### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="allstate_claims_severity",
    dataset_year="2016",
    domain_str="insurance",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/allstate-claims-severity",
    download_description="""
We use the train.csv from the Kaggle competition.

kaggle competitions download -c allstate-claims-severity -f train.csv && unzip train.csv.zip &&  rm train.csv.zip
mkdir -p local-data-warehouse/allstate_claims_severity && mv train.csv local-data-warehouse/allstate_claims_severity/
""",
    # References
    academic_reference_bibtex=r"""@misc{Ferguson2016AllstateClaimsSeverity,
  author = {Dana Ferguson and Meg Risdal and NoTrick and Sara R. Sillah and Tim Emmerling and Will Cukierski},
  title  = {Allstate Claims Severity},
  year   = {2016},
  howpublished = {\url{https://kaggle.com/competitions/allstate-claims-severity},
  note   = {Kaggle competition}
}
""",
    academic_reference_bibtex_key="Ferguson2016AllstateClaimsSeverity",
    license="Kaggle Competition Rules",
    data_tags=["IID", "Anonymized"],
    curation_comments="""
We start with the train.csv from Kaggle.

- The data has been anonymized.
- Top Kaggle solutions did not perform any relevant preprocessing.
- We drop the ID column, as it does not contain any signal.
- The data contains 1 duplicate row when ignoring the target. We drop this artifact.
- We log scale the target.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="loss",
    problem_type="regression",
    objective_metric_name="mae",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(dataset_mold.path / "train.csv")
print("Loaded data shape:", df.shape)

cat_features = [c for c in list(df) if c.startswith("cat")]
df[cat_features] = df[cat_features].astype("category")
df = df.drop(columns=["id"])

# Drop duplicates w/o target column
df = df.drop_duplicates(subset=[c for c in df.columns if c != task_mold.target_column_name])

# log scale the target
df[task_mold.target_column_name] = np.log(df[task_mold.target_column_name])

df = df.reset_index(drop=True)

Loaded data shape: (188318, 132)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 188,317
Columns: 131

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,cat10,cat11,cat12,cat13,cat14,cat15,cat16,cat17,cat18,cat19,cat20,cat21,cat22,cat23,cat24,cat25,cat26,cat27,cat28,cat29,cat30,cat31,cat32,cat33,cat34,cat35,cat36,cat37,cat38,cat39,cat40,cat41,cat42,cat43,cat44,cat45,cat46,cat47,cat48,cat49,cat50,cat51,cat52,cat53,cat54,cat55,cat56,cat57,cat58,cat59,cat60,cat61,cat62,cat63,cat64,cat65,cat66,cat67,cat68,cat69,cat70,cat71,cat72,cat73,cat74,cat75,cat76,cat77,cat78,cat79,cat80,cat81,cat82,cat83,cat84,cat85,cat86,cat87,cat88,cat89,cat90,cat91,cat92,cat93,cat94,cat95,cat96,cat97,cat98,cat99,cat100,cat101,cat102,cat103,cat104,cat105,cat106,cat107,cat108,cat109,cat110,cat111,cat112,cat113,cat114,cat115,cat116,cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,cont14,loss
0,A,B,A,B,A,A,A,A,B,A,B,A,A,A,A,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,A,D,B,B,D,D,B,D,C,B,D,B,A,A,A,A,A,D,B,C,E,A,C,T,B,G,A,A,I,E,G,J,G,BU,BC,C,AS,S,A,O,LB,0.726300,0.245921,0.187583,0.789639,0.310061,0.718367,0.335060,0.30260,0.67135,0.83510,0.569745,0.594646,0.822493,0.714843,7.702186
1,A,B,A,A,A,A,A,A,B,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,D,B,B,D,D,A,B,C,B,D,B,A,A,A,A,A,D,D,C,E,E,D,T,L,F,A,A,E,E,I,K,K,BI,CQ,A,AV,BM,A,O,DP,0.330514,0.737068,0.592681,0.614134,0.885834,0.438917,0.436585,0.60087,0.35127,0.43919,0.338312,0.366307,0.611431,0.304496,7.157424
2,A,B,A,A,B,A,A,A,B,B,B,B,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,D,B,B,B,D,B,D,C,B,B,B,A,A,A,A,A,D,D,C,E,E,A,D,L,O,A,B,E,F,H,F,A,AB,DK,A,C,AF,A,I,GK,0.261841,0.358319,0.484196,0.236924,0.397069,0.289648,0.315545,0.27320,0.26076,0.32446,0.381398,0.373424,0.195709,0.774425,8.008063
3,B,B,A,B,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,A,A,A,D,B,B,D,D,D,B,C,B,D,B,A,A,A,A,A,D,D,C,E,E,D,T,I,D,A,A,E,E,I,K,K,BI,CS,C,N,AE,A,O,DJ,0.321594,0.555782,0.527991,0.373816,0.422268,0.440945,0.391128,0.31796,0.32128,0.44467,0.327915,0.321570,0.605077,0.602642,6.845720
4,A,B,A,B,A,A,A,A,B,B,A,B,A,A,A,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,A,A,A,A,D,B,D,B,D,B,B,C,B,B,C,A,A,A,B,H,D,B,D,E,E,A,P,F,J,A,A,D,E,K,G,B,H,C,C,Y,BM,A,K,CK,0.273204,0.159990,0.527991,0.473202,0.704268,0.178193,0.247408,0.24564,0.22089,0.21230,0.204687,0.202213,0.246011,0.432606,7.924380

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,cat1,category,0,0.0,2,"A, B"
1,cat2,category,0,0.0,2,"A, B"
2,cat3,category,0,0.0,2,"A, B"
3,cat4,category,0,0.0,2,"A, B"
4,cat5,category,0,0.0,2,"A, B"
5,cat6,category,0,0.0,2,"A, B"
6,cat7,category,0,0.0,2,"A, B"
7,cat8,category,0,0.0,2,"A, B"
8,cat9,category,0,0.0,2,"A, B"
9,cat10,category,0,0.0,2,"A, B"
10,cat11,category,0,0.0,2,"A, B"
11,cat12,category,0,0.0,2,"A, B"
12,cat13,category,0,0.0,2,"A, B"
13,cat14,category,0,0.0,2,"A, B"
14,cat15,category,0,0.0,2,"A, B"
15,cat16,category,0,0.0,2,"A, B"
16,cat17,category,0,0.0,2,"A, B"
17,cat18,category,0,0.0,2,"A, B"
18,cat19,category,0,0.0,2,"A, B"
19,cat20,category,0,0.0,2,"A, B"
20,cat21,category,0,0.0,2,"A, B"
21,cat22,category,0,0.0,2,"A, B"
22,cat23,category,0,0.0,2,"A, B"
23,cat24,category,0,0.0,2,"A, B"
24,cat25,category,0,0.0,2,"A, B"
25,cat26,category,0,0.0,2,"A, B"
26,cat27,category,0,0.0,2,"A, B"
27,cat28,category,0,0.0,2,"A, B"
28,cat29,category,0,0.0,2,"A, B"
29,cat30,category,0,0.0,2,"A, B"
30,cat31,category,0,0.0,2,"A, B"
31,cat32,category,0,0.0,2,"A, B"
32,cat33,category,0,0.0,2,"A, B"
33,cat34,category,0,0.0,2,"A, B"
34,cat35,category,0,0.0,2,"A, B"
35,cat36,category,0,0.0,2,"A, B"
36,cat37,category,0,0.0,2,"A, B"
37,cat38,category,0,0.0,2,"A, B"
38,cat39,category,0,0.0,2,"A, B"
39,cat40,category,0,0.0,2,"A, B"
40,cat41,category,0,0.0,2,"A, B"
41,cat42,category,0,0.0,2,"A, B"
42,cat43,category,0,0.0,2,"A, B"
43,cat44,category,0,0.0,2,"A, B"
44,cat45,category,0,0.0,2,"A, B"
45,cat46,category,0,0.0,2,"A, B"
46,cat47,category,0,0.0,2,"A, B"
47,cat48,category,0,0.0,2,"A, B"
48,cat49,category,0,0.0,2,"A, B"
49,cat50,category,0,0.0,2,"A, B"
50,cat51,category,0,0.0,2,"A, B"
51,cat52,category,0,0.0,2,"A, B"
52,cat53,category,0,0.0,2,"A, B"
53,cat54,category,0,0.0,2,"A, B"
54,cat55,category,0,0.0,2,"A, B"
55,cat56,category,0,0.0,2,"A, B"
56,cat57,category,0,0.0,2,"A, B"
57,cat58,category,0,0.0,2,"A, B"
58,cat59,category,0,0.0,2,"A, B"
59,cat60,category,0,0.0,2,"A, B"
60,cat61,category,0,0.0,2,"A, B"
61,cat62,category,0,0.0,2,"A, B"
62,cat63,category,0,0.0,2,"A, B"
63,cat64,category,0,0.0,2,"A, B"
64,cat65,category,0,0.0,2,"A, B"
65,cat66,category,0,0.0,2,"A, B"
66,cat67,category,0,0.0,2,"A, B"
67,cat68,category,0,0.0,2,"A, B"
68,cat69,category,0,0.0,2,"A, B"
69,cat70,category,0,0.0,2,"A, B"
70,cat71,category,0,0.0,2,"A, B"
71,cat72,category,0,0.0,2,"A, B"
72,cat73,category,0,0.0,3,"A, B, C"
73,cat74,category,0,0.0,3,"A, B, C"
74,cat75,category,0,0.0,3,"A, B, C"
75,cat76,category,0,0.0,3,"A, B, C"
76,cat77,category,0,0.0,4,"D, C, B, A"
77,cat78,category,0,0.0,4,"B, A, C, D"
78,cat79,category,0,0.0,4,"B, D, A, C"
79,cat80,category,0,0.0,4,"D, B, C, A"
80,cat81,category,0,0.0,4,"D, B, C, A"
81,cat82,category,0,0.0,4,"B, A, D, C"
82,cat83,category,0,0.0,4,"B, A, D, C"
83,cat84,category,0,0.0,4,"C, A, D, B"
84,cat85,category,0,0.0,4,"B, C, A, D"
85,cat86,category,0,0.0,4,"B, D, C, A"
86,cat87,category,0,0.0,4,"B, D, C, A"
87,cat88,category,0,0.0,4,"A, D, E, B"
88,cat89,category,0,0.0,8,"A, B, C, D, E, I, G, H"
89,cat90,category,0,0.0,7,"A, B, C, D, E, F, G"
90,cat91,category,0,0.0,8,"A, B, G, C, D, E, F, H"
91,cat92,category,0,0.0,7,"A, H, B, C, I, D, F"
92,cat93,category,0,0.0,5,"D, C, B, E, A"
93,cat94,category,0,0.0,7,"D, B, C, A, F, E, G"
94,cat95,category,0,0.0,5,"C, D, E, A, B"
95,cat96,category,0,0.0,8,"E, D, B, G, F, A, C, I"
96,cat97,category,0,0.0,7,"C, E, A, G, D, F, B"
97,cat98,category,0,0.0,5,"A, D, C, E, B"
98,cat99,category,0,0.0,16,"P, T, R, D, S, N, K, F, E, C"
99,cat100,category,0,0.0,15,"F, I, L, K, G, J, H, A, N, B"
100,cat101,category,0,0.0,19,"A, D, C, G, F, J, I, M, L, Q"
101,cat102,category,0,0.0,9,"A, B, C, E, D, G, F, H, J"
102,cat103,category,0,0.0,13,"A, B, C, D, E, F, G, H, I, J"
103,cat104,category,0,0.0,17,"E, G, D, F, H, K, I, C, L, J"
104,cat105,category,0,0.0,20,"E, F, G, D, H, I, J, K, C, M"
105,cat106,category,0,0.0,17,"G, H, F, I, J, E, K, L, D, M"
106,cat107,category,0,0.0,20,"F, G, H, J, K, I, E, L, D, M"
107,cat108,category,0,0.0,11,"B, K, G, D, F, A, E, I, H, C"
108,cat109,category,0,0.0,84,"BI, AB, BU, K, G, BQ, N, M, BO, BH"
109,cat110,category,0,0.0,131,"CL, EG, CS, EB, CO, BT, EL, BC, DW, CQ"
110,cat111,category,0,0.0,16,"A, C, E, G, I, K, M, O, Q, S"
111,cat112,category,0,0.0,51,"E, AH, AS, J, AF, AN, N, U, AV, AK"
112,cat113,category,0,0.0,61,"BM, AE, L, AX, Y, K, S, X, AF, AN"
113,cat114,category,0,0.0,19,"A, C, E, J, F, N, I, R, L, U"
114,cat115,category,0,0.0,23,"K, O, J, N, P, L, M, Q, I, H"
115,cat116,category,0,0.0,326,"HK, DJ, CK, DP, GS, CR, HX, DC, HG, IE"
116,cont1,float64,0,0.0,647,"0.4758, 0.5033, 0.3254, 0.5467, 0.3305, 0.4845, 0.4801, 0.8943, 0.4657, 0.6293"
117,cont2,float64,0,0.0,33,"0.5558, 0.6208, 0.4888, 0.7371, 0.4222, 0.7858, 0.6818, 0.3583, 0.2991, 0.2459"
118,cont3,float64,0,0.0,76,"0.5498, 0.5061, 0.4842, 0.528, 0.337, 0.6137, 0.6928, 0.4406, 0.5927, 0.5714"
119,cont4,float64,0,0.0,112,"0.3738, 0.4732, 0.3274, 0.3096, 0.4529, 0.4327, 0.4128, 0.2087, 0.5344, 0.6238"
120,cont5,float64,0,0.0,141,"0.2811, 0.4223, 0.3027, 0.3724, 0.5942, 0.7832, 0.5517, 0.5345, 0.3888, 0.4911"
121,cont6,float64,0,0.0,2573,"0.3735, 0.3645, 0.2401, 0.3177, 0.2011, 0.2207, 0.2525, 0.3796, 0.2203, 0.3361"
122,cont7,float64,0,0.0,5632,"0.3475, 0.3502, 0.3819, 0.2837, 0.3624, 0.3594, 0.391, 0.4012, 0.2799, 0.4093"
123,cont8,float64,0,0.0,201,"0.2685, 0.3608, 0.2456, 0.2976, 0.278, 0.5835, 0.3391, 0.3499, 0.318, 0.3128"
124,cont9,float64,0,0.0,347,"0.3825, 0.4435, 0.3086, 0.3213, 0.4147, 0.3945, 0.4623, 0.3985, 0.3437, 0.5042"
125,cont10,float64,0,0.0,174,"0.4502, 0.4392, 0.8351, 0.4778, 0.396, 0.5056, 0.2123, 0.4447, 0.3646, 0.3749"
126,cont11,float64,0,0.0,326,"0.3418, 0.4533, 0.4922, 0.2454, 0.644, 0.415, 0.3076, 0.5697, 0.6075, 0.223"
127,cont12,float64,0,0.0,328,"0.4813, 0.4434, 0.2417, 0.3523, 0.335, 0.3019, 0.5946, 0.7145, 0.7857, 0.6309"
128,cont13,float64,0,0.0,353,"0.3392, 0.69, 0.3044, 0.3333, 0.3158, 0.3186, 0.3452, 0.2987, 0.6114, 0.6051"
129,cont14,float64,0,0.0,18740,"0.2977, 0.7401, 0.2971, 0.2294, 0.2294, 0.2331, 0.2957, 0.2378, 0.7245, 0.2978"
130,loss,float64,0,0.0,158223,"6.363, 6.9847, 5.7991, 6.5511, 5.6348, 6.6846, 5.7038, 4.382, 6.6201, 6.1738"

In [6]:
# Numeric Feature Statistics
numeric_stats

           count      mean       std       min        max
cont1   188317.0  0.493861  0.187641  0.000016   0.984975
cont2   188317.0  0.507189  0.207202  0.001149   0.862654
cont3   188317.0  0.498920  0.202104  0.002634   0.944251
cont4   188317.0  0.491810  0.211291  0.176921   0.954297
cont5   188317.0  0.487428  0.209027  0.281143   0.983674
cont6   188317.0  0.490945  0.205273  0.012683   0.997162
cont7   188317.0  0.484971  0.178451  0.069503   1.000000
cont8   188317.0  0.486437  0.199371  0.236880   0.980200
cont9   188317.0  0.485507  0.181661  0.000080   0.995400
cont10  188317.0  0.498066  0.185877  0.000000   0.994980
cont11  188317.0  0.493512  0.209737  0.035321   0.998742
cont12  188317.0  0.493152  0.209427  0.036232   0.998484
cont13  188317.0  0.493139  0.212777  0.000228   0.988494
cont14  188317.0  0.495718  0.222487  0.179722   0.844848
loss    188317.0  7.685274  0.811865 -0.400478  11.703647

In [7]:
# Categorical Feature Statistics
cat_stats

            value   count    pct
column rank
cat1   1        A  141549  75.17
       2        B   46768  24.83
cat10  1        A  160212  85.08
       2        B   28105  14.92
cat100 1        F   42970  22.82
       2        I   39932  21.20
       3        L   19961  10.60
       4        K   13817   7.34
       5        G   12935   6.87
cat101 1        A  106720  56.67
       2        D   17171   9.12
       3        C   16971   9.01
       4        G   10944   5.81
       5        F   10139   5.38
cat102 1        A  177273  94.14
       2        B    5155   2.74
       3        C    4929   2.62
       4        E     482   0.26
       5        D     449   0.24
cat103 1        A  123736  65.71
       2        B   33342  17.71
       3        C   16508   8.77
       4        D    7806   4.15
       5        E    4473   2.38
cat104 1        E   42925  22.79
       2        G   40660  21.59
       3        D   27611  14.66
       4        F   19227  10.21
       5        H   17187   9.13
cat105 1        E   76492  40.62
       2        F   62892  33.40
       3        G   20613  10.95
       4        D   12172   6.46
       5        H   11258   5.98
cat106 1        G   47164  25.05
       2        H   37713  20.03
       3        F   36143  19.19
       4        I   21433  11.38
       5        J   18281   9.71
cat107 1        F   47310  25.12
       2        G   28560  15.17
       3        H   23461  12.46
       4        J   22405  11.90
       5        K   20236  10.75
cat108 1        B   65511  34.79
       2        K   42435  22.53
       3        G   21421  11.37
       4        D   19160  10.17
       5        F   10242   5.44
cat109 1       BI  152918  81.20
       2       AB   21932  11.65
       3       BU    3142   1.67
       4        K    2999   1.59
       5        G    1353   0.72
cat11  1        A  168185  89.31
       2        B   20132  10.69
cat110 1       CL   25305  13.44
       2       EG   24654  13.09
       3       CS   24592  13.06
       4       EB   21395  11.36
       5       CO   17495   9.29
cat111 1        A  128394  68.18
       2        C   32401  17.21
       3        E   14682   7.80
       4        G    7039   3.74
       5        I    3578   1.90
cat112 1        E   25148  13.35
       2       AH   18638   9.90
       3       AS   17669   9.38
       4        J   16222   8.61
       5       AF    9368   4.97
cat113 1       BM   26191  13.91
       2       AE   22030  11.70
       3        L   13058   6.93
       4       AX   12661   6.72
       5        Y   11374   6.04
cat114 1        A  131693  69.93
       2        C   16793   8.92
       3        E   16474   8.75
       4        J    8199   4.35
       5        F    7905   4.20
cat115 1        K   43866  23.29
       2        O   26813  14.24
       3        J   23894  12.69
       4        N   22438  11.92
       5        P   21538  11.44
cat116 1       HK   21061  11.18
       2       DJ   20244  10.75
       3       CK   10162   5.40
       4       DP    9202   4.89
       5       GS    8736   4.64
cat12  1        A  159824  84.87
       2        B   28493  15.13
cat13  1        A  168850  89.66
       2        B   19467  10.34
cat14  1        A  186040  98.79
       2        B    2277   1.21
cat15  1        A  188283  99.98
       2        B      34   0.02
cat16  1        A  181842  96.56
       2        B    6475   3.44
cat17  1        A  187008  99.30
       2        B    1309   0.70
cat18  1        A  187330  99.48
       2        B     987   0.52
cat19  1        A  186509  99.04
       2        B    1808   0.96
cat2   1        A  106720  56.67
       2        B   81597  43.33
cat20  1        A  188113  99.89
       2        B     204   0.11
cat21  1        A  187904  99.78
       2        B     413   0.22
cat22  1        A  188274  99.98
       2        B      43   0.02
cat23  1        A  157444  83.61
       2        B   30873  16.39
cat24  1        A  181976  96.63
       2        B    6341   3.37
cat25  1        A  169968  90.26
       2        B   18349   9.74
cat26  1        A  177118  94.05
       2        B   11199   5.95
cat27  1        A  168249  89.34
       2        B   20068  10.66
cat28  1        A  180937  96.08
       2        B    7380   3.92
cat29  1        A  184592  98.02
       2        B    3725   1.98
cat3   1        A  177992  94.52
       2        B   10325   5.48
cat30  1        A  184759  98.11
       2        B    3558   1.89
cat31  1        A  182979  97.17
       2        B    5338   2.83
cat32  1        A  187106  99.36
       2        B    1211   0.64
cat33  1        A  187360  99.49
       2        B     957   0.51
cat34  1        A  187733  99.69
       2        B     584   0.31
cat35  1        A  188104  99.89
       2        B     213   0.11
cat36  1        A  156312  83.00
       2        B   32005  17.00
cat37  1        A  165728  88.00
       2        B   22589  12.00
cat38  1        A  169322  89.91
       2        B   18995  10.09
cat39  1        A  183392  97.38
       2        B    4925   2.62
cat4   1        A  128394  68.18
       2        B   59923  31.82
cat40  1        A  180118  95.65
       2        B    8199   4.35
cat41  1        A  181176  96.21
       2        B    7141   3.79
cat42  1        A  186622  99.10
       2        B    1695   0.90
cat43  1        A  184109  97.77
       2        B    4208   2.23
cat44  1        A  172715  91.72
       2        B   15602   8.28
cat45  1        A  183990  97.70
       2        B    4327   2.30
cat46  1        A  187435  99.53
       2        B     882   0.47
cat47  1        A  187616  99.63
       2        B     701   0.37
cat48  1        A  188048  99.86
       2        B     269   0.14
cat49  1        A  179126  95.12
       2        B    9191   4.88
cat5   1        A  123736  65.71
       2        B   64581  34.29
cat50  1        A  137611  73.07
       2        B   50706  26.93
cat51  1        A  187070  99.34
       2        B    1247   0.66
cat52  1        A  179504  95.32
       2        B    8813   4.68
cat53  1        A  172948  91.84
       2        B   15369   8.16
cat54  1        A  183761  97.58
       2        B    4556   2.42
cat55  1        A  188172  99.92
       2        B     145   0.08
cat56  1        A  188135  99.90
       2        B     182   0.10
cat57  1        A  185295  98.40
       2        B    3022   1.60
cat58  1        A  188078  99.87
       2        B     239   0.13
cat59  1        A  188017  99.84
       2        B     300   0.16
cat6   1        A  131693  69.93
       2        B   56624  30.07
cat60  1        A  187871  99.76
       2        B     446   0.24
cat61  1        A  187595  99.62
       2        B     722   0.38
cat62  1        A  188272  99.98
       2        B      45   0.02
cat63  1        A  188238  99.96
       2        B      79   0.04
cat64  1        A  188270  99.98
       2        B      47   0.02
cat65  1        A  186055  98.80
       2        B    2262   1.20
cat66  1        A  179981  95.57
       2        B    8336   4.43
cat67  1        A  187625  99.63
       2        B     692   0.37
cat68  1        A  188175  99.92
       2        B     142   0.08
cat69  1        A  188010  99.84
       2        B     307   0.16
cat7   1        A  183743  97.57
       2        B    4574   2.43
cat70  1        A  188294  99.99
       2        B      23   0.01
cat71  1        A  178645  94.86
       2        B    9672   5.14
cat72  1        A  118321  62.83
       2        B   69996  37.17
cat73  1        A  154275  81.92
       2        B   34016  18.06
       3        C      26   0.01
cat74  1        A  184730  98.10
       2        B    3561   1.89
       3        C      26   0.01
cat75  1        A  154306  81.94
       2        B   34010  18.06
       3        C       1   0.00
cat76  1        A  181346  96.30
       2        B    6183   3.28
       3        C     788   0.42
cat77  1        D  187502  99.57
       2        C     408   0.22
       3        B     358   0.19
       4        A      49   0.03
cat78  1        B  186525  99.05
       2        A     788   0.42
       3        C     645   0.34
       4        D     359   0.19
cat79  1        B  152928  81.21
       2        D   26657  14.16
       3        A    7064   3.75
       4        C    1668   0.89
cat8   1        A  177273  94.14
       2        B   11044   5.86
cat80  1        D  137504  73.02
       2        B   46538  24.71
       3        C    3492   1.85
       4        A     783   0.42
cat81  1        D  154384  81.98
       2        B   24132  12.81
       3        C    9013   4.79
       4        A     788   0.42
cat82  1        B  147535  78.34
       2        A   19322  10.26
       3        D   18805   9.99
       4        C    2655   1.41
cat83  1        B  141534  75.16
       2        A   26038  13.83
       3        D   15787   8.38
       4        C    4958   2.63
cat84  1        C  154938  82.28
       2        A   29450  15.64
       3        D    3498   1.86
       4        B     431   0.23
cat85  1        B  186004  98.77
       2        C    1011   0.54
       3        A     788   0.42
       4        D     514   0.27
cat86  1        B  103851  55.15
       2        D   72587  38.55
       3        C   10290   5.46
       4        A    1589   0.84
cat87  1        B  166991  88.68
       2        D   11719   6.22
       3        C    8819   4.68
       4        A     788   0.42
cat88  1        A  168925  89.70
       2        D   19302  10.25
       3        E      83   0.04
       4        B       7   0.00
cat89  1        A  183743  97.57
       2        B    4312   2.29
       3        C     220   0.12
       4        D      33   0.02
       5        E       5   0.00
cat9   1        A  113121  60.07
       2        B   75196  39.93
cat90  1        A  177992  94.52
       2        B    9515   5.05
       3        C     728   0.39
       4        D      70   0.04
       5        E       6   0.00
cat91  1        A  111027  58.96
       2        B   42630  22.64
       3        G   26734  14.20
       4        C    6400   3.40
       5        D    1149   0.61
cat92  1        A  124688  66.21
       2        H   62901  33.40
       3        B     628   0.33
       4        C      62   0.03
       5        I      26   0.01
cat93  1        D  150237  79.78
       2        C   35787  19.00
       3        B    1133   0.60
       4        E     728   0.39
       5        A     432   0.23
cat94  1        D  121642  64.59
       2        B   51709  27.46
       3        C   13623   7.23
       4        A     738   0.39
       5        F     494   0.26
cat95  1        C   87531  46.48
       2        D   79524  42.23
       3        E   17417   9.25
       4        A    3736   1.98
       5        B     109   0.06
cat96  1        E  174360  92.59
       2        D    7921   4.21
       3        B    2957   1.57
       4        G    2665   1.42
       5        F     343   0.18
cat97  1        C   78127  41.49
       2        E   47450  25.20
       3        A   41969  22.29
       4        G   16745   8.89
       5        D    3779   2.01
cat98  1        A  105491  56.02
       2        D   50557  26.85
       3        C   21485  11.41
       4        E   10242   5.44
       5        B     542   0.29
cat99  1        P   79454  42.19
       2        T   72591  38.55
       3        R   10290   5.46
       4        D    8844   4.70
       5        S    7045   3.74

In [8]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,0.093,-0.312,0.659,0.009,log1p,1156787.0,184996813.6,exponential

## Task Curation

In [10]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [11]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

## Export

In [12]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019c0a71-9029-727e-a7d9-a4c48238c737
a0ec8284df3fbc11d51def0c245d4d6c501f647a7708984fe7fbba51488a6efe