### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="lending_club_1m",
    version_from_unique_name="lending_club",
    version_comment="""
To sub-sample this dataset, we only take the first year to obtain 814751 train and 276431.
""",
    # same as lending_club.ipynb
    dataset_year="2018",
    domain_str="finance",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://zenodo.org/records/11295916",
    download_description="""
It seems the official download portal from https://www.lendingclub.com is gone. So we can only utilize artifacts from the past, which seem to go up to 2018.
Old script and source: https://github.com/nateGeorge/preprocess_lending_club_data

From all the artifacts we found online, this seems to be the newest: https://www.kaggle.com/datasets/wordsforthewise/lending-club/data
And the following paper (https://arxiv.org/abs/2401.16458) curated this dataset https://zenodo.org/records/11295916 for tabular-text learning.

Other artifacts:
- https://www.kaggle.com/datasets/adarshsng/lending-club-loan-data-csv
- https://www.kaggle.com/datasets/imsparsh/lending-club-loan-dataset-2007-2011

wget https://zenodo.org/records/11295916/files/LC_loans_granting_model_dataset.csv?download=1
mkdir -p local-data-warehouse/lending_club && mv LC_loans_granting_model_dataset.csv?download=1 local-data-warehouse/lending_club
kaggle datasets download wordsforthewise/lending-club -f accepted_2007_to_2018Q4.csv.gz && mv accepted_2007_to_2018Q4.csv.gz local-data-warehouse/lending_club/
""",
    # References
    academic_reference_bibtex=r"""@article{sanz2025credit,
  title={Credit Risk Meets Large Language Models: Building a Risk Indicator from Loan Descriptions in P2P Lending},
  author={Sanz-Guerrero, Mario and Arroyo, Javier},
  journal={Inteligencia Artificial},
  volume={28},
  number={75},
  pages={220--247},
  year={2025}
}
""",
    academic_reference_bibtex_key="sanz2025credit",
    license="CC0: Public Domain", # On Kaggle, likely not true TOS from the website.
    data_tags=["Non-IID", "Temporal", "Spatial"],
    curation_comments="""
We start withe data from Sanz-Guerrero et al. (2025). This data is already well preprocessed and curated for the task and used for tabular-text learning. However, we noticed a lot variables from the original data are missing that can be added to the task without invalidating the task or introducing data leakage. Thus, we also merge new features from the original data into the version from Sanz-Guerrero et al. (2025).

- This is a datasets where the description is very often empty or a standard phrase. So the model needs to be able to handle cases with a lot of missing data in the text modality, and also cases where the text is rarely informative. This is a common case in real-world tabular-text datasets, and it is important to have it represented in our benchmark.
- We reverse the ordinal encoding of the target.
- We reverse the name change of "revenue" back to "annual_inc".
- We also create a sec_app_fico_n like the fico_n from anz-Guerrero et al. (2025).
- We drop rows where "application_type" is missing as these rows have consistent missing values across features and likely represent some data loading artifact.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Default",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="Default",
    time_on="issue_d",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

original_df = pd.read_csv(dataset_mold.path /  "accepted_2007_to_2018Q4.csv.gz")
df = pd.read_csv(dataset_mold.path / "LC_loans_granting_model_dataset.csv?download=1")
print("Loaded data shape:", df.shape)
print("Original data shape:", original_df.shape)

# 0 for fully paid loans and a 1 for defaulted loans.
df["Default"] = df["Default"].map({0: "Fully Paid", 1: "Defaulted"})

df = df.rename(columns={"revenue": "annual_inc"})

# Transform     "sec_app_fico_range_low"    "sec_app_fico_range_high", to sec_app_fico_n
original_df["sec_app_fico_n"] = (original_df["sec_app_fico_range_low"] + original_df["sec_app_fico_range_high"]) / 2

new_features_from_original = original_df[[
    "id",
    # known when the loan is granted, so it can be used as a feature without data leakage.
    #   This, however, would create a different task, in that we want to train a model that the company uses after their own risk assessment but before granting the loan.
    #   Given that these values and grades are often determined by an internal model of the company, they might also introduce an unknown bias.
    #   We stick to treating the task as a pre-assessment modelling. An alternative version could also function as a "stacking" model that takes the output of the company's internal model as an input.
    #   The variables for this task are:
    # "term",
    # "int_rate",
    # "installment",
    # "grade",
    # "sub_grade",
    # "verification_status",
    # Known at the start / from data source even without the company assessing the risk, so it can be used no matter the use case.
    "emp_title",
    "disbursement_method",
    "acc_now_delinq",
    "acc_open_past_24mths",
    "all_util",
    "sec_app_fico_n",
    # annual_inc	annual_inc_joint -> were already merged by prior work
    # fico_range_high fico_range_low -> transformed before into avg fico
    "application_type", "avg_cur_bal", "bc_open_to_buy", "bc_util", "chargeoff_within_12_mths", "collections_12_mths_ex_med", "delinq_2yrs", "delinq_amnt", "earliest_cr_line", "il_util", "inq_fi", "inq_last_12m", "inq_last_6mths", "max_bal_bc", "mo_sin_old_il_acct", "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc", "mths_since_last_delinq", "mths_since_last_major_derog", "mths_since_last_record", "mths_since_rcnt_il", "mths_since_recent_bc", "mths_since_recent_bc_dlq", "mths_since_recent_inq", "mths_since_recent_revol_delinq", "num_accts_ever_120_pd", "num_actv_bc_tl", "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl", "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0", "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m", "num_tl_op_past_12m", "open_acc", "open_acc_6m", "open_il_12m", "open_il_24m", "open_act_il", "open_rv_12m", "open_rv_24m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec", "pub_rec_bankruptcies", "revol_bal", "revol_util", "tax_liens", "tot_coll_amt", "tot_cur_bal", "tot_hi_cred_lim", "total_acc", "total_bal_ex_mort", "total_bal_il", "total_bc_limit", "total_cu_tl", "total_il_high_credit_limit", "total_rev_hi_lim", "revol_bal_joint", "sec_app_earliest_cr_line", "sec_app_inq_last_6mths", "sec_app_mort_acc", "sec_app_open_acc", "sec_app_revol_util", "sec_app_open_act_il", "sec_app_num_rev_accts", "sec_app_chargeoff_within_12_mths", "sec_app_collections_12_mths_ex_med", "sec_app_mths_since_last_major_derog", "sec_app_fico_range_low", "sec_app_fico_range_high", # dti dti_joint -> already merged by prior work via max
]]

# Merge new features into the curated version of the dataset.
df = df.merge(new_features_from_original, on="id", how="left")
del new_features_from_original, original_df

as_cat_type = [
    # There are only two options on this website. This is ordinal technically, so we could treat it as a number too.
    "home_ownership_n",
    "application_type",
    "disbursement_method",
    "emp_length",
    "Default",
    "experience_c",
    "purpose",
]
as_string_type = [
    "emp_title",
    "addr_state",
    "zip_code",
    "title",
    "desc",
]

df["issue_d"] = pd.to_datetime(df["issue_d"], format="%b-%Y")
df["sec_app_earliest_cr_line"] = pd.to_datetime(df["sec_app_earliest_cr_line"], format="%b-%Y")
df["earliest_cr_line"] = pd.to_datetime(df["earliest_cr_line"], format="%b-%Y")

for c in as_string_type:
    nan_mask = df[c].isna()
    df.loc[nan_mask, c] = np.nan
    df[c] = df[c].astype("string")


df[as_cat_type] = df[as_cat_type].astype("category")

df = df[~df["application_type"].isna()]
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
df = df.drop(columns=[
    "id",  # meaningless identifier
    "experience_c", # constant after preprocessing
])

/tmp/ipykernel_613182/1013934924.py:4: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  original_df = pd.read_csv(dataset_mold.path /  "accepted_2007_to_2018Q4.csv.gz")

/tmp/ipykernel_613182/1013934924.py:5: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dataset_mold.path / "LC_loans_granting_model_dataset.csv?download=1")

Loaded data shape: (1347681, 15)
Original data shape: (2260701, 151)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
    duplicate_column_check=False, # skip
)

Warning: Found 1 constant feature(s) with 1 or fewer unique values (including NaNs): ['desc']

#### Dataset Overview
Rows: 1,310,259
Columns: 97
Use sampling: True (sample size: 131,026)
Get missing and unique counts per column...

missing/unique per-col:   0%|          | 0/97 [00:00<?, ?it/s]

Get example values per column...

examples per-col:   0%|          | 0/97 [00:00<?, ?it/s]

Get numeric feature statistics...

numeric stats:   0%|          | 0/83 [00:00<?, ?it/s]

Get cat stats...

cat stats:   0%|          | 0/14 [00:00<?, ?it/s]

Get target stats...
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['tot_hi_cred_lim', 'tot_cur_bal', 'emp_title', 'total_bal_ex_mort', 'total_il_high_credit_limit', 'total_bal_il', 'desc', 'revol_bal', 'avg_cur_bal', 'bc_open_to_buy']

Rows remaining as candidates after top-10 filter: 203 (of 1,310,259)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,issue_d,annual_inc,dti_n,loan_amnt,fico_n,emp_length,purpose,home_ownership_n,addr_state,zip_code,Default,title,desc,emp_title,disbursement_method,acc_now_delinq,acc_open_past_24mths,all_util,sec_app_fico_n,application_type,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,collections_12_mths_ex_med,delinq_2yrs,delinq_amnt,earliest_cr_line,il_util,inq_fi,inq_last_12m,inq_last_6mths,max_bal_bc,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_last_delinq,mths_since_last_major_derog,mths_since_last_record,mths_since_rcnt_il,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,open_acc,open_acc_6m,open_il_12m,open_il_24m,open_act_il,open_rv_12m,open_rv_24m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec,pub_rec_bankruptcies,revol_bal,revol_util,tax_liens,tot_coll_amt,tot_cur_bal,tot_hi_cred_lim,total_acc,total_bal_ex_mort,total_bal_il,total_bc_limit,total_cu_tl,total_il_high_credit_limit,total_rev_hi_lim,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,sec_app_fico_range_low,sec_app_fico_range_high
0,2014-04-01,61000.0,10.06,25850,682.0,10+ years,debt_consolidation,RENT,GA,300xx,Fully Paid,Debt consolidation,<NA>,Asset Manager,Cash,0.0,1.0,NaN,NaN,Individual,1259.0,7882.0,65.3,0.0,0.0,0.0,0.0,1989-05-01,NaN,NaN,NaN,0.0,NaN,NaN,299.0,17.0,17.0,0.0,NaN,NaN,52.0,NaN,67.0,NaN,12.0,NaN,0.0,8.0,11.0,8.0,8.0,0.0,13.0,13.0,11.0,13.0,0.0,0.0,0.0,0.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,100.0,37.5,1.0,0.0,16365.0,36.0,1.0,0.0,16365.0,45400.0,13.0,16365.0,NaN,22700.0,NaN,0.0,45400.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-05-01,115000.0,8.31,28000,692.0,10+ years,debt_consolidation,RENT,NY,112xx,Fully Paid,Debt consolidation,<NA>,System Administrator,Cash,0.0,2.0,NaN,NaN,Individual,49682.0,8123.0,82.1,0.0,0.0,0.0,0.0,2003-09-01,NaN,NaN,NaN,0.0,NaN,110.0,140.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN,24.0,NaN,23.0,NaN,0.0,5.0,6.0,5.0,7.0,1.0,6.0,10.0,6.0,7.0,0.0,0.0,0.0,1.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,100.0,80.0,0.0,0.0,37318.0,80.6,0.0,0.0,347773.0,376300.0,13.0,37318.0,NaN,45300.0,NaN,0.0,46300.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-02-01,30000.0,8.68,12000,702.0,NI,credit_card,OWN,CA,952xx,Fully Paid,Credit card refinancing,credit card consolidation.,<NA>,Cash,0.0,3.0,NaN,NaN,Individual,1167.0,14004.0,44.0,0.0,0.0,0.0,0.0,1963-10-01,NaN,NaN,NaN,0.0,NaN,127.0,604.0,8.0,8.0,0.0,NaN,NaN,67.0,NaN,9.0,NaN,NaN,NaN,0.0,5.0,7.0,8.0,9.0,2.0,10.0,11.0,7.0,10.0,0.0,0.0,0.0,2.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,100.0,12.5,4.0,0.0,11672.0,40.4,4.0,0.0,11672.0,28900.0,13.0,11672.0,NaN,25000.0,NaN,0.0,28900.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-12-01,85000.0,7.58,3000,667.0,< 1 year,home_improvement,MORTGAGE,SC,294xx,Fully Paid,Home improvement,<NA>,Project Manager,Cash,0.0,5.0,33.0,NaN,Individual,43592.0,1796.0,62.6,0.0,0.0,0.0,0.0,2006-04-01,35.0,0.0,5.0,0.0,2304.0,116.0,115.0,8.0,3.0,4.0,65.0,66.0,39.0,49.0,8.0,NaN,3.0,NaN,1.0,2.0,3.0,2.0,4.0,2.0,5.0,7.0,3.0,7.0,0.0,0.0,0.0,2.0,7.0,1.0,0.0,0.0,1.0,1.0,4.0,92.3,0.0,1.0,0.0,3274.0,28.7,0.0,726.0,305144.0,327236.0,13.0,10644.0,7370.0,4800.0,1.0,21336.0,11400.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014-11-01,81435.0,17.27,25200,677.0,10+ years,debt_consolidation,MORTGAGE,VA,224xx,Defaulted,Debt consolidation,<NA>,Assistant Principal,Cash,0.0,6.0,NaN,NaN,Individual,39249.0,1392.0,88.7,0.0,0.0,0.0,0.0,2000-09-01,NaN,NaN,NaN,0.0,NaN,148.0,170.0,8.0,8.0,5.0,NaN,NaN,NaN,NaN,75.0,NaN,7.0,NaN,0.0,4.0,8.0,4.0,8.0,12.0,8.0,13.0,8.0,11.0,0.0,0.0,0.0,3.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,100.0,75.0,0.0,0.0,37909.0,86.9,0.0,0.0,431743.0,456444.0,30.0,53579.0,NaN,12300.0,NaN,19969.0,43600.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,emp_length,category,0.0,0.00,12.0,"10+ years, 2 years, 3 years, < 1 year, 1 year, 5 years, 4 years, NI, 6 years, 8 years"
1,purpose,category,0.0,0.00,14.0,"debt_consolidation, credit_card, home_improvement, other, major_purchase, medical, small_business, car, moving, vacation"
2,home_ownership_n,category,0.0,0.00,4.0,"MORTGAGE, RENT, OWN, OTHER"
3,Default,category,0.0,0.00,2.0,"Fully Paid, Defaulted"
4,disbursement_method,category,0.0,0.00,2.0,"Cash, DirectPay"
5,application_type,category,0.0,0.00,2.0,"Individual, Joint App"
6,sec_app_earliest_cr_line,datetime64[ns],1292511.0,98.65,570.0,"2006-03-01 00:00:00, 2006-08-01 00:00:00, 2004-07-01 00:00:00, 2005-06-01 00:00:00, 2004-12-01 00:00:00, 2007-08-01 00:00:00, 2004-08-01 00:00:00, 2002-08-01 00:00:00, 2005-10-01 00:00:00, 2005-12-01 00:00:00"
7,issue_d,datetime64[ns],0.0,0.00,129.0,"2016-03-01 00:00:00, 2015-10-01 00:00:00, 2015-07-01 00:00:00, 2015-12-01 00:00:00, 2014-10-01 00:00:00, 2016-02-01 00:00:00, 2015-11-01 00:00:00, 2015-04-01 00:00:00, 2015-08-01 00:00:00, 2015-01-01 00:00:00"
8,earliest_cr_line,datetime64[ns],0.0,0.00,739.0,"2002-08-01 00:00:00, 2001-08-01 00:00:00, 2001-10-01 00:00:00, 2002-09-01 00:00:00, 2003-09-01 00:00:00, 2000-08-01 00:00:00, 2002-10-01 00:00:00, 2000-10-01 00:00:00, 2000-09-01 00:00:00, 2004-09-01 00:00:00"
9,sec_app_mths_since_last_major_derog,float64,1303942.0,99.52,112.0,"1.0, 4.0, 44.0, 9.0, 33.0, 2.0, 12.0, 60.0, 55.0, 51.0"
10,sec_app_revol_util,float64,1292825.0,98.67,1112.0,"0.0, 93.3, 88.5, 28.0, 90.1, 69.6, 64.1, 96.6, 78.3, 77.3"
11,sec_app_fico_n,float64,1292511.0,98.65,60.0,"672.0, 662.0, 677.0, 667.0, 682.0, 657.0, 647.0, 652.0, 687.0, 642.0"
12,revol_bal_joint,float64,1292512.0,98.65,15472.0,"18319.0, 48689.0, 22049.0, 22507.0, 21407.0, 0.0, 38772.0, 13859.0, 12811.0, 21280.0"
13,sec_app_inq_last_6mths,float64,1292511.0,98.65,7.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0"
14,sec_app_mort_acc,float64,1292511.0,98.65,17.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
15,sec_app_open_acc,float64,1292511.0,98.65,54.0,"9.0, 7.0, 10.0, 8.0, 11.0, 5.0, 6.0, 12.0, 13.0, 14.0"
16,sec_app_open_act_il,float64,1292511.0,98.65,33.0,"1.0, 2.0, 3.0, 0.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
17,sec_app_num_rev_accts,float64,1292511.0,98.65,68.0,"6.0, 7.0, 8.0, 9.0, 12.0, 10.0, 5.0, 11.0, 13.0, 4.0"
18,sec_app_chargeoff_within_12_mths,float64,1292511.0,98.65,14.0,"0.0, 1.0, 2.0, 3.0, 7.0, 5.0, 6.0"
19,sec_app_collections_12_mths_ex_med,float64,1292511.0,98.65,11.0,"0.0, 1.0, 2.0, 3.0, 5.0"
20,sec_app_fico_range_low,float64,1292511.0,98.65,60.0,"670.0, 660.0, 675.0, 665.0, 680.0, 655.0, 645.0, 650.0, 685.0, 640.0"
21,sec_app_fico_range_high,float64,1292511.0,98.65,60.0,"674.0, 664.0, 679.0, 669.0, 684.0, 659.0, 649.0, 654.0, 689.0, 644.0"
22,mths_since_last_record,float64,1088483.0,83.07,125.0,"72.0, 71.0, 77.0, 62.0, 81.0, 69.0, 67.0, 76.0, 65.0, 64.0"
23,mths_since_recent_bc_dlq,float64,998723.0,76.22,167.0,"27.0, 32.0, 38.0, 28.0, 47.0, 36.0, 25.0, 14.0, 29.0, 13.0"
24,mths_since_last_major_derog,float64,964883.0,73.64,173.0,"47.0, 41.0, 44.0, 49.0, 45.0, 43.0, 30.0, 38.0, 40.0, 46.0"
25,mths_since_recent_revol_delinq,float64,870864.0,66.47,167.0,"13.0, 12.0, 14.0, 9.0, 19.0, 8.0, 6.0, 25.0, 16.0, 20.0"
26,il_util,float64,865149.0,66.03,234.0,"86.0, 78.0, 77.0, 81.0, 83.0, 80.0, 76.0, 79.0, 85.0, 70.0"
27,mths_since_rcnt_il,float64,809413.0,61.78,341.0,"7.0, 4.0, 6.0, 3.0, 5.0, 8.0, 9.0, 2.0, 10.0, 12.0"
28,all_util,float64,795858.0,60.74,169.0,"67.0, 66.0, 58.0, 62.0, 63.0, 55.0, 64.0, 68.0, 59.0, 69.0"
29,inq_fi,float64,795807.0,60.74,30.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
30,inq_last_12m,float64,795808.0,60.74,42.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
31,max_bal_bc,float64,795807.0,60.74,27282.0,"0.0, 3000.0, 2000.0, 3700.0, 4000.0, 8.0, 3500.0, 2900.0, 5000.0, 5200.0"
32,open_acc_6m,float64,795808.0,60.74,19.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
33,open_il_12m,float64,795807.0,60.74,19.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
34,open_il_24m,float64,795807.0,60.74,31.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
35,open_act_il,float64,795807.0,60.74,49.0,"1.0, 2.0, 3.0, 0.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
36,open_rv_12m,float64,795807.0,60.74,27.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
37,open_rv_24m,float64,795807.0,60.74,47.0,"1.0, 2.0, 3.0, 0.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
38,total_bal_il,float64,795807.0,60.74,116607.0,"0.0, 13628.0, 7989.0, 10000.0, 4897.0, 15029.0, 10830.0, 26356.0, 15182.0, 17829.0"
39,total_cu_tl,float64,795808.0,60.74,53.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
40,mths_since_last_delinq,float64,660989.0,50.45,163.0,"12.0, 13.0, 8.0, 6.0, 9.0, 14.0, 10.0, 7.0, 16.0, 15.0"
41,mths_since_recent_inq,float64,166314.0,12.69,26.0,"1.0, 2.0, 0.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
42,num_tl_120dpd_2m,float64,111601.0,8.52,6.0,"0.0, 1.0, 2.0, 6.0"
43,mo_sin_old_il_acct,float64,99866.0,7.62,519.0,"132.0, 122.0, 130.0, 125.0, 128.0, 129.0, 120.0, 126.0, 133.0, 123.0"
44,pct_tl_nvr_dlq,float64,62788.0,4.79,630.0,"100.0, 95.0, 90.0, 96.0, 92.9, 92.3, 91.7, 90.9, 88.9, 87.5"
45,avg_cur_bal,float64,62655.0,4.78,76350.0,"0.0, 1905.0, 2380.0, 1602.0, 2873.0, 2526.0, 2269.0, 3476.0, 2161.0, 1998.0"
46,mo_sin_old_rev_tl_op,float64,62635.0,4.78,756.0,"127.0, 132.0, 140.0, 131.0, 128.0, 129.0, 135.0, 125.0, 126.0, 138.0"
47,mo_sin_rcnt_rev_tl_op,float64,62635.0,4.78,284.0,"2.0, 3.0, 4.0, 1.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
48,mo_sin_rcnt_tl,float64,62634.0,4.78,193.0,"2.0, 3.0, 4.0, 1.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
49,num_accts_ever_120_pd,float64,62634.0,4.78,39.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
50,num_actv_bc_tl,float64,62634.0,4.78,34.0,"3.0, 2.0, 4.0, 1.0, 5.0, 6.0, 7.0, 8.0, 0.0, 9.0"
51,num_actv_rev_tl,float64,62634.0,4.78,52.0,"4.0, 5.0, 3.0, 6.0, 2.0, 7.0, 8.0, 9.0, 1.0, 10.0"
52,num_bc_tl,float64,62634.0,4.78,68.0,"6.0, 5.0, 7.0, 4.0, 8.0, 3.0, 9.0, 10.0, 11.0, 2.0"
53,num_il_tl,float64,62634.0,4.78,114.0,"4.0, 3.0, 5.0, 2.0, 6.0, 7.0, 8.0, 1.0, 9.0, 10.0"
54,num_op_rev_tl,float64,62634.0,4.78,73.0,"6.0, 5.0, 7.0, 8.0, 4.0, 9.0, 10.0, 3.0, 11.0, 12.0"
55,num_rev_accts,float64,62635.0,4.78,107.0,"10.0, 11.0, 9.0, 12.0, 8.0, 13.0, 14.0, 7.0, 15.0, 6.0"
56,num_rev_tl_bal_gt_0,float64,62634.0,4.78,46.0,"4.0, 5.0, 3.0, 6.0, 2.0, 7.0, 8.0, 9.0, 1.0, 10.0"
57,num_tl_30dpd,float64,62634.0,4.78,5.0,"0.0, 1.0, 2.0, 3.0, 4.0"
58,num_tl_90g_dpd_24m,float64,62634.0,4.78,29.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
59,num_tl_op_past_12m,float64,62634.0,4.78,32.0,"1.0, 2.0, 0.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
60,tot_coll_amt,float64,62634.0,4.78,12745.0,"0.0, 50.0, 100.0, 75.0, 200.0, 150.0, 80.0, 60.0, 70.0, 65.0"
61,tot_cur_bal,float64,62634.0,4.78,396601.0,"0.0, 7069.0, 4294.0, 27736.0, 13981.0, 15134.0, 19860.0, 29232.0, 11348.0, 31440.0"
62,tot_hi_cred_lim,float64,62634.0,4.78,423124.0,"17700.0, 15500.0, 9000.0, 10000.0, 16500.0, 22000.0, 15000.0, 16000.0, 19100.0, 10900.0"
63,total_il_high_credit_limit,float64,62634.0,4.78,161405.0,"0.0, 10000.0, 15000.0, 20000.0, 5000.0, 12000.0, 25000.0, 8000.0, 6000.0, 7000.0"
64,total_rev_hi_lim,float64,62634.0,4.78,26533.0,"10000.0, 16500.0, 15500.0, 15000.0, 17000.0, 16000.0, 11500.0, 13500.0, 12500.0, 18000.0"
65,bc_util,float64,56670.0,4.33,1442.0,"0.0, 98.0, 97.0, 96.0, 99.0, 95.0, 94.0, 92.0, 93.0, 91.0"
66,percent_bc_gt_75,float64,56321.0,4.30,245.0,"0.0, 100.0, 50.0, 33.3, 66.7, 25.0, 75.0, 20.0, 40.0, 60.0"
67,bc_open_to_buy,float64,55913.0,4.27,74380.0,"0.0, 500.0, 2000.0, 3000.0, 1000.0, 2500.0, 1500.0, 5000.0, 800.0, 4000.0"
68,mths_since_recent_bc,float64,55006.0,4.20,490.0,"3.0, 2.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 1.0"
69,num_bc_sats,float64,50948.0,3.89,51.0,"3.0, 4.0, 2.0, 5.0, 6.0, 7.0, 1.0, 8.0, 9.0, 10.0"
70,num_sats,float64,50948.0,3.89,82.0,"9.0, 10.0, 8.0, 11.0, 7.0, 12.0, 13.0, 6.0, 14.0, 5.0"
71,acc_open_past_24mths,float64,42388.0,3.24,55.0,"3.0, 4.0, 2.0, 5.0, 6.0, 1.0, 7.0, 8.0, 0.0, 9.0"
72,mort_acc,float64,42388.0,3.24,39.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
73,total_bal_ex_mort,float64,42388.0,3.24,176628.0,"0.0, 13981.0, 7069.0, 19655.0, 20068.0, 26930.0, 32576.0, 11158.0, 17688.0, 17183.0"
74,total_bc_limit,float64,42388.0,3.24,16995.0,"0.0, 5000.0, 6000.0, 7000.0, 10000.0, 4000.0, 8000.0, 6500.0, 3000.0, 9000.0"
75,revol_util,float64,823.0,0.06,1370.0,"0.0, 55.0, 54.0, 62.0, 48.0, 53.0, 39.0, 58.0, 42.0, 38.0"
76,annual_inc,float64,0.0,0.00,64458.0,"60000.0, 50000.0, 65000.0, 70000.0, 40000.0, 80000.0, 75000.0, 45000.0, 55000.0, 100000.0"
77,dti_n,float64,0.0,0.00,7010.0,"21.6, 13.2, 19.2, 12.0, 18.0, 14.4, 17.89, 15.6, 0.0, 24.0"
78,fico_n,float64,0.0,0.00,38.0,"662.0, 672.0, 667.0, 677.0, 682.0, 687.0, 692.0, 697.0, 702.0, 707.0"
79,acc_now_delinq,float64,0.0,0.00,8.0,"0.0, 1.0, 2.0, 3.0, 4.0, 6.0"
80,chargeoff_within_12_mths,float64,0.0,0.00,11.0,"0.0, 1.0, 2.0, 3.0, 4.0, 6.0, 5.0"
81,collections_12_mths_ex_med,float64,0.0,0.00,15.0,"0.0, 1.0, 2.0, 3.0, 4.0, 7.0, 6.0, 5.0"
82,delinq_2yrs,float64,0.0,0.00,31.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
83,delinq_amnt,float64,0.0,0.00,1965.0,"0.0, 65000.0, 50.0, 52.0, 54.0, 57.0, 58.0, 75.0, 27.0, 60.0"
84,inq_last_6mths,float64,1.0,0.00,9.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0"
85,open_acc,float64,0.0,0.00,83.0,"9.0, 10.0, 8.0, 11.0, 7.0, 12.0, 13.0, 6.0, 14.0, 5.0"
86,pub_rec,float64,0.0,0.00,36.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0"
87,pub_rec_bankruptcies,float64,6.0,0.00,11.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0, 9.0, 7.0"
88,revol_bal,float64,0.0,0.00,83069.0,"0.0, 5390.0, 8530.0, 5980.0, 5372.0, 6982.0, 7481.0, 4177.0, 7944.0, 6177.0"
89,tax_liens,float64,0.0,0.00,35.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0"
90,total_acc,float64,0.0,0.00,142.0,"20.0, 21.0, 22.0, 19.0, 18.0, 23.0, 17.0, 16.0, 24.0, 25.0"
91,loan_amnt,int64,0.0,0.00,1547.0,"10000, 12000, 20000, 15000, 35000, 5000, 8000, 6000, 16000, 25000"
92,desc,string,1191160.0,90.91,109539.0,"Debt consolidation., Debt Consolidation., debt consolidation., Pay off credit cards., Credit card consolidation., pay off credit cards., Credit Card Consolidation., Pay off high interest credit cards., To pay off credit cards., Consolidate credit cards."
93,emp_title,string,83048.0,6.34,370596.0,"Teacher, Manager, Owner, Registered Nurse, RN, Supervisor, Sales, Driver, Project Manager, Office Manager"
94,title,string,16043.0,1.22,58108.0,"Debt consolidation, Credit card refinancing, Home improvement, Other, Major purchase, Debt Consolidation, Medical expenses, Business, Car financing, Vacation"
95,addr_state,string,0.0,0.00,51.0,"CA, TX, NY, FL, IL, NJ, PA, OH, GA, NC"
96,zip_code,string,1.0,0.00,942.0,"945xx, 750xx, 112xx, 606xx, 300xx, 891xx, 331xx, 770xx, 100xx, 070xx"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
annual_inc,131026.0,77432.859017,66269.682201,2000.0,7000000.0
dti_n,131026.0,18.351067,10.941811,0.0,999.0
loan_amnt,131026.0,14494.346160,8723.635823,1000.0,40000.0
fico_n,131026.0,698.092077,31.828085,662.0,847.5
acc_now_delinq,131026.0,0.005136,0.078604,0.0,6.0
acc_open_past_24mths,126783.0,4.696111,3.187263,0.0,50.0
all_util,51366.0,58.046704,20.950480,0.0,184.0
sec_app_fico_n,1781.0,667.870298,47.222585,542.0,832.0
avg_cur_bal,124690.0,13487.800160,16240.565864,0.0,646339.0
bc_open_to_buy,125438.0,10206.234769,15444.151180,0.0,320558.0
bc_util,125359.0,59.989950,28.333959,0.0,173.2
chargeoff_within_12_mths,131026.0,0.008907,0.108435,0.0,6.0
collections_12_mths_ex_med,131026.0,0.016875,0.141669,0.0,7.0
delinq_2yrs,131026.0,0.314411,0.861443,0.0,27.0
delinq_amnt,131026.0,16.776205,1043.125313,0.0,249925.0
il_util,44546.0,71.348202,23.080102,0.0,558.0
inq_fi,51369.0,1.086979,1.600507,0.0,48.0
inq_last_12m,51369.0,2.307209,2.550758,0.0,67.0
inq_last_6mths,131026.0,0.655664,0.938724,0.0,8.0
max_bal_bc,51369.0,5551.699722,5224.162993,0.0,87470.0
mo_sin_old_il_acct,121071.0,125.919089,52.177898,0.0,534.0
mo_sin_old_rev_tl_op,124692.0,181.472701,94.436037,2.0,789.0
mo_sin_rcnt_rev_tl_op,124692.0,13.134756,16.376962,0.0,295.0
mo_sin_rcnt_tl,124692.0,7.854530,8.706269,0.0,194.0
mort_acc,126783.0,1.673781,1.996939,0.0,29.0
mths_since_last_delinq,64928.0,34.334309,21.926519,0.0,161.0
mths_since_last_major_derog,34516.0,43.649815,21.340526,0.0,162.0
mths_since_last_record,22365.0,70.918802,26.427283,0.0,120.0
mths_since_rcnt_il,50070.0,19.565988,25.050800,0.0,411.0
mths_since_recent_bc,125516.0,23.813020,30.788236,0.0,534.0
mths_since_recent_bc_dlq,31124.0,39.698496,22.661327,0.0,158.0
mths_since_recent_inq,114466.0,6.731300,5.861409,0.0,25.0
mths_since_recent_revol_delinq,43906.0,35.862160,22.436092,0.0,161.0
num_accts_ever_120_pd,124692.0,0.508325,1.324836,0.0,34.0
num_actv_bc_tl,124692.0,3.646064,2.247522,0.0,32.0
num_actv_rev_tl,124692.0,5.649127,3.313675,0.0,63.0
num_bc_sats,125872.0,4.739235,2.947076,0.0,42.0
num_bc_tl,124692.0,8.102894,4.786621,0.0,65.0
num_il_tl,124692.0,8.576797,7.359625,0.0,101.0
num_op_rev_tl,124692.0,8.278999,4.556870,0.0,79.0
num_rev_accts,124692.0,14.607721,8.122749,2.0,104.0
num_rev_tl_bal_gt_0,124692.0,5.596831,3.219559,0.0,43.0
num_sats,125872.0,11.640611,5.474631,0.0,80.0
num_tl_120dpd_2m,119792.0,0.000910,0.035492,0.0,6.0
num_tl_30dpd,124692.0,0.003296,0.062793,0.0,4.0
num_tl_90g_dpd_24m,124692.0,0.088298,0.497645,0.0,26.0
num_tl_op_past_12m,124692.0,2.181054,1.843241,0.0,25.0
open_acc,131026.0,11.601934,5.469524,0.0,80.0
open_acc_6m,51369.0,1.055345,1.214559,0.0,14.0
open_il_12m,51369.0,0.779945,0.988689,0.0,11.0
open_il_24m,51369.0,1.745352,1.674411,0.0,23.0
open_act_il,51369.0,2.787420,2.955099,0.0,32.0
open_rv_12m,51369.0,1.424731,1.574743,0.0,22.0
open_rv_24m,51369.0,3.004108,2.726066,0.0,43.0
pct_tl_nvr_dlq,124676.0,94.208670,8.654990,0.0,100.0
percent_bc_gt_75,125391.0,45.253546,35.983055,0.0,100.0
pub_rec,131026.0,0.218025,0.627346,0.0,47.0
pub_rec_bankruptcies,131026.0,0.135431,0.379334,0.0,9.0
revol_bal,131026.0,16219.660144,21324.819131,0.0,1039013.0
revol_util,130955.0,51.861781,24.565118,0.0,154.9
tax_liens,131026.0,0.054356,0.431350,0.0,46.0
tot_coll_amt,124692.0,226.253120,1733.384459,0.0,146917.0
tot_cur_bal,124692.0,140987.349028,156083.814166,0.0,3701271.0
tot_hi_cred_lim,124692.0,174152.243119,175856.910319,0.0,9999999.0
total_acc,131026.0,25.004488,11.977154,2.0,130.0
total_bal_ex_mort,126783.0,49707.189876,47131.112325,0.0,1167999.0
total_bal_il,51369.0,35915.650451,42626.666034,0.0,706085.0
total_bc_limit,126783.0,21699.968379,21563.702305,0.0,425150.0
total_cu_tl,51369.0,1.607837,2.802529,0.0,42.0
total_il_high_credit_limit,124692.0,42208.495669,43079.920871,0.0,1027358.0
total_rev_hi_lim,124692.0,32727.501468,32645.502321,0.0,1252500.0
revol_bal_joint,1780.0,31755.602247,27549.737867,0.0,280272.0
sec_app_inq_last_6mths,1781.0,0.772038,1.120154,0.0,6.0
sec_app_mort_acc,1781.0,1.687816,1.863973,0.0,13.0
sec_app_open_acc,1781.0,11.319483,6.656551,0.0,46.0
sec_app_revol_util,1751.0,57.180697,26.774390,0.0,135.8
sec_app_open_act_il,1781.0,2.943852,3.186205,0.0,32.0
sec_app_num_rev_accts,1781.0,12.782706,8.282000,0.0,57.0
sec_app_chargeoff_within_12_mths,1781.0,0.047165,0.340223,0.0,7.0
sec_app_collections_12_mths_ex_med,1781.0,0.083099,0.356088,0.0,5.0
sec_app_mths_since_last_major_derog,633.0,36.243286,23.978251,0.0,107.0
sec_app_fico_range_low,1781.0,665.870298,47.222585,540.0,830.0
sec_app_fico_range_high,1781.0,669.870298,47.222585,544.0,834.0

In [7]:
# Categorical Feature Statistics
cat_stats

                                                 value   count    pct
column                   rank
Default                  1                  Fully Paid  104830  80.01
                         2                   Defaulted   26196  19.99
addr_state               1                          CA   18981  14.49
                         2                          TX   10841   8.27
                         3                          NY   10729   8.19
                         4                          FL    9316   7.11
                         5                          IL    4919   3.75
application_type         1                  Individual  128572  98.13
                         2                   Joint App    2454   1.87
desc                     1                        <NA>  119191  90.97
                         2         Debt consolidation.     117   0.09
                         3         Debt Consolidation.      76   0.06
                         4         debt consolidation.      55   0.04
                         5       Pay off credit cards.      28   0.02
disbursement_method      1                        Cash  130382  99.51
                         2                   DirectPay     644   0.49
earliest_cr_line         1         2002-08-01 00:00:00     911    0.7
                         2         2001-08-01 00:00:00     902   0.69
                         3         2001-10-01 00:00:00     885   0.68
                         4         2002-09-01 00:00:00     882   0.67
                         5         2003-09-01 00:00:00     875   0.67
emp_length               1                   10+ years   43186  32.96
                         2                     2 years   11747   8.97
                         3                     3 years   10616    8.1
                         4                    < 1 year   10498   8.01
                         5                      1 year    8470   6.46
emp_title                1                        <NA>    8393   6.41
                         2                     Teacher    2116   1.61
                         3                     Manager    1908   1.46
                         4                       Owner     976   0.74
                         5            Registered Nurse     848   0.65
home_ownership_n         1                    MORTGAGE   65022  49.63
                         2                        RENT   52035  39.71
                         3                         OWN   13921  10.62
                         4                       OTHER      48   0.04
issue_d                  1         2016-03-01 00:00:00    4594   3.51
                         2         2015-10-01 00:00:00    4328    3.3
                         3         2015-07-01 00:00:00    4156   3.17
                         4         2015-12-01 00:00:00    3883   2.96
                         5         2014-10-01 00:00:00    3685   2.81
purpose                  1          debt_consolidation   76137  58.11
                         2                 credit_card   28842  22.01
                         3            home_improvement    8559   6.53
                         4                       other    7409   5.65
                         5              major_purchase    2854   2.18
sec_app_earliest_cr_line 1                        <NA>  129245  98.64
                         2         2006-03-01 00:00:00      21   0.02
                         3         2006-08-01 00:00:00      19   0.01
                         4         2004-07-01 00:00:00      19   0.01
                         5         2005-06-01 00:00:00      18   0.01
title                    1          Debt consolidation   64840  49.49
                         2     Credit card refinancing   24527  18.72
                         3            Home improvement    7343    5.6
                         4                       Other    6337   4.84
                         5              Major purchase    2319   1.77
zip_code                 1                       945xx    1407   1.07
                         2                       750xx    1385   1.06
                         3                       112xx    1330   1.02
                         4                       606xx    1145   0.87
                         5                       300xx    1134   0.87

In [8]:
# Target Distribution
target_df

              count    pct
Default
Fully Paid  1049280  80.08
Defaulted    260979  19.92

## Task Curation

In [9]:
time_df = df.copy()
time_df["year_month"] = time_df[task_mold.time_on].dt.to_period("Y")

# 1) Total number of samples per month
monthly_totals = (
    time_df
    .groupby("year_month")
    .size()
    .rename("total_samples")
)

# Optional: sort by month and convert PeriodIndex to timestamp (month start)
result = monthly_totals.sort_index()
result.index = result.index.to_timestamp()
result

year_month
2008-01-01       836
2009-01-01      4716
2010-01-01     11536
2011-01-01     19776
2012-01-01     51396
2013-01-01    132915
2014-01-01    221034
2015-01-01    372542
2016-01-01    276431
2017-01-01    164085
2018-01-01     54992
Freq: YS-JAN, Name: total_samples, dtype: int64

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import subsample_temporal
# Sort by time
df = df.sort_values(by=task_mold.time_on).reset_index(drop=True)


ref_date  = pd.Timestamp("2016")
train_index = df[
    df[task_mold.time_on] < ref_date
].index.tolist()
test_index = df[
    (df[task_mold.time_on].dt.year == ref_date.year)
].index.tolist()

df, test_index, test_index = subsample_temporal(
    df=df,
    train_idx=train_index,
    test_idx=test_index,
    stratify_on=task_mold.stratify_on,
)

splits = {0: {
    0: (train_index, test_index)
}}

print(f"Split: Train size: {len(train_index)}, Test size: {len(test_index)}")
assert df[task_mold.time_on].iloc[train_index].max() < df[task_mold.time_on].iloc[test_index].min()

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="""We try to create splits that simulate a model deployed to solve the task.

The official data is updated monthly but has not enough data per month to create large enough test splits. We opt for simulating a model that is refit every year to obtain a robust test set instead. This introduces the unrealistic downside of data shift across a year that would not exist in a real-world model. We create 1 test split (2016). We use all data before the test year as training data.
""",
    splits=splits,
    time_horizon=1,
    time_horizon_unit="years",
)

Split: Train size: 814751, Test size: 250000

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...

Saving curated container to lending_club/versions/019d738c-5edd-7437-9116-e3bc87a8b0c5

019d738c-5edd-7437-9116-e3bc87a8b0c5
c80c2cea9dfb4b67e6ba42ff9d4c96fcd93aeba045bfc33904ccbbba608c6d52