### Dataset and Task Metadata

In [61]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="predict_students_dropout_and_academic_success",
    dataset_year="2021",
    domain_str="education",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success",
    download_description="""
    We download the data from the UCI repository and uzip it to a predefined folder.

    mkdir -p local-data-warehouse/predict_students_dropout_and_academic_success/ && wget -P local-data-warehouse/predict_students_dropout_and_academic_success/ https://archive.ics.uci.edu/static/public/697/predict+students+dropout+and+academic+success.zip && unzip local-data-warehouse/predict_students_dropout_and_academic_success/predict+students+dropout+and+academic+success.zip -d local-data-warehouse/predict_students_dropout_and_academic_success/  && rm local-data-warehouse/predict_students_dropout_and_academic_success/predict+students+dropout+and+academic+success.zip
""",
    # References
    academic_reference_bibtex="""@inproceedings{martins2021studentperformance,
  title={Early prediction of student’s performance in higher education: A case study},
  author={Martins, M{\'o}nica V and Tolledo, Daniel and Machado, Jorge and Baptista, Lu{\'\i}s MT and Realinho, Valentim},
  booktitle={World Conference on Information Systems and Technologies},
  pages={166--175},
  year={2021},
  organization={Springer}
}

""",
    academic_reference_bibtex_key="martins2021studentperformance",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
- We renamed the column Nacionality to Nationality
- We removed whitespaces and special characters from the feature names.
- We mapped the values of the factorized variables to their original values
""",
    
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Academic_outcome",
    problem_type="multiclass_classification",
    objective_metric_name="log_loss",
    # For classification
    stratify_on="Academic_outcome",
)

## Preprocessing

In [50]:
import pandas as pd

df = pd.read_csv(dataset_mold.path / "data.csv", sep=";", header=0)

feature_names = [
    "Marital_status",
    "Application_mode",
    "Application_order",
    "Course",
    "Daytime_evening_attendance",
    "Previous_qualification",
    "Previous_qualification_grade",
    "Nationality",
    "Mother_qualification",
    "Father_qualification",
    "Mother_occupation",
    "Father_occupation",
    "Admission_grade",
    "Displaced",
    "Educational_special_needs",
    "Debtor",
    "Tuition_fees_up_to_date",
    "Gender",
    "Scholarship_holder",
    "Age_at_enrollment",
    "International",
    "Curricular_units_1st_sem_credited",
    "Curricular_units_1st_sem_enrolled",
    "Curricular_units_1st_sem_evaluations",
    "Curricular_units_1st_sem_approved",
    "Curricular_units_1st_sem_grade",
    "Curricular_units_1st_sem_without_evaluations",
    "Curricular_units_2nd_sem_credited",
    "Curricular_units_2nd_sem_enrolled",
    "Curricular_units_2nd_sem_evaluations",
    "Curricular_units_2nd_sem_approved",
    "Curricular_units_2nd_sem_grade",
    "Curricular_units_2nd_sem_without_evaluations",
    "Unemployment_rate",
    "Inflation_rate",
    "GDP",
    "Academic_outcome"
]

df.columns = feature_names

cat_features = [
    "Marital_status",
    "Application_mode",
    "Course",
    "Daytime_evening_attendance",
    "Previous_qualification",
    "Previous_qualification_grade",
    "Nationality",
    "Mother_qualification",
    "Father_qualification",
    "Mother_occupation",
    "Father_occupation",
    "Displaced",
    "Educational_special_needs",
    "Debtor",
    "Tuition_fees_up_to_date",
    "Gender",
    "Scholarship_holder",
    "Age_at_enrollment",
    "International",
    "Academic_outcome"
]

df[cat_features] = df[cat_features].astype("category")

maps = {
    "International": {1: "yes", 0: "no"},
    "Marital_status": {
        1: "single",
        2: "married",
        3: "widower",
        4: "divorced",
        5: "facto union",
        6: "legally separated",
    },
    "Application_mode": {
        1: "1st phase - general contingent",
        2: "Ordinance No. 612/93",
        5: "1st phase - special contingent (Azores Island)",
        7: "Holders of other higher courses",
        10: "Ordinance No. 854-B/99",
        15: "International student (bachelor)",
        16: "1st phase - special contingent (Madeira Island)",
        17: "2nd phase - general contingent",
        18: "3rd phase - general contingent",
        26: "Ordinance No. 533-A/99, item b2) (Different Plan)",
        27: "Ordinance No. 533-A/99, item b3 (Other Institution)",
        39: "Over 23 years old",
        42: "Transfer",
        43: "Change of course",
        44: "Technological specialization diploma holders",
        51: "Change of institution/course",
        53: "Short cycle diploma holders",
        57: "Change of institution/course (International)",
    },
    "Course": {
        33: "Biofuel Production Technologies",
        171: "Animation and Multimedia Design",
        8014: "Social Service (evening attendance)",
        9003: "Agronomy",
        9070: "Communication Design",
        9085: "Veterinary Nursing",
        9119: "Informatics Engineering",
        9130: "Equinculture",
        9147: "Management",
        9238: "Social Service",
        9254: "Tourism",
        9500: "Nursing",
        9556: "Oral Hygiene",
        9670: "Advertising and Marketing Management",
        9773: "Journalism and Communication",
        9853: "Basic Education",
        9991: "Management (evening attendance)",
    },
    "Daytime_evening_attendance": {1: "daytime", 0: "evening"},
    "Previous_qualification": {
        1: "Secondary education",
        2: "Higher education - bachelor's degree",
        3: "Higher education - degree",
        4: "Higher education - master's",
        5: "Higher education - doctorate",
        6: "Frequency of higher education",
        9: "12th year of schooling - not completed",
        10: "11th year of schooling - not completed",
        12: "Other - 11th year of schooling",
        14: "10th year of schooling",
        15: "10th year of schooling - not completed",
        19: "Basic education 3rd cycle (9th/10th/11th year) or equiv.",
        38: "Basic education 2nd cycle (6th/7th/8th year) or equiv.",
        39: "Technological specialization course",
        40: "Higher education - degree (1st cycle)",
        42: "Professional higher technical course",
        43: "Higher education - master (2nd cycle)",
    },
    "Nationality": {
        1: "Portuguese",
        2: "German",
        6: "Spanish",
        11: "Italian",
        13: "Dutch",
        14: "English",
        17: "Lithuanian",
        21: "Angolan",
        22: "Cape Verdean",
        24: "Guinean",
        25: "Mozambican",
        26: "Santomean",
        32: "Turkish",
        41: "Brazilian",
        62: "Romanian",
        100: "Moldova (Republic of)",
        101: "Mexican",
        103: "Ukrainian",
        105: "Russian",
        108: "Cuban",
        109: "Colombian",
    },
    "Mother_qualification": {
        1: "Secondary Education - 12th Year of Schooling or Eq.",
        2: "Higher Education - Bachelor's Degree",
        3: "Higher Education - Degree",
        4: "Higher Education - Master's",
        5: "Higher Education - Doctorate",
        6: "Frequency of Higher Education",
        9: "12th Year of Schooling - Not Completed",
        10: "11th Year of Schooling - Not Completed",
        11: "7th Year (Old)",
        12: "Other - 11th Year of Schooling",
        14: "10th Year of Schooling",
        18: "General commerce course",
        19: "Basic Education 3rd Cycle",
        22: "Technical-professional course",
        26: "7th year of schooling",
        27: "2nd cycle of the general high school course",
        29: "9th Year of Schooling - Not Completed",
        30: "8th year of schooling",
        34: "Unknown",
        35: "Can't read or write",
        36: "Can read without having a 4th year of schooling",
        37: "Basic education 1st cycle (4th/5th year) or equiv.",
        38: "Basic Education 2nd Cycle",
        39: "Technological specialization course",
        40: "Higher education - degree (1st cycle)",
        41: "Specialized higher studies course",
        42: "Professional higher technical course",
        43: "Higher Education - Master (2nd cycle)",
        44: "Higher Education - Doctorate (3rd cycle)",
    },
    "Father_qualification": {
        1: "Secondary Education - 12th Year of Schooling or Eq.",
        2: "Higher Education - Bachelor's Degree",
        3: "Higher Education - Degree",
        4: "Higher Education - Master's",
        5: "Higher Education - Doctorate",
        6: "Frequency of Higher Education",
        9: "12th Year of Schooling - Not Completed",
        10: "11th Year of Schooling - Not Completed",
        11: "7th Year (Old)",
        12: "Other - 11th Year of Schooling",
        13: "2nd year complementary high school course",
        14: "10th Year of Schooling",
        18: "General commerce course",
        19: "Basic Education 3rd Cycle",
        20: "Complementary High School Course",
        22: "Technical-professional course",
        25: "Complementary High School Course - not concluded",
        26: "7th year of schooling",
        27: "2nd cycle of the general high school course",
        29: "9th Year of Schooling - Not Completed",
        30: "8th year of schooling",
        31: "General Course of Administration and Commerce",
        33: "Supplementary Accounting and Administration",
        34: "Unknown",
        35: "Can't read or write",
        36: "Can read without having a 4th year of schooling",
        37: "Basic education 1st cycle",
        38: "Basic Education 2nd Cycle",
        39: "Technological specialization course",
        40: "Higher education - degree (1st cycle)",
        41: "Specialized higher studies course",
        42: "Professional higher technical course",
        43: "Higher Education - Master (2nd cycle)",
        44: "Higher Education - Doctorate (3rd cycle)",
    },
    "Mother_occupation": {
        0: "Student",
        1: "Representatives of Legislative/Executive Bodies",
        2: "Specialists in Intellectual/Scientific Activities",
        3: "Intermediate Level Technicians and Professions",
        4: "Administrative staff",
        5: "Personal Services, Security and Safety Workers and Sellers",
        6: "Farmers and Skilled Workers",
        7: "Skilled Workers in Industry/Construction/Craftsmen",
        8: "Installation and Machine Operators",
        9: "Unskilled Workers",
        10: "Armed Forces Professions",
        90: "Other Situation",
        99: "(blank)",
        122: "Health professionals",
        123: "Teachers",
        125: "ICT Specialists",
        131: "Intermediate science and engineering technicians",
        132: "Health technicians",
        134: "Legal/social/cultural technicians",
        141: "Office workers",
        143: "Finance/statistics workers",
        144: "Other administrative support",
        151: "Personal service workers",
        152: "Sellers",
        153: "Personal care workers",
        171: "Skilled construction workers",
        173: "Printing/jewelers/artisans",
        175: "Food/woodworking workers",
        191: "Cleaning workers",
        192: "Unskilled agriculture workers",
        193: "Unskilled construction workers",
        194: "Meal preparation assistants",
    },
    "Father_occupation": {
        0: "Student",
        1: "Representatives of Legislative/Executive Bodies",
        2: "Specialists in Intellectual/Scientific Activities",
        3: "Intermediate Level Technicians and Professions",
        4: "Administrative staff",
        5: "Personal Services, Security and Safety Workers and Sellers",
        6: "Farmers and Skilled Workers",
        7: "Skilled Workers in Industry/Construction/Craftsmen",
        8: "Installation and Machine Operators",
        9: "Unskilled Workers",
        10: "Armed Forces Professions",
        90: "Other Situation",
        99: "(blank)",
        101: "Armed Forces Officers",
        102: "Armed Forces Sergeants",
        103: "Other Armed Forces personnel",
        112: "Directors of administrative services",
        114: "Hotel/catering services directors",
        121: "Physical sciences/engineering specialists",
        122: "Health professionals",
        123: "Teachers",
        124: "Finance/administration specialists",
        131: "Intermediate science technicians",
        132: "Health technicians",
        134: "Legal/social/cultural technicians",
        135: "ICT technicians",
        141: "Office workers",
        143: "Finance/statistics workers",
        144: "Other administrative support",
        151: "Personal service workers",
        152: "Sellers",
        153: "Personal care workers",
        154: "Security personnel",
        161: "Market-oriented farmers",
        163: "Subsistence farmers",
        171: "Skilled construction workers",
        172: "Metal workers",
        174: "Electricians",
        175: "Food/craft workers",
        181: "Machine operators",
        182: "Assembly workers",
        183: "Vehicle drivers",
        192: "Unskilled agriculture workers",
        193: "Unskilled construction workers",
        194: "Meal preparation assistants",
        195: "Street vendors",
    },
    "Displaced": {1: "yes", 0: "no"},
    "Educational_special_needs": {1: "yes", 0: "no"},
    "Debtor": {1: "yes", 0: "no"},
    "Tuition_fees_up_to_date": {1: "yes", 0: "no"},
    "Gender": {1: "male", 0: "female"},
    "Scholarship_holder": {1: "yes", 0: "no"},
}

for column, mapping in maps.items():
    df[column] = df[column].map(mapping)

In [51]:
# Use if needed to get see all cols of pandas dataframes
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
df.head()

,Marital_status,Application_mode,Application_order,Course,Daytime_evening_attendance,Previous_qualification,Previous_qualification_grade,Nationality,Mother_qualification,Father_qualification,Mother_occupation,Father_occupation,Admission_grade,Displaced,Educational_special_needs,Debtor,Tuition_fees_up_to_date,Gender,Scholarship_holder,Age_at_enrollment,International,Curricular_units_1st_sem_credited,Curricular_units_1st_sem_enrolled,Curricular_units_1st_sem_evaluations,Curricular_units_1st_sem_approved,Curricular_units_1st_sem_grade,Curricular_units_1st_sem_without_evaluations,Curricular_units_2nd_sem_credited,Curricular_units_2nd_sem_enrolled,Curricular_units_2nd_sem_evaluations,Curricular_units_2nd_sem_approved,Curricular_units_2nd_sem_grade,Curricular_units_2nd_sem_without_evaluations,Unemployment_rate,Inflation_rate,GDP,Academic_outcome
0,single,2nd phase - general contingent,5,Animation and Multimedia Design,daytime,Secondary education,122.0,Portuguese,Basic Education 3rd Cycle,Other - 11th Year of Schooling,"Personal Services, Security and Safety Workers and Sellers",Unskilled Workers,127.3,yes,no,no,yes,male,no,20,no,0,0,0,0,0.000000,0,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,single,International student (bachelor),1,Tourism,daytime,Secondary education,160.0,Portuguese,Secondary Education - 12th Year of Schooling or Eq.,Higher Education - Degree,Intermediate Level Technicians and Professions,Intermediate Level Technicians and Professions,142.5,yes,no,no,no,male,no,19,no,0,6,6,6,14.000000,0,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,single,1st phase - general contingent,5,Communication Design,daytime,Secondary education,122.0,Portuguese,Basic education 1st cycle (4th/5th year) or equiv.,Basic education 1st cycle,Unskilled Workers,Unskilled Workers,124.8,yes,no,no,no,male,no,19,no,0,6,0,0,0.000000,0,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,single,2nd phase - general contingent,2,Journalism and Communication,daytime,Secondary education,122.0,Portuguese,Basic Education 2nd Cycle,Basic education 1st cycle,"Personal Services, Security and Safety Workers and Sellers",Intermediate Level Technicians and Professions,119.6,yes,no,no,yes,female,no,20,no,0,6,8,6,13.428571,0,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,married,Over 23 years old,1,Social Service (evening attendance),evening,Secondary education,100.0,Portuguese,Basic education 1st cycle (4th/5th year) or equiv.,Basic Education 2nd Cycle,Unskilled Workers,Unskilled Workers,141.5,no,no,no,yes,female,no,45,no,0,6,9,5,12.333333,0,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

## Data Checks

In [52]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 4,424
Columns: 37
Use sampling: False (sample size: 4,424)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['Curricular_units_1st_sem_grade', 'Curricular_units_2nd_sem_grade', 'Admission_grade', 'Previous_qualification_grade', 'Age_at_enrollment', 'Father_occupation', 'Curricular_units_1st_sem_evaluations', 'Father_qualification', 'Mother_occupation', 'Curricular_units_2nd_sem_evaluations']
Rows remaining as candidates after top-10 filter: 0 (of 4,424)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [53]:
# Sample Rows
df_head

,Marital_status,Application_mode,Application_order,Course,Daytime_evening_attendance,Previous_qualification,Previous_qualification_grade,Nationality,Mother_qualification,Father_qualification,Mother_occupation,Father_occupation,Admission_grade,Displaced,Educational_special_needs,Debtor,Tuition_fees_up_to_date,Gender,Scholarship_holder,Age_at_enrollment,International,Curricular_units_1st_sem_credited,Curricular_units_1st_sem_enrolled,Curricular_units_1st_sem_evaluations,Curricular_units_1st_sem_approved,Curricular_units_1st_sem_grade,Curricular_units_1st_sem_without_evaluations,Curricular_units_2nd_sem_credited,Curricular_units_2nd_sem_enrolled,Curricular_units_2nd_sem_evaluations,Curricular_units_2nd_sem_approved,Curricular_units_2nd_sem_grade,Curricular_units_2nd_sem_without_evaluations,Unemployment_rate,Inflation_rate,GDP,Academic_outcome
0,single,2nd phase - general contingent,5,Animation and Multimedia Design,daytime,Secondary education,122.0,Portuguese,Basic Education 3rd Cycle,Other - 11th Year of Schooling,"Personal Services, Security and Safety Workers and Sellers",Unskilled Workers,127.3,yes,no,no,yes,male,no,20,no,0,0,0,0,0.000000,0,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,single,International student (bachelor),1,Tourism,daytime,Secondary education,160.0,Portuguese,Secondary Education - 12th Year of Schooling or Eq.,Higher Education - Degree,Intermediate Level Technicians and Professions,Intermediate Level Technicians and Professions,142.5,yes,no,no,no,male,no,19,no,0,6,6,6,14.000000,0,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,single,1st phase - general contingent,5,Communication Design,daytime,Secondary education,122.0,Portuguese,Basic education 1st cycle (4th/5th year) or equiv.,Basic education 1st cycle,Unskilled Workers,Unskilled Workers,124.8,yes,no,no,no,male,no,19,no,0,6,0,0,0.000000,0,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,single,2nd phase - general contingent,2,Journalism and Communication,daytime,Secondary education,122.0,Portuguese,Basic Education 2nd Cycle,Basic education 1st cycle,"Personal Services, Security and Safety Workers and Sellers",Intermediate Level Technicians and Professions,119.6,yes,no,no,yes,female,no,20,no,0,6,8,6,13.428571,0,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,married,Over 23 years old,1,Social Service (evening attendance),evening,Secondary education,100.0,Portuguese,Basic education 1st cycle (4th/5th year) or equiv.,Basic Education 2nd Cycle,Unskilled Workers,Unskilled Workers,141.5,no,no,no,yes,female,no,45,no,0,6,9,5,12.333333,0,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [54]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Marital_status,category,0.0,0.0,6.0,"single, married, divorced, facto union, legally separated, widower"
1,Application_mode,category,0.0,0.0,18.0,"1st phase - general contingent, 2nd phase - general contingent, Over 23 years old, Change of course, Technological specialization diploma holders, Holders of other higher courses, 3rd phase - general contingent, Transfer, Change of institution/course, 1st phase - special contingent (Madeira Island)"
2,Course,category,0.0,0.0,17.0,"Nursing, Management, Social Service, Veterinary Nursing, Journalism and Communication, Advertising and Marketing Management, Management (evening attendance), Tourism, Communication Design, Animation and Multimedia Design"
3,Daytime_evening_attendance,category,0.0,0.0,2.0,"daytime, evening"
4,Previous_qualification,category,0.0,0.0,17.0,"Secondary education, Technological specialization course, Basic education 3rd cycle (9th/10th/11th year) or equiv., Higher education - degree, Other - 11th year of schooling, Higher education - degree (1st cycle), Professional higher technical course, Higher education - bachelor's degree, Frequency of higher education, 12th year of schooling - not completed"
5,Previous_qualification_grade,category,0.0,0.0,101.0,"133.1, 130.0, 140.0, 120.0, 150.0, 125.0, 135.0, 110.0, 131.0, 160.0"
6,Nationality,category,0.0,0.0,21.0,"Portuguese, Brazilian, Santomean, Spanish, Cape Verdean, Guinean, Italian, Ukrainian, Moldova (Republic of), Russian"
7,Mother_qualification,category,0.0,0.0,29.0,"Secondary Education - 12th Year of Schooling or Eq., Basic education 1st cycle (4th/5th year) or equiv., Basic Education 3rd Cycle, Basic Education 2nd Cycle, Higher Education - Degree, Unknown, Higher Education - Bachelor's Degree, Higher Education - Master's, Other - 11th Year of Schooling, Higher Education - Doctorate"
8,Father_qualification,category,0.0,0.0,34.0,"Basic education 1st cycle, Basic Education 3rd Cycle, Secondary Education - 12th Year of Schooling or Eq., Basic Education 2nd Cycle, Higher Education - Degree, Unknown, Higher Education - Bachelor's Degree, Higher Education - Master's, Other - 11th Year of Schooling, Technological specialization course"
9,Mother_occupation,category,0.0,0.0,32.0,"Unskilled Workers, Administrative staff, Personal Services, Security and Safety Workers and Sellers, Intermediate Level Technicians and Professions, Specialists in Intellectual/Scientific Activities, Skilled Workers in Industry/Construction/Craftsmen, Student, Representatives of Legislative/Executive Bodies, Farmers and Skilled Workers, Other Situation"
10,Father_occupation,category,0.0,0.0,46.0,"Unskilled Workers, Skilled Workers in Industry/Construction/Craftsmen, Personal Services, Security and Safety Workers and Sellers, Administrative staff, Intermediate Level Technicians and Professions, Installation and Machine Operators, Armed Forces Professions, Farmers and Skilled Workers, Specialists in Intellectual/Scientific Activities, Representatives of Legislative/Executive Bodies"
11,Displaced,category,0.0,0.0,2.0,"yes, no"
12,Educational_special_needs,category,0.0,0.0,2.0,"no, yes"
13,Debtor,category,0.0,0.0,2.0,"no, yes"
14,Tuition_fees_up_to_date,category,0.0,0.0,2.0,"yes, no"
15,Gender,category,0.0,0.0,2.0,"female, male"
16,Scholarship_holder,category,0.0,0.0,2.0,"no, yes"
17,Age_at_enrollment,category,0.0,0.0,46.0,"18, 19, 20, 21, 22, 24, 23, 26, 25, 27"
18,International,category,0.0,0.0,2.0,"no, yes"
19,Academic_outcome,category,0.0,0.0,3.0,"Graduate, Dropout, Enrolled"
20,Admission_grade,float64,0.0,0.0,620.0,"130.0, 140.0, 120.0, 100.0, 150.0, 110.0, 160.0, 128.2, 123.0, 128.0"
21,Curricular_units_1st_sem_grade,float64,0.0,0.0,805.0,"0.0, 12.0, 13.0, 11.0, 11.5, 14.0, 12.5, 10.0, 12.6667, 12.3333"
22,Curricular_units_2nd_sem_grade,float64,0.0,0.0,786.0,"0.0, 12.0, 11.0, 13.0, 11.5, 12.5, 14.0, 10.0, 13.5, 12.6667"
23,Unemployment_rate,float64,0.0,0.0,10.0,"7.6, 9.4, 10.8, 12.4, 12.7, 11.1, 15.5, 13.9, 8.9, 16.2"
24,Inflation_rate,float64,0.0,0.0,9.0,"1.4, 2.6, -0.8, 0.5, 3.7, 0.6, 2.8, -0.3, 0.3"
25,GDP,float64,0.0,0.0,10.0,"0.32, -3.12, 1.74, 1.79, -1.7, 2.02, -4.06, 0.79, 3.51, -0.92"
26,Application_order,int64,0.0,0.0,8.0,"1, 2, 3, 4, 5, 6, 9, 0"
27,Curricular_units_1st_sem_credited,int64,0.0,0.0,21.0,"0, 2, 1, 3, 6, 4, 7, 5, 8, 9"
28,Curricular_units_1st_sem_enrolled,int64,0.0,0.0,23.0,"6, 5, 7, 8, 0, 12, 10, 11, 9, 15"
29,Curricular_units_1st_sem_evaluations,int64,0.0,0.0,35.0,"8, 7, 6, 9, 0, 10, 11, 12, 5, 13"
30,Curricular_units_1st_sem_approved,int64,0.0,0.0,23.0,"6, 5, 0, 7, 4, 3, 2, 1, 8, 11"
31,Curricular_units_1st_sem_without_evaluations,int64,0.0,0.0,11.0,"0, 1, 2, 3, 4, 6, 7, 5, 8, 12"
32,Curricular_units_2nd_sem_credited,int64,0.0,0.0,19.0,"0, 1, 2, 4, 5, 3, 6, 11, 7, 9"
33,Curricular_units_2nd_sem_enrolled,int64,0.0,0.0,22.0,"6, 5, 8, 7, 0, 11, 9, 10, 12, 13"
34,Curricular_units_2nd_sem_evaluations,int64,0.0,0.0,30.0,"8, 6, 7, 9, 0, 10, 5, 11, 12, 13"
35,Curricular_units_2nd_sem_approved,int64,0.0,0.0,20.0,"6, 0, 5, 4, 7, 8, 3, 2, 1, 11"
36,Curricular_units_2nd_sem_without_evaluations,int64,0.0,0.0,10.0,"0, 1, 2, 3, 4, 5, 6, 8, 7, 12"

In [55]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
Application_order,4424.0,1.727848,1.313793,0.00,9.000000
Admission_grade,4424.0,126.978119,14.482001,95.00,190.000000
Curricular_units_1st_sem_credited,4424.0,0.709991,2.360507,0.00,20.000000
Curricular_units_1st_sem_enrolled,4424.0,6.270570,2.480178,0.00,26.000000
Curricular_units_1st_sem_evaluations,4424.0,8.299051,4.179106,0.00,45.000000
Curricular_units_1st_sem_approved,4424.0,4.706600,3.094238,0.00,26.000000
Curricular_units_1st_sem_grade,4424.0,10.640822,4.843663,0.00,18.875000
Curricular_units_1st_sem_without_evaluations,4424.0,0.137658,0.690880,0.00,12.000000
Curricular_units_2nd_sem_credited,4424.0,0.541817,1.918546,0.00,19.000000
Curricular_units_2nd_sem_enrolled,4424.0,6.232143,2.195951,0.00,23.000000
Curricular_units_2nd_sem_evaluations,4424.0,8.063291,3.947951,0.00,33.000000
Curricular_units_2nd_sem_approved,4424.0,4.435805,3.014764,0.00,20.000000
Curricular_units_2nd_sem_grade,4424.0,10.230206,5.210808,0.00,18.571429
Curricular_units_2nd_sem_without_evaluations,4424.0,0.150316,0.753774,0.00,12.000000
Unemployment_rate,4424.0,11.566139,2.663850,7.60,16.200000
Inflation_rate,4424.0,1.228029,1.382711,-0.80,3.700000
GDP,4424.0,0.001969,2.269935,-4.06,3.510000

In [56]:
# Categorical Feature Statistics
cat_stats

                                                                                        value  \
column                       rank
Academic_outcome             1                                                       Graduate
                             2                                                        Dropout
                             3                                                       Enrolled
Age_at_enrollment            1                                                             18
                             2                                                             19
                             3                                                             20
                             4                                                             21
                             5                                                             22
Application_mode             1                                 1st phase - general contingent
                             2                                 2nd phase - general contingent
                             3                                              Over 23 years old
                             4                                               Change of course
                             5                   Technological specialization diploma holders
Course                       1                                                        Nursing
                             2                                                     Management
                             3                                                 Social Service
                             4                                             Veterinary Nursing
                             5                                   Journalism and Communication
Daytime_evening_attendance   1                                                        daytime
                             2                                                        evening
Debtor                       1                                                             no
                             2                                                            yes
Displaced                    1                                                            yes
                             2                                                             no
Educational_special_needs    1                                                             no
                             2                                                            yes
Father_occupation            1                                              Unskilled Workers
                             2             Skilled Workers in Industry/Construction/Craftsmen
                             3     Personal Services, Security and Safety Workers and Sellers
                             4                                           Administrative staff
                             5                 Intermediate Level Technicians and Professions
Father_qualification         1                                      Basic education 1st cycle
                             2                                      Basic Education 3rd Cycle
                             3            Secondary Education - 12th Year of Schooling or Eq.
                             4                                      Basic Education 2nd Cycle
                             5                                      Higher Education - Degree
Gender                       1                                                         female
                             2                                                           male
International                1                                                             no
                             2                                                            yes
Marital_status               1                                                         single
                             2                                                        married
                             3                                                       divorced
                             4                                                    facto union
                             5                                              legally separated
Mother_occupation            1                                              Unskilled Workers
                             2                                           Administrative staff
                             3     Personal Services, Security and Safety Workers and Sellers
                             4                 Intermediate Level Technicians and Professions
                             5              Specialists in Intellectual/Scientific Activities
Mother_qualification         1            Secondary Education - 12th Year of Schooling or Eq.
                             2             Basic education 1st cycle (4th/5th year) or equiv.
                             3                                      Basic Education 3rd Cycle
                             4                                      Basic Education 2nd Cycle
                             5                                      Higher Education - Degree
Nationality                  1                                                     Portuguese
                             2                                                      Brazilian
                             3                                                      Santomean
                             4                                                        Spanish
                             5                                                   Cape Verdean
Previous_qualification       1                                            Secondary education
                             2                            Technological specialization course
                             3       Basic education 3rd cycle (9th/10th/11th year) or equiv.
                             4                                      Higher education - degree
                             5                                 Other - 11th year of schooling
Previous_qualification_grade 1                                                          133.1
                             2                                                          130.0
                             3                                                          140.0
                             4                                                          120.0
                             5                                                          150.0
Scholarship_holder           1                                                             no
                             2                                                            yes
Tuition_fees_up_to_date      1                                                            yes
                             2                                                             no

                                   count    pct
column                       rank
Academic_outcome             1      2209  49.93
                             2      1421  32.12
                             3       794  17.95
Age_at_enrollment            1      1036  23.42
                             2       911  20.59
                             3       599  13.54
                             4       322   7.28
                             5       174   3.93
Application_mode             1      1708  38.61
                             2       872  19.71
                             3       785  17.74
                             4       312   7.05
                             5       213   4.81
Course                       1       766  17.31
                             2       380   8.59
                             3       355   8.02
                             4       337   7.62
                             5       331   7.48
Daytime_evening_attendance   1      3941  89.08
                             2       483  10.92
Debtor                       1      3921  88.63
                             2       503  11.37
Displaced                    1      2426  54.84
                             2      1998  45.16
Educational_special_needs    1      4373  98.85
                             2        51   1.15
Father_occupation            1      1010  22.83
                             2       666  15.05
                             3       516  11.66
                             4       386   8.73
                             5       384   8.68
Father_qualification         1      1209  27.33
                             2       968  21.88
                             3       904  20.43
                             4       702  15.87
                             5       282   6.37
Gender                       1      2868  64.83
                             2      1556  35.17
International                1      4314  97.51
                             2       110   2.49
Marital_status               1      3919  88.58
                             2       379   8.57
                             3        91   2.06
                             4        25   0.57
                             5         6   0.14
Mother_occupation            1      1577  35.65
                             2       817  18.47
                             3       530  11.98
                             4       351   7.93
                             5       318   7.19
Mother_qualification         1      1069  24.16
                             2      1009  22.81
                             3       953  21.54
                             4       562  12.70
                             5       438   9.90
Nationality                  1      4314  97.51
                             2        38   0.86
                             3        14   0.32
                             4        13   0.29
                             5        13   0.29
Previous_qualification       1      3717  84.02
                             2       219   4.95
                             3       162   3.66
                             4       126   2.85
                             5        45   1.02
Previous_qualification_grade 1       491  11.10
                             2       375   8.48
                             3       336   7.59
                             4       278   6.28
                             5       162   3.66
Scholarship_holder           1      3325  75.16
                             2      1099  24.84
Tuition_fees_up_to_date      1      3896  88.07
                             2       528  11.93

In [57]:
# Target Distribution
target_df

                  count    pct
Academic_outcome
Graduate           2209  49.93
Dropout            1421  32.12
Enrolled            794  17.95

## Task Curation

In [58]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
    group_labels=task_mold.group_labels,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=3, n_splits=3, test_size=None

In [59]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

# -- For IID Data
splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [60]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to predict_students_dropout_and_academic_success/019d3d8b-ac63-7589-b10b-1e3e16ac8535
019d3d8b-ac63-7589-b10b-1e3e16ac8535
cbef0776cc65c6b4db0685843b5d154de4d12aa3bff789c0fed2aee507383e69