### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="santander_transaction_value",
    dataset_year="2018",
    domain_str="finance",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/santander-value-prediction-challenge",
    download_description="""
We use the train.csv from the Kaggle competition.

kaggle competitions download -c santander-value-prediction-challenge -f train.csv && unzip train.csv.zip &&  rm train.csv.zip
mkdir -p local-data-warehouse/santander_transaction_value && mv train.csv local-data-warehouse/santander_transaction_value/
""",
    # References
    academic_reference_bibtex=r"""@misc{McDonald2018SantanderValuePredictionChallenge,
  author = {Mark McDonald and Mercedes Piedra and Sohier Dane and Soraya Jimenez},
  title  = {Santander Value Prediction Challenge},
  year   = {2018},
  howpublished = {\url{https://kaggle.com/competitions/santander-value-prediction-challenge}},
  note   = {Kaggle competition}
}
""",
    academic_reference_bibtex_key="McDonald2018SantanderValuePredictionChallenge",
    license="Kaggle Competition Rules",
    data_tags=["IID", "Anonymized"],
    curation_comments="""
We start with the train.csv from Kaggle.

- The data has been anonymized.
- We follow the preprocessing by Tschalzev et al. (https://arxiv.org/abs/2407.02112), which follows https://www.kaggle.com/competitions/santander-value-prediction-challenge/discussion/63919
- Since we restrict to the train.csv, we do not exploit the test leak of the competition.
- The expert preprocessing aggregates over feature groups per row to create the new features for the final dataset. Feature groups for aggregation are found by searching for chains of features (?).
- The data contains a very small number of duplicates. We remove them to avoid leakage in our own splits.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="target",
    problem_type="regression",
    objective_metric_name="rmsle",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

og_df = pd.read_csv(dataset_mold.path / "train.csv")
# print("Loaded data shape:", df.shape)

In [3]:
train = og_df.copy()

# Code adapted from https://github.com/atschalz/dc_tabeval/blob/main/datasets.py#L2120 w/o test leak part
import gc
features = [
    'f190486d6', '58e2e02e6', 'eeb9cd3aa', '9fd594eec', '6eef030c1',
    '15ace8c9f', 'fb0f5dbfe', '58e056e12', '20aa07010', '024c577b9',
    'd6bb78916', 'b43a7cfd5', '58232a6fb', '1702b5bf0', '324921c7b',
    '62e59a501', '2ec5b290f', '241f0f867', 'fb49e4212', '66ace2992',
    'f74e8f13d', '5c6487af1', '963a49cdc', '26fc93eb7', '1931ccfdd',
    '703885424', '70feb1494', '491b9ee45', '23310aa6f', 'e176a204a',
    '6619d81fc', '1db387535', 'fc99f9426', '91f701ba2', '0572565c2',
    '190db8488', 'adb64ff71', 'c47340d97', 'c5a231d81', '0ff32eb98'
]
extra_features = []

train = train
train_t = train.drop(['target'], axis = 1, inplace=False)
train_t.set_index('ID', inplace=True)
train_t = train_t.T

#run this iteratively until you have no more links. Then prune
def chain_pairs(ordered_items):
    ordered_chains = []
    links_found = 0
    for i_1, op_chain in enumerate(ordered_items.copy()[:]):
        if op_chain[0] != op_chain[1]:
            end_chain = op_chain[-1]
            for i_2, op in enumerate(ordered_items.copy()[:]):
                if (end_chain == op[0]):
                    links_found += 1
                    op_chain.extend(op[1:])
                    end_chain = op_chain[-1]

            ordered_chains.append(op_chain)
    return links_found, ordered_chains

def prune_chain(ordered_chain):

    ordered_chain = sorted(ordered_chain, key=len, reverse=True)
    new_chain = []
    id_lookup = {}
    for oc in ordered_chain:
        id_already_in_chain = False
        for idd in oc:
            if idd in id_lookup:
                id_already_in_chain = True
            id_lookup[idd] = idd

        if not id_already_in_chain:
            new_chain.append(oc)
    return sorted(new_chain, key=len, reverse=True)

def find_new_ordered_features(ordered_ids, data_t):
    data = data_t.copy()

    f1 = ordered_ids[0][:-1]
    f2 = ordered_ids[0][1:]
    for ef in ordered_ids[1:]:
        f1 += ef[:-1]
        f2 += ef[1:]

    d1 = data[f1].apply(tuple, axis=1).apply(hash).to_frame().rename(columns={0: 'key'})
    d1['ID'] = data.index
    gc.collect()
    d2 = data[f2].apply(tuple, axis=1).apply(hash).to_frame().rename(columns={0: 'key'})
    d2['ID'] = data.index
    gc.collect()
    d3 = d2[~d2.duplicated(['key'], keep=False)]
    d4 = d1[~d1.duplicated(['key'], keep=False)]
    d5 = d4.merge(d3, how='inner', on='key')

    d_feat = d1.merge(d5, how='left', on='key')
    d_feat.fillna(0, inplace=True)

    ordered_features = list(d_feat[['ID_x', 'ID_y']][d_feat.ID_x != 0].apply(list, axis=1))
    del d1,d2,d3,d4,d5,d_feat
    gc.collect()

    links_found = 1
    while links_found > 0:
        links_found, ordered_features = chain_pairs(ordered_features)

    ordered_features = prune_chain(ordered_features)
    #make lookup of all features found so far
    found = {}
    for ef in extra_features:
        found[ef[0]] = ef
    found [features[0]] = features

    new_feature_sets = []
    for of in ordered_features:
        if len(of) >= 40:
            if of[0] not in found:
                new_feature_sets.append(of)

    return new_feature_sets

def add_new_feature_sets(data, data_t):

    # print ('\nData Shape:', data.shape)
    f1 = features[:-1]
    f2 = features[1:]

    for ef in extra_features:
        f1 += ef[:-1]
        f2 += ef[1:]

    d1 = data[f1].apply(tuple, axis=1).apply(hash).to_frame().rename(columns={0: 'key'})
    d1['ID'] = data['ID']
    gc.collect()
    d2 = data[f2].apply(tuple, axis=1).apply(hash).to_frame().rename(columns={0: 'key'})
    d2['ID'] = data['ID']
    gc.collect()
    #print('here')
    d3 = d2[~d2.duplicated(['key'], keep=False)]
    del d2
    d4 = d1[~d1.duplicated(['key'], keep=False)]
    #print('here')
    d5 = d4.merge(d3, how='inner', on='key')
    del d4
    d = d1.merge(d5, how='left', on='key')
    d.fillna(0, inplace=True)
    #print('here')
    ordered_ids = list(d[['ID_x', 'ID_y']][d.ID_x != 0].apply(list, axis=1))
    del d1,d3,d5,d
    gc.collect()

    links_found = 1
    while links_found > 0:
        links_found, ordered_ids = chain_pairs(ordered_ids)
        #print(links_found)

    # print ('OrderedIds:', len(ordered_ids))
    #Make distinct ordered id chains
    ordered_ids = prune_chain(ordered_ids)
    # print ('OrderedIds Pruned:', len(ordered_ids))

    #look for ordered features with new ordered id chains
    new_feature_sets = find_new_ordered_features(ordered_ids, data_t)

    extra_features.extend(new_feature_sets)
    # print('New Feature Count:', len(new_feature_sets))
    # print('Extra Feature Count:', len(extra_features))

add_new_feature_sets(train,train_t)
add_new_feature_sets(train,train_t)
add_new_feature_sets(train,train_t)

del train_t
gc.collect()

### Create 40 features
extra_features_list = []

for ef in extra_features:
    extra_features_list.extend(ef)

extra_features_list.extend(features)

#This makes the 100 40 length feature groups into 40 100 length feature groups.
feats = pd.DataFrame(extra_features)
time_features = []
for c in feats.columns[:]:
    time_features.append([f for f in feats[c].values if f is not None])


#Make a bunch of different feature groups to build aggregates from
agg_features = []
all_cols = train.columns.drop(['ID', 'target'])
agg_features.append(all_cols)
agg_features.append([c for c in all_cols if c not in extra_features_list])
agg_features.append(extra_features_list)
agg_features.extend(time_features)
agg_features.extend(extra_features)

def add_new_features(source, dest, feats):
    high = source[feats].max(axis=1)
    high.name = 'high_{}_{}'.format(feats[0], len(feats))
    mean = source[feats].replace(0, np.nan).mean(axis=1)
    mean.name = 'mean_{}_{}'.format(feats[0], len(feats))
    low = source[feats].replace(0, np.nan).min(axis=1)
    low.name = 'low_{}_{}'.format(feats[0], len(feats))
    median = source[feats].replace(0, np.nan).median(axis=1)
    median.name = 'median_{}_{}'.format(feats[0], len(feats))
    sum = source[feats].sum(axis=1)
    sum.name = 'sum_{}_{}'.format(feats[0], len(feats))
    stddev = source[feats].std(axis=1)
    stddev.name = 'stddev_{}_{}'.format(feats[0], len(feats))
    first_nonZero= np.log1p(source[feats].replace(0, np.nan).bfill(axis=1).iloc[:, 0])
    first_nonZero.name = 'first_nonZero_{}_{}'.format(feats[0], len(feats))
    last_nonZero = np.log1p(source[feats[::-1]].replace(0, np.nan).bfill(axis=1).iloc[:, 0])
    last_nonZero.name = 'last_nonZero_{}_{}'.format(feats[0], len(feats))
    nb_nans =  source[feats].replace(0, np.nan).isnull().sum(axis=1)
    nb_nans.name = 'nb_nans_{}_{}'.format(feats[0], len(feats))
    unique = source[feats].nunique(axis=1)
    unique.name = 'unique_{}_{}'.format(feats[0], len(feats))

    dest = pd.concat([dest, high, mean, low, median, sum, stddev, first_nonZero, last_nonZero, nb_nans, unique],axis=1)
    return dest


train_feats = pd.DataFrame()
for i, ef in list(enumerate(agg_features)):
    train_feats = add_new_features(train, train_feats, ef)


df = train_feats
df[task_mold.target_column_name] = np.log1p(train.target.values)

# Remove duplicates
df = df.drop_duplicates(subset=[c for c in df.columns if c != task_mold.target_column_name])
df = df.reset_index(drop=True)

## Data Checks

In [4]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 4,447
Columns: 541
Use sampling: False (sample size: 4,447)

Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['stddev_48df886f9_4511', 'stddev_48df886f9_4991', 'mean_48df886f9_4991', 'sum_48df886f9_4991', 'mean_48df886f9_4511', 'sum_48df886f9_4511', 'stddev_9ddd6d137_480', 'mean_9ddd6d137_480', 'sum_9ddd6d137_480', 'median_48df886f9_4991']
Rows remaining as candidates after top-10 filter: 94 (of 4,447)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [5]:
# Sample Rows
df_head

,high_48df886f9_4991,mean_48df886f9_4991,low_48df886f9_4991,median_48df886f9_4991,sum_48df886f9_4991,stddev_48df886f9_4991,first_nonZero_48df886f9_4991,last_nonZero_48df886f9_4991,nb_nans_48df886f9_4991,unique_48df886f9_4991,high_48df886f9_4511,mean_48df886f9_4511,low_48df886f9_4511,median_48df886f9_4511,sum_48df886f9_4511,stddev_48df886f9_4511,first_nonZero_48df886f9_4511,last_nonZero_48df886f9_4511,nb_nans_48df886f9_4511,unique_48df886f9_4511,high_9ddd6d137_480,mean_9ddd6d137_480,low_9ddd6d137_480,median_9ddd6d137_480,sum_9ddd6d137_480,stddev_9ddd6d137_480,first_nonZero_9ddd6d137_480,last_nonZero_9ddd6d137_480,nb_nans_9ddd6d137_480,unique_9ddd6d137_480,high_9ddd6d137_11,mean_9ddd6d137_11,low_9ddd6d137_11,median_9ddd6d137_11,sum_9ddd6d137_11,stddev_9ddd6d137_11,first_nonZero_9ddd6d137_11,last_nonZero_9ddd6d137_11,nb_nans_9ddd6d137_11,unique_9ddd6d137_11,high_5cfc625f1_11,mean_5cfc625f1_11,low_5cfc625f1_11,median_5cfc625f1_11,sum_5cfc625f1_11,stddev_5cfc625f1_11,first_nonZero_5cfc625f1_11,last_nonZero_5cfc625f1_11,nb_nans_5cfc625f1_11,unique_5cfc625f1_11,high_8984e4066_11,mean_8984e4066_11,low_8984e4066_11,median_8984e4066_11,sum_8984e4066_11,stddev_8984e4066_11,first_nonZero_8984e4066_11,last_nonZero_8984e4066_11,nb_nans_8984e4066_11,unique_8984e4066_11,high_0ccd6454a_11,mean_0ccd6454a_11,low_0ccd6454a_11,median_0ccd6454a_11,sum_0ccd6454a_11,stddev_0ccd6454a_11,first_nonZero_0ccd6454a_11,last_nonZero_0ccd6454a_11,nb_nans_0ccd6454a_11,unique_0ccd6454a_11,high_9397535c7_11,mean_9397535c7_11,low_9397535c7_11,median_9397535c7_11,sum_9397535c7_11,stddev_9397535c7_11,first_nonZero_9397535c7_11,last_nonZero_9397535c7_11,nb_nans_9397535c7_11,unique_9397535c7_11,high_de7063efa_11,mean_de7063efa_11,low_de7063efa_11,median_de7063efa_11,sum_de7063efa_11,stddev_de7063efa_11,first_nonZero_de7063efa_11,last_nonZero_de7063efa_11,nb_nans_de7063efa_11,unique_de7063efa_11,high_74f3ac6af_11,mean_74f3ac6af_11,low_74f3ac6af_11,median_74f3ac6af_11,sum_74f3ac6af_11,stddev_74f3ac6af_11,first_nonZero_74f3ac6af_11,last_nonZero_74f3ac6af_11,nb_nans_74f3ac6af_11,unique_74f3ac6af_11,high_6bee3733e_11,mean_6bee3733e_11,low_6bee3733e_11,median_6bee3733e_11,sum_6bee3733e_11,stddev_6bee3733e_11,first_nonZero_6bee3733e_11,last_nonZero_6bee3733e_11,nb_nans_6bee3733e_11,unique_6bee3733e_11,high_20e2c484e_11,mean_20e2c484e_11,low_20e2c484e_11,median_20e2c484e_11,sum_20e2c484e_11,stddev_20e2c484e_11,first_nonZero_20e2c484e_11,last_nonZero_20e2c484e_11,nb_nans_20e2c484e_11,unique_20e2c484e_11,high_5adfe7419_11,mean_5adfe7419_11,low_5adfe7419_11,median_5adfe7419_11,sum_5adfe7419_11,stddev_5adfe7419_11,first_nonZero_5adfe7419_11,last_nonZero_5adfe7419_11,nb_nans_5adfe7419_11,unique_5adfe7419_11,high_03a4ccd7c_11,mean_03a4ccd7c_11,low_03a4ccd7c_11,median_03a4ccd7c_11,sum_03a4ccd7c_11,stddev_03a4ccd7c_11,first_nonZero_03a4ccd7c_11,last_nonZero_03a4ccd7c_11,nb_nans_03a4ccd7c_11,unique_03a4ccd7c_11,high_ecbd077d0_11,mean_ecbd077d0_11,low_ecbd077d0_11,median_ecbd077d0_11,sum_ecbd077d0_11,stddev_ecbd077d0_11,first_nonZero_ecbd077d0_11,last_nonZero_ecbd077d0_11,nb_nans_ecbd077d0_11,unique_ecbd077d0_11,high_851697562_11,mean_851697562_11,low_851697562_11,median_851697562_11,sum_851697562_11,stddev_851697562_11,first_nonZero_851697562_11,last_nonZero_851697562_11,nb_nans_851697562_11,unique_851697562_11,high_60cb16e88_11,mean_60cb16e88_11,low_60cb16e88_11,median_60cb16e88_11,sum_60cb16e88_11,stddev_60cb16e88_11,first_nonZero_60cb16e88_11,last_nonZero_60cb16e88_11,nb_nans_60cb16e88_11,unique_60cb16e88_11,high_73a8a4d75_11,mean_73a8a4d75_11,low_73a8a4d75_11,median_73a8a4d75_11,sum_73a8a4d75_11,stddev_73a8a4d75_11,first_nonZero_73a8a4d75_11,last_nonZero_73a8a4d75_11,nb_nans_73a8a4d75_11,unique_73a8a4d75_11,high_4c48708d8_11,mean_4c48708d8_11,low_4c48708d8_11,median_4c48708d8_11,sum_4c48708d8_11,stddev_4c48708d8_11,first_nonZero_4c48708d8_11,last_nonZero_4c48708d8_11,nb_nans_4c48708d8_11,unique_4c48708d8_11,high_ea72c62a1_11,mean_ea72c62a1_11,low_ea72c62a1_11,median_ea72c62a1_11,sum_ea72c62a1_11,stddev_ea72c62a1_11,first_nonZero_ea72c62a1_11,last_nonZero_ea72c62a1_11,nb_nans_ea72c62a1_11,unique_ea72c62a1_11,high_bbd16b7a0_11,mean_bbd16b7a0_11,low_bbd16b7a0_11,median_bbd16b7a0_11,sum_bbd16b7a0_11,stddev_bbd16b7a0_11,first_nonZero_bbd16b7a0_11,last_nonZero_bbd16b7a0_11,nb_nans_bbd16b7a0_11,unique_bbd16b7a0_11,high_3fa6c395f_11,mean_3fa6c395f_11,low_3fa6c395f_11,median_3fa6c395f_11,sum_3fa6c395f_11,stddev_3fa6c395f_11,first_nonZero_3fa6c395f_11,last_nonZero_3fa6c395f_11,nb_nans_3fa6c395f_11,unique_3fa6c395f_11,high_dba14a5d4_11,mean_dba14a5d4_11,low_dba14a5d4_11,median_dba14a5d4_11,sum_dba14a5d4_11,stddev_dba14a5d4_11,first_nonZero_dba14a5d4_11,last_nonZero_dba14a5d4_11,nb_nans_dba14a5d4_11,unique_dba14a5d4_11,high_5d60b9ba7_11,mean_5d60b9ba7_11,low_5d60b9ba7_11,median_5d60b9ba7_11,sum_5d60b9ba7_11,stddev_5d60b9ba7_11,first_nonZero_5d60b9ba7_11,last_nonZero_5d60b9ba7_11,nb_nans_5d60b9ba7_11,unique_5d60b9ba7_11,high_7f9e0d947_11,mean_7f9e0d947_11,low_7f9e0d947_11,median_7f9e0d947_11,sum_7f9e0d947_11,stddev_7f9e0d947_11,first_nonZero_7f9e0d947_11,last_nonZero_7f9e0d947_11,nb_nans_7f9e0d947_11,unique_7f9e0d947_11,high_a636266f3_11,mean_a636266f3_11,low_a636266f3_11,median_a636266f3_11,sum_a636266f3_11,stddev_a636266f3_11,first_nonZero_a636266f3_11,last_nonZero_a636266f3_11,nb_nans_a636266f3_11,unique_a636266f3_11,high_6931ed626_11,mean_6931ed626_11,low_6931ed626_11,median_6931ed626_11,sum_6931ed626_11,stddev_6931ed626_11,first_nonZero_6931ed626_11,last_nonZero_6931ed626_11,nb_nans_6931ed626_11,unique_6931ed626_11,high_76e9423c3_11,mean_76e9423c3_11,low_76e9423c3_11,median_76e9423c3_11,sum_76e9423c3_11,stddev_76e9423c3_11,first_nonZero_76e9423c3_11,last_nonZero_76e9423c3_11,nb_nans_76e9423c3_11,unique_76e9423c3_11,high_6723b1708_11,mean_6723b1708_11,low_6723b1708_11,median_6723b1708_11,sum_6723b1708_11,stddev_6723b1708_11,first_nonZero_6723b1708_11,last_nonZero_6723b1708_11,nb_nans_6723b1708_11,unique_6723b1708_11,high_d80abf8bc_11,mean_d80abf8bc_11,low_d80abf8bc_11,median_d80abf8bc_11,sum_d80abf8bc_11,stddev_d80abf8bc_11,first_nonZero_d80abf8bc_11,last_nonZero_d80abf8bc_11,nb_nans_d80abf8bc_11,unique_d80abf8bc_11,high_7194699cd_11,mean_7194699cd_11,low_7194699cd_11,median_7194699cd_11,sum_7194699cd_11,stddev_7194699cd_11,first_nonZero_7194699cd_11,last_nonZero_7194699cd_11,nb_nans_7194699cd_11,unique_7194699cd_11,high_e3846e931_11,mean_e3846e931_11,low_e3846e931_11,median_e3846e931_11,sum_e3846e931_11,stddev_e3846e931_11,first_nonZero_e3846e931_11,last_nonZero_e3846e931_11,nb_nans_e3846e931_11,unique_e3846e931_11,high_b66bf9d44_11,mean_b66bf9d44_11,low_b66bf9d44_11,median_b66bf9d44_11,sum_b66bf9d44_11,stddev_b66bf9d44_11,first_nonZero_b66bf9d44_11,last_nonZero_b66bf9d44_11,nb_nans_b66bf9d44_11,unique_b66bf9d44_11,high_c436c7e73_11,mean_c436c7e73_11,low_c436c7e73_11,median_c436c7e73_11,sum_c436c7e73_11,stddev_c436c7e73_11,first_nonZero_c436c7e73_11,last_nonZero_c436c7e73_11,nb_nans_c436c7e73_11,unique_c436c7e73_11,high_b74ef4294_11,mean_b74ef4294_11,low_b74ef4294_11,median_b74ef4294_11,sum_b74ef4294_11,stddev_b74ef4294_11,first_nonZero_b74ef4294_11,last_nonZero_b74ef4294_11,nb_nans_b74ef4294_11,unique_b74ef4294_11,high_a2a1975d6_11,mean_a2a1975d6_11,low_a2a1975d6_11,median_a2a1975d6_11,sum_a2a1975d6_11,stddev_a2a1975d6_11,first_nonZero_a2a1975d6_11,last_nonZero_a2a1975d6_11,nb_nans_a2a1975d6_11,unique_a2a1975d6_11,high_1c4157dfd_11,mean_1c4157dfd_11,low_1c4157dfd_11,median_1c4157dfd_11,sum_1c4157dfd_11,stddev_1c4157dfd_11,first_nonZero_1c4157dfd_11,last_nonZero_1c4157dfd_11,nb_nans_1c4157dfd_11,unique_1c4157dfd_11,high_e32ad270b_11,mean_e32ad270b_11,low_e32ad270b_11,median_e32ad270b_11,sum_e32ad270b_11,stddev_e32ad270b_11,first_nonZero_e32ad270b_11,last_nonZero_e32ad270b_11,nb_nans_e32ad270b_11,unique_e32ad270b_11,high_c30399758_11,mean_c30399758_11,low_c30399758_11,median_c30399758_11,sum_c30399758_11,stddev_c30399758_11,first_nonZero_c30399758_11,last_nonZero_c30399758_11,nb_nans_c30399758_11,unique_c30399758_11,high_d45fd5508_11,mean_d45fd5508_11,low_d45fd5508_11,median_d45fd5508_11,sum_d45fd5508_11,stddev_d45fd5508_11,first_nonZero_d45fd5508_11,last_nonZero_d45fd5508_11,nb_nans_d45fd5508_11,unique_d45fd5508_11,high_e97fa47e4_11,mean_e97fa47e4_11,low_e97fa47e4_11,median_e97fa47e4_11,sum_e97fa47e4_11,stddev_e97fa47e4_11,first_nonZero_e97fa47e4_11,last_nonZero_e97fa47e4_11,nb_nans_e97fa47e4_11,unique_e97fa47e4_11,high_02827212f_11,mean_02827212f_11,low_02827212f_11,median_02827212f_11,sum_02827212f_11,stddev_02827212f_11,first_nonZero_02827212f_11,last_nonZero_02827212f_11,nb_nans_02827212f_11,unique_02827212f_11,high_6f53aee73_11,mean_6f53aee73_11,low_6f53aee73_11,median_6f53aee73_11,sum_6f53aee73_11,stddev_6f53aee73_11,first_nonZero_6f53aee73_11,last_nonZero_6f53aee73_11,nb_nans_6f53aee73_11,unique_6f53aee73_11,high_9ddd6d137_40,mean_9ddd6d137_40,low_9ddd6d137_40,median_9ddd6d137_40,sum_9ddd6d137_40,stddev_9ddd6d137_40,first_nonZero_9ddd6d137_40,last_nonZero_9ddd6d137_40,nb_nans_9ddd6d137_40,unique_9ddd6d137_40,high_d48c44c49_40,mean_d48c44c49_40,low_d48c44c49_40,median_d48c44c49_40,sum_d48c44c49_40,stddev_d48c44c49_40,first_nonZero_d48c44c49_40,last_nonZero_d48c44c49_40,nb_nans_d48c44c49_40,unique_d48c44c49_40,high_6469d38ef_40,mean_6469d38ef_40,low_6469d38ef_40,median_6469d38ef_40,sum_6469d38ef_40,stddev_6469d38ef_40,first_nonZero_6469d38ef_40,last_nonZero_6469d38ef_40,nb_nans_6469d38ef_40,unique_6469d38ef_40,high_20868afc1_40,mean_20868afc1_40,low_20868afc1_40,median_20868afc1_40,sum_20868afc1_40,stddev_20868afc1_40,first_nonZero_20868afc1_40,last_nonZero_20868afc1_40,nb_nans_20868afc1_40,unique_20868afc1_40,high_a59d32627_40,mean_a59d32627_40,low_a59d32627_40,median_a59d32627_40,sum_a59d32627_40,stddev_a59d32627_40,first_nonZero_a59d32627_40,last_nonZero_a59d32627_40,nb_nans_a59d32627_40,unique_a59d32627_40,high_8ceddccb8_40,mean_8ceddccb8_40,low_8ceddccb8_40,median_8ceddccb8_40,sum_8ceddccb8_40,stddev_8ceddccb8_40,first_nonZero_8ceddccb8_40,last_nonZero_8ceddccb8_40,nb_nans_8ceddccb8_40,unique_8ceddccb8_40,high_5bc10886b_40,mean_5bc10886b_40,low_5bc10886b_40,median_5bc10886b_40,sum_5bc10886b_40,stddev_5bc10886b_40,first_nonZero_5bc10886b_40,last_nonZero_5bc10886b_40,nb_nans_5bc10886b_40,unique_5bc10886b_40,high_50603ae3d_40,mean_50603ae3d_40,low_50603ae3d_40,median_50603ae3d_40,sum_50603ae3d_40,stddev_50603ae3d_40,first_nonZero_50603ae3d_40,last_nonZero_50603ae3d_40,nb_nans_50603ae3d_40,unique_50603ae3d_40,high_2c7e41e16_40,mean_2c7e41e16_40,low_2c7e41e16_40,median_2c7e41e16_40,sum_2c7e41e16_40,stddev_2c7e41e16_40,first_nonZero_2c7e41e16_40,last_nonZero_2c7e41e16_40,nb_nans_2c7e41e16_40,unique_2c7e41e16_40,high_9c92cbc0c_40,mean_9c92cbc0c_40,low_9c92cbc0c_40,median_9c92cbc0c_40,sum_9c92cbc0c_40,stddev_9c92cbc0c_40,first_nonZero_9c92cbc0c_40,last_nonZero_9c92cbc0c_40,nb_nans_9c92cbc0c_40,unique_9c92cbc0c_40,high_b33e83cdc_40,mean_b33e83cdc_40,low_b33e83cdc_40,median_b33e83cdc_40,sum_b33e83cdc_40,stddev_b33e83cdc_40,first_nonZero_b33e83cdc_40,last_nonZero_b33e83cdc_40,nb_nans_b33e83cdc_40,unique_b33e83cdc_40,target
0,40000000.0,7.066356e+06,250000.0,2400000.00,7.207683e+08,1.741261e+06,14.077876,15.201805,4889,53,40000000.0,7.465020e+06,250000.0,2600000.00,6.195967e+08,1.743294e+06,14.077876,15.201805,4428,45,28000000.0,5.324825e+06,400000.0,2000000.0,1.011717e+08,1.722415e+06,16.510138,12.899222,461,19,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.000000e+00,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,14800000.0,14800000.0,14800000.0,14800000.0,14800000.0,4.462368e+06,16.510138,16.510138,10,2,0.0,NaN,NaN,NaN,0.0,0.000000e+00,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,4000000.0,4000000.0,4000000.0,4000000.0,4000000.0,1.206045e+06,15.201805,15.201805,10,2,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.000000,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0,NaN,NaN,NaN,0,0.0,NaN,NaN,40,1,0,NaN,NaN,NaN,0,0.0,NaN,NaN,40,1,0,NaN,NaN,NaN,0,0.0,NaN,NaN,40,1,0,NaN,NaN,NaN,0,0.0,NaN,NaN,40,1,0.0,NaN,NaN,NaN,0.0,0.000000e+00,NaN,NaN,40,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,40,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,40,1,14800000,9400000.0,4000000.0,9400000.0,18800000,2.408340e+06,16.510138,15.201805,38,3,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,40,1,0,NaN,NaN,NaN,0,0.000000e+00,NaN,NaN,40,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,40,1,17.453097
1,50000000.0,7.939801e+06,800000.0,2225000.00,5.319667e+08,1.529294e+06,14.603968,14.508658,4924,23,50000000.0,7.764137e+06,800000.0,2100000.00,4.347917e+08,1.393874e+06,16.993564,14.508658,4455,21,50000000.0,8.834091e+06,800000.0,2850000.0,9.717500e+07,2.461821e+06,16.012735,15.761421,469,12,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,50000000.0,50000000.0,50000000.0,50000000.0,50000000.0,1.507557e+07,17.727534,17.727534,10,2,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.000000e+00,NaN,NaN,11,1,9000000.0,9000000.0,9000000.0,9000000.0,9000000.0,2.713602e+06,16.012735,16.012735,10,2,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.000000e+00,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.000000,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0,NaN,NaN,NaN,0,0.0,NaN,NaN,40,1,0,NaN,NaN,NaN,0,0.0,NaN,NaN,40,1,0,NaN,NaN,NaN,0,0.0,NaN,NaN,40,1,0,NaN,NaN,NaN,0,0.0,NaN,NaN,40,1,9000000.0,9000000.0,9000000.0,9000000.0,9000000.0,1.423025e+06,16.012735,16.012735,39,2,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,40,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,40,1,0,NaN,NaN,NaN,0,0.000000e+00,NaN,NaN,40,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,40,1,50000000,50000000.0,50000000.0,50000000.0,50000000,7.905694e+06,17.727534,17.727534,39,2,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,40,1,13.304687
2,12000000.0,4.233333e+06,200000.0,4000000.00,7.620000e+07,3.314076e+05,16.300417,13.122365,4973,12,12000000.0,3.750000e+06,200000.0,3250000.00,5.250000e+07,2.738892e+05,15.201805,13.122365,4497,12,12000000.0,5.925000e+06,200000.0,5750000.0,2.370000e+07,6.607388e+05,12.206078,16.300417,476,5,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.000000e+00,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.000000e+00,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.000000e+00,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.000000e+00,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,200000.0,200000.0,200000.0,200000.0,200000.0,60302.268916,12.206078,12.206078,10,2,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,11,1,0,NaN,NaN,NaN,0,0.0,NaN,NaN,40,1,0,NaN,NaN,NaN,0,0.0,NaN,NaN,40,1,0,NaN,NaN,NaN,0,0.0,NaN,NaN,40,1,0,NaN,NaN,NaN,0,0.0,NaN,NaN,40,1,200000.0,200000.0,200000.0,200000.0,200000.0,3.162278e+04,12.206078,12.206078,39,2,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,40,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,40,1,0,NaN,NaN,NaN,0,0.000000e+00,NaN,NaN,40,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,40,1,0,NaN,NaN,NaN,0,0.000000e+00,NaN,NaN,40,1,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,40,1,16.118096

In [6]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,mean_d48c44c49_40,float64,4174.0,93.86,67.0,"2000000.0, 5618000.0, 260000.0, 1600000.0, 200000.0, 9000000.0, 1280000.0, 320000.0, 70000.0, 310000.0"
1,low_d48c44c49_40,float64,4174.0,93.86,29.0,"252000.0, 2000000.0, 5618000.0, 320000.0, 160000.0, 300000.0, 1600000.0, 200000.0, 9000000.0, 1280000.0"
2,median_d48c44c49_40,float64,4174.0,93.86,34.0,"1032000.0, 2000000.0, 5618000.0, 240000.0, 1600000.0, 300000.0, 200000.0, 1280000.0, 9000000.0, 320000.0"
3,first_nonZero_d48c44c49_40,float64,4174.0,93.86,32.0,"12.6761, 14.5087, 13.8235, 15.5415, 11.9829, 12.6115, 14.2855, 12.2061, 16.0127, 14.0624"
4,last_nonZero_d48c44c49_40,float64,4174.0,93.86,29.0,"13.847, 12.6115, 14.5087, 15.5415, 12.6761, 14.2855, 12.2061, 16.0127, 14.0624, 13.3047"
5,mean_9ddd6d137_40,float64,4098.0,92.15,57.0,"1360000.0, 20106000.0, 33333333.3333, 220000.0, 120000000.0, 1244000.0, 10000000.0, 5200000.0, 236000.0, 46000000.0"
6,low_9ddd6d137_40,float64,4098.0,92.15,30.0,"220000.0, 1360000.0, 20106000.0, 456000.0, 20000000.0, 252000.0, 120000000.0, 8000.0, 10000000.0, 5200000.0"
7,median_9ddd6d137_40,float64,4098.0,92.15,39.0,"1360000.0, 20106000.0, 30000000.0, 472000.0, 220000.0, 120000000.0, 22000.0, 10000000.0, 5200000.0, 236000.0"
8,first_nonZero_9ddd6d137_40,float64,4098.0,92.15,33.0,"13.0303, 14.123, 16.8165, 16.8112, 12.3014, 18.603, 8.9873, 12.4372, 16.1181, 15.4642"
9,last_nonZero_9ddd6d137_40,float64,4098.0,92.15,29.0,"12.3014, 14.123, 16.8165, 17.7275, 12.4372, 18.603, 9.9988, 13.0647, 16.1181, 15.4642"
10,mean_ecbd077d0_11,float64,4006.0,90.08,222.0,"4000000.0, 400000.0, 50000000.0, 600000.0, 200000.0, 911000.0, 1000000.0, 61714000.0, 40000000.0, 22000.0"
11,low_ecbd077d0_11,float64,4006.0,90.08,197.0,"200000.0, 400000.0, 4000000.0, 50000000.0, 20000000.0, 600000.0, 80000.0, 800000.0, 1000000.0, 61714000.0"
12,median_ecbd077d0_11,float64,4006.0,90.08,221.0,"4000000.0, 400000.0, 50000000.0, 600000.0, 200000.0, 1032000.0, 61714000.0, 1000000.0, 100000.0, 300000.0"
13,first_nonZero_ecbd077d0_11,float64,4006.0,90.08,199.0,"15.2018, 12.8992, 12.2061, 17.7275, 16.8112, 13.3047, 13.5924, 13.847, 13.8155, 17.938"
14,last_nonZero_ecbd077d0_11,float64,4006.0,90.08,202.0,"15.2018, 17.7275, 12.2061, 12.8992, 13.3047, 11.2898, 16.1181, 13.8155, 13.5924, 17.938"
15,mean_5adfe7419_11,float64,4005.0,90.06,244.0,"200000.0, 400000.0, 30000000.0, 600000.0, 20000000.0, 50000000.0, 2000000.0, 61714000.0, 100000.0, 1000000.0"
16,low_5adfe7419_11,float64,4005.0,90.06,217.0,"200000.0, 400000.0, 20000000.0, 30000000.0, 600000.0, 2000000.0, 1000000.0, 50000000.0, 22000.0, 800000.0"
17,median_5adfe7419_11,float64,4005.0,90.06,240.0,"200000.0, 400000.0, 30000000.0, 20000000.0, 600000.0, 50000000.0, 2000000.0, 100000.0, 1000000.0, 22000.0"
18,first_nonZero_5adfe7419_11,float64,4005.0,90.06,216.0,"12.2061, 12.8992, 16.8112, 17.2167, 13.5924, 13.3047, 14.5087, 13.8155, 17.7275, 11.5129"
19,last_nonZero_5adfe7419_11,float64,4005.0,90.06,222.0,"12.2061, 12.8992, 17.7275, 17.2167, 14.5087, 13.3047, 16.8112, 13.8155, 16.1181, 11.5129"
20,mean_9c92cbc0c_40,float64,4004.0,90.04,59.0,"2600000.0, 10000000.0, 4378000.0, 1920000.0, 50000000.0, 3000000.0, 512000.0, 8244000.0, 760000.0, 42000.0"
21,low_9c92cbc0c_40,float64,4004.0,90.04,39.0,"2000000.0, 512000.0, 1200000.0, 2600000.0, 10000000.0, 1920000.0, 8244000.0, 50000000.0, 42000.0, 760000.0"
22,median_9c92cbc0c_40,float64,4004.0,90.04,52.0,"2600000.0, 50000000.0, 10000000.0, 4378000.0, 8180000.0, 1920000.0, 11600000.0, 3000000.0, 512000.0, 8244000.0"
23,first_nonZero_9c92cbc0c_40,float64,4004.0,90.04,42.0,"16.1181, 13.1461, 14.771, 14.5087, 15.3758, 17.7275, 14.4678, 16.9066, 15.925, 10.6454"
24,last_nonZero_9c92cbc0c_40,float64,4004.0,90.04,42.0,"13.9978, 15.925, 14.771, 17.9099, 15.2018, 16.1181, 14.4678, 14.5087, 13.1461, 17.7275"
25,mean_8984e4066_11,float64,3995.0,89.84,258.0,"400000.0, 200000.0, 20000000.0, 1000000.0, 30000000.0, 600000.0, 4000000.0, 2000000.0, 10000000.0, 6000000.0"
26,low_8984e4066_11,float64,3995.0,89.84,229.0,"400000.0, 200000.0, 20000000.0, 1000000.0, 2000000.0, 800000.0, 4000000.0, 30000000.0, 600000.0, 10000000.0"
27,median_8984e4066_11,float64,3995.0,89.84,255.0,"400000.0, 200000.0, 20000000.0, 1000000.0, 30000000.0, 600000.0, 4000000.0, 10000000.0, 800000.0, 2000000.0"
28,first_nonZero_8984e4066_11,float64,3995.0,89.84,227.0,"12.8992, 12.2061, 16.8112, 13.8155, 13.5924, 17.2167, 15.2018, 13.3047, 14.5087, 16.1181"
29,last_nonZero_8984e4066_11,float64,3995.0,89.84,232.0,"12.2061, 12.8992, 13.8155, 16.8112, 15.2018, 14.5087, 17.2167, 13.3047, 16.1181, 13.5924"
30,mean_bbd16b7a0_11,float64,3993.0,89.79,206.0,"200000.0, 911000.0, 400000.0, 61714000.0, 50000000.0, 22000.0, 600000.0, 650000.0, 4000000.0, 2000000.0"
31,low_bbd16b7a0_11,float64,3993.0,89.79,188.0,"200000.0, 400000.0, 20000000.0, 80000.0, 61714000.0, 50000000.0, 600000.0, 22000.0, 4000000.0, 650000.0"
32,median_bbd16b7a0_11,float64,3993.0,89.79,204.0,"200000.0, 1032000.0, 400000.0, 61714000.0, 600000.0, 22000.0, 50000000.0, 650000.0, 4000000.0, 100000.0"
33,first_nonZero_bbd16b7a0_11,float64,3993.0,89.79,193.0,"12.2061, 16.8112, 12.8992, 13.847, 17.7275, 17.938, 13.3047, 9.9988, 15.2018, 16.1181"
34,last_nonZero_bbd16b7a0_11,float64,3993.0,89.79,189.0,"12.2061, 17.7275, 12.8992, 11.2898, 17.938, 13.3047, 9.9988, 16.1181, 14.5087, 15.2018"
35,mean_9ddd6d137_11,float64,3988.0,89.68,253.0,"400000.0, 1000000.0, 2000000.0, 600000.0, 10000000.0, 30000000.0, 200000.0, 20000000.0, 4000000.0, 800000.0"
36,low_9ddd6d137_11,float64,3988.0,89.68,226.0,"400000.0, 1000000.0, 200000.0, 2000000.0, 800000.0, 20000000.0, 600000.0, 4000000.0, 30000000.0, 10000000.0"
37,median_9ddd6d137_11,float64,3988.0,89.68,251.0,"400000.0, 1000000.0, 2000000.0, 600000.0, 800000.0, 10000000.0, 4000000.0, 20000000.0, 200000.0, 30000000.0"
38,first_nonZero_9ddd6d137_11,float64,3988.0,89.68,222.0,"12.8992, 13.8155, 13.5924, 12.2061, 14.5087, 17.2167, 16.8112, 13.3047, 15.2018, 17.7275"
39,last_nonZero_9ddd6d137_11,float64,3988.0,89.68,236.0,"12.8992, 13.8155, 14.5087, 12.2061, 16.1181, 13.3047, 16.8112, 15.2018, 13.5924, 17.2167"
40,mean_03a4ccd7c_11,float64,3987.0,89.66,238.0,"400000.0, 2000000.0, 200000.0, 50000000.0, 1000000.0, 20000000.0, 10000000.0, 600000.0, 4000000.0, 911000.0"
41,low_03a4ccd7c_11,float64,3987.0,89.66,208.0,"200000.0, 400000.0, 2000000.0, 20000000.0, 50000000.0, 1000000.0, 10000000.0, 600000.0, 61714000.0, 80000.0"
42,median_03a4ccd7c_11,float64,3987.0,89.66,236.0,"2000000.0, 400000.0, 200000.0, 50000000.0, 1000000.0, 20000000.0, 10000000.0, 600000.0, 4000000.0, 61714000.0"
43,first_nonZero_03a4ccd7c_11,float64,3987.0,89.66,211.0,"12.2061, 14.5087, 12.8992, 16.8112, 17.7275, 13.8155, 13.5924, 15.2018, 16.1181, 13.3047"
44,last_nonZero_03a4ccd7c_11,float64,3987.0,89.66,215.0,"12.8992, 14.5087, 12.2061, 17.7275, 16.1181, 13.8155, 16.8112, 15.2018, 13.3047, 11.2898"
45,mean_60cb16e88_11,float64,3987.0,89.66,213.0,"400000.0, 200000.0, 50000000.0, 20000000.0, 911000.0, 100000.0, 22000.0, 2000000.0, 61714000.0, 30000000.0"
46,low_60cb16e88_11,float64,3987.0,89.66,194.0,"200000.0, 400000.0, 20000000.0, 50000000.0, 2000000.0, 80000.0, 100000.0, 22000.0, 61714000.0, 30000000.0"
47,median_60cb16e88_11,float64,3987.0,89.66,211.0,"400000.0, 200000.0, 50000000.0, 20000000.0, 1032000.0, 100000.0, 2000000.0, 22000.0, 30000000.0, 61714000.0"
48,first_nonZero_60cb16e88_11,float64,3987.0,89.66,190.0,"12.8992, 12.2061, 16.8112, 17.7275, 11.5129, 13.847, 14.5087, 9.9988, 17.2167, 17.938"
49,last_nonZero_60cb16e88_11,float64,3987.0,89.66,195.0,"17.7275, 12.8992, 12.2061, 14.5087, 16.8112, 11.2898, 11.5129, 9.9988, 17.938, 17.2167"
50,mean_8ceddccb8_40,float64,3984.0,89.59,101.0,"20000000.0, 26000000.0, 38000000.0, 1466666.6667, 50000000.0, 10000000.0, 70000000.0, 6000000.0, 550000.0, 16620000.0"
51,low_8ceddccb8_40,float64,3984.0,89.59,48.0,"20000000.0, 200000.0, 50000000.0, 26000000.0, 18500000.0, 10000000.0, 14000000.0, 3000000.0, 4000000.0, 860000.0"
52,median_8ceddccb8_40,float64,3984.0,89.59,83.0,"20000000.0, 50000000.0, 26000000.0, 900000.0, 10000000.0, 6000000.0, 16620000.0, 550000.0, 1234000.0, 22832000.0"
53,first_nonZero_8ceddccb8_40,float64,3984.0,89.59,60.0,"16.8112, 17.0736, 17.2167, 16.4546, 15.0094, 17.7275, 16.6261, 16.1181, 13.6647, 13.7102"
54,last_nonZero_8ceddccb8_40,float64,3984.0,89.59,53.0,"16.8112, 17.7275, 12.2061, 17.0736, 16.1181, 16.6261, 16.0127, 18.064, 16.1619, 11.5327"
55,mean_de7063efa_11,float64,3981.0,89.52,263.0,"400000.0, 4000000.0, 200000.0, 20000000.0, 1000000.0, 2000000.0, 600000.0, 100000.0, 40000000.0, 800000.0"
56,low_de7063efa_11,float64,3981.0,89.52,235.0,"200000.0, 400000.0, 20000000.0, 4000000.0, 1000000.0, 2000000.0, 600000.0, 800000.0, 100000.0, 40000000.0"
57,median_de7063efa_11,float64,3981.0,89.52,261.0,"4000000.0, 400000.0, 200000.0, 20000000.0, 1000000.0, 2000000.0, 100000.0, 600000.0, 40000000.0, 800000.0"
58,first_nonZero_de7063efa_11,float64,3981.0,89.52,233.0,"12.2061, 12.8992, 15.2018, 16.8112, 13.5924, 14.5087, 13.8155, 13.3047, 11.5129, 17.5044"
59,last_nonZero_de7063efa_11,float64,3981.0,89.52,245.0,"15.2018, 12.2061, 12.8992, 16.8112, 13.8155, 14.5087, 11.5129, 13.3047, 17.5044, 13.5924"
60,mean_9397535c7_11,float64,3980.0,89.50,251.0,"4000000.0, 200000.0, 2000000.0, 20000000.0, 400000.0, 600000.0, 1000000.0, 10000000.0, 30000000.0, 800000.0"
61,low_9397535c7_11,float64,3980.0,89.50,230.0,"200000.0, 20000000.0, 400000.0, 4000000.0, 2000000.0, 600000.0, 1000000.0, 800000.0, 10000000.0, 30000000.0"
62,median_9397535c7_11,float64,3980.0,89.50,250.0,"4000000.0, 200000.0, 20000000.0, 2000000.0, 600000.0, 1000000.0, 400000.0, 10000000.0, 30000000.0, 300000.0"
63,first_nonZero_9397535c7_11,float64,3980.0,89.50,229.0,"16.8112, 12.2061, 12.8992, 15.2018, 14.5087, 13.3047, 13.8155, 13.5924, 16.1181, 17.2167"
64,last_nonZero_9397535c7_11,float64,3980.0,89.50,232.0,"12.2061, 15.2018, 14.5087, 12.8992, 16.8112, 16.1181, 13.8155, 13.3047, 17.2167, 13.5924"
65,mean_6bee3733e_11,float64,3980.0,89.50,255.0,"400000.0, 20000000.0, 1000000.0, 2000000.0, 600000.0, 4000000.0, 200000.0, 10000000.0, 30000000.0, 800000.0"
66,low_6bee3733e_11,float64,3980.0,89.50,223.0,"400000.0, 20000000.0, 200000.0, 2000000.0, 1000000.0, 800000.0, 600000.0, 4000000.0, 30000000.0, 100000.0"
67,median_6bee3733e_11,float64,3980.0,89.50,252.0,"400000.0, 20000000.0, 1000000.0, 2000000.0, 200000.0, 600000.0, 30000000.0, 4000000.0, 10000000.0, 800000.0"
68,first_nonZero_6bee3733e_11,float64,3980.0,89.50,226.0,"12.8992, 16.8112, 13.5924, 14.5087, 13.8155, 12.2061, 13.3047, 17.2167, 17.7275, 16.1181"
69,last_nonZero_6bee3733e_11,float64,3980.0,89.50,233.0,"12.8992, 14.5087, 16.8112, 13.8155, 12.2061, 16.1181, 15.2018, 17.7275, 13.3047, 17.2167"
70,mean_4c48708d8_11,float64,3980.0,89.50,231.0,"400000.0, 200000.0, 911000.0, 22000.0, 600000.0, 61714000.0, 4000000.0, 650000.0, 100000.0, 1000000.0"
71,low_4c48708d8_11,float64,3980.0,89.50,206.0,"400000.0, 200000.0, 20000000.0, 80000.0, 600000.0, 22000.0, 100000.0, 61714000.0, 1000000.0, 4000000.0"
72,median_4c48708d8_11,float64,3980.0,89.50,229.0,"400000.0, 200000.0, 1032000.0, 22000.0, 600000.0, 61714000.0, 4000000.0, 100000.0, 1000000.0, 650000.0"
73,first_nonZero_4c48708d8_11,float64,3980.0,89.50,211.0,"12.8992, 12.2061, 16.8112, 13.847, 13.3047, 9.9988, 17.938, 11.5129, 15.2018, 13.5924"
74,last_nonZero_4c48708d8_11,float64,3980.0,89.50,211.0,"12.8992, 12.2061, 17.7275, 11.2898, 13.3047, 15.2018, 9.9988, 17.938, 11.5129, 14.5087"
75,mean_20e2c484e_11,float64,3978.0,89.45,236.0,"200000.0, 2000000.0, 400000.0, 600000.0, 20000000.0, 10000000.0, 30000000.0, 1000000.0, 40000000.0, 4000000.0"
76,low_20e2c484e_11,float64,3978.0,89.45,212.0,"200000.0, 2000000.0, 400000.0, 20000000.0, 600000.0, 1000000.0, 30000000.0, 10000000.0, 800000.0, 40000000.0"
77,median_20e2c484e_11,float64,3978.0,89.45,234.0,"200000.0, 2000000.0, 400000.0, 20000000.0, 600000.0, 10000000.0, 30000000.0, 1000000.0, 40000000.0, 50000000.0"
78,first_nonZero_20e2c484e_11,float64,3978.0,89.45,216.0,"12.2061, 12.8992, 14.5087, 16.8112, 13.5924, 13.3047, 13.8155, 17.5044, 16.1181, 17.2167"
79,last_nonZero_20e2c484e_11,float64,3978.0,89.45,213.0,"12.2061, 14.5087, 12.8992, 13.3047, 16.1181, 17.7275, 16.8112, 13.8155, 15.2018, 17.2167"
80,mean_0ccd6454a_11,float64,3977.0,89.43,249.0,"400000.0, 20000000.0, 200000.0, 2000000.0, 4000000.0, 1000000.0, 30000000.0, 50000000.0, 10000000.0, 600000.0"
81,low_0ccd6454a_11,float64,3977.0,89.43,220.0,"400000.0, 200000.0, 20000000.0, 2000000.0, 4000000.0, 800000.0, 1000000.0, 10000000.0, 50000000.0, 30000000.0"
82,median_0ccd6454a_11,float64,3977.0,89.43,247.0,"400000.0, 20000000.0, 200000.0, 2000000.0, 4000000.0, 1000000.0, 30000000.0, 50000000.0, 600000.0, 10000000.0"
83,first_nonZero_0ccd6454a_11,float64,3977.0,89.43,217.0,"12.8992, 16.8112, 12.2061, 13.5924, 14.5087, 17.7275, 15.2018, 13.8155, 17.2167, 16.1181"
84,last_nonZero_0ccd6454a_11,float64,3977.0,89.43,232.0,"12.8992, 12.2061, 16.8112, 14.5087, 15.2018, 17.7275, 13.5924, 13.8155, 17.2167, 16.1181"
85,mean_ea72c62a1_11,float64,3974.0,89.36,224.0,"200000.0, 911000.0, 600000.0, 61714000.0, 400000.0, 50000000.0, 30000000.0, 22000.0, 4000000.0, 650000.0"
86,low_ea72c62a1_11,float64,3974.0,89.36,201.0,"200000.0, 20000000.0, 400000.0, 80000.0, 4000000.0, 600000.0, 61714000.0, 50000000.0, 22000.0, 30000000.0"
87,median_ea72c62a1_11,float64,3974.0,89.36,223.0,"200000.0, 1032000.0, 600000.0, 61714000.0, 400000.0, 50000000.0, 22000.0, 4000000.0, 650000.0, 30000000.0"
88,first_nonZero_ea72c62a1_11,float64,3974.0,89.36,201.0,"16.8112, 12.2061, 13.847, 12.8992, 13.3047, 17.938, 17.7275, 17.2167, 15.2018, 13.5924"
89,last_nonZero_ea72c62a1_11,float64,3974.0,89.36,206.0,"12.2061, 17.7275, 11.2898, 12.8992, 17.938, 13.3047, 15.2018, 9.9988, 13.3847, 13.8155"
90,mean_5cfc625f1_11,float64,3971.0,89.30,274.0,"400000.0, 200000.0, 1000000.0, 4000000.0, 20000000.0, 2000000.0, 800000.0, 10000000.0, 30000000.0, 600000.0"
91,low_5cfc625f1_11,float64,3971.0,89.30,243.0,"200000.0, 400000.0, 1000000.0, 800000.0, 4000000.0, 10000000.0, 2000000.0, 20000000.0, 30000000.0, 600000.0"
92,median_5cfc625f1_11,float64,3971.0,89.30,271.0,"400000.0, 200000.0, 1000000.0, 2000000.0, 20000000.0, 4000000.0, 10000000.0, 800000.0, 30000000.0, 600000.0"
93,first_nonZero_5cfc625f1_11,float64,3971.0,89.30,239.0,"12.8992, 12.2061, 13.5924, 13.8155, 16.8112, 14.5087, 15.2018, 16.1181, 17.2167, 12.6115"
94,last_nonZero_5cfc625f1_11,float64,3971.0,89.30,250.0,"12.2061, 12.8992, 13.8155, 14.5087, 15.2018, 13.5924, 16.8112, 16.1181, 17.2167, 13.3047"
95,mean_3fa6c395f_11,float64,3971.0,89.30,215.0,"911000.0, 2000000.0, 22000.0, 61714000.0, 200000.0, 20000000.0, 650000.0, 50000000.0, 1000000.0, 400000.0"
96,low_3fa6c395f_11,float64,3971.0,89.30,189.0,"20000000.0, 200000.0, 80000.0, 400000.0, 22000.0, 61714000.0, 2000000.0, 50000000.0, 650000.0, 1000000.0"
97,median_3fa6c395f_11,float64,3971.0,89.30,210.0,"1032000.0, 22000.0, 2000000.0, 200000.0, 61714000.0, 20000000.0, 50000000.0, 650000.0, 1000000.0, 100000.0"
98,first_nonZero_3fa6c395f_11,float64,3971.0,89.30,195.0,"16.8112, 13.847, 9.9988, 17.938, 14.5087, 12.2061, 12.8992, 13.3847, 17.7275, 13.8155"
99,last_nonZero_3fa6c395f_11,float64,3971.0,89.30,196.0,"17.7275, 12.2061, 11.2898, 14.5087, 17.938, 9.9988, 16.8112, 12.8992, 13.3847, 13.8155"
100,mean_7f9e0d947_11,float64,3965.0,89.16,217.0,"911000.0, 61714000.0, 22000.0, 2000000.0, 650000.0, 400000.0, 100000.0, 35000000.0, 1000000.0, 50000000.0"
101,low_7f9e0d947_11,float64,3965.0,89.16,191.0,"80000.0, 20000000.0, 61714000.0, 2000000.0, 400000.0, 650000.0, 22000.0, 100000.0, 1000000.0, 10000000.0"
102,median_7f9e0d947_11,float64,3965.0,89.16,216.0,"1032000.0, 61714000.0, 2000000.0, 22000.0, 650000.0, 400000.0, 100000.0, 1000000.0, 35000000.0, 50000000.0"
103,first_nonZero_7f9e0d947_11,float64,3965.0,89.16,196.0,"13.847, 16.8112, 17.938, 12.8992, 14.5087, 13.3847, 9.9988, 11.5129, 13.8155, 16.1181"
104,last_nonZero_7f9e0d947_11,float64,3965.0,89.16,198.0,"11.2898, 17.7275, 17.938, 14.5087, 12.8992, 9.9988, 13.3847, 13.8155, 11.5129, 13.3047"
105,mean_851697562_11,float64,3962.0,89.09,248.0,"400000.0, 200000.0, 2000000.0, 50000000.0, 600000.0, 911000.0, 22000.0, 4000000.0, 10000000.0, 100000.0"
106,low_851697562_11,float64,3962.0,89.09,225.0,"200000.0, 400000.0, 2000000.0, 20000000.0, 50000000.0, 600000.0, 4000000.0, 80000.0, 22000.0, 10000000.0"
107,median_851697562_11,float64,3962.0,89.09,244.0,"400000.0, 200000.0, 50000000.0, 2000000.0, 600000.0, 1032000.0, 22000.0, 4000000.0, 10000000.0, 100000.0"
108,first_nonZero_851697562_11,float64,3962.0,89.09,223.0,"12.8992, 12.2061, 16.8112, 17.7275, 14.5087, 13.3047, 15.2018, 13.847, 9.9988, 16.1181"
109,last_nonZero_851697562_11,float64,3962.0,89.09,223.0,"17.7275, 12.2061, 12.8992, 14.5087, 13.3047, 9.9988, 16.1181, 11.2898, 15.2018, 11.5129"
110,mean_73a8a4d75_11,float64,3962.0,89.09,236.0,"400000.0, 600000.0, 911000.0, 200000.0, 22000.0, 50000000.0, 2000000.0, 61714000.0, 1000000.0, 20000000.0"
111,low_73a8a4d75_11,float64,3962.0,89.09,212.0,"200000.0, 400000.0, 20000000.0, 600000.0, 80000.0, 22000.0, 50000000.0, 2000000.0, 61714000.0, 1000000.0"
112,median_73a8a4d75_11,float64,3962.0,89.09,234.0,"400000.0, 600000.0, 200000.0, 1032000.0, 50000000.0, 22000.0, 2000000.0, 61714000.0, 1000000.0, 20000000.0"
113,first_nonZero_73a8a4d75_11,float64,3962.0,89.09,215.0,"12.8992, 16.8112, 12.2061, 13.3047, 13.847, 17.7275, 14.5087, 9.9988, 17.938, 13.8155"
114,last_nonZero_73a8a4d75_11,float64,3962.0,89.09,214.0,"17.7275, 12.2061, 12.8992, 13.3047, 11.2898, 14.5087, 9.9988, 13.8155, 17.938, 16.8112"
115,mean_dba14a5d4_11,float64,3961.0,89.07,220.0,"911000.0, 600000.0, 61714000.0, 2000000.0, 22000.0, 200000.0, 400000.0, 20000000.0, 650000.0, 100000.0"
116,low_dba14a5d4_11,float64,3961.0,89.07,201.0,"20000000.0, 80000.0, 400000.0, 2000000.0, 600000.0, 61714000.0, 200000.0, 22000.0, 1000000.0, 650000.0"
117,median_dba14a5d4_11,float64,3961.0,89.07,217.0,"1032000.0, 600000.0, 61714000.0, 2000000.0, 22000.0, 200000.0, 400000.0, 20000000.0, 100000.0, 650000.0"
118,first_nonZero_dba14a5d4_11,float64,3961.0,89.07,197.0,"16.8112, 13.847, 13.3047, 17.938, 14.5087, 12.2061, 12.8992, 9.9988, 13.8155, 13.3847"
119,last_nonZero_dba14a5d4_11,float64,3961.0,89.07,205.0,"17.7275, 11.2898, 13.3047, 17.938, 14.5087, 12.8992, 12.2061, 9.9988, 16.8112, 13.3847"
120,mean_5d60b9ba7_11,float64,3960.0,89.05,224.0,"911000.0, 400000.0, 61714000.0, 22000.0, 650000.0, 1000000.0, 100000.0, 600000.0, 35000000.0, 2600000.0"
121,low_5d60b9ba7_11,float64,3960.0,89.05,204.0,"20000000.0, 80000.0, 400000.0, 61714000.0, 22000.0, 650000.0, 100000.0, 1000000.0, 200000.0, 600000.0"
122,median_5d60b9ba7_11,float64,3960.0,89.05,221.0,"1032000.0, 400000.0, 61714000.0, 22000.0, 650000.0, 1000000.0, 100000.0, 2600000.0, 600000.0, 35000000.0"
123,first_nonZero_5d60b9ba7_11,float64,3960.0,89.05,205.0,"13.847, 16.8112, 12.8992, 17.938, 9.9988, 11.5129, 13.3847, 13.8155, 17.7275, 14.771"
124,last_nonZero_5d60b9ba7_11,float64,3960.0,89.05,205.0,"12.8992, 11.2898, 17.7275, 17.938, 9.9988, 13.8155, 13.3847, 11.5129, 13.3047, 12.2061"
125,mean_b66bf9d44_11,float64,3953.0,88.89,186.0,"911000.0, 61714000.0, 22000.0, 650000.0, 35000000.0, 50000000.0, 100000.0, 1000000.0, 600000.0, 4000.0"
126,low_b66bf9d44_11,float64,3953.0,88.89,170.0,"80000.0, 61714000.0, 20000000.0, 22000.0, 650000.0, 50000000.0, 200000.0, 100000.0, 1000000.0, 600000.0"
127,median_b66bf9d44_11,float64,3953.0,88.89,184.0,"1032000.0, 61714000.0, 22000.0, 650000.0, 50000000.0, 35000000.0, 100000.0, 1000000.0, 600000.0, 2600000.0"
128,first_nonZero_b66bf9d44_11,float64,3953.0,88.89,176.0,"13.847, 17.938, 16.8112, 9.9988, 13.3847, 17.7275, 11.5129, 13.8155, 13.3047, 8.2943"
129,last_nonZero_b66bf9d44_11,float64,3953.0,88.89,169.0,"17.7275, 11.2898, 17.938, 9.9988, 13.3847, 12.2061, 11.5129, 14.5087, 13.8155, 13.3047"

In [7]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
high_48df886f9_4991,4447.0,9.093418e+07,2.481567e+08,4000.000000,4.652000e+09
mean_48df886f9_4991,4447.0,9.846985e+06,1.460954e+07,4000.000000,4.000000e+08
low_48df886f9_4991,4447.0,1.249765e+06,8.502263e+06,52.000000,4.000000e+08
median_48df886f9_4991,4447.0,6.077197e+06,1.344192e+07,2000.000000,4.000000e+08
sum_48df886f9_4991,4447.0,1.392292e+09,2.408176e+09,4000.000000,2.273642e+10
stddev_48df886f9_4991,4447.0,2.783841e+06,4.538350e+06,56.619523,6.594061e+07
first_nonZero_48df886f9_4991,4447.0,1.441295e+01,2.161032e+00,3.970292,2.021244e+01
last_nonZero_48df886f9_4991,4447.0,1.452458e+01,2.123884e+00,6.511745,2.021244e+01
nb_nans_48df886f9_4991,4447.0,4.833572e+03,2.122190e+02,3002.000000,4.990000e+03
unique_48df886f9_4991,4447.0,6.715426e+01,1.066218e+02,2.000000,8.130000e+02
high_48df886f9_4511,4447.0,8.966139e+07,2.480973e+08,0.000000,4.652000e+09
mean_48df886f9_4511,4446.0,9.960573e+06,1.542205e+07,4000.000000,4.000000e+08
low_48df886f9_4511,4446.0,1.305877e+06,8.598462e+06,52.000000,4.000000e+08
median_48df886f9_4511,4446.0,6.286797e+06,1.527595e+07,2000.000000,4.000000e+08
sum_48df886f9_4511,4447.0,1.220011e+09,2.201790e+09,0.000000,2.044635e+10
stddev_48df886f9_4511,4447.0,2.735215e+06,4.698686e+06,0.000000,6.935974e+07
first_nonZero_48df886f9_4511,4446.0,1.440156e+01,2.225184e+00,3.970292,2.021244e+01
last_nonZero_48df886f9_4511,4446.0,1.449778e+01,2.120709e+00,6.511745,2.021244e+01
nb_nans_48df886f9_4511,4447.0,4.372732e+03,1.948791e+02,2720.000000,4.511000e+03
unique_48df886f9_4511,4447.0,6.202091e+01,1.001618e+02,1.000000,7.630000e+02
high_9ddd6d137_480,4447.0,3.058062e+07,4.424588e+07,0.000000,3.196120e+08
mean_9ddd6d137_480,4196.0,8.888773e+06,1.220794e+07,1164.000000,2.000000e+08
low_9ddd6d137_480,4196.0,2.390200e+06,7.263514e+06,164.660000,2.000000e+08
median_9ddd6d137_480,4196.0,6.571450e+06,1.189429e+07,1164.000000,2.000000e+08
sum_9ddd6d137_480,4447.0,1.722814e+08,3.603689e+08,0.000000,3.786605e+09
stddev_9ddd6d137_480,4447.0,2.294484e+06,3.366690e+06,0.000000,2.161033e+07
first_nonZero_9ddd6d137_480,4196.0,1.428685e+01,2.283343e+00,7.060476,1.957362e+01
last_nonZero_9ddd6d137_480,4196.0,1.441045e+01,2.024048e+00,7.060476,1.958262e+01
nb_nans_9ddd6d137_480,4447.0,4.608401e+02,2.126734e+01,282.000000,4.800000e+02
unique_9ddd6d137_480,4447.0,1.320778e+01,1.309839e+01,1.000000,7.800000e+01
high_9ddd6d137_11,4447.0,1.312804e+06,9.739640e+06,0.000000,3.023120e+08
mean_9ddd6d137_11,459.0,1.157848e+07,2.622739e+07,8000.000000,3.023120e+08
low_9ddd6d137_11,459.0,1.049882e+07,2.589023e+07,8000.000000,3.023120e+08
median_9ddd6d137_11,459.0,1.151990e+07,2.619325e+07,8000.000000,3.023120e+08
sum_9ddd6d137_11,4447.0,1.359463e+06,9.989361e+06,0.000000,3.023120e+08
stddev_9ddd6d137_11,4447.0,3.977407e+05,2.941840e+06,0.000000,9.115050e+07
first_nonZero_9ddd6d137_11,459.0,1.430853e+01,2.239231e+00,8.987322,1.952697e+01
last_nonZero_9ddd6d137_11,459.0,1.432740e+01,2.195115e+00,8.987322,1.952697e+01
nb_nans_9ddd6d137_11,4447.0,1.087834e+01,3.862180e-01,7.000000,1.100000e+01
unique_9ddd6d137_11,4447.0,1.120980e+00,3.826279e-01,1.000000,5.000000e+00
high_5cfc625f1_11,4447.0,1.349766e+06,1.023413e+07,0.000000,3.023120e+08
mean_5cfc625f1_11,476.0,1.166696e+07,2.801652e+07,4000.000000,3.023120e+08
low_5cfc625f1_11,476.0,1.080625e+07,2.790109e+07,4000.000000,3.023120e+08
median_5cfc625f1_11,476.0,1.162419e+07,2.801945e+07,4000.000000,3.023120e+08
sum_5cfc625f1_11,4447.0,1.388893e+06,1.036472e+07,0.000000,3.023120e+08
stddev_5cfc625f1_11,4447.0,4.089666e+05,3.089812e+06,0.000000,9.115050e+07
first_nonZero_5cfc625f1_11,476.0,1.430365e+01,2.206967e+00,8.294300,1.952697e+01
last_nonZero_5cfc625f1_11,476.0,1.428199e+01,2.194272e+00,8.294300,1.952697e+01
nb_nans_5cfc625f1_11,4447.0,1.087272e+01,3.979144e-01,7.000000,1.100000e+01
unique_5cfc625f1_11,4447.0,1.125928e+00,3.909343e-01,1.000000,5.000000e+00
high_8984e4066_11,4447.0,1.330598e+06,1.005227e+07,0.000000,3.023120e+08
mean_8984e4066_11,452.0,1.182091e+07,2.717776e+07,1974.000000,3.023120e+08
low_8984e4066_11,452.0,1.061281e+07,2.677677e+07,1974.000000,3.023120e+08
median_8984e4066_11,452.0,1.176064e+07,2.714518e+07,1974.000000,3.023120e+08
sum_8984e4066_11,4447.0,1.372209e+06,1.026337e+07,0.000000,3.023120e+08
stddev_8984e4066_11,4447.0,4.023129e+05,3.032142e+06,0.000000,9.115050e+07
first_nonZero_8984e4066_11,452.0,1.435890e+01,2.283383e+00,7.588324,1.952697e+01
last_nonZero_8984e4066_11,452.0,1.433180e+01,2.274818e+00,7.588324,1.952697e+01
nb_nans_8984e4066_11,4447.0,1.087700e+01,4.001003e-01,7.000000,1.100000e+01
unique_8984e4066_11,4447.0,1.121205e+00,3.898367e-01,1.000000,5.000000e+00
high_0ccd6454a_11,4447.0,1.209026e+06,8.123020e+06,0.000000,1.966800e+08
mean_0ccd6454a_11,470.0,1.035324e+07,2.080334e+07,1164.000000,1.966800e+08
low_0ccd6454a_11,470.0,9.351785e+06,2.043334e+07,1164.000000,1.966800e+08
median_0ccd6454a_11,470.0,1.030931e+07,2.080490e+07,1164.000000,1.966800e+08
sum_0ccd6454a_11,4447.0,1.264742e+06,8.384362e+06,0.000000,1.966800e+08
stddev_0ccd6454a_11,4447.0,3.675625e+05,2.459182e+06,0.000000,5.930125e+07
first_nonZero_0ccd6454a_11,470.0,1.427406e+01,2.256398e+00,7.060476,1.909709e+01
last_nonZero_0ccd6454a_11,470.0,1.423524e+01,2.267578e+00,7.060476,1.909709e+01
nb_nans_0ccd6454a_11,4447.0,1.087272e+01,4.051960e-01,7.000000,1.100000e+01
unique_0ccd6454a_11,4447.0,1.125253e+00,3.937301e-01,1.000000,5.000000e+00
high_9397535c7_11,4447.0,1.183418e+06,8.557275e+06,0.000000,2.400000e+08
mean_9397535c7_11,467.0,1.053956e+07,2.321463e+07,164.660000,2.400000e+08
low_9397535c7_11,467.0,9.813423e+06,2.295210e+07,164.660000,2.400000e+08
median_9397535c7_11,467.0,1.053630e+07,2.321601e+07,164.660000,2.400000e+08
sum_9397535c7_11,4447.0,1.255171e+06,8.953500e+06,0.000000,2.400000e+08
stddev_9397535c7_11,4447.0,3.612963e+05,2.599893e+06,0.000000,7.236272e+07
first_nonZero_9397535c7_11,467.0,1.422696e+01,2.365000e+00,5.109937,1.929615e+01
last_nonZero_9397535c7_11,467.0,1.421296e+01,2.367808e+00,5.109937,1.929615e+01
nb_nans_9397535c7_11,4447.0,1.087407e+01,4.022766e-01,7.000000,1.100000e+01
unique_9397535c7_11,4447.0,1.124129e+00,3.915094e-01,1.000000,5.000000e+00
high_de7063efa_11,4447.0,1.376755e+06,1.101180e+07,0.000000,3.167500e+08
mean_de7063efa_11,466.0,1.232782e+07,3.100266e+07,1316.000000,3.167500e+08
low_de7063efa_11,466.0,1.152214e+07,3.083887e+07,1316.000000,3.167500e+08
median_de7063efa_11,466.0,1.232291e+07,3.100451e+07,1316.000000,3.167500e+08
sum_de7063efa_11,4447.0,1.472163e+06,1.147238e+07,0.000000,3.167500e+08
stddev_de7063efa_11,4447.0,4.214914e+05,3.345375e+06,0.000000,9.550372e+07
first_nonZero_de7063efa_11,466.0,1.427103e+01,2.322045e+00,7.183112,1.957362e+01
last_nonZero_de7063efa_11,466.0,1.424935e+01,2.365786e+00,7.183112,1.957362e+01
nb_nans_de7063efa_11,4447.0,1.087340e+01,4.062387e-01,7.000000,1.100000e+01
unique_de7063efa_11,4447.0,1.124353e+00,3.922989e-01,1.000000,5.000000e+00
high_74f3ac6af_11,4447.0,1.388961e+06,9.560518e+06,0.000000,3.023120e+08
mean_74f3ac6af_11,501.0,1.146481e+07,2.519729e+07,2000.000000,3.023120e+08
low_74f3ac6af_11,501.0,1.061270e+07,2.503934e+07,2000.000000,3.023120e+08
median_74f3ac6af_11,501.0,1.145364e+07,2.519572e+07,2000.000000,3.023120e+08
sum_74f3ac6af_11,4447.0,1.484051e+06,1.007017e+07,0.000000,3.023120e+08
stddev_74f3ac6af_11,4447.0,4.250020e+05,2.911500e+06,0.000000,9.115050e+07
first_nonZero_74f3ac6af_11,501.0,1.428708e+01,2.349721e+00,7.601402,1.952697e+01
last_nonZero_74f3ac6af_11,501.0,1.422632e+01,2.363318e+00,7.601402,1.952697e+01
nb_nans_74f3ac6af_11,4447.0,1.086305e+01,4.251431e-01,7.000000,1.100000e+01
unique_74f3ac6af_11,4447.0,1.134248e+00,4.087587e-01,1.000000,5.000000e+00
high_6bee3733e_11,4447.0,1.372085e+06,9.637478e+06,0.000000,3.023120e+08
mean_6bee3733e_11,467.0,1.182395e+07,2.556332e+07,330.000000,3.023120e+08
low_6bee3733e_11,467.0,1.066272e+07,2.522797e+07,330.000000,3.023120e+08
median_6bee3733e_11,467.0,1.174282e+07,2.553066e+07,330.000000,3.023120e+08
sum_6bee3733e_11,4447.0,1.463616e+06,1.021099e+07,0.000000,3.023120e+08
stddev_6bee3733e_11,4447.0,4.183703e+05,2.929398e+06,0.000000,9.115050e+07
first_nonZero_6bee3733e_11,467.0,1.431883e+01,2.336588e+00,5.802118,1.952697e+01
last_nonZero_6bee3733e_11,467.0,1.426615e+01,2.349349e+00,5.802118,1.952697e+01
nb_nans_6bee3733e_11,4447.0,1.086823e+01,4.291400e-01,7.000000,1.100000e+01
unique_6bee3733e_11,4447.0,1.129301e+00,4.130823e-01,1.000000,5.000000e+00
high_20e2c484e_11,4447.0,1.330857e+06,9.806851e+06,0.000000,3.023120e+08
mean_20e2c484e_11,469.0,1.157315e+07,2.646855e+07,2000.000000,3.023120e+08
low_20e2c484e_11,469.0,1.068354e+07,2.623240e+07,2000.000000,3.023120e+08
median_20e2c484e_11,469.0,1.145566e+07,2.643652e+07,2000.000000,3.023120e+08
sum_20e2c484e_11,4447.0,1.421038e+06,1.030269e+07,0.000000,3.023120e+08
stddev_20e2c484e_11,4447.0,4.064700e+05,2.978764e+06,0.000000,9.115050e+07
first_nonZero_20e2c484e_11,469.0,1.416950e+01,2.384620e+00,7.601402,1.952697e+01
last_nonZero_20e2c484e_11,469.0,1.410597e+01,2.401590e+00,7.601402,1.952697e+01
nb_nans_20e2c484e_11,4447.0,1.087025e+01,4.210322e-01,7.000000,1.100000e+01
unique_20e2c484e_11,4447.0,1.127502e+00,4.059573e-01,1.000000,5.000000e+00
high_5adfe7419_11,4447.0,1.468289e+06,1.080716e+07,0.000000,3.023120e+08
mean_5adfe7419_11,442.0,1.359051e+07,3.004660e+07,400.000000,3.023120e+08
low_5adfe7419_11,442.0,1.250404e+07,2.982977e+07,400.000000,3.023120e+08
median_5adfe7419_11,442.0,1.353576e+07,3.005018e+07,400.000000,3.023120e+08
sum_5adfe7419_11,4447.0,1.549503e+06,1.119961e+07,0.000000,3.023120e+08
stddev_5adfe7419_11,4447.0,4.472347e+05,3.276922e+06,0.000000,9.115050e+07
first_nonZero_5adfe7419_11,442.0,1.416700e+01,2.534804e+00,5.993961,1.952697e+01
last_nonZero_5adfe7419_11,442.0,1.414326e+01,2.572619e+00,5.993961,1.952697e+01
nb_nans_5adfe7419_11,4447.0,1.087632e+01,4.172335e-01,7.000000,1.100000e+01
unique_5adfe7419_11,4447.0,1.121430e+00,4.003001e-01,1.000000,5.000000e+00
high_03a4ccd7c_11,4447.0,1.369096e+06,9.495254e+06,0.000000,3.023120e+08
mean_03a4ccd7c_11,460.0,1.234137e+07,2.562461e+07,330.000000,3.023120e+08
low_03a4ccd7c_11,460.0,1.145077e+07,2.530036e+07,330.000000,3.023120e+08
median_03a4ccd7c_11,460.0,1.233658e+07,2.562680e+07,330.000000,3.023120e+08
sum_03a4ccd7c_11,4447.0,1.466507e+06,1.009559e+07,0.000000,3.023120e+08
stddev_03a4ccd7c_11,4447.0,4.188005e+05,2.894108e+06,0.000000,9.115050e+07
first_nonZero_03a4ccd7c_11,460.0,1.424549e+01,2.485398e+00,5.802118,1.952697e+01
last_nonZero_03a4ccd7c_11,460.0,1.417608e+01,2.506205e+00,5.802118,1.952697e+01
nb_nans_03a4ccd7c_11,4447.0,1.087227e+01,4.208498e-01,7.000000,1.100000e+01
unique_03a4ccd7c_11,4447.0,1.125028e+00,4.014381e-01,1.000000,5.000000e+00
high_ecbd077d0_11,4447.0,1.406262e+06,9.927517e+06,0.000000,3.023120e+08
mean_ecbd077d0_11,441.0,1.312241e+07,2.744081e+07,2000.000000,3.023120e+08
low_ecbd077d0_11,441.0,1.213629e+07,2.725972e+07,2000.000000,3.023120e+08
median_ecbd077d0_11,441.0,1.304881e+07,2.741378e+07,2000.000000,3.023120e+08
sum_ecbd077d0_11,4447.0,1.495845e+06,1.043932e+07,0.000000,3.023120e+08
stddev_ecbd077d0_11,4447.0,4.291743e+05,3.017444e+06,0.000000,9.115050e+07
first_nonZero_ecbd077d0_11,441.0,1.433400e+01,2.387638e+00,7.601402,1.952697e+01
last_nonZero_ecbd077d0_11,441.0,1.427730e+01,2.477691e+00,7.601402,1.952697e+01
nb_nans_ecbd077d0_11,4447.0,1.087565e+01,4.221255e-01,7.000000,1.100000e+01
unique_ecbd077d0_11,4447.0,1.121655e+00,4.021939e-01,1.000000,5.000000e+00
high_851697562_11,4447.0,1.661813e+06,1.141287e+07,0.000000,3.023120e+08
mean_851697562_11,485.0,1.405843e+07,3.012856e+07,2000.000000,3.023120e+08
low_851697562_11,485.0,1.298228e+07,2.982015e+07,2000.000000,3.023120e+08
median_851697562_11,485.0,1.399220e+07,3.013794e+07,2000.000000,3.023120e+08
sum_851697562_11,4447.0,1.762587e+06,1.193065e+07,0.000000,3.023120e+08
stddev_851697562_11,4447.0,5.062276e+05,3.462560e+06,0.000000,9.115050e+07
first_nonZero_851697562_11,485.0,1.433119e+01,2.427521e+00,7.601402,1.952697e+01
last_nonZero_851697562_11,485.0,1.430588e+01,2.471488e+00,7.601402,1.952697e+01
nb_nans_851697562_11,4447.0,1.086440e+01,4.375624e-01,7.000000,1.100000e+01
unique_851697562_11,4447.0,1.132674e+00,4.160853e-01,1.000000,5.000000e+00
high_60cb16e88_11,4447.0,1.447950e+06,9.927138e+06,0.000000,3.167500e+08
mean_60cb16e88_11,460.0,1.306676e+07,2.678024e+07,2000.000000,3.167500e+08
low_60cb16e88_11,460.0,1.213740e+07,2.654749e+07,2000.000000,3.167500e+08
median_60cb16e88_11,460.0,1.306299e+07,2.678199e+07,2000.000000,3.167500e+08
sum_60cb16e88_11,4447.0,1.542248e+06,1.040389e+07,0.000000,3.167500e+08
stddev_60cb16e88_11,4447.0,4.427501e+05,3.020301e+06,0.000000,9.550372e+07
first_nonZero_60cb16e88_11,460.0,1.417658e+01,2.522838e+00,7.601402,1.957362e+01
last_nonZero_60cb16e88_11,460.0,1.415805e+01,2.560445e+00,7.601402,1.957362e+01
nb_nans_60cb16e88_11,4447.0,1.087070e+01,4.296302e-01,7.000000,1.100000e+01
unique_60cb16e88_11,4447.0,1.125928e+00,4.050626e-01,1.000000,5.000000e+00
high_73a8a4d75_11,4447.0,1.605061e+06,1.027833e+07,0.000000,2.744060e+08
mean_73a8a4d75_11,485.0,1.337456e+07,2.544565e+07,164.660000,2.744060e+08
low_73a8a4d75_11,485.0,1.221646e+07,2.510090e+07,164.660000,2.744060e+08
median_73a8a4d75_11,485.0,1.318818e+07,2.530300e+07,164.660000,2.744060e+08
sum_73a8a4d75_11,4447.0,1.718944e+06,1.091564e+07,0.000000,2.744060e+08
stddev_73a8a4d75_11,4447.0,4.907261e+05,3.130714e+06,0.000000,8.273652e+07
first_nonZero_73a8a4d75_11,485.0,1.429293e+01,2.484127e+00,5.109937,1.943012e+01
last_nonZero_73a8a4d75_11,485.0,1.422168e+01,2.557892e+00,5.109937,1.943012e+01
nb_nans_73a8a4d75_11,4447.0,1.086418e+01,4.403112e-01,7.000000,1.100000e+01
unique_73a8a4d75_11,4447.0,1.132674e+00,4.166255e-01,1.000000,5.000000e+00
high_4c48708d8_11,4447.0,1.474727e+06,9.981354e+06,0.000000,3.023120e+08
mean_4c48708d8_11,467.0,1.291727e+07,2.647717e+07,2000.000000,3.023120e+08
low_4c48708d8_11,467.0,1.188537e+07,2.618552e+07,1494.000000,3.023120e+08
median_4c48708d8_11,467.0,1.286073e+07,2.648617e+07,2000.000000,3.023120e+08
sum_4c48708d8_11,4447.0,1.589101e+06,1.060016e+07,0.000000,3.023120e+08
stddev_4c48708d8_11,4447.0,4.516927e+05,3.042972e+06,0.000000,9.115050e+07
first_nonZero_4c48708d8_11,467.0,1.428973e+01,2.428655e+00,7.601402,1.952697e+01
last_nonZero_4c48708d8_11,467.0,1.421586e+01,2.532465e+00,7.309881,1.952697e+01
nb_nans_4c48708d8_11,4447.0,1.086733e+01,4.402496e-01,7.000000,1.100000e+01
unique_4c48708d8_11,4447.0,1.129076e+00,4.150537e-01,1.000000,5.000000e+00
high_ea72c62a1_11,4447.0,1.690669e+06,1.164377e+07,0.000000,3.167500e+08
mean_ea72c62a1_11,473.0,1.448953e+07,3.036096e+07,2000.000000,3.167500e+08
low_ea72c62a1_11,473.0,1.328984e+07,3.007874e+07,1494.000000,3.167500e+08
median_ea72c62a1_11,473.0,1.428116e+07,3.025135e+07,2000.000000,3.167500e+08
sum_ea72c62a1_11,4447.0,1.836358e+06,1.237709e+07,0.000000,3.167500e+08
stddev_ea72c62a1_11,4447.0,5.190860e+05,3.549366e+06,0.000000,9.550372e+07
first_nonZero_ea72c62a1_11,473.0,1.428094e+01,2.516620e+00,7.601402,1.957362e+01
last_nonZero_ea72c62a1_11,473.0,1.423047e+01,2.593142e+00,7.309881,1.957362e+01
nb_nans_ea72c62a1_11,4447.0,1.086463e+01,4.465356e-01,7.000000,1.100000e+01
unique_ea72c62a1_11,4447.0,1.131324e+00,4.192046e-01,1.000000,5.000000e+00
high_bbd16b7a0_11,4447.0,1.639614e+06,1.142349e+07,0.000000,3.023120e+08
mean_bbd16b7a0_11,454.0,1.507729e+07,3.154333e+07,330.000000,3.023120e+08
low_bbd16b7a0_11,454.0,1.422582e+07,3.140462e+07,330.000000,3.023120e+08
median_bbd16b7a0_11,454.0,1.498370e+07,3.152402e+07,330.000000,3.023120e+08
sum_bbd16b7a0_11,4447.0,1.766104e+06,1.205288e+07,0.000000,3.023120e+08
stddev_bbd16b7a0_11,4447.0,5.018888e+05,3.474503e+06,0.000000,9.115050e+07
first_nonZero_bbd16b7a0_11,454.0,1.427743e+01,2.605888e+00,5.802118,1.952697e+01
last_nonZero_bbd16b7a0_11,454.0,1.421043e+01,2.667635e+00,5.802118,1.952697e+01
nb_nans_bbd16b7a0_11,4447.0,1.087070e+01,4.389525e-01,7.000000,1.100000e+01
unique_bbd16b7a0_11,4447.0,1.125253e+00,4.099620e-01,1.000000,5.000000e+00
high_3fa6c395f_11,4447.0,1.419385e+06,8.417722e+06,0.000000,1.546360e+08
mean_3fa6c395f_11,476.0,1.226940e+07,2.134757e+07,2000.000000,1.546360e+08
low_3fa6c395f_11,476.0,1.142342e+07,2.109426e+07,2000.000000,1.546360e+08
median_3fa6c395f_11,476.0,1.216015e+07,2.131644e+07,2000.000000,1.546360e+08
sum_3fa6c395f_11,4447.0,1.562653e+06,9.362125e+06,0.000000,1.546360e+08
stddev_3fa6c395f_11,4447.0,4.365491e+05,2.586868e+06,0.000000,4.662451e+07
first_nonZero_3fa6c395f_11,476.0,1.432158e+01,2.427120e+00,7.601402,1.885658e+01
last_nonZero_3fa6c395f_11,476.0,1.422302e+01,2.525700e+00,7.601402,1.885658e+01
nb_nans_3fa6c395f_11,4447.0,1.086238e+01,4.568113e-01,7.000000,1.100000e+01
unique_3fa6c395f_11,4447.0,1.133348e+00,4.268129e-01,1.000000,5.000000e+00
high_dba14a5d4_11,4447.0,1.577610e+06,1.038096e+07,0.000000,3.023120e+08
mean_dba14a5d4_11,486.0,1.327735e+07,2.680205e+07,164.660000,3.023120e+08
low_dba14a5d4_11,486.0,1.219176e+07,2.644722e+07,164.660000,3.023120e+08
median_dba14a5d4_11,486.0,1.323863e+07,2.680592e+07,164.660000,3.023120e+08
sum_dba14a5d4_11,4447.0,1.702759e+06,1.102725e+07,0.000000,3.023120e+08
stddev_dba14a5d4_11,4447.0,4.831045e+05,3.163788e+06,0.000000,9.115050e+07
first_nonZero_dba14a5d4_11,486.0,1.424219e+01,2.518187e+00,5.109937,1.952697e+01
last_nonZero_dba14a5d4_11,486.0,1.416251e+01,2.620182e+00,5.109937,1.952697e+01
nb_nans_dba14a5d4_11,4447.0,1.086238e+01,4.503650e-01,7.000000,1.100000e+01
unique_dba14a5d4_11,4447.0,1.133573e+00,4.201026e-01,1.000000,5.000000e+00
high_5d60b9ba7_11,4447.0,1.518327e+06,8.694324e+06,0.000000,1.400000e+08
mean_5d60b9ba7_11,487.0,1.273939e+07,2.110204e+07,2000.000000,1.400000e+08
low_5d60b9ba7_11,487.0,1.166026e+07,2.060892e+07,2000.000000,1.400000e+08
median_5d60b9ba7_11,487.0,1.269007e+07,2.106157e+07,2000.000000,1.400000e+08
sum_5d60b9ba7_11,4447.0,1.670046e+06,9.654997e+06,0.000000,1.400000e+08
stddev_5d60b9ba7_11,4447.0,4.661396e+05,2.666499e+06,0.000000,4.221159e+07
first_nonZero_5d60b9ba7_11,487.0,1.437688e+01,2.412771e+00,7.601402,1.875715e+01
last_nonZero_5d60b9ba7_11,487.0,1.431335e+01,2.506081e+00,7.601402,1.875715e+01
nb_nans_5d60b9ba7_11,4447.0,1.086058e+01,4.557721e-01,7.000000,1.100000e+01
unique_5d60b9ba7_11,4447.0,1.135147e+00,4.241306e-01,1.000000,5.000000e+00
high_7f9e0d947_11,4447.0,1.610841e+06,9.990100e+06,0.000000,3.023120e+08
mean_7f9e0d947_11,482.0,1.361373e+07,2.536773e+07,1316.000000,3.023120e+08
low_7f9e0d947_11,482.0,1.248776e+07,2.502284e+07,1316.000000,3.023120e+08
median_7f9e0d947_11,482.0,1.352630e+07,2.533964e+07,1316.000000,3.023120e+08
sum_7f9e0d947_11,4447.0,1.759378e+06,1.081078e+07,0.000000,3.023120e+08
stddev_7f9e0d947_11,4447.0,4.940702e+05,3.051515e+06,0.000000,9.115050e+07
first_nonZero_7f9e0d947_11,482.0,1.433014e+01,2.524211e+00,7.183112,1.952697e+01
last_nonZero_7f9e0d947_11,482.0,1.425391e+01,2.579624e+00,7.183112,1.952697e+01
nb_nans_7f9e0d947_11,4447.0,1.086081e+01,4.595266e-01,7.000000,1.100000e+01
unique_7f9e0d947_11,4447.0,1.134698e+00,4.263889e-01,1.000000,5.000000e+00
high_a636266f3_11,4447.0,1.773193e+06,1.055973e+07,0.000000,3.023120e+08
mean_a636266f3_11,503.0,1.432220e+07,2.615354e+07,330.000000,3.023120e+08
low_a636266f3_11,503.0,1.308505e+07,2.583887e+07,330.000000,3.023120e+08
median_a636266f3_11,503.0,1.423784e+07,2.613002e+07,330.000000,3.023120e+08
sum_a636266f3_11,4447.0,1.941921e+06,1.145506e+07,0.000000,3.023120e+08
stddev_a636266f3_11,4447.0,5.447047e+05,3.229479e+06,0.000000,9.115050e+07
first_nonZero_a636266f3_11,503.0,1.434061e+01,2.592561e+00,5.802118,1.952697e+01
last_nonZero_a636266f3_11,503.0,1.422796e+01,2.660745e+00,5.802118,1.952697e+01
nb_nans_a636266f3_11,4447.0,1.085361e+01,4.732378e-01,7.000000,1.100000e+01
unique_a636266f3_11,4447.0,1.141444e+00,4.387936e-01,1.000000,5.000000e+00
high_6931ed626_11,4447.0,1.818584e+06,1.099019e+07,0.000000,3.167500e+08
mean_6931ed626_11,504.0,1.495735e+07,2.798129e+07,1646.000000,3.167500e+08

In [8]:
# Categorical Feature Statistics
cat_stats

'No categorical/object features to summarize.'

In [9]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,-0.424,-0.665,3.062,0.016,log,43548.1,3.659291e+16,exponential

## Task Curation

In [10]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [11]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

## Export

In [12]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to santander_transaction_value/019d5dca-1ba7-77c8-b93c-71d396f67068
019d5dca-1ba7-77c8-b93c-71d396f67068
4604a2f3a2f182583102cbe78711d66e7b4296e07da8b97e0dd751b7a1cff504