### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="micro_mass",
    dataset_year="2013",
    domain_str="biology & life sciences",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C5T61S",
    download_description="""
wget https://archive.ics.uci.edu/static/public/253/micromass.zip && unzip micromass.zip micromass_un_anonymized.zip && rm micromass.zip && mkdir -p local-data-warehouse/micro_mass && unzip micromass_un_anonymized.zip -d local-data-warehouse/micro_mass/ && rm micromass_un_anonymized.zip
""",
    # References
    academic_reference_bibtex=r"""@article{mahe2014automatic,
  title={Automatic identification of mixed bacterial species fingerprints in a MALDI-TOF mass-spectrum},
  author={Mahe, Pierre and Arsac, Maud and Chatellier, Sonia and Monnin, Val{\'e}rie and Perrot, Nadine and Mailler, Sandrine and Girard, Victoria and Ramjeet, Mahendrasingh and Surre, J{\'e}r{\'e}my and Lacroix, Bruno and others},
  journal={Bioinformatics},
  volume={30},
  number={9},
  pages={1280--1286},
  year={2014},
  publisher={Oxford University Press}
}
""",
    academic_reference_bibtex_key="mahe2014automatic",
    license="CC BY 4.0",
    data_tags=["Non-IID", "Grouped"],
    curation_comments="""
We use the pure spectra version (without mixing) and replicate a grouped-based task to predict the species of strains.

- We drop columns with the same value across all samples.
- We drop constant columns (all 0).
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Species",
    problem_type="multiclass_classification",
    objective_metric_name="",
    stratify_on="Species",
    group_on="Strain",
    group_labels="per_group",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(dataset_mold.path / "micromass" / "pure_spectra_matrix.csv", header=None, names=[f"peak_list_spectra_bin_{i}" for i in range(1, 1301)], sep=";")
metadata = pd.read_csv(dataset_mold.path / "micromass" / "pure_spectra_metadata_with-species-name.csv", sep=";")
df = pd.concat([metadata, df], axis=1)
print("Loaded data shape:", df.shape)


as_cat_type = ["Strain", "Species"]
df[as_cat_type] = df[as_cat_type].astype("category")

# Drop duplicate columns based on values
df = df.loc[:, ~df.T.duplicated()]
# DRop constant columns
df = df.loc[:, (df != df.iloc[0]).any()]

df = df.sample(frac=1, random_state=42).sort_values(by="Strain").reset_index(drop=True)

Loaded data shape: (571, 1302)

## Data Checks

In [3]:
df.groupby("Strain")["Species"].first().value_counts()

/tmp/ipykernel_65639/512819356.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Strain")["Species"].first().value_counts()

Species
Escherichia coli              20
Haemophilus influenzae        18
Enterobacter cloacae          16
Bacillus cereus               10
Yersinia frederiksenii        10
Yersinia enterocolitica       10
Citrobacter freundii          10
Enterobacter asburiae         10
Streptococcus mitis           10
Shigella sonnei               10
Shigella flexneri             10
Listeria monocytogenes        10
Shigella boydii                9
Citrobacter braakii            9
Clostridium glycolicum         9
Haemophilus parainfluenzae     9
Streptococcus oralis           9
Listeria ivanovii              9
Bacillus thuringiensis         8
Clostridium difficile          7
Name: count, dtype: int64

In [4]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 571
Columns: 1084
Use sampling: False (sample size: 571)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['peak_list_spectra_bin_838', 'peak_list_spectra_bin_719', 'peak_list_spectra_bin_1261', 'peak_list_spectra_bin_1002', 'Strain', 'peak_list_spectra_bin_695', 'peak_list_spectra_bin_1239', 'peak_list_spectra_bin_430', 'peak_list_spectra_bin_744', 'peak_list_spectra_bin_1163']
Rows remaining as candidates after top-10 filter: 43 (of 571)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [5]:
# Sample Rows
df_head

,Species,Strain,peak_list_spectra_bin_3,peak_list_spectra_bin_4,peak_list_spectra_bin_5,peak_list_spectra_bin_7,peak_list_spectra_bin_8,peak_list_spectra_bin_9,peak_list_spectra_bin_10,peak_list_spectra_bin_11,peak_list_spectra_bin_12,peak_list_spectra_bin_13,peak_list_spectra_bin_14,peak_list_spectra_bin_15,peak_list_spectra_bin_16,peak_list_spectra_bin_17,peak_list_spectra_bin_18,peak_list_spectra_bin_19,peak_list_spectra_bin_20,peak_list_spectra_bin_21,peak_list_spectra_bin_22,peak_list_spectra_bin_23,peak_list_spectra_bin_24,peak_list_spectra_bin_25,peak_list_spectra_bin_26,peak_list_spectra_bin_28,peak_list_spectra_bin_29,peak_list_spectra_bin_30,peak_list_spectra_bin_31,peak_list_spectra_bin_32,peak_list_spectra_bin_34,peak_list_spectra_bin_35,peak_list_spectra_bin_36,peak_list_spectra_bin_37,peak_list_spectra_bin_39,peak_list_spectra_bin_40,peak_list_spectra_bin_41,peak_list_spectra_bin_42,peak_list_spectra_bin_43,peak_list_spectra_bin_44,peak_list_spectra_bin_45,peak_list_spectra_bin_46,peak_list_spectra_bin_47,peak_list_spectra_bin_48,peak_list_spectra_bin_49,peak_list_spectra_bin_50,peak_list_spectra_bin_52,peak_list_spectra_bin_53,peak_list_spectra_bin_55,peak_list_spectra_bin_56,peak_list_spectra_bin_57,peak_list_spectra_bin_58,peak_list_spectra_bin_59,peak_list_spectra_bin_60,peak_list_spectra_bin_61,peak_list_spectra_bin_62,peak_list_spectra_bin_64,peak_list_spectra_bin_66,peak_list_spectra_bin_67,peak_list_spectra_bin_68,peak_list_spectra_bin_69,peak_list_spectra_bin_70,peak_list_spectra_bin_72,peak_list_spectra_bin_73,peak_list_spectra_bin_74,peak_list_spectra_bin_76,peak_list_spectra_bin_77,peak_list_spectra_bin_78,peak_list_spectra_bin_79,peak_list_spectra_bin_80,peak_list_spectra_bin_81,peak_list_spectra_bin_83,peak_list_spectra_bin_85,peak_list_spectra_bin_86,peak_list_spectra_bin_87,peak_list_spectra_bin_88,peak_list_spectra_bin_89,peak_list_spectra_bin_90,peak_list_spectra_bin_91,peak_list_spectra_bin_92,peak_list_spectra_bin_93,peak_list_spectra_bin_95,peak_list_spectra_bin_97,peak_list_spectra_bin_98,peak_list_spectra_bin_99,peak_list_spectra_bin_100,peak_list_spectra_bin_101,peak_list_spectra_bin_103,peak_list_spectra_bin_105,peak_list_spectra_bin_106,peak_list_spectra_bin_107,peak_list_spectra_bin_108,peak_list_spectra_bin_109,peak_list_spectra_bin_111,peak_list_spectra_bin_112,peak_list_spectra_bin_113,peak_list_spectra_bin_115,peak_list_spectra_bin_116,peak_list_spectra_bin_117,peak_list_spectra_bin_118,peak_list_spectra_bin_119,peak_list_spectra_bin_120,peak_list_spectra_bin_121,peak_list_spectra_bin_122,peak_list_spectra_bin_123,peak_list_spectra_bin_124,peak_list_spectra_bin_125,peak_list_spectra_bin_127,peak_list_spectra_bin_128,peak_list_spectra_bin_130,peak_list_spectra_bin_131,peak_list_spectra_bin_132,peak_list_spectra_bin_133,peak_list_spectra_bin_134,peak_list_spectra_bin_135,peak_list_spectra_bin_137,peak_list_spectra_bin_138,peak_list_spectra_bin_139,peak_list_spectra_bin_140,peak_list_spectra_bin_141,peak_list_spectra_bin_143,peak_list_spectra_bin_145,peak_list_spectra_bin_147,peak_list_spectra_bin_149,peak_list_spectra_bin_150,peak_list_spectra_bin_151,peak_list_spectra_bin_152,peak_list_spectra_bin_153,peak_list_spectra_bin_154,peak_list_spectra_bin_155,peak_list_spectra_bin_156,peak_list_spectra_bin_157,peak_list_spectra_bin_158,peak_list_spectra_bin_159,peak_list_spectra_bin_161,peak_list_spectra_bin_162,peak_list_spectra_bin_163,peak_list_spectra_bin_164,peak_list_spectra_bin_166,peak_list_spectra_bin_167,peak_list_spectra_bin_168,peak_list_spectra_bin_169,peak_list_spectra_bin_170,peak_list_spectra_bin_171,peak_list_spectra_bin_172,peak_list_spectra_bin_173,peak_list_spectra_bin_174,peak_list_spectra_bin_175,peak_list_spectra_bin_176,peak_list_spectra_bin_177,peak_list_spectra_bin_178,peak_list_spectra_bin_180,peak_list_spectra_bin_184,peak_list_spectra_bin_185,peak_list_spectra_bin_186,peak_list_spectra_bin_188,peak_list_spectra_bin_189,peak_list_spectra_bin_190,peak_list_spectra_bin_191,peak_list_spectra_bin_192,peak_list_spectra_bin_194,peak_list_spectra_bin_195,peak_list_spectra_bin_196,peak_list_spectra_bin_197,peak_list_spectra_bin_198,peak_list_spectra_bin_199,peak_list_spectra_bin_200,peak_list_spectra_bin_201,peak_list_spectra_bin_203,peak_list_spectra_bin_204,peak_list_spectra_bin_205,peak_list_spectra_bin_206,peak_list_spectra_bin_207,peak_list_spectra_bin_208,peak_list_spectra_bin_209,peak_list_spectra_bin_210,peak_list_spectra_bin_211,peak_list_spectra_bin_214,peak_list_spectra_bin_215,peak_list_spectra_bin_216,peak_list_spectra_bin_217,peak_list_spectra_bin_218,peak_list_spectra_bin_219,peak_list_spectra_bin_220,peak_list_spectra_bin_221,peak_list_spectra_bin_222,peak_list_spectra_bin_224,peak_list_spectra_bin_225,peak_list_spectra_bin_226,peak_list_spectra_bin_227,peak_list_spectra_bin_228,peak_list_spectra_bin_229,peak_list_spectra_bin_230,peak_list_spectra_bin_231,peak_list_spectra_bin_232,peak_list_spectra_bin_233,peak_list_spectra_bin_235,peak_list_spectra_bin_237,peak_list_spectra_bin_238,peak_list_spectra_bin_239,peak_list_spectra_bin_240,peak_list_spectra_bin_241,peak_list_spectra_bin_242,peak_list_spectra_bin_243,peak_list_spectra_bin_244,peak_list_spectra_bin_245,peak_list_spectra_bin_246,peak_list_spectra_bin_249,peak_list_spectra_bin_250,peak_list_spectra_bin_252,peak_list_spectra_bin_253,peak_list_spectra_bin_256,peak_list_spectra_bin_257,peak_list_spectra_bin_258,peak_list_spectra_bin_260,peak_list_spectra_bin_262,peak_list_spectra_bin_263,peak_list_spectra_bin_264,peak_list_spectra_bin_265,peak_list_spectra_bin_266,peak_list_spectra_bin_267,peak_list_spectra_bin_268,peak_list_spectra_bin_269,peak_list_spectra_bin_271,peak_list_spectra_bin_272,peak_list_spectra_bin_273,peak_list_spectra_bin_274,peak_list_spectra_bin_275,peak_list_spectra_bin_276,peak_list_spectra_bin_277,peak_list_spectra_bin_278,peak_list_spectra_bin_279,peak_list_spectra_bin_280,peak_list_spectra_bin_281,peak_list_spectra_bin_282,peak_list_spectra_bin_283,peak_list_spectra_bin_284,peak_list_spectra_bin_285,peak_list_spectra_bin_286,peak_list_spectra_bin_287,peak_list_spectra_bin_288,peak_list_spectra_bin_289,peak_list_spectra_bin_290,peak_list_spectra_bin_291,peak_list_spectra_bin_292,peak_list_spectra_bin_293,peak_list_spectra_bin_294,peak_list_spectra_bin_296,peak_list_spectra_bin_297,peak_list_spectra_bin_298,peak_list_spectra_bin_299,peak_list_spectra_bin_300,peak_list_spectra_bin_302,peak_list_spectra_bin_303,peak_list_spectra_bin_304,peak_list_spectra_bin_305,peak_list_spectra_bin_306,peak_list_spectra_bin_307,peak_list_spectra_bin_308,peak_list_spectra_bin_309,peak_list_spectra_bin_310,peak_list_spectra_bin_311,peak_list_spectra_bin_312,peak_list_spectra_bin_313,peak_list_spectra_bin_314,peak_list_spectra_bin_315,peak_list_spectra_bin_316,peak_list_spectra_bin_317,peak_list_spectra_bin_318,peak_list_spectra_bin_319,peak_list_spectra_bin_320,peak_list_spectra_bin_321,peak_list_spectra_bin_323,peak_list_spectra_bin_324,peak_list_spectra_bin_325,peak_list_spectra_bin_326,peak_list_spectra_bin_327,peak_list_spectra_bin_328,peak_list_spectra_bin_329,peak_list_spectra_bin_330,peak_list_spectra_bin_331,peak_list_spectra_bin_332,peak_list_spectra_bin_333,peak_list_spectra_bin_334,peak_list_spectra_bin_335,peak_list_spectra_bin_336,peak_list_spectra_bin_337,peak_list_spectra_bin_338,peak_list_spectra_bin_340,peak_list_spectra_bin_341,peak_list_spectra_bin_342,peak_list_spectra_bin_343,peak_list_spectra_bin_344,peak_list_spectra_bin_345,peak_list_spectra_bin_346,peak_list_spectra_bin_347,peak_list_spectra_bin_348,peak_list_spectra_bin_349,peak_list_spectra_bin_350,peak_list_spectra_bin_351,peak_list_spectra_bin_352,peak_list_spectra_bin_353,peak_list_spectra_bin_354,peak_list_spectra_bin_357,peak_list_spectra_bin_358,peak_list_spectra_bin_359,peak_list_spectra_bin_360,peak_list_spectra_bin_361,peak_list_spectra_bin_363,peak_list_spectra_bin_366,peak_list_spectra_bin_367,peak_list_spectra_bin_368,peak_list_spectra_bin_369,peak_list_spectra_bin_370,peak_list_spectra_bin_371,peak_list_spectra_bin_372,peak_list_spectra_bin_373,peak_list_spectra_bin_374,peak_list_spectra_bin_376,peak_list_spectra_bin_377,peak_list_spectra_bin_378,peak_list_spectra_bin_379,peak_list_spectra_bin_380,peak_list_spectra_bin_381,peak_list_spectra_bin_382,peak_list_spectra_bin_383,peak_list_spectra_bin_384,peak_list_spectra_bin_385,peak_list_spectra_bin_386,peak_list_spectra_bin_387,peak_list_spectra_bin_388,peak_list_spectra_bin_389,peak_list_spectra_bin_390,peak_list_spectra_bin_391,peak_list_spectra_bin_392,peak_list_spectra_bin_393,peak_list_spectra_bin_396,peak_list_spectra_bin_397,peak_list_spectra_bin_398,peak_list_spectra_bin_399,peak_list_spectra_bin_400,peak_list_spectra_bin_401,peak_list_spectra_bin_402,peak_list_spectra_bin_403,peak_list_spectra_bin_404,peak_list_spectra_bin_405,peak_list_spectra_bin_406,peak_list_spectra_bin_407,peak_list_spectra_bin_408,peak_list_spectra_bin_409,peak_list_spectra_bin_410,peak_list_spectra_bin_412,peak_list_spectra_bin_414,peak_list_spectra_bin_415,peak_list_spectra_bin_416,peak_list_spectra_bin_417,peak_list_spectra_bin_418,peak_list_spectra_bin_419,peak_list_spectra_bin_420,peak_list_spectra_bin_421,peak_list_spectra_bin_422,peak_list_spectra_bin_423,peak_list_spectra_bin_424,peak_list_spectra_bin_425,peak_list_spectra_bin_426,peak_list_spectra_bin_427,peak_list_spectra_bin_430,peak_list_spectra_bin_431,peak_list_spectra_bin_432,peak_list_spectra_bin_435,peak_list_spectra_bin_436,peak_list_spectra_bin_437,peak_list_spectra_bin_438,peak_list_spectra_bin_439,peak_list_spectra_bin_440,peak_list_spectra_bin_441,peak_list_spectra_bin_442,peak_list_spectra_bin_443,peak_list_spectra_bin_444,peak_list_spectra_bin_445,peak_list_spectra_bin_446,peak_list_spectra_bin_449,peak_list_spectra_bin_450,peak_list_spectra_bin_451,peak_list_spectra_bin_452,peak_list_spectra_bin_453,peak_list_spectra_bin_454,peak_list_spectra_bin_455,peak_list_spectra_bin_456,peak_list_spectra_bin_457,peak_list_spectra_bin_458,peak_list_spectra_bin_459,peak_list_spectra_bin_460,peak_list_spectra_bin_461,peak_list_spectra_bin_462,peak_list_spectra_bin_463,peak_list_spectra_bin_464,peak_list_spectra_bin_466,peak_list_spectra_bin_467,peak_list_spectra_bin_468,peak_list_spectra_bin_470,peak_list_spectra_bin_471,peak_list_spectra_bin_472,peak_list_spectra_bin_474,peak_list_spectra_bin_475,peak_list_spectra_bin_476,peak_list_spectra_bin_477,peak_list_spectra_bin_478,peak_list_spectra_bin_480,peak_list_spectra_bin_481,peak_list_spectra_bin_482,peak_list_spectra_bin_483,peak_list_spectra_bin_484,peak_list_spectra_bin_485,peak_list_spectra_bin_486,peak_list_spectra_bin_487,peak_list_spectra_bin_488,peak_list_spectra_bin_490,peak_list_spectra_bin_491,peak_list_spectra_bin_492,peak_list_spectra_bin_494,peak_list_spectra_bin_495,peak_list_spectra_bin_496,peak_list_spectra_bin_497,peak_list_spectra_bin_499,peak_list_spectra_bin_502,peak_list_spectra_bin_503,peak_list_spectra_bin_504,peak_list_spectra_bin_505,peak_list_spectra_bin_506,peak_list_spectra_bin_507,peak_list_spectra_bin_508,peak_list_spectra_bin_510,peak_list_spectra_bin_511,peak_list_spectra_bin_512,peak_list_spectra_bin_513,peak_list_spectra_bin_514,peak_list_spectra_bin_515,peak_list_spectra_bin_516,peak_list_spectra_bin_517,peak_list_spectra_bin_518,peak_list_spectra_bin_519,peak_list_spectra_bin_521,peak_list_spectra_bin_522,peak_list_spectra_bin_523,peak_list_spectra_bin_524,peak_list_spectra_bin_525,peak_list_spectra_bin_528,peak_list_spectra_bin_529,peak_list_spectra_bin_531,peak_list_spectra_bin_532,peak_list_spectra_bin_533,peak_list_spectra_bin_534,peak_list_spectra_bin_535,peak_list_spectra_bin_536,peak_list_spectra_bin_537,peak_list_spectra_bin_538,peak_list_spectra_bin_539,peak_list_spectra_bin_540,peak_list_spectra_bin_541,peak_list_spectra_bin_542,peak_list_spectra_bin_544,peak_list_spectra_bin_545,peak_list_spectra_bin_546,peak_list_spectra_bin_547,peak_list_spectra_bin_548,peak_list_spectra_bin_549,peak_list_spectra_bin_550,peak_list_spectra_bin_552,peak_list_spectra_bin_553,peak_list_spectra_bin_554,peak_list_spectra_bin_556,peak_list_spectra_bin_557,peak_list_spectra_bin_558,peak_list_spectra_bin_559,peak_list_spectra_bin_561,peak_list_spectra_bin_562,peak_list_spectra_bin_563,peak_list_spectra_bin_564,peak_list_spectra_bin_566,peak_list_spectra_bin_567,peak_list_spectra_bin_568,peak_list_spectra_bin_570,peak_list_spectra_bin_573,peak_list_spectra_bin_574,peak_list_spectra_bin_577,peak_list_spectra_bin_578,peak_list_spectra_bin_579,peak_list_spectra_bin_580,peak_list_spectra_bin_581,peak_list_spectra_bin_582,peak_list_spectra_bin_583,peak_list_spectra_bin_584,peak_list_spectra_bin_585,peak_list_spectra_bin_586,peak_list_spectra_bin_587,peak_list_spectra_bin_588,peak_list_spectra_bin_590,peak_list_spectra_bin_591,peak_list_spectra_bin_592,peak_list_spectra_bin_593,peak_list_spectra_bin_594,peak_list_spectra_bin_595,peak_list_spectra_bin_596,peak_list_spectra_bin_598,peak_list_spectra_bin_599,peak_list_spectra_bin_602,peak_list_spectra_bin_603,peak_list_spectra_bin_605,peak_list_spectra_bin_606,peak_list_spectra_bin_607,peak_list_spectra_bin_608,peak_list_spectra_bin_609,peak_list_spectra_bin_610,peak_list_spectra_bin_611,peak_list_spectra_bin_613,peak_list_spectra_bin_614,peak_list_spectra_bin_615,peak_list_spectra_bin_617,peak_list_spectra_bin_618,peak_list_spectra_bin_619,peak_list_spectra_bin_620,peak_list_spectra_bin_621,peak_list_spectra_bin_622,peak_list_spectra_bin_623,peak_list_spectra_bin_624,peak_list_spectra_bin_625,peak_list_spectra_bin_627,peak_list_spectra_bin_628,peak_list_spectra_bin_629,peak_list_spectra_bin_630,peak_list_spectra_bin_631,peak_list_spectra_bin_632,peak_list_spectra_bin_633,peak_list_spectra_bin_635,peak_list_spectra_bin_636,peak_list_spectra_bin_637,peak_list_spectra_bin_639,peak_list_spectra_bin_641,peak_list_spectra_bin_642,peak_list_spectra_bin_643,peak_list_spectra_bin_644,peak_list_spectra_bin_645,peak_list_spectra_bin_646,peak_list_spectra_bin_647,peak_list_spectra_bin_648,peak_list_spectra_bin_649,peak_list_spectra_bin_650,peak_list_spectra_bin_651,peak_list_spectra_bin_652,peak_list_spectra_bin_653,peak_list_spectra_bin_655,peak_list_spectra_bin_656,peak_list_spectra_bin_657,peak_list_spectra_bin_658,peak_list_spectra_bin_659,peak_list_spectra_bin_660,peak_list_spectra_bin_661,peak_list_spectra_bin_662,peak_list_spectra_bin_663,peak_list_spectra_bin_665,peak_list_spectra_bin_666,peak_list_spectra_bin_667,peak_list_spectra_bin_669,peak_list_spectra_bin_670,peak_list_spectra_bin_671,peak_list_spectra_bin_672,peak_list_spectra_bin_673,peak_list_spectra_bin_674,peak_list_spectra_bin_675,peak_list_spectra_bin_677,peak_list_spectra_bin_678,peak_list_spectra_bin_679,peak_list_spectra_bin_681,peak_list_spectra_bin_682,peak_list_spectra_bin_684,peak_list_spectra_bin_685,peak_list_spectra_bin_686,peak_list_spectra_bin_688,peak_list_spectra_bin_689,peak_list_spectra_bin_690,peak_list_spectra_bin_692,peak_list_spectra_bin_693,peak_list_spectra_bin_694,peak_list_spectra_bin_695,peak_list_spectra_bin_697,peak_list_spectra_bin_698,peak_list_spectra_bin_699,peak_list_spectra_bin_701,peak_list_spectra_bin_703,peak_list_spectra_bin_704,peak_list_spectra_bin_705,peak_list_spectra_bin_706,peak_list_spectra_bin_707,peak_list_spectra_bin_708,peak_list_spectra_bin_709,peak_list_spectra_bin_710,peak_list_spectra_bin_711,peak_list_spectra_bin_712,peak_list_spectra_bin_713,peak_list_spectra_bin_714,peak_list_spectra_bin_715,peak_list_spectra_bin_716,peak_list_spectra_bin_717,peak_list_spectra_bin_719,peak_list_spectra_bin_720,peak_list_spectra_bin_722,peak_list_spectra_bin_723,peak_list_spectra_bin_724,peak_list_spectra_bin_726,peak_list_spectra_bin_727,peak_list_spectra_bin_729,peak_list_spectra_bin_731,peak_list_spectra_bin_732,peak_list_spectra_bin_733,peak_list_spectra_bin_734,peak_list_spectra_bin_735,peak_list_spectra_bin_736,peak_list_spectra_bin_738,peak_list_spectra_bin_739,peak_list_spectra_bin_740,peak_list_spectra_bin_741,peak_list_spectra_bin_742,peak_list_spectra_bin_743,peak_list_spectra_bin_744,peak_list_spectra_bin_745,peak_list_spectra_bin_746,peak_list_spectra_bin_747,peak_list_spectra_bin_748,peak_list_spectra_bin_749,peak_list_spectra_bin_750,peak_list_spectra_bin_751,peak_list_spectra_bin_752,peak_list_spectra_bin_753,peak_list_spectra_bin_754,peak_list_spectra_bin_755,peak_list_spectra_bin_756,peak_list_spectra_bin_757,peak_list_spectra_bin_758,peak_list_spectra_bin_759,peak_list_spectra_bin_761,peak_list_spectra_bin_763,peak_list_spectra_bin_765,peak_list_spectra_bin_767,peak_list_spectra_bin_768,peak_list_spectra_bin_769,peak_list_spectra_bin_771,peak_list_spectra_bin_772,peak_list_spectra_bin_773,peak_list_spectra_bin_774,peak_list_spectra_bin_775,peak_list_spectra_bin_776,peak_list_spectra_bin_777,peak_list_spectra_bin_778,peak_list_spectra_bin_779,peak_list_spectra_bin_780,peak_list_spectra_bin_781,peak_list_spectra_bin_783,peak_list_spectra_bin_784,peak_list_spectra_bin_785,peak_list_spectra_bin_787,peak_list_spectra_bin_788,peak_list_spectra_bin_789,peak_list_spectra_bin_790,peak_list_spectra_bin_791,peak_list_spectra_bin_792,peak_list_spectra_bin_793,peak_list_spectra_bin_794,peak_list_spectra_bin_795,peak_list_spectra_bin_796,peak_list_spectra_bin_797,peak_list_spectra_bin_799,peak_list_spectra_bin_800,peak_list_spectra_bin_802,peak_list_spectra_bin_803,peak_list_spectra_bin_804,peak_list_spectra_bin_805,peak_list_spectra_bin_806,peak_list_spectra_bin_807,peak_list_spectra_bin_808,peak_list_spectra_bin_809,peak_list_spectra_bin_810,peak_list_spectra_bin_811,peak_list_spectra_bin_812,peak_list_spectra_bin_814,peak_list_spectra_bin_815,peak_list_spectra_bin_817,peak_list_spectra_bin_818,peak_list_spectra_bin_819,peak_list_spectra_bin_820,peak_list_spectra_bin_821,peak_list_spectra_bin_822,peak_list_spectra_bin_823,peak_list_spectra_bin_824,peak_list_spectra_bin_825,peak_list_spectra_bin_826,peak_list_spectra_bin_827,peak_list_spectra_bin_828,peak_list_spectra_bin_829,peak_list_spectra_bin_830,peak_list_spectra_bin_831,peak_list_spectra_bin_832,peak_list_spectra_bin_833,peak_list_spectra_bin_835,peak_list_spectra_bin_836,peak_list_spectra_bin_837,peak_list_spectra_bin_838,peak_list_spectra_bin_839,peak_list_spectra_bin_841,peak_list_spectra_bin_842,peak_list_spectra_bin_843,peak_list_spectra_bin_844,peak_list_spectra_bin_846,peak_list_spectra_bin_847,peak_list_spectra_bin_848,peak_list_spectra_bin_849,peak_list_spectra_bin_852,peak_list_spectra_bin_853,peak_list_spectra_bin_855,peak_list_spectra_bin_856,peak_list_spectra_bin_858,peak_list_spectra_bin_859,peak_list_spectra_bin_860,peak_list_spectra_bin_861,peak_list_spectra_bin_862,peak_list_spectra_bin_863,peak_list_spectra_bin_864,peak_list_spectra_bin_865,peak_list_spectra_bin_867,peak_list_spectra_bin_868,peak_list_spectra_bin_869,peak_list_spectra_bin_870,peak_list_spectra_bin_871,peak_list_spectra_bin_873,peak_list_spectra_bin_874,peak_list_spectra_bin_875,peak_list_spectra_bin_876,peak_list_spectra_bin_877,peak_list_spectra_bin_878,peak_list_spectra_bin_879,peak_list_spectra_bin_881,peak_list_spectra_bin_883,peak_list_spectra_bin_884,peak_list_spectra_bin_885,peak_list_spectra_bin_886,peak_list_spectra_bin_887,peak_list_spectra_bin_888,peak_list_spectra_bin_889,peak_list_spectra_bin_890,peak_list_spectra_bin_891,peak_list_spectra_bin_892,peak_list_spectra_bin_893,peak_list_spectra_bin_894,peak_list_spectra_bin_896,peak_list_spectra_bin_897,peak_list_spectra_bin_901,peak_list_spectra_bin_902,peak_list_spectra_bin_903,peak_list_spectra_bin_904,peak_list_spectra_bin_905,peak_list_spectra_bin_906,peak_list_spectra_bin_908,peak_list_spectra_bin_909,peak_list_spectra_bin_910,peak_list_spectra_bin_911,peak_list_spectra_bin_912,peak_list_spectra_bin_913,peak_list_spectra_bin_914,peak_list_spectra_bin_916,peak_list_spectra_bin_917,peak_list_spectra_bin_918,peak_list_spectra_bin_919,peak_list_spectra_bin_920,peak_list_spectra_bin_921,p

In [6]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Species,category,0.0,0.0,20.0,"Escherichia coli, Enterobacter cloacae, Haemophilus influenzae, Shigella flexneri, Listeria monocytogenes, Shigella sonnei, Listeria ivanovii, Enterobacter asburiae, Citrobacter freundii, Yersinia enterocolitica"
1,Strain,category,0.0,0.0,213.0,"7, 66, 126, 188, 49, 211, 198, 59, 56, 18"
2,peak_list_spectra_bin_3,float64,0.0,0.0,87.0,"0.0, 133483.9219, 184903.0469, 1419734.5, 27943.2695, 169226.375, 9010.8008, 11229.2373, 4190.5786, 10624.4219"
3,peak_list_spectra_bin_4,float64,0.0,0.0,8.0,"0.0, 3284.9226, 2330278.25, 72315.8906, 6252400.0, 21472.7812, 58306.8242, 15470.124"
4,peak_list_spectra_bin_5,float64,0.0,0.0,5.0,"0.0, 495329.375, 1260594.75, 312997.5, 825143.0625"
5,peak_list_spectra_bin_7,float64,0.0,0.0,93.0,"0.0, 44431.9219, 4701.7124, 96809.9453, 97883.0859, 205319.7656, 25435.4902, 22785.2656, 34239.082, 38974.2656"
6,peak_list_spectra_bin_8,float64,0.0,0.0,45.0,"0.0, 31592.1621, 4363.2222, 5103.458, 14443.8369, 118729.9453, 506043.9062, 147971.1406, 5474.0811, 55808.3203"
7,peak_list_spectra_bin_9,float64,0.0,0.0,52.0,"0.0, 36870.0352, 408579.4375, 413691.4062, 130932.1641, 29301.8965, 4265.8784, 519936.4375, 67924.7656, 36723.4258"
8,peak_list_spectra_bin_10,float64,0.0,0.0,25.0,"0.0, 67041.6016, 19550.2383, 219985.3906, 56969.9492, 259344.4375, 16830.2324, 32809.9336, 75805.3828, 7972.9575"
9,peak_list_spectra_bin_11,float64,0.0,0.0,55.0,"0.0, 299438.5, 651770.625, 1003640.75, 14568.3535, 125789.6328, 713392.375, 482951.2188, 695641.25, 44889.8516"
10,peak_list_spectra_bin_12,float64,0.0,0.0,11.0,"0.0, 138632.3281, 15370.5293, 10097.707, 70723.4219, 76601.3594, 6079.7173, 36117.1562, 28950.6016, 154043.4375"
11,peak_list_spectra_bin_13,float64,0.0,0.0,130.0,"0.0, 155102.0312, 136896.0625, 170977.7656, 971103.3125, 19741.2266, 10012.916, 503572.125, 94176.6406, 266522.75"
12,peak_list_spectra_bin_14,float64,0.0,0.0,12.0,"0.0, 23400.166, 45353.3398, 61702.3633, 11557.8184, 219462.2812, 157533.3281, 34151.4883, 79644.9453, 275457.4375"
13,peak_list_spectra_bin_15,float64,0.0,0.0,60.0,"0.0, 43587.9805, 15194.748, 155158.0938, 100177.2578, 905.5087, 19762.7793, 149314.6094, 1617.1168, 450425.5"
14,peak_list_spectra_bin_16,float64,0.0,0.0,134.0,"0.0, 19599.9082, 6080748.0, 75301.3672, 450886.5312, 88255.7812, 220267.875, 88784.7031, 36183.9375, 251515.1875"
15,peak_list_spectra_bin_17,float64,0.0,0.0,44.0,"0.0, 573453.375, 680321.4375, 1094372.875, 885850.5, 340458.875, 90944.2891, 10912.9453, 155343.7031, 587676.375"
16,peak_list_spectra_bin_18,float64,0.0,0.0,41.0,"0.0, 59089.5352, 23636.6094, 227362.0312, 270076.625, 9378.2031, 24779.7559, 4788.7212, 256803.3281, 16590.3516"
17,peak_list_spectra_bin_19,float64,0.0,0.0,70.0,"0.0, 49956.2188, 7815.2598, 31735.1152, 1767.9908, 14094.0869, 3278.9995, 48771.1719, 117589.8984, 13878.2266"
18,peak_list_spectra_bin_20,float64,0.0,0.0,3.0,"0.0, 20131.4336, 195262.8281"
19,peak_list_spectra_bin_21,float64,0.0,0.0,19.0,"0.0, 100276.7656, 2997314.0, 85235.0156, 184789.875, 994229.125, 527022.875, 414626.0625, 93963.4453, 111901.6328"
20,peak_list_spectra_bin_22,float64,0.0,0.0,168.0,"0.0, 722855.5625, 214672.5312, 8442023.0, 1261040.125, 385321.4375, 1767139.5, 843396.1875, 595434.125, 155751.9531"
21,peak_list_spectra_bin_23,float64,0.0,0.0,36.0,"0.0, 87006.4453, 749.1118, 547379.8125, 729516.25, 5164.8506, 18586.7988, 10680263.0, 13441607.0, 18882.1738"
22,peak_list_spectra_bin_24,float64,0.0,0.0,104.0,"0.0, 1269657.75, 7348.4023, 1204.3353, 52992.8594, 222832.5156, 98572.875, 54952.8672, 68340.7188, 585296.4375"
23,peak_list_spectra_bin_25,float64,0.0,0.0,72.0,"0.0, 125450.5625, 162647.875, 22212.3145, 5085.8828, 1382.017, 9072.7676, 16324.9248, 195443.4219, 451641.5312"
24,peak_list_spectra_bin_26,float64,0.0,0.0,153.0,"0.0, 369554.625, 231711.0312, 44780.8789, 450803.4688, 72307.6797, 55171.2773, 68275.6016, 17820.2422, 8631.1084"
25,peak_list_spectra_bin_28,float64,0.0,0.0,2.0,"0.0, 44348.1953"
26,peak_list_spectra_bin_29,float64,0.0,0.0,88.0,"0.0, 27013.2676, 217176.5781, 238903.9062, 3819.8889, 17727.127, 58874.5312, 18987.2598, 8763.9727, 869158.8125"
27,peak_list_spectra_bin_30,float64,0.0,0.0,15.0,"0.0, 29023.416, 102594.5312, 162849.8125, 24045.4609, 120366.4219, 71629.875, 123011.4609, 32803.082, 47671.9609"
28,peak_list_spectra_bin_31,float64,0.0,0.0,89.0,"0.0, 2528850.5, 148533.2812, 3973007.0, 896994.0625, 522055.2812, 307817.2812, 1031808.0625, 411503.8125, 46200.3047"
29,peak_list_spectra_bin_32,float64,0.0,0.0,39.0,"0.0, 18477.502, 12263.9062, 4855.8862, 59871.2031, 1793.6462, 16724.5742, 231077.0156, 18439.4609, 49083.6445"
30,peak_list_spectra_bin_34,float64,0.0,0.0,100.0,"0.0, 11751.9248, 14830.8574, 28258.6777, 1895681.875, 4858.2515, 153368.4062, 31279.8633, 31239.4629, 514840.9688"
31,peak_list_spectra_bin_35,float64,0.0,0.0,84.0,"0.0, 734477.125, 20407.4199, 42047.2031, 396560.5312, 70579.4844, 17458.9414, 3534.7034, 64387.5352, 16820.5273"
32,peak_list_spectra_bin_36,float64,0.0,0.0,80.0,"0.0, 49720.6602, 2094.4807, 1046296.125, 11085.9287, 4426.5552, 55872.2695, 71588.5625, 2012.0703, 1270.9797"
33,peak_list_spectra_bin_37,float64,0.0,0.0,37.0,"0.0, 104884.3047, 24013.6758, 74424.8359, 67380.1406, 124426.9688, 3373.1526, 3898.3501, 16932.8203, 71644.6406"
34,peak_list_spectra_bin_39,float64,0.0,0.0,93.0,"0.0, 21270.6367, 12797.3057, 442554.7812, 545062.125, 25023.7539, 4099.0791, 13068.1133, 3470079.5, 2641146.25"
35,peak_list_spectra_bin_40,float64,0.0,0.0,52.0,"0.0, 14996.7031, 295777.2812, 19294.4219, 62537.3906, 69475.2266, 120585.9062, 3388.2734, 35852.1484, 35072.5742"
36,peak_list_spectra_bin_41,float64,0.0,0.0,35.0,"0.0, 21331.6133, 142201.7344, 219974.3594, 46844.0391, 182591.6406, 243287.3438, 10853.9863, 6005.9653, 20261.1543"
37,peak_list_spectra_bin_42,float64,0.0,0.0,57.0,"0.0, 64794.8477, 526421.8125, 150366.8438, 25173.541, 15390.8604, 1466208.875, 46333.3398, 10567.0352, 21122.791"
38,peak_list_spectra_bin_43,float64,0.0,0.0,96.0,"0.0, 66629.0781, 81382.7109, 278187.7188, 1017872.4375, 744314.125, 344594.0312, 135784.1406, 5281117.5, 5250986.5"
39,peak_list_spectra_bin_44,float64,0.0,0.0,28.0,"0.0, 11737.5684, 43416.7969, 4576.2456, 123934.875, 9647.332, 15770.6309, 36258.4648, 26636.0078, 35798.4609"
40,peak_list_spectra_bin_45,float64,0.0,0.0,12.0,"0.0, 4605.7617, 4560290.0, 2316160.75, 27517.6973, 9967.3242, 32401.5566, 10419.7217, 442855.625, 59716.5703"
41,peak_list_spectra_bin_46,float64,0.0,0.0,31.0,"0.0, 131487.7344, 50677.6719, 9981.6338, 772338.6875, 18342.6406, 5150.9194, 262137.5, 120491.3203, 39916.8555"
42,peak_list_spectra_bin_47,float64,0.0,0.0,32.0,"0.0, 192331.5625, 157947.4531, 53574.2812, 1381.0509, 4490.5972, 1733208.875, 1676522.375, 57436.5781, 13026.8936"
43,peak_list_spectra_bin_48,float64,0.0,0.0,42.0,"0.0, 855587.9375, 2369082.25, 8258.041, 25776.9199, 105611.9688, 497063.5312, 3444515.0, 766716.1875, 14073.5938"
44,peak_list_spectra_bin_49,float64,0.0,0.0,79.0,"0.0, 12840.2588, 50153.4375, 302854.4062, 96306.3828, 116418.3516, 397602.9375, 97440.375, 286290.2188, 467812.0625"
45,peak_list_spectra_bin_50,float64,0.0,0.0,50.0,"0.0, 7496672.5, 21260.6621, 322336.0, 878071.9375, 322015.75, 13036.0625, 336367.2188, 5254821.5, 21255.1387"
46,peak_list_spectra_bin_52,float64,0.0,0.0,25.0,"0.0, 17702.209, 51003.875, 47443.1875, 1037665.0625, 1907.7366, 403513.75, 8720.2656, 99733.4531, 23468.9902"
47,peak_list_spectra_bin_53,float64,0.0,0.0,34.0,"0.0, 10102.4277, 4285.5425, 1673846.0, 3733.9841, 692754.4375, 3888917.25, 1840397.125, 1878473.125, 28410.416"
48,peak_list_spectra_bin_55,float64,0.0,0.0,53.0,"0.0, 925.041, 6759.9731, 35430.1172, 3175.8108, 75705.7422, 27159.957, 184744.3281, 1058143.625, 193329.6875"
49,peak_list_spectra_bin_56,float64,0.0,0.0,33.0,"0.0, 1640292.5, 735.6381, 510991.375, 2951.2542, 6593.4961, 103954.0391, 42464.9297, 182967.1094, 5051.6978"
50,peak_list_spectra_bin_57,float64,0.0,0.0,82.0,"0.0, 2532.4241, 96954.9766, 20586.666, 191950.875, 34160.4805, 12578.3555, 2363.5774, 2218.8533, 2568.563"
51,peak_list_spectra_bin_58,float64,0.0,0.0,60.0,"0.0, 105916.9922, 335396.5938, 867105.0, 1078140.625, 7245400.0, 6153449.0, 41965.5938, 1394.8209, 1204845.25"
52,peak_list_spectra_bin_59,float64,0.0,0.0,101.0,"0.0, 1300749.875, 431029.6875, 69518.8359, 4266507.0, 942399.9375, 208117.8906, 306287.8125, 504762.7812, 4085203.75"
53,peak_list_spectra_bin_60,float64,0.0,0.0,79.0,"0.0, 239096.4531, 96182.4453, 3473.0542, 191088.7188, 68716.7422, 271.8788, 142854.6406, 41937.2461, 108655.5078"
54,peak_list_spectra_bin_61,float64,0.0,0.0,79.0,"0.0, 1357163.25, 188042.5781, 737610.0, 57882.7617, 1469990.375, 618031.0, 4447176.0, 4166.231, 88170.9922"
55,peak_list_spectra_bin_62,float64,0.0,0.0,63.0,"0.0, 10691.1172, 792149.5625, 77091.625, 134188.7812, 22569.4316, 11589.332, 450319.2188, 9311.7373, 61608.5469"
56,peak_list_spectra_bin_64,float64,0.0,0.0,106.0,"0.0, 6900.145, 27507.9961, 921096.1875, 1433495.0, 187459.9844, 69577.8516, 56031.4414, 60724.3359, 174962.9531"
57,peak_list_spectra_bin_66,float64,0.0,0.0,2.0,"0.0, 144709.8438"
58,peak_list_spectra_bin_67,float64,0.0,0.0,3.0,"0.0, 74636.3828, 5597.603"
59,peak_list_spectra_bin_68,float64,0.0,0.0,53.0,"0.0, 14794.2793, 9964.542, 11944.5244, 115760.0469, 22711.5137, 9554.1484, 17475.2598, 2052068.0, 2415147.75"
60,peak_list_spectra_bin_69,float64,0.0,0.0,63.0,"0.0, 21643.7695, 61333.6836, 471525.125, 15562.0352, 3871.1216, 12871.084, 8057.0972, 281106.0625, 49422.1367"
61,peak_list_spectra_bin_70,float64,0.0,0.0,69.0,"0.0, 472710.625, 2761023.5, 5620.9985, 15547727.0, 11416139.0, 4999112.0, 3050930.0, 9464557.0, 12399384.0"
62,peak_list_spectra_bin_72,float64,0.0,0.0,55.0,"0.0, 1234744.625, 593569.0625, 206528.0, 2112222.75, 3702.6362, 113975.2578, 9653.6982, 44322.9258, 32552.2363"
63,peak_list_spectra_bin_73,float64,0.0,0.0,49.0,"0.0, 44077.625, 6251.4917, 16726.2891, 174687.2656, 101746.2266, 29024.1133, 12184.5098, 36177.6875, 391539.7812"
64,peak_list_spectra_bin_74,float64,0.0,0.0,18.0,"0.0, 11441.9951, 193694.9062, 2397505.0, 47246.4336, 41569.25, 921853.3125, 49802.8477, 382957.0938, 114757.5156"
65,peak_list_spectra_bin_76,float64,0.0,0.0,75.0,"0.0, 13408.6562, 421945.2812, 165666.3125, 361067.5312, 4199.0718, 6280.9194, 4190.6958, 311011.9375, 2043.6072"
66,peak_list_spectra_bin_77,float64,0.0,0.0,93.0,"0.0, 64195.6367, 387426.0312, 109317.7812, 63598.6328, 31923.7969, 11825975.0, 2418018.75, 2916986.75, 391577.3438"
67,peak_list_spectra_bin_78,float64,0.0,0.0,74.0,"0.0, 1805796.125, 302125.1875, 2869553.75, 1288972.625, 9962279.0, 12580592.0, 6202360.0, 311534.375, 504650.3125"
68,peak_list_spectra_bin_79,float64,0.0,0.0,60.0,"0.0, 104292.0547, 37381.2188, 33901.8828, 1564083.75, 538249.8125, 45197.9766, 253915.25, 2407271.0, 664601.875"
69,peak_list_spectra_bin_80,float64,0.0,0.0,37.0,"0.0, 477388.8125, 630677.6875, 13200.0146, 3483.5403, 52573.2891, 421192.0312, 21092.2578, 49271.5234, 43848.8867"
70,peak_list_spectra_bin_81,float64,0.0,0.0,100.0,"0.0, 2754679.0, 32768.1406, 121979.2266, 27414.7012, 157308.9219, 1200567.75, 866931.9375, 6663916.5, 13640.1416"
71,peak_list_spectra_bin_83,float64,0.0,0.0,36.0,"0.0, 1537.0521, 206011.9219, 1958.563, 27417.1621, 17426.2344, 82092.2578, 11646.1738, 82915.8906, 16554.2812"
72,peak_list_spectra_bin_85,float64,0.0,0.0,119.0,"0.0, 13063296.0, 3044425.75, 677658.375, 20734108.0, 1606777.875, 392120.5312, 1022031.3125, 671166.6875, 786689.6875"
73,peak_list_spectra_bin_86,float64,0.0,0.0,58.0,"0.0, 169243.0469, 233232.5938, 123706.6562, 25288.2109, 244013.875, 21830.7676, 8639.2207, 1953.1489, 28683.6719"
74,peak_list_spectra_bin_87,float64,0.0,0.0,112.0,"0.0, 17199.5469, 530706.5625, 372053.5625, 194641.125, 1947985.125, 273509.125, 417400.7188, 182549.1406, 1611170.25"
75,peak_list_spectra_bin_88,float64,0.0,0.0,22.0,"0.0, 21445.1504, 48144.2539, 7790.0752, 1948.5192, 5793.0024, 3485.1741, 604855.9375, 1135287.75, 376186.5625"
76,peak_list_spectra_bin_89,float64,0.0,0.0,57.0,"0.0, 943275.875, 726788.6875, 88387.75, 91311.2969, 69659.9375, 13619.5615, 14240.7266, 7907.2026, 14276.7842"
77,peak_list_spectra_bin_90,float64,0.0,0.0,30.0,"0.0, 81521.9844, 59095.7852, 16771.3574, 37239.6094, 4729.5444, 36916.668, 11776.707, 108920.8594, 162157.5156"
78,peak_list_spectra_bin_91,float64,0.0,0.0,59.0,"0.0, 331317.0, 12252.1865, 12686.6895, 27831.2227, 76806.1328, 53412.1406, 19623.8281, 50668.957, 414037.2188"
79,peak_list_spectra_bin_92,float64,0.0,0.0,63.0,"0.0, 152163.7969, 267799.2812, 349131.0, 847466.375, 17936.9766, 564591.8125, 1164.1884, 53882.1836, 76738.0547"
80,peak_list_spectra_bin_93,float64,0.0,0.0,5.0,"0.0, 107364.5234, 61181.7188, 8577.2939, 19750.1055"
81,peak_list_spectra_bin_95,float64,0.0,0.0,6.0,"0.0, 108178.4141, 235456.8594, 33555.2578, 68475.4453, 19201.5664"
82,peak_list_spectra_bin_97,float64,0.0,0.0,44.0,"0.0, 63252.6328, 242003.25, 77974.7969, 82816.7266, 116388.8594, 264688.9375, 394243.7188, 20609.6875, 212862.4688"
83,peak_list_spectra_bin_98,float64,0.0,0.0,19.0,"0.0, 2748.8931, 296.7197, 40379.4492, 209739.3906, 25412.4199, 219293.1406, 121447.2656, 1712800.25, 666577.9375"
84,peak_list_spectra_bin_99,float64,0.0,0.0,68.0,"0.0, 77897.9844, 33881.0391, 23216.0977, 17267.252, 203936.2812, 111283.5703, 20465.7402, 12084.9531, 34079.4375"
85,peak_list_spectra_bin_100,float64,0.0,0.0,89.0,"0.0, 30592.8867, 213409.5, 8962.4561, 13491.7666, 70934.7969, 71518.6016, 12751.6064, 6083.4556, 264559.8438"
86,peak_list_spectra_bin_101,float64,0.0,0.0,2.0,"0.0, 49260.2578"
87,peak_list_spectra_bin_103,float64,0.0,0.0,88.0,"0.0, 15644.2891, 741962.9375, 138136.8125, 174165.3594, 53593.5977, 96710.1328, 66267.0, 1619.1323, 161697.4688"
88,peak_list_spectra_bin_105,float64,0.0,0.0,25.0,"0.0, 548107.5, 8216.8604, 28754.8496, 5270.6426, 112702.7031, 12211.1328, 4965.2607, 659232.0625, 621508.3125"
89,peak_list_spectra_bin_106,float64,0.0,0.0,17.0,"0.0, 44066.3789, 912.702, 21606.4141, 9503.458, 23432.8965, 20922.9395, 28350.8066, 76825.1641, 507025.3125"
90,peak_list_spectra_bin_107,float64,0.0,0.0,12.0,"0.0, 19972.8652, 85333.375, 125415.4375, 91412.4766, 4864.6626, 59937.5977, 8415.0596, 38153.1758, 406227.2188"
91,peak_list_spectra_bin_108,float64,0.0,0.0,8.0,"0.0, 11800.0977, 11228219.0, 4497752.0, 1741056.375, 12690171.0, 11828338.0, 19120.4102"
92,peak_list_spectra_bin_109,float64,0.0,0.0,4.0,"0.0, 29360.707, 8464180.0, 486647.0938"
93,peak_list_spectra_bin_111,float64,0.0,0.0,34.0,"0.0, 25114.1211, 972.7905, 160482.4688, 5531.897, 6141.9976, 138433.0156, 203449.125, 25572.4922, 86688.5078"
94,peak_list_spectra_bin_112,float64,0.0,0.0,72.0,"0.0, 15325.7393, 49314.9453, 12011.6104, 103501.6484, 85925.1484, 306570.2812, 56361.0703, 1000.1752, 9322.4629"
95,peak_list_spectra_bin_113,float64,0.0,0.0,9.0,"0.0, 134061.5469, 23699.3867, 54663.7695, 7544.5366, 423366.9375, 300936.75, 55752.5586, 59759.7266"
96,peak_list_spectra_bin_115,float64,0.0,0.0,176.0,"0.0, 257079.6562, 7686623.5, 73881.9531, 1344494.0, 37478.6836, 3618490.0, 5816875.5, 767989.625, 9109.0293"
97,peak_list_spectra_bin_116,float64,0.0,0.0,26.0,"0.0, 27002.8359, 46705.3867, 246862.0312, 245272.1094, 29460.3828, 4535902.5, 43474.4023, 31013.2695, 334559.4375"
98,peak_list_spectra_bin_117,float64,0.0,0.0,29.0,"0.0, 14282.1807, 9414.6533, 8242.2383, 6008.7788, 8566.3828, 8360.5635, 3607.1919, 54559.9062, 11808.5938"
99,peak_list_spectra_bin_118,float64,0.0,0.0,53.0,"0.0, 30632.9336, 123722.1719, 73579.7109, 11781.0391, 2819.6245, 6631.625, 8827.1709, 140010.1719, 90008.3906"
100,peak_list_spectra_bin_119,float64,0.0,0.0,5.0,"0.0, 8339.5088, 2569.2246, 15008.7871, 4631.3672"
101,peak_list_spectra_bin_120,float64,0.0,0.0,33.0,"0.0, 60091.1367, 504464.0938, 1654482.375, 135759.2344, 1777064.875, 2687602.0, 69219.4062, 25485.5293, 331244.7188"
102,peak_list_spectra_bin_121,float64,0.0,0.0,112.0,"0.0, 1597174.25, 80835.0938, 328822.9062, 967587.0, 722142.4375, 8087205.5, 34446.7578, 68273.1562, 21127.0449"
103,peak_list_spectra_bin_122,float64,0.0,0.0,41.0,"0.0, 73694.5, 31501.1562, 13645.7578, 25274.0586, 1382.3263, 2899738.75, 10269.2666, 15657.5811, 41622.1953"
104,peak_list_spectra_bin_123,float64,0.0,0.0,2.0,"0.0, 369486.375"
105,peak_list_spectra_bin_124,float64,0.0,0.0,23.0,"0.0, 208424.5625, 5807.0454, 2597.3262, 489653.0938, 20549.6465, 242901.2344, 106322.0625, 214607.4375, 53592.7031"
106,peak_list_spectra_bin_125,float64,0.0,0.0,56.0,"0.0, 52069.9961, 101430.6016, 12873.8828, 4004.1453, 442191.0625, 115035.0547, 8658.8545, 255840.125, 120702.8672"
107,peak_list_spectra_bin_127,float64,0.0,0.0,53.0,"0.0, 49379.3672, 22426.8789, 3494.4644, 57710.8984, 11272.1592, 133234.9375, 16400.9629, 81616.2266, 42295.1719"
108,peak_list_spectra_bin_128,float64,0.0,0.0,184.0,"0.0, 7270.5718, 3685.6172, 6907148.0, 11060910.0, 4623593.0, 5134535.5, 1159704.625, 8027712.5, 4623115.5"
109,peak_list_spectra_bin_130,float64,0.0,0.0,69.0,"0.0, 35838.125, 2720.4758, 51772.4531, 12929.4795, 7633.3184, 195964.2812, 254610.5625, 470129.4688, 49256.4805"
110,peak_list_spectra_bin_131,float64,0.0,0.0,88.0,"0.0, 87490.3984, 51434.8555, 62029.7773, 26385.0156, 1761.7587, 149412.9844, 789352.6875, 1684.9474, 33100.1719"
111,peak_list_spectra_bin_132,float64,0.0,0.0,96.0,"0.0, 85324.2891, 2334039.25, 560417.0, 20675.8594, 250663.6875, 223312.4375, 139496.2031, 467684.4375, 187325.9062"
112,peak_list_spectra_bin_133,float64,0.0,0.0,14.0,"0.0, 1196588.875, 801198.625, 49712.8398, 36396.6836, 512780.7812, 327902.9375, 450738.625, 162756.0781, 47486.2266"
113,peak_list_spectra_bin_134,float64,0.0,0.0,3.0,"0.0, 16819.5508, 113947.0156"
114,peak_list_spectra_bin_135,float64,0.0,0.0,68.0,"0.0, 13407.4951, 1691.0315, 200531.3281, 17778.3828, 84228.4922, 331361.1562, 6122.1528, 83640.5312, 64011.0312"
115,peak_list_spectra_bin_137,float64,0.0,0.0,22.0,"0.0, 180024.1094, 311908.8125, 11983.4971, 119.28, 536742.8125, 23241.9512, 29549.959, 253003.0, 58861.2695"
116,peak_list_spectra_bin_138,float64,0.0,0.0,92.0,"0.0, 388183.3125, 251894.5625, 31282.5625, 966876.125, 2309166.25, 206938.0938, 18892552.0, 2201659.25, 647306.9375"
117,peak_list_spectra_bin_139,float64,0.0,0.0,38.0,"0.0, 11943.54, 16167.9453, 3549.6226, 25907.4043, 28643.0566, 4303.6206, 149079.8906, 6012.2134, 11932.667"
118,peak_list_spectra_bin_140,float64,0.0,0.0,49.0,"0.0, 17713.3125, 23646.8652, 491110.0, 113844.4219, 1696.7742, 47997.6914, 105091.4844, 1284797.375, 6617.875"
119,peak_list_spectra_bin_141,float64,0.0,0.0,16.0,"0.0, 130552.6719, 239444.6094, 1774309.875, 1950619.875, 2650421.25, 159020.7812, 2382985.0, 2652020.75, 6841020.0"
120,peak_list_spectra_bin_143,float64,0.0,0.0,77.0,"0.0, 9794.623, 783908.3125, 13556.5498, 5846.0469, 119919.5234, 161318.2188, 87313.6484, 23266.3945, 16864.0879"
121,peak_list_spectra_bin_145,float64,0.0,0.0,4.0,"0.0, 17326.2324, 23357.6211, 131906.6094"
122,peak_list_spectra_bin_147,float64,0.0,0.0,54.0,"0.0, 49545.3789, 23048.502, 6311.2949, 34633.8125, 300830.75, 21313.2539, 107275.3906, 302391.5938, 39018.5898"
123,peak_list_spectra_bin_149,float64,0.0,0.0,2.0,"0.0, 4372.3853"
124,peak_list_spectra_bin_150,float64,0.0,0.0,104.0,"0.0, 2271.4851, 104997.0312, 1298991.25, 96334.1484, 122548.9688, 459731.9375, 94855.0547, 4326.3086, 12081.8037"
125,peak_list_spectra_bin_151,float64,0.0,0.0,9.0,"0.0, 6766.728, 36005.0938, 58676.3125, 50151.4258, 8829.1562, 12941.8857, 13259.3184, 3532.2983"
126,peak_list_spectra_bin_152,float64,0.0,0.0,98.0,"0.0, 715177.25, 147246.8281, 54020.5859, 217120.7969, 36977.5898, 153657.0938, 33255.6328, 6253.3696, 27666.209"
127,peak_list_spectra_bin_153,float64,0.0,0.0,92.0,"0.0, 1985672.5, 641377.3125, 686458.75, 186817.5625, 275413.4062, 37584.5664, 503268.25, 18294.9824, 6030.292"
128,peak_list_spectra_bin_154,float64,0.0,0.0,40.0,"0.0, 23557.5859, 271450.3125, 58803.0859, 152823.75, 50027.2891, 123066.875, 2619515.75, 2464711.0, 46402.4766"

In [7]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
peak_list_spectra_bin_3,571.0,7.139591e+04,4.502179e+05,0.0,7.028834e+06
peak_list_spectra_bin_4,571.0,1.533017e+04,2.790895e+05,0.0,6.252400e+06
peak_list_spectra_bin_5,571.0,5.068415e+03,6.752011e+04,0.0,1.260595e+06
peak_list_spectra_bin_7,571.0,2.819248e+04,1.462817e+05,0.0,2.160791e+06
peak_list_spectra_bin_8,571.0,1.016611e+04,8.954112e+04,0.0,1.961872e+06
peak_list_spectra_bin_9,571.0,8.026213e+04,5.129584e+05,0.0,5.417460e+06
peak_list_spectra_bin_10,571.0,8.890188e+03,6.750842e+04,0.0,9.331868e+05
peak_list_spectra_bin_11,571.0,5.524693e+04,2.713508e+05,0.0,3.492954e+06
peak_list_spectra_bin_12,571.0,1.413608e+03,1.500842e+04,0.0,2.705538e+05
peak_list_spectra_bin_13,571.0,4.031135e+04,1.294317e+05,0.0,1.002091e+06
peak_list_spectra_bin_14,571.0,1.865831e+03,1.766638e+04,0.0,2.754574e+05
peak_list_spectra_bin_15,571.0,5.153679e+04,4.192762e+05,0.0,8.542998e+06
peak_list_spectra_bin_16,571.0,1.539336e+05,6.374991e+05,0.0,8.524062e+06
peak_list_spectra_bin_17,571.0,1.867660e+04,1.168632e+05,0.0,1.672555e+06
peak_list_spectra_bin_18,571.0,6.978326e+03,7.611191e+04,0.0,1.686837e+06
peak_list_spectra_bin_19,571.0,1.021086e+04,6.640189e+04,0.0,1.116150e+06
peak_list_spectra_bin_20,571.0,3.772229e+02,8.213339e+03,0.0,1.952628e+05
peak_list_spectra_bin_21,571.0,1.266136e+04,1.407655e+05,0.0,2.997314e+06
peak_list_spectra_bin_22,571.0,2.807554e+05,8.983399e+05,0.0,9.503275e+06
peak_list_spectra_bin_23,571.0,7.037403e+04,7.976250e+05,0.0,1.344161e+07
peak_list_spectra_bin_24,571.0,1.884710e+05,9.078573e+05,0.0,1.219677e+07
peak_list_spectra_bin_25,571.0,9.631509e+04,5.455992e+05,0.0,8.064792e+06
peak_list_spectra_bin_26,571.0,9.012541e+04,4.148073e+05,0.0,7.233476e+06
peak_list_spectra_bin_28,571.0,7.766759e+01,1.855914e+03,0.0,4.434820e+04
peak_list_spectra_bin_29,571.0,2.459488e+04,1.149778e+05,0.0,1.348512e+06
peak_list_spectra_bin_30,571.0,4.396934e+03,6.070518e+04,0.0,1.390651e+06
peak_list_spectra_bin_31,571.0,9.873887e+04,5.563571e+05,0.0,7.727092e+06
peak_list_spectra_bin_32,571.0,1.173225e+04,7.854600e+04,0.0,1.217201e+06
peak_list_spectra_bin_34,571.0,1.093660e+05,9.865699e+05,0.0,1.742044e+07
peak_list_spectra_bin_35,571.0,2.913917e+04,1.541080e+05,0.0,3.091789e+06
peak_list_spectra_bin_36,571.0,3.698161e+04,2.239843e+05,0.0,3.249630e+06
peak_list_spectra_bin_37,571.0,4.851729e+03,3.337768e+04,0.0,4.597278e+05
peak_list_spectra_bin_39,571.0,1.060374e+05,5.002093e+05,0.0,8.083785e+06
peak_list_spectra_bin_40,571.0,2.718032e+04,3.590280e+05,0.0,8.241982e+06
peak_list_spectra_bin_41,571.0,5.015460e+03,2.967608e+04,0.0,3.093092e+05
peak_list_spectra_bin_42,571.0,1.388836e+04,8.906850e+04,0.0,1.466209e+06
peak_list_spectra_bin_43,571.0,1.950287e+05,8.053122e+05,0.0,7.788256e+06
peak_list_spectra_bin_44,571.0,5.872646e+03,3.968279e+04,0.0,4.832809e+05
peak_list_spectra_bin_45,571.0,1.316720e+04,2.146607e+05,0.0,4.560290e+06
peak_list_spectra_bin_46,571.0,6.969217e+03,4.793374e+04,0.0,7.723387e+05
peak_list_spectra_bin_47,571.0,1.107888e+04,1.064277e+05,0.0,1.733209e+06
peak_list_spectra_bin_48,571.0,6.743968e+04,3.714543e+05,0.0,3.444515e+06
peak_list_spectra_bin_49,571.0,6.624534e+04,3.690801e+05,0.0,4.670851e+06
peak_list_spectra_bin_50,571.0,5.683309e+04,4.492663e+05,0.0,7.496672e+06
peak_list_spectra_bin_52,571.0,7.970166e+03,6.502163e+04,0.0,1.037665e+06
peak_list_spectra_bin_53,571.0,2.547221e+04,2.286711e+05,0.0,3.888917e+06
peak_list_spectra_bin_55,571.0,1.396947e+04,9.645514e+04,0.0,1.738842e+06
peak_list_spectra_bin_56,571.0,8.605217e+03,8.037228e+04,0.0,1.640292e+06
peak_list_spectra_bin_57,571.0,1.592477e+04,1.009432e+05,0.0,1.299844e+06
peak_list_spectra_bin_58,571.0,6.603542e+04,5.128154e+05,0.0,7.245400e+06
peak_list_spectra_bin_59,571.0,1.086505e+05,5.890912e+05,0.0,9.100563e+06
peak_list_spectra_bin_60,571.0,2.810549e+04,1.120491e+05,0.0,1.176842e+06
peak_list_spectra_bin_61,571.0,2.284820e+05,9.438640e+05,0.0,8.922107e+06
peak_list_spectra_bin_62,571.0,4.222659e+04,5.356746e+05,0.0,1.243150e+07
peak_list_spectra_bin_64,571.0,3.617552e+04,1.570826e+05,0.0,1.863363e+06
peak_list_spectra_bin_66,571.0,2.534323e+02,6.055918e+03,0.0,1.447098e+05
peak_list_spectra_bin_67,571.0,1.405149e+02,3.131798e+03,0.0,7.463638e+04
peak_list_spectra_bin_68,571.0,1.313235e+05,1.204164e+06,0.0,2.464953e+07
peak_list_spectra_bin_69,571.0,1.734920e+04,1.367625e+05,0.0,2.842582e+06
peak_list_spectra_bin_70,571.0,4.986942e+05,2.270733e+06,0.0,2.195004e+07
peak_list_spectra_bin_72,571.0,3.772405e+04,2.400694e+05,0.0,3.589408e+06
peak_list_spectra_bin_73,571.0,5.793584e+03,3.745963e+04,0.0,6.179639e+05
peak_list_spectra_bin_74,571.0,1.477556e+04,1.551703e+05,0.0,2.476276e+06
peak_list_spectra_bin_76,571.0,2.406107e+05,1.508404e+06,0.0,1.652224e+07
peak_list_spectra_bin_77,571.0,3.206365e+05,1.427621e+06,0.0,1.429425e+07
peak_list_spectra_bin_78,571.0,3.825605e+05,1.775412e+06,0.0,2.012449e+07
peak_list_spectra_bin_79,571.0,9.120768e+04,6.343570e+05,0.0,1.105722e+07
peak_list_spectra_bin_80,571.0,1.207772e+04,1.018794e+05,0.0,1.675007e+06
peak_list_spectra_bin_81,571.0,2.947291e+05,1.452139e+06,0.0,2.010605e+07
peak_list_spectra_bin_83,571.0,4.578638e+03,3.246201e+04,0.0,6.288964e+05
peak_list_spectra_bin_85,571.0,7.555372e+05,2.805172e+06,0.0,3.714673e+07
peak_list_spectra_bin_86,571.0,1.430561e+04,8.968585e+04,0.0,1.225411e+06
peak_list_spectra_bin_87,571.0,6.693561e+04,2.505805e+05,0.0,2.754208e+06
peak_list_spectra_bin_88,571.0,3.458672e+04,3.466118e+05,0.0,5.743747e+06
peak_list_spectra_bin_89,571.0,8.959003e+03,5.761010e+04,0.0,9.432759e+05
peak_list_spectra_bin_90,571.0,3.577124e+03,2.771152e+04,0.0,4.826351e+05
peak_list_spectra_bin_91,571.0,3.202787e+04,3.044019e+05,0.0,6.369110e+06
peak_list_spectra_bin_92,571.0,4.771298e+04,2.813378e+05,0.0,3.605114e+06
peak_list_spectra_bin_93,571.0,3.447875e+02,5.242555e+03,0.0,1.073645e+05
peak_list_spectra_bin_95,571.0,8.141288e+02,1.131275e+04,0.0,2.354569e+05
peak_list_spectra_bin_97,571.0,3.058363e+04,1.801120e+05,0.0,2.244584e+06
peak_list_spectra_bin_98,571.0,7.893888e+03,8.196755e+04,0.0,1.712800e+06
peak_list_spectra_bin_99,571.0,1.160926e+05,1.105743e+06,0.0,2.039352e+07
peak_list_spectra_bin_100,571.0,1.734934e+04,7.827802e+04,0.0,1.124329e+06
peak_list_spectra_bin_101,571.0,8.627015e+01,2.061478e+03,0.0,4.926026e+04
peak_list_spectra_bin_103,571.0,4.938203e+04,3.527091e+05,0.0,6.233386e+06
peak_list_spectra_bin_105,571.0,2.607455e+04,2.317956e+05,0.0,3.659485e+06
peak_list_spectra_bin_106,571.0,3.254155e+03,3.043838e+04,0.0,5.070253e+05
peak_list_spectra_bin_107,571.0,1.921552e+03,2.139304e+04,0.0,4.062272e+05
peak_list_spectra_bin_108,571.0,7.358399e+04,8.857475e+05,0.0,1.269017e+07
peak_list_spectra_bin_109,571.0,1.572712e+04,3.547641e+05,0.0,8.464180e+06
peak_list_spectra_bin_111,571.0,1.252943e+04,1.083640e+05,0.0,2.211591e+06
peak_list_spectra_bin_112,571.0,9.298751e+04,6.651709e+05,0.0,9.216992e+06
peak_list_spectra_bin_113,571.0,1.856016e+03,2.279175e+04,0.0,4.233669e+05
peak_list_spectra_bin_115,571.0,2.802712e+05,8.847124e+05,0.0,8.493492e+06
peak_list_spectra_bin_116,571.0,2.256794e+04,2.426876e+05,0.0,4.535902e+06
peak_list_spectra_bin_117,571.0,3.184422e+03,3.328438e+04,0.0,5.422035e+05
peak_list_spectra_bin_118,571.0,1.097662e+04,6.410520e+04,0.0,8.117446e+05
peak_list_spectra_bin_119,571.0,5.350068e+01,7.507040e+02,0.0,1.500879e+04
peak_list_spectra_bin_120,571.0,5.176803e+04,3.485529e+05,0.0,5.075663e+06
peak_list_spectra_bin_121,571.0,4.882626e+05,2.001958e+06,0.0,2.436522e+07
peak_list_spectra_bin_122,571.0,1.538720e+04,1.526608e+05,0.0,2.899739e+06
peak_list_spectra_bin_123,571.0,6.470865e+02,1.546252e+04,0.0,3.694864e+05
peak_list_spectra_bin_124,571.0,3.372907e+04,4.263258e+05,0.0,8.232961e+06
peak_list_spectra_bin_125,571.0,1.346609e+04,1.077581e+05,0.0,2.194990e+06
peak_list_spectra_bin_127,571.0,1.090029e+04,1.156150e+05,0.0,2.561364e+06
peak_list_spectra_bin_128,571.0,2.164582e+06,5.187401e+06,0.0,5.088121e+07
peak_list_spectra_bin_130,571.0,1.874312e+04,1.114663e+05,0.0,2.011263e+06
peak_list_spectra_bin_131,571.0,2.159207e+04,1.079894e+05,0.0,1.361243e+06
peak_list_spectra_bin_132,571.0,2.420844e+05,9.778631e+05,0.0,9.847198e+06
peak_list_spectra_bin_133,571.0,6.883511e+03,6.922692e+04,0.0,1.196589e+06
peak_list_spectra_bin_134,571.0,2.290133e+02,4.818982e+03,0.0,1.139470e+05
peak_list_spectra_bin_135,571.0,1.291443e+04,8.084318e+04,0.0,1.086483e+06
peak_list_spectra_bin_137,571.0,5.008708e+03,4.116586e+04,0.0,5.596643e+05
peak_list_spectra_bin_138,571.0,2.063026e+05,1.198286e+06,0.0,1.889255e+07
peak_list_spectra_bin_139,571.0,1.162781e+04,1.109836e+05,0.0,1.989810e+06
peak_list_spectra_bin_140,571.0,7.364379e+04,6.519344e+05,0.0,1.052031e+07
peak_list_spectra_bin_141,571.0,4.310486e+04,3.838694e+05,0.0,6.841020e+06
peak_list_spectra_bin_143,571.0,4.529756e+04,2.701266e+05,0.0,4.988464e+06
peak_list_spectra_bin_145,571.0,3.022600e+02,5.649556e+03,0.0,1.319066e+05
peak_list_spectra_bin_147,571.0,1.742658e+04,1.041750e+05,0.0,1.404113e+06
peak_list_spectra_bin_149,571.0,7.657417e+00,1.829786e+02,0.0,4.372385e+03
peak_list_spectra_bin_150,571.0,4.867108e+04,1.831563e+05,0.0,1.356018e+06
peak_list_spectra_bin_151,571.0,3.330337e+02,3.668413e+03,0.0,5.867631e+04
peak_list_spectra_bin_152,571.0,1.336091e+05,1.240750e+06,0.0,2.014689e+07
peak_list_spectra_bin_153,571.0,1.268255e+05,9.237868e+05,0.0,1.621177e+07
peak_list_spectra_bin_154,571.0,2.556842e+04,1.902627e+05,0.0,2.619516e+06
peak_list_spectra_bin_155,571.0,9.994166e+03,4.954596e+04,0.0,5.712281e+05
peak_list_spectra_bin_156,571.0,5.526524e+04,2.020568e+05,0.0,1.756037e+06
peak_list_spectra_bin_157,571.0,2.144692e+04,8.517260e+04,0.0,9.991646e+05
peak_list_spectra_bin_158,571.0,7.636786e+04,1.193959e+06,0.0,2.815042e+07
peak_list_spectra_bin_159,571.0,3.895512e+05,1.165024e+06,0.0,8.802974e+06
peak_list_spectra_bin_161,571.0,7.782494e+03,4.392186e+04,0.0,5.131680e+05
peak_list_spectra_bin_162,571.0,1.266070e+04,1.710760e+05,0.0,3.954858e+06
peak_list_spectra_bin_163,571.0,2.372649e+02,4.923676e+03,0.0,1.160777e+05
peak_list_spectra_bin_164,571.0,1.845973e+02,2.984169e+03,0.0,5.724943e+04
peak_list_spectra_bin_166,571.0,7.423260e+04,3.698486e+05,0.0,5.961487e+06
peak_list_spectra_bin_167,571.0,2.400246e+05,1.015196e+06,0.0,1.340529e+07
peak_list_spectra_bin_168,571.0,3.561323e+01,8.509996e+02,0.0,2.033515e+04
peak_list_spectra_bin_169,571.0,2.910241e+05,1.736602e+06,0.0,1.790025e+07
peak_list_spectra_bin_170,571.0,1.207717e+05,7.643884e+05,0.0,1.260363e+07
peak_list_spectra_bin_171,571.0,1.579117e+05,5.231729e+05,0.0,5.788722e+06
peak_list_spectra_bin_172,571.0,5.804609e+04,4.209199e+05,0.0,5.569688e+06
peak_list_spectra_bin_173,571.0,1.196316e+05,5.876409e+05,0.0,5.239409e+06
peak_list_spectra_bin_174,571.0,4.518547e+04,5.208414e+05,0.0,1.210592e+07
peak_list_spectra_bin_175,571.0,5.375151e+03,8.410180e+04,0.0,1.515603e+06
peak_list_spectra_bin_176,571.0,2.302374e+04,2.531206e+05,0.0,5.853928e+06
peak_list_spectra_bin_177,571.0,2.621215e+03,3.321766e+04,0.0,6.802004e+05
peak_list_spectra_bin_178,571.0,1.044919e+05,4.711793e+05,0.0,6.123098e+06
peak_list_spectra_bin_180,571.0,1.260871e+02,2.991522e+03,0.0,7.148329e+04
peak_list_spectra_bin_184,571.0,8.287967e+03,6.155113e+04,0.0,9.319597e+05
peak_list_spectra_bin_185,571.0,2.373959e+02,2.890577e+03,0.0,4.709680e+04
peak_list_spectra_bin_186,571.0,1.541970e+05,5.982613e+05,0.0,7.039934e+06
peak_list_spectra_bin_188,571.0,2.414493e+02,3.388512e+03,0.0,7.591655e+04
peak_list_spectra_bin_189,571.0,5.271053e+05,2.406202e+06,0.0,2.850261e+07
peak_list_spectra_bin_190,571.0,4.307073e+04,5.029019e+05,0.0,9.794014e+06
peak_list_spectra_bin_191,571.0,2.672337e+04,3.966766e+05,0.0,7.170204e+06
peak_list_spectra_bin_192,571.0,6.106895e+04,3.031882e+05,0.0,3.354083e+06
peak_list_spectra_bin_194,571.0,1.903428e+04,1.790598e+05,0.0,3.219634e+06
peak_list_spectra_bin_195,571.0,5.807185e+03,4.435641e+04,0.0,5.628727e+05
peak_list_spectra_bin_196,571.0,7.908917e+01,1.889884e+03,0.0,4.515991e+04
peak_list_spectra_bin_197,571.0,1.020826e+05,3.741026e+05,0.0,4.390958e+06
peak_list_spectra_bin_198,571.0,5.133967e+03,2.781181e+04,0.0,2.735182e+05
peak_list_spectra_bin_199,571.0,2.572779e+04,3.921030e+05,0.0,8.709684e+06
peak_list_spectra_bin_200,571.0,6.484371e+03,5.481882e+04,0.0,8.354066e+05
peak_list_spectra_bin_201,571.0,5.298261e+03,8.860901e+04,0.0,2.091089e+06
peak_list_spectra_bin_203,571.0,1.985095e+04,2.179817e+05,0.0,4.699577e+06
peak_list_spectra_bin_204,571.0,3.238111e+04,2.197511e+05,0.0,2.927758e+06
peak_list_spectra_bin_205,571.0,1.481047e+03,1.971074e+04,0.0,3.945810e+05
peak_list_spectra_bin_206,571.0,6.605075e+03,5.962481e+04,0.0,9.222669e+05
peak_list_spectra_bin_207,571.0,1.078627e+05,1.253020e+06,0.0,2.194311e+07
peak_list_spectra_bin_208,571.0,5.773605e+04,1.989736e+05,0.0,2.284039e+06
peak_list_spectra_bin_209,571.0,1.876592e+02,2.039526e+03,0.0,3.236861e+04
peak_list_spectra_bin_210,571.0,5.440869e+04,6.757098e+05,0.0,1.409393e+07
peak_list_spectra_bin_211,571.0,6.261242e+04,3.449450e+05,0.0,3.766276e+06
peak_list_spectra_bin_214,571.0,8.494985e+04,1.153253e+06,0.0,2.053518e+07
peak_list_spectra_bin_215,571.0,6.781059e+04,8.053152e+05,0.0,1.716453e+07
peak_list_spectra_bin_216,571.0,3.018743e+04,2.206438e+05,0.0,3.677553e+06
peak_list_spectra_bin_217,571.0,2.337016e+05,7.189675e+05,0.0,5.922583e+06
peak_list_spectra_bin_218,571.0,4.956708e+03,4.050016e+04,0.0,6.943298e+05
peak_list_spectra_bin_219,571.0,7.027295e+03,5.385445e+04,0.0,8.789136e+05
peak_list_spectra_bin_220,571.0,8.907689e+01,2.128546e+03,0.0,5.086291e+04
peak_list_spectra_bin_221,571.0,4.537023e+05,1.651749e+06,0.0,1.806526e+07
peak_list_spectra_bin_222,571.0,1.827018e+04,8.823428e+04,0.0,1.227866e+06
peak_list_spectra_bin_224,571.0,4.759109e+04,4.911103e+05,0.0,8.989121e+06
peak_list_spectra_bin_225,571.0,5.471823e+04,2.173046e+05,0.0,2.849998e+06
peak_list_spectra_bin_226,571.0,1.358937e+05,8.135707e+05,0.0,1.020022e+07
peak_list_spectra_bin_227,571.0,2.484569e+04,2.562866e+05,0.0,5.098246e+06
peak_list_spectra_bin_228,571.0,6.071104e+04,8.495279e+05,0.0,1.493892e+07
peak_list_spectra_bin_229,571.0,4.378329e+04,2.437273e+05,0.0,3.858546e+06
peak_list_spectra_bin_230,571.0,2.525262e+04,1.507169e+05,0.0,2.189834e+06
peak_list_spectra_bin_231,571.0,1.627070e+04,9.938797e+04,0.0,1.339120e+06
peak_list_spectra_bin_232,571.0,8.391515e+04,3.133593e+05,0.0,2.976480e+06
peak_list_spectra_bin_233,571.0,3.081164e+05,1.308510e+06,0.0,1.625054e+07
peak_list_spectra_bin_235,571.0,2.813625e+02,4.757596e+03,0.0,8.488398e+04
peak_list_spectra_bin_237,571.0,1.429844e+04,7.502710e+04,0.0,1.132010e+06
peak_list_spectra_bin_238,571.0,5.062940e+04,2.580358e+05,0.0,2.900358e+06
peak_list_spectra_bin_239,571.0,1.501523e+04,1.137577e+05,0.0,1.873040e+06
peak_list_spectra_bin_240,571.0,2.662126e+04,1.278238e+05,0.0,1.467247e+06
peak_list_spectra_bin_241,571.0,2.863142e+01,4.898484e+02,0.0,9.516469e+03
peak_list_spectra_bin_242,571.0,2.734412e+05,2.128420e+06,0.0,3.239747e+07
peak_list_spectra_bin_243,571.0,6.839154e+05,2.484988e+06,0.0,2.384417e+07
peak_list_spectra_bin_244,571.0,1.310964e+04,6.134882e+04,0.0,6.203011e+05
peak_list_spectra_bin_245,571.0,1.715071e+03,1.946674e+04,0.0,3.613795e+05
peak_list_spectra_bin_246,571.0,5.205393e+04,3.894070e+05,0.0,4.832734e+06
peak_list_spectra_bin_249,571.0,8.793392e+02,1.382468e+04,0.0,2.377240e+05
peak_list_spectra_bin_250,571.0,7.233702e+04,7.503712e+05,0.0,1.480293e+07
peak_list_spectra_bin_252,571.0,2.837119e+04,1.839231e+05,0.0,2.433900e+06
peak_list_spectra_bin_253,571.0,8.600101e+03,1.704995e+05,0.0,3.971194e+06
peak_list_spectra_bin_256,571.0,3.827481e+03,2.029005e+04,0.0,3.109505e+05
peak_list_spectra_bin_257,571.0,1.406718e+04,9.201450e+04,0.0,1.077014e+06
peak_list_spectra_bin_258,571.0,4.734382e+04,2.994781e+05,0.0,3.844549e+06
peak_list_spectra_bin_260,571.0,2.113274e+03,1.102601e+04,0.0,1.133325e+05
peak_list_spectra_bin_262,571.0,5.110172e+04,2.991435e+05,0.0,6.110973e+06
peak_list_spectra_bin_263,571.0,9.232363e+04,3.724155e+05,0.0,4.505586e+06
peak_list_spectra_bin_264,571.0,5.262342e+04,4.607860e+05,0.0,9.261053e+06
peak_list_spectra_bin_265,571.0,1.165951e+04,6.157315e+04,0.0,8.363297e+05
peak_list_spectra_bin_266,571.0,1.799602e+04,1.186526e+05,0.0,1.983156e+06
peak_list_spectra_bin_267,571.0,1.356058e+01,3.240382e+02,0.0,7.743088e+03
peak_list_spectra_bin_268,571.0,1.539704e+03,1.896605e+04,0.0,3.516509e+05
peak_list_spectra_bin_269,571.0,1.599730e+04,1.576311e+05,0.0,3.603478e+06
peak_list_spectra_bin_271,571.0,2.338306e+04,9.061081e+04,0.0,1.109618e+06
peak_list_spectra_bin_272,571.0,7.246781e+04,2.551951e+05,0.0,2.277098e+06
peak_list_spectra_bin_273,571.0,2.423871e+04,1.554318e+05,0.0,2.130844e+06
peak_list_spectra_bin_274,571.0,6.955424e+03,3.946895e+04,0.0,4.012787e+05
peak_list_spectra_bin_275,571.0,1.350860e+04,7.550009e+04,0.0,1.057897e+06
peak_list_spectra_bin_276,571.0,1.903195e+03,1.427776e+04,0.0,1.810168e+05
peak_list_spectra_bin_277,571.0,4.132904e+04,2.053476e+05,0.0,2.136466e+06
peak_list_spectra_bin_278,571.0,3.398555e+04,3.091972e+05,0.0,4.372633e+06
peak_list_spectra_bin_279,571.0,7.946829e+04,5.710621e+05,0.0,8.981687e+06
peak_list_spectra_bin_280,571.0,2.039365e+02,4.081738e+03,0.0,9.619313e+04
peak_list_spectra_bin_281,571.0,6.828721e+03,6.658333e+04,0.0,1.265987e+06
peak_list_spectra_bin_282,571.0,1.112785e+04,6.895299e+04,0.0,9.848936e+05
peak_list_spectra_bin_283,571.0,3.021043e+04,3.411653e+05,0.0,6.508758e+06
peak_list_spectra_bin_284,571.0,1.994338e+04,1.786128e+05,0.0,3.840763e+06
peak_list_spectra_bin_285,571.0,1.508176e+04,1.436750e+05,0.0,2.965014e+06
peak_list_spectra_bin_286,571.0,2.900644e+03,2.336600e+04,0.0,3.418777e+05
peak_list_spectra_bin_287,571.0,4.209823e+03,6.554006e+04,0.0,1.466207e+06
peak_list_spectra_bin_288,571.0,1.243401e+04,8.162258e+04,0.0,1.181660e+06
peak_list_spectra_bin_289,571.0,1.549896e+05,1.196180e+06,0.0,2.239998e+07
peak_list_spectra_bin_290,571.0,1.613999e+04,8.740383e+04,0.0,1.283988e+06
peak_list_spectra_bin_291,571.0,3.354726e+04,2.863442e+05,0.0,6.216098e+06
peak_list_spectra_bin_292,571.0,2.570094e+05,1.689105e+06,0.0,2.650349e+07
peak_list_spectra_bin_293,571.0,2.382705e+04,1.502624e+05,0.0,2.578582e+06
peak_list_spectra_bin_294,571.0,1.913765e+05,9.258664e+05,0.0,1.321832e+07
peak_list_spectra_bin_296,571.0,1.715065e+05,1.446781e+06,0.0,2.849311e+07
peak_list_spectra_bin_297,571.0,8.904766e+03,7.276697e+04,0.0,1.247659e+06
peak_list_spectra_bin_298,571.0,3.295617e+04,3.794463e+05,0.0,6.059732e+06
peak_list_spectra_bin_299,571.0,4.149882e+03,2.510410e+04,0.0,3.780302e+05
peak_list_spectra_bin_300,571.0,2.698135e+04,1.730902e+05,0.0,2.342510e+06
peak_list_spectra_bin_302,571.0,5.346065e+03,3.793916e+04,0.0,6.309619e+05
peak_list_spectra_bin_303,571.0,3.670941e+04,3.096203e+05,0.0,6.260814e+06
peak_list_spectra_bin_304,571.0,4.915152e+02,5.331062e+03,0.0,9.112562e+04
peak_list_spectra_bin_305,571.0,1.090491e+03,1.338338e+04,0.0,2.771540e+05
peak_list_spectra_bin_306,571.0,2.893165e+03,2.538775e+04,0.0,4.051868e+05
peak_list_spectra_bin_307,571.0,3.324130e+05,1.490765e+06,0.0,1.473961e+07
peak_list_spectra_bin_308,571.0,3.133618e+03,2.489821e+04,0.0,2.961908e+05
peak_list_spectra_bin_309,571.0,3.294004e+05,1.204193e+06,0.0,1.403054e+07
peak_list_spectra_bin_310,571.0,1.945404e+04,9.993792e+04,0.0,1.140095e+06
peak_list_spectra_bin_311,571.0,3.059053e+04,2.008100e+05,0.0,3.154217e+06
peak_list_spectra_bin_312,571.0,2.095177e+04,2.183038e+05,0.0,4.544786e+06
peak_list_spectra_bin_313,571.0,4.718130e+04,3.999190e+05,0.0,6.637383e+06
peak_list_spectra_bin_314,571.0,5.538764e+04,3.422628e+05,0.0,6.036959e+06
peak_list_spectra_bin_315,571.0,7.666539e+03,4.548680e+04,0.0,5.233367e+05
peak_list_spectra_bin_316,571.0,2.554306e+05,1.000841e+06,0.0,1.208244e+07
peak_list_spectra_bin_317,571.0,9.706246e+04,1.222426e+06,0.0,2.766784e+07
peak_list_spectra_bin_318,571.0,3.177254e+04,1.581275e+05,0.0,2.669176e+06

In [8]:
# Categorical Feature Statistics
cat_stats

                               value  count    pct
column  rank
Species 1           Escherichia coli     60  10.51
        2       Enterobacter cloacae     52   9.11
        3     Haemophilus influenzae     50   8.76
        4          Shigella flexneri     32   5.60
        5     Listeria monocytogenes     31   5.43
Strain  1                          7      6   1.05
        2                         66      6   1.05
        3                        126      6   1.05
        4                        188      6   1.05
        5                         49      5   0.88

In [9]:
# Target Distribution
target_df

                            count    pct
Species
Escherichia coli               60  10.51
Enterobacter cloacae           52   9.11
Haemophilus influenzae         50   8.76
Shigella flexneri              32   5.60
Listeria monocytogenes         31   5.43
Shigella sonnei                31   5.43
Listeria ivanovii              29   5.08
Enterobacter asburiae          29   5.08
Citrobacter freundii           28   4.90
Yersinia enterocolitica        27   4.73
Bacillus cereus                26   4.55
Citrobacter braakii            26   4.55
Streptococcus mitis            26   4.55
Streptococcus oralis           24   4.20
Haemophilus parainfluenzae     21   3.68
Yersinia frederiksenii         20   3.50
Shigella boydii                18   3.15
Clostridium glycolicum         16   2.80
Clostridium difficile          14   2.45
Bacillus thuringiensis         11   1.93

## Task Curation

In [10]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
    group_labels=task_mold.group_labels,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Providing recommendations based on number of groups (213).
Recommended splits: n_repeats=20, n_splits=3, test_size=None

In [11]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_grouped_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    group_on=task_mold.group_on,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
    group_labels=task_mold.group_labels,
    show_splits=True,
    target_on=task_mold.target_column_name,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for grouped data.",
    splits=splits,
)

Using Stratified Grouped splits.
Using label-per-group grouped splits.
Creating index-based splits for 213 groups
Using Stratified IID splits.
Repeat 0, Fold 0:
            Train N: 380, Test N: 191
            Target Distribution:
            	Train target distribution: {'Escherichia coli': 0.11052631578947368, 'Enterobacter cloacae': 0.09736842105263158, 'Haemophilus influenzae': 0.07894736842105263, 'Shigella sonnei': 0.05526315789473684, 'Listeria monocytogenes': 0.05263157894736842, 'Yersinia enterocolitica': 0.05263157894736842, 'Enterobacter asburiae': 0.05263157894736842, 'Citrobacter freundii': 0.05, 'Shigella flexneri': 0.05, 'Listeria ivanovii': 0.05, 'Citrobacter braakii': 0.05, 'Streptococcus mitis': 0.04473684210526316, 'Bacillus cereus': 0.042105263157894736, 'Yersinia frederiksenii': 0.03684210526315789, 'Haemophilus parainfluenzae': 0.03684210526315789, 'Streptococcus oralis': 0.03684210526315789, 'Shigella boydii': 0.034210526315789476, 'Clostridium glycolicum': 0.02631578947368421, 'Bacillus thuringiensis': 0.021052631578947368, 'Clostridium difficile': 0.021052631578947368}
            	Test target distribution: {'Haemophilus influenzae': 0.10471204188481675, 'Escherichia coli': 0.09424083769633508, 'Enterobacter cloacae': 0.07853403141361257, 'Shigella flexneri': 0.06806282722513089, 'Listeria monocytogenes': 0.05759162303664921, 'Shigella sonnei': 0.05235602094240838, 'Streptococcus oralis': 0.05235602094240838, 'Bacillus cereus': 0.05235602094240838, 'Listeria ivanovii': 0.05235602094240838, 'Streptococcus mitis': 0.04712041884816754, 'Citrobacter freundii': 0.04712041884816754, 'Enterobacter asburiae': 0.04712041884816754, 'Haemophilus parainfluenzae': 0.03664921465968586, 'Citrobacter braakii': 0.03664921465968586, 'Yersinia enterocolitica': 0.03664921465968586, 'Clostridium glycolicum': 0.031413612565445025, 'Yersinia frederiksenii': 0.031413612565445025, 'Clostridium difficile': 0.031413612565445025, 'Shigella boydii': 0.02617801047120419, 'Bacillus thuringiensis': 0.015706806282722512}
            Group Distribution Strain:
            	Train: 142
            	Test: 71

Repeat 0, Fold 1:
            Train N: 382, Test N: 189
            Target Distribution:
            	Train target distribution: {'Escherichia coli': 0.09947643979057591, 'Enterobacter cloacae': 0.09947643979057591, 'Haemophilus influenzae': 0.08638743455497382, 'Shigella flexneri': 0.05759162303664921, 'Listeria monocytogenes': 0.05235602094240838, 'Enterobacter asburiae': 0.05235602094240838, 'Citrobacter freundii': 0.05235602094240838, 'Listeria ivanovii': 0.049738219895287955, 'Yersinia enterocolitica': 0.049738219895287955, 'Shigella sonnei': 0.049738219895287955, 'Bacillus cereus': 0.04450261780104712, 'Streptococcus mitis': 0.04450261780104712, 'Citrobacter braakii': 0.041884816753926704, 'Streptococcus oralis': 0.03926701570680628, 'Haemophilus parainfluenzae': 0.03664921465968586, 'Yersinia frederiksenii': 0.034031413612565446, 'Shigella boydii': 0.031413612565445025, 'Clostridium difficile': 0.031413612565445025, 'Clostridium glycolicum': 0.028795811518324606, 'Bacillus thuringiensis': 0.01832460732984293}
            	Test target distribution: {'Escherichia coli': 0.1164021164021164, 'Haemophilus influenzae': 0.08994708994708994, 'Enterobacter cloacae': 0.07407407407407407, 'Shigella sonnei': 0.06349206349206349, 'Listeria monocytogenes': 0.0582010582010582, 'Shigella flexneri': 0.05291005291005291, 'Listeria ivanovii': 0.05291005291005291, 'Citrobacter braakii': 0.05291005291005291, 'Streptococcus oralis': 0.047619047619047616, 'Streptococcus mitis': 0.047619047619047616, 'Bacillus cereus': 0.047619047619047616, 'Enterobacter asburiae': 0.047619047619047616, 'Yersinia enterocolitica': 0.042328042328042326, 'Citrobacter freundii': 0.042328042328042326, 'Yersinia frederiksenii': 0.037037037037037035, 'Haemophilus parainfluenzae': 0.037037037037037035, 'Shigella boydii': 0.031746031746031744, 'Clostridium glycolicum': 0.026455026455026454, 'Bacillus thuringiensis': 0.021164021164021163, 'Clostridium difficile': 0.010582010582010581}
            Group Distribution Strain:
            	Train: 142
            	Test: 71

Repeat 0, Fold 2:
            Train N: 380, Test N: 191
            Target Distribution:
            	Train target distribution: {'Escherichia coli': 0.10526315789473684, 'Haemophilus influenzae': 0.09736842105263158, 'Enterobacter cloacae': 0.07631578947368421, 'Shigella flexneri': 0.060526315789473685, 'Listeria monocytogenes': 0.05789473684210526, 'Shigella sonnei': 0.05789473684210526, 'Listeria ivanovii': 0.05263157894736842, 'Bacillus cereus': 0.05, 'Streptococcus oralis': 0.05, 'Streptococcus mitis': 0.04736842105263158, 'Enterobacter asburiae': 0.04736842105263158, 'Citrobacter braakii': 0.04473684210526316, 'Citrobacter freundii': 0.04473684210526316, 'Yersinia enterocolitica': 0.039473684210526314, 'Haemophilus parainfluenzae': 0.03684210526315789, 'Yersinia frederiksenii': 0.034210526315789476, 'Shigella boydii': 0.02894736842105263, 'Clostridium glycolicum': 0.02894736842105263, 'Clostridium difficile': 0.021052631578947368, 'Bacillus thuringiensis': 0.018421052631578946}
            	Test target distribution: {'Enterobacter cloacae': 0.12041884816753927, 'Escherichia coli': 0.10471204188481675, 'Haemophilus influenzae': 0.06806282722513089, 'Yersinia enterocolitica': 0.06282722513089005, 'Enterobacter asburiae': 0.05759162303664921, 'Citrobacter freundii': 0.05759162303664921, 'Citrobacter braakii': 0.04712041884816754, 'Listeria ivanovii': 0.04712041884816754, 'Shigella flexneri': 0.04712041884816754, 'Shigella sonnei': 0.04712041884816754, 'Listeria monocytogenes': 0.04712041884816754, 'Streptococcus mitis': 0.041884816753926704, 'Yersinia frederiksenii': 0.03664921465968586, 'Bacillus cereus': 0.03664921465968586, 'Haemophilus parainfluenzae': 0.03664921465968586, 'Shigella boydii': 0.03664921465968586, 'Clostridium difficile': 0.031413612565445025, 'Clostridium glycolicum': 0.02617801047120419, 'Streptococcus oralis': 0.02617801047120419, 'Bacillus thuringiensis': 0.020942408376963352}
            Group Distribution Strain:
            	Train: 142
            	Test: 71

Repeat 1, Fold 0:
            Train N: 362, Test N: 209
            Target Distribution:
            	Train target distribution: {'Escherichia coli': 0.11602209944751381, 'Enterobacter cloacae': 0.10497237569060773, 'Haemophilus influenzae': 0.08011049723756906, 'Shigella sonnei': 0.055248618784530384, 'Listeria monocytogenes': 0.052486187845303865, 'Shigella flexneri': 0.052486187845303865, 'Streptococcus oralis': 0.049723756906077346, 'Yersinia enterocolitica': 0.049723756906077346, 'Streptococcus mitis': 0.04696132596685083, 'Citrobacter freundii': 0.04696132596685083, 'Bacillus cereus': 0.04419889502762431, 'Citrobacter braakii': 0.04143646408839779, 'Listeria ivanovii': 0.04143646408839779, 'Enterobacter asburiae': 0.04143646408839779, 'Yersinia frederiksenii': 0.03591160220994475, 'Haemophilus parainfluenzae': 0.03314917127071823, 'Clostridium glycolicum': 0.03038674033149171, 'Clostridium difficile': 0.03038674033149171, 'Shigella boydii': 0.03038674033149171, 'Bacillus thuringiensis': 0.016574585635359115}
            	Test target distribution: {'Haemophilus influenzae': 0.10047846889952153, 'Escherichia coli': 0.0861244019138756, 'Enterobacter asburiae': 0.06698564593301436, 'Enterobacter cloacae': 0.06698564593301436, 'Listeria ivanovii': 0.06698564593301436, 'Shigella flexneri': 0.06220095693779904, 'Listeria monocytogenes': 0.05741626794258373, 'Citrobacter freundii': 0.05263157894736842, 'Citrobacter braakii': 0.05263157894736842, 'Shigella sonnei': 0.05263157894736842, 'Bacillus cereus': 0.04784688995215311, 'Yersinia enterocolitica': 0.0430622009569378, 'Haemophilus parainfluenzae': 0.0430622009569378, 'Streptococcus mitis': 0.0430622009569378, 'Yersinia frederiksenii': 0.03349282296650718, 'Shigella boydii': 0.03349282296650718, 'Streptococcus oralis': 0.028708133971291867, 'Bacillus thuringiensis': 0.023923444976076555, 'Clostridium glycolicum': 0.023923444976076555, 'Clostridium difficile': 0.014354066985645933}
            Group Distribution Strain:
            	Train: 142
            	Test: 71

Repeat 1, Fold 1:
            Train N: 384, Test N: 187
            Target Distribution:
            	Train target distribution: {'Escherichia coli': 0.09895833333333333, 'Haemophilus influenzae': 0.09375, 'Enterobacter cloacae': 0.09114583333333333, 'Shigella flexneri': 0.059895833333333336, 'Listeria ivanovii': 0.057291666666666664, 'Shigella sonnei': 0.0546875, 'Enterobacter asburiae': 0.052083333333333336, 'Listeria monocytogenes': 0.052083333333333336, 'Yersinia enterocolitica': 0.049479166666666664, 'Citrobacter braakii': 0.049479166666666664, 'Citrobacter freundii': 0.046875, 'Streptococcus mitis': 0.041666666666666664, 'Yersinia frederiksenii': 0.0390625, 'Bacillus cereus': 0.0390625, 'Streptococcus oralis': 0.036458333333333336, 'Haemophilus parainfluenzae': 0.036458333333333336, 'Shigella boydii': 0.03125, 'Clostridium glycolicum': 0.026041666666666668, 'Clostridium difficile': 0.026041666666666668, 'Bacillus thuringiensis': 0.018229166666666668}
            	Test target distribution: {'Escherichia coli': 0.11764705882352941, 'Enterobacter cloacae': 0.09090909090909091, 'Haemophilus influenzae': 0.0748663101604278, 'Bacillus cereus': 0.058823529411764705, 'Listeria monocytogenes': 0.058823529411764705, 'Streptococcus mitis': 0.053475935828877004, 'Citrobacter freundii': 0.053475935828877004, 'Streptococcus oralis': 0.053475935828877004, 'Shigella sonnei': 0.053475935828877004, 'Enterobacter asburiae': 0.0481283422459893, 'Shigella flexneri': 0.0481283422459893, 'Yersinia enterocolitica': 0.0427807486631016, 'Listeria ivanovii': 0.0374331550802139, 'Citrobacter braakii': 0.0374331550802139, 'Haemophilus parainfluenzae': 0.0374331550802139, 'Shigella boydii': 0.03208556149732621, 'Clostridium glycolicum': 0.03208556149732621, 'Yersinia frederiksenii': 0.026737967914438502, 'Bacillus thuringiensis': 0.0213903743315508, 'Clostridium difficile': 0.0213903743315508}
            Group Distribution Strain:
            	Train: 142
            	Test: 71

Repeat 1, Fold 2:
            Train N: 396, Test N: 175
            Target Distribution:
            	Train target distribution: {'Escherichia coli': 0.10101010101010101, 'Haemophilus influenzae': 0.08838383838383838, 'Enterobacter cloacae': 0.07828282828282829, 'Enterobacter asburiae': 0.05808080808080808, 'Listeria monocytogenes': 0.05808080808080808, 'Shigella flexneri': 0.05555555555555555, 'Citrobacter freundii': 0.05303030303030303, 'Bacillus cereus': 0.05303030303030303, 'Listeria ivanovii': 0.05303030303030303, 'Shigella sonnei': 0.05303030303030303, 'Streptococcus mitis': 0.047979797979797977, 'Citrobacter braakii': 0.045454545454545456, 'Yersinia enterocolitica': 0.04292929292929293, 'Haemophilus parainfluenzae': 0.04040404040404041, 'Streptococcus oralis': 0.04040404040404041, 'Shigella boydii': 0.03282828282828283, 'Yersinia frederiksenii': 0.030303030303030304, 'Clostridium glycolicum': 0.027777777777777776, 'Bacillus thuringiensis': 0.022727272727272728, 'Clostridium difficile': 0.017676767676767676}
            	Test target distribution: {'Enterobacter cloacae': 0.12, 'Escherichia coli': 0.11428571428571428, 'Haemophilus influenzae': 0.08571428571428572, 'Shigella sonnei': 0.05714285714285714, 'Shigella flexneri': 0.05714285714285714, 'Yersinia enterocolitica': 0.05714285714285714, 'Listeria monocytogenes': 0.045714285714285714, 'Citrobacter braakii': 0.045714285714285714, 'Yersinia frederiksenii': 0.045714285714285714, 'Streptococcus oralis': 0.045714285714285714, 'Listeria ivanovii': 0.045714285714285714, 'Citrobacter freundii': 0.04, 'Streptococcus mitis': 0.04, 'Clostridium difficile': 0.04, 'Enterobacter asburiae': 0.03428571428571429, 'Bacillus cereus': 0.02857142857142857, 'Haemophilus parainfluenzae': 0.02857142857142857, 'Clostridium glycolicum': 0.02857142857142857, 'Shigella boydii': 0.02857142857142857, 'Bacillus thuringiensis': 0.011428571428571429}
            Group Distribution Strain:
            	Train: 142
            	Test: 71

Repeat 2, Fold 0:
            Train N: 381, Test N: 190
            Target Distribution:
            	Train target distribution: {'Escherichia coli': 0.10498687664041995, 'Enterobacter cloacae': 0.09711286089238845, 'Haemophilus influenzae': 0.08923884514435695, 'Listeria ivanovii': 0.05511811023622047, 'Shigella sonnei': 0.05511811023622047, 'Listeria monocytogenes': 0.05249343832020997, 'Citrobacter freundii': 0.05249343832020997, 'Bacillus cereus': 0.05249343832020997, 'Enterobacter asburiae': 0.049868766404199474, 'Yersinia enterocolitica': 0.049868766404199474, 'Streptococcus mitis': 0.047244094488188976, 'Shigella flexneri': 0.04461942257217848, 'Streptococcus oralis': 0.04199475065616798, 'Citrobacter braakii': 0.04199475065616798, 'Haemophilus parainfluenzae': 0.03937007874015748, 'Shigella boydii': 0.028871391076115485, 'Yersinia frederiksenii': 0.028871391076115485, 'Clostridium glycolicum': 0.026246719160104987, 'Bacillus thuringiensis': 0.02099737532808399, 'Clostridium difficile': 0.02099737532808399}
            	Test target distribution: {'Escherichia coli': 0.10526315789473684, 'Haemophilus influenzae': 0.08421052631578947, 'Shigella flexneri': 0.07894736842105263, 'Enterobacter cloacae': 0.07894736842105263, 'Listeria monocytogenes': 0.05789473684210526, 'Shigella sonnei': 0.05263157894736842, 'Enterobacter asburiae': 0.05263157894736842, 'Citrobacter braakii': 0.05263157894736842, 'Yersinia frederiksenii': 0.04736842105263158, 'Streptococcus oralis': 0.042105263157894736, 'Citrobacter freundii': 0.042105263157894736, 'Streptococcus mitis': 0.042105263157894736, 'Yersinia enterocolitica': 0.042105263157894736, 'Listeria ivanovii': 0.042105263157894736, 'Shigella boydii': 0.03684210526315789, 'Bacillus cereus': 0.031578947368421054, 'Clostridium glycolicum': 0.031578947368421054, 'Haemophilus parainfluenzae': 0.031578947368421054, 'Clostridium difficile': 0.031578947368421054, 'Bacillus thuringiensis': 0.015789473684210527}
            Group Distribution Strain:
            	Train: 142
            	Test: 71

Repeat 2, Fold 1:
            Train N: 387, Test N: 184
            Target Distribution:
            	Train target distribution: {'Escherichia coli': 0.10594315245478036, 'Enterobacter cloacae': 0.09043927648578812, 'Haemophilus influenzae': 0.082687338501292, 'Listeria monocytogenes': 0.059431524547803614, 'Shigella flexneri': 0.056847545219638244, 'Citrobacter freundii': 0.056847545219638244, 'Enterobacter asburiae': 0.05426356589147287, 'Yersinia enterocolitica': 0.05426356589147287, 'Listeria ivanovii': 0.046511627906976744, 'Shigella sonnei': 0.04392764857881137, 'Citrobacter braakii': 0.04392764857881137, 'Bacillus cereus': 0.041343669250646, 'Streptococcus mitis': 0.041343669250646, 'Yersinia frederiksenii': 0.03875968992248062, 'Streptococcus oralis': 0.03875968992248062, 'Haemophilus parainfluenzae': 0.03617571059431524, 'Shigella boydii': 0.03359173126614987, 'Clostridium difficile': 0.031007751937984496, 'Clostridium glycolicum': 0.028423772609819122, 'Bacillus thuringiensis': 0.015503875968992248}
            	Test target distribution: {'Escherichia coli': 0.10326086956521739, 'Haemophilus influenzae': 0.09782608695652174, 'Enterobacter cloacae': 0.09239130434782608, 'Shigella sonnei': 0.07608695652173914, 'Listeria ivanovii': 0.059782608695652176, 'Shigella flexneri': 0.05434782608695652, 'Streptococcus mitis': 0.05434782608695652, 'Bacillus cereus': 0.05434782608695652, 'Citrobacter braakii': 0.04891304347826087, 'Streptococcus oralis': 0.04891304347826087, 'Listeria monocytogenes': 0.043478260869565216, 'Enterobacter asburiae': 0.043478260869565216, 'Haemophilus parainfluenzae': 0.03804347826086957, 'Citrobacter freundii': 0.03260869565217391, 'Yersinia enterocolitica': 0.03260869565217391, 'Bacillus thuringiensis': 0.02717391304347826, 'Shigella boydii': 0.02717391304347826, 'Clostridium glycolicum': 0.02717391304347826, 'Yersinia frederiksenii': 0.02717391304347826, 'Clostridium difficile': 0.010869565217391304}
            Group Distribution Strain:
            	Train: 142
            	Test: 71

Repeat 2, Fold 2:
            Train N: 374, Test N: 197
            Target Distribution:
            	Train target distribution: {'Escherichia coli': 0.10427807486631016, 'Haemophilus influenzae': 0.09090909090909091, 'Enterobacter cloacae': 0.0855614973262032, 'Shigella flexneri': 0.06684491978609626, 'Shigella sonnei': 0.06417112299465241, 'Listeria monocytogenes': 0.05080213903743316, 'Listeria ivanovii': 0.05080213903743316, 'Citrobacter braakii': 0.05080213903743316, 'Streptococcus mitis': 0.0481283422459893, 'Enterobacter asburiae': 0.0481283422459893, 'Streptococcus oralis': 0.045454545454545456, 'Bacillus cereus': 0.0427807486631016, 'Yersinia frederiksenii': 0.0374331550802139, 'Citrobacter freundii': 0.0374331550802139, 'Yersinia enterocolitica': 0.0374331550802139, 'Haemophilus parainfluenzae': 0.034759358288770054, 'Shigella boydii': 0.03208556149732621, 'Clostridium glycolicum': 0.029411764705882353, 'Bacillus thuringiensis': 0.0213903743315508, 'Clostridium difficile': 0.0213903743315508}
            	Test target distribution: {'Escherichia coli': 0.1065989847715736, 'Enterobacter cloacae': 0.10152284263959391, 'Haemophilus influenzae': 0.08121827411167512, 'Citrobacter freundii': 0.07106598984771574, 'Yersinia enterocolitica': 0.06598984771573604, 'Listeria monocytogenes': 0.06091370558375635, 'Enterobacter asburiae': 0.05583756345177665, 'Bacillus cereus': 0.050761421319796954, 'Listeria ivanovii': 0.050761421319796954, 'Haemophilus parainfluenzae': 0.04060913705583756, 'Streptococcus mitis': 0.04060913705583756, 'Citrobacter braakii': 0.03553299492385787, 'Streptococcus oralis': 0.03553299492385787, 'Shigella sonnei': 0.03553299492385787, 'Shigella flexneri': 0.03553299492385787, 'Shigella boydii': 0.030456852791878174, 'Yersinia frederiksenii': 0.030456852791878174, 'Clostridium difficile': 0.030456852791878174, 'Clostridium glycolicum': 0.025380710659898477, 'Bacillus thuringiensis': 0.015228426395939087}
            Group Distribution Strain:
            	Train: 142
            	Test: 71

Repeat 3, Fold 0:
            Train N: 387, Test N: 184
            Target Distribution:
            	Train target distribution: {'Escherichia coli': 0.09819121447028424, 'Enterobacter cloacae': 0.09043927648578812, 'Haemophilus influenzae': 0.08785529715762273, 'Shigella sonnei': 0.06201550387596899, 'Listeria ivanovii': 0.056847545219638244, 'Listeria monocytogenes': 0.05426356589147287, 'Enterobacter asburiae': 0.05167958656330749, 'Citrobacter freundii': 0.05167958656330749, 'Yersinia enterocolitica': 0.05167958656330749, 'Bacillus cereus': 0.046511627906976744, 'Citrobacter braakii': 0.046511627906976744, 'Shigella flexneri': 0.04392764857881137, 'Streptococcus mitis': 0.041343669250646, 'Streptococcus oralis': 0.041343669250646, 'Shigella boydii': 0.03359173126614987, 'Haemophilus parainfluenzae': 0.03359173126614987, 'Yersinia frederiksenii': 0.03359173126614987, 'Clostridium difficile': 0.028423772609819122, 'Clostridium glycolicum': 0.025839793281653745, 'Bacillus thuringiensis': 0.020671834625323}

## Export

In [12]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to micro_mass/019d319c-d4d7-7b90-9c84-1201e1f4eb51
019d319c-d4d7-7b90-9c84-1201e1f4eb51
a869e9ec6842f4666caa1774b744370a6979c9f5e8595895607a79afb23bd0fd