### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="sberbank_housing_market_forecasting",
    dataset_year="2017",
    domain_str="business & marketing",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/sberbank-russian-housing-market",
    download_description="""
We use the data from Kaggle:

kaggle competitions download -c sberbank-russian-housing-market
mkdir -p local-data-warehouse/sberbank_housing_market_forecasting && mv sberbank-russian-housing-market.zip local-data-warehouse/sberbank_housing_market_forecasting/ && cd local-data-warehouse/sberbank_housing_market_forecasting/ && unzip sberbank-russian-housing-market.zip && rm test.csv.zip sample_submission.csv.zip data_dictionary.txt sberbank-russian-housing-market.zip
""",
    # References
    academic_reference_bibtex=r"""@misc{Herman2024HomeCreditCreditRiskModelStability,
  author = {Daniel Herman and Tomas Jelinek and Walter Reade and Maggie Demkin and Addison Howard},
  title  = {Home Credit - Credit Risk Model Stability},
  year   = {2024},
  howpublished = {\url{https://kaggle.com/competitions/home-credit-credit-risk-model-stability}},
  note   = {Kaggle competition}
}
""",
    academic_reference_bibtex_key="Herman2024HomeCreditCreditRiskModelStability",
    license="Kaggle Competition Rules",
    data_tags=["Non-IID", "Temporal", "Spatial"],
    curation_comments="""
We follow the preprocessing from TabRed (https://github.com/yandex-research/tabred/tree/main/preprocessing#sberbank-housing-market-forecasting).

- We drop two duplicated columns with the same values as other columns: "0_6_all", "7_14_all"
- We drop the ID column as it does not provide information.
- Note, the dataset contains a lot of spatial feature and even more already decoded spatial information (like distances to various points of interest).
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="price_doc",
    problem_type="regression",
    # We use RMSE instead of RMSLE from the competition as we already log scale the target
    objective_metric_name="rmse",
    time_on="timestamp",
)

## Preprocessing

In [2]:
import pandas as pd
import polars as pl
import zipfile
from pathlib import Path

# From: https://github.com/yandex-research/tabred/blob/main/preprocessing/sberbank-housing.py
data = pl.read_csv(
    zipfile.ZipFile(dataset_mold.path / 'train.csv.zip').read('train.csv'),
    null_values=["NA"],
    infer_schema_length=30_000
).with_columns(
    pl.col('timestamp').str.strptime(pl.Date)
)
data_macro = pl.read_csv(
    zipfile.ZipFile(dataset_mold.path / 'macro.csv.zip').read('macro.csv'),
    null_values=["NA"],
    infer_schema_length=30_000
).with_columns(
    pl.col('timestamp').str.strptime(pl.Date),
    pl.col('child_on_acc_pre_school').str.replace(',', '.').cast(pl.Float32, strict=False),
    pl.col('modern_education_share').str.replace(',', '.').cast(pl.Float32),
    pl.col('old_education_build_share').str.replace(',', '.').cast(pl.Float32),
).drop('provision_retail_space_modern_sqm') # this feature has one value except for nulls
data_fixup = (
    pl.read_excel(Path.cwd() / "BAD_ADDRESS_FIX.xlsx")
      .with_columns(pl.col(pl.Utf8).replace("NA", None))
)

data = data.filter(
    pl.col('kremlin_km').ne(pl.col('kremlin_km').min()) |
    pl.col('id').is_in(data_fixup['id'])
).update(data_fixup, on='id')
data = data.filter(
    pl.col('full_sq').gt(5.0) &
    pl.col('full_sq').ne(5326.0) &
    pl.col('price_doc').gt(1_000_000) &
    pl.col('price_doc').ne(2_000_000) &
    pl.col('price_doc').ne(3_000_000)
)

data = data.join(data_macro, on="timestamp")

# log scale target as in TabRed
data = data.with_columns(
    (pl.col("price_doc") / pl.col("full_sq")).log().alias("price_doc")
)

data = data.to_pandas()
cat_cols = [
    'ID_railroad_station_walk','ID_railroad_station_avto','ID_big_road1','ID_big_road2','ID_railroad_terminal','ID_bus_terminal','ecology','material','state','sub_area','product_type', 'culture_objects_top_25', 'thermal_power_plant_raion', 'incineration_raion', 'oil_chemistry_raion', 'radiation_raion', 'railroad_terminal_raion', 'big_market_raion', 'nuclear_reactor_raion', 'detention_facility_raion', 'water_1line', 'big_road1_1line', 'railroad_1line'
]
data[cat_cols] = data[cat_cols].astype("category")
data = data.drop(columns=["0_6_all", "7_14_all", "id"])
data = data.reset_index(drop=True)
df = data

/tmp/ipykernel_608303/1061013581.py:29: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  data = data.filter(

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 28,321
Columns: 387
Use sampling: False (sample size: 28,321)

Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['ttk_km', 'basketball_km', 'hospice_morgue_km', 'power_transmission_line_km', 'sadovoe_km', 'big_road2_km', 'big_road1_km', 'oil_chemistry_km', 'catering_km', 'exhibition_km']
Rows remaining as candidates after top-10 filter: 21,379 (of 28,321)

#### Duplicate Report
Total duplicate rows: 9 (0.03% of dataset)
Duplicate rows ignoring target: 20 (0.07% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,timestamp,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,state,product_type,sub_area,area_m,raion_popul,green_zone_part,indust_part,children_preschool,preschool_quota,preschool_education_centers_raion,children_school,school_quota,school_education_centers_raion,school_education_centers_top_20_raion,hospital_beds_raion,healthcare_centers_raion,university_top_20_raion,sport_objects_raion,additional_education_raion,culture_objects_top_25,culture_objects_top_25_raion,shopping_centers_raion,office_raion,thermal_power_plant_raion,incineration_raion,oil_chemistry_raion,radiation_raion,railroad_terminal_raion,big_market_raion,nuclear_reactor_raion,detention_facility_raion,full_all,male_f,female_f,young_all,young_male,young_female,work_all,work_male,work_female,ekder_all,ekder_male,ekder_female,0_6_male,0_6_female,7_14_male,7_14_female,0_17_all,0_17_male,0_17_female,16_29_all,16_29_male,16_29_female,0_13_all,0_13_male,0_13_female,raion_build_count_with_material_info,build_count_block,build_count_wood,build_count_frame,build_count_brick,build_count_monolith,build_count_panel,build_count_foam,build_count_slag,build_count_mix,raion_build_count_with_builddate_info,build_count_before_1920,build_count_1921-1945,build_count_1946-1970,build_count_1971-1995,build_count_after_1995,ID_metro,metro_min_avto,metro_km_avto,metro_min_walk,metro_km_walk,kindergarten_km,school_km,park_km,green_zone_km,industrial_km,water_treatment_km,cemetery_km,incineration_km,railroad_station_walk_km,railroad_station_walk_min,ID_railroad_station_walk,railroad_station_avto_km,railroad_station_avto_min,ID_railroad_station_avto,public_transport_station_km,public_transport_station_min_walk,water_km,water_1line,mkad_km,ttk_km,sadovoe_km,bulvar_ring_km,kremlin_km,big_road1_km,ID_big_road1,big_road1_1line,big_road2_km,ID_big_road2,railroad_km,railroad_1line,zd_vokzaly_avto_km,ID_railroad_terminal,bus_terminal_avto_km,ID_bus_terminal,oil_chemistry_km,nuclear_reactor_km,radiation_km,power_transmission_line_km,thermal_power_plant_km,ts_km,big_market_km,market_shop_km,fitness_km,swim_pool_km,ice_rink_km,stadium_km,basketball_km,hospice_morgue_km,detention_facility_km,public_healthcare_km,university_km,workplaces_km,shopping_centers_km,office_km,additional_education_km,preschool_km,big_church_km,church_synagogue_km,mosque_km,theater_km,museum_km,exhibition_km,catering_km,ecology,green_part_500,prom_part_500,office_count_500,office_sqm_500,trc_count_500,trc_sqm_500,cafe_count_500,cafe_sum_500_min_price_avg,cafe_sum_500_max_price_avg,cafe_avg_price_500,cafe_count_500_na_price,cafe_count_500_price_500,cafe_count_500_price_1000,cafe_count_500_price_1500,cafe_count_500_price_2500,cafe_count_500_price_4000,cafe_count_500_price_high,big_church_count_500,church_count_500,mosque_count_500,leisure_count_500,sport_count_500,market_count_500,green_part_1000,prom_part_1000,office_count_1000,office_sqm_1000,trc_count_1000,trc_sqm_1000,cafe_count_1000,cafe_sum_1000_min_price_avg,cafe_sum_1000_max_price_avg,cafe_avg_price_1000,cafe_count_1000_na_price,cafe_count_1000_price_500,cafe_count_1000_price_1000,cafe_count_1000_price_1500,cafe_count_1000_price_2500,cafe_count_1000_price_4000,cafe_count_1000_price_high,big_church_count_1000,church_count_1000,mosque_count_1000,leisure_count_1000,sport_count_1000,market_count_1000,green_part_1500,prom_part_1500,office_count_1500,office_sqm_1500,trc_count_1500,trc_sqm_1500,cafe_count_1500,cafe_sum_1500_min_price_avg,cafe_sum_1500_max_price_avg,cafe_avg_price_1500,cafe_count_1500_na_price,cafe_count_1500_price_500,cafe_count_1500_price_1000,cafe_count_1500_price_1500,cafe_count_1500_price_2500,cafe_count_1500_price_4000,cafe_count_1500_price_high,big_church_count_1500,church_count_1500,mosque_count_1500,leisure_count_1500,sport_count_1500,market_count_1500,green_part_2000,prom_part_2000,office_count_2000,office_sqm_2000,trc_count_2000,trc_sqm_2000,cafe_count_2000,cafe_sum_2000_min_price_avg,cafe_sum_2000_max_price_avg,cafe_avg_price_2000,cafe_count_2000_na_price,cafe_count_2000_price_500,cafe_count_2000_price_1000,cafe_count_2000_price_1500,cafe_count_2000_price_2500,cafe_count_2000_price_4000,cafe_count_2000_price_high,big_church_count_2000,church_count_2000,mosque_count_2000,leisure_count_2000,sport_count_2000,market_count_2000,green_part_3000,prom_part_3000,office_count_3000,office_sqm_3000,trc_count_3000,trc_sqm_3000,cafe_count_3000,cafe_sum_3000_min_price_avg,cafe_sum_3000_max_price_avg,cafe_avg_price_3000,cafe_count_3000_na_price,cafe_count_3000_price_500,cafe_count_3000_price_1000,cafe_count_3000_price_1500,cafe_count_3000_price_2500,cafe_count_3000_price_4000,cafe_count_3000_price_high,big_church_count_3000,church_count_3000,mosque_count_3000,leisure_count_3000,sport_count_3000,market_count_3000,green_part_5000,prom_part_5000,office_count_5000,office_sqm_5000,trc_count_5000,trc_sqm_5000,cafe_count_5000,cafe_sum_5000_min_price_avg,cafe_sum_5000_max_price_avg,cafe_avg_price_5000,cafe_count_5000_na_price,cafe_count_5000_price_500,cafe_count_5000_price_1000,cafe_count_5000_price_1500,cafe_count_5000_price_2500,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000,price_doc,oil_urals,gdp_quart,gdp_quart_growth,cpi,ppi,gdp_deflator,balance_trade,balance_trade_growth,usdrub,eurrub,brent,net_capital_export,gdp_annual,gdp_annual_growth,average_provision_of_build_contract,average_provision_of_build_contract_moscow,rts,micex,micex_rgbi_tr,micex_cbi_tr,deposits_value,deposits_growth,deposits_rate,mortgage_value,mortgage_growth,mortgage_rate,grp,grp_growth,income_per_cap,real_dispos_income_per_cap_growth,salary,salary_growth,fixed_basket,retail_trade_turnover,retail_trade_turnover_per_cap,retail_trade_turnover_growth,labor_force,unemployment,employment,invest_fixed_capital_per_cap,invest_fixed_assets,profitable_enterpr_share,unprofitable_enterpr_share,share_own_revenues,overdue_wages_per_cap,fin_res_per_cap,marriages_per_1000_cap,divorce_rate,construction_value,invest_fixed_assets_phys,pop_natural_increase,pop_migration,pop_total_inc,childbirth,mortality,housing_fund_sqm,lodging_sqm_per_cap,water_pipes_share,baths_share,sewerage_share,gas_share,hot_water_share,electric_stove_share,heating_share,old_house_share,average_life_exp,infant_mortarity_per_1000_cap,perinatal_mort_per_1000_cap,incidence_population,rent_price_4+room_bus,rent_price_3room_bus,rent_price_2room_bus,rent_price_1room_bus,rent_price_3room_eco,rent_price_2room_eco,rent_price_1room_eco,load_of_teachers_preschool_per_teacher,child_on_acc_pre_school,load_of_teachers_school_per_teacher,students_state_oneshift,modern_education_share,old_education_build_share,provision_doctors,provision_nurse,load_on_doctors,power_clinics,hospital_beds_available_per_cap,hospital_bed_occupancy_per_year,provision_retail_space_sqm,turnover_catering_per_cap,theaters_viewers_per_1000_cap,seats_theather_rfmin_per_100000_cap,museum_visitis_per_100_cap,bandwidth_sports,population_reg_sports_share,students_reg_sports_share,apartment_build,apartment_fund_sqm
0,2011-08-20,43,27.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,Investment,Bibirevo,6.407578e+06,155572,0.189727,0.000070,9576,5001.0,5,10309,11065.0,5,0,240.0,1,0,7,3,no,0,16,1,no,no,no,no,no,no,no,no,86206,40477,45729,21154,11007,10147,98207,52277,45930,36211,10580,25631,4899,4677,5463,4846,23603,12286,11317,17508,9425,8083,18654,9709,8945,211.0,25.0,0.0,0.0,0.0,2.0,184.0,0.0,0.0,0.0,211.0,0.0,0.0,0.0,206.0,5.0,1,2.590241,1.131260,13.575119,1.131260,0.145700,0.177975,2.158587,0.600973,1.080934,23.683460,1.804127,3.633334,5.419893,65.038716,1.0,5.419893,6.905893,1,0.274985,3.299822,0.992631,no,1.422391,10.918587,13.100618,13.675657,15.156211,1.422391,1,no,3.830951,5,1.305159,no,14.231961,101,24.292406,1,18.152338,5.718519,1.210027,1.062513,5.814135,4.308127,10.814172,1.676258,0.485841,3.065047,1.107594,8.148591,3.516513,2.392353,4.248036,0.974743,6.715026,0.884350,0.648488,0.637189,0.947962,0.177975,0.625783,0.628187,3.932040,14.053047,7.389498,7.023705,0.516838,good,0.00,0.00,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,1,0,7.36,0.00,1,30500,3,55600,19,527.78,888.89,708.33,1,10,4,3,1,0,0,1,2,0,0,6,1,14.27,6.92,3,39554,9,171420,34,566.67,969.70,768.18,1,14,11,6,2,0,0,1,2,0,0,7,1,11.77,15.97,9,188854,19,1244891,36,614.29,1042.86,828.57,1,15,11,6,2,1,0,1,2,0,0,10,1,11.98,13.55,12,251554,23,1419204,68,639.68,1079.37,859.52,5,21,22,16,3,1,0,2,4,0,0,21,1,13.09,13.31,29,807385,52,4036616,152,708.57,1185.71,947.14,12,39,48,40,9,4,0,13,22,1,0,52,4,11.820752,109.31,14313.7,3.3,354.0,420.7,86.721,15.459,10.1,29.0048,41.7681,108.62,0.301811,46308.5,0.045037,5.76,6.74,1575.33,1438.74,131.16,204.78,10618898,0.009740,4.1,323275,1.051914,11.84,9948.7728,0.187791,42688.6,-0.005,44898.7,0.168917,12838.36,3322.047,286.952,106.6,6643.626,0.014,0.708,73976.19863,856.424079,0.708,0.292,0.891478,53636.0,226.214157,8.5,3.8,549075.8,106.6,1.1,5.1,6.2,10.8,9.7,218.0,18.772066,99.9,99.8,99.5,43.9,95.7,55.3,99.9,0.3,75.79,6.2,5.53,715.1,136.11,77.93,62.89,47.85,41.80,36.77,29.07,793.319561,NaN,1391.710938,89.0495,NaN,NaN,65.9,99.6,8180.755454,375.8,846.0,302.0,741.0,6943,565.0,0.45356,1240.0,269768,22.37,64.12,23587.0,230310.0
1,2011-08-23,34,19.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,Investment,Nagatinskij Zaton,9.589337e+06,115352,0.372602,0.049637,6880,3119.0,5,7759,6237.0,8,0,229.0,1,0,6,1,yes,1,3,0,no,no,no,no,no,no,no,no,76284,34200,42084,15727,7925,7802,70194,35622,34572,29431,9266,20165,3466,3414,3909,3850,17700,8998,8702,15164,7571,7593,13729,6929,6800,245.0,83.0,1.0,0.0,67.0,4.0,90.0,0.0,0.0,0.0,244.0,1.0,1.0,143.0,84.0,15.0,2,0.936700,0.647337,7.620630,0.635053,0.147754,0.273345,0.550690,0.065321,0.966479,1.317476,4.655004,8.648587,3.411993,40.943917,2.0,3.641773,4.679745,2,0.065263,0.783160,0.698081,no,9.503405,3.103996,6.444333,8.132640,8.698054,2.887377,2,no,3.103996,4,0.694536,no,9.242586,32,5.706113,2,9.034642,3.489954,2.724295,1.246149,3.419574,0.725560,6.910568,3.424716,0.668364,2.000154,8.972823,6.127073,1.161579,2.543747,12.649879,1.477723,1.852560,0.686252,0.519311,0.688796,1.072315,0.273345,0.967821,0.471447,4.841544,6.829889,0.709260,2.358840,0.230287,excellent,25.14,0.00,0,0,0,0,5,860.00,1500.00,1180.00,0,1,3,0,0,1,0,0,1,0,0,0,0,26.66,0.07,2,86600,5,94065,13,615.38,1076.92,846.15,0,5,6,1,0,1,0,1,2,0,4,2,0,21.53,7.71,3,102910,7,127065,17,694.12,1205.88,950.00,0,6,7,1,2,1,0,1,5,0,4,9,0,22.37,19.25,4,165510,8,179065,21,695.24,1190.48,942.86,0,7,8,3,2,1,0,1,5,0,4,11,0,18.07,27.32,12,821986,14,491565,30,631.03,1086.21,858.62,1,11,11,4,2,1,0,1,7,0,6,19,1,10.26,27.47,66,2690465,40,2034942,177,673.81,1148.81,911.31,9,49,65,36,15,3,0,15,29,1,10,66,14,12.080910,109.31,14313.7,3.3,354.0,420.7,86.721,15.459,10.1,28.9525,41.7537,109.31,0.301811,46308.5,0.045037,5.76,6.74,1578.91,1444.11,131.45,204.92,10618898,0.009740,4.1,323275,1.051914,11.84,9948.7728,0.187791,42688.6,-0.005,44898.7,0.168917,12838.36,3322.047,286.952,106.6,6643.626,0.014,0.708,73976.19863,856.424079,0.708,0.292,0.891478,53636.0,226.214157,8.5,3.8,549075.8,106.6,1.1,5.1,6.2,10.8,9.7,218.0,18.772066,99.9,99.8,99.5,43.9,95.7,55.3,99.9,0.3,75.79,6.2,5.53,715.1,136.11,77.93,62.89,47.85,41.80,36.77,29.07,793.319561,NaN,1391.710938,89.0495,NaN,NaN,65.9,99.6,8180.755454,375.8,846.0,302.0,741.0,6943,565.0,0.45356,1240.0,269768,22.37,64.12,23587.0,230310.0
2,2011-08-27,43,29.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,Investment,Tekstil'shhiki,4.808270e+06,101708,0.112560,0.118537,5879,1463.0,4,6207,5580.0,7,0,1183.0,1,0,5,1,no,0,0,1,no,no,no,yes,no,no,no,no,101982,46076,55906,13028,6835,6193,63388,31813,31575,25292,7609,17683,3095,2784,3269,2938,14884,7821,7063,19401,9045,10356,11252,5916,5336,330.0,59.0,0.0,0.0,206.0,4.0,60.0,0.0,1.0,0.0,330.0,1.0,0.0,246.0,63.0,20.0,3,2.120999,1.637996,17.351515,1.445960,0.049102,0.158072,0.374848,0.453172,0.939275,4.912660,3.381083,11.996480,1.277658,15.331896,3.0,1.277658,1.701420,3,0.328756,3.945073,0.468265,no,5.604800,2.927487,6.963403,8.054252,9.067885,0.647250,3,no,2.927487,4,0.700691,no,9.540544,5,6.710302,3,5.777394,7.506612,0.772216,1.602183,3.682455,3.562188,5.752368,1.375443,0.733101,1.239304,1.978517,0.767569,1.952771,0.621357,7.682303,0.097144,0.841254,1.510089,1.486533,1.543049,0.391957,0.158072,3.178751,0.755946,7.922152,4.273200,3.156423,4.958214,0.190462,poor,1.67,0.00,0,0,0,0,3,666.67,1166.67,916.67,0,0,2,1,0,0,0,0,0,0,0,0,0,4.99,0.29,0,0,0,0,9,642.86,1142.86,892.86,2,0,5,2,0,0,0,0,1,0,0,5,3,9.92,6.73,0,0,1,2600,14,516.67,916.67,716.67,2,4,6,2,0,0,0,0,4,0,0,6,5,12.99,12.75,4,100200,7,52550,24,563.64,977.27,770.45,2,8,9,4,1,0,0,0,4,0,0,8,5,12.14,26.46,8,110856,7,52550,41,697.44,1192.31,944.87,2,9,17,9,3,1,0,0,11,0,0,20,6,13.69,21.58,43,1478160,35,1572990,122,702.68,1196.43,949.55,10,29,45,25,10,3,0,11,27,0,4,67,10,11.794777,109.31,14313.7,3.3,354.0,420.7,86.721,15.459,10.1,28.8082,41.7114,111.36,0.301811,46308.5,0.045037,5.76,6.74,1596.17,1458.84,131.08,204.84,10618898,0.009740,4.1,323275,1.051914,11.84,9948.7728,0.187791,42688.6,-0.005,44898.7,0.168917,12838.36,3322.047,286.952,106.6,6643.626,0.014,0.708,73976.19863,856.424079,0.708,0.292,0.891478,53636.0,226.214157,8.5,3.8,549075.8,106.6,1.1,5.1,6.2,10.8,9.7,218.0,18.772066,99.9,99.8,99.5,43.9,95.7,55.3,99.9,0.3,75.79,6.2,5.53,715.1,136.11,77.93,62.89,47.85,41.80,36.77,29.07,793.319561,NaN,1391.710938,89.0495,NaN,NaN,65.9,99.6,8180.755454,375.8,846.0,302.0,741.0,6943,565.0,0.45356,1240.0,269768,22.37,64.12,23587.0,230310.0
3,2011-09-01,89,50.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,Investment,Mitino,1.258354e+07,178473,0.194703,0.069753,13087,6839.0,9,13670,17063.0,10,0,NaN,1,0,17,6,no,0,11,4,no,no,no,no,no,no,no,no,21155,9828,11327,28563,14680,13883,120381,60040,60341,29529,9083,20446,6645,6442,7126,6544,32063,16513,15550,3292,1450,1842,24934,12782,12152,458.0,9.0,51.0,12.0,124.0,50.0,201.0,0.0,9.0,2.0,459.0,13.0,24.0,40.0,130.0,252.0,4,1.489049,0.984537,11.565624,0.963802,0.179441,0.236455,0.078090,0.106125,0.451173,15.623710,2.017080,14.317640,4.291432,51.497190,4.0,3.816045,5.271136,4,0.131597,1.579164,1.200336,no,2.677824,14.606501,17.457198,18.309433,19.487005,2.677824,1,no,2.780449,17,1.999265,no,17.478380,83,6.734618,1,27.667863,9.522538,6.348716,1.767612,11.178333,0.583025,27.892717,0.811275,0.623484,1.950317,6.483172,7.385521,4.923843,3.549558,8.789894,2.163735,10.903161,0.622272,0.599914,0.934273,0.892674,0.236455,1.031777,1.561505,15.300449,16.990677,16.041521,5.029696,0.465820,good,17.36,0.57,0,0,0,0,2,1000.00,1500.00,1250.00,0,0,0,2,0,0,0,0,0,0,0,0,0,19.25,10.35,1,11000,6,80780,12,658.33,1083.33,870.83,0,3,4,5,0,0,0,0,0,0,0,3,1,28.38,6.57,2,11000,7,89492,23,673.91,1130.43,902.17,0,5,9,8,1,0,0,1,0,0,0,9,2,32.29,5.73,2,11000,7,89492,25,660.00,1120.00,890.00,0,5,11,8,1,0,0,1,1,0,0,13,2,20.79,3.57,4,167000,12,205756,32,718.75,1218.75,968.75,0,5,14,10,3,0,0,1,2,0,0,18,3,14.18,3.89,8,244166,22,942180,61,931.58,1552.63,1242.11,4,7,21,15,11,2,1,4,4,0,0,26,3,11.899486,111.29,14313.7,3.3,353.2,434.4,86.721,15.386,10.1,28.9655,41.4014,114.29,0.599709,46308.5,0.045037,5.76,6.74,1703.86,1551.58,131.45,205.42,10720911,0.009607,4.0,386388,1.049543,11.92,9948.7728,0.187791,40311.3,-0.005,44898.7,0.168917,12856.97,3322.047,286.952,106.6,6643.626,0.014,0.708,73976.19863,856.424079,0.708,0.292,0.891478,53636.0,226.214157,8.5,3.8,549075.8,106.6,1.1,5.1,6.2,10.8,9.7,218.0,18.772066,99.9,99.8,99.5,43.9,95.7,55.3,99.9,0.3,75.79,6.2,5.53,715.1,155.22,94.02,66.28,51.15,44.25,37.73,30.63,793.319561,NaN,1391.710938,89.0495,NaN,NaN,65.9,99.6,8180.755454,375.8,846.0,302.0,741.0,6943,565.0,0.45356,1240.0,269768,22.37,64.12,23587.0,230310.0
4,2011-09-05,77,77.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,Investment,Basmannoe,8.398461e+06,108171,0.015234,0.037316,5706,3240.0,7,6748,7770.0,9,0,562.0,4,2,25,2,no,0,10,93,no,no,no,yes,yes,no,no,no,28179,13522,14657,13368,7159,6209,68043,34236,33807,26760,8563,18197,2982,2724,3664,3084,15237,8113,7124,5164,2583,2581,11631,6223,5408,746.0,48.0,0.0,0.0,643.0,16.0,35.0,0.0,3.0,1.0,746.0,371.0,114.0,146.0,62.0,53.0,5,1.257186,0.876620,8.266305,0.688859,0.247901,0.376838,0.258289,0.236214,0.392871,10.683540,2.936581,11.903910,0.853960,10.247521,5.0,1.595898,2.156284,113,0.071480,0.857764,0.820294,no,11.616653,1.721834,0.046810,0.787593,2.578671,1.721834,4,no,3.133531,10,0.084113,yes,1.595898,113,1.423428,4,6.515857,8.671016,1.638318,3.632640,4.587917,2.609420,9.155057,1.969738,0.220288,2.544696,3.975401,3.610754,0.307915,1.864637,3.779781,1.121703,0.991683,0.892668,0.429052,0.077901,0.810801,0.376838,0.378756,0.121681,2.584370,1.112486,1.800125,1.339652,0.026102,excellent,3.56,4.44,15,293699,1,45000,48,702.22,1166.67,934.44,3,17,10,11,7,0,0,1,4,0,2,3,0,3.34,8.29,46,420952,3,158200,153,763.45,1272.41,1017.93,8,39,45,39,19,2,1,7,12,0,6,7,0,4.12,4.83,93,1195735,9,445900,272,766.80,1272.73,1019.76,19,70,74,72,30,6,1,18,30,0,10,14,2,4.53,5.02,149,1625130,17,564843,483,765.93,1269.23,1017.58,28,130,129,131,50,14,1,35,61,0,17,21,3,5.06,8.62,305,3420907,60,2296870,1068,853.03,1410.45,1131.74,63,266,267,262,149,57,4,70,121,1,40,77,5,8.38,10.92,689,8404624,114,3503058,2283,853.88,1411.45,1132.66,143,566,578,552,319,108,17,135,236,2,91,195,14,12.264798,111.29,14313.7,3.3,353.2,434.4,86.721,15.386,10.1,29.4625,41.5902,110.08,0.599709,46308.5,0.045037,5.76,6.74,1617.01,1492.83,131.19,198.24,10920215,0.018590,4.0,386388,1.049543,11.92,9948.7728,0.187791,40311.3,-0.005,44898.7,0.168917,12856.97,3322.047,286.952,106.6,6643.626,0.014,0.708,73976.19863,856.424079,0.708,0.292,0.891478,53636.0,226.214157,8.5,3.8,549075.8,106.6,1.1,5.1,6.2,10.8,9.7,218.0,18.772066,99.9,99.8,99.5,43.9,95.7,55.3,99.9,0.3,75.79,6.2,5.53,715.1,155.22,94.02,66.28,51.15,44.25,37.73,30.63,793.319561,NaN,1391.710938,89.0495,NaN,NaN,65.9,99.6,8180.755454,375.8,846.0,302.0,741.0,6943,565.0,0.45356,1240.0,269768,22.37,64.12,23587.0,230310.0

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,state,category,12701.0,44.85,5.0,"3.0, 2.0, 1.0, 4.0, 33.0"
1,material,category,8851.0,31.25,6.0,"1.0, 2.0, 5.0, 4.0, 6.0, 3.0"
2,ID_railroad_station_walk,category,24.0,0.08,132.0,"24.0, 47.0, 75.0, 39.0, 42.0, 4.0, 33.0, 2.0, 18.0, 28.0"
3,product_type,category,0.0,0.00,2.0,"Investment, OwnerOccupier"
4,sub_area,category,0.0,0.00,145.0,"Poselenie Sosenskoe, Nekrasovka, Poselenie Vnukovskoe, Poselenie Moskovskij, Poselenie Voskresenskoe, Mitino, Poselenie Filimonkovskoe, Krjukovo, Poselenie Shherbinka, Mar'ino"
5,culture_objects_top_25,category,0.0,0.00,2.0,"no, yes"
6,thermal_power_plant_raion,category,0.0,0.00,2.0,"no, yes"
7,incineration_raion,category,0.0,0.00,2.0,"no, yes"
8,oil_chemistry_raion,category,0.0,0.00,2.0,"no, yes"
9,radiation_raion,category,0.0,0.00,2.0,"no, yes"
10,railroad_terminal_raion,category,0.0,0.00,2.0,"no, yes"
11,big_market_raion,category,0.0,0.00,2.0,"no, yes"
12,nuclear_reactor_raion,category,0.0,0.00,2.0,"no, yes"
13,detention_facility_raion,category,0.0,0.00,2.0,"no, yes"
14,ID_railroad_station_avto,category,0.0,0.00,132.0,"75, 105, 19, 4, 39, 24, 42, 73, 47, 2"
15,water_1line,category,0.0,0.00,2.0,"no, yes"
16,ID_big_road1,category,0.0,0.00,48.0,"1, 2, 38, 13, 4, 14, 11, 5, 3, 16"
17,big_road1_1line,category,0.0,0.00,2.0,"no, yes"
18,ID_big_road2,category,0.0,0.00,58.0,"1, 4, 27, 38, 55, 13, 39, 7, 10, 17"
19,railroad_1line,category,0.0,0.00,2.0,"no, yes"
20,ID_railroad_terminal,category,0.0,0.00,8.0,"32, 50, 5, 83, 121, 101, 97, 113"
21,ID_bus_terminal,category,0.0,0.00,14.0,"8, 1, 9, 5, 3, 14, 4, 7, 13, 2"
22,ecology,category,0.0,0.00,5.0,"no data, poor, good, satisfactory, excellent"
23,timestamp,datetime64[ms],0.0,0.00,1158.0,"2014-12-16 00:00:00, 2014-12-09 00:00:00, 2014-06-30 00:00:00, 2014-12-18 00:00:00, 2014-09-30 00:00:00, 2014-11-25 00:00:00, 2014-12-08 00:00:00, 2014-12-03 00:00:00, 2014-11-21 00:00:00, 2014-12-15 00:00:00"
24,modern_education_share,float32,5053.0,17.84,3.0,"93.08, 90.92, 95.4918"
25,old_education_build_share,float32,5053.0,17.84,3.0,"25.47, 23.14, 8.2517"
26,child_on_acc_pre_school,float32,3692.0,13.04,3.0,"16.765, 3.013, 7.311"
27,provision_retail_space_sqm,float64,23268.0,82.16,2.0,"794.0, 741.0"
28,load_of_teachers_preschool_per_teacher,float64,15786.0,55.74,3.0,"863.3948, 856.7305, 793.3196"
29,theaters_viewers_per_1000_cap,float64,15786.0,55.74,3.0,"627.0, 603.0, 565.0"
30,museum_visitis_per_100_cap,float64,15786.0,55.74,3.0,"1440.0, 1309.0, 1240.0"
31,students_reg_sports_share,float64,15786.0,55.74,3.0,"76.2, 67.85, 64.12"
32,hospital_beds_raion,float64,13665.0,48.25,79.0,"540.0, 30.0, 1046.0, 2300.0, 240.0, 1084.0, 750.0, 229.0, 645.0, 1183.0"
33,build_year,float64,12853.0,45.38,118.0,"2014.0, 2015.0, 0.0, 2013.0, 1970.0, 2016.0, 1968.0, 1969.0, 1.0, 1967.0"
34,cafe_sum_500_min_price_avg,float64,12687.0,44.80,634.0,"500.0, 1000.0, 300.0, 1500.0, 750.0, 400.0, 650.0, 954.84, 600.0, 666.67"
35,cafe_sum_500_max_price_avg,float64,12687.0,44.80,434.0,"1000.0, 1500.0, 500.0, 2500.0, 1250.0, 750.0, 1166.67, 1750.0, 1564.52, 1333.33"
36,cafe_avg_price_500,float64,12687.0,44.80,835.0,"750.0, 1250.0, 400.0, 2000.0, 575.0, 1000.0, 825.0, 1259.68, 1375.0, 800.0"
37,max_floor,float64,8851.0,31.25,48.0,"17.0, 9.0, 12.0, 5.0, 14.0, 16.0, 1.0, 25.0, 22.0, 0.0"
38,num_room,float64,8851.0,31.25,13.0,"2.0, 1.0, 3.0, 4.0, 5.0, 0.0, 6.0, 8.0, 10.0, 19.0"
39,kitch_sq,float64,8851.0,31.25,72.0,"1.0, 8.0, 5.0, 10.0, 6.0, 9.0, 0.0, 7.0, 12.0, 11.0"
40,preschool_quota,float64,6629.0,23.41,121.0,"2395.0, 6839.0, 5278.0, 10175.0, 11926.0, 1503.0, 3953.0, 1874.0, 3092.0, 5088.0"
41,school_quota,float64,6626.0,23.40,125.0,"7377.0, 17063.0, 10529.0, 21892.0, 24750.0, 5782.0, 9700.0, 6772.0, 12721.0, 6237.0"
42,cafe_sum_1000_min_price_avg,float64,6385.0,22.55,1574.0,"500.0, 1000.0, 750.0, 600.0, 400.0, 700.0, 300.0, 666.67, 660.0, 914.53"
43,cafe_sum_1000_max_price_avg,float64,6385.0,22.55,1009.0,"1000.0, 1500.0, 1750.0, 1250.0, 1166.67, 750.0, 1100.0, 500.0, 1125.0, 833.33"
44,cafe_avg_price_1000,float64,6385.0,22.55,2052.0,"750.0, 1375.0, 1250.0, 1000.0, 575.0, 400.0, 800.0, 916.67, 1207.26, 880.0"
45,life_sq,float64,6363.0,22.47,174.0,"19.0, 30.0, 18.0, 20.0, 28.0, 29.0, 44.0, 17.0, 32.0, 27.0"
46,raion_build_count_with_material_info,float64,4960.0,17.51,112.0,"43.0, 1.0, 458.0, 2.0, 372.0, 352.0, 244.0, 314.0, 217.0, 1681.0"
47,build_count_block,float64,4960.0,17.51,76.0,"3.0, 0.0, 9.0, 58.0, 55.0, 52.0, 8.0, 25.0, 14.0, 78.0"
48,build_count_wood,float64,4960.0,17.51,34.0,"0.0, 1.0, 2.0, 51.0, 5.0, 146.0, 4.0, 607.0, 11.0, 352.0"
49,build_count_frame,float64,4960.0,17.51,21.0,"0.0, 1.0, 12.0, 4.0, 11.0, 3.0, 19.0, 79.0, 25.0, 5.0"
50,build_count_brick,float64,4960.0,17.51,101.0,"0.0, 10.0, 4.0, 124.0, 16.0, 28.0, 2.0, 65.0, 105.0, 66.0"
51,build_count_monolith,float64,4960.0,17.51,33.0,"0.0, 2.0, 4.0, 3.0, 9.0, 7.0, 5.0, 8.0, 1.0, 16.0"
52,build_count_panel,float64,4960.0,17.51,91.0,"0.0, 28.0, 201.0, 123.0, 111.0, 60.0, 30.0, 41.0, 124.0, 328.0"
53,build_count_foam,float64,4960.0,17.51,4.0,"0.0, 1.0, 11.0, 2.0"
54,build_count_slag,float64,4960.0,17.51,21.0,"0.0, 1.0, 2.0, 9.0, 4.0, 17.0, 5.0, 84.0, 23.0, 3.0"
55,build_count_mix,float64,4960.0,17.51,9.0,"0.0, 1.0, 2.0, 5.0, 4.0, 9.0, 8.0, 3.0, 6.0"
56,raion_build_count_with_builddate_info,float64,4960.0,17.51,114.0,"41.0, 1.0, 459.0, 2.0, 373.0, 244.0, 352.0, 1680.0, 213.0, 175.0"
57,build_count_before_1920,float64,4960.0,17.51,29.0,"0.0, 1.0, 2.0, 4.0, 13.0, 47.0, 6.0, 34.0, 23.0, 5.0"
58,build_count_1921-1945,float64,4960.0,17.51,47.0,"0.0, 1.0, 2.0, 4.0, 20.0, 24.0, 3.0, 5.0, 299.0, 14.0"
59,build_count_1946-1970,float64,4960.0,17.51,100.0,"7.0, 0.0, 1.0, 14.0, 40.0, 184.0, 2.0, 153.0, 439.0, 246.0"
60,build_count_1971-1995,float64,4960.0,17.51,92.0,"10.0, 0.0, 131.0, 130.0, 93.0, 58.0, 42.0, 59.0, 176.0, 102.0"
61,build_count_after_1995,float64,4960.0,17.51,69.0,"23.0, 0.0, 57.0, 13.0, 20.0, 176.0, 22.0, 11.0, 252.0, 33.0"
62,cafe_sum_1500_min_price_avg,float64,4126.0,14.57,2494.0,"1000.0, 500.0, 700.0, 300.0, 600.0, 716.67, 660.0, 750.0, 650.0, 833.33"
63,cafe_sum_1500_max_price_avg,float64,4126.0,14.57,1665.0,"1000.0, 1500.0, 1750.0, 1166.67, 1250.0, 500.0, 1100.0, 1208.33, 1125.0, 900.0"
64,cafe_avg_price_1500,float64,4126.0,14.57,3203.0,"750.0, 1250.0, 1375.0, 400.0, 962.5, 1000.0, 933.33, 880.0, 825.0, 1166.67"
65,grp,float64,3064.0,10.82,4.0,"12808.5734, 11814.8974, 10666.8705, 9948.7728"
66,grp_growth,float64,3064.0,10.82,4.0,"0.0841, 0.1076, 0.0722, 0.1878"
67,real_dispos_income_per_cap_growth,float64,3064.0,10.82,4.0,"-0.079, 0.054, -0.025, -0.005"
68,profitable_enterpr_share,float64,3064.0,10.82,4.0,"0.646, 0.685, 0.702, 0.708"
69,unprofitable_enterpr_share,float64,3064.0,10.82,4.0,"0.354, 0.315, 0.298, 0.292"
70,share_own_revenues,float64,3064.0,10.82,4.0,"0.9778, 0.9698, 0.9421, 0.8915"
71,overdue_wages_per_cap,float64,3064.0,10.82,4.0,"57746.0, 84183.0, 47563.0, 53636.0"
72,fin_res_per_cap,float64,3064.0,10.82,4.0,"96.9126, 198.0047, 249.2838, 226.2142"
73,marriages_per_1000_cap,float64,3064.0,10.82,4.0,"8.3, 8.0, 7.8, 8.5"
74,divorce_rate,float64,3064.0,10.82,3.0,"3.7, 3.8, 3.6"
75,construction_value,float64,3064.0,10.82,4.0,"734697.6, 674276.8, 609729.3, 549075.8"
76,invest_fixed_assets_phys,float64,3064.0,10.82,4.0,"100.1, 107.1, 133.1, 106.6"
77,pop_migration,float64,3064.0,10.82,4.0,"5.7, 9.0, 8.9, 5.1"
78,pop_total_inc,float64,3064.0,10.82,4.0,"7.3, 10.7, 10.3, 6.2"
79,housing_fund_sqm,float64,3064.0,10.82,4.0,"234.0, 233.0, 231.0, 218.0"
80,lodging_sqm_per_cap,float64,3064.0,10.82,4.0,"19.185, 19.2435, 19.2821, 18.7721"
81,water_pipes_share,float64,3064.0,10.82,2.0,"98.8, 99.9"
82,baths_share,float64,3064.0,10.82,2.0,"98.6, 99.8"
83,sewerage_share,float64,3064.0,10.82,3.0,"98.1, 98.0, 99.5"
84,gas_share,float64,3064.0,10.82,4.0,"43.3, 43.6, 44.1, 43.9"
85,hot_water_share,float64,3064.0,10.82,3.0,"94.3, 94.4, 95.7"
86,electric_stove_share,float64,3064.0,10.82,4.0,"55.2, 54.5, 54.1, 55.3"
87,heating_share,float64,3064.0,10.82,2.0,"99.3, 99.9"
88,old_house_share,float64,3064.0,10.82,2.0,"0.4, 0.3"
89,infant_mortarity_per_1000_cap,float64,3064.0,10.82,4.0,"6.1, 7.6, 8.1, 6.2"
90,perinatal_mort_per_1000_cap,float64,3064.0,10.82,4.0,"7.61, 8.82, 10.2, 5.53"
91,incidence_population,float64,3064.0,10.82,4.0,"662.3, 684.2, 698.6, 715.1"
92,provision_doctors,float64,3064.0,10.82,4.0,"61.0, 65.2, 66.1, 65.9"
93,power_clinics,float64,3064.0,10.82,4.0,"41.9, 121.1, 156.3, 375.8"
94,hospital_beds_available_per_cap,float64,3064.0,10.82,4.0,"707.0, 772.0, 836.0, 846.0"
95,hospital_bed_occupancy_per_year,float64,3064.0,10.82,4.0,"286.0, 293.0, 298.0, 302.0"
96,population_reg_sports_share,float64,3064.0,10.82,4.0,"28.2, 26.7, 23.01, 22.37"
97,apartment_build,float64,3064.0,10.82,4.0,"46080.0, 46352.0, 42551.0, 23587.0"
98,cafe_sum_2000_min_price_avg,float64,1704.0,6.02,3379.0,"500.0, 650.0, 1000.0, 700.0, 716.67, 833.33, 660.0, 600.0, 300.0, 733.33"
99,cafe_sum_2000_max_price_avg,float64,1704.0,6.02,2323.0,"1000.0, 1500.0, 1250.0, 1166.67, 1100.0, 500.0, 1233.33, 1285.71, 800.0, 1125.0"
100,cafe_avg_price_2000,float64,1704.0,6.02,4291.0,"750.0, 825.0, 1250.0, 983.33, 1166.67, 400.0, 880.0, 933.33, 1000.0, 640.0"
101,cafe_sum_3000_min_price_avg,float64,976.0,3.45,4908.0,"1000.0, 760.0, 700.0, 500.0, 1750.0, 750.0, 833.33, 566.67, 680.0, 684.09"
102,cafe_sum_3000_max_price_avg,float64,976.0,3.45,3715.0,"1000.0, 1300.0, 1500.0, 1250.0, 1222.22, 2875.0, 1333.33, 1750.0, 1200.0, 1375.0"
103,cafe_avg_price_3000,float64,976.0,3.45,5766.0,"1030.0, 1250.0, 750.0, 2312.5, 961.11, 1000.0, 1083.33, 1375.0, 940.0, 915.91"
104,cafe_sum_5000_min_price_avg,float64,287.0,1.01,6877.0,"662.5, 700.0, 747.37, 661.54, 507.14, 783.78, 1250.0, 1114.29, 715.04, 1176.92"
105,cafe_sum_5000_max_price_avg,float64,287.0,1.01,5975.0,"1156.25, 1125.0, 1263.16, 1153.85, 857.14, 1297.3, 1857.14, 2000.0, 1203.01, 1884.62"
106,cafe_avg_price_5000,float64,287.0,1.01,7421.0,"909.38, 1005.26, 907.69, 912.5, 682.14, 1040.54, 1485.71, 1530.77, 959.02, 1625.0"
107,prom_part_5000,float64,176.0,0.62,2364.0,"6.54, 4.56, 4.75, 7.12, 6.16, 14.96, 1.32, 7.92, 4.8, 7.69"
108,floor,float64,151.0,0.53,41.0,"3.0, 2.0, 5.0, 4.0, 7.0, 1.0, 6.0, 9.0, 8.0, 12.0"
109,metro_min_walk,float64,24.0,0.08,10996.0,"45.322, 68.4029, 66.8928, 24.9254, 144.2363, 29.2426, 25.9519, 27.059, 73.8001, 0.3817"
110,metro_km_walk,float64,24.0,0.08,10996.0,"3.7768, 5.7002, 5.5744, 2.0771, 12.0197, 2.4369, 2.1627, 2.2549, 6.15, 0.0318"
111,railroad_station_walk_km,float64,24.0,0.08,10996.0,"1.9235, 7.7137, 10.7455, 4.0905, 18.4496, 5.9662, 4.8343, 5.7842, 10.0374, 3.2139"
112,railroad_station_walk_min,float64,24.0,0.08,10996.0,"23.0819, 92.5641, 128.9457, 49.0866, 221.3949, 71.5944, 58.0121, 69.4108, 120.449, 38.5664"
113,area_m,float64,0.0,0.00,145.0,"66772450.69, 11391678.48, 25536296.81, 40366999.51, 21494094.8, 12583535.69, 35747947.91, 10842309.74, 11754772.16, 7878765.473"
114,green_zone_part,float64,0.0,0.00,145.0,"0.3362, 0.0556, 0.4963, 0.4928, 0.2625, 0.1947, 0.549, 0.0622, 0.1887, 0.0571"
115,indust_part,float64,0.0,0.00,131.0,"0.0722, 0.2432, 0.0, 0.0071, 0.0758, 0.0176, 0.0698, 0.0347, 0.1615, 0.0908"
116,metro_min_avto,float64,0.0,0.00,11004.0,"4.721, 8.4586, 7.1324, 2.5964, 15.8395, 3.1215, 2.8945, 5.5953, 7.5815, 0.0596"
117,metro_km_avto,float64,0.0,0.00,11004.0,"3.7768, 6.7324, 6.5418, 2.0771, 12.7186, 2.4369, 2.1593, 2.2549, 6.15, 0.0318"
118,kindergarten_km,float64,0.0,0.00,11013.0,"0.2867, 3.8619, 3.0293, 1.1704, 4.4152, 0.7453, 0.2831, 0.6472, 3.6026, 0.5561"
119,school_km,float64,0.0,0.00,10986.0,"0.2142, 3.5327, 2.8836, 1.5457, 7.6713, 0.9363, 0.4319, 0.8261, 3.9021, 0.2491"
120,park_km,float64,0.0,0.00,11013.0,"4.6162, 6.5201, 3.4048, 4.8948, 9.6842, 1.7738, 0.5812, 1.7999, 4.4482, 0.5288"
121,green_zone_km,float64,0.0,0.00,10899.0,"0.0176, 0.0, 0.1835, 0.035, 0.2143, 0.9918, 0.4567, 0.4812, 0.3144, 0.5745"
122,industrial_km,float64,0.0,0.00,10891.0,"0.3941, 0.0, 0.2389, 0.4244, 0.1175, 1.3519, 1.0181, 0.3855, 1.0061, 0.1832"
123,water_treatment_km,float64,0.0,0.00,10990.0,"0.3878, 13.9976, 5.5236, 17.0495, 9.2113, 1.0144, 18.1276, 0.971, 5.8348, 15.8936"
124,cemetery_km,float64,0.0,0.00,10990.0,"5.6181, 2.486, 3.3591, 1.8747, 1.2529, 1.7653, 1.0557, 1.6307, 1.7805, 1.6677"
125,incineration_km,float64,0.0,0.00,10992.0,"3.1942, 18.019, 8.8004, 19.5243, 18.3675, 11.5716, 5.6849, 11.4359, 10.4765, 13.3834"
126,railroad_station_avto_km,float64,0.0,0.00,11004.0,"1.9235, 8.6238, 11.5724, 4.0905, 21.2792, 5.9662, 3.6497, 5.7842, 13.5606, 2.7385"
127,railroad_station_avto_min,float64,0.0,0.00,11004.0,"3.0507, 11.9355, 10.3832, 5.2259, 21.7653, 7.4057, 4.9446, 9.8794, 12.412, 3.533"
128,public_transport_station_km,float64,0.0,0.00,11012.0,"0.036, 0.1336, 1.4829, 0.2798, 1.7912, 0.4676, 0.1628, 0.3274, 0.1264, 0.1217"
129,public_transport_station_min_walk,float64,0.0,0.00,11013.0,"0.4318, 1.6032, 17.7945, 3.357, 21.4945, 5.6109, 1.954, 3.9283, 1.5167, 1.4608"
130,water_km,float64,0.0,0.00,11012.0,"1.1103, 1.2633, 1.3636, 0.7185, 0.2153, 0.0067, 1.4744, 0.1382, 0.3396, 0.7495"
131,mkad_km,float64,0.0,0.00,11013.0,"5.9469, 8.1848, 2.4983, 7.466, 11.7513, 7.3717, 1.0363, 7.2298, 3.6579, 1.7449"
132,ttk_km,float64,0.0,0.00,11013.0,"14.2982, 18.6864, 15.6936, 17.4634, 24.3821, 20.6241, 11.0283, 20.4835, 16.7485, 13.9259"
133,sadovoe_km,float64,0.0,0.00,11013.0,"18.4189, 21.3806, 18.7289, 20.184, 27.2714, 23.7534, 13.799, 23.6136, 19.7135, 16.7242"
134,bulvar_ring_km,float64,0.0,0.00,11013.0,"19.2725, 22.5489, 19.9452, 21.3526, 28.3851, 25.0321, 14.47, 24.8931, 20.8756, 17.5665"
135,kremlin_km,float64,0.0,0.00,11013.0,"20.5495, 23.3737, 20.6668, 22.2224, 29.1338, 25.7353, 15.869, 25.596, 21.6097, 18.7528"
136,big_road1_km,float64,0.0,0.00,11013.0,"1.9051, 0.4786, 2.2572, 2.9595, 0.4647, 4.5861, 0.5764, 4.5409, 1.165, 1.7449"
137,big_road2_km,float64,0.0,0.00,11013.0,"2.6573, 6.8868, 2.4983, 3.4741, 9.152, 5.6022, 1.0363, 5.586, 3.6579, 2.0916"
138,railroad_km,float64,0.0,0.00,11013.0,"1.2149, 3.6739, 3.9583, 1.6869, 8.6076, 1.2661, 0.0643, 1.1284, 4.3715, 1.6633"
139,zd_vokzaly_avto_km,float64,0.0,0.00,11004.0,"24.0612, 30.9277, 23.6233, 26.0543, 30.1954, 29.2545, 14.7784, 29.0725, 22.4767, 16.4008"
140,bus_terminal_avto_km,float64,0.0,0.00,11004.0,"7.2537, 15.2696, 9.9365, 17.8454, 15.1662, 10.1259, 14.614, 9.944, 7.4476, 5.6571"
141,oil_chemistry_km,float64,0.0,0.00,11013.0,"8.4834, 29.5461, 21.0784, 30.3516, 30.672, 23.5906, 21.9045, 23.4634, 22.7374, 26.8473"
142,nuclear_reactor_km,float64,0.0,0.00,11013.0,"16.3725, 18.3251, 13.6637, 17.7502, 23.3765, 17.2431, 2.3837, 17.1037, 15.2257, 8.8409"
143,radiation_km,float64,0.0,0.00,11013.0,"4.3177, 9.3011, 3.0132, 9.4178, 12.7215, 7.5762, 0.7181, 7.4365, 4.5876, 5.5093"
144,power_transmission_line_km,float64,0.0,0.00,11013.0,"6.3809, 5.6016, 0.3279, 5.8893, 9.137, 4.9266, 0.616, 4.7989, 0.9807, 0.8335"
145,thermal_power_plant_km,float64,0.0,0.00,11013.0,"9.0463, 12.1511, 8.2531, 10.3864, 17.2935, 9.9202, 1.7228, 9.7932, 9.9277, 10.3102"
146,ts_km,float64,0.0,0.00,11010.0,"5.0131, 6.0098, 4.3078, 4.0369, 13.0111, 9.6588, 1.5722, 9.5301, 5.1312, 0.6787"
147,big_market_km,float64,0.0,0.00,11004.0,"10.2642, 13.449, 5.5478, 16.0248, 11.9104, 14.3503, 15.7737, 14.7038, 4.1918, 26.8152"
148,market_shop_km,float64,0.0,0.00,11004.0,"5.4397, 9.625, 7.5607, 6.7887, 7.4805, 6.4691, 4.0346, 6.2872, 6.3221, 0.9527"
149,fitness_km,float64,0.0,0.00,10939.0,"2.4932, 1.8694, 1.4452, 1.8849, 5.9804, 0.8223, 0.9891, 0.68, 0.2526, 0.341"
150,swim_pool_km,float64,0.0,0.00,11004.0,"8.1069, 6.5078, 6.8184, 2.8766, 15.8501, 5.3749, 4.9231, 5.1929, 8.1314, 1.1244"
151,ice_rink_km,float64,0.0,0.00,11004.0,"8.6238, 6.702, 5.9108, 3.0707, 16.3871, 13.5118, 2.768, 13.3298, 8.2433, 6.9572"
152,stadium_km,float64,0.0,0.00,11004.0,"13.5918, 11.8015, 14.6494, 14.3774, 19.7468, 22.0934, 9.304, 21.9114, 12.0282, 6.308"
153,basketball_km,float64,0.0,0.00,11013.0,"5.2112, 10.5665, 5.8339, 8.6282, 15.5237, 10.1313, 3.3599, 9.9892, 7.3561, 4.1022"
154,hospice_morgue_km,float64,0.0,0.00,11013.0,"1.4519, 4.9521, 3.6409, 7.2635, 4.0929, 4.2176, 2.0542, 4.0962, 5.2473, 2.6259"
155,detention_facility_km,float64,0.0,0.00,11004.0,"12.2392, 30.313, 25.1435, 25.4397, 37.1154, 27.1637, 8.0511, 26.9817, 27.476, 7.7123"
156,public_healthcare_km,float64,0.0,0.00,11004.0,"5.4226, 6.0391, 6.032, 2.4078, 12.4781, 2.9923, 4.0483, 3.2625, 5.4383, 2.6377"
157,university_km,float64,0.0,0.00,11004.0,"8.8372, 10.7966, 11.4718, 13.3725, 16.5692, 18.9158, 4.9524, 18.7339, 8.8506, 9.8256"
158,workplaces_km,float64,0.0,0.00,11005.0,"5.5991, 9.907, 4.8263, 9.66, 13.6113, 8.9415, 3.2324, 8.8022, 6.1482, 0.2491"
159,shopping_centers_km,float64,0.0,0.00,10977.0,"2.2151, 0.9808, 3.5438, 1.4729, 7.937, 3.1723, 0.5297, 3.2315, 4.5295, 0.1795"
160,office_km,float64,0.0,0.00,10970.0,"4.7788, 0.9808, 4.3226, 0.0, 4.4456, 7.937, 5.0871, 0.8378, 5.0724, 3.5739"
161,additional_education_km,float64,0.0,0.00,11005.0,"0.2035, 0.5949, 3.6319, 1.5387, 3.9781, 1.334, 0.473, 1.2106, 4.472, 0.7129"
162,preschool_km,float64,0.0,0.00,10989.0,"0.2142, 3.5327, 2.8836, 1.5457, 7.6713, 0.9363, 0.4319, 0.8261, 3.9021, 0.2491"
163,big_church_km,float64,0.0,0.00,11013.0,"3.4683, 4.4716, 4.1601, 1.328, 9.5598, 1.715, 0.7375, 1.5824, 4.9877, 0.1714"
164,church_synagogue_km,float64,0.0,0.00,11013.0,"0.9122, 0.7436, 0.4263, 1.3234, 0.7818, 0.8224, 0.7383, 0.7561, 0.0513, 0.8548"
165,mosque_km,float64,0.0,0.00,11013.0,"11.8915, 13.1886, 3.5132, 13.0243, 10.1995, 2.9386, 6.8626, 2.7975, 4.3986, 14.3666"
166,theater_km,float64,0.0,0.00,11004.0,"9.8362, 11.3625, 14.2104, 13.9384, 19.3078, 21.6544, 19.0126, 21.4724, 11.5892, 15.9131"
167,museum_km,float64,0.0,0.00,11013.0,"7.2888, 11.3455, 11.8179, 10.2254, 18.1042, 15.0513, 9.824, 14.9173, 11.9805, 15.5089"
168,exhibition_km,float64,0.0,0.00,11013.0,"7.4022, 6.3048, 8.0792, 4.8996, 14.2483, 13.1493, 5.0702, 13.03, 8.8725, 4.0956"
169,catering_km,float64,0.0,0.00,11013.0,"1.8361, 0.5378, 1.5109, 0.3303, 0.0468, 1.4529, 1.006, 1.3149, 0.5926, 0.0804"
170,green_part_500,float64,0.0,0.00,3242.0,"0.0, 42.63, 21.17, 27.33, 15.29, 1.48, 0.11, 9.88, 17.94, 8.93"
171,prom_part_500,float64,0.0,0.00,2441.0,"0.0, 5.76, 2.83, 14.29, 1.6, 14.0, 4.07, 1.51, 3.7, 2.72"
172,green_part_1000,float64,0.0,0.00,3661.0,"21.22, 0.0, 32.38, 31.84, 34.64, 10.96, 14.96, 0.67, 13.93, 21.7"
173,prom_part_1000,float64,0.0,0.00,3053.0,"0.0, 28.43, 4.89, 2.86, 2.82, 28.59, 10.85, 4.06, 3.41, 2.92"
174,green_part_1500,float64,0.0,0.00,3845.0,"9.43, 42.82, 0.0, 38.77, 36.78, 8.47, 12.58, 14.24, 14.21, 13.83"
175,prom_part_1500,float64,0.0,0.00,3241.0,"0.0, 34.86, 1.3, 11.46, 8.26, 0.05, 1.45, 27.46, 1.42, 8.16"
176,green_part_2000,float64,0.0,0.00,3899.0,"5.3, 46.43, 41.84, 40.08, 18.54, 11.82, 13.13, 12.39, 25.06, 25.52"
177,prom_part_2000,float64,0.0,0.00,3277.0,"0.0, 26.61, 12.07, 11.87, 1.77, 0.1, 1.64, 21.76, 1.55, 7.89"
178,green_part_3000,float64,0.0,0.00,3841.0,"2.36, 56.34, 44.41, 10.62, 43.78, 40.25, 12.8, 10.54, 30.7, 25.12"
179,prom_part_3000,float64,0.0,0.00,3009.0,"13.06, 6.82, 7.22, 1.99, 1.97, 1.98, 0.43, 15.73, 5.0, 2.14"
180,green_part_5000,float64,0.0,0.00,3438.0,"4.46, 46.77, 37.13, 34.95, 17.74, 39.4, 14.78, 34.33, 17.92, 17.39"
181,price_doc,float64,0.0,0.00,13260.0,"11.9184, 12.0238, 12.2061, 11.9829, 12.0725, 11.8006, 11.7361, 11.9984, 11.8494, 11.9697"
182,oil_urals,float64,0.0,0.00,47.0,"61.2833, 107.076, 109.6476, 78.9665, 106.8776, 107.988, 107.843, 95.6732, 86.6257, 110.622"
183,gdp_quart,float64,0.0,0.00,16.0,"20406.9, 17138.9, 19566.5, 18543.5, 18884.6, 17015.1, 15891.7, 18209.7, 17442.1, 21514.7"
184,gdp_quart_growth,float64,0.0,0.00,15.0,"0.7, 0.9, 0.6, 2.1, 1.3, 1.2, -2.8, 3.1, 0.4, 2.0"
185,cpi,float64,0.0,0.00,47.0,"440.5, 415.3, 422.8, 434.9, 411.2, 408.3, 419.1, 428.6, 431.4, 403.9"
186,ppi,float64,0.0,0.00,47.0,"510.1, 496.6, 502.4, 512.5, 485.6, 487.7, 500.3, 514.7, 510.8, 480.6"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
full_sq,28321.0,5.451831e+01,2.342759e+01,6.000000e+00,7.290000e+02
life_sq,21958.0,3.491880e+01,5.457491e+01,0.000000e+00,7.478000e+03
floor,28170.0,7.743876e+00,5.354901e+00,0.000000e+00,7.700000e+01
max_floor,19470.0,1.261002e+01,6.792349e+00,0.000000e+00,9.900000e+01
build_year,15468.0,3.171396e+03,1.612137e+05,0.000000e+00,2.005201e+07
num_room,19470.0,1.914176e+00,8.575572e-01,0.000000e+00,1.900000e+01
kitch_sq,19470.0,6.253364e+00,2.564831e+01,0.000000e+00,2.014000e+03
area_m,28321.0,1.860064e+07,2.145786e+07,2.081628e+06,2.060718e+08
raion_popul,28321.0,8.166703e+04,5.895374e+04,2.546000e+03,2.474690e+05
green_zone_part,28321.0,2.255320e-01,1.772803e-01,1.879375e-03,8.529228e-01
indust_part,28321.0,1.197760e-01,1.178900e-01,0.000000e+00,5.218671e-01
children_preschool,28321.0,5.011235e+03,3.875091e+03,1.750000e+02,1.922300e+04
preschool_quota,21692.0,3.286581e+03,2.170014e+03,0.000000e+00,1.192600e+04
preschool_education_centers_raion,28321.0,3.968327e+00,3.053840e+00,0.000000e+00,1.300000e+01
children_school,28321.0,5.178637e+03,4.050257e+03,1.680000e+02,1.908300e+04
school_quota,21695.0,8.356940e+03,4.293905e+03,1.012000e+03,2.475000e+04
school_education_centers_raion,28321.0,4.594788e+00,3.508735e+00,0.000000e+00,1.400000e+01
school_education_centers_top_20_raion,28321.0,8.785001e-02,3.060956e-01,0.000000e+00,2.000000e+00
hospital_beds_raion,14656.0,1.174884e+03,1.056222e+03,0.000000e+00,4.849000e+03
healthcare_centers_raion,28321.0,1.242047e+00,1.483737e+00,0.000000e+00,6.000000e+00
university_top_20_raion,28321.0,9.713640e-02,3.555342e-01,0.000000e+00,3.000000e+00
sport_objects_raion,28321.0,5.992514e+00,5.811245e+00,0.000000e+00,2.900000e+01
additional_education_raion,28321.0,2.608877e+00,2.724720e+00,0.000000e+00,1.600000e+01
culture_objects_top_25_raion,28321.0,8.922708e-02,6.233318e-01,0.000000e+00,1.000000e+01
shopping_centers_raion,28321.0,3.716500e+00,3.953905e+00,0.000000e+00,2.300000e+01
office_raion,28321.0,5.399527e+00,1.412254e+01,0.000000e+00,1.410000e+02
full_all,28321.0,1.436098e+05,2.799830e+05,2.546000e+03,1.716730e+06
male_f,28321.0,6.599104e+04,1.280752e+05,1.208000e+03,7.745850e+05
female_f,28321.0,7.761905e+04,1.519573e+05,1.341000e+03,9.421450e+05
young_all,28321.0,1.085500e+04,8.420076e+03,3.650000e+02,4.069200e+04
young_male,28321.0,5.563327e+03,4.341843e+03,1.890000e+02,2.097700e+04
young_female,28321.0,5.291741e+03,4.085700e+03,1.770000e+02,1.971500e+04
work_all,28321.0,5.227126e+04,3.817102e+04,1.633000e+03,1.612900e+05
work_male,28321.0,2.655342e+04,1.928518e+04,8.630000e+02,7.962200e+04
work_female,28321.0,2.571794e+04,1.898146e+04,7.710000e+02,8.166800e+04
ekder_all,28321.0,1.854077e+04,1.339858e+04,5.480000e+02,5.708600e+04
ekder_male,28321.0,5.595801e+03,4.137998e+03,1.560000e+02,1.927500e+04
ekder_female,28321.0,1.294505e+04,9.301579e+03,3.930000e+02,3.781100e+04
0_6_male,28321.0,2.567044e+03,2.001986e+03,9.100000e+01,9.987000e+03
0_6_female,28321.0,2.444335e+03,1.876115e+03,8.500000e+01,9.236000e+03
7_14_male,28321.0,2.656483e+03,2.085947e+03,8.700000e+01,9.761000e+03
7_14_female,28321.0,2.522319e+03,1.970273e+03,8.200000e+01,9.322000e+03
0_17_all,28321.0,1.217933e+04,9.403418e+03,4.110000e+02,4.517000e+04
0_17_male,28321.0,6.244378e+03,4.845379e+03,2.140000e+02,2.323300e+04
0_17_female,28321.0,5.935128e+03,4.565661e+03,1.980000e+02,2.193700e+04
16_29_all,28321.0,3.078942e+04,5.974216e+04,5.750000e+02,3.676590e+05
16_29_male,28321.0,1.511830e+04,2.899854e+04,3.080000e+02,1.729580e+05
16_29_female,28321.0,1.567126e+04,3.076917e+04,2.530000e+02,1.947010e+05
0_13_all,28321.0,9.556565e+03,7.405925e+03,3.220000e+02,3.603500e+04
0_13_male,28321.0,4.896023e+03,3.818868e+03,1.660000e+02,1.857400e+04
0_13_female,28321.0,4.660551e+03,3.594255e+03,1.560000e+02,1.746100e+04
raion_build_count_with_material_info,23361.0,3.194921e+02,2.770890e+02,1.000000e+00,1.681000e+03
build_count_block,23361.0,4.926840e+01,4.689004e+01,0.000000e+00,2.230000e+02
build_count_wood,23361.0,4.109730e+01,1.269444e+02,0.000000e+00,7.930000e+02
build_count_frame,23361.0,5.071786e+00,1.535187e+01,0.000000e+00,9.700000e+01
build_count_brick,23361.0,1.005814e+02,1.196889e+02,0.000000e+00,6.640000e+02
build_count_monolith,23361.0,1.179042e+01,1.927831e+01,0.000000e+00,1.270000e+02
build_count_panel,23361.0,1.065051e+02,8.852501e+01,0.000000e+00,4.310000e+02
build_count_foam,23361.0,1.595822e-01,1.103254e+00,0.000000e+00,1.100000e+01
build_count_slag,23361.0,4.438594e+00,1.313731e+01,0.000000e+00,8.400000e+01
build_count_mix,23361.0,5.795985e-01,1.568093e+00,0.000000e+00,9.000000e+00
raion_build_count_with_builddate_info,23361.0,3.191622e+02,2.771319e+02,1.000000e+00,1.680000e+03
build_count_before_1920,23361.0,1.526968e+01,5.380275e+01,0.000000e+00,3.710000e+02
build_count_1921-1945,23361.0,2.551684e+01,6.193841e+01,0.000000e+00,3.820000e+02
build_count_1946-1970,23361.0,1.382755e+02,1.261254e+02,0.000000e+00,8.450000e+02
build_count_1971-1995,23361.0,7.914255e+01,5.856607e+01,0.000000e+00,2.460000e+02
build_count_after_1995,23361.0,6.095758e+01,1.140048e+02,0.000000e+00,7.990000e+02
ID_metro,28321.0,7.249469e+01,5.577621e+01,1.000000e+00,2.230000e+02
metro_min_avto,28321.0,5.145089e+00,6.648845e+00,0.000000e+00,6.143847e+01
metro_km_avto,28321.0,3.862203e+00,5.943810e+00,0.000000e+00,7.490576e+01
metro_min_walk,28297.0,4.476083e+01,7.110308e+01,0.000000e+00,7.112158e+02
metro_km_walk,28297.0,3.730070e+00,5.925257e+00,0.000000e+00,5.926798e+01
kindergarten_km,28321.0,1.038673e+00,2.229380e+00,4.697480e-04,2.908577e+01
school_km,28321.0,1.422361e+00,3.209607e+00,0.000000e+00,4.739471e+01
park_km,28321.0,3.259135e+00,4.030433e+00,3.737175e-03,4.735154e+01
green_zone_km,28321.0,3.012683e-01,3.014382e-01,0.000000e+00,1.982448e+00
industrial_km,28321.0,7.340732e-01,6.869615e-01,0.000000e+00,1.404816e+01
water_treatment_km,28321.0,1.107541e+01,7.139739e+00,2.741390e-01,4.759124e+01
cemetery_km,28321.0,2.304812e+00,1.472974e+00,0.000000e+00,1.577871e+01
incineration_km,28321.0,1.099750e+01,6.938196e+00,1.980710e-01,5.863205e+01
railroad_station_walk_km,28297.0,4.509524e+00,3.967418e+00,2.815276e-02,2.465304e+01
railroad_station_walk_min,28297.0,5.411429e+01,4.760901e+01,3.378331e-01,2.958365e+02
railroad_station_avto_km,28321.0,4.712463e+00,4.079311e+00,2.815276e-02,2.465398e+01
railroad_station_avto_min,28321.0,6.231996e+00,4.978311e+00,3.519094e-02,3.869192e+01
public_transport_station_km,28321.0,4.391572e-01,1.340784e+00,2.803868e-03,1.741300e+01
public_transport_station_min_walk,28321.0,5.269886e+00,1.608941e+01,3.364641e-02,2.089560e+02
water_km,28321.0,6.984806e-01,4.467401e-01,6.707311e-03,2.827709e+00
mkad_km,28321.0,6.201641e+00,5.123917e+00,1.362618e-02,5.327783e+01
ttk_km,28321.0,1.176615e+01,8.146365e+00,1.934755e-03,6.603320e+01
sadovoe_km,28321.0,1.461083e+01,8.315500e+00,3.554990e-04,6.885305e+01
bulvar_ring_km,28321.0,1.563655e+01,8.367404e+00,1.946827e-03,6.998487e+01
kremlin_km,28321.0,1.667794e+01,8.275001e+00,1.035835e-01,7.073877e+01
big_road1_km,28321.0,1.847871e+00,1.271539e+00,3.638320e-04,6.995416e+00
big_road2_km,28321.0,3.431894e+00,1.910371e+00,1.934730e-03,1.379835e+01
railroad_km,28321.0,1.918758e+00,2.029038e+00,2.299482e-03,1.665624e+01
zd_vokzaly_avto_km,28321.0,1.792564e+01,1.035437e+01,1.367154e-01,9.121506e+01
bus_terminal_avto_km,28321.0,1.023986e+01,7.390135e+00,6.202603e-02,7.479611e+01
oil_chemistry_km,28321.0,1.787970e+01,1.049370e+01,5.107099e-01,7.041343e+01
nuclear_reactor_km,28321.0,1.131321e+01,7.387479e+00,3.593362e-01,6.425696e+01
radiation_km,28321.0,4.650846e+00,5.703809e+00,4.663282e-03,5.389016e+01
power_transmission_line_km,28321.0,3.564095e+00,4.651822e+00,3.026594e-02,4.332437e+01
thermal_power_plant_km,28321.0,7.585369e+00,5.730635e+00,4.005630e-01,5.685615e+01
ts_km,28321.0,5.041220e+00,4.915106e+00,0.000000e+00,5.408091e+01
big_market_km,28321.0,1.339566e+01,8.500364e+00,6.613662e-01,5.883065e+01
market_shop_km,28321.0,4.163639e+00,3.569888e+00,3.847146e-03,4.110365e+01
fitness_km,28321.0,1.230410e+00,1.612668e+00,0.000000e+00,2.665250e+01
swim_pool_km,28321.0,4.454001e+00,4.804058e+00,0.000000e+00,5.335929e+01
ice_rink_km,28321.0,6.388093e+00,4.762857e+00,0.000000e+00,4.603720e+01
stadium_km,28321.0,9.811671e+00,7.748204e+00,1.147456e-01,8.339851e+01
basketball_km,28321.0,5.066815e+00,5.540379e+00,5.458234e-03,5.670379e+01
hospice_morgue_km,28321.0,2.780749e+00,3.072545e+00,2.516713e-03,4.369464e+01
detention_facility_km,28321.0,1.524544e+01,1.127197e+01,4.122708e-02,8.937137e+01
public_healthcare_km,28321.0,3.521703e+00,4.560793e+00,0.000000e+00,7.605514e+01
university_km,28321.0,7.247429e+00,6.931651e+00,9.307850e-04,8.486215e+01
workplaces_km,28321.0,4.213156e+00,5.102809e+00,0.000000e+00,5.527822e+01
shopping_centers_km,28321.0,1.602831e+00,2.349499e+00,0.000000e+00,2.625954e+01
office_km,28321.0,2.145920e+00,2.371015e+00,0.000000e+00,1.895893e+01
additional_education_km,28321.0,1.384468e+00,1.581012e+00,0.000000e+00,2.426821e+01
preschool_km,28321.0,1.443057e+00,3.204860e+00,0.000000e+00,4.739471e+01
big_church_km,28321.0,2.470930e+00,3.113535e+00,4.071872e-03,4.566906e+01
church_synagogue_km,28321.0,9.957640e-01,7.698878e-01,0.000000e+00,1.561573e+01
mosque_km,28321.0,7.969025e+00,5.772908e+00,5.544522e-03,4.484983e+01
theater_km,28321.0,1.003594e+01,7.234171e+00,2.678807e-02,8.760069e+01
museum_km,28321.0,7.424168e+00,5.814954e+00,7.902693e-03,5.920315e+01
exhibition_km,28321.0,5.784961e+00,5.374225e+00,8.949292e-03,5.443124e+01
catering_km,28321.0,7.300954e-01,8.547980e-01,3.566960e-04,1.216270e+01
green_part_500,28321.0,1.386837e+01,1.689218e+01,0.000000e+00,1.000000e+02
prom_part_500,28321.0,5.782852e+00,1.153185e+01,0.000000e+00,9.877000e+01
office_count_500,28321.0,5.387875e-01,1.879713e+00,0.000000e+00,3.400000e+01
office_sqm_500,28321.0,1.120472e+04,3.890970e+04,0.000000e+00,6.110150e+05
trc_count_500,28321.0,4.333180e-01,9.793475e-01,0.000000e+00,8.000000e+00
trc_sqm_500,28321.0,1.239804e+04,5.030899e+04,0.000000e+00,1.500000e+06
cafe_count_500,28321.0,2.443946e+00,6.056074e+00,0.000000e+00,1.200000e+02
cafe_sum_500_min_price_avg,15634.0,7.407406e+02,3.435100e+02,3.000000e+02,4.000000e+03
cafe_sum_500_max_price_avg,15634.0,1.246944e+03,5.303708e+02,5.000000e+02,6.000000e+03
cafe_avg_price_500,15634.0,9.938424e+02,4.356322e+02,4.000000e+02,5.000000e+03
cafe_count_500_na_price,28321.0,1.623883e-01,5.728120e-01,0.000000e+00,1.300000e+01
cafe_count_500_price_500,28321.0,6.129374e-01,1.689020e+00,0.000000e+00,3.300000e+01
cafe_count_500_price_1000,28321.0,7.561174e-01,1.774033e+00,0.000000e+00,3.900000e+01
cafe_count_500_price_1500,28321.0,5.792168e-01,1.551181e+00,0.000000e+00,2.900000e+01
cafe_count_500_price_2500,28321.0,2.642562e-01,9.582069e-01,0.000000e+00,2.200000e+01
cafe_count_500_price_4000,28321.0,5.935525e-02,4.195616e-01,0.000000e+00,1.400000e+01
cafe_count_500_price_high,28321.0,9.674800e-03,1.190459e-01,0.000000e+00,3.000000e+00
big_church_count_500,28321.0,1.267258e-01,4.509164e-01,0.000000e+00,1.100000e+01
church_count_500,28321.0,2.872074e-01,7.024939e-01,0.000000e+00,1.700000e+01
mosque_count_500,28321.0,4.660852e-03,6.811235e-02,0.000000e+00,1.000000e+00
leisure_count_500,28321.0,7.044243e-02,3.879573e-01,0.000000e+00,9.000000e+00
sport_count_500,28321.0,7.232442e-01,1.164396e+00,0.000000e+00,1.100000e+01
market_count_500,28321.0,1.019738e-01,3.784213e-01,0.000000e+00,4.000000e+00
green_part_1000,28321.0,1.746894e+01,1.485552e+01,0.000000e+00,1.000000e+02
prom_part_1000,28321.0,8.966102e+00,1.155075e+01,0.000000e+00,7.084000e+01
office_count_1000,28321.0,2.141485e+00,6.357083e+00,0.000000e+00,9.100000e+01
office_sqm_1000,28321.0,4.893620e+04,1.160991e+05,0.000000e+00,2.244723e+06
trc_count_1000,28321.0,1.569648e+00,2.005473e+00,0.000000e+00,1.900000e+01
trc_sqm_1000,28321.0,4.879028e+04,1.007055e+05,0.000000e+00,1.500000e+06
cafe_count_1000,28321.0,9.058508e+00,2.120810e+01,0.000000e+00,4.490000e+02
cafe_sum_1000_min_price_avg,21936.0,7.093776e+02,2.251868e+02,3.000000e+02,2.500000e+03
cafe_sum_1000_max_price_avg,21936.0,1.205667e+03,3.439845e+02,5.000000e+02,4.000000e+03
cafe_avg_price_1000,21936.0,9.575226e+02,2.833924e+02,4.000000e+02,3.250000e+03
cafe_count_1000_na_price,28321.0,6.185869e-01,1.654411e+00,0.000000e+00,2.800000e+01
cafe_count_1000_price_500,28321.0,2.255005e+00,5.435284e+00,0.000000e+00,1.120000e+02
cafe_count_1000_price_1000,28321.0,2.802267e+00,5.496027e+00,0.000000e+00,1.070000e+02
cafe_count_1000_price_1500,28321.0,2.153278e+00,5.151640e+00,0.000000e+00,1.040000e+02
cafe_count_1000_price_2500,28321.0,9.556513e-01,3.141767e+00,0.000000e+00,7.900000e+01
cafe_count_1000_price_4000,28321.0,2.331839e-01,1.344455e+00,0.000000e+00,4.000000e+01
cafe_count_1000_price_high,28321.0,4.053529e-02,3.032001e-01,0.000000e+00,6.000000e+00
big_church_count_1000,28321.0,4.900957e-01,1.255292e+00,0.000000e+00,2.700000e+01
church_count_1000,28321.0,1.145087e+00,1.985459e+00,0.000000e+00,3.800000e+01
mosque_count_1000,28321.0,1.881996e-02,1.358912e-01,0.000000e+00,1.000000e+00
leisure_count_1000,28321.0,2.494262e-01,1.039408e+00,0.000000e+00,3.000000e+01
sport_count_1000,28321.0,2.551993e+00,2.778433e+00,0.000000e+00,2.500000e+01
market_count_1000,28321.0,3.533067e-01,7.222457e-01,0.000000e+00,6.000000e+00
green_part_1500,28321.0,1.973181e+01,1.440074e+01,0.000000e+00,9.041000e+01
prom_part_1500,28321.0,1.081251e+01,1.100963e+01,0.000000e+00,6.300000e+01
office_count_1500,28321.0,4.881713e+00,1.360349e+01,0.000000e+00,1.720000e+02
office_sqm_1500,28321.0,1.143026e+05,2.544401e+05,0.000000e+00,2.908344e+06
trc_count_1500,28321.0,3.192719e+00,3.334834e+00,0.000000e+00,2.700000e+01
trc_sqm_1500,28321.0,1.051463e+05,1.635544e+05,0.000000e+00,1.533000e+06
cafe_count_1500,28321.0,1.953455e+01,4.466825e+01,0.000000e+00,7.840000e+02
cafe_sum_1500_min_price_avg,24195.0,7.116865e+02,1.945852e+02,3.000000e+02,2.500000e+03
cafe_sum_1500_max_price_avg,24195.0,1.202932e+03,2.944583e+02,5.000000e+02,4.000000e+03
cafe_avg_price_1500,24195.0,9.573094e+02,2.433366e+02,4.000000e+02,3.250000e+03
cafe_count_1500_na_price,28321.0,1.336676e+00,3.117932e+00,0.000000e+00,5.400000e+01
cafe_count_1500_price_500,28321.0,4.905265e+00,1.118352e+01,0.000000e+00,1.950000e+02
cafe_count_1500_price_1000,28321.0,5.874122e+00,1.130431e+01,0.000000e+00,1.770000e+02
cafe_count_1500_price_1500,28321.0,4.668373e+00,1.079046e+01,0.000000e+00,1.830000e+02
cafe_count_1500_price_2500,28321.0,2.092758e+00,6.573421e+00,0.000000e+00,1.270000e+02
cafe_count_1500_price_4000,28321.0,5.619858e-01,2.689574e+00,0.000000e+00,5.800000e+01
cafe_count_1500_price_high,28321.0,9.537093e-02,5.994172e-01,0.000000e+00,1.200000e+01
big_church_count_1500,28321.0,1.083931e+00,2.524397e+00,0.000000e+00,4.400000e+01
church_count_1500,28321.0,2.364500e+00,4.075481e+00,0.000000e+00,7.500000e+01
mosque_count_1500,28321.0,3.700434e-02,1.887757e-01,0.000000e+00,1.000000e+00
leisure_count_1500,28321.0,5.440486e-01,1.980977e+00,0.000000e+00,4.400000e+01
sport_count_1500,28321.0,5.290456e+00,5.132264e+00,0.000000e+00,3.700000e+01
market_count_1500,28321.0,7.153349e-01,1.101248e+00,0.000000e+00,7.000000e+00
green_part_2000,28321.0,2.140554e+01,1.441948e+01,1.000000e-02,7.530000e+01
prom_part_2000,28321.0,1.137608e+01,9.588202e+00,0.000000e+00,5.610000e+01
office_count_2000,28321.0,8.622683e+00,2.320618e+01,0.000000e+00,2.500000e+02
office_sqm_2000,28321.0,2.004688e+05,4.192824e+05,0.000000e+00,3.602982e+06
trc_count_2000,28321.0,5.224674e+00,4.987093e+00,0.000000e+00,3.700000e+01
trc_sqm_2000,28321.0,1.857052e+05,2.507047e+05,0.000000e+00,2.448300e+06
cafe_count_2000,28321.0,3.374807e+01,7.678517e+01,0.000000e+00,1.115000e+03
cafe_sum_2000_min_price_avg,26617.0,7.173581e+02,2.028027e+02,3.000000e+02,2.166670e+03
cafe_sum_2000_max_price_avg,26617.0,1.206411e+03,3.075864e+02,5.000000e+02,3.500000e+03
cafe_avg_price_2000,26617.0,9.618846e+02,2.540076e+02,4.000000e+02,2.833330e+03
cafe_count_2000_na_price,28321.0,2.251933e+00,5.110479e+00,0.000000e+00,7.000000e+01
cafe_count_2000_price_500,28321.0,8.453939e+00,1.902738e+01,0.000000e+00,2.780000e+02
cafe_count_2000_price_1000,28321.0,1.003471e+01,1.913749e+01,0.000000e+00,2.620000e+02
cafe_count_2000_price_1500,28321.0,8.101479e+00,1.848279e+01,0.000000e+00,2.610000e+02
cafe_count_2000_price_2500,28321.0,3.656898e+00,1.122612e+01,0.000000e+00,1.700000e+02
cafe_count_2000_price_4000,28321.0,1.069313e+00,4.528710e+00,0.000000e+00,8.100000e+01
cafe_count_2000_price_high,28321.0,1.797959e-01,9.932057e-01,0.000000e+00,1.600000e+01
big_church_count_2000,28321.0,1.899015e+00,4.247645e+00,0.000000e+00,7.000000e+01
church_count_2000,28321.0,4.152784e+00,6.896808e+00,0.000000e+00,1.080000e+02
mosque_count_2000,28321.0,6.673493e-02,2.495668e-01,0.000000e+00,1.000000e+00
leisure_count_2000,28321.0,9.743300e-01,3.274313e+00,0.000000e+00,5.500000e+01
sport_count_2000,28321.0,8.875817e+00,8.109783e+00,0.000000e+00,5.400000e+01
market_count_2000,28321.0,1.109106e+00,1.429942e+00,0.000000e+00,8.000000e+00
green_part_3000,28321.0,2.331527e+01,1.429898e+01,3.100000e-01,7.402000e+01
prom_part_3000,28321.0,1.098388e+01,7.847000e+00,0.000000e+00,4.510000e+01
office_count_3000,28321.0,1.950796e+01,4.922161e+01,0.000000e+00,4.930000e+02
office_sqm_3000,28321.0,4.369440e+05,8.378773e+05,0.000000e+00,6.106112e+06
trc_count_3000,28321.0,1.059945e+01,9.252989e+00,0.000000e+00,6.600000e+01
trc_sqm_3000,28321.0,3.976998e+05,4.346624e+05,0.000000e+00,2.654102e+06
cafe_count_3000,28321.0,7.416324e+01,1.609283e+02,0.000000e+00,1.807000e+03
cafe_sum_3000_min_price_avg,27345.0,7.682152e+02,2.317381e+02,3.000000e+02,1.833330e+03
cafe_sum_3000_max_price_avg,27345.0,1.287613e+03,3.656858e+02,5.000000e+02,3.000000e+03
cafe_avg_price_3000,27345.0,1.027914e+03,2.981896e+02,4.000000e+02,2.416670e+03
cafe_count_3000_na_price,28321.0,4.979097e+00,1.042157e+01,0.000000e+00,1.190000e+02
cafe_count_3000_price_500,28321.0,1.866915e+01,3.999058e+01,0.000000e+00,4.440000e+02
cafe_count_3000_price_1000,28321.0,2.164627e+01,4.001593e+01,0.000000e+00,4.410000e+02
cafe_count_3000_price_1500,28321.0,1.766961e+01,3.859212e+01,0.000000e+00,4.380000e+02
cafe_count_3000_price_2500,28321.0,8.228876e+00,2.305330e+01,0.000000e+00,2.660000e+02
cafe_count_3000_price_4000,28321.0,2.560220e+00,9.089965e+00,0.000000e+00,1.130000e+02
cafe_count_3000_price_high,28321.0,4.100138e-01,1.895737e+00,0.000000e+00,2.300000e+01
big_church_count_3000,28321.0,4.197027e+00,9.063828e+00,0.000000e+00,1.020000e+02
church_count_3000,28321.0,9.049822e+00,1.464400e+01,0.000000e+00,1.640000e+02
mosque_count_3000,28321.0,1.606935e-01,3.693637e-01,0.000000e+00,2.000000e+00
leisure_count_3000,28321.0,2.176618e+00,6.455767e+00,0.000000e+00,8.400000e+01
sport_count_3000,28321.0,1.820331e+01,1.643218e+01,0.000000e+00,9.900000e+01
market_count_3000,28321.0,2.164189e+00,2.230095e+00,0.000000e+00,1.000000e+01
green_part_5000,28321.0,2.331752e+01,1.135875e+01,3.520000e+00,7.546000e+01
prom_part_5000,28145.0,1.024182e+01,5.678932e+00,2.100000e-01,2.856000e+01
office_count_5000,28321.0,5.531863e+01,1.191909e+02,0.000000e+00,7.890000e+02
office_sqm_5000,28321.0,1.188459e+06,1.958702e+06,0.000000e+00,1.270211e+07
trc_count_5000,28321.0,2.776925e+01,2.205942e+01,0.000000e+00,1.200000e+02
trc_sqm_5000,28321.0,1.089786e+06,9.625890e+05,0.000000e+00,4.585477e+06
cafe_count_5000,28321.0,2.111258e+02,3.915752e+02,0.000000e+00,2.645000e+03
cafe_sum_5000_min_price_avg,28034.0,7.658675e+02,1.561204e+02,3.000000e+02,1.875000e+03
cafe_sum_5000_max_price_avg,28034.0,1.279756e+03,2.420072e+02,5.000000e+02,3.000000e+03
cafe_avg_price_5000,28034.0,1.022812e+03,1.988599e+02,4.000000e+02,2.437500e+03
cafe_count_5000_na_price,28321.0,1.425352e+01,2.536100e+01,0.000000e+00,1.740000e+02
cafe_count_5000_price_500,28321.0,5.283546e+01,9.648615e+01,0.000000e+00,6.500000e+02
cafe_count_5000_price_1000,28321.0,6.002179e+01,9.730822e+01,0.000000e+00,6.480000e+02
cafe_count_5000_price_1500,28321.0,5.034183e+01,9.389721e+01,0.000000e+00,6.410000e+02

In [7]:
# Categorical Feature Statistics
cat_stats

                                                  value  count    pct
column                    rank
ID_big_road1              1                           1   4430  15.64
                          2                           2   3455  12.20
                          3                          38   2721   9.61
                          4                          13   2704   9.55
                          5                           4   2169   7.66
ID_big_road2              1                           1   4136  14.60
                          2                           4   2376   8.39
                          3                          27   2040   7.20
                          4                          38   1204   4.25
                          5                          55   1167   4.12
ID_bus_terminal           1                           8   6966  24.60
                          2                           1   3787  13.37
                          3                           9   3328  11.75
                          4                           5   2604   9.19
                          5                           3   2085   7.36
ID_railroad_station_avto  1                          75   1702   6.01
                          2                         105   1653   5.84
                          3                          19   1583   5.59
                          4                           4   1308   4.62
                          5                          39   1301   4.59
ID_railroad_station_walk  1                        24.0   2677   9.45
                          2                        47.0   2196   7.75
                          3                        75.0   1702   6.01
                          4                        39.0   1301   4.59
                          5                        42.0   1221   4.31
ID_railroad_terminal      1                          32   8859  31.28
                          2                          50   5419  19.13
                          3                           5   5077  17.93
                          4                          83   3640  12.85
                          5                         121   1839   6.49
big_market_raion          1                          no  25547  90.21
                          2                         yes   2774   9.79
big_road1_1line           1                          no  27602  97.46
                          2                         yes    719   2.54
culture_objects_top_25    1                          no  27097  95.68
                          2                         yes   1224   4.32
detention_facility_raion  1                          no  26120  92.23
                          2                         yes   2201   7.77
ecology                   1                     no data   7813  27.59
                          2                        poor   7274  25.68
                          3                        good   6806  24.03
                          4                satisfactory   3364  11.88
                          5                   excellent   3064  10.82
incineration_raion        1                          no  25982  91.74
                          2                         yes   2339   8.26
material                  1                         1.0  13291  46.93
                          2                        <NA>   8851  31.25
                          3                         2.0   2714   9.58
                          4                         5.0   1386   4.89
                          5                         4.0   1305   4.61
nuclear_reactor_raion     1                          no  27550  97.28
                          2                         yes    771   2.72
oil_chemistry_raion       1                          no  28055  99.06
                          2                         yes    266   0.94
product_type              1                  Investment  17379  61.36
                          2               OwnerOccupier  10942  38.64
radiation_raion           1                          no  19059  67.30
                          2                         yes   9262  32.70
railroad_1line            1                          no  27485  97.05
                          2                         yes    836   2.95
railroad_terminal_raion   1                          no  27825  98.25
                          2                         yes    496   1.75
state                     1                        <NA>  12701  44.85
                          2                         3.0   5266  18.59
                          3                         2.0   5182  18.30
                          4                         1.0   4768  16.84
                          5                         4.0    403   1.42
sub_area                  1         Poselenie Sosenskoe   1821   6.43
                          2                  Nekrasovka   1702   6.01
                          3        Poselenie Vnukovskoe   1412   4.99
                          4        Poselenie Moskovskij    964   3.40
                          5     Poselenie Voskresenskoe    738   2.61
thermal_power_plant_raion 1                          no  26830  94.74
                          2                         yes   1491   5.26
timestamp                 1         2014-12-16 00:00:00    150   0.53
                          2         2014-12-09 00:00:00    136   0.48
                          3         2014-06-30 00:00:00    122   0.43
                          4         2014-12-18 00:00:00    111   0.39
                          5         2014-09-30 00:00:00     88   0.31
water_1line               1                          no  26025  91.89
                          2                         yes   2296   8.11

In [8]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,-0.944,-1.175,0.155,0.001,log,248443.5,2.724907e+17,exponential

## Task Curation

In [9]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

date_col = task_mold.time_on
target_col = task_mold.target_column_name

df = df.sort_values(by=date_col).reset_index(drop=True)

n_steps = 5
now = df[date_col].max().normalize()

splits = {}

for step in range(n_steps):
    # Move split point back by 6 months each step
    test_time_max = now - pd.DateOffset(months=6 * step) + pd.DateOffset(day=1)
    test_time_min = now - pd.DateOffset(months=6 * (step + 1))

    if step == 0:
        test_mask = df[date_col] >= test_time_min
    else:
        test_mask = (df[date_col] >= test_time_min) & (df[date_col] < test_time_max)
    # Define indices
    test_idx = df.index[test_mask].to_numpy().tolist()
    train_idx = df.index[
        df[date_col] < test_time_min
    ].to_numpy().tolist()

    # Diagnostics
    print(f"\n=== Step {step} ===")
    print("Train size:", len(train_idx), "| Test size:", len(test_idx))
    print("Train target mean:", df.loc[train_idx, target_col].mean())
    print("Test target mean:", df.loc[test_idx, target_col].mean())

    splits[step] = {0: (train_idx, test_idx)}


splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="We always use 6 month of the data as test data and all prior data as training data. This simulate a model that is refit every half year. We create 5 splits going back 6 months each, starting from the newest date.",
    splits=splits,
    time_horizon=6,
    time_horizon_unit="months",
)

=== Step 0 ===
Train size: 25229 | Test size: 3092
Train target mean: 11.771233591123726
Test target mean: 11.832385125165297

=== Step 1 ===
Train size: 18847 | Test size: 4827
Train target mean: 11.752482748951802
Test target mean: 11.81531650654064

=== Step 2 ===
Train size: 12484 | Test size: 5306
Train target mean: 11.722513816733114
Test target mean: 11.814028162807226

=== Step 3 ===
Train size: 8104 | Test size: 3586
Train target mean: 11.700659268216672
Test target mean: 11.755326186683703

=== Step 4 ===
Train size: 5038 | Test size: 2571
Train target mean: 11.716871538118392
Test target mean: 11.663313899164537

## Export

In [10]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...

Saving curated container to sberbank_housing_market_forecasting/019d7384-f3e1-7248-bbfc-f8115677fa9a

019d7384-f3e1-7248-bbfc-f8115677fa9a
ebac5616e017c7f27ac07ce36e573f84f499357d4be1af4e3367deaf14194726