### Dataset and Task Metadata

In [2]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="otto_group_product_classification_challenge",
    dataset_year="2015",
    domain_str="business & marketing",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/otto-group-product-classification-challenge",
    download_description="""
We use the train.csv from the Kaggle competition.

kaggle competitions download -c otto-group-product-classification-challenge -f train.csv && unzip train.csv.zip &&  rm train.csv.zip
mkdir -p local-data-warehouse/otto_group_product_classification_challenge && mv train.csv local-data-warehouse/otto_group_product_classification_challenge/
""",
    # References
    academic_reference_bibtex=r"""@misc{Bossan2015OttoGroupProductClassificationChallenge,
  author = {Benjamin Bossan and Josef Feigl and Wendy Kan},
  title  = {Otto Group Product Classification Challenge},
  year   = {2015},
  howpublished = {\url{https://kaggle.com/competitions/otto-group-product-classification-challenge}},
  note   = {Kaggle competition}
}
""",
    academic_reference_bibtex_key="Bossan2015OttoGroupProductClassificationChallenge",
    license="Kaggle Competition Rules",
    data_tags=["IID", "Anonymized"],
    curation_comments="""
We start with the train.csv from Kaggle.

- The data has been anonymized, so feature meanings are unknown.
- Features and data is clean. Top Kaggle experts applied no relevant preprocessing.
- We drop the index column.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="target",
    problem_type="multiclass_classification",
    objective_metric_name="log_loss",
    stratify_on="target",
)

## Preprocessing

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv(dataset_mold.path / "train.csv")
print("Loaded data shape:", df.shape)
df = df.drop(columns=["id"])

Loaded data shape: (61878, 95)

## Data Checks

In [5]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 61,878
Columns: 94

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)

Data quality checks completed.

In [6]:
# Sample Rows
df_head

,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,feat_10,feat_11,feat_12,feat_13,feat_14,feat_15,feat_16,feat_17,feat_18,feat_19,feat_20,feat_21,feat_22,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,feat_32,feat_33,feat_34,feat_35,feat_36,feat_37,feat_38,feat_39,feat_40,feat_41,feat_42,feat_43,feat_44,feat_45,feat_46,feat_47,feat_48,feat_49,feat_50,feat_51,feat_52,feat_53,feat_54,feat_55,feat_56,feat_57,feat_58,feat_59,feat_60,feat_61,feat_62,feat_63,feat_64,feat_65,feat_66,feat_67,feat_68,feat_69,feat_70,feat_71,feat_72,feat_73,feat_74,feat_75,feat_76,feat_77,feat_78,feat_79,feat_80,feat_81,feat_82,feat_83,feat_84,feat_85,feat_86,feat_87,feat_88,feat_89,feat_90,feat_91,feat_92,feat_93,target
0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,2,0,0,0,0,1,0,4,1,1,0,0,2,0,0,0,0,0,1,0,0,0,0,1,0,5,0,0,0,0,0,2,0,0,0,0,0,1,0,0,2,0,0,11,0,1,1,0,1,0,7,0,0,0,1,0,0,0,0,0,0,0,2,1,0,0,0,0,1,0,0,0,0,0,0,0,0,Class_1
1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,2,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Class_1
2,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,6,0,0,2,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Class_1
3,1,0,0,1,6,1,5,0,0,1,1,0,1,0,0,1,1,0,0,0,0,0,0,7,2,2,0,0,0,58,0,10,0,0,0,0,0,3,0,0,0,0,0,2,0,2,0,1,2,1,3,0,0,3,1,0,0,0,0,0,0,0,0,0,2,1,5,0,0,4,0,0,2,1,0,1,0,0,1,1,2,2,0,22,0,1,2,0,0,0,0,0,0,Class_1
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,3,0,0,0,0,0,0,0,4,0,1,0,0,0,1,0,0,0,0,1,0,0,0,Class_1

In [7]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,feat_1,int64,0,0.0,42,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
1,feat_2,int64,0,0.0,37,"0, 1, 2, 3, 4, 5, 6, 7, 10, 8"
2,feat_3,int64,0,0.0,48,"0, 1, 2, 3, 4, 5, 6, 8, 7, 9"
3,feat_4,int64,0,0.0,59,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
4,feat_5,int64,0,0.0,15,"0, 1, 2, 3, 4, 7, 5, 6, 10, 8"
5,feat_6,int64,0,0.0,9,"0, 1, 2, 3, 5, 4, 10, 6, 8"
6,feat_7,int64,0,0.0,30,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
7,feat_8,int64,0,0.0,55,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
8,feat_9,int64,0,0.0,40,"0, 1, 2, 3, 4, 14, 13, 12, 11, 15"
9,feat_10,int64,0,0.0,26,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
10,feat_11,int64,0,0.0,28,"0, 1, 2, 7, 8, 9, 6, 3, 10, 5"
11,feat_12,int64,0,0.0,20,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"
12,feat_13,int64,0,0.0,51,"0, 1, 2, 3, 4, 5, 10, 11, 6, 12"
13,feat_14,int64,0,0.0,32,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
14,feat_15,int64,0,0.0,37,"0, 1, 2, 3, 4, 5, 6, 7, 18, 19"
15,feat_16,int64,0,0.0,28,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
16,feat_17,int64,0,0.0,40,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
17,feat_18,int64,0,0.0,30,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"
18,feat_19,int64,0,0.0,105,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"
19,feat_20,int64,0,0.0,27,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
20,feat_21,int64,0,0.0,15,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"
21,feat_22,int64,0,0.0,21,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
22,feat_23,int64,0,0.0,24,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
23,feat_24,int64,0,0.0,66,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
24,feat_25,int64,0,0.0,28,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
25,feat_26,int64,0,0.0,31,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
26,feat_27,int64,0,0.0,55,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
27,feat_28,int64,0,0.0,21,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
28,feat_29,int64,0,0.0,50,"0, 1, 2, 3, 4, 5, 6, 8, 9, 7"
29,feat_30,int64,0,0.0,51,"0, 1, 2, 3, 4, 5, 6, 7, 11, 80"
30,feat_31,int64,0,0.0,29,"0, 1, 2, 3, 4, 5, 6, 8, 10, 7"
31,feat_32,int64,0,0.0,40,"0, 1, 2, 3, 7, 4, 6, 5, 8, 9"
32,feat_33,int64,0,0.0,20,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
33,feat_34,int64,0,0.0,49,"0, 1, 2, 3, 4, 5, 6, 8, 9, 7"
34,feat_35,int64,0,0.0,78,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
35,feat_36,int64,0,0.0,58,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
36,feat_37,int64,0,0.0,18,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
37,feat_38,int64,0,0.0,36,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
38,feat_39,int64,0,0.0,77,"0, 1, 2, 3, 4, 5, 6, 8, 7, 10"
39,feat_40,int64,0,0.0,41,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
40,feat_41,int64,0,0.0,31,"0, 1, 2, 3, 4, 5, 6, 8, 7, 10"
41,feat_42,int64,0,0.0,39,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
42,feat_43,int64,0,0.0,28,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"
43,feat_44,int64,0,0.0,26,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
44,feat_45,int64,0,0.0,76,"0, 1, 2, 3, 4, 5, 6, 9, 8, 17"
45,feat_46,int64,0,0.0,39,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
46,feat_47,int64,0,0.0,39,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"
47,feat_48,int64,0,0.0,47,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
48,feat_49,int64,0,0.0,35,"0, 1, 2, 3, 4, 5, 6, 8, 7, 9"
49,feat_50,int64,0,0.0,56,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
50,feat_51,int64,0,0.0,22,"0, 1, 2, 3, 4, 5, 6, 8, 7, 11"
51,feat_52,int64,0,0.0,36,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
52,feat_53,int64,0,0.0,42,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
53,feat_54,int64,0,0.0,53,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
54,feat_55,int64,0,0.0,26,"0, 1, 2, 3, 4, 5, 6, 7, 8, 12"
55,feat_56,int64,0,0.0,54,"0, 1, 2, 3, 4, 5, 7, 6, 12, 9"
56,feat_57,int64,0,0.0,27,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
57,feat_58,int64,0,0.0,87,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"
58,feat_59,int64,0,0.0,63,"0, 1, 2, 3, 4, 5, 6, 7, 8, 19"
59,feat_60,int64,0,0.0,39,"0, 1, 2, 12, 3, 4, 8, 13, 10, 9"
60,feat_61,int64,0,0.0,23,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
61,feat_62,int64,0,0.0,40,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
62,feat_63,int64,0,0.0,28,"0, 1, 2, 3, 4, 6, 5, 17, 7, 10"
63,feat_64,int64,0,0.0,49,"0, 1, 2, 3, 4, 5, 6, 8, 7, 10"
64,feat_65,int64,0,0.0,25,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"
65,feat_66,int64,0,0.0,34,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
66,feat_67,int64,0,0.0,72,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
67,feat_68,int64,0,0.0,39,"0, 1, 2, 3, 4, 5, 6, 7, 9, 11"
68,feat_69,int64,0,0.0,65,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
69,feat_70,int64,0,0.0,35,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
70,feat_71,int64,0,0.0,28,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
71,feat_72,int64,0,0.0,31,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
72,feat_73,int64,0,0.0,115,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
73,feat_74,int64,0,0.0,101,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
74,feat_75,int64,0,0.0,70,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
75,feat_76,int64,0,0.0,61,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
76,feat_77,int64,0,0.0,24,"0, 1, 2, 4, 3, 5, 6, 9, 27, 11"
77,feat_78,int64,0,0.0,70,"0, 1, 2, 3, 4, 5, 6, 7, 9, 8"
78,feat_79,int64,0,0.0,22,"0, 1, 2, 3, 4, 12, 5, 7, 6, 11"
79,feat_80,int64,0,0.0,41,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
80,feat_81,int64,0,0.0,19,"0, 1, 2, 3, 4, 5, 6, 7, 9, 8"
81,feat_82,int64,0,0.0,23,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
82,feat_83,int64,0,0.0,57,"0, 1, 2, 3, 4, 5, 6, 7, 10, 8"
83,feat_84,int64,0,0.0,42,"0, 1, 2, 3, 4, 6, 7, 5, 22, 38"
84,feat_85,int64,0,0.0,42,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
85,feat_86,int64,0,0.0,52,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
86,feat_87,int64,0,0.0,49,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
87,feat_88,int64,0,0.0,31,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
88,feat_89,int64,0,0.0,37,"0, 1, 2, 3, 4, 5, 6, 8, 7, 9"
89,feat_90,int64,0,0.0,91,"0, 1, 2, 3, 4, 6, 5, 7, 8, 10"
90,feat_91,int64,0,0.0,50,"0, 1, 2, 3, 4, 5, 6, 39, 8, 7"
91,feat_92,int64,0,0.0,19,"0, 1, 2, 3, 4, 5, 6, 7, 9, 8"
92,feat_93,int64,0,0.0,43,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
93,target,object,0,0.0,9,"Class_2, Class_6, Class_8, Class_3, Class_9, Class_7, Class_5, Class_4, Class_1"

In [8]:
# Numeric Feature Statistics
numeric_stats

           count      mean       std  min    max
feat_1   61878.0  0.386680  1.525330  0.0   61.0
feat_2   61878.0  0.263066  1.252073  0.0   51.0
feat_3   61878.0  0.901467  2.934818  0.0   64.0
feat_4   61878.0  0.779081  2.788005  0.0   70.0
feat_5   61878.0  0.071043  0.438902  0.0   19.0
feat_6   61878.0  0.025696  0.215333  0.0   10.0
feat_7   61878.0  0.193704  1.030102  0.0   38.0
feat_8   61878.0  0.662433  2.255770  0.0   76.0
feat_9   61878.0  1.011296  3.474822  0.0   43.0
feat_10  61878.0  0.263906  1.083340  0.0   30.0
feat_11  61878.0  1.252869  3.042333  0.0   38.0
feat_12  61878.0  0.140874  0.567089  0.0   30.0
feat_13  61878.0  0.480979  2.014697  0.0   72.0
feat_14  61878.0  1.696693  3.163212  0.0   33.0
feat_15  61878.0  1.284398  3.862236  0.0   46.0
feat_16  61878.0  1.413459  2.226163  0.0   37.0
feat_17  61878.0  0.366108  1.477436  0.0   43.0
feat_18  61878.0  0.575423  1.335985  0.0   32.0
feat_19  61878.0  0.551699  4.636145  0.0  121.0
feat_20  61878.0  0.471525  1.438727  0.0   27.0
feat_21  61878.0  0.204014  0.696050  0.0   14.0
feat_22  61878.0  0.729969  1.446220  0.0   22.0
feat_23  61878.0  0.142522  0.782979  0.0   64.0
feat_24  61878.0  2.643880  4.629015  0.0  263.0
feat_25  61878.0  1.534520  2.332994  0.0   30.0
feat_26  61878.0  0.563108  1.710305  0.0   33.0
feat_27  61878.0  0.696613  2.873222  0.0  123.0
feat_28  61878.0  0.238970  0.828112  0.0   22.0
feat_29  61878.0  0.275768  1.901294  0.0   69.0
feat_30  61878.0  0.150312  1.640880  0.0   87.0
feat_31  61878.0  0.148680  0.897354  0.0   59.0
feat_32  61878.0  1.043796  2.416849  0.0  149.0
feat_33  61878.0  0.696516  1.310202  0.0   24.0
feat_34  61878.0  0.946411  3.368622  0.0   84.0
feat_35  61878.0  0.666263  3.197965  0.0  105.0
feat_36  61878.0  0.709089  2.555119  0.0   84.0
feat_37  61878.0  0.263632  0.756934  0.0   22.0
feat_38  61878.0  0.582129  1.602579  0.0   39.0
feat_39  61878.0  0.485585  3.298315  0.0   78.0
feat_40  61878.0  1.653059  3.299798  0.0   41.0
feat_41  61878.0  0.303468  1.085672  0.0   36.0
feat_42  61878.0  0.698019  1.961189  0.0   41.0
feat_43  61878.0  0.451146  1.706013  0.0   42.0
feat_44  61878.0  0.560829  1.346090  0.0   34.0
feat_45  61878.0  0.238130  2.587131  0.0   80.0
feat_46  61878.0  0.641375  2.348359  0.0   41.0
feat_47  61878.0  0.249669  1.446203  0.0   47.0
feat_48  61878.0  1.584893  2.577071  0.0   49.0
feat_49  61878.0  0.348314  1.369380  0.0   81.0
feat_50  61878.0  0.324283  1.720470  0.0   73.0
feat_51  61878.0  0.053298  0.513820  0.0   44.0
feat_52  61878.0  0.213485  1.044788  0.0   48.0
feat_53  61878.0  0.442063  2.006485  0.0   53.0
feat_54  61878.0  2.072465  4.113319  0.0   63.0
feat_55  61878.0  0.323120  0.998743  0.0   27.0
feat_56  61878.0  0.303775  1.925806  0.0   62.0
feat_57  61878.0  0.309108  1.082148  0.0   30.0
feat_58  61878.0  0.697970  3.983722  0.0  117.0
feat_59  61878.0  0.388603  2.577693  0.0   97.0
feat_60  61878.0  1.029930  3.028469  0.0   40.0
feat_61  61878.0  0.239746  1.017553  0.0   38.0
feat_62  61878.0  1.187563  2.666742  0.0   56.0
feat_63  61878.0  0.168590  0.946158  0.0   51.0
feat_64  61878.0  1.256796  3.402080  0.0   73.0
feat_65  61878.0  0.222228  0.783052  0.0   38.0
feat_66  61878.0  0.571706  1.361874  0.0   36.0
feat_67  61878.0  2.897653  4.974322  0.0  104.0
feat_68  61878.0  0.392902  1.761054  0.0  109.0
feat_69  61878.0  0.811128  4.111091  0.0   76.0
feat_70  61878.0  0.892789  1.941368  0.0   46.0
feat_71  61878.0  0.319290  1.162443  0.0   31.0
feat_72  61878.0  0.858722  2.411646  0.0   30.0
feat_73  61878.0  0.591050  5.783233  0.0  352.0
feat_74  61878.0  0.579851  3.757822  0.0  231.0
feat_75  61878.0  0.726817  3.200095  0.0   80.0
feat_76  61878.0  0.748457  2.920038  0.0  102.0
feat_77  61878.0  0.124196  0.906621  0.0   29.0
feat_78  61878.0  0.366415  2.778317  0.0   80.0
feat_79  61878.0  0.300446  1.285569  0.0   25.0
feat_80  61878.0  0.698067  2.245671  0.0   54.0
feat_81  61878.0  0.078461  0.461244  0.0   26.0
feat_82  61878.0  0.187983  0.836269  0.0   24.0
feat_83  61878.0  0.496719  2.434921  0.0   79.0
feat_84  61878.0  0.070752  1.151460  0.0   76.0
feat_85  61878.0  0.532306  1.900438  0.0   55.0
feat_86  61878.0  1.128576  2.681554  0.0   65.0
feat_87  61878.0  0.393549  1.575455  0.0   67.0
feat_88  61878.0  0.874915  2.115466  0.0   30.0
feat_89  61878.0  0.457772  1.527385  0.0   61.0
feat_90  61878.0  0.812421  4.597804  0.0  130.0
feat_91  61878.0  0.264941  2.045646  0.0   52.0
feat_92  61878.0  0.380119  0.982385  0.0   19.0
feat_93  61878.0  0.126135  1.201720  0.0   87.0

In [9]:
# Categorical Feature Statistics
cat_stats

               value  count    pct
column rank
target 1     Class_2  16122  26.05
       2     Class_6  14135  22.84
       3     Class_8   8464  13.68
       4     Class_3   8004  12.94
       5     Class_9   4955   8.01

In [10]:
# Target Distribution
target_df

         count    pct
target
Class_2  16122  26.05
Class_6  14135  22.84
Class_8   8464  13.68
Class_3   8004  12.94
Class_9   4955   8.01
Class_7   2839   4.59
Class_5   2739   4.43
Class_4   2691   4.35
Class_1   1929   3.12

## Task Curation

In [11]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [12]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [13]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019c10cf-1388-7c7b-a68b-5ebb4df6f33a
1bd7e65397ac17eb04624b9a7db8e5feef719b3a27d6d05e5f5fe83c5dc0a79d