### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="mercedes_benz_greener_manufacturing",
    dataset_year="2017",
    domain_str="industry & manufacturing",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/mercedes-benz-greener-manufacturing",
    download_description="""
We use the train.csv from the Kaggle competition.

kaggle competitions download -c mercedes-benz-greener-manufacturing -f train.csv.zip && unzip train.csv.zip &&  rm train.csv.zip
mkdir -p local-data-warehouse/mercedes_benz_greener_manufacturing && mv train.csv local-data-warehouse/mercedes_benz_greener_manufacturing/
""",
    # References
    academic_reference_bibtex=r"""@misc{Novy2017MercedesBenzGreenerManufacturing,
  author = {Alexander Novy and CH1Mercedes and Christian Drescher and Christian Pfaundler and KOESIM and Will Cukierski},
  title  = {Mercedes-Benz Greener Manufacturing},
  year   = {2017},
  howpublished = {\url{https://kaggle.com/competitions/mercedes-benz-greener-manufacturing}},
  note   = {Kaggle competition}
}
""",
    academic_reference_bibtex_key="Novy2017MercedesBenzGreenerManufacturing",
    license="Kaggle Competition Rules",
    data_tags=["Non-IID", "Anonymized"],
    curation_comments="""
We start with the train.csv from Kaggle.

- The data has been anonymized, so feature meanings are unknown.
- There is generally weird behavior related to the ID and potentially a time column (see X5 here https://www.kaggle.com/competitions/mercedes-benz-greener-manufacturing/discussion/34949). However, it is hard to parse the exact details due to anonymization. We generally take from this that the data is sorted sequentially by ID and that there may be time dependencies. Also checkout https://www.kaggle.com/code/sudalairajkumar/simple-exploration-notebook-mercedes which shows relation between index and y, showing that y goes up with higher index and it shows that X5 (the time group feature), has the highest importance. Plus, it has one outlier.
- We remove the one outlier from y.
- We drop X5 as it leaks time group information in temporal splits (besides having a full categorical-value distribution shift with a temporal split).
- We tread the ID as a time_index.
- Some of the other constructed features (X0-X8) may leak across time as well. We remove all of them for which we do not have an explanation from experts on Kaggle.
- There are exactly 4 rows that have value that is not equal to "d" in column "X4". This indicates some kind of sub-group or data different. Given the lack of semantics and anonymity, we cannot parse the meaning of "X4". Thus, to avoid this being an indicator of data leakage, we remove these rows and subsequently drop "X4" as well.
- We drop other constructed features from up to X10 for which we have no information about them and they may leak group information across rows.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="y",
    problem_type="regression",
    objective_metric_name="rmse", # r2 in competition, which is inferior to rmse for regression tasks
    time_on="time_index",
)

## Preprocessing

In [6]:
import pandas as pd

df = pd.read_csv(dataset_mold.path / "train.csv")
print("Loaded data shape:", df.shape)

# Remove on huge y outlier that seems like a clear shift case
df = df[df["y"] < 180]

# Handle constructed features: ['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']
#   - X0,X1,X2 likely only uses information per row
#   - X4 has 4 rows that are not "d", we drop these rows to avoid leakage and later drop X4
#   - X5, time group feature that leaks group time info in temporal splits
#   - X8 seems to leak group information across rows by having value assigned based on sampling from the distribution of all data, so we drop it as well
#   - We have no further information about X3 and X6, so we drop them as well to be safe, given the trend of other constructed features leaking info across rows.
#   - We drop X11 as it is a constant feature after preprocessing.
df = df[df["X4"] == "d"]

df = df.drop(columns=["X5", "X8", "X4", "X3", "X6", "X11"])
df = df.rename(columns={"ID": "time_index"})
df = df.reset_index(drop=True)

# All X features are binary/categorical
as_cat_type = [c for c in list(df) if c.startswith("X")]
df[as_cat_type] = df[as_cat_type].astype("category")

Loaded data shape: (4209, 378)

## Data Checks

In [7]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 4,204
Columns: 372

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)

Data quality checks completed.

In [8]:
# Sample Rows
df_head

,time_index,y,X0,X1,X2,X10,X12,X13,X14,X15,X16,X17,X18,X19,X20,X21,X22,X23,X24,X26,X27,X28,X29,X30,X31,X32,X33,X34,X35,X36,X37,X38,X39,X40,X41,X42,X43,X44,X45,X46,X47,X48,X49,X50,X51,X52,X53,X54,X55,X56,X57,X58,X59,X60,X61,X62,X63,X64,X65,X66,X67,X68,X69,X70,X71,X73,X74,X75,X76,X77,X78,X79,X80,X81,X82,X83,X84,X85,X86,X87,X88,X89,X90,X91,X92,X93,X94,X95,X96,X97,X98,X99,X100,X101,X102,X103,X104,X105,X106,X107,X108,X109,X110,X111,X112,X113,X114,X115,X116,X117,X118,X119,X120,X122,X123,X124,X125,X126,X127,X128,X129,X130,X131,X132,X133,X134,X135,X136,X137,X138,X139,X140,X141,X142,X143,X144,X145,X146,X147,X148,X150,X151,X152,X153,X154,X155,X156,X157,X158,X159,X160,X161,X162,X163,X164,X165,X166,X167,X168,X169,X170,X171,X172,X173,X174,X175,X176,X177,X178,X179,X180,X181,X182,X183,X184,X185,X186,X187,X189,X190,X191,X192,X194,X195,X196,X197,X198,X199,X200,X201,X202,X203,X204,X205,X206,X207,X208,X209,X210,X211,X212,X213,X214,X215,X216,X217,X218,X219,X220,X221,X222,X223,X224,X225,X226,X227,X228,X229,X230,X231,X232,X233,X234,X235,X236,X237,X238,X239,X240,X241,X242,X243,X244,X245,X246,X247,X248,X249,X250,X251,X252,X253,X254,X255,X256,X257,X258,X259,X260,X261,X262,X263,X264,X265,X266,X267,X268,X269,X270,X271,X272,X273,X274,X275,X276,X277,X278,X279,X280,X281,X282,X283,X284,X285,X286,X287,X288,X289,X290,X291,X292,X293,X294,X295,X296,X297,X298,X299,X300,X301,X302,X304,X305,X306,X307,X308,X309,X310,X311,X312,X313,X314,X315,X316,X317,X318,X319,X320,X321,X322,X323,X324,X325,X326,X327,X328,X329,X330,X331,X332,X333,X334,X335,X336,X337,X338,X339,X340,X341,X342,X343,X344,X345,X346,X347,X348,X349,X350,X351,X352,X353,X354,X355,X356,X357,X358,X359,X360,X361,X362,X363,X364,X365,X366,X367,X368,X369,X370,X371,X372,X373,X374,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,1,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0,1,1,1,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [9]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,X0,category,0,0.0,47,"z, ak, y, ay, t, x, o, f, n, w"
1,X1,category,0,0.0,27,"aa, s, b, l, v, r, i, a, c, o"
2,X2,category,0,0.0,44,"as, ae, ai, m, ak, r, n, s, f, e"
3,X10,category,0,0.0,2,"0, 1"
4,X12,category,0,0.0,2,"0, 1"
5,X13,category,0,0.0,2,"0, 1"
6,X14,category,0,0.0,2,"0, 1"
7,X15,category,0,0.0,2,"0, 1"
8,X16,category,0,0.0,2,"0, 1"
9,X17,category,0,0.0,2,"0, 1"
10,X18,category,0,0.0,2,"0, 1"
11,X19,category,0,0.0,2,"0, 1"
12,X20,category,0,0.0,2,"0, 1"
13,X21,category,0,0.0,2,"0, 1"
14,X22,category,0,0.0,2,"0, 1"
15,X23,category,0,0.0,2,"0, 1"
16,X24,category,0,0.0,2,"0, 1"
17,X26,category,0,0.0,2,"0, 1"
18,X27,category,0,0.0,2,"1, 0"
19,X28,category,0,0.0,2,"0, 1"
20,X29,category,0,0.0,2,"0, 1"
21,X30,category,0,0.0,2,"0, 1"
22,X31,category,0,0.0,2,"0, 1"
23,X32,category,0,0.0,2,"0, 1"
24,X33,category,0,0.0,2,"0, 1"
25,X34,category,0,0.0,2,"0, 1"
26,X35,category,0,0.0,2,"0, 1"
27,X36,category,0,0.0,2,"0, 1"
28,X37,category,0,0.0,2,"0, 1"
29,X38,category,0,0.0,2,"0, 1"
30,X39,category,0,0.0,2,"0, 1"
31,X40,category,0,0.0,2,"0, 1"
32,X41,category,0,0.0,2,"0, 1"
33,X42,category,0,0.0,2,"0, 1"
34,X43,category,0,0.0,2,"0, 1"
35,X44,category,0,0.0,2,"0, 1"
36,X45,category,0,0.0,2,"0, 1"
37,X46,category,0,0.0,2,"1, 0"
38,X47,category,0,0.0,2,"0, 1"
39,X48,category,0,0.0,2,"0, 1"
40,X49,category,0,0.0,2,"0, 1"
41,X50,category,0,0.0,2,"0, 1"
42,X51,category,0,0.0,2,"1, 0"
43,X52,category,0,0.0,2,"0, 1"
44,X53,category,0,0.0,2,"0, 1"
45,X54,category,0,0.0,2,"0, 1"
46,X55,category,0,0.0,2,"0, 1"
47,X56,category,0,0.0,2,"0, 1"
48,X57,category,0,0.0,2,"0, 1"
49,X58,category,0,0.0,2,"1, 0"
50,X59,category,0,0.0,2,"0, 1"
51,X60,category,0,0.0,2,"0, 1"
52,X61,category,0,0.0,2,"1, 0"
53,X62,category,0,0.0,2,"0, 1"
54,X63,category,0,0.0,2,"0, 1"
55,X64,category,0,0.0,2,"0, 1"
56,X65,category,0,0.0,2,"0, 1"
57,X66,category,0,0.0,2,"0, 1"
58,X67,category,0,0.0,2,"0, 1"
59,X68,category,0,0.0,2,"0, 1"
60,X69,category,0,0.0,2,"0, 1"
61,X70,category,0,0.0,2,"1, 0"
62,X71,category,0,0.0,2,"0, 1"
63,X73,category,0,0.0,2,"0, 1"
64,X74,category,0,0.0,2,"1, 0"
65,X75,category,0,0.0,2,"0, 1"
66,X76,category,0,0.0,2,"0, 1"
67,X77,category,0,0.0,2,"0, 1"
68,X78,category,0,0.0,2,"0, 1"
69,X79,category,0,0.0,2,"0, 1"
70,X80,category,0,0.0,2,"1, 0"
71,X81,category,0,0.0,2,"0, 1"
72,X82,category,0,0.0,2,"0, 1"
73,X83,category,0,0.0,2,"0, 1"
74,X84,category,0,0.0,2,"0, 1"
75,X85,category,0,0.0,2,"0, 1"
76,X86,category,0,0.0,2,"0, 1"
77,X87,category,0,0.0,2,"0, 1"
78,X88,category,0,0.0,2,"0, 1"
79,X89,category,0,0.0,2,"0, 1"
80,X90,category,0,0.0,2,"0, 1"
81,X91,category,0,0.0,2,"0, 1"
82,X92,category,0,0.0,2,"0, 1"
83,X93,category,0,0.0,1,0
84,X94,category,0,0.0,2,"0, 1"
85,X95,category,0,0.0,2,"0, 1"
86,X96,category,0,0.0,2,"1, 0"
87,X97,category,0,0.0,2,"0, 1"
88,X98,category,0,0.0,2,"1, 0"
89,X99,category,0,0.0,2,"0, 1"
90,X100,category,0,0.0,2,"1, 0"
91,X101,category,0,0.0,2,"1, 0"
92,X102,category,0,0.0,2,"0, 1"
93,X103,category,0,0.0,2,"1, 0"
94,X104,category,0,0.0,2,"0, 1"
95,X105,category,0,0.0,2,"0, 1"
96,X106,category,0,0.0,2,"0, 1"
97,X107,category,0,0.0,1,0
98,X108,category,0,0.0,2,"0, 1"
99,X109,category,0,0.0,2,"0, 1"
100,X110,category,0,0.0,2,"0, 1"
101,X111,category,0,0.0,2,"1, 0"
102,X112,category,0,0.0,2,"0, 1"
103,X113,category,0,0.0,2,"0, 1"
104,X114,category,0,0.0,2,"0, 1"
105,X115,category,0,0.0,2,"0, 1"
106,X116,category,0,0.0,2,"0, 1"
107,X117,category,0,0.0,2,"0, 1"
108,X118,category,0,0.0,2,"1, 0"
109,X119,category,0,0.0,2,"1, 0"
110,X120,category,0,0.0,2,"1, 0"
111,X122,category,0,0.0,2,"0, 1"
112,X123,category,0,0.0,2,"0, 1"
113,X124,category,0,0.0,2,"0, 1"
114,X125,category,0,0.0,2,"0, 1"
115,X126,category,0,0.0,2,"0, 1"
116,X127,category,0,0.0,2,"0, 1"
117,X128,category,0,0.0,2,"1, 0"
118,X129,category,0,0.0,2,"0, 1"
119,X130,category,0,0.0,2,"0, 1"
120,X131,category,0,0.0,2,"0, 1"
121,X132,category,0,0.0,2,"1, 0"
122,X133,category,0,0.0,2,"0, 1"
123,X134,category,0,0.0,2,"0, 1"
124,X135,category,0,0.0,2,"0, 1"
125,X136,category,0,0.0,2,"1, 0"
126,X137,category,0,0.0,2,"1, 0"
127,X138,category,0,0.0,2,"0, 1"
128,X139,category,0,0.0,2,"0, 1"
129,X140,category,0,0.0,2,"0, 1"
130,X141,category,0,0.0,2,"0, 1"
131,X142,category,0,0.0,2,"1, 0"
132,X143,category,0,0.0,2,"0, 1"
133,X144,category,0,0.0,2,"1, 0"
134,X145,category,0,0.0,2,"0, 1"
135,X146,category,0,0.0,2,"0, 1"
136,X147,category,0,0.0,2,"0, 1"
137,X148,category,0,0.0,2,"0, 1"
138,X150,category,0,0.0,2,"1, 0"
139,X151,category,0,0.0,2,"0, 1"
140,X152,category,0,0.0,2,"0, 1"
141,X153,category,0,0.0,2,"0, 1"
142,X154,category,0,0.0,2,"0, 1"
143,X155,category,0,0.0,2,"0, 1"
144,X156,category,0,0.0,2,"1, 0"
145,X157,category,0,0.0,2,"0, 1"
146,X158,category,0,0.0,2,"0, 1"
147,X159,category,0,0.0,2,"0, 1"
148,X160,category,0,0.0,2,"0, 1"
149,X161,category,0,0.0,2,"0, 1"
150,X162,category,0,0.0,2,"0, 1"
151,X163,category,0,0.0,2,"0, 1"
152,X164,category,0,0.0,2,"0, 1"
153,X165,category,0,0.0,2,"0, 1"
154,X166,category,0,0.0,2,"0, 1"
155,X167,category,0,0.0,2,"0, 1"
156,X168,category,0,0.0,2,"0, 1"
157,X169,category,0,0.0,2,"0, 1"
158,X170,category,0,0.0,2,"0, 1"
159,X171,category,0,0.0,2,"1, 0"
160,X172,category,0,0.0,2,"0, 1"
161,X173,category,0,0.0,2,"0, 1"
162,X174,category,0,0.0,2,"0, 1"
163,X175,category,0,0.0,2,"0, 1"
164,X176,category,0,0.0,2,"0, 1"
165,X177,category,0,0.0,2,"0, 1"
166,X178,category,0,0.0,2,"1, 0"
167,X179,category,0,0.0,2,"0, 1"
168,X180,category,0,0.0,2,"0, 1"
169,X181,category,0,0.0,2,"0, 1"
170,X182,category,0,0.0,2,"0, 1"
171,X183,category,0,0.0,2,"0, 1"
172,X184,category,0,0.0,2,"0, 1"
173,X185,category,0,0.0,2,"0, 1"
174,X186,category,0,0.0,2,"1, 0"
175,X187,category,0,0.0,2,"0, 1"
176,X189,category,0,0.0,2,"1, 0"
177,X190,category,0,0.0,2,"0, 1"
178,X191,category,0,0.0,2,"0, 1"
179,X192,category,0,0.0,2,"0, 1"
180,X194,category,0,0.0,2,"0, 1"
181,X195,category,0,0.0,2,"0, 1"
182,X196,category,0,0.0,2,"0, 1"
183,X197,category,0,0.0,2,"0, 1"
184,X198,category,0,0.0,2,"0, 1"
185,X199,category,0,0.0,2,"0, 1"
186,X200,category,0,0.0,2,"0, 1"
187,X201,category,0,0.0,2,"0, 1"
188,X202,category,0,0.0,2,"0, 1"
189,X203,category,0,0.0,2,"0, 1"
190,X204,category,0,0.0,2,"0, 1"
191,X205,category,0,0.0,2,"1, 0"
192,X206,category,0,0.0,2,"0, 1"
193,X207,category,0,0.0,2,"0, 1"
194,X208,category,0,0.0,2,"0, 1"
195,X209,category,0,0.0,2,"1, 0"
196,X210,category,0,0.0,2,"0, 1"
197,X211,category,0,0.0,2,"0, 1"
198,X212,category,0,0.0,2,"0, 1"
199,X213,category,0,0.0,2,"0, 1"
200,X214,category,0,0.0,2,"0, 1"
201,X215,category,0,0.0,2,"0, 1"
202,X216,category,0,0.0,2,"0, 1"
203,X217,category,0,0.0,2,"0, 1"
204,X218,category,0,0.0,2,"0, 1"
205,X219,category,0,0.0,2,"0, 1"
206,X220,category,0,0.0,2,"1, 0"
207,X221,category,0,0.0,2,"0, 1"
208,X222,category,0,0.0,2,"0, 1"
209,X223,category,0,0.0,2,"1, 0"
210,X224,category,0,0.0,2,"0, 1"
211,X225,category,0,0.0,2,"0, 1"
212,X226,category,0,0.0,2,"0, 1"
213,X227,category,0,0.0,2,"0, 1"
214,X228,category,0,0.0,2,"0, 1"
215,X229,category,0,0.0,2,"1, 0"
216,X230,category,0,0.0,2,"0, 1"
217,X231,category,0,0.0,2,"0, 1"
218,X232,category,0,0.0,2,"0, 1"
219,X233,category,0,0.0,1,0
220,X234,category,0,0.0,2,"0, 1"
221,X235,category,0,0.0,1,0
222,X236,category,0,0.0,2,"0, 1"
223,X237,category,0,0.0,2,"0, 1"
224,X238,category,0,0.0,2,"1, 0"
225,X239,category,0,0.0,2,"0, 1"
226,X240,category,0,0.0,2,"0, 1"
227,X241,category,0,0.0,2,"0, 1"
228,X242,category,0,0.0,2,"0, 1"
229,X243,category,0,0.0,2,"0, 1"
230,X244,category,0,0.0,2,"0, 1"
231,X245,category,0,0.0,2,"0, 1"
232,X246,category,0,0.0,2,"0, 1"
233,X247,category,0,0.0,2,"0, 1"
234,X248,category,0,0.0,2,"0, 1"
235,X249,category,0,0.0,2,"0, 1"
236,X250,category,0,0.0,2,"1, 0"
237,X251,category,0,0.0,2,"0, 1"
238,X252,category,0,0.0,2,"0, 1"
239,X253,category,0,0.0,2,"0, 1"
240,X254,category,0,0.0,2,"0, 1"
241,X255,category,0,0.0,2,"0, 1"
242,X256,category,0,0.0,2,"0, 1"
243,X257,category,0,0.0,2,"0, 1"
244,X258,category,0,0.0,2,"0, 1"
245,X259,category,0,0.0,2,"0, 1"
246,X260,category,0,0.0,2,"0, 1"
247,X261,category,0,0.0,2,"0, 1"
248,X262,category,0,0.0,2,"0, 1"
249,X263,category,0,0.0,2,"1, 0"
250,X264,category,0,0.0,2,"0, 1"
251,X265,category,0,0.0,2,"1, 0"
252,X266,category,0,0.0,2,"0, 1"
253,X267,category,0,0.0,2,"0, 1"
254,X268,category,0,0.0,1,0
255,X269,category,0,0.0,2,"0, 1"
256,X270,category,0,0.0,2,"0, 1"
257,X271,category,0,0.0,2,"0, 1"
258,X272,category,0,0.0,2,"0, 1"
259,X273,category,0,0.0,2,"1, 0"
260,X274,category,0,0.0,2,"0, 1"
261,X275,category,0,0.0,2,"1, 0"
262,X276,category,0,0.0,2,"0, 1"
263,X277,category,0,0.0,2,"0, 1"
264,X278,category,0,0.0,2,"0, 1"
265,X279,category,0,0.0,2,"0, 1"
266,X280,category,0,0.0,2,"0, 1"
267,X281,category,0,0.0,2,"0, 1"
268,X282,category,0,0.0,2,"0, 1"
269,X283,category,0,0.0,2,"0, 1"
270,X284,category,0,0.0,2,"0, 1"
271,X285,category,0,0.0,2,"0, 1"
272,X286,category,0,0.0,2,"0, 1"
273,X287,category,0,0.0,2,"0, 1"
274,X288,category,0,0.0,2,"0, 1"
275,X289,category,0,0.0,1,0
276,X290,category,0,0.0,1,0
277,X291,category,0,0.0,2,"0, 1"
278,X292,category,0,0.0,2,"0, 1"
279,X293,category,0,0.0,1,0
280,X294,category,0,0.0,2,"0, 1"
281,X295,category,0,0.0,2,"0, 1"
282,X296,category,0,0.0,2,"0, 1"
283,X297,category,0,0.0,1,0
284,X298,category,0,0.0,2,"0, 1"
285,X299,category,0,0.0,2,"0, 1"
286,X300,category,0,0.0,2,"0, 1"
287,X301,category,0,0.0,2,"0, 1"
288,X302,category,0,0.0,2,"0, 1"
289,X304,category,0,0.0,2,"1, 0"
290,X305,category,0,0.0,2,"0, 1"
291,X306,category,0,0.0,2,"0, 1"
292,X307,category,0,0.0,2,"0, 1"
293,X308,category,0,0.0,2,"0, 1"
294,X309,category,0,0.0,2,"0, 1"
295,X310,category,0,0.0,2,"0, 1"
296,X311,category,0,0.0,2,"1, 0"
297,X312,category,0,0.0,2,"0, 1"
298,X313,category,0,0.0,2,"0, 1"
299,X314,category,0,0.0,2,"0, 1"
300,X315,category,0,0.0,2,"0, 1"
301,X316,category,0,0.0,2,"0, 1"
302,X317,category,0,0.0,2,"0, 1"
303,X318,category,0,0.0,2,"0, 1"
304,X319,category,0,0.0,2,"0, 1"
305,X320,category,0,0.0,2,"0, 1"
306,X321,category,0,0.0,2,"0, 1"
307,X322,category,0,0.0,2,"0, 1"
308,X323,category,0,0.0,2,"0, 1"
309,X324,category,0,0.0,2,"1, 0"
310,X325,category,0,0.0,2,"0, 1"
311,X326,category,0,0.0,2,"0, 1"
312,X327,category,0,0.0,2,"0, 1"
313,X328,category,0,0.0,2,"0, 1"
314,X329,category,0,0.0,2,"0, 1"
315,X330,category,0,0.0,1,0
316,X331,category,0,0.0,2,"0, 1"
317,X332,category,0,0.0,2,"0, 1"
318,X333,category,0,0.0,2,"0, 1"
319,X334,category,0,0.0,2,"0, 1"
320,X335,category,0,0.0,2,"0, 1"
321,X336,category,0,0.0,2,"0, 1"
322,X337,category,0,0.0,2,"1, 0"
323,X338,category,0,0.0,2,"0, 1"
324,X339,category,0,0.0,2,"0, 1"
325,X340,category,0,0.0,2,"0, 1"
326,X341,category,0,0.0,2,"0, 1"
327,X342,category,0,0.0,2,"0, 1"
328,X343,category,0,0.0,2,"0, 1"
329,X344,category,0,0.0,2,"0, 1"
330,X345,category,0,0.0,2,"0, 1"
331,X346,category,0,0.0,2,"0, 1"
332,X347,category,0,0.0,1,0
333,X348,category,0,0.0,2,"1, 0"
334,X349,category,0,0.0,2,"0, 1"
335,X350,category,0,0.0,2,"0, 1"
336,X351,category,0,0.0,2,"0, 1"
337,X352,category,0,0.0,2,"0, 1"
338,X353,category,0,0.0,2,"0, 1"
339,X354,category,0,0.0,2,"0, 1"
340,X355,category,0,0.0,2,"0, 1"
341,X356,category,0,0.0,2,"0, 1"
342,X357,category,0,0.0,2,"0, 1"
343,X358,category,0,0.0,2,"0, 1"
344,X359,category,0,0.0,2,"0, 1"
345,X360,category,0,0.0,2,"0, 1"
346,X361,category,0,0.0,2,"1, 0"
347,X362,category,0,0.0,2,"1, 0"
348,X363,category,0,0.0,2,"1, 0"
349,X364,category,0,0.0,2,"0, 1"
350,X365,category,0,0.0,2,"0, 1"
351,X366,category,0,0.0,2,"0, 1"
352,X367,category,0,0.0,2,"0, 1"
353,X368,category,0,0.0,2,"0, 1"
354,X369,category,0,0.0,2,"0, 1"
355,X370,category,0,0.0,2,"0, 1"
356,X371,category,0,0.0,2,"0, 1"
357,X372,category,0,0.0,2,"0, 1"
358,X373,category,0,0.0,2,"0, 1"
359,X374,category,0,0.0,2,"0, 1"
360,X375,category,0,0.0,2,"0, 1"
361,X376,category,0,0.0,2,"0, 1"
362,X377,category,0,0.0,2,"0, 1"
363,X378,category,0,0.0,2,"0, 1"
364,X379,category,0,0.0,2,"0, 1"
365,X380,category,0,0.0,2,"0, 1"
366,X382,category,0,0.0,2,"0, 1"
367,X383,category,0,0.0,2,"0, 1"
368,X384,category,0,0.0,2,"0, 1"
369,X385,category,0,0.0,2,"0, 1"
370,y,float64,0,0.0,2542,"90.76, 89.38, 91.88, 89.06, 89.19, 93.62, 89.6, 91.62, 90.44, 90.38"
371,time_index,int64,0,0.0,4204,"8417, 0, 6, 7, 9, 13, 18, 24, 25, 27"

In [10]:
# Numeric Feature Statistics
numeric_stats

             count         mean          std    min      max
time_index  4204.0  4208.083492  2438.254452   0.00  8417.00
y           4204.0   100.619125    12.417569  72.11   169.91

In [11]:
# Categorical Feature Statistics
cat_stats

            value  count     pct
column rank
X0     1        z    359    8.54
       2       ak    348    8.28
       3        y    323    7.68
       4       ay    313    7.45
       5        t    306    7.28
X1     1       aa    833   19.81
       2        s    598   14.22
       3        b    592   14.08
       4        l    589   14.01
       5        v    408    9.71
X10    1        0   4148   98.67
       2        1     56    1.33
X100   1        1   2903   69.05
       2        0   1301   30.95
X101   1        1   3934   93.58
       2        0    270    6.42
X102   1        0   4175   99.31
       2        1     29    0.69
X103   1        1   3299   78.47
       2        0    905   21.53
X104   1        0   4196   99.81
       2        1      8    0.19
X105   1        0   4194   99.76
       2        1     10    0.24
X106   1        0   4149   98.69
       2        1     55    1.31
X107   1        0   4204  100.00
X108   1        0   4142   98.53
       2        1     62    1.47
X109   1        0   4034   95.96
       2        1    170    4.04
X110   1        0   4200   99.90
       2        1      4    0.10
X111   1        1   4099   97.50
       2        0    105    2.50
X112   1        0   4192   99.71
       2        1     12    0.29
X113   1        0   4111   97.79
       2        1     93    2.21
X114   1        0   3590   85.39
       2        1    614   14.61
X115   1        0   3004   71.46
       2        1   1200   28.54
X116   1        0   3377   80.33
       2        1    827   19.67
X117   1        0   3997   95.08
       2        1    207    4.92
X118   1        1   2616   62.23
       2        0   1588   37.77
X119   1        1   2616   62.23
       2        0   1588   37.77
X12    1        0   3888   92.48
       2        1    316    7.52
X120   1        1   4027   95.79
       2        0    177    4.21
X122   1        0   4174   99.29
       2        1     30    0.71
X123   1        0   4193   99.74
       2        1     11    0.26
X124   1        0   4202   99.95
       2        1      2    0.05
X125   1        0   4191   99.69
       2        1     13    0.31
X126   1        0   4041   96.12
       2        1    163    3.88
X127   1        0   2122   50.48
       2        1   2082   49.52
X128   1        1   4030   95.86
       2        0    174    4.14
X129   1        0   3689   87.75
       2        1    515   12.25
X13    1        0   3960   94.20
       2        1    244    5.80
X130   1        0   4030   95.86
       2        1    174    4.14
X131   1        0   4092   97.34
       2        1    112    2.66
X132   1        1   2895   68.86
       2        0   1309   31.14
X133   1        0   3681   87.56
       2        1    523   12.44
X134   1        0   4111   97.79
       2        1     93    2.21
X135   1        0   4090   97.29
       2        1    114    2.71
X136   1        1   4021   95.65
       2        0    183    4.35
X137   1        1   2445   58.16
       2        0   1759   41.84
X138   1        0   4032   95.91
       2        1    172    4.09
X139   1        0   3824   90.96
       2        1    380    9.04
X14    1        0   2403   57.16
       2        1   1801   42.84
X140   1        0   4034   95.96
       2        1    170    4.04
X141   1        0   4144   98.57
       2        1     60    1.43
X142   1        1   3239   77.05
       2        0    965   22.95
X143   1        0   4043   96.17
       2        1    161    3.83
X144   1        1   3398   80.83
       2        0    806   19.17
X145   1        0   4198   99.86
       2        1      6    0.14
X146   1        0   4032   95.91
       2        1    172    4.09
X147   1        0   4111   97.79
       2        1     93    2.21
X148   1        0   4015   95.50
       2        1    189    4.50
X15    1        0   4202   99.95
       2        1      2    0.05
X150   1        1   3331   79.23
       2        0    873   20.77
X151   1        0   3844   91.44
       2        1    360    8.56
X152   1        0   4068   96.76
       2        1    136    3.24
X153   1        0   4201   99.93
       2        1      3    0.07
X154   1        0   3327   79.14
       2        1    877   20.86
X155   1        0   3883   92.36
       2        1    321    7.64
X156   1        1   3016   71.74
       2        0   1188   28.26
X157   1        0   3016   71.74
       2        1   1188   28.26
X158   1        0   3239   77.05
       2        1    965   22.95
X159   1        0   4147   98.64
       2        1     57    1.36
X16    1        0   4194   99.76
       2        1     10    0.24
X160   1        0   4199   99.88
       2        1      5    0.12
X161   1        0   3372   80.21
       2        1    832   19.79
X162   1        0   4032   95.91
       2        1    172    4.09
X163   1        0   2929   69.67
       2        1   1275   30.33
X164   1        0   3941   93.74
       2        1    263    6.26
X165   1        0   4185   99.55
       2        1     19    0.45
X166   1        0   4064   96.67
       2        1    140    3.33
X167   1        0   4200   99.90
       2        1      4    0.10
X168   1        0   3066   72.93
       2        1   1138   27.07
X169   1        0   4176   99.33
       2        1     28    0.67
X17    1        0   4172   99.24
       2        1     32    0.76
X170   1        0   4103   97.60
       2        1    101    2.40
X171   1        1   2765   65.77
       2        0   1439   34.23
X172   1        0   4179   99.41
       2        1     25    0.59
X173   1        0   4163   99.02
       2        1     41    0.98
X174   1        0   4131   98.26
       2        1     73    1.74
X175   1        0   4110   97.76
       2        1     94    2.24
X176   1        0   4132   98.29
       2        1     72    1.71
X177   1        0   3993   94.98
       2        1    211    5.02
X178   1        1   2343   55.73
       2        0   1861   44.27
X179   1        0   4003   95.22
       2        1    201    4.78
X18    1        0   4171   99.22
       2        1     33    0.78
X180   1        0   3541   84.23
       2        1    663   15.77
X181   1        0   3809   90.60
       2        1    395    9.40
X182   1        0   3757   89.37
       2        1    447   10.63
X183   1        0   4187   99.60
       2        1     17    0.40
X184   1        0   4198   99.86
       2        1      6    0.14
X185   1        0   4125   98.12
       2        1     79    1.88
X186   1        1   2254   53.62
       2        0   1950   46.38
X187   1        0   2437   57.97
       2        1   1767   42.03
X189   1        1   3849   91.56
       2        0    355    8.44
X19    1        0   3786   90.06
       2        1    418    9.94
X190   1        0   4203   99.98
       2        1      1    0.02
X191   1        0   2223   52.88
       2        1   1981   47.12
X192   1        0   4194   99.76
       2        1     10    0.24
X194   1        0   2254   53.62
       2        1   1950   46.38
X195   1        0   4155   98.83
       2        1     49    1.17
X196   1        0   4161   98.98
       2        1     43    1.02
X197   1        0   4068   96.76
       2        1    136    3.24
X198   1        0   4108   97.72
       2        1     96    2.28
X199   1        0   4192   99.71
       2        1     12    0.29
X2     1       as   1658   39.44
       2       ae    495   11.77
       3       ai    414    9.85
       4        m    367    8.73
       5       ak    265    6.30
X20    1        0   3604   85.73
       2        1    600   14.27
X200   1        0   4176   99.33
       2        1     28    0.67
X201   1        0   3456   82.21
       2        1    748   17.79
X202   1        0   3189   75.86
       2        1   1015   24.14
X203   1        0   4133   98.31
       2        1     71    1.69
X204   1        0   4203   99.98
       2        1      1    0.02
X205   1        1   4203   99.98
       2        0      1    0.02
X206   1        0   4123   98.07
       2        1     81    1.93
X207   1        0   4203   99.98
       2        1      1    0.02
X208   1        0   3940   93.72
       2        1    264    6.28
X209   1        1   3778   89.87
       2        0    426   10.13
X21    1        0   4193   99.74
       2        1     11    0.26
X210   1        0   4203   99.98
       2        1      1    0.02
X211   1        0   4141   98.50
       2        1     63    1.50
X212   1        0   4181   99.45
       2        1     23    0.55
X213   1        0   4196   99.81
       2        1      8    0.19
X214   1        0   4175   99.31
       2        1     29    0.69
X215   1        0   3790   90.15
       2        1    414    9.85
X216   1        0   4179   99.41
       2        1     25    0.59
X217   1        0   4173   99.26
       2        1     31    0.74
X218   1        0   2891   68.77
       2        1   1313   31.23
X219   1        0   3920   93.24
       2        1    284    6.76
X22    1        0   3838   91.29
       2        1    366    8.71
X220   1        1   2362   56.18
       2        0   1842   43.82
X221   1        0   4170   99.19
       2        1     34    0.81
X222   1        0   4111   97.79
       2        1     93    2.21
X223   1        1   2334   55.52
       2        0   1870   44.48
X224   1        0   2869   68.24
       2        1   1335   31.76
X225   1        0   3796   90.29
       2        1    408    9.71
X226   1        0   4068   96.76
       2        1    136    3.24
X227   1        0   4191   99.69
       2        1     13    0.31
X228   1        0   4041   96.12
       2        1    163    3.88
X229   1        1   4037   96.03
       2        0    167    3.97
X23    1        0   4117   97.93
       2        1     87    2.07
X230   1        0   4182   99.48
       2        1     22    0.52
X231   1        0   4136   98.38
       2        1     68    1.62
X232   1        0   4023   95.69
       2        1    181    4.31
X233   1        0   4204  100.00
X234   1        0   3356   79.83
       2        1    848   20.17
X235   1        0   4204  100.00
X236   1        0   4202   99.95
       2        1      2    0.05
X237   1        0   4176   99.33
       2        1     28    0.67
X238   1        1   3852   91.63
       2        0    352    8.37
X239   1        0   4175   99.31
       2        1     29    0.69
X24    1        0   4196   99.81
       2        1      8    0.19
X240   1        0   4192   99.71
       2        1     12    0.29
X241   1        0   3796   90.29
       2        1    408    9.71
X242   1        0   4173   99.26
       2        1     31    0.74
X243   1        0   4174   99.29
       2        1     30    0.71
X244   1        0   3769   89.65
       2        1    435   10.35
X245   1        0   4201   99.93
       2        1      3    0.07
X246   1        0   2484   59.09
       2        1   1720   40.91
X247   1        0   3189   75.86
       2        1   1015   24.14
X248   1        0   4198   99.86
       2        1      6    0.14
X249   1        0   4172   99.24
       2        1     32    0.76
X250   1        1   2324   55.28
       2        0   1880   44.72
X251   1        0   2546   60.56
       2        1   1658   39.44
X252   1        0   4201   99.93
       2        1      3    0.07
X253   1        0   4198   99.86
       2        1      6    0.14
X254   1        0   4182   99.48
       2        1     22    0.52
X255   1        0   4122   98.05
       2        1     82    1.95
X256   1        0   3896   92.67
       2        1    308    7.33
X257   1        0   4203   99.98
       2        1      1    0.02
X258   1        0   4194   99.76
       2        1     10    0.24
X259   1        0   4203   99.98
       2        1      1    0.02
X26    1        0   4183   99.50
       2        1     21    0.50
X260   1        0   4203   99.98
       2        1      1    0.02
X261   1        0   2441   58.06
       2        1   1763   41.94
X262   1        0   4198   99.86
       2        1      6    0.14
X263   1        1   4023   95.69
       2        0    181    4.31
X264   1        0   4039   96.08
       2        1    165    3.92
X265   1        1   3807   90.56
       2        0    397    9.44
X266   1        0   4198   99.86
       2        1      6    0.14
X267   1        0   4166   99.10
       2        1     38    0.90
X268   1        0   4204  100.00
X269   1        0   4202   99.95
       2        1      2    0.05
X27    1        1   2871   68.29
       2        0   1333   31.71
X270   1        0   4203   99.98
       2        1      1    0.02
X271   1        0   4195   99.79
       2        1      9    0.21
X272   1        0   4046   96.24
       2        1    158    3.76
X273   1        1   3026   71.98
       2        0   1178   28.02
X274   1        0   4162   99.00
       2        1     42    1.00
X275   1        1   3056   72.69
       2        0   1148   27.31
X276   1        0   4042   96.15
       2        1    162    3.85
X277   1        0   4198   99.86
       2        1      6    0.14
X278   1        0   4202   99.95
       2        1      2    0.05
X279   1        0   4023   95.69
       2        1    181    4.31
X28    1        0   4067   96.74
       2        1    137    3.26
X280   1        0   4203   99.98
       2        1      1    0.02
X281   1        0   4193   99.74
       2        1     11    0.26
X282   1        0   4187   99.60
       2        1     17    0.40
X283   1        0   3613   85.94
       2        1    591   14.06
X284   1        0   4032   95.91
       2        1    172    4.09
X285   1        0   3339   79.42
       2        1    865   20.58
X286   1        0   3974   94.53
       2        1    230    5.47
X287   1        0   4137   98.41
       2        1     67    1.59
X288   1        0   4203   99.98
       2        1      1    0.02
X289   1        0   4204  100.00
X29    1        0   4023   95.69
       2        1    181    4.31
X290   1        0   4204  100.00
X291   1        0   4160   98.95
       2        1     44    1.05
X292   1        0   4166   99.10
       2        1     38    0.90
X293   1        0   4204  100.00
X294   1        0   3678   87.49
       2        1    526   12.51
X295   1        0   4203   99.98
       2        1      1    0.02
X296   1        0   4203   99.98
       2        1      1    0.02
X297   1        0   4204  100.00
X298   1        0   4185   99.55
       2        1     19    0.45
X299   1        0   4185   99.55
       2        1     19    0.45
X30    1        0   4185   99.55
       2        1     19    0.45
X300   1        0   3333   79.28
       2        1    871   20.72
X301   1        0   4007   95.31
       2        1    197    4.69
X302   1        0   4156   98.86
       2        1     48    1.14
X304   1        1   3886   92.44
       2        0    318    7.56
X305   1        0   4148   98.67
       2        1     56    1.33
X306   1        0   4021   95.65
       2        1    183    4.35
X307   1        0   4195   99.79
       2        1      9    0.21
X308   1        0   4164   99.05
       2        1     40    0.95
X309   1        0   4174   99.29
       2        1     30    0.71
X31    1        0   3228   76.78
       2        1    976   23.22
X310   1        0   4193   99.74
       2        1     11    0.26
X311   1        1   2517   59.87
       2        0   1687   40.13
X312   1        0   4186   99.57
       2        1     18    0.43
X313   1        0   2939   69.91
       2        1   1265   30.09
X314   1        0   2390   56.85
       2        1   1814   43.15
X315   1        0   4083   97.12
       2        1    121    2.88
X316   1        0   3381   80.42
       2        1    823   19.58
X317   1        0   4172   99.24
       2        1     32    0.76
X318   1        0   4201   99.93
       2        1      3    0.07
X319   1        0   4202   99.95
       2        1      2    0.05
X32    1        0   4157   98.88
       2        1     47    1.12
X320   1        0   4174   99.29
       2        1     30    0.71
X321   1        0   3202   76.17
       2        1   1002   23.83
X322   1        0   4112   97.81
       2        1     92    2.19
X323   1        0   4165   99.07
       2        1     39    0.93
X324   1        1   2416   57.47
       2        0   1788   42.53
X325   1        0   4180   99.43
       2        1     24    0.57
X326   1        0   4068   96.76
       2        1    136    3.24
X327   1        0   3665   87.18
       2        1    539   12.82
X328   1        0   4035   95.98
       2        1    169    4.02
X329   1        0   2373   56.45
       2        1   1831   43.55
X33    1        0   4203   99.98
       2        1      1    0.02
X330   1        0   4204  100.00
X331   1        0   3969   94.41
       2        1    235    5.59
X332   1        0   4201   99.93
       2        1      3    0.07
X333   1        0   4103   97.60
       2        1    101    2.40
X334   1        0   2259   53.73
       2        1   1945   46.27
X335   1        0   4189   99.64
       2        1     15    0.36
X336   1        0   3669   87.27
       2        1    535   12.73
X337   1        1   2171   51.64
       2        0   2033   48.36
X338   1        0   4175   99.31
       2        1     29    0.69
X339   1        0   4203   99.98
       2        1      1    0.02
X34    1        0   4181   99.45
       2        1     23    0.55
X340   1        0   4110   97.76
       2        1     94    2.24
X341   1        0   4170   99.19
       2        1     34    0.81
X342   1        0   4111   97.79
       2        1     93    2.21
X343   1        0   3874   92.15
       2        1    330    7.85
X344   1        0   4168   99.14
       2        1     36    0.86
X345   1        0   4110   97.76
       2        1     94    2.24
X346   1        0   4005   95.27
       2        1    199    4.73
X347   1        0   4204  100.00
X348   1        1   3983   94.74
       2        0    221    5.26
X349   1        0   4015   95.50
       2        1    189    4.50
X35    1        0   3228   76.78
       2        1    976   23.22
X350   1        0   2780   66.13
       2        1   1424   33.87
X351   1        0   2953   70.24
       2        1   1251   29.76
X352   1        0   3977   94.60
       2        1    227    5.40
X353   1        0   4195   99.79
       2        1      9    0.21
X354   1        0   3351   79.71
       2        1    853   20.29
X355   1        0   2605   61.96
       2        1   1599   38.04
X356   1        0   3447   81.99
       2        1    757   18.01
X357   1        0   4199   99.88
       2        1      5    0.12
X358   1        0   2410   57.33
       2        1   1794   42.67
X359   1        0   4070   96.81
       2        1    134    3.19
X36    1        0   4185   99.55
       2        1     19    0.45
X360   1        0   3883   92.36
       2        1    321    7.64
X361   1        1   4061   96.60
       2        0    143    3.40
X362   1        1   2188   52.05
       2        0   2016   47.95
X363   1        1   3170   75.40
       2        0   1034   24.60
X364   1        0   4192   99.71
       2        1     12    0.29
X365   1        0   4192   99.71
       2        1     12    0.29
X366   1        0   4199   99.88
       2        1      5    0.12
X367   1        0   3987   94.84
       2        1    217    5.16
X368   1        0   3941   93.74
       2        1    263    6.26
X369   1        0   4202   99.95
       2        1      2    0.05
X37    1        0   3228   76.78
       2        1    976   23.22
X370   1        0   4176   99.33
       2        1     28    0.67
X371   1        0   4144   98.57
       2        1     60    1.43
X372   1        0   4202   99.95
       2        1      2    0.05
X373   1        0   4123   98.07
       2        1     81    1.93
X374   1        0   3249   77.28
       2        1    955   22.72
X375   1        0   2864   68.13
       2        1   1340   31.87
X376   1        0   3963   94.27
       2        1    241    5.73
X377   1        0   2880   68.51
       2        1   1324   31.49
X378   1        0   4117   97.93

In [12]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,0.738,0.278,154.196,0.015,log,57845.6,60798.8,exponential

## Task Curation

In [13]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from sklearn.model_selection import TimeSeriesSplit

df = df.sort_values(by="time_index", ascending=True).reset_index(drop=True)

default_train_index = df.index[:1000].to_list()
to_split_index = df.index[1000:]

spliter = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=9, test_size=None)
splits = {}
for i, (train_idx, test_idx) in enumerate(spliter.split(to_split_index)):
    print(len(train_idx) + len(default_train_index), len(test_idx))
    splits[i] = {0: (default_train_index + to_split_index[train_idx].to_list(), to_split_index[test_idx].tolist())}

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="This is a small temporal dataset. Thus, we could refit often and we could simulate that a model was often refit, basically, if possible, after each time_index (akin to LOO). As this would create too many splits with too small test sizes for a robust signal, we opt for less splits. Moreover, as we want to have sufficient train data signal, we start with the first 1000 samples of the data as fixed train data. The rest is than gradually split to create 9 test splits using a sklearn TimeSeriesSplit.",
    splits=splits,
)

1324 320
1644 320
1964 320
2284 320
2604 320
2924 320
3244 320
3564 320
3884 320

## Export

In [14]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019c0e8e-8749-7ff7-9c06-632c3ca2aa05
3898208b0b8c66d56b9a9b3da81335fc1d0a60f342f4a6ecb51898fa086c7cbf