### Dataset and Task Metadata

In [47]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="coil_2000_insurance_policies",
    dataset_year="2000",
    domain_str="insurance",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="http://archive.ics.uci.edu/dataset/125/insurance+company+benchmark+coil+2000",
    download_description="""
We download the data from the UCI repository and uzip it to a predefined folder.

mkdir -p local-data-warehouse/coil_2000_insurance_policies/ && wget -P local-data-warehouse/coil_2000_insurance_policies/ https://archive.ics.uci.edu/static/public/125/insurance+company+benchmark+coil+2000.zip && unzip local-data-warehouse/coil_2000_insurance_policies/insurance+company+benchmark+coil+2000.zip -d local-data-warehouse/coil_2000_insurance_policies/ && rm local-data-warehouse/coil_2000_insurance_policies/tic.task.html && rm local-data-warehouse/coil_2000_insurance_policies/tic.tar.gz && rm local-data-warehouse/coil_2000_insurance_policies/tic.html && rm local-data-warehouse/coil_2000_insurance_policies/tic.data.html && rm local-data-warehouse/coil_2000_insurance_policies/dictionary.txt && rm local-data-warehouse/coil_2000_insurance_policies/insurance+company+benchmark+coil+2000.zip && rm local-data-warehouse/coil_2000_insurance_policies/019d1b44-3904-7f10-88c9-328d66ac0b6c && rm local-data-warehouse/coil_2000_insurance_policies/insurance+company+benchmark+coil+2000.zip.1 && rm local-data-warehouse/coil_2000_insurance_policies/TicDataDescr.txt
""",
    # References
    academic_reference_bibtex="""@techreport{putten2000coil,
  title={CoIL Challenge 2000: The Insurance Company Case, Sentient Machine Research, Amsterdam and Leiden Institute of Advanced Computer Science},
  author={van der Putten, P and van Someren, M},
  year={2000},
  institution={Leiden LIACS Technical Report 2000-09}
}
""",
    academic_reference_bibtex_key="putten2000coil",
    license="non commercial research and education purposes",
    data_tags=["IID"],
    curation_comments="""
- We combined train and test data into a single dataset.
- Map target column to yes/no values.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="CARAVAN",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="CARAVAN",
)

## Preprocessing

In [49]:
import pandas as pd

train = pd.read_csv(f"{dataset_mold.path}/ticdata2000.txt", header=None, sep="\t")
test_data = pd.read_csv(f"{dataset_mold.path}/ticeval2000.txt", header=None, sep="\t")
test_target = pd.read_csv(f"{dataset_mold.path}/tictgts2000.txt", header=None, sep="\t")

# Concatenate the two datasets
test = pd.concat([test_data, test_target], ignore_index=True, axis=1)
data = pd.concat([train, test], ignore_index=True)

feature_names = [
    "MOSTYPE",      # Customer Subtype see L0
    "MAANTHUI",     # Number of houses 1 � 10
    "MGEMOMV",      # Avg size household 1 � 6
    "MGEMLEEF",     # Avg age see L1
    "MOSHOOFD",     # Customer main type see L2
    "MGODRK",       # Roman catholic see L3
    "MGODPR",       # Protestant ...
    "MGODOV",       # Other religion
    "MGODGE",       # No religion
    "MRELGE",       # Married
    "MRELSA",       # Living together
    "MRELOV",       # Other relation
    "MFALLEEN",     # Singles
    "MFGEKIND",     # Household without children
    "MFWEKIND",     # Household with children
    "MOPLHOOG",     # High level education
    "MOPLMIDD",     # Medium level education
    "MOPLLAAG",     # Lower level education
    "MBERHOOG",     # High status
    "MBERZELF",     # Entrepreneur
    "MBERBOER",     # Farmer
    "MBERMIDD",     # Middle management
    "MBERARBG",     # Skilled labourers
    "MBERARBO",     # Unskilled labourers
    "MSKA",         # Social class A
    "MSKB1",        # Social class B1
    "MSKB2",        # Social class B2
    "MSKC",         # Social class C
    "MSKD",         # Social class D
    "MHHUUR",       # Rented house
    "MHKOOP",       # Home owners
    "MAUT1",        # 1 car
    "MAUT2",        # 2 cars
    "MAUT0",        # No car
    "MZFONDS",      # National Health Service
    "MZPART",       # Private health insurance
    "MINKM30",      # Income < 30.000
    "MINK3045",     # Income 30-45.000
    "MINK4575",     # Income 45-75.000
    "MINK7512",     # Income 75-122.000
    "MINK123M",     # Income >123.000
    "MINKGEM",      # Average income
    "MKOOPKLA",     # Purchasing power class
    "PWAPART",      # Contribution private third party insurance see L4
    "PWABEDR",      # Contribution third party insurance (firms) ...
    "PWALAND",      # Contribution third party insurane (agriculture)
    "PPERSAUT",     # Contribution car policies
    "PBESAUT",      # Contribution delivery van policies
    "PMOTSCO",      # Contribution motorcycle/scooter policies
    "PVRAAUT",      # Contribution lorry policies
    "PAANHANG",     # Contribution trailer policies
    "PTRACTOR",     # Contribution tractor policies
    "PWERKT",       # Contribution agricultural machines policies 
    "PBROM",        # Contribution moped policies
    "PLEVEN",       # Contribution life insurances
    "PPERSONG",     # Contribution private accident insurance policies
    "PGEZONG",      # Contribution family accidents insurance policies
    "PWAOREG",      # Contribution disability insurance policies
    "PBRAND",       # Contribution fire policies
    "PZEILPL",      # Contribution surfboard policies
    "PPLEZIER",     # Contribution boat policies
    "PFIETS",       # Contribution bicycle policies
    "PINBOED",      # Contribution property insurance policies
    "PBYSTAND",     # Contribution social security insurance policies
    "AWAPART",      # Number of private third party insurance 1 - 12
    "AWABEDR",      # Number of third party insurance (firms) ...
    "AWALAND",      # Number of third party insurane (agriculture)
    "APERSAUT",     # Number of car policies
    "ABESAUT",      # Number of delivery van policies
    "AMOTSCO",      # Number of motorcycle/scooter policies
    "AVRAAUT",      # Number of lorry policies
    "AAANHANG",     # Number of trailer policies
    "ATRACTOR",     # Number of tractor policies
    "AWERKT",       # Number of agricultural machines policies
    "ABROM",        # Number of moped policies
    "ALEVEN",       # Number of life insurances
    "APERSONG",     # Number of private accident insurance policies
    "AGEZONG",      # Number of family accidents insurance policies
    "AWAOREG",      # Number of disability insurance policies
    "ABRAND",       # Number of fire policies
    "AZEILPL",      # Number of surfboard policies
    "APLEZIER",     # Number of boat policies
    "AFIETS",       # Number of bicycle policies
    "AINBOED",      # Number of property insurance policies
    "ABYSTAND",     # Number of social security insurance policies
    "CARAVAN"       # Number of mobile home policies 0 - 1
]

cat_features = [
    "MOSTYPE",      # Customer Subtype see L0
    "MOSHOOFD",     # Customer main type see L2
    "MGODRK",       # Roman catholic see L3
    "MGODPR",       # Protestant ...
    "MGODOV",       # Other religion
    "MGODGE",       # No religion
    "MRELGE",       # Married
    "MRELSA",       # Living together
    "MRELOV",       # Other relation
    "MFALLEEN",     # Singles
    "MFGEKIND",     # Household without children
    "MFWEKIND",     # Household with children
    "MOPLHOOG",     # High level education
    "MOPLMIDD",     # Medium level education
    "MOPLLAAG",     # Lower level education
    "MBERHOOG",     # High status
    "MBERZELF",     # Entrepreneur
    "MBERBOER",     # Farmer
    "MBERMIDD",     # Middle management
    "MBERARBG",     # Skilled labourers
    "MBERARBO",     # Unskilled labourers
    "MSKA",         # Social class A
    "MSKB1",        # Social class B1
    "MSKB2",        # Social class B2
    "MSKC",         # Social class C
    "MSKD",         # Social class D
    "MHHUUR",       # Rented house
    "MHKOOP",       # Home owners
    "MAUT1",        # 1 car
    "MAUT2",        # 2 cars
    "MAUT0",        # No car
    "MZFONDS",      # National Health Service
    "MZPART",       # Private health insurance
    "MINKM30",      # Income < 30.000
    "MINK3045",     # Income 30-45.000
    "MINK4575",     # Income 45-75.000
    "MINK7512",     # Income 75-122.000
    "MINK123M",     # Income >123.000
    "MINKGEM",      # Average income
    "MKOOPKLA",     # Purchasing power class
    "PWAPART",      # Contribution private third party insurance see L4
    "PWABEDR",      # Contribution third party insurance (firms) ...
    "PWALAND",      # Contribution third party insurane (agriculture)
    "PPERSAUT",     # Contribution car policies
    "PBESAUT",      # Contribution delivery van policies
    "PMOTSCO",      # Contribution motorcycle/scooter policies
    "PVRAAUT",      # Contribution lorry policies
    "PAANHANG",     # Contribution trailer policies
    "PTRACTOR",     # Contribution tractor policies
    "PWERKT",       # Contribution agricultural machines policies 
    "PBROM",        # Contribution moped policies
    "PLEVEN",       # Contribution life insurances
    "PPERSONG",     # Contribution private accident insurance policies
    "PGEZONG",      # Contribution family accidents insurance policies
    "PWAOREG",      # Contribution disability insurance policies
    "PBRAND",       # Contribution fire policies
    "PZEILPL",      # Contribution surfboard policies
    "PPLEZIER",     # Contribution boat policies
    "PFIETS",       # Contribution bicycle policies
    "PINBOED",      # Contribution property insurance policies
    "PBYSTAND",     # Contribution social security insurance policies
    "CARAVAN"       # Number of mobile home policies 0 - 1
]

data.columns = feature_names
df = data.sample(frac=1, random_state=42).reset_index(drop=True)

df[cat_features] = df[cat_features].astype("category")

df["CARAVAN"] = df["CARAVAN"].map({0.0: "No", 1.0: "Yes"})

In [50]:
# Use if needed to get see all cols of pandas dataframes
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
df.head()

,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,MRELGE,MRELSA,MRELOV,MFALLEEN,MFGEKIND,MFWEKIND,MOPLHOOG,MOPLMIDD,MOPLLAAG,MBERHOOG,MBERZELF,MBERBOER,MBERMIDD,MBERARBG,MBERARBO,MSKA,MSKB1,MSKB2,MSKC,MSKD,MHHUUR,MHKOOP,MAUT1,MAUT2,MAUT0,MZFONDS,MZPART,MINKM30,MINK3045,MINK4575,MINK7512,MINK123M,MINKGEM,MKOOPKLA,PWAPART,PWABEDR,PWALAND,PPERSAUT,PBESAUT,PMOTSCO,PVRAAUT,PAANHANG,PTRACTOR,PWERKT,PBROM,PLEVEN,PPERSONG,PGEZONG,PWAOREG,PBRAND,PZEILPL,PPLEZIER,PFIETS,PINBOED,PBYSTAND,AWAPART,AWABEDR,AWALAND,APERSAUT,ABESAUT,AMOTSCO,AVRAAUT,AAANHANG,ATRACTOR,AWERKT,ABROM,ALEVEN,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,CARAVAN
0,31,1,3,3,7,0,2,4,4,9,0,0,0,3,6,0,4,5,1,0,0,3,3,2,2,2,2,5,1,9,0,5,3,2,6,3,0,4,5,1,0,4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,No
1,10,1,4,3,3,5,3,1,1,8,1,1,1,1,8,1,5,3,1,0,0,5,3,1,1,3,3,3,0,1,8,9,0,0,5,4,3,2,4,0,0,4,8,2,0,0,6,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,No
2,40,1,3,2,10,0,6,0,3,6,3,0,0,5,4,1,7,2,3,0,3,3,0,1,4,2,2,2,0,0,9,4,5,0,3,6,0,4,4,2,0,5,3,0,0,0,7,0,0,0,2,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,3,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,No
3,5,2,2,5,1,0,4,2,3,5,0,4,4,4,2,4,0,5,4,0,0,0,4,2,4,0,0,5,0,4,5,5,0,4,5,4,1,3,5,1,0,5,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,No
4,33,2,3,2,8,0,7,0,2,7,2,0,0,4,5,0,2,7,0,2,0,2,4,2,0,0,4,5,0,2,7,5,4,0,9,0,0,5,4,0,0,4,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,No

## Data Checks

In [51]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 9,822
Columns: 86
Use sampling: False (sample size: 9,822)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['MOSTYPE', 'MAUT0', 'MSKB1', 'MSKB2', 'PLEVEN', 'MSKD', 'MHHUUR', 'MHKOOP', 'MAUT1', 'MZFONDS']
Rows remaining as candidates after top-10 filter: 8,480 (of 9,822)

#### Duplicate Report
Total duplicate rows: 1442 (14.68% of dataset)
Duplicate rows ignoring target: 1561 (15.89% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [52]:
# Sample Rows
df_head

,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,MRELGE,MRELSA,MRELOV,MFALLEEN,MFGEKIND,MFWEKIND,MOPLHOOG,MOPLMIDD,MOPLLAAG,MBERHOOG,MBERZELF,MBERBOER,MBERMIDD,MBERARBG,MBERARBO,MSKA,MSKB1,MSKB2,MSKC,MSKD,MHHUUR,MHKOOP,MAUT1,MAUT2,MAUT0,MZFONDS,MZPART,MINKM30,MINK3045,MINK4575,MINK7512,MINK123M,MINKGEM,MKOOPKLA,PWAPART,PWABEDR,PWALAND,PPERSAUT,PBESAUT,PMOTSCO,PVRAAUT,PAANHANG,PTRACTOR,PWERKT,PBROM,PLEVEN,PPERSONG,PGEZONG,PWAOREG,PBRAND,PZEILPL,PPLEZIER,PFIETS,PINBOED,PBYSTAND,AWAPART,AWABEDR,AWALAND,APERSAUT,ABESAUT,AMOTSCO,AVRAAUT,AAANHANG,ATRACTOR,AWERKT,ABROM,ALEVEN,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,CARAVAN
0,31,1,3,3,7,0,2,4,4,9,0,0,0,3,6,0,4,5,1,0,0,3,3,2,2,2,2,5,1,9,0,5,3,2,6,3,0,4,5,1,0,4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,No
1,10,1,4,3,3,5,3,1,1,8,1,1,1,1,8,1,5,3,1,0,0,5,3,1,1,3,3,3,0,1,8,9,0,0,5,4,3,2,4,0,0,4,8,2,0,0,6,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,No
2,40,1,3,2,10,0,6,0,3,6,3,0,0,5,4,1,7,2,3,0,3,3,0,1,4,2,2,2,0,0,9,4,5,0,3,6,0,4,4,2,0,5,3,0,0,0,7,0,0,0,2,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,3,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,No
3,5,2,2,5,1,0,4,2,3,5,0,4,4,4,2,4,0,5,4,0,0,0,4,2,4,0,0,5,0,4,5,5,0,4,5,4,1,3,5,1,0,5,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,No
4,33,2,3,2,8,0,7,0,2,7,2,0,0,4,5,0,2,7,0,2,0,2,4,2,0,0,4,5,0,2,7,5,4,0,9,0,0,5,4,0,0,4,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,No

In [53]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,MOSTYPE,category,0.0,0.0,40.0,"33, 38, 8, 39, 9, 3, 23, 36, 35, 41"
1,MOSHOOFD,category,0.0,0.0,10.0,"8, 3, 9, 1, 5, 7, 2, 10, 6, 4"
2,MGODRK,category,0.0,0.0,10.0,"0, 1, 2, 3, 4, 5, 6, 7, 9, 8"
3,MGODPR,category,0.0,0.0,10.0,"4, 5, 6, 3, 7, 2, 9, 1, 0, 8"
4,MGODOV,category,0.0,0.0,6.0,"0, 1, 2, 3, 4, 5"
5,MGODGE,category,0.0,0.0,10.0,"3, 4, 2, 5, 0, 6, 1, 7, 9, 8"
6,MRELGE,category,0.0,0.0,10.0,"7, 6, 5, 9, 8, 4, 3, 2, 1, 0"
7,MRELSA,category,0.0,0.0,8.0,"0, 1, 2, 3, 4, 5, 6, 7"
8,MRELOV,category,0.0,0.0,10.0,"2, 0, 3, 4, 1, 5, 6, 7, 9, 8"
9,MFALLEEN,category,0.0,0.0,10.0,"0, 2, 1, 3, 4, 5, 6, 7, 8, 9"
10,MFGEKIND,category,0.0,0.0,10.0,"3, 4, 2, 5, 0, 1, 6, 7, 9, 8"
11,MFWEKIND,category,0.0,0.0,10.0,"4, 5, 3, 6, 2, 7, 1, 8, 9, 0"
12,MOPLHOOG,category,0.0,0.0,10.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
13,MOPLMIDD,category,0.0,0.0,10.0,"4, 3, 2, 5, 0, 1, 6, 7, 9, 8"
14,MOPLLAAG,category,0.0,0.0,10.0,"5, 6, 4, 3, 2, 7, 9, 0, 8, 1"
15,MBERHOOG,category,0.0,0.0,10.0,"0, 2, 1, 3, 4, 5, 6, 7, 9, 8"
16,MBERZELF,category,0.0,0.0,6.0,"0, 1, 2, 5, 3, 4"
17,MBERBOER,category,0.0,0.0,10.0,"0, 1, 2, 3, 4, 5, 6, 8, 9, 7"
18,MBERMIDD,category,0.0,0.0,10.0,"2, 3, 4, 0, 5, 1, 6, 7, 9, 8"
19,MBERARBG,category,0.0,0.0,10.0,"2, 0, 3, 1, 4, 5, 6, 7, 8, 9"
20,MBERARBO,category,0.0,0.0,10.0,"2, 3, 1, 0, 4, 5, 6, 7, 9, 8"
21,MSKA,category,0.0,0.0,10.0,"0, 1, 2, 3, 4, 5, 6, 7, 9, 8"
22,MSKB1,category,0.0,0.0,10.0,"2, 1, 0, 3, 4, 5, 6, 9, 8, 7"
23,MSKB2,category,0.0,0.0,10.0,"2, 3, 0, 1, 4, 5, 6, 8, 7, 9"
24,MSKC,category,0.0,0.0,10.0,"5, 4, 3, 2, 6, 0, 1, 7, 9, 8"
25,MSKD,category,0.0,0.0,10.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
26,MHHUUR,category,0.0,0.0,10.0,"0, 9, 2, 3, 4, 8, 5, 1, 7, 6"
27,MHKOOP,category,0.0,0.0,10.0,"9, 0, 7, 6, 5, 1, 4, 8, 2, 3"
28,MAUT1,category,0.0,0.0,10.0,"6, 7, 5, 9, 4, 8, 3, 2, 0, 1"
29,MAUT2,category,0.0,0.0,9.0,"0, 2, 1, 3, 4, 5, 6, 7, 9"
30,MAUT0,category,0.0,0.0,10.0,"2, 0, 3, 1, 4, 5, 6, 7, 9, 8"
31,MZFONDS,category,0.0,0.0,10.0,"7, 5, 6, 9, 8, 4, 2, 3, 0, 1"
32,MZPART,category,0.0,0.0,10.0,"2, 4, 0, 3, 1, 5, 7, 6, 9, 8"
33,MINKM30,category,0.0,0.0,10.0,"0, 2, 3, 1, 4, 5, 6, 7, 9, 8"
34,MINK3045,category,0.0,0.0,10.0,"4, 3, 5, 2, 0, 6, 1, 7, 9, 8"
35,MINK4575,category,0.0,0.0,10.0,"3, 2, 4, 0, 1, 5, 6, 7, 9, 8"
36,MINK7512,category,0.0,0.0,10.0,"0, 1, 2, 3, 4, 5, 6, 8, 9, 7"
37,MINK123M,category,0.0,0.0,9.0,"0, 1, 2, 3, 4, 5, 6, 7, 9"
38,MINKGEM,category,0.0,0.0,10.0,"3, 4, 5, 2, 6, 7, 8, 1, 0, 9"
39,MKOOPKLA,category,0.0,0.0,8.0,"3, 6, 4, 5, 1, 7, 2, 8"
40,PWAPART,category,0.0,0.0,4.0,"0, 2, 1, 3"
41,PWABEDR,category,0.0,0.0,7.0,"0, 2, 3, 4, 1, 5, 6"
42,PWALAND,category,0.0,0.0,5.0,"0, 4, 3, 2, 1"
43,PPERSAUT,category,0.0,0.0,7.0,"0, 6, 5, 7, 8, 4, 9"
44,PBESAUT,category,0.0,0.0,4.0,"0, 6, 5, 7"
45,PMOTSCO,category,0.0,0.0,6.0,"0, 4, 6, 5, 3, 7"
46,PVRAAUT,category,0.0,0.0,5.0,"0, 6, 7, 4, 9"
47,PAANHANG,category,0.0,0.0,6.0,"0, 2, 1, 3, 4, 5"
48,PTRACTOR,category,0.0,0.0,6.0,"0, 3, 4, 5, 6, 7"
49,PWERKT,category,0.0,0.0,6.0,"0, 4, 3, 2, 6, 1"
50,PBROM,category,0.0,0.0,6.0,"0, 3, 4, 2, 5, 6"
51,PLEVEN,category,0.0,0.0,10.0,"0, 4, 3, 5, 6, 2, 1, 7, 8, 9"
52,PPERSONG,category,0.0,0.0,7.0,"0, 2, 3, 1, 4, 5, 6"
53,PGEZONG,category,0.0,0.0,3.0,"0, 2, 3"
54,PWAOREG,category,0.0,0.0,5.0,"0, 6, 7, 4, 5"
55,PBRAND,category,0.0,0.0,9.0,"0, 4, 3, 2, 5, 6, 1, 7, 8"
56,PZEILPL,category,0.0,0.0,4.0,"0, 2, 1, 3"
57,PPLEZIER,category,0.0,0.0,7.0,"0, 4, 2, 1, 3, 5, 6"
58,PFIETS,category,0.0,0.0,2.0,"0, 1"
59,PINBOED,category,0.0,0.0,7.0,"0, 1, 2, 4, 3, 6, 5"
60,PBYSTAND,category,0.0,0.0,5.0,"0, 4, 3, 2, 5"
61,CARAVAN,category,0.0,0.0,2.0,"No, Yes"
62,MAANTHUI,int64,0.0,0.0,9.0,"1, 2, 3, 7, 4, 6, 5, 10, 8"
63,MGEMOMV,int64,0.0,0.0,6.0,"3, 2, 4, 1, 5, 6"
64,MGEMLEEF,int64,0.0,0.0,6.0,"3, 2, 4, 5, 1, 6"
65,AWAPART,int64,0.0,0.0,3.0,"0, 1, 2"
66,AWABEDR,int64,0.0,0.0,3.0,"0, 1, 5"
67,AWALAND,int64,0.0,0.0,2.0,"0, 1"
68,APERSAUT,int64,0.0,0.0,9.0,"0, 1, 2, 3, 4, 6, 5, 12, 7"
69,ABESAUT,int64,0.0,0.0,6.0,"0, 1, 2, 3, 5, 4"
70,AMOTSCO,int64,0.0,0.0,5.0,"0, 1, 2, 3, 8"
71,AVRAAUT,int64,0.0,0.0,5.0,"0, 1, 2, 4, 3"
72,AAANHANG,int64,0.0,0.0,4.0,"0, 1, 2, 3"
73,ATRACTOR,int64,0.0,0.0,7.0,"0, 1, 2, 3, 4, 6, 5"
74,AWERKT,int64,0.0,0.0,6.0,"0, 1, 2, 3, 4, 6"
75,ABROM,int64,0.0,0.0,4.0,"0, 1, 2, 3"
76,ALEVEN,int64,0.0,0.0,7.0,"0, 1, 2, 3, 4, 5, 8"
77,APERSONG,int64,0.0,0.0,2.0,"0, 1"
78,AGEZONG,int64,0.0,0.0,2.0,"0, 1"
79,AWAOREG,int64,0.0,0.0,3.0,"0, 1, 2"
80,ABRAND,int64,0.0,0.0,8.0,"1, 0, 2, 3, 4, 5, 6, 7"
81,AZEILPL,int64,0.0,0.0,2.0,"0, 1"
82,APLEZIER,int64,0.0,0.0,3.0,"0, 1, 2"
83,AFIETS,int64,0.0,0.0,5.0,"0, 1, 2, 3, 4"
84,AINBOED,int64,0.0,0.0,3.0,"0, 1, 2"
85,ABYSTAND,int64,0.0,0.0,3.0,"0, 1, 2"

In [54]:
# Numeric Feature Statistics
numeric_stats

           count      mean       std  min   max
MAANTHUI  9822.0  1.108735  0.412101  1.0  10.0
MGEMOMV   9822.0  2.677561  0.780701  1.0   6.0
MGEMLEEF  9822.0  2.996437  0.804660  1.0   6.0
AWAPART   9822.0  0.400020  0.492001  0.0   2.0
AWABEDR   9822.0  0.014050  0.126058  0.0   5.0
AWALAND   9822.0  0.021279  0.144319  0.0   1.0
APERSAUT  9822.0  0.557218  0.608575  0.0  12.0
ABESAUT   9822.0  0.011098  0.129928  0.0   5.0
AMOTSCO   9822.0  0.040216  0.223622  0.0   8.0
AVRAAUT   9822.0  0.002240  0.068402  0.0   4.0
AAANHANG  9822.0  0.011403  0.116251  0.0   3.0
ATRACTOR  9822.0  0.034413  0.249706  0.0   6.0
AWERKT    9822.0  0.005192  0.109954  0.0   6.0
ABROM     9822.0  0.071065  0.267432  0.0   3.0
ALEVEN    9822.0  0.079821  0.384431  0.0   8.0
APERSONG  9822.0  0.004582  0.067535  0.0   1.0
AGEZONG   9822.0  0.007941  0.088764  0.0   1.0
AWAOREG   9822.0  0.004276  0.071224  0.0   2.0
ABRAND    9822.0  0.574018  0.561255  0.0   7.0
AZEILPL   9822.0  0.000916  0.030258  0.0   1.0
APLEZIER  9822.0  0.005091  0.077996  0.0   2.0
AFIETS    9822.0  0.031460  0.209070  0.0   4.0
AINBOED   9822.0  0.008450  0.092647  0.0   2.0
ABYSTAND  9822.0  0.013846  0.117728  0.0   2.0

In [55]:
# Categorical Feature Statistics
cat_stats

              value  count    pct
column   rank
CARAVAN  1       No   9236  94.03
         2      Yes    586   5.97
MAUT0    1        2   2611  26.58
         2        0   2475  25.20
         3        3   1871  19.05
         4        1   1327  13.51
         5        4   1020  10.38
MAUT1    1        6   2822  28.73
         2        7   2338  23.80
         3        5   2106  21.44
         4        9    829   8.44
         5        4    740   7.53
MAUT2    1        0   3078  31.34
         2        2   2999  30.53
         3        1   2454  24.98
         4        3    638   6.50
         5        4    531   5.41
MBERARBG 1        2   2327  23.69
         2        0   1995  20.31
         3        3   1967  20.03
         4        1   1523  15.51
         5        4   1006  10.24
MBERARBO 1        2   2460  25.05
         2        3   1817  18.50
         3        1   1685  17.16
         4        0   1636  16.66
         5        4   1289  13.12
MBERBOER 1        0   6985  71.12
         2        1   1462  14.88
         3        2    815   8.30
         4        3    256   2.61
         5        4    144   1.47
MBERHOOG 1        0   2576  26.23
         2        2   2278  23.19
         3        1   2119  21.57
         4        3   1282  13.05
         5        4    641   6.53
MBERMIDD 1        2   2508  25.53
         2        3   2348  23.91
         3        4   1573  16.02
         4        0   1164  11.85
         5        5    726   7.39
MBERZELF 1        0   7031  71.58
         2        1   2009  20.45
         3        2    600   6.11
         4        5     94   0.96
         5        3     70   0.71
MFALLEEN 1        0   2916  29.69
         2        2   2143  21.82
         3        1   1619  16.48
         4        3   1439  14.65
         5        4    890   9.06
MFGEKIND 1        3   2517  25.63
         2        4   2493  25.38
         3        2   1798  18.31
         4        5   1043  10.62
         5        0    613   6.24
MFWEKIND 1        4   1983  20.19
         2        5   1869  19.03
         3        3   1596  16.25
         4        6   1322  13.46
         5        2   1096  11.16
MGODGE   1        3   2476  25.21
         2        4   2245  22.86
         3        2   1778  18.10
         4        5   1572  16.00
         5        0    773   7.87
MGODOV   1        0   3460  35.23
         2        1   3391  34.52
         3        2   2294  23.36
         4        3    415   4.23
         5        4    220   2.24
MGODPR   1        4   2666  27.14
         2        5   2533  25.79
         3        6   1180  12.01
         4        3   1022  10.41
         5        7    995  10.13
MGODRK   1        0   5420  55.18
         2        1   2744  27.94
         3        2   1213  12.35
         4        3    243   2.47
         5        4    123   1.25
MHHUUR   1        0   1663  16.93
         2        9   1255  12.78
         3        2   1177  11.98
         4        3    961   9.78
         5        4    908   9.24
MHKOOP   1        9   1663  16.93
         2        0   1255  12.78
         3        7   1185  12.06
         4        6    978   9.96
         5        5    912   9.29
MINK123M 1        0   8253  84.03
         2        1   1269  12.92
         3        2    188   1.91
         4        3     66   0.67
         5        4     38   0.39
MINK3045 1        4   2207  22.47
         2        3   1989  20.25
         3        5   1585  16.14
         4        2   1569  15.97
         5        0    782   7.96
MINK4575 1        3   2028  20.65
         2        2   1962  19.98
         3        4   1709  17.40
         4        0   1505  15.32
         5        1   1132  11.53
MINK7512 1        0   5464  55.63
         2        1   2251  22.92
         3        2   1256  12.79
         4        3    429   4.37
         5        4    278   2.83
MINKGEM  1        3   3232  32.91
         2        4   3063  31.19
         3        5   1268  12.91
         4        2   1110  11.30
         5        6    646   6.58
MINKM30  1        0   2164  22.03
         2        2   1893  19.27
         3        3   1826  18.59
         4        1   1060  10.79
         5        4    981   9.99
MKOOPKLA 1        3   2556  26.02
         2        6   1587  16.16
         3        4   1539  15.67
         4        5    964   9.81
         5        1    938   9.55
MOPLHOOG 1        0   3621  36.87
         2        1   2176  22.15
         3        2   1921  19.56
         4        3    927   9.44
         5        4    577   5.87
MOPLLAAG 1        5   1740  17.72
         2        6   1472  14.99
         3        4   1448  14.74
         4        3   1128  11.48
         5        2   1099  11.19
MOPLMIDD 1        4   2394  24.37
         2        3   2332  23.74
         3        2   1648  16.78
         4        5   1227  12.49
         5        0    711   7.24
MOSHOOFD 1        8   2694  27.43
         2        3   1513  15.40
         3        9   1111  11.31
         4        1    959   9.76
         5        5    940   9.57
MOSTYPE  1       33   1401  14.26
         2       38    569   5.79
         3        8    546   5.56
         4       39    542   5.52
         5        9    460   4.68
MRELGE   1        7   2800  28.51
         2        6   2015  20.52
         3        5   1628  16.58
         4        9   1345  13.69
         5        8    603   6.14
MRELOV   1        2   2944  29.97
         2        0   1981  20.17
         3        3   1965  20.01
         4        4   1140  11.61
         5        1    900   9.16
MRELSA   1        0   4185  42.61
         2        1   3402  34.64
         3        2   1790  18.22
         4        3    260   2.65
         5        4    133   1.35
MSKA     1        0   2871  29.23
         2        1   2626  26.74
         3        2   2056  20.93
         4        3   1168  11.89
         5        4    452   4.60
MSKB1    1        2   3009  30.64
         2        1   2549  25.95
         3        0   2275  23.16
         4        3   1300  13.24
         5        4    459   4.67
MSKB2    1        2   2778  28.28
         2        3   2025  20.62
         3        0   1694  17.25
         4        1   1434  14.60
         5        4   1104  11.24
MSKC     1        5   1953  19.88
         2        4   1929  19.64
         3        3   1845  18.78
         4        2   1468  14.95
         5        6    800   8.14
MSKD     1        0   4376  44.55
         2        1   2658  27.06
         3        2   1434  14.60
         4        3    757   7.71
         5        4    378   3.85
MZFONDS  1        7   2520  25.66
         2        5   1644  16.74
         3        6   1451  14.77
         4        9   1436  14.62
         5        8   1178  11.99
MZPART   1        2   2520  25.66
         2        4   1668  16.98
         3        0   1436  14.62
         4        3   1415  14.41
         5        1   1178  11.99
PAANHANG 1        0   9719  98.95
         2        2     62   0.63
         3        1     30   0.31
         4        3      9   0.09
         5        4      1   0.01
PBESAUT  1        0   9730  99.06
         2        6     71   0.72
         3        5     17   0.17
         4        7      4   0.04
PBRAND   1        0   4464  45.45
         2        4   2142  21.81
         3        3   1541  15.69
         4        2    901   9.17
         5        5    263   2.68
PBROM    1        0   9150  93.16
         2        3    481   4.90
         3        4     99   1.01
         4        2     63   0.64
         5        5     27   0.27
PBYSTAND 1        0   9687  98.63
         2        4     68   0.69
         3        3     34   0.35
         4        2     31   0.32
         5        5      2   0.02
PFIETS   1        0   9573  97.46
         2        1    249   2.54
PGEZONG  1        0   9744  99.21
         2        2     50   0.51
         3        3     28   0.29
PINBOED  1        0   9740  99.17
         2        1     34   0.35
         3        2     30   0.31
         4        4      8   0.08
         5        3      7   0.07
PLEVEN   1        0   9308  94.77
         2        4    172   1.75
         3        3    141   1.44
         4        5     65   0.66
         5        6     65   0.66
PMOTSCO  1        0   9460  96.31
         2        4    207   2.11
         3        6     79   0.80
         4        5     70   0.71
         5        3      4   0.04
PPERSAUT 1        0   4825  49.12
         2        6   3910  39.81
         3        5   1013  10.31
         4        7     64   0.65
         5        8      5   0.05
PPERSONG 1        0   9777  99.54
         2        2     24   0.24
         3        3      7   0.07
         4        1      6   0.06
         5        4      4   0.04
PPLEZIER 1        0   9777  99.54
         2        4     18   0.18
         3        2      8   0.08
         4        1      6   0.06
         5        3      6   0.06
PTRACTOR 1        0   9576  97.50
         2        3    142   1.45
         3        4     45   0.46
         4        5     42   0.43
         5        6     16   0.16
PVRAAUT  1        0   9808  99.86
         2        6     10   0.10
         3        7      2   0.02
         4        4      1   0.01
         5        9      1   0.01
PWABEDR  1        0   9688  98.64
         2        2     53   0.54
         3        3     36   0.37
         4        4     26   0.26
         5        1      9   0.09
PWALAND  1        0   9613  97.87
         2        4    108   1.10
         3        3     92   0.94
         4        2      7   0.07
         5        1      2   0.02
PWAOREG  1        0   9784  99.61
         2        6     32   0.33
         3        7      4   0.04
         4        4      1   0.01
         5        5      1   0.01
PWAPART  1        0   5903  60.10
         2        2   3562  36.27
         3        1    341   3.47
         4        3     16   0.16
PWERKT   1        0   9790  99.67
         2        4     11   0.11
         3        3      8   0.08
         4        2      7   0.07
         5        6      5   0.05
PZEILPL  1        0   9813  99.91
         2        2      5   0.05
         3        1      3   0.03
         4        3      1   0.01

In [56]:
# Target Distribution
target_df

         count    pct
CARAVAN
No        9236  94.03
Yes        586   5.97

## Task Curation

In [57]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [58]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [59]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019d1b44-3904-7f10-88c9-328d66ac0b6c
940992d048cda7b978b05f91209bf8c9cc364c7c8a7c47f94fc8dc4212ee9630