### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="superconductivity",
    dataset_year="2018",
    domain_str="physics & astronomy",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C53P47",
    download_description="""
We download the data from the UCI repository and uzip it to a predefined folder.

mkdir -p local-data-warehouse/superconductivity/ && wget -P local-data-warehouse/superconductivity/ https://archive.ics.uci.edu/static/public/464/superconductivty+data.zip && unzip local-data-warehouse/superconductivity/superconductivty+data.zip -d local-data-warehouse/superconductivity/ && rm local-data-warehouse/superconductivity/superconductivty+data.zip
""",
    # References
    academic_reference_bibtex="""@article{hamidieh2018data,
  title={A data-driven statistical model for predicting the critical temperature of a superconductor},
  author={Hamidieh, Kam},
  journal={Computational Materials Science},
  volume={154},
  pages={346--354},
  year={2018},
  publisher={Elsevier}
}
""",
    academic_reference_bibtex_key="hamidieh2018data",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
- Anomaly: the data has a lot of duplicates (29%) when ignoring the target feature
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="critical_temp",
    problem_type="regression",
    objective_metric_name="rmse",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(f"{dataset_mold.path}/train.csv")

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 21,263
Columns: 82
Use sampling: False (sample size: 21,263)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['wtd_gmean_atomic_mass', 'wtd_mean_atomic_mass', 'wtd_entropy_atomic_mass', 'wtd_gmean_fie', 'wtd_entropy_Density', 'wtd_gmean_Density', 'wtd_entropy_fie', 'wtd_std_atomic_mass', 'wtd_mean_Density', 'wtd_gmean_atomic_radius']
Rows remaining as candidates after top-10 filter: 8,513 (of 21,263)

#### Duplicate Report
Total duplicate rows: 66 (0.31% of dataset)
Duplicate rows ignoring target: 6093 (28.66% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,wtd_std_atomic_mass,mean_fie,wtd_mean_fie,gmean_fie,wtd_gmean_fie,entropy_fie,wtd_entropy_fie,range_fie,wtd_range_fie,std_fie,wtd_std_fie,mean_atomic_radius,wtd_mean_atomic_radius,gmean_atomic_radius,wtd_gmean_atomic_radius,entropy_atomic_radius,wtd_entropy_atomic_radius,range_atomic_radius,wtd_range_atomic_radius,std_atomic_radius,wtd_std_atomic_radius,mean_Density,wtd_mean_Density,gmean_Density,wtd_gmean_Density,entropy_Density,wtd_entropy_Density,range_Density,wtd_range_Density,std_Density,wtd_std_Density,mean_ElectronAffinity,wtd_mean_ElectronAffinity,gmean_ElectronAffinity,wtd_gmean_ElectronAffinity,entropy_ElectronAffinity,wtd_entropy_ElectronAffinity,range_ElectronAffinity,wtd_range_ElectronAffinity,std_ElectronAffinity,wtd_std_ElectronAffinity,mean_FusionHeat,wtd_mean_FusionHeat,gmean_FusionHeat,wtd_gmean_FusionHeat,entropy_FusionHeat,wtd_entropy_FusionHeat,range_FusionHeat,wtd_range_FusionHeat,std_FusionHeat,wtd_std_FusionHeat,mean_ThermalConductivity,wtd_mean_ThermalConductivity,gmean_ThermalConductivity,wtd_gmean_ThermalConductivity,entropy_ThermalConductivity,wtd_entropy_ThermalConductivity,range_ThermalConductivity,wtd_range_ThermalConductivity,std_ThermalConductivity,wtd_std_ThermalConductivity,mean_Valence,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
0,2,82.768190,87.837285,82.144935,87.360109,0.685627,0.509575,20.27638,51.522285,10.138190,8.779930,711.80,687.700000,710.166178,686.488365,0.690853,0.589409,96.4,307.700000,48.200000,41.742424,161.500000,179.750000,157.321327,176.492557,0.667386,0.461943,73,117.250000,36.500000,31.609927,6946.500000,7758.250000,6754.118003,7608.074085,0.665582,0.458299,3247.000,5096.750000,1623.500000,1405.992243,104.050000,95.825000,102.741423,94.869113,0.680597,0.622557,32.90,35.575000,16.450000,14.246118,29.3000,28.050000,29.193150,27.970992,0.689503,0.596157,5.000,12.150000,2.500000,2.165064,57.000000,55.500000,56.920998,55.441265,0.691761,0.583527,6.00000,25.500000,3.000000,2.598076,4.50,4.750000,4.472136,4.728708,0.686962,0.514653,1,2.750000,0.500000,0.433013,6.4
1,4,76.444563,81.456750,59.356672,68.229617,1.199541,1.108189,121.32760,36.950657,43.823354,40.612293,794.00,738.357143,741.629349,702.424197,1.315004,1.282439,810.6,231.371429,311.743492,255.465227,164.500000,171.571429,139.000514,153.255987,1.256701,1.166832,205,65.428571,77.525802,67.911407,4235.857250,5481.918429,669.556588,1780.077447,1.015407,0.810985,8958.571,3839.795857,3194.938946,3275.968307,77.237500,80.600000,53.527965,56.435929,1.105182,0.953371,127.05,46.971429,54.830755,52.650295,8.1805,9.560286,4.035569,6.229663,1.112098,0.975148,12.878,5.582571,4.948155,4.359650,108.756645,179.003797,7.552385,26.578636,0.336262,0.201966,399.97342,171.424774,168.301047,191.475655,2.25,2.142857,2.213364,2.119268,1.368922,1.309526,1,0.571429,0.433013,0.349927,91.2
2,5,88.936744,51.090431,70.358975,34.783991,1.445824,1.525092,122.90607,10.438667,46.482335,44.261233,743.42,1006.991437,696.313849,942.154532,1.538527,0.933542,810.6,690.076300,296.615154,340.103711,170.600000,111.914373,148.737352,88.458069,1.506998,1.509873,205,25.802752,70.406250,75.991199,4617.885800,3035.177165,1043.153792,66.205693,1.324548,0.978095,8958.571,2054.272376,2958.021492,3686.008724,71.690000,110.674694,52.696967,90.754610,1.354052,0.815880,127.05,75.361239,50.281492,47.273696,7.8044,5.154569,4.411557,1.310299,1.374615,1.153108,12.878,2.884422,4.489231,5.622243,89.605316,95.618363,8.418912,1.058389,0.457810,0.209583,399.97342,91.728732,155.329609,166.192923,2.40,2.114679,2.352158,2.095193,1.589027,1.314189,1,0.967890,0.489898,0.318634,38.0
3,4,76.517718,56.149432,59.310096,35.562124,1.197273,1.042132,122.90607,31.920690,44.289459,51.815571,787.05,1011.642286,734.219624,940.469590,1.313008,0.802473,772.0,731.520000,314.505966,353.685876,151.750000,104.680000,131.302197,84.236452,1.275274,1.215773,171,41.520000,65.579627,67.580981,4434.357250,2916.268000,674.484751,52.847119,0.995983,0.807732,8958.571,1544.463429,3402.856196,3563.512853,79.607500,111.226743,48.477265,95.882106,1.096672,0.773969,135.97,81.204686,54.373097,43.628244,6.9055,3.856571,3.479475,1.042408,1.088575,1.016669,12.878,1.744571,4.599064,4.673780,112.006645,61.626617,8.339818,0.637507,0.403693,0.304547,399.97342,57.127669,166.742351,138.361103,2.25,2.251429,2.213364,2.214646,1.368922,1.078855,1,1.074286,0.433013,0.433834,19.0
4,3,104.608490,89.558979,101.719818,88.481210,1.070258,0.944284,59.94547,33.541423,25.225148,15.159829,722.10,812.626104,703.695276,799.630186,1.072790,0.796138,399.3,469.515797,165.133461,141.219887,162.666667,143.728246,156.269832,137.110827,1.062146,0.913764,92,64.036145,42.240055,43.743683,7081.666667,7095.665328,6727.404359,6633.555886,1.046587,0.841524,5461.000,3741.817938,2325.544285,2627.642628,106.466667,137.813253,89.376074,121.321040,0.925747,0.621554,147.00,102.106426,64.406539,63.255476,15.9000,17.745783,10.699060,11.681349,0.726384,0.547497,30.600,14.061446,14.217595,14.955962,50.840000,56.919679,9.794610,6.007072,0.313841,0.106068,138.48000,55.544846,62.546392,67.307993,5.00,5.811245,4.762203,5.743954,1.054920,0.803990,3,3.024096,1.414214,0.728448,11.0

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,mean_atomic_mass,float64,0.0,0.0,3365.0,"76.4446, 76.5177, 83.2448, 74.2317, 89.3372, 88.9367, 72.3247, 88.9445, 79.1712, 104.3656"
1,wtd_mean_atomic_mass,float64,0.0,0.0,15164.0,"51.2457, 59.2244, 56.8088, 15.309, 76.633, 81.4567, 97.0463, 49.7159, 59.3441, 56.4425"
2,gmean_atomic_mass,float64,0.0,0.0,3365.0,"59.3567, 59.3101, 59.5061, 60.5152, 70.5606, 70.359, 58.6371, 66.3616, 59.9949, 72.7469"
3,wtd_gmean_atomic_mass,float64,0.0,0.0,15165.0,"34.9353, 36.1262, 35.7734, 14.1626, 42.6054, 68.2296, 73.6759, 34.5124, 36.4969, 35.6559"
4,entropy_atomic_mass,float64,0.0,0.0,3314.0,"1.1995, 1.1973, 1.3115, 0.0, 1.4537, 1.4445, 1.4458, 1.4446, 1.1818, 1.39"
5,wtd_entropy_atomic_mass,float64,0.0,0.0,15113.0,"0.0, 1.2919, 1.3721, 0.9819, 0.6914, 1.1586, 1.1082, 1.1986, 1.2908, 1.0106"
6,range_atomic_mass,float64,0.0,0.0,1042.0,"121.3276, 192.981, 122.9061, 128.2426, 124.9082, 188.3839, 184.5906, 141.2506, 191.2006, 134.3606"
7,wtd_range_atomic_mass,float64,0.0,0.0,12641.0,"0.0, 36.9507, 12.5122, 50.2452, 14.2883, 17.5627, 25.1922, 40.1961, 22.7487, 18.9594"
8,std_atomic_mass,float64,0.0,0.0,3313.0,"43.8234, 44.2895, 67.2338, 0.0, 39.4459, 46.9177, 46.4823, 40.0535, 51.9688, 50.425"
9,wtd_std_atomic_mass,float64,0.0,0.0,15031.0,"0.0, 44.1921, 64.1963, 52.5332, 6.3611, 75.2195, 40.6123, 68.2777, 42.227, 55.864"
10,mean_fie,float64,0.0,0.0,2997.0,"794.0, 787.05, 779.88, 816.36, 740.52, 787.02, 743.42, 775.425, 738.22, 891.65"
11,wtd_mean_fie,float64,0.0,0.0,14940.0,"1003.6231, 1005.8667, 1011.5407, 779.2333, 982.4, 737.0375, 738.3571, 1007.0133, 788.75, 1008.8129"
12,gmean_fie,float64,0.0,0.0,3286.0,"741.6293, 734.2196, 740.3993, 771.891, 692.5413, 745.091, 696.3138, 718.1529, 690.3281, 838.5849"
13,wtd_gmean_fie,float64,0.0,0.0,15089.0,"937.5592, 945.3714, 940.2943, 778.6586, 905.2205, 702.4242, 709.1597, 944.2692, 935.5287, 940.3917"
14,entropy_fie,float64,0.0,0.0,3238.0,"1.315, 1.313, 1.5532, 0.0, 1.5525, 1.537, 1.5517, 1.5385, 1.306, 1.5366"
15,wtd_entropy_fie,float64,0.0,0.0,15058.0,"0.0, 0.8905, 1.0192, 0.7869, 0.6233, 0.8772, 1.2824, 1.5671, 0.8835, 0.7832"
16,range_fie,float64,0.0,0.0,854.0,"810.6, 764.1, 772.0, 773.0, 781.6, 786.5, 0.0, 894.6, 443.7, 1138.9"
17,wtd_range_fie,float64,0.0,0.0,12266.0,"0.0, 738.7693, 659.7154, 661.0267, 738.5786, 698.9523, 648.5091, 253.4475, 112.575, 287.7"
18,std_fie,float64,0.0,0.0,3185.0,"311.7435, 314.506, 276.0631, 0.0, 282.3953, 298.643, 279.1811, 296.6152, 323.8118, 299.032"
19,wtd_std_fie,float64,0.0,0.0,14922.0,"0.0, 342.396, 333.2384, 353.8198, 29.6513, 367.1544, 255.4652, 230.9812, 335.3152, 357.4502"
20,mean_atomic_radius,float64,0.0,0.0,942.0,"164.5, 149.8, 160.0, 151.75, 167.0, 181.0, 150.5, 162.8, 162.0, 160.25"
21,wtd_mean_atomic_radius,float64,0.0,0.0,12423.0,"114.5385, 106.1333, 157.0, 104.3714, 106.3333, 156.0, 113.7273, 171.5714, 112.1333, 115.6154"
22,gmean_atomic_radius,float64,0.0,0.0,3148.0,"139.0005, 131.3022, 133.4253, 139.5953, 155.9382, 148.7374, 142.2453, 136.126, 146.1212, 131.729"
23,wtd_gmean_atomic_radius,float64,0.0,0.0,14969.0,"89.6852, 86.4573, 84.1108, 103.1499, 88.963, 144.683, 153.256, 88.8243, 85.0316, 97.8805"
24,entropy_atomic_radius,float64,0.0,0.0,3111.0,"1.2567, 1.2753, 1.5195, 0.0, 1.5012, 1.4999, 1.507, 1.5045, 1.2592, 1.5088"
25,wtd_entropy_atomic_radius,float64,0.0,0.0,14948.0,"0.0, 1.3397, 1.5732, 1.1601, 0.689, 1.3004, 1.456, 1.1668, 1.3268, 1.1333"
26,wtd_range_atomic_radius,float64,0.0,0.0,11407.0,"0.0, 65.4286, 38.5, 48.75, 22.6154, 16.2667, 55.2857, 55.7143, 35.1231, 46.8429"
27,std_atomic_radius,float64,0.0,0.0,2529.0,"77.5258, 65.5796, 58.6085, 0.0, 69.9228, 76.7932, 1.0, 69.4245, 70.4062, 75.2375"
28,wtd_std_atomic_radius,float64,0.0,0.0,14312.0,"0.0, 79.2354, 66.3193, 67.1115, 27.3415, 79.3532, 67.9114, 51.9832, 76.1077, 70.1132"
29,mean_Density,float64,0.0,0.0,3274.0,"4235.8573, 4434.3573, 4584.2858, 4816.6858, 4716.6858, 4617.8858, 4963.4858, 4565.5715, 4654.3573, 4033.4858"
30,wtd_mean_Density,float64,0.0,0.0,15010.0,"2952.4618, 2953.4288, 2961.4737, 2219.3333, 3608.0522, 5481.9184, 5536.4286, 7310.0, 3156.2288, 6775.0"
31,gmean_Density,float64,0.0,0.0,3332.0,"669.5566, 674.4848, 874.1648, 1074.9035, 1059.4085, 1043.1538, 1096.1473, 724.9532, 843.9453, 883.1173"
32,wtd_gmean_Density,float64,0.0,0.0,15085.0,"66.3422, 64.6229, 53.427, 2190.988, 67.4747, 1814.7681, 1780.0774, 71.2372, 7310.0, 56.4346"
33,entropy_Density,float64,0.0,0.0,3283.0,"1.0154, 0.996, 1.1618, 0.0, 1.3222, 1.3239, 1.3245, 1.318, 1.0331, 1.2248"
34,wtd_entropy_Density,float64,0.0,0.0,15087.0,"0.0, 0.8128, 1.0995, 0.7696, 0.5741, 0.9521, 0.811, 1.0977, 0.7186, 0.8286"
35,range_Density,float64,0.0,0.0,890.0,"8958.571, 9778.571, 11338.571, 13532.571, 11848.571, 7872.571, 0.0, 12368.571, 5870.0, 9064.571"
36,wtd_range_Density,float64,0.0,0.0,9279.0,"2066.9228, 3839.7959, 1303.2379, 0.0, 1623.4834, 2388.5712, 2444.8214, 1279.1834, 1377.6921, 2592.6667"
37,std_Density,float64,0.0,0.0,3265.0,"3194.9389, 3402.8562, 4004.2732, 0.0, 3084.7293, 3015.1107, 2958.0215, 3206.8491, 3306.1629, 3207.2568"
38,wtd_std_Density,float64,0.0,0.0,14939.0,"0.0, 3639.1292, 3977.0608, 3581.8489, 340.3541, 4695.9205, 3275.9683, 3919.1831, 3797.7072, 535.0"
39,mean_ElectronAffinity,float64,0.0,0.0,2377.0,"77.2375, 82.3375, 79.6075, 73.1, 72.09, 62.09, 76.17, 91.35, 69.5, 71.69"
40,wtd_mean_ElectronAffinity,float64,0.0,0.0,13526.0,"110.7385, 113.2714, 81.7167, 109.1692, 105.4753, 83.5143, 19.3, 111.7792, 1.5, 95.2"
41,gmean_ElectronAffinity,float64,0.0,0.0,2678.0,"53.528, 60.7215, 48.4773, 33.1488, 53.1161, 26.1868, 58.7537, 35.6745, 82.0469, 52.697"
42,wtd_gmean_ElectronAffinity,float64,0.0,0.0,13752.0,"103.9473, 89.9629, 65.911, 86.5394, 89.9629, 68.5473, 60.6524, 10.6055, 98.412, 1.5"
43,entropy_ElectronAffinity,float64,0.0,0.0,2635.0,"1.1052, 1.164, 1.0967, 1.2009, 1.3574, 1.1304, 0.0, 1.4028, 1.2852, 1.4264"
44,wtd_entropy_ElectronAffinity,float64,0.0,0.0,14078.0,"0.0, 0.8023, 0.7628, 0.8277, 0.8227, 1.2062, 1.0123, 0.7777, 0.1202, 0.6454"
45,range_ElectronAffinity,float64,0.0,0.0,644.0,"127.05, 138.63, 135.97, 141.0, 127.2, 0.0, 91.0, 312.3, 64.05, 179.3"
46,wtd_range_ElectronAffinity,float64,0.0,0.0,10937.0,"0.0, 74.3538, 75.742, 81.2886, 80.325, 46.9714, 76.4331, 73.94, 29.4913, 29.25"
47,std_ElectronAffinity,float64,0.0,0.0,2562.0,"54.8308, 51.1257, 54.3731, 57.6457, 50.111, 0.0, 57.6447, 47.3627, 53.2352, 40.6432"
48,wtd_std_ElectronAffinity,float64,0.0,0.0,13581.0,"0.0, 47.2166, 39.8077, 48.4608, 49.4457, 50.3438, 52.6708, 12.5865, 42.5579, 39.5424"
49,mean_FusionHeat,float64,0.0,0.0,2660.0,"8.1805, 6.9055, 8.1524, 8.0144, 7.9244, 9.3044, 7.8044, 7.2324, 6.8124, 5.903"
50,wtd_mean_FusionHeat,float64,0.0,0.0,14194.0,"5.2503, 4.9544, 3.8347, 9.5603, 5.4384, 9.0953, 36.2333, 3.5302, 3.8469, 3.9926"
51,gmean_FusionHeat,float64,0.0,0.0,3166.0,"4.0356, 3.4795, 4.6464, 4.5497, 4.4926, 5.1606, 4.4116, 4.1639, 3.8396, 2.7017"
52,wtd_gmean_FusionHeat,float64,0.0,0.0,14767.0,"1.3369, 1.3219, 1.0392, 6.2297, 1.381, 6.2976, 27.9139, 1.0533, 1.041, 1.064"
53,entropy_FusionHeat,float64,0.0,0.0,3108.0,"1.1121, 1.0886, 1.3929, 0.0, 1.3847, 1.3808, 1.3902, 1.3746, 1.3781, 0.9637"
54,wtd_entropy_FusionHeat,float64,0.0,0.0,14885.0,"0.0, 1.0429, 1.3958, 0.964, 0.2789, 1.1788, 0.9751, 1.3311, 0.995, 0.9621"
55,range_FusionHeat,float64,0.0,0.0,595.0,"12.878, 27.478, 13.578, 15.978, 16.978, 10.678, 0.0, 19.7, 34.27, 25.478"
56,wtd_range_FusionHeat,float64,0.0,0.0,9671.0,"2.9035, 1.7446, 5.5826, 1.6283, 0.0, 3.2473, 3.3749, 1.8958, 6.8695, 2.0468"
57,std_FusionHeat,float64,0.0,0.0,2920.0,"4.9482, 4.5991, 4.361, 0.0, 4.4382, 4.4553, 4.9639, 4.4892, 4.1652, 4.3402"
58,wtd_std_FusionHeat,float64,0.0,0.0,14470.0,"0.0, 5.6486, 5.2534, 4.6583, 4.3597, 5.7801, 3.8735, 19.469, 4.2437, 4.6669"
59,mean_ThermalConductivity,float64,0.0,0.0,1980.0,"108.7566, 89.6053, 112.0066, 128.6053, 111.0053, 107.7566, 102.8053, 126.2053, 108.0044, 61.75"
60,wtd_mean_ThermalConductivity,float64,0.0,0.0,13150.0,"96.3989, 72.4142, 71.3333, 61.3438, 65.3333, 179.0038, 60.8295, 48.0145, 114.7368, 110.2142"
61,gmean_ThermalConductivity,float64,0.0,0.0,2737.0,"7.5524, 8.4189, 8.3398, 14.2876, 13.1312, 7.0625, 12.0779, 13.7839, 14.2742, 51.6378"
62,wtd_gmean_ThermalConductivity,float64,0.0,0.0,14152.0,"1.0963, 0.9692, 0.6294, 26.5786, 48.8595, 0.614, 83.2356, 0.8087, 1.2678, 48.8101"
63,entropy_ThermalConductivity,float64,0.0,0.0,2711.0,"0.3363, 0.4578, 0.4037, 0.872, 0.0, 0.7856, 0.3081, 0.7136, 0.835, 0.9345"
64,wtd_entropy_ThermalConductivity,float64,0.0,0.0,14269.0,"0.0, 0.2031, 0.7773, 0.202, 0.2834, 0.5649, 0.1632, 0.7004, 0.2446, 0.7759"
65,range_ThermalConductivity,float64,0.0,0.0,452.0,"399.9734, 78.9734, 133.0, 0.0, 99.9734, 82.0, 78.48, 181.0, 134.0, 123.0"
66,wtd_range_ThermalConductivity,float64,0.0,0.0,7996.0,"57.1277, 92.2934, 53.3192, 171.4248, 0.0, 99.9967, 106.6525, 36.3491, 61.5241, 74.9867"
67,std_ThermalConductivity,float64,0.0,0.0,2492.0,"168.301, 155.3296, 166.7424, 154.008, 0.0, 150.6002, 168.8542, 151.0029, 155.4697, 147.6439"
68,wtd_std_ThermalConductivity,float64,0.0,0.0,13797.0,"0.0, 166.4404, 137.5793, 138.4377, 191.4757, 62.6968, 138.5791, 174.877, 112.6219, 59.0065"
69,mean_Valence,float64,0.0,0.0,63.0,"2.25, 3.0, 2.2, 4.0, 2.6, 5.0, 2.4, 2.5, 4.5, 2.0"
70,wtd_mean_Valence,float64,0.0,0.0,5737.0,"2.0769, 2.0, 3.0, 5.0, 4.5, 6.0, 4.0, 2.1429, 2.8333, 2.2643"
71,gmean_Valence,float64,0.0,0.0,243.0,"2.2134, 2.1689, 2.4915, 2.3522, 2.0, 2.2894, 2.4019, 4.4721, 3.9149, 2.8845"
72,wtd_gmean_Valence,float64,0.0,0.0,8102.0,"2.0634, 2.0, 6.0, 2.1193, 3.0, 2.7495, 2.2262, 2.0548, 4.0, 5.0"
73,entropy_Valence,float64,0.0,0.0,319.0,"1.3689, 1.5942, 1.565, 1.589, 0.6931, 0.673, 0.687, 1.749, 1.7721, 1.0776"
74,wtd_entropy_Valence,float64,0.0,0.0,10778.0,"0.0, 1.2018, 0.5623, 0.6365, 1.3095, 0.5004, 0.673, 0.5147, 0.687, 1.3546"
75,wtd_range_Valence,float64,0.0,0.0,5908.0,"1.0, 0.0, 0.5, 0.8462, 0.8, 3.0, 1.1, 2.0, 0.5714, 1.5"
76,std_Valence,float64,0.0,0.0,125.0,"0.433, 0.4, 0.5, 0.0, 0.4714, 1.0, 0.8, 0.4899, 0.8165, 1.2472"
77,wtd_std_Valence,float64,0.0,0.0,7082.0,"0.0, 0.2665, 0.433, 0.4714, 0.3499, 0.6872, 0.441, 0.5, 0.2494, 1.299"
78,critical_temp,float64,0.0,0.0,3007.0,"80.0, 20.0, 30.0, 90.0, 40.0, 32.0, 35.0, 92.0, 15.0, 25.0"
79,number_of_elements,int64,0.0,0.0,9.0,"5, 4, 3, 2, 6, 7, 1, 8, 9"
80,range_atomic_radius,int64,0.0,0.0,195.0,"205, 171, 139, 199, 53, 0, 80, 33, 147, 185"
81,range_Valence,int64,0.0,0.0,7.0,"1, 2, 3, 4, 0, 5, 6"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
number_of_elements,21263.0,4.115224,1.439295,1.000000,9.000000
mean_atomic_mass,21263.0,87.557631,29.676497,6.941000,208.980400
wtd_mean_atomic_mass,21263.0,72.988310,33.490406,6.423452,208.980400
gmean_atomic_mass,21263.0,71.290627,31.030272,5.320573,208.980400
wtd_gmean_atomic_mass,21263.0,58.539916,36.651067,1.960849,208.980400
entropy_atomic_mass,21263.0,1.165608,0.364930,0.000000,1.983797
wtd_entropy_atomic_mass,21263.0,1.063884,0.401423,0.000000,1.958203
range_atomic_mass,21263.0,115.601251,54.626887,0.000000,207.972460
wtd_range_atomic_mass,21263.0,33.225218,26.967752,0.000000,205.589910
std_atomic_mass,21263.0,44.391893,20.035430,0.000000,101.019700
wtd_std_atomic_mass,21263.0,41.448045,19.983544,0.000000,101.019700
mean_fie,21263.0,769.614748,87.488694,375.500000,1313.100000
wtd_mean_fie,21263.0,870.442317,143.278200,375.500000,1348.028986
gmean_fie,21263.0,737.474751,78.327275,375.500000,1313.100000
wtd_gmean_fie,21263.0,832.769649,119.772520,375.500000,1327.593381
entropy_fie,21263.0,1.299172,0.381935,0.000000,2.157777
wtd_entropy_fie,21263.0,0.926726,0.334018,0.000000,2.038560
range_fie,21263.0,572.222612,309.614442,0.000000,1304.500000
wtd_range_fie,21263.0,483.517264,224.042874,0.000000,1251.855072
std_fie,21263.0,215.631279,109.966774,0.000000,499.671949
wtd_std_fie,21263.0,224.050033,127.927104,0.000000,479.162305
mean_atomic_radius,21263.0,157.983101,20.147288,48.000000,298.000000
wtd_mean_atomic_radius,21263.0,134.720039,28.801567,48.000000,298.000000
gmean_atomic_radius,21263.0,144.448738,22.090958,48.000000,298.000000
wtd_gmean_atomic_radius,21263.0,120.989330,35.837843,48.000000,298.000000
entropy_atomic_radius,21263.0,1.267756,0.375411,0.000000,2.141961
wtd_entropy_atomic_radius,21263.0,1.131138,0.407159,0.000000,1.903748
range_atomic_radius,21263.0,139.325025,67.272228,0.000000,256.000000
wtd_range_atomic_radius,21263.0,51.369885,35.019356,0.000000,240.164344
std_atomic_radius,21263.0,51.601267,22.898396,0.000000,115.500000
wtd_std_atomic_radius,21263.0,52.340465,25.294524,0.000000,97.140711
mean_Density,21263.0,6111.465214,2846.785185,1.429000,22590.000000
wtd_mean_Density,21263.0,5267.188547,3221.314506,1.429000,22590.000000
gmean_Density,21263.0,3460.692235,3703.256370,1.429000,22590.000000
wtd_gmean_Density,21263.0,3117.241110,3975.122587,0.686245,22590.000000
entropy_Density,21263.0,1.072425,0.342356,0.000000,1.954297
wtd_entropy_Density,21263.0,0.856037,0.319761,0.000000,1.703420
range_Density,21263.0,8665.438818,4097.126831,0.000000,22588.571000
wtd_range_Density,21263.0,2902.736814,2398.471020,0.000000,22434.160000
std_Density,21263.0,3416.910784,1673.624915,0.000000,10724.374500
wtd_std_Density,21263.0,3319.170628,1611.799629,0.000000,10410.932005
mean_ElectronAffinity,21263.0,76.879751,27.701890,1.500000,326.100000
wtd_mean_ElectronAffinity,21263.0,92.717486,32.276387,1.500000,326.100000
gmean_ElectronAffinity,21263.0,54.359502,29.007425,1.500000,326.100000
wtd_gmean_ElectronAffinity,21263.0,72.416225,31.648444,1.500000,326.100000
entropy_ElectronAffinity,21263.0,1.070250,0.343391,0.000000,1.767732
wtd_entropy_ElectronAffinity,21263.0,0.770757,0.285986,0.000000,1.675400
range_ElectronAffinity,21263.0,120.730514,58.700327,0.000000,349.000000
wtd_range_ElectronAffinity,21263.0,59.332637,28.620409,0.000000,218.696600
std_ElectronAffinity,21263.0,48.912207,21.740521,0.000000,162.895331
wtd_std_ElectronAffinity,21263.0,44.409356,20.429293,0.000000,169.075862
mean_FusionHeat,21263.0,14.296113,11.300188,0.222000,105.000000
wtd_mean_FusionHeat,21263.0,13.848001,14.279335,0.222000,105.000000
gmean_FusionHeat,21263.0,10.136977,10.065901,0.222000,105.000000
wtd_gmean_FusionHeat,21263.0,10.141161,13.134007,0.222000,105.000000
entropy_FusionHeat,21263.0,1.093343,0.375932,0.000000,2.034410
wtd_entropy_FusionHeat,21263.0,0.914065,0.370125,0.000000,1.747165
range_FusionHeat,21263.0,21.138994,20.370620,0.000000,104.778000
wtd_range_FusionHeat,21263.0,8.218528,11.414066,0.000000,102.675000
std_FusionHeat,21263.0,8.323333,8.671651,0.000000,51.635000
wtd_std_FusionHeat,21263.0,7.717576,7.288239,0.000000,51.680482
mean_ThermalConductivity,21263.0,89.706911,38.517485,0.026580,332.500000
wtd_mean_ThermalConductivity,21263.0,81.549080,45.519256,0.026580,406.960000
gmean_ThermalConductivity,21263.0,29.841727,34.059581,0.026580,317.883627
wtd_gmean_ThermalConductivity,21263.0,27.308061,40.191150,0.022952,376.032878
entropy_ThermalConductivity,21263.0,0.727630,0.325976,0.000000,1.633977
wtd_entropy_ThermalConductivity,21263.0,0.539991,0.318248,0.000000,1.612989
range_ThermalConductivity,21263.0,250.893443,158.703557,0.000000,429.974170
wtd_range_ThermalConductivity,21263.0,62.033066,43.123317,0.000000,401.440000
std_ThermalConductivity,21263.0,98.943993,60.143272,0.000000,214.986150
wtd_std_ThermalConductivity,21263.0,96.234051,63.710355,0.000000,213.300452
mean_Valence,21263.0,3.198228,1.044611,1.000000,7.000000
wtd_mean_Valence,21263.0,3.153127,1.191249,1.000000,7.000000
gmean_Valence,21263.0,3.056536,1.046257,1.000000,7.000000
wtd_gmean_Valence,21263.0,3.055885,1.174815,1.000000,7.000000
entropy_Valence,21263.0,1.295682,0.393155,0.000000,2.141963
wtd_entropy_Valence,21263.0,1.052841,0.380291,0.000000,1.949739
range_Valence,21263.0,2.041010,1.242345,0.000000,6.000000
wtd_range_Valence,21263.0,1.483007,0.978176,0.000000,6.992200
std_Valence,21263.0,0.839342,0.484676,0.000000,3.000000
wtd_std_Valence,21263.0,0.673987,0.455580,0.000000,3.000000
critical_temp,21263.0,34.421219,34.254362,0.000210,185.000000

In [7]:
# Categorical Feature Statistics
cat_stats

'No categorical/object features to summarize.'

In [8]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,0.86,-1.004,1173.361,2.487,log,193013.6,197014.7,exponential

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to superconductivity/019d7369-cca6-7baa-b958-4ec60c44e1c1

019d7369-cca6-7baa-b958-4ec60c44e1c1
2c3e3aac2e4d6b68232f1dfb0b1340ad4093208ad033226e386aec44bc300cc3