### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="santander_customer_satisfaction",
    dataset_year="2016",
    domain_str="business & marketing",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/santander-customer-satisfaction",
    download_description="""
We use the train.csv from the Kaggle competition.

kaggle competitions download -c santander-customer-satisfaction -f train.csv && unzip train.csv.zip &&  rm train.csv.zip
mkdir -p local-data-warehouse/santander_customer_satisfaction && mv train.csv local-data-warehouse/santander_customer_satisfaction/
""",
    # References
    academic_reference_bibtex=r"""@misc{Jimenez2016SantanderCustomerSatisfaction,
  author = {Soraya Jimenez and Will Cukierski},
  title  = {Santander Customer Satisfaction},
  year   = {2016},
  howpublished = {\url{https://kaggle.com/competitions/santander-customer-satisfaction}},
  note   = {Kaggle competition}
}
""",
    academic_reference_bibtex_key="Jimenez2016SantanderCustomerSatisfaction",
    license="Kaggle Competition Rules",
    data_tags=["IID", "Anonymized"],
    curation_comments="""
We start with the train.csv from Kaggle.

- The data has been anonymized, so feature meanings are unknown.
- We remove duplicated columns and zero-variance columns.
- We add a zero-count feature (number of zeros per row). #1 Kaggle experts also applied a lot of other features and feature selection but each experts used something different (https://www.kaggle.com/competitions/santander-customer-satisfaction/writeups/1-leustagos-3rd-place-solution).
- We drop duplicates as their origin is unclear and they could create data leaks when splitting the training data.
- We replace -999999 in var3 with with nan.
- We keep the data otherwise as it. Several columns might be categorical and contain encoded nan values but we are not able to determine this due to anonymization.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="TARGET",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="TARGET",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(dataset_mold.path / "train.csv")
print("Loaded data shape:", df.shape)

# remove duplicated columns
df = df.loc[:, ~df.T.duplicated()]
# remove zero-variance columns
df = df.loc[:, df.nunique(dropna=False) > 1]
# add zero-count feature
numeric_cols = df.drop(columns=["ID", "TARGET"])
df["zero_count"] = (numeric_cols == 0).sum(axis=1)
df = df.drop(columns=["ID"])
df[task_mold.target_column_name] = df[task_mold.target_column_name].astype("category")

# Drop duplicates w/o target col
df = df.drop_duplicates(subset=df.columns.difference([task_mold.target_column_name]))

# Replace -999999 with np.nan
df["var3"] = df["var3"].replace(-999999, np.nan)

df = df.reset_index(drop=True)

Loaded data shape: (76020, 371)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 71,080
Columns: 308
Use sampling: False (sample size: 71,080)

Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['var38', 'saldo_medio_var5_ult3', 'saldo_var30', 'saldo_var42', 'saldo_medio_var5_ult1', 'saldo_medio_var5_hace2', 'saldo_var5', 'imp_op_var39_comer_ult3', 'imp_op_var41_comer_ult3', 'imp_op_var39_ult1']
Rows remaining as candidates after top-10 filter: 5,180 (of 71,080)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,imp_op_var40_ult1,imp_op_var41_comer_ult1,imp_op_var41_comer_ult3,imp_op_var41_efect_ult1,imp_op_var41_efect_ult3,imp_op_var41_ult1,imp_op_var39_efect_ult1,imp_op_var39_efect_ult3,imp_op_var39_ult1,imp_sal_var16_ult1,ind_var1_0,ind_var1,ind_var5_0,ind_var5,ind_var6_0,ind_var6,ind_var8_0,ind_var8,ind_var12_0,ind_var12,ind_var13_0,ind_var13_corto_0,ind_var13_corto,ind_var13_largo_0,ind_var13_largo,ind_var13_medio_0,ind_var13,ind_var14_0,ind_var14,ind_var17_0,ind_var17,ind_var18_0,ind_var19,ind_var20_0,ind_var20,ind_var24_0,ind_var24,ind_var25_cte,ind_var26_0,ind_var26_cte,ind_var25_0,ind_var30_0,ind_var30,ind_var31_0,ind_var31,ind_var32_cte,ind_var32_0,ind_var33_0,ind_var33,ind_var34_0,ind_var37_cte,ind_var37_0,ind_var39_0,ind_var40_0,ind_var40,ind_var41_0,ind_var44_0,ind_var44,num_var1_0,num_var1,num_var4,num_var5_0,num_var5,num_var6_0,num_var6,num_var8_0,num_var8,num_var12_0,num_var12,num_var13_0,num_var13_corto_0,num_var13_corto,num_var13_largo_0,num_var13_largo,num_var13_medio_0,num_var13,num_var14_0,num_var14,num_var17_0,num_var17,num_var18_0,num_var20_0,num_var20,num_var24_0,num_var24,num_var26_0,num_var25_0,num_op_var40_hace2,num_op_var40_hace3,num_op_var40_ult1,num_op_var40_ult3,num_op_var41_hace2,num_op_var41_hace3,num_op_var41_ult1,num_op_var41_ult3,num_op_var39_hace2,num_op_var39_hace3,num_op_var39_ult1,num_op_var39_ult3,num_var30_0,num_var30,num_var31_0,num_var31,num_var32_0,num_var33_0,num_var33,num_var34_0,num_var35,num_var37_med_ult2,num_var37_0,num_var39_0,num_var40_0,num_var40,num_var41_0,num_var42_0,num_var42,num_var44_0,num_var44,saldo_var1,saldo_var5,saldo_var6,saldo_var8,saldo_var12,saldo_var13_corto,saldo_var13_largo,saldo_var13_medio,saldo_var13,saldo_var14,saldo_var17,saldo_var18,saldo_var20,saldo_var24,saldo_var26,saldo_var25,saldo_var30,saldo_var31,saldo_var32,saldo_var33,saldo_var34,saldo_var37,saldo_var40,saldo_var42,saldo_var44,var36,delta_imp_amort_var18_1y3,delta_imp_amort_var34_1y3,delta_imp_aport_var13_1y3,delta_imp_aport_var17_1y3,delta_imp_aport_var33_1y3,delta_imp_compra_var44_1y3,delta_imp_reemb_var13_1y3,delta_imp_reemb_var17_1y3,delta_imp_reemb_var33_1y3,delta_imp_trasp_var17_in_1y3,delta_imp_trasp_var17_out_1y3,delta_imp_trasp_var33_in_1y3,delta_imp_trasp_var33_out_1y3,delta_imp_venta_var44_1y3,delta_num_aport_var13_1y3,delta_num_aport_var17_1y3,delta_num_aport_var33_1y3,delta_num_compra_var44_1y3,delta_num_venta_var44_1y3,imp_amort_var18_ult1,imp_amort_var34_ult1,imp_aport_var13_hace3,imp_aport_var13_ult1,imp_aport_var17_hace3,imp_aport_var17_ult1,imp_aport_var33_hace3,imp_aport_var33_ult1,imp_var7_emit_ult1,imp_var7_recib_ult1,imp_compra_var44_hace3,imp_compra_var44_ult1,imp_reemb_var13_ult1,imp_reemb_var17_hace3,imp_reemb_var17_ult1,imp_reemb_var33_ult1,imp_var43_emit_ult1,imp_trans_var37_ult1,imp_trasp_var17_in_hace3,imp_trasp_var17_in_ult1,imp_trasp_var17_out_ult1,imp_trasp_var33_in_hace3,imp_trasp_var33_in_ult1,imp_trasp_var33_out_ult1,imp_venta_var44_hace3,imp_venta_var44_ult1,ind_var7_emit_ult1,ind_var7_recib_ult1,ind_var10_ult1,ind_var10cte_ult1,ind_var9_cte_ult1,ind_var9_ult1,ind_var43_emit_ult1,ind_var43_recib_ult1,var21,num_aport_var13_hace3,num_aport_var13_ult1,num_aport_var17_hace3,num_aport_var17_ult1,num_aport_var33_hace3,num_aport_var33_ult1,num_var7_emit_ult1,num_var7_recib_ult1,num_compra_var44_hace3,num_compra_var44_ult1,num_ent_var16_ult1,num_var22_hace2,num_var22_hace3,num_var22_ult1,num_var22_ult3,num_med_var22_ult3,num_med_var45_ult3,num_meses_var5_ult3,num_meses_var8_ult3,num_meses_var12_ult3,num_meses_var13_corto_ult3,num_meses_var13_largo_ult3,num_meses_var13_medio_ult3,num_meses_var17_ult3,num_meses_var29_ult3,num_meses_var33_ult3,num_meses_var39_vig_ult3,num_meses_var44_ult3,num_op_var39_comer_ult1,num_op_var39_comer_ult3,num_op_var40_comer_ult1,num_op_var40_comer_ult3,num_op_var40_efect_ult1,num_op_var40_efect_ult3,num_op_var41_comer_ult1,num_op_var41_comer_ult3,num_op_var41_efect_ult1,num_op_var41_efect_ult3,num_op_var39_efect_ult1,num_op_var39_efect_ult3,num_reemb_var13_ult1,num_reemb_var17_hace3,num_reemb_var17_ult1,num_reemb_var33_ult1,num_sal_var16_ult1,num_var43_emit_ult1,num_var43_recib_ult1,num_trasp_var11_ult1,num_trasp_var17_in_hace3,num_trasp_var17_in_ult1,num_trasp_var17_out_ult1,num_trasp_var33_in_hace3,num_trasp_var33_in_ult1,num_trasp_var33_out_ult1,num_venta_var44_hace3,num_venta_var44_ult1,num_var45_hace2,num_var45_hace3,num_var45_ult1,num_var45_ult3,saldo_medio_var5_hace2,saldo_medio_var5_hace3,saldo_medio_var5_ult1,saldo_medio_var5_ult3,saldo_medio_var8_hace2,saldo_medio_var8_hace3,saldo_medio_var8_ult1,saldo_medio_var8_ult3,saldo_medio_var12_hace2,saldo_medio_var12_hace3,saldo_medio_var12_ult1,saldo_medio_var12_ult3,saldo_medio_var13_corto_hace2,saldo_medio_var13_corto_hace3,saldo_medio_var13_corto_ult1,saldo_medio_var13_corto_ult3,saldo_medio_var13_largo_hace2,saldo_medio_var13_largo_hace3,saldo_medio_var13_largo_ult1,saldo_medio_var13_largo_ult3,saldo_medio_var13_medio_hace2,saldo_medio_var13_medio_ult3,saldo_medio_var17_hace2,saldo_medio_var17_hace3,saldo_medio_var17_ult1,saldo_medio_var17_ult3,saldo_medio_var29_hace2,saldo_medio_var29_hace3,saldo_medio_var29_ult1,saldo_medio_var29_ult3,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET,zero_count
0,2.0,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0,0.00,0.0,0.00,0.0,99,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0,292
1,2.0,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,0,0,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,3,0,0,0,0,0,0,0,3,3,3,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,3,0,0,0,0,0,0,3,0,0,3,0,0,3,3,0,0,0,0.0,0.00,0.0,0.0,0.0,300.0,0.0,0,300.0,0.0,0.0,0,0.0,0.0,0.0,0.0,300.00,0.0,0.0,0.0,0,0.00,0.0,0.00,0.0,3,0,0,-1.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,300.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,3,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,88.89,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,300.0,122.22,300.0,240.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0,266
2,2.0,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,0,0,3,0,0,3,0,0,3,3,3,0,0,0.0,3.00,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,3.00,0.0,0.0,0.0,0,0.00,0.0,3.00,0.0,99,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.00,0.18,3.00,2.07,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0,277
3,2.0,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,0.0,195.0,195.0,0.0,0.0,195.0,0.0,0.0,195.0,0.0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,1,0,0,1,0,0,0,0,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,9,0,0,9,9,3,3,0,0,0,0,0,0,9,6,6,3,0,0,3,3,3,0,0,0.0,70.62,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,70.62,0.0,0.0,0.0,0,34.95,0.0,70.62,0.0,2,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,3,0,15,2,0,0,0,0,0,0,0,0,1,0,9,9,0,0,0,0,9,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27,3,18,48,186.09,0.00,91.56,138.84,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0,248
4,2.0,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,3,0,0,0,0,0,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,3,0,0,0,0,0,0,3,0,0,3,0,0,3,6,3,0,0,0.0,0.00,0.0,0.0,135003.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,135003.0,0.0,0.0,135003.00,0.0,0.0,0.0,0,0.00,0.0,135003.00,0.0,1,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,135003.0,270003.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,3,0,6,9,3,0,3,0,1,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,6,3,0,0,0,0,0,0,0,0,0,0,0,0,3.00,0.30,40501.08,13501.47,0.0,0.0,0.0,0.0,0.0,0.0,85501.89,85501.89,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0,256

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,TARGET,category,0.0,0.00,2.0,"0, 1"
1,var3,float64,107.0,0.15,207.0,"2.0, 8.0, 9.0, 3.0, 1.0, 13.0, 7.0, 4.0, 12.0, 6.0"
2,imp_ent_var16_ult1,float64,0.0,0.00,596.0,"0.0, 300.0, 150.0, 600.0, 900.0, 3.0, 450.0, 60.0, 1500.0, 90.0"
3,imp_op_var39_comer_ult1,float64,0.0,0.00,7551.0,"0.0, 30.0, 60.0, 15.0, 90.0, 4.5, 45.0, 150.0, 120.0, 2.67"
4,imp_op_var39_comer_ult3,float64,0.0,0.00,9099.0,"0.0, 30.0, 60.0, 4.5, 15.0, 90.0, 45.0, 150.0, 2.67, 120.0"
5,imp_op_var40_comer_ult1,float64,0.0,0.00,293.0,"0.0, 396.0, 30.0, 180.0, 175.47, 168.0, 2189.04, 1222.62, 1430.94, 488.43"
6,imp_op_var40_comer_ult3,float64,0.0,0.00,346.0,"0.0, 30.0, 4.5, 3520.59, 109.5, 1430.31, 678.48, 499.2, 2189.04, 1222.62"
7,imp_op_var40_efect_ult1,float64,0.0,0.00,23.0,"0.0, 900.0, 1800.0, 60.0, 600.0, 450.0, 300.0, 120.0, 270.0, 210.0"
8,imp_op_var40_efect_ult3,float64,0.0,0.00,29.0,"0.0, 900.0, 1800.0, 120.0, 960.0, 330.0, 60.0, 600.0, 450.0, 300.0"
9,imp_op_var40_ult1,float64,0.0,0.00,224.0,"0.0, 600.0, 450.0, 900.0, 1800.0, 567.0, 270.0, 828.18, 199.53, 17.94"
10,imp_op_var41_comer_ult1,float64,0.0,0.00,7421.0,"0.0, 30.0, 60.0, 15.0, 90.0, 4.5, 45.0, 120.0, 150.0, 2.67"
11,imp_op_var41_comer_ult3,float64,0.0,0.00,8961.0,"0.0, 30.0, 60.0, 4.5, 15.0, 90.0, 45.0, 150.0, 120.0, 2.67"
12,imp_op_var41_efect_ult1,float64,0.0,0.00,331.0,"0.0, 60.0, 120.0, 180.0, 240.0, 300.0, 360.0, 420.0, 210.0, 600.0"
13,imp_op_var41_efect_ult3,float64,0.0,0.00,454.0,"0.0, 60.0, 120.0, 180.0, 240.0, 300.0, 150.0, 360.0, 420.0, 210.0"
14,imp_op_var41_ult1,float64,0.0,0.00,8032.0,"0.0, 60.0, 120.0, 30.0, 300.0, 180.0, 150.0, 240.0, 90.0, 210.0"
15,imp_op_var39_efect_ult1,float64,0.0,0.00,336.0,"0.0, 60.0, 120.0, 180.0, 240.0, 300.0, 420.0, 360.0, 210.0, 600.0"
16,imp_op_var39_efect_ult3,float64,0.0,0.00,462.0,"0.0, 60.0, 120.0, 180.0, 240.0, 300.0, 150.0, 360.0, 420.0, 210.0"
17,imp_op_var39_ult1,float64,0.0,0.00,8149.0,"0.0, 60.0, 120.0, 30.0, 300.0, 180.0, 150.0, 240.0, 90.0, 210.0"
18,imp_sal_var16_ult1,float64,0.0,0.00,66.0,"0.0, 3000.0, 1500.0, 600.0, 150.0, 750.0, 450.0, 210.0, 1620.0, 45.0"
19,saldo_var1,float64,0.0,0.00,285.0,"0.0, 900.0, 4035.0, 499.2, 1664.1, 69.0, 1436.94, 470.49, 85.74, 194.82"
20,saldo_var5,float64,0.0,0.00,11642.0,"0.0, 3.0, 90.0, 30.0, 15.0, 6.0, 150.0, 60.0, 300.0, 120.0"
21,saldo_var6,float64,0.0,0.00,3.0,"0.0, 11976.6, 19531.8"
22,saldo_var8,float64,0.0,0.00,1989.0,"0.0, 3.0, 30.0, 15.0, 150.0, 60.0, 1500.0, 750.0, 300.0, 900.0"
23,saldo_var12,float64,0.0,0.00,3059.0,"0.0, 3.0, 3000.0, 150392.37, 300.0, 60000.0, 30000.0, 600.0, 300385.68, 90000.0"
24,saldo_var13_corto,float64,0.0,0.00,730.0,"0.0, 90000.0, 30000.0, 60000.0, 150000.0, 300000.0, 45000.0, 120000.0, 180000.0, 450000.0"
25,saldo_var13_largo,float64,0.0,0.00,229.0,"0.0, 75000.0, 90000.0, 150000.0, 300000.0, 120000.0, 180000.0, 36000.0, 15000.0, 30000.0"
26,saldo_var13,float64,0.0,0.00,859.0,"0.0, 90000.0, 150000.0, 300000.0, 30000.0, 60000.0, 75000.0, 120000.0, 180000.0, 45000.0"
27,saldo_var14,float64,0.0,0.00,345.0,"0.0, 3000.0, 600.0, 3.0, 1200.0, 30.0, 1500.0, 300.0, 900.0, 450.0"
28,saldo_var17,float64,0.0,0.00,111.0,"0.0, 3065.94, 60851.22, 14569.98, 32224.11, 161036.37, 30618.81, 6285.54, 5917.11, 24236.22"
29,saldo_var20,float64,0.0,0.00,176.0,"0.0, 90.06, 150.0, 900.36, 300.0, 300.12, 450.15, 60.0, 3900.42, 750.3"
30,saldo_var24,float64,0.0,0.00,2614.0,"0.0, 150392.37, 30000.0, 300000.0, 300385.68, 90000.0, 300784.74, 60000.0, 75090.0, 150192.84"
31,saldo_var26,float64,0.0,0.00,1592.0,"0.0, 1278.0, 1065.0, 761.64, 2700.0, 3000.0, 1745.73, 1500.0, 300.0, 900.0"
32,saldo_var25,float64,0.0,0.00,1524.0,"0.0, 1278.0, 761.64, 1065.0, 2700.0, 3000.0, 1500.0, 1745.73, 894.6, 900.0"
33,saldo_var30,float64,0.0,0.00,16940.0,"0.0, 3.0, 90.0, 30.0, 15.0, 6.0, 150.0, 60.0, 300.0, 120.0"
34,saldo_var31,float64,0.0,0.00,278.0,"0.0, 15156.66, 65439.45, 121683.84, 52252.26, 13511.31, 21090.0, 3402.69, 16910.52, 7515.33"
35,saldo_var32,float64,0.0,0.00,75.0,"0.0, 1898.7, 436.5, 218.25, 579.9, 2737.65, 1323.81, 2935.92, 6076.98, 2300.25"
36,saldo_var33,float64,0.0,0.00,48.0,"0.0, 15156.66, 16019.79, 4696.11, 604.56, 2543.37, 64224.39, 8788.98, 604.14, 1969.8"
37,saldo_var37,float64,0.0,0.00,4041.0,"0.0, 159.21, 30.0, 160.77, 120.12, 25.38, 60.0, 45.0, 90.0, 15.0"
38,saldo_var40,float64,0.0,0.00,282.0,"0.0, 900.0, 4035.0, 1664.1, 69.0, 1436.94, 470.49, 85.74, 4588.38, 499.2"
39,saldo_var42,float64,0.0,0.00,15730.0,"0.0, 3.0, 90.0, 30.0, 15.0, 6.0, 150.0, 60.0, 300.0, 120.0"
40,saldo_var44,float64,0.0,0.00,129.0,"0.0, 65439.45, 25216.71, 2983.5, 12013.65, 48459.9, 1144.32, 14465.97, 45610.71, 8946.0"
41,delta_imp_aport_var13_1y3,float64,0.0,0.00,27.0,"0.0, -1.0, 9999999999.0, -0.5, 4.0, -0.3333, 2.3331, -0.2911, 0.1538, -0.8"
42,delta_imp_aport_var17_1y3,float64,0.0,0.00,7.0,"0.0, 9999999999.0, -1.0, 0.6853, 1.0001, 1.5, -0.75"
43,delta_imp_aport_var33_1y3,float64,0.0,0.00,9.0,"0.0, -1.0, -0.9405, -0.7, -0.916, -0.95, 9999999999.0, -0.6667, -0.5"
44,delta_imp_compra_var44_1y3,float64,0.0,0.00,17.0,"0.0, 9999999999.0, -1.0, -0.9642, -0.4757, -0.9504, 2.6505, -0.6307, 0.1518, -0.9685"
45,delta_imp_venta_var44_1y3,float64,0.0,0.00,5.0,"0.0, 9999999999.0, 5.4171, -0.5058, -1.0"
46,delta_num_aport_var13_1y3,float64,0.0,0.00,6.0,"0.0, -1.0, 9999999999.0, 1.0, -0.3333, -0.5"
47,delta_num_aport_var17_1y3,float64,0.0,0.00,6.0,"0.0, 9999999999.0, -1.0, 2.0, 1.0, -0.3333"
48,delta_num_aport_var33_1y3,float64,0.0,0.00,4.0,"0.0, -1.0, -0.5, 9999999999.0"
49,delta_num_compra_var44_1y3,float64,0.0,0.00,9.0,"0.0, 9999999999.0, -1.0, 1.0, 4.0, 0.5, -0.3333, 2.5, -0.6667"
50,delta_num_venta_var44_1y3,float64,0.0,0.00,5.0,"0.0, 9999999999.0, 8.0, -0.5, -1.0"
51,imp_amort_var18_ult1,float64,0.0,0.00,3.0,"0.0, 15691.8, 1883.22"
52,imp_amort_var34_ult1,float64,0.0,0.00,3.0,"0.0, 1096.02, 276.24"
53,imp_aport_var13_hace3,float64,0.0,0.00,425.0,"0.0, 90000.0, 150000.0, 30000.0, 300000.0, 60000.0, 75000.0, 120000.0, 45000.0, 180000.0"
54,imp_aport_var13_ult1,float64,0.0,0.00,182.0,"0.0, 90000.0, 300000.0, 150000.0, 15000.0, 75000.0, 180000.0, 36000.0, 60000.0, 30000.0"
55,imp_aport_var17_hace3,float64,0.0,0.00,20.0,"0.0, 30000.0, 3000.0, 120000.0, 37500.0, 1815.0, 96781.44, 6083691.87, 45741.48, 22793.16"
56,imp_aport_var17_ult1,float64,0.0,0.00,42.0,"0.0, 30000.0, 3000.0, 6129.9, 144302.34, 12000.0, 60778.41, 432457.32, 24000.0, 14356.26"
57,imp_var7_emit_ult1,float64,0.0,0.00,4.0,"0.0, 145384.92, 18000.0, 43500.0"
58,imp_var7_recib_ult1,float64,0.0,0.00,184.0,"0.0, 90000.0, 75000.0, 45000.0, 3000.0, 900.0, 210000.0, 600.0, 300000.0, 120000.0"
59,imp_compra_var44_hace3,float64,0.0,0.00,33.0,"0.0, 6679.05, 41801.64, 3019.5, 17113.8, 13568.4, 18203.52, 27.3, 19308.24, 10597.44"
60,imp_compra_var44_ult1,float64,0.0,0.00,85.0,"0.0, 15752.88, 3050.79, 799.26, 1495.02, 167.61, 14189.52, 23262.96, 560.34, 5854.8"
61,imp_reemb_var13_ult1,float64,0.0,0.00,33.0,"0.0, 90000.0, 18000.0, 180000.0, 6000.0, 66000.0, 15000.0, 51000.0, 111000.0, 270000.0"
62,imp_reemb_var17_hace3,float64,0.0,0.00,2.0,"0.0, 12027.15"
63,imp_reemb_var17_ult1,float64,0.0,0.00,20.0,"0.0, 37035.75, 6098.28, 56395.56, 26571.81, 4149.39, 69620.1, 69622.29, 3059.52, 36000.0"
64,imp_var43_emit_ult1,float64,0.0,0.00,2342.0,"0.0, 3000.0, 300.0, 1500.0, 900.0, 90.0, 600.0, 150.0, 30.0, 1200.0"
65,imp_trans_var37_ult1,float64,0.0,0.00,3831.0,"0.0, 300.0, 600.0, 1500.0, 150.0, 900.0, 3000.0, 1200.0, 450.0, 1800.0"
66,imp_trasp_var17_in_hace3,float64,0.0,0.00,3.0,"0.0, 96781.44, 45741.48"
67,imp_trasp_var17_in_ult1,float64,0.0,0.00,5.0,"0.0, 14356.26, 2999.82, 39927.15, 133730.58"
68,imp_trasp_var17_out_ult1,float64,0.0,0.00,5.0,"0.0, 69622.29, 3059.52, 69599.01, 3192.27"
69,imp_trasp_var33_in_hace3,float64,0.0,0.00,7.0,"0.0, 49581.27, 25501.8, 25920.03, 33744.48, 44251.08, 33079.83"
70,imp_trasp_var33_in_ult1,float64,0.0,0.00,6.0,"0.0, 2545.65, 5400.0, 13207.32, 2596.53, 174.09"
71,imp_venta_var44_hace3,float64,0.0,0.00,4.0,"0.0, 23.16, 209834.4, 78040.59"
72,imp_venta_var44_ult1,float64,0.0,0.00,45.0,"0.0, 18944.64, 7267.05, 388.08, 735.33, 21948.36, 3127.02, 17122.5, 125480.49, 450.99"
73,saldo_medio_var5_hace2,float64,0.0,0.00,14486.0,"0.0, 3.0, 90.0, 15.0, 30.0, 6.0, 150.0, 60.0, 300.0, 120.0"
74,saldo_medio_var5_hace3,float64,0.0,0.00,7787.0,"0.0, 0.09, 0.18, 0.99, 2.61, 0.27, 1.05, 0.51, 2.55, 2.4"
75,saldo_medio_var5_ult1,float64,0.0,0.00,14778.0,"0.0, 3.0, 90.0, 30.0, 15.0, 6.0, 150.0, 60.0, 300.0, 120.0"
76,saldo_medio_var5_ult3,float64,0.0,0.00,17330.0,"0.0, 2.88, 2.34, 2.85, 2.07, 2.04, 2.79, 2.28, 2.1, 2.61"
77,saldo_medio_var8_hace2,float64,0.0,0.00,1325.0,"0.0, 3.0, 30.0, 15.0, 60.0, 150.0, 6.0, 155.79, 51.54, 35.37"
78,saldo_medio_var8_hace3,float64,0.0,0.00,439.0,"0.0, 0.99, 0.3, 0.18, 1.05, 0.51, 0.54, 1.59, 14.01, 32.13"
79,saldo_medio_var8_ult1,float64,0.0,0.00,2116.0,"0.0, 3.0, 15.0, 60.0, 30.0, 150.0, 300.0, 900.0, 750.0, 431.91"
80,saldo_medio_var8_ult3,float64,0.0,0.00,2173.0,"0.0, 3.0, 13.2, 837.78, 47.16, 304.23, 2.34, 2.7, 99.15, 6497.64"
81,saldo_medio_var12_hace2,float64,0.0,0.00,2834.0,"0.0, 180000.0, 150000.0, 45000.0, 30000.0, 36000.0, 60.0, 15.0, 30.0, 90.0"
82,saldo_medio_var12_hace3,float64,0.0,0.00,1152.0,"0.0, 11612.91, 7741.92, 1935.48, 580.65, 10714.29, 0.09, 5000.01, 38709.69, 8709.69"
83,saldo_medio_var12_ult1,float64,0.0,0.00,3405.0,"0.0, 3.0, 90.03, 30.0, 300.0, 60.03, 75.0, 30.03, 3000.81, 15000.0"
84,saldo_medio_var12_ult3,float64,0.0,0.00,3447.0,"0.0, 75.03, 25177.77, 8709.69, 20658.45, 17600.01, 200.01, 1968.84, 3900.87, 51319.05"
85,saldo_medio_var13_corto_hace2,float64,0.0,0.00,1628.0,"0.0, 30000.0, 60000.0, 90000.0, 150000.0, 45000.0, 300000.0, 450000.0, 120000.0, 180000.0"
86,saldo_medio_var13_corto_hace3,float64,0.0,0.00,968.0,"0.0, 5000.01, 6000.0, 4000.02, 11612.91, 30000.0, 967.74, 9677.43, 3999.99, 39999.99"
87,saldo_medio_var13_corto_ult1,float64,0.0,0.00,943.0,"0.0, 90000.0, 30000.0, 60000.0, 150000.0, 300000.0, 45000.0, 120000.0, 75000.0, 450000.0"
88,saldo_medio_var13_corto_ult3,float64,0.0,0.00,2576.0,"0.0, 20322.57, 240.75, 41333.34, 40645.17, 233.34, 261290.34, 81333.33, 42000.0, 85500.0"
89,saldo_medio_var13_largo_hace2,float64,0.0,0.00,295.0,"0.0, 75000.0, 90000.0, 150000.0, 300000.0, 120000.0, 180000.0, 36000.0, 15000.0, 30000.0"
90,saldo_medio_var13_largo_hace3,float64,0.0,0.00,264.0,"0.0, 6000.0, 9677.43, 4838.7, 2419.35, 3000.0, 20322.57, 5000.01, 29032.32, 19354.83"
91,saldo_medio_var13_largo_ult1,float64,0.0,0.00,233.0,"0.0, 75000.0, 90000.0, 150000.0, 300000.0, 120000.0, 180000.0, 60000.0, 36000.0, 450000.0"
92,saldo_medio_var13_largo_ult3,float64,0.0,0.00,511.0,"0.0, 203225.82, 50806.44, 27600.0, 50862.06, 19600.02, 75000.0, 65833.32, 124137.93, 81964.32"
93,saldo_medio_var13_medio_hace2,float64,0.0,0.00,3.0,"0.0, 7741.95, 5586.21"
94,saldo_medio_var13_medio_ult3,float64,0.0,0.00,3.0,"0.0, 18870.99, 7293.12"
95,saldo_medio_var17_hace2,float64,0.0,0.00,88.0,"0.0, 67321.32, 37020.03, 33081.39, 2198.67, 30117.39, 5996.58, 514.8, 1079.97, 4080.48"
96,saldo_medio_var17_hace3,float64,0.0,0.00,18.0,"0.0, 119.04, 9024.39, 2368558.95, 50905.89, 2934.84, 7396.35, 4773.66, 44402.97, 76698.39"
97,saldo_medio_var17_ult1,float64,0.0,0.00,119.0,"0.0, 2126.07, 51422.91, 8087.91, 21970.92, 98048.19, 30614.88, 2263.44, 5906.01, 6400.2"
98,saldo_medio_var17_ult3,float64,0.0,0.00,119.0,"0.0, 1320.45, 42252.15, 8087.91, 12985.35, 50123.43, 30366.15, 2263.44, 5951.31, 6400.2"
99,saldo_medio_var29_hace2,float64,0.0,0.00,5.0,"0.0, 4838.7, 868.98, 59.97, 10430.01"
100,saldo_medio_var29_hace3,float64,0.0,0.00,2.0,"0.0, 145.2"
101,saldo_medio_var29_ult1,float64,0.0,0.00,4.0,"0.0, 3365.46, 2142.87, 13793.67"
102,saldo_medio_var29_ult3,float64,0.0,0.00,4.0,"0.0, 3365.46, 3490.8, 7331.34"
103,saldo_medio_var33_hace2,float64,0.0,0.00,43.0,"0.0, 15265.95, 13775.97, 4729.98, 22217.13, 1160.55, 385.41, 1735.23, 11060.04, 3255.81"
104,saldo_medio_var33_hace3,float64,0.0,0.00,24.0,"0.0, 2000.16, 6643.29, 4060.71, 6028.08, 54.69, 555.75, 20385.72, 1506.24, 3765.06"
105,saldo_medio_var33_ult1,float64,0.0,0.00,48.0,"0.0, 15050.52, 15458.22, 4663.23, 604.68, 2290.41, 63317.19, 8791.29, 595.23, 2002.53"
106,saldo_medio_var33_ult3,float64,0.0,0.00,48.0,"0.0, 10772.22, 11959.17, 4484.64, 604.68, 2290.41, 42767.16, 4975.92, 490.32, 1868.88"
107,saldo_medio_var44_hace2,float64,0.0,0.00,99.0,"0.0, 27781.5, 5946.63, 12646.68, 24579.15, 558.66, 44990.49, 3684.84, 934.86, 697.26"
108,saldo_medio_var44_hace3,float64,0.0,0.00,33.0,"0.0, 866.58, 18928.59, 1169.91, 4789.74, 1395.09, 6946.98, 0.57, 1874.7, 5499.24"
109,saldo_medio_var44_ult1,float64,0.0,0.00,141.0,"0.0, 61887.72, 21881.16, 398.01, 18291.72, 47045.55, 1176.84, 5115.57, 21069.45, 8975.76"
110,saldo_medio_var44_ult3,float64,0.0,0.00,141.0,"0.0, 44834.61, 13913.91, 398.01, 10601.67, 36988.2, 867.75, 5115.57, 19548.15, 6330.3"
111,var38,float64,0.0,0.00,57736.0,"117310.979, 451931.22, 463625.16, 104563.8, 288997.44, 236690.34, 104644.41, 67088.31, 125722.44, 329603.97"
112,var15,int64,0.0,0.00,100.0,"23, 24, 25, 26, 27, 28, 31, 29, 30, 32"
113,ind_var1_0,int64,0.0,0.00,2.0,"0, 1"
114,ind_var1,int64,0.0,0.00,2.0,"0, 1"
115,ind_var5_0,int64,0.0,0.00,2.0,"1, 0"
116,ind_var5,int64,0.0,0.00,2.0,"1, 0"
117,ind_var6_0,int64,0.0,0.00,2.0,"0, 1"
118,ind_var6,int64,0.0,0.00,2.0,"0, 1"
119,ind_var8_0,int64,0.0,0.00,2.0,"0, 1"
120,ind_var8,int64,0.0,0.00,2.0,"0, 1"
121,ind_var12_0,int64,0.0,0.00,2.0,"0, 1"
122,ind_var12,int64,0.0,0.00,2.0,"0, 1"
123,ind_var13_0,int64,0.0,0.00,2.0,"0, 1"
124,ind_var13_corto_0,int64,0.0,0.00,2.0,"0, 1"
125,ind_var13_corto,int64,0.0,0.00,2.0,"0, 1"
126,ind_var13_largo_0,int64,0.0,0.00,2.0,"0, 1"
127,ind_var13_largo,int64,0.0,0.00,2.0,"0, 1"
128,ind_var13_medio_0,int64,0.0,0.00,2.0,"0, 1"
129,ind_var13,int64,0.0,0.00,2.0,"0, 1"
130,ind_var14_0,int64,0.0,0.00,2.0,"0, 1"
131,ind_var14,int64,0.0,0.00,2.0,"0, 1"
132,ind_var17_0,int64,0.0,0.00,2.0,"0, 1"
133,ind_var17,int64,0.0,0.00,2.0,"0, 1"
134,ind_var18_0,int64,0.0,0.00,2.0,"0, 1"
135,ind_var19,int64,0.0,0.00,2.0,"0, 1"
136,ind_var20_0,int64,0.0,0.00,2.0,"0, 1"
137,ind_var20,int64,0.0,0.00,2.0,"0, 1"
138,ind_var24_0,int64,0.0,0.00,2.0,"0, 1"
139,ind_var24,int64,0.0,0.00,2.0,"0, 1"
140,ind_var25_cte,int64,0.0,0.00,2.0,"0, 1"
141,ind_var26_0,int64,0.0,0.00,2.0,"0, 1"
142,ind_var26_cte,int64,0.0,0.00,2.0,"0, 1"
143,ind_var25_0,int64,0.0,0.00,2.0,"0, 1"
144,ind_var30_0,int64,0.0,0.00,2.0,"1, 0"
145,ind_var30,int64,0.0,0.00,2.0,"1, 0"
146,ind_var31_0,int64,0.0,0.00,2.0,"0, 1"
147,ind_var31,int64,0.0,0.00,2.0,"0, 1"
148,ind_var32_cte,int64,0.0,0.00,2.0,"0, 1"
149,ind_var32_0,int64,0.0,0.00,2.0,"0, 1"
150,ind_var33_0,int64,0.0,0.00,2.0,"0, 1"
151,ind_var33,int64,0.0,0.00,2.0,"0, 1"
152,ind_var34_0,int64,0.0,0.00,2.0,"0, 1"
153,ind_var37_cte,int64,0.0,0.00,2.0,"0, 1"
154,ind_var37_0,int64,0.0,0.00,2.0,"0, 1"
155,ind_var39_0,int64,0.0,0.00,2.0,"1, 0"
156,ind_var40_0,int64,0.0,0.00,2.0,"0, 1"
157,ind_var40,int64,0.0,0.00,2.0,"0, 1"
158,ind_var41_0,int64,0.0,0.00,2.0,"1, 0"
159,ind_var44_0,int64,0.0,0.00,2.0,"0, 1"
160,ind_var44,int64,0.0,0.00,2.0,"0, 1"
161,num_var1_0,int64,0.0,0.00,3.0,"0, 3, 6"
162,num_var1,int64,0.0,0.00,3.0,"0, 3, 6"
163,num_var4,int64,0.0,0.00,8.0,"1, 0, 2, 3, 4, 5, 6, 7"
164,num_var5_0,int64,0.0,0.00,5.0,"3, 0, 6, 9, 15"
165,num_var5,int64,0.0,0.00,5.0,"3, 0, 6, 9, 15"
166,num_var6_0,int64,0.0,0.00,2.0,"0, 3"
167,num_var6,int64,0.0,0.00,2.0,"0, 3"
168,num_var8_0,int64,0.0,0.00,3.0,"0, 3, 6"
169,num_var8,int64,0.0,0.00,2.0,"0, 3"
170,num_var12_0,int64,0.0,0.00,6.0,"0, 3, 6, 9, 15, 111"
171,num_var12,int64,0.0,0.00,4.0,"0, 3, 6, 15"
172,num_var13_0,int64,0.0,0.00,7.0,"0, 3, 6, 9, 12, 15, 18"
173,num_var13_corto_0,int64,0.0,0.00,3.0,"0, 3, 6"
174,num_var13_corto,int64,0.0,0.00,3.0,"0, 3, 6"
175,num_var13_largo_0,int64,0.0,0.00,7.0,"0, 3, 6, 9, 12, 15, 18"
176,num_var13_largo,int64,0.0,0.00,7.0,"0, 3, 6, 9, 12, 15, 18"
177,num_var13_medio_0,int64,0.0,0.00,2.0,"0, 3"
178,num_var13,int64,0.0,0.00,7.0,"0, 3, 6, 9, 12, 15, 18"
179,num_var14_0,int64,0.0,0.00,5.0,"0, 3, 6, 12, 111"
180,num_var14,int64,0.0,0.00,4.0,"0, 3, 6, 12"
181,num_var17_0,int64,0.0,0.00,11.0,"0, 3, 6, 9, 12, 15, 18, 24, 36, 21"
182,num_var17,int64,0.0,0.00,9.0,"0, 3, 6, 9, 12, 15, 18, 27, 21"
183,num_var18_0,int64,0.0,0.00,2.0,"0, 3"
184,num_var20_0,int64,0.0,0.00,2.0,"0, 3"
185,num_var20,int64,0.0,0.00,2.0,"0, 3"
186,num_var24_0,int64,0.0,0.00,4.0,"0, 3, 6, 9"
187,num_var24,int64,0.0,0.00,3.0,"0, 3, 6"
188,num_var26_0,int64,0.0,0.00,9.0,"0, 3, 6, 9, 12, 15, 33, 21, 27"
189,num_var25_0,int64,0.0,0.00,9.0,"0, 3, 6, 9, 12, 15, 33, 21, 27"
190,num_op_var40_hace2,int64,0.0,0.00,19.0,"0, 3, 6, 9, 12, 15, 18, 24, 21, 51"
191,num_op_var40_hace3,int64,0.0,0.00,5.0,"0, 3, 6, 9, 48"
192,num_op_var40_ult1,int64,0.0,0.00,30.0,"0, 3, 6, 9, 12, 15, 24, 18, 21, 33"
193,num_op_var40_ult3,int64,0.0,0.00,35.0,"0, 3, 6, 12, 24, 15, 9, 21, 18, 33"
194,num_op_var41_hace2,int64,0.0,0.00,51.0,"0, 3, 6, 9, 12, 15, 18, 21, 24, 27"
195,num_op_var41_hace3,int64,0.0,0.00,22.0,"0, 3, 6, 9, 12, 15, 21, 18, 30, 24"
196,num_op_var41_ult1,int64,0.0,0.00,68.0,"0, 3, 6, 9, 12, 15, 18, 21, 24, 27"
197,num_op_var41_ult3,int64,0.0,0.00,96.0,"0, 3, 6, 9, 12, 15, 18, 21, 24, 27"
198,num_op_var39_hace2,int64,0.0,0.00,50.0,"0, 3, 6, 9, 12, 15, 18, 21, 24, 27"
199,num_op_var39_hace3,int64,0.0,0.00,22.0,"0, 3, 6, 9, 12, 15, 21, 18, 30, 24"
200,num_op_var39_ult1,int64,0.0,0.00,71.0,"0, 3, 6, 9, 12, 15, 18, 21, 24, 27"
201,num_op_var39_ult3,int64,0.0,0.00,99.0,"0, 3, 6, 9, 12, 15, 18, 21, 24, 27"
202,num_var30_0,int64,0.0,0.00,11.0,"3, 6, 9, 0, 12, 15, 18, 33, 24, 114"
203,num_var30,int64,0.0,0.00,9.0,"3, 0, 6, 9, 12, 15, 18, 33, 21"
204,num_var31_0,int64,0.0,0.00,11.0,"0, 3, 6, 9, 12, 15, 18, 24, 36, 21"
205,num_var31,int64,0.0,0.00,9.0,"0, 3, 6, 9, 12, 15, 18, 27, 21"
206,num_var32_0,int64,0.0,0.00,5.0,"0, 3, 6, 12, 9"
207,num_var33_0,int64,0.0,0.00,4.0,"0, 3, 6, 12"
208,num_var33,int64,0.0,0.00,3.0,"0, 3, 6"
209,num_var34_0,int64,0.0,0.00,2.0,"0, 3"
210,num_var35,int64,0.0,0.00,13.0,"3, 0, 6, 9, 12, 15, 18, 21, 24, 27"
211,num_var37_med_ult2,int64,0.0,0.00,21.0,"0, 3, 6, 9, 12, 15, 18, 21, 27, 24"
212,num_var37_0,int64,0.0,0.00,22.0,"0, 3, 6, 9, 12, 15, 18, 21, 30, 27"
213,num_var39_0,int64,0.0,0.00,9.0,"3, 0, 6, 9, 12, 15, 18, 33, 21"
214,num_var40_0,int64,0.0,0.00,3.0,"0, 3, 6"
215,num_var40,int64,0.0,0.00,2.0,"0, 3"
216,num_var41_0,int64,0.0,0.00,9.0,"3, 0, 6, 9, 12, 15, 18, 33, 21"
217,num_var42_0,int64,0.0,0.00,8.0,"3, 6, 0, 9, 12, 15, 18, 114"
218,num_var42,int64,0.0,0.00,7.0,"3, 0, 6, 9, 12, 15, 18"
219,num_var44_0,int64,0.0,0.00,3.0,"0, 3, 6"
220,num_var44,int64,0.0,0.00,2.0,"0, 3"
221,saldo_var13_medio,int64,0.0,0.00,3.0,"0, 30000, 9000"
222,saldo_var18,int64,0.0,0.00,3.0,"0, 3000000, 300000"
223,saldo_var34,int64,0.0,0.00,3.0,"0, 36000, 15000"
224,var36,int64,0.0,0.00,5.0,"99, 3, 1, 2, 0"
225,delta_imp_amort_var18_1y3,int64,0.0,0.00,2.0,"0, 9999999999"
226,delta_imp_amort_var34_1y3,int64,0.0,0.00,2.0,"0, 9999999999"
227,delta_imp_reemb_var13_1y3,int64,0.0,0.00,2.0,"0, 9999999999"
228,delta_imp_reemb_var17_1y3,int64,0.0,0.00,3.0,"0, 9999999999, -1"
229,delta_imp_reemb_var33_1y3,int64,0.0,0.00,2.0,"0, 9999999999"
230,delta_imp_trasp_var17_in_1y3,int64,0.0,0.00,3.0,"0, 9999999999, -1"
231,delta_imp_trasp_var17_out_1y3,int64,0.0,0.00,2.0,"0, 9999999999"
232,delta_imp_trasp_var33_in_1y3,int64,0.0,0.00,3.0,"0, -1, 9999999999"
233,delta_imp_trasp_var33_out_1y3,int64,0.0,0.00,2.0,"0, 9999999999"
234,imp_aport_var33_hace3,int64,0.0,0.00,16.0,"0, 15000, 1500, 9000, 18000, 7500, 4500, 12600, 7530, 150"
235,imp_aport_var33_ult1,int64,0.0,0.00,6.0,"0, 450, 300, 750, 1260, 150"
236,imp_reemb_var33_ult1,int64,0.0,0.00,2.0,"0, 1200"
237,imp_trasp_var33_out_ult1,int64,0.0,0.00,2.0,"0, 3000"
238,ind_var7_emit_ult1,int64,0.0,0.00,2.0,"0, 1"
239,ind_var7_recib_ult1,int64,0.0,0.00,2.0,"0, 1"
240,ind_var10_ult1,int64,0.0,0.00,2.0,"0, 1"
241,ind_var10cte_ult1,int64,0.0,0.00,2.0,"0, 1"
242,ind_var9_cte_ult1,int64,0.0,0.00,2.0,"0, 1"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
var3,70973.0,2.767489e+00,9.776127e+00,0.00,2.380000e+02
var15,71080.0,3.355101e+01,1.310395e+01,5.00,1.050000e+02
imp_ent_var16_ult1,71080.0,9.219967e+01,1.669762e+03,0.00,2.100000e+05
imp_op_var39_comer_ult1,71080.0,7.739224e+01,3.503540e+02,0.00,1.288803e+04
imp_op_var39_comer_ult3,71080.0,1.278368e+02,5.639895e+02,0.00,2.102481e+04
imp_op_var40_comer_ult1,71080.0,3.806486e+00,9.633366e+01,0.00,8.237820e+03
imp_op_var40_comer_ult3,71080.0,6.922545e+00,1.589799e+02,0.00,1.107357e+04
imp_op_var40_efect_ult1,71080.0,4.416458e-01,3.165032e+01,0.00,6.600000e+03
imp_op_var40_efect_ult3,71080.0,6.067829e-01,3.776073e+01,0.00,6.600000e+03
imp_op_var40_ult1,71080.0,3.380383e+00,9.851941e+01,0.00,8.237820e+03
imp_op_var41_comer_ult1,71080.0,7.358575e+01,3.299926e+02,0.00,1.288803e+04
imp_op_var41_comer_ult3,71080.0,1.209143e+02,5.287557e+02,0.00,1.656681e+04
imp_op_var41_efect_ult1,71080.0,7.294534e+01,5.497566e+02,0.00,4.599000e+04
imp_op_var41_efect_ult3,71080.0,1.210941e+02,9.820624e+02,0.00,1.311000e+05
imp_op_var41_ult1,71080.0,1.467810e+02,7.205801e+02,0.00,4.759809e+04
imp_op_var39_efect_ult1,71080.0,7.338699e+01,5.534529e+02,0.00,4.599000e+04
imp_op_var39_efect_ult3,71080.0,1.217009e+02,9.856709e+02,0.00,1.311000e+05
imp_op_var39_ult1,71080.0,1.501614e+02,7.361253e+02,0.00,4.759809e+04
imp_sal_var16_ult1,71080.0,5.858369e+00,4.812896e+02,0.00,1.050000e+05
ind_var1_0,71080.0,1.225380e-02,1.100173e-01,0.00,1.000000e+00
ind_var1,71080.0,4.023635e-03,6.330483e-02,0.00,1.000000e+00
ind_var5_0,71080.0,9.554305e-01,2.063581e-01,0.00,1.000000e+00
ind_var5,71080.0,6.799803e-01,4.664870e-01,0.00,1.000000e+00
ind_var6_0,71080.0,1.125492e-04,1.060840e-02,0.00,1.000000e+00
ind_var6,71080.0,2.813731e-05,5.304424e-03,0.00,1.000000e+00
ind_var8_0,71080.0,3.484806e-02,1.833961e-01,0.00,1.000000e+00
ind_var8,71080.0,3.058526e-02,1.721924e-01,0.00,1.000000e+00
ind_var12_0,71080.0,7.215813e-02,2.587514e-01,0.00,1.000000e+00
ind_var12,71080.0,4.857907e-02,2.149879e-01,0.00,1.000000e+00
ind_var13_0,71080.0,5.588070e-02,2.296928e-01,0.00,1.000000e+00
ind_var13_corto_0,71080.0,4.592009e-02,2.093133e-01,0.00,1.000000e+00
ind_var13_corto,71080.0,4.435847e-02,2.058917e-01,0.00,1.000000e+00
ind_var13_largo_0,71080.0,1.087507e-02,1.037157e-01,0.00,1.000000e+00
ind_var13_largo,71080.0,1.069218e-02,1.028494e-01,0.00,1.000000e+00
ind_var13_medio_0,71080.0,2.813731e-05,5.304424e-03,0.00,1.000000e+00
ind_var13,71080.0,5.438942e-02,2.267861e-01,0.00,1.000000e+00
ind_var14_0,71080.0,2.529544e-02,1.570221e-01,0.00,1.000000e+00
ind_var14,71080.0,5.669668e-03,7.508397e-02,0.00,1.000000e+00
ind_var17_0,71080.0,1.927406e-03,4.386021e-02,0.00,1.000000e+00
ind_var17,71080.0,1.547552e-03,3.930876e-02,0.00,1.000000e+00
ind_var18_0,71080.0,2.813731e-05,5.304424e-03,0.00,1.000000e+00
ind_var19,71080.0,4.487901e-03,6.684177e-02,0.00,1.000000e+00
ind_var20_0,71080.0,3.826674e-03,6.174208e-02,0.00,1.000000e+00
ind_var20,71080.0,2.841868e-03,5.323375e-02,0.00,1.000000e+00
ind_var24_0,71080.0,4.531514e-02,2.079959e-01,0.00,1.000000e+00
ind_var24,71080.0,4.051773e-02,1.971715e-01,0.00,1.000000e+00
ind_var25_cte,71080.0,2.826393e-02,1.657271e-01,0.00,1.000000e+00
ind_var26_0,71080.0,2.635059e-02,1.601768e-01,0.00,1.000000e+00
ind_var26_cte,71080.0,2.947383e-02,1.691317e-01,0.00,1.000000e+00
ind_var25_0,71080.0,2.528137e-02,1.569795e-01,0.00,1.000000e+00
ind_var30_0,71080.0,9.951745e-01,6.929885e-02,0.00,1.000000e+00
ind_var30,71080.0,7.538126e-01,4.307920e-01,0.00,1.000000e+00
ind_var31_0,71080.0,4.572313e-03,6.746459e-02,0.00,1.000000e+00
ind_var31,71080.0,3.925155e-03,6.252842e-02,0.00,1.000000e+00
ind_var32_cte,71080.0,1.294316e-03,3.595357e-02,0.00,1.000000e+00
ind_var32_0,71080.0,1.153630e-03,3.394577e-02,0.00,1.000000e+00
ind_var33_0,71080.0,8.019133e-04,2.830692e-02,0.00,1.000000e+00
ind_var33,71080.0,6.752954e-04,2.597785e-02,0.00,1.000000e+00
ind_var34_0,71080.0,2.813731e-05,5.304424e-03,0.00,1.000000e+00
ind_var37_cte,71080.0,7.732133e-02,2.671025e-01,0.00,1.000000e+00
ind_var37_0,71080.0,6.979460e-02,2.548023e-01,0.00,1.000000e+00
ind_var39_0,71080.0,8.852701e-01,3.186979e-01,0.00,1.000000e+00
ind_var40_0,71080.0,1.221159e-02,1.098300e-01,0.00,1.000000e+00
ind_var40,71080.0,3.981429e-03,6.297328e-02,0.00,1.000000e+00
ind_var41_0,71080.0,8.836944e-01,3.205932e-01,0.00,1.000000e+00
ind_var44_0,71080.0,2.011818e-03,4.480846e-02,0.00,1.000000e+00
ind_var44,71080.0,1.814856e-03,4.256276e-02,0.00,1.000000e+00
num_var1_0,71080.0,3.684581e-02,3.311915e-01,0.00,6.000000e+00
num_var1,71080.0,1.211311e-02,1.909093e-01,0.00,6.000000e+00
num_var4,71080.0,1.124508e+00,9.146078e-01,0.00,7.000000e+00
num_var5_0,71080.0,2.887437e+00,6.758021e-01,0.00,1.500000e+01
num_var5,71080.0,2.048382e+00,1.415002e+00,0.00,1.500000e+01
num_var6_0,71080.0,3.376477e-04,3.182520e-02,0.00,3.000000e+00
num_var6,71080.0,8.441193e-05,1.591327e-02,0.00,3.000000e+00
num_var8_0,71080.0,1.045864e-01,5.505255e-01,0.00,6.000000e+00
num_var8,71080.0,9.175577e-02,5.165771e-01,0.00,3.000000e+00
num_var12_0,71080.0,2.257597e-01,9.186148e-01,0.00,1.110000e+02
num_var12,71080.0,1.474676e-01,6.576963e-01,0.00,1.500000e+01
num_var13_0,71080.0,1.793754e-01,7.699472e-01,0.00,1.800000e+01
num_var13_corto_0,71080.0,1.393641e-01,6.389825e-01,0.00,6.000000e+00
num_var13_corto,71080.0,1.331598e-01,6.182716e-01,0.00,6.000000e+00
num_var13_largo_0,71080.0,3.992684e-02,4.185294e-01,0.00,1.800000e+01
num_var13_largo,71080.0,3.768993e-02,3.942857e-01,0.00,1.800000e+01
num_var13_medio_0,71080.0,8.441193e-05,1.591327e-02,0.00,3.000000e+00
num_var13,71080.0,1.709342e-01,7.360950e-01,0.00,1.800000e+01
num_var14_0,71080.0,7.774339e-02,6.313734e-01,0.00,1.110000e+02
num_var14,71080.0,1.726224e-02,2.318806e-01,0.00,1.200000e+01
num_var17_0,71080.0,1.270400e-02,3.748507e-01,0.00,3.600000e+01
num_var17,71080.0,9.496342e-03,2.986247e-01,0.00,2.700000e+01
num_var18_0,71080.0,8.441193e-05,1.591327e-02,0.00,3.000000e+00
num_var20_0,71080.0,1.148002e-02,1.852262e-01,0.00,3.000000e+00
num_var20,71080.0,8.525605e-03,1.597012e-01,0.00,3.000000e+00
num_var24_0,71080.0,1.365363e-01,6.283079e-01,0.00,9.000000e+00
num_var24,71080.0,1.216798e-01,5.924509e-01,0.00,6.000000e+00
num_var26_0,71080.0,9.559651e-02,6.496162e-01,0.00,3.300000e+01
num_var25_0,71080.0,9.108047e-02,6.325973e-01,0.00,3.300000e+01
num_op_var40_hace2,71080.0,2.165166e-02,9.282697e-01,0.00,1.170000e+02
num_op_var40_hace3,71080.0,1.097355e-03,1.869380e-01,0.00,4.800000e+01
num_op_var40_ult1,71080.0,6.098762e-02,1.889744e+00,0.00,2.340000e+02
num_op_var40_ult3,71080.0,8.373663e-02,2.645535e+00,0.00,3.510000e+02
num_op_var41_hace2,71080.0,1.712423e+00,7.559577e+00,0.00,2.490000e+02
num_op_var41_hace3,71080.0,1.004502e-01,1.256477e+00,0.00,8.100000e+01
num_op_var41_ult1,71080.0,3.057527e+00,1.123125e+01,0.00,4.680000e+02
num_op_var41_ult3,71080.0,4.870400e+00,1.742476e+01,0.00,4.680000e+02
num_op_var39_hace2,71080.0,1.734074e+00,7.629217e+00,0.00,2.490000e+02
num_op_var39_hace3,71080.0,1.015476e-01,1.270220e+00,0.00,8.100000e+01
num_op_var39_ult1,71080.0,3.118514e+00,1.146506e+01,0.00,4.680000e+02
num_op_var39_ult3,71080.0,4.954136e+00,1.771779e+01,0.00,4.680000e+02
num_var30_0,71080.0,3.397496e+00,1.378431e+00,0.00,1.140000e+02
num_var30,71080.0,2.458624e+00,1.626226e+00,0.00,3.300000e+01
num_var31_0,71080.0,2.152504e-02,4.204809e-01,0.00,3.600000e+01
num_var31,71080.0,1.717783e-02,3.429108e-01,0.00,2.700000e+01
num_var32_0,71080.0,4.516038e-03,1.444709e-01,0.00,1.200000e+01
num_var33_0,71080.0,2.743388e-03,1.049209e-01,0.00,1.200000e+01
num_var33,71080.0,2.236916e-03,8.928626e-02,0.00,6.000000e+00
num_var34_0,71080.0,8.441193e-05,1.591327e-02,0.00,3.000000e+00
num_var35,71080.0,3.438815e+00,2.888907e+00,0.00,3.600000e+01
num_var37_med_ult2,71080.0,2.818514e-01,1.705144e+00,0.00,1.050000e+02
num_var37_0,71080.0,4.478897e-01,2.314899e+00,0.00,1.140000e+02
num_var39_0,71080.0,2.744063e+00,1.134704e+00,0.00,3.300000e+01
num_var40_0,71080.0,3.667698e-02,3.300614e-01,0.00,6.000000e+00
num_var40,71080.0,1.194429e-02,1.889198e-01,0.00,3.000000e+00
num_var41_0,71080.0,2.716587e+00,1.098759e+00,0.00,3.300000e+01
num_var42_0,71080.0,3.218120e+00,9.745149e-01,0.00,1.140000e+02
num_var42,71080.0,2.282288e+00,1.477162e+00,0.00,1.800000e+01
num_var44_0,71080.0,6.077659e-03,1.358291e-01,0.00,6.000000e+00
num_var44,71080.0,5.444569e-03,1.276883e-01,0.00,3.000000e+00
saldo_var1,71080.0,5.181628e+01,1.131116e+04,-0.90,3.000000e+06
saldo_var5,71080.0,1.099408e+03,1.018495e+04,-2895.72,6.193292e+05
saldo_var6,71080.0,4.432808e-01,8.593584e+01,0.00,1.953180e+04
saldo_var8,71080.0,1.510419e+02,2.601322e+03,-4942.26,2.400450e+05
saldo_var12,71080.0,6.439618e+03,4.976251e+04,0.00,3.008077e+06
saldo_var13_corto,71080.0,5.340815e+03,3.370613e+04,0.00,4.500000e+05
saldo_var13_largo,71080.0,1.597492e+03,2.069637e+04,0.00,1.500000e+06
saldo_var13_medio,71080.0,5.486775e-01,1.174787e+02,0.00,3.000000e+04
saldo_var13,71080.0,6.938855e+03,3.968992e+04,0.00,1.500000e+06
saldo_var14,71080.0,7.389833e+01,2.936578e+03,0.00,4.500000e+05
saldo_var17,71080.0,1.961525e+02,2.347359e+04,0.00,6.119500e+06
saldo_var18,71080.0,4.642656e+01,1.130857e+04,0.00,3.000000e+06
saldo_var20,71080.0,2.880824e+01,2.559945e+03,0.00,4.558582e+05
saldo_var24,71080.0,6.336911e+03,4.962252e+04,0.00,3.008077e+06
saldo_var26,71080.0,8.136924e+01,7.647709e+02,0.00,6.975672e+04
saldo_var25,71080.0,7.779076e+01,7.514560e+02,0.00,6.975672e+04
saldo_var30,71080.0,1.462937e+04,6.506036e+04,-4942.26,3.458077e+06
saldo_var31,71080.0,3.126049e+02,2.411290e+04,0.00,6.119500e+06
saldo_var32,71080.0,3.578481e+00,1.310052e+02,0.00,1.221078e+04
saldo_var33,71080.0,1.340332e+01,8.250918e+02,0.00,1.420788e+05
saldo_var34,71080.0,7.175014e-01,1.462813e+02,0.00,3.600000e+04
saldo_var37,71080.0,3.947221e+01,4.881251e+02,0.00,6.000000e+04
saldo_var40,71080.0,4.672216e+00,1.178566e+02,-0.90,8.192610e+03
saldo_var42,71080.0,7.690511e+03,5.078663e+04,-4942.26,3.008077e+06
saldo_var44,71080.0,1.030492e+02,5.396659e+03,0.00,7.400066e+05
var36,71080.0,3.832641e+01,4.687366e+01,0.00,9.900000e+01
delta_imp_amort_var18_1y3,71080.0,2.813731e+05,5.304424e+07,0.00,1.000000e+10
delta_imp_amort_var34_1y3,71080.0,2.813731e+05,5.304424e+07,0.00,1.000000e+10
delta_imp_aport_var13_1y3,71080.0,5.205402e+07,7.196095e+08,-1.00,1.000000e+10
delta_imp_aport_var17_1y3,71080.0,5.486775e+06,2.341760e+08,-1.00,1.000000e+10
delta_imp_aport_var33_1y3,71080.0,1.406866e+05,3.750821e+07,-1.00,1.000000e+10
delta_imp_compra_var44_1y3,71080.0,9.848059e+06,3.136638e+08,-1.00,1.000000e+10
delta_imp_reemb_var13_1y3,71080.0,5.346089e+06,2.311559e+08,0.00,1.000000e+10
delta_imp_reemb_var17_1y3,71080.0,2.813731e+06,1.677194e+08,-1.00,1.000000e+10
delta_imp_reemb_var33_1y3,71080.0,1.406866e+05,3.750821e+07,0.00,1.000000e+10
delta_imp_trasp_var17_in_1y3,71080.0,5.627462e+05,7.501483e+07,-1.00,1.000000e+10
delta_imp_trasp_var17_out_1y3,71080.0,5.627462e+05,7.501483e+07,0.00,1.000000e+10
delta_imp_trasp_var33_in_1y3,71080.0,7.034328e+05,8.386854e+07,-1.00,1.000000e+10
delta_imp_trasp_var33_out_1y3,71080.0,1.406866e+05,3.750821e+07,0.00,1.000000e+10
delta_imp_venta_var44_1y3,71080.0,5.908835e+06,2.430108e+08,-1.00,1.000000e+10
delta_num_aport_var13_1y3,71080.0,5.205402e+07,7.196095e+08,-1.00,1.000000e+10
delta_num_aport_var17_1y3,71080.0,5.486775e+06,2.341760e+08,-1.00,1.000000e+10
delta_num_aport_var33_1y3,71080.0,1.406866e+05,3.750821e+07,-1.00,1.000000e+10
delta_num_compra_var44_1y3,71080.0,9.848059e+06,3.136638e+08,-1.00,1.000000e+10
delta_num_venta_var44_1y3,71080.0,5.908835e+06,2.430108e+08,-1.00,1.000000e+10
imp_amort_var18_ult1,71080.0,2.472569e-01,5.927938e+01,0.00,1.569180e+04
imp_amort_var34_ult1,71080.0,1.930585e-02,4.239522e+00,0.00,1.096020e+03
imp_aport_var13_hace3,71080.0,3.020211e+03,2.618874e+04,0.00,8.400000e+05
imp_aport_var13_ult1,71080.0,6.626456e+02,1.163624e+04,0.00,4.500000e+05
imp_aport_var17_hace3,71080.0,1.056545e+02,2.287649e+04,0.00,6.083692e+06
imp_aport_var17_ult1,71080.0,3.326712e+01,2.541027e+03,0.00,4.324573e+05
imp_aport_var33_hace3,71080.0,3.193303e+00,2.346127e+02,0.00,3.600000e+04
imp_aport_var33_ult1,71080.0,5.149128e-02,6.228452e+00,0.00,1.260000e+03
imp_var7_emit_ult1,71080.0,2.910593e+00,5.731857e+02,0.00,1.453849e+05
imp_var7_recib_ult1,71080.0,1.365731e+02,6.586510e+03,0.00,1.039260e+06
imp_compra_var44_hace3,71080.0,1.493511e+01,1.190848e+03,0.00,2.100014e+05
imp_compra_var44_ult1,71080.0,1.248988e+02,1.408577e+04,0.00,3.410059e+06
imp_reemb_var13_ult1,71080.0,4.938973e+01,2.957417e+03,0.00,4.500000e+05
imp_reemb_var17_hace3,71080.0,1.692058e-01,4.511168e+01,0.00,1.202715e+04
imp_reemb_var17_ult1,71080.0,1.344296e+01,1.130477e+03,0.00,1.821330e+05
imp_reemb_var33_ult1,71080.0,1.688239e-02,4.500985e+00,0.00,1.200000e+03
imp_var43_emit_ult1,71080.0,9.134814e+02,1.474112e+04,0.00,1.155003e+06
imp_trans_var37_ult1,71080.0,2.067292e+03,2.621673e+04,0.00,2.310003e+06
imp_trasp_var17_in_hace3,71080.0,2.005106e+00,4.015096e+02,0.00,9.678144e+04
imp_trasp_var17_in_ult1,71080.0,2.687307e+00,5.263580e+02,0.00,1.337306e+05
imp_trasp_var17_out_ult1,71080.0,2.046611e+00,3.696162e+02,0.00,6.962229e+04
imp_trasp_var33_in_hace3,71080.0,2.983659e+00,3.348770e+02,0.00,4.958127e+04
imp_trasp_var33_in_ult1,71080.0,3.365727e-01,5.523278e+01,0.00,1.320732e+04
imp_trasp_var33_out_ult1,71080.0,4.220597e-02,1.125246e+01,0.00,3.000000e+03
imp_venta_var44_hace3,71080.0,4.050340e+00,8.397177e+02,0.00,2.098344e+05
imp_venta_var44_ult1,71080.0,8.709341e+01,1.166787e+04,0.00,2.754476e+06
ind_var7_emit_ult1,71080.0,4.220597e-05,6.496520e-03,0.00,1.000000e+00
ind_var7_recib_ult1,71080.0,2.884074e-03,5.362646e-02,0.00,1.000000e+00
ind_var10_ult1,71080.0,8.649409e-02,2.810942e-01,0.00,1.000000e+00
ind_var10cte_ult1,71080.0,9.856500e-02,2.980792e-01,0.00,1.000000e+00
ind_var9_cte_ult1,71080.0,1.036016e-01,3.047451e-01,0.00,1.000000e+00
ind_var9_ult1,71080.0,9.188239e-02,2.888619e-01,0.00,1.000000e+00
ind_var43_emit_ult1,71080.0,7.121553e-02,2.571863e-01,0.00,1.000000e+00
ind_var43_recib_ult1,71080.0,1.382808e-01,3.451969e-01,0.00,1.000000e+00
var21,71080.0,3.481148e+01,4.071942e+02,0.00,3.000000e+04
num_aport_var13_hace3,71080.0,8.116207e-02,5.710013e-01,0.00,2.400000e+01
num_aport_var13_ult1,71080.0,1.920371e-02,2.985822e-01,0.00,3.000000e+01
num_aport_var17_hace3,71080.0,1.646033e-03,1.085031e-01,0.00,1.200000e+01
num_aport_var17_ult1,71080.0,3.629713e-03,1.800041e-01,0.00,2.100000e+01
num_aport_var33_hace3,71080.0,1.139561e-03,7.204241e-02,0.00,1.200000e+01
num_aport_var33_ult1,71080.0,3.376477e-04,3.558206e-02,0.00,6.000000e+00
num_var7_emit_ult1,71080.0,1.266179e-04,1.948956e-02,0.00,3.000000e+00
num_var7_recib_ult1,71080.0,1.101576e-02,2.365823e-01,0.00,2.400000e+01
num_compra_var44_hace3,71080.0,1.983680e-03,1.024963e-01,0.00,9.000000e+00
num_compra_var44_ult1,71080.0,8.061339e-03,3.262241e-01,0.00,3.900000e+01
num_ent_var16_ult1,71080.0,2.010270e-01,1.027736e+00,0.00,6.000000e+01
num_var22_hace2,71080.0,1.388112e+00,3.550442e+00,0.00,1.230000e+02
num_var22_hace3,71080.0,1.265419e+00,3.359094e+00,0.00,1.080000e+02
num_var22_ult1,71080.0,5.992825e-01,2.170796e+00,0.00,9.600000e+01
num_var22_ult3,71080.0,3.252814e+00,6.364993e+00,0.00,2.340000e+02
num_med_var22_ult3,71080.0,6.800225e-01,1.890019e+00,0.00,7.800000e+01
num_med_var45_ult3,71080.0,4.303995e+00,1.125050e+01,0.00,2.670000e+02
num_meses_var5_ult3,71080.0,2.029643e+00,1.271822e+00,0.00,3.000000e+00
num_meses_var8_ult3,71080.0,5.732977e-02,3.460424e-01,0.00,3.000000e+00
num_meses_var12_ult3,71080.0,1.090321e-01,5.032988e-01,0.00,3.000000e+00
num_meses_var13_corto_ult3,71080.0,1.057963e-01,5.019470e-01,0.00,3.000000e+00
num_meses_var13_largo_ult3,71080.0,1.861283e-02,2.203244e-01,0.00,3.000000e+00
num_meses_var13_medio_ult3,71080.0,5.627462e-05,1.060885e-02,0.00,2.000000e+00
num_meses_var17_ult3,71080.0,3.165447e-03,8.029684e-02,0.00,3.000000e+00
num_meses_var29_ult3,71080.0,1.125492e-04,1.403393e-02,0.00,2.000000e+00
num_meses_var33_ult3,71080.0,1.617895e-03,6.462068e-02,0.00,3.000000e+00
num_meses_var39_vig_ult3,71080.0,1.598002e+00,7.141727e-01,0.00,3.000000e+00
num_meses_var44_ult3,71080.0,3.826674e-03,9.118178e-02,0.00,3.000000e+00
num_op_var39_comer_ult1,71080.0,2.347327e+00,9.424416e+00,0.00,4.380000e+02
num_op_var39_comer_ult3,71080.0,3.857752e+00,1.539811e+01,0.00,6.000000e+02
num_op_var40_comer_ult1,71080.0,8.019133e-02,2.160699e+00,0.00,2.100000e+02
num_op_var40_comer_ult3,71080.0,1.548959e-01,4.434479e+00,0.00,5.820000e+02
num_op_var40_efect_ult1,71080.0,2.658976e-03,1.521983e-01,0.00,2.400000e+01
num_op_var40_efect_ult3,71080.0,3.925155e-03,2.089698e-01,0.00,2.400000e+01
num_op_var41_comer_ult1,71080.0,2.267136e+00,9.081771e+00,0.00,4.380000e+02
num_op_var41_comer_ult3,71080.0,3.702856e+00,1.459329e+01,0.00,4.380000e+02
num_op_var41_efect_ult1,71080.0,7.694147e-01,3.314910e+00,0.00,9.000000e+01
num_op_var41_efect_ult3,71080.0,1.296398e+00,5.326466e+00,0.00,1.560000e+02
num_op_var39_efect_ult1,71080.0,7.720737e-01,3.330736e+00,0.00,9.000000e+01
num_op_var39_efect_ult3,71080.0,1.300324e+00,5.347848e+00,0.00,1.560000e+02
num_reemb_var13_ult1,71080.0,1.603827e-03,6.934678e-02,0.00,3.000000e+00
num_reemb_var17_hace3,71080.0,4.220597e-05,1.125246e-02,0.00,3.000000e+00
num_reemb_var17_ult1,71080.0,1.266179e-03,1.018882e-01,0.00,2.100000e+01
num_reemb_var33_ult1,71080.0,4.220597e-05,1.125246e-02,0.00,3.000000e+00
num_sal_var16_ult1,71080.0,5.275746e-03,1.602372e-01,0.00,1.500000e+01
num_var43_emit_ult1,71080.0,4.201182e-01,2.289057e+00,0.00,1.800000e+02
num_var43_recib_ult1,71080.0,8.715954e-01,3.672489e+00,0.00,2.640000e+02
num_trasp_var11_ult1,71080.0,1.290658e-01,1.211750e+00,0.00,9.300000e+01
num_trasp_var17_in_hace3,71080.0,1.266179e-04,2.516113e-02,0.00,6.000000e+00
num_trasp_var17_in_ult1,71080.0,1.688239e-04,2.250445e-02,0.00,3.000000e+00
num_trasp_var17_out_ult1,71080.0,1.688239e-04,2.250445e-02,0.00,3.000000e+00
num_trasp_var33_in_hace3,71080.0,2.532358e-04,2.756182e-02,0.00,3.000000e+00
num_trasp_var33_in_ult1,71080.0,2.532358e-04,3.182598e-02,0.00,6.000000e+00
num_trasp_var33_out_ult1,71080.0,4.220597e-05,1.125246e-02,0.00,3.000000e+00
num_venta_var44_hace3,71080.0,1.688239e-04,2.756247e-02,0.00,6.000000e+00
num_venta_var44_ult1,71080.0,4.727068e-03,2.732824e-01,0.00,3.900000e+01
num_var45_hace2,71080.0,5.764322e+00,1.492006e+01,0.00,3.420000e+02
num_var45_hace3,71080.0,4.156190e+00,1.072206e+01,0.00,3.390000e+02
num_var45_ult1,71080.0,4.665616e+00,1.485136e+01,0.00,5.100000e+02
num_var45_ult3,71080.0,1.458613e+01,3.424521e+01,0.00,8.010000e+02
saldo_medio_var5_hace2,71080.0,1.688348e+03,1.255621e+04,-128.37,8.121373e+05
saldo_medio_var5_hace3,71080.0,9.531265e+02,1.022358e+04,-8.04,1.542339e+06
saldo_medio_var5_ult1,71080.0,1.151587e+03,9.939136e+03,-922.38,6.014286e+05
saldo_medio_var5_ult3,71080.0,1.121319e+03,8.464997e+03,-476.07,5.443656e+05
saldo_medio_var8_hace2,71080.0,7.302054e+01,1.792981e+03,-287.67,2.313520e+05
saldo_medio_var8_hace3,71080.0,1.016590e+01,5.371286e+02,0.00,7.758621e+04
saldo_medio_var8_ult1,71080.0,1.332820e+02,2.280342e+03,-3401.34,2.280318e+05
saldo_medio_var8_ult3,71080.0,1.176733e+02,2.001203e+03,-1844.52,1.775820e+05
saldo_medio_var12_hace2,71080.0,4.274384e+03,3.904843e+04,0.00,3.000538e+06
saldo_medio_var12_hace3,71080.0,6.561583e+02,9.608797e+03,0.00,6.683353e+05
saldo_medio_var12_ult1,71080.0,6.098868e+03,4.775573e+04,0.00,3.004186e+06
saldo_medio_var12_ult3,71080.0,4.706541e+03,3.670070e+04,0.00,2.272859e+06
saldo_medio_var13_corto_hace2,71080.0,3.892357e+03,2.724171e+04,0.00,4.500000e+05
saldo_medio_var13_corto_hace3,71080.0,5.948385e+02,7.426500e+03,0.00,3.048387e+05
saldo_medio_var13_corto_ult1,71080.0,5.189490e+03,3.294952e+04,0.00,4.500000e+05
saldo_medio_var13_corto_ult3,71080.0,4.125966e+03,2.642503e+04,0.00,4.500000e+05
saldo_medio_var13_largo_hace2,71080.0,8.248271e+02,1.352749e+04,0.00,8.400000e+05
saldo_medio_var13_largo_hace3,71080.0,1.734411e+02,4.859210e+03,0.00,5.340000e+05

In [7]:
# Categorical Feature Statistics
cat_stats

            value  count    pct
column rank
TARGET 1        0  68368  96.18
       2        1   2712   3.82

In [8]:
# Target Distribution
target_df

        count    pct
TARGET
0       68368  96.18
1        2712   3.82

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...

Saving curated container to santander_customer_satisfaction/019d5dc6-86ea-7525-81f2-e50b404706ea

019d5dc6-86ea-7525-81f2-e50b404706ea
db64be8fb612418697885b5fad51f3a2256f6a19e8d80aecf88fa6fb6066d9c2