### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="pca_genexp_prediction",
    dataset_year="2002",
    domain_str="medical & healthcare",
    # Data Source
    dataset_source="OpenML",
    original_dataset_source_download_link="https://api.openml.org/data/download/22112160/dataset",
    download_description="""
We download the dataset from OpenML to a predefined folder:

mkdir -p local-data-warehouse/pca_genexp_prediction/ && wget -P local-data-warehouse/pca_genexp_prediction/ https://api.openml.org/data/download/22112160/dataset
""",
    # References
    academic_reference_bibtex=r"""@article{singh2002gene,
  title={Gene expression correlates of clinical prostate cancer behavior},
  author={Singh, Dinesh and Febbo, Phillip G and Ross, Kenneth and Jackson, Donald G and Manola, Judith and Ladd, Christine and Tamayo, Pablo and Renshaw, Andrew A and D'Amico, Anthony V and Richie, Jerome P and others},
  journal={Cancer cell},
  volume={1},
  number={2},
  pages={203--209},
  year={2002},
  publisher={Elsevier}
}
@inproceedings{torrijos2023miniande,
  title={MiniAnDE: a reduced AnDE ensemble to deal with microarray data},
  author={Torrijos, Pablo and G{\'a}mez, Jos{\'e} A and Puerta, Jos{\'e} M},
  booktitle={International Conference on Engineering Applications of Neural Networks},
  pages={131--143},
  year={2023},
  organization={Springer}
}
""",
    academic_reference_bibtex_key="singh2002gene,torrijos2023miniande",
    license="Public Domain", # From OpenML, original license unknown
    data_tags=["IID"],
    curation_comments="""N/A""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="HasTumor",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="HasTumor",
)

## Preprocessing

In [2]:
import pandas as pd
import arff

with open(dataset_mold.path / "dataset") as f:
    data = arff.load(f)
df = pd.DataFrame(data["data"], columns = [x[0] for x in data["attributes"]])

target_feature = "HasTumor"
df.rename(columns={"class": target_feature}, inplace=True)
df[target_feature] = df[target_feature].map({"1": "Yes", "2": "No"}).astype("category")
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 102
Columns: 12601
Use sampling: False (sample size: 102)

Get row duplicates (staged, merged)...

Using top-10 columns for initial filtering: ['1804_at', '35278_at', '31573_at', '32335_r_at', '32466_at', '36931_at', '34593_g_at', '1173_g_at', '37383_f_at', '35905_s_at']
Rows remaining as candidates after top-10 filter: 0 (of 102)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...

Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

   AFFX-MurIL2_at  AFFX-MurIL10_at  AFFX-MurIL4_at  AFFX-MurFAS_at  \
0           -13.0             45.0             0.0            26.0
1            10.0             42.0            -9.0            58.0
2            -6.0              0.0             2.0            12.0
3             0.0              3.0             0.0             3.0
4             1.0              1.0             0.0             6.0

   AFFX-BioB-5_at  AFFX-BioB-M_at  AFFX-BioB-3_at  AFFX-BioC-5_at  \
0           -26.0           -15.0             0.0            -1.0
1             1.0           -21.0            22.0            45.0
2            -4.0           -11.0             0.0             2.0
3            -4.0            -4.0             0.0             4.0
4             0.0            -5.0             0.0             5.0

   AFFX-BioC-3_at  AFFX-BioDn-5_at  AFFX-BioDn-3_at  AFFX-CreX-5_at  \
0           -51.0            -52.0            -43.0           -19.0
1           -60.0            -62.0           -143.0           -25.0
2           -11.0            -17.0             11.0            -7.0
3            -6.0            -11.0              4.0            -3.0
4            -6.0             -3.0              8.0            -2.0

   AFFX-CreX-3_at  AFFX-BioB-5_st  AFFX-BioB-M_st  AFFX-BioB-3_st  \
0            11.0            42.0            -8.0          -117.0
1           -49.0           112.0           -45.0           -70.0
2             0.0            12.0            -6.0           -43.0
3            -2.0             8.0             2.0           -16.0
4             0.0            13.0            -5.0           -23.0

   AFFX-BioC-5_st  AFFX-BioC-3_st  AFFX-BioDn-5_st  AFFX-BioDn-3_st  \
0           -38.0            -5.0             34.0             19.0
1           -51.0           -19.0            167.0             65.0
2           -14.0            -3.0             30.0             14.0
3             0.0             0.0              5.0             10.0
4            -1.0             0.0             10.0              2.0

   AFFX-CreX-5_st  AFFX-CreX-3_st  AFFX-hum_alu_at  AFFX-DapX-5_at  \
0            -3.0           -80.0           4963.0            -2.0
1           -15.0           -17.0           2775.0            -4.0
2             0.0           -18.0           2251.0             4.0
3            -1.0            -5.0           1519.0            -1.0
4            -1.0            -4.0           1684.0             2.0

   AFFX-DapX-M_at  AFFX-DapX-3_at  AFFX-LysX-5_at  AFFX-LysX-M_at  \
0            25.0           -18.0             0.0           -39.0
1            44.0           -10.0             8.0           -31.0
2            10.0             1.0             0.0            -4.0
3             4.0            -1.0             0.0             0.0
4             5.0             0.0             0.0            -2.0

   AFFX-LysX-3_at  AFFX-PheX-5_at  AFFX-PheX-M_at  AFFX-PheX-3_at  \
0            39.0            -4.0           -10.0            -3.0
1            17.0            -2.0           -32.0            35.0
2            12.0             0.0            -4.0             0.0
3             6.0            -1.0             0.0             0.0
4             3.0            -1.0            -2.0             0.0

   AFFX-ThrX-5_at  AFFX-ThrX-M_at  AFFX-ThrX-3_at  AFFX-TrpnX-5_at  \
0             5.0            16.0           -43.0             13.0
1            -3.0            -7.0           -61.0             12.0
2            -4.0            -2.0           -15.0              0.0
3             0.0             2.0            -6.0              0.0
4            -2.0            -1.0             0.0              0.0

   AFFX-TrpnX-M_at  AFFX-TrpnX-3_at  AFFX-HUMISGF3A/M97935_5_at  \
0            -31.0             -9.0                        14.0
1            -39.0            -10.0                         9.0
2            -11.0             -2.0                         2.0
3             -7.0              0.0                         1.0
4              0.0              0.0                         1.0

   AFFX-HUMISGF3A/M97935_MA_at  AFFX-HUMISGF3A/M97935_MB_at  \
0                         14.0                          1.0
1                          8.0                          1.0
2                         13.0                          4.0
3                         -6.0                         13.0
4                         -2.0                         10.0

   AFFX-HUMISGF3A/M97935_3_at  AFFX-HUMRGE/M10098_5_at  \
0                        30.0                     27.0
1                        15.0                      8.0
2                        46.0                      0.0
3                        47.0                      0.0
4                        54.0                      0.0

   AFFX-HUMRGE/M10098_M_at  AFFX-HUMRGE/M10098_3_at  \
0                      0.0                    -17.0
1                    -71.0                   -117.0
2                    -19.0                      1.0
3                     -8.0                     -6.0
4                     -4.0                     -6.0

   AFFX-HUMGAPDH/M33197_5_at  AFFX-HUMGAPDH/M33197_M_at  \
0                       62.0                     -131.0
1                       76.0                     -155.0
2                       26.0                      -33.0
3                      244.0                      371.0
4                       55.0                      205.0

   AFFX-HUMGAPDH/M33197_3_at  AFFX-HSAC07/X00351_5_at  \
0                      140.0                     99.0
1                      135.0                    167.0
2                      341.0                     34.0
3                      561.0                    255.0
4                      416.0                     51.0

   AFFX-HSAC07/X00351_M_at  AFFX-HSAC07/X00351_3_at  AFFX-HUMTFRR/M11507_5_at  \
0                    -22.0                    720.0                      24.0
1                    141.0                    569.0                      46.0
2                     29.0                   1057.0                       6.0
3                    627.0                    699.0                       4.0
4                    224.0                    828.0                       2.0

   AFFX-HUMTFRR/M11507_M_at  AFFX-HUMTFRR/M11507_3_at  AFFX-M27830_5_at  \
0                     -22.0                      75.0              11.0
1                      -9.0                       2.0              -7.0
2                      -6.0                      17.0               9.0
3                      -3.0                       1.0               5.0
4                      -1.0                       3.0              -1.0

   AFFX-M27830_M_at  AFFX-M27830_3_at  AFFX-HSAC07/X00351_3_st  \
0             193.0              99.0                    169.0
1             260.0             282.0                    138.0
2              83.0              34.0                     57.0
3              26.0              17.0                      7.0
4              20.0              16.0                     27.0

   AFFX-HUMGAPDH/M33197_5_st  AFFX-HUMGAPDH/M33197_M_st  \
0                      -27.0                        7.0
1                      -50.0                       19.0
2                      -16.0                        0.0
3                       -7.0                       -2.0
4                       -3.0                        3.0

   AFFX-HUMGAPDH/M33197_3_st  AFFX-HSAC07/X00351_5_st  \
0                       40.0                      5.0
1                       55.0                     -1.0
2                       10.0                    -12.0
3                        0.0                     -3.0
4                        1.0                     -2.0

   AFFX-HSAC07/X00351_M_st  AFFX-YEL002c/WBP1_at  AFFX-YEL018w/_at  \
0                     21.0                  -1.0             -28.0
1                     51.0                  -5.0             -29.0
2                     -3.0                  -1.0              -7.0
3                     -7.0                   0.0              -1.0
4                      5.0                   0.0              -4.0

   AFFX-YEL024w/RIP1_at  AFFX-YEL021w/URA3_at  31307_at  31308_at  31309_r_at  \
0                  14.0                  47.0     -33.0     -20.0         4.0
1                  49.0                  80.0     -41.0     -19.0        17.0
2                   7.0                  27.0      -7.0       0.0         0.0
3                   1.0                  10.0      -1.0      -1.0         0.0
4                   4.0                  13.0      -1.0       0.0        -1.0

   31310_at  31311_at  31312_at  31313_at  31314_at  31315_at  31316_at  \
0     -11.0      37.0      -1.0     -68.0       3.0       9.0       0.0
1      34.0      65.0     -76.0     -77.0      46.0       9.0       3.0
2       1.0      17.0       2.0     -13.0      -6.0       3.0      -2.0
3      -1.0       6.0       1.0       0.0      -7.0       4.0       0.0
4      -1.0       9.0       1.0      -4.0       0.0       9.0       1.0

   31317_r_at  31318_at  31319_at  31320_at  31321_at  31322_at  31323_r_at  \
0       196.0       1.0      27.0     -72.0      26.0       7.0        26.0
1       348.0     -14.0      10.0    -118.0      54.0       0.0         8.0
2       123.0       1.0       3.0     -30.0      15.0       7.0         2.0
3        38.0       0.0      -1.0       5.0       7.0       0.0       -16.0
4        39.0       0.0       4.0     -14.0       4.0       2.0         5.0

   31324_at  31325_at  31326_at  31327_at  31328_at  31329_at  31330_at  \
0     150.0     -31.0     -58.0     -10.0       7.0      19.0       6.0
1     173.0     -78.0    -234.0     -18.0      -8.0      26.0       7.0
2      54.0     -12.0     -16.0      -1.0       0.0       0.0     151.0
3       6.0      -7.0      -8.0      -1.0       8.0       1.0     501.0
4      17.0      -4.0      -6.0       0.0       5.0      -2.0     805.0

   31331_at  31332_at  31333_at  31334_at  31335_at  31336_at  31337_at  \
0      -9.0       3.0      20.0      -9.0     -18.0      -4.0      87.0
1       0.0       3.0       3.0       0.0     -37.0      -3.0     -68.0
2       1.0       0.0       0.0      -1.0      -7.0      -2.0      27.0
3       0.0       0.0       0.0       0.0      -2.0       4.0     -14.0
4       0.0       0.0       0.0       0.0      -3.0      -2.0      15.0

   31338_at  31339_at  31340_at  31341_at  31342_at  31343_at  31344_at  \
0      10.0     -14.0      -6.0     -96.0      33.0       6.0     -11.0
1      16.0     -45.0      14.0      30.0      25.0       6.0      33.0
2       2.0      -1.0       1.0      26.0      18.0      -1.0      -2.0
3       1.0      -4.0       0.0      -2.0       4.0      -1.0       0.0
4      -3.0      -1.0       5.0       4.0       3.0       1.0      -4.0

   31345_at  31346_at  31347_at  31348_at  31349_at  31350_at  31351_at  \
0       8.0     -42.0     -47.0     -68.0     -44.0      34.0      -8.0
1      19.0     -46.0     -64.0     -42.0     -40.0      87.0      -7.0
2       7.0     -14.0     -47.0     -13.0     -15.0      12.0      -8.0
3      -1.0       0.0     -20.0      -7.0      -8.0      -5.0     -13.0
4       0.0      -1.0     -20.0      -5.0      -2.0       1.0      -4.0

   31352_at  31353_f_at  31354_r_at  31355_at  31356_at  31357_at  31358_at  \
0      10.0       113.0       -75.0       7.0      49.0     -18.0      -3.0
1      30.0       116.0      -198.0       4.0     138.0     -11.0     -21.0
2       3.0        55.0       -31.0      -9.0       8.0      -3.0       3.0
3       1.0        10.0       -18.0      -2.0       7.0      -3.0      -1.0
4       2.0        13.0       -13.0      -3.0       2.0      -5.0       1.0

   31359_at  31360_at  31361_at  31362_at  31363_at  31364_i_at  31365_f_at  \
0      -1.0       4.0      -1.0      33.0      -1.0        -5.0        34.0
1     -28.0       6.0     -57.0       7.0      58.0         6.0        33.0
2       0.0       1.0      -7.0     -15.0      15.0        -1.0         3.0
3      -1.0       1.0      -3.0      -5.0       0.0        -1.0         2.0
4      -3.0       0.0       2.0     -10.0       4.0        -2.0         0.0

   31366_at  31367_at  31368_at  31369_at  31370_at  31371_at  31372_at  \
0       2.0     -35.0      17.0     -10.0      24.0       4.0     -33.0
1      -7.0     -99.0      16.0     -11.0       6.0      -9.0     -70.0
2       1.0     -30.0       0.0      -3.0       1.0       0.0      -6.0
3       4.0     -11.0      -2.0       0.0       0.0       0.0       6.0
4      -1.0      -8.0       0.0       0.0       0.0       0.0       7.0

   31373_at  31374_at  31375_at  31376_at  31377_r_at  31378_at  31379_at  \
0       3.0      -4.0     132.0      -5.0        52.0      26.0      20.0
1      26.0     -33.0     121.0      -5.0        10.0       4.0      43.0
2      -1.0     -15.0      19.0       1.0         3.0       7.0      10.0
3       2.0      -4.0       9.0      -1.0         3.0       3.0       4.0
4       0.0       0.0      12.0       1.0         4.0       0.0       9.0

   31380_at  31381_at  31382_f_at  31383_at  31384_at  31385_at  31386_at  \
0       1.0     -35.0         4.0       2.0     -90.0       4.0     220.0
1      -6.0     -36.0         5.0      -4.0    -126.0      21.0     194.0
2       0.0      -9.0        -3.0       0.0     -33.0     122.0      38.0
3       0.0      -3.0        -2.0      -1.0     -25.0     678.0      15.0
4       2.0      -2.0        -2.0       0.0     -12.0     590.0      14.0

   31387_at  31388_at  31389_at  31390_at  31391_at  31392_r_at  31393_r_at  \
0     -51.0       0.0      14.0     -13.0     215.0        19.0      -610.0
1     -52.0       2.0      38.0     -12.0     365.0        46.0      -876.0
2     -18.0       0.0      15.0       0.0      84.0         6.0      -206.0
3      -5.0      -1.0      11.0      -1.0      30.0         1.0       -79.0
4       1.0      -1.0       7.0       0.0      40.0         3.0       -41.0

   31394_at  31395_i_at  31396_r_at  31397_at  31398_at  31399_at  31400_at  \
0       4.0       -22.0        27.0       1.0     -52.0      68.0       0.0
1     -21.0       -31.0       627.0      27.0      40.0      48.0     -17.0
2       0.0        -5.0       170.0      11.0       6.0      18.0       0.0
3      -2.0        -5.0       -68.0       0.0       3.0       6.0       0.0
4      -1.0         0.0        93.0       1.0       0.0       9.0       1.0

   31401_r_at  31402_at  31403_at  31404_at  31405_at  31406_at  31407_at  \
0         1.0      55.0      57.0     -57.0     -90.0    -195.0      -2.0
1         2.0     -29.0      74.0     -82.0     -19.0    -164.0      13.0
2        -2.0       9.0      28.0     -29.0     -12.0     -33.0       0.0
3         0.0      15.0       5.0      -8.0     -10.0     -69.0       0.0
4         0.0      -2.0       9.0     -16.0      -6.0     -32.0       1.0

   31408_at  31409_at  31410_at  31411_at  31412_at  31413_at  31414_at  \
0      11.0      17.0       0.0     -10.0      17.0      13.0      35.0
1      47.0       2.0      36.0       0.0       5.0      23.0      35.0
2      16.0       6.0      17.0      -4.0       1.0       1.0      17.0
3       2.0       1.0      -8.0       0.0       0.0       0.0       0.0
4       5.0       3.0      -4.0       0.0      -5.0       3.0       2.0

   31415_at  31416_at  31417_at  31418_at  31419_r_at  31420_at  31421_at  \
0      -6.0       0.0      58.0       2.0       408.0     -10.0      -2.0
1     -10.0      60.0      59.0      -4.0       599.0     -27.0       1.0
2       0.0       7.0      21.0       2.0        76.0       1.0      -3.0
3       0.0      -7.0       8.0       7.0        70.0      -4.0      -1.0
4       0.0       0.0      10.0       5.0        38.0      -1.0       3.0

   31422_at  31423_at  31424_at  31425_g_at  31426_at  31427_at  31428_at  \
0     -39.0       0.0       1.0        23.0      45.0      -2.0     -60.0
1     -51.0     -26.0     -49.0        -6.0      24.0      -7.0     -66.0
2     -15.0       5.0       0.0         3.0      30.0      -1.0     -24.0
3      -5.0       7.0      -8.0         2.0      12.0       0.0      -4.0
4      -4.0       2.0       4.0         0.0       6.0       2.0      -7.0

   31429_at  31430_at  31431_at  31432_g_at  31433_at  31434_at  31435_at  \
0     179.0      12.0     -36.0       -36.0      16.0      31.0     -16.0
1     173.0       4.0     -48.0       -69.0      46.0      56.0      -4.0
2      42.0       1.0     -10.0         8.0      19.0      12.0      -6.0
3      14.0       1.0      49.0       106.0       3.0       4.0      -7.0
4      16.0      -1.0      16.0        53.0       0.0       3.0      -2.0

   31436_s_at  31437_r_at  31438_s_at  31439_f_at  31440_at  31441_at  \
0        18.0         3.0        29.0         1.0     174.0      18.0
1        80.0       -49.0        54.0         5.0     188.0     -15.0
2        17.0        -7.0        11.0        38.0      60.0      -4.0
3         3.0        -2.0         5.0         5.0      17.0      -2.0
4         4.0        -7.0         7.0         7.0      24.0       0.0

   31442_at  31443_at  31444_s_at  31445_at  31446_s_at  31447_at  31448_s_at  \
0       4.0     174.0      1248.0     -30.0       -61.0      44.0        -8.0
1       0.0     219.0      1170.0     -13.0        -7.0      30.0        -2.0
2      -2.0      55.0      1887.0      -2.0         7.0      14.0         0.0
3      -5.0      10.0       610.0      -1.0         0.0       1.0         0.0
4       0.0      24.0       683.0       1.0         5.0       1.0         0.0

   31449_at  31450_s_at  31451_at  31452_at  31453_s_at  31454_f_at  \
0      15.0       -27.0    -124.0       9.0         7.0        20.0
1      -4.0        12.0    -397.0      28.0         2.0         3.0
2       5.0        -3.0     -55.0      11.0         2.0         7.0
3       0.0        -5.0     -10.0      -2.0         0.0         0.0
4       2.0         0.0     -31.0       3.0        -2.0         0.0

   31455_r_at  31456_at  31457_at  31458_at  31459_i_at  31460_f_at  31461_at  \
0       -10.0      13.0     -27.0      -3.0         1.0       -38.0     -26.0
1        14.0      43.0     -48.0      18.0       -23.0       -33.0      -4.0
2         1.0      10.0      -1.0       9.0        -6.0       -13.0      -1.0
3         0.0       2.0       0.0      -3.0        -2.0        -8.0       0.0
4         0.0      -1.0       3.0       0.0         0.0       -12.0      -1.0

   31462_f_at  31463_s_at  31464_at  31465_g_at  31466_at  31467_at  \
0       -24.0        97.0     -13.0       -64.0      -8.0      24.0
1         7.0        44.0     -20.0       -61.0     -35.0       0.0
2        -5.0       143.0      -3.0       -18.0      -1.0     -10.0
3        -1.0       190.0      -2.0        -8.0      -5.0     -10.0
4         0.0       179.0       0.0        -7.0       0.0      -5.0

   31468_f_at  31469_s_at  31470_at  31471_at  31472_s_at  31473_s_at  \
0        22.0        17.0     -17.0      37.0        13.0        -2.0
1        44.0        35.0      -3.0      21.0        23.0        14.0
2        19.0         8.0      -8.0       0.0         4.0         0.0
3         3.0         6.0      -1.0       5.0         8.0         0.0
4         7.0         3.0       0.0       1.0         0.0         1.0

   31474_r_at  31475_at  31476_g_at  31477_at  31478_at  31479_f_at  \
0         2.0      40.0        -7.0      37.0      92.0        15.0
1       -21.0      79.0        13.0      23.0      61.0        11.0
2         0.0      20.0        -4.0       9.0      13.0         9.0
3         5.0       9.0        -2.0      84.0       4.0         0.0
4         3.0       7.0         0.0     100.0       6.0         3.0

   31480_f_at  31481_s_at  31482_at  31483_g_at  31484_at  31485_at  \
0        -6.0         8.0     -73.0         6.0     -66.0      21.0
1         2.0         4.0    -116.0       -29.0    -198.0      95.0
2         1.0        86.0     -35.0        -4.0     -59.0      21.0
3        -1.0        94.0      -8.0        -2.0     -24.0       4.0

In [5]:
# Feature Summary
summary.head(100)

,index,dtype,n_missing,pct_missing,n_unique,examples
0,HasTumor,category,0.0,0.0,2.0,"Yes, No"
1,AFFX-MurIL2_at,float64,0.0,0.0,34.0,"-6.0, 0.0, -3.0, -2.0, -1.0, -4.0, 1.0, -8.0, -16.0, -9.0"
2,AFFX-MurIL10_at,float64,0.0,0.0,32.0,"0.0, 1.0, 2.0, -2.0, 6.0, -1.0, 5.0, 3.0, 4.0, 17.0"
3,AFFX-MurIL4_at,float64,0.0,0.0,20.0,"0.0, 1.0, 2.0, -1.0, 7.0, -2.0, 4.0, 3.0, 6.0, 8.0"
4,AFFX-MurFAS_at,float64,0.0,0.0,40.0,"4.0, 2.0, 7.0, 6.0, 5.0, 3.0, 1.0, 12.0, 11.0, 10.0"
5,AFFX-BioB-5_at,float64,0.0,0.0,30.0,"-1.0, -2.0, -5.0, 0.0, -3.0, -10.0, -8.0, -4.0, -9.0, 1.0"
6,AFFX-BioB-M_at,float64,0.0,0.0,40.0,"-3.0, -2.0, -4.0, -11.0, -8.0, -6.0, -5.0, -7.0, -9.0, -18.0"
7,AFFX-BioB-3_at,float64,0.0,0.0,30.0,"0.0, -2.0, -1.0, -3.0, 1.0, -7.0, -8.0, 4.0, -11.0, 2.0"
8,AFFX-BioC-5_at,float64,0.0,0.0,43.0,"8.0, 5.0, 7.0, 4.0, 6.0, 10.0, 2.0, 12.0, 0.0, 19.0"
9,AFFX-BioC-3_at,float64,0.0,0.0,48.0,"-6.0, -4.0, -7.0, -12.0, -3.0, -10.0, -5.0, -11.0, -8.0, -14.0"
10,AFFX-BioDn-5_at,float64,0.0,0.0,46.0,"-9.0, -6.0, -5.0, -10.0, -13.0, -11.0, -16.0, -28.0, -23.0, -15.0"
11,AFFX-BioDn-3_at,float64,0.0,0.0,58.0,"13.0, 12.0, 21.0, 9.0, 18.0, 15.0, 11.0, 7.0, 8.0, 4.0"
12,AFFX-CreX-5_at,float64,0.0,0.0,28.0,"-3.0, -5.0, -2.0, -6.0, -4.0, -11.0, -7.0, -9.0, -19.0, -1.0"
13,AFFX-CreX-3_at,float64,0.0,0.0,27.0,"0.0, 1.0, -2.0, 2.0, 3.0, 4.0, -1.0, 6.0, 11.0, -3.0"
14,AFFX-BioB-5_st,float64,0.0,0.0,49.0,"8.0, 4.0, 11.0, 6.0, 7.0, 0.0, 13.0, 10.0, 12.0, 5.0"
15,AFFX-BioB-M_st,float64,0.0,0.0,38.0,"0.0, -3.0, -8.0, -4.0, -2.0, 3.0, 2.0, -1.0, -5.0, 5.0"
16,AFFX-BioB-3_st,float64,0.0,0.0,66.0,"-14.0, -16.0, -36.0, -25.0, -31.0, -23.0, -22.0, -66.0, -13.0, -70.0"
17,AFFX-BioC-5_st,float64,0.0,0.0,51.0,"-1.0, 0.0, -9.0, -5.0, -12.0, -8.0, -3.0, -6.0, -7.0, -14.0"
18,AFFX-BioC-3_st,float64,0.0,0.0,29.0,"0.0, -1.0, -4.0, -5.0, -8.0, -9.0, -2.0, -3.0, -17.0, -14.0"
19,AFFX-BioDn-5_st,float64,0.0,0.0,59.0,"5.0, 4.0, 6.0, 8.0, 3.0, 7.0, 47.0, 14.0, 9.0, 10.0"
20,AFFX-BioDn-3_st,float64,0.0,0.0,45.0,"6.0, 3.0, 5.0, 4.0, 7.0, 2.0, 11.0, 14.0, 30.0, 8.0"
21,AFFX-CreX-5_st,float64,0.0,0.0,29.0,"0.0, -1.0, -3.0, -2.0, -4.0, -5.0, 2.0, 3.0, -12.0, 6.0"
22,AFFX-CreX-3_st,float64,0.0,0.0,55.0,"-11.0, -7.0, -5.0, -12.0, -19.0, -18.0, -16.0, -46.0, -20.0, -21.0"
23,AFFX-hum_alu_at,float64,0.0,0.0,100.0,"2002.0, 2044.0, 4963.0, 2775.0, 1684.0, 2065.0, 3497.0, 2951.0, 2247.0, 3095.0"
24,AFFX-DapX-5_at,float64,0.0,0.0,26.0,"0.0, 2.0, 4.0, 1.0, 3.0, -1.0, 6.0, 7.0, 14.0, 15.0"
25,AFFX-DapX-M_at,float64,0.0,0.0,44.0,"1.0, 4.0, 3.0, 6.0, 11.0, 10.0, 0.0, 8.0, 2.0, 13.0"
26,AFFX-DapX-3_at,float64,0.0,0.0,28.0,"0.0, -1.0, -2.0, -3.0, -4.0, -5.0, 1.0, -8.0, 2.0, -19.0"
27,AFFX-LysX-5_at,float64,0.0,0.0,20.0,"0.0, -1.0, 1.0, 2.0, -3.0, 5.0, 3.0, 6.0, -5.0, -2.0"
28,AFFX-LysX-M_at,float64,0.0,0.0,38.0,"0.0, -3.0, -2.0, -7.0, -1.0, -4.0, -8.0, -31.0, -5.0, -6.0"
29,AFFX-LysX-3_at,float64,0.0,0.0,32.0,"0.0, 2.0, 3.0, 4.0, 5.0, 1.0, -1.0, 9.0, 7.0, 11.0"
30,AFFX-PheX-5_at,float64,0.0,0.0,28.0,"0.0, -1.0, -2.0, -3.0, -7.0, -5.0, 1.0, -4.0, -6.0, -12.0"
31,AFFX-PheX-M_at,float64,0.0,0.0,24.0,"-2.0, 0.0, -1.0, -4.0, -6.0, -3.0, -5.0, -7.0, -16.0, -11.0"
32,AFFX-PheX-3_at,float64,0.0,0.0,27.0,"0.0, -1.0, -3.0, -2.0, 1.0, 2.0, -4.0, 3.0, 4.0, -6.0"
33,AFFX-ThrX-5_at,float64,0.0,0.0,24.0,"0.0, -1.0, -2.0, 2.0, -5.0, 5.0, -4.0, -3.0, 3.0, 1.0"
34,AFFX-ThrX-M_at,float64,0.0,0.0,22.0,"0.0, -2.0, -1.0, 1.0, -3.0, 2.0, -4.0, -7.0, -6.0, -5.0"
35,AFFX-ThrX-3_at,float64,0.0,0.0,42.0,"-5.0, -11.0, -7.0, -6.0, -9.0, -1.0, -10.0, -3.0, -12.0, -15.0"
36,AFFX-TrpnX-5_at,float64,0.0,0.0,23.0,"0.0, 1.0, 3.0, 2.0, 4.0, 5.0, 7.0, -1.0, -2.0, 12.0"
37,AFFX-TrpnX-M_at,float64,0.0,0.0,42.0,"-11.0, -4.0, -2.0, -5.0, -3.0, -7.0, -19.0, -10.0, -13.0, -15.0"
38,AFFX-TrpnX-3_at,float64,0.0,0.0,18.0,"0.0, 1.0, -1.0, -3.0, 2.0, -2.0, -10.0, -9.0, 5.0, -4.0"
39,AFFX-HUMISGF3A/M97935_5_at,float64,0.0,0.0,23.0,"0.0, 1.0, 2.0, 3.0, -1.0, -2.0, 4.0, -3.0, -4.0, 14.0"
40,AFFX-HUMISGF3A/M97935_MA_at,float64,0.0,0.0,40.0,"0.0, -2.0, -5.0, 3.0, 1.0, 6.0, -1.0, 5.0, -6.0, -3.0"
41,AFFX-HUMISGF3A/M97935_MB_at,float64,0.0,0.0,33.0,"5.0, 4.0, 7.0, 11.0, 6.0, 13.0, 1.0, 10.0, 3.0, 2.0"
42,AFFX-HUMISGF3A/M97935_3_at,float64,0.0,0.0,54.0,"36.0, 35.0, 30.0, 42.0, 26.0, 12.0, 68.0, 24.0, 25.0, 23.0"
43,AFFX-HUMRGE/M10098_5_at,float64,0.0,0.0,42.0,"0.0, 3.0, 4.0, 1.0, -2.0, 8.0, -1.0, 46.0, 5.0, 2.0"
44,AFFX-HUMRGE/M10098_M_at,float64,0.0,0.0,51.0,"-3.0, -8.0, 0.0, -6.0, -7.0, -10.0, -20.0, -9.0, -12.0, -13.0"
45,AFFX-HUMRGE/M10098_3_at,float64,0.0,0.0,53.0,"-6.0, -7.0, -18.0, -11.0, -3.0, -9.0, -2.0, 1.0, -4.0, -13.0"
46,AFFX-HUMGAPDH/M33197_5_at,float64,0.0,0.0,83.0,"85.0, 101.0, 43.0, 61.0, 185.0, 21.0, 49.0, 139.0, 55.0, 99.0"
47,AFFX-HUMGAPDH/M33197_M_at,float64,0.0,0.0,93.0,"263.0, 195.0, 170.0, 143.0, 313.0, 243.0, 24.0, 136.0, 155.0, 205.0"
48,AFFX-HUMGAPDH/M33197_3_at,float64,0.0,0.0,92.0,"561.0, 416.0, 405.0, 465.0, 423.0, 213.0, 475.0, 460.0, 298.0, 370.0"
49,AFFX-HSAC07/X00351_5_at,float64,0.0,0.0,91.0,"126.0, 52.0, 35.0, 93.0, 134.0, 45.0, 152.0, 80.0, 36.0, 69.0"
50,AFFX-HSAC07/X00351_M_at,float64,0.0,0.0,91.0,"416.0, 616.0, 29.0, 122.0, 67.0, 135.0, 125.0, 827.0, 116.0, 141.0"
51,AFFX-HSAC07/X00351_3_at,float64,0.0,0.0,99.0,"1095.0, 1365.0, 1341.0, 1057.0, 699.0, 757.0, 828.0, 1256.0, 1248.0, 926.0"
52,AFFX-HUMTFRR/M11507_5_at,float64,0.0,0.0,31.0,"1.0, 3.0, 2.0, 5.0, 6.0, 4.0, 9.0, 10.0, 8.0, 11.0"
53,AFFX-HUMTFRR/M11507_M_at,float64,0.0,0.0,24.0,"0.0, -1.0, -3.0, -2.0, -6.0, -7.0, -4.0, -5.0, -9.0, -14.0"
54,AFFX-HUMTFRR/M11507_3_at,float64,0.0,0.0,40.0,"1.0, 2.0, 3.0, 7.0, 4.0, 6.0, 9.0, 17.0, 5.0, 0.0"
55,AFFX-M27830_5_at,float64,0.0,0.0,45.0,"6.0, 2.0, 0.0, 7.0, 15.0, 10.0, 4.0, 1.0, 5.0, 24.0"
56,AFFX-M27830_M_at,float64,0.0,0.0,84.0,"64.0, 20.0, 65.0, 260.0, 66.0, 35.0, 48.0, 67.0, 218.0, 62.0"
57,AFFX-M27830_3_at,float64,0.0,0.0,76.0,"78.0, 18.0, 42.0, 63.0, 14.0, 33.0, 105.0, 35.0, 34.0, 15.0"
58,AFFX-HSAC07/X00351_3_st,float64,0.0,0.0,78.0,"26.0, 58.0, 12.0, 36.0, 15.0, 27.0, 14.0, 33.0, 94.0, 21.0"
59,AFFX-HUMGAPDH/M33197_5_st,float64,0.0,0.0,37.0,"-7.0, -11.0, -4.0, -6.0, -3.0, -12.0, -8.0, -16.0, -9.0, -10.0"
60,AFFX-HUMGAPDH/M33197_M_st,float64,0.0,0.0,33.0,"0.0, 2.0, 1.0, 4.0, -2.0, 3.0, -3.0, 5.0, 6.0, 7.0"
61,AFFX-HUMGAPDH/M33197_3_st,float64,0.0,0.0,38.0,"0.0, 2.0, 1.0, 6.0, 11.0, 4.0, 16.0, 7.0, 8.0, 10.0"
62,AFFX-HSAC07/X00351_5_st,float64,0.0,0.0,42.0,"-1.0, -6.0, -9.0, -8.0, -2.0, -3.0, -5.0, -7.0, -13.0, -12.0"
63,AFFX-HSAC07/X00351_M_st,float64,0.0,0.0,43.0,"0.0, 3.0, 5.0, 2.0, 1.0, 4.0, 6.0, 10.0, 19.0, -3.0"
64,AFFX-YEL002c/WBP1_at,float64,0.0,0.0,23.0,"0.0, -1.0, 1.0, 3.0, -2.0, 4.0, 2.0, -4.0, -5.0, 9.0"
65,AFFX-YEL018w/_at,float64,0.0,0.0,35.0,"-1.0, -4.0, -2.0, -3.0, 0.0, -7.0, -8.0, -10.0, -6.0, -5.0"
66,AFFX-YEL024w/RIP1_at,float64,0.0,0.0,32.0,"4.0, 3.0, 2.0, 1.0, 7.0, 9.0, 5.0, 6.0, 8.0, 12.0"
67,AFFX-YEL021w/URA3_at,float64,0.0,0.0,48.0,"18.0, 8.0, 28.0, 10.0, 17.0, 9.0, 16.0, 21.0, 6.0, 27.0"
68,31307_at,float64,0.0,0.0,30.0,"-1.0, -7.0, 0.0, -3.0, -4.0, -2.0, -9.0, -8.0, -5.0, -16.0"
69,31308_at,float64,0.0,0.0,24.0,"-1.0, 0.0, -3.0, -2.0, -6.0, -11.0, 1.0, -4.0, -17.0, -5.0"
70,31309_r_at,float64,0.0,0.0,22.0,"0.0, -1.0, 1.0, -2.0, 2.0, 4.0, -3.0, 3.0, 5.0, 8.0"
71,31310_at,float64,0.0,0.0,26.0,"0.0, -1.0, -2.0, 1.0, 3.0, 2.0, 5.0, 4.0, -3.0, -5.0"
72,31311_at,float64,0.0,0.0,53.0,"6.0, 10.0, 9.0, 7.0, 12.0, 11.0, 2.0, 15.0, 4.0, 5.0"
73,31312_at,float64,0.0,0.0,39.0,"0.0, 1.0, -1.0, -6.0, -2.0, -4.0, 2.0, 4.0, -11.0, -18.0"
74,31313_at,float64,0.0,0.0,48.0,"-3.0, -4.0, -1.0, 0.0, -25.0, -13.0, -6.0, -7.0, -12.0, -30.0"
75,31314_at,float64,0.0,0.0,38.0,"0.0, -2.0, 1.0, -3.0, -6.0, 3.0, -1.0, 4.0, 8.0, 2.0"
76,31315_at,float64,0.0,0.0,42.0,"-1.0, 9.0, 3.0, 6.0, -2.0, 0.0, 10.0, -4.0, 12.0, 8.0"
77,31316_at,float64,0.0,0.0,18.0,"0.0, -1.0, -2.0, -3.0, -4.0, 1.0, -6.0, -5.0, 3.0, -12.0"
78,31317_r_at,float64,0.0,0.0,83.0,"25.0, 73.0, 39.0, 105.0, 69.0, 91.0, 56.0, 27.0, 143.0, 38.0"
79,31318_at,float64,0.0,0.0,18.0,"0.0, -1.0, 1.0, -2.0, 2.0, -3.0, -4.0, -17.0, 4.0, 8.0"
80,31319_at,float64,0.0,0.0,38.0,"-1.0, 0.0, 2.0, 1.0, 7.0, 4.0, -5.0, -2.0, 3.0, -4.0"
81,31320_at,float64,0.0,0.0,72.0,"0.0, -8.0, -3.0, -30.0, -9.0, -6.0, -18.0, 5.0, -13.0, -12.0"
82,31321_at,float64,0.0,0.0,48.0,"6.0, 7.0, 11.0, 15.0, 8.0, 10.0, 23.0, 9.0, 25.0, 12.0"
83,31322_at,float64,0.0,0.0,28.0,"0.0, 1.0, 2.0, 5.0, 3.0, 6.0, -1.0, 7.0, 4.0, 18.0"
84,31323_r_at,float64,0.0,0.0,53.0,"8.0, 5.0, -6.0, -3.0, 0.0, -5.0, 7.0, 25.0, 6.0, -12.0"
85,31324_at,float64,0.0,0.0,72.0,"12.0, 20.0, 4.0, 3.0, 34.0, 5.0, 63.0, 18.0, 75.0, 102.0"
86,31325_at,float64,0.0,0.0,42.0,"-5.0, -4.0, -2.0, -6.0, -3.0, 0.0, -10.0, -9.0, -7.0, -12.0"
87,31326_at,float64,0.0,0.0,69.0,"-6.0, -11.0, -10.0, -8.0, -7.0, 0.0, -4.0, -5.0, -20.0, -83.0"
88,31327_at,float64,0.0,0.0,20.0,"0.0, -1.0, -2.0, -3.0, -4.0, -5.0, 1.0, -10.0, -6.0, -18.0"
89,31328_at,float64,0.0,0.0,28.0,"5.0, 6.0, 8.0, 7.0, 3.0, 0.0, 4.0, 10.0, 2.0, 1.0"
90,31329_at,float64,0.0,0.0,28.0,"0.0, 1.0, 2.0, 4.0, -2.0, 3.0, 6.0, 5.0, -3.0, 21.0"
91,31330_at,float64,0.0,0.0,97.0,"451.0, 627.0, 616.0, 16.0, 523.0, 959.0, 6.0, 7.0, 151.0, 609.0"
92,31331_at,float64,0.0,0.0,30.0,"0.0, -1.0, -2.0, 1.0, 2.0, -5.0, -4.0, -22.0, -8.0, -9.0"
93,31332_at,float64,0.0,0.0,18.0,"0.0, 2.0, 3.0, 1.0, -1.0, -3.0, -6.0, -4.0, -5.0, -2.0"
94,31333_at,float64,0.0,0.0,26.0,"0.0, 1.0, 2.0, -1.0, -3.0, 3.0, 7.0, -5.0, -2.0, 20.0"
95,31334_at,float64,0.0,0.0,25.0,"0.0, -1.0, 2.0, -2.0, -3.0, 1.0, -6.0, 3.0, -9.0, -5.0"
96,31335_at,float64,0.0,0.0,38.0,"-3.0, -2.0, -8.0, -4.0, -6.0, -17.0, 0.0, -11.0, -5.0, -7.0"
97,31336_at,float64,0.0,0.0,21.0,"0.0, -1.0, 1.0, 2.0, -2.0, -3.0, 5.0, 9.0, -4.0, 4.0"
98,31337_at,float64,0.0,0.0,68.0,"-8.0, -18.0, -19.0, -14.0, -32.0, -15.0, -5.0, -22.0, -3.0, -24.0"
99,31338_at,float64,0.0,0.0,22.0,"0.0, 1.0, -1.0, 2.0, -2.0, 3.0, -3.0, -5.0, -10.0, 12.0"

In [6]:
# Numeric Feature Statistics
numeric_stats.head(100)

                             count         mean          std     min      max
AFFX-MurIL2_at               102.0    -7.389216    11.949000   -69.0     10.0
AFFX-MurIL10_at              102.0     6.491176    10.837870   -20.0     51.0
AFFX-MurIL4_at               102.0     1.734314     4.214790   -12.0     18.0
AFFX-MurFAS_at               102.0    14.979412    18.144242   -32.0     96.0
AFFX-BioB-5_at               102.0    -5.008824     9.507997   -51.0     30.0
AFFX-BioB-M_at               102.0   -15.268627    17.607435  -103.0      0.0
AFFX-BioB-3_at               102.0    -4.300000     9.953745   -44.0     23.0
AFFX-BioC-5_at               102.0    13.690196    16.093283   -11.0     94.0
AFFX-BioC-3_at               102.0   -19.149020    21.458404  -124.0      0.0
AFFX-BioDn-5_at              102.0   -25.250980    22.310974   -83.0     -3.0
AFFX-BioDn-3_at              102.0    -2.423529    44.470342  -164.0     87.0
AFFX-CreX-5_at               102.0    -9.540196     8.831114   -42.0     -1.0
AFFX-CreX-3_at               102.0     3.225490    10.541673   -49.0     64.0
AFFX-BioB-5_st               102.0    22.256863    33.566088  -135.0    144.0
AFFX-BioB-M_st               102.0    -5.905882    15.034105   -74.0     46.0
AFFX-BioB-3_st               102.0   -58.497059    51.705611  -283.0     -7.0
AFFX-BioC-5_st               102.0   -23.336275    30.153133  -140.0      3.0
AFFX-BioC-3_st               102.0    -6.246078     9.089562   -49.0     25.0
AFFX-BioDn-5_st              102.0    41.903922    56.496096   -10.0    263.0
AFFX-BioDn-3_st              102.0    15.418627    16.899357   -10.0     86.0
AFFX-CreX-5_st               102.0    -2.341176     7.043266   -41.0     18.0
AFFX-CreX-3_st               102.0   -33.428431    35.506877  -164.0     -1.0
AFFX-hum_alu_at              102.0  3089.254902  1823.041560  1243.0  17530.0
AFFX-DapX-5_at               102.0     4.304902     6.223023    -8.0     32.0
AFFX-DapX-M_at               102.0    16.601961    17.986629   -18.0     93.0
AFFX-DapX-3_at               102.0    -5.091176    10.121266   -61.0      8.0
AFFX-LysX-5_at               102.0     0.107843     4.334770   -28.0     18.0
AFFX-LysX-M_at               102.0   -11.850980    17.795865  -129.0      3.0
AFFX-LysX-3_at               102.0     8.531373    11.786399    -2.0     48.0
AFFX-PheX-5_at               102.0    -4.296078     8.473546   -50.0     15.0
AFFX-PheX-M_at               102.0    -6.538235     7.357397   -35.0      0.0
AFFX-PheX-3_at               102.0     0.335294     7.236440   -22.0     36.0
AFFX-ThrX-5_at               102.0    -1.677451     6.535962   -40.0     26.0
AFFX-ThrX-M_at               102.0    -1.209804     4.935896   -17.0     18.0
AFFX-ThrX-3_at               102.0   -14.634314    18.263866   -77.0     73.0
AFFX-TrpnX-5_at              102.0     3.416667     6.526065   -31.0     27.0
AFFX-TrpnX-M_at              102.0   -16.580392    17.145701   -91.0      0.0
AFFX-TrpnX-3_at              102.0    -0.990196     3.456935   -13.0      8.0
AFFX-HUMISGF3A/M97935_5_at   102.0     0.761765     8.043508   -59.0     30.0
AFFX-HUMISGF3A/M97935_MA_at  102.0    -1.930392    18.585184  -120.0     36.0
AFFX-HUMISGF3A/M97935_MB_at  102.0     8.762745     9.900044   -27.0     58.0
AFFX-HUMISGF3A/M97935_3_at   102.0    39.038235    23.195310     1.0    166.0
AFFX-HUMRGE/M10098_5_at      102.0    12.516667    21.150302    -8.0    130.0
AFFX-HUMRGE/M10098_M_at      102.0   -19.550980    26.605939  -150.0     22.0
AFFX-HUMRGE/M10098_3_at      102.0   -20.735294    30.132357  -125.0     64.0
AFFX-HUMGAPDH/M33197_5_at    102.0   105.084314    67.582354    14.0    268.0
AFFX-HUMGAPDH/M33197_M_at    102.0   133.955882   171.370251  -200.0    505.0
AFFX-HUMGAPDH/M33197_3_at    102.0   389.678431   152.570532    85.0    702.0
AFFX-HSAC07/X00351_5_at      102.0   148.576471   101.102905    34.0    473.0
AFFX-HSAC07/X00351_M_at      102.0   391.295098   332.760594  -109.0   1178.0
AFFX-HSAC07/X00351_3_at      102.0  1027.677451   520.873012    53.0   2889.0
AFFX-HUMTFRR/M11507_5_at     102.0     9.632353    13.252858     0.0     75.0
AFFX-HUMTFRR/M11507_M_at     102.0    -5.389216     6.485809   -27.0      2.0
AFFX-HUMTFRR/M11507_3_at     102.0    14.150000    20.820971    -2.0    100.0
AFFX-M27830_5_at             102.0    17.879412    27.288631   -21.0    164.0
AFFX-M27830_M_at             102.0   109.818627    90.914599    11.0    585.0
AFFX-M27830_3_at             102.0    66.571569    77.441077  -112.0    425.0
AFFX-HSAC07/X00351_3_st      102.0    72.682353    55.814604     7.0    254.0
AFFX-HUMGAPDH/M33197_5_st    102.0   -11.618627    12.980478   -72.0     29.0
AFFX-HUMGAPDH/M33197_M_st    102.0     4.130392     8.759807   -23.0     38.0
AFFX-HUMGAPDH/M33197_3_st    102.0     8.641176    13.495003   -29.0     59.0
AFFX-HSAC07/X00351_5_st      102.0   -11.782353    14.259688   -72.0      5.0
AFFX-HSAC07/X00351_M_st      102.0    12.966667    17.569958    -7.0     70.0
AFFX-YEL002c/WBP1_at         102.0    -0.288235     5.750149   -22.0     28.0
AFFX-YEL018w/_at             102.0    -8.038235    11.817448   -57.0      7.0
AFFX-YEL024w/RIP1_at         102.0    10.542157    12.339468     0.0     73.0
AFFX-YEL021w/URA3_at         102.0    31.313725    28.852297     3.0    141.0
31307_at                     102.0    -8.552941    12.460382   -98.0      7.0
31308_at                     102.0    -4.640196     6.931836   -33.0     19.0
31309_r_at                   102.0     0.309804     4.185749   -16.0     17.0
31310_at                     102.0     1.434314     6.781344   -11.0     38.0
31311_at                     102.0    26.754902    30.729557    -3.0    182.0
31312_at                     102.0    -5.908824    18.394425   -96.0     25.0
31313_at                     102.0   -21.122549    21.544961   -87.0      3.0
31314_at                     102.0     0.525490    12.233695   -55.0     46.0
31315_at                     102.0     8.563725    17.264923   -80.0     61.0
31316_at                     102.0    -1.695098     4.080535   -16.0     15.0
31317_r_at                   102.0   124.480392   118.995360     4.0    551.0
31318_at                     102.0    -1.022549     4.216232   -24.0      8.0
31319_at                     102.0     4.004902    13.571318   -35.0     65.0
31320_at                     102.0   -45.227451    60.907994  -299.0     13.0
31321_at                     102.0    24.572549    25.901627    -4.0    117.0
31322_at                     102.0     4.460784     8.192814    -7.0     39.0
31323_r_at                   102.0     5.235294    21.281320   -73.0     84.0
31324_at                     102.0    70.930392    77.618368     0.0    287.0
31325_at                     102.0   -14.352941    17.687411   -81.0      7.0
31326_at                     102.0   -55.440196    69.506752  -307.0      5.0
31327_at                     102.0    -3.426471     5.063653   -21.0      6.0
31328_at                     102.0     6.649020    10.366872   -51.0     61.0
31329_at                     102.0     2.182353     6.181871   -14.0     26.0
31330_at                     102.0   473.407843   285.058708   -62.0   1070.0
31331_at                     102.0    -3.655882     7.830337   -28.0     14.0
31332_at                     102.0    -0.088235     5.586587   -20.0     43.0
31333_at                     102.0     2.043137     8.989967   -18.0     63.0
31334_at                     102.0    -1.332353     5.851414   -23.0     19.0
31335_at                     102.0   -11.307843    16.039893   -84.0      9.0
31336_at                     102.0     0.414706     5.415917   -24.0     31.0
31337_at                     102.0     1.345098    56.998948  -130.0    252.0
31338_at                     102.0     0.587255     4.766252   -17.0     16.0
31339_at                     102.0    -8.627451    13.222335   -72.0      6.0

In [7]:
# Categorical Feature Statistics
cat_stats

              value  count    pct
column   rank
HasTumor 1      Yes     52  50.98
         2       No     50  49.02

In [8]:
# Target Distribution
target_df

          count    pct
HasTumor
Yes          52  50.98
No           50  49.02

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=20, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to pca_genexp_prediction/019d7376-206a-713c-86be-9d76eefe1448

019d7376-206a-713c-86be-9d76eefe1448
6aeeefbf9f979ca0ad83da23b0811a26ace1636b76fdacf76c02344c06dd423e