### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="sf_permit_time",
    dataset_year="2025",
    domain_str="business & marketing",
    # Data Source
    dataset_source="GOV Website",
    original_dataset_source_download_link="https://data.sfgov.org/Housing-and-Buildings/Building-Permits/i98e-djp9",
    download_description="""
We re-collected the data similar to how the data from Kaggle was created.

We go to https://data.sfgov.org/Housing-and-Buildings/Building-Permits/i98e-djp9, then we set the query such that we only take data from 1st of January 2015 until 31st of December of 2025, and then download the data as a CSV file. Due to API limits, this must be done manually. Here is the link to the query: https://data.sfgov.org/Housing-and-Buildings/Building-Permits/i98e-djp9/explore/query/SELECT%0A%20%20%60permit_number%60%2C%0A%20%20%60permit_type%60%2C%0A%20%20%60permit_type_definition%60%2C%0A%20%20%60permit_creation_date%60%2C%0A%20%20%60block%60%2C%0A%20%20%60lot%60%2C%0A%20%20%60street_number%60%2C%0A%20%20%60street_number_suffix%60%2C%0A%20%20%60street_name%60%2C%0A%20%20%60street_suffix%60%2C%0A%20%20%60unit%60%2C%0A%20%20%60unit_suffix%60%2C%0A%20%20%60description%60%2C%0A%20%20%60status%60%2C%0A%20%20%60status_date%60%2C%0A%20%20%60filed_date%60%2C%0A%20%20%60issued_date%60%2C%0A%20%20%60completed_date%60%2C%0A%20%20%60first_construction_document_date%60%2C%0A%20%20%60approved_date%60%2C%0A%20%20%60structural_notification%60%2C%0A%20%20%60number_of_existing_stories%60%2C%0A%20%20%60number_of_proposed_stories%60%2C%0A%20%20%60voluntary_soft_story_retrofit%60%2C%0A%20%20%60fire_only_permit%60%2C%0A%20%20%60estimated_cost%60%2C%0A%20%20%60revised_cost%60%2C%0A%20%20%60existing_use%60%2C%0A%20%20%60existing_units%60%2C%0A%20%20%60proposed_use%60%2C%0A%20%20%60proposed_units%60%2C%0A%20%20%60plansets%60%2C%0A%20%20%60tidf_compliance%60%2C%0A%20%20%60existing_occupancy%60%2C%0A%20%20%60proposed_occupancy%60%2C%0A%20%20%60existing_construction_type%60%2C%0A%20%20%60existing_construction_type_description%60%2C%0A%20%20%60proposed_construction_type%60%2C%0A%20%20%60proposed_construction_type_description%60%2C%0A%20%20%60site_permit%60%2C%0A%20%20%60last_permit_activity_date%60%2C%0A%20%20%60application_submission_method%60%2C%0A%20%20%60adu%60%2C%0A%20%20%60primary_address_flag%60%2C%0A%20%20%60supervisor_district%60%2C%0A%20%20%60neighborhoods_analysis_boundaries%60%2C%0A%20%20%60zipcode%60%2C%0A%20%20%60location%60%2C%0A%20%20%60point_source%60%2C%0A%20%20%60reroof%60%2C%0A%20%20%60record_id%60%2C%0A%20%20%60data_as_of%60%2C%0A%20%20%60data_loaded_at%60%0AWHERE%0A%20%20%60approved_date%60%0A%20%20%20%20BETWEEN%20%222015-01-01T16%3A13%3A34%22%20%3A%3A%20floating_timestamp%0A%20%20%20%20AND%20%222025-12-31T16%3A13%3A34%22%20%3A%3A%20floating_timestamp%0AORDER%20BY%20%60approved_date%60%20ASC%20NULL%20LAST/page/filter

We save the file in the root dir as Building_Permits_20260205.csv
mkdir -p local-data-warehouse/sf_permit_time && mv Building_Permits_20260205.csv local-data-warehouse/sf_permit_time
""",
    # References
    academic_reference_bibtex=r"""@misc{SanFrancisco2026BuildingPermits,
  author = {{City and County of San Francisco}},
  title  = {Building Permits},
  year   = {2026},
  howpublished = {\url{https://data.sfgov.org/Housing-and-Buildings/Building-Permits/i98e-djp9/about_data}},
  note   = {DataSF Open Data Portal dataset, Accessed: 2026-02-05}
}
""",
    academic_reference_bibtex_key="SanFrancisco2026BuildingPermits",
    license="Open Data Commons Public Domain Dedication and License",
    data_tags=["Non-IID","Temporal"],
    curation_comments="""
We simulate the task of predicting the days (in float) it takes to issue the permit. We add the special use case, that we assume the model is only used to predict for permits that take longer than one day to be issued. We do this, as waiting for one day seems very reasonable. Plus, the data contains several unresolvable data errors when the permit was issued on the same day it was filed.

- ALthough we donwloaded data
- We drop miscellaneous permits (those that start with "M") as they are not of interest for our task. Compared to normal permits, these are usually automatically or very quickly approved and thus are not relevant to predict the time it takes to issue the permit. Moreover, the represent a significant distribution shift compared to the rest of the data.
- We drop the permit type ordinal encoding and the creation date of the permit in the tracking system as other dates are more accurate.
- A large number of descriptions are from standard phrases (they appear in the same way multiple times). so we add a new column that indicates whether the description is from a standard phrase or not through a categorical variable. We define a standard phrase as a description that appears more than 100 times in the dataset.
- The 'Current Status' is the last status update of the permit. Note, that for miscellaneous permits, the permit is never completed. We filter to permits that have been issued for our task. Thus, we select all permits that are issued or completed.
- There are several features that have almost no information (up to only 20 non nan values). We keep this and let the pipeline decide what to do with them.
- We only keep on permit per primary address (filter based on Primary Address Flag) following https://data.sfgov.org/Housing-and-Buildings/Building-Permits-Deduplicated-on-Primary-Address/f2jc-ivnc
- We drop all permits without a location, as every permit requires a location by definition, thus these are likely data errors.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="DaysToIssue",
    problem_type="regression",
    objective_metric_name="rmse",
    time_on="Filed Date"
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(dataset_mold.path / "Building_Permits_20260205.csv")
# Things to check
# - address unique cases as on the website (This is a filtered view of the Building Permits dataset. This dataset only shows building permits where the 'Primary Address Flag' is equal to "Y", indicating it is the primary address)

df["DaysToIssue"] = (pd.to_datetime(df["Issued Date"]) - pd.to_datetime(df["Filed Date"])).dt.total_seconds() / pd.Timedelta(days=1).total_seconds()

df = df[df["DaysToIssue"] >= 1]
df = df[~df["Permit Number"].str.startswith("M")]
df = df[df["Current Status"].isin(["issued", "complete"])]
df = df[df["Primary Address Flag"] == "Y"]
df = df[~df["Location"].isna()]

df["DescriptionIsStandardPhrase"] = df["Description"].isin(df["Description"].value_counts(dropna=False)[df["Description"].value_counts(dropna=False) > 100].index)
df["Location_Latitude"] = df["Location"].apply(lambda x: str(x).split("(")[-1].split(" ")[0]).astype(float)
df["Location_Longitude"] = df["Location"].apply(lambda x: str(x).split("(")[-1].split(" ")[-1][:-1]).astype(float)

df = df.drop(columns=[
    "Permit Creation Date", # Just a log date from the system.
    "Permit Type", # Ordinal encoding of "Permit Type Definition"
    "Current Status", # repeat information from other columns, also leaks into the future
    "Current Status Date", # leaks into the future and the target
    "Completed Date", # completed happens after issuing, so this is after our task and outside of the control of the government body that issues the permit. Moreover, it leaks the target variable.
    "First Construction Document Date", # same as above
    "approved_date", # often the same value as issued date depending on the type of permit, thus leakage
    "Issued Date", # Target leakage
    "Revised Cost", # Also only available after the permit is issued most likely (after project review)
    "Existing Construction Type", # Ordinal encoding of "Existing Construction Type Description"
    "Proposed Construction Type", # Ordinal encoding of "Proposed Construction Type Description"
    "Last Permit Activity Date", # target leakage
    "ADU", # Deprecated column from 2025 onwards
    "Primary Address Flag", # constant after filter above
    "Record ID", # Unique ID
    "data_as_of", # metadata from logging system
    "data_loaded_at", # metadata from logging system
    "Location", # resolved above
    "Permit Number", # meaningless ID given other info
])

as_cat_type = [
    "Permit Type Definition",
    "DescriptionIsStandardPhrase",
    "Structural Notification",
    "Voluntary Soft-Story Retrofit",
    "Fire Only Permit",
    "TIDF Compliance",
    "Existing Construction Type Description",
    "Proposed Construction Type Description",
    "Site Permit",
    "Application Submission Method",
    "supervisor_district",
    "neighborhoods_analysis_boundaries",
    "point_source",
    "reroof",
]
as_string_type = [
    "Block",
    "Lot",
    "Street Number",
    "Street Number Suffix",
    "Street Name",
    "Street Suffix",
    "Unit",
    "Unit Suffix",
    "Description",
    "Existing Use",
    "Proposed Use",
    "Existing Occupancy",
    "Proposed Occupancy",
    "Zipcode",
]
as_datetime_type = [
    "Filed Date"
]

for c in as_string_type:
    nan_mask = df[c].isna()
    df.loc[nan_mask, c] = np.nan
    df[c] = df[c].astype("string")

for c in as_datetime_type:
    df[c] = pd.to_datetime(df[c])

df[as_cat_type] = df[as_cat_type].astype("category")

# Log scale the target
df["DaysToIssue"] = np.log(df["DaysToIssue"])

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

/tmp/ipykernel_614421/2993407991.py:4: DtypeWarning: Columns (19,23,32,35,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dataset_mold.path / "Building_Permits_20260205.csv")

/tmp/ipykernel_614421/2993407991.py:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["DaysToIssue"] = (pd.to_datetime(df["Issued Date"]) - pd.to_datetime(df["Filed Date"])).dt.total_seconds() / pd.Timedelta(days=1).total_seconds()

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

Warning: Found 2 constant feature(s) with 1 or fewer unique values (including NaNs): ['Street Number Suffix', 'Unit Suffix']

#### Dataset Overview
Rows: 116,954
Columns: 38
Use sampling: False (sample size: 116,954)

Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['Filed Date', 'Description', 'Location_Latitude', 'Location_Longitude', 'Estimated Cost', 'Block', 'Street Number', 'Proposed Occupancy', 'Existing Occupancy', 'Street Name']
Rows remaining as candidates after top-10 filter: 36 (of 116,954)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 18 (0.02% of dataset)
Get column duplicates...

Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,Permit Type Definition,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,Unit,Unit Suffix,Description,Filed Date,Structural Notification,Number of Existing Stories,Number of Proposed Stories,Voluntary Soft-Story Retrofit,Fire Only Permit,Estimated Cost,Existing Use,Existing Units,Proposed Use,Proposed Units,Plansets,TIDF Compliance,Existing Occupancy,Proposed Occupancy,Existing Construction Type Description,Proposed Construction Type Description,Site Permit,Application Submission Method,supervisor_district,neighborhoods_analysis_boundaries,Zipcode,point_source,reroof,DaysToIssue,DescriptionIsStandardPhrase,Location_Latitude,Location_Longitude
0,otc alterations permit,3602,036,225.0,<NA>,Hartford,St,0.0,<NA>,"to comply with nov#201390061, construction of new egress stair from upper apartment that had been illegally removed by previous owner. removal of non permitted space, restoration of original exterior wall at location of non permitted additions, new rear deck.",2016-09-23 14:26:18,Y,4.0,4.0,NaN,NaN,19500.0,apartments,4.0,apartments,4.0,2.0,NaN,R-2,R-2,wood frame (5),wood frame (5),NaN,in-house,8.0,Castro/Upper Market,94114.0,eas_address_point,NaN,1.095633,False,-122.433383,37.758930
1,otc alterations permit,2019,016,2350.0,<NA>,Noriega,St,<NA>,<NA>,"install one utility transformer, 1 switchboard assembly, 4 150 kw btc power units, 4 150 kw btc dispensers.",2019-04-09 12:53:35,NaN,0.0,0.0,NaN,NaN,100000.0,parking lot,0.0,parking lot,0.0,2.0,NaN,S-2,S-2,constr type 1,constr type 1,NaN,in-house,4.0,Sunset/Parkside,94122.0,eas_address_point,NaN,4.354326,False,-122.488820,37.754128
2,otc alterations permit,1291,034,617.0,<NA>,Belvedere,St,<NA>,<NA>,"top unit: proposed interior remodel, consisting of expanding kitchen, & reconfigure existing bathroom.",2020-02-03 11:04:15,NaN,3.0,3.0,NaN,NaN,150000.0,2 family dwelling,2.0,2 family dwelling,2.0,2.0,NaN,R-3,R-3,wood frame (5),wood frame (5),NaN,in-house,8.0,Inner Sunset,94117.0,eas_address_point,NaN,2.075805,False,-122.448001,37.761444
3,otc alterations permit,1931,035C,621.0,<NA>,Lawton,St,<NA>,<NA>,voluntary foundation - bolt house & sheath cripple walls as per details,2015-04-03 15:54:59,NaN,2.0,2.0,NaN,NaN,8000.0,1 family dwelling,1.0,1 family dwelling,1.0,2.0,NaN,R-3,R-3,wood frame (5),wood frame (5),NaN,in-house,7.0,Inner Sunset,94122.0,eas_address_point,NaN,1.011310,False,-122.469563,37.758040
4,otc alterations permit,3720,009,415.0,<NA>,Mission,St,<NA>,<NA>,non rated stair connecting floors 34 and 35. ref . 2017-09-08-7306,2017-09-08 07:46:02,NaN,63.0,63.0,NaN,NaN,120000.0,office,0.0,office,0.0,2.0,NaN,B,B,constr type 1,constr type 1,NaN,in-house,6.0,Financial District/South Beach,94105.0,eas_address_point,NaN,1.170319,False,-122.397097,37.789934

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,TIDF Compliance,category,116953.0,100.00,1.0,P
1,Voluntary Soft-Story Retrofit,category,116943.0,99.99,1.0,Y
2,reroof,category,115306.0,98.59,1.0,Y
3,Site Permit,category,113361.0,96.93,1.0,Y
4,Structural Notification,category,109395.0,93.54,1.0,Y
5,Fire Only Permit,category,102457.0,87.60,1.0,Y
6,Proposed Construction Type Description,category,5865.0,5.01,5.0,"wood frame (5), constr type 1, constr type 3, constr type 2, constr type 4"
7,Existing Construction Type Description,category,4975.0,4.25,5.0,"wood frame (5), constr type 1, constr type 3, constr type 2, constr type 4"
8,Permit Type Definition,category,168.0,0.14,8.0,"otc alterations permit, additions alterations or repairs, sign - erect, demolitions, new construction wood frame, wall or painted sign, new construction, grade or quarry or fill or excavate"
9,Application Submission Method,category,0.0,0.00,3.0,"in-house, website, epr website"
10,supervisor_district,category,0.0,0.00,11.0,"3.0, 6.0, 8.0, 2.0, 9.0, 7.0, 5.0, 1.0, 10.0, 4.0"
11,neighborhoods_analysis_boundaries,category,0.0,0.00,41.0,"Financial District/South Beach, Mission, Sunset/Parkside, West of Twin Peaks, South of Market, Marina, Outer Richmond, Pacific Heights, Noe Valley, Bayview Hunters Point"
12,point_source,category,0.0,0.00,2.0,"eas_address_point, parcel_centroid"
13,DescriptionIsStandardPhrase,category,0.0,0.00,2.0,"False, True"
14,Filed Date,datetime64[ns],0.0,0.00,114858.0,"2020-06-12 19:52:07, 2015-11-03 11:55:38, 2015-06-09 08:59:11, 2015-11-03 11:55:39, 2018-06-20 11:25:26, 2015-11-03 11:55:36, 2017-11-15 08:38:17, 2017-09-15 16:41:38, 2015-11-03 11:55:37, 2017-12-11 09:07:56"
15,Existing Units,float64,21728.0,18.58,366.0,"1.0, 0.0, 2.0, 6.0, 3.0, 4.0, 12.0, 5.0, 8.0, 9.0"
16,Proposed Units,float64,21179.0,18.11,381.0,"1.0, 0.0, 2.0, 3.0, 6.0, 4.0, 12.0, 5.0, 8.0, 7.0"
17,Number of Proposed Stories,float64,5544.0,4.74,66.0,"2.0, 3.0, 4.0, 1.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
18,Number of Existing Stories,float64,4522.0,3.87,65.0,"2.0, 3.0, 4.0, 1.0, 6.0, 5.0, 7.0, 8.0, 10.0, 9.0"
19,Estimated Cost,float64,241.0,0.21,11167.0,"1.0, 10000.0, 5000.0, 20000.0, 50000.0, 30000.0, 15000.0, 25000.0, 40000.0, 100000.0"
20,Plansets,float64,77.0,0.07,7.0,"2.0, 0.0, 1.0, 3.0, 4.0, 9.0, 7.0"
21,DaysToIssue,float64,0.0,0.00,113861.0,"0.0119, 0.0451, 5.5706, 0.0429, 0.6973, 1.3783, 0.0244, 0.0061, 1.1117, 0.0108"
22,Location_Latitude,float64,0.0,0.00,45279.0,"-122.395, -122.398, -122.4768, -122.3971, -122.4018, -122.4035, -122.3996, -122.3921, -122.3992, -122.3993"
23,Location_Longitude,float64,0.0,0.00,45271.0,"37.794, 37.793, 37.7285, 37.7899, 37.7898, 37.7926, 37.7946, 37.7766, 37.7956, 37.7906"
24,Unit Suffix,string,115791.0,99.01,128.0,"A, PARCEL A, B, C, D, BLDG 1, E, COMML, HOA, C102"
25,Street Number Suffix,string,115501.0,98.76,13.0,"A, B, V, C, D, L, E, K, ½, P"
26,Unit,string,101964.0,87.18,487.0,"0.0, 1.0, 101.0, 2.0, 3.0, 4.0, 201.0, 534.0, 5.0, 6.0"
27,Proposed Use,string,6611.0,5.65,93.0,"1 family dwelling, apartments, office, 2 family dwelling, retail sales, food/beverage hndlng, tourist hotel/motel, clinics-medic/dental, school, warehouse,no frnitur"
28,Proposed Occupancy,string,5150.0,4.40,1941.0,"R-3, R-2, B, B,M, R-2,B, B,M,S-2, B,R-2, M, R-2,M, M,B"
29,Existing Use,string,4332.0,3.70,90.0,"1 family dwelling, apartments, office, 2 family dwelling, retail sales, food/beverage hndlng, vacant lot, tourist hotel/motel, warehouse,no frnitur, clinics-medic/dental"
30,Existing Occupancy,string,3876.0,3.31,1730.0,"R-3, R-2, B, B,M, M, B,M,S-2, R-2,B, B,R-2, M,B, R-2,M"
31,Street Suffix,string,2178.0,1.86,19.0,"St, Av, Bl, Dr, Wy, Tr, Ct, Pl, Ln, Rd"
32,Description,string,9.0,0.01,113347.0,"reroofing, soft story retrofit per sfebc chapter 4d engineering criteria 2016 cebc appendix a-4, upgrade existing fire alarm system to comply with sffc section 1103.7.6.1, re-roofing, reroofing., soft story retrofit per sfebc chapter 4d: 2016 cebc appendix a-4, soft story retrofit per sfbc chapter 34b engineering criteria 2012 iebc appendix a-4, erect 3-story, type 5-b, no basement, single family dwelling., soft story retrofit per sfebc chapter 4d engineering criteria 2016 cebc appendix a-4., upgrade (e) fire alarm system to comply with sffc section 1103.7.6.1"
33,Zipcode,string,7.0,0.01,27.0,"94110.0, 94105.0, 94103.0, 94109.0, 94114.0, 94117.0, 94118.0, 94107.0, 94115.0, 94123.0"
34,Block,string,0.0,0.00,4851.0,"3708, 3721, 3713, 3710, 3707, 3717, 3709, 0289, 3735, 0288"
35,Lot,string,0.0,0.00,934.0,"001, 007, 008, 009, 004, 003, 005, 006, 002, 011"
36,Street Number,string,0.0,0.00,4750.0,"1.0, 101.0, 100.0, 50.0, 555.0, 201.0, 300.0, 2.0, 350.0, 333.0"
37,Street Name,string,0.0,0.00,1636.0,"Market, California, Mission, Montgomery, Geary, 03rd, Folsom, Howard, Bush, 20th"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
Number of Existing Stories,112432.0,6.862779,1.024347e+01,0.000000,6.700000e+01
Number of Proposed Stories,111410.0,6.933902,1.025844e+01,0.000000,1.180000e+02
Estimated Cost,116713.0,246251.141330,3.856691e+06,0.000000,5.379586e+08
Existing Units,95226.0,18.586510,8.123818e+01,0.000000,1.907000e+03
Proposed Units,95775.0,19.772613,8.154362e+01,0.000000,1.907000e+03
Plansets,116877.0,1.779734,6.258673e-01,0.000000,9.000000e+00
DaysToIssue,116954.0,3.246426,1.716170e+00,0.000012,8.139683e+00
Location_Latitude,116954.0,-122.429255,2.982557e-02,-122.510735,-1.223629e+02
Location_Longitude,116954.0,37.769456,2.412744e-02,37.708201,3.782981e+01

In [7]:
# Categorical Feature Statistics
cat_stats

                                                                                                           value  \
column                                 rank
Application Submission Method          1                                                                in-house
                                       2                                                                 website
                                       3                                                             epr website
Block                                  1                                                                    3708
                                       2                                                                    3721
                                       3                                                                    3713
                                       4                                                                    3710
                                       5                                                                    3707
Description                            1                                                               reroofing
                                       2     soft story retrofit per sfebc chapter 4d engineering criteria 20...
                                       3     upgrade existing fire alarm system to comply with sffc section 1...
                                       4                                                              re-roofing
                                       5                                                              reroofing.
DescriptionIsStandardPhrase            1                                                                   False
                                       2                                                                    True
Existing Construction Type Description 1                                                          wood frame (5)
                                       2                                                           constr type 1
                                       3                                                           constr type 3
                                       4                                                                    <NA>
                                       5                                                           constr type 2
Existing Occupancy                     1                                                                     R-3
                                       2                                                                     R-2
                                       3                                                                       B
                                       4                                                                    <NA>
                                       5                                                                     B,M
Existing Use                           1                                                       1 family dwelling
                                       2                                                              apartments
                                       3                                                                  office
                                       4                                                       2 family dwelling
                                       5                                                            retail sales
Filed Date                             1                                                     2020-06-12 19:52:07
                                       2                                                     2015-11-03 11:55:38
                                       3                                                     2015-06-09 08:59:11
                                       4                                                     2015-11-03 11:55:39
                                       5                                                     2018-06-20 11:25:26
Fire Only Permit                       1                                                                    <NA>
                                       2                                                                       Y
Lot                                    1                                                                     001
                                       2                                                                     007
                                       3                                                                     008
                                       4                                                                     009
                                       5                                                                     004
Permit Type Definition                 1                                                  otc alterations permit
                                       2                                        additions alterations or repairs
                                       3                                                            sign - erect
                                       4                                                             demolitions
                                       5                                             new construction wood frame
Proposed Construction Type Description 1                                                          wood frame (5)
                                       2                                                           constr type 1
                                       3                                                           constr type 3
                                       4                                                                    <NA>
                                       5                                                           constr type 2
Proposed Occupancy                     1                                                                     R-3
                                       2                                                                     R-2
                                       3                                                                       B
                                       4                                                                    <NA>
                                       5                                                                     B,M
Proposed Use                           1                                                       1 family dwelling
                                       2                                                              apartments
                                       3                                                                  office
                                       4                                                       2 family dwelling
                                       5                                                                    <NA>
Site Permit                            1                                                                    <NA>
                                       2                                                                       Y
Street Name                            1                                                                  Market
                                       2                                                              California
                                       3                                                                 Mission
                                       4                                                              Montgomery
                                       5                                                                   Geary
Street Number                          1                                                                     1.0
                                       2                                                                   101.0
                                       3                                                                   100.0
                                       4                                                                    50.0
                                       5                                                                   555.0
Street Number Suffix                   1                                                                    <NA>
                                       2                                                                       A
                                       3                                                                       B
                                       4                                                                       V
                                       5                                                                       C
Street Suffix                          1                                                                      St
                                       2                                                                      Av
                                       3                                                                      Bl
                                       4                                                                    <NA>
                                       5                                                                      Dr
Structural Notification                1                                                                    <NA>
                                       2                                                                       Y
TIDF Compliance                        1                                                                    <NA>
                                       2                                                                       P
Unit                                   1                                                                    <NA>
                                       2                                                                     0.0
                                       3                                                                     1.0
                                       4                                                                   101.0
                                       5                                                                     2.0
Unit Suffix                            1                                                                    <NA>
                                       2                                                                       A
                                       3                                                                PARCEL A
                                       4                                                                       B
                                       5                                                                       C
Voluntary Soft-Story Retrofit          1                                                                    <NA>
                                       2                                                                       Y
Zipcode                                1                                                                 94110.0
                                       2                                                                 94105.0
                                       3                                                                 94103.0
                                       4                                                                 94109.0
                                       5                                                                 94114.0
neighborhoods_analysis_boundaries      1                                          Financial District/South Beach
                                       2                                                                 Mission
                                       3                                                         Sunset/Parkside
                                       4                                                      West of Twin Peaks
                                       5                                                         South of Market
point_source                           1                                                       eas_address_point
                                       2                                                         parcel_centroid
reroof                                 1                                                                    <NA>
                                       2                                                                       Y
supervisor_district                    1                                                                     3.0
                                       2                                                                     6.0
                                       3                                                                     8.0
                                       4                                                                     2.0
                                       5                                                                     9.0

                                              count    pct
column                                 rank
Application Submission Method          1     116768  99.84
                                       2        181   0.15
                                       3          5    0.0
Block                                  1       1049    0.9
                                       2        539   0.46
                                       3        527   0.45
                                       4        516   0.44
                                       5        501   0.43
Description                            1        544   0.47
                                       2        178   0.15
                                       3        134   0.11
                                       4        129   0.11
                                       5        106   0.09
DescriptionIsStandardPhrase            1     115863  99.07
                                       2       1091   0.93
Existing Construction Type Description 1      73872  63.16
                                       2      25777  22.04
                                       3       8420    7.2
                                       4       4975   4.25
                                       5       3606   3.08
Existing Occupancy                     1      41421  35.42
                                       2      22395  19.15
                                       3      16738  14.31
                                       4       3876   3.31
                                       5       2953   2.52
Existing Use                           1      31930   27.3
                                       2      25169  21.52
                                       3      22295  19.06
                                       4       9963   8.52
                                       5       6562   5.61
Filed Date                             1          7   0.01
                                       2          7   0.01
                                       3          7   0.01
                                       4          6   0.01
                                       5          6   0.01
Fire Only Permit                       1     102457   87.6
                                       2      14497   12.4
Lot                                    1       6825   5.84
                                       2       3246   2.78
                                       3       3184   2.72
                                       4       2995   2.56
                                       5       2954   2.53
Permit Type Definition                 1      96895  82.85
                                       2      14299  12.23
                                       3       3515   3.01
                                       4        648   0.55
                                       5        593   0.51
Proposed Construction Type Description 1      73731  63.04
                                       2      25752  22.02
                                       3       8121   6.94
                                       4       5865   5.01
                                       5       3216   2.75
Proposed Occupancy                     1      41643  35.61
                                       2      23275   19.9
                                       3      15717  13.44
                                       4       5150    4.4
                                       5       2796   2.39
Proposed Use                           1      30904  26.42
                                       2      27211  23.27
                                       3      21713  18.57
                                       4      11307   9.67
                                       5       6611   5.65
Site Permit                            1     113361  96.93
                                       2       3593   3.07
Street Name                            1       3720   3.18
                                       2       3497   2.99
                                       3       3122   2.67
                                       4       1867    1.6
                                       5       1619   1.38
Street Number                          1       2355   2.01
                                       2       1029   0.88
                                       3        918   0.78
                                       4        783   0.67
                                       5        782   0.67
Street Number Suffix                   1     115501  98.76
                                       2       1146   0.98
                                       3        133   0.11
                                       4        122    0.1
                                       5         30   0.03
Street Suffix                          1      80462   68.8
                                       2      25012  21.39
                                       3       2604   2.23
                                       4       2178   1.86
                                       5       2121   1.81
Structural Notification                1     109395  93.54
                                       2       7559   6.46
TIDF Compliance                        1     116953  100.0
                                       2          1    0.0
Unit                                   1     101964  87.18
                                       2      11584    9.9
                                       3        610   0.52
                                       4        253   0.22
                                       5        214   0.18
Unit Suffix                            1     115791  99.01
                                       2        201   0.17
                                       3        147   0.13
                                       4         83   0.07
                                       5         71   0.06
Voluntary Soft-Story Retrofit          1     116943  99.99
                                       2         11   0.01
Zipcode                                1       8973   7.67
                                       2       8007   6.85
                                       3       6915   5.91
                                       4       6294   5.38
                                       5       6015   5.14
neighborhoods_analysis_boundaries      1      19387  16.58

In [8]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,0.15,-3.086,2.945,1.104,log,509349.5,82741244.1,exponential

## Task Curation

In [9]:
# Filter to year 2025
df_2025 = df.copy()

# Create a year-month column for grouping
df_2025["year_month"] = df_2025[task_mold.time_on].dt.to_period("Y")

# 1) Total number of samples per month
monthly_totals = (
    df_2025
    .groupby("year_month")
    .size()
    .rename("total_samples")
)

# Optional: sort by month and convert PeriodIndex to timestamp (month start)
result = monthly_totals.sort_index()
result.index = result.index.to_timestamp()
result

year_month
2015-01-01    11958
2016-01-01    11840
2017-01-01    12006
2018-01-01    12786
2019-01-01    12194
2020-01-01    10636
2021-01-01     9915
2022-01-01     9449
2023-01-01     9063
2024-01-01     8532
2025-01-01     8575
Freq: YS-JAN, Name: total_samples, dtype: int64

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata

# Sort by time
df = df.sort_values(by=task_mold.time_on).reset_index(drop=True)

splits = {}

test_years = [
    "2020",
    "2021",
    "2022",
    "2023",
    "2024",
    "2025",
]
for i, month in enumerate(test_years):
    ref_date  = pd.Timestamp(month)
    train_index = df[
        df[task_mold.time_on] < ref_date
    ].index
    test_index = df[
        (df[task_mold.time_on].dt.year == ref_date.year)
    ].index
    splits[i] = {
        0: (train_index.tolist(), test_index.tolist())
    }

for s in splits:
    train_index, test_index = splits[s][0]
    print(f"Split {s}: Train size: {len(train_index)}, Test size: {len(test_index)}")
    assert df[task_mold.time_on].iloc[train_index].max() < df[task_mold.time_on].iloc[test_index].min()

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="""We try to create splits that simulate a model deployed to solve the task.

The official data is updated daily but has not enough data per day to create large enough test splits. We opt for simulating a model that is refit every year to obtain a robust test set instead.
This introduces the unrealistic downside of data shift across a month that would not exist in a real-world model. We create 5 test splits by 2020-2025 as test year. For each test split, we use all data before the test month as training data.
""",
    splits=splits,
    time_horizon=1,
    time_horizon_unit="years",
)

Split 0: Train size: 60784, Test size: 10636
Split 1: Train size: 71420, Test size: 9915
Split 2: Train size: 81335, Test size: 9449
Split 3: Train size: 90784, Test size: 9063
Split 4: Train size: 99847, Test size: 8532
Split 5: Train size: 108379, Test size: 8575

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...

Saving curated container to sf_permit_time/019d738d-80c6-71a6-99f0-e3e0955ce2d0

019d738d-80c6-71a6-99f0-e3e0955ce2d0
1f766752fbab7d592f90edb006afbeb17a39eb0c5cb06d66777968c4d495750c