### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="mic",
    dataset_year="2020",
    domain_str="medical & healthcare",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://archive.ics.uci.edu/dataset/579/myocardial+infarction+complications",
    download_description="""
We download the data from the UCI repository and uzip it to a predefined folder.

mkdir -p local-data-warehouse/mic/ && wget -P local-data-warehouse/mic/ https://archive.ics.uci.edu/static/public/579/myocardial+infarction+complications.zip && unzip local-data-warehouse/mic/myocardial+infarction+complications.zip -d local-data-warehouse/mic/ && rm local-data-warehouse/mic/myocardial+infarction+complications.zip
""",

# References
academic_reference_bibtex="""@article{golovenkin2020trajectories,
  title={Trajectories, bifurcations, and pseudo-time in large clinical datasets: applications to myocardial infarction and diabetes data},
  author={Golovenkin, Sergey E and Bac, Jonathan and Chervov, Alexander and Mirkes, Evgeny M and Orlova, Yuliya V and Barillot, Emmanuel and Gorban, Alexander N and Zinovyev, Andrei},
  journal={GigaScience},
  volume={9},
  number={11},
  pages={giaa128},
  year={2020},
  publisher={Oxford University Press}
}
""",
    academic_reference_bibtex_key="golovenkin2020trajectories",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
- There are 12 possible targets and four possible time moments to predict the targets for this dataset. We use the categorical target as it summarizes the other possible targets. Furthermore, we use the last possible time point for prediction to utilize all available data.
- We treat "?" as missing values.
- We dropped the "id" column.
- We reversed the ordinal encoding of the target feature.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="LET_IS",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="LET_IS",
)

## Preprocessing

In [2]:
import pandas as pd


df = pd.read_csv(f"{dataset_mold.path}/MI.data", na_values="?")
df.columns = [
    "ID", "AGE", "SEX", "INF_ANAM", "STENOK_AN", "FK_STENOK", "IBS_POST", "IBS_NASL", "GB", "SIM_GIPERT", "DLIT_AG", "ZSN_A", "nr_11", "nr_01", "nr_02", "nr_03", "nr_04", "nr_07", "nr_08", "np_01", "np_04", "np_05", "np_07", "np_08", "np_09", "np_10", "endocr_01", "endocr_02", "endocr_03", "zab_leg_01", "zab_leg_02", "zab_leg_03", "zab_leg_04", "zab_leg_06", "S_AD_KBRIG", "D_AD_KBRIG", "S_AD_ORIT", "D_AD_ORIT", "O_L_POST", "K_SH_POST", "MP_TP_POST", "SVT_POST", "GT_POST", "FIB_G_POST", "ant_im", "lat_im", "inf_im", "post_im", "IM_PG_P", "ritm_ecg_p_01", "ritm_ecg_p_02", "ritm_ecg_p_04", "ritm_ecg_p_06", "ritm_ecg_p_07", "ritm_ecg_p_08", "n_r_ecg_p_01", "n_r_ecg_p_02", "n_r_ecg_p_03", "n_r_ecg_p_04", "n_r_ecg_p_05", "n_r_ecg_p_06", "n_r_ecg_p_08", "n_r_ecg_p_09", "n_r_ecg_p_10", "n_p_ecg_p_01", "n_p_ecg_p_03", "n_p_ecg_p_04", "n_p_ecg_p_05", "n_p_ecg_p_06", "n_p_ecg_p_07", "n_p_ecg_p_08", "n_p_ecg_p_09", "n_p_ecg_p_10", "n_p_ecg_p_11", "n_p_ecg_p_12", "fibr_ter_01", "fibr_ter_02", "fibr_ter_03", "fibr_ter_05", "fibr_ter_06", "fibr_ter_07", "fibr_ter_08", "GIPO_K", "K_BLOOD", "GIPER_NA", "NA_BLOOD", "ALT_BLOOD", "AST_BLOOD", "KFK_BLOOD", "L_BLOOD", "ROE", "TIME_B_S", "R_AB_1_n", "R_AB_2_n", "R_AB_3_n", "NA_KB", "NOT_NA_KB", "LID_KB", "NITR_S", "NA_R_1_n", "NA_R_2_n", "NA_R_3_n", "NOT_NA_1_n", "NOT_NA_2_n", "NOT_NA_3_n", "LID_S_n", "B_BLOK_S_n", "ANT_CA_S_n", "GEPAR_S_n", "ASP_S_n", "TIKL_S_n", "TRENT_S_n", "FIBR_PREDS", "PREDS_TAH", "JELUD_TAH", "FIBR_JELUD", "A_V_BLOK", "OTEK_LANC", "RAZRIV", "DRESSLER", "ZSN", "REC_IM", "P_IM_STEN", "LET_IS",
]
df = df.drop(columns=[
    "ID", 'FIBR_PREDS', 'PREDS_TAH', 'JELUD_TAH', 'FIBR_JELUD', 'A_V_BLOK',
    'OTEK_LANC', 'RAZRIV', 'DRESSLER', 'ZSN', 'REC_IM', 'P_IM_STEN'
])

target_feature = "LET_IS"
df[target_feature] = df[target_feature].map(
    {
        1: "cardiogenic_shock",
        0: "alive",
        2: "pulmonary_edema",
        3: "myocardial_rupture",
        4: "progress_congestive_heart_failure",
        5: "thromboembolism",
        6: "asystole",
        7: "ventricular_fibrillation",
    }
)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)


cat_features = [
"SEX","INF_ANAM","STENOK_AN","FK_STENOK","IBS_POST","IBS_NASL","GB","SIM_GIPERT","DLIT_AG","ZSN_A","nr_11","nr_01","nr_02","nr_03","nr_04","nr_07","nr_08","np_01","np_04","np_05","np_07","np_08","np_09","np_10","endocr_01","endocr_02","endocr_03","zab_leg_01","zab_leg_02","zab_leg_03","zab_leg_04","zab_leg_06","O_L_POST","K_SH_POST","MP_TP_POST","SVT_POST","GT_POST","FIB_G_POST","ant_im","lat_im","inf_im","post_im","IM_PG_P","ritm_ecg_p_01","ritm_ecg_p_02","ritm_ecg_p_04","ritm_ecg_p_06","ritm_ecg_p_07","ritm_ecg_p_08","n_r_ecg_p_01","n_r_ecg_p_02","n_r_ecg_p_03","n_r_ecg_p_04","n_r_ecg_p_05","n_r_ecg_p_06","n_r_ecg_p_08","n_r_ecg_p_09","n_r_ecg_p_10","n_p_ecg_p_01","n_p_ecg_p_03","n_p_ecg_p_04","n_p_ecg_p_05","n_p_ecg_p_06","n_p_ecg_p_07","n_p_ecg_p_08","n_p_ecg_p_09","n_p_ecg_p_10","n_p_ecg_p_11","n_p_ecg_p_12","fibr_ter_01","fibr_ter_02","fibr_ter_03","fibr_ter_05","fibr_ter_06","fibr_ter_07","fibr_ter_08","GIPO_K","GIPER_NA","TIME_B_S","R_AB_1_n","R_AB_2_n","R_AB_3_n","NA_KB","NOT_NA_KB","LID_KB","NITR_S","NOT_NA_1_n","LID_S_n","B_BLOK_S_n","ANT_CA_S_n","GEPAR_S_n","ASP_S_n","TIKL_S_n","TRENT_S_n",
    "LET_IS"
]

df[cat_features] = df[cat_features].astype("category")

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 1,699
Columns: 112
Use sampling: False (sample size: 1,699)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['L_BLOOD', 'ALT_BLOOD', 'AGE', 'AST_BLOOD', 'ROE', 'K_BLOOD', 'NA_BLOOD', 'S_AD_ORIT', 'S_AD_KBRIG', 'D_AD_KBRIG']
Rows remaining as candidates after top-10 filter: 8 (of 1,699)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,AGE,SEX,INF_ANAM,STENOK_AN,FK_STENOK,IBS_POST,IBS_NASL,GB,SIM_GIPERT,DLIT_AG,ZSN_A,nr_11,nr_01,nr_02,nr_03,nr_04,nr_07,nr_08,np_01,np_04,np_05,np_07,np_08,np_09,np_10,endocr_01,endocr_02,endocr_03,zab_leg_01,zab_leg_02,zab_leg_03,zab_leg_04,zab_leg_06,S_AD_KBRIG,D_AD_KBRIG,S_AD_ORIT,D_AD_ORIT,O_L_POST,K_SH_POST,MP_TP_POST,SVT_POST,GT_POST,FIB_G_POST,ant_im,lat_im,inf_im,post_im,IM_PG_P,ritm_ecg_p_01,ritm_ecg_p_02,ritm_ecg_p_04,ritm_ecg_p_06,ritm_ecg_p_07,ritm_ecg_p_08,n_r_ecg_p_01,n_r_ecg_p_02,n_r_ecg_p_03,n_r_ecg_p_04,n_r_ecg_p_05,n_r_ecg_p_06,n_r_ecg_p_08,n_r_ecg_p_09,n_r_ecg_p_10,n_p_ecg_p_01,n_p_ecg_p_03,n_p_ecg_p_04,n_p_ecg_p_05,n_p_ecg_p_06,n_p_ecg_p_07,n_p_ecg_p_08,n_p_ecg_p_09,n_p_ecg_p_10,n_p_ecg_p_11,n_p_ecg_p_12,fibr_ter_01,fibr_ter_02,fibr_ter_03,fibr_ter_05,fibr_ter_06,fibr_ter_07,fibr_ter_08,GIPO_K,K_BLOOD,GIPER_NA,NA_BLOOD,ALT_BLOOD,AST_BLOOD,KFK_BLOOD,L_BLOOD,ROE,TIME_B_S,R_AB_1_n,R_AB_2_n,R_AB_3_n,NA_KB,NOT_NA_KB,LID_KB,NITR_S,NA_R_1_n,NA_R_2_n,NA_R_3_n,NOT_NA_1_n,NOT_NA_2_n,NOT_NA_3_n,LID_S_n,B_BLOK_S_n,ANT_CA_S_n,GEPAR_S_n,ASP_S_n,TIKL_S_n,TRENT_S_n,LET_IS
0,55.0,1,1.0,2.0,2.0,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,120.0,70.0,130.0,80.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.6,0.0,132.0,0.30,0.15,NaN,8.9,10.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,alive
1,64.0,0,0.0,4.0,2.0,1.0,NaN,3.0,0.0,7.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.2,0.0,136.0,0.15,0.41,NaN,8.1,5.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,alive
2,78.0,1,1.0,2.0,2.0,1.0,NaN,3.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.23,0.07,NaN,5.6,5.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,alive
3,61.0,1,0.0,0.0,0.0,2.0,NaN,2.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,100.0,70.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.5,7.0,5.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,alive
4,78.0,1,0.0,4.0,2.0,2.0,NaN,2.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,120.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.8,0.0,139.0,0.23,0.15,NaN,6.2,7.0,2.0,1.0,1.0,0.0,NaN,NaN,NaN,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,alive

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,IBS_NASL,category,1627.0,95.76,2.0,"0.0, 1.0"
1,NOT_NA_KB,category,685.0,40.32,2.0,"1.0, 0.0"
2,LID_KB,category,676.0,39.79,2.0,"0.0, 1.0"
3,NA_KB,category,656.0,38.61,2.0,"1.0, 0.0"
4,GIPER_NA,category,375.0,22.07,2.0,"0.0, 1.0"
5,GIPO_K,category,369.0,21.72,2.0,"0.0, 1.0"
6,DLIT_AG,category,248.0,14.60,8.0,"0.0, 7.0, 6.0, 1.0, 5.0, 2.0, 3.0, 4.0"
7,ritm_ecg_p_01,category,152.0,8.95,2.0,"1.0, 0.0"
8,ritm_ecg_p_02,category,152.0,8.95,2.0,"0.0, 1.0"
9,ritm_ecg_p_04,category,152.0,8.95,2.0,"0.0, 1.0"
10,ritm_ecg_p_06,category,152.0,8.95,2.0,"0.0, 1.0"
11,ritm_ecg_p_07,category,152.0,8.95,2.0,"0.0, 1.0"
12,ritm_ecg_p_08,category,152.0,8.95,2.0,"0.0, 1.0"
13,R_AB_3_n,category,128.0,7.53,4.0,"0.0, 1.0, 2.0, 3.0"
14,TIME_B_S,category,126.0,7.42,9.0,"2.0, 9.0, 1.0, 3.0, 6.0, 7.0, 8.0, 5.0, 4.0"
15,n_r_ecg_p_01,category,115.0,6.77,2.0,"0.0, 1.0"
16,n_r_ecg_p_02,category,115.0,6.77,2.0,"0.0, 1.0"
17,n_r_ecg_p_03,category,115.0,6.77,2.0,"0.0, 1.0"
18,n_r_ecg_p_04,category,115.0,6.77,2.0,"0.0, 1.0"
19,n_r_ecg_p_05,category,115.0,6.77,2.0,"0.0, 1.0"
20,n_r_ecg_p_06,category,115.0,6.77,2.0,"0.0, 1.0"
21,n_r_ecg_p_08,category,115.0,6.77,2.0,"0.0, 1.0"
22,n_r_ecg_p_09,category,115.0,6.77,2.0,"0.0, 1.0"
23,n_r_ecg_p_10,category,115.0,6.77,2.0,"0.0, 1.0"
24,n_p_ecg_p_01,category,115.0,6.77,2.0,"0.0, 1.0"
25,n_p_ecg_p_03,category,115.0,6.77,2.0,"0.0, 1.0"
26,n_p_ecg_p_04,category,115.0,6.77,2.0,"0.0, 1.0"
27,n_p_ecg_p_05,category,115.0,6.77,2.0,"0.0, 1.0"
28,n_p_ecg_p_06,category,115.0,6.77,2.0,"0.0, 1.0"
29,n_p_ecg_p_07,category,115.0,6.77,2.0,"0.0, 1.0"
30,n_p_ecg_p_08,category,115.0,6.77,2.0,"0.0, 1.0"
31,n_p_ecg_p_09,category,115.0,6.77,2.0,"0.0, 1.0"
32,n_p_ecg_p_10,category,115.0,6.77,2.0,"0.0, 1.0"
33,n_p_ecg_p_11,category,115.0,6.77,2.0,"0.0, 1.0"
34,n_p_ecg_p_12,category,115.0,6.77,2.0,"0.0, 1.0"
35,R_AB_2_n,category,108.0,6.36,4.0,"0.0, 1.0, 2.0, 3.0"
36,STENOK_AN,category,106.0,6.24,7.0,"0.0, 6.0, 1.0, 2.0, 5.0, 3.0, 4.0"
37,ant_im,category,83.0,4.89,5.0,"0.0, 4.0, 1.0, 2.0, 3.0"
38,lat_im,category,80.0,4.71,5.0,"1.0, 0.0, 2.0, 3.0, 4.0"
39,inf_im,category,80.0,4.71,5.0,"0.0, 1.0, 2.0, 4.0, 3.0"
40,FK_STENOK,category,73.0,4.30,5.0,"2.0, 0.0, 3.0, 1.0, 4.0"
41,post_im,category,72.0,4.24,5.0,"0.0, 1.0, 2.0, 3.0, 4.0"
42,ZSN_A,category,54.0,3.18,5.0,"0.0, 1.0, 3.0, 2.0, 4.0"
43,IBS_POST,category,51.0,3.00,3.0,"2.0, 1.0, 0.0"
44,nr_11,category,21.0,1.24,2.0,"0.0, 1.0"
45,nr_01,category,21.0,1.24,2.0,"0.0, 1.0"
46,nr_02,category,21.0,1.24,2.0,"0.0, 1.0"
47,nr_03,category,21.0,1.24,2.0,"0.0, 1.0"
48,nr_04,category,21.0,1.24,2.0,"0.0, 1.0"
49,nr_07,category,21.0,1.24,2.0,"0.0, 1.0"
50,nr_08,category,21.0,1.24,2.0,"0.0, 1.0"
51,np_01,category,18.0,1.06,2.0,"0.0, 1.0"
52,np_04,category,18.0,1.06,2.0,"0.0, 1.0"
53,np_05,category,18.0,1.06,2.0,"0.0, 1.0"
54,np_07,category,18.0,1.06,2.0,"0.0, 1.0"
55,np_08,category,18.0,1.06,2.0,"0.0, 1.0"
56,np_09,category,18.0,1.06,2.0,"0.0, 1.0"
57,np_10,category,18.0,1.06,2.0,"0.0, 1.0"
58,GEPAR_S_n,category,17.0,1.00,2.0,"1.0, 0.0"
59,ASP_S_n,category,17.0,1.00,2.0,"1.0, 0.0"
60,R_AB_1_n,category,16.0,0.94,4.0,"0.0, 1.0, 2.0, 3.0"
61,TIKL_S_n,category,16.0,0.94,2.0,"0.0, 1.0"
62,TRENT_S_n,category,16.0,0.94,2.0,"0.0, 1.0"
63,K_SH_POST,category,15.0,0.88,2.0,"0.0, 1.0"
64,MP_TP_POST,category,14.0,0.82,2.0,"0.0, 1.0"
65,ANT_CA_S_n,category,13.0,0.77,2.0,"1.0, 0.0"
66,O_L_POST,category,12.0,0.71,2.0,"0.0, 1.0"
67,SVT_POST,category,12.0,0.71,2.0,"0.0, 1.0"
68,GT_POST,category,12.0,0.71,2.0,"0.0, 1.0"
69,FIB_G_POST,category,12.0,0.71,2.0,"0.0, 1.0"
70,endocr_01,category,11.0,0.65,2.0,"0.0, 1.0"
71,B_BLOK_S_n,category,11.0,0.65,2.0,"0.0, 1.0"
72,endocr_02,category,10.0,0.59,2.0,"0.0, 1.0"
73,endocr_03,category,10.0,0.59,2.0,"0.0, 1.0"
74,fibr_ter_01,category,10.0,0.59,2.0,"0.0, 1.0"
75,fibr_ter_02,category,10.0,0.59,2.0,"0.0, 1.0"
76,fibr_ter_03,category,10.0,0.59,2.0,"0.0, 1.0"
77,fibr_ter_05,category,10.0,0.59,2.0,"0.0, 1.0"
78,fibr_ter_06,category,10.0,0.59,2.0,"0.0, 1.0"
79,fibr_ter_07,category,10.0,0.59,2.0,"0.0, 1.0"
80,fibr_ter_08,category,10.0,0.59,2.0,"0.0, 1.0"
81,NOT_NA_1_n,category,10.0,0.59,5.0,"0.0, 1.0, 2.0, 3.0, 4.0"
82,LID_S_n,category,10.0,0.59,2.0,"0.0, 1.0"
83,GB,category,9.0,0.53,4.0,"2.0, 0.0, 3.0, 1.0"
84,NITR_S,category,9.0,0.53,2.0,"0.0, 1.0"
85,SIM_GIPERT,category,8.0,0.47,2.0,"0.0, 1.0"
86,zab_leg_01,category,7.0,0.41,2.0,"0.0, 1.0"
87,zab_leg_02,category,7.0,0.41,2.0,"0.0, 1.0"
88,zab_leg_03,category,7.0,0.41,2.0,"0.0, 1.0"
89,zab_leg_04,category,7.0,0.41,2.0,"0.0, 1.0"
90,zab_leg_06,category,7.0,0.41,2.0,"0.0, 1.0"
91,INF_ANAM,category,4.0,0.24,4.0,"0.0, 1.0, 2.0, 3.0"
92,IM_PG_P,category,1.0,0.06,2.0,"0.0, 1.0"
93,SEX,category,0.0,0.00,2.0,"1, 0"
94,LET_IS,category,0.0,0.00,8.0,"alive, cardiogenic_shock, myocardial_rupture, asystole, ventricular_fibrillation, progress_congestive_heart_failure, pulmonary_edema, thromboembolism"
95,KFK_BLOOD,float64,1695.0,99.76,4.0,"1.4, 1.8, 3.6, 1.2"
96,S_AD_KBRIG,float64,1075.0,63.27,30.0,"140.0, 130.0, 160.0, 120.0, 110.0, 150.0, 170.0, 180.0, 100.0, 90.0"
97,D_AD_KBRIG,float64,1075.0,63.27,21.0,"80.0, 90.0, 100.0, 70.0, 60.0, 120.0, 110.0, 40.0, 0.0, 50.0"
98,NA_BLOOD,float64,375.0,22.07,40.0,"136.0, 140.0, 130.0, 133.0, 138.0, 143.0, 146.0, 134.0, 132.0, 139.0"
99,K_BLOOD,float64,371.0,21.84,51.0,"4.0, 3.8, 4.2, 3.9, 3.5, 4.1, 4.5, 4.3, 3.6, 3.7"
100,AST_BLOOD,float64,284.0,16.72,58.0,"0.15, 0.22, 0.07, 0.3, 0.11, 0.18, 0.37, 0.45, 0.26, 0.52"
101,ALT_BLOOD,float64,283.0,16.66,69.0,"0.15, 0.3, 0.45, 0.23, 0.38, 0.61, 0.75, 0.52, 0.9, 0.68"
102,S_AD_ORIT,float64,267.0,15.72,32.0,"130.0, 120.0, 140.0, 160.0, 110.0, 150.0, 180.0, 100.0, 170.0, 90.0"
103,D_AD_ORIT,float64,267.0,15.72,20.0,"80.0, 90.0, 100.0, 70.0, 60.0, 110.0, 40.0, 120.0, 0.0, 50.0"
104,ROE,float64,203.0,11.95,58.0,"5.0, 3.0, 10.0, 4.0, 7.0, 8.0, 6.0, 12.0, 15.0, 20.0"
105,NA_R_3_n,float64,131.0,7.71,3.0,"0.0, 1.0, 2.0"
106,NOT_NA_3_n,float64,131.0,7.71,3.0,"0.0, 1.0, 2.0"
107,L_BLOOD,float64,125.0,7.36,174.0,"6.9, 7.0, 6.8, 7.4, 8.0, 7.2, 9.0, 7.7, 6.0, 5.0"
108,NOT_NA_2_n,float64,110.0,6.47,4.0,"0.0, 1.0, 2.0, 3.0"
109,NA_R_2_n,float64,108.0,6.36,4.0,"0.0, 1.0, 2.0, 3.0"
110,AGE,float64,8.0,0.47,62.0,"63.0, 65.0, 62.0, 64.0, 70.0, 52.0, 61.0, 66.0, 55.0, 57.0"
111,NA_R_1_n,float64,5.0,0.29,5.0,"0.0, 1.0, 2.0, 3.0, 4.0"

In [6]:
# Numeric Feature Statistics
numeric_stats

             count        mean        std     min     max
AGE         1691.0   61.848019  11.257238   26.00   92.00
S_AD_KBRIG   624.0  136.907051  34.997835    0.00  260.00
D_AD_KBRIG   624.0   81.394231  19.745045    0.00  190.00
S_AD_ORIT   1432.0  134.556564  31.336338    0.00  260.00
D_AD_ORIT   1432.0   82.737430  18.321785    0.00  190.00
K_BLOOD     1328.0    4.191039   0.754231    2.30    8.20
NA_BLOOD    1324.0  136.549849   6.514459  117.00  169.00
ALT_BLOOD   1416.0    0.481455   0.387261    0.03    3.00
AST_BLOOD   1415.0    0.263717   0.201802    0.04    2.15
KFK_BLOOD      4.0    2.000000   1.095445    1.20    3.60
L_BLOOD     1574.0    8.783412   3.401580    2.00   27.90
ROE         1496.0   13.443182  11.299900    1.00  140.00
NA_R_1_n    1694.0    0.485242   0.779663    0.00    4.00
NA_R_2_n    1591.0    0.094280   0.356307    0.00    3.00
NA_R_3_n    1568.0    0.058673   0.275113    0.00    2.00
NOT_NA_2_n  1589.0    0.113279   0.399630    0.00    3.00
NOT_NA_3_n  1568.0    0.084821   0.355213    0.00    2.00

In [7]:
# Categorical Feature Statistics
cat_stats

                                       value  count    pct
column        rank
ANT_CA_S_n    1                          1.0   1125  66.22
              2                          0.0    561  33.02
              3                         <NA>     13   0.77
ASP_S_n       1                          1.0   1251  73.63
              2                          0.0    431  25.37
              3                         <NA>     17   1.00
B_BLOK_S_n    1                          0.0   1473  86.70
              2                          1.0    215  12.65
              3                         <NA>     11   0.65
DLIT_AG       1                          0.0    551  32.43
              2                          7.0    431  25.37
              3                         <NA>    248  14.60
              4                          6.0    165   9.71
              5                          1.0     93   5.47
FIB_G_POST    1                          0.0   1672  98.41
              2                          1.0     15   0.88
              3                         <NA>     12   0.71
FK_STENOK     1                          2.0    854  50.26
              2                          0.0    661  38.91
              3                         <NA>     73   4.30
              4                          3.0     54   3.18
              5                          1.0     46   2.71
GB            1                          2.0    880  51.80
              2                          0.0    605  35.61
              3                          3.0    194  11.42
              4                          1.0     11   0.65
              5                         <NA>      9   0.53
GEPAR_S_n     1                          1.0   1202  70.75
              2                          0.0    480  28.25
              3                         <NA>     17   1.00
GIPER_NA      1                          0.0   1294  76.16
              2                         <NA>    375  22.07
              3                          1.0     30   1.77
GIPO_K        1                          0.0    796  46.85
              2                          1.0    534  31.43
              3                         <NA>    369  21.72
GT_POST       1                          0.0   1679  98.82
              2                         <NA>     12   0.71
              3                          1.0      8   0.47
IBS_NASL      1                         <NA>   1627  95.76
              2                          0.0     45   2.65
              3                          1.0     27   1.59
IBS_POST      1                          2.0    682  40.14
              2                          1.0    548  32.25
              3                          0.0    418  24.60
              4                         <NA>     51   3.00
IM_PG_P       1                          0.0   1648  97.00
              2                          1.0     50   2.94
              3                         <NA>      1   0.06
INF_ANAM      1                          0.0   1060  62.39
              2                          1.0    410  24.13
              3                          2.0    146   8.59
              4                          3.0     79   4.65
              5                         <NA>      4   0.24
K_SH_POST     1                          0.0   1638  96.41
              2                          1.0     46   2.71
              3                         <NA>     15   0.88
LET_IS        1                        alive   1428  84.05
              2            cardiogenic_shock    110   6.47
              3           myocardial_rupture     54   3.18
              4                     asystole     27   1.59
              5     ventricular_fibrillation     27   1.59
LID_KB        1                         <NA>    676  39.79
              2                          0.0    627  36.90
              3                          1.0    396  23.31
LID_S_n       1                          0.0   1211  71.28
              2                          1.0    478  28.13
              3                         <NA>     10   0.59
MP_TP_POST    1                          0.0   1571  92.47
              2                          1.0    114   6.71
              3                         <NA>     14   0.82
NA_KB         1                         <NA>    656  38.61
              2                          1.0    618  36.37
              3                          0.0    425  25.01
NITR_S        1                          0.0   1495  87.99
              2                          1.0    195  11.48
              3                         <NA>      9   0.53
NOT_NA_1_n    1                          0.0   1236  72.75
              2                          1.0    376  22.13
              3                          2.0     53   3.12
              4                          3.0     17   1.00
              5                         <NA>     10   0.59
NOT_NA_KB     1                          1.0    701  41.26
              2                         <NA>    685  40.32
              3                          0.0    313  18.42
O_L_POST      1                          0.0   1577  92.82
              2                          1.0    110   6.47
              3                         <NA>     12   0.71
R_AB_1_n      1                          0.0   1281  75.40
              2                          1.0    298  17.54
              3                          2.0     78   4.59
              4                          3.0     26   1.53
              5                         <NA>     16   0.94
R_AB_2_n      1                          0.0   1413  83.17
              2                          1.0    133   7.83
              3                         <NA>    108   6.36
              4                          2.0     44   2.59
              5                          3.0      1   0.06
R_AB_3_n      1                          0.0   1469  86.46
              2                         <NA>    128   7.53
              3                          1.0     85   5.00
              4                          2.0     15   0.88
              5                          3.0      2   0.12
SEX           1                            1   1064  62.63
              2                            0    635  37.37
SIM_GIPERT    1                          0.0   1634  96.17
              2                          1.0     57   3.35
              3                         <NA>      8   0.47
STENOK_AN     1                          0.0    661  38.91
              2                          6.0    332  19.54
              3                          1.0    145   8.53
              4                          2.0    137   8.06
              5                          5.0    125   7.36
SVT_POST      1                          0.0   1679  98.82
              2                         <NA>     12   0.71
              3                          1.0      8   0.47
TIKL_S_n      1                          0.0   1653  97.29
              2                          1.0     30   1.77
              3                         <NA>     16   0.94
TIME_B_S      1                          2.0    360  21.19
              2                          9.0    269  15.83
              3                          1.0    198  11.65
              4                          3.0    175  10.30
              5                          6.0    151   8.89
TRENT_S_n     1                          0.0   1342  78.99
              2                          1.0    341  20.07
              3                         <NA>     16   0.94
ZSN_A         1                          0.0   1467  86.34
              2                          1.0    103   6.06
              3                         <NA>     54   3.18
              4                          3.0     29   1.71
              5                          2.0     27   1.59
ant_im        1                          0.0    660  38.85
              2                          4.0    492  28.96
              3                          1.0    391  23.01
              4                         <NA>     83   4.89
              5                          2.0     39   2.30
endocr_01     1                          0.0   1460  85.93
              2                          1.0    228  13.42
              3                         <NA>     11   0.65
endocr_02     1                          0.0   1647  96.94
              2                          1.0     42   2.47
              3                         <NA>     10   0.59
endocr_03     1                          0.0   1676  98.65
              2                          1.0     13   0.77
              3                         <NA>     10   0.59
fibr_ter_01   1                          0.0   1676  98.65
              2                          1.0     13   0.77
              3                         <NA>     10   0.59
fibr_ter_02   1                          0.0   1673  98.47
              2                          1.0     16   0.94
              3                         <NA>     10   0.59
fibr_ter_03   1                          0.0   1621  95.41
              2                          1.0     68   4.00
              3                         <NA>     10   0.59
fibr_ter_05   1                          0.0   1685  99.18
              2                         <NA>     10   0.59
              3                          1.0      4   0.24
fibr_ter_06   1                          0.0   1680  98.88
              2                         <NA>     10   0.59
              3                          1.0      9   0.53
fibr_ter_07   1                          0.0   1683  99.06
              2                         <NA>     10   0.59
              3                          1.0      6   0.35
fibr_ter_08   1                          0.0   1687  99.29
              2                         <NA>     10   0.59
              3                          1.0      2   0.12
inf_im        1                          0.0    936  55.09
              2                          1.0    195  11.48
              3                          2.0    191  11.24
              4                          4.0    176  10.36
              5                          3.0    121   7.12
lat_im        1                          1.0    838  49.32
              2                          0.0    575  33.84
              3                          2.0     97   5.71
              4                         <NA>     80   4.71
              5                          3.0     72   4.24
n_p_ecg_p_01  1                          0.0   1582  93.11
              2                         <NA>    115   6.77
              3                          1.0      2   0.12
n_p_ecg_p_03  1                          0.0   1552  91.35
              2                         <NA>    115   6.77
              3                          1.0     32   1.88
n_p_ecg_p_04  1                          0.0   1579  92.94
              2                         <NA>    115   6.77
              3                          1.0      5   0.29
n_p_ecg_p_05  1                          0.0   1582  93.11
              2                         <NA>    115   6.77
              3                          1.0      2   0.12
n_p_ecg_p_06  1                          0.0   1557  91.64
              2                         <NA>    115   6.77
              3                          1.0     27   1.59
n_p_ecg_p_07  1                          0.0   1482  87.23
              2                         <NA>    115   6.77
              3                          1.0    102   6.00
n_p_ecg_p_08  1                          0.0   1578  92.88
              2                         <NA>    115   6.77
              3                          1.0      6   0.35
n_p_ecg_p_09  1                          0.0   1574  92.64
              2                         <NA>    115   6.77
              3                          1.0     10   0.59
n_p_ecg_p_10  1                          0.0   1550  91.23
              2                         <NA>    115   6.77
              3                          1.0     34   2.00
n_p_ecg_p_11  1                          0.0   1556  91.58
              2                         <NA>    115   6.77
              3                          1.0     28   1.65
n_p_ecg_p_12  1                          0.0   1506  88.64
              2                         <NA>    115   6.77
              3                          1.0     78   4.59
n_r_ecg_p_01  1                          0.0   1526  89.82
              2                         <NA>    115   6.77
              3                          1.0     58   3.41
n_r_ecg_p_02  1                          0.0   1576  92.76
              2                         <NA>    115   6.77
              3                          1.0      8   0.47
n_r_ecg_p_03  1                          0.0   1380  81.22
              2                          1.0    204  12.01
              3                         <NA>    115   6.77
n_r_ecg_p_04  1                          0.0   1515  89.17
              2                         <NA>    115   6.77
              3                          1.0     69   4.06
n_r_ecg_p_05  1                          0.0   1515  89.17
              2                         <NA>    115   6.77
              3                          1.0     69   4.06
n_r_ecg_p_06  1                          0.0   1552  91.35
              2                         <NA>    115   6.77
              3                          1.0     32   1.88
n_r_ecg_p_08  1                          0.0   1580  93.00
              2                         <NA>    115   6.77
              3                          1.0      4   0.24
n_r_ecg_p_09  1                          0.0   1582  93.11
              2                         <NA>    115   6.77
              3                          1.0      2   0.12
n_r_ecg_p_10  1                          0.0   1582  93.11
              2                         <NA>    115   6.77
              3                          1.0      2   0.12
np_01         1                          0.0   1679  98.82
              2                         <NA>     18   1.06
              3                          1.0      2   0.12
np_04         1                          0.0   1678  98.76
              2                         <NA>     18   1.06
              3                          1.0      3   0.18
np_05         1                          0.0   1670  98.29
              2                         <NA>     18   1.06
              3                          1.0     11   0.65
np_07         1                          0.0   1680  98.88
              2                         <NA>     18   1.06
              3                          1.0      1   0.06
np_08         1                          0.0   1675  98.59
              2                         <NA>     18   1.06
              3                          1.0      6   0.35
np_09         1                          0.0   1679  98.82
              2                         <NA>     18   1.06
              3                          1.0      2   0.12
np_10         1                          0.0   1678  98.76
              2                         <NA>     18   1.06
              3                          1.0      3   0.18
nr_01         1                          0.0   1674  98.53
              2                         <NA>     21   1.24
              3                          1.0      4   0.24
nr_02         1                          0.0   1659  97.65
              2                         <NA>     21   1.24
              3                          1.0     19   1.12
nr_03         1                          0.0   1643  96.70
              2                          1.0     35   2.06
              3                         <NA>     21   1.24
nr_04         1                          0.0   1649  97.06
              2                          1.0     29   1.71
              3                         <NA>     21   1.24
nr_07         1                          0.0   1677  98.71
              2                         <NA>     21   1.24
              3                          1.0      1   0.06
nr_08         1                          0.0   1674  98.53
              2                         <NA>     21   1.24
              3                          1.0      4   0.24
nr_11         1                          0.0   1636  96.29
              2                          1.0     42   2.47
              3                         <NA>     21   1.24
post_im       1                          0.0   1369  80.58
              2                          1.0    157   9.24
              3                         <NA>     72   4.24
              4                          2.0     52   3.06
              5                          3.0     35   2.06
ritm_ecg_p_01 1                          1.0   1029  60.57
              2                          0.0    518  30.49
              3                         <NA>    152   8.95
ritm_ecg_p_02 1                          0.0   1452  85.46
              2                         <NA>    152   8.95
              3                          1.0     95   5.59
ritm_ecg_p_04 1                          0.0   1524  89.70
              2                         <NA>    152   8.95
              3                          1.0     23   1.35
ritm_ecg_p_06 1                          0.0   1546  90.99
              2                         <NA>    152   8.95
              3                          1.0      1   0.06
ritm_ecg_p_07 1                          0.0   1195  70.34
              2                          1.0    352  20.72
              3                         <NA>    152   8.95
ritm_ecg_p_08 1                          0.0   1501  88.35
              2                         <NA>    152   8.95
              3                          1.0     46   2.71
zab_leg_01    1                          0.0   1558  91.70
              2                          1.0    134   7.89
              3                         <NA>      7   0.41
zab_leg_02    1                          0.0   1571  92.47
              2                          1.0    121   7.12
              3                         <NA>      7   0.41
zab_leg_03    1                          0.0   1655  97.41
              2                          1.0     37   2.18
              3                         <NA>      7   0.41
zab_leg_04    1                          0.0   1683  99.06
              2                          1.0      9   0.53
              3                         <NA>      7   0.41
zab_leg_06    1                          0.0   1670  98.29
              2                          1.0     22   1.29
              3                         <NA>      7   0.41

In [8]:
# Target Distribution
target_df

                                   count    pct
LET_IS
alive                               1428  84.05
cardiogenic_shock                    110   6.47
myocardial_rupture                    54   3.18
asystole                              27   1.59
ventricular_fibrillation              27   1.59
progress_congestive_heart_failure     23   1.35
pulmonary_edema                       18   1.06
thromboembolism                       12   0.71

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=10, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to mic/019d5ce5-2c20-7057-8545-8e291f3bd5e2
019d5ce5-2c20-7057-8545-8e291f3bd5e2
b2153a8bd5e25e79eb720fdb0231245825e38a8857da6161c09c2bdee83dcc42