### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="sat11_hand_algo_runtime_iid",
    version_from_unique_name="sat11_hand_algo_runtime",
    version_comment="IID outer splits for the musk dataset",
    # -- Rest as before
    dataset_year="2011",
    domain_str="technology & internet",
    # Data Source
    dataset_source="ASlib",
    original_dataset_source_download_link="https://github.com/coseal/aslib_data/tree/master/SAT11-HAND",
    download_description="""
wget https://raw.githubusercontent.com/coseal/aslib_data/refs/heads/master/SAT11-HAND-ALGO/feature_values.arff \
&& wget https://raw.githubusercontent.com/coseal/aslib_data/refs/heads/master/SAT11-HAND-ALGO/algorithm_feature_values.arff \
&& wget https://raw.githubusercontent.com/coseal/aslib_data/refs/heads/master/SAT11-HAND-ALGO/algorithm_runs.arff \
&& mkdir -p local-data-warehouse/sat11_hand_algo_runtime \
&& mv feature_values.arff algorithm_feature_values.arff algorithm_runs.arff local-data-warehouse/sat11_hand_algo_runtime/
""",
    # References
    academic_reference_bibtex="""@inproceedings{xu-sat12a,
  author    = {L. Xu and F. Hutter and H. Hoos and K. Leyton-Brown},
  title     = {Evaluating Component Solver Contributions to Portfolio-Based Algorithm Selectors},
  pages     = {228-241},
  crossref  = {sat12}
}
@Proceedings{sat12,
  editor =         {A. Cimatti and R. Sebastiani},
  title =         {Proceedings of the Fifteenth International Conference on Theory and Applications of Satisfiability Testing (SAT'12)},
  booktitle = {Proceedings of the Fifteenth International Conference on Theory and Applications of Satisfiability Testing (SAT'12)},
  publisher =         springer,
  series =         lncs,
  volume =         7317,
  year =         2012
}
@article{bischl_aslib_2016,
	title = {{ASlib}: {A} {Benchmark} {Library} for {Algorithm} {Selection}},
	number = {237},
	journal = {Artificial Intelligence Journal (AIJ)},
	author = {Bischl, Bernd and Kerschke, Pascal and Kotthoff, Lars and Lindauer, Marius and Malitsky, Yuri and Fréchette, Alexandre and Hoos, Holger H. and Hutter, Frank and Leyton-Brown, Kevin and Tierney, Kevin and Vanschoren, Joaquin},
	year = {2016},
	pages = {41--58}
}
""",
    academic_reference_bibtex_key="xu-sat12a,sat12,bischl_aslib_2016",
    license="GPLv3",
    data_tags=["Non-IID", "Grouped"],
    curation_comments="""
We get the data from ASlib and merge them into one file.

- Algorithm selection can be solved with many methods (pairwise classification, hierarchical regression, multi-label, ...). We follow the concept from Pulatov et al. (https://proceedings.mlr.press/v188/pulatov22a.html) and learn one single, unified regression model that goes from (instance_features, algorithm_features) -> runtime.
- The description says 'If features are "?", the instance was solved during feature computation.' but from the status file we can see that no task was presovled. So it is unclear what this is referring to. We believe that in all cases we have nan values for features, it is a case of the feature running into a memout, timeout, or crash as stated by the description.
- This regression task is special as it contains censored regression values (capped to some max value) and the model needs to learn this.
- We log scale the target.
- We drop duplicated columns and remove features that leak the target or are not relevant for the predictive task.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="runtime",
    problem_type="regression",
    objective_metric_name="rmse", # better to score with RMSE with cut-off, or like PAR10?
)

## Preprocessing

In [2]:
import arff
import pandas as pd
import uuid
import numpy as np


def load_arff(path) -> pd.DataFrame:
    with open(path, encoding="utf-8") as f:
        data = arff.load(f)
    df = pd.DataFrame(data["data"], columns=[a[0] for a in data["attributes"]])
    return df


df_features = load_arff(dataset_mold.path / "feature_values.arff")
print("feature_values shape:", df_features.shape)
df_algo_features = load_arff(dataset_mold.path / "algorithm_feature_values.arff")
print("algorithm_feature_values shape:", df_algo_features.shape)
df_algo_runs = load_arff(dataset_mold.path / "algorithm_runs.arff")
print("algorithm_runs shape:", df_algo_runs.shape)

# Drop algorithms that for which we do not have features
df_algo_runs = df_algo_runs[df_algo_runs["algorithm"].isin(df_algo_features["algorithm"].unique())]

# Merge
df = df_algo_runs.merge(df_features, on="instance_id", how="left").merge(
    df_algo_features, on="algorithm", how="left"
)
print("Merged data shape:", df.shape)

# Sanitize ID
# Create mapping: molecule -> random string id
mapping = {val: uuid.uuid4().hex[:12] for val in df["instance_id"].unique()}
df["instance_id"] = df["instance_id"].map(mapping)
df["instance_id"] = df["instance_id"].astype("category")

# Drop features
df = df.drop(columns=[
    # Data has no repetitions
    "repetition_x", "repetition_y", "repetition",
    # We want to only rely on algorithm meta features not names.
    "algorithm",
    # Leaks target
    "runstatus",
    # Duplicated columns
    "clustering_min", "edge_ta","edge_to","edge_tl","edge_da","edge_do","edge_dl","edge_as","edge_aa","edge_ao","edge_al","edge_ot","edge_oa","edge_ol","edge_lt","edge_la","edge_ll","degree_min","path_min","VCG_VAR_mean","edge_at",
])

df["runtime"] = np.log(df["runtime"])

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

feature_values shape: (296, 117)
algorithm_feature_values shape: (11, 77)
algorithm_runs shape: (4440, 5)
Merged data shape: (2960, 197)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

Warning: Found 3 constant feature(s) with 1 or fewer unique values (including NaNs): ['POSNEG_RATIO_CLAUSE_max', 'UNARY', 'clustering_max']

#### Dataset Overview
Rows: 2,960
Columns: 171
Use sampling: False (sample size: 2,960)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['instance_id', 'gsat_FirstLocalMinStep_Mean', 'gsat_BestAvgImprovement_Mean', 'saps_BestAvgImprovement_Mean', 'saps_FirstLocalMinStep_Mean', 'saps_BestSolution_Mean', 'gsat_BestAvgImprovement_CoeffVariance', 'lobjois_mean_depth_over_vars', 'saps_BestSolution_CoeffVariance', 'gsat_BestSolution_Mean']
Rows remaining as candidates after top-10 filter: 2,960 (of 2,960)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

/home/lennart_priorlabs_ai/.venvs/tabarena_1503/lib/python3.11/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [4]:
# Sample Rows
df_head

,instance_id,runtime,nvarsOrig,nclausesOrig,nvars,nclauses,reducedVars,reducedClauses,vars_clauses_ratio,POSNEG_RATIO_CLAUSE_mean,POSNEG_RATIO_CLAUSE_coeff_variation,POSNEG_RATIO_CLAUSE_min,POSNEG_RATIO_CLAUSE_max,POSNEG_RATIO_CLAUSE_entropy,VCG_CLAUSE_mean,VCG_CLAUSE_coeff_variation,VCG_CLAUSE_min,VCG_CLAUSE_max,VCG_CLAUSE_entropy,UNARY,BINARYp,TRINARYp,VCG_VAR_coeff_variation,VCG_VAR_min,VCG_VAR_max,VCG_VAR_entropy,POSNEG_RATIO_VAR_mean,POSNEG_RATIO_VAR_stdev,POSNEG_RATIO_VAR_min,POSNEG_RATIO_VAR_max,POSNEG_RATIO_VAR_entropy,HORNY_VAR_mean,HORNY_VAR_coeff_variation,HORNY_VAR_min,HORNY_VAR_max,HORNY_VAR_entropy,horn_clauses_fraction,VG_mean,VG_coeff_variation,VG_min,VG_max,CG_mean,CG_coeff_variation,CG_min,CG_max,CG_entropy,cluster_coeff_mean,cluster_coeff_coeff_variation,cluster_coeff_min,cluster_coeff_max,cluster_coeff_entropy,DIAMETER_mean,DIAMETER_coeff_variation,DIAMETER_min,DIAMETER_max,DIAMETER_entropy,cl_num_mean,cl_num_coeff_variation,cl_num_min,cl_num_max,cl_num_q90,cl_num_q10,cl_num_q75,cl_num_q25,cl_num_q50,cl_size_mean,cl_size_coeff_variation,cl_size_min,cl_size_max,cl_size_q90,cl_size_q10,cl_size_q75,cl_size_q25,cl_size_q50,SP_bias_mean,SP_bias_coeff_variation,SP_bias_min,SP_bias_max,SP_bias_q90,SP_bias_q10,SP_bias_q75,SP_bias_q25,SP_bias_q50,SP_unconstraint_mean,SP_unconstraint_coeff_variation,SP_unconstraint_min,SP_unconstraint_max,SP_unconstraint_q90,SP_unconstraint_q10,SP_unconstraint_q75,SP_unconstraint_q25,SP_unconstraint_q50,saps_BestSolution_Mean,saps_BestSolution_CoeffVariance,saps_FirstLocalMinStep_Mean,saps_FirstLocalMinStep_CoeffVariance,saps_FirstLocalMinStep_Median,saps_FirstLocalMinStep_Q10,saps_FirstLocalMinStep_Q90,saps_BestAvgImprovement_Mean,saps_BestAvgImprovement_CoeffVariance,saps_FirstLocalMinRatio_Mean,saps_FirstLocalMinRatio_CoeffVariance,gsat_BestSolution_Mean,gsat_BestSolution_CoeffVariance,gsat_FirstLocalMinStep_Mean,gsat_FirstLocalMinStep_CoeffVariance,gsat_FirstLocalMinStep_Median,gsat_FirstLocalMinStep_Q10,gsat_FirstLocalMinStep_Q90,gsat_BestAvgImprovement_Mean,gsat_BestAvgImprovement_CoeffVariance,gsat_FirstLocalMinRatio_Mean,gsat_FirstLocalMinRatio_CoeffVariance,lobjois_mean_depth_over_vars,lobjois_log_num_nodes_over_vars,Lines..Average.,Lines..Total.,Size..Average.,Size..Total.,Number.of.files,Cyclomatic..Average.,Cyclomatic..Total.,Max.Indent..Average.,Max.Indent..Total.,nb_nodes,nb_edges,degree_max,degree_mean,degree_variance,degree_entropy,transitivity,clustering_max,clustering_mean,clustering_variance,paths_max,path_mean,path_variance,path_entropy,Stmt,Type,Decl,Attribute,Operator,Literal,edge_ss,edge_st,edge_sd,edge_sa,edge_so,edge_sl,edge_ts,edge_tt,edge_td,edge_ds,edge_dt,edge_dd,edge_ad,edge_os,edge_od,edge_oo,edge_ls,edge_ld,edge_lo,op_short,op_int,op_long,op_long_long,op_float,op_double,op_bit
0,ca47f6221702,4.090067,2754.0,10377.0,969.0,5950.0,1.8421,0.7440,0.1629,0.4874,0.7382,0.0,1.0,1.8292,0.0044,0.9928,0.0021,0.0289,1.7384,0.0,0.2415,0.5521,3.5252,0.0008,0.2471,2.0945,0.2476,0.2429,0.0000,0.9487,2.1954,0.0016,4.0951,0.0002,0.1696,1.6444,0.5526,0.0046,1.9272,0.0010,0.0595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.8874,0.0813,3.0,4.0,0.3519,3144.0000,0.0787,2657.0,3485.0,3485.0,2657.0,3337.0,2993.0,3229.0,16.9642,0.1304,14.9793,21.9515,21.9515,14.9793,18.7361,15.7147,16.0341,0.2752,0.9193,0.0003,0.9609,0.6508,0.0283,0.3792,0.0756,0.2055,0.2727,0.3527,0.0000,0.3874,0.3484,0.0842,0.3322,0.2631,0.3076,14.0239,0.2026,180.9720,0.0506,181.0,170.0,193.0,1.3709,0.2342,0.9208,0.0181,16.3016,0.3787,180.8640,0.0592,181.0,169.0,192.0,0.3977,0.9364,0.9249,0.0204,0.1206,0.4990,12.837907,14969.0,10037.734177,792981.0,79.0,2.720930,2691.0,1.731041,1712.0,4334441.0,4545157.0,32037.0,2.097229,259.670236,1.350620,0.000037,0.5,0.002287,0.000368,72.0,6.518183,11.123855,2.433300,0.513657,0.054792,0.352065,0.010225,0.046191,0.023070,3657.0,15.0,453.0,0.0,574.0,0.0,21.0,770.0,205.0,112.0,112.0,3074.0,93.0,347.0,7.0,65.0,146.0,12.0,56.0,0.0,0.25899,0.17986,0.00288,0.00144,0.00576,0.04604
1,7bed349ffd1e,8.517193,34307.0,708206.0,34307.0,708206.0,0.0000,0.0000,0.0484,1.0000,0.0000,1.0,1.0,0.0000,0.0001,0.0000,0.0001,0.0001,0.0000,0.0,0.0000,0.0000,0.3004,0.0000,0.0004,4.1179,0.0000,0.0000,0.0000,0.0000,0.0000,0.0001,0.3004,0.0000,0.0002,4.1179,0.5000,0.0003,0.2795,0.0000,0.0007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.4783,0.1115,4.0,5.0,0.6922,5.2632,0.6663,1.0,13.0,13.0,1.0,6.0,2.0,5.0,93.6251,0.3792,45.1667,167.0000,159.0000,48.4000,110.1667,62.5000,87.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.2499,0.3436,0.0529,0.4640,0.3833,0.1468,0.3109,0.1814,0.2357,1877.0000,0.0000,6562.0000,0.0000,6562.0,6562.0,6562.0,0.9618,0.0000,0.8715,0.0000,1693.0000,0.1671,6511.5000,0.0014,6511.5,6505.0,6505.0,0.3763,0.6276,0.8584,0.0123,0.3325,0.3361,20.928571,2344.0,8767.200000,87672.0,10.0,5.030928,488.0,2.103093,204.0,34620.0,35661.0,4330.0,2.060139,544.494722,1.310086,0.000014,0.5,0.002829,0.000511,32.0,5.035136,21.758159,1.888720,0.424359,0.044100,0.292746,0.098889,0.086944,0.052962,2742.0,0.0,93.0,0.0,1093.0,0.0,0.0,488.0,251.0,61.0,46.0,2644.0,919.0,749.0,1.0,98.0,194.0,22.0,245.0,0.0,0.74791,0.05292,0.02994,0.00000,0.01671,0.24791
2,2252b2556c86,0.147402,880.0,6174.0,807.0,5781.0,0.0905,0.0680,0.1396,0.3696,0.8892,0.0,1.0,1.0097,0.0049,0.0323,0.0025,0.0062,0.0696,0.0,0.0017,0.0112,0.4176,0.0017,0.0157,3.1250,0.1259,0.0978,0.0000,0.5714,3.1370,0.0015,0.4651,0.0002,0.0054,2.7428,0.3081,0.0022,0.4088,0.0009,0.0067,0.0102,0.2341,0.0021,0.0192,4.0244,0.1766,0.2489,0.0650,0.5842,2.8154,5.1005,0.0589,5.0,6.0,0.3262,1987.2500,0.7371,155.0,3691.0,3691.0,155.0,3683.0,402.0,3047.0,19.2666,0.6940,2.9290,33.3209,33.3209,2.9290,32.4778,3.6169,30.9019,0.2353,0.6484,0.0001,0.7370,0.4498,0.0420,0.3514,0.1122,0.2198,0.0766,0.8625,0.0001,0.3281,0.1859,0.0077,0.1127,0.0238,0.0534,30.0438,0.3913,157.5510,0.0650,158.0,146.0,169.0,0.6928,0.2300,0.8117,0.0467,31.4200,0.1653,157.8730,0.0549,158.0,147.0,169.0,0.2403,0.3504,0.8159,0.0317,0.1170,0.2724,4.712835,5104.0,6089.764706,310578.0,51.0,0.995580,901.0,1.181215,1069.0,113915.0,119055.0,2771.0,2.090243,127.825871,1.319752,0.000105,0.5,0.003041,0.000508,39.0,5.476320,13.606343,2.110430,0.446610,0.039052,0.397553,0.034089,0.051649,0.031048,3143.0,11.0,448.0,1.0,643.0,0.0,8.0,468.0,210.0,77.0,46.0,3690.0,325.0,380.0,7.0,91.0,224.0,25.0,93.0,0.0,0.46191,0.05804,0.01935,0.00363,0.03507,0.07013
3,290654acf82e,-4.074777,168.0,1554.0,126.0,1386.0,0.3333,0.1212,0.0909,1.0000,0.0000,1.0,1.0,0.0000,0.0447,0.6205,0.0159,0.0952,0.8158,0.0,0.0909,0.0909,0.0000,0.0447,0.0447,0.0000,0.0323,0.0000,0.0323,0.0323,0.0000,0.0231,0.0000,0.0231,0.0231,0.0000,0.7727,0.0902,0.0000,0.0902,0.0902,0.1013,0.6655,0.0216,0.2229,0.8158,0.0210,0.7089,0.0065,0.0645,0.8158,2.0000,0.0000,2.0,2.0,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.5993,0.0000,0.5992,0.5993,0.5993,0.5993,0.5993,0.5993,0.5993,0.3528,0.0000,0.3528,0.3528,0.3528,0.3528,0.3528,0.3528,0.3528,0.0000,0.0000,28.5016,0.1569,28.0,23.0,34.0,3.2192,0.1790,1.0000,0.0007,0.0000,0.0000,28.5513,0.1576,28.0,23.0,34.0,3.2254,0.1778,1.0000,0.0006,0.9998,1.0000,20.928571,2344.0,8767.200000,87672.0,10.0,5.030928,488.0,2.103093,204.0,34620.0,35661.0,4330.0,2.060139,544.494722,1.310086,0.000014,0.5,0.002829,0.000511,32.0,5.035136,21.758159,1.888720,0.424359,0.044100,0.292746,0.098889,0.086944,0.052962,2742.0,0.0,93.0,0.0,1093.0,0.0,0.0,488.0,251.0,61.0,46.0,2644.0,919.0,749.0,1.0,98.0,194.0,22.0,245.0,0.0,0.74791,0.05292,0.02994,0.00000,0.01671,0.24791
4,925b6f7e9a41,7.228011,180.0,432.0,180.0,432.0,0.0000,0.0000,0.4167,0.4380,1.0670,0.0,1.0,1.0976,0.0139,0.4472,0.0111,0.0278,0.4506,0.0,0.8333,0.8333,0.0000,0.0139,0.0139,0.0000,0.3333,0.0000,0.3333,0.3333,0.0000,0.0077,0.3222,0.0000,0.0116,1.2514,0.6713,0.0276,0.0192,0.0255,0.0278,0.0154,0.8944,0.0093,0.0463,0.4506,0.3492,0.3252,0.0952,0.4000,0.4506,4.1899,0.0936,4.0,5.0,0.4861,4535.1667,0.0066,4484.0,4579.0,4579.0,4484.0,4553.0,4514.0,4541.0,33.3541,0.0728,29.6164,37.3144,37.3144,29.6164,35.2104,32.0081,33.3253,0.5832,0.0001,0.5831,0.5833,0.5832,0.5831,0.5832,0.5832,0.5832,0.2295,0.0001,0.2294,0.2295,0.2295,0.2295,0.2295,0.2295,0.2295,6.4189,0.2429,46.8352,0.1288,47.0,39.0,55.0,1.1278,0.2039,0.9326,0.0313,3.7080,0.2557,46.8335,0.1282,47.0,39.0,55.0,0.6079,0.3453,0.9030,0.0309,0.6788,0.8349,8.427325,28004.0,13089.165048,1348184.0,103.0,1.636564,4458.0,1.514684,4126.0,2750173.0,2865629.0,12991.0,2.083963,69.981263,1.358274,0.000152,0.5,0.002722,0.000428,33.0,6.908184,10.615592,2.462984,0.568400,0.047438,0.294037,0.009859,0.055561,0.024705,3693.0,0.0,544.0,0.0,690.0,0.0,13.0,662.0,185.0,108.0,95.0,2509.0,101.0,425.0,16.0,81.0,165.0,13.0,79.0,0.0,0.31294,0.19647,0.01294,0.00000,0.00235,0.07647

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,instance_id,category,0.0,0.00,296.0,"feba188676d9, 01026dd24a23, 02033e5b65f1, 04418fe8cd39, 05f4dd3c60df, 0700c43bc4a0, 0799ae2bc566, 0814117290c3, da537bb01692, da9d7a59cea7"
1,CG_mean,float64,1810.0,61.15,106.0,"0.026, 0.0198, 0.0174, 0.0206, 0.001, 0.0139, 0.0046, 0.0202, 0.0176, 0.1013"
2,CG_coeff_variation,float64,1810.0,61.15,105.0,"0.8944, 0.2341, 0.6655, 0.5632, 1.1867, 0.3417, 0.2621, 1.0857, 0.0928, 0.0057"
3,CG_min,float64,1810.0,61.15,89.0,"0.0, 0.0003, 0.0001, 0.0021, 0.006, 0.0012, 0.0135, 0.022, 0.0069, 0.0009"
4,CG_max,float64,1810.0,61.15,112.0,"0.0417, 0.1319, 0.0142, 0.0463, 0.0733, 0.1103, 0.0542, 0.0192, 0.2169, 0.0361"
5,CG_entropy,float64,1810.0,61.15,104.0,"0.4506, 0.8158, 4.0244, 4.2844, 0.3622, 2.5663, 2.5202, 0.3906, 0.3034, 0.0437"
6,cluster_coeff_mean,float64,1810.0,61.15,103.0,"0.3492, 0.1766, 0.1958, 0.0766, 0.1983, 0.4461, 0.0545, 0.4474, 0.1046, 0.302"
7,cluster_coeff_coeff_variation,float64,1810.0,61.15,105.0,"0.3252, 0.2063, 0.2489, 0.485, 0.7089, 0.1655, 0.1565, 0.3199, 0.3095, 0.0676"
8,cluster_coeff_min,float64,1810.0,61.15,84.0,"0.0952, 0.1538, 0.3012, 0.3262, 0.4, 0.0014, 0.0065, 0.0095, 0.0435, 0.0556"
9,cluster_coeff_max,float64,1810.0,61.15,70.0,"0.4, 0.2, 0.5, 0.0952, 0.069, 0.0645, 0.9048, 0.8889, 0.1333, 0.0606"
10,cluster_coeff_entropy,float64,1810.0,61.15,103.0,"0.4506, 0.8158, 2.8154, 3.2728, 0.3622, 2.7953, 2.8759, 0.3906, 0.3034, 0.3072"
11,runtime,float64,0.0,0.00,1046.0,"8.5172, -4.5101, -4.9621, -4.343, -4.8286, -4.7109, -5.8095, -3.2191, -5.2987, -5.1163"
12,nvarsOrig,float64,0.0,0.00,221.0,"945.0, 2400.0, 760.0, 2100.0, 600.0, 2640.0, 870.0, 160.0, 1150.0, 120.0"
13,nclausesOrig,float64,0.0,0.00,255.0,"266431.0, 61409.0, 43649.0, 215164.0, 305320.0, 111739.0, 84314.0, 896.0, 672.0, 936.0"
14,nvars,float64,0.0,0.00,221.0,"900.0, 2325.0, 720.0, 2030.0, 120.0, 2560.0, 1320.0, 360.0, 580.0, 150.0"
15,nclauses,float64,0.0,0.00,282.0,"42889.0, 60464.0, 264031.0, 2416.0, 302680.0, 936.0, 396.0, 7504.0, 1160280.0, 18172.0"
16,reducedVars,float64,0.0,0.00,103.0,"0.0, 0.3333, 0.0345, 0.0323, 0.0556, 0.05, 0.0455, 0.0313, 0.0417, 0.04"
17,reducedClauses,float64,0.0,0.00,142.0,"0.0, 0.0177, 0.0156, 0.0091, 0.012, 0.0118, 0.0202, 0.0049, 0.0083, 0.0124"
18,vars_clauses_ratio,float64,0.0,0.00,213.0,"0.4167, 0.0088, 0.0149, 0.0168, 0.012, 0.0085, 0.015, 0.0026, 0.0096, 0.0116"
19,POSNEG_RATIO_CLAUSE_mean,float64,0.0,0.00,162.0,"1.0, 0.9939, 0.9972, 0.9971, 0.9923, 0.9973, 0.9991, 0.9993, 0.9995, 0.9956"
20,POSNEG_RATIO_CLAUSE_coeff_variation,float64,0.0,0.00,178.0,"0.0, 0.0236, 0.013, 0.0132, 0.0126, 0.5773, 0.0142, 0.0276, 0.005, 0.8453"
21,POSNEG_RATIO_CLAUSE_min,float64,0.0,0.00,34.0,"0.0, 1.0, 0.3333, 0.8, 0.8947, 0.8333, 0.8182, 0.8824, 0.8462, 0.75"
22,POSNEG_RATIO_CLAUSE_max,float64,0.0,0.00,1.0,1.0
23,POSNEG_RATIO_CLAUSE_entropy,float64,0.0,0.00,205.0,"0.0, 0.184, 0.2102, 0.5623, 0.9346, 1.3808, 1.3553, 1.603, 1.1174, 1.617"
24,VCG_CLAUSE_mean,float64,0.0,0.00,168.0,"0.0015, 0.0001, 0.0014, 0.0025, 0.0036, 0.0037, 0.0046, 0.0013, 0.001, 0.0035"
25,VCG_CLAUSE_coeff_variation,float64,0.0,0.00,258.0,"0.0, 0.4472, 1.0759, 1.4728, 1.105, 1.0967, 0.518, 1.1742, 0.5792, 0.016"
26,VCG_CLAUSE_min,float64,0.0,0.00,129.0,"0.0008, 0.0009, 0.0022, 0.001, 0.0028, 0.0013, 0.0001, 0.0023, 0.0015, 0.0079"
27,VCG_CLAUSE_max,float64,0.0,0.00,189.0,"0.1, 0.0433, 0.0486, 0.0909, 0.0667, 0.0833, 0.0258, 0.0714, 0.0952, 0.0262"
28,VCG_CLAUSE_entropy,float64,0.0,0.00,256.0,"0.0, 0.4506, 0.267, 0.8158, 0.0081, 0.3096, 0.1647, 0.2994, 0.6867, 0.3344"
29,UNARY,float64,0.0,0.00,1.0,0.0
30,BINARYp,float64,0.0,0.00,201.0,"0.0, 0.8333, 0.0323, 0.9523, 0.9349, 0.9534, 0.0909, 0.0027, 0.0047, 0.0101"
31,TRINARYp,float64,0.0,0.00,229.0,"0.0, 0.8333, 1.0, 0.9349, 0.0909, 0.9169, 0.9523, 0.9439, 0.9534, 0.0891"
32,VCG_VAR_coeff_variation,float64,0.0,0.00,207.0,"0.0, 0.2615, 0.1671, 0.2483, 0.1887, 0.2614, 0.3004, 0.1947, 0.192, 0.2491"
33,VCG_VAR_min,float64,0.0,0.00,151.0,"0.0001, 0.0, 0.0008, 0.0004, 0.0009, 0.0005, 0.0003, 0.0014, 0.0007, 0.0024"
34,VCG_VAR_max,float64,0.0,0.00,202.0,"0.0021, 0.0203, 0.0055, 0.0026, 0.0013, 0.0045, 0.0031, 0.0029, 0.0025, 0.0035"
35,VCG_VAR_entropy,float64,0.0,0.00,222.0,"0.0, 4.1179, 4.7775, 2.0945, 5.2412, 3.125, 4.8069, 1.6381, 2.0951, 1.1936"
36,POSNEG_RATIO_VAR_mean,float64,0.0,0.00,252.0,"0.0, 0.3333, 0.0323, 0.0345, 0.0526, 0.037, 0.0435, 0.2552, 0.0476, 0.1646"
37,POSNEG_RATIO_VAR_stdev,float64,0.0,0.00,193.0,"0.0, 0.1569, 0.0363, 0.0423, 0.0454, 0.0782, 0.1092, 0.0334, 0.0766, 0.0786"
38,POSNEG_RATIO_VAR_min,float64,0.0,0.00,154.0,"0.0, 0.3333, 0.2, 0.0323, 0.0769, 0.0526, 0.1254, 0.0795, 0.0013, 0.0345"
39,POSNEG_RATIO_VAR_max,float64,0.0,0.00,208.0,"0.3333, 1.0, 0.0, 0.2, 0.0526, 0.0323, 0.037, 0.5, 0.0345, 0.6667"
40,POSNEG_RATIO_VAR_entropy,float64,0.0,0.00,215.0,"0.0, 2.1954, 3.137, 3.5623, 2.9611, 2.8278, 0.4872, 1.7102, 0.6221, 0.6363"
41,HORNY_VAR_mean,float64,0.0,0.00,114.0,"0.0008, 0.0021, 0.0007, 0.0017, 0.0002, 0.0011, 0.0001, 0.0009, 0.0026, 0.0014"
42,HORNY_VAR_coeff_variation,float64,0.0,0.00,229.0,"0.0, 0.3562, 0.3004, 0.1855, 0.3923, 0.2023, 0.1569, 0.3597, 0.3709, 0.1589"
43,HORNY_VAR_min,float64,0.0,0.00,82.0,"0.0, 0.0005, 0.0004, 0.0008, 0.0002, 0.0006, 0.0001, 0.0012, 0.0003, 0.0007"
44,HORNY_VAR_max,float64,0.0,0.00,152.0,"0.0012, 0.0015, 0.0014, 0.0013, 0.0055, 0.0023, 0.0054, 0.0036, 0.0033, 0.0032"
45,HORNY_VAR_entropy,float64,0.0,0.00,239.0,"0.0, 4.1179, 2.9257, 2.7428, 1.2514, 4.9453, 1.6444, 4.2763, 2.0506, 3.1342"
46,horn_clauses_fraction,float64,0.0,0.00,266.0,"0.5, 0.9349, 0.9523, 0.0753, 0.0915, 0.751, 0.0831, 0.9534, 0.9439, 0.9261"
47,VG_mean,float64,0.0,0.00,169.0,"0.0029, 0.0001, 0.0018, 0.0026, 0.0034, 0.008, 0.0048, 0.002, 0.0103, 0.003"
48,VG_coeff_variation,float64,0.0,0.00,201.0,"0.0, 0.0022, 0.0021, 0.0246, 0.0017, 1.1315, 0.2012, 0.0019, 0.2795, 0.1536"
49,VG_min,float64,0.0,0.00,156.0,"0.0001, 0.0009, 0.0, 0.001, 0.0025, 0.0005, 0.0027, 0.0073, 0.0016, 0.0004"
50,VG_max,float64,0.0,0.00,189.0,"0.0029, 0.0042, 0.0027, 0.0031, 0.0116, 0.0007, 0.0026, 0.0047, 0.0064, 0.0114"
51,DIAMETER_mean,float64,0.0,0.00,152.0,"2.0, 3.0, 4.0, 4.4783, 2.1802, 4.1899, 5.1005, 3.8874, 8.2451, 6.2098"
52,DIAMETER_coeff_variation,float64,0.0,0.00,144.0,"0.0, 0.1115, 0.0927, 0.1763, 0.0288, 0.1441, 0.0056, 0.0813, 0.0656, 0.0507"
53,DIAMETER_min,float64,0.0,0.00,12.0,"2.0, 3.0, 4.0, 6.0, 5.0, 8.0, 25.0, 744.0, 90.0, 743.0"
54,DIAMETER_max,float64,0.0,0.00,17.0,"3.0, 2.0, 7.0, 4.0, 6.0, 5.0, 8.0, 14.0, 49.0, 760.0"
55,DIAMETER_entropy,float64,0.0,0.00,146.0,"0.0, 0.6922, 0.0238, 0.4717, 2.6899, 0.3519, 0.0389, 0.3262, 0.4861, 0.4431"
56,cl_num_mean,float64,0.0,0.00,274.0,"0.0, 4241.5, 4870.0, 4900.0, 2768.25, 4026.2222, 2438.6364, 10.1429, 1236.3, 3546.5"
57,cl_num_coeff_variation,float64,0.0,0.00,255.0,"0.0, 0.0191, 0.0066, 0.0094, 0.0092, 0.0026, 0.004, 0.5934, 0.4744, 0.0093"
58,cl_num_min,float64,0.0,0.00,246.0,"0.0, 1.0, 4886.0, 104.0, 3.0, 102.0, 2.0, 58.0, 74.0, 63.0"
59,cl_num_max,float64,0.0,0.00,268.0,"0.0, 4879.0, 171.0, 4330.0, 4636.0, 4471.0, 4202.0, 3848.0, 205.0, 4449.0"
60,cl_num_q90,float64,0.0,0.00,267.0,"0.0, 4879.0, 565.0, 4330.0, 199.0, 4202.0, 4636.0, 4471.0, 290.0, 3848.0"
61,cl_num_q10,float64,0.0,0.00,253.0,"0.0, 4886.0, 3.0, 1.0, 4872.0, 46.0, 74.0, 319.0, 151.0, 66.0"
62,cl_num_q75,float64,0.0,0.00,261.0,"0.0, 2061.0, 3205.0, 751.0, 4272.0, 110.0, 385.0, 4636.0, 664.0, 4879.0"
63,cl_num_q25,float64,0.0,0.00,262.0,"0.0, 4872.0, 4669.0, 594.0, 295.0, 102.0, 291.0, 3690.0, 438.0, 66.0"
64,cl_num_q50,float64,0.0,0.00,266.0,"0.0, 212.0, 5.0, 46.0, 96.0, 322.0, 438.0, 47.0, 4887.0, 4673.0"
65,cl_size_mean,float64,0.0,0.00,277.0,"0.0, 68.1512, 27.4694, 16.1729, 118.1665, 31.4966, 33.1743, 88.0179, 88.215, 39.3932"
66,cl_size_coeff_variation,float64,0.0,0.00,254.0,"0.0, 0.0699, 0.0916, 0.0918, 0.1179, 0.0328, 0.1528, 0.1476, 0.1332, 0.0817"
67,cl_size_min,float64,0.0,0.00,277.0,"0.0, 57.4684, 24.444, 12.3498, 107.0, 22.1886, 28.1668, 76.6151, 84.1817, 35.5768"
68,cl_size_max,float64,0.0,0.00,277.0,"0.0, 93.4828, 30.862, 20.4812, 149.6, 59.6541, 38.1818, 102.5278, 90.8046, 48.0683"
69,cl_size_q90,float64,0.0,0.00,277.0,"0.0, 79.8312, 30.862, 19.3394, 149.6, 59.6541, 38.1818, 102.5278, 90.8046, 48.0683"
70,cl_size_q10,float64,0.0,0.00,277.0,"0.0, 57.4913, 24.444, 12.772, 107.0, 23.9885, 28.1668, 76.6151, 84.1817, 35.5768"
71,cl_size_q75,float64,0.0,0.00,277.0,"0.0, 75.8, 29.3943, 17.4375, 117.1765, 39.855, 38.1818, 94.7619, 90.8046, 48.0683"
72,cl_size_q25,float64,0.0,0.00,277.0,"0.0, 63.2153, 25.0828, 13.9581, 112.0, 24.3333, 28.1668, 81.5424, 84.1817, 35.8046"
73,cl_size_q50,float64,0.0,0.00,276.0,"0.0, 40.4414, 65.6183, 27.5068, 16.8886, 113.4286, 25.9877, 38.1818, 86.8868, 89.6588"
74,SP_bias_mean,float64,0.0,0.00,266.0,"0.0, 0.5832, 0.828, 0.5993, 0.0262, 0.1178, 0.8049, 0.8092, 0.509, 0.9762"
75,SP_bias_coeff_variation,float64,0.0,0.00,214.0,"0.0, 0.0001, 0.0002, 0.0193, 0.0003, 0.0186, 0.018, 0.001, 0.0212, 0.0203"
76,SP_bias_min,float64,0.0,0.00,208.0,"0.0, 0.0001, 0.5831, 0.0003, 0.0004, 0.0002, 0.0044, 0.5992, 0.0026, 0.8144"
77,SP_bias_max,float64,0.0,0.00,239.0,"1.0, 0.0, 0.5833, 0.9994, 0.8837, 0.5993, 0.5091, 0.984, 0.5834, 0.999"
78,SP_bias_q90,float64,0.0,0.00,261.0,"0.0, 0.5832, 1.0, 0.1214, 0.14, 0.5993, 0.812, 0.5091, 0.0878, 0.9532"
79,SP_bias_q10,float64,0.0,0.00,248.0,"0.0, 0.5831, 0.0001, 0.0007, 0.0002, 0.0003, 0.5993, 0.0014, 0.7334, 0.0369"
80,SP_bias_q75,float64,0.0,0.00,262.0,"0.0, 0.5832, 0.0333, 0.9354, 1.0, 0.9992, 0.8024, 0.9226, 0.509, 0.9216"
81,SP_bias_q25,float64,0.0,0.00,250.0,"0.0, 0.5832, 0.0033, 0.5831, 0.7805, 0.6662, 0.85, 0.0003, 0.0001, 0.5993"
82,SP_bias_q50,float64,0.0,0.00,260.0,"0.0, 0.5832, 0.0042, 0.6969, 0.0374, 0.8996, 0.7908, 0.509, 0.8577, 0.9938"
83,SP_unconstraint_mean,float64,0.0,0.00,156.0,"0.0, 0.0001, 0.2295, 0.0002, 0.0064, 0.0285, 0.4942, 0.3151, 0.494, 0.3528"
84,SP_unconstraint_coeff_variation,float64,0.0,0.00,248.0,"0.0001, 0.0, 0.0002, 0.0018, 0.0014, 0.0003, 0.0006, 0.3436, 0.0007, 0.0013"
85,SP_unconstraint_min,float64,0.0,0.00,101.0,"0.0, 0.2294, 0.0001, 0.0003, 0.0002, 0.3528, 0.0814, 0.4941, 0.4921, 0.0064"
86,SP_unconstraint_max,float64,0.0,0.00,156.0,"0.0, 0.0001, 0.5, 0.2295, 0.9999, 0.0002, 0.0043, 1.0, 0.4961, 0.0003"
87,SP_unconstraint_q90,float64,0.0,0.00,151.0,"0.0, 0.0001, 0.2295, 0.4997, 0.495, 0.0002, 0.3528, 0.0004, 0.0037, 0.4948"
88,SP_unconstraint_q10,float64,0.0,0.00,130.0,"0.0, 0.2295, 0.0001, 0.0002, 0.0033, 0.1468, 0.4933, 0.0044, 0.0004, 0.3528"
89,SP_unconstraint_q75,float64,0.0,0.00,145.0,"0.0, 0.2295, 0.499, 0.0001, 0.4946, 0.4947, 0.0002, 0.3109, 0.3528, 0.3325"
90,SP_unconstraint_q25,float64,0.0,0.00,139.0,"0.0, 0.2295, 0.0001, 0.0043, 0.0002, 0.3528, 0.006, 0.0013, 0.0238, 0.2654"
91,SP_unconstraint_q50,float64,0.0,0.00,148.0,"0.0, 0.2295, 0.0064, 0.0047, 0.0002, 0.496, 0.0001, 0.3325, 0.03, 0.4941"
92,saps_BestSolution_Mean,float64,0.0,0.00,291.0,"0.0, 15.8854, 19134.0, 83.9466, 0.0004, 0.0009, 14.6154, 2.4794, 11.9521, 1877.0"
93,saps_BestSolution_CoeffVariance,float64,0.0,0.00,283.0,"0.0, 0.1635, 0.2013, 0.1884, 0.2679, 0.0955, 0.2404, 0.2501, 3.7613, 0.4158"
94,saps_FirstLocalMinStep_Mean,float64,0.0,0.00,296.0,"30.4626, 180.972, 6562.0, 157.551, 28.5016, 46.8352, 103.079, 117.659, 9.0564, 139.675"
95,saps_FirstLocalMinStep_CoeffVariance,float64,0.0,0.00,272.0,"0.0, 0.0794, 0.0731, 0.0278, 0.1213, 0.0992, 0.0745, 0.0706, 0.0358, 0.0714"
96,saps_FirstLocalMinStep_Median,float64,0.0,0.00,225.0,"17.0, 83.0, 133.0, 56.0, 28.0, 54.0, 62.0, 411.0, 408.0, 4.0"
97,saps_FirstLocalMinStep_Q10,float64,0.0,0.00,218.0,"0.0, 14.0, 392.0, 20.0, 49.0, 3.0, 6.0, 390.0, 91.0, 74.0"
98,saps_FirstLocalMinStep_Q90,float64,0.0,0.00,232.0,"21.0, 63.0, 145.0, 90.0, 427.0, 6.0, 60.0, 425.0, 15.0, 168.0"
99,saps_BestAvgImprovement_Mean,float64,0.0,0.00,296.0,"1.1995, 1.3709, 0.9618, 0.6928, 3.2192, 1.1278, 27.8847, 17.2726, 1.8382, 7.3884"
100,saps_BestAvgImprovement_CoeffVariance,float64,0.0,0.00,276.0,"0.1342, 0.0, 0.1953, 0.1278, 0.1316, 0.206, 0.1259, 0.1289, 0.172, 0.355"
101,saps_FirstLocalMinRatio_Mean,float64,0.0,0.00,225.0,"1.0, 0.9996, 0.9998, 0.9987, 0.9999, 0.9957, 0.9994, 0.9991, 0.9995, 1.0019"
102,saps_FirstLocalMinRatio_CoeffVariance,float64,0.0,0.00,235.0,"0.0002, 0.0001, 0.0, 0.0003, 0.0009, 0.0005, 0.0004, 0.001, 0.0069, 0.0313"
103,gsat_BestSolution_Mean,float64,0.0,0.00,283.0,"0.0, 1.0, 0.0007, 822.0, 53.0, 276.616, 60.4583, 1.1276, 1.261, 18.6697"
104,gsat_BestSolution_CoeffVariance,float64,0.0,0.00,278.0,"0.0, 0.372, 0.1675, 0.2379, 0.2212, 0.1601, 0.1247, 0.1186, 52.3259, 38.5616"
105,gsat_FirstLocalMinStep_Mean,float64,0.0,0.00,296.0,"30.3481, 180.864, 6511.5, 157.873, 28.5513, 46.8335, 102.297, 117.508, 8.9216, 138.622"
106,gsat_FirstLocalMinStep_CoeffVariance,float64,0.0,0.00,268.0,"0.0354, 0.0742, 0.0846, 0.1142, 0.0984, 0.0767, 0.0783, 0.0352, 0.0224, 0.0283"
107,gsat_FirstLocalMinStep_Median,float64,0.0,0.00,220.0,"102.0, 408.0, 17.0, 83.0, 325.0, 4.0, 80.0, 133.0, 56.0, 131.0"
108,gsat_FirstLocalMinStep_Q10,float64,0.0,0.00,219.0,"0.0, 122.0, 49.0, 90.0, 14.0, 6.0, 58.0, 15.0, 20.0, 390.0"
109,gsat_FirstLocalMinStep_Q90,float64,0.0,0.00,224.0,"21.0, 63.0, 428.0, 90.0, 6.0, 15.0, 526.0, 426.0, 100.0, 82.0"
110,gsat_BestAvgImprovement_Mean,float64,0.0,0.00,296.0,"0.9146, 0.3977, 0.3763, 0.2403, 3.2254, 0.6079, 30.9129, 18.4885, 1.031, 5.4255"
111,gsat_BestAvgImprovement_CoeffVariance,float64,0.0,0.00,287.0,"0.2089, 0.3453, 0.3615, 0.2558, 0.3457, 0.3386, 0.1715, 0.2392, 0.2271, 0.144"
112,gsat_FirstLocalMinRatio_Mean,float64,0.0,0.00,210.0,"0.9999, 0.9998, 0.9996, 0.9997, 1.0, 0.999, 0.9995, 0.9987, 0.997, 1.0027"
113,gsat_FirstLocalMinRatio_CoeffVariance,float64,0.0,0.00,207.0,"0.0, 0.0003, 0.0002, 0.0001, 0.0004, 0.0006, 0.0016, 0.0005, 0.0017, 0.0156"
114,lobjois_mean_depth_over_vars,float64,0.0,0.00,287.0,"0.8884, 1.0, 0.9999, 0.8838, 0.2363, 0.8016, 0.9026, 0.8286, 0.8584, 0.2221"
115,lobjois_log_num_nodes_over_vars,float64,0.0,0.00,279.0,"1.0, 0.9596, 0.9599, 0.9978, 0.9633, 0.9515, 0.7013, 0.9999, 0.9992, 0.9962"
116,Lines..Average.,float64,0.0,0.00,10.0,"12.8379, 20.9286, 4.7128, 8.4273, 3.3806, 6.1991, 23.5942, 23.504, 8.844, 21.3022"
117,Lines..Total.,float64,0.0,0.00,10.0,"14969.0, 2344.0, 5104.0, 28004.0, 835.0, 2833.0, 7267.0, 67903.0, 4820.0, 11418.0"
118,Size..Average.,float64,0.0,0.00,10.0,"10037.7342, 8767.2, 6089.7647, 13089.165, 5767.0909, 8232.4545, 29587.5714, 22142.8376, 11323.1364, 33905.6364"
119,Size..Total.,float64,0.0,0.00,10.0,"792981.0, 87672.0, 310578.0, 1348184.0, 63438.0, 181114.0, 207113.0, 4362139.0, 249109.0, 372962.0"
120,Number.of.files,float64,0.0,0.00,8.0,"22.0, 11.0, 79.0, 10.0, 103.0, 51.0, 7.0, 197.0"
121,Cyclomatic..Average.,float64,0.0,0.00,10.0,"2.7209, 5.0309, 0.9956, 1.6366, 0.5962, 1.5947, 4.1952, 2.0324, 1.7429, 7.406"
122,Cyclomatic..Total.,float64,0.0,0.00,10.0,"2691.0, 488.0, 901.0, 4458.0, 127.0, 606.0, 1225.0, 4699.0, 854.0, 3466.0"
123,Max.Indent..Average.,float64,0.0,0.00,10.0,"1.731, 2.1031, 1.1812, 1.5147, 1.1408, 1.2895, 1.6233, 1.548, 1.602, 2.2585"
124,Max.Indent..Total.,float64,0.0,0.00,10.0,"1712.0, 204.0, 1069.0, 4126.0, 243.0, 490.0, 474.0, 3579.0, 785.0, 1057.0"
125,nb_nodes,float64,0.0,0.00,10.0,"4334441.0, 34620.0, 113915.0, 2750173.0, 61190.0, 117121.0, 66353.0, 6389970.0, 1156552.0, 311606.0"
126,nb_edges,float64,0.0,0.00,10.0,"4545157.0, 35661.0, 119055.0, 2865629.0, 64065.0, 122044.0, 67203.0, 6601302.0, 1223172.0, 322859.0"
127,degree_max,float64,0.0,0.00,10.0,"32037.0, 4330.0, 2771.0, 12991.0, 1204.0, 3262.0, 3332.0, 1103346.0, 6472.0, 4137.0"
128,degree_mean,float64,0.0,0.00,10.0,"2.0972, 2.0601, 2.0902, 2.084, 2.094, 2.0841, 2.0256, 2.0661, 2.1152, 2.0722"
129,degree_variance,float64,0.0,0.00,10.0,"259.6702, 544.4947, 127.8259, 69.9813, 57.095, 165.0315, 169.7313, 190631.4435, 61.2153, 87.7601"
130,degree_entropy,float64,0.0,0.00,10.0,"1.3506, 1.3101, 1.3198, 1.3583, 1.3249, 1.3044, 1.2712, 1.198, 1.3502, 1.3321"
131,transitivity,float64,0.0,0.00,10.0,"0.0, 0.0, 0.0001, 0.0002, 0.0002, 0.0001, 0.0, 0.0, 0.0002, 0.0001"
132,clustering_max,float64,0.0,0.00,1.0,0.5
133,clustering_mean,float64,0.0,0.00,10.0,"0.0023, 0.0028, 0.003, 0.0027, 0.0032, 0.003, 0.0013, 0.0016, 0.0028, 0.0021"
134,clustering_variance,float64,0.0,0.00,10.0,"0.0004, 0.0005, 0.0005, 0.0004, 0.0005, 0.0005, 0.0002, 0.0003, 0.0004, 0.0003"
135,paths_max,float64,0.0,0.00,7.0,"72.0, 24.0, 33.0, 39.0, 32.0, 22.0, 38.0"
136,path_mean,float64,0.0,0.00,10.0,"6.5182, 5.0351, 5.4763, 6.9082, 5.7496, 5.1886, 8.3862, 5.5918, 6.5339, 6.3987"
137,path_variance,float64,0.0,0.00,10.0,"11.1239, 21.7582, 13.6063, 10.6156, 13.0147, 10.9685, 38.0051, 8.4527, 11.13, 12.6411"
138,path_entropy,float64,0.0,0.00,10.0,"2.4333, 1.8887, 2.1104, 2.463, 2.1769, 1.9934, 2.7711, 1.9276, 2.4267, 2.4491"
139,Stmt,float64,0.0,0.00,10.0,"0.5137, 0.4244, 0.4466, 0.5684, 0.4798, 0.428, 0.6128, 0.5081, 0.508, 0.5221"
140,Type,float64,0.0,0.00,10.0,"0.0548, 0.0441, 0.0391, 0.0474, 0.0481, 0.0398, 0.0173, 0.0374, 0.064, 0.038"
141,Decl,float64,0.0,0.00,10.0,"0.3521, 0.2927, 0.3976, 0.294, 0.3575, 0.4291, 0.1248, 0.2291, 0.3569, 0.318"
142,Attribute,float64,0.0,0.00,10.0,"0.0102, 0.0989, 0.0341, 0.0099, 0.0267, 0.0379, 0.0318, 0.0069, 0.0101, 0.019"
143,Operator,float64,0.0,0.00,10.0,"0.0462, 0.0869, 0.0516, 0.0556, 0.0574, 0.0421, 0.1294, 0.0302, 0.0414, 0.0688"
144,Literal,float64,0.0,0.00,10.0,"0.0231, 0.053, 0.031, 0.0247, 0.0306, 0.0232, 0.0838, 0.1885, 0.0196, 0.0341"
145,edge_ss,float64,0.0,0.00,10.0,"3657.0, 2742.0, 3143.0, 3693.0, 3357.0, 3057.0, 4130.0, 4012.0, 3599.0, 3761.0"
146,edge_st,float64,0.0,0.00,7.0,"0.0, 9.0, 15.0, 11.0, 14.0, 10.0, 16.0"
147,edge_sd,float64,0.0,0.00,10.0,"453.0, 93.0, 448.0, 544.0, 345.0, 413.0, 139.0, 329.0, 490.0, 415.0"
148,edge_sa,float64,0.0,0.00,2.0,"0.0, 1.0"
149,edge_so,float64,0.0,0.00,10.0,"574.0, 1093.0, 643.0, 690.0, 801.0, 515.0, 1741.0, 389.0, 497.0, 816.0"
150,edge_sl,float64,0.0,0.00,2.0,"0.0, 1.0"
151,edge_ts,float64,0.0,0.00,8.0,"0.0, 13.0, 21.0, 8.0, 2.0, 7.0, 27.0, 22.0"
152,edge_tt,float64,0.0,0.00,10.0,"770.0, 488.0, 468.0, 662.0, 535.0, 502.0, 199.0, 521.0, 907.0, 505.0"
153,edge_td,float64,0.0,0.00,10.0,"205.0, 251.0, 210.0, 185.0, 211.0, 160.0, 86.0, 155.0, 228.0, 144.0"
154,edge_ds,float64,0.0,0.00,10.0,"112.0, 61.0, 77.0, 108.0, 71.0, 63.0, 157.0, 56.0, 104.0, 135.0"
155,edge_dt,float64,0.0,0.00,9.0,"46.0, 112.0, 95.0, 65.0, 61.0, 30.0, 79.0, 146.0, 53.0"
156,edge_dd,float64,0.0,0.00,10.0,"3074.0, 2644.0, 3690.0, 2509.0, 3313.0, 3986.0, 1066.0, 2124.0, 3037.0, 2827.0"
157,edge_ad,float64,0.0,0.00,10.0,"93.0, 919.0, 325.0, 101.0, 248.0, 367.0, 352.0, 77.0, 78.0, 192.0"
158,edge_os,float64,0.0,0.00,10.0,"347.0, 749.0, 380.0, 425.0, 407.0, 327.0, 1012.0, 214.0, 277.0, 500.0"
159,edge_od,float64,0.0,0.00,9.0,"7.0, 1.0, 16.0, 18.0, 15.0, 22.0, 5.0, 14.0, 11.0"
160,edge_oo,float64,0.0,0.00,10.0,"65.0, 98.0, 91.0, 81.0, 109.0, 110.0, 237.0, 48.0, 72.0, 126.0"
161,edge_ls,float64,0.0,0.00,8.0,"165.0, 146.0, 194.0, 224.0, 205.0, 520.0, 1725.0, 134.0"
162,edge_ld,float64,0.0,0.00,8.0,"25.0, 11.0, 22.0, 12.0, 13.0, 17.0, 7.0, 16.0"
163,edge_lo,float64,0.0,0.00,10.0,"56.0, 245.0, 93.0, 79.0, 132.0, 84.0, 300.0, 54.0, 59.0, 175.0"
164,op_short,float64,0.0,0.00,2.0,"0.0, 0.0048"
165,op_int,float64,0.0,0.00,10.0,"0.259, 0.7479, 0.4619, 0.3129, 0.5269, 0.5374, 0.4877, 0.2525, 0.2229, 0.4906"
166,op_long,float64,0.0,0.00,10.0,"0.1799, 0.0529, 0.058, 0.1965, 0.047, 0.0649, 0.0465, 0.1568, 0.2006, 0.1065"
167,op_long_long,float64,0.0,0.00,10.0,"0.0029, 0.0299, 0.0193, 0.0129, 0.0278, 0.0226, 0.0162, 0.0081, 0.0095, 0.0107"
168,op_float,float64,0.0,0.00,6.0,"0.0, 0.0014, 0.0036, 0.001, 0.0014, 0.0054"
169,op_double,float64,0.0,0.00,10.0,"0.0058, 0.0167, 0.0351, 0.0024, 0.0278, 0.0226, 0.011, 0.0061, 0.008, 0.0089"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
runtime,2960.0,6.297399e+00,3.867976e+00,-6.908756e+00,8.517193e+00
nvarsOrig,2960.0,2.598159e+03,8.266341e+03,2.000000e+01,6.388200e+04
nclausesOrig,2960.0,9.961375e+04,1.973931e+05,1.050000e+02,1.711065e+06
nvars,2960.0,1.785720e+03,4.741163e+03,2.000000e+01,3.430700e+04
nclauses,2960.0,9.572429e+04,1.925640e+05,1.050000e+02,1.667873e+06
reducedVars,2960.0,3.573963e-01,3.140072e+00,0.000000e+00,5.385140e+01
reducedClauses,2960.0,2.789071e-01,3.213233e+00,0.000000e+00,5.496770e+01
vars_clauses_ratio,2960.0,9.685068e-02,1.290584e-01,6.000000e-04,5.132000e-01
POSNEG_RATIO_CLAUSE_mean,2960.0,7.536118e-01,2.874457e-01,2.437000e-01,1.000000e+00
POSNEG_RATIO_CLAUSE_coeff_variation,2960.0,3.524490e-01,4.109207e-01,0.000000e+00,1.147100e+00
POSNEG_RATIO_CLAUSE_min,2960.0,5.334730e-01,4.507661e-01,0.000000e+00,1.000000e+00
POSNEG_RATIO_CLAUSE_max,2960.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
POSNEG_RATIO_CLAUSE_entropy,2960.0,5.883929e-01,6.646122e-01,0.000000e+00,2.931600e+00
VCG_CLAUSE_mean,2960.0,1.655236e-02,3.311820e-02,1.000000e-04,3.500000e-01
VCG_CLAUSE_coeff_variation,2960.0,9.672905e-01,7.449843e-01,0.000000e+00,2.751500e+00
VCG_CLAUSE_min,2960.0,1.051723e-02,2.813907e-02,1.000000e-04,3.500000e-01
VCG_CLAUSE_max,2960.0,4.939291e-02,4.362519e-02,1.000000e-04,3.500000e-01
VCG_CLAUSE_entropy,2960.0,4.618584e-01,4.533194e-01,0.000000e+00,2.611500e+00
UNARY,2960.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
BINARYp,2960.0,4.574568e-01,4.474049e-01,0.000000e+00,9.893000e-01
TRINARYp,2960.0,6.388578e-01,4.026918e-01,0.000000e+00,1.000000e+00
VCG_VAR_coeff_variation,2960.0,3.786530e-01,7.177741e-01,0.000000e+00,4.572100e+00
VCG_VAR_min,2960.0,1.286959e-02,3.020453e-02,0.000000e+00,3.349000e-01
VCG_VAR_max,2960.0,3.030878e-02,6.334545e-02,3.000000e-04,7.095000e-01
VCG_VAR_entropy,2960.0,2.754457e+00,2.194402e+00,0.000000e+00,6.617200e+00
POSNEG_RATIO_VAR_mean,2960.0,2.042970e-01,1.926585e-01,0.000000e+00,9.379000e-01
POSNEG_RATIO_VAR_stdev,2960.0,7.459155e-02,8.278319e-02,0.000000e+00,4.232000e-01
POSNEG_RATIO_VAR_min,2960.0,7.527365e-02,9.415844e-02,0.000000e+00,5.000000e-01
POSNEG_RATIO_VAR_max,2960.0,4.300155e-01,3.346879e-01,0.000000e+00,1.000000e+00
POSNEG_RATIO_VAR_entropy,2960.0,1.763200e+00,1.395289e+00,0.000000e+00,4.244100e+00
HORNY_VAR_mean,2960.0,5.313514e-03,9.529451e-03,0.000000e+00,1.333000e-01
HORNY_VAR_coeff_variation,2960.0,4.914824e-01,8.173746e-01,0.000000e+00,6.043600e+00
HORNY_VAR_min,2960.0,3.113851e-03,9.237154e-03,0.000000e+00,1.333000e-01
HORNY_VAR_max,2960.0,1.229932e-02,2.773356e-02,2.000000e-04,2.122000e-01
HORNY_VAR_entropy,2960.0,2.763186e+00,1.877474e+00,0.000000e+00,6.341300e+00
horn_clauses_fraction,2960.0,6.153946e-01,3.203676e-01,9.400000e-03,9.871000e-01
VG_mean,2960.0,2.233176e-02,4.376082e-02,1.000000e-04,3.429000e-01
VG_coeff_variation,2960.0,2.400878e-01,4.343248e-01,0.000000e+00,2.102400e+00
VG_min,2960.0,2.058953e-02,4.320996e-02,0.000000e+00,3.333000e-01
VG_max,2960.0,2.735068e-02,4.697766e-02,2.000000e-04,3.714000e-01
CG_mean,1150.0,3.780609e-02,4.782801e-02,0.000000e+00,3.232000e-01
CG_coeff_variation,1150.0,7.996461e-01,7.878927e-01,5.700000e-03,4.692700e+00
CG_min,1150.0,1.984087e-02,2.895618e-02,0.000000e+00,2.048000e-01
CG_max,1150.0,9.638000e-02,8.298475e-02,1.400000e-03,3.714000e-01
CG_entropy,1150.0,1.632671e+00,1.543694e+00,4.370000e-02,5.917500e+00
cluster_coeff_mean,1150.0,2.133130e-01,1.559122e-01,9.700000e-03,5.877000e-01
cluster_coeff_coeff_variation,1150.0,3.232670e-01,2.736142e-01,8.000000e-03,1.619600e+00
cluster_coeff_min,1150.0,9.736174e-02,1.151070e-01,4.000000e-04,4.000000e-01
cluster_coeff_max,1150.0,3.624565e-01,2.783557e-01,4.080000e-02,9.797000e-01
cluster_coeff_entropy,1150.0,1.245157e+00,1.078876e+00,9.750000e-02,3.943700e+00
DIAMETER_mean,2960.0,9.680976e+00,6.196878e+01,2.000000e+00,7.495250e+02
DIAMETER_coeff_variation,2960.0,4.469155e-02,5.594105e-02,0.000000e+00,1.864000e-01
DIAMETER_min,2960.0,8.939189e+00,6.106504e+01,2.000000e+00,7.440000e+02
DIAMETER_max,2960.0,1.051689e+01,6.359416e+01,2.000000e+00,7.600000e+02
DIAMETER_entropy,2960.0,2.922770e-01,5.783957e-01,0.000000e+00,4.451900e+00
cl_num_mean,2960.0,2.108434e+03,1.780278e+03,0.000000e+00,4.926250e+03
cl_num_coeff_variation,2960.0,3.939703e-01,4.482572e-01,0.000000e+00,2.391700e+00
cl_num_min,2960.0,1.681848e+03,1.883444e+03,0.000000e+00,4.916000e+03
cl_num_max,2960.0,2.827412e+03,1.764903e+03,0.000000e+00,4.941000e+03
cl_num_q90,2960.0,2.688720e+03,1.806504e+03,0.000000e+00,4.941000e+03
cl_num_q10,2960.0,1.719226e+03,1.866885e+03,0.000000e+00,4.916000e+03
cl_num_q75,2960.0,2.333473e+03,1.845856e+03,0.000000e+00,4.941000e+03
cl_num_q25,2960.0,1.862159e+03,1.863707e+03,0.000000e+00,4.917000e+03
cl_num_q50,2960.0,2.092551e+03,1.864532e+03,0.000000e+00,4.931000e+03
cl_size_mean,2960.0,4.734434e+01,3.493671e+01,0.000000e+00,2.346801e+02
cl_size_coeff_variation,2960.0,1.260182e-01,1.368153e-01,0.000000e+00,9.067000e-01
cl_size_min,2960.0,3.970851e+01,3.086483e+01,0.000000e+00,2.346801e+02
cl_size_max,2960.0,5.961286e+01,4.502113e+01,0.000000e+00,3.903691e+02
cl_size_q90,2960.0,5.620278e+01,4.328131e+01,0.000000e+00,3.903691e+02
cl_size_q10,2960.0,4.043380e+01,3.109529e+01,0.000000e+00,2.346801e+02
cl_size_q75,2960.0,5.162402e+01,4.094728e+01,0.000000e+00,3.903691e+02
cl_size_q25,2960.0,4.275899e+01,3.156602e+01,0.000000e+00,2.346801e+02
cl_size_q50,2960.0,4.762751e+01,3.906778e+01,0.000000e+00,3.903691e+02
SP_bias_mean,2960.0,5.861301e-01,3.135833e-01,0.000000e+00,9.812000e-01
SP_bias_coeff_variation,2960.0,3.780926e-01,7.799257e-01,0.000000e+00,8.359800e+00
SP_bias_min,2960.0,3.958307e-01,3.431301e-01,0.000000e+00,9.352000e-01
SP_bias_max,2960.0,7.510392e-01,2.956466e-01,0.000000e+00,1.000000e+00
SP_bias_q90,2960.0,6.623912e-01,3.112393e-01,0.000000e+00,1.000000e+00
SP_bias_q10,2960.0,5.087557e-01,3.305463e-01,0.000000e+00,9.684000e-01
SP_bias_q75,2960.0,6.257564e-01,3.262073e-01,0.000000e+00,1.000000e+00
SP_bias_q25,2960.0,5.482230e-01,3.331186e-01,0.000000e+00,9.950000e-01
SP_bias_q50,2960.0,5.864463e-01,3.315479e-01,0.000000e+00,9.966000e-01
SP_unconstraint_mean,2960.0,1.111044e-01,1.527636e-01,0.000000e+00,4.988000e-01
SP_unconstraint_coeff_variation,2960.0,2.422025e+00,3.380867e+00,0.000000e+00,1.573620e+01
SP_unconstraint_min,2960.0,6.986486e-02,1.303445e-01,0.000000e+00,4.988000e-01
SP_unconstraint_max,2960.0,1.946024e-01,2.588927e-01,0.000000e+00,1.000000e+00
SP_unconstraint_q90,2960.0,1.333422e-01,1.793048e-01,0.000000e+00,9.908000e-01
SP_unconstraint_q10,2960.0,8.439966e-02,1.355858e-01,0.000000e+00,4.988000e-01
SP_unconstraint_q75,2960.0,1.232453e-01,1.736538e-01,0.000000e+00,9.381000e-01
SP_unconstraint_q25,2960.0,1.006429e-01,1.525751e-01,0.000000e+00,4.988000e-01
SP_unconstraint_q50,2960.0,1.118493e-01,1.600547e-01,0.000000e+00,4.997000e-01
saps_BestSolution_Mean,2960.0,5.220809e+02,3.257775e+03,0.000000e+00,4.690380e+04
saps_BestSolution_CoeffVariance,2960.0,3.760398e+00,8.357293e+00,0.000000e+00,5.450690e+01
saps_FirstLocalMinStep_Mean,2960.0,4.702383e+02,9.240200e+02,0.000000e+00,6.592400e+03
saps_FirstLocalMinStep_CoeffVariance,2960.0,1.187287e-01,9.178478e-02,0.000000e+00,8.661000e-01
saps_FirstLocalMinStep_Median,2960.0,4.869949e+02,9.724089e+02,0.000000e+00,6.775000e+03
saps_FirstLocalMinStep_Q10,2960.0,4.213919e+02,8.849658e+02,0.000000e+00,6.562000e+03
saps_FirstLocalMinStep_Q90,2960.0,5.007061e+02,9.735261e+02,0.000000e+00,6.775000e+03
saps_BestAvgImprovement_Mean,2960.0,1.878347e+01,2.495597e+01,1.959000e-01,1.692540e+02
saps_BestAvgImprovement_CoeffVariance,2960.0,2.241720e-01,1.576393e-01,0.000000e+00,1.288100e+00
saps_FirstLocalMinRatio_Mean,2960.0,9.619520e-01,7.782478e-02,6.758000e-01,1.252400e+00
saps_FirstLocalMinRatio_CoeffVariance,2960.0,6.459899e-02,1.350776e-01,0.000000e+00,1.056200e+00
gsat_BestSolution_Mean,2960.0,2.745470e+02,1.422699e+03,0.000000e+00,2.123420e+04
gsat_BestSolution_CoeffVariance,2960.0,2.777124e+00,8.206693e+00,0.000000e+00,5.900000e+01
gsat_FirstLocalMinStep_Mean,2960.0,4.885683e+02,9.603048e+02,2.697000e+00,6.849500e+03
gsat_FirstLocalMinStep_CoeffVariance,2960.0,1.120605e-01,1.332572e-01,1.400000e-03,1.414200e+00
gsat_FirstLocalMinStep_Median,2960.0,4.988953e+02,9.923141e+02,3.000000e+00,6.866000e+03
gsat_FirstLocalMinStep_Q10,2960.0,4.121554e+02,8.126145e+02,0.000000e+00,6.519000e+03
gsat_FirstLocalMinStep_Q90,2960.0,4.799426e+02,9.145491e+02,0.000000e+00,6.908000e+03
gsat_BestAvgImprovement_Mean,2960.0,1.959939e+01,2.676289e+01,4.440000e-02,1.633440e+02
gsat_BestAvgImprovement_CoeffVariance,2960.0,3.377743e-01,4.233378e-01,2.040000e-02,5.893400e+00
gsat_FirstLocalMinRatio_Mean,2960.0,9.803493e-01,4.425102e-01,6.870000e-01,8.462900e+00
gsat_FirstLocalMinRatio_CoeffVariance,2960.0,6.024324e-02,2.353238e-01,0.000000e+00,3.528600e+00
lobjois_mean_depth_over_vars,2960.0,6.605753e-01,2.684546e-01,2.730000e-02,1.000000e+00
lobjois_log_num_nodes_over_vars,2960.0,8.046534e-01,1.984986e-01,8.710000e-02,1.000000e+00
Lines..Average.,2960.0,1.337307e+01,7.738474e+00,3.380567e+00,2.359416e+01
Lines..Total.,2960.0,1.454970e+04,1.936523e+04,8.350000e+02,6.790300e+04
Size..Average.,2960.0,1.489426e+04,9.552581e+03,5.767091e+03,3.390564e+04
Size..Total.,2960.0,7.975290e+05,1.245167e+06,6.343800e+04,4.362139e+06
Number.of.files,2960.0,5.130000e+01,5.771772e+01,7.000000e+00,1.970000e+02
Cyclomatic..Average.,2960.0,2.795147e+00,2.019503e+00,5.962441e-01,7.405983e+00
Cyclomatic..Total.,2960.0,1.951500e+03,1.637003e+03,1.270000e+02,4.699000e+03
Max.Indent..Average.,2960.0,1.599224e+00,3.460514e-01,1.140845e+00,2.258547e+00
Max.Indent..Total.,2960.0,1.373900e+03,1.316647e+03,2.040000e+02,4.126000e+03
nb_nodes,2960.0,1.533594e+06,2.124840e+06,3.462000e+04,6.389970e+06
nb_edges,2960.0,1.596615e+06,2.204801e+06,3.566100e+04,6.601302e+06
degree_max,2960.0,1.173882e+05,3.288224e+05,1.204000e+03,1.103346e+06
degree_mean,2960.0,2.078881e+00,2.337050e-02,2.025621e+00,2.115205e+00
degree_variance,2960.0,1.921742e+04,5.714783e+04,5.709500e+01,1.906314e+05
degree_entropy,2960.0,1.311941e+00,4.523115e-02,1.197951e+00,1.358274e+00
transitivity,2960.0,9.054889e-05,7.074469e-05,3.642893e-08,2.179608e-04
clustering_max,2960.0,5.000000e-01,0.000000e+00,5.000000e-01,5.000000e-01
clustering_mean,2960.0,2.479035e-03,6.100060e-04,1.290410e-03,3.186031e-03
clustering_variance,2960.0,4.137295e-04,9.864092e-05,2.472258e-04,5.242587e-04
paths_max,2960.0,3.890000e+01,1.743539e+01,2.200000e+01,7.200000e+01
path_mean,2960.0,6.178658e+00,9.490906e-01,5.035136e+00,8.386158e+00
path_variance,2960.0,1.513162e+01,8.335238e+00,8.452734e+00,3.800513e+01
path_entropy,2960.0,2.264033e+00,2.729192e-01,1.888720e+00,2.771147e+00
Stmt,2960.0,5.011756e-01,5.690206e-02,4.243586e-01,6.128133e-01
Type,2960.0,4.299189e-02,1.170183e-02,1.734662e-02,6.401017e-02
Decl,2960.0,3.151823e-01,8.324190e-02,1.248323e-01,4.291425e-01
Attribute,2960.0,2.854495e-02,2.582039e-02,6.905315e-03,9.888925e-02
Operator,2960.0,6.095260e-02,2.730487e-02,3.015083e-02,1.293687e-01
Literal,2960.0,5.115264e-02,4.931188e-02,1.957068e-02,1.884558e-01
edge_ss,2960.0,3.515100e+03,4.142312e+02,2.742000e+03,4.130000e+03
edge_st,2960.0,8.400000e+00,5.954156e+00,0.000000e+00,1.600000e+01
edge_sd,2960.0,3.669000e+02,1.392438e+02,9.300000e+01,5.440000e+02
edge_sa,2960.0,4.000000e-01,4.899807e-01,0.000000e+00,1.000000e+00
edge_so,2960.0,7.759000e+02,3.736349e+02,3.890000e+02,1.741000e+03
edge_sl,2960.0,1.000000e-01,3.000507e-01,0.000000e+00,1.000000e+00
edge_ts,2960.0,1.130000e+01,9.123493e+00,0.000000e+00,2.700000e+01
edge_tt,2960.0,5.557000e+02,1.809261e+02,1.990000e+02,9.070000e+02
edge_td,2960.0,1.835000e+02,4.571385e+01,8.600000e+01,2.510000e+02
edge_ds,2960.0,9.440000e+01,3.253302e+01,5.600000e+01,1.570000e+02
edge_dt,2960.0,7.330000e+01,3.359749e+01,3.000000e+01,1.460000e+02
edge_dd,2960.0,2.827000e+03,7.849446e+02,1.066000e+03,3.986000e+03
edge_ad,2960.0,2.752000e+02,2.410095e+02,7.700000e+01,9.190000e+02
edge_os,2960.0,4.638000e+02,2.290753e+02,2.140000e+02,1.012000e+03
edge_od,2960.0,1.160000e+01,6.201048e+00,1.000000e+00,2.200000e+01
edge_oo,2960.0,1.037000e+02,4.965524e+01,4.800000e+01,2.370000e+02
edge_ls,2960.0,3.643000e+02,4.658752e+02,1.340000e+02,1.725000e+03
edge_ld,2960.0,1.590000e+01,5.958355e+00,7.000000e+00,2.500000e+01
edge_lo,2960.0,1.277000e+02,8.154911e+01,5.400000e+01,3.000000e+02
op_short,2960.0,4.780000e-04,1.434242e-03,0.000000e+00,4.780000e-03
op_int,2960.0,4.299790e-01,1.572894e-01,2.229300e-01,7.479100e-01
op_long,2960.0,1.109720e-01,6.226518e-02,4.653000e-02,2.006400e-01
op_long_long,2960.0,1.601900e-02,8.374613e-03,2.880000e-03,2.994000e-02
op_float,2960.0,1.281000e-03,1.749223e-03,0.000000e+00,5.370000e-03
op_double,2960.0,1.442800e-02,1.025458e-02,2.350000e-03,3.507000e-02
op_bit,2960.0,8.897800e-02,5.655534e-02,4.604000e-02,2.479100e-01

In [7]:
# Categorical Feature Statistics
cat_stats

                         value  count   pct
column      rank
instance_id 1     feba188676d9     10  0.34
            2     01026dd24a23     10  0.34
            3     02033e5b65f1     10  0.34
            4     04418fe8cd39     10  0.34
            5     05f4dd3c60df     10  0.34

In [8]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,11.32,-1.741,NaN,14.961,0.355,log1p,15819.8,4.564490e+17,exponential

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
    group_labels=task_mold.group_labels,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=10, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default IID splits",
    splits=splits
)

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to sat11_hand_algo_runtime/versions/019dd4a1-d364-7e7e-9ebd-af85a6b33ecb
019dd4a1-d364-7e7e-9ebd-af85a6b33ecb
ef0bf175afa055903ed74130a5e6be0eb7dde475b0e6446aab8958e593fe3eba