### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="musk_iid",
    version_from_unique_name="musk",
    version_comment="IID outer splits for the musk dataset",
    # -- Rest as before
    dataset_year="1994",
    domain_str="chemistry & material science",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C51608",
    download_description="""
wget https://archive.ics.uci.edu/static/public/75/musk+version+2.zip && unzip musk+version+2.zip clean2.data.Z && uncompress clean2.data.Z && rm musk+version+2.zip && mkdir -p local-data-warehouse/musk && mv clean2.data local-data-warehouse/musk/
""",
    # References
    academic_reference_bibtex="""@article{dietterich1993comparison,
  title={A comparison of dynamic reposing and tangent distance for drug activity prediction},
  author={Dietterich, Thomas and Jain, Ajay and Lathrop, Richard and Lozano-Perez, Tomas},
  journal={Advances in neural information processing systems},
  volume={6},
  year={1993}
}
""",
    academic_reference_bibtex_key="dietterich1993comparison",
    license="CC BY 4.0",
    data_tags=["Non-IID", "Grouped"],
    curation_comments="""
- We rename the molecule IDs to remove the target leakage from the names.
- We drop the conformation name as it leaks information that the real task should not have (the correlation between specific conformations across samples).
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="class",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="class",
)

## Preprocessing

In [2]:
import pandas as pd
import uuid

df = pd.read_csv(dataset_mold.path / "clean2.data", header=None, names=[
    "molecule_name", "conformation_name", *[f"feature_{i}" for i in range(166)], "class",
])
print("Loaded data shape:", df.shape)

df = df.drop(columns=["conformation_name"])

df["class"] = df["class"].map({0: "non-musk", 1: "musk"})

# Create mapping: molecule -> random string id
mapping = {val: uuid.uuid4().hex[:12] for val in df["molecule_name"].unique()}
df["molecule_name"] = df["molecule_name"].map(mapping)

as_cat_type = ["molecule_name", "class"]
df[as_cat_type] = df[as_cat_type].astype("category")


df = df.sample(frac=1, random_state=42).sort_values(by="molecule_name").reset_index(drop=True)

Loaded data shape: (6598, 169)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 6,598
Columns: 168
Use sampling: False (sample size: 6,598)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['feature_126', 'feature_72', 'feature_33', 'feature_20', 'feature_132', 'feature_55', 'feature_128', 'feature_139', 'feature_59', 'feature_47']
Rows remaining as candidates after top-10 filter: 860 (of 6,598)

#### Duplicate Report
Total duplicate rows: 17 (0.26% of dataset)
Duplicate rows ignoring target: 17 (0.26% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,molecule_name,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,feature_80,feature_81,feature_82,feature_83,feature_84,feature_85,feature_86,feature_87,feature_88,feature_89,feature_90,feature_91,feature_92,feature_93,feature_94,feature_95,feature_96,feature_97,feature_98,feature_99,feature_100,feature_101,feature_102,feature_103,feature_104,feature_105,feature_106,feature_107,feature_108,feature_109,feature_110,feature_111,feature_112,feature_113,feature_114,feature_115,feature_116,feature_117,feature_118,feature_119,feature_120,feature_121,feature_122,feature_123,feature_124,feature_125,feature_126,feature_127,feature_128,feature_129,feature_130,feature_131,feature_132,feature_133,feature_134,feature_135,feature_136,feature_137,feature_138,feature_139,feature_140,feature_141,feature_142,feature_143,feature_144,feature_145,feature_146,feature_147,feature_148,feature_149,feature_150,feature_151,feature_152,feature_153,feature_154,feature_155,feature_156,feature_157,feature_158,feature_159,feature_160,feature_161,feature_162,feature_163,feature_164,feature_165,class
0,00b64ae2feb3,2,-198,-159,146,-117,-122,52,37,-25,-129,-49,-124,-58,-97,-76,-293,37,-72,-69,-80,-90,-12,-66,-65,-94,6,-10,-91,65,-141,-116,-18,77,-233,83,47,-173,-10,-145,-29,-183,-138,-80,-57,-128,-120,-115,-74,-23,-127,-107,-16,-14,52,134,-70,62,-151,-12,-169,111,-187,2,-185,-12,26,-166,-116,-132,-113,-168,-150,-50,-133,-61,-179,8,-54,-103,55,-82,14,-59,207,-181,40,-137,-74,119,-145,-201,18,68,-135,46,-33,-41,37,-155,42,-205,-5,-53,-50,-85,-131,-170,-92,-69,-124,-48,-73,-68,-51,-196,-113,-78,57,72,-20,-111,50,-103,107,16,5,-157,-189,-132,-48,58,-116,-72,-119,-99,-109,39,-106,-48,-41,-36,-40,22,14,-178,-104,-120,-117,-129,-11,126,-2,67,-170,-121,-193,-236,-265,-206,-130,6,9,148,-50,-112,83,musk
1,00b64ae2feb3,22,-197,-151,148,-117,-50,66,-6,-20,-174,-50,-101,-88,-85,-95,-279,34,-100,-94,-41,-51,-10,-81,-60,-93,-17,18,-120,6,-144,-116,-4,53,-237,91,50,-174,-39,-145,18,-180,-104,-121,-52,-123,-107,-107,-63,-42,-136,-68,-24,-19,37,22,-60,84,-152,2,-185,135,-180,41,-185,-26,13,-166,-114,-133,-82,-163,-150,-68,-111,-97,-180,8,-27,-105,66,-57,31,-59,205,-193,38,-125,-134,79,-143,-202,10,87,-152,41,91,-71,9,-155,73,-203,20,-79,-61,-90,-63,-127,-52,-74,-124,-40,-58,-65,-52,-178,-72,-88,35,78,-9,-111,-74,-95,40,-59,21,-181,-195,-165,-11,53,108,-74,-96,-75,-133,3,-122,-71,-48,-74,-13,51,8,-178,-104,-120,-92,-111,28,124,-11,64,-169,-20,-186,-236,-258,-206,-134,-90,-15,138,-58,-119,39,musk
2,00b64ae2feb3,20,-198,-159,32,-117,131,52,40,-24,-127,-51,-125,-58,-98,-74,-296,37,-73,-70,-81,-90,-12,-66,-62,-94,6,-8,-90,115,-141,-116,-6,69,-211,70,53,43,-12,-145,-27,-183,-99,-79,-59,-126,-126,-115,-75,-22,-124,-107,-16,-15,56,-21,-71,63,-151,137,-170,-42,-181,39,-97,87,11,-166,-117,-132,-112,-168,-150,-51,-133,-59,-180,8,-58,-104,55,-82,14,-60,-39,-181,40,-136,-73,71,12,-202,8,49,-139,42,92,118,36,-154,43,-205,21,-52,-50,-85,-137,-170,-92,-67,-124,-51,-74,-68,-51,-195,-113,-89,57,73,-19,-113,73,78,46,-78,29,-158,-161,-134,30,56,108,-72,-118,-100,-110,38,-106,-48,-39,-36,-40,22,14,-178,-104,-119,-116,-128,-9,126,60,58,-169,-18,-185,-238,-270,-201,-133,-97,-14,141,-60,-126,21,musk
3,00b64ae2feb3,2,-197,-151,146,-117,-121,66,-7,-20,-175,-50,-102,-89,-85,-96,-277,35,-99,-94,-42,-50,-10,-81,-66,-94,-17,19,-120,66,-142,-116,-18,77,-237,83,47,-173,-38,-145,19,-180,-138,-123,-52,-124,-106,-107,-63,-41,-137,-68,-24,-19,35,134,-60,84,-152,-12,-185,110,-187,2,-185,-13,26,-166,-114,-132,-82,-163,-150,-68,-111,-98,-180,9,-26,-105,66,-57,31,-60,207,-193,38,-125,-134,119,-145,-201,19,68,-152,46,-32,-40,10,-154,74,-203,-5,-80,-62,-90,-61,-127,-53,-74,-124,-39,-57,-65,-52,-178,-73,-77,35,78,-9,-111,50,-103,106,16,5,-181,-194,-165,-48,58,-116,-73,-96,-74,-132,4,-121,-71,-48,-74,-13,51,8,-178,-104,-120,-92,-111,28,126,-2,67,-171,-121,-193,-236,-257,-206,-130,6,8,148,-50,-112,84,musk
4,00b64ae2feb3,5,-197,-151,29,-117,100,66,-4,-20,-174,-51,-101,-88,-85,-94,-281,34,-100,-94,-43,-51,-10,-81,-64,-93,-17,19,-120,62,-145,-116,-13,81,-222,64,45,133,-39,-145,19,-180,-139,-121,-53,-122,-109,-107,-63,-42,-137,-68,-24,-19,40,-51,-59,84,-152,96,-185,112,-186,7,-148,99,27,-166,-114,-132,-82,-163,-150,-68,-111,-96,-180,8,-28,-105,66,-57,31,-59,-43,-193,38,-125,-133,21,-92,-201,18,69,-153,47,-12,131,9,-155,74,-203,-5,-78,-61,-89,-66,-128,-52,-74,-124,-40,-58,-65,-53,-178,-72,-91,35,78,-9,-112,-63,-51,101,15,1,-181,-191,-165,69,56,8,-76,-97,-75,-133,2,-122,-71,-48,-74,-13,51,8,-178,-104,-119,-92,-111,29,125,57,55,-171,-114,-192,-238,-251,-148,-131,4,6,141,-54,-113,65,musk

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,molecule_name,category,0.0,0.0,102.0,"c394ef9107ce, a470dec69277, d2c2629403c4, 6c75e31d113c, a24523edbb05, 14b0c39debce, 54c36f77003d, 6047a5025b9c, 311bb792dd49, 0208e864f467"
1,class,category,0.0,0.0,2.0,"non-musk, musk"
2,feature_0,int64,0.0,0.0,202.0,"44, 43, 35, 36, 46, 51, 48, 37, 47, 57"
3,feature_1,int64,0.0,0.0,260.0,"-198, -194, -199, -193, -192, -195, -196, -197, 86, -191"
4,feature_2,int64,0.0,0.0,221.0,"-145, -144, -112, -19, -22, -111, 31, -62, -23, -146"
5,feature_3,int64,0.0,0.0,257.0,"-76, -77, -69, 28, -70, 29, 33, 131, 32, 152"
6,feature_4,int64,0.0,0.0,129.0,"-117, -116, -115, -113, -112, -111, -114, -108, -110, -109"
7,feature_5,int64,0.0,0.0,358.0,"11, 12, 10, 86, 85, 54, -154, 55, 53, 52"
8,feature_6,int64,0.0,0.0,323.0,"56, 26, 57, -163, 27, -160, -162, -161, -164, -159"
9,feature_7,int64,0.0,0.0,389.0,"-95, -96, -103, 57, 64, -3, -171, -102, -5, 67"
10,feature_8,int64,0.0,0.0,347.0,"-40, -21, -22, -31, -231, -32, -233, -230, -232, -234"
11,feature_9,int64,0.0,0.0,399.0,"-22, -23, -24, 7, 8, 6, -25, 9, 5, -21"
12,feature_10,int64,0.0,0.0,387.0,"-242, -321, -49, -50, -53, -40, -54, -51, -48, -47"
13,feature_11,int64,0.0,0.0,384.0,"-113, -112, -214, -24, -23, -25, -212, -114, -22, -215"
14,feature_12,int64,0.0,0.0,397.0,"-68, -67, -69, -56, -66, -55, -64, -62, -53, -61"
15,feature_13,int64,0.0,0.0,329.0,"-283, -287, -83, -72, -286, -74, -71, -285, -100, -76"
16,feature_14,int64,0.0,0.0,319.0,"-283, -284, -282, -285, -281, -76, -75, -74, -73, -94"
17,feature_15,int64,0.0,0.0,327.0,"-302, -301, -303, -300, -298, -299, -304, -297, -295, -288"
18,feature_16,int64,0.0,0.0,350.0,"53, 52, 54, -214, -218, -213, 55, -215, -217, -212"
19,feature_17,int64,0.0,0.0,375.0,"-76, -75, -77, -53, -81, -80, -55, -52, -56, -58"
20,feature_18,int64,0.0,0.0,398.0,"-191, -99, -190, -100, -192, -98, 14, 13, -193, -101"
21,feature_19,int64,0.0,0.0,388.0,"-47, -46, -48, -184, -45, -44, -42, -29, -43, -35"
22,feature_20,int64,0.0,0.0,419.0,"-62, -61, -60, -29, -63, -28, -64, -59, -27, -30"
23,feature_21,int64,0.0,0.0,304.0,"-184, -180, -22, -15, -183, -14, -181, -10, -16, -11"
24,feature_22,int64,0.0,0.0,397.0,"2, -42, 21, -43, 3, 19, 20, 18, 1, 17"
25,feature_23,int64,0.0,0.0,368.0,"-63, -64, -65, -66, -62, -61, -67, 184, -68, 185"
26,feature_24,int64,0.0,0.0,304.0,"-95, -98, 111, 81, -96, 80, -97, -94, 92, -82"
27,feature_25,int64,0.0,0.0,379.0,"-34, 22, 23, -33, 24, -35, -49, 21, -206, -39"
28,feature_26,int64,0.0,0.0,338.0,"-20, -19, 48, 47, 28, 46, 45, 29, -170, 44"
29,feature_27,int64,0.0,0.0,272.0,"-157, -134, -154, -160, -156, -158, -159, -153, -161, -155"
30,feature_28,int64,0.0,0.0,278.0,"25, 9, 11, -66, 8, 10, 5, 26, -65, 14"
31,feature_29,int64,0.0,0.0,341.0,"104, 69, 68, -144, 105, -143, -145, -142, -146, -141"
32,feature_30,int64,0.0,0.0,276.0,"-116, -117, -114, -115, -113, -108, -110, -107, -112, -111"
33,feature_31,int64,0.0,0.0,334.0,"139, 136, 137, 129, 138, -105, -103, -92, -35, -102"
34,feature_32,int64,0.0,0.0,240.0,"-121, -13, -14, -9, -122, -11, -29, -15, -24, -22"
35,feature_33,int64,0.0,0.0,419.0,"5, 4, 6, 12, 7, 13, 15, 14, 16, 11"
36,feature_34,int64,0.0,0.0,243.0,"-122, -156, -155, -14, -157, -23, -129, -128, -137, -132"
37,feature_35,int64,0.0,0.0,261.0,"87, 74, 151, 156, 104, 93, 81, 141, 174, 159"
38,feature_36,int64,0.0,0.0,288.0,"-175, -174, -163, -172, -173, -164, -167, -171, -168, -166"
39,feature_37,int64,0.0,0.0,324.0,"73, 4, -153, -152, 3, 2, 64, 5, -149, -118"
40,feature_38,int64,0.0,0.0,217.0,"-145, -144, -146, -31, -25, -26, -20, -27, -28, -143"
41,feature_39,int64,0.0,0.0,322.0,"70, 39, 69, -128, -131, 38, 95, -109, 71, 36"
42,feature_40,int64,0.0,0.0,231.0,"-172, -178, -48, -176, -179, -184, -43, -177, -44, 79"
43,feature_41,int64,0.0,0.0,329.0,"-10, -21, 26, 27, -137, -11, -9, -138, 88, 101"
44,feature_42,int64,0.0,0.0,407.0,"-29, -27, -28, -30, -52, -26, -53, -25, -31, -51"
45,feature_43,int64,0.0,0.0,328.0,"-289, -55, -56, -54, -57, -59, -58, -60, -61, -62"
46,feature_44,int64,0.0,0.0,340.0,"-280, -279, -82, -79, -81, -84, -80, -91, -78, -83"
47,feature_45,int64,0.0,0.0,392.0,"-331, -329, -328, -330, -327, -332, -105, -326, -107, -108"
48,feature_46,int64,0.0,0.0,265.0,"-152, -151, -153, -150, -137, -97, -96, -154, -138, -98"
49,feature_47,int64,0.0,0.0,411.0,"-7, -6, -72, -63, -71, -67, -70, -62, -74, -61"
50,feature_48,int64,0.0,0.0,381.0,"-139, 31, 28, -140, 29, -141, -23, 26, -109, -142"
51,feature_49,int64,0.0,0.0,374.0,"-2, -103, -19, -102, -18, -20, -101, -22, -21, -3"
52,feature_50,int64,0.0,0.0,390.0,"-73, -72, -71, -74, -141, -142, -70, -139, -144, -143"
53,feature_51,int64,0.0,0.0,329.0,"-26, -27, -199, -200, -197, -198, -196, -18, -201, -17"
54,feature_52,int64,0.0,0.0,333.0,"-1, -12, 0, -11, -200, -197, -195, -198, -199, 1"
55,feature_53,int64,0.0,0.0,389.0,"-136, -135, -138, -134, -131, -137, 58, -132, -133, 67"
56,feature_54,int64,0.0,0.0,313.0,"148, -51, 107, 108, 163, -50, 147, -52, 149, 109"
57,feature_55,int64,0.0,0.0,415.0,"1, 2, 3, -61, -35, -59, -37, -36, -95, -96"
58,feature_56,int64,0.0,0.0,363.0,"93, 40, -160, 41, 92, 94, 99, -159, -161, 100"
59,feature_57,int64,0.0,0.0,271.0,"-177, -171, -170, -139, -140, -172, -141, -138, -150, -143"
60,feature_58,int64,0.0,0.0,302.0,"35, 0, 36, 3, 9, -16, -20, 87, 10, 1"
61,feature_59,int64,0.0,0.0,412.0,"40, 10, 41, 11, 9, 12, 8, 51, -167, 27"
62,feature_60,int64,0.0,0.0,254.0,"-101, -100, -98, -97, -96, -102, -99, -88, 196, -8"
63,feature_61,int64,0.0,0.0,305.0,"-195, 65, 83, 62, -187, 64, -194, 63, 66, 24"
64,feature_62,int64,0.0,0.0,205.0,"28, -35, -37, 23, 24, 31, 16, 27, -34, -38"
65,feature_63,int64,0.0,0.0,388.0,"-188, -186, 110, -187, 111, -185, -189, 109, 108, 112"
66,feature_64,int64,0.0,0.0,251.0,"-134, -145, -146, -12, -144, -11, -133, -13, -10, 97"
67,feature_65,int64,0.0,0.0,206.0,"59, 58, 60, 55, 57, 54, 56, 73, 80, 75"
68,feature_66,int64,0.0,0.0,181.0,"-166, -167, -165, -164, -161, -163, -160, -159, -162, -152"
69,feature_67,int64,0.0,0.0,287.0,"-40, 16, -83, 17, -30, -31, -39, 15, -84, -32"
70,feature_68,int64,0.0,0.0,314.0,"-133, -132, 78, 92, 31, 79, 29, 75, 77, 30"
71,feature_69,int64,0.0,0.0,287.0,"14, 13, -28, -35, -25, -41, -54, -55, 12, -58"
72,feature_70,int64,0.0,0.0,224.0,"-156, -148, -38, -155, -31, -162, -169, -39, -66, -163"
73,feature_71,int64,0.0,0.0,224.0,"-150, -149, -38, -146, -36, -33, -148, -37, -147, -39"
74,feature_72,int64,0.0,0.0,429.0,"-164, -163, -47, -48, -75, -165, -50, -71, -49, -74"
75,feature_73,int64,0.0,0.0,386.0,"-247, -246, -248, -62, -191, -245, -192, -60, -194, -64"
76,feature_74,int64,0.0,0.0,380.0,"-220, -96, -95, -218, -219, -97, -53, -67, -93, -92"
77,feature_75,int64,0.0,0.0,113.0,"-181, -182, -180, -179, -183, -184, -178, -177, -176, -185"
78,feature_76,int64,0.0,0.0,338.0,"0, 1, -32, -31, 8, -242, -243, 4, -30, -244"
79,feature_77,int64,0.0,0.0,392.0,"-218, -26, -28, -24, -25, -29, -23, -33, -22, -27"
80,feature_78,int64,0.0,0.0,347.0,"-105, -215, -216, -9, -10, -106, -8, -11, -13, -79"
81,feature_79,int64,0.0,0.0,338.0,"63, 62, 64, -177, -176, -166, 66, 61, 65, 60"
82,feature_80,int64,0.0,0.0,397.0,"-14, -13, -19, -20, -15, -17, -12, -18, -16, -209"
83,feature_81,int64,0.0,0.0,294.0,"11, -170, 13, 12, 14, -168, -171, -173, -169, -167"
84,feature_82,int64,0.0,0.0,368.0,"-32, -117, -116, -44, -43, -45, -46, -47, -48, -49"
85,feature_83,int64,0.0,0.0,361.0,"194, -40, -41, -39, 110, -81, -42, 111, 109, 105"
86,feature_84,int64,0.0,0.0,368.0,"17, 16, 0, 1, 18, -1, 43, 2, -5, -178"
87,feature_85,int64,0.0,0.0,320.0,"16, 23, 17, -190, -191, 22, -189, 24, -194, -192"
88,feature_86,int64,0.0,0.0,307.0,"-157, -82, 105, -158, 103, -191, -85, -89, 102, -156"
89,feature_87,int64,0.0,0.0,347.0,"-168, -167, -166, -52, -51, -169, -48, -49, -170, -174"
90,feature_88,int64,0.0,0.0,258.0,"-75, -7, -8, 29, 30, -74, -76, 8, -72, 7"
91,feature_89,int64,0.0,0.0,398.0,"134, 133, -146, -147, 83, -145, 82, -148, 81, 135"
92,feature_90,int64,0.0,0.0,331.0,"-202, -201, -196, -200, -195, -199, 32, 167, 33, -194"
93,feature_91,int64,0.0,0.0,247.0,"137, 23, 131, 133, 25, 62, 21, 34, 61, 24"
94,feature_92,int64,0.0,0.0,233.0,"-106, -119, -120, -115, -118, -105, -117, -116, 17, 16"
95,feature_93,int64,0.0,0.0,398.0,"-48, -92, -47, -46, -108, -111, -45, -107, -110, -99"
96,feature_94,int64,0.0,0.0,199.0,"9, -17, 3, 7, -23, -16, -25, -29, 28, -18"
97,feature_95,int64,0.0,0.0,333.0,"234, -50, -53, -55, -52, -54, -51, -49, 235, -56"
98,feature_96,int64,0.0,0.0,340.0,"-167, 126, -166, -183, -168, -182, -43, -188, -189, -184"
99,feature_97,int64,0.0,0.0,354.0,"31, 33, 32, -183, -184, 34, -181, -182, -187, -186"
100,feature_98,int64,0.0,0.0,181.0,"-156, -154, -155, -143, -24, -152, -153, -25, -23, -150"
101,feature_99,int64,0.0,0.0,331.0,"76, 80, 75, 79, -149, -148, -150, -151, -145, 81"
102,feature_100,int64,0.0,0.0,255.0,"-207, -206, -194, -61, -195, 89, -190, -205, 88, -62"
103,feature_101,int64,0.0,0.0,255.0,"130, 135, 134, 133, 131, 144, 136, -5, 143, 141"
104,feature_102,int64,0.0,0.0,396.0,"-259, -258, -39, -260, -257, -40, -38, -37, -61, -53"
105,feature_103,int64,0.0,0.0,337.0,"-53, -54, -52, -55, -293, -50, -284, -49, -51, -56"
106,feature_104,int64,0.0,0.0,277.0,"-302, -109, -110, -92, -89, -91, -301, -90, -88, -84"
107,feature_105,int64,0.0,0.0,382.0,"-264, -265, -262, -195, -54, -53, -266, -56, -49, -61"
108,feature_106,int64,0.0,0.0,319.0,"-167, -166, -169, -168, -175, -165, -181, -174, -171, -173"
109,feature_107,int64,0.0,0.0,388.0,"-120, -14, -119, -15, -16, -13, -78, -118, -17, -121"
110,feature_108,int64,0.0,0.0,328.0,"-245, -246, 2, -244, 1, 0, -186, -1, -63, -65"
111,feature_109,int64,0.0,0.0,268.0,"-282, -281, -249, -101, -233, -91, -100, -105, -99, -90"
112,feature_110,int64,0.0,0.0,292.0,"-243, -242, -55, -56, -57, -54, -53, -241, -52, -49"
113,feature_111,int64,0.0,0.0,406.0,"2, 3, -59, -58, 6, 1, 4, 7, 5, -60"
114,feature_112,int64,0.0,0.0,368.0,"-2, -28, -1, -27, 27, 28, 26, 29, 25, -207"
115,feature_113,int64,0.0,0.0,337.0,"-24, -3, -2, -23, -198, -199, -200, -197, -196, 24"
116,feature_114,int64,0.0,0.0,402.0,"24, -1, 23, 25, 53, 54, 1, 55, 52, 22"
117,feature_115,int64,0.0,0.0,406.0,"60, 61, -18, -15, -19, -9, -12, -11, -16, -13"
118,feature_116,int64,0.0,0.0,351.0,"162, 112, -93, -92, -94, -91, -90, 160, 111, 163"
119,feature_117,int64,0.0,0.0,354.0,"37, 36, 22, 38, 23, -202, -205, -199, -201, -200"
120,feature_118,int64,0.0,0.0,352.0,"84, 85, 86, -179, 7, 6, 83, -180, 8, -178"
121,feature_119,int64,0.0,0.0,347.0,"-189, 24, 26, 25, -188, -190, -123, 23, 22, -187"
122,feature_120,int64,0.0,0.0,299.0,"-114, -115, -113, 81, 82, 90, -112, -116, 89, 91"
123,feature_121,int64,0.0,0.0,314.0,"149, 72, -68, -66, 73, 141, -62, -67, 136, -55"
124,feature_122,int64,0.0,0.0,353.0,"114, 131, 115, 130, -101, -102, 113, 116, -81, -70"
125,feature_123,int64,0.0,0.0,277.0,"54, 50, 51, 53, 48, -108, 49, 29, 52, 30"
126,feature_124,int64,0.0,0.0,327.0,"-132, -133, -127, -129, -130, -131, -134, -126, -135, -136"
127,feature_125,int64,0.0,0.0,246.0,"65, 64, 59, 54, 55, 63, 68, 67, 56, 5"
128,feature_126,int64,0.0,0.0,435.0,"41, -23, -24, -20, -26, -21, -25, -27, -39, -19"
129,feature_127,int64,0.0,0.0,405.0,"81, 58, 80, 57, 56, 91, 90, 88, 92, 59"
130,feature_128,int64,0.0,0.0,415.0,"14, 15, 13, 16, -45, -64, -98, 12, -67, -71"
131,feature_129,int64,0.0,0.0,253.0,"-187, -188, -185, -186, -184, -23, -24, -51, -22, -52"
132,feature_130,int64,0.0,0.0,235.0,"42, 30, 25, 35, 43, 32, 41, 31, -88, 24"
133,feature_131,int64,0.0,0.0,320.0,"-138, -139, -117, -116, 42, -121, -110, 78, -136, 81"
134,feature_132,int64,0.0,0.0,416.0,"-65, -64, -63, -90, -86, -74, -76, -89, -73, -87"
135,feature_133,int64,0.0,0.0,393.0,"-128, -165, -126, -163, -82, -124, -162, -83, -84, -71"
136,feature_134,int64,0.0,0.0,394.0,"-206, -32, -37, -38, -207, -36, -35, -33, -102, -34"
137,feature_135,int64,0.0,0.0,267.0,"-20, -92, -23, -21, -27, -22, -26, -28, -93, -16"
138,feature_136,int64,0.0,0.0,345.0,"46, 45, 53, -174, 54, 47, -175, 38, -173, 51"
139,feature_137,int64,0.0,0.0,301.0,"-116, 127, -48, -33, -118, -44, -23, -49, -32, 126"
140,feature_138,int64,0.0,0.0,396.0,"-3, -4, -18, -19, -2, -21, -17, -16, -20, -207"
141,feature_139,int64,0.0,0.0,414.0,"-33, -34, -35, -32, -55, -37, -53, -54, -56, -36"
142,feature_140,int64,0.0,0.0,386.0,"-27, -37, -28, -26, -36, -94, -64, -95, -93, -63"
143,feature_141,int64,0.0,0.0,303.0,"76, 5, -138, -139, -136, 4, 79, 3, 78, -124"
144,feature_142,int64,0.0,0.0,331.0,"79, 49, -152, -154, -153, 50, 80, -150, -149, 48"
145,feature_143,int64,0.0,0.0,311.0,"61, -168, -169, 16, -166, -170, 17, -167, 24, 60"
146,feature_144,int64,0.0,0.0,150.0,"-178, -177, -175, -176, -140, -163, -139, -174, -141, -165"
147,feature_145,int64,0.0,0.0,247.0,"-103, -102, -104, -101, -105, -100, -99, -97, -95, -96"
148,feature_146,int64,0.0,0.0,144.0,"-120, -119, -121, -122, -118, -123, -117, -124, -116, -115"
149,feature_147,int64,0.0,0.0,294.0,"-32, -35, -21, -36, -34, 99, -33, -63, -42, 100"
150,feature_148,int64,0.0,0.0,295.0,"-35, 65, -107, -51, 94, 108, -66, -36, -34, 109"
151,feature_149,int64,0.0,0.0,329.0,"40, 53, -142, 41, 52, -137, 39, 16, -143, -136"
152,feature_150,int64,0.0,0.0,197.0,"-26, -25, -97, -112, 123, -98, -99, -96, -104, -105"
153,feature_151,int64,0.0,0.0,184.0,"-125, -124, -122, -126, -123, -121, -120, 3, 2, -35"
154,feature_152,int64,0.0,0.0,151.0,"-112, -113, 9, 8, -111, -114, 10, 35, -110, 36"
155,feature_153,int64,0.0,0.0,257.0,"-169, -168, -170, -41, -46, -42, -47, -167, -40, -55"
156,feature_154,int64,0.0,0.0,323.0,"127, 124, 123, 126, 125, 121, 2, 117, -66, 122"
157,feature_155,int64,0.0,0.0,286.0,"-195, -196, -194, 16, 32, -11, 31, -193, -192, -10"
158,feature_156,int64,0.0,0.0,258.0,"-238, -237, -236, -235, -239, -240, -234, -233, -241, -243"
159,feature_157,int64,0.0,0.0,398.0,"-303, -300, -302, -73, -301, -79, -306, -298, -264, -258"
160,feature_158,int64,0.0,0.0,386.0,"-206, -209, -208, -207, -210, -205, -211, 58, 56, -204"
161,feature_159,int64,0.0,0.0,278.0,"-21, -20, -14, -32, -129, -130, -8, -131, 9, -9"
162,feature_160,int64,0.0,0.0,354.0,"154, 150, 153, 155, 147, 149, 30, 151, 127, -41"
163,feature_161,int64,0.0,0.0,281.0,"129, 125, 106, 107, 131, 128, 100, 8, 112, 113"
164,feature_162,int64,0.0,0.0,292.0,"159, 172, 202, 175, 176, 162, 187, 196, 193, 215"
165,feature_163,int64,0.0,0.0,172.0,"-66, -73, -72, -68, -51, -44, -70, -41, -60, -54"
166,feature_164,int64,0.0,0.0,352.0,"-116, -117, -162, -145, -150, -127, -154, -147, -164, -148"
167,feature_165,int64,0.0,0.0,385.0,"-6, -5, 118, 119, -19, -7, 130, 120, -18, -15"

In [6]:
# Numeric Feature Statistics
numeric_stats

              count        mean         std    min    max
feature_0    6598.0   58.945135   53.249007  -31.0  292.0
feature_1    6598.0 -119.128524   90.813375 -199.0   95.0
feature_2    6598.0  -73.146560   67.956235 -167.0   81.0
feature_3    6598.0   -0.628372   80.444617 -114.0  161.0
feature_4    6598.0 -103.533495   64.387559 -118.0  325.0
feature_5    6598.0   18.359806   80.593655 -183.0  200.0
feature_6    6598.0  -14.108821  115.315673 -171.0  220.0
feature_7    6598.0   -1.858290   90.372537 -225.0  320.0
feature_8    6598.0  -86.003031  108.326676 -245.0  147.0
feature_9    6598.0  -44.495756   72.088903 -286.0  231.0
feature_10   6598.0 -119.456502  108.911397 -328.0  176.0
feature_11   6598.0  -84.929221   79.541410 -321.0  184.0
feature_12   6598.0  -61.911185   61.444281 -305.0  195.0
feature_13   6598.0 -127.935283  101.191126 -342.0  158.0
feature_14   6598.0 -123.005153   98.009158 -294.0  172.0
feature_15   6598.0 -265.690967   70.647329 -327.0   80.0
feature_16   6598.0  -53.415732  117.237608 -224.0  138.0
feature_17   6598.0  -67.741285   61.403085 -308.0  189.0
feature_18   6598.0  -52.352531   82.503477 -286.0  225.0
feature_19   6598.0  -44.902698   79.304489 -252.0  227.0
feature_20   6598.0  -75.645953   75.187995 -295.0  194.0
feature_21   6598.0  -55.783419  101.908604 -185.0  190.0
feature_22   6598.0  -61.619127   94.524709 -253.0  213.0
feature_23   6598.0   72.506062  123.334433  -76.0  317.0
feature_24   6598.0   32.285238  108.105908 -100.0  277.0
feature_25   6598.0  -69.659139  101.325550 -242.0  183.0
feature_26   6598.0  -15.361018   91.621335 -205.0  164.0
feature_27   6598.0 -102.665959   73.778232 -166.0  145.0
feature_28   6598.0    8.520764   63.484770 -142.0  174.0
feature_29   6598.0   12.553956  126.086157 -162.0  266.0
feature_30   6598.0  -82.314186   80.225924 -117.0  309.0
feature_31   6598.0   25.436193  106.627993 -143.0  310.0
feature_32   6598.0  -34.503183   57.816952 -139.0  207.0
feature_33   6598.0  -78.915732  118.201270 -279.0  160.0
feature_34   6598.0  -73.199000   75.350809 -160.0  220.0
feature_35   6598.0  115.882995   57.070192   -7.0  324.0
feature_36   6598.0 -115.562746  104.682519 -175.0  147.0
feature_37   6598.0   -7.853289   85.732778 -190.0  187.0
feature_38   6598.0  -75.578509   70.534415 -148.0  107.0
feature_39   6598.0   12.700667   80.750001 -180.0  194.0
feature_40   6598.0  -94.105335   84.554740 -188.0   90.0
feature_41   6598.0   24.210821   91.727678 -150.0  367.0
feature_42   6598.0  -45.615186   60.306330 -295.0  225.0
feature_43   6598.0 -121.602758  111.901894 -343.0  198.0
feature_44   6598.0 -125.547439   89.969244 -310.0  147.0
feature_45   6598.0 -170.321461  100.722635 -340.0  161.0
feature_46   6598.0  -95.759018   66.723054 -159.0  110.0
feature_47   6598.0  -87.315399   82.392698 -290.0  179.0
feature_48   6598.0  -24.237951   81.577192 -265.0  273.0
feature_49   6598.0  -54.001819   68.294161 -279.0  215.0
feature_50   6598.0  -91.248863   66.227603 -326.0  172.0
feature_51   6598.0  -67.800697  103.574857 -206.0  177.0
feature_52   6598.0  -55.654744  104.238710 -206.0  169.0
feature_53   6598.0    7.128221   93.704299 -147.0  335.0
feature_54   6598.0   80.092452   84.223115 -112.0  269.0
feature_55   6598.0  -62.756896   67.330179 -279.0  214.0
feature_56   6598.0    5.114580  112.618475 -170.0  229.0
feature_57   6598.0 -112.445893   79.650938 -178.0  113.0
feature_58   6598.0   26.498030   61.708787 -172.0  200.0
feature_59   6598.0  -36.375417  101.679670 -250.0  200.0
feature_60   6598.0  -23.988027   96.857409 -102.0  254.0
feature_61   6598.0  -54.988481  119.688552 -196.0  180.0
feature_62   6598.0    1.634435   48.537040 -100.0  284.0
feature_63   6598.0  -17.274022  131.326710 -195.0  225.0
feature_64   6598.0  -61.321916   85.130894 -165.0  112.0
feature_65   6598.0   79.316763   55.849966   -9.0  315.0
feature_66   6598.0 -155.735677   48.084476 -167.0  234.0
feature_67   6598.0  -16.943619   59.781700 -195.0  149.0
feature_68   6598.0  -13.007730   99.930285 -134.0  232.0
feature_69   6598.0   -6.271749   59.108877 -191.0  158.0
feature_70   6598.0  -84.647772   76.688701 -174.0   86.0
feature_71   6598.0  -82.482722   68.045335 -152.0   99.0
feature_72   6598.0  -99.559867   92.497523 -324.0  181.0
feature_73   6598.0 -104.820855   86.984078 -333.0  172.0
feature_74   6598.0  -72.398151   82.839247 -274.0  203.0
feature_75   6598.0 -175.827372   13.975250 -195.0   21.0
feature_76   6598.0  -83.528190  120.603288 -259.0  156.0
feature_77   6598.0  -92.815247  104.123379 -313.0  235.0
feature_78   6598.0  -73.518036   82.957802 -306.0  193.0
feature_79   6598.0   -3.541982  107.300603 -202.0  309.0
feature_80   6598.0  -70.569567   93.915668 -255.0  198.0
feature_81   6598.0  -34.470294  107.524802 -175.0  201.0
feature_82   6598.0  -74.743407   71.020966 -299.0  175.0
feature_83   6598.0   67.787208   96.733880  -98.0  273.0
feature_84   6598.0  -44.386935  103.820817 -220.0  193.0
feature_85   6598.0  -41.463474  114.975636 -203.0  194.0
feature_86   6598.0  -62.579418   84.797934 -207.0  109.0
feature_87   6598.0 -100.544559   78.672916 -213.0  172.0
feature_88   6598.0    2.058199   64.616847 -111.0  152.0
feature_89   6598.0   30.591846  123.957652 -157.0  269.0
feature_90   6598.0 -111.898151  111.033244 -202.0  235.0
feature_91   6598.0   85.028342   67.810941  -16.0  306.0
feature_92   6598.0  -39.855865   83.356713 -125.0  223.0
feature_93   6598.0 -118.955744   84.928006 -328.0  184.0
feature_94   6598.0   -6.052440   43.393333 -119.0  238.0
feature_95   6598.0   82.377690  113.737566  -69.0  347.0
feature_96   6598.0  -50.006517   99.398274 -191.0  165.0
feature_97   6598.0  -32.127008  110.107389 -190.0  203.0
feature_98   6598.0  -92.595938   64.245317 -157.0   40.0
feature_99   6598.0   13.029100  106.169467 -156.0  237.0
feature_100  6598.0 -106.344195   91.362072 -209.0   91.0
feature_101  6598.0  110.281600   73.623469  -33.0  348.0
feature_102  6598.0 -102.374204   97.065169 -299.0  173.0
feature_103  6598.0 -120.374659  109.257008 -324.0  191.0
feature_104  6598.0 -135.487572  101.510096 -319.0  154.0
feature_105  6598.0 -103.310700   90.044170 -284.0  212.0
feature_106  6598.0 -133.560473   69.825312 -200.0  159.0
feature_107  6598.0 -108.788724   86.429935 -292.0  167.0
feature_108  6598.0  -78.686875   98.082819 -249.0  200.0
feature_109  6598.0 -130.175053   85.835828 -291.0  141.0
feature_110  6598.0  -84.534101   94.897728 -250.0  209.0
feature_111  6598.0  -60.493786   87.738542 -266.0  214.0
feature_112  6598.0  -61.240376  103.003485 -224.0  194.0
feature_113  6598.0  -56.862989  102.903701 -204.0  180.0
feature_114  6598.0  -40.597908   98.182931 -250.0  216.0
feature_115  6598.0   -9.352380   66.273053 -257.0  253.0
feature_116  6598.0   61.939527  125.069996 -103.0  315.0
feature_117  6598.0  -42.358745  110.701484 -212.0  156.0
feature_118  6598.0  -17.505305  120.421611 -196.0  209.0
feature_119  6598.0  -52.381631   99.621142 -201.0  152.0
feature_120  6598.0   21.712337  114.037722 -121.0  267.0
feature_121  6598.0   63.267505   86.122325 -117.0  258.0
feature_122  6598.0   56.299939  100.990614 -129.0  276.0
feature_123  6598.0   -0.655199   69.524695 -127.0  227.0
feature_124  6598.0   -0.861928  113.150553 -144.0  299.0
feature_125  6598.0   51.431040   47.687834  -69.0  308.0
feature_126  6598.0  -46.587754   86.065208 -286.0  219.0
feature_127  6598.0  -19.476811  130.607205 -221.0  241.0
feature_128  6598.0  -68.070627   70.016546 -307.0  206.0
feature_129  6598.0  -94.963474   98.100733 -189.0  122.0
feature_130  6598.0    2.993786   60.633027 -123.0  281.0
feature_131  6598.0  -36.652774   84.316386 -140.0  255.0
feature_132  6598.0  -79.191422   61.733776 -319.0  176.0
feature_133  6598.0  -90.778266   68.098995 -338.0  169.0
feature_134  6598.0  -95.868142   87.253395 -336.0  219.0
feature_135  6598.0  -28.259473   61.664300 -196.0  125.0
feature_136  6598.0   -8.521067   97.997434 -197.0  186.0
feature_137  6598.0  -37.599121   77.580190 -199.0  130.0
feature_138  6598.0  -67.789330   94.753428 -243.0  202.0
feature_139  6598.0  -51.976508   64.344336 -283.0  203.0
feature_140  6598.0  -65.693089   69.094605 -290.0  188.0
feature_141  6598.0   -0.443165   82.410293 -185.0  184.0
feature_142  6598.0    1.331464  103.746483 -157.0  239.0
feature_143  6598.0  -21.754319  103.113954 -171.0  208.0
feature_144  6598.0 -165.748863   54.087579 -179.0  213.0
feature_145  6598.0  -87.364050   51.177725 -106.0  261.0
feature_146  6598.0 -113.114580   21.463582 -136.0  172.0
feature_147  6598.0  -18.523644   63.048333 -200.0  130.0
feature_148  6598.0  -41.386481   73.864481 -213.0  117.0
feature_149  6598.0    8.755077   83.274158 -190.0  185.0
feature_150  6598.0  -55.026069   60.100098 -140.0  244.0
feature_151  6598.0  -61.105335   70.788743 -128.0  153.0
feature_152  6598.0  -54.810397   67.538140 -114.0  211.0
feature_153  6598.0  -76.831161   76.908685 -173.0  120.0
feature_154  6598.0   33.209912   98.511502 -143.0  379.0
feature_155  6598.0  -61.212337   97.547356 -198.0  153.0
feature_156  6598.0 -210.975447   83.710890 -257.0  145.0
feature_157  6598.0 -184.798272  107.819514 -328.0   94.0
feature_158  6598.0  -75.795696  127.861271 -219.0  179.0
feature_159  6598.0  -26.073204   69.727964 -136.0  192.0
feature_160  6598.0   64.616702  100.861935 -120.0  411.0
feature_161  6598.0  112.037739   72.835040  -69.0  355.0
feature_162  6598.0  201.760230   59.526751   73.0  625.0
feature_163  6598.0  -47.488330   55.069365 -289.0  295.0
feature_164  6598.0 -150.259927   76.019023 -428.0  168.0
feature_165  6598.0   41.770233   94.116085 -471.0  367.0

In [7]:
# Categorical Feature Statistics
cat_stats

                           value  count    pct
column        rank
class         1         non-musk   5581  84.59
              2             musk   1017  15.41
molecule_name 1     c394ef9107ce   1044  15.82
              2     a470dec69277   1010  15.31
              3     d2c2629403c4    911  13.81
              4     6c75e31d113c    383   5.80
              5     a24523edbb05    344   5.21

In [8]:
# Target Distribution
target_df

          count    pct
class
non-musk   5581  84.59
musk       1017  15.41

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
    group_labels=task_mold.group_labels,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default IID splits",
    splits=splits
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to musk/versions/019dd49e-4009-7822-a3a5-bb615a182e0f
019dd49e-4009-7822-a3a5-bb615a182e0f
7bdff1ae335fde55bc681ed16627ff0e0fa2471272e9b6636943c2e4d2727906