### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="amex_non_iid_1m",
    version_from_unique_name="amex_non_iid",
    version_comment="""
We randomly sub-sample to 1.25 million rows such that train and test splits are roughly 1M and 250k rows respectively.
""",
    # Same as amex_non_iid.ipynb
    dataset_year="2022",
    domain_str="finance",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/amex-default-prediction/",
    download_description="""
We start with the preprocessed version of the dataset in Parquet format provided by
the user 'raddar' on Kaggle. At the root of this project, I ran on linux with
the kaggle CLI installed and authenticated:

kaggle datasets download -d raddar/amex-data-integer-dtypes-parquet-format --unzip -p amex_dataset && rm amex_dataset/test.parquet
kaggle competitions download -c amex-default-prediction -f train_labels.csv -p amex_dataset && cd amex_dataset && unzip train_labels.csv.zip train_labels.csv && rm train_labels.csv.zip && cd ..
mkdir -p local-data-warehouse/amex_non_iid && mv amex_dataset/* local-data-warehouse/amex_non_iid/ && rm -rf amex_dataset
""",
    # References
    academic_reference_bibtex="""@misc{howard2022amex,
  author       = {Howard, Addison and AritraAmex and Xu, Di and Vashani, Hossein and inversion and Negin and Dane, Sohier},
  title        = {American Express -- Default Prediction},
  year         = {2022},
  howpublished = {Kaggle Competition},
  url          = {https://kaggle.com/competitions/amex-default-prediction},
  note         = {Accessed via Kaggle}
}
""",
    academic_reference_bibtex_key="howard2022amex",
    license="Kaggle Competition License",
    data_tags=["Non-IID", "Grouped", "Anonymized"],
    curation_comments="""
We start with the raw data from Kaggle and do not apply any further preprocessing to simulate a pipeline that can handle raw non-IID grouped data.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="target",
    problem_type="binary_classification",
    objective_metric_name="amex_metric",
    stratify_on="target",
    group_on="customer_ID",
    group_time_on="S_2",
    group_labels="per_group",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_parquet(dataset_mold.path / "train.parquet")
print("Loaded data shape:", df.shape)

df.S_2 = pd.to_datetime(df.S_2)
df = df.sort_values(["customer_ID", "S_2"])

cat_features = [
    "B_30",
    "B_38",
    "D_114",
    "D_116",
    "D_117",
    "D_120",
    "D_126",
    "D_63",
    "D_64",
    "D_66",
    "D_68",
]
df = df.set_index("customer_ID")
# Add labels
targets = pd.read_csv(dataset_mold.path / "train_labels.csv")
targets = targets.set_index("customer_ID")
df = df.merge(targets, left_index=True, right_index=True, how="left")
df.target = df.target.astype("int8")
del targets

df[cat_features] = df[cat_features].astype("category")

df = df.reset_index().reset_index(drop=True)
df["customer_ID"] = df["customer_ID"].astype("category")

Loaded data shape: (5531451, 190)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False,
    duplicate_column_check=False,
)

#### Dataset Overview
Rows: 5,531,451
Columns: 191
Use sampling: True (sample size: 553,145)
Get missing and unique counts per column...

missing/unique per-col:   0%|          | 0/191 [00:00<?, ?it/s]

Get example values per column...

examples per-col:   0%|          | 0/191 [00:00<?, ?it/s]

Get numeric feature statistics...

numeric stats:   0%|          | 0/178 [00:00<?, ?it/s]

Get cat stats...

cat stats:   0%|          | 0/13 [00:00<?, ?it/s]

Get target stats...
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['B_1', 'B_37', 'B_14', 'B_11', 'B_40', 'B_23', 'B_25', 'S_5', 'B_28', 'B_3']
Rows remaining as candidates after top-10 filter: 0 (of 5,531,451)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,D_42,D_43,D_44,B_4,D_45,B_5,R_2,D_46,D_47,D_48,D_49,B_6,B_7,B_8,D_50,D_51,B_9,R_3,D_52,P_3,B_10,D_53,S_5,B_11,S_6,D_54,R_4,S_7,B_12,S_8,D_55,D_56,B_13,R_5,D_58,S_9,B_14,D_59,D_60,D_61,B_15,S_11,D_62,D_63,D_64,D_65,B_16,B_17,B_18,B_19,D_66,B_20,D_68,S_12,R_6,S_13,B_21,D_69,B_22,D_70,D_71,D_72,S_15,B_23,D_73,P_4,D_74,D_75,D_76,B_24,R_7,D_77,B_25,B_26,D_78,D_79,R_8,R_9,S_16,D_80,R_10,R_11,B_27,D_81,D_82,S_17,R_12,B_28,R_13,D_83,R_14,R_15,D_84,R_16,B_29,B_30,S_18,D_86,D_87,R_17,R_18,D_88,B_31,S_19,R_19,B_32,S_20,R_20,R_21,B_33,D_89,R_22,R_23,D_91,D_92,D_93,D_94,R_24,R_25,D_96,S_22,S_23,S_24,S_25,S_26,D_102,D_103,D_104,D_105,D_106,D_107,B_36,B_37,R_26,R_27,B_38,D_108,D_109,D_110,D_111,B_39,D_112,B_40,S_27,D_113,D_114,D_115,D_116,D_117,D_118,D_119,D_120,D_121,D_122,D_123,D_124,D_125,D_126,D_127,D_128,D_129,B_41,B_42,D_130,D_131,D_132,D_133,R_28,D_134,D_135,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145,target
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a,2017-03-09,0.938469,0,0.008724,1.006838,0.009228,0.124035,0.0,0.004709,NaN,NaN,0,6,0.708906,0.170600,0,0.358587,0.525351,0.255736,-1,0.063902,0.059416,0.0,0.148698,4,0.008207,0,0.207334,0.736463,0.096219,NaN,0.023381,0.002768,0,1.0,0,0.161345,0.148266,2896,0.354596,0.152025,0.118075,0,0.158612,0.065728,0.018385,8,0.199617,0.308233,0.016361,15,0.091071,0,0,0,0,NaN,0.652984,0,-1,0,6,0.272008,0.008363,524,0.002644,0.009013,0,0,0.119403,0,4,0.050882,NaN,0.0,1,1,NaN,0.004327,0.0,NaN,0.007729,0.000272,0,0,0,-1,0.002271,0,0,0,0.002310,0,1,0.008033,1.0,0.084683,0,0,0.0,0,0,0,NaN,0,0,0,-1,0,0,NaN,1,0.002537,0,0,0,0,0,1,0,0,0,3,1,0,0,0,0,0,0.894090,0.135561,0.911191,0.974539,0.001243,0.766688,1,1.004587,0.893734,-1,2,0.009968,0.004572,-1,1.008949,2,-1,0,NaN,-1,NaN,1.0,0.210060,0.676922,0,1,0.238250,0,5,0.232120,0.236266,0,0.702280,3,0,16,0,2,1,1.007819,1,0,NaN,0.0,0.0,NaN,0.004345,0,NaN,-1,-1,-1,-1,0,0,0.0,NaN,0,0.000610,0,0
1,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a,2017-04-07,0.936665,0,0.004923,1.000653,0.006151,0.126750,0.0,0.002714,NaN,NaN,0,5,0.712795,0.113239,0,0.353630,0.521311,0.223329,-1,0.065261,0.057744,0.0,0.149723,4,0.008373,0,0.202778,0.720886,0.099804,NaN,0.030599,0.002749,0,1.0,0,0.140951,0.143530,2896,0.326757,0.156201,0.118737,0,0.148459,0.093935,0.013035,8,0.151387,0.265026,0.017688,15,0.086805,0,0,0,0,NaN,0.647093,0,-1,0,6,0.188970,0.004030,524,0.004193,0.007842,0,0,0.140611,0,4,0.040469,NaN,0.0,1,1,NaN,0.004203,0.0,NaN,0.001864,0.000979,0,0,0,-1,0.009810,0,0,0,0.001327,0,1,0.000760,1.0,0.081843,0,0,0.0,0,0,0,NaN,0,0,0,-1,0,0,NaN,1,0.008427,0,0,0,0,0,1,0,0,0,3,1,0,0,0,0,0,0.902135,0.136333,0.919876,0.975625,0.004561,0.786007,1,1.004118,0.906841,-1,2,0.003921,0.004654,-1,1.003205,2,-1,0,NaN,-1,NaN,1.0,0.184093,0.822281,0,1,0.247217,0,5,0.243532,0.241885,0,0.707017,3,0,16,0,2,1,1.004333,1,0,NaN,0.0,0.0,NaN,0.007495,0,NaN,-1,-1,-1,-1,0,0,0.0,NaN,0,0.005492,0,0
2,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a,2017-05-28,0.954180,3,0.021655,1.009672,0.006815,0.123977,0.0,0.009423,NaN,NaN,0,5,0.720884,0.060492,0,0.334650,0.524568,0.189424,-1,0.066982,0.056647,0.0,0.151955,4,0.009355,0,0.206629,0.738044,0.134073,NaN,0.048367,0.010077,0,1.0,0,0.112229,0.137014,3166,0.304124,0.153795,0.114534,0,0.139504,0.084757,0.056653,8,0.305883,0.212165,0.063955,15,0.094001,0,0,0,0,NaN,0.645819,0,-1,0,6,0.495308,0.006838,702,0.001337,0.006025,0,0,0.075868,0,4,0.047454,NaN,0.0,1,1,NaN,0.001782,0.0,NaN,0.005419,0.006149,0,0,0,-1,0.009362,0,0,0,0.007624,0,1,0.004056,1.0,0.081954,0,0,0.0,0,0,0,NaN,0,0,0,-1,0,0,NaN,1,0.007327,0,0,0,0,0,1,0,0,0,3,1,0,0,0,0,0,0.939654,0.134938,0.958699,0.974067,0.011736,0.806840,1,1.009285,0.928719,-1,2,0.001264,0.019176,-1,1.000754,2,-1,0,NaN,-1,NaN,1.0,0.154837,0.853498,0,1,0.239867,0,5,0.240768,0.239710,0,0.704843,3,0,16,0,2,1,1.007831,1,0,NaN,0.0,0.0,NaN,0.009227,0,NaN,-1,-1,-1,-1,0,0,0.0,NaN,0,0.006986,0,0
3,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a,2017-06-13,0.960384,0,0.013683,1.002700,0.001373,0.117169,0.0,0.005531,NaN,NaN,0,4,0.723997,0.166782,0,0.323271,0.530929,0.135586,-1,0.083720,0.049253,0.0,0.151219,4,0.006782,0,0.208214,0.741813,0.134437,NaN,0.030063,0.009667,0,1.0,0,0.102838,0.129017,2218,0.275055,0.155772,0.120740,0,0.138100,0.048382,0.012498,8,0.273553,0.204300,0.022732,15,0.094854,0,0,0,0,NaN,0.654358,0,-1,0,6,0.508670,0.008183,524,0.008716,0.005271,0,0,0.150209,0,5,0.031705,NaN,0.0,1,1,NaN,0.005595,0.0,NaN,0.000646,0.009193,0,0,0,-1,0.004876,0,0,0,0.000034,0,1,0.006969,1.0,0.060634,0,0,0.0,0,0,0,NaN,0,0,0,-1,0,0,NaN,1,0.007053,0,0,0,0,0,1,0,0,0,3,1,0,0,0,0,0,0.913205,0.140058,0.926341,0.975499,0.007571,0.808214,1,1.004514,0.935383,-1,2,0.002729,0.011720,-1,1.005338,2,-1,0,NaN,-1,NaN,1.0,0.153939,0.844667,0,1,0.240910,0,5,0.239400,0.240727,0,0.711546,3,0,16,0,2,1,1.003460,1,0,NaN,0.0,0.0,NaN,0.007206,0,NaN,-1,-1,-1,-1,0,0,0.0,NaN,0,0.006527,0,0
4,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a,2017-07-16,0.947248,0,0.015193,1.000727,0.007605,0.117325,0.0,0.009312,NaN,NaN,0,3,0.720619,0.143630,0,0.231009,0.529305,NaN,-1,0.075900,0.048918,0.0,0.154026,4,0.000519,0,0.205468,0.691986,0.121518,NaN,0.054221,0.009484,0,1.0,0,0.094311,0.129539,2896,0.231110,0.154914,0.095178,0,0.126443,0.039259,0.027897,8,0.233103,0.175655,0.031171,17,0.093915,0,0,0,0,NaN,0.650112,0,-1,0,6,0.216507,0.008605,524,0.006821,0.000152,0,0,0.096441,0,4,0.032733,NaN,0.0,1,1,NaN,0.004933,0.0,NaN,0.001833,0.005738,0,0,0,-1,0.007447,0,0,0,0.002109,0,1,0.001770,1.0,0.062492,0,0,0.0,0,0,0,NaN,0,0,0,-1,0,0,NaN,1,0.007728,0,0,0,0,0,1,0,0,0,3,1,0,0,0,0,0,0.921026,0.131620,0.933479,0.978027,0.018200,0.822281,1,1.005735,0.953363,-1,2,0.009998,0.017598,-1,1.003175,2,-1,0,NaN,-1,NaN,1.0,0.120717,0.811199,0,1,0.247939,0,5,0.244199,0.242325,0,0.705343,3,0,16,0,2,1,1.005053,1,0,NaN,0.0,0.0,NaN,0.006312,0,NaN,-1,-1,-1,-1,0,0,0.0,NaN,0,0.008126,0,0

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,customer_ID,category,0.0,0.00,458913.0,"9660ea13ba1089b8e1ecefdf9eef0347b09f9aca417dd061291fd4933a78854a, 8e8a18f4d22c180069a2d788d41af17ca108af04c864cd720d9b5b2206b9dc7e, c2efc5d0e3e190028ad14108a9a6b1583d28ce69996169f57310fb15b52a40ae, dc8004517ae308efaaaecf903a1535f3f5419e50d46a475b34a4bb30457a5f75, fc4c2dde8be3c17727bb0de26bdd072a47f5866be29b50ba0ef873a8de525ca8, 8db80999c8a38ccdf1ad1b0feddaeaebfafd45ffaa67df7046680df7c6f1c13e, de7b27b029841bef824982df7fb38acb22caa6165c79b22e38ee5f79c20072f9, 607ebdbd6e10d91bb0adbdad59d74676a951311be6d254fd5adc6399109385fc, 81bbb59be03f31bf023112fd4d6022546bb5d03a6bf710adf20bf8427c0d4dad, 95b4e8cce9abb80a63a9881b2afe17a2c36badc709c18c7b9b6af3cbd656146e"
1,D_63,category,0.0,0.00,6.0,"3, 0, 4, 1, 2, 5"
2,D_64,category,0.0,0.00,5.0,"0, 3, 2, -1, 1"
3,D_66,category,0.0,0.00,3.0,"-1, 1, 0"
4,D_68,category,0.0,0.00,8.0,"6, 5, 3, 4, 2, -1, 1, 0"
5,B_30,category,0.0,0.00,4.0,"0, 1, 2, -1"
6,B_38,category,0.0,0.00,8.0,"2, 3, 1, 5, 4, 7, 6, -1"
7,D_114,category,0.0,0.00,3.0,"1, 0, -1"
8,D_116,category,0.0,0.00,3.0,"0, -1, 1"
9,D_117,category,0.0,0.00,8.0,"0, 4, 5, 3, 6, 7, -1, 2"
10,D_120,category,0.0,0.00,3.0,"0, 1, -1"
11,D_126,category,0.0,0.00,4.0,"2, 1, 0, -1"
12,S_2,datetime64[ns],0.0,0.00,396.0,"2018-02-17 00:00:00, 2018-01-20 00:00:00, 2018-02-03 00:00:00, 2018-03-17 00:00:00, 2017-11-18 00:00:00, 2018-02-24 00:00:00, 2018-01-27 00:00:00, 2018-03-03 00:00:00, 2018-02-10 00:00:00, 2017-08-19 00:00:00"
13,D_88,float32,5525447.0,99.89,6004.0,"0.0933, 0.6384, 0.0884, 0.0785, 0.0142, 0.0793, 0.5381, 0.0055, 0.3571, 0.0576"
14,D_110,float32,5500117.0,99.43,30406.0,"1.0005, 0.7672, 1.0099, 1.01, 1.0075, 1.0088, 0.0836, 1.004, 0.5271, 0.215"
15,B_39,float32,5497819.0,99.39,33557.0,"0.4919, 0.138, 0.0846, 1.0036, 0.2975, 0.407, 0.1569, 0.2218, 0.1293, 1.0016"
16,D_73,float32,5475595.0,98.99,55802.0,"0.0699, 0.0994, 0.0979, 0.0722, 0.0544, 0.2075, 0.0423, 0.1167, 0.2507, 0.1078"
17,B_42,float32,5459973.0,98.71,71434.0,"0.0096, 0.0664, 0.0338, 0.0015, 0.0153, 0.0075, 0.1035, 0.0178, 0.0976, 0.031"
18,D_134,float32,5336752.0,96.48,192523.0,"1.0008, 1.0069, 1.0019, 1.0071, 0.1643, 1.0044, 1.0088, 1.0041, 1.0029, 1.0098"
19,B_29,float32,5150035.0,93.10,378319.0,"0.0093, 0.0088, 0.0085, 0.0056, 0.0079, 0.0028, 0.0085, 0.0034, 0.0085, 0.0097"
20,D_132,float32,4988874.0,90.19,538748.0,"0.198, 0.1824, 0.7143, 0.162, 0.0642, 0.2088, 0.0661, 0.109, 0.3194, 0.2412"
21,D_76,float32,4908954.0,88.75,619107.0,"0.1898, 0.0379, 0.0076, 0.1018, 0.0379, 0.0946, 0.0023, 0.174, 0.1953, 0.0571"
22,D_42,float32,4740137.0,85.69,785339.0,"0.0234, 0.0366, 0.1387, 0.4779, 0.1287, 0.1299, 0.3178, 0.229, 0.5432, 0.1395"
23,D_142,float32,4587043.0,82.93,926344.0,"0.5956, 0.2128, 0.4475, 0.3607, 0.27, 0.5606, 0.4828, 0.3235, 0.5906, 0.5699"
24,D_53,float32,4084585.0,73.84,1428989.0,"0.0091, 0.0549, 0.0085, 0.0079, 0.0098, 0.0043, 0.0635, 0.0399, 0.0223, 0.0082"
25,D_50,float32,3142402.0,56.81,2306378.0,"0.1195, 0.138, 0.0935, 0.0807, 0.0657, 0.1806, 0.0767, 0.1923, 0.0493, 0.0399"
26,B_17,float32,3137598.0,56.72,1592707.0,"1.0032, 1.0033, 1.0051, 1.0092, 1.0002, 1.0027, 1.0098, 1.0094, 1.005, 1.0003"
27,D_105,float32,3021431.0,54.62,2414778.0,"0.2741, 0.2581, 0.4054, 0.7813, 0.4623, 0.2984, 0.2142, 0.4842, 0.077, 0.2658"
28,D_56,float32,2990943.0,54.07,2446769.0,"0.1453, 0.1661, 0.1632, 0.2666, 0.2519, 0.1089, 0.1336, 0.3087, 0.1492, 0.1297"
29,S_9,float32,2933643.0,53.04,2531874.0,"0.008, 0.0436, 0.0083, 0.0746, 0.0152, 0.009, 0.0213, 0.0297, 0.0207, 0.008"
30,D_77,float32,2513912.0,45.45,2859646.0,"0.4071, 0.2057, 0.3065, 0.5075, 0.708, 0.5052, 0.4037, 0.5077, 0.3097, 0.2035"
31,D_43,float32,1658396.0,29.98,3708893.0,"0.0387, 0.07, 0.036, 0.1006, 0.1163, 0.0163, 0.0721, 0.1874, 0.1973, 0.0367"
32,S_27,float32,1400935.0,25.33,3885609.0,"0.4537, 0.3944, 0.3943, 0.5321, 0.0088, 0.4667, 0.5258, 0.4344, 0.3789, 0.6228"
33,D_46,float32,1211699.0,21.91,3388402.0,"0.4594, 0.4479, 0.4427, 0.4364, 0.4369, 0.4584, 0.4453, 0.5004, 0.4421, 0.4248"
34,S_3,float32,1020544.0,18.45,4004312.0,"0.1613, 0.1348, 0.1589, 0.1619, 0.1652, 0.1725, 0.1638, 0.166, 0.2925, 0.1503"
35,S_7,float32,1020544.0,18.45,4185390.0,"0.1027, 0.0964, 0.1065, 0.3738, 0.0944, 0.108, 0.088, 0.0991, 0.1366, 0.0933"
36,D_62,float32,758161.0,13.71,4519358.0,"0.545, 0.5419, 0.6546, 0.5435, 0.5441, 0.0489, 0.6487, 0.5441, 0.5477, 0.3241"
37,D_48,float32,718725.0,12.99,4534865.0,"0.8982, 0.9638, 0.437, 0.9424, 0.9519, 0.9456, 0.5099, 0.2064, 0.5935, 0.4233"
38,D_61,float32,598052.0,10.81,4529133.0,"0.8923, 0.6118, 0.8525, 0.7504, 0.9008, 0.8996, 0.8425, 0.9079, 0.7762, 0.8891"
39,P_3,float32,301492.0,5.45,3816101.0,"0.6124, 0.6236, 0.6451, 0.6213, 0.5882, 0.5918, 0.6436, 0.5836, 0.6118, 0.6177"
40,D_69,float32,194473.0,3.52,4800508.0,"0.0083, 0.0092, 0.0076, 0.0068, 0.0085, 0.0099, 0.0095, 0.0096, 0.0098, 0.0096"
41,D_55,float32,184803.0,3.34,5082515.0,"0.7242, 0.4672, 0.523, 0.5802, 0.5687, 0.0431, 0.6562, 0.0187, 0.7104, 0.5145"
42,D_115,float32,176716.0,3.19,5063856.0,"0.6358, 0.3255, 0.4277, 0.3233, 0.264, 0.7221, 0.5882, 0.3007, 0.4068, 0.3169"
43,D_118,float32,176716.0,3.19,5064015.0,"0.7096, 0.3315, 0.2526, 0.5259, 0.1345, 0.5851, 0.4748, 0.6205, 0.3033, 0.0335"
44,D_119,float32,176716.0,3.19,5071097.0,"0.542, 0.4606, 0.1583, 0.0595, 0.128, 0.7263, 0.7084, 0.3373, 0.4503, 0.4072"
45,D_121,float32,176716.0,3.19,4308351.0,"0.7677, 0.7597, 0.7093, 0.7612, 0.7626, 0.7094, 0.7676, 0.7645, 0.7639, 0.7596"
46,R_27,float32,128703.0,2.33,685818.0,"1.0093, 1.0027, 1.0027, 1.006, 1.003, 1.004, 1.007, 1.0071, 1.009, 1.0015"
47,D_104,float32,101548.0,1.84,850543.0,"0.0, 0.9608, 0.9535, 0.9569, 0.9682, 0.9536, 0.9577, 0.9552, 0.9566, 0.9583"
48,D_128,float32,101548.0,1.84,100748.0,"0.0, 1.0088, 1.0047, 1.0064, 1.0001, 1.0061, 1.0037, 1.0089, 1.0001, 1.0054"
49,D_130,float32,101548.0,1.84,87229.0,"0.0, 1.0038, 1.0026, 1.004, 1.0015, 1.0053, 1.0, 1.0094, 1.0089, 1.0047"
50,D_131,float32,101548.0,1.84,357435.0,"0.0, 0.9791, 0.9777, 0.979, 0.9838, 0.9762, 0.9972, 0.9862, 0.9781, 0.976"
51,D_141,float32,101548.0,1.84,779126.0,"0.0, 0.867, 0.903, 0.8788, 0.9686, 0.8585, 0.8951, 0.8665, 0.8614, 0.8955"
52,B_13,float32,49519.0,0.90,5249059.0,"0.0102, 0.0357, 0.0048, 0.0171, 0.0084, 0.0364, 0.0461, 0.049, 0.0067, 0.0083"
53,P_2,float32,45985.0,0.83,4534509.0,"1.0013, 1.0025, 1.0071, 0.9162, 0.9221, 1.0004, 0.8007, 0.7159, 1.0033, 1.0045"
54,D_133,float32,42716.0,0.77,4966219.0,"0.005, 0.0078, 0.0089, 0.0087, 0.007, 0.0063, 0.0099, 0.0087, 0.0045, 0.0089"
55,D_144,float32,40727.0,0.74,4985193.0,"0.0097, 0.0082, 0.0081, 0.0081, 0.0078, 0.0099, 0.0081, 0.0084, 0.0062, 0.0091"
56,D_102,float32,40655.0,0.73,5187619.0,"0.0094, 0.4715, 0.0039, 0.0099, 0.0099, 0.0047, 0.0091, 0.0084, 0.0098, 0.7269"
57,D_52,float32,29563.0,0.53,4949947.0,"0.2988, 1.0078, 0.1986, 1.0013, 1.0023, 1.0073, 0.218, 1.0039, 1.0033, 0.2541"
58,B_8,float32,22268.0,0.40,88734.0,"0.0, 1.0013, 1.0093, 1.0021, 1.0061, 1.0006, 1.001, 1.0075, 1.0066, 1.0047"
59,S_22,float32,19024.0,0.34,2330970.0,"0.2954, 0.964, 0.9568, 0.972, 0.9546, 0.9635, 0.9771, 0.9574, 0.9465, 0.9641"
60,S_24,float32,18593.0,0.34,2793098.0,"0.9629, 0.9681, 0.9574, 0.9819, 0.9626, 0.9476, 0.9782, 0.9591, 0.9418, 0.9736"
61,S_25,float32,12847.0,0.23,755544.0,"0.9712, 0.9748, 0.9749, 0.9727, 0.9697, 0.9706, 0.9731, 0.9707, 0.9762, 0.9765"
62,B_15,float32,6923.0,0.13,5103912.0,"0.0096, 0.0095, 0.0086, 0.0056, 0.0052, 0.0039, 0.0047, 0.0068, 0.0092, 0.007"
63,B_25,float32,6923.0,0.13,5297013.0,"0.041, 0.0093, 0.0099, 0.0151, 0.0509, 0.1313, 0.0082, 0.0096, 0.0534, 0.0896"
64,D_112,float32,2650.0,0.05,894388.0,"1.0, 0.0042, 0.003, 0.0077, 0.0097, 0.0039, 0.0046, 0.0093, 0.0085, 0.0174"
65,B_2,float32,2016.0,0.04,2346669.0,"1.0057, 1.0072, 1.0086, 1.0028, 1.008, 1.0023, 1.0016, 1.0049, 1.0045, 1.0036"
66,D_41,float32,2016.0,0.04,710177.0,"0.0, 1.098, 0.3454, 0.3679, 0.4169, 0.2284, 0.1833, 0.0875, 1.237, 0.5929"
67,B_3,float32,2016.0,0.04,5273509.0,"0.0061, 0.0095, 0.008, 0.0074, 0.008, 0.0099, 0.0079, 0.1633, 0.0095, 0.0106"
68,D_45,float32,2017.0,0.04,5210401.0,"0.4657, 0.3589, 0.3288, 0.3158, 0.5773, 0.2548, 0.0792, 0.2539, 0.1347, 0.4584"
69,D_54,float32,2016.0,0.04,112645.0,"1.0, 0.0165, 0.0015, 0.0098, 0.002, 0.0025, 0.0041, -0.0012, 0.0073, 0.0053"
70,B_26,float32,2016.0,0.04,4969518.0,"0.0083, 0.0087, 0.0091, 0.0089, 0.0082, 0.0084, 0.0049, 0.0078, 0.0083, 0.0087"
71,B_27,float32,2016.0,0.04,4921945.0,"0.0058, 0.0069, 0.0074, 0.0094, 0.0088, 0.0065, 0.0099, 0.0096, 0.008, 0.0082"
72,S_23,float32,445.0,0.01,1252495.0,"0.1381, 0.1337, 0.1339, 0.135, 0.1386, 0.135, 0.1372, 0.1382, 0.1341, 0.1373"
73,S_26,float32,634.0,0.01,5157577.0,"0.0088, 0.0079, 0.0092, 0.0079, 0.0085, 0.0059, 0.004, 0.0094, 0.0062, 0.0045"
74,B_1,float32,0.0,0.00,5319031.0,"0.0233, 0.0082, 0.0074, 0.0093, 0.2197, 0.0094, 0.003, 0.036, 0.0674, 0.1303"
75,R_1,float32,0.0,0.00,4788285.0,"0.5099, 0.5058, 0.5027, 0.0079, 0.5007, 0.5006, 0.5095, 0.5019, 0.5007, 0.5035"
76,B_5,float32,0.0,0.00,5268298.0,"0.0123, 0.0091, 0.0175, 0.0055, 0.1154, 0.0097, 0.0093, 0.078, 0.0156, 0.0078"
77,D_47,float32,0.0,0.00,4986282.0,"0.6708, 0.3358, 0.6208, 0.3097, 0.1807, 0.6508, 0.5806, 0.2279, 0.4115, 0.5117"
78,B_6,float32,233.0,0.00,5152590.0,"0.1998, 0.1774, 0.1835, 0.1707, 0.1982, 0.1746, 0.1958, 0.1954, 0.2041, 0.19"
79,B_7,float32,0.0,0.00,5259879.0,"0.0276, 0.1672, 0.0354, 0.0298, 0.0908, 0.0272, 0.5727, 0.0722, 0.0324, 0.0641"
80,B_9,float32,0.0,0.00,5181777.0,"0.6441, 0.6112, 0.6454, 0.0039, 0.6002, 0.6463, 0.6448, 0.6386, 0.6371, 0.6353"
81,B_10,float32,0.0,0.00,4190332.0,"0.2955, 0.2997, 0.2977, 0.2941, 0.3028, 0.3011, 0.3008, 0.3015, 0.2954, 0.3026"
82,S_5,float32,0.0,0.00,5290271.0,"0.0058, 0.0072, 0.0058, 0.0087, 0.0079, 0.0057, 0.0054, 0.0071, 0.0081, 0.0065"
83,B_11,float32,0.0,0.00,5309099.0,"0.0099, 0.0085, 0.0079, 0.1511, 0.008, 0.0161, 0.0078, 0.0062, 0.0079, 0.0191"
84,B_12,float32,0.0,0.00,5193313.0,"0.0385, 0.0214, 0.0104, 0.0099, 0.0107, 0.0084, 0.0096, 0.0067, 0.0138, 0.0115"
85,D_58,float32,0.0,0.00,5256972.0,"0.1623, 0.5495, 0.0097, 0.0051, 0.005, 0.01, 0.0055, 0.5747, 0.0082, 0.0091"
86,B_14,float32,0.0,0.00,5309932.0,"0.0062, 0.0042, 0.229, 0.1255, 0.0088, 0.0315, 0.025, 0.0452, 0.049, 0.0082"
87,D_60,float32,0.0,0.00,4679920.0,"1.0096, 1.0084, 1.0063, 1.0057, 1.0093, 1.0057, 1.0067, 1.0094, 1.0065, 1.0047"
88,B_18,float32,0.0,0.00,2603059.0,"1.0, 0.648, 0.6475, 0.6955, 0.6453, 0.6909, 0.6925, 0.6459, 0.6937, 0.6466"
89,S_12,float32,0.0,0.00,2592981.0,"0.1937, 0.19, 0.1875, 0.1925, 0.1867, 0.1845, 0.1859, 0.1935, 0.1934, 0.1859"
90,R_6,float32,0.0,0.00,4959486.0,"0.0087, 0.01, 0.0088, 0.0042, 0.0087, 0.0059, 0.0087, 0.0059, 0.0092, 0.0086"
91,B_21,float32,0.0,0.00,4944665.0,"0.0091, 0.01, 0.0099, 0.008, 0.0083, 0.0085, 0.0091, 0.0083, 0.01, 0.0083"
92,D_71,float32,0.0,0.00,5076426.0,"0.0082, 0.0086, 0.016, 0.0109, 0.0099, 0.0167, 0.0104, 0.0099, 0.0079, 0.0083"
93,B_23,float32,0.0,0.00,5300841.0,"0.0374, 0.3154, 0.0174, 0.0216, 0.1291, 0.4185, 0.1243, 0.5749, 0.0176, 0.0106"
94,P_4,float32,0.0,0.00,424684.0,"0.0, 0.9562, 0.9577, 0.9588, 0.9592, 0.9565, 0.9633, 0.9561, 0.9609, 0.9646"
95,B_24,float32,0.0,0.00,4960342.0,"0.0093, 0.0084, 0.0084, 0.008, 0.0092, 0.0091, 0.0068, 0.0082, 0.0099, 0.0068"
96,R_7,float32,1.0,0.00,144971.0,"0.0, 0.3468, 0.6222, 2.914, 1.2493, 0.157, 0.6193, 2.0339, 0.2731, 0.3977"
97,S_16,float32,0.0,0.00,4944353.0,"0.0095, 0.006, 0.0085, 0.0064, 0.0097, 0.0086, 0.0089, 0.0085, 0.0095, 0.006"
98,S_17,float32,0.0,0.00,4996175.0,"0.0082, 0.0065, 0.0099, 0.0085, 0.01, 0.0083, 0.007, 0.0083, 0.0092, 0.0099"
99,R_12,float32,56.0,0.00,153759.0,"1.0, 0.3215, 0.1675, 0.1827, -0.0675, 0.2557, 0.1376, -0.0492, 0.035, -0.0831"
100,B_28,float32,0.0,0.00,5274054.0,"0.0332, 0.0186, 0.141, 0.1592, 0.0414, 0.1878, 0.1499, 0.094, 0.1269, 0.1352"
101,R_14,float32,1.0,0.00,77586.0,"0.0, 0.4243, 2.0272, 0.3812, 0.3907, 0.6801, 0.4779, 1.7101, 0.9059, 0.8729"
102,S_19,float32,0.0,0.00,4923015.0,"0.0094, 0.0092, 0.0083, 0.0081, 0.0084, 0.0096, 0.0077, 0.0078, 0.0051, 0.0082"
103,B_36,float32,0.0,0.00,4929153.0,"0.0073, 0.0086, 0.0079, 0.0094, 0.0096, 0.0026, 0.0099, 0.0095, 0.0079, 0.0097"
104,B_37,float32,56.0,0.00,5318922.0,"0.021, 0.0096, 0.0094, 0.0254, 0.0919, 0.0288, 0.0086, 0.0437, 0.0081, 0.0284"
105,B_40,float32,53.0,0.00,5308815.0,"0.0167, 0.276, 0.454, 0.4094, 0.5438, 0.3735, 0.2849, 0.1096, 0.0255, 0.0658"
106,D_39,int16,0.0,0.00,180.0,"0, 1, 3, 2, 4, 5, 6, 8, 7, 9"
107,B_4,int16,0.0,0.00,293.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
108,D_49,int16,0.0,0.00,321.0,"-1, 1, 4, 2, 5, 3, 7, 6, 8, 9"
109,S_8,int16,0.0,0.00,32.0,"0, 1021, 2380, 528, 996, 1544, 2218, 1511, 2096, 1454"
110,D_65,int16,0.0,0.00,775.0,"0, 1, 7, 2, 3, 4, 5, 6, 8, 9"
111,S_13,int16,0.0,0.00,13.0,"0, 435, 290, 702, 1034, 872, 524, 643, 711, 544"
112,D_106,int16,0.0,0.00,309.0,"-1, 2, 0, 3, 1, 4, 5, 6, 7, 8"
113,R_26,int16,0.0,0.00,158.0,"-1, 0, 1, 2, 3, 4, 5, 6, 7, 8"
114,D_124,int16,0.0,0.00,61.0,"4, 5, 6, 3, 7, 8, 2, 9, 10, 11"
115,D_44,int8,0.0,0.00,38.0,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
116,R_2,int8,0.0,0.00,2.0,"0, 1"
117,D_51,int8,0.0,0.00,9.0,"0, 1, 2, 3, 4, 5, 6, 7, 8"
118,R_3,int8,0.0,0.00,91.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
119,S_6,int8,0.0,0.00,2.0,"0, 1"
120,R_4,int8,0.0,0.00,2.0,"0, 1"
121,R_5,int8,0.0,0.00,47.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
122,D_59,int8,0.0,0.00,104.0,"28, 27, 26, 8, 21, 25, 22, 29, 18, 23"
123,S_11,int8,0.0,0.00,83.0,"12, 15, 14, 13, 16, 17, 11, 18, 10, 19"
124,B_16,int8,0.0,0.00,14.0,"0, 12, 1, 2, 3, 11, 4, 10, 5, 7"
125,B_19,int8,0.0,0.00,47.0,"0, 100, 8, 50, 16, 33, 25, 66, 91, 83"
126,B_20,int8,0.0,0.00,19.0,"0, 17, 1, 2, 5, 3, 4, 6, 7, 8"
127,B_22,int8,0.0,0.00,9.0,"0, 1, 2, 3, -1, 4, 5, 7, 6"
128,D_70,int8,0.0,0.00,29.0,"0, 1, 2, 3, -1, 4, 5, 6, 7, 8"
129,D_72,int8,0.0,0.00,11.0,"0, 1, 2, -1, 3, 4, 9, 5, 6, 7"
130,S_15,int8,0.0,0.00,57.0,"8, 5, 6, 7, 4, 9, 3, 10, 11, 12"
131,D_74,int8,0.0,0.00,53.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
132,D_75,int8,0.0,0.00,57.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
133,D_78,int8,0.0,0.00,25.0,"0, -1, 1, 2, 3, 4, 5, 6, 7, 8"
134,D_79,int8,0.0,0.00,25.0,"0, 1, 2, -1, 3, 4, 5, 6, 8, 7"
135,R_8,int8,0.0,0.00,33.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
136,R_9,int8,0.0,0.00,11.0,"-1, 1, 2, 0, 3, 4, 5, 6, 9, 7"
137,D_80,int8,0.0,0.00,38.0,"0, 1, 2, 3, 4, 5, -1, 6, 7, 8"
138,R_10,int8,0.0,0.00,18.0,"0, 1, 2, 3, 4, 5, 6, 7, 9, 8"
139,R_11,int8,0.0,0.00,19.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 25"
140,D_81,int8,0.0,0.00,10.0,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
141,D_82,int8,0.0,0.00,8.0,"-1, 1, 0, 2, 3, 4, 5, 6"
142,R_13,int8,0.0,0.00,28.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
143,D_83,int8,0.0,0.00,33.0,"0, -1, 1, 2, 3, 4, 5, 6, 7, 8"
144,R_15,int8,0.0,0.00,2.0,"0, 1"
145,D_84,int8,0.0,0.00,40.0,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
146,R_16,int8,0.0,0.00,32.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
147,S_18,int8,0.0,0.00,2.0,"0, 1"
148,D_86,int8,0.0,0.00,2.0,"0, 1"
149,D_87,int8,0.0,0.00,2.0,"-1, 1"
150,R_17,int8,0.0,0.00,25.0,"0, 1, 2, 3, 4, 5, 6, 8, 7, 9"
151,R_18,int8,0.0,0.00,20.0,"0, 2, 1, 4, 6, 7, 11, 5, 8, 10"
152,B_31,int8,0.0,0.00,2.0,"1, 0"
153,R_19,int8,0.0,0.00,2.0,"0, 1"
154,B_32,int8,0.0,0.00,2.0,"0, 1"
155,S_20,int8,0.0,0.00,2.0,"0, 1"
156,R_20,int8,0.0,0.00,43.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
157,R_21,int8,0.0,0.00,2.0,"0, 1"
158,B_33,int8,0.0,0.00,3.0,"1, 0, -1"
159,D_89,int8,0.0,0.00,11.0,"0, 1, -1, 2, 3, 4, 5, 6, 9, 8"
160,R_22,int8,0.0,0.00,2.0,"0, 1"
161,R_23,int8,0.0,0.00,2.0,"0, 1"
162,D_91,int8,0.0,0.00,8.0,"0, 1, -1, 2, 3, 4, 5, 6"
163,D_92,int8,0.0,0.00,3.0,"0, 1, 2"
164,D_93,int8,0.0,0.00,2.0,"0, 1"
165,D_94,int8,0.0,0.00,2.0,"0, 1"
166,R_24,int8,0.0,0.00,2.0,"0, 1"
167,R_25,int8,0.0,0.00,2.0,"0, 1"
168,D_96,int8,0.0,0.00,2.0,"0, 1"
169,D_103,int8,0.0,0.00,3.0,"0, 1, -1"
170,D_107,int8,0.0,0.00,22.0,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
171,D_108,int8,0.0,0.00,11.0,"-1, 0, 1, 2, 4, 3, 5"
172,D_109,int8,0.0,0.00,3.0,"0, 1, -1"
173,D_111,int8,0.0,0.00,4.0,"-1, 2, 1, 0"
174,D_113,int8,0.0,0.00,24.0,"0, 1, 2, 3, -1, 4, 5, 6, 7, 8"
175,D_122,int8,0.0,0.00,16.0,"1, 2, 3, 4, 5, 6, -1, 7, 0, 8"
176,D_123,int8,0.0,0.00,13.0,"0, 1, -1, 2, 3, 32, 104, 37, 5"
177,D_125,int8,0.0,0.00,12.0,"0, 1, -1, 2, 3, 4, 5, 6, 14"
178,D_127,int8,0.0,0.00,2.0,"0, 1"
179,D_129,int8,0.0,0.00,3.0,"0, 1, -1"
180,B_41,int8,0.0,0.00,21.0,"0, 1, 2, 3, 4, -1, 5, 6, 8, 10"
181,R_28,int8,0.0,0.00,2.0,"0, 1"
182,D_135,int8,0.0,0.00,3.0,"-1, 0, 1"
183,D_136,int8,0.0,0.00,9.0,"-1, 1, 0, 2, 3, 4, 5, 6, 7"
184,D_137,int8,0.0,0.00,3.0,"-1, 0, 1"
185,D_138,int8,0.0,0.00,8.0,"-1, 0, 1, 2, 3, 4, 5, 6"
186,D_139,int8,0.0,0.00,3.0,"0, 1, -1"
187,D_140,int8,0.0,0.00,3.0,"0, 1, -1"
188,D_143,int8,0.0,0.00,3.0,"0, 1, -1"
189,D_145,int8,0.0,0.00,52.0,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
190,target,int8,0.0,0.00,2.0,"0, 1"

In [6]:
# Numeric Feature Statistics
numeric_stats

           count         mean         std           min           max
P_2     548548.0     0.656102    0.244823 -4.131063e-01      1.010000
D_39    553145.0     5.033774    9.214970  0.000000e+00    183.000000
B_1     553145.0     0.123490    0.211265 -1.024709e+00      1.324058
B_2     552932.0     0.621507    0.401277  1.179233e-06      1.010000
R_1     553145.0     0.078804    0.226431  8.059843e-09      2.758633
S_3     451273.0     0.225840    0.193153 -4.915387e-01      4.882418
D_41    552932.0     0.055709    0.205253  0.000000e+00      8.988807
B_3     552932.0     0.132275    0.234518  1.498946e-07      1.540823
D_42     79361.0     0.185331    0.231210 -1.983227e-04      4.186264
D_43    387522.0     0.154672    0.211767  2.876647e-07     10.111619
D_44    553145.0     0.814761    1.773135 -1.000000e+00     27.000000
B_4     553145.0    13.066916   17.310671  0.000000e+00    292.000000
D_45    552932.0     0.251913    0.242805  7.454545e-08      1.599662
B_5     553145.0     0.083140    0.419531  2.064900e-07    116.657402
R_2     553145.0     0.042320    0.201318  0.000000e+00      1.000000
D_46    432359.0     0.475754    0.170475 -9.647968e+00      7.313056
D_47    553145.0     0.406735    0.235048 -2.661579e-02      1.643008
D_48    481701.0     0.381749    0.326249 -9.603049e-03      8.964579
D_49    553145.0     0.409267    7.270832 -1.000000e+00   1454.000000
B_6     553117.0     0.152551    1.432282 -4.477354e-03    583.183350
B_7     553145.0     0.186032    0.229894 -4.124801e-01      1.252749
B_8     550933.0     0.448631    0.499509  0.000000e+00      1.011718
D_50    238881.0     0.173602    0.601884 -4.498265e+00    113.801125
D_51    553145.0     0.419049    0.725806  0.000000e+00      8.000000
B_9     553145.0     0.189118    0.283720  2.376601e-08     16.342426
R_3     553145.0     1.160638    2.119802  0.000000e+00     84.000000
D_52    550196.0     0.179615    0.173099 -6.913935e-03      1.010000
P_3     522811.0     0.601139    0.170829 -1.266380e+00      2.233687
B_10    553145.0     0.237331    4.695023 -2.958481e-03   1722.187378
D_53    144631.0     0.076399    0.203490  6.530330e-08      7.109793
S_5     553145.0     0.087895    0.371801  1.803506e-08     91.433449
B_11    553145.0     0.110434    0.207587  7.463281e-08      1.567640
S_6     553145.0     0.239279    0.426644  0.000000e+00      1.000000
D_54    552932.0     0.979494    0.141221 -2.000691e-03      1.000000
R_4     553145.0     0.025991    0.159110  0.000000e+00      1.000000
S_7     451273.0     0.223029    0.206094 -3.601164e-01      3.516453
B_12    553145.0     0.094228    0.956807  1.221753e-07    418.793091
S_8     553145.0  1020.491672  959.201921  0.000000e+00   3867.000000
D_55    534829.0     0.298316    0.288613  3.883899e-07      2.603316
D_56    253672.0     0.203727    0.209502 -1.603519e-02      8.518801
B_13    548111.0     0.100858    0.609704  2.371625e-07    234.729340
R_5     553145.0     0.059653    0.520609  0.000000e+00     41.000000
D_58    553145.0     0.215694    0.260271  1.085239e-07      1.261784
S_9     259377.0     0.074124    0.194477  4.459887e-07      2.839580
B_14    553145.0     0.100914    0.278917 -5.680852e+00     39.645187
D_59    553145.0    21.717716    9.731644 -1.000000e+00    100.000000
D_60    553145.0     0.375247    0.371381  3.356854e-08      1.010000
D_61    493826.0     0.429685    0.347742 -9.258480e-03     46.417835
B_15    552446.0     0.052456    0.292915 -6.720455e+00     46.874805
S_11    553145.0    14.249725    4.760566  0.000000e+00     80.000000
D_62    477963.0     0.190388    0.230091 -2.319997e-03      9.770630
D_65    553145.0     1.330277   25.907637  0.000000e+00  14664.000000
B_16    553145.0     4.121583    4.826031 -1.000000e+00     12.000000
B_17    239447.0     0.714946    0.386909  5.242698e-07      1.010000
B_18    553145.0     0.594033    0.363181  9.678920e-07      1.000000
B_19    553145.0    14.487520   28.913697 -1.000000e+00    100.000000
B_20    553145.0     3.925934    6.350242 -1.000000e+00     17.000000
S_12    553145.0     0.240689    0.249515 -3.896515e-01     62.183109
R_6     553145.0     0.058516    0.642179  1.532081e-08     14.448178
S_13    553145.0   257.690759  306.420933  0.000000e+00   1034.000000
B_21    553145.0     0.055771    0.849439  1.647962e-07    288.294281
D_69    533666.0     0.155217   18.328608  2.055434e-08  13000.903320
B_22    553145.0     0.203064    0.445837 -1.000000e+00      7.000000
D_70    553145.0     0.397182    0.920779 -1.000000e+00     21.000000
D_71    553145.0     0.070938    0.330189  1.026092e-08     55.511433
D_72    553145.0     0.093339    0.614315 -1.000000e+00      9.000000
S_15    553145.0     6.699175    1.952031  0.000000e+00     56.000000
B_23    553145.0     0.171374    0.228751  4.252517e-07      1.519500
D_73      5514.0     0.153828    0.190843 -4.242653e-02      3.205873
P_4     553145.0     0.140120    0.340543  0.000000e+00      1.269390
D_74    553145.0     2.069025    3.064349 -1.000000e+00     48.000000
D_75    553145.0     2.494888    3.358944  0.000000e+00     52.000000
D_76     62216.0     0.139565    0.283106  1.663297e-06     15.130428
B_24    553145.0     0.040384    0.323067  1.999223e-08     31.093552
R_7     553145.0     0.082650    1.534307  0.000000e+00    243.556976
D_77    302340.0     0.256021    0.232503  7.095482e-08      9.003958
B_25    552446.0     0.103982    0.210223 -4.318307e+00     12.530606
B_26    552932.0     0.093454    3.215001  5.753395e-09   1499.216431
D_78    553145.0     0.060787    0.562442 -1.000000e+00     19.000000
D_79    553145.0     0.113184    0.460294 -1.000000e+00     36.000000
R_8     553145.0     0.033161    0.304782  0.000000e+00     21.000000
R_9     553145.0    -0.867060    0.605557 -1.000000e+00      9.000000
S_16    553145.0     0.054208    0.928593  4.509010e-08    231.754211
D_80    553145.0     0.530955    1.077242 -1.000000e+00     32.000000
R_10    553145.0     0.060449    0.309167  0.000000e+00     10.000000
R_11    553145.0     0.091896    0.351404  0.000000e+00     25.000000
B_27    552932.0     0.005009    0.003258  2.007182e-08      1.005370
D_81    553145.0     0.045102    0.346831 -1.000000e+00      8.000000
D_82    553145.0    -0.492724    0.864869 -1.000000e+00      6.000000
S_17    553145.0     0.039521    0.239568  1.954301e-08      4.049048
R_12    553140.0     0.973918    0.154180 -9.144605e-02      1.000000
B_28    553145.0     0.154469    0.226062 -2.111560e-05     18.401817
R_13    553145.0     0.014906    0.208698  0.000000e+00     22.000000
D_83    553145.0    -0.000224    0.363798 -1.000000e+00     35.000000
R_14    553145.0     0.246980    8.173603  0.000000e+00   1968.196777
R_15    553145.0     0.015325    0.122842  0.000000e+00      1.000000
D_84    553145.0     0.074474    0.577353 -1.000000e+00     33.000000
R_16    553145.0     0.106726    0.474934  0.000000e+00     37.000000
B_29     38092.0     0.034410    0.281156  2.146359e-08      9.738897
S_18    553145.0     0.026409    0.160348  0.000000e+00      1.000000
D_86    553145.0     0.032456    0.177209  0.000000e+00      1.000000
D_87    553145.0    -0.998821    0.048539 -1.000000e+00      1.000000
R_17    553145.0     0.011586    0.205118  0.000000e+00     22.000000
R_18    553145.0     0.000246    0.037358  0.000000e+00     11.000000
D_88       607.0     0.176118    0.213234  1.892726e-03      1.456043
B_31    553145.0     0.996878    0.055789  0.000000e+00      1.000000
S_19    553145.0     0.005030    0.003073  2.376606e-08      0.408605
R_19    553145.0     0.017390    0.130718  0.000000e+00      1.000000
B_32    553145.0     0.022309    0.147686  0.000000e+00      1.000000
S_20    553145.0     0.012733    0.112118  0.000000e+00      1.000000
R_20    553145.0     0.032438    0.391642 -1.000000e+00     40.000000
R_21    553145.0     0.016717    0.128210  0.000000e+00      1.000000
B_33    553145.0     0.606631    0.489286 -1.000000e+00      1.000000
D_89    553145.0     0.007783    0.186024 -1.000000e+00      9.000000
R_22    553145.0     0.003547    0.059451  0.000000e+00      1.000000
R_23    553145.0     0.000316    0.017784  0.000000e+00      1.000000
D_91    553145.0     0.082517    0.411734 -1.000000e+00      6.000000
D_92    553145.0     0.085563    0.292841  0.000000e+00      2.000000
D_93    553145.0     0.010032    0.099655  0.000000e+00      1.000000
D_94    553145.0     0.017225    0.130109  0.000000e+00      1.000000
R_24    553145.0     0.013922    0.117168  0.000000e+00      1.000000
R_25    553145.0     0.003316    0.057486  0.000000e+00      1.000000
D_96    553145.0     0.030715    0.172545  0.000000e+00      1.000000
S_22    551208.0     0.778240    0.770096 -8.267871e+01      1.032671
S_23    553098.0     0.179458    0.858255 -1.702370e+02    579.276245
S_24    551253.0     0.734028    0.892083 -9.048161e+01      1.053231
S_25    551837.0     0.925134    0.205779 -2.453435e+00      2.973127
S_26    553081.0     0.066855    0.457252  2.219500e-08     83.223015
D_102   549030.0     0.190332    0.275174  7.100560e-08      1.089997
D_103   553145.0     0.435390    0.532041 -1.000000e+00      1.000000
D_104   542845.0     0.448313    0.483283  0.000000e+00      1.299110
D_105   251133.0     0.371052    0.250360 -2.344517e-02      5.503611
D_106   553145.0    -0.452923    4.216568 -1.000000e+00   1501.000000
D_107   553145.0     0.576408    0.795889 -1.000000e+00     20.000000
B_36    553145.0     0.006381    0.021407  1.018407e-08      0.979890
B_37    553141.0     0.122647    0.210943 -1.443582e+00      1.327806
R_26    553145.0    -0.642228    2.538420 -1.000000e+00    266.000000
R_27    540193.0     0.893038    0.313107 -2.267554e-02      1.010000
D_108   553145.0    -0.994387    0.081049 -1.000000e+00      5.000000
D_109   553145.0     0.001417    0.044734 -1.000000e+00      1.000000
D_110     3168.0     0.738316    0.311451 -2.267699e-02      1.009994
D_111   553145.0    -0.984239    0.211505 -1.000000e+00      2.000000
B_39      3398.0     0.255357    0.296398 -9.793140e-01      1.027121
D_112   552868.0     0.836791    0.367615  4.947340e-07      1.000000
B_40    553141.0     0.197387    7.868359  1.726541e-07   5755.076172
S_27    413248.0     0.277282    0.325908  4.191520e-08      5.346264
D_113   553145.0     0.705703    1.155254 -1.000000e+00     36.000000
D_115   535470.0     0.277562    0.256156  8.462625e-07      1.999034
D_118   535470.0     0.283039    0.255686  8.861901e-08      1.967873
D_119   535470.0     0.278963    0.256176  2.353007e-07      1.976611
D_121   535470.0     0.531971    0.234156 -3.207145e-02      1.791044
D_122   553145.0     2.676014    1.762260 -1.000000e+00     14.000000
D_123   553145.0     0.012570    0.317173 -1.000000e+00    104.000000
D_124   553145.0     7.342930    5.128626 -1.000000e+00     62.000000
D_125   553145.0     0.045142    0.344845 -1.000000e+00     14.000000
D_127   553145.0     0.102633    0.303479  0.000000e+00      1.000000
D_128   542845.0     0.581684    0.495667  0.000000e+00      1.022260
D_129   553145.0     0.408336    0.528053 -1.000000e+00      1.000000
B_41    553145.0     0.027304    0.225328 -1.000000e+00     16.000000
B_42      7012.0     0.106339    0.297834  3.108574e-06      9.028084
D_130   542845.0     0.197412    0.399294  0.000000e+00      1.015453
D_131   542845.0     0.099169    0.297191  0.000000e+00      1.491104
D_132    54408.0     0.209048    0.240951 -1.408600e-02      5.999511
D_133   548825.0     0.046294    0.172429  3.685528e-09      1.509998
R_28    553145.0     0.000757    0.027512  0.000000e+00      1.000000
D_134    19623.0     0.333576    0.296871 -1.244420e-02      1.009997
D_135   553145.0    -0.963628    0.191944 -1.000000e+00      1.000000
D_136   553145.0    -0.930575    0.396069 -1.000000e+00      7.000000
D_137   553145.0    -0.964188    0.187621 -1.000000e+00      1.000000
D_138   553145.0    -0.953195    0.264213 -1.000000e+00      6.000000
D_139   553145.0     0.151503    0.407175 -1.000000e+00      1.000000
D_140   553145.0     0.013935    0.169140 -1.000000e+00      1.000000
D_141   542845.0     0.159850    0.349682  0.000000e+00      1.330236
D_142    94101.0     0.390261    0.236677 -1.089843e-02      2.229368
D_143   553145.0     0.151391    0.407079 -1.000000e+00      1.000000
D_144   549024.0     0.052058    0.181851  2.500991e-09      1.343328
D_145   553145.0     0.595851    2.106423 -1.000000e+00     52.000000
target  553145.0     0.249629    0.432799  0.000000e+00      1.000000

In [7]:
# Categorical Feature Statistics
cat_stats

                                                                             value  \
column      rank
B_30        1                                                                    0
            2                                                                    1
            3                                                                    2
            4                                                                   -1
B_38        1                                                                    2
            2                                                                    3
            3                                                                    1
            4                                                                    5
            5                                                                    4
D_114       1                                                                    1
            2                                                                    0
            3                                                                   -1
D_116       1                                                                    0
            2                                                                   -1
            3                                                                    1
D_117       1                                                                    0
            2                                                                    4
            3                                                                    5
            4                                                                    3
            5                                                                    6
D_120       1                                                                    0
            2                                                                    1
            3                                                                   -1
D_126       1                                                                    2
            2                                                                    1
            3                                                                    0
            4                                                                   -1
D_63        1                                                                    3
            2                                                                    0
            3                                                                    4
            4                                                                    1
            5                                                                    2
D_64        1                                                                    0
            2                                                                    3
            3                                                                    2
            4                                                                   -1
            5                                                                    1
D_66        1                                                                   -1
            2                                                                    1
            3                                                                    0
D_68        1                                                                    6
            2                                                                    5
            3                                                                    3
            4                                                                    4
            5                                                                    2
S_2         1                                                  2018-02-17 00:00:00
            2                                                  2018-01-20 00:00:00
            3                                                  2018-02-03 00:00:00
            4                                                  2018-03-17 00:00:00
            5                                                  2017-11-18 00:00:00
customer_ID 1     9660ea13ba1089b8e1ecefdf9eef0347b09f9aca417dd061291fd4933a78854a
            2     8e8a18f4d22c180069a2d788d41af17ca108af04c864cd720d9b5b2206b9dc7e
            3     c2efc5d0e3e190028ad14108a9a6b1583d28ce69996169f57310fb15b52a40ae
            4     dc8004517ae308efaaaecf903a1535f3f5419e50d46a475b34a4bb30457a5f75
            5     fc4c2dde8be3c17727bb0de26bdd072a47f5866be29b50ba0ef873a8de525ca8

                   count    pct
column      rank
B_30        1     471445  85.23
            2      76083  13.75
            3       5404   0.98
            4        213   0.04
B_38        1     195241  35.30
            2     125710  22.73
            3     115960  20.96
            4      44417   8.03
            5      29492   5.33
D_114       1     331461  59.92
            2     204009  36.88
            3      17675   3.20
D_116       1     534800  96.68
            2      17675   3.20
            3        670   0.12
D_117       1     145029  26.22
            2     116802  21.12
            3     114112  20.63
            4      66922  12.10
            5      45754   8.27
D_120       1     472618  85.44
            2      62852  11.36
            3      17675   3.20
D_126       1     425833  76.98
            2      89400  16.16
            3      26203   4.74
            4      11709   2.12
D_63        1     412223  74.52
            2      92942  16.80
            3      43686   7.90
            4       2578   0.47
            5       1036   0.19
D_64        1     291303  52.66
            2     152103  27.50
            3      84359  15.25
            4      21739   3.93
            5       3641   0.66
D_66        1     490685  88.71
            2      61838  11.18
            3        622   0.11
D_68        1     277578  50.18
            2     120737  21.83
            3      48110   8.70
            4      47926   8.66
            5      22247   4.02
S_2         1       2662   0.48
            2       2464   0.45
            3       2450   0.44
            4       2442   0.44
            5       2335   0.42
customer_ID 1          8   0.00
            2          8   0.00
            3          7   0.00
            4          7   0.00
            5          7   0.00

In [8]:
# Target Distribution
target_df

          count    pct
target
0       4153582  75.09
1       1377869  24.91

## Task Curation

In [9]:
# We create 1M train and 250k test rows
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_grouped_splits(
    dataset=df,
    n_repeats=1,
    n_splits=1,
    group_on=task_mold.group_on,
    test_size=250_000,
    stratify_on=task_mold.stratify_on,
    group_labels=task_mold.group_labels,
    show_splits=True,
    target_on=task_mold.target_column_name,
)
train_index, test_index = splits[0][0]

# re-use this in a hacky way for sub-sampling
train_splits = curation_recommendations.get_recommended_grouped_splits(
    dataset=df.iloc[train_index].reset_index(drop=True),
    n_repeats=1,
    n_splits=1,
    group_on=task_mold.group_on,
    test_size=1_000_000,
    stratify_on=task_mold.stratify_on,
    group_labels=task_mold.group_labels,
    show_splits=True,
    target_on=task_mold.target_column_name,
)
_, new_train_index = train_splits[0][0]


n_train_rows = len(new_train_index)
df = pd.concat([df.iloc[train_index].iloc[new_train_index], df.iloc[test_index]], axis=0).reset_index(drop=True)
train_index = list(range(n_train_rows))
test_index = list(range(n_train_rows, len(df)))

print(len(train_index), len(test_index))

splits = {0: {0: (train_index, test_index)}}

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="We create default 250k holdout split given the dataset size. This represents 20741 customers in test data, and 82952 in train data.",
    splits=splits
)

Using Stratified Grouped splits.
Using label-per-group grouped splits.
Creating index-based splits for 458913 groups
Using Stratified IID splits.
Repeat 0, Fold 0:
            Train N: 5282196, Test N: 249255
            Target Distribution:
            	Train target distribution: 0.24917799339517124
            	Test target distribution: 0.24738520791960042
            Group Distribution customer_ID:
            	Train: 438172
            	Test: 20741

Using Stratified Grouped splits.
Using label-per-group grouped splits.
Creating index-based splits for 438172 groups
Using Stratified IID splits.
Repeat 0, Fold 0:
            Train N: 4281846, Test N: 1000350
            Target Distribution:
            	Train target distribution: 0.24920139584655776
            	Test target distribution: 0.2490778227620333
            Group Distribution customer_ID:
            	Train: 355220
            	Test: 82952

1000350 249255

## Export

In [10]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to amex_non_iid/versions/019d31ff-7b8d-7085-ad19-77fecaae5d49
019d31ff-7b8d-7085-ad19-77fecaae5d49
9704ca87e399cad523b560b144cca6b2ed5e6aefe3382f3ff495963af65fb67d