### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="qsar_tid_11",
    dataset_year="2015",
    domain_str="chemistry & material science",
    # Data Source
    dataset_source="OpenML",
    original_dataset_source_download_link="https://www.openml.org/d/3050",
    download_description="""
We download the dataset from OpenML to a predefined folder.

mkdir -p local-data-warehouse/qsar_tid_11/ && wget -P local-data-warehouse/qsar_tid_11/ https://www.openml.org/data/download/1674848/11.arff
""",
    # References
    academic_reference_bibtex="""@article{olier2018meta,
  title={Meta-QSAR: a large-scale application of meta-learning to drug design and discovery},
  author={Olier, Ivan and Sadawi, Noureddin and Bickerton, G Richard and Vanschoren, Joaquin and Grosan, Crina and Soldatova, Larisa and King, Ross D},
  journal={Machine Learning},
  volume={107},
  pages={285--311},
  year={2018},
  publisher={Springer}
}
""",
    academic_reference_bibtex_key="olier2018meta",
    license="Public Domain",
    data_tags=["IID"],
    curation_comments="""
- We drop the "MOLECULE_CHEMBL_ID" column.
- We shuffle the data as it has an original distribution shift.
- Only one row has a negative value (-6.24) and is thus extremely out-of-distribution, which is likely results from the target being log scaled in the original domain. We remove this row as it is unclear if this is a scaling or labeling error, but we judge it is in all cases a data artifact.
- We do not log scale the target (it could make sense for this distribution), as the original label is already log transformed.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="MEDIAN_PXC50",
    problem_type="regression",
    objective_metric_name="rmse",
)

## Preprocessing

In [2]:
import pandas as pd
import arff


with open(dataset_mold.path/"11.arff") as f:
    data = arff.load(f)

df = pd.DataFrame(data["data"], columns=[x[0] for x in data["attributes"]])
df.drop(columns=["MOLECULE_CHEMBL_ID"], inplace=True)

# Remove one negative outlier row
df = df[df["MEDIAN_PXC50"] >= 0].reset_index(drop=True)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 5,741
Columns: 1025
Use sampling: False (sample size: 5,741)

Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['FCFP6_1024_0', 'FCFP6_1024_686', 'FCFP6_1024_685', 'FCFP6_1024_684', 'FCFP6_1024_683', 'FCFP6_1024_682', 'FCFP6_1024_681', 'FCFP6_1024_680', 'FCFP6_1024_679', 'FCFP6_1024_678']
Rows remaining as candidates after top-10 filter: 5,726 (of 5,741)

#### Duplicate Report
Total duplicate rows: 116 (2.02% of dataset)
Duplicate rows ignoring target: 483 (8.41% of dataset)
Get column duplicates...

Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,FCFP6_1024_0,FCFP6_1024_1,FCFP6_1024_2,FCFP6_1024_3,FCFP6_1024_4,FCFP6_1024_5,FCFP6_1024_6,FCFP6_1024_7,FCFP6_1024_8,FCFP6_1024_9,FCFP6_1024_10,FCFP6_1024_11,FCFP6_1024_12,FCFP6_1024_13,FCFP6_1024_14,FCFP6_1024_15,FCFP6_1024_16,FCFP6_1024_17,FCFP6_1024_18,FCFP6_1024_19,FCFP6_1024_20,FCFP6_1024_21,FCFP6_1024_22,FCFP6_1024_23,FCFP6_1024_24,FCFP6_1024_25,FCFP6_1024_26,FCFP6_1024_27,FCFP6_1024_28,FCFP6_1024_29,FCFP6_1024_30,FCFP6_1024_31,FCFP6_1024_32,FCFP6_1024_33,FCFP6_1024_34,FCFP6_1024_35,FCFP6_1024_36,FCFP6_1024_37,FCFP6_1024_38,FCFP6_1024_39,FCFP6_1024_40,FCFP6_1024_41,FCFP6_1024_42,FCFP6_1024_43,FCFP6_1024_44,FCFP6_1024_45,FCFP6_1024_46,FCFP6_1024_47,FCFP6_1024_48,FCFP6_1024_49,FCFP6_1024_50,FCFP6_1024_51,FCFP6_1024_52,FCFP6_1024_53,FCFP6_1024_54,FCFP6_1024_55,FCFP6_1024_56,FCFP6_1024_57,FCFP6_1024_58,FCFP6_1024_59,FCFP6_1024_60,FCFP6_1024_61,FCFP6_1024_62,FCFP6_1024_63,FCFP6_1024_64,FCFP6_1024_65,FCFP6_1024_66,FCFP6_1024_67,FCFP6_1024_68,FCFP6_1024_69,FCFP6_1024_70,FCFP6_1024_71,FCFP6_1024_72,FCFP6_1024_73,FCFP6_1024_74,FCFP6_1024_75,FCFP6_1024_76,FCFP6_1024_77,FCFP6_1024_78,FCFP6_1024_79,FCFP6_1024_80,FCFP6_1024_81,FCFP6_1024_82,FCFP6_1024_83,FCFP6_1024_84,FCFP6_1024_85,FCFP6_1024_86,FCFP6_1024_87,FCFP6_1024_88,FCFP6_1024_89,FCFP6_1024_90,FCFP6_1024_91,FCFP6_1024_92,FCFP6_1024_93,FCFP6_1024_94,FCFP6_1024_95,FCFP6_1024_96,FCFP6_1024_97,FCFP6_1024_98,FCFP6_1024_99,FCFP6_1024_100,FCFP6_1024_101,FCFP6_1024_102,FCFP6_1024_103,FCFP6_1024_104,FCFP6_1024_105,FCFP6_1024_106,FCFP6_1024_107,FCFP6_1024_108,FCFP6_1024_109,FCFP6_1024_110,FCFP6_1024_111,FCFP6_1024_112,FCFP6_1024_113,FCFP6_1024_114,FCFP6_1024_115,FCFP6_1024_116,FCFP6_1024_117,FCFP6_1024_118,FCFP6_1024_119,FCFP6_1024_120,FCFP6_1024_121,FCFP6_1024_122,FCFP6_1024_123,FCFP6_1024_124,FCFP6_1024_125,FCFP6_1024_126,FCFP6_1024_127,FCFP6_1024_128,FCFP6_1024_129,FCFP6_1024_130,FCFP6_1024_131,FCFP6_1024_132,FCFP6_1024_133,FCFP6_1024_134,FCFP6_1024_135,FCFP6_1024_136,FCFP6_1024_137,FCFP6_1024_138,FCFP6_1024_139,FCFP6_1024_140,FCFP6_1024_141,FCFP6_1024_142,FCFP6_1024_143,FCFP6_1024_144,FCFP6_1024_145,FCFP6_1024_146,FCFP6_1024_147,FCFP6_1024_148,FCFP6_1024_149,FCFP6_1024_150,FCFP6_1024_151,FCFP6_1024_152,FCFP6_1024_153,FCFP6_1024_154,FCFP6_1024_155,FCFP6_1024_156,FCFP6_1024_157,FCFP6_1024_158,FCFP6_1024_159,FCFP6_1024_160,FCFP6_1024_161,FCFP6_1024_162,FCFP6_1024_163,FCFP6_1024_164,FCFP6_1024_165,FCFP6_1024_166,FCFP6_1024_167,FCFP6_1024_168,FCFP6_1024_169,FCFP6_1024_170,FCFP6_1024_171,FCFP6_1024_172,FCFP6_1024_173,FCFP6_1024_174,FCFP6_1024_175,FCFP6_1024_176,FCFP6_1024_177,FCFP6_1024_178,FCFP6_1024_179,FCFP6_1024_180,FCFP6_1024_181,FCFP6_1024_182,FCFP6_1024_183,FCFP6_1024_184,FCFP6_1024_185,FCFP6_1024_186,FCFP6_1024_187,FCFP6_1024_188,FCFP6_1024_189,FCFP6_1024_190,FCFP6_1024_191,FCFP6_1024_192,FCFP6_1024_193,FCFP6_1024_194,FCFP6_1024_195,FCFP6_1024_196,FCFP6_1024_197,FCFP6_1024_198,FCFP6_1024_199,FCFP6_1024_200,FCFP6_1024_201,FCFP6_1024_202,FCFP6_1024_203,FCFP6_1024_204,FCFP6_1024_205,FCFP6_1024_206,FCFP6_1024_207,FCFP6_1024_208,FCFP6_1024_209,FCFP6_1024_210,FCFP6_1024_211,FCFP6_1024_212,FCFP6_1024_213,FCFP6_1024_214,FCFP6_1024_215,FCFP6_1024_216,FCFP6_1024_217,FCFP6_1024_218,FCFP6_1024_219,FCFP6_1024_220,FCFP6_1024_221,FCFP6_1024_222,FCFP6_1024_223,FCFP6_1024_224,FCFP6_1024_225,FCFP6_1024_226,FCFP6_1024_227,FCFP6_1024_228,FCFP6_1024_229,FCFP6_1024_230,FCFP6_1024_231,FCFP6_1024_232,FCFP6_1024_233,FCFP6_1024_234,FCFP6_1024_235,FCFP6_1024_236,FCFP6_1024_237,FCFP6_1024_238,FCFP6_1024_239,FCFP6_1024_240,FCFP6_1024_241,FCFP6_1024_242,FCFP6_1024_243,FCFP6_1024_244,FCFP6_1024_245,FCFP6_1024_246,FCFP6_1024_247,FCFP6_1024_248,FCFP6_1024_249,FCFP6_1024_250,FCFP6_1024_251,FCFP6_1024_252,FCFP6_1024_253,FCFP6_1024_254,FCFP6_1024_255,FCFP6_1024_256,FCFP6_1024_257,FCFP6_1024_258,FCFP6_1024_259,FCFP6_1024_260,FCFP6_1024_261,FCFP6_1024_262,FCFP6_1024_263,FCFP6_1024_264,FCFP6_1024_265,FCFP6_1024_266,FCFP6_1024_267,FCFP6_1024_268,FCFP6_1024_269,FCFP6_1024_270,FCFP6_1024_271,FCFP6_1024_272,FCFP6_1024_273,FCFP6_1024_274,FCFP6_1024_275,FCFP6_1024_276,FCFP6_1024_277,FCFP6_1024_278,FCFP6_1024_279,FCFP6_1024_280,FCFP6_1024_281,FCFP6_1024_282,FCFP6_1024_283,FCFP6_1024_284,FCFP6_1024_285,FCFP6_1024_286,FCFP6_1024_287,FCFP6_1024_288,FCFP6_1024_289,FCFP6_1024_290,FCFP6_1024_291,FCFP6_1024_292,FCFP6_1024_293,FCFP6_1024_294,FCFP6_1024_295,FCFP6_1024_296,FCFP6_1024_297,FCFP6_1024_298,FCFP6_1024_299,FCFP6_1024_300,FCFP6_1024_301,FCFP6_1024_302,FCFP6_1024_303,FCFP6_1024_304,FCFP6_1024_305,FCFP6_1024_306,FCFP6_1024_307,FCFP6_1024_308,FCFP6_1024_309,FCFP6_1024_310,FCFP6_1024_311,FCFP6_1024_312,FCFP6_1024_313,FCFP6_1024_314,FCFP6_1024_315,FCFP6_1024_316,FCFP6_1024_317,FCFP6_1024_318,FCFP6_1024_319,FCFP6_1024_320,FCFP6_1024_321,FCFP6_1024_322,FCFP6_1024_323,FCFP6_1024_324,FCFP6_1024_325,FCFP6_1024_326,FCFP6_1024_327,FCFP6_1024_328,FCFP6_1024_329,FCFP6_1024_330,FCFP6_1024_331,FCFP6_1024_332,FCFP6_1024_333,FCFP6_1024_334,FCFP6_1024_335,FCFP6_1024_336,FCFP6_1024_337,FCFP6_1024_338,FCFP6_1024_339,FCFP6_1024_340,FCFP6_1024_341,FCFP6_1024_342,FCFP6_1024_343,FCFP6_1024_344,FCFP6_1024_345,FCFP6_1024_346,FCFP6_1024_347,FCFP6_1024_348,FCFP6_1024_349,FCFP6_1024_350,FCFP6_1024_351,FCFP6_1024_352,FCFP6_1024_353,FCFP6_1024_354,FCFP6_1024_355,FCFP6_1024_356,FCFP6_1024_357,FCFP6_1024_358,FCFP6_1024_359,FCFP6_1024_360,FCFP6_1024_361,FCFP6_1024_362,FCFP6_1024_363,FCFP6_1024_364,FCFP6_1024_365,FCFP6_1024_366,FCFP6_1024_367,FCFP6_1024_368,FCFP6_1024_369,FCFP6_1024_370,FCFP6_1024_371,FCFP6_1024_372,FCFP6_1024_373,FCFP6_1024_374,FCFP6_1024_375,FCFP6_1024_376,FCFP6_1024_377,FCFP6_1024_378,FCFP6_1024_379,FCFP6_1024_380,FCFP6_1024_381,FCFP6_1024_382,FCFP6_1024_383,FCFP6_1024_384,FCFP6_1024_385,FCFP6_1024_386,FCFP6_1024_387,FCFP6_1024_388,FCFP6_1024_389,FCFP6_1024_390,FCFP6_1024_391,FCFP6_1024_392,FCFP6_1024_393,FCFP6_1024_394,FCFP6_1024_395,FCFP6_1024_396,FCFP6_1024_397,FCFP6_1024_398,FCFP6_1024_399,FCFP6_1024_400,FCFP6_1024_401,FCFP6_1024_402,FCFP6_1024_403,FCFP6_1024_404,FCFP6_1024_405,FCFP6_1024_406,FCFP6_1024_407,FCFP6_1024_408,FCFP6_1024_409,FCFP6_1024_410,FCFP6_1024_411,FCFP6_1024_412,FCFP6_1024_413,FCFP6_1024_414,FCFP6_1024_415,FCFP6_1024_416,FCFP6_1024_417,FCFP6_1024_418,FCFP6_1024_419,FCFP6_1024_420,FCFP6_1024_421,FCFP6_1024_422,FCFP6_1024_423,FCFP6_1024_424,FCFP6_1024_425,FCFP6_1024_426,FCFP6_1024_427,FCFP6_1024_428,FCFP6_1024_429,FCFP6_1024_430,FCFP6_1024_431,FCFP6_1024_432,FCFP6_1024_433,FCFP6_1024_434,FCFP6_1024_435,FCFP6_1024_436,FCFP6_1024_437,FCFP6_1024_438,FCFP6_1024_439,FCFP6_1024_440,FCFP6_1024_441,FCFP6_1024_442,FCFP6_1024_443,FCFP6_1024_444,FCFP6_1024_445,FCFP6_1024_446,FCFP6_1024_447,FCFP6_1024_448,FCFP6_1024_449,FCFP6_1024_450,FCFP6_1024_451,FCFP6_1024_452,FCFP6_1024_453,FCFP6_1024_454,FCFP6_1024_455,FCFP6_1024_456,FCFP6_1024_457,FCFP6_1024_458,FCFP6_1024_459,FCFP6_1024_460,FCFP6_1024_461,FCFP6_1024_462,FCFP6_1024_463,FCFP6_1024_464,FCFP6_1024_465,FCFP6_1024_466,FCFP6_1024_467,FCFP6_1024_468,FCFP6_1024_469,FCFP6_1024_470,FCFP6_1024_471,FCFP6_1024_472,FCFP6_1024_473,FCFP6_1024_474,FCFP6_1024_475,FCFP6_1024_476,FCFP6_1024_477,FCFP6_1024_478,FCFP6_1024_479,FCFP6_1024_480,FCFP6_1024_481,FCFP6_1024_482,FCFP6_1024_483,FCFP6_1024_484,FCFP6_1024_485,FCFP6_1024_486,FCFP6_1024_487,FCFP6_1024_488,FCFP6_1024_489,FCFP6_1024_490,FCFP6_1024_491,FCFP6_1024_492,FCFP6_1024_493,FCFP6_1024_494,FCFP6_1024_495,FCFP6_1024_496,FCFP6_1024_497,FCFP6_1024_498,FCFP6_1024_499,FCFP6_1024_500,FCFP6_1024_501,FCFP6_1024_502,FCFP6_1024_503,FCFP6_1024_504,FCFP6_1024_505,FCFP6_1024_506,FCFP6_1024_507,FCFP6_1024_508,FCFP6_1024_509,FCFP6_1024_510,FCFP6_1024_511,FCFP6_1024_512,FCFP6_1024_513,FCFP6_1024_514,FCFP6_1024_515,FCFP6_1024_516,FCFP6_1024_517,FCFP6_1024_518,FCFP6_1024_519,FCFP6_1024_520,FCFP6_1024_521,FCFP6_1024_522,FCFP6_1024_523,FCFP6_1024_524,FCFP6_1024_525,FCFP6_1024_526,FCFP6_1024_527,FCFP6_1024_528,FCFP6_1024_529,FCFP6_1024_530,FCFP6_1024_531,FCFP6_1024_532,FCFP6_1024_533,FCFP6_1024_534,FCFP6_1024_535,FCFP6_1024_536,FCFP6_1024_537,FCFP6_1024_538,FCFP6_1024_539,FCFP6_1024_540,FCFP6_1024_541,FCFP6_1024_542,FCFP6_1024_543,FCFP6_1024_544,FCFP6_1024_545,FCFP6_1024_546,FCFP6_1024_547,FCFP6_1024_548,FCFP6_1024_549,FCFP6_1024_550,FCFP6_1024_551,FCFP6_1024_552,FCFP6_1024_553,FCFP6_1024_554,FCFP6_1024_555,FCFP6_1024_556,FCFP6_1024_557,FCFP6_1024_558,FCFP6_1024_559,FCFP6_1024_560,FCFP6_1024_561,FCFP6_1024_562,FCFP6_1024_563,FCFP6_1024_564,FCFP6_1024_565,FCFP6_1024_566,FCFP6_1024_567,FCFP6_1024_568,FCFP6_1024_569,FCFP6_1024_570,FCFP6_1024_571,FCFP6_1024_572,FCFP6_1024_573,FCFP6_1024_574,FCFP6_1024_575,FCFP6_1024_576,FCFP6_1024_577,FCFP6_1024_578,FCFP6_1024_579,FCFP6_1024_580,FCFP6_1024_581,FCFP6_1024_582,FCFP6_1024_583,FCFP6_1024_584,FCFP6_1024_585,FCFP6_1024_586,FCFP6_1024_587,FCFP6_1024_588,FCFP6_1024_589,FCFP6_1024_590,FCFP6_1024_591,FCFP6_1024_592,FCFP6_1024_593,FCFP6_1024_594,FCFP6_1024_595,FCFP6_1024_596,FCFP6_1024_597,FCFP6_1024_598,FCFP6_1024_599,FCFP6_1024_600,FCFP6_1024_601,FCFP6_1024_602,FCFP6_1024_603,FCFP6_1024_604,FCFP6_1024_605,FCFP6_1024_606,FCFP6_1024_607,FCFP6_1024_608,FCFP6_1024_609,FCFP6_1024_610,FCFP6_1024_611,FCFP6_1024_612,FCFP6_1024_613,FCFP6_1024_614,FCFP6_1024_615,FCFP6_1024_616,FCFP6_1024_617,FCFP6_1024_618,FCFP6_1024_619,FCFP6_1024_620,FCFP6_1024_621,FCFP6_1024_622,FCFP6_1024_623,FCFP6_1024_624,FCFP6_1024_625,FCFP6_1024_626,FCFP6_1024_627,FCFP6_1024_628,FCFP6_1024_629,FCFP6_1024_630,FCFP6_1024_631,FCFP6_1024_632,FCFP6_1024_633,FCFP6_1024_634,FCFP6_1024_635,FCFP6_1024_636,FCFP6_1024_637,FCFP6_1024_638,FCFP6_1024_639,FCFP6_1024_640,FCFP6_1024_641,FCFP6_1024_642,FCFP6_1024_643,FCFP6_1024_644,FCFP6_1024_645,FCFP6_1024_646,FCFP6_1024_647,FCFP6_1024_648,FCFP6_1024_649,FCFP6_1024_650,FCFP6_1024_651,FCFP6_1024_652,FCFP6_1024_653,FCFP6_1024_654,FCFP6_1024_655,FCFP6_1024_656,FCFP6_1024_657,FCFP6_1024_658,FCFP6_1024_659,FCFP6_1024_660,FCFP6_1024_661,FCFP6_1024_662,FCFP6_1024_663,FCFP6_1024_664,FCFP6_1024_665,FCFP6_1024_666,FCFP6_1024_667,FCFP6_1024_668,FCFP6_1024_669,FCFP6_1024_670,FCFP6_1024_671,FCFP6_1024_672,FCFP6_1024_673,FCFP6_1024_674,FCFP6_1024_675,FCFP6_1024_676,FCFP6_1024_677,FCFP6_1024_678,FCFP6_1024_679,FCFP6_1024_680,FCFP6_1024_681,FCFP6_1024_682,FCFP6_1024_683,FCFP6_1024_684,FCFP6_1024_685,FCFP6_1024_686,FCFP6_1024_687,FCFP6_1024_688,FCFP6_1024_689,FCFP6_1024_690,FCFP6_1024_691,FCFP6_1024_692,FCFP6_1024_693,FCFP6_1024_694,FCFP6_1024_695,FCFP6_1024_696,FCFP6_1024_697,FCFP6_1024_698,FCFP6_1024_699,FCFP6_1024_700,FCFP6_1024_701,FCFP6_1024_702,FCFP6_1024_703,FCFP6_1024_704,FCFP6_1024_705,FCFP6_1024_706,FCFP6_1024_707,FCFP6_1024_708,FCFP6_1024_709,FCFP6_1024_710,FCFP6_1024_711,FCFP6_1024_712,FCFP6_1024_713,FCFP6_1024_714,FCFP6_1024_715,FCFP6_1024_716,FCFP6_1024_717,FCFP6_1024_718,FCFP6_1024_719,FCFP6_1024_720,FCFP6_1024_721,FCFP6_1024_722,FCFP6_1024_723,FCFP6_1024_724,FCFP6_1024_725,FCFP6_1024_726,FCFP6_1024_727,FCFP6_1024_728,FCFP6_1024_729,FCFP6_1024_730,FCFP6_1024_731,FCFP6_1024_732,FCFP6_1024_733,FCFP6_1024_734,FCFP6_1024_735,FCFP6_1024_736,FCFP6_1024_737,FCFP6_1024_738,FCFP6_1024_739,FCFP6_1024_740,FCFP6_1024_741,FCFP6_1024_742,FCFP6_1024_743,FCFP6_1024_744,FCFP6_1024_745,FCFP6_1024_746,FCFP6_1024_747,FCFP6_1024_748,FCFP6_1024_749,FCFP6_1024_750,FCFP6_1024_751,FCFP6_1024_752,FCFP6_1024_753,FCFP6_1024_754,FCFP6_1024_755,FCFP6_1024_756,FCFP6_1024_757,FCFP6_1024_758,FCFP6_1024_759,FCFP6_1024_760,FCFP6_1024_761,FCFP6_1024_762,FCFP6_1024_763,FCFP6_1024_764,FCFP6_1024_765,FCFP6_1024_766,FCFP6_1024_767,FCFP6_1024_768,FCFP6_1024_769,FCFP6_1024_770,FCFP6_1024_771,FCFP6_1024_772,FCFP6_1024_773,FCFP6_1024_774,FCFP6_1024_775,FCFP6_1024_776,FCFP6_1024_777,FCFP6_1024_778,FCFP6_1024_779,FCFP6_1024_780,FCFP6_1024_781,FCFP6_1024_782,FCFP6_1024_783,FCFP6_1024_784,FCFP6_1024_785,FCFP6_1024_786,FCFP6_1024_787,FCFP6_1024_788,FCFP6_1024_789,FCFP6_1024_790,FCFP6_1024_791,FCFP6_1024_792,FCFP6_1024_793,FCFP6_1024_794,FCFP6_1024_795,FCFP6_1024_796,FCFP6_1024_797,FCFP6_1024_798,FCFP6_1024_799,FCFP6_1024_800,FCFP6_1024_801,FCFP6_1024_802,FCFP6_1024_803,FCFP6_1024_804,FCFP6_1024_805,FCFP6_1024_806,FCFP6_1024_807,FCFP6_1024_808,FCFP6_1024_809,FCFP6_1024_810,FCFP6_1024_811,FCFP6_1024_812,FCFP6_1024_813,FCFP6_1024_814,FCFP6_1024_815,FCFP6_1024_816,FCFP6_1024_817,FCFP6_1024_818,FCFP6_1024_819,FCFP6_1024_820,FCFP6_1024_821,FCFP6_1024_822,FCFP6_1024_823,FCFP6_1024_824,FCFP6_1024_825,FCFP6_1024_826,FCFP6_1024_827,FCFP6_1024_828,FCFP6_1024_829,FCFP6_1024_830,FCFP6_1024_831,FCFP6_1024_832,FCFP6_1024_833,FCFP6_1024_834,FCFP6_1024_835,FCFP6_1024_836,FCFP6_1024_837,FCFP6_1024_838,FCFP6_1024_839,FCFP6_1024_840,FCFP6_1024_841,FCFP6_1024_842,FCFP6_1024_843,FCFP6_1024_844,FCFP6_1024_845,FCFP6_1024_846,FCFP6_1024_847,FCFP6_1024_848,FCFP6_1024_849,FCFP6_1024_850,FCFP6_1024_851,FCFP6_1024_852,FCFP6_1024_853,FCFP6_1024_854,FCFP6_1024_855,FCFP6_1024_856,FCFP6_1024_857,FCFP6_1024_858,FCFP6_1024_859,FCFP6_1024_860,FCFP6_1024_861,FCFP6_1024_862,FCFP6_1024_863,FCFP6_1024_864,FCFP6_1024_865,FCFP6_1024_866,FCFP6_1024_867,FCFP6_1024_868,FCFP6_1024_869,FCFP6_1024_870,FCFP6_1024_871,FCFP6_1024_872,FCFP6_1024_873,FCFP6_1024_874,FCFP6_1024_875,FCFP6_1024_876,FCFP6_1024_877,FCFP6_1024_878,FCFP6_1024_879,FCFP6_1024_880,FCFP6_1024_881,FCFP6_1024_882,FCFP6_1024_883,FCFP6_1024_884,FCFP6_1024_885,FCFP6_1024_886,FCFP6_1024_887,FCFP6_1024_888,FCFP6_1024_889,FCFP6_1024_890,FCFP6_1024_891,FCFP6_1024_892,FCFP6_1024_893,FCFP6_1024_894,FCFP6_1024_895,FCFP6_1024_896,FCFP6_1024_897,FCFP6_1024_898,FCFP6_1024_899,FCFP6_1024_900,FCFP6_1024_901,FCFP6_1024_902,FCFP6_1024_903,FCFP6_1024_904,FCFP6_1024_905,FCFP6_1024_906,FCFP6_1024_907,FCFP6_1024_908,FCFP6_1024_909,FCFP6_1024_910,FCFP6_1024_911,FCFP6_1024_912,FCFP6_1024_913,FCFP6_1024_914,FCFP6_1024_915,FCFP6_1024_916,FCFP6_1024_917,FCFP6_1024_918,FCFP6_1024_919,FCFP6_1024_920,FCFP6_1024_921,FCFP6_1024_922,FCFP6_1024_923,FCFP6_1024_924,FCFP6_1024_925,FCFP6_1024_926,FCFP6_1024_927,FCFP6_1024_928,FCFP6_1024_929,FCFP6_1024_930,FCFP6_1024_931,FCFP6_1024_932,FCFP6_1024_933,FCFP6_1024_934,FCFP6_1024_935,FCFP6_1024_936,FCFP6_1024_937,FCFP6_1024_938,FCFP6_1024_939,FCFP6_1024_940,FCFP6_1024_941,FCFP6_1024_942,FCFP6_1024_943,FCFP6_1024_944,FCFP6_1024_945,FCFP6_1024_946,FCFP6_1024_947,FCFP6_1024_948,FCFP6_1024_949,FCFP6_1024_950,FCFP6_1024_951,FCFP6_1024_952,FCFP6_1024_953,FCFP6_1024_954,FCFP6_1024_955,FCFP6_1024_956,FCFP6_1024_957,FCFP6_1024_958,FCFP6_1024_959,FCFP6_1024_960,FCFP6_1024_961,FCFP6_1024_962,FCFP6_1024_963,FCFP6_1024_964,FCFP6_1024_965,FCFP6_1024_966,FCFP6_1024_967,FCFP6_1024_968,FCFP6_1024_969,FCFP6_1024_970,FCFP6_1024_971,FCFP6_1024_972,FCFP6_1024_973,FCFP6_1024_974,FCFP6_1024_975,FCFP6_1024_976,FCFP6_1024_977,FCFP6_1024_978,FCFP6_1024_979,FCFP6_1024_980,FCFP6_1024_981,FCFP6_1024_982,FCFP6_1024_983,FCFP6_1024_984,FCFP6_1024_985,FCFP6_1024_986,FCFP6_1024_987,FCFP6_1024_988,FCFP6_1024_989,FCFP6_1024_990,FCFP6_1024_991,FCFP6_1024_992,FCFP6_1024_993,FCFP6_1024_994,FCFP6_1024_995,FCFP6_1024_996,FCFP6_1024_997,FCFP6_1024_998,FCFP6_1024_999,FCFP6_1024_1000,FCFP6_1024_1001,FCFP6_1024_1002,FCFP6_1024_1003,FCFP6_1024_1004,FCFP6_1024_1005,FCFP6_1024_1006,FCFP6_1024_1007,FCFP6_1024_1008,FCFP6_1024_1009,FCFP6_1024_1010,FCFP6_1024_1011,FCFP6_1024_1012,FCFP6_1024_1013,FCFP6_1024_1014,FCFP6_1024_1015,FCFP6_1024_1016,FCFP6_1024_1017,FCFP6_1024_1018,FCFP6_1024_1019,FCFP6_1024_1020,FCFP6_1024_1021,FCFP6_1024_1022,FCFP6_1024_1023,MEDIAN_PXC50
0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.721

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,FCFP6_1024_0,float64,0.0,0.0,2.0,"1.0, 0.0"
1,FCFP6_1024_1,float64,0.0,0.0,2.0,"1.0, 0.0"
2,FCFP6_1024_2,float64,0.0,0.0,2.0,"0.0, 1.0"
3,FCFP6_1024_3,float64,0.0,0.0,2.0,"1.0, 0.0"
4,FCFP6_1024_4,float64,0.0,0.0,2.0,"0.0, 1.0"
5,FCFP6_1024_5,float64,0.0,0.0,2.0,"0.0, 1.0"
6,FCFP6_1024_6,float64,0.0,0.0,2.0,"0.0, 1.0"
7,FCFP6_1024_7,float64,0.0,0.0,2.0,"0.0, 1.0"
8,FCFP6_1024_8,float64,0.0,0.0,2.0,"0.0, 1.0"
9,FCFP6_1024_9,float64,0.0,0.0,2.0,"0.0, 1.0"
10,FCFP6_1024_10,float64,0.0,0.0,2.0,"0.0, 1.0"
11,FCFP6_1024_11,float64,0.0,0.0,2.0,"0.0, 1.0"
12,FCFP6_1024_12,float64,0.0,0.0,2.0,"0.0, 1.0"
13,FCFP6_1024_13,float64,0.0,0.0,2.0,"0.0, 1.0"
14,FCFP6_1024_14,float64,0.0,0.0,2.0,"0.0, 1.0"
15,FCFP6_1024_15,float64,0.0,0.0,2.0,"0.0, 1.0"
16,FCFP6_1024_16,float64,0.0,0.0,2.0,"1.0, 0.0"
17,FCFP6_1024_17,float64,0.0,0.0,2.0,"1.0, 0.0"
18,FCFP6_1024_18,float64,0.0,0.0,2.0,"0.0, 1.0"
19,FCFP6_1024_19,float64,0.0,0.0,2.0,"0.0, 1.0"
20,FCFP6_1024_20,float64,0.0,0.0,2.0,"0.0, 1.0"
21,FCFP6_1024_21,float64,0.0,0.0,2.0,"0.0, 1.0"
22,FCFP6_1024_22,float64,0.0,0.0,2.0,"0.0, 1.0"
23,FCFP6_1024_23,float64,0.0,0.0,2.0,"0.0, 1.0"
24,FCFP6_1024_24,float64,0.0,0.0,2.0,"1.0, 0.0"
25,FCFP6_1024_25,float64,0.0,0.0,2.0,"0.0, 1.0"
26,FCFP6_1024_26,float64,0.0,0.0,2.0,"0.0, 1.0"
27,FCFP6_1024_27,float64,0.0,0.0,2.0,"0.0, 1.0"
28,FCFP6_1024_28,float64,0.0,0.0,2.0,"0.0, 1.0"
29,FCFP6_1024_29,float64,0.0,0.0,2.0,"0.0, 1.0"
30,FCFP6_1024_30,float64,0.0,0.0,2.0,"0.0, 1.0"
31,FCFP6_1024_31,float64,0.0,0.0,2.0,"0.0, 1.0"
32,FCFP6_1024_32,float64,0.0,0.0,2.0,"0.0, 1.0"
33,FCFP6_1024_33,float64,0.0,0.0,2.0,"0.0, 1.0"
34,FCFP6_1024_34,float64,0.0,0.0,2.0,"0.0, 1.0"
35,FCFP6_1024_35,float64,0.0,0.0,2.0,"0.0, 1.0"
36,FCFP6_1024_36,float64,0.0,0.0,2.0,"0.0, 1.0"
37,FCFP6_1024_37,float64,0.0,0.0,2.0,"0.0, 1.0"
38,FCFP6_1024_38,float64,0.0,0.0,2.0,"0.0, 1.0"
39,FCFP6_1024_39,float64,0.0,0.0,2.0,"0.0, 1.0"
40,FCFP6_1024_40,float64,0.0,0.0,2.0,"0.0, 1.0"
41,FCFP6_1024_41,float64,0.0,0.0,2.0,"0.0, 1.0"
42,FCFP6_1024_42,float64,0.0,0.0,2.0,"0.0, 1.0"
43,FCFP6_1024_43,float64,0.0,0.0,2.0,"0.0, 1.0"
44,FCFP6_1024_44,float64,0.0,0.0,2.0,"0.0, 1.0"
45,FCFP6_1024_45,float64,0.0,0.0,2.0,"0.0, 1.0"
46,FCFP6_1024_46,float64,0.0,0.0,2.0,"0.0, 1.0"
47,FCFP6_1024_47,float64,0.0,0.0,2.0,"0.0, 1.0"
48,FCFP6_1024_48,float64,0.0,0.0,2.0,"0.0, 1.0"
49,FCFP6_1024_49,float64,0.0,0.0,2.0,"0.0, 1.0"
50,FCFP6_1024_50,float64,0.0,0.0,2.0,"0.0, 1.0"
51,FCFP6_1024_51,float64,0.0,0.0,2.0,"0.0, 1.0"
52,FCFP6_1024_52,float64,0.0,0.0,2.0,"0.0, 1.0"
53,FCFP6_1024_53,float64,0.0,0.0,2.0,"0.0, 1.0"
54,FCFP6_1024_54,float64,0.0,0.0,2.0,"0.0, 1.0"
55,FCFP6_1024_55,float64,0.0,0.0,2.0,"0.0, 1.0"
56,FCFP6_1024_56,float64,0.0,0.0,2.0,"0.0, 1.0"
57,FCFP6_1024_57,float64,0.0,0.0,2.0,"0.0, 1.0"
58,FCFP6_1024_58,float64,0.0,0.0,2.0,"0.0, 1.0"
59,FCFP6_1024_59,float64,0.0,0.0,2.0,"0.0, 1.0"
60,FCFP6_1024_60,float64,0.0,0.0,2.0,"0.0, 1.0"
61,FCFP6_1024_61,float64,0.0,0.0,2.0,"0.0, 1.0"
62,FCFP6_1024_62,float64,0.0,0.0,2.0,"0.0, 1.0"
63,FCFP6_1024_63,float64,0.0,0.0,2.0,"0.0, 1.0"
64,FCFP6_1024_64,float64,0.0,0.0,2.0,"0.0, 1.0"
65,FCFP6_1024_65,float64,0.0,0.0,2.0,"0.0, 1.0"
66,FCFP6_1024_66,float64,0.0,0.0,2.0,"0.0, 1.0"
67,FCFP6_1024_67,float64,0.0,0.0,2.0,"0.0, 1.0"
68,FCFP6_1024_68,float64,0.0,0.0,2.0,"0.0, 1.0"
69,FCFP6_1024_69,float64,0.0,0.0,2.0,"0.0, 1.0"
70,FCFP6_1024_70,float64,0.0,0.0,2.0,"0.0, 1.0"
71,FCFP6_1024_71,float64,0.0,0.0,2.0,"0.0, 1.0"
72,FCFP6_1024_72,float64,0.0,0.0,2.0,"0.0, 1.0"
73,FCFP6_1024_73,float64,0.0,0.0,2.0,"0.0, 1.0"
74,FCFP6_1024_74,float64,0.0,0.0,2.0,"0.0, 1.0"
75,FCFP6_1024_75,float64,0.0,0.0,2.0,"0.0, 1.0"
76,FCFP6_1024_76,float64,0.0,0.0,2.0,"0.0, 1.0"
77,FCFP6_1024_77,float64,0.0,0.0,2.0,"0.0, 1.0"
78,FCFP6_1024_78,float64,0.0,0.0,2.0,"0.0, 1.0"
79,FCFP6_1024_79,float64,0.0,0.0,2.0,"0.0, 1.0"
80,FCFP6_1024_80,float64,0.0,0.0,2.0,"0.0, 1.0"
81,FCFP6_1024_81,float64,0.0,0.0,2.0,"0.0, 1.0"
82,FCFP6_1024_82,float64,0.0,0.0,2.0,"0.0, 1.0"
83,FCFP6_1024_83,float64,0.0,0.0,2.0,"0.0, 1.0"
84,FCFP6_1024_84,float64,0.0,0.0,2.0,"0.0, 1.0"
85,FCFP6_1024_85,float64,0.0,0.0,2.0,"0.0, 1.0"
86,FCFP6_1024_86,float64,0.0,0.0,2.0,"0.0, 1.0"
87,FCFP6_1024_87,float64,0.0,0.0,2.0,"0.0, 1.0"
88,FCFP6_1024_88,float64,0.0,0.0,2.0,"0.0, 1.0"
89,FCFP6_1024_89,float64,0.0,0.0,2.0,"0.0, 1.0"
90,FCFP6_1024_90,float64,0.0,0.0,2.0,"0.0, 1.0"
91,FCFP6_1024_91,float64,0.0,0.0,2.0,"0.0, 1.0"
92,FCFP6_1024_92,float64,0.0,0.0,2.0,"0.0, 1.0"
93,FCFP6_1024_93,float64,0.0,0.0,2.0,"0.0, 1.0"
94,FCFP6_1024_94,float64,0.0,0.0,2.0,"0.0, 1.0"
95,FCFP6_1024_95,float64,0.0,0.0,2.0,"0.0, 1.0"
96,FCFP6_1024_96,float64,0.0,0.0,2.0,"0.0, 1.0"
97,FCFP6_1024_97,float64,0.0,0.0,2.0,"0.0, 1.0"
98,FCFP6_1024_98,float64,0.0,0.0,2.0,"0.0, 1.0"
99,FCFP6_1024_99,float64,0.0,0.0,2.0,"0.0, 1.0"
100,FCFP6_1024_100,float64,0.0,0.0,2.0,"0.0, 1.0"
101,FCFP6_1024_101,float64,0.0,0.0,2.0,"0.0, 1.0"
102,FCFP6_1024_102,float64,0.0,0.0,2.0,"0.0, 1.0"
103,FCFP6_1024_103,float64,0.0,0.0,2.0,"0.0, 1.0"
104,FCFP6_1024_104,float64,0.0,0.0,2.0,"0.0, 1.0"
105,FCFP6_1024_105,float64,0.0,0.0,2.0,"0.0, 1.0"
106,FCFP6_1024_106,float64,0.0,0.0,2.0,"0.0, 1.0"
107,FCFP6_1024_107,float64,0.0,0.0,2.0,"0.0, 1.0"
108,FCFP6_1024_108,float64,0.0,0.0,2.0,"0.0, 1.0"
109,FCFP6_1024_109,float64,0.0,0.0,2.0,"0.0, 1.0"
110,FCFP6_1024_110,float64,0.0,0.0,2.0,"0.0, 1.0"
111,FCFP6_1024_111,float64,0.0,0.0,2.0,"0.0, 1.0"
112,FCFP6_1024_112,float64,0.0,0.0,2.0,"0.0, 1.0"
113,FCFP6_1024_113,float64,0.0,0.0,2.0,"0.0, 1.0"
114,FCFP6_1024_114,float64,0.0,0.0,2.0,"0.0, 1.0"
115,FCFP6_1024_115,float64,0.0,0.0,2.0,"0.0, 1.0"
116,FCFP6_1024_116,float64,0.0,0.0,2.0,"0.0, 1.0"
117,FCFP6_1024_117,float64,0.0,0.0,2.0,"0.0, 1.0"
118,FCFP6_1024_118,float64,0.0,0.0,2.0,"0.0, 1.0"
119,FCFP6_1024_119,float64,0.0,0.0,2.0,"0.0, 1.0"
120,FCFP6_1024_120,float64,0.0,0.0,2.0,"0.0, 1.0"
121,FCFP6_1024_121,float64,0.0,0.0,2.0,"0.0, 1.0"
122,FCFP6_1024_122,float64,0.0,0.0,2.0,"0.0, 1.0"
123,FCFP6_1024_123,float64,0.0,0.0,2.0,"0.0, 1.0"
124,FCFP6_1024_124,float64,0.0,0.0,2.0,"0.0, 1.0"
125,FCFP6_1024_125,float64,0.0,0.0,2.0,"0.0, 1.0"
126,FCFP6_1024_126,float64,0.0,0.0,2.0,"0.0, 1.0"
127,FCFP6_1024_127,float64,0.0,0.0,2.0,"0.0, 1.0"
128,FCFP6_1024_128,float64,0.0,0.0,2.0,"0.0, 1.0"
129,FCFP6_1024_129,float64,0.0,0.0,2.0,"0.0, 1.0"
130,FCFP6_1024_130,float64,0.0,0.0,2.0,"0.0, 1.0"
131,FCFP6_1024_131,float64,0.0,0.0,2.0,"0.0, 1.0"
132,FCFP6_1024_132,float64,0.0,0.0,2.0,"0.0, 1.0"
133,FCFP6_1024_133,float64,0.0,0.0,2.0,"0.0, 1.0"
134,FCFP6_1024_134,float64,0.0,0.0,2.0,"0.0, 1.0"
135,FCFP6_1024_135,float64,0.0,0.0,2.0,"0.0, 1.0"
136,FCFP6_1024_136,float64,0.0,0.0,2.0,"0.0, 1.0"
137,FCFP6_1024_137,float64,0.0,0.0,2.0,"0.0, 1.0"
138,FCFP6_1024_138,float64,0.0,0.0,2.0,"0.0, 1.0"
139,FCFP6_1024_139,float64,0.0,0.0,2.0,"0.0, 1.0"
140,FCFP6_1024_140,float64,0.0,0.0,2.0,"0.0, 1.0"
141,FCFP6_1024_141,float64,0.0,0.0,2.0,"0.0, 1.0"
142,FCFP6_1024_142,float64,0.0,0.0,2.0,"0.0, 1.0"
143,FCFP6_1024_143,float64,0.0,0.0,2.0,"0.0, 1.0"
144,FCFP6_1024_144,float64,0.0,0.0,2.0,"0.0, 1.0"
145,FCFP6_1024_145,float64,0.0,0.0,2.0,"0.0, 1.0"
146,FCFP6_1024_146,float64,0.0,0.0,2.0,"0.0, 1.0"
147,FCFP6_1024_147,float64,0.0,0.0,2.0,"0.0, 1.0"
148,FCFP6_1024_148,float64,0.0,0.0,2.0,"0.0, 1.0"
149,FCFP6_1024_149,float64,0.0,0.0,2.0,"0.0, 1.0"
150,FCFP6_1024_150,float64,0.0,0.0,2.0,"0.0, 1.0"
151,FCFP6_1024_151,float64,0.0,0.0,2.0,"1.0, 0.0"
152,FCFP6_1024_152,float64,0.0,0.0,2.0,"0.0, 1.0"
153,FCFP6_1024_153,float64,0.0,0.0,2.0,"0.0, 1.0"
154,FCFP6_1024_154,float64,0.0,0.0,2.0,"0.0, 1.0"
155,FCFP6_1024_155,float64,0.0,0.0,2.0,"0.0, 1.0"
156,FCFP6_1024_156,float64,0.0,0.0,2.0,"0.0, 1.0"
157,FCFP6_1024_157,float64,0.0,0.0,2.0,"0.0, 1.0"
158,FCFP6_1024_158,float64,0.0,0.0,2.0,"0.0, 1.0"
159,FCFP6_1024_159,float64,0.0,0.0,2.0,"0.0, 1.0"
160,FCFP6_1024_160,float64,0.0,0.0,2.0,"0.0, 1.0"
161,FCFP6_1024_161,float64,0.0,0.0,2.0,"0.0, 1.0"
162,FCFP6_1024_162,float64,0.0,0.0,2.0,"0.0, 1.0"
163,FCFP6_1024_163,float64,0.0,0.0,2.0,"0.0, 1.0"
164,FCFP6_1024_164,float64,0.0,0.0,2.0,"0.0, 1.0"
165,FCFP6_1024_165,float64,0.0,0.0,2.0,"0.0, 1.0"
166,FCFP6_1024_166,float64,0.0,0.0,2.0,"0.0, 1.0"
167,FCFP6_1024_167,float64,0.0,0.0,2.0,"0.0, 1.0"
168,FCFP6_1024_168,float64,0.0,0.0,2.0,"0.0, 1.0"
169,FCFP6_1024_169,float64,0.0,0.0,2.0,"1.0, 0.0"
170,FCFP6_1024_170,float64,0.0,0.0,2.0,"0.0, 1.0"
171,FCFP6_1024_171,float64,0.0,0.0,2.0,"0.0, 1.0"
172,FCFP6_1024_172,float64,0.0,0.0,2.0,"0.0, 1.0"
173,FCFP6_1024_173,float64,0.0,0.0,2.0,"0.0, 1.0"
174,FCFP6_1024_174,float64,0.0,0.0,2.0,"0.0, 1.0"
175,FCFP6_1024_175,float64,0.0,0.0,2.0,"0.0, 1.0"
176,FCFP6_1024_176,float64,0.0,0.0,2.0,"0.0, 1.0"
177,FCFP6_1024_177,float64,0.0,0.0,2.0,"0.0, 1.0"
178,FCFP6_1024_178,float64,0.0,0.0,2.0,"0.0, 1.0"
179,FCFP6_1024_179,float64,0.0,0.0,2.0,"0.0, 1.0"
180,FCFP6_1024_180,float64,0.0,0.0,2.0,"0.0, 1.0"
181,FCFP6_1024_181,float64,0.0,0.0,2.0,"0.0, 1.0"
182,FCFP6_1024_182,float64,0.0,0.0,2.0,"0.0, 1.0"
183,FCFP6_1024_183,float64,0.0,0.0,2.0,"0.0, 1.0"
184,FCFP6_1024_184,float64,0.0,0.0,2.0,"0.0, 1.0"
185,FCFP6_1024_185,float64,0.0,0.0,2.0,"0.0, 1.0"
186,FCFP6_1024_186,float64,0.0,0.0,2.0,"0.0, 1.0"
187,FCFP6_1024_187,float64,0.0,0.0,2.0,"0.0, 1.0"
188,FCFP6_1024_188,float64,0.0,0.0,2.0,"0.0, 1.0"
189,FCFP6_1024_189,float64,0.0,0.0,2.0,"0.0, 1.0"
190,FCFP6_1024_190,float64,0.0,0.0,2.0,"0.0, 1.0"
191,FCFP6_1024_191,float64,0.0,0.0,2.0,"0.0, 1.0"
192,FCFP6_1024_192,float64,0.0,0.0,2.0,"0.0, 1.0"
193,FCFP6_1024_193,float64,0.0,0.0,2.0,"0.0, 1.0"
194,FCFP6_1024_194,float64,0.0,0.0,2.0,"0.0, 1.0"
195,FCFP6_1024_195,float64,0.0,0.0,2.0,"0.0, 1.0"
196,FCFP6_1024_196,float64,0.0,0.0,2.0,"0.0, 1.0"
197,FCFP6_1024_197,float64,0.0,0.0,2.0,"0.0, 1.0"
198,FCFP6_1024_198,float64,0.0,0.0,2.0,"0.0, 1.0"
199,FCFP6_1024_199,float64,0.0,0.0,2.0,"0.0, 1.0"
200,FCFP6_1024_200,float64,0.0,0.0,2.0,"0.0, 1.0"
201,FCFP6_1024_201,float64,0.0,0.0,2.0,"0.0, 1.0"
202,FCFP6_1024_202,float64,0.0,0.0,2.0,"0.0, 1.0"
203,FCFP6_1024_203,float64,0.0,0.0,2.0,"0.0, 1.0"
204,FCFP6_1024_204,float64,0.0,0.0,2.0,"0.0, 1.0"
205,FCFP6_1024_205,float64,0.0,0.0,2.0,"0.0, 1.0"
206,FCFP6_1024_206,float64,0.0,0.0,2.0,"0.0, 1.0"
207,FCFP6_1024_207,float64,0.0,0.0,2.0,"0.0, 1.0"
208,FCFP6_1024_208,float64,0.0,0.0,2.0,"0.0, 1.0"
209,FCFP6_1024_209,float64,0.0,0.0,2.0,"0.0, 1.0"
210,FCFP6_1024_210,float64,0.0,0.0,2.0,"0.0, 1.0"
211,FCFP6_1024_211,float64,0.0,0.0,2.0,"0.0, 1.0"
212,FCFP6_1024_212,float64,0.0,0.0,2.0,"0.0, 1.0"
213,FCFP6_1024_213,float64,0.0,0.0,2.0,"0.0, 1.0"
214,FCFP6_1024_214,float64,0.0,0.0,2.0,"0.0, 1.0"
215,FCFP6_1024_215,float64,0.0,0.0,2.0,"0.0, 1.0"
216,FCFP6_1024_216,float64,0.0,0.0,2.0,"0.0, 1.0"
217,FCFP6_1024_217,float64,0.0,0.0,2.0,"0.0, 1.0"
218,FCFP6_1024_218,float64,0.0,0.0,2.0,"0.0, 1.0"
219,FCFP6_1024_219,float64,0.0,0.0,2.0,"0.0, 1.0"
220,FCFP6_1024_220,float64,0.0,0.0,2.0,"0.0, 1.0"
221,FCFP6_1024_221,float64,0.0,0.0,2.0,"0.0, 1.0"
222,FCFP6_1024_222,float64,0.0,0.0,2.0,"0.0, 1.0"
223,FCFP6_1024_223,float64,0.0,0.0,2.0,"0.0, 1.0"
224,FCFP6_1024_224,float64,0.0,0.0,2.0,"0.0, 1.0"
225,FCFP6_1024_225,float64,0.0,0.0,2.0,"0.0, 1.0"
226,FCFP6_1024_226,float64,0.0,0.0,2.0,"0.0, 1.0"
227,FCFP6_1024_227,float64,0.0,0.0,2.0,"0.0, 1.0"
228,FCFP6_1024_228,float64,0.0,0.0,2.0,"0.0, 1.0"
229,FCFP6_1024_229,float64,0.0,0.0,2.0,"0.0, 1.0"
230,FCFP6_1024_230,float64,0.0,0.0,2.0,"0.0, 1.0"
231,FCFP6_1024_231,float64,0.0,0.0,2.0,"0.0, 1.0"
232,FCFP6_1024_232,float64,0.0,0.0,2.0,"0.0, 1.0"
233,FCFP6_1024_233,float64,0.0,0.0,2.0,"0.0, 1.0"
234,FCFP6_1024_234,float64,0.0,0.0,2.0,"0.0, 1.0"
235,FCFP6_1024_235,float64,0.0,0.0,2.0,"0.0, 1.0"
236,FCFP6_1024_236,float64,0.0,0.0,2.0,"0.0, 1.0"
237,FCFP6_1024_237,float64,0.0,0.0,2.0,"0.0, 1.0"
238,FCFP6_1024_238,float64,0.0,0.0,2.0,"0.0, 1.0"
239,FCFP6_1024_239,float64,0.0,0.0,2.0,"0.0, 1.0"
240,FCFP6_1024_240,float64,0.0,0.0,2.0,"0.0, 1.0"
241,FCFP6_1024_241,float64,0.0,0.0,2.0,"0.0, 1.0"
242,FCFP6_1024_242,float64,0.0,0.0,2.0,"0.0, 1.0"
243,FCFP6_1024_243,float64,0.0,0.0,2.0,"0.0, 1.0"
244,FCFP6_1024_244,float64,0.0,0.0,2.0,"0.0, 1.0"
245,FCFP6_1024_245,float64,0.0,0.0,2.0,"0.0, 1.0"
246,FCFP6_1024_246,float64,0.0,0.0,2.0,"0.0, 1.0"
247,FCFP6_1024_247,float64,0.0,0.0,2.0,"0.0, 1.0"
248,FCFP6_1024_248,float64,0.0,0.0,2.0,"0.0, 1.0"
249,FCFP6_1024_249,float64,0.0,0.0,2.0,"0.0, 1.0"
250,FCFP6_1024_250,float64,0.0,0.0,2.0,"0.0, 1.0"
251,FCFP6_1024_251,float64,0.0,0.0,2.0,"0.0, 1.0"
252,FCFP6_1024_252,float64,0.0,0.0,2.0,"0.0, 1.0"
253,FCFP6_1024_253,float64,0.0,0.0,2.0,"0.0, 1.0"
254,FCFP6_1024_254,float64,0.0,0.0,2.0,"0.0, 1.0"
255,FCFP6_1024_255,float64,0.0,0.0,2.0,"0.0, 1.0"
256,FCFP6_1024_256,float64,0.0,0.0,2.0,"0.0, 1.0"
257,FCFP6_1024_257,float64,0.0,0.0,2.0,"0.0, 1.0"
258,FCFP6_1024_258,float64,0.0,0.0,2.0,"0.0, 1.0"
259,FCFP6_1024_259,float64,0.0,0.0,2.0,"0.0, 1.0"
260,FCFP6_1024_260,float64,0.0,0.0,2.0,"0.0, 1.0"
261,FCFP6_1024_261,float64,0.0,0.0,2.0,"0.0, 1.0"
262,FCFP6_1024_262,float64,0.0,0.0,2.0,"0.0, 1.0"
263,FCFP6_1024_263,float64,0.0,0.0,2.0,"0.0, 1.0"
264,FCFP6_1024_264,float64,0.0,0.0,2.0,"0.0, 1.0"
265,FCFP6_1024_265,float64,0.0,0.0,2.0,"0.0, 1.0"
266,FCFP6_1024_266,float64,0.0,0.0,2.0,"0.0, 1.0"
267,FCFP6_1024_267,float64,0.0,0.0,2.0,"0.0, 1.0"
268,FCFP6_1024_268,float64,0.0,0.0,2.0,"0.0, 1.0"
269,FCFP6_1024_269,float64,0.0,0.0,2.0,"0.0, 1.0"
270,FCFP6_1024_270,float64,0.0,0.0,2.0,"0.0, 1.0"
271,FCFP6_1024_271,float64,0.0,0.0,2.0,"0.0, 1.0"
272,FCFP6_1024_272,float64,0.0,0.0,2.0,"0.0, 1.0"
273,FCFP6_1024_273,float64,0.0,0.0,2.0,"0.0, 1.0"
274,FCFP6_1024_274,float64,0.0,0.0,2.0,"0.0, 1.0"
275,FCFP6_1024_275,float64,0.0,0.0,2.0,"0.0, 1.0"
276,FCFP6_1024_276,float64,0.0,0.0,2.0,"0.0, 1.0"
277,FCFP6_1024_277,float64,0.0,0.0,2.0,"0.0, 1.0"
278,FCFP6_1024_278,float64,0.0,0.0,2.0,"0.0, 1.0"
279,FCFP6_1024_279,float64,0.0,0.0,2.0,"0.0, 1.0"
280,FCFP6_1024_280,float64,0.0,0.0,2.0,"0.0, 1.0"
281,FCFP6_1024_281,float64,0.0,0.0,2.0,"0.0, 1.0"
282,FCFP6_1024_282,float64,0.0,0.0,2.0,"0.0, 1.0"
283,FCFP6_1024_283,float64,0.0,0.0,2.0,"0.0, 1.0"
284,FCFP6_1024_284,float64,0.0,0.0,2.0,"0.0, 1.0"
285,FCFP6_1024_285,float64,0.0,0.0,2.0,"0.0, 1.0"
286,FCFP6_1024_286,float64,0.0,0.0,2.0,"0.0, 1.0"
287,FCFP6_1024_287,float64,0.0,0.0,2.0,"0.0, 1.0"
288,FCFP6_1024_288,float64,0.0,0.0,2.0,"0.0, 1.0"
289,FCFP6_1024_289,float64,0.0,0.0,2.0,"0.0, 1.0"
290,FCFP6_1024_290,float64,0.0,0.0,2.0,"0.0, 1.0"
291,FCFP6_1024_291,float64,0.0,0.0,2.0,"0.0, 1.0"
292,FCFP6_1024_292,float64,0.0,0.0,2.0,"0.0, 1.0"
293,FCFP6_1024_293,float64,0.0,0.0,2.0,"0.0, 1.0"
294,FCFP6_1024_294,float64,0.0,0.0,2.0,"0.0, 1.0"
295,FCFP6_1024_295,float64,0.0,0.0,2.0,"0.0, 1.0"
296,FCFP6_1024_296,float64,0.0,0.0,2.0,"0.0, 1.0"
297,FCFP6_1024_297,float64,0.0,0.0,2.0,"0.0, 1.0"
298,FCFP6_1024_298,float64,0.0,0.0,2.0,"0.0, 1.0"
299,FCFP6_1024_299,float64,0.0,0.0,2.0,"0.0, 1.0"
300,FCFP6_1024_300,float64,0.0,0.0,2.0,"0.0, 1.0"
301,FCFP6_1024_301,float64,0.0,0.0,2.0,"0.0, 1.0"
302,FCFP6_1024_302,float64,0.0,0.0,2.0,"0.0, 1.0"
303,FCFP6_1024_303,float64,0.0,0.0,2.0,"0.0, 1.0"
304,FCFP6_1024_304,float64,0.0,0.0,2.0,"0.0, 1.0"
305,FCFP6_1024_305,float64,0.0,0.0,2.0,"0.0, 1.0"
306,FCFP6_1024_306,float64,0.0,0.0,2.0,"0.0, 1.0"
307,FCFP6_1024_307,float64,0.0,0.0,2.0,"0.0, 1.0"
308,FCFP6_1024_308,float64,0.0,0.0,2.0,"0.0, 1.0"
309,FCFP6_1024_309,float64,0.0,0.0,2.0,"0.0, 1.0"
310,FCFP6_1024_310,float64,0.0,0.0,2.0,"0.0, 1.0"
311,FCFP6_1024_311,float64,0.0,0.0,2.0,"0.0, 1.0"
312,FCFP6_1024_312,float64,0.0,0.0,2.0,"0.0, 1.0"
313,FCFP6_1024_313,float64,0.0,0.0,2.0,"0.0, 1.0"
314,FCFP6_1024_314,float64,0.0,0.0,2.0,"0.0, 1.0"
315,FCFP6_1024_315,float64,0.0,0.0,2.0,"0.0, 1.0"
316,FCFP6_1024_316,float64,0.0,0.0,2.0,"0.0, 1.0"
317,FCFP6_1024_317,float64,0.0,0.0,2.0,"0.0, 1.0"
318,FCFP6_1024_318,float64,0.0,0.0,2.0,"0.0, 1.0"
319,FCFP6_1024_319,float64,0.0,0.0,2.0,"0.0, 1.0"
320,FCFP6_1024_320,float64,0.0,0.0,2.0,"0.0, 1.0"
321,FCFP6_1024_321,float64,0.0,0.0,2.0,"0.0, 1.0"
322,FCFP6_1024_322,float64,0.0,0.0,2.0,"0.0, 1.0"
323,FCFP6_1024_323,float64,0.0,0.0,2.0,"0.0, 1.0"
324,FCFP6_1024_324,float64,0.0,0.0,2.0,"0.0, 1.0"
325,FCFP6_1024_325,float64,0.0,0.0,2.0,"0.0, 1.0"
326,FCFP6_1024_326,float64,0.0,0.0,2.0,"0.0, 1.0"
327,FCFP6_1024_327,float64,0.0,0.0,2.0,"0.0, 1.0"
328,FCFP6_1024_328,float64,0.0,0.0,2.0,"0.0, 1.0"
329,FCFP6_1024_329,float64,0.0,0.0,2.0,"0.0, 1.0"
330,FCFP6_1024_330,float64,0.0,0.0,2.0,"0.0, 1.0"
331,FCFP6_1024_331,float64,0.0,0.0,2.0,"0.0, 1.0"
332,FCFP6_1024_332,float64,0.0,0.0,2.0,"0.0, 1.0"
333,FCFP6_1024_333,float64,0.0,0.0,2.0,"0.0, 1.0"
334,FCFP6_1024_334,float64,0.0,0.0,2.0,"0.0, 1.0"
335,FCFP6_1024_335,float64,0.0,0.0,2.0,"0.0, 1.0"
336,FCFP6_1024_336,float64,0.0,0.0,2.0,"0.0, 1.0"
337,FCFP6_1024_337,float64,0.0,0.0,2.0,"0.0, 1.0"
338,FCFP6_1024_338,float64,0.0,0.0,2.0,"0.0, 1.0"
339,FCFP6_1024_339,float64,0.0,0.0,2.0,"0.0, 1.0"
340,FCFP6_1024_340,float64,0.0,0.0,2.0,"0.0, 1.0"
341,FCFP6_1024_341,float64,0.0,0.0,2.0,"0.0, 1.0"
342,FCFP6_1024_342,float64,0.0,0.0,2.0,"0.0, 1.0"
343,FCFP6_1024_343,float64,0.0,0.0,2.0,"0.0, 1.0"
344,FCFP6_1024_344,float64,0.0,0.0,2.0,"0.0, 1.0"
345,FCFP6_1024_345,float64,0.0,0.0,2.0,"0.0, 1.0"
346,FCFP6_1024_346,float64,0.0,0.0,2.0,"0.0, 1.0"
347,FCFP6_1024_347,float64,0.0,0.0,2.0,"0.0, 1.0"
348,FCFP6_1024_348,float64,0.0,0.0,2.0,"0.0, 1.0"
349,FCFP6_1024_349,float64,0.0,0.0,2.0,"0.0, 1.0"
350,FCFP6_1024_350,float64,0.0,0.0,2.0,"0.0, 1.0"
351,FCFP6_1024_351,float64,0.0,0.0,2.0,"0.0, 1.0"
352,FCFP6_1024_352,float64,0.0,0.0,2.0,"0.0, 1.0"
353,FCFP6_1024_353,float64,0.0,0.0,2.0,"0.0, 1.0"
354,FCFP6_1024_354,float64,0.0,0.0,2.0,"0.0, 1.0"
355,FCFP6_1024_355,float64,0.0,0.0,2.0,"0.0, 1.0"
356,FCFP6_1024_356,float64,0.0,0.0,2.0,"0.0, 1.0"
357,FCFP6_1024_357,float64,0.0,0.0,2.0,"0.0, 1.0"
358,FCFP6_1024_358,float64,0.0,0.0,2.0,"0.0, 1.0"
359,FCFP6_1024_359,float64,0.0,0.0,2.0,"0.0, 1.0"
360,FCFP6_1024_360,float64,0.0,0.0,2.0,"0.0, 1.0"
361,FCFP6_1024_361,float64,0.0,0.0,2.0,"0.0, 1.0"
362,FCFP6_1024_362,float64,0.0,0.0,2.0,"0.0, 1.0"
363,FCFP6_1024_363,float64,0.0,0.0,2.0,"0.0, 1.0"
364,FCFP6_1024_364,float64,0.0,0.0,2.0,"0.0, 1.0"
365,FCFP6_1024_365,float64,0.0,0.0,2.0,"0.0, 1.0"
366,FCFP6_1024_366,float64,0.0,0.0,2.0,"0.0, 1.0"
367,FCFP6_1024_367,float64,0.0,0.0,2.0,"0.0, 1.0"
368,FCFP6_1024_368,float64,0.0,0.0,2.0,"0.0, 1.0"
369,FCFP6_1024_369,float64,0.0,0.0,2.0,"0.0, 1.0"
370,FCFP6_1024_370,float64,0.0,0.0,2.0,"0.0, 1.0"
371,FCFP6_1024_371,float64,0.0,0.0,2.0,"0.0, 1.0"
372,FCFP6_1024_372,float64,0.0,0.0,2.0,"0.0, 1.0"
373,FCFP6_1024_373,float64,0.0,0.0,2.0,"0.0, 1.0"
374,FCFP6_1024_374,float64,0.0,0.0,2.0,"0.0, 1.0"
375,FCFP6_1024_375,float64,0.0,0.0,2.0,"0.0, 1.0"
376,FCFP6_1024_376,float64,0.0,0.0,2.0,"0.0, 1.0"
377,FCFP6_1024_377,float64,0.0,0.0,2.0,"0.0, 1.0"
378,FCFP6_1024_378,float64,0.0,0.0,2.0,"0.0, 1.0"
379,FCFP6_1024_379,float64,0.0,0.0,2.0,"0.0, 1.0"
380,FCFP6_1024_380,float64,0.0,0.0,2.0,"0.0, 1.0"
381,FCFP6_1024_381,float64,0.0,0.0,2.0,"0.0, 1.0"
382,FCFP6_1024_382,float64,0.0,0.0,2.0,"0.0, 1.0"
383,FCFP6_1024_383,float64,0.0,0.0,2.0,"0.0, 1.0"
384,FCFP6_1024_384,float64,0.0,0.0,2.0,"0.0, 1.0"
385,FCFP6_1024_385,float64,0.0,0.0,2.0,"0.0, 1.0"
386,FCFP6_1024_386,float64,0.0,0.0,2.0,"0.0, 1.0"
387,FCFP6_1024_387,float64,0.0,0.0,2.0,"0.0, 1.0"
388,FCFP6_1024_388,float64,0.0,0.0,2.0,"0.0, 1.0"
389,FCFP6_1024_389,float64,0.0,0.0,2.0,"0.0, 1.0"
390,FCFP6_1024_390,float64,0.0,0.0,2.0,"0.0, 1.0"
391,FCFP6_1024_391,float64,0.0,0.0,2.0,"0.0, 1.0"
392,FCFP6_1024_392,float64,0.0,0.0,2.0,"0.0, 1.0"
393,FCFP6_1024_393,float64,0.0,0.0,2.0,"0.0, 1.0"
394,FCFP6_1024_394,float64,0.0,0.0,2.0,"0.0, 1.0"
395,FCFP6_1024_395,float64,0.0,0.0,2.0,"0.0, 1.0"
396,FCFP6_1024_396,float64,0.0,0.0,2.0,"0.0, 1.0"
397,FCFP6_1024_397,float64,0.0,0.0,2.0,"0.0, 1.0"
398,FCFP6_1024_398,float64,0.0,0.0,2.0,"0.0, 1.0"
399,FCFP6_1024_399,float64,0.0,0.0,2.0,"0.0, 1.0"
400,FCFP6_1024_400,float64,0.0,0.0,2.0,"0.0, 1.0"
401,FCFP6_1024_401,float64,0.0,0.0,2.0,"0.0, 1.0"
402,FCFP6_1024_402,float64,0.0,0.0,2.0,"0.0, 1.0"

In [6]:
# Numeric Feature Statistics
numeric_stats

                  count      mean       std    min   max
FCFP6_1024_0     5741.0  0.999303  0.026389  0.000   1.0
FCFP6_1024_1     5741.0  0.978053  0.146525  0.000   1.0
FCFP6_1024_2     5741.0  0.011322  0.105810  0.000   1.0
FCFP6_1024_3     5741.0  0.954712  0.207954  0.000   1.0
FCFP6_1024_4     5741.0  0.097892  0.297195  0.000   1.0
FCFP6_1024_5     5741.0  0.046508  0.210600  0.000   1.0
FCFP6_1024_6     5741.0  0.020554  0.141898  0.000   1.0
FCFP6_1024_7     5741.0  0.199617  0.399747  0.000   1.0
FCFP6_1024_8     5741.0  0.133600  0.340252  0.000   1.0
FCFP6_1024_9     5741.0  0.175405  0.380346  0.000   1.0
FCFP6_1024_10    5741.0  0.009232  0.095646  0.000   1.0
FCFP6_1024_11    5741.0  0.075945  0.264933  0.000   1.0
FCFP6_1024_12    5741.0  0.022296  0.147657  0.000   1.0
FCFP6_1024_13    5741.0  0.010625  0.102539  0.000   1.0
FCFP6_1024_14    5741.0  0.007838  0.088195  0.000   1.0
FCFP6_1024_15    5741.0  0.005051  0.070900  0.000   1.0
FCFP6_1024_16    5741.0  0.978227  0.145955  0.000   1.0
FCFP6_1024_17    5741.0  0.628984  0.483119  0.000   1.0
FCFP6_1024_18    5741.0  0.008883  0.093841  0.000   1.0
FCFP6_1024_19    5741.0  0.079254  0.270159  0.000   1.0
FCFP6_1024_20    5741.0  0.008361  0.091063  0.000   1.0
FCFP6_1024_21    5741.0  0.021251  0.144231  0.000   1.0
FCFP6_1024_22    5741.0  0.012367  0.110528  0.000   1.0
FCFP6_1024_23    5741.0  0.013064  0.113558  0.000   1.0
FCFP6_1024_24    5741.0  0.921268  0.269343  0.000   1.0
FCFP6_1024_25    5741.0  0.017244  0.130192  0.000   1.0
FCFP6_1024_26    5741.0  0.072635  0.259560  0.000   1.0
FCFP6_1024_27    5741.0  0.055217  0.228423  0.000   1.0
FCFP6_1024_28    5741.0  0.011322  0.105810  0.000   1.0
FCFP6_1024_29    5741.0  0.042501  0.201747  0.000   1.0
FCFP6_1024_30    5741.0  0.117401  0.321926  0.000   1.0
FCFP6_1024_31    5741.0  0.029437  0.169044  0.000   1.0
FCFP6_1024_32    5741.0  0.340707  0.473988  0.000   1.0
FCFP6_1024_33    5741.0  0.014109  0.117951  0.000   1.0
FCFP6_1024_34    5741.0  0.095628  0.294106  0.000   1.0
FCFP6_1024_35    5741.0  0.012367  0.110528  0.000   1.0
FCFP6_1024_36    5741.0  0.113743  0.317527  0.000   1.0
FCFP6_1024_37    5741.0  0.079080  0.269888  0.000   1.0
FCFP6_1024_38    5741.0  0.025257  0.156918  0.000   1.0
FCFP6_1024_39    5741.0  0.019160  0.137101  0.000   1.0
FCFP6_1024_40    5741.0  0.028392  0.166105  0.000   1.0
FCFP6_1024_41    5741.0  0.030134  0.170971  0.000   1.0
FCFP6_1024_42    5741.0  0.032399  0.177072  0.000   1.0
FCFP6_1024_43    5741.0  0.047553  0.212836  0.000   1.0
FCFP6_1024_44    5741.0  0.036927  0.188600  0.000   1.0
FCFP6_1024_45    5741.0  0.015503  0.123551  0.000   1.0
FCFP6_1024_46    5741.0  0.012716  0.112054  0.000   1.0
FCFP6_1024_47    5741.0  0.028741  0.167091  0.000   1.0
FCFP6_1024_48    5741.0  0.010451  0.101704  0.000   1.0
FCFP6_1024_49    5741.0  0.036927  0.188600  0.000   1.0
FCFP6_1024_50    5741.0  0.006967  0.083187  0.000   1.0
FCFP6_1024_51    5741.0  0.041108  0.198557  0.000   1.0
FCFP6_1024_52    5741.0  0.083261  0.276300  0.000   1.0
FCFP6_1024_53    5741.0  0.296987  0.456970  0.000   1.0
FCFP6_1024_54    5741.0  0.035882  0.186013  0.000   1.0
FCFP6_1024_55    5741.0  0.037450  0.189878  0.000   1.0
FCFP6_1024_56    5741.0  0.255530  0.436197  0.000   1.0
FCFP6_1024_57    5741.0  0.033792  0.180709  0.000   1.0
FCFP6_1024_58    5741.0  0.022470  0.148219  0.000   1.0
FCFP6_1024_59    5741.0  0.034837  0.183383  0.000   1.0
FCFP6_1024_60    5741.0  0.070894  0.256669  0.000   1.0
FCFP6_1024_61    5741.0  0.009929  0.099155  0.000   1.0
FCFP6_1024_62    5741.0  0.143181  0.350287  0.000   1.0
FCFP6_1024_63    5741.0  0.008361  0.091063  0.000   1.0
FCFP6_1024_64    5741.0  0.280787  0.449423  0.000   1.0
FCFP6_1024_65    5741.0  0.031876  0.175685  0.000   1.0
FCFP6_1024_66    5741.0  0.036579  0.187742  0.000   1.0
FCFP6_1024_67    5741.0  0.070197  0.255501  0.000   1.0
FCFP6_1024_68    5741.0  0.072113  0.258697  0.000   1.0
FCFP6_1024_69    5741.0  0.029263  0.168558  0.000   1.0
FCFP6_1024_70    5741.0  0.078035  0.268250  0.000   1.0
FCFP6_1024_71    5741.0  0.029089  0.168071  0.000   1.0
FCFP6_1024_72    5741.0  0.028392  0.166105  0.000   1.0
FCFP6_1024_73    5741.0  0.017767  0.132115  0.000   1.0
FCFP6_1024_74    5741.0  0.048424  0.214678  0.000   1.0
FCFP6_1024_75    5741.0  0.021773  0.145955  0.000   1.0
FCFP6_1024_76    5741.0  0.051211  0.220446  0.000   1.0
FCFP6_1024_77    5741.0  0.404633  0.490864  0.000   1.0
FCFP6_1024_78    5741.0  0.038843  0.193238  0.000   1.0
FCFP6_1024_79    5741.0  0.071068  0.256960  0.000   1.0
FCFP6_1024_80    5741.0  0.047030  0.211722  0.000   1.0
FCFP6_1024_81    5741.0  0.029437  0.169044  0.000   1.0
FCFP6_1024_82    5741.0  0.018986  0.136488  0.000   1.0
FCFP6_1024_83    5741.0  0.029263  0.168558  0.000   1.0
FCFP6_1024_84    5741.0  0.014457  0.119377  0.000   1.0
FCFP6_1024_85    5741.0  0.027173  0.162601  0.000   1.0
FCFP6_1024_86    5741.0  0.078558  0.269071  0.000   1.0
FCFP6_1024_87    5741.0  0.025605  0.157968  0.000   1.0
FCFP6_1024_88    5741.0  0.051385  0.220801  0.000   1.0
FCFP6_1024_89    5741.0  0.011322  0.105810  0.000   1.0
FCFP6_1024_90    5741.0  0.010625  0.102539  0.000   1.0
FCFP6_1024_91    5741.0  0.060965  0.239287  0.000   1.0
FCFP6_1024_92    5741.0  0.025605  0.157968  0.000   1.0
FCFP6_1024_93    5741.0  0.024909  0.155860  0.000   1.0
FCFP6_1024_94    5741.0  0.007316  0.085226  0.000   1.0
FCFP6_1024_95    5741.0  0.012541  0.111293  0.000   1.0
FCFP6_1024_96    5741.0  0.008709  0.092924  0.000   1.0
FCFP6_1024_97    5741.0  0.020206  0.140715  0.000   1.0
FCFP6_1024_98    5741.0  0.007316  0.085226  0.000   1.0
FCFP6_1024_99    5741.0  0.033444  0.179808  0.000   1.0
FCFP6_1024_100   5741.0  0.008361  0.091063  0.000   1.0
FCFP6_1024_101   5741.0  0.037276  0.189453  0.000   1.0
FCFP6_1024_102   5741.0  0.039714  0.195304  0.000   1.0
FCFP6_1024_103   5741.0  0.028566  0.166599  0.000   1.0
FCFP6_1024_104   5741.0  0.049817  0.217586  0.000   1.0
FCFP6_1024_105   5741.0  0.084132  0.277609  0.000   1.0
FCFP6_1024_106   5741.0  0.285316  0.451604  0.000   1.0
FCFP6_1024_107   5741.0  0.054172  0.226376  0.000   1.0
FCFP6_1024_108   5741.0  0.008361  0.091063  0.000   1.0
FCFP6_1024_109   5741.0  0.057830  0.233441  0.000   1.0
FCFP6_1024_110   5741.0  0.009232  0.095646  0.000   1.0
FCFP6_1024_111   5741.0  0.069152  0.253734  0.000   1.0
FCFP6_1024_112   5741.0  0.016199  0.126252  0.000   1.0
FCFP6_1024_113   5741.0  0.032224  0.176611  0.000   1.0
FCFP6_1024_114   5741.0  0.012716  0.112054  0.000   1.0
FCFP6_1024_115   5741.0  0.025431  0.157444  0.000   1.0
FCFP6_1024_116   5741.0  0.067410  0.250752  0.000   1.0
FCFP6_1024_117   5741.0  0.113221  0.316890  0.000   1.0
FCFP6_1024_118   5741.0  0.016722  0.128238  0.000   1.0
FCFP6_1024_119   5741.0  0.021076  0.143652  0.000   1.0
FCFP6_1024_120   5741.0  0.071765  0.258120  0.000   1.0
FCFP6_1024_121   5741.0  0.089009  0.284781  0.000   1.0
FCFP6_1024_122   5741.0  0.058004  0.233771  0.000   1.0
FCFP6_1024_123   5741.0  0.155896  0.362788  0.000   1.0
FCFP6_1024_124   5741.0  0.012716  0.112054  0.000   1.0
FCFP6_1024_125   5741.0  0.029263  0.168558  0.000   1.0
FCFP6_1024_126   5741.0  0.026128  0.159529  0.000   1.0
FCFP6_1024_127   5741.0  0.109389  0.312153  0.000   1.0
FCFP6_1024_128   5741.0  0.313534  0.463970  0.000   1.0
FCFP6_1024_129   5741.0  0.039540  0.194893  0.000   1.0
FCFP6_1024_130   5741.0  0.027870  0.164614  0.000   1.0
FCFP6_1024_131   5741.0  0.043372  0.203711  0.000   1.0
FCFP6_1024_132   5741.0  0.173663  0.378853  0.000   1.0
FCFP6_1024_133   5741.0  0.047553  0.212836  0.000   1.0
FCFP6_1024_134   5741.0  0.024038  0.153179  0.000   1.0
FCFP6_1024_135   5741.0  0.011322  0.105810  0.000   1.0
FCFP6_1024_136   5741.0  0.140916  0.347965  0.000   1.0
FCFP6_1024_137   5741.0  0.037972  0.191146  0.000   1.0
FCFP6_1024_138   5741.0  0.213900  0.410093  0.000   1.0
FCFP6_1024_139   5741.0  0.007664  0.087217  0.000   1.0
FCFP6_1024_140   5741.0  0.019160  0.137101  0.000   1.0
FCFP6_1024_141   5741.0  0.050862  0.219735  0.000   1.0
FCFP6_1024_142   5741.0  0.061139  0.239606  0.000   1.0
FCFP6_1024_143   5741.0  0.009232  0.095646  0.000   1.0
FCFP6_1024_144   5741.0  0.014632  0.120083  0.000   1.0
FCFP6_1024_145   5741.0  0.014109  0.117951  0.000   1.0
FCFP6_1024_146   5741.0  0.007838  0.088195  0.000   1.0
FCFP6_1024_147   5741.0  0.019335  0.137710  0.000   1.0
FCFP6_1024_148   5741.0  0.016199  0.126252  0.000   1.0
FCFP6_1024_149   5741.0  0.025083  0.156390  0.000   1.0
FCFP6_1024_150   5741.0  0.018986  0.136488  0.000   1.0
FCFP6_1024_151   5741.0  0.526563  0.499337  0.000   1.0
FCFP6_1024_152   5741.0  0.062707  0.242456  0.000   1.0
FCFP6_1024_153   5741.0  0.009754  0.098290  0.000   1.0
FCFP6_1024_154   5741.0  0.019160  0.137101  0.000   1.0
FCFP6_1024_155   5741.0  0.009058  0.094748  0.000   1.0
FCFP6_1024_156   5741.0  0.022644  0.148779  0.000   1.0
FCFP6_1024_157   5741.0  0.014632  0.120083  0.000   1.0
FCFP6_1024_158   5741.0  0.059572  0.236712  0.000   1.0
FCFP6_1024_159   5741.0  0.018464  0.134633  0.000   1.0
FCFP6_1024_160   5741.0  0.015851  0.124909  0.000   1.0
FCFP6_1024_161   5741.0  0.023341  0.150997  0.000   1.0
FCFP6_1024_162   5741.0  0.013412  0.115042  0.000   1.0
FCFP6_1024_163   5741.0  0.074726  0.262971  0.000   1.0
FCFP6_1024_164   5741.0  0.049643  0.217225  0.000   1.0
FCFP6_1024_165   5741.0  0.054346  0.226719  0.000   1.0
FCFP6_1024_166   5741.0  0.049120  0.216138  0.000   1.0
FCFP6_1024_167   5741.0  0.021425  0.144808  0.000   1.0
FCFP6_1024_168   5741.0  0.112176  0.315610  0.000   1.0
FCFP6_1024_169   5741.0  0.964292  0.185577  0.000   1.0
FCFP6_1024_170   5741.0  0.447831  0.497314  0.000   1.0
FCFP6_1024_171   5741.0  0.017070  0.129544  0.000   1.0
FCFP6_1024_172   5741.0  0.116530  0.320888  0.000   1.0
FCFP6_1024_173   5741.0  0.003832  0.061790  0.000   1.0
FCFP6_1024_174   5741.0  0.006793  0.082148  0.000   1.0
FCFP6_1024_175   5741.0  0.010800  0.103367  0.000   1.0
FCFP6_1024_176   5741.0  0.057307  0.232449  0.000   1.0
FCFP6_1024_177   5741.0  0.107647  0.309961  0.000   1.0
FCFP6_1024_178   5741.0  0.022993  0.149893  0.000   1.0
FCFP6_1024_179   5741.0  0.012193  0.109756  0.000   1.0
FCFP6_1024_180   5741.0  0.038669  0.192822  0.000   1.0
FCFP6_1024_181   5741.0  0.054172  0.226376  0.000   1.0
FCFP6_1024_182   5741.0  0.027347  0.163107  0.000   1.0
FCFP6_1024_183   5741.0  0.013935  0.117231  0.000   1.0
FCFP6_1024_184   5741.0  0.046333  0.210224  0.000   1.0
FCFP6_1024_185   5741.0  0.031876  0.175685  0.000   1.0
FCFP6_1024_186   5741.0  0.049295  0.216501  0.000   1.0
FCFP6_1024_187   5741.0  0.035534  0.185141  0.000   1.0
FCFP6_1024_188   5741.0  0.008883  0.093841  0.000   1.0
FCFP6_1024_189   5741.0  0.016896  0.128893  0.000   1.0
FCFP6_1024_190   5741.0  0.121582  0.326830  0.000   1.0
FCFP6_1024_191   5741.0  0.035882  0.186013  0.000   1.0
FCFP6_1024_192   5741.0  0.047379  0.212466  0.000   1.0
FCFP6_1024_193   5741.0  0.042850  0.202536  0.000   1.0
FCFP6_1024_194   5741.0  0.233757  0.423256  0.000   1.0
FCFP6_1024_195   5741.0  0.029612  0.169528  0.000   1.0
FCFP6_1024_196   5741.0  0.034837  0.183383  0.000   1.0
FCFP6_1024_197   5741.0  0.032050  0.176149  0.000   1.0
FCFP6_1024_198   5741.0  0.076468  0.265768  0.000   1.0
FCFP6_1024_199   5741.0  0.021599  0.145383  0.000   1.0
FCFP6_1024_200   5741.0  0.040063  0.196123  0.000   1.0
FCFP6_1024_201   5741.0  0.015503  0.123551  0.000   1.0
FCFP6_1024_202   5741.0  0.030134  0.170971  0.000   1.0
FCFP6_1024_203   5741.0  0.026650  0.161074  0.000   1.0
FCFP6_1024_204   5741.0  0.017593  0.131477  0.000   1.0
FCFP6_1024_205   5741.0  0.028044  0.165113  0.000   1.0
FCFP6_1024_206   5741.0  0.019160  0.137101  0.000   1.0
FCFP6_1024_207   5741.0  0.147187  0.354323  0.000   1.0
FCFP6_1024_208   5741.0  0.036753  0.188172  0.000   1.0
FCFP6_1024_209   5741.0  0.018464  0.134633  0.000   1.0
FCFP6_1024_210   5741.0  0.017419  0.130836  0.000   1.0
FCFP6_1024_211   5741.0  0.025083  0.156390  0.000   1.0
FCFP6_1024_212   5741.0  0.017941  0.132749  0.000   1.0
FCFP6_1024_213   5741.0  0.130291  0.336653  0.000   1.0
FCFP6_1024_214   5741.0  0.128549  0.334729  0.000   1.0
FCFP6_1024_215   5741.0  0.024038  0.153179  0.000   1.0
FCFP6_1024_216   5741.0  0.007142  0.084213  0.000   1.0
FCFP6_1024_217   5741.0  0.034837  0.183383  0.000   1.0
FCFP6_1024_218   5741.0  0.021773  0.145955  0.000   1.0
FCFP6_1024_219   5741.0  0.023167  0.150446  0.000   1.0
FCFP6_1024_220   5741.0  0.011845  0.108196  0.000   1.0
FCFP6_1024_221   5741.0  0.089183  0.285033  0.000   1.0
FCFP6_1024_222   5741.0  0.036753  0.188172  0.000   1.0
FCFP6_1024_223   5741.0  0.024734  0.155328  0.000   1.0
FCFP6_1024_224   5741.0  0.018986  0.136488  0.000   1.0
FCFP6_1024_225   5741.0  0.069326  0.254030  0.000   1.0
FCFP6_1024_226   5741.0  0.046333  0.210224  0.000   1.0
FCFP6_1024_227   5741.0  0.032050  0.176149  0.000   1.0
FCFP6_1024_228   5741.0  0.045288  0.207954  0.000   1.0
FCFP6_1024_229   5741.0  0.005226  0.072105  0.000   1.0
FCFP6_1024_230   5741.0  0.016199  0.126252  0.000   1.0
FCFP6_1024_231   5741.0  0.014632  0.120083  0.000   1.0
FCFP6_1024_232   5741.0  0.024212  0.153720  0.000   1.0
FCFP6_1024_233   5741.0  0.026476  0.160561  0.000   1.0
FCFP6_1024_234   5741.0  0.061488  0.240243  0.000   1.0
FCFP6_1024_235   5741.0  0.029786  0.170011  0.000   1.0
FCFP6_1024_236   5741.0  0.044940  0.207190  0.000   1.0
FCFP6_1024_237   5741.0  0.007490  0.086227  0.000   1.0
FCFP6_1024_238   5741.0  0.040934  0.198154  0.000   1.0
FCFP6_1024_239   5741.0  0.130117  0.336461  0.000   1.0
FCFP6_1024_240   5741.0  0.059746  0.237036  0.000   1.0
FCFP6_1024_241   5741.0  0.033618  0.180259  0.000   1.0
FCFP6_1024_242   5741.0  0.031876  0.175685  0.000   1.0
FCFP6_1024_243   5741.0  0.024386  0.154258  0.000   1.0
FCFP6_1024_244   5741.0  0.022296  0.147657  0.000   1.0
FCFP6_1024_245   5741.0  0.048249  0.214312  0.000   1.0
FCFP6_1024_246   5741.0  0.024212  0.153720  0.000   1.0
FCFP6_1024_247   5741.0  0.067236  0.250452  0.000   1.0
FCFP6_1024_248   5741.0  0.014632  0.120083  0.000   1.0
FCFP6_1024_249   5741.0  0.107995  0.310401  0.000   1.0
FCFP6_1024_250   5741.0  0.018638  0.135254  0.000   1.0
FCFP6_1024_251   5741.0  0.065145  0.246804  0.000   1.0
FCFP6_1024_252   5741.0  0.010974  0.104188  0.000   1.0
FCFP6_1024_253   5741.0  0.007142  0.084213  0.000   1.0
FCFP6_1024_254   5741.0  0.024909  0.155860  0.000   1.0
FCFP6_1024_255   5741.0  0.036753  0.188172  0.000   1.0
FCFP6_1024_256   5741.0  0.009058  0.094748  0.000   1.0
FCFP6_1024_257   5741.0  0.054694  0.227402  0.000   1.0
FCFP6_1024_258   5741.0  0.036056  0.186447  0.000   1.0
FCFP6_1024_259   5741.0  0.052778  0.223610  0.000   1.0
FCFP6_1024_260   5741.0  0.017419  0.130836  0.000   1.0
FCFP6_1024_261   5741.0  0.014632  0.120083  0.000   1.0
FCFP6_1024_262   5741.0  0.041979  0.200558  0.000   1.0
FCFP6_1024_263   5741.0  0.199443  0.399616  0.000   1.0
FCFP6_1024_264   5741.0  0.044766  0.206807  0.000   1.0
FCFP6_1024_265   5741.0  0.020031  0.140120  0.000   1.0
FCFP6_1024_266   5741.0  0.020031  0.140120  0.000   1.0
FCFP6_1024_267   5741.0  0.022644  0.148779  0.000   1.0
FCFP6_1024_268   5741.0  0.037450  0.189878  0.000   1.0
FCFP6_1024_269   5741.0  0.071590  0.257831  0.000   1.0
FCFP6_1024_270   5741.0  0.175928  0.380792  0.000   1.0
FCFP6_1024_271   5741.0  0.012890  0.112809  0.000   1.0
FCFP6_1024_272   5741.0  0.033792  0.180709  0.000   1.0
FCFP6_1024_273   5741.0  0.009406  0.096536  0.000   1.0
FCFP6_1024_274   5741.0  0.037450  0.189878  0.000   1.0
FCFP6_1024_275   5741.0  0.035534  0.185141  0.000   1.0
FCFP6_1024_276   5741.0  0.017593  0.131477  0.000   1.0
FCFP6_1024_277   5741.0  0.046856  0.211349  0.000   1.0
FCFP6_1024_278   5741.0  0.027521  0.163611  0.000   1.0
FCFP6_1024_279   5741.0  0.136910  0.343782  0.000   1.0
FCFP6_1024_280   5741.0  0.120362  0.325413  0.000   1.0
FCFP6_1024_281   5741.0  0.001742  0.041703  0.000   1.0
FCFP6_1024_282   5741.0  0.205887  0.404384  0.000   1.0
FCFP6_1024_283   5741.0  0.031179  0.173817  0.000   1.0
FCFP6_1024_284   5741.0  0.008361  0.091063  0.000   1.0
FCFP6_1024_285   5741.0  0.027173  0.162601  0.000   1.0
FCFP6_1024_286   5741.0  0.011496  0.106612  0.000   1.0
FCFP6_1024_287   5741.0  0.050340  0.218664  0.000   1.0
FCFP6_1024_288   5741.0  0.052082  0.222211  0.000   1.0
FCFP6_1024_289   5741.0  0.011670  0.107407  0.000   1.0
FCFP6_1024_290   5741.0  0.019335  0.137710  0.000   1.0
FCFP6_1024_291   5741.0  0.016548  0.127580  0.000   1.0
FCFP6_1024_292   5741.0  0.009580  0.097417  0.000   1.0
FCFP6_1024_293   5741.0  0.015677  0.124232  0.000   1.0
FCFP6_1024_294   5741.0  0.038147  0.191567  0.000   1.0
FCFP6_1024_295   5741.0  0.032224  0.176611  0.000   1.0
FCFP6_1024_296   5741.0  0.044766  0.206807  0.000   1.0
FCFP6_1024_297   5741.0  0.117575  0.322133  0.000   1.0
FCFP6_1024_298   5741.0  0.027696  0.164113  0.000   1.0
FCFP6_1024_299   5741.0  0.062184  0.241511  0.000   1.0
FCFP6_1024_300   5741.0  0.040411  0.196939  0.000   1.0
FCFP6_1024_301   5741.0  0.031876  0.175685  0.000   1.0
FCFP6_1024_302   5741.0  0.006967  0.083187  0.000   1.0
FCFP6_1024_303   5741.0  0.008187  0.090117  0.000   1.0
FCFP6_1024_304   5741.0  0.058352  0.234429  0.000   1.0
FCFP6_1024_305   5741.0  0.083435  0.276563  0.000   1.0
FCFP6_1024_306   5741.0  0.004703  0.068423  0.000   1.0
FCFP6_1024_307   5741.0  0.033618  0.180259  0.000   1.0
FCFP6_1024_308   5741.0  0.021425  0.144808  0.000   1.0
FCFP6_1024_309   5741.0  0.066365  0.248940  0.000   1.0
FCFP6_1024_310   5741.0  0.012890  0.112809  0.000   1.0
FCFP6_1024_311   5741.0  0.036579  0.187742  0.000   1.0
FCFP6_1024_312   5741.0  0.043198  0.203320  0.000   1.0
FCFP6_1024_313   5741.0  0.033444  0.179808  0.000   1.0
FCFP6_1024_314   5741.0  0.005226  0.072105  0.000   1.0
FCFP6_1024_315   5741.0  0.025431  0.157444  0.000   1.0
FCFP6_1024_316   5741.0  0.035360  0.184703  0.000   1.0
FCFP6_1024_317   5741.0  0.040063  0.196123  0.000   1.0
FCFP6_1024_318   5741.0  0.261975  0.439748  0.000   1.0
FCFP6_1024_319   5741.0  0.039018  0.193654  0.000   1.0
FCFP6_1024_320   5741.0  0.024560  0.154794  0.000   1.0
FCFP6_1024_321   5741.0  0.013412  0.115042  0.000   1.0
FCFP6_1024_322   5741.0  0.068803  0.253141  0.000   1.0
FCFP6_1024_323   5741.0  0.059397  0.236387  0.000   1.0
FCFP6_1024_324   5741.0  0.038669  0.192822  0.000   1.0
FCFP6_1024_325   5741.0  0.052430  0.222912  0.000   1.0
FCFP6_1024_326   5741.0  0.031353  0.174286  0.000   1.0
FCFP6_1024_327   5741.0  0.014980  0.121483  0.000   1.0
FCFP6_1024_328   5741.0  0.014109  0.117951  0.000   1.0
FCFP6_1024_329   5741.0  0.060617  0.238647  0.000   1.0
FCFP6_1024_330   5741.0  0.037798  0.190725  0.000   1.0
FCFP6_1024_331   5741.0  0.024560  0.154794  0.000   1.0
FCFP6_1024_332   5741.0  0.026302  0.160046  0.000   1.0
FCFP6_1024_333   5741.0  0.046159  0.209848  0.000   1.0
FCFP6_1024_334   5741.0  0.017941  0.132749  0.000   1.0
FCFP6_1024_335   5741.0  0.017419  0.130836  0.000   1.0
FCFP6_1024_336   5741.0  0.007838  0.088195  0.000   1.0
FCFP6_1024_337   5741.0  0.013412  0.115042  0.000   1.0
FCFP6_1024_338   5741.0  0.010451  0.101704  0.000   1.0
FCFP6_1024_339   5741.0  0.038843  0.193238  0.000   1.0
FCFP6_1024_340   5741.0  0.019683  0.138921  0.000   1.0
FCFP6_1024_341   5741.0  0.019335  0.137710  0.000   1.0
FCFP6_1024_342   5741.0  0.040759  0.197750  0.000   1.0
FCFP6_1024_343   5741.0  0.051559  0.221154  0.000   1.0
FCFP6_1024_344   5741.0  0.056785  0.231451  0.000   1.0
FCFP6_1024_345   5741.0  0.035360  0.184703  0.000   1.0
FCFP6_1024_346   5741.0  0.466992  0.498953  0.000   1.0
FCFP6_1024_347   5741.0  0.095628  0.294106  0.000   1.0
FCFP6_1024_348   5741.0  0.020728  0.142485  0.000   1.0

In [7]:
# Categorical Feature Statistics
cat_stats

'No categorical/object features to summarize.'

In [8]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,0.692,0.285,2.369,0.057,log,37698.4,37354.6,lognormal

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to qsar_tid_11/019d7369-7ffa-7d6a-b578-fa8c63c7adb6

019d7369-7ffa-7d6a-b578-fa8c63c7adb6
22e72245604999f978deaada71170b6f1e80a1348184aa35e98f98f6fc6b053e