### Dataset and Task Metadata

In [15]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="naticusdroid_android_permissions_dataset",
    dataset_year="2021",
    domain_str="technology & internet",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://archive.ics.uci.edu/dataset/722/naticusdroid+android+permissions+dataset",
    download_description="""
We download the data from the UCI repository and uzip it to a predefined folder.

mkdir -p local-data-warehouse/naticusdroid_android_permissions_dataset/ && wget -P local-data-warehouse/naticusdroid_android_permissions_dataset/ https://archive.ics.uci.edu/static/public/722/naticusdroid+android+permissions+dataset.zip && unzip local-data-warehouse/naticusdroid_android_permissions_dataset/naticusdroid+android+permissions+dataset.zip -d local-data-warehouse/naticusdroid_android_permissions_dataset/  && rm local-data-warehouse/naticusdroid_android_permissions_dataset/naticusdroid+android+permissions+dataset.zip
""",
    # References
    academic_reference_bibtex="""@article{mathur2021naticusdroid,
  title={NATICUSdroid: A malware detection framework for Android using native and custom permissions},
  author={Mathur, Akshay and Podila, Laxmi Mounika and Kulkarni, Keyur and Niyaz, Quamar and Javaid, Ahmad Y},
  journal={Journal of Information Security and Applications},
  volume={58},
  pages={102696},
  year={2021},
  publisher={Elsevier}
}
""",
    academic_reference_bibtex_key="mathur2021naticusdroid",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
- Map target column to categorical with values "Yes" and "No" instead of 1 and 0.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Result",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="Result",
)

## Preprocessing

In [16]:
import pandas as pd

df = pd.read_csv(f"{dataset_mold.path}/data.csv", header=0)

cat_features = [
    "Result"
]

df["Result"] = df["Result"].map({0: "No", 1: "Yes"})

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

df[cat_features] = df[cat_features].astype("category")

In [17]:
# Use if needed to get see all cols of pandas dataframes
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
df.head()

,android.permission.GET_ACCOUNTS,com.sonyericsson.home.permission.BROADCAST_BADGE,android.permission.READ_PROFILE,android.permission.MANAGE_ACCOUNTS,android.permission.WRITE_SYNC_SETTINGS,android.permission.READ_EXTERNAL_STORAGE,android.permission.RECEIVE_SMS,com.android.launcher.permission.READ_SETTINGS,android.permission.WRITE_SETTINGS,com.google.android.providers.gsf.permission.READ_GSERVICES,android.permission.DOWNLOAD_WITHOUT_NOTIFICATION,android.permission.GET_TASKS,android.permission.WRITE_EXTERNAL_STORAGE,android.permission.RECORD_AUDIO,com.huawei.android.launcher.permission.CHANGE_BADGE,com.oppo.launcher.permission.READ_SETTINGS,android.permission.CHANGE_NETWORK_STATE,com.android.launcher.permission.INSTALL_SHORTCUT,android.permission.android.permission.READ_PHONE_STATE,android.permission.CALL_PHONE,android.permission.WRITE_CONTACTS,android.permission.READ_PHONE_STATE,com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY,android.permission.MODIFY_AUDIO_SETTINGS,android.permission.ACCESS_LOCATION_EXTRA_COMMANDS,android.permission.INTERNET,android.permission.MOUNT_UNMOUNT_FILESYSTEMS,com.majeur.launcher.permission.UPDATE_BADGE,android.permission.AUTHENTICATE_ACCOUNTS,com.htc.launcher.permission.READ_SETTINGS,android.permission.ACCESS_WIFI_STATE,android.permission.FLASHLIGHT,android.permission.READ_APP_BADGE,android.permission.USE_CREDENTIALS,android.permission.CHANGE_CONFIGURATION,android.permission.READ_SYNC_SETTINGS,android.permission.BROADCAST_STICKY,com.anddoes.launcher.permission.UPDATE_COUNT,com.android.alarm.permission.SET_ALARM,com.google.android.c2dm.permission.RECEIVE,android.permission.KILL_BACKGROUND_PROCESSES,com.sonymobile.home.permission.PROVIDER_INSERT_BADGE,com.sec.android.provider.badge.permission.READ,android.permission.WRITE_CALENDAR,android.permission.SEND_SMS,com.huawei.android.launcher.permission.WRITE_SETTINGS,android.permission.REQUEST_INSTALL_PACKAGES,android.permission.SET_WALLPAPER_HINTS,android.permission.SET_WALLPAPER,com.oppo.launcher.permission.WRITE_SETTINGS,android.permission.RESTART_PACKAGES,me.everything.badger.permission.BADGE_COUNT_WRITE,android.permission.ACCESS_MOCK_LOCATION,android.permission.ACCESS_COARSE_LOCATION,android.permission.READ_LOGS,com.google.android.gms.permission.ACTIVITY_RECOGNITION,com.amazon.device.messaging.permission.RECEIVE,android.permission.SYSTEM_ALERT_WINDOW,android.permission.DISABLE_KEYGUARD,android.permission.USE_FINGERPRINT,me.everything.badger.permission.BADGE_COUNT_READ,android.permission.CHANGE_WIFI_STATE,android.permission.READ_CONTACTS,com.android.vending.BILLING,android.permission.READ_CALENDAR,android.permission.RECEIVE_BOOT_COMPLETED,android.permission.WAKE_LOCK,android.permission.ACCESS_FINE_LOCATION,android.permission.BLUETOOTH,android.permission.CAMERA,com.android.vending.CHECK_LICENSE,android.permission.FOREGROUND_SERVICE,android.permission.BLUETOOTH_ADMIN,android.permission.VIBRATE,android.permission.NFC,android.permission.RECEIVE_USER_PRESENT,android.permission.CLEAR_APP_CACHE,com.android.launcher.permission.UNINSTALL_SHORTCUT,com.sec.android.iap.permission.BILLING,com.htc.launcher.permission.UPDATE_SHORTCUT,com.sec.android.provider.badge.permission.WRITE,android.permission.ACCESS_NETWORK_STATE,com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE,com.huawei.android.launcher.permission.READ_SETTINGS,android.permission.READ_SMS,android.permission.PROCESS_INCOMING_CALLS,Result
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,No
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,Yes
2,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,No
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,No
4,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Yes

## Data Checks

In [18]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 29,332
Columns: 87
Use sampling: False (sample size: 29,332)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['android.permission.READ_LOGS', 'android.permission.READ_CONTACTS', 'android.permission.CHANGE_WIFI_STATE', 'me.everything.badger.permission.BADGE_COUNT_READ', 'android.permission.USE_FINGERPRINT', 'android.permission.DISABLE_KEYGUARD', 'android.permission.SYSTEM_ALERT_WINDOW', 'com.amazon.device.messaging.permission.RECEIVE', 'com.google.android.gms.permission.ACTIVITY_RECOGNITION', 'android.permission.ACCESS_COARSE_LOCATION']
Rows remaining as candidates after top-10 filter: 29,294 (of 29,332)

#### Duplicate Report
Total duplicate rows: 21841 (74.46% of dataset)
Duplicate rows ignoring target: 21937 (74.79% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [19]:
# Sample Rows
df_head

,android.permission.GET_ACCOUNTS,com.sonyericsson.home.permission.BROADCAST_BADGE,android.permission.READ_PROFILE,android.permission.MANAGE_ACCOUNTS,android.permission.WRITE_SYNC_SETTINGS,android.permission.READ_EXTERNAL_STORAGE,android.permission.RECEIVE_SMS,com.android.launcher.permission.READ_SETTINGS,android.permission.WRITE_SETTINGS,com.google.android.providers.gsf.permission.READ_GSERVICES,android.permission.DOWNLOAD_WITHOUT_NOTIFICATION,android.permission.GET_TASKS,android.permission.WRITE_EXTERNAL_STORAGE,android.permission.RECORD_AUDIO,com.huawei.android.launcher.permission.CHANGE_BADGE,com.oppo.launcher.permission.READ_SETTINGS,android.permission.CHANGE_NETWORK_STATE,com.android.launcher.permission.INSTALL_SHORTCUT,android.permission.android.permission.READ_PHONE_STATE,android.permission.CALL_PHONE,android.permission.WRITE_CONTACTS,android.permission.READ_PHONE_STATE,com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY,android.permission.MODIFY_AUDIO_SETTINGS,android.permission.ACCESS_LOCATION_EXTRA_COMMANDS,android.permission.INTERNET,android.permission.MOUNT_UNMOUNT_FILESYSTEMS,com.majeur.launcher.permission.UPDATE_BADGE,android.permission.AUTHENTICATE_ACCOUNTS,com.htc.launcher.permission.READ_SETTINGS,android.permission.ACCESS_WIFI_STATE,android.permission.FLASHLIGHT,android.permission.READ_APP_BADGE,android.permission.USE_CREDENTIALS,android.permission.CHANGE_CONFIGURATION,android.permission.READ_SYNC_SETTINGS,android.permission.BROADCAST_STICKY,com.anddoes.launcher.permission.UPDATE_COUNT,com.android.alarm.permission.SET_ALARM,com.google.android.c2dm.permission.RECEIVE,android.permission.KILL_BACKGROUND_PROCESSES,com.sonymobile.home.permission.PROVIDER_INSERT_BADGE,com.sec.android.provider.badge.permission.READ,android.permission.WRITE_CALENDAR,android.permission.SEND_SMS,com.huawei.android.launcher.permission.WRITE_SETTINGS,android.permission.REQUEST_INSTALL_PACKAGES,android.permission.SET_WALLPAPER_HINTS,android.permission.SET_WALLPAPER,com.oppo.launcher.permission.WRITE_SETTINGS,android.permission.RESTART_PACKAGES,me.everything.badger.permission.BADGE_COUNT_WRITE,android.permission.ACCESS_MOCK_LOCATION,android.permission.ACCESS_COARSE_LOCATION,android.permission.READ_LOGS,com.google.android.gms.permission.ACTIVITY_RECOGNITION,com.amazon.device.messaging.permission.RECEIVE,android.permission.SYSTEM_ALERT_WINDOW,android.permission.DISABLE_KEYGUARD,android.permission.USE_FINGERPRINT,me.everything.badger.permission.BADGE_COUNT_READ,android.permission.CHANGE_WIFI_STATE,android.permission.READ_CONTACTS,com.android.vending.BILLING,android.permission.READ_CALENDAR,android.permission.RECEIVE_BOOT_COMPLETED,android.permission.WAKE_LOCK,android.permission.ACCESS_FINE_LOCATION,android.permission.BLUETOOTH,android.permission.CAMERA,com.android.vending.CHECK_LICENSE,android.permission.FOREGROUND_SERVICE,android.permission.BLUETOOTH_ADMIN,android.permission.VIBRATE,android.permission.NFC,android.permission.RECEIVE_USER_PRESENT,android.permission.CLEAR_APP_CACHE,com.android.launcher.permission.UNINSTALL_SHORTCUT,com.sec.android.iap.permission.BILLING,com.htc.launcher.permission.UPDATE_SHORTCUT,com.sec.android.provider.badge.permission.WRITE,android.permission.ACCESS_NETWORK_STATE,com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE,com.huawei.android.launcher.permission.READ_SETTINGS,android.permission.READ_SMS,android.permission.PROCESS_INCOMING_CALLS,Result
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,No
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,Yes
2,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,No
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,No
4,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Yes

In [20]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Result,category,0.0,0.0,2.0,"Yes, No"
1,android.permission.GET_ACCOUNTS,int64,0.0,0.0,2.0,"0, 1"
2,com.sonyericsson.home.permission.BROADCAST_BADGE,int64,0.0,0.0,2.0,"0, 1"
3,android.permission.READ_PROFILE,int64,0.0,0.0,2.0,"0, 1"
4,android.permission.MANAGE_ACCOUNTS,int64,0.0,0.0,2.0,"0, 1"
5,android.permission.WRITE_SYNC_SETTINGS,int64,0.0,0.0,2.0,"0, 1"
6,android.permission.READ_EXTERNAL_STORAGE,int64,0.0,0.0,2.0,"0, 1"
7,android.permission.RECEIVE_SMS,int64,0.0,0.0,2.0,"0, 1"
8,com.android.launcher.permission.READ_SETTINGS,int64,0.0,0.0,2.0,"0, 1"
9,android.permission.WRITE_SETTINGS,int64,0.0,0.0,2.0,"0, 1"
10,com.google.android.providers.gsf.permission.READ_GSERVICES,int64,0.0,0.0,2.0,"0, 1"
11,android.permission.DOWNLOAD_WITHOUT_NOTIFICATION,int64,0.0,0.0,2.0,"0, 1"
12,android.permission.GET_TASKS,int64,0.0,0.0,2.0,"0, 1"
13,android.permission.WRITE_EXTERNAL_STORAGE,int64,0.0,0.0,2.0,"1, 0"
14,android.permission.RECORD_AUDIO,int64,0.0,0.0,2.0,"0, 1"
15,com.huawei.android.launcher.permission.CHANGE_BADGE,int64,0.0,0.0,2.0,"0, 1"
16,com.oppo.launcher.permission.READ_SETTINGS,int64,0.0,0.0,2.0,"0, 1"
17,android.permission.CHANGE_NETWORK_STATE,int64,0.0,0.0,2.0,"0, 1"
18,com.android.launcher.permission.INSTALL_SHORTCUT,int64,0.0,0.0,2.0,"0, 1"
19,android.permission.android.permission.READ_PHONE_STATE,int64,0.0,0.0,2.0,"0, 1"
20,android.permission.CALL_PHONE,int64,0.0,0.0,2.0,"0, 1"
21,android.permission.WRITE_CONTACTS,int64,0.0,0.0,2.0,"0, 1"
22,android.permission.READ_PHONE_STATE,int64,0.0,0.0,2.0,"1, 0"
23,com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY,int64,0.0,0.0,2.0,"0, 1"
24,android.permission.MODIFY_AUDIO_SETTINGS,int64,0.0,0.0,2.0,"0, 1"
25,android.permission.ACCESS_LOCATION_EXTRA_COMMANDS,int64,0.0,0.0,2.0,"0, 1"
26,android.permission.INTERNET,int64,0.0,0.0,2.0,"1, 0"
27,android.permission.MOUNT_UNMOUNT_FILESYSTEMS,int64,0.0,0.0,2.0,"0, 1"
28,com.majeur.launcher.permission.UPDATE_BADGE,int64,0.0,0.0,2.0,"0, 1"
29,android.permission.AUTHENTICATE_ACCOUNTS,int64,0.0,0.0,2.0,"0, 1"
30,com.htc.launcher.permission.READ_SETTINGS,int64,0.0,0.0,2.0,"0, 1"
31,android.permission.ACCESS_WIFI_STATE,int64,0.0,0.0,2.0,"1, 0"
32,android.permission.FLASHLIGHT,int64,0.0,0.0,2.0,"0, 1"
33,android.permission.READ_APP_BADGE,int64,0.0,0.0,2.0,"0, 1"
34,android.permission.USE_CREDENTIALS,int64,0.0,0.0,2.0,"0, 1"
35,android.permission.CHANGE_CONFIGURATION,int64,0.0,0.0,2.0,"0, 1"
36,android.permission.READ_SYNC_SETTINGS,int64,0.0,0.0,2.0,"0, 1"
37,android.permission.BROADCAST_STICKY,int64,0.0,0.0,2.0,"0, 1"
38,com.anddoes.launcher.permission.UPDATE_COUNT,int64,0.0,0.0,2.0,"0, 1"
39,com.android.alarm.permission.SET_ALARM,int64,0.0,0.0,2.0,"0, 1"
40,com.google.android.c2dm.permission.RECEIVE,int64,0.0,0.0,2.0,"0, 1"
41,android.permission.KILL_BACKGROUND_PROCESSES,int64,0.0,0.0,2.0,"0, 1"
42,com.sonymobile.home.permission.PROVIDER_INSERT_BADGE,int64,0.0,0.0,2.0,"0, 1"
43,com.sec.android.provider.badge.permission.READ,int64,0.0,0.0,2.0,"0, 1"
44,android.permission.WRITE_CALENDAR,int64,0.0,0.0,2.0,"0, 1"
45,android.permission.SEND_SMS,int64,0.0,0.0,2.0,"0, 1"
46,com.huawei.android.launcher.permission.WRITE_SETTINGS,int64,0.0,0.0,2.0,"0, 1"
47,android.permission.REQUEST_INSTALL_PACKAGES,int64,0.0,0.0,2.0,"0, 1"
48,android.permission.SET_WALLPAPER_HINTS,int64,0.0,0.0,2.0,"0, 1"
49,android.permission.SET_WALLPAPER,int64,0.0,0.0,2.0,"0, 1"
50,com.oppo.launcher.permission.WRITE_SETTINGS,int64,0.0,0.0,2.0,"0, 1"
51,android.permission.RESTART_PACKAGES,int64,0.0,0.0,2.0,"0, 1"
52,me.everything.badger.permission.BADGE_COUNT_WRITE,int64,0.0,0.0,2.0,"0, 1"
53,android.permission.ACCESS_MOCK_LOCATION,int64,0.0,0.0,2.0,"0, 1"
54,android.permission.ACCESS_COARSE_LOCATION,int64,0.0,0.0,2.0,"0, 1"
55,android.permission.READ_LOGS,int64,0.0,0.0,2.0,"0, 1"
56,com.google.android.gms.permission.ACTIVITY_RECOGNITION,int64,0.0,0.0,2.0,"0, 1"
57,com.amazon.device.messaging.permission.RECEIVE,int64,0.0,0.0,2.0,"0, 1"
58,android.permission.SYSTEM_ALERT_WINDOW,int64,0.0,0.0,2.0,"0, 1"
59,android.permission.DISABLE_KEYGUARD,int64,0.0,0.0,2.0,"0, 1"
60,android.permission.USE_FINGERPRINT,int64,0.0,0.0,2.0,"0, 1"
61,me.everything.badger.permission.BADGE_COUNT_READ,int64,0.0,0.0,2.0,"0, 1"
62,android.permission.CHANGE_WIFI_STATE,int64,0.0,0.0,2.0,"0, 1"
63,android.permission.READ_CONTACTS,int64,0.0,0.0,2.0,"0, 1"
64,com.android.vending.BILLING,int64,0.0,0.0,2.0,"0, 1"
65,android.permission.READ_CALENDAR,int64,0.0,0.0,2.0,"0, 1"
66,android.permission.RECEIVE_BOOT_COMPLETED,int64,0.0,0.0,2.0,"0, 1"
67,android.permission.WAKE_LOCK,int64,0.0,0.0,2.0,"0, 1"
68,android.permission.ACCESS_FINE_LOCATION,int64,0.0,0.0,2.0,"0, 1"
69,android.permission.BLUETOOTH,int64,0.0,0.0,2.0,"0, 1"
70,android.permission.CAMERA,int64,0.0,0.0,2.0,"0, 1"
71,com.android.vending.CHECK_LICENSE,int64,0.0,0.0,2.0,"0, 1"
72,android.permission.FOREGROUND_SERVICE,int64,0.0,0.0,2.0,"0, 1"
73,android.permission.BLUETOOTH_ADMIN,int64,0.0,0.0,2.0,"0, 1"
74,android.permission.VIBRATE,int64,0.0,0.0,2.0,"0, 1"
75,android.permission.NFC,int64,0.0,0.0,2.0,"0, 1"
76,android.permission.RECEIVE_USER_PRESENT,int64,0.0,0.0,2.0,"0, 1"
77,android.permission.CLEAR_APP_CACHE,int64,0.0,0.0,2.0,"0, 1"
78,com.android.launcher.permission.UNINSTALL_SHORTCUT,int64,0.0,0.0,2.0,"0, 1"
79,com.sec.android.iap.permission.BILLING,int64,0.0,0.0,2.0,"0, 1"
80,com.htc.launcher.permission.UPDATE_SHORTCUT,int64,0.0,0.0,2.0,"0, 1"
81,com.sec.android.provider.badge.permission.WRITE,int64,0.0,0.0,2.0,"0, 1"
82,android.permission.ACCESS_NETWORK_STATE,int64,0.0,0.0,2.0,"1, 0"
83,com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE,int64,0.0,0.0,2.0,"0, 1"
84,com.huawei.android.launcher.permission.READ_SETTINGS,int64,0.0,0.0,2.0,"0, 1"
85,android.permission.READ_SMS,int64,0.0,0.0,2.0,"0, 1"
86,android.permission.PROCESS_INCOMING_CALLS,int64,0.0,0.0,2.0,"0, 1"

In [21]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
android.permission.GET_ACCOUNTS,29332.0,0.226033,0.418268,0.0,1.0
com.sonyericsson.home.permission.BROADCAST_BADGE,29332.0,0.034263,0.181907,0.0,1.0
android.permission.READ_PROFILE,29332.0,0.045888,0.209247,0.0,1.0
android.permission.MANAGE_ACCOUNTS,29332.0,0.013603,0.115837,0.0,1.0
android.permission.WRITE_SYNC_SETTINGS,29332.0,0.005762,0.075688,0.0,1.0
android.permission.READ_EXTERNAL_STORAGE,29332.0,0.171690,0.377117,0.0,1.0
android.permission.RECEIVE_SMS,29332.0,0.060071,0.237622,0.0,1.0
com.android.launcher.permission.READ_SETTINGS,29332.0,0.014114,0.117964,0.0,1.0
android.permission.WRITE_SETTINGS,29332.0,0.110800,0.313890,0.0,1.0
com.google.android.providers.gsf.permission.READ_GSERVICES,29332.0,0.043741,0.204521,0.0,1.0
android.permission.DOWNLOAD_WITHOUT_NOTIFICATION,29332.0,0.011046,0.104519,0.0,1.0
android.permission.GET_TASKS,29332.0,0.233533,0.423086,0.0,1.0
android.permission.WRITE_EXTERNAL_STORAGE,29332.0,0.669201,0.470509,0.0,1.0
android.permission.RECORD_AUDIO,29332.0,0.058707,0.235080,0.0,1.0
com.huawei.android.launcher.permission.CHANGE_BADGE,29332.0,0.022944,0.149728,0.0,1.0
com.oppo.launcher.permission.READ_SETTINGS,29332.0,0.017626,0.131589,0.0,1.0
android.permission.CHANGE_NETWORK_STATE,29332.0,0.038422,0.192217,0.0,1.0
com.android.launcher.permission.INSTALL_SHORTCUT,29332.0,0.214169,0.410251,0.0,1.0
android.permission.android.permission.READ_PHONE_STATE,29332.0,0.003614,0.060007,0.0,1.0
android.permission.CALL_PHONE,29332.0,0.075753,0.264608,0.0,1.0
android.permission.WRITE_CONTACTS,29332.0,0.064707,0.246013,0.0,1.0
android.permission.READ_PHONE_STATE,29332.0,0.587379,0.492314,0.0,1.0
com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY,29332.0,0.004125,0.064096,0.0,1.0
android.permission.MODIFY_AUDIO_SETTINGS,29332.0,0.031263,0.174030,0.0,1.0
android.permission.ACCESS_LOCATION_EXTRA_COMMANDS,29332.0,0.040740,0.197692,0.0,1.0
android.permission.INTERNET,29332.0,0.975317,0.155160,0.0,1.0
android.permission.MOUNT_UNMOUNT_FILESYSTEMS,29332.0,0.059082,0.235783,0.0,1.0
com.majeur.launcher.permission.UPDATE_BADGE,29332.0,0.032354,0.176941,0.0,1.0
android.permission.AUTHENTICATE_ACCOUNTS,29332.0,0.010398,0.101442,0.0,1.0
com.htc.launcher.permission.READ_SETTINGS,29332.0,0.041286,0.198954,0.0,1.0
android.permission.ACCESS_WIFI_STATE,29332.0,0.525058,0.499380,0.0,1.0
android.permission.FLASHLIGHT,29332.0,0.039445,0.194654,0.0,1.0
android.permission.READ_APP_BADGE,29332.0,0.017217,0.130080,0.0,1.0
android.permission.USE_CREDENTIALS,29332.0,0.026319,0.160086,0.0,1.0
android.permission.CHANGE_CONFIGURATION,29332.0,0.020626,0.142131,0.0,1.0
android.permission.READ_SYNC_SETTINGS,29332.0,0.004671,0.068184,0.0,1.0
android.permission.BROADCAST_STICKY,29332.0,0.009103,0.094974,0.0,1.0
com.anddoes.launcher.permission.UPDATE_COUNT,29332.0,0.032763,0.178018,0.0,1.0
com.android.alarm.permission.SET_ALARM,29332.0,0.005216,0.072036,0.0,1.0
com.google.android.c2dm.permission.RECEIVE,29332.0,0.212430,0.409035,0.0,1.0
android.permission.KILL_BACKGROUND_PROCESSES,29332.0,0.033138,0.179000,0.0,1.0
com.sonymobile.home.permission.PROVIDER_INSERT_BADGE,29332.0,0.022808,0.149293,0.0,1.0
com.sec.android.provider.badge.permission.READ,29332.0,0.034229,0.181820,0.0,1.0
android.permission.WRITE_CALENDAR,29332.0,0.013978,0.117401,0.0,1.0
android.permission.SEND_SMS,29332.0,0.068730,0.252999,0.0,1.0
com.huawei.android.launcher.permission.WRITE_SETTINGS,29332.0,0.023012,0.149945,0.0,1.0
android.permission.REQUEST_INSTALL_PACKAGES,29332.0,0.007773,0.087823,0.0,1.0
android.permission.SET_WALLPAPER_HINTS,29332.0,0.007466,0.086086,0.0,1.0
android.permission.SET_WALLPAPER,29332.0,0.048548,0.214924,0.0,1.0
com.oppo.launcher.permission.WRITE_SETTINGS,29332.0,0.017387,0.130711,0.0,1.0
android.permission.RESTART_PACKAGES,29332.0,0.047798,0.213341,0.0,1.0
me.everything.badger.permission.BADGE_COUNT_WRITE,29332.0,0.013978,0.117401,0.0,1.0
android.permission.ACCESS_MOCK_LOCATION,29332.0,0.012137,0.109499,0.0,1.0
android.permission.ACCESS_COARSE_LOCATION,29332.0,0.463896,0.498703,0.0,1.0
android.permission.READ_LOGS,29332.0,0.057003,0.231852,0.0,1.0
com.google.android.gms.permission.ACTIVITY_RECOGNITION,29332.0,0.005557,0.074340,0.0,1.0
com.amazon.device.messaging.permission.RECEIVE,29332.0,0.003921,0.062493,0.0,1.0
android.permission.SYSTEM_ALERT_WINDOW,29332.0,0.186963,0.389889,0.0,1.0
android.permission.DISABLE_KEYGUARD,29332.0,0.026422,0.160388,0.0,1.0
android.permission.USE_FINGERPRINT,29332.0,0.009512,0.097065,0.0,1.0
me.everything.badger.permission.BADGE_COUNT_READ,29332.0,0.013978,0.117401,0.0,1.0
android.permission.CHANGE_WIFI_STATE,29332.0,0.086833,0.281596,0.0,1.0
android.permission.READ_CONTACTS,29332.0,0.127029,0.333011,0.0,1.0
com.android.vending.BILLING,29332.0,0.132620,0.339169,0.0,1.0
android.permission.READ_CALENDAR,29332.0,0.014046,0.117683,0.0,1.0
android.permission.RECEIVE_BOOT_COMPLETED,29332.0,0.454862,0.497967,0.0,1.0
android.permission.WAKE_LOCK,29332.0,0.480874,0.499643,0.0,1.0
android.permission.ACCESS_FINE_LOCATION,29332.0,0.445520,0.497032,0.0,1.0
android.permission.BLUETOOTH,29332.0,0.041559,0.199582,0.0,1.0
android.permission.CAMERA,29332.0,0.148882,0.355978,0.0,1.0
com.android.vending.CHECK_LICENSE,29332.0,0.027104,0.162388,0.0,1.0
android.permission.FOREGROUND_SERVICE,29332.0,0.003887,0.062222,0.0,1.0
android.permission.BLUETOOTH_ADMIN,29332.0,0.031536,0.174763,0.0,1.0
android.permission.VIBRATE,29332.0,0.349039,0.476674,0.0,1.0
android.permission.NFC,29332.0,0.006409,0.079803,0.0,1.0
android.permission.RECEIVE_USER_PRESENT,29332.0,0.013603,0.115837,0.0,1.0
android.permission.CLEAR_APP_CACHE,29332.0,0.004432,0.066427,0.0,1.0
com.android.launcher.permission.UNINSTALL_SHORTCUT,29332.0,0.029660,0.169652,0.0,1.0
com.sec.android.iap.permission.BILLING,29332.0,0.003887,0.062222,0.0,1.0
com.htc.launcher.permission.UPDATE_SHORTCUT,29332.0,0.033445,0.179798,0.0,1.0
com.sec.android.provider.badge.permission.WRITE,29332.0,0.034297,0.181994,0.0,1.0
android.permission.ACCESS_NETWORK_STATE,29332.0,0.949032,0.219937,0.0,1.0
com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE,29332.0,0.023728,0.152204,0.0,1.0
com.huawei.android.launcher.permission.READ_SETTINGS,29332.0,0.023387,0.151133,0.0,1.0
android.permission.READ_SMS,29332.0,0.051718,0.221461,0.0,1.0
android.permission.PROCESS_INCOMING_CALLS,29332.0,0.003648,0.060289,0.0,1.0

In [22]:
# Categorical Feature Statistics
cat_stats

            value  count    pct
column rank
Result 1      Yes  14700  50.12
       2       No  14632  49.88

In [23]:
# Target Distribution
target_df

        count    pct
Result
Yes     14700  50.12
No      14632  49.88

## Task Curation

In [24]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [25]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [26]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to naticusdroid_android_permissions_dataset/019d35cd-fdc7-73eb-b6a5-aad6e45d7019
019d35cd-fdc7-73eb-b6a5-aad6e45d7019
8b2ea4b95ddfe246c08569890032d796c3005e31bd2abd1a68d573649831a1a0