### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="bioresponse",
    dataset_year="2012",
    domain_str="biology & life sciences",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/c/bioresponse",
    download_description="""
We download the data from Kaggle and uzip it to a predefined folder.

mkdir -p local-data-warehouse/bioresponse && cd local-data-warehouse/bioresponse && kaggle competitions download -c bioresponse && unzip bioresponse.zip && rm bioresponse.zip
""",
    # References
    academic_reference_bibtex="""@misc{bioresponse2012hamner,
    author = {Ben Hamner and dcthompson and Jorg},
    title = {Predicting a Biological Response},
    year = {2012},
    howpublished = {https://kaggle.com/competitions/bioresponse},
    note = {Kaggle}
}
""",
    academic_reference_bibtex_key="bioresponse2012hamner",
    license="Public Domain",
    data_tags=["IID"],
    curation_comments="""
- We changed the name of the target and mapped it to yes/no
- Anomaly: Only train data is used, since test data is empty for target
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="MoleculeElicitsResponse",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="MoleculeElicitsResponse",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(f"{dataset_mold.path}/train.csv")

df = df.rename(columns={"Activity": "MoleculeElicitsResponse"})

cat_features = [
    'MoleculeElicitsResponse'
]
df["MoleculeElicitsResponse"] = df["MoleculeElicitsResponse"].map({0: "No", 1: "Yes"}).astype("category")

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 3,751
Columns: 1777
Use sampling: False (sample size: 3,751)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['D17', 'D9', 'D6', 'D10', 'D7', 'D15', 'D30', 'D89', 'D105', 'D106']
Rows remaining as candidates after top-10 filter: 0 (of 3,751)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,MoleculeElicitsResponse,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14,D15,D16,D17,D18,D19,D20,D21,D22,D23,D24,D25,D26,D27,D28,D29,D30,D31,D32,D33,D34,D35,D36,D37,D38,D39,D40,D41,D42,D43,D44,D45,D46,D47,D48,D49,D50,D51,D52,D53,D54,D55,D56,D57,D58,D59,D60,D61,D62,D63,D64,D65,D66,D67,D68,D69,D70,D71,D72,D73,D74,D75,D76,D77,D78,D79,D80,D81,D82,D83,D84,D85,D86,D87,D88,D89,D90,D91,D92,D93,D94,D95,D96,D97,D98,D99,D100,D101,D102,D103,D104,D105,D106,D107,D108,D109,D110,D111,D112,D113,D114,D115,D116,D117,D118,D119,D120,D121,D122,D123,D124,D125,D126,D127,D128,D129,D130,D131,D132,D133,D134,D135,D136,D137,D138,D139,D140,D141,D142,D143,D144,D145,D146,D147,D148,D149,D150,D151,D152,D153,D154,D155,D156,D157,D158,D159,D160,D161,D162,D163,D164,D165,D166,D167,D168,D169,D170,D171,D172,D173,D174,D175,D176,D177,D178,D179,D180,D181,D182,D183,D184,D185,D186,D187,D188,D189,D190,D191,D192,D193,D194,D195,D196,D197,D198,D199,D200,D201,D202,D203,D204,D205,D206,D207,D208,D209,D210,D211,D212,D213,D214,D215,D216,D217,D218,D219,D220,D221,D222,D223,D224,D225,D226,D227,D228,D229,D230,D231,D232,D233,D234,D235,D236,D237,D238,D239,D240,D241,D242,D243,D244,D245,D246,D247,D248,D249,D250,D251,D252,D253,D254,D255,D256,D257,D258,D259,D260,D261,D262,D263,D264,D265,D266,D267,D268,D269,D270,D271,D272,D273,D274,D275,D276,D277,D278,D279,D280,D281,D282,D283,D284,D285,D286,D287,D288,D289,D290,D291,D292,D293,D294,D295,D296,D297,D298,D299,D300,D301,D302,D303,D304,D305,D306,D307,D308,D309,D310,D311,D312,D313,D314,D315,D316,D317,D318,D319,D320,D321,D322,D323,D324,D325,D326,D327,D328,D329,D330,D331,D332,D333,D334,D335,D336,D337,D338,D339,D340,D341,D342,D343,D344,D345,D346,D347,D348,D349,D350,D351,D352,D353,D354,D355,D356,D357,D358,D359,D360,D361,D362,D363,D364,D365,D366,D367,D368,D369,D370,D371,D372,D373,D374,D375,D376,D377,D378,D379,D380,D381,D382,D383,D384,D385,D386,D387,D388,D389,D390,D391,D392,D393,D394,D395,D396,D397,D398,D399,D400,D401,D402,D403,D404,D405,D406,D407,D408,D409,D410,D411,D412,D413,D414,D415,D416,D417,D418,D419,D420,D421,D422,D423,D424,D425,D426,D427,D428,D429,D430,D431,D432,D433,D434,D435,D436,D437,D438,D439,D440,D441,D442,D443,D444,D445,D446,D447,D448,D449,D450,D451,D452,D453,D454,D455,D456,D457,D458,D459,D460,D461,D462,D463,D464,D465,D466,D467,D468,D469,D470,D471,D472,D473,D474,D475,D476,D477,D478,D479,D480,D481,D482,D483,D484,D485,D486,D487,D488,D489,D490,D491,D492,D493,D494,D495,D496,D497,D498,D499,D500,D501,D502,D503,D504,D505,D506,D507,D508,D509,D510,D511,D512,D513,D514,D515,D516,D517,D518,D519,D520,D521,D522,D523,D524,D525,D526,D527,D528,D529,D530,D531,D532,D533,D534,D535,D536,D537,D538,D539,D540,D541,D542,D543,D544,D545,D546,D547,D548,D549,D550,D551,D552,D553,D554,D555,D556,D557,D558,D559,D560,D561,D562,D563,D564,D565,D566,D567,D568,D569,D570,D571,D572,D573,D574,D575,D576,D577,D578,D579,D580,D581,D582,D583,D584,D585,D586,D587,D588,D589,D590,D591,D592,D593,D594,D595,D596,D597,D598,D599,D600,D601,D602,D603,D604,D605,D606,D607,D608,D609,D610,D611,D612,D613,D614,D615,D616,D617,D618,D619,D620,D621,D622,D623,D624,D625,D626,D627,D628,D629,D630,D631,D632,D633,D634,D635,D636,D637,D638,D639,D640,D641,D642,D643,D644,D645,D646,D647,D648,D649,D650,D651,D652,D653,D654,D655,D656,D657,D658,D659,D660,D661,D662,D663,D664,D665,D666,D667,D668,D669,D670,D671,D672,D673,D674,D675,D676,D677,D678,D679,D680,D681,D682,D683,D684,D685,D686,D687,D688,D689,D690,D691,D692,D693,D694,D695,D696,D697,D698,D699,D700,D701,D702,D703,D704,D705,D706,D707,D708,D709,D710,D711,D712,D713,D714,D715,D716,D717,D718,D719,D720,D721,D722,D723,D724,D725,D726,D727,D728,D729,D730,D731,D732,D733,D734,D735,D736,D737,D738,D739,D740,D741,D742,D743,D744,D745,D746,D747,D748,D749,D750,D751,D752,D753,D754,D755,D756,D757,D758,D759,D760,D761,D762,D763,D764,D765,D766,D767,D768,D769,D770,D771,D772,D773,D774,D775,D776,D777,D778,D779,D780,D781,D782,D783,D784,D785,D786,D787,D788,D789,D790,D791,D792,D793,D794,D795,D796,D797,D798,D799,D800,D801,D802,D803,D804,D805,D806,D807,D808,D809,D810,D811,D812,D813,D814,D815,D816,D817,D818,D819,D820,D821,D822,D823,D824,D825,D826,D827,D828,D829,D830,D831,D832,D833,D834,D835,D836,D837,D838,D839,D840,D841,D842,D843,D844,D845,D846,D847,D848,D849,D850,D851,D852,D853,D854,D855,D856,D857,D858,D859,D860,D861,D862,D863,D864,D865,D866,D867,D868,D869,D870,D871,D872,D873,D874,D875,D876,D877,D878,D879,D880,D881,D882,D883,D884,D885,D886,D887,D888,D889,D890,D891,D892,D893,D894,D895,D896,D897,D898,D899,D900,D901,D902,D903,D904,D905,D906,D907,D908,D909,D910,D911,D912,D913,D914,D915,D916,D917,D918,D919,D920,D921,D922,D923,D924,D925,D926,D927,D928,D929,D930,D931,D932,D933,D934,D935,D936,D937,D938,D939,D940,D941,D942,D943,D944,D945,D946,D947,D948,D949,D950,D951,D952,D953,D954,D955,D956,D957,D958,D959,D960,D961,D962,D963,D964,D965,D966,D967,D968,D969,D970,D971,D972,D973,D974,D975,D976,D977,D978,D979,D980,D981,D982,D983,D984,D985,D986,D987,D988,D989,D990,D991,D992,D993,D994,D995,D996,D997,D998,D999,D1000,D1001,D1002,D1003,D1004,D1005,D1006,D1007,D1008,D1009,D1010,D1011,D1012,D1013,D1014,D1015,D1016,D1017,D1018,D1019,D1020,D1021,D1022,D1023,D1024,D1025,D1026,D1027,D1028,D1029,D1030,D1031,D1032,D1033,D1034,D1035,D1036,D1037,D1038,D1039,D1040,D1041,D1042,D1043,D1044,D1045,D1046,D1047,D1048,D1049,D1050,D1051,D1052,D1053,D1054,D1055,D1056,D1057,D1058,D1059,D1060,D1061,D1062,D1063,D1064,D1065,D1066,D1067,D1068,D1069,D1070,D1071,D1072,D1073,D1074,D1075,D1076,D1077,D1078,D1079,D1080,D1081,D1082,D1083,D1084,D1085,D1086,D1087,D1088,D1089,D1090,D1091,D1092,D1093,D1094,D1095,D1096,D1097,D1098,D1099,D1100,D1101,D1102,D1103,D1104,D1105,D1106,D1107,D1108,D1109,D1110,D1111,D1112,D1113,D1114,D1115,D1116,D1117,D1118,D1119,D1120,D1121,D1122,D1123,D1124,D1125,D1126,D1127,D1128,D1129,D1130,D1131,D1132,D1133,D1134,D1135,D1136,D1137,D1138,D1139,D1140,D1141,D1142,D1143,D1144,D1145,D1146,D1147,D1148,D1149,D1150,D1151,D1152,D1153,D1154,D1155,D1156,D1157,D1158,D1159,D1160,D1161,D1162,D1163,D1164,D1165,D1166,D1167,D1168,D1169,D1170,D1171,D1172,D1173,D1174,D1175,D1176,D1177,D1178,D1179,D1180,D1181,D1182,D1183,D1184,D1185,D1186,D1187,D1188,D1189,D1190,D1191,D1192,D1193,D1194,D1195,D1196,D1197,D1198,D1199,D1200,D1201,D1202,D1203,D1204,D1205,D1206,D1207,D1208,D1209,D1210,D1211,D1212,D1213,D1214,D1215,D1216,D1217,D1218,D1219,D1220,D1221,D1222,D1223,D1224,D1225,D1226,D1227,D1228,D1229,D1230,D1231,D1232,D1233,D1234,D1235,D1236,D1237,D1238,D1239,D1240,D1241,D1242,D1243,D1244,D1245,D1246,D1247,D1248,D1249,D1250,D1251,D1252,D1253,D1254,D1255,D1256,D1257,D1258,D1259,D1260,D1261,D1262,D1263,D1264,D1265,D1266,D1267,D1268,D1269,D1270,D1271,D1272,D1273,D1274,D1275,D1276,D1277,D1278,D1279,D1280,D1281,D1282,D1283,D1284,D1285,D1286,D1287,D1288,D1289,D1290,D1291,D1292,D1293,D1294,D1295,D1296,D1297,D1298,D1299,D1300,D1301,D1302,D1303,D1304,D1305,D1306,D1307,D1308,D1309,D1310,D1311,D1312,D1313,D1314,D1315,D1316,D1317,D1318,D1319,D1320,D1321,D1322,D1323,D1324,D1325,D1326,D1327,D1328,D1329,D1330,D1331,D1332,D1333,D1334,D1335,D1336,D1337,D1338,D1339,D1340,D1341,D1342,D1343,D1344,D1345,D1346,D1347,D1348,D1349,D1350,D1351,D1352,D1353,D1354,D1355,D1356,D1357,D1358,D1359,D1360,D1361,D1362,D1363,D1364,D1365,D1366,D1367,D1368,D1369,D1370,D1371,D1372,D1373,D1374,D1375,D1376,D1377,D1378,D1379,D1380,D1381,D1382,D1383,D1384,D1385,D1386,D1387,D1388,D1389,D1390,D1391,D1392,D1393,D1394,D1395,D1396,D1397,D1398,D1399,D1400,D1401,D1402,D1403,D1404,D1405,D1406,D1407,D1408,D1409,D1410,D1411,D1412,D1413,D1414,D1415,D1416,D1417,D1418,D1419,D1420,D1421,D1422,D1423,D1424,D1425,D1426,D1427,D1428,D1429,D1430,D1431,D1432,D1433,D1434,D1435,D1436,D1437,D1438,D1439,D1440,D1441,D1442,D1443,D1444,D1445,D1446,D1447,D1448,D1449,D1450,D1451,D1452,D1453,D1454,D1455,D1456,D1457,D1458,D1459,D1460,D1461,D1462,D1463,D1464,D1465,D1466,D1467,D1468,D1469,D1470,D1471,D1472,D1473,D1474,D1475,D1476,D1477,D1478,D1479,D1480,D1481,D1482,D1483,D1484,D1485,D1486,D1487,D1488,D1489,D1490,D1491,D1492,D1493,D1494,D1495,D1496,D1497,D1498,D1499,D1500,D1501,D1502,D1503,D1504,D1505,D1506,D1507,D1508,D1509,D1510,D1511,D1512,D1513,D1514,D1515,D1516,D1517,D1518,D1519,D1520,D1521,D1522,D1523,D1524,D1525,D1526,D1527,D1528,D1529,D1530,D1531,D1532,D1533,D1534,D1535,D1536,D1537,D1538,D1539,D1540,D1541,D1542,D1543,D1544,D1545,D1546,D1547,D1548,D1549,D1550,D1551,D1552,D1553,D1554,D1555,D1556,D1557,D1558,D1559,D1560,D1561,D1562,D1563,D1564,D1565,D1566,D1567,D1568,D1569,D1570,D1571,D1572,D1573,D1574,D1575,D1576,D1577,D1578,D1579,D1580,D1581,D1582,D1583,D1584,D1585,D1586,D1587,D1588,D1589,D1590,D1591,D1592,D1593,D1594,D1595,D1596,D1597,D1598,D1599,D1600,D1601,D1602,D1603,D1604,D1605,D1606,D1607,D1608,D1609,D1610,D1611,D1612,D1613,D1614,D1615,D1616,D1617,D1618,D1619,D1620,D1621,D1622,D1623,D1624,D1625,D1626,D1627,D1628,D1629,D1630,D1631,D1632,D1633,D1634,D1635,D1636,D1637,D1638,D1639,D1640,D1641,D1642,D1643,D1644,D1645,D1646,D1647,D1648,D1649,D1650,D1651,D1652,D1653,D1654,D1655,D1656,D1657,D1658,D1659,D1660,D1661,D1662,D1663,D1664,D1665,D1666,D1667,D1668,D1669,D1670,D1671,D1672,D1673,D1674,D1675,D1676,D1677,D1678,D1679,D1680,D1681,D1682,D1683,D1684,D1685,D1686,D1687,D1688,D1689,D1690,D1691,D1692,D1693,D1694,D1695,D1696,D1697,D1698,D1699,D1700,D1701,D1702,D1703,D1704,D1705,D1706,D1707,D1708,D1709,D1710,D1711,D1712,D1713,D1714,D1715,D1716,D1717,D1718,D1719,D1720,D1721,D1722,D1723,D1724,D1725,D1726,D1727,D1728,D1729,D1730,D1731,D1732,D1733,D1734,D1735,D1736,D1737,D1738,D1739,D1740,D1741,D1742,D1743,D1744,D1745,D1746,D1747,D1748,D1749,D1750,D1751,D1752,D1753,D1754,D1755,D1756,D1757,D1758,D1759,D1760,D1761,D1762,D1763,D1764,D1765,D1766,D1767,D1768,D1769,D1770,D1771,D1772,D1773,D1774,D1775,D1776
0,Yes,0.1000,0.734427,0.20,0.25,0.136259,0.674081,0.212153,0.512164,0.707647,0.244693,0.221774,0.0625,0.0,0.146091,0.500770,0.311070,0.606249,0.245203,0.168908,0.078300,0.01150,0.0690,1,0.00,0.472542,0.656698,1,1,0.000000,0.205872,0.091700,0.145012,0.115257,0.0519,0.220843,0.0,0.000000,0.0658,0.112614,0.0,0.0,0.0837,0.167339,0.053700,0.323341,0.582785,0.209250,0.200904,0.146952,0.833333,0,1.0,0.0469,0.218014,0.0,0.2697,0.0,0.000000,0.000,0.0000,0.073500,0.0213,0.13322,0.166667,0.0000,0.14588,0.156408,0.117573,0.150202,0.685704,0.0624,0,0.0421,0.197353,0.263474,0.0720,0.166667,0.027000,0.571429,0.0350,0.0,0.25,0.222222,0.0606,0.0,0.0507,0.291222,0.127822,0.541818,0.320355,0.417145,0.052600,0.047600,0,0.001380,0.100000,0.0000,0.0,0.609925,0.661906,0.020400,0.182956,0.182276,0.768263,0.713662,0.265804,0.578591,0.000000,0.166667,0.0,0.166667,0.0,0.0,0.0,0.0,0.0,0.000000,0.384406,0.0,0.247808,0.0,0.0,0.0,0.0,0.0,0.315789,0.166667,0.066700,0.0,0.166667,0.261905,0.0,0.0,0.0,0.0769,0.111111,0.0000,0.0,0.190476,0.0,0.0,0.0625,0.0000,0.0,0.250000,0.238095,0.0,0.0,0.0000,0.0000,0.028600,0.257576,0.0,0.0,0.0588,0.0,0.0,0.0444,0.0,0.0,0.0000,0.166667,0.0,0.0,0.333333,0.0,0.0769,0.0000,0.0,0,0.0,0.0,0.000000,0.0,0.110024,0.0,0.277786,0.830997,0.0,0.452221,0.705973,0.179805,0.97674,0.0,0.194392,0.0628,0.754647,0.0,0.309464,0.636643,0.000000,0.0,0.043,0.768255,0.0,0.653428,0.0,0.489652,0.0,0.653428,0.257565,0.588595,0.0836,0.592013,0.803928,0.0,0.705213,0.596014,0.639709,0.927678,0.0,0.789491,0.0,0.0,0.885204,0.0498,0.306713,0.718781,0.000000,0.0,0.360484,1.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.166667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0909,0.307692,0.0667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.333333,0.125,0.125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.25,0.125,0.0,0.166667,0.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.166667,0.5,0.142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.266667,0.25,0.0833,0.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.333333,0.0,0.333333,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.08,0.0,0.0,0.0263,0.133333,0.0385,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0476,0.05,0.000000,0.0714,0.0,0.133333,0.0,0.0,0.0,0.0,0.0,0.0,0.166667,0.1250,0.0417,0.0769,0.125,0.181818,0.0417,0.0741,0.0,0.0,0.1000,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.121951,0.126984,0.0,0.0,0.0,0.0,0.0,0.0,0.0714,0.0417,0.333333,0.125,0.0625,0.0,0.0,0.0455,0.0476,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.142857,0.222222,0.000,0.166667,0.0000,0.125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.00,0.125,0.176471,0.0,0.133333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.208333,0.142857,0.0909,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0714,0.000000,0.2,0.125,0.111111,0.142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0833,0.222222,0.0,0.111111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0417,0.0,0.0417,0.266667,0.0417,0.0909,0.0,0.0625,0.0,0.0,0.0,0.0,0.2,0.222222,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.295455,0.0952,0.108696,0.0444,0.0,0.0,0.0,0.0,0.125,0.0625,0.142857,0.125,0.214286,0.181818,0.0769,0.0625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0833,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0606,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.025,0.0,0.0,0.0,0.0769,0.125,0.166667,0.0,0.0645,0.0,0.0,0.0333,0.0,0.0625,0.0476,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.333333,0.25,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.139785,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.153846,0.1,0.0698,0.0317,0.0,0.0,0.0,0.0,0.166667,0.0,0.0714,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.128205,0.0,0.250,0.107143,0.133333,0,0,0,0,1,1,1,0,0,1,0,1,1,1,0,1,1,1,0,0,1,0,0,0,0,1,0,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,0,0,1,1,0,1,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,1,1,0,1,0,1,1,0,1,0,1,0,1,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,1,1,0,0,0,1,1,0,0,1,0,1,0,0,1,1,0,0,0,0,0,1,1,0,0,1,1,1,0,0,0,0,1,0,0,1,1,0,1,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,0,1,0,0,1,1,1,1,0,1,0,0,1,1,1,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0,0,1,0,1,0,0,1,0,0,1,1,0,0,1,0,0,1,1,1,1,1,1,1,0,0,1,0,0,0,1,1,1,1,0,0,1,0,0,1,0,1,0,1,1,1,1,0,0,0,1,1,0,1,1,1,1,1,0,1,0,0,0,0,0,1,0,1,1,1,1,0,0,1,0,0,0,1,0,0,1,0,1,1,1,1,1,1,1,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,1,0,1,0,0,0,0,1,0,0,0,0,1,1,0,1,0,0,1,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,1,0,0,1,1,0,1,1,0,0,0,0,1,0,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,1,1,1,1,0,0,1,1,1,0,0,1,1,1,0,1,1,0,1,0,1,1,0,1,1,0,1,1,0,0,0,1,0,0,1,0,0,0,0,0,1,1,1,1,0,1,1,0,1,1,1,1,1,0,0,1,0,0,0,0,1,1,1,0,1,1,0,1,0,1,0,1,1,1,1,1,1,0,0,0,1,1,0,0,1,0,1,1,1,1,0,0,1,1,0,0,1,0,0,1,0,0,1,1,1,0,0,0,0,1,0,1,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,1,1,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,MoleculeElicitsResponse,category,0.0,0.0,2.0,"Yes, No"
1,D1,float64,0.0,0.0,24.0,"0.0333, 0.0667, 0.0, 0.1, 0.1333, 0.1667, 0.2, 0.2333, 0.2667, 0.3333"
2,D2,float64,0.0,0.0,1768.0,"0.5702, 0.6025, 0.6995, 0.5948, 0.5493, 0.5662, 0.5178, 0.72, 0.6602, 0.4832"
3,D3,float64,0.0,0.0,15.0,"0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45"
4,D4,float64,0.0,0.0,5.0,"0.0, 0.25, 0.5, 1.0, 0.75"
5,D5,float64,0.0,0.0,2923.0,"0.2633, 0.1917, 0.2462, 0.2275, 0.1922, 0.2021, 0.2315, 0.3058, 0.2471, 0.3725"
6,D6,float64,0.0,0.0,3732.0,"0.7766, 0.7166, 0.7247, 0.7326, 0.8248, 0.7404, 0.7828, 0.7564, 0.7591, 0.7147"
7,D7,float64,0.0,0.0,3685.0,"0.2324, 0.2324, 0.2065, 0.1879, 0.1685, 0.1886, 0.0991, 0.1725, 0.0992, 0.1061"
8,D8,float64,0.0,0.0,3272.0,"0.0678, 0.5854, 0.4972, 0.137, 0.2931, 0.7756, 0.0909, 0.0791, 0.0713, 0.7385"
9,D9,float64,0.0,0.0,3741.0,"0.8705, 0.7209, 0.8139, 0.7915, 0.8105, 0.8742, 0.797, 0.8304, 0.8213, 0.7571"
10,D10,float64,0.0,0.0,3692.0,"0.2889, 0.1224, 0.1966, 0.3056, 0.4154, 0.0448, 0.0373, 0.1432, 0.012, 0.0177"
11,D11,float64,0.0,0.0,265.0,"0.0, 0.2129, 0.1774, 0.1183, 0.2661, 0.1065, 0.0968, 0.3548, 0.1521, 0.1935"
12,D12,float64,0.0,0.0,12.0,"0.0, 0.0625, 0.125, 0.1875, 0.25, 0.3125, 0.375, 0.5, 0.8125, 0.625"
13,D13,float64,0.0,0.0,20.0,"0.0, 0.0323, 0.0645, 0.129, 0.0968, 0.1935, 0.1613, 0.2258, 0.2581, 0.3226"
14,D14,float64,0.0,0.0,2390.0,"0.0677, 0.0866, 0.096, 0.0925, 0.0949, 0.0729, 0.0867, 0.1224, 0.0915, 0.0963"
15,D15,float64,0.0,0.0,3682.0,"0.5727, 0.5727, 0.5048, 0.3597, 0.5216, 0.6815, 0.5922, 0.5427, 0.5759, 0.5742"
16,D16,float64,0.0,0.0,3166.0,"0.0928, 0.3018, 0.1874, 0.6804, 0.4011, 0.5503, 0.2321, 0.1244, 0.2255, 0.1625"
17,D17,float64,0.0,0.0,3749.0,"0.5498, 0.5839, 0.5487, 0.6339, 0.3874, 0.5706, 0.5633, 0.7327, 0.4501, 0.6242"
18,D18,float64,0.0,0.0,3212.0,"0.1908, 0.0, 0.1782, 0.37, 0.1866, 0.1824, 0.3556, 0.0264, 0.0756, 0.0706"
19,D19,float64,0.0,0.0,2134.0,"0.0634, 0.0593, 0.0747, 0.1149, 0.1082, 0.0877, 0.0797, 0.0759, 0.089, 0.0829"
20,D20,float64,0.0,0.0,1531.0,"0.0, 0.0374, 0.1084, 0.0316, 0.0438, 0.0362, 0.0407, 0.0355, 0.0368, 0.0391"
21,D21,float64,0.0,0.0,1033.0,"0.0109, 0.0111, 0.0104, 0.0108, 0.0114, 0.0047, 0.0138, 0.0131, 0.0107, 0.005"
22,D22,float64,0.0,0.0,17.0,"0.0, 0.0345, 0.069, 0.1034, 0.1379, 0.1724, 0.2069, 0.2759, 0.2414, 0.3103"
23,D24,float64,0.0,0.0,5.0,"0.0, 0.25, 0.5, 0.75, 1.0"
24,D25,float64,0.0,0.0,2943.0,"0.4866, 0.4341, 0.4558, 0.4624, 0.5068, 0.4597, 0.4304, 0.5268, 0.4967, 0.4521"
25,D26,float64,0.0,0.0,3280.0,"0.5911, 0.5643, 0.5634, 0.5419, 0.5748, 0.4898, 0.539, 0.5041, 0.5622, 0.5992"
26,D29,float64,0.0,0.0,7.0,"0.0, 0.1667, 0.3333, 0.5, 0.6667, 0.8333, 1.0"
27,D30,float64,0.0,0.0,3671.0,"0.5, 0.25, 1.0, 0.0795, 0.0796, 0.1667, 0.0818, 0.082, 0.0702, 0.0921"
28,D31,float64,0.0,0.0,1325.0,"0.0, 0.0056, 0.0324, 0.0649, 0.0311, 0.0621, 0.0112, 0.017, 0.0367, 0.048"
29,D32,float64,0.0,0.0,1141.0,"0.0, 0.0414, 0.0207, 0.0517, 0.0621, 0.031, 0.0827, 0.1138, 0.0103, 0.0931"
30,D33,float64,0.0,0.0,387.0,"0.0, 0.1003, 0.0501, 0.0571, 0.0285, 0.0248, 0.2006, 0.0984, 0.0492, 0.039"
31,D34,float64,0.0,0.0,161.0,"0.0, 0.04, 0.0393, 0.08, 0.0785, 0.0518, 0.0917, 0.0519, 0.0311, 0.0984"
32,D35,float64,0.0,0.0,121.0,"0.0, 0.0588, 0.1176, 0.0738, 0.1765, 0.1326, 0.2353, 0.0482, 0.1476, 0.107"
33,D36,float64,0.0,0.0,72.0,"0.0, 0.1667, 0.0759, 0.1467, 0.3333, 0.1518, 0.2426, 0.0474, 0.0958, 0.1871"
34,D37,float64,0.0,0.0,73.0,"0.0, 0.25, 0.2964, 0.1323, 0.0711, 0.2201, 0.1139, 0.3263, 0.1537, 0.1423"
35,D38,float64,0.0,0.0,647.0,"0.0, 0.0562, 0.1124, 0.0843, 0.0281, 0.0199, 0.043, 0.0399, 0.0612, 0.0859"
36,D39,float64,0.0,0.0,458.0,"0.0, 0.0751, 0.1126, 0.0375, 0.1877, 0.1502, 0.2252, 0.3003, 0.2628, 0.3378"
37,D40,float64,0.0,0.0,74.0,"0.0, 0.0637, 0.1111, 0.0708, 0.2222, 0.0178, 0.0838, 0.0742, 0.0409, 0.0354"
38,D41,float64,0.0,0.0,55.0,"0.0, 0.0784, 0.0416, 0.0251, 0.0261, 0.1579, 0.0112, 0.0236, 0.0873, 0.0219"
39,D42,float64,0.0,0.0,70.0,"0.0, 0.0419, 0.1, 0.2359, 0.0837, 0.0877, 0.0435, 0.1256, 0.4718, 0.0286"
40,D43,float64,0.0,0.0,156.0,"0.0, 0.0666, 0.1333, 0.1667, 0.0279, 0.0007, 0.0789, 0.3333, 0.2333, 0.1999"
41,D44,float64,0.0,0.0,200.0,"0.0, 0.0537, 0.0173, 0.0009, 0.046, 0.1075, 0.0346, 0.071, 0.092, 0.0547"
42,D45,float64,0.0,0.0,2610.0,"0.0, 0.1665, 0.2711, 0.0801, 0.126, 0.2233, 0.0879, 0.1967, 0.4716, 0.0507"
43,D46,float64,0.0,0.0,3334.0,"0.2611, 0.3045, 0.2561, 0.2371, 0.3439, 0.2473, 0.3509, 0.3494, 0.3946, 0.4221"
44,D47,float64,0.0,0.0,3131.0,"0.298, 0.2993, 0.3058, 0.2905, 0.2748, 0.2747, 0.2987, 0.2517, 0.0679, 0.2087"
45,D48,float64,0.0,0.0,732.0,"0.0, 0.0293, 0.0512, 0.1281, 0.0095, 0.0607, 0.0251, 0.1025, 0.0215, 0.0587"
46,D49,float64,0.0,0.0,345.0,"0.0, 0.0391, 0.0254, 0.0558, 0.0783, 0.0949, 0.0491, 0.0508, 0.1115, 0.0882"
47,D50,float64,0.0,0.0,26.0,"1.0, 0.8, 0.75, 0.6667, 0.8333, 0.5, 0.8571, 0.3333, 0.875, 0.6"
48,D52,float64,0.0,0.0,208.0,"1.0, 0.0, 0.2, 0.5, 0.3333, 0.1429, 0.0476, 0.0435, 0.0909, 0.25"
49,D53,float64,0.0,0.0,202.0,"0.0, 0.0469, 0.0608, 0.0938, 0.0333, 0.0203, 0.1215, 0.0406, 0.0058, 0.1407"
50,D54,float64,0.0,0.0,461.0,"0.0, 0.0288, 0.0263, 0.0624, 0.0211, 0.0423, 0.0576, 0.0527, 0.0669, 0.179"
51,D55,float64,0.0,0.0,356.0,"0.0, 0.0639, 0.0933, 0.0294, 0.0173, 0.1277, 0.0468, 0.0449, 0.0641, 0.0107"
52,D56,float64,0.0,0.0,254.0,"0.0, 0.1521, 0.0625, 0.0758, 0.3043, 0.1101, 0.125, 0.0551, 0.072, 0.1423"
53,D57,float64,0.0,0.0,108.0,"0.0, 0.0176, 0.0351, 0.1491, 0.1667, 0.0243, 0.0527, 0.2982, 0.0702, 0.3333"
54,D58,float64,0.0,0.0,268.0,"0.0, 0.0667, 0.1251, 0.0113, 0.0697, 0.0055, 0.0336, 0.2327, 0.1163, 0.0594"
55,D59,float64,0.0,0.0,24.0,"0.0, 0.125, 0.1575, 0.25, 0.375, 0.5, 0.2771, 0.1097, 0.4021, 0.315"
56,D60,float64,0.0,0.0,90.0,"0.0, 0.0294, 0.0588, 0.0275, 0.0882, 0.1176, 0.0101, 0.0376, 0.0202, 0.055"
57,D61,float64,0.0,0.0,649.0,"0.0, 0.0709, 0.0059, 0.1418, 0.0117, 0.2127, 0.0768, 0.0112, 0.0223, 0.1477"
58,D62,float64,0.0,0.0,149.0,"0.0, 0.0718, 0.0213, 0.1437, 0.1049, 0.0331, 0.1768, 0.0427, 0.145, 0.0932"
59,D63,float64,0.0,0.0,322.0,"0.0, 0.0574, 0.0379, 0.1147, 0.0249, 0.0071, 0.0497, 0.0759, 0.0513, 0.0702"
60,D64,float64,0.0,0.0,307.0,"0.0, 0.1667, 0.0831, 0.0589, 0.0144, 0.0789, 0.3333, 0.0102, 0.0051, 0.0549"
61,D65,float64,0.0,0.0,513.0,"0.0, 0.0173, 0.0346, 0.0284, 0.0351, 0.0457, 0.1047, 0.0518, 0.0216, 0.063"
62,D66,float64,0.0,0.0,273.0,"0.0, 0.0136, 0.0271, 0.1617, 0.0232, 0.0759, 0.0506, 0.1021, 0.0313, 0.0407"
63,D67,float64,0.0,0.0,432.0,"0.0, 0.1043, 0.2085, 0.0782, 0.1303, 0.2346, 0.2607, 0.1564, 0.1825, 0.0279"
64,D68,float64,0.0,0.0,382.0,"0.0, 0.0231, 0.0157, 0.0625, 0.017, 0.0527, 0.034, 0.0856, 0.0551, 0.1101"
65,D69,float64,0.0,0.0,989.0,"0.0, 0.0293, 0.0247, 0.0663, 0.038, 0.0376, 0.0181, 0.0539, 0.0585, 0.0186"
66,D70,float64,0.0,0.0,71.0,"0.5361, 0.6236, 0.5174, 0.6464, 0.6353, 0.6669, 0.4968, 0.5534, 0.4741, 0.6569"
67,D71,float64,0.0,0.0,213.0,"0.0, 0.0745, 0.149, 0.0138, 0.0312, 0.0883, 0.0275, 0.0624, 0.1035, 0.1735"
68,D73,float64,0.0,0.0,42.0,"0.0, 0.0421, 0.1316, 0.2631, 0.0843, 0.0599, 0.1737, 0.0807, 0.102, 0.0699"
69,D74,float64,0.0,0.0,2217.0,"0.0, 0.2184, 0.1267, 0.216, 0.208, 0.0827, 0.0977, 0.2362, 0.1852, 0.2239"
70,D75,float64,0.0,0.0,517.0,"0.0, 0.1588, 0.0805, 0.0688, 0.0606, 0.0396, 0.0792, 0.3175, 0.1611, 0.1032"
71,D76,float64,0.0,0.0,475.0,"0.0, 0.0319, 0.0638, 0.0134, 0.0417, 0.0453, 0.0059, 0.0772, 0.0957, 0.0835"
72,D77,float64,0.0,0.0,7.0,"0.1667, 0.0, 0.3333, 0.5, 0.6667, 0.8333, 1.0"
73,D78,float64,0.0,0.0,46.0,"0.0068, 0.0, 0.0135, 0.0203, 0.0405, 0.0676, 0.027, 0.0473, 0.1486, 0.0811"
74,D79,float64,0.0,0.0,6.0,"0.4286, 0.2857, 0.5714, 0.1429, 0.7143, 0.8571"
75,D80,float64,0.0,0.0,1379.0,"0.0, 0.0145, 0.0155, 0.0105, 0.0143, 0.0148, 0.0168, 0.0171, 0.0195, 0.0172"
76,D81,float64,0.0,0.0,4.0,"0.0, 0.3333, 0.6667, 1.0"
77,D82,float64,0.0,0.0,5.0,"0.0, 0.25, 0.5, 0.75, 1.0"
78,D83,float64,0.0,0.0,10.0,"0.1111, 0.0, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889, 1.0"
79,D84,float64,0.0,0.0,1347.0,"0.0, 0.0125, 0.0089, 0.0177, 0.0137, 0.025, 0.0069, 0.0354, 0.0153, 0.0106"
80,D85,float64,0.0,0.0,184.0,"0.0, 0.0085, 0.0933, 0.0095, 0.005, 0.017, 0.0269, 0.007, 0.0209, 0.0467"
81,D86,float64,0.0,0.0,1293.0,"0.0, 0.0172, 0.0268, 0.0509, 0.018, 0.0149, 0.0201, 0.0287, 0.0213, 0.0035"
82,D87,float64,0.0,0.0,586.0,"0.3791, 0.4067, 0.4506, 0.3954, 0.423, 0.3515, 0.3075, 0.2799, 0.3352, 0.3515"
83,D88,float64,0.0,0.0,1446.0,"0.0535, 0.0484, 0.0462, 0.0436, 0.041, 0.0523, 0.0384, 0.0543, 0.0527, 0.0694"
84,D89,float64,0.0,0.0,3658.0,"0.6596, 0.6182, 0.6491, 0.5395, 0.5591, 0.5848, 0.538, 0.5943, 0.44, 0.6128"
85,D90,float64,0.0,0.0,3356.0,"0.3662, 0.3614, 0.3599, 0.356, 0.3543, 0.3552, 0.3651, 0.3568, 0.3604, 0.3649"
86,D91,float64,0.0,0.0,3372.0,"0.4754, 0.4735, 0.4741, 0.4744, 0.469, 0.4739, 0.4678, 0.4183, 0.4501, 0.4681"
87,D92,float64,0.0,0.0,13.0,"0.0, 0.0526, 0.1053, 0.1579, 0.2105, 0.3158, 0.2632, 0.5263, 0.3684, 0.6316"
88,D93,float64,0.0,0.0,15.0,"0.0, 0.0476, 0.0952, 0.1429, 0.1905, 0.2381, 0.3333, 0.2857, 0.4286, 0.8095"
89,D95,float64,0.0,0.0,1333.0,"0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0002, 0.0"
90,D96,float64,0.0,0.0,25.0,"0.1, 0.0667, 0.1333, 0.0333, 0.1667, 0.2, 0.0, 0.2333, 0.2667, 0.3"
91,D97,float64,0.0,0.0,15.0,"0.0, 0.0263, 0.0526, 0.1053, 0.0789, 0.1579, 0.1842, 0.1316, 0.2105, 0.4211"
92,D98,float64,0.0,0.0,5.0,"0.0, 0.2, 0.4, 0.8, 0.6"
93,D99,float64,0.0,0.0,2455.0,"0.2877, 0.2758, 0.3491, 0.296, 0.3852, 0.189, 0.4064, 0.4319, 0.3608, 0.3577"
94,D100,float64,0.0,0.0,444.0,"0.5242, 0.4803, 0.6655, 0.6436, 0.5432, 0.5769, 0.5033, 0.6757, 0.6318, 0.592"
95,D101,float64,0.0,0.0,447.0,"0.0, 0.0526, 0.0465, 0.25, 0.0192, 0.1402, 0.0375, 0.0416, 0.075, 0.1204"
96,D102,float64,0.0,0.0,2900.0,"0.0724, 0.0683, 0.0736, 0.0934, 0.0773, 0.303, 0.0972, 0.113, 0.1675, 0.0733"
97,D103,float64,0.0,0.0,2980.0,"0.1768, 0.3792, 0.2169, 0.365, 0.1971, 0.2893, 0.2552, 0.1015, 0.2289, 0.1684"
98,D104,float64,0.0,0.0,3613.0,"0.0, 0.3202, 0.4278, 0.4031, 0.3539, 0.4012, 0.2366, 0.3915, 0.4886, 0.376"
99,D105,float64,0.0,0.0,3640.0,"0.0517, 0.0532, 0.0393, 0.0519, 0.0505, 0.0451, 0.0317, 0.0469, 0.0446, 0.4984"
100,D106,float64,0.0,0.0,3638.0,"0.0, 0.3674, 0.0986, 0.3637, 0.1809, 0.4196, 0.2238, 0.183, 0.1677, 0.1783"
101,D107,float64,0.0,0.0,3595.0,"0.7447, 0.7519, 0.8397, 0.8207, 0.7363, 0.7163, 0.7871, 0.7381, 0.7275, 0.6691"
102,D108,float64,0.0,0.0,7.0,"0.0, 0.1667, 0.3333, 0.5, 0.6667, 0.8333, 1.0"
103,D109,float64,0.0,0.0,6.0,"0.0, 0.1667, 0.3333, 0.5, 0.6667, 0.8333"
104,D110,float64,0.0,0.0,7.0,"0.0, 0.1667, 0.3333, 0.5, 0.6667, 0.8333, 1.0"
105,D111,float64,0.0,0.0,7.0,"0.0, 0.1667, 0.3333, 0.5, 0.6667, 1.0, 0.8333"
106,D112,float64,0.0,0.0,5.0,"0.0, 0.2, 0.4, 0.6, 0.8"
107,D113,float64,0.0,0.0,6.0,"0.0, 0.2, 0.4, 0.6, 0.8, 1.0"
108,D114,float64,0.0,0.0,6.0,"0.0, 0.2, 0.4, 0.6, 0.8, 1.0"
109,D115,float64,0.0,0.0,6.0,"0.0, 0.1, 0.2, 0.3, 0.4, 0.9"
110,D116,float64,0.0,0.0,5.0,"0.0, 0.25, 0.5, 0.75, 1.0"
111,D117,float64,0.0,0.0,746.0,"0.0, 0.7379, 0.5724, 0.7273, 0.7297, 0.1376, 0.7144, 0.7018, 0.7138, 0.827"
112,D118,float64,0.0,0.0,416.0,"0.0, 0.0853, 0.0862, 0.0856, 0.0851, 0.0737, 0.0834, 0.0852, 0.0842, 0.3294"
113,D119,float64,0.0,0.0,542.0,"0.0, 0.0963, 0.0871, 0.2468, 0.0577, 0.1575, 0.8055, 0.5148, 0.1694, 0.7249"
114,D120,float64,0.0,0.0,274.0,"0.0, 0.6142, 0.6684, 0.7695, 0.5619, 0.219, 0.4777, 0.1535, 0.108, 0.6173"
115,D121,float64,0.0,0.0,304.0,"0.0, 0.7456, 0.7115, 0.5632, 0.7539, 0.7483, 0.4833, 0.644, 0.4499, 0.2876"
116,D122,float64,0.0,0.0,170.0,"0.0, 0.3546, 0.8265, 0.171, 0.6122, 0.2717, 0.438, 0.2557, 0.5155, 0.6876"
117,D123,float64,0.0,0.0,199.0,"0.0, 0.5052, 0.3402, 0.7706, 0.3392, 0.355, 0.711, 0.2542, 0.1581, 0.0907"
118,D124,float64,0.0,0.0,128.0,"0.0, 0.3411, 0.5586, 0.3581, 0.5982, 0.4205, 0.1589, 0.2904, 0.8031, 0.2158"
119,D125,float64,0.0,0.0,80.0,"0.0, 0.3096, 0.3323, 0.3481, 0.7181, 0.7864, 0.425, 0.6069, 0.8067, 0.4184"
120,D126,float64,0.0,0.0,33.0,"0.2105, 0.1579, 0.1842, 0.1053, 0.2368, 0.1316, 0.2632, 0.2895, 0.0789, 0.0526"
121,D127,float64,0.0,0.0,7.0,"0.0, 0.1667, 0.3333, 0.5, 0.6667, 1.0, 0.8333"
122,D128,float64,0.0,0.0,20.0,"0.0667, 0.0, 0.0333, 0.1, 0.1333, 0.1667, 0.2, 0.2667, 0.2333, 0.3"
123,D129,float64,0.0,0.0,14.0,"0.0, 0.1579, 0.1053, 0.0526, 0.2105, 0.3158, 0.2632, 0.6316, 0.5263, 0.4737"
124,D130,float64,0.0,0.0,26.0,"0.1111, 0.0556, 0.0833, 0.0, 0.1389, 0.0278, 0.1667, 0.1944, 0.2222, 0.25"
125,D131,float64,0.0,0.0,32.0,"0.1905, 0.0952, 0.1429, 0.2381, 0.0, 0.0476, 0.119, 0.0714, 0.2857, 0.2143"
126,D132,float64,0.0,0.0,10.0,"0.0, 0.0833, 0.1667, 0.25, 0.3333, 0.4167, 0.5, 0.5833, 0.6667, 0.8333"
127,D133,float64,0.0,0.0,11.0,"0.0, 0.0909, 0.1818, 0.3636, 0.2727, 0.4545, 0.5455, 0.7273, 0.8182, 0.6364"
128,D134,float64,0.0,0.0,7.0,"0.0, 0.0714, 0.1429, 0.2143, 0.8571, 0.5714, 0.4286"
129,D135,float64,0.0,0.0,13.0,"0.0, 0.0769, 0.1538, 0.2308, 0.3077, 0.4615, 0.3846, 0.9231, 0.5385, 0.6923"
130,D136,float64,0.0,0.0,8.0,"0.0, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778"
131,D137,float64,0.0,0.0,14.0,"0.0, 0.0625, 0.125, 0.1875, 0.25, 0.3125, 0.375, 0.5, 0.4375, 0.625"
132,D138,float64,0.0,0.0,10.0,"0.0, 0.0556, 0.1111, 0.1667, 0.2222, 0.8333, 1.0, 0.2778, 0.3889, 0.7778"
133,D139,float64,0.0,0.0,27.0,"0.0952, 0.119, 0.0476, 0.0714, 0.0, 0.1429, 0.0238, 0.1667, 0.1905, 0.2381"
134,D140,float64,0.0,0.0,11.0,"0.0, 0.1, 0.2, 0.3, 0.4, 0.6, 0.5, 0.7, 0.8, 0.9"
135,D141,float64,0.0,0.0,11.0,"0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.4, 0.3, 0.35, 1.0"
136,D142,float64,0.0,0.0,12.0,"0.125, 0.0625, 0.0, 0.1875, 0.25, 0.3125, 0.375, 0.4375, 0.5, 0.5625"
137,D143,float64,0.0,0.0,21.0,"0.0, 0.0345, 0.069, 0.1034, 0.1379, 0.1724, 0.2069, 0.2414, 0.3103, 0.2759"
138,D144,float64,0.0,0.0,11.0,"0.0, 0.0303, 0.0606, 0.0909, 0.1212, 0.1515, 0.8788, 0.4848, 0.3333, 0.3636"
139,D145,float64,0.0,0.0,38.0,"0.0, 0.1538, 0.1154, 0.0385, 0.0769, 0.1731, 0.1346, 0.0962, 0.2308, 0.1923"
140,D146,float64,0.0,0.0,36.0,"0.0, 0.0476, 0.0238, 0.0952, 0.1429, 0.0714, 0.1667, 0.119, 0.1905, 0.2381"
141,D147,float64,0.0,0.0,11.0,"0.0, 0.1, 0.2, 0.4, 0.3, 0.6, 0.5, 0.7, 0.8, 0.9"
142,D148,float64,0.0,0.0,8.0,"0.0, 0.0208, 0.0417, 0.0833, 0.0625, 0.1042, 0.125, 0.8333"
143,D149,float64,0.0,0.0,20.0,"0.0, 0.0294, 0.0588, 0.0882, 0.1176, 0.1765, 0.1471, 0.2353, 0.2059, 0.2647"
144,D150,float64,0.0,0.0,18.0,"0.0, 0.1176, 0.0588, 0.2353, 0.1765, 0.3529, 0.2941, 0.4706, 0.4118, 0.5294"
145,D151,float64,0.0,0.0,27.0,"0.0, 0.0571, 0.0286, 0.0857, 0.1143, 0.1429, 0.1714, 0.2, 0.2286, 0.2571"
146,D152,float64,0.0,0.0,40.0,"0.0, 0.0303, 0.0152, 0.1212, 0.0606, 0.0909, 0.1818, 0.1515, 0.2121, 0.0455"
147,D153,float64,0.0,0.0,13.0,"0.0, 0.0667, 0.1333, 0.2, 0.2667, 0.3333, 0.4, 0.4667, 0.6, 0.5333"
148,D154,float64,0.0,0.0,17.0,"0.0, 0.0385, 0.0192, 0.0577, 0.0769, 0.0962, 0.1154, 0.1538, 0.1346, 0.1731"
149,D155,float64,0.0,0.0,14.0,"0.0, 0.0588, 0.1176, 0.1765, 0.2353, 0.2941, 0.3529, 0.4118, 0.4706, 0.5294"
150,D156,float64,0.0,0.0,6.0,"0.0, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143"
151,D157,float64,0.0,0.0,15.0,"0.0, 0.0556, 0.1111, 0.1667, 0.2222, 0.5556, 0.3333, 0.2778, 0.5, 0.6667"
152,D158,float64,0.0,0.0,36.0,"0.0, 0.0222, 0.0444, 0.0889, 0.0667, 0.1333, 0.1111, 0.1778, 0.1556, 0.2222"
153,D159,float64,0.0,0.0,13.0,"0.0, 0.0323, 0.0645, 0.0968, 0.129, 0.1935, 0.1613, 0.2581, 0.2258, 0.3226"
154,D160,float64,0.0,0.0,21.0,"0.0, 0.0357, 0.0714, 0.1429, 0.1071, 0.1786, 0.2143, 0.25, 0.2857, 0.3214"
155,D161,float64,0.0,0.0,12.0,"0.0, 0.0625, 0.125, 0.1875, 0.25, 0.3125, 0.375, 0.4375, 0.5, 0.625"
156,D162,float64,0.0,0.0,17.0,"0.0, 0.0833, 0.125, 0.1667, 0.0417, 0.2083, 0.25, 0.3333, 0.2917, 0.375"
157,D163,float64,0.0,0.0,9.0,"0.0, 0.1, 0.2, 0.3, 0.4, 0.6, 0.9, 0.5, 0.7"
158,D164,float64,0.0,0.0,7.0,"0.0, 0.125, 0.25, 0.5, 0.375, 0.75, 1.0"
159,D165,float64,0.0,0.0,7.0,"0.0, 0.1667, 0.3333, 0.5, 0.6667, 0.8333, 1.0"
160,D166,float64,0.0,0.0,6.0,"0.0, 0.1667, 0.3333, 0.5, 0.6667, 1.0"
161,D167,float64,0.0,0.0,11.0,"0.0, 0.0769, 0.1538, 0.2308, 0.3077, 0.3846, 0.4615, 0.6154, 0.6923, 1.0"
162,D168,float64,0.0,0.0,11.0,"0.0, 0.0714, 0.1429, 0.2143, 0.2857, 0.3571, 0.4286, 0.5, 0.5714, 0.6429"
163,D169,float64,0.0,0.0,3.0,"0.0, 0.5, 1.0"
164,D171,float64,0.0,0.0,21.0,"0.0, 0.2601, 0.2459, 0.2087, 0.2032, 0.241, 1.0, 0.2369, 0.4872, 0.2322"
165,D172,float64,0.0,0.0,246.0,"0.0, 0.0945, 0.2535, 0.0871, 0.0901, 0.095, 0.1347, 0.0789, 0.1092, 0.0989"
166,D173,float64,0.0,0.0,1435.0,"0.0, 0.0658, 0.0653, 0.0656, 0.076, 0.0557, 0.0566, 0.0644, 0.0642, 0.053"
167,D174,float64,0.0,0.0,134.0,"0.0, 0.3109, 0.3367, 0.3382, 0.3639, 0.2445, 0.3191, 0.6283, 0.3016, 0.6304"
168,D175,float64,0.0,0.0,1742.0,"0.1034, 0.0993, 0.0951, 0.0995, 0.0986, 0.0972, 0.0992, 0.123, 0.098, 0.1216"
169,D176,float64,0.0,0.0,11.0,"0.0, 0.7754, 0.9667, 0.7421, 0.9754, 1.0, 0.9348, 0.8285, 0.9812, 0.9711"
170,D177,float64,0.0,0.0,2658.0,"0.0005, 0.0692, 0.0796, 0.0769, 0.0686, 0.0309, 0.0329, 0.1881, 0.0842, 0.6372"
171,D178,float64,0.0,0.0,1133.0,"0.831, 0.7915, 0.8454, 0.8376, 0.8414, 0.8349, 0.8303, 0.8356, 0.8297, 0.8561"
172,D179,float64,0.0,0.0,15.0,"0.0, 0.3885, 0.6917, 0.6855, 0.8882, 1.0, 0.9291, 0.5011, 0.7119, 0.8816"
173,D180,float64,0.0,0.0,1518.0,"0.4522, 0.4397, 0.44, 0.4467, 0.4581, 0.4888, 0.4368, 0.4269, 0.4348, 0.4044"
174,D181,float64,0.0,0.0,2622.0,"0.6589, 0.7063, 0.6789, 0.6935, 0.677, 0.6903, 0.798, 0.6795, 0.6682, 0.6843"
175,D182,float64,0.0,0.0,991.0,"0.0943, 0.1958, 0.1847, 0.218, 0.1317, 0.1793, 0.1973, 0.2054, 0.1825, 0.4264"
176,D183,float64,0.0,0.0,454.0,"0.9767, 0.9835, 0.957, 0.9696, 0.9179, 0.9337, 0.9664, 0.9092, 0.9221, 0.9751"
177,D184,float64,0.0,0.0,20.0,"0.0, 0.4842, 0.5249, 0.439, 0.4326, 0.9173, 0.4009, 0.383, 0.4304, 0.4446"
178,D185,float64,0.0,0.0,698.0,"0.0, 0.1728, 0.1693, 0.2139, 0.1568, 0.1235, 0.1613, 0.1896, 0.1735, 0.1822"
179,D186,float64,0.0,0.0,190.0,"0.0628, 0.4559, 0.4756, 0.4042, 0.3174, 0.3267, 0.4556, 0.4367, 0.3469, 0.3333"
180,D187,float64,0.0,0.0,571.0,"0.837, 0.7544, 0.7438, 0.7555, 0.7587, 0.7583, 0.7495, 0.7426, 0.7577, 0.7563"
181,D188,float64,0.0,0.0,19.0,"0.0, 0.4258, 0.3964, 0.3981, 0.4397, 0.4792, 0.4443, 0.9498, 0.4722, 0.93"
182,D189,float64,0.0,0.0,124.0,"0.3095, 0.5284, 0.5032, 0.5099, 0.5882, 0.5737, 0.4945, 0.5354, 0.4009, 0.4164"
183,D190,float64,0.0,0.0,60.0,"0.6366, 0.9079, 0.8881, 0.4642, 0.9096, 0.8652, 0.8664, 0.9079, 0.9639, 0.8942"
184,D191,float64,0.0,0.0,429.0,"0.0, 0.0724, 0.0696, 0.0714, 0.0717, 0.0744, 0.0686, 0.0688, 0.0695, 0.0698"
185,D192,float64,0.0,0.0,134.0,"0.0, 0.0941, 0.0946, 0.0927, 0.0921, 0.0862, 0.0893, 0.0934, 0.093, 0.0924"
186,D193,float64,0.0,0.0,15.0,"0.043, 0.2314, 0.2443, 0.5428, 0.197, 0.2429, 0.777, 0.0, 0.2509, 0.2474"
187,D194,float64,0.0,0.0,1116.0,"0.0, 0.8004, 0.7973, 0.8245, 0.8073, 0.8112, 0.8114, 0.8151, 0.8404, 0.7476"
188,D195,float64,0.0,0.0,633.0,"0.0, 0.6001, 0.581, 0.757, 0.5769, 0.801, 0.6472, 0.8803, 0.7062, 0.7389"
189,D196,float64,0.0,0.0,1956.0,"0.0, 0.6306, 0.6117, 0.604, 0.6044, 0.6237, 0.6025, 0.6451, 0.6076, 0.616"
190,D197,float64,0.0,0.0,249.0,"0.0, 0.4126, 0.3348, 0.4528, 0.5622, 0.5179, 0.3635, 0.3034, 0.4307, 0.3802"
191,D198,float64,0.0,0.0,1642.0,"0.0, 0.3476, 0.309, 0.4119, 0.414, 0.3286, 0.3175, 0.4281, 0.2897, 0.3372"
192,D199,float64,0.0,0.0,1706.0,"0.0, 0.4436, 0.3918, 0.3965, 0.4567, 0.6172, 0.5362, 0.5363, 0.5874, 0.3222"
193,D200,float64,0.0,0.0,2183.0,"0.0, 0.604, 0.6306, 0.6117, 0.6027, 0.6014, 0.6044, 0.6076, 0.6237, 0.616"
194,D201,float64,0.0,0.0,1804.0,"0.2576, 0.702, 0.7675, 0.8282, 0.8584, 0.8455, 0.8837, 0.884, 0.8433, 0.841"
195,D202,float64,0.0,0.0,1712.0,"0.5932, 0.8251, 0.7595, 0.8177, 0.7753, 0.6178, 0.9443, 0.8321, 0.862, 0.6104"
196,D203,float64,0.0,0.0,650.0,"0.0836, 0.2971, 0.6366, 0.6397, 0.3343, 0.6221, 0.5803, 0.6815, 0.6083, 0.3666"

In [6]:
# Numeric Feature Statistics
numeric_stats

        count      mean       std       min       max
D1     3751.0  0.076948  0.079989  0.000000  1.000000
D2     3751.0  0.592436  0.105860  0.282128  0.964381
D3     3751.0  0.068142  0.078414  0.000000  0.950000
D4     3751.0  0.038990  0.115885  0.000000  1.000000
D5     3751.0  0.212112  0.102592  0.002630  1.000000
D6     3751.0  0.686653  0.078702  0.137873  0.994735
D7     3751.0  0.274713  0.090017  0.006130  0.790831
D8     3751.0  0.455133  0.162731  0.000000  0.989870
D9     3751.0  0.749517  0.071702  0.275590  1.000000
D10    3751.0  0.270411  0.096128  0.003040  1.000000
D11    3751.0  0.171688  0.177193  0.000000  1.000000
D12    3751.0  0.079529  0.086347  0.000000  1.000000
D13    3751.0  0.017066  0.058205  0.000000  1.000000
D14    3751.0  0.126521  0.066008  0.000000  1.000000
D15    3751.0  0.516515  0.088258  0.002970  0.725665
D16    3751.0  0.278736  0.116261  0.000000  0.980615
D17    3751.0  0.580890  0.107543  0.155826  1.000000
D18    3751.0  0.196150  0.087323  0.000000  1.000000
D19    3751.0  0.140164  0.084340  0.001700  0.964094
D20    3751.0  0.082016  0.078940  0.000000  0.895526
D21    3751.0  0.012049  0.015626  0.000000  0.483241
D22    3751.0  0.045368  0.060156  0.000000  0.896552
D23    3751.0  0.966409  0.180198  0.000000  1.000000
D24    3751.0  0.051853  0.137879  0.000000  1.000000
D25    3751.0  0.493408  0.075702  0.000000  0.966400
D26    3751.0  0.742171  0.112946  0.071600  1.000000
D27    3751.0  0.520661  0.499640  0.000000  1.000000
D28    3751.0  0.890696  0.312062  0.000000  1.000000
D29    3751.0  0.069937  0.145437  0.000000  1.000000
D30    3751.0  0.282709  0.135139  0.030000  1.000000
D31    3751.0  0.109775  0.105946  0.000000  1.000000
D32    3751.0  0.097083  0.068714  0.000000  0.817857
D33    3751.0  0.058377  0.086331  0.000000  0.802001
D34    3751.0  0.025529  0.048316  0.000000  0.807171
D35    3751.0  0.048006  0.078512  0.000000  0.898321
D36    3751.0  0.059954  0.102083  0.000000  1.000000
D37    3751.0  0.033708  0.100521  0.000000  1.000000
D38    3751.0  0.087340  0.075382  0.000000  1.000000
D39    3751.0  0.154882  0.139819  0.000000  0.876857
D40    3751.0  0.017699  0.055137  0.000000  1.000000
D41    3751.0  0.008044  0.033226  0.000000  1.000000
D42    3751.0  0.022567  0.072454  0.000000  1.000000
D43    3751.0  0.074959  0.097964  0.000000  1.000000
D44    3751.0  0.052783  0.077344  0.000000  0.871676
D45    3751.0  0.176666  0.147722  0.000000  1.000000
D46    3751.0  0.481821  0.141755  0.000000  1.000000
D47    3751.0  0.213649  0.100871  0.000000  0.852198
D48    3751.0  0.098021  0.095685  0.000000  0.957123
D49    3751.0  0.059523  0.070123  0.000000  0.775407
D50    3751.0  0.839723  0.184144  0.000000  1.000000
D51    3751.0  0.232205  0.422295  0.000000  1.000000
D52    3751.0  0.706062  0.421552  0.000000  1.000000
D53    3751.0  0.043351  0.062855  0.000000  0.878480
D54    3751.0  0.054967  0.074778  0.000000  0.802514
D55    3751.0  0.048949  0.076902  0.000000  0.945099
D56    3751.0  0.081752  0.107076  0.000000  0.937500
D57    3751.0  0.048108  0.085539  0.000000  0.964878
D58    3751.0  0.051673  0.095390  0.000000  1.000000
D59    3751.0  0.024842  0.082714  0.000000  1.000000
D60    3751.0  0.027874  0.069637  0.000000  0.794118
D61    3751.0  0.112468  0.117376  0.000000  1.000000
D62    3751.0  0.070439  0.087475  0.000000  1.000000
D63    3751.0  0.051736  0.073699  0.000000  0.745698
D64    3751.0  0.064201  0.097357  0.000000  1.000000
D65    3751.0  0.053911  0.069794  0.000000  0.833864
D66    3751.0  0.047238  0.069131  0.000000  0.676523
D67    3751.0  0.153600  0.107173  0.000000  0.752715
D68    3751.0  0.051127  0.074415  0.000000  0.937500
D69    3751.0  0.081744  0.068246  0.000000  0.948342
D70    3751.0  0.592281  0.124732  0.000000  1.000000
D71    3751.0  0.074801  0.086101  0.000000  1.000000
D72    3751.0  0.000267  0.016328  0.000000  1.000000
D73    3751.0  0.032370  0.068035  0.000000  0.736891
D74    3751.0  0.182529  0.090979  0.000000  0.845545
D75    3751.0  0.106928  0.119832  0.000000  1.000000
D76    3751.0  0.070796  0.073351  0.000000  0.929903
D77    3751.0  0.099662  0.106519  0.000000  1.000000
D78    3751.0  0.031041  0.050004  0.000000  1.000000
D79    3751.0  0.392581  0.117362  0.142857  0.857143
D80    3751.0  0.032548  0.069162  0.000000  1.000000
D81    3751.0  0.023549  0.091777  0.000000  1.000000
D82    3751.0  0.079179  0.143744  0.000000  1.000000
D83    3751.0  0.192541  0.164408  0.000000  1.000000
D84    3751.0  0.067146  0.064985  0.000000  1.000000
D85    3751.0  0.009512  0.032752  0.000000  0.534523
D86    3751.0  0.051453  0.055727  0.000000  0.846353
D87    3751.0  0.347842  0.101862  0.000000  1.000000
D88    3751.0  0.098893  0.080749  0.000000  1.000000
D89    3751.0  0.590861  0.059581  0.035700  1.000000
D90    3751.0  0.346854  0.045107  0.008650  0.870249
D91    3751.0  0.427092  0.046480  0.000000  0.744617
D92    3751.0  0.065461  0.070718  0.000000  0.842105
D93    3751.0  0.048889  0.058168  0.000000  0.809524
D94    3751.0  0.433218  0.495586  0.000000  1.000000
D95    3751.0  0.003298  0.023202  0.000000  0.630370
D96    3751.0  0.120131  0.085224  0.000000  1.000000
D97    3751.0  0.017301  0.039662  0.000000  1.000000
D98    3751.0  0.018182  0.077974  0.000000  0.800000
D99    3751.0  0.519965  0.117189  0.000000  0.960662
D100   3751.0  0.546393  0.128193  0.000000  1.000000
D101   3751.0  0.081825  0.118591  0.000000  1.000000
D102   3751.0  0.171100  0.107520  0.002350  0.823154
D103   3751.0  0.264248  0.121219  0.000000  1.000000
D104   3751.0  0.574999  0.206242  0.000000  1.000000
D105   3751.0  0.513321  0.205054  0.003810  0.972938
D106   3751.0  0.253627  0.105059  0.000000  1.000000
D107   3751.0  0.647139  0.095194  0.000000  0.915614
D108   3751.0  0.045943  0.107116  0.000000  1.000000
D109   3751.0  0.026971  0.083833  0.000000  0.833333
D110   3751.0  0.033369  0.091354  0.000000  1.000000
D111   3751.0  0.018306  0.074374  0.000000  1.000000
D112   3751.0  0.024314  0.091130  0.000000  0.800000
D113   3751.0  0.013117  0.067714  0.000000  1.000000
D114   3751.0  0.016849  0.080225  0.000000  1.000000
D115   3751.0  0.005678  0.037555  0.000000  0.900000
D116   3751.0  0.007665  0.056785  0.000000  1.000000
D117   3751.0  0.127947  0.265760  0.000000  1.000000
D118   3751.0  0.042680  0.137690  0.000000  0.922243
D119   3751.0  0.062238  0.175403  0.000000  1.000000
D120   3751.0  0.036680  0.144374  0.000000  1.000000
D121   3751.0  0.042475  0.157308  0.000000  1.000000
D122   3751.0  0.021721  0.110334  0.000000  0.984054
D123   3751.0  0.024392  0.116677  0.000000  0.999932
D124   3751.0  0.015715  0.094329  0.000000  0.999939
D125   3751.0  0.010407  0.078603  0.000000  0.999924
D126   3751.0  0.201738  0.116799  0.000000  0.921053
D127   3751.0  0.107482  0.149295  0.000000  1.000000
D128   3751.0  0.083980  0.073924  0.000000  1.000000
D129   3751.0  0.023053  0.068258  0.000000  1.000000
D130   3751.0  0.109212  0.086901  0.000000  0.861111
D131   3751.0  0.157042  0.103952  0.000000  1.000000
D132   3751.0  0.019038  0.068571  0.000000  0.833333
D133   3751.0  0.024817  0.081399  0.000000  0.909091
D134   3751.0  0.002513  0.023014  0.000000  0.857143
D135   3751.0  0.064551  0.100648  0.000000  1.000000
D136   3751.0  0.139815  0.130421  0.000000  0.777778
D137   3751.0  0.083994  0.090429  0.000000  0.937500
D138   3751.0  0.004385  0.031750  0.000000  1.000000
D139   3751.0  0.111330  0.086409  0.000000  0.714286
D140   3751.0  0.022234  0.086419  0.000000  1.000000
D141   3751.0  0.008491  0.038720  0.000000  1.000000
D142   3751.0  0.119701  0.100442  0.000000  0.687500
D143   3751.0  0.055830  0.073149  0.000000  1.000000
D144   3751.0  0.003522  0.023185  0.000000  0.878788
D145   3751.0  0.133404  0.108606  0.000000  0.807692
D146   3751.0  0.149032  0.157936  0.000000  0.952381
D147   3751.0  0.023194  0.092235  0.000000  1.000000
D148   3751.0  0.000983  0.015094  0.000000  0.833333
D149   3751.0  0.026482  0.056610  0.000000  1.000000
D150   3751.0  0.137074  0.126908  0.000000  1.000000
D151   3751.0  0.062285  0.081372  0.000000  1.000000
D152   3751.0  0.129684  0.107103  0.000000  0.651515
D153   3751.0  0.018414  0.079091  0.000000  1.000000
D154   3751.0  0.005917  0.029007  0.000000  1.000000
D155   3751.0  0.035907  0.068166  0.000000  0.764706
D156   3751.0  0.028678  0.073839  0.000000  0.714286
D157   3751.0  0.020724  0.060188  0.000000  1.000000
D158   3751.0  0.051727  0.091248  0.000000  1.000000
D159   3751.0  0.031529  0.040743  0.000000  0.451613
D160   3751.0  0.025770  0.064129  0.000000  1.000000
D161   3751.0  0.047504  0.075388  0.000000  0.750000
D162   3751.0  0.103347  0.099093  0.000000  0.750000
D163   3751.0  0.019541  0.064741  0.000000  0.900000
D164   3751.0  0.020861  0.068115  0.000000  1.000000
D165   3751.0  0.035857  0.100862  0.000000  1.000000
D166   3751.0  0.029192  0.076976  0.000000  1.000000
D167   3751.0  0.076096  0.088034  0.000000  1.000000
D168   3751.0  0.036290  0.072254  0.000000  0.714286
D169   3751.0  0.024793  0.115694  0.000000  1.000000
D170   3751.0  0.016529  0.127515  0.000000  1.000000
D171   3751.0  0.001598  0.025608  0.000000  1.000000
D172   3751.0  0.010192  0.046467  0.000000  1.000000
D173   3751.0  0.068035  0.094339  0.000000  0.885242
D174   3751.0  0.013301  0.072886  0.000000  0.959824
D175   3751.0  0.126170  0.057293  0.018900  0.821575
D176   3751.0  0.002408  0.046805  0.000000  1.000000
D177   3751.0  0.208469  0.191975  0.000514  1.000000
D178   3751.0  0.823950  0.044878  0.001150  1.000000
D179   3751.0  0.002744  0.046370  0.000000  1.000000
D180   3751.0  0.444874  0.034478  0.094500  0.838127
D181   3751.0  0.692926  0.054086  0.354010  1.000000
D182   3751.0  0.145412  0.110448  0.000000  1.000000
D183   3751.0  0.974167  0.021605  0.000000  1.000000
D184   3751.0  0.002742  0.041047  0.000000  0.943388
D185   3751.0  0.046267  0.110011  0.000000  1.000000
D186   3751.0  0.081391  0.084714  0.062800  1.000000
D187   3751.0  0.818474  0.054831  0.000000  1.000000
D188   3751.0  0.002602  0.039847  0.000000  0.955796
D189   3751.0  0.316691  0.045417  0.190762  1.000000
D190   3751.0  0.639801  0.037296  0.000000  1.000000
D191   3751.0  0.020788  0.064370  0.000000  0.820906
D192   3751.0  0.006093  0.041046  0.000000  1.000000
D193   3751.0  0.043995  0.020317  0.000000  0.777032
D194   3751.0  0.281561  0.386496  0.000000  1.000000
D195   3751.0  0.133478  0.286470  0.000000  0.998499
D196   3751.0  0.478900  0.295417  0.000000  1.000000
D197   3751.0  0.028192  0.109365  0.000000  0.985417
D198   3751.0  0.185733  0.198238  0.000000  0.852456
D199   3751.0  0.265955  0.265280  0.000000  1.000000
D200   3751.0  0.525619  0.259600  0.000000  1.000000
D201   3751.0  0.537153  0.270686  0.257565  1.000000
D202   3751.0  0.645608  0.107997  0.000000  1.000000
D203   3751.0  0.175771  0.209890  0.000000  0.976333
D204   3751.0  0.490191  0.318866  0.003990  1.000000
D205   3751.0  0.784096  0.074165  0.032400  1.000000
D206   3751.0  0.016434  0.103956  0.000000  0.979965
D207   3751.0  0.679580  0.070677  0.000000  0.974644
D208   3751.0  0.643615  0.138822  0.141124  0.995063
D209   3751.0  0.402150  0.195302  0.000000  1.000000
D210   3751.0  0.913854  0.061883  0.000000  1.000000
D211   3751.0  0.130840  0.304374  0.000000  1.000000
D212   3751.0  0.137323  0.288360  0.000000  0.993831
D213   3751.0  0.024748  0.142335  0.000000  0.981663
D214   3751.0  0.050008  0.142436  0.000000  0.642111
D215   3751.0  0.114172  0.282852  0.000000  1.000000
D216   3751.0  0.103726  0.141770  0.000000  1.000000
D217   3751.0  0.500381  0.095056  0.000000  1.000000
D218   3751.0  0.426647  0.364878  0.000000  0.994036
D219   3751.0  0.197528  0.297888  0.000000  0.825550
D220   3751.0  0.021878  0.127619  0.000000  1.000000
D221   3751.0  0.051773  0.099901  0.000000  1.000000
D222   3751.0  0.966882  0.157473  0.000000  1.000000
D223   3751.0  0.114313  0.275182  0.000000  0.969680
D224   3751.0  0.032418  0.163415  0.000000  0.991929
D225   3751.0  0.012663  0.093307  0.000000  1.000000
D226   3751.0  0.024393  0.082491  0.000000  1.000000
D227   3751.0  0.014929  0.051027  0.000000  1.000000
D228   3751.0  0.021150  0.069153  0.000000  0.666667
D229   3751.0  0.024327  0.087510  0.000000  1.000000
D230   3751.0  0.003866  0.048150  0.000000  1.000000
D231   3751.0  0.006132  0.056235  0.000000  1.000000
D232   3751.0  0.004957  0.053638  0.000000  0.663127
D233   3751.0  0.016935  0.040858  0.011000  1.000000
D234   3751.0  0.000949  0.027087  0.000000  1.000000
D235   3751.0  0.002097  0.036929  0.000000  1.000000
D236   3751.0  0.005341  0.052682  0.000000  1.000000
D237   3751.0  0.018646  0.095835  0.000000  1.000000
D238   3751.0  0.001046  0.032034  0.000000  1.000000
D239   3751.0  0.003611  0.043581  0.000000  0.976768
D240   3751.0  0.000787  0.025774  0.000000  1.000000
D241   3751.0  0.002350  0.033515  0.000000  1.000000
D242   3751.0  0.000501  0.021729  0.000000  1.000000
D243   3751.0  0.002638  0.038915  0.000000  0.964268
D244   3751.0  0.001598  0.024151  0.000000  1.000000
D245   3751.0  0.002920  0.049079  0.000000  1.000000
D246   3751.0  0.004915  0.041215  0.000000  1.000000
D247   3751.0  0.002543  0.040078  0.000000  1.000000
D248   3751.0  0.009687  0.068372  0.000000  0.853855
D249   3751.0  0.014096  0.055321  0.000000  1.000000
D250   3751.0  0.006482  0.054872  0.000000  1.000000
D251   3751.0  0.003732  0.030866  0.000000  0.500000
D252   3751.0  0.005199  0.056918  0.000000  1.000000
D253   3751.0  0.003732  0.043386  0.000000  0.666667
D254   3751.0  0.003332  0.036818  0.000000  0.750000
D255   3751.0  0.002999  0.038397  0.000000  1.000000
D256   3751.0  0.002466  0.033325  0.000000  1.000000
D257   3751.0  0.002133  0.034187  0.000000  0.800000
D258   3751.0  0.006532  0.044617  0.000000  1.000000
D259   3751.0  0.004577  0.031992  0.000000  0.666667
D260   3751.0  0.006397  0.046544  0.000000  1.000000
D261   3751.0  0.004399  0.033189  0.000000  1.000000
D262   3751.0  0.003332  0.029156  0.000000  1.000000
D263   3751.0  0.001883  0.014563  0.000000  0.375000
D264   3751.0  0.002166  0.025971  0.000000  1.000000
D265   3751.0  0.004151  0.044129  0.000000  1.000000
D266   3751.0  0.006265  0.045027  0.000000  1.000000
D267   3751.0  0.004665  0.040557  0.000000  1.000000
D268   3751.0  0.002021  0.026763  0.000000  1.000000
D269   3751.0  0.001033  0.015376  0.000000  0.625000
D270   3751.0  0.011197  0.070294  0.000000  1.000000
D271   3751.0  0.005065  0.056341  0.000000  1.000000
D272   3751.0  0.006598  0.050396  0.000000  1.000000
D273   3751.0  0.003399  0.034231  0.000000  0.750000
D274   3751.0  0.006265  0.063462  0.000000  1.000000
D275   3751.0  0.004532  0.053970  0.000000  1.000000
D276   3751.0  0.002799  0.035947  0.000000  1.000000
D277   3751.0  0.001666  0.029674  0.000000  1.000000
D278   3751.0  0.007531  0.046832  0.000000  0.500000
D279   3751.0  0.007198  0.055311  0.000000  0.666667
D280   3751.0  0.006132  0.049285  0.000000  1.000000
D281   3751.0  0.006998  0.054170  0.000000  1.000000
D282   3751.0  0.003946  0.038163  0.000000  1.000000
D283   3751.0  0.004465  0.045056  0.000000  1.000000
D284   3751.0  0.001866  0.021349  0.000000  0.333333
D285   3751.0  0.001266  0.020373  0.000000  0.500000
D286   3751.0  0.004532  0.051440  0.000000  1.000000
D287   3751.0  0.007598  0.067396  0.000000  1.000000
D288   3751.0  0.005599  0.036656  0.000000  1.000000
D289   3751.0  0.003386  0.026967  0.000000  0.600000
D290   3751.0  0.004532  0.040572  0.000000  0.750000
D291   3751.0  0.004212  0.037429  0.000000  1.000000
D292   3751.0  0.011064  0.092074  0.000000  1.000000
D293   3751.0  0.002044  0.023639  0.000000  0.666667
D294   3751.0  0.002346  0.031238  0.000000  1.000000
D295   3751.0  0.001999  0.028798  0.000000  1.000000
D296   3751.0  0.001511  0.025063  0.000000  1.000000
D297   3751.0  0.002599  0.029607  0.000000  1.000000
D298   3751.0  0.001866  0.031509  0.000000  1.000000
D299   3751.0  0.001799  0.029853  0.000000  1.000000
D300   3751.0  0.001288  0.024232  0.000000  1.000000
D301   3751.0  0.001577  0.031788  0.000000  1.000000
D302   3751.0  0.000217  0.005099  0.000000  0.250000
D303   3751.0  0.000355  0.014397  0.000000  0.833333
D304   3751.0  0.001777  0.038256  0.000000  1.000000
D305   3751.0  0.003555  0.053631  0.000000  1.000000
D306   3751.0  0.001777  0.033063  0.000000  1.000000
D307   3751.0  0.000733  0.014701  0.000000  0.500000
D308   3751.0  0.001533  0.026727  0.000000  1.000000
D309   3751.0  0.030592  0.104788  0.000000  1.000000
D310   3751.0  0.019758  0.077117  0.000000  0.888889
D311   3751.0  0.018928  0.075958  0.000000  1.000000
D312   3751.0  0.015516  0.068774  0.000000  1.000000
D313   3751.0  0.010663  0.050118  0.000000  0.692308
D314   3751.0  0.013893  0.070234  0.000000  1.000000
D315   3751.0  0.006732  0.046463  0.000000  1.000000
D316   3751.0  0.004132  0.042813  0.000000  1.000000
D317   3751.0  0.007865  0.069317  0.000000  1.000000
D318   3751.0  0.007687  0.051999  0.000000  1.000000
D319   3751.0  0.004465  0.036126  0.000000  1.000000
D320   3751.0  0.002899  0.030617  0.000000  1.000000
D321   3751.0  0.001899  0.019163  0.000000  0.375000
D322   3751.0  0.001377  0.023213  0.000000  1.000000
D323   3751.0  0.002719  0.036705  0.000000  1.000000
D324   3751.0  0.001280  0.024840  0.000000  1.000000
D325   3751.0  0.007065  0.044908  0.000000  1.000000
D326   3751.0  0.012663  0.070990  0.000000  1.000000
D327   3751.0  0.013196  0.087326  0.000000  1.000000
D328   3751.0  0.004399  0.038044  0.000000  1.000000
D329   3751.0  0.003572  0.034841  0.000000  1.000000
D330   3751.0  0.003199  0.034973  0.000000  1.000000
D331   3751.0  0.003377  0.041317  0.000000  1.000000
D332   3751.0  0.003910  0.049735  0.000000  1.000000
D333   3751.0  0.000853  0.022135  0.000000  1.000000
D334   3751.0  0.020161  0.070398  0.000000  1.000000
D335   3751.0  0.018660  0.062343  0.000000  1.000000
D336   3751.0  0.026360  0.085883  0.000000  1.000000
D337   3751.0  0.016286  0.061989  0.000000  1.000000
D338   3751.0  0.015318  0.062960  0.000000  1.000000
D339   3751.0  0.009349  0.047031  0.000000  1.000000
D340   3751.0  0.008464  0.050995  0.000000  1.000000
D341   3751.0  0.008211  0.050298  0.000000  1.000000
D342   3751.0  0.007831  0.056283  0.000000  1.000000
D343   3751.0  0.003343  0.030664  0.000000  0.846154
D344   3751.0  0.002555  0.027130  0.000000  0.750000
D345   3751.0  0.002799  0.036517  0.000000  1.000000
D346   3751.0  0.011641  0.068513  0.000000  1.000000
D347   3751.0  0.003766  0.029693  0.000000  0.500000
D348   3751.0  0.009298  0.050837  0.000000  1.000000
D349   3751.0  0.006772  0.045747  0.000000  1.000000
D350   3751.0  0.004159  0.032505  0.000000  0.666667
D351   3751.0  0.007050  0.054400  0.000000  1.000000
D352   3751.0  0.003443  0.036883  0.000000  1.000000
D353   3751.0  0.002213  0.030074  0.000000  1.000000
D354   3751.0  0.001573  0.027426  0.000000  1.000000
D355   3751.0  0.002266  0.033270  0.000000  1.000000
D356   3751.0  0.001244  0.020329  0.000000  0.583333
D357   3751.0  0.001481  0.025229  0.000000  0.777778
D358   3751.0  0.001377  0.025055  0.000000  1.000000
D359   3751.0  0.022350  0.075892  0.000000  0.666667
D360   3751.0  0.021461  0.070812  0.000000  1.000000
D361   3751.0  0.022527  0.079061  0.000000  1.000000
D362   3751.0  0.009364  0.039578  0.000000  0.500000
D363   3751.0  0.009553  0.051257  0.000000  1.000000
D364   3751.0  0.013396  0.069550  0.000000  1.000000
D365   3751.0  0.011064  0.066915  0.000000  1.000000
D366   3751.0  0.005599  0.051335  0.000000  1.000000
D367   3751.0  0.003066  0.031941  0.000000  1.000000
D368   3751.0  0.002866  0.034763  0.000000  1.000000
D369   3751.0  0.003021  0.044785  0.000000  1.000000

In [7]:
# Categorical Feature Statistics
cat_stats

                             value  count    pct
column                  rank
MoleculeElicitsResponse 1      Yes   2034  54.23
                        2       No   1717  45.77

In [8]:
# Target Distribution
target_df

                         count    pct
MoleculeElicitsResponse
Yes                       2034  54.23
No                        1717  45.77

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to bioresponse/019d5a23-4b00-71bc-b7e0-165aa7637026
019d5a23-4b00-71bc-b7e0-165aa7637026
54cbe67a82a6a8b8c5524964343d1a3479e0ace3618e163263e3b54140f6bcf8