### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="gallstone_disease",
    dataset_year="2023",
    domain_str="medical & healthcare",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.1097/md.0000000000037258",
    download_description="""
We get the data from UCI.

wget https://archive.ics.uci.edu/static/public/1150/gallstone-1.zip && unzip gallstone-1.zip && rm gallstone-1.zip && unzip dataset-uci.zip && rm dataset-uci.zip && mkdir -p local-data-warehouse/gallstone_disease && mv dataset-uci.xlsx local-data-warehouse/gallstone_disease/
""",
    # References
    academic_reference_bibtex=r"""@article{esen2024early,
  title={Early prediction of gallstone disease with a machine learning-based method from bioimpedance and laboratory data},
  author={Esen, {\.I}rfan and Arslan, Hilal and Esen, Selin Akt{\"u}rk and G{\"u}l{\c{s}}en, Mervenur and K{\"u}ltekin, Nimet and {\"O}zdemir, O{\u{g}}uzhan},
  journal={Medicine},
  volume={103},
  number={8},
  pages={e37258},
  year={2024},
  publisher={LWW}
}
""",
    academic_reference_bibtex_key="esen2024early",
    licence="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
We use the data without any further curation.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Gallstone Status",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="Gallstone Status",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

df = pd.read_excel(dataset_mold.path / "dataset-uci.xlsx", sheet_name="dataset", engine="calamine")

as_cat_type = [
    "Gallstone Status", "Coronary Artery Disease (CAD)", "Hypothyroidism",
    "Gender", "Comorbidity", "Hyperlipidemia", "Diabetes Mellitus (DM)",
]
df[as_cat_type] = df[as_cat_type].astype("category")
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 319
Columns: 39
Use sampling: False (sample size: 319)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['Lean Mass (LM) (%)', 'Obesity (%)', 'Glomerular Filtration Rate (GFR)', 'Body Protein Content (Protein) (%)', 'Weight', 'Vitamin D', 'Total Body Fat Ratio (TBFR) (%)', 'Muscle Mass (MM)', 'Total Fat Content (TFC)', 'Visceral Fat Area (VFA)']
Rows remaining as candidates after top-10 filter: 0 (of 319)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,Gallstone Status,Age,Gender,Comorbidity,Coronary Artery Disease (CAD),Hypothyroidism,Hyperlipidemia,Diabetes Mellitus (DM),Height,Weight,Body Mass Index (BMI),Total Body Water (TBW),Extracellular Water (ECW),Intracellular Water (ICW),Extracellular Fluid/Total Body Water (ECF/TBW),Total Body Fat Ratio (TBFR) (%),Lean Mass (LM) (%),Body Protein Content (Protein) (%),Visceral Fat Rating (VFR),Bone Mass (BM),Muscle Mass (MM),Obesity (%),Total Fat Content (TFC),Visceral Fat Area (VFA),Visceral Muscle Area (VMA) (Kg),Hepatic Fat Accumulation (HFA),Glucose,Total Cholesterol (TC),Low Density Lipoprotein (LDL),High Density Lipoprotein (HDL),Triglyceride,Aspartat Aminotransferaz (AST),Alanin Aminotransferaz (ALT),Alkaline Phosphatase (ALP),Creatinine,Glomerular Filtration Rate (GFR),C-Reactive Protein (CRP),Hemoglobin (HGB),Vitamin D
0,0,44,0,0,0,0,0,0,179,81.9,25.6,47.3,19.3,28.0,41.0,18.70,81.32,17.63,7,3.3,63.3,16.20,15.3,9.5,34.7,0,91.0,233.0,160.0,54.0,100.0,17.0,20.0,66.0,1.03,91.83,0.63,15.5,10.900000
1,1,42,0,0,0,0,0,0,182,88.0,26.6,47.6,19.0,29.0,40.0,22.05,72.26,18.17,8,2.1,65.2,13.05,19.4,11.5,35.0,1,96.0,336.0,177.0,60.0,159.0,12.0,27.0,65.0,1.01,95.80,0.50,14.9,23.600000
2,0,52,0,1,1,0,0,0,169,88.9,31.1,47.1,19.7,27.4,42.0,26.30,73.68,16.13,13,3.3,62.2,41.60,23.4,14.4,33.7,4,123.0,184.0,100.0,45.0,224.0,25.0,38.0,33.0,1.22,71.33,0.00,14.1,25.142857
3,1,31,0,0,0,0,0,0,178,94.8,29.9,50.9,20.6,30.3,40.0,25.30,74.68,15.54,9,3.5,67.3,36.00,24.0,14.8,35.4,2,97.0,156.0,109.0,34.0,70.0,36.0,24.0,67.0,0.72,125.00,13.90,15.4,13.600000
4,0,38,0,0,0,0,0,0,171,68.6,23.5,39.5,16.6,22.9,42.0,19.20,80.76,17.28,6,2.8,52.6,6.70,13.2,8.2,28.8,0,93.0,239.0,169.0,43.0,129.0,19.0,34.0,75.0,0.91,110.63,0.00,16.6,15.600000

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Gallstone Status,category,0.0,0.0,2.0,"0, 1"
1,Gender,category,0.0,0.0,2.0,"0, 1"
2,Comorbidity,category,0.0,0.0,4.0,"0, 1, 3, 2"
3,Coronary Artery Disease (CAD),category,0.0,0.0,2.0,"0, 1"
4,Hypothyroidism,category,0.0,0.0,2.0,"0, 1"
5,Hyperlipidemia,category,0.0,0.0,2.0,"0, 1"
6,Diabetes Mellitus (DM),category,0.0,0.0,2.0,"0, 1"
7,Weight,float64,0.0,0.0,245.0,"68.4, 63.6, 76.8, 78.4, 69.6, 74.7, 92.2, 68.2, 62.8, 70.6"
8,Body Mass Index (BMI),float64,0.0,0.0,162.0,"28.2, 25.3, 28.0, 29.9, 25.2, 25.1, 27.2, 27.4, 30.8, 26.6"
9,Total Body Water (TBW),float64,0.0,0.0,199.0,"47.1, 34.3, 44.0, 31.2, 36.2, 47.3, 47.6, 31.9, 34.8, 43.2"
10,Extracellular Water (ECW),float64,0.0,0.0,109.0,"18.0, 20.0, 14.0, 12.0, 13.0, 19.0, 11.0, 15.0, 17.1, 16.9"
11,Intracellular Water (ICW),float64,0.0,0.0,138.0,"20.0, 28.0, 22.0, 23.0, 25.0, 29.0, 27.0, 21.0, 19.0, 18.0"
12,Extracellular Fluid/Total Body Water (ECF/TBW),float64,0.0,0.0,81.0,"42.0, 43.0, 41.0, 40.0, 44.0, 45.0, 46.0, 47.0, 48.0, 39.0"
13,Total Body Fat Ratio (TBFR) (%),float64,0.0,0.0,228.0,"19.2, 23.6, 34.2, 19.7, 19.1, 21.6, 37.1, 31.9, 33.4, 28.8"
14,Lean Mass (LM) (%),float64,0.0,0.0,294.0,"73.22, 76.4, 80.24, 71.13, 65.87, 77.73, 68.16, 67.18, 63.6, 72.11"
15,Body Protein Content (Protein) (%),float64,0.0,0.0,259.0,"17.1, 14.2, 14.19, 14.9, 13.95, 15.85, 13.45, 18.47, 16.48, 15.55"
16,Bone Mass (BM),float64,0.0,0.0,25.0,"2.4, 2.6, 3.0, 2.2, 2.8, 2.5, 2.3, 3.1, 3.3, 3.4"
17,Muscle Mass (MM),float64,0.0,0.0,219.0,"56.8, 68.2, 43.9, 63.4, 43.5, 65.4, 64.5, 41.8, 58.1, 65.2"
18,Obesity (%),float64,0.0,0.0,276.0,"6.8, 15.1, 49.5, 36.0, 13.2, 28.4, 32.6, 23.5, 28.6, 31.1"
19,Total Fat Content (TFC),float64,0.0,0.0,212.0,"24.2, 20.1, 19.2, 27.6, 23.8, 28.9, 16.4, 22.0, 15.6, 25.3"
20,Visceral Fat Area (VFA),float64,0.0,0.0,209.0,"9.1, 12.6, 10.6, 8.2, 9.5, 10.1, 14.5, 9.0, 10.4, 8.0"
21,Visceral Muscle Area (VMA) (Kg),float64,0.0,0.0,179.0,"34.5, 26.8, 32.3, 32.2, 28.6, 29.2, 35.3, 24.2, 34.0, 36.4"
22,Glucose,float64,0.0,0.0,78.0,"91.0, 99.0, 93.0, 89.0, 96.0, 94.0, 92.0, 101.0, 103.0, 98.0"
23,Total Cholesterol (TC),float64,0.0,0.0,150.0,"183.0, 187.0, 190.0, 172.0, 199.0, 173.0, 206.0, 185.0, 226.0, 180.0"
24,Low Density Lipoprotein (LDL),float64,0.0,0.0,135.0,"122.0, 94.0, 127.0, 106.0, 125.0, 118.0, 160.0, 151.0, 115.0, 129.0"
25,High Density Lipoprotein (HDL),float64,0.0,0.0,63.0,"40.0, 44.0, 42.0, 46.0, 50.0, 45.0, 54.0, 43.0, 48.0, 47.0"
26,Triglyceride,float64,0.0,0.0,178.0,"125.0, 116.0, 97.0, 78.0, 118.0, 63.0, 128.0, 103.0, 145.0, 105.0"
27,Aspartat Aminotransferaz (AST),float64,0.0,0.0,44.0,"16.0, 17.0, 14.0, 18.0, 15.0, 21.0, 13.0, 19.0, 20.0, 22.0"
28,Alanin Aminotransferaz (ALT),float64,0.0,0.0,67.0,"16.0, 13.0, 18.0, 14.0, 12.0, 15.0, 20.0, 17.0, 19.0, 27.0"
29,Alkaline Phosphatase (ALP),float64,0.0,0.0,97.0,"66.0, 73.0, 63.0, 79.0, 65.0, 51.0, 70.0, 86.0, 49.0, 58.0"
30,Creatinine,float64,0.0,0.0,76.0,"0.7, 0.6, 0.64, 0.86, 0.81, 0.59, 0.96, 0.9, 0.82, 0.79"
31,Glomerular Filtration Rate (GFR),float64,0.0,0.0,275.0,"106.6, 107.26, 108.81, 107.4, 112.47, 103.7, 85.09, 109.0, 114.0, 114.37"
32,C-Reactive Protein (CRP),float64,0.0,0.0,117.0,"0.0, 0.5, 0.2, 0.6, 0.8, 0.9, 0.08, 1.7, 1.3, 2.4"
33,Hemoglobin (HGB),float64,0.0,0.0,83.0,"14.4, 15.6, 13.5, 16.0, 13.8, 14.5, 14.1, 12.9, 15.5, 15.9"
34,Vitamin D,float64,0.0,0.0,238.0,"24.0, 20.0, 8.7, 30.0, 35.4, 22.0, 15.7, 21.8, 7.8, 12.4"
35,Age,int64,0.0,0.0,56.0,"53, 56, 50, 51, 44, 59, 54, 35, 38, 47"
36,Height,int64,0.0,0.0,46.0,"170, 175, 168, 160, 165, 163, 172, 176, 158, 178"
37,Visceral Fat Rating (VFR),int64,0.0,0.0,22.0,"9, 7, 8, 10, 12, 6, 11, 5, 3, 15"
38,Hepatic Fat Accumulation (HFA),int64,0.0,0.0,5.0,"0, 2, 1, 3, 4"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
Age,319.0,48.068966,12.114558,20.00,96.00
Height,319.0,167.156740,10.053030,145.00,191.00
Weight,319.0,80.564890,15.709069,42.90,143.50
Body Mass Index (BMI),319.0,28.877116,5.313707,17.40,49.70
Total Body Water (TBW),319.0,40.587774,7.930235,13.00,66.20
Extracellular Water (ECW),319.0,17.071160,3.161857,9.00,27.80
Intracellular Water (ICW),319.0,23.634483,5.349332,13.80,57.10
Extracellular Fluid/Total Body Water (ECF/TBW),319.0,42.212038,3.244470,29.23,52.00
Total Body Fat Ratio (TBFR) (%),319.0,28.274984,8.444417,6.30,50.92
Lean Mass (LM) (%),319.0,71.638245,8.437598,48.99,93.67
Body Protein Content (Protein) (%),319.0,15.938809,2.334744,5.56,24.81
Visceral Fat Rating (VFR),319.0,9.078370,4.332501,1.00,31.00
Bone Mass (BM),319.0,2.803292,0.509467,1.40,4.00
Muscle Mass (MM),319.0,54.273041,10.603833,4.70,78.80
Obesity (%),319.0,35.850125,109.799718,0.40,1954.00
Total Fat Content (TFC),319.0,23.487774,9.607607,3.10,62.50
Visceral Fat Area (VFA),319.0,12.171599,5.262178,0.90,41.00
Visceral Muscle Area (VMA) (Kg),319.0,30.403448,4.460530,18.90,41.10
Hepatic Fat Accumulation (HFA),319.0,1.150470,1.059217,0.00,4.00
Glucose,319.0,108.688715,44.848714,69.00,575.00
Total Cholesterol (TC),319.0,203.495298,45.758501,60.00,360.00
Low Density Lipoprotein (LDL),319.0,126.652351,38.541175,11.00,293.00
High Density Lipoprotein (HDL),319.0,49.475549,17.718701,25.00,273.00
Triglyceride,319.0,144.502163,97.904493,1.39,838.00
Aspartat Aminotransferaz (AST),319.0,21.684953,16.697605,8.00,195.00
Alanin Aminotransferaz (ALT),319.0,26.855799,27.884413,3.00,372.00
Alkaline Phosphatase (ALP),319.0,73.112539,24.181069,7.00,197.00
Creatinine,319.0,0.800611,0.176433,0.46,1.46
Glomerular Filtration Rate (GFR),319.0,100.818903,16.971396,10.60,132.00
C-Reactive Protein (CRP),319.0,1.853856,4.989591,0.00,43.40
Hemoglobin (HGB),319.0,14.418182,1.775815,8.50,18.80
Vitamin D,319.0,21.401411,9.981659,3.50,53.10

In [7]:
# Categorical Feature Statistics
cat_stats

                                   value  count    pct
column                        rank
Comorbidity                   1        0    217  68.03
                              2        1     99  31.03
                              3        3      2   0.63
                              4        2      1   0.31
Coronary Artery Disease (CAD) 1        0    307  96.24
                              2        1     12   3.76
Diabetes Mellitus (DM)        1        0    276  86.52
                              2        1     43  13.48
Gallstone Status              1        0    161  50.47
                              2        1    158  49.53
Gender                        1        0    162  50.78
                              2        1    157  49.22
Hyperlipidemia                1        0    311  97.49
                              2        1      8   2.51
Hypothyroidism                1        0    310  97.18
                              2        1      9   2.82

In [8]:
# Target Distribution
target_df

                  count    pct
Gallstone Status
0                   161  50.47
1                   158  49.53

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_iid_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_iid_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=20, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019c7c96-2179-77ae-96b3-ca02452ece61
e66bdeb1ec9ba2360a2ffe61292c8bd05d0a2c97695faebf7be419574904ba51