### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="polish_companies_bankruptcy",
    dataset_year="2010",
    domain_str="finance",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C5F600",
    download_description="""
We download the data from the UCI repository and uzip it to a predefined folder.

mkdir -p local-data-warehouse/polish_companies_bankruptcy/ && wget -P local-data-warehouse/polish_companies_bankruptcy/ https://archive.ics.uci.edu/static/public/365/polish+companies+bankruptcy+data.zip && unzip local-data-warehouse/polish_companies_bankruptcy/polish+companies+bankruptcy+data.zip -d local-data-warehouse/polish_companies_bankruptcy/ && rm local-data-warehouse/polish_companies_bankruptcy/polish+companies+bankruptcy+data.zip
""",
    # References
    academic_reference_bibtex="""@article{zikeba2016ensemble,
  title={Ensemble boosted trees with synthetic features generation in application to bankruptcy prediction},
  author={Zi{\k{e}}ba, Maciej and Tomczak, Sebastian K and Tomczak, Jakub M},
  journal={Expert systems with applications},
  volume={58},
  pages={93--101},
  year={2016},
  publisher={Elsevier}
}
""",
    academic_reference_bibtex_key="zikeba2016ensemble",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
- We only use data from year 5 (5year.arff), because it is the newest data and the target is bankruptcy status after only 1 year.
- We created semantically meaningful feature names.
- We removed duplicates.
- Anomaly: the data contains a lot of features created by feature engineering.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="company_bankrupt",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="company_bankrupt",
)

## Preprocessing

In [2]:
import arff
import pandas as pd

with open(dataset_mold.path /"5year.arff") as f:
        data = arff.load(f)

df = pd.DataFrame(data["data"], columns=[x[0] for x in data["attributes"]])

target_feature = task_mold.target_column_name
df.columns = [
    "net_profit_to_total_assets",
    "total_liabilities_to_total_assets",
    "working_capital_to_total_assets",
    "current_assets_to_short_term_liabilities",
    "liquidity_days_ratio",
    "retained_earnings_to_total_assets",
    "ebit_to_total_assets",
    "book_value_equity_to_total_liabilities",
    "sales_to_total_assets",
    "equity_to_total_assets",
    "extended_profit_to_total_assets",
    "gross_profit_to_short_term_liabilities",
    "gross_profit_plus_depreciation_to_sales",
    "gross_profit_plus_interest_to_total_assets",
    "liabilities_days_ratio",
    "gross_profit_plus_depreciation_to_total_liabilities",
    "total_assets_to_total_liabilities",
    "gross_profit_to_total_assets",
    "gross_profit_to_sales",
    "inventory_days_ratio",
    "sales_growth_ratio",
    "operating_profit_to_total_assets",
    "net_profit_to_sales",
    "three_year_gross_profit_to_total_assets",
    "equity_minus_share_capital_to_total_assets",
    "net_profit_plus_depreciation_to_total_liabilities",
    "operating_profit_to_financial_expenses",
    "working_capital_to_fixed_assets",
    "log_total_assets",
    "net_liabilities_to_sales",
    "gross_profit_plus_interest_to_sales",
    "current_liabilities_days_ratio",
    "operating_expenses_to_short_term_liabilities",
    "operating_expenses_to_total_liabilities",
    "sales_profit_to_total_assets",
    "total_sales_to_total_assets",
    "current_assets_minus_inventories_to_long_term_liabilities",
    "constant_capital_to_total_assets",
    "sales_profit_to_sales",
    "liquid_assets_to_short_term_liabilities",
    "liabilities_to_adjusted_operating_profit",
    "operating_profit_to_sales",
    "receivables_plus_inventory_turnover_days",
    "receivables_days_ratio",
    "net_profit_to_inventory",
    "current_assets_minus_inventory_to_short_term_liabilities",
    "inventory_days_cost_ratio",
    "ebitda_to_total_assets",
    "ebitda_to_sales",
    "current_assets_to_total_liabilities",
    "short_term_liabilities_to_total_assets",
    "short_term_liabilities_days_cost_ratio",
    "equity_to_fixed_assets",
    "constant_capital_to_fixed_assets",
    "working_capital_absolute",
    "gross_margin",
    "adjusted_liquidity_ratio",
    "total_costs_to_total_sales",
    "long_term_liabilities_to_equity",
    "inventory_turnover_ratio",
    "receivables_turnover_ratio",
    "short_term_liabilities_days_ratio",
    "sales_to_short_term_liabilities",
    "sales_to_fixed_assets",
    target_feature,
]

df[target_feature] = df[target_feature].map({"1": "Yes", "0": "No"}).astype("category")

# conflicting duplicates drop (without target column)
df = df.drop_duplicates(subset=[c for c in df.columns if c != task_mold.target_column_name], keep=False)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 5,790
Columns: 65
Use sampling: False (sample size: 5,790)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['liquidity_days_ratio', 'working_capital_absolute', 'liquid_assets_to_short_term_liabilities', 'gross_profit_plus_interest_to_sales', 'gross_profit_plus_depreciation_to_total_liabilities', 'liabilities_days_ratio', 'operating_expenses_to_total_liabilities', 'gross_profit_to_short_term_liabilities', 'gross_profit_to_sales', 'net_profit_plus_depreciation_to_total_liabilities']
Rows remaining as candidates after top-10 filter: 10 (of 5,790)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,net_profit_to_total_assets,total_liabilities_to_total_assets,working_capital_to_total_assets,current_assets_to_short_term_liabilities,liquidity_days_ratio,retained_earnings_to_total_assets,ebit_to_total_assets,book_value_equity_to_total_liabilities,sales_to_total_assets,equity_to_total_assets,extended_profit_to_total_assets,gross_profit_to_short_term_liabilities,gross_profit_plus_depreciation_to_sales,gross_profit_plus_interest_to_total_assets,liabilities_days_ratio,gross_profit_plus_depreciation_to_total_liabilities,total_assets_to_total_liabilities,gross_profit_to_total_assets,gross_profit_to_sales,inventory_days_ratio,sales_growth_ratio,operating_profit_to_total_assets,net_profit_to_sales,three_year_gross_profit_to_total_assets,equity_minus_share_capital_to_total_assets,net_profit_plus_depreciation_to_total_liabilities,operating_profit_to_financial_expenses,working_capital_to_fixed_assets,log_total_assets,net_liabilities_to_sales,gross_profit_plus_interest_to_sales,current_liabilities_days_ratio,operating_expenses_to_short_term_liabilities,operating_expenses_to_total_liabilities,sales_profit_to_total_assets,total_sales_to_total_assets,current_assets_minus_inventories_to_long_term_liabilities,constant_capital_to_total_assets,sales_profit_to_sales,liquid_assets_to_short_term_liabilities,liabilities_to_adjusted_operating_profit,operating_profit_to_sales,receivables_plus_inventory_turnover_days,receivables_days_ratio,net_profit_to_inventory,current_assets_minus_inventory_to_short_term_liabilities,inventory_days_cost_ratio,ebitda_to_total_assets,ebitda_to_sales,current_assets_to_total_liabilities,short_term_liabilities_to_total_assets,short_term_liabilities_days_cost_ratio,equity_to_fixed_assets,constant_capital_to_fixed_assets,working_capital_absolute,gross_margin,adjusted_liquidity_ratio,total_costs_to_total_sales,long_term_liabilities_to_equity,inventory_turnover_ratio,receivables_turnover_ratio,short_term_liabilities_days_ratio,sales_to_short_term_liabilities,sales_to_fixed_assets,company_bankrupt
0,-0.024622,0.69575,0.23866,1.3620,6.9025,-0.03091,-0.024622,0.43729,3.9185,0.30425,0.006002,-0.037346,0.002942,-0.024622,22025.00,0.016572,1.4373,-0.024622,-0.006284,14.876,0.99532,-0.001915,-0.006284,0.053616,0.25164,0.016572,-0.062521,2.33870,3.6769,0.171910,-0.002653,61.059,5.9778,5.66450,-0.022609,3.91850,101.0100,0.31156,-0.005770,0.039764,0.677380,-0.000489,81.201,66.325,-0.154170,1.11980,14.791,-0.038066,-0.009715,1.2906,0.65929,0.16729,2.9814,3.0530,1134.10,-0.005770,-0.080927,1.006200,0.024023,24.5360,5.5032,61.412,5.9435,38.3980,No
1,0.370150,0.37631,0.39923,2.0609,36.2850,0.00000,0.481240,1.65740,3.8763,0.62369,0.609720,1.278800,0.133850,0.481240,264.73,1.378800,2.6574,0.481240,0.124150,0.000,1.17570,0.533700,0.095491,1.408600,0.62065,1.083600,4.153900,1.77870,3.2170,-0.005092,0.124220,41.740,8.7446,8.74460,0.585560,3.87630,NaN,0.62369,0.151060,1.242000,0.021956,0.137680,29.016,29.016,NaN,2.06090,0.000,0.496080,0.127980,2.0609,0.37631,0.11436,2.7787,2.7787,658.04,0.151060,0.593490,0.878260,0.000000,NaN,12.5790,35.435,10.3010,17.2700,No
2,0.009359,0.46223,0.11333,1.2549,-92.8570,0.00000,0.009478,1.16340,1.4469,0.53777,0.028016,0.021318,0.036509,0.009478,3193.80,0.114280,2.1634,0.009478,0.006550,116.640,0.89136,0.027737,0.006469,-0.161410,0.49595,0.114030,1.496200,0.25637,3.8558,0.316610,0.015220,114.010,3.2014,3.07930,0.023555,1.44690,5.5037,0.55513,0.016280,0.024769,0.216750,0.019170,137.970,21.323,0.020241,0.21489,118.570,-0.015611,-0.010789,1.2071,0.44460,0.31236,1.2165,1.2558,813.11,0.016280,0.017404,0.993480,0.032281,3.1292,17.1170,112.160,3.2544,3.2731,No
3,0.085659,0.28314,0.48309,2.7062,-4.5713,0.18313,0.107660,2.12670,1.0215,0.60217,0.107660,0.380230,0.059843,0.107660,641.01,0.569410,3.5318,0.107660,0.039960,43.494,1.22280,0.094664,0.031794,0.230380,0.60217,0.491710,0.358930,2.06660,4.6094,0.093601,0.039960,39.185,9.3148,0.33433,0.094664,2.75720,NaN,0.60217,0.035137,0.797590,0.062799,0.035137,73.213,29.719,0.266820,1.57230,44.429,0.041098,0.015255,2.7062,0.28314,0.10736,2.5760,2.5760,19652.00,0.021050,0.142250,0.978950,0.000000,8.3920,12.2820,38.360,9.5151,11.5250,No
4,0.042429,0.24166,0.38281,2.5840,68.5550,0.22159,0.055587,2.80740,1.1018,0.67845,0.055587,0.230020,0.118440,0.055587,843.35,0.432800,4.1380,0.055587,0.062946,98.386,0.97836,0.062451,0.048046,0.282980,0.67845,0.378350,0.779190,1.01940,4.9325,0.272150,0.062946,110.060,3.3165,0.25842,0.062451,0.89247,NaN,0.67845,0.070718,0.011624,0.071285,0.070718,256.950,158.560,0.178250,1.59910,108.400,0.013446,0.015226,2.5840,0.24166,0.30152,1.8066,1.8066,32767.00,0.092414,0.062539,0.015226,0.000000,3.7099,2.3020,99.885,3.6542,2.3516,No

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,company_bankrupt,category,0.0,0.00,2.0,"No, Yes"
1,current_assets_minus_inventories_to_long_term_liabilities,float64,2502.0,43.21,3225.0,"2.7727, 4.1023, 1.0662, 1.3454, 11.675, 1.534, 18.721, 1.8035, 1.1776, 5.2905"
2,operating_profit_to_financial_expenses,float64,389.0,6.72,4935.0,"0.0, 1.397, 2.6295, 1.3454, 7.0649, 0.7183, 3.0986, 1.2127, 1.1694, 7.1814"
3,net_profit_to_inventory,float64,264.0,4.56,5367.0,"0.0, 0.132, 0.161, 1.5193, 2.907, 1.668, 0.368, 1.0742, 0.3118, 0.1546"
4,inventory_turnover_ratio,float64,264.0,4.56,5319.0,"11.045, 11.257, 12.364, 10.34, 5.2512, 17.114, 12.16, 9.2509, 4.0762, 7.4142"
5,three_year_gross_profit_to_total_assets,float64,135.0,2.33,5496.0,"0.0, 0.1345, 1.4774, 0.735, 0.1304, 0.2073, 0.1976, 0.7013, 0.2343, 0.0423"
6,working_capital_to_fixed_assets,float64,105.0,1.81,5555.0,"1.2599, 1.0404, 2.5396, 1.5311, 2.5157, 0.5859, 1.0304, 13.99, 2.0996, 6.7331"
7,equity_to_fixed_assets,float64,105.0,1.81,5415.0,"2.2499, 1.0391, 1.3602, 1.2216, 1.8225, 1.5962, 1.0107, 1.3816, 2.3016, 1.2624"
8,constant_capital_to_fixed_assets,float64,105.0,1.81,5298.0,"1.0371, 2.2499, 1.1296, 1.6298, 1.3008, 1.9589, 1.56, 1.0736, 1.2271, 1.1915"
9,sales_to_fixed_assets,float64,105.0,1.81,5493.0,"1.6959, 6.7586, 2.682, 1.8704, 16.589, 3.5166, 14.521, 6.0223, 2.9985, 0.6372"
10,sales_growth_ratio,float64,103.0,1.78,4386.0,"1.121, 1.0022, 1.2387, 1.0637, 1.1091, 1.3353, 1.1086, 1.0942, 1.1148, 1.071"
11,liabilities_to_adjusted_operating_profit,float64,84.0,1.45,5540.0,"0.0, 0.1128, 0.2253, 0.1093, 0.2925, -0.1207, 0.1411, 0.0179, 0.0193, 0.1863"
12,current_liabilities_days_ratio,float64,46.0,0.79,5458.0,"0.0, 62.32, 109.97, 112.12, 100.83, 101.1, 48.78, 57.341, 135.24, 124.9"
13,short_term_liabilities_days_cost_ratio,float64,36.0,0.62,5449.0,"0.0, 0.1571, 0.3059, 0.1505, 0.15, 0.1933, 0.1055, 0.2708, 0.1097, 0.2474"
14,inventory_days_cost_ratio,float64,35.0,0.60,5340.0,"0.0, 140.3, 33.904, 18.157, 68.232, 100.81, 15.301, 107.59, 65.362, 12.759"
15,current_assets_to_short_term_liabilities,float64,21.0,0.36,5416.0,"1.4348, 1.041, 1.3859, 1.6422, 1.1501, 1.2851, 1.7137, 1.0074, 1.1679, 1.2003"
16,gross_profit_to_short_term_liabilities,float64,21.0,0.36,5630.0,"0.2061, 0.1001, 0.465, 0.4245, 0.3339, 0.1705, 0.1996, 1.4036, 0.6034, 0.9327"
17,operating_expenses_to_short_term_liabilities,float64,21.0,0.36,5539.0,"0.0, 4.7075, 2.0725, 3.2695, 5.1785, 5.1719, 5.2954, 14.25, 3.6507, 2.5727"
18,liquid_assets_to_short_term_liabilities,float64,21.0,0.36,5643.0,"0.0, 0.3246, 1.2077, 0.3741, 0.1718, 0.506, 1.269, 0.0329, 0.4962, 0.1729"
19,current_assets_minus_inventory_to_short_term_liabilities,float64,21.0,0.36,5494.0,"1.1699, 2.0599, 2.0799, 1.2142, 0.3202, 1.3217, 1.6191, 1.0586, 1.0043, 1.6204"
20,sales_to_short_term_liabilities,float64,21.0,0.36,5523.0,"5.6358, 2.5748, 3.6796, 14.691, 4.2731, 2.1269, 2.3307, 10.156, 3.6029, 12.278"
21,book_value_equity_to_total_liabilities,float64,18.0,0.31,5581.0,"1.1634, 1.2376, 0.7327, 2.9632, 2.1171, 1.8245, 1.9198, 1.0819, 1.3062, 0.3363"
22,gross_profit_plus_depreciation_to_total_liabilities,float64,18.0,0.31,5642.0,"0.1764, 1.195, 1.0101, 0.397, 0.9301, -0.1098, -0.1753, 0.7082, 0.1391, 0.5857"
23,total_assets_to_total_liabilities,float64,18.0,0.31,5398.0,"1.9046, 1.3363, 2.9198, 1.7673, 1.945, 1.7327, 1.5152, 1.5508, 3.9632, 1.5194"
24,net_profit_plus_depreciation_to_total_liabilities,float64,18.0,0.31,5613.0,"0.0, 0.1932, 0.2509, 1.0898, 0.1939, 0.5512, 0.2482, 0.3678, 0.2226, 1.2018"
25,operating_expenses_to_total_liabilities,float64,18.0,0.31,5630.0,"0.0, 3.5357, 0.5075, 0.0135, 3.3595, 0.1246, 0.1257, 6.5941, 0.1268, 14.23"
26,current_assets_to_total_liabilities,float64,18.0,0.31,5453.0,"1.0454, 1.0509, 2.9458, 1.1042, 1.2891, 1.7068, 1.2161, 1.7137, 1.9128, 1.666"
27,receivables_turnover_ratio,float64,15.0,0.26,5555.0,"10.096, 4.3754, 7.2732, 16.789, 6.7081, 9.4409, 5.9772, 11.183, 12.352, 5.695"
28,liquidity_days_ratio,float64,11.0,0.19,5718.0,"0.0, 33.352, 52.287, 15.209, -109.53, -138.98, -18.84, 54.833, -11.512, -45.718"
29,liabilities_days_ratio,float64,6.0,0.10,5635.0,"0.0, 2069.4, 1302.2, 305.44, 361.35, 488.75, 2164.5, 1690.0, 1461.7, 276.63"
30,net_profit_to_total_assets,float64,3.0,0.05,5570.0,"0.0, 0.2229, 0.0462, 0.146, 0.1535, 0.0246, 0.2041, -0.0938, 0.0487, 0.1004"
31,total_liabilities_to_total_assets,float64,3.0,0.05,5566.0,"0.0, 1.0208, 0.5772, 0.66, 0.402, 0.172, 0.3853, 0.3425, 0.6158, 0.7195"
32,working_capital_to_total_assets,float64,3.0,0.05,5597.0,"1.0, 0.2003, -0.0575, 0.5797, 0.165, 0.2959, 0.248, 0.1061, -0.0618, 0.3523"
33,retained_earnings_to_total_assets,float64,3.0,0.05,3498.0,"0.0, 0.1352, -0.3777, -0.3596, 0.1881, -0.1777, 0.0347, -0.0055, 0.075, 0.1903"
34,ebit_to_total_assets,float64,3.0,0.05,5600.0,"0.0, 0.1438, 0.2314, 0.2443, 0.2044, -0.1829, -0.031, 0.02, 0.1956, 0.1571"
35,equity_to_total_assets,float64,3.0,0.05,5558.0,"1.0, 0.7477, 0.2406, 0.6575, 0.4229, 0.5374, 0.3497, 0.4412, 0.6144, 0.8442"
36,extended_profit_to_total_assets,float64,3.0,0.05,5609.0,"0.0, 0.1482, 0.115, 0.1426, 0.2571, 0.1668, 0.1647, 0.0931, 0.1341, 0.1053"
37,gross_profit_plus_interest_to_total_assets,float64,3.0,0.05,5600.0,"0.0, 0.1438, 0.2314, 0.2443, 0.2044, -0.1829, -0.031, 0.02, 0.1956, 0.1571"
38,gross_profit_to_total_assets,float64,3.0,0.05,5600.0,"0.0, 0.1438, 0.2314, 0.2443, 0.2044, -0.1829, -0.031, 0.02, 0.1956, 0.1571"
39,operating_profit_to_total_assets,float64,3.0,0.05,5096.0,"0.0, 0.1706, 0.1637, 0.1437, 0.0353, 0.1396, 0.1178, 0.062, 0.058, 0.0609"
40,equity_minus_share_capital_to_total_assets,float64,3.0,0.05,5609.0,"0.5013, 0.7256, 0.5942, 0.3994, 0.5262, 0.6417, 0.0, 0.1937, 0.7752, 0.1245"
41,log_total_assets,float64,3.0,0.05,5170.0,"4.1709, 4.1152, 4.225, 4.402, 4.8609, 4.2604, 3.6421, 3.5293, 3.4531, 3.8214"
42,sales_profit_to_total_assets,float64,3.0,0.05,5593.0,"0.0, 0.0, 0.0126, 0.1463, 0.1018, 0.0, 0.1081, 0.1785, 0.0926, -0.2423"
43,total_sales_to_total_assets,float64,3.0,0.05,5364.0,"1.2038, 1.3215, 1.58, 1.1918, 1.5127, 1.5792, 1.0431, 1.6662, 1.1461, 1.1609"
44,constant_capital_to_total_assets,float64,3.0,0.05,5522.0,"1.0, 0.8079, 0.443, 0.4965, 0.832, 0.3497, 0.759, 0.6142, 0.6994, 0.7477"
45,ebitda_to_total_assets,float64,3.0,0.05,5556.0,"0.0, -0.0038, 0.1452, 0.1331, -0.1224, 0.0235, 0.1097, 0.1124, 0.1221, 0.1398"
46,short_term_liabilities_to_total_assets,float64,3.0,0.05,5524.0,"0.0, 0.7195, 0.3624, 0.5035, 0.1642, 0.3019, 0.1805, 0.2665, 0.3575, 0.2277"
47,adjusted_liquidity_ratio,float64,3.0,0.05,5519.0,"0.0, 0.1864, 0.3068, 0.1594, 0.1209, 0.1581, 0.3622, 0.1034, 0.1122, 0.1386"
48,long_term_liabilities_to_equity,float64,3.0,0.05,3220.0,"0.0, 0.2105, 0.0053, 0.0142, 0.1205, 0.0454, 0.1186, 0.57, 0.3396, 0.2865"
49,sales_to_total_assets,float64,1.0,0.02,4782.0,"1.0277, 1.0117, 1.0376, 1.0488, 1.0102, 1.0085, 1.0335, 1.023, 1.0121, 1.0008"
50,gross_profit_plus_depreciation_to_sales,float64,0.0,0.00,5608.0,"0.0, 0.162, 0.0326, -0.391, 0.1022, 0.0253, 0.1395, 0.1003, 0.1043, 0.009"
51,gross_profit_to_sales,float64,0.0,0.00,5620.0,"0.0, 0.1394, 0.0898, 0.0378, 0.1081, -0.124, 0.0561, 0.0645, 0.0067, 0.0085"
52,inventory_days_ratio,float64,0.0,0.00,5342.0,"0.0, 69.508, 100.19, 34.392, 0.3406, 29.152, 26.659, 16.546, 22.995, 28.263"
53,net_profit_to_sales,float64,0.0,0.00,5595.0,"0.0, 0.0008, 0.1914, 0.0032, 0.0473, 0.0028, 0.0327, 0.0507, 0.109, 0.0415"
54,net_liabilities_to_sales,float64,0.0,0.00,5572.0,"0.2685, 0.2823, 0.6125, 0.0, -0.0433, 0.1227, 0.61, 0.2568, 0.2003, 0.1541"
55,gross_profit_plus_interest_to_sales,float64,0.0,0.00,5643.0,"0.0, 0.0173, 0.1128, 0.0371, 0.0738, 0.0738, 0.0893, 0.0773, 0.0314, 0.0321"
56,sales_profit_to_sales,float64,0.0,0.00,5597.0,"0.0, 0.002, 0.0, 0.0144, 0.1247, 0.0, 0.1036, 0.1128, 0.1815, 0.1308"
57,operating_profit_to_sales,float64,0.0,0.00,5110.0,"0.0, 0.0, -0.1247, 0.0095, 0.0288, 0.0099, 0.1052, 0.0742, 0.049, 0.0718"
58,receivables_plus_inventory_turnover_days,float64,0.0,0.00,5299.0,"0.0, 117.68, 134.82, 111.2, 105.27, 144.78, 103.83, 137.33, 150.06, 105.4"
59,receivables_days_ratio,float64,0.0,0.00,5560.0,"0.0, 41.469, 21.74, 103.3, 54.412, 50.184, 67.206, 109.6, 45.113, 61.507"
60,ebitda_to_sales,float64,0.0,0.00,5544.0,"0.0, -0.0089, 0.1061, 0.0037, 0.0, -0.0886, -0.0002, -0.1384, -0.0077, 0.0808"
61,working_capital_absolute,float64,0.0,0.00,5660.0,"1797.0, 2443.9, 13593.0, 10361.0, -11216.0, 2192.4, 1156.9, 5743.2, 1038.1, 1020.1"
62,gross_margin,float64,0.0,0.00,5589.0,"1.0, 0.1138, 0.1032, 0.1695, 0.1037, 0.1554, 0.184, 0.1478, 0.1036, 0.0552"
63,total_costs_to_total_sales,float64,0.0,0.00,5072.0,"1.0053, 1.0115, 1.0179, 0.9943, 1.0505, 0.9895, 1.0438, 0.9393, 1.022, 0.9822"
64,short_term_liabilities_days_ratio,float64,0.0,0.00,5507.0,"0.0, 102.89, 104.08, 107.17, 117.87, 132.1, 108.09, 132.22, 141.76, 107.84"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
net_profit_to_total_assets,5787.0,-0.024261,6.227187,-4.638900e+02,8.745900e+01
total_liabilities_to_total_assets,5787.0,0.466893,5.810483,-4.308700e+02,7.241600e+01
working_capital_to_total_assets,5787.0,0.187873,1.189212,-7.206700e+01,2.833600e+01
current_assets_to_short_term_liabilities,5769.0,4.908487,92.370898,-4.031100e-01,6.845800e+03
liquidity_days_ratio,5779.0,19.568831,21751.730364,-1.076400e+06,1.250100e+06
retained_earnings_to_total_assets,5787.0,0.021568,10.095067,-4.638900e+02,5.432500e+02
ebit_to_total_assets,5787.0,-0.115911,9.150502,-5.174800e+02,5.530000e+00
book_value_equity_to_total_liabilities,5772.0,5.739466,103.400811,-3.735100e+00,6.868500e+03
sales_to_total_assets,5789.0,1.596409,1.561708,-3.496000e+00,6.560700e+01
equity_to_total_assets,5787.0,0.544601,5.823079,-7.144400e+01,3.398500e+02
extended_profit_to_total_assets,5787.0,-0.012176,6.125555,-4.638900e+02,6.388000e+00
gross_profit_to_short_term_liabilities,5769.0,1.064381,35.637072,-2.318500e+02,2.470300e+03
gross_profit_plus_depreciation_to_sales,5790.0,0.359682,31.237561,-3.103400e+02,2.340200e+03
gross_profit_plus_interest_to_total_assets,5787.0,-0.115885,9.150503,-5.174800e+02,5.530000e+00
liabilities_days_ratio,5784.0,1047.365984,131468.435263,-9.632400e+06,1.341700e+06
gross_profit_plus_depreciation_to_total_liabilities,5772.0,1.166713,37.674032,-2.213300e+02,2.837400e+03
total_assets_to_total_liabilities,5772.0,6.835386,103.406737,-2.321000e-03,6.869500e+03
gross_profit_to_total_assets,5787.0,-0.106386,9.179270,-5.174800e+02,5.512500e+01
gross_profit_to_sales,5790.0,-0.093315,5.500968,-3.108000e+02,7.724400e+01
inventory_days_ratio,5790.0,56.858686,169.747013,-2.934000e+01,9.928500e+03
sales_growth_ratio,5687.0,2.487324,101.608010,-1.351500e+02,7.661500e+03
operating_profit_to_total_assets,5787.0,-0.006131,5.690662,-4.315900e+02,1.554100e+01
net_profit_to_sales,5790.0,-0.099886,5.474193,-3.108900e+02,7.724400e+01
three_year_gross_profit_to_total_assets,5655.0,0.137464,7.441703,-4.638900e+02,2.523400e+02
equity_minus_share_capital_to_total_assets,5787.0,0.371925,4.177782,-7.144400e+01,2.668600e+02
net_profit_plus_depreciation_to_total_liabilities,5772.0,1.071154,35.726914,-2.213300e+02,2.689100e+03
operating_profit_to_financial_expenses,5401.0,473.342862,10331.483820,-1.581300e+05,5.659400e+05
working_capital_to_fixed_assets,5685.0,10.355702,305.390255,-1.089700e+03,2.170100e+04
log_total_assets,5787.0,4.143160,0.834145,6.359000e-03,9.698300e+00
net_liabilities_to_sales,5790.0,0.860296,19.273969,-2.306000e+01,1.236700e+03
gross_profit_plus_interest_to_sales,5790.0,-0.068556,5.312490,-3.108000e+02,7.724400e+01
current_liabilities_days_ratio,5744.0,663.461947,31236.978938,-2.551000e+02,2.340500e+06
operating_expenses_to_short_term_liabilities,5769.0,8.392432,103.436070,-1.433400e+00,7.590500e+03
operating_expenses_to_total_liabilities,5772.0,5.068486,101.268843,-1.601500e+01,7.590500e+03
sales_profit_to_total_assets,5787.0,-0.009525,5.686602,-4.315900e+02,1.554100e+01
total_sales_to_total_assets,5787.0,2.061719,12.906769,1.910000e-04,9.656600e+02
current_assets_minus_inventories_to_long_term_liabilities,3288.0,116.036138,1614.856561,-4.325800e+00,6.792200e+04
constant_capital_to_total_assets,5787.0,0.652346,7.188380,-7.144400e+01,4.677700e+02
sales_profit_to_sales,5790.0,0.016032,0.716849,-4.704700e+01,2.901100e+00
liquid_assets_to_short_term_liabilities,5769.0,2.209357,58.301333,-9.068600e+00,4.303200e+03
liabilities_to_adjusted_operating_profit,5706.0,2.231404,83.955724,-2.699900e+02,5.043300e+03
operating_profit_to_sales,5790.0,-0.016517,2.462432,-1.435200e+02,4.038600e+01
receivables_plus_inventory_turnover_days,5790.0,156.204290,790.635019,-3.975600e+03,4.051500e+04
receivables_days_ratio,5790.0,99.345720,727.227485,-3.946200e+03,4.051500e+04
net_profit_to_inventory,5526.0,68.023004,4924.284145,-3.037300e+03,3.660300e+05
current_assets_minus_inventory_to_short_term_liabilities,5769.0,4.021593,92.214957,-9.049000e+00,6.845800e+03
inventory_days_cost_ratio,5755.0,137.701697,3310.273127,-1.865800e+01,1.856100e+05
ebitda_to_total_assets,5787.0,-0.092081,7.151658,-5.425600e+02,1.554100e+01
ebitda_to_sales,5790.0,-0.072699,2.481503,-1.448000e+02,1.686600e+01
current_assets_to_total_liabilities,5772.0,4.176926,91.877055,-1.217500e-02,6.845800e+03
short_term_liabilities_to_total_assets,5787.0,0.428809,1.102596,-1.866100e-01,7.241600e+01
short_term_liabilities_days_cost_ratio,5754.0,0.737896,12.990412,-6.976400e-01,6.661100e+02
equity_to_fixed_assets,5685.0,11.324293,317.636985,-1.088700e+03,2.170200e+04
constant_capital_to_fixed_assets,5685.0,12.252173,323.888823,-1.088700e+03,2.170200e+04
working_capital_absolute,5790.0,10654.957698,79955.386641,-1.118500e+06,4.212200e+06
gross_margin,5790.0,0.055561,0.704598,-4.678800e+01,1.651000e+00
adjusted_liquidity_ratio,5787.0,-0.268223,18.614482,-1.236300e+03,8.798100e+01
total_costs_to_total_sales,5790.0,0.958268,0.865608,-1.643900e-01,4.778800e+01
long_term_liabilities_to_equity,5787.0,0.269451,5.885054,-1.849800e+02,3.081500e+02
inventory_turnover_ratio,5526.0,929.800518,64824.540815,-1.244000e+01,4.818700e+06
receivables_turnover_ratio,5775.0,10.989177,41.521736,-9.249300e-02,1.308500e+03
short_term_liabilities_days_ratio,5790.0,245.143052,6285.238713,-2.365300e+02,4.513800e+05
sales_to_short_term_liabilities,5769.0,9.130587,104.108179,-1.543200e+00,7.641300e+03
sales_to_fixed_assets,5685.0,66.428330,2172.833224,-3.726500e+00,1.581800e+05

In [7]:
# Categorical Feature Statistics
cat_stats

                      value  count    pct
column           rank
company_bankrupt 1       No   5384  92.99
                 2      Yes    406   7.01

In [8]:
# Target Distribution
target_df

                  count    pct
company_bankrupt
No                 5384  92.99
Yes                 406   7.01

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to polish_companies_bankruptcy/019d9d2a-a55b-7465-b41d-7a7c3cc16d13
019d9d2a-a55b-7465-b41d-7a7c3cc16d13
891c33a6391bea681c6bfb6db2a5b8eeb1ea42b9534f085dba71ca58db521300