### Dataset and Task Metadata

In [2]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="drug_induced_autoimmunity_prediction",
    dataset_year="2025",
    domain_str="medical & healthcare",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C5332M",
    download_description="""
wget https://archive.ics.uci.edu/static/public/1104/drug_induced_autoimmunity_prediction.zip && unzip drug_induced_autoimmunity_prediction.zip && rm drug_induced_autoimmunity_prediction.zip RDKit_ChemDes.xlsx && mkdir -p local-data-warehouse/drug_induced_autoimmunity_prediction && mv DIA_trainingset_RDKit_descriptors.csv local-data-warehouse/drug_induced_autoimmunity_prediction/ && mv DIA_testset_RDKit_descriptors.csv local-data-warehouse/drug_induced_autoimmunity_prediction/
""",
    # References
    academic_reference_bibtex="""@article{huang2025interdia,
  title={InterDIA: Interpretable prediction of drug-induced autoimmunity through ensemble machine learning approaches},
  author={Huang, Lina and Liu, Peineng and Huang, Xiaojie},
  journal={Toxicology},
  volume={511},
  pages={154064},
  year={2025},
  publisher={Elsevier}
}
""",
    academic_reference_bibtex_key="huang2025interdia",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
We start with the dataset from UCI.

- We drop the constant columns.
- We keep the SMILES code as string for later pipelines to handle.

""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Label",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="Label",
)

## Preprocessing

In [10]:
import pandas as pd
import numpy as np

df = pd.read_csv(dataset_mold.path / "DIA_trainingset_RDKit_descriptors.csv")
df = pd.concat([df, pd.read_csv(dataset_mold.path / "DIA_testset_RDKit_descriptors.csv")], ignore_index=True)
print("Loaded data shape:", df.shape)

# Drop constant columns
constant_cols = df.columns[df.nunique(dropna=False) == 1]
df = df.drop(columns=constant_cols)

# dropping duplicated columns (by chance)
duplicated = ["fr_Nhpyrrole", "MaxEStateIndex", "fr_benzene"]
df = df.drop(columns=duplicated)

as_string_type = ["SMILES"]
as_cat_type = ["Label"]

for c in as_string_type:
    nan_mask = df[c].isna()
    df.loc[nan_mask, c] = np.nan
    df[c] = df[c].astype("string")
df[as_cat_type] = df[as_cat_type].astype("category")


df = df.sample(frac=1, random_state=42).reset_index(drop=True)

Loaded data shape: (597, 198)

## Data Checks

In [11]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 597
Columns: 178
Use sampling: False (sample size: 597)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['SMILES', 'MolMR', 'Chi1v', 'Chi2v', 'LabuteASA', 'BertzCT', 'Chi0v', 'MolWt', 'Chi1n', 'ExactMolWt']
Rows remaining as candidates after top-10 filter: 0 (of 597)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [12]:
# Sample Rows
df_head

,Label,SMILES,BalabanJ,BertzCT,Chi0,Chi0n,Chi0v,Chi1,Chi1n,Chi1v,Chi2n,Chi2v,Chi3n,Chi3v,Chi4n,Chi4v,EState_VSA1,EState_VSA10,EState_VSA11,EState_VSA2,EState_VSA3,EState_VSA4,EState_VSA5,EState_VSA6,EState_VSA7,EState_VSA8,EState_VSA9,ExactMolWt,FractionCSP3,HallKierAlpha,HeavyAtomCount,HeavyAtomMolWt,Ipc,Kappa1,Kappa2,Kappa3,LabuteASA,MaxAbsEStateIndex,MaxAbsPartialCharge,MaxPartialCharge,MinAbsEStateIndex,MinAbsPartialCharge,MinEStateIndex,MinPartialCharge,MolLogP,MolMR,MolWt,NHOHCount,NOCount,NumAliphaticCarbocycles,NumAliphaticHeterocycles,NumAliphaticRings,NumAromaticCarbocycles,NumAromaticHeterocycles,NumAromaticRings,NumHAcceptors,NumHDonors,NumHeteroatoms,NumRotatableBonds,NumSaturatedCarbocycles,NumSaturatedHeterocycles,NumSaturatedRings,NumValenceElectrons,PEOE_VSA1,PEOE_VSA10,PEOE_VSA11,PEOE_VSA12,PEOE_VSA13,PEOE_VSA14,PEOE_VSA2,PEOE_VSA3,PEOE_VSA4,PEOE_VSA5,PEOE_VSA6,PEOE_VSA7,PEOE_VSA8,PEOE_VSA9,RingCount,SMR_VSA1,SMR_VSA10,SMR_VSA2,SMR_VSA3,SMR_VSA4,SMR_VSA5,SMR_VSA6,SMR_VSA7,SMR_VSA9,SlogP_VSA1,SlogP_VSA10,SlogP_VSA11,SlogP_VSA12,SlogP_VSA2,SlogP_VSA3,SlogP_VSA4,SlogP_VSA5,SlogP_VSA6,SlogP_VSA7,SlogP_VSA8,TPSA,VSA_EState10,VSA_EState8,VSA_EState9,fr_Al_COO,fr_Al_OH,fr_Al_OH_noTert,fr_ArN,fr_Ar_COO,fr_Ar_N,fr_Ar_NH,fr_Ar_OH,fr_COO,fr_COO2,fr_C_O,fr_C_O_noCOO,fr_C_S,fr_HOCCN,fr_Imine,fr_NH0,fr_NH1,fr_NH2,fr_N_O,fr_Ndealkylation1,fr_Ndealkylation2,fr_SH,fr_aldehyde,fr_alkyl_carbamate,fr_alkyl_halide,fr_allylic_oxid,fr_amide,fr_amidine,fr_aniline,fr_aryl_methyl,fr_azo,fr_benzodiazepine,fr_bicyclic,fr_dihydropyridine,fr_epoxide,fr_ester,fr_ether,fr_furan,fr_guanido,fr_halogen,fr_hdrzine,fr_hdrzone,fr_imidazole,fr_imide,fr_ketone,fr_ketone_Topliss,fr_lactam,fr_lactone,fr_methoxy,fr_morpholine,fr_nitrile,fr_nitro,fr_nitro_arom,fr_nitro_arom_nonortho,fr_nitroso,fr_oxazole,fr_oxime,fr_para_hydroxylation,fr_phenol,fr_phenol_noOrthoHbond,fr_phos_acid,fr_phos_ester,fr_piperdine,fr_piperzine,fr_priamide,fr_pyridine,fr_quatN,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiophene,fr_unbrch_alkane,fr_urea
0,1,OCCN1CCN(CCCN2c3ccccc3Sc4ccc(Cl)cc24)CC1,1.410,779.772,18.640,15.480,17.053,13.242,9.640,10.834,7.094,8.614,5.325,6.690,3.874,5.116,0.000,0.000,0.0,6.607,0.000,57.257,21.166,0.000,17.828,51.098,16.707,403.149,0.429,-1.24,27,377.771,2100937.376,19.093,8.842,4.438,170.261,9.078,0.395,0.057,0.258,0.057,0.258,-0.395,3.943,113.606,403.979,1,4,0,2,2,2,0,2,5,1,6,6,0,1,1,144,14.906,0.000,0.000,0.000,0.0,0.000,4.900,0.000,0.0,0.0,35.496,43.297,54.082,17.982,4,5.107,34.738,0.0,9.8,0.000,16.212,57.320,47.487,0.0,4.900,11.375,0.0,23.363,67.327,0.000,0.000,6.421,52.256,5.023,0.0,29.95,8.122,0.000,45.656,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,3,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,2,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,1,NC(=O)Cc1cccc(C(=O)c2ccccc2)c1N,2.406,621.298,13.828,10.297,10.297,9.092,5.847,5.847,4.217,4.217,2.842,2.842,1.898,1.898,5.907,9.589,0.0,12.204,22.378,0.000,0.000,42.465,6.066,0.000,11.467,254.106,0.067,-2.62,19,240.177,20828.746,12.827,5.351,2.796,110.586,12.309,0.398,0.221,0.030,0.221,-0.476,-0.398,1.528,73.627,254.289,4,4,0,0,0,2,0,2,3,2,4,4,0,0,0,96,11.467,0.000,5.783,5.907,0.0,0.000,9.589,0.000,0.0,0.0,42.465,11.630,16.814,6.421,2,9.589,17.378,0.0,0.0,5.734,6.421,5.734,65.221,0.0,11.467,5.687,0.0,0.000,11.690,11.215,0.000,21.485,48.531,0.000,0.0,86.18,0.000,0.000,49.500,0,0,0,1,0,0,0,0,0,0,2,2,0,0,0,0,0,2,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,1,OC(=O)[C@@H]1C[C@H](CN1C(=O)CP(=O)(O)CCCCc2ccccc2)C3CCCCC3,1.501,762.117,21.562,17.618,18.512,14.355,11.226,13.256,8.965,11.421,6.703,8.483,5.039,6.519,31.449,24.154,0.0,12.080,25.304,25.683,29.726,0.000,30.332,0.000,0.000,435.217,0.652,-1.65,30,401.229,5910365.206,23.022,10.588,6.422,178.671,12.789,0.480,0.326,0.100,0.326,-3.615,-0.480,4.162,116.758,435.501,2,6,1,1,2,1,0,1,3,2,7,10,1,1,2,166,14.900,12.204,0.000,13.276,0.0,5.969,9.360,4.795,0.0,0.0,62.436,43.083,12.707,0.000,3,24.154,19.245,0.0,4.9,11.836,63.829,18.869,35.895,0.0,0.000,0.000,0.0,7.369,51.687,20.575,11.836,56.930,30.332,0.000,0.0,94.91,0.000,12.613,60.193,1,0,0,0,0,0,0,0,1,1,2,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,1,CC[C@H](C)C(=O)O[C@@H]1C[C@H](C)C=C2C=C[C@H](C)[C@H](CC[C@@H]3C[C@H](O)CC(=O)O3)[C@H]12,1.740,666.182,21.129,18.174,18.174,13.778,11.259,11.259,9.355,9.355,6.935,6.935,5.070,5.070,6.104,14.696,0.0,42.403,24.175,25.683,5.573,0.000,13.847,32.076,9.474,404.256,0.750,-1.62,29,368.259,2389463.979,22.074,9.461,5.302,174.081,12.544,0.462,0.308,0.085,0.308,-0.597,-0.462,4.196,110.838,404.547,1,5,2,1,3,0,0,0,5,1,5,7,0,1,1,162,14.580,12.208,0.000,0.000,0.0,11.939,9.589,0.000,0.0,0.0,45.923,49.010,12.339,18.443,3,24.169,11.939,0.0,0.0,29.590,84.532,0.000,23.801,0.0,0.000,0.000,0.0,0.000,35.357,19.063,29.590,66.220,23.801,0.000,0.0,72.83,0.000,0.000,65.667,0,1,1,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,1,0,0,2,2,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1,CC[C@H](C)C(=O)O[C@H]1C[C@@H](C)C=C2C=C[C@H](C)[C@H](CC[C@@H]3C[C@@H](O)CC(=O)O3)[C@@H]12,1.740,666.182,21.129,18.174,18.174,13.778,11.259,11.259,9.355,9.355,6.935,6.935,5.070,5.070,6.104,14.696,0.0,42.403,24.175,25.683,5.573,0.000,13.847,32.076,9.474,404.256,0.750,-1.62,29,368.259,2389463.979,22.074,9.461,5.302,174.081,12.544,0.462,0.308,0.085,0.308,-0.597,-0.462,4.196,110.838,404.547,1,5,2,1,3,0,0,0,5,1,5,7,0,1,1,162,14.580,12.208,0.000,0.000,0.0,11.939,9.589,0.000,0.0,0.0,45.923,49.010,12.339,18.443,3,24.169,11.939,0.0,0.0,29.590,84.532,0.000,23.801,0.0,0.000,0.000,0.0,0.000,35.357,19.063,29.590,66.220,23.801,0.000,0.0,72.83,0.000,0.000,65.667,0,1,1,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,1,0,0,2,2,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [13]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Label,category,0.0,0.0,2.0,"0, 1"
1,BalabanJ,float64,0.0,0.0,487.0,"1.838, 1.735, 2.195, 2.462, 2.218, 2.079, 1.85, 1.43, 1.384, 1.797"
2,BertzCT,float64,0.0,0.0,575.0,"682.154, 983.598, 400.94, 593.895, 49.784, 431.802, 760.387, 666.182, 1053.003, 804.749"
3,Chi0,float64,0.0,0.0,449.0,"10.836, 20.698, 13.828, 12.345, 22.422, 16.397, 11.707, 12.958, 23.859, 15.267"
4,Chi0n,float64,0.0,0.0,570.0,"17.145, 16.613, 17.935, 14.202, 13.404, 19.777, 14.059, 4.957, 4.331, 18.174"
5,Chi0v,float64,0.0,0.0,571.0,"13.404, 16.626, 21.884, 20.593, 13.542, 14.059, 20.6, 14.202, 16.995, 18.174"
6,Chi1,float64,0.0,0.0,515.0,"12.963, 14.867, 4.877, 9.665, 4.5, 9.075, 14.918, 11.952, 4.164, 6.914"
7,Chi1n,float64,0.0,0.0,570.0,"4.609, 11.259, 1.982, 8.308, 8.683, 6.728, 9.823, 7.049, 2.745, 9.128"
8,Chi1v,float64,0.0,0.0,577.0,"12.377, 5.98, 9.298, 7.771, 12.729, 11.19, 3.683, 8.683, 9.128, 9.926"
9,Chi2n,float64,0.0,0.0,565.0,"7.662, 6.974, 7.441, 5.461, 3.781, 5.49, 8.304, 2.667, 5.397, 9.355"
10,Chi2v,float64,0.0,0.0,576.0,"8.484, 7.441, 11.478, 6.101, 10.368, 4.764, 5.714, 6.974, 7.662, 3.781"
11,Chi3n,float64,0.0,0.0,563.0,"0.0, 2.506, 2.388, 4.998, 6.935, 0.48, 3.517, 5.766, 8.791, 4.778"
12,Chi3v,float64,0.0,0.0,567.0,"0.0, 6.935, 5.998, 5.819, 6.305, 5.911, 6.899, 0.635, 7.798, 4.998"
13,Chi4n,float64,0.0,0.0,557.0,"0.0, 1.276, 4.444, 0.17, 1.32, 1.904, 3.17, 6.96, 3.377, 3.531"
14,Chi4v,float64,0.0,0.0,554.0,"0.0, 1.276, 3.377, 4.82, 1.131, 8.416, 1.527, 1.425, 2.621, 3.409"
15,EState_VSA1,float64,0.0,0.0,251.0,"0.0, 6.104, 5.969, 5.601, 11.57, 30.064, 10.023, 17.12, 11.939, 24.095"
16,EState_VSA10,float64,0.0,0.0,122.0,"0.0, 4.795, 9.589, 9.901, 5.107, 14.696, 19.49, 24.597, 19.802, 14.384"
17,EState_VSA11,float64,0.0,0.0,5.0,"0.0, 4.39, 8.781, 13.575, 4.795"
18,EState_VSA2,float64,0.0,0.0,334.0,"0.0, 5.907, 6.104, 6.607, 11.949, 6.042, 6.421, 5.918, 5.817, 5.415"
19,EState_VSA3,float64,0.0,0.0,291.0,"0.0, 5.563, 6.421, 6.545, 19.262, 6.607, 5.918, 12.108, 5.687, 6.042"
20,EState_VSA4,float64,0.0,0.0,284.0,"0.0, 5.563, 11.127, 25.683, 6.421, 19.262, 6.076, 5.573, 38.525, 12.842"
21,EState_VSA5,float64,0.0,0.0,209.0,"0.0, 4.9, 5.563, 12.133, 11.127, 6.924, 6.066, 7.11, 6.421, 12.152"
22,EState_VSA6,float64,0.0,0.0,147.0,"0.0, 12.133, 6.924, 6.066, 24.265, 13.847, 7.11, 4.9, 18.199, 6.197"
23,EState_VSA7,float64,0.0,0.0,144.0,"0.0, 30.332, 13.847, 6.924, 6.066, 12.133, 24.265, 6.076, 18.199, 20.771"
24,EState_VSA8,float64,0.0,0.0,274.0,"0.0, 5.317, 10.634, 6.924, 4.984, 10.301, 9.968, 4.992, 13.847, 4.9"
25,EState_VSA9,float64,0.0,0.0,148.0,"0.0, 4.737, 9.474, 5.734, 5.107, 11.601, 16.338, 9.843, 14.211, 10.471"
26,ExactMolWt,float64,0.0,0.0,570.0,"226.095, 404.256, 411.185, 324.184, 434.21, 415.272, 392.21, 263.189, 285.136, 500.184"
27,FractionCSP3,float64,0.0,0.0,195.0,"1.0, 0.5, 0.0, 0.333, 0.4, 0.429, 0.125, 0.75, 0.294, 0.667"
28,HallKierAlpha,float64,0.0,0.0,279.0,"-2.41, -1.59, -2.33, -1.06, -2.62, -1.3, -0.9, -1.51, -1.1, -1.26"
29,HeavyAtomMolWt,float64,0.0,0.0,507.0,"320.215, 420.248, 238.181, 266.191, 282.19, 212.12, 226.17, 314.235, 278.202, 290.213"
30,Ipc,float64,0.0,0.0,554.0,"1500075.637, 88.552, 271685.711, 8427682.936, 78.513, 280153.657, 209851.397, 512499.659, 372.422, 3.61"
31,Kappa1,float64,0.0,0.0,553.0,"22.001, 25.482, 11.813, 21.517, 10.39, 21.436, 16.313, 12.28, 21.742, 21.519"
32,Kappa2,float64,0.0,0.0,568.0,"6.893, 9.461, 9.238, 8.053, 6.188, 5.931, 9.303, 1.125, 4.242, 4.081"
33,Kappa3,float64,0.0,0.0,551.0,"2.478, 2.138, 2.885, 2.502, 2.947, 7.03, 5.302, 3.286, 0.407, 2.332"
34,LabuteASA,float64,0.0,0.0,575.0,"182.429, 170.622, 201.107, 183.524, 181.029, 120.331, 28.307, 174.081, 142.313, 174.259"
35,MaxAbsEStateIndex,float64,0.0,0.0,558.0,"12.341, 12.61, 13.498, 13.741, 12.531, 13.051, 13.083, 2.335, 17.14, 11.152"
36,MaxAbsPartialCharge,float64,0.0,0.0,181.0,"0.481, 0.508, 0.493, 0.48, 0.394, 0.504, 0.393, 0.462, 0.507, 0.369"
37,MaxPartialCharge,float64,0.0,0.0,247.0,"0.326, 0.303, 0.306, 0.119, 0.339, 0.224, 0.255, 0.407, 0.174, 0.416"
38,MinAbsEStateIndex,float64,0.0,0.0,318.0,"0.013, 0.008, 0.016, 0.004, 0.017, 0.006, 0.045, 0.003, 0.022, 0.054"
39,MinAbsPartialCharge,float64,0.0,0.0,238.0,"0.326, 0.306, 0.303, 0.119, 0.224, 0.339, 0.407, 0.316, 0.255, 0.174"
40,MinEStateIndex,float64,0.0,0.0,539.0,"-1.316, -0.594, -0.597, -0.598, -0.987, -1.299, -1.02, 0.483, 0.688, -1.031"
41,MinPartialCharge,float64,0.0,0.0,172.0,"-0.481, -0.493, -0.508, -0.48, -0.394, -0.504, -0.393, -0.462, -0.39, -0.507"
42,MolLogP,float64,0.0,0.0,565.0,"2.44, -0.053, 4.628, 3.173, 3.383, -3.493, 1.63, 4.17, 1.418, 1.396"
43,MolMR,float64,0.0,0.0,586.0,"120.868, 115.634, 95.027, 56.84, 23.325, 100.153, 111.443, 108.387, 98.485, 110.838"
44,MolWt,float64,0.0,0.0,570.0,"226.232, 404.547, 411.473, 324.424, 434.504, 415.574, 392.499, 263.381, 285.343, 500.579"
45,PEOE_VSA1,float64,0.0,0.0,246.0,"0.0, 9.843, 5.317, 5.107, 10.213, 14.743, 9.637, 4.737, 5.734, 15.32"
46,PEOE_VSA10,float64,0.0,0.0,179.0,"0.0, 5.75, 6.104, 12.084, 6.607, 5.601, 6.042, 5.783, 18.46, 12.208"
47,PEOE_VSA11,float64,0.0,0.0,97.0,"0.0, 11.499, 5.783, 5.96, 11.566, 11.384, 6.104, 23.386, 5.132, 9.837"
48,PEOE_VSA12,float64,0.0,0.0,53.0,"0.0, 5.907, 11.814, 5.783, 10.023, 5.948, 5.88, 5.429, 5.601, 5.824"
49,PEOE_VSA13,float64,0.0,0.0,30.0,"0.0, 5.907, 11.814, 5.559, 5.687, 10.023, 5.083, 5.239, 6.2, 17.722"
50,PEOE_VSA14,float64,0.0,0.0,58.0,"0.0, 5.969, 11.939, 6.093, 5.69, 6.176, 6.031, 15.192, 17.908, 12.063"
51,PEOE_VSA2,float64,0.0,0.0,104.0,"0.0, 4.795, 9.589, 14.384, 4.9, 9.694, 14.906, 4.567, 9.779, 10.114"
52,PEOE_VSA3,float64,0.0,0.0,72.0,"0.0, 4.795, 4.984, 4.39, 9.589, 9.779, 8.418, 9.185, 4.992, 13.557"
53,PEOE_VSA4,float64,0.0,0.0,47.0,"0.0, 5.262, 13.171, 5.099, 4.984, 4.992, 12.629, 8.418, 5.213, 4.305"
54,PEOE_VSA5,float64,0.0,0.0,26.0,"0.0, 11.337, 11.762, 10.197, 11.601, 5.099, 6.579, 6.423, 23.099, 22.674"
55,PEOE_VSA6,float64,0.0,0.0,214.0,"0.0, 12.133, 6.066, 30.332, 18.199, 11.601, 24.265, 42.465, 6.924, 13.847"
56,PEOE_VSA7,float64,0.0,0.0,376.0,"0.0, 6.924, 12.133, 18.199, 17.696, 6.421, 12.842, 30.332, 25.123, 6.066"
57,PEOE_VSA8,float64,0.0,0.0,346.0,"0.0, 6.421, 6.545, 5.687, 6.042, 16.748, 11.836, 12.966, 5.563, 12.587"
58,PEOE_VSA9,float64,0.0,0.0,288.0,"0.0, 6.104, 6.607, 12.208, 6.042, 6.545, 12.649, 11.375, 5.918, 5.694"
59,SMR_VSA1,float64,0.0,0.0,247.0,"0.0, 4.795, 9.901, 14.638, 9.531, 4.737, 9.589, 24.597, 9.843, 14.696"
60,SMR_VSA10,float64,0.0,0.0,298.0,"0.0, 5.969, 5.907, 11.566, 17.846, 11.753, 11.939, 5.783, 11.595, 11.814"
61,SMR_VSA2,float64,0.0,0.0,6.0,"0.0, 5.262, 10.524, 5.409, 5.594, 10.819"
62,SMR_VSA3,float64,0.0,0.0,98.0,"0.0, 4.9, 5.317, 10.217, 4.984, 9.551, 9.884, 9.968, 10.301, 9.8"
63,SMR_VSA4,float64,0.0,0.0,58.0,"0.0, 5.918, 5.734, 28.584, 11.836, 4.992, 17.569, 34.502, 5.139, 23.672"
64,SMR_VSA5,float64,0.0,0.0,366.0,"0.0, 6.421, 18.883, 13.847, 12.842, 12.966, 13.468, 6.924, 19.262, 6.104"
65,SMR_VSA6,float64,0.0,0.0,184.0,"0.0, 6.607, 6.545, 13.09, 13.152, 5.317, 14.095, 13.214, 7.11, 13.592"
66,SMR_VSA7,float64,0.0,0.0,296.0,"0.0, 23.801, 35.895, 29.326, 29.829, 23.26, 23.763, 11.649, 65.221, 65.724"
67,SMR_VSA9,float64,0.0,0.0,40.0,"0.0, 5.75, 11.499, 6.069, 5.687, 17.249, 11.257, 11.841, 12.344, 5.88"
68,SlogP_VSA1,float64,0.0,0.0,110.0,"0.0, 5.317, 4.737, 5.734, 4.9, 10.634, 10.054, 11.05, 9.474, 14.791"
69,SlogP_VSA10,float64,0.0,0.0,53.0,"0.0, 5.687, 4.39, 4.795, 11.375, 5.818, 13.171, 8.781, 5.132, 11.766"
70,SlogP_VSA11,float64,0.0,0.0,14.0,"0.0, 5.75, 11.499, 17.249, 5.88, 22.998, 28.748, 34.497, 11.63, 40.247"
71,SlogP_VSA12,float64,0.0,0.0,39.0,"0.0, 11.601, 11.762, 11.337, 23.202, 7.823, 15.93, 7.596, 12.629, 15.192"
72,SlogP_VSA2,float64,0.0,0.0,525.0,"9.968, 11.076, 17.621, 16.182, 26.828, 9.551, 11.566, 16.491, 58.626, 6.042"
73,SlogP_VSA3,float64,0.0,0.0,185.0,"0.0, 4.795, 9.589, 11.215, 6.421, 4.737, 19.063, 6.545, 14.326, 14.384"
74,SlogP_VSA4,float64,0.0,0.0,73.0,"0.0, 5.918, 11.836, 6.924, 28.584, 13.847, 5.817, 10.114, 34.502, 11.331"
75,SlogP_VSA5,float64,0.0,0.0,307.0,"0.0, 5.563, 11.127, 6.924, 12.842, 12.487, 10.358, 23.969, 19.411, 6.421"
76,SlogP_VSA6,float64,0.0,0.0,205.0,"0.0, 18.199, 30.332, 23.801, 24.265, 42.465, 48.531, 12.133, 54.597, 36.398"
77,SlogP_VSA7,float64,0.0,0.0,8.0,"0.0, 5.023, 10.045, 15.068, 5.153, 20.091, 4.336, 5.284"
78,SlogP_VSA8,float64,0.0,0.0,56.0,"0.0, 10.903, 11.164, 11.033, 5.759, 5.573, 11.257, 6.076, 5.687, 10.772"
79,TPSA,float64,0.0,0.0,428.0,"46.53, 54.37, 95.94, 94.83, 106.94, 49.77, 3.24, 6.48, 93.06, 12.47"
80,VSA_EState10,float64,0.0,0.0,187.0,"0.0, 1.242, 6.082, 0.396, 1.527, 1.542, 5.42, 4.348, 9.455, 1.843"
81,VSA_EState8,float64,0.0,0.0,230.0,"0.0, 46.02, 0.902, 15.642, 22.447, 65.968, 16.816, 40.801, 23.08, 28.546"
82,VSA_EState9,float64,0.0,0.0,550.0,"49.5, 46.667, 49.833, 51.333, 47.667, 65.667, 75.667, 48.917, 49.667, 74.333"
83,HeavyAtomCount,int64,0.0,0.0,56.0,"25, 30, 22, 19, 27, 23, 32, 24, 28, 29"
84,NHOHCount,int64,0.0,0.0,14.0,"1, 2, 0, 3, 4, 5, 6, 7, 8, 10"
85,NOCount,int64,0.0,0.0,22.0,"4, 5, 3, 6, 7, 2, 8, 9, 1, 10"
86,NumAliphaticCarbocycles,int64,0.0,0.0,6.0,"0, 1, 4, 3, 2, 5"
87,NumAliphaticHeterocycles,int64,0.0,0.0,8.0,"0, 1, 2, 3, 4, 6, 5, 7"
88,NumAliphaticRings,int64,0.0,0.0,9.0,"0, 1, 2, 4, 3, 5, 6, 7, 8"
89,NumAromaticCarbocycles,int64,0.0,0.0,5.0,"1, 0, 2, 3, 4"
90,NumAromaticHeterocycles,int64,0.0,0.0,6.0,"0, 1, 2, 3, 4, 5"
91,NumAromaticRings,int64,0.0,0.0,7.0,"1, 2, 0, 3, 4, 5, 8"
92,NumHAcceptors,int64,0.0,0.0,21.0,"4, 3, 5, 2, 6, 7, 1, 8, 9, 11"
93,NumHDonors,int64,0.0,0.0,13.0,"1, 2, 0, 3, 4, 5, 6, 8, 12, 9"
94,NumHeteroatoms,int64,0.0,0.0,22.0,"5, 7, 4, 6, 3, 8, 9, 2, 10, 11"
95,NumRotatableBonds,int64,0.0,0.0,26.0,"2, 4, 5, 6, 3, 1, 8, 7, 11, 10"
96,NumSaturatedCarbocycles,int64,0.0,0.0,6.0,"0, 1, 3, 2, 4, 5"
97,NumSaturatedHeterocycles,int64,0.0,0.0,6.0,"0, 1, 2, 3, 4, 5"
98,NumSaturatedRings,int64,0.0,0.0,8.0,"0, 1, 2, 3, 4, 5, 6, 7"
99,NumValenceElectrons,int64,0.0,0.0,123.0,"132, 170, 164, 154, 108, 112, 138, 116, 158, 150"
100,RingCount,int64,0.0,0.0,11.0,"3, 2, 4, 1, 5, 0, 6, 7, 8, 9"
101,fr_Al_COO,int64,0.0,0.0,5.0,"0, 1, 2, 3, 5"
102,fr_Al_OH,int64,0.0,0.0,10.0,"0, 1, 2, 3, 4, 5, 6, 7, 11, 8"
103,fr_Al_OH_noTert,int64,0.0,0.0,9.0,"0, 1, 2, 3, 5, 6, 4, 11, 8"
104,fr_ArN,int64,0.0,0.0,3.0,"0, 1, 2"
105,fr_Ar_COO,int64,0.0,0.0,3.0,"0, 1, 2"
106,fr_Ar_N,int64,0.0,0.0,7.0,"0, 1, 2, 4, 3, 6, 5"
107,fr_Ar_NH,int64,0.0,0.0,3.0,"0, 1, 2"
108,fr_Ar_OH,int64,0.0,0.0,4.0,"0, 1, 2, 4"
109,fr_COO,int64,0.0,0.0,6.0,"0, 1, 2, 3, 5, 4"
110,fr_COO2,int64,0.0,0.0,6.0,"0, 1, 2, 3, 5, 4"
111,fr_C_O,int64,0.0,0.0,8.0,"0, 1, 2, 3, 4, 5, 6, 10"
112,fr_C_O_noCOO,int64,0.0,0.0,8.0,"0, 1, 2, 3, 4, 5, 6, 10"
113,fr_C_S,int64,0.0,0.0,2.0,"0, 1"
114,fr_HOCCN,int64,0.0,0.0,3.0,"0, 1, 2"
115,fr_Imine,int64,0.0,0.0,4.0,"0, 1, 2, 4"
116,fr_NH0,int64,0.0,0.0,8.0,"0, 1, 2, 3, 4, 5, 6, 7"
117,fr_NH1,int64,0.0,0.0,7.0,"0, 1, 2, 3, 4, 6, 7"
118,fr_NH2,int64,0.0,0.0,6.0,"0, 1, 2, 4, 3, 5"
119,fr_N_O,int64,0.0,0.0,4.0,"0, 1, 2, 6"
120,fr_Ndealkylation1,int64,0.0,0.0,3.0,"0, 1, 2"
121,fr_Ndealkylation2,int64,0.0,0.0,3.0,"0, 1, 2"
122,fr_SH,int64,0.0,0.0,2.0,"0, 1"
123,fr_aldehyde,int64,0.0,0.0,3.0,"0, 1, 2"
124,fr_alkyl_carbamate,int64,0.0,0.0,3.0,"0, 1, 2"
125,fr_alkyl_halide,int64,0.0,0.0,8.0,"0, 1, 3, 2, 6, 7, 5, 8"
126,fr_allylic_oxid,int64,0.0,0.0,8.0,"0, 4, 2, 1, 3, 5, 12, 6"
127,fr_amide,int64,0.0,0.0,8.0,"0, 1, 2, 3, 4, 5, 6, 10"
128,fr_amidine,int64,0.0,0.0,3.0,"0, 1, 2"
129,fr_aniline,int64,0.0,0.0,5.0,"0, 1, 2, 3, 4"
130,fr_aryl_methyl,int64,0.0,0.0,6.0,"0, 1, 2, 3, 5, 7"
131,fr_azo,int64,0.0,0.0,2.0,"0, 1"
132,fr_benzodiazepine,int64,0.0,0.0,2.0,"0, 1"
133,fr_bicyclic,int64,0.0,0.0,11.0,"0, 1, 5, 2, 3, 7, 6, 4, 8, 9"
134,fr_dihydropyridine,int64,0.0,0.0,2.0,"0, 1"
135,fr_epoxide,int64,0.0,0.0,2.0,"0, 1"
136,fr_ester,int64,0.0,0.0,5.0,"0, 1, 2, 3, 4"
137,fr_ether,int64,0.0,0.0,11.0,"0, 1, 2, 3, 4, 5, 6, 7, 10, 9"
138,fr_furan,int64,0.0,0.0,2.0,"0, 1"
139,fr_guanido,int64,0.0,0.0,4.0,"0, 1, 2, 4"
140,fr_halogen,int64,0.0,0.0,9.0,"0, 1, 2, 3, 4, 6, 5, 7, 8"
141,fr_hdrzine,int64,0.0,0.0,2.0,"0, 1"
142,fr_hdrzone,int64,0.0,0.0,2.0,"0, 1"
143,fr_imidazole,int64,0.0,0.0,3.0,"0, 1, 2"
144,fr_imide,int64,0.0,0.0,3.0,"0, 1, 2"
145,fr_ketone,int64,0.0,0.0,4.0,"0, 1, 2, 3"
146,fr_ketone_Topliss,int64,0.0,0.0,4.0,"0, 1, 2, 3"
147,fr_lactam,int64,0.0,0.0,2.0,"0, 1"
148,fr_lactone,int64,0.0,0.0,2.0,"0, 1"
149,fr_methoxy,int64,0.0,0.0,6.0,"0, 1, 2, 3, 6, 8"
150,fr_morpholine,int64,0.0,0.0,2.0,"0, 1"
151,fr_nitrile,int64,0.0,0.0,3.0,"0, 1, 2"
152,fr_nitro,int64,0.0,0.0,3.0,"0, 1, 2"
153,fr_nitro_arom,int64,0.0,0.0,3.0,"0, 1, 2"
154,fr_nitro_arom_nonortho,int64,0.0,0.0,2.0,"0, 1"
155,fr_nitroso,int64,0.0,0.0,2.0,"0, 1"
156,fr_oxazole,int64,0.0,0.0,2.0,"0, 1"
157,fr_oxime,int64,0.0,0.0,2.0,"0, 1"
158,fr_para_hydroxylation,int64,0.0,0.0,4.0,"0, 1, 2, 3"
159,fr_phenol,int64,0.0,0.0,5.0,"0, 1, 2, 3, 4"
160,fr_phenol_noOrthoHbond,int64,0.0,0.0,5.0,"0, 1, 2, 3, 4"
161,fr_phos_acid,int64,0.0,0.0,3.0,"0, 1, 2"
162,fr_phos_ester,int64,0.0,0.0,3.0,"0, 1, 2"
163,fr_piperdine,int64,0.0,0.0,5.0,"0, 1, 3, 2, 4"
164,fr_piperzine,int64,0.0,0.0,3.0,"0, 1, 2"
165,fr_priamide,int64,0.0,0.0,3.0,"0, 1, 2"
166,fr_pyridine,int64,0.0,0.0,3.0,"0, 1, 2"
167,fr_quatN,int64,0.0,0.0,3.0,"0, 1, 2"
168,fr_sulfide,int64,0.0,0.0,3.0,"0, 1, 2"
169,fr_sulfonamd,int64,0.0,0.0,3.0,"0, 1, 2"
170,fr_sulfone,int64,0.0,0.0,2.0,"0, 1"
171,fr_term_acetylene,int64,0.0,0.0,2.0,"0, 1"
172,fr_tetrazole,int64,0.0,0.0,2.0,"0, 1"
173,fr_thiazole,int64,0.0,0.0,3.0,"0, 1, 2"
174,fr_thiophene,int64,0.0,0.0,3.0,"0, 1, 2"
175,fr_unbrch_alkane,int64,0.0,0.0,11.0,"0, 1, 2, 4, 3, 6, 9, 10, 5, 8"
176,fr_urea,int64,0.0,0.0,2.0,"0, 1"
177,SMILES,string,0.0,0.0,597.0,"CC(C)NC[C@H](O)COc1cccc2[nH]ccc12, OCCN1CCN(CCCN2c3ccccc3Sc4ccc(Cl)cc24)CC1, NC(=O)Cc1cccc(C(=O)c2ccccc2)c1N, OC(=O)[C@@H]1C[C@H](CN1C(=O)CP(=O)(O)CCCCc2ccccc2)C3CCCCC3, CC[C@H](C)C(=O)O[C@@H]1C[C@H](C)C=C2C=C[C@H](C)[C@H](CC[C@@H]3C[C@H](O)CC(=O)O3)[C@H]12, CC[C@H](C)C(=O)O[C@H]1C[C@@H](C)C=C2C=C[C@H](C)[C@H](CC[C@@H]3C[C@@H](O)CC(=O)O3)[C@@H]12, FC(F)O[C@H](F)C(F)(F)F, CCN(CC)CC(=O)Nc1c(C)cccc1C, CCCNC[C@H](O)COc1ccccc1C(=O)CCc2ccccc2, COc1cc(cc(OC)c1O)c2[o+]c3cc(O)cc(O)c3cc2O"

In [14]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
BalabanJ,597.0,2.143109e+00,7.242450e-01,0.837,5.083000e+00
BertzCT,597.0,7.521650e+02,4.042390e+02,2.000,2.629395e+03
Chi0,597.0,1.844259e+01,7.352206e+00,2.000,5.012000e+01
Chi0n,597.0,1.463103e+01,6.153925e+00,0.908,4.132800e+01
Chi0v,597.0,1.513229e+01,6.204312e+00,0.908,4.132800e+01
Chi1,597.0,1.207100e+01,4.895135e+00,1.000,3.235000e+01
Chi1n,597.0,8.573367e+00,3.778853e+00,0.204,2.326900e+01
Chi1v,597.0,9.076570e+00,3.838328e+00,0.204,2.444000e+01
Chi2n,597.0,6.800184e+00,3.322090e+00,0.000,1.935200e+01
Chi2v,597.0,7.351312e+00,3.375425e+00,0.000,1.961500e+01
Chi3n,597.0,4.944434e+00,2.799888e+00,0.000,1.595200e+01
Chi3v,597.0,5.395913e+00,2.848818e+00,0.000,1.595200e+01
Chi4n,597.0,3.621070e+00,2.335903e+00,0.000,1.323600e+01
Chi4v,597.0,3.993571e+00,2.395207e+00,0.000,1.323600e+01
EState_VSA1,597.0,1.875925e+01,2.397713e+01,0.000,1.556720e+02
EState_VSA10,597.0,1.350579e+01,1.101552e+01,0.000,5.871900e+01
EState_VSA11,597.0,2.146164e-01,1.224024e+00,0.000,1.357500e+01
EState_VSA2,597.0,1.599812e+01,1.408235e+01,0.000,9.678100e+01
EState_VSA3,597.0,1.539934e+01,1.368033e+01,0.000,1.069490e+02
EState_VSA4,597.0,1.943097e+01,1.814033e+01,0.000,1.178060e+02
EState_VSA5,597.0,1.294959e+01,1.436296e+01,0.000,1.219960e+02
EState_VSA6,597.0,1.168614e+01,1.386843e+01,0.000,9.271000e+01
EState_VSA7,597.0,1.640658e+01,1.870743e+01,0.000,9.369800e+01
EState_VSA8,597.0,1.598869e+01,1.696075e+01,0.000,9.083000e+01
EState_VSA9,597.0,1.047414e+01,1.061935e+01,0.000,6.960600e+01
ExactMolWt,597.0,3.648919e+02,1.485152e+02,31.006,9.794260e+02
FractionCSP3,597.0,4.807705e-01,2.597235e-01,0.000,1.000000e+00
HallKierAlpha,597.0,-1.985628e+00,1.116886e+00,-7.060,1.740000e+00
HeavyAtomCount,597.0,2.537856e+01,1.025206e+01,2.000,6.700000e+01
HeavyAtomMolWt,597.0,3.415419e+02,1.393358e+02,30.006,9.146610e+02
Ipc,597.0,9.187930e+11,1.620354e+13,2.000,3.850000e+14
Kappa1,597.0,1.857920e+01,7.926347e+00,1.600,5.566700e+01
Kappa2,597.0,7.773353e+00,3.957010e+00,0.600,2.662000e+01
Kappa3,597.0,9.470233e+00,8.725238e+01,-4.900,1.512242e+03
LabuteASA,597.0,1.509684e+02,6.019297e+01,11.859,3.965720e+02
MaxAbsEStateIndex,597.0,1.142562e+01,2.697187e+00,2.335,1.736100e+01
MaxAbsPartialCharge,597.0,4.449430e-01,9.929258e-02,0.120,8.750000e-01
MaxPartialCharge,597.0,2.572697e-01,1.080158e-01,-0.085,5.730000e-01
MinAbsEStateIndex,597.0,2.412714e-01,5.356284e-01,0.000,6.578000e+00
MinAbsPartialCharge,597.0,2.533233e-01,1.007407e-01,0.002,4.930000e-01
MinEStateIndex,597.0,-1.235906e+00,1.532702e+00,-6.625,4.500000e+00
MinPartialCharge,597.0,-4.403769e-01,1.018391e-01,-0.875,-1.200000e-01
MolLogP,597.0,2.293191e+00,2.720541e+00,-9.358,9.868000e+00
MolMR,597.0,9.570753e+01,3.832395e+01,5.396,2.553220e+02
MolWt,597.0,3.652713e+02,1.486440e+02,31.014,9.801810e+02
NHOHCount,597.0,2.262982e+00,2.195829e+00,0.000,1.600000e+01
NOCount,597.0,5.953099e+00,3.559345e+00,0.000,2.300000e+01
NumAliphaticCarbocycles,597.0,6.934673e-01,1.292015e+00,0.000,5.000000e+00
NumAliphaticHeterocycles,597.0,7.353434e-01,9.607955e-01,0.000,7.000000e+00
NumAliphaticRings,597.0,1.428811e+00,1.572746e+00,0.000,8.000000e+00
NumAromaticCarbocycles,597.0,9.782245e-01,8.999598e-01,0.000,4.000000e+00
NumAromaticHeterocycles,597.0,4.489112e-01,7.346777e-01,0.000,5.000000e+00
NumAromaticRings,597.0,1.427136e+00,1.180149e+00,0.000,8.000000e+00
NumHAcceptors,597.0,5.038526e+00,3.160716e+00,0.000,2.100000e+01
NumHDonors,597.0,1.989950e+00,1.843699e+00,0.000,1.200000e+01
NumHeteroatoms,597.0,6.800670e+00,3.797138e+00,1.000,2.500000e+01
NumRotatableBonds,597.0,6.026801e+00,4.617877e+00,0.000,2.800000e+01
NumSaturatedCarbocycles,597.0,4.907873e-01,1.014326e+00,0.000,5.000000e+00
NumSaturatedHeterocycles,597.0,4.941374e-01,8.018744e-01,0.000,5.000000e+00
NumSaturatedRings,597.0,9.849246e-01,1.290690e+00,0.000,7.000000e+00
NumValenceElectrons,597.0,1.371223e+02,5.593003e+01,12.000,3.720000e+02
PEOE_VSA1,597.0,1.669164e+01,1.287662e+01,0.000,1.035400e+02
PEOE_VSA10,597.0,8.980683e+00,1.027918e+01,0.000,9.766300e+01
PEOE_VSA11,597.0,4.738119e+00,7.610418e+00,0.000,4.599600e+01
PEOE_VSA12,597.0,2.819742e+00,5.178355e+00,0.000,5.907200e+01
PEOE_VSA13,597.0,1.562988e+00,3.450167e+00,0.000,2.023600e+01
PEOE_VSA14,597.0,4.158863e+00,5.630208e+00,0.000,4.159600e+01
PEOE_VSA2,597.0,7.443052e+00,6.891159e+00,0.000,4.794500e+01
PEOE_VSA3,597.0,3.893503e+00,5.236373e+00,0.000,2.881900e+01
PEOE_VSA4,597.0,1.953280e+00,5.098657e+00,0.000,3.512300e+01
PEOE_VSA5,597.0,2.077752e+00,5.740292e+00,0.000,6.960600e+01
PEOE_VSA6,597.0,2.452707e+01,2.137118e+01,0.000,1.289190e+02
PEOE_VSA7,597.0,3.891980e+01,2.569736e+01,0.000,1.200250e+02
PEOE_VSA8,597.0,1.904013e+01,1.461528e+01,0.000,9.685400e+01
PEOE_VSA9,597.0,1.400657e+01,1.309533e+01,0.000,1.232080e+02
RingCount,597.0,2.855946e+00,1.704520e+00,0.000,1.000000e+01
SMR_VSA1,597.0,1.949113e+01,1.534599e+01,0.000,1.035400e+02
SMR_VSA10,597.0,1.874963e+01,1.501348e+01,0.000,9.118200e+01
SMR_VSA2,597.0,2.569045e-01,1.328523e+00,0.000,1.081900e+01
SMR_VSA3,597.0,6.943650e+00,7.587909e+00,0.000,4.211700e+01
SMR_VSA4,597.0,7.170229e+00,1.022481e+01,0.000,4.290400e+01
SMR_VSA5,597.0,3.962717e+01,3.348211e+01,0.000,2.039720e+02
SMR_VSA6,597.0,1.507845e+01,1.601058e+01,0.000,1.103670e+02
SMR_VSA7,597.0,3.943363e+01,2.694169e+01,0.000,1.448480e+02
SMR_VSA9,597.0,4.062474e+00,7.152618e+00,0.000,6.750600e+01
SlogP_VSA1,597.0,7.126434e+00,7.374831e+00,0.000,5.441900e+01
SlogP_VSA10,597.0,3.691564e+00,6.076579e+00,0.000,3.512300e+01
SlogP_VSA11,597.0,2.612616e+00,5.343302e+00,0.000,4.599600e+01
SlogP_VSA12,597.0,5.535186e+00,1.060174e+01,0.000,6.960600e+01
SlogP_VSA2,597.0,4.290986e+01,2.949060e+01,0.000,2.326700e+02
SlogP_VSA3,597.0,1.283040e+01,1.084503e+01,0.000,7.253900e+01
SlogP_VSA4,597.0,8.045405e+00,1.055010e+01,0.000,4.143000e+01
SlogP_VSA5,597.0,3.298443e+01,2.575832e+01,0.000,1.368490e+02
SlogP_VSA6,597.0,3.086678e+01,2.212283e+01,0.000,1.334600e+02
SlogP_VSA7,597.0,8.074054e-01,2.557532e+00,0.000,2.009100e+01
SlogP_VSA8,597.0,3.403198e+00,7.320935e+00,0.000,7.760800e+01
TPSA,597.0,8.688523e+01,5.640444e+01,0.000,3.766700e+02
VSA_EState10,597.0,1.176586e+00,4.128960e+00,-21.832,3.528700e+01
VSA_EState8,597.0,7.525801e+00,1.602530e+01,0.000,1.415200e+02
VSA_EState9,597.0,5.444277e+01,2.610509e+01,-19.781,1.827770e+02
fr_Al_COO,597.0,2.395310e-01,6.030502e-01,0.000,5.000000e+00
fr_Al_OH,597.0,6.951424e-01,1.286557e+00,0.000,1.100000e+01
fr_Al_OH_noTert,597.0,5.711893e-01,1.194383e+00,0.000,1.100000e+01
fr_ArN,597.0,7.537688e-02,3.054539e-01,0.000,2.000000e+00
fr_Ar_COO,597.0,3.182580e-02,1.938454e-01,0.000,2.000000e+00
fr_Ar_N,597.0,6.231156e-01,1.194367e+00,0.000,6.000000e+00
fr_Ar_NH,597.0,8.710218e-02,3.263349e-01,0.000,2.000000e+00
fr_Ar_OH,597.0,1.323283e-01,4.497316e-01,0.000,4.000000e+00
fr_COO,597.0,2.713568e-01,6.346275e-01,0.000,5.000000e+00
fr_COO2,597.0,2.763819e-01,6.390495e-01,0.000,5.000000e+00
fr_C_O,597.0,1.217755e+00,1.258322e+00,0.000,1.000000e+01
fr_C_O_noCOO,597.0,1.010050e+00,1.205371e+00,0.000,1.000000e+01
fr_C_S,597.0,3.350084e-03,5.783133e-02,0.000,1.000000e+00
fr_HOCCN,597.0,2.512563e-02,1.670064e-01,0.000,2.000000e+00
fr_Imine,597.0,6.532663e-02,3.077638e-01,0.000,4.000000e+00
fr_NH0,597.0,1.252931e+00,1.397990e+00,0.000,7.000000e+00
fr_NH1,597.0,5.711893e-01,8.174117e-01,0.000,7.000000e+00
fr_NH2,597.0,2.780570e-01,6.474557e-01,0.000,5.000000e+00
fr_N_O,597.0,2.010050e-02,2.770857e-01,0.000,6.000000e+00
fr_Ndealkylation1,597.0,1.340034e-01,3.553988e-01,0.000,2.000000e+00
fr_Ndealkylation2,597.0,1.172529e-01,3.271606e-01,0.000,2.000000e+00
fr_SH,597.0,8.375209e-03,9.120855e-02,0.000,1.000000e+00
fr_aldehyde,597.0,6.700168e-03,1.001107e-01,0.000,2.000000e+00
fr_alkyl_carbamate,597.0,1.675042e-02,1.523446e-01,0.000,2.000000e+00
fr_alkyl_halide,597.0,2.562814e-01,9.157358e-01,0.000,8.000000e+00
fr_allylic_oxid,597.0,4.237856e-01,1.185612e+00,0.000,1.200000e+01
fr_amide,597.0,4.974874e-01,9.458903e-01,0.000,1.000000e+01
fr_amidine,597.0,1.172529e-02,1.223232e-01,0.000,2.000000e+00
fr_aniline,597.0,3.551089e-01,6.739607e-01,0.000,4.000000e+00
fr_aryl_methyl,597.0,2.613065e-01,6.362065e-01,0.000,7.000000e+00
fr_azo,597.0,1.675042e-03,4.092728e-02,0.000,1.000000e+00
fr_benzodiazepine,597.0,1.005025e-02,9.982954e-02,0.000,1.000000e+00
fr_bicyclic,597.0,1.221106e+00,1.852268e+00,0.000,1.100000e+01
fr_dihydropyridine,597.0,1.340034e-02,1.150780e-01,0.000,1.000000e+00
fr_epoxide,597.0,1.005025e-02,9.982954e-02,0.000,1.000000e+00
fr_ester,597.0,2.110553e-01,5.393991e-01,0.000,4.000000e+00
fr_ether,597.0,8.726968e-01,1.421506e+00,0.000,1.000000e+01
fr_furan,597.0,1.507538e-02,1.219550e-01,0.000,1.000000e+00
fr_guanido,597.0,4.187605e-02,2.776734e-01,0.000,4.000000e+00
fr_halogen,597.0,5.376884e-01,1.099422e+00,0.000,8.000000e+00
fr_hdrzine,597.0,1.842546e-02,1.345968e-01,0.000,1.000000e+00
fr_hdrzone,597.0,3.350084e-03,5.783133e-02,0.000,1.000000e+00
fr_imidazole,597.0,6.532663e-02,2.540024e-01,0.000,2.000000e+00
fr_imide,597.0,2.345059e-02,1.621567e-01,0.000,2.000000e+00
fr_ketone,597.0,2.378559e-01,6.051020e-01,0.000,3.000000e+00
fr_ketone_Topliss,597.0,1.591290e-01,4.447357e-01,0.000,3.000000e+00
fr_lactam,597.0,2.177554e-02,1.460723e-01,0.000,1.000000e+00
fr_lactone,597.0,3.182580e-02,1.756833e-01,0.000,1.000000e+00
fr_methoxy,597.0,2.144054e-01,6.586494e-01,0.000,8.000000e+00
fr_morpholine,597.0,1.172529e-02,1.077370e-01,0.000,1.000000e+00
fr_nitrile,597.0,4.187605e-02,2.315439e-01,0.000,2.000000e+00
fr_nitro,597.0,3.015075e-02,1.806833e-01,0.000,2.000000e+00
fr_nitro_arom,597.0,1.842546e-02,1.465333e-01,0.000,2.000000e+00
fr_nitro_arom_nonortho,597.0,1.005025e-02,9.982954e-02,0.000,1.000000e+00
fr_nitroso,597.0,3.350084e-03,5.783133e-02,0.000,1.000000e+00
fr_oxazole,597.0,1.675042e-03,4.092728e-02,0.000,1.000000e+00
fr_oxime,597.0,8.375209e-03,9.120855e-02,0.000,1.000000e+00
fr_para_hydroxylation,597.0,1.541039e-01,4.331530e-01,0.000,3.000000e+00
fr_phenol,597.0,1.289782e-01,4.355600e-01,0.000,4.000000e+00
fr_phenol_noOrthoHbond,597.0,1.189280e-01,4.267800e-01,0.000,4.000000e+00
fr_phos_acid,597.0,1.675042e-02,1.409013e-01,0.000,2.000000e+00
fr_phos_ester,597.0,1.340034e-02,1.288358e-01,0.000,2.000000e+00
fr_piperdine,597.0,1.373534e-01,4.500876e-01,0.000,4.000000e+00
fr_piperzine,597.0,4.187605e-02,2.086755e-01,0.000,2.000000e+00
fr_priamide,597.0,4.857621e-02,2.228224e-01,0.000,2.000000e+00
fr_pyridine,597.0,9.882747e-02,3.306724e-01,0.000,2.000000e+00
fr_quatN,597.0,3.685092e-02,2.055818e-01,0.000,2.000000e+00
fr_sulfide,597.0,5.862647e-02,2.556347e-01,0.000,2.000000e+00
fr_sulfonamd,597.0,4.187605e-02,2.241805e-01,0.000,2.000000e+00
fr_sulfone,597.0,1.340034e-02,1.150780e-01,0.000,1.000000e+00
fr_term_acetylene,597.0,8.375209e-03,9.120855e-02,0.000,1.000000e+00
fr_tetrazole,597.0,1.172529e-02,1.077370e-01,0.000,1.000000e+00
fr_thiazole,597.0,2.680067e-02,1.717028e-01,0.000,2.000000e+00
fr_thiophene,597.0,2.847571e-02,1.855335e-01,0.000,2.000000e+00
fr_unbrch_alkane,597.0,3.333333e-01,1.351526e+00,0.000,1.800000e+01
fr_urea,597.0,2.512563e-02,1.566379e-01,0.000,1.000000e+00

In [15]:
# Categorical Feature Statistics
cat_stats

                                                                           value  \
column rank
Label  1                                                                       0
       2                                                                       1
SMILES 1                                       CC(C)NC[C@H](O)COc1cccc2[nH]ccc12
       2                                OCCN1CCN(CCCN2c3ccccc3Sc4ccc(Cl)cc24)CC1
       3                                         NC(=O)Cc1cccc(C(=O)c2ccccc2)c1N
       4              OC(=O)[C@@H]1C[C@H](CN1C(=O)CP(=O)(O)CCCCc2ccccc2)C3CCCCC3
       5     CC[C@H](C)C(=O)O[C@@H]1C[C@H](C)C=C2C=C[C@H](C)[C@H](CC[C@@H]3C[...

             count    pct
column rank
Label  1       449  75.21
       2       148  24.79
SMILES 1         1   0.17
       2         1   0.17
       3         1   0.17
       4         1   0.17
       5         1   0.17

In [16]:
# Target Distribution
target_df

       count    pct
Label
0        449  75.21
1        148  24.79

## Task Curation

In [17]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=20, n_splits=3, test_size=None

In [18]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [19]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019c9f82-d8aa-7c13-b593-d70835a80e0a
614393f00340d2a0e9ffcecd39bfacabdbc16c461ab886004a0bda1159c7d0b6