### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="mice_protein_trisomy_discriminant",
    dataset_year="2015",
    domain_str="biology & life sciences",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C50S3Z",
    download_description="""
We get the data from UCI.

wget https://archive.ics.uci.edu/static/public/342/mice+protein+expression.zip && unzip mice+protein+expression.zip && rm -rf mice+protein+expression.zip
mkdir -p local-data-warehouse/mice_protein_trisomy_discriminant && mv Data_Cortex_Nuclear.xls local-data-warehouse/mice_protein_trisomy_discriminant/
""",
    # References
    academic_reference_bibtex="""@article{higuera2015self,
  title={Self-organizing feature maps identify proteins critical to learning in a mouse model of down syndrome},
  author={Higuera, Clara and Gardiner, Katheleen J and Cios, Krzysztof J},
  journal={PloS one},
  volume={10},
  number={6},
  pages={e0129126},
  year={2015},
  publisher={Public Library of Science San Francisco, CA USA}
}
""",
    academic_reference_bibtex_key="higuera2015self",
    license="CC BY 4.0",
    data_tags=["Non-IID", "Grouped"],
    curation_comments="""
We start with the dataset from UCI.

- We drop the three feature that make up the target to remove the leakage.
- We reduce the mouse ID to represent the ID of the mouse instead of the experiment for the mouse.
- We drop the duplicated feature pS6_N.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="class",
    problem_type="binary_classification",
    objective_metric_name="log_loss",
    stratify_on="class",
    group_on="MouseID",
    group_labels="per_group",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_excel(dataset_mold.path / "Data_Cortex_Nuclear.xls")
print("Loaded data shape:", df.shape)

# Fix the ID so it reduces to the same mouse
df["MouseID"] = df["MouseID"].str.split("_").str[0]
# Drop leaky features that are part of the target
df = df.drop(columns=["Genotype", "Treatment", "Behavior"])
as_type_cat = ["MouseID", "class"]
df[as_type_cat] = df[as_type_cat].astype("category")
# Drop duplicated column
df = df.drop(columns=["pS6_N"])
df = df.reset_index(drop=True)

Loaded data shape: (1080, 82)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 1,080
Columns: 78
Use sampling: False (sample size: 1,080)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['PSD95_N', 'pCASP9_N', 'Ubiquitin_N', 'S6_N', 'CDK5_N', 'pPKCG_N', 'BAX_N', 'RRP1_N', 'ARC_N', 'pGSK3B_Tyr216_N']
Rows remaining as candidates after top-10 filter: 0 (of 1,080)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,MouseID,DYRK1A_N,ITSN1_N,BDNF_N,NR1_N,NR2A_N,pAKT_N,pBRAF_N,pCAMKII_N,pCREB_N,pELK_N,pERK_N,pJNK_N,PKCA_N,pMEK_N,pNR1_N,pNR2A_N,pNR2B_N,pPKCAB_N,pRSK_N,AKT_N,BRAF_N,CAMKII_N,CREB_N,ELK_N,ERK_N,GSK3B_N,JNK_N,MEK_N,TRKA_N,RSK_N,APP_N,Bcatenin_N,SOD1_N,MTOR_N,P38_N,pMTOR_N,DSCR1_N,AMPKA_N,NR2B_N,pNUMB_N,RAPTOR_N,TIAM1_N,pP70S6_N,NUMB_N,P70S6_N,pGSK3B_N,pPKCG_N,CDK5_N,S6_N,ADARB1_N,AcetylH3K9_N,RRP1_N,BAX_N,ARC_N,ERBB4_N,nNOS_N,Tau_N,GFAP_N,GluR3_N,GluR4_N,IL1B_N,P3525_N,pCASP9_N,PSD95_N,SNCA_N,Ubiquitin_N,pGSK3B_Tyr216_N,SHH_N,BAD_N,BCL2_N,pCFOS_N,SYP_N,H3AcK18_N,EGR1_N,H3MeK4_N,CaNA_N,class
0,309,0.503644,0.747193,0.430175,2.816329,5.990152,0.218830,0.177565,2.373744,0.232224,1.750936,0.687906,0.306382,0.402698,0.296927,1.022060,0.605673,1.877684,2.308745,0.441599,0.859366,0.416289,0.369608,0.178944,1.866358,3.685247,1.537227,0.264526,0.319677,0.813866,0.165846,0.453910,3.037621,0.369510,0.458539,0.335336,0.825192,0.576916,0.448099,0.586271,0.394721,0.339571,0.482864,0.294170,0.182150,0.842725,0.192608,1.443091,0.294700,0.354605,1.339070,0.170119,0.159102,0.188852,0.106305,0.144989,0.176668,0.125190,0.115291,0.228043,0.142756,0.430957,0.247538,1.603310,2.014875,0.108234,1.044979,0.831557,0.188852,0.122652,NaN,0.108336,0.427099,0.114783,0.131790,0.128186,1.675652,c-CS-m
1,309,0.514617,0.689064,0.411770,2.789514,5.685038,0.211636,0.172817,2.292150,0.226972,1.596377,0.695006,0.299051,0.385987,0.281319,0.956676,0.587559,1.725774,2.043037,0.445222,0.834659,0.400364,0.356178,0.173680,1.761047,3.485287,1.509249,0.255727,0.304419,0.780504,0.157194,0.430940,2.921882,0.342279,0.423560,0.324835,0.761718,0.545097,0.420876,0.545097,0.368255,0.321959,0.454519,0.276431,0.182086,0.847615,0.194815,1.439460,0.294060,0.354548,1.306323,0.171427,0.158129,0.184570,0.106592,0.150471,0.178309,0.134275,0.118235,0.238073,0.142037,0.457156,0.257632,1.671738,2.004605,0.109749,1.009883,0.849270,0.200404,0.116682,NaN,0.104315,0.441581,0.111974,0.135103,0.131119,1.743610,c-CS-m
2,309,0.509183,0.730247,0.418309,2.687201,5.622059,0.209011,0.175722,2.283337,0.230247,1.561316,0.677348,0.291276,0.381002,0.281710,1.003635,0.602449,1.731873,2.017984,0.467668,0.814329,0.399847,0.368089,0.173905,1.765544,3.571456,1.501244,0.259614,0.311747,0.785154,0.160895,0.423187,2.944136,0.343696,0.425005,0.324852,0.757031,0.543620,0.404630,0.552994,0.363880,0.313086,0.447197,0.256648,0.184388,0.856166,0.200737,1.524364,0.301881,0.386087,1.279600,0.185456,0.148696,0.190532,0.108303,0.145330,0.176213,0.132560,0.117760,0.244817,0.142445,0.510472,0.255343,1.663550,2.016831,0.108196,0.996848,0.846709,0.193685,0.118508,NaN,0.106219,0.435777,0.111883,0.133362,0.127431,1.926427,c-CS-m
3,309,0.442107,0.617076,0.358626,2.466947,4.979503,0.222886,0.176463,2.152301,0.207004,1.595086,0.583277,0.296729,0.377087,0.313832,0.875390,0.520293,1.566852,2.132754,0.477671,0.727705,0.385639,0.362970,0.179449,1.286277,2.970137,1.419710,0.259536,0.279218,0.734492,0.162210,0.410615,2.500204,0.344509,0.429211,0.330121,0.746980,0.546763,0.386860,0.547849,0.366771,0.328492,0.442650,0.398534,0.161768,0.760234,0.184169,1.612382,0.296382,0.290680,1.198765,0.159799,0.166112,0.185323,0.103184,0.140656,0.163804,0.123210,0.117439,0.234947,0.145068,0.430996,0.251103,1.484624,1.957233,0.119883,0.990225,0.833277,0.192112,0.132781,NaN,0.111262,0.391691,0.130405,0.147444,0.146901,1.700563,c-CS-m
4,309,0.434940,0.617430,0.358802,2.365785,4.718679,0.213106,0.173627,2.134014,0.192158,1.504230,0.550960,0.286961,0.363502,0.277964,0.864912,0.507990,1.480059,2.013697,0.483416,0.687794,0.367531,0.355311,0.174836,1.324695,2.896334,1.359876,0.250705,0.273667,0.702699,0.154827,0.398550,2.456560,0.329126,0.408755,0.313415,0.691956,0.536860,0.360816,0.512824,0.351551,0.312206,0.419095,0.393447,0.160200,0.768113,0.185718,1.645807,0.296829,0.309345,1.206995,0.164650,0.160687,0.188221,0.104784,0.141983,0.167710,0.136838,0.116048,0.255528,0.140871,0.481227,0.251773,1.534835,2.009109,0.119524,0.997775,0.878668,0.205604,0.129954,NaN,0.110694,0.434154,0.118481,0.140314,0.148380,1.839730,c-CS-m

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,MouseID,category,0.0,0.00,72.0,"18899, 293, 294, 309, 311, 320, 321, 322, 3411, 3412"
1,class,category,0.0,0.00,8.0,"c-CS-m, c-SC-m, c-CS-s, c-SC-s, t-CS-m, t-SC-m, t-SC-s, t-CS-s"
2,BCL2_N,float64,285.0,26.39,795.0,"0.1726, 0.1786, 0.1436, 0.1329, 0.1824, 0.1638, 0.1431, 0.2023, 0.1783, 0.1604"
3,H3MeK4_N,float64,270.0,25.00,810.0,"0.3653, 0.1282, 0.1311, 0.1274, 0.1469, 0.1484, 0.1422, 0.1575, 0.1594, 0.1582"
4,BAD_N,float64,213.0,19.72,866.0,"0.2003, 0.1356, 0.1411, 0.1378, 0.1557, 0.1496, 0.1511, 0.1468, 0.1729, 0.1507"
5,EGR1_N,float64,210.0,19.44,870.0,"0.253, 0.1318, 0.1351, 0.1334, 0.1474, 0.1403, 0.1904, 0.1601, 0.1827, 0.1864"
6,H3AcK18_N,float64,180.0,16.67,900.0,"0.3351, 0.1148, 0.112, 0.1119, 0.1651, 0.148, 0.158, 0.163, 0.1714, 0.1724"
7,pCFOS_N,float64,75.0,6.94,1005.0,"0.1876, 0.1083, 0.1043, 0.1062, 0.1113, 0.1107, 0.1094, 0.1115, 0.1131, 0.1055"
8,ELK_N,float64,18.0,1.67,1062.0,"0.8847, 1.8664, 1.761, 1.7655, 1.2863, 1.3247, 1.5303, 1.1515, 1.233, 1.23"
9,Bcatenin_N,float64,18.0,1.67,1062.0,"1.7428, 3.0376, 2.9219, 2.9441, 2.5002, 2.4566, 2.872, 2.4499, 2.5657, 2.5414"
10,MEK_N,float64,7.0,0.65,1072.0,"0.2752, 0.297, 0.3135, 0.327, 0.267, 0.2396, 0.2483, 0.2485, 0.2617, 0.251"
11,DYRK1A_N,float64,3.0,0.28,1077.0,"0.3026, 0.5036, 0.5146, 0.5092, 0.4421, 0.4349, 0.4475, 0.428, 0.4169, 0.3863"
12,ITSN1_N,float64,3.0,0.28,1076.0,"0.6393, 0.623, 0.4619, 0.4433, 0.444, 0.479, 0.4903, 0.5112, 0.6281, 0.5159"
13,BDNF_N,float64,3.0,0.28,1077.0,"0.2566, 0.4302, 0.4118, 0.4183, 0.3586, 0.3588, 0.3674, 0.3427, 0.3277, 0.3177"
14,NR1_N,float64,3.0,0.28,1077.0,"2.0928, 2.8163, 2.7895, 2.6872, 2.4669, 2.3658, 2.3859, 2.3342, 2.2601, 2.1257"
15,NR2A_N,float64,3.0,0.28,1077.0,"2.5943, 5.9902, 5.685, 5.6221, 4.9795, 4.7187, 4.8076, 4.4731, 4.2687, 4.064"
16,pAKT_N,float64,3.0,0.28,1076.0,"0.2312, 0.2449, 0.2499, 0.2874, 0.2611, 0.2739, 0.2593, 0.2352, 0.2617, 0.2497"
17,pBRAF_N,float64,3.0,0.28,1075.0,"0.2042, 0.2105, 0.2015, 0.2063, 0.1922, 0.2035, 0.1903, 0.1907, 0.1978, 0.1782"
18,pCAMKII_N,float64,3.0,0.28,1077.0,"2.3618, 2.3737, 2.2921, 2.2833, 2.1523, 2.134, 2.1413, 2.0124, 2.008, 1.8615"
19,pCREB_N,float64,3.0,0.28,1077.0,"0.2236, 0.2322, 0.227, 0.2302, 0.207, 0.1922, 0.1952, 0.1958, 0.1898, 0.1807"
20,pELK_N,float64,3.0,0.28,1077.0,"1.0641, 1.7509, 1.5964, 1.5613, 1.5951, 1.5042, 1.4424, 1.612, 1.4246, 1.2619"
21,pERK_N,float64,3.0,0.28,1077.0,"0.2761, 0.6879, 0.695, 0.6773, 0.5833, 0.551, 0.5663, 0.5099, 0.5011, 0.4767"
22,pJNK_N,float64,3.0,0.28,1076.0,"0.3333, 0.3719, 0.374, 0.3432, 0.3107, 0.3138, 0.3173, 0.329, 0.3763, 0.3203"
23,PKCA_N,float64,3.0,0.28,1077.0,"0.2755, 0.4027, 0.386, 0.381, 0.3771, 0.3635, 0.3639, 0.3712, 0.3589, 0.337"
24,pMEK_N,float64,3.0,0.28,1077.0,"0.3158, 0.2969, 0.2813, 0.2817, 0.3138, 0.278, 0.2668, 0.2777, 0.2564, 0.2426"
25,pNR1_N,float64,3.0,0.28,1077.0,"0.7132, 1.0221, 0.9567, 1.0036, 0.8754, 0.8649, 0.8591, 0.8443, 0.8186, 0.7483"
26,pNR2A_N,float64,3.0,0.28,1077.0,"0.5022, 0.6057, 0.5876, 0.6024, 0.5203, 0.508, 0.5213, 0.4854, 0.4785, 0.459"
27,pNR2B_N,float64,3.0,0.28,1077.0,"1.2319, 1.8777, 1.7258, 1.7319, 1.5669, 1.4801, 1.5382, 1.4948, 1.4094, 1.3418"
28,pPKCAB_N,float64,3.0,0.28,1077.0,"1.2824, 2.3087, 2.043, 2.018, 2.1328, 2.0137, 1.9683, 2.0126, 1.857, 1.8221"
29,pRSK_N,float64,3.0,0.28,1077.0,"0.4292, 0.4416, 0.4452, 0.4677, 0.4777, 0.4834, 0.4959, 0.4975, 0.4896, 0.4645"
30,AKT_N,float64,3.0,0.28,1077.0,"0.6295, 0.8594, 0.8347, 0.8143, 0.7277, 0.6878, 0.6724, 0.6461, 0.6281, 0.6006"
31,BRAF_N,float64,3.0,0.28,1077.0,"0.312, 0.4163, 0.4004, 0.3998, 0.3856, 0.3675, 0.3694, 0.396, 0.3607, 0.3266"
32,CAMKII_N,float64,3.0,0.28,1077.0,"0.3498, 0.3696, 0.3562, 0.3681, 0.363, 0.3553, 0.3572, 0.3595, 0.3607, 0.3289"
33,CREB_N,float64,3.0,0.28,1073.0,"0.2289, 0.186, 0.2109, 0.1979, 0.1915, 0.1831, 0.1778, 0.2078, 0.1891, 0.1912"
34,ERK_N,float64,3.0,0.28,1077.0,"1.7859, 3.6852, 3.4853, 3.5715, 2.9701, 2.8963, 2.957, 2.5996, 2.5502, 2.4346"
35,GSK3B_N,float64,3.0,0.28,1077.0,"0.9702, 1.5372, 1.5092, 1.5012, 1.4197, 1.3599, 1.4479, 1.3642, 1.3166, 1.252"
36,JNK_N,float64,3.0,0.28,1077.0,"0.287, 0.2645, 0.2557, 0.2596, 0.2595, 0.2507, 0.2508, 0.2615, 0.2506, 0.2304"
37,TRKA_N,float64,3.0,0.28,1075.0,"0.6667, 0.7769, 0.7867, 0.6335, 0.6097, 0.633, 0.6271, 0.6397, 0.6472, 0.6513"
38,RSK_N,float64,3.0,0.28,1074.0,"0.1877, 0.1622, 0.1956, 0.1562, 0.1585, 0.2098, 0.2041, 0.2156, 0.1847, 0.1518"
39,APP_N,float64,3.0,0.28,1077.0,"0.403, 0.4539, 0.4309, 0.4232, 0.4106, 0.3985, 0.391, 0.4056, 0.3755, 0.3512"
40,SOD1_N,float64,3.0,0.28,1077.0,"0.7868, 0.3695, 0.3423, 0.3437, 0.3445, 0.3291, 0.3276, 0.3454, 0.3282, 0.3092"
41,MTOR_N,float64,3.0,0.28,1077.0,"0.3999, 0.4585, 0.4236, 0.425, 0.4292, 0.4088, 0.4045, 0.4276, 0.4072, 0.3785"
42,P38_N,float64,3.0,0.28,1075.0,"0.4729, 0.3333, 0.3568, 0.3593, 0.4009, 0.3541, 0.371, 0.3667, 0.34, 0.362"
43,pMTOR_N,float64,3.0,0.28,1077.0,"0.6028, 0.8252, 0.7617, 0.757, 0.747, 0.692, 0.6744, 0.7575, 0.6952, 0.6369"
44,DSCR1_N,float64,3.0,0.28,1077.0,"0.5338, 0.5769, 0.5451, 0.5436, 0.5468, 0.5369, 0.5397, 0.5586, 0.525, 0.4849"
45,AMPKA_N,float64,3.0,0.28,1075.0,"0.3333, 0.3677, 0.3729, 0.4244, 0.3246, 0.3062, 0.3067, 0.3065, 0.3142, 0.3312"
46,NR2B_N,float64,3.0,0.28,1077.0,"0.638, 0.5863, 0.5451, 0.553, 0.5478, 0.5128, 0.5143, 0.5446, 0.5098, 0.48"
47,pNUMB_N,float64,3.0,0.28,1077.0,"0.2815, 0.3947, 0.3683, 0.3639, 0.3668, 0.3516, 0.3472, 0.3603, 0.3383, 0.3121"
48,RAPTOR_N,float64,3.0,0.28,1077.0,"0.2737, 0.3396, 0.322, 0.3131, 0.3285, 0.3122, 0.3031, 0.3294, 0.2985, 0.2793"
49,TIAM1_N,float64,3.0,0.28,1075.0,"0.375, 0.3156, 0.5071, 0.3789, 0.3667, 0.3761, 0.3617, 0.38, 0.4226, 0.3883"
50,pP70S6_N,float64,3.0,0.28,1076.0,"0.5, 0.368, 0.3928, 0.35, 0.336, 0.3321, 0.3355, 0.344, 0.3594, 0.3216"
51,NUMB_N,float64,0.0,0.00,1080.0,"0.1888, 0.1822, 0.1821, 0.1844, 0.1618, 0.1602, 0.1623, 0.1456, 0.1478, 0.1501"
52,P70S6_N,float64,0.0,0.00,1080.0,"0.7728, 0.8427, 0.8476, 0.8562, 0.7602, 0.7681, 0.7797, 0.7022, 0.6819, 0.7108"
53,pGSK3B_N,float64,0.0,0.00,1080.0,"0.1727, 0.1926, 0.1948, 0.2007, 0.1842, 0.1857, 0.1868, 0.177, 0.1746, 0.1675"
54,pPKCG_N,float64,0.0,0.00,1080.0,"2.6549, 1.4431, 1.4395, 1.5244, 1.6124, 1.6458, 1.6346, 1.7738, 1.7958, 1.8052"
55,CDK5_N,float64,0.0,0.00,1080.0,"0.317, 0.2947, 0.2941, 0.3019, 0.2964, 0.2968, 0.288, 0.2922, 0.2885, 0.2945"
56,S6_N,float64,0.0,0.00,1080.0,"0.6317, 0.3546, 0.3545, 0.3861, 0.2907, 0.3093, 0.3324, 0.2669, 0.2886, 0.2941"
57,ADARB1_N,float64,0.0,0.00,1080.0,"0.7366, 1.3391, 1.3063, 1.2796, 1.1988, 1.207, 1.1234, 1.0323, 1.1521, 1.1079"
58,AcetylH3K9_N,float64,0.0,0.00,1080.0,"0.5353, 0.1701, 0.1714, 0.1855, 0.1598, 0.1647, 0.1757, 0.1479, 0.1524, 0.1588"
59,RRP1_N,float64,0.0,0.00,1080.0,"0.194, 0.1591, 0.1581, 0.1487, 0.1661, 0.1607, 0.1506, 0.1498, 0.1545, 0.1487"
60,BAX_N,float64,0.0,0.00,1080.0,"0.1722, 0.1889, 0.1846, 0.1905, 0.1853, 0.1882, 0.1838, 0.1816, 0.1829, 0.1785"
61,ARC_N,float64,0.0,0.00,1080.0,"0.1189, 0.1063, 0.1066, 0.1083, 0.1032, 0.1048, 0.1065, 0.0978, 0.0995, 0.1051"
62,ERBB4_N,float64,0.0,0.00,1079.0,"0.1553, 0.1702, 0.1637, 0.1721, 0.1681, 0.1627, 0.1938, 0.1905, 0.1699, 0.1893"
63,nNOS_N,float64,0.0,0.00,1079.0,"0.1739, 0.2126, 0.211, 0.1953, 0.2057, 0.1901, 0.1783, 0.1905, 0.1839, 0.1723"
64,Tau_N,float64,0.0,0.00,1080.0,"0.3932, 0.1252, 0.1343, 0.1326, 0.1232, 0.1368, 0.1305, 0.116, 0.1196, 0.124"
65,GFAP_N,float64,0.0,0.00,1079.0,"0.1304, 0.1232, 0.1109, 0.1113, 0.1162, 0.1314, 0.1308, 0.1291, 0.1168, 0.1349"
66,GluR3_N,float64,0.0,0.00,1080.0,"0.2044, 0.228, 0.2381, 0.2448, 0.2349, 0.2555, 0.2368, 0.2245, 0.2468, 0.2339"
67,GluR4_N,float64,0.0,0.00,1079.0,"0.111, 0.1594, 0.1639, 0.1549, 0.1545, 0.1566, 0.1031, 0.1573, 0.1025, 0.1183"
68,IL1B_N,float64,0.0,0.00,1080.0,"0.6303, 0.431, 0.4572, 0.5105, 0.431, 0.4812, 0.4786, 0.4155, 0.4511, 0.456"
69,P3525_N,float64,0.0,0.00,1080.0,"0.3565, 0.2475, 0.2576, 0.2553, 0.2511, 0.2518, 0.2445, 0.238, 0.2414, 0.236"
70,pCASP9_N,float64,0.0,0.00,1080.0,"1.4901, 1.6033, 1.6717, 1.6635, 1.4846, 1.5348, 1.5078, 1.3388, 1.3861, 1.4042"
71,PSD95_N,float64,0.0,0.00,1080.0,"2.5264, 2.0149, 2.0046, 2.0168, 1.9572, 2.0091, 2.0035, 1.8617, 1.9695, 1.9587"
72,SNCA_N,float64,0.0,0.00,1079.0,"0.1715, 0.1462, 0.1461, 0.1485, 0.136, 0.175, 0.1915, 0.1762, 0.1139, 0.1558"
73,Ubiquitin_N,float64,0.0,0.00,1080.0,"1.2671, 1.045, 1.0099, 0.9968, 0.9902, 0.9978, 0.9202, 1.0288, 0.9435, 0.9469"
74,pGSK3B_Tyr216_N,float64,0.0,0.00,1080.0,"1.0204, 0.8316, 0.8493, 0.8467, 0.8333, 0.8787, 0.8437, 0.7983, 0.844, 0.8322"
75,SHH_N,float64,0.0,0.00,1080.0,"0.2923, 0.1889, 0.2004, 0.1937, 0.1921, 0.2056, 0.1905, 0.1816, 0.1916, 0.1864"
76,SYP_N,float64,0.0,0.00,1079.0,"0.488, 0.4824, 0.514, 0.49, 0.4961, 0.4991, 0.4855, 0.5022, 0.49, 0.4855"
77,CaNA_N,float64,0.0,0.00,1080.0,"1.371, 1.6757, 1.7436, 1.9264, 1.7006, 1.8397, 1.8164, 1.5285, 1.6527, 1.8346"

In [6]:
# Numeric Feature Statistics
numeric_stats

                  count      mean       std       min       max
DYRK1A_N         1077.0  0.425810  0.249362  0.145327  2.516367
ITSN1_N          1077.0  0.617102  0.251640  0.245359  2.602662
BDNF_N           1077.0  0.319088  0.049383  0.115181  0.497160
NR1_N            1077.0  2.297269  0.347293  1.330831  3.757641
NR2A_N           1077.0  3.843934  0.933100  1.737540  8.482553
pAKT_N           1077.0  0.233168  0.041634  0.063236  0.539050
pBRAF_N          1077.0  0.181846  0.027042  0.064043  0.317066
pCAMKII_N        1077.0  3.537109  1.295169  1.343998  7.464070
pCREB_N          1077.0  0.212574  0.032587  0.112812  0.306247
pELK_N           1077.0  1.428682  0.466904  0.429032  6.113347
pERK_N           1077.0  0.545904  0.345309  0.149155  3.566685
pJNK_N           1077.0  0.313505  0.051978  0.052110  0.493426
PKCA_N           1077.0  0.317939  0.052236  0.191431  0.473992
pMEK_N           1077.0  0.275033  0.046164  0.056818  0.458001
pNR1_N           1077.0  0.825813  0.117969  0.500160  1.408169
pNR2A_N          1077.0  0.726933  0.188013  0.281285  1.412750
pNR2B_N          1077.0  1.561965  0.270737  0.301609  2.723965
pPKCAB_N         1077.0  1.525338  0.481780  0.567840  3.061387
pRSK_N           1077.0  0.442848  0.066672  0.095942  0.650962
AKT_N            1077.0  0.682236  0.127434  0.064421  1.182175
BRAF_N           1077.0  0.378519  0.216388  0.143894  2.133416
CAMKII_N         1077.0  0.363357  0.052352  0.212960  0.586245
CREB_N           1077.0  0.180492  0.026370  0.113636  0.319558
ELK_N            1062.0  1.173400  0.335786  0.497695  2.802948
ERK_N            1077.0  2.474492  0.653397  1.131796  5.198404
GSK3B_N          1077.0  1.172603  0.244752  0.151124  2.475751
JNK_N            1077.0  0.241644  0.033901  0.046298  0.387191
MEK_N            1073.0  0.272789  0.041075  0.147201  0.415408
TRKA_N           1077.0  0.693180  0.120825  0.198743  1.001623
RSK_N            1077.0  0.168417  0.028138  0.107394  0.305136
APP_N            1077.0  0.404808  0.061173  0.235595  0.632663
Bcatenin_N       1062.0  2.146550  0.435742  1.134886  3.680552
SOD1_N           1077.0  0.542635  0.280568  0.217120  1.872899
MTOR_N           1077.0  0.452459  0.065488  0.201143  0.676748
P38_N            1077.0  0.415311  0.089290  0.227880  0.933256
pMTOR_N          1077.0  0.759047  0.122446  0.166579  1.124883
DSCR1_N          1077.0  0.585186  0.100601  0.155321  0.916429
AMPKA_N          1077.0  0.368370  0.062583  0.226409  0.700839
NR2B_N           1077.0  0.565317  0.088201  0.184785  0.972020
pNUMB_N          1077.0  0.357095  0.063025  0.185598  0.631052
RAPTOR_N         1077.0  0.315813  0.054163  0.194824  0.526681
TIAM1_N          1077.0  0.418605  0.067288  0.237777  0.722122
pP70S6_N         1077.0  0.394475  0.156170  0.131120  1.129171
NUMB_N           1080.0  0.181080  0.029296  0.117999  0.316575
P70S6_N          1080.0  0.943116  0.172838  0.344120  1.679953
pGSK3B_N         1080.0  0.161211  0.019308  0.099976  0.253210
pPKCG_N          1080.0  1.706599  0.578442  0.598767  3.381976
CDK5_N           1080.0  0.292434  0.037380  0.181157  0.817402
S6_N             1080.0  0.429226  0.137440  0.130206  0.822611
ADARB1_N         1080.0  1.197420  0.361743  0.529108  2.539890
AcetylH3K9_N     1080.0  0.216482  0.185309  0.052528  1.459387
RRP1_N           1080.0  0.166631  0.031896 -0.062008  0.612377
BAX_N            1080.0  0.179307  0.018826  0.072326  0.241141
ARC_N            1080.0  0.121521  0.014276  0.067254  0.158748
ERBB4_N          1080.0  0.156478  0.015071  0.100217  0.208698
nNOS_N           1080.0  0.181300  0.024919  0.099734  0.260739
Tau_N            1080.0  0.210489  0.069010  0.096233  0.602768
GFAP_N           1080.0  0.120889  0.013233  0.086114  0.213621
GluR3_N          1080.0  0.221851  0.034886  0.111382  0.331016
GluR4_N          1080.0  0.126560  0.026885  0.072580  0.537004
IL1B_N           1080.0  0.527349  0.082057  0.284001  0.889735
P3525_N          1080.0  0.291276  0.030015  0.207438  0.443735
pCASP9_N         1080.0  1.548348  0.248132  0.853176  2.586216
PSD95_N          1080.0  2.235236  0.254395  1.206098  2.877873
SNCA_N           1080.0  0.159821  0.024150  0.101233  0.257616
Ubiquitin_N      1080.0  1.239270  0.173580  0.750664  1.897202
pGSK3B_Tyr216_N  1080.0  0.848767  0.094311  0.577397  1.204598
SHH_N            1080.0  0.226676  0.028989  0.155869  0.358289
BAD_N             867.0  0.157914  0.029537  0.088305  0.282016
BCL2_N            795.0  0.134762  0.027417  0.080657  0.261506
pCFOS_N          1005.0  0.131053  0.023863  0.085419  0.256529
SYP_N            1080.0  0.446073  0.066432  0.258626  0.759588
H3AcK18_N         900.0  0.169609  0.059402  0.079691  0.479763
EGR1_N            870.0  0.183135  0.040406  0.105537  0.360692
H3MeK4_N          810.0  0.205440  0.055514  0.101787  0.413903
CaNA_N           1080.0  1.337784  0.317126  0.586479  2.129791

In [7]:
# Categorical Feature Statistics
cat_stats

               value  count    pct
column  rank
MouseID 1      18899     15   1.39
        2        293     15   1.39
        3        294     15   1.39
        4        309     15   1.39
        5        311     15   1.39
class   1     c-CS-m    150  13.89
        2     c-SC-m    150  13.89
        3     c-CS-s    135  12.50
        4     c-SC-s    135  12.50
        5     t-CS-m    135  12.50

In [8]:
# Target Distribution
target_df

        count    pct
class
c-CS-m    150  13.89
c-SC-m    150  13.89
c-CS-s    135  12.50
c-SC-s    135  12.50
t-CS-m    135  12.50
t-SC-m    135  12.50
t-SC-s    135  12.50
t-CS-s    105   9.72

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
    group_labels=task_mold.group_labels,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Providing recommendations based on number of groups (72).
Recommended splits: n_repeats=20, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_grouped_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    group_on=task_mold.group_on,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
    group_labels=task_mold.group_labels,
    show_splits=True,
    target_on=task_mold.target_column_name,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="We create stratified grouped 20-repeated 3-fold split. This creates 24 group members (360 samples) per test set.",
    splits=splits
)

Using Stratified Grouped splits.
Using label-per-group grouped splits.
Creating index-based splits for 72 groups
Using Stratified IID splits.
Repeat 0, Fold 0:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-SC-m': 0.14583333333333334, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-CS-m': 0.16666666666666666, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 0, Fold 1:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-SC-m': 0.16666666666666666, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 0, Fold 2:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-SC-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            	Test target distribution: {'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-CS-s': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 1, Fold 0:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-SC-m': 0.14583333333333334, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-CS-m': 0.16666666666666666, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 1, Fold 1:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-SC-m': 0.16666666666666666, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 1, Fold 2:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-SC-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            	Test target distribution: {'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-CS-s': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 2, Fold 0:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-SC-m': 0.14583333333333334, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-CS-m': 0.16666666666666666, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 2, Fold 1:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-SC-m': 0.16666666666666666, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 2, Fold 2:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-SC-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            	Test target distribution: {'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-CS-s': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 3, Fold 0:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-SC-m': 0.14583333333333334, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-CS-m': 0.16666666666666666, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 3, Fold 1:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-SC-m': 0.16666666666666666, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 3, Fold 2:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-SC-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            	Test target distribution: {'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-CS-s': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 4, Fold 0:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-SC-m': 0.14583333333333334, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-CS-m': 0.16666666666666666, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 4, Fold 1:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-SC-m': 0.16666666666666666, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 4, Fold 2:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-SC-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            	Test target distribution: {'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-CS-s': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 5, Fold 0:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-SC-m': 0.14583333333333334, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-CS-m': 0.16666666666666666, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 5, Fold 1:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-SC-m': 0.16666666666666666, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 5, Fold 2:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-SC-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            	Test target distribution: {'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-CS-s': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 6, Fold 0:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-SC-m': 0.14583333333333334, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-CS-m': 0.16666666666666666, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 6, Fold 1:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-SC-m': 0.16666666666666666, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 6, Fold 2:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-SC-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            	Test target distribution: {'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-CS-s': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 7, Fold 0:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-SC-m': 0.14583333333333334, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-CS-m': 0.16666666666666666, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 7, Fold 1:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-SC-m': 0.16666666666666666, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 7, Fold 2:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-SC-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            	Test target distribution: {'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-CS-s': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 8, Fold 0:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-SC-m': 0.14583333333333334, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-CS-m': 0.16666666666666666, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 8, Fold 1:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-SC-m': 0.16666666666666666, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 8, Fold 2:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-SC-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            	Test target distribution: {'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-CS-s': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 9, Fold 0:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-SC-m': 0.14583333333333334, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-CS-m': 0.16666666666666666, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 9, Fold 1:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-SC-m': 0.16666666666666666, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 9, Fold 2:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-SC-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            	Test target distribution: {'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-CS-s': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 10, Fold 0:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-SC-m': 0.14583333333333334, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-CS-m': 0.16666666666666666, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 10, Fold 1:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-SC-m': 0.16666666666666666, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 10, Fold 2:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-CS-m': 0.14583333333333334, 'c-SC-m': 0.14583333333333334, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            	Test target distribution: {'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-CS-s': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 11, Fold 0:
            Train N: 720, Test N: 360
            Target Distribution:
            	Train target distribution: {'c-SC-m': 0.14583333333333334, 'c-CS-m': 0.125, 'c-CS-s': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.10416666666666667}
            	Test target distribution: {'c-CS-m': 0.16666666666666666, 'c-CS-s': 0.125, 'c-SC-m': 0.125, 'c-SC-s': 0.125, 't-CS-m': 0.125, 't-SC-m': 0.125, 't-SC-s': 0.125, 't-CS-s': 0.08333333333333333}
            Group Distribution MouseID:
            	Train: 48
            	Test: 24

Repeat 11, Fold 1:
            Train N: 720, Test N: 360
            Target Distribution:

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to mice_protein_trisomy_discriminant/019d3198-e47c-7c16-8878-751d864d733a
019d3198-e47c-7c16-8878-751d864d733a
30c64cbd348be8ecf7a4d839a948effc287005d784aafccf75b2f0ef209f25bb