### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="splice",
    dataset_year="1991",
    domain_str="biology & life sciences",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C5M888",
    download_description="""
We download the data from the UCI repository and unzip it to a predefined folder.

mkdir -p local-data-warehouse/splice/ && wget -P local-data-warehouse/splice/ https://archive.ics.uci.edu/static/public/69/molecular+biology+splice+junction+gene+sequences.zip && unzip local-data-warehouse/splice/molecular+biology+splice+junction+gene+sequences.zip -d local-data-warehouse/splice/
""",
    # References
    academic_reference_bibtex="""@article{towell1994knowledge,
  title={Knowledge-based artificial neural networks},
  author={Towell, Geoffrey G and Shavlik, Jude W},
  journal={Artificial intelligence},
  volume={70},
  number={1-2},
  pages={119--165},
  year={1994},
  publisher={Elsevier}
}
""",
    academic_reference_bibtex_key="towell1994knowledge",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
- We tabularized the fixed-size DNA sequences from the original dataset based on the nucleotide position.
- We removed the instance ID.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="SiteType",
    problem_type="multiclass_classification",
    objective_metric_name="log_loss",
    stratify_on="SiteType",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(f"{dataset_mold.path}/splice.data", index_col=False, header=None)

# Strip tab-like whitespaces from original data
df = df.map(lambda x: x.strip())
df = df.drop(columns=[1])  # Drop instance ID
target_feature = "SiteType"

split_data = df[2].apply(lambda x: pd.Series(list(x)))
# Generate new column names from -30 to +30 excluding 0
split_data.columns = [f"position_{i}" for i in range(-30, 31) if i != 0]
split_data[target_feature] = df[0]
df = split_data

cat_features = [f"position_{i}" for i in range(-30, 31) if i != 0] + [target_feature]

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

df[cat_features] = df[cat_features].astype("category")

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 3,190
Columns: 61
Use sampling: False (sample size: 3,190)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['position_6', 'position_5', 'position_-3', 'position_-29', 'position_-30', 'position_-9', 'position_-8', 'position_-7', 'position_-6', 'position_-12']
Rows remaining as candidates after top-10 filter: 499 (of 3,190)

#### Duplicate Report
Total duplicate rows: 184 (5.77% of dataset)
Duplicate rows ignoring target: 185 (5.80% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,position_-30,position_-29,position_-28,position_-27,position_-26,position_-25,position_-24,position_-23,position_-22,position_-21,position_-20,position_-19,position_-18,position_-17,position_-16,position_-15,position_-14,position_-13,position_-12,position_-11,position_-10,position_-9,position_-8,position_-7,position_-6,position_-5,position_-4,position_-3,position_-2,position_-1,position_1,position_2,position_3,position_4,position_5,position_6,position_7,position_8,position_9,position_10,position_11,position_12,position_13,position_14,position_15,position_16,position_17,position_18,position_19,position_20,position_21,position_22,position_23,position_24,position_25,position_26,position_27,position_28,position_29,position_30,SiteType
0,T,C,C,T,T,G,A,C,C,T,G,G,G,T,T,C,C,C,C,C,T,C,T,C,C,T,G,C,A,G,A,A,C,G,A,T,T,C,C,C,T,G,A,T,G,A,G,G,C,A,G,A,T,G,C,G,G,G,A,A,IE
1,T,T,G,A,T,A,A,C,A,T,G,A,C,A,T,T,T,T,C,C,T,T,T,T,C,T,A,C,A,G,A,A,T,G,A,A,A,C,A,G,T,A,G,A,A,G,T,C,A,T,C,T,C,A,G,A,A,A,T,G,IE
2,C,A,T,G,C,C,T,T,G,A,A,T,T,T,C,T,T,T,T,C,T,G,C,A,C,G,A,C,A,G,G,T,C,T,G,C,C,A,G,C,T,T,A,C,A,T,T,T,A,C,C,C,A,A,A,C,T,G,T,C,IE
3,G,A,T,T,C,T,C,T,T,C,A,G,C,C,A,A,T,C,T,T,C,A,T,T,G,C,T,C,A,A,G,T,A,T,G,A,C,T,T,T,A,A,T,C,T,T,C,C,T,T,A,C,A,A,C,T,A,G,G,T,EI
4,T,C,C,C,T,C,C,A,T,T,G,C,C,C,T,C,C,G,G,T,T,T,C,T,C,C,C,C,A,G,G,C,T,C,C,C,G,G,A,C,G,T,C,C,C,T,G,C,T,C,C,T,G,G,C,T,T,T,T,G,IE

In [5]:
# Feature Summary
summary

           index     dtype  n_missing  pct_missing  n_unique          examples
0   position_-30  category        0.0          0.0       5.0     G, C, A, T, D
1   position_-29  category        0.0          0.0       5.0     C, G, A, T, D
2   position_-28  category        0.0          0.0       4.0        C, G, T, A
3   position_-27  category        0.0          0.0       4.0        C, G, A, T
4   position_-26  category        0.0          0.0       4.0        C, T, A, G
5   position_-25  category        0.0          0.0       4.0        C, G, T, A
6   position_-24  category        0.0          0.0       4.0        C, A, G, T
7   position_-23  category        0.0          0.0       4.0        C, T, A, G
8   position_-22  category        0.0          0.0       4.0        C, T, A, G
9   position_-21  category        0.0          0.0       4.0        T, C, A, G
10  position_-20  category        0.0          0.0       4.0        T, C, G, A
11  position_-19  category        0.0          0.0       4.0        C, G, T, A
12  position_-18  category        0.0          0.0       4.0        C, T, G, A
13  position_-17  category        0.0          0.0       5.0     C, A, T, G, N
14  position_-16  category        0.0          0.0       4.0        C, T, G, A
15  position_-15  category        0.0          0.0       4.0        C, T, A, G
16  position_-14  category        0.0          0.0       4.0        T, C, G, A
17  position_-13  category        0.0          0.0       4.0        T, C, G, A
18  position_-12  category        0.0          0.0       5.0     C, T, G, A, N
19  position_-11  category        0.0          0.0       5.0     T, C, A, G, N
20  position_-10  category        0.0          0.0       5.0     C, T, G, A, N
21   position_-9  category        0.0          0.0       5.0     C, T, G, A, N
22   position_-8  category        0.0          0.0       5.0     C, T, G, A, N
23   position_-7  category        0.0          0.0       5.0     C, T, G, A, N
24   position_-6  category        0.0          0.0       5.0     C, T, G, A, N
25   position_-5  category        0.0          0.0       5.0     T, C, A, G, N
26   position_-4  category        0.0          0.0       5.0     C, G, A, T, N
27   position_-3  category        0.0          0.0       5.0     C, A, T, G, N
28   position_-2  category        0.0          0.0       5.0     A, C, G, T, N
29   position_-1  category        0.0          0.0       5.0     G, A, T, C, N
30    position_1  category        0.0          0.0       5.0     G, A, C, T, N
31    position_2  category        0.0          0.0       5.0     T, A, C, G, N
32    position_3  category        0.0          0.0       5.0     A, G, C, T, N
33    position_4  category        0.0          0.0       5.0     A, G, C, T, N
34    position_5  category        0.0          0.0       6.0  G, C, T, A, N, R
35    position_6  category        0.0          0.0       6.0  T, C, G, A, N, S
36    position_7  category        0.0          0.0       5.0     G, A, C, T, N
37    position_8  category        0.0          0.0       5.0     C, G, A, T, N
38    position_9  category        0.0          0.0       5.0     C, G, T, A, N
39   position_10  category        0.0          0.0       5.0     G, C, T, A, N
40   position_11  category        0.0          0.0       5.0     G, C, T, A, N
41   position_12  category        0.0          0.0       5.0     G, C, T, A, N
42   position_13  category        0.0          0.0       5.0     G, C, A, T, N
43   position_14  category        0.0          0.0       5.0     C, G, T, A, N
44   position_15  category        0.0          0.0       5.0     C, G, A, T, N
45   position_16  category        0.0          0.0       5.0     G, C, A, T, N
46   position_17  category        0.0          0.0       5.0     G, T, C, A, N
47   position_18  category        0.0          0.0       5.0     G, C, A, T, N
48   position_19  category        0.0          0.0       5.0     G, C, A, T, N
49   position_20  category        0.0          0.0       5.0     G, C, A, T, N
50   position_21  category        0.0          0.0       5.0     G, C, T, A, N
51   position_22  category        0.0          0.0       5.0     G, A, C, T, N
52   position_23  category        0.0          0.0       5.0     G, C, T, A, N
53   position_24  category        0.0          0.0       5.0     G, C, T, A, N
54   position_25  category        0.0          0.0       5.0     G, C, A, T, N
55   position_26  category        0.0          0.0       5.0     G, C, T, A, N
56   position_27  category        0.0          0.0       5.0     G, C, T, A, N
57   position_28  category        0.0          0.0       5.0     C, G, T, A, N
58   position_29  category        0.0          0.0       5.0     C, G, A, T, N
59   position_30  category        0.0          0.0       5.0     G, C, T, A, N
60      SiteType  category        0.0          0.0       3.0         N, IE, EI

In [6]:
# Numeric Feature Statistics
numeric_stats

'No numeric features to summarize.'

In [7]:
# Categorical Feature Statistics
cat_stats

                  value  count    pct
column       rank
SiteType     1        N   1655  51.88
             2       IE    768  24.08
             3       EI    767  24.04
position_-1  1        G   1822  57.12
             2        A    474  14.86
             3        T    451  14.14
             4        C    442  13.86
             5        N      1   0.03
position_-10 1        C    938  29.40
             2        T    913  28.62
             3        G    697  21.85
             4        A    640  20.06
             5        N      2   0.06
position_-11 1        T    935  29.31
             2        C    889  27.87
             3        A    693  21.72
             4        G    671  21.03
             5        N      2   0.06
position_-12 1        C    921  28.87
             2        T    899  28.18
             3        G    712  22.32
             4        A    657  20.60
             5        N      1   0.03
position_-13 1        T    906  28.40
             2        C    889  27.87
             3        G    746  23.39
             4        A    649  20.34
position_-14 1        T    911  28.56
             2        C    908  28.46
             3        G    701  21.97
             4        A    670  21.00
position_-15 1        C    949  29.75
             2        T    857  26.87
             3        A    700  21.94
             4        G    684  21.44
position_-16 1        C    959  30.06
             2        T    798  25.02
             3        G    768  24.08
             4        A    665  20.85
position_-17 1        C    898  28.15
             2        A    797  24.98
             3        T    782  24.51
             4        G    712  22.32
             5        N      1   0.03
position_-18 1        C    878  27.52
             2        T    822  25.77
             3        G    752  23.57
             4        A    738  23.13
position_-19 1        C    930  29.15
             2        G    807  25.30
             3        T    785  24.61
             4        A    668  20.94
position_-2  1        A   1613  50.56
             2        C    536  16.80
             3        G    523  16.39
             4        T    517  16.21
             5        N      1   0.03
position_-20 1        T    872  27.34
             2        C    823  25.80
             3        G    778  24.39
             4        A    717  22.48
position_-21 1        T    849  26.61
             2        C    808  25.33
             3        A    767  24.04
             4        G    766  24.01
position_-22 1        C    909  28.50
             2        T    783  24.55
             3        A    749  23.48
             4        G    749  23.48
position_-23 1        C    878  27.52
             2        T    791  24.80
             3        A    790  24.76
             4        G    731  22.92
position_-24 1        C    858  26.90
             2        A    783  24.55
             3        G    780  24.45
             4        T    769  24.11
position_-25 1        C    898  28.15
             2        G    828  25.96
             3        T    760  23.82
             4        A    704  22.07
position_-26 1        C    865  27.12
             2        T    805  25.24
             3        A    801  25.11
             4        G    719  22.54
position_-27 1        C    884  27.71
             2        G    802  25.14
             3        A    753  23.61
             4        T    751  23.54
position_-28 1        C    876  27.46
             2        G    841  26.36
             3        T    761  23.86
             4        A    712  22.32
position_-29 1        C    858  26.90
             2        G    794  24.89
             3        A    779  24.42
             4        T    758  23.76
             5        D      1   0.03
position_-3  1        C   1309  41.03
             2        A    696  21.82
             3        T    608  19.06
             4        G    576  18.06
             5        N      1   0.03
position_-30 1        G    876  27.46
             2        C    835  26.18
             3        A    743  23.29
             4        T    735  23.04
             5        D      1   0.03
position_-4  1        C    883  27.68
             2        G    855  26.80
             3        A    769  24.11
             4        T    682  21.38
             5        N      1   0.03
position_-5  1        T    970  30.41
             2        C    892  27.96
             3        A    667  20.91
             4        G    660  20.69
             5        N      1   0.03
position_-6  1        C    946  29.66
             2        T    887  27.81
             3        G    704  22.07
             4        A    652  20.44
             5        N      1   0.03
position_-7  1        C    952  29.84
             2        T    893  27.99
             3        G    706  22.13
             4        A    638  20.00
             5        N      1   0.03
position_-8  1        C    968  30.34
             2        T    857  26.87
             3        G    702  22.01
             4        A    662  20.75
             5        N      1   0.03
position_-9  1        C    923  28.93
             2        T    848  26.58
             3        G    716  22.45
             4        A    702  22.01
             5        N      1   0.03
position_1   1        G   1592  49.91
             2        A    595  18.65
             3        C    514  16.11
             4        T    488  15.30
             5        N      1   0.03
position_10  1        G    925  29.00
             2        C    819  25.67
             3        T    745  23.35
             4        A    700  21.94
             5        N      1   0.03
position_11  1        G    914  28.65
             2        C    794  24.89
             3        T    762  23.89
             4        A    719  22.54
             5        N      1   0.03
position_12  1        G    916  28.71
             2        C    816  25.58
             3        T    755  23.67
             4        A    702  22.01
             5        N      1   0.03
position_13  1        G    910  28.53
             2        C    845  26.49
             3        A    720  22.57
             4        T    713  22.35
             5        N      2   0.06
position_14  1        C    841  26.36
             2        G    838  26.27
             3        T    780  24.45
             4        A    730  22.88
             5        N      1   0.03
position_15  1        C    885  27.74
             2        G    822  25.77
             3        A    757  23.73
             4        T    725  22.73
             5        N      1   0.03
position_16  1        G    871  27.30
             2        C    844  26.46
             3        A    768  24.08
             4        T    706  22.13
             5        N      1   0.03
position_17  1        G    915  28.68
             2        T    770  24.14
             3        C    769  24.11
             4        A    735  23.04
             5        N      1   0.03
position_18  1        G    912  28.59
             2        C    800  25.08
             3        A    761  23.86
             4        T    716  22.45
             5        N      1   0.03
position_19  1        G    945  29.62
             2        C    849  26.61
             3        A    725  22.73
             4        T    669  20.97
             5        N      2   0.06
position_2   1        T   1428  44.76
             2        A    606  19.00
             3        C    579  18.15
             4        G    576  18.06
             5        N      1   0.03
position_20  1        G    836  26.21
             2        C    807  25.30
             3        A    778  24.39
             4        T    766  24.01
             5        N      3   0.09
position_21  1        G    902  28.28
             2        C    881  27.62
             3        T    711  22.29
             4        A    695  21.79
             5        N      1   0.03
position_22  1        G    874  27.40
             2        A    818  25.64
             3        C    788  24.70
             4        T    709  22.23
             5        N      1   0.03
position_23  1        G    874  27.40
             2        C    832  26.08
             3        T    750  23.51
             4        A    733  22.98
             5        N      1   0.03
position_24  1        G    934  29.28
             2        C    818  25.64
             3        T    742  23.26
             4        A    695  21.79
             5        N      1   0.03
position_25  1        G    859  26.93
             2        C    835  26.18
             3        A    802  25.14
             4        T    693  21.72
             5        N      1   0.03
position_26  1        G    838  26.27
             2        C    831  26.05
             3        T    763  23.92
             4        A    756  23.70
             5        N      2   0.06
position_27  1        G    908  28.46
             2        C    790  24.76
             3        T    748  23.45
             4        A    743  23.29
             5        N      1   0.03
position_28  1        C    870  27.27
             2        G    866  27.15
             3        T    733  22.98
             4        A    720  22.57
             5        N      1   0.03
position_29  1        C    860  26.96
             2        G    789  24.73
             3        A    785  24.61
             4        T    755  23.67
             5        N      1   0.03
position_3   1        A    982  30.78
             2        G    951  29.81
             3        C    637  19.97
             4        T    617  19.34
             5        N      3   0.09
position_30  1        G    953  29.87
             2        C    785  24.61
             3        T    730  22.88
             4        A    721  22.60
             5        N      1   0.03
position_4   1        A   1121  35.14
             2        G    751  23.54
             3        C    710  22.26
             4        T    607  19.03
             5        N      1   0.03
position_5   1        G   1201  37.65
             2        C    708  22.19
             3        T    665  20.85
             4        A    614  19.25
             5        N      1   0.03
position_6   1        T    931  29.18
             2        C    810  25.39
             3        G    765  23.98
             4        A    682  21.38
             5        N      1   0.03
position_7   1        G    968  30.34
             2        A    813  25.49
             3        C    736  23.07
             4        T    671  21.03
             5        N      2   0.06
position_8   1        C    866  27.15
             2        G    822  25.77
             3        A    750  23.51
             4        T    748  23.45
             5        N      4   0.13
position_9   1        C    879  27.55
             2        G    840  26.33
             3        T    757  23.73
             4        A    713  22.35
             5        N      1   0.03

In [8]:
# Target Distribution
target_df

          count    pct
SiteType
N          1655  51.88
IE          768  24.08
EI          767  24.04

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=10, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to splice/019d7369-b922-718a-adbf-099484b95908
019d7369-b922-718a-adbf-099484b95908
d25acd20577bcac3c95cbb8c7e84a14a91e73d76d55764f01eb4146c3618cf78