### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="cooking_time_1m",
    version_from_unique_name="cooking_time",
    version_comment="""
We randomly sub-sample the train to 1 million and test data 250k rows. We follow TabReD and use random sub-sampling. The idea behind this instead of a time-based subsampling is to keep data from various time periods and model the distribution shift across the full time horizon.
""",
    # Same as cooking_time.ipynb
    dataset_year="2024",
    domain_str="industry & manufacturing",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/datasets/pcovkrd84mejm/cooking-time",
    download_description="""
We get the TabRed data from Kaggle.

kaggle datasets download -d pcovkrd84mejm/cooking-time -f cooking_time.parquet && unzip cooking_time.parquet.zip && rm cooking_time.parquet.zip
mkdir -p local-data-warehouse/cooking_time && mv cooking_time.parquet local-data-warehouse/cooking_time/
""",
    # References
    academic_reference_bibtex="""@inproceedings{rubachev2025tabred,
  title={TabReD: Analyzing Pitfalls and Filling the Gaps in Tabular Deep Learning Benchmarks},
  author={Rubachev, Ivan and Kartashev, Nikolay and Gorishniy, Yury and Babenko, Artem},
  booktitle={The Thirteenth International Conference on Learning Representations},
  year={2025},
}
""",
    academic_reference_bibtex_key="rubachev2025tabred",
    license="CC-BY-NC-SA-4.0",
    data_tags=["Non-IID", "Temporal", "Anonymized"],
    curation_comments="""
We start with data from TabRed, which already comes preprocessed.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="cooking_time_minutes",
    problem_type="regression",
    objective_metric_name="rmse",
    time_on="timestamp",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

df = pd.read_parquet(dataset_mold.path / "cooking_time.parquet")
print("Loaded data shape:", df.shape)

df["timestamp"] = pd.to_datetime(df["timestamp"])

# Following TabRed
df = df[df["cooking_time_minutes"] >= 1.0]

# We take all bin + cat as Category
cat_cols = [c for c in df.columns if c.startswith("cat") or c.startswith("bin")]
df[cat_cols] = df[cat_cols].astype("category")

df["cooking_time_minutes"] = np.log(df["cooking_time_minutes"])

df = df.sort_values(by="timestamp").reset_index(drop=True)

Loaded data shape: (12799642, 197)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 12,799,474
Columns: 197
Use sampling: True (sample size: 1,279,947)
Get missing and unique counts per column...

missing/unique per-col:   0%|          | 0/197 [00:00<?, ?it/s]

Get example values per column...

examples per-col:   0%|          | 0/197 [00:00<?, ?it/s]

Get numeric feature statistics...

numeric stats:   0%|          | 0/187 [00:00<?, ?it/s]

Get cat stats...

cat stats:   0%|          | 0/10 [00:00<?, ?it/s]

Get target stats...
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['num_20', 'num_16', 'num_19', 'num_17', 'num_18', 'num_24', 'num_25', 'num_30', 'num_27', 'num_26']
Rows remaining as candidates after top-10 filter: 743,569 (of 12,799,474)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...

hash cols:   0%|          | 0/197 [00:00<?, ?it/s]

group check:   0%|          | 0/197 [00:00<?, ?it/s]

Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,num_0,num_1,num_2,num_3,num_4,num_5,num_6,num_7,num_8,num_9,num_10,num_11,num_12,num_13,num_14,num_15,num_16,num_17,num_18,num_19,num_20,num_21,num_22,num_23,num_24,num_25,num_26,num_27,num_28,num_29,num_30,num_31,num_32,num_33,num_34,num_35,num_36,num_37,num_38,num_39,num_40,num_41,num_42,num_43,num_44,num_45,num_46,num_47,num_48,num_49,num_50,num_51,num_52,num_53,num_54,num_55,num_56,num_57,num_58,num_59,num_60,num_61,num_62,num_63,num_64,num_65,num_66,num_67,num_68,num_69,num_70,num_71,num_72,num_73,num_74,num_75,num_76,num_77,num_78,num_79,num_80,num_81,num_82,num_83,num_84,num_85,num_86,num_87,num_88,num_89,num_90,num_91,num_92,num_93,num_94,num_95,num_96,num_97,num_98,num_99,num_100,num_101,num_102,num_103,num_104,num_105,num_106,num_107,num_108,num_109,num_110,num_111,num_112,num_113,num_114,num_115,num_116,num_117,num_118,num_119,num_120,num_121,num_122,num_123,num_124,num_125,num_126,num_127,num_128,num_129,num_130,num_131,num_132,num_133,num_134,num_135,num_136,num_137,num_138,num_139,num_140,num_141,num_142,num_143,num_144,num_145,num_146,num_147,num_148,num_149,num_150,num_151,num_152,num_153,num_154,num_155,num_156,num_157,num_158,num_159,num_160,num_161,num_162,num_163,num_164,num_165,num_166,num_167,num_168,num_169,num_170,num_171,num_172,num_173,num_174,num_175,num_176,num_177,num_178,num_179,num_180,num_181,num_182,num_183,num_184,num_185,bin_0,bin_1,bin_2,cat_0,cat_1,cat_2,cat_3,cat_4,cat_5,timestamp,cooking_time_minutes
0,-0.681594,-3.102334,0.444534,0.511699,0.381675,-1.044438,-1.684454,-1.664196,-0.003764,1.480534,0.413874,-0.973340,-1.560785,-1.559244,-0.017181,0.683092,-3.449218,-0.859161,-0.272515,0.244094,0.843248,-5.199337,-1.624522,-0.221422,0.777329,2.132002,0.983219,-1.717545,-0.852424,-0.332343,0.422873,0.015853,-0.208505,-0.116947,-0.200814,0.034749,-0.400006,1.199766,0.048950,-0.365532,0.078047,-0.160011,0.085670,-0.400641,0.601439,-0.254901,-0.559204,-0.002562,-0.236594,-0.290899,-0.119953,0.406079,-0.443624,-0.601947,-0.406435,-0.529372,-0.397571,-0.838778,0.595437,-0.239379,-0.683596,0.167483,-0.223767,-0.250444,-0.129119,-0.303168,-0.450248,-0.607366,-0.256453,-0.540588,-0.356790,-0.864245,-0.099274,0.087933,-0.392493,0.164347,-0.115160,0.124527,-0.362871,0.360172,-1.189522,-1.197193,-1.079690,-0.294859,-1.374878,-0.651824,-1.664082,0.366873,-0.910873,-1.084195,-0.167640,-1.023003,-0.599937,-1.261282,0.199538,-0.794462,0.876022,-0.334851,-0.790772,-0.353041,-0.605961,0.441766,-0.975463,0.322932,-0.083574,-0.875455,-0.418828,-0.819792,0.647177,-0.667420,-0.338834,-0.862717,-0.532584,-0.306122,-0.121994,0.315012,-0.805692,-0.250015,-0.689529,-0.687339,-0.481193,-0.422177,0.530745,-0.857097,-0.880888,-0.047692,-0.890172,-0.457033,-1.077446,0.127053,-0.814401,0.879040,0.837338,0.157470,-0.624145,-0.610484,-0.830234,0.158552,-0.857097,NaN,NaN,NaN,NaN,-0.765908,-0.824933,NaN,NaN,NaN,NaN,-0.725954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.144896,-0.726606,1.0,1.0,0.0,1859,1,236,2675,2,2,2023-11-15 00:00:01,2.452441
1,0.573115,-3.102334,0.913155,-0.492944,0.422712,-0.874910,-1.312398,-1.303162,-0.089996,1.291961,0.389340,-0.913414,-1.314144,-1.281020,-0.123809,0.919959,-2.633894,-0.845622,-0.262506,0.253654,0.856805,-4.325760,-1.624449,-0.221401,0.777356,2.132189,0.983224,-1.717529,-0.852419,-0.332340,0.422876,-2.208501,-2.200761,-2.197654,-2.210861,-2.206982,-2.210644,-2.156653,-2.207876,-2.209828,-2.190933,-2.211842,-2.205113,-2.212413,-2.204020,-2.208467,-2.211699,-2.202031,-2.210622,-2.211230,-2.210030,-2.078677,-2.210065,-2.212500,-2.204582,-2.208765,-2.204990,-2.209472,-1.489621,-2.208218,-2.211330,-2.195002,-2.208313,-2.212440,-2.207500,-2.173822,-2.210134,-2.211267,-2.204342,-2.205216,-2.206745,-2.213031,-1.837738,-2.210472,-2.212087,-2.182674,-2.207037,-2.205777,-2.211176,-2.207600,-2.212818,1.035892,0.517903,1.792319,1.180354,1.510628,0.996639,-1.895259,1.069054,0.514119,1.856233,1.189936,1.587907,0.984365,-2.013672,1.105985,0.673933,1.916603,1.238948,1.597122,1.037123,-1.892598,1.092721,0.588062,1.877535,1.232223,1.575943,1.035348,-1.292465,1.113878,0.717786,1.954118,1.254346,1.617762,1.050386,-2.158637,1.089789,0.567856,1.858912,1.227308,1.565231,1.032745,-1.674186,1.076834,0.800928,1.908012,1.234565,1.592124,1.074783,-2.107953,0.870853,1.236652,0.837338,0.880888,0.738089,0.279964,0.086674,0.824850,1.315958,1.197193,0.987651,0.043924,-0.857097,1.556246,1.125776,0.758004,1.042247,-0.220058,-0.857097,1.608844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.144896,-0.092972,0.0,1.0,0.0,31477,11521,455,331,2,104220,2023-11-15 00:00:15,3.142715
2,0.573115,-3.102334,1.355133,-0.984601,-1.654088,-1.631533,-0.897525,0.046433,0.560024,-1.041709,-1.558282,-1.592492,-0.890815,0.046395,0.535971,1.520245,-2.613214,-0.844628,-0.261798,0.254356,0.857802,-4.309645,-1.624444,-0.221399,0.777358,2.132204,0.983224,-1.717528,-0.852418,-0.332340,0.422877,1.159109,1.825266,0.479695,1.227574,0.997627,1.170838,1.199766,1.235029,1.645240,0.280912,1.253925,0.975789,1.418119,0.601439,1.231945,1.538076,0.724395,1.354202,1.116080,1.565532,-0.166367,1.254175,1.327331,0.592252,1.187943,0.974760,1.213321,0.069056,1.447437,1.334904,0.950148,1.418592,1.201030,1.526252,-0.345485,0.961270,0.986596,0.844230,1.033320,1.060814,1.002767,-0.051460,1.189523,1.583475,0.363283,1.206455,0.977487,1.303971,0.360172,0.335080,1.258536,1.637002,0.826701,1.233280,1.094116,1.163652,0.366873,1.325847,1.567663,0.695907,1.249966,0.970154,1.346388,0.199538,1.316906,1.384287,0.907279,1.263551,0.920549,1.384149,-0.733156,1.288202,1.242163,0.851538,1.209489,0.958501,1.256088,-0.648724,1.354900,1.276298,1.053359,1.346579,1.029078,1.439337,-0.830234,1.224672,1.089238,1.063546,1.188923,1.098946,1.188072,-0.728240,1.346386,1.537692,0.728240,1.252437,0.990280,1.354294,0.127053,0.213636,-0.002509,-0.209787,-0.778225,-0.357496,-0.490250,-0.997920,0.411333,0.357496,0.672129,0.369558,0.816150,1.044409,0.018820,0.434861,0.832006,0.530745,0.862544,1.040090,0.091712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.144896,0.121995,0.0,1.0,0.0,1280,569,761,1135,2,7071,2023-11-15 00:00:17,3.426432
3,0.573115,-3.102334,0.489308,0.103938,-0.188562,-0.076604,-0.229802,-0.446735,-1.740439,0.363174,-0.200690,-0.103349,-0.265030,-0.492926,-1.623380,0.102567,-2.415047,-0.832910,-0.253136,0.262999,0.869852,-4.169747,-1.624376,-0.221380,0.777382,2.132376,0.983229,-1.717513,-0.852414,-0.332337,0.422879,0.651444,0.318623,0.526309,0.576115,0.214812,0.866135,0.046436,0.625733,0.683901,0.552530,0.619668,0.421748,0.659639,0.601439,0.508053,0.000521,0.440684,0.387350,0.388745,0.314386,-0.839121,0.525845,0.629362,0.224979,0.520625,0.365523,0.650231,-0.583992,0.300420,-0.463993,0.607995,0.199753,0.202081,0.047491,-0.969427,0.554197,0.568755,0.272813,0.514957,0.383737,0.611463,-0.943004,0.712520,0.628725,0.643572,0.716411,0.541246,0.874634,0.360172,0.797210,0.168182,-0.160888,0.667792,0.196282,0.198511,0.036964,-0.584984,0.165822,0.167640,0.639404,0.235922,0.190584,0.007464,0.199538,0.250529,-0.749274,0.649612,0.230285,0.249930,0.281663,-1.175638,0.092714,-0.354743,0.509204,0.082109,0.186631,0.171329,-1.037507,0.212225,-1.259023,0.785215,0.176943,0.274832,0.112138,-1.244778,0.130240,-0.469663,0.535007,0.068442,0.214848,0.120306,-1.284409,0.142245,0.098013,0.664288,0.226185,0.173687,0.257495,0.127053,0.586683,0.473810,0.209787,0.116941,0.329548,-0.048948,-0.020074,0.637051,0.723343,0.447305,0.636386,-0.017565,-0.262686,1.213168,0.434861,0.027604,0.754664,0.005018,-0.257495,1.482681,-2.394743,-2.852363,-2.725013,-0.023129,-2.815832,-0.977487,-1.439446,-1.12594,-0.162392,-1.352782,-2.29695,-2.814459,-2.665114,-0.048328,-2.753043,NaN,NaN,NaN,NaN,NaN,-2.389961,-2.686334,-1.164159,-0.025091,-1.775173,-2.389961,-2.169384,-0.696973,-0.026974,-1.204439,-0.023596,-0.024362,-0.02569,-0.024124,0.625670,0.121995,0.0,1.0,1.0,1921,811,1447,2880,2,2,2023-11-15 00:00:28,1.813738
4,-0.681594,-3.102334,-0.823171,1.780213,-0.199602,-0.193110,-0.379130,-0.623922,-1.274571,0.426511,-0.211743,-0.192350,-0.377904,-0.631030,-1.265667,-1.875285,-2.328973,-0.825740,-0.247833,0.268375,0.877587,-4.111143,-1.624334,-0.221368,0.777397,2.132484,0.983231,-1.717504,-0.852411,-0.332335,0.422881,-1.909034,-1.195397,-1.440855,-1.837278,-1.776618,-1.194387,-0.198259,-1.900026,-0.308048,-1.373492,-1.709877,-1.764587,-0.965417,0.601439,-0.372649,-0.512667,0.387215,-0.491202,-0.338793,-0.639021,-0.785036,-1.895091,-0.229042,-0.320302,-1.731697,-1.319299,-1.197098,-0.583992,-0.355951,-0.637251,0.532491,-0.469569,-0.294892,-0.645651,-1.315958,-1.894695,-0.234154,-0.185541,-1.724982,-1.291767,-1.222270,-1.121060,-1.910233,-0.243686,-0.678433,-1.776635,-1.750222,-1.070746,0.360172,-0.713403,-0.659082,-0.056486,-0.899534,0.058999,-1.286702,0.513491,0.366873,-0.524976,0.248427,-0.991746,0.081638,-1.315958,0.503497,0.199538,-1.956910,0.644601,-2.152937,-0.956825,-1.792846,0.021063,0.441766,-0.900040,-0.755712,-0.978836,-0.341535,-1.278888,0.181203,-0.313957,-2.033105,-1.228197,-2.174728,-1.912901,-1.948702,-1.406049,0.315012,-1.762429,-0.564886,-0.961429,-1.691813,-1.751882,-1.616596,0.530745,-0.372246,0.205941,-0.918498,0.069056,-1.310017,0.482248,0.127053,-0.389783,0.473810,0.209787,-0.807429,-0.779924,-1.023003,-1.482760,0.106718,0.357496,0.227777,0.636386,0.340606,0.134645,1.073861,0.007527,-0.802226,-0.514923,-0.233789,0.140977,0.250816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.910600,-0.092972,1.0,1.0,0.0,381,2,363,3502,2,2,2023-11-15 00:00:36,1.950661

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,bin_0,category,0.0,0.00,2.0,"0.0, 1.0"
1,bin_1,category,0.0,0.00,2.0,"1.0, 0.0"
2,bin_2,category,0.0,0.00,2.0,"1.0, 0.0"
3,cat_0,category,0.0,0.00,57924.0,"251, 94, 1327, 889, 1544, 985, 171, 753, 31, 2360"
4,cat_1,category,0.0,0.00,21551.0,"1, 7, 2, 34, 6, 8, 82, 14, 50, 22"
5,cat_2,category,0.0,0.00,10757.0,"120, 172, 381, 361, 196, 758, 170, 148, 478, 111"
6,cat_3,category,0.0,0.00,54791.0,"827, 121, 916, 1085, 86, 706, 288, 2351, 244, 577"
7,cat_4,category,0.0,0.00,3.0,"1, 2, 3"
8,cat_5,category,0.0,0.00,123880.0,"2, 27, 568, 293, 218, 563, 29, 3064, 449, 1026"
9,timestamp,datetime64[us],0.0,0.00,2911998.0,"2023-12-14 16:27:55, 2023-12-10 10:31:13, 2023-12-01 17:19:17, 2023-12-09 16:34:06, 2023-11-19 09:41:28, 2023-12-08 16:33:45, 2023-11-25 15:35:00, 2023-12-28 14:18:49, 2023-12-28 13:46:28, 2023-12-24 15:05:05"
10,num_165,float32,12672342.0,99.01,67.0,"-0.8644, -1.1794, -0.6425, -0.2796, -0.4143, -1.5347, -0.525, -1.9225, -0.1702, -0.0842"
11,num_166,float32,12672342.0,99.01,115428.0,"5.1993, -3.0932, -0.8926, -2.3655, -1.5378, -1.7276, -1.4446, 0.7641, -1.9747, -2.2547"
12,num_167,float32,12672342.0,99.01,115328.0,"-3.0989, -5.1993, -2.1107, -1.2925, -1.8784, -1.4177, 0.9964, -2.387, -1.1135, -1.3906"
13,num_168,float32,12672342.0,99.01,98576.0,"-0.0878, -0.5016, 0.2447, 0.2472, -0.2941, -1.257, -0.0181, -0.0865, -1.3615, 0.1725"
14,num_169,float32,12672342.0,99.01,106014.0,"-1.2316, -1.2311, -1.8807, -1.8038, -1.6003, -1.8447, -1.365, -1.3018, -1.8948, -2.2421"
15,num_155,float32,6036308.0,47.16,68.0,"-0.9775, -0.16, 0.2835, 0.5969, 0.8373, 1.0315, 1.1998, 1.3485, 1.4828, 1.6022"
16,num_156,float32,6036308.0,47.16,5130502.0,"-1.5437, -0.2959, -1.0793, -0.2966, -0.2956, -0.3539, -0.2975, -1.9463, -1.6887, -0.5859"
17,num_157,float32,6036308.0,47.16,4717158.0,"-1.3015, 2.4536, -0.3498, 2.4591, 2.4437, 2.4281, 1.9396, -1.8605, -1.5206, -1.8601"
18,num_158,float32,6036308.0,47.16,4845298.0,"-0.3111, -1.5002, -1.5063, -1.3708, -1.5047, -2.0783, -0.5767, -1.0113, -0.3115, -1.5069"
19,num_159,float32,6036308.0,47.16,3897320.0,"1.5646, 0.4789, 1.5664, 0.9033, 1.963, 1.5354, 1.5731, 0.9153, 0.9221, 1.5722"
20,num_145,float32,3554494.0,27.77,8887.0,"-0.4418, -0.7233, 0.0276, -0.1931, 0.4252, -1.0619, 0.2368, -0.8883, -1.4865, -1.2669"
21,num_146,float32,3554494.0,27.77,2092.0,"-0.3335, 0.0201, 0.3058, 0.5307, -0.8022, 0.7547, 1.0422, -1.218, -0.1575, 0.1778"
22,num_147,float32,3554494.0,27.77,38391.0,"0.2407, 0.5394, 0.7902, -0.1321, -0.5999, 0.9836, 1.1449, -0.0452, 1.3879, 0.3696"
23,num_148,float32,3554494.0,27.77,1969.0,"-0.8571, 0.141, -0.2575, -2.0744, 0.6456, 0.4197, 0.8481, -0.5555, -0.1562, -0.0088"
24,num_139,float32,3476171.0,27.16,9758.0,"-0.5687, -0.8409, 0.2757, -0.1132, -0.3282, 0.0905, -1.1694, -1.0021, -1.58, 0.6014"
25,num_140,float32,3476171.0,27.16,2097.0,"0.6364, -0.4626, 0.1587, -0.1132, 0.3696, -0.9185, 0.9877, 1.6395, -1.325, -0.2901"
26,num_141,float32,3476171.0,27.16,43247.0,"0.1676, 0.4794, 0.7397, -0.2252, 1.1211, 0.9456, -0.7088, -0.1359, 1.3781, 0.3032"
27,num_142,float32,3476171.0,27.16,1962.0,"-0.8571, 0.1346, -0.2627, -2.0854, 0.6425, 0.4156, 0.8553, -0.5584, -0.1626, -0.0163"
28,num_160,float32,3360318.0,26.25,175.0,"-0.3084, -0.4556, -0.3817, -0.5322, -0.2381, -0.612, -0.098, -0.6927, -0.0301, -0.1689"
29,num_161,float32,3360318.0,26.25,7294268.0,"3.0919, 3.0906, 3.0909, 3.0928, 3.0904, 3.0904, 3.0903, 3.0905, 3.0908, 3.0917"
30,num_162,float32,3360318.0,26.25,5464171.0,"3.09, 3.09, 3.09, 3.09, 3.09, 3.0901, 3.09, 3.0899, 3.0901, 3.0901"
31,num_163,float32,3360318.0,26.25,6472002.0,"3.09, -1.6517, 3.09, -1.6573, 3.0901, 3.0901, -0.2525, 3.09, -1.5226, 3.09"
32,num_164,float32,3360318.0,26.25,5733508.0,"3.09, 3.09, 3.09, 3.0901, 3.0902, 3.0903, 3.0902, 3.0902, 3.09, 3.0901"
33,num_150,float32,3318234.0,25.92,251.0,"-1.1794, -0.9476, -1.0956, -0.8809, -1.2734, -0.7597, -1.0188, -0.8197, -0.7023, -0.5969"
34,num_151,float32,3318234.0,25.92,7347580.0,"3.0917, 3.0902, 3.0983, -2.8813, 3.0903, 3.0958, 3.0925, 3.0914, 3.0917, 3.0912"
35,num_152,float32,3318234.0,25.92,5667318.0,"3.09, 3.09, 3.09, 3.0901, 3.09, 3.0899, 3.09, 3.09, 3.0901, 3.0901"
36,num_153,float32,3318234.0,25.92,6484657.0,"3.09, -1.648, 3.09, 3.09, -1.6534, 3.0901, -0.2321, 3.09, -1.5193, 3.09"
37,num_154,float32,3318234.0,25.92,5724998.0,"3.09, 3.0901, 3.09, 3.09, 3.09, 3.0904, 3.0903, 3.0903, 3.0907, 3.0901"
38,num_170,float32,3318234.0,25.92,5.0,"0.0766, -2.39, -1.6113, -1.7688, -1.9769"
39,num_171,float32,3318234.0,25.92,6592807.0,"3.09, 3.09, 3.09, 3.09, 3.0899, 3.09, 3.09, 3.0901, 3.0901, 3.0901"
40,num_172,float32,3318234.0,25.92,6534458.0,"3.09, 3.09, 3.09, 3.09, 3.09, 3.0901, 3.0899, 3.0901, 3.0901, 3.09"
41,num_173,float32,3318234.0,25.92,6484489.0,"3.09, 3.09, -1.6458, 3.0901, -1.6522, 3.09, -0.234, 3.0901, -1.5165, 3.09"
42,num_174,float32,3318234.0,25.92,6341515.0,"-3.0482, -3.0463, -3.0463, -3.0476, -3.0444, -2.6554, -1.994, -3.0489, -2.6533, -3.0439"
43,num_175,float32,3318234.0,25.92,3.0,"0.0402, -2.39, -1.9792"
44,num_176,float32,3318234.0,25.92,6585433.0,"3.09, 3.09, 3.09, 3.09, 3.09, 3.0901, 3.0899, 3.09, 3.0901, 3.0901"
45,num_177,float32,3318234.0,25.92,6549544.0,"3.09, 3.09, 3.09, 3.09, 3.09, 3.0901, 3.0901, 3.09, 3.0901, 3.0899"
46,num_178,float32,3318234.0,25.92,6486453.0,"-1.6504, -1.6557, -0.235, -1.5224, -1.6541, -2.2098, -0.5936, -1.1305, -1.6562, -1.659"
47,num_179,float32,3318234.0,25.92,6325118.0,"-2.7322, 3.09, 3.09, 3.09, 3.09, -2.7348, -2.7343, 3.09, 3.0901, 3.0901"
48,num_180,float32,3318234.0,25.92,6484546.0,"3.09, -1.647, -1.6527, 3.0901, -0.232, 3.09, 3.09, 3.09, -1.5183, 3.0901"
49,num_181,float32,3318234.0,25.92,6482812.0,"-1.6455, -1.6518, -0.2327, -1.5151, -1.6502, -2.2045, -0.5883, -1.1255, -1.6551, -1.6524"
50,num_182,float32,3318234.0,25.92,6488326.0,"-1.6477, -1.6535, -0.2343, -1.5198, -1.652, -0.5926, -2.2129, -1.1264, -1.6568, -1.6541"
51,num_183,float32,3318234.0,25.92,6483586.0,"3.09, 3.09, -1.6431, -1.6497, 3.0901, -0.232, 3.09, 3.09, -1.5138, 3.0901"
52,num_131,float32,1103.0,0.01,34.0,"-0.585, -0.0025, -1.3956, 0.4738, 0.879, 1.2367, 1.5543, 1.838, 2.0965, 2.326"
53,num_132,float32,1103.0,0.01,112.0,"-0.7547, -0.2098, 0.2098, -1.5418, 0.5511, 0.8373, 1.0842, 1.3041, 1.498, 1.6742"
54,num_133,float32,1103.0,0.01,58477.0,"-0.0603, -0.6784, -0.2979, -0.1359, 0.0151, 0.9714, -0.4047, -0.5178, 1.4012, -0.1689"
55,num_134,float32,1103.0,0.01,14396.0,"-0.6456, -0.7799, -0.2614, 0.0025, 0.3084, 0.3295, 0.4404, -0.0515, -0.4529, 0.6943"
56,num_135,float32,1103.0,0.01,129015.0,"0.188, 0.3295, -0.174, 0.0691, -0.0728, 0.5021, 0.0226, -0.0226, 1.1329, 0.2927"
57,num_136,float32,1103.0,0.01,10336.0,"-1.4828, -1.2154, -0.2188, -0.0615, -1.1047, -0.606, -0.909, -0.8302, -0.763, -0.5092"
58,num_137,float32,1103.0,0.01,1924149.0,"-1.3525, -0.4034, -0.8391, -0.797, -0.6943, -0.748, -0.8837, -0.6395, 0.1804, -0.5279"
59,num_138,float32,1103.0,0.01,100.0,"-0.8571, -0.054, 0.3575, 0.7233, 1.0422, 1.316, 1.5501, 1.7541, 1.9345, 2.0948"
60,num_143,float32,1103.0,0.01,898318.0,"-0.7659, 0.0402, 0.294, -0.0854, 0.5702, -0.1176, -0.0489, 0.8285, 0.1804, -0.0138"
61,num_144,float32,1103.0,0.01,97.0,"-0.8249, 0.0075, 0.4349, 0.8057, 1.1258, 1.3978, 1.63, 1.8312, 2.0089, 2.1644"
62,num_149,float32,1103.0,0.01,760448.0,"-0.726, 0.1132, 0.3925, -0.0213, -0.0565, 0.0188, 0.6895, 0.9674, 0.2679, 0.059"
63,num_0,float32,0.0,0.00,3.0,"-0.6816, 0.5731, 1.8587"
64,num_1,float32,0.0,0.00,24.0,"0.4837, 0.2445, 0.7547, 0.0314, -0.1676, -0.3669, -0.5731, 1.0444, -0.7988, -1.0466"
65,num_2,float32,0.0,0.00,4084.0,"-0.6226, -0.909, -1.2613, -0.0381, -1.6691, -2.0191, -0.4006, -0.1983, -2.3652, 0.122"
66,num_3,float32,0.0,0.00,383965.0,"2.1697, 1.1024, -2.0616, 0.3424, 0.6861, 0.4461, -0.2057, 0.1782, -0.3462, -0.4994"
67,num_4,float32,0.0,0.00,32637.0,"-0.6041, -0.4752, 0.0403, 0.8373, 0.8444, -0.4895, -0.0138, 0.7282, -0.7185, 0.6302"
68,num_5,float32,0.0,0.00,32642.0,"-0.4394, -0.3629, -0.4226, 0.6303, 0.1347, 0.615, -0.4335, 0.1752, 0.4362, -0.5467"
69,num_6,float32,0.0,0.00,32638.0,"-0.4988, -0.4808, -0.044, 0.585, 0.5702, -0.5584, 0.0691, 0.3952, -0.6211, -1.0488"
70,num_7,float32,0.0,0.00,32149.0,"-0.7782, -0.6576, -0.6864, -0.2732, 0.5613, 0.5467, -0.7579, -0.1906, -0.1046, 0.3309"
71,num_8,float32,0.0,0.00,33515.0,"-1.0509, -1.3653, -0.9109, 0.2059, 0.1906, -1.0444, -1.1117, -0.3388, -0.5939, 0.0038"
72,num_9,float32,0.0,0.00,1232845.0,"0.252, 0.1265, 1.3839, 0.3244, 1.2951, 0.2673, -0.2023, 1.3343, 0.1845, 1.1309"
73,num_10,float32,0.0,0.00,1221487.0,"-0.3098, -0.2872, -0.449, 0.3837, 0.2959, 0.4954, -0.2737, -0.3119, -0.2537, -0.699"
74,num_11,float32,0.0,0.00,1248969.0,"-0.1538, -1.0104, -0.194, -0.4715, -0.174, -0.3134, 2.3259, -0.9215, -0.7102, -1.0996"
75,num_12,float32,0.0,0.00,1382131.0,"-0.2785, 2.326, -0.3456, -1.592, -1.1025, -0.4187, -0.3051, -0.4274, -1.1921, -0.2205"
76,num_13,float32,0.0,0.00,1461836.0,"-0.4835, -1.5711, -0.5698, -1.0808, -0.6199, -0.5119, -0.5037, -0.0672, -0.5405, -0.4096"
77,num_14,float32,0.0,0.00,2935661.0,"-1.9503, -0.0417, -1.552, 0.0741, -0.6567, 0.0154, -1.5119, -0.1982, 0.09, -1.7938"
78,num_15,float32,0.0,0.00,6854360.0,"-5.1993, -0.3066, -0.6383, -0.6066, -0.5575, -2.0759, -3.862, -1.4754, -0.0611, -1.2858"
79,num_16,float32,0.0,0.00,9211599.0,"-5.1993, 0.0163, -0.7018, 0.1762, -0.6467, -0.7189, -0.651, -0.3661, -1.2234, -0.616"
80,num_17,float32,0.0,0.00,9190640.0,"-0.8601, 0.5242, -0.1637, 0.7179, -0.1772, -0.1197, 0.1283, -0.1232, -0.5106, -0.2615"
81,num_18,float32,0.0,0.00,9189375.0,"-0.2731, 1.2723, 0.3414, 1.7755, 0.3271, 0.388, 0.3841, 0.0074, 0.6711, 0.2408"
82,num_19,float32,0.0,0.00,9206659.0,"0.2434, -1.2689, 0.9804, -0.9721, 1.0547, 0.9595, 1.6704, 1.0485, 0.5421, 1.0646"
83,num_20,float32,0.0,0.00,9216359.0,"0.8424, -0.5066, -1.7453, -0.3331, -1.8103, -1.5728, -1.0072, -1.585, 1.3433, 1.029"
84,num_21,float32,0.0,0.00,8005623.0,"0.6182, 0.1338, 0.7581, -0.6832, -0.0721, -0.2699, 0.3606, 0.9038, 0.2435, -0.8004"
85,num_22,float32,0.0,0.00,7003483.0,"0.7842, 0.2664, 0.9452, -0.527, 0.0589, 0.5035, -0.1361, 1.122, 0.3807, -0.6326"
86,num_23,float32,0.0,0.00,7943075.0,"-1.0633, 1.8194, -0.8851, 0.4114, 1.1938, 0.863, -1.6154, -0.7408, -2.3759, 0.3165"
87,num_24,float32,0.0,0.00,8852683.0,"0.032, -0.4286, 0.1447, -1.906, -0.9362, -0.6687, -0.1974, 0.25, -0.3118, 2.4512"
88,num_25,float32,0.0,0.00,8773314.0,"0.5676, 0.0896, 0.7035, -0.7382, -0.3148, 0.3154, -0.1163, 0.8428, 0.2001, -0.8599"
89,num_26,float32,0.0,0.00,8318055.0,"-0.2557, -0.6674, 0.2581, -0.7177, 0.8739, 0.7078, -0.6437, 0.0468, 1.2907, 0.891"
90,num_27,float32,0.0,0.00,8417967.0,"0.2663, -0.1056, 1.8282, -2.1823, 0.8687, -0.1443, 0.5963, -0.0863, 0.3697, 0.2261"
91,num_28,float32,0.0,0.00,8011497.0,"0.7006, 0.2835, 1.7727, -0.9585, 0.2426, -1.1744, 0.304, 0.2045, 1.1676, 0.1295"
92,num_29,float32,0.0,0.00,7998123.0,"1.4887, 0.7888, -1.1068, -0.5452, -0.4084, 0.7366, 0.8156, -1.6346, 0.6895, -0.1667"
93,num_30,float32,0.0,0.00,8559968.0,"-0.7533, -1.4112, -1.5258, -0.1801, 0.3464, 0.2195, 0.6054, -1.3612, -0.3971, -0.6285"
94,num_31,float32,0.0,0.00,169554.0,"-2.2085, -0.1473, -0.3335, -1.7763, -0.141, 0.2996, -1.4951, -0.1266, -1.4753, 0.0159"
95,num_32,float32,0.0,0.00,159590.0,"-2.2008, -0.947, 0.3203, -0.2085, 0.5831, -0.225, 0.7612, 0.9437, -0.4529, -0.1394"
96,num_33,float32,39.0,0.00,104707.0,"-1.1047, -2.1977, -0.8395, -0.6109, -0.7039, -0.5355, -0.4778, -0.3289, -0.4336, -0.9964"
97,num_34,float32,0.0,0.00,267266.0,"-2.2109, 0.617, 0.2627, -0.059, 0.4584, 0.0395, -0.6895, -0.4726, -0.1646, -0.8106"
98,num_35,float32,0.0,0.00,207683.0,"-2.207, -1.7766, -1.6072, -1.9083, -1.5159, -1.0315, -1.0062, -0.9816, 0.74, 0.3255"
99,num_36,float32,0.0,0.00,232346.0,"-2.2106, 1.2925, 0.7648, 0.9408, -0.1126, 0.2643, -0.1502, -0.8259, -0.6951, -1.0"
100,num_37,float32,0.0,0.00,201.0,"1.1998, -2.1567, -1.3427, -1.2833, -1.4813, -1.4086, -1.2277, -1.0812, -1.561, -1.1274"
101,num_38,float32,0.0,0.00,67943.0,"-2.2079, -0.3177, -0.3522, -0.5293, -0.4893, -0.9378, -0.9109, -1.1258, -1.7861, 0.2342"
102,num_39,float32,0.0,0.00,42172.0,"-2.2098, -1.0887, -0.2999, -1.1187, 0.417, -0.2523, -0.0414, -0.6406, -0.9185, -0.3871"
103,num_40,float32,193.0,0.00,32756.0,"-1.023, -0.7392, -2.1909, -0.4668, -0.587, -0.3725, -0.3011, -0.2504, -0.2066, -0.1378"
104,num_41,float32,0.0,0.00,80233.0,"-2.2118, 0.0697, -0.1271, -0.7816, -0.5149, -0.3682, -0.6029, -0.16, -0.2992, -0.5293"
105,num_42,float32,0.0,0.00,73457.0,"-2.2051, -1.7646, -1.5756, -1.4605, -1.8978, -0.9755, -1.0101, -1.6793, -1.5297, -0.9456"
106,num_43,float32,0.0,0.00,77783.0,"-2.2124, -0.1322, -0.1245, -0.4006, -0.9815, -0.2291, 0.0153, -0.5008, -0.6364, -0.4233"
107,num_44,float32,0.0,0.00,201.0,"0.6014, -2.204, -1.479, -1.4551, -1.4127, -1.5739, -1.6845, -1.3341, -1.2334, -1.316"
108,num_45,float32,0.0,0.00,212144.0,"-2.2085, -0.1346, -0.3229, -1.7578, -0.1284, -1.4645, -1.7401, -1.4921, -0.1239, 0.4067"
109,num_46,float32,0.0,0.00,220615.0,"-2.2117, 0.1931, 0.205, -0.3424, -0.0703, 0.2085, -0.063, 0.3362, -1.2518, -0.1534"
110,num_47,float32,37.0,0.00,122452.0,"-1.1761, -2.202, -0.9208, -0.7059, -0.7862, -0.642, -0.5902, -0.508, -0.548, -0.4446"
111,num_48,float32,0.0,0.00,447376.0,"-2.2106, -0.4254, -0.7016, 0.1119, 0.7473, 0.754, -0.9495, 0.2164, 0.1394, -0.9281"
112,num_49,float32,0.0,0.00,280259.0,"-2.2112, -1.7901, -1.6379, -1.9106, -1.5503, -1.025, -1.001, -0.9775, 0.7315, 0.3176"
113,num_50,float32,0.0,0.00,334734.0,"-2.21, -0.7159, -0.3508, 0.7139, 1.2173, 1.0859, -0.9919, -0.0992, -0.9464, -0.6001"
114,num_51,float32,0.0,0.00,201.0,"1.5844, -2.0787, -1.1981, -1.2971, -1.4124, -1.1086, -1.5452, -1.0315, -0.9614, -0.8977"
115,num_52,float32,0.0,0.00,225548.0,"-2.2101, -0.1504, -0.1456, -0.3347, -1.4627, -1.1208, -1.4533, -0.1549, -1.1335, -1.7387"
116,num_53,float32,0.0,0.00,287858.0,"-2.2125, 0.2384, -0.4209, 1.1794, -0.3141, -0.1543, -1.1122, -0.0573, -0.5019, -0.6041"
117,num_54,float32,76.0,0.00,108354.0,"-2.2046, -1.4124, -1.2435, -1.086, -1.1445, -1.0408, -1.0064, -0.8636, -0.9734, -0.9437"
118,num_55,float32,0.0,0.00,1349448.0,"-2.2088, 2.1106, -0.3556, -0.5056, 0.0838, 0.5245, -1.1595, 1.4907, -1.5012, -0.8974"
119,num_56,float32,0.0,0.00,365904.0,"-2.205, -1.8404, -1.7435, -1.9106, -1.6844, -1.1071, -1.0916, -1.0503, -1.0626, -0.4802"
120,num_57,float32,0.0,0.00,536357.0,"-2.2095, -1.4644, -0.2328, 1.8932, -1.4686, 0.4768, -0.3735, -0.3243, -1.4891, 1.1401"
121,num_58,float32,0.0,0.00,172.0,"-1.4896, -0.8902, -0.584, -0.3629, -0.1897, -0.0489, 0.0691, 0.1715, 0.2627, 0.3415"
122,num_59,float32,0.0,0.00,134659.0,"-2.2082, -0.122, -0.1144, -0.464, -0.368, -0.7436, 0.3283, -1.767, -0.3019, -0.3071"
123,num_60,float32,0.0,0.00,117783.0,"-2.2113, -0.0222, -1.0002, -0.4609, 0.0604, -0.2705, 0.2619, 0.2316, -1.5052, 0.5144"
124,num_61,float32,120.0,0.00,82315.0,"-1.0663, -2.195, -0.791, -0.55, -0.6491, -0.469, -0.4083, -0.3624, -0.8475, -0.2504"
125,num_62,float32,0.0,0.00,193435.0,"-2.2083, -0.5786, 0.5021, -1.1744, -0.7769, -0.8792, -1.1849, -1.3341, -0.2204, -0.2136"
126,num_63,float32,0.0,0.00,157827.0,"-2.2124, -1.773, -1.594, -1.9089, -1.493, -0.9979, -1.5067, -0.9378, -1.7164, -0.9649"
127,num_64,float32,0.0,0.00,173672.0,"-2.2075, -0.7055, 1.0707, -1.3402, -0.7044, -0.83, -0.9503, -1.4341, -0.1397, -0.1594"
128,num_65,float32,0.0,0.00,201.0,"0.9877, -2.1738, -1.4497, -1.2367, -1.5591, -1.5019, -1.2753, -1.619, -1.3564, -1.4012"
129,num_66,float32,0.0,0.00,241622.0,"-2.2101, -0.157, -0.1516, -0.3421, -1.4618, -1.4735, -1.736, -0.3464, -0.1473, -0.1614"
130,num_67,float32,0.0,0.00,279542.0,"-2.2113, 1.2259, -0.4277, -0.16, -0.3271, -0.3203, 0.2448, 0.0307, -0.8362, 0.1549"
131,num_68,float32,26.0,0.00,126488.0,"-2.2043, -1.3136, -1.0982, -0.9086, -0.9769, -0.8554, -0.8152, -0.7782, -0.6832, -0.7431"
132,num_69,float32,0.0,0.00,845124.0,"-2.2052, 2.0803, -1.1625, 1.4803, 0.0723, -0.3714, 0.5163, 0.4203, -1.498, -0.3133"
133,num_70,float32,0.0,0.00,356868.0,"-2.2067, -1.8108, -1.6845, -1.9106, -1.6104, -1.06, -1.0428, -1.0255, 0.6959, 0.271"
134,num_71,float32,0.0,0.00,470577.0,"-2.213, 1.8665, -0.3496, 1.1251, -1.1844, 0.4548, 0.0766, -1.5047, -0.1344, -0.2593"
135,num_72,float32,0.0,0.00,201.0,"-1.8377, -1.3539, -1.1211, -0.943, -0.8011, -0.6816, -0.5776, -0.4865, -0.4061, -0.3335"
136,num_73,float32,0.0,0.00,4407.0,"-2.2105, -1.0884, -1.498, -1.432, -0.2685, -1.4605, -1.1089, -0.2301, -1.1262, -1.4071"
137,num_74,float32,0.0,0.00,5152.0,"-2.2121, -0.3335, -1.1071, -0.9378, 0.3768, -0.2861, -1.1401, -1.2475, -0.0716, 0.1296"
138,num_75,float32,311.0,0.00,1608.0,"-0.9694, -0.6784, -0.5121, -0.3844, -0.2792, -2.1827, -0.2044, -0.152, -0.1094, -0.0414"
139,num_76,float32,0.0,0.00,39712.0,"-2.207, 0.1174, -0.0805, -0.7348, -0.4591, -0.5555, -0.3124, -1.2475, -0.5613, -0.2524"
140,num_77,float32,0.0,0.00,11116.0,"-2.2058, -1.7502, -1.5641, -1.4431, -0.9456, -0.9824, -0.9109, -1.8953, -0.8837, -1.3795"
141,num_78,float32,0.0,0.00,18625.0,"-2.2112, -0.1024, -0.0942, -0.9456, -0.1957, -0.3629, -0.6164, -0.3203, 0.044, -0.4696"
142,num_79,float32,0.0,0.00,192.0,"0.3602, -2.2076, -0.9594, -1.5961, -1.291, -1.2641, -1.6395, -1.281, -1.3833, -1.1473"
143,num_80,float32,0.0,0.00,39085.0,"-2.2128, -0.6863, -0.3309, -1.31, -0.4034, -1.0146, -0.615, -0.7547, -0.6518, -0.2966"
144,num_81,float32,0.0,0.00,89691.0,"-0.2575, -1.1972, -0.4349, -0.5351, -1.0251, -0.8092, -0.7348, 0.1931, -2.0089, -0.0565"
145,num_82,float32,0.0,0.00,81189.0,"0.5731, -1.0797, -1.6897, -0.6769, -1.3371, -0.0013, -0.5121, 0.3481, 0.1537, -2.5614"
146,num_83,float32,0.0,0.00,70671.0,"-0.8995, -0.0984, -0.2949, 0.1609, 0.2523, -1.1417, -1.2997, 0.0716, -0.5195, -0.7386"
147,num_84,float32,0.0,0.00,97902.0,"-0.0691, -1.3749, -0.7201, -0.5999, -1.1694, -0.4431, -0.8232, 0.2252, -0.3045, -2.5478"
148,num_85,float32,0.0,0.00,94717.0,"0.0854, -0.6518, -0.5423, -0.2887, -0.763, -0.4408, -0.9761, -1.2867, -1.4691, 0.0013"
149,num_86,float32,0.0,0.00,96308.0,"-0.0703, -1.6641, -0.9378, -0.669, -1.2725, -0.2407, -0.7953, 0.2188, -0.5776, -2.5559"
150,num_87,float32,0.0,0.00,201.0,"0.3669, -2.5201, -1.6081, -1.711, -1.8448, -2.0149, -1.7517, -1.9527, -1.8953, -1.7961"
151,num_88,float32,0.0,0.00,27212.0,"-0.9109, -0.3415, -0.0879, -0.525, -1.6347, 0.0766, -1.316, -0.1766, 0.1983, -1.9889"
152,num_89,float32,0.0,0.00,18308.0,"-1.0842, -0.4418, -0.0905, 0.2484, -1.711, -0.6895, -0.2059, 0.7381, -0.5984, 0.0502"
153,num_90,float32,0.0,0.00,14602.0,"-0.1676, -0.9917, 0.2575, -1.7128, -0.6052, -0.5307, 0.589, -1.3931, -0.4752, -2.5413"
154,num_91,float32,0.0,0.00,28980.0,"-1.023, -0.5192, -0.2047, 0.0816, -1.58, -0.0339, -0.3229, -0.3871, 0.1791, -1.8246"
155,num_92,float32,0.0,0.00,28491.0,"-0.5999, -0.2239, -1.316, -0.0741, -1.8659, 0.0176, -0.9788, 0.2662, -1.5951, -2.5594"
156,num_93,float32,0.0,0.00,28777.0,"-1.2613, -0.4752, -0.2601, 0.5035, -0.8074, 0.0502, 0.2072, -0.6196, -0.0993, -0.6832"
157,num_94,float32,0.0,0.00,201.0,"0.1995, -2.5501, -1.9264, -1.7339, -1.7691, -1.9769, -1.6691, -1.9427, -2.0137, -1.9106"
158,num_95,float32,0.0,0.00,143739.0,"-0.7513, -0.3229, -0.5511, -0.2226, -0.383, -0.8535, -1.0146, -0.0867, -0.932, -1.114"
159,num_96,float32,0.0,0.00,138468.0,"-0.3736, 0.4047, -0.5731, 1.0531, -0.7201, -0.0905, 0.3005, 0.1855, -0.9674, 0.1308"
160,num_97,float32,0.0,0.00,111387.0,"-0.5351, -1.0041, -0.3349, -1.3199, -0.6848, -0.1182, -0.0489, 0.0368, -0.7831, -1.931"
161,num_98,float32,0.0,0.00,167112.0,"-0.2458, -0.5351, -0.3032, -0.4034, -0.9917, -0.9128, -0.6753, -0.1359, -0.7597, -1.439"
162,num_99,float32,0.0,0.00,154898.0,"-0.3934, -0.909, -0.1991, -0.7414, -0.3262, -0.6695, -0.7962, -0.0496, -1.0415, -1.6979"
163,num_100,float32,0.0,0.00,160542.0,"-0.1384, -0.471, -0.5235, -0.7023, -1.0444, -0.8232, -0.3602, -0.2433, -0.4034, -1.6897"
164,num_101,float32,0.0,0.00,201.0,"0.4418, -2.4466, -1.8926, -1.8043, -1.7287, -1.9981, -1.6641, -1.6047, -1.5533, -1.5057"

In [6]:
# Numeric Feature Statistics
numeric_stats

                          count      mean       std       min       max
num_0                 1279947.0  0.032297  0.767462 -0.681594  1.858747
num_1                 1279947.0  0.002439  0.990955 -3.102334  3.035368
num_2                 1279947.0 -0.002621  1.000037 -5.199337  5.199337
num_3                 1279947.0 -0.099354  0.998842 -5.199337  2.169694
num_4                 1279947.0 -0.000326  0.997010 -5.059109  4.992494
num_5                 1279947.0  0.000491  0.998920 -5.018341  5.199337
num_6                 1279947.0 -0.002663  0.999711 -5.199337  4.992494
num_7                 1279947.0 -0.000793  0.999690 -5.199337  4.957175
num_8                 1279947.0 -0.002872  0.998681 -5.199337  5.199337
num_9                 1279947.0 -0.000249  0.994146 -5.199337  5.199337
num_10                1279947.0 -0.002447  0.996210 -4.071859  5.199337
num_11                1279947.0 -0.000845  0.998747 -5.199337  5.199337
num_12                1279947.0 -0.000668  0.995773 -3.250911  5.199337
num_13                1279947.0 -0.000841  0.999318 -3.883994  5.199337
num_14                1279947.0 -0.002063  0.997687 -5.199337  5.199337
num_15                1279947.0 -0.000736  1.002550 -5.199337  5.199337
num_16                1279947.0 -0.000745  1.001199 -5.199337  5.199337
num_17                1279947.0 -0.000818  0.997772 -5.199337  5.199337
num_18                1279947.0  0.001328  0.999168 -5.199337  4.728219
num_19                1279947.0 -0.000905  0.999831 -5.199337  4.927129
num_20                1279947.0  0.000895  1.000807 -5.199337  5.199337
num_21                1279947.0  0.002774  0.998286 -5.199337  5.199337
num_22                1279947.0 -0.001133  1.000051 -5.016853  5.199337
num_23                1279947.0  0.007123  0.998837 -5.199337  5.199337
num_24                1279947.0 -0.003850  1.001651 -5.199337  4.707853
num_25                1279947.0  0.001598  0.997552 -5.199337  5.199337
num_26                1279947.0 -0.008397  1.001149 -5.199337  4.739188
num_27                1279947.0  0.003847  1.018701 -5.199337  5.199337
num_28                1279947.0 -0.035469  0.987869 -4.574813  5.199337
num_29                1279947.0  0.005949  0.991146 -5.199337  4.540848
num_30                1279947.0  0.005413  1.006249 -4.641226  5.199337
num_31                1279947.0 -0.015880  1.002143 -2.208501  5.199337
num_32                1279947.0 -0.016369  1.002166 -2.200761  5.199337
num_33                1279942.0 -0.015115  1.002957 -5.199337  3.912268
num_34                1279947.0 -0.017115  1.001847 -5.199337  5.199337
num_35                1279947.0 -0.017595  1.002561 -2.206982  5.199337
num_36                1279947.0 -0.016420  1.001847 -2.210644  5.199337
num_37                1279947.0 -0.036372  0.937307 -2.156653  1.199766
num_38                1279947.0 -0.018740  1.002530 -2.207876  5.199337
num_39                1279947.0 -0.014406  1.000332 -2.209828  5.199337
num_40                1279927.0 -0.017264  1.003238 -5.199337  5.199337
num_41                1279947.0 -0.018466  1.002269 -2.211842  5.199337
num_42                1279947.0 -0.017635  1.001780 -2.205113  5.199337
num_43                1279947.0 -0.018072  1.001382 -2.212413  5.199337
num_44                1279947.0 -0.066109  0.834595 -2.204020  0.601439
num_45                1279947.0 -0.015693  1.001492 -2.208467  5.199337
num_46                1279947.0 -0.014074  1.002645 -2.211699  5.199337
num_47                1279940.0 -0.013886  1.001825 -5.199337  5.199337
num_48                1279947.0 -0.016226  1.002276 -5.199337  5.199337
num_49                1279947.0 -0.016545  1.003439 -2.211230  5.199337
num_50                1279947.0 -0.015114  1.000731 -2.210030  5.199337
num_51                1279947.0 -0.019521  0.969181 -2.078677  1.584354
num_52                1279947.0 -0.016068  1.002474 -2.210065  5.199337
num_53                1279947.0 -0.014481  1.002638 -2.212500  5.199337
num_54                1279937.0 -0.017836  1.002015 -5.199337  5.199337
num_55                1279947.0 -0.015767  1.002512 -2.208765  5.199337
num_56                1279947.0 -0.016457  1.002301 -2.204990  5.199337
num_57                1279947.0 -0.017160  1.001211 -2.209472  5.199337
num_58                1279947.0  0.002745  0.964740 -1.489621  5.199337
num_59                1279947.0 -0.015740  1.001257 -2.208218  5.199337
num_60                1279947.0 -0.015357  1.001149 -2.211330  5.199337
num_61                1279933.0 -0.015175  1.002872 -5.199337  5.199337
num_62                1279947.0 -0.017235  1.000457 -5.199337  3.585057
num_63                1279947.0 -0.015309  1.003652 -2.212440  5.199337
num_64                1279947.0 -0.015055  1.000928 -2.207500  5.199337
num_65                1279947.0 -0.047527  0.912063 -2.173822  0.987651
num_66                1279947.0 -0.017773  1.003198 -2.210134  5.199337
num_67                1279947.0 -0.017164  1.002554 -2.211267  4.728219
num_68                1279944.0 -0.014149  1.003961 -5.199337  5.199337
num_69                1279947.0 -0.015572  1.001441 -5.199337  5.199337
num_70                1279947.0 -0.016518  1.001756 -2.206745  5.199337
num_71                1279947.0 -0.017676  1.001932 -2.213031  4.042302
num_72                1279947.0 -0.007927  0.984406 -1.837738  2.408551
num_73                1279947.0 -0.015607  1.002789 -2.210472  5.199337
num_74                1279947.0 -0.013220  1.001529 -2.212087  5.199337
num_75                1279915.0 -0.014819  1.003222 -5.199337  5.199337
num_76                1279947.0 -0.012885  1.003088 -2.207037  5.199337
num_77                1279947.0 -0.014645  1.003024 -2.205777  5.199337
num_78                1279947.0 -0.017349  1.001688 -2.211176  5.199337
num_79                1279947.0 -0.083982  0.753290 -2.207600  0.360172
num_80                1279947.0 -0.007613  0.997907 -2.212818  5.199337
num_81                1279947.0 -0.008422  1.000444 -2.561309  4.179568
num_82                1279947.0 -0.002936  0.999233 -2.561415  5.199337
num_83                1279947.0 -0.008917  1.000637 -5.199337  5.199337
num_84                1279947.0 -0.008005  0.998881 -2.547844  5.199337
num_85                1279947.0 -0.009083  1.001950 -2.552509  5.199337
num_86                1279947.0 -0.007817  0.997700 -2.555852  5.199337
num_87                1279947.0 -0.072396  0.751021 -2.520133  0.366873
num_88                1279947.0 -0.008305  0.997266 -2.552461  5.199337
num_89                1279947.0 -0.005149  0.996634 -2.552906  5.199337
num_90                1279947.0 -0.008087  0.996199 -5.199337  5.199337
num_91                1279947.0 -0.007487  0.995725 -2.554169  5.199337
num_92                1279947.0 -0.009033  0.999534 -2.559441  5.199337
num_93                1279947.0 -0.006047  0.988847 -2.556173  3.750067
num_94                1279947.0 -0.070321  0.650535 -2.550115  0.199538
num_95                1279947.0 -0.009842  1.003120 -2.551561  3.837888
num_96                1279947.0 -0.006399  1.000185 -2.557282  5.199337
num_97                1279947.0 -0.008437  0.997972 -5.199337  4.209179
num_98                1279947.0 -0.009879  1.001254 -2.555980  4.243014
num_99                1279947.0 -0.010615  1.001639 -2.557450  4.010160
num_100               1279947.0 -0.009644  1.000487 -2.549528  3.787792
num_101               1279947.0 -0.069978  0.781632 -2.446636  0.441766
num_102               1279947.0 -0.012791  1.003885 -2.556380  5.199337
num_103               1279947.0 -0.007814  1.001606 -2.548353  5.199337
num_104               1279947.0 -0.010482  1.001233 -5.199337  5.199337
num_105               1279947.0 -0.011721  1.004148 -2.555850  4.717792
num_106               1279947.0 -0.011176  1.003307 -2.556379  5.199337
num_107               1279947.0 -0.013266  1.003855 -2.552890  3.881460
num_108               1279947.0 -0.055381  0.831285 -1.983695  0.647177
num_109               1279947.0 -0.009279  1.001876 -2.556064  3.781437
num_110               1279947.0 -0.005505  0.999360 -2.548491  5.199337
num_111               1279947.0 -0.007531  0.998733 -5.199337  5.199337
num_112               1279947.0 -0.008806  1.000559 -2.550622  5.199337
num_113               1279947.0 -0.009074  1.000716 -2.551785  5.199337
num_114               1279947.0 -0.009111  0.999996 -2.555262  3.836711
num_115               1279947.0 -0.074834  0.727024 -2.525221  0.315012
num_116               1279947.0 -0.011401  1.004276 -2.563072  5.199337
num_117               1279947.0 -0.006410  1.000544 -2.550154  5.199337
num_118               1279947.0 -0.009362  0.999555 -5.199337  5.199337
num_119               1279947.0 -0.011230  1.004856 -2.559050  5.199337
num_120               1279947.0 -0.012349  1.003652 -2.557328  5.199337
num_121               1279947.0 -0.011862  1.002452 -2.551564  3.862623
num_122               1279947.0 -0.064464  0.806441 -2.255026  0.530745
num_123               1279947.0 -0.001711  0.989035 -2.548314  5.199337
num_124               1279947.0 -0.002848  0.991426 -2.560380  5.199337
num_125               1279947.0 -0.003625  0.989787 -5.199337  5.199337
num_126               1279947.0 -0.003961  0.988174 -2.547019  5.199337
num_127               1279947.0 -0.005118  0.994094 -2.549376  5.199337
num_128               1279947.0  0.003761  0.974574 -2.554472  5.199337
num_129               1279947.0 -0.061304  0.577795 -2.551324  0.127053
num_130               1279947.0  0.005296  0.984937 -2.555601  5.199337
num_131               1279839.0  0.031530  0.943417 -1.395618  5.199337
num_132               1279839.0  0.029973  0.956452 -1.541796  5.199337
num_133               1279839.0  0.017189  0.993054 -5.199337  5.199337
num_134               1279839.0  0.011417  0.994446 -5.199337  5.199337
num_135               1279839.0  0.005977  0.993733 -5.199337  3.633332
num_136               1279839.0 -0.002241  0.998109 -3.030351  5.199337
num_137               1279839.0  0.031469  0.950438 -1.352526  5.199337
num_138               1279839.0  0.055091  0.885497 -0.857097  5.199337
num_139                931512.0  0.021410  1.001447 -5.199337  3.829301
num_140                931512.0  0.013623  1.003613 -5.199337  5.199337
num_141                931512.0  0.006325  1.003316 -5.199337  5.199337
num_142                931512.0  0.002365  0.994052 -2.085356  3.669957
num_143               1279839.0  0.061035  0.874403 -0.765908  5.199337
num_144               1279839.0  0.057118  0.880613 -0.824933  5.199337
num_145                923705.0  0.020780  1.002592 -5.199337  3.686397
num_146                923705.0  0.015121  1.005531 -5.199337  5.199337
num_147                923705.0  0.009257  1.003137 -5.199337  3.654216
num_148                923705.0  0.001387  0.992990 -2.074445  3.655524
num_149               1279839.0  0.065471  0.866452 -0.725954  5.199337
num_150                949215.0 -0.011176  1.011001 -2.394743  3.659122
num_151                949215.0 -0.005240  1.008623 -5.199337  5.199337
num_152                949215.0  0.032642  1.021298 -5.199337  3.479756
num_153                949215.0  0.018880  1.017704 -4.184958  3.467362
num_154                949215.0  0.006579  1.007567 -5.199337  5.199337
num_155                676495.0  0.065726  0.918604 -0.977487  3.871332
num_156                676495.0  0.024775  1.013540 -4.386922  4.105112
num_157                676495.0 -0.001128  0.998303 -5.199337  5.199337
num_158                676495.0 -0.014785  1.004387 -5.199337  4.877777
num_159                676495.0  0.011778  1.001766 -4.195245  3.956876
num_160                945093.0 -0.016968  1.014753 -2.296950  5.199337
num_161                945093.0 -0.015480  1.016100 -5.199337  5.199337
num_162                945093.0  0.015745  1.019822 -5.199337  5.166578
num_163                945093.0  0.015696  1.019463 -5.199337  3.466996
num_164                945093.0 -0.004235  1.008507 -5.199337  5.166578
num_165                 12586.0 -0.022684  1.035297 -2.471374  5.199337
num_166                 12586.0 -0.033079  1.055278 -5.199337  5.199337
num_167                 12586.0 -0.047270  1.015312 -5.199337  5.199337
num_168                 12586.0 -0.024377  0.995902 -5.199337  4.059237
num_169                 12586.0 -0.007961  1.051471 -5.199337  5.199337
num_170                949215.0 -0.052369  0.499923 -2.389961  0.076604
num_171                949215.0  0.026256  1.028070 -5.199337  5.199337
num_172                949215.0  0.024279  1.023138 -5.199337  3.479819
num_173                949215.0  0.018519  1.017105 -4.096986  3.466935
num_174                949215.0  0.024015  1.024900 -5.199337  5.199337
num_175                949215.0 -0.032118  0.397349 -2.389961  0.040157
num_176                949215.0  0.021298  1.024994 -5.199337  3.141936
num_177                949215.0  0.022430  1.022072 -5.199337  3.284898
num_178                949215.0  0.016831  1.018948 -4.298732  5.199337
num_179                949215.0  0.023362  1.023368 -5.199337  3.466388
num_180                949215.0  0.018928  1.017408 -4.123016  3.467362
num_181                949215.0  0.020498  1.018430 -5.199337  5.199337
num_182                949215.0  0.018717  1.019434 -4.200823  5.199337
num_183                949215.0  0.019410  1.016747 -4.530458  3.466935
num_184               1279947.0  0.009213  0.999311 -5.199337  3.713609
num_185               1279947.0 -0.006861  0.988678 -5.199337  3.545599
cooking_time_minutes  1279947.0  2.547534  0.661283  0.032790  4.786102

In [7]:
# Categorical Feature Statistics
cat_stats

                              value    count    pct
column    rank
bin_0     1                     0.0   679105  53.06
          2                     1.0   600842  46.94
bin_1     1                     1.0   864228  67.52
          2                     0.0   415719  32.48
bin_2     1                     1.0   949215  74.16
          2                     0.0   330732  25.84
cat_0     1                     251     1801   0.14
          2                      94     1605   0.13
          3                    1327     1559   0.12
          4                     889     1489   0.12
          5                    1544     1328   0.10
cat_1     1                       1   279969  21.87
          2                       7    91504   7.15
          3                       2    75767   5.92
          4                      34    58559   4.58
          5                       6    32010   2.50
cat_2     1                     120     3720   0.29
          2                     172     2934   0.23
          3                     381     2842   0.22
          4                     361     2496   0.20
          5                     196     2476   0.19
cat_3     1                     827     1297   0.10
          2                     121     1020   0.08
          3                     916      938   0.07
          4                    1085      920   0.07
          5                      86      911   0.07
cat_4     1                       1   840335  65.65
          2                       2   438824  34.28
          3                       3      788   0.06
cat_5     1                       2  1187811  92.80
          2                      27     9196   0.72
          3                     568      157   0.01
          4                     293      156   0.01
          5                     218      151   0.01
timestamp 1     2023-12-14 16:27:55        8   0.00
          2     2023-12-10 10:31:13        8   0.00
          3     2023-12-01 17:19:17        8   0.00
          4     2023-12-09 16:34:06        7   0.00
          5     2023-11-19 09:41:28        7   0.00

In [8]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,-0.095,-0.761,0.437,0.081,log,4953934.4,6.102131e+16,exponential

## Task Curation

In [9]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import subsample_temporal

date_col = task_mold.time_on
target_col = task_mold.target_column_name

df = df.sort_values(by=date_col).reset_index(drop=True)

test_time_min = df[date_col].max().normalize() - pd.DateOffset(weeks=1)

# Define indices
test_idx = df.index[df[date_col] >= test_time_min].to_numpy().tolist()
train_idx = df.index[
    df[date_col] < test_time_min
].to_numpy().tolist()

df, train_idx, test_idx = subsample_temporal(
    df=df,
    train_idx=train_idx,
    test_idx=test_idx,
    stratify_on=task_mold.stratify_on,
)

print("Train size:", len(train_idx), "| Test size:", len(test_idx))
print("Train target mean:", df.loc[train_idx, target_col].mean())
print("Test target mean:", df.loc[test_idx, target_col].mean())

splits = {0: {0: (train_idx, test_idx)}}

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="We use the last week as test data and all prior data as train data.",
    splits=splits,
    time_horizon=7,
    time_horizon_unit="days",
)

Train size: 1000000 | Test size: 250000
Train target mean: 2.538523
Test target mean: 2.5951653

## Export

In [10]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to cooking_time/versions/019d308c-c2ae-71dc-9c65-e4b185c97eb4
019d308c-c2ae-71dc-9c65-e4b185c97eb4
98a872b67d07382a0090bc04965e20cd499cd37638cbf606b32d4f6f09c9bf02