### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="online_shoppers_purchasing_intention_dataset",
    dataset_year="2017",
    domain_str="business & marketing",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C5F88Q",
    download_description="""
We download the data from the UCI repository and uzip it to a predefined folder.

mkdir -p local-data-warehouse/online_shoppers_purchasing_intention_dataset/ && wget -P local-data-warehouse/online_shoppers_purchasing_intention_dataset/ http://archive.ics.uci.edu/static/public/468/online+shoppers+purchasing+intention+dataset.zip && unzip local-data-warehouse/online_shoppers_purchasing_intention_dataset/online+shoppers+purchasing+intention+dataset.zip -d local-data-warehouse/online_shoppers_purchasing_intention_dataset/ && rm local-data-warehouse/online_shoppers_purchasing_intention_dataset/online+shoppers+purchasing+intention+dataset.zip
""",
    # References
    academic_reference_bibtex="""@article{sakar2019real,
  title={Real-time prediction of online shoppers’ purchasing intention using multilayer perceptron and LSTM recurrent neural networks},
  author={Sakar, C Okan and Polat, S Olcay and Katircioglu, Mete and Kastro, Yomi},
  journal={Neural Computing and Applications},
  volume={31},
  number={10},
  pages={6893--6908},
  year={2019},
  publisher={Springer}
}
""",
    academic_reference_bibtex_key="sakar2019real",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
- Anomaly: the data contains time-based features that were preprocessed to create a time-invariant predictive task.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Revenue",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="Revenue",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(f"{dataset_mold.path}/online_shoppers_intention.csv")

cat_features = [
  "Month",
  "OperatingSystems",
  "Browser",
  "Region",
  "TrafficType",
  "VisitorType",
  "Weekend",
]

df[cat_features] = df[cat_features].astype("category")

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 12,330
Columns: 18
Use sampling: False (sample size: 12,330)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['ProductRelated_Duration', 'ExitRates', 'Administrative_Duration', 'PageValues', 'BounceRates', 'Informational_Duration', 'ProductRelated', 'Administrative', 'TrafficType', 'Informational']
Rows remaining as candidates after top-10 filter: 741 (of 12,330)

#### Duplicate Report
Total duplicate rows: 125 (1.01% of dataset)
Duplicate rows ignoring target: 125 (1.01% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,3,142.500000,0,0.00,48,1052.255952,0.004348,0.013043,0.000000,0.0,Nov,1,8,6,11,Returning_Visitor,False,False
1,6,437.391304,2,235.55,83,2503.881781,0.002198,0.004916,2.086218,0.0,Mar,2,2,3,2,Returning_Visitor,False,True
2,1,41.125000,0,0.00,126,4310.004668,0.000688,0.012823,3.451072,0.0,Nov,2,2,2,2,Returning_Visitor,False,False
3,2,141.000000,0,0.00,10,606.666667,0.008333,0.026389,36.672294,0.0,Aug,2,5,7,4,Returning_Visitor,False,False
4,18,608.140000,6,733.80,168,4948.398759,0.006632,0.013528,10.150644,0.0,Aug,2,2,3,1,Returning_Visitor,True,False

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Revenue,bool,0.0,0.0,2.0,"False, True"
1,Month,category,0.0,0.0,10.0,"May, Nov, Mar, Dec, Oct, Sep, Aug, Jul, June, Feb"
2,OperatingSystems,category,0.0,0.0,8.0,"2, 1, 3, 4, 8, 6, 7, 5"
3,Browser,category,0.0,0.0,13.0,"2, 1, 4, 5, 6, 10, 8, 3, 13, 7"
4,Region,category,0.0,0.0,9.0,"1, 3, 4, 2, 6, 7, 9, 8, 5"
5,TrafficType,category,0.0,0.0,20.0,"2, 1, 3, 4, 13, 10, 6, 8, 5, 11"
6,VisitorType,category,0.0,0.0,3.0,"Returning_Visitor, New_Visitor, Other"
7,Weekend,category,0.0,0.0,2.0,"False, True"
8,Administrative_Duration,float64,0.0,0.0,3335.0,"0.0, 4.0, 5.0, 7.0, 11.0, 6.0, 14.0, 9.0, 15.0, 10.0"
9,Informational_Duration,float64,0.0,0.0,1258.0,"0.0, 9.0, 10.0, 7.0, 6.0, 13.0, 12.0, 16.0, 8.0, 11.0"
10,ProductRelated_Duration,float64,0.0,0.0,9551.0,"0.0, 17.0, 11.0, 8.0, 15.0, 12.0, 22.0, 19.0, 13.0, 7.0"
11,BounceRates,float64,0.0,0.0,1872.0,"0.0, 0.2, 0.0667, 0.0286, 0.05, 0.0333, 0.025, 0.0167, 0.1, 0.04"
12,ExitRates,float64,0.0,0.0,4777.0,"0.2, 0.1, 0.05, 0.0333, 0.0667, 0.025, 0.04, 0.0167, 0.02, 0.0222"
13,PageValues,float64,0.0,0.0,2704.0,"0.0, 53.988, 42.2931, 26.5455, 9.0848, 34.04, 44.8935, 58.9242, 14.1274, 42.4225"
14,SpecialDay,float64,0.0,0.0,6.0,"0.0, 0.6, 0.8, 0.4, 0.2, 1.0"
15,Administrative,int64,0.0,0.0,27.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
16,Informational,int64,0.0,0.0,17.0,"0, 1, 2, 3, 4, 5, 6, 7, 9, 8"
17,ProductRelated,int64,0.0,0.0,311.0,"1, 2, 3, 4, 6, 7, 5, 8, 10, 9"

In [6]:
# Numeric Feature Statistics
numeric_stats

                           count         mean          std  min           max
Administrative           12330.0     2.315166     3.321784  0.0     27.000000
Administrative_Duration  12330.0    80.818611   176.779107  0.0   3398.750000
Informational            12330.0     0.503569     1.270156  0.0     24.000000
Informational_Duration   12330.0    34.472398   140.749294  0.0   2549.375000
ProductRelated           12330.0    31.731468    44.475503  0.0    705.000000
ProductRelated_Duration  12330.0  1194.746220  1913.669288  0.0  63973.522230
BounceRates              12330.0     0.022191     0.048488  0.0      0.200000
ExitRates                12330.0     0.043073     0.048597  0.0      0.200000
PageValues               12330.0     5.889258    18.568437  0.0    361.763742
SpecialDay               12330.0     0.061427     0.198917  0.0      1.000000
Revenue                  12330.0     0.154745     0.361676  0.0      1.000000

In [7]:
# Categorical Feature Statistics
cat_stats

                                   value  count    pct
column           rank
Browser          1                     2   7961  64.57
                 2                     1   2462  19.97
                 3                     4    736   5.97
                 4                     5    467   3.79
                 5                     6    174   1.41
Month            1                   May   3364  27.28
                 2                   Nov   2998  24.31
                 3                   Mar   1907  15.47
                 4                   Dec   1727  14.01
                 5                   Oct    549   4.45
OperatingSystems 1                     2   6601  53.54
                 2                     1   2585  20.97
                 3                     3   2555  20.72
                 4                     4    478   3.88
                 5                     8     79   0.64
Region           1                     1   4780  38.77
                 2                     3   2403  19.49
                 3                     4   1182   9.59
                 4                     2   1136   9.21
                 5                     6    805   6.53
TrafficType      1                     2   3913  31.74
                 2                     1   2451  19.88
                 3                     3   2052  16.64
                 4                     4   1069   8.67
                 5                    13    738   5.99
VisitorType      1     Returning_Visitor  10551  85.57
                 2           New_Visitor   1694  13.74
                 3                 Other     85   0.69
Weekend          1                 False   9462  76.74
                 2                  True   2868  23.26

In [8]:
# Target Distribution
target_df

         count    pct
Revenue
False    10422  84.53
True      1908  15.47

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...

Saving curated container to online_shoppers_purchasing_intention_dataset/019d7369-04fa-7d46-86a2-5b698a906fae
019d7369-04fa-7d46-86a2-5b698a906fae
0c40aac0ab9b97c6731ec047a14f96e553a309963b36ba4e5622d4863e1a3843