### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="amex_non_iid",
    dataset_year="2022",
    domain_str="finance",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/amex-default-prediction/",
    download_description="""
We start with the preprocessed version of the dataset in Parquet format provided by
the user 'raddar' on Kaggle. At the root of this project, I ran on linux with
the kaggle CLI installed and authenticated:

kaggle datasets download -d raddar/amex-data-integer-dtypes-parquet-format --unzip -p amex_dataset && rm amex_dataset/test.parquet
kaggle competitions download -c amex-default-prediction -f train_labels.csv -p amex_dataset && cd amex_dataset && unzip train_labels.csv.zip train_labels.csv && rm train_labels.csv.zip && cd ..
mkdir -p local-data-warehouse/amex_non_iid && mv amex_dataset/* local-data-warehouse/amex_non_iid/ && rm -rf amex_dataset
""",
    # References
    academic_reference_bibtex="""@misc{howard2022amex,
  author       = {Howard, Addison and AritraAmex and Xu, Di and Vashani, Hossein and inversion and Negin and Dane, Sohier},
  title        = {American Express -- Default Prediction},
  year         = {2022},
  howpublished = {Kaggle Competition},
  url          = {https://kaggle.com/competitions/amex-default-prediction},
  note         = {Accessed via Kaggle}
}
""",
    academic_reference_bibtex_key="howard2022amex",
    licence="Kaggle Competition License",
    data_tags=["Non-IID", "Temporal", "Grouped", "Anonymized"],
    curation_comments="""
We start with the raw data from Kaggle and do not apply any further preprocessing to simulate a pipeline that can handle raw non-IID grouped data.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="target",
    problem_type="binary_classification",
    objective_metric_name="amex_metric",
    stratify_on="target",
    group_on="customer_ID",
    time_on="S_2",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_parquet(dataset_mold.path / "train.parquet")
print("Loaded data shape:", df.shape)

df.S_2 = pd.to_datetime(df.S_2)
df = df.sort_values(["customer_ID", "S_2"])

cat_features = [
    "B_30",
    "B_38",
    "D_114",
    "D_116",
    "D_117",
    "D_120",
    "D_126",
    "D_63",
    "D_64",
    "D_66",
    "D_68",
]
df = df.set_index("customer_ID")
# Add labels
targets = pd.read_csv(dataset_mold.path / "train_labels.csv")
targets = targets.set_index("customer_ID")
df = df.merge(targets, left_index=True, right_index=True, how="left")
df.target = df.target.astype("int8")
del targets

df[cat_features] = df[cat_features].astype("category")

df = df.reset_index().reset_index(drop=True)

Loaded data shape: (5531451, 190)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False,
    duplicate_column_check=False,
)

#### Dataset Overview
Rows: 5,531,451
Columns: 191

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,D_42,D_43,D_44,B_4,D_45,B_5,R_2,D_46,D_47,D_48,D_49,B_6,B_7,B_8,D_50,D_51,B_9,R_3,D_52,P_3,B_10,D_53,S_5,B_11,S_6,D_54,R_4,S_7,B_12,S_8,D_55,D_56,B_13,R_5,D_58,S_9,B_14,D_59,D_60,D_61,B_15,S_11,D_62,D_63,D_64,D_65,B_16,B_17,B_18,B_19,D_66,B_20,D_68,S_12,R_6,S_13,B_21,D_69,B_22,D_70,D_71,D_72,S_15,B_23,D_73,P_4,D_74,D_75,D_76,B_24,R_7,D_77,B_25,B_26,D_78,D_79,R_8,R_9,S_16,D_80,R_10,R_11,B_27,D_81,D_82,S_17,R_12,B_28,R_13,D_83,R_14,R_15,D_84,R_16,B_29,B_30,S_18,D_86,D_87,R_17,R_18,D_88,B_31,S_19,R_19,B_32,S_20,R_20,R_21,B_33,D_89,R_22,R_23,D_91,D_92,D_93,D_94,R_24,R_25,D_96,S_22,S_23,S_24,S_25,S_26,D_102,D_103,D_104,D_105,D_106,D_107,B_36,B_37,R_26,R_27,B_38,D_108,D_109,D_110,D_111,B_39,D_112,B_40,S_27,D_113,D_114,D_115,D_116,D_117,D_118,D_119,D_120,D_121,D_122,D_123,D_124,D_125,D_126,D_127,D_128,D_129,B_41,B_42,D_130,D_131,D_132,D_133,R_28,D_134,D_135,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145,target
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a,2017-03-09,0.938469,0,0.008724,1.006838,0.009228,0.124035,0.0,0.004709,NaN,NaN,0,6,0.708906,0.170600,0,0.358587,0.525351,0.255736,-1,0.063902,0.059416,0.0,0.148698,4,0.008207,0,0.207334,0.736463,0.096219,NaN,0.023381,0.002768,0,1.0,0,0.161345,0.148266,2896,0.354596,0.152025,0.118075,0,0.158612,0.065728,0.018385,8,0.199617,0.308233,0.016361,15,0.091071,0,0,0,0,NaN,0.652984,0,-1,0,6,0.272008,0.008363,524,0.002644,0.009013,0,0,0.119403,0,4,0.050882,NaN,0.0,1,1,NaN,0.004327,0.0,NaN,0.007729,0.000272,0,0,0,-1,0.002271,0,0,0,0.002310,0,1,0.008033,1.0,0.084683,0,0,0.0,0,0,0,NaN,0,0,0,-1,0,0,NaN,1,0.002537,0,0,0,0,0,1,0,0,0,3,1,0,0,0,0,0,0.894090,0.135561,0.911191,0.974539,0.001243,0.766688,1,1.004587,0.893734,-1,2,0.009968,0.004572,-1,1.008949,2,-1,0,NaN,-1,NaN,1.0,0.210060,0.676922,0,1,0.238250,0,5,0.232120,0.236266,0,0.702280,3,0,16,0,2,1,1.007819,1,0,NaN,0.0,0.0,NaN,0.004345,0,NaN,-1,-1,-1,-1,0,0,0.0,NaN,0,0.000610,0,0
1,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a,2017-04-07,0.936665,0,0.004923,1.000653,0.006151,0.126750,0.0,0.002714,NaN,NaN,0,5,0.712795,0.113239,0,0.353630,0.521311,0.223329,-1,0.065261,0.057744,0.0,0.149723,4,0.008373,0,0.202778,0.720886,0.099804,NaN,0.030599,0.002749,0,1.0,0,0.140951,0.143530,2896,0.326757,0.156201,0.118737,0,0.148459,0.093935,0.013035,8,0.151387,0.265026,0.017688,15,0.086805,0,0,0,0,NaN,0.647093,0,-1,0,6,0.188970,0.004030,524,0.004193,0.007842,0,0,0.140611,0,4,0.040469,NaN,0.0,1,1,NaN,0.004203,0.0,NaN,0.001864,0.000979,0,0,0,-1,0.009810,0,0,0,0.001327,0,1,0.000760,1.0,0.081843,0,0,0.0,0,0,0,NaN,0,0,0,-1,0,0,NaN,1,0.008427,0,0,0,0,0,1,0,0,0,3,1,0,0,0,0,0,0.902135,0.136333,0.919876,0.975625,0.004561,0.786007,1,1.004118,0.906841,-1,2,0.003921,0.004654,-1,1.003205,2,-1,0,NaN,-1,NaN,1.0,0.184093,0.822281,0,1,0.247217,0,5,0.243532,0.241885,0,0.707017,3,0,16,0,2,1,1.004333,1,0,NaN,0.0,0.0,NaN,0.007495,0,NaN,-1,-1,-1,-1,0,0,0.0,NaN,0,0.005492,0,0
2,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a,2017-05-28,0.954180,3,0.021655,1.009672,0.006815,0.123977,0.0,0.009423,NaN,NaN,0,5,0.720884,0.060492,0,0.334650,0.524568,0.189424,-1,0.066982,0.056647,0.0,0.151955,4,0.009355,0,0.206629,0.738044,0.134073,NaN,0.048367,0.010077,0,1.0,0,0.112229,0.137014,3166,0.304124,0.153795,0.114534,0,0.139504,0.084757,0.056653,8,0.305883,0.212165,0.063955,15,0.094001,0,0,0,0,NaN,0.645819,0,-1,0,6,0.495308,0.006838,702,0.001337,0.006025,0,0,0.075868,0,4,0.047454,NaN,0.0,1,1,NaN,0.001782,0.0,NaN,0.005419,0.006149,0,0,0,-1,0.009362,0,0,0,0.007624,0,1,0.004056,1.0,0.081954,0,0,0.0,0,0,0,NaN,0,0,0,-1,0,0,NaN,1,0.007327,0,0,0,0,0,1,0,0,0,3,1,0,0,0,0,0,0.939654,0.134938,0.958699,0.974067,0.011736,0.806840,1,1.009285,0.928719,-1,2,0.001264,0.019176,-1,1.000754,2,-1,0,NaN,-1,NaN,1.0,0.154837,0.853498,0,1,0.239867,0,5,0.240768,0.239710,0,0.704843,3,0,16,0,2,1,1.007831,1,0,NaN,0.0,0.0,NaN,0.009227,0,NaN,-1,-1,-1,-1,0,0,0.0,NaN,0,0.006986,0,0
3,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a,2017-06-13,0.960384,0,0.013683,1.002700,0.001373,0.117169,0.0,0.005531,NaN,NaN,0,4,0.723997,0.166782,0,0.323271,0.530929,0.135586,-1,0.083720,0.049253,0.0,0.151219,4,0.006782,0,0.208214,0.741813,0.134437,NaN,0.030063,0.009667,0,1.0,0,0.102838,0.129017,2218,0.275055,0.155772,0.120740,0,0.138100,0.048382,0.012498,8,0.273553,0.204300,0.022732,15,0.094854,0,0,0,0,NaN,0.654358,0,-1,0,6,0.508670,0.008183,524,0.008716,0.005271,0,0,0.150209,0,5,0.031705,NaN,0.0,1,1,NaN,0.005595,0.0,NaN,0.000646,0.009193,0,0,0,-1,0.004876,0,0,0,0.000034,0,1,0.006969,1.0,0.060634,0,0,0.0,0,0,0,NaN,0,0,0,-1,0,0,NaN,1,0.007053,0,0,0,0,0,1,0,0,0,3,1,0,0,0,0,0,0.913205,0.140058,0.926341,0.975499,0.007571,0.808214,1,1.004514,0.935383,-1,2,0.002729,0.011720,-1,1.005338,2,-1,0,NaN,-1,NaN,1.0,0.153939,0.844667,0,1,0.240910,0,5,0.239400,0.240727,0,0.711546,3,0,16,0,2,1,1.003460,1,0,NaN,0.0,0.0,NaN,0.007206,0,NaN,-1,-1,-1,-1,0,0,0.0,NaN,0,0.006527,0,0
4,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a,2017-07-16,0.947248,0,0.015193,1.000727,0.007605,0.117325,0.0,0.009312,NaN,NaN,0,3,0.720619,0.143630,0,0.231009,0.529305,NaN,-1,0.075900,0.048918,0.0,0.154026,4,0.000519,0,0.205468,0.691986,0.121518,NaN,0.054221,0.009484,0,1.0,0,0.094311,0.129539,2896,0.231110,0.154914,0.095178,0,0.126443,0.039259,0.027897,8,0.233103,0.175655,0.031171,17,0.093915,0,0,0,0,NaN,0.650112,0,-1,0,6,0.216507,0.008605,524,0.006821,0.000152,0,0,0.096441,0,4,0.032733,NaN,0.0,1,1,NaN,0.004933,0.0,NaN,0.001833,0.005738,0,0,0,-1,0.007447,0,0,0,0.002109,0,1,0.001770,1.0,0.062492,0,0,0.0,0,0,0,NaN,0,0,0,-1,0,0,NaN,1,0.007728,0,0,0,0,0,1,0,0,0,3,1,0,0,0,0,0,0.921026,0.131620,0.933479,0.978027,0.018200,0.822281,1,1.005735,0.953363,-1,2,0.009998,0.017598,-1,1.003175,2,-1,0,NaN,-1,NaN,1.0,0.120717,0.811199,0,1,0.247939,0,5,0.244199,0.242325,0,0.705343,3,0,16,0,2,1,1.005053,1,0,NaN,0.0,0.0,NaN,0.006312,0,NaN,-1,-1,-1,-1,0,0,0.0,NaN,0,0.008126,0,0

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,D_63,category,0,0.00,6,"3, 0, 4, 1, 2, 5"
1,D_64,category,0,0.00,5,"0, 3, 2, -1, 1"
2,D_66,category,0,0.00,3,"-1, 1, 0"
3,D_68,category,0,0.00,8,"6, 5, 3, 4, 2, -1, 1, 0"
4,B_30,category,0,0.00,4,"0, 1, 2, -1"
5,B_38,category,0,0.00,8,"2, 3, 1, 5, 4, 7, 6, -1"
6,D_114,category,0,0.00,3,"1, 0, -1"
7,D_116,category,0,0.00,3,"0, -1, 1"
8,D_117,category,0,0.00,8,"0, 4, 5, 3, 6, 7, -1, 2"
9,D_120,category,0,0.00,3,"0, 1, -1"
10,D_126,category,0,0.00,4,"2, 1, 0, -1"
11,S_2,datetime64[ns],0,0.00,396,"2018-02-17 00:00:00, 2018-01-20 00:00:00, 2018-02-03 00:00:00, 2018-03-17 00:00:00, 2018-02-24 00:00:00, 2017-11-18 00:00:00, 2018-03-03 00:00:00, 2018-01-27 00:00:00, 2018-02-10 00:00:00, 2018-03-10 00:00:00"
12,D_88,float32,5525447,99.89,6004,"0.1672, 0.117, 0.0642, 0.0418, 0.0454, 0.0224, 0.0507, 0.0282, 0.164, 0.0814"
13,D_110,float32,5500117,99.43,30406,"1.0093, 1.0079, 1.0021, 1.0074, 1.0091, 1.0014, 1.0045, 1.0016, 1.0031, 1.0033"
14,B_39,float32,5497819,99.39,33557,"1.009, 1.0024, 1.0079, 1.0083, 1.0033, 1.0058, 1.0023, 1.0041, 1.0021, 1.002"
15,D_73,float32,5475595,98.99,55802,"0.0626, 0.1258, 0.1645, 0.1034, 0.0328, 0.0689, 0.1364, 0.1662, 0.0519, 0.1295"
16,B_42,float32,5459973,98.71,71434,"0.0117, 0.0081, 0.005, 0.1234, 0.0096, 0.008, 0.0049, 0.0077, 0.0083, 0.0211"
17,D_134,float32,5336752,96.48,192523,"1.0038, 1.0089, 1.0001, 1.0096, 1.0035, 1.0039, 1.0072, 1.0011, 1.0029, 1.0063"
18,B_29,float32,5150035,93.10,378319,"0.0052, 0.009, 0.0098, 0.0083, 0.0081, 0.0096, 0.0084, 0.008, 0.0081, 0.0084"
19,D_132,float32,4988874,90.19,538748,"0.2962, 0.1197, 0.1317, 0.0701, 0.1472, 0.2155, 0.2259, 0.3127, 0.2611, 0.1527"
20,D_76,float32,4908954,88.75,619107,"0.1922, 0.1925, 0.0618, 0.0614, 0.0324, 0.0247, 0.265, 0.1966, 0.2575, 0.2859"
21,D_42,float32,4740137,85.69,785339,"0.2413, 0.3121, 0.2712, 0.5833, 0.1717, 0.376, 0.1557, 0.1999, 0.1228, 0.1614"
22,D_142,float32,4587043,82.93,926344,"0.3809, 0.5327, 0.5512, 0.3017, 0.5618, 0.6386, 0.6482, 0.3067, 0.474, 0.5361"
23,D_53,float32,4084585,73.84,1428989,"0.0082, 0.0096, 0.0095, 0.0085, 0.0083, 0.0071, 0.0097, 0.0099, 0.0099, 0.0384"
24,D_50,float32,3142402,56.81,2306378,"0.143, 0.1178, 0.1708, 0.0492, 0.0801, 0.1743, 0.0788, 0.1325, 0.0645, 0.0971"
25,B_17,float32,3137598,56.72,1592707,"1.0077, 1.0044, 1.008, 1.0029, 1.0055, 1.0082, 1.0093, 1.004, 1.004, 1.0054"
26,D_105,float32,3021431,54.62,2414778,"0.365, 0.3185, 0.6422, 0.5484, 0.7259, 0.5947, 0.1641, 0.3776, 0.3289, 0.6037"
27,D_56,float32,2990943,54.07,2446769,"0.1359, 0.128, 0.0824, 0.1352, 0.1477, 0.132, 0.0652, 0.1558, 0.1411, 0.3609"
28,S_9,float32,2933643,53.04,2531874,"0.0095, 0.0408, 0.0189, 0.0107, 0.0168, 0.0163, 0.0159, 0.0158, 0.0084, 0.0089"
29,D_77,float32,2513912,45.45,2859646,"0.5016, 0.5083, 0.4017, 0.5003, 0.5089, 0.5087, 0.5095, 0.503, 0.3024, 0.6027"
30,D_43,float32,1658396,29.98,3708893,"0.1519, 0.1197, 0.069, 0.0637, 0.0429, 0.0449, 0.0637, 0.1427, 0.0643, 0.0405"
31,S_27,float32,1400935,25.33,3885609,"0.3726, 0.5251, 0.3849, 0.2722, 0.3717, 0.5648, 0.3614, 0.4202, 0.424, 0.4226"
32,D_46,float32,1211699,21.91,3388402,"0.4474, 0.4431, 0.4498, 0.4519, 0.4687, 0.4469, 0.4305, 0.4565, 0.4548, 0.451"
33,S_3,float32,1020544,18.45,4004312,"0.157, 0.1594, 0.1666, 0.1514, 0.173, 0.1383, 0.1709, 0.1722, 0.1661, 0.1753"
34,S_7,float32,1020544,18.45,4185390,"0.1062, 0.1087, 0.1085, 0.1062, 0.1097, 0.1046, 0.1049, 0.1034, 0.1061, 0.1065"
35,D_62,float32,758161,13.71,4519358,"0.5429, 0.5467, 0.0544, 0.5473, 0.545, 0.5453, 0.5423, 0.5405, 0.5221, 0.5465"
36,D_48,float32,718725,12.99,4534865,"0.9413, 0.9425, 0.9248, 0.8922, 0.9292, 0.9232, 0.5869, 0.9425, 0.9457, 0.6439"
37,D_61,float32,598052,10.81,4529133,"0.9077, 0.8984, 0.8989, 0.9159, 0.8802, 0.8988, 0.9024, 0.8892, 0.9075, 0.9076"
38,P_3,float32,301492,5.45,3816101,"0.6149, 0.6132, 0.6516, 0.5852, 0.6375, 0.6159, 0.5932, 0.6161, 0.6146, 0.6157"
39,D_69,float32,194473,3.52,4800508,"0.0092, 0.0082, 0.0085, 0.0089, 0.0078, 0.008, 0.0088, 0.0093, 0.0072, 0.0087"
40,D_55,float32,184803,3.34,5082515,"0.8517, 0.6922, 0.6306, 0.1104, 0.8692, 0.9158, 0.6884, 0.9095, 0.6194, 0.2667"
41,D_115,float32,176716,3.19,5063856,"0.5248, 0.2928, 0.2747, 0.5183, 0.2646, 0.3441, 0.8645, 0.5809, 0.3578, 0.5655"
42,D_118,float32,176716,3.19,5064015,"0.4453, 0.2806, 0.2698, 0.292, 0.5275, 0.1254, 0.6225, 0.4547, 0.3252, 0.5328"
43,D_119,float32,176716,3.19,5071097,"0.5714, 0.3059, 0.3447, 0.3206, 0.5692, 0.8598, 0.4101, 0.3104, 0.1287, 0.2996"
44,D_121,float32,176716,3.19,4308351,"0.7635, 0.7588, 0.7644, 0.7647, 0.7646, 0.7607, 0.7592, 0.7571, 0.7682, 0.759"
45,R_27,float32,128703,2.33,685818,"1.0013, 1.0008, 1.0098, 1.0045, 1.009, 1.0051, 1.005, 1.0085, 1.0097, 1.0005"
46,D_104,float32,101548,1.84,850543,"0.0, 0.9638, 0.9585, 0.9551, 0.957, 0.9586, 0.9617, 0.9577, 0.9564, 0.958"
47,D_128,float32,101548,1.84,100748,"0.0, 1.0045, 1.0072, 1.0078, 1.0032, 1.0086, 1.0083, 1.0001, 1.0053, 1.0056"
48,D_130,float32,101548,1.84,87229,"0.0, 1.0064, 1.0074, 1.004, 1.0005, 1.0071, 1.0052, 1.0026, 1.0046, 1.0071"
49,D_131,float32,101548,1.84,357435,"0.0, 0.9846, 0.9818, 0.9797, 0.978, 0.9835, 0.9794, 0.9808, 0.9792, 0.9797"
50,D_141,float32,101548,1.84,779126,"0.0, 0.8722, 0.8655, 0.8678, 0.8651, 0.8636, 0.8632, 0.8625, 0.865, 0.8642"
51,B_13,float32,49519,0.90,5249059,"0.06, 0.0098, 0.0482, 0.0182, 0.0068, 0.0301, 0.0315, 0.0673, 0.0827, 0.008"
52,P_2,float32,45985,0.83,4534509,"1.0016, 1.0094, 1.0027, 1.0027, 1.0001, 1.0024, 1.0002, 1.0011, 1.0037, 1.0035"
53,D_133,float32,42716,0.77,4966219,"0.0082, 0.0084, 0.0087, 0.0044, 0.0097, 0.0082, 0.0092, 0.0086, 0.0097, 0.01"
54,D_144,float32,40727,0.74,4985193,"0.0089, 0.0086, 0.0079, 0.0098, 0.0092, 0.0096, 0.0088, 0.0083, 0.0091, 0.0082"
55,D_102,float32,40655,0.73,5187619,"0.0086, 0.5463, 0.0085, 0.0088, 0.0082, 0.0082, 0.9264, 0.009, 0.0093, 0.544"
56,D_52,float32,29563,0.53,4949947,"1.0006, 1.0014, 1.0014, 1.0079, 1.0006, 1.0073, 1.0053, 1.006, 1.0027, 1.0035"
57,B_8,float32,22268,0.40,88734,"0.0, 1.0065, 1.0008, 1.0049, 1.009, 1.0046, 1.0046, 1.0025, 1.0075, 1.0081"
58,S_22,float32,19024,0.34,2330970,"0.9728, 0.9537, 0.9621, 0.3024, 0.3007, 0.9531, 0.9581, 0.963, 0.9583, 0.958"
59,S_24,float32,18593,0.34,2793098,"0.975, 0.961, 0.9712, 0.977, 0.9737, 0.9757, 0.9723, 0.9764, 0.9657, 0.9741"
60,S_25,float32,12847,0.23,755544,"0.9753, 0.9708, 0.9741, 0.97, 0.975, 0.9738, 0.9757, 0.9764, 0.9708, 0.9752"
61,B_15,float32,6923,0.13,5103912,"0.0081, 0.0089, 0.0098, 0.0097, 0.0099, 0.0096, 0.0092, 0.0086, 0.009, 0.008"
62,B_25,float32,6923,0.13,5297013,"0.0081, 0.009, 0.0083, 0.0086, 0.0088, 0.0086, 0.0083, 0.0097, 0.0093, 0.0087"
63,D_112,float32,2650,0.05,894388,"1.0, 0.009, 0.0086, 0.0059, 0.0098, 0.0086, 0.0099, 0.0095, 0.0067, 0.0099"
64,B_2,float32,2016,0.04,2346669,"1.0017, 1.002, 1.0083, 1.0087, 1.0079, 1.0099, 1.0057, 1.0095, 1.0021, 1.0053"
65,D_41,float32,2016,0.04,710177,"0.0, 0.3534, 0.1263, 0.6345, 0.443, 0.1878, 0.1707, 0.2028, 0.2649, 0.306"
66,B_3,float32,2016,0.04,5273509,"0.0055, 0.0096, 0.0096, 0.0086, 0.0093, 0.009, 0.0095, 0.0079, 0.0081, 0.0097"
67,D_45,float32,2017,0.04,5210401,"0.3872, 0.2685, 0.3349, 0.0319, 0.3118, 0.1902, 0.2573, 0.2887, 0.3393, 0.3049"
68,D_54,float32,2016,0.04,112645,"1.0, 0.0099, 0.0004, 0.0024, 0.0078, 0.0165, 0.0045, 0.0078, 0.0075, 0.0083"
69,B_26,float32,2016,0.04,4969518,"0.0093, 0.0079, 0.0094, 0.0086, 0.0079, 0.0087, 0.0079, 0.0084, 0.01, 0.0096"
70,B_27,float32,2016,0.04,4921945,"0.0081, 0.0099, 0.0089, 0.0042, 0.0058, 0.0095, 0.0093, 0.0096, 0.0084, 0.0088"
71,S_23,float32,445,0.01,1252495,"0.1354, 0.1356, 0.1385, 0.1366, 0.1366, 0.1386, 0.14, 0.1373, 0.1382, 0.1342"
72,S_26,float32,634,0.01,5157577,"0.0085, 0.0098, 0.01, 0.0087, 0.0078, 0.0083, 0.0078, 0.0089, 0.008, 0.0049"
73,B_1,float32,0,0.00,5319031,"0.0317, 0.0431, 0.0089, 0.0089, 0.01, 0.0351, 0.0086, 0.0082, 0.0087, 0.0084"
74,R_1,float32,0,0.00,4788285,"0.5049, 0.5059, 0.5029, 0.5005, 0.5068, 0.5054, 0.506, 0.5033, 0.5062, 0.5096"
75,B_5,float32,0,0.00,5268298,"0.01, 0.0093, 0.0094, 0.0091, 0.0087, 0.0091, 0.0169, 0.0099, 0.0093, 0.0094"
76,D_47,float32,0,0.00,4986282,"0.5861, 0.538, 0.5357, 0.5384, 0.5301, 0.5622, 0.5491, 0.5803, 0.5503, 0.3163"
77,B_6,float32,233,0.00,5152590,"0.2018, 0.179, 0.1729, 0.1938, 0.1804, 0.1755, 0.1763, 0.173, 0.2007, 0.1794"
78,B_7,float32,0,0.00,5259879,"0.0379, 0.0272, 0.0352, 0.1409, 0.025, 0.0318, 0.032, 0.1941, 0.0316, 0.0321"
79,B_9,float32,0,0.00,5181777,"0.6512, 0.6436, 0.6454, 0.6453, 0.6449, 0.6525, 0.6507, 0.6374, 0.6453, 0.6398"
80,B_10,float32,0,0.00,4190332,"0.2941, 0.2993, 0.3017, 0.2999, 0.2955, 0.2945, 0.2956, 0.2987, 0.3007, 0.2972"
81,S_5,float32,0,0.00,5290271,"0.0084, 0.0084, 0.0045, 0.0058, 0.0093, 0.0088, 0.0085, 0.0217, 0.0084, 0.0083"
82,B_11,float32,0,0.00,5309099,"0.167, 0.01, 0.008, 0.008, 0.0098, 0.0086, 0.0092, 0.0046, 0.0092, 0.0086"
83,B_12,float32,0,0.00,5193313,"0.0139, 0.0141, 0.015, 0.0092, 0.0117, 0.0115, 0.0108, 0.0104, 0.0102, 0.1147"
84,D_58,float32,0,0.00,5256972,"0.0092, 0.0085, 0.5802, 0.0087, 0.0081, 0.0078, 0.4344, 0.0078, 0.0095, 0.5617"
85,B_14,float32,0,0.00,5309932,"0.0081, 0.0092, 0.0082, 0.0638, 0.0413, 0.0769, 0.0079, 0.0329, 0.0083, 0.0083"
86,D_60,float32,0,0.00,4679920,"1.0043, 1.0061, 1.0057, 1.0061, 1.0016, 1.0082, 1.0072, 1.0073, 1.0063, 1.0054"
87,B_18,float32,0,0.00,2603059,"1.0, 0.6546, 0.6525, 0.6541, 0.6451, 0.6477, 0.6913, 0.688, 0.5852, 0.6478"
88,S_12,float32,0,0.00,2592981,"0.1879, 0.1875, 0.1868, 0.1854, 0.1932, 0.1928, 0.1879, 0.1903, 0.1942, 0.1863"
89,R_6,float32,0,0.00,4959486,"0.0092, 0.0078, 0.008, 0.0084, 0.0096, 0.0081, 0.0092, 0.0093, 0.0094, 0.0084"
90,B_21,float32,0,0.00,4944665,"0.0087, 0.0081, 0.0096, 0.01, 0.0086, 0.0091, 0.0083, 0.0088, 0.0093, 0.0092"
91,D_71,float32,0,0.00,5076426,"0.0157, 0.0111, 0.0159, 0.0157, 0.0158, 0.0092, 0.0096, 0.0089, 0.0092, 0.0123"
92,B_23,float32,0,0.00,5300841,"0.0094, 0.0099, 0.5924, 0.0204, 0.0332, 0.0335, 0.6275, 0.2597, 0.032, 0.1251"
93,P_4,float32,0,0.00,424684,"0.0, 0.9621, 0.9563, 0.9646, 0.965, 0.959, 0.9655, 0.9648, 0.9571, 0.965"
94,B_24,float32,0,0.00,4960342,"0.0096, 0.0087, 0.0086, 0.0089, 0.0082, 0.0097, 0.0084, 0.0098, 0.0098, 0.0084"
95,R_7,float32,1,0.00,144971,"0.0, 0.0714, 2.914, 0.6444, 0.1651, 0.0767, 2.3757, 29.0092, 1.7962, 0.2779"
96,S_16,float32,0,0.00,4944353,"0.0089, 0.0084, 0.0093, 0.0098, 0.0094, 0.0099, 0.0083, 0.0087, 0.0089, 0.009"
97,S_17,float32,0,0.00,4996175,"0.0099, 0.0099, 0.0092, 0.0097, 0.0085, 0.009, 0.0081, 0.009, 0.0099, 0.0089"
98,R_12,float32,56,0.00,153759,"1.0, -0.083, 0.1827, 0.0812, -0.0759, -0.0263, 0.2437, 0.3027, -0.0372, 0.0649"
99,B_28,float32,0,0.00,5274054,"0.0945, 0.0641, 0.1392, 0.2894, 0.0137, 0.2741, 0.0158, 0.0812, 0.1315, 0.515"
100,R_14,float32,1,0.00,77586,"0.0, 98.1861, 0.6022, 85.8193, 3.0991, 0.6357, 6.9912, 2.2664, 0.3364, 6.7433"
101,S_19,float32,0,0.00,4923015,"0.0094, 0.0086, 0.009, 0.0091, 0.0083, 0.006, 0.0088, 0.0085, 0.0084, 0.0099"
102,B_36,float32,0,0.00,4929153,"0.0095, 0.0082, 0.0085, 0.0099, 0.0079, 0.0098, 0.0098, 0.0097, 0.009, 0.0048"
103,B_37,float32,56,0.00,5318922,"0.0063, 0.009, 0.0097, 0.4565, 0.009, 0.0094, 0.1262, 0.0327, 0.0821, 0.035"
104,B_40,float32,53,0.00,5308815,"0.0246, 0.5919, 0.0083, 0.0337, 0.5711, 0.6322, 0.0083, 0.3735, 0.3158, 0.0334"
105,D_39,int16,0,0.00,180,"0, 1, 3, 2, 4, 5, 8, 6, 7, 10"
106,B_4,int16,0,0.00,293,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
107,D_49,int16,0,0.00,321,"-1, 1, 2, 4, 3, 5, 6, 7, 8, 9"
108,S_8,int16,0,0.00,32,"0, 1021, 2380, 528, 996, 1544, 2218, 1511, 2096, 1454"
109,D_65,int16,0,0.00,775,"0, 1, 7, 2, 3, 4, 5, 6, 8, 9"
110,S_13,int16,0,0.00,13,"0, 435, 290, 702, 1034, 872, 524, 643, 711, 544"
111,D_106,int16,0,0.00,309,"-1, 0, 2, 3, 1, 4, 5, 6, 7, 8"
112,R_26,int16,0,0.00,158,"-1, 0, 1, 2, 3, 4, 5, 6, 7, 8"
113,D_124,int16,0,0.00,61,"5, 4, 6, 3, 7, 8, 2, 9, 10, 11"
114,D_44,int8,0,0.00,38,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
115,R_2,int8,0,0.00,2,"0, 1"
116,D_51,int8,0,0.00,9,"0, 1, 2, 3, 4, 5, 6, 7, 8"
117,R_3,int8,0,0.00,91,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
118,S_6,int8,0,0.00,2,"0, 1"
119,R_4,int8,0,0.00,2,"0, 1"
120,R_5,int8,0,0.00,47,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
121,D_59,int8,0,0.00,104,"28, 27, 26, 8, 21, 25, 22, 29, 18, 23"
122,S_11,int8,0,0.00,83,"12, 15, 14, 16, 13, 17, 11, 18, 10, 19"
123,B_16,int8,0,0.00,14,"0, 12, 1, 2, 3, 11, 4, 10, 5, 7"
124,B_19,int8,0,0.00,47,"0, 100, 8, 50, 16, 33, 25, 66, 91, 83"
125,B_20,int8,0,0.00,19,"0, 17, 1, 2, 3, 5, 4, 6, 7, 8"
126,B_22,int8,0,0.00,9,"0, 1, 2, 3, -1, 4, 5, 6, 7"
127,D_70,int8,0,0.00,29,"0, 1, 2, 3, -1, 4, 5, 6, 7, 8"
128,D_72,int8,0,0.00,11,"0, 1, 2, -1, 3, 4, 9, 5, 6, 7"
129,S_15,int8,0,0.00,57,"8, 5, 6, 7, 4, 9, 3, 10, 11, 12"
130,D_74,int8,0,0.00,53,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
131,D_75,int8,0,0.00,57,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
132,D_78,int8,0,0.00,25,"0, -1, 1, 2, 3, 4, 5, 6, 7, 8"
133,D_79,int8,0,0.00,25,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
134,R_8,int8,0,0.00,33,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
135,R_9,int8,0,0.00,11,"-1, 1, 2, 0, 3, 4, 5, 6, 9, 7"
136,D_80,int8,0,0.00,38,"0, 1, 2, 3, 4, 5, -1, 6, 7, 8"
137,R_10,int8,0,0.00,18,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
138,R_11,int8,0,0.00,19,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
139,D_81,int8,0,0.00,10,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
140,D_82,int8,0,0.00,8,"-1, 1, 0, 2, 3, 4, 5, 6"
141,R_13,int8,0,0.00,28,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
142,D_83,int8,0,0.00,33,"0, -1, 1, 2, 3, 4, 5, 6, 7, 8"
143,R_15,int8,0,0.00,2,"0, 1"
144,D_84,int8,0,0.00,40,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
145,R_16,int8,0,0.00,32,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
146,S_18,int8,0,0.00,2,"0, 1"
147,D_86,int8,0,0.00,2,"0, 1"
148,D_87,int8,0,0.00,2,"-1, 1"
149,R_17,int8,0,0.00,25,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
150,R_18,int8,0,0.00,20,"0, 1, 2, 4, 3, 5, 7, 6, 10, 9"
151,B_31,int8,0,0.00,2,"1, 0"
152,R_19,int8,0,0.00,2,"0, 1"
153,B_32,int8,0,0.00,2,"0, 1"
154,S_20,int8,0,0.00,2,"0, 1"
155,R_20,int8,0,0.00,43,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
156,R_21,int8,0,0.00,2,"0, 1"
157,B_33,int8,0,0.00,3,"1, 0, -1"
158,D_89,int8,0,0.00,11,"0, 1, -1, 2, 3, 4, 5, 6, 9, 7"
159,R_22,int8,0,0.00,2,"0, 1"
160,R_23,int8,0,0.00,2,"0, 1"
161,D_91,int8,0,0.00,8,"0, 1, -1, 2, 3, 4, 5, 6"
162,D_92,int8,0,0.00,3,"0, 1, 2"
163,D_93,int8,0,0.00,2,"0, 1"
164,D_94,int8,0,0.00,2,"0, 1"
165,R_24,int8,0,0.00,2,"0, 1"
166,R_25,int8,0,0.00,2,"0, 1"
167,D_96,int8,0,0.00,2,"0, 1"
168,D_103,int8,0,0.00,3,"0, 1, -1"
169,D_107,int8,0,0.00,22,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
170,D_108,int8,0,0.00,11,"-1, 0, 1, 2, 3, 4, 5, 6, 9, 8"
171,D_109,int8,0,0.00,3,"0, 1, -1"
172,D_111,int8,0,0.00,4,"-1, 2, 1, 0"
173,D_113,int8,0,0.00,24,"0, 1, 2, 3, -1, 4, 5, 6, 7, 8"
174,D_122,int8,0,0.00,16,"1, 2, 3, 4, 5, 6, -1, 7, 0, 8"
175,D_123,int8,0,0.00,13,"0, 1, -1, 2, 3, 5, 104, 100, 62, 32"
176,D_125,int8,0,0.00,12,"0, 1, -1, 2, 3, 4, 5, 6, 8, 10"
177,D_127,int8,0,0.00,2,"0, 1"
178,D_129,int8,0,0.00,3,"0, 1, -1"
179,B_41,int8,0,0.00,21,"0, 1, 2, 3, 4, -1, 5, 6, 7, 8"
180,R_28,int8,0,0.00,2,"0, 1"
181,D_135,int8,0,0.00,3,"-1, 0, 1"
182,D_136,int8,0,0.00,9,"-1, 1, 0, 2, 3, 4, 5, 6, 7"
183,D_137,int8,0,0.00,3,"-1, 0, 1"
184,D_138,int8,0,0.00,8,"-1, 0, 1, 2, 3, 4, 5, 6"
185,D_139,int8,0,0.00,3,"0, 1, -1"
186,D_140,int8,0,0.00,3,"0, 1, -1"
187,D_143,int8,0,0.00,3,"0, 1, -1"
188,D_145,int8,0,0.00,52,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
189,target,int8,0,0.00,2,"0, 1"
190,customer_ID,object,0,0.00,458913,"fffff1d38b785cef84adeace64f8f83db3a0c31e8d92eaba8b115f71cab04681, fffac04d4779c019b73f555e7c969ddd8b05b1cd22127179379a1a88a2dde6a7, fffadb0b7f909848854778c7b4b3781430cff772bfcbdf84b35a9428bbebad3d, fffb1641cf36f09a91daf551b8f9d8bfece9fa055b6f60dc8a136016584d9729, fffb6886e0bfbb9bb719d153a1e41a780d107fc9190d0e3444efe01acc2f67e7, fffb8cb2a4375ee042827ce1e880268ca33b1091bb6811ae06f300fd6514a66b, fffba0c4fec239273a7758e4a49dc42463922f953d2aa5dea1275d099c35906c, fff94ae882244cbe97416913a5ee734eccbc81390db6c15830f89e71c50e3f97, fff94caf999925232878e3a6814229c7c8ec40a5b977c2171fe4aeaa77bc8167, fff95116500b345097426a54e70a067987829bf1d57543e51d8d4e17b8c94205"

In [6]:
# Numeric Feature Statistics
numeric_stats

            count         mean         std           min           max
P_2     5485466.0     0.656334    0.244649 -4.589548e-01      1.010000
D_39    5531451.0     5.035986    9.181833  0.000000e+00    183.000000
B_1     5531451.0     0.124010    0.211987 -7.588799e+00      1.324060
B_2     5529435.0     0.621489    0.401488  9.192280e-09      1.010000
R_1     5531451.0     0.078803    0.226397  1.534223e-09      3.256284
S_3     4510907.0     0.225845    0.193347 -6.271321e-01      5.482888
D_41    5529435.0     0.055435    0.203707  0.000000e+00      8.988807
B_3     5529435.0     0.132539    0.234993  6.285293e-09      1.625262
D_42     791314.0     0.184974    0.228185 -4.543303e-04      4.191119
D_43    3873055.0     0.154684    0.213398  1.154550e-07     10.111619
D_44    5531451.0     0.812945    1.774809 -1.000000e+00     45.000000
B_4     5531451.0    13.069095   17.346935  0.000000e+00   1544.000000
D_45    5529434.0     0.252187    0.242683  1.563241e-08      1.610002
B_5     5531451.0     0.083112    0.397043  2.804822e-11    144.207016
R_2     5531451.0     0.042516    0.201764  0.000000e+00      1.000000
D_46    4319752.0     0.475478    0.169893 -1.728934e+01     16.319901
D_47    5531451.0     0.407110    0.234799 -2.662164e-02      1.643096
D_48    4812726.0     0.381624    0.326479 -9.615277e-03      8.971425
D_49    5531451.0     0.407532    7.525524 -1.000000e+00   3254.000000
B_6     5531218.0     0.152117    1.476770 -5.178168e-03   1214.516968
B_7     5531451.0     0.186083    0.230419 -2.652749e+00      1.252750
B_8     5509183.0     0.447810    0.499421  0.000000e+00      1.019079
D_50    2389049.0     0.174435    0.633748 -3.064871e+02    244.042664
D_51    5531451.0     0.420226    0.726946  0.000000e+00      8.000000
B_9     5531451.0     0.189524    0.286274  6.726070e-09     27.424858
R_3     5531451.0     1.158301    2.104965  0.000000e+00    116.000000
D_52    5501888.0     0.180051    0.173865 -7.083110e-03      1.010000
P_3     5229959.0     0.601289    0.170799 -1.519690e+00      2.428051
B_10    5531451.0     0.231600    4.799846 -2.958481e-03   4097.440918
D_53    1446866.0     0.076183    0.202693  5.678129e-08      7.901939
S_5     5531451.0     0.088105    0.407405  8.168135e-09    206.875275
B_11    5531451.0     0.110969    0.208256  2.017814e-08      1.970375
S_6     5531451.0     0.239192    0.426590  0.000000e+00      1.000000
D_54    5529435.0     0.979742    0.140370 -2.005767e-03      1.000000
R_4     5531451.0     0.026205    0.159745  0.000000e+00      1.000000
S_7     4510907.0     0.223138    0.206303 -4.701318e-01      3.948271
B_12    5531451.0     0.093700    0.820427  3.343624e-08    420.748993
S_8     5531451.0  1021.351741  959.537364  0.000000e+00   3867.000000
D_55    5346648.0     0.298091    0.288742  2.353218e-08      2.767759
D_56    2540508.0     0.203710    0.212159 -1.708915e-02     10.956514
B_13    5481932.0     0.100715    0.559384  1.905850e-08    276.177826
R_5     5531451.0     0.059186    0.513583  0.000000e+00     70.000000
D_58    5531451.0     0.215531    0.260440  4.968945e-09      1.261945
S_9     2597808.0     0.074415    0.195998  2.823498e-07      2.839635
B_14    5531451.0     0.101155    0.283583 -8.469853e+00     55.011517
D_59    5531451.0    21.709431    9.716249 -1.000000e+00    108.000000
D_60    5531451.0     0.376155    0.371832  5.905030e-09      1.010000
D_61    4933399.0     0.429629    0.524527 -9.259018e-03    868.515442
B_15    5524528.0     0.052808    0.300550 -1.000805e+01     65.037430
S_11    5531451.0    14.258346    4.774680  0.000000e+00    100.000000
D_62    4773290.0     0.190662    0.230257 -2.822135e-03     11.100953
D_65    5531451.0     1.321066   17.977417  0.000000e+00  14664.000000
B_16    5531451.0     4.122231    4.828299 -1.000000e+00     12.000000
B_17    2393853.0     0.715240    0.386673  3.774555e-08      1.010000
B_18    5531451.0     0.594379    0.363528  5.891222e-08      1.000000
B_19    5531451.0    14.507921   28.956450 -1.000000e+00    100.000000
B_20    5531451.0     3.930388    6.352275 -1.000000e+00     17.000000
S_12    5531451.0     0.240463    0.250719 -4.041090e-01    175.331421
R_6     5531451.0     0.058531    0.641566  4.650681e-10     14.448201
S_13    5531451.0   258.162014  306.738952  0.000000e+00   1034.000000
B_21    5531451.0     0.053154    0.719635  4.426753e-09    288.294281
D_69    5336978.0     0.154041   16.009655  6.051601e-09  13000.909180
B_22    5531451.0     0.204027    0.447000 -1.000000e+00      7.000000
D_70    5531451.0     0.397890    0.921744 -1.000000e+00     28.000000
D_71    5531451.0     0.070832    0.326011  3.026939e-09     67.032310
D_72    5531451.0     0.092993    0.611611 -1.000000e+00      9.000000
S_15    5531451.0     6.697893    1.950759  0.000000e+00     56.000000
B_23    5531451.0     0.171480    0.229353  4.352963e-08      1.693098
D_73      55856.0     0.156493    0.204952 -4.526149e-02      3.853647
P_4     5531451.0     0.139648    0.340019  0.000000e+00      1.269390
D_74    5531451.0     2.066787    3.068434 -1.000000e+00     63.000000
D_75    5531451.0     2.492983    3.362906  0.000000e+00     64.000000
D_76     622497.0     0.140505    0.290127  3.128482e-07     15.132614
B_24    5531451.0     0.039651    0.317219  1.820939e-09     46.606647
R_7     5531450.0     0.083195    1.551131  0.000000e+00    449.988892
D_77    3017539.0     0.256556    0.232645  2.678714e-08     10.229170
B_25    5524528.0     0.103870    0.208705 -1.125358e+01     15.699759
B_26    5529435.0     0.090620    2.588205  1.691721e-09   1499.220337
D_78    5531451.0     0.059915    0.560600 -1.000000e+00     32.000000
D_79    5531451.0     0.112764    0.456478 -1.000000e+00     36.000000
R_8     5531451.0     0.033120    0.303627  0.000000e+00     38.000000
R_9     5531451.0    -0.867260    0.605819 -1.000000e+00      9.000000
S_16    5531451.0     0.050816    0.772487  5.083304e-09    231.758942
D_80    5531451.0     0.529000    1.075817 -1.000000e+00     40.000000
R_10    5531451.0     0.059774    0.305680  0.000000e+00     21.000000
R_11    5531451.0     0.091661    0.351196  0.000000e+00     25.000000
B_27    5529435.0     0.005008    0.003012  1.044159e-09      1.005370
D_81    5531451.0     0.045041    0.346625 -1.000000e+00      8.000000
D_82    5531451.0    -0.492650    0.864727 -1.000000e+00      6.000000
S_17    5531451.0     0.039720    0.241023  1.019806e-09      4.049070
R_12    5531395.0     0.974360    0.152903 -9.179347e-02      1.000000
B_28    5531451.0     0.154528    0.227502 -2.160207e-05     25.533373
R_13    5531451.0     0.014899    0.207156  0.000000e+00     31.000000
D_83    5531451.0    -0.000488    0.355967 -1.000000e+00     38.000000
R_14    5531450.0     0.236508    8.356590  0.000000e+00   4837.304688
R_15    5531451.0     0.015282    0.122673  0.000000e+00      1.000000
D_84    5531451.0     0.073730    0.574005 -1.000000e+00     58.000000
R_16    5531451.0     0.107075    0.478457  0.000000e+00     37.000000
B_29     381416.0     0.032998    0.276513  2.146359e-08     12.023968
S_18    5531451.0     0.026466    0.160517  0.000000e+00      1.000000
D_86    5531451.0     0.032498    0.177318  0.000000e+00      1.000000
D_87    5531451.0    -0.998603    0.052849 -1.000000e+00      1.000000
R_17    5531451.0     0.011167    0.199184  0.000000e+00     35.000000
R_18    5531451.0     0.000284    0.045576  0.000000e+00     31.000000
D_88       6004.0     0.172304    0.218063 -3.196266e-05      2.669250
B_31    5531451.0     0.996943    0.055201  0.000000e+00      1.000000
S_19    5531451.0     0.005026    0.003069  3.156390e-09      1.000000
R_19    5531451.0     0.017694    0.131836  0.000000e+00      1.000000
B_32    5531451.0     0.022415    0.148030  0.000000e+00      1.000000
S_20    5531451.0     0.012488    0.111050  0.000000e+00      1.000000
R_20    5531451.0     0.031932    0.378071 -1.000000e+00     45.000000
R_21    5531451.0     0.016613    0.127816  0.000000e+00      1.000000
B_33    5531451.0     0.606608    0.489248 -1.000000e+00      1.000000
D_89    5531451.0     0.007601    0.184255 -1.000000e+00      9.000000
R_22    5531451.0     0.003606    0.059938  0.000000e+00      1.000000
R_23    5531451.0     0.000296    0.017195  0.000000e+00      1.000000
D_91    5531451.0     0.082737    0.411513 -1.000000e+00      6.000000
D_92    5531451.0     0.086020    0.293606  0.000000e+00      2.000000
D_93    5531451.0     0.010105    0.100017  0.000000e+00      1.000000
D_94    5531451.0     0.017272    0.130283  0.000000e+00      1.000000
R_24    5531451.0     0.013918    0.117151  0.000000e+00      1.000000
R_25    5531451.0     0.003206    0.056528  0.000000e+00      1.000000
D_96    5531451.0     0.030720    0.172558  0.000000e+00      1.000000
S_22    5512427.0     0.779104    0.718747 -9.199815e+01      1.032727
S_23    5531006.0     0.179677    0.851958 -2.060855e+02    885.334900
S_24    5512858.0     0.734920    0.835673 -9.048383e+01      1.055638
S_25    5518604.0     0.925038    0.206805 -2.453451e+00      4.052048
S_26    5530817.0     0.066840    0.463808  5.137101e-09    136.665985
D_102   5490796.0     0.189837    0.274805  9.620587e-10      1.089998
D_103   5531451.0     0.435418    0.531550 -1.000000e+00      1.000000
D_104   5429903.0     0.447938    0.483231  0.000000e+00      1.302976
D_105   2510020.0     0.370122    0.250521 -2.640482e-02      5.631732
D_106   5531451.0    -0.451386    9.200740 -1.000000e+00  14417.000000
D_107   5531451.0     0.576213    0.794398 -1.000000e+00     21.000000
B_36    5531451.0     0.006360    0.021239  1.160856e-09      1.000000
B_37    5531395.0     0.123190    0.211777 -7.604273e+00      1.327812
R_26    5531451.0    -0.644158    2.485526 -1.000000e+00    266.000000
R_27    5402748.0     0.893694    0.312307 -2.571099e-02      1.010000
D_108   5531451.0    -0.994421    0.080376 -1.000000e+00      9.000000
D_109   5531451.0     0.001370    0.044112 -1.000000e+00      1.000000
D_110     31334.0     0.739263    0.308294 -2.374994e-02      1.010000
D_111   5531451.0    -0.984484    0.209535 -1.000000e+00      2.000000
B_39      33632.0     0.255473    0.297895 -9.793140e-01      2.060899
D_112   5528801.0     0.836867    0.367544  4.344640e-08      1.000000
B_40    5531398.0     0.203261    8.081345  1.201275e-08   5755.076172
S_27    4130516.0     0.277978    0.325033  4.417077e-10      5.456269
D_113   5531451.0     0.703559    1.157140 -1.000000e+00    125.000000
D_115   5354735.0     0.278129    0.256212  2.228054e-07      1.999540
D_118   5354735.0     0.283512    0.255950  2.551906e-08      1.970907
D_119   5354735.0     0.279408    0.256467  7.076709e-08      1.977007
D_121   5354735.0     0.532244    0.233808 -3.207547e-02      1.791115
D_122   5531451.0     2.674699    1.762807 -1.000000e+00     14.000000
D_123   5531451.0     0.012105    0.303632 -1.000000e+00    104.000000
D_124   5531451.0     7.336947    5.123307 -1.000000e+00    201.000000
D_125   5531451.0     0.044860    0.344540 -1.000000e+00     14.000000
D_127   5531451.0     0.102547    0.303366  0.000000e+00      1.000000
D_128   5429903.0     0.582019    0.495615  0.000000e+00      1.023472
D_129   5531451.0     0.408605    0.527602 -1.000000e+00      1.000000
B_41    5531451.0     0.027221    0.222569 -1.000000e+00     22.000000
B_42      71478.0     0.110038    0.313704  3.108574e-06      9.051837
D_130   5429903.0     0.197645    0.399473  0.000000e+00      1.028044
D_131   5429903.0     0.098876    0.296819  0.000000e+00      1.491624
D_132    542577.0     0.210199    0.247630 -1.510199e-02      6.039006
D_133   5488735.0     0.046144    0.172090  6.380582e-10      1.510000
R_28    5531451.0     0.000742    0.027225  0.000000e+00      1.000000
D_134    194699.0     0.330082    0.296216 -1.244420e-02      1.010000
D_135   5531451.0    -0.963922    0.191141 -1.000000e+00      1.000000
D_136   5531451.0    -0.931324    0.392607 -1.000000e+00      7.000000
D_137   5531451.0    -0.964476    0.186847 -1.000000e+00      1.000000
D_138   5531451.0    -0.953565    0.262945 -1.000000e+00      6.000000
D_139   5531451.0     0.152378    0.407278 -1.000000e+00      1.000000
D_140   5531451.0     0.014139    0.169206 -1.000000e+00      1.000000
D_141   5429903.0     0.160391    0.350159  0.000000e+00      1.339910
D_142    944408.0     0.390799    0.236182 -1.453934e-02      2.229368
D_143   5531451.0     0.152253    0.407172 -1.000000e+00      1.000000
D_144   5490724.0     0.052390    0.182514  2.500991e-09      1.343331
D_145   5531451.0     0.600745    2.119894 -1.000000e+00     53.000000
target  5531451.0     0.249097    0.432490  0.000000e+00      1.000000

In [7]:
# Categorical Feature Statistics
cat_stats

                                                                             value  \
column      rank
B_30        1                                                                    0
            2                                                                    1
            3                                                                    2
            4                                                                   -1
B_38        1                                                                    2
            2                                                                    3
            3                                                                    1
            4                                                                    5
            5                                                                    4
D_114       1                                                                    1
            2                                                                    0
            3                                                                   -1
D_116       1                                                                    0
            2                                                                   -1
            3                                                                    1
D_117       1                                                                    0
            2                                                                    4
            3                                                                    5
            4                                                                    3
            5                                                                    6
D_120       1                                                                    0
            2                                                                    1
            3                                                                   -1
D_126       1                                                                    2
            2                                                                    1
            3                                                                    0
            4                                                                   -1
D_63        1                                                                    3
            2                                                                    0
            3                                                                    4
            4                                                                    1
            5                                                                    2
D_64        1                                                                    0
            2                                                                    3
            3                                                                    2
            4                                                                   -1
            5                                                                    1
D_66        1                                                                   -1
            2                                                                    1
            3                                                                    0
D_68        1                                                                    6
            2                                                                    5
            3                                                                    3
            4                                                                    4
            5                                                                    2
S_2         1                                                  2018-02-17 00:00:00
            2                                                  2018-01-20 00:00:00
            3                                                  2018-02-03 00:00:00
            4                                                  2018-03-17 00:00:00
            5                                                  2018-02-24 00:00:00
customer_ID 1     fffff1d38b785cef84adeace64f8f83db3a0c31e8d92eaba8b115f71cab04681
            2     fffac04d4779c019b73f555e7c969ddd8b05b1cd22127179379a1a88a2dde6a7
            3     fffadb0b7f909848854778c7b4b3781430cff772bfcbdf84b35a9428bbebad3d
            4     fffb1641cf36f09a91daf551b8f9d8bfece9fa055b6f60dc8a136016584d9729
            5     fffb6886e0bfbb9bb719d153a1e41a780d107fc9190d0e3444efe01acc2f67e7

                    count    pct
column      rank
B_30        1     4710663  85.16
            2      763955  13.81
            3       54817   0.99
            4        2016   0.04
B_38        1     1953232  35.31
            2     1255315  22.69
            3     1160047  20.97
            4      444856   8.04
            5      294917   5.33
D_114       1     3316478  59.96
            2     2038257  36.85
            3      176716   3.19
D_116       1     5348109  96.69
            2      176716   3.19
            3        6626   0.12
D_117       1     1456084  26.32
            2     1166400  21.09
            3     1138666  20.59
            4      666808  12.05
            5      459290   8.30
D_120       1     4729723  85.51
            2      625012  11.30
            3      176716   3.19
D_126       1     4262414  77.06
            2      891323  16.11
            3      260898   4.72
            4      116816   2.11
D_63        1     4119621  74.48
            2      930133  16.82
            3      438390   7.93
            4       25786   0.47
            5       10556   0.19
D_64        1     2913244  52.67
            2     1523448  27.54
            3      840112  15.19
            4      217442   3.93
            5       37205   0.67
D_66        1     4908097  88.73
            2      617066  11.16
            3        6288   0.11
D_68        1     2782455  50.30
            2     1201706  21.72
            3      484442   8.76
            4      477187   8.63
            5      220111   3.98
S_2         1       26715   0.48
            2       25016   0.45
            3       23966   0.43
            4       23373   0.42
            5       23356   0.42
customer_ID 1          13   0.00
            2          13   0.00
            3          13   0.00
            4          13   0.00
            5          13   0.00

In [8]:
# Target Distribution
target_df

          count    pct
target
0       4153582  75.09
1       1377869  24.91

## Task Curation

In [ ]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from sklearn.model_selection import StratifiedGroupKFold

splits = {0: {}}

sklearn_splits = StratifiedGroupKFold(n_splits=3, random_state=42, shuffle=True).split(
    X=df,
    y=df[task_mold.target_column_name],
    groups=df[task_mold.group_on],
)
print_once = False
for fold_idx, (train_index, test_index) in enumerate(sklearn_splits):
    # Print len, target col count, and group counts
    train_data = df.iloc[train_index]
    test_data = df.iloc[test_index]

    if not print_once:
        print(f"""Train N: {len(train_index)}, Test N: {len(test_index)}
        Target Distribution:
        \tTrain target distribution: {df.iloc[train_index][task_mold.target_column_name].value_counts(normalize=True).to_dict()}
        \tTest target distribution: {df.iloc[test_index][task_mold.target_column_name].value_counts(normalize=True).to_dict()}
        Group Distribution {task_mold.group_on}:
        \tTrain: {len(train_data[task_mold.group_on].unique())}
        \tTest: {len(test_data[task_mold.group_on].unique())}
        """
        )
        print_once = True
    splits[0][fold_idx] = (train_index.tolist(), test_index.tolist())

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="We create stratified grouped 3-fold split. This represents 150k (33%) customers and 1.8 million samples per test split. The label are equally represented in all train and test sets. Note, we will likely only use the first fold.",
        splits=splits
)

## Export

In [10]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019c392e-d78c-7969-9f83-1e3bb2eb8a21
8cb9c9d3873cdc11fbefe37bffa09e02f39182ce24e0e2b0b464afd42d1f97cf