### Dataset and Task Metadata

In [ ]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="aps_failure",
    dataset_year="2016",
    domain_str="industry & manufacturing",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C5V60Q",
    download_description="""
    mkdir -p local-data-warehouse/aps_failure 
    wget -P local-data-warehouse/aps_failure/ https://archive.ics.uci.edu/static/public/414/ida2016challenge.zip 
    unzip local-data-warehouse/aps_failure/ida2016challenge.zip -d local-data-warehouse/aps_failure/ 
    rm local-data-warehouse/aps_failure/ida2016challenge.zip
""",
    # References
    academic_reference_bibtex="""@misc{ida2016challenge,
  author       = {{IDA2016Challenge}},
  title        = {IDA2016Challenge [Dataset]},
  year         = {2016},
  howpublished = {\\url{https://doi.org/10.24432/C5V60Q}},
  note         = {UCI Machine Learning Repository},
}
""",
    academic_reference_bibtex_key="ida2016challenge",
    license="CC BY 4.0",
    data_tags=["ForcedIIDFromTemporal", "Anonymized"],
    curation_comments="""
  - We combined the original training and testing data into a single dataset.
  - We renamed the target feature to "AirPressureSystemFailure".
  - We converted "na" strings to real NaN/missing values, making the data numeric.
  - Anomaly: we cannot determine the data types of the features.
  - Anomaly: some features are bins of histograms (see original data description).
  - Anomaly: the original task used a cost matrix for evaluation.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="AirPressureSystemFailure",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="AirPressureSystemFailure",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

df = pd.concat(
    [
        pd.read_csv(f"{dataset_mold.path}/to_uci/aps_failure_training_set.csv", skiprows=20, na_values="na"),
        pd.read_csv(f"{dataset_mold.path}/to_uci/aps_failure_test_set.csv", skiprows=20, na_values="na"),
    ]
)

df.rename(columns={"class": "AirPressureSystemFailure"}, inplace=True)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print("Loaded data shape:", df.shape)

Loaded data shape: (76000, 171)

In [3]:
# Use if needed to get see all cols of pandas dataframes
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
df.head()

,AirPressureSystemFailure,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,ag_004,ag_005,ag_006,ag_007,ag_008,ag_009,ah_000,ai_000,aj_000,ak_000,al_000,am_0,an_000,ao_000,ap_000,aq_000,ar_000,as_000,at_000,au_000,av_000,ax_000,ay_000,ay_001,ay_002,ay_003,ay_004,ay_005,ay_006,ay_007,ay_008,ay_009,az_000,az_001,az_002,az_003,az_004,az_005,az_006,az_007,az_008,az_009,ba_000,ba_001,ba_002,ba_003,ba_004,ba_005,ba_006,ba_007,ba_008,ba_009,bb_000,bc_000,bd_000,be_000,bf_000,bg_000,bh_000,bi_000,bj_000,bk_000,bl_000,bm_000,bn_000,bo_000,bp_000,bq_000,br_000,bs_000,bt_000,bu_000,bv_000,bx_000,by_000,bz_000,ca_000,cb_000,cc_000,cd_000,ce_000,cf_000,cg_000,ch_000,ci_000,cj_000,ck_000,cl_000,cm_000,cn_000,cn_001,cn_002,cn_003,cn_004,cn_005,cn_006,cn_007,cn_008,cn_009,co_000,cp_000,cq_000,cr_000,cs_000,cs_001,cs_002,cs_003,cs_004,cs_005,cs_006,cs_007,cs_008,cs_009,ct_000,cu_000,cv_000,cx_000,cy_000,cz_000,da_000,db_000,dc_000,dd_000,de_000,df_000,dg_000,dh_000,di_000,dj_000,dk_000,dl_000,dm_000,dn_000,do_000,dp_000,dq_000,dr_000,ds_000,dt_000,du_000,dv_000,dx_000,dy_000,dz_000,ea_000,eb_000,ec_00,ed_000,ee_000,ee_001,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,4090,0.0,268.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,79820.0,0.0,0.0,0.0,30902.0,50622.0,242674.0,244736.0,54112.0,13910.0,0.0,0.0,0.0,0.0,132.0,208.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,327848.0,138.0,114.0,284.0,4.0,79820.0,1820.0,22336.0,31272.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52820.0,4089.02,327848.0,327848.0,296.0,0.0,92.0,31980.0,326140.0,0.0,1209600.0,4826.0,0.0,0.0,0.0,200013.12,4826.88,79081.92,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,327848.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,590.0,398.0,10430.0,6734.0,0.0,0.0,0.0,0.0,0.0,0.0,2232.0,18.0,6.0,0.0,0.0,4288.0,638.0,987500.0,98836.0,0.0,0.0,0.0,0.0,3089100.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,neg,12,0.0,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,2328.0,1006.0,1700.0,0.0,0.0,0.0,622.0,0.0,0.0,0.0,442.0,792.0,11258.0,10292.0,18590.0,366.0,0.0,0.0,0.0,0.0,14.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,430.0,4604.0,0.0,40.0,362.0,752.0,44.0,12.0,140.0,3684.0,0.0,0.0,0.0,3532.0,336.0,80.0,80.0,266.0,56.0,454.0,56.0,18.0,156.0,30308.0,0.0,6.0,0.0,0.0,622.0,110.0,16982.0,1526.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18400.0,12.59,30308.0,30308.0,33030.0,27.0,18.0,2976.0,30100.0,5066.0,1209600.0,270.0,2.0,2.0,0.0,1973.76,0.00,1933.44,0.0,6.0,0.0,0.0,2170.0,346.0,1586.0,354.0,578.0,0.0,0.0,0.0,0.0,0.0,30308.0,0.0,1198.0,8.0,18.0,2.0,30.0,624.0,2356.0,772.0,26.0,0.0,4.0,20.0,2108.0,74.0,0.0,0.0,0.0,0.0,2170.0,32.0,42.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,158.0,0.0,0.0,0.0,0.0,20.0,16.0,7260.0,728.0,0.0,6.0,0.0,0.0,0.0,0.58,30.0,3258.0,1532.0,30.0,8.0,38.0,32.0,60.0,76.0,0.0,0.0,0.0,0.0
2,neg,378,NaN,32.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,148.0,3212.0,28760.0,1020.0,0.0,0.0,16812.0,0.0,0.0,0.0,0.0,0.0,28814.0,21958.0,37052.0,2696.0,0.0,0.0,0.0,0.0,18.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,29092.0,2296.0,1752.0,0.0,1786.0,30.0,148.0,144.0,488.0,30266.0,278.0,0.0,0.0,0.0,22570.0,7592.0,2202.0,270.0,78.0,146.0,278.0,4.0,0.0,0.0,65890.0,2.0,58.0,22.0,0.0,16812.0,494.0,30462.0,6552.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36740.0,377.91,65890.0,65890.0,67674.0,98.0,0.0,6298.0,65580.0,33140.0,1209600.0,944.0,2.0,0.0,0.0,22626.24,0.00,8659.20,NaN,NaN,0.0,0.0,0.0,1266.0,18886.0,12068.0,800.0,100.0,20.0,0.0,0.0,4.0,65890.0,NaN,1880.0,24.0,504.0,1644.0,536.0,14222.0,12174.0,2072.0,84.0,0.0,62.0,70.0,19596.0,12412.0,42.0,42.0,0.0,0.0,20494.0,94.0,38.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,448.0,4.0,2.0,0.0,0.0,528.0,122.0,1100.0,110.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,11074.0,5894.0,1324.0,346.0,386.0,14064.0,22.0,30.0,0.0,0.0,0.0,0.0
3,neg,10616,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,6882.0,120030.0,420100.0,212040.0,10278.0,0.0,0.0,301262.0,0.0,0.0,0.0,5332.0,6890.0,745736.0,722518.0,54604.0,16356.0,0.0,0.0,0.0,0.0,0.0,0.0,36354.0,14584.0,9986.0,17572.0,5890.0,70778.0,200230.0,180584.0,233352.0,0.0,412.0,62.0,114.0,128.0,112568.0,651344.0,4700.0,2.0,0.0,0.0,205006.0,453566.0,72738.0,28332.0,7346.0,1552.0,560.0,218.0,12.0,0.0,805816.0,8.0,18.0,2292.0,0.0,301262.0,3746.0,26092.0,28258.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53340.0,10616.93,805816.0,805816.0,801172.0,2639.0,98416.0,79806.0,804240.0,769330.0,1209600.0,0.0,NaN,NaN,NaN,701064.96,1557.12,66096.00,0.0,0.0,0.0,1372.0,50704.0,289958.0,379072.0,43626.0,3378.0,1090.0,130.0,0.0,NaN,62.0,805816.0,NaN,904.0,124.0,28622.0,56558.0,17242.0,474234.0,181904.0,9482.0,260.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,452.0,62.0,0.0,0.0,0.0,1556.0,0.0,0.0,0.0,0.0,2044.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1354.0,0.0,0.0,9617300.0,308.56,312.0,70910.0,64386.0,524588.0,90948.0,14080.0,2914.0,814.0,422.0,268.0,0.0,0.0,0.0
4,neg,38218,NaN,414.0,408.0,0.0,0.0,0.0,0.0,0.0,13824.0,295106.0,1741854.0,551684.0,10024.0,0.0,0.0,1179564.0,0.0,0.0,0.0,4022.0,5530.0,2460798.0,2255538.0,249410.0,154582.0,0.0,0.0,0.0,0.0,860.0,818.0,0.0,0.0,0.0,0.0,0.0,0.0,395580.0,195454.0,2021458.0,0.0,1918.0,422.0,552.0,2662.0,552344.0,2028092.0,26500.0,2.0,0.0,0.0,663592.0,771508.0,485780.0,302198.0,177166.0,97968.0,79000.0,35280.0,0.0,0.0,2715140.0,0.0,1046.0,348.0,2.0,1179564.0,28408.0,118806.0,129822.0,100280.0,122280.0,NaN,NaN,NaN,NaN,NaN,NaN,19640.0,38218.16,2715140.0,2715140.0,2730004.0,11045.0,5034.0,25720.0,287460.0,2612492.0,1209600.0,77324.0,0.0,66.0,0.0,2365926.72,0.00,243192.00,0.0,0.0,0.0,0.0,33628.0,962226.0,1217154.0,332462.0,48768.0,15110.0,3108.0,36.0,2.0,8.0,2715140.0,NaN,4746.0,778.0,6470.0,210936.0,149414.0,2068292.0,168124.0,3732.0,0.0,0.0,562.0,8854.0,2331968.0,344560.0,0.0,5422.0,32.0,18.0,2394976.0,2572.0,210.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14612.0,24864.0,5742.0,0.0,0.0,78440.0,16566.0,192340.0,25464.0,0.0,0.0,0.0,0.0,442190.0,1447.08,1656.0,268084.0,574602.0,429814.0,193228.0,364644.0,498410.0,196434.0,43556.0,42866.0,854.0,0.0,0.0

## Data Checks

In [4]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 76,000
Columns: 171
Use sampling: False (sample size: 76,000)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['bx_000', 'bb_000', 'bu_000', 'cq_000', 'bv_000', 'an_000', 'ao_000', 'ci_000', 'bt_000', 'ck_000']
Rows remaining as candidates after top-10 filter: 107 (of 76,000)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [5]:
# Sample Rows
df_head

,AirPressureSystemFailure,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,ag_004,ag_005,ag_006,ag_007,ag_008,ag_009,ah_000,ai_000,aj_000,ak_000,al_000,am_0,an_000,ao_000,ap_000,aq_000,ar_000,as_000,at_000,au_000,av_000,ax_000,ay_000,ay_001,ay_002,ay_003,ay_004,ay_005,ay_006,ay_007,ay_008,ay_009,az_000,az_001,az_002,az_003,az_004,az_005,az_006,az_007,az_008,az_009,ba_000,ba_001,ba_002,ba_003,ba_004,ba_005,ba_006,ba_007,ba_008,ba_009,bb_000,bc_000,bd_000,be_000,bf_000,bg_000,bh_000,bi_000,bj_000,bk_000,bl_000,bm_000,bn_000,bo_000,bp_000,bq_000,br_000,bs_000,bt_000,bu_000,bv_000,bx_000,by_000,bz_000,ca_000,cb_000,cc_000,cd_000,ce_000,cf_000,cg_000,ch_000,ci_000,cj_000,ck_000,cl_000,cm_000,cn_000,cn_001,cn_002,cn_003,cn_004,cn_005,cn_006,cn_007,cn_008,cn_009,co_000,cp_000,cq_000,cr_000,cs_000,cs_001,cs_002,cs_003,cs_004,cs_005,cs_006,cs_007,cs_008,cs_009,ct_000,cu_000,cv_000,cx_000,cy_000,cz_000,da_000,db_000,dc_000,dd_000,de_000,df_000,dg_000,dh_000,di_000,dj_000,dk_000,dl_000,dm_000,dn_000,do_000,dp_000,dq_000,dr_000,ds_000,dt_000,du_000,dv_000,dx_000,dy_000,dz_000,ea_000,eb_000,ec_00,ed_000,ee_000,ee_001,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,4090,0.0,268.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,79820.0,0.0,0.0,0.0,30902.0,50622.0,242674.0,244736.0,54112.0,13910.0,0.0,0.0,0.0,0.0,132.0,208.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,327848.0,138.0,114.0,284.0,4.0,79820.0,1820.0,22336.0,31272.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52820.0,4089.02,327848.0,327848.0,296.0,0.0,92.0,31980.0,326140.0,0.0,1209600.0,4826.0,0.0,0.0,0.0,200013.12,4826.88,79081.92,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,327848.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,590.0,398.0,10430.0,6734.0,0.0,0.0,0.0,0.0,0.0,0.0,2232.0,18.0,6.0,0.0,0.0,4288.0,638.0,987500.0,98836.0,0.0,0.0,0.0,0.0,3089100.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,neg,12,0.0,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,2328.0,1006.0,1700.0,0.0,0.0,0.0,622.0,0.0,0.0,0.0,442.0,792.0,11258.0,10292.0,18590.0,366.0,0.0,0.0,0.0,0.0,14.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,430.0,4604.0,0.0,40.0,362.0,752.0,44.0,12.0,140.0,3684.0,0.0,0.0,0.0,3532.0,336.0,80.0,80.0,266.0,56.0,454.0,56.0,18.0,156.0,30308.0,0.0,6.0,0.0,0.0,622.0,110.0,16982.0,1526.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18400.0,12.59,30308.0,30308.0,33030.0,27.0,18.0,2976.0,30100.0,5066.0,1209600.0,270.0,2.0,2.0,0.0,1973.76,0.00,1933.44,0.0,6.0,0.0,0.0,2170.0,346.0,1586.0,354.0,578.0,0.0,0.0,0.0,0.0,0.0,30308.0,0.0,1198.0,8.0,18.0,2.0,30.0,624.0,2356.0,772.0,26.0,0.0,4.0,20.0,2108.0,74.0,0.0,0.0,0.0,0.0,2170.0,32.0,42.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,158.0,0.0,0.0,0.0,0.0,20.0,16.0,7260.0,728.0,0.0,6.0,0.0,0.0,0.0,0.58,30.0,3258.0,1532.0,30.0,8.0,38.0,32.0,60.0,76.0,0.0,0.0,0.0,0.0
2,neg,378,NaN,32.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,148.0,3212.0,28760.0,1020.0,0.0,0.0,16812.0,0.0,0.0,0.0,0.0,0.0,28814.0,21958.0,37052.0,2696.0,0.0,0.0,0.0,0.0,18.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,29092.0,2296.0,1752.0,0.0,1786.0,30.0,148.0,144.0,488.0,30266.0,278.0,0.0,0.0,0.0,22570.0,7592.0,2202.0,270.0,78.0,146.0,278.0,4.0,0.0,0.0,65890.0,2.0,58.0,22.0,0.0,16812.0,494.0,30462.0,6552.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36740.0,377.91,65890.0,65890.0,67674.0,98.0,0.0,6298.0,65580.0,33140.0,1209600.0,944.0,2.0,0.0,0.0,22626.24,0.00,8659.20,NaN,NaN,0.0,0.0,0.0,1266.0,18886.0,12068.0,800.0,100.0,20.0,0.0,0.0,4.0,65890.0,NaN,1880.0,24.0,504.0,1644.0,536.0,14222.0,12174.0,2072.0,84.0,0.0,62.0,70.0,19596.0,12412.0,42.0,42.0,0.0,0.0,20494.0,94.0,38.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,448.0,4.0,2.0,0.0,0.0,528.0,122.0,1100.0,110.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,11074.0,5894.0,1324.0,346.0,386.0,14064.0,22.0,30.0,0.0,0.0,0.0,0.0
3,neg,10616,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,6882.0,120030.0,420100.0,212040.0,10278.0,0.0,0.0,301262.0,0.0,0.0,0.0,5332.0,6890.0,745736.0,722518.0,54604.0,16356.0,0.0,0.0,0.0,0.0,0.0,0.0,36354.0,14584.0,9986.0,17572.0,5890.0,70778.0,200230.0,180584.0,233352.0,0.0,412.0,62.0,114.0,128.0,112568.0,651344.0,4700.0,2.0,0.0,0.0,205006.0,453566.0,72738.0,28332.0,7346.0,1552.0,560.0,218.0,12.0,0.0,805816.0,8.0,18.0,2292.0,0.0,301262.0,3746.0,26092.0,28258.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53340.0,10616.93,805816.0,805816.0,801172.0,2639.0,98416.0,79806.0,804240.0,769330.0,1209600.0,0.0,NaN,NaN,NaN,701064.96,1557.12,66096.00,0.0,0.0,0.0,1372.0,50704.0,289958.0,379072.0,43626.0,3378.0,1090.0,130.0,0.0,NaN,62.0,805816.0,NaN,904.0,124.0,28622.0,56558.0,17242.0,474234.0,181904.0,9482.0,260.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,452.0,62.0,0.0,0.0,0.0,1556.0,0.0,0.0,0.0,0.0,2044.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1354.0,0.0,0.0,9617300.0,308.56,312.0,70910.0,64386.0,524588.0,90948.0,14080.0,2914.0,814.0,422.0,268.0,0.0,0.0,0.0
4,neg,38218,NaN,414.0,408.0,0.0,0.0,0.0,0.0,0.0,13824.0,295106.0,1741854.0,551684.0,10024.0,0.0,0.0,1179564.0,0.0,0.0,0.0,4022.0,5530.0,2460798.0,2255538.0,249410.0,154582.0,0.0,0.0,0.0,0.0,860.0,818.0,0.0,0.0,0.0,0.0,0.0,0.0,395580.0,195454.0,2021458.0,0.0,1918.0,422.0,552.0,2662.0,552344.0,2028092.0,26500.0,2.0,0.0,0.0,663592.0,771508.0,485780.0,302198.0,177166.0,97968.0,79000.0,35280.0,0.0,0.0,2715140.0,0.0,1046.0,348.0,2.0,1179564.0,28408.0,118806.0,129822.0,100280.0,122280.0,NaN,NaN,NaN,NaN,NaN,NaN,19640.0,38218.16,2715140.0,2715140.0,2730004.0,11045.0,5034.0,25720.0,287460.0,2612492.0,1209600.0,77324.0,0.0,66.0,0.0,2365926.72,0.00,243192.00,0.0,0.0,0.0,0.0,33628.0,962226.0,1217154.0,332462.0,48768.0,15110.0,3108.0,36.0,2.0,8.0,2715140.0,NaN,4746.0,778.0,6470.0,210936.0,149414.0,2068292.0,168124.0,3732.0,0.0,0.0,562.0,8854.0,2331968.0,344560.0,0.0,5422.0,32.0,18.0,2394976.0,2572.0,210.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14612.0,24864.0,5742.0,0.0,0.0,78440.0,16566.0,192340.0,25464.0,0.0,0.0,0.0,0.0,442190.0,1447.08,1656.0,268084.0,574602.0,429814.0,193228.0,364644.0,498410.0,196434.0,43556.0,42866.0,854.0,0.0,0.0

In [6]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,br_000,float64,62393.0,82.10,4607.0,"1310700.0, 0.0, 229360.0, 205800.0, 267280.0, 218560.0, 250840.0, 292360.0, 181280.0, 288400.0"
1,bq_000,float64,61703.0,81.19,5116.0,"1310700.0, 0.0, 220000.0, 165940.0, 349100.0, 308480.0, 267400.0, 136780.0, 214300.0, 153480.0"
2,bp_000,float64,60461.0,79.55,5863.0,"1310700.0, 0.0, 168060.0, 289660.0, 161080.0, 241360.0, 235700.0, 216480.0, 196220.0, 204920.0"
3,bo_000,float64,58709.0,77.25,6828.0,"1310700.0, 0.0, 221400.0, 235860.0, 377320.0, 209740.0, 133900.0, 208740.0, 272300.0, 403280.0"
4,ab_000,float64,58692.0,77.23,30.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 24.0"
5,cr_000,float64,58692.0,77.23,86.0,"0.0, 44.0, 3750.0, 1234.0, 4.0, 1416.0, 54.0, 52.0, 450.0, 2632.0"
6,bn_000,float64,55722.0,73.32,8216.0,"1310700.0, 0.0, 182360.0, 254940.0, 222060.0, 300080.0, 162980.0, 184040.0, 198080.0, 261620.0"
7,bm_000,float64,50095.0,65.91,10254.0,"1310700.0, 0.0, 193240.0, 198100.0, 237100.0, 259560.0, 212200.0, 228140.0, 159060.0, 178380.0"
8,bl_000,float64,34503.0,45.40,13085.0,"1310700.0, 0.0, 156260.0, 174560.0, 160580.0, 213400.0, 172900.0, 179340.0, 181280.0, 169300.0"
9,bk_000,float64,29128.0,38.33,14029.0,"1310700.0, 0.0, 161880.0, 179220.0, 212520.0, 167800.0, 186480.0, 145460.0, 175300.0, 171740.0"
10,ad_000,float64,18842.0,24.79,2027.0,"0.0, 2.0, 4.0, 6.0, 10.0, 8.0, 16.0, 12.0, 14.0, 20.0"
11,cf_000,float64,18842.0,24.79,583.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
12,cg_000,float64,18842.0,24.79,716.0,"4.0, 0.0, 2.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
13,ch_000,float64,18842.0,24.79,2.0,"0.0, 2.0"
14,co_000,float64,18842.0,24.79,2045.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
15,ct_000,float64,17526.0,23.06,2824.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 16.0, 14.0, 20.0"
16,cu_000,float64,17526.0,23.06,3818.0,"0.0, 2.0, 6.0, 4.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
17,cv_000,float64,17526.0,23.06,38941.0,"0.0, 2280.0, 2038.0, 1442.0, 1332.0, 1436.0, 1346.0, 1328.0, 1986.0, 1700.0"
18,cx_000,float64,17526.0,23.06,29452.0,"0.0, 52.0, 60.0, 56.0, 40.0, 70.0, 68.0, 72.0, 34.0, 42.0"
19,cy_000,float64,17526.0,23.06,836.0,"0.0, 54.0, 16.0, 22.0, 12.0, 24.0, 14.0, 26.0, 52.0, 48.0"
20,cz_000,float64,17526.0,23.06,12163.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
21,da_000,float64,17526.0,23.06,290.0,"0.0, 170.0, 52.0, 2.0, 124.0, 154.0, 4.0, 6.0, 50.0, 66.0"
22,db_000,float64,17526.0,23.06,149.0,"0.0, 10.0, 12.0, 14.0, 16.0, 8.0, 18.0, 22.0, 20.0, 24.0"
23,dc_000,float64,17526.0,23.06,39278.0,"0.0, 1974.0, 1796.0, 2144.0, 2052.0, 2014.0, 2724.0, 1664.0, 2112.0, 2092.0"
24,ec_00,float64,12883.0,16.95,36263.0,"0.0, 0.72, 0.7, 0.82, 0.74, 0.64, 0.86, 0.66, 0.8, 0.78"
25,cm_000,float64,12455.0,16.39,2346.0,"0.0, 14.0, 12.0, 16.0, 10.0, 18.0, 8.0, 20.0, 22.0, 24.0"
26,cl_000,float64,12012.0,15.81,1089.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
27,ed_000,float64,12012.0,15.81,4314.0,"0.0, 46.0, 42.0, 48.0, 54.0, 44.0, 40.0, 38.0, 50.0, 56.0"
28,ak_000,float64,5598.0,7.37,194.0,"0.0, 598.0, 596.0, 1196.0, 1198.0, 1794.0, 1194.0, 9994.0, 34852.0, 866.0"
29,ca_000,float64,5562.0,7.32,31826.0,"0.0, 1880.0, 2212.0, 1786.0, 1610.0, 1914.0, 1902.0, 1816.0, 1776.0, 2104.0"
30,df_000,float64,5102.0,6.71,466.0,"0.0, 10.0, 30.0, 60.0, 40.0, 20.0, 130.0, 100.0, 50.0, 70.0"
31,dg_000,float64,5102.0,6.71,1620.0,"0.0, 2.0, 4.0, 8.0, 6.0, 22.0, 10.0, 14.0, 6734.0, 70434.0"
32,dh_000,float64,5102.0,6.71,1195.0,"0.0, 10.0, 30.0, 20.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0"
33,di_000,float64,5100.0,6.71,6670.0,"0.0, 4.0, 2.0, 6.0, 8.0, 12.0, 18.0, 16.0, 10.0, 14.0"
34,dj_000,float64,5101.0,6.71,80.0,"0.0, 10.0, 30.0, 40.0, 60.0, 50.0, 100.0, 80.0, 20.0, 70.0"
35,dk_000,float64,5101.0,6.71,313.0,"0.0, 4.0, 6.0, 8.0, 16.0, 34.0, 12.0, 2.0, 18.0, 98448.0"
36,dl_000,float64,5102.0,6.71,217.0,"0.0, 180.0, 15202350.0, 410.0, 40.0, 60.0, 28979160.0, 50.0, 130.0, 230.0"
37,dm_000,float64,5103.0,6.71,278.0,"0.0, 6.0, 8844466.0, 70588.0, 90.0, 12.0, 28.0, 15070.0, 109784.0, 7842.0"
38,eb_000,float64,5101.0,6.71,33325.0,"0.0, 228290.0, 455490.0, 10611120.0, 752140.0, 925120.0, 7165300.0, 451920.0, 410080.0, 370890.0"
39,ac_000,float64,4261.0,5.61,2229.0,"0.0, 2130706432.0, 2130706434.0, 2.0, 4.0, 8.0, 6.0, 12.0, 10.0, 16.0"
40,bx_000,float64,4123.0,5.42,66034.0,"202.0, 212.0, 200.0, 216.0, 220.0, 214.0, 218.0, 224.0, 208.0, 222.0"
41,cc_000,float64,4120.0,5.42,52485.0,"0.0, 6640.0, 7018.0, 8460.0, 89632.0, 7384.0, 5722.0, 5406.0, 7200.0, 5214.0"
42,ar_000,float64,3487.0,4.59,72.0,"0.0, 2.0, 4.0, 6.0, 8.0, 12.0, 10.0, 14.0, 18.0, 16.0"
43,bc_000,float64,3489.0,4.59,3122.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 16.0, 14.0, 18.0"
44,bd_000,float64,3491.0,4.59,3944.0,"0.0, 4.0, 2.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
45,bz_000,float64,3486.0,4.59,19260.0,"0.0, 6.0, 12.0, 10.0, 4.0, 16.0, 8.0, 18.0, 20.0, 26.0"
46,cp_000,float64,3487.0,4.59,2569.0,"0.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0"
47,de_000,float64,3488.0,4.59,2087.0,"0.0, 50.0, 48.0, 52.0, 40.0, 44.0, 42.0, 38.0, 36.0, 46.0"
48,do_000,float64,3488.0,4.59,23340.0,"0.0, 20.0, 40.0, 60.0, 6.0, 18.0, 12.0, 4.0, 16.0, 42.0"
49,dp_000,float64,3490.0,4.59,12599.0,"0.0, 2.0, 6.0, 4.0, 12.0, 10.0, 8.0, 18.0, 14.0, 16.0"
50,dq_000,float64,3490.0,4.59,9587.0,"0.0, 80.0, 60.0, 100.0, 120.0, 140.0, 72.0, 48.0, 240.0, 160.0"
51,dr_000,float64,3490.0,4.59,7878.0,"0.0, 118.0, 96.0, 6.0, 130.0, 116.0, 138.0, 104.0, 108.0, 132.0"
52,ds_000,float64,3491.0,4.59,30563.0,"0.0, 46.0, 20.0, 40.0, 50.0, 34.0, 30.0, 28.0, 44.0, 32.0"
53,dt_000,float64,3491.0,4.59,17596.0,"0.0, 14.0, 12.0, 16.0, 10.0, 18.0, 22.0, 8.0, 20.0, 24.0"
54,du_000,float64,3490.0,4.59,33450.0,"0.0, 80.0, 40.0, 20.0, 60.0, 100.0, 160.0, 260.0, 360.0, 660.0"
55,dv_000,float64,3490.0,4.59,35505.0,"0.0, 8.0, 4.0, 2.0, 6.0, 10.0, 16.0, 12.0, 20.0, 18.0"
56,dx_000,float64,3487.0,4.59,18079.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 16.0, 14.0, 136.0"
57,dy_000,float64,3488.0,4.59,7342.0,"0.0, 8.0, 12.0, 4.0, 10.0, 14.0, 16.0, 6.0, 18.0, 20.0"
58,dz_000,float64,3485.0,4.59,51.0,"0.0, 2.0, 4.0, 6.0, 8.0, 14.0, 12.0, 10.0, 42.0, 16.0"
59,ea_000,float64,3485.0,4.59,141.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 18.0, 22.0, 14.0"
60,ef_000,float64,3486.0,4.59,30.0,"0.0, 2.0, 4.0, 6.0, 8.0, 12.0, 10.0, 84.0, 166.0, 20.0"
61,eg_000,float64,3485.0,4.59,55.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 26.0, 20.0"
62,ae_000,float64,3190.0,4.20,355.0,"0.0, 2.0, 4.0, 8.0, 6.0, 10.0, 12.0, 14.0, 18.0, 16.0"
63,af_000,float64,3190.0,4.20,458.0,"0.0, 2.0, 4.0, 6.0, 8.0, 12.0, 10.0, 14.0, 18.0, 30.0"
64,ax_000,float64,3189.0,4.20,2415.0,"0.0, 6.0, 4.0, 10.0, 2.0, 8.0, 12.0, 14.0, 22.0, 16.0"
65,be_000,float64,3193.0,4.20,4367.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
66,bf_000,float64,3189.0,4.20,1219.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
67,ce_000,float64,3190.0,4.20,25505.0,"0.0, 246.0, 244.0, 248.0, 204.0, 218.0, 286.0, 236.0, 190.0, 256.0"
68,dd_000,float64,3191.0,4.20,7226.0,"0.0, 56.0, 60.0, 50.0, 74.0, 64.0, 52.0, 58.0, 46.0, 70.0"
69,av_000,float64,3188.0,4.19,4220.0,"0.0, 4.0, 6.0, 2.0, 12.0, 8.0, 10.0, 14.0, 16.0, 18.0"
70,bs_000,float64,928.0,1.22,13714.0,"0.0, 7080.0, 10460.0, 11140.0, 6720.0, 8360.0, 10580.0, 5200.0, 11760.0, 7480.0"
71,cb_000,float64,928.0,1.22,33989.0,"0.0, 19020.0, 19920.0, 16640.0, 18000.0, 16040.0, 19000.0, 19340.0, 16720.0, 17180.0"
72,ba_000,float64,881.0,1.16,53546.0,"0.0, 6280.0, 47074.0, 5148.0, 5890.0, 4020.0, 2914.0, 6564.0, 6466.0, 3564.0"
73,ba_001,float64,881.0,1.16,47871.0,"0.0, 228.0, 248.0, 230.0, 198.0, 192.0, 226.0, 386.0, 308.0, 186.0"
74,ba_002,float64,881.0,1.16,42462.0,"0.0, 78.0, 90.0, 76.0, 112.0, 124.0, 116.0, 102.0, 122.0, 84.0"
75,ba_003,float64,881.0,1.16,38700.0,"0.0, 58.0, 62.0, 56.0, 54.0, 70.0, 60.0, 68.0, 64.0, 72.0"
76,ba_004,float64,881.0,1.16,36076.0,"0.0, 32.0, 44.0, 24.0, 42.0, 36.0, 34.0, 48.0, 30.0, 28.0"
77,ba_005,float64,881.0,1.16,34937.0,"0.0, 22.0, 26.0, 28.0, 20.0, 34.0, 30.0, 32.0, 18.0, 24.0"
78,ba_006,float64,881.0,1.16,34658.0,"0.0, 8.0, 2.0, 14.0, 6.0, 12.0, 10.0, 76.0, 18.0, 70.0"
79,ba_007,float64,881.0,1.16,29876.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 16.0, 14.0, 20.0"
80,ba_008,float64,881.0,1.16,13925.0,"0.0, 2.0, 4.0, 8.0, 6.0, 10.0, 14.0, 12.0, 18.0, 22.0"
81,ba_009,float64,881.0,1.16,8088.0,"0.0, 2.0, 4.0, 6.0, 10.0, 8.0, 12.0, 14.0, 20.0, 16.0"
82,bu_000,float64,881.0,1.16,59653.0,"0.0, 131080.0, 18258.0, 32252.0, 2537146.0, 20320.0, 20344.0, 27080.0, 25722.0, 2760680.0"
83,bv_000,float64,881.0,1.16,59649.0,"0.0, 131080.0, 18258.0, 2537146.0, 32252.0, 16918.0, 19544.0, 20800.0, 21296.0, 20344.0"
84,cn_000,float64,881.0,1.16,1873.0,"0.0, 2.0, 10.0, 14.0, 492.0, 198.0, 8.0, 30.0, 106.0, 58.0"
85,cn_001,float64,881.0,1.16,6456.0,"0.0, 2.0, 4.0, 10.0, 14.0, 6.0, 8.0, 20.0, 22.0, 30.0"
86,cn_002,float64,881.0,1.16,17134.0,"0.0, 6.0, 4.0, 12.0, 10.0, 32.0, 8.0, 2.0, 16.0, 22.0"
87,cn_003,float64,881.0,1.16,39883.0,"0.0, 4.0, 2.0, 24.0, 10.0, 36.0, 12.0, 6.0, 2480.0, 276.0"
88,cn_004,float64,881.0,1.16,50096.0,"0.0, 1494.0, 2016.0, 1284.0, 1664.0, 1378.0, 1530.0, 1392.0, 1338.0, 1660.0"
89,cn_005,float64,881.0,1.16,46037.0,"0.0, 998.0, 826.0, 890.0, 502.0, 1002.0, 924.0, 338.0, 380.0, 950.0"
90,cn_006,float64,881.0,1.16,38608.0,"0.0, 10.0, 4.0, 14.0, 6.0, 8.0, 16.0, 18.0, 20.0, 12.0"
91,cn_007,float64,881.0,1.16,25025.0,"0.0, 6.0, 4.0, 8.0, 10.0, 14.0, 12.0, 16.0, 18.0, 2.0"
92,cn_008,float64,881.0,1.16,11139.0,"0.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 2.0, 16.0, 18.0"
93,cn_009,float64,881.0,1.16,3430.0,"0.0, 10.0, 8.0, 12.0, 4.0, 6.0, 14.0, 16.0, 18.0, 20.0"
94,cq_000,float64,881.0,1.16,59651.0,"0.0, 131080.0, 18258.0, 2537146.0, 32252.0, 20800.0, 2760680.0, 20320.0, 3089264.0, 16918.0"
95,dn_000,float64,881.0,1.16,23935.0,"176.0, 158.0, 148.0, 162.0, 152.0, 140.0, 170.0, 154.0, 142.0, 156.0"
96,ay_000,float64,863.0,1.14,575.0,"0.0, 2.0, 180266.0, 36276.0, 79434.0, 35618.0, 1522468.0, 8.0, 33304.0, 31414.0"
97,ay_001,float64,863.0,1.14,1110.0,"0.0, 664.0, 1422.0, 2676.0, 480.0, 2974.0, 1358.0, 13296.0, 17626.0, 14894.0"
98,ay_002,float64,863.0,1.14,1194.0,"0.0, 8284.0, 8852.0, 4220.0, 1372508.0, 21788.0, 9720.0, 9060.0, 5466.0, 4354.0"
99,ay_003,float64,863.0,1.14,1249.0,"0.0, 17278.0, 13998.0, 5388.0, 29174.0, 15680.0, 1314.0, 1058754.0, 7462.0, 1336838.0"
100,ay_004,float64,863.0,1.14,2126.0,"0.0, 2.0, 196.0, 1352.0, 6956.0, 32.0, 7550.0, 936.0, 136.0, 9494.0"
101,ay_005,float64,863.0,1.14,22880.0,"0.0, 2.0, 54.0, 86.0, 96.0, 126.0, 48.0, 186.0, 1446.0, 8136.0"
102,ay_006,float64,863.0,1.14,41538.0,"0.0, 52858.0, 2.0, 764946.0, 880874.0, 169962.0, 8236.0, 168.0, 1445482.0, 40990.0"
103,ay_007,float64,863.0,1.14,46022.0,"0.0, 2.0, 4.0, 830.0, 980.0, 986.0, 286.0, 1018.0, 938.0, 446.0"
104,ay_008,float64,863.0,1.14,44763.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 1108.0, 12.0, 1258.0, 1030.0"
105,ay_009,float64,863.0,1.14,568.0,"0.0, 2.0, 4.0, 6.0, 55132.0, 36.0, 14.0, 68.0, 460.0, 10.0"
106,az_000,float64,863.0,1.14,10290.0,"0.0, 54.0, 52.0, 70.0, 58.0, 60.0, 64.0, 72.0, 74.0, 50.0"
107,az_001,float64,863.0,1.14,8287.0,"0.0, 10.0, 12.0, 6.0, 14.0, 8.0, 18.0, 16.0, 4.0, 20.0"
108,az_002,float64,863.0,1.14,10236.0,"0.0, 26.0, 18.0, 14.0, 24.0, 20.0, 22.0, 28.0, 16.0, 12.0"
109,az_003,float64,863.0,1.14,24771.0,"0.0, 24.0, 16.0, 26.0, 20.0, 12.0, 14.0, 18.0, 28.0, 22.0"
110,az_004,float64,863.0,1.14,40463.0,"0.0, 12.0, 8.0, 20.0, 16.0, 18.0, 6.0, 14.0, 24.0, 10.0"
111,az_005,float64,863.0,1.14,53355.0,"0.0, 140.0, 168.0, 194.0, 250.0, 114.0, 180.0, 306.0, 274.0, 196.0"
112,az_006,float64,863.0,1.14,14147.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
113,az_007,float64,863.0,1.14,4563.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
114,az_008,float64,863.0,1.14,1453.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 18.0, 16.0"
115,az_009,float64,863.0,1.14,386.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
116,ee_000,float64,863.0,1.14,49556.0,"0.0, 3924.0, 3590.0, 4468.0, 4116.0, 4742.0, 4648.0, 4098.0, 5366.0, 4644.0"
117,ee_001,float64,863.0,1.14,45032.0,"0.0, 1494.0, 1120.0, 1198.0, 1326.0, 1454.0, 1312.0, 1298.0, 1536.0, 1276.0"
118,ee_002,float64,863.0,1.14,40696.0,"0.0, 32.0, 34.0, 30.0, 42.0, 28.0, 44.0, 40.0, 36.0, 38.0"
119,ee_003,float64,863.0,1.14,37291.0,"0.0, 10.0, 8.0, 12.0, 14.0, 16.0, 6.0, 18.0, 20.0, 22.0"
120,ee_004,float64,863.0,1.14,41657.0,"0.0, 20.0, 24.0, 16.0, 28.0, 26.0, 30.0, 18.0, 22.0, 32.0"
121,ee_005,float64,863.0,1.14,43051.0,"0.0, 28.0, 22.0, 20.0, 18.0, 24.0, 26.0, 16.0, 30.0, 14.0"
122,ee_006,float64,863.0,1.14,37560.0,"0.0, 4.0, 2.0, 8.0, 22.0, 14.0, 6.0, 10.0, 12.0, 16.0"
123,ee_007,float64,863.0,1.14,35859.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 36.0, 14.0, 38.0"
124,ee_008,float64,863.0,1.14,28412.0,"0.0, 2.0, 4.0, 10.0, 6.0, 8.0, 12.0, 20.0, 14.0, 16.0"
125,ee_009,float64,863.0,1.14,10947.0,"0.0, 2.0, 10.0, 8.0, 6.0, 4.0, 12.0, 14.0, 16.0, 20.0"
126,ag_000,float64,860.0,1.13,198.0,"0.0, 2.0, 8.0, 16186.0, 4.0, 11912.0, 28.0, 206.0, 776.0, 17706.0"
127,ag_001,float64,860.0,1.13,795.0,"0.0, 2.0, 12.0, 15166.0, 530916.0, 26.0, 1768.0, 50.0, 5734.0, 102.0"
128,ag_002,float64,860.0,1.13,2952.0,"0.0, 16.0, 12.0, 342.0, 6.0, 82.0, 2.0, 80.0, 54.0, 94.0"
129,ag_003,float64,860.0,1.13,9383.0,"0.0, 30.0, 22.0, 2.0, 16.0, 26.0, 40.0, 140.0, 24.0, 4.0"
130,ag_004,float64,860.0,1.13,26854.0,"0.0, 6.0, 2.0, 4.0, 8.0, 10.0, 12.0, 88.0, 94.0, 14.0"
131,ag_005,float64,860.0,1.13,48327.0,"0.0, 554.0, 1700.0, 2016.0, 2332.0, 3576.0, 3024.0, 2920.0, 1826.0, 4484.0"
132,ag_006,float64,860.0,1.13,48480.0,"0.0, 1002.0, 1046.0, 1068.0, 1028.0, 2138.0, 1784.0, 2084.0, 1098.0, 2188.0"
133,ag_007,float64,860.0,1.13,38289.0,"0.0, 4.0, 18.0, 12.0, 10.0, 68.0, 16.0, 26.0, 42.0, 80.0"
134,ag_008,float64,860.0,1.13,21563.0,"0.0, 4.0, 82.0, 12.0, 6.0, 18.0, 46.0, 30.0, 14.0, 38.0"
135,ag_009,float64,860.0,1.13,5923.0,"0.0, 4.0, 2.0, 6.0, 8.0, 12.0, 10.0, 72.0, 18.0, 48.0"
136,cd_000,float64,861.0,1.13,1.0,1209600.0
137,cs_000,float64,858.0,1.13,10172.0,"0.0, 1132.0, 1148.0, 1144.0, 1186.0, 1172.0, 1180.0, 1134.0, 1118.0, 1120.0"
138,cs_001,float64,858.0,1.13,3714.0,"0.0, 12.0, 14.0, 10.0, 16.0, 8.0, 18.0, 20.0, 22.0, 6.0"
139,cs_002,float64,858.0,1.13,33134.0,"0.0, 12.0, 18.0, 16.0, 14.0, 20.0, 10.0, 22.0, 24.0, 8.0"
140,cs_003,float64,858.0,1.13,41631.0,"0.0, 8.0, 6.0, 10.0, 12.0, 14.0, 4.0, 16.0, 18.0, 2.0"
141,cs_004,float64,858.0,1.13,40803.0,"0.0, 4.0, 2.0, 6.0, 10.0, 8.0, 12.0, 14.0, 16.0, 18.0"
142,cs_005,float64,858.0,1.13,50808.0,"0.0, 2.0, 764.0, 726.0, 1070.0, 1024.0, 988.0, 1132.0, 1074.0, 808.0"
143,cs_006,float64,858.0,1.13,48557.0,"0.0, 310.0, 322.0, 356.0, 276.0, 62.0, 2078.0, 740.0, 160.0, 320.0"
144,cs_007,float64,858.0,1.13,18939.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 14.0, 12.0, 18.0, 22.0"
145,cs_008,float64,858.0,1.13,820.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 20.0"
146,cs_009,float64,858.0,1.13,64.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 16.0, 14.0, 18.0"
147,ah_000,float64,820.0,1.08,52008.0,"0.0, 1868.0, 1436.0, 2232.0, 1950.0, 2196.0, 2228.0, 1974.0, 2990.0, 2608.0"
148,bb_000,float64,820.0,1.08,59705.0,"0.0, 131080.0, 18258.0, 32252.0, 2537146.0, 20320.0, 20800.0, 27080.0, 2760680.0, 14342.0"
149,al_000,float64,811.0,1.07,10456.0,"0.0, 54.0, 158.0, 178.0, 130.0, 176.0, 148.0, 136.0, 140.0, 186.0"
150,an_000,float64,811.0,1.07,57987.0,"0.0, 11742.0, 99428.0, 8464.0, 13562.0, 8436.0, 10542.0, 12838.0, 9060.0, 16230962.0"
151,ap_000,float64,811.0,1.07,53131.0,"0.0, 31576.0, 8080.0, 13100.0, 6732.0, 11362.0, 7456.0, 15486.0, 10626.0, 10266.0"
152,bg_000,float64,811.0,1.07,52012.0,"0.0, 1868.0, 1436.0, 2228.0, 2548.0, 1950.0, 2232.0, 2196.0, 1974.0, 2608.0"
153,bh_000,float64,811.0,1.07,29068.0,"0.0, 134.0, 138.0, 140.0, 152.0, 132.0, 136.0, 150.0, 180.0, 128.0"
154,ai_000,float64,792.0,1.04,4804.0,"0.0, 864.0, 1288.0, 3618.0, 942.0, 1166.0, 1444.0, 1200.0, 1616.0, 4466.0"
155,aj_000,float64,792.0,1.04,1031.0,"0.0, 58.0, 54.0, 56.0, 60.0, 52.0, 64.0, 62.0, 34.0, 50.0"
156,am_0,float64,792.0,1.04,12214.0,"0.0, 1196.0, 1184.0, 1192.0, 240.0, 230.0, 1194.0, 236.0, 238.0, 232.0"
157,as_000,float64,792.0,1.04,30.0,"0.0, 13752.0, 10696.0, 1150508.0, 790.0, 1246190.0, 320346.0, 1156.0, 63712.0, 489122.0"
158,at_000,float64,792.0,1.04,4025.0,"0.0, 756.0, 1014.0, 686.0, 1034.0, 410.0, 1658.0, 792.0, 364.0, 464.0"
159,au_000,float64,792.0,1.04,71.0,"0.0, 249166.0, 1324.0, 37936.0, 5444.0, 96986.0, 2376.0, 205016.0, 20738.0, 24242.0"
160,ao_000,float64,751.0,0.99,57386.0,"0.0, 5896.0, 87122.0, 11286.0, 9890.0, 10558.0, 6622.0, 7922.0, 9574.0, 7494.0"
161,aq_000,float64,751.0,0.99,41140.0,"0.0, 398.0, 336.0, 500.0, 404.0, 364.0, 544.0, 324.0, 600.0, 288.0"
162,bi_000,float64,751.0,0.99,49750.0,"0.0, 2.0, 7640.0, 8112.0, 7308.0, 5534.0, 11342.0, 7364.0, 11878.0, 9936.0"
163,bj_000,float64,751.0,0.99,45121.0,"0.0, 1856.0, 2044.0, 2458.0, 1578.0, 1456.0, 3404.0, 1398.0, 1896.0, 2184.0"
164,by_000,float64,580.0,0.76,25856.0,"0.0, 26.0, 24.0, 23.0, 25.0, 27.0, 22.0, 21.0, 29.0, 28.0"
165,ci_000,float64,424.0,0.56,55003.0,"0.0, 1692.48, 1830.72, 2184.0, 1402.56, 1580.16, 1618.56, 1517.76, 1612.8, 1449.6"
166,cj_000,float64,424.0,0.56,9091.0,"0.0, 3.84, 2.88, 6.72, 5.76, 4.8, 11.52, 12.48, 8.64, 7.68"
167,ck_000,float64,424.0,0.56,53627.0,"0.0, 21732.48, 22427.52, 2170.56, 251350.08, 2369.28, 3284.16, 3405.12, 3518.4, 2199.36"
168,bt_000,float64,195.0,0.26,54523.0,"0.0, 8.4, 8.65, 11.67, 8.91, 7.66, 8.3, 13.94, 7.44, 8.25"
169,aa_000,int64,0.0,0.00,25211.0,"8, 10, 12, 14, 6, 16, 18, 28, 0, 4"
170,AirPressureSystemFailure,object,0.0,0.00,2.0,"neg, pos"

In [7]:
# Numeric Feature Statistics
numeric_stats

          count          mean           std        min           max
aa_000  76000.0  6.115976e+04  2.647366e+05        0.0  4.294967e+07
ab_000  17308.0  7.255604e-01  3.311913e+00        0.0  2.040000e+02
ac_000  71739.0  3.564398e+08  7.952530e+08        0.0  2.130707e+09
ad_000  57158.0  1.506300e+05  3.590593e+07        0.0  8.584298e+09
ae_000  72810.0  6.736959e+00  1.534465e+02        0.0  2.105000e+04
af_000  72810.0  1.083631e+01  2.015949e+02        0.0  2.007000e+04
ag_000  75140.0  2.004306e+02  1.843612e+04        0.0  3.376892e+06
ag_001  75140.0  1.204761e+03  5.099091e+04        0.0  1.047252e+07
ag_002  75140.0  9.697328e+03  1.718996e+05        0.0  1.914916e+07
ag_003  75140.0  9.364902e+04  8.244157e+05        0.0  7.305747e+07
ag_004  75140.0  4.483426e+05  2.468736e+06        0.0  2.288306e+08
ag_005  75140.0  1.122573e+06  3.346554e+06        0.0  1.791880e+08
ag_006  75140.0  1.666272e+06  3.942420e+06        0.0  9.402067e+07
ag_007  75140.0  5.007954e+05  1.416524e+06        0.0  6.334675e+07
ag_008  75140.0  3.564389e+04  2.249410e+05        0.0  1.770252e+07
ag_009  75140.0  5.255755e+03  1.700269e+05        0.0  2.519851e+07
ah_000  75180.0  1.832622e+06  4.266590e+06        0.0  8.207358e+07
ai_000  75208.0  9.597229e+03  1.785420e+05        0.0  1.777009e+07
aj_000  75208.0  1.167200e+03  5.062269e+04        0.0  5.629340e+06
ak_000  70402.0  9.689417e+02  7.915197e+04        0.0  1.093059e+07
al_000  75189.0  6.160588e+04  5.643716e+05        0.0  3.777930e+07
am_0    75208.0  9.724470e+04  8.863673e+05        0.0  5.590351e+07
an_000  75189.0  3.503077e+06  7.939203e+06        0.0  1.498686e+08
ao_000  75249.0  3.039594e+06  6.952902e+06        0.0  1.427517e+08
ap_000  75189.0  1.019361e+06  3.162551e+06        0.0  1.156131e+08
aq_000  75249.0  4.491939e+05  1.288142e+06        0.0  3.455877e+07
ar_000  72513.0  4.928771e-01  5.333102e+00        0.0  3.500000e+02
as_000  75208.0  2.473336e+02  2.831496e+04        0.0  6.383704e+06
at_000  75208.0  5.196723e+03  1.211295e+05        0.0  1.065435e+07
au_000  75208.0  2.999350e+02  2.595569e+04        0.0  5.711474e+06
av_000  72812.0  1.145837e+03  6.708410e+03        0.0  7.944580e+05
ax_000  72811.0  3.770191e+02  1.486451e+03        0.0  1.166520e+05
ay_000  75137.0  1.495621e+04  6.152499e+05        0.0  7.404109e+07
ay_001  75137.0  1.133445e+04  5.614030e+05        0.0  8.052538e+07
ay_002  75137.0  1.135212e+04  4.377592e+05        0.0  3.023117e+07
ay_003  75137.0  7.321961e+03  2.086193e+05        0.0  1.394517e+07
ay_004  75137.0  1.016125e+04  3.376516e+05        0.0  4.002870e+07
ay_005  75137.0  1.066613e+05  1.288238e+06        0.0  1.249489e+08
ay_006  75137.0  1.081914e+06  3.288182e+06        0.0  1.276803e+08
ay_007  75137.0  1.556827e+06  5.088498e+06        0.0  4.896782e+08
ay_008  75137.0  1.078965e+06  4.279569e+06        0.0  3.268368e+08
ay_009  75137.0  1.158223e+03  9.023099e+04        0.0  1.882466e+07
az_000  75137.0  7.899449e+03  7.166003e+04        0.0  1.012462e+07
az_001  75137.0  4.486525e+03  3.327746e+04        0.0  4.530258e+06
az_002  75137.0  8.046204e+03  9.751545e+04        0.0  1.421766e+07
az_003  75137.0  8.772173e+04  6.674653e+05        0.0  4.558424e+07
az_004  75137.0  1.488475e+06  4.248206e+06        0.0  1.320373e+08
az_005  75137.0  2.162875e+06  6.670762e+06        0.0  4.810465e+08
az_006  75137.0  1.026049e+05  8.982292e+05        0.0  6.458914e+07
az_007  75137.0  1.788403e+04  2.766703e+05        0.0  3.915822e+07
az_008  75137.0  6.341621e+02  1.429607e+04        0.0  1.947884e+06
az_009  75137.0  3.760768e+01  2.950180e+03        0.0  6.661480e+05
ba_000  75119.0  1.414577e+06  3.825417e+06        0.0  2.328717e+08
ba_001  75119.0  9.041115e+05  2.407672e+06        0.0  1.420004e+08
ba_002  75119.0  4.179982e+05  1.213790e+06        0.0  5.580739e+07
ba_003  75119.0  2.775360e+05  7.620962e+05        0.0  3.693142e+07
ba_004  75119.0  2.076826e+05  5.517862e+05        0.0  2.515856e+07
ba_005  75119.0  1.909976e+05  5.193505e+05        0.0  1.924055e+07
ba_006  75119.0  2.115967e+05  6.378501e+05        0.0  1.899766e+07
ba_007  75119.0  1.867980e+05  5.302447e+05        0.0  1.542726e+07
ba_008  75119.0  3.627100e+04  2.446216e+05        0.0  3.126598e+07
ba_009  75119.0  3.712154e+04  3.556871e+05        0.0  4.370641e+07
bb_000  75180.0  4.584731e+06  1.110908e+07        0.0  2.349818e+08
bc_000  72511.0  5.674798e+02  3.890956e+03        0.0  3.969520e+05
bd_000  72509.0  9.255670e+02  4.819315e+03        0.0  3.064520e+05
be_000  72807.0  1.382803e+03  8.978983e+03        0.0  8.105680e+05
bf_000  72811.0  7.636291e+01  5.502164e+02        0.0  5.105000e+04
bg_000  75189.0  1.832519e+06  4.262272e+06        0.0  8.207358e+07
bh_000  75189.0  5.877788e+04  1.551209e+05        0.0  3.868624e+06
bi_000  75249.0  4.969615e+05  1.503636e+06        0.0  5.403607e+07
bj_000  75249.0  5.203771e+05  1.872042e+06        0.0  6.437019e+07
bk_000  46872.0  2.803808e+05  2.606883e+05        0.0  1.310700e+06
bl_000  41497.0  3.211696e+05  3.183189e+05        0.0  1.310700e+06
bm_000  25905.0  3.998161e+05  4.069775e+05        0.0  1.310700e+06
bn_000  20278.0  4.623655e+05  4.633323e+05        0.0  1.310700e+06
bo_000  17291.0  5.110801e+05  4.960001e+05        0.0  1.310700e+06
bp_000  15539.0  5.487090e+05  5.180590e+05        0.0  1.310700e+06
bq_000  14297.0  5.796985e+05  5.349894e+05        0.0  1.310700e+06
br_000  13607.0  6.012993e+05  5.455199e+05        0.0  1.310700e+06
bs_000  75072.0  8.063566e+04  8.484203e+04        0.0  1.037240e+06
bt_000  75805.0  6.123980e+04  2.649841e+05        0.0  4.294967e+07
bu_000  75119.0  4.573524e+06  1.108062e+07        0.0  2.349818e+08
bv_000  75119.0  4.573525e+06  1.108062e+07        0.0  2.349818e+08
bx_000  71877.0  4.152868e+06  1.062524e+07      170.0  5.318356e+08
by_000  75420.0  2.221936e+04  5.448130e+04        0.0  1.002003e+06
bz_000  72514.0  1.034416e+05  6.412725e+05        0.0  4.054259e+07
ca_000  70438.0  3.932377e+04  3.680975e+04        0.0  1.209560e+05
cb_000  75072.0  4.068323e+05  3.696570e+05        0.0  1.209520e+06
cc_000  71880.0  3.844510e+06  9.900743e+06        0.0  5.062058e+08
cd_000  75139.0  1.209600e+06  0.000000e+00  1209600.0  1.209600e+06
ce_000  72810.0  6.427970e+04  1.426797e+05        0.0  4.908098e+06
cf_000  57158.0  1.502312e+05  3.590594e+07        0.0  8.584298e+09
cg_000  57158.0  9.198055e+01  3.724506e+02        0.0  2.140000e+04
ch_000  57158.0  4.548795e-04  3.015904e-02        0.0  2.000000e+00
ci_000  75576.0  3.518084e+06  8.446261e+06        0.0  1.409861e+08
cj_000  75576.0  1.058583e+05  1.188267e+06        0.0  7.449868e+07
ck_000  75576.0  7.235052e+05  2.208255e+06        0.0  5.542867e+07
cl_000  63988.0  3.601250e+02  4.774181e+03        0.0  1.305600e+05
cm_000  63545.0  3.463896e+02  1.780234e+03        0.0  9.812400e+04
cn_000  75119.0  2.678814e+03  7.537833e+04        0.0  1.256709e+07
cn_001  75119.0  2.404110e+04  3.052824e+05        0.0  4.531786e+07
cn_002  75119.0  1.660813e+05  1.129849e+06        0.0  8.397790e+07
cn_003  75119.0  5.418796e+05  2.305079e+06        0.0  1.603483e+08
cn_004  75119.0  1.298715e+06  3.449580e+06        0.0  1.698693e+08
cn_005  75119.0  1.348580e+06  3.171220e+06        0.0  1.178158e+08
cn_006  75119.0  4.103622e+05  1.257944e+06        0.0  7.208041e+07
cn_007  75119.0  6.472584e+04  3.974845e+05        0.0  3.314373e+07
cn_008  75119.0  1.965129e+04  1.934498e+05        0.0  9.628690e+06
cn_009  75119.0  8.018107e+03  2.497028e+05        0.0  3.639837e+07
co_000  57158.0  1.505174e+05  3.590594e+07        0.0  8.584298e+09
cp_000  72513.0  5.525232e+02  7.307657e+03        0.0  4.963600e+05
cq_000  75119.0  4.573525e+06  1.108062e+07        0.0  2.349818e+08
cr_000  17308.0  3.978634e+01  1.039717e+03        0.0  5.745000e+04
cs_000  75142.0  5.522760e+03  1.095533e+04        0.0  9.249960e+05
cs_001  75142.0  7.920520e+02  2.766431e+03        0.0  4.388060e+05
cs_002  75142.0  2.430570e+05  1.252976e+06        0.0  6.557294e+07
cs_003  75142.0  3.602479e+05  1.151020e+06        0.0  6.173720e+07
cs_004  75142.0  4.529609e+05  2.163141e+06        0.0  1.524554e+08
cs_005  75142.0  2.257808e+06  5.684214e+06        0.0  3.791421e+08
cs_006  75142.0  5.471896e+05  1.155262e+06        0.0  7.374197e+07
cs_007  75142.0  1.472408e+04  7.303380e+04        0.0  1.288422e+07
cs_008  75142.0  2.475639e+02  1.424186e+04        0.0  2.826620e+06
cs_009  75142.0  1.024872e+03  1.984342e+05        0.0  4.490299e+07
ct_000  58474.0  7.499852e+02  5.258342e+03        0.0  9.103660e+05
cu_000  58474.0  1.217781e+03  7.386238e+03        0.0  7.336880e+05
cv_000  58474.0  1.930347e+06  3.631624e+06        0.0  8.161051e+07
cx_000  58474.0  3.535989e+05  1.510434e+06        0.0  4.410549e+07
cy_000  58474.0  2.550845e+02  8.144390e+03        0.0  9.314720e+05
cz_000  58474.0  1.887897e+04  2.316695e+05        0.0  1.915653e+07
da_000  58474.0  7.476827e+00  2.148551e+02        0.0  2.245800e+04
db_000  58474.0  1.326850e+01  6.607356e+01        0.0  9.636000e+03
dc_000  58474.0  2.202093e+06  4.070384e+06        0.0  1.207595e+08
dd_000  72809.0  3.177416e+03  9.859060e+03        0.0  4.451420e+05
de_000  72512.0  3.749164e+02  1.623047e+03        0.0  1.761760e+05
df_000  70898.0  6.999671e+03  8.071134e+05        0.0  2.035008e+08
dg_000  70898.0  7.034914e+03  2.525721e+05        0.0  2.706429e+07
dh_000  70898.0  4.302818e+03  5.018612e+05        0.0  1.247009e+08
di_000  70900.0  3.688729e+04  4.293744e+05        0.0  2.298742e+07
dj_000  70899.0  3.186138e+01  4.028722e+03        0.0  7.267500e+05
dk_000  70899.0  1.659336e+03  6.273772e+04        0.0  5.483574e+06
dl_000  70898.0  2.887204e+04  1.119686e+06        0.0  1.038581e+08
dm_000  70897.0  7.841488e+03  2.805190e+05        0.0  2.369792e+07
dn_000  75119.0  3.424801e+04  9.904364e+04        0.0  2.924584e+06
do_000  72512.0  2.880935e+04  6.413361e+04        0.0  2.472198e+06
dp_000  72510.0  7.029668e+03  1.446098e+04        0.0  5.353160e+05
dq_000  72510.0  4.355312e+06  9.445991e+07        0.0  6.351873e+09
dr_000  72510.0  2.031181e+05  1.369545e+06        0.0  5.013766e+07
ds_000  72509.0  9.044653e+04  2.120491e+05        0.0  4.970962e+06
dt_000  72509.0  1.552771e+04  3.441902e+04        0.0  8.552600e+05
du_000  72510.0  4.120840e+06  1.179671e+07        0.0  4.602076e+08
dv_000  72510.0  6.044064e+05  2.136171e+06        0.0  1.270345e+08
dx_000  72513.0  7.894708e+05  4.126273e+06        0.0  1.142884e+08
dy_000  72512.0  7.840397e+03  6.033645e+04        0.0  3.793022e+06
dz_000  72515.0  2.063021e-01  1.040142e+01        0.0  1.414000e+03
ea_000  72515.0  1.535489e+00  5.152435e+01        0.0  8.506000e+03
eb_000  70899.0  9.924878e+06  4.667332e+07        0.0  4.496966e+09
ec_00   63117.0  1.358262e+03  3.545043e+03        0.0  1.060202e+05
ed_000  63988.0  1.464653e+03  3.592178e+03        0.0  8.838800e+04
ee_000  75137.0  7.445035e+05  2.522756e+06        0.0  1.630857e+08
ee_001  75137.0  7.883109e+05  2.564973e+06        0.0  9.822438e+07
ee_002  75137.0  4.495763e+05  1.177226e+06        0.0  7.793393e+07
ee_003  75137.0  2.132460e+05  5.518865e+05        0.0  3.775839e+07
ee_004  75137.0  4.506478e+05  1.189909e+06        0.0  9.715238e+07
ee_005  75137.0  4.006204e+05  1.151635e+06        0.0  5.743524e+07
ee_006  75137.0  3.378689e+05  1.097909e+06        0.0  4.215944e+07
ee_007  75137.0  3.475611e+05  1.707593e+06        0.0  1.195801e+08
ee_008  75137.0  1.398968e+05  4.692327e+05        0.0  1.926740e+07
ee_009  75137.0  8.424984e+03  4.875440e+04        0.0  4.570398e+06
ef_000  72514.0  8.519734e-02  4.179600e+00        0.0  4.820000e+02
eg_000  72515.0  2.190443e-01  1.023705e+01        0.0  1.720000e+03

In [8]:
# Categorical Feature Statistics
cat_stats

                              value  count    pct
column                   rank
AirPressureSystemFailure 1      neg  74625  98.19
                         2      pos   1375   1.81

In [9]:
# Target Distribution
target_df

                          count    pct
AirPressureSystemFailure
neg                       74625  98.19
pos                        1375   1.81

## Task Curation

In [10]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=3, n_splits=3, test_size=None

In [11]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

# -- For IID Data
splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [12]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019ce752-57f8-7535-90f8-ce435bb1027f
bbb6acbb2087cbd107d542322409c797b5ea869fb5200c067d6f60ce306fee8c