### Dataset and Task Metadata

In [9]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="SRBCT",
    dataset_year="2001",
    domain_str="medical & healthcare",
    # Data Source
    dataset_source="OpenML",
    original_dataset_source_download_link="https://www.openml.org/d/45101",
    download_description="""
We download the data from OpenML to a predefined folder.

mkdir -p local-data-warehouse/SRBCT/ && wget -P local-data-warehouse/SRBCT/ https://api.openml.org/data/download/22112162/dataset 
""",
    # References
    academic_reference_bibtex="""@article{Khan2001ClassificationAD,
  title={Classification and diagnostic prediction of cancers using gene expression profiling and artificial neural networks},
  author={Javed Khan and Jun S. Wei and Markus Ringnér and Lao H. Saal and Marc Ladanyi and Frank Westermann and Frank Berthold and Manfred Schwab and Cristina R. Antonescu and Carsten Peterson and Paul S. Meltzer},
  journal={Nature Medicine},
  year={2001},
  volume={7},
  number={6},
  pages={673-679},
  doi={10.1038/89044},
  url={https://doi.org/10.1038/89044}
}
""",
    academic_reference_bibtex_key="Khan2001ClassificationAD",
    license="Public Domain",
    data_tags=["IID"],
    curation_comments="""
        - We use the OpenML version of the dataset (training and test excluding 5 non-SRBCT test samples) as the original reference does not mention any official data repostitory. 
        - We use target feature encoding as in the plsgenomics R package (https://rdrr.io/cran/plsgenomics/man/SRBCT.html).
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="CancerType",
    problem_type="multiclass_classification",
    objective_metric_name="log_loss",
    stratify_on="CancerType",
)

## Preprocessing

In [10]:
import pandas as pd
import arff

with open(dataset_mold.path/"dataset") as f:
    data = arff.load(f)
df = pd.DataFrame(data["data"], columns=[x[0] for x in data["attributes"]])

target_feature = "CancerType"
df = df.rename(columns={"CLASS": target_feature})
df[target_feature] = df[target_feature].map({"1": "EWS", "2": "BL", "3": "NB", "4": "RMS"}).astype("category")

In [11]:
df.columns

Index(['gene1', 'gene2', 'gene3', 'gene4', 'gene5', 'gene6', 'gene7', 'gene8',
       'gene9', 'gene10',
       ...
       'gene2300', 'gene2301', 'gene2302', 'gene2303', 'gene2304', 'gene2305',
       'gene2306', 'gene2307', 'gene2308', 'CancerType'],
      dtype='object', length=2309)

## Data Checks

In [12]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 83
Columns: 2309
Use sampling: False (sample size: 83)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['gene1154', 'gene1955', 'gene1177', 'gene1956', 'gene1175', 'gene1174', 'gene1173', 'gene1957', 'gene1958', 'gene1170']
Rows remaining as candidates after top-10 filter: 0 (of 83)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [13]:
# Sample Rows
df_head

,gene1,gene2,gene3,gene4,gene5,gene6,gene7,gene8,gene9,gene10,gene11,gene12,gene13,gene14,gene15,gene16,gene17,gene18,gene19,gene20,gene21,gene22,gene23,gene24,gene25,gene26,gene27,gene28,gene29,gene30,gene31,gene32,gene33,gene34,gene35,gene36,gene37,gene38,gene39,gene40,gene41,gene42,gene43,gene44,gene45,gene46,gene47,gene48,gene49,gene50,gene51,gene52,gene53,gene54,gene55,gene56,gene57,gene58,gene59,gene60,gene61,gene62,gene63,gene64,gene65,gene66,gene67,gene68,gene69,gene70,gene71,gene72,gene73,gene74,gene75,gene76,gene77,gene78,gene79,gene80,gene81,gene82,gene83,gene84,gene85,gene86,gene87,gene88,gene89,gene90,gene91,gene92,gene93,gene94,gene95,gene96,gene97,gene98,gene99,gene100,gene101,gene102,gene103,gene104,gene105,gene106,gene107,gene108,gene109,gene110,gene111,gene112,gene113,gene114,gene115,gene116,gene117,gene118,gene119,gene120,gene121,gene122,gene123,gene124,gene125,gene126,gene127,gene128,gene129,gene130,gene131,gene132,gene133,gene134,gene135,gene136,gene137,gene138,gene139,gene140,gene141,gene142,gene143,gene144,gene145,gene146,gene147,gene148,gene149,gene150,gene151,gene152,gene153,gene154,gene155,gene156,gene157,gene158,gene159,gene160,gene161,gene162,gene163,gene164,gene165,gene166,gene167,gene168,gene169,gene170,gene171,gene172,gene173,gene174,gene175,gene176,gene177,gene178,gene179,gene180,gene181,gene182,gene183,gene184,gene185,gene186,gene187,gene188,gene189,gene190,gene191,gene192,gene193,gene194,gene195,gene196,gene197,gene198,gene199,gene200,gene201,gene202,gene203,gene204,gene205,gene206,gene207,gene208,gene209,gene210,gene211,gene212,gene213,gene214,gene215,gene216,gene217,gene218,gene219,gene220,gene221,gene222,gene223,gene224,gene225,gene226,gene227,gene228,gene229,gene230,gene231,gene232,gene233,gene234,gene235,gene236,gene237,gene238,gene239,gene240,gene241,gene242,gene243,gene244,gene245,gene246,gene247,gene248,gene249,gene250,gene251,gene252,gene253,gene254,gene255,gene256,gene257,gene258,gene259,gene260,gene261,gene262,gene263,gene264,gene265,gene266,gene267,gene268,gene269,gene270,gene271,gene272,gene273,gene274,gene275,gene276,gene277,gene278,gene279,gene280,gene281,gene282,gene283,gene284,gene285,gene286,gene287,gene288,gene289,gene290,gene291,gene292,gene293,gene294,gene295,gene296,gene297,gene298,gene299,gene300,gene301,gene302,gene303,gene304,gene305,gene306,gene307,gene308,gene309,gene310,gene311,gene312,gene313,gene314,gene315,gene316,gene317,gene318,gene319,gene320,gene321,gene322,gene323,gene324,gene325,gene326,gene327,gene328,gene329,gene330,gene331,gene332,gene333,gene334,gene335,gene336,gene337,gene338,gene339,gene340,gene341,gene342,gene343,gene344,gene345,gene346,gene347,gene348,gene349,gene350,gene351,gene352,gene353,gene354,gene355,gene356,gene357,gene358,gene359,gene360,gene361,gene362,gene363,gene364,gene365,gene366,gene367,gene368,gene369,gene370,gene371,gene372,gene373,gene374,gene375,gene376,gene377,gene378,gene379,gene380,gene381,gene382,gene383,gene384,gene385,gene386,gene387,gene388,gene389,gene390,gene391,gene392,gene393,gene394,gene395,gene396,gene397,gene398,gene399,gene400,gene401,gene402,gene403,gene404,gene405,gene406,gene407,gene408,gene409,gene410,gene411,gene412,gene413,gene414,gene415,gene416,gene417,gene418,gene419,gene420,gene421,gene422,gene423,gene424,gene425,gene426,gene427,gene428,gene429,gene430,gene431,gene432,gene433,gene434,gene435,gene436,gene437,gene438,gene439,gene440,gene441,gene442,gene443,gene444,gene445,gene446,gene447,gene448,gene449,gene450,gene451,gene452,gene453,gene454,gene455,gene456,gene457,gene458,gene459,gene460,gene461,gene462,gene463,gene464,gene465,gene466,gene467,gene468,gene469,gene470,gene471,gene472,gene473,gene474,gene475,gene476,gene477,gene478,gene479,gene480,gene481,gene482,gene483,gene484,gene485,gene486,gene487,gene488,gene489,gene490,gene491,gene492,gene493,gene494,gene495,gene496,gene497,gene498,gene499,gene500,gene501,gene502,gene503,gene504,gene505,gene506,gene507,gene508,gene509,gene510,gene511,gene512,gene513,gene514,gene515,gene516,gene517,gene518,gene519,gene520,gene521,gene522,gene523,gene524,gene525,gene526,gene527,gene528,gene529,gene530,gene531,gene532,gene533,gene534,gene535,gene536,gene537,gene538,gene539,gene540,gene541,gene542,gene543,gene544,gene545,gene546,gene547,gene548,gene549,gene550,gene551,gene552,gene553,gene554,gene555,gene556,gene557,gene558,gene559,gene560,gene561,gene562,gene563,gene564,gene565,gene566,gene567,gene568,gene569,gene570,gene571,gene572,gene573,gene574,gene575,gene576,gene577,gene578,gene579,gene580,gene581,gene582,gene583,gene584,gene585,gene586,gene587,gene588,gene589,gene590,gene591,gene592,gene593,gene594,gene595,gene596,gene597,gene598,gene599,gene600,gene601,gene602,gene603,gene604,gene605,gene606,gene607,gene608,gene609,gene610,gene611,gene612,gene613,gene614,gene615,gene616,gene617,gene618,gene619,gene620,gene621,gene622,gene623,gene624,gene625,gene626,gene627,gene628,gene629,gene630,gene631,gene632,gene633,gene634,gene635,gene636,gene637,gene638,gene639,gene640,gene641,gene642,gene643,gene644,gene645,gene646,gene647,gene648,gene649,gene650,gene651,gene652,gene653,gene654,gene655,gene656,gene657,gene658,gene659,gene660,gene661,gene662,gene663,gene664,gene665,gene666,gene667,gene668,gene669,gene670,gene671,gene672,gene673,gene674,gene675,gene676,gene677,gene678,gene679,gene680,gene681,gene682,gene683,gene684,gene685,gene686,gene687,gene688,gene689,gene690,gene691,gene692,gene693,gene694,gene695,gene696,gene697,gene698,gene699,gene700,gene701,gene702,gene703,gene704,gene705,gene706,gene707,gene708,gene709,gene710,gene711,gene712,gene713,gene714,gene715,gene716,gene717,gene718,gene719,gene720,gene721,gene722,gene723,gene724,gene725,gene726,gene727,gene728,gene729,gene730,gene731,gene732,gene733,gene734,gene735,gene736,gene737,gene738,gene739,gene740,gene741,gene742,gene743,gene744,gene745,gene746,gene747,gene748,gene749,gene750,gene751,gene752,gene753,gene754,gene755,gene756,gene757,gene758,gene759,gene760,gene761,gene762,gene763,gene764,gene765,gene766,gene767,gene768,gene769,gene770,gene771,gene772,gene773,gene774,gene775,gene776,gene777,gene778,gene779,gene780,gene781,gene782,gene783,gene784,gene785,gene786,gene787,gene788,gene789,gene790,gene791,gene792,gene793,gene794,gene795,gene796,gene797,gene798,gene799,gene800,gene801,gene802,gene803,gene804,gene805,gene806,gene807,gene808,gene809,gene810,gene811,gene812,gene813,gene814,gene815,gene816,gene817,gene818,gene819,gene820,gene821,gene822,gene823,gene824,gene825,gene826,gene827,gene828,gene829,gene830,gene831,gene832,gene833,gene834,gene835,gene836,gene837,gene838,gene839,gene840,gene841,gene842,gene843,gene844,gene845,gene846,gene847,gene848,gene849,gene850,gene851,gene852,gene853,gene854,gene855,gene856,gene857,gene858,gene859,gene860,gene861,gene862,gene863,gene864,gene865,gene866,gene867,gene868,gene869,gene870,gene871,gene872,gene873,gene874,gene875,gene876,gene877,gene878,gene879,gene880,gene881,gene882,gene883,gene884,gene885,gene886,gene887,gene888,gene889,gene890,gene891,gene892,gene893,gene894,gene895,gene896,gene897,gene898,gene899,gene900,gene901,gene902,gene903,gene904,gene905,gene906,gene907,gene908,gene909,gene910,gene911,gene912,gene913,gene914,gene915,gene916,gene917,gene918,gene919,gene920,gene921,gene922,gene923,gene924,gene925,gene926,gene927,gene928,gene929,gene930,gene931,gene932,gene933,gene934,gene935,gene936,gene937,gene938,gene939,gene940,gene941,gene942,gene943,gene944,gene945,gene946,gene947,gene948,gene949,gene950,gene951,gene952,gene953,gene954,gene955,gene956,gene957,gene958,gene959,gene960,gene961,gene962,gene963,gene964,gene965,gene966,gene967,gene968,gene969,gene970,gene971,gene972,gene973,gene974,gene975,gene976,gene977,gene978,gene979,gene980,gene981,gene982,gene983,gene984,gene985,gene986,gene987,gene988,gene989,gene990,gene991,gene992,gene993,gene994,gene995,gene996,gene997,gene998,gene999,gene1000,gene1001,gene1002,gene1003,gene1004,gene1005,gene1006,gene1007,gene1008,gene1009,gene1010,gene1011,gene1012,gene1013,gene1014,gene1015,gene1016,gene1017,gene1018,gene1019,gene1020,gene1021,gene1022,gene1023,gene1024,gene1025,gene1026,gene1027,gene1028,gene1029,gene1030,gene1031,gene1032,gene1033,gene1034,gene1035,gene1036,gene1037,gene1038,gene1039,gene1040,gene1041,gene1042,gene1043,gene1044,gene1045,gene1046,gene1047,gene1048,gene1049,gene1050,gene1051,gene1052,gene1053,gene1054,gene1055,gene1056,gene1057,gene1058,gene1059,gene1060,gene1061,gene1062,gene1063,gene1064,gene1065,gene1066,gene1067,gene1068,gene1069,gene1070,gene1071,gene1072,gene1073,gene1074,gene1075,gene1076,gene1077,gene1078,gene1079,gene1080,gene1081,gene1082,gene1083,gene1084,gene1085,gene1086,gene1087,gene1088,gene1089,gene1090,gene1091,gene1092,gene1093,gene1094,gene1095,gene1096,gene1097,gene1098,gene1099,gene1100,gene1101,gene1102,gene1103,gene1104,gene1105,gene1106,gene1107,gene1108,gene1109,gene1110,gene1111,gene1112,gene1113,gene1114,gene1115,gene1116,gene1117,gene1118,gene1119,gene1120,gene1121,gene1122,gene1123,gene1124,gene1125,gene1126,gene1127,gene1128,gene1129,gene1130,gene1131,gene1132,gene1133,gene1134,gene1135,gene1136,gene1137,gene1138,gene1139,gene1140,gene1141,gene1142,gene1143,gene1144,gene1145,gene1146,gene1147,gene1148,gene1149,gene1150,gene1151,gene1152,gene1153,gene1154,gene1155,gene1156,gene1157,gene1158,gene1159,gene1160,gene1161,gene1162,gene1163,gene1164,gene1165,gene1166,gene1167,gene1168,gene1169,gene1170,gene1171,gene1172,gene1173,gene1174,gene1175,gene1176,gene1177,gene1178,gene1179,gene1180,gene1181,gene1182,gene1183,gene1184,gene1185,gene1186,gene1187,gene1188,gene1189,gene1190,gene1191,gene1192,gene1193,gene1194,gene1195,gene1196,gene1197,gene1198,gene1199,gene1200,gene1201,gene1202,gene1203,gene1204,gene1205,gene1206,gene1207,gene1208,gene1209,gene1210,gene1211,gene1212,gene1213,gene1214,gene1215,gene1216,gene1217,gene1218,gene1219,gene1220,gene1221,gene1222,gene1223,gene1224,gene1225,gene1226,gene1227,gene1228,gene1229,gene1230,gene1231,gene1232,gene1233,gene1234,gene1235,gene1236,gene1237,gene1238,gene1239,gene1240,gene1241,gene1242,gene1243,gene1244,gene1245,gene1246,gene1247,gene1248,gene1249,gene1250,gene1251,gene1252,gene1253,gene1254,gene1255,gene1256,gene1257,gene1258,gene1259,gene1260,gene1261,gene1262,gene1263,gene1264,gene1265,gene1266,gene1267,gene1268,gene1269,gene1270,gene1271,gene1272,gene1273,gene1274,gene1275,gene1276,gene1277,gene1278,gene1279,gene1280,gene1281,gene1282,gene1283,gene1284,gene1285,gene1286,gene1287,gene1288,gene1289,gene1290,gene1291,gene1292,gene1293,gene1294,gene1295,gene1296,gene1297,gene1298,gene1299,gene1300,gene1301,gene1302,gene1303,gene1304,gene1305,gene1306,gene1307,gene1308,gene1309,gene1310,gene1311,gene1312,gene1313,gene1314,gene1315,gene1316,gene1317,gene1318,gene1319,gene1320,gene1321,gene1322,gene1323,gene1324,gene1325,gene1326,gene1327,gene1328,gene1329,gene1330,gene1331,gene1332,gene1333,gene1334,gene1335,gene1336,gene1337,gene1338,gene1339,gene1340,gene1341,gene1342,gene1343,gene1344,gene1345,gene1346,gene1347,gene1348,gene1349,gene1350,gene1351,gene1352,gene1353,gene1354,gene1355,gene1356,gene1357,gene1358,gene1359,gene1360,gene1361,gene1362,gene1363,gene1364,gene1365,gene1366,gene1367,gene1368,gene1369,gene1370,gene1371,gene1372,gene1373,gene1374,gene1375,gene1376,gene1377,gene1378,gene1379,gene1380,gene1381,gene1382,gene1383,gene1384,gene1385,gene1386,gene1387,gene1388,gene1389,gene1390,gene1391,gene1392,gene1393,gene1394,gene1395,gene1396,gene1397,gene1398,gene1399,gene1400,gene1401,gene1402,gene1403,gene1404,gene1405,gene1406,gene1407,gene1408,gene1409,gene1410,gene1411,gene1412,gene1413,gene1414,gene1415,gene1416,gene1417,gene1418,gene1419,gene1420,gene1421,gene1422,gene1423,gene1424,gene1425,gene1426,gene1427,gene1428,gene1429,gene1430,gene1431,gene1432,gene1433,gene1434,gene1435,gene1436,gene1437,gene1438,gene1439,gene1440,gene1441,gene1442,gene1443,gene1444,gene1445,gene1446,gene1447,gene1448,gene1449,gene1450,gene1451,gene1452,gene1453,gene1454,gene1455,gene1456,gene1457,gene1458,gene1459,gene1460,gene1461,gene1462,gene1463,gene1464,gene1465,gene1466,gene1467,gene1468,gene1469,gene1470,gene1471,gene1472,gene1473,gene1474,gene1475,gene1476,gene1477,gene1478,gene1479,gene1480,gene1481,gene1482,gene1483,gene1484,gene1485,gene1486,gene1487,gene1488,gene1489,gene1490,gene1491,gene1492,gene1493,gene1494,gene1495,gene1496,gene1497,gene1498,gene1499,gene1500,gene1501,gene1502,gene1503,gene1504,gene1505,gene1506,gene1507,gene1508,gene1509,gene1510,gene1511,gene1512,gene1513,gene1514,gene1515,gene1516,gene1517,gene1518,gene1519,gene1520,gene1521,gene1522,gene1523,gene1524,gene1525,gene1526,gene1527,gene1528,gene1529,gene1530,gene1531,gene1532,gene1533,gene1534,gene1535,gene1536,gene1537,gene1538,gene1539,gene1540,gene1541,gene1542,gene1543,gene1544,gene1545,gene1546,gene1547,gene1548,gene1549,gene1550,gene1551,gene1552,gene1553,gene1554,gene1555,gene1556,gene1557,gene1558,gene1559,gene1560,gene1561,gene1562,gene1563,gene1564,gene1565,gene1566,gene1567,gene1568,gene1569,gene1570,gene1571,gene1572,gene1573,gene1574,gene1575,gene1576,gene1577,gene1578,gene1579,gene1580,gene1581,gene1582,gene1583,gene1584,gene1585,gene1586,gene1587,gene1588,gene1589,gene1590,gene1591,gene1592,gene1593,gene1594,gene1595,gene1596,gene1597,gene1598,gene1599,gene1600,gene1601,gene1602,gene1603,gene1604,gene1605,gene1606,gene1607,gene1608,gene1609,gene1610,gene1611,gene1612,gene1613,gene1614,gene1615,gene1616,gene1617,gene1618,gene1619,gene1620,gene1621,gene1622,gene1623,gene1624,gene1625,gene1626,gene1627,gene1628,gene1629,gene1630,gene1631,gene1632,gene1633,gene1634,gene1635,gene1636,gene1637,gene1638,gene1639,gene1640,gene1641,gene1642,gene1643,gene1644,gene1645,gene1646,gene1647,gene1648,gene1649,gene1650,gene1651,gene1652,gene1653,gene1654,gene1655,gene1656,gene1657,gene1658,gene1659,gene1660,gene1661,gene1662,gene1663,gene1664,gene1665,gene1666,gene1667,gene1668,gene1669,gene1670,gene1671,gene1672,gene1673,gene1674,gene1675,gene1676,gene1677,gene1678,gene1679,gene1680,gene1681,gene1682,gene1683,gene1684,gene1685,gene1686,gene1687,gene1688,gene1689,gene1690,gene1691,gene1692,gene1693,gene1694,gene1695,gene1696,gene1697,gene1698,gene1699,gene1700,gene1701,gene1702,gene1703,gene1704,gene1705,gene1706,gene1707,gene1708,gene1709,gene1710,gene1711,gene1712,gene1713,gene1714,gene1715,gene1716,gene1717,gene1718,gene1719,gene1720,gene1721,gene1722,gene1723,gene1724,gene1725,gene1726,gene1727,gene1728,gene1729,gene1730,gene1731,gene1732,gene1733,gene1734,gene1735,gene1736,gene1737,gene1738,gene1739,gene1740,gene1741,gene1742,gene1743,gene1744,gene1745,gene1746,gene1747,gene1748,gene1749,gene1750,gene1751,gene1752,gene1753,gene1754,gene1755,gene1756,gene1757,gene1758,gene1759,gene1760,gene1761,gene1762,gene1763,gene1764,gene1765,gene1766,gene1767,gene1768,gene1769,gene1770,gene1771,gene1772,gene1773,gene1774,gene1775,gene1776,gene1777,gene1778,gene1779,gene1780,gene1781,gene1782,gene1783,gene1784,gene1785,gene1786,gene1787,gene1788,gene1789,gene1790,gene1791,gene1792,gene1793,gene1794,gene1795,gene1796,gene1797,gene1798,gene1799,gene1800,gene1801,gene1802,gene1803,gene1804,gene1805,gene1806,gene1807,gene1808,gene1809,gene1810,gene1811,gene1812,gene1813,gene1814,gene1815,gene1816,gene1817,gene1818,gene1819,gene1820,gene1821,gene1822,gene1823,gene1824,gene1825,gene1826,gene1827,gene1828,gene1829,gene1830,gene1831,gene1832,gene1833,gene1834,gene1835,gene1836,gene1837,gene1838,gene1839,gene1840,gene1841,gene1842,gene1843,gene1844,gene1845,gene1846,gene1847,gene1848,gene1849,gene1850,gene1851,gene1852,gene1853,gene1854,gene1855,gene1856,gene1857,gene1858,gene1859,gene1860,gene1861,gene1862,gene1863,gene1864,gene1865,gene1866,gene1867,gene1868,gene1869,gene1870,gene1871,gene1872,gene1873,gene1874,gene1875,gene1876,gene1877,gene1878,gene1879,gene1880,gene1881,gene1882,gene1883,gene1884,gene1885,gene1886,gene1887,gene1888,gene1889,gene1890,gene1891,gene1892,gene1893,gene1894,gene1895,gene1896,gene1897,gene1898,gene1899,gene1900,gene1901,gene1902,gene1903,gene1904,gene1905,gene1906,gene1907,gene1908,gene1909,gene1910,gene1911,gene1912,gene1913,gene1914,gene1915,gene1916,gene1917,gene1918,gene1919,gene1920,gene1921,gene1922,gene1923,gene1924,gene1925,gene1926,gene1927,gene1928,gene1929,gene1930,gene1931,gene1932,gene1933,gene1934,gene1935,gene1936,gene1937,gene1938,gene1939,gene1940,gene1941,gene1942,gene1943,gene1944,gene1945,gene1946,gene1947,gene1948,gene1949,gene1950,gene1951,gene1952,gene1953,gene1954,gene1955,gene1956,gene1957,gene1958,gene1959,gene1960,gene1961,gene1962,gene1963,gene1964,gene1965,gene1966,gene1967,gene1968,gene1969,gene1970,gene1971,gene1972,gene1973,gene1974,gene1975,gene1976,gene1977,gene1978,gene1979,gene1980,gene1981,gene1982,gene1983,gene1984,gene1985,gene1986,gene1987,gene1988,gene1989,gene1990,gene1991,gene1992,gene1993,gene1994,gene1995,gene1996,gene1997,gene1998,gene1999,gene2000,gene2001,gene2002,gene2003,gene2004,gene2005,gene2006,gene2007,gene2008,gene2009,gene2010,gene2011,gene2012,gene2013,gene2014,gene2015,gene2016,gene2017,gene2018,gene2019,gene2020,gene2021,gene2022,gene2023,gene2024,gene2025,gene2026,gene2027,gene2028,gene2029,gene2030,gene2031,gene2032,gene2033,gene2034,gene2035,gene2036,gene2037,gene2038,gene2039,gene2040,gene2041,gene2042,gene2043,gene2044,gene2045,gene2046,gene2047,gene2048,gene2049,gene2050,gene2051,gene2052,gene2053,gene2054,gene2055,gene2056,gene2057,gene2058,gene2059,gene2060,gene2061,gene2062,gene2063,gene2064,gene2065,gene2066,gene2067,gene2068,gene2069,gene2070,gene2071,gene2072,gene2073,gene2074,gene2075,gene2076,gene2077,gene2078,gene2079,gene2080,gene2081,gene2082,gene2083,gene2084,gene2085,gene2086,gene2087,gene2088,gene2089,gene2090,gene2091,gene2092,gene2093,gene2094,gene2095,gene2096,gene2097,gene2098,gene2099,gene2100,gene2101,gene2102,gene2103,gene2104,gene2105,gene2106,gene2107,gene2108,gene2109,gene2110,gene2111,gene2112,gene2113,gene2114,gene2115,gene2116,gene2117,gene2118,gene2119,gene2120,gene2121,gene2122,gene2123,gene2124,gene2125,gene2126,gene2127,gene2128,gene2129,gene2130,gene2131,gene2132,gene2133,gene2134,gene2135,gene2136,gene2137,gene2138,gene2139,gene2140,gene2141,gene2142,gene2143,gene2144,gene2145,gene2146,gene2147,gene2148,gene2149,gene2150,gene2151,gene2152,gene2153,gene2154,gene2155,gene2156,gene2157,gene2158,gene2159,gene2160,gene2161,gene2162,gene2163,gene2164,gene2165,gene2166,gene2167,gene2168,gene2169,gene2170,gene2171,gene2172,gene2173,gene2174,gene2175,gene2176,gene2177,gene2178,gene2179,gene2180,gene2181,gene2182,gene2183,gene2184,gene2185,gene2186,gene2187,gene2188,gene2189,gene2190,gene2191,gene2192,gene2193,gene2194,gene2195,gene2196,gene2197,gene2198,gene2199,gene2200,gene2201,gene2202,gene2203,gene2204,gene2205,gene2206,gene2207,gene2208,gene2209,gene2210,gene2211,gene2212,gene2213,gene2214,gene2215,gene2216,gene2217,gene2218,gene2219,gene2220,gene2221,gene2222,gene2223,gene2224,gene2225,gene2226,gene2227,gene2228,gene2229,gene2230,gene2231,gene2232,gene2233,gene2234,gene2235,gene2236,gene2237,gene2238,gene2239,gene2240,gene2241,gene2242,gene2243,gene2244,gene2245,gene2246,gene2247,gene2248,gene2249,gene2250,gene2251,gene2252,gene2253,gene2254,gene2255,gene2256,gene2257,gene2258,gene2259,gene2260,gene2261,gene2262,gene2263,gene2264,gene2265,gene2266,gene2267,gene2268,gene2269,gene2270,gene2271,gene2272,gene2273,gene2274,gene2275,gene2276,gene2277,gene2278,gene2279,gene2280,gene2281,gene2282,gene2283,gene2284,gene2285,gene2286,gene2287,gene2288,gene2289,gene2290,gene2291,gene2292,gene2293,gene2294,gene2295,gene2296,gene2297,gene2298,gene2299,gene2300,gene2301,gene2302,gene2303,gene2304,gene2305,gene2306,gene2307,gene2308,CancerType

In [14]:
# Feature Summary
summary

           index     dtype  n_missing  pct_missing  n_unique  \
0     CancerType  category        0.0          0.0       4.0
1          gene1   float64        0.0          0.0      83.0
2          gene2   float64        0.0          0.0      83.0
3          gene3   float64        0.0          0.0      83.0
4          gene4   float64        0.0          0.0      82.0
5          gene5   float64        0.0          0.0      83.0
6          gene6   float64        0.0          0.0      83.0
7          gene7   float64        0.0          0.0      83.0
8          gene8   float64        0.0          0.0      83.0
9          gene9   float64        0.0          0.0      83.0
10        gene10   float64        0.0          0.0      83.0
11        gene11   float64        0.0          0.0      83.0
12        gene12   float64        0.0          0.0      83.0
13        gene13   float64        0.0          0.0      83.0
14        gene14   float64        0.0          0.0      83.0
15        gene15   float64        0.0          0.0      83.0
16        gene16   float64        0.0          0.0      83.0
17        gene17   float64        0.0          0.0      83.0
18        gene18   float64        0.0          0.0      83.0
19        gene19   float64        0.0          0.0      83.0
20        gene20   float64        0.0          0.0      82.0
21        gene21   float64        0.0          0.0      83.0
22        gene22   float64        0.0          0.0      83.0
23        gene23   float64        0.0          0.0      83.0
24        gene24   float64        0.0          0.0      83.0
25        gene25   float64        0.0          0.0      82.0
26        gene26   float64        0.0          0.0      83.0
27        gene27   float64        0.0          0.0      83.0
28        gene28   float64        0.0          0.0      83.0
29        gene29   float64        0.0          0.0      83.0
30        gene30   float64        0.0          0.0      83.0
31        gene31   float64        0.0          0.0      83.0
32        gene32   float64        0.0          0.0      83.0
33        gene33   float64        0.0          0.0      83.0
34        gene34   float64        0.0          0.0      83.0
35        gene35   float64        0.0          0.0      83.0
36        gene36   float64        0.0          0.0      83.0
37        gene37   float64        0.0          0.0      83.0
38        gene38   float64        0.0          0.0      83.0
39        gene39   float64        0.0          0.0      83.0
40        gene40   float64        0.0          0.0      82.0
41        gene41   float64        0.0          0.0      83.0
42        gene42   float64        0.0          0.0      83.0
43        gene43   float64        0.0          0.0      83.0
44        gene44   float64        0.0          0.0      83.0
45        gene45   float64        0.0          0.0      83.0
46        gene46   float64        0.0          0.0      83.0
47        gene47   float64        0.0          0.0      83.0
48        gene48   float64        0.0          0.0      82.0
49        gene49   float64        0.0          0.0      83.0
50        gene50   float64        0.0          0.0      83.0
51        gene51   float64        0.0          0.0      83.0
52        gene52   float64        0.0          0.0      83.0
53        gene53   float64        0.0          0.0      83.0
54        gene54   float64        0.0          0.0      82.0
55        gene55   float64        0.0          0.0      83.0
56        gene56   float64        0.0          0.0      83.0
57        gene57   float64        0.0          0.0      83.0
58        gene58   float64        0.0          0.0      83.0
59        gene59   float64        0.0          0.0      82.0
60        gene60   float64        0.0          0.0      83.0
61        gene61   float64        0.0          0.0      83.0
62        gene62   float64        0.0          0.0      83.0
63        gene63   float64        0.0          0.0      83.0
64        gene64   float64        0.0          0.0      82.0
65        gene65   float64        0.0          0.0      83.0
66        gene66   float64        0.0          0.0      83.0
67        gene67   float64        0.0          0.0      83.0
68        gene68   float64        0.0          0.0      83.0
69        gene69   float64        0.0          0.0      83.0
70        gene70   float64        0.0          0.0      82.0
71        gene71   float64        0.0          0.0      82.0
72        gene72   float64        0.0          0.0      83.0
73        gene73   float64        0.0          0.0      83.0
74        gene74   float64        0.0          0.0      83.0
75        gene75   float64        0.0          0.0      83.0
76        gene76   float64        0.0          0.0      81.0
77        gene77   float64        0.0          0.0      83.0
78        gene78   float64        0.0          0.0      83.0
79        gene79   float64        0.0          0.0      83.0
80        gene80   float64        0.0          0.0      82.0
81        gene81   float64        0.0          0.0      82.0
82        gene82   float64        0.0          0.0      83.0
83        gene83   float64        0.0          0.0      83.0
84        gene84   float64        0.0          0.0      83.0
85        gene85   float64        0.0          0.0      83.0
86        gene86   float64        0.0          0.0      82.0
87        gene87   float64        0.0          0.0      83.0
88        gene88   float64        0.0          0.0      83.0
89        gene89   float64        0.0          0.0      82.0
90        gene90   float64        0.0          0.0      82.0
91        gene91   float64        0.0          0.0      82.0
92        gene92   float64        0.0          0.0      83.0
93        gene93   float64        0.0          0.0      83.0
94        gene94   float64        0.0          0.0      83.0
95        gene95   float64        0.0          0.0      82.0
96        gene96   float64        0.0          0.0      82.0
97        gene97   float64        0.0          0.0      83.0
98        gene98   float64        0.0          0.0      81.0
99        gene99   float64        0.0          0.0      83.0
100      gene100   float64        0.0          0.0      83.0
101      gene101   float64        0.0          0.0      83.0
102      gene102   float64        0.0          0.0      83.0
103      gene103   float64        0.0          0.0      81.0
104      gene104   float64        0.0          0.0      83.0
105      gene105   float64        0.0          0.0      83.0
106      gene106   float64        0.0          0.0      83.0
107      gene107   float64        0.0          0.0      83.0
108      gene108   float64        0.0          0.0      83.0
109      gene109   float64        0.0          0.0      82.0
110      gene110   float64        0.0          0.0      83.0
111      gene111   float64        0.0          0.0      83.0
112      gene112   float64        0.0          0.0      83.0
113      gene113   float64        0.0          0.0      83.0
114      gene114   float64        0.0          0.0      83.0
115      gene115   float64        0.0          0.0      83.0
116      gene116   float64        0.0          0.0      79.0
117      gene117   float64        0.0          0.0      83.0
118      gene118   float64        0.0          0.0      82.0
119      gene119   float64        0.0          0.0      83.0
120      gene120   float64        0.0          0.0      83.0
121      gene121   float64        0.0          0.0      83.0
122      gene122   float64        0.0          0.0      83.0
123      gene123   float64        0.0          0.0      80.0
124      gene124   float64        0.0          0.0      83.0
125      gene125   float64        0.0          0.0      83.0
126      gene126   float64        0.0          0.0      83.0
127      gene127   float64        0.0          0.0      83.0
128      gene128   float64        0.0          0.0      83.0
129      gene129   float64        0.0          0.0      82.0
130      gene130   float64        0.0          0.0      83.0
131      gene131   float64        0.0          0.0      83.0
132      gene132   float64        0.0          0.0      81.0
133      gene133   float64        0.0          0.0      83.0
134      gene134   float64        0.0          0.0      83.0
135      gene135   float64        0.0          0.0      83.0
136      gene136   float64        0.0          0.0      83.0
137      gene137   float64        0.0          0.0      83.0
138      gene138   float64        0.0          0.0      83.0
139      gene139   float64        0.0          0.0      83.0
140      gene140   float64        0.0          0.0      83.0
141      gene141   float64        0.0          0.0      83.0
142      gene142   float64        0.0          0.0      83.0
143      gene143   float64        0.0          0.0      81.0
144      gene144   float64        0.0          0.0      83.0
145      gene145   float64        0.0          0.0      82.0
146      gene146   float64        0.0          0.0      83.0
147      gene147   float64        0.0          0.0      82.0
148      gene148   float64        0.0          0.0      83.0
149      gene149   float64        0.0          0.0      83.0
150      gene150   float64        0.0          0.0      83.0
151      gene151   float64        0.0          0.0      83.0
152      gene152   float64        0.0          0.0      83.0
153      gene153   float64        0.0          0.0      83.0
154      gene154   float64        0.0          0.0      83.0
155      gene155   float64        0.0          0.0      83.0
156      gene156   float64        0.0          0.0      83.0
157      gene157   float64        0.0          0.0      83.0
158      gene158   float64        0.0          0.0      83.0
159      gene159   float64        0.0          0.0      83.0
160      gene160   float64        0.0          0.0      82.0
161      gene161   float64        0.0          0.0      83.0
162      gene162   float64        0.0          0.0      83.0
163      gene163   float64        0.0          0.0      82.0
164      gene164   float64        0.0          0.0      83.0
165      gene165   float64        0.0          0.0      83.0
166      gene166   float64        0.0          0.0      81.0
167      gene167   float64        0.0          0.0      83.0
168      gene168   float64        0.0          0.0      83.0
169      gene169   float64        0.0          0.0      83.0
170      gene170   float64        0.0          0.0      82.0
171      gene171   float64        0.0          0.0      83.0
172      gene172   float64        0.0          0.0      82.0
173      gene173   float64        0.0          0.0      82.0
174      gene174   float64        0.0          0.0      83.0
175      gene175   float64        0.0          0.0      82.0
176      gene176   float64        0.0          0.0      83.0
177      gene177   float64        0.0          0.0      83.0
178      gene178   float64        0.0          0.0      83.0
179      gene179   float64        0.0          0.0      83.0
180      gene180   float64        0.0          0.0      83.0
181      gene181   float64        0.0          0.0      83.0
182      gene182   float64        0.0          0.0      83.0
183      gene183   float64        0.0          0.0      83.0
184      gene184   float64        0.0          0.0      82.0
185      gene185   float64        0.0          0.0      82.0
186      gene186   float64        0.0          0.0      83.0
187      gene187   float64        0.0          0.0      83.0
188      gene188   float64        0.0          0.0      83.0
189      gene189   float64        0.0          0.0      83.0
190      gene190   float64        0.0          0.0      80.0
191      gene191   float64        0.0          0.0      83.0
192      gene192   float64        0.0          0.0      82.0
193      gene193   float64        0.0          0.0      82.0
194      gene194   float64        0.0          0.0      83.0
195      gene195   float64        0.0          0.0      83.0
196      gene196   float64        0.0          0.0      82.0
197      gene197   float64        0.0          0.0      82.0
198      gene198   float64        0.0          0.0      83.0
199      gene199   float64        0.0          0.0      81.0
200      gene200   float64        0.0          0.0      83.0
201      gene201   float64        0.0          0.0      83.0
202      gene202   float64        0.0          0.0      83.0
203      gene203   float64        0.0          0.0      82.0
204      gene204   float64        0.0          0.0      82.0
205      gene205   float64        0.0          0.0      83.0
206      gene206   float64        0.0          0.0      83.0
207      gene207   float64        0.0          0.0      83.0
208      gene208   float64        0.0          0.0      83.0
209      gene209   float64        0.0          0.0      81.0
210      gene210   float64        0.0          0.0      83.0
211      gene211   float64        0.0          0.0      82.0
212      gene212   float64        0.0          0.0      83.0
213      gene213   float64        0.0          0.0      81.0
214      gene214   float64        0.0          0.0      83.0
215      gene215   float64        0.0          0.0      83.0
216      gene216   float64        0.0          0.0      83.0
217      gene217   float64        0.0          0.0      82.0
218      gene218   float64        0.0          0.0      83.0
219      gene219   float64        0.0          0.0      83.0
220      gene220   float64        0.0          0.0      82.0
221      gene221   float64        0.0          0.0      83.0
222      gene222   float64        0.0          0.0      83.0
223      gene223   float64        0.0          0.0      81.0
224      gene224   float64        0.0          0.0      79.0
225      gene225   float64        0.0          0.0      82.0
226      gene226   float64        0.0          0.0      82.0
227      gene227   float64        0.0          0.0      83.0
228      gene228   float64        0.0          0.0      83.0
229      gene229   float64        0.0          0.0      83.0
230      gene230   float64        0.0          0.0      83.0
231      gene231   float64        0.0          0.0      83.0
232      gene232   float64        0.0          0.0      82.0
233      gene233   float64        0.0          0.0      82.0
234      gene234   float64        0.0          0.0      82.0
235      gene235   float64        0.0          0.0      83.0
236      gene236   float64        0.0          0.0      83.0
237      gene237   float64        0.0          0.0      83.0
238      gene238   float64        0.0          0.0      82.0
239      gene239   float64        0.0          0.0      83.0
240      gene240   float64        0.0          0.0      83.0
241      gene241   float64        0.0          0.0      83.0
242      gene242   float64        0.0          0.0      82.0
243      gene243   float64        0.0          0.0      82.0
244      gene244   float64        0.0          0.0      82.0
245      gene245   float64        0.0          0.0      83.0
246      gene246   float64        0.0          0.0      83.0
247      gene247   float64        0.0          0.0      83.0
248      gene248   float64        0.0          0.0      83.0
249      gene249   float64        0.0          0.0      83.0
250      gene250   float64        0.0          0.0      83.0
251      gene251   float64        0.0          0.0      83.0
252      gene252   float64        0.0          0.0      83.0
253      gene253   float64        0.0          0.0      83.0
254      gene254   float64        0.0          0.0      83.0
255      gene255   float64        0.0          0.0      83.0
256      gene256   float64        0.0          0.0      83.0
257      gene257   float64        0.0          0.0      83.0
258      gene258   float64        0.0          0.0      83.0
259      gene259   float64        0.0          0.0      82.0
260      gene260   float64        0.0          0.0      83.0
261      gene261   float64        0.0          0.0      83.0
262      gene262   float64        0.0          0.0      83.0
263      gene263   float64        0.0          0.0      83.0
264      gene264   float64        0.0          0.0      83.0
265      gene265   float64        0.0          0.0      83.0
266      gene266   float64        0.0          0.0      83.0
267      gene267   float64        0.0          0.0      83.0
268      gene268   float64        0.0          0.0      83.0
269      gene269   float64        0.0          0.0      80.0
270      gene270   float64        0.0          0.0      83.0
271      gene271   float64        0.0          0.0      81.0
272      gene272   float64        0.0          0.0      83.0
273      gene273   float64        0.0          0.0      83.0
274      gene274   float64        0.0          0.0      83.0
275      gene275   float64        0.0          0.0      83.0
276      gene276   float64        0.0          0.0      83.0
277      gene277   float64        0.0          0.0      82.0
278      gene278   float64        0.0          0.0      83.0
279      gene279   float64        0.0          0.0      83.0
280      gene280   float64        0.0          0.0      83.0
281      gene281   float64        0.0          0.0      83.0
282      gene282   float64        0.0          0.0      83.0
283      gene283   float64        0.0          0.0      82.0
284      gene284   float64        0.0          0.0      81.0
285      gene285   float64        0.0          0.0      83.0
286      gene286   float64        0.0          0.0      83.0
287      gene287   float64        0.0          0.0      83.0
288      gene288   float64        0.0          0.0      83.0
289      gene289   float64        0.0          0.0      83.0
290      gene290   float64        0.0          0.0      82.0
291      gene291   float64        0.0          0.0      81.0
292      gene292   float64        0.0          0.0      83.0
293      gene293   float64        0.0          0.0      83.0
294      gene294   float64        0.0          0.0      83.0
295      gene295   float64        0.0          0.0      82.0
296      gene296   float64        0.0          0.0      83.0
297      gene297   float64        0.0          0.0      83.0
298      gene298   float64        0.0          0.0      83.0
299      gene299   float64        0.0          0.0      81.0
300      gene300   float64        0.0          0.0      82.0
301      gene301   float64        0.0          0.0      83.0
302      gene302   float64        0.0          0.0      83.0
303      gene303   float64        0.0          0.0      82.0
304      gene304   float64        0.0          0.0      83.0
305      gene305   float64        0.0          0.0      83.0
306      gene306   float64        0.0          0.0      82.0
307      gene307   float64        0.0          0.0      83.0
308      gene308   float64        0.0          0.0      83.0
309      gene309   float64        0.0          0.0      82.0
310      gene310   float64        0.0          0.0      82.0
311      gene311   float64        0.0          0.0      82.0
312      gene312   float64        0.0          0.0      83.0
313      gene313   float64        0.0          0.0      83.0
314      gene314   float64        0.0          0.0      83.0
315      gene315   float64        0.0          0.0      83.0
316      gene316   float64        0.0          0.0      83.0
317      gene317   float64        0.0          0.0      83.0
318      gene318   float64        0.0          0.0      83.0
319      gene319   float64        0.0          0.0      83.0
320      gene320   float64        0.0          0.0      83.0
321      gene321   float64        0.0          0.0      83.0
322      gene322   float64        0.0          0.0      83.0
323      gene323   float64        0.0          0.0      83.0
324      gene324   float64        0.0          0.0      81.0
325      gene325   float64        0.0          0.0      83.0

In [15]:
# Numeric Feature Statistics
numeric_stats

          count      mean       std     min      max
gene1      83.0  1.487880  0.988884  0.0683   4.3557
gene2      83.0  0.300580  0.371274  0.0494   1.9247
gene3      83.0  1.020083  0.671267  0.1570   3.1923
gene4      83.0  0.501959  0.558527  0.0345   1.7928
gene5      83.0  0.293716  0.154303  0.0401   0.7674
gene6      83.0  1.903552  1.644205  0.2826  11.6200
gene7      83.0  5.976558  3.171152  2.1729  19.0419
gene8      83.0  1.290884  0.629206  0.2958   3.4008
gene9      83.0  1.413651  0.697047  0.5277   4.2117
gene10     83.0  1.652846  0.712888  0.2076   3.2202
gene11     83.0  6.305360  2.957928  2.6131  16.8467
gene12     83.0  0.847607  0.372462  0.1645   1.6819
gene13     83.0  5.372463  2.072527  0.7430  10.8410
gene14     83.0  1.815135  0.814652  0.1667   4.3739
gene15     83.0  0.992533  0.560793  0.2812   2.7932
gene16     83.0  0.746039  0.427594  0.1098   2.6361
gene17     83.0  1.119800  0.524873  0.3130   3.4933
gene18     83.0  2.194901  1.137175  0.4827   5.1954
gene19     83.0  0.872243  0.871405  0.0781   3.4498
gene20     83.0  1.197177  0.635433  0.1476   3.4896
gene21     83.0  1.604120  0.760056  0.4571   4.3359
gene22     83.0  5.834029  2.339818  2.2653  13.6498
gene23     83.0  0.494005  0.259658  0.0419   1.3326
gene24     83.0  3.536314  2.078099  0.4738  11.7202
gene25     83.0  2.680371  1.687979  0.1263   7.9529
gene26     83.0  5.888641  2.716861  2.0562  16.7242
gene27     83.0  1.030260  0.768218  0.0572   3.7736
gene28     83.0  1.269367  0.690405  0.3297   3.7840
gene29     83.0  0.366127  0.244284  0.0442   1.0769
gene30     83.0  1.323563  0.793472  0.3039   3.9688
gene31     83.0  0.561837  0.278123  0.1196   1.5751
gene32     83.0  1.016720  0.507884  0.2853   3.1411
gene33     83.0  0.651269  0.818093  0.0188   3.8806
gene34     83.0  1.999800  0.910553  0.3790   4.7468
gene35     83.0  4.153582  1.955357  0.9257  11.0402
gene36     83.0  2.065116  1.099900  0.6502   6.2452
gene37     83.0  0.731452  0.395307  0.1554   2.2363
gene38     83.0  0.551766  0.332739  0.0500   2.0631
gene39     83.0  0.569075  0.225650  0.1534   1.1363
gene40     83.0  0.341222  0.187387  0.0816   1.3195
gene41     83.0  0.729701  0.694550  0.0906   3.8392
gene42     83.0  3.104458  1.518578  1.1167   9.0717
gene43     83.0  0.581673  0.528954  0.0742   2.3113
gene44     83.0  0.552411  0.354737  0.1355   2.9923
gene45     83.0  0.946647  0.535510  0.1711   2.9859
gene46     83.0  1.680612  0.806552  0.3464   3.9030
gene47     83.0  4.774549  1.804138  0.1574  10.1598
gene48     83.0  1.660086  1.041271  0.2801   5.2167
gene49     83.0  2.963140  2.002574  0.1493   8.5808
gene50     83.0  0.246886  0.210554  0.0430   1.1734
gene51     83.0  2.955699  1.454491  0.4826   8.1181
gene52     83.0  0.471051  0.240082  0.0719   1.1281
gene53     83.0  1.619722  0.641716  0.2447   3.4742
gene54     83.0  0.303934  0.281653  0.0334   1.3874
gene55     83.0  2.127036  1.187287  0.2330   5.1017
gene56     83.0  1.280739  0.672227  0.3738   3.3430
gene57     83.0  4.025931  1.686176  0.8853  11.8735
gene58     83.0  0.776784  0.999935  0.0385   3.3964
gene59     83.0  2.593630  1.110064  0.1198   5.9119
gene60     83.0  5.770893  2.847167  1.2415  14.4826
gene61     83.0  5.030701  2.365475  1.8432  14.8016
gene62     83.0  6.285769  3.298317  0.0909  18.1841
gene63     83.0  0.837582  0.380768  0.2286   2.3740
gene64     83.0  1.404746  1.052069  0.1388   4.2967
gene65     83.0  1.646833  0.810493  0.3687   4.4537
gene66     83.0  0.741941  1.293638  0.0727  11.0257
gene67     83.0  0.311092  0.284403  0.0375   1.5017
gene68     83.0  1.815192  2.583910  0.0830  17.9885
gene69     83.0  0.633272  0.225551  0.1522   1.2596
gene70     83.0  0.312394  0.295324  0.0365   2.2303
gene71     83.0  0.540242  0.342128  0.0261   1.5071
gene72     83.0  0.711205  0.550850  0.1599   3.9519
gene73     83.0  0.217936  0.206734  0.0345   1.6130
gene74     83.0  0.624648  0.616309  0.0669   2.5600
gene75     83.0  0.354360  0.308204  0.0206   2.1721
gene76     83.0  1.451813  0.954664  0.1441   5.1301
gene77     83.0  3.097476  1.987173  0.5561  12.0810
gene78     83.0  0.461398  0.234648  0.0066   1.3459
gene79     83.0  0.192186  0.106176  0.0298   0.5038
gene80     83.0  0.507004  0.248929  0.0785   1.2640
gene81     83.0  0.422301  0.204821  0.0951   0.9343
gene82     83.0  0.201712  0.080023  0.0342   0.4562
gene83     83.0  3.833128  1.817949  0.6610  11.2570
gene84     83.0  1.951475  1.164015  0.0990   7.1308
gene85     83.0  0.848745  1.017101  0.1010   5.3431
gene86     83.0  0.245736  0.164240  0.0249   0.6798
gene87     83.0  0.815558  0.667033  0.0686   4.0525
gene88     83.0  1.878119  1.387175  0.1745   5.7276
gene89     83.0  0.329122  0.214092  0.0204   0.9761
gene90     83.0  0.429306  0.378098  0.0090   2.1931
gene91     83.0  0.511269  0.903556  0.1254   8.3337
gene92     83.0  1.014896  0.682887  0.2318   4.2433
gene93     83.0  0.204029  0.157713  0.0243   0.7855
gene94     83.0  3.168747  1.374413  0.6841   8.6320
gene95     83.0  0.344463  0.204133  0.0311   1.1864
gene96     83.0  0.568881  0.288966  0.1719   1.6977
gene97     83.0  0.623906  0.253866  0.1842   1.3106
gene98     83.0  0.197670  0.133533  0.0231   0.8898
gene99     83.0  1.453180  0.876606  0.2805   4.2282
gene100    83.0  0.298999  0.261266  0.0516   1.5680
gene101    83.0  1.897377  1.395173  0.1920   7.7114
gene102    83.0  0.619008  0.360151  0.0750   1.9496
gene103    83.0  0.537354  0.283717  0.1148   1.6768
gene104    83.0  0.942188  0.577706  0.1694   3.5046
gene105    83.0  0.597602  0.217693  0.2088   1.2570
gene106    83.0  0.380235  0.201410  0.0724   1.1411
gene107    83.0  1.278822  1.556774  0.0529  10.9814
gene108    83.0  0.351988  0.375995  0.0520   1.7495
gene109    83.0  0.295005  0.156576  0.0459   0.9189
gene110    83.0  0.193137  0.080042  0.0398   0.4505
gene111    83.0  0.246687  0.124280  0.0563   0.6473
gene112    83.0  1.152878  1.208454  0.1130   7.7745
gene113    83.0  0.369351  0.149028  0.1579   0.8280
gene114    83.0  0.932218  0.435194  0.1104   2.4718
gene115    83.0  0.481358  0.938455  0.0202   5.3958
gene116    83.0  0.284163  0.178837  0.0714   1.1472
gene117    83.0  0.176893  0.106826  0.0120   0.5235
gene118    83.0  1.539189  0.863257  0.3679   4.8183
gene119    83.0  0.496107  0.670329  0.0376   3.1361
gene120    83.0  1.124801  0.575068  0.3578   4.8968
gene121    83.0  0.588496  0.280583  0.1149   1.6331
gene122    83.0  0.687965  0.480593  0.1235   1.9574
gene123    83.0  0.326110  0.282507  0.0364   1.3896
gene124    83.0  1.983267  1.193740  0.2605   5.5377
gene125    83.0  0.578358  0.307753  0.1486   1.7495
gene126    83.0  1.495086  1.540705  0.1130   8.5717
gene127    83.0  0.903407  0.868896  0.1072   3.7791
gene128    83.0  0.994273  0.571634  0.1956   4.0059
gene129    83.0  0.971247  2.221323  0.0557  13.9601
gene130    83.0  1.350495  1.020150  0.2109   4.8959
gene131    83.0  0.634064  0.304438  0.0639   1.8805
gene132    83.0  0.500748  1.215477  0.0278   7.2320
gene133    83.0  2.608580  1.257078  0.6788   8.5290
gene134    83.0  0.557125  0.806838  0.1000   7.5267
gene135    83.0  0.990246  0.710421  0.1629   3.9138
gene136    83.0  0.911157  0.628755  0.0451   3.2052
gene137    83.0  0.674987  0.602474  0.0453   2.8756
gene138    83.0  0.655055  0.332432  0.0727   1.6965
gene139    83.0  0.456498  0.409976  0.1018   2.8863
gene140    83.0  1.807878  1.011962  0.4143   5.2963
gene141    83.0  2.188658  1.983194  0.1700   8.7203
gene142    83.0  0.790414  0.714774  0.0893   4.4342
gene143    83.0  0.255652  0.207103  0.0292   0.9524
gene144    83.0  2.826720  1.466666  0.5548   7.1218
gene145    83.0  0.260925  0.227906  0.0359   1.0627
gene146    83.0  2.113588  2.330427  0.0823  11.7826
gene147    83.0  0.168967  0.110999  0.0384   0.7777
gene148    83.0  6.109146  3.168107  1.9213  19.3932
gene149    83.0  1.174034  0.616421  0.1094   3.0325
gene150    83.0  0.257159  0.179793  0.0582   0.8384
gene151    83.0  2.812636  2.643076  0.1071  14.7220
gene152    83.0  1.224382  0.672116  0.1018   2.9259
gene153    83.0  1.064382  0.909346  0.0754   4.4771
gene154    83.0  0.484140  0.522213  0.0702   3.2777
gene155    83.0  0.395193  0.215717  0.0089   1.3301
gene156    83.0  0.907242  1.207473  0.0979   6.9794
gene157    83.0  0.431857  0.607257  0.0291   2.8948
gene158    83.0  0.743259  0.375374  0.1402   1.9435
gene159    83.0  1.634872  0.871110  0.0960   4.3754
gene160    83.0  0.294051  0.204009  0.0439   1.2869
gene161    83.0  2.010901  0.864993  0.7663   5.1242
gene162    83.0  1.200663  0.809688  0.0688   3.2715
gene163    83.0  0.441898  0.152369  0.1926   1.0154
gene164    83.0  1.223669  0.939622  0.1058   3.9162
gene165    83.0  0.685402  0.608366  0.0673   3.2467
gene166    83.0  0.600712  0.525578  0.0962   3.6589
gene167    83.0  0.372886  0.240971  0.1028   1.1906
gene168    83.0  0.407508  0.162146  0.0867   0.9398
gene169    83.0  0.648977  0.886778  0.0730   5.1062
gene170    83.0  0.821490  0.505544  0.2226   3.6820
gene171    83.0  0.783976  0.389534  0.1122   1.9716
gene172    83.0  0.352630  0.198045  0.0844   1.5591
gene173    83.0  0.386324  0.162805  0.1458   0.9667
gene174    83.0  0.299427  0.303616  0.0239   1.4964
gene175    83.0  0.642373  0.388999  0.1756   2.1140
gene176    83.0  2.597716  1.139786  0.5518   6.7884
gene177    83.0  0.153127  0.110377  0.0138   0.5431
gene178    83.0  1.779645  0.698693  0.6565   4.6403
gene179    83.0  0.796608  0.419405  0.1587   2.1505
gene180    83.0  2.854048  1.270468  0.5934   7.3131
gene181    83.0  0.575017  0.368246  0.0516   1.6442
gene182    83.0  0.403966  0.303547  0.0409   1.5563
gene183    83.0  1.152637  0.841715  0.1394   4.1510
gene184    83.0  0.220795  0.626523  0.0323   5.8038
gene185    83.0  0.920361  1.077692  0.0506   5.4117
gene186    83.0  0.417863  0.267233  0.0790   1.6202
gene187    83.0  2.837000  4.382373  0.0183  19.2571
gene188    83.0  0.551542  0.452365  0.0649   2.6960
gene189    83.0  1.091576  0.977322  0.0630   4.0711
gene190    83.0  0.376251  0.345899  0.0320   2.4104
gene191    83.0  0.301343  0.182988  0.0242   0.9570
gene192    83.0  0.616130  0.771116  0.0078   3.4041
gene193    83.0  0.451342  0.442828  0.0059   2.6259
gene194    83.0  0.580066  0.429296  0.0143   2.0847
gene195    83.0  0.447367  0.375826  0.0377   1.7385
gene196    83.0  0.835730  0.478942  0.2064   3.0538
gene197    83.0  0.164860  0.109016  0.0182   0.5371
gene198    83.0  0.528741  1.287199  0.0343  11.5904
gene199    83.0  0.455423  0.332236  0.0771   1.9417
gene200    83.0  0.921228  1.034249  0.0411   4.0977
gene201    83.0  0.514806  0.562228  0.0364   3.5314
gene202    83.0  4.446545  1.970530  0.1543  10.1571
gene203    83.0  0.482299  0.305602  0.0703   1.2865
gene204    83.0  0.399836  0.364126  0.0639   2.5057
gene205    83.0  1.676111  0.987167  0.1217   3.9726
gene206    83.0  1.297617  0.680051  0.2986   3.6205
gene207    83.0  1.132337  0.645449  0.2273   3.0237
gene208    83.0  0.565012  0.267864  0.1458   1.7096
gene209    83.0  0.532545  0.343679  0.0583   1.4887
gene210    83.0  0.336525  0.214663  0.0360   0.9195
gene211    83.0  0.810745  0.380538  0.1874   2.5928
gene212    83.0  0.854088  0.580492  0.1479   3.8762
gene213    83.0  0.480318  0.266569  0.0297   1.2532
gene214    83.0  2.565464  1.113837  0.7999   5.6895
gene215    83.0  2.273693  0.996674  0.2887   5.2998
gene216    83.0  0.544190  0.390634  0.0910   2.5288
gene217    83.0  0.368412  0.428114  0.0426   2.6518
gene218    83.0  2.736264  1.427398  0.0612   9.6952
gene219    83.0  0.279798  0.220807  0.0351   1.0897
gene220    83.0  0.436271  1.380662  0.0234   9.0043
gene221    83.0  0.697175  0.321547  0.0493   1.5628
gene222    83.0  0.752677  0.422278  0.1635   1.9924
gene223    83.0  0.694899  0.377244  0.0514   2.0486
gene224    83.0  0.265040  0.299690  0.0343   1.6982
gene225    83.0  0.434898  0.377853  0.0638   2.2382
gene226    83.0  0.606478  0.324934  0.0973   1.5813
gene227    83.0  0.307282  0.151872  0.0766   0.7124
gene228    83.0  0.589345  0.429370  0.0852   2.0479
gene229    83.0  0.338305  0.202502  0.0480   1.1610
gene230    83.0  1.095280  0.951935  0.0988   4.4664
gene231    83.0  0.517672  0.649593  0.0518   2.6505
gene232    83.0  0.743439  0.861487  0.1014   6.1929
gene233    83.0  0.159808  0.072336  0.0421   0.4173
gene234    83.0  0.335001  0.380835  0.0109   2.0989
gene235    83.0  1.238553  1.624711  0.0495   7.2540
gene236    83.0  0.870504  0.980718  0.0603   4.6866
gene237    83.0  0.508461  0.411924  0.0954   3.1936
gene238    83.0  0.310602  0.192799  0.0727   1.2087
gene239    83.0  0.976004  0.458502  0.2345   2.5457
gene240    83.0  0.409536  0.212515  0.0672   1.2886
gene241    83.0  2.241578  0.979039  0.7700   6.6650
gene242    83.0  0.314214  0.155968  0.0622   0.8289
gene243    83.0  0.315525  0.154037  0.0494   0.9387
gene244    83.0  0.487566  0.376186  0.0856   2.3035
gene245    83.0  1.579265  0.713002  0.1888   4.2636
gene246    83.0  1.677437  2.023229  0.0820   8.2508
gene247    83.0  0.695392  0.647321  0.0706   4.6900
gene248    83.0  0.771093  0.436687  0.0796   2.2643
gene249    83.0  0.595154  0.370153  0.0559   2.4455
gene250    83.0  1.037677  0.659298  0.0440   2.9905
gene251    83.0  1.220352  1.221167  0.0398   5.4096
gene252    83.0  3.790075  1.698160  0.7188   9.4978
gene253    83.0  0.484836  0.309779  0.1132   1.4128
gene254    83.0  3.023446  2.077840  0.5742  15.4487
gene255    83.0  0.565401  0.668399  0.0439   3.2082
gene256    83.0  0.917614  0.792436  0.0943   3.7013
gene257    83.0  0.639524  0.615208  0.0710   3.3752
gene258    83.0  0.194647  0.203329  0.0099   1.3401
gene259    83.0  0.214399  0.120026  0.0398   0.8183
gene260    83.0  1.539607  0.711954  0.2243   3.5602
gene261    83.0  2.545842  1.647438  0.3482   6.5588
gene262    83.0  0.765070  0.351622  0.2772   2.2446
gene263    83.0  0.661369  0.369628  0.0686   1.6213
gene264    83.0  0.320899  0.223853  0.0165   1.2213
gene265    83.0  0.347061  0.215216  0.0541   1.7006
gene266    83.0  1.795445  1.355628  0.1168   5.4582
gene267    83.0  0.469513  0.497999  0.0335   3.2579
gene268    83.0  0.565189  0.306149  0.1200   1.4325
gene269    83.0  0.237075  0.131769  0.0413   0.6855
gene270    83.0  0.945117  0.422042  0.2395   2.0601
gene271    83.0  0.275929  0.166298  0.0685   1.0373
gene272    83.0  1.918004  1.514231  0.1754   6.8813
gene273    83.0  1.154486  0.666831  0.2636   3.5324
gene274    83.0  1.132999  1.034464  0.0363   4.5558
gene275    83.0  0.372000  0.194720  0.0708   1.0211
gene276    83.0  2.385657  2.657227  0.0600  16.9335
gene277    83.0  0.494489  0.250503  0.1766   1.3937
gene278    83.0  1.182736  0.661547  0.1238   3.3369
gene279    83.0  0.562449  0.315276  0.0875   2.3030
gene280    83.0  0.637546  0.443054  0.0109   2.6071
gene281    83.0  1.531287  1.501253  0.0826   8.4621
gene282    83.0  0.710647  0.429773  0.0511   1.5608
gene283    83.0  0.558812  0.283148  0.1386   1.2611
gene284    83.0  0.150018  0.075630  0.0254   0.3857
gene285    83.0  1.652687  0.774241  0.4861   4.2255
gene286    83.0  1.282755  1.179360  0.0941   6.0053
gene287    83.0  2.543629  1.123307  0.4975   6.2357
gene288    83.0  0.277890  0.132763  0.0882   0.8289
gene289    83.0  1.093527  1.644564  0.1056  13.6524
gene290    83.0  0.321639  0.227220  0.0812   0.9458
gene291    83.0  1.089927  0.566074  0.2655   3.1326
gene292    83.0  5.629224  2.416679  2.0654  15.4885
gene293    83.0  0.848866  0.407684  0.0920   1.7147
gene294    83.0  2.633043  1.610390  0.4362   6.4905
gene295    83.0  0.969214  0.803573  0.0675   3.7655
gene296    83.0  1.258042  0.719002  0.1706   4.1895
gene297    83.0  2.155720  1.049279  0.2505   4.7697
gene298    83.0  2.318976  1.287095  0.0898   5.7075
gene299    83.0  0.353102  0.273075  0.0083   1.4715
gene300    83.0  0.271155  0.228411  0.0369   1.3380
gene301    83.0  1.206135  0.662960  0.1179   3.3505
gene302    83.0  2.977408  1.662291  0.6630   8.2369
gene303    83.0  0.365037  0.434088  0.0379   2.5610
gene304    83.0  1.066955  0.413766  0.2903   2.0812
gene305    83.0  0.523372  0.262030  0.0113   1.3655
gene306    83.0  0.748216  0.372690  0.0591   1.5158
gene307    83.0  0.221975  0.109706  0.0193   0.6876
gene308    83.0  1.577427  1.352417  0.1413   8.0438
gene309    83.0  0.497698  0.296411  0.0855   1.8571
gene310    83.0  0.491236  0.357370  0.0787   1.7717
gene311    83.0  0.144143  0.093452  0.0126   0.5993
gene312    83.0  0.453027  0.381296  0.0289   1.6642
gene313    83.0  0.344045  0.176575  0.0567   0.8317
gene314    83.0  0.887220  0.615284  0.1153   3.3825
gene315    83.0  0.448422  0.286002  0.0390   1.6415
gene316    83.0  1.196246  0.752478  0.1297   4.8720
gene317    83.0  2.057716  0.961081  0.6446   5.1549
gene318    83.0  1.776501  0.737902  0.7489   6.2016
gene319    83.0  0.599399  0.311605  0.1675   1.4064
gene320    83.0  1.223845  0.642129  0.2168   3.3711
gene321    83.0  0.700682  0.513260  0.0986   2.9758
gene322    83.0  0.242060  0.198390  0.0335   1.2569
gene323    83.0  0.390252  0.388132  0.0542   2.4155
gene324    83.0  0.372906  0.214721  0.0439   1.0177
gene325    83.0  0.479690  0.403186  0.0978   2.3771
gene326    83.0  1.663834  1.565238  0.1683   8.5009
gene327    83.0  0.468163  0.276243  0.1062   2.0798
gene328    83.0  0.230717  0.171878  0.0126   1.1923
gene329    83.0  4.264910  2.136223  1.3849  13.1366
gene330    83.0  3.933987  1.781168  0.2580   9.6434
gene331    83.0  4.364317  1.807220  0.4980   9.0738
gene332    83.0  0.678373  0.549611  0.1334   3.0528
gene333    83.0  0.455249  0.389148  0.0289   1.7197
gene334    83.0  4.675640  2.230134  1.4414  11.8656
gene335    83.0  0.554642  0.660495  0.0597   3.6351
gene336    83.0  1.800470  1.205363  0.1840   6.0020
gene337    83.0  0.831133  0.395186  0.1888   2.2907
gene338    83.0  0.423380  0.424565  0.0327   2.6209
gene339    83.0  0.320302  0.154827  0.0832   0.8345
gene340    83.0  0.541581  0.304535  0.0978   1.7425
gene341    83.0  1.061033  0.683819  0.1043   4.6308
gene342    83.0  1.862847  0.753126  0.6298   3.7111
gene343    83.0  1.387853  0.632535  0.4035   3.2455
gene344    83.0  0.839467  0.556914  0.1100   2.8626
gene345    83.0  2.236523  1.481158  0.4915   8.8383
gene346    83.0  1.884877  0.899105  0.4774   4.9744
gene347    83.0  5.084123  2.304784  1.0853  15.2423
gene348    83.0  1.197334  2.064375  0.1018  17.8767
gene349    83.0  1.124376  1.376332  0.2067  12.7848
gene350    83.0  0.374780  0.387126  0.0263   2.5266
gene351    83.0  0.729975  0.449349  0.0733   3.0444
gene352    83.0  0.839088  0.855862  0.0287   4.2884
gene353    83.0  2.466589  1.017329  0.1763   5.6551
gene354    83.0  0.356400  0.339605  0.0402   1.6224
gene355    83.0  4.127212  2.056717  0.8410  16.3197
gene356    83.0  0.705519  0.261569  0.2127   1.5603
gene357    83.0  0.160859  0.100638  0.0168   0.4900
gene358    83.0  0.274401  0.172193  0.0271   0.8876
gene359    83.0  0.248964  0.220898  0.0301   1.5970
gene360    83.0  3.856493  1.852835  1.2878  11.0558
gene361    83.0  1.428598  0.614509  0.5029   3.1174
gene362    83.0  0.809798  0.673010  0.1670   3.3564
gene363    83.0  0.289128  0.158213  0.0563   0.8593
gene364    83.0  3.050508  2.126965  0.0781   9.6595
gene365    83.0  0.511678  0.414895  0.0707   2.0281
gene366    83.0  0.513517  0.237651  0.1428   1.1028
gene367    83.0  0.285014  0.123633  0.1129   0.6996
gene368    83.0  0.837064  0.982147  0.0463   4.1744
gene369    83.0  0.802886  0.572990  0.0439   2.6419
gene370    83.0  0.915673  0.769668  0.1687   4.1877
gene371    83.0  0.688423  0.886723  0.1593   5.8807
gene372    83.0  0.854445  0.464911  0.1625   2.3444
gene373    83.0  1.097165  0.979465  0.0271   5.1686
gene374    83.0  0.826507  0.431206  0.2379   2.0451
gene375    83.0  0.501207  0.461976  0.0141   3.1132
gene376    83.0  0.509759  0.383698  0.1092   1.9923

In [16]:
# Categorical Feature Statistics
cat_stats

                value  count    pct
column     rank
CancerType 1      EWS     29  34.94
           2      RMS     25  30.12
           3       NB     18  21.69
           4       BL     11  13.25

In [17]:
# Target Distribution
target_df

            count    pct
CancerType
EWS            29  34.94
RMS            25  30.12
NB             18  21.69
BL             11  13.25

## Task Curation

In [18]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=20, n_splits=3, test_size=None

In [19]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [20]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019cfbce-1521-7263-894a-710ac5ce15e4
1a6d615508a1562dfabb9709c9680f9671815e7a4070d2329212a7f70823055c