### Dataset and Task Metadata

In [31]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="clock_protein_toxicity",
    dataset_year="2021",
    domain_str="biology & life sciences",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://archive.ics.uci.edu/static/public/728/toxicity-2.zip",
    download_description="""
We download the data from the UCI repository and uzip it to a predefined folder. 

mkdir -p local-data-warehouse/clock_protein_toxicity && wget -P local-data-warehouse/clock_protein_toxicity/ https://archive.ics.uci.edu/static/public/728/toxicity-2.zip && unzip local-data-warehouse/clock_protein_toxicity/toxicity-2.zip -d local-data-warehouse/clock_protein_toxicity/ && rm local-data-warehouse/clock_protein_toxicity/toxicity-2.zip
""",
    # References
    academic_reference_bibtex="""@article{Gul2021StructureBasedDC,
  title={Structure-based design and classifications of small molecules regulating the circadian rhythm period},
  author={Sadia Gul and Fatima Rahim and Selen Isin and others},
  journal={Scientific Reports},
  year={2021},
  volume={11},
  pages={18510},
  doi={10.1038/s41598-021-97962-5},
  url={https://doi.org/10.1038/s41598-021-97962-5}
}
""",
    academic_reference_bibtex_key="Gul2021StructureBasedDC",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
    - We remove duplicated columns but keep the first occurance.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Toxic",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="Toxic",
)

## Preprocessing

In [32]:
import pandas as pd

df = pd.read_csv(dataset_mold.path / "data.csv")

target_feature = "Toxic"
df = df.rename(columns={"Class": target_feature})
df[target_feature] = df[target_feature].map({"Toxic": "Yes", "NonToxic": "No"}).astype("category")

duplicated_mask = df.T.duplicated(keep='first')
df = df.drop(columns = df.columns[duplicated_mask])

print("Loaded data shape:", df.shape)

Loaded data shape: (171, 1112)

In [33]:
# Use if needed to get see all cols of pandas dataframes
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
df.head()

,MATS3v,nHBint10,MATS3s,MATS3p,nHBDon_Lipinski,minHBint8,MATS3e,MATS3c,minHBint2,MATS3m,minHBint6,minHBint7,minHBint4,MATS3i,VR3_Dt,SpMax8_Bhi,SdsN,SpMax8_Bhm,SpMax8_Bhe,ECCEN,MDEC-14,SpMax8_Bhs,SpMax8_Bhp,SpMax8_Bhv,MDEC-11,MDEC-12,MDEC-13,VR2_Dt,BIC5,ATS7s,ATS7p,ATS7v,ATS7i,ATS7m,ATS7e,mintN,nHsNH2,khs.sssCH,minHBint3,maxdssC,nT6Ring,minHBint5,nF8Ring,minssCH2,SpMax_DzZ,ETA_EtaP,nHsOH,SpMin1_Bhe,maxHother,nHBAcc_Lipinski,StN,khs.aaS,khs.aaO,khs.aaN,Sare,SHAvin,SpMax3_Bhv,SpMax3_Bhp,SpMax3_Bhs,SpMax3_Bhe,SpMin6_Bhi,SpMax3_Bhm,SpMax3_Bhi,ETA_EtaP_F_L,mindCH2,AATSC2e,AATSC2c,AATSC2m,AATSC2i,nsBr,AATS5p,AATSC2v,AATSC2p,AATSC2s,VABC,maxdNH,khs.ddsN,RotBtFrac,ATS4e,ATS4m,nFRing,ATS4i,ATS4s,ATS4p,ETA_Alpha,khs.sssN,EE_Dzi,MAXDN,EE_Dzm,EE_Dze,EE_Dzs,EE_Dzp,EE_Dzv,ATS8e,maxsOH,minssssNp,maxsOm,MDEC-23,MDEC-22,MDEC-24,nFG12HeteroRing,ATS8s,ATS8v,SP-6,SP-7,SHsNH2,SP-5,SP-2,SP-3,SP-0,SP-1,minHsOH,ATSC8v,MATS2v,ATSC8s,MATS2p,MATS2s,ATSC8p,MATS2e,ATSC8e,ATSC8c,MATS2c,MATS2m,topoDiameter,ATSC8m,MATS2i,ATSC8i,ntN,khs.ssCH2,SpAD_Dt,ETA_Eta_R_L,SHdsCH,SaasN,SC-4,SaasC,minaaCH,AATSC3c,AATSC3e,AATSC3i,AATSC3m,AATSC3s,AATSC3p,AATSC3v,SpMax2_Bhp,AATS8e,AATS8i,AATS8m,AATS8s,AATS8p,AATS8v,VE3_Dt,XLogP,SpMax2_Bhi,maxssCH2,minaaS,SpMax4_Bhv,SpMax4_Bhs,SpMax4_Bhp,SpMax4_Bhm,minHaaNH,SpMax4_Bhi,minaaN,SpMax4_Bhe,StsC,SssCH2,maxHdNH,MATS1p,R_TpiPCTPC,MATS1s,MATS1v,JGI10,MATS1c,MATS1e,VR2_DzZ,MATS1i,MATS1m,MDEC-34,MDEC-33,VR2_Dze,VR2_Dzm,VR2_Dzs,VR2_Dzp,khs.ssssC,nTG12Ring,khs.ssssN,ATS5e,gmin,VR2_D,ATS5m,ATS5p,ATS5s,ATS5v,AATSC5p,TpiPC,maxsCH3,SdS,khs.ssO,ETA_Eta_F_L,khs.ssS,SdO,VE2_Dt,maxHtCH,ETA_dEpsilon_B,ETA_dEpsilon_A,ETA_dEpsilon_D,SsNH2,StCH,SsCH3,CIC5,CIC4,CIC1,CIC0,CIC3,CIC2,nF10HeteroRing,maxssO,WPOL,n5HeteroRing,maxHAvin,fragC,ETA_Eta_B_RC,AATS7m,SpDiam_Dt,SdssC,ETA_Epsilon_3,AATS7i,AATS7e,nT9Ring,minsCl,AATS7v,AATS7s,AATS7p,nHdCH2,ETA_Epsilon_5,ETA_Epsilon_4,SsssCH,maxHsOH,GATS1v,maxaaaC,GATS1s,minsNH2,BIC4,SpMin7_Bhs,SpMin7_Bhp,SpMin7_Bhv,nHtCH,GATS1e,mintsC,GATS1c,SpMin7_Bhm,GATS1m,SpMin7_Bhe,GATS1i,maxtsC,minHAvin,MDEC-44,AATS2v,SPC-6,SPC-4,SPC-5,SpAD_D,MATS6c,ETA_BetaP_s,minaasC,minaasN,minssNH,nT7HeteroRing,RotBFrac,nF10Ring,ETA_BetaP_ns,nH,nL,nN,nO,nA,nC,nF,nX,nQ,nS,nV,ATS1m,mindsN,SHCsats,SHCsatu,CrippenMR,GATS1p,SRW10,ETA_dPsi_A,AATS6m,AATS6i,AATS6e,minsBr,nF9HeteroRing,SpMin7_Bhi,AATS6v,AATS6p,AATS6s,naAromAtom,nBase,minHBint10,SpDiam_DzZ,SaaNH,khs.dNH,maxaaN,maxaaO,SpDiam_Dzv,SpDiam_Dzs,SpDiam_Dzp,SpDiam_Dze,SpDiam_Dzm,GATS6i,SpDiam_Dzi,Mi,Mv,Mp,GGI10,bpol,MW,GATS6v,MATS7s,MATS7p,C1SP1,MATS7v,MATS7i,MATS7m,MATS7c,GATS6s,MATS7e,maxtN,SpMin8_Bhe,SpMin8_Bhi,SpMin8_Bhm,SpMin8_Bhp,SpMin8_Bhs,SpMin8_Bhv,maxHCsatu,maxHCsats,ATSC3v,ATSC3s,ATSC3p,minHdCH2,ATSC3e,ATSC3c,maxssNH,ATSC3m,ATSC3i,minHCsatu,minHCsats,SpMax7_Bhe,SpMax7_Bhi,SpMax7_Bhm,ETA_BetaP_ns_d,SpMax7_Bhp,SpMax7_Bhs,SpMax7_Bhv,SdsCH,minssO,minssS,SpMin3_Bhe,SpMin3_Bhm,SpMin3_Bhi,SpMin3_Bhv,SpMin3_Bhs,SpMin3_Bhp,TPC,VP-5,VP-4,VP-7,VP-6,VP-1,VP-0,VP-3,VP-2,MIC5,MIC4,MIC3,MIC2,MIC1,MIC0,ATSC5p,piPC10,ATSC5s,minsOm,nHBa,nHBd,SddssS,nCl,minsOH,SHaaCH,nHBDon,nF11HeteroRing,AATS5i,AATS5m,SpMin6_Bhs,SpMin6_Bhp,SpMin6_Bhv,AATS5e,ETA_dBeta,khs.sCH3,ALogP,SpMin6_Bhm,BCUTp-1l,AATS5s,BCUTp-1h,AATS5v,SpMin6_Bhe,ATS8i,ATS8m,BCUTw-1h,BCUTw-1l,nBondsS3,nBondsS2,ATS8p,GATS3p,GATS3s,GATS3v,GATS3c,GATS3e,SC-5,GATS3i,SC-6,GATS3m,SC-3,minsCH3,SssssC,nAtomLC,nT12HeteroRing,minHaaCH,MLFER_BH,MLFER_BO,SaaaC,mindsCH,nddssS,maxaasC,maxsssN,MATS6p,MATS6s,MATS6v,MATS6i,MATS6m,MATS6e,ETA_Beta_ns_d,hmax,ETA_Beta_s,nHaaCH,khs.aaaC,ETA_AlphaP,nAromBond,ATSC2v,ATSC2p,ATSC2s,ATS4v,ATSC2e,ATSC2c,ATSC2m,ATSC2i,AATS4v,AATS4s,AATS4p,AATS4e,ETA_BetaP,AATS4m,AATS4i,SHsOH,SpMax_D,MDEN-13,MDEN-12,MDEN-11,ATS3m,PetitjeanNumber,khs.aasN,khs.aasC,MWC10,MPC7,TWC,topoRadius,WPATH,nG,ndsN,MAXDP,naaaC,SM1_DzZ,SpAbs_DzZ,SpAbs_Dze,khs.aaNH,SpAbs_Dzm,SM1_Dzv,SpAbs_Dzi,SM1_Dzp,SM1_Dzs,SM1_Dzm,SpAbs_Dzv,SM1_Dzi,SpAbs_Dzp,SpAbs_Dzs,SM1_Dze,maxaaCH,maxdO,nF11Ring,GATS2v,GATS2s,ETA_Beta,GATS2m,GATS2i,GATS2e,GATS2c,nHaaNH,ATSC1p,ATSC1s,ATSC1v,ATSC1c,ATSC1e,ATSC1i,ATSC1m,MWC9,MWC8,MWC5,MWC4,MWC7,MWC6,ndssC,MWC2,MAXDN2,MATS5e,SpMin2_Bhe,MATS5c,MATS5m,SpMin2_Bhm,MATS5i,SpMin2_Bhi,SpMin2_Bhv,MATS5v,MATS5p,SpMin2_Bhs,SpMin2_Bhp,VE1_Dzi,Mare,BCUTc-1l,BCUTc-1h,SssNH,MPC9,VE1_Dzp,naaN,SHBd,TSRW,SHBa,khs.ssNH,SpMax6_Bhp,SpMax6_Bhs,SpMAD_Dzv,SpMax6_Bhv,SpMax6_Bhe,SpMAD_Dze,SpMax6_Bhi,SpMAD_Dzi,SpMax6_Bhm,SpMAD_Dzm,SpMAD_DzZ,AATSC8s,AATSC8p,AATSC8v,minHssNH,AATSC8c,AATSC8e,AATSC8i,AATSC8m,AATS3s,AATS3p,AATS3v,SpMin5_Bhv,SpMin5_Bhp,SpMin5_Bhs,SpMin5_Bhm,SpMin5_Bhi,AATS3e,SpMin5_Bhe,AATS3i,SpMAD_Dzs,AATS3m,MLFER_L,GATS5s,GATS5p,GATS5v,MLFER_A,GATS5i,GATS5m,IC3,IC2,IC1,IC0,IC5,IC4,ETA_Eta_R,ETA_Eta_L,ETA_Eta_B,ETA_Eta_F,SaaCH,nAcid,maxsssCH,SsCl,nF6Ring,maxsF,MATS4c,MATS4e,MATS4i,SP-4,MATS4m,MATS4s,MATS4p,MATS4v,VC-6,SsssN,minaaaC,minwHBa,nT6HeteroRing,khs.dssC,AATSC0m,EE_Dt,minsF,ATSC0v,ATSC0s,ATSC0p,ATSC0m,ATSC0i,ATSC0e,ATSC0c,VE2_D,SpMAD_D,nHBint2,nHBint3,ETA_Epsilon_1,nHBint6,nHBint7,nHBint4,nHBint5,nHBint8,nHBint9,nBondsS,AATS2p,AATS2s,AATS2e,nBondsD,AATS2i,AATS2m,nBondsM,nBonds2,MDEN-33,Sp,Sv,Si,FMF,nRotB,minssssC,SwHBa,Zagreb,SRW6,SRW7,SRW4,SRW5,SRW2,SRW8,SRW9,maxHsNH2,SCH-5,SCH-6,SCH-7,ATS6p,maxaasN,MAXDP2,VE1_DzZ,VE1_Dze,GATS4p,GATS4s,VE1_Dzm,GATS4v,GATS4i,VE1_Dzs,GATS4m,ndsCH,VE1_Dzv,GATS4c,GATS4e,ETA_Beta_ns,McGowan_Volume,n5Ring,ETA_dAlpha_B,ATSC7s,ATSC7p,ETA_dAlpha_A,ATSC7v,ATSC7i,ATSC7m,ATSC7c,VC-4,VC-5,VC-3,ATSC7e,JGI2,JGI3,JGI1,JGI6,JGI7,JGI4,JGI5,JGI8,JGI9,SpAD_DzZ,SpAD_Dze,SpAD_Dzm,SpAD_Dzi,SpAD_Dzv,SpAD_Dzp,SpAD_Dzs,nBonds,LipinskiFailures,SpDiam_D,minHdsCH,SssO,C2SP3,C2SP2,GATS2p,ETA_Shape_X,ETA_Shape_Y,ETA_Shape_P,AVP-5,AVP-4,AVP-7,AVP-1,AVP-0,AVP-2,AATS1v,AATS1p,AATS1s,AATS1m,MDEN-22,AATS1i,AATS1e,maxaaNH,GATS7c,GATS7m,GATS7v,GATS7p,GATS7s,SsOm,SsOH,AATSC4v,maxHBd,AATSC4s,maxHBa,SHssNH,AATSC4e,AATSC4c,AATSC4m,AATSC4i,SHBint10,ATS2v,ATS2p,ATS2s,CrippenLogP,ATS2i,JGT,MPC10,VAdjMat,ATSC6p,ATSC6s,ATSC6v,ATSC6i,ATSC6m,ATSC6c,ATSC6e,SpMin1_Bhi,SpMin1_Bhm,SpMin1_Bhp,SpMin1_Bhs,SpMin1_Bhv,SHother,AATS0s,SpMin4_Bhv,AATS0p,SpMin4_Bhp,AATS0v,SpMin4_Bhs,SpMin4_Bhm,AATS0i,SpMin4_Bhi,AATS0m,minsssCH,SpMin4_Bhe,nAtomLAC,AATS0e,MWC3,ATSC5v,MLFER_S,ETA_dBetaP,AATSC4p,nRotBt,SHaaNH,AATSC5v,AATSC5s,AATSC5e,naasN,AATSC5c,AATSC5m,SpMax_Dt,AATSC5i,naasC,VR3_D,VR1_D,VR1_Dt,ETA_Epsilon_2,MLogP,nHBAcc2,nHBAcc3,AMR,AMW,GATS6c,sumI,GATS6e,gmax,maxHssNH,MATS5s,GATS6m,maxHBint8,maxHBint9,GATS6p,C1SP2,C1SP3,maxHBint2,maxHBint3,maxHBint4,maxHBint5,maxHBint6,maxHBint7,AVP-6,ATSC5e,C4SP3,AVP-3,ATSC5c,ATSC5m,nHother,ATSC5i,VCH-5,VCH-7,VCH-6,Mse,DELS2,MATS8m,ATS3v,ATS3s,ATS3p,ATS3e,MATS8i,Kier2,Kier3,Kier1,HybRatio,ATS3i,MDEN-23,SHBint9,SHBint8,SHBint3,SHBint2,SHBint7,SHBint6,SHBint5,SHBint4,DELS,nHeteroRing,GATS7e,ETA_Psi_1,mindssC,nwHBa,maxHBint10,GATS7i,nAtom,Spe,khs.dS,khs.dO,maxwHBa,AATSC6p,AATSC6s,AATSC6v,AATSC6c,AATSC6e,AATSC6i,AATSC6m,SssssNp,AATSC7c,ASP-2,ASP-3,ASP-0,ASP-1,ASP-6,ASP-7,ASP-4,ASP-5,ATS0s,MATS8v,ATS0p,MATS8s,ATS0v,MATS8p,MATS8e,MATS8c,ATS0e,ATS0i,ATS0m,GGI9,GGI8,GGI1,GGI3,GGI2,GGI5,GGI4,GGI7,GGI6,nTRing,TIC0,TIC1,TIC2,TIC3,TIC4,TIC5,ZMIC4,ZMIC5,ZMIC0,ZMIC1,ZMIC2,ZMIC3,minHother,ATSC4c,ATSC4e,ATSC4i,ATSC4m,ATSC4s,ATSC4p,ATSC4v,SpMax1_Bhs,SpMax1_Bhp,SpMax1_Bhv,hmin,SpMax1_Bhe,SpMax1_Bhi,SpMax1_Bhm,MPC6,nAtomP,MPC4,MPC5,MPC2,VR3_Dzv,VR3_Dzs,MPC8,VR3_Dzp,VR3_Dzm,SpMAD_Dzp,VR3_Dzi,VR3_Dze,SsF,minaaO,VR3_DzZ,mintCH,Sse,C3SP2,VR1_DzZ,VR1_Dzp,VR1_Dzs,SHtCH,VR1_Dzi,VR1_Dzm,VR1_Dze,maxdsN,AATSC7v,AATSC7s,AATSC7p,AATSC7m,AATSC7i,AATSC7e,BIC2,BIC3,BIC0,BIC1,SIC5,SIC4,SIC1,SIC0,SIC3,SIC2,minHBd,minHBa,AATSC1p,AATSC0i,ALogp2,AATSC1i,SaaO,SaaN,GATS8m,SpMax2_Bhv,GATS8i,SpMax2_Bhs,GATS8e,GATS8c,SpMax2_Bhe,SpMax2_Bhm,GATS8v,GATS8p,GATS8s,piPC3,piPC2,piPC1,piPC7,piPC6,piPC5,piPC4,piPC9,piPC8,maxHdsCH,ATS1v,ATS1p,ATS1s,ATS1i,SpMAD_Dt,ATS1e,VR2_Dzi,MPC3,ATS2e,VR2_Dzv,minHBint9,VE2_Dzs,VE2_Dzp,VE2_Dzv,ATS2m,VE2_Dzi,VE2_Dzm,VE2_Dze,VE2_DzZ,nHAvin,meanI,nHCsatu,nHCsats,apol,ATS5i,nF12Ring,mindO,MolIP,maxdsCH,TopoPSA,ETA_EtaP_B_RC,MDEO-11,MDEO-12,AATSC0s,SpMax5_Bhv,AATSC0p,SpMax5_Bhs,AATSC0v,SpMax5_Bhp,SpMax5_Bhm,SpMax5_Bhi,AATSC0c,SpMax5_Bhe,AATSC0e,VE3_DzZ,C3SP3,VE3_Dzv,minddssS,ATS6s,VE3_Dzs,VE3_Dzp,ATS6v,ATS6i,VE3_Dzm,ATS6m,VE3_Dzi,VE3_Dze,ATS6e,VPC-6,VPC-5,VPC-4,MLFER_E,nBondsD2,Mpe,nHeavyAtom,nRing,GATS5c,GATS5e,VR1_Dzv,minsssN,topoShape,VE1_Dt,maxHaaCH,nHBAcc,VE3_D,VE1_D,AATSC1s,AATSC1v,AATSC1m,AATSC1c,AATSC1e,LipoaffinityIndex,n6Ring,ETA_Eta,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,ETA_EtaP_L,ETA_EtaP_F,ETA_EtaP_B,ETA_dEpsilon_C,MDEO-22,Toxic
0,0.0908,0,0.0075,0.0173,0,0.0,-0.0436,0.0409,0.0,0.1368,0.0,0.0000,0.0,-0.0574,31.8800,3.3540,0.0000,3.2664,3.3158,1422,0.0,3.8373,3.2044,3.2128,0.0000,0.0000,0.0000,22.2380,0.8435,768.4444,275.1928,41003.7141,24110.8860,15270.4651,1277.0737,0.0000,0,0,0.0,0.0000,0,0.0,0,0.000,201.0744,0.8169,0,2.2798,0.0000,8,0.0000,0,0,0,60.832,0.0000,3.9710,3.9582,4.6723,4.0541,1.5761,4.0396,4.0792,0.3114,0.0,0.0076,0.0007,0.6986,0.0196,0,1.9081,-0.8911,-0.0033,-0.0255,451.4722,0.0,0,0.0000,1453.5938,19835.8193,0,26862.1417,759.7778,347.5541,21.9333,0,198.0675,0.0000,201.0915,201.1842,213.9751,232.9974,222.2215,1094.3304,0.0000,0.0,0.0000,60.1757,13.9880,0.0,0,554.0000,35648.5015,18.2418,16.2633,0.0,20.9413,22.2081,22.3620,30.3248,22.5080,0.0000,237.1491,-0.0231,-0.6667,-0.0166,-0.0129,-0.2969,0.1073,0.0573,0.1053,0.0481,0.0281,17,384.1820,0.0129,-13.8718,0,0,3444.0152,22.5079,0.0000,0.0000,0.0,0.0000,0.0000,0.0006,-0.0031,-0.0868,3.4021,0.0149,0.0034,3.5086,4.1095,7.8166,149.5621,92.9158,3.9571,1.7139,254.6322,-167.1241,-0.094,4.2285,0.000,0.0,3.8192,4.6641,3.8195,3.8311,0.0,3.8758,0.0000,3.8599,0.0000,0.000,0.0,0.0049,20.3566,-0.0388,0.0255,0.0063,-0.4760,-0.0226,25.3775,-0.0816,0.0440,0.0,0.0000,25.3702,25.3764,43.3885,24.5288,0,0,0,1408.5019,0.0000,34.7634,18932.5551,339.6464,734.3333,51592.2938,-0.0198,12.0215,0.0000,0.0,0,14.3222,0,0.0000,0.0000,0.0,0.1391,0.2258,0.0000,0.0,0.0,0.0000,0.3333,0.3000,3.0318,4.4787,0.8667,2.0135,0,0.000,116,0,0.0000,1179.08,1.4381,94.8476,1814.8151,0.0000,0.4586,149.7571,7.9321,0,0.0,254.6815,4.7729,1.7093,0,0.8015,0.5454,0.0000,0.0000,0.6341,0.0000,0.4793,0.0,0.8486,1.3331,1.4748,1.4774,0,0.5505,0.0000,1.2841,1.4670,0.5007,1.3636,0.9429,0.0000,0.000,0.0,328.8105,39.5531,11.4364,22.4183,581.0425,-0.0902,0.6957,0.0000,0.0000,0.0,0,0.0000,0,0.9565,14,0,4,4,0,38,0,0,0,0,0,8823.8932,0.0000,0.0000,0.0000,0.0000,0.7123,11.4843,0.1194,101.4081,146.8943,7.9652,0.0,0,1.3448,270.7278,1.7912,4.6957,38,-1,0.0,296.0059,0.0,0,0.0000,0.0000,322.7435,319.6259,336.0904,296.1456,296.0272,1.0554,292.0703,7.2942,0.7947,0.8024,0.3406,25.7369,590.1015,1.0713,0.1647,0.0333,0,-0.0006,-0.0066,0.0473,0.1148,1.3061,0.2220,0.0000,1.3061,1.2720,1.3491,1.4567,1.3022,1.4359,0.0000,0.0000,575.4060,2.4444,0.5603,0.0,-0.5069,0.0919,0.0,557.9458,-14.2345,0.0000,0.0000,3.4009,3.4171,3.3582,0.0000,3.3048,3.9738,3.3124,0.0000,0.000,0.0,1.8776,1.9542,1.8540,1.9645,1.8650,1.9655,8169,6.8704,8.4524,3.7561,4.9553,14.9333,23.5048,10.2643,12.3024,54.9937,55.3273,51.3250,43.2973,30.8117,13.3151,-3.5162,11.3293,-36.3333,0.0000,0,0,0.0,0,0.0000,0.0000,0,0,145.1083,106.3627,1.5355,1.6851,1.6695,7.9129,12.00,0,0.0000,1.6425,6.0583,4.1255,12.9486,289.8443,1.5809,20938.6998,13008.2055,15.9980,11.8500,8,22,239.9415,0.8415,0.7303,0.7413,0.9107,0.8248,1.5764,0.9982,0.0,0.6471,3.6250,0.0000,0.0,0,0,0.0000,0.000,0.000,0.0000,0.0000,0,0.0000,0.0000,-0.1490,0.0338,-0.1505,-0.1327,-0.0799,0.0522,0.0,0.0000,32.00,0,0,0.4768,45,-108.7165,-0.3998,-3.1111,53189.5532,0.9281,0.0803,85.2306,2.3875,292.2503,4.1746,1.9096,7.9868,1.6522,108.9880,147.5942,0.0000,290.5212,0.0000,0.0000,0.0000,18480.9749,0.4706,0,0,13.6498,863,190.0101,9,6433,0,0,0.0000,0,1.5714,407.0386,407.2647,0,407.0756,-2.8733,401.3850,-6.4019,3.7003,1.5671,453.4003,1.5935,478.6676,436.9364,1.5550,0.0000,0.0000,0,0.7155,0.5235,76.00,0.5750,0.9010,0.5026,0.7545,0,0.0691,-5.4444,70.0473,-0.4627,-0.1138,-8.7604,77.6923,12.6504,11.6523,8.6654,7.6755,10.6549,9.6596,0,5.7137,0.0000,-0.1483,2.0535,-0.0829,-0.1063,2.0784,-0.0509,2.0423,2.1124,-0.0865,-0.0998,2.0764,2.1249,0.0337,1.0139,-0.2886,0.2461,0.0,1857,0.0560,0,0.0000,11.6829,0.0000,0,3.5115,4.1131,9.8375,3.5121,3.5675,8.8774,3.5848,8.7486,3.5302,8.8734,8.8727,-0.0048,-0.0021,1.6939,0.0,0.0008,0.0004,-0.0991,2.7442,3.7710,1.9991,304.0993,1.7577,1.7830,1.6544,1.6838,1.6427,7.8189,1.6609,144.2227,9.5199,112.6889,0.000,1.2088,1.0033,0.9343,0.000,0.9706,0.9430,5.0402,3.8933,2.8751,1.4282,5.5736,5.6069,108.8196,8.1857,0.4061,71.2436,0.0000,-1,0.0,0.0,0,0.0,0.0139,-0.1538,0.1338,21.7757,-0.0798,-0.0969,0.0788,0.0508,0.0,0.0000,0.0000,0.0000,0,0,24.8725,709.7827,0.0,2318.1149,118.6667,11.8713,1492.3506,90.7490,4.2547,0.8214,0.0000,12.6314,0,0,0.6844,0,0,0,0,0,0,49,2.1667,3.5811,7.8186,22,140.9233,121.1999,49,71,0.0909,48.1456,47.6838,437.6516,0.0000,0,0.0,0.0000,302,7.8675,5.5334,6.1964,3.0445,4.7449,9.6454,7.7736,0.0,0.1571,0.9203,2.1607,315.2451,0.0000,0.0000,0.0363,0.0363,0.8112,1.1874,0.0363,0.7761,0.8813,0.0519,0.9191,0,0.0502,1.1078,1.2503,44.0,0.0000,0,0.0232,52.4444,1.0601,0.0,-3.6343,-1.6116,189.4998,0.2531,0.0,0.4500,1.6157,2.5341,0.0615,0.0427,0.1053,0.0206,0.0144,0.0498,0.0235,0.0121,0.0092,408.1438,408.3601,408.1779,402.4356,452.5259,476.7291,437.9165,57,0,426.7978,0.000,0.000,0,20,0.7623,0.0,0.5836,0.0608,0.0170,0.0333,0.0044,0.2620,0.5110,0.1309,341.3882,2.2428,3.5290,124.2802,0.0909,138.6737,7.7709,0.0,0.9371,1.0249,1.0345,1.0152,1.1557,0.0000,0.0000,1.9637,0.0000,-0.1917,0.0000,0.0,-0.0109,0.0002,-1.9843,0.2023,0.0,40114.8749,264.3407,436.8889,0.0000,17192.6451,0.3674,2576,6.5236,-5.1902,11.7778,-1023.5362,-35.3276,-349.9540,-0.2175,0.6513,2.2764,2.2945,2.3139,2.3109,2.3083,0.0000,5.9778,1.9476,1.9936,1.9431,306.1272,1.8476,1.9460,149.8966,1.8440,121.7486,0.0000,1.8672,0,7.9135,6.6884,-594.7517,0.000,0.2609,0.0156,0,0.0,-3.3413,-0.2041,-0.0105,0,-0.0011,-2.6427,1722.0076,-0.0771,0,33.9352,1.599117e+03,1.022946e+03,0.8015,4.76,6,6,0.0000,9.8350,1.2051,0.0000,1.1754,0.0000,0.0,-0.1032,1.0236,0.0,0.0000,1.1226,4,0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0085,-1.8717,0,0.0658,-0.2019,-470.4030,0,-13.7157,0.0500,0.5730,0.3002,1.0198,0.0000,0.1103,49872.2846,618.4444,327.8598,1282.2958,-0.0655,9.8597,3.4208,28.6704,0.0000,23652.5257,0.8528,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0000,0,1.0079,0.5949,0.0000,0,0.0,0.9751,60,60.2431,0,0,0.0000,-0.0295,0.0669,-5.8155,-0.0012,0.0037,-0.2007,-1.9884,0.0,0.0016,0.2363,0.1433,0.6592,0.3949,0.0313,0.0188,0.0857,0.0518,358.6667,0.0438,119.6156,-0.0024,18367.6345,-0.0107,0.0058,0.0549,474.8115,8993.7981,7304.9177,0.5950,0.9458,6.0,4.9583,5.7778,2.7300,6.0711,1.3005,2.1860,0,85.6892,172.5045,233.6007,302.4134,336.4134,334.4134,35.3312,35.9824,117.6403,111.8885,67.0118,44.6829,0.0000,0.0347,-1.9853,36.8197,-361.1360,-34.8889,2.8374,357.4015,4.7297,4.2811,4.2858,0.0000,4.3204,4.3305,4.3132,582,46,254,404,94,32.3486,34.9546,1280,32.3310,32.4873,10.3637,32.5303,32.4862,0.0,0.0000,32.4875,0.0,61.1901,14,1167.3667,1128.3245,1995.8719,0.0,1178.2762,1167.3161,1167.0302,0.0000,-0.0226,0.3257,0.0066,1.1770,-0.0100,0.0157,0.5892,0.7628,0.2161,0.4351,0.9436,0.9492,0.4867,0.2418,0.8533,0.6591,0.0000,0.0000,0.0010,1.5125,0.0000,-0.1234,0.0000,0.0000,0.9661,4.1222,1.0458,4.6961,1.0229,0.9193,4.2017,4.1919,1.0201,1.0536,1.0575,6.1361,5.2653,4.4368,9.2281,8.4940,7.7915,6.9825,10.6613,9.9550,0.0000,24238.5612,159.2397,250.5556,9845.8296,74.8699,551.7318,25.6147,156,953.8683,24.6225,0.0000,0.0011,0.0012,0.0011,14786.3920,0.0007,0.0008,0.0008,0.0008,0,0.0000,0,0,83.8231,25829.2720,0,0.0000,0.0,0.0000,0.00,0.0313,0.8369,0.0000,1.9778,3.5545,0.1979,4.1297,38.6352,3.5441,3.6046,3.6279,0.0137,3.6275,0.0709,-15.2581,0,-13.7580,0.0,826.4444,-13.6053,-13.2579,47648.0932,25853.3904,-15.2568,17847.8323,-15.5940,-15.2483,1401.8756,10.2464,6.9289,4.1692,0.000,4,1.0041,46,0,1.1829,1.1976,1132.6367,0.0000,0.8889,0.0000,0.0000,8,-158.6333,0.0000,-0.0767,0.9866,1.0943,-0.0065,-0.0016,0.0000,0,37.5760,0.0000,0.0000,0.0000,0.0000,0.0000,0.1780,1.5488,0.0088,-0.0868,0.00,No

## Data Checks

In [34]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 171
Columns: 1112
Use sampling: False (sample size: 171)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['SpMAD_Dzs', 'GATS6m', 'ATS5v', 'MATS8s', 'AATSC6m', 'AATSC6v', 'AATS7i', 'AATS7v', 'AATS7p', 'ATSC5i']
Rows remaining as candidates after top-10 filter: 0 (of 171)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [35]:
# Sample Rows
df_head

,MATS3v,nHBint10,MATS3s,MATS3p,nHBDon_Lipinski,minHBint8,MATS3e,MATS3c,minHBint2,MATS3m,minHBint6,minHBint7,minHBint4,MATS3i,VR3_Dt,SpMax8_Bhi,SdsN,SpMax8_Bhm,SpMax8_Bhe,ECCEN,MDEC-14,SpMax8_Bhs,SpMax8_Bhp,SpMax8_Bhv,MDEC-11,MDEC-12,MDEC-13,VR2_Dt,BIC5,ATS7s,ATS7p,ATS7v,ATS7i,ATS7m,ATS7e,mintN,nHsNH2,khs.sssCH,minHBint3,maxdssC,nT6Ring,minHBint5,nF8Ring,minssCH2,SpMax_DzZ,ETA_EtaP,nHsOH,SpMin1_Bhe,maxHother,nHBAcc_Lipinski,StN,khs.aaS,khs.aaO,khs.aaN,Sare,SHAvin,SpMax3_Bhv,SpMax3_Bhp,SpMax3_Bhs,SpMax3_Bhe,SpMin6_Bhi,SpMax3_Bhm,SpMax3_Bhi,ETA_EtaP_F_L,mindCH2,AATSC2e,AATSC2c,AATSC2m,AATSC2i,nsBr,AATS5p,AATSC2v,AATSC2p,AATSC2s,VABC,maxdNH,khs.ddsN,RotBtFrac,ATS4e,ATS4m,nFRing,ATS4i,ATS4s,ATS4p,ETA_Alpha,khs.sssN,EE_Dzi,MAXDN,EE_Dzm,EE_Dze,EE_Dzs,EE_Dzp,EE_Dzv,ATS8e,maxsOH,minssssNp,maxsOm,MDEC-23,MDEC-22,MDEC-24,nFG12HeteroRing,ATS8s,ATS8v,SP-6,SP-7,SHsNH2,SP-5,SP-2,SP-3,SP-0,SP-1,minHsOH,ATSC8v,MATS2v,ATSC8s,MATS2p,MATS2s,ATSC8p,MATS2e,ATSC8e,ATSC8c,MATS2c,MATS2m,topoDiameter,ATSC8m,MATS2i,ATSC8i,ntN,khs.ssCH2,SpAD_Dt,ETA_Eta_R_L,SHdsCH,SaasN,SC-4,SaasC,minaaCH,AATSC3c,AATSC3e,AATSC3i,AATSC3m,AATSC3s,AATSC3p,AATSC3v,SpMax2_Bhp,AATS8e,AATS8i,AATS8m,AATS8s,AATS8p,AATS8v,VE3_Dt,XLogP,SpMax2_Bhi,maxssCH2,minaaS,SpMax4_Bhv,SpMax4_Bhs,SpMax4_Bhp,SpMax4_Bhm,minHaaNH,SpMax4_Bhi,minaaN,SpMax4_Bhe,StsC,SssCH2,maxHdNH,MATS1p,R_TpiPCTPC,MATS1s,MATS1v,JGI10,MATS1c,MATS1e,VR2_DzZ,MATS1i,MATS1m,MDEC-34,MDEC-33,VR2_Dze,VR2_Dzm,VR2_Dzs,VR2_Dzp,khs.ssssC,nTG12Ring,khs.ssssN,ATS5e,gmin,VR2_D,ATS5m,ATS5p,ATS5s,ATS5v,AATSC5p,TpiPC,maxsCH3,SdS,khs.ssO,ETA_Eta_F_L,khs.ssS,SdO,VE2_Dt,maxHtCH,ETA_dEpsilon_B,ETA_dEpsilon_A,ETA_dEpsilon_D,SsNH2,StCH,SsCH3,CIC5,CIC4,CIC1,CIC0,CIC3,CIC2,nF10HeteroRing,maxssO,WPOL,n5HeteroRing,maxHAvin,fragC,ETA_Eta_B_RC,AATS7m,SpDiam_Dt,SdssC,ETA_Epsilon_3,AATS7i,AATS7e,nT9Ring,minsCl,AATS7v,AATS7s,AATS7p,nHdCH2,ETA_Epsilon_5,ETA_Epsilon_4,SsssCH,maxHsOH,GATS1v,maxaaaC,GATS1s,minsNH2,BIC4,SpMin7_Bhs,SpMin7_Bhp,SpMin7_Bhv,nHtCH,GATS1e,mintsC,GATS1c,SpMin7_Bhm,GATS1m,SpMin7_Bhe,GATS1i,maxtsC,minHAvin,MDEC-44,AATS2v,SPC-6,SPC-4,SPC-5,SpAD_D,MATS6c,ETA_BetaP_s,minaasC,minaasN,minssNH,nT7HeteroRing,RotBFrac,nF10Ring,ETA_BetaP_ns,nH,nL,nN,nO,nA,nC,nF,nX,nQ,nS,nV,ATS1m,mindsN,SHCsats,SHCsatu,CrippenMR,GATS1p,SRW10,ETA_dPsi_A,AATS6m,AATS6i,AATS6e,minsBr,nF9HeteroRing,SpMin7_Bhi,AATS6v,AATS6p,AATS6s,naAromAtom,nBase,minHBint10,SpDiam_DzZ,SaaNH,khs.dNH,maxaaN,maxaaO,SpDiam_Dzv,SpDiam_Dzs,SpDiam_Dzp,SpDiam_Dze,SpDiam_Dzm,GATS6i,SpDiam_Dzi,Mi,Mv,Mp,GGI10,bpol,MW,GATS6v,MATS7s,MATS7p,C1SP1,MATS7v,MATS7i,MATS7m,MATS7c,GATS6s,MATS7e,maxtN,SpMin8_Bhe,SpMin8_Bhi,SpMin8_Bhm,SpMin8_Bhp,SpMin8_Bhs,SpMin8_Bhv,maxHCsatu,maxHCsats,ATSC3v,ATSC3s,ATSC3p,minHdCH2,ATSC3e,ATSC3c,maxssNH,ATSC3m,ATSC3i,minHCsatu,minHCsats,SpMax7_Bhe,SpMax7_Bhi,SpMax7_Bhm,ETA_BetaP_ns_d,SpMax7_Bhp,SpMax7_Bhs,SpMax7_Bhv,SdsCH,minssO,minssS,SpMin3_Bhe,SpMin3_Bhm,SpMin3_Bhi,SpMin3_Bhv,SpMin3_Bhs,SpMin3_Bhp,TPC,VP-5,VP-4,VP-7,VP-6,VP-1,VP-0,VP-3,VP-2,MIC5,MIC4,MIC3,MIC2,MIC1,MIC0,ATSC5p,piPC10,ATSC5s,minsOm,nHBa,nHBd,SddssS,nCl,minsOH,SHaaCH,nHBDon,nF11HeteroRing,AATS5i,AATS5m,SpMin6_Bhs,SpMin6_Bhp,SpMin6_Bhv,AATS5e,ETA_dBeta,khs.sCH3,ALogP,SpMin6_Bhm,BCUTp-1l,AATS5s,BCUTp-1h,AATS5v,SpMin6_Bhe,ATS8i,ATS8m,BCUTw-1h,BCUTw-1l,nBondsS3,nBondsS2,ATS8p,GATS3p,GATS3s,GATS3v,GATS3c,GATS3e,SC-5,GATS3i,SC-6,GATS3m,SC-3,minsCH3,SssssC,nAtomLC,nT12HeteroRing,minHaaCH,MLFER_BH,MLFER_BO,SaaaC,mindsCH,nddssS,maxaasC,maxsssN,MATS6p,MATS6s,MATS6v,MATS6i,MATS6m,MATS6e,ETA_Beta_ns_d,hmax,ETA_Beta_s,nHaaCH,khs.aaaC,ETA_AlphaP,nAromBond,ATSC2v,ATSC2p,ATSC2s,ATS4v,ATSC2e,ATSC2c,ATSC2m,ATSC2i,AATS4v,AATS4s,AATS4p,AATS4e,ETA_BetaP,AATS4m,AATS4i,SHsOH,SpMax_D,MDEN-13,MDEN-12,MDEN-11,ATS3m,PetitjeanNumber,khs.aasN,khs.aasC,MWC10,MPC7,TWC,topoRadius,WPATH,nG,ndsN,MAXDP,naaaC,SM1_DzZ,SpAbs_DzZ,SpAbs_Dze,khs.aaNH,SpAbs_Dzm,SM1_Dzv,SpAbs_Dzi,SM1_Dzp,SM1_Dzs,SM1_Dzm,SpAbs_Dzv,SM1_Dzi,SpAbs_Dzp,SpAbs_Dzs,SM1_Dze,maxaaCH,maxdO,nF11Ring,GATS2v,GATS2s,ETA_Beta,GATS2m,GATS2i,GATS2e,GATS2c,nHaaNH,ATSC1p,ATSC1s,ATSC1v,ATSC1c,ATSC1e,ATSC1i,ATSC1m,MWC9,MWC8,MWC5,MWC4,MWC7,MWC6,ndssC,MWC2,MAXDN2,MATS5e,SpMin2_Bhe,MATS5c,MATS5m,SpMin2_Bhm,MATS5i,SpMin2_Bhi,SpMin2_Bhv,MATS5v,MATS5p,SpMin2_Bhs,SpMin2_Bhp,VE1_Dzi,Mare,BCUTc-1l,BCUTc-1h,SssNH,MPC9,VE1_Dzp,naaN,SHBd,TSRW,SHBa,khs.ssNH,SpMax6_Bhp,SpMax6_Bhs,SpMAD_Dzv,SpMax6_Bhv,SpMax6_Bhe,SpMAD_Dze,SpMax6_Bhi,SpMAD_Dzi,SpMax6_Bhm,SpMAD_Dzm,SpMAD_DzZ,AATSC8s,AATSC8p,AATSC8v,minHssNH,AATSC8c,AATSC8e,AATSC8i,AATSC8m,AATS3s,AATS3p,AATS3v,SpMin5_Bhv,SpMin5_Bhp,SpMin5_Bhs,SpMin5_Bhm,SpMin5_Bhi,AATS3e,SpMin5_Bhe,AATS3i,SpMAD_Dzs,AATS3m,MLFER_L,GATS5s,GATS5p,GATS5v,MLFER_A,GATS5i,GATS5m,IC3,IC2,IC1,IC0,IC5,IC4,ETA_Eta_R,ETA_Eta_L,ETA_Eta_B,ETA_Eta_F,SaaCH,nAcid,maxsssCH,SsCl,nF6Ring,maxsF,MATS4c,MATS4e,MATS4i,SP-4,MATS4m,MATS4s,MATS4p,MATS4v,VC-6,SsssN,minaaaC,minwHBa,nT6HeteroRing,khs.dssC,AATSC0m,EE_Dt,minsF,ATSC0v,ATSC0s,ATSC0p,ATSC0m,ATSC0i,ATSC0e,ATSC0c,VE2_D,SpMAD_D,nHBint2,nHBint3,ETA_Epsilon_1,nHBint6,nHBint7,nHBint4,nHBint5,nHBint8,nHBint9,nBondsS,AATS2p,AATS2s,AATS2e,nBondsD,AATS2i,AATS2m,nBondsM,nBonds2,MDEN-33,Sp,Sv,Si,FMF,nRotB,minssssC,SwHBa,Zagreb,SRW6,SRW7,SRW4,SRW5,SRW2,SRW8,SRW9,maxHsNH2,SCH-5,SCH-6,SCH-7,ATS6p,maxaasN,MAXDP2,VE1_DzZ,VE1_Dze,GATS4p,GATS4s,VE1_Dzm,GATS4v,GATS4i,VE1_Dzs,GATS4m,ndsCH,VE1_Dzv,GATS4c,GATS4e,ETA_Beta_ns,McGowan_Volume,n5Ring,ETA_dAlpha_B,ATSC7s,ATSC7p,ETA_dAlpha_A,ATSC7v,ATSC7i,ATSC7m,ATSC7c,VC-4,VC-5,VC-3,ATSC7e,JGI2,JGI3,JGI1,JGI6,JGI7,JGI4,JGI5,JGI8,JGI9,SpAD_DzZ,SpAD_Dze,SpAD_Dzm,SpAD_Dzi,SpAD_Dzv,SpAD_Dzp,SpAD_Dzs,nBonds,LipinskiFailures,SpDiam_D,minHdsCH,SssO,C2SP3,C2SP2,GATS2p,ETA_Shape_X,ETA_Shape_Y,ETA_Shape_P,AVP-5,AVP-4,AVP-7,AVP-1,AVP-0,AVP-2,AATS1v,AATS1p,AATS1s,AATS1m,MDEN-22,AATS1i,AATS1e,maxaaNH,GATS7c,GATS7m,GATS7v,GATS7p,GATS7s,SsOm,SsOH,AATSC4v,maxHBd,AATSC4s,maxHBa,SHssNH,AATSC4e,AATSC4c,AATSC4m,AATSC4i,SHBint10,ATS2v,ATS2p,ATS2s,CrippenLogP,ATS2i,JGT,MPC10,VAdjMat,ATSC6p,ATSC6s,ATSC6v,ATSC6i,ATSC6m,ATSC6c,ATSC6e,SpMin1_Bhi,SpMin1_Bhm,SpMin1_Bhp,SpMin1_Bhs,SpMin1_Bhv,SHother,AATS0s,SpMin4_Bhv,AATS0p,SpMin4_Bhp,AATS0v,SpMin4_Bhs,SpMin4_Bhm,AATS0i,SpMin4_Bhi,AATS0m,minsssCH,SpMin4_Bhe,nAtomLAC,AATS0e,MWC3,ATSC5v,MLFER_S,ETA_dBetaP,AATSC4p,nRotBt,SHaaNH,AATSC5v,AATSC5s,AATSC5e,naasN,AATSC5c,AATSC5m,SpMax_Dt,AATSC5i,naasC,VR3_D,VR1_D,VR1_Dt,ETA_Epsilon_2,MLogP,nHBAcc2,nHBAcc3,AMR,AMW,GATS6c,sumI,GATS6e,gmax,maxHssNH,MATS5s,GATS6m,maxHBint8,maxHBint9,GATS6p,C1SP2,C1SP3,maxHBint2,maxHBint3,maxHBint4,maxHBint5,maxHBint6,maxHBint7,AVP-6,ATSC5e,C4SP3,AVP-3,ATSC5c,ATSC5m,nHother,ATSC5i,VCH-5,VCH-7,VCH-6,Mse,DELS2,MATS8m,ATS3v,ATS3s,ATS3p,ATS3e,MATS8i,Kier2,Kier3,Kier1,HybRatio,ATS3i,MDEN-23,SHBint9,SHBint8,SHBint3,SHBint2,SHBint7,SHBint6,SHBint5,SHBint4,DELS,nHeteroRing,GATS7e,ETA_Psi_1,mindssC,nwHBa,maxHBint10,GATS7i,nAtom,Spe,khs.dS,khs.dO,maxwHBa,AATSC6p,AATSC6s,AATSC6v,AATSC6c,AATSC6e,AATSC6i,AATSC6m,SssssNp,AATSC7c,ASP-2,ASP-3,ASP-0,ASP-1,ASP-6,ASP-7,ASP-4,ASP-5,ATS0s,MATS8v,ATS0p,MATS8s,ATS0v,MATS8p,MATS8e,MATS8c,ATS0e,ATS0i,ATS0m,GGI9,GGI8,GGI1,GGI3,GGI2,GGI5,GGI4,GGI7,GGI6,nTRing,TIC0,TIC1,TIC2,TIC3,TIC4,TIC5,ZMIC4,ZMIC5,ZMIC0,ZMIC1,ZMIC2,ZMIC3,minHother,ATSC4c,ATSC4e,ATSC4i,ATSC4m,ATSC4s,ATSC4p,ATSC4v,SpMax1_Bhs,SpMax1_Bhp,SpMax1_Bhv,hmin,SpMax1_Bhe,SpMax1_Bhi,SpMax1_Bhm,MPC6,nAtomP,MPC4,MPC5,MPC2,VR3_Dzv,VR3_Dzs,MPC8,VR3_Dzp,VR3_Dzm,SpMAD_Dzp,VR3_Dzi,VR3_Dze,SsF,minaaO,VR3_DzZ,mintCH,Sse,C3SP2,VR1_DzZ,VR1_Dzp,VR1_Dzs,SHtCH,VR1_Dzi,VR1_Dzm,VR1_Dze,maxdsN,AATSC7v,AATSC7s,AATSC7p,AATSC7m,AATSC7i,AATSC7e,BIC2,BIC3,BIC0,BIC1,SIC5,SIC4,SIC1,SIC0,SIC3,SIC2,minHBd,minHBa,AATSC1p,AATSC0i,ALogp2,AATSC1i,SaaO,SaaN,GATS8m,SpMax2_Bhv,GATS8i,SpMax2_Bhs,GATS8e,GATS8c,SpMax2_Bhe,SpMax2_Bhm,GATS8v,GATS8p,GATS8s,piPC3,piPC2,piPC1,piPC7,piPC6,piPC5,piPC4,piPC9,piPC8,maxHdsCH,ATS1v,ATS1p,ATS1s,ATS1i,SpMAD_Dt,ATS1e,VR2_Dzi,MPC3,ATS2e,VR2_Dzv,minHBint9,VE2_Dzs,VE2_Dzp,VE2_Dzv,ATS2m,VE2_Dzi,VE2_Dzm,VE2_Dze,VE2_DzZ,nHAvin,meanI,nHCsatu,nHCsats,apol,ATS5i,nF12Ring,mindO,MolIP,maxdsCH,TopoPSA,ETA_EtaP_B_RC,MDEO-11,MDEO-12,AATSC0s,SpMax5_Bhv,AATSC0p,SpMax5_Bhs,AATSC0v,SpMax5_Bhp,SpMax5_Bhm,SpMax5_Bhi,AATSC0c,SpMax5_Bhe,AATSC0e,VE3_DzZ,C3SP3,VE3_Dzv,minddssS,ATS6s,VE3_Dzs,VE3_Dzp,ATS6v,ATS6i,VE3_Dzm,ATS6m,VE3_Dzi,VE3_Dze,ATS6e,VPC-6,VPC-5,VPC-4,MLFER_E,nBondsD2,Mpe,nHeavyAtom,nRing,GATS5c,GATS5e,VR1_Dzv,minsssN,topoShape,VE1_Dt,maxHaaCH,nHBAcc,VE3_D,VE1_D,AATSC1s,AATSC1v,AATSC1m,AATSC1c,AATSC1e,LipoaffinityIndex,n6Ring,ETA_Eta,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,ETA_EtaP_L,ETA_EtaP_F,ETA_EtaP_B,ETA_dEpsilon_C,MDEO-22,Toxic
0,0.0908,0,0.0075,0.0173,0,0.0,-0.0436,0.0409,0.0,0.1368,0.0,0.0000,0.0,-0.0574,31.8800,3.3540,0.0000,3.2664,3.3158,1422,0.0,3.8373,3.2044,3.2128,0.0000,0.0000,0.0000,22.2380,0.8435,768.4444,275.1928,41003.7141,24110.8860,15270.4651,1277.0737,0.0000,0,0,0.0,0.0000,0,0.0,0,0.000,201.0744,0.8169,0,2.2798,0.0000,8,0.0000,0,0,0,60.832,0.0000,3.9710,3.9582,4.6723,4.0541,1.5761,4.0396,4.0792,0.3114,0.0,0.0076,0.0007,0.6986,0.0196,0,1.9081,-0.8911,-0.0033,-0.0255,451.4722,0.0,0,0.0000,1453.5938,19835.8193,0,26862.1417,759.7778,347.5541,21.9333,0,198.0675,0.0000,201.0915,201.1842,213.9751,232.9974,222.2215,1094.3304,0.0000,0.0,0.0000,60.1757,13.9880,0.0,0,554.0000,35648.5015,18.2418,16.2633,0.0,20.9413,22.2081,22.3620,30.3248,22.5080,0.0000,237.1491,-0.0231,-0.6667,-0.0166,-0.0129,-0.2969,0.1073,0.0573,0.1053,0.0481,0.0281,17,384.1820,0.0129,-13.8718,0,0,3444.0152,22.5079,0.0000,0.0000,0.0,0.0000,0.0000,0.0006,-0.0031,-0.0868,3.4021,0.0149,0.0034,3.5086,4.1095,7.8166,149.5621,92.9158,3.9571,1.7139,254.6322,-167.1241,-0.094,4.2285,0.000,0.0,3.8192,4.6641,3.8195,3.8311,0.0,3.8758,0.0000,3.8599,0.0000,0.000,0.0,0.0049,20.3566,-0.0388,0.0255,0.0063,-0.4760,-0.0226,25.3775,-0.0816,0.0440,0.0,0.0000,25.3702,25.3764,43.3885,24.5288,0,0,0,1408.5019,0.0000,34.7634,18932.5551,339.6464,734.3333,51592.2938,-0.0198,12.0215,0.0000,0.0,0,14.3222,0,0.0000,0.0000,0.0,0.1391,0.2258,0.0000,0.0,0.0,0.0000,0.3333,0.3000,3.0318,4.4787,0.8667,2.0135,0,0.000,116,0,0.0000,1179.08,1.4381,94.8476,1814.8151,0.0000,0.4586,149.7571,7.9321,0,0.0,254.6815,4.7729,1.7093,0,0.8015,0.5454,0.0000,0.0000,0.6341,0.0000,0.4793,0.0,0.8486,1.3331,1.4748,1.4774,0,0.5505,0.0000,1.2841,1.4670,0.5007,1.3636,0.9429,0.0000,0.000,0.0,328.8105,39.5531,11.4364,22.4183,581.0425,-0.0902,0.6957,0.0000,0.0000,0.0,0,0.0000,0,0.9565,14,0,4,4,0,38,0,0,0,0,0,8823.8932,0.0000,0.0000,0.0000,0.0000,0.7123,11.4843,0.1194,101.4081,146.8943,7.9652,0.0,0,1.3448,270.7278,1.7912,4.6957,38,-1,0.0,296.0059,0.0,0,0.0000,0.0000,322.7435,319.6259,336.0904,296.1456,296.0272,1.0554,292.0703,7.2942,0.7947,0.8024,0.3406,25.7369,590.1015,1.0713,0.1647,0.0333,0,-0.0006,-0.0066,0.0473,0.1148,1.3061,0.2220,0.0000,1.3061,1.2720,1.3491,1.4567,1.3022,1.4359,0.0000,0.0000,575.4060,2.4444,0.5603,0.0,-0.5069,0.0919,0.0,557.9458,-14.2345,0.0000,0.0000,3.4009,3.4171,3.3582,0.0000,3.3048,3.9738,3.3124,0.0000,0.000,0.0,1.8776,1.9542,1.8540,1.9645,1.8650,1.9655,8169,6.8704,8.4524,3.7561,4.9553,14.9333,23.5048,10.2643,12.3024,54.9937,55.3273,51.3250,43.2973,30.8117,13.3151,-3.5162,11.3293,-36.3333,0.0000,0,0,0.0,0,0.0000,0.0000,0,0,145.1083,106.3627,1.5355,1.6851,1.6695,7.9129,12.00,0,0.0000,1.6425,6.0583,4.1255,12.9486,289.8443,1.5809,20938.6998,13008.2055,15.9980,11.8500,8,22,239.9415,0.8415,0.7303,0.7413,0.9107,0.8248,1.5764,0.9982,0.0,0.6471,3.6250,0.0000,0.0,0,0,0.0000,0.000,0.000,0.0000,0.0000,0,0.0000,0.0000,-0.1490,0.0338,-0.1505,-0.1327,-0.0799,0.0522,0.0,0.0000,32.00,0,0,0.4768,45,-108.7165,-0.3998,-3.1111,53189.5532,0.9281,0.0803,85.2306,2.3875,292.2503,4.1746,1.9096,7.9868,1.6522,108.9880,147.5942,0.0000,290.5212,0.0000,0.0000,0.0000,18480.9749,0.4706,0,0,13.6498,863,190.0101,9,6433,0,0,0.0000,0,1.5714,407.0386,407.2647,0,407.0756,-2.8733,401.3850,-6.4019,3.7003,1.5671,453.4003,1.5935,478.6676,436.9364,1.5550,0.0000,0.0000,0,0.7155,0.5235,76.00,0.5750,0.9010,0.5026,0.7545,0,0.0691,-5.4444,70.0473,-0.4627,-0.1138,-8.7604,77.6923,12.6504,11.6523,8.6654,7.6755,10.6549,9.6596,0,5.7137,0.0000,-0.1483,2.0535,-0.0829,-0.1063,2.0784,-0.0509,2.0423,2.1124,-0.0865,-0.0998,2.0764,2.1249,0.0337,1.0139,-0.2886,0.2461,0.0,1857,0.0560,0,0.0000,11.6829,0.0000,0,3.5115,4.1131,9.8375,3.5121,3.5675,8.8774,3.5848,8.7486,3.5302,8.8734,8.8727,-0.0048,-0.0021,1.6939,0.0,0.0008,0.0004,-0.0991,2.7442,3.7710,1.9991,304.0993,1.7577,1.7830,1.6544,1.6838,1.6427,7.8189,1.6609,144.2227,9.5199,112.6889,0.000,1.2088,1.0033,0.9343,0.000,0.9706,0.9430,5.0402,3.8933,2.8751,1.4282,5.5736,5.6069,108.8196,8.1857,0.4061,71.2436,0.0000,-1,0.0,0.0,0,0.0,0.0139,-0.1538,0.1338,21.7757,-0.0798,-0.0969,0.0788,0.0508,0.0,0.0000,0.0000,0.0000,0,0,24.8725,709.7827,0.0,2318.1149,118.6667,11.8713,1492.3506,90.7490,4.2547,0.8214,0.0000,12.6314,0,0,0.6844,0,0,0,0,0,0,49,2.1667,3.5811,7.8186,22,140.9233,121.1999,49,71,0.0909,48.1456,47.6838,437.6516,0.0000,0,0.0,0.0000,302,7.8675,5.5334,6.1964,3.0445,4.7449,9.6454,7.7736,0.0,0.1571,0.9203,2.1607,315.2451,0.0000,0.0000,0.0363,0.0363,0.8112,1.1874,0.0363,0.7761,0.8813,0.0519,0.9191,0,0.0502,1.1078,1.2503,44.0,0.0000,0,0.0232,52.4444,1.0601,0.0,-3.6343,-1.6116,189.4998,0.2531,0.0,0.4500,1.6157,2.5341,0.0615,0.0427,0.1053,0.0206,0.0144,0.0498,0.0235,0.0121,0.0092,408.1438,408.3601,408.1779,402.4356,452.5259,476.7291,437.9165,57,0,426.7978,0.000,0.000,0,20,0.7623,0.0,0.5836,0.0608,0.0170,0.0333,0.0044,0.2620,0.5110,0.1309,341.3882,2.2428,3.5290,124.2802,0.0909,138.6737,7.7709,0.0,0.9371,1.0249,1.0345,1.0152,1.1557,0.0000,0.0000,1.9637,0.0000,-0.1917,0.0000,0.0,-0.0109,0.0002,-1.9843,0.2023,0.0,40114.8749,264.3407,436.8889,0.0000,17192.6451,0.3674,2576,6.5236,-5.1902,11.7778,-1023.5362,-35.3276,-349.9540,-0.2175,0.6513,2.2764,2.2945,2.3139,2.3109,2.3083,0.0000,5.9778,1.9476,1.9936,1.9431,306.1272,1.8476,1.9460,149.8966,1.8440,121.7486,0.0000,1.8672,0,7.9135,6.6884,-594.7517,0.000,0.2609,0.0156,0,0.0,-3.3413,-0.2041,-0.0105,0,-0.0011,-2.6427,1722.0076,-0.0771,0,33.9352,1.599117e+03,1.022946e+03,0.8015,4.76,6,6,0.0000,9.8350,1.2051,0.0000,1.1754,0.0000,0.0,-0.1032,1.0236,0.0,0.0000,1.1226,4,0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0085,-1.8717,0,0.0658,-0.2019,-470.4030,0,-13.7157,0.0500,0.5730,0.3002,1.0198,0.0000,0.1103,49872.2846,618.4444,327.8598,1282.2958,-0.0655,9.8597,3.4208,28.6704,0.0000,23652.5257,0.8528,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0000,0,1.0079,0.5949,0.0000,0,0.0,0.9751,60,60.2431,0,0,0.0000,-0.0295,0.0669,-5.8155,-0.0012,0.0037,-0.2007,-1.9884,0.0,0.0016,0.2363,0.1433,0.6592,0.3949,0.0313,0.0188,0.0857,0.0518,358.6667,0.0438,119.6156,-0.0024,18367.6345,-0.0107,0.0058,0.0549,474.8115,8993.7981,7304.9177,0.5950,0.9458,6.0,4.9583,5.7778,2.7300,6.0711,1.3005,2.1860,0,85.6892,172.5045,233.6007,302.4134,336.4134,334.4134,35.3312,35.9824,117.6403,111.8885,67.0118,44.6829,0.0000,0.0347,-1.9853,36.8197,-361.1360,-34.8889,2.8374,357.4015,4.7297,4.2811,4.2858,0.0000,4.3204,4.3305,4.3132,582,46,254,404,94,32.3486,34.9546,1280,32.3310,32.4873,10.3637,32.5303,32.4862,0.0,0.0000,32.4875,0.0,61.1901,14,1167.3667,1128.3245,1995.8719,0.0,1178.2762,1167.3161,1167.0302,0.0000,-0.0226,0.3257,0.0066,1.1770,-0.0100,0.0157,0.5892,0.7628,0.2161,0.4351,0.9436,0.9492,0.4867,0.2418,0.8533,0.6591,0.0000,0.0000,0.0010,1.5125,0.0000,-0.1234,0.0000,0.0000,0.9661,4.1222,1.0458,4.6961,1.0229,0.9193,4.2017,4.1919,1.0201,1.0536,1.0575,6.1361,5.2653,4.4368,9.2281,8.4940,7.7915,6.9825,10.6613,9.9550,0.0000,24238.5612,159.2397,250.5556,9845.8296,74.8699,551.7318,25.6147,156,953.8683,24.6225,0.0000,0.0011,0.0012,0.0011,14786.3920,0.0007,0.0008,0.0008,0.0008,0,0.0000,0,0,83.8231,25829.2720,0,0.0000,0.0,0.0000,0.00,0.0313,0.8369,0.0000,1.9778,3.5545,0.1979,4.1297,38.6352,3.5441,3.6046,3.6279,0.0137,3.6275,0.0709,-15.2581,0,-13.7580,0.0,826.4444,-13.6053,-13.2579,47648.0932,25853.3904,-15.2568,17847.8323,-15.5940,-15.2483,1401.8756,10.2464,6.9289,4.1692,0.000,4,1.0041,46,0,1.1829,1.1976,1132.6367,0.0000,0.8889,0.0000,0.0000,8,-158.6333,0.0000,-0.0767,0.9866,1.0943,-0.0065,-0.0016,0.0000,0,37.5760,0.0000,0.0000,0.0000,0.0000,0.0000,0.1780,1.5488,0.0088,-0.0868,0.00,No

In [36]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Toxic,category,0.0,0.0,2.0,"No, Yes"
1,MATS3v,float64,0.0,0.0,163.0,"0.0096, -0.0619, 0.03, 0.0289, 0.0247, -0.0325, -0.0028, -0.0251, -0.0702, -0.0432"
2,MATS3s,float64,0.0,0.0,168.0,"0.017, -0.0384, 0.0095, 0.0065, -0.0678, -0.0022, 0.0489, -0.0116, -0.0282, -0.0319"
3,MATS3p,float64,0.0,0.0,157.0,"0.0089, -0.0137, -0.0905, -0.1369, -0.0614, -0.0429, -0.0164, -0.0453, -0.1607, -0.0912"
4,minHBint8,float64,0.0,0.0,38.0,"0.0, 4.3121, 2.1399, 4.0632, 0.7339, 5.385, 0.9326, 0.6583, 0.9507, 0.5115"
5,MATS3e,float64,0.0,0.0,162.0,"-0.0436, -0.0332, -0.0201, -0.0739, -0.0265, -0.0549, -0.0663, -0.0763, -0.0356, -0.0185"
6,MATS3c,float64,0.0,0.0,169.0,"-0.045, -0.0876, 0.0409, -0.2554, 0.0461, -0.0257, 0.1063, 0.0762, -0.1663, -0.118"
7,minHBint2,float64,0.0,0.0,67.0,"0.0, 5.0375, 5.096, -0.663, 0.6969, 4.9615, 5.4463, 5.4595, 5.8704, 5.9765"
8,MATS3m,float64,0.0,0.0,163.0,"0.0143, 0.0511, 0.0361, -0.0669, 0.0922, 0.1063, -0.0337, 0.0086, -0.0417, 0.0471"
9,minHBint6,float64,0.0,0.0,51.0,"0.0, 4.5206, 4.4584, 0.289, 0.571, 1.001, 0.5781, 0.5757, 0.3674, 3.3506"
10,minHBint7,float64,0.0,0.0,46.0,"0.0, 0.8609, 1.025, 5.4379, 1.0846, 5.8061, -0.8532, 5.5787, 0.653, 5.5792"
11,minHBint4,float64,0.0,0.0,50.0,"0.0, 0.8723, 0.4421, 0.4387, 2.6637, 3.1292, 7.2662, 0.7832, 4.5071, -0.6114"
12,MATS3i,float64,0.0,0.0,165.0,"-0.1693, -0.0947, -0.1512, -0.0759, 0.0243, -0.0082, -0.0574, -0.0773, -0.1903, -0.1492"
13,VR3_Dt,float64,0.0,0.0,161.0,"66.8884, 25.1713, 65.6228, 9.9389, 21.808, 25.2415, 29.02, 31.88, 25.0444, 25.0398"
14,SpMax8_Bhi,float64,0.0,0.0,165.0,"3.0725, 3.2732, 3.1479, 3.1095, 3.0903, 3.354, 3.277, 3.1439, 3.1119, 3.1285"
15,SdsN,float64,0.0,0.0,43.0,"0.0, 5.0866, 4.5061, 9.1541, 4.9913, 5.182, 9.5722, 9.2656, 12.7387, 4.8633"
16,SpMax8_Bhm,float64,0.0,0.0,165.0,"2.9614, 3.185, 2.0418, 3.0904, 3.2021, 3.1665, 3.0585, 3.2602, 3.0406, 2.9961"
17,SpMax8_Bhe,float64,0.0,0.0,162.0,"3.0841, 3.1105, 3.024, 3.086, 2.9908, 3.0885, 2.9815, 3.0799, 2.9984, 3.0579"
18,MDEC-14,float64,0.0,0.0,17.0,"0.0, 0.0909, 0.63, 5.3666, 0.3162, 0.0556, 3.0, 0.1952, 1.0, 1.0931"
19,SpMax8_Bhs,float64,0.0,0.0,167.0,"3.7357, 3.3403, 3.6561, 3.8373, 3.8182, 3.7137, 3.2468, 3.2722, 3.1487, 3.7394"
20,SpMax8_Bhp,float64,0.0,0.0,161.0,"2.8246, 3.0507, 3.0151, 3.0428, 2.9522, 3.2044, 2.9381, 2.8967, 2.9279, 3.0502"
21,SpMax8_Bhv,float64,0.0,0.0,168.0,"3.0653, 2.9599, 2.9444, 3.2128, 3.1068, 2.9603, 2.9006, 2.9316, 3.0427, 3.0431"
22,MDEC-11,float64,0.0,0.0,31.0,"0.0, 0.0833, 0.2, 0.3333, 0.0909, 0.0556, 0.3041, 0.1111, 0.226, 0.1783"
23,MDEC-12,float64,0.0,0.0,90.0,"0.0, 4.3436, 2.2517, 2.7868, 2.3177, 6.1055, 2.8825, 1.3698, 3.6175, 2.1431"
24,MDEC-13,float64,0.0,0.0,89.0,"0.0, 6.4605, 1.5036, 1.6549, 5.6625, 1.4364, 1.5518, 3.194, 1.7455, 2.3509"
25,VR2_Dt,float64,0.0,0.0,164.0,"9.5401, 16.631, 90918.7748, 20.353, 11.873, 13.7562, 13.0949, 9.2324, 13.0798, 14.9365"
26,BIC5,float64,0.0,0.0,158.0,"0.8479, 0.8661, 0.8921, 0.8933, 0.8164, 0.9053, 0.895, 0.8262, 0.8948, 0.8969"
27,ATS7s,float64,0.0,0.0,171.0,"768.4444, 584.8643, 542.4444, 665.0607, 473.6173, 453.2438, 537.8889, 670.7778, 623.4167, 430.0309"
28,ATS7p,float64,0.0,0.0,171.0,"275.1928, 172.6206, 184.1086, 279.9207, 256.3269, 163.8859, 257.3541, 302.7803, 275.5873, 212.5503"
29,ATS7v,float64,0.0,0.0,171.0,"41003.7141, 23827.8863, 25068.2617, 39636.1173, 33263.7279, 22302.6913, 36295.6422, 41351.5495, 36397.0418, 29617.67"
30,ATS7i,float64,0.0,0.0,171.0,"24110.886, 17550.5762, 26947.7472, 29845.7723, 27568.3365, 17755.0595, 28406.1479, 36214.8353, 36278.9644, 19188.1513"
31,ATS7m,float64,0.0,0.0,171.0,"15270.4651, 9435.317, 8952.8369, 13651.8722, 10438.6632, 7731.3774, 12188.5342, 13468.0939, 11024.3513, 11280.2942"
32,ATS7e,float64,0.0,0.0,171.0,"1277.0737, 893.7, 1223.9192, 1483.5924, 1320.6997, 872.5727, 1375.7646, 1725.219, 1674.9775, 987.8822"
33,mintN,float64,0.0,0.0,6.0,"0.0, 9.9035, 9.9186, 10.5396, 9.9411, 9.2592"
34,minHBint3,float64,0.0,0.0,25.0,"0.0, 0.4555, 0.4649, 0.4862, 0.4876, 2.6025, 0.9304, 0.5101, 0.6144, 6.2401"
35,maxdssC,float64,0.0,0.0,79.0,"0.0, 0.0405, 0.9153, 0.5949, 0.3579, 0.2791, 0.0704, 1.012, 0.8819, 0.4751"
36,minHBint5,float64,0.0,0.0,51.0,"0.0, 0.6321, 0.8057, 0.3212, 0.3194, 0.9637, 5.9451, 0.8051, 1.3081, 1.1382"
37,minssCH2,float64,0.0,0.0,103.0,"0.0, -0.214, 0.4285, 0.1966, 1.0422, 0.9434, 0.5303, 0.3066, 0.5644, 0.1374"
38,SpMax_DzZ,float64,0.0,0.0,171.0,"201.0744, 183.2467, 196.4886, 234.7424, 243.4516, 163.5596, 180.6385, 270.1107, 233.623, 196.4468"
39,ETA_EtaP,float64,0.0,0.0,170.0,"0.8606, 0.7553, 0.8654, 0.8674, 0.8629, 0.814, 0.7847, 1.067, 0.9255, 0.7913"
40,SpMin1_Bhe,float64,0.0,0.0,145.0,"2.1314, 1.9639, 1.9121, 2.063, 1.9289, 2.04, 2.0273, 2.0272, 1.9564, 1.9524"
41,maxHother,float64,0.0,0.0,162.0,"0.0, 0.6625, 0.6756, 0.6322, 0.6549, 0.5668, 0.602, 0.6079, 0.6018, 0.552"
42,StN,float64,0.0,0.0,6.0,"0.0, 19.8069, 19.8385, 21.2941, 19.8822, 9.2592"
43,Sare,float64,0.0,0.0,162.0,"64.456, 58.672, 61.82, 64.056, 58.076, 57.916, 63.5, 60.1, 60.832, 66.004"
44,SHAvin,float64,0.0,0.0,34.0,"0.0, 0.5759, 1.1951, 1.1875, 0.4964, 0.484, 0.4439, 0.6209, 0.5819, 1.46"
45,SpMax3_Bhv,float64,0.0,0.0,161.0,"3.7732, 3.8353, 3.8045, 3.7988, 3.8, 3.7841, 3.8379, 3.7969, 3.7995, 3.8141"
46,SpMax3_Bhp,float64,0.0,0.0,164.0,"3.7714, 3.8386, 3.7404, 3.8293, 3.8447, 3.849, 3.8034, 3.8245, 3.8078, 3.8439"
47,SpMax3_Bhs,float64,0.0,0.0,163.0,"4.1029, 4.1305, 4.5738, 4.57, 4.6173, 4.0663, 4.05, 4.6723, 4.0656, 3.8711"
48,SpMax3_Bhe,float64,0.0,0.0,168.0,"3.8813, 3.8772, 3.8746, 4.0541, 3.9344, 3.8957, 3.8926, 3.8644, 3.8627, 3.8854"
49,SpMin6_Bhi,float64,0.0,0.0,155.0,"1.3815, 1.3884, 1.4068, 1.162, 1.2748, 1.4635, 1.2952, 0.5827, 1.2698, 1.4623"
50,SpMax3_Bhm,float64,0.0,0.0,164.0,"3.8556, 3.8635, 3.825, 3.8563, 3.9383, 3.8715, 3.8737, 3.8915, 3.9064, 3.8186"
51,SpMax3_Bhi,float64,0.0,0.0,158.0,"3.9253, 3.878, 3.9097, 3.8723, 3.9423, 3.89, 3.909, 3.8689, 3.9108, 3.8946"
52,ETA_EtaP_F_L,float64,0.0,0.0,155.0,"0.2782, 0.3093, 0.2559, 0.3127, 0.3049, 0.2618, 0.2872, 0.3041, 0.3086, 0.2761"
53,mindCH2,float64,0.0,0.0,2.0,"0.0, 3.5148"
54,AATSC2e,float64,0.0,0.0,117.0,"0.006, 0.005, 0.0094, 0.0098, 0.0107, 0.0075, 0.0063, 0.0142, 0.0058, 0.0179"
55,AATSC2c,float64,0.0,0.0,60.0,"0.0007, -0.0001, 0.0009, 0.0, -0.0005, -0.0007, 0.0003, 0.0004, -0.0003, 0.001"
56,AATSC2m,float64,0.0,0.0,166.0,"-0.757, -0.1926, 0.0465, 6.0504, 0.6986, 0.2558, 1.8607, 2.7655, 2.0108, 3.2999"
57,AATSC2i,float64,0.0,0.0,163.0,"-0.1221, -0.0733, -0.0355, -0.0611, -0.2415, 0.2696, -0.096, 0.0196, 0.1211, -0.0528"
58,AATS5p,float64,0.0,0.0,171.0,"1.9081, 1.4706, 1.3297, 1.4975, 1.4189, 1.3174, 1.591, 1.3471, 1.383, 1.4604"
59,AATSC2v,float64,0.0,0.0,165.0,"-4.004, -4.1565, -3.4506, 3.6996, -3.9618, -0.8911, -0.1839, 1.311, 0.1032, -1.4038"
60,AATSC2p,float64,0.0,0.0,143.0,"-0.0088, -0.0205, -0.0119, -0.0134, 0.0126, -0.0042, 0.0059, -0.0218, 0.0176, 0.0025"
61,AATSC2s,float64,0.0,0.0,167.0,"0.2951, 0.0379, -0.0024, 0.003, -0.0255, 0.6186, 0.3114, 0.0304, 0.0254, 0.0152"
62,VABC,float64,0.0,0.0,166.0,"509.5859, 494.8352, 448.9705, 437.2103, 451.4722, 463.5374, 508.4141, 410.341, 425.6175, 547.5251"
63,maxdNH,float64,0.0,0.0,3.0,"0.0, 8.7272, 8.9304"
64,RotBtFrac,float64,0.0,0.0,91.0,"0.1667, 0.1463, 0.18, 0.1304, 0.1458, 0.122, 0.1333, 0.1429, 0.119, 0.102"
65,ATS4e,float64,0.0,0.0,171.0,"1453.5938, 1242.216, 1335.9386, 1451.3586, 1441.4165, 1276.0562, 1255.3961, 1683.1004, 1589.3631, 1133.1705"
66,ATS4m,float64,0.0,0.0,171.0,"19835.8193, 15992.5474, 11642.026, 14106.2886, 11775.6235, 10598.7005, 13383.2561, 13787.4433, 12922.2153, 11251.7854"
67,ATS4i,float64,0.0,0.0,171.0,"26862.1417, 23542.4902, 27499.8279, 29089.5664, 29595.965, 25747.2848, 25147.4827, 35218.2031, 32432.2377, 22660.9871"
68,ATS4s,float64,0.0,0.0,171.0,"759.7778, 668.4198, 578.3333, 659.4897, 520.8241, 542.8025, 515.6667, 712.8333, 601.3056, 489.4599"
69,ATS4p,float64,0.0,0.0,171.0,"347.5541, 260.9372, 232.7019, 271.5223, 278.652, 234.881, 249.9978, 293.4198, 305.6507, 221.9348"
70,ETA_Alpha,float64,0.0,0.0,135.0,"20.8, 20.4, 17.0333, 20.1, 20.9667, 17.8667, 19.0667, 17.7333, 15.1333, 17.3"
71,EE_Dzi,float64,0.0,0.0,171.0,"198.0675, 227.0135, 189.2118, 227.7043, 244.1974, 179.8007, 177.34, 259.7762, 227.8552, 193.554"
72,MAXDN,float64,0.0,0.0,168.0,"0.0, 5.7983, 1.8947, 2.3666, 1.7, 5.7821, 1.5733, 2.3046, 1.7385, 2.2987"
73,EE_Dzm,float64,0.0,0.0,171.0,"201.0915, 183.245, 196.4469, 234.6624, 243.4787, 163.5684, 180.661, 270.1588, 233.6499, 196.4885"
74,EE_Dze,float64,0.0,0.0,171.0,"201.1842, 222.6177, 196.7674, 236.2504, 249.3847, 180.1384, 180.773, 270.4503, 233.8118, 198.0368"
75,EE_Dzs,float64,0.0,0.0,171.0,"213.9751, 545.0212, 215.9819, 269.5249, 304.5484, 331.6161, 205.7192, 305.6304, 294.4283, 203.9095"
76,EE_Dzp,float64,0.0,0.0,171.0,"232.9974, 247.2093, 265.1579, 314.7254, 302.5646, 207.8984, 225.1691, 367.2085, 283.7825, 276.4085"
77,EE_Dzv,float64,0.0,0.0,171.0,"222.2215, 255.1665, 241.8, 288.5636, 287.5874, 205.8686, 208.7138, 335.5189, 268.1021, 246.7091"
78,ATS8e,float64,0.0,0.0,171.0,"1094.3304, 823.2446, 915.8935, 1426.6288, 1159.6799, 765.6348, 1214.2976, 1736.18, 1345.8822, 1048.1182"
79,maxsOH,float64,0.0,0.0,21.0,"0.0, 11.0926, 10.9933, 10.9827, 11.0973, 9.2146, 9.6712, 10.4708, 9.254, 9.3461"
80,minssssNp,float64,0.0,0.0,2.0,"0.0, 1.2767"
81,maxsOm,float64,0.0,0.0,13.0,"0.0, 11.5873, 11.5974, 11.5498, 12.0908, 11.7346, 11.0258, 11.2993, 11.0702, 11.2508"
82,MDEC-23,float64,0.0,0.0,162.0,"48.9891, 44.0116, 31.588, 14.9505, 34.2818, 43.1223, 30.0905, 42.7042, 44.0546, 36.4437"
83,MDEC-22,float64,0.0,0.0,137.0,"0.0, 22.955, 9.975, 23.3278, 6.2882, 20.8814, 31.7922, 29.5387, 21.3119, 18.814"
84,MDEC-24,float64,0.0,0.0,24.0,"0.0, 5.3684, 5.3649, 3.8902, 2.5984, 2.337, 4.9672, 2.1519, 1.7619, 1.4625"
85,ATS8s,float64,0.0,0.0,170.0,"526.6667, 554.0, 302.0432, 384.5, 708.7459, 393.7593, 302.5216, 451.7222, 640.8889, 529.6667"
86,ATS8v,float64,0.0,0.0,171.0,"35648.5015, 22665.7158, 22888.2923, 36940.3404, 29684.2361, 20128.5887, 32384.4471, 40730.508, 31554.6752, 29308.5348"
87,SP-6,float64,0.0,0.0,159.0,"0.0, 9.7135, 9.4758, 10.2605, 4.4464, 7.4475, 8.8396, 18.2418, 7.0885, 10.3665"
88,SP-7,float64,0.0,0.0,159.0,"0.0, 7.7532, 7.0353, 7.4806, 3.4441, 5.5308, 6.8546, 16.2633, 5.5828, 8.6103"
89,SHsNH2,float64,0.0,0.0,4.0,"0.0, 0.4427, 1.0057, 0.6252"
90,SP-5,float64,0.0,0.0,159.0,"0.0, 13.2209, 12.9731, 13.1815, 6.0075, 9.8961, 11.7948, 20.9413, 9.8143, 13.6955"
91,SP-2,float64,0.0,0.0,159.0,"0.0, 18.9343, 19.9962, 19.3323, 7.7729, 16.12, 18.1145, 22.2081, 15.5677, 18.2146"
92,SP-3,float64,0.0,0.0,158.0,"0.0, 16.9876, 17.5102, 18.08, 18.8575, 7.075, 13.9332, 16.8161, 14.0126, 16.6439"
93,SP-0,float64,0.0,0.0,129.0,"30.5344, 0.0, 28.9571, 24.8108, 25.3548, 30.1118, 27.6642, 25.6811, 23.5179, 25.2335"
94,SP-1,float64,0.0,0.0,143.0,"0.0, 21.2789, 20.4019, 18.0468, 19.653, 18.508, 21.2086, 20.0805, 20.4239, 19.853"
95,minHsOH,float64,0.0,0.0,21.0,"0.0, 0.3128, 0.3286, 0.3322, 0.3048, 0.6431, 0.5334, 0.4547, 0.6233, 0.6909"
96,ATSC8v,float64,0.0,0.0,171.0,"237.1491, 64.0125, 847.7322, -178.6377, -722.9392, -438.0029, -199.7166, 170.0641, 70.0074, -555.3495"
97,MATS2v,float64,0.0,0.0,160.0,"-0.0885, -0.0726, -0.0404, -0.0891, 0.0712, -0.0755, 0.0127, -0.0296, -0.0867, 0.0246"
98,ATSC8s,float64,0.0,0.0,171.0,"-0.6667, -37.5557, -13.7654, -33.0658, -7.5478, -35.4236, -3.4702, -2.4325, -11.1941, 7.6783"
99,MATS2p,float64,0.0,0.0,162.0,"-0.0911, 0.0164, 0.0481, -0.0554, -0.0607, 0.1117, -0.0291, -0.0987, -0.0288, 0.0727"
100,MATS2s,float64,0.0,0.0,165.0,"-0.0269, 0.0223, 0.1289, 0.1049, 0.0059, 0.0039, 0.2044, 0.0116, 0.1806, 0.0458"
101,ATSC8p,float64,0.0,0.0,171.0,"-0.2969, -1.5994, 3.6176, 0.7888, -6.4027, 0.2895, 0.396, -0.0141, 0.4775, -0.9675"
102,MATS2e,float64,0.0,0.0,162.0,"0.0681, 0.0807, 0.0311, 0.1649, 0.1692, 0.2861, 0.1304, 0.0825, 0.2948, 0.2811"
103,ATSC8e,float64,0.0,0.0,170.0,"-0.7819, 0.0573, -0.566, -0.6634, 0.0238, -1.0467, -0.3643, -0.8919, -0.1485, -0.2258"
104,ATSC8c,float64,0.0,0.0,169.0,"-0.0081, -0.1551, 0.1053, 0.2807, -0.001, -0.2331, -0.2454, -0.1927, 0.0567, 0.0441"
105,MATS2c,float64,0.0,0.0,168.0,"-0.0057, 0.0378, 0.1708, 0.0481, -0.0747, 0.1085, 0.0132, 0.1468, -0.0589, 0.0803"
106,MATS2m,float64,0.0,0.0,160.0,"-0.0249, 0.04, 0.0015, -0.0065, 0.1148, 0.0145, 0.1189, 0.0059, 0.0089, 0.0281"
107,ATSC8m,float64,0.0,0.0,171.0,"384.182, 943.0313, 265.3886, -257.224, -554.8337, -427.4926, -462.7457, 85.8694, -18.0472, -627.6578"
108,MATS2i,float64,0.0,0.0,161.0,"-0.084, -0.0741, -0.0524, -0.1494, -0.1388, -0.0423, 0.0795, 0.166, 0.0961, -0.0517"
109,ATSC8i,float64,0.0,0.0,171.0,"-13.8718, -21.914, 22.3587, 7.2588, -25.1428, -3.8679, 16.4674, -16.1949, 2.6817, -2.0421"
110,SpAD_Dt,float64,0.0,0.0,164.0,"1474.7562, 1297.6157, 1633.9653, 422.9251, 790.1646, 996.1411, 1003.2035, 1055.9654, 1126.0087, 937.6026"
111,ETA_Eta_R_L,float64,0.0,0.0,147.0,"21.2788, 20.4018, 18.0468, 19.6529, 17.4138, 21.2086, 20.4238, 19.8529, 8.3433, 18.7759"
112,SHdsCH,float64,0.0,0.0,47.0,"0.0, 0.8246, 1.1875, 0.9811, 0.484, 0.4439, 0.6209, 0.5759, 0.5819, 0.6098"
113,SaasN,float64,0.0,0.0,47.0,"0.0, 1.9205, 2.0952, 2.8632, 2.2228, 4.2863, 4.3113, 1.4521, 1.8311, 1.7093"
114,SC-4,float64,0.0,0.0,16.0,"0.0, 0.0833, 0.1667, 0.2887, 0.0556, 0.25, 0.2041, 0.1443, 0.1179, 0.125"
115,SaasC,float64,0.0,0.0,169.0,"0.0, 5.5822, 4.7988, 4.7763, 7.6463, 6.5256, 6.7474, 5.9772, 3.7054, 6.7873"
116,minaaCH,float64,0.0,0.0,166.0,"0.0, 1.4895, 1.5871, 1.2782, 1.7414, 1.5014, 1.9033, 1.5919, 1.6031, 1.7448"
117,AATSC3c,float64,0.0,0.0,52.0,"-0.0013, -0.0002, -0.0003, -0.0004, -0.0009, -0.0011, 0.0005, 0.0, 0.0001, -0.0001"
118,AATSC3e,float64,0.0,0.0,106.0,"-0.0029, -0.0043, -0.0031, -0.0012, -0.0025, -0.0026, -0.0037, -0.0008, -0.0035, -0.005"
119,AATSC3i,float64,0.0,0.0,165.0,"-0.0355, -0.0743, -0.0287, -0.2198, -0.1227, -0.356, -0.3285, -0.214, -0.2901, -0.248"
120,AATSC3m,float64,0.0,0.0,169.0,"2.8048, 1.5709, 3.4021, -1.0086, -2.3579, 0.372, -4.0394, 1.4622, -2.6087, -1.6052"
121,AATSC3s,float64,0.0,0.0,164.0,"-0.0519, 0.004, 0.04, 0.0783, -0.0406, 0.0226, -0.0546, -0.2053, -0.0023, 0.0843"
122,AATSC3p,float64,0.0,0.0,144.0,"-0.016, -0.0101, -0.0076, -0.0216, -0.0199, -0.0037, -0.0175, -0.003, -0.0044, 0.0093"
123,AATSC3v,float64,0.0,0.0,169.0,"-0.1275, 1.35, 3.5086, -1.3569, -3.931, -2.9141, -5.3107, -1.707, -6.0171, -2.0482"
124,SpMax2_Bhp,float64,0.0,0.0,161.0,"3.9515, 4.0711, 3.9043, 4.0297, 4.0851, 4.0741, 3.984, 3.8436, 3.8946, 4.1629"
125,AATS8e,float64,0.0,0.0,169.0,"7.7618, 7.7877, 7.8166, 7.6226, 7.8819, 7.3865, 7.5805, 7.5894, 7.5816, 7.5611"
126,AATS8i,float64,0.0,0.0,171.0,"149.5621, 152.9392, 162.0549, 158.7527, 153.1733, 153.2807, 156.793, 160.7413, 159.6228, 153.6712"
127,AATS8m,float64,0.0,0.0,171.0,"92.9158, 82.8582, 67.2022, 74.1469, 58.8652, 63.0336, 63.449, 56.8892, 55.3173, 80.1593"
128,AATS8s,float64,0.0,0.0,169.0,"2.6765, 3.1129, 3.9571, 2.9757, 3.2585, 3.9157, 2.508, 2.9953, 2.8233, 2.7986"
129,AATS8p,float64,0.0,0.0,170.0,"1.3683, 1.7139, 1.5573, 1.3613, 1.4306, 1.4761, 1.4977, 1.4731, 1.3085, 1.314"
130,AATS8v,float64,0.0,0.0,171.0,"254.6322, 209.8677, 193.9686, 204.0903, 189.0716, 199.293, 202.4028, 177.8625, 177.2735, 217.1003"
131,VE3_Dt,float64,0.0,0.0,163.0,"-8.3966, -5.7152, -154.141, -4.311, -123.9632, -7.7709, -13.1156, -167.1241, -14.1206, -6.1052"
132,XLogP,float64,0.0,0.0,165.0,"3.327, 0.991, 4.589, 2.849, 2.933, 2.158, -0.094, 3.62, 2.234, 1.686"
133,SpMax2_Bhi,float64,0.0,0.0,160.0,"4.0573, 3.9435, 4.2256, 4.0561, 4.1645, 4.0497, 4.2285, 3.944, 4.1037, 3.9976"
134,maxssCH2,float64,0.0,0.0,100.0,"0.0, 0.7321, 0.8026, 0.8006, 0.2887, 0.3934, 0.8072, 0.6867, 0.7679, 0.6311"
135,minaaS,float64,0.0,0.0,12.0,"0.0, -1.1871, -1.8213, -1.6243, -1.8075, -1.6505, -1.5988, -2.0683, -1.467, -1.9145"
136,SpMax4_Bhv,float64,0.0,0.0,159.0,"3.6586, 3.6978, 3.7631, 3.6138, 3.6109, 3.6731, 3.6608, 3.6818, 3.7045, 3.7522"
137,SpMax4_Bhs,float64,0.0,0.0,165.0,"3.9825, 4.1263, 4.4768, 3.8676, 3.9707, 4.5009, 4.6641, 4.6157, 3.907, 3.8379"
138,SpMax4_Bhp,float64,0.0,0.0,160.0,"3.6667, 3.707, 3.8083, 3.6788, 3.7682, 3.7707, 3.5912, 3.5818, 3.8116, 3.7855"
139,SpMax4_Bhm,float64,0.0,0.0,162.0,"3.6477, 3.4701, 3.6856, 3.7321, 3.7368, 3.7114, 3.7669, 3.7826, 3.737, 3.7724"
140,minHaaNH,float64,0.0,0.0,24.0,"0.0, 0.2929, 0.2909, 0.3501, 0.431, 0.5094, 0.3776, 0.6097, 0.3594, 0.4031"
141,SpMax4_Bhi,float64,0.0,0.0,160.0,"3.7349, 3.756, 3.7821, 3.8519, 3.7601, 3.7997, 3.8758, 3.8137, 3.8296, 3.8146"
142,minaaN,float64,0.0,0.0,92.0,"0.0, 4.9169, 3.8682, 3.5986, 4.1314, 4.6082, 4.6126, 4.1143, 4.8943, 4.8619"
143,SpMax4_Bhe,float64,0.0,0.0,162.0,"3.7088, 3.7536, 3.8095, 3.6813, 3.739, 3.7044, 3.8599, 3.7944, 3.8276, 3.7923"
144,StsC,float64,0.0,0.0,7.0,"0.0, 4.4113, 4.379, 4.795, 4.511, 4.9494, 2.1265"
145,SssCH2,float64,0.0,0.0,105.0,"0.0, 1.6732, 3.8445, 1.3251, 2.4667, 0.4261, 0.7281, 3.1985, 3.2457, 0.7679"
146,maxHdNH,float64,0.0,0.0,3.0,"0.0, 0.4292, 0.395"
147,MATS1p,float64,0.0,0.0,157.0,"0.0778, 0.0082, 0.0398, -0.0581, -0.0522, 0.0001, -0.0396, 0.0424, 0.0186, -0.0661"
148,R_TpiPCTPC,float64,0.0,0.0,165.0,"5.662, 22.3815, 7.1506, 6.3882, 3.924, 20.3566, 3.9304, 4.5635, 11.1108, 9.3718"
149,MATS1s,float64,0.0,0.0,155.0,"-0.0214, -0.0482, -0.0578, -0.0362, -0.0622, -0.0683, -0.0104, -0.0644, -0.0767, -0.0114"
150,MATS1v,float64,0.0,0.0,149.0,"0.0684, 0.0218, 0.033, 0.0141, 0.0339, 0.0208, 0.0373, -0.007, 0.0332, 0.0393"
151,JGI10,float64,0.0,0.0,55.0,"0.0065, 0.0066, 0.0063, 0.0059, 0.0064, 0.0069, 0.0057, 0.0072, 0.0, 0.0048"
152,MATS1c,float64,0.0,0.0,166.0,"-0.4421, -0.4484, -0.4447, -0.4425, -0.476, -0.4347, -0.5532, -0.4495, -0.2342, -0.4147"
153,MATS1e,float64,0.0,0.0,159.0,"-0.0346, -0.0261, -0.0226, 0.2105, -0.0157, -0.0104, -0.0406, 0.1071, -0.0307, -0.0059"
154,VR2_DzZ,float64,0.0,0.0,171.0,"25.3775, 12.1976, 13.4636, 15.8239, 14.4682, 14.6727, 18.1443, 11.1788, 12.0586, 11.0458"
155,MATS1i,float64,0.0,0.0,158.0,"0.0803, -0.0607, -0.0914, 0.0457, -0.1334, -0.0593, 0.0164, -0.1471, -0.1317, -0.0536"
156,MATS1m,float64,0.0,0.0,154.0,"0.044, 0.0689, 0.016, 0.0699, 0.0515, 0.0755, 0.0466, 0.0688, 0.1696, 0.0724"
157,MDEC-34,float64,0.0,0.0,23.0,"0.0, 3.3518, 3.3732, 2.1748, 3.4722, 4.654, 5.3696, 1.6162, 1.8963, 1.4573"
158,MDEC-33,float64,0.0,0.0,156.0,"23.499, 10.4134, 12.4851, 19.9337, 10.8013, 26.3497, 24.0107, 22.923, 10.6179, 23.5913"
159,VR2_Dze,float64,0.0,0.0,171.0,"25.3702, 13.9489, 13.525, 15.299, 14.9767, 16.7604, 18.0572, 11.1807, 12.0616, 10.8801"
160,VR2_Dzm,float64,0.0,0.0,171.0,"25.3764, 12.1973, 13.4876, 15.8231, 14.4702, 14.6978, 18.1357, 11.179, 12.059, 11.0436"
161,VR2_Dzs,float64,0.0,0.0,170.0,"11.0012, 43.3885, 12.5638, 19.638, 8.0075, 14.5975, 10.6787, 12.1234, 13.3781, 32.8374"
162,VR2_Dzp,float64,0.0,0.0,171.0,"24.5288, 14.5195, 11.4529, 13.8685, 15.9945, 21.5783, 15.8736, 14.3091, 12.2947, 9.617"
163,ATS5e,float64,0.0,0.0,171.0,"1408.5019, 1251.8476, 1309.9289, 1450.2115, 1466.1035, 1171.3646, 1265.7684, 1632.4755, 1738.0827, 1084.3564"
164,gmin,float64,0.0,0.0,167.0,"0.0, -0.7095, -5.4743, -0.3285, -0.39, 0.0704, -0.4632, -0.7851, -1.7395, -5.4581"
165,VR2_D,float64,0.0,0.0,164.0,"13.6551, 22.6367, 90917.8013, 8.7332, 23.5074, 12.448, 12.3238, 16.2237, 17.8187, 14.6379"
166,ATS5m,float64,0.0,0.0,171.0,"18932.5551, 13736.3774, 10883.4321, 14859.2757, 11553.5725, 8770.4504, 14073.089, 13600.4833, 12802.8804, 10602.3989"
167,ATS5p,float64,0.0,0.0,171.0,"339.6464, 225.0074, 223.3901, 277.0404, 278.1057, 202.8819, 256.1451, 286.9326, 320.8618, 207.3816"
168,ATS5s,float64,0.0,0.0,170.0,"624.4444, 734.3333, 708.8272, 663.1852, 518.3025, 466.7716, 525.5, 644.0833, 626.1667, 412.3827"
169,ATS5v,float64,0.0,0.0,171.0,"51592.2938, 31543.5599, 31109.4924, 40368.2559, 36228.1953, 26628.0508, 37809.3321, 40052.8294, 42689.0001, 28299.5335"

In [37]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
MATS3v,171.0,-0.031244,6.355880e-02,-0.3115,1.411000e-01
nHBint10,171.0,0.315789,7.629177e-01,0.0000,4.000000e+00
MATS3s,171.0,-0.001001,6.392783e-02,-0.1846,2.181000e-01
MATS3p,171.0,-0.061501,7.289129e-02,-0.3485,1.290000e-01
nHBDon_Lipinski,171.0,0.994152,1.108773e+00,0.0000,6.000000e+00
minHBint8,171.0,0.677770,1.647322e+00,0.0000,8.141400e+00
MATS3e,171.0,-0.025418,7.864469e-02,-0.2119,2.495000e-01
MATS3c,171.0,-0.053289,1.094628e-01,-0.4729,2.122000e-01
minHBint2,171.0,1.569251,2.497362e+00,-0.7087,7.740800e+00
MATS3m,171.0,0.003226,7.407627e-02,-0.1987,1.684000e-01
minHBint6,171.0,0.520492,1.257976e+00,0.0000,6.462100e+00
minHBint7,171.0,0.723782,1.827843e+00,-0.9139,8.822100e+00
minHBint4,171.0,0.718278,1.668787e+00,-1.0388,7.266200e+00
MATS3i,171.0,-0.081831,9.153891e-02,-0.3510,1.780000e-01
VR3_Dt,171.0,28.644151,1.258271e+01,7.7282,7.206780e+01
SpMax8_Bhi,171.0,3.123065,1.983508e-01,1.9163,3.359700e+00
SdsN,171.0,1.706996,3.159232e+00,0.0000,1.325480e+01
SpMax8_Bhm,171.0,3.019816,2.241608e-01,1.6085,3.266400e+00
SpMax8_Bhe,171.0,3.082035,2.082587e-01,1.8102,3.315800e+00
ECCEN,171.0,1158.654971,2.708338e+02,199.0000,1.783000e+03
MDEC-14,171.0,0.080663,4.880176e-01,0.0000,5.366600e+00
SpMax8_Bhs,171.0,3.386848,3.136425e-01,2.2356,4.110600e+00
SpMax8_Bhp,171.0,2.910943,2.347011e-01,1.3239,3.204400e+00
SpMax8_Bhv,171.0,2.918874,2.314912e-01,1.3676,3.212800e+00
MDEC-11,171.0,0.100580,3.548214e-01,0.0000,3.879600e+00
MDEC-12,171.0,1.786255,2.024710e+00,0.0000,7.241800e+00
MDEC-13,171.0,1.998240,2.592965e+00,0.0000,1.155920e+01
VR2_Dt,171.0,12530.867470,4.392829e+04,5.5937,4.418654e+05
BIC5,171.0,0.853699,5.178575e-02,0.6291,9.201000e-01
ATS7s,171.0,508.944899,1.517033e+02,61.3333,1.018958e+03
ATS7p,171.0,221.364883,6.396429e+01,12.3680,4.010535e+02
ATS7v,171.0,30651.982409,8.605418e+03,2114.7852,5.662685e+04
ATS7i,171.0,24508.016474,7.975336e+03,2896.8102,4.438565e+04
ATS7m,171.0,10522.977021,2.987504e+03,688.3376,1.834878e+04
ATS7e,171.0,1195.526461,3.647721e+02,136.7417,2.069838e+03
mintN,171.0,0.289836,1.676366e+00,0.0000,1.053960e+01
nHsNH2,171.0,0.023392,1.863967e-01,0.0000,2.000000e+00
khs.sssCH,171.0,0.672515,1.078291e+00,0.0000,5.000000e+00
minHBint3,171.0,0.201878,9.246670e-01,-0.8867,8.105000e+00
maxdssC,171.0,0.230207,3.523607e-01,0.0000,1.412600e+00
nT6Ring,171.0,4.953216,1.417591e+00,0.0000,8.000000e+00
minHBint5,171.0,0.518080,1.361909e+00,-0.7046,7.503500e+00
nF8Ring,171.0,0.070175,2.782074e-01,0.0000,2.000000e+00
minssCH2,171.0,0.262209,3.493925e-01,-0.4039,1.269300e+00
SpMax_DzZ,171.0,197.485398,5.004862e+01,0.0000,2.953160e+02
ETA_EtaP,171.0,0.832961,1.224487e-01,0.4690,1.108100e+00
nHsOH,171.0,0.187135,6.774159e-01,0.0000,6.000000e+00
SpMin1_Bhe,171.0,2.015347,7.754008e-02,1.8782,2.332400e+00
maxHother,171.0,0.615785,9.891208e-02,0.0000,8.422000e-01
nHBAcc_Lipinski,171.0,7.204678,1.987958e+00,2.0000,1.400000e+01
StN,171.0,0.526789,3.136970e+00,0.0000,2.129410e+01
khs.aaS,171.0,0.064327,2.460559e-01,0.0000,1.000000e+00
khs.aaO,171.0,0.111111,3.977058e-01,0.0000,3.000000e+00
khs.aaN,171.0,1.187135,1.376294e+00,0.0000,7.000000e+00
Sare,171.0,61.013287,9.493701e+00,24.2440,7.941600e+01
SHAvin,171.0,0.129085,2.979039e-01,0.0000,1.582200e+00
SpMax3_Bhv,171.0,3.784153,1.246652e-01,3.0031,3.982800e+00
SpMax3_Bhp,171.0,3.784172,1.269576e-01,2.9822,4.002900e+00
SpMax3_Bhs,171.0,4.288991,3.212847e-01,3.4378,4.993800e+00
SpMax3_Bhe,171.0,3.862561,1.109595e-01,3.1907,4.054100e+00
SpMin6_Bhi,171.0,1.292263,1.682596e-01,0.3102,1.669500e+00
SpMax3_Bhm,171.0,3.836958,1.227891e-01,3.1498,4.071700e+00
SpMax3_Bhi,171.0,3.887102,1.077870e-01,3.2426,4.079200e+00
ETA_EtaP_F_L,171.0,0.283848,2.592269e-02,0.2018,3.302000e-01
mindCH2,171.0,0.020554,2.687835e-01,0.0000,3.514800e+00
AATSC2e,171.0,0.011473,1.229304e-02,-0.0060,1.051000e-01
AATSC2c,171.0,0.000811,1.542551e-03,-0.0035,5.300000e-03
AATSC2m,171.0,2.063015,2.746873e+00,-2.0616,1.170240e+01
AATSC2i,171.0,0.002350,2.240569e-01,-0.3803,1.530400e+00
nsBr,171.0,0.005848,7.647191e-02,0.0000,1.000000e+00
AATS5p,171.0,1.464854,1.340978e-01,1.1008,1.908100e+00
AATSC2v,171.0,-0.184427,3.928329e+00,-7.4048,1.446120e+01
AATSC2p,171.0,-0.001894,1.966043e-02,-0.0418,5.710000e-02
AATSC2s,171.0,0.135098,3.017574e-01,-0.1199,2.546400e+00
VABC,171.0,440.891096,6.578428e+01,161.0673,5.475251e+02
maxdNH,171.0,0.103261,9.520650e-01,0.0000,8.930400e+00
khs.ddsN,171.0,0.076023,2.870919e-01,0.0000,2.000000e+00
RotBtFrac,171.0,0.144713,6.439254e-02,0.0000,4.545000e-01
ATS4e,171.0,1283.943116,2.772209e+02,392.3390,2.149939e+03
ATS4m,171.0,12359.091329,2.508721e+03,3633.9093,1.983582e+04
nFRing,171.0,5.538012,1.145336e+01,0.0000,1.400000e+02
ATS4i,171.0,25801.735060,6.009832e+03,7738.5317,4.698959e+04
ATS4s,171.0,568.456767,1.331322e+02,164.5556,1.005750e+03
ATS4p,171.0,245.285136,5.163408e+01,67.6761,4.039097e+02
ETA_Alpha,171.0,18.193759,2.573944e+00,7.0905,2.193330e+01
khs.sssN,171.0,1.169591,1.040593e+00,0.0000,4.000000e+00
EE_Dzi,171.0,195.144808,4.814992e+01,0.0000,2.868385e+02
MAXDN,171.0,2.445382,1.324287e+00,0.0000,6.359500e+00
EE_Dzm,171.0,197.492489,5.005524e+01,0.0000,2.953742e+02
EE_Dze,171.0,200.055095,4.993923e+01,0.0000,2.957390e+02
EE_Dzs,171.0,234.689470,7.582078e+01,0.0000,5.450212e+02
EE_Dzp,171.0,262.006421,7.047983e+01,0.0000,4.335789e+02
EE_Dzv,171.0,240.582718,6.291165e+01,0.0000,3.708415e+02
ATS8e,171.0,1117.604982,3.573868e+02,50.9656,1.981608e+03
maxsOH,171.0,1.210462,3.347656e+00,0.0000,1.135810e+01
minssssNp,171.0,0.007466,9.763169e-02,0.0000,1.276700e+00
maxsOm,171.0,0.799613,2.920385e+00,0.0000,1.209080e+01
MDEC-23,171.0,39.135014,1.008614e+01,7.8612,6.525600e+01
MDEC-22,171.0,16.131371,9.313449e+00,0.0000,3.623970e+01
MDEC-24,171.0,0.550030,1.465493e+00,0.0000,6.175100e+00
nFG12HeteroRing,171.0,1.362573,3.191460e+00,0.0000,3.200000e+01
ATS8s,171.0,464.059342,1.413130e+02,26.0000,8.251250e+02
ATS8v,171.0,28311.786932,8.547669e+03,652.4182,5.205846e+04
SP-6,171.0,8.299644,2.515473e+00,0.0000,1.824180e+01
SP-7,171.0,6.557322,2.171011e+00,0.0000,1.626330e+01
SHsNH2,171.0,0.012126,9.619666e-02,0.0000,1.005700e+00
SP-5,171.0,11.255061,3.123124e+00,0.0000,2.094130e+01
SP-2,171.0,16.639594,3.969708e+00,0.0000,2.220810e+01
SP-3,171.0,14.950604,3.741143e+00,0.0000,2.236200e+01
SP-0,171.0,25.272005,6.018061e+00,0.0000,3.140470e+01
SP-1,171.0,17.910909,4.301346e+00,0.0000,2.250800e+01
minHsOH,171.0,0.052649,1.536403e-01,0.0000,6.909000e-01
ATSC8v,171.0,-174.590725,6.928967e+02,-2206.4650,3.598947e+03
MATS2v,171.0,-0.005382,8.175490e-02,-0.1527,2.849000e-01
ATSC8s,171.0,-6.269639,3.005532e+01,-120.8036,9.350820e+01
MATS2p,171.0,-0.009956,8.249436e-02,-0.1821,2.445000e-01
MATS2s,171.0,0.069091,9.415957e-02,-0.0990,4.792000e-01
ATSC8p,171.0,-0.838499,3.000779e+00,-10.0183,1.083250e+01
MATS2e,171.0,0.152136,1.059596e-01,-0.2382,5.292000e-01
ATSC8e,171.0,-0.351548,1.426684e+00,-5.4045,5.473300e+00
ATSC8c,171.0,-0.034970,2.003132e-01,-0.8375,5.650000e-01
MATS2c,171.0,0.051550,1.223595e-01,-0.3124,3.820000e-01
MATS2m,171.0,0.055047,7.312579e-02,-0.0667,3.350000e-01
topoDiameter,171.0,17.040936,2.675283e+00,7.0000,2.400000e+01
ATSC8m,171.0,-214.215268,7.052584e+02,-3652.7572,3.006524e+03
MATS2i,171.0,-0.006192,1.052461e-01,-0.2150,3.766000e-01
ATSC8i,171.0,-3.729999,2.171322e+01,-62.2383,6.130750e+01
ntN,171.0,0.052632,3.117910e-01,0.0000,2.000000e+00
khs.ssCH2,171.0,2.473684,2.831162e+00,0.0000,1.400000e+01
SpAD_Dt,171.0,1205.815858,3.781610e+02,238.6680,3.444015e+03
ETA_Eta_R_L,171.0,18.564098,2.633207e+00,7.3760,2.250790e+01
SHdsCH,171.0,0.235961,4.529646e-01,0.0000,2.631400e+00
SaasN,171.0,0.618078,1.149362e+00,0.0000,4.866500e+00
SC-4,171.0,0.040853,9.753932e-02,0.0000,5.774000e-01
SaasC,171.0,4.291185,2.469410e+00,-4.9669,1.219350e+01
minaaCH,171.0,1.602589,3.266879e-01,0.0000,2.208800e+00
AATSC3c,171.0,-0.000768,1.468078e-03,-0.0067,2.500000e-03
AATSC3e,171.0,-0.002487,5.471300e-03,-0.0221,1.150000e-02
AATSC3i,171.0,-0.134929,1.509579e-01,-0.5670,2.805000e-01
AATSC3m,171.0,-0.070870,2.643989e+00,-8.7730,5.350800e+00
AATSC3s,171.0,-0.016894,9.839464e-02,-0.4290,1.752000e-01
AATSC3p,171.0,-0.014671,1.736059e-02,-0.0813,2.940000e-02
AATSC3v,171.0,-1.540519,3.098198e+00,-15.8140,7.155300e+00
SpMax2_Bhp,171.0,3.920800,1.161355e-01,3.4228,4.162900e+00
AATS8e,171.0,7.723254,4.512086e-01,7.1137,1.274140e+01
AATS8i,171.0,158.010158,6.892665e+00,148.4702,2.162291e+02
AATS8m,171.0,67.408006,2.017795e+01,9.1588,2.309934e+02
AATS8s,171.0,3.456208,2.624595e+00,1.7591,3.631250e+01
AATS8p,171.0,1.411591,1.826823e-01,0.5710,1.889300e+00
AATS8v,171.0,195.526226,2.893278e+01,66.6878,2.701533e+02
VE3_Dt,171.0,-32.311274,5.149398e+01,-167.7416,-2.067100e+00
XLogP,171.0,2.993339,1.525161e+00,-0.3270,7.196000e+00
SpMax2_Bhi,171.0,4.018668,8.821177e-02,3.6056,4.228500e+00
maxssCH2,171.0,0.456720,4.239263e-01,0.0000,1.407300e+00
minaaS,171.0,-0.112743,4.366152e-01,-2.1212,0.000000e+00
SpMax4_Bhv,171.0,3.622745,1.683568e-01,2.8378,3.859900e+00
SpMax4_Bhs,171.0,4.106869,3.272155e-01,3.2173,4.828200e+00
SpMax4_Bhp,171.0,3.623998,1.734190e-01,2.7952,3.853100e+00
SpMax4_Bhm,171.0,3.680777,1.556536e-01,2.9788,4.019700e+00
minHaaNH,171.0,0.051389,1.334817e-01,0.0000,6.097000e-01
SpMax4_Bhi,171.0,3.750196,1.398109e-01,3.1112,3.931400e+00
minaaN,171.0,2.427775,2.274623e+00,0.0000,5.173800e+00
SpMax4_Bhe,171.0,3.720929,1.437745e-01,3.0668,3.920700e+00
StsC,171.0,0.147206,7.944270e-01,0.0000,4.949400e+00
SssCH2,171.0,1.661502,2.488746e+00,-0.5911,1.854950e+01
maxHdNH,171.0,0.004820,4.447505e-02,0.0000,4.292000e-01
MATS1p,171.0,0.004227,5.573063e-02,-0.1084,3.068000e-01
R_TpiPCTPC,171.0,10.469081,5.372464e+00,3.3873,2.653650e+01
MATS1s,171.0,-0.046733,6.128673e-02,-0.2256,2.524000e-01
MATS1v,171.0,0.027392,2.975432e-02,-0.0273,2.029000e-01
JGI10,171.0,0.006249,1.815371e-03,0.0000,9.600000e-03
MATS1c,171.0,-0.464899,1.113137e-01,-0.6996,-3.650000e-02
MATS1e,171.0,0.023715,8.708720e-02,-0.1714,3.804000e-01
VR2_DzZ,171.0,11190.811801,4.930224e+04,0.0000,4.359020e+05
MATS1i,171.0,-0.047423,1.032956e-01,-0.3332,3.132000e-01
MATS1m,171.0,0.061598,4.156153e-02,-0.0788,2.045000e-01
MDEC-34,171.0,0.441039,1.173697e+00,0.0000,6.311900e+00
MDEC-33,171.0,17.987819,9.077481e+00,0.0000,8.451790e+01
VR2_Dze,171.0,11190.322302,4.930234e+04,0.0000,4.359020e+05
VR2_Dzm,171.0,11190.697178,4.930227e+04,0.0000,4.359020e+05
VR2_Dzs,171.0,3464.722048,3.426144e+04,0.0000,4.359017e+05
VR2_Dzp,171.0,11184.575122,4.930365e+04,0.0000,4.359025e+05
khs.ssssC,171.0,0.157895,3.965798e-01,0.0000,2.000000e+00
nTG12Ring,171.0,2.239766,9.751371e+00,0.0000,1.210000e+02
khs.ssssN,171.0,0.011696,1.529438e-01,0.0000,2.000000e+00
ATS5e,171.0,1272.160721,3.063456e+02,336.8069,1.992878e+03
gmin,171.0,-1.085842,1.627209e+00,-6.0354,1.202500e+00
VR2_D,171.0,17250.403500,6.099545e+04,7.8120,4.418650e+05
ATS5m,171.0,11785.906006,2.722758e+03,3006.1356,1.903461e+04
ATS5p,171.0,239.367486,5.902322e+01,49.5348,3.975281e+02
ATS5s,171.0,554.309005,1.380260e+02,146.4444,9.758889e+02
ATS5v,171.0,33724.666235,8.020893e+03,7489.7229,5.362892e+04
AATSC5p,171.0,-0.001781,2.468278e-02,-0.0865,6.610000e-02
TpiPC,171.0,9.867456,6.640434e-01,8.3037,1.202150e+01
maxsCH3,171.0,1.025959,9.797699e-01,0.0000,2.329600e+00
SdS,171.0,0.003534,4.621198e-02,0.0000,6.043000e-01
khs.ssO,171.0,0.438596,8.047845e-01,0.0000,4.000000e+00
ETA_Eta_F_L,171.0,10.827160,1.824233e+00,4.2636,1.432220e+01
khs.ssS,171.0,0.052632,2.239527e-01,0.0000,1.000000e+00
SdO,171.0,29.220506,1.965041e+01,0.0000,8.104410e+01
VE2_Dt,171.0,0.003741,3.700647e-03,0.0000,1.580000e-02
maxHtCH,171.0,0.003521,4.604374e-02,0.0000,6.021000e-01
ETA_dEpsilon_B,171.0,0.090856,2.120218e-02,0.0443,1.464000e-01
ETA_dEpsilon_A,171.0,0.175942,3.920625e-02,0.0568,3.154000e-01
ETA_dEpsilon_D,171.0,0.013785,1.549848e-02,0.0000,7.660000e-02
SsNH2,171.0,0.143927,1.146601e+00,0.0000,1.224270e+01
StCH,171.0,0.063778,8.340027e-01,0.0000,1.090600e+01
SsCH3,171.0,1.824542,2.294850e+00,0.0000,1.275390e+01
CIC5,171.0,0.484829,3.382467e-01,0.0000,1.795500e+00
CIC4,171.0,0.572261,3.533179e-01,0.0820,1.900800e+00
CIC1,171.0,2.631502,4.306563e-01,0.9686,3.651400e+00
CIC0,171.0,4.382917,3.316082e-01,2.7837,5.254200e+00
CIC3,171.0,0.926010,3.765844e-01,0.1698,2.256300e+00
CIC2,171.0,1.754835,4.508120e-01,0.4111,3.072600e+00
nF10HeteroRing,171.0,0.742690,9.661274e-01,0.0000,6.000000e+00
maxssO,171.0,1.693558,2.653154e+00,0.0000,6.808500e+00
WPOL,171.0,70.736842,1.304047e+01,24.0000,1.160000e+02
n5HeteroRing,171.0,1.356725,1.026816e+00,0.0000,5.000000e+00
maxHAvin,171.0,0.109099,2.269648e-01,0.0000,7.942000e-01
fragC,171.0,507.732807,1.541978e+02,49.0500,1.179080e+03
ETA_Eta_B_RC,171.0,0.994649,1.999055e-01,0.3455,1.562700e+00
AATS7m,171.0,69.546873,1.643363e+01,31.1171,1.533993e+02
SpDiam_Dt,171.0,822.676130,2.347925e+02,155.0004,1.814815e+03
SdssC,171.0,-0.335672,1.215628e+00,-5.0633,5.259200e+00
ETA_Epsilon_3,171.0,0.447749,2.721621e-03,0.4391,4.586000e-01
AATS7i,171.0,157.877174,6.291664e+00,148.7015,2.107654e+02
AATS7e,171.0,7.733903,2.439430e-01,7.1782,9.340400e+00
nT9Ring,171.0,1.345029,1.257082e+00,0.0000,5.000000e+00
minsCl,171.0,0.062028,2.016057e-01,0.0000,8.746000e-01
AATS7v,171.0,199.544729,2.898519e+01,100.6805,2.870550e+02
AATS7s,171.0,3.386235,7.622401e-01,1.9212,6.572500e+00
AATS7p,171.0,1.433113,1.798344e-01,0.5377,2.009500e+00
nHdCH2,171.0,0.005848,7.647191e-02,0.0000,1.000000e+00
ETA_Epsilon_5,171.0,0.803224,3.443107e-02,0.7191,9.417000e-01
ETA_Epsilon_4,171.0,0.532831,2.795612e-02,0.4600,6.467000e-01
SsssCH,171.0,-0.276071,7.202134e-01,-3.4037,2.682200e+00
maxHsOH,171.0,0.053801,1.558720e-01,0.0000,6.909000e-01
GATS1v,171.0,0.821107,8.915346e-02,0.5592,1.045400e+00
maxaaaC,171.0,0.695216,5.109225e-01,0.0000,1.506600e+00
GATS1s,171.0,0.588929,1.117857e-01,0.4477,1.083100e+00
minsNH2,171.0,0.108129,8.139499e-01,0.0000,6.760100e+00
BIC4,171.0,0.839952,5.546014e-02,0.6127,9.147000e-01
SpMin7_Bhs,171.0,1.217247,1.993103e-01,0.0035,1.476700e+00
SpMin7_Bhp,171.0,1.394719,1.660885e-01,0.5644,1.690200e+00
SpMin7_Bhv,171.0,1.392451,1.640677e-01,0.5749,1.696900e+00
nHtCH,171.0,0.011696,1.529438e-01,0.0000,2.000000e+00
GATS1e,171.0,0.643969,1.245415e-01,0.3330,1.141800e+00
mintsC,171.0,0.079342,4.178317e-01,0.0000,2.474700e+00
GATS1c,171.0,1.418488,1.328504e-01,0.9836,1.815200e+00
SpMin7_Bhm,171.0,1.356494,1.656301e-01,0.5363,1.607700e+00
GATS1m,171.0,0.668149,7.231206e-02,0.4417,8.897000e-01
SpMin7_Bhe,171.0,1.194090,1.886091e-01,0.1424,1.474800e+00
GATS1i,171.0,1.074105,1.600955e-01,0.5876,1.598000e+00
maxtsC,171.0,0.080301,4.231132e-01,0.0000,2.474700e+00
minHAvin,171.0,0.108908,2.264722e-01,0.0000,7.880000e-01
MDEC-44,171.0,0.002437,2.291589e-02,0.0000,2.500000e-01
AATS2v,171.0,264.812285,2.328324e+01,210.3416,3.327257e+02
SPC-6,171.0,17.719431,5.993424e+00,0.0000,3.955310e+01
SPC-4,171.0,6.746144,1.894873e+00,0.0000,1.143640e+01
SPC-5,171.0,11.753075,3.568034e+00,0.0000,2.241830e+01
SpAD_D,171.0,526.599495,1.176118e+02,105.6356,7.785257e+02
MATS6c,171.0,0.000530,1.360144e-01,-0.2838,4.556000e-01
ETA_BetaP_s,171.0,0.654249,2.059137e-02,0.6029,7.222000e-01
minaasC,171.0,0.232642,4.464715e-01,-1.0461,1.389100e+00
minaasN,171.0,0.485596,8.148875e-01,0.0000,2.433300e+00
minssNH,171.0,1.145885,1.443032e+00,0.0000,3.696800e+00
nT7HeteroRing,171.0,0.052632,2.488363e-01,0.0000,2.000000e+00
RotBFrac,171.0,0.106015,4.466169e-02,0.0000,3.030000e-01
nF10Ring,171.0,1.549708,1.718973e+00,0.0000,1.300000e+01
ETA_BetaP_ns,171.0,0.791892,1.197621e-01,0.4516,1.024200e+00
nH,171.0,23.304094,6.037231e+00,7.0000,4.200000e+01
nL,171.0,0.081871,5.469369e-01,0.0000,6.000000e+00
nN,171.0,4.134503,1.887897e+00,0.0000,9.000000e+00
nO,171.0,3.070175,1.639867e+00,0.0000,8.000000e+00
nA,171.0,0.116959,4.033741e-01,0.0000,2.000000e+00
nC,171.0,30.374269,4.858011e+00,11.0000,4.000000e+01
nF,171.0,0.263158,6.994027e-01,0.0000,3.000000e+00
nX,171.0,0.368421,7.813618e-01,0.0000,3.000000e+00
nQ,171.0,0.029240,1.689727e-01,0.0000,1.000000e+00
nS,171.0,0.210526,4.628623e-01,0.0000,2.000000e+00
nV,171.0,0.058480,3.379454e-01,0.0000,2.000000e+00
ATS1m,171.0,7221.804160,1.056131e+03,2900.9915,9.667641e+03
mindsN,171.0,1.225025,2.064788e+00,0.0000,5.228700e+00
SHCsats,171.0,1.837405,1.958720e+00,0.0000,6.538600e+00
SHCsatu,171.0,0.670709,1.013092e+00,0.0000,4.647200e+00
CrippenMR,171.0,146.236654,2.693749e+01,0.0000,1.805565e+02
GATS1p,171.0,0.910332,1.255933e-01,0.5705,1.205700e+00
SRW10,171.0,10.784464,2.398990e-01,9.6922,1.148430e+01
ETA_dPsi_A,171.0,0.129347,3.507687e-02,0.0256,2.629000e-01
AATS6m,171.0,72.364237,1.509508e+01,40.0774,1.449962e+02
AATS6i,171.0,157.077920,4.700179e+00,146.8943,1.789124e+02
AATS6e,171.0,7.756127,2.164124e-01,7.2369,8.482100e+00
minsBr,171.0,0.001096,1.433084e-02,0.0000,1.874000e-01
nF9HeteroRing,171.0,1.181287,1.196515e+00,0.0000,5.000000e+00
SpMin7_Bhi,171.0,1.155068,1.936183e-01,0.0627,1.407800e+00
AATS6v,171.0,205.599443,2.651951e+01,144.3076,2.961831e+02
AATS6p,171.0,1.464387,1.543825e-01,0.8950,2.026000e+00
AATS6s,171.0,3.411623,7.657415e-01,2.0177,6.699500e+00
naAromAtom,171.0,24.918129,6.125575e+00,6.0000,4.200000e+01
nBase,171.0,0.327485,8.733331e-01,-1.0000,5.000000e+00
minHBint10,171.0,0.306003,1.019409e+00,-0.8482,6.429900e+00
SpDiam_DzZ,171.0,295.881008,7.780502e+01,0.0000,4.801856e+02
SaaNH,171.0,0.606626,1.638662e+00,0.0000,7.006000e+00
khs.dNH,171.0,0.011696,1.078291e-01,0.0000,1.000000e+00
maxaaN,171.0,2.507591,2.345287e+00,0.0000,5.180800e+00
maxaaO,171.0,0.495871,1.606866e+00,0.0000,6.057800e+00
SpDiam_Dzv,171.0,363.822661,9.943902e+01,0.0000,6.128502e+02
SpDiam_Dzs,171.0,359.145207,1.262808e+02,0.0000,9.054116e+02
SpDiam_Dzp,171.0,396.589088,1.119137e+02,0.0000,7.076270e+02
SpDiam_Dze,171.0,300.005551,7.776758e+01,0.0000,4.809287e+02
SpDiam_Dzm,171.0,295.903427,7.781811e+01,0.0000,4.802879e+02
GATS6i,171.0,1.004774,1.240399e-01,0.5898,1.371400e+00
SpDiam_Dzi,171.0,291.988384,7.487908e+01,0.0000,4.565990e+02
Mi,171.0,7.489481,9.138761e-02,7.2942,7.811200e+00
Mv,171.0,0.695011,3.479525e-02,0.6192,8.101000e-01
Mp,171.0,0.725284,2.922986e-02,0.6472,8.226000e-01
GGI10,171.0,0.268537,1.051921e-01,0.0000,6.081000e-01
bpol,171.0,34.725023,8.143540e+00,10.2924,5.136580e+01
MW,171.0,510.649111,7.050779e+01,220.0749,5.991627e+02
GATS6v,171.0,0.995067,1.067225e-01,0.6973,1.354100e+00
MATS7s,171.0,-0.020613,1.456504e-01,-0.8463,3.430000e-01
MATS7p,171.0,-0.009951,8.964719e-02,-0.2401,5.610000e-01
C1SP1,171.0,0.064327,3.454954e-01,0.0000,2.000000e+00
MATS7v,171.0,-0.020216,9.385922e-02,-0.2570,4.715000e-01
MATS7i,171.0,0.001771,9.193512e-02,-0.2625,2.562000e-01
MATS7m,171.0,-0.035907,1.230679e-01,-0.5011,3.744000e-01
MATS7c,171.0,0.012537,1.331722e-01,-0.4893,4.674000e-01
GATS6s,171.0,1.095387,2.849360e-01,0.3444,1.717100e+00
MATS7e,171.0,-0.020196,1.696752e-01,-0.8149,4.147000e-01
maxtN,171.0,0.291101,1.684201e+00,0.0000,1.075450e+01
SpMin8_Bhe,171.0,1.069841,1.928656e-01,0.0505,1.384900e+00
SpMin8_Bhi,171.0,1.031567,1.883782e-01,0.0520,1.330600e+00
SpMin8_Bhm,171.0,1.250570,1.898478e-01,0.2354,1.542600e+00
SpMin8_Bhp,171.0,1.272891,1.965372e-01,0.1180,1.569200e+00
SpMin8_Bhs,171.0,1.095081,2.106371e-01,0.0259,1.457700e+00
SpMin8_Bhv,171.0,1.273694,1.897111e-01,0.1596,1.564300e+00
maxHCsatu,171.0,0.386651,4.408492e-01,0.0000,1.111500e+00
maxHCsats,171.0,0.432850,3.892990e-01,0.0000,1.111500e+00
ATSC3v,171.0,-223.866177,4.728481e+02,-2182.3284,1.280791e+03
ATSC3s,171.0,-2.264263,1.387972e+01,-50.5569,3.389560e+01
ATSC3p,171.0,-2.154444,2.567232e+00,-12.0812,4.644800e+00
minHdCH2,171.0,0.003076,4.022423e-02,0.0000,5.260000e-01
ATSC3e,171.0,-0.353745,7.425195e-01,-2.8927,1.557300e+00
ATSC3c,171.0,-0.107223,2.108481e-01,-1.1070,3.029000e-01
maxssNH,171.0,1.171271,1.473294e+00,0.0000,3.844200e+00
ATSC3m,171.0,-10.322351,3.844066e+02,-1149.2679,9.577934e+02
ATSC3i,171.0,-19.523330,2.123647e+01,-76.3531,5.862030e+01
minHCsatu,171.0,0.347576,4.004006e-01,0.0000,1.104700e+00
minHCsats,171.0,0.334647,3.074225e-01,0.0000,9.044000e-01
SpMax7_Bhe,171.0,3.220797,1.914412e-01,2.2471,3.464200e+00

In [38]:
# Categorical Feature Statistics
cat_stats

            value  count    pct
column rank
Toxic  1       No    115  67.25
       2      Yes     56  32.75

In [39]:
# Target Distribution
target_df

       count    pct
Toxic
No       115  67.25
Yes       56  32.75

## Task Curation

In [40]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=20, n_splits=3, test_size=None

In [41]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [42]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019cf608-902b-7180-a7d2-f5944d5c8f70
107c9cfbcf26d9a413d9653913711d855d7ed72ee1fa6dc8ae150ed7124dd89c