### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="california_house_prices_2020",
    dataset_year="2021",
    domain_str="business & marketing",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/california-house-prices/data?select=train.csv",
    download_description="""
We utilize the train.csv from the Kaggle competition. We use the following commands to download and organize the data:

kaggle competitions download -c california-house-prices -f train.csv && unzip train.csv.zip train.csv && rm train.csv.zip
mkdir -p local-data-warehouse/california_house_prices_2020 && mv train.csv local-data-warehouse/california_house_prices_2020
""",
    # References
    academic_reference_bibtex=r"""@misc{d2lcourse2021california_house_prices,
  author       = {d2lcourse},
  title        = {California House Prices},
  year         = {2021},
  howpublished = {\url{https://kaggle.com/competitions/california-house-prices}},
  note         = {Kaggle}
}
""",
    academic_reference_bibtex_key="d2lcourse2021california_house_prices",
    license="Custom Kaggle Competition Rules",
    data_tags=["Non-IID", "Temporal", "Spatial"],
    curation_comments="""
We follow some common preprocessing steps from Kaggle and enhance features as much as possible.

We found out that the data was web scraped from redfin.com and that the houses are ordered by the time they were sold such that a house with a higher ID was sold later. We confirmed this by looking at the history of various houses on redfin.com that we found in the dataset and checking their order in the ID with the time they were sold. Houses with a higher ID were sold later.

- We log scale the target variable.
- We do not have the exact dates but we know a higher ID means a later sale. We name the ID column accordingly to "time_index" and use it as a time feature.
- The descriptions did contain the last sold price with a standard phrase such as "This home last sold for $X in January 2020. The Zestimate for this house is $Y The Rent Zestimate for this home is $Z/mo.". In these cases $X is identical to the target variable. Given such a drastic data leakage, we remove all rows (5413) that contain this phrase in the description to ensure they are not different in other ways too.
- Note, sometime descriptions are missing and we intend that models/pipelines need to be able to handle this.
- When investigating the "Lot" column we found many cases where the lot size (given in sq ft) is incorrect compared to the official lot size on the internet. The parser seems to have had an issue because the website often incorrectly showed the sq ft but gave the unit as acres. We found cases that were wrong by checking the acres size of the houses and anything with more than 2000 acres was investigated and subsequently corrected.
- We parsed the bedrooms with a proxy following Kaggle and added an additional column containing only the semi-free text descriptions of the bedrooms.
- We fix the parser errors for two cases for total interior livable area that were clear outliers based on the real data on redfin.
- Garage and total space were in most cases the same values parsed from different fields. We keep Garage space and add an 'Extra Space' column that is the difference between total and garage space as an additional feature. This results in some cases with negative extra space that are most likely parser errors. We set them to nan. Note, we observed that that garage space number is in many cases a parsing error and does not reflect the real garage count.
- The data has a lot of spatial features that are already semi-resolved to distances. This could be further enhanced using the address information. We leave it to the pipeline to handle this, if at all.
- The dataset contains many text-like many categorical that are also high-cardinality, so perfect string data.
- We drop all entries from the State of Arizona (AZ) as they are only a small fraction (n=431 after our preprocessing). The dataset is specified to be for California house prices.
- We treat ZIP codes as strings. But we add a new categorical features that puts zip code in to approximate relevant buckets of regions.
- We fixed one entry that had a negative value for garage space, likely due to a typo. This error still exists on the website.
- After all the above preprocessing, there exist 63 houses that appear multiple times in the dataset (same address, zip code, year built). We only keep the newest entry to avoid group-related target leakage.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Sold Price",
    problem_type="regression",
    objective_metric_name="rmse",
    time_on="time_index",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(dataset_mold.path / "train.csv")
print("Loaded data shape:", df.shape)

df = df.rename(columns={
    "Id": "time_index",
})

as_date_cols = ["Listed On", "Last Sold On"]
as_string_cols = [
    "Summary", "Type", "Heating", "Cooling", "Parking", "Region",
    "Elementary School", "Middle School", "High School", "Flooring",
    "Heating features", "Cooling features", "Appliances included",
    "Laundry features", "Parking features", "City",
    "Address", "State",
]
as_cat_type = ["Type"]

# Remove rows with target leakage in description
leak_mask = ~df["Summary"].isna() & (df["Summary"].str.contains("last sold for"))
df = df[~leak_mask]

# Set wrongly parsed years to NaN
df.loc[df["Year built"].isin([0, 19, 9999, 1471, 2281]), "Year built"] = np.nan


# Fix wrong lot sizes
#   - found by: wrong_lot_size_mask = (df["Lot"]/43560) > 2000
for time_index, correct_size in [
    (1701, 6660), (5198, 5500), (11205, 5768), (16036, 4200),
    (17241, 7650), (19469, 60984), (23605, 7700), (23807, 35283.6),
    (30942, 4500), (31871, 6500), (34622, 6403), (39769, 2584), (43009, 7546),
    # still says acres
    (13280, 5804),(46033, 6216),
]:
    df.loc[df["time_index"] == time_index, "Lot"] = correct_size
assert ((df["Lot"]/43560) > 2000).sum() == 0, "There are still wrong lot sizes > 2000 acres"

# Ensure dtypes
c = "Year built" # special case
nan_mask = df[c].isna()
df.loc[nan_mask, c] = df.loc[~df[c].isna(), c].iloc[0]
df[c] = pd.to_datetime(df[c].astype(int).astype(str), errors='raise')
df.loc[nan_mask, c] = pd.NaT

for c in as_date_cols:
    nan_mask = df[c].isna()
    df.loc[nan_mask, c] = df.loc[~df[c].isna(), c].iloc[0]  # Temp fill to allow conversion
    df[c] = pd.to_datetime(df[c], errors='raise')
    df.loc[nan_mask, c] = pd.NaT


c = "Zip" # ensure zip string is without .0 at the end.
nan_mask = df[c].isna()
df[c] = df[c].astype("string")
df.loc[nan_mask, c] = np.nan
df.loc[~nan_mask, c] = df.loc[~nan_mask, c].astype(int).astype("string")

for c in as_string_cols:
    nan_mask = df[c].isna()
    df.loc[nan_mask, c] = np.nan
    df[c] = df[c].astype("string")

# Extra FE for Bedrooms
bedroom_description_mask = pd.to_numeric(df["Bedrooms"], errors="coerce").isna()
df["Bedrooms_description"] = df["Bedrooms"].astype("string")
df.loc[(~bedroom_description_mask) | (df["Bedrooms"].isna()), "Bedrooms_description"] = np.nan
df["Bedrooms_description"] = df["Bedrooms_description"].astype("string")

# Compute a proxy for bedrooms from the description
# https://www.kaggle.com/code/wuwawa/automl-using-h2o
def bedroom_proxy(x):
    if not pd.isna(x) and not x.isdigit():
        temp = x.split(',')
        n = len(x.split(','))
        if 'Walk-in Closet' in temp:
            n -= 1
        if "Reverse Floor Plan" in temp:
            n -= 1
        if n <= 0:
            n = np.nan
        return n
    else:
        return x
df.loc[bedroom_description_mask, "Bedrooms"] = df.loc[bedroom_description_mask, "Bedrooms"].apply(bedroom_proxy)
df["Bedrooms"] = pd.to_numeric(df["Bedrooms"], errors="coerce")

# Fix wrong sqft parsing outliers
for time_index, correct_size in [
    (43911, 702),
    (26533, 700),
]:
    df.loc[df["time_index"] == time_index, "Total interior livable area"] = correct_size

# Add extra space and remove total space duplicates
df.loc[df["time_index"] == 41450, "Garage spaces"] = 5 # fix data error
df["Extra Space"] = df["Total spaces"] - df["Garage spaces"]
df.loc[df["Extra Space"] < 0, "Extra Space"] = np.nan
df = df.drop(columns=["Total spaces"])

# Drop entries from AZ state
df = df[df["State"] != "AZ"]
df = df.drop(columns=["State"])

# Zip code buckets for CA
def zip_buckets(x):
    if pd.isna(x):
        return np.nan

    x = int(x)

    if x < 91911:
        return "Southern California / LA Area"

    if x < 93000:
        return "San Diego Area"
    if x < 94000:
        return "Central California"
    if x < 95200:
        return "San Francisco Bay Area"
    if x < 97000:
        return "Northern California"

    raise ValueError(f"Unexpected zip code: {x}")

df["Zip Region"] = df["Zip"].apply(zip_buckets).astype("category")

# Only keep the newest entry for houses that appear multiple times
n_data = len(df)
idx = df.groupby(["Address", "Zip", "Year built"], dropna=False)["time_index"].idxmax()
df = df.loc[idx].reset_index(drop=True)
assert n_data - len(df) == 67 # We have 63 houses with multiple entries (either 2 or 3) for a total of 130 entire. We keep one entry per house, thus 130 - 63 = 67

# Log scale target as it is exp distributed
df[task_mold.target_column_name] = np.log1p(df[task_mold.target_column_name])

# Rest time_index (to avoid gaps from dropping rows)
df = df.drop(columns=["time_index"]).reset_index().rename(columns={"index": "time_index"})

Loaded data shape: (47439, 41)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 41,528
Columns: 42
Use sampling: False (sample size: 41,528)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['time_index', 'Address', 'Summary', 'Tax assessed value', 'Annual tax amount', 'Lot', 'Last Sold On', 'Parking', 'Parking features', 'Appliances included']
Rows remaining as candidates after top-10 filter: 0 (of 41,528)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,time_index,Address,Sold Price,Summary,Type,Year built,Heating,Cooling,Parking,Lot,Bedrooms,Bathrooms,Full bathrooms,Total interior livable area,Garage spaces,Region,Elementary School,Elementary School Score,Elementary School Distance,Middle School,Middle School Score,Middle School Distance,High School,High School Score,High School Distance,Flooring,Heating features,Cooling features,Appliances included,Laundry features,Parking features,Tax assessed value,Annual tax amount,Listed On,Listed Price,Last Sold On,Last Sold Price,City,Zip,Bedrooms_description,Extra Space,Zip Region
0,0,0 113th St,11.982935,"LAND LAND LAND FOR SALE! CALLING ALL INVESTORS WHO KNOW THIS AREA OF LOS ANGELES. LAND IS READY FOR A SFR TO BE CONSTRUCTED. BUILD AND FLIP! HOME NEXT DOOR IS IDENTICAL AND HAS 3 BEDS 2 BATHS. SEE TO APPRECIATE! LAND IS CEMENTED AND HAS ALLEY ACCESS. MAKE AN OFFER, THIS ONE WILL NOT LAST! NOTE: LATEST 1/30/2020* FOR FURTHER INFO ON HOW YOU CAN OBTAIN PERMITS FOR THIS LAND ANY LOS ANGELES (CITY) OFFICES HAVE ALL THE REQUIREMENTS FOR YOU TO USE THIS LAND TO BUILD. CITY HAS AN ADDRESS ADDRESS 1601 E 113TH ST LOS ANGELES. YOU CAN USE 45% OF THE LAND TO BUILD A HOME OF YOUR CHOICE. ZONE IS R1. CALL ME FOR FURTHER QUESTIONS...",VacantLand,NaT,<NA>,<NA>,0 spaces,NaN,NaN,NaN,NaN,NaN,NaN,Los Angeles,<NA>,NaN,NaN,Samuel Gompers Middle School,2.0,0.9,George Washington Preparatory High School,2.0,1.3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,2020-01-25,169999.0,NaT,NaN,Los Angeles,90044,<NA>,NaN,Southern California / LA Area
1,1,0 40 Ac Wilkins Rd,11.982935,"- Prime flat/level residential/agricultural lot - Easy access highway 111 - Canal access with water right - Paved road - Utilities are on or close by to the parcel - Excellent opportunity to build a farm - 40 acres of flat/level land - 1,742,400 sqft Interested buyers can also purchase together with parcel 003-120-007-000 (164 ac) and parcel 003-110-025-000 (17 ac) for a total of 221 acres.",VacantLand,NaT,Gas,<NA>,0 spaces,NaN,NaN,NaN,NaN,NaN,NaN,Niland,Grace Smith Elementary School,6.0,4.9,Bill E. Young Jr. Middle School,4.0,2.3,Calipatria High School,6.0,2.3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,2019-02-11,200000.0,NaT,NaN,Calipatria,92233,<NA>,NaN,San Diego Area
2,2,0 Acacia St,11.652696,<NA>,VacantLand,NaT,<NA>,<NA>,0 spaces,NaN,NaN,NaN,NaN,NaN,NaN,Delhi,Schendel Elementary School,5.0,0.2,Delhi Middle,4.0,0.8,Delhi High School,5.0,0.9,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,2020-06-17,120000.0,NaT,NaN,Delhi,95315,<NA>,NaN,Northern California
3,3,0 Apn 255 #280-24-00,11.571204,"Are you looking for a get away, then this might be place for you. 20 acres of land in the mountains of Lebec. Ready for you to build your new house or put a trailer on it. Property has water to it already and power is not to far from the property. Take a look at the views.",VacantLand,NaT,<NA>,<NA>,0 spaces,NaN,NaN,NaN,NaN,NaN,NaN,Lebec,Gorman Elementary School,3.0,5.2,<NA>,NaN,NaN,Quartz Hill High School,6.0,35.1,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,2020-06-27,174900.0,NaT,NaN,Lebec,93243,<NA>,NaN,Central California
4,4,0 Avenue 71,13.652993,"Warm farmground. 15 acres medjools, 5 acres tall deglets, 6 acres young offshoot deglets. 50 acres open farmground. The following APNs are also apart of this 2 parcel property: 729-120-004 (39.45 ac)",VacantLand,NaT,<NA>,<NA>,0 spaces,NaN,NaN,NaN,NaN,NaN,NaN,Mecca,Saul Martinez Elementary School,3.0,3.1,Toro Canyon Middle School,2.0,8.3,Desert Mirage High School,3.0,8.3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,2017-11-10,2220000.0,NaT,NaN,Mecca,92254,<NA>,NaN,San Diego Area

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Zip Region,category,0.0,0.00,5.0,"San Francisco Bay Area, Southern California / LA Area, Northern California, Central California, San Diego Area"
1,Last Sold On,datetime64[ns],15536.0,37.41,5903.0,"2017-06-30 00:00:00, 2016-09-30 00:00:00, 2017-05-26 00:00:00, 2015-02-27 00:00:00, 2019-08-30 00:00:00, 2016-07-29 00:00:00, 2017-12-29 00:00:00, 2013-08-30 00:00:00, 2018-05-31 00:00:00, 2019-04-30 00:00:00"
2,Year built,datetime64[ns],1076.0,2.59,157.0,"1973-01-01 00:00:00, 2020-01-01 00:00:00, 1950-01-01 00:00:00, 1947-01-01 00:00:00, 1924-01-01 00:00:00, 1972-01-01 00:00:00, 1948-01-01 00:00:00, 1955-01-01 00:00:00, 1923-01-01 00:00:00, 1979-01-01 00:00:00"
3,Listed On,datetime64[ns],0.0,0.00,2266.0,"2020-09-18 00:00:00, 2020-10-16 00:00:00, 2020-10-02 00:00:00, 2020-10-09 00:00:00, 2020-08-14 00:00:00, 2020-08-07 00:00:00, 2020-09-25 00:00:00, 2020-10-23 00:00:00, 2020-09-11 00:00:00, 2020-10-01 00:00:00"
4,Last Sold Price,float64,15536.0,37.41,3723.0,"650000.0, 850000.0, 500000.0, 550000.0, 1100000.0, 1200000.0, 750000.0, 350000.0, 700000.0, 300000.0"
5,Middle School Score,float64,14458.0,34.82,9.0,"6.0, 3.0, 5.0, 7.0, 4.0, 8.0, 2.0, 9.0, 1.0"
6,Middle School Distance,float64,14457.0,34.81,212.0,"0.6, 0.8, 0.7, 0.5, 0.9, 0.4, 1.0, 0.3, 1.1, 1.2"
7,Lot,float64,13004.0,31.31,7903.0,"5000.0, 6098.0, 6534.0, 2500.0, 2495.0, 2996.0, 11325.6, 7405.0, 5998.0, 10890.0"
8,Full bathrooms,float64,6772.0,16.31,16.0,"2.0, 1.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
9,High School Score,float64,4778.0,11.51,10.0,"7.0, 6.0, 8.0, 5.0, 4.0, 3.0, 9.0, 2.0, 10.0, 1.0"
10,High School Distance,float64,4591.0,11.06,330.0,"0.8, 0.7, 0.9, 0.6, 1.0, 0.5, 1.2, 1.1, 1.3, 0.4"
11,Elementary School Score,float64,4137.0,9.96,10.0,"6.0, 7.0, 4.0, 5.0, 8.0, 9.0, 3.0, 2.0, 1.0, 10.0"
12,Elementary School Distance,float64,4009.0,9.65,239.0,"0.3, 0.4, 0.2, 0.5, 0.6, 0.7, 0.1, 0.8, 0.9, 1.0"
13,Annual tax amount,float64,3672.0,8.84,18038.0,"1395.0, 2307.0, 1204.0, 2506.0, 1976.0, 2460.0, 5340.0, 1266.0, 4235.0, 1516.0"
14,Bedrooms,float64,3564.0,8.58,28.0,"3.0, 2.0, 4.0, 1.0, 5.0, 6.0, 0.0, 7.0, 8.0, 9.0"
15,Tax assessed value,float64,3250.0,7.83,30689.0,"1224000.0, 867000.0, 918000.0, 1530000.0, 1200000.0, 765000.0, 1100000.0, 1326000.0, 663000.0, 1196460.0"
16,Bathrooms,float64,2960.0,7.13,22.0,"2.0, 3.0, 1.0, 4.0, 5.0, 6.0, 0.0, 7.0, 8.0, 9.0"
17,Total interior livable area,float64,2307.0,5.56,4457.0,"1200.0, 1440.0, 1300.0, 1400.0, 1000.0, 1800.0, 1100.0, 1500.0, 1040.0, 2000.0"
18,Extra Space,float64,750.0,1.81,20.0,"0.0, 2.0, 4.0, 1.0, 3.0, 6.0, 5.0, 10.0, 8.0, 12.0"
19,Garage spaces,float64,711.0,1.71,42.0,"2.0, 0.0, 1.0, 3.0, 4.0, 5.0, 6.0, 8.0, 10.0, 7.0"
20,Sold Price,float64,0.0,0.00,5311.0,"13.9978, 13.9108, 14.0779, 14.0387, 13.653, 13.9553, 13.8643, 14.1156, 14.221, 14.152"
21,Listed Price,float64,0.0,0.00,4338.0,"899000.0, 799000.0, 699000.0, 1495000.0, 599000.0, 995000.0, 1299000.0, 999000.0, 1199000.0, 849000.0"
22,time_index,int64,0.0,0.00,41528.0,"41527, 0, 1, 2, 3, 4, 5, 6, 7, 8"
23,Bedrooms_description,string,35351.0,85.13,222.0,"Walk-in Closet, Master Suite / Retreat, Walk-in Closet, Master Suite / Retreat, Ground Floor Bedroom, Master Bedroom on Ground Floor, Ground Floor Bedroom, Master Suite / Retreat, Walk-in Closet, Ground Floor Bedroom, Walk-in Closet, More than One Bedroom on Ground Floor, Master Bedroom on Ground Floor, More than One Bedroom on Ground Floor, Ground Floor Bedroom, Master Bedroom on Ground Floor, More than One Bedroom on Ground Floor"
24,Cooling features,string,19978.0,48.11,252.0,"Central, Central Air, Other, Wall/Window Unit(s), Wall, Central, Solar, See Remarks, Evaporative, Ceiling Fan(s), Central, Other"
25,Cooling,string,18684.0,44.99,440.0,"Central Air, Central AC, Central, Ceiling Fan, Other, Ceiling Fan, Central AC, Wall/Window Unit(s), Multi-Zone, Central AC, Window / Wall Unit, See Remarks"
26,Middle School,string,14457.0,34.81,479.0,"Hubert Howe Bancroft Middle School, Mission Hill Middle School, Lick (James) Middle School, Thomas Starr King Middle School, John Muir Middle School, Audubon Middle School, Willow Glen Middle School, John Burroughs Middle School, Everett Middle School, Paul Revere Middle School"
27,Laundry features,string,12882.0,31.02,1758.0,"Inside, In Garage, Laundry Closet, Laundry Room, Washer / Dryer, Washer / Dryer, Inside, Inside Room, In Unit, Community, In Garage, Washer / Dryer"
28,Appliances included,string,11459.0,27.59,4566.0,"Dishwasher, Dryer, Garbage disposal, Microwave, Range / Oven, Refrigerator, Washer, Dishwasher, Dryer, Freezer, Garbage disposal, Microwave, Range / Oven, Refrigerator, Washer, Dryer, Washer, Dishwasher, Dishwasher, Garbage disposal, Microwave, Range / Oven, Refrigerator, Dishwasher, Dryer, Garbage disposal, Range / Oven, Refrigerator, Washer, Dishwasher, Disposal, Refrigerator, Washer, Dryer, Dishwasher, Dryer, Microwave, Range / Oven, Refrigerator, Washer, Dishwasher, Refrigerator, Dishwasher, Disposal"
29,Flooring,string,10310.0,24.83,1184.0,"Wood, Hardwood, Tile, Wood, Laminate, Tile, Hardwood, Wood, Tile, Tile, Hardwood, Carpet, Carpet, Wood, Carpet, Tile, Laminate"
30,Heating features,string,7089.0,17.07,1038.0,"Central, Forced air, Gas, Forced air, Other, Wall Furnace, Forced Air, Central, Gas, Radiant, Forced air, Electric, Other, Gas"
31,Heating,string,6367.0,15.33,1628.0,"Central, Central Forced Air, Central Forced Air - Gas, Forced Air, Wall Furnace, Other, Forced air, Gas, Forced air, Central, Gas, Gas"
32,High School,string,4591.0,11.06,613.0,"Fairfax Senior High School, University Senior High School Charter, Harbor High School, Independence High School, John Marshall Senior High School, Belmont Senior High School, Willow Glen High School, Venice Senior High School, Benjamin Franklin Senior High School, Santa Clara High School"
33,Parking features,string,4042.0,9.73,4815.0,"Garage, Garage - Attached, Covered, Garage, Garage, Garage - Attached, Garage - Attached, Garage - Attached, Covered, Carport, Driveway, Garage - Two Door, Garage, Garage - Detached, Covered, Covered"
34,Elementary School,string,4009.0,9.65,1647.0,"Laurel Elementary School, Sherman Elementary School, Daniel Webster Elementary School, Kenter Canyon Elementary School, Gardner Street Elementary School, Warner Avenue Elementary School, Cabrillo Elementary School, Rooftop Elementary School, McKinley Elementary School, Westwood Charter Elementary School"
35,Parking,string,1357.0,3.27,4939.0,"Garage, Garage - Attached, Covered, 0 spaces, Garage, Garage, Garage - Attached, Garage - Attached, Garage - Attached, Covered, Carport, Driveway, Garage - Two Door, Garage, Garage - Detached, Covered"
36,Summary,string,354.0,0.85,40908.0,"Neighboring The Ace Hotel, 939 S. Broadway is the epitome of effort lessliving in Downtown Los Angeles. While the former Western Costume Building maintains its iconic exterior architecture, each residence has been renovated to feature the finest modern details. Stainless steel appliances and Quartz countertops add contemporary sophistication to the loft-style, industrial chic interiors. The original, towering windows, capture abundant natural light and reveal dynamic views of Downtown Los Angeles. One- and two-bedrooms ranging from 505 to 1,227 square feet, residences feature open-concept living and boast high ceilings. Providing generous gathering spaces, the interiors showcase the perfect balance of form and function. Amenities include rooftop pool/spa, cabanas, gym, in-unit stacked laundry, and high ceilings., -, ., 40 units remaining! Many floor plans available. BRAND NEW CONSTRUCTION! LARGE living rooms and LARGE bedrooms with great views of DTLA, Koreatown & Hollywood. Quartz Countertops, Thor Appliances, Hardwood Flooring & very spacious laundry rooms. Two assigned SIDE BY SIDE parking spaces in secured garage, bicycle storage & Electric vehicle charging stations. On-site fitness room, Pool, Lounge/Club Room, 2 courtyards and 20 guest parking. Conveniently located to Metro Station on Vermont and Wilshire. Plenty of restaurants and entertainment within walking distance. Minutes from DTLA. Pictures may be photos of a different unit. 3D https://my.matterport.com/show/?m=T8XeseJaweX/ Sales Office OPEN DAILY from 11-5pm, BRAND NEW PROJECT! This is THE best adaptive re-use project in DTLA to date. 151 Live/Work units in the first historic condo building in South Park. Great variety of very attractive floor plans, with 11-14 ft ceilings, all with spectacular city views. LOWEST HOA'S IN DTLA. 1 COVERED PARKING SPACE INCLUDED in building across the street. Amazing amenities incl. rooftop sundeck w/ pool, spa, lounge chairs and cabanas, gym, and theater and media room on the basement floor, and beautiful historic lobby w/ security guard. Former home of the Western Costume Co est. 1924. Adjacent to the United Artists Theater (and now the Ace Hotel) 939 South Broadway was the largest costume rental house in the world, responsible for 99% of the costumes used in all Western movies in the early days of Hollywood. Bldg was the vision of big screen stars Mary Pickford, Charlie Chaplin and Douglas Fairbanks of the United Artists studio. AGENTS SEE PRIVATE AND SHOWING REMARKS!, Sold before processing., Murieta Gardens is an all electric community offering 4 single-story new home designs in Rancho Murieta, CA. Live a relaxed lifestyle in a great school district with easy commute routes to Elk Grove, Downtown Sacramento and Folsom. Offered By: K. Hovnanian Homes Northern California, Inc., For Comp Purposes Only..., Residence 1 is a roomy two bedroom, 2.5 bath townhome with a spacious tandem-style garage. You will have plenty of storage for outdoor recreation equipment with your first floor tandem-style garage. The second floor is contemporary with it's open layout. The kitchen features a walk-in-pantry closet and a bright window over the over-sized kitchen sink. On the the third floor you will find two bedrooms with en suite bathrooms. The master bedroom features dual sinks and a walk-in shower., Explore a new angle on life at MIRA, luxury condominium homes developed by the team at Tishman Speyer and designed by award-winning architecture Studio Gang. Located at the corner of Spear and Folsom Streets in San Francisco, CA, MIRA features iconic architecture, innovative layouts, striking views and a bold attitude. Fresh and forward-thinking, MIRA invites you to shift your perspective on living in San Francisco. All images are representative of the development."
37,Address,string,0.0,0.00,41510.0,"421 Grove St, 1529 6th Ave, 2476 Martin Luther King Jr Way, 540 Delancey St UNIT 204, 627 16th Ave, 500 Cambridge St, 242 Robles Way, 115 Navarra Dr, 555 Fulton St #215, 815 Encino Dr"
38,Type,string,0.0,0.00,144.0,"SingleFamily, Condo, Townhouse, Unknown, MultiFamily, MobileManufactured, VacantLand, Single Family, Apartment, Cooperative"
39,Region,string,0.0,0.00,908.0,"Los Angeles, San Jose, San Francisco, San Mateo, Santa Cruz, Sunnyvale, Santa Clara, Morgan Hill, Los Gatos, Compton"
40,City,string,0.0,0.00,861.0,"Los Angeles, San Jose, San Francisco, Santa Clara, San Mateo, Santa Cruz, Sunnyvale, Los Gatos, Morgan Hill, Redwood City"
41,Zip,string,0.0,0.00,1143.0,"95123, 95037, 95125, 90046, 95020, 94110, 95124, 90042, 95035, 90066"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
time_index,41528.0,2.076350e+04,1.198825e+04,0.000000,4.152700e+04
Sold Price,41528.0,1.377772e+01,7.755062e-01,11.517923,1.831532e+01
Lot,28524.0,5.405607e+04,7.977161e+05,0.000000,6.969600e+07
Bedrooms,37964.0,2.830497e+00,1.305326e+00,0.000000,4.200000e+01
Bathrooms,38568.0,2.356876e+00,1.196705e+00,0.000000,2.400000e+01
Full bathrooms,34756.0,2.087985e+00,9.803851e-01,1.000000,1.700000e+01
Total interior livable area,39221.0,1.830280e+03,1.187843e+03,1.000000,3.597000e+04
Garage spaces,40817.0,1.455643e+00,8.649698e+00,0.000000,1.000000e+03
Elementary School Score,37391.0,5.734508e+00,2.120630e+00,1.000000,1.000000e+01
Elementary School Distance,37519.0,1.071526e+00,2.235817e+00,0.000000,5.720000e+01
Middle School Score,27070.0,5.289656e+00,2.014079e+00,1.000000,9.000000e+00
Middle School Distance,27071.0,1.614972e+00,2.367637e+00,0.000000,5.720000e+01
High School Score,36750.0,6.108789e+00,2.005713e+00,1.000000,1.000000e+01
High School Distance,36937.0,2.273579e+00,3.454688e+00,0.000000,7.390000e+01
Tax assessed value,38278.0,8.093157e+05,1.173496e+06,0.000000,4.590000e+07
Annual tax amount,37856.0,1.021850e+04,1.407790e+04,0.000000,5.524850e+05
Listed Price,41528.0,1.351165e+06,2.751264e+06,0.000000,4.025320e+08
Last Sold Price,25992.0,8.291973e+05,1.195404e+06,0.000000,9.000000e+07
Extra Space,40778.0,8.676247e-02,8.934867e-01,0.000000,1.000000e+02

In [7]:
# Categorical Feature Statistics
cat_stats

                                                                                         value  \
column               rank
Address              1                                                            421 Grove St
                     2                                                            1529 6th Ave
                     3                                          2476 Martin Luther King Jr Way
                     4                                                540 Delancey St UNIT 204
                     5                                                            627 16th Ave
Appliances included  1                                                                    <NA>
                     2     Dishwasher, Dryer, Garbage disposal, Microwave, Range / Oven, Re...
                     3     Dishwasher, Dryer, Freezer, Garbage disposal, Microwave, Range /...
                     4                                                           Dryer, Washer
                     5                                                              Dishwasher
Bedrooms_description 1                                                                    <NA>
                     2                                                          Walk-in Closet
                     3                                  Master Suite / Retreat, Walk-in Closet
                     4                                                  Master Suite / Retreat
                     5                                                    Ground Floor Bedroom
City                 1                                                             Los Angeles
                     2                                                                San Jose
                     3                                                           San Francisco
                     4                                                             Santa Clara
                     5                                                               San Mateo
Cooling              1                                                                    <NA>
                     2                                                             Central Air
                     3                                                              Central AC
                     4                                                                 Central
                     5                                                             Ceiling Fan
Cooling features     1                                                                    <NA>
                     2                                                                 Central
                     3                                                             Central Air
                     4                                                                   Other
                     5                                                     Wall/Window Unit(s)
Elementary School    1                                                                    <NA>
                     2                                                Laurel Elementary School
                     3                                               Sherman Elementary School
                     4                                        Daniel Webster Elementary School
                     5                                         Kenter Canyon Elementary School
Flooring             1                                                                    <NA>
                     2                                                                    Wood
                     3                                                                Hardwood
                     4                                                              Tile, Wood
                     5                                                                Laminate
Heating              1                                                                 Central
                     2                                                                    <NA>
                     3                                                      Central Forced Air
                     4                                                Central Forced Air - Gas
                     5                                                              Forced Air
Heating features     1                                                                 Central
                     2                                                                    <NA>
                     3                                                         Forced air, Gas
                     4                                                              Forced air
                     5                                                                   Other
High School          1                                                                    <NA>
                     2                                              Fairfax Senior High School
                     3                                   University Senior High School Charter
                     4                                                      Harbor High School
                     5                                                Independence High School
Last Sold On         1                                                                    <NA>
                     2                                                     2017-06-30 00:00:00
                     3                                                     2016-09-30 00:00:00
                     4                                                     2017-05-26 00:00:00
                     5                                                     2015-02-27 00:00:00
Laundry features     1                                                                    <NA>
                     2                                                                  Inside
                     3                                                               In Garage
                     4                                                          Laundry Closet
                     5                                                            Laundry Room
Listed On            1                                                     2020-09-18 00:00:00
                     2                                                     2020-10-16 00:00:00
                     3                                                     2020-10-02 00:00:00
                     4                                                     2020-10-09 00:00:00
                     5                                                     2020-08-14 00:00:00
Middle School        1                                                                    <NA>
                     2                                      Hubert Howe Bancroft Middle School
                     3                                              Mission Hill Middle School
                     4                                              Lick (James) Middle School
                     5                                         Thomas Starr King Middle School
Parking              1                                      Garage, Garage - Attached, Covered
                     2                                                                0 spaces
                     3                                                                  Garage
                     4                                               Garage, Garage - Attached
                     5                                                       Garage - Attached
Parking features     1                                      Garage, Garage - Attached, Covered
                     2                                                                    <NA>
                     3                                                                  Garage
                     4                                               Garage, Garage - Attached
                     5                                                       Garage - Attached
Region               1                                                             Los Angeles
                     2                                                                San Jose
                     3                                                           San Francisco
                     4                                                               San Mateo
                     5                                                              Santa Cruz
Summary              1                                                                    <NA>
                     2     Neighboring The Ace Hotel, 939 S. Broadway is the epitome of eff...
                     3                                                                       -
                     4                                                                       .
                     5     40 units remaining! Many floor plans available. BRAND NEW CONSTR...
Type                 1                                                            SingleFamily
                     2                                                                   Condo
                     3                                                               Townhouse
                     4                                                                 Unknown
                     5                                                             MultiFamily
Year built           1                                                                    <NA>
                     2                                                     1973-01-01 00:00:00
                     3                                                     2020-01-01 00:00:00
                     4                                                     1950-01-01 00:00:00
                     5                                                     1947-01-01 00:00:00
Zip                  1                                                                   95123
                     2                                                                   95037
                     3                                                                   95125
                     4                                                                   90046
                     5                                                                   95020
Zip Region           1                                                  San Francisco Bay Area
                     2                                           Southern California / LA Area
                     3                                                     Northern California
                     4                                                      Central California
                     5                                                          San Diego Area

                           count    pct
column               rank
Address              1         2    0.0
                     2         2    0.0
                     3         2    0.0
                     4         2    0.0
                     5         2    0.0
Appliances included  1     11459  27.59
                     2      1673   4.03
                     3      1174   2.83
                     4      1091   2.63
                     5       793   1.91
Bedrooms_description 1     35351  85.13
                     2       935   2.25
                     3       718   1.73
                     4       690   1.66
                     5       494   1.19
City                 1      9915  23.88
                     2      5609  13.51
                     3      4848  11.67
                     4       884   2.13
                     5       861   2.07
Cooling              1     18684  44.99
                     2      7983  19.22
                     3      5131  12.36
                     4      2150   5.18
                     5       974   2.35
Cooling features     1     19978  48.11
                     2      9499  22.87
                     3      7313  17.61
                     4       884   2.13
                     5       663    1.6
Elementary School    1      4009   9.65
                     2       316   0.76
                     3       306   0.74
                     4       303   0.73
                     5       296   0.71
Flooring             1     10310  24.83
                     2      3939   9.49
                     3      2082   5.01
                     4      1661    4.0
                     5      1577    3.8
Heating              1      8853  21.32
                     2      6367  15.33
                     3      4593  11.06
                     4      2957   7.12
                     5      2299   5.54
Heating features     1      8025  19.32
                     2      7089  17.07
                     3      6998  16.85
                     4      5323  12.82
                     5      1414    3.4
High School          1      4591  11.06
                     2      1424   3.43
                     3      1189   2.86
                     4       770   1.85
                     5       693   1.67
Last Sold On         1     15536  37.41
                     2        31   0.07
                     3        30   0.07
                     4        28   0.07
                     5        28   0.07
Laundry features     1     12882  31.02
                     2      3514   8.46
                     3      2953   7.11
                     4      1662    4.0
                     5      1467   3.53
Listed On            1       259   0.62
                     2       254   0.61
                     3       245   0.59
                     4       228   0.55
                     5       228   0.55
Middle School        1     14457  34.81
                     2       931   2.24
                     3       643   1.55
                     4       621    1.5
                     5       573   1.38
Parking              1      8288  19.96
                     2      2531   6.09
                     3      2087   5.03
                     4      1973   4.75
                     5      1593   3.84
Parking features     1      8339  20.08
                     2      4042   9.73
                     3      2062   4.97
                     4      1975   4.76
                     5      1625   3.91
Region               1     10004  24.09
                     2      5827  14.03
                     3      4847  11.67
                     4       700   1.69
                     5       684   1.65
Summary              1       354   0.85
                     2        18   0.04
                     3        16   0.04
                     4        15   0.04
                     5         8   0.02
Type                 1     26906  64.79
                     2      7566  18.22
                     3      2223   5.35
                     4      1587   3.82
                     5      1085   2.61
Year built           1      1076   2.59
                     2       700   1.69
                     3       648   1.56
                     4       645   1.55
                     5       605   1.46
Zip                  1       509   1.23
                     2       502   1.21
                     3       490   1.18
                     4       462   1.11
                     5       446   1.07
Zip Region           1     22378  53.89
                     2     13052  31.43
                     3      3380   8.14
                     4      1616   3.89
                     5      1102   2.65

In [8]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,0.026,-0.205,0.601,0.003,log,574097.8,6.882298e+09,exponential

## Task Curation

In [9]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from sklearn.model_selection import TimeSeriesSplit

spliter = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None)
splits = {0: {}, 1: {}, 2: {}}
for i, (train_idx, test_idx) in enumerate(spliter.split(df)):
    print(len(train_idx), len(test_idx))
    splits[i][0] = (train_idx, test_idx)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="We create a sklearn TimeSeriesSplit with 3 splits. We treat each split as a separate repeat with one fold. Each fold has 25% of the original data as test set. We simulate as if we deploy a model at a time point x, for the next time period (e.g. for a whole next year like in the original competition task). As we do not know the time periods from the time_index, we split based on number of samples.",
    splits=splits,
    time_horizon=10382,
    time_horizon_unit="steps",
)

10382 10382
20764 10382
31146 10382

## Export

In [10]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019d3064-3158-7e93-b010-51a7b6c72ba1
ad0d1b46cc651f864ac32cdb0cedd31f82596883e50eb11aef7dac83bc55f39c