### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="lending_club",
    dataset_year="2018",
    domain_str="finance",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://zenodo.org/records/11295916",
    download_description="""
It seems the official download portal from https://www.lendingclub.com is gone. So we can only utilize artifacts from the past, which seem to go up to 2018.
Old script and source: https://github.com/nateGeorge/preprocess_lending_club_data

From all the artifacts we found online, this seems to be the newest: https://www.kaggle.com/datasets/wordsforthewise/lending-club/data
And the following paper (https://arxiv.org/abs/2401.16458) curated this dataset https://zenodo.org/records/11295916 for tabular-text learning.

Other artifacts:
- https://www.kaggle.com/datasets/adarshsng/lending-club-loan-data-csv
- https://www.kaggle.com/datasets/imsparsh/lending-club-loan-dataset-2007-2011

wget https://zenodo.org/records/11295916/files/LC_loans_granting_model_dataset.csv?download=1
mkdir -p local-data-warehouse/lending_club && mv LC_loans_granting_model_dataset.csv?download=1 local-data-warehouse/lending_club
kaggle datasets download wordsforthewise/lending-club -f accepted_2007_to_2018Q4.csv.gz && mv accepted_2007_to_2018Q4.csv.gz local-data-warehouse/lending_club/
""",
    # References
    academic_reference_bibtex=r"""@article{sanz2025credit,
  title={Credit Risk Meets Large Language Models: Building a Risk Indicator from Loan Descriptions in P2P Lending},
  author={Sanz-Guerrero, Mario and Arroyo, Javier},
  journal={Inteligencia Artificial},
  volume={28},
  number={75},
  pages={220--247},
  year={2025}
}
""",
    academic_reference_bibtex_key="sanz2025credit",
    licence="CC0: Public Domain", # On Kaggle, likely not true TOS from the website.
    data_tags=["Non-IID", "Temporal", "Spatial"],
    curation_comments="""
We start withe data from Sanz-Guerrero et al. (2025). This data is already well preprocessed and curated for the task and used for tabular-text learning. However, we noticed a lot variables from the original data are missing that can be added to the task without invalidating the task or introducing data leakage. Thus, we also merge new features from the original data into the version from Sanz-Guerrero et al. (2025).

- This is a datasets where the description is very often empty or a standard phrase. So the model needs to be able to handle cases with a lot of missing data in the text modality, and also cases where the text is rarely informative. This is a common case in real-world tabular-text datasets, and it is important to have it represented in our benchmark.
- We reverse the ordinal encoding of the target.
- We reverse the name change of "revenue" back to "annual_inc".
- We also create a sec_app_fico_n like the fico_n from anz-Guerrero et al. (2025).
- We drop rows where "application_type" is missing as these rows have consistent missing values across features and likely represent some data loading artifact.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Default",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="Default",
    time_on="issue_d",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

original_df = pd.read_csv(dataset_mold.path /  "accepted_2007_to_2018Q4.csv.gz")
df = pd.read_csv(dataset_mold.path / "LC_loans_granting_model_dataset.csv?download=1")
print("Loaded data shape:", df.shape)
print("Original data shape:", original_df.shape)

# 0 for fully paid loans and a 1 for defaulted loans.
df["Default"] = df["Default"].map({0: "Fully Paid", 1: "Defaulted"})

df = df.rename(columns={"revenue": "annual_inc"})

# Transform     "sec_app_fico_range_low"    "sec_app_fico_range_high", to sec_app_fico_n
original_df["sec_app_fico_n"] = (original_df["sec_app_fico_range_low"] + original_df["sec_app_fico_range_high"]) / 2

new_features_from_original = original_df[[
    "id",
    # known when the loan is granted, so it can be used as a feature without data leakage.
    #   This, however, would create a different task, in that we want to train a model that the company uses after their own risk assessment but before granting the loan.
    #   Given that these values and grades are often determined by an internal model of the company, they might also introduce an unknown bias.
    #   We stick to treating the task as a pre-assessment modelling. An alternative version could also function as a "stacking" model that takes the output of the company's internal model as an input.
    #   The variables for this task are:
    # "term",
    # "int_rate",
    # "installment",
    # "grade",
    # "sub_grade",
    # "verification_status",
    # Known at the start / from data source even without the company assessing the risk, so it can be used no matter the use case.
    "emp_title",
    "disbursement_method",
    "acc_now_delinq",
    "acc_open_past_24mths",
    "all_util",
    "sec_app_fico_n",
    # annual_inc	annual_inc_joint -> were already merged by prior work
    # fico_range_high fico_range_low -> transformed before into avg fico
    "application_type", "avg_cur_bal", "bc_open_to_buy", "bc_util", "chargeoff_within_12_mths", "collections_12_mths_ex_med", "delinq_2yrs", "delinq_amnt", "earliest_cr_line", "il_util", "inq_fi", "inq_last_12m", "inq_last_6mths", "max_bal_bc", "mo_sin_old_il_acct", "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc", "mths_since_last_delinq", "mths_since_last_major_derog", "mths_since_last_record", "mths_since_rcnt_il", "mths_since_recent_bc", "mths_since_recent_bc_dlq", "mths_since_recent_inq", "mths_since_recent_revol_delinq", "num_accts_ever_120_pd", "num_actv_bc_tl", "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl", "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0", "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m", "num_tl_op_past_12m", "open_acc", "open_acc_6m", "open_il_12m", "open_il_24m", "open_act_il", "open_rv_12m", "open_rv_24m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec", "pub_rec_bankruptcies", "revol_bal", "revol_util", "tax_liens", "tot_coll_amt", "tot_cur_bal", "tot_hi_cred_lim", "total_acc", "total_bal_ex_mort", "total_bal_il", "total_bc_limit", "total_cu_tl", "total_il_high_credit_limit", "total_rev_hi_lim", "revol_bal_joint", "sec_app_earliest_cr_line", "sec_app_inq_last_6mths", "sec_app_mort_acc", "sec_app_open_acc", "sec_app_revol_util", "sec_app_open_act_il", "sec_app_num_rev_accts", "sec_app_chargeoff_within_12_mths", "sec_app_collections_12_mths_ex_med", "sec_app_mths_since_last_major_derog", "sec_app_fico_range_low", "sec_app_fico_range_high", # dti dti_joint -> already merged by prior work via max
]]

# Merge new features into the curated version of the dataset.
df = df.merge(new_features_from_original, on="id", how="left")
del new_features_from_original, original_df

as_cat_type = [
    # There are only two options on this website. This is ordinal technically, so we could treat it as a number too.
    "home_ownership_n",
    "application_type",
    "disbursement_method",
    "emp_length",
    "Default",
    "experience_c",
    "purpose",
]
as_string_type = [
    "emp_title",
    "addr_state",
    "zip_code",
    "title",
    "desc",
]

df["issue_d"] = pd.to_datetime(df["issue_d"], format="%b-%Y")
df["sec_app_earliest_cr_line"] = pd.to_datetime(df["sec_app_earliest_cr_line"], format="%b-%Y")
df["earliest_cr_line"] = pd.to_datetime(df["earliest_cr_line"], format="%b-%Y")

for c in as_string_type:
    nan_mask = df[c].isna()
    df.loc[nan_mask, c] = np.nan
    df[c] = df[c].astype("string")


df[as_cat_type] = df[as_cat_type].astype("category")

df = df[~df["application_type"].isna()]
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
df = df.drop(columns=[
    "id",  # meaningless identifier
    "experience_c", # constant after preprocessing
])

/tmp/ipykernel_939758/4121396100.py:4: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  original_df = pd.read_csv(dataset_mold.path /  "accepted_2007_to_2018Q4.csv.gz")
/tmp/ipykernel_939758/4121396100.py:5: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dataset_mold.path / "LC_loans_granting_model_dataset.csv?download=1")

Loaded data shape: (1347681, 15)
Original data shape: (2260701, 151)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
    duplicate_column_check=False, # skip
)

#### Dataset Overview
Rows: 1,310,259
Columns: 97

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,issue_d,annual_inc,dti_n,loan_amnt,fico_n,emp_length,purpose,home_ownership_n,addr_state,zip_code,Default,title,desc,emp_title,disbursement_method,acc_now_delinq,acc_open_past_24mths,all_util,sec_app_fico_n,application_type,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,collections_12_mths_ex_med,delinq_2yrs,delinq_amnt,earliest_cr_line,il_util,inq_fi,inq_last_12m,inq_last_6mths,max_bal_bc,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_last_delinq,mths_since_last_major_derog,mths_since_last_record,mths_since_rcnt_il,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,open_acc,open_acc_6m,open_il_12m,open_il_24m,open_act_il,open_rv_12m,open_rv_24m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec,pub_rec_bankruptcies,revol_bal,revol_util,tax_liens,tot_coll_amt,tot_cur_bal,tot_hi_cred_lim,total_acc,total_bal_ex_mort,total_bal_il,total_bc_limit,total_cu_tl,total_il_high_credit_limit,total_rev_hi_lim,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,sec_app_fico_range_low,sec_app_fico_range_high
0,2014-04-01,61000.0,10.06,25850,682.0,10+ years,debt_consolidation,RENT,GA,300xx,Fully Paid,Debt consolidation,<NA>,Asset Manager,Cash,0.0,1.0,NaN,NaN,Individual,1259.0,7882.0,65.3,0.0,0.0,0.0,0.0,1989-05-01,NaN,NaN,NaN,0.0,NaN,NaN,299.0,17.0,17.0,0.0,NaN,NaN,52.0,NaN,67.0,NaN,12.0,NaN,0.0,8.0,11.0,8.0,8.0,0.0,13.0,13.0,11.0,13.0,0.0,0.0,0.0,0.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,100.0,37.5,1.0,0.0,16365.0,36.0,1.0,0.0,16365.0,45400.0,13.0,16365.0,NaN,22700.0,NaN,0.0,45400.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-05-01,115000.0,8.31,28000,692.0,10+ years,debt_consolidation,RENT,NY,112xx,Fully Paid,Debt consolidation,<NA>,System Administrator,Cash,0.0,2.0,NaN,NaN,Individual,49682.0,8123.0,82.1,0.0,0.0,0.0,0.0,2003-09-01,NaN,NaN,NaN,0.0,NaN,110.0,140.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN,24.0,NaN,23.0,NaN,0.0,5.0,6.0,5.0,7.0,1.0,6.0,10.0,6.0,7.0,0.0,0.0,0.0,1.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,100.0,80.0,0.0,0.0,37318.0,80.6,0.0,0.0,347773.0,376300.0,13.0,37318.0,NaN,45300.0,NaN,0.0,46300.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-02-01,30000.0,8.68,12000,702.0,NI,credit_card,OWN,CA,952xx,Fully Paid,Credit card refinancing,credit card consolidation.,<NA>,Cash,0.0,3.0,NaN,NaN,Individual,1167.0,14004.0,44.0,0.0,0.0,0.0,0.0,1963-10-01,NaN,NaN,NaN,0.0,NaN,127.0,604.0,8.0,8.0,0.0,NaN,NaN,67.0,NaN,9.0,NaN,NaN,NaN,0.0,5.0,7.0,8.0,9.0,2.0,10.0,11.0,7.0,10.0,0.0,0.0,0.0,2.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,100.0,12.5,4.0,0.0,11672.0,40.4,4.0,0.0,11672.0,28900.0,13.0,11672.0,NaN,25000.0,NaN,0.0,28900.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-12-01,85000.0,7.58,3000,667.0,< 1 year,home_improvement,MORTGAGE,SC,294xx,Fully Paid,Home improvement,<NA>,Project Manager,Cash,0.0,5.0,33.0,NaN,Individual,43592.0,1796.0,62.6,0.0,0.0,0.0,0.0,2006-04-01,35.0,0.0,5.0,0.0,2304.0,116.0,115.0,8.0,3.0,4.0,65.0,66.0,39.0,49.0,8.0,NaN,3.0,NaN,1.0,2.0,3.0,2.0,4.0,2.0,5.0,7.0,3.0,7.0,0.0,0.0,0.0,2.0,7.0,1.0,0.0,0.0,1.0,1.0,4.0,92.3,0.0,1.0,0.0,3274.0,28.7,0.0,726.0,305144.0,327236.0,13.0,10644.0,7370.0,4800.0,1.0,21336.0,11400.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014-11-01,81435.0,17.27,25200,677.0,10+ years,debt_consolidation,MORTGAGE,VA,224xx,Defaulted,Debt consolidation,<NA>,Assistant Principal,Cash,0.0,6.0,NaN,NaN,Individual,39249.0,1392.0,88.7,0.0,0.0,0.0,0.0,2000-09-01,NaN,NaN,NaN,0.0,NaN,148.0,170.0,8.0,8.0,5.0,NaN,NaN,NaN,NaN,75.0,NaN,7.0,NaN,0.0,4.0,8.0,4.0,8.0,12.0,8.0,13.0,8.0,11.0,0.0,0.0,0.0,3.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,100.0,75.0,0.0,0.0,37909.0,86.9,0.0,0.0,431743.0,456444.0,30.0,53579.0,NaN,12300.0,NaN,19969.0,43600.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,emp_length,category,0,0.00,12,"10+ years, 2 years, < 1 year, 3 years, 1 year, 5 years, 4 years, NI, 6 years, 8 years"
1,purpose,category,0,0.00,14,"debt_consolidation, credit_card, home_improvement, other, major_purchase, medical, small_business, car, moving, vacation"
2,home_ownership_n,category,0,0.00,4,"MORTGAGE, RENT, OWN, OTHER"
3,Default,category,0,0.00,2,"Fully Paid, Defaulted"
4,disbursement_method,category,0,0.00,2,"Cash, DirectPay"
5,application_type,category,0,0.00,2,"Individual, Joint App"
6,sec_app_earliest_cr_line,datetime64[ns],1292511,98.65,570,"2006-08-01 00:00:00, 2005-08-01 00:00:00, 2006-09-01 00:00:00, 2006-07-01 00:00:00, 2004-08-01 00:00:00, 2005-06-01 00:00:00, 2004-09-01 00:00:00, 2006-03-01 00:00:00, 2006-05-01 00:00:00, 2005-11-01 00:00:00"
7,issue_d,datetime64[ns],0,0.00,129,"2016-03-01 00:00:00, 2015-10-01 00:00:00, 2015-07-01 00:00:00, 2015-12-01 00:00:00, 2014-10-01 00:00:00, 2016-02-01 00:00:00, 2015-11-01 00:00:00, 2015-04-01 00:00:00, 2015-08-01 00:00:00, 2015-01-01 00:00:00"
8,earliest_cr_line,datetime64[ns],0,0.00,739,"2001-08-01 00:00:00, 2002-08-01 00:00:00, 2003-09-01 00:00:00, 2001-10-01 00:00:00, 2000-08-01 00:00:00, 2002-09-01 00:00:00, 2004-09-01 00:00:00, 2003-08-01 00:00:00, 2000-10-01 00:00:00, 2002-10-01 00:00:00"
9,sec_app_mths_since_last_major_derog,float64,1303942,99.52,112,"1.0, 13.0, 4.0, 2.0, 8.0, 14.0, 9.0, 6.0, 3.0, 15.0"
10,sec_app_revol_util,float64,1292825,98.67,1112,"0.0, 60.4, 77.0, 76.9, 78.8, 56.4, 69.7, 64.1, 57.3, 47.0"
11,sec_app_fico_n,float64,1292511,98.65,60,"662.0, 672.0, 667.0, 652.0, 657.0, 677.0, 682.0, 692.0, 647.0, 687.0"
12,revol_bal_joint,float64,1292512,98.65,15472,"0.0, 21280.0, 28047.0, 15828.0, 23681.0, 14643.0, 7392.0, 32178.0, 22708.0, 14546.0"
13,sec_app_inq_last_6mths,float64,1292511,98.65,7,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0"
14,sec_app_mort_acc,float64,1292511,98.65,17,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
15,sec_app_open_acc,float64,1292511,98.65,54,"8.0, 9.0, 7.0, 10.0, 6.0, 11.0, 12.0, 5.0, 13.0, 14.0"
16,sec_app_open_act_il,float64,1292511,98.65,33,"1.0, 2.0, 3.0, 0.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
17,sec_app_num_rev_accts,float64,1292511,98.65,68,"9.0, 8.0, 7.0, 10.0, 11.0, 6.0, 12.0, 5.0, 13.0, 4.0"
18,sec_app_chargeoff_within_12_mths,float64,1292511,98.65,14,"0.0, 1.0, 2.0, 3.0, 5.0, 4.0, 10.0, 6.0, 7.0, 8.0"
19,sec_app_collections_12_mths_ex_med,float64,1292511,98.65,11,"0.0, 1.0, 2.0, 3.0, 4.0, 6.0, 8.0, 5.0, 10.0, 11.0"
20,sec_app_fico_range_low,float64,1292511,98.65,60,"660.0, 670.0, 665.0, 650.0, 655.0, 675.0, 680.0, 690.0, 645.0, 685.0"
21,sec_app_fico_range_high,float64,1292511,98.65,60,"664.0, 674.0, 669.0, 654.0, 659.0, 679.0, 684.0, 694.0, 649.0, 689.0"
22,mths_since_last_record,float64,1088483,83.07,125,"71.0, 79.0, 72.0, 75.0, 77.0, 80.0, 69.0, 67.0, 76.0, 70.0"
23,mths_since_recent_bc_dlq,float64,998723,76.22,167,"26.0, 13.0, 19.0, 28.0, 25.0, 45.0, 29.0, 18.0, 31.0, 15.0"
24,mths_since_last_major_derog,float64,964883,73.64,173,"43.0, 45.0, 40.0, 42.0, 46.0, 38.0, 41.0, 44.0, 48.0, 47.0"
25,mths_since_recent_revol_delinq,float64,870864,66.47,167,"13.0, 12.0, 14.0, 15.0, 9.0, 7.0, 19.0, 11.0, 8.0, 17.0"
26,il_util,float64,865149,66.03,234,"83.0, 81.0, 85.0, 78.0, 86.0, 80.0, 82.0, 75.0, 79.0, 77.0"
27,mths_since_rcnt_il,float64,809413,61.78,341,"4.0, 7.0, 3.0, 6.0, 5.0, 8.0, 9.0, 2.0, 10.0, 13.0"
28,all_util,float64,795858,60.74,169,"63.0, 64.0, 59.0, 60.0, 67.0, 65.0, 66.0, 62.0, 61.0, 68.0"
29,inq_fi,float64,795807,60.74,30,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
30,inq_last_12m,float64,795808,60.74,42,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
31,max_bal_bc,float64,795807,60.74,27282,"0.0, 3000.0, 2000.0, 8.0, 4000.0, 5000.0, 2500.0, 3500.0, 1500.0, 1900.0"
32,open_acc_6m,float64,795808,60.74,19,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
33,open_il_12m,float64,795807,60.74,19,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
34,open_il_24m,float64,795807,60.74,31,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
35,open_act_il,float64,795807,60.74,49,"1.0, 2.0, 3.0, 0.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
36,open_rv_12m,float64,795807,60.74,27,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
37,open_rv_24m,float64,795807,60.74,47,"1.0, 2.0, 3.0, 0.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
38,total_bal_il,float64,795807,60.74,116607,"0.0, 10000.0, 15000.0, 5000.0, 9500.0, 5500.0, 20000.0, 3000.0, 14000.0, 2500.0"
39,total_cu_tl,float64,795808,60.74,53,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
40,mths_since_last_delinq,float64,660989,50.45,163,"13.0, 12.0, 9.0, 6.0, 7.0, 14.0, 8.0, 15.0, 10.0, 11.0"
41,mths_since_recent_inq,float64,166314,12.69,26,"1.0, 2.0, 0.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
42,num_tl_120dpd_2m,float64,111601,8.52,6,"0.0, 1.0, 2.0, 3.0, 6.0, 4.0"
43,mo_sin_old_il_acct,float64,99866,7.62,519,"125.0, 126.0, 127.0, 122.0, 128.0, 124.0, 130.0, 129.0, 132.0, 121.0"
44,pct_tl_nvr_dlq,float64,62788,4.79,630,"100.0, 95.0, 90.0, 96.0, 91.7, 90.9, 92.3, 92.9, 88.9, 87.5"
45,avg_cur_bal,float64,62655,4.78,76350,"0.0, 1971.0, 2606.0, 2656.0, 2253.0, 2447.0, 2831.0, 2842.0, 1956.0, 2142.0"
46,mo_sin_old_rev_tl_op,float64,62635,4.78,756,"132.0, 125.0, 131.0, 136.0, 129.0, 127.0, 130.0, 133.0, 128.0, 124.0"
47,mo_sin_rcnt_rev_tl_op,float64,62635,4.78,284,"2.0, 3.0, 4.0, 1.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
48,mo_sin_rcnt_tl,float64,62634,4.78,193,"2.0, 3.0, 4.0, 1.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
49,num_accts_ever_120_pd,float64,62634,4.78,39,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
50,num_actv_bc_tl,float64,62634,4.78,34,"3.0, 2.0, 4.0, 1.0, 5.0, 6.0, 7.0, 8.0, 0.0, 9.0"
51,num_actv_rev_tl,float64,62634,4.78,52,"4.0, 5.0, 3.0, 6.0, 2.0, 7.0, 8.0, 9.0, 1.0, 10.0"
52,num_bc_tl,float64,62634,4.78,68,"5.0, 6.0, 7.0, 4.0, 8.0, 3.0, 9.0, 10.0, 11.0, 2.0"
53,num_il_tl,float64,62634,4.78,114,"4.0, 3.0, 5.0, 2.0, 6.0, 7.0, 8.0, 1.0, 9.0, 10.0"
54,num_op_rev_tl,float64,62634,4.78,73,"6.0, 5.0, 7.0, 8.0, 4.0, 9.0, 10.0, 3.0, 11.0, 12.0"
55,num_rev_accts,float64,62635,4.78,107,"10.0, 11.0, 9.0, 12.0, 8.0, 13.0, 7.0, 14.0, 15.0, 6.0"
56,num_rev_tl_bal_gt_0,float64,62634,4.78,46,"4.0, 5.0, 3.0, 6.0, 2.0, 7.0, 8.0, 9.0, 1.0, 10.0"
57,num_tl_30dpd,float64,62634,4.78,5,"0.0, 1.0, 2.0, 3.0, 4.0"
58,num_tl_90g_dpd_24m,float64,62634,4.78,29,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
59,num_tl_op_past_12m,float64,62634,4.78,32,"1.0, 2.0, 0.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
60,tot_coll_amt,float64,62634,4.78,12745,"0.0, 50.0, 100.0, 75.0, 150.0, 200.0, 60.0, 70.0, 80.0, 65.0"
61,tot_cur_bal,float64,62634,4.78,396601,"0.0, 18311.0, 24742.0, 29232.0, 25148.0, 14511.0, 28842.0, 20084.0, 30191.0, 34574.0"
62,tot_hi_cred_lim,float64,62634,4.78,423124,"12500.0, 15500.0, 16500.0, 17500.0, 15000.0, 18000.0, 13500.0, 17700.0, 16000.0, 10000.0"
63,total_il_high_credit_limit,float64,62634,4.78,161405,"0.0, 10000.0, 15000.0, 20000.0, 5000.0, 25000.0, 12000.0, 6000.0, 8000.0, 4000.0"
64,total_rev_hi_lim,float64,62634,4.78,26533,"10000.0, 15000.0, 11500.0, 13000.0, 12000.0, 11000.0, 14000.0, 13500.0, 12500.0, 14500.0"
65,bc_util,float64,56670,4.33,1442,"0.0, 98.0, 97.0, 96.0, 99.0, 95.0, 94.0, 93.0, 92.0, 91.0"
66,percent_bc_gt_75,float64,56321,4.30,245,"0.0, 100.0, 50.0, 33.3, 66.7, 25.0, 75.0, 20.0, 40.0, 60.0"
67,bc_open_to_buy,float64,55913,4.27,74380,"0.0, 2000.0, 500.0, 1000.0, 3000.0, 2500.0, 1500.0, 5000.0, 3500.0, 4000.0"
68,mths_since_recent_bc,float64,55006,4.20,490,"3.0, 2.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 10.0"
69,num_bc_sats,float64,50948,3.89,51,"3.0, 4.0, 2.0, 5.0, 6.0, 7.0, 1.0, 8.0, 9.0, 10.0"
70,num_sats,float64,50948,3.89,82,"9.0, 10.0, 8.0, 11.0, 7.0, 12.0, 6.0, 13.0, 14.0, 5.0"
71,acc_open_past_24mths,float64,42388,3.24,55,"3.0, 4.0, 2.0, 5.0, 6.0, 1.0, 7.0, 8.0, 0.0, 9.0"
72,mort_acc,float64,42388,3.24,39,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
73,total_bal_ex_mort,float64,42388,3.24,176628,"0.0, 34058.0, 19095.0, 23068.0, 20275.0, 34638.0, 28842.0, 24805.0, 21168.0, 19217.0"
74,total_bc_limit,float64,42388,3.24,16995,"0.0, 5000.0, 6000.0, 7000.0, 4000.0, 10000.0, 3000.0, 8000.0, 7500.0, 9000.0"
75,revol_util,float64,823,0.06,1370,"0.0, 57.0, 58.0, 53.0, 54.0, 59.0, 48.0, 55.0, 61.0, 51.0"
76,annual_inc,float64,0,0.00,64458,"60000.0, 50000.0, 65000.0, 70000.0, 80000.0, 40000.0, 75000.0, 45000.0, 55000.0, 100000.0"
77,dti_n,float64,0,0.00,7010,"18.0, 19.2, 14.4, 16.8, 13.2, 15.6, 12.0, 20.4, 21.6, 0.0"
78,fico_n,float64,0,0.00,38,"662.0, 672.0, 667.0, 677.0, 682.0, 687.0, 692.0, 697.0, 702.0, 707.0"
79,acc_now_delinq,float64,0,0.00,8,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 14.0"
80,chargeoff_within_12_mths,float64,0,0.00,11,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 9.0, 8.0"
81,collections_12_mths_ex_med,float64,0,0.00,15,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 10.0, 12.0"
82,delinq_2yrs,float64,0,0.00,31,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
83,delinq_amnt,float64,0,0.00,1965,"0.0, 65000.0, 25.0, 30.0, 54.0, 53.0, 75.0, 56.0, 50.0, 52.0"
84,inq_last_6mths,float64,1,0.00,9,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0"
85,open_acc,float64,0,0.00,83,"9.0, 10.0, 8.0, 11.0, 7.0, 12.0, 6.0, 13.0, 14.0, 5.0"
86,pub_rec,float64,0,0.00,36,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
87,pub_rec_bankruptcies,float64,6,0.00,11,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
88,revol_bal,float64,0,0.00,83069,"0.0, 5235.0, 4777.0, 6312.0, 6118.0, 5849.0, 5249.0, 5655.0, 5891.0, 2.0"
89,tax_liens,float64,0,0.00,35,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
90,total_acc,float64,0,0.00,142,"20.0, 21.0, 22.0, 19.0, 18.0, 23.0, 17.0, 24.0, 16.0, 25.0"
91,loan_amnt,int64,0,0.00,1547,"10000, 12000, 20000, 15000, 35000, 5000, 8000, 6000, 16000, 25000"
92,desc,string,1191160,90.91,109539,"Debt consolidation., Debt Consolidation., debt consolidation., Pay off credit cards., Credit card consolidation., pay off credit cards., To pay off credit cards., credit card consolidation., Credit Card Consolidation., Consolidation."
93,emp_title,string,83048,6.34,370596,"Teacher, Manager, Owner, Registered Nurse, RN, Supervisor, Driver, Sales, Project Manager, Office Manager"
94,title,string,16043,1.22,58108,"Debt consolidation, Credit card refinancing, Home improvement, Other, Major purchase, Debt Consolidation, Medical expenses, Business, Car financing, Vacation"
95,addr_state,string,0,0.00,51,"CA, TX, NY, FL, IL, NJ, PA, OH, GA, VA"
96,zip_code,string,1,0.00,942,"945xx, 750xx, 112xx, 606xx, 300xx, 331xx, 070xx, 100xx, 891xx, 900xx"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
annual_inc,1310259.0,77373.918126,70570.866233,2000.0,10999200.0
dti_n,1310259.0,18.317660,11.059676,0.0,999.0
loan_amnt,1310259.0,14424.098728,8711.320446,1000.0,40000.0
fico_n,1310259.0,698.131801,31.822966,662.0,847.5
acc_now_delinq,1310259.0,0.005062,0.077360,0.0,14.0
acc_open_past_24mths,1267871.0,4.686723,3.182407,0.0,64.0
all_util,514401.0,58.156073,20.941521,0.0,198.0
sec_app_fico_n,17748.0,668.031666,45.920621,542.0,842.0
avg_cur_bal,1247604.0,13482.036988,16268.948554,0.0,958084.0
bc_open_to_buy,1254346.0,10165.366754,15323.730620,0.0,497445.0
bc_util,1253589.0,60.015968,28.277526,0.0,339.6
chargeoff_within_12_mths,1310259.0,0.009107,0.110098,0.0,10.0
collections_12_mths_ex_med,1310259.0,0.017127,0.147133,0.0,20.0
delinq_2yrs,1310259.0,0.318187,0.878507,0.0,39.0
delinq_amnt,1310259.0,14.867350,810.265471,0.0,249925.0
il_util,445110.0,71.388603,22.911125,0.0,558.0
inq_fi,514452.0,1.093115,1.585086,0.0,48.0
inq_last_12m,514451.0,2.308673,2.537439,0.0,67.0
inq_last_6mths,1310258.0,0.654565,0.937757,0.0,8.0
max_bal_bc,514452.0,5544.004628,5472.891613,0.0,776843.0
mo_sin_old_il_acct,1210393.0,125.827819,52.214519,0.0,999.0
mo_sin_old_rev_tl_op,1247624.0,181.522249,94.467187,2.0,852.0
mo_sin_rcnt_rev_tl_op,1247624.0,13.125273,16.334770,0.0,438.0
mo_sin_rcnt_tl,1247625.0,7.865849,8.727060,0.0,314.0
mort_acc,1267871.0,1.672094,2.001630,0.0,51.0
mths_since_last_delinq,649270.0,34.335905,21.908450,0.0,226.0
mths_since_last_major_derog,345376.0,43.693349,21.380684,0.0,226.0
mths_since_last_record,221776.0,70.855097,26.343462,0.0,124.0
mths_since_rcnt_il,500846.0,19.595133,24.850100,0.0,511.0
mths_since_recent_bc,1255253.0,23.839701,30.733374,0.0,639.0
mths_since_recent_bc_dlq,311536.0,39.665281,22.699263,0.0,202.0
mths_since_recent_inq,1143945.0,6.722080,5.849914,0.0,25.0
mths_since_recent_revol_delinq,439395.0,35.819238,22.425245,0.0,202.0
num_accts_ever_120_pd,1247625.0,0.508774,1.322973,0.0,51.0
num_actv_bc_tl,1247625.0,3.644973,2.248449,0.0,35.0
num_actv_rev_tl,1247625.0,5.647768,3.303554,0.0,63.0
num_bc_sats,1259311.0,4.735522,2.951577,0.0,57.0
num_bc_tl,1247625.0,8.108097,4.801474,0.0,70.0
num_il_tl,1247625.0,8.564001,7.383265,0.0,159.0
num_op_rev_tl,1247625.0,8.279937,4.556212,0.0,79.0
num_rev_accts,1247624.0,14.618168,8.118819,0.0,128.0
num_rev_tl_bal_gt_0,1247625.0,5.596584,3.216392,0.0,45.0
num_sats,1259311.0,11.639200,5.480099,0.0,87.0
num_tl_120dpd_2m,1198658.0,0.000813,0.030310,0.0,6.0
num_tl_30dpd,1247625.0,0.003425,0.062467,0.0,4.0
num_tl_90g_dpd_24m,1247625.0,0.088866,0.503686,0.0,39.0
num_tl_op_past_12m,1247625.0,2.175092,1.841721,0.0,32.0
open_acc,1310259.0,11.599846,5.473602,0.0,88.0
open_acc_6m,514451.0,1.047200,1.206377,0.0,18.0
open_il_12m,514452.0,0.774494,0.990904,0.0,25.0
open_il_24m,514452.0,1.741432,1.682864,0.0,51.0
open_act_il,514452.0,2.792603,2.987931,0.0,57.0
open_rv_12m,514452.0,1.418471,1.573085,0.0,28.0
open_rv_24m,514452.0,3.002634,2.701602,0.0,53.0
pct_tl_nvr_dlq,1247471.0,94.166564,8.740588,0.0,100.0
percent_bc_gt_75,1253938.0,45.249071,36.000346,0.0,100.0
pub_rec,1310259.0,0.215003,0.599267,0.0,86.0
pub_rec_bankruptcies,1310253.0,0.134305,0.377543,0.0,12.0
revol_bal,1310259.0,16256.961315,22299.379672,0.0,2904836.0
revol_util,1309436.0,51.858786,24.505909,0.0,892.3
tax_liens,1310259.0,0.051949,0.394336,0.0,85.0
tot_coll_amt,1247625.0,248.043637,11136.988428,0.0,9152545.0
tot_cur_bal,1247625.0,141065.623991,157307.696379,0.0,8000078.0
tot_hi_cred_lim,1247625.0,174269.128862,177425.148263,0.0,9999999.0
total_acc,1310259.0,24.997714,11.997515,2.0,176.0
total_bal_ex_mort,1267871.0,49637.862075,47704.152218,0.0,3408095.0
total_bal_il,514452.0,35884.640483,42966.256345,0.0,1711009.0
total_bc_limit,1267871.0,21623.852315,21528.222242,0.0,1105500.0
total_cu_tl,514451.0,1.609265,2.823912,0.0,79.0
total_il_high_credit_limit,1247625.0,42099.765245,43231.825100,0.0,2101913.0
total_rev_hi_lim,1247625.0,32770.009965,36652.011460,0.0,9999999.0
revol_bal_joint,17747.0,31629.244323,26725.864623,0.0,357135.0
sec_app_inq_last_6mths,17748.0,0.751465,1.088694,0.0,6.0
sec_app_mort_acc,17748.0,1.666498,1.832309,0.0,18.0
sec_app_open_acc,17748.0,11.315867,6.500618,0.0,82.0
sec_app_revol_util,17434.0,57.229712,26.487949,0.0,212.6
sec_app_open_act_il,17748.0,2.939768,3.170682,0.0,35.0
sec_app_num_rev_accts,17748.0,12.829953,8.362858,0.0,92.0
sec_app_chargeoff_within_12_mths,17748.0,0.055556,0.448461,0.0,20.0
sec_app_collections_12_mths_ex_med,17748.0,0.086545,0.415718,0.0,11.0
sec_app_mths_since_last_major_derog,6317.0,36.417128,23.970526,0.0,132.0
sec_app_fico_range_low,17748.0,666.031666,45.920621,540.0,840.0
sec_app_fico_range_high,17748.0,670.031666,45.920621,544.0,844.0

In [7]:
# Categorical Feature Statistics
cat_stats

                                                 value    count    pct
column                   rank
Default                  1                  Fully Paid  1049280  80.08
                         2                   Defaulted   260979  19.92
addr_state               1                          CA   191332   14.6
                         2                          TX   107251   8.19
                         3                          NY   106908   8.16
                         4                          FL    93025    7.1
                         5                          IL    50462   3.85
application_type         1                  Individual  1285632  98.12
                         2                   Joint App    24627   1.88
desc                     1                        <NA>  1191160  90.91
                         2         Debt consolidation.     1170   0.09
                         3         Debt Consolidation.      689   0.05
                         4         debt consolidation.      599   0.05
                         5       Pay off credit cards.      248   0.02
disbursement_method      1                        Cash  1303542  99.49
                         2                   DirectPay     6717   0.51
earliest_cr_line         1         2001-08-01 00:00:00     9178    0.7
                         2         2002-08-01 00:00:00     8834   0.67
                         3         2003-09-01 00:00:00     8785   0.67
                         4         2001-10-01 00:00:00     8634   0.66
                         5         2000-08-01 00:00:00     8618   0.66
emp_length               1                   10+ years   431065   32.9
                         2                     2 years   118464   9.04
                         3                    < 1 year   104976   8.01
                         4                     3 years   104782    8.0
                         5                      1 year    86098   6.57
emp_title                1                        <NA>    83048   6.34
                         2                     Teacher    20745   1.58
                         3                     Manager    18951   1.45
                         4                       Owner     9976   0.76
                         5            Registered Nurse     8566   0.65
home_ownership_n         1                    MORTGAGE   649016  49.53
                         2                        RENT   519944  39.68
                         3                         OWN   140836  10.75
                         4                       OTHER      463   0.04
issue_d                  1         2016-03-01 00:00:00    46175   3.52
                         2         2015-10-01 00:00:00    42986   3.28
                         3         2015-07-01 00:00:00    41053   3.13
                         4         2015-12-01 00:00:00    39001   2.98
                         5         2014-10-01 00:00:00    36072   2.75
purpose                  1          debt_consolidation   760858  58.07
                         2                 credit_card   287800  21.97
                         3            home_improvement    85125    6.5
                         4                       other    75405   5.75
                         5              major_purchase    28576   2.18
sec_app_earliest_cr_line 1                        <NA>  1292511  98.65
                         2         2006-08-01 00:00:00      192   0.01
                         3         2005-08-01 00:00:00      164   0.01
                         4         2006-09-01 00:00:00      163   0.01
                         5         2006-07-01 00:00:00      151   0.01
title                    1          Debt consolidation   645943   49.3
                         2     Credit card refinancing   244239  18.64
                         3            Home improvement    73100   5.58
                         4                       Other    64801   4.95
                         5              Major purchase    23358   1.78
zip_code                 1                       945xx    14631   1.12
                         2                       750xx    14119   1.08
                         3                       112xx    13444   1.03
                         4                       606xx    12115   0.92
                         5                       300xx    11814    0.9

In [8]:
# Target Distribution
target_df

              count    pct
Default
Fully Paid  1049280  80.08
Defaulted    260979  19.92

## Task Curation

In [9]:
time_df = df.copy()
time_df["year_month"] = time_df[task_mold.time_on].dt.to_period("Y")

# 1) Total number of samples per month
monthly_totals = (
    time_df
    .groupby("year_month")
    .size()
    .rename("total_samples")
)

# Optional: sort by month and convert PeriodIndex to timestamp (month start)
result = monthly_totals.sort_index()
result.index = result.index.to_timestamp()
result

year_month
2008-01-01       836
2009-01-01      4716
2010-01-01     11536
2011-01-01     19776
2012-01-01     51396
2013-01-01    132915
2014-01-01    221034
2015-01-01    372542
2016-01-01    276431
2017-01-01    164085
2018-01-01     54992
Freq: YS-JAN, Name: total_samples, dtype: int64

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata

# Sort by time
df = df.sort_values(by=task_mold.time_on).reset_index(drop=True)

splits = {}

test_years = [
    "2016",
    "2017",
    "2018"
]
for i, month in enumerate(test_years):
    ref_date  = pd.Timestamp(month)
    train_index = df[
        df[task_mold.time_on] < ref_date
    ].index
    test_index = df[
        (df[task_mold.time_on].dt.year == ref_date.year)
    ].index
    splits[i] = {
        0: (train_index.tolist(), test_index.tolist())
    }

for s in splits:
    train_index, test_index = splits[s][0]
    print(f"Split {s}: Train size: {len(train_index)}, Test size: {len(test_index)}")
    assert df[task_mold.time_on].iloc[train_index].max() < df[task_mold.time_on].iloc[test_index].min()

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="""We try to create splits that simulate a model deployed to solve the task.

The official data is updated monthly but has not enough data per month to create large enough test splits. We opt for simulating a model that is refit every year to obtain a robust test set instead. This introduces the unrealistic downside of data shift across a year that would not exist in a real-world model. We create 3 test splits (2016, 2017, 2018). For each test split, we use all data before the test month as training data.
""",
    splits=splits,
)

Split 0: Train size: 814751, Test size: 276431
Split 1: Train size: 1091182, Test size: 164085
Split 2: Train size: 1255267, Test size: 54992

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019c329b-28de-79cb-9b1a-3afb125e0b9c
43d80689126e783b675bcde2edf8e2213f06d67ff7ac4eb6d4653ec09f081c1c