### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="taiwanese_bankruptcy_prediction",
    dataset_year="2009",
    domain_str="finance",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C5004D",
    download_description="""
We download the data from the UCI repository and uzip it to a predefined folder.

mkdir -p local-data-warehouse/taiwanese_bankruptcy_prediction/ && wget -P local-data-warehouse/taiwanese_bankruptcy_prediction/ https://archive.ics.uci.edu/static/public/572/taiwanese+bankruptcy+prediction.zip && unzip local-data-warehouse/taiwanese_bankruptcy_prediction/taiwanese+bankruptcy+prediction.zip -d local-data-warehouse/taiwanese_bankruptcy_prediction/ && rm local-data-warehouse/taiwanese_bankruptcy_prediction/taiwanese+bankruptcy+prediction.zip
""",
    # References
    academic_reference_bibtex="""@article{liang2016financial,
  title={Financial ratios and corporate governance indicators in bankruptcy prediction: A comprehensive study},
  author={Liang, Deron and Lu, Chia-Chi and Tsai, Chih-Fong and Shih, Guan-An},
  journal={European journal of operational research},
  volume={252},
  number={2},
  pages={561--572},
  year={2016},
  publisher={Elsevier}
}
""",
    academic_reference_bibtex_key="liang2016financial",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
- We map binary Bankrupt column to yes/no
- We rename the features to be shorter and have no special characters.
- We drop the constant column "Net_Income_Flag".
- We drop two duplicated features (same values as other features).
- Anomaly: the paper introducing the dataset has more features, but these do not seem to be in the dataset. 
- Anomaly: the data is temporal but all features are time-invariant. This might still have a latent, non-verifiable temporal component, which we ignore for our predictive IID task.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Bankrupt",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="Bankrupt",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(f"{dataset_mold.path}/data.csv")

df.columns = [
    "Bankrupt",
    "ROA_C_Before_Interest_Depreciation",
    "ROA_A_Before_Interest_After_Tax",
    "ROA_B_Before_Interest_Depreciation_After_Tax",
    "Operating_Gross_Margin",
    "Realized_Sales_Gross_Margin",
    "Operating_Profit_Rate",
    "PreTax_Net_Interest_Rate",
    "AfterTax_Net_Interest_Rate",
    "NonIndustry_Income_Expenditure_Revenue",
    "Continuous_Interest_Rate_After_Tax",
    "Operating_Expense_Rate",
    "R&D_Expense_Rate",
    "Cash_Flow_Rate",
    "InterestBearing_Debt_Interest_Rate",
    "Tax_Rate_A",
    "Net_Value_Per_Share_B",
    "Net_Value_Per_Share_A",
    "Net_Value_Per_Share_C",
    "Persistent_EPS_Last_4_Seasons",
    "Cash_Flow_Per_Share",
    "Revenue_Per_Share",
    "Operating_Profit_Per_Share",
    "Net_Profit_Before_Tax_Per_Share",
    "Realized_Sales_Gross_Profit_Growth_Rate",
    "Operating_Profit_Growth_Rate",
    "AfterTax_Net_Profit_Growth_Rate",
    "Regular_Net_Profit_Growth_Rate",
    "Continuous_Net_Profit_Growth_Rate",
    "Total_Asset_Growth_Rate",
    "Net_Value_Growth_Rate",
    "Total_Asset_Return_Growth_Rate",
    "Cash_Reinvestment_Percent",
    "Current_Ratio",
    "Quick_Ratio",
    "Interest_Expense_Ratio",
    "Total_Debt_to_Net_Worth",
    "Debt_Ratio_Percent",
    "Net_Worth_to_Assets",
    "LongTerm_Fund_Suitability_Ratio_A",
    "Borrowing_Dependency",
    "Contingent_Liabilities_to_Net_Worth",
    "Operating_Profit_to_PaidIn_Capital",
    "Net_Profit_Before_Tax_to_PaidIn_Capital",
    "Inventory_Accounts_Receivable_to_Net_Value",
    "Total_Asset_Turnover",
    "Accounts_Receivable_Turnover",
    "Average_Collection_Days",
    "Inventory_Turnover_Rate",
    "Fixed_Assets_Turnover_Frequency",
    "Net_Worth_Turnover_Rate",
    "Revenue_Per_Person",
    "Operating_Profit_Per_Person",
    "Allocation_Rate_Per_Person",
    "Working_Capital_to_Total_Assets",
    "Quick_Assets_to_Total_Assets",
    "Current_Assets_to_Total_Assets",
    "Cash_to_Total_Assets",
    "Quick_Assets_to_Current_Liability",
    "Cash_to_Current_Liability",
    "Current_Liability_to_Assets",
    "Operating_Funds_to_Liability",
    "Inventory_to_Working_Capital",
    "Inventory_to_Current_Liability",
    "Current_Liabilities_to_Liability",
    "Working_Capital_to_Equity",
    "Current_Liabilities_to_Equity",
    "LongTerm_Liability_to_Current_Assets",
    "Retained_Earnings_to_Total_Assets",
    "Total_Income_to_Total_Expense",
    "Total_Expense_to_Assets",
    "Current_Asset_Turnover_Rate",
    "Quick_Asset_Turnover_Rate",
    "Working_Capital_Turnover_Rate",
    "Cash_Turnover_Rate",
    "Cash_Flow_to_Sales",
    "Fixed_Assets_to_Assets",
    "Current_Liability_to_Liability",
    "Current_Liability_to_Equity",
    "Equity_to_LongTerm_Liability",
    "Cash_Flow_to_Total_Assets",
    "Cash_Flow_to_Liability",
    "CFO_to_Assets",
    "Cash_Flow_to_Equity",
    "Current_Liability_to_Current_Assets",
    "Liability_Assets_Flag",
    "Net_Income_to_Total_Assets",
    "Total_Assets_to_GNP_Price",
    "NoCredit_Interval",
    "Gross_Profit_to_Sales",
    "Net_Income_to_Stockholders_Equity",
    "Liability_to_Equity",
    "DFL",
    "Interest_Coverage_Ratio",
    "Net_Income_Flag",
    "Equity_to_Liability",
]

cat_features = [
    "Bankrupt",
]
df["Bankrupt"] = df["Bankrupt"].map({0: "No", 1: "Yes"})
df[cat_features] = df[cat_features].astype("category")

df = df.drop(columns=[
    "Net_Income_Flag",
    "Current_Liability_to_Liability",
    "Current_Liability_to_Equity",
])

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 6,819
Columns: 93
Use sampling: False (sample size: 6,819)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['Working_Capital_to_Equity', 'Working_Capital_Turnover_Rate', 'Cash_Flow_to_Sales', 'Total_Expense_to_Assets', 'Total_Income_to_Total_Expense', 'Operating_Funds_to_Liability', 'Retained_Earnings_to_Total_Assets', 'Current_Liability_to_Current_Assets', 'Net_Income_to_Total_Assets', 'Cash_Flow_to_Equity']
Rows remaining as candidates after top-10 filter: 0 (of 6,819)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,Bankrupt,ROA_C_Before_Interest_Depreciation,ROA_A_Before_Interest_After_Tax,ROA_B_Before_Interest_Depreciation_After_Tax,Operating_Gross_Margin,Realized_Sales_Gross_Margin,Operating_Profit_Rate,PreTax_Net_Interest_Rate,AfterTax_Net_Interest_Rate,NonIndustry_Income_Expenditure_Revenue,Continuous_Interest_Rate_After_Tax,Operating_Expense_Rate,R&D_Expense_Rate,Cash_Flow_Rate,InterestBearing_Debt_Interest_Rate,Tax_Rate_A,Net_Value_Per_Share_B,Net_Value_Per_Share_A,Net_Value_Per_Share_C,Persistent_EPS_Last_4_Seasons,Cash_Flow_Per_Share,Revenue_Per_Share,Operating_Profit_Per_Share,Net_Profit_Before_Tax_Per_Share,Realized_Sales_Gross_Profit_Growth_Rate,Operating_Profit_Growth_Rate,AfterTax_Net_Profit_Growth_Rate,Regular_Net_Profit_Growth_Rate,Continuous_Net_Profit_Growth_Rate,Total_Asset_Growth_Rate,Net_Value_Growth_Rate,Total_Asset_Return_Growth_Rate,Cash_Reinvestment_Percent,Current_Ratio,Quick_Ratio,Interest_Expense_Ratio,Total_Debt_to_Net_Worth,Debt_Ratio_Percent,Net_Worth_to_Assets,LongTerm_Fund_Suitability_Ratio_A,Borrowing_Dependency,Contingent_Liabilities_to_Net_Worth,Operating_Profit_to_PaidIn_Capital,Net_Profit_Before_Tax_to_PaidIn_Capital,Inventory_Accounts_Receivable_to_Net_Value,Total_Asset_Turnover,Accounts_Receivable_Turnover,Average_Collection_Days,Inventory_Turnover_Rate,Fixed_Assets_Turnover_Frequency,Net_Worth_Turnover_Rate,Revenue_Per_Person,Operating_Profit_Per_Person,Allocation_Rate_Per_Person,Working_Capital_to_Total_Assets,Quick_Assets_to_Total_Assets,Current_Assets_to_Total_Assets,Cash_to_Total_Assets,Quick_Assets_to_Current_Liability,Cash_to_Current_Liability,Current_Liability_to_Assets,Operating_Funds_to_Liability,Inventory_to_Working_Capital,Inventory_to_Current_Liability,Current_Liabilities_to_Liability,Working_Capital_to_Equity,Current_Liabilities_to_Equity,LongTerm_Liability_to_Current_Assets,Retained_Earnings_to_Total_Assets,Total_Income_to_Total_Expense,Total_Expense_to_Assets,Current_Asset_Turnover_Rate,Quick_Asset_Turnover_Rate,Working_Capital_Turnover_Rate,Cash_Turnover_Rate,Cash_Flow_to_Sales,Fixed_Assets_to_Assets,Equity_to_LongTerm_Liability,Cash_Flow_to_Total_Assets,Cash_Flow_to_Liability,CFO_to_Assets,Cash_Flow_to_Equity,Current_Liability_to_Current_Assets,Liability_Assets_Flag,Net_Income_to_Total_Assets,Total_Assets_to_GNP_Price,NoCredit_Interval,Gross_Profit_to_Sales,Net_Income_to_Stockholders_Equity,Liability_to_Equity,DFL,Interest_Coverage_Ratio,Equity_to_Liability
0,No,0.434456,0.481247,0.498742,0.596326,0.596326,0.998791,0.797012,0.809041,0.303237,0.781291,2.217908e-04,3.040000e+09,0.473117,0.000000,0.000000,0.174076,0.174076,0.174076,0.202515,0.320153,0.009755,0.087452,0.156963,0.021977,0.842429,0.685817,0.685817,0.217409,5.620000e+09,0.000419,0.263370,0.379056,0.016739,0.014061,0.630611,0.001595,0.043807,0.956193,0.005102,0.369637,0.007023,0.087466,0.155991,0.395832,0.065967,0.000781,0.008093,2.967364e-04,5.900000e+09,0.017419,0.004304,0.389498,0.009512,0.787113,0.185681,0.204108,0.046863,0.014760,0.010498,0.023262,0.357598,0.277073,0.005461,0.472822,0.733696,0.326899,0.000000,0.922162,0.002054,0.029762,1.104112e-04,1.054056e-04,0.593969,7.230000e+09,0.671572,0.624778,0.110933,0.642917,0.459268,0.590226,0.314565,0.017526,0,0.765336,0.001373,0.626305,0.596326,0.838369,0.275936,0.026791,0.565157,0.087378
1,No,0.542534,0.571413,0.590663,0.603417,0.603417,0.999041,0.797476,0.809375,0.303526,0.781638,8.550000e+09,1.550000e+09,0.467422,0.000264,0.251645,0.189078,0.189078,0.189078,0.232107,0.329561,0.053753,0.115300,0.188522,0.022079,0.848008,0.689377,0.689377,0.217591,6.220000e+09,0.000466,0.263868,0.385297,0.009777,0.005425,0.631052,0.007164,0.130000,0.870000,0.005211,0.376524,0.005366,0.115280,0.187588,0.404142,0.193403,0.001051,0.006012,1.282100e-04,2.632612e-04,0.048387,0.018736,0.396938,0.008633,0.809259,0.384289,0.556516,0.049034,0.006546,0.002434,0.106642,0.354767,0.277414,0.008694,0.775494,0.736243,0.331198,0.004023,0.946527,0.002402,0.021704,1.051830e-04,7.420000e+09,0.593946,2.720000e+09,0.671572,0.362928,0.114698,0.641826,0.459059,0.624217,0.314383,0.029840,0,0.817797,0.001010,0.625384,0.603415,0.841846,0.279975,0.026904,0.565645,0.028519
2,No,0.584897,0.631433,0.617057,0.610567,0.609954,0.999079,0.797542,0.809422,0.303560,0.781684,1.520620e-04,4.620000e+09,0.477995,0.000000,0.248203,0.186928,0.186928,0.186928,0.244020,0.334123,0.055598,0.125886,0.202305,0.022124,0.848081,0.689454,0.689454,0.217601,9.170000e+08,0.000524,0.264255,0.403068,0.013770,0.011747,0.630615,0.003319,0.078635,0.921365,0.006838,0.369637,0.005945,0.125898,0.201365,0.398379,0.313343,0.002061,0.003067,3.976230e-04,1.409355e-03,0.055000,0.022699,0.400896,0.002025,0.831848,0.478858,0.526841,0.187792,0.012113,0.013740,0.072207,0.383311,0.277090,0.004631,0.853168,0.736503,0.328779,0.000000,0.948985,0.002417,0.047048,6.640000e+07,6.480000e+09,0.593946,7.440000e+09,0.671592,0.098180,0.110933,0.706713,0.479430,0.675930,0.322690,0.021286,0,0.847518,0.001218,0.623886,0.610563,0.843304,0.277186,0.026792,0.565161,0.048876
3,Yes,0.436942,0.490951,0.482413,0.607987,0.607951,0.998921,0.797265,0.809187,0.303408,0.781435,2.785683e-04,2.410000e+09,0.459603,0.000270,0.000000,0.154903,0.154903,0.154903,0.189279,0.309118,0.043726,0.087045,0.151842,0.022065,0.847916,0.689611,0.689610,0.217617,5.310000e+08,0.000376,0.265263,0.354253,0.006719,0.003789,0.630033,0.029799,0.227318,0.772682,0.006580,0.393783,0.007494,0.087034,0.150818,0.431712,0.133433,0.000532,0.011896,4.530000e+09,1.865523e-03,0.064677,0.025736,0.388503,0.001596,0.776263,0.574318,0.838038,0.028922,0.004466,0.000667,0.230077,0.335447,0.278505,0.006173,0.972187,0.736433,0.351943,0.000000,0.920257,0.002143,0.055727,2.297914e-04,1.593711e-04,0.593933,2.170000e+09,0.671549,0.035988,0.110933,0.603615,0.454822,0.526707,0.299014,0.042961,0,0.767650,0.000978,0.623608,0.607985,0.834479,0.296390,0.026615,0.564153,0.014691
4,No,0.506898,0.565526,0.561754,0.608693,0.608693,0.999103,0.797538,0.809447,0.303503,0.781699,1.076576e-04,0.000000e+00,0.464343,0.000638,0.061848,0.182167,0.182167,0.182167,0.227853,0.323336,0.022490,0.110170,0.182345,0.022123,0.848064,0.689536,0.689536,0.217605,8.900000e+09,0.000472,0.264305,0.381403,0.005856,0.004755,0.632175,0.014674,0.182695,0.817305,0.005102,0.384317,0.005366,0.109694,0.181389,0.398743,0.071964,0.000722,0.008766,2.361663e-04,6.960000e+09,0.027581,0.010452,0.396904,0.021827,0.749491,0.250554,0.262240,0.021855,0.005487,0.001388,0.083288,0.344531,0.273814,0.001311,0.428413,0.731808,0.331901,0.039702,0.935565,0.002430,0.012348,1.633962e-04,1.617848e-04,0.593913,3.760000e+09,0.671585,0.529594,0.136805,0.652108,0.460562,0.587414,0.316791,0.049027,0,0.810394,0.003965,0.620144,0.608693,0.841780,0.285421,0.027121,0.566357,0.019245

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Bankrupt,category,0.0,0.0,2.0,"No, Yes"
1,ROA_C_Before_Interest_Depreciation,float64,0.0,0.0,3333.0,"0.4901, 0.5165, 0.4992, 0.5138, 0.5019, 0.4804, 0.5146, 0.4841, 0.4951, 0.5061"
2,ROA_A_Before_Interest_After_Tax,float64,0.0,0.0,3151.0,"0.5597, 0.5683, 0.5579, 0.5631, 0.566, 0.5589, 0.5542, 0.5613, 0.5806, 0.5511"
3,ROA_B_Before_Interest_Depreciation_After_Tax,float64,0.0,0.0,3160.0,"0.5515, 0.5525, 0.5582, 0.5388, 0.5523, 0.554, 0.5405, 0.5436, 0.5434, 0.5507"
4,Operating_Gross_Margin,float64,0.0,0.0,3781.0,"0.599, 0.6065, 0.602, 0.6058, 0.6009, 0.6083, 0.6044, 0.5992, 0.6052, 0.5982"
5,Realized_Sales_Gross_Margin,float64,0.0,0.0,3788.0,"0.6026, 0.6058, 0.6047, 0.6003, 0.6027, 0.607, 0.6065, 0.599, 0.607, 0.5982"
6,Operating_Profit_Rate,float64,0.0,0.0,3376.0,"0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999"
7,PreTax_Net_Interest_Rate,float64,0.0,0.0,3789.0,"0.7974, 0.7974, 0.7974, 0.7974, 0.7974, 0.7974, 0.7975, 0.7974, 0.7975, 0.7975"
8,AfterTax_Net_Interest_Rate,float64,0.0,0.0,3604.0,"0.8093, 0.8094, 0.8093, 0.8093, 0.8093, 0.8093, 0.8093, 0.8093, 0.8093, 0.8094"
9,NonIndustry_Income_Expenditure_Revenue,float64,0.0,0.0,2551.0,"0.3035, 0.3035, 0.3035, 0.3035, 0.3035, 0.3035, 0.3035, 0.3035, 0.3035, 0.3035"
10,Continuous_Interest_Rate_After_Tax,float64,0.0,0.0,3617.0,"0.7817, 0.7816, 0.7816, 0.7816, 0.7816, 0.7816, 0.7816, 0.7816, 0.7817, 0.7816"
11,Operating_Expense_Rate,float64,0.0,0.0,2966.0,"0.0002, 9860000000.0, 5530000000.0, 0.0001, 5450000000.0, 8480000000.0, 0.0001, 8400000000.0, 0.0002, 8950000000.0"
12,R&D_Expense_Rate,float64,0.0,0.0,1536.0,"0.0, 441000000.0, 645000000.0, 815000000.0, 458000000.0, 323000000.0, 1140000000.0, 968000000.0, 543000000.0, 1410000000.0"
13,Cash_Flow_Rate,float64,0.0,0.0,5557.0,"0.4606, 0.4644, 0.461, 0.4625, 0.4611, 0.4601, 0.4639, 0.4621, 0.4603, 0.4627"
14,InterestBearing_Debt_Interest_Rate,float64,0.0,0.0,1080.0,"0.0, 0.0003, 0.0003, 0.0002, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0002"
15,Tax_Rate_A,float64,0.0,0.0,2488.0,"0.0, 0.2531, 0.0004, 0.1138, 0.2527, 0.0859, 0.245, 0.0638, 0.2261, 0.211"
16,Net_Value_Per_Share_B,float64,0.0,0.0,2278.0,"0.177, 0.1755, 0.1846, 0.1746, 0.1732, 0.1806, 0.1801, 0.1752, 0.1809, 0.1829"
17,Net_Value_Per_Share_A,float64,0.0,0.0,2285.0,"0.177, 0.1755, 0.1846, 0.1746, 0.1809, 0.1788, 0.1829, 0.1801, 0.1753, 0.1811"
18,Net_Value_Per_Share_C,float64,0.0,0.0,2284.0,"0.177, 0.1746, 0.1755, 0.1846, 0.1809, 0.1806, 0.1811, 0.1732, 0.1771, 0.1752"
19,Persistent_EPS_Last_4_Seasons,float64,0.0,0.0,1358.0,"0.2149, 0.2182, 0.2146, 0.2187, 0.2186, 0.219, 0.2201, 0.2185, 0.2251, 0.2192"
20,Cash_Flow_Per_Share,float64,0.0,0.0,1545.0,"0.3192, 0.3205, 0.3226, 0.3213, 0.3198, 0.3178, 0.3215, 0.3212, 0.3193, 0.3204"
21,Revenue_Per_Share,float64,0.0,0.0,3807.0,"0.0178, 0.017, 0.0312, 0.0232, 0.0205, 0.0097, 0.0113, 0.0359, 0.0155, 0.0116"
22,Operating_Profit_Per_Share,float64,0.0,0.0,1236.0,"0.0971, 0.0993, 0.0977, 0.0995, 0.0976, 0.0994, 0.1008, 0.1027, 0.097, 0.0984"
23,Net_Profit_Before_Tax_Per_Share,float64,0.0,0.0,1522.0,"0.1701, 0.17, 0.1742, 0.1747, 0.1737, 0.1709, 0.1759, 0.1717, 0.1704, 0.1703"
24,Realized_Sales_Gross_Profit_Growth_Rate,float64,0.0,0.0,5583.0,"0.0221, 0.0221, 0.0221, 0.0221, 0.0221, 0.0221, 0.0221, 0.0221, 0.0221, 0.0221"
25,Operating_Profit_Growth_Rate,float64,0.0,0.0,6249.0,"0.8481, 0.848, 0.848, 0.848, 0.848, 0.848, 0.848, 0.848, 0.848, 0.8481"
26,AfterTax_Net_Profit_Growth_Rate,float64,0.0,0.0,6246.0,"0.6895, 0.6897, 0.6894, 0.6894, 0.6894, 0.6896, 0.6895, 0.6893, 0.6893, 0.6895"
27,Regular_Net_Profit_Growth_Rate,float64,0.0,0.0,6253.0,"0.6894, 0.6893, 0.6893, 0.6895, 0.6893, 0.6894, 0.6897, 0.6896, 0.6893, 0.6894"
28,Continuous_Net_Profit_Growth_Rate,float64,0.0,0.0,6270.0,"0.2176, 0.2176, 0.2176, 0.2176, 0.2176, 0.2176, 0.2176, 0.2176, 0.2176, 0.2176"
29,Total_Asset_Growth_Rate,float64,0.0,0.0,1751.0,"6370000000.0, 6400000000.0, 6470000000.0, 6440000000.0, 6300000000.0, 6890000000.0, 6430000000.0, 6520000000.0, 6900000000.0, 6610000000.0"
30,Net_Value_Growth_Rate,float64,0.0,0.0,4502.0,"0.0004, 0.0004, 0.0005, 0.0005, 0.0004, 0.0004, 0.0004, 0.0004, 0.0005, 0.0005"
31,Total_Asset_Return_Growth_Rate,float64,0.0,0.0,2903.0,"0.264, 0.2641, 0.2639, 0.2641, 0.2641, 0.264, 0.2641, 0.2639, 0.2639, 0.2641"
32,Cash_Reinvestment_Percent,float64,0.0,0.0,3599.0,"0.3759, 0.3754, 0.3765, 0.3866, 0.3823, 0.3803, 0.3765, 0.3794, 0.3849, 0.3789"
33,Current_Ratio,float64,0.0,0.0,6132.0,"0.0092, 0.0061, 0.0069, 0.0121, 0.0071, 0.0071, 0.0059, 0.0132, 0.0091, 0.0075"
34,Quick_Ratio,float64,0.0,0.0,6094.0,"0.0054, 0.0109, 0.0072, 0.0069, 0.0021, 0.0096, 0.0069, 0.006, 0.0055, 0.0062"
35,Interest_Expense_Ratio,float64,0.0,0.0,3794.0,"0.6306, 0.6306, 0.6306, 0.6306, 0.6306, 0.6306, 0.6306, 0.6306, 0.6306, 0.6306"
36,Total_Debt_to_Net_Worth,float64,0.0,0.0,5518.0,"0.0032, 0.0034, 0.0015, 0.0011, 0.0014, 0.0092, 0.0044, 0.0025, 0.0011, 0.007"
37,Debt_Ratio_Percent,float64,0.0,0.0,4208.0,"0.1402, 0.1155, 0.1195, 0.1234, 0.1282, 0.0892, 0.1129, 0.1067, 0.0926, 0.103"
38,Net_Worth_to_Assets,float64,0.0,0.0,4208.0,"0.8598, 0.8845, 0.8805, 0.8766, 0.8718, 0.9108, 0.8871, 0.8933, 0.9074, 0.897"
39,LongTerm_Fund_Suitability_Ratio_A,float64,0.0,0.0,6523.0,"0.0047, 0.0053, 0.0054, 0.0051, 0.0053, 0.0051, 0.0055, 0.0054, 0.0051, 0.0051"
40,Borrowing_Dependency,float64,0.0,0.0,4338.0,"0.3696, 0.3696, 0.3696, 0.3697, 0.3697, 0.3706, 0.3697, 0.3707, 0.3698, 0.3716"
41,Contingent_Liabilities_to_Net_Worth,float64,0.0,0.0,1855.0,"0.0054, 0.0056, 0.0055, 0.0054, 0.0057, 0.0055, 0.0054, 0.0055, 0.0058, 0.0056"
42,Operating_Profit_to_PaidIn_Capital,float64,0.0,0.0,4423.0,"0.0979, 0.1032, 0.0993, 0.0994, 0.0984, 0.1097, 0.1132, 0.0995, 0.1048, 0.0951"
43,Net_Profit_Before_Tax_to_PaidIn_Capital,float64,0.0,0.0,4785.0,"0.1784, 0.169, 0.1706, 0.1794, 0.1801, 0.1728, 0.1694, 0.1714, 0.1828, 0.1718"
44,Inventory_Accounts_Receivable_to_Net_Value,float64,0.0,0.0,5289.0,"0.3937, 0.3963, 0.4002, 0.3951, 0.399, 0.3961, 0.3988, 0.3998, 0.3973, 0.4016"
45,Total_Asset_Turnover,float64,0.0,0.0,381.0,"0.0795, 0.1034, 0.093, 0.072, 0.1064, 0.1139, 0.1259, 0.1004, 0.099, 0.1079"
46,Accounts_Receivable_Turnover,float64,0.0,0.0,1593.0,"0.0008, 0.0007, 0.0007, 0.0006, 0.0007, 0.0007, 0.0009, 0.0006, 0.0007, 0.0009"
47,Average_Collection_Days,float64,0.0,0.0,5451.0,"0.0, 0.0076, 0.0078, 0.0073, 0.005, 0.0044, 0.0067, 0.0059, 0.0093, 0.0051"
48,Inventory_Turnover_Rate,float64,0.0,0.0,2397.0,"19100000.0, 812000000.0, 8100000000.0, 8500000000.0, 8460000000.0, 8370000000.0, 5690000000.0, 6190000000.0, 0.0001, 8750000000.0"
49,Fixed_Assets_Turnover_Frequency,float64,0.0,0.0,2451.0,"0.0001, 0.0001, 9380000000.0, 8470000000.0, 469000000.0, 6280000000.0, 787000000.0, 9680000000.0, 0.0001, 0.0001"
50,Net_Worth_Turnover_Rate,float64,0.0,0.0,741.0,"0.0284, 0.0261, 0.0216, 0.0265, 0.0224, 0.0245, 0.0252, 0.0281, 0.0215, 0.0185"
51,Revenue_Per_Person,float64,0.0,0.0,5667.0,"0.0136, 0.0238, 0.0087, 0.0076, 0.0082, 0.0083, 0.0157, 0.0091, 0.0074, 0.0065"
52,Operating_Profit_Per_Person,float64,0.0,0.0,3023.0,"0.3945, 0.3932, 0.3952, 0.3923, 0.3949, 0.394, 0.3945, 0.3938, 0.3968, 0.3943"
53,Allocation_Rate_Per_Person,float64,0.0,0.0,6768.0,"0.0, 0.0064, 0.0005, 0.0264, 0.0034, 0.0024, 0.005, 0.0077, 0.0074, 0.0002"
54,Working_Capital_to_Total_Assets,float64,0.0,0.0,6819.0,"0.8603, 0.7871, 0.8093, 0.7989, 0.8128, 0.8018, 0.7174, 0.8044, 0.7222, 0.8084"
55,Quick_Assets_to_Total_Assets,float64,0.0,0.0,6819.0,"0.5408, 0.1857, 0.3843, 0.225, 0.4257, 0.5586, 0.0777, 0.0536, 0.1139, 0.4047"
56,Current_Assets_to_Total_Assets,float64,0.0,0.0,6819.0,"0.6438, 0.2041, 0.5565, 0.2444, 0.4488, 0.7081, 0.0806, 0.384, 0.1188, 0.5609"
57,Cash_to_Total_Assets,float64,0.0,0.0,6819.0,"0.188, 0.0469, 0.049, 0.0424, 0.0349, 0.0782, 0.0264, 0.0145, 0.0077, 0.07"
58,Quick_Assets_to_Current_Liability,float64,0.0,0.0,6819.0,"0.013, 0.0148, 0.0065, 0.0185, 0.0112, 0.0062, 0.0023, 0.0017, 0.003, 0.0067"
59,Cash_to_Current_Liability,float64,0.0,0.0,6816.0,"8870000000.0, 7510000000.0, 4610000000.0, 0.0022, 0.0119, 0.0171, 0.0106, 0.0025, 0.0025, 0.0058"
60,Current_Liability_to_Assets,float64,0.0,0.0,6819.0,"0.0762, 0.0233, 0.1066, 0.0224, 0.0696, 0.1616, 0.0635, 0.0591, 0.0698, 0.109"
61,Operating_Funds_to_Liability,float64,0.0,0.0,6819.0,"0.3575, 0.3576, 0.3548, 0.3675, 0.3353, 0.3439, 0.3567, 0.3092, 0.3413, 0.3471"
62,Inventory_to_Working_Capital,float64,0.0,0.0,6593.0,"0.277, 0.2771, 0.2774, 0.2773, 0.2775, 0.2771, 0.2775, 0.277, 0.2783, 0.2772"
63,Inventory_to_Current_Liability,float64,0.0,0.0,6590.0,"0.0, 8790000000.0, 5070000000.0, 5280000000.0, 0.0131, 0.0055, 0.1382, 0.0021, 0.0105, 0.0039"
64,Current_Liabilities_to_Liability,float64,0.0,0.0,6627.0,"1.0, 0.6425, 0.6805, 0.6019, 0.6449, 0.9892, 0.9835, 0.8383, 0.8471, 0.9665"
65,Working_Capital_to_Equity,float64,0.0,0.0,6819.0,"0.738, 0.7337, 0.7362, 0.7343, 0.7357, 0.7369, 0.7299, 0.7353, 0.7294, 0.7366"
66,Current_Liabilities_to_Equity,float64,0.0,0.0,6819.0,"0.3289, 0.3269, 0.3312, 0.3269, 0.3289, 0.3362, 0.3286, 0.3285, 0.3301, 0.3319"
67,LongTerm_Liability_to_Current_Assets,float64,0.0,0.0,4249.0,"0.0, 579000000.0, 279000000.0, 0.0076, 0.0069, 0.0062, 0.0176, 0.0403, 0.0233, 0.0082"
68,Retained_Earnings_to_Total_Assets,float64,0.0,0.0,6819.0,"0.9694, 0.9222, 0.9465, 0.9323, 0.8809, 0.9357, 0.9495, 0.9322, 0.93, 0.9368"
69,Total_Income_to_Total_Expense,float64,0.0,0.0,6819.0,"0.0026, 0.0021, 0.0024, 0.0022, 0.002, 0.0024, 0.0024, 0.0022, 0.0022, 0.0023"
70,Total_Expense_to_Assets,float64,0.0,0.0,6819.0,"0.0221, 0.0298, 0.0217, 0.0199, 0.0425, 0.0171, 0.0296, 0.0061, 0.0254, 0.0222"
71,Current_Asset_Turnover_Rate,float64,0.0,0.0,6261.0,"8580000000.0, 9660000000.0, 9980000000.0, 9950000000.0, 9470000000.0, 8470000000.0, 7320000000.0, 7410000000.0, 9720000000.0, 8730000000.0"
72,Quick_Asset_Turnover_Rate,float64,0.0,0.0,5377.0,"6460000000.0, 8590000000.0, 9590000000.0, 9160000000.0, 9910000000.0, 6440000000.0, 5830000000.0, 8480000000.0, 7580000000.0, 9070000000.0"
73,Working_Capital_Turnover_Rate,float64,0.0,0.0,6819.0,"0.594, 0.594, 0.5939, 0.594, 0.5941, 0.5939, 0.5939, 0.5941, 0.5939, 0.594"
74,Cash_Turnover_Rate,float64,0.0,0.0,4023.0,"1940000000.0, 3020000000.0, 1930000000.0, 2060000000.0, 1750000000.0, 1250000000.0, 2110000000.0, 2870000000.0, 1220000000.0, 5450000000.0"
75,Cash_Flow_to_Sales,float64,0.0,0.0,6819.0,"0.6716, 0.6716, 0.6716, 0.6715, 0.6715, 0.6716, 0.6716, 0.6716, 0.6716, 0.6716"
76,Fixed_Assets_to_Assets,float64,0.0,0.0,6814.0,"0.0, 0.024, 0.0681, 0.5106, 0.068, 0.2242, 0.1423, 0.5628, 0.0925, 0.1349"
77,Equity_to_LongTerm_Liability,float64,0.0,0.0,4251.0,"0.1109, 0.1174, 0.1176, 0.1186, 0.1163, 0.1313, 0.1278, 0.1117, 0.111, 0.1166"
78,Cash_Flow_to_Total_Assets,float64,0.0,0.0,6819.0,"0.6387, 0.6429, 0.6418, 0.607, 0.6199, 0.6444, 0.6416, 0.6425, 0.6384, 0.6604"
79,Cash_Flow_to_Liability,float64,0.0,0.0,6819.0,"0.4579, 0.4593, 0.4591, 0.4391, 0.4532, 0.4595, 0.4589, 0.4592, 0.4585, 0.4623"
80,CFO_to_Assets,float64,0.0,0.0,6819.0,"0.607, 0.5902, 0.6242, 0.6039, 0.5481, 0.5826, 0.6141, 0.4615, 0.5679, 0.5953"
81,Cash_Flow_to_Equity,float64,0.0,0.0,6819.0,"0.314, 0.3146, 0.3144, 0.3106, 0.3114, 0.3149, 0.3144, 0.3145, 0.3137, 0.3178"
82,Current_Liability_to_Current_Assets,float64,0.0,0.0,6819.0,"0.0184, 0.0175, 0.0298, 0.0141, 0.0241, 0.0356, 0.1156, 0.0239, 0.0883, 0.0303"
83,Net_Income_to_Total_Assets,float64,0.0,0.0,6819.0,"0.8497, 0.7653, 0.8178, 0.7939, 0.7293, 0.809, 0.817, 0.7963, 0.7903, 0.8088"
84,Total_Assets_to_GNP_Price,float64,0.0,0.0,6818.0,"0.0037, 0.0006, 0.0001, 0.0025, 0.0006, 0.0045, 0.001, 0.0007, 0.0007, 0.0027"
85,NoCredit_Interval,float64,0.0,0.0,6819.0,"0.6241, 0.6263, 0.6254, 0.6201, 0.6317, 0.6238, 0.6236, 0.6142, 0.6236, 0.6238"
86,Gross_Profit_to_Sales,float64,0.0,0.0,6816.0,"0.6651, 0.6085, 0.6258, 0.5854, 0.6301, 0.6107, 0.6051, 0.6174, 0.6146, 0.6086"
87,Net_Income_to_Stockholders_Equity,float64,0.0,0.0,6819.0,"0.8434, 0.8384, 0.8418, 0.8399, 0.8355, 0.8415, 0.8415, 0.8401, 0.8395, 0.8412"
88,Liability_to_Equity,float64,0.0,0.0,6819.0,"0.2771, 0.2759, 0.28, 0.2759, 0.2779, 0.2838, 0.2779, 0.2782, 0.2822, 0.2813"
89,DFL,float64,0.0,0.0,6240.0,"0.0268, 0.0269, 0.0269, 0.0269, 0.0268, 0.0268, 0.027, 0.0268, 0.0269, 0.0268"
90,Interest_Coverage_Ratio,float64,0.0,0.0,6240.0,"0.5652, 0.5655, 0.5657, 0.5654, 0.565, 0.5652, 0.5659, 0.5651, 0.5657, 0.5653"
91,Equity_to_Liability,float64,0.0,0.0,6819.0,"0.0506, 0.0874, 0.0285, 0.0905, 0.0404, 0.0209, 0.0406, 0.0381, 0.0231, 0.025"
92,Liability_Assets_Flag,int64,0.0,0.0,2.0,"0, 1"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
ROA_C_Before_Interest_Depreciation,6819.0,5.051796e-01,6.068564e-02,0.0,1.000000e+00
ROA_A_Before_Interest_After_Tax,6819.0,5.586249e-01,6.562003e-02,0.0,1.000000e+00
ROA_B_Before_Interest_Depreciation_After_Tax,6819.0,5.535887e-01,6.159481e-02,0.0,1.000000e+00
Operating_Gross_Margin,6819.0,6.079480e-01,1.693381e-02,0.0,1.000000e+00
Realized_Sales_Gross_Margin,6819.0,6.079295e-01,1.691607e-02,0.0,1.000000e+00
Operating_Profit_Rate,6819.0,9.987551e-01,1.301003e-02,0.0,1.000000e+00
PreTax_Net_Interest_Rate,6819.0,7.971898e-01,1.286899e-02,0.0,1.000000e+00
AfterTax_Net_Interest_Rate,6819.0,8.090836e-01,1.360065e-02,0.0,1.000000e+00
NonIndustry_Income_Expenditure_Revenue,6819.0,3.036229e-01,1.116344e-02,0.0,1.000000e+00
Continuous_Interest_Rate_After_Tax,6819.0,7.813814e-01,1.267900e-02,0.0,1.000000e+00
Operating_Expense_Rate,6819.0,1.995347e+09,3.237684e+09,0.0,9.990000e+09
R&D_Expense_Rate,6819.0,1.950427e+09,2.598292e+09,0.0,9.980000e+09
Cash_Flow_Rate,6819.0,4.674312e-01,1.703552e-02,0.0,1.000000e+00
InterestBearing_Debt_Interest_Rate,6819.0,1.644801e+07,1.082750e+08,0.0,9.900000e+08
Tax_Rate_A,6819.0,1.150007e-01,1.386675e-01,0.0,1.000000e+00
Net_Value_Per_Share_B,6819.0,1.906606e-01,3.338977e-02,0.0,1.000000e+00
Net_Value_Per_Share_A,6819.0,1.906332e-01,3.347351e-02,0.0,1.000000e+00
Net_Value_Per_Share_C,6819.0,1.906724e-01,3.348014e-02,0.0,1.000000e+00
Persistent_EPS_Last_4_Seasons,6819.0,2.288129e-01,3.326261e-02,0.0,1.000000e+00
Cash_Flow_Per_Share,6819.0,3.234819e-01,1.761091e-02,0.0,1.000000e+00
Revenue_Per_Share,6819.0,1.328641e+06,5.170709e+07,0.0,3.020000e+09
Operating_Profit_Per_Share,6819.0,1.090907e-01,2.794224e-02,0.0,1.000000e+00
Net_Profit_Before_Tax_Per_Share,6819.0,1.843606e-01,3.318021e-02,0.0,1.000000e+00
Realized_Sales_Gross_Profit_Growth_Rate,6819.0,2.240785e-02,1.207927e-02,0.0,1.000000e+00
Operating_Profit_Growth_Rate,6819.0,8.479800e-01,1.075248e-02,0.0,1.000000e+00
AfterTax_Net_Profit_Growth_Rate,6819.0,6.891461e-01,1.385302e-02,0.0,1.000000e+00
Regular_Net_Profit_Growth_Rate,6819.0,6.891500e-01,1.391028e-02,0.0,1.000000e+00
Continuous_Net_Profit_Growth_Rate,6819.0,2.176390e-01,1.006296e-02,0.0,1.000000e+00
Total_Asset_Growth_Rate,6819.0,5.508097e+09,2.897718e+09,0.0,9.990000e+09
Net_Value_Growth_Rate,6819.0,1.566212e+06,1.141594e+08,0.0,9.330000e+09
Total_Asset_Return_Growth_Rate,6819.0,2.642475e-01,9.634209e-03,0.0,1.000000e+00
Cash_Reinvestment_Percent,6819.0,3.796767e-01,2.073657e-02,0.0,1.000000e+00
Current_Ratio,6819.0,4.032850e+05,3.330216e+07,0.0,2.750000e+09
Quick_Ratio,6819.0,8.376595e+06,2.446847e+08,0.0,9.230000e+09
Interest_Expense_Ratio,6819.0,6.309910e-01,1.123846e-02,0.0,1.000000e+00
Total_Debt_to_Net_Worth,6819.0,4.416337e+06,1.684069e+08,0.0,9.940000e+09
Debt_Ratio_Percent,6819.0,1.131771e-01,5.392031e-02,0.0,1.000000e+00
Net_Worth_to_Assets,6819.0,8.868229e-01,5.392031e-02,0.0,1.000000e+00
LongTerm_Fund_Suitability_Ratio_A,6819.0,8.782734e-03,2.815293e-02,0.0,1.000000e+00
Borrowing_Dependency,6819.0,3.746543e-01,1.628616e-02,0.0,1.000000e+00
Contingent_Liabilities_to_Net_Worth,6819.0,5.968277e-03,1.218836e-02,0.0,1.000000e+00
Operating_Profit_to_PaidIn_Capital,6819.0,1.089767e-01,2.778169e-02,0.0,1.000000e+00
Net_Profit_Before_Tax_to_PaidIn_Capital,6819.0,1.827150e-01,3.078477e-02,0.0,1.000000e+00
Inventory_Accounts_Receivable_to_Net_Value,6819.0,4.024593e-01,1.332408e-02,0.0,1.000000e+00
Total_Asset_Turnover,6819.0,1.416056e-01,1.011450e-01,0.0,1.000000e+00
Accounts_Receivable_Turnover,6819.0,1.278971e+07,2.782598e+08,0.0,9.740000e+09
Average_Collection_Days,6819.0,9.826221e+06,2.563589e+08,0.0,9.730000e+09
Inventory_Turnover_Rate,6819.0,2.149106e+09,3.247967e+09,0.0,9.990000e+09
Fixed_Assets_Turnover_Frequency,6819.0,1.008596e+09,2.477557e+09,0.0,9.990000e+09
Net_Worth_Turnover_Rate,6819.0,3.859505e-02,3.668034e-02,0.0,1.000000e+00
Revenue_Per_Person,6819.0,2.325854e+06,1.366327e+08,0.0,8.810000e+09
Operating_Profit_Per_Person,6819.0,4.006710e-01,3.272014e-02,0.0,1.000000e+00
Allocation_Rate_Per_Person,6819.0,1.125579e+07,2.945063e+08,0.0,9.570000e+09
Working_Capital_to_Total_Assets,6819.0,8.141252e-01,5.905440e-02,0.0,1.000000e+00
Quick_Assets_to_Total_Assets,6819.0,4.001318e-01,2.019981e-01,0.0,1.000000e+00
Current_Assets_to_Total_Assets,6819.0,5.222734e-01,2.181118e-01,0.0,1.000000e+00
Cash_to_Total_Assets,6819.0,1.240946e-01,1.392506e-01,0.0,1.000000e+00
Quick_Assets_to_Current_Liability,6819.0,3.592902e+06,1.716209e+08,0.0,8.820000e+09
Cash_to_Current_Liability,6819.0,3.715999e+07,5.103509e+08,0.0,9.650000e+09
Current_Liability_to_Assets,6819.0,9.067279e-02,5.028986e-02,0.0,1.000000e+00
Operating_Funds_to_Liability,6819.0,3.538280e-01,3.514718e-02,0.0,1.000000e+00
Inventory_to_Working_Capital,6819.0,2.773951e-01,1.046885e-02,0.0,1.000000e+00
Inventory_to_Current_Liability,6819.0,5.580680e+07,5.820516e+08,0.0,9.910000e+09
Current_Liabilities_to_Liability,6819.0,7.615989e-01,2.066768e-01,0.0,1.000000e+00
Working_Capital_to_Equity,6819.0,7.358165e-01,1.167803e-02,0.0,1.000000e+00
Current_Liabilities_to_Equity,6819.0,3.314098e-01,1.348803e-02,0.0,1.000000e+00
LongTerm_Liability_to_Current_Assets,6819.0,5.416004e+07,5.702706e+08,0.0,9.540000e+09
Retained_Earnings_to_Total_Assets,6819.0,9.347328e-01,2.556422e-02,0.0,1.000000e+00
Total_Income_to_Total_Expense,6819.0,2.548946e-03,1.209281e-02,0.0,1.000000e+00
Total_Expense_to_Assets,6819.0,2.918410e-02,2.714878e-02,0.0,1.000000e+00
Current_Asset_Turnover_Rate,6819.0,1.195856e+09,2.821161e+09,0.0,1.000000e+10
Quick_Asset_Turnover_Rate,6819.0,2.163735e+09,3.374944e+09,0.0,1.000000e+10
Working_Capital_Turnover_Rate,6819.0,5.940063e-01,8.959384e-03,0.0,1.000000e+00
Cash_Turnover_Rate,6819.0,2.471977e+09,2.938623e+09,0.0,1.000000e+10
Cash_Flow_to_Sales,6819.0,6.715308e-01,9.341346e-03,0.0,1.000000e+00
Fixed_Assets_to_Assets,6819.0,1.220121e+06,1.007542e+08,0.0,8.320000e+09
Equity_to_LongTerm_Liability,6819.0,1.156447e-01,1.952918e-02,0.0,1.000000e+00
Cash_Flow_to_Total_Assets,6819.0,6.497306e-01,4.737213e-02,0.0,1.000000e+00
Cash_Flow_to_Liability,6819.0,4.618493e-01,2.994268e-02,0.0,1.000000e+00
CFO_to_Assets,6819.0,5.934151e-01,5.856055e-02,0.0,1.000000e+00
Cash_Flow_to_Equity,6819.0,3.155824e-01,1.296089e-02,0.0,1.000000e+00
Current_Liability_to_Current_Assets,6819.0,3.150637e-02,3.084469e-02,0.0,1.000000e+00
Liability_Assets_Flag,6819.0,1.173193e-03,3.423431e-02,0.0,1.000000e+00
Net_Income_to_Total_Assets,6819.0,8.077602e-01,4.033219e-02,0.0,1.000000e+00
Total_Assets_to_GNP_Price,6819.0,1.862942e+07,3.764501e+08,0.0,9.820000e+09
NoCredit_Interval,6819.0,6.239146e-01,1.228955e-02,0.0,1.000000e+00
Gross_Profit_to_Sales,6819.0,6.079463e-01,1.693381e-02,0.0,1.000000e+00
Net_Income_to_Stockholders_Equity,6819.0,8.404021e-01,1.452253e-02,0.0,1.000000e+00
Liability_to_Equity,6819.0,2.803652e-01,1.446322e-02,0.0,1.000000e+00
DFL,6819.0,2.754112e-02,1.566794e-02,0.0,1.000000e+00
Interest_Coverage_Ratio,6819.0,5.653579e-01,1.321424e-02,0.0,1.000000e+00
Equity_to_Liability,6819.0,4.757836e-02,5.001372e-02,0.0,1.000000e+00

In [7]:
# Categorical Feature Statistics
cat_stats

              value  count    pct
column   rank
Bankrupt 1       No   6599  96.77
         2      Yes    220   3.23

In [8]:
# Target Distribution
target_df

          count    pct
Bankrupt
No         6599  96.77
Yes         220   3.23

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to taiwanese_bankruptcy_prediction/019d5d97-a099-74fa-a2ca-48f596397dfa
019d5d97-a099-74fa-a2ca-48f596397dfa
4677ce7616fa453a4116ebdd9832515808185def935cebb8eec64edb6e31628f