### Dataset and Task Metadata

In [ ]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="polish_companies_bankruptcy",
    dataset_year="2010",
    domain_str="finance",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C5F600",
    download_description="""
We download the data from the UCI repository and uzip it to a predefined folder.

mkdir -p local-data-warehouse/polish_companies_bankruptcy/ && wget -P local-data-warehouse/polish_companies_bankruptcy/ https://archive.ics.uci.edu/static/public/365/polish+companies+bankruptcy+data.zip && unzip local-data-warehouse/polish_companies_bankruptcy/polish+companies+bankruptcy+data.zip -d local-data-warehouse/polish_companies_bankruptcy/ && rm local-data-warehouse/polish_companies_bankruptcy/polish+companies+bankruptcy+data.zip
""",
    # References
    academic_reference_bibtex="""@article{Ziba2016EnsembleBT,
  title={Ensemble boosted trees with synthetic features generation in application to bankruptcy prediction},
  author={Maciej Ziȩba and Sebastian Klaudiusz Tomczak and Jakub M. Tomczak},
  journal={Expert Syst. Appl.},
  year={2016},
  volume={58},
  pages={93-101},
  url={https://api.semanticscholar.org/CorpusID:40512567}
}
""",
    academic_reference_bibtex_key="Ziba2016EnsembleBT",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
        - We only use data from year 5 (5year.arff), because it is the newest data and the target is bankruptcy status after only 1 year.
        - We created semantically meaningful feature names.
        - We removed duplicates.
        - Anomaly: the data contains a lot of features created by feature engineering.
    """,
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="company_bankrupt",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="company_bankrupt",
)

## Preprocessing

In [ ]:
import arff
import pandas as pd

with open(dataset_mold.path /"5year.arff") as f:
        data = arff.load(f)

df = pd.DataFrame(data["data"], columns=[x[0] for x in data["attributes"]])

target_feature = "company_bankrupt"
df.columns = feature_names = [
    "net_profit_to_total_assets",
    "total_liabilities_to_total_assets",
    "working_capital_to_total_assets",
    "current_assets_to_short_term_liabilities",
    "liquidity_days_ratio",
    "retained_earnings_to_total_assets",
    "ebit_to_total_assets",
    "book_value_equity_to_total_liabilities",
    "sales_to_total_assets",
    "equity_to_total_assets",
    "extended_profit_to_total_assets",
    "gross_profit_to_short_term_liabilities",
    "gross_profit_plus_depreciation_to_sales",
    "gross_profit_plus_interest_to_total_assets",
    "liabilities_days_ratio",
    "gross_profit_plus_depreciation_to_total_liabilities",
    "total_assets_to_total_liabilities",
    "gross_profit_to_total_assets",
    "gross_profit_to_sales",
    "inventory_days_ratio",
    "sales_growth_ratio",
    "operating_profit_to_total_assets",
    "net_profit_to_sales",
    "three_year_gross_profit_to_total_assets",
    "equity_minus_share_capital_to_total_assets",
    "net_profit_plus_depreciation_to_total_liabilities",
    "operating_profit_to_financial_expenses",
    "working_capital_to_fixed_assets",
    "log_total_assets",
    "net_liabilities_to_sales",
    "gross_profit_plus_interest_to_sales",
    "current_liabilities_days_ratio",
    "operating_expenses_to_short_term_liabilities",
    "operating_expenses_to_total_liabilities",
    "sales_profit_to_total_assets",
    "total_sales_to_total_assets",
    "current_assets_minus_inventories_to_long_term_liabilities",
    "constant_capital_to_total_assets",
    "sales_profit_to_sales",
    "liquid_assets_to_short_term_liabilities",
    "liabilities_to_adjusted_operating_profit",
    "operating_profit_to_sales",
    "receivables_plus_inventory_turnover_days",
    "receivables_days_ratio",
    "net_profit_to_inventory",
    "current_assets_minus_inventory_to_short_term_liabilities",
    "inventory_days_cost_ratio",
    "ebitda_to_total_assets",
    "ebitda_to_sales",
    "current_assets_to_total_liabilities",
    "short_term_liabilities_to_total_assets",
    "short_term_liabilities_days_cost_ratio",
    "equity_to_fixed_assets",
    "constant_capital_to_fixed_assets",
    "working_capital_absolute",
    "gross_margin",
    "adjusted_liquidity_ratio",
    "total_costs_to_total_sales",
    "long_term_liabilities_to_equity",
    "inventory_turnover_ratio",
    "receivables_turnover_ratio",
    "short_term_liabilities_days_ratio",
    "sales_to_short_term_liabilities",
    "sales_to_fixed_assets",
    target_feature,
]

df = df.rename(columns={"target": target_feature})
df[target_feature] = df[target_feature].map({"1": "Yes", "0": "No"}).astype("category")

# conflicting duplicates drop (without target column)
df = df.drop_duplicates(subset=[c for c in df.columns if c != task_mold.target_column_name], keep=False)
df = df.reset_index(drop=True)

Data shape: (5790, 65)

## Data Checks

In [4]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 5,790
Columns: 65
Use sampling: False (sample size: 5,790)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['liquidity_days_ratio', 'working_capital_absolute', 'liquid_assets_to_short_term_liabilities', 'gross_profit_plus_interest_to_sales', 'gross_profit_plus_depreciation_to_total_liabilities', 'liabilities_days_ratio', 'operating_expenses_to_total_liabilities', 'gross_profit_to_short_term_liabilities', 'gross_profit_to_sales', 'net_profit_plus_depreciation_to_total_liabilities']
Rows remaining as candidates after top-10 filter: 10 (of 5,790)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [5]:
# Sample Rows
df_head

,net_profit_to_total_assets,total_liabilities_to_total_assets,working_capital_to_total_assets,current_assets_to_short_term_liabilities,liquidity_days_ratio,retained_earnings_to_total_assets,ebit_to_total_assets,book_value_equity_to_total_liabilities,sales_to_total_assets,equity_to_total_assets,extended_profit_to_total_assets,gross_profit_to_short_term_liabilities,gross_profit_plus_depreciation_to_sales,gross_profit_plus_interest_to_total_assets,liabilities_days_ratio,gross_profit_plus_depreciation_to_total_liabilities,total_assets_to_total_liabilities,gross_profit_to_total_assets,gross_profit_to_sales,inventory_days_ratio,sales_growth_ratio,operating_profit_to_total_assets,net_profit_to_sales,three_year_gross_profit_to_total_assets,equity_minus_share_capital_to_total_assets,net_profit_plus_depreciation_to_total_liabilities,operating_profit_to_financial_expenses,working_capital_to_fixed_assets,log_total_assets,net_liabilities_to_sales,gross_profit_plus_interest_to_sales,current_liabilities_days_ratio,operating_expenses_to_short_term_liabilities,operating_expenses_to_total_liabilities,sales_profit_to_total_assets,total_sales_to_total_assets,current_assets_minus_inventories_to_long_term_liabilities,constant_capital_to_total_assets,sales_profit_to_sales,liquid_assets_to_short_term_liabilities,liabilities_to_adjusted_operating_profit,operating_profit_to_sales,receivables_plus_inventory_turnover_days,receivables_days_ratio,net_profit_to_inventory,current_assets_minus_inventory_to_short_term_liabilities,inventory_days_cost_ratio,ebitda_to_total_assets,ebitda_to_sales,current_assets_to_total_liabilities,short_term_liabilities_to_total_assets,short_term_liabilities_days_cost_ratio,equity_to_fixed_assets,constant_capital_to_fixed_assets,working_capital_absolute,gross_margin,adjusted_liquidity_ratio,total_costs_to_total_sales,long_term_liabilities_to_equity,inventory_turnover_ratio,receivables_turnover_ratio,short_term_liabilities_days_ratio,sales_to_short_term_liabilities,sales_to_fixed_assets,company_bankrupt
0,0.088238,0.55472,0.01134,1.0205,-66.5200,0.342040,0.109490,0.57752,1.0881,0.32036,0.109490,0.197600,0.096885,0.109490,1475.20,0.247420,1.8027,0.109490,0.077287,50.199,1.15740,0.135230,0.062287,0.41949,0.320360,0.209120,1.03870,0.026093,6.1267,0.377880,0.077287,155.330,2.3498,0.24377,0.135230,1.4493,571.3700,0.32101,0.095457,0.128790,0.111890,0.095457,127.30,77.096,0.452890,0.66883,54.621,0.107460,0.075859,1.01930,0.55407,0.42557,0.73717,0.73866,15182.0000,0.080955,0.275430,0.91905,0.002024,7.2711,4.7343,142.760,2.5568,3.2597,No
1,-0.006202,0.48465,0.23298,1.5998,6.1825,0.000000,-0.006202,1.06340,1.2757,0.51535,0.001329,-0.015967,0.037544,-0.006202,3693.40,0.098825,2.0634,-0.006202,-0.004862,59.923,1.01580,0.001289,-0.004862,NaN,0.080285,0.098825,0.17118,0.615450,4.0022,0.363810,0.000778,108.050,3.3779,2.70750,-0.036475,1.2757,5.2519,0.59380,-0.028591,0.057810,0.291670,0.001011,171.38,111.450,-0.029614,1.06060,58.258,-0.052809,-0.041395,1.28230,0.38846,0.29604,1.36140,1.56860,2341.8000,-0.028591,-0.012035,1.00470,0.152220,6.0911,3.2749,111.140,3.2841,3.3700,No
2,0.130240,0.22142,0.57751,3.6082,120.0400,0.187640,0.162120,3.05900,1.1415,0.67731,0.162120,0.732180,0.165680,0.162120,431.75,0.845390,4.5164,0.162120,0.143490,41.508,1.23620,0.145860,0.115280,0.23566,0.677310,0.701430,1.47370,2.872100,4.7622,0.050069,0.143490,81.653,4.4701,0.65878,0.145860,1.1698,NaN,0.67731,0.129100,1.319600,0.042587,0.129100,163.71,122.200,1.013700,3.02800,47.382,0.120800,0.106920,3.60820,0.22142,0.22371,3.36840,3.36840,33401.0000,0.123960,0.192290,0.87604,0.000000,8.7934,2.9870,71.531,5.1027,5.6188,No
3,-0.089951,0.88700,0.26927,1.5222,-55.9920,-0.073957,-0.089951,0.12740,1.2754,0.11300,-0.080792,-0.174450,0.084038,-0.089951,3020.50,0.120840,1.1274,-0.089951,-0.070525,47.698,1.09420,0.000000,-0.070525,NaN,0.064737,0.120840,0.00000,1.251900,4.0153,0.657790,-0.138650,253.910,1.4375,0.83567,0.014027,1.2754,1.9005,0.43830,0.010998,0.456220,0.149980,0.000000,157.30,109.600,-0.539690,1.19900,82.073,-0.197140,-0.154560,0.88491,0.51564,0.69565,0.52538,2.03780,2789.6000,0.418840,-0.796020,0.59074,2.878700,7.6524,3.3302,147.560,2.4735,5.9299,No
4,0.048179,0.55041,0.10765,1.2437,-22.9590,0.000000,0.059280,0.81682,1.5150,0.44959,0.091990,0.134190,0.055575,0.059280,2386.10,0.152970,1.8168,0.059280,0.039129,36.074,0.99455,0.067616,0.031802,0.00000,0.429200,0.132800,2.06710,0.238910,5.8823,0.363310,0.039129,140.120,2.6583,2.13360,0.364200,1.5150,6.3783,0.51225,0.240400,0.067283,0.198280,0.044632,125.21,89.134,0.321770,0.90475,46.538,0.042701,0.028186,0.99819,0.44176,0.37618,0.99779,1.13690,1.2437,0.240400,0.107160,0.77048,0.139380,10.1180,4.0950,106.430,3.4294,3.3622,No

In [6]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,company_bankrupt,category,0.0,0.00,2.0,"No, Yes"
1,current_assets_minus_inventories_to_long_term_liabilities,float64,2502.0,43.21,3225.0,"4.1023, 2.7727, 8.9029, 90.261, 2.7914, 1.7831, 0.9886, 2.4927, 4.6545, 1.6972"
2,operating_profit_to_financial_expenses,float64,389.0,6.72,4935.0,"0.0, 1.3454, 2.6295, 1.397, 1.6554, 1.2704, 3.0986, 1.502, 1.1694, 35.274"
3,net_profit_to_inventory,float64,264.0,4.56,5367.0,"0.0, 1.5193, 0.132, 0.161, 0.3805, 0.2122, 1.0567, 0.513, 0.3903, 0.6352"
4,inventory_turnover_ratio,float64,264.0,4.56,5319.0,"17.114, 5.2512, 12.364, 10.34, 12.16, 11.257, 11.045, 12.125, 4.5363, 11.79"
5,three_year_gross_profit_to_total_assets,float64,135.0,2.33,5496.0,"0.0, 0.1304, 0.735, 0.1345, 1.4774, 0.2073, 0.109, 0.3924, 0.1583, 0.21"
6,working_capital_to_fixed_assets,float64,105.0,1.81,5555.0,"1.2599, 1.0404, 0.1231, 0.4333, -0.2354, 0.2723, -0.195, 1.0307, 1.1103, 1.4399"
7,equity_to_fixed_assets,float64,105.0,1.81,5415.0,"2.2499, 1.5962, 1.0107, 1.8225, 1.3602, 1.2624, 2.3016, 1.3816, 1.2216, 1.0391"
8,constant_capital_to_fixed_assets,float64,105.0,1.81,5298.0,"2.2499, 1.0371, 1.6298, 1.1296, 1.3109, 1.07, 1.56, 1.0567, 1.3008, 2.376"
9,sales_to_fixed_assets,float64,105.0,1.81,5493.0,"2.682, 1.6959, 16.589, 6.7586, 1.8704, 4.5617, 2.8884, 4.9866, 1.834, 1.5791"
10,sales_growth_ratio,float64,103.0,1.78,4386.0,"1.121, 1.0022, 1.0233, 1.1892, 1.2387, 1.1906, 1.0536, 1.0637, 1.3353, 1.1148"
11,liabilities_to_adjusted_operating_profit,float64,84.0,1.45,5540.0,"0.0, 0.2253, 0.1093, 0.1128, 0.2925, 0.1054, 0.1518, 0.0985, 0.1682, 0.1173"
12,current_liabilities_days_ratio,float64,46.0,0.79,5458.0,"0.0, 48.78, 101.1, 62.32, 100.83, 109.97, 134.12, 116.59, 38.514, 112.12"
13,short_term_liabilities_days_cost_ratio,float64,36.0,0.62,5449.0,"0.0, 0.1571, 0.1505, 0.2474, 0.15, 0.1933, 0.1949, 0.2708, 0.3013, 0.1707"
14,inventory_days_cost_ratio,float64,35.0,0.60,5340.0,"0.0, 33.904, 140.3, 49.571, 75.935, 102.06, 111.01, 44.866, 55.368, 12.14"
15,current_assets_to_short_term_liabilities,float64,21.0,0.36,5416.0,"2.3386, 1.0472, 1.7944, 1.2851, 1.6656, 1.1534, 1.3905, 1.6422, 1.5428, 1.029"
16,gross_profit_to_short_term_liabilities,float64,21.0,0.36,5630.0,"0.465, 0.2061, 0.1001, 0.1687, 1.754, 0.3686, 0.2521, 1.014, 0.3934, 0.4745"
17,operating_expenses_to_short_term_liabilities,float64,21.0,0.36,5539.0,"0.0, 5.1719, 4.7075, 5.1785, 2.0725, 3.2695, 3.0868, 3.2406, 3.3082, 12.866"
18,liquid_assets_to_short_term_liabilities,float64,21.0,0.36,5643.0,"0.0, 1.2077, 0.3246, 0.1206, 0.1341, 0.1729, 0.2161, 0.1305, 0.4962, 0.0391"
19,current_assets_minus_inventory_to_short_term_liabilities,float64,21.0,0.36,5494.0,"1.1262, 1.0043, 1.6191, 0.3202, 1.1699, 1.0492, 1.1234, 1.0586, 1.6204, 1.3217"
20,sales_to_short_term_liabilities,float64,21.0,0.36,5523.0,"2.3307, 3.6796, 4.2731, 5.6358, 14.691, 2.1269, 2.5748, 3.3354, 4.5771, 9.0078"
21,book_value_equity_to_total_liabilities,float64,18.0,0.31,5581.0,"1.2376, 1.1634, 1.9198, 1.3062, 1.0819, 0.7327, 2.1171, 1.8245, 2.9632, 0.3363"
22,gross_profit_plus_depreciation_to_total_liabilities,float64,18.0,0.31,5642.0,"1.195, 1.0101, 0.1764, 0.3472, 0.1845, 1.3731, 0.1564, 0.2788, 0.5609, 1.0243"
23,total_assets_to_total_liabilities,float64,18.0,0.31,5398.0,"1.3363, 1.9046, 1.5508, 1.0192, 2.9198, 1.1631, 1.945, 1.5194, 1.309, 1.3152"
24,net_profit_plus_depreciation_to_total_liabilities,float64,18.0,0.31,5613.0,"0.0, 0.1939, 1.0898, 0.2509, 0.5512, 0.2482, 0.1932, 0.1185, 0.0198, 0.9301"
25,operating_expenses_to_total_liabilities,float64,18.0,0.31,5630.0,"0.0, 3.5357, 2.9149, 0.1246, 2.5904, 1.3423, 2.5308, 0.3991, 3.3595, 0.6781"
26,current_assets_to_total_liabilities,float64,18.0,0.31,5453.0,"1.0454, 1.7137, 1.1042, 1.0375, 1.0433, 1.0822, 2.9458, 1.2839, 1.2581, 1.7068"
27,receivables_turnover_ratio,float64,15.0,0.26,5555.0,"10.096, 7.2732, 9.4409, 6.7081, 5.9772, 12.352, 11.183, 13.983, 16.789, 4.3754"
28,liquidity_days_ratio,float64,11.0,0.19,5718.0,"0.0, 33.352, -66.52, -29.617, -41.151, -21.426, -57.414, 109.14, 117.49, 153.8"
29,liabilities_days_ratio,float64,6.0,0.10,5635.0,"0.0, 361.35, 305.44, 2069.4, 1302.2, 1736.9, 1313.0, 5945.1, 1888.9, 1217.8"
30,net_profit_to_total_assets,float64,3.0,0.05,5570.0,"0.0, 0.2229, 0.0462, 0.1535, 0.146, 0.1283, 0.1133, 0.2216, 0.0545, 0.0496"
31,total_liabilities_to_total_assets,float64,3.0,0.05,5566.0,"0.0, 0.172, 0.2523, 0.3425, 0.402, 0.5772, 0.6158, 1.0208, 0.3853, 0.66"
32,working_capital_to_total_assets,float64,3.0,0.05,5597.0,"1.0, 0.2003, 0.2974, 0.5322, 0.1057, 0.1957, 0.3879, 0.5797, 0.2445, 0.545"
33,retained_earnings_to_total_assets,float64,3.0,0.05,3498.0,"0.0, 0.1352, 0.1721, 0.0955, 0.3423, -0.1582, 0.1048, 0.1903, -0.0027, 0.1958"
34,ebit_to_total_assets,float64,3.0,0.05,5600.0,"0.0, 0.2443, 0.2314, 0.2044, 0.1438, 0.1589, 0.1442, 0.0033, 0.0174, 0.1622"
35,equity_to_total_assets,float64,3.0,0.05,5558.0,"1.0, 0.7477, 0.5374, 0.2406, 0.3497, 0.4229, 0.6575, 0.5197, 0.5906, 0.6292"
36,extended_profit_to_total_assets,float64,3.0,0.05,5609.0,"0.0, 0.1482, 0.1426, 0.1341, 0.0931, 0.1647, 0.115, 0.1668, 0.1053, 0.2571"
37,gross_profit_plus_interest_to_total_assets,float64,3.0,0.05,5600.0,"0.0, 0.2443, 0.2314, 0.2044, 0.1438, 0.1589, 0.1442, 0.0033, 0.0174, 0.1622"
38,gross_profit_to_total_assets,float64,3.0,0.05,5600.0,"0.0, 0.2443, 0.2314, 0.2044, 0.1438, 0.1589, 0.1442, 0.0033, 0.0174, 0.1622"
39,operating_profit_to_total_assets,float64,3.0,0.05,5096.0,"0.0, 0.1706, 0.1637, 0.1396, 0.0353, 0.1437, 0.1085, 0.2237, 0.1029, -0.3064"
40,equity_minus_share_capital_to_total_assets,float64,3.0,0.05,5609.0,"0.0, 0.3994, 0.6417, 0.5262, 0.5942, 0.5013, 0.7256, 0.6868, 0.6784, 0.7752"
41,log_total_assets,float64,3.0,0.05,5170.0,"4.1709, 4.8609, 3.8214, 3.6421, 4.225, 4.1152, 4.402, 4.2604, 3.5293, 3.4531"
42,sales_profit_to_total_assets,float64,3.0,0.05,5593.0,"0.0, 0.0, 0.1018, 0.0126, 0.1463, 0.0, -0.2423, 0.1395, 0.1042, 0.1982"
43,total_sales_to_total_assets,float64,3.0,0.05,5364.0,"1.2038, 1.3215, 1.3512, 1.1918, 1.4214, 2.0805, 1.0431, 1.5792, 1.0633, 1.1609"
44,constant_capital_to_total_assets,float64,3.0,0.05,5522.0,"1.0, 0.6602, 0.7472, 0.443, 0.8079, 0.6142, 0.4965, 0.759, 0.7477, 0.3497"
45,ebitda_to_total_assets,float64,3.0,0.05,5556.0,"0.0, -0.0038, 0.1381, 0.1462, -0.0086, -0.0171, 0.1221, -0.0071, 0.1474, 0.1018"
46,short_term_liabilities_to_total_assets,float64,3.0,0.05,5524.0,"0.0, 0.3575, 0.3019, 0.1805, 0.1642, 0.7195, 0.5035, 0.172, 0.2277, 0.2391"
47,adjusted_liquidity_ratio,float64,3.0,0.05,5519.0,"0.0, 0.1034, 0.1594, 0.3622, 0.1581, 0.1864, 0.3068, 0.1122, 0.1209, 0.3119"
48,long_term_liabilities_to_equity,float64,3.0,0.05,3220.0,"0.0, 0.2865, 0.4182, 0.1432, 0.3751, 0.0053, 0.2527, 0.0001, 0.5655, 0.0454"
49,sales_to_total_assets,float64,1.0,0.02,4782.0,"1.0277, 1.0376, 1.0117, 1.1284, 1.0008, 1.0647, 1.0335, 1.081, 1.0579, 1.0317"
50,gross_profit_plus_depreciation_to_sales,float64,0.0,0.00,5608.0,"0.0, 0.162, -0.0789, 0.1052, 0.015, 0.1338, 0.0429, 0.1677, 0.1424, 0.1099"
51,gross_profit_to_sales,float64,0.0,0.00,5620.0,"0.0, 0.0378, 0.0898, 0.1394, 0.1081, 0.0476, 0.0233, 0.2892, 0.102, 0.0672"
52,inventory_days_ratio,float64,0.0,0.00,5342.0,"0.0, 69.508, 100.19, 106.24, 86.357, 20.857, 233.31, 16.798, 35.322, 54.52"
53,net_profit_to_sales,float64,0.0,0.00,5595.0,"0.0, 0.0008, 0.1914, 0.0099, 0.04, 0.0005, 0.127, 0.1506, 0.1076, 0.1132"
54,net_liabilities_to_sales,float64,0.0,0.00,5572.0,"0.2685, 0.61, 0.2568, 0.0, 0.2003, 0.1227, 0.6125, 0.2823, -0.0433, 0.2636"
55,gross_profit_plus_interest_to_sales,float64,0.0,0.00,5643.0,"0.0, 0.0738, 0.1128, 0.0173, 0.0371, 0.121, 0.1165, 0.0302, 0.0893, 0.1655"
56,sales_profit_to_sales,float64,0.0,0.00,5597.0,"0.0, 0.0, 0.002, 0.0144, 0.1036, 0.0, 0.1247, 0.0443, 0.0494, 0.148"
57,operating_profit_to_sales,float64,0.0,0.00,5110.0,"0.0, 0.0288, -0.1247, 0.049, 0.0, 0.1052, 0.0742, 0.0099, 0.0095, 0.0718"
58,receivables_plus_inventory_turnover_days,float64,0.0,0.00,5299.0,"0.0, 105.27, 111.2, 134.82, 117.68, 93.495, 107.27, 113.67, 105.4, 126.11"
59,receivables_days_ratio,float64,0.0,0.00,5560.0,"0.0, 54.412, 103.3, 109.6, 21.74, 41.469, 67.206, 50.184, 76.548, 37.38"
60,ebitda_to_sales,float64,0.0,0.00,5544.0,"0.0, 0.0, -0.0089, 0.0037, 0.1061, 0.0361, -0.0078, 0.0808, 0.0139, -0.1368"
61,working_capital_absolute,float64,0.0,0.00,5660.0,"1797.0, 2443.9, 10361.0, -11216.0, 13593.0, 10577.0, 2305.7, 22830.0, 2317.7, 10445.0"
62,gross_margin,float64,0.0,0.00,5589.0,"1.0, 0.1032, 0.1695, 0.1036, 0.1037, 0.1138, 0.184, 0.1478, 0.1554, 0.2939"
63,total_costs_to_total_sales,float64,0.0,0.00,5072.0,"1.0053, 1.0179, 1.0505, 0.9943, 1.0115, 0.9949, 1.0095, 1.0, 1.0002, 1.054"
64,short_term_liabilities_days_ratio,float64,0.0,0.00,5507.0,"0.0, 104.08, 102.89, 125.27, 101.31, 117.87, 132.1, 118.72, 132.22, 107.84"

In [7]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
net_profit_to_total_assets,5787.0,-0.024261,6.227187,-4.638900e+02,8.745900e+01
total_liabilities_to_total_assets,5787.0,0.466893,5.810483,-4.308700e+02,7.241600e+01
working_capital_to_total_assets,5787.0,0.187873,1.189212,-7.206700e+01,2.833600e+01
current_assets_to_short_term_liabilities,5769.0,4.908487,92.370898,-4.031100e-01,6.845800e+03
liquidity_days_ratio,5779.0,19.568831,21751.730364,-1.076400e+06,1.250100e+06
retained_earnings_to_total_assets,5787.0,0.021568,10.095067,-4.638900e+02,5.432500e+02
ebit_to_total_assets,5787.0,-0.115911,9.150502,-5.174800e+02,5.530000e+00
book_value_equity_to_total_liabilities,5772.0,5.739466,103.400811,-3.735100e+00,6.868500e+03
sales_to_total_assets,5789.0,1.596409,1.561708,-3.496000e+00,6.560700e+01
equity_to_total_assets,5787.0,0.544601,5.823079,-7.144400e+01,3.398500e+02
extended_profit_to_total_assets,5787.0,-0.012176,6.125555,-4.638900e+02,6.388000e+00
gross_profit_to_short_term_liabilities,5769.0,1.064381,35.637072,-2.318500e+02,2.470300e+03
gross_profit_plus_depreciation_to_sales,5790.0,0.359682,31.237561,-3.103400e+02,2.340200e+03
gross_profit_plus_interest_to_total_assets,5787.0,-0.115885,9.150503,-5.174800e+02,5.530000e+00
liabilities_days_ratio,5784.0,1047.365984,131468.435263,-9.632400e+06,1.341700e+06
gross_profit_plus_depreciation_to_total_liabilities,5772.0,1.166713,37.674032,-2.213300e+02,2.837400e+03
total_assets_to_total_liabilities,5772.0,6.835386,103.406737,-2.321000e-03,6.869500e+03
gross_profit_to_total_assets,5787.0,-0.106386,9.179270,-5.174800e+02,5.512500e+01
gross_profit_to_sales,5790.0,-0.093315,5.500968,-3.108000e+02,7.724400e+01
inventory_days_ratio,5790.0,56.858686,169.747013,-2.934000e+01,9.928500e+03
sales_growth_ratio,5687.0,2.487324,101.608010,-1.351500e+02,7.661500e+03
operating_profit_to_total_assets,5787.0,-0.006131,5.690662,-4.315900e+02,1.554100e+01
net_profit_to_sales,5790.0,-0.099886,5.474193,-3.108900e+02,7.724400e+01
three_year_gross_profit_to_total_assets,5655.0,0.137464,7.441703,-4.638900e+02,2.523400e+02
equity_minus_share_capital_to_total_assets,5787.0,0.371925,4.177782,-7.144400e+01,2.668600e+02
net_profit_plus_depreciation_to_total_liabilities,5772.0,1.071154,35.726914,-2.213300e+02,2.689100e+03
operating_profit_to_financial_expenses,5401.0,473.342862,10331.483820,-1.581300e+05,5.659400e+05
working_capital_to_fixed_assets,5685.0,10.355702,305.390255,-1.089700e+03,2.170100e+04
log_total_assets,5787.0,4.143160,0.834145,6.359000e-03,9.698300e+00
net_liabilities_to_sales,5790.0,0.860296,19.273969,-2.306000e+01,1.236700e+03
gross_profit_plus_interest_to_sales,5790.0,-0.068556,5.312490,-3.108000e+02,7.724400e+01
current_liabilities_days_ratio,5744.0,663.461947,31236.978938,-2.551000e+02,2.340500e+06
operating_expenses_to_short_term_liabilities,5769.0,8.392432,103.436070,-1.433400e+00,7.590500e+03
operating_expenses_to_total_liabilities,5772.0,5.068486,101.268843,-1.601500e+01,7.590500e+03
sales_profit_to_total_assets,5787.0,-0.009525,5.686602,-4.315900e+02,1.554100e+01
total_sales_to_total_assets,5787.0,2.061719,12.906769,1.910000e-04,9.656600e+02
current_assets_minus_inventories_to_long_term_liabilities,3288.0,116.036138,1614.856561,-4.325800e+00,6.792200e+04
constant_capital_to_total_assets,5787.0,0.652346,7.188380,-7.144400e+01,4.677700e+02
sales_profit_to_sales,5790.0,0.016032,0.716849,-4.704700e+01,2.901100e+00
liquid_assets_to_short_term_liabilities,5769.0,2.209357,58.301333,-9.068600e+00,4.303200e+03
liabilities_to_adjusted_operating_profit,5706.0,2.231404,83.955724,-2.699900e+02,5.043300e+03
operating_profit_to_sales,5790.0,-0.016517,2.462432,-1.435200e+02,4.038600e+01
receivables_plus_inventory_turnover_days,5790.0,156.204290,790.635019,-3.975600e+03,4.051500e+04
receivables_days_ratio,5790.0,99.345720,727.227485,-3.946200e+03,4.051500e+04
net_profit_to_inventory,5526.0,68.023004,4924.284145,-3.037300e+03,3.660300e+05
current_assets_minus_inventory_to_short_term_liabilities,5769.0,4.021593,92.214957,-9.049000e+00,6.845800e+03
inventory_days_cost_ratio,5755.0,137.701697,3310.273127,-1.865800e+01,1.856100e+05
ebitda_to_total_assets,5787.0,-0.092081,7.151658,-5.425600e+02,1.554100e+01
ebitda_to_sales,5790.0,-0.072699,2.481503,-1.448000e+02,1.686600e+01
current_assets_to_total_liabilities,5772.0,4.176926,91.877055,-1.217500e-02,6.845800e+03
short_term_liabilities_to_total_assets,5787.0,0.428809,1.102596,-1.866100e-01,7.241600e+01
short_term_liabilities_days_cost_ratio,5754.0,0.737896,12.990412,-6.976400e-01,6.661100e+02
equity_to_fixed_assets,5685.0,11.324293,317.636985,-1.088700e+03,2.170200e+04
constant_capital_to_fixed_assets,5685.0,12.252173,323.888823,-1.088700e+03,2.170200e+04
working_capital_absolute,5790.0,10654.957698,79955.386641,-1.118500e+06,4.212200e+06
gross_margin,5790.0,0.055561,0.704598,-4.678800e+01,1.651000e+00
adjusted_liquidity_ratio,5787.0,-0.268223,18.614482,-1.236300e+03,8.798100e+01
total_costs_to_total_sales,5790.0,0.958268,0.865608,-1.643900e-01,4.778800e+01
long_term_liabilities_to_equity,5787.0,0.269451,5.885054,-1.849800e+02,3.081500e+02
inventory_turnover_ratio,5526.0,929.800518,64824.540815,-1.244000e+01,4.818700e+06
receivables_turnover_ratio,5775.0,10.989177,41.521736,-9.249300e-02,1.308500e+03
short_term_liabilities_days_ratio,5790.0,245.143052,6285.238713,-2.365300e+02,4.513800e+05
sales_to_short_term_liabilities,5769.0,9.130587,104.108179,-1.543200e+00,7.641300e+03
sales_to_fixed_assets,5685.0,66.428330,2172.833224,-3.726500e+00,1.581800e+05

In [8]:
# Categorical Feature Statistics
cat_stats

                      value  count    pct
column           rank
company_bankrupt 1       No   5384  92.99
                 2      Yes    406   7.01

In [9]:
# Target Distribution
target_df

                  count    pct
company_bankrupt
No                 5384  92.99
Yes                 406   7.01

## Task Curation

In [10]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [11]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [12]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...

019cb2f9-13f5-7ece-b452-89074fada91d
2e02e284c25bb41ce7f72b759d2ac2744b42ba71a28fc7c10a41195384d3d326