### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="labour_inspection_compliance",
    dataset_year="2019",
    domain_str="industry & manufacturing",
    # Data Source
    dataset_source="Other",
    original_dataset_source_download_link="https://doi.org/10.18710/7U6TZP",
    download_description="""
Get the data from dataverse.

wget https://dataverse.no/api/access/datafile/:persistentId?persistentId=doi:10.18710/7U6TZP/HAV8AG &&  mv  ':persistentId?persistentId=doi:10.18710%2F7U6TZP%2FHAV8AG' data.csv
mkdir -p local-data-warehouse/labour_inspection_compliance && mv data.csv local-data-warehouse/labour_inspection_compliance
""",
    # References
    academic_reference_bibtex="""@inproceedings{flogard2022dataset,
  title={A dataset for efforts towards achieving the sustainable development goal of safe working environments},
  author={Flogard, Eirik Lund and Mengshoel, Ole Jakob},
  booktitle={Thirty-sixth Conference on Neural Information Processing Systems Datasets and Benchmarks Track},
  year={2022}
}
""",
    academic_reference_bibtex_key="flogard2022dataset",
    license="CC0 1.0",
    data_tags=["IID", "Spatial", "ForcedIIDFromTemporal"],
    curation_comments="""
We start with the data from dataverse. We create a task for the Non-compliance Classification Problem (NCP).

- We resolve the industry codes to their true names.
- We drop the checklist ID, as we use the checklist text as predictive signal.
- We remove two rows with missing values for IsRegisteredVATregister, as these seem to be data artifact given the data state.
- The data has spatial information (County).
- There are lot of undescribed numeric values. Thus, we do some general purpose preprocessing and drop all columns with less than 5 not nan values
- As it turns out, the data does not contain temporal information, although it is clearly a temporal task and has data from 2021 to 2019. It seems the curators have removed the temporal information. This can mean that there is not temporal leakage or relevance for the task, or that it was forgotten. In any case, we must treat the task as IID now.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="NonCompliance",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="NonCompliance",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(dataset_mold.path / "data.csv", sep=";")
print("Loaded data shape:", df.shape)


# Resolve industry codes
code_resolution = pd.read_csv("klass-version-30-codes.csv", sep=";")
code_as_number = pd.to_numeric(code_resolution["code"], errors="coerce")
int_codes_mask = code_as_number.notna() & (code_as_number % 1 == 0)
code_resolution = code_resolution[int_codes_mask].copy()
code_resolution["code"] = code_as_number[int_codes_mask].astype(int)
code_resolution = code_resolution.set_index(["code", "parentCode"])["name"].to_dict()
df["Industry Sub Area"] = df.apply(
    lambda row: code_resolution[(row["Industry Code"], row["Industry Main Area Code"])],
    axis=1
)
del code_resolution

sector_map = {
    "A": "Agriculture, forestry and fishing",
    "B": "Mining and quarrying",
    "C": "Manufacturing",
    "D": "Electricity, gas, steam and air conditioning supply",
    "E": "Water supply; sewerage, waste management and remediation activities",
    "F": "Construction",
    "G": "Wholesale and retail trade; repair of motor vehicles and motorcycles",
    "H": "Transportation and storage",
    "I": "Accommodation and food service activities",
    "J": "Information and communication",
    "K": "Financial and insurance activities",
    "L": "Real estate activities",
    "M": "Professional, scientific and technical activities",
    "N": "Administrative and support service activities",
    "O": "Public administration and defence; compulsory social security",
    "P": "Education",
    "Q": "Human health and social work activities",
    "R": "Arts, entertainment and recreation",
    "S": "Other service activities",
    "T": "Activities of household as employers; undifferentiated goods- and services-producing activities of households for own account",
    "U": "Activities of extraterritorial organisations and bodies",
}
df["Industry Main Area"] = df["Industry Main Area Code"].map(sector_map)

df = df[df["IsRegisteredVATregister"].notna()]

prev_cols = set(df.columns)
df = df.dropna(axis=1, thresh=5)
print("Columns dropped due to low non-nan count:", prev_cols - set(df.columns))

df = df.drop(columns=[
    'Checklist ID',
    "Industry Main Area Code",
])
as_cat_type = [
    "Industry Code",
    "IsRegisteredVATregister",
    "IsRegisteredEmploymentregister",
    "NonCompliance",
    "Currency code",
    "Fiscal accounting type",
]
as_string_type = [
    "Checklist Content",
    "Industry Main Area",
    "Industry Sub Area",
    "County",
]

for c in as_string_type:
    nan_mask = df[c].isna()
    df.loc[nan_mask, c] = np.nan
    df[c] = df[c].astype("string")

df[as_cat_type] = df[as_cat_type].astype("category")

# Drop duplicated columns
df = df.loc[:, ~df.T.duplicated()]

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

Loaded data shape: (63634, 581)
Columns dropped due to low non-nan count: {'Change in provision for non-drained risk', 'Exchange rate adjustment funds', 'Change in premiership', "Premium funds, defined contribution funds and pensioners' surplus funds", 'Portfolio result', 'Changes in the value of financial instruments valued at fair value', 'Effective share of gains and losses on hedging instruments in cash flow hedging', 'Retained earnings', 'Change in safety provision', 'Financial revenues', 'Compensations paid out', 'Transferred from funds for assessment differences', 'Change in technical provisions for the non-life insurance business', 'Cost of goods sold', 'Courses/subcurs courses', 'Share of other profit components using the equity method', 'Own bonds, certificates m.m.', 'Tax expense on extraordinary items', "The fund's securities portfolio", 'To (from) technical provisions for the non-life insurance business', 'Foreign securities at cost', 'Overdue, un paid pensions and ejaculation amounts', 'Transfer of the premiere reserve from other insurance lovers/ pension funds', 'Change in exchange rate adjustment funds', 'Unrecognized record 3', 'Other assets of its kind', "Changes in premium funds, defined contribution funds and pensioners' surplus funds", 'Receivables related to premium income', 'To (from) premiere reserve, gross', 'Safety deposition m.v.', 'Total funds assigned to the insurance contracts - contractual obligations', 'Ordinary responsible loan capital', 'Net distribution to unitholders a year', 'Gross compensations paid', 'Interest expense', 'Other insurance-related costs', 'Transfer of additional provisions from other insurance companies/pension companies.1', 'Total investments in the investment portfolio', 'Change in reinsurance share of the premiere reserve.1', 'Transferred to/from retained earnings', 'Share capital at nominal length', 'Unrecognized record 1', 'Premium depot from reinsurance companies', 'Premiereserve', 'Unrecognized record 7', 'To (from) technical provisions for the non-life insurance business ', 'Agio/disagio', 'Other portfolio income', 'Change in prepaid direct sales costs', 'Certificates', 'Change in reinsurance share of the premiere reserve', 'Reinsurance share of compensations paid out', 'Earned, not received revenue', 'Transfer of additional provisions from other insurance companies/pension companies', 'Change in replacement provisions', 'Grants', 'Gross pensions paid out', 'Total accrued costs and receipts, not earned revenue', 'Reinsurance commissions and profit shares', 'Total application', 'Net change unrealized exchange rate gains/share price losses', 'Change in provisions for substitutions', 'Total reinsurance share of gross insurance obligations in insurance', 'Total net income from investments in the collective portfolio', 'Overdue gross premium', 'Allocated investment return transferred to technical accounting', 'Bank deposits', 'Total recognised changes in insurance obligations - separate investment portfolio', 'Allocated investment return transferred from non-technical accounts', 'Profit on return result', 'Adjustment of insurance obligations', 'Change in the premiere reserve', 'Gross profit and loss', 'Change in other provisions', 'Investments in subsidiaries', 'Investment in shares and shares', 'Dividends incurred', 'Tax co-ordination on ordinary profit', 'Overdue premiums, gross', 'Change in reinsurance share of compensation provisions', 'Total investments in the investment choice portfolio', 'Insurance-related administration costs', 'Total assets in the customer portfolio', 'Funds raised, gifts, etc', "Transferred from the savings bank's fund", 'Unrecognized record 5', 'Total securities portfolio', 'result of technical accounts for non-life insurance', 'Subscription fee for management companies', 'Value adjustments - intangible assets', 'Change in additional accruals', 'Security provision', 'Unrealised exchange rate gains', 'For the benefit of brokers', 'Management costs', 'Liabilities in the event of tax', 'Change in provision for not earned gross premium', 'Interest income', 'Administration provision', 'Prepaid costs and no income received', 'Funds raised, gifts m.v', 'Total net income from investments in the company portfolio', 'Guilty to management companies', 'Management fee', 'result of technical accounting prior to safety provisions', 'Total insurance obligations gross in non-life insurance', 'Change in reinsurance share of compensation provisions.1', 'Allocated for distribution to unitholders', 'Group contribution received', 'Transaction costs', 'Management fees incurred', 'Total insurance obligations in life insurance - special investment portfolio', 'Share capital/primary capital certificate capital/guarantee fund', 'Other technical provisions for the non-life insurance business', 'Change in replacement provision', 'Commission income from the sale and redemption of shares', 'Receivables in connection with reinsurance stores', 'Other technical provisions', 'To (from) premiere reserve (gross)', 'Income/costs atr.  fixed assets/disposal groups classified as held for sale', 'Benefit from management companies', 'Risk profit and loss assigned to the insurance contracts', 'Transfer of premiere reserve from other insurance lover/pensj.kass', 'Re-insurance premiums issued', 'Unrecognized record 2', 'Prize discounts and other winning agreements', 'Other invested purpose capital', 'Unknown record 6', 'Costs of sale and redemption of shares', 'Paid pensions', 'Additional accruals', 'Transfer of additional provisions from other insurance companies/pension funds', 'Transfer of the premiere reserve and additional provisions to other insurance companies/pension funds', 'Invested equity', 'Risk equalisation fund', 'Stocks', 'Provision for non-drained risk', 'Provision for prize discounts and other winning agreements', 'Total safety deposition m.v.', 'Write-down of financial assets', 'Total insurance obligations - contractual obligations', 'Replacement provision', 'Tax receivable on dividends', 'Total net income from investments in the investment selection portfolio', 'Transfer of the premiere reserve and additional provisions to other insurance companies/pension companies', 'Supplementary provisions', 'Transfer of a premiere reserve from other insurance companies/pension companies', 'Funds for unrealized gains', 'Transferred from leveling fund', 'Total insurance obligations - special investment portfolio', 'Shares and shares (incl.  shares and shares measured at cost).1', 'Equity ratio of composite financial instruments and other equity instruments', 'Total insurance obligations in life insurance - contractual obligations', 'Total net income from investments in the investment portfolio', 'Gross', 'Ordinary result before tax co-income', 'Total replacements', 'Guilty to brokers', 'Accrued interest', 'Tax costs', 'Reinsurance share of insurance obligations in the collective portfolio', 'Distribution links', 'Total recognised changes in the insurance obligations - contractual obligations', 'Perpetual responsible capital', 'Value of investments', 'Total investments in the collective portfolio', 'Unrecognized record 4', 'Adjustment of the insurance obligations', 'Total assets in the company portfolio', 'Reinsurance share of insurance obligations in the investment choice portfolio', 'Incurred costs and did not receive earned income', 'Norwegian securities at cost', 'Revenue from operational activities', 'Investments in other enterprises in the same group', "Change in premium funds, defined contribution funds and pensioners' surplus funds", 'Paid damages', 'Total change in profit and loss in insurance obligations - contractual obligations', 'Other costs incurred and received, not earned income', 'Effective share of gains and losses on hedging instruments in cash flow hedging.1', 'Courtship', 'Insurance-related administration costs (incl.  commissions for re-insurance received)', 'Gain/loss on realisation', 'Other technical provisions for the non-life insurance business.1', 'Net distribution to unitholders', 'Change in other technical provisions', 'Total pensions m.v.', 'Administrative costs', 'Member deposits to be refunded', 'Gains and losses on financial assets available for sale.1', 'Management results', 'Gross replacement provisions', 'Reinsurance share of pensions paid out', 'Other allocation of surplus', 'Total change in security provisions m.v.', 'Received, unearned rental income', 'Fund bonds', 'Change in the reinsurance share of technical provisions for the non-life insurance business', 'Change in technical provisions for the non-life insurance business.1'}

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 63,634
Columns: 377

#### Duplicate Report
Total duplicate rows: 497 (0.78% of dataset)
Duplicate rows ignoring target: 676 (1.06% of dataset)
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,Industry Code,IsRegisteredVATregister,IsRegisteredEmploymentregister,Business Age,County,Number of Employees,NonCompliance,Checklist Content,Currency code,Fiscal accounting type,Total receivables,Trade receivables,"Bank deposits, cash and the like",Company capital,Market-based bonds,Depreciation of fixed assets and intangible assets,Other operating cost,TOTAL ASSETS,Public fees owed,Total other long-term liabilities,Other market-based financial instruments,Machinery and plant,Total debt,Dividends,Group receivables,Other operating income,Total result,Transfer to/from funds,An increase in value for other financial instruments valued at fair value,Net income (loss) for the year,Goodwill,Loans to enterprises in the same group,Total funds consumed,Minority interests,Other profit components for IFRS enterprises,"Collected funds, gifts m.v.",Accrued dividends,Total purpose capital with self-imposed restrictions,Other operating expenses,Dividends on shares/dividends on primary capital certificates,Interest and similar income from loans to and receivables on customers,Net interest and credit commission income,Other fees and commission income,"Machinery, fixtures and means of transport",Issued by others,Leveling fund,Social costs,Total commission income and income from banking services,Interest and similar costs on issued securities,Interest and similar costs on deposits from and liabilities to customers,Write-down/reversal of write-down,Buildings and other permanent properties,Building loans,Total net loans and receivables from credit institutions,Assets taken over,"Total certificates, bonds and other interest-bearing securities with a fixed return",Total prepaid costs were not incurred and no income received,Total other operating expenses,Transferred to the savings bank's fund,Bond debt,Total liabilities to credit institutions,Deposits from and liabilities to customers without an agreed maturity,Pensions,Total commission costs and costs of banking,result of extraordinary records,Loss on guarantees m.v.,Transferred to gift funds and/or gifts,Total net change in value and gain/loss on foreign exchange and securities that are current assets,Interest and similar costs on responsible loan capital,Certificates and other short-term borrowing,Other belongings,Issued by the public,Annual results before minority interests,Transferred to other equity,Other interest-bearing securities,Other purpose capital with statutory restrictions,Total inventory,"Credit losses on certificates, bonds and other interest-bearing securities",Transferred to funds for assessment differences,Unspecified loss provisions,Fund for assessment differences,Debt letters that can be refinanced in central banks,Own non-amortized certificates,Obligations,Gift fund,Reinsurance obligations,Total prepaid costs and unearned income received,Financial assets that are measured at amortized cost,Financial assets that are measured at fair value,Sum incurred costs and did not receive earned revenue,Provision for unearned gross premium,"Daughter enterprises, affiliated enterprises and jointly controlled enterprises",Earned revenue from operational activities,Realized gain and loss on investments,Investments that are held to maturity,Other financial assets,Fund for changes in value,Net operating income from real estate,Total replacement costs at your own expense,– Reinsurance share of gross premiums earned,Total premium income at your own expense,Other insurance-related income,Other possessions denoted by their nature,Assets by tax,Intermediaries,Receivables in connection with reinsurance,Other prepaid costs and no income received,Sales costs,Ordinary result after tax expense,Group contributions made,Other current liabilities,Investments in equities and shares,Total retained earnings,Other financial instruments,Annual results by minority interests,Total long-term debt,Total intangible assets,Tax payable,"Total bank deposits, cash and the like",Investment in subsidiaries,Holdings of own shares,Shares and shares in enterprises in the same group,Ordinary profit before tax expense,Income from investments in subsidiaries and affiliates,Value reduction other financial instruments valued at fair value,"Operating equipment, fixtures, tools, office machines and the like",Deferred tax assets,Other long-term debt,Other financial cost,Long-term corporate debt,Research and development,Change in inventory of self-made fixed assets,Bond loans,Basic capital,Purpose capital with statutory restrictions,Total invested purpose capital,Total purpose creationL,Fund issue,Total depreciation of m.v. of fixed assets and intangible assets,Salary m.v.,Total dividends and other income from securities with variable returns,result for the financial year prior to minority interests,Repayment loans,Total other liabilities,Salary,Total interest costs and similar costs,Operating costs fixed properties,"Interest rates and similar income from certificates, bonds and other interest-bearing securities",result of ordinary operations after tax,No earnings received,Ownership interests in other group companies,Loans and deposits from credit institutions without an agreed maturity or notice period,Specified provisions on warranty liability,Operating income fixed properties,Other interest costs and similar costs,Interest and similar income from loans to and receivables from credit institutions,Net change in value and gain/loss on equities and other securities with variable returns,Tax on ordinary profit,Total allocations and transfers,Perpetual responsible loan capital,Factoring,"Total shares, shares and other securities with variable returns",Other purpose capital,Financial and investment income,Other assets,profit before tax expense,Other purpose capital with externally imposed restrictions,Holdings of own shares/primary capital certificates,Itemized loss provisions,Rental financing agreements (financial leasing),Margin deductions and other intercompany with customers,Responsible loan capital with associated conversion rights,Receivables factoring,Ownership interests in credit institutions,Liabilities in the event of deferred tax,Total insurance liabilities gross,Total responsible loan capital m.v.,Other retained earnings,TOTAL EQUITY AND LIABILITIES,Reinsurance share of gross compensation provision,Receivables in connection with direct business,Purpose capital with externally imposed restrictions,result of technical accounting,Gross premiums earned,Insurance-related administration costs including 10 commissions for re-insurance received,Provision for the guarantee scheme,Holdings of own shares/equity certificates,"Earned, undiscensed rental income",Facilities and equipment,Actuarial gains and losses on defined benefit pension schemes - benefits to employees,Payroll cost,Net ledger,Tax expense on ordinary profit and loss,Uncovered loss,Accounts payable,Other receivables,Total invested equity,Total items,Market-based equities,Loans to associated companies and jointly controlled enterprises,Total financial revenues,Other interest cost,Total transfers and availability,Interest income from enterprises in the same group,Total current assets,Total fixed assets,Merchandise,Other invested equity,"Licenses, patents, licenses, trademarks and similar rights",Income on other investments,Total fixed assets.1,Total current liabilities,Total equity,Total provisions for liabilities,Pledges,Total revenue,Sales revenue,Responsible loan capital,Deferred tax,Over-course,Total investments,Transfers to/from other equity,Write-down of fixed assets and intangible assets,"Ships, rigs, planes and the like",Bonds,Claim for payment of company capital,Convertible loans,Tax expense on extraordinary profit,Costs associated with the organization's purpose,Administration costs,Other income,Extraordinary records,Losses on loans,Write-downs,Warranty commission,Income from ownership interests in group companies,Other fees and commission costs,Costs incurred and no earned income were received,"Income from equities, shares and other securities with variable returns",result of ordinary operations,TOTAL LIABILITIES AND EQUITY,Total liabilities established by issuance of securities,Loans to and receivables from credit institutions without an agreed maturity or notice period,Total ownership interests in affiliates,Sparebanken's fund,profit and loss for the fiscal year,Net change in value and gain/loss on foreign exchange and financial derivatives,Total write-down/reversal of impairment and gain/loss on securities that are fixed assets,Transferred to leveling fund,Share capital/primary capital certificate capital,"Total losses on loans, guarantees m.v.",Gain/Loss,Total responsible loan capital,"Shares, shares and primary capital certificates",Cash and receivables from central banks,Total ownership interests in group companies,Total preservation-worthy assets,Public subsidies,"Grants, grants m.v. for the fulfillment of org. formåL",Other interest income and similar income,Other responsible loan capital,Other securities,Member revenue,Other long-term borrowings,Extraordinary costs,Interest rates and similar income from debt letters that can be refinanced in central banks,Preference share capital,Contingent liabilities,Transferred from gift funds,Other fixed assets,Lending factoring,Prepaid direct sales costs,Provision for the Nature Damage Fund,Bonds and other fixed-yield securities,Share capital/ownership share capital/guarantee fund,Shares and shares (incl. shares and shares measured at cost),Other obligations,Loans and receivables,Total reinsurance share of gross insurance obligations,Total insurance-related operating expenses,Changes in the value of investments,Investment properties,Pension liabilities o.l.,Interest income and dividend m.v. on financial assets,result before other result components,"Shares and shares in subsidiaries, associated enterprises and joint ventures",Owner-owned property,"Income from investments in subsidiaries, affiliated enterprises and joint ventures","Value regulations - property, plant and equipment",Gains and losses on financial assets available for sale,Changes in prepaid direct sales costs,Exchange rate differences from foreign activities,Tax on other performance components,Total ledger costs,Operating profit and loss,Other interest income,TOTAL EQUITY AND LIABILITIES.1,Other equity,Investments in associated companies,Total costs,Cost of goods,Other financial income,Interest expense to enterprises in the same group,"Land, buildings and other real estate",Guarantees,Change in inventory of goods under manufacturing and manufactured goods,Investment in other enterprises in the same group,Funds,Other provisions for liabilities,Certificate loan,Debt to credit institutions,Current group debt,Pension liabilities,Corporate contribution,Total of financial fixed assets,Purpose capital with self-imposed restrictions,Costs for tasks that fulfill their purpose,Total funds acquired,TOTAL PURPOSE CAPITAL AND LIABILITIES,Register/Operating and Usage Credits,Total provisions for accrued costs and liabilities,Certificates and bonds,Total deposits from and liabilities to customers,Other operating income.1,Total salary and general administration costs,"Shares in responsible companies, limited partnerships m.v.",Other debt,Over-the-course funds,Total net loans and receivables on customers,Write-downs on individual loans,Total interest income and similar income,Total other operating income,Income from ownership interests in affiliated companies,Loans to and receivables from credit institutions with an agreed maturity or notice period,Deposits from and liabilities to customers with an agreed maturity,Ordinary depreciation,Interest and similar costs on debt to credit institutions,Prepaid costs were not incurred,Total other assets,Write-downs on groups of loans,Total subsidy,Costs associated with the acquisition of funds,Other costs,Other provisions for accrued costs and liabilities,Other prepaid costs were not incurred,Other intangible assets,Ownership interests in other affiliates,Overfunding of pension liabilities,Transferred from other equity,Tax expense,Financial derivatives,Other loans,Extraordinary revenues,Loans and deposits from credit institutions with an agreed maturity or notice period,Own non-amortised bonds,Unspecified provisions on warranty liability,Total liabilities,Gross replacement accrual,"Cash register, bank",Reinsurance share of unearned gross premium,Other subsidies,Activities that fulfill your organization's purpose,result of non-technical accounting,– Reinsurance share of gross compensation costs,Activities that create revenue,Obligations in the event of periodic tax,Policyholders,Obligations in connection with direct insurance,Commissions received for re-insurance and profit shares,Total net income from investments,Gross replacement costs,"Administrative costs related to investments, including interest costs",Reinsurance depots,Other insurance-related operating expenses,Obligations to credit institutions,Industry Sub Area,Industry Main Area
0,10,Nei,Ja,163,Vestland,341,1,"HSE and working environment training for managers and worker representatives, Occupational health service, Information and training, Mapping, risk assessment and measures, Duty to register and report work, Coordinations, Safety representative and worker representative's participation",NOK,STORE,163636532.0,156637979.0,125122888.0,35000000.0,NaN,37963940.0,198075157.0,751064514.0,20514901.0,434000000.0,NaN,161622907.0,602737273.0,NaN,6368019.0,4526529.0,NaN,NaN,NaN,60431498.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60431498.0,NaN,21987467.0,20460835.0,113327241.0,5845487.0,NaN,434000000.0,6243645.0,872687.0,125122888.0,301643.0,NaN,NaN,81051222.0,NaN,NaN,13888041.0,6243645.0,NaN,472291.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,192056391.0,-10537779.0,20619724.0,NaN,63012270.0,630534.0,35000000.0,247807000.0,NaN,1960536.0,2624503.0,10958425.0,60431498.0,70353.0,542411907.0,208652607.0,247807000.0,NaN,NaN,NaN,175510948.0,168737273.0,148327241.0,0.0,NaN,2.289635e+09,2.285109e+09,NaN,NaN,NaN,5845487.0,17732060.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13162282.0,91589001.0,1476347.0,751064514.0,113327241.0,4175000.0,2.198046e+09,1.772983e+09,1077803.0,1731566.0,NaN,NaN,-3032000.0,NaN,NaN,NaN,NaN,434000000.0,62349948.0,0.0,42699438.0,26898014.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacture of food products,Manufacturing
1,16,Nei,Ja,53,Agder,11,1,"HSE and working environment training for managers and worker representatives, Occupational health service, Building and equipment conditions, HES card, Not specified, Information and training, Mapping, risk assessment and measures, Machines and other working equipment, Personal protective gear - technical, Duty to register and report work, Coordinations, Safety representative and worker representative's participation",NOK,STORE,14827354.0,233112.0,53258.0,100000.0,NaN,234656.0,2324606.0,32306703.0,570551.0,8334332.0,NaN,NaN,31244441.0,NaN,14353091.0,7665179.0,NaN,NaN,NaN,1049707.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1049707.0,NaN,1630870.0,NaN,NaN,NaN,1049707.0,8334332.0,1966040.0,NaN,53258.0,NaN,NaN,NaN,-916333.0,NaN,NaN,57000.0,1966040.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7122644.0,-935717.0,-1966040.0,5087444.0,10604569.0,241150.0,1062262.0,10665051.0,NaN,NaN,2520.0,938236.0,1049707.0,NaN,25545663.0,6761040.0,10665051.0,962262.0,NaN,NaN,4795000.0,22910109.0,1062262.0,NaN,NaN,2.574837e+07,1.808319e+07,NaN,NaN,NaN,NaN,962262.0,NaN,526000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,938236.0,19384.0,2520.0,32306703.0,NaN,NaN,2.572899e+07,1.604708e+07,NaN,NaN,4212000.0,NaN,NaN,NaN,NaN,NaN,NaN,8334332.0,8172567.0,NaN,-5000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Manufacture of wood and products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials, except furniture",Manufacturing
2,85,Nei,Ja,604,Viken,63,1,"HSE and working environment training for managers and worker representatives, Occupational health service, Not specified, Mapping, risk assessment and measures, Facilitation and management, Safety representative and worker representative's participation, Violence and threats",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Education,Education

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Currency code,category,14003,22.01,9,"NOK, EUR, SEK, USD, CHF, DKK, USN, ISK, GBP"
1,Fiscal accounting type,category,14003,22.01,8,"STORE, BANK, IDEELL, SKADE, FRIV, FUNK, PENSJ, LIV"
2,Industry Code,category,0,0.00,84,"43, 41, 47, 56, 49, 88, 46, 10, 45, 84"
3,IsRegisteredVATregister,category,0,0.00,3,"Nei, Ja, Not specified"
4,IsRegisteredEmploymentregister,category,0,0.00,3,"Ja, Nei, Not specified"
5,NonCompliance,category,0,0.00,2,"1, 0"
6,Own non-amortized certificates,float64,63629,99.99,2,"0.0, 19000000.0"
7,Intermediaries,float64,63628,99.99,4,"76366000.0, 4859659.0, 5140099.0, 71000000.0"
8,Other assets,float64,63625,99.99,4,"2995000.0, 3176332.0, 240000.0, 11758000.0"
9,Receivables factoring,float64,63628,99.99,3,"0.0, 2297185815.0, 76190525.0"
10,Holdings of own shares/equity certificates,float64,63626,99.99,1,-100000.0
11,Extraordinary costs,float64,63626,99.99,1,0.0
12,Transferred from gift funds,float64,63629,99.99,5,"2878000.0, 200000.0, 100000.0, 800000.0, 193000.0"
13,Lending factoring,float64,63629,99.99,2,"0.0, 9756101.0"
14,Investment properties,float64,63628,99.99,5,"269000000.0, 9908000.0, 1581000.0, 639647.0, 91476454.0"
15,"Value regulations - property, plant and equipment",float64,63626,99.99,2,"-19000000.0, 100000000.0"
16,Changes in prepaid direct sales costs,float64,63627,99.99,2,"69000000.0, 1462030.0"
17,"Shares in responsible companies, limited partnerships m.v.",float64,63625,99.99,6,"2416000.0, 7319000000.0, 21000000.0, 747000.0, 604000.0, 1193000.0"
18,Transferred from other equity,float64,63625,99.99,6,"20000000.0, -17240000.0, 298000.0, 937000.0, -259000.0, -9591349.0"
19,Extraordinary revenues,float64,63629,99.99,3,"3597000.0, 36885000.0, 19280000.0"
20,Obligations to credit institutions,float64,63629,99.99,4,"178000000.0, 611000.0, 1334000000.0, 0.0"
21,Other interest-bearing securities,float64,63621,99.98,7,"0.0, 160114000000.0, 56218000.0, 3828147569.0, 1047498000.0, 684000000.0, 56480000.0"
22,"Credit losses on certificates, bonds and other interest-bearing securities",float64,63624,99.98,1,0.0
23,Transferred to funds for assessment differences,float64,63619,99.98,7,"-7000000.0, -111000000.0, 44000000.0, -8170000.0, 9255000.0, -95000000.0, 27553000.0"
24,Investments that are held to maturity,float64,63621,99.98,5,"1625900000.0, 26407.0, 178914000.0, 192115000.0, 2039791790.0"
25,Other possessions denoted by their nature,float64,63620,99.98,6,"486200000.0, 742000000.0, 5557000.0, 34649310.0, 3000000.0, 6685699.0"
26,Assets by tax,float64,63621,99.98,7,"21000000.0, 0.0, 10339000.0, 1381000.0, 50613000.0, 4054590.0, 563000000.0"
27,Responsible loan capital with associated conversion rights,float64,63622,99.98,7,"0.0, 90573000.0, 30000000.0, 150000000.0, 44722000.0, 90000000.0, 49887000.0"
28,"Earned, undiscensed rental income",float64,63624,99.98,4,"373000000.0, 221000000.0, 14756000.0, 386000000.0"
29,Other securities,float64,63619,99.98,4,"4172000000.0, 696000.0, 101730000.0, 57558000.0"
30,Interest rates and similar income from debt letters that can be refinanced in central banks,float64,63619,99.98,5,"0.0, 55000000.0, 660000000.0, 395000.0, 48000000.0"
31,Prepaid direct sales costs,float64,63624,99.98,4,"985000000.0, 10144760.0, 181806000.0, 39550000.0"
32,Gains and losses on financial assets available for sale,float64,63619,99.98,3,"-12200000.0, 1014000000.0, 2207292.0"
33,Unspecified provisions on warranty liability,float64,63622,99.98,4,"0.0, 100000.0, 498000.0, 175000.0"
34,Loss on guarantees m.v.,float64,63615,99.97,11,"0.0, -155000.0, 235000.0, 1000000.0, 895000.0, -2000.0, -926000.0, 1400000.0, 6000000.0, -1000.0"
35,Unspecified loss provisions,float64,63617,99.97,11,"49352000.0, 0.0, 20000000.0, 109955000.0, 8206000.0, 12678000.0, 11000000.0, 28840000.0, 39546000.0, 19100000.0"
36,Fund for assessment differences,float64,63615,99.97,8,"134000000.0, 0.0, 52000000.0, 335000000.0, 5575000.0, 115432000.0, 363000.0, 117516000.0"
37,Debt letters that can be refinanced in central banks,float64,63616,99.97,3,"94236000000.0, 0.0, 107571000000.0"
38,Other financial assets,float64,63617,99.97,9,"18268700000.0, 651762000.0, 15166000.0, 208223000.0, 40483000.0, 121054395.0, 83000000.0, 24230000.0, 333515646.0"
39,Receivables in connection with reinsurance,float64,63612,99.97,8,"340100000.0, 426000000.0, 183000000.0, 54273477.0, 23422000.0, 119761433.0, 110000000.0, 10528000.0"
40,Sales costs,float64,63612,99.97,13,"3508000000.0, 2106000000.0, 53781000.0, 41905662.0, 7832069.0, 3292000.0, 366848000.0, -4056155.0, 426682000.0, 348984699.0"
41,Purpose capital with statutory restrictions,float64,63613,99.97,2,"11142000.0, 7000.0"
42,Itemized loss provisions,float64,63617,99.97,11,"10231000.0, 0.0, 19351000.0, 297093000.0, 2008000.0, 22274000.0, 26124000.0, 25299000.0, 28991000.0, 10935000.0"
43,Margin deductions and other intercompany with customers,float64,63618,99.97,3,"1572000000.0, 0.0, 21055827.0"
44,Provision for the guarantee scheme,float64,63615,99.97,9,"628900000.0, 83301000.0, 3018074.0, 13920870.0, 109793000.0, 2388000.0, 764684.0, 44102000.0, 2266513.0"
45,Actuarial gains and losses on defined benefit pension schemes - benefits to employees,float64,63616,99.97,9,"-159200000.0, -1181000.0, -95000000.0, -63000.0, -4681000.0, -119271.0, -1935000.0, -2225911.0, 3966733.0"
46,Write-downs,float64,63615,99.97,7,"0.0, 6800000.0, 16500000.0, 66000000.0, 5000000.0, 765000.0, 2000000.0"
47,Member revenue,float64,63618,99.97,9,"4799000.0, 3383000.0, 15773000.0, 159000.0, 42358045.0, 855000.0, 33277000.0, 93200.0, 3807000.0"
48,Preference share capital,float64,63617,99.97,3,"3013000000.0, 0.0, 230149000.0"
49,Provision for the Nature Damage Fund,float64,63613,99.97,10,"2266200000.0, 8326000.0, 6315844.0, 822000000.0, 0.0, 71013000.0, 462000.0, 10912.0, 159759000.0, 48447250.0"
50,Pension liabilities o.l.,float64,63612,99.97,13,"511800000.0, 10924000.0, 345000000.0, 61000.0, 863000.0, 109451000.0, 61428000.0, 6696944.0, 233040902.0, 55000000.0"
51,"Shares and shares in subsidiaries, associated enterprises and joint ventures",float64,63617,99.97,9,"6828600000.0, 3172000000.0, 274489000.0, 39586000.0, 825887000.0, 630846364.0, 700000000.0, 616581000.0, 503442731.0"
52,"Income from investments in subsidiaries, affiliated enterprises and joint ventures",float64,63612,99.97,9,"19100000.0, -6000000.0, 558000000.0, 26689000.0, 53810000.0, 91672098.0, 83000000.0, 14279453.0, 9406291.0"
53,Exchange rate differences from foreign activities,float64,63613,99.97,7,"-391300000.0, 386000000.0, -3297000.0, 51000000.0, 3095000.0, 8042000.0, -238000000.0"
54,Policyholders,float64,63612,99.97,13,"9036000000.0, 83798000.0, 110945770.0, 15513356.0, 1108000000.0, 1122389000.0, 43124000.0, 1019786000.0, 129983000.0, 5391907.0"
55,Reinsurance depots,float64,63618,99.97,4,"457800000.0, 7000000.0, 3705589.0, 4000000.0"
56,Other purpose capital with statutory restrictions,float64,63607,99.96,4,"71402000.0, 203414000.0, 16297145.0, 0.0"
57,Realized gain and loss on investments,float64,63606,99.96,13,"1920800000.0, 266000000.0, 17757000.0, 4098803.0, 11720044.0, 1088000.0, 9018000.0, -2378873.0, 974284000.0, 16817266.0"
58,Net operating income from real estate,float64,63610,99.96,10,"0.0, 8000000.0, 12000000.0, -2576928.0, 292000.0, -123460.0, 363293.0, -1000000.0, 295440.0, 68011412.0"
59,Specified provisions on warranty liability,float64,63611,99.96,7,"0.0, 10000000.0, 2500000.0, 2743118.0, 1150000.0, 6000000.0, 5400000.0"
60,Holdings of own shares/primary capital certificates,float64,63611,99.96,12,"-3000000.0, 0.0, -2011000.0, -624000.0, -223000.0, -410000.0, -316000.0, -290000.0, -4000000.0, 165357000.0"
61,Rental financing agreements (financial leasing),float64,63609,99.96,9,"2436000000.0, 2854000000.0, 0.0, 16295000000.0, 805258000.0, 26597359650.0, 2929098000.0, 20700000.0, 1232768000.0"
62,Liabilities in the event of deferred tax,float64,63607,99.96,12,"905400000.0, 707000000.0, 5653711.0, 633000000.0, 6312018.0, 73345000.0, 257000.0, 115179000.0, 613835000.0, 111000000.0"
63,Total responsible loan capital m.v.,float64,63607,99.96,8,"0.0, 1946800000.0, 645875000.0, 2567000000.0, 20000000.0, 249072000.0, 323437000.0, 1000000000.0"
64,Share capital/ownership share capital/guarantee fund,float64,63606,99.96,13,"999900000.0, 104000000.0, 86156000.0, 40606000.0, 1100000000.0, 2478000.0, 175000000.0, 79122000.0, 40000000.0, 348400000.0"
65,Loans and receivables,float64,63610,99.96,11,"60030600000.0, 250000000.0, 72037944.0, 25000.0, 805635000.0, 163729660.0, 46696635.0, 56000000.0, 1180821000.0, 45226898.0"
66,Owner-owned property,float64,63611,99.96,9,"29500000.0, 2000000.0, 13725000.0, 22560000.0, 97961000.0, 123000.0, 4951294.0, 12000000.0, 3129949.0"
67,Tax on other performance components,float64,63611,99.96,9,"-106400000.0, 296000000.0, -1120000.0, -11000000.0, -1170000.0, -29818.0, 3000000.0, -484000.0, -556479.0"
68,Other costs,float64,63607,99.96,12,"9200000.0, 585000000.0, 28244000.0, 199000000.0, 1986661.0, 13433000.0, 3856000.0, 54874000.0, 1243.0, 28193981.0"
69,Overfunding of pension liabilities,float64,63611,99.96,8,"164000000.0, 0.0, 124000.0, 500000.0, 2500000.0, 8712000.0, 9868000.0, 2172000.0"
70,Obligations in the event of periodic tax,float64,63611,99.96,11,"1272700000.0, 0.0, 30464000.0, 268000000.0, 515078.0, 26949306.0, 4833000.0, 23960000.0, 246060.0, 105262181.0"
71,Commissions received for re-insurance and profit shares,float64,63606,99.96,12,"23700000.0, 101000000.0, 172267000.0, 150000000.0, 31426711.0, 17977615.0, 210400000.0, 19598000.0, 251873000.0, 374151837.0"
72,Other insurance-related operating expenses,float64,63610,99.96,10,"4068000000.0, 263000000.0, 25839000.0, 2852207.0, 204757000.0, 638658000.0, 3462734.0, 2463319.0, 10620000.0, 18336708.0"
73,Annual results before minority interests,float64,63603,99.95,15,"4665800000.0, 4119000000.0, 452681000.0, 2525000000.0, 14034434.0, 34022439.0, 302659000.0, 175084000.0, -37427000.0, 1077932.0"
74,Total inventory,float64,63600,99.95,11,"1513000.0, 1618038.0, 62480.0, 702000.0, 150000.0, 1002343.0, 1914000.0, 1055000.0, 14526629.0, 6284000.0"
75,Reinsurance obligations,float64,63605,99.95,13,"88200000.0, 253000000.0, 196841000.0, 7318811.0, 426000000.0, 44600108.0, 137023000.0, 33920000.0, 320369000.0, 20992000.0"
76,Total prepaid costs and unearned income received,float64,63602,99.95,16,"91300000.0, 1578000000.0, 182930000.0, 676000000.0, 12646740.0, 11568542.0, 6145000.0, 1605000.0, 493185000.0, 205106000.0"
77,Financial assets that are measured at amortized cost,float64,63601,99.95,8,"0.0, 61656500000.0, 26407.0, 25000.0, 984549000.0, 163729660.0, 1372936000.0, 2072090958.0"
78,Financial assets that are measured at fair value,float64,63601,99.95,17,"56882000000.0, 77265000000.0, 8537624000.0, 39136000000.0, 366754030.0, 575849875.0, 1288344000.0, 0.0, 3170841000.0, 9944521000.0"
79,Sum incurred costs and did not receive earned revenue,float64,63603,99.95,15,"493300000.0, 1211000000.0, 333707000.0, 45000000.0, 8280559.0, 36721878.0, 41881000.0, 426677000.0, 8441000.0, 757356.0"
80,Provision for unearned gross premium,float64,63603,99.95,15,"8585900000.0, 15851000000.0, 590750000.0, 5783000000.0, 41593070.0, 135250675.0, 1297929000.0, 1407332000.0, 57250000.0, 619249.0"
81,"Daughter enterprises, affiliated enterprises and jointly controlled enterprises",float64,63601,99.95,10,"0.0, 8248800000.0, 3172000000.0, 322932000.0, 39586000.0, 830893000.0, 633846364.0, 1700000000.0, 616581000.0, 639206635.0"
82,Fund for changes in value,float64,63605,99.95,11,"20000000.0, 0.0, 51000000.0, 52000000.0, 31255000.0, 45876000.0, 104384000.0, 139000000.0, 39713000.0, 44055000.0"
83,Total replacement costs at your own expense,float64,63603,99.95,15,"17479600000.0, 20569000000.0, 2540363000.0, 11517000000.0, 25513518.0, 125221274.0, 1249597000.0, 1963920000.0, 21661000.0, 15831338.0"
84,– Reinsurance share of gross premiums earned,float64,63604,99.95,14,"578000000.0, 1403000000.0, 581338000.0, 153788861.0, 98747746.0, 1197000000.0, 4235000.0, 81999000.0, 678940000.0, 663831000.0"
85,Total premium income at your own expense,float64,63601,99.95,17,"23921300000.0, 29770000000.0, 2669030000.0, 16487000000.0, 27316539.0, 179402036.0, 2891399000.0, 23557000.0, 1905866000.0, 6443587000.0"
86,Other insurance-related income,float64,63603,99.95,16,"1570000000.0, 421000000.0, 15433000.0, 2047437.0, 5912793.0, 874000.0, 697000.0, 21705000.0, 114040000.0, 203079000.0"
87,Other prepaid costs and no income received,float64,63602,99.95,16,"91300000.0, 220000000.0, 182930000.0, 455000000.0, 2501980.0, 11568542.0, 6145000.0, 1605000.0, 453635000.0, 8544000.0"
88,Basic capital,float64,63600,99.95,14,"194000000.0, 4548750.0, 26300000.0, 21278128.0, 3685000.0, 438694.0, 2407000.0, 100000000.0, 37355338.0, 1320000.0"
89,Total invested purpose capital,float64,63602,99.95,12,"194000000.0, 4548750.0, 26300000.0, 21278128.0, 438694.0, 2407000.0, 37355338.0, 1320000.0, 500560.0, 20000.0"
90,profit before tax expense,float64,63601,99.95,17,"6139900000.0, 5300000000.0, 541095000.0, 3142000000.0, 12790891.0, 39534900.0, 230871000.0, -37427000.0, 394606000.0, 521457000.0"
91,Ownership interests in credit institutions,float64,63600,99.95,13,"591000000.0, 3733000000.0, 1350000000.0, 0.0, 350130000.0, 1259000000.0, 390000000.0, 82367000.0, 56305000.0, 1000000000.0"
92,Total insurance liabilities gross,float64,63603,99.95,15,"46102400000.0, 62108000000.0, 5147983000.0, 30601000000.0, 181018187.0, 560607203.0, 3411577000.0, 1709189000.0, 105424000.0, 8001182.0"
93,Other retained earnings,float64,63601,99.95,17,"19876300000.0, 21370000000.0, 1822740000.0, 8205000000.0, 337562792.0, 163766084.0, 454383000.0, -152395000.0, 492712000.0, 1059076000.0"
94,TOTAL EQUITY AND LIABILITIES,float64,63601,99.95,17,"67745000000.0, 93653000000.0, 9847383000.0, 49527000000.0, 552846337.0, 970807343.0, 3488012000.0, 230793000.0, 5436241000.0, 47033142000.0"
95,Reinsurance share of gross compensation provision,float64,63604,99.95,14,"706800000.0, 1741000000.0, 638166000.0, 97252019.0, 101782130.0, 1820000000.0, 4018000.0, 38654000.0, 655814000.0, 462798000.0"
96,Receivables in connection with direct business,float64,63602,99.95,16,"5621500000.0, 9036000000.0, 160164000.0, 1108000000.0, 110945770.0, 20373015.0, 1019786000.0, 43124000.0, 129983000.0, 1122389000.0"
97,Purpose capital with externally imposed restrictions,float64,63601,99.95,9,"9226000.0, 28250000.0, 7000.0, 1052000.0, -1736194.0, -77341000.0, 14000000.0, -101753.0, 1914000.0"
98,result of technical accounting,float64,63601,99.95,17,"3943700000.0, 4406000000.0, 69708000.0, 2311000000.0, -7968057.0, 13401134.0, 289695000.0, -38292000.0, 326905000.0, 304823000.0"
99,Gross premiums earned,float64,63603,99.95,15,"21930600000.0, 31173000000.0, 3250368000.0, 17684000000.0, 126064285.0, 333190897.0, 2584806000.0, 2895634000.0, 105556000.0, 18813934.0"
100,Insurance-related administration costs including 10 commissions for re-insurance received,float64,63604,99.95,14,"2973400000.0, 1477000000.0, 703000000.0, 167039000.0, 33749100.0, 21964061.0, 57191000.0, 194621000.0, 5209591.0, 478441000.0"
101,Facilities and equipment,float64,63603,99.95,15,"292500000.0, 88000000.0, 12421000.0, 49000000.0, 466000.0, 1535486.0, 10587000.0, 18470000.0, 379000.0, 72026000.0"
102,"Grants, grants m.v. for the fulfillment of org. formåL",float64,63603,99.95,10,"2146000.0, 40568932.0, 21640000.0, 15860000.0, 853333000.0, 847940.0, 143473043.0, 26293362.0, 361834736.0, 293390.0"
103,Bonds and other fixed-yield securities,float64,63603,99.95,15,"30385800000.0, 64562000000.0, 5224987000.0, 34167000000.0, 196696606.0, 407933956.0, 2935375000.0, 1781141000.0, 1268768000.0, 8349107000.0"
104,Shares and shares (incl. shares and shares measured at cost),float64,63603,99.95,15,"6892100000.0, 12322000000.0, 1670208000.0, 3998000000.0, 98019480.0, 167915919.0, 235466000.0, 290904000.0, 3000.0, 12850924.0"
105,Other obligations,float64,63601,99.95,17,"60867900000.0, 5185000000.0, 56899000.0, 1266000000.0, 932514.0, 3824675.0, 49709000.0, 5034000.0, 442553000.0, 700370000.0"
106,Total reinsurance share of gross insurance obligations,float64,63603,99.95,15,"706800000.0, 2121000000.0, 704146000.0, 2034000000.0, 124911549.0, 162494802.0, 978678000.0, 4024000.0, 84466000.0, 0.0"
107,Total insurance-related operating expenses,float64,63601,99.95,17,"2949700000.0, 4953000000.0, 48553000.0, 2659000000.0, 11818515.0, 44228051.0, 0.0, 40885000.0, 351069000.0, 960804000.0"
108,Changes in the value of investments,float64,63603,99.95,15,"-1053400000.0, -235000000.0, 310999000.0, -117000000.0, 3898136.0, 10999441.0, 8473000.0, -2377000.0, -8222000.0, -2847866.0"
109,Interest income and dividend m.v. on financial assets,float64,63602,99.95,16,"1266100000.0, 1597000000.0, 191485000.0, 667000000.0, 13084745.0, 9896688.0, 65275000.0, 874000.0, 25986000.0, 4272000.0"
110,result before other result components,float64,63601,99.95,17,"4670400000.0, 4119000000.0, 452681000.0, 2525000000.0, 14034434.0, 34022439.0, 175084000.0, -37427000.0, 302659000.0, 407367000.0"
111,Purpose capital with self-imposed restrictions,float64,63601,99.95,8,"-71000.0, 24838000.0, 0.0, -8819115.0, 5711000.0, 647.0, -1941000.0, 3000000.0"
112,Tax expense,float64,63604,99.95,14,"1474100000.0, 1181000000.0, 617000000.0, 88414000.0, 5512461.0, -1243543.0, 55787000.0, 91947000.0, -2112940.0, 62792000.0"
113,Own non-amortised bonds,float64,63603,99.95,13,"1000000.0, 423000000.0, 30000000.0, 570000000.0, 946000000.0, 90000000.0, 5000000.0, 148363500.0, 219000.0, 19000000.0"
114,Total liabilities,float64,63601,99.95,17,"6246900000.0, 7108000000.0, 1253303000.0, 4816000000.0, 10482092.0, 69348384.0, 59063000.0, 40267000.0, 619326000.0, 978845000.0"
115,Gross replacement accrual,float64,63604,99.95,14,"32447500000.0, 46257000000.0, 4557233000.0, 425356528.0, 139425117.0, 24818000000.0, 301857000.0, 48174000.0, 2113648000.0, 1061533000.0"
116,"Cash register, bank",float64,63601,99.95,17,"2158700000.0, 742000000.0, 204307000.0, 451000000.0, 5913279.0, 40335295.0, 85223000.0, 87897000.0, 221936000.0, 262633000.0"
117,Reinsurance share of unearned gross premium,float64,63605,99.95,13,"115500000.0, 380000000.0, 65980000.0, 23129419.0, 214000000.0, 65242783.0, 322864000.0, 45812000.0, 6000.0, 169464000.0"
118,result of non-technical accounting,float64,63601,99.95,17,"2196100000.0, 894000000.0, 471387000.0, 831000000.0, 20758948.0, 26133766.0, -58824000.0, 865000.0, 67701000.0, 216634000.0"
119,– Reinsurance share of gross compensation costs,float64,63604,99.95,14,"497100000.0, 641000000.0, 464652000.0, 135087166.0, 64654906.0, 96000000.0, 277000.0, 84928000.0, 354247000.0, 271896000.0"
120,Activities that create revenue,float64,63602,99.95,8,"59240000.0, 3455000.0, 4845000.0, 53000.0, 212583332.0, 652832.0, 2296900.0, 1105355.0"
121,Obligations in connection with direct insurance,float64,63603,99.95,15,"289600000.0, 1337000000.0, 7311000.0, 556000000.0, 2230767.0, 20923601.0, 39750000.0, 6152000.0, 1313000.0, 129411000.0"
122,Total net income from investments,float64,63603,99.95,15,"2196100000.0, 1479000000.0, 499265000.0, 925000000.0, 20678224.0, 27922121.0, 79662000.0, -3950000.0, 865000.0, 41753.0"
123,Gross replacement costs,float64,63603,99.95,15,"15205300000.0, 21210000000.0, 3005015000.0, 11613000000.0, 90168424.0, 260308440.0, 1603844000.0, 1964197000.0, 106589000.0, 15831338.0"
124,"Administrative costs related to investments, including interest costs",float64,63604,99.95,14,"218900000.0, 151000000.0, 195000000.0, 20976000.0, 260868.0, 2259716.0, 9000.0, 3104000.0, 1384996.0, 24171000.0"
125,Total purpose capital with self-imposed restrictions,float64,63598,99.94,12,"18582000.0, 24838000.0, 6479720.0, 25775321.0, 5711000.0, 7626842.0, 28904455.0, 10776805.0, 27525149.0, 8645059.0"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
Business Age,63634.0,2.011097e+02,1.976831e+02,-1.050000e+02,2.361000e+03
Number of Employees,63634.0,1.120812e+02,8.117329e+02,6.000000e+00,2.824900e+04
Total receivables,49051.0,1.770889e+08,2.123415e+09,-6.974970e+05,1.111610e+11
Trade receivables,47665.0,1.021949e+08,1.429322e+09,-1.138160e+06,8.741300e+10
"Bank deposits, cash and the like",46134.0,6.191823e+07,7.409474e+08,-3.855300e+07,4.812900e+10
Company capital,48713.0,6.494859e+07,8.818570e+08,-1.574047e+06,5.502100e+10
Market-based bonds,555.0,1.704854e+08,1.409295e+09,0.000000e+00,1.899600e+10
Depreciation of fixed assets and intangible assets,47206.0,2.002496e+07,1.315036e+08,-3.635000e+09,6.427000e+09
Other operating cost,49295.0,1.147271e+08,8.898446e+08,-6.028000e+09,5.226500e+10
TOTAL ASSETS,49631.0,2.541217e+09,6.117032e+10,-2.075746e+06,2.348272e+12
Public fees owed,48295.0,1.599255e+07,5.930341e+07,-1.109311e+06,3.098886e+09
Total other long-term liabilities,29569.0,2.431225e+08,2.957081e+09,-1.453714e+06,1.050800e+11
Other market-based financial instruments,541.0,9.985039e+07,1.094058e+09,0.000000e+00,2.521300e+10
Machinery and plant,18748.0,1.597138e+08,1.594781e+09,-1.144000e+04,4.233400e+10
Total debt,49598.0,2.141864e+09,5.640220e+10,-5.110470e+05,2.158195e+12
Dividends,14635.0,2.241434e+07,1.364586e+08,-4.670000e+08,3.922000e+09
Group receivables,9131.0,1.291360e+08,4.285421e+08,-3.880000e+05,8.554000e+09
Other operating income,36274.0,5.387077e+07,4.991258e+08,-3.786000e+09,1.330300e+10
Total result,21986.0,5.694535e+07,7.117922e+08,-2.170000e+08,2.060000e+10
Transfer to/from funds,2362.0,5.145126e+06,1.050534e+08,-1.180079e+09,8.809110e+08
An increase in value for other financial instruments valued at fair value,1625.0,2.682414e+06,3.006519e+07,-9.041800e+07,9.537080e+08
Net income (loss) for the year,49452.0,3.565685e+07,3.951939e+08,-2.902000e+09,1.322200e+10
Goodwill,8130.0,2.482384e+08,2.404172e+09,-1.155000e+07,7.043800e+10
Loans to enterprises in the same group,6947.0,7.350706e+07,4.681915e+08,-8.925000e+04,1.783900e+10
Total funds consumed,50.0,6.525383e+08,4.882843e+08,2.327098e+07,1.192086e+09
Minority interests,1629.0,2.858773e+07,1.047979e+08,-2.910000e+08,2.326000e+09
Other profit components for IFRS enterprises,707.0,-1.178522e+08,6.033166e+08,-3.233000e+09,8.572100e+08
"Collected funds, gifts m.v.",44.0,6.933510e+07,6.527808e+07,1.952700e+04,4.201843e+08
Accrued dividends,61.0,-5.387685e+06,5.242414e+07,-1.613368e+08,5.532800e+07
Total purpose capital with self-imposed restrictions,36.0,2.080870e+07,1.123847e+07,5.711000e+06,6.347100e+07
Other operating expenses,138.0,1.313760e+09,2.716297e+09,-8.300000e+07,7.207000e+09
Dividends on shares/dividends on primary capital certificates,49.0,1.487717e+08,1.698999e+08,2.400000e+05,5.750000e+08
Interest and similar income from loans to and receivables on customers,130.0,1.125853e+10,1.739926e+10,3.142900e+07,4.473500e+10
Net interest and credit commission income,146.0,7.819792e+09,1.275363e+10,-5.804280e+05,3.451700e+10
Other fees and commission income,134.0,2.689583e+09,3.972895e+09,4.670000e+05,1.579600e+10
"Machinery, fixtures and means of transport",122.0,1.482957e+09,2.765165e+09,2.000000e+03,6.946000e+09
Issued by others,122.0,2.852269e+09,4.605090e+09,0.000000e+00,2.204200e+10
Leveling fund,58.0,6.271290e+08,7.805464e+08,1.174000e+03,4.487000e+09
Social costs,120.0,2.217632e+08,3.974656e+08,1.651909e+06,2.374000e+09
Total commission income and income from banking services,146.0,2.475430e+09,3.884830e+09,0.000000e+00,1.601100e+10
Interest and similar costs on issued securities,110.0,1.146192e+09,2.192697e+09,2.873000e+06,1.301300e+10
Interest and similar costs on deposits from and liabilities to customers,123.0,2.070558e+09,3.013070e+09,2.207352e+06,7.065000e+09
Write-down/reversal of write-down,56.0,-3.189346e+09,3.700532e+09,-7.424000e+09,9.690000e+05
Buildings and other permanent properties,152.0,3.060881e+08,7.569821e+08,0.000000e+00,2.970000e+09
Building loans,75.0,6.005410e+08,9.041871e+08,0.000000e+00,4.285000e+09
Total net loans and receivables from credit institutions,146.0,1.376893e+11,2.399098e+11,0.000000e+00,5.931250e+11
Assets taken over,45.0,1.215804e+07,1.304767e+07,0.000000e+00,4.600000e+07
"Total certificates, bonds and other interest-bearing securities with a fixed return",146.0,4.967958e+10,8.839795e+10,0.000000e+00,2.361200e+11
Total prepaid costs were not incurred and no income received,122.0,5.627750e+08,1.459620e+09,0.000000e+00,4.792000e+09
Total other operating expenses,146.0,1.246321e+09,2.655378e+09,-8.300000e+07,7.207000e+09
Transferred to the savings bank's fund,67.0,1.355117e+08,1.573247e+08,6.733000e+06,5.960000e+08
Bond debt,108.0,1.508730e+11,2.573771e+11,6.996841e+07,8.416730e+11
Total liabilities to credit institutions,145.0,8.074480e+10,1.293807e+11,0.000000e+00,3.387310e+11
Deposits from and liabilities to customers without an agreed maturity,97.0,4.298289e+10,1.154207e+11,6.645790e+08,7.929240e+11
Pensions,120.0,2.066033e+08,3.992373e+08,-2.200000e+08,9.680000e+08
Total commission costs and costs of banking,146.0,7.232749e+08,1.227482e+09,0.000000e+00,4.678000e+09
result of extraordinary records,114.0,3.688684e+05,3.926621e+06,-8.491000e+06,3.688500e+07
Loss on guarantees m.v.,19.0,5.092632e+05,1.431236e+06,-9.260000e+05,6.000000e+06
Transferred to gift funds and/or gifts,58.0,7.273397e+07,1.396747e+08,2.000000e+05,4.010000e+08
Total net change in value and gain/loss on foreign exchange and securities that are current assets,146.0,1.767960e+09,3.259994e+09,-6.200000e+07,8.834000e+09
Interest and similar costs on responsible loan capital,104.0,1.418179e+08,2.175018e+08,0.000000e+00,5.320000e+08
Certificates and other short-term borrowing,53.0,6.995000e+10,7.668733e+10,0.000000e+00,1.534150e+11
Other belongings,127.0,1.193019e+10,2.372153e+10,2.100000e+04,6.079600e+10
Issued by the public,122.0,1.020083e+10,3.379405e+10,0.000000e+00,2.346150e+11
Annual results before minority interests,31.0,2.304382e+09,2.081076e+09,-3.742700e+07,4.665800e+09
Transferred to other equity,71.0,3.367006e+09,7.449757e+09,-2.030000e+08,2.060000e+10
Other interest-bearing securities,13.0,2.507358e+10,5.994186e+10,0.000000e+00,1.601140e+11
Other purpose capital with statutory restrictions,27.0,9.605256e+07,6.085647e+07,0.000000e+00,2.034140e+08
Total inventory,34.0,1.780741e+06,2.467824e+06,6.248000e+04,1.452663e+07
"Credit losses on certificates, bonds and other interest-bearing securities",10.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Transferred to funds for assessment differences,15.0,-2.355747e+07,5.525348e+07,-1.110000e+08,4.400000e+07
Unspecified loss provisions,17.0,3.205506e+07,3.376239e+07,0.000000e+00,1.099550e+08
Fund for assessment differences,19.0,9.836242e+07,1.010048e+08,0.000000e+00,3.350000e+08
Debt letters that can be refinanced in central banks,18.0,6.954100e+10,4.457683e+10,0.000000e+00,1.075710e+11
Own non-amortized certificates,5.0,3.800000e+06,8.497058e+06,0.000000e+00,1.900000e+07
Obligations,41.0,2.655723e+09,5.000367e+09,0.000000e+00,1.839700e+10
Gift fund,58.0,9.770736e+07,1.753718e+08,2.050000e+05,5.210000e+08
Reinsurance obligations,29.0,1.528950e+08,1.198432e+08,3.420000e+05,4.260000e+08
Total prepaid costs and unearned income received,32.0,4.116847e+08,5.977987e+08,6.200000e+04,1.578000e+09
Financial assets that are measured at amortized cost,33.0,1.508622e+10,2.675628e+10,0.000000e+00,6.165650e+10
Financial assets that are measured at fair value,33.0,3.250673e+10,3.133612e+10,0.000000e+00,7.726500e+10
Sum incurred costs and did not receive earned revenue,31.0,4.136323e+08,4.431742e+08,2.605690e+05,1.211000e+09
Provision for unearned gross premium,31.0,5.904398e+09,6.036971e+09,6.192490e+05,1.585100e+10
"Daughter enterprises, affiliated enterprises and jointly controlled enterprises",33.0,2.336892e+09,3.487148e+09,0.000000e+00,8.248800e+09
Earned revenue from operational activities,40.0,1.237577e+08,1.137059e+08,2.510000e+05,3.558820e+08
Realized gain and loss on investments,28.0,6.445582e+08,8.445538e+08,-2.378873e+06,1.920800e+09
Investments that are held to maturity,13.0,1.186006e+09,7.687735e+08,2.640700e+04,2.039792e+09
Other financial assets,17.0,8.722282e+09,9.279217e+09,1.516600e+07,1.826870e+10
Fund for changes in value,29.0,3.617210e+07,3.043336e+07,0.000000e+00,1.390000e+08
Net operating income from real estate,24.0,5.611868e+06,1.407483e+07,-2.576928e+06,6.801141e+07
Total replacement costs at your own expense,31.0,9.885554e+09,8.825442e+09,1.583134e+07,2.056900e+10
– Reinsurance share of gross premiums earned,30.0,6.800965e+08,4.891050e+08,4.235000e+06,1.403000e+09
Total premium income at your own expense,33.0,1.329182e+10,1.238671e+10,1.881393e+07,2.977000e+10
Other insurance-related income,31.0,4.977850e+08,6.625073e+08,-9.800000e+07,1.570000e+09
Other possessions denoted by their nature,14.0,3.873923e+08,2.620214e+08,3.000000e+06,7.420000e+08
Assets by tax,13.0,5.810674e+07,1.523179e+08,0.000000e+00,5.630000e+08
Intermediaries,6.0,3.976524e+07,3.818518e+07,4.859659e+06,7.636600e+07
Receivables in connection with reinsurance,22.0,2.734117e+08,1.495364e+08,1.052800e+07,4.260000e+08
Other prepaid costs and no income received,32.0,1.231722e+08,1.352743e+08,6.200000e+04,4.550000e+08
Sales costs,22.0,1.302587e+09,1.538241e+09,-4.056155e+06,3.508000e+09
Ordinary result after tax expense,49450.0,2.837221e+07,2.995886e+08,-2.902000e+09,1.322200e+10
Group contributions made,1808.0,2.445307e+07,2.816178e+08,-5.767690e+08,2.700000e+09
Other current liabilities,49128.0,1.381976e+08,1.864954e+09,-5.863360e+05,1.323320e+11
Investments in equities and shares,15901.0,2.763452e+07,5.414756e+08,-7.732639e+06,6.057286e+10
Total retained earnings,47832.0,2.345955e+08,3.967146e+09,-6.722015e+09,1.598200e+11
Other financial instruments,1438.0,4.013564e+08,3.960938e+09,-3.721000e+03,8.329900e+10
Annual results by minority interests,30039.0,3.919322e+07,1.720799e+09,-1.687000e+09,2.075027e+11
Total long-term debt,49439.0,2.092769e+08,3.378608e+09,-1.453714e+06,4.300610e+11
Total intangible assets,26925.0,1.312727e+08,1.864646e+09,-1.155000e+07,8.870800e+10
Tax payable,36352.0,7.673060e+06,7.036668e+07,-4.258106e+06,3.023000e+09
"Total bank deposits, cash and the like",48696.0,5.963984e+07,7.216958e+08,-3.855300e+07,4.812900e+10
Investment in subsidiaries,11035.0,2.908320e+08,2.072117e+09,-1.265072e+06,5.088500e+10
Holdings of own shares,2930.0,-1.397016e+08,3.428071e+09,-8.303800e+10,5.000000e+08
Shares and shares in enterprises in the same group,354.0,2.259259e+07,1.538611e+08,0.000000e+00,2.838947e+09
Ordinary profit before tax expense,49449.0,3.879216e+07,3.916718e+08,-2.202000e+09,1.923000e+10
Income from investments in subsidiaries and affiliates,5155.0,2.085583e+07,1.000045e+08,-9.540000e+08,3.361000e+09
Value reduction other financial instruments valued at fair value,960.0,2.054496e+06,8.438978e+06,-7.833100e+07,1.000000e+08
"Operating equipment, fixtures, tools, office machines and the like",43975.0,4.997194e+07,1.085698e+09,-1.602760e+05,5.955600e+10
Deferred tax assets,25824.0,1.296155e+07,9.699192e+07,-3.439003e+06,1.882000e+09
Other long-term debt,14527.0,2.636689e+08,2.261684e+09,-4.302540e+06,8.718400e+10
Other financial cost,31624.0,8.228339e+06,7.114879e+07,-1.880000e+08,2.797000e+09
Long-term corporate debt,3566.0,1.893639e+08,9.049179e+08,-2.884680e+05,1.864362e+10
Research and development,2210.0,2.953766e+08,2.577915e+09,-1.254000e+03,3.791600e+10
Change in inventory of self-made fixed assets,237.0,-1.316503e+07,2.261432e+08,-3.790000e+08,3.144468e+09
Bond loans,890.0,1.326694e+09,6.506222e+09,0.000000e+00,6.065300e+10
Basic capital,34.0,1.158148e+08,9.091178e+07,2.000000e+04,1.940000e+08
Purpose capital with statutory restrictions,21.0,1.008152e+07,3.349326e+06,7.000000e+03,1.114200e+07
Total invested purpose capital,32.0,1.198130e+08,9.147689e+07,2.000000e+04,1.940000e+08
Total purpose creationL,48.0,3.395416e+08,2.810448e+08,8.753815e+06,6.615370e+08
Fund issue,37.0,1.331814e+06,3.649078e+06,-1.200000e+06,2.000000e+07
Total depreciation of m.v. of fixed assets and intangible assets,146.0,4.203293e+08,7.675771e+08,0.000000e+00,2.103000e+09
Salary m.v.,146.0,2.547821e+09,3.911961e+09,0.000000e+00,1.042700e+10
Total dividends and other income from securities with variable returns,146.0,1.622471e+09,4.446548e+09,-3.818000e+06,1.704500e+10
result for the financial year prior to minority interests,146.0,5.128478e+09,8.035563e+09,-1.724000e+07,2.060000e+10
Repayment loans,96.0,1.383888e+11,3.115226e+11,8.321360e+08,1.507247e+12
Total other liabilities,146.0,9.274647e+10,1.909998e+11,0.000000e+00,7.050400e+11
Salary,144.0,2.546993e+09,3.940770e+09,9.175083e+06,1.042700e+10
Total interest costs and similar costs,146.0,4.031122e+09,6.694592e+09,3.991000e+03,1.837100e+10
Operating costs fixed properties,64.0,1.072406e+07,1.283327e+07,2.660000e+05,3.700000e+07
"Interest rates and similar income from certificates, bonds and other interest-bearing securities",109.0,1.261337e+09,2.259144e+09,-4.870000e+05,5.489000e+09
result of ordinary operations after tax,146.0,5.128188e+09,8.035737e+09,-1.724000e+07,2.060000e+10
No earnings received,75.0,1.098438e+08,4.755072e+08,1.009000e+06,2.930000e+09
Ownership interests in other group companies,93.0,3.076477e+10,5.187046e+10,0.000000e+00,1.182330e+11
Loans and deposits from credit institutions without an agreed maturity or notice period,83.0,1.649505e+10,4.710828e+10,0.000000e+00,1.661330e+11
Specified provisions on warranty liability,23.0,3.491005e+06,4.296952e+06,0.000000e+00,1.000000e+07
Operating income fixed properties,68.0,3.860538e+06,5.233523e+06,9.000000e+03,3.100000e+07
Other interest costs and similar costs,129.0,-4.462595e+08,1.548739e+09,-5.861000e+09,2.692000e+09
Interest and similar income from loans to and receivables from credit institutions,113.0,8.432812e+08,1.583726e+09,-5.435000e+06,3.879000e+09
Net change in value and gain/loss on equities and other securities with variable returns,103.0,1.167854e+09,2.166992e+09,-8.610000e+08,5.073000e+09
Tax on ordinary profit,139.0,1.417645e+09,2.151079e+09,-6.132000e+06,5.223000e+09
Total allocations and transfers,115.0,2.326024e+09,5.995842e+09,0.000000e+00,2.060000e+10
Perpetual responsible loan capital,76.0,3.530026e+09,4.551613e+09,0.000000e+00,1.411600e+10
Factoring,114.0,2.090467e+07,2.152305e+08,0.000000e+00,2.297186e+09
"Total shares, shares and other securities with variable returns",146.0,3.454217e+09,7.060549e+09,0.000000e+00,3.121600e+10
Other purpose capital,46.0,5.665291e+07,6.317211e+07,-3.199000e+06,2.034140e+08
Financial and investment income,47.0,1.040775e+07,1.108011e+07,2.152200e+04,2.353400e+07
Other assets,9.0,3.682704e+06,3.165372e+06,2.400000e+05,1.175800e+07
profit before tax expense,33.0,2.827821e+09,2.714964e+09,-3.742700e+07,6.139900e+09
Other purpose capital with externally imposed restrictions,35.0,4.892136e+07,3.245828e+07,0.000000e+00,1.437900e+08
Holdings of own shares/primary capital certificates,23.0,5.782000e+06,3.481156e+07,-4.000000e+06,1.653570e+08
Itemized loss provisions,17.0,4.615394e+07,9.493096e+07,0.000000e+00,2.970930e+08
Rental financing agreements (financial leasing),25.0,4.031487e+09,6.255811e+09,0.000000e+00,2.659736e+10
Margin deductions and other intercompany with customers,16.0,1.082066e+09,7.505375e+08,0.000000e+00,1.572000e+09
Responsible loan capital with associated conversion rights,12.0,4.797958e+07,4.830888e+07,0.000000e+00,1.500000e+08
Receivables factoring,6.0,3.955627e+08,9.320996e+08,0.000000e+00,2.297186e+09
Ownership interests in credit institutions,34.0,1.133403e+09,1.291520e+09,0.000000e+00,3.733000e+09
Liabilities in the event of deferred tax,27.0,5.141698e+08,3.754813e+08,2.570000e+05,9.054000e+08
Total insurance liabilities gross,31.0,2.763317e+10,2.543393e+10,8.001182e+06,6.210800e+10
Total responsible loan capital m.v.,27.0,8.745429e+08,9.776481e+08,0.000000e+00,2.567000e+09
Other retained earnings,33.0,9.598693e+09,9.705840e+09,-1.523950e+08,2.137000e+10
TOTAL EQUITY AND LIABILITIES,33.0,4.104111e+10,3.677939e+10,1.982566e+08,9.365300e+10
Reinsurance share of gross compensation provision,30.0,8.233493e+08,6.433739e+08,2.748182e+06,1.820000e+09
Receivables in connection with direct business,32.0,3.325913e+09,3.574139e+09,0.000000e+00,9.036000e+09
Purpose capital with externally imposed restrictions,33.0,8.563486e+06,1.782823e+07,-7.734100e+07,2.825000e+07
result of technical accounting,33.0,2.005572e+09,1.967748e+09,-3.829200e+07,4.406000e+09
Gross premiums earned,31.0,1.390958e+10,1.237995e+10,1.881393e+07,3.117300e+10
Insurance-related administration costs including 10 commissions for re-insurance received,30.0,1.223002e+09,1.195536e+09,0.000000e+00,2.973400e+09
Provision for the guarantee scheme,19.0,2.837365e+08,3.039366e+08,7.646840e+05,6.289000e+08
Holdings of own shares/equity certificates,8.0,-1.000000e+05,0.000000e+00,-1.000000e+05,-1.000000e+05
"Earned, undiscensed rental income",10.0,3.080756e+08,1.213645e+08,1.475600e+07,3.860000e+08
Facilities and equipment,31.0,1.021642e+08,1.183292e+08,7.510000e+04,2.925000e+08
Actuarial gains and losses on defined benefit pension schemes - benefits to employees,18.0,-8.172330e+07,7.694142e+07,-1.592000e+08,3.966733e+06
Payroll cost,48845.0,1.804071e+08,8.560428e+08,-3.394000e+09,4.655569e+10
Net ledger,49240.0,-9.109402e+05,1.556715e+08,-8.776000e+09,8.063000e+09
Tax expense on ordinary profit and loss,44965.0,9.320795e+06,1.187943e+08,-1.648000e+09,6.008000e+09
Uncovered loss,9940.0,1.365033e+07,1.631158e+08,-4.868780e+08,4.643000e+09
Accounts payable,48162.0,8.083442e+07,9.048251e+08,-4.066951e+06,5.526400e+10
Other receivables,48486.0,7.018639e+07,1.445701e+09,-2.233035e+06,7.771100e+10
Total invested equity,48978.0,1.559085e+08,2.636659e+09,-7.930500e+10,1.297050e+11
Total items,35463.0,1.104263e+08,9.653363e+08,-8.694996e+06,4.828700e+10
Market-based equities,1881.0,8.903666e+07,2.988998e+09,0.000000e+00,1.295370e+11
Loans to associated companies and jointly controlled enterprises,2655.0,1.343617e+07,4.897733e+07,-2.000000e+05,5.828361e+08
Total financial revenues,48895.0,8.626706e+06,1.127082e+08,-9.540000e+08,8.063000e+09
Other interest cost,40616.0,3.278247e+06,7.444462e+07,-1.266300e+07,5.025000e+09
Total transfers and availability,47676.0,2.124477e+07,2.916279e+08,-8.831000e+09,1.314700e+10
Interest income from enterprises in the same group,7868.0,2.942108e+06,1.268712e+07,-2.135000e+06,6.870000e+08
Total current assets,49452.0,3.335748e+08,4.063196e+09,-2.075746e+06,3.389600e+11
Total fixed assets,49452.0,4.243489e+08,4.766510e+09,-1.932728e+06,2.186140e+11
Merchandise,21775.0,1.595714e+08,1.224732e+09,-8.694996e+06,4.828700e+10
Other invested equity,13403.0,2.874816e+08,3.402552e+09,-6.453600e+07,1.087940e+11
"Licenses, patents, licenses, trademarks and similar rights",5858.0,1.220929e+08,8.775924e+08,0.000000e+00,1.643700e+10
Income on other investments,980.0,1.405325e+07,5.513000e+07,-1.503780e+08,9.030000e+08
Total fixed assets.1,46886.0,2.507373e+08,2.467379e+09,-1.348400e+04,9.056800e+10
Total current liabilities,49332.0,2.968778e+08,3.365408e+09,-8.437520e+05,1.795880e+11
Total equity,49583.0,3.810377e+08,5.141981e+09,-4.025783e+08,1.900770e+11
Total provisions for liabilities,24339.0,9.825223e+07,2.697361e+09,-1.659000e+06,4.057210e+11
Pledges,3111.0,6.485222e+07,5.420933e+08,-1.524100e+07,1.779300e+10
Total revenue,49081.0,9.018381e+08,5.694852e+09,-7.813400e+07,3.019140e+11
Sales revenue,48477.0,8.772559e+08,5.639250e+09,-4.308646e+06,3.019140e+11
Responsible loan capital,411.0,5.170547e+07,3.941948e+08,0.000000e+00,7.621000e+09
Deferred tax,25223.0,2.614029e+07,2.315254e+08,-8.204800e+04,6.494000e+09
Over-course,15034.0,5.584140e+07,1.212559e+09,-8.303800e+10,3.118700e+10
Total investments,5543.0,4.158953e+08,6.739783e+09,-3.721000e+03,3.265870e+11
Transfers to/from other equity,42639.0,1.442004e+07,2.930611e+08,-8.831000e+09,1.314700e+10

In [7]:
# Categorical Feature Statistics
cat_stats

                                                                                                   value  \
column                         rank
Checklist Content              1     Working agreements, HSE and working environment training for man...
                               2     Working agreements, Working hour schedules, Building and equipme...
                               3     HSE and working environment training for managers and worker rep...
                               4     Working agreements, HSE and working environment training for man...
                               5     HSE and working environment training for managers and worker rep...
County                         1                                                                   Viken
                               2                                                                    Oslo
                               3                                                                Vestland
                               4                                                               Trøndelag
                               5                                                                Rogaland
Currency code                  1                                                                     NOK
                               2                                                                    <NA>
                               3                                                                     EUR
                               4                                                                     SEK
                               5                                                                     USD
Fiscal accounting type         1                                                                   STORE
                               2                                                                    <NA>
                               3                                                                    BANK
                               4                                                                  IDEELL
                               5                                                                   SKADE
Industry Code                  1                                                                      43
                               2                                                                      41
                               3                                                                      47
                               4                                                                      56
                               5                                                                      49
Industry Main Area             1                                                            Construction
                               2     Wholesale and retail trade; repair of motor vehicles and motorcy...
                               3                                                           Manufacturing
                               4                               Accommodation and food service activities
                               5                                 Human health and social work activities
Industry Sub Area              1                                     Specialised construction activities
                               2                                               Construction of buildings
                               3                  Retail trade, except of motor vehicles and motorcycles
                               4                                    Food and beverage service activities
                               5                              Land transport and transport via pipelines
IsRegisteredEmploymentregister 1                                                                      Ja
                               2                                                                     Nei
                               3                                                           Not specified
IsRegisteredVATregister        1                                                                     Nei
                               2                                                                      Ja
                               3                                                           Not specified
NonCompliance                  1                                                                       1
                               2                                                                       0

                                     count    pct
column                         rank
Checklist Content              1      1892   2.97
                               2      1773   2.79
                               3      1645   2.59
                               4      1632   2.56
                               5      1611   2.53
County                         1     13746   21.6
                               2      7688  12.08
                               3      5773   9.07
                               4      5463   8.59
                               5      5358   8.42
Currency code                  1     49345  77.55
                               2     14003  22.01
                               3       113   0.18
                               4       106   0.17
                               5        56   0.09
Fiscal accounting type         1     49401  77.63
                               2     14003  22.01
                               3       146   0.23
                               4        48   0.08
                               5        31   0.05
Industry Code                  1      8786  13.81
                               2      8495  13.35
                               3      6439  10.12
                               4      5130   8.06
                               5      2196   3.45
Industry Main Area             1     18010   28.3
                               2     10382  16.32
                               3      7392  11.62
                               4      6392  10.04
                               5      5131   8.06
Industry Sub Area              1      8786  13.81
                               2      8495  13.35
                               3      6439  10.12
                               4      5130   8.06
                               5      2196   3.45
IsRegisteredEmploymentregister 1     55018  86.46
                               2      8614  13.54
                               3         2    0.0
IsRegisteredVATregister        1     53240  83.67
                               2     10392  16.33
                               3         2    0.0
NonCompliance                  1     47265  74.28
                               2     16369  25.72

In [8]:
# Target Distribution
target_df

               count    pct
NonCompliance
1              47265  74.28
0              16369  25.72

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019c341f-2374-74a2-9859-42d23baa891e
c783e21a1fa0b2e354b8a54af7da525100f43ec06731c6a87b8e00d4daeee897