### Dataset and Task Metadata

In [27]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="bank_customer_churn",
    dataset_year="2020",
    domain_str="business & marketing",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/datasets/gauravtopre/bank-customer-churn-dataset",
    download_description="""
We download the data from Kaggle to a .csv file in a predefined folder.
    
mkdir -p local-data-warehouse/bank_customer_churn && \
wget -O local-data-warehouse/bank_customer_churn/Bank_Customer_Churn_Prediction.csv "https://storage.googleapis.com/kagglesdsdata/datasets/2445309/4139805/Bank%20Customer%20Churn%20Prediction.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260323%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260323T150852Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=9507cfc667e1be2347054693a43390dcc4efd7f6dbcc3ab6dbce7074b27dec0777c74db069433476bf151b9d4fc0eea0e3d21561c29f4b045d53653d33e2f7bdb9828d504ea7c14a5b50f34d9fb6dcbbcca77cc77299c8722a40cf10de7f4929a29f789947d3dc31c03a70d955fcd9ea920c70c31466770f293df2beea1badacb57c746777bfca5dc8e98b20c25489d103bd7afb5bce570fa8547b857e887aedeed1ae12f0de51eb0e1b252684a9efa4c56e1913de0b955524d334fbec53ae383c1eb07cc453f881280857c07605f308269f59aaa906f4d013337988e73cad2e50a1e655b8359afaec243aedb4f4b59904b8a3eb82662a6203d2d805d5a4c4fc"
""",
    # References
    academic_reference_bibtex="""@misc{Topre2022BankCustomerChurn,
  title={Bank Customer Churn Dataset},
  author={Gaurav Topre},
  year={2022},
  publisher={Kaggle},
  url={https://www.kaggle.com/datasets/gauravtopre/bank-customer-churn-dataset}
}
""",
    academic_reference_bibtex_key="Topre2022BankCustomerChurn",
    license="Public Domain",
    data_tags=["IID"],
    curation_comments="""
        - We remove customer_id column.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="churn",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="churn",
)

## Preprocessing

In [28]:
import pandas as pd

df = pd.read_csv(dataset_mold.path / "Bank_Customer_Churn_Prediction.csv")

df["churn"] = df["churn"].map({1: "Yes", 0: "No"})

cat_cols = ["churn", "active_member", "country", "gender", "credit_card"]
df[cat_cols] = df[cat_cols].astype("category")

df = df.drop(columns=["customer_id"])

In [29]:
df.head()

,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,619,France,Female,42,2,0.00,1,1,1,101348.88,Yes
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,No
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,Yes
3,699,France,Female,39,1,0.00,2,0,0,93826.63,No
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,No

## Data Checks

In [30]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 10,000
Columns: 11
Use sampling: False (sample size: 10,000)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['estimated_salary', 'balance', 'credit_score', 'age', 'tenure', 'products_number', 'country', 'gender', 'credit_card', 'active_member']
Rows remaining as candidates after top-10 filter: 0 (of 10,000)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [31]:
# Sample Rows
df_head

,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,619,France,Female,42,2,0.00,1,1,1,101348.88,Yes
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,No
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,Yes
3,699,France,Female,39,1,0.00,2,0,0,93826.63,No
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,No

In [32]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,country,category,0.0,0.0,3.0,"France, Germany, Spain"
1,gender,category,0.0,0.0,2.0,"Male, Female"
2,credit_card,category,0.0,0.0,2.0,"1, 0"
3,active_member,category,0.0,0.0,2.0,"1, 0"
4,churn,category,0.0,0.0,2.0,"No, Yes"
5,balance,float64,0.0,0.0,6382.0,"0.0, 130170.82, 105473.74, 85304.27, 159397.75, 144238.7, 112262.84, 109106.8, 142147.32, 109109.33"
6,estimated_salary,float64,0.0,0.0,9999.0,"24924.92, 101348.88, 55313.44, 72500.68, 182692.8, 4993.94, 124964.82, 161971.42, 39488.04, 187811.71"
7,credit_score,int64,0.0,0.0,460.0,"850, 678, 655, 705, 667, 684, 670, 651, 683, 652"
8,age,int64,0.0,0.0,70.0,"37, 38, 35, 36, 34, 33, 40, 39, 32, 31"
9,tenure,int64,0.0,0.0,11.0,"2, 1, 7, 8, 5, 3, 4, 9, 6, 10"
10,products_number,int64,0.0,0.0,4.0,"1, 2, 3, 4"

In [33]:
# Numeric Feature Statistics
numeric_stats

                    count           mean           std     min        max
credit_score      10000.0     650.528800     96.653299  350.00     850.00
age               10000.0      38.921800     10.487806   18.00      92.00
tenure            10000.0       5.012800      2.892174    0.00      10.00
balance           10000.0   76485.889288  62397.405202    0.00  250898.09
products_number   10000.0       1.530200      0.581654    1.00       4.00
estimated_salary  10000.0  100090.239881  57510.492818   11.58  199992.48

In [34]:
# Categorical Feature Statistics
cat_stats

                      value  count    pct
column        rank
active_member 1           1   5151  51.51
              2           0   4849  48.49
churn         1          No   7963  79.63
              2         Yes   2037  20.37
country       1      France   5014  50.14
              2     Germany   2509  25.09
              3       Spain   2477  24.77
credit_card   1           1   7055  70.55
              2           0   2945  29.45
gender        1        Male   5457  54.57
              2      Female   4543  45.43

In [35]:
# Target Distribution
target_df

       count    pct
churn
No      7963  79.63
Yes     2037  20.37

## Task Curation

In [36]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=3, n_splits=3, test_size=None

In [37]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)


splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [38]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019d1b47-e503-7163-92c4-67c024b260f4
b9581d0e46fb782664a9efdf871e59a672b922ca33e2a5bbcfdd9d6a41002880