### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="biogeographical_ancestry_prediction",
    dataset_year="2025", # source data is older, but this version was created in 2025
    domain_str="biology & life sciences",
    # Data Source
    dataset_source="GitHub",
    original_dataset_source_download_link="https://github.com/CarolaHeinzel/BGA_Classification/blob/main/data/input_data/full_data.csv",
    download_description="""
We download the data from the GitHub repository and save it to a predefined folder.

mkdir -p local-data-warehouse/biogeographical_ancestry_prediction/ && curl -L -o local-data-warehouse/biogeographical_ancestry_prediction/filter_population.xlsx https://raw.githubusercontent.com/CarolaHeinzel/BGA-Classification/main/datat/filtered_population_eur_update.xlsx
""",
    # References
    academic_reference_bibtex=r"""@article{heinzel2025advancing,
  title={Advancing biogeographical ancestry predictions through machine learning},
  author={Heinzel, Carola Sophia and Purucker, Lennart and Hutter, Frank and Pfaffelhuber, Peter},
  journal={Forensic Science International: Genetics},
  volume={79},
  pages={103290},
  year={2025},
  publisher={Elsevier}
}
@article{ruiz2023development,
  title={Development and evaluations of the ancestry informative markers of the VISAGE Enhanced Tool for Appearance and Ancestry},
  author={Ruiz-Ram{\'\i}rez, Jorge and de La Puente, M and Xavier, Catarina and Ambroa-Conde, Adri{\'a}n and {\'A}lvarez-Dios, J and Freire-Aradas, A and Mosquera-Miguel, Ana and Ralf, Arwin and Amory, Christina and Katsara, Maria Alexandra and others},
  journal={Forensic Science International: Genetics},
  volume={64},
  pages={102853},
  year={2023},
  publisher={Elsevier}
}
@article{xavier2020development,
  title={Development and validation of the VISAGE AmpliSeq basic tool to predict appearance and ancestry from DNA},
  author={Xavier, Catarina and de la Puente, Maria and Mosquera-Miguel, Ana and Freire-Aradas, Ana and Kalamara, Vivian and Vidaki, Athina and Gross, Theresa E and Revoir, Andrew and Po{\'s}piech, Ewelina and Kartasi{\'n}ska, Ewa and others},
  journal={Forensic Science International: Genetics},
  volume={48},
  pages={102336},
  year={2020},
  publisher={Elsevier}
}
""",
    academic_reference_bibtex_key="heinzel2025advancing,ruiz2023development,xavier2020development",
    license="None", # Data from GitHub does not have a license, source is Apache-2.0 license (I think)
    data_tags=["IID"],
    curation_comments="""
We use this dataset as one of the most recent example of a machine learning task based on the Human Genome project.
We take the targets from the paper by Heinzel et al. (2025) and only rename the targets to be standardized and more concise.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Population",
    problem_type="multiclass_classification",
    objective_metric_name="log_loss",
    stratify_on="Population",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_excel(f"{dataset_mold.path}/filter_population.xlsx")
df = df.drop(
    columns=[
        "Unnamed: 1",
        "SNP-Indel with complex genotype listing in VCF (not compiled)",
        "Unnamed: 3",
        "Unnamed: 4",
        "ID",
    ],
)

column_map = {
    "Iberian population in Spain": "Spain (Iberian)",
    "Toscani in Italia": "Italy (Toscani)",
    "Finnish in Finland": "Finland (Finnish)",
    "Utah Residents (CEPH) with N & W European ancestry": "Utah (CEPH, N/W European ancestry)",
    "British in England and Scotland": "UK (England & Scotland, British)",
    "13. Italy - Sardinian": "Italy (Sardinian)",
    "11. France - French": "France (French)",
    "Turkey": "Turkey",
    "09. Russia - Russian": "Russia (Russian)",
    "10. France - French Basque": "France (Basque)"
}
df["Population"] = df["Population"].map(column_map)

for col in df.columns:
    df[col] = df[col].astype("category")
    
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 635
Columns: 105
Use sampling: False (sample size: 635)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['rs1398461', 'rs17287498', 'rs12629397', 'rs6504633', 'rs392461', 'rs393953', 'rs408046', 'rs2737126', 'rs5030240', 'rs2585339']
Rows remaining as candidates after top-10 filter: 0 (of 635)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,Population,rs1024124,rs1040934,rs1074689,rs10764919,rs10954737,rs10962599,rs1150911,rs11960137,rs1197062,rs12142199,rs1229984,rs12405776,rs12498138,rs12594144,rs12629397,rs12880237,rs12913832,rs1317026,rs13280988,rs1371048,rs1382568,rs1398461,rs1426654,rs1495085,rs1545397,rs1567803,rs1592672,rs166054,rs16891982,rs17086288,rs17130385,rs17287498,rs1757928,rs17625895,rs1796048,rs182857716,rs1871534,rs1924381,rs2024566,rs2026999,rs2156208,rs2196051,rs234623,rs2375771,rs2387842,rs2472304,rs2585339,rs2605361,rs262037,rs2715883,rs2737126,rs2789823,rs2814778,rs2835133,rs310362,rs367953206,rs3737576,rs3751050,rs3827760,rs3844336,rs3852253,rs3857620,rs3862700,rs392461,rs393953,rs408046,rs4308478,rs4465645,rs4471745,rs4540055,rs4657449,rs4737753,rs487750,rs5030240,rs556365,rs6088466,rs6437783,rs6496996,rs6504633,rs6588145,rs6701640,rs6754311,rs6894681,rs6933094,rs7151991,rs7171818,rs7252391,rs7594173,rs776912,rs7816786,rs7975017,rs7989291,rs8072587,rs809540,rs848461,rs881929,rs914468,rs9467370,rs9479657,rs9522149,rs9817359,rs9845503,rs9847307,rs9899480
0,Russia (Russian),CT,CT,AA,AA,TT,CC,GT,CC,GT,AA,CC,CC,GG,CC,TT,GG,GG,CC,AG,TT,CG,AG,AA,AA,AA,CT,GT,GG,GG,TT,GG,AC,AA,AA,CC,AA,GG,CC,AA,TT,CC,AG,AG,CG,CG,AG,GT,GT,CC,AA,CT,AA,TT,CC,TT,TT,TT,TT,AA,AA,AA,GG,TT,AG,AG,AG,TT,TT,GG,AC,GG,CC,TT,CC,AT,GG,TT,GG,CT,GG,AC,CC,AA,TT,GG,AA,AG,AG,AC,CT,CC,AG,GG,TT,CT,TT,CG,CC,CC,CC,GG,AG,TT,CC
1,"UK (England & Scotland, British)",CT,TT,AT,AA,CT,CT,GG,CC,TT,AA,CC,CC,GG,CC,GT,AA,AG,CC,AA,GG,CC,GG,AA,AA,AA,TT,TT,GG,GG,TT,GG,CT,AA,CC,CC,AA,GG,CC,AG,CT,CC,AA,AG,CC,CC,GG,GT,GT,CT,GG,CT,AA,TT,CC,CT,TT,TT,TT,AA,AA,AA,GG,TT,CG,AA,AT,TT,TT,GG,AA,GG,CC,CT,CC,GG,GG,TT,AG,TT,GT,AC,CT,AA,TT,AG,AG,AA,AG,AC,TT,CT,AC,GG,TT,CT,GT,CG,CC,CC,CC,GG,AA,TT,CC
2,Italy (Toscani),CT,CT,AA,AA,TT,TT,GT,CC,TT,AA,CT,CC,GG,AC,CG,GG,AA,CC,AA,GG,CG,GG,AA,AA,AA,CT,TT,GG,GG,TT,GG,CT,AC,CC,CC,AA,GG,CT,GG,TT,CT,AA,AG,CG,CT,AA,TT,GG,CC,AA,CG,AA,TT,CC,TT,TT,TT,TT,AA,AG,AG,GG,TT,CG,AG,GG,CT,TT,GG,AT,GG,CT,CC,CG,GT,AG,TT,AG,TT,TT,CC,CC,AA,CT,AG,TT,AA,AA,AT,CT,CC,CG,CG,GT,CT,TT,CG,CC,CT,CC,GG,AA,TT,CC
3,"UK (England & Scotland, British)",CT,CT,AA,AA,TT,TT,GT,CC,TT,AA,CC,CC,GG,CC,TT,AG,AG,CC,AA,GG,CC,GG,AA,AA,AA,TT,TT,GG,GG,TT,GG,AC,AA,AA,CC,AA,GG,CC,GG,TT,CT,AA,GG,CC,CT,AG,TT,TT,CC,AA,CC,AA,TT,AC,CT,TT,CT,CT,AA,AA,AA,GG,TT,CC,AG,AA,TT,TT,GG,AA,GG,CC,CT,CC,AT,GG,TT,AG,CT,GT,CC,CT,AA,TT,GG,GG,AG,AA,AA,TT,CC,AG,GG,CT,CC,GG,GG,CC,CC,CC,GG,AA,TT,CT
4,"UK (England & Scotland, British)",CT,TT,TT,GG,TT,TT,CG,CG,TT,AA,CC,CC,GG,CC,GT,GG,GG,CC,AG,GG,GG,AG,AA,AA,AT,TT,TT,GG,GG,TT,GG,TT,AC,AC,CT,AA,GG,CC,GG,CT,CC,AG,GG,GG,TT,AA,TT,GT,CC,AA,GG,AA,TT,CC,CT,TT,TT,TT,AA,AA,AA,GG,TT,GG,GG,GG,TT,TT,GG,AT,GG,CC,CC,CG,AT,AG,CT,AG,TT,TT,CC,CT,AA,TT,AG,GT,GG,AA,AA,CT,CC,AC,GG,TT,CT,GT,GG,CC,CC,CC,GG,AT,TT,CC

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Population,category,0.0,0.0,10.0,"Spain (Iberian), Italy (Toscani), Utah (CEPH, N/W European ancestry), Finland (Finnish), UK (England & Scotland, British), France (French), Turkey, Italy (Sardinian), Russia (Russian), France (Basque)"
1,rs1024124,category,0.0,0.0,3.0,"CT, CC, TT"
2,rs1040934,category,0.0,0.0,3.0,"TT, CT, CC"
3,rs1074689,category,0.0,0.0,6.0,"AA, AT, AC, TT, CT, CC"
4,rs10764919,category,0.0,0.0,3.0,"AG, AA, GG"
5,rs10954737,category,0.0,0.0,3.0,"TT, CT, NN"
6,rs10962599,category,0.0,0.0,3.0,"TT, CT, CC"
7,rs1150911,category,0.0,0.0,6.0,"GT, GG, CG, CT, TT, CC"
8,rs11960137,category,0.0,0.0,3.0,"CC, CG, GG"
9,rs1197062,category,0.0,0.0,3.0,"TT, GT, GG"
10,rs12142199,category,0.0,0.0,4.0,"AA, AG, GG, NN"
11,rs1229984,category,0.0,0.0,3.0,"CC, CT, TT"
12,rs12405776,category,0.0,0.0,2.0,"CC, CT"
13,rs12498138,category,0.0,0.0,2.0,"GG, AG"
14,rs12594144,category,0.0,0.0,3.0,"CC, AC, AA"
15,rs12629397,category,0.0,0.0,7.0,"GT, TT, GG, CG, CT, CC, NN"
16,rs12880237,category,0.0,0.0,3.0,"AG, GG, AA"
17,rs12913832,category,0.0,0.0,4.0,"GG, AG, AA, NN"
18,rs1317026,category,0.0,0.0,3.0,"CC, CT, TT"
19,rs13280988,category,0.0,0.0,3.0,"AG, AA, GG"
20,rs1371048,category,0.0,0.0,3.0,"GT, GG, TT"
21,rs1382568,category,0.0,0.0,6.0,"GG, CG, AG, AC, CC, AA"
22,rs1398461,category,0.0,0.0,7.0,"AG, AC, AA, CG, GG, CC, NN"
23,rs1426654,category,0.0,0.0,2.0,"AA, AG"
24,rs1495085,category,0.0,0.0,3.0,"AA, AG, GG"
25,rs1545397,category,0.0,0.0,3.0,"AA, AT, TT"
26,rs1567803,category,0.0,0.0,3.0,"CT, TT, CC"
27,rs1592672,category,0.0,0.0,3.0,"TT, GT, GG"
28,rs166054,category,0.0,0.0,3.0,"GG, GT, TT"
29,rs16891982,category,0.0,0.0,3.0,"GG, CG, CC"
30,rs17086288,category,0.0,0.0,2.0,"TT, CT"
31,rs17130385,category,0.0,0.0,4.0,"GG, GT, NN, TT"
32,rs17287498,category,0.0,0.0,7.0,"CC, CT, AC, AT, TT, AA, NN"
33,rs1757928,category,0.0,0.0,3.0,"AA, AC, CC"
34,rs17625895,category,0.0,0.0,3.0,"AC, AA, CC"
35,rs1796048,category,0.0,0.0,3.0,"CC, CT, TT"
36,rs182857716,category,0.0,0.0,3.0,"AA, NN, AG"
37,rs1871534,category,0.0,0.0,3.0,"GG, CG, NN"
38,rs1924381,category,0.0,0.0,3.0,"CC, CT, TT"
39,rs2024566,category,0.0,0.0,4.0,"AA, AG, GG, NN"
40,rs2026999,category,0.0,0.0,3.0,"TT, CT, CC"
41,rs2156208,category,0.0,0.0,3.0,"CT, CC, TT"
42,rs2196051,category,0.0,0.0,3.0,"AA, AG, GG"
43,rs234623,category,0.0,0.0,3.0,"AG, GG, AA"
44,rs2375771,category,0.0,0.0,6.0,"CG, GG, CC, GT, CT, TT"
45,rs2387842,category,0.0,0.0,6.0,"CT, TT, CC, GT, CG, GG"
46,rs2472304,category,0.0,0.0,3.0,"AG, AA, GG"
47,rs2585339,category,0.0,0.0,6.0,"TT, GT, GG, CT, CG, NN"
48,rs2605361,category,0.0,0.0,6.0,"GT, GG, TT, AG, AT, NN"
49,rs262037,category,0.0,0.0,3.0,"CC, CT, TT"
50,rs2715883,category,0.0,0.0,3.0,"AA, AG, GG"
51,rs2737126,category,0.0,0.0,7.0,"CT, CC, CG, GT, TT, GG, NN"
52,rs2789823,category,0.0,0.0,3.0,"AA, AG, NN"
53,rs2814778,category,0.0,0.0,3.0,"TT, CT, NN"
54,rs2835133,category,0.0,0.0,3.0,"CC, AC, AA"
55,rs310362,category,0.0,0.0,4.0,"CT, TT, CC, NN"
56,rs367953206,category,0.0,0.0,2.0,"TT, NN"
57,rs3737576,category,0.0,0.0,3.0,"TT, CT, CC"
58,rs3751050,category,0.0,0.0,3.0,"TT, CT, CC"
59,rs3827760,category,0.0,0.0,2.0,"AA, AG"
60,rs3844336,category,0.0,0.0,3.0,"AA, AG, GG"
61,rs3852253,category,0.0,0.0,3.0,"AA, AG, GG"
62,rs3857620,category,0.0,0.0,2.0,"GG, AG"
63,rs3862700,category,0.0,0.0,3.0,"TT, GT, GG"
64,rs392461,category,0.0,0.0,7.0,"CG, GG, CC, AC, AG, AA, NN"
65,rs393953,category,0.0,0.0,7.0,"AG, GG, GT, AA, AT, TT, NN"
66,rs408046,category,0.0,0.0,7.0,"AG, GG, AA, GT, AT, NN, TT"
67,rs4308478,category,0.0,0.0,3.0,"TT, CT, CC"
68,rs4465645,category,0.0,0.0,2.0,"TT, CT"
69,rs4471745,category,0.0,0.0,3.0,"GG, AG, AA"
70,rs4540055,category,0.0,0.0,6.0,"AA, AT, TT, AC, CT, CC"
71,rs4657449,category,0.0,0.0,3.0,"GG, AG, AA"
72,rs4737753,category,0.0,0.0,4.0,"CC, CT, TT, NN"
73,rs487750,category,0.0,0.0,3.0,"CT, CC, TT"
74,rs5030240,category,0.0,0.0,7.0,"CC, CG, AC, GG, AG, AA, NN"
75,rs556365,category,0.0,0.0,6.0,"AT, TT, AA, GT, AG, GG"
76,rs6088466,category,0.0,0.0,4.0,"GG, AG, AA, NN"
77,rs6437783,category,0.0,0.0,3.0,"TT, CT, CC"
78,rs6496996,category,0.0,0.0,3.0,"GG, AG, AA"
79,rs6504633,category,0.0,0.0,7.0,"TT, CT, GT, CG, CC, GG, AG"
80,rs6588145,category,0.0,0.0,6.0,"GT, GG, TT, AG, AT, AA"
81,rs6701640,category,0.0,0.0,3.0,"CC, AC, AA"
82,rs6754311,category,0.0,0.0,3.0,"CT, CC, TT"
83,rs6894681,category,0.0,0.0,3.0,"AA, AG, NN"
84,rs6933094,category,0.0,0.0,5.0,"TT, CT, AT, CC, AC"
85,rs7151991,category,0.0,0.0,3.0,"GG, AG, AA"
86,rs7171818,category,0.0,0.0,6.0,"AG, AA, AT, GT, GG, TT"
87,rs7252391,category,0.0,0.0,3.0,"AA, AG, GG"
88,rs7594173,category,0.0,0.0,4.0,"AA, AG, GG, NN"
89,rs776912,category,0.0,0.0,6.0,"AA, AC, AT, CT, TT, CC"
90,rs7816786,category,0.0,0.0,4.0,"CT, TT, CC, NN"
91,rs7975017,category,0.0,0.0,4.0,"CC, CT, TT, NN"
92,rs7989291,category,0.0,0.0,6.0,"AC, CG, CC, AG, AA, GG"
93,rs8072587,category,0.0,0.0,3.0,"GG, CG, CC"
94,rs809540,category,0.0,0.0,6.0,"TT, CT, GT, CG, CC, GG"
95,rs848461,category,0.0,0.0,3.0,"CT, CC, TT"
96,rs881929,category,0.0,0.0,4.0,"GT, GG, TT, NN"
97,rs914468,category,0.0,0.0,4.0,"CG, GG, CC, GT"
98,rs9467370,category,0.0,0.0,3.0,"CC, AC, NN"
99,rs9479657,category,0.0,0.0,3.0,"CC, CT, TT"
100,rs9522149,category,0.0,0.0,3.0,"CC, CT, TT"
101,rs9817359,category,0.0,0.0,2.0,"GG, AG"
102,rs9845503,category,0.0,0.0,6.0,"AA, AG, AT, GT, GG, TT"
103,rs9847307,category,0.0,0.0,2.0,"TT, AT"
104,rs9899480,category,0.0,0.0,4.0,"CC, CT, TT, NN"

In [6]:
# Numeric Feature Statistics
numeric_stats

'No numeric features to summarize.'

In [7]:
# Categorical Feature Statistics
cat_stats

                                               value  count    pct
column      rank
Population  1                        Spain (Iberian)    107  16.85
            2                        Italy (Toscani)    107  16.85
            3     Utah (CEPH, N/W European ancestry)     99  15.59
            4                      Finland (Finnish)     99  15.59
            5       UK (England & Scotland, British)     91  14.33
rs1024124   1                                     CT    321  50.55
            2                                     CC    193  30.39
            3                                     TT    121  19.06
rs1040934   1                                     TT    378  59.53
            2                                     CT    212  33.39
            3                                     CC     45   7.09
rs1074689   1                                     AA    262  41.26
            2                                     AT    232  36.54
            3                                     AC     59   9.29
            4                                     TT     57   8.98
            5                                     CT     23   3.62
rs10764919  1                                     AG    284  44.72
            2                                     AA    234  36.85
            3                                     GG    117  18.43
rs10954737  1                                     TT    578  91.02
            2                                     CT     47   7.40
            3                                     NN     10   1.57
rs10962599  1                                     TT    323  50.87
            2                                     CT    255  40.16
            3                                     CC     57   8.98
rs1150911   1                                     GT    195  30.71
            2                                     GG    149  23.46
            3                                     CG     99  15.59
            4                                     CT     92  14.49
            5                                     TT     74  11.65
rs11960137  1                                     CC    469  73.86
            2                                     CG    149  23.46
            3                                     GG     17   2.68
rs1197062   1                                     TT    579  91.18
            2                                     GT     55   8.66
            3                                     GG      1   0.16
rs12142199  1                                     AA    406  63.94
            2                                     AG    197  31.02
            3                                     GG     31   4.88
            4                                     NN      1   0.16
rs1229984   1                                     CC    584  91.97
            2                                     CT     49   7.72
            3                                     TT      2   0.31
rs12405776  1                                     CC    605  95.28
            2                                     CT     30   4.72
rs12498138  1                                     GG    550  86.61
            2                                     AG     85  13.39
rs12594144  1                                     CC    474  74.65
            2                                     AC    152  23.94
            3                                     AA      9   1.42
rs12629397  1                                     GT    274  43.15
            2                                     TT    187  29.45
            3                                     GG    111  17.48
            4                                     CG     34   5.35
            5                                     CT     26   4.09
rs12880237  1                                     AG    288  45.35
            2                                     GG    271  42.68
            3                                     AA     76  11.97
rs12913832  1                                     GG    263  41.42
            2                                     AG    229  36.06
            3                                     AA    142  22.36
            4                                     NN      1   0.16
rs1317026   1                                     CC    604  95.12
            2                                     CT     30   4.72
            3                                     TT      1   0.16
rs13280988  1                                     AG    289  45.51
            2                                     AA    249  39.21
            3                                     GG     97  15.28
rs1371048   1                                     GT    292  45.98
            2                                     GG    269  42.36
            3                                     TT     74  11.65
rs1382568   1                                     GG    191  30.08
            2                                     CG    163  25.67
            3                                     AG    137  21.57
            4                                     AC     72  11.34
            5                                     CC     42   6.61
rs1398461   1                                     AG    206  32.44
            2                                     AC    128  20.16
            3                                     AA    118  18.58
            4                                     CG     90  14.17
            5                                     GG     72  11.34
rs1426654   1                                     AA    629  99.06
            2                                     AG      6   0.94
rs1495085   1                                     AA    559  88.03
            2                                     AG     75  11.81
            3                                     GG      1   0.16
rs1545397   1                                     AA    537  84.57
            2                                     AT     91  14.33
            3                                     TT      7   1.10
rs1567803   1                                     CT    286  45.04
            2                                     TT    274  43.15
            3                                     CC     75  11.81
rs1592672   1                                     TT    498  78.43
            2                                     GT    128  20.16
            3                                     GG      9   1.42
rs166054    1                                     GG    613  96.54
            2                                     GT     20   3.15
            3                                     TT      2   0.31
rs16891982  1                                     GG    531  83.62
            2                                     CG     90  14.17
            3                                     CC     14   2.20
rs17086288  1                                     TT    631  99.37
            2                                     CT      4   0.63
rs17130385  1                                     GG    553  87.09
            2                                     GT     80  12.60
            3                                     NN      1   0.16
            4                                     TT      1   0.16
rs17287498  1                                     CC    217  34.17
            2                                     CT    161  25.35
            3                                     AC    139  21.89
            4                                     AT     59   9.29
            5                                     TT     28   4.41
rs1757928   1                                     AA    417  65.67
            2                                     AC    195  30.71
            3                                     CC     23   3.62
rs17625895  1                                     AC    287  45.20
            2                                     AA    183  28.82
            3                                     CC    165  25.98
rs1796048   1                                     CC    372  58.58
            2                                     CT    225  35.43
            3                                     TT     38   5.98
rs182857716 1                                     AA    630  99.21
            2                                     NN      3   0.47
            3                                     AG      2   0.31
rs1871534   1                                     GG    627  98.74
            2                                     CG      7   1.10
            3                                     NN      1   0.16
rs1924381   1                                     CC    471  74.17
            2                                     CT    159  25.04
            3                                     TT      5   0.79
rs2024566   1                                     AA    295  46.46
            2                                     AG    269  42.36
            3                                     GG     70  11.02
            4                                     NN      1   0.16
rs2026999   1                                     TT    288  45.35
            2                                     CT    278  43.78
            3                                     CC     69  10.87
rs2156208   1                                     CT    313  49.29
            2                                     CC    186  29.29
            3                                     TT    136  21.42
rs2196051   1                                     AA    312  49.13
            2                                     AG    271  42.68
            3                                     GG     52   8.19
rs234623    1                                     AG    318  50.08
            2                                     GG    159  25.04
            3                                     AA    158  24.88
rs2375771   1                                     CG    255  40.16
            2                                     GG    225  35.43
            3                                     CC     62   9.76
            4                                     GT     54   8.50
            5                                     CT     33   5.20
rs2387842   1                                     CT    234  36.85
            2                                     TT    162  25.51
            3                                     CC    112  17.64
            4                                     GT     68  10.71
            5                                     CG     55   8.66
rs2472304   1                                     AG    278  43.78
            2                                     AA    241  37.95
            3                                     GG    116  18.27
rs2585339   1                                     TT    368  57.95
            2                                     GT    210  33.07
            3                                     GG     35   5.51
            4                                     CT     13   2.05
            5                                     CG      8   1.26
rs2605361   1                                     GT    267  42.05
            2                                     GG    246  38.74
            3                                     TT     84  13.23
            4                                     AG     27   4.25
            5                                     AT     10   1.57
rs262037    1                                     CC    551  86.77
            2                                     CT     81  12.76
            3                                     TT      3   0.47
rs2715883   1                                     AA    313  49.29
            2                                     AG    254  40.00
            3                                     GG     68  10.71
rs2737126   1                                     CT    168  26.46
            2                                     CC    155  24.41
            3                                     CG    123  19.37
            4                                     GT    102  16.06
            5                                     TT     44   6.93
rs2789823   1                                     AA    625  98.43
            2                                     AG      7   1.10
            3                                     NN      3   0.47
rs2814778   1                                     TT    627  98.74
            2                                     CT      7   1.10
            3                                     NN      1   0.16
rs2835133   1                                     CC    571  89.92
            2                                     AC     61   9.61
            3                                     AA      3   0.47
rs310362    1                                     CT    288  45.35
            2                                     TT    252  39.69
            3                                     CC     94  14.80
            4                                     NN      1   0.16
rs367953206 1                                     TT    625  98.43
            2                                     NN     10   1.57
rs3737576   1                                     TT    569  89.61
            2                                     CT     65  10.24
            3                                     CC      1   0.16
rs3751050   1                                     TT    498  78.43
            2                                     CT    134  21.10
            3                                     CC      3   0.47
rs3827760   1                                     AA    621  97.80
            2                                     AG     14   2.20
rs3844336   1                                     AA    480  75.59
            2                                     AG    139  21.89
            3                                     GG     16   2.52
rs3852253   1                                     AA    574  90.39
            2                                     AG     58   9.13
            3                                     GG      3   0.47
rs3857620   1                                     GG    611  96.22
            2                                     AG     24   3.78
rs3862700   1                                     TT    526  82.83
            2                                     GT     99  15.59
            3                                     GG     10   1.57
rs392461    1                                     CG    304  47.87
            2                                     GG    174  27.40
            3                                     CC    142  22.36
            4                                     AC      7   1.10
            5                                     AG      6   0.94
rs393953    1                                     AG    214  33.70
            2                                     GG    209  32.91
            3                                     GT     90  14.17
            4                                     AA     68  10.71
            5                                     AT     40   6.30
rs408046    1                                     AG    275  43.31
            2                                     GG    180  28.35
            3                                     AA    100  15.75
            4                                     GT     45   7.09
            5                                     AT     33   5.20
rs4308478   1                                     TT    524  82.52
            2                                     CT    106  16.69
            3                                     CC      5   0.79
rs4465645   1                                     TT    611  96.22
            2                                     CT     24   3.78
rs4471745   1                                     GG    567  89.29
            2                                     AG     64  10.08
            3                                     AA      4   0.63
rs4540055   1                                     AA    329  51.81
            2                                     AT    200  31.50
            3                                     TT     53   8.35
            4                                     AC     31   4.88
            5                                     CT     20   3.15
rs4657449   1                                     GG    496  78.11
            2                                     AG    134  21.10
            3                                     AA      5   0.79
rs4737753   1                                     CC    550  86.61
            2                                     CT     81  12.76
            3                                     TT      3   0.47
            4                                     NN      1   0.16
rs487750    1                                     CT    285  44.88
            2                                     CC    222  34.96
            3                                     TT    128  20.16
rs5030240   1                                     CC    295  46.46
            2                                     CG    199  31.34
            3                                     AC     74  11.65
            4                                     GG     39   6.14
            5                                     AG     20   3.15
rs556365    1                                     AT    249  39.21
            2                                     TT    158  24.88
            3                                     AA    108  17.01
            4                                     GT     59   9.29
            5                                     AG     53   8.35
rs6088466   1                                     GG    286  45.04
            2                                     AG    275  43.31
            3                                     AA     73  11.50
            4                                     NN      1   0.16
rs6437783   1                                     TT    443  69.76
            2                                     CT    178  28.03
            3                                     CC     14   2.20
rs6496996   1                                     GG    418  65.83
            2                                     AG    193  30.39
            3                                     AA     24   3.78
rs6504633   1                                     TT    362  57.01
            2                                     CT    159  25.04
            3                                     GT     71  11.18
            4                                     CG     19   2.99
            5                                     CC     18   2.83
rs6588145   1                                     GT    283  44.57
            2                                     GG    208  32.76
            3                                     TT    106  16.69
            4                                     AG     21   3.31
            5                                     AT     16   2.52
rs6701640   1                                     CC    440  69.29
            2                                     AC    184  28.98
            3                                     AA     11   1.73
rs6754311   1                                     CT    228  35.91
            2                                     CC    227  35.75
            3                                     TT    180  28.35
rs6894681   1                                     AA    619  97.48
            2                                     AG     15   2.36
            3                                     NN      1   0.16
rs6933094   1                                     TT    391  61.57
            2                                     CT    171  26.93
            3                                     AT     50   7.87
            4                                     CC     15   2.36
            5                                     AC      8   1.26
rs7151991   1                                     GG    421  66.30

In [8]:
# Target Distribution
target_df

                                    count    pct
Population
Spain (Iberian)                       107  16.85
Italy (Toscani)                       107  16.85
Utah (CEPH, N/W European ancestry)     99  15.59
Finland (Finnish)                      99  15.59
UK (England & Scotland, British)       91  14.33
France (French)                        28   4.41
Turkey                                 28   4.41
Italy (Sardinian)                      28   4.41
Russia (Russian)                       25   3.94
France (Basque)                        23   3.62

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=20, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to biogeographical_ancestry_prediction/019d7374-b899-714c-9372-37a48f580b0f
019d7374-b899-714c-9372-37a48f580b0f
bab4155061902f0f65763080f1103c2149ec7325f690d35ac845c732dc9ad6dd