### Dataset and Task Metadata

In [103]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="hiva_agnostic",
    dataset_year="2007",
    domain_str="chemistry & material science",
    # Data Source
    dataset_source="Other",
    original_dataset_source_download_link="https://doi.org/10.1109/IJCNN.2007.4371065",
    download_description="""
We download the dataset from the challenge platform into predefined folder:
    
mkdir -p local-data-warehouse/hiva_agnostic/ && \
wget -P local-data-warehouse/hiva_agnostic/ https://www.agnostic.inf.ethz.ch/datasets/DataAgnos/HIVA.zip && \
wget -P local-data-warehouse/hiva_agnostic/ https://www.agnostic.inf.ethz.ch/datasets/ValidAgnos.zip && \
unzip local-data-warehouse/hiva_agnostic/HIVA.zip -d local-data-warehouse/hiva_agnostic/ && \
unzip local-data-warehouse/hiva_agnostic/ValidAgnos.zip -d local-data-warehouse/hiva_agnostic/ && \
rm local-data-warehouse/hiva_agnostic/HIVA.zip && \
rm local-data-warehouse/hiva_agnostic/ValidAgnos.zip
""",
    # References
    academic_reference_bibtex="""@inproceedings{guyon2007agnostic,
  author={Isabelle Guyon and Amir Saffari and Gideon Dror and Gavin Cawley},
  booktitle={2007 International Joint Conference on Neural Networks}, 
  title={Agnostic Learning vs. Prior Knowledge Challenge}, 
  year={2007},
  pages={829-834},
  doi={10.1109/IJCNN.2007.4371065}
}
""",
    academic_reference_bibtex_key="guyon2007agnostic",
    license="Public Domain",
    data_tags=["IID"],
    curation_comments="""
        - We merge files containing attributes and labels for training and validation datasets and then merge the two DataFrames into one.
        - We remove 136 duplicated columns and one empty string column.  
        - Anomalies: large imbalance between the two classes (96.5% vs 3.5%)
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="CompoundActive",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="CompoundActive",
)

## Preprocessing

In [104]:
import pandas as pd

# train data
df_train = pd.read_csv(dataset_mold.path / "HIVA/hiva_train.data", header=None, sep=" ")
df_train.columns = [
    f"molecule_structure_property_{i + 1}" for i in range(len(df_train.columns))
]

df_y_train = pd.read_csv(dataset_mold.path / "HIVA/hiva_train.labels", header=None)
target_feature = "CompoundActive"
df_train[target_feature] = df_y_train[0]


# val data
df_valid = pd.read_csv(dataset_mold.path / "HIVA/hiva_valid.data", header=None, sep=" ")
df_valid.columns = [
    f"molecule_structure_property_{i + 1}" for i in range(len(df_valid.columns))
]

df_y_valid = pd.read_csv(dataset_mold.path / "Agnostic/hiva_valid.labels", header=None)
target_feature = "CompoundActive"
df_valid[target_feature] = df_y_valid[0]

# merge train and valid sets
df = pd.concat([df_train, df_valid], ignore_index=True)
df[target_feature] = df[target_feature].map({-1: "No", 1: "Yes"}).astype("category")

# duplicated columns and NaN column
df.drop(columns=[
    "molecule_structure_property_1618",
    "molecule_structure_property_287",
    "molecule_structure_property_748",
    "molecule_structure_property_117",
    "molecule_structure_property_119",
    "molecule_structure_property_127",
    "molecule_structure_property_113",
    "molecule_structure_property_108",
    "molecule_structure_property_410",
    "molecule_structure_property_509",
    "molecule_structure_property_103",
    "molecule_structure_property_138",
    "molecule_structure_property_144",
    "molecule_structure_property_122",
    "molecule_structure_property_104",
    "molecule_structure_property_132",
    "molecule_structure_property_791",
    "molecule_structure_property_120",
    "molecule_structure_property_157",
    "molecule_structure_property_120",
    "molecule_structure_property_100",
    "molecule_structure_property_937",
    "molecule_structure_property_175",
    "molecule_structure_property_111",
    "molecule_structure_property_139",
    "molecule_structure_property_112",
    "molecule_structure_property_667",
    "molecule_structure_property_851",
    "molecule_structure_property_152",
    "molecule_structure_property_711",
    "molecule_structure_property_147",
    "molecule_structure_property_142",
    "molecule_structure_property_710",
    "molecule_structure_property_103",
    "molecule_structure_property_320",
    "molecule_structure_property_842",
    "molecule_structure_property_112",
    "molecule_structure_property_699",
    "molecule_structure_property_796",
    "molecule_structure_property_107",
    "molecule_structure_property_120",
    "molecule_structure_property_933",
    "molecule_structure_property_554",
    "molecule_structure_property_941",
    "molecule_structure_property_110",
    "molecule_structure_property_420",
    "molecule_structure_property_734",
    "molecule_structure_property_145",
    "molecule_structure_property_147",
    "molecule_structure_property_59",
    "molecule_structure_property_114",
    "molecule_structure_property_136",
    "molecule_structure_property_780",
    "molecule_structure_property_533",
    "molecule_structure_property_131",
    "molecule_structure_property_701",
    "molecule_structure_property_137",
    "molecule_structure_property_143",
    "molecule_structure_property_108",
    "molecule_structure_property_542",
    "molecule_structure_property_158",
    "molecule_structure_property_638",
    "molecule_structure_property_143",
    "molecule_structure_property_147",
    "molecule_structure_property_132",
    "molecule_structure_property_574",
    "molecule_structure_property_407",
    "molecule_structure_property_746",
    "molecule_structure_property_146",
    "molecule_structure_property_928",
    "molecule_structure_property_504",
    "molecule_structure_property_989",
    "molecule_structure_property_141",
    "molecule_structure_property_130",
    "molecule_structure_property_829",
    "molecule_structure_property_264",
    "molecule_structure_property_116",
    "molecule_structure_property_925",
    "molecule_structure_property_123",
    "molecule_structure_property_633",
    "molecule_structure_property_100",
    "molecule_structure_property_105",
    "molecule_structure_property_813",
    "molecule_structure_property_548",
    "molecule_structure_property_155",
    "molecule_structure_property_139",
    "molecule_structure_property_112",
    "molecule_structure_property_114",
    "molecule_structure_property_288",
    "molecule_structure_property_478",
    "molecule_structure_property_519",
    "molecule_structure_property_415",
    "molecule_structure_property_140",
    "molecule_structure_property_724",
    "molecule_structure_property_145",
    "molecule_structure_property_107",
    "molecule_structure_property_376",
    "molecule_structure_property_332",
    "molecule_structure_property_159",
    "molecule_structure_property_128",
    "molecule_structure_property_159",
    "molecule_structure_property_155",
    "molecule_structure_property_102",  
    "molecule_structure_property_1175",
    "molecule_structure_property_1191",
    "molecule_structure_property_1272",
    "molecule_structure_property_1086",
    "molecule_structure_property_1035",
    "molecule_structure_property_1481",
    "molecule_structure_property_1223",
    "molecule_structure_property_1049",
    "molecule_structure_property_1325",
    "molecule_structure_property_1205",
    "molecule_structure_property_1576",
    "molecule_structure_property_1209",
    "molecule_structure_property_1006",
    "molecule_structure_property_1124",
    "molecule_structure_property_1523",
    "molecule_structure_property_1472",
    "molecule_structure_property_472",
    "molecule_structure_property_1031",
    "molecule_structure_property_1075",
    "molecule_structure_property_1208",
    "molecule_structure_property_1108",
    "molecule_structure_property_1054",
    "molecule_structure_property_1455",
    "molecule_structure_property_1475",
    "molecule_structure_property_1142",
    "molecule_structure_property_1367",
    "molecule_structure_property_1314",
    "molecule_structure_property_1373",
    "molecule_structure_property_1430",
    "molecule_structure_property_1194",
    "molecule_structure_property_1582",
    "molecule_structure_property_1432",
    "molecule_structure_property_1471",
    "molecule_structure_property_1322",
    "molecule_structure_property_1468",
    "molecule_structure_property_1307",
    "molecule_structure_property_1167",
    "molecule_structure_property_1236",
    "molecule_structure_property_1000",
    "molecule_structure_property_1050",
    "molecule_structure_property_1552",
    "molecule_structure_property_1398",
    "molecule_structure_property_1127",
    "molecule_structure_property_1140",
    "molecule_structure_property_1409",
    "molecule_structure_property_1458",
    "molecule_structure_property_1070",
    "molecule_structure_property_1598",
    "molecule_structure_property_1281",
    "molecule_structure_property_1599",
    "molecule_structure_property_1556",
    "molecule_structure_property_1029",
], inplace=True)

df = df.sample(frac=1, random_state=11).reset_index(drop=True)

## Data Checks

In [105]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 4,229
Columns: 1481
Use sampling: False (sample size: 4,229)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['molecule_structure_property_1080', 'molecule_structure_property_1090', 'molecule_structure_property_1089', 'molecule_structure_property_1088', 'molecule_structure_property_1087', 'molecule_structure_property_1085', 'molecule_structure_property_1084', 'molecule_structure_property_1083', 'molecule_structure_property_1082', 'molecule_structure_property_1081']
Rows remaining as candidates after top-10 filter: 4,203 (of 4,229)

#### Duplicate Report
Total duplicate rows: 23 (0.54% of dataset)
Duplicate rows ignoring target: 23 (0.54% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [106]:
# Sample Rows
df_head

,molecule_structure_property_1,molecule_structure_property_2,molecule_structure_property_3,molecule_structure_property_4,molecule_structure_property_5,molecule_structure_property_6,molecule_structure_property_7,molecule_structure_property_8,molecule_structure_property_9,molecule_structure_property_10,molecule_structure_property_11,molecule_structure_property_12,molecule_structure_property_13,molecule_structure_property_14,molecule_structure_property_15,molecule_structure_property_16,molecule_structure_property_17,molecule_structure_property_18,molecule_structure_property_19,molecule_structure_property_20,molecule_structure_property_21,molecule_structure_property_22,molecule_structure_property_23,molecule_structure_property_24,molecule_structure_property_25,molecule_structure_property_26,molecule_structure_property_27,molecule_structure_property_28,molecule_structure_property_29,molecule_structure_property_30,molecule_structure_property_31,molecule_structure_property_32,molecule_structure_property_33,molecule_structure_property_34,molecule_structure_property_35,molecule_structure_property_36,molecule_structure_property_37,molecule_structure_property_38,molecule_structure_property_39,molecule_structure_property_40,molecule_structure_property_41,molecule_structure_property_42,molecule_structure_property_43,molecule_structure_property_44,molecule_structure_property_45,molecule_structure_property_46,molecule_structure_property_47,molecule_structure_property_48,molecule_structure_property_49,molecule_structure_property_50,molecule_structure_property_51,molecule_structure_property_52,molecule_structure_property_53,molecule_structure_property_54,molecule_structure_property_55,molecule_structure_property_56,molecule_structure_property_57,molecule_structure_property_58,molecule_structure_property_60,molecule_structure_property_61,molecule_structure_property_62,molecule_structure_property_63,molecule_structure_property_64,molecule_structure_property_65,molecule_structure_property_66,molecule_structure_property_67,molecule_structure_property_68,molecule_structure_property_69,molecule_structure_property_70,molecule_structure_property_71,molecule_structure_property_72,molecule_structure_property_73,molecule_structure_property_74,molecule_structure_property_75,molecule_structure_property_76,molecule_structure_property_77,molecule_structure_property_78,molecule_structure_property_79,molecule_structure_property_80,molecule_structure_property_81,molecule_structure_property_82,molecule_structure_property_83,molecule_structure_property_84,molecule_structure_property_85,molecule_structure_property_86,molecule_structure_property_87,molecule_structure_property_88,molecule_structure_property_89,molecule_structure_property_90,molecule_structure_property_91,molecule_structure_property_92,molecule_structure_property_93,molecule_structure_property_94,molecule_structure_property_95,molecule_structure_property_96,molecule_structure_property_97,molecule_structure_property_98,molecule_structure_property_99,molecule_structure_property_101,molecule_structure_property_106,molecule_structure_property_109,molecule_structure_property_115,molecule_structure_property_118,molecule_structure_property_121,molecule_structure_property_124,molecule_structure_property_125,molecule_structure_property_126,molecule_structure_property_129,molecule_structure_property_133,molecule_structure_property_134,molecule_structure_property_135,molecule_structure_property_148,molecule_structure_property_149,molecule_structure_property_150,molecule_structure_property_151,molecule_structure_property_153,molecule_structure_property_154,molecule_structure_property_156,molecule_structure_property_160,molecule_structure_property_161,molecule_structure_property_162,molecule_structure_property_163,molecule_structure_property_164,molecule_structure_property_165,molecule_structure_property_166,molecule_structure_property_167,molecule_structure_property_168,molecule_structure_property_169,molecule_structure_property_170,molecule_structure_property_171,molecule_structure_property_172,molecule_structure_property_173,molecule_structure_property_174,molecule_structure_property_176,molecule_structure_property_177,molecule_structure_property_178,molecule_structure_property_179,molecule_structure_property_180,molecule_structure_property_181,molecule_structure_property_182,molecule_structure_property_183,molecule_structure_property_184,molecule_structure_property_185,molecule_structure_property_186,molecule_structure_property_187,molecule_structure_property_188,molecule_structure_property_189,molecule_structure_property_190,molecule_structure_property_191,molecule_structure_property_192,molecule_structure_property_193,molecule_structure_property_194,molecule_structure_property_195,molecule_structure_property_196,molecule_structure_property_197,molecule_structure_property_198,molecule_structure_property_199,molecule_structure_property_200,molecule_structure_property_201,molecule_structure_property_202,molecule_structure_property_203,molecule_structure_property_204,molecule_structure_property_205,molecule_structure_property_206,molecule_structure_property_207,molecule_structure_property_208,molecule_structure_property_209,molecule_structure_property_210,molecule_structure_property_211,molecule_structure_property_212,molecule_structure_property_213,molecule_structure_property_214,molecule_structure_property_215,molecule_structure_property_216,molecule_structure_property_217,molecule_structure_property_218,molecule_structure_property_219,molecule_structure_property_220,molecule_structure_property_221,molecule_structure_property_222,molecule_structure_property_223,molecule_structure_property_224,molecule_structure_property_225,molecule_structure_property_226,molecule_structure_property_227,molecule_structure_property_228,molecule_structure_property_229,molecule_structure_property_230,molecule_structure_property_231,molecule_structure_property_232,molecule_structure_property_233,molecule_structure_property_234,molecule_structure_property_235,molecule_structure_property_236,molecule_structure_property_237,molecule_structure_property_238,molecule_structure_property_239,molecule_structure_property_240,molecule_structure_property_241,molecule_structure_property_242,molecule_structure_property_243,molecule_structure_property_244,molecule_structure_property_245,molecule_structure_property_246,molecule_structure_property_247,molecule_structure_property_248,molecule_structure_property_249,molecule_structure_property_250,molecule_structure_property_251,molecule_structure_property_252,molecule_structure_property_253,molecule_structure_property_254,molecule_structure_property_255,molecule_structure_property_256,molecule_structure_property_257,molecule_structure_property_258,molecule_structure_property_259,molecule_structure_property_260,molecule_structure_property_261,molecule_structure_property_262,molecule_structure_property_263,molecule_structure_property_265,molecule_structure_property_266,molecule_structure_property_267,molecule_structure_property_268,molecule_structure_property_269,molecule_structure_property_270,molecule_structure_property_271,molecule_structure_property_272,molecule_structure_property_273,molecule_structure_property_274,molecule_structure_property_275,molecule_structure_property_276,molecule_structure_property_277,molecule_structure_property_278,molecule_structure_property_279,molecule_structure_property_280,molecule_structure_property_281,molecule_structure_property_282,molecule_structure_property_283,molecule_structure_property_284,molecule_structure_property_285,molecule_structure_property_286,molecule_structure_property_289,molecule_structure_property_290,molecule_structure_property_291,molecule_structure_property_292,molecule_structure_property_293,molecule_structure_property_294,molecule_structure_property_295,molecule_structure_property_296,molecule_structure_property_297,molecule_structure_property_298,molecule_structure_property_299,molecule_structure_property_300,molecule_structure_property_301,molecule_structure_property_302,molecule_structure_property_303,molecule_structure_property_304,molecule_structure_property_305,molecule_structure_property_306,molecule_structure_property_307,molecule_structure_property_308,molecule_structure_property_309,molecule_structure_property_310,molecule_structure_property_311,molecule_structure_property_312,molecule_structure_property_313,molecule_structure_property_314,molecule_structure_property_315,molecule_structure_property_316,molecule_structure_property_317,molecule_structure_property_318,molecule_structure_property_319,molecule_structure_property_321,molecule_structure_property_322,molecule_structure_property_323,molecule_structure_property_324,molecule_structure_property_325,molecule_structure_property_326,molecule_structure_property_327,molecule_structure_property_328,molecule_structure_property_329,molecule_structure_property_330,molecule_structure_property_331,molecule_structure_property_333,molecule_structure_property_334,molecule_structure_property_335,molecule_structure_property_336,molecule_structure_property_337,molecule_structure_property_338,molecule_structure_property_339,molecule_structure_property_340,molecule_structure_property_341,molecule_structure_property_342,molecule_structure_property_343,molecule_structure_property_344,molecule_structure_property_345,molecule_structure_property_346,molecule_structure_property_347,molecule_structure_property_348,molecule_structure_property_349,molecule_structure_property_350,molecule_structure_property_351,molecule_structure_property_352,molecule_structure_property_353,molecule_structure_property_354,molecule_structure_property_355,molecule_structure_property_356,molecule_structure_property_357,molecule_structure_property_358,molecule_structure_property_359,molecule_structure_property_360,molecule_structure_property_361,molecule_structure_property_362,molecule_structure_property_363,molecule_structure_property_364,molecule_structure_property_365,molecule_structure_property_366,molecule_structure_property_367,molecule_structure_property_368,molecule_structure_property_369,molecule_structure_property_370,molecule_structure_property_371,molecule_structure_property_372,molecule_structure_property_373,molecule_structure_property_374,molecule_structure_property_375,molecule_structure_property_377,molecule_structure_property_378,molecule_structure_property_379,molecule_structure_property_380,molecule_structure_property_381,molecule_structure_property_382,molecule_structure_property_383,molecule_structure_property_384,molecule_structure_property_385,molecule_structure_property_386,molecule_structure_property_387,molecule_structure_property_388,molecule_structure_property_389,molecule_structure_property_390,molecule_structure_property_391,molecule_structure_property_392,molecule_structure_property_393,molecule_structure_property_394,molecule_structure_property_395,molecule_structure_property_396,molecule_structure_property_397,molecule_structure_property_398,molecule_structure_property_399,molecule_structure_property_400,molecule_structure_property_401,molecule_structure_property_402,molecule_structure_property_403,molecule_structure_property_404,molecule_structure_property_405,molecule_structure_property_406,molecule_structure_property_408,molecule_structure_property_409,molecule_structure_property_411,molecule_structure_property_412,molecule_structure_property_413,molecule_structure_property_414,molecule_structure_property_416,molecule_structure_property_417,molecule_structure_property_418,molecule_structure_property_419,molecule_structure_property_421,molecule_structure_property_422,molecule_structure_property_423,molecule_structure_property_424,molecule_structure_property_425,molecule_structure_property_426,molecule_structure_property_427,molecule_structure_property_428,molecule_structure_property_429,molecule_structure_property_430,molecule_structure_property_431,molecule_structure_property_432,molecule_structure_property_433,molecule_structure_property_434,molecule_structure_property_435,molecule_structure_property_436,molecule_structure_property_437,molecule_structure_property_438,molecule_structure_property_439,molecule_structure_property_440,molecule_structure_property_441,molecule_structure_property_442,molecule_structure_property_443,molecule_structure_property_444,molecule_structure_property_445,molecule_structure_property_446,molecule_structure_property_447,molecule_structure_property_448,molecule_structure_property_449,molecule_structure_property_450,molecule_structure_property_451,molecule_structure_property_452,molecule_structure_property_453,molecule_structure_property_454,molecule_structure_property_455,molecule_structure_property_456,molecule_structure_property_457,molecule_structure_property_458,molecule_structure_property_459,molecule_structure_property_460,molecule_structure_property_461,molecule_structure_property_462,molecule_structure_property_463,molecule_structure_property_464,molecule_structure_property_465,molecule_structure_property_466,molecule_structure_property_467,molecule_structure_property_468,molecule_structure_property_469,molecule_structure_property_470,molecule_structure_property_471,molecule_structure_property_473,molecule_structure_property_474,molecule_structure_property_475,molecule_structure_property_476,molecule_structure_property_477,molecule_structure_property_479,molecule_structure_property_480,molecule_structure_property_481,molecule_structure_property_482,molecule_structure_property_483,molecule_structure_property_484,molecule_structure_property_485,molecule_structure_property_486,molecule_structure_property_487,molecule_structure_property_488,molecule_structure_property_489,molecule_structure_property_490,molecule_structure_property_491,molecule_structure_property_492,molecule_structure_property_493,molecule_structure_property_494,molecule_structure_property_495,molecule_structure_property_496,molecule_structure_property_497,molecule_structure_property_498,molecule_structure_property_499,molecule_structure_property_500,molecule_structure_property_501,molecule_structure_property_502,molecule_structure_property_503,molecule_structure_property_505,molecule_structure_property_506,molecule_structure_property_507,molecule_structure_property_508,molecule_structure_property_510,molecule_structure_property_511,molecule_structure_property_512,molecule_structure_property_513,molecule_structure_property_514,molecule_structure_property_515,molecule_structure_property_516,molecule_structure_property_517,molecule_structure_property_518,molecule_structure_property_520,molecule_structure_property_521,molecule_structure_property_522,molecule_structure_property_523,molecule_structure_property_524,molecule_structure_property_525,molecule_structure_property_526,molecule_structure_property_527,molecule_structure_property_528,molecule_structure_property_529,molecule_structure_property_530,molecule_structure_property_531,molecule_structure_property_532,molecule_structure_property_534,molecule_structure_property_535,molecule_structure_property_536,molecule_structure_property_537,molecule_structure_property_538,molecule_structure_property_539,molecule_structure_property_540,molecule_structure_property_541,molecule_structure_property_543,molecule_structure_property_544,molecule_structure_property_545,molecule_structure_property_546,molecule_structure_property_547,molecule_structure_property_549,molecule_structure_property_550,molecule_structure_property_551,molecule_structure_property_552,molecule_structure_property_553,molecule_structure_property_555,molecule_structure_property_556,molecule_structure_property_557,molecule_structure_property_558,molecule_structure_property_559,molecule_structure_property_560,molecule_structure_property_561,molecule_structure_property_562,molecule_structure_property_563,molecule_structure_property_564,molecule_structure_property_565,molecule_structure_property_566,molecule_structure_property_567,molecule_structure_property_568,molecule_structure_property_569,molecule_structure_property_570,molecule_structure_property_571,molecule_structure_property_572,molecule_structure_property_573,molecule_structure_property_575,molecule_structure_property_576,molecule_structure_property_577,molecule_structure_property_578,molecule_structure_property_579,molecule_structure_property_580,molecule_structure_property_581,molecule_structure_property_582,molecule_structure_property_583,molecule_structure_property_584,molecule_structure_property_585,molecule_structure_property_586,molecule_structure_property_587,molecule_structure_property_588,molecule_structure_property_589,molecule_structure_property_590,molecule_structure_property_591,molecule_structure_property_592,molecule_structure_property_593,molecule_structure_property_594,molecule_structure_property_595,molecule_structure_property_596,molecule_structure_property_597,molecule_structure_property_598,molecule_structure_property_599,molecule_structure_property_600,molecule_structure_property_601,molecule_structure_property_602,molecule_structure_property_603,molecule_structure_property_604,molecule_structure_property_605,molecule_structure_property_606,molecule_structure_property_607,molecule_structure_property_608,molecule_structure_property_609,molecule_structure_property_610,molecule_structure_property_611,molecule_structure_property_612,molecule_structure_property_613,molecule_structure_property_614,molecule_structure_property_615,molecule_structure_property_616,molecule_structure_property_617,molecule_structure_property_618,molecule_structure_property_619,molecule_structure_property_620,molecule_structure_property_621,molecule_structure_property_622,molecule_structure_property_623,molecule_structure_property_624,molecule_structure_property_625,molecule_structure_property_626,molecule_structure_property_627,molecule_structure_property_628,molecule_structure_property_629,molecule_structure_property_630,molecule_structure_property_631,molecule_structure_property_632,molecule_structure_property_634,molecule_structure_property_635,molecule_structure_property_636,molecule_structure_property_637,molecule_structure_property_639,molecule_structure_property_640,molecule_structure_property_641,molecule_structure_property_642,molecule_structure_property_643,molecule_structure_property_644,molecule_structure_property_645,molecule_structure_property_646,molecule_structure_property_647,molecule_structure_property_648,molecule_structure_property_649,molecule_structure_property_650,molecule_structure_property_651,molecule_structure_property_652,molecule_structure_property_653,molecule_structure_property_654,molecule_structure_property_655,molecule_structure_property_656,molecule_structure_property_657,molecule_structure_property_658,molecule_structure_property_659,molecule_structure_property_660,molecule_structure_property_661,molecule_structure_property_662,molecule_structure_property_663,molecule_structure_property_664,molecule_structure_property_665,molecule_structure_property_666,molecule_structure_property_668,molecule_structure_property_669,molecule_structure_property_670,molecule_structure_property_671,molecule_structure_property_672,molecule_structure_property_673,molecule_structure_property_674,molecule_structure_property_675,molecule_structure_property_676,molecule_structure_property_677,molecule_structure_property_678,molecule_structure_property_679,molecule_structure_property_680,molecule_structure_property_681,molecule_structure_property_682,molecule_structure_property_683,molecule_structure_property_684,molecule_structure_property_685,molecule_structure_property_686,molecule_structure_property_687,molecule_structure_property_688,molecule_structure_property_689,molecule_structure_property_690,molecule_structure_property_691,molecule_structure_property_692,molecule_structure_property_693,molecule_s

In [107]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,CompoundActive,category,0.0,0.0,2.0,"No, Yes"
1,molecule_structure_property_1,int64,0.0,0.0,2.0,"0, 1"
2,molecule_structure_property_2,int64,0.0,0.0,2.0,"0, 1"
3,molecule_structure_property_3,int64,0.0,0.0,2.0,"0, 1"
4,molecule_structure_property_4,int64,0.0,0.0,2.0,"0, 1"
5,molecule_structure_property_5,int64,0.0,0.0,2.0,"0, 1"
6,molecule_structure_property_6,int64,0.0,0.0,2.0,"0, 1"
7,molecule_structure_property_7,int64,0.0,0.0,2.0,"0, 1"
8,molecule_structure_property_8,int64,0.0,0.0,2.0,"0, 1"
9,molecule_structure_property_9,int64,0.0,0.0,2.0,"0, 1"
10,molecule_structure_property_10,int64,0.0,0.0,2.0,"0, 1"
11,molecule_structure_property_11,int64,0.0,0.0,2.0,"0, 1"
12,molecule_structure_property_12,int64,0.0,0.0,2.0,"0, 1"
13,molecule_structure_property_13,int64,0.0,0.0,2.0,"0, 1"
14,molecule_structure_property_14,int64,0.0,0.0,2.0,"0, 1"
15,molecule_structure_property_15,int64,0.0,0.0,2.0,"0, 1"
16,molecule_structure_property_16,int64,0.0,0.0,2.0,"0, 1"
17,molecule_structure_property_17,int64,0.0,0.0,2.0,"0, 1"
18,molecule_structure_property_18,int64,0.0,0.0,2.0,"0, 1"
19,molecule_structure_property_19,int64,0.0,0.0,2.0,"0, 1"
20,molecule_structure_property_20,int64,0.0,0.0,2.0,"0, 1"
21,molecule_structure_property_21,int64,0.0,0.0,2.0,"0, 1"
22,molecule_structure_property_22,int64,0.0,0.0,2.0,"0, 1"
23,molecule_structure_property_23,int64,0.0,0.0,2.0,"0, 1"
24,molecule_structure_property_24,int64,0.0,0.0,2.0,"0, 1"
25,molecule_structure_property_25,int64,0.0,0.0,2.0,"0, 1"
26,molecule_structure_property_26,int64,0.0,0.0,2.0,"0, 1"
27,molecule_structure_property_27,int64,0.0,0.0,2.0,"0, 1"
28,molecule_structure_property_28,int64,0.0,0.0,2.0,"0, 1"
29,molecule_structure_property_29,int64,0.0,0.0,2.0,"0, 1"
30,molecule_structure_property_30,int64,0.0,0.0,2.0,"0, 1"
31,molecule_structure_property_31,int64,0.0,0.0,2.0,"0, 1"
32,molecule_structure_property_32,int64,0.0,0.0,2.0,"0, 1"
33,molecule_structure_property_33,int64,0.0,0.0,2.0,"0, 1"
34,molecule_structure_property_34,int64,0.0,0.0,2.0,"0, 1"
35,molecule_structure_property_35,int64,0.0,0.0,2.0,"0, 1"
36,molecule_structure_property_36,int64,0.0,0.0,2.0,"0, 1"
37,molecule_structure_property_37,int64,0.0,0.0,2.0,"0, 1"
38,molecule_structure_property_38,int64,0.0,0.0,2.0,"0, 1"
39,molecule_structure_property_39,int64,0.0,0.0,2.0,"0, 1"
40,molecule_structure_property_40,int64,0.0,0.0,2.0,"0, 1"
41,molecule_structure_property_41,int64,0.0,0.0,2.0,"0, 1"
42,molecule_structure_property_42,int64,0.0,0.0,2.0,"0, 1"
43,molecule_structure_property_43,int64,0.0,0.0,2.0,"0, 1"
44,molecule_structure_property_44,int64,0.0,0.0,2.0,"0, 1"
45,molecule_structure_property_45,int64,0.0,0.0,2.0,"0, 1"
46,molecule_structure_property_46,int64,0.0,0.0,2.0,"0, 1"
47,molecule_structure_property_47,int64,0.0,0.0,2.0,"0, 1"
48,molecule_structure_property_48,int64,0.0,0.0,2.0,"0, 1"
49,molecule_structure_property_49,int64,0.0,0.0,2.0,"0, 1"
50,molecule_structure_property_50,int64,0.0,0.0,2.0,"0, 1"
51,molecule_structure_property_51,int64,0.0,0.0,2.0,"0, 1"
52,molecule_structure_property_52,int64,0.0,0.0,2.0,"0, 1"
53,molecule_structure_property_53,int64,0.0,0.0,2.0,"0, 1"
54,molecule_structure_property_54,int64,0.0,0.0,2.0,"0, 1"
55,molecule_structure_property_55,int64,0.0,0.0,2.0,"0, 1"
56,molecule_structure_property_56,int64,0.0,0.0,2.0,"0, 1"
57,molecule_structure_property_57,int64,0.0,0.0,2.0,"0, 1"
58,molecule_structure_property_58,int64,0.0,0.0,2.0,"0, 1"
59,molecule_structure_property_60,int64,0.0,0.0,2.0,"0, 1"
60,molecule_structure_property_61,int64,0.0,0.0,2.0,"0, 1"
61,molecule_structure_property_62,int64,0.0,0.0,2.0,"0, 1"
62,molecule_structure_property_63,int64,0.0,0.0,2.0,"0, 1"
63,molecule_structure_property_64,int64,0.0,0.0,2.0,"0, 1"
64,molecule_structure_property_65,int64,0.0,0.0,2.0,"0, 1"
65,molecule_structure_property_66,int64,0.0,0.0,2.0,"1, 0"
66,molecule_structure_property_67,int64,0.0,0.0,2.0,"0, 1"
67,molecule_structure_property_68,int64,0.0,0.0,2.0,"0, 1"
68,molecule_structure_property_69,int64,0.0,0.0,2.0,"1, 0"
69,molecule_structure_property_70,int64,0.0,0.0,2.0,"0, 1"
70,molecule_structure_property_71,int64,0.0,0.0,2.0,"0, 1"
71,molecule_structure_property_72,int64,0.0,0.0,2.0,"0, 1"
72,molecule_structure_property_73,int64,0.0,0.0,2.0,"0, 1"
73,molecule_structure_property_74,int64,0.0,0.0,2.0,"0, 1"
74,molecule_structure_property_75,int64,0.0,0.0,2.0,"0, 1"
75,molecule_structure_property_76,int64,0.0,0.0,2.0,"0, 1"
76,molecule_structure_property_77,int64,0.0,0.0,2.0,"0, 1"
77,molecule_structure_property_78,int64,0.0,0.0,2.0,"0, 1"
78,molecule_structure_property_79,int64,0.0,0.0,2.0,"0, 1"
79,molecule_structure_property_80,int64,0.0,0.0,2.0,"0, 1"
80,molecule_structure_property_81,int64,0.0,0.0,2.0,"0, 1"
81,molecule_structure_property_82,int64,0.0,0.0,2.0,"0, 1"
82,molecule_structure_property_83,int64,0.0,0.0,2.0,"0, 1"
83,molecule_structure_property_84,int64,0.0,0.0,2.0,"0, 1"
84,molecule_structure_property_85,int64,0.0,0.0,2.0,"0, 1"
85,molecule_structure_property_86,int64,0.0,0.0,2.0,"0, 1"
86,molecule_structure_property_87,int64,0.0,0.0,2.0,"0, 1"
87,molecule_structure_property_88,int64,0.0,0.0,2.0,"0, 1"
88,molecule_structure_property_89,int64,0.0,0.0,2.0,"0, 1"
89,molecule_structure_property_90,int64,0.0,0.0,2.0,"0, 1"
90,molecule_structure_property_91,int64,0.0,0.0,2.0,"0, 1"
91,molecule_structure_property_92,int64,0.0,0.0,2.0,"0, 1"
92,molecule_structure_property_93,int64,0.0,0.0,2.0,"0, 1"
93,molecule_structure_property_94,int64,0.0,0.0,2.0,"0, 1"
94,molecule_structure_property_95,int64,0.0,0.0,2.0,"0, 1"
95,molecule_structure_property_96,int64,0.0,0.0,2.0,"0, 1"
96,molecule_structure_property_97,int64,0.0,0.0,2.0,"0, 1"
97,molecule_structure_property_98,int64,0.0,0.0,2.0,"0, 1"
98,molecule_structure_property_99,int64,0.0,0.0,2.0,"0, 1"
99,molecule_structure_property_101,int64,0.0,0.0,2.0,"0, 1"
100,molecule_structure_property_106,int64,0.0,0.0,2.0,"0, 1"
101,molecule_structure_property_109,int64,0.0,0.0,2.0,"0, 1"
102,molecule_structure_property_115,int64,0.0,0.0,2.0,"0, 1"
103,molecule_structure_property_118,int64,0.0,0.0,2.0,"0, 1"
104,molecule_structure_property_121,int64,0.0,0.0,2.0,"0, 1"
105,molecule_structure_property_124,int64,0.0,0.0,2.0,"0, 1"
106,molecule_structure_property_125,int64,0.0,0.0,2.0,"1, 0"
107,molecule_structure_property_126,int64,0.0,0.0,2.0,"0, 1"
108,molecule_structure_property_129,int64,0.0,0.0,2.0,"0, 1"
109,molecule_structure_property_133,int64,0.0,0.0,2.0,"0, 1"
110,molecule_structure_property_134,int64,0.0,0.0,2.0,"0, 1"
111,molecule_structure_property_135,int64,0.0,0.0,2.0,"0, 1"
112,molecule_structure_property_148,int64,0.0,0.0,2.0,"0, 1"
113,molecule_structure_property_149,int64,0.0,0.0,2.0,"0, 1"
114,molecule_structure_property_150,int64,0.0,0.0,2.0,"0, 1"
115,molecule_structure_property_151,int64,0.0,0.0,2.0,"0, 1"
116,molecule_structure_property_153,int64,0.0,0.0,2.0,"0, 1"
117,molecule_structure_property_154,int64,0.0,0.0,2.0,"0, 1"
118,molecule_structure_property_156,int64,0.0,0.0,2.0,"0, 1"
119,molecule_structure_property_160,int64,0.0,0.0,2.0,"0, 1"
120,molecule_structure_property_161,int64,0.0,0.0,2.0,"0, 1"
121,molecule_structure_property_162,int64,0.0,0.0,2.0,"0, 1"
122,molecule_structure_property_163,int64,0.0,0.0,2.0,"0, 1"
123,molecule_structure_property_164,int64,0.0,0.0,2.0,"0, 1"
124,molecule_structure_property_165,int64,0.0,0.0,2.0,"0, 1"
125,molecule_structure_property_166,int64,0.0,0.0,2.0,"0, 1"
126,molecule_structure_property_167,int64,0.0,0.0,2.0,"0, 1"
127,molecule_structure_property_168,int64,0.0,0.0,2.0,"0, 1"
128,molecule_structure_property_169,int64,0.0,0.0,2.0,"0, 1"
129,molecule_structure_property_170,int64,0.0,0.0,2.0,"0, 1"
130,molecule_structure_property_171,int64,0.0,0.0,2.0,"0, 1"
131,molecule_structure_property_172,int64,0.0,0.0,2.0,"0, 1"
132,molecule_structure_property_173,int64,0.0,0.0,2.0,"0, 1"
133,molecule_structure_property_174,int64,0.0,0.0,2.0,"0, 1"
134,molecule_structure_property_176,int64,0.0,0.0,2.0,"0, 1"
135,molecule_structure_property_177,int64,0.0,0.0,2.0,"0, 1"
136,molecule_structure_property_178,int64,0.0,0.0,2.0,"0, 1"
137,molecule_structure_property_179,int64,0.0,0.0,2.0,"0, 1"
138,molecule_structure_property_180,int64,0.0,0.0,2.0,"0, 1"
139,molecule_structure_property_181,int64,0.0,0.0,2.0,"0, 1"
140,molecule_structure_property_182,int64,0.0,0.0,2.0,"0, 1"
141,molecule_structure_property_183,int64,0.0,0.0,2.0,"0, 1"
142,molecule_structure_property_184,int64,0.0,0.0,2.0,"0, 1"
143,molecule_structure_property_185,int64,0.0,0.0,2.0,"0, 1"
144,molecule_structure_property_186,int64,0.0,0.0,2.0,"0, 1"
145,molecule_structure_property_187,int64,0.0,0.0,2.0,"0, 1"
146,molecule_structure_property_188,int64,0.0,0.0,2.0,"0, 1"
147,molecule_structure_property_189,int64,0.0,0.0,2.0,"0, 1"
148,molecule_structure_property_190,int64,0.0,0.0,2.0,"0, 1"
149,molecule_structure_property_191,int64,0.0,0.0,2.0,"0, 1"
150,molecule_structure_property_192,int64,0.0,0.0,2.0,"0, 1"
151,molecule_structure_property_193,int64,0.0,0.0,2.0,"0, 1"
152,molecule_structure_property_194,int64,0.0,0.0,2.0,"0, 1"
153,molecule_structure_property_195,int64,0.0,0.0,2.0,"0, 1"
154,molecule_structure_property_196,int64,0.0,0.0,2.0,"1, 0"
155,molecule_structure_property_197,int64,0.0,0.0,2.0,"0, 1"
156,molecule_structure_property_198,int64,0.0,0.0,2.0,"0, 1"
157,molecule_structure_property_199,int64,0.0,0.0,2.0,"0, 1"
158,molecule_structure_property_200,int64,0.0,0.0,2.0,"0, 1"
159,molecule_structure_property_201,int64,0.0,0.0,2.0,"0, 1"
160,molecule_structure_property_202,int64,0.0,0.0,2.0,"0, 1"
161,molecule_structure_property_203,int64,0.0,0.0,2.0,"0, 1"
162,molecule_structure_property_204,int64,0.0,0.0,2.0,"0, 1"
163,molecule_structure_property_205,int64,0.0,0.0,2.0,"0, 1"
164,molecule_structure_property_206,int64,0.0,0.0,2.0,"0, 1"
165,molecule_structure_property_207,int64,0.0,0.0,2.0,"0, 1"
166,molecule_structure_property_208,int64,0.0,0.0,2.0,"0, 1"
167,molecule_structure_property_209,int64,0.0,0.0,2.0,"0, 1"
168,molecule_structure_property_210,int64,0.0,0.0,2.0,"0, 1"
169,molecule_structure_property_211,int64,0.0,0.0,2.0,"0, 1"
170,molecule_structure_property_212,int64,0.0,0.0,2.0,"0, 1"
171,molecule_structure_property_213,int64,0.0,0.0,2.0,"0, 1"
172,molecule_structure_property_214,int64,0.0,0.0,2.0,"0, 1"
173,molecule_structure_property_215,int64,0.0,0.0,2.0,"0, 1"
174,molecule_structure_property_216,int64,0.0,0.0,2.0,"1, 0"
175,molecule_structure_property_217,int64,0.0,0.0,2.0,"0, 1"
176,molecule_structure_property_218,int64,0.0,0.0,2.0,"0, 1"
177,molecule_structure_property_219,int64,0.0,0.0,2.0,"0, 1"
178,molecule_structure_property_220,int64,0.0,0.0,2.0,"0, 1"
179,molecule_structure_property_221,int64,0.0,0.0,2.0,"0, 1"
180,molecule_structure_property_222,int64,0.0,0.0,2.0,"0, 1"
181,molecule_structure_property_223,int64,0.0,0.0,2.0,"0, 1"
182,molecule_structure_property_224,int64,0.0,0.0,2.0,"0, 1"
183,molecule_structure_property_225,int64,0.0,0.0,2.0,"0, 1"
184,molecule_structure_property_226,int64,0.0,0.0,2.0,"0, 1"
185,molecule_structure_property_227,int64,0.0,0.0,2.0,"0, 1"
186,molecule_structure_property_228,int64,0.0,0.0,2.0,"0, 1"
187,molecule_structure_property_229,int64,0.0,0.0,2.0,"0, 1"
188,molecule_structure_property_230,int64,0.0,0.0,2.0,"0, 1"
189,molecule_structure_property_231,int64,0.0,0.0,2.0,"1, 0"
190,molecule_structure_property_232,int64,0.0,0.0,2.0,"0, 1"
191,molecule_structure_property_233,int64,0.0,0.0,2.0,"0, 1"
192,molecule_structure_property_234,int64,0.0,0.0,2.0,"0, 1"
193,molecule_structure_property_235,int64,0.0,0.0,2.0,"0, 1"
194,molecule_structure_property_236,int64,0.0,0.0,2.0,"0, 1"
195,molecule_structure_property_237,int64,0.0,0.0,2.0,"0, 1"
196,molecule_structure_property_238,int64,0.0,0.0,2.0,"0, 1"
197,molecule_structure_property_239,int64,0.0,0.0,2.0,"0, 1"
198,molecule_structure_property_240,int64,0.0,0.0,2.0,"0, 1"
199,molecule_structure_property_241,int64,0.0,0.0,2.0,"0, 1"
200,molecule_structure_property_242,int64,0.0,0.0,2.0,"1, 0"
201,molecule_structure_property_243,int64,0.0,0.0,2.0,"0, 1"
202,molecule_structure_property_244,int64,0.0,0.0,2.0,"0, 1"
203,molecule_structure_property_245,int64,0.0,0.0,2.0,"1, 0"
204,molecule_structure_property_246,int64,0.0,0.0,2.0,"0, 1"
205,molecule_structure_property_247,int64,0.0,0.0,2.0,"0, 1"
206,molecule_structure_property_248,int64,0.0,0.0,2.0,"0, 1"
207,molecule_structure_property_249,int64,0.0,0.0,2.0,"0, 1"
208,molecule_structure_property_250,int64,0.0,0.0,2.0,"1, 0"
209,molecule_structure_property_251,int64,0.0,0.0,2.0,"0, 1"
210,molecule_structure_property_252,int64,0.0,0.0,2.0,"0, 1"
211,molecule_structure_property_253,int64,0.0,0.0,2.0,"0, 1"
212,molecule_structure_property_254,int64,0.0,0.0,2.0,"0, 1"
213,molecule_structure_property_255,int64,0.0,0.0,2.0,"0, 1"
214,molecule_structure_property_256,int64,0.0,0.0,2.0,"0, 1"
215,molecule_structure_property_257,int64,0.0,0.0,2.0,"0, 1"
216,molecule_structure_property_258,int64,0.0,0.0,2.0,"0, 1"
217,molecule_structure_property_259,int64,0.0,0.0,2.0,"0, 1"
218,molecule_structure_property_260,int64,0.0,0.0,2.0,"0, 1"
219,molecule_structure_property_261,int64,0.0,0.0,2.0,"0, 1"
220,molecule_structure_property_262,int64,0.0,0.0,2.0,"0, 1"
221,molecule_structure_property_263,int64,0.0,0.0,2.0,"0, 1"
222,molecule_structure_property_265,int64,0.0,0.0,2.0,"0, 1"
223,molecule_structure_property_266,int64,0.0,0.0,2.0,"0, 1"
224,molecule_structure_property_267,int64,0.0,0.0,2.0,"0, 1"
225,molecule_structure_property_268,int64,0.0,0.0,2.0,"0, 1"
226,molecule_structure_property_269,int64,0.0,0.0,2.0,"0, 1"
227,molecule_structure_property_270,int64,0.0,0.0,2.0,"0, 1"
228,molecule_structure_property_271,int64,0.0,0.0,2.0,"0, 1"
229,molecule_structure_property_272,int64,0.0,0.0,2.0,"0, 1"
230,molecule_structure_property_273,int64,0.0,0.0,2.0,"0, 1"
231,molecule_structure_property_274,int64,0.0,0.0,2.0,"0, 1"
232,molecule_structure_property_275,int64,0.0,0.0,2.0,"0, 1"
233,molecule_structure_property_276,int64,0.0,0.0,2.0,"0, 1"
234,molecule_structure_property_277,int64,0.0,0.0,2.0,"0, 1"
235,molecule_structure_property_278,int64,0.0,0.0,2.0,"0, 1"
236,molecule_structure_property_279,int64,0.0,0.0,2.0,"0, 1"
237,molecule_structure_property_280,int64,0.0,0.0,2.0,"0, 1"
238,molecule_structure_property_281,int64,0.0,0.0,2.0,"0, 1"
239,molecule_structure_property_282,int64,0.0,0.0,2.0,"0, 1"
240,molecule_structure_property_283,int64,0.0,0.0,2.0,"0, 1"
241,molecule_structure_property_284,int64,0.0,0.0,2.0,"0, 1"
242,molecule_structure_property_285,int64,0.0,0.0,2.0,"0, 1"
243,molecule_structure_property_286,int64,0.0,0.0,2.0,"0, 1"
244,molecule_structure_property_289,int64,0.0,0.0,2.0,"0, 1"
245,molecule_structure_property_290,int64,0.0,0.0,2.0,"0, 1"
246,molecule_structure_property_291,int64,0.0,0.0,2.0,"0, 1"
247,molecule_structure_property_292,int64,0.0,0.0,2.0,"0, 1"
248,molecule_structure_property_293,int64,0.0,0.0,2.0,"0, 1"
249,molecule_structure_property_294,int64,0.0,0.0,2.0,"0, 1"
250,molecule_structure_property_295,int64,0.0,0.0,2.0,"0, 1"
251,molecule_structure_property_296,int64,0.0,0.0,2.0,"1, 0"
252,molecule_structure_property_297,int64,0.0,0.0,2.0,"0, 1"
253,molecule_structure_property_298,int64,0.0,0.0,2.0,"0, 1"
254,molecule_structure_property_299,int64,0.0,0.0,2.0,"0, 1"
255,molecule_structure_property_300,int64,0.0,0.0,2.0,"0, 1"
256,molecule_structure_property_301,int64,0.0,0.0,2.0,"0, 1"
257,molecule_structure_property_302,int64,0.0,0.0,2.0,"0, 1"
258,molecule_structure_property_303,int64,0.0,0.0,2.0,"0, 1"
259,molecule_structure_property_304,int64,0.0,0.0,2.0,"0, 1"
260,molecule_structure_property_305,int64,0.0,0.0,2.0,"0, 1"
261,molecule_structure_property_306,int64,0.0,0.0,2.0,"0, 1"
262,molecule_structure_property_307,int64,0.0,0.0,2.0,"0, 1"
263,molecule_structure_property_308,int64,0.0,0.0,2.0,"0, 1"
264,molecule_structure_property_309,int64,0.0,0.0,2.0,"0, 1"
265,molecule_structure_property_310,int64,0.0,0.0,2.0,"0, 1"
266,molecule_structure_property_311,int64,0.0,0.0,2.0,"0, 1"
267,molecule_structure_property_312,int64,0.0,0.0,2.0,"0, 1"
268,molecule_structure_property_313,int64,0.0,0.0,2.0,"0, 1"
269,molecule_structure_property_314,int64,0.0,0.0,2.0,"0, 1"
270,molecule_structure_property_315,int64,0.0,0.0,2.0,"0, 1"
271,molecule_structure_property_316,int64,0.0,0.0,2.0,"0, 1"
272,molecule_structure_property_317,int64,0.0,0.0,2.0,"0, 1"
273,molecule_structure_property_318,int64,0.0,0.0,2.0,"0, 1"
274,molecule_structure_property_319,int64,0.0,0.0,2.0,"0, 1"
275,molecule_structure_property_321,int64,0.0,0.0,2.0,"0, 1"
276,molecule_structure_property_322,int64,0.0,0.0,2.0,"0, 1"
277,molecule_structure_property_323,int64,0.0,0.0,2.0,"0, 1"
278,molecule_structure_property_324,int64,0.0,0.0,2.0,"0, 1"
279,molecule_structure_property_325,int64,0.0,0.0,2.0,"0, 1"
280,molecule_structure_property_326,int64,0.0,0.0,2.0,"0, 1"
281,molecule_structure_property_327,int64,0.0,0.0,2.0,"0, 1"
282,molecule_structure_property_328,int64,0.0,0.0,2.0,"0, 1"
283,molecule_structure_property_329,int64,0.0,0.0,2.0,"0, 1"
284,molecule_structure_property_330,int64,0.0,0.0,2.0,"0, 1"
285,molecule_structure_property_331,int64,0.0,0.0,2.0,"0, 1"
286,molecule_structure_property_333,int64,0.0,0.0,2.0,"0, 1"
287,molecule_structure_property_334,int64,0.0,0.0,2.0,"0, 1"
288,molecule_structure_property_335,int64,0.0,0.0,2.0,"0, 1"
289,molecule_structure_property_336,int64,0.0,0.0,2.0,"0, 1"
290,molecule_structure_property_337,int64,0.0,0.0,2.0,"0, 1"
291,molecule_structure_property_338,int64,0.0,0.0,2.0,"0, 1"
292,molecule_structure_property_339,int64,0.0,0.0,2.0,"0, 1"
293,molecule_structure_property_340,int64,0.0,0.0,2.0,"0, 1"
294,molecule_structure_property_341,int64,0.0,0.0,2.0,"0, 1"
295,molecule_structure_property_342,int64,0.0,0.0,2.0,"0, 1"
296,molecule_structure_property_343,int64,0.0,0.0,2.0,"0, 1"
297,molecule_structure_property_344,int64,0.0,0.0,2.0,"0, 1"
298,molecule_structure_property_345,int64,0.0,0.0,2.0,"0, 1"
299,molecule_structure_property_346,int64,0.0,0.0,2.0,"0, 1"
300,molecule_structure_property_347,int64,0.0,0.0,2.0,"0, 1"
301,molecule_structure_property_348,int64,0.0,0.0,2.0,"0, 1"
302,molecule_structure_property_349,int64,0.0,0.0,2.0,"0, 1"
303,molecule_structure_property_350,int64,0.0,0.0,2.0,"0, 1"
304,molecule_structure_property_351,int64,0.0,0.0,2.0,"0, 1"
305,molecule_structure_property_352,int64,0.0,0.0,2.0,"0, 1"
306,molecule_structure_property_353,int64,0.0,0.0,2.0,"0, 1"
307,molecule_structure_property_354,int64,0.0,0.0,2.0,"0, 1"
308,molecule_structure_property_355,int64,0.0,0.0,2.0,"0, 1"
309,molecule_structure_property_356,int64,0.0,0.0,2.0,"0, 1"
310,molecule_structure_property_357,int64,0.0,0.0,2.0,"0, 1"
311,molecule_structure_property_358,int64,0.0,0.0,2.0,"0, 1"
312,molecule_structure_property_359,int64,0.0,0.0,2.0,"0, 1"
313,molecule_structure_property_360,int64,0.0,0.0,2.0,"0, 1"
314,molecule_structure_property_361,int64,0.0,0.0,2.0,"1, 0"
315,molecule_structure_property_362,int64,0.0,0.0,2.0,"0, 1"
316,molecule_structure_property_363,int64,0.0,0.0,2.0,"0, 1"
317,molecule_structure_property_364,int64,0.0,0.0,2.0,"0, 1"
318,molecule_structure_property_365,int64,0.0,0.0,2.0,"0, 1"
319,molecule_structure_property_366,int64,0.0,0.0,2.0,"0, 1"
320,molecule_structure_property_367,int64,0.0,0.0,2.0,"0, 1"
321,molecule_structure_property_368,int64,0.0,0.0,2.0,"0, 1"
322,molecule_structure_property_369,int64,0.0,0.0,2.0,"1, 0"
323,molecule_structure_property_370,int64,0.0,0.0,2.0,"0, 1"
324,molecule_structure_property_371,int64,0.0,0.0,2.0,"0, 1"
325,molecule_structure_property_372,int64,0.0,0.0,2.0,"0, 1"
326,molecule_structure_property_373,int64,0.0,0.0,2.0,"0, 1"
327,molecule_structure_property_374,int64,0.0,0.0,2.0,"0, 1"
328,molecule_structure_property_375,int64,0.0,0.0,2.0,"0, 1"
329,molecule_structure_property_377,int64,0.0,0.0,2.0,"0, 1"

In [108]:
# Numeric Feature Statistics
numeric_stats

                                   count      mean       std  min  max
molecule_structure_property_1     4229.0  0.010641  0.102616  0.0  1.0
molecule_structure_property_2     4229.0  0.022227  0.147440  0.0  1.0
molecule_structure_property_3     4229.0  0.017025  0.129381  0.0  1.0
molecule_structure_property_4     4229.0  0.035706  0.185578  0.0  1.0
molecule_structure_property_5     4229.0  0.061480  0.240238  0.0  1.0
molecule_structure_property_6     4229.0  0.119414  0.324313  0.0  1.0
molecule_structure_property_7     4229.0  0.033105  0.178931  0.0  1.0
molecule_structure_property_8     4229.0  0.007803  0.088001  0.0  1.0
molecule_structure_property_9     4229.0  0.035706  0.185578  0.0  1.0
molecule_structure_property_10    4229.0  0.016789  0.128495  0.0  1.0
molecule_structure_property_11    4229.0  0.082289  0.274837  0.0  1.0
molecule_structure_property_12    4229.0  0.004493  0.066885  0.0  1.0
molecule_structure_property_13    4229.0  0.005912  0.076668  0.0  1.0
molecule_structure_property_14    4229.0  0.025774  0.158480  0.0  1.0
molecule_structure_property_15    4229.0  0.034051  0.181381  0.0  1.0
molecule_structure_property_16    4229.0  0.023173  0.150472  0.0  1.0
molecule_structure_property_17    4229.0  0.016316  0.126702  0.0  1.0
molecule_structure_property_18    4229.0  0.047765  0.213295  0.0  1.0
molecule_structure_property_19    4229.0  0.431544  0.495350  0.0  1.0
molecule_structure_property_20    4229.0  0.024119  0.153437  0.0  1.0
molecule_structure_property_21    4229.0  0.128399  0.334573  0.0  1.0
molecule_structure_property_22    4229.0  0.030504  0.171989  0.0  1.0
molecule_structure_property_23    4229.0  0.064318  0.245347  0.0  1.0
molecule_structure_property_24    4229.0  0.005202  0.071947  0.0  1.0
molecule_structure_property_25    4229.0  0.052495  0.223049  0.0  1.0
molecule_structure_property_26    4229.0  0.098841  0.298484  0.0  1.0
molecule_structure_property_27    4229.0  0.048002  0.213796  0.0  1.0
molecule_structure_property_28    4229.0  0.090092  0.286348  0.0  1.0
molecule_structure_property_29    4229.0  0.049421  0.216770  0.0  1.0
molecule_structure_property_30    4229.0  0.013951  0.117303  0.0  1.0
molecule_structure_property_31    4229.0  0.095767  0.294307  0.0  1.0
molecule_structure_property_32    4229.0  0.050367  0.218726  0.0  1.0
molecule_structure_property_33    4229.0  0.053913  0.225874  0.0  1.0
molecule_structure_property_34    4229.0  0.012060  0.109165  0.0  1.0
molecule_structure_property_35    4229.0  0.024592  0.154897  0.0  1.0
molecule_structure_property_36    4229.0  0.005202  0.071947  0.0  1.0
molecule_structure_property_37    4229.0  0.004966  0.070301  0.0  1.0
molecule_structure_property_38    4229.0  0.022700  0.148964  0.0  1.0
molecule_structure_property_39    4229.0  0.015843  0.124883  0.0  1.0
molecule_structure_property_40    4229.0  0.002838  0.053199  0.0  1.0
molecule_structure_property_41    4229.0  0.031922  0.175814  0.0  1.0
molecule_structure_property_42    4229.0  0.022700  0.148964  0.0  1.0
molecule_structure_property_43    4229.0  0.057933  0.233645  0.0  1.0
molecule_structure_property_44    4229.0  0.113029  0.316666  0.0  1.0
molecule_structure_property_45    4229.0  0.038543  0.192527  0.0  1.0
molecule_structure_property_46    4229.0  0.023883  0.152702  0.0  1.0
molecule_structure_property_47    4229.0  0.195082  0.396310  0.0  1.0
molecule_structure_property_48    4229.0  0.045637  0.208722  0.0  1.0
molecule_structure_property_49    4229.0  0.081580  0.273755  0.0  1.0
molecule_structure_property_50    4229.0  0.306219  0.460976  0.0  1.0
molecule_structure_property_51    4229.0  0.058406  0.234538  0.0  1.0
molecule_structure_property_52    4229.0  0.336959  0.472727  0.0  1.0
molecule_structure_property_53    4229.0  0.042090  0.200819  0.0  1.0
molecule_structure_property_54    4229.0  0.094821  0.293003  0.0  1.0
molecule_structure_property_55    4229.0  0.017498  0.131134  0.0  1.0
molecule_structure_property_56    4229.0  0.155592  0.362511  0.0  1.0
molecule_structure_property_57    4229.0  0.033105  0.178931  0.0  1.0
molecule_structure_property_58    4229.0  0.061953  0.241099  0.0  1.0
molecule_structure_property_60    4229.0  0.015607  0.123962  0.0  1.0
molecule_structure_property_61    4229.0  0.038780  0.193093  0.0  1.0
molecule_structure_property_62    4229.0  0.290140  0.453880  0.0  1.0
molecule_structure_property_63    4229.0  0.127926  0.334047  0.0  1.0
molecule_structure_property_64    4229.0  0.050603  0.219211  0.0  1.0
molecule_structure_property_65    4229.0  0.028612  0.166733  0.0  1.0
molecule_structure_property_66    4229.0  0.511468  0.499928  0.0  1.0
molecule_structure_property_67    4229.0  0.035233  0.184390  0.0  1.0
molecule_structure_property_68    4229.0  0.030267  0.171342  0.0  1.0
molecule_structure_property_69    4229.0  0.600615  0.489830  0.0  1.0
molecule_structure_property_70    4229.0  0.009459  0.096805  0.0  1.0
molecule_structure_property_71    4229.0  0.075668  0.264497  0.0  1.0
molecule_structure_property_72    4229.0  0.078506  0.268997  0.0  1.0
molecule_structure_property_73    4229.0  0.023646  0.151962  0.0  1.0
molecule_structure_property_74    4229.0  0.088201  0.283620  0.0  1.0
molecule_structure_property_75    4229.0  0.040672  0.197552  0.0  1.0
molecule_structure_property_76    4229.0  0.008986  0.094377  0.0  1.0
molecule_structure_property_77    4229.0  0.040908  0.198101  0.0  1.0
molecule_structure_property_78    4229.0  0.013951  0.117303  0.0  1.0
molecule_structure_property_79    4229.0  0.013715  0.116318  0.0  1.0
molecule_structure_property_80    4229.0  0.130054  0.336403  0.0  1.0
molecule_structure_property_81    4229.0  0.021045  0.143552  0.0  1.0
molecule_structure_property_82    4229.0  0.018208  0.133717  0.0  1.0
molecule_structure_property_83    4229.0  0.005675  0.075128  0.0  1.0
molecule_structure_property_84    4229.0  0.057697  0.233197  0.0  1.0
molecule_structure_property_85    4229.0  0.029558  0.169384  0.0  1.0
molecule_structure_property_86    4229.0  0.030267  0.171342  0.0  1.0
molecule_structure_property_87    4229.0  0.021045  0.143552  0.0  1.0
molecule_structure_property_88    4229.0  0.038070  0.191389  0.0  1.0
molecule_structure_property_89    4229.0  0.011823  0.108102  0.0  1.0
molecule_structure_property_90    4229.0  0.088673  0.284305  0.0  1.0
molecule_structure_property_91    4229.0  0.090092  0.286348  0.0  1.0
molecule_structure_property_92    4229.0  0.015607  0.123962  0.0  1.0
molecule_structure_property_93    4229.0  0.030267  0.171342  0.0  1.0
molecule_structure_property_94    4229.0  0.060298  0.238066  0.0  1.0
molecule_structure_property_95    4229.0  0.381414  0.485791  0.0  1.0
molecule_structure_property_96    4229.0  0.082052  0.274477  0.0  1.0
molecule_structure_property_97    4229.0  0.073303  0.260665  0.0  1.0
molecule_structure_property_98    4229.0  0.026247  0.159889  0.0  1.0
molecule_structure_property_99    4229.0  0.041854  0.200279  0.0  1.0
molecule_structure_property_101   4229.0  0.022227  0.147440  0.0  1.0
molecule_structure_property_106   4229.0  0.233861  0.423335  0.0  1.0
molecule_structure_property_109   4229.0  0.042563  0.201894  0.0  1.0
molecule_structure_property_115   4229.0  0.082762  0.275555  0.0  1.0
molecule_structure_property_118   4229.0  0.066682  0.249501  0.0  1.0
molecule_structure_property_121   4229.0  0.018681  0.135410  0.0  1.0
molecule_structure_property_124   4229.0  0.025774  0.158480  0.0  1.0
molecule_structure_property_125   4229.0  0.612911  0.487142  0.0  1.0
molecule_structure_property_126   4229.0  0.115157  0.319249  0.0  1.0
molecule_structure_property_129   4229.0  0.076141  0.265255  0.0  1.0
molecule_structure_property_133   4229.0  0.044455  0.206128  0.0  1.0
molecule_structure_property_134   4229.0  0.020809  0.142760  0.0  1.0
molecule_structure_property_135   4229.0  0.030504  0.171989  0.0  1.0
molecule_structure_property_148   4229.0  0.075432  0.264118  0.0  1.0
molecule_structure_property_149   4229.0  0.065973  0.248264  0.0  1.0
molecule_structure_property_150   4229.0  0.065264  0.247020  0.0  1.0
molecule_structure_property_151   4229.0  0.017735  0.132001  0.0  1.0
molecule_structure_property_153   4229.0  0.291795  0.454642  0.0  1.0
molecule_structure_property_154   4229.0  0.034996  0.183793  0.0  1.0
molecule_structure_property_156   4229.0  0.070229  0.255563  0.0  1.0
molecule_structure_property_160   4229.0  0.024592  0.154897  0.0  1.0
molecule_structure_property_161   4229.0  0.021991  0.146671  0.0  1.0
molecule_structure_property_162   4229.0  0.169544  0.375276  0.0  1.0
molecule_structure_property_163   4229.0  0.095058  0.293330  0.0  1.0
molecule_structure_property_164   4229.0  0.058643  0.234983  0.0  1.0
molecule_structure_property_165   4229.0  0.019390  0.137907  0.0  1.0
molecule_structure_property_166   4229.0  0.035233  0.184390  0.0  1.0
molecule_structure_property_167   4229.0  0.009459  0.096805  0.0  1.0
molecule_structure_property_168   4229.0  0.003547  0.059457  0.0  1.0
molecule_structure_property_169   4229.0  0.111374  0.314632  0.0  1.0
molecule_structure_property_170   4229.0  0.074486  0.262591  0.0  1.0
molecule_structure_property_171   4229.0  0.051549  0.221140  0.0  1.0
molecule_structure_property_172   4229.0  0.077323  0.267135  0.0  1.0
molecule_structure_property_173   4229.0  0.020336  0.141163  0.0  1.0
molecule_structure_property_174   4229.0  0.037125  0.189089  0.0  1.0
molecule_structure_property_176   4229.0  0.216600  0.411976  0.0  1.0
molecule_structure_property_177   4229.0  0.019153  0.137080  0.0  1.0
molecule_structure_property_178   4229.0  0.003074  0.055365  0.0  1.0
molecule_structure_property_179   4229.0  0.020336  0.141163  0.0  1.0
molecule_structure_property_180   4229.0  0.058879  0.235426  0.0  1.0
molecule_structure_property_181   4229.0  0.028612  0.166733  0.0  1.0
molecule_structure_property_182   4229.0  0.022937  0.149720  0.0  1.0
molecule_structure_property_183   4229.0  0.013242  0.114323  0.0  1.0
molecule_structure_property_184   4229.0  0.013478  0.115325  0.0  1.0
molecule_structure_property_185   4229.0  0.018444  0.134567  0.0  1.0
molecule_structure_property_186   4229.0  0.134784  0.341533  0.0  1.0
molecule_structure_property_187   4229.0  0.102388  0.303194  0.0  1.0
molecule_structure_property_188   4229.0  0.027430  0.163351  0.0  1.0
molecule_structure_property_189   4229.0  0.063845  0.244505  0.0  1.0
molecule_structure_property_190   4229.0  0.048948  0.215784  0.0  1.0
molecule_structure_property_191   4229.0  0.006857  0.082535  0.0  1.0
molecule_structure_property_192   4229.0  0.022700  0.148964  0.0  1.0
molecule_structure_property_193   4229.0  0.134784  0.341533  0.0  1.0
molecule_structure_property_194   4229.0  0.287302  0.452557  0.0  1.0
molecule_structure_property_195   4229.0  0.103098  0.304122  0.0  1.0
molecule_structure_property_196   4229.0  0.639631  0.480164  0.0  1.0
molecule_structure_property_197   4229.0  0.006857  0.082535  0.0  1.0
molecule_structure_property_198   4229.0  0.067155  0.250320  0.0  1.0
molecule_structure_property_199   4229.0  0.112793  0.316377  0.0  1.0
molecule_structure_property_200   4229.0  0.007330  0.085313  0.0  1.0
molecule_structure_property_201   4229.0  0.035942  0.186168  0.0  1.0
molecule_structure_property_202   4229.0  0.327264  0.469270  0.0  1.0
molecule_structure_property_203   4229.0  0.197446  0.398119  0.0  1.0
molecule_structure_property_204   4229.0  0.014661  0.120205  0.0  1.0
molecule_structure_property_205   4229.0  0.071885  0.258327  0.0  1.0
molecule_structure_property_206   4229.0  0.045874  0.209236  0.0  1.0
molecule_structure_property_207   4229.0  0.032159  0.176443  0.0  1.0
molecule_structure_property_208   4229.0  0.029085  0.168064  0.0  1.0
molecule_structure_property_209   4229.0  0.044928  0.207170  0.0  1.0
molecule_structure_property_210   4229.0  0.015370  0.123034  0.0  1.0
molecule_structure_property_211   4229.0  0.077323  0.267135  0.0  1.0
molecule_structure_property_212   4229.0  0.004256  0.065109  0.0  1.0
molecule_structure_property_213   4229.0  0.237172  0.425399  0.0  1.0
molecule_structure_property_214   4229.0  0.027903  0.164713  0.0  1.0
molecule_structure_property_215   4229.0  0.015607  0.123962  0.0  1.0
molecule_structure_property_216   4229.0  0.502719  0.500052  0.0  1.0
molecule_structure_property_217   4229.0  0.013242  0.114323  0.0  1.0
molecule_structure_property_218   4229.0  0.019863  0.139545  0.0  1.0
molecule_structure_property_219   4229.0  0.316150  0.465027  0.0  1.0
molecule_structure_property_220   4229.0  0.075195  0.263737  0.0  1.0
molecule_structure_property_221   4229.0  0.034996  0.183793  0.0  1.0
molecule_structure_property_222   4229.0  0.425160  0.494426  0.0  1.0
molecule_structure_property_223   4229.0  0.079451  0.270474  0.0  1.0
molecule_structure_property_224   4229.0  0.096950  0.295924  0.0  1.0
molecule_structure_property_225   4229.0  0.074486  0.262591  0.0  1.0
molecule_structure_property_226   4229.0  0.010877  0.103738  0.0  1.0
molecule_structure_property_227   4229.0  0.168361  0.374231  0.0  1.0
molecule_structure_property_228   4229.0  0.194609  0.395946  0.0  1.0
molecule_structure_property_229   4229.0  0.038070  0.191389  0.0  1.0
molecule_structure_property_230   4229.0  0.037834  0.190817  0.0  1.0
molecule_structure_property_231   4229.0  0.527784  0.499286  0.0  1.0
molecule_structure_property_232   4229.0  0.177820  0.382406  0.0  1.0
molecule_structure_property_233   4229.0  0.062190  0.241528  0.0  1.0
molecule_structure_property_234   4229.0  0.026484  0.160588  0.0  1.0
molecule_structure_property_235   4229.0  0.018208  0.133717  0.0  1.0
molecule_structure_property_236   4229.0  0.102152  0.302884  0.0  1.0
molecule_structure_property_237   4229.0  0.040672  0.197552  0.0  1.0
molecule_structure_property_238   4229.0  0.025301  0.157058  0.0  1.0
molecule_structure_property_239   4229.0  0.127453  0.333520  0.0  1.0
molecule_structure_property_240   4229.0  0.017025  0.129381  0.0  1.0
molecule_structure_property_241   4229.0  0.309057  0.462159  0.0  1.0
molecule_structure_property_242   4229.0  0.520690  0.499631  0.0  1.0
molecule_structure_property_243   4229.0  0.059116  0.235869  0.0  1.0
molecule_structure_property_244   4229.0  0.100733  0.301010  0.0  1.0
molecule_structure_property_245   4229.0  0.645543  0.478405  0.0  1.0
molecule_structure_property_246   4229.0  0.033814  0.180772  0.0  1.0
molecule_structure_property_247   4229.0  0.167888  0.373811  0.0  1.0
molecule_structure_property_248   4229.0  0.060534  0.238502  0.0  1.0
molecule_structure_property_249   4229.0  0.019153  0.137080  0.0  1.0
molecule_structure_property_250   4229.0  0.659967  0.473776  0.0  1.0
molecule_structure_property_251   4229.0  0.040199  0.196448  0.0  1.0
molecule_structure_property_252   4229.0  0.091747  0.288703  0.0  1.0
molecule_structure_property_253   4229.0  0.029794  0.170039  0.0  1.0
molecule_structure_property_254   4229.0  0.050839  0.219696  0.0  1.0
molecule_structure_property_255   4229.0  0.025065  0.156341  0.0  1.0
molecule_structure_property_256   4229.0  0.055805  0.229572  0.0  1.0
molecule_structure_property_257   4229.0  0.020809  0.142760  0.0  1.0
molecule_structure_property_258   4229.0  0.059116  0.235869  0.0  1.0
molecule_structure_property_259   4229.0  0.087018  0.281895  0.0  1.0
molecule_structure_property_260   4229.0  0.099314  0.299119  0.0  1.0
molecule_structure_property_261   4229.0  0.389217  0.487630  0.0  1.0
molecule_structure_property_262   4229.0  0.023173  0.150472  0.0  1.0
molecule_structure_property_263   4229.0  0.084417  0.278045  0.0  1.0
molecule_structure_property_265   4229.0  0.021755  0.145898  0.0  1.0
molecule_structure_property_266   4229.0  0.136675  0.343545  0.0  1.0
molecule_structure_property_267   4229.0  0.016316  0.126702  0.0  1.0
molecule_structure_property_268   4229.0  0.035233  0.184390  0.0  1.0
molecule_structure_property_269   4229.0  0.024829  0.155621  0.0  1.0
molecule_structure_property_270   4229.0  0.027903  0.164713  0.0  1.0
molecule_structure_property_271   4229.0  0.029085  0.168064  0.0  1.0
molecule_structure_property_272   4229.0  0.019626  0.138729  0.0  1.0
molecule_structure_property_273   4229.0  0.115157  0.319249  0.0  1.0
molecule_structure_property_274   4229.0  0.342871  0.474725  0.0  1.0
molecule_structure_property_275   4229.0  0.042090  0.200819  0.0  1.0
molecule_structure_property_276   4229.0  0.044928  0.207170  0.0  1.0
molecule_structure_property_277   4229.0  0.058406  0.234538  0.0  1.0
molecule_structure_property_278   4229.0  0.091747  0.288703  0.0  1.0
molecule_structure_property_279   4229.0  0.449988  0.497551  0.0  1.0
molecule_structure_property_280   4229.0  0.013715  0.116318  0.0  1.0
molecule_structure_property_281   4229.0  0.346891  0.476037  0.0  1.0
molecule_structure_property_282   4229.0  0.249231  0.432619  0.0  1.0
molecule_structure_property_283   4229.0  0.015134  0.122099  0.0  1.0
molecule_structure_property_284   4229.0  0.034051  0.181381  0.0  1.0
molecule_structure_property_285   4229.0  0.056278  0.230485  0.0  1.0
molecule_structure_property_286   4229.0  0.055569  0.229114  0.0  1.0
molecule_structure_property_289   4229.0  0.008276  0.090607  0.0  1.0
molecule_structure_property_290   4229.0  0.038780  0.193093  0.0  1.0
molecule_structure_property_291   4229.0  0.019626  0.138729  0.0  1.0
molecule_structure_property_292   4229.0  0.185860  0.389039  0.0  1.0
molecule_structure_property_293   4229.0  0.024356  0.154169  0.0  1.0
molecule_structure_property_294   4229.0  0.144715  0.351855  0.0  1.0
molecule_structure_property_295   4229.0  0.020572  0.141964  0.0  1.0
molecule_structure_property_296   4229.0  0.773942  0.418327  0.0  1.0
molecule_structure_property_297   4229.0  0.035469  0.184985  0.0  1.0
molecule_structure_property_298   4229.0  0.029085  0.168064  0.0  1.0
molecule_structure_property_299   4229.0  0.007330  0.085313  0.0  1.0
molecule_structure_property_300   4229.0  0.039726  0.195337  0.0  1.0
molecule_structure_property_301   4229.0  0.074486  0.262591  0.0  1.0
molecule_structure_property_302   4229.0  0.007567  0.086668  0.0  1.0
molecule_structure_property_303   4229.0  0.119414  0.324313  0.0  1.0
molecule_structure_property_304   4229.0  0.010404  0.101482  0.0  1.0
molecule_structure_property_305   4229.0  0.029085  0.168064  0.0  1.0
molecule_structure_property_306   4229.0  0.008749  0.093138  0.0  1.0
molecule_structure_property_307   4229.0  0.029321  0.168726  0.0  1.0
molecule_structure_property_308   4229.0  0.069756  0.254766  0.0  1.0
molecule_structure_property_309   4229.0  0.019863  0.139545  0.0  1.0
molecule_structure_property_310   4229.0  0.164105  0.370415  0.0  1.0
molecule_structure_property_311   4229.0  0.055569  0.229114  0.0  1.0
molecule_structure_property_312   4229.0  0.099314  0.299119  0.0  1.0
molecule_structure_property_313   4229.0  0.059116  0.235869  0.0  1.0
molecule_structure_property_314   4229.0  0.174982  0.379997  0.0  1.0
molecule_structure_property_315   4229.0  0.147080  0.354227  0.0  1.0
molecule_structure_property_316   4229.0  0.035942  0.186168  0.0  1.0
molecule_structure_property_317   4229.0  0.020809  0.142760  0.0  1.0
molecule_structure_property_318   4229.0  0.062426  0.241956  0.0  1.0
molecule_structure_property_319   4229.0  0.026247  0.159889  0.0  1.0
molecule_structure_property_321   4229.0  0.015607  0.123962  0.0  1.0
molecule_structure_property_322   4229.0  0.028612  0.166733  0.0  1.0
molecule_structure_property_323   4229.0  0.249941  0.433030  0.0  1.0
molecule_structure_property_324   4229.0  0.117049  0.321517  0.0  1.0
molecule_structure_property_325   4229.0  0.278080  0.448106  0.0  1.0
molecule_structure_property_326   4229.0  0.003547  0.059457  0.0  1.0

In [109]:
# Categorical Feature Statistics
cat_stats

                    value  count    pct
column         rank
CompoundActive 1       No   4080  96.48
               2      Yes    149   3.52

In [110]:
# Target Distribution
target_df

                count    pct
CompoundActive
No               4080  96.48
Yes               149   3.52

## Task Curation

In [111]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=3, n_splits=3, test_size=None

In [112]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [113]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019d1b2f-370f-7b87-bcac-8bf7912d887b
47bd213dda3912409e36d921e0e4500315597458516e98f26c22bbfb5d4ca28c