### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="colon_tumor",
    dataset_year="1999",
    domain_str="medical & healthcare",
    # Data Source
    dataset_source="OpenML",
    original_dataset_source_download_link="https://www.openml.org/d/45087",
    download_description="""
We download the data to a predefined folder.

mkdir -p local-data-warehouse/colon_tumor && wget -P local-data-warehouse/colon_tumor https://api.openml.org/data/download/22112148/dataset 
""",
    # References
    academic_reference_bibtex="""@article{Alon1999BroadPO,
  title={Broad patterns of gene expression revealed by clustering analysis of tumor and normal colon tissues probed by oligonucleotide arrays},
  author={Uri Alon and Naama Barkai and Daniel A. Notterman and Kurt Gish and Suzanne Ybarra and Daniel Mack and Arnold J. Levine},
  journal={Proceedings of the National Academy of Sciences},
  year={1999},
  volume={96},
  number={12},
  pages={6745-6750},
  doi={10.1073/pnas.96.12.6745},
  url={https://doi.org/10.1073/pnas.96.12.6745}
}
""",
    academic_reference_bibtex_key="Alon1999BroadPO",
    license="Public Domain",
    data_tags=["IID"],
    curation_comments="""
        - We use the OpenML version of the data as original raw data in not available. The features have been pre-filtered in an unsupervised way from 6,500 to 2,000. They have been already z-normalized.
        - We remove 9 duplicated columns: "att_261", "att_262", "att_263", "att_51", "att_52", "att_53", "att_40", "att_41", "att_42".
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="HasTumor",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="HasTumor",
)

## Preprocessing

In [2]:
import pandas as pd
import arff

with open(dataset_mold.path/"dataset") as f:
    data = arff.load(f)
df = pd.DataFrame(data["data"], columns=[x[0] for x in data["attributes"]])

target_feature = "HasTumor"
df.rename(columns={"class": target_feature}, inplace=True)
df[target_feature] = df[target_feature].map({"-1": "Yes", "1": "No"})
df.drop(columns=["att_261", "att_262", "att_263", "att_51", "att_52", "att_53", "att_40", "att_41", "att_42"], inplace=True)
df["HasTumor"] = df["HasTumor"].astype("category")

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 62
Columns: 1992
Use sampling: False (sample size: 62)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['att_1005', 'att_1333', 'att_1346', 'att_1345', 'att_1344', 'att_1343', 'att_1342', 'att_1341', 'att_1340', 'att_1339']
Rows remaining as candidates after top-10 filter: 0 (of 62)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,att_1,att_2,att_3,att_4,att_5,att_6,att_7,att_8,att_9,att_10,att_11,att_12,att_13,att_14,att_15,att_16,att_17,att_18,att_19,att_20,att_21,att_22,att_23,att_24,att_25,att_26,att_27,att_28,att_29,att_30,att_31,att_32,att_33,att_34,att_35,att_36,att_37,att_38,att_39,att_43,att_44,att_45,att_46,att_47,att_48,att_49,att_50,att_54,att_55,att_56,att_57,att_58,att_59,att_60,att_61,att_62,att_63,att_64,att_65,att_66,att_67,att_68,att_69,att_70,att_71,att_72,att_73,att_74,att_75,att_76,att_77,att_78,att_79,att_80,att_81,att_82,att_83,att_84,att_85,att_86,att_87,att_88,att_89,att_90,att_91,att_92,att_93,att_94,att_95,att_96,att_97,att_98,att_99,att_100,att_101,att_102,att_103,att_104,att_105,att_106,att_107,att_108,att_109,att_110,att_111,att_112,att_113,att_114,att_115,att_116,att_117,att_118,att_119,att_120,att_121,att_122,att_123,att_124,att_125,att_126,att_127,att_128,att_129,att_130,att_131,att_132,att_133,att_134,att_135,att_136,att_137,att_138,att_139,att_140,att_141,att_142,att_143,att_144,att_145,att_146,att_147,att_148,att_149,att_150,att_151,att_152,att_153,att_154,att_155,att_156,att_157,att_158,att_159,att_160,att_161,att_162,att_163,att_164,att_165,att_166,att_167,att_168,att_169,att_170,att_171,att_172,att_173,att_174,att_175,att_176,att_177,att_178,att_179,att_180,att_181,att_182,att_183,att_184,att_185,att_186,att_187,att_188,att_189,att_190,att_191,att_192,att_193,att_194,att_195,att_196,att_197,att_198,att_199,att_200,att_201,att_202,att_203,att_204,att_205,att_206,att_207,att_208,att_209,att_210,att_211,att_212,att_213,att_214,att_215,att_216,att_217,att_218,att_219,att_220,att_221,att_222,att_223,att_224,att_225,att_226,att_227,att_228,att_229,att_230,att_231,att_232,att_233,att_234,att_235,att_236,att_237,att_238,att_239,att_240,att_241,att_242,att_243,att_244,att_245,att_246,att_247,att_248,att_249,att_250,att_251,att_252,att_253,att_254,att_255,att_256,att_257,att_258,att_259,att_260,att_264,att_265,att_266,att_267,att_268,att_269,att_270,att_271,att_272,att_273,att_274,att_275,att_276,att_277,att_278,att_279,att_280,att_281,att_282,att_283,att_284,att_285,att_286,att_287,att_288,att_289,att_290,att_291,att_292,att_293,att_294,att_295,att_296,att_297,att_298,att_299,att_300,att_301,att_302,att_303,att_304,att_305,att_306,att_307,att_308,att_309,att_310,att_311,att_312,att_313,att_314,att_315,att_316,att_317,att_318,att_319,att_320,att_321,att_322,att_323,att_324,att_325,att_326,att_327,att_328,att_329,att_330,att_331,att_332,att_333,att_334,att_335,att_336,att_337,att_338,att_339,att_340,att_341,att_342,att_343,att_344,att_345,att_346,att_347,att_348,att_349,att_350,att_351,att_352,att_353,att_354,att_355,att_356,att_357,att_358,att_359,att_360,att_361,att_362,att_363,att_364,att_365,att_366,att_367,att_368,att_369,att_370,att_371,att_372,att_373,att_374,att_375,att_376,att_377,att_378,att_379,att_380,att_381,att_382,att_383,att_384,att_385,att_386,att_387,att_388,att_389,att_390,att_391,att_392,att_393,att_394,att_395,att_396,att_397,att_398,att_399,att_400,att_401,att_402,att_403,att_404,att_405,att_406,att_407,att_408,att_409,att_410,att_411,att_412,att_413,att_414,att_415,att_416,att_417,att_418,att_419,att_420,att_421,att_422,att_423,att_424,att_425,att_426,att_427,att_428,att_429,att_430,att_431,att_432,att_433,att_434,att_435,att_436,att_437,att_438,att_439,att_440,att_441,att_442,att_443,att_444,att_445,att_446,att_447,att_448,att_449,att_450,att_451,att_452,att_453,att_454,att_455,att_456,att_457,att_458,att_459,att_460,att_461,att_462,att_463,att_464,att_465,att_466,att_467,att_468,att_469,att_470,att_471,att_472,att_473,att_474,att_475,att_476,att_477,att_478,att_479,att_480,att_481,att_482,att_483,att_484,att_485,att_486,att_487,att_488,att_489,att_490,att_491,att_492,att_493,att_494,att_495,att_496,att_497,att_498,att_499,att_500,att_501,att_502,att_503,att_504,att_505,att_506,att_507,att_508,att_509,att_510,att_511,att_512,att_513,att_514,att_515,att_516,att_517,att_518,att_519,att_520,att_521,att_522,att_523,att_524,att_525,att_526,att_527,att_528,att_529,att_530,att_531,att_532,att_533,att_534,att_535,att_536,att_537,att_538,att_539,att_540,att_541,att_542,att_543,att_544,att_545,att_546,att_547,att_548,att_549,att_550,att_551,att_552,att_553,att_554,att_555,att_556,att_557,att_558,att_559,att_560,att_561,att_562,att_563,att_564,att_565,att_566,att_567,att_568,att_569,att_570,att_571,att_572,att_573,att_574,att_575,att_576,att_577,att_578,att_579,att_580,att_581,att_582,att_583,att_584,att_585,att_586,att_587,att_588,att_589,att_590,att_591,att_592,att_593,att_594,att_595,att_596,att_597,att_598,att_599,att_600,att_601,att_602,att_603,att_604,att_605,att_606,att_607,att_608,att_609,att_610,att_611,att_612,att_613,att_614,att_615,att_616,att_617,att_618,att_619,att_620,att_621,att_622,att_623,att_624,att_625,att_626,att_627,att_628,att_629,att_630,att_631,att_632,att_633,att_634,att_635,att_636,att_637,att_638,att_639,att_640,att_641,att_642,att_643,att_644,att_645,att_646,att_647,att_648,att_649,att_650,att_651,att_652,att_653,att_654,att_655,att_656,att_657,att_658,att_659,att_660,att_661,att_662,att_663,att_664,att_665,att_666,att_667,att_668,att_669,att_670,att_671,att_672,att_673,att_674,att_675,att_676,att_677,att_678,att_679,att_680,att_681,att_682,att_683,att_684,att_685,att_686,att_687,att_688,att_689,att_690,att_691,att_692,att_693,att_694,att_695,att_696,att_697,att_698,att_699,att_700,att_701,att_702,att_703,att_704,att_705,att_706,att_707,att_708,att_709,att_710,att_711,att_712,att_713,att_714,att_715,att_716,att_717,att_718,att_719,att_720,att_721,att_722,att_723,att_724,att_725,att_726,att_727,att_728,att_729,att_730,att_731,att_732,att_733,att_734,att_735,att_736,att_737,att_738,att_739,att_740,att_741,att_742,att_743,att_744,att_745,att_746,att_747,att_748,att_749,att_750,att_751,att_752,att_753,att_754,att_755,att_756,att_757,att_758,att_759,att_760,att_761,att_762,att_763,att_764,att_765,att_766,att_767,att_768,att_769,att_770,att_771,att_772,att_773,att_774,att_775,att_776,att_777,att_778,att_779,att_780,att_781,att_782,att_783,att_784,att_785,att_786,att_787,att_788,att_789,att_790,att_791,att_792,att_793,att_794,att_795,att_796,att_797,att_798,att_799,att_800,att_801,att_802,att_803,att_804,att_805,att_806,att_807,att_808,att_809,att_810,att_811,att_812,att_813,att_814,att_815,att_816,att_817,att_818,att_819,att_820,att_821,att_822,att_823,att_824,att_825,att_826,att_827,att_828,att_829,att_830,att_831,att_832,att_833,att_834,att_835,att_836,att_837,att_838,att_839,att_840,att_841,att_842,att_843,att_844,att_845,att_846,att_847,att_848,att_849,att_850,att_851,att_852,att_853,att_854,att_855,att_856,att_857,att_858,att_859,att_860,att_861,att_862,att_863,att_864,att_865,att_866,att_867,att_868,att_869,att_870,att_871,att_872,att_873,att_874,att_875,att_876,att_877,att_878,att_879,att_880,att_881,att_882,att_883,att_884,att_885,att_886,att_887,att_888,att_889,att_890,att_891,att_892,att_893,att_894,att_895,att_896,att_897,att_898,att_899,att_900,att_901,att_902,att_903,att_904,att_905,att_906,att_907,att_908,att_909,att_910,att_911,att_912,att_913,att_914,att_915,att_916,att_917,att_918,att_919,att_920,att_921,att_922,att_923,att_924,att_925,att_926,att_927,att_928,att_929,att_930,att_931,att_932,att_933,att_934,att_935,att_936,att_937,att_938,att_939,att_940,att_941,att_942,att_943,att_944,att_945,att_946,att_947,att_948,att_949,att_950,att_951,att_952,att_953,att_954,att_955,att_956,att_957,att_958,att_959,att_960,att_961,att_962,att_963,att_964,att_965,att_966,att_967,att_968,att_969,att_970,att_971,att_972,att_973,att_974,att_975,att_976,att_977,att_978,att_979,att_980,att_981,att_982,att_983,att_984,att_985,att_986,att_987,att_988,att_989,att_990,att_991,att_992,att_993,att_994,att_995,att_996,att_997,att_998,att_999,att_1000,att_1001,att_1002,att_1003,att_1004,att_1005,att_1006,att_1007,att_1008,att_1009,att_1010,att_1011,att_1012,att_1013,att_1014,att_1015,att_1016,att_1017,att_1018,att_1019,att_1020,att_1021,att_1022,att_1023,att_1024,att_1025,att_1026,att_1027,att_1028,att_1029,att_1030,att_1031,att_1032,att_1033,att_1034,att_1035,att_1036,att_1037,att_1038,att_1039,att_1040,att_1041,att_1042,att_1043,att_1044,att_1045,att_1046,att_1047,att_1048,att_1049,att_1050,att_1051,att_1052,att_1053,att_1054,att_1055,att_1056,att_1057,att_1058,att_1059,att_1060,att_1061,att_1062,att_1063,att_1064,att_1065,att_1066,att_1067,att_1068,att_1069,att_1070,att_1071,att_1072,att_1073,att_1074,att_1075,att_1076,att_1077,att_1078,att_1079,att_1080,att_1081,att_1082,att_1083,att_1084,att_1085,att_1086,att_1087,att_1088,att_1089,att_1090,att_1091,att_1092,att_1093,att_1094,att_1095,att_1096,att_1097,att_1098,att_1099,att_1100,att_1101,att_1102,att_1103,att_1104,att_1105,att_1106,att_1107,att_1108,att_1109,att_1110,att_1111,att_1112,att_1113,att_1114,att_1115,att_1116,att_1117,att_1118,att_1119,att_1120,att_1121,att_1122,att_1123,att_1124,att_1125,att_1126,att_1127,att_1128,att_1129,att_1130,att_1131,att_1132,att_1133,att_1134,att_1135,att_1136,att_1137,att_1138,att_1139,att_1140,att_1141,att_1142,att_1143,att_1144,att_1145,att_1146,att_1147,att_1148,att_1149,att_1150,att_1151,att_1152,att_1153,att_1154,att_1155,att_1156,att_1157,att_1158,att_1159,att_1160,att_1161,att_1162,att_1163,att_1164,att_1165,att_1166,att_1167,att_1168,att_1169,att_1170,att_1171,att_1172,att_1173,att_1174,att_1175,att_1176,att_1177,att_1178,att_1179,att_1180,att_1181,att_1182,att_1183,att_1184,att_1185,att_1186,att_1187,att_1188,att_1189,att_1190,att_1191,att_1192,att_1193,att_1194,att_1195,att_1196,att_1197,att_1198,att_1199,att_1200,att_1201,att_1202,att_1203,att_1204,att_1205,att_1206,att_1207,att_1208,att_1209,att_1210,att_1211,att_1212,att_1213,att_1214,att_1215,att_1216,att_1217,att_1218,att_1219,att_1220,att_1221,att_1222,att_1223,att_1224,att_1225,att_1226,att_1227,att_1228,att_1229,att_1230,att_1231,att_1232,att_1233,att_1234,att_1235,att_1236,att_1237,att_1238,att_1239,att_1240,att_1241,att_1242,att_1243,att_1244,att_1245,att_1246,att_1247,att_1248,att_1249,att_1250,att_1251,att_1252,att_1253,att_1254,att_1255,att_1256,att_1257,att_1258,att_1259,att_1260,att_1261,att_1262,att_1263,att_1264,att_1265,att_1266,att_1267,att_1268,att_1269,att_1270,att_1271,att_1272,att_1273,att_1274,att_1275,att_1276,att_1277,att_1278,att_1279,att_1280,att_1281,att_1282,att_1283,att_1284,att_1285,att_1286,att_1287,att_1288,att_1289,att_1290,att_1291,att_1292,att_1293,att_1294,att_1295,att_1296,att_1297,att_1298,att_1299,att_1300,att_1301,att_1302,att_1303,att_1304,att_1305,att_1306,att_1307,att_1308,att_1309,att_1310,att_1311,att_1312,att_1313,att_1314,att_1315,att_1316,att_1317,att_1318,att_1319,att_1320,att_1321,att_1322,att_1323,att_1324,att_1325,att_1326,att_1327,att_1328,att_1329,att_1330,att_1331,att_1332,att_1333,att_1334,att_1335,att_1336,att_1337,att_1338,att_1339,att_1340,att_1341,att_1342,att_1343,att_1344,att_1345,att_1346,att_1347,att_1348,att_1349,att_1350,att_1351,att_1352,att_1353,att_1354,att_1355,att_1356,att_1357,att_1358,att_1359,att_1360,att_1361,att_1362,att_1363,att_1364,att_1365,att_1366,att_1367,att_1368,att_1369,att_1370,att_1371,att_1372,att_1373,att_1374,att_1375,att_1376,att_1377,att_1378,att_1379,att_1380,att_1381,att_1382,att_1383,att_1384,att_1385,att_1386,att_1387,att_1388,att_1389,att_1390,att_1391,att_1392,att_1393,att_1394,att_1395,att_1396,att_1397,att_1398,att_1399,att_1400,att_1401,att_1402,att_1403,att_1404,att_1405,att_1406,att_1407,att_1408,att_1409,att_1410,att_1411,att_1412,att_1413,att_1414,att_1415,att_1416,att_1417,att_1418,att_1419,att_1420,att_1421,att_1422,att_1423,att_1424,att_1425,att_1426,att_1427,att_1428,att_1429,att_1430,att_1431,att_1432,att_1433,att_1434,att_1435,att_1436,att_1437,att_1438,att_1439,att_1440,att_1441,att_1442,att_1443,att_1444,att_1445,att_1446,att_1447,att_1448,att_1449,att_1450,att_1451,att_1452,att_1453,att_1454,att_1455,att_1456,att_1457,att_1458,att_1459,att_1460,att_1461,att_1462,att_1463,att_1464,att_1465,att_1466,att_1467,att_1468,att_1469,att_1470,att_1471,att_1472,att_1473,att_1474,att_1475,att_1476,att_1477,att_1478,att_1479,att_1480,att_1481,att_1482,att_1483,att_1484,att_1485,att_1486,att_1487,att_1488,att_1489,att_1490,att_1491,att_1492,att_1493,att_1494,att_1495,att_1496,att_1497,att_1498,att_1499,att_1500,att_1501,att_1502,att_1503,att_1504,att_1505,att_1506,att_1507,att_1508,att_1509,att_1510,att_1511,att_1512,att_1513,att_1514,att_1515,att_1516,att_1517,att_1518,att_1519,att_1520,att_1521,att_1522,att_1523,att_1524,att_1525,att_1526,att_1527,att_1528,att_1529,att_1530,att_1531,att_1532,att_1533,att_1534,att_1535,att_1536,att_1537,att_1538,att_1539,att_1540,att_1541,att_1542,att_1543,att_1544,att_1545,att_1546,att_1547,att_1548,att_1549,att_1550,att_1551,att_1552,att_1553,att_1554,att_1555,att_1556,att_1557,att_1558,att_1559,att_1560,att_1561,att_1562,att_1563,att_1564,att_1565,att_1566,att_1567,att_1568,att_1569,att_1570,att_1571,att_1572,att_1573,att_1574,att_1575,att_1576,att_1577,att_1578,att_1579,att_1580,att_1581,att_1582,att_1583,att_1584,att_1585,att_1586,att_1587,att_1588,att_1589,att_1590,att_1591,att_1592,att_1593,att_1594,att_1595,att_1596,att_1597,att_1598,att_1599,att_1600,att_1601,att_1602,att_1603,att_1604,att_1605,att_1606,att_1607,att_1608,att_1609,att_1610,att_1611,att_1612,att_1613,att_1614,att_1615,att_1616,att_1617,att_1618,att_1619,att_1620,att_1621,att_1622,att_1623,att_1624,att_1625,att_1626,att_1627,att_1628,att_1629,att_1630,att_1631,att_1632,att_1633,att_1634,att_1635,att_1636,att_1637,att_1638,att_1639,att_1640,att_1641,att_1642,att_1643,att_1644,att_1645,att_1646,att_1647,att_1648,att_1649,att_1650,att_1651,att_1652,att_1653,att_1654,att_1655,att_1656,att_1657,att_1658,att_1659,att_1660,att_1661,att_1662,att_1663,att_1664,att_1665,att_1666,att_1667,att_1668,att_1669,att_1670,att_1671,att_1672,att_1673,att_1674,att_1675,att_1676,att_1677,att_1678,att_1679,att_1680,att_1681,att_1682,att_1683,att_1684,att_1685,att_1686,att_1687,att_1688,att_1689,att_1690,att_1691,att_1692,att_1693,att_1694,att_1695,att_1696,att_1697,att_1698,att_1699,att_1700,att_1701,att_1702,att_1703,att_1704,att_1705,att_1706,att_1707,att_1708,att_1709,att_1710,att_1711,att_1712,att_1713,att_1714,att_1715,att_1716,att_1717,att_1718,att_1719,att_1720,att_1721,att_1722,att_1723,att_1724,att_1725,att_1726,att_1727,att_1728,att_1729,att_1730,att_1731,att_1732,att_1733,att_1734,att_1735,att_1736,att_1737,att_1738,att_1739,att_1740,att_1741,att_1742,att_1743,att_1744,att_1745,att_1746,att_1747,att_1748,att_1749,att_1750,att_1751,att_1752,att_1753,att_1754,att_1755,att_1756,att_1757,att_1758,att_1759,att_1760,att_1761,att_1762,att_1763,att_1764,att_1765,att_1766,att_1767,att_1768,att_1769,att_1770,att_1771,att_1772,att_1773,att_1774,att_1775,att_1776,att_1777,att_1778,att_1779,att_1780,att_1781,att_1782,att_1783,att_1784,att_1785,att_1786,att_1787,att_1788,att_1789,att_1790,att_1791,att_1792,att_1793,att_1794,att_1795,att_1796,att_1797,att_1798,att_1799,att_1800,att_1801,att_1802,att_1803,att_1804,att_1805,att_1806,att_1807,att_1808,att_1809,att_1810,att_1811,att_1812,att_1813,att_1814,att_1815,att_1816,att_1817,att_1818,att_1819,att_1820,att_1821,att_1822,att_1823,att_1824,att_1825,att_1826,att_1827,att_1828,att_1829,att_1830,att_1831,att_1832,att_1833,att_1834,att_1835,att_1836,att_1837,att_1838,att_1839,att_1840,att_1841,att_1842,att_1843,att_1844,att_1845,att_1846,att_1847,att_1848,att_1849,att_1850,att_1851,att_1852,att_1853,att_1854,att_1855,att_1856,att_1857,att_1858,att_1859,att_1860,att_1861,att_1862,att_1863,att_1864,att_1865,att_1866,att_1867,att_1868,att_1869,att_1870,att_1871,att_1872,att_1873,att_1874,att_1875,att_1876,att_1877,att_1878,att_1879,att_1880,att_1881,att_1882,att_1883,att_1884,att_1885,att_1886,att_1887,att_1888,att_1889,att_1890,att_1891,att_1892,att_1893,att_1894,att_1895,att_1896,att_1897,att_1898,att_1899,att_1900,att_1901,att_1902,att_1903,att_1904,att_1905,att_1906,att_1907,att_1908,att_1909,att_1910,att_1911,att_1912,att_1913,att_1914,att_1915,att_1916,att_1917,att_1918,att_1919,att_1920,att_1921,att_1922,att_1923,att_1924,att_1925,att_1926,att_1927,att_1928,att_1929,att_1930,att_1931,att_1932,att_1933,att_1934,att_1935,att_1936,att_1937,att_1938,att_1939,att_1940,att_1941,att_1942,att_1943,att_1944,att_1945,att_1946,att_1947,att_1948,att_1949,att_1950,att_1951,att_1952,att_1953,att_1954,att_1955,att_1956,att_1957,att_1958,att_1959,att_1960,att_1961,att_1962,att_1963,att_1964,att_1965,att_1966,att_1967,att_1968,att_1969,att_1970,att_1971,att_1972,att_1973,att_1974,att_1975,att_1976,att_1977,att_1978,att_1979,att_1980,att_1981,att_1982,att_1983,att_1984,att_1985,att_1986,att_1987,att_1988,att_1989,att_1990,att_1991,att_1992,att_1993,att_1994,att_1995,att_1996,att_1997,att_1998,att_1999,att_2000,HasTumor

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,HasTumor,category,0.0,0.0,2.0,"Yes, No"
1,att_1,float64,0.0,0.0,62.0,"2.0808, -2.3456, 0.4512, 0.1736, -0.5528, -1.6337, -1.1546, -1.7652, 1.4834, -0.953"
2,att_2,float64,0.0,0.0,62.0,"1.0991, -1.2664, 1.5331, -0.087, -0.395, 1.225, -1.1395, 0.4341, 0.5672, 1.1079"
3,att_3,float64,0.0,0.0,62.0,"0.9278, -1.2953, 1.4932, 0.0493, -0.0674, 1.0365, -0.8528, 0.3975, 0.5733, 1.3285"
4,att_4,float64,0.0,0.0,62.0,"1.0291, -1.8666, 0.1087, 0.1546, -1.4685, 1.1086, -1.8056, -2.1802, -0.2029, -1.6446"
5,att_5,float64,0.0,0.0,62.0,"-0.1308, -0.6652, 0.1187, -0.8546, 0.9867, -2.1212, 1.2116, -0.4822, 1.1082, -0.0742"
6,att_6,float64,0.0,0.0,62.0,"1.2655, -0.3256, 0.3596, 0.3957, -0.951, 0.0875, -0.0432, 0.5799, 1.6272, -0.7767"
7,att_7,float64,0.0,0.0,62.0,"-0.4363, -0.1646, -0.0807, -0.5017, -0.5648, 0.2854, 1.0209, 0.0072, 1.2024, -1.4058"
8,att_8,float64,0.0,0.0,62.0,"0.7289, -0.1915, 1.088, -0.6068, 0.9063, -0.4536, 0.4752, -0.3964, -0.094, -0.3387"
9,att_9,float64,0.0,0.0,62.0,"2.108, -1.8555, 0.0418, 0.4277, -0.3363, 0.2922, -0.7338, -2.1862, 0.7798, -0.5836"
10,att_10,float64,0.0,0.0,62.0,"1.3599, -1.1796, 0.3298, 0.6713, -0.8527, 0.0929, -0.2204, 0.3604, 0.5408, 1.3705"
11,att_11,float64,0.0,0.0,62.0,"0.2655, 0.3964, 1.3404, 0.2469, 0.056, -0.5996, 0.33, -0.4797, 0.0755, 0.1952"
12,att_12,float64,0.0,0.0,62.0,"-0.3244, -0.6395, 0.9725, -0.7205, 0.9981, 0.0218, 0.6036, -0.8082, -0.3015, -0.1594"
13,att_13,float64,0.0,0.0,62.0,"-1.2009, 0.1565, 0.4413, -0.6888, -0.8721, 0.3342, -0.3682, 0.2149, -0.5079, -1.4255"
14,att_14,float64,0.0,0.0,62.0,"-1.5319, -0.2611, 0.1053, -0.7509, 0.0634, -2.3195, 0.0717, 0.7609, -0.1423, -0.2322"
15,att_15,float64,0.0,0.0,62.0,"0.298, 0.181, 0.9664, -0.2429, 0.772, -0.7153, 0.922, -0.3343, 1.0498, -0.2759"
16,att_16,float64,0.0,0.0,62.0,"0.0883, 0.0255, 0.0239, -0.7224, -1.3403, -0.0628, -1.3869, 0.5292, -0.3163, -1.7207"
17,att_17,float64,0.0,0.0,62.0,"0.6446, 0.7259, 0.4003, 1.1129, 1.6732, -2.2788, 1.6435, 0.511, 1.0022, -0.6519"
18,att_18,float64,0.0,0.0,62.0,"-0.6509, -0.1802, 0.7944, 0.8561, 1.2597, -1.7616, 0.2351, -0.1122, -0.6011, -0.6364"
19,att_19,float64,0.0,0.0,62.0,"-0.891, -0.4373, -0.242, -0.0225, 0.0229, -0.514, 0.823, 0.3786, 1.6391, -1.5774"
20,att_20,float64,0.0,0.0,62.0,"-0.1857, -0.2042, -0.6539, -0.6758, -1.036, 1.0379, 0.4361, 0.6339, 1.1618, -1.4653"
21,att_21,float64,0.0,0.0,62.0,"1.396, -1.8362, -1.2089, 0.7942, -1.2625, -0.4006, -1.398, -0.7534, 1.1951, -1.1813"
22,att_22,float64,0.0,0.0,62.0,"-0.8321, 0.271, 0.4446, -0.5746, 1.0368, -1.1816, 0.5032, -0.0781, -0.0626, 0.0003"
23,att_23,float64,0.0,0.0,62.0,"2.1155, -0.582, -0.9371, 0.0144, -0.7387, -0.2451, -0.0889, -1.2799, 1.802, -0.7656"
24,att_24,float64,0.0,0.0,62.0,"1.3474, -0.2862, 1.075, 1.3721, -0.7027, -0.2784, -0.2735, -0.0634, -0.0429, 1.2408"
25,att_25,float64,0.0,0.0,62.0,"0.3197, -0.3946, 0.7957, -0.5891, 0.6671, -0.519, 0.4527, -1.0039, -0.216, -0.322"
26,att_26,float64,0.0,0.0,62.0,"0.2061, -0.3615, 0.5708, 0.2864, 1.2464, -0.3849, 1.5927, -0.7402, 1.4067, 0.306"
27,att_27,float64,0.0,0.0,62.0,"-0.3772, -0.2288, 1.0536, -0.5042, 1.2108, -0.11, 0.883, -0.6127, -0.0925, 0.0649"
28,att_28,float64,0.0,0.0,62.0,"-1.6076, 0.5521, 0.6673, -0.1607, 1.565, -2.1608, 1.9504, -0.2497, 0.5624, -0.2049"
29,att_29,float64,0.0,0.0,62.0,"0.8567, -0.3111, 0.3117, 0.2586, -0.6583, 0.2526, 0.3339, 0.6926, 1.3645, -0.8857"
30,att_30,float64,0.0,0.0,62.0,"-0.2082, -0.2101, 0.5056, 0.4809, 0.4879, -1.8203, -0.0665, 0.7829, -0.8359, 0.0339"
31,att_31,float64,0.0,0.0,62.0,"-0.2274, 1.2156, 0.0217, -0.032, 1.1437, -0.2734, 1.7183, -0.8147, 1.0421, -0.411"
32,att_32,float64,0.0,0.0,62.0,"0.4553, -1.3176, -1.2106, 0.9763, -2.294, -0.8471, -1.5701, 1.3421, 0.4278, 0.5842"
33,att_33,float64,0.0,0.0,62.0,"0.7008, -0.9099, 0.3301, 0.2376, -0.0004, -0.4038, -0.1229, -0.4372, 0.5845, 0.7205"
34,att_34,float64,0.0,0.0,62.0,"1.4608, -0.639, 0.7238, 0.4574, -0.7458, 0.2083, -0.8698, 0.4889, -0.2435, 0.3632"
35,att_35,float64,0.0,0.0,62.0,"-0.1279, -0.9514, 0.7256, -0.5424, -0.3789, 0.8263, -0.0211, -0.0957, -0.2728, -0.4439"
36,att_36,float64,0.0,0.0,62.0,"1.6869, -1.4628, -0.989, 0.7933, -0.5368, -0.6077, -0.0799, -0.5648, 1.5983, -0.7572"
37,att_37,float64,0.0,0.0,62.0,"-1.4004, 0.5965, 0.6049, -0.4688, 0.8446, -1.8835, 1.9535, -0.9883, 0.6768, 0.1091"
38,att_38,float64,0.0,0.0,62.0,"1.3063, -1.3448, 0.6498, 0.5179, -0.5956, 0.6447, -0.421, -0.0242, 0.2773, -0.4228"
39,att_39,float64,0.0,0.0,62.0,"0.6404, -0.7131, -0.4807, 1.2815, -0.5648, -2.5303, -0.3182, 0.7941, -0.3182, -0.3249"
40,att_43,float64,0.0,0.0,62.0,"0.5848, 0.6012, 0.2889, -0.753, 1.5112, -1.158, 1.9343, -0.7792, 1.2171, -0.0935"
41,att_44,float64,0.0,0.0,62.0,"0.7777, -1.3361, 0.0039, 1.2205, -0.5223, 0.0255, -0.6882, 0.0384, -0.21, 0.8773"
42,att_45,float64,0.0,0.0,62.0,"0.946, -0.6862, -0.5562, -1.1252, -1.1499, -0.5745, -1.4924, 1.0821, 0.4596, -0.8077"
43,att_46,float64,0.0,0.0,62.0,"1.4487, -1.4174, 0.1118, 0.8878, -0.2784, 0.3027, -0.6814, -1.1117, 1.4338, -0.1027"
44,att_47,float64,0.0,0.0,62.0,"-0.0162, 0.2563, 0.8047, -0.3375, 1.0565, -0.5271, 1.6432, -0.3308, 1.4785, -0.3602"
45,att_48,float64,0.0,0.0,62.0,"-0.5166, -0.7993, 0.3198, 1.0531, -0.2559, -0.0909, 0.4232, 0.6122, -0.9501, -1.2931"
46,att_49,float64,0.0,0.0,62.0,"0.1508, -1.0406, -1.3165, 0.3285, -1.7948, -0.2161, -2.1831, 0.5487, -0.7707, 0.853"
47,att_50,float64,0.0,0.0,62.0,"1.5729, -0.224, 0.5581, 0.7681, 0.8267, -1.9779, 1.7599, -0.3216, 0.5518, 0.4011"
48,att_54,float64,0.0,0.0,62.0,"-0.6312, 0.0886, 0.5605, 0.2728, -0.2294, 1.1235, 0.8612, 0.2234, 1.3011, -0.7223"
49,att_55,float64,0.0,0.0,62.0,"0.2528, -0.3576, 0.0191, 0.8958, -1.1233, -1.3489, -0.8538, 0.9401, -0.8282, 1.2654"
50,att_56,float64,0.0,0.0,62.0,"-0.356, -0.9527, -0.3972, 0.3827, 1.9842, -3.5476, 0.2793, 0.6677, 0.134, 0.1571"
51,att_57,float64,0.0,0.0,62.0,"-1.8976, 0.3919, 0.713, 0.0413, 1.9356, -1.2602, 1.2004, -0.3057, -0.4928, -0.517"
52,att_58,float64,0.0,0.0,62.0,"-0.4336, 0.2684, 0.4544, -0.5478, -0.9369, 1.0791, -0.4925, 0.2478, 1.4349, -1.1237"
53,att_59,float64,0.0,0.0,62.0,"1.9947, -0.4805, -0.0754, 0.9352, -1.3809, 0.1219, -1.7581, 1.4023, 0.2552, 1.7483"
54,att_60,float64,0.0,0.0,62.0,"-0.0186, 0.3117, 1.0305, 0.1866, 1.4211, -1.229, 1.4866, -0.4633, 0.6472, -0.7315"
55,att_61,float64,0.0,0.0,62.0,"0.0613, -0.5789, -0.3721, -0.0952, -0.056, -1.5071, 0.4154, 0.3915, -0.2351, -1.3371"
56,att_62,float64,0.0,0.0,62.0,"-0.6047, 0.8327, 0.9083, -0.466, 1.9322, -0.3563, 1.7594, -0.8214, 0.7953, -0.1739"
57,att_63,float64,0.0,0.0,62.0,"0.9059, -0.8265, -1.4403, 0.392, -0.821, -1.3454, -0.3375, -0.9417, 1.253, -0.9068"
58,att_64,float64,0.0,0.0,62.0,"-0.7824, 0.621, 0.5172, -0.1466, 0.8974, 0.3574, 1.8148, -0.4917, 0.1461, -1.4938"
59,att_65,float64,0.0,0.0,62.0,"0.9644, -1.2002, -0.209, 1.0997, -0.9096, 0.1086, -1.589, -1.5573, -0.9787, 1.1327"
60,att_66,float64,0.0,0.0,62.0,"0.017, -1.1656, -0.8906, -0.8017, 0.0961, -1.6786, -0.4868, 1.1184, -0.3588, -0.8439"
61,att_67,float64,0.0,0.0,62.0,"0.1169, -0.4433, -1.5204, 0.3155, -1.2915, -0.7193, -1.5205, 1.5232, 0.8584, -0.8818"
62,att_68,float64,0.0,0.0,62.0,"-0.7332, 0.6842, -0.1744, -1.4125, -0.0952, 1.0181, 0.9253, 0.3202, 1.2579, -1.819"
63,att_69,float64,0.0,0.0,62.0,"-0.4683, -2.5783, 0.08, 0.6913, -0.5204, 0.0406, 0.3255, 1.2948, 0.0783, -1.2011"
64,att_70,float64,0.0,0.0,62.0,"-0.3613, -1.0716, -1.1446, 1.1695, -0.9872, -0.0409, -1.4148, 0.2303, -0.9254, 0.3877"
65,att_71,float64,0.0,0.0,62.0,"1.5912, 0.4687, -0.0894, 1.4811, 0.1471, -0.634, -0.0026, 0.7609, 0.3944, 0.1286"
66,att_72,float64,0.0,0.0,62.0,"-0.7342, 1.2254, 1.0625, 0.6219, 1.6367, -1.8772, 2.01, -0.8543, -0.0204, -0.0874"
67,att_73,float64,0.0,0.0,62.0,"0.6522, 0.0585, -0.583, -0.7453, -1.3568, 1.693, -0.6152, -1.5332, -1.7237, -1.3945"
68,att_74,float64,0.0,0.0,62.0,"0.4061, -0.1053, 0.7562, -0.3242, 1.2653, -0.071, 0.5136, -0.2552, -0.2504, 0.1058"
69,att_75,float64,0.0,0.0,62.0,"1.4623, -1.1174, 0.6857, 1.3401, 0.467, 0.6098, 0.3028, -2.0236, 1.0796, -0.614"
70,att_76,float64,0.0,0.0,62.0,"-0.4872, -1.6094, -0.3819, 0.4423, -0.7159, 1.872, -0.3902, -0.0601, -0.374, -1.4248"
71,att_77,float64,0.0,0.0,62.0,"-0.4571, 0.4269, 0.2092, -0.8382, 1.1741, -2.2135, 0.5997, 0.4654, 0.2164, -0.7939"
72,att_78,float64,0.0,0.0,62.0,"-0.158, -0.4362, -1.0089, -0.2429, -0.9687, -0.8054, -0.8266, 0.0189, 0.1837, -1.091"
73,att_79,float64,0.0,0.0,62.0,"-0.3561, -0.3626, 1.0825, -0.3973, 1.3549, 0.1955, 1.1606, -0.3722, -2.1726, 0.2986"
74,att_80,float64,0.0,0.0,62.0,"-0.6805, -0.5498, -0.622, -0.4024, -0.9156, 0.4849, -1.1601, 0.6688, -0.1131, -1.5734"
75,att_81,float64,0.0,0.0,62.0,"0.7476, -0.0006, -0.4298, -0.338, -1.1816, 1.819, -0.6502, -1.711, -1.7305, -1.3266"
76,att_82,float64,0.0,0.0,62.0,"-1.6627, 0.7697, 0.6626, -0.0266, 0.5232, -0.6901, 1.0884, 0.0174, -0.7673, -0.3011"
77,att_83,float64,0.0,0.0,62.0,"-0.9251, -0.6324, 1.4025, 0.7755, 0.6746, 1.1222, -0.2274, -2.0873, 0.3566, 0.0193"
78,att_84,float64,0.0,0.0,62.0,"-2.2913, -0.8938, 0.4624, -0.2462, -0.5144, -0.1693, -0.1175, 0.886, -1.7246, -0.7182"
79,att_85,float64,0.0,0.0,62.0,"-0.1657, 0.3082, 0.8799, 0.0607, 0.0283, 0.3895, 1.2454, 0.1824, 0.2203, -1.7247"
80,att_86,float64,0.0,0.0,62.0,"0.4642, 0.1408, 1.2268, 0.5131, 1.7881, -0.5594, 1.8746, -0.5923, 0.4881, 0.0175"
81,att_87,float64,0.0,0.0,62.0,"0.8758, -0.7795, -0.3077, 0.2447, -2.2166, 0.0471, -1.755, 1.1092, 0.2409, 1.6078"
82,att_88,float64,0.0,0.0,62.0,"-0.9187, 0.2919, -0.2505, -0.7705, -0.6853, 0.6317, 1.3328, 0.4715, 1.4259, -0.4773"
83,att_89,float64,0.0,0.0,62.0,"0.0959, -0.6027, -0.087, -0.3025, -0.2441, 1.6867, -0.0285, -0.6692, 0.7931, -0.4368"
84,att_90,float64,0.0,0.0,62.0,"0.2499, -0.8581, -0.1412, -0.8516, -1.0575, 1.62, -0.7413, -1.2323, -0.9822, -1.6864"
85,att_91,float64,0.0,0.0,62.0,"-0.8074, 0.8705, -0.4218, 0.0031, 1.4205, -1.09, 1.8756, -0.4194, 1.6692, -1.365"
86,att_92,float64,0.0,0.0,62.0,"-0.1925, -0.1383, 0.2792, -0.7932, 0.1064, 0.6478, -1.2807, 1.6807, -0.7455, 0.9248"
87,att_93,float64,0.0,0.0,62.0,"-0.8002, 0.1451, 0.3027, -1.6008, 0.123, -0.207, 0.821, 0.442, 0.1251, -1.4243"
88,att_94,float64,0.0,0.0,62.0,"0.8811, -1.6039, 0.1986, 0.9761, -0.7677, 0.632, -0.2387, 0.0113, 0.6668, 0.0894"
89,att_95,float64,0.0,0.0,62.0,"-1.2246, -0.0986, 0.2993, 0.1328, 1.604, -0.1196, 1.6454, -0.6906, -0.0149, -0.7946"
90,att_96,float64,0.0,0.0,62.0,"1.5095, -1.1465, -0.5018, -0.4242, -1.5402, 1.3986, -0.9243, 0.1955, -0.525, -0.2543"
91,att_97,float64,0.0,0.0,62.0,"-0.8163, 0.1713, 1.0135, -0.6668, 1.2781, -0.3381, 0.8226, -0.3465, 0.1582, 0.3295"
92,att_98,float64,0.0,0.0,62.0,"1.0996, -2.2016, 0.2877, 1.7716, -0.7692, -0.8963, -1.1742, -1.3002, 1.2236, -0.9951"
93,att_99,float64,0.0,0.0,62.0,"-1.7049, 0.504, -0.7732, -0.0164, 0.5245, -0.1005, 1.0555, 0.4622, 0.2952, -1.8763"
94,att_100,float64,0.0,0.0,62.0,"0.2649, -0.002, 0.9391, 0.2537, -0.1249, 0.3929, 0.1455, 0.0762, 1.9927, 0.5174"
95,att_101,float64,0.0,0.0,62.0,"0.6301, 0.5295, -0.2039, 0.835, -0.0375, -0.3355, 0.348, 0.7351, -0.4448, 1.6739"
96,att_102,float64,0.0,0.0,62.0,"0.9758, -0.5232, -0.6099, 0.6404, 0.1717, 0.4432, 0.5608, -1.0179, 1.6446, -0.7207"
97,att_103,float64,0.0,0.0,62.0,"-1.6294, 1.2658, -0.3561, -0.2131, 1.0554, -1.5213, 1.5128, -0.2816, -0.1404, -1.1623"
98,att_104,float64,0.0,0.0,62.0,"0.3606, 0.4445, 0.4042, -0.3452, 0.9589, -1.0576, 1.1203, -0.0874, -0.3917, -0.0863"
99,att_105,float64,0.0,0.0,62.0,"0.1981, -0.0231, -0.2676, -0.7004, -0.0913, 0.2477, 1.6758, 0.0941, 1.6193, -0.9694"
100,att_106,float64,0.0,0.0,62.0,"1.3033, -1.2184, 0.33, 0.6979, -0.3638, 0.4154, 0.0487, -0.8224, 0.4885, -0.803"
101,att_107,float64,0.0,0.0,62.0,"0.1328, 0.2893, 0.4159, 0.3991, 1.0515, -1.528, 1.5478, -0.398, 0.7428, -0.4227"
102,att_108,float64,0.0,0.0,62.0,"1.3672, -2.1771, -0.1878, 0.2282, -1.1503, 1.2073, -1.6337, -2.4522, -0.4965, -1.7705"
103,att_109,float64,0.0,0.0,62.0,"-1.0165, 0.0641, 0.2333, -1.6575, 0.2603, -0.0845, 1.2739, 0.3098, 0.4571, -1.2218"
104,att_110,float64,0.0,0.0,62.0,"1.2239, -0.8683, -0.721, -0.6003, -1.2816, 1.2968, -0.748, -0.5167, -0.6496, -0.8851"
105,att_111,float64,0.0,0.0,62.0,"0.1951, -1.5131, 0.2028, -0.0327, -1.005, -1.0106, -1.5736, 1.6435, -0.3183, 0.9966"
106,att_112,float64,0.0,0.0,62.0,"1.0496, -0.3657, -0.619, 0.1579, -0.8156, 1.5511, -0.4109, -0.4996, -0.0882, -1.2981"
107,att_113,float64,0.0,0.0,62.0,"-1.2502, 0.9016, 1.4737, -1.3214, 1.8439, -0.0321, 1.5995, -0.1278, 0.6316, 0.1664"
108,att_114,float64,0.0,0.0,62.0,"-1.1508, 1.1139, 1.3451, 0.2835, 1.6448, -1.9781, 1.4774, -0.3929, -0.0687, -0.244"
109,att_115,float64,0.0,0.0,62.0,"-0.8431, -0.7184, -0.0455, 1.0167, 0.4939, -1.0899, -0.1155, -0.5204, -1.9985, 0.88"
110,att_116,float64,0.0,0.0,62.0,"-2.0837, 1.8747, -0.4775, -0.7561, 1.0187, -0.5699, -0.6449, -1.0253, -1.1311, 0.0064"
111,att_117,float64,0.0,0.0,62.0,"-1.4433, -0.2107, 0.4532, -1.3039, -1.1728, -1.4816, -0.8211, 0.4334, 0.8371, 1.2998"
112,att_118,float64,0.0,0.0,62.0,"-1.9262, -0.2363, -0.223, 2.4667, 1.5125, -0.6217, 0.6699, -0.4263, -1.3003, 0.6351"
113,att_119,float64,0.0,0.0,62.0,"0.3304, 0.1011, 0.6042, -0.0251, -0.8295, 0.3604, -2.3951, 0.754, 0.3132, 0.5848"
114,att_120,float64,0.0,0.0,62.0,"-0.2459, -0.6367, -0.7092, 0.093, -0.1963, -0.9642, -0.9146, 0.1197, -0.9539, -0.8396"
115,att_121,float64,0.0,0.0,62.0,"0.9205, -1.8006, -1.1872, 0.8773, -1.6471, -1.1685, -1.7488, -0.1304, 0.1948, -1.6343"
116,att_122,float64,0.0,0.0,62.0,"0.8297, -1.2938, 0.0453, -0.1097, -0.8356, 1.1007, -0.7878, -0.5868, 0.4563, -0.5809"
117,att_123,float64,0.0,0.0,62.0,"0.8614, 0.2863, -0.6778, -1.039, -1.084, 0.4621, -0.6198, -0.1378, 0.1019, -1.1954"
118,att_124,float64,0.0,0.0,62.0,"-1.5307, 2.0305, -0.597, -0.9863, -0.3291, 0.2034, -0.4797, 0.3386, -0.3079, -0.4116"
119,att_125,float64,0.0,0.0,62.0,"1.9905, -0.4405, -0.1369, 0.8968, -1.386, 0.3439, -1.8041, 1.5355, 0.2588, 1.7574"
120,att_126,float64,0.0,0.0,62.0,"1.3664, -1.4153, 1.0876, 0.2759, -0.54, 1.0951, -0.5748, 0.4221, -0.0918, 1.3502"
121,att_127,float64,0.0,0.0,62.0,"-0.3496, 0.9885, 0.3534, -0.1429, 1.6285, -0.5708, 2.1524, -0.7503, 1.722, -0.4307"
122,att_128,float64,0.0,0.0,62.0,"-1.3743, 1.1444, 0.4283, 0.1869, 1.6607, -1.9862, 1.5309, -0.3057, -0.3566, -0.6241"
123,att_129,float64,0.0,0.0,62.0,"0.4568, 0.5046, 0.362, -0.3655, 0.795, -0.4704, 0.636, -0.0221, -0.2836, -0.8573"
124,att_130,float64,0.0,0.0,62.0,"-1.158, 0.2661, 0.3539, -0.6882, 0.9937, -1.8314, 1.3722, 0.222, 0.3166, -0.2196"
125,att_131,float64,0.0,0.0,62.0,"1.5266, -1.7587, -0.4065, 0.1543, -1.0865, 1.3596, -1.0932, -2.2721, -0.392, -1.6463"
126,att_132,float64,0.0,0.0,62.0,"-0.9395, 0.3553, -0.4993, -1.4951, 0.4562, -0.885, -0.2977, 0.7768, -0.4721, -0.1855"
127,att_133,float64,0.0,0.0,62.0,"1.6039, -1.1917, 0.0653, 0.8301, -1.4982, -0.8559, -1.5244, 0.6341, 1.4223, 0.6684"
128,att_134,float64,0.0,0.0,62.0,"0.4276, -1.0798, -1.3141, 0.4113, -1.0182, -0.1446, -1.1358, -0.9464, 0.3001, -0.2025"
129,att_135,float64,0.0,0.0,62.0,"-0.1706, 1.4466, 0.4782, -0.7359, 0.6811, -0.5916, 0.6497, 0.3789, -0.4294, -0.7289"
130,att_136,float64,0.0,0.0,62.0,"-0.8294, 1.3793, 0.7812, -0.0311, 1.4774, -0.8446, 1.871, -0.4091, 1.2449, -0.6382"
131,att_137,float64,0.0,0.0,62.0,"1.3025, -1.3346, -1.7365, -0.3826, -2.3721, -0.7978, -2.4567, -0.9913, -0.2805, -0.8595"
132,att_138,float64,0.0,0.0,62.0,"-1.2513, 0.9538, 1.1778, -0.4407, 2.1384, -0.6374, 2.0161, -1.6086, 0.657, -0.5932"
133,att_139,float64,0.0,0.0,62.0,"0.5515, 0.7819, 0.5436, -0.405, 1.0744, -0.1364, 1.656, -0.8181, 0.248, 0.0915"
134,att_140,float64,0.0,0.0,62.0,"0.947, 0.0736, 0.5312, 0.797, -0.6073, -1.1595, 0.5042, 0.6624, 1.1112, 1.0832"
135,att_141,float64,0.0,0.0,62.0,"-1.3182, 1.5044, 0.4804, 0.9638, 1.5221, -1.1259, 1.18, -0.3833, -0.4802, -0.0385"
136,att_142,float64,0.0,0.0,62.0,"-1.3734, 1.9227, -0.5578, -0.6632, -0.2604, 0.0556, -0.3858, 0.0485, -0.0235, -0.2822"
137,att_143,float64,0.0,0.0,62.0,"-0.0524, 0.0179, -0.8161, -0.6045, -0.4432, -1.3833, -0.2573, 1.057, -1.0593, -1.0571"
138,att_144,float64,0.0,0.0,62.0,"-0.5156, 0.1701, 0.2683, 0.0323, 0.0763, -0.3098, 1.1235, 0.6066, -2.0176, -0.5615"
139,att_145,float64,0.0,0.0,62.0,"-0.7373, 0.7439, 0.1981, -0.9969, -0.0372, 0.0648, 0.9037, 0.8371, 0.0695, -1.5984"
140,att_146,float64,0.0,0.0,62.0,"0.127, -1.1728, -0.3641, -1.2582, 0.338, 0.2333, 0.7901, 0.3657, -1.6056, -0.5062"
141,att_147,float64,0.0,0.0,62.0,"0.1755, 1.5548, 0.9259, 1.5498, 1.2444, 0.9286, 1.407, -1.3356, -1.1362, 0.7505"
142,att_148,float64,0.0,0.0,62.0,"0.8708, -0.3784, 1.1529, 1.0373, 0.1183, 0.508, -0.0645, -1.3238, -0.748, 1.0111"
143,att_149,float64,0.0,0.0,62.0,"1.4811, -1.0967, -0.199, 0.436, -0.5784, -0.2096, -0.2591, 0.019, 1.3514, 0.1478"
144,att_150,float64,0.0,0.0,62.0,"0.7893, -0.7712, 0.479, 0.5079, -0.4138, 0.3248, -0.1057, -0.9813, 1.0396, -0.6191"
145,att_151,float64,0.0,0.0,62.0,"-0.2754, 0.0784, 0.9586, 0.0876, 0.9804, 0.0423, 0.8432, -0.4074, 0.212, 0.1596"
146,att_152,float64,0.0,0.0,62.0,"-0.4288, 0.5515, 0.0367, -0.2714, -1.2576, 0.7318, -1.7196, -0.6842, -0.436, 0.7006"
147,att_153,float64,0.0,0.0,62.0,"0.7096, 0.0398, 0.3602, -1.0236, -0.5396, 0.3998, -1.5973, 1.6881, 1.2084, 1.7749"
148,att_154,float64,0.0,0.0,62.0,"-1.3176, 0.6235, 1.2763, -0.1472, 1.1136, -1.8806, 0.3944, 0.6294, -0.1586, 0.5654"
149,att_155,float64,0.0,0.0,62.0,"-1.3559, 1.1835, 0.5632, -1.3534, -0.1101, 1.2271, -0.6764, 0.4077, 0.1713, 0.0044"
150,att_156,float64,0.0,0.0,62.0,"0.8827, -0.7399, 0.2474, -0.6083, -1.1793, -0.1221, -1.3457, 1.2132, 0.3824, 1.0574"
151,att_157,float64,0.0,0.0,62.0,"-0.0589, -0.1582, -0.2396, 0.6203, 1.2951, 1.0013, -1.2187, -1.5144, 1.1315, 0.2017"
152,att_158,float64,0.0,0.0,62.0,"-0.19, 0.3439, 0.4056, -0.3861, -1.1299, 2.9275, -0.7295, -0.3327, -0.6628, -2.0062"
153,att_159,float64,0.0,0.0,62.0,"-1.0565, -0.8776, 0.7247, 0.559, 1.0567, 0.2709, -0.4121, 0.2811, -1.632, 0.6736"
154,att_160,float64,0.0,0.0,62.0,"0.1159, 0.5365, -1.8223, -1.6107, -2.4008, 0.4935, -0.9949, -0.4396, -1.0349, -0.5706"
155,att_161,float64,0.0,0.0,62.0,"1.3178, -0.8906, 1.0158, 0.4836, -0.7371, 0.937, -0.7904, -0.8505, -1.2095, 1.2204"
156,att_162,float64,0.0,0.0,62.0,"1.8367, -1.4019, 0.4259, -0.148, -1.2416, 1.4948, -1.2441, 0.4018, 0.5679, 1.7398"
157,att_163,float64,0.0,0.0,62.0,"-0.4993, 0.4203, 1.452, -0.1067, 2.0559, -0.3997, 1.2241, 0.0417, 0.6633, 0.6051"
158,att_164,float64,0.0,0.0,62.0,"-1.7922, 0.5179, 0.1348, 1.5314, 1.1153, -0.8899, 0.5071, -0.6407, -0.8821, 0.3055"
159,att_165,float64,0.0,0.0,62.0,"-0.4683, 1.507, 1.6038, 0.6969, 1.711, -2.0476, 2.0602, -0.5089, 0.1725, -0.5088"
160,att_166,float64,0.0,0.0,62.0,"-0.468, 0.2725, -0.1481, -0.9387, -0.6073, -0.2758, -0.7496, 0.6958, -0.6111, -1.8704"
161,att_167,float64,0.0,0.0,62.0,"0.7714, -0.2356, 0.7722, 0.3217, -0.3401, -0.307, -2.9632, -0.4619, 0.3815, -0.0017"
162,att_168,float64,0.0,0.0,62.0,"-0.0816, -0.2558, -0.5247, 0.1717, -0.453, 1.0334, -0.673, 1.0355, -1.1083, -1.2042"
163,att_169,float64,0.0,0.0,62.0,"-0.296, 0.6243, -0.965, -0.7696, -1.6322, 0.8431, -1.1912, 0.9768, -0.0143, -1.6047"
164,att_170,float64,0.0,0.0,62.0,"-2.1208, 0.7474, 0.9448, -0.3865, 1.5045, -1.5152, 1.2993, 0.1853, 0.1305, 0.2978"
165,att_171,float64,0.0,0.0,62.0,"-1.8281, -0.6214, 0.9296, 0.4555, 1.235, 0.0205, -0.4302, 0.5262, 0.1448, 0.5083"
166,att_172,float64,0.0,0.0,62.0,"-0.0224, 1.2146, -0.6633, -0.6777, -1.2261, -0.9159, -0.1815, 0.6557, 0.3655, -1.033"
167,att_173,float64,0.0,0.0,62.0,"-1.4098, 0.675, -0.6244, 0.2955, 1.3383, -2.0198, 1.7168, 0.1161, -0.1188, -0.8181"
168,att_174,float64,0.0,0.0,62.0,"-0.8216, -0.2343, 1.0521, -1.7917, -0.4009, 1.4807, 0.5264, 0.2884, 0.1007, -1.6595"
169,att_175,float64,0.0,0.0,62.0,"1.1608, -0.2214, 1.0094, 0.2257, -0.6082, 1.0954, -0.4255, -2.1808, -2.1158, 1.0167"
170,att_176,float64,0.0,0.0,62.0,"-1.5166, -0.9227, -0.0974, -0.0125, 0.5395, 1.3287, -0.2948, -0.4485, -0.6025, -1.0821"

In [6]:
# Numeric Feature Statistics
numeric_stats

          count          mean       std      min      max
att_1      62.0  1.774194e-07  1.000000 -2.34557  2.08075
att_2      62.0  9.677419e-08  1.000000 -2.62049  1.69310
att_3      62.0 -1.451613e-07  1.000000 -2.76391  1.55925
att_4      62.0  8.064516e-08  1.000000 -2.18024  2.52569
att_5      62.0  4.838710e-08  1.000000 -2.12120  2.89500
att_6      62.0 -3.225806e-08  1.000000 -2.98831  1.62717
att_7      62.0  6.451613e-08  1.000000 -2.34981  1.74813
att_8      62.0  9.677419e-08  1.000000 -2.44796  2.68992
att_9      62.0 -4.838710e-08  1.000000 -2.92951  2.10798
att_10     62.0  9.677419e-08  1.000000 -2.67227  2.25484
att_11     62.0  1.129032e-07  1.000000 -2.35261  2.25884
att_12     62.0 -1.935484e-07  0.999999 -1.53331  2.98745
att_13     62.0 -2.419355e-07  1.000000 -2.16672  2.93557
att_14     62.0  3.225806e-08  1.000000 -2.31952  2.08865
att_15     62.0  1.129032e-07  1.000000 -2.93927  2.00340
att_16     62.0 -4.838710e-08  1.000000 -3.47401  2.31307
att_17     62.0 -4.193548e-07  1.000000 -2.27882  1.82446
att_18     62.0  1.774194e-07  1.000000 -2.33838  2.36600
att_19     62.0 -9.677419e-08  1.000000 -2.60753  2.06809
att_20     62.0  9.677419e-08  1.000000 -2.37904  1.96768
att_21     62.0  1.612903e-07  1.000001 -2.33451  2.38927
att_22     62.0 -2.741935e-07  1.000000 -3.34464  2.54265
att_23     62.0 -2.258065e-07  1.000000 -2.23396  2.42954
att_24     62.0  8.064516e-08  1.000000 -2.64375  1.78723
att_25     62.0  1.290323e-07  1.000000 -2.30345  2.75998
att_26     62.0 -8.064516e-08  1.000000 -2.07869  1.75984
att_27     62.0  1.290323e-07  1.000000 -2.05768  2.84023
att_28     62.0  1.612903e-08  1.000000 -2.34728  1.95036
att_29     62.0 -6.451613e-08  1.000000 -2.80102  1.80559
att_30     62.0  1.129032e-07  1.000000 -2.07485  2.00576
att_31     62.0  8.064516e-08  1.000000 -2.10507  1.75668
att_32     62.0 -1.935484e-07  1.000000 -2.69277  2.01843
att_33     62.0  9.677419e-08  1.000000 -2.61553  2.18428
att_34     62.0 -1.612903e-08  1.000000 -4.17451  1.99541
att_35     62.0 -1.612903e-08  1.000000 -2.41675  2.84892
att_36     62.0 -9.677419e-08  1.000000 -2.60429  2.02276
att_37     62.0 -1.612903e-07  1.000000 -2.05603  2.54660
att_38     62.0 -1.290323e-07  1.000000 -2.74708  2.14069
att_39     62.0 -1.129032e-07  1.000000 -2.83750  1.80924
att_43     62.0 -1.129032e-07  1.000000 -2.36283  2.00285
att_44     62.0 -3.709677e-07  1.000000 -2.90865  1.83035
att_45     62.0  1.129032e-07  1.000000 -2.16456  2.36841
att_46     62.0  2.580645e-07  0.999999 -2.40173  2.29443
att_47     62.0 -2.580645e-07  1.000000 -2.50696  1.78758
att_48     62.0  1.612903e-08  1.000000 -2.09988  2.12399
att_49     62.0  5.000000e-07  1.000000 -2.56030  1.77726
att_50     62.0 -4.838710e-08  1.000000 -1.97786  2.78476
att_54     62.0 -1.612903e-08  1.000000 -2.56087  1.70497
att_55     62.0 -1.935484e-07  1.000000 -3.31866  1.84604
att_56     62.0  2.258065e-07  0.999999 -3.54758  1.98422
att_57     62.0 -2.258065e-07  1.000000 -1.91125  1.93556
att_58     62.0  5.806452e-07  1.000000 -2.08937  2.04222
att_59     62.0  1.451613e-07  1.000000 -2.07756  1.99465
att_60     62.0 -4.838710e-08  1.000000 -2.29969  1.99054
att_61     62.0  5.000000e-07  1.000000 -2.07240  2.39352
att_62     62.0  2.258065e-07  1.000000 -2.04036  2.14123
att_63     62.0 -1.129032e-07  1.000000 -2.34905  2.29426
att_64     62.0 -4.838710e-08  1.000000 -2.07070  1.99064
att_65     62.0  6.451613e-08  1.000000 -2.44795  1.68628
att_66     62.0  1.774194e-07  1.000000 -1.94371  2.08643
att_67     62.0 -3.709677e-07  1.000000 -2.15622  1.93345
att_68     62.0 -1.935484e-07  1.000000 -1.91349  1.61950
att_69     62.0  9.677419e-08  1.000000 -2.57825  1.81931
att_70     62.0  9.677419e-08  1.000000 -3.01615  1.99496
att_71     62.0  1.129032e-07  0.999999 -2.48868  2.58763
att_72     62.0  1.935484e-07  1.000001 -2.33487  2.01004
att_73     62.0  4.677419e-07  1.000000 -2.12350  2.22018
att_74     62.0  1.935484e-07  1.000000 -2.08691  2.83922
att_75     62.0 -6.451613e-08  1.000000 -2.27738  1.71127
att_76     62.0  3.870968e-07  1.000000 -1.60944  2.06279
att_77     62.0  2.419355e-07  1.000001 -2.44785  2.17441
att_78     62.0  4.838710e-08  1.000000 -3.78391  2.06642
att_79     62.0  4.838710e-08  1.000000 -2.17264  2.02055
att_80     62.0  4.838710e-08  1.000000 -3.36028  2.48925
att_81     62.0 -8.064516e-08  1.000000 -2.16602  2.12316
att_82     62.0 -1.774194e-07  1.000000 -2.56359  1.82503
att_83     62.0 -6.451613e-08  1.000000 -2.33004  1.87347
att_84     62.0 -1.790682e-17  1.000000 -2.53100  2.62912
att_85     62.0 -4.838710e-08  1.000000 -2.42335  2.15725
att_86     62.0 -1.612903e-08  1.000000 -2.42507  1.87463
att_87     62.0  1.612903e-07  1.000000 -2.45700  2.04496
att_88     62.0  1.451613e-07  1.000000 -2.26399  2.00637
att_89     62.0  1.290323e-07  1.000000 -1.97104  1.85270
att_90     62.0  3.225806e-08  1.000000 -1.68643  2.31016
att_91     62.0 -5.322581e-07  1.000000 -1.97788  2.06297
att_92     62.0 -2.258065e-07  1.000000 -3.38793  1.73298
att_93     62.0  1.935484e-07  1.000000 -2.07069  1.96776
att_94     62.0  4.032258e-07  1.000000 -2.69420  1.80224
att_95     62.0 -1.774194e-07  1.000000 -2.21530  1.84344
att_96     62.0 -1.612903e-07  1.000000 -2.17185  2.22844
att_97     62.0  1.612903e-07  1.000000 -1.85390  2.61502
att_98     62.0  2.741935e-07  1.000000 -2.59482  2.01811
att_99     62.0  6.451613e-08  1.000000 -2.31920  1.77500
att_100    62.0 -8.064516e-08  1.000000 -2.44875  1.99265
att_101    62.0  8.064516e-08  1.000000 -2.84772  2.03185
att_102    62.0 -1.935484e-07  1.000000 -2.17993  1.64464
att_103    62.0 -1.935484e-07  1.000000 -2.84655  1.51280
att_104    62.0  2.903226e-07  1.000000 -3.32812  1.55283
att_105    62.0  2.419355e-07  1.000000 -2.20663  2.14745
att_106    62.0 -2.258065e-07  1.000000 -3.06766  1.91141
att_107    62.0  2.258065e-07  1.000000 -3.15086  2.02911
att_108    62.0 -4.838710e-08  1.000000 -2.45219  1.83085
att_109    62.0  1.129032e-07  1.000000 -2.51295  2.00706
att_110    62.0 -3.870968e-07  1.000000 -1.66598  1.88664
att_111    62.0 -1.935484e-07  1.000000 -2.10292  1.66272
att_112    62.0 -1.612903e-07  1.000000 -2.48744  3.27848
att_113    62.0 -2.258065e-07  1.000000 -2.56396  1.84387
att_114    62.0 -6.451613e-08  1.000000 -2.44580  2.15857
att_115    62.0  4.838710e-08  1.000000 -2.33063  2.21627
att_116    62.0 -4.516129e-07  1.000000 -2.08373  2.16555
att_117    62.0 -2.903226e-07  1.000000 -2.49851  2.03871
att_118    62.0 -3.225806e-08  1.000000 -1.92621  2.46666
att_119    62.0  9.677419e-08  1.000000 -2.81705  2.06027
att_120    62.0  3.225806e-08  1.000000 -2.15933  1.90484
att_121    62.0  8.064516e-08  1.000000 -2.32191  1.61228
att_122    62.0 -3.225806e-08  0.999999 -2.62302  2.55351
att_123    62.0  1.612903e-08  1.000001 -2.64239  2.32299
att_124    62.0 -5.322581e-07  1.000000 -1.90277  2.47544
att_125    62.0 -2.580645e-07  1.000000 -2.07262  1.99046
att_126    62.0 -1.612903e-08  1.000000 -2.39515  1.82579
att_127    62.0  1.129032e-07  1.000001 -2.40528  2.15242
att_128    62.0  1.290323e-07  1.000000 -1.98620  1.80439
att_129    62.0 -4.032258e-07  1.000000 -2.50525  2.10374
att_130    62.0  4.838710e-08  1.000000 -1.86110  2.80969
att_131    62.0  4.838710e-08  1.000000 -2.27205  2.71718
att_132    62.0  1.612903e-08  1.000001 -2.54338  2.61034
att_133    62.0  3.225806e-08  1.000000 -2.16225  2.19995
att_134    62.0 -1.290323e-07  1.000000 -1.75517  2.90135
att_135    62.0  3.548387e-07  1.000000 -2.95869  2.08834
att_136    62.0  1.612903e-08  1.000000 -2.09571  2.11610
att_137    62.0  2.258065e-07  1.000000 -2.45666  2.44045
att_138    62.0  2.419355e-07  1.000000 -1.99255  2.13840
att_139    62.0  1.451613e-07  1.000000 -2.42333  2.44768
att_140    62.0  1.612903e-07  1.000001 -2.73019  1.72625
att_141    62.0 -5.322581e-07  1.000000 -2.54287  2.31592
att_142    62.0 -6.290323e-07  1.000000 -2.20668  2.51133
att_143    62.0 -4.838710e-08  1.000000 -2.17303  2.42809
att_144    62.0 -2.258065e-07  1.000001 -2.59807  1.76612
att_145    62.0 -1.612903e-07  1.000000 -2.96588  1.81060
att_146    62.0  4.516129e-07  1.000000 -2.25417  1.85809
att_147    62.0 -1.129032e-07  1.000000 -2.16965  1.69162
att_148    62.0  3.225806e-08  1.000000 -2.70711  1.70694
att_149    62.0 -4.838710e-08  1.000000 -2.54648  1.79682
att_150    62.0  3.225806e-08  1.000000 -2.46872  2.31045
att_151    62.0  2.419355e-07  1.000000 -3.03290  2.06507
att_152    62.0  1.774194e-07  1.000000 -1.95910  2.09373
att_153    62.0 -2.741935e-07  1.000000 -2.30254  2.04631
att_154    62.0  1.129032e-07  0.999999 -2.49200  1.85913
att_155    62.0 -4.476706e-18  0.999999 -2.23300  2.04321
att_156    62.0 -2.741935e-07  1.000000 -2.50685  2.70946
att_157    62.0 -3.225806e-08  1.000000 -2.45303  1.88339
att_158    62.0  8.064516e-08  1.000000 -2.00621  2.92747
att_159    62.0 -1.612903e-07  1.000001 -2.38847  2.77494
att_160    62.0  4.838710e-08  1.000001 -2.40080  2.25800
att_161    62.0 -1.451613e-07  1.000000 -2.19544  2.01154
att_162    62.0  3.225806e-07  1.000000 -2.75473  1.83670
att_163    62.0  4.838710e-08  1.000000 -2.19899  2.05588
att_164    62.0  8.064516e-08  1.000000 -2.57104  1.54450
att_165    62.0  3.225806e-08  1.000000 -3.46706  2.06016
att_166    62.0  1.935484e-07  1.000000 -3.31050  2.51780
att_167    62.0  4.838710e-08  1.000000 -2.96324  2.08657
att_168    62.0 -3.225806e-08  1.000000 -2.76032  1.96090
att_169    62.0  1.612903e-07  1.000000 -2.73633  1.73109
att_170    62.0 -6.451613e-08  1.000000 -2.32868  2.21483
att_171    62.0 -1.612903e-07  1.000000 -2.97227  2.79960
att_172    62.0  8.064516e-08  1.000001 -4.07519  1.95345
att_173    62.0  2.741935e-07  1.000001 -2.19799  2.00795
att_174    62.0  1.612903e-08  0.999999 -2.21995  1.77865
att_175    62.0  8.064516e-08  1.000000 -2.97332  1.26797
att_176    62.0 -1.451613e-07  1.000001 -2.03526  2.76887
att_177    62.0 -4.838710e-08  1.000000 -1.32456  3.88045
att_178    62.0 -1.129032e-07  1.000000 -3.74649  2.06999
att_179    62.0  1.612903e-08  1.000000 -3.16167  1.81633
att_180    62.0  1.129032e-07  1.000000 -3.15125  1.90496
att_181    62.0 -2.741935e-07  1.000000 -2.30909  1.90387
att_182    62.0 -2.014518e-17  1.000000 -2.43599  1.72765
att_183    62.0  1.935484e-07  1.000000 -2.42352  2.23652
att_184    62.0 -9.677419e-08  1.000000 -2.37455  1.73842
att_185    62.0 -2.419355e-07  1.000000 -3.44596  1.92942
att_186    62.0 -2.258065e-07  1.000000 -2.50550  1.53361
att_187    62.0 -7.162729e-18  1.000000 -1.99449  2.71405
att_188    62.0 -4.838710e-08  1.000000 -2.81951  2.17273
att_189    62.0 -1.612903e-08  1.000000 -2.81794  1.87703
att_190    62.0  1.290323e-07  1.000000 -2.59585  1.69733
att_191    62.0 -1.612903e-07  1.000000 -2.63555  1.77770
att_192    62.0 -2.258065e-07  1.000000 -3.31929  1.92964
att_193    62.0  3.548387e-07  1.000000 -1.92859  2.37896
att_194    62.0 -2.741935e-07  1.000000 -3.01049  1.79751
att_195    62.0  6.451613e-08  1.000000 -2.11865  1.78652
att_196    62.0  1.129032e-07  1.000000 -2.00188  2.53024
att_197    62.0  6.451613e-08  1.000000 -2.78633  1.96723
att_198    62.0  1.612903e-08  1.000000 -1.69363  2.03617
att_199    62.0  1.451613e-07  0.999999 -2.27819  1.82403
att_200    62.0 -4.354839e-07  1.000000 -2.47281  1.87198
att_201    62.0 -1.451613e-07  1.000000 -2.86876  1.85420
att_202    62.0 -3.225806e-07  1.000000 -2.76089  1.75654
att_203    62.0 -1.612903e-08  1.000000 -1.97875  1.92797
att_204    62.0 -2.580645e-07  1.000000 -1.98748  2.04877
att_205    62.0  1.612903e-07  1.000000 -2.06412  2.48135
att_206    62.0  1.129032e-07  1.000000 -2.41667  2.41071
att_207    62.0  1.290323e-07  1.000000 -2.65704  2.15569
att_208    62.0 -2.741935e-07  0.999999 -3.15106  1.74374
att_209    62.0  9.677419e-08  1.000000 -2.13548  1.89734
att_210    62.0  2.096774e-07  1.000000 -2.09357  2.29045
att_211    62.0  2.903226e-07  1.000000 -2.18004  1.93318
att_212    62.0  1.774194e-07  1.000000 -1.83521  2.99001
att_213    62.0  1.290323e-07  1.000000 -3.59737  1.96781
att_214    62.0  1.935484e-07  1.000000 -2.96258  1.87284
att_215    62.0  2.580645e-07  1.000001 -2.50880  3.28938
att_216    62.0  1.451613e-07  1.000000 -2.30991  2.32043
att_217    62.0  2.258065e-07  1.000000 -2.55106  1.85563
att_218    62.0 -3.870968e-07  1.000000 -2.72447  1.81670
att_219    62.0  1.612903e-08  1.000000 -3.42820  1.72851
att_220    62.0  1.129032e-07  1.000000 -3.29077  2.52178
att_221    62.0 -1.290323e-07  1.000000 -2.40274  2.86986
att_222    62.0 -1.129032e-07  1.000000 -2.05302  1.95061
att_223    62.0  2.903226e-07  1.000000 -2.43981  1.32178
att_224    62.0  4.838710e-08  1.000000 -2.12619  1.62966
att_225    62.0 -6.451613e-08  1.000000 -2.65494  2.05222
att_226    62.0 -2.741935e-07  1.000000 -2.08037  2.04100
att_227    62.0 -3.225806e-08  1.000000 -1.91327  1.61200
att_228    62.0  2.903226e-07  1.000000 -2.02562  2.18259
att_229    62.0 -2.741935e-07  1.000000 -3.10852  1.88365
att_230    62.0 -1.290323e-07  1.000001 -2.54396  1.85661
att_231    62.0  1.612903e-07  1.000000 -2.02279  1.99816
att_232    62.0 -2.419355e-07  1.000000 -2.80976  2.11634
att_233    62.0  3.225806e-08  1.000000 -3.11565  1.76533
att_234    62.0  8.064516e-08  1.000000 -2.51982  2.60846
att_235    62.0 -1.935484e-07  1.000000 -2.68241  1.98396
att_236    62.0 -3.225806e-08  0.999999 -2.35542  1.79727
att_237    62.0 -1.451613e-07  1.000000 -3.90747  1.84678
att_238    62.0 -2.580645e-07  1.000000 -2.41255  2.28303
att_239    62.0 -7.162729e-18  0.999999 -2.43909  2.61271
att_240    62.0  1.612903e-07  1.000000 -2.12054  2.43756
att_241    62.0  3.548387e-07  1.000000 -2.17430  1.85119
att_242    62.0 -1.163943e-17  1.000000 -2.21098  2.06905
att_243    62.0  1.612903e-07  1.000000 -1.82027  2.35378
att_244    62.0 -1.774194e-07  1.000000 -2.41254  1.84449
att_245    62.0 -2.903226e-07  1.000000 -1.92121  1.96491
att_246    62.0  1.129032e-07  1.000000 -3.01476  2.48386
att_247    62.0  6.451613e-08  1.000000 -3.07587  2.02933
att_248    62.0  1.612903e-07  1.000000 -2.12737  2.51093
att_249    62.0  8.064516e-07  1.000000 -1.72487  1.91310
att_250    62.0  1.290323e-07  0.999999 -2.53084  2.46731
att_251    62.0 -8.064516e-08  1.000000 -2.54448  2.16142
att_252    62.0 -2.903226e-07  1.000000 -2.48915  2.32409
att_253    62.0  3.064516e-07  1.000000 -2.36886  2.20064
att_254    62.0  9.677419e-08  1.000000 -2.77490  1.95714
att_255    62.0 -4.838710e-08  1.000000 -2.51538  2.20490
att_256    62.0  2.741935e-07  1.000000 -1.95116  2.38490
att_257    62.0 -1.612903e-07  1.000000 -1.82236  2.67952
att_258    62.0  2.580645e-07  1.000000 -2.41422  1.98967
att_259    62.0 -1.612903e-08  1.000000 -3.00148  1.83900
att_260    62.0  8.064516e-08  0.999999 -1.72564  4.05876
att_264    62.0 -1.129032e-07  1.000000 -1.99270  2.25751
att_265    62.0  2.903226e-07  1.000001 -2.17430  1.92057
att_266    62.0  1.774194e-07  1.000000 -2.53171  1.90766
att_267    62.0 -3.548387e-07  1.000000 -2.04057  1.96086
att_268    62.0  1.451613e-07  0.999999 -1.73890  2.55651
att_269    62.0 -1.774194e-07  1.000000 -2.61123  1.59755
att_270    62.0  1.612903e-07  1.000000 -2.75215  1.78030
att_271    62.0 -9.677419e-08  1.000000 -2.16159  1.81877
att_272    62.0  6.451613e-08  1.000000 -2.00130  2.01472
att_273    62.0 -5.322581e-07  1.000000 -2.00676  1.94838
att_274    62.0  1.774194e-07  1.000000 -2.35578  2.90086
att_275    62.0  1.935484e-07  1.000000 -2.19315  2.61603
att_276    62.0 -1.290323e-07  1.000000 -2.05483  2.03074
att_277    62.0  2.419355e-07  1.000000 -2.60968  1.86045
att_278    62.0  4.838710e-08  1.000001 -2.31996  1.93714
att_279    62.0  4.838710e-08  1.000000 -2.48017  2.84925
att_280    62.0  3.709677e-07  1.000000 -2.41547  2.23809
att_281    62.0  3.387097e-07  1.000000 -2.26401  2.93216
att_282    62.0  1.129032e-07  1.000000 -2.10178  1.68265
att_283    62.0 -3.225806e-08  1.000000 -2.90605  2.18297
att_284    62.0  5.645161e-07  1.000000 -2.74779  1.92826
att_285    62.0  1.129032e-07  1.000000 -1.84214  3.44665
att_286    62.0 -1.612903e-08  1.000000 -2.34665  1.65058
att_287    62.0  2.903226e-07  1.000000 -2.53328  2.65166
att_288    62.0 -1.612903e-08  1.000000 -2.21417  2.31550
att_289    62.0 -1.451613e-07  1.000000 -2.51357  1.99878
att_290    62.0  9.677419e-08  1.000000 -3.39321  1.75599
att_291    62.0  1.935484e-07  1.000000 -2.90933  2.10936
att_292    62.0  6.451613e-08  1.000000 -2.38742  2.14385
att_293    62.0  2.903226e-07  1.000000 -2.55981  1.84122
att_294    62.0 -1.774194e-07  1.000000 -3.19731  1.67219
att_295    62.0  2.580645e-07  1.000000 -2.69188  2.06788
att_296    62.0 -1.612903e-08  1.000000 -2.77300  1.85791
att_297    62.0  9.677419e-08  0.999999 -2.09054  3.16168
att_298    62.0 -1.129032e-07  1.000000 -1.65428  2.17991
att_299    62.0 -8.064516e-08  1.000000 -2.10937  2.48198
att_300    62.0 -8.058070e-18  1.000000 -2.69268  2.02024
att_301    62.0 -8.064516e-08  1.000000 -2.75702  1.85124
att_302    62.0  1.935484e-07  0.999999 -2.68039  1.81639
att_303    62.0 -1.290323e-07  1.000000 -2.69622  1.88725
att_304    62.0  4.354839e-07  1.000000 -2.94968  2.17433
att_305    62.0  6.451613e-08  1.000000 -2.49427  2.77454
att_306    62.0 -2.258065e-07  1.000000 -2.06561  2.33132
att_307    62.0  2.741935e-07  1.000000 -2.43291  2.01596
att_308    62.0 -2.258065e-07  1.000000 -2.36459  1.79981
att_309    62.0 -1.612903e-07  1.000000 -2.50873  2.46339
att_310    62.0 -1.290323e-07  1.000000 -3.39380  1.81007
att_311    62.0 -1.129032e-07  1.000000 -2.57851  2.13182
att_312    62.0  1.451613e-07  1.000000 -2.18797  1.88850
att_313    62.0  4.838710e-08  0.999999 -2.12064  2.16129
att_314    62.0 -3.225806e-08  1.000000 -3.39129  1.97383
att_315    62.0  8.064516e-08  1.000000 -2.36228  2.78496
att_316    62.0  4.516129e-07  1.000000 -4.11045  1.86896
att_317    62.0 -1.774194e-07  1.000000 -1.84241  1.84752
att_318    62.0 -4.838710e-08  1.000001 -3.65116  1.80135
att_319    62.0 -4.838710e-08  1.000001 -2.69303  2.48288
att_320    62.0  2.096774e-07  1.000000 -2.58449  2.23790
att_321    62.0 -4.838710e-08  0.999999 -2.69494  1.60233
att_322    62.0 -2.096774e-07  1.000000 -2.46044  2.60738
att_323    62.0 -1.612903e-08  1.000000 -2.41418  2.02783
att_324    62.0 -3.225806e-07  1.000000 -2.06433  2.00548
att_325    62.0  9.677419e-08  1.000000 -2.11876  3.93390
att_326    62.0 -1.612903e-08  1.000000 -2.09909  1.89374
att_327    62.0 -1.774194e-07  1.000000 -2.85340  1.91202
att_328    62.0 -1.935484e-07  1.000000 -2.52236  1.96167
att_329    62.0 -1.451613e-07  1.000000 -3.02817  1.76273
att_330    62.0 -8.064516e-08  1.000000 -3.03218  2.53534
att_331    62.0 -1.612903e-08  1.000000 -3.30133  2.04008
att_332    62.0  9.677419e-08  1.000000 -3.08757  2.25727
att_333    62.0  1.129032e-07  1.000000 -3.07392  1.74487
att_334    62.0 -3.870968e-07  0.999999 -2.38216  1.98351
att_335    62.0  9.677419e-08  1.000000 -2.11268  1.74135
att_336    62.0 -1.129032e-07  0.999999 -2.76508  1.62253
att_337    62.0  8.064516e-08  1.000000 -2.56451  1.85420
att_338    62.0 -2.580645e-07  1.000000 -2.35445  1.79468
att_339    62.0 -9.677419e-08  1.000000 -2.89702  1.85274
att_340    62.0  1.290323e-07  1.000000 -3.23241  1.77435
att_341    62.0  3.548387e-07  1.000000 -3.09467  2.54333
att_342    62.0  2.258065e-07  1.000000 -2.08061  2.74692
att_343    62.0 -1.290323e-07  0.999999 -2.52415  2.10436
att_344    62.0  6.451613e-08  1.000000 -2.46405  1.86352
att_345    62.0 -1.612903e-08  1.000000 -2.08330  2.20630
att_346    62.0 -1.129032e-07  1.000000 -2.07662  1.98094
att_347    62.0  1.290323e-07  1.000001 -2.90931  1.61073
att_348    62.0 -1.612903e-08  1.000000 -2.31110  1.92600
att_349    62.0 -4.838710e-08  1.000000 -3.69082  1.89309
att_350    62.0 -6.451613e-08  1.000000 -2.29695  1.93459
att_351    62.0  1.774194e-07  1.000000 -2.52564  2.17942
att_352    62.0  1.290323e-07  1.000000 -2.87987  1.81453

In [7]:
# Categorical Feature Statistics
cat_stats

              value  count    pct
column   rank
HasTumor 1      Yes     40  64.52
         2       No     22  35.48

In [8]:
# Target Distribution
target_df

          count    pct
HasTumor
Yes          40  64.52
No           22  35.48

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=20, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to colon_tumor/019d9cd6-7112-7d0e-a09d-f0e137b371cf
019d9cd6-7112-7d0e-a09d-f0e137b371cf
8115e47a3b674163b4219806397cba1b708cb26217ba509d4a659bb14a5ad0cc