### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="santander_customer_transaction_prediction",
    dataset_year="2019",
    domain_str="finance",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/c/santander-customer-transaction-prediction",
    download_description="""
We use the train.csv from the Kaggle competition.

kaggle competitions download -c santander-customer-transaction-prediction -f train.csv && unzip train.csv.zip &&  rm train.csv.zip
mkdir -p local-data-warehouse/santander_customer_transaction_prediction && mv train.csv local-data-warehouse/santander_customer_transaction_prediction/
""",
    # References
    academic_reference_bibtex=r"""@misc{Piedra2019SantanderCustomerTransactionPrediction,
  author = {Mercedes Piedra and Sohier Dane and Soraya Jimenez},
  title  = {Santander Customer Transaction Prediction},
  year   = {2019},
  howpublished = {\url{https://kaggle.com/competitions/santander-customer-transaction-prediction}},
  note   = {Kaggle competition}
}
""",
    academic_reference_bibtex_key="Piedra2019SantanderCustomerTransactionPrediction",
    license="Kaggle Competition Rules",
    data_tags=["IID", "Anonymized"],
    curation_comments="""
We start with the train.csv from Kaggle.

- The data has been anonymized, so feature meanings are unknown.
- The data seems to be generated or created for the competition. Most features are perfectly normally distributed.
- Kaggle experts found various uniqueness-based features and had to filter fake samples from the test data. We apply the uniqueness-based features.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="target",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="target",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(dataset_mold.path / "train.csv")
print("Loaded data shape:", df.shape)

# Follow #1 solution https://www.kaggle.com/code/fl2ooo/create-data
# - We do not create the feature that is used for / requires test-time adaption for the fake test samples (that do not exist in the train data).
orig = [f'var_{i}' for i in range(200)]
has_one = [f'var_{i}_has_one' for i in range(200)]
has_zero = [f'var_{i}_has_zero' for i in range(200)]
target = task_mold.target_column_name

for f in orig:
    df[f + '_has_one'] = 0
    df[f + '_has_zero'] = 0
    f_1 = df.loc[df[target] == 1, f].value_counts()

    f_1_1 = set(f_1.index[f_1 > 1])
    f_0_1 = set(f_1.index[f_1 > 0])

    f_0 = df.loc[df[target] == 0, f].value_counts()
    f_0_0 = set(f_0.index[f_0 > 1])
    f_1_0 = set(f_0.index[f_0 > 0])

    df.loc[df[target] == 1, f + '_has_one'] = df.loc[df[target] == 1, f].isin(f_1_1).astype(int)
    df.loc[df[target] == 0, f + '_has_one'] = df.loc[df[target] == 0, f].isin(f_0_1).astype(int)
    df.loc[df[target] == 1, f + '_has_zero'] = df.loc[df[target] == 1, f].isin(f_1_0).astype(int)
    df.loc[df[target] == 0, f + '_has_zero'] = df.loc[df[target] == 0, f].isin(f_0_0).astype(int)
    df = df.copy()

df.loc[:, has_one] = 2*df.loc[:, has_one].values + df.loc[:, has_zero].values

df = df.drop(columns=["ID_code"])

cat_cols = [task_mold.target_column_name] + has_one + has_zero
for col in cat_cols:
    df[col] = df[col].astype("category")

df = df.reset_index(drop=True)

Loaded data shape: (200000, 202)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 200,000
Columns: 601
Use sampling: False (sample size: 200,000)

Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['var_45', 'var_117', 'var_74', 'var_61', 'var_97', 'var_120', 'var_90', 'var_187', 'var_136', 'var_160']
Rows remaining as candidates after top-10 filter: 0 (of 200,000)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...

Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,var_10,var_11,var_12,var_13,var_14,var_15,var_16,var_17,var_18,var_19,var_20,var_21,var_22,var_23,var_24,var_25,var_26,var_27,var_28,var_29,var_30,var_31,var_32,var_33,var_34,var_35,var_36,var_37,var_38,var_39,var_40,var_41,var_42,var_43,var_44,var_45,var_46,var_47,var_48,var_49,var_50,var_51,var_52,var_53,var_54,var_55,var_56,var_57,var_58,var_59,var_60,var_61,var_62,var_63,var_64,var_65,var_66,var_67,var_68,var_69,var_70,var_71,var_72,var_73,var_74,var_75,var_76,var_77,var_78,var_79,var_80,var_81,var_82,var_83,var_84,var_85,var_86,var_87,var_88,var_89,var_90,var_91,var_92,var_93,var_94,var_95,var_96,var_97,var_98,var_99,var_100,var_101,var_102,var_103,var_104,var_105,var_106,var_107,var_108,var_109,var_110,var_111,var_112,var_113,var_114,var_115,var_116,var_117,var_118,var_119,var_120,var_121,var_122,var_123,var_124,var_125,var_126,var_127,var_128,var_129,var_130,var_131,var_132,var_133,var_134,var_135,var_136,var_137,var_138,var_139,var_140,var_141,var_142,var_143,var_144,var_145,var_146,var_147,var_148,var_149,var_150,var_151,var_152,var_153,var_154,var_155,var_156,var_157,var_158,var_159,var_160,var_161,var_162,var_163,var_164,var_165,var_166,var_167,var_168,var_169,var_170,var_171,var_172,var_173,var_174,var_175,var_176,var_177,var_178,var_179,var_180,var_181,var_182,var_183,var_184,var_185,var_186,var_187,var_188,var_189,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199,var_0_has_one,var_0_has_zero,var_1_has_one,var_1_has_zero,var_2_has_one,var_2_has_zero,var_3_has_one,var_3_has_zero,var_4_has_one,var_4_has_zero,var_5_has_one,var_5_has_zero,var_6_has_one,var_6_has_zero,var_7_has_one,var_7_has_zero,var_8_has_one,var_8_has_zero,var_9_has_one,var_9_has_zero,var_10_has_one,var_10_has_zero,var_11_has_one,var_11_has_zero,var_12_has_one,var_12_has_zero,var_13_has_one,var_13_has_zero,var_14_has_one,var_14_has_zero,var_15_has_one,var_15_has_zero,var_16_has_one,var_16_has_zero,var_17_has_one,var_17_has_zero,var_18_has_one,var_18_has_zero,var_19_has_one,var_19_has_zero,var_20_has_one,var_20_has_zero,var_21_has_one,var_21_has_zero,var_22_has_one,var_22_has_zero,var_23_has_one,var_23_has_zero,var_24_has_one,var_24_has_zero,var_25_has_one,var_25_has_zero,var_26_has_one,var_26_has_zero,var_27_has_one,var_27_has_zero,var_28_has_one,var_28_has_zero,var_29_has_one,var_29_has_zero,var_30_has_one,var_30_has_zero,var_31_has_one,var_31_has_zero,var_32_has_one,var_32_has_zero,var_33_has_one,var_33_has_zero,var_34_has_one,var_34_has_zero,var_35_has_one,var_35_has_zero,var_36_has_one,var_36_has_zero,var_37_has_one,var_37_has_zero,var_38_has_one,var_38_has_zero,var_39_has_one,var_39_has_zero,var_40_has_one,var_40_has_zero,var_41_has_one,var_41_has_zero,var_42_has_one,var_42_has_zero,var_43_has_one,var_43_has_zero,var_44_has_one,var_44_has_zero,var_45_has_one,var_45_has_zero,var_46_has_one,var_46_has_zero,var_47_has_one,var_47_has_zero,var_48_has_one,var_48_has_zero,var_49_has_one,var_49_has_zero,var_50_has_one,var_50_has_zero,var_51_has_one,var_51_has_zero,var_52_has_one,var_52_has_zero,var_53_has_one,var_53_has_zero,var_54_has_one,var_54_has_zero,var_55_has_one,var_55_has_zero,var_56_has_one,var_56_has_zero,var_57_has_one,var_57_has_zero,var_58_has_one,var_58_has_zero,var_59_has_one,var_59_has_zero,var_60_has_one,var_60_has_zero,var_61_has_one,var_61_has_zero,var_62_has_one,var_62_has_zero,var_63_has_one,var_63_has_zero,var_64_has_one,var_64_has_zero,var_65_has_one,var_65_has_zero,var_66_has_one,var_66_has_zero,var_67_has_one,var_67_has_zero,var_68_has_one,var_68_has_zero,var_69_has_one,var_69_has_zero,var_70_has_one,var_70_has_zero,var_71_has_one,var_71_has_zero,var_72_has_one,var_72_has_zero,var_73_has_one,var_73_has_zero,var_74_has_one,var_74_has_zero,var_75_has_one,var_75_has_zero,var_76_has_one,var_76_has_zero,var_77_has_one,var_77_has_zero,var_78_has_one,var_78_has_zero,var_79_has_one,var_79_has_zero,var_80_has_one,var_80_has_zero,var_81_has_one,var_81_has_zero,var_82_has_one,var_82_has_zero,var_83_has_one,var_83_has_zero,var_84_has_one,var_84_has_zero,var_85_has_one,var_85_has_zero,var_86_has_one,var_86_has_zero,var_87_has_one,var_87_has_zero,var_88_has_one,var_88_has_zero,var_89_has_one,var_89_has_zero,var_90_has_one,var_90_has_zero,var_91_has_one,var_91_has_zero,var_92_has_one,var_92_has_zero,var_93_has_one,var_93_has_zero,var_94_has_one,var_94_has_zero,var_95_has_one,var_95_has_zero,var_96_has_one,var_96_has_zero,var_97_has_one,var_97_has_zero,var_98_has_one,var_98_has_zero,var_99_has_one,var_99_has_zero,var_100_has_one,var_100_has_zero,var_101_has_one,var_101_has_zero,var_102_has_one,var_102_has_zero,var_103_has_one,var_103_has_zero,var_104_has_one,var_104_has_zero,var_105_has_one,var_105_has_zero,var_106_has_one,var_106_has_zero,var_107_has_one,var_107_has_zero,var_108_has_one,var_108_has_zero,var_109_has_one,var_109_has_zero,var_110_has_one,var_110_has_zero,var_111_has_one,var_111_has_zero,var_112_has_one,var_112_has_zero,var_113_has_one,var_113_has_zero,var_114_has_one,var_114_has_zero,var_115_has_one,var_115_has_zero,var_116_has_one,var_116_has_zero,var_117_has_one,var_117_has_zero,var_118_has_one,var_118_has_zero,var_119_has_one,var_119_has_zero,var_120_has_one,var_120_has_zero,var_121_has_one,var_121_has_zero,var_122_has_one,var_122_has_zero,var_123_has_one,var_123_has_zero,var_124_has_one,var_124_has_zero,var_125_has_one,var_125_has_zero,var_126_has_one,var_126_has_zero,var_127_has_one,var_127_has_zero,var_128_has_one,var_128_has_zero,var_129_has_one,var_129_has_zero,var_130_has_one,var_130_has_zero,var_131_has_one,var_131_has_zero,var_132_has_one,var_132_has_zero,var_133_has_one,var_133_has_zero,var_134_has_one,var_134_has_zero,var_135_has_one,var_135_has_zero,var_136_has_one,var_136_has_zero,var_137_has_one,var_137_has_zero,var_138_has_one,var_138_has_zero,var_139_has_one,var_139_has_zero,var_140_has_one,var_140_has_zero,var_141_has_one,var_141_has_zero,var_142_has_one,var_142_has_zero,var_143_has_one,var_143_has_zero,var_144_has_one,var_144_has_zero,var_145_has_one,var_145_has_zero,var_146_has_one,var_146_has_zero,var_147_has_one,var_147_has_zero,var_148_has_one,var_148_has_zero,var_149_has_one,var_149_has_zero,var_150_has_one,var_150_has_zero,var_151_has_one,var_151_has_zero,var_152_has_one,var_152_has_zero,var_153_has_one,var_153_has_zero,var_154_has_one,var_154_has_zero,var_155_has_one,var_155_has_zero,var_156_has_one,var_156_has_zero,var_157_has_one,var_157_has_zero,var_158_has_one,var_158_has_zero,var_159_has_one,var_159_has_zero,var_160_has_one,var_160_has_zero,var_161_has_one,var_161_has_zero,var_162_has_one,var_162_has_zero,var_163_has_one,var_163_has_zero,var_164_has_one,var_164_has_zero,var_165_has_one,var_165_has_zero,var_166_has_one,var_166_has_zero,var_167_has_one,var_167_has_zero,var_168_has_one,var_168_has_zero,var_169_has_one,var_169_has_zero,var_170_has_one,var_170_has_zero,var_171_has_one,var_171_has_zero,var_172_has_one,var_172_has_zero,var_173_has_one,var_173_has_zero,var_174_has_one,var_174_has_zero,var_175_has_one,var_175_has_zero,var_176_has_one,var_176_has_zero,var_177_has_one,var_177_has_zero,var_178_has_one,var_178_has_zero,var_179_has_one,var_179_has_zero,var_180_has_one,var_180_has_zero,var_181_has_one,var_181_has_zero,var_182_has_one,var_182_has_zero,var_183_has_one,var_183_has_zero,var_184_has_one,var_184_has_zero,var_185_has_one,var_185_has_zero,var_186_has_one,var_186_has_zero,var_187_has_one,var_187_has_zero,var_188_has_one,var_188_has_zero,var_189_has_one,var_189_has_zero,var_190_has_one,var_190_has_zero,var_191_has_one,var_191_has_zero,var_192_has_one,var_192_has_zero,var_193_has_one,var_193_has_zero,var_194_has_one,var_194_has_zero,var_195_has_one,var_195_has_zero,var_196_has_one,var_196_has_zero,var_197_has_one,var_197_has_zero,var_198_has_one,var_198_has_zero,var_199_has_one,var_199_has_zero
0,0,8.9255,-6.7863,11.9081,5.0930,11.4607,-9.2834,5.1187,18.6266,-4.9200,5.7470,2.9252,3.1821,14.0137,0.5745,8.7989,14.5691,5.7487,-7.2393,4.2840,30.7133,10.5350,16.2191,2.5791,2.4716,14.3831,13.4325,-5.1488,-0.4073,4.9306,5.9965,-0.3085,12.9041,-3.8766,16.8911,11.1920,10.5785,0.6764,7.8871,4.6667,3.8743,-5.2387,7.3746,11.5767,12.0446,11.6418,-7.0170,5.9226,-14.2136,16.0283,5.3253,12.9194,29.0460,-0.6940,5.1736,-0.7474,14.8322,11.2668,5.3822,2.0183,10.1166,16.1828,4.9590,2.0771,-0.2154,8.6748,9.5319,5.8056,22.4321,5.0109,-4.7010,21.6374,0.5663,5.1999,8.8600,43.1127,18.3816,-2.3440,23.4104,6.5199,12.1983,13.6468,13.8372,1.3675,2.9423,-4.5213,21.4669,9.3225,16.4597,7.9984,-1.7069,-21.4494,6.7806,11.0924,9.9913,14.8421,0.1812,8.9642,16.2572,2.1743,-3.4132,9.4763,13.3102,26.5376,1.4403,14.7100,6.0454,9.5426,17.1554,14.1104,24.3627,2.0323,6.7602,3.9141,-0.4851,2.5240,1.5093,2.5516,15.5752,-13.4221,7.2739,16.0094,9.7268,0.8897,0.7754,4.2218,12.0039,13.8571,-0.7338,-1.9245,15.4462,12.8287,0.3587,9.6508,6.5674,5.1726,3.1345,29.4547,31.4045,2.8279,15.6599,8.3307,-5.6011,19.0614,11.2663,8.6989,8.3694,11.5659,-16.4727,4.0288,17.9244,18.5177,10.7800,9.0056,16.6964,10.4838,1.6573,12.1749,-13.1324,17.6054,11.5423,15.4576,5.3133,3.6159,5.0384,6.6760,12.6644,2.7004,-0.6975,9.5981,5.4879,-4.7645,-8.4254,20.8773,3.1531,18.5618,7.7423,-10.1245,13.7241,-3.5189,1.7202,-8.4051,9.0164,3.0657,14.3691,25.8398,5.8764,11.8411,-19.7159,17.5743,0.5857,4.4354,3.9642,3.1364,1.6910,18.5227,-2.3978,7.8784,8.5635,12.7803,-1.0914,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,3,1,0,0,1,1,3,1,0,0,1,1,0,0,0,0,1,1,1,1,1,1,1,1,0,0,3,1,1,1,3,1,3,1,1,1,0,0,3,1,1,1,1,1,3,1,2,0,1,1,3,1,0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,2,0,0,0,3,1,1,1,1,1,3,1,0,0,3,1,1,1,3,1,0,0,3,1,0,0,3,1,1,1,1,1,3,1,0,0,0,0,0,0,1,1,0,0,1,1,3,1,1,1,0,0,3,1,0,0,1,1,1,1,3,1,1,1,1,1,1,1,0,0,0,0,3,1,1,1,3,1,1,1,3,1,0,0,0,0,1,1,3,1,0,0,1,1,1,1,3,1,1,1,0,0,1,1,0,0,3,1,1,1,1,1,3,1,1,1,0,0,1,1,3,1,1,1,0,0,1,1,0,0,0,0,1,1,1,1,0,0,1,1,3,1,3,1,1,1,1,1,1,1,3,1,3,1,1,1,3,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,2,0,1,1,1,1,1,1,1,1,1,1,3,1,0,0,1,1,1,1,1,1,1,1,3,1,0,0,3,1,1,1,0,0,1,1,0,0,3,1,1,1,3,1,0,0,1,1,3,1,0,0,3,1,3,1,3,1,1,1,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,1,1,1,1,3,1,3,1,3,1,1,1,3,1,1,1,1,1,1,1,3,1,3,1,1,1
1,0,11.5006,-4.1473,13.8588,5.3890,12.3622,7.0433,5.6208,16.5338,3.1468,8.0851,-0.4032,8.0585,14.0239,8.4135,5.4345,13.7003,13.8275,-15.5849,7.8000,28.5708,3.4287,2.7407,8.5524,3.3716,6.9779,13.8910,-11.7684,-2.5586,5.0464,0.5481,-9.2987,7.8755,1.2859,19.3710,11.3702,0.7399,2.7995,5.8434,10.8160,3.6783,-11.1147,1.8730,9.8775,11.7842,1.2444,-47.3797,7.3718,0.1948,34.4014,25.7037,11.8343,13.2256,-4.1083,6.6885,-8.0946,18.5995,19.3219,7.0118,1.9210,8.8682,8.0109,-7.2417,1.7944,-1.3147,8.1042,1.5365,5.4007,7.9344,5.0220,2.2302,40.5632,0.5134,3.1701,20.1068,7.7841,7.0529,3.2709,23.4822,5.5075,13.7814,2.5462,18.1782,0.3683,-4.8210,-5.4850,13.7867,-13.5901,11.0993,7.9022,12.2301,0.4768,6.8852,8.0905,10.9631,11.7569,-1.2722,24.7876,26.6881,1.8944,0.6939,-13.6950,8.4068,35.4734,1.7093,15.1866,2.6227,7.3412,32.0888,13.9550,13.0858,6.6203,7.1051,5.3523,8.5426,3.6159,4.1569,3.0454,7.8522,-11.5100,7.5109,31.5899,9.5018,8.2736,10.1633,0.1225,12.5942,14.5697,2.4354,0.8194,16.5346,12.4205,-0.1780,5.7582,7.0513,1.9568,-8.9921,9.7797,18.1577,-1.9721,16.1622,3.6937,6.6803,-0.3243,12.2806,8.6086,11.0738,8.9231,11.7700,4.2578,-4.4223,20.6294,14.8743,9.4317,16.7242,-0.5687,0.1898,12.2419,-9.6953,22.3949,10.6261,29.4846,5.8683,3.8208,15.8348,-5.0121,15.1345,3.2003,9.3192,3.8821,5.7999,5.5378,5.0988,22.0330,5.5134,30.2645,10.4968,-7.2352,16.5721,-7.3477,11.0752,-5.5937,9.4878,-14.9100,9.4245,22.5441,-4.8622,7.6543,-15.9319,13.3175,-0.3566,7.6421,7.7214,2.5837,10.9516,15.4305,2.0339,8.1267,8.7889,18.3560,1.9518,1,1,1,1,1,1,3,1,3,1,0,0,1,1,3,1,1,1,3,1,1,1,0,0,3,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,3,1,0,0,1,1,3,1,0,0,1,1,3,1,3,1,2,0,3,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,3,1,3,1,1,1,0,0,0,0,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,0,0,1,1,3,1,1,1,1,1,1,1,0,0,3,1,1,1,1,1,1,1,1,1,1,1,3,1,0,0,0,0,3,1,1,1,0,0,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,1,1,3,1,1,1,0,0,1,1,3,1,0,0,0,0,3,1,0,0,3,1,3,1,1,1,0,0,0,0,3,1,1,1,0,0,3,1,1,1,3,1,0,0,1,1,1,1,3,1,3,1,0,0,2,0,1,1,1,1,0,0,3,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,3,1,3,1,2,0,1,1,0,0,3,1,1,1,1,1,3,1,1,1,1,1,0,0,3,1,1,1,0,0,1,1,1,1,0,0,3,1,1,1,1,1,1,1,2,0,3,1,0,0,0,0,0,0,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,3,1,3,1,0,0,0,0,1,1,3,1,0,0,1,1,3,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,1,1,1,1,0,0,1,1,0,0,1,1,1,1,0,0,1,1,1,1,1,1,3,1,3,1,0,0,0,0,1,1,1,1,3,1,1,1,0,0
2,0,8.6093,-2.7457,12.0805,7.8928,10.5825,-9.0837,6.9427,14.6155,-4.9193,5.9525,-0.3249,-11.2648,14.1929,7.3124,7.5244,14.6472,7.6782,-1.7395,4.7011,20.4775,17.7559,18.1377,1.2145,3.5137,5.6777,13.2177,-7.9940,-2.9029,5.8463,6.1439,-11.1025,12.4858,-2.2871,19.0422,11.0449,4.1087,4.6974,6.9346,10.8917,0.9003,-13.5174,2.2439,11.5283,12.0406,4.1006,-7.9078,11.1405,-5.7864,20.7477,6.8874,12.9143,19.5856,0.7268,6.4059,9.3124,6.2846,15.6372,5.8200,1.1000,9.1854,12.5963,-10.3734,0.8748,5.8042,3.7163,-1.1016,7.3667,9.8565,5.0228,-5.7828,2.3612,0.8520,6.3577,12.1719,19.7312,19.4465,4.5048,23.2378,6.3191,12.8046,7.4729,15.7811,13.3529,10.1852,5.4604,19.0773,-4.4577,9.5413,11.9052,2.1447,-22.4038,7.0883,14.1613,10.5080,14.2621,0.2647,20.4031,17.0360,1.6981,-0.0269,-0.3939,12.6317,14.8863,1.3854,15.0284,3.9995,5.3683,8.6273,14.1963,20.3882,3.2304,5.7033,4.5255,2.1929,3.1290,2.9044,1.1696,28.7632,-17.2738,2.1056,21.1613,8.9573,2.7768,-2.1746,3.6932,12.4653,14.1978,-2.5511,-0.9479,17.1092,11.5419,0.0975,8.8186,6.6231,3.9358,-11.7218,24.5437,15.5827,3.8212,8.6674,7.3834,-2.4438,10.2158,7.4844,9.1104,4.3649,11.4934,1.7624,4.0714,-1.2681,14.3330,8.0088,4.4015,14.1479,-5.1747,0.5778,14.5362,-1.7624,33.8820,11.6041,13.2070,5.8442,4.7086,5.7141,-1.0410,20.5092,3.2790,-5.5952,7.3176,5.7690,-7.0927,-3.9116,7.2569,-5.8234,25.6820,10.9202,-0.3104,8.8438,-9.7009,2.4013,-4.2935,9.3908,-13.2648,3.1545,23.0866,-5.3000,5.3745,-6.2660,10.1934,-0.8417,2.9057,9.7905,1.6704,1.6858,21.6042,3.1417,-6.5213,8.2675,14.7222,0.3965,1,1,0,0,1,1,1,1,3,1,1,1,1,1,3,1,0,0,3,1,0,0,0,0,3,1,1,1,1,1,3,1,3,1,0,0,2,0,1,1,1,1,0,0,2,0,1,1,0,0,3,1,2,0,3,1,1,1,0,0,1,1,1,1,1,1,1,1,3,1,3,1,1,1,1,1,1,1,3,1,0,0,1,1,3,1,1,1,0,0,1,1,0,0,0,0,1,1,1,1,3,1,1,1,1,1,3,1,0,0,0,0,2,0,3,1,1,1,1,1,1,1,0,0,3,1,3,1,3,1,1,1,3,1,0,0,3,1,3,1,0,0,3,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,3,1,1,1,1,1,1,1,1,1,2,0,0,0,3,1,3,1,1,1,2,0,1,1,3,1,1,1,3,1,1,1,0,0,3,1,1,1,1,1,3,1,3,1,1,1,3,1,3,1,1,1,1,1,1,1,1,1,0,0,0,0,1,1,0,0,1,1,3,1,1,1,1,1,1,1,0,0,3,1,1,1,3,1,3,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,3,1,0,0,1,1,1,1,1,1,3,1,3,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,0,0,3,1,1,1,3,1,3,1,0,0,1,1,1,1,3,1,1,1,1,1,3,1,0,0,1,1,0,0,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,0,0,0,1,1,1,1,1,1,0,0,0,0,3,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1
3,0,11.0604,-2.1518,8.9522,7.1957,12.5846,-1.8361,5.8428,14.9250,-5.8609,8.2450,2.3061,2.8102,13.8463,11.9704,6.4569,14.8372,10.7430,-0.4299,15.9426,13.7257,20.3010,12.5579,6.8202,2.7229,12.1354,13.7367,0.8135,-0.9059,5.9070,2.8407,-15.2398,10.4407,-2.5731,6.1796,10.6093,-5.9158,8.1723,2.8521,9.1738,0.6665,-3.8294,-1.0370,11.7770,11.2834,8.0485,-24.6840,12.7404,-35.1659,0.7613,8.3838,12.6832,9.5503,1.7895,5.2091,8.0913,12.3972,14.4698,6.5850,3.3164,9.4638,15.7820,-25.0222,3.4418,-4.3923,8.6464,6.3072,5.6221,23.6143,5.0220,-3.9989,4.0462,0.2500,1.2516,24.4187,4.5290,15.4235,11.6875,23.6273,4.0806,15.2733,0.7839,10.5404,1.6212,-5.2896,1.6027,17.9762,-2.3174,15.6298,4.5474,7.5509,-7.5866,7.0364,14.4027,10.7795,7.2887,-1.0930,11.3596,18.1486,2.8344,1.9480,-19.8592,22.5316,18.6129,1.3512,9.3291,4.2835,10.3907,7.0874,14.3256,14.4135,4.2827,6.9750,1.6480,11.6896,2.5762,-2.5459,5.3446,38.1015,3.5732,5.0988,30.5644,11.3025,3.9618,-8.2464,2.7038,12.3441,12.5431,-1.3683,3.5974,13.9761,14.3003,1.0486,8.9500,7.1954,-1.1984,1.9586,27.5609,24.6065,-2.8233,8.9821,3.8873,15.9638,10.0142,7.8388,9.9718,2.9253,10.4994,4.1622,3.7613,2.3701,18.0984,17.1765,7.6508,18.2452,17.0336,-10.9370,12.0500,-1.2155,19.9750,12.3892,31.8833,5.9684,7.2084,3.8899,-11.0882,17.2502,2.5881,-2.7018,0.5641,5.3430,-7.1541,-6.1920,18.2366,11.7134,14.7483,8.1013,11.8771,13.9552,-10.4701,5.6961,-3.7546,8.4117,1.8986,7.2601,-0.4639,-0.0498,7.9336,-12.8279,12.4124,1.8489,4.4666,4.7433,0.7178,1.4214,23.0347,-1.2706,-2.9275,10.2922,17.9697,-8.9996,1,1,3,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,3,1,1,1,1,1,3,1,1,1,3,1,3,1,3,1,1,1,0,0,1,1,1,1,1,1,1,1,3,1,0,0,3,1,1,1,3,1,3,1,1,1,0,0,1,1,0,0,0,0,3,1,0,0,1,1,2,0,1,1,1,1,0,0,0,0,1,1,3,1,0,0,0,0,3,1,0,0,1,1,3,1,3,1,1,1,1,1,3,1,0,0,1,1,3,1,3,1,0,0,3,1,0,0,2,0,1,1,1,1,1,1,0,0,1,1,0,0,3,1,0,0,0,0,1,1,0,0,0,0,1,1,1,1,0,0,3,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,3,1,1,1,3,1,0,0,1,1,2,0,0,0,3,1,2,0,0,0,1,1,1,1,3,1,1,1,3,1,1,1,0,0,3,1,1,1,1,1,3,1,1,1,0,0,3,1,0,0,0,0,1,1,0,0,0,0,0,0,1,1,1,1,0,0,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,2,0,1,1,2,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,0,0,3,1,0,0,1,1,0,0,3,1,1,1,1,1,0,0,1,1,0,0,1,1,0,0,0,0,3,1,1,1,1,1,0,0,1,1,1,1,0,0,3,1,3,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,3,1,1,1,0,0,3,1,1,1,0,0,3,1,3,1,0,0,2,0,3,1,1,1,1,1,3,1,1,1,3,1,1,1,1,1
4,0,9.8369,-1.4834,12.8746,6.6375,12.2772,2.4486,5.9405,19.2514,6.2654,7.6784,-9.4458,-12.1419,13.8481,7.8895,7.7894,15.0553,8.4871,-3.0680,6.5263,11.3152,21.4246,18.9608,10.1102,2.7142,14.2080,13.5433,3.1736,-3.3423,5.9015,7.9352,-3.1582,9.4668,-0.0083,19.3239,12.4057,0.6329,2.7922,5.8184,19.3038,1.4450,-5.5963,14.0685,11.9171,11.5111,6.9087,-65.4863,13.8657,0.0444,-0.1346,14.4268,13.3273,10.4857,-1.4367,5.7555,-8.5414,14.1482,16.9840,6.1812,1.9548,9.2048,8.6591,-27.7439,-0.4952,-1.7839,5.2670,-4.3205,6.9860,1.6184,5.0301,-3.2431,40.1236,0.7737,-0.7264,4.5886,-4.5346,23.3521,1.0273,19.1600,7.1734,14.3937,2.9598,13.3317,-9.2587,-6.7075,7.8984,14.5265,7.0799,20.1670,8.0053,3.7954,-39.7997,7.0065,9.3627,10.4316,14.0553,0.0213,14.7246,35.2988,1.6844,0.6715,-22.9264,12.3562,17.3410,1.6940,7.1179,5.1934,8.8230,10.6617,14.0837,28.2749,-0.1937,5.9654,1.0719,7.9923,2.9138,-3.6135,1.4684,25.6795,13.8224,4.7478,41.1037,12.7140,5.2964,9.7289,3.9370,12.1316,12.5815,7.0642,5.6518,10.9346,11.4266,0.9442,7.7532,6.6173,-6.8304,6.4730,17.1728,25.8128,2.6791,13.9547,6.6289,-4.3965,11.7159,16.1080,7.6874,9.1570,11.5670,-12.7047,3.7574,9.9110,20.1461,1.2995,5.8493,19.8234,4.7022,10.6101,13.0021,-12.6068,27.0846,8.0913,33.5107,5.6953,5.4663,18.2201,6.5769,21.2607,3.2304,-1.7759,3.1283,5.5518,1.4493,-2.6627,19.8056,2.3705,18.4685,16.3309,-3.3456,13.5261,1.7189,5.1743,-7.6938,9.7685,4.8910,12.2198,11.8503,-7.8931,6.4209,5.9270,16.0201,-0.2829,-1.4905,9.5214,-0.1508,9.1942,13.2876,-1.5121,3.9267,9.5031,17.9974,-8.8104,1,1,1,1,1,1,1,1,3,1,0,0,1,1,0,0,0,0,3,1,0,0,0,0,3,1,0,0,1,1,3,1,3,1,1,1,0,0,1,1,1,1,1,1,1,1,3,1,2,0,3,1,0,0,1,1,1,1,0,0,0,0,3,1,3,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,3,1,3,1,1,1,0,0,1,1,0,0,1,1,0,0,1,1,1,1,1,1,3,1,0,0,0,0,3,1,3,1,3,1,3,1,1,1,2,0,1,1,1,1,0,0,1,1,3,1,0,0,3,1,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,0,0,0,0,1,1,1,1,1,1,1,1,1,1,0,0,3,1,1,1,3,1,2,0,1,1,0,0,0,0,3,1,1,1,0,0,1,1,1,1,3,1,0,0,3,1,1,1,1,1,3,1,0,0,1,1,3,1,3,1,0,0,1,1,0,0,3,1,0,0,0,0,0,0,0,0,3,1,1,1,0,0,3,1,3,1,3,1,3,1,0,0,1,1,1,1,3,1,1,1,3,1,1,1,1,1,0,0,1,1,1,1,0,0,0,0,0,0,1,1,0,0,3,1,0,0,1,1,0,0,3,1,0,0,1,1,0,0,1,1,1,1,2,0,0,0,3,1,0,0,0,0,0,0,1,1,3,1,1,1,0,0,0,0,0,0,3,1,0,0,3,1,3,1,0,0,1,1,0,0,3,1,1,1,1,1,3,1,0,0,1,1,1,1,1,1,3,1,0,0,0,0,1,1,0,0,1,1,0,0,1,1,3,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,3,1,1,1,1,1

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,target,category,0.0,0.0,2.0,"0, 1"
1,var_0_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
2,var_0_has_zero,category,0.0,0.0,2.0,"1, 0"
3,var_1_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
4,var_1_has_zero,category,0.0,0.0,2.0,"1, 0"
5,var_2_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
6,var_2_has_zero,category,0.0,0.0,2.0,"1, 0"
7,var_3_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
8,var_3_has_zero,category,0.0,0.0,2.0,"1, 0"
9,var_4_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
10,var_4_has_zero,category,0.0,0.0,2.0,"1, 0"
11,var_5_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
12,var_5_has_zero,category,0.0,0.0,2.0,"0, 1"
13,var_6_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
14,var_6_has_zero,category,0.0,0.0,2.0,"1, 0"
15,var_7_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
16,var_7_has_zero,category,0.0,0.0,2.0,"1, 0"
17,var_8_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
18,var_8_has_zero,category,0.0,0.0,2.0,"1, 0"
19,var_9_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
20,var_9_has_zero,category,0.0,0.0,2.0,"1, 0"
21,var_10_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
22,var_10_has_zero,category,0.0,0.0,2.0,"1, 0"
23,var_11_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
24,var_11_has_zero,category,0.0,0.0,2.0,"1, 0"
25,var_12_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
26,var_12_has_zero,category,0.0,0.0,2.0,"1, 0"
27,var_13_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
28,var_13_has_zero,category,0.0,0.0,2.0,"1, 0"
29,var_14_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
30,var_14_has_zero,category,0.0,0.0,2.0,"1, 0"
31,var_15_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
32,var_15_has_zero,category,0.0,0.0,2.0,"1, 0"
33,var_16_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
34,var_16_has_zero,category,0.0,0.0,2.0,"1, 0"
35,var_17_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
36,var_17_has_zero,category,0.0,0.0,2.0,"1, 0"
37,var_18_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
38,var_18_has_zero,category,0.0,0.0,2.0,"0, 1"
39,var_19_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
40,var_19_has_zero,category,0.0,0.0,2.0,"0, 1"
41,var_20_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
42,var_20_has_zero,category,0.0,0.0,2.0,"1, 0"
43,var_21_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
44,var_21_has_zero,category,0.0,0.0,2.0,"0, 1"
45,var_22_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
46,var_22_has_zero,category,0.0,0.0,2.0,"1, 0"
47,var_23_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
48,var_23_has_zero,category,0.0,0.0,2.0,"1, 0"
49,var_24_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
50,var_24_has_zero,category,0.0,0.0,2.0,"1, 0"
51,var_25_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
52,var_25_has_zero,category,0.0,0.0,2.0,"1, 0"
53,var_26_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
54,var_26_has_zero,category,0.0,0.0,2.0,"1, 0"
55,var_27_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
56,var_27_has_zero,category,0.0,0.0,2.0,"1, 0"
57,var_28_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
58,var_28_has_zero,category,0.0,0.0,2.0,"1, 0"
59,var_29_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
60,var_29_has_zero,category,0.0,0.0,2.0,"1, 0"
61,var_30_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
62,var_30_has_zero,category,0.0,0.0,2.0,"0, 1"
63,var_31_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
64,var_31_has_zero,category,0.0,0.0,2.0,"1, 0"
65,var_32_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
66,var_32_has_zero,category,0.0,0.0,2.0,"1, 0"
67,var_33_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
68,var_33_has_zero,category,0.0,0.0,2.0,"1, 0"
69,var_34_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
70,var_34_has_zero,category,0.0,0.0,2.0,"1, 0"
71,var_35_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
72,var_35_has_zero,category,0.0,0.0,2.0,"1, 0"
73,var_36_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
74,var_36_has_zero,category,0.0,0.0,2.0,"1, 0"
75,var_37_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
76,var_37_has_zero,category,0.0,0.0,2.0,"1, 0"
77,var_38_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
78,var_38_has_zero,category,0.0,0.0,2.0,"1, 0"
79,var_39_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
80,var_39_has_zero,category,0.0,0.0,2.0,"1, 0"
81,var_40_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
82,var_40_has_zero,category,0.0,0.0,2.0,"0, 1"
83,var_41_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
84,var_41_has_zero,category,0.0,0.0,2.0,"1, 0"
85,var_42_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
86,var_42_has_zero,category,0.0,0.0,2.0,"1, 0"
87,var_43_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
88,var_43_has_zero,category,0.0,0.0,2.0,"1, 0"
89,var_44_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
90,var_44_has_zero,category,0.0,0.0,2.0,"1, 0"
91,var_45_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
92,var_45_has_zero,category,0.0,0.0,2.0,"0, 1"
93,var_46_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
94,var_46_has_zero,category,0.0,0.0,2.0,"1, 0"
95,var_47_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
96,var_47_has_zero,category,0.0,0.0,2.0,"0, 1"
97,var_48_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
98,var_48_has_zero,category,0.0,0.0,2.0,"0, 1"
99,var_49_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
100,var_49_has_zero,category,0.0,0.0,2.0,"0, 1"
101,var_50_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
102,var_50_has_zero,category,0.0,0.0,2.0,"1, 0"
103,var_51_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
104,var_51_has_zero,category,0.0,0.0,2.0,"0, 1"
105,var_52_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
106,var_52_has_zero,category,0.0,0.0,2.0,"1, 0"
107,var_53_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
108,var_53_has_zero,category,0.0,0.0,2.0,"1, 0"
109,var_54_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
110,var_54_has_zero,category,0.0,0.0,2.0,"0, 1"
111,var_55_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
112,var_55_has_zero,category,0.0,0.0,2.0,"1, 0"
113,var_56_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
114,var_56_has_zero,category,0.0,0.0,2.0,"1, 0"
115,var_57_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
116,var_57_has_zero,category,0.0,0.0,2.0,"1, 0"
117,var_58_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
118,var_58_has_zero,category,0.0,0.0,2.0,"1, 0"
119,var_59_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
120,var_59_has_zero,category,0.0,0.0,2.0,"1, 0"
121,var_60_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
122,var_60_has_zero,category,0.0,0.0,2.0,"1, 0"
123,var_61_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
124,var_61_has_zero,category,0.0,0.0,2.0,"0, 1"
125,var_62_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
126,var_62_has_zero,category,0.0,0.0,2.0,"1, 0"
127,var_63_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
128,var_63_has_zero,category,0.0,0.0,2.0,"1, 0"
129,var_64_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
130,var_64_has_zero,category,0.0,0.0,2.0,"1, 0"
131,var_65_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
132,var_65_has_zero,category,0.0,0.0,2.0,"1, 0"
133,var_66_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
134,var_66_has_zero,category,0.0,0.0,2.0,"1, 0"
135,var_67_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
136,var_67_has_zero,category,0.0,0.0,2.0,"1, 0"
137,var_68_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
138,var_68_has_zero,category,0.0,0.0,2.0,"1, 0"
139,var_69_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
140,var_69_has_zero,category,0.0,0.0,2.0,"1, 0"
141,var_70_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
142,var_70_has_zero,category,0.0,0.0,2.0,"0, 1"
143,var_71_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
144,var_71_has_zero,category,0.0,0.0,2.0,"1, 0"
145,var_72_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
146,var_72_has_zero,category,0.0,0.0,2.0,"1, 0"
147,var_73_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
148,var_73_has_zero,category,0.0,0.0,2.0,"0, 1"
149,var_74_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
150,var_74_has_zero,category,0.0,0.0,2.0,"0, 1"
151,var_75_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
152,var_75_has_zero,category,0.0,0.0,2.0,"1, 0"
153,var_76_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
154,var_76_has_zero,category,0.0,0.0,2.0,"0, 1"
155,var_77_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
156,var_77_has_zero,category,0.0,0.0,2.0,"1, 0"
157,var_78_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
158,var_78_has_zero,category,0.0,0.0,2.0,"1, 0"
159,var_79_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
160,var_79_has_zero,category,0.0,0.0,2.0,"1, 0"
161,var_80_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
162,var_80_has_zero,category,0.0,0.0,2.0,"1, 0"
163,var_81_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
164,var_81_has_zero,category,0.0,0.0,2.0,"1, 0"
165,var_82_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
166,var_82_has_zero,category,0.0,0.0,2.0,"0, 1"
167,var_83_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
168,var_83_has_zero,category,0.0,0.0,2.0,"0, 1"
169,var_84_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
170,var_84_has_zero,category,0.0,0.0,2.0,"1, 0"
171,var_85_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
172,var_85_has_zero,category,0.0,0.0,2.0,"1, 0"
173,var_86_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
174,var_86_has_zero,category,0.0,0.0,2.0,"0, 1"
175,var_87_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
176,var_87_has_zero,category,0.0,0.0,2.0,"1, 0"
177,var_88_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
178,var_88_has_zero,category,0.0,0.0,2.0,"1, 0"
179,var_89_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
180,var_89_has_zero,category,0.0,0.0,2.0,"1, 0"
181,var_90_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
182,var_90_has_zero,category,0.0,0.0,2.0,"0, 1"
183,var_91_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
184,var_91_has_zero,category,0.0,0.0,2.0,"1, 0"
185,var_92_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
186,var_92_has_zero,category,0.0,0.0,2.0,"1, 0"
187,var_93_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
188,var_93_has_zero,category,0.0,0.0,2.0,"1, 0"
189,var_94_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
190,var_94_has_zero,category,0.0,0.0,2.0,"1, 0"
191,var_95_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
192,var_95_has_zero,category,0.0,0.0,2.0,"1, 0"
193,var_96_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
194,var_96_has_zero,category,0.0,0.0,2.0,"0, 1"
195,var_97_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
196,var_97_has_zero,category,0.0,0.0,2.0,"0, 1"
197,var_98_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
198,var_98_has_zero,category,0.0,0.0,2.0,"1, 0"
199,var_99_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
200,var_99_has_zero,category,0.0,0.0,2.0,"1, 0"
201,var_100_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
202,var_100_has_zero,category,0.0,0.0,2.0,"0, 1"
203,var_101_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
204,var_101_has_zero,category,0.0,0.0,2.0,"1, 0"
205,var_102_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
206,var_102_has_zero,category,0.0,0.0,2.0,"0, 1"
207,var_103_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
208,var_103_has_zero,category,0.0,0.0,2.0,"1, 0"
209,var_104_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
210,var_104_has_zero,category,0.0,0.0,2.0,"1, 0"
211,var_105_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
212,var_105_has_zero,category,0.0,0.0,2.0,"1, 0"
213,var_106_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
214,var_106_has_zero,category,0.0,0.0,2.0,"1, 0"
215,var_107_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
216,var_107_has_zero,category,0.0,0.0,2.0,"1, 0"
217,var_108_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
218,var_108_has_zero,category,0.0,0.0,2.0,"1, 0"
219,var_109_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
220,var_109_has_zero,category,0.0,0.0,2.0,"1, 0"
221,var_110_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
222,var_110_has_zero,category,0.0,0.0,2.0,"1, 0"
223,var_111_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
224,var_111_has_zero,category,0.0,0.0,2.0,"1, 0"
225,var_112_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
226,var_112_has_zero,category,0.0,0.0,2.0,"1, 0"
227,var_113_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
228,var_113_has_zero,category,0.0,0.0,2.0,"1, 0"
229,var_114_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
230,var_114_has_zero,category,0.0,0.0,2.0,"1, 0"
231,var_115_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
232,var_115_has_zero,category,0.0,0.0,2.0,"1, 0"
233,var_116_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
234,var_116_has_zero,category,0.0,0.0,2.0,"1, 0"
235,var_117_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
236,var_117_has_zero,category,0.0,0.0,2.0,"0, 1"
237,var_118_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
238,var_118_has_zero,category,0.0,0.0,2.0,"0, 1"
239,var_119_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
240,var_119_has_zero,category,0.0,0.0,2.0,"1, 0"
241,var_120_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
242,var_120_has_zero,category,0.0,0.0,2.0,"0, 1"
243,var_121_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
244,var_121_has_zero,category,0.0,0.0,2.0,"1, 0"
245,var_122_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
246,var_122_has_zero,category,0.0,0.0,2.0,"1, 0"
247,var_123_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
248,var_123_has_zero,category,0.0,0.0,2.0,"1, 0"
249,var_124_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
250,var_124_has_zero,category,0.0,0.0,2.0,"1, 0"
251,var_125_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
252,var_125_has_zero,category,0.0,0.0,2.0,"1, 0"
253,var_126_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
254,var_126_has_zero,category,0.0,0.0,2.0,"1, 0"
255,var_127_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
256,var_127_has_zero,category,0.0,0.0,2.0,"1, 0"
257,var_128_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
258,var_128_has_zero,category,0.0,0.0,2.0,"1, 0"
259,var_129_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
260,var_129_has_zero,category,0.0,0.0,2.0,"1, 0"
261,var_130_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
262,var_130_has_zero,category,0.0,0.0,2.0,"1, 0"
263,var_131_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
264,var_131_has_zero,category,0.0,0.0,2.0,"1, 0"
265,var_132_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
266,var_132_has_zero,category,0.0,0.0,2.0,"1, 0"
267,var_133_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
268,var_133_has_zero,category,0.0,0.0,2.0,"1, 0"
269,var_134_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
270,var_134_has_zero,category,0.0,0.0,2.0,"1, 0"
271,var_135_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
272,var_135_has_zero,category,0.0,0.0,2.0,"0, 1"
273,var_136_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
274,var_136_has_zero,category,0.0,0.0,2.0,"0, 1"
275,var_137_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
276,var_137_has_zero,category,0.0,0.0,2.0,"0, 1"
277,var_138_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
278,var_138_has_zero,category,0.0,0.0,2.0,"1, 0"
279,var_139_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
280,var_139_has_zero,category,0.0,0.0,2.0,"1, 0"
281,var_140_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
282,var_140_has_zero,category,0.0,0.0,2.0,"1, 0"
283,var_141_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
284,var_141_has_zero,category,0.0,0.0,2.0,"1, 0"
285,var_142_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
286,var_142_has_zero,category,0.0,0.0,2.0,"1, 0"
287,var_143_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
288,var_143_has_zero,category,0.0,0.0,2.0,"1, 0"
289,var_144_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
290,var_144_has_zero,category,0.0,0.0,2.0,"1, 0"
291,var_145_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
292,var_145_has_zero,category,0.0,0.0,2.0,"1, 0"
293,var_146_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
294,var_146_has_zero,category,0.0,0.0,2.0,"1, 0"
295,var_147_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
296,var_147_has_zero,category,0.0,0.0,2.0,"1, 0"
297,var_148_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
298,var_148_has_zero,category,0.0,0.0,2.0,"1, 0"
299,var_149_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
300,var_149_has_zero,category,0.0,0.0,2.0,"0, 1"
301,var_150_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
302,var_150_has_zero,category,0.0,0.0,2.0,"1, 0"
303,var_151_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
304,var_151_has_zero,category,0.0,0.0,2.0,"1, 0"
305,var_152_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
306,var_152_has_zero,category,0.0,0.0,2.0,"1, 0"
307,var_153_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
308,var_153_has_zero,category,0.0,0.0,2.0,"1, 0"
309,var_154_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
310,var_154_has_zero,category,0.0,0.0,2.0,"1, 0"
311,var_155_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
312,var_155_has_zero,category,0.0,0.0,2.0,"1, 0"
313,var_156_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
314,var_156_has_zero,category,0.0,0.0,2.0,"1, 0"
315,var_157_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
316,var_157_has_zero,category,0.0,0.0,2.0,"1, 0"
317,var_158_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
318,var_158_has_zero,category,0.0,0.0,2.0,"0, 1"
319,var_159_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
320,var_159_has_zero,category,0.0,0.0,2.0,"1, 0"
321,var_160_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
322,var_160_has_zero,category,0.0,0.0,2.0,"0, 1"
323,var_161_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
324,var_161_has_zero,category,0.0,0.0,2.0,"1, 0"
325,var_162_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
326,var_162_has_zero,category,0.0,0.0,2.0,"1, 0"
327,var_163_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
328,var_163_has_zero,category,0.0,0.0,2.0,"1, 0"
329,var_164_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
330,var_164_has_zero,category,0.0,0.0,2.0,"1, 0"
331,var_165_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
332,var_165_has_zero,category,0.0,0.0,2.0,"1, 0"
333,var_166_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
334,var_166_has_zero,category,0.0,0.0,2.0,"1, 0"
335,var_167_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
336,var_167_has_zero,category,0.0,0.0,2.0,"0, 1"
337,var_168_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
338,var_168_has_zero,category,0.0,0.0,2.0,"1, 0"
339,var_169_has_one,category,0.0,0.0,4.0,"3, 1, 0, 2"
340,var_169_has_zero,category,0.0,0.0,2.0,"1, 0"
341,var_170_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
342,var_170_has_zero,category,0.0,0.0,2.0,"1, 0"
343,var_171_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
344,var_171_has_zero,category,0.0,0.0,2.0,"1, 0"
345,var_172_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
346,var_172_has_zero,category,0.0,0.0,2.0,"0, 1"
347,var_173_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
348,var_173_has_zero,category,0.0,0.0,2.0,"1, 0"
349,var_174_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
350,var_174_has_zero,category,0.0,0.0,2.0,"1, 0"
351,var_175_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
352,var_175_has_zero,category,0.0,0.0,2.0,"1, 0"
353,var_176_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
354,var_176_has_zero,category,0.0,0.0,2.0,"0, 1"
355,var_177_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
356,var_177_has_zero,category,0.0,0.0,2.0,"1, 0"
357,var_178_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
358,var_178_has_zero,category,0.0,0.0,2.0,"0, 1"
359,var_179_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
360,var_179_has_zero,category,0.0,0.0,2.0,"1, 0"
361,var_180_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
362,var_180_has_zero,category,0.0,0.0,2.0,"1, 0"
363,var_181_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
364,var_181_has_zero,category,0.0,0.0,2.0,"1, 0"
365,var_182_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
366,var_182_has_zero,category,0.0,0.0,2.0,"0, 1"
367,var_183_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
368,var_183_has_zero,category,0.0,0.0,2.0,"1, 0"
369,var_184_has_one,category,0.0,0.0,4.0,"0, 1, 3, 2"
370,var_184_has_zero,category,0.0,0.0,2.0,"0, 1"
371,var_185_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
372,var_185_has_zero,category,0.0,0.0,2.0,"1, 0"
373,var_186_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
374,var_186_has_zero,category,0.0,0.0,2.0,"1, 0"
375,var_187_has_one,category,0.0,0.0,4.0,"0, 1, 2, 3"
376,var_187_has_zero,category,0.0,0.0,2.0,"0, 1"
377,var_188_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
378,var_188_has_zero,category,0.0,0.0,2.0,"1, 0"
379,var_189_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
380,var_189_has_zero,category,0.0,0.0,2.0,"1, 0"
381,var_190_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
382,var_190_has_zero,category,0.0,0.0,2.0,"1, 0"
383,var_191_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
384,var_191_has_zero,category,0.0,0.0,2.0,"1, 0"
385,var_192_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
386,var_192_has_zero,category,0.0,0.0,2.0,"1, 0"
387,var_193_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
388,var_193_has_zero,category,0.0,0.0,2.0,"1, 0"
389,var_194_has_one,category,0.0,0.0,4.0,"1, 0, 3, 2"
390,var_194_has_zero,category,0.0,0.0,2.0,"1, 0"
391,var_195_has_one,category,0.0,0.0,4.0,"1, 3, 0, 2"
392,var_195_has_zero,category,0.0,0.0,2.0,"1, 0"

In [6]:
# Numeric Feature Statistics
numeric_stats

            count       mean        std      min      max
var_0    200000.0  10.679914   3.040051   0.4084  20.3150
var_1    200000.0  -1.627622   4.050044 -15.0434  10.3768
var_2    200000.0  10.715192   2.640894   2.1171  19.3530
var_3    200000.0   6.796529   2.043319  -0.0402  13.1883
var_4    200000.0  11.078333   1.623150   5.0748  16.6714
var_5    200000.0  -5.065317   7.863267 -32.5626  17.2516
var_6    200000.0   5.408949   0.866607   2.3473   8.4477
var_7    200000.0  16.545850   3.418076   5.3497  27.6918
var_8    200000.0   0.284162   3.332634 -10.5055  10.1513
var_9    200000.0   7.567236   1.235070   3.9705  11.1506
var_10   200000.0   0.394340   5.500793 -20.7313  18.6702
var_11   200000.0  -3.245596   5.970253 -26.0950  17.1887
var_12   200000.0  14.023978   0.190059  13.4346  14.6545
var_13   200000.0   8.530232   4.639536  -6.0111  22.3315
var_14   200000.0   7.537606   2.247908   1.0133  14.9377
var_15   200000.0  14.573126   0.411711  13.0769  15.8633
var_16   200000.0   9.333264   2.557421   0.6351  17.9506
var_17   200000.0  -5.696731   6.712612 -33.3802  19.0259
var_18   200000.0  15.244013   7.851370 -10.6642  41.7480
var_19   200000.0  12.438567   7.996694 -12.4025  35.1830
var_20   200000.0  13.290894   5.876254  -5.4322  31.2859
var_21   200000.0  17.257883   8.196564 -10.0890  49.0443
var_22   200000.0   4.305430   2.847958  -5.3225  14.5945
var_23   200000.0   3.019540   0.526893   1.2098   4.8752
var_24   200000.0  10.584400   3.777245  -0.6784  25.4460
var_25   200000.0  13.667496   0.285535  12.7200  14.6546
var_26   200000.0  -4.055133   5.922210 -24.2431  15.6751
var_27   200000.0  -1.137908   1.523714  -6.1668   3.2431
var_28   200000.0   5.532980   0.783367   2.0896   8.7874
var_29   200000.0   5.053874   2.615942  -4.7872  13.1431
var_30   200000.0  -7.687740   7.965198 -34.7984  15.6515
var_31   200000.0  10.393046   2.159891   2.1406  20.1719
var_32   200000.0  -0.512886   2.587830  -8.9861   6.7871
var_33   200000.0  14.774147   4.322325   1.5085  29.5466
var_34   200000.0  11.434250   0.541614   9.8169  13.2878
var_35   200000.0   3.842499   5.179559 -16.5136  21.5289
var_36   200000.0   2.187230   3.119978  -8.0951  14.2456
var_37   200000.0   5.868899   2.249730  -1.1834  11.8638
var_38   200000.0  10.642131   4.278903  -6.3371  29.8235
var_39   200000.0   0.662956   4.068845 -14.5457  15.3223
var_40   200000.0  -6.725505   8.279259 -35.2117  18.1056
var_41   200000.0   9.299858   5.938088  -8.5359  26.1658
var_42   200000.0  11.222356   0.695991   8.8590  13.4696
var_43   200000.0  11.569954   0.309599  10.6528  12.5779
var_44   200000.0   8.948289   5.903073  -9.9396  34.1961
var_45   200000.0 -12.699667  21.404912 -90.2525  62.0844
var_46   200000.0  11.326488   2.860511   1.2062  21.2939
var_47   200000.0 -12.471737  10.579862 -47.6862  20.6854
var_48   200000.0  14.704713  11.384332 -23.9022  54.2738
var_49   200000.0  16.682499   7.855762  -8.0707  41.1530
var_50   200000.0  12.740986   0.691709  10.3855  15.3172
var_51   200000.0  13.428912   8.187306 -15.0462  40.6890
var_52   200000.0  -2.528816   4.985532 -24.7214  17.0968
var_53   200000.0   6.008569   0.764753   3.3449   8.2315
var_54   200000.0   1.137117   8.414241 -26.7786  28.5724
var_55   200000.0  12.745852   5.690072  -3.7826  29.0921
var_56   200000.0  16.629165   3.540174   2.7618  29.0741
var_57   200000.0   6.272014   0.795026   3.4423   9.1609
var_58   200000.0   3.177633   4.296686 -12.6009  20.4833
var_59   200000.0   8.931124   0.854798   6.1840  11.9867
var_60   200000.0  12.155618   4.222389  -2.1006  25.1955
var_61   200000.0 -11.946744  11.622948 -48.8027  27.1029
var_62   200000.0   0.874170   2.026238  -6.3289   7.7536
var_63   200000.0   0.661173   3.113089 -10.5544  11.2317
var_64   200000.0   6.369157   1.485854   1.6117  11.1537
var_65   200000.0   0.982891   3.786493 -14.0888  15.7313
var_66   200000.0   5.794039   1.121366   1.3368   9.7132
var_67   200000.0  11.943223   7.365115 -19.5443  39.3968
var_68   200000.0   5.018893   0.007186   4.9938   5.0469
var_69   200000.0  -3.331515   3.955723 -16.3094   8.5473
var_70   200000.0  24.446811  11.951742 -17.0275  64.4644
var_71   200000.0   0.669756   0.266696  -0.2240   1.5719
var_72   200000.0   0.640553   3.944703 -12.3834  14.1500
var_73   200000.0  19.610888   7.466303  -1.6658  44.5361
var_74   200000.0  19.518846  14.112591 -34.1015  70.2720
var_75   200000.0  16.853732   6.055322  -1.2936  36.1567
var_76   200000.0   6.050871   7.938351 -21.6333  34.4352
var_77   200000.0  19.066993   3.817292   7.4257  30.9569
var_78   200000.0   5.349479   1.993792  -1.8183  11.3507
var_79   200000.0  14.402136   1.309055  10.4454  18.2256
var_80   200000.0   5.795044   7.436737 -18.0422  30.4769
var_81   200000.0  14.719024   2.299567   7.5865  23.1324
var_82   200000.0  -3.471273   8.479255 -30.0266  21.8934
var_83   200000.0   1.025817   8.297229 -24.2201  27.7143
var_84   200000.0  -2.590209   6.225305 -24.4398  17.7424
var_85   200000.0  18.362721   3.908536   7.0230  32.9011
var_86   200000.0   5.621058   7.751142 -19.2722  34.5637
var_87   200000.0  11.351483   5.661867  -8.4816  33.3541
var_88   200000.0   8.702924   2.491460   1.3502  17.4594
var_89   200000.0   3.725208   3.560554  -9.6014  15.4816
var_90   200000.0 -16.548147  13.152810 -61.7180  27.2713
var_91   200000.0   6.987541   0.152641   6.5218   7.4895
var_92   200000.0  12.739578   4.186252  -1.0185  26.9976
var_93   200000.0  10.556740   0.543341   8.4916  12.5343
var_94   200000.0  10.999162   2.768099   2.8190  18.9750
var_95   200000.0  -0.084344   0.621125  -2.4324   1.8040
var_96   200000.0  14.400433   8.525400 -12.1584  40.8806
var_97   200000.0  18.539645  12.642382 -21.7400  58.2879
var_98   200000.0   1.752012   0.715836  -0.6035   4.5028
var_99   200000.0  -0.746296   1.862550  -7.2806   5.0764
var_100  200000.0  -6.600518   9.181683 -39.1791  25.1409
var_101  200000.0  13.413526   4.950537   0.0757  28.4594
var_102  200000.0  22.294908   8.628179  -7.3829  51.3265
var_103  200000.0   1.568393   0.185020   0.9793   2.1887
var_104  200000.0  11.509834   1.970520   4.0846  19.0206
var_105  200000.0   4.244744   0.855698   0.7153   7.1692
var_106  200000.0   8.617657   1.894899   0.9424  15.3074
var_107  200000.0  17.796266   7.604723  -5.8980  46.3795
var_108  200000.0  14.224435   0.171091  13.7290  14.7430
var_109  200000.0  18.458001   4.355031   5.7697  32.0591
var_110  200000.0   5.513238   3.823253  -9.2398  19.5193
var_111  200000.0   6.312603   1.082404   2.1942   9.8002
var_112  200000.0   3.317843   1.591170  -2.0302   8.4317
var_113  200000.0   8.136542   4.459077  -5.5139  21.5421
var_114  200000.0   3.081191   0.985396  -0.0505   6.5850
var_115  200000.0   2.213717   2.621851  -6.8586  11.9504
var_116  200000.0   2.402570   1.650912  -3.1630   8.1207
var_117  200000.0  16.102233  13.297662 -31.8369  64.8109
var_118  200000.0  -5.305132   8.799268 -37.5277  25.2635
var_119  200000.0   3.032849   4.182796  -9.7742  15.6885
var_120  200000.0  24.521078  12.121016 -18.6962  74.0321
var_121  200000.0  11.310591   1.714416   6.3052  17.3074
var_122  200000.0   1.192984   5.168479 -15.1940  18.4714
var_123  200000.0   7.076254   6.147345 -12.4059  26.8749
var_124  200000.0   4.272740   2.736821  -7.0538  14.9915
var_125  200000.0  12.489165   0.318100  11.4861  13.6642
var_126  200000.0  13.202326   0.776056  11.2654  15.5156
var_127  200000.0   0.851507   3.137684  -8.8769  10.5976
var_128  200000.0  -1.127952   3.238043 -11.7559   9.8096
var_129  200000.0  15.460314   4.136453   2.1863  31.2036
var_130  200000.0  12.257151   0.832199   9.5283  14.9895
var_131  200000.0   0.544674   0.456280  -0.9548   2.1923
var_132  200000.0   7.799676   1.456486   2.8900  12.4650
var_133  200000.0   6.813270   0.375603   5.3593   8.3091
var_134  200000.0  -4.826053   6.166126 -24.2546  12.7236
var_135  200000.0  -4.259472   7.617732 -31.3808  21.4128
var_136  200000.0  22.968602  10.382235  -9.9493  54.5794
var_137  200000.0  17.613651   8.890516  -9.8510  44.4376
var_138  200000.0   1.210792   4.551750 -16.4684  18.8187
var_139  200000.0   7.760193   7.686433 -21.2743  36.0971
var_140  200000.0   3.423636   4.896325 -15.4595  21.1219
var_141  200000.0   2.897596   6.715637 -16.6937  23.9658
var_142  200000.0  11.983489   5.691936  -7.1080  32.8911
var_143  200000.0  12.333698   2.934706   2.8068  22.6916
var_144  200000.0   8.647632   0.922469   5.4443  11.8101
var_145  200000.0   4.841328   3.899281  -8.2734  16.0083
var_146  200000.0  10.341178   2.518883   0.4274  20.4373
var_147  200000.0  -3.300779   7.413301 -29.9840  22.1494
var_148  200000.0   3.990726   0.199192   3.3205   4.7528
var_149  200000.0   5.296237  10.385133 -41.1683  48.4240
var_150  200000.0  16.817671   2.464157   9.2420  25.4357
var_151  200000.0  10.141542   3.962426  -2.1915  21.1245
var_152  200000.0   7.633199   3.005373  -2.8800  18.3846
var_153  200000.0  16.727902   2.014200  11.0308  24.0075
var_154  200000.0   6.974955   4.961678  -8.1966  23.2428
var_155  200000.0  -2.074128   5.771261 -21.8409  16.8316
var_156  200000.0  13.209272   0.955140   9.9965  16.4970
var_157  200000.0  -4.813552   5.570272 -22.9904  11.9721
var_158  200000.0  17.914591   7.885579  -4.5544  44.7795
var_159  200000.0  10.223282   4.122912  -4.6416  25.1200
var_160  200000.0  24.259300  10.880263  -7.4522  58.3942
var_161  200000.0   5.633293   0.217938   4.8526   6.3099
var_162  200000.0   5.362896   1.419612   0.6231  10.1344
var_163  200000.0  11.002170   5.262056  -6.5317  27.5648
var_164  200000.0  -2.871906   5.457784 -19.9977  12.1193
var_165  200000.0  19.315753   5.024182   3.8167  38.3322
var_166  200000.0   2.963335   0.369684   1.8512   4.2204
var_167  200000.0  -4.151155   7.798020 -35.9695  21.2766
var_168  200000.0   4.937124   3.105986  -5.2502  14.8861
var_169  200000.0   5.636008   0.369437   4.2588   7.0890
var_170  200000.0  -0.004962   4.424621 -14.5060  16.7319
var_171  200000.0  -0.831777   5.378008 -22.4793  17.9173
var_172  200000.0  19.817094   8.674171 -11.4533  53.5919
var_173  200000.0  -0.677967   5.966674 -22.7487  18.8554
var_174  200000.0  20.210677   7.136427  -2.9953  43.5468
var_175  200000.0  11.640613   2.892167   3.2415  20.8548
var_176  200000.0  -2.799585   7.513939 -29.1165  20.2452
var_177  200000.0  11.882933   2.628895   4.9521  20.5965
var_178  200000.0  -1.014064   8.579810 -29.2734  29.8413
var_179  200000.0   2.591444   2.798956  -7.8561  13.4487
var_180  200000.0  -2.741666   5.261243 -22.0374  12.7505
var_181  200000.0  10.085518   1.371862   5.4165  14.3939
var_182  200000.0   0.719109   8.963434 -26.0011  29.2487
var_183  200000.0   8.769088   4.474924  -4.8082  23.7049
var_184  200000.0  12.756676   9.318280 -18.4897  44.3634
var_185  200000.0  -3.983261   4.725167 -22.5833  12.9975
var_186  200000.0   8.970274   3.189759  -3.0223  21.7392
var_187  200000.0 -10.335043  11.574708 -47.7536  22.7861
var_188  200000.0  15.377174   3.944604   4.4123  29.3303
var_189  200000.0   0.746072   0.976348  -2.5543   4.0341
var_190  200000.0   3.234440   4.559922 -14.0933  18.4409
var_191  200000.0   7.438408   3.023272  -2.6917  16.7165
var_192  200000.0   1.927839   1.478423  -3.8145   8.4024
var_193  200000.0   3.331774   3.992030 -11.7834  18.2818
var_194  200000.0  17.993784   3.135162   8.6944  27.9288
var_195  200000.0  -0.142088   1.429372  -5.2610   4.2729
var_196  200000.0   2.303335   5.454369 -14.2096  18.3215
var_197  200000.0   8.908158   0.921625   5.9606  12.0004
var_198  200000.0  15.870720   3.010945   6.2993  26.0791
var_199  200000.0  -3.326537  10.438015 -38.8528  28.5007

In [7]:
# Categorical Feature Statistics
cat_stats

                      value   count    pct
column           rank
target           1        0  179902  89.95
                 2        1   20098  10.05
var_0_has_one    1        1  126381  63.19
                 2        0   40355  20.18
                 3        3   27409  13.70
                 4        2    5855   2.93
var_0_has_zero   1        1  153790  76.90
                 2        0   46210  23.10
var_100_has_one  1        0  111407  55.70
                 2        1   76729  38.36
                 3        2    6503   3.25
                 4        3    5361   2.68
var_100_has_zero 1        0  117910  58.96
                 2        1   82090  41.04
var_101_has_one  1        1  108907  54.45
                 2        0   70054  35.03
                 3        3   13834   6.92
                 4        2    7205   3.60
var_101_has_zero 1        1  122741  61.37
                 2        0   77259  38.63
var_102_has_one  1        0  104560  52.28
                 2        1   82278  41.14
                 3        2    6761   3.38
                 4        3    6401   3.20
var_102_has_zero 1        0  111321  55.66
                 2        1   88679  44.34
var_103_has_one  1        3  181251  90.63
                 2        1   17924   8.96
                 3        0     747   0.37
                 4        2      78   0.04
var_103_has_zero 1        1  199175  99.59
                 2        0     825   0.41
var_104_has_one  1        1  128694  64.35
                 2        3   45375  22.69
                 3        0   22009  11.00
                 4        2    3922   1.96
var_104_has_zero 1        1  174069  87.03
                 2        0   25931  12.97
var_105_has_one  1        1  100409  50.20
                 2        3   91253  45.63
                 3        0    7054   3.53
                 4        2    1284   0.64
var_105_has_zero 1        1  191662  95.83
                 2        0    8338   4.17
var_106_has_one  1        1  128475  64.24
                 2        3   46279  23.14
                 3        0   21382  10.69
                 4        2    3864   1.93
var_106_has_zero 1        1  174754  87.38
                 2        0   25246  12.62
var_107_has_one  1        0   92223  46.11
                 2        1   91994  46.00
                 3        3    8759   4.38
                 4        2    7024   3.51
var_107_has_zero 1        1  100753  50.38
                 2        0   99247  49.62
var_108_has_one  1        3  184331  92.17
                 2        1   15226   7.61
                 3        0     345   0.17
                 4        2      98   0.05
var_108_has_zero 1        1  199557  99.78
                 2        0     443   0.22
var_109_has_one  1        1  116612  58.31
                 2        0   58241  29.12
                 3        3   18350   9.18
                 4        2    6797   3.40
var_109_has_zero 1        1  134962  67.48
                 2        0   65038  32.52
var_10_has_one   1        1  102283  51.14
                 2        0   78867  39.43
                 3        3   11584   5.79
                 4        2    7266   3.63
var_10_has_zero  1        1  113867  56.93
                 2        0   86133  43.07
var_110_has_one  1        1  119832  59.92
                 2        0   52487  26.24
                 3        3   21215  10.61
                 4        2    6466   3.23
var_110_has_zero 1        1  141047  70.52
                 2        0   58953  29.48
var_111_has_one  1        1  113079  56.54
                 2        3   76387  38.19
                 3        0    8827   4.41
                 4        2    1707   0.85
var_111_has_zero 1        1  189466  94.73
                 2        0   10534   5.27
var_112_has_one  1        1  128597  64.30
                 2        3   55490  27.74
                 3        0   13046   6.52
                 4        2    2867   1.43
var_112_has_zero 1        1  184087  92.04
                 2        0   15913   7.96
var_113_has_one  1        1  113683  56.84
                 2        0   62988  31.49
                 3        3   16295   8.15
                 4        2    7034   3.52
var_113_has_zero 1        1  129978  64.99
                 2        0   70022  35.01
var_114_has_one  1        1  109286  54.64
                 2        3   81645  40.82
                 3        0    7604   3.80
                 4        2    1465   0.73
var_114_has_zero 1        1  190931  95.47
                 2        0    9069   4.53
var_115_has_one  1        1  128536  64.27
                 2        3   33245  16.62
                 3        0   32973  16.49
                 4        2    5246   2.62
var_115_has_zero 1        1  161781  80.89
                 2        0   38219  19.11
var_116_has_one  1        1  128683  64.34
                 2        3   52830  26.42
                 3        0   15302   7.65
                 4        2    3185   1.59
var_116_has_zero 1        1  181513  90.76
                 2        0   18487   9.24
var_117_has_one  1        0  133952  66.98
                 2        1   58095  29.05
                 3        2    5336   2.67
                 4        3    2617   1.31
var_117_has_zero 1        0  139288  69.64
                 2        1   60712  30.36
var_118_has_one  1        0  100883  50.44
                 2        1   85254  42.63
                 3        3    7149   3.57
                 4        2    6714   3.36
var_118_has_zero 1        0  107597  53.80
                 2        1   92403  46.20
var_119_has_one  1        1  116430  58.22
                 2        0   58444  29.22
                 3        3   18204   9.10
                 4        2    6922   3.46
var_119_has_zero 1        1  134634  67.32
                 2        0   65366  32.68
var_11_has_one   1        1   99752  49.88
                 2        0   81636  40.82
                 3        3   11566   5.78
                 4        2    7046   3.52
var_11_has_zero  1        1  111318  55.66
                 2        0   88682  44.34
var_120_has_one  1        0  123788  61.89
                 2        1   66232  33.12
                 3        2    5981   2.99
                 4        3    3999   2.00
var_120_has_zero 1        0  129769  64.88
                 2        1   70231  35.12
var_121_has_one  1        1  129079  64.54
                 2        3   51523  25.76
                 3        0   16092   8.05
                 4        2    3306   1.65
var_121_has_zero 1        1  180602  90.30
                 2        0   19398   9.70
var_122_has_one  1        1  108495  54.25
                 2        0   70123  35.06
                 3        3   14327   7.16
                 4        2    7055   3.53
var_122_has_zero 1        1  122822  61.41
                 2        0   77178  38.59
var_123_has_one  1        1  100723  50.36
                 2        0   81122  40.56
                 3        3   11124   5.56
                 4        2    7031   3.52
var_123_has_zero 1        1  111847  55.92
                 2        0   88153  44.08
var_124_has_one  1        1  127341  63.67
                 2        0   36462  18.23
                 3        3   30692  15.35
                 4        2    5505   2.75
var_124_has_zero 1        1  158033  79.02
                 2        0   41967  20.98
var_125_has_one  1        3  156534  78.27
                 2        1   41441  20.72
                 3        0    1689   0.84
                 4        2     336   0.17
var_125_has_zero 1        1  197975  98.99
                 2        0    2025   1.01
var_126_has_one  1        3  100946  50.47
                 2        1   94662  47.33
                 3        0    3695   1.85
                 4        2     697   0.35
var_126_has_zero 1        1  195608  97.80
                 2        0    4392   2.20
var_127_has_one  1        1  126722  63.36
                 2        0   40188  20.09
                 3        3   27121  13.56
                 4        2    5969   2.98
var_127_has_zero 1        1  153843  76.92
                 2        0   46157  23.08
var_128_has_one  1        1  125674  62.84
                 2        0   42377  21.19
                 3        3   25796  12.90
                 4        2    6153   3.08
var_128_has_zero 1        1  151470  75.74
                 2        0   48530  24.26
var_129_has_one  1        1  114995  57.50
                 2        0   59726  29.86
                 3        3   18512   9.26
                 4        2    6767   3.38
var_129_has_zero 1        1  133507  66.75
                 2        0   66493  33.25
var_12_has_one   1        3  180386  90.19
                 2        1   19005   9.50
                 3        0     476   0.24
                 4        2     133   0.07
var_12_has_zero  1        1  199391  99.70
                 2        0     609   0.30
var_130_has_one  1        1  101085  50.54
                 2        3   92488  46.24
                 3        0    5357   2.68
                 4        2    1070   0.53
var_130_has_zero 1        1  193573  96.79
                 2        0    6427   3.21
var_131_has_one  1        3  133132  66.57
                 2        1   64318  32.16
                 3        0    2119   1.06
                 4        2     431   0.22
var_131_has_zero 1        1  197450  98.72
                 2        0    2550   1.27
var_132_has_one  1        1  125741  62.87
                 2        3   58844  29.42
                 3        0   12809   6.40
                 4        2    2606   1.30
var_132_has_zero 1        1  184585  92.29
                 2        0   15415   7.71
var_133_has_one  1        3  145033  72.52
                 2        1   52113  26.06
                 3        0    2319   1.16
                 4        2     535   0.27
var_133_has_zero 1        1  197146  98.57
                 2        0    2854   1.43
var_134_has_one  1        1   99320  49.66
                 2        0   82833  41.42
                 3        3   10619   5.31
                 4        2    7228   3.61
var_134_has_zero 1        1  109939  54.97
                 2        0   90061  45.03
var_135_has_one  1        0   96473  48.24
                 2        1   88535  44.27
                 3        3    8119   4.06
                 4        2    6873   3.44
var_135_has_zero 1        0  103346  51.67
                 2        1   96654  48.33
var_136_has_one  1        0  120534  60.27
                 2        1   69496  34.75
                 3        2    6097   3.05
                 4        3    3873   1.94
var_136_has_zero 1        0  126631  63.32
                 2        1   73369  36.68
var_137_has_one  1        0  101921  50.96
                 2        1   84310  42.16
                 3        3    7109   3.55
                 4        2    6660   3.33
var_137_has_zero 1        0  108581  54.29
                 2        1   91419  45.71
var_138_has_one  1        1  111975  55.99
                 2        0   64797  32.40
                 3        3   16300   8.15
                 4        2    6928   3.46
var_138_has_zero 1        1  128275  64.14
                 2        0   71725  35.86
var_139_has_one  1        1   92747  46.37
                 2        0   91822  45.91
                 3        3    8433   4.22
                 4        2    6998   3.50
var_139_has_zero 1        1  101180  50.59
                 2        0   98820  49.41
var_13_has_one   1        1  114728  57.36
                 2        0   61559  30.78
                 3        3   16698   8.35
                 4        2    7015   3.51
var_13_has_zero  1        1  131426  65.71
                 2        0   68574  34.29
var_140_has_one  1        1  108683  54.34
                 2        0   69446  34.72
                 3        3   14826   7.41
                 4        2    7045   3.52
var_140_has_zero 1        1  123509  61.75
                 2        0   76491  38.25
var_141_has_one  1        1   95985  47.99
                 2        0   87172  43.59
                 3        3    9869   4.93
                 4        2    6974   3.49
var_141_has_zero 1        1  105854  52.93
                 2        0   94146  47.07
var_142_has_one  1        1  102203  51.10
                 2        0   79028  39.51
                 3        3   11719   5.86
                 4        2    7050   3.52
var_142_has_zero 1        1  113922  56.96
                 2        0   86078  43.04
var_143_has_one  1        1  125920  62.96
                 2        0   39694  19.85
                 3        3   28693  14.35
                 4        2    5693   2.85
var_143_has_zero 1        1  154613  77.31
                 2        0   45387  22.69
var_144_has_one  1        1  106685  53.34
                 2        3   85565  42.78
                 3        0    6509   3.25
                 4        2    1241   0.62
var_144_has_zero 1        1  192250  96.12
                 2        0    7750   3.88
var_145_has_one  1        1  119354  59.68
                 2        0   53889  26.94
                 3        3   20106  10.05
                 4        2    6651   3.33
var_145_has_zero 1        1  139460  69.73
                 2        0   60540  30.27
var_146_has_one  1        1  128460  64.23
                 2        3   34791  17.40
                 3        0   31669  15.83
                 4        2    5080   2.54
var_146_has_zero 1        1  163251  81.63
                 2        0   36749  18.37
var_147_has_one  1        1   92377  46.19
                 2        0   91868  45.93
                 3        3    8770   4.38
                 4        2    6985   3.49
var_147_has_zero 1        1  101147  50.57
                 2        0   98853  49.43
var_148_has_one  1        3  177919  88.96
                 2        1   21103  10.55
                 3        0     828   0.41
                 4        2     150   0.08
var_148_has_zero 1        1  199022  99.51
                 2        0     978   0.49
var_149_has_one  1        0  108370  54.18
                 2        1   79038  39.52
                 3        2    6455   3.23
                 4        3    6137   3.07
var_149_has_zero 1        0  114825  57.41
                 2        1   85175  42.59
var_14_has_one   1        1  132551  66.28
                 2        3   38043  19.02
                 3        0   24670  12.34
                 4        2    4736   2.37
var_14_has_zero  1        1  170594  85.30
                 2        0   29406  14.70
var_150_has_one  1        1  131069  65.53
                 2        3   34864  17.43
                 3        0   28952  14.48
                 4        2    5115   2.56
var_150_has_zero 1        1  165933  82.97
                 2        0   34067  17.03
var_151_has_one  1        1  118806  59.40
                 2        0   55072  27.54
                 3        3   19294   9.65
                 4        2    6828   3.41
var_151_has_zero 1        1  138100  69.05
                 2        0   61900  30.95
var_152_has_one  1        1  125411  62.71
                 2        0   41083  20.54
                 3        3   27645  13.82
                 4        2    5861   2.93
var_152_has_zero 1        1  153056  76.53
                 2        0   46944  23.47
var_153_has_one  1        1  131417  65.71
                 2        3   43123  21.56
                 3        0   21318  10.66
                 4        2    4142   2.07
var_153_has_zero 1        1  174540  87.27
                 2        0   25460  12.73
var_154_has_one  1        1  110902  55.45
                 2        0   67053  33.53
                 3        3   15017   7.51
                 4        2    7028   3.51
var_154_has_zero 1        1  125919  62.96
                 2        0   74081  37.04
var_155_has_one  1        1  102744  51.37
                 2        0   78016  39.01
                 3        3   12230   6.12
                 4        2    7010   3.50
var_155_has_zero 1        1  114974  57.49
                 2        0   85026  42.51
var_156_has_one  1        1  108770  54.38
                 2        3   84263  42.13
                 3        0    5788   2.89
                 4        2    1179   0.59
var_156_has_zero 1        1  193033  96.52
                 2        0    6967   3.48
var_157_has_one  1        1  103753  51.88
                 2        0   76587  38.29
                 3        3   12655   6.33
                 4        2    7005   3.50
var_157_has_zero 1        1  116408  58.20
                 2        0   83592  41.80
var_158_has_one  1        0  101502  50.75
                 2        1   84757  42.38
                 3        2    6871   3.44
                 4        3    6870   3.44
var_158_has_zero 1        0  108373  54.19
                 2        1   91627  45.81
var_159_has_one  1        1  115890  57.94
                 2        0   59096  29.55
                 3        3   18089   9.04
                 4        2    6925   3.46
var_159_has_zero 1        1  133979  66.99
                 2        0   66021  33.01
var_15_has_one   1        3  139724  69.86
                 2        1   58134  29.07
                 3        0    1797   0.90
                 4        2     345   0.17
var_15_has_zero  1        1  197858  98.93
                 2        0    2142   1.07
var_160_has_one  1        0  120148  60.07
                 2        1   69372  34.69
                 3        2    6185   3.09
                 4        3    4295   2.15
var_160_has_zero 1        0  126333  63.17
                 2        1   73667  36.83
var_161_has_one  1        3  175227  87.61
                 2        1   23920  11.96
                 3        0     733   0.37
                 4        2     120   0.06
var_161_has_zero 1        1  199147  99.57
                 2        0     853   0.43
var_162_has_one  1        1  123305  61.65
                 2        3   60896  30.45
                 3        0   13224   6.61
                 4        2    2575   1.29
var_162_has_zero 1        1  184201  92.10
                 2        0   15799   7.90
var_163_has_one  1        1  107204  53.60
                 2        0   72147  36.07
                 3        3   13535   6.77
                 4        2    7114   3.56
var_163_has_zero 1        1  120739  60.37
                 2        0   79261  39.63
var_164_has_one  1        1  107544  53.77
                 2        0   71367  35.68
                 3        3   13999   7.00
                 4        2    7090   3.55
var_164_has_zero 1        1  121543  60.77
                 2        0   78457  39.23
var_165_has_one  1        1  109736  54.87
                 2        0   67708  33.85
                 3        3   15587   7.79
                 4        2    6969   3.48
var_165_has_zero 1        1  125323  62.66
                 2        0   74677  37.34
var_166_has_one  1        3  146390  73.19
                 2        1   51865  25.93
                 3        0    1325   0.66
                 4        2     420   0.21
var_166_has_zero 1        1  198255  99.13
                 2        0    1745   0.87
var_167_has_one  1        0   96843  48.42
                 2        1   88221  44.11
                 3        3    8298   4.15
                 4        2    6638   3.32
var_167_has_zero 1        0  103481  51.74
                 2        1   96519  48.26
var_168_has_one  1        1  124269  62.13
                 2        0   42907  21.45
                 3        3   26924  13.46
                 4        2    5900   2.95
var_168_has_zero 1        1  151193  75.60
                 2        0   48807  24.40
var_169_has_one  1        3  146537  73.27
                 2        1   51402  25.70
                 3        0    1704   0.85
                 4        2     357   0.18
var_169_has_zero 1        1  197939  98.97

In [8]:
# Target Distribution
target_df

         count    pct
target
0       179902  89.95
1        20098  10.05

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...

Saving curated container to santander_customer_transaction_prediction/019d5dc9-73a2-7c3a-857c-8ecf5209804a

019d5dc9-73a2-7c3a-857c-8ecf5209804a
89c3ba280f38f7831e074d3c51d2cc323d275537e622d38861d069ec8c237507