### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="electric_motor_temperature_prediction",
    dataset_year="2021",
    domain_str="industry & manufacturing",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/datasets/wkirgsn/electric-motor-temperature",
    download_description="""
kaggle datasets download wkirgsn/electric-motor-temperature --unzip \
&& mkdir -p local-data-warehouse/electric_motor_temperature_prediction \
&& mv measures_v2.csv local-data-warehouse/electric_motor_temperature_prediction/
""",
    # References
    academic_reference_bibtex="""@article{kirchgassner2020estimating,
  title={Estimating electric motor temperatures with deep residual machine learning},
  author={Kirchg{\"a}ssner, Wilhelm and Wallscheid, Oliver and B{\"o}cker, Joachim},
  journal={IEEE Transactions on Power Electronics},
  volume={36},
  number={7},
  pages={7480--7488},
  year={2020},
  publisher={IEEE}
}
""",
    academic_reference_bibtex_key="kirchgassner2020estimating",
    license="CC BY-SA 4.0",
    data_tags=["Non-IID", "Grouped"],
    curation_comments="""
We select the task to predict permanent magnet temperature from the input features. We create grouped splits on the profile_id, which corresponds to predicting the temperature for an unseen motor run session, thus simulating how the model would be used in reality.

- The original study also incorporates temporal connection within the session. We re-create a time-index (https://www.kaggle.com/datasets/wkirgsn/electric-motor-temperature/discussion/147446).
- We also add the derived inputs used in the original study.
- We also add the EWMA/WEMS features with window sizes of [500, 2000, 4000, 8000]. To avoid the problem of having an incorrect EWMA/WEMS state and since not all recording are warmed up (https://www.kaggle.com/datasets/wkirgsn/electric-motor-temperature/discussion/117319), we drop the first 500 samples (first span) of each profile to simulate such a warm-up.
"""
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="permanent_magnet_temperature",
    problem_type="regression",
    objective_metric_name="rmse",
    # For grouped data
    group_on="profile_id",
    group_labels="per_sample",
    group_time_on="profile_time_index"
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(dataset_mold.path / "measures_v2.csv")
print("Loaded data shape:", df.shape)

# Add time feature
df["profile_time_index"] = df.groupby("profile_id").cumcount() + 1

df = df.rename(columns={
    "pm": "permanent_magnet_temperature",
})

df = df.drop(columns=[
    # Other targets
    "stator_winding",
    "stator_tooth",
    "stator_yoke",
    # excluded as in the original study
    "torque",
])

# Add derived features  (from Table II)
# Voltage magnitude
df["u_s"] = np.sqrt(df["u_d"]**2 + df["u_q"]**2)
# Current magnitude
df["i_s"] = np.sqrt(df["i_d"]**2 + df["i_q"]**2)
# Apparent power
df["S_el"] = df["u_s"] * df["i_s"]
# Joint interaction terms
df["i_s_omega"] = df["i_s"] * df["motor_speed"]
df["S_el_omega"] = df["S_el"] * df["motor_speed"]


def add_grouped_ewm_features(
    input_df: pd.DataFrame,
    group_col: str,
    time_col: str,
    cols: list[str],
    input_spans: list[int],
) -> pd.DataFrame:
    input_df = input_df.sort_values([group_col, time_col]).copy()

    for col in cols:
        for span in input_spans:
            alpha = 2 / (span + 1)

            # EWMA
            input_df[f"{col}_ewma_{span}"] = (
                input_df.groupby(group_col, sort=False)[col]
                  .transform(lambda s: s.ewm(alpha=alpha, adjust=False).mean())
            )

            # EWMS
            input_df[f"{col}_ewms_{span}"] = (
                input_df.groupby(group_col, sort=False)[col]
                  .transform(lambda s: s.ewm(alpha=alpha, adjust=False).std())
            )

    return input_df

input_cols = [
    # Original features
    "u_d", "u_q",
    "i_d", "i_q",
    "coolant", "motor_speed", "ambient",
    # Derived features
    "u_s", "i_s", "S_el", "i_s_omega", "S_el_omega",
]
spans = [500, 2000, 4000, 8000]
df = add_grouped_ewm_features(
    input_df=df,
    group_col="profile_id",
    time_col="profile_time_index",
    cols=input_cols,
    input_spans=spans,
)

# Drop the first 500 samples of each profile to simulate warm-up and avoid incorrect EWMA/WEMS state
df = (
    df.sort_values(["profile_id", "profile_time_index"])
      .loc[lambda d: d.groupby("profile_id").cumcount() >= 500]
      .reset_index(drop=True)
)
df["profile_id"] = df["profile_id"].astype("category")
df = df.sample(frac=1, random_state=42).reset_index(drop=True) # Shuffle data

Loaded data shape: (1330816, 13)
['u_q', 'coolant', 'u_d', 'motor_speed', 'i_d', 'i_q', 'permanent_magnet_temperature', 'ambient', 'profile_id', 'profile_time_index', 'u_s', 'i_s', 'S_el', 'i_s_omega', 'S_el_omega']

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 1,296,316
Columns: 111
Use sampling: True (sample size: 129,632)
Get missing and unique counts per column...

missing/unique per-col:   0%|          | 0/111 [00:00<?, ?it/s]

Get example values per column...

examples per-col:   0%|          | 0/111 [00:00<?, ?it/s]

Get numeric feature statistics...

numeric stats:   0%|          | 0/110 [00:00<?, ?it/s]

Get cat stats...

cat stats:   0%|          | 0/1 [00:00<?, ?it/s]

Get target stats...
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['S_el', 'u_d_ewma_500', 'S_el_omega', 'u_q_ewma_4000', 'u_q_ewms_2000', 'u_q_ewma_2000', 'u_q_ewms_500', 'u_q_ewma_500', 'u_d_ewms_8000', 'u_d_ewma_8000']
Rows remaining as candidates after top-10 filter: 0 (of 1,296,316)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...

hash cols:   0%|          | 0/111 [00:00<?, ?it/s]

group check:   0%|          | 0/111 [00:00<?, ?it/s]

Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,u_q,coolant,u_d,motor_speed,i_d,i_q,permanent_magnet_temperature,ambient,profile_id,profile_time_index,u_s,i_s,S_el,i_s_omega,S_el_omega,u_d_ewma_500,u_d_ewms_500,u_d_ewma_2000,u_d_ewms_2000,u_d_ewma_4000,u_d_ewms_4000,u_d_ewma_8000,u_d_ewms_8000,u_q_ewma_500,u_q_ewms_500,u_q_ewma_2000,u_q_ewms_2000,u_q_ewma_4000,u_q_ewms_4000,u_q_ewma_8000,u_q_ewms_8000,i_d_ewma_500,i_d_ewms_500,i_d_ewma_2000,i_d_ewms_2000,i_d_ewma_4000,i_d_ewms_4000,i_d_ewma_8000,i_d_ewms_8000,i_q_ewma_500,i_q_ewms_500,i_q_ewma_2000,i_q_ewms_2000,i_q_ewma_4000,i_q_ewms_4000,i_q_ewma_8000,i_q_ewms_8000,coolant_ewma_500,coolant_ewms_500,coolant_ewma_2000,coolant_ewms_2000,coolant_ewma_4000,coolant_ewms_4000,coolant_ewma_8000,coolant_ewms_8000,motor_speed_ewma_500,motor_speed_ewms_500,motor_speed_ewma_2000,motor_speed_ewms_2000,motor_speed_ewma_4000,motor_speed_ewms_4000,motor_speed_ewma_8000,motor_speed_ewms_8000,ambient_ewma_500,ambient_ewms_500,ambient_ewma_2000,ambient_ewms_2000,ambient_ewma_4000,ambient_ewms_4000,ambient_ewma_8000,ambient_ewms_8000,u_s_ewma_500,u_s_ewms_500,u_s_ewma_2000,u_s_ewms_2000,u_s_ewma_4000,u_s_ewms_4000,u_s_ewma_8000,u_s_ewms_8000,i_s_ewma_500,i_s_ewms_500,i_s_ewma_2000,i_s_ewms_2000,i_s_ewma_4000,i_s_ewms_4000,i_s_ewma_8000,i_s_ewms_8000,S_el_ewma_500,S_el_ewms_500,S_el_ewma_2000,S_el_ewms_2000,S_el_ewma_4000,S_el_ewms_4000,S_el_ewma_8000,S_el_ewms_8000,i_s_omega_ewma_500,i_s_omega_ewms_500,i_s_omega_ewma_2000,i_s_omega_ewms_2000,i_s_omega_ewma_4000,i_s_omega_ewms_4000,i_s_omega_ewma_8000,i_s_omega_ewms_8000,S_el_omega_ewma_500,S_el_omega_ewms_500,S_el_omega_ewma_2000,S_el_omega_ewms_2000,S_el_omega_ewma_4000,S_el_omega_ewms_4000,S_el_omega_ewma_8000,S_el_omega_ewms_8000
0,-2.096244,62.223688,1.664608,0.001003,-2.000487,1.098619,77.498236,26.346033,76,8768,2.676781,2.282304,6.109228,2.289900e-03,6.129562e-03,-7.681700,33.894432,-13.084412,56.318832,-8.343476,57.705183,-4.340015,56.511980,22.211271,46.429748,53.005856,52.531843,51.058756,50.909152,45.515545,50.085248,-23.573697,46.402029,-59.706847,62.583651,-58.947646,62.471776,-53.909337,62.031806,7.635789,28.387802,3.152057,58.250874,-0.009774,63.472660,0.191756,65.279577,62.248308,1.012289,64.898807,6.573771,65.555176,10.269212,60.149717,16.892353,956.818779,1795.513671,2337.807946,2168.929170,2248.092343,2141.273858,1997.821703,2127.554420,26.292732,0.290655,26.265771,0.210988,26.175974,0.238199,26.032000,0.289304,32.129543,53.137874,73.189597,59.618137,71.580259,58.936519,64.913978,59.596189,27.739290,52.945824,74.513296,73.017123,76.123210,74.904216,71.367421,76.774950,3329.223425,6908.195966,8816.089050,9243.507212,8812.747252,9333.239652,8134.737250,9393.879517,107834.945862,227674.028276,287834.474368,311944.039037,282360.115089,311999.144228,255549.256997,309857.469639,1.388807e+07,2.935391e+07,3.641664e+07,4.047250e+07,3.548600e+07,4.050924e+07,3.196538e+07,4.010690e+07
1,-2.173978,74.151566,0.222524,0.003956,-2.002110,1.096618,61.762292,25.092981,63,5902,2.185337,2.282765,4.988610,9.030746e-03,1.973522e-02,3.041417,27.035296,-4.161962,61.560295,-6.861791,69.119375,-6.226701,67.655363,7.796962,27.281483,40.622455,42.781444,50.308691,42.647332,46.185097,44.716979,-10.592248,31.571030,-48.331580,60.780923,-61.580542,63.564765,-56.931277,65.070159,-3.872850,35.139565,0.470308,81.199107,5.301869,90.787242,6.637607,88.415767,59.891418,10.782185,48.812016,10.486852,43.499313,10.861997,38.110591,11.016667,336.482200,938.203975,1567.383648,1613.048426,1970.365755,1652.176466,1812.880386,1749.009722,25.099772,0.096264,25.114710,0.122790,25.062778,0.145831,24.985583,0.162289,15.832692,35.974898,63.920981,56.571265,78.502849,54.780455,71.881252,58.446980,17.389276,45.342868,77.510413,81.326810,96.013733,82.875031,87.390350,86.364499,1592.033664,5361.396601,8411.954174,10209.444868,10730.494083,10539.996273,9841.826750,10817.198686,40346.324874,145094.174096,209923.683232,271092.522343,270117.401672,284016.725248,249596.625905,291665.569730,4.873236e+06,1.872292e+07,2.571203e+07,3.543306e+07,3.332437e+07,3.735109e+07,3.089541e+07,3.813413e+07
2,16.907560,61.157390,11.138434,453.221274,-15.467547,-73.869407,68.503790,26.109660,79,17370,20.246736,75.471413,1528.049758,3.420525e+04,6.925447e+05,43.179571,39.515811,27.624059,45.451400,18.954410,51.190063,11.774005,56.217740,24.039895,20.952296,19.635905,31.171362,28.382989,40.705299,36.470803,45.182045,-53.274133,42.222120,-38.719451,49.979013,-42.954378,54.131835,-49.795055,57.623869,-127.542869,71.905905,-61.776550,87.613916,-37.824337,84.214944,-23.121192,82.388481,53.824962,2.222005,53.827519,3.844842,55.381091,6.783040,55.609698,10.837483,930.784421,847.428778,862.369608,1296.179642,1247.112829,1723.083387,1615.415621,1952.654487,26.071838,0.127407,25.999394,0.283052,25.965156,0.284676,25.848303,0.363157,50.663518,43.311067,40.671491,50.316179,48.631660,55.469533,57.297779,58.198185,140.254720,79.912218,81.424112,94.122763,75.206735,87.415807,77.972912,83.915624,9483.473540,9776.633967,6990.316312,10018.862520,7266.936099,9795.048101,8041.165463,9734.471808,170835.653587,179941.502864,144428.394160,217030.815773,180417.890017,256667.076509,222373.689998,285723.081038,1.601818e+07,2.349027e+07,1.600408e+07,2.766575e+07,2.146984e+07,3.314024e+07,2.723995e+07,3.708424e+07
3,4.161091,18.698500,1.429657,99.963142,-1.999374,1.097938,23.952309,22.423880,3,15315,4.399840,2.281000,10.036038,2.280160e+02,1.003234e+03,1.459739,0.022075,1.435094,0.404728,1.058550,1.611460,-0.055081,2.848270,4.175426,0.020366,4.190731,0.206134,4.383953,0.817567,4.948717,1.446369,-2.000713,0.000859,-2.144903,2.441124,-4.427260,9.735691,-11.162467,17.215444,1.096752,0.002053,1.554303,7.736091,8.787484,30.849207,30.129307,54.546539,18.647156,0.071237,18.619028,0.105450,18.622858,0.148071,18.676735,0.231652,99.986331,0.019770,99.988018,0.019802,99.989535,0.019499,99.991775,0.019771,22.179450,0.250171,22.108145,0.285875,22.069718,0.291368,22.025380,0.298020,4.423295,0.019468,4.443268,0.292097,4.717482,1.161752,5.520256,2.054425,2.281604,0.001850,2.758945,8.075307,10.309118,32.202445,32.586939,56.939845,10.092206,0.047021,14.610455,76.387926,86.027617,304.670292,296.787609,538.765513,228.129207,0.197492,275.866702,807.525020,1030.884573,3220.238461,3258.682097,5694.009597,1.009083e+03,4.698131e+00,1.460920e+03,7.638734e+03,8.602626e+03,3.046695e+04,2.967875e+04,5.387674e+04
4,31.666536,18.903755,-126.625763,5845.617676,-192.004272,59.908649,87.561798,24.750105,27,28260,130.525298,201.133505,26253.010664,1.175750e+06,1.534651e+08,-130.122055,0.929413,-128.370815,13.418089,-118.273399,30.743269,-103.965698,39.373032,14.397550,4.438759,14.350271,6.521398,19.936673,17.727458,32.271721,28.677551,-209.533592,4.582309,-207.309782,27.227739,-185.846641,65.408770,-149.224719,87.022637,117.416795,14.938704,120.347418,9.024879,118.131604,12.146928,113.702421,19.434820,18.960339,0.246563,18.949358,0.254978,18.903084,0.275640,18.841083,0.287351,3469.851607,598.392400,3299.024399,440.196107,3046.565181,748.983194,2751.571513,1001.703891,24.639606,0.314070,24.742905,0.348683,24.699020,0.409150,24.561257,0.572844,130.994393,0.181795,129.684146,9.461814,123.198767,21.618163,115.657477,29.088211,240.474506,10.340699,240.384354,22.334842,224.210830,51.468093,196.358452,67.748393,31502.565466,1389.886508,31375.607963,3777.854489,28655.638825,8643.222539,24295.661306,11086.522440,828258.861669,87442.688981,797998.151743,110646.692661,718091.399792,239906.664094,597987.013817,316236.474405,1.084828e+08,1.126954e+07,1.044257e+08,1.538144e+07,9.327697e+07,3.358789e+07,7.679217e+07,4.394293e+07

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,profile_id,category,0.0,0.0,69.0,"20, 6, 65, 66, 18, 13, 27, 56, 4, 58"
1,u_q,float64,0.0,0.0,1237646.0,"131.8004, 8.1426, 131.7986, 132.0084, 131.7984, 131.7957, 131.8011, 8.1419, 119.5759, 131.7592"
2,coolant,float64,0.0,0.0,1082713.0,"56.1055, 35.7982, 81.4896, 61.222, 81.4896, 61.222, 15.4908, 30.7213, 35.7982, 15.4908"
3,u_d,float64,0.0,0.0,1261982.0,"-129.9406, -7.6112, -128.0483, -11.633, -7.6103, -130.0341, -7.6103, -130.0807, -11.6377, -7.6161"
4,motor_speed,float64,0.0,0.0,754389.0,"4999.9463, 4999.9458, 4499.9561, 4999.9453, 4999.9478, 4999.9468, 4499.957, 4999.9473, 4999.9443, 4999.9448"
5,i_d,float64,0.0,0.0,1019349.0,"-43.5117, -43.5118, -43.5116, -43.5116, -43.5117, -43.5116, -43.5114, -43.5118, -43.5121, -43.5121"
6,i_q,float64,0.0,0.0,996985.0,"132.6176, 132.6176, 132.6176, 132.6174, 132.6177, 132.6177, 132.6179, 132.6176, 132.6176, 132.6176"
7,permanent_magnet_temperature,float64,0.0,0.0,1282892.0,"44.1124, 38.4401, 82.8469, 31.8331, 40.0473, 41.5088, 88.7856, 72.4434, 28.4124, 36.8684"
8,ambient,float64,0.0,0.0,1164004.0,"19.8506, 26.3845, 26.3845, 26.3845, 19.8506, 26.3845, 19.8506, 19.8506, 19.8506, 26.3845"
9,u_s,float64,0.0,0.0,1296314.0,"131.2528, 130.9348, 17.9342, 131.2762, 17.9544, 12.1076, 0.9601, 1.1741, 132.1215, 129.9521"
10,i_s,float64,0.0,0.0,1266302.0,"139.5734, 139.5733, 271.8303, 204.6696, 204.6697, 139.5742, 204.6694, 139.5736, 185.1548, 204.6694"
11,S_el,float64,0.0,0.0,1296316.0,"29038.9631, 29574.1346, 2503.1412, 10356.3869, 2505.9663, 27.5926, 2.1898, 2.6796, 23152.5446, 19334.3208"
12,i_s_omega,float64,0.0,0.0,1296289.0,"309948.0337, 97465.0454, 69784.3369, 855130.4053, 18741.1241, 19263.2664, 206888.1105, 333309.7273, 76986.9836, 129090.6256"
13,S_el_omega,float64,0.0,0.0,1296316.0,"130674015.3054, 118295704.0939, 625734.9198, 35422232.3467, 626540.9504, 6898.0318, -0.0085, 0.0046, 57880717.1967, 96670471.3312"
14,u_d_ewma_500,float64,0.0,0.0,1296316.0,"-124.1393, -62.0223, -11.6032, -57.1015, -11.6318, 0.7632, -0.6936, -0.5939, 112.9152, -95.4162"
15,u_d_ewms_500,float64,0.0,0.0,1296316.0,"28.8965, 31.733, 0.004, 71.3245, 0.0039, 0.018, 1.0485, 0.0523, 6.5805, 1.8612"
16,u_d_ewma_2000,float64,0.0,0.0,1296316.0,"-53.8502, -39.3124, -11.589, -10.4037, -11.6341, 0.6568, 0.1357, -0.6208, 85.5376, -81.7604"
17,u_d_ewms_2000,float64,0.0,0.0,1296316.0,"92.2574, 28.7675, 0.3869, 85.5044, 0.008, 1.2701, 23.3788, 3.3915, 49.303, 32.7259"
18,u_d_ewma_4000,float64,0.0,0.0,1296316.0,"-7.8137, -33.2197, -11.2096, -7.4978, -11.6276, -0.4664, 0.58, -1.1258, 50.9654, -59.6937"
19,u_d_ewms_4000,float64,0.0,0.0,1296316.0,"98.5749, 32.344, 2.1547, 82.6633, 0.2814, 3.7773, 38.4266, 15.8558, 67.6988, 48.5987"
20,u_d_ewma_8000,float64,0.0,0.0,1296316.0,"21.0693, -30.1011, -9.4034, -8.8174, -11.3476, -3.1327, 0.428, -2.627, 8.1637, -37.4499"
21,u_d_ewms_8000,float64,0.0,0.0,1296316.0,"93.1825, 36.1173, 4.794, 80.784, 1.8473, 5.7994, 46.1589, 31.0129, 79.4602, 57.2514"
22,u_q_ewma_500,float64,0.0,0.0,1296316.0,"18.2462, 103.4254, 13.6768, 68.6158, 13.6754, 12.0812, -0.6411, -0.9074, 67.7291, 88.2207"
23,u_q_ewms_500,float64,0.0,0.0,1296316.0,"5.9246, 38.0353, 0.0016, 36.6315, 0.0018, 0.0184, 1.35, 0.0224, 4.0629, 1.6973"
24,u_q_ewma_2000,float64,0.0,0.0,1296316.0,"26.7308, 85.9375, 13.6665, 70.8202, 13.6777, 12.091, 7.5673, -0.7396, 51.7797, 76.7692"
25,u_q_ewms_2000,float64,0.0,0.0,1296316.0,"34.3476, 48.6245, 0.4613, 34.3759, 0.0084, 0.1656, 26.5127, 3.7489, 29.5269, 30.3505"
26,u_q_ewma_4000,float64,0.0,0.0,1296316.0,"40.9005, 63.8884, 13.2246, 72.3838, 13.6723, 12.2403, 21.0493, 2.267, 40.3368, 56.6029"
27,u_q_ewms_4000,float64,0.0,0.0,1296316.0,"43.8676, 52.4685, 2.5722, 34.2307, 0.3346, 0.4869, 39.8175, 16.7134, 35.5729, 45.3646"
28,u_q_ewma_8000,float64,0.0,0.0,1296316.0,"49.8505, 46.3225, 11.0781, 72.4737, 13.3474, 12.5505, 30.1388, 10.7498, 42.9082, 35.9376"
29,u_q_ewms_8000,float64,0.0,0.0,1296316.0,"43.6988, 50.3419, 5.7289, 34.6756, 2.1992, 1.0223, 45.1536, 30.7201, 39.1421, 53.6397"
30,i_d_ewma_500,float64,0.0,0.0,1296316.0,"-197.1511, -98.7386, -43.5119, -114.0497, -43.512, -2.001, -2.0182, -2.0007, -91.2499, -138.8309"
31,i_d_ewms_500,float64,0.0,0.0,1296316.0,"39.0717, 49.1976, 0.0007, 46.4821, 0.0006, 0.0047, 1.4068, 0.0007, 5.2658, 2.4668"
32,i_d_ewma_2000,float64,0.0,0.0,1296316.0,"-139.2733, -60.0995, -43.4712, -99.6759, -43.5119, -2.4394, -9.8254, -2.1708, -70.5929, -121.8268"
33,i_d_ewms_2000,float64,0.0,0.0,1296316.0,"95.378, 46.9799, 1.2979, 54.0671, 0.0213, 4.2427, 27.6803, 4.4993, 38.4135, 44.0132"
34,i_d_ewma_4000,float64,0.0,0.0,1296316.0,"-112.5729, -45.8313, -42.2126, -93.1007, -43.4905, -6.2681, -23.2627, -5.6014, -57.158, -92.5324"
35,i_d_ewms_4000,float64,0.0,0.0,1296316.0,"96.3335, 47.5106, 7.2303, 54.7898, 0.941, 12.6029, 43.4034, 20.5836, 48.3387, 65.5846"
36,i_d_ewma_8000,float64,0.0,0.0,1296316.0,"-95.8183, -36.7094, -36.167, -90.1794, -42.5703, -15.2013, -32.7622, -15.6434, -64.4254, -62.6705"
37,i_d_ewms_8000,float64,0.0,0.0,1296316.0,"86.4656, 47.532, 16.092, 54.5367, 6.1818, 19.3272, 50.392, 38.5416, 57.1934, 77.414"
38,i_q_ewma_500,float64,0.0,0.0,1296316.0,"81.9544, 44.03, 132.6179, 98.542, 132.6176, 1.0964, 1.0954, 1.0973, -148.9025, 53.3411"
39,i_q_ewms_500,float64,0.0,0.0,1296316.0,"19.6892, 26.226, 0.0005, 107.7086, 0.0004, 0.0147, 1.0661, 0.0015, 8.7951, 0.1952"
40,i_q_ewma_2000,float64,0.0,0.0,1296316.0,"30.2296, 33.2548, 132.4892, 38.545, 132.6177, 2.4879, 1.5584, 1.1237, -112.6727, 54.5507"
41,i_q_ewms_2000,float64,0.0,0.0,1296316.0,"73.43, 24.9091, 4.1102, 121.8711, 0.0676, 13.4455, 29.491, 4.6721, 65.0055, 3.2386"
42,i_q_ewma_4000,float64,0.0,0.0,1296316.0,"-11.2788, 36.8018, 128.5032, 29.9139, 132.5502, 14.6214, 1.4959, 1.476, -71.5504, 56.6664"
43,i_q_ewms_4000,float64,0.0,0.0,1296316.0,"89.5364, 42.1287, 22.9002, 117.4356, 2.9804, 39.934, 48.2744, 22.0392, 80.0845, 4.7944"
44,i_q_ewma_8000,float64,0.0,0.0,1296316.0,"-41.2644, 40.3779, 109.3548, 25.9931, 129.6357, 42.9266, 1.1289, 2.0723, -29.6858, 58.8216"
45,i_q_ewms_8000,float64,0.0,0.0,1296316.0,"92.1658, 53.7352, 50.971, 114.4955, 19.5805, 61.2363, 58.7166, 43.3864, 80.9338, 5.6416"
46,coolant_ewma_500,float64,0.0,0.0,1296290.0,"35.7982, 19.0221, 85.7017, 76.9609, 18.9689, 54.9609, 28.979, 19.2268, 32.6329, 40.9136"
47,coolant_ewms_500,float64,0.0,0.0,1296290.0,"0.0, 0.2389, 0.4357, 9.3701, 0.2595, 0.0867, 0.1923, 0.2462, 0.3207, 0.0559"
48,coolant_ewma_2000,float64,0.0,0.0,1296290.0,"35.7982, 19.0258, 81.0482, 57.8157, 18.8412, 54.891, 31.3669, 18.9566, 32.7489, 41.68"
49,coolant_ewms_2000,float64,0.0,0.0,1296290.0,"0.0, 0.2628, 12.7944, 20.1176, 0.244, 1.2872, 9.2046, 0.3597, 0.3118, 3.5235"
50,coolant_ewma_4000,float64,0.0,0.0,1296290.0,"35.7982, 18.9138, 71.7407, 48.7629, 18.7729, 54.8748, 39.3856, 18.8585, 32.8588, 43.1001"
51,coolant_ewms_4000,float64,0.0,0.0,1296290.0,"0.0, 0.4971, 19.5792, 18.9154, 0.2425, 5.4862, 18.4675, 0.3483, 0.314, 6.3829"
52,coolant_ewma_8000,float64,0.0,0.0,1296290.0,"35.7982, 18.5663, 62.505, 42.865, 18.7287, 54.9441, 50.7147, 18.9088, 32.9676, 42.5904"
53,coolant_ewms_8000,float64,0.0,0.0,1296290.0,"0.0, 0.8445, 20.9532, 16.723, 0.2413, 11.4904, 23.5528, 0.5543, 0.3118, 8.3232"
54,motor_speed_ewma_500,float64,0.0,0.0,1296315.0,"4334.3505, 3961.8344, 249.9975, 2829.5237, 249.9981, 249.9979, 0.7393, -0.0002, 2491.2374, 4998.0411"
55,motor_speed_ewms_500,float64,0.0,0.0,1296316.0,"828.8265, 338.4751, 0.0171, 1285.7286, 0.019, 0.0135, 56.1218, 0.0124, 147.0653, 97.1249"
56,motor_speed_ewma_2000,float64,0.0,0.0,1296316.0,"3255.7147, 2874.4279, 249.7531, 2853.0101, 249.9975, 249.9976, 315.2525, 6.195, 1917.988, 4301.459"
57,motor_speed_ewms_2000,float64,0.0,0.0,1296316.0,"1746.5075, 1623.7552, 7.8046, 1332.8416, 0.1294, 0.0126, 1064.7603, 153.1071, 1085.3352, 1747.5761"
58,motor_speed_ewma_4000,float64,0.0,0.0,1296315.0,"2889.6698, 2079.3142, 242.187, 2840.3639, 249.8692, 249.9958, 848.9187, 128.0159, 1626.458, 3131.1638"
59,motor_speed_ewms_4000,float64,0.0,0.0,1296316.0,"1590.7688, 1751.0895, 43.5073, 1373.599, 5.6623, 0.6589, 1626.5684, 684.3354, 1521.0608, 2601.9391"
60,motor_speed_ewma_8000,float64,0.0,0.0,1296316.0,"2654.7513, 1478.8786, 205.81, 2827.2378, 244.3331, 249.3386, 1216.1714, 477.2717, 2079.1975, 1943.1962"
61,motor_speed_ewms_8000,float64,0.0,0.0,1296316.0,"1494.4267, 1646.7947, 96.8693, 1424.6614, 37.2092, 12.816, 1845.4524, 1259.378, 2050.6707, 3069.589"
62,ambient_ewma_500,float64,0.0,0.0,1296316.0,"26.2036, 23.9367, 22.7118, 26.5551, 22.8858, 22.9411, 24.6779, 25.7968, 25.6926, 23.1026"
63,ambient_ewms_500,float64,0.0,0.0,1296316.0,"0.1982, 0.3249, 0.3462, 0.3195, 0.2821, 0.2979, 0.0966, 0.0141, 0.2175, 0.2602"
64,ambient_ewma_2000,float64,0.0,0.0,1296316.0,"26.1102, 23.8873, 22.7966, 26.4883, 22.9558, 22.9569, 24.5732, 25.7953, 25.7637, 23.1"
65,ambient_ewms_2000,float64,0.0,0.0,1296316.0,"0.2542, 0.3585, 0.3256, 0.3272, 0.2764, 0.2723, 0.184, 0.0371, 0.3187, 0.2604"
66,ambient_ewma_4000,float64,0.0,0.0,1296316.0,"26.0422, 23.8649, 22.8495, 26.4777, 22.9391, 22.975, 24.4522, 25.7962, 25.9474, 23.1314"
67,ambient_ewms_4000,float64,0.0,0.0,1296316.0,"0.2906, 0.3643, 0.3065, 0.3006, 0.2954, 0.2655, 0.2803, 0.0845, 0.5355, 0.2378"
68,ambient_ewma_8000,float64,0.0,0.0,1296316.0,"26.0148, 23.8308, 22.8567, 26.4542, 22.9168, 22.9911, 24.2467, 25.7662, 26.1741, 23.1574"
69,ambient_ewms_8000,float64,0.0,0.0,1296316.0,"0.4142, 0.3545, 0.2853, 0.259, 0.3033, 0.2619, 0.3997, 0.173, 0.7876, 0.2195"
70,u_s_ewma_500,float64,0.0,0.0,1296316.0,"126.6713, 130.0186, 17.9357, 117.2556, 17.9531, 12.1052, 0.9852, 1.0854, 131.6745, 129.9514"
71,u_s_ewms_500,float64,0.0,0.0,1296316.0,"23.8198, 9.3636, 0.0021, 25.2448, 0.0028, 0.0187, 1.6862, 0.0351, 7.6627, 2.4693"
72,u_s_ewma_2000,float64,0.0,0.0,1296316.0,"103.4871, 98.4574, 17.9213, 113.1558, 17.9564, 12.1617, 11.8424, 1.2903, 101.1326, 112.1755"
73,u_s_ewms_2000,float64,0.0,0.0,1296316.0,"50.916, 49.2787, 0.5183, 28.4315, 0.0097, 0.5977, 34.1539, 4.9823, 55.4303, 44.5754"
74,u_s_ewma_4000,float64,0.0,0.0,1296316.0,"104.8496, 76.5088, 17.42, 111.3529, 17.9495, 12.7043, 30.0725, 5.5845, 77.1499, 82.3052"
75,u_s_ewms_4000,float64,0.0,0.0,1296316.0,"48.7803, 55.9464, 2.8887, 29.9892, 0.3765, 1.7737, 50.9994, 22.4935, 64.1916, 66.4211"
76,u_s_ewma_8000,float64,0.0,0.0,1296316.0,"105.6477, 59.7395, 15.0048, 109.6613, 17.5799, 13.9355, 42.7022, 18.0542, 75.0413, 51.9597"
77,u_s_ewms_8000,float64,0.0,0.0,1296316.0,"48.5704, 57.4975, 6.431, 32.09, 2.473, 2.7942, 56.9727, 41.2477, 64.2037, 78.3946"
78,i_s_ewma_500,float64,0.0,0.0,1296316.0,"213.7826, 108.3706, 139.5736, 176.4768, 139.5733, 2.2817, 2.3044, 2.2818, 174.646, 148.7367"
79,i_s_ewms_500,float64,0.0,0.0,1296316.0,"42.3808, 55.2438, 0.0004, 72.9291, 0.0004, 0.0153, 1.7546, 0.0011, 10.1165, 1.6787"
80,i_s_ewma_2000,float64,0.0,0.0,1296316.0,"154.4778, 71.9404, 139.4392, 154.8493, 139.5734, 3.7335, 14.2166, 2.541, 134.0982, 137.3009"
81,i_s_ewms_2000,float64,0.0,0.0,1296316.0,"104.5689, 48.6801, 4.2909, 72.1958, 0.0705, 14.0351, 39.15, 6.449, 73.4664, 29.8874"
82,i_s_ewma_4000,float64,0.0,0.0,1296316.0,"135.5644, 63.7228, 135.278, 145.8597, 139.5029, 16.3988, 34.0644, 7.7926, 100.4857, 117.4282"
83,i_s_ewms_4000,float64,0.0,0.0,1296316.0,"108.2482, 58.5294, 23.9067, 71.2576, 3.1114, 41.6859, 59.9756, 29.7024, 83.8979, 44.5712"
84,i_s_ewma_8000,float64,0.0,0.0,1296316.0,"128.3032, 59.2298, 115.2881, 141.8348, 136.4604, 45.9456, 47.6951, 23.1927, 92.3099, 97.1365"
85,i_s_ewms_8000,float64,0.0,0.0,1296316.0,"101.9427, 67.8255, 53.2107, 69.0565, 20.4409, 63.9234, 69.1047, 55.4799, 79.5719, 52.634"
86,S_el_ewma_500,float64,0.0,0.0,1296316.0,"28068.4858, 14143.8922, 2503.3435, 19631.3078, 2505.7732, 27.6202, 4.9811, 2.4768, 23073.6695, 19332.5853"
87,S_el_ewms_500,float64,0.0,0.0,1296316.0,"5625.8877, 7225.8734, 0.2915, 7414.2744, 0.3851, 0.2793, 221.0637, 0.0999, 1363.37, 374.3188"
88,S_el_ewma_2000,float64,0.0,0.0,1296316.0,"20220.9707, 8802.716, 2501.1529, 17274.3798, 2506.236, 53.7783, 1369.6208, 30.9834, 17628.5611, 16705.3468"
89,S_el_ewms_2000,float64,0.0,0.0,1296316.0,"13839.6449, 6743.5529, 78.1771, 8443.9618, 1.4413, 253.0922, 4739.5895, 738.4499, 9845.828, 6729.387"
90,S_el_ewma_4000,float64,0.0,0.0,1296316.0,"17755.4708, 7306.3482, 2425.5078, 16226.6077, 2505.1737, 282.2149, 3695.8024, 617.4126, 13116.6328, 12214.3515"
91,S_el_ewms_4000,float64,0.0,0.0,1296316.0,"14311.3023, 7428.2072, 435.5007, 8698.7498, 56.7491, 751.9491, 7359.4224, 3433.9477, 11226.2399, 10030.1835"
92,S_el_ewma_8000,float64,0.0,0.0,1296316.0,"16818.4681, 6485.8146, 2061.3975, 15696.7016, 2449.4777, 815.3152, 5325.7264, 2342.5858, 11986.615, 7640.6996"
93,S_el_ewms_8000,float64,0.0,0.0,1296316.0,"13491.5916, 8125.3629, 969.2314, 8810.3942, 372.703, 1153.4707, 8512.1084, 6440.8462, 10627.9889, 11840.469"
94,i_s_omega_ewma_500,float64,0.0,0.0,1296316.0,"961209.206, 432148.6909, 34893.0463, 439868.0265, 34893.061, 570.4125, 89.383, -0.0005, 436566.9474, 743552.3743"
95,i_s_omega_ewms_500,float64,0.0,0.0,1296316.0,"192669.0364, 223003.9708, 2.3725, 202010.8622, 2.6781, 3.8316, 7300.3813, 1.6429, 25814.4458, 14586.8952"
96,i_s_omega_ewma_2000,float64,0.0,0.0,1296316.0,"666665.8923, 261042.7176, 34858.8268, 415879.1438, 34893.0159, 933.358, 38744.3459, 790.512, 335374.1284, 641775.4193"
97,i_s_omega_ewms_2000,float64,0.0,0.0,1296316.0,"461701.7248, 205703.2231, 1090.6436, 233896.0069, 18.086, 3508.726, 140708.7787, 21159.324, 188525.5338, 261148.9918"
98,i_s_omega_ewma_4000,float64,0.0,0.0,1296316.0,"528396.0974, 196287.0296, 33801.1406, 398343.0558, 34875.0786, 4099.6396, 105648.9479, 16766.2935, 274698.7107, 467656.1306"
99,i_s_omega_ewms_4000,float64,0.0,0.0,1296316.0,"455148.6319, 202350.164, 6075.9741, 243900.5881, 790.7833, 10421.3587, 221059.1856, 96617.7962, 245755.0484, 389030.2109"
100,i_s_omega_ewma_8000,float64,0.0,0.0,1296316.0,"448014.7374, 154748.2199, 28720.6356, 390494.0464, 34101.7895, 11484.7699, 152361.5887, 63443.7311, 325154.8477, 290388.0779"
101,i_s_omega_ewms_8000,float64,0.0,0.0,1296316.0,"402097.7811, 197730.9648, 13523.059, 248829.4727, 5194.9429, 15981.7357, 255662.753, 180794.6954, 305804.8351, 459111.2078"
102,S_el_omega_ewma_500,float64,0.0,0.0,1296316.0,"126249449.9626, 56506959.3419, 625829.4883, 54227623.6741, 626438.4387, 6904.9881, 11389.0363, 0.0, 57682078.6568, 96661215.8232"
103,S_el_omega_ewms_500,float64,0.0,0.0,1296316.0,"25335798.8807, 29023900.2206, 77.0705, 29345641.1429, 103.4759, 69.8323, 942327.1843, 203.0081, 3420396.4921, 1897022.0366"
104,S_el_omega_ewma_2000,float64,0.0,0.0,1296316.0,"87535747.8578, 33597354.8544, 625280.1285, 51339983.0469, 626552.9741, 13444.436, 4817234.5714, 95788.0833, 44290971.4021, 83388724.4471"
105,S_el_omega_ewms_2000,float64,0.0,0.0,1296316.0,"60691384.4025, 27464312.724, 19570.8298, 32730224.8412, 361.7439, 63272.3653, 18063434.264, 2661054.0132, 24910838.4652, 33947299.2605"
106,S_el_omega_ewma_4000,float64,0.0,0.0,1296316.0,"69409527.7245, 24593209.4831, 606343.0158, 49060024.4355, 626286.7307, 70552.9579, 13161133.4573, 2044137.1028, 36194858.5508, 60751021.2125"
107,S_el_omega_ewms_4000,float64,0.0,0.0,1296316.0,"59822054.1174, 26848997.9303, 109014.5769, 33627861.1306, 14205.4999, 187985.2848, 28423630.1295, 12192383.3129, 32322013.6053, 50552831.7112"
108,S_el_omega_ewma_8000,float64,0.0,0.0,1296316.0,"58887417.9948, 18832190.0316, 515199.4136, 48040905.7583, 612344.7087, 203824.5151, 19017990.6155, 7758406.4049, 42655642.0174, 37717752.7224"
109,S_el_omega_ewms_8000,float64,0.0,0.0,1296316.0,"52838647.0784, 25819558.8624, 242607.4505, 34120307.4249, 93291.7741, 288366.0378, 32937764.2884, 22914260.2277, 40022650.8792, 59648055.5671"
110,profile_time_index,int64,0.0,0.0,43471.0,"2720, 9822, 701, 1808, 4858, 4946, 1902, 696, 9504, 3245"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
u_q,129632.0,5.423378e+01,4.423986e+01,-2.491796e+01,1.322492e+02
coolant,129632.0,3.641024e+01,2.186564e+01,1.199671e+01,9.373608e+01
u_d,129632.0,-2.466753e+01,6.317037e+01,-1.314386e+02,1.313946e+02
motor_speed,129632.0,2.197430e+03,1.856846e+03,-2.426863e+02,6.000015e+03
i_d,129632.0,-6.824552e+01,6.485284e+01,-2.776520e+02,6.458024e-03
i_q,129632.0,3.661469e+01,9.175560e+01,-2.929667e+02,3.017075e+02
permanent_magnet_temperature,129632.0,5.910639e+01,1.871198e+01,2.202800e+01,1.135573e+02
ambient,129632.0,2.460547e+01,1.907550e+00,9.934283e+00,3.012359e+01
profile_time_index,129632.0,1.230782e+04,8.873765e+03,5.010000e+02,4.396600e+04
u_s,129632.0,8.151762e+01,5.340697e+01,3.604401e-06,1.338712e+02
i_s,129632.0,1.066916e+02,8.508772e+01,9.746108e-05,3.614991e+02
S_el,129632.0,1.090680e+04,1.031424e+04,5.694256e-09,4.761210e+04
i_s_omega,129632.0,2.959127e+05,3.196842e+05,-1.745850e+03,1.213853e+06
S_el_omega,129632.0,3.677494e+07,4.247879e+07,-1.790239e+04,1.577617e+08
u_d_ewma_500,129632.0,-2.513035e+01,5.314399e+01,-1.311243e+02,1.260344e+02
u_d_ewms_500,129632.0,2.225304e+01,2.625097e+01,2.183671e-03,1.078123e+02
u_d_ewma_2000,129632.0,-2.516987e+01,4.555793e+01,-1.304844e+02,1.162623e+02
u_d_ewms_2000,129632.0,3.421112e+01,2.680631e+01,2.760228e-03,9.797548e+01
u_d_ewma_4000,129632.0,-2.452055e+01,4.061265e+01,-1.291518e+02,1.074005e+02
u_d_ewms_4000,129632.0,4.042506e+01,2.460139e+01,1.735012e-02,1.083499e+02
u_d_ewma_8000,129632.0,-2.281868e+01,3.453555e+01,-1.266740e+02,7.716784e+01
u_d_ewms_8000,129632.0,4.519033e+01,2.217226e+01,3.549792e-01,1.138654e+02
u_q_ewma_500,129632.0,5.418895e+01,3.846950e+01,-9.168612e+00,1.320073e+02
u_q_ewms_500,129632.0,1.457118e+01,1.603414e+01,1.123186e-03,6.302919e+01
u_q_ewma_2000,129632.0,5.280813e+01,3.383333e+01,-1.689499e+00,1.319642e+02
u_q_ewms_2000,129632.0,2.308646e+01,1.721901e+01,1.604808e-03,7.858845e+01
u_q_ewma_4000,129632.0,5.029335e+01,3.065381e+01,-8.191644e-01,1.308055e+02
u_q_ewms_4000,129632.0,2.823082e+01,1.729701e+01,1.789728e-02,8.458823e+01
u_q_ewma_8000,129632.0,4.536909e+01,2.728508e+01,2.186643e-01,1.299083e+02
u_q_ewms_8000,129632.0,3.328055e+01,1.704365e+01,2.500995e-01,8.757296e+01
i_d_ewma_500,129632.0,-6.871006e+01,5.677009e+01,-2.535252e+02,3.656231e-05
i_d_ewms_500,129632.0,2.148967e+01,2.335210e+01,2.226429e-04,1.182138e+02
i_d_ewma_2000,129632.0,-6.774463e+01,4.890649e+01,-2.199892e+02,-1.986772e+00
i_d_ewms_2000,129632.0,3.564477e+01,2.487622e+01,7.579667e-04,1.386644e+02
i_d_ewma_4000,129632.0,-6.533752e+01,4.326956e+01,-2.164606e+02,-2.008933e+00
i_d_ewms_4000,129632.0,4.417580e+01,2.392320e+01,1.820348e-01,1.479852e+02
i_d_ewma_8000,129632.0,-6.002253e+01,3.706679e+01,-1.980443e+02,-2.636158e+00
i_d_ewms_8000,129632.0,5.194805e+01,2.293449e+01,2.700778e-01,1.530298e+02
i_q_ewma_500,129632.0,3.726664e+01,7.927105e+01,-2.474925e+02,2.975120e+02
i_q_ewms_500,129632.0,2.974220e+01,3.625129e+01,1.749426e-04,2.017574e+02
i_q_ewma_2000,129632.0,3.735153e+01,6.809056e+01,-2.066765e+02,2.422739e+02
i_q_ewms_2000,129632.0,4.814634e+01,3.853959e+01,1.047997e-03,1.833440e+02
i_q_ewma_4000,129632.0,3.657889e+01,6.089157e+01,-1.750672e+02,2.363998e+02
i_q_ewms_4000,129632.0,5.834714e+01,3.508748e+01,1.193090e-01,1.958996e+02
i_q_ewma_8000,129632.0,3.454869e+01,5.222521e+01,-1.295165e+02,2.042287e+02
i_q_ewms_8000,129632.0,6.692364e+01,3.037857e+01,1.201035e-01,2.019889e+02
coolant_ewma_500,129632.0,3.631373e+01,2.149121e+01,1.545887e+01,9.146757e+01
coolant_ewms_500,129632.0,1.516920e+00,3.157200e+00,0.000000e+00,2.904104e+01
coolant_ewma_2000,129632.0,3.603873e+01,2.024676e+01,1.620763e+01,9.108626e+01
coolant_ewms_2000,129632.0,4.258661e+00,6.173348e+00,0.000000e+00,3.439036e+01
coolant_ewma_4000,129632.0,3.572700e+01,1.915751e+01,1.626249e+01,9.100654e+01
coolant_ewms_4000,129632.0,5.978753e+00,7.621267e+00,0.000000e+00,3.426347e+01
coolant_ewma_8000,129632.0,3.508938e+01,1.796715e+01,1.600300e+01,9.097245e+01
coolant_ewms_8000,129632.0,7.421054e+00,8.677571e+00,0.000000e+00,3.297827e+01
motor_speed_ewma_500,129632.0,2.200594e+03,1.681559e+03,-5.472291e-04,5.999942e+03
motor_speed_ewms_500,129632.0,4.931493e+02,6.141112e+02,1.274772e-03,2.921089e+03
motor_speed_ewma_2000,129632.0,2.154792e+03,1.493916e+03,7.675242e-06,5.999749e+03
motor_speed_ewms_2000,129632.0,8.582198e+02,7.359673e+02,1.836563e-03,3.634298e+03
motor_speed_ewma_4000,129632.0,2.063416e+03,1.366285e+03,3.217865e-01,5.966406e+03
motor_speed_ewms_4000,129632.0,1.085904e+03,7.675151e+02,3.492292e-03,3.867006e+03
motor_speed_ewma_8000,129632.0,1.876023e+03,1.221603e+03,6.919864e+00,5.551403e+03
motor_speed_ewms_8000,129632.0,1.325125e+03,7.823589e+02,1.221431e-02,3.978039e+03
ambient_ewma_500,129632.0,2.458156e+01,1.890041e+00,1.883213e+01,2.955733e+01
ambient_ewms_500,129632.0,2.568510e-01,2.028722e-01,6.652610e-05,1.845438e+00
ambient_ewma_2000,129632.0,2.451436e+01,1.904413e+00,1.871047e+01,2.909602e+01
ambient_ewms_2000,129632.0,3.336746e-01,2.304140e-01,6.856036e-05,1.555023e+00
ambient_ewma_4000,129632.0,2.442918e+01,1.920607e+00,1.862281e+01,2.895371e+01
ambient_ewms_4000,129632.0,4.064997e-01,2.704490e-01,6.669650e-05,1.682427e+00
ambient_ewma_8000,129632.0,2.427777e+01,1.946341e+00,1.857367e+01,2.878879e+01
ambient_ewms_8000,129632.0,5.148074e-01,3.421668e-01,6.551648e-05,2.087672e+00
u_s_ewma_500,129632.0,8.169878e+01,4.824661e+01,6.546763e-01,1.320970e+02
u_s_ewms_500,129632.0,1.374470e+01,1.822332e+01,1.306539e-03,6.474639e+01
u_s_ewma_2000,129632.0,7.997350e+01,4.315150e+01,8.310912e-01,1.320194e+02
u_s_ewms_2000,129632.0,2.499693e+01,2.159584e+01,1.636653e-03,7.974839e+01
u_s_ewma_4000,129632.0,7.654833e+01,3.989442e+01,1.152317e+00,1.319957e+02
u_s_ewms_4000,129632.0,3.280216e+01,2.224093e+01,2.457587e-02,8.535784e+01
u_s_ewma_8000,129632.0,6.951761e+01,3.660398e+01,1.593552e+00,1.313674e+02
u_s_ewms_8000,129632.0,4.142728e+01,2.194371e+01,2.390056e-01,8.825099e+01
i_s_ewma_500,129632.0,1.074981e+02,7.360326e+01,1.877955e-03,3.395991e+02
i_s_ewms_500,129632.0,2.921845e+01,3.150365e+01,1.573707e-04,1.710236e+02
i_s_ewma_2000,129632.0,1.061793e+02,6.213845e+01,2.281522e+00,2.716616e+02
i_s_ewms_2000,129632.0,4.943890e+01,3.325749e+01,1.124390e-03,2.091600e+02
i_s_ewma_4000,129632.0,1.026454e+02,5.388152e+01,2.294063e+00,2.650734e+02
i_s_ewms_4000,129632.0,6.253471e+01,3.061201e+01,2.879287e-01,2.232534e+02
i_s_ewma_8000,129632.0,9.473390e+01,4.531666e+01,3.376838e+00,2.289972e+02
i_s_ewms_8000,129632.0,7.508203e+01,2.688279e+01,2.806888e-01,2.300347e+02
S_el_ewma_500,129632.0,1.097931e+04,8.938976e+03,5.671014e-03,3.943568e+04
S_el_ewms_500,129632.0,3.546354e+03,3.816687e+03,2.777620e-02,2.293505e+04
S_el_ewma_2000,129632.0,1.080248e+04,7.707259e+03,2.457780e+00,3.501543e+04
S_el_ewms_2000,129632.0,5.742416e+03,4.013179e+03,3.349321e-01,2.218890e+04
S_el_ewma_4000,129632.0,1.037717e+04,6.831480e+03,4.241100e+00,3.185602e+04
S_el_ewms_4000,129632.0,7.052539e+03,3.877422e+03,5.227938e+00,2.204957e+04
S_el_ewma_8000,129632.0,9.449979e+03,5.898042e+03,6.550725e+01,2.911407e+04
S_el_ewms_8000,129632.0,8.222245e+03,3.767506e+03,7.987330e+01,2.275522e+04
i_s_omega_ewma_500,129632.0,2.976523e+05,2.865996e+05,-1.248671e-03,1.186019e+06
i_s_omega_ewms_500,129632.0,9.607060e+04,1.070025e+05,4.534455e-03,5.769206e+05
i_s_omega_ewma_2000,129632.0,2.929687e+05,2.530373e+05,4.436123e-03,1.168124e+06
i_s_omega_ewms_2000,129632.0,1.596905e+05,1.199352e+05,3.393664e+00,6.798382e+05
i_s_omega_ewma_4000,129632.0,2.817259e+05,2.279300e+05,4.251517e+01,1.152085e+06
i_s_omega_ewms_4000,129632.0,1.972295e+05,1.226465e+05,4.691824e+01,7.301600e+05
i_s_omega_ewma_8000,129632.0,2.571120e+05,1.982620e+05,9.449469e+02,1.034981e+06
i_s_omega_ewms_8000,129632.0,2.309178e+05,1.280108e+05,9.756872e+02,7.542756e+05
S_el_omega_ewma_500,129632.0,3.699564e+07,3.811418e+07,-1.633461e-03,1.551536e+08
S_el_omega_ewms_500,129632.0,1.266480e+07,1.425513e+07,5.100539e-03,7.497790e+07
S_el_omega_ewma_2000,129632.0,3.640513e+07,3.367816e+07,5.553659e-01,1.524038e+08
S_el_omega_ewms_2000,129632.0,2.092054e+07,1.612327e+07,7.444455e+01,8.837436e+07
S_el_omega_ewma_4000,129632.0,3.499235e+07,3.037555e+07,1.297023e+03,1.499144e+08
S_el_omega_ewms_4000,129632.0,2.569945e+07,1.660805e+07,5.280341e+02,9.488254e+07
S_el_omega_ewma_8000,129632.0,3.189774e+07,2.643455e+07,9.050410e+03,1.348026e+08
S_el_omega_ewms_8000,129632.0,2.991689e+07,1.745658e+07,1.087575e+04,9.799866e+07

In [7]:
# Categorical Feature Statistics
cat_stats

                value  count   pct
column     rank
profile_id 1       20   4439  3.42
           2        6   3970  3.06
           3       65   3937  3.04
           4       66   3647  2.81
           5       18   3642  2.81

In [8]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,0.032,-0.589,350.138,0.121,log,1350022.6,2.968767e+09,exponential

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
    group_labels=task_mold.group_labels,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=1, n_splits=1, test_size=250000

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

# -- For Grouped Non-IID data
splits = curation_recommendations.get_recommended_grouped_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    group_on=task_mold.group_on,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
    group_labels=task_mold.group_labels,
    show_splits=True,
    target_on=task_mold.target_column_name,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using label-per-sample grouped splits.
Repeat 0, Fold 0:
            Train N: 968996, Test N: 327320
            Target Distribution:
            	Train target distribution: 62.405901049380915
            	Test target distribution: 49.361947978382396
            Group Distribution profile_id:
            	Train: 55
            	Test: 14

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to electric_motor_temperature_prediction/019d459a-334a-7077-812d-776a08a70ee2
019d459a-334a-7077-812d-776a08a70ee2
df2dd9a82429ad3ab0e89978ae49945abecf750f65c2699e3267042ea7b131b3