### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="asp_potassco_classification",
    dataset_year="2014",
    domain_str="technology & internet",
    # Data Source
    dataset_source="ASlib",
    original_dataset_source_download_link="https://github.com/coseal/aslib_data/tree/master/ASP-POTASSCO",
    download_description="""
wget https://raw.githubusercontent.com/coseal/aslib_data/refs/heads/master/ASP-POTASSCO/algorithm_runs.arff \
&& wget https://raw.githubusercontent.com/coseal/aslib_data/refs/heads/master/ASP-POTASSCO/feature_values.arff \
&& mkdir -p local-data-warehouse/asp_potassco_classification \
&& mv feature_values.arff algorithm_runs.arff local-data-warehouse/asp_potassco_classification/
""",
    # References
    academic_reference_bibtex="""@article{hoos2014claspfolio,
  title={claspfolio 2: Advances in algorithm selection for answer set programming},
  author={Hoos, Holger and Lindauer, Marius and Schaub, Torsten},
  journal={Theory and Practice of Logic Programming},
  volume={14},
  number={4-5},
  pages={569--585},
  year={2014},
  publisher={Cambridge University Press}
}
@article{bischl_aslib_2016,
	title = {{ASlib}: {A} {Benchmark} {Library} for {Algorithm} {Selection}},
	number = {237},
	journal = {Artificial Intelligence Journal (AIJ)},
	author = {Bischl, Bernd and Kerschke, Pascal and Kotthoff, Lars and Lindauer, Marius and Malitsky, Yuri and Fréchette, Alexandre and Hoos, Holger H. and Hutter, Frank and Leyton-Brown, Kevin and Tierney, Kevin and Vanschoren, Joaquin},
	year = {2016},
	pages = {41--58}
}
""",
    academic_reference_bibtex_key="hoos2014claspfolio,bischl_aslib_2016",
    license="GPLv3",
    data_tags=["Non-IID", "Grouped"],
    curation_comments="""
We get the data from ASlib and merge them into one file.

- We treat it as a multiclass classification task to solve the algorithm selection task as in the OpenML version (https://openml.org/d/41705).
- We drop all cases where no algorithm was able to finish before the timeout as these are essentially random labels.
- We resole the instance ID to a task ID by mapping the instance ID back to the source task based on their naming convention. From our understanding, the data contains multiple instance from the same solver task, differing only in seed or task configurations. We want to avoid having samples from the same task in both train and test set, as this would leak what algorithms are best for this task, and since in real-world you might not have samples from your new task. Thus, we treat the data as a grouped task, where we aim to generalize the predicting the best algorithm to new tasks across a set of instances of this task.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="algorithm",
    problem_type="multiclass_classification",
    objective_metric_name="log_loss", # or RMSE on runtime, or PAR10?
    # For classification
    stratify_on="algorithm",
    # For grouped data
    group_on="task_id",
    group_labels="per_sample",
)

## Preprocessing

In [2]:
import arff
import pandas as pd
import uuid
import numpy as np


def load_arff(path) -> pd.DataFrame:
    with open(path, encoding="utf-8") as f:
        data = arff.load(f)
    df = pd.DataFrame(data["data"], columns=[a[0] for a in data["attributes"]])
    return df


df_features = load_arff(dataset_mold.path / "feature_values.arff").drop(columns=["repetition"])
df_algo_runs = load_arff(dataset_mold.path / "algorithm_runs.arff")

# Only keep instances for which we have meaningful labels
df_algo_runs = df_algo_runs[df_algo_runs["runstatus"] == "ok"]
# Reduce to best algorithm per instance
df_algo_runs = df_algo_runs.loc[
    df_algo_runs.groupby('instance_id')['runtime'].idxmin(),
    ['instance_id', 'algorithm']
].reset_index(drop=True)

# Merge
df = df_algo_runs.merge(df_features, on="instance_id", how="left")
print("Merged data shape:", df.shape)


# Map instance ID to group ID
df["task_id"]  = df["instance_id"].str.rsplit("/", n=1).str[0]
# map it to a uuid
mapping = {val: uuid.uuid4().hex[:12] for val in df["task_id"].unique()}
df["task_id"] = df["task_id"].map(mapping)
df = df.drop(columns=[
    "instance_id",
    # Duplicated columns
    "Frac_Removed_Nogood-1",
    "Frac_Removed_Nogood-2",
])

as_cat_type = ["task_id", "algorithm"]
df[as_cat_type] = df[as_cat_type].astype("category")
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

Merged data shape: (1212, 140)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 1,212
Columns: 138
Use sampling: False (sample size: 1,212)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['Constraints', 'Binary_Constraints', 'Problem_Variables', 'Equivalences', 'Other_Equivalences', 'Created_Bodies', 'Normal_Rules', 'Rules', 'Free_Problem_Variables', 'Avg_Conflict_Levels-2']
Rows remaining as candidates after top-10 filter: 62 (of 1,212)

#### Duplicate Report
Total duplicate rows: 5 (0.41% of dataset)
Duplicate rows ignoring target: 10 (0.83% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,algorithm,Frac_Neg_Body,Frac_Pos_Body,Frac_Unary_Rules,Frac_Binary_Rules,Frac_Ternary_Rules,Frac_Integrity_Rules,Tight,Problem_Variables,Free_Problem_Variables,Assigned_Problem_Variables,Constraints,Constraints/Vars,Created_Bodies,Program_Atoms,SCCS,Nodes_in_Positive_BADG,Rules,Normal_Rules,Cardinality_Rules,Choice_Rules,Weight_Rules,Frac_Normal_Rules,Frac_Cardinality_Rules,Frac_Choice_Rules,Frac_Weight_Rules,Equivalences,Atom-Atom_Equivalences,Body-Body_Equivalences,Other_Equivalences,Frac_Atom-Atom_Equivalences,Frac_Body-Body_Equivalences,Frac_Other_Equivalences,Binary_Constraints,Ternary_Constraints,Other_Constraints,Frac_Binary_Constraints,Frac_Ternary_Constraints,Frac_Other_Constraints,Choices-1,Conflicts/Choices-1,Avg_Conflict_Levels-1,Avg_LBD_Levels-1,Learnt_from_Conflict-1,Learnt_from_Loop-1,Frac_Learnt_from_Conflict-1,Frac_Learnt_from_Loop-1,Literals_in_Conflict_Nogoods-1,Literals_in_Loop_Nogoods-1,Frac_Literals_in_Conflict_Nogoods-1,Frac_Literals_in_Loop_Nogoods-1,Removed_Nogoods-1,Learnt_Binary-1,Learnt_Ternary-1,Learnt_Others-1,Frac_Learnt_Binary-1,Frac_Learnt_Ternary-1,Frac_Learnt_Others-1,Skipped_Levels_while_Backjumping-1,Avg_Skipped_Levels_while_Backjumping-1,Longest_Backjumping-1,Running_Avg_Conflictlevel-1,Running_Avg_LBD-1,Choices-2,Conflicts/Choices-2,Avg_Conflict_Levels-2,Avg_LBD_Levels-2,Learnt_from_Conflict-2,Learnt_from_Loop-2,Frac_Learnt_from_Conflict-2,Frac_Learnt_from_Loop-2,Literals_in_Conflict_Nogoods-2,Literals_in_Loop_Nogoods-2,Frac_Literals_in_Conflict_Nogoods-2,Frac_Literals_in_Loop_Nogoods-2,Removed_Nogoods-2,Learnt_Binary-2,Learnt_Ternary-2,Learnt_Others-2,Frac_Learnt_Binary-2,Frac_Learnt_Ternary-2,Frac_Learnt_Others-2,Skipped_Levels_while_Backjumping-2,Avg_Skipped_Levels_while_Backjumping-2,Longest_Backjumping-2,Running_Avg_Conflictlevel-2,Running_Avg_LBD-2,Choices-3,Conflicts/Choices-3,Avg_Conflict_Levels-3,Avg_LBD_Levels-3,Learnt_from_Conflict-3,Learnt_from_Loop-3,Frac_Learnt_from_Conflict-3,Frac_Learnt_from_Loop-3,Literals_in_Conflict_Nogoods-3,Literals_in_Loop_Nogoods-3,Frac_Literals_in_Conflict_Nogoods-3,Frac_Literals_in_Loop_Nogoods-3,Removed_Nogoods-3,Learnt_Binary-3,Learnt_Ternary-3,Learnt_Others-3,Frac_Removed_Nogood-3,Frac_Learnt_Binary-3,Frac_Learnt_Ternary-3,Frac_Learnt_Others-3,Skipped_Levels_while_Backjumping-3,Avg_Skipped_Levels_while_Backjumping-3,Longest_Backjumping-3,Running_Avg_Conflictlevel-3,Running_Avg_LBD-3,Choices-4,Conflicts/Choices-4,Avg_Conflict_Levels-4,Avg_LBD_Levels-4,Learnt_from_Conflict-4,Learnt_from_Loop-4,Frac_Learnt_from_Conflict-4,Frac_Learnt_from_Loop-4,Literals_in_Conflict_Nogoods-4,Literals_in_Loop_Nogoods-4,Frac_Literals_in_Conflict_Nogoods-4,Frac_Literals_in_Loop_Nogoods-4,Removed_Nogoods-4,Learnt_Binary-4,Learnt_Ternary-4,Learnt_Others-4,Frac_Removed_Nogood-4,Frac_Learnt_Binary-4,Frac_Learnt_Ternary-4,Frac_Learnt_Others-4,Skipped_Levels_while_Backjumping-4,Avg_Skipped_Levels_while_Backjumping-4,Longest_Backjumping-4,Running_Avg_Conflictlevel-4,Running_Avg_LBD-4,task_id
0,clasp/2.1.3/h11-n1,0.0094,0.8846,0.0077,0.0045,0.5951,0.4004,0.0,53071.0,44709.0,8362.0,158491.0,2.9864,70097.0,36685.0,100.0,45217.0,71117.0,71086.0,16.0,15.0,0.0,0.9996,0.0002,0.0002,0.0,5763.0,850.0,1071.0,3842.0,0.1475,0.1858,0.6667,106634.0,42268.0,9589.0,0.6728,0.2667,0.0605,84.0,0.3929,11.7879,2.9091,33.0,1338.0,0.0241,0.9759,188.0,42154.0,0.0044,0.9956,0.0,19.0,2.0,1350.0,0.0139,0.0015,0.9847,71.0,2.1515,8.0,3.89,0.96,224.0,0.2902,12.4308,3.1538,65.0,2599.0,0.0244,0.9756,452.0,73881.0,0.0061,0.9939,0.0,27.0,8.0,2629.0,0.0101,0.0030,0.9869,197.0,3.0308,19.0,8.08,2.05,367.0,0.2643,11.4227,3.0206,97.0,3670.0,0.0257,0.9743,611.0,100565.0,0.0060,0.9940,0.0,37.0,14.0,3716.0,0.0,0.0098,0.0037,0.9865,337.0,3.4742,19.0,11.08,2.93,428.0,0.3014,9.6977,2.8450,129.0,4119.0,0.0304,0.9696,774.0,111704.0,0.0069,0.9931,0.0,51.0,17.0,4180.0,0.0,0.0120,0.0040,0.9840,396.0,3.0698,19.0,9.34,2.79,2134e8d16e0d
1,clasp/2.1.3/h4-n1,0.0073,0.7807,0.0051,0.6897,0.2181,0.1476,1.0,9283.0,6338.0,2945.0,23907.0,2.5754,9021.0,8166.0,0.0,0.0,19968.0,19924.0,22.0,22.0,0.0,0.9978,0.0011,0.0011,0.0,24310.0,191.0,1422.0,22697.0,0.0079,0.0585,0.9336,19068.0,1498.0,3341.0,0.7976,0.0627,0.1397,119.0,0.2689,58.5312,3.2188,32.0,0.0,1.0000,0.0000,115.0,0.0,1.0000,0.0000,0.0,3.0,17.0,12.0,0.0938,0.5312,0.3750,61.0,1.9062,5.0,18.73,1.03,222.0,0.2883,42.3750,3.2812,64.0,0.0,1.0000,0.0000,344.0,0.0,1.0000,0.0000,0.0,17.0,25.0,22.0,0.2656,0.3906,0.3438,137.0,2.1406,7.0,27.12,2.10,326.0,0.2945,37.4271,3.1354,96.0,0.0,1.0000,0.0000,526.0,0.0,1.0000,0.0000,0.0,31.0,29.0,36.0,0.0,0.3229,0.3021,0.3750,211.0,2.1979,9.0,35.93,3.01,437.0,0.2929,34.3906,3.2969,128.0,0.0,1.0000,0.0000,1012.0,0.0,1.0000,0.0000,0.0,35.0,36.0,57.0,0.0,0.2734,0.2812,0.4453,297.0,2.3203,24.0,27.78,3.33,93e83d7e99e3
2,clasp/2.1.3/h1-n1,0.0462,0.9792,0.0045,0.0886,0.7975,0.0886,1.0,7516.0,7074.0,442.0,23391.0,3.1122,6733.0,3236.0,0.0,0.0,6907.0,6259.0,504.0,144.0,0.0,0.9062,0.0730,0.0208,0.0,944.0,30.0,144.0,770.0,0.0318,0.1525,0.8157,16524.0,5508.0,1359.0,0.7064,0.2355,0.0581,216.0,0.1620,144.8857,16.2000,35.0,0.0,1.0000,0.0000,687.0,0.0,1.0000,0.0000,0.0,0.0,0.0,35.0,0.0000,0.0000,1.0000,38.0,1.0857,4.0,50.71,5.67,435.0,0.1586,158.3768,17.1884,69.0,0.0,1.0000,0.0000,1632.0,0.0,1.0000,0.0000,0.0,0.0,0.0,69.0,0.0000,0.0000,1.0000,72.0,1.0435,4.0,109.28,11.86,723.0,0.1411,163.6176,16.8137,102.0,0.0,1.0000,0.0000,2270.0,0.0,1.0000,0.0000,0.0,0.0,0.0,102.0,0.0,0.0000,0.0000,1.0000,162.0,1.5882,35.0,164.91,16.83,968.0,0.1384,168.7761,16.6194,134.0,0.0,1.0000,0.0000,3122.0,0.0,1.0000,0.0000,0.0,0.0,0.0,134.0,0.0,0.0000,0.0000,1.0000,219.0,1.6343,35.0,177.24,16.81,886d9dc946db
3,clasp/2.1.3/h5-n1,0.0459,0.9573,0.0185,0.1224,0.7287,0.0002,0.0,215697.0,215335.0,362.0,792842.0,3.6757,185813.0,66783.0,18.0,55247.0,212873.0,212819.0,36.0,18.0,0.0,0.9997,0.0002,0.0001,0.0,76484.0,27603.0,2075.0,46806.0,0.3609,0.0271,0.6120,578477.0,155458.0,58907.0,0.7296,0.1961,0.0743,5244.0,0.0061,1667.8125,6.1562,32.0,3058.0,0.0104,0.9896,422.0,2299140.0,0.0002,0.9998,0.0,0.0,2.0,3088.0,0.0000,0.0006,0.9994,3970.0,124.0625,2531.0,533.70,1.97,6306.0,0.0101,875.5312,4.5312,64.0,3099.0,0.0202,0.9798,676.0,2299782.0,0.0003,0.9997,0.0,12.0,12.0,3139.0,0.0038,0.0038,0.9924,4919.0,76.8594,2531.0,560.34,2.90,8272.0,0.0116,637.2500,3.9792,96.0,3150.0,0.0296,0.9704,980.0,2300935.0,0.0004,0.9996,0.0,17.0,18.0,3211.0,0.0,0.0052,0.0055,0.9892,5608.0,58.4167,2531.0,611.76,3.82,9018.0,0.0142,492.9531,3.6875,128.0,3434.0,0.0359,0.9641,1101.0,2308869.0,0.0005,0.9995,0.0,31.0,22.0,3509.0,0.0,0.0087,0.0062,0.9851,6312.0,49.3125,2531.0,129.25,2.94,81728f2574c3
4,clasp/2.1.3/h4-n1,0.0024,0.8266,0.0007,0.0088,0.2024,0.0195,1.0,37516.0,25890.0,11626.0,144822.0,3.8603,226931.0,2453.0,0.0,0.0,285808.0,285808.0,0.0,0.0,0.0,1.0000,0.0000,0.0000,0.0,5777.0,194.0,3410.0,2173.0,0.0336,0.5903,0.3761,114794.0,22364.0,7664.0,0.7927,0.1544,0.0529,47.0,0.6809,10.5000,9.4062,32.0,0.0,1.0000,0.0000,8188.0,0.0,1.0000,0.0000,0.0,2.0,0.0,30.0,0.0625,0.0000,0.9375,41.0,1.2812,8.0,3.36,3.01,91.0,0.7033,6.7969,5.8594,64.0,0.0,1.0000,0.0000,9797.0,0.0,1.0000,0.0000,0.0,5.0,1.0,58.0,0.0781,0.0156,0.9062,85.0,1.3281,8.0,4.35,3.75,209.0,0.4593,6.3750,4.8125,96.0,0.0,1.0000,0.0000,10298.0,0.0,1.0000,0.0000,0.0,19.0,12.0,65.0,0.0,0.1979,0.1250,0.6771,202.0,2.1042,13.0,6.12,4.62,244.0,0.5246,5.1875,3.9922,128.0,0.0,1.0000,0.0000,10862.0,0.0,1.0000,0.0000,0.0,19.0,12.0,97.0,0.0,0.1484,0.0938,0.7578,237.0,1.8516,13.0,3.56,2.31,71bdaba653d9

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,algorithm,category,0.0,0.00,11.0,"clasp/2.1.3/h1-n1, clasp/2.1.3/h10-n1, clasp/2.1.3/h6-n1, clasp/2.1.3/h4-n1, clasp/2.1.3/h8-n1, clasp/2.1.3/h7-n1, clasp/2.1.3/h2-n1, clasp/2.1.3/h11-n1, clasp/2.1.3/h9-n1, clasp/2.1.3/h5-n1"
1,task_id,category,0.0,0.00,96.0,"81728f2574c3, 8f6a79c51a4b, 00cf7b166f3c, e57bbf07e3ce, fd0e9d0851f7, 2b9a735d9c1d, 12fc10127cde, 27c3fb2ec1c4, 4806e1713598, cf4b46f8eb3c"
2,Choices-4,float64,218.0,17.99,751.0,"528.0, 200.0, 644.0, 716.0, 634.0, 974.0, 415.0, 557.0, 128.0, 411.0"
3,Conflicts/Choices-4,float64,218.0,17.99,812.0,"0.2424, 0.2524, 0.1427, 0.2393, 0.0047, 0.0048, 0.0075, 0.2622, 0.2298, 0.251"
4,Avg_Conflict_Levels-4,float64,218.0,17.99,954.0,"33.8984, 64.6589, 1.0, 38.1016, 33.1797, 10.3125, 19.8438, 49.6692, 45.3594, 53.3566"
5,Avg_LBD_Levels-4,float64,218.0,17.99,825.0,"3.1406, 4.0231, 10.6641, 3.5469, 3.9922, 2.8281, 4.1008, 3.0, 5.4297, 3.2578"
6,Learnt_from_Conflict-4,float64,218.0,17.99,10.0,"128.0, 129.0, 130.0, 131.0, 132.0, 133.0, 134.0, 135.0, 136.0, 120.0"
7,Learnt_from_Loop-4,float64,218.0,17.99,284.0,"0.0, 28.0, 31.0, 30.0, 37.0, 11.0, 9.0, 32.0, 18.0, 26.0"
8,Frac_Learnt_from_Conflict-4,float64,218.0,17.99,312.0,"1.0, 0.8205, 0.805, 0.8101, 0.9209, 0.9343, 0.8312, 0.8767, 0.8421, 0.9481"
9,Frac_Learnt_from_Loop-4,float64,218.0,17.99,312.0,"0.0, 0.1795, 0.195, 0.1899, 0.0791, 0.0657, 0.1688, 0.1233, 0.1579, 0.0519"
10,Literals_in_Conflict_Nogoods-4,float64,218.0,17.99,861.0,"684.0, 913.0, 1770.0, 442.0, 1070.0, 128.0, 2116.0, 757.0, 708.0, 1451.0"
11,Literals_in_Loop_Nogoods-4,float64,218.0,17.99,353.0,"0.0, 55.0, 45.0, 135.0, 160.0, 130.0, 120.0, 40.0, 150.0, 116.0"
12,Frac_Literals_in_Conflict_Nogoods-4,float64,218.0,17.99,357.0,"1.0, 0.0011, 0.0014, 0.0019, 0.0016, 0.0018, 0.0004, 0.0115, 0.0025, 0.002"
13,Frac_Literals_in_Loop_Nogoods-4,float64,218.0,17.99,357.0,"0.0, 0.9989, 0.9986, 0.9981, 0.9984, 0.9982, 0.9996, 0.9885, 0.9975, 0.998"
14,Removed_Nogoods-4,float64,218.0,17.99,6.0,"0.0, 92.0, 93.0, 89.0, 61.0, 90.0"
15,Learnt_Binary-4,float64,218.0,17.99,73.0,"0.0, 2.0, 3.0, 1.0, 6.0, 7.0, 14.0, 4.0, 17.0, 12.0"
16,Learnt_Ternary-4,float64,218.0,17.99,106.0,"0.0, 1.0, 10.0, 19.0, 18.0, 9.0, 8.0, 22.0, 14.0, 7.0"
17,Learnt_Others-4,float64,218.0,17.99,336.0,"129.0, 128.0, 130.0, 131.0, 94.0, 132.0, 126.0, 127.0, 108.0, 54.0"
18,Frac_Removed_Nogood-4,float64,218.0,17.99,12.0,"0.0, 0.7266, 0.7188, 0.7099, 0.7023, 0.6953, 0.7132, 0.697, 0.4766, 0.6899"
19,Frac_Learnt_Binary-4,float64,218.0,17.99,417.0,"0.0, 0.0078, 0.0046, 0.0156, 0.2969, 0.0076, 0.1318, 0.1797, 0.1484, 0.0923"
20,Frac_Learnt_Ternary-4,float64,218.0,17.99,454.0,"0.0, 0.0078, 0.0076, 0.2812, 0.1154, 0.1473, 0.0938, 0.062, 0.0156, 0.0077"
21,Frac_Learnt_Others-4,float64,218.0,17.99,549.0,"1.0, 0.9922, 0.9924, 0.4219, 0.9766, 0.9844, 0.9923, 0.7231, 0.9927, 0.7344"
22,Skipped_Levels_while_Backjumping-4,float64,218.0,17.99,691.0,"382.0, 163.0, 128.0, 169.0, 159.0, 351.0, 178.0, 161.0, 181.0, 436.0"
23,Avg_Skipped_Levels_while_Backjumping-4,float64,218.0,17.99,872.0,"1.0, 2.9844, 1.2846, 1.2636, 2.7209, 1.2578, 3.4846, 4.0, 3.374, 3.0"
24,Longest_Backjumping-4,float64,218.0,17.99,305.0,"24.0, 4.0, 6.0, 5.0, 20.0, 26.0, 27.0, 7.0, 16.0, 17.0"
25,Running_Avg_Conflictlevel-4,float64,218.0,17.99,905.0,"27.15, 18.88, 1.0, 17.91, 26.11, 29.27, 12.48, 16.22, 29.95, 33.91"
26,Running_Avg_LBD-4,float64,218.0,17.99,544.0,"3.13, 3.2, 3.93, 4.93, 2.99, 3.44, 3.58, 3.11, 4.75, 3.95"
27,Choices-3,float64,191.0,15.76,693.0,"341.0, 209.0, 338.0, 410.0, 158.0, 339.0, 162.0, 336.0, 473.0, 453.0"
28,Conflicts/Choices-3,float64,191.0,15.76,814.0,"0.2815, 0.2861, 0.2553, 0.4593, 0.9796, 0.3345, 0.0093, 0.1696, 0.6139, 0.198"
29,Avg_Conflict_Levels-3,float64,191.0,15.76,968.0,"37.6667, 1.1875, 1.0, 31.7188, 35.1042, 29.1667, 8.2917, 31.2083, 30.5833, 11.4583"
30,Avg_LBD_Levels-3,float64,191.0,15.76,797.0,"3.1146, 2.6667, 3.5729, 2.6979, 3.125, 2.75, 3.9479, 12.0, 2.9479, 3.625"
31,Learnt_from_Conflict-3,float64,191.0,15.76,12.0,"96.0, 97.0, 98.0, 99.0, 100.0, 101.0, 72.0, 103.0, 68.0, 102.0"
32,Learnt_from_Loop-3,float64,191.0,15.76,279.0,"0.0, 21.0, 26.0, 1.0, 23.0, 14.0, 22.0, 7.0, 19.0, 4.0"
33,Frac_Learnt_from_Conflict-3,float64,191.0,15.76,300.0,"1.0, 0.8205, 0.7869, 0.932, 0.8, 0.8348, 0.8136, 0.8727, 0.7934, 0.9505"
34,Frac_Learnt_from_Loop-3,float64,191.0,15.76,300.0,"0.0, 0.1795, 0.2131, 0.068, 0.2, 0.1652, 0.1864, 0.1273, 0.2066, 0.0495"
35,Literals_in_Conflict_Nogoods-3,float64,191.0,15.76,856.0,"521.0, 295.0, 917.0, 297.0, 1433.0, 355.0, 301.0, 318.0, 311.0, 313.0"
36,Literals_in_Loop_Nogoods-3,float64,191.0,15.76,344.0,"0.0, 551.0, 40.0, 125.0, 35.0, 105.0, 30.0, 65.0, 25.0, 70.0"
37,Frac_Literals_in_Conflict_Nogoods-3,float64,191.0,15.76,353.0,"1.0, 0.0014, 0.0016, 0.0022, 0.0024, 0.0013, 0.001, 0.0125, 0.876, 0.0012"
38,Frac_Literals_in_Loop_Nogoods-3,float64,191.0,15.76,353.0,"0.0, 0.9986, 0.9984, 0.9978, 0.9976, 0.9987, 0.999, 0.9875, 0.124, 0.9988"
39,Removed_Nogoods-3,float64,191.0,15.76,2.0,"0.0, 61.0"
40,Learnt_Binary-3,float64,191.0,15.76,59.0,"0.0, 2.0, 1.0, 4.0, 3.0, 11.0, 5.0, 6.0, 10.0, 9.0"
41,Learnt_Ternary-3,float64,191.0,15.76,86.0,"0.0, 7.0, 1.0, 10.0, 9.0, 8.0, 3.0, 4.0, 5.0, 16.0"
42,Learnt_Others-3,float64,191.0,15.76,323.0,"96.0, 97.0, 99.0, 98.0, 95.0, 93.0, 65.0, 71.0, 66.0, 58.0"
43,Frac_Removed_Nogood-3,float64,191.0,15.76,2.0,"0.0, 0.6354"
44,Frac_Learnt_Binary-3,float64,191.0,15.76,361.0,"0.0, 0.0104, 0.0208, 0.3333, 0.1649, 0.0816, 0.0103, 0.0928, 0.0729, 0.1146"
45,Frac_Learnt_Ternary-3,float64,191.0,15.76,391.0,"0.0, 0.0104, 0.0729, 0.0833, 0.134, 0.0208, 0.3021, 0.1531, 0.1771, 0.0102"
46,Frac_Learnt_Others-3,float64,191.0,15.76,499.0,"1.0, 0.9896, 0.9897, 0.9688, 0.8646, 0.7526, 0.3646, 0.7245, 0.6875, 0.9792"
47,Skipped_Levels_while_Backjumping-3,float64,191.0,15.76,655.0,"223.0, 96.0, 125.0, 135.0, 123.0, 118.0, 267.0, 136.0, 128.0, 232.0"
48,Avg_Skipped_Levels_while_Backjumping-3,float64,191.0,15.76,856.0,"1.0, 2.3229, 1.2292, 1.3021, 2.7812, 1.3776, 2.4167, 1.4227, 1.4021, 3.1771"
49,Longest_Backjumping-3,float64,191.0,15.76,300.0,"4.0, 16.0, 5.0, 6.0, 27.0, 9.0, 26.0, 24.0, 15.0, 7.0"
50,Running_Avg_Conflictlevel-3,float64,191.0,15.76,930.0,"36.16, 1.14, 9.38, 27.38, 30.45, 33.7, 0.96, 9.96, 10.96, 29.36"
51,Running_Avg_LBD-3,float64,191.0,15.76,599.0,"2.99, 3.82, 3.86, 3.83, 11.88, 3.79, 3.0, 3.32, 2.56, 3.43"
52,Choices-2,float64,162.0,13.37,630.0,"222.0, 102.0, 190.0, 205.0, 196.0, 64.0, 241.0, 278.0, 108.0, 198.0"
53,Conflicts/Choices-2,float64,162.0,13.37,757.0,"0.2883, 0.3368, 1.0, 0.3351, 0.6275, 0.0064, 0.3333, 0.3265, 0.2591, 0.619"
54,Avg_Conflict_Levels-2,float64,162.0,13.37,977.0,"42.375, 1.0, 32.7969, 4.4565, 1.9844, 32.3594, 11.9091, 19.3594, 22.9688, 28.8281"
55,Avg_LBD_Levels-2,float64,162.0,13.37,719.0,"3.2812, 2.8125, 4.0, 1.0, 2.6562, 2.7031, 3.0938, 4.5, 2.4844, 2.7969"
56,Learnt_from_Conflict-2,float64,162.0,13.37,12.0,"64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 49.0, 46.0, 58.0, 54.0"
57,Learnt_from_Loop-2,float64,162.0,13.37,270.0,"0.0, 4.0, 10.0, 14.0, 5.0, 8.0, 2.0, 7.0, 6.0, 18.0"
58,Frac_Learnt_from_Conflict-2,float64,162.0,13.37,255.0,"1.0, 0.9412, 0.8649, 0.9275, 0.8205, 0.9143, 0.9014, 0.9697, 0.8889, 0.7111"
59,Frac_Learnt_from_Loop-2,float64,162.0,13.37,255.0,"0.0, 0.0588, 0.1351, 0.0725, 0.1795, 0.0857, 0.0986, 0.0303, 0.1111, 0.2889"
60,Literals_in_Conflict_Nogoods-2,float64,162.0,13.37,791.0,"344.0, 64.0, 204.0, 200.0, 194.0, 190.0, 196.0, 213.0, 198.0, 603.0"
61,Literals_in_Loop_Nogoods-2,float64,162.0,13.37,316.0,"0.0, 20.0, 50.0, 25.0, 40.0, 70.0, 551.0, 35.0, 30.0, 60.0"
62,Frac_Literals_in_Conflict_Nogoods-2,float64,162.0,13.37,333.0,"1.0, 0.002, 0.001, 0.0014, 0.0012, 0.0003, 0.0011, 0.0045, 0.0053, 0.0088"
63,Frac_Literals_in_Loop_Nogoods-2,float64,162.0,13.37,333.0,"0.0, 0.998, 0.999, 0.9986, 0.9988, 0.9997, 0.9989, 0.9955, 0.9947, 0.9912"
64,Removed_Nogoods-2,float64,162.0,13.37,1.0,0.0
65,Learnt_Binary-2,float64,162.0,13.37,48.0,"0.0, 2.0, 1.0, 3.0, 4.0, 5.0, 9.0, 8.0, 7.0, 11.0"
66,Learnt_Ternary-2,float64,162.0,13.37,63.0,"0.0, 1.0, 3.0, 5.0, 6.0, 2.0, 7.0, 12.0, 10.0, 4.0"
67,Learnt_Others-2,float64,162.0,13.37,306.0,"64.0, 65.0, 66.0, 45.0, 63.0, 35.0, 56.0, 36.0, 42.0, 62.0"
68,Frac_Learnt_Binary-2,float64,162.0,13.37,281.0,"0.0, 0.0156, 0.2656, 0.0469, 0.0312, 0.0781, 0.0625, 0.1385, 0.1719, 0.0154"
69,Frac_Learnt_Ternary-2,float64,162.0,13.37,322.0,"0.0, 0.0156, 0.1875, 0.0781, 0.0469, 0.1094, 0.125, 0.0154, 0.3906, 0.0938"
70,Frac_Learnt_Others-2,float64,162.0,13.37,403.0,"1.0, 0.9844, 0.5469, 0.3438, 0.9688, 0.9531, 0.9846, 0.875, 0.7344, 0.7031"
71,Skipped_Levels_while_Backjumping-2,float64,162.0,13.37,569.0,"137.0, 84.0, 75.0, 78.0, 64.0, 82.0, 156.0, 80.0, 85.0, 83.0"
72,Avg_Skipped_Levels_while_Backjumping-2,float64,162.0,13.37,774.0,"2.1406, 1.0, 1.2, 1.1875, 1.2969, 6.0938, 1.3125, 2.3906, 1.2812, 2.4"
73,Longest_Backjumping-2,float64,162.0,13.37,283.0,"4.0, 16.0, 7.0, 5.0, 3.0, 14.0, 15.0, 20.0, 11.0, 6.0"
74,Running_Avg_Conflictlevel-2,float64,162.0,13.37,923.0,"27.12, 0.64, 20.99, 20.71, 10.81, 16.73, 2.05, 8.95, 52.82, 18.5"
75,Running_Avg_LBD-2,float64,162.0,13.37,538.0,"2.1, 1.8, 1.98, 1.74, 0.64, 1.7, 3.75, 1.73, 2.15, 1.87"
76,Choices-1,float64,135.0,11.14,463.0,"119.0, 59.0, 82.0, 64.0, 92.0, 66.0, 101.0, 47.0, 32.0, 61.0"
77,Conflicts/Choices-1,float64,135.0,11.14,600.0,"0.2689, 0.5, 0.5424, 1.0, 0.3902, 0.7111, 0.2735, 0.5246, 0.3368, 0.6531"
78,Avg_Conflict_Levels-1,float64,135.0,11.14,923.0,"58.5312, 1.0, 7.1875, 33.7188, 28.5, 32.7188, 23.1562, 33.875, 21.6562, 17.3125"
79,Avg_LBD_Levels-1,float64,135.0,11.14,543.0,"1.0, 3.125, 2.4062, 3.2188, 2.5625, 2.5312, 2.5938, 3.0, 3.0312, 5.0625"
80,Learnt_from_Conflict-1,float64,135.0,11.14,6.0,"32.0, 33.0, 34.0, 35.0, 36.0, 9.0"
81,Learnt_from_Loop-1,float64,135.0,11.14,245.0,"0.0, 2.0, 4.0, 1.0, 11.0, 6.0, 3.0, 5.0, 105.0, 218.0"
82,Frac_Learnt_from_Conflict-1,float64,135.0,11.14,222.0,"1.0, 0.9412, 0.8889, 0.7442, 0.9697, 0.8421, 0.9143, 0.8649, 0.0063, 0.0082"
83,Frac_Learnt_from_Loop-1,float64,135.0,11.14,222.0,"0.0, 0.0588, 0.1111, 0.2558, 0.0303, 0.1579, 0.0857, 0.1351, 0.9937, 0.9918"
84,Literals_in_Conflict_Nogoods-1,float64,135.0,11.14,693.0,"32.0, 103.0, 115.0, 101.0, 102.0, 346.0, 100.0, 98.0, 272.0, 113.0"
85,Literals_in_Loop_Nogoods-1,float64,135.0,11.14,290.0,"0.0, 10.0, 131.0, 20.0, 49.0, 12.0, 15.0, 62.0, 102.0, 33.0"
86,Frac_Literals_in_Conflict_Nogoods-1,float64,135.0,11.14,297.0,"1.0, 0.9115, 0.9099, 0.9107, 0.9187, 0.9091, 0.9145, 0.9153, 0.0009, 0.0002"
87,Frac_Literals_in_Loop_Nogoods-1,float64,135.0,11.14,297.0,"0.0, 0.0885, 0.0901, 0.0893, 0.0813, 0.0909, 0.0855, 0.0847, 0.9991, 0.9998"
88,Removed_Nogoods-1,float64,135.0,11.14,1.0,0.0
89,Learnt_Binary-1,float64,135.0,11.14,31.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
90,Learnt_Ternary-1,float64,135.0,11.14,38.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 14.0, 6.0, 13.0, 7.0"
91,Learnt_Others-1,float64,135.0,11.14,272.0,"32.0, 30.0, 33.0, 29.0, 31.0, 26.0, 25.0, 28.0, 19.0, 18.0"
92,Frac_Learnt_Binary-1,float64,135.0,11.14,165.0,"0.0, 0.0312, 0.0938, 0.0588, 0.0294, 0.0625, 0.0606, 0.125, 0.0909, 0.0303"
93,Frac_Learnt_Ternary-1,float64,135.0,11.14,194.0,"0.0, 0.0312, 0.125, 0.0625, 0.0938, 0.1562, 0.0303, 0.4118, 0.3824, 0.0606"
94,Frac_Learnt_Others-1,float64,135.0,11.14,232.0,"1.0, 0.9375, 0.7812, 0.9688, 0.8125, 0.5588, 0.875, 0.9062, 0.8788, 0.5294"
95,Skipped_Levels_while_Backjumping-1,float64,135.0,11.14,386.0,"53.0, 38.0, 42.0, 41.0, 59.0, 61.0, 55.0, 39.0, 46.0, 77.0"
96,Avg_Skipped_Levels_while_Backjumping-1,float64,135.0,11.14,504.0,"1.1875, 1.6562, 1.3125, 1.8438, 1.0, 1.9062, 1.2812, 1.7188, 2.0, 2.75"
97,Longest_Backjumping-1,float64,135.0,11.14,190.0,"4.0, 5.0, 3.0, 2.0, 8.0, 11.0, 6.0, 7.0, 9.0, 12.0"
98,Running_Avg_Conflictlevel-1,float64,135.0,11.14,864.0,"18.73, 0.32, 3.33, 2.3, 10.79, 5.01, 7.22, 4.78, 2.77, 2.65"
99,Running_Avg_LBD-1,float64,135.0,11.14,430.0,"1.0, 0.32, 1.03, 0.77, 0.82, 0.81, 1.08, 0.99, 1.62, 1.32"
100,Frac_Neg_Body,float64,16.0,1.32,648.0,"0.018, 0.0015, 0.0051, 0.0093, 0.0179, 0.01, 0.0014, 0.005, 0.007, 0.5386"
101,Frac_Pos_Body,float64,16.0,1.32,679.0,"0.9923, 0.9872, 0.9985, 0.9576, 0.9574, 0.8223, 0.9577, 0.9568, 0.9572, 0.995"
102,Frac_Unary_Rules,float64,16.0,1.32,514.0,"0.0, 0.0021, 0.0013, 0.0019, 0.0039, 0.004, 0.0017, 0.0011, 0.0026, 0.0186"
103,Frac_Binary_Rules,float64,16.0,1.32,825.0,"0.003, 0.0011, 0.0008, 0.097, 0.1082, 0.0695, 0.2866, 0.0961, 0.1213, 0.2863"
104,Frac_Ternary_Rules,float64,16.0,1.32,855.0,"0.0076, 0.0, 0.016, 0.2611, 0.2025, 0.2644, 0.2699, 0.2675, 0.5983, 0.7299"
105,Frac_Integrity_Rules,float64,16.0,1.32,663.0,"0.0003, 0.0002, 0.0001, 0.0, 0.0385, 0.976, 0.0004, 0.0006, 0.9934, 0.9935"
106,Tight,float64,16.0,1.32,2.0,"1.0, 0.0"
107,Problem_Variables,float64,16.0,1.32,1051.0,"146291.0, 168724.0, 218803.0, 191157.0, 20626.0, 678.0, 865.0, 439.0, 21943.0, 2683.0"
108,Free_Problem_Variables,float64,16.0,1.32,1012.0,"342.0, 1545.0, 559.0, 2365.0, 524.0, 146254.0, 625.0, 191110.0, 218742.0, 725.0"
109,Assigned_Problem_Variables,float64,16.0,1.32,834.0,"102.0, 442.0, 401.0, 257.0, 4.0, 152.0, 202.0, 122.0, 290.0, 362.0"
110,Constraints,float64,16.0,1.32,1095.0,"613593.0, 802603.0, 708098.0, 2129.0, 160624.0, 82744.0, 519088.0, 222.0, 5000.0, 335.0"
111,Constraints/Vars,float64,16.0,1.32,955.0,"0.9924, 1.1141, 1.1139, 1.1143, 1.1142, 4.1943, 1.114, 4.1968, 1.1146, 4.1987"
112,Created_Bodies,float64,16.0,1.32,1031.0,"43096.0, 907187.0, 203685.0, 135239.0, 445.0, 156018.0, 176797.0, 161740.0, 1681.0, 2725.0"
113,Program_Atoms,float64,16.0,1.32,957.0,"2887.0, 2007.0, 1716.0, 1711.0, 1026.0, 7803.0, 2524.0, 6873.0, 5203.0, 11603.0"
114,SCCS,float64,16.0,1.32,52.0,"0.0, 1.0, 17.0, 18.0, 12.0, 19.0, 20.0, 16.0, 10.0, 15.0"
115,Nodes_in_Positive_BADG,float64,16.0,1.32,504.0,"0.0, 132655.0, 57096.0, 74504.0, 65800.0, 48392.0, 663.0, 91912.0, 39688.0, 602.0"
116,Rules,float64,16.0,1.32,1024.0,"85325.0, 21890.0, 85315.0, 7802.0, 11702.0, 17402.0, 205926.0, 21895.0, 139990.0, 161411.0"
117,Normal_Rules,float64,16.0,1.32,1027.0,"21520.0, 85065.0, 85055.0, 9002.0, 6002.0, 13402.0, 205854.0, 139948.0, 182778.0, 161363.0"
118,Cardinality_Rules,float64,16.0,1.32,357.0,"0.0, 32.0, 36.0, 30.0, 1.0, 34.0, 28.0, 40.0, 38.0, 2.0"
119,Choice_Rules,float64,16.0,1.32,475.0,"0.0, 130.0, 1.0, 100.0, 16.0, 15.0, 18.0, 150.0, 10.0, 200.0"
120,Weight_Rules,float64,16.0,1.32,32.0,"0.0, 1.0, 146.0, 30.0, 6.0, 28.0, 299.0, 147.0, 26.0, 27.0"
121,Frac_Normal_Rules,float64,16.0,1.32,480.0,"1.0, 0.9997, 0.9998, 0.9996, 0.9995, 0.997, 0.7693, 0.9994, 0.9916, 0.9978"
122,Frac_Cardinality_Rules,float64,16.0,1.32,299.0,"0.0, 0.0002, 0.0001, 0.0003, 0.0004, 0.0011, 0.0006, 0.0005, 0.0015, 0.001"
123,Frac_Choice_Rules,float64,16.0,1.32,412.0,"0.0, 0.0001, 0.0002, 0.0003, 0.0015, 0.0011, 0.0059, 0.2051, 0.177, 0.0042"
124,Frac_Weight_Rules,float64,16.0,1.32,39.0,"0.0, 0.0003, 0.0002, 0.006, 0.0004, 0.0798, 0.0001, 0.0797, 0.0779, 0.0787"
125,Equivalences,float64,16.0,1.32,1046.0,"18053.0, 13204.0, 8804.0, 19604.0, 19530.0, 24818.0, 22174.0, 8706.0, 16886.0, 4563.0"
126,Atom-Atom_Equivalences,float64,16.0,1.32,877.0,"285.0, 1572.0, 295.0, 174.0, 2501.0, 149.0, 164.0, 154.0, 0.0, 6807.0"
127,Body-Body_Equivalences,float64,16.0,1.32,731.0,"0.0, 1.0, 90.0, 70.0, 2.0, 100.0, 24.0, 64.0, 18.0, 5.0"
128,Other_Equivalences,float64,16.0,1.32,1032.0,"6303.0, 9453.0, 14003.0, 19249.0, 21889.0, 3963.0, 24529.0, 3085.0, 6183.0, 992.0"
129,Frac_Atom-Atom_Equivalences,float64,16.0,1.32,756.0,"0.2841, 0.3616, 0.3609, 0.0828, 0.2689, 0.0, 0.3612, 0.2857, 0.3614, 0.1799"
130,Frac_Body-Body_Equivalences,float64,16.0,1.32,601.0,"0.0, 0.0007, 0.0051, 0.0003, 0.0009, 0.0203, 0.0174, 0.1194, 0.1195, 0.0002"
131,Frac_Other_Equivalences,float64,16.0,1.32,804.0,"0.7159, 1.0, 0.6116, 0.9856, 0.6115, 0.9859, 0.9256, 0.613, 0.6117, 0.7143"
132,Binary_Constraints,float64,16.0,1.32,1068.0,"0.0, 2880.0, 467359.0, 611519.0, 539439.0, 395279.0, 78090.0, 264.0, 4466.0, 323199.0"
133,Ternary_Constraints,float64,16.0,1.32,974.0,"0.0, 1800.0, 800.0, 1200.0, 42760.0, 56168.0, 157500.0, 49464.0, 1.0, 82.0"
134,Other_Constraints,float64,16.0,1.32,882.0,"300.0, 220.0, 230.0, 600.0, 7602.0, 450.0, 103474.0, 290.0, 301.0, 303.0"
135,Frac_Binary_Constraints,float64,16.0,1.32,704.0,"0.7296, 0.7295, 0.7297, 0.0, 0.7976, 0.0179, 0.7618, 0.6635, 0.7294, 0.7639"
136,Frac_Ternary_Constraints,float64,16.0,1.32,672.0,"0.0, 0.1961, 0.0382, 0.196, 0.1962, 0.0383, 0.0381, 0.1959, 0.0616, 0.1958"
137,Frac_Other_Constraints,float64,16.0,1.32,619.0,"0.0743, 0.0742, 0.0744, 1.0, 0.0745, 0.0015, 0.0746, 0.0747, 0.051, 0.1408"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
Frac_Neg_Body,1196.0,0.133759,2.194506e-01,0.0002,9.283000e-01
Frac_Pos_Body,1196.0,0.790592,2.101437e-01,0.0000,9.994000e-01
Frac_Unary_Rules,1196.0,0.103597,2.008177e-01,0.0000,8.863000e-01
Frac_Binary_Rules,1196.0,0.191836,1.667393e-01,0.0000,9.737000e-01
Frac_Ternary_Rules,1196.0,0.494413,2.773479e-01,0.0000,1.000000e+00
Frac_Integrity_Rules,1196.0,0.282627,2.775921e-01,0.0000,9.977000e-01
Tight,1196.0,0.517559,4.999006e-01,0.0000,1.000000e+00
Problem_Variables,1196.0,94270.510033,3.614105e+05,59.0000,7.758660e+06
Free_Problem_Variables,1196.0,50633.986622,1.015189e+05,45.0000,1.691690e+06
Assigned_Problem_Variables,1196.0,43636.523411,3.151337e+05,2.0000,6.910879e+06
Constraints,1196.0,205693.154682,4.257232e+05,138.0000,7.054066e+06
Constraints/Vars,1196.0,2.289328,1.875871e+00,0.1223,1.759760e+01
Created_Bodies,1196.0,118256.929766,4.103365e+05,105.0000,8.043761e+06
Program_Atoms,1196.0,41523.083612,9.980722e+04,51.0000,2.498934e+06
SCCS,1196.0,9.096154,2.867314e+01,0.0000,4.250000e+02
Nodes_in_Positive_BADG,1196.0,14336.841973,3.350684e+04,0.0000,4.074170e+05
Rules,1196.0,166206.749164,6.792293e+05,125.0000,1.418204e+07
Normal_Rules,1196.0,155016.755017,6.768045e+05,105.0000,1.418184e+07
Cardinality_Rules,1196.0,4669.495819,1.801448e+04,0.0000,1.607970e+05
Choice_Rules,1196.0,6513.232441,1.784869e+04,0.0000,1.429410e+05
Weight_Rules,1196.0,7.265886,3.929148e+01,0.0000,2.990000e+02
Frac_Normal_Rules,1196.0,0.900057,1.282358e-01,0.4223,1.000000e+00
Frac_Cardinality_Rules,1196.0,0.043771,8.503083e-02,0.0000,5.564000e-01
Frac_Choice_Rules,1196.0,0.053623,6.655548e-02,0.0000,2.227000e-01
Frac_Weight_Rules,1196.0,0.002549,1.390465e-02,0.0000,8.290000e-02
Equivalences,1196.0,76508.510033,1.869690e+05,2.0000,3.678844e+06
Atom-Atom_Equivalences,1196.0,19026.581940,5.388715e+04,0.0000,1.219248e+06
Body-Body_Equivalences,1196.0,6656.076923,2.217661e+04,0.0000,5.368620e+05
Other_Equivalences,1196.0,50825.851171,1.142457e+05,2.0000,1.922734e+06
Frac_Atom-Atom_Equivalences,1196.0,0.203499,1.316732e-01,0.0000,4.743000e-01
Frac_Body-Body_Equivalences,1196.0,0.070607,9.439276e-02,0.0000,6.460000e-01
Frac_Other_Equivalences,1196.0,0.725891,1.364180e-01,0.3425,1.000000e+00
Binary_Constraints,1196.0,150438.297659,3.349841e+05,0.0000,5.388172e+06
Ternary_Constraints,1196.0,38543.838629,8.734779e+04,0.0000,1.665484e+06
Other_Constraints,1196.0,16711.018395,3.194062e+04,8.0000,1.978000e+05
Frac_Binary_Constraints,1196.0,0.665059,2.210482e-01,0.0000,9.979000e-01
Frac_Ternary_Constraints,1196.0,0.206640,2.054618e-01,0.0000,9.823000e-01
Frac_Other_Constraints,1196.0,0.128300,1.845784e-01,0.0000,1.000000e+00
Choices-1,1077.0,418.518106,1.079083e+03,14.0000,1.858400e+04
Conflicts/Choices-1,1077.0,0.273656,2.092576e-01,0.0017,1.000000e+00
Avg_Conflict_Levels-1,1077.0,130.113318,3.430163e+02,1.0000,3.490886e+03
Avg_LBD_Levels-1,1077.0,8.441906,1.107125e+01,1.0000,1.034688e+02
Learnt_from_Conflict-1,1077.0,32.314763,9.898628e-01,9.0000,3.600000e+01
Learnt_from_Loop-1,1077.0,463.721448,1.298138e+03,0.0000,1.261200e+04
Frac_Learnt_from_Conflict-1,1077.0,0.777021,3.859689e-01,0.0025,1.000000e+00
Frac_Learnt_from_Loop-1,1077.0,0.222979,3.859689e-01,0.0000,9.975000e-01
Literals_in_Conflict_Nogoods-1,1077.0,1637.544104,4.015153e+03,14.0000,3.737300e+04
Literals_in_Loop_Nogoods-1,1077.0,178052.707521,1.047088e+06,0.0000,1.377102e+07
Frac_Literals_in_Conflict_Nogoods-1,1077.0,0.780685,3.786011e-01,0.0000,1.000000e+00
Frac_Literals_in_Loop_Nogoods-1,1077.0,0.219315,3.786011e-01,0.0000,1.000000e+00
Removed_Nogoods-1,1077.0,0.000000,0.000000e+00,0.0000,0.000000e+00
Learnt_Binary-1,1077.0,3.162488,1.651648e+01,0.0000,3.650000e+02
Learnt_Ternary-1,1077.0,7.750232,3.905286e+01,0.0000,7.660000e+02
Learnt_Others-1,1077.0,485.123491,1.282042e+03,0.0000,1.231600e+04
Frac_Learnt_Binary-1,1077.0,0.045099,8.856558e-02,0.0000,8.438000e-01
Frac_Learnt_Ternary-1,1077.0,0.099649,1.501758e-01,0.0000,1.000000e+00
Frac_Learnt_Others-1,1077.0,0.855246,1.933434e-01,0.0000,1.000000e+00
Skipped_Levels_while_Backjumping-1,1077.0,281.051068,8.592869e+02,14.0000,1.854500e+04
Avg_Skipped_Levels_while_Backjumping-1,1077.0,8.732978,2.680345e+01,1.0000,5.795312e+02
Longest_Backjumping-1,1077.0,74.886722,2.817891e+02,1.0000,4.612000e+03
Running_Avg_Conflictlevel-1,1077.0,42.117948,1.115325e+02,0.1600,1.221810e+03
Running_Avg_LBD-1,1077.0,2.737957,3.616636e+00,0.1100,3.311000e+01
Choices-2,1050.0,1386.282857,3.636914e+03,63.0000,5.219100e+04
Conflicts/Choices-2,1050.0,0.245546,1.973641e-01,0.0013,1.000000e+00
Avg_Conflict_Levels-2,1050.0,175.351877,4.683977e+02,1.0000,3.449359e+03
Avg_LBD_Levels-2,1050.0,7.585695,9.113076e+00,1.0000,8.912500e+01
Learnt_from_Conflict-2,1050.0,64.535238,1.819080e+00,46.0000,7.000000e+01
Learnt_from_Loop-2,1050.0,663.147619,1.920347e+03,0.0000,2.350300e+04
Frac_Learnt_from_Conflict-2,1050.0,0.768671,3.818766e-01,0.0027,1.000000e+00
Frac_Learnt_from_Loop-2,1050.0,0.231329,3.818766e-01,0.0000,9.973000e-01
Literals_in_Conflict_Nogoods-2,1050.0,2492.878095,5.240965e+03,64.0000,5.612800e+04
Literals_in_Loop_Nogoods-2,1050.0,235623.312381,1.155271e+06,0.0000,1.377323e+07
Frac_Literals_in_Conflict_Nogoods-2,1050.0,0.763555,3.809709e-01,0.0001,1.000000e+00
Frac_Literals_in_Loop_Nogoods-2,1050.0,0.236445,3.809709e-01,0.0000,9.999000e-01
Removed_Nogoods-2,1050.0,0.000000,0.000000e+00,0.0000,0.000000e+00
Learnt_Binary-2,1050.0,7.735238,2.004790e+01,0.0000,3.660000e+02
Learnt_Ternary-2,1050.0,14.144762,5.169449e+01,0.0000,8.660000e+02
Learnt_Others-2,1050.0,705.802857,1.892646e+03,1.0000,2.321800e+04
Frac_Learnt_Binary-2,1050.0,0.069224,9.538804e-02,0.0000,8.438000e-01
Frac_Learnt_Ternary-2,1050.0,0.109961,1.469284e-01,0.0000,8.906000e-01
Frac_Learnt_Others-2,1050.0,0.820816,1.996126e-01,0.0156,1.000000e+00
Skipped_Levels_while_Backjumping-2,1050.0,1049.418095,3.007529e+03,59.0000,5.101100e+04
Avg_Skipped_Levels_while_Backjumping-2,1050.0,16.269688,4.639986e+01,1.0000,7.728939e+02
Longest_Backjumping-2,1050.0,252.660000,7.824534e+02,1.0000,7.791000e+03
Running_Avg_Conflictlevel-2,1050.0,113.240600,3.026798e+02,0.6400,2.207590e+03
Running_Avg_LBD-2,1050.0,4.911648,5.932247e+00,0.6400,5.704000e+01
Choices-3,1021.0,2241.127326,5.844434e+03,78.0000,6.222200e+04
Conflicts/Choices-3,1021.0,0.233292,1.892397e-01,0.0015,1.000000e+00
Avg_Conflict_Levels-3,1021.0,173.210126,4.706452e+02,1.0000,4.430521e+03
Avg_LBD_Levels-3,1021.0,7.538167,8.917266e+00,1.0000,8.828120e+01
Learnt_from_Conflict-3,1021.0,96.809011,2.405011e+00,68.0000,1.030000e+02
Learnt_from_Loop-3,1021.0,767.178257,2.331887e+03,0.0000,3.194200e+04
Frac_Learnt_from_Conflict-3,1021.0,0.763887,3.794317e-01,0.0030,1.000000e+00
Frac_Learnt_from_Loop-3,1021.0,0.236113,3.794317e-01,0.0000,9.970000e-01
Literals_in_Conflict_Nogoods-3,1021.0,3341.213516,6.406811e+03,96.0000,7.130100e+04
Literals_in_Loop_Nogoods-3,1021.0,252425.222331,1.202904e+06,0.0000,1.527644e+07
Frac_Literals_in_Conflict_Nogoods-3,1021.0,0.753005,3.832331e-01,0.0001,1.000000e+00
Frac_Literals_in_Loop_Nogoods-3,1021.0,0.246995,3.832331e-01,0.0000,9.999000e-01
Removed_Nogoods-3,1021.0,0.059745,1.909049e+00,0.0000,6.100000e+01
Learnt_Binary-3,1021.0,12.933399,3.795781e+01,0.0000,6.970000e+02
Learnt_Ternary-3,1021.0,21.274241,6.051933e+01,0.0000,9.220000e+02
Learnt_Others-3,1021.0,829.779628,2.295428e+03,4.0000,3.167000e+04
Frac_Removed_Nogood-3,1021.0,0.000622,1.988540e-02,0.0000,6.354000e-01
Frac_Learnt_Binary-3,1021.0,0.072408,9.522277e-02,0.0000,7.708000e-01
Frac_Learnt_Ternary-3,1021.0,0.113244,1.465001e-01,0.0000,8.229000e-01
Frac_Learnt_Others-3,1021.0,0.814345,1.971773e-01,0.0417,1.000000e+00
Skipped_Levels_while_Backjumping-3,1021.0,1741.630754,4.646756e+03,76.0000,5.151100e+04
Avg_Skipped_Levels_while_Backjumping-3,1021.0,18.025124,4.810599e+01,1.0000,5.256224e+02
Longest_Backjumping-3,1021.0,288.826641,8.326002e+02,1.0000,7.791000e+03
Running_Avg_Conflictlevel-3,1021.0,167.608335,4.552534e+02,0.9600,4.253300e+03
Running_Avg_LBD-3,1021.0,7.322703,8.714604e+00,0.9600,8.475000e+01
Choices-4,994.0,2927.598592,7.577984e+03,128.0000,9.111000e+04
Conflicts/Choices-4,994.0,0.227682,1.847755e-01,0.0014,1.000000e+00
Avg_Conflict_Levels-4,994.0,159.829770,4.372118e+02,1.0000,5.329969e+03
Avg_LBD_Levels-4,994.0,7.404050,8.650564e+00,1.0000,8.417190e+01
Learnt_from_Conflict-4,994.0,129.307847,1.493793e+00,120.0000,1.360000e+02
Learnt_from_Loop-4,994.0,877.536217,2.753590e+03,0.0000,3.607400e+04
Frac_Learnt_from_Conflict-4,994.0,0.760164,3.783191e-01,0.0035,1.000000e+00
Frac_Learnt_from_Loop-4,994.0,0.239836,3.783191e-01,0.0000,9.965000e-01
Literals_in_Conflict_Nogoods-4,994.0,4223.825956,7.649217e+03,128.0000,7.377400e+04
Literals_in_Loop_Nogoods-4,994.0,267055.391348,1.254877e+06,0.0000,1.636067e+07
Frac_Literals_in_Conflict_Nogoods-4,994.0,0.746643,3.855295e-01,0.0001,1.000000e+00
Frac_Literals_in_Loop_Nogoods-4,994.0,0.253357,3.855295e-01,0.0000,9.999000e-01
Removed_Nogoods-4,994.0,1.354125,1.098701e+01,0.0000,9.300000e+01
Learnt_Binary-4,994.0,16.538229,3.986133e+01,0.0000,7.100000e+02
Learnt_Ternary-4,994.0,27.330986,6.751820e+01,0.0000,1.058000e+03
Learnt_Others-4,994.0,962.974849,2.714153e+03,6.0000,3.582800e+04
Frac_Removed_Nogood-4,994.0,0.010480,8.502001e-02,0.0000,7.266000e-01
Frac_Learnt_Binary-4,994.0,0.071135,9.246781e-02,0.0000,7.734000e-01
Frac_Learnt_Ternary-4,994.0,0.114890,1.483484e-01,0.0000,8.047000e-01
Frac_Learnt_Others-4,994.0,0.813977,1.954882e-01,0.0469,1.000000e+00
Skipped_Levels_while_Backjumping-4,994.0,2320.392354,6.071708e+03,128.0000,7.820000e+04
Avg_Skipped_Levels_while_Backjumping-4,994.0,18.010377,4.719944e+01,1.0000,6.109375e+02
Longest_Backjumping-4,994.0,303.477867,8.469877e+02,1.0000,7.791000e+03
Running_Avg_Conflictlevel-4,994.0,167.291590,4.808514e+02,1.0000,6.255770e+03
Running_Avg_LBD-4,994.0,7.318954,8.893948e+00,1.0000,8.285000e+01

In [7]:
# Categorical Feature Statistics
cat_stats

                             value  count    pct
column    rank
algorithm 1      clasp/2.1.3/h1-n1    240  19.80
          2     clasp/2.1.3/h10-n1    176  14.52
          3      clasp/2.1.3/h6-n1    151  12.46
          4      clasp/2.1.3/h4-n1    125  10.31
          5      clasp/2.1.3/h8-n1    109   8.99
task_id   1           81728f2574c3    134  11.06
          2           8f6a79c51a4b     89   7.34
          3           00cf7b166f3c     74   6.11
          4           e57bbf07e3ce     67   5.53
          5           fd0e9d0851f7     59   4.87

In [8]:
# Target Distribution
target_df

                    count    pct
algorithm
clasp/2.1.3/h1-n1     240  19.80
clasp/2.1.3/h10-n1    176  14.52
clasp/2.1.3/h6-n1     151  12.46
clasp/2.1.3/h4-n1     125  10.31
clasp/2.1.3/h8-n1     109   8.99
clasp/2.1.3/h7-n1      88   7.26
clasp/2.1.3/h2-n1      87   7.18
clasp/2.1.3/h11-n1     75   6.19
clasp/2.1.3/h9-n1      75   6.19
clasp/2.1.3/h5-n1      65   5.36
clasp/2.1.3/h3-n1      21   1.73

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
    group_labels=task_mold.group_labels,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=10, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

# -- For Grouped Non-IID data
splits = curation_recommendations.get_recommended_grouped_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    group_on=task_mold.group_on,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
    group_labels=task_mold.group_labels,
    show_splits=True,
    target_on=task_mold.target_column_name,
)


splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified Grouped splits.
Using label-per-sample grouped splits.

Repeat 0, Fold 0:
            Train N: 733, Test N: 479
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h1-n1': 0.28512960436562074, 'clasp/2.1.3/h4-n1': 0.1296043656207367, 'clasp/2.1.3/h10-n1': 0.10641200545702592, 'clasp/2.1.3/h2-n1': 0.08594815825375171, 'clasp/2.1.3/h6-n1': 0.08321964529331514, 'clasp/2.1.3/h7-n1': 0.0791268758526603, 'clasp/2.1.3/h11-n1': 0.06957708049113233, 'clasp/2.1.3/h5-n1': 0.058663028649386086, 'clasp/2.1.3/h8-n1': 0.047748976807639835, 'clasp/2.1.3/h9-n1': 0.04229195088676671, 'clasp/2.1.3/h3-n1': 0.01227830832196453}
            	Test target distribution: {'clasp/2.1.3/h10-n1': 0.2045929018789144, 'clasp/2.1.3/h6-n1': 0.18789144050104384, 'clasp/2.1.3/h8-n1': 0.1544885177453027, 'clasp/2.1.3/h9-n1': 0.0918580375782881, 'clasp/2.1.3/h1-n1': 0.06471816283924843, 'clasp/2.1.3/h7-n1': 0.06263048016701461, 'clasp/2.1.3/h4-n1': 0.06263048016701461, 'clasp/2.1.3/h11-n1': 0.05010438413361169, 'clasp/2.1.3/h2-n1': 0.05010438413361169, 'clasp/2.1.3/h5-n1': 0.04592901878914405, 'clasp/2.1.3/h3-n1': 0.025052192066805846}
            Group Distribution task_id:
            	Train: 66
            	Test: 30

Repeat 0, Fold 1:
            Train N: 815, Test N: 397
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h1-n1': 0.2134969325153374, 'clasp/2.1.3/h10-n1': 0.16932515337423312, 'clasp/2.1.3/h6-n1': 0.13865030674846626, 'clasp/2.1.3/h8-n1': 0.11411042944785275, 'clasp/2.1.3/h4-n1': 0.07484662576687116, 'clasp/2.1.3/h9-n1': 0.06257668711656442, 'clasp/2.1.3/h11-n1': 0.06134969325153374, 'clasp/2.1.3/h2-n1': 0.05276073619631902, 'clasp/2.1.3/h7-n1': 0.05276073619631902, 'clasp/2.1.3/h5-n1': 0.04049079754601227, 'clasp/2.1.3/h3-n1': 0.0196319018404908}
            	Test target distribution: {'clasp/2.1.3/h1-n1': 0.16624685138539042, 'clasp/2.1.3/h4-n1': 0.16120906801007556, 'clasp/2.1.3/h7-n1': 0.11335012594458438, 'clasp/2.1.3/h2-n1': 0.11083123425692695, 'clasp/2.1.3/h10-n1': 0.09571788413098237, 'clasp/2.1.3/h6-n1': 0.09571788413098237, 'clasp/2.1.3/h5-n1': 0.08060453400503778, 'clasp/2.1.3/h11-n1': 0.06297229219143577, 'clasp/2.1.3/h9-n1': 0.060453400503778336, 'clasp/2.1.3/h8-n1': 0.04030226700251889, 'clasp/2.1.3/h3-n1': 0.012594458438287154}
            Group Distribution task_id:
            	Train: 61
            	Test: 35

Repeat 0, Fold 2:
            Train N: 876, Test N: 336
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h10-n1': 0.1552511415525114, 'clasp/2.1.3/h6-n1': 0.1461187214611872, 'clasp/2.1.3/h1-n1': 0.11073059360730593, 'clasp/2.1.3/h4-n1': 0.10730593607305935, 'clasp/2.1.3/h8-n1': 0.10273972602739725, 'clasp/2.1.3/h7-n1': 0.08561643835616438, 'clasp/2.1.3/h2-n1': 0.0776255707762557, 'clasp/2.1.3/h9-n1': 0.0776255707762557, 'clasp/2.1.3/h5-n1': 0.06164383561643835, 'clasp/2.1.3/h11-n1': 0.05593607305936073, 'clasp/2.1.3/h3-n1': 0.019406392694063926}
            	Test target distribution: {'clasp/2.1.3/h1-n1': 0.4255952380952381, 'clasp/2.1.3/h10-n1': 0.11904761904761904, 'clasp/2.1.3/h4-n1': 0.09226190476190477, 'clasp/2.1.3/h11-n1': 0.07738095238095238, 'clasp/2.1.3/h6-n1': 0.06845238095238096, 'clasp/2.1.3/h8-n1': 0.05654761904761905, 'clasp/2.1.3/h2-n1': 0.05654761904761905, 'clasp/2.1.3/h7-n1': 0.03869047619047619, 'clasp/2.1.3/h5-n1': 0.03273809523809524, 'clasp/2.1.3/h9-n1': 0.020833333333333332, 'clasp/2.1.3/h3-n1': 0.011904761904761904}
            Group Distribution task_id:
            	Train: 65
            	Test: 31

Repeat 1, Fold 0:
            Train N: 843, Test N: 369
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h10-n1': 0.17793594306049823, 'clasp/2.1.3/h1-n1': 0.1376037959667853, 'clasp/2.1.3/h6-n1': 0.11269276393831554, 'clasp/2.1.3/h4-n1': 0.099644128113879, 'clasp/2.1.3/h8-n1': 0.09252669039145907, 'clasp/2.1.3/h7-n1': 0.08659549228944247, 'clasp/2.1.3/h9-n1': 0.08066429418742586, 'clasp/2.1.3/h2-n1': 0.06761565836298933, 'clasp/2.1.3/h11-n1': 0.06405693950177936, 'clasp/2.1.3/h5-n1': 0.05931198102016608, 'clasp/2.1.3/h3-n1': 0.021352313167259787}
            	Test target distribution: {'clasp/2.1.3/h1-n1': 0.33604336043360433, 'clasp/2.1.3/h6-n1': 0.15176151761517614, 'clasp/2.1.3/h4-n1': 0.1111111111111111, 'clasp/2.1.3/h8-n1': 0.08401084010840108, 'clasp/2.1.3/h2-n1': 0.08130081300813008, 'clasp/2.1.3/h10-n1': 0.07046070460704607, 'clasp/2.1.3/h11-n1': 0.056910569105691054, 'clasp/2.1.3/h7-n1': 0.04065040650406504, 'clasp/2.1.3/h5-n1': 0.04065040650406504, 'clasp/2.1.3/h9-n1': 0.018970189701897018, 'clasp/2.1.3/h3-n1': 0.008130081300813009}
            Group Distribution task_id:
            	Train: 67
            	Test: 29

Repeat 1, Fold 1:
            Train N: 769, Test N: 443
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h1-n1': 0.22106631989596878, 'clasp/2.1.3/h10-n1': 0.13003901170351106, 'clasp/2.1.3/h4-n1': 0.13003901170351106, 'clasp/2.1.3/h6-n1': 0.13003901170351106, 'clasp/2.1.3/h7-n1': 0.08322496749024708, 'clasp/2.1.3/h2-n1': 0.07672301690507152, 'clasp/2.1.3/h8-n1': 0.07022106631989597, 'clasp/2.1.3/h5-n1': 0.05721716514954486, 'clasp/2.1.3/h11-n1': 0.053315994798439535, 'clasp/2.1.3/h9-n1': 0.04031209362808843, 'clasp/2.1.3/h3-n1': 0.007802340702210663}
            	Test target distribution: {'clasp/2.1.3/h10-n1': 0.17155756207674944, 'clasp/2.1.3/h1-n1': 0.1580135440180587, 'clasp/2.1.3/h8-n1': 0.12415349887133183, 'clasp/2.1.3/h6-n1': 0.11512415349887133, 'clasp/2.1.3/h9-n1': 0.09932279909706546, 'clasp/2.1.3/h11-n1': 0.07674943566591422, 'clasp/2.1.3/h2-n1': 0.06320541760722348, 'clasp/2.1.3/h4-n1': 0.056433408577878104, 'clasp/2.1.3/h7-n1': 0.05417607223476298, 'clasp/2.1.3/h5-n1': 0.04740406320541761, 'clasp/2.1.3/h3-n1': 0.033860045146726865}
            Group Distribution task_id:
            	Train: 60
            	Test: 36

Repeat 1, Fold 2:
            Train N: 812, Test N: 400
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h1-n1': 0.23891625615763548, 'clasp/2.1.3/h6-n1': 0.13177339901477833, 'clasp/2.1.3/h10-n1': 0.12561576354679804, 'clasp/2.1.3/h8-n1': 0.10591133004926108, 'clasp/2.1.3/h4-n1': 0.0812807881773399, 'clasp/2.1.3/h2-n1': 0.07142857142857142, 'clasp/2.1.3/h11-n1': 0.06773399014778325, 'clasp/2.1.3/h9-n1': 0.06280788177339902, 'clasp/2.1.3/h7-n1': 0.0480295566502463, 'clasp/2.1.3/h5-n1': 0.04433497536945813, 'clasp/2.1.3/h3-n1': 0.022167487684729065}
            	Test target distribution: {'clasp/2.1.3/h10-n1': 0.185, 'clasp/2.1.3/h4-n1': 0.1475, 'clasp/2.1.3/h7-n1': 0.1225, 'clasp/2.1.3/h1-n1': 0.115, 'clasp/2.1.3/h6-n1': 0.11, 'clasp/2.1.3/h5-n1': 0.0725, 'clasp/2.1.3/h2-n1': 0.0725, 'clasp/2.1.3/h9-n1': 0.06, 'clasp/2.1.3/h8-n1': 0.0575, 'clasp/2.1.3/h11-n1': 0.05, 'clasp/2.1.3/h3-n1': 0.0075}
            Group Distribution task_id:
            	Train: 65
            	Test: 31

Repeat 2, Fold 0:
            Train N: 844, Test N: 368
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h10-n1': 0.1646919431279621, 'clasp/2.1.3/h1-n1': 0.15639810426540285, 'clasp/2.1.3/h6-n1': 0.1066350710900474, 'clasp/2.1.3/h8-n1': 0.09123222748815166, 'clasp/2.1.3/h2-n1': 0.08767772511848342, 'clasp/2.1.3/h7-n1': 0.08767772511848342, 'clasp/2.1.3/h4-n1': 0.08530805687203792, 'clasp/2.1.3/h11-n1': 0.07345971563981042, 'clasp/2.1.3/h9-n1': 0.06635071090047394, 'clasp/2.1.3/h5-n1': 0.058056872037914695, 'clasp/2.1.3/h3-n1': 0.022511848341232227}
            	Test target distribution: {'clasp/2.1.3/h1-n1': 0.29347826086956524, 'clasp/2.1.3/h6-n1': 0.16576086956521738, 'clasp/2.1.3/h4-n1': 0.14402173913043478, 'clasp/2.1.3/h10-n1': 0.10054347826086957, 'clasp/2.1.3/h8-n1': 0.08695652173913043, 'clasp/2.1.3/h9-n1': 0.051630434782608696, 'clasp/2.1.3/h5-n1': 0.043478260869565216, 'clasp/2.1.3/h7-n1': 0.03804347826086957, 'clasp/2.1.3/h11-n1': 0.035326086956521736, 'clasp/2.1.3/h2-n1': 0.035326086956521736, 'clasp/2.1.3/h3-n1': 0.005434782608695652}
            Group Distribution task_id:
            	Train: 67
            	Test: 29

Repeat 2, Fold 1:
            Train N: 770, Test N: 442
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h1-n1': 0.22207792207792207, 'clasp/2.1.3/h10-n1': 0.14285714285714285, 'clasp/2.1.3/h6-n1': 0.12467532467532468, 'clasp/2.1.3/h4-n1': 0.11948051948051948, 'clasp/2.1.3/h8-n1': 0.07792207792207792, 'clasp/2.1.3/h2-n1': 0.07012987012987013, 'clasp/2.1.3/h7-n1': 0.06883116883116883, 'clasp/2.1.3/h11-n1': 0.05714285714285714, 'clasp/2.1.3/h5-n1': 0.05454545454545454, 'clasp/2.1.3/h9-n1': 0.05194805194805195, 'clasp/2.1.3/h3-n1': 0.01038961038961039}
            	Test target distribution: {'clasp/2.1.3/h1-n1': 0.15610859728506787, 'clasp/2.1.3/h10-n1': 0.1493212669683258, 'clasp/2.1.3/h6-n1': 0.1244343891402715, 'clasp/2.1.3/h8-n1': 0.11085972850678733, 'clasp/2.1.3/h9-n1': 0.07918552036199095, 'clasp/2.1.3/h7-n1': 0.07918552036199095, 'clasp/2.1.3/h4-n1': 0.0746606334841629, 'clasp/2.1.3/h2-n1': 0.0746606334841629, 'clasp/2.1.3/h11-n1': 0.07013574660633484, 'clasp/2.1.3/h5-n1': 0.05203619909502263, 'clasp/2.1.3/h3-n1': 0.029411764705882353}
            Group Distribution task_id:
            	Train: 61
            	Test: 35

Repeat 2, Fold 2:
            Train N: 810, Test N: 402
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h1-n1': 0.21851851851851853, 'clasp/2.1.3/h6-n1': 0.14320987654320988, 'clasp/2.1.3/h10-n1': 0.1271604938271605, 'clasp/2.1.3/h4-n1': 0.10617283950617284, 'clasp/2.1.3/h8-n1': 0.1, 'clasp/2.1.3/h9-n1': 0.06666666666666667, 'clasp/2.1.3/h7-n1': 0.06049382716049383, 'clasp/2.1.3/h2-n1': 0.056790123456790124, 'clasp/2.1.3/h11-n1': 0.05432098765432099, 'clasp/2.1.3/h5-n1': 0.04814814814814815, 'clasp/2.1.3/h3-n1': 0.018518518518518517}
            	Test target distribution: {'clasp/2.1.3/h10-n1': 0.18159203980099503, 'clasp/2.1.3/h1-n1': 0.15671641791044777, 'clasp/2.1.3/h2-n1': 0.10199004975124377, 'clasp/2.1.3/h7-n1': 0.09701492537313433, 'clasp/2.1.3/h4-n1': 0.09701492537313433, 'clasp/2.1.3/h6-n1': 0.08706467661691543, 'clasp/2.1.3/h11-n1': 0.07711442786069651, 'clasp/2.1.3/h8-n1': 0.06965174129353234, 'clasp/2.1.3/h5-n1': 0.06467661691542288, 'clasp/2.1.3/h9-n1': 0.05223880597014925, 'clasp/2.1.3/h3-n1': 0.014925373134328358}
            Group Distribution task_id:
            	Train: 64
            	Test: 32

Repeat 3, Fold 0:
            Train N: 1003, Test N: 209
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h1-n1': 0.2033898305084746, 'clasp/2.1.3/h10-n1': 0.14556331006979062, 'clasp/2.1.3/h6-n1': 0.13958125623130607, 'clasp/2.1.3/h4-n1': 0.09770687936191426, 'clasp/2.1.3/h8-n1': 0.09272183449651047, 'clasp/2.1.3/h7-n1': 0.0707876370887338, 'clasp/2.1.3/h2-n1': 0.06779661016949153, 'clasp/2.1.3/h9-n1': 0.05782652043868395, 'clasp/2.1.3/h11-n1': 0.05583250249252243, 'clasp/2.1.3/h5-n1': 0.0518444666001994, 'clasp/2.1.3/h3-n1': 0.01694915254237288}
            	Test target distribution: {'clasp/2.1.3/h1-n1': 0.1722488038277512, 'clasp/2.1.3/h10-n1': 0.14354066985645933, 'clasp/2.1.3/h4-n1': 0.1291866028708134, 'clasp/2.1.3/h11-n1': 0.09090909090909091, 'clasp/2.1.3/h2-n1': 0.09090909090909091, 'clasp/2.1.3/h9-n1': 0.08133971291866028, 'clasp/2.1.3/h7-n1': 0.08133971291866028, 'clasp/2.1.3/h8-n1': 0.07655502392344497, 'clasp/2.1.3/h5-n1': 0.06220095693779904, 'clasp/2.1.3/h6-n1': 0.05263157894736842, 'clasp/2.1.3/h3-n1': 0.019138755980861243}
            Group Distribution task_id:
            	Train: 67
            	Test: 29

Repeat 3, Fold 1:
            Train N: 668, Test N: 544
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h10-n1': 0.18413173652694612, 'clasp/2.1.3/h6-n1': 0.16467065868263472, 'clasp/2.1.3/h8-n1': 0.14520958083832336, 'clasp/2.1.3/h4-n1': 0.1122754491017964, 'clasp/2.1.3/h1-n1': 0.08832335329341318, 'clasp/2.1.3/h2-n1': 0.08233532934131736, 'clasp/2.1.3/h11-n1': 0.06437125748502993, 'clasp/2.1.3/h7-n1': 0.061377245508982034, 'clasp/2.1.3/h5-n1': 0.04790419161676647, 'clasp/2.1.3/h9-n1': 0.038922155688622756, 'clasp/2.1.3/h3-n1': 0.010479041916167664}
            	Test target distribution: {'clasp/2.1.3/h1-n1': 0.3327205882352941, 'clasp/2.1.3/h10-n1': 0.0974264705882353, 'clasp/2.1.3/h4-n1': 0.09191176470588236, 'clasp/2.1.3/h9-n1': 0.0900735294117647, 'clasp/2.1.3/h7-n1': 0.08639705882352941, 'clasp/2.1.3/h6-n1': 0.07536764705882353, 'clasp/2.1.3/h5-n1': 0.06066176470588235, 'clasp/2.1.3/h11-n1': 0.058823529411764705, 'clasp/2.1.3/h2-n1': 0.058823529411764705, 'clasp/2.1.3/h3-n1': 0.025735294117647058, 'clasp/2.1.3/h8-n1': 0.022058823529411766}
            Group Distribution task_id:
            	Train: 60
            	Test: 36

Repeat 3, Fold 2:
            Train N: 753, Test N: 459
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h1-n1': 0.28818061088977426, 'clasp/2.1.3/h10-n1': 0.1102257636122178, 'clasp/2.1.3/h4-n1': 0.10225763612217796, 'clasp/2.1.3/h9-n1': 0.08764940239043825, 'clasp/2.1.3/h7-n1': 0.0849933598937583, 'clasp/2.1.3/h6-n1': 0.06905710491367861, 'clasp/2.1.3/h11-n1': 0.06772908366533864, 'clasp/2.1.3/h2-n1': 0.06772908366533864, 'clasp/2.1.3/h5-n1': 0.06108897742363878, 'clasp/2.1.3/h8-n1': 0.03718459495351926, 'clasp/2.1.3/h3-n1': 0.02390438247011952}
            	Test target distribution: {'clasp/2.1.3/h6-n1': 0.21568627450980393, 'clasp/2.1.3/h10-n1': 0.20261437908496732, 'clasp/2.1.3/h8-n1': 0.17647058823529413, 'clasp/2.1.3/h4-n1': 0.10457516339869281, 'clasp/2.1.3/h2-n1': 0.0784313725490196, 'clasp/2.1.3/h7-n1': 0.05228758169934641, 'clasp/2.1.3/h11-n1': 0.05228758169934641, 'clasp/2.1.3/h1-n1': 0.05010893246187364, 'clasp/2.1.3/h5-n1': 0.04139433551198257, 'clasp/2.1.3/h9-n1': 0.0196078431372549, 'clasp/2.1.3/h3-n1': 0.006535947712418301}
            Group Distribution task_id:
            	Train: 65
            	Test: 31

Repeat 4, Fold 0:
            Train N: 755, Test N: 457
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h1-n1': 0.20132450331125828, 'clasp/2.1.3/h10-n1': 0.14437086092715232, 'clasp/2.1.3/h6-n1': 0.13642384105960265, 'clasp/2.1.3/h4-n1': 0.11258278145695365, 'clasp/2.1.3/h8-n1': 0.10728476821192053, 'clasp/2.1.3/h9-n1': 0.06357615894039735, 'clasp/2.1.3/h2-n1': 0.05562913907284768, 'clasp/2.1.3/h7-n1': 0.05562913907284768, 'clasp/2.1.3/h11-n1': 0.054304635761589407, 'clasp/2.1.3/h5-n1': 0.04370860927152318, 'clasp/2.1.3/h3-n1': 0.025165562913907286}
            	Test target distribution: {'clasp/2.1.3/h1-n1': 0.1925601750547046, 'clasp/2.1.3/h10-n1': 0.14660831509846828, 'clasp/2.1.3/h6-n1': 0.1050328227571116, 'clasp/2.1.3/h7-n1': 0.10065645514223195, 'clasp/2.1.3/h2-n1': 0.09846827133479212, 'clasp/2.1.3/h4-n1': 0.087527352297593, 'clasp/2.1.3/h11-n1': 0.07439824945295405, 'clasp/2.1.3/h5-n1': 0.0700218818380744, 'clasp/2.1.3/h8-n1': 0.061269146608315096, 'clasp/2.1.3/h9-n1': 0.05908096280087528, 'clasp/2.1.3/h3-n1': 0.00437636761487965}
            Group Distribution task_id:
            	Train: 64
            	Test: 32

Repeat 4, Fold 1:
            Train N: 648, Test N: 564
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h1-n1': 0.16666666666666666, 'clasp/2.1.3/h10-n1': 0.14814814814814814, 'clasp/2.1.3/h6-n1': 0.10648148148148148, 'clasp/2.1.3/h7-n1': 0.09259259259259259, 'clasp/2.1.3/h2-n1': 0.09259259259259259, 'clasp/2.1.3/h4-n1': 0.09259259259259259, 'clasp/2.1.3/h11-n1': 0.0787037037037037, 'clasp/2.1.3/h9-n1': 0.0787037037037037, 'clasp/2.1.3/h8-n1': 0.06944444444444445, 'clasp/2.1.3/h5-n1': 0.06172839506172839, 'clasp/2.1.3/h3-n1': 0.012345679012345678}
            	Test target distribution: {'clasp/2.1.3/h1-n1': 0.23404255319148937, 'clasp/2.1.3/h6-n1': 0.1453900709219858, 'clasp/2.1.3/h10-n1': 0.14184397163120568, 'clasp/2.1.3/h4-n1': 0.11524822695035461, 'clasp/2.1.3/h8-n1': 0.11347517730496454, 'clasp/2.1.3/h7-n1': 0.04964539007092199, 'clasp/2.1.3/h2-n1': 0.047872340425531915, 'clasp/2.1.3/h5-n1': 0.044326241134751775, 'clasp/2.1.3/h11-n1': 0.0425531914893617, 'clasp/2.1.3/h9-n1': 0.0425531914893617, 'clasp/2.1.3/h3-n1': 0.02304964539007092}
            Group Distribution task_id:
            	Train: 61
            	Test: 35

Repeat 4, Fold 2:
            Train N: 1021, Test N: 191
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h1-n1': 0.21547502448579825, 'clasp/2.1.3/h10-n1': 0.14397649363369247, 'clasp/2.1.3/h6-n1': 0.12732615083251714, 'clasp/2.1.3/h4-n1': 0.10284035259549461, 'clasp/2.1.3/h8-n1': 0.0901077375122429, 'clasp/2.1.3/h7-n1': 0.07247796278158668, 'clasp/2.1.3/h2-n1': 0.07051909892262488, 'clasp/2.1.3/h11-n1': 0.05680705190989226, 'clasp/2.1.3/h5-n1': 0.05582761998041136, 'clasp/2.1.3/h9-n1': 0.04995102840352596, 'clasp/2.1.3/h3-n1': 0.014691478942213516}
            	Test target distribution: {'clasp/2.1.3/h10-n1': 0.1518324607329843, 'clasp/2.1.3/h9-n1': 0.1256544502617801, 'clasp/2.1.3/h6-n1': 0.1099476439790576, 'clasp/2.1.3/h4-n1': 0.10471204188481675, 'clasp/2.1.3/h1-n1': 0.10471204188481675, 'clasp/2.1.3/h11-n1': 0.08900523560209424, 'clasp/2.1.3/h8-n1': 0.08900523560209424, 'clasp/2.1.3/h2-n1': 0.07853403141361257, 'clasp/2.1.3/h7-n1': 0.07329842931937172, 'clasp/2.1.3/h5-n1': 0.041884816753926704, 'clasp/2.1.3/h3-n1': 0.031413612565445025}
            Group Distribution task_id:
            	Train: 67
            	Test: 29

Repeat 5, Fold 0:
            Train N: 918, Test N: 294
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h1-n1': 0.2374727668845316, 'clasp/2.1.3/h10-n1': 0.1394335511982571, 'clasp/2.1.3/h4-n1': 0.09912854030501089, 'clasp/2.1.3/h6-n1': 0.09041394335511982, 'clasp/2.1.3/h7-n1': 0.08387799564270153, 'clasp/2.1.3/h9-n1': 0.07080610021786492, 'clasp/2.1.3/h2-n1': 0.07080610021786492, 'clasp/2.1.3/h8-n1': 0.06753812636165578, 'clasp/2.1.3/h11-n1': 0.06209150326797386, 'clasp/2.1.3/h5-n1': 0.05664488017429194, 'clasp/2.1.3/h3-n1': 0.02178649237472767}
            	Test target distribution: {'clasp/2.1.3/h6-n1': 0.23129251700680273, 'clasp/2.1.3/h10-n1': 0.16326530612244897, 'clasp/2.1.3/h8-n1': 0.1598639455782313, 'clasp/2.1.3/h4-n1': 0.11564625850340136, 'clasp/2.1.3/h1-n1': 0.07482993197278912, 'clasp/2.1.3/h2-n1': 0.07482993197278912, 'clasp/2.1.3/h11-n1': 0.061224489795918366, 'clasp/2.1.3/h5-n1': 0.04421768707482993, 'clasp/2.1.3/h7-n1': 0.03741496598639456, 'clasp/2.1.3/h9-n1': 0.034013605442176874, 'clasp/2.1.3/h3-n1': 0.003401360544217687}
            Group Distribution task_id:
            	Train: 68
            	Test: 28

Repeat 5, Fold 1:
            Train N: 701, Test N: 511
            Target Distribution:
            	Train target distribution: {'clasp/2.1.3/h10-n1': 0.15691868758915833, 'clasp/2.1.3/h6-n1': 0.14407988587731813, 'clasp/2.1.3/h1-n1': 0.1340941512125535, 'clasp/2.1.3/h4-n1': 0.1312410841654779, 'clasp/2.1.3/h2-n1': 0.0884450784593438, 'clasp/2.1.3/h8-n1': 0.08416547788873038, 'clasp/2.1.3/h7-n1': 0.07845934379457917, 'clasp/2.1.3/h11-n1': 0.06419400855920114, 'clasp/2.1.3/h5-n1': 0.05706134094151213, 'clasp/2.1.3/h9-n1': 0.052781740370898715, 'clasp/2.1.3/h3-n1': 0.008559201141226819}
            	Test target distribution: {'clasp/2.1.3/h1-n1': 0.2857142857142857, 'clasp/2.1.3/h10-n1': 0.12915851272015655, 'clasp/2.1.3/h8-n1': 0.09784735812133072, 'clasp/2.1.3/h6-n1': 0.09784735812133072, 'clasp/2.1.3/h9-n1': 0.07436399217221135, 'clasp/2.1.3/h7-n1': 0.06457925636007827, 'clasp/2.1.3/h4-n1': 0.06457925636007827, 'clasp/2.1.3/h11-n1': 0.05870841487279843, 'clasp/2.1.3/h2-n1': 0.04892367906066536, 'clasp/2.1.3/h5-n1': 0.04892367906066536, 'clasp/2.1.3/h3-n1': 0.029354207436399216}
            Group Distribution task_id:
            	Train: 61
            	Test: 35

Repeat 5, Fold 2:

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to asp_potassco_classification/019d73d2-fce7-7f07-82e1-4882cb552f37

019d73d2-fce7-7f07-82e1-4882cb552f37
cd9153b1d99e94e64e1e12fb527a8093abe5128feb79eede723de6e4b3b1694f