### Dataset and Task Metadata

In [11]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="maps_router_eta",
    dataset_year="2024",
    domain_str="industry & manufacturing",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/datasets/pcovkrd84mejm/maps-routing",
    download_description="""
We get the TabRed data from Kaggle.

kaggle datasets download -d pcovkrd84mejm/maps-routing -f maps_routing.parquet && unzip maps_routing.parquet.zip && rm maps_routing.parquet.zip && mkdir -p local-data-warehouse/maps_router_eta && mv maps_routing.parquet local-data-warehouse/maps_router_eta/
""",
    # References
    academic_reference_bibtex="""@inproceedings{rubachev2025tabred,
  title={TabReD: Analyzing Pitfalls and Filling the Gaps in Tabular Deep Learning Benchmarks},
  author={Rubachev, Ivan and Kartashev, Nikolay and Gorishniy, Yury and Babenko, Artem},
  booktitle={The Thirteenth International Conference on Learning Representations},
  year={2025},
}
""",
    academic_reference_bibtex_key="rubachev2025tabred",
    license="CC-BY-NC-SA-4.0",
    data_tags=["Non-IID", "Temporal", "Anonymized"],
    curation_comments="""
We start with data from TabRed, which already comes preprocessed.
We perform no additional preprocessing steps.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="target_log_spkm",
    problem_type="regression",
    objective_metric_name="rmse",
    time_on="timestamp",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_parquet(dataset_mold.path / "maps_routing.parquet")
print("Loaded data shape:", df.shape)

df["timestamp"] = pd.to_datetime(df["timestamp"])

# We take all bin + cat as Category
cat_cols = [c for c in df.columns if c.startswith("cat") or c.startswith("bin")]
df[cat_cols] = df[cat_cols].astype("category")

df = df.sort_values(by="timestamp").reset_index(drop=True)

Loaded data shape: (13639272, 989)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 13,639,272
Columns: 989
Use sampling: True (sample size: 1,363,927)
Get missing and unique counts per column...

missing/unique per-col:   0%|          | 0/989 [00:00<?, ?it/s]

Get example values per column...

examples per-col:   0%|          | 0/989 [00:00<?, ?it/s]

Get numeric feature statistics...

numeric stats:   0%|          | 0/986 [00:00<?, ?it/s]

Get cat stats...

cat stats:   0%|          | 0/3 [00:00<?, ?it/s]

Get target stats...
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['track_length', 'num_15', 'num_88', 'num_20', 'num_11', 'num_448', 'num_339', 'num_557', 'num_38', 'num_41']
Rows remaining as candidates after top-10 filter: 156 (of 13,639,272)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 12 (0.00% of dataset)
Get column duplicates...

hash cols:   0%|          | 0/989 [00:00<?, ?it/s]

group check:   0%|          | 0/989 [00:00<?, ?it/s]

Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,num_0,num_1,num_2,num_3,num_4,num_5,num_6,num_7,num_8,num_9,num_10,num_11,num_12,num_13,num_14,num_15,num_16,num_17,num_18,num_19,num_20,num_21,num_22,num_23,num_24,num_25,num_26,num_27,num_28,num_29,num_30,num_31,num_32,num_33,num_34,num_35,num_36,num_37,num_38,num_39,num_40,num_41,num_42,num_43,num_44,num_45,num_46,num_47,num_48,num_49,num_50,num_51,num_52,num_53,num_54,num_55,num_56,num_57,num_58,num_59,num_60,num_61,num_62,num_63,num_64,num_65,num_66,num_67,num_68,num_69,num_70,num_71,num_72,num_73,num_74,num_75,num_76,num_77,num_78,num_79,num_80,num_81,num_82,num_83,num_84,num_85,num_86,num_87,num_88,num_89,num_90,num_91,num_92,num_93,num_94,num_95,num_96,num_97,num_98,num_99,num_100,num_101,num_102,num_103,num_104,num_105,num_106,num_107,num_108,num_109,num_110,num_111,num_112,num_113,num_114,num_115,num_116,num_117,num_118,num_119,num_120,num_121,num_122,num_123,num_124,num_125,num_126,num_127,num_128,num_129,num_130,num_131,num_132,num_133,num_134,num_135,num_136,num_137,num_138,num_139,num_140,num_141,num_142,num_143,num_144,num_145,num_146,num_147,num_148,num_149,num_150,num_151,num_152,num_153,num_154,num_155,num_156,num_157,num_158,num_159,num_160,num_161,num_162,num_163,num_164,num_165,num_166,num_167,num_168,num_169,num_170,num_171,num_172,num_173,num_174,num_175,num_176,num_177,num_178,num_179,num_180,num_181,num_182,num_183,num_184,num_185,num_186,num_187,num_188,num_189,num_190,num_191,num_192,num_193,num_194,num_195,num_196,num_197,num_198,num_199,num_200,num_201,num_202,num_203,num_204,num_205,num_206,num_207,num_208,num_209,num_210,num_211,num_212,num_213,num_214,num_215,num_216,num_217,num_218,num_219,num_220,num_221,num_222,num_223,num_224,num_225,num_226,num_227,num_228,num_229,num_230,num_231,num_232,num_233,num_234,num_235,num_236,num_237,num_238,num_239,num_240,num_241,num_242,num_243,num_244,num_245,num_246,num_247,num_248,num_249,num_250,num_251,num_252,num_253,num_254,num_255,num_256,num_257,num_258,num_259,num_260,num_261,num_262,num_263,num_264,num_265,num_266,num_267,num_268,num_269,num_270,num_271,num_272,num_273,num_274,num_275,num_276,num_277,num_278,num_279,num_280,num_281,num_282,num_283,num_284,num_285,num_286,num_287,num_288,num_289,num_290,num_291,num_292,num_293,num_294,num_295,num_296,num_297,num_298,num_299,num_300,num_301,num_302,num_303,num_304,num_305,num_306,num_307,num_308,num_309,num_310,num_311,num_312,num_313,num_314,num_315,num_316,num_317,num_318,num_319,num_320,num_321,num_322,num_323,num_324,num_325,num_326,num_327,num_328,num_329,num_330,num_331,num_332,num_333,num_334,num_335,num_336,num_337,num_338,num_339,num_340,num_341,num_342,num_343,num_344,num_345,num_346,num_347,num_348,num_349,num_350,num_351,num_352,num_353,num_354,num_355,num_356,num_357,num_358,num_359,num_360,num_361,num_362,num_363,num_364,num_365,num_366,num_367,num_368,num_369,num_370,num_371,num_372,num_373,num_374,num_375,num_376,num_377,num_378,num_379,num_380,num_381,num_382,num_383,num_384,num_385,num_386,num_387,num_388,num_389,num_390,num_391,num_392,num_393,num_394,num_395,num_396,num_397,num_398,num_399,num_400,num_401,num_402,num_403,num_404,num_405,num_406,num_407,num_408,num_409,num_410,num_411,num_412,num_413,num_414,num_415,num_416,num_417,num_418,num_419,num_420,num_421,num_422,num_423,num_424,num_425,num_426,num_427,num_428,num_429,num_430,num_431,num_432,num_433,num_434,num_435,num_436,num_437,num_438,num_439,num_440,num_441,num_442,num_443,num_444,num_445,num_446,num_447,num_448,num_449,num_450,num_451,num_452,num_453,num_454,num_455,num_456,num_457,num_458,num_459,num_460,num_461,num_462,num_463,num_464,num_465,num_466,num_467,num_468,num_469,num_470,num_471,num_472,num_473,num_474,num_475,num_476,num_477,num_478,num_479,num_480,num_481,num_482,num_483,num_484,num_485,num_486,num_487,num_488,num_489,num_490,num_491,num_492,num_493,num_494,num_495,num_496,num_497,num_498,num_499,num_500,num_501,num_502,num_503,num_504,num_505,num_506,num_507,num_508,num_509,num_510,num_511,num_512,num_513,num_514,num_515,num_516,num_517,num_518,num_519,num_520,num_521,num_522,num_523,num_524,num_525,num_526,num_527,num_528,num_529,num_530,num_531,num_532,num_533,num_534,num_535,num_536,num_537,num_538,num_539,num_540,num_541,num_542,num_543,num_544,num_545,num_546,num_547,num_548,num_549,num_550,num_551,num_552,num_553,num_554,num_555,num_556,num_557,num_558,num_559,num_560,num_561,num_562,num_563,num_564,num_565,num_566,num_567,num_568,num_569,num_570,num_571,num_572,num_573,num_574,num_575,num_576,num_577,num_578,num_579,num_580,num_581,num_582,num_583,num_584,num_585,num_586,num_587,num_588,num_589,num_590,num_591,num_592,num_593,num_594,num_595,num_596,num_597,num_598,num_599,num_600,num_601,num_602,num_603,num_604,num_605,num_606,num_607,num_608,num_609,num_610,num_611,num_612,num_613,num_614,num_615,num_616,num_617,num_618,num_619,num_620,num_621,num_622,num_623,num_624,num_625,num_626,num_627,num_628,num_629,num_630,num_631,num_632,num_633,num_634,num_635,num_636,num_637,num_638,num_639,num_640,num_641,num_642,num_643,num_644,num_645,num_646,num_647,num_648,num_649,num_650,num_651,num_652,num_653,num_654,num_655,num_656,num_657,num_658,num_659,num_660,num_661,num_662,num_663,num_664,num_665,num_666,num_667,num_668,num_669,num_670,num_671,num_672,num_673,num_674,num_675,num_676,num_677,num_678,num_679,num_680,num_681,num_682,num_683,num_684,num_685,num_686,num_687,num_688,num_689,num_690,num_691,num_692,num_693,num_694,num_695,num_696,num_697,num_698,num_699,num_700,num_701,num_702,num_703,num_704,num_705,num_706,num_707,num_708,num_709,num_710,num_711,num_712,num_713,num_714,num_715,num_716,num_717,num_718,num_719,num_720,num_721,num_722,num_723,num_724,num_725,num_726,num_727,num_728,num_729,num_730,num_731,num_732,num_733,num_734,num_735,num_736,num_737,num_738,num_739,num_740,num_741,num_742,num_743,num_744,num_745,num_746,num_747,num_748,num_749,num_750,num_751,num_752,num_753,num_754,num_755,num_756,num_757,num_758,num_759,num_760,num_761,num_762,num_763,num_764,num_765,num_766,num_767,num_768,num_769,num_770,num_771,num_772,num_773,num_774,num_775,num_776,num_777,num_778,num_779,num_780,num_781,num_782,num_783,num_784,num_785,num_786,num_787,num_788,num_789,num_790,num_791,num_792,num_793,num_794,num_795,num_796,num_797,num_798,num_799,num_800,num_801,num_802,num_803,num_804,num_805,num_806,num_807,num_808,num_809,num_810,num_811,num_812,num_813,num_814,num_815,num_816,num_817,num_818,num_819,num_820,num_821,num_822,num_823,num_824,num_825,num_826,num_827,num_828,num_829,num_830,num_831,num_832,num_833,num_834,num_835,num_836,num_837,num_838,num_839,num_840,num_841,num_842,num_843,num_844,num_845,num_846,num_847,num_848,num_849,num_850,num_851,num_852,num_853,num_854,num_855,num_856,num_857,num_858,num_859,num_860,num_861,num_862,num_863,num_864,num_865,num_866,num_867,num_868,num_869,num_870,num_871,num_872,num_873,num_874,num_875,num_876,num_877,num_878,num_879,num_880,num_881,num_882,num_883,num_884,num_885,num_886,num_887,num_888,num_889,num_890,num_891,num_892,num_893,num_894,num_895,num_896,num_897,num_898,num_899,num_900,num_901,num_902,num_903,num_904,num_905,num_906,num_907,num_908,num_909,num_910,num_911,num_912,num_913,num_914,num_915,num_916,num_917,num_918,num_919,num_920,num_921,num_922,num_923,num_924,num_925,num_926,num_927,num_928,num_929,num_930,num_931,num_932,num_933,num_934,num_935,num_936,num_937,num_938,num_939,num_940,num_941,num_942,num_943,num_944,num_945,num_946,num_947,num_948,num_949,num_950,num_951,num_952,num_953,num_954,num_955,num_956,num_957,num_958,num_959,num_960,num_961,num_962,num_963,num_964,num_965,num_966,num_967,num_968,num_969,num_970,num_971,num_972,num_973,num_974,num_975,num_976,num_977,num_978,num_979,num_980,num_981,num_982,num_983,cat_0,cat_1,timestamp,track_length,target_log_spkm
0,0.689529,0.678433,0.426459,0.393967,0.294161,-0.041413,-1.164444,-0.473810,0.206696,-0.071621,-0.037877,0.532238,-0.506457,0.536730,-0.000479,-0.026024,-1.304851,-0.612252,0.257540,1.294533,0.333544,NaN,-1.503596,1.300525,1.238514,-0.849111,-0.230315,-1.104137,-0.205061,-0.357496,1.397836,-0.292676,0.578806,1.928289,0.062770,-0.455915,0.723343,-0.726606,-0.457620,0.723343,-0.724973,-0.587166,0.720784,-0.163824,0.202772,0.451469,-0.163824,0.310820,0.451469,-0.165095,0.250906,0.45008,-1.088722,0.079892,0.561327,-1.085702,0.084479,0.689529,0.076604,0.315722,0.761353,-0.961429,-0.593976,0.494971,-0.961429,-0.272834,0.439001,-0.965420,-0.269673,0.161281,-0.028859,-0.105318,0.536531,-0.031369,0.093298,0.631785,-0.033880,0.028530,0.615024,0.634851,0.124530,0.565738,0.634851,0.248306,0.636386,0.631785,0.166003,0.598435,-0.367766,0.312133,0.599235,0.247133,0.167018,0.125359,1.431971,0.022183,1.225943,-0.035089,-0.032375,-0.034806,0.669823,0.491734,0.423463,0.203379,-0.403234,-0.584839,-0.754652,0.192930,0.535599,0.576092,1.257818,2.044038,-0.304433,-0.170263,-0.124746,-0.011291,-0.144780,0.130848,0.347689,1.066124,-0.340678,-1.493584,0.586048,0.636298,0.445492,0.208385,1.211558,1.285686,-0.243788,0.326784,NaN,-0.667837,-0.073446,1.416859,0.393339,-0.812905,0.635950,0.776528,-0.079120,1.008294,-1.027247,-0.651277,2.956244,0.366873,-0.173974,-0.283522,0.205941,-0.384398,-0.441766,0.208505,-0.604466,-0.642543,-0.325577,-0.173975,-0.01882,-0.324254,-0.174842,-0.016310,-0.326900,-0.175633,-0.01882,-0.587964,0.295234,1.215372,0.878249,1.329192,1.321946,0.878777,1.365788,1.375955,0.236799,0.954968,1.130517,0.461215,0.935442,1.081940,0.461215,0.895926,0.868016,0.598435,1.066198,1.164444,0.812654,1.201468,1.242061,0.808008,1.233830,1.225943,0.732609,1.137660,1.176890,0.810329,1.258555,1.231280,0.805692,1.279821,1.204935,-0.291062,-0.171327,1.442673,1.253675,1.280846,1.137454,0.681594,-1.131765,0.530745,1.127262,1.130606,1.126862,0.069515,0.121523,-0.199110,0.147316,0.975494,0.890886,0.779930,1.256344,1.412937,1.437423,0.992124,1.293174,-0.368100,-0.254068,-0.117145,0.871679,-0.067799,-0.860725,0.388430,0.510554,-1.100197,-0.311578,0.340707,0.401995,0.311531,-0.187819,0.566758,0.525669,2.393011,0.243999,NaN,-0.06425,1.846165,1.505077,-0.176553,-0.323140,0.128534,0.265284,-0.170185,0.451469,-0.604448,-0.642071,-0.025340,-0.517790,0.065265,0.111890,-0.472407,-0.062267,-0.057742,-1.700222,-0.120965,-0.101796,-0.276998,-0.533636,-0.535083,-0.275694,-0.535083,-0.533636,-0.275694,-0.535083,-0.535083,0.821161,0.881759,0.567211,0.887565,1.037002,0.705530,0.945616,1.020448,0.692715,0.003764,0.600285,0.512061,0.172731,0.656555,0.774833,0.041413,0.580263,0.496390,0.458426,0.774650,0.627196,0.459820,0.821974,0.741388,0.540882,0.823188,0.723343,0.517790,0.785775,0.707140,0.486480,0.822578,0.752998,0.570161,0.833446,0.764710,0.219173,-0.523537,0.858637,0.821063,0.831653,0.785529,0.13971,-0.721183,0.038901,0.509302,0.509168,0.509569,0.643817,0.654783,0.576359,0.138444,-0.696563,-0.399622,-0.097628,0.514635,0.843608,0.847786,1.699252,2.187673,0.252816,1.381110,0.781714,1.107059,0.769761,0.485069,-1.173806,-0.793916,-0.319387,0.207578,-0.947355,-1.151250,0.296693,-0.727727,-0.768802,-0.781831,1.119050,0.328331,NaN,-0.038125,2.067976,1.918803,1.251196,0.962716,-0.299038,0.172731,-0.193143,0.333524,-0.524976,-0.593675,-0.029582,-1.176890,-0.722379,-0.177827,-0.961429,-0.730871,-0.207223,-1.792374,-1.028193,-0.275694,-0.258792,-0.454249,-0.454249,-0.258792,0.428296,0.697507,-0.258792,-0.452858,-0.455640,-0.168912,-0.597472,-0.204660,-1.719551,-1.176863,-0.479432,-1.724287,-0.408749,-0.162552,-1.519532,-1.524184,-0.922330,-1.404533,-1.318727,-1.132898,-1.206666,-1.029077,-0.743040,-0.877196,-1.126794,-0.844485,-0.798769,-0.987761,-0.901416,-0.586473,-0.844987,-0.622621,-0.564267,-0.925361,-0.914679,-0.537980,-0.817468,-1.006211,-0.439001,-0.733754,-0.662724,0.142714,0.429621,-0.745973,-0.819248,-0.734510,-0.929422,0.094232,0.048395,0.021329,-0.794204,-0.792841,-0.794731,0.484104,0.629945,0.259999,0.137177,-2.017233,-2.174227,-2.271376,-0.792607,-0.805653,-0.795543,1.855028,2.207237,0.586257,-0.288599,0.677342,1.192071,0.842694,0.507774,-0.172286,-0.954291,0.465429,0.924685,-0.409543,-0.162457,0.217549,-1.003803,-1.035673,-0.947370,1.249523,0.320596,NaN,-0.034504,1.764258,1.095399,-0.635178,0.373038,-1.107399,-1.084919,-0.202098,-0.873515,0.694311,1.196015,-0.032169,-1.095556,-0.823558,-0.816150,-1.095556,-0.956816,-0.506348,-1.824556,-0.755359,-0.630254,-0.253606,0.501785,0.734798,-0.254902,0.537840,0.734798,-0.254902,0.531741,0.731515,-2.702603,-1.148597,-0.743040,-1.195653,-0.874541,-0.180377,-1.195910,-0.772327,-0.387078,-1.482760,-1.298000,-1.057485,-0.888309,-0.946794,-0.723343,-0.888309,-0.913925,-0.648724,-1.376494,-1.046815,-0.764710,-1.031509,-0.878804,-0.497809,-1.031509,-0.774081,-0.471004,-1.116369,-0.850236,-0.866189,-0.689529,-0.787723,-0.697507,-0.689529,-0.663609,-0.393847,-0.080637,0.539438,-0.723390,-0.788353,-0.661220,-0.851489,0.089192,0.803084,0.017565,-0.957679,-0.958580,-0.960634,0.892480,1.072096,0.787705,0.134645,-1.344447,-1.481550,-1.722490,-0.955156,-0.775417,-0.764868,0.174869,1.460364,0.818282,-0.281321,0.329548,-0.282216,0.184203,0.468203,0.241963,0.124328,0.321170,0.151179,0.307374,0.249721,0.350142,0.175141,0.240516,0.133785,-0.165578,0.272175,NaN,-0.040631,-0.050651,0.377093,-1.155671,-0.759006,-0.783900,-1.238877,-0.189310,-0.853480,0.691121,0.400268,-0.031003,-0.395204,-0.631438,-0.830234,-1.381364,-1.404448,-1.439001,-0.483658,-0.857830,-1.027247,-0.261387,-0.443149,-0.441766,-0.260089,-0.443149,-0.443149,-0.262686,-0.444534,-0.444534,-1.478256,-0.034535,0.427976,-2.704862,-0.657505,0.406079,-0.635363,-0.149805,0.137177,0.016310,0.119980,0.473810,0.239380,0.324149,0.337506,0.267884,0.260478,0.274391,-0.330873,0.231097,0.283522,-0.195700,0.373549,0.322932,-0.147316,0.208917,0.106841,-0.336178,0.256612,0.130848,-0.605955,0.383528,0.241963,-0.085414,0.288070,0.172731,-0.935868,-0.432104,0.415504,0.382015,0.284580,0.255660,0.096752,-0.282399,0.020074,0.122007,0.121446,0.123761,0.678686,0.509263,0.460613,0.134645,-0.810849,-0.616193,-0.596212,0.126798,0.398356,0.403029,1.384776,1.893840,0.793965,-0.256185,0.198259,-0.336178,0.030114,0.364190,0.345485,-0.127829,0.542299,0.599965,0.647435,0.362850,0.470083,1.334066,0.067466,-0.100023,-0.184183,0.377012,NaN,-0.060462,-0.050358,-0.214240,-0.657676,0.022163,-0.163845,-0.659374,-0.152391,-0.759677,1.446103,1.176077,-0.026930,-1.029375,-1.412122,-1.210137,-1.331018,-0.836838,-0.309743,-1.020888,-1.461368,-1.247506,-0.279606,-0.487893,-0.486480,-0.278302,0.439657,0.641002,-0.280911,-0.489307,-0.490721,0.043924,0.169854,0.213636,-2.625464,-0.276793,0.267884,-0.713598,-0.710394,0.152391,0.368215,-0.160265,-0.564267,0.445919,0.238576,-0.147316,0.101796,0.039980,0.109365,0.137177,0.151903,-0.196979,0.218773,0.278031,0.089192,-0.118204,-0.065732,-0.380326,0.216204,0.267103,-0.171458,0.158740,0.324417,0.172731,-0.447305,-0.074327,-0.385726,-0.415659,0.441209,0.381676,0.324083,-0.075556,0.265471,0.124523,-0.050905,0.036391,-0.127258,-0.126307,-0.127177,1.030762,0.395371,0.956498,0.134645,-0.703760,-0.714004,-0.626316,-0.114602,0.353225,0.360459,0.965666,1.916471,0.799216,-0.217315,-0.076604,-0.499230,-0.307111,0.174005,0.561327,0.392957,-1.076305,0.284313,0.793499,0.608973,0.456476,0.773109,0.639834,0.464704,-0.212156,0.328350,NaN,-0.144841,-0.055509,-0.668799,-1.409414,-1.003383,-0.384873,-0.942805,-0.085414,-0.504922,0.496390,1.704648,-0.026533,-0.783330,-1.642485,-1.579968,-1.674186,-0.269729,-0.176553,-0.879040,-1.560788,-1.407905,-0.313694,-0.601439,-0.601439,-0.313694,0.402621,0.464007,-0.316330,-0.604448,-0.604448,-0.691121,0.363771,0.384375,-0.019656,0.324212,0.129582,-0.018820,0.351883,0.365531,0.378977,-0.012251,-0.389783,0.869846,0.495769,0.119468,0.639462,0.411003,0.177827,0.376283,0.348025,0.099274,0.705530,0.595638,0.191865,-0.003764,0.354571,0.143512,0.785036,0.457111,0.130848,0.910873,0.658903,0.198259,-0.195700,0.332853,0.175278,-0.125582,0.405984,0.749141,0.656224,0.334031,0.461051,0.221344,-0.158579,0.103057,0.408690,0.404251,0.409474,0.553683,-0.049158,0.196394,0.137177,-0.231690,-0.100052,-0.018680,0.440727,0.717246,0.726751,1.099764,1.697889,0.078431,-0.129846,-0.376020,-0.157469,-1.505747,-0.193143,0.330924,-0.852425,1.283942,1.524682,0.730851,1.008956,0.401258,-0.558649,-0.084347,0.001152,-0.211866,0.441174,NaN,-1.184235,-0.063641,-0.121283,-0.513452,0.557629,0.048023,0.159349,0.099274,0.774833,-0.075345,-0.521322,-0.013124,-0.761353,0.853961,1.375759,-0.523537,0.895483,1.376936,-0.524976,0.845101,1.374585,-0.384375,0.826104,0.812654,0.851675,0.831779,0.814401,-0.387078,0.819410,0.812654,0.225202,-0.086738,0.344154,0.664287,0.429686,0.422483,0.659082,0.407330,0.079120,-1.378114,-1.286256,-0.520661,-1.374878,-1.228109,-0.129582,-1.374878,-1.223343,-0.061513,-0.647177,-0.774684,0.070314,-0.648724,-0.692969,0.216204,-0.645631,-0.728165,-0.032625,-0.273089,-0.569581,0.082896,-0.270485,-0.539313,0.129582,-0.275694,-0.591161,-0.251016,-0.047444,0.836086,0.285505,-0.536766,-0.592030,-0.568533,1.111702,1.136709,0.957454,-0.678289,-0.676007,-0.679204,0.457172,0.344421,0.400609,0.162552,0.709632,0.079953,-0.333310,-0.092836,0.179126,0.257947,-0.264133,0.335526,3,3,2023-11-01 00:00:13,7291.365336,4.993570

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,cat_0,category,0.0,0.00,96.0,"1, 2, 7, 4, 10, 6, 5, 3, 18, 8"
1,cat_1,category,0.0,0.00,97.0,"1, 2, 7, 4, 10, 6, 5, 3, 18, 8"
2,timestamp,datetime64[us],0.0,0.00,3073903.0,"2023-12-06 10:22:42, 2023-11-19 09:20:36, 2023-11-01 10:02:50, 2023-11-12 14:14:35, 2023-11-24 12:59:43, 2023-11-04 07:13:00, 2023-11-16 15:22:39, 2023-11-30 11:18:30, 2023-11-04 10:54:18, 2023-11-09 04:54:43"
3,num_457,float32,13257625.0,97.20,82483.0,"-0.7152, -0.0464, 0.7647, 0.3481, -1.6897, 1.1449, -1.2075, 1.4216, 1.7387, 1.3041"
4,num_348,float32,13225480.0,96.97,89516.0,"-0.6257, 0.0364, -1.567, 0.832, 0.4197, 1.1972, -1.1024, 1.4642, 1.78, 1.3526"
5,num_566,float32,13200374.0,96.78,87116.0,"-0.5336, 0.1144, -1.5215, 0.8717, 0.4766, -1.0188, 1.2394, 1.4942, 1.3781, 1.805"
6,num_675,float32,12974505.0,95.13,107694.0,"-0.1068, -1.1305, 0.5221, 1.1769, 0.8427, -0.5496, 1.498, 1.7502, 0.2953, 1.6444"
7,num_239,float32,12923032.0,94.75,125726.0,"-1.0575, -0.0703, 0.5511, 0.879, 1.2259, -0.478, 1.5377, 1.7862, 0.3106, 1.6845"
8,num_784,float32,12041260.0,88.28,183492.0,"-0.7039, 0.5035, 1.1744, 0.0854, 1.439, 1.7275, 0.9694, 1.995, 2.144, 2.2318"
9,num_130,float32,6828289.0,50.06,641182.0,"-0.3535, 1.2669, 0.8662, 2.0137, 2.2258, 2.4569, 1.7619, -3.0899, 2.6563, 2.8034"
10,num_893,float32,3357540.0,24.62,782304.0,"-0.3111, 1.4753, 1.0379, 2.3995, 2.0799, -3.1014, 2.6517, 2.8778, 2.5118, 3.0937"
11,num_972,float32,2962472.0,21.72,6041012.0,"3.0915, 3.0909, 3.0917, 3.0904, 3.0901, 3.0906, 3.0916, 3.0965, 3.0909, 3.091"
12,num_973,float32,2962472.0,21.72,6089072.0,"3.0906, 3.0905, 3.0913, 3.0902, 3.0904, 3.0902, 3.0947, 3.09, 3.0912, -0.0468"
13,num_974,float32,2962472.0,21.72,6001637.0,"3.0932, 3.0901, 3.0911, 3.093, 3.0911, 3.094, -0.2857, -0.5857, 0.1231, -0.2852"
14,num_883,float32,2672082.0,19.59,4252838.0,"-0.5885, 3.0905, 3.091, 3.0903, 3.0904, 3.0901, 3.0906, 3.0915, 3.0911, 0.1293"
15,num_915,float32,2345302.0,17.20,3.0,"-0.3844, 0.8553, 1.6793"
16,num_916,float32,2345302.0,17.20,4658070.0,"-1.2448, 0.1842, 1.6793, -0.1794, -0.4581, -0.486, 1.0532, -0.7791, 0.4131, -0.5978"
17,num_917,float32,2345302.0,17.20,3.0,"0.8127, -0.2575, -1.2448"
18,num_918,float32,2345480.0,17.20,3.0,"-0.3857, 0.8517, 1.6742"
19,num_919,float32,2345480.0,17.20,4653621.0,"-1.2421, 0.1817, 1.6742, -0.1799, -0.4837, -0.4562, 1.0504, -0.7759, 0.4107, -0.6508"
20,num_920,float32,2345480.0,17.20,3.0,"0.8144, -0.2549, -1.2421"
21,num_921,float32,2345678.0,17.20,3.0,"-0.3871, 0.8499, 1.6742"
22,num_922,float32,2345678.0,17.20,4652716.0,"-1.2448, 0.1791, 1.6742, -0.1825, -0.4847, -0.778, -0.4571, 1.048, 0.4081, -0.5958"
23,num_923,float32,2345678.0,17.20,3.0,"0.8127, -0.2575, -1.2448"
24,num_906,float32,2331178.0,17.09,4444.0,"-1.331, -0.7614, -0.5264, -0.3669, -0.2471, -0.1448, -0.0603, 0.0151, 0.0804, 0.141"
25,num_907,float32,2331178.0,17.09,8323250.0,"-2.9886, -2.4655, -2.1929, -2.0074, -1.8605, -1.7387, -1.6347, -1.5402, -1.4551, -1.3781"
26,num_908,float32,2331178.0,17.09,10703.0,"-1.4716, -1.425, -1.3041, -1.63, -1.5186, -1.7659, -1.3402, -1.8448, -1.6949, -1.5713"
27,num_909,float32,2331178.0,17.09,3949.0,"-1.331, -0.758, -0.5235, -0.3669, -0.2445, -0.1448, -0.0577, 0.0151, 0.0829, 0.141"
28,num_910,float32,2331178.0,17.09,8323838.0,"-2.9886, -2.4655, -2.2009, -2.0137, -1.8659, -1.7453, -1.6379, -1.5445, -1.4597, -1.3814"
29,num_911,float32,2331178.0,17.09,10807.0,"-1.4716, -1.5175, -1.6949, -1.3402, -1.2641, -1.7619, -1.425, -1.3022, -1.3814, -1.63"
30,num_912,float32,2331178.0,17.09,3030.0,"-1.331, -0.758, -0.525, -0.3669, -0.2445, -0.146, -0.0603, 0.0151, 0.0804, 0.1384"
31,num_913,float32,2331178.0,17.09,8322455.0,"-2.9886, -2.4655, -2.1969, -2.0113, -1.867, -1.743, -1.6376, -1.5458, -1.4605, -1.3817"
32,num_914,float32,2331178.0,17.09,10930.0,"-1.63, -1.5215, -1.4716, -1.5742, -1.425, -1.3433, -1.6949, -1.3846, -1.2697, -1.3041"
33,num_924,float32,2331178.0,17.09,252.0,"-1.4193, -0.8144, -0.5083, -0.2705, -0.0758, 0.0879, 0.2252, 0.3402, 0.4381, 0.5221"
34,num_925,float32,2331178.0,17.09,8500964.0,"-3.1048, -2.4569, -1.8517, -2.0966, -1.4828, -1.6446, -1.3402, -1.2101, -1.0932, -0.8846"
35,num_926,float32,2331178.0,17.09,311.0,"-0.146, -0.064, -0.0226, -0.2304, -0.1245, -0.0439, 0.0188, -0.1043, -0.0842, -0.251"
36,num_927,float32,2331178.0,17.09,238.0,"-1.4195, -0.8149, -0.5092, -0.2718, -0.0766, 0.0867, 0.2248, 0.3406, 0.439, 0.5243"
37,num_928,float32,2331178.0,17.09,8502796.0,"-3.1024, -2.4569, -1.8516, -2.0966, -1.4828, -1.649, -1.3348, -1.2101, -1.0905, -0.8809"
38,num_929,float32,2331178.0,17.09,321.0,"-0.0201, -0.0615, -0.1043, -0.0829, -0.1245, -0.2718, -0.315, -0.1448, 0.0414, -0.2497"
39,num_930,float32,2331178.0,17.09,253.0,"-1.4202, -0.8144, -0.5092, -0.2731, -0.0783, 0.0854, 0.2226, 0.3375, 0.4353, 0.5199"
40,num_931,float32,2331178.0,17.09,8504030.0,"-3.1103, -2.4569, -2.0965, -1.8469, -1.4783, -1.6444, -1.3341, -1.2049, -1.0887, -0.7884"
41,num_932,float32,2331178.0,17.09,314.0,"-0.0653, -0.0854, -0.1068, -0.0439, -0.1906, -0.0238, -0.1271, -0.2731, -0.1486, -0.3163"
42,num_933,float32,2331178.0,17.09,490.0,"-0.5999, -0.4992, -0.5322, -0.6706, -0.4668, -0.4034, -0.5672, -0.4335, -0.7088, -0.2809"
43,num_934,float32,2331178.0,17.09,7236152.0,"0.1321, 0.1829, 0.3112, 0.434, 0.4584, 0.5063, 0.1575, 0.3362, -0.0238, -0.1022"
44,num_935,float32,2331178.0,17.09,565.0,"-0.146, -0.1906, -0.1689, -0.059, -0.0804, 0.0063, -0.1018, -0.2124, -0.1245, -0.0364"
45,num_936,float32,2331178.0,17.09,488.0,"-0.4626, -0.5969, -0.4006, -0.6674, -0.495, -0.4307, -0.7023, -0.3682, -0.5293, -0.6303"
46,num_937,float32,2331178.0,17.09,7237791.0,"0.0791, -0.0246, 0.4082, 0.5293, 0.3081, 0.3834, 0.3335, 0.1818, 0.577, 0.4328"
47,num_938,float32,2331178.0,17.09,572.0,"-0.1296, -0.1524, -0.0867, -0.1081, -0.1957, -0.064, -0.0439, -0.2175, -0.2394, -0.1727"
48,num_939,float32,2331178.0,17.09,485.0,"-0.5969, -0.4006, -0.464, -0.4307, -0.4978, -0.5643, -0.6674, -0.6333, -0.7414, -0.3097"
49,num_940,float32,2331178.0,17.09,7238265.0,"0.4078, 0.4319, 0.3576, 0.5047, 0.258, 0.1829, 0.4559, 0.0796, 0.2085, 0.1314"
50,num_941,float32,2331178.0,17.09,575.0,"-0.1068, -0.0188, -0.2601, -0.2809, -0.0615, -0.1727, -0.1499, -0.0402, -0.0842, -0.2162"
51,num_942,float32,2331178.0,17.09,354.0,"-0.4738, -0.5307, -0.588, -0.4197, -0.6472, -0.3124, -0.3655, -0.2627, -0.2124, -0.7071"
52,num_943,float32,2331178.0,17.09,7649321.0,"0.5677, 0.2693, 0.238, -0.3336, 0.5121, -0.0582, 0.6241, 0.331, 0.3925, 0.4225"
53,num_944,float32,2331178.0,17.09,400.0,"-0.0816, -0.0314, -0.1575, -0.1829, -0.1321, -0.2072, -0.2575, -0.0565, -0.1068, 0.0452"
54,num_945,float32,2331178.0,17.09,358.0,"-0.4738, -0.5307, -0.4197, -0.588, -0.6487, -0.3655, -0.3137, -0.2627, -0.2136, -0.7681"
55,num_946,float32,2331178.0,17.09,7646048.0,"0.2394, 0.6817, 0.6272, -0.2627, 0.2705, -0.0561, 0.11, -0.0892, 0.5129, 0.0442"
56,num_947,float32,2331178.0,17.09,409.0,"-0.0816, -0.1575, -0.0565, -0.1321, 0.0176, -0.1829, 0.0427, -0.0075, -0.2342, -0.3097"
57,num_948,float32,2331178.0,17.09,353.0,"-0.4724, -0.5279, -0.6456, -0.417, -0.3629, -0.3111, -0.585, -0.2601, -0.7055, -0.2111"
58,num_949,float32,2331178.0,17.09,7645983.0,"0.5105, 0.1403, 0.0088, 0.4226, -0.16, 0.2705, -0.0575, 0.3925, 0.6248, 0.6518"
59,num_950,float32,2331178.0,17.09,397.0,"-0.0829, -0.1334, -0.1081, -0.0088, -0.0577, -0.1587, -0.1842, -0.3375, -0.2355, -0.0326"
60,num_951,float32,2331178.0,17.09,354.0,"-0.4197, -0.3203, -0.471, -0.3696, -0.5235, -0.5776, -0.2252, -0.2731, -0.6333, -0.6895"
61,num_952,float32,2331178.0,17.09,7838470.0,"0.7888, 0.813, 0.7647, 0.6632, 0.2188, 0.6368, 0.4755, 0.4197, 0.2476, -0.2809"
62,num_953,float32,2331178.0,17.09,415.0,"-0.1689, -0.1195, -0.0942, -0.1448, 0.0577, 0.0326, -0.0691, 0.0075, -0.0176, -0.1944"
63,num_954,float32,2331178.0,17.09,347.0,"-0.4197, -0.4696, -0.3682, -0.5761, -0.319, -0.2705, -0.5235, -0.6333, -0.2239, -0.6895"
64,num_955,float32,2331178.0,17.09,7838550.0,"0.8121, -0.2835, 0.7859, 0.4181, 0.2162, 0.7614, 0.6333, 0.6084, 0.3898, 0.3326"
65,num_956,float32,2331178.0,17.09,409.0,"-0.1995, -0.174, -0.0728, -0.098, -0.0213, 0.0038, -0.1486, -0.0464, 0.1043, 0.054"
66,num_957,float32,2331178.0,17.09,353.0,"-0.3229, -0.4225, -0.579, -0.4738, -0.5264, -0.6333, -0.3736, -0.2291, -0.2757, -0.6895"
67,num_958,float32,2331178.0,17.09,7834336.0,"0.7885, -0.2814, 0.8127, 0.585, 0.2188, 0.9575, 0.662, 0.688, 0.6115, 0.1294"
68,num_959,float32,2331178.0,17.09,418.0,"-0.1258, 0.0527, -0.0238, 0.0276, -0.1766, -0.2008, -0.1511, -0.0741, -0.0489, 0.0025"
69,num_960,float32,2331178.0,17.09,8887279.0,"-5.0287, 5.1993, 3.0941, 0.1803, 1.1772, -0.2726, 3.0978, -0.1076, 3.0922, 0.0275"
70,num_961,float32,2331178.0,17.09,4695584.0,"-1.2286, 0.1842, 1.6845, -5.1993, -0.1782, -0.4808, -0.4531, 1.0555, -0.7719, 0.4117"
71,num_963,float32,2331178.0,17.09,7834718.0,"0.8161, -0.2804, 0.7919, 0.4213, 0.2192, 0.7661, 0.6387, 0.612, 0.3929, 0.3362"
72,num_964,float32,2331178.0,17.09,7832862.0,"0.7876, -0.2814, 0.8127, 0.582, 0.2162, 0.9575, 0.6612, 0.6864, 0.609, 0.1271"
73,num_965,float32,2331178.0,17.09,7836931.0,"0.7904, 0.8159, 0.7658, 0.6643, 0.2199, 0.6388, 0.478, 0.4215, 0.2497, -0.2788"
74,num_967,float32,2331178.0,17.09,7502160.0,"-0.0716, -0.3143, -0.5351, 0.1866, -0.7381, 0.464, -0.9223, 0.7514, -1.0887, -1.2421"
75,num_881,float32,2035595.0,14.92,3940206.0,"-1.1744, 0.0716, 1.1234, 0.5207, 1.5977, 2.0638, -2.3302, 1.8804, -0.5228, 1.4296"
76,num_882,float32,2035595.0,14.92,8357191.0,"-0.8632, 1.6525, -0.2525, -0.7438, -0.1842, -0.4162, 1.2253, 0.0168, -0.0424, -0.0285"
77,num_21,float32,1794383.0,13.16,2122268.0,"-0.4307, 1.425, 0.9856, 2.1639, -3.1601, 1.838, 2.326, 2.5802, 0.5539, 2.7834"
78,num_976,float32,1558915.0,11.43,9168465.0,"-1.2572, 1.6919, -1.2428, -1.2499, 1.7183, -1.2445, -0.7457, -1.2396, -0.4516, -0.46"
79,num_977,float32,1558915.0,11.43,8953989.0,"-1.4027, -1.3925, 1.7015, -1.3994, 1.409, -1.3913, -0.793, -0.652, -0.8651, -1.3956"
80,num_978,float32,1558915.0,11.43,8485979.0,"-1.1838, 1.5378, -1.1863, -1.181, -0.8954, -1.1887, -0.7997, -0.8109, -0.8114, 1.4734"
81,num_969,float32,1415817.0,10.38,8675336.0,"-1.3395, -1.2421, -1.2905, -1.1493, -1.1951, -1.4361, -1.5364, -1.5864, -1.486, -1.1024"
82,num_970,float32,1415817.0,10.38,8678910.0,"-1.3362, -1.2404, -1.2883, -1.193, -1.4343, -1.3846, -1.1457, -1.0993, -1.0531, -1.5865"
83,num_971,float32,1415817.0,10.38,8676643.0,"-1.3383, -1.2435, -1.2913, -1.1497, -1.1967, -1.4359, -1.1036, -1.6381, -1.5377, -1.4872"
84,num_867,float32,1407738.0,10.32,8821538.0,"0.8661, 0.8031, 0.8675, 0.6867, 0.8701, 0.5901, 0.8656, 0.8746, -1.4886, 0.7764"
85,num_868,float32,1407738.0,10.32,8263854.0,"0.9635, 0.963, 0.6938, 0.966, 0.9621, 0.9681, 0.6403, 0.5774, 0.8858, 0.6907"
86,num_869,float32,1407738.0,10.32,7865032.0,"0.9884, 0.9875, 0.608, 0.9866, 0.9886, 0.9883, 0.5201, 0.99, 0.5739, 0.6157"
87,num_758,float32,1385572.0,10.16,8705664.0,"0.8221, 0.8339, 0.8245, 0.824, 1.6419, 0.6879, 0.5198, 0.8103, 0.8098, 1.6385"
88,num_759,float32,1385572.0,10.16,8091832.0,"0.8174, 0.8242, 0.824, 0.8056, 0.8202, 1.5616, 0.5582, 0.7366, 1.5585, 0.8129"
89,num_760,float32,1385572.0,10.16,7655099.0,"0.8092, 0.8153, 1.4607, 0.8162, 0.8128, 0.8063, 0.8131, 0.8027, 1.4578, 0.5705"
90,num_649,float32,1380421.0,10.12,8685489.0,"1.6404, 1.8082, 0.6832, 0.6957, 1.7782, 1.7929, 0.6883, 1.6521, 0.6965, 1.8017"
91,num_650,float32,1380421.0,10.12,8049881.0,"1.7807, 1.6254, 0.8381, 1.7457, 0.8473, 1.6353, 0.7774, 0.8469, 0.8346, 1.7649"
92,num_651,float32,1380421.0,10.12,7566048.0,"1.632, 1.5297, 0.8787, 1.6045, 0.8846, 0.8836, 0.7777, 1.6195, 1.5366, 0.8827"
93,num_540,float32,1378704.0,10.11,8698983.0,"0.8824, 1.1522, 1.2135, 2.0589, 1.2125, 2.007, 1.2119, 1.223, 0.8699, 1.1976"
94,num_541,float32,1378704.0,10.11,8052473.0,"1.9034, 1.0469, 1.0834, 0.7617, 1.8725, 1.0909, 1.0847, 1.0858, 1.0748, 1.0892"
95,num_542,float32,1378704.0,10.11,7546105.0,"1.6894, 0.705, 0.9974, 0.9827, 1.0033, 0.9994, 1.0014, 1.6686, 1.0057, 0.9967"
96,num_322,float32,1377251.0,10.10,8821910.0,"0.81, 0.8034, 0.8098, 0.8095, 0.7242, 0.8015, 0.7218, 0.8099, 0.7852, 0.8074"
97,num_323,float32,1377251.0,10.10,8173897.0,"0.9665, 0.9663, 0.9574, 0.8687, 0.9663, 0.9631, 0.9551, 0.9357, 0.9604, 0.9344"
98,num_324,float32,1377251.0,10.10,7644554.0,"0.9759, 0.9762, 0.9683, 0.8803, 0.976, 0.9666, 0.9462, 0.9708, 0.8753, 0.9742"
99,num_431,float32,1377884.0,10.10,8748310.0,"0.9201, 0.9175, 0.8625, 0.922, 0.9203, 0.9213, 0.9206, 0.8667, 0.8563, 0.918"
100,num_432,float32,1377884.0,10.10,8096608.0,"0.8126, 0.8106, 0.8125, 0.7535, 0.8133, 0.8137, 0.7968, 0.8118, 0.8104, 0.8126"
101,num_433,float32,1377884.0,10.10,7573921.0,"0.7547, 0.7528, 0.6902, 0.7549, 0.7552, 0.7545, 0.7225, 0.7366, 0.7566, 0.6964"
102,num_213,float32,1375833.0,10.09,9280099.0,"-2.4428, -2.4734, -2.4857, -2.4193, -2.019, -2.479, -2.0163, -2.4943, -1.7021, -1.927"
103,num_214,float32,1375833.0,10.09,8788225.0,"-1.798, -1.7438, -1.777, -1.7365, 0.9974, -0.6904, 0.1631, -1.1698, -1.7487, -1.0113"
104,num_215,float32,1375833.0,10.09,8150507.0,"-1.0227, -1.0163, -1.0162, -0.6739, 0.4436, -0.5108, -1.0063, -1.0231, -0.539, -0.6658"
105,num_104,float32,1367917.0,10.03,8602944.0,"0.6833, -0.3288, 0.5961, -0.1193, 0.1443, 0.8237, 0.5134, -0.2778, -1.7565, -1.143"
106,num_105,float32,1367917.0,10.03,7906461.0,"0.5769, -0.4756, -0.0453, 0.0954, 0.1701, 0.9149, -0.8021, -0.0622, -0.4958, -0.0109"
107,num_106,float32,1367917.0,10.03,7198313.0,"-0.0458, 3.0904, 0.088, -0.7022, -0.0845, -0.7653, -0.0909, 0.2775, -0.8194, -0.1762"
108,num_863,float32,1363238.0,9.99,6184794.0,"3.0911, 3.0905, 3.0911, 3.0903, 3.0904, 3.0911, 3.0904, 3.0908, 3.091, 3.0913"
109,num_864,float32,1363238.0,9.99,6244783.0,"3.0902, 3.0908, 3.0904, -0.2809, 0.0224, 3.0919, -0.4258, 3.0905, 3.0984, -0.3252"
110,num_865,float32,1363238.0,9.99,6140889.0,"3.0902, 3.0903, 3.091, -0.8106, 3.0901, -0.0956, -0.3323, -0.0336, 3.0909, -0.4312"
111,num_209,float32,1295523.0,9.50,6349689.0,"3.0921, 3.0919, -0.4529, 3.091, 3.093, 3.0914, 3.0911, -0.2919, 3.0926, 0.4731"
112,num_210,float32,1295523.0,9.50,6405279.0,"3.0906, 3.0907, 3.093, 3.092, 3.0901, 0.1525, -0.4271, 3.0909, 3.0913, 0.0318"
113,num_211,float32,1295523.0,9.50,6333365.0,"3.0906, -0.8504, -0.3348, 3.0931, 0.041, -0.1266, -0.374, -0.2381, -0.9152, -0.5924"
114,num_806,float32,1082902.0,7.94,3.0,"-0.3137, 0.9979, 1.7987"
115,num_807,float32,1082902.0,7.94,2128985.0,"-0.6014, 0.6991, 1.7987, 0.2609, 0.215, 0.2451, 0.1622, 0.3692, 1.2254, 0.9567"
116,num_808,float32,1082902.0,7.94,3.0,"-0.6014, 0.464, 1.313"
117,num_809,float32,1083168.0,7.94,3.0,"-0.3137, 0.9979, 1.7987"
118,num_810,float32,1083168.0,7.94,2127930.0,"-0.6029, 0.6991, 1.805, 0.2135, 0.2597, 0.2434, 0.356, 0.4283, 0.1599, 0.458"
119,num_811,float32,1083168.0,7.94,3.0,"-0.6014, 0.464, 1.313"
120,num_812,float32,1083413.0,7.94,3.0,"-0.3163, 0.9938, 1.7987"
121,num_813,float32,1083413.0,7.94,2132693.0,"-0.6044, 0.6943, 1.7987, 0.2577, 0.2413, 0.2111, 0.3534, 0.1586, 0.4078, 0.4533"
122,num_814,float32,1083413.0,7.94,3.0,"-0.6044, 0.4598, 1.31"
123,num_797,float32,1066277.0,7.82,5479.0,"-1.6742, -1.2023, -1.0125, -0.8827, -0.7833, -0.6975, -0.6272, -0.5643, -0.5063, -0.4542"
124,num_798,float32,1066277.0,7.82,9290218.0,"-3.1069, -2.5553, -2.2496, -2.0331, -1.8731, -1.7387, -1.5215, -1.6253, -1.432, -1.3526"
125,num_799,float32,1066277.0,7.82,11400.0,"-1.316, -1.0531, -1.2697, -1.0887, -1.3621, -1.5175, -1.2313, -1.1946, -0.9614, -1.1546"
126,num_800,float32,1066277.0,7.82,5438.0,"-1.6742, -1.1998, -1.0104, -0.8809, -0.7799, -0.6975, -0.6241, -0.5599, -0.5035, -0.4515"
127,num_801,float32,1066277.0,7.82,9287576.0,"-3.1065, -2.5755, -2.2567, -2.0331, -1.8659, -1.7275, -1.6159, -1.5215, -1.425, -1.3464"
128,num_802,float32,1066277.0,7.82,11497.0,"-1.2734, -1.1211, -1.1546, -1.3621, -1.4113, -0.9614, -1.2313, -1.1946, -1.0865, -1.023"
129,num_803,float32,1066277.0,7.82,5577.0,"-1.6742, -1.1972, -1.0062, -0.879, -0.7799, -0.6943, -0.6241, -0.5599, -0.5021, -0.4501"
130,num_804,float32,1066277.0,7.82,9294161.0,"-3.1064, -2.5511, -2.2446, -2.0331, -1.8659, -1.731, -1.6159, -1.5215, -1.432, -1.3464"
131,num_805,float32,1066277.0,7.82,11578.0,"-1.316, -1.0531, -1.2697, -1.5136, -1.1546, -0.93, -1.3589, -1.1211, -1.0842, -0.9614"
132,num_815,float32,1066277.0,7.82,285.0,"-0.9175, -0.6911, -1.1883, -0.5063, -0.3508, -0.2226, -1.5038, -0.1119, -0.018, 0.064"
133,num_816,float32,1066277.0,7.82,9358773.0,"-1.8953, -1.6576, -1.7725, -2.0248, -1.2697, -1.4533, -1.3577, -1.5536, -2.1697, -2.3351"
134,num_817,float32,1066277.0,7.82,325.0,"-0.2381, -0.1346, -0.2175, -0.1132, -0.3005, 0.0088, -0.093, -0.1957, 0.0289, -0.0728"
135,num_818,float32,1066277.0,7.82,259.0,"-0.9223, -0.6943, -0.5092, -1.1933, -0.3548, -0.2248, -1.5089, -0.1144, -0.0197, 0.0615"
136,num_819,float32,1066277.0,7.82,9359272.0,"-1.8953, -1.7739, -1.3628, -2.0306, -1.2753, -1.6641, -1.4569, -1.5568, -2.1697, -1.1895"
137,num_820,float32,1066277.0,7.82,337.0,"-0.1983, -0.1562, -0.1359, -0.1144, 0.0289, -0.1777, -0.2601, -0.2188, -0.3229, 0.0489"
138,num_821,float32,1066277.0,7.82,267.0,"-0.9198, -0.6943, -0.5092, -1.1895, -0.3535, -0.2252, -1.5057, -0.1144, -0.0188, 0.064"
139,num_822,float32,1066277.0,7.82,9363952.0,"-1.364, -1.8953, -2.0331, -1.5567, -1.7739, -1.6641, -1.2753, -1.4589, -2.1781, -1.1906"
140,num_823,float32,1066277.0,7.82,334.0,"-0.1778, -0.1575, -0.2201, -0.2835, -0.2614, -0.1359, -0.1995, -0.0942, -0.054, 0.0489"
141,num_824,float32,1066277.0,7.82,514.0,"-0.3071, -0.4143, -0.4404, -0.3335, -0.3602, -0.2549, -0.3871, -0.4682, -0.2809, -0.2047"
142,num_825,float32,1066277.0,7.82,7815886.0,"-0.0334, -0.2059, 0.2225, -0.1561, -0.2312, -0.0816, -0.1068, 0.0389, 0.0863, 0.155"
143,num_826,float32,1066277.0,7.82,568.0,"-0.2265, -0.2731, -0.3203, -0.2497, -0.2966, -0.3669, -0.3442, -0.4143, -0.1587, -0.3898"
144,num_827,float32,1066277.0,7.82,522.0,"-0.3058, -0.439, -0.3322, -0.4115, -0.4668, -0.3588, -0.2536, -0.3857, -0.2291, -0.5207"
145,num_828,float32,1066277.0,7.82,7811514.0,"-0.0389, 0.0088, -0.0873, -0.2111, -0.1119, 0.0797, 0.1027, -0.2861, -0.0149, 0.2176"
146,num_829,float32,1066277.0,7.82,580.0,"-0.3203, -0.2265, -0.2966, -0.3442, -0.2731, -0.3669, -0.2497, -0.2034, -0.1804, -0.3911"
147,num_830,float32,1066277.0,7.82,498.0,"-0.4978, -0.3097, -0.2575, -0.2316, -0.4156, -0.3362, -0.4696, -0.2835, -0.3629, -0.3884"
148,num_831,float32,1066277.0,7.82,7812790.0,"-0.0386, -0.1104, -0.2098, -0.0863, -0.16, -0.2601, 0.009, 0.3057, 0.1496, 0.2179"
149,num_832,float32,1066277.0,7.82,577.0,"-0.3468, -0.3229, -0.2523, -0.2757, -0.2304, -0.2992, -0.417, -0.2072, -0.3696, -0.1626"
150,num_833,float32,1066277.0,7.82,372.0,"-0.478, -0.3979, -0.5207, -0.4376, -0.5628, -0.606, -0.3203, -0.6487, -0.7414, -0.3575"
151,num_834,float32,1066277.0,7.82,8281361.0,"-0.2004, -0.6821, -0.5485, 0.2599, -0.26, -0.5155, -0.1123, -0.3847, 0.0007, 0.2835"
152,num_835,float32,1066277.0,7.82,412.0,"-0.2979, -0.2731, -0.2484, -0.146, -0.3508, -0.3243, -0.197, -0.3763, -0.1207, -0.4556"
153,num_836,float32,1066277.0,7.82,377.0,"-0.5235, -0.4808, -0.439, -0.3979, -0.6534, -0.609, -0.5643, -0.3588, -0.6991, -0.3203"
154,num_837,float32,1066277.0,7.82,8279254.0,"-0.2653, -0.1166, -0.7217, -0.5525, -0.7557, 0.2802, -0.3263, -0.5195, -0.6877, 0.2554"
155,num_838,float32,1066277.0,7.82,419.0,"-0.2744, -0.3522, -0.3256, -0.3005, -0.2484, -0.1473, -0.0968, -0.2226, -0.0477, -0.0728"
156,num_839,float32,1066277.0,7.82,377.0,"-0.4808, -0.5207, -0.439, -0.3979, -0.609, -0.3203, -0.5643, -0.6959, -0.3575, -0.2809"
157,num_840,float32,1066277.0,7.82,8278847.0,"-0.2655, -0.7193, -0.1179, -0.1758, 0.1804, -0.0608, -0.2059, 0.2549, -0.3275, -0.5192"
158,num_841,float32,1066277.0,7.82,415.0,"-0.2992, -0.1983, -0.0716, -0.1473, -0.2226, -0.2744, -0.2484, -0.3256, -0.3522, -0.4047"
159,num_842,float32,1066277.0,7.82,387.0,"-0.579, -0.5438, -0.4752, -0.6165, -0.5092, -0.6534, -0.6911, -0.4418, -0.4088, -0.3763"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
num_0,1363927.0,0.011929,0.966405,-1.663369,5.199337
num_1,1363927.0,0.012664,0.968333,-1.693591,5.199337
num_2,1363927.0,0.001468,0.998096,-5.199337,4.554733
num_3,1363927.0,0.045415,0.864491,-0.748138,3.810157
num_4,1363927.0,0.017554,0.998097,-5.199337,5.199337
num_5,1363927.0,-0.004201,0.936901,-2.818956,5.199337
num_6,1363927.0,-0.052900,0.682164,-5.199337,3.152530
num_7,1363927.0,0.019544,0.936857,-1.689670,5.199337
num_8,1348267.0,-0.016434,0.994686,-5.199337,3.389254
num_9,1348267.0,-0.080083,0.999855,-5.199337,5.199337
num_10,1347913.0,-0.017069,0.992691,-5.199337,3.289543
num_11,1363927.0,0.086058,0.988849,-5.199337,5.199337
num_12,1363927.0,-0.016544,0.996881,-5.199337,5.199337
num_13,1363927.0,-0.018890,0.998321,-5.199337,5.199337
num_14,1363927.0,-0.000406,0.015102,-0.000479,3.415837
num_15,1363927.0,-0.018770,0.992934,-5.199337,5.199337
num_16,1363927.0,0.000090,1.001169,-5.148797,4.992494
num_17,1363927.0,-0.060262,0.994827,-5.199337,3.899677
num_18,1363927.0,-0.072829,0.998716,-5.199337,5.199337
num_19,1363927.0,0.042941,0.876021,-0.804920,5.199337
num_20,1363927.0,-0.019513,0.994059,-5.199337,5.199337
num_21,1184945.0,0.063351,0.813427,-3.160128,5.199337
num_22,1363927.0,0.028306,0.963056,-1.503596,2.538295
num_23,1363927.0,0.079555,0.737579,-0.328619,5.199337
num_24,1363927.0,0.015783,0.997417,-3.563641,5.199337
num_25,1363927.0,0.002012,0.996541,-5.199337,5.199337
num_26,1363927.0,0.073967,0.994193,-5.199337,4.416880
num_27,1363927.0,-0.012074,0.995632,-5.199337,5.199337
num_28,1363927.0,-0.018445,0.995997,-5.199337,5.199337
num_29,1363927.0,0.043008,0.798942,-5.199337,3.089935
num_30,1363927.0,0.016233,0.797067,-1.880352,5.199337
num_31,1363927.0,0.003824,0.939113,-2.212092,5.199337
num_32,1363927.0,0.021359,0.970415,-1.633964,5.199337
num_33,1363927.0,0.056370,0.576130,-0.131710,5.199337
num_34,1346905.0,0.067193,0.861579,-0.726606,5.199337
num_35,1346905.0,-0.011834,0.995911,-5.199337,4.142645
num_36,1346905.0,-0.015068,0.988984,-5.199337,5.199337
num_37,1346905.0,0.066667,0.861145,-0.726606,5.199337
num_38,1346905.0,-0.012018,0.995820,-5.199337,5.199337
num_39,1346905.0,-0.014437,0.987988,-5.199337,5.199337
num_40,1346905.0,0.066448,0.860724,-0.724973,5.199337
num_41,1346905.0,-0.010627,0.995545,-5.199337,5.199337
num_42,1346905.0,-0.013595,0.988770,-5.199337,5.199337
num_43,1346580.0,0.069547,0.607195,-0.163824,2.196894
num_44,1346580.0,0.000279,0.983095,-1.873053,2.196894
num_45,1346580.0,-0.063986,0.737103,-1.865852,0.451469
num_46,1346569.0,0.069256,0.606669,-0.163824,2.196894
num_47,1346569.0,0.002113,0.981994,-1.865852,2.196894
num_48,1346569.0,-0.064176,0.737372,-1.865852,0.451469
num_49,1346562.0,0.069961,0.609959,-0.165095,2.211128
num_50,1346562.0,0.000395,0.982783,-1.873053,2.196894
num_51,1346562.0,-0.064116,0.736707,-1.865852,0.450080
num_52,1346905.0,0.026530,0.918857,-1.088722,5.199337
num_53,1346905.0,-0.034926,1.001429,-5.199337,5.199337
num_54,1346905.0,-0.057230,0.989260,-5.199337,5.199337
num_55,1346905.0,0.027495,0.917115,-1.085702,5.199337
num_56,1346905.0,-0.036994,1.000323,-5.199337,5.199337
num_57,1346905.0,-0.060103,0.990835,-5.199337,3.632564
num_58,1346905.0,0.026041,0.918685,-1.087211,5.199337
num_59,1346905.0,-0.035578,1.000529,-5.199337,5.199337
num_60,1346905.0,-0.055683,0.991272,-5.199337,5.199337
num_61,1346905.0,-0.024880,0.997205,-5.199337,5.199337
num_62,1346905.0,-0.060414,1.003410,-5.199337,5.199337
num_63,1346905.0,-0.052772,1.004821,-3.937680,5.199337
num_64,1346905.0,-0.023110,0.996906,-3.661994,5.199337
num_65,1346905.0,-0.058778,1.002808,-5.199337,5.199337
num_66,1346905.0,-0.050742,1.004688,-5.199337,5.199337
num_67,1346905.0,-0.023862,0.999133,-3.661996,5.199337
num_68,1346905.0,-0.060070,1.004042,-5.199337,5.199337
num_69,1346905.0,-0.053002,1.003411,-5.199337,3.902086
num_70,1346905.0,-0.023108,1.001812,-5.199337,5.199337
num_71,1346905.0,-0.058375,1.002893,-5.199337,3.782581
num_72,1346905.0,-0.061889,1.000554,-5.199337,3.640457
num_73,1346905.0,-0.021278,1.002628,-5.199337,5.199337
num_74,1346905.0,-0.058251,1.004042,-5.199337,3.639781
num_75,1346905.0,-0.061248,1.000399,-5.199337,4.255464
num_76,1346905.0,-0.022760,1.002666,-5.199337,5.199337
num_77,1346905.0,-0.058075,1.004275,-5.199337,3.945505
num_78,1346905.0,-0.062591,1.000916,-5.199337,5.199337
num_79,1346905.0,-0.018992,1.009173,-5.199337,3.979631
num_80,1346905.0,-0.056222,1.002767,-5.199337,5.199337
num_81,1346905.0,-0.064712,1.002328,-3.979583,5.199337
num_82,1346905.0,-0.017572,1.008380,-5.199337,5.199337
num_83,1346905.0,-0.056290,1.004435,-5.199337,3.582027
num_84,1346905.0,-0.062173,1.001369,-5.199337,5.199337
num_85,1346905.0,-0.017705,1.009415,-5.199337,5.199337
num_86,1346905.0,-0.054361,1.003634,-5.199337,5.199337
num_87,1346905.0,-0.064826,1.000613,-5.199337,5.199337
num_88,1346905.0,-0.003556,0.993482,-5.199337,5.199337
num_89,1346905.0,-0.000799,0.991959,-5.199337,2.211128
num_90,1363927.0,-0.050782,1.000883,-5.199337,3.682554
num_91,1346905.0,-0.056372,1.003273,-3.724245,3.581844
num_92,1346905.0,-0.055081,1.002867,-5.199337,5.199337
num_93,1346905.0,-0.055754,1.003115,-3.726416,4.093787
num_94,1363927.0,-0.034891,0.958436,-2.510826,1.431971
num_95,1346905.0,0.050614,1.002321,-5.199337,5.199337
num_96,1363927.0,-0.038507,0.946617,-4.137304,1.225943
num_97,1362441.0,-0.078239,1.000131,-5.199337,5.199337
num_98,1362441.0,-0.076564,1.000043,-5.199337,5.199337
num_99,1362441.0,-0.078853,1.000402,-5.199337,5.199337
num_100,1332426.0,0.077049,1.032865,-3.855330,5.199337
num_101,1332426.0,0.074215,1.032032,-5.199337,5.199337
num_102,1332426.0,0.077960,1.029314,-5.199337,5.199337
num_103,1363927.0,-0.068389,0.619912,-1.643877,0.203379
num_104,1227192.0,-0.042888,0.999707,-5.199337,3.647771
num_105,1227192.0,-0.052630,1.001731,-5.199337,5.199337
num_106,1227192.0,-0.056367,0.999899,-4.461810,3.647655
num_107,1363722.0,-0.076951,0.999678,-5.199337,5.199337
num_108,1361734.0,-0.052968,1.002968,-3.931383,3.751593
num_109,1363927.0,-0.052763,1.002117,-5.199337,3.438659
num_110,1363927.0,-0.056372,1.009501,-5.199337,3.520006
num_111,1363927.0,-0.008552,1.005934,-4.054945,5.199337
num_112,1363927.0,0.001628,0.999318,-5.199337,4.301982
num_113,1363927.0,0.064460,0.628627,-0.170263,5.090231
num_114,1363927.0,0.011240,0.993660,-2.737934,5.199337
num_115,1363927.0,0.021972,0.867821,-1.066304,5.199337
num_116,1363927.0,-0.037286,0.872709,-2.737934,5.199337
num_117,1363927.0,0.009814,0.951216,-2.138280,5.199337
num_118,1304919.0,-0.002614,0.984211,-5.199337,5.199337
num_119,1304919.0,-0.059524,0.995021,-4.190054,5.199337
num_120,1277427.0,-0.013569,0.997107,-5.199337,3.416348
num_121,1363927.0,0.056392,0.985858,-3.761941,5.199337
num_122,1363927.0,-0.010799,1.005637,-5.154060,3.901481
num_123,1363927.0,-0.013415,0.998368,-5.199337,5.199337
num_124,1363927.0,-0.022625,1.002327,-5.199337,5.199337
num_125,1363927.0,-0.001885,0.996890,-4.581935,2.392751
num_126,1363927.0,-0.039473,0.997079,-5.108028,5.199337
num_127,1363927.0,-0.050262,0.993660,-5.199337,5.199337
num_128,1363927.0,0.070336,0.687713,-0.243788,4.992494
num_129,1363927.0,-0.020307,0.994634,-5.199337,5.199337
num_130,681817.0,0.063684,0.772883,-3.089933,5.199337
num_131,1363927.0,0.067843,0.840094,-0.667837,2.029513
num_132,1363927.0,0.045358,0.491137,-0.073446,5.199337
num_133,1363927.0,0.009161,0.999567,-4.186700,5.199337
num_134,1363927.0,-0.000617,0.995353,-5.199337,3.498560
num_135,1363927.0,0.044071,0.991997,-5.199337,5.199337
num_136,1363927.0,-0.010377,1.007168,-5.199337,5.199337
num_137,1363927.0,-0.017489,0.990085,-5.199337,5.199337
num_138,1363927.0,0.007302,0.817157,-5.199337,5.199337
num_139,1363927.0,0.016598,0.873493,-2.241016,5.199337
num_140,1363927.0,0.021833,0.873973,-1.027247,3.539804
num_141,1363927.0,0.063967,0.848027,-0.651277,3.468400
num_142,1363927.0,0.016943,0.298590,-0.017804,5.199337
num_143,1263164.0,0.026424,0.953513,-1.391202,5.199337
num_144,1263164.0,-0.005482,0.997903,-3.121935,3.576511
num_145,1263164.0,-0.007110,0.995941,-3.124751,5.199337
num_146,1263164.0,0.024218,0.953387,-1.391202,5.199337
num_147,1263164.0,-0.005894,0.997188,-3.106872,5.199337
num_148,1263164.0,-0.008757,0.995829,-3.123759,5.199337
num_149,1263164.0,0.024112,0.954530,-1.391202,5.199337
num_150,1263164.0,-0.005292,0.996934,-3.104759,5.199337
num_151,1263164.0,-0.005962,0.993743,-3.105958,5.199337
num_152,1261630.0,0.071868,0.699650,-0.325577,1.792374
num_153,1261630.0,0.033826,0.889336,-0.987652,1.798663
num_154,1261630.0,-0.005227,0.789109,-0.987652,0.959440
num_155,1261613.0,0.072799,0.699367,-0.324254,1.792374
num_156,1261613.0,0.031799,0.887926,-0.987652,1.792374
num_157,1261613.0,-0.004148,0.790120,-0.987652,0.961429
num_158,1261599.0,0.072007,0.700719,-0.326900,1.792374
num_159,1261599.0,0.032714,0.888703,-0.989697,1.792374
num_160,1261599.0,-0.003673,0.789426,-0.987652,0.959440
num_161,1263164.0,0.008766,0.959125,-1.474029,5.199337
num_162,1263164.0,-0.024553,1.002282,-5.199337,3.601406
num_163,1263164.0,-0.043231,0.990190,-5.199337,4.100385
num_164,1263164.0,0.010288,0.957487,-1.469090,5.199337
num_165,1263164.0,-0.025588,1.003119,-5.199337,5.199337
num_166,1263164.0,-0.041077,0.990335,-5.199337,5.199337
num_167,1263164.0,0.010851,0.958156,-1.470321,5.199337
num_168,1263164.0,-0.022363,1.002366,-5.199337,5.199337
num_169,1263164.0,-0.041013,0.989601,-5.199337,5.199337
num_170,1263164.0,-0.022984,1.000336,-5.199337,4.164286
num_171,1263164.0,-0.045644,1.002328,-5.199337,5.199337
num_172,1263164.0,-0.049526,1.001994,-3.505006,5.199337
num_173,1263164.0,-0.022682,1.000081,-3.764572,5.199337
num_174,1263164.0,-0.046458,1.001140,-5.199337,5.199337
num_175,1263164.0,-0.049104,1.000960,-5.199337,5.199337
num_176,1263164.0,-0.022550,1.001027,-5.199337,5.199337
num_177,1263164.0,-0.045190,1.000621,-5.199337,4.060939
num_178,1263164.0,-0.047118,1.001322,-5.199337,5.199337
num_179,1263164.0,-0.019495,1.001688,-5.199337,3.637206
num_180,1263164.0,-0.043290,1.000742,-5.199337,5.199337
num_181,1263164.0,-0.051931,0.996361,-3.710190,5.199337
num_182,1263164.0,-0.020601,1.002609,-5.199337,5.199337
num_183,1263164.0,-0.042835,1.001057,-3.770217,5.199337
num_184,1263164.0,-0.051145,0.998168,-5.199337,5.199337
num_185,1263164.0,-0.020142,1.000408,-5.199337,5.199337
num_186,1263164.0,-0.043887,1.001711,-5.199337,5.199337
num_187,1263164.0,-0.051681,0.996689,-3.962566,5.199337
num_188,1263164.0,-0.013133,1.001262,-5.199337,3.510141
num_189,1263164.0,-0.040377,0.999898,-5.199337,5.199337
num_190,1263164.0,-0.054314,0.997254,-5.199337,5.199337
num_191,1263164.0,-0.015449,1.001959,-5.199337,3.546563
num_192,1263164.0,-0.039391,1.000348,-5.199337,3.631361
num_193,1263164.0,-0.054454,0.996418,-5.199337,5.199337
num_194,1263164.0,-0.016495,1.001360,-5.199337,5.199337
num_195,1263164.0,-0.041395,0.999839,-5.199337,5.199337
num_196,1263164.0,-0.054642,0.998012,-5.199337,5.199337
num_197,1263164.0,0.000272,0.999246,-4.315856,5.199337
num_198,1263164.0,0.023257,0.918855,-5.199337,1.805023
num_199,1363927.0,-0.035011,0.995558,-5.199337,4.012959
num_200,1263164.0,-0.043630,1.001056,-5.199337,4.394820
num_201,1263164.0,-0.040347,0.999911,-5.199337,5.199337
num_202,1263164.0,-0.040464,1.000005,-5.199337,5.199337
num_203,1363927.0,-0.061882,0.834383,-1.798694,0.681594
num_204,1263164.0,0.034656,1.000255,-5.199337,5.199337
num_205,1363927.0,-0.077942,0.811031,-2.285268,0.530745
num_206,1332745.0,-0.059598,0.995899,-5.199337,3.566141
num_207,1332745.0,-0.056667,0.996331,-5.199337,5.199337
num_208,1332745.0,-0.058618,0.994906,-4.458950,5.199337
num_209,1234579.0,0.056533,1.007174,-3.785064,3.786044
num_210,1234579.0,0.055230,1.008855,-5.199337,3.576153
num_211,1234579.0,0.055911,1.007062,-5.199337,5.199337
num_212,1363927.0,-0.054690,0.558387,-1.641445,0.147316
num_213,1226425.0,-0.027366,0.997997,-3.905597,5.199337
num_214,1226425.0,-0.036016,0.996872,-3.757642,5.199337
num_215,1226425.0,-0.041215,0.997715,-5.199337,4.154056
num_216,1360590.0,-0.051501,0.994031,-4.026777,5.199337
num_217,1352615.0,-0.037101,0.999048,-3.751846,4.453102
num_218,1363927.0,-0.035508,0.996841,-5.199337,3.582392
num_219,1363927.0,-0.031284,1.004950,-5.199337,5.199337
num_220,1363927.0,-0.003153,1.004065,-3.920989,5.199337
num_221,1363924.0,0.000671,1.000582,-5.199337,4.276866
num_222,1363924.0,0.072808,0.689863,-0.254068,3.105533
num_223,1363924.0,0.011228,0.977217,-2.215973,5.199337
num_224,1363924.0,0.055723,0.731424,-0.443149,5.199337
num_225,1363924.0,0.002891,0.945540,-2.203955,5.199337
num_226,1363924.0,0.010955,0.946325,-1.938580,5.199337
num_227,1335508.0,-0.010351,0.982756,-5.199337,5.199337
num_228,1335508.0,-0.061788,0.989517,-5.199337,5.199337
num_229,1322491.0,-0.004228,0.997364,-5.199337,5.199337
num_230,1363924.0,0.069645,0.983807,-3.805390,5.199337
num_231,1363924.0,-0.012180,0.996714,-5.199337,5.166578
num_232,1363924.0,-0.012179,0.989619,-5.199337,5.199337
num_233,1363924.0,-0.019804,0.995090,-5.199337,5.199337
num_234,1363924.0,-0.003505,0.982971,-4.973094,1.997600
num_235,1363924.0,-0.052845,0.988401,-5.199337,5.199337
num_236,1363924.0,-0.062498,0.988086,-5.199337,5.199337
num_237,1363924.0,0.070339,0.661744,-0.214931,3.134759
num_238,1363924.0,-0.020330,0.994192,-3.937214,5.199337
num_239,71626.0,0.022666,0.925070,-5.199337,5.199337
num_240,1363924.0,0.044855,0.467270,-0.064250,2.314860
num_241,1363924.0,0.041301,0.467494,-0.061870,5.199337
num_242,1363924.0,0.008322,0.998485,-4.547389,5.199337
num_243,1363924.0,0.003807,0.997071,-5.199337,4.274081
num_244,1363924.0,0.068159,0.983658,-4.100795,5.199337
num_245,1363924.0,-0.006551,0.995358,-5.199337,5.199337
num_246,1363924.0,-0.017601,0.966618,-5.199337,5.199337
num_247,1363924.0,0.019090,0.821819,-5.199337,5.199337
num_248,1363924.0,-0.015088,0.910441,-5.199337,5.199337
num_249,1363924.0,0.052918,0.803183,-0.604448,5.199337
num_250,1363924.0,0.066820,0.845276,-0.642071,5.199337
num_251,1363924.0,0.024684,0.348912,-0.025340,5.199337
num_252,1306808.0,0.008121,0.973255,-1.705570,3.320711
num_253,1306808.0,-0.009783,0.995591,-3.205093,3.567872
num_254,1306808.0,-0.009852,0.991960,-3.185848,5.199337
num_255,1306808.0,0.006311,0.972926,-1.705570,3.716875
num_256,1306808.0,-0.008288,0.994986,-3.180909,5.199337
num_257,1306808.0,-0.009401,0.992830,-3.188526,5.199337
num_258,1306808.0,0.008000,0.973228,-1.700222,3.356191
num_259,1306808.0,-0.011288,0.995500,-3.181451,5.199337
num_260,1306808.0,-0.009746,0.993111,-3.163823,5.199337
num_261,1305244.0,0.073228,0.679545,-0.276998,1.887754
num_262,1305244.0,0.067141,0.795518,-0.533636,1.887754
num_263,1305244.0,0.048172,0.749470,-0.535083,1.394512
num_264,1305221.0,0.074780,0.679589,-0.275694,1.887754
num_265,1305221.0,0.066054,0.796295,-0.535083,1.887754
num_266,1305221.0,0.049043,0.748984,-0.533636,1.394512
num_267,1305198.0,0.076248,0.680612,-0.275694,1.887754
num_268,1305198.0,0.066321,0.794644,-0.535083,1.880353
num_269,1305198.0,0.048785,0.748604,-0.535083,1.391202
num_270,1306808.0,-0.012191,0.985975,-2.404842,3.796915
num_271,1306808.0,-0.028443,0.994012,-5.199337,5.199337
num_272,1306808.0,-0.046583,0.987762,-5.199337,5.199337
num_273,1306808.0,-0.010662,0.986867,-2.414621,3.584780
num_274,1306808.0,-0.028301,0.995309,-5.199337,3.542965
num_275,1306808.0,-0.048112,0.986948,-5.199337,3.853696
num_276,1306808.0,-0.011010,0.987893,-2.411243,3.676183
num_277,1306808.0,-0.027132,0.995371,-5.199337,3.579844
num_278,1306808.0,-0.045675,0.987818,-5.199337,4.090553
num_279,1306808.0,-0.031457,0.997719,-5.199337,5.199337
num_280,1306808.0,-0.046628,1.002362,-5.199337,5.199337
num_281,1306808.0,-0.050295,1.000573,-5.199337,3.872408
num_282,1306808.0,-0.034210,0.998542,-5.199337,3.711990
num_283,1306808.0,-0.045302,1.001667,-3.936670,5.199337
num_284,1306808.0,-0.049300,1.000465,-5.199337,3.904212
num_285,1306808.0,-0.031072,0.999209,-5.199337,5.199337
num_286,1306808.0,-0.046477,1.001642,-5.199337,3.920260
num_287,1306808.0,-0.050395,1.001423,-5.199337,3.995303
num_288,1306808.0,-0.027825,0.997586,-5.199337,5.199337
num_289,1306808.0,-0.044613,0.999761,-5.199337,5.199337
num_290,1306808.0,-0.054817,0.997043,-5.199337,5.199337
num_291,1306808.0,-0.025535,0.996965,-5.199337,5.199337
num_292,1306808.0,-0.044685,0.999478,-5.199337,5.199337
num_293,1306808.0,-0.056224,0.998328,-5.199337,5.199337
num_294,1306808.0,-0.027136,0.998839,-5.199337,5.199337
num_295,1306808.0,-0.042927,1.000086,-4.187087,5.199337
num_296,1306808.0,-0.055636,0.997000,-5.199337,5.199337
num_297,1306808.0,-0.021621,0.994413,-5.199337,5.199337
num_298,1306808.0,-0.041634,0.997493,-5.199337,5.199337
num_299,1306808.0,-0.055836,0.999481,-5.199337,3.764484
num_300,1306808.0,-0.022968,0.995500,-5.199337,5.199337
num_301,1306808.0,-0.041843,0.996808,-5.199337,3.958381
num_302,1306808.0,-0.056899,0.999503,-5.199337,3.648815
num_303,1306808.0,-0.024413,0.994868,-5.199337,5.199337
num_304,1306808.0,-0.042303,0.997962,-5.199337,5.199337
num_305,1306808.0,-0.056676,0.997424,-5.199337,5.199337
num_306,1306808.0,-0.002155,0.994306,-4.351150,3.124515
num_307,1306808.0,0.053555,0.837228,-5.199337,1.887754
num_308,1363924.0,-0.038773,0.996214,-5.199337,5.199337
num_309,1306808.0,-0.043340,0.997412,-5.199337,5.199337
num_310,1306808.0,-0.042768,0.997905,-5.199337,5.199337
num_311,1306808.0,-0.040637,0.996112,-5.199337,5.199337
num_312,1363924.0,-0.067735,0.585787,-2.044775,0.139710
num_313,1306808.0,0.034628,1.000039,-5.199337,5.199337
num_314,1363924.0,-0.032364,0.399326,-2.659998,0.038901
num_315,1353166.0,-0.063021,0.989806,-5.199337,5.199337
num_316,1353166.0,-0.061774,0.989079,-5.199337,5.199337
num_317,1353166.0,-0.062381,0.989807,-5.199337,5.199337
num_318,1288935.0,0.066320,1.009172,-4.336300,5.199337
num_319,1288935.0,0.066075,1.008991,-5.199337,5.199337
num_320,1288935.0,0.066376,1.007261,-4.336886,5.199337
num_321,1363924.0,-0.051018,0.545108,-1.639391,0.138444
num_322,1226247.0,-0.031976,0.991463,-3.734093,5.199337
num_323,1226247.0,-0.044109,0.996462,-3.466324,5.199337
num_324,1226247.0,-0.044195,0.998392,-3.341166,5.199337
num_325,1362684.0,-0.063546,0.989154,-5.199337,5.199337
num_326,1356739.0,-0.042261,0.997077,-5.199337,5.199337
num_327,1363924.0,-0.041685,0.996403,-5.199337,5.199337
num_328,1363924.0,-0.062603,0.996756,-5.199337,3.756571
num_329,1363924.0,-0.013897,1.005819,-5.199337,5.199337
num_330,1363915.0,0.000324,1.000210,-5.199337,4.199903
num_331,1363915.0,0.071864,0.707607,-0.284120,2.905879
num_332,1363915.0,0.014379,0.964350,-2.026541,5.199337
num_333,1363915.0,0.061829,0.680343,-0.313694,5.199337
num_334,1363915.0,0.005927,0.941801,-2.025239,5.199337
num_335,1363915.0,0.011920,0.943380,-1.869955,5.199337
num_336,1340137.0,-0.011783,0.979664,-5.199337,5.199337
num_337,1340137.0,-0.067022,0.986656,-5.199337,3.966434
num_338,1326803.0,-0.003224,0.998361,-4.063238,3.194063
num_339,1363915.0,0.072534,0.984516,-5.199337,5.199337
num_340,1363915.0,-0.014785,0.997406,-5.199337,5.199337
num_341,1363915.0,-0.013453,0.983025,-5.199337,5.199337
num_342,1363915.0,-0.018842,0.994746,-5.199337,5.199337
num_343,1363915.0,-0.005920,0.977708,-5.069501,1.898292
num_344,1363915.0,-0.057513,0.985035,-5.199337,5.199337
num_345,1363915.0,-0.065418,0.986925,-5.199337,5.199337
num_346,1363915.0,0.065742,0.633206,-0.182031,3.109230
num_347,1363915.0,-0.019356,0.993846,-5.199337,5.199337
num_348,41158.0,0.014124,0.961563,-5.199337,5.199337
num_349,1363915.0,0.029943,0.387411,-0.038125,2.382749
num_350,1363915.0,0.040736,0.449573,-0.052480,5.199337
num_351,1363915.0,0.008995,0.997217,-4.386655,3.389440
num_352,1363915.0,0.003118,0.996274,-3.882524,5.199337
num_353,1363915.0,0.074444,0.982628,-5.199337,5.199337
num_354,1363915.0,-0.007738,0.995073,-5.199337,5.199337
num_355,1363915.0,-0.017318,0.962778,-5.199337,5.199337
num_356,1363915.0,0.025533,0.828325,-5.199337,5.199337
num_357,1363915.0,-0.013832,0.914518,-5.199337,5.199337
num_358,1363915.0,0.059816,0.781862,-0.524976,5.199337
num_359,1363915.0,0.075192,0.835674,-0.593675,5.199337

In [7]:
# Categorical Feature Statistics
cat_stats

                              value    count    pct
column    rank
cat_0     1                       1  1054471  77.31
          2                       2    94971   6.96
          3                       7    55361   4.06
          4                       4    51581   3.78
          5                      10    36510   2.68
cat_1     1                       1  1054464  77.31
          2                       2    94971   6.96
          3                       7    55365   4.06
          4                       4    51581   3.78
          5                      10    36509   2.68
timestamp 1     2023-12-06 10:22:42        8   0.00
          2     2023-11-19 09:20:36        7   0.00
          3     2023-11-01 10:02:50        7   0.00
          4     2023-11-12 14:14:35        7   0.00
          5     2023-11-24 12:59:43        7   0.00

In [8]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,-0.17,-0.443,0.142,0.006,log,9194557.8,5.889561e+18,exponential

## Task Curation

In [9]:
from data_foundry.schema import PredictiveMLSplitsMetadata

date_col = task_mold.time_on
target_col = task_mold.target_column_name

df = df.sort_values(by=date_col).reset_index(drop=True)

test_time_min = df[date_col].max().normalize() - pd.DateOffset(weeks=1)

# Define indices
test_idx = df.index[df[date_col] >= test_time_min].to_numpy().tolist()
train_idx = df.index[
    df[date_col] < test_time_min
].to_numpy().tolist()

print("Train size:", len(train_idx), "| Test size:", len(test_idx))
print("Train target mean:", df.loc[train_idx, target_col].mean())
print("Test target mean:", df.loc[test_idx, target_col].mean())

splits = {0: {0: (train_idx, test_idx)}}

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="We use the last week as test data and all prior data as train data.",
    splits=splits
)

Train size: 10902438 | Test size: 2736834
Train target mean: 4.85484
Test target mean: 4.889229

## Export

In [12]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019c704a-391b-7eb8-ab62-8f248435892f
b286fabc21a10847ea15dd2400eb38e31ff33b31203837e4c62a13b39ff18eb6