### Dataset and Task Metadata

In [97]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="emscad",
    dataset_year="2014",
    domain_str="business & marketing",
    # Data Source
    dataset_source="Other",
    original_dataset_source_download_link="https://www.kaggle.com/datasets/shivamb/real-or-fake-fake-jobposting-prediction/data",
    download_description="""
The original website (http://icsdweb.aegean.gr/emscad) has been down for a while.
Thus, we us an alternative source from Kaggle (https://www.kaggle.com/datasets/shivamb/real-or-fake-fake-jobposting-prediction/data).
There is also an additional alternative source from Kaggle (https://www.kaggle.com/datasets/amruthjithrajvr/recruitment-scam).

kaggle datasets download -d shivamb/real-or-fake-fake-jobposting-prediction -f fake_job_postings.csv && unzip fake_job_postings.csv.zip fake_job_postings.csv&& rm fake_job_postings.csv.zip
mkdir -p local-data-warehouse/emscad && mv fake_job_postings.csv local-data-warehouse/emscad
""",
    # References
    academic_reference_bibtex="""@article{vidros2017automatic,
  title={Automatic detection of online recruitment frauds: Characteristics, methods, and a public dataset},
  author={Vidros, Sokratis and Kolias, Constantinos and Kambourakis, Georgios and Akoglu, Leman},
  journal={Future Internet},
  volume={9},
  number={1},
  pages={6},
  year={2017},
  publisher={MDPI}
}
""",
    academic_reference_bibtex_key="vidros2017automatic",
    licence="CC0: Public Domain", # from Kaggle, paper does not state anything, website is down to check -> so maybe None...
    data_tags=["IID", "Spatial"],
    curation_comments="""
We have no access to the original state and the data already contains some preprocessed features.
The paper describes them in more detail as well in Table 2.

In the original paper, the authors subsampled the data to have 450 fraudulent and 450 non-fraudulent samples.
No details are given on how the subsampling was done. Moreover, duplicates were skipped, but no details are given on how duplicates were identified.

- The dataset was collected from 2012 to 2014. But the data contains no feature to identify the time of a sample. So we can expect that some bias from temporal leakage. Moreover, the data might contain multiple job postings from the same fraudster, which would need to be grouped, but we cannot identify them from the data.
- Following the original paper, we drop all duplicates (when ignoring the job_id column) to avoid data leakage.
- The data has a location description, we do not resolve it lat/longitude but leave it to the pipelines.
- The salary range has several weird quirks. It contains data either in the thousands, or is missing the "k" to denote thousands. Moreover, it contains empty or 0-0 entries. The column might contain yearly salary, hourly salary, or one-time payment. Finally, for some jobs, the column contains a date (e.g. "Oct-20"). We keep the column as complex as it is. We add one column that contains the maximum salary parsed from the text and we only keep salary values above 50k as valid values to create a numerical feature for differences in the larger ranges.
- We removed job listings with non english texts (138 rows).
- We do not subsample the data, as a result, the data is heavily imbalanced.
- We found no relation of job_id with a timestamp and even found cases where a lower job_id has a description claiming to be a job from 2014 (so the end of the collection period). Thus, we do dropped job_id as it does not contain any signal.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="fraudulent",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="fraudulent",
)

## Preprocessing

In [223]:
import pandas as pd
import  numpy as np
df = pd.read_csv(dataset_mold.path / "fake_job_postings.csv")
print("Loaded data shape:", df.shape)

# Drop duplicates
df = df[~df.drop(columns=["job_id"]).duplicated(keep="last")]

# Get max salary proxy for larger ranges
s = df["salary_range"].astype(str).str.strip()
invalid_mask = (df["salary_range"].isna() | (s == '') | (s == '0-0'))
ranges = s.str.split('-', expand=True)
min_vals, max_vals = ranges[0], ranges[1]
is_not_salary_range = pd.to_numeric(max_vals, errors="coerce").isna() | pd.to_numeric(min_vals, errors="coerce").isna() # remove dates
not_above_50_k =  ~(pd.to_numeric(max_vals, errors="coerce") >= 50_000)
df["salary_range_max"] = pd.to_numeric(max_vals, errors="coerce")
df.loc[invalid_mask | is_not_salary_range |not_above_50_k, "salary_range_max"] = np.nan

# from langdetect import detect, LangDetectException
#
# def is_not_english(text: str) -> bool:
#     try:
#         return detect(text) != "en"
#     except LangDetectException:
#         # Raised for very short or ambiguous text
#         return False
# df["is_english_description"] = df["description"].astype(str).apply(lambda x: not is_not_english(x))
# bad_filter_list = [
#     # Missing, faulty or, Lorem ipsum description...
#     1243,
#     3031,
#     7613,
#     5557,
#     11078,
#     11894,
#     12190,
#     13530,
# ]
# print(list(df[(~df["is_english_description"]) & (~df["description"].isna()) & (df["description"] != "Sales Executive") & (~df["job_id"].isin(bad_filter_list))]["job_id"]))
# Output from the above
filter_non_en_job = [543, 550, 557, 687, 936, 986, 1174, 1558, 1667, 1689, 1794, 1831, 1922, 2351, 2384, 2424, 2474, 2677, 2788, 2857, 2929, 2967, 2986, 3126, 3132, 3139, 3156, 3169, 3566, 3576, 3702, 3764, 3856, 3952, 3993, 4157, 4185, 4193, 4315, 4362, 4371, 4401, 4812, 4825, 4867, 5058, 5198, 5274, 5632, 5637, 5651, 5693, 5724, 5931, 6023, 6096, 6169, 6184, 6269, 6284, 6438, 6445, 6573, 6587, 6699, 6752, 6853, 6988, 7025, 7112, 7212, 7549, 7679, 7849, 7881, 8066, 8106, 8214, 8355, 8365, 8397, 8615, 8719, 8791, 8895, 9216, 9393, 9413, 9965, 10450, 10468, 10557, 10570, 10661, 11075, 11314, 11320, 11383, 11419, 11424, 11426, 11427, 11446, 11449, 11463, 11464, 11536, 11631, 11748, 11958, 12231, 12395, 12683, 12973, 13016, 13301, 13474, 13476, 13551, 13696, 14021, 14131, 14333, 14911, 15185, 15410, 16343, 16500, 16586, 16608, 16691, 17034, 17047, 17148, 17226, 17328, 17357, 17781]
df = df[~df["job_id"].isin(filter_non_en_job)]

as_string_col = [
    "title",
    "location",
    "department",
    "salary_range",
    # HTML fragments
    "company_profile",
    "description",
    "requirements",
    "benefits",
]
as_cat_type = [
    "telecommuting",
    "has_company_logo",
    "has_questions",
    "employment_type",
    "required_experience",
    "required_education",
    "industry",
    "function",
    "fraudulent",
]

for c in as_string_col:
    nan_mask = df[c].isna()
    df.loc[nan_mask, c] = np.nan
    df[c] = df[c].astype("string")

df[as_cat_type] = df[as_cat_type].astype("category")

df = df.drop(columns=["job_id"]).reset_index(drop=True)

# After our preprocessing, there is just one entry without a description, so we drop it as well.
df = df[~df["description"].isna()].reset_index(drop=True)

## Data Checks

In [224]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 17,460
Columns: 18

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)

Data quality checks completed.

In [225]:
# Sample Rows
df_head

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,salary_range_max
0,Marketing Intern,"US, NY, New York",Marketing,<NA>,"We're Food52, and we've created a groundbreaking and award-winning cooking site. We support, connect, and celebrate home cooks, and give them everything they need in one place.We have a top editorial, business, and engineering team. We're focused on using technology to find new and better ways to connect people around their specific food interests, and to offer them superb, highly curated information about food and cooking. We attract the most talented home cooks and contributors in the country; we also publish well-known professionals like Mario Batali, Gwyneth Paltrow, and Danny Meyer. And we have partnerships with Whole Foods Market and Random House.Food52 has been named the best food website by the James Beard Foundation and IACP, and has been featured in the New York Times, NPR, Pando Daily, TechCrunch, and on the Today Show.We're located in Chelsea, in New York City.","Food52, a fast-growing, James Beard Award-winning online food community and crowd-sourced and curated recipe hub, is currently interviewing full- and part-time unpaid interns to work in a small team of editors, executives, and developers in its New York City headquarters.Reproducing and/or repackaging existing Food52 content for a number of partner sites, such as Huffington Post, Yahoo, Buzzfeed, and more in their various content management systemsResearching blogs and websites for the Provisions by Food52 Affiliate ProgramAssisting in day-to-day affiliate program support, such as screening affiliates and assisting in any affiliate inquiriesSupporting with PR &amp; Events when neededHelping with office administrative work, such as filing, mailing, and preparing for meetingsWorking with developers to document bugs and suggest improvements to the siteSupporting the marketing and executive staff","Experience with content management systems a major plus (any blogging counts!)Familiar with the Food52 editorial voice and aestheticLoves food, appreciates the importance of home cooking and cooking with the seasonsMeticulous editor, perfectionist, obsessive attention to detail, maddened by typos and broken links, delighted by finding and fixing themCheerful under pressureExcellent communication skillsA+ multi-tasker and juggler of responsibilities big and smallInterested in and engaged with social media like Twitter, Facebook, and PinterestLoves problem-solving and collaborating to drive Food52 forwardThinks big picture but pitches in on the nitty gritty of running a small company (dishes, shopping, administrative support)Comfortable with the realities of working for a startup: being on call on evenings and weekends, and working long hours",<NA>,0,1,0,Other,Internship,NaN,NaN,Marketing,0,NaN
1,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,<NA>,"90 Seconds, the worlds Cloud Video Production Service.90 Seconds is the worlds Cloud Video Production Service enabling brands and agencies to get high quality online video content shot and produced anywhere in the world. 90 Seconds makes video production fast, affordable, and all managed seamlessly in the cloud from purchase to publish. http://90#URL_fbe6559afac620a3cd2c22281f7b8d0eef56a73e3d9a311e2f1ca13d081dd630#90 Seconds removes the hassle, cost, risk and speed issues of working with regular video production companies by managing every aspect of video projects in a beautiful online experience. With a growing global network of over 2,000 rated video professionals in over 50 countries managed by dedicated production success teams in 5 countries, 90 Seconds provides a 100% success guarantee.90 Seconds has produced almost 4,000 videos in over 30 Countries for over 500 Global brands including some of the worlds largest including Paypal, L’Oreal, Sony and Barclays and has offices in Auckland, London, Sydney, Tokyo and Singapore.http://90#URL_fbe6559afac620a3cd2c22281f7b8d0eef56a73e3d9a311e2f1ca13d081dd630# | http://90#URL_e2ad0bde3f09a0913a486abdbb1e6ac373bb3310f64b1fbcf550049bcba4a17b# | http://90#URL_8c5dd1806f97ab90876d9daebeb430f682dbc87e2f01549b47e96c7bff2ea17e#","Organised - Focused - Vibrant - Awesome!Do you have a passion for customer service? Slick typing skills? Maybe Account Management? ...And think administration is cooler than a polar bear on a jetski? Then we need to hear you! We are the Cloud Video Production Service and opperating on a glodal level. Yeah, it's pretty cool. Serious about delivering a world class product and excellent customer service.Our rapidly expanding business is looking for a talented Project Manager to manage the successful delivery of video projects, manage client communications and drive the production process. Work with some of the coolest brands on the planet and learn from a global team that are representing NZ is a huge way!We are entering the next growth stage of our business and growing quickly internationally. Therefore, the position is bursting with opportunity for the right person entering the business at the right time. 90 Seconds, the worlds Cloud Video Production Service - http://90#URL_fbe6559afac620a3cd2c22281f7b8d0eef56a73e3d9a311e2f1ca13d081dd630#90 Seconds is the worlds Cloud Video Production Service enabling brands and agencies to get high quality online video content shot and produced anywhere in the world. Fast, affordable, and all managed seamlessly in the cloud from purchase to publish. 90 Seconds removes the hassle, cost, risk and speed issues of working with regular video production companies by managing every aspect of video projects in a beautiful online experience. With a growing network of over 2,000 rated video professionals in over 50 countries and dedicated production success teams in 5 countries guaranteeing video project success 100%. It's as easy as commissioning a quick google adwords campaign.90 Seconds has produced almost 4,000 videos in over 30 Countries for over 500 Global brands including some of the worlds largest including Paypal, L'oreal, Sony and Barclays and has offices in Auckland, London, Sydney, Tokyo &amp; Singapore.Our Auckland office is based right in the heart of the Wynyard Quarter Innovation Precinct - GridAKL!","What we expect from you:Your key responsibility will be to communicate with the client, 90 Seconds team and freelance community throughout the video production process including, shoot planning, securing freelance talent, managing workflow and the online production management system. The aim is to manage each video project effectively so that we produce great videos that our clients love.Key attributesClient focused - excellent customer service and communication skillsOnline - oustanding computer knowledge and experience using online software and project management toolsOrganised - manage workload and able to multi-task100% attention to detailMotivated - self-starter with a passion for doing excellent work and achieving great resultsAdaptable - show initiative and think on your feet as this is a constantly evolving atmosphereFlexible - fast turnaround work and after hours availabilityEasy going &amp; upbeat - dosen't get bogged down and loves the challengeSense of Humour - have a laugh and know that working in a startup takes guts!Ability to deliver - including meeting project deadlines and budgetAttitude is more important than experience at 90 Seconds, however previous experience in customer service and/or project management is beneficialPlease view our platform / website at #URL_395a8683a907ce95f49a12fb240e6e47ad8d5a4f96d07ebbd869c4dd4dea1826# and get a clear understand about what we do before reaching out.","What you will get from usThrough being part of the 90 Seconds team you will gain:experience working on projects located around the world with an international brandexperience working with a variety of clients and on a large range of projectsopportunity to drive and grow production function and teama positive working environment with a great teamPay$40,000-$55,000Applying for this role with a VIDEOBeing a video business, we understand that one of the quickest ways that we can assess your suitability for this role, and one of the quickest ways that you can apply for it, is for you to submit a 60-90 second long video telling us about yourself, your experience and why you think you would be perfect for the role. It’s not about being a filmmaker or making a really creative video. A simple video filmed with a smart phone or web cam will be fine. Please also include where you are based and when you can start.You can upload the video onto YouTube or Vimeo (or similar) as a Draft or Live link.APPLICATIONS DUE by 5pm on Wednesday 18th July 2014 - Once you have a video ready, apply for this role via the following link together with a cover letter and your CV. After we have watched your video and get an idea of your suitability for the role, we will email the shortlisted candidates",0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,NaN
2,Commissioning Machinery Assistant (CMA),"US, IA, Wever",<NA>,<NA>,"Valor Services provides Workforce Solutions that meet the needs of companies across the Private Sector, with a special focus on the Oil &amp; Gas Industry. Valor Services will be involved with you throughout every step of the hiring process and remain in contact with you all the way through the final step of signing of the employment contract with your new employer. Valor Services was founded with the vision of employing the unique skills, experiences, and qualities of America’s finest veterans to provide Private Sector companies with precise and concerted value-added services – and America’s finest Veterans with an optimized career opportunity.We are eager to get the word out to veterans that there are ample opportunities for employment in the private sector and that you are the ideal candidates to fill those positions. Valor Services Your Success is Our Mission. ™","Our client, located in Houston, is actively seeking an experienced Commissioning Machinery Assistant that possesses strong supervisory skills and has an attention to detail. A strong dedication to safety is a must. The ideal candidate will execute all activities while complying with quality requirements and health, environmental, and safety regulations.","Implement pre-commissioning and commissioning procedures for rotary equipment.Execute all activities with subcontractor’s assigned crew that pertains to the discipline.Ensure effective utilization of commissioning manpower and consumables.Ensure the execution of vendor specialists' field activities with the assigned resources from the sub-contractor per vendor’s representative plans.Carry out equipment inspections with client representatives and ensure proper certification is produced.Prepare forms for all pending tests and submit signed certificates for final hand over to the certification engineer for QA and QC.Coordinate in the field with vendor representatives.Keep records of all activities.Ensure that safety practices are strictly followed during the execution of activities.Report progress and constraints to the mechanical supervisor.Possible authorization by site manager to receive or issue a Permit To Work according to project Permit To Work procedures.Assist supervisor to expedite pending punch-list items in accordance with the commissioning manager’s priorities.Assist supervisor to coordinate and supervise construction-support activities during pre-commissioning and commissioning activities.Company Overview:Our client is a premiere engineering, construction, and procurement company that executes large-scale projects internationally.",<NA>,0,1,0,NaN,NaN,NaN,NaN,NaN,0,NaN
3,Account Executive - Washington DC,"US, DC, Washington",Sales,<NA>,"Our passion for improving quality of life through geography is at the heart of everything we do. Esri’s geographic information system (GIS) technology inspires and enables governments, universities and businesses worldwide to save money, lives and our environment through a deeper understanding of the changing world around them.Carefully managed growth and zero debt give Esri stability that is uncommon in today's volatile business world. Privately held, we offer exceptional benefits, competitive salaries, 401(k) and profit-sharing programs, opportunities for personal and professional growth, and much more.","THE COMPANY: ESRI – Environmental Systems Research InstituteOur passion for improving quality of life through geography is at the heart of everything we do. Esri’s geographic information system (GIS) technology inspires and enables governments, universities and businesses worldwide to save money, lives and our environment through a deeper understanding of the changing world around them.Carefully managed growth and zero debt give Esri stability that is uncommon in today's volatile business world. Privately held, we offer exceptional benefits, competitive salaries, 401(k) and profit-sharing programs, opportunities for personal and professional growth, and much more.THE OPPORTUNITY: Account ExecutiveAs a member of the Sales Division, you will work collaboratively with an account team in order to sell and promote adoption of Esri’s ArcGIS platform within an organization. As part of an account team, you will be responsible for facilitating the development and execution of a set of strategies for a defined portfolio of accounts. When executing these strategies you will utilize your experience in enterprise sales to help customers leverage geospatial information and technology to achieve their business goals. Specifically…Prospect and develop opportunities to partner with key stakeholders to envision, develop, and implement a location strategy for their organizationClearly articulate the strength and value proposition of the ArcGIS platformDevelop and maintain a healthy pipeline of opportunities for business growthDemonstrate a thoughtful understanding of insightful industry knowledge and how GIS applies to initiatives, trends, and triggersUnderstand the key business drivers within an organization and identify key business stakeholdersUnderstand your customers’ budgeting and acquisition processesSuccessfully execute the account management process including account prioritization, account resourcing, and account planningSuccessfully execute the sales process for all opportunitiesLeverage and lead an account team consisting of sales and other cross-divisional resources to define and execute an account strategyEffectively utilize and leverage the CRM to manage opportunities and drive the buying processPursue professional and personal development to ensure competitive knowledge of the real estate industryLeverage social media to successfully prospect and build a professional networkParticipate in trade shows, workshops, and seminars (as required)Support visual story telling through effective whiteboard sessionsBe resourceful and takes initiative to resolve issues","EDUCATION: Bachelor’s or Master’s in GIS, business administration, or a related field, or equivalent work experience, depending on position levelEXPERIENCE: 5+ years of enterprise sales experience providing platform solutions to businessesDemonstrated experience in managing the sales cycle including prospecting, proposing, and closingAbility to adapt to new technology trends and translate them into solutions that address customer needsDemonstrated experience with strong partnerships and advocacy with customersExcellent presentation, white boarding, and negotiation skills including good listening, probing, and qualification abilitiesExperience executing insight selling methodologiesDemonstrated understanding and mitigation of competitive threatsExcellent written and verbal communication and interpersonal skillsAbility to manage and prioritize your activitiesDemonstrated experience to lead executive engagements to provide services and sell to the real estate industryKnowledge of the real estate industry fiscal year, budgeting, and procurement cycleHighly motivated team player with a mature, positive attitude and passion to meet the challenges and opportunities of a businessAbility to travel domestically and/or internationally up to 50%General knowledge of spatial analysis and problem solvingResults oriented; ability to write and craft smart, attainable, realistic, time-driven goals with clear lead indicators","Our culture is anything but corporate—we have a collaborative, creative environment; phone directories organized by first name; a relaxed dress code; and open-door policies.A Place to ThrivePassionate people who strive to make a differenceCasual dress codeFlexible work schedulesSupport for continuing educationCollege-Like CampusA network of buildings amid lush landscaping and numerous outdoor patio areasOn-site café including a Starbucks coffee bar and lounge areaFitness center available 24/7Comprehensive reference library and GIS bibliographyState-of-the-art conference center to host staff and guest speakers Green InitiativesSolar rooftop panels reduce carbon emissionsElectric vehicles provide on-campus transportationHundreds of trees reduce the cost of cooling buildings",0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,NaN

In [226]:
# Feature Summary
summary

                  index     dtype  n_missing  pct_missing  n_unique  \
0    required_education  category       7932        45.43        13
1   required_experience  category       6890        39.46         7
2              function  category       6310        36.14        37
3              industry  category       4778        27.37       131
4       employment_type  category       3376        19.34         5
5         telecommuting  category          0         0.00         2
6      has_company_logo  category          0         0.00         2
7         has_questions  category          0         0.00         2
8            fraudulent  category          0         0.00         2
9      salary_range_max   float64      15972        91.48       119
10         salary_range    string      14644        83.87       872
11           department    string      11232        64.33      1321
12             benefits    string       7067        40.48      6130
13      company_profile    string       3257        18.65      1683
14         requirements    string       2630        15.06     11865
15             location    string        333         1.91      3084
16                title    string          0         0.00     11134
17          description    string          0         0.00     14683

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   examples
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Bachelor's Degree, High School or equivalent, Unspecified, Master's Degree, Associate Degree, Certification, Some College Coursework Completed, Professional, Vocational, Some High School Coursework

In [227]:
# Numeric Feature Statistics
numeric_stats

                   count          mean           std      min           max
salary_range_max  1488.0  1.530745e+06  3.737839e+07  50000.0  1.200000e+09

In [228]:
# Categorical Feature Statistics
cat_stats

                                                                                        value  \
column              rank
benefits            1                                                                    <NA>
                    2                                                     See job description
                    3                                                       Career prospects.
                    4     CSD offers a competitive benefits package for full-time employee...
                    5     Plenty of perksAs well as the opportunity to solve complex probl...
company_profile     1                                                                    <NA>
                    2                   We help teachers get safe &amp; secure jobs abroad :)
                    3     We Provide Full Time Permanent Positions for many medium to larg...
                    4     Novitex Enterprise Solutions, formerly Pitney Bowes Management S...
                    5     Established on the principles that full time education is not fo...
department          1                                                                    <NA>
                    2                                                                   Sales
                    3                                                             Engineering
                    4                                                               Marketing
                    5                                                              Operations
description         1     Play with kids, get paid for it Love travel? Jobs in Asia$1,500+...
                    2     Play with kids, get paid for it :-)Love travel? Jobs in Asia$150...
                    3     Play with kids, get paid for it Love travel? Jobs in Asia$1500 U...
                    4     Play with kids, get paid for it :-)Love travel? Jobs in Asia$150...
                    5     The International Broadcaster shall properly complete all daily ...
employment_type     1                                                               Full-time
                    2                                                                    <NA>
                    3                                                                Contract
                    4                                                               Part-time
                    5                                                               Temporary
fraudulent          1                                                                       0
                    2                                                                       1
function            1                                                                    <NA>
                    2                                                  Information Technology
                    3                                                                   Sales
                    4                                                             Engineering
                    5                                                        Customer Service
has_company_logo    1                                                                       1
                    2                                                                       0
has_questions       1                                                                       0
                    2                                                                       1
industry            1                                                                    <NA>
                    2                                     Information Technology and Services
                    3                                                       Computer Software
                    4                                                                Internet
                    5                                                    Education Management
location            1                                                         GB, LND, London
                    2                                                        US, NY, New York
                    3                                                   US, CA, San Francisco
                    4                                                           GR, I, Athens
                    5                                                                  US, ,
required_education  1                                                                    <NA>
                    2                                                       Bachelor's Degree
                    3                                               High School or equivalent
                    4                                                             Unspecified
                    5                                                         Master's Degree
required_experience 1                                                                    <NA>
                    2                                                        Mid-Senior level
                    3                                                             Entry level
                    4                                                               Associate
                    5                                                          Not Applicable
requirements        1                                                                    <NA>
                    2     University degree required. TEFL / TESOL / CELTA or teaching exp...
                    3     University degree required. TEFL / TESOL / CELTA or teaching exp...
                    4     16-18 year olds only due to government funding.Full time availab...
                    5     Minimum Requirements:Minimum of 6 months customer service relate...
salary_range        1                                                                    <NA>
                    2                                                                     0-0
                    3                                                             40000-50000
                    4                                                             30000-40000
                    5                                                             45000-67000
telecommuting       1                                                                       0
                    2                                                                       1
title               1                                                 English Teacher Abroad
                    2                      Graduates: English Teacher Abroad (Conversational)
                    3                                             Customer Service Associate
                    4                                                  English Teacher Abroad
                    5                                                       Software Engineer

                          count    pct
column              rank
benefits            1      7067  40.48
                    2       723   4.14
                    3       131   0.75
                    4        59   0.34
                    5        58   0.33
company_profile     1      3257  18.65
                    2       723   4.14
                    3       665   3.81
                    4       550   3.15
                    5       403   2.31
department          1     11232  64.33
                    2       536   3.07
                    3       479   2.74
                    4       397   2.27
                    5       266   1.52
description         1       376   2.15
                    2        66   0.38
                    3        46   0.26
                    4        32   0.18
                    5        31   0.18
employment_type     1     11348  64.99
                    2      3376  19.34
                    3      1511   8.65
                    4       768    4.4
                    5       235   1.35
fraudulent          1     16607  95.11
                    2       853   4.89
function            1      6310  36.14
                    2      1708   9.78
                    3      1443   8.26
                    4      1329   7.61
                    5      1178   6.75
has_company_logo    1     13861  79.39
                    2      3599  20.61
has_questions       1      8890  50.92
                    2      8570  49.08
industry            1      4778  27.37
                    2      1684   9.64
                    3      1360   7.79
                    4      1041   5.96
                    5       819   4.69
location            1       718   4.11
                    2       644   3.69
                    3       466   2.67
                    4       441   2.53
                    5       339   1.94
required_education  1      7932  45.43
                    2      5056  28.96
                    3      1987  11.38
                    4      1360   7.79
                    5       412   2.36
required_experience 1      6890  39.46
                    2      3737   21.4
                    3      2619   15.0
                    4      2260  12.94
                    5      1064   6.09
requirements        1      2630  15.06
                    2       407   2.33
                    3       163   0.93
                    4        96   0.55
                    5        75   0.43
salary_range        1     14644  83.87
                    2       141   0.81
                    3        66   0.38
                    4        54   0.31
                    5        36   0.21
telecommuting       1     16708  95.69
                    2       752   4.31
title               1       309   1.77
                    2       144   0.82
                    3       141   0.81
                    4        94   0.54
                    5        84   0.48

In [229]:
# Target Distribution
target_df

            count    pct
fraudulent
0           16607  95.11
1             853   4.89

## Task Curation

In [230]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from sklearn.model_selection import RepeatedStratifiedKFold

n_repeats, n_splits = 3, 3
assert task_mold.stratify_on == task_mold.target_column_name
sklearn_splits = RepeatedStratifiedKFold(
    n_repeats=n_repeats, n_splits=n_splits, random_state=42
).split(X=df.drop(columns=[task_mold.target_column_name]), y=df[task_mold.target_column_name])

splits = {}
for split_i, (train_idx, test_idx) in enumerate(sklearn_splits):
    repeat_i = split_i // n_splits
    fold_i = split_i % n_splits
    if repeat_i not in splits:
        splits[repeat_i] = {}
    splits[repeat_i][fold_i] = (train_idx.tolist(), test_idx.tolist())

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="In the original paper, 10-fold CV is used. We follow our default suggestions in the case of IID.",
    splits=splits,
)

## Export

In [231]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019bf56c-467d-7805-baab-94b17ee9dc04
aeb4f16183e3e5201ba5042e0d4db89bd491e06cf0a63e15b0128722af75ee9c