### Dataset and Task Metadata

In [2]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="mercedes_benz_greener_manufacturing",
    dataset_year="2017",
    domain_str="industry & manufacturing",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/mercedes-benz-greener-manufacturing",
    download_description="""
We use the train.csv from the Kaggle competition.

kaggle competitions download -c mercedes-benz-greener-manufacturing -f train.csv.zip && unzip train.csv.zip &&  rm train.csv.zip
mkdir -p local-data-warehouse/mercedes_benz_greener_manufacturing && mv train.csv local-data-warehouse/mercedes_benz_greener_manufacturing/
""",
    # References
    academic_reference_bibtex=r"""@misc{Novy2017MercedesBenzGreenerManufacturing,
  author = {Alexander Novy and CH1Mercedes and Christian Drescher and Christian Pfaundler and KOESIM and Will Cukierski},
  title  = {Mercedes-Benz Greener Manufacturing},
  year   = {2017},
  howpublished = {\url{https://kaggle.com/competitions/mercedes-benz-greener-manufacturing}},
  note   = {Kaggle competition}
}
""",
    academic_reference_bibtex_key="Novy2017MercedesBenzGreenerManufacturing",
    licence="Kaggle Competition Rules",
    data_tags=["Non-IID", "Anonymized"],
    curation_comments="""
We start with the train.csv from Kaggle.

- The data has been anonymized, so feature meanings are unknown.
- There is generally weird behavior related to the ID and potentially a time column (see X5 here https://www.kaggle.com/competitions/mercedes-benz-greener-manufacturing/discussion/34949). However, it is hard to parse the exact details due to anonymization. We generally take from this that the data is sorted sequentially by ID and that there may be time dependencies. Also checkout https://www.kaggle.com/code/sudalairajkumar/simple-exploration-notebook-mercedes which shows relation between index and y, showing that y goes up with higher index and it shows that X5 (the time group feature), has the highest importance. Plus, it has one outlier.
- We remove the one outlier from y.
- We drop X5 as it leaks time group information in temporal splits (besides having a full categorical-value distribution shift with a temporal split).
- We tread the ID as a time_index.
- Some of the other constructed features (X0-X8) may leak across time as well. We remove all of them for which we do not have an explanation from experts on Kaggle.
- There are exactly 4 rows that have value that is not equal to "d" in column "X4". This indicates some kind of sub-group or data different. Given the lack of semantics and anonymity, we cannot parse the meaning of "X4". Thus, to avoid this being an indicator of data leakage, we remove these rows and subsequently drop "X4" as well.
- We drop other constructed features from up to X10 for which we have no information about them and they may leak group information across rows.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="y",
    problem_type="regression",
    objective_metric_name="rmse", # r2 in competition, which is inferior to rmse for regression tasks
    time_on="time_index",
)

## Preprocessing

In [27]:
import pandas as pd

df = pd.read_csv(dataset_mold.path / "train.csv")
print("Loaded data shape:", df.shape)

# Remove on huge y outlier that seems like a clear shift case
df = df[df["y"] < 180]

# Handle constructed features: ['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']
#   - X0,X1,X2 likely only uses information per row
#   - X4 has 4 rows that are not "d", we drop these rows to avoid leakage and later drop X4
#   - X5, time group feature that leaks group time info in temporal splits
#   - X8 seems to leak group information across rows by having value assigned based on sampling from the distribution of all data, so we drop it as well
#   - We have no further information about X3 and X6, so we drop them as well to be safe, given the trend of other constructed features leaking info across rows.
df = df[df["X4"] == "d"]

df = df.drop(columns=["X5", "X8", "X4", "X3", "X6"])
df = df.rename(columns={"ID": "time_index"})
df = df.reset_index(drop=True)

## Data Checks

In [28]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 4,204
Columns: 373

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)

Data quality checks completed.

In [29]:
# Sample Rows
df_head

,time_index,y,X0,X1,X2,X10,X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,X21,X22,X23,X24,X26,X27,X28,X29,X30,X31,X32,X33,X34,X35,X36,X37,X38,X39,X40,X41,X42,X43,X44,X45,X46,X47,X48,X49,X50,X51,X52,X53,X54,X55,X56,X57,X58,X59,X60,X61,X62,X63,X64,X65,X66,X67,X68,X69,X70,X71,X73,X74,X75,X76,X77,X78,X79,X80,X81,X82,X83,X84,X85,X86,X87,X88,X89,X90,X91,X92,X93,X94,X95,X96,X97,X98,X99,X100,X101,X102,X103,X104,X105,X106,X107,X108,X109,X110,X111,X112,X113,X114,X115,X116,X117,X118,X119,X120,X122,X123,X124,X125,X126,X127,X128,X129,X130,X131,X132,X133,X134,X135,X136,X137,X138,X139,X140,X141,X142,X143,X144,X145,X146,X147,X148,X150,X151,X152,X153,X154,X155,X156,X157,X158,X159,X160,X161,X162,X163,X164,X165,X166,X167,X168,X169,X170,X171,X172,X173,X174,X175,X176,X177,X178,X179,X180,X181,X182,X183,X184,X185,X186,X187,X189,X190,X191,X192,X194,X195,X196,X197,X198,X199,X200,X201,X202,X203,X204,X205,X206,X207,X208,X209,X210,X211,X212,X213,X214,X215,X216,X217,X218,X219,X220,X221,X222,X223,X224,X225,X226,X227,X228,X229,X230,X231,X232,X233,X234,X235,X236,X237,X238,X239,X240,X241,X242,X243,X244,X245,X246,X247,X248,X249,X250,X251,X252,X253,X254,X255,X256,X257,X258,X259,X260,X261,X262,X263,X264,X265,X266,X267,X268,X269,X270,X271,X272,X273,X274,X275,X276,X277,X278,X279,X280,X281,X282,X283,X284,X285,X286,X287,X288,X289,X290,X291,X292,X293,X294,X295,X296,X297,X298,X299,X300,X301,X302,X304,X305,X306,X307,X308,X309,X310,X311,X312,X313,X314,X315,X316,X317,X318,X319,X320,X321,X322,X323,X324,X325,X326,X327,X328,X329,X330,X331,X332,X333,X334,X335,X336,X337,X338,X339,X340,X341,X342,X343,X344,X345,X346,X347,X348,X349,X350,X351,X352,X353,X354,X355,X356,X357,X358,X359,X360,X361,X362,X363,X364,X365,X366,X367,X368,X369,X370,X371,X372,X373,X374,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,1,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0,1,1,1,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [30]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,y,float64,0,0.0,2542,"90.76, 89.38, 91.88, 89.06, 89.19, 93.62, 89.6, 91.62, 90.44, 90.38"
1,time_index,int64,0,0.0,4204,"8417, 0, 6, 7, 9, 13, 18, 24, 25, 27"
2,X10,int64,0,0.0,2,"0, 1"
3,X11,int64,0,0.0,1,0
4,X12,int64,0,0.0,2,"0, 1"
5,X13,int64,0,0.0,2,"0, 1"
6,X14,int64,0,0.0,2,"0, 1"
7,X15,int64,0,0.0,2,"0, 1"
8,X16,int64,0,0.0,2,"0, 1"
9,X17,int64,0,0.0,2,"0, 1"
10,X18,int64,0,0.0,2,"0, 1"
11,X19,int64,0,0.0,2,"0, 1"
12,X20,int64,0,0.0,2,"0, 1"
13,X21,int64,0,0.0,2,"0, 1"
14,X22,int64,0,0.0,2,"0, 1"
15,X23,int64,0,0.0,2,"0, 1"
16,X24,int64,0,0.0,2,"0, 1"
17,X26,int64,0,0.0,2,"0, 1"
18,X27,int64,0,0.0,2,"1, 0"
19,X28,int64,0,0.0,2,"0, 1"
20,X29,int64,0,0.0,2,"0, 1"
21,X30,int64,0,0.0,2,"0, 1"
22,X31,int64,0,0.0,2,"0, 1"
23,X32,int64,0,0.0,2,"0, 1"
24,X33,int64,0,0.0,2,"0, 1"
25,X34,int64,0,0.0,2,"0, 1"
26,X35,int64,0,0.0,2,"0, 1"
27,X36,int64,0,0.0,2,"0, 1"
28,X37,int64,0,0.0,2,"0, 1"
29,X38,int64,0,0.0,2,"0, 1"
30,X39,int64,0,0.0,2,"0, 1"
31,X40,int64,0,0.0,2,"0, 1"
32,X41,int64,0,0.0,2,"0, 1"
33,X42,int64,0,0.0,2,"0, 1"
34,X43,int64,0,0.0,2,"0, 1"
35,X44,int64,0,0.0,2,"0, 1"
36,X45,int64,0,0.0,2,"0, 1"
37,X46,int64,0,0.0,2,"1, 0"
38,X47,int64,0,0.0,2,"0, 1"
39,X48,int64,0,0.0,2,"0, 1"
40,X49,int64,0,0.0,2,"0, 1"
41,X50,int64,0,0.0,2,"0, 1"
42,X51,int64,0,0.0,2,"1, 0"
43,X52,int64,0,0.0,2,"0, 1"
44,X53,int64,0,0.0,2,"0, 1"
45,X54,int64,0,0.0,2,"0, 1"
46,X55,int64,0,0.0,2,"0, 1"
47,X56,int64,0,0.0,2,"0, 1"
48,X57,int64,0,0.0,2,"0, 1"
49,X58,int64,0,0.0,2,"1, 0"
50,X59,int64,0,0.0,2,"0, 1"
51,X60,int64,0,0.0,2,"0, 1"
52,X61,int64,0,0.0,2,"1, 0"
53,X62,int64,0,0.0,2,"0, 1"
54,X63,int64,0,0.0,2,"0, 1"
55,X64,int64,0,0.0,2,"0, 1"
56,X65,int64,0,0.0,2,"0, 1"
57,X66,int64,0,0.0,2,"0, 1"
58,X67,int64,0,0.0,2,"0, 1"
59,X68,int64,0,0.0,2,"0, 1"
60,X69,int64,0,0.0,2,"0, 1"
61,X70,int64,0,0.0,2,"1, 0"
62,X71,int64,0,0.0,2,"0, 1"
63,X73,int64,0,0.0,2,"0, 1"
64,X74,int64,0,0.0,2,"1, 0"
65,X75,int64,0,0.0,2,"0, 1"
66,X76,int64,0,0.0,2,"0, 1"
67,X77,int64,0,0.0,2,"0, 1"
68,X78,int64,0,0.0,2,"0, 1"
69,X79,int64,0,0.0,2,"0, 1"
70,X80,int64,0,0.0,2,"1, 0"
71,X81,int64,0,0.0,2,"0, 1"
72,X82,int64,0,0.0,2,"0, 1"
73,X83,int64,0,0.0,2,"0, 1"
74,X84,int64,0,0.0,2,"0, 1"
75,X85,int64,0,0.0,2,"0, 1"
76,X86,int64,0,0.0,2,"0, 1"
77,X87,int64,0,0.0,2,"0, 1"
78,X88,int64,0,0.0,2,"0, 1"
79,X89,int64,0,0.0,2,"0, 1"
80,X90,int64,0,0.0,2,"0, 1"
81,X91,int64,0,0.0,2,"0, 1"
82,X92,int64,0,0.0,2,"0, 1"
83,X93,int64,0,0.0,1,0
84,X94,int64,0,0.0,2,"0, 1"
85,X95,int64,0,0.0,2,"0, 1"
86,X96,int64,0,0.0,2,"1, 0"
87,X97,int64,0,0.0,2,"0, 1"
88,X98,int64,0,0.0,2,"1, 0"
89,X99,int64,0,0.0,2,"0, 1"
90,X100,int64,0,0.0,2,"1, 0"
91,X101,int64,0,0.0,2,"1, 0"
92,X102,int64,0,0.0,2,"0, 1"
93,X103,int64,0,0.0,2,"1, 0"
94,X104,int64,0,0.0,2,"0, 1"
95,X105,int64,0,0.0,2,"0, 1"
96,X106,int64,0,0.0,2,"0, 1"
97,X107,int64,0,0.0,1,0
98,X108,int64,0,0.0,2,"0, 1"
99,X109,int64,0,0.0,2,"0, 1"
100,X110,int64,0,0.0,2,"0, 1"
101,X111,int64,0,0.0,2,"1, 0"
102,X112,int64,0,0.0,2,"0, 1"
103,X113,int64,0,0.0,2,"0, 1"
104,X114,int64,0,0.0,2,"0, 1"
105,X115,int64,0,0.0,2,"0, 1"
106,X116,int64,0,0.0,2,"0, 1"
107,X117,int64,0,0.0,2,"0, 1"
108,X118,int64,0,0.0,2,"1, 0"
109,X119,int64,0,0.0,2,"1, 0"
110,X120,int64,0,0.0,2,"1, 0"
111,X122,int64,0,0.0,2,"0, 1"
112,X123,int64,0,0.0,2,"0, 1"
113,X124,int64,0,0.0,2,"0, 1"
114,X125,int64,0,0.0,2,"0, 1"
115,X126,int64,0,0.0,2,"0, 1"
116,X127,int64,0,0.0,2,"0, 1"
117,X128,int64,0,0.0,2,"1, 0"
118,X129,int64,0,0.0,2,"0, 1"
119,X130,int64,0,0.0,2,"0, 1"
120,X131,int64,0,0.0,2,"0, 1"
121,X132,int64,0,0.0,2,"1, 0"
122,X133,int64,0,0.0,2,"0, 1"
123,X134,int64,0,0.0,2,"0, 1"
124,X135,int64,0,0.0,2,"0, 1"
125,X136,int64,0,0.0,2,"1, 0"
126,X137,int64,0,0.0,2,"1, 0"
127,X138,int64,0,0.0,2,"0, 1"
128,X139,int64,0,0.0,2,"0, 1"
129,X140,int64,0,0.0,2,"0, 1"
130,X141,int64,0,0.0,2,"0, 1"
131,X142,int64,0,0.0,2,"1, 0"
132,X143,int64,0,0.0,2,"0, 1"
133,X144,int64,0,0.0,2,"1, 0"
134,X145,int64,0,0.0,2,"0, 1"
135,X146,int64,0,0.0,2,"0, 1"
136,X147,int64,0,0.0,2,"0, 1"
137,X148,int64,0,0.0,2,"0, 1"
138,X150,int64,0,0.0,2,"1, 0"
139,X151,int64,0,0.0,2,"0, 1"
140,X152,int64,0,0.0,2,"0, 1"
141,X153,int64,0,0.0,2,"0, 1"
142,X154,int64,0,0.0,2,"0, 1"
143,X155,int64,0,0.0,2,"0, 1"
144,X156,int64,0,0.0,2,"1, 0"
145,X157,int64,0,0.0,2,"0, 1"
146,X158,int64,0,0.0,2,"0, 1"
147,X159,int64,0,0.0,2,"0, 1"
148,X160,int64,0,0.0,2,"0, 1"
149,X161,int64,0,0.0,2,"0, 1"
150,X162,int64,0,0.0,2,"0, 1"
151,X163,int64,0,0.0,2,"0, 1"
152,X164,int64,0,0.0,2,"0, 1"
153,X165,int64,0,0.0,2,"0, 1"
154,X166,int64,0,0.0,2,"0, 1"
155,X167,int64,0,0.0,2,"0, 1"
156,X168,int64,0,0.0,2,"0, 1"
157,X169,int64,0,0.0,2,"0, 1"
158,X170,int64,0,0.0,2,"0, 1"
159,X171,int64,0,0.0,2,"1, 0"
160,X172,int64,0,0.0,2,"0, 1"
161,X173,int64,0,0.0,2,"0, 1"
162,X174,int64,0,0.0,2,"0, 1"
163,X175,int64,0,0.0,2,"0, 1"
164,X176,int64,0,0.0,2,"0, 1"
165,X177,int64,0,0.0,2,"0, 1"
166,X178,int64,0,0.0,2,"1, 0"
167,X179,int64,0,0.0,2,"0, 1"
168,X180,int64,0,0.0,2,"0, 1"
169,X181,int64,0,0.0,2,"0, 1"
170,X182,int64,0,0.0,2,"0, 1"
171,X183,int64,0,0.0,2,"0, 1"
172,X184,int64,0,0.0,2,"0, 1"
173,X185,int64,0,0.0,2,"0, 1"
174,X186,int64,0,0.0,2,"1, 0"
175,X187,int64,0,0.0,2,"0, 1"
176,X189,int64,0,0.0,2,"1, 0"
177,X190,int64,0,0.0,2,"0, 1"
178,X191,int64,0,0.0,2,"0, 1"
179,X192,int64,0,0.0,2,"0, 1"
180,X194,int64,0,0.0,2,"0, 1"
181,X195,int64,0,0.0,2,"0, 1"
182,X196,int64,0,0.0,2,"0, 1"
183,X197,int64,0,0.0,2,"0, 1"
184,X198,int64,0,0.0,2,"0, 1"
185,X199,int64,0,0.0,2,"0, 1"
186,X200,int64,0,0.0,2,"0, 1"
187,X201,int64,0,0.0,2,"0, 1"
188,X202,int64,0,0.0,2,"0, 1"
189,X203,int64,0,0.0,2,"0, 1"
190,X204,int64,0,0.0,2,"0, 1"
191,X205,int64,0,0.0,2,"1, 0"
192,X206,int64,0,0.0,2,"0, 1"
193,X207,int64,0,0.0,2,"0, 1"
194,X208,int64,0,0.0,2,"0, 1"
195,X209,int64,0,0.0,2,"1, 0"
196,X210,int64,0,0.0,2,"0, 1"
197,X211,int64,0,0.0,2,"0, 1"
198,X212,int64,0,0.0,2,"0, 1"
199,X213,int64,0,0.0,2,"0, 1"
200,X214,int64,0,0.0,2,"0, 1"
201,X215,int64,0,0.0,2,"0, 1"
202,X216,int64,0,0.0,2,"0, 1"
203,X217,int64,0,0.0,2,"0, 1"
204,X218,int64,0,0.0,2,"0, 1"
205,X219,int64,0,0.0,2,"0, 1"
206,X220,int64,0,0.0,2,"1, 0"
207,X221,int64,0,0.0,2,"0, 1"
208,X222,int64,0,0.0,2,"0, 1"
209,X223,int64,0,0.0,2,"1, 0"
210,X224,int64,0,0.0,2,"0, 1"
211,X225,int64,0,0.0,2,"0, 1"
212,X226,int64,0,0.0,2,"0, 1"
213,X227,int64,0,0.0,2,"0, 1"
214,X228,int64,0,0.0,2,"0, 1"
215,X229,int64,0,0.0,2,"1, 0"
216,X230,int64,0,0.0,2,"0, 1"
217,X231,int64,0,0.0,2,"0, 1"
218,X232,int64,0,0.0,2,"0, 1"
219,X233,int64,0,0.0,1,0
220,X234,int64,0,0.0,2,"0, 1"
221,X235,int64,0,0.0,1,0
222,X236,int64,0,0.0,2,"0, 1"
223,X237,int64,0,0.0,2,"0, 1"
224,X238,int64,0,0.0,2,"1, 0"
225,X239,int64,0,0.0,2,"0, 1"
226,X240,int64,0,0.0,2,"0, 1"
227,X241,int64,0,0.0,2,"0, 1"
228,X242,int64,0,0.0,2,"0, 1"
229,X243,int64,0,0.0,2,"0, 1"
230,X244,int64,0,0.0,2,"0, 1"
231,X245,int64,0,0.0,2,"0, 1"
232,X246,int64,0,0.0,2,"0, 1"
233,X247,int64,0,0.0,2,"0, 1"
234,X248,int64,0,0.0,2,"0, 1"
235,X249,int64,0,0.0,2,"0, 1"
236,X250,int64,0,0.0,2,"1, 0"
237,X251,int64,0,0.0,2,"0, 1"
238,X252,int64,0,0.0,2,"0, 1"
239,X253,int64,0,0.0,2,"0, 1"
240,X254,int64,0,0.0,2,"0, 1"
241,X255,int64,0,0.0,2,"0, 1"
242,X256,int64,0,0.0,2,"0, 1"
243,X257,int64,0,0.0,2,"0, 1"
244,X258,int64,0,0.0,2,"0, 1"
245,X259,int64,0,0.0,2,"0, 1"
246,X260,int64,0,0.0,2,"0, 1"
247,X261,int64,0,0.0,2,"0, 1"
248,X262,int64,0,0.0,2,"0, 1"
249,X263,int64,0,0.0,2,"1, 0"
250,X264,int64,0,0.0,2,"0, 1"
251,X265,int64,0,0.0,2,"1, 0"
252,X266,int64,0,0.0,2,"0, 1"
253,X267,int64,0,0.0,2,"0, 1"
254,X268,int64,0,0.0,1,0
255,X269,int64,0,0.0,2,"0, 1"
256,X270,int64,0,0.0,2,"0, 1"
257,X271,int64,0,0.0,2,"0, 1"
258,X272,int64,0,0.0,2,"0, 1"
259,X273,int64,0,0.0,2,"1, 0"
260,X274,int64,0,0.0,2,"0, 1"
261,X275,int64,0,0.0,2,"1, 0"
262,X276,int64,0,0.0,2,"0, 1"
263,X277,int64,0,0.0,2,"0, 1"
264,X278,int64,0,0.0,2,"0, 1"
265,X279,int64,0,0.0,2,"0, 1"
266,X280,int64,0,0.0,2,"0, 1"
267,X281,int64,0,0.0,2,"0, 1"
268,X282,int64,0,0.0,2,"0, 1"
269,X283,int64,0,0.0,2,"0, 1"
270,X284,int64,0,0.0,2,"0, 1"
271,X285,int64,0,0.0,2,"0, 1"
272,X286,int64,0,0.0,2,"0, 1"
273,X287,int64,0,0.0,2,"0, 1"
274,X288,int64,0,0.0,2,"0, 1"
275,X289,int64,0,0.0,1,0
276,X290,int64,0,0.0,1,0
277,X291,int64,0,0.0,2,"0, 1"
278,X292,int64,0,0.0,2,"0, 1"
279,X293,int64,0,0.0,1,0
280,X294,int64,0,0.0,2,"0, 1"
281,X295,int64,0,0.0,2,"0, 1"
282,X296,int64,0,0.0,2,"0, 1"
283,X297,int64,0,0.0,1,0
284,X298,int64,0,0.0,2,"0, 1"
285,X299,int64,0,0.0,2,"0, 1"
286,X300,int64,0,0.0,2,"0, 1"
287,X301,int64,0,0.0,2,"0, 1"
288,X302,int64,0,0.0,2,"0, 1"
289,X304,int64,0,0.0,2,"1, 0"
290,X305,int64,0,0.0,2,"0, 1"
291,X306,int64,0,0.0,2,"0, 1"
292,X307,int64,0,0.0,2,"0, 1"
293,X308,int64,0,0.0,2,"0, 1"
294,X309,int64,0,0.0,2,"0, 1"
295,X310,int64,0,0.0,2,"0, 1"
296,X311,int64,0,0.0,2,"1, 0"
297,X312,int64,0,0.0,2,"0, 1"
298,X313,int64,0,0.0,2,"0, 1"
299,X314,int64,0,0.0,2,"0, 1"
300,X315,int64,0,0.0,2,"0, 1"
301,X316,int64,0,0.0,2,"0, 1"
302,X317,int64,0,0.0,2,"0, 1"
303,X318,int64,0,0.0,2,"0, 1"
304,X319,int64,0,0.0,2,"0, 1"
305,X320,int64,0,0.0,2,"0, 1"
306,X321,int64,0,0.0,2,"0, 1"
307,X322,int64,0,0.0,2,"0, 1"
308,X323,int64,0,0.0,2,"0, 1"
309,X324,int64,0,0.0,2,"1, 0"
310,X325,int64,0,0.0,2,"0, 1"
311,X326,int64,0,0.0,2,"0, 1"
312,X327,int64,0,0.0,2,"0, 1"
313,X328,int64,0,0.0,2,"0, 1"
314,X329,int64,0,0.0,2,"0, 1"
315,X330,int64,0,0.0,1,0
316,X331,int64,0,0.0,2,"0, 1"
317,X332,int64,0,0.0,2,"0, 1"
318,X333,int64,0,0.0,2,"0, 1"
319,X334,int64,0,0.0,2,"0, 1"
320,X335,int64,0,0.0,2,"0, 1"
321,X336,int64,0,0.0,2,"0, 1"
322,X337,int64,0,0.0,2,"1, 0"
323,X338,int64,0,0.0,2,"0, 1"
324,X339,int64,0,0.0,2,"0, 1"
325,X340,int64,0,0.0,2,"0, 1"
326,X341,int64,0,0.0,2,"0, 1"
327,X342,int64,0,0.0,2,"0, 1"
328,X343,int64,0,0.0,2,"0, 1"
329,X344,int64,0,0.0,2,"0, 1"
330,X345,int64,0,0.0,2,"0, 1"
331,X346,int64,0,0.0,2,"0, 1"
332,X347,int64,0,0.0,1,0
333,X348,int64,0,0.0,2,"1, 0"
334,X349,int64,0,0.0,2,"0, 1"
335,X350,int64,0,0.0,2,"0, 1"
336,X351,int64,0,0.0,2,"0, 1"
337,X352,int64,0,0.0,2,"0, 1"
338,X353,int64,0,0.0,2,"0, 1"
339,X354,int64,0,0.0,2,"0, 1"
340,X355,int64,0,0.0,2,"0, 1"
341,X356,int64,0,0.0,2,"0, 1"
342,X357,int64,0,0.0,2,"0, 1"
343,X358,int64,0,0.0,2,"0, 1"
344,X359,int64,0,0.0,2,"0, 1"
345,X360,int64,0,0.0,2,"0, 1"
346,X361,int64,0,0.0,2,"1, 0"
347,X362,int64,0,0.0,2,"1, 0"
348,X363,int64,0,0.0,2,"1, 0"
349,X364,int64,0,0.0,2,"0, 1"
350,X365,int64,0,0.0,2,"0, 1"
351,X366,int64,0,0.0,2,"0, 1"
352,X367,int64,0,0.0,2,"0, 1"
353,X368,int64,0,0.0,2,"0, 1"
354,X369,int64,0,0.0,2,"0, 1"
355,X370,int64,0,0.0,2,"0, 1"
356,X371,int64,0,0.0,2,"0, 1"
357,X372,int64,0,0.0,2,"0, 1"
358,X373,int64,0,0.0,2,"0, 1"
359,X374,int64,0,0.0,2,"0, 1"
360,X375,int64,0,0.0,2,"0, 1"
361,X376,int64,0,0.0,2,"0, 1"
362,X377,int64,0,0.0,2,"0, 1"
363,X378,int64,0,0.0,2,"0, 1"
364,X379,int64,0,0.0,2,"0, 1"
365,X380,int64,0,0.0,2,"0, 1"
366,X382,int64,0,0.0,2,"0, 1"
367,X383,int64,0,0.0,2,"0, 1"
368,X384,int64,0,0.0,2,"0, 1"
369,X385,int64,0,0.0,2,"0, 1"
370,X0,object,0,0.0,47,"z, ak, y, ay, t, x, o, f, n, w"
371,X1,object,0,0.0,27,"aa, s, b, l, v, r, i, a, c, o"
372,X2,object,0,0.0,44,"as, ae, ai, m, ak, r, n, s, f, e"

In [31]:
# Numeric Feature Statistics
numeric_stats

             count         mean          std    min      max
time_index  4204.0  4208.083492  2438.254452   0.00  8417.00
y           4204.0   100.619125    12.417569  72.11   169.91
X10         4204.0     0.013321     0.114657   0.00     1.00
X11         4204.0     0.000000     0.000000   0.00     0.00
X12         4204.0     0.075167     0.263691   0.00     1.00
X13         4204.0     0.058040     0.233847   0.00     1.00
X14         4204.0     0.428402     0.494906   0.00     1.00
X15         4204.0     0.000476     0.021809   0.00     1.00
X16         4204.0     0.002379     0.048720   0.00     1.00
X17         4204.0     0.007612     0.086923   0.00     1.00
X18         4204.0     0.007850     0.088260   0.00     1.00
X19         4204.0     0.099429     0.299273   0.00     1.00
X20         4204.0     0.142721     0.349830   0.00     1.00
X21         4204.0     0.002617     0.051091   0.00     1.00
X22         4204.0     0.087060     0.281956   0.00     1.00
X23         4204.0     0.020695     0.142377   0.00     1.00
X24         4204.0     0.001903     0.043586   0.00     1.00
X26         4204.0     0.004995     0.070509   0.00     1.00
X27         4204.0     0.682921     0.465394   0.00     1.00
X28         4204.0     0.032588     0.177577   0.00     1.00
X29         4204.0     0.043054     0.203003   0.00     1.00
X30         4204.0     0.004520     0.067083   0.00     1.00
X31         4204.0     0.232160     0.422261   0.00     1.00
X32         4204.0     0.011180     0.105155   0.00     1.00
X33         4204.0     0.000238     0.015423   0.00     1.00
X34         4204.0     0.005471     0.073772   0.00     1.00
X35         4204.0     0.232160     0.422261   0.00     1.00
X36         4204.0     0.004520     0.067083   0.00     1.00
X37         4204.0     0.232160     0.422261   0.00     1.00
X38         4204.0     0.033302     0.179444   0.00     1.00
X39         4204.0     0.000238     0.015423   0.00     1.00
X40         4204.0     0.000714     0.026707   0.00     1.00
X41         4204.0     0.011418     0.106255   0.00     1.00
X42         4204.0     0.000238     0.015423   0.00     1.00
X43         4204.0     0.072074     0.258642   0.00     1.00
X44         4204.0     0.011418     0.106255   0.00     1.00
X45         4204.0     0.253330     0.434970   0.00     1.00
X46         4204.0     0.596813     0.490596   0.00     1.00
X47         4204.0     0.012845     0.112619   0.00     1.00
X48         4204.0     0.022122     0.147097   0.00     1.00
X49         4204.0     0.122027     0.327356   0.00     1.00
X50         4204.0     0.213844     0.410067   0.00     1.00
X51         4204.0     0.721931     0.448101   0.00     1.00
X52         4204.0     0.042103     0.200847   0.00     1.00
X53         4204.0     0.006898     0.082778   0.00     1.00
X54         4204.0     0.043530     0.204071   0.00     1.00
X55         4204.0     0.005233     0.072159   0.00     1.00
X56         4204.0     0.021170     0.143969   0.00     1.00
X57         4204.0     0.013321     0.114657   0.00     1.00
X58         4204.0     0.574691     0.494449   0.00     1.00
X59         4204.0     0.000714     0.026707   0.00     1.00
X60         4204.0     0.001427     0.037756   0.00     1.00
X61         4204.0     0.954091     0.209312   0.00     1.00
X62         4204.0     0.005947     0.076894   0.00     1.00
X63         4204.0     0.011418     0.106255   0.00     1.00
X64         4204.0     0.375357     0.484273   0.00     1.00
X65         4204.0     0.002141     0.046225   0.00     1.00
X66         4204.0     0.026879     0.161749   0.00     1.00
X67         4204.0     0.001903     0.043586   0.00     1.00
X68         4204.0     0.073264     0.260600   0.00     1.00
X69         4204.0     0.029971     0.170529   0.00     1.00
X70         4204.0     0.920076     0.271208   0.00     1.00
X71         4204.0     0.103473     0.304612   0.00     1.00
X73         4204.0     0.019981     0.139951   0.00     1.00
X74         4204.0     0.999286     0.026707   0.00     1.00
X75         4204.0     0.035918     0.186108   0.00     1.00
X76         4204.0     0.043530     0.204071   0.00     1.00
X77         4204.0     0.012607     0.111584   0.00     1.00
X78         4204.0     0.005709     0.075350   0.00     1.00
X79         4204.0     0.025214     0.156793   0.00     1.00
X80         4204.0     0.947193     0.223674   0.00     1.00
X81         4204.0     0.229068     0.420283   0.00     1.00
X82         4204.0     0.017127     0.129758   0.00     1.00
X83         4204.0     0.001189     0.034470   0.00     1.00
X84         4204.0     0.103473     0.304612   0.00     1.00
X85         4204.0     0.407945     0.491511   0.00     1.00
X86         4204.0     0.001427     0.037756   0.00     1.00
X87         4204.0     0.000951     0.030835   0.00     1.00
X88         4204.0     0.007136     0.084183   0.00     1.00
X89         4204.0     0.000714     0.026707   0.00     1.00
X90         4204.0     0.007374     0.085565   0.00     1.00
X91         4204.0     0.001665     0.040776   0.00     1.00
X92         4204.0     0.000951     0.030835   0.00     1.00
X93         4204.0     0.000000     0.000000   0.00     0.00
X94         4204.0     0.007374     0.085565   0.00     1.00
X95         4204.0     0.000238     0.015423   0.00     1.00
X96         4204.0     0.758325     0.428149   0.00     1.00
X97         4204.0     0.004282     0.065302   0.00     1.00
X98         4204.0     0.942674     0.232493   0.00     1.00
X99         4204.0     0.008563     0.092152   0.00     1.00
X100        4204.0     0.690533     0.462329   0.00     1.00
X101        4204.0     0.935775     0.245182   0.00     1.00
X102        4204.0     0.006898     0.082778   0.00     1.00
X103        4204.0     0.784729     0.411059   0.00     1.00
X104        4204.0     0.001903     0.043586   0.00     1.00
X105        4204.0     0.002379     0.048720   0.00     1.00
X106        4204.0     0.013083     0.113643   0.00     1.00
X107        4204.0     0.000000     0.000000   0.00     0.00
X108        4204.0     0.014748     0.120556   0.00     1.00
X109        4204.0     0.040438     0.197007   0.00     1.00
X110        4204.0     0.000951     0.030835   0.00     1.00
X111        4204.0     0.975024     0.156071   0.00     1.00
X112        4204.0     0.002854     0.053357   0.00     1.00
X113        4204.0     0.022122     0.147097   0.00     1.00
X114        4204.0     0.146051     0.353200   0.00     1.00
X115        4204.0     0.285442     0.451679   0.00     1.00
X116        4204.0     0.196717     0.397564   0.00     1.00
X117        4204.0     0.049239     0.216392   0.00     1.00
X118        4204.0     0.622265     0.484879   0.00     1.00
X119        4204.0     0.622265     0.484879   0.00     1.00
X120        4204.0     0.957897     0.200847   0.00     1.00
X122        4204.0     0.007136     0.084183   0.00     1.00
X123        4204.0     0.002617     0.051091   0.00     1.00
X124        4204.0     0.000476     0.021809   0.00     1.00
X125        4204.0     0.003092     0.055529   0.00     1.00
X126        4204.0     0.038773     0.193076   0.00     1.00
X127        4204.0     0.495243     0.500037   0.00     1.00
X128        4204.0     0.958611     0.199212   0.00     1.00
X129        4204.0     0.122502     0.327904   0.00     1.00
X130        4204.0     0.041389     0.199212   0.00     1.00
X131        4204.0     0.026641     0.161052   0.00     1.00
X132        4204.0     0.688630     0.463109   0.00     1.00
X133        4204.0     0.124405     0.330083   0.00     1.00
X134        4204.0     0.022122     0.147097   0.00     1.00
X135        4204.0     0.027117     0.162444   0.00     1.00
X136        4204.0     0.956470     0.204071   0.00     1.00
X137        4204.0     0.581589     0.493357   0.00     1.00
X138        4204.0     0.040913     0.198113   0.00     1.00
X139        4204.0     0.090390     0.286774   0.00     1.00
X140        4204.0     0.040438     0.197007   0.00     1.00
X141        4204.0     0.014272     0.118625   0.00     1.00
X142        4204.0     0.770457     0.420589   0.00     1.00
X143        4204.0     0.038297     0.191935   0.00     1.00
X144        4204.0     0.808278     0.393702   0.00     1.00
X145        4204.0     0.001427     0.037756   0.00     1.00
X146        4204.0     0.040913     0.198113   0.00     1.00
X147        4204.0     0.022122     0.147097   0.00     1.00
X148        4204.0     0.044957     0.207235   0.00     1.00
X150        4204.0     0.792341     0.405680   0.00     1.00
X151        4204.0     0.085633     0.279854   0.00     1.00
X152        4204.0     0.032350     0.176949   0.00     1.00
X153        4204.0     0.000714     0.026707   0.00     1.00
X154        4204.0     0.208611     0.406364   0.00     1.00
X155        4204.0     0.076356     0.265598   0.00     1.00
X156        4204.0     0.717412     0.450311   0.00     1.00
X157        4204.0     0.282588     0.450311   0.00     1.00
X158        4204.0     0.229543     0.420589   0.00     1.00
X159        4204.0     0.013559     0.115663   0.00     1.00
X160        4204.0     0.001189     0.034470   0.00     1.00
X161        4204.0     0.197907     0.398469   0.00     1.00
X162        4204.0     0.040913     0.198113   0.00     1.00
X163        4204.0     0.303283     0.459731   0.00     1.00
X164        4204.0     0.062559     0.242198   0.00     1.00
X165        4204.0     0.004520     0.067083   0.00     1.00
X166        4204.0     0.033302     0.179444   0.00     1.00
X167        4204.0     0.000951     0.030835   0.00     1.00
X168        4204.0     0.270695     0.444371   0.00     1.00
X169        4204.0     0.006660     0.081348   0.00     1.00
X170        4204.0     0.024025     0.153144   0.00     1.00
X171        4204.0     0.657707     0.474534   0.00     1.00
X172        4204.0     0.005947     0.076894   0.00     1.00
X173        4204.0     0.009753     0.098284   0.00     1.00
X174        4204.0     0.017364     0.130641   0.00     1.00
X175        4204.0     0.022360     0.147868   0.00     1.00
X176        4204.0     0.017127     0.129758   0.00     1.00
X177        4204.0     0.050190     0.218363   0.00     1.00
X178        4204.0     0.557326     0.496762   0.00     1.00
X179        4204.0     0.047812     0.213393   0.00     1.00
X180        4204.0     0.157707     0.364509   0.00     1.00
X181        4204.0     0.093958     0.291805   0.00     1.00
X182        4204.0     0.106327     0.308293   0.00     1.00
X183        4204.0     0.004044     0.063469   0.00     1.00
X184        4204.0     0.001427     0.037756   0.00     1.00
X185        4204.0     0.018792     0.135805   0.00     1.00
X186        4204.0     0.536156     0.498750   0.00     1.00
X187        4204.0     0.420314     0.493668   0.00     1.00
X189        4204.0     0.915557     0.278085   0.00     1.00
X190        4204.0     0.000238     0.015423   0.00     1.00
X191        4204.0     0.471218     0.499230   0.00     1.00
X192        4204.0     0.002379     0.048720   0.00     1.00
X194        4204.0     0.463844     0.498750   0.00     1.00
X195        4204.0     0.011656     0.107343   0.00     1.00
X196        4204.0     0.010228     0.100629   0.00     1.00
X197        4204.0     0.032350     0.176949   0.00     1.00
X198        4204.0     0.022835     0.149396   0.00     1.00
X199        4204.0     0.002854     0.053357   0.00     1.00
X200        4204.0     0.006660     0.081348   0.00     1.00
X201        4204.0     0.177926     0.382496   0.00     1.00
X202        4204.0     0.241437     0.428005   0.00     1.00
X203        4204.0     0.016889     0.128870   0.00     1.00
X204        4204.0     0.000238     0.015423   0.00     1.00
X205        4204.0     0.999762     0.015423   0.00     1.00
X206        4204.0     0.019267     0.137480   0.00     1.00
X207        4204.0     0.000238     0.015423   0.00     1.00
X208        4204.0     0.062797     0.242627   0.00     1.00
X209        4204.0     0.898668     0.301804   0.00     1.00
X210        4204.0     0.000238     0.015423   0.00     1.00
X211        4204.0     0.014986     0.121510   0.00     1.00
X212        4204.0     0.005471     0.073772   0.00     1.00
X213        4204.0     0.001903     0.043586   0.00     1.00
X214        4204.0     0.006898     0.082778   0.00     1.00
X215        4204.0     0.098478     0.297995   0.00     1.00
X216        4204.0     0.005947     0.076894   0.00     1.00
X217        4204.0     0.007374     0.085565   0.00     1.00
X218        4204.0     0.312322     0.463495   0.00     1.00
X219        4204.0     0.067555     0.251010   0.00     1.00
X220        4204.0     0.561846     0.496219   0.00     1.00
X221        4204.0     0.008088     0.089577   0.00     1.00
X222        4204.0     0.022122     0.147097   0.00     1.00
X223        4204.0     0.555186     0.497004   0.00     1.00
X224        4204.0     0.317555     0.465581   0.00     1.00
X225        4204.0     0.097050     0.296062   0.00     1.00
X226        4204.0     0.032350     0.176949   0.00     1.00
X227        4204.0     0.003092     0.055529   0.00     1.00
X228        4204.0     0.038773     0.193076   0.00     1.00
X229        4204.0     0.960276     0.195333   0.00     1.00
X230        4204.0     0.005233     0.072159   0.00     1.00
X231        4204.0     0.016175     0.126163   0.00     1.00
X232        4204.0     0.043054     0.203003   0.00     1.00
X233        4204.0     0.000000     0.000000   0.00     0.00
X234        4204.0     0.201713     0.401327   0.00     1.00
X235        4204.0     0.000000     0.000000   0.00     0.00
X236        4204.0     0.000476     0.021809   0.00     1.00
X237        4204.0     0.006660     0.081348   0.00     1.00
X238        4204.0     0.916270     0.277015   0.00     1.00
X239        4204.0     0.006898     0.082778   0.00     1.00
X240        4204.0     0.002854     0.053357   0.00     1.00
X241        4204.0     0.097050     0.296062   0.00     1.00
X242        4204.0     0.007374     0.085565   0.00     1.00
X243        4204.0     0.007136     0.084183   0.00     1.00
X244        4204.0     0.103473     0.304612   0.00     1.00
X245        4204.0     0.000714     0.026707   0.00     1.00
X246        4204.0     0.409134     0.491733   0.00     1.00
X247        4204.0     0.241437     0.428005   0.00     1.00
X248        4204.0     0.001427     0.037756   0.00     1.00
X249        4204.0     0.007612     0.086923   0.00     1.00
X250        4204.0     0.552807     0.497263   0.00     1.00
X251        4204.0     0.394386     0.488777   0.00     1.00
X252        4204.0     0.000714     0.026707   0.00     1.00
X253        4204.0     0.001427     0.037756   0.00     1.00
X254        4204.0     0.005233     0.072159   0.00     1.00
X255        4204.0     0.019505     0.138309   0.00     1.00
X256        4204.0     0.073264     0.260600   0.00     1.00
X257        4204.0     0.000238     0.015423   0.00     1.00
X258        4204.0     0.002379     0.048720   0.00     1.00
X259        4204.0     0.000238     0.015423   0.00     1.00
X260        4204.0     0.000238     0.015423   0.00     1.00
X261        4204.0     0.419363     0.493513   0.00     1.00
X262        4204.0     0.001427     0.037756   0.00     1.00
X263        4204.0     0.956946     0.203003   0.00     1.00
X264        4204.0     0.039248     0.194208   0.00     1.00
X265        4204.0     0.905566     0.292466   0.00     1.00
X266        4204.0     0.001427     0.037756   0.00     1.00
X267        4204.0     0.009039     0.094654   0.00     1.00
X268        4204.0     0.000000     0.000000   0.00     0.00
X269        4204.0     0.000476     0.021809   0.00     1.00
X270        4204.0     0.000238     0.015423   0.00     1.00
X271        4204.0     0.002141     0.046225   0.00     1.00
X272        4204.0     0.037583     0.190209   0.00     1.00
X273        4204.0     0.719791     0.449155   0.00     1.00
X274        4204.0     0.009990     0.099464   0.00     1.00
X275        4204.0     0.726927     0.445591   0.00     1.00
X276        4204.0     0.038535     0.192506   0.00     1.00
X277        4204.0     0.001427     0.037756   0.00     1.00
X278        4204.0     0.000476     0.021809   0.00     1.00
X279        4204.0     0.043054     0.203003   0.00     1.00
X280        4204.0     0.000238     0.015423   0.00     1.00
X281        4204.0     0.002617     0.051091   0.00     1.00
X282        4204.0     0.004044     0.063469   0.00     1.00
X283        4204.0     0.140580     0.347630   0.00     1.00
X284        4204.0     0.040913     0.198113   0.00     1.00
X285        4204.0     0.205756     0.404301   0.00     1.00
X286        4204.0     0.054710     0.227440   0.00     1.00
X287        4204.0     0.015937     0.125248   0.00     1.00
X288        4204.0     0.000238     0.015423   0.00     1.00
X289        4204.0     0.000000     0.000000   0.00     0.00
X290        4204.0     0.000000     0.000000   0.00     0.00
X291        4204.0     0.010466     0.101780   0.00     1.00
X292        4204.0     0.009039     0.094654   0.00     1.00
X293        4204.0     0.000000     0.000000   0.00     0.00
X294        4204.0     0.125119     0.330893   0.00     1.00
X295        4204.0     0.000238     0.015423   0.00     1.00
X296        4204.0     0.000238     0.015423   0.00     1.00
X297        4204.0     0.000000     0.000000   0.00     0.00
X298        4204.0     0.004520     0.067083   0.00     1.00
X299        4204.0     0.004520     0.067083   0.00     1.00
X300        4204.0     0.207184     0.405336   0.00     1.00
X301        4204.0     0.046860     0.211364   0.00     1.00
X302        4204.0     0.011418     0.106255   0.00     1.00
X304        4204.0     0.924358     0.264456   0.00     1.00
X305        4204.0     0.013321     0.114657   0.00     1.00
X306        4204.0     0.043530     0.204071   0.00     1.00
X307        4204.0     0.002141     0.046225   0.00     1.00
X308        4204.0     0.009515     0.097090   0.00     1.00
X309        4204.0     0.007136     0.084183   0.00     1.00
X310        4204.0     0.002617     0.051091   0.00     1.00
X311        4204.0     0.598716     0.490217   0.00     1.00
X312        4204.0     0.004282     0.065302   0.00     1.00
X313        4204.0     0.300904     0.458706   0.00     1.00
X314        4204.0     0.431494     0.495344   0.00     1.00
X315        4204.0     0.028782     0.167213   0.00     1.00
X316        4204.0     0.195766     0.396836   0.00     1.00
X317        4204.0     0.007612     0.086923   0.00     1.00
X318        4204.0     0.000714     0.026707   0.00     1.00
X319        4204.0     0.000476     0.021809   0.00     1.00
X320        4204.0     0.007136     0.084183   0.00     1.00
X321        4204.0     0.238344     0.426122   0.00     1.00
X322        4204.0     0.021884     0.146322   0.00     1.00
X323        4204.0     0.009277     0.095880   0.00     1.00
X324        4204.0     0.574691     0.494449   0.00     1.00
X325        4204.0     0.005709     0.075350   0.00     1.00
X326        4204.0     0.032350     0.176949   0.00     1.00
X327        4204.0     0.128211     0.334365   0.00     1.00
X328        4204.0     0.040200     0.196451   0.00     1.00
X329        4204.0     0.435538     0.495886   0.00     1.00
X330        4204.0     0.000000     0.000000   0.00     0.00
X331        4204.0     0.055899     0.229754   0.00     1.00
X332        4204.0     0.000714     0.026707   0.00     1.00
X333        4204.0     0.024025     0.153144   0.00     1.00
X334        4204.0     0.462655     0.498663   0.00     1.00
X335        4204.0     0.003568     0.059633   0.00     1.00
X336        4204.0     0.127260     0.333303   0.00     1.00
X337        4204.0     0.516413     0.499790   0.00     1.00
X338        4204.0     0.006898     0.082778   0.00     1.00
X339        4204.0     0.000238     0.015423   0.00     1.00
X340        4204.0     0.022360     0.147868   0.00     1.00

In [32]:
# Categorical Feature Statistics
cat_stats

            value  count    pct
column rank
X0     1        z    359   8.54
       2       ak    348   8.28
       3        y    323   7.68
       4       ay    313   7.45
       5        t    306   7.28
X1     1       aa    833  19.81
       2        s    598  14.22
       3        b    592  14.08
       4        l    589  14.01
       5        v    408   9.71
X2     1       as   1658  39.44
       2       ae    495  11.77
       3       ai    414   9.85
       4        m    367   8.73
       5       ak    265   6.30

In [33]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,0.738,0.278,154.196,0.015,log,57845.6,60798.8,exponential

## Task Curation

In [44]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from sklearn.model_selection import TimeSeriesSplit

df = df.sort_values(by="time_index", ascending=True).reset_index(drop=True)

default_train_index = df.index[:1000].to_list()
to_split_index = df.index[1000:]

spliter = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=9, test_size=None)
splits = {}
for i, (train_idx, test_idx) in enumerate(spliter.split(to_split_index)):
    print(len(train_idx) + len(default_train_index), len(test_idx))
    splits[i] = {0: (default_train_index + to_split_index[train_idx].to_list(), to_split_index[test_idx].tolist())}

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="This is a small temporal dataset. Thus, we could refit often and we could simulate that a model was often refit, basically, if possible, after each time_index (akin to LOO). As this would create too many splits with too small test sizes for a robust signal, we opt for less splits. Moreover, as we want to have sufficient train data signal, we start with the first 1000 samples of the data as fixed train data. The rest is than gradually split to create 9 test splits using a sklearn TimeSeriesSplit.",
    splits=splits,
)

1324 320
1644 320
1964 320
2284 320
2604 320
2924 320
3244 320
3564 320
3884 320

## Export

In [45]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019c0e88-024b-7ba9-84f5-f495bd8a3bdd
8ca9e779304984559c40917b7a1ebf03bb53cfc3dd405a814ed671e77c1d7d56