### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="concrete_compressive_strength",
    dataset_year="1998",
    domain_str="chemistry & material science",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C5PK67",
    download_description="""
We download the data from the UCI repository and unzip it to a predefined folder.

mkdir -p local-data-warehouse/concrete_compressive_strength/ && wget -P local-data-warehouse/concrete_compressive_strength/ https://archive.ics.uci.edu/static/public/165/concrete+compressive+strength.zip && unzip local-data-warehouse/concrete_compressive_strength/concrete+compressive+strength.zip -d local-data-warehouse/concrete_compressive_strength/
""",
    # References
    academic_reference_bibtex="""@article{yeh1998modeling,
  title={Modeling of strength of high-performance concrete using artificial neural networks},
  author={Yeh, I-C},
  journal={Cement and Concrete research},
  volume={28},
  number={12},
  pages={1797--1808},
  year={1998},
  publisher={Elsevier}
}
""",
    academic_reference_bibtex_key="yeh1998modeling",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
- We rename features to be shorter while similar to the original names.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="ConcreteCompressiveStrength",
    problem_type="regression",
    objective_metric_name="rmse",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_excel(f"{dataset_mold.path}/Concrete_Data.xls")

target_feature = "ConcreteCompressiveStrength"
df.columns = [
    "Cement",
    "BlastFurnaceSlag",
    "FlyAsh",
    "Water",
    "Superplasticizer",
    "CoarseAggregate",
    "FineAggregate",
    "Age",
    target_feature,
]

# Data was ordered by default, so we shuffle it to avoid any unintended ordering effects.
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 1,030
Columns: 9
Use sampling: False (sample size: 1,030)
Get row duplicates (staged, merged)...
Using top-8 columns for initial filtering: ['FineAggregate', 'CoarseAggregate', 'Cement', 'Water', 'BlastFurnaceSlag', 'FlyAsh', 'Superplasticizer', 'Age']
Rows remaining as candidates after top-8 filter: 53 (of 1,030)

#### Duplicate Report
Total duplicate rows: 25 (2.43% of dataset)
Duplicate rows ignoring target: 34 (3.30% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,Cement,BlastFurnaceSlag,FlyAsh,Water,Superplasticizer,CoarseAggregate,FineAggregate,Age,ConcreteCompressiveStrength
0,266.0,114.0,0.0,228.0,0.0,932.0,670.0,365,52.908320
1,362.6,189.0,0.0,164.9,11.6,944.7,755.8,7,55.895819
2,389.9,189.0,0.0,145.9,22.0,944.7,755.8,28,74.497882
3,362.6,189.0,0.0,164.9,11.6,944.7,755.8,3,35.301171
4,145.0,0.0,179.0,202.0,8.0,824.0,869.0,28,10.535193

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Cement,float64,0.0,0.0,280.0,"362.6, 425.0, 251.37, 310.0, 446.0, 331.0, 250.0, 475.0, 349.0, 387.0"
1,BlastFurnaceSlag,float64,0.0,0.0,187.0,"0.0, 189.0, 106.3, 24.0, 20.0, 145.0, 19.0, 26.0, 22.0, 190.0"
2,FlyAsh,float64,0.0,0.0,163.0,"0.0, 141.0, 118.27, 79.0, 94.0, 125.18, 174.24, 121.62, 100.52, 98.75"
3,Water,float64,0.0,0.0,205.0,"192.0, 228.0, 185.7, 203.5, 186.0, 164.9, 162.0, 185.0, 153.5, 193.0"
4,Superplasticizer,float64,0.0,0.0,155.0,"0.0, 8.0, 11.6, 7.0, 6.0, 10.0, 9.0, 16.5, 11.0, 11.66"
5,CoarseAggregate,float64,0.0,0.0,284.0,"932.0, 852.1, 944.7, 968.0, 1125.0, 1047.0, 967.0, 822.0, 938.0, 942.0"
6,FineAggregate,float64,0.0,0.0,304.0,"755.8, 594.0, 670.0, 613.0, 801.0, 746.6, 887.1, 712.0, 845.0, 750.0"
7,ConcreteCompressiveStrength,float64,0.0,0.0,938.0,"33.3982, 77.2972, 35.3012, 79.2966, 71.2987, 31.3505, 49.201, 18.1263, 64.9004, 17.5403"
8,Age,int64,0.0,0.0,14.0,"28, 3, 7, 56, 14, 90, 100, 180, 91, 365"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
Cement,1030.0,281.165631,104.507142,102.000000,540.000000
BlastFurnaceSlag,1030.0,73.895485,86.279104,0.000000,359.400000
FlyAsh,1030.0,54.187136,63.996469,0.000000,200.100000
Water,1030.0,181.566359,21.355567,121.750000,247.000000
Superplasticizer,1030.0,6.203112,5.973492,0.000000,32.200000
CoarseAggregate,1030.0,972.918592,77.753818,801.000000,1145.000000
FineAggregate,1030.0,773.578883,80.175427,594.000000,992.600000
Age,1030.0,45.662136,63.169912,1.000000,365.000000
ConcreteCompressiveStrength,1030.0,35.817836,16.705679,2.331808,82.599225

In [7]:
# Categorical Feature Statistics
cat_stats

'No categorical/object features to summarize.'

In [8]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,0.417,-0.872,279.08,0.304,log,9438.4,30799.5,exponential

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=10, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to concrete_compressive_strength/019d7367-0f12-7c25-b411-de9c711bd4ec

019d7367-0f12-7c25-b411-de9c711bd4ec
af774eaeaf9d490623146046567399c7e5068c1a75ea2d9c1ad92a6e428c351f