### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="homesite_quote_conversion",
    dataset_year="2015",
    domain_str="insurance",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/homesite-quote-conversion",
    download_description="""
We use the train.csv from the Kaggle competition.

kaggle competitions download -c homesite-quote-conversion -f train.csv.zip && unzip train.csv.zip &&  rm train.csv.zip
mkdir -p local-data-warehouse/homesite_quote_conversion && mv train.csv local-data-warehouse/homesite_quote_conversion/
""",
    # References
    academic_reference_bibtex=r"""@misc{Darrel2015HomesiteQuoteConversion,
  author = {Darrel and Stephen D. Stayton and Will Cukierski},
  title  = {Homesite Quote Conversion},
  year   = {2015},
  howpublished = {\url{https://kaggle.com/competitions/homesite-quote-conversion}},
  note   = {Kaggle competition}
}
""",
    academic_reference_bibtex_key="Darrel2015HomesiteQuoteConversion",
    licence="Kaggle Competition Rules",
    data_tags=["IID", "Anonymized"],
    curation_comments="""
We start with the train.csv from Kaggle.

- The data has been anonymized, so feature meanings are unknown.
- The data contains decoded spatial information.
- We fix the Field10 column to be integer instead of string with ',' characters.
- We convert the Original_Quote_Date to datetime. This column does not seems to be a timestamp for splitting as the test data on Kaggle also contains dates within the range of the training data's timestamps. So the task is still IID.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="QuoteConversion_Flag",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="QuoteConversion_Flag",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(dataset_mold.path / "train.csv")
print("Loaded data shape:", df.shape)

df["Field10"] = df["Field10"].astype("string").str.replace(",", "").astype(int)
df["Original_Quote_Date"] = pd.to_datetime(df["Original_Quote_Date"])
as_cat = df.select_dtypes(include=["object"]).columns.tolist() + ["QuoteConversion_Flag"]
df[as_cat] = df[as_cat].astype("category")

Loaded data shape: (260753, 299)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 260,753
Columns: 299

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,QuoteNumber,Original_Quote_Date,QuoteConversion_Flag,Field6,Field7,Field8,Field9,Field10,Field11,Field12,CoverageField1A,CoverageField1B,CoverageField2A,CoverageField2B,CoverageField3A,CoverageField3B,CoverageField4A,CoverageField4B,CoverageField5A,CoverageField5B,CoverageField6A,CoverageField6B,CoverageField8,CoverageField9,CoverageField11A,CoverageField11B,SalesField1A,SalesField1B,SalesField2A,SalesField2B,SalesField3,SalesField4,SalesField5,SalesField6,SalesField7,SalesField8,SalesField9,SalesField10,SalesField11,SalesField12,SalesField13,SalesField14,SalesField15,PersonalField1,PersonalField2,PersonalField4A,PersonalField4B,PersonalField5,PersonalField6,PersonalField7,PersonalField8,PersonalField9,PersonalField10A,PersonalField10B,PersonalField11,PersonalField12,PersonalField13,PersonalField14,PersonalField15,PersonalField16,PersonalField17,PersonalField18,PersonalField19,PersonalField22,PersonalField23,PersonalField24,PersonalField25,PersonalField26,PersonalField27,PersonalField28,PersonalField29,PersonalField30,PersonalField31,PersonalField32,PersonalField33,PersonalField34,PersonalField35,PersonalField36,PersonalField37,PersonalField38,PersonalField39,PersonalField40,PersonalField41,PersonalField42,PersonalField43,PersonalField44,PersonalField45,PersonalField46,PersonalField47,PersonalField48,PersonalField49,PersonalField50,PersonalField51,PersonalField52,PersonalField53,PersonalField54,PersonalField55,PersonalField56,PersonalField57,PersonalField58,PersonalField59,PersonalField60,PersonalField61,PersonalField62,PersonalField63,PersonalField64,PersonalField65,PersonalField66,PersonalField67,PersonalField68,PersonalField69,PersonalField70,PersonalField71,PersonalField72,PersonalField73,PersonalField74,PersonalField75,PersonalField76,PersonalField77,PersonalField78,PersonalField79,PersonalField80,PersonalField81,PersonalField82,PersonalField83,PersonalField84,PropertyField1A,PropertyField1B,PropertyField2A,PropertyField2B,PropertyField3,PropertyField4,PropertyField5,PropertyField6,PropertyField7,PropertyField8,PropertyField9,PropertyField10,PropertyField11A,PropertyField11B,PropertyField12,PropertyField13,PropertyField14,PropertyField15,PropertyField16A,PropertyField16B,PropertyField17,PropertyField18,PropertyField19,PropertyField20,PropertyField21A,PropertyField21B,PropertyField22,PropertyField23,PropertyField24A,PropertyField24B,PropertyField25,PropertyField26A,PropertyField26B,PropertyField27,PropertyField28,PropertyField29,PropertyField30,PropertyField31,PropertyField32,PropertyField33,PropertyField34,PropertyField35,PropertyField36,PropertyField37,PropertyField38,PropertyField39A,PropertyField39B,GeographicField1A,GeographicField1B,GeographicField2A,GeographicField2B,GeographicField3A,GeographicField3B,GeographicField4A,GeographicField4B,GeographicField5A,GeographicField5B,GeographicField6A,GeographicField6B,GeographicField7A,GeographicField7B,GeographicField8A,GeographicField8B,GeographicField9A,GeographicField9B,GeographicField10A,GeographicField10B,GeographicField11A,GeographicField11B,GeographicField12A,GeographicField12B,GeographicField13A,GeographicField13B,GeographicField14A,GeographicField14B,GeographicField15A,GeographicField15B,GeographicField16A,GeographicField16B,GeographicField17A,GeographicField17B,GeographicField18A,GeographicField18B,GeographicField19A,GeographicField19B,GeographicField20A,GeographicField20B,GeographicField21A,GeographicField21B,GeographicField22A,GeographicField22B,GeographicField23A,GeographicField23B,GeographicField24A,GeographicField24B,GeographicField25A,GeographicField25B,GeographicField26A,GeographicField26B,GeographicField27A,GeographicField27B,GeographicField28A,GeographicField28B,GeographicField29A,GeographicField29B,GeographicField30A,GeographicField30B,GeographicField31A,GeographicField31B,GeographicField32A,GeographicField32B,GeographicField33A,GeographicField33B,GeographicField34A,GeographicField34B,GeographicField35A,GeographicField35B,GeographicField36A,GeographicField36B,GeographicField37A,GeographicField37B,GeographicField38A,GeographicField38B,GeographicField39A,GeographicField39B,GeographicField40A,GeographicField40B,GeographicField41A,GeographicField41B,GeographicField42A,GeographicField42B,GeographicField43A,GeographicField43B,GeographicField44A,GeographicField44B,GeographicField45A,GeographicField45B,GeographicField46A,GeographicField46B,GeographicField47A,GeographicField47B,GeographicField48A,GeographicField48B,GeographicField49A,GeographicField49B,GeographicField50A,GeographicField50B,GeographicField51A,GeographicField51B,GeographicField52A,GeographicField52B,GeographicField53A,GeographicField53B,GeographicField54A,GeographicField54B,GeographicField55A,GeographicField55B,GeographicField56A,GeographicField56B,GeographicField57A,GeographicField57B,GeographicField58A,GeographicField58B,GeographicField59A,GeographicField59B,GeographicField60A,GeographicField60B,GeographicField61A,GeographicField61B,GeographicField62A,GeographicField62B,GeographicField63,GeographicField64
0,1,2013-08-16,0,B,23,0.9403,0.0006,965,1.0200,N,17,23,17,23,15,22,16,22,13,22,13,23,T,D,2,1,7,18,3,8,0,5,5,24,V,48649,0,0,0,0,0,0,0,0,0,-1,-1,7,0,N,1,2,5,7,0,1,2,2,24,ZA,ZE,XR,XD,1,0,0,0,0,1,2,2,0,1,1,1,1,0,0,0,0,0,0,0,0,1,0,1,1,1,2,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,1,1,1,2,0,0,0,0,1,2.0,5,7,-1,19,N,N,Y,0,O,0,0,1,-1,21,4,2,C,4,14,22,0,3,0,0,17,23,2,4,15,21,3.0,5,5,6,B,0.0,N,N,Y,G,Y,2,N,N,N,7,5,3,6,15,14,12,13,20,22,-1,13,2,5,1,1,1,1,2,9,-1,25,1,1,1,1,1,1,-1,7,1,2,1,2,13,22,-1,12,3,6,4,12,-1,10,-1,15,-1,5,14,9,16,16,15,18,17,16,11,18,24,25,5,4,7,10,13,20,14,21,12,14,14,22,3,2,15,24,2,2,15,23,1,1,15,13,9,10,2,2,8,4,20,22,10,8,6,5,15,13,19,18,16,14,21,23,21,23,16,11,22,24,7,14,-1,17,15,17,14,18,9,9,-1,8,-1,18,-1,10,N,CA
1,2,2014-04-22,0,F,7,1.0006,0.0040,548,1.2433,N,6,8,6,8,5,7,5,8,13,22,13,23,T,E,5,9,5,14,6,18,1,5,5,11,P,26778,0,0,1,1,0,0,0,1,1,14,19,7,0,N,1,2,24,25,0,1,2,5,19,XB,YJ,YE,XT,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,NaN,17,21,-1,22,N,N,Y,0,N,0,0,1,-1,23,3,0,B,4,7,15,0,1,0,0,6,8,2,1,6,8,2.0,4,3,3,B,NaN,N,O,N,H,Y,2,N,N,N,11,12,8,17,19,20,12,14,16,18,-1,19,4,13,9,13,5,13,5,12,-1,25,4,15,8,13,5,14,-1,13,9,11,5,12,2,16,-1,22,23,24,20,22,-1,22,-1,22,-1,13,10,4,10,5,5,5,13,6,7,10,21,24,10,19,7,10,9,15,4,3,13,17,6,9,17,23,11,21,13,21,9,17,12,21,25,25,15,21,10,13,23,24,11,15,21,24,6,11,21,21,18,15,20,20,13,12,12,12,15,9,13,11,11,20,-1,9,18,21,8,7,10,10,-1,11,-1,17,-1,20,N,NJ
2,4,2014-08-25,0,F,7,1.0006,0.0040,548,1.2433,N,7,12,7,12,6,10,7,11,25,25,13,23,T,J,4,6,3,10,4,11,1,5,5,11,K,8751,0,0,2,2,0,0,0,1,1,16,21,7,0,N,1,2,7,16,0,1,2,3,7,ZH,XS,YP,XC,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,NaN,12,16,-1,13,Y,Y,Y,0,R,1,0,1,-1,21,4,2,C,4,9,17,1,3,0,0,7,12,2,1,15,21,1.5,14,20,3,B,NaN,N,K,Y,H,Y,2,N,N,N,23,24,2,4,20,22,18,20,16,18,-1,21,4,12,10,14,5,13,6,14,-1,25,4,11,9,15,5,12,-1,12,10,16,6,14,2,13,-1,17,21,21,20,21,-1,19,-1,19,-1,10,18,17,12,8,7,8,15,11,6,9,8,11,7,12,13,21,11,18,12,19,15,20,10,17,9,13,4,10,14,22,17,24,10,16,24,22,12,15,12,20,21,22,24,25,20,22,7,13,23,23,20,19,20,20,18,20,19,21,20,19,11,8,3,3,-1,5,21,24,12,15,15,18,-1,21,-1,11,-1,8,N,NJ
3,6,2013-04-15,0,J,10,0.9769,0.0004,1165,1.2665,N,3,2,3,2,2,2,3,2,13,22,13,23,Y,F,15,23,8,19,14,24,0,5,5,23,V,43854,0,0,0,0,0,0,0,1,1,2,2,6,1,N,1,3,-1,-1,0,5,2,3,13,XO,XE,YI,XX,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,NaN,1,1,-1,2,N,N,Y,0,R,1,0,1,-1,21,4,2,C,1,3,6,0,2,0,0,3,2,2,1,7,9,1.0,13,18,10,B,NaN,N,O,Y,G,N,2,N,Y,N,24,25,2,3,10,8,8,9,21,23,-1,23,13,21,22,22,14,21,18,21,-1,25,15,22,21,22,15,22,-1,15,24,23,9,18,2,3,-1,6,10,13,2,3,-1,8,-1,15,-1,24,19,20,13,10,7,10,16,14,3,3,11,16,2,1,10,15,3,3,14,21,1,1,9,16,3,2,4,8,4,3,9,18,2,1,13,9,7,7,25,25,3,1,14,22,6,2,7,14,11,8,19,18,18,16,13,12,13,12,17,13,5,2,3,4,-1,7,14,14,14,18,6,5,-1,10,-1,9,-1,21,N,TX
4,8,2014-01-25,0,E,23,0.9472,0.0006,1487,1.3045,N,8,13,8,13,7,11,7,13,13,22,13,23,T,F,4,6,3,6,3,6,1,5,5,7,R,12505,1,0,0,0,0,0,0,1,1,20,24,7,0,N,1,2,5,8,0,1,2,2,24,ZA,ZE,XR,XD,1,0,0,0,0,1,2,2,0,1,1,1,1,0,0,0,0,0,0,0,0,1,0,1,1,1,2,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,1,1,1,2,0,0,0,0,1,2.0,10,13,-1,19,Y,Y,Y,0,D,0,0,1,-1,21,1,2,A,4,5,11,0,0,0,0,8,13,2,1,13,19,3.0,4,4,4,B,0.0,N,O,N,H,N,0,N,N,N,18,22,2,2,17,18,13,15,9,7,-1,13,9,18,11,16,9,17,12,17,-1,25,9,17,12,16,9,17,-1,22,9,8,10,20,2,6,-1,4,17,16,5,13,-1,22,25,25,-1,15,17,16,17,17,10,13,21,20,9,14,5,4,10,18,8,11,6,8,11,17,16,21,7,11,8,11,3,6,12,19,4,6,10,15,18,17,24,25,10,12,24,25,9,11,25,25,5,3,22,22,21,21,17,15,25,25,25,25,17,13,13,11,3,4,-1,7,11,9,10,10,18,22,-1,10,-1,11,-1,12,N,IL

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,PropertyField38,category,1220,0.47,2,"N, Y"
1,PersonalField7,category,113,0.04,2,"N, Y"
2,PropertyField36,category,113,0.04,2,"N, Y"
3,PropertyField3,category,81,0.03,2,"N, Y"
4,PropertyField32,category,70,0.03,2,"Y, N"
5,PropertyField34,category,70,0.03,2,"Y, N"
6,PropertyField4,category,63,0.02,2,"N, Y"
7,QuoteConversion_Flag,category,0,0.00,2,"0, 1"
8,Field6,category,0,0.00,8,"B, F, J, E, K, C, D, A"
9,Field12,category,0,0.00,2,"N, Y"
10,CoverageField8,category,0,0.00,7,"Y, T, X, Z, U, V, W"
11,CoverageField9,category,0,0.00,12,"E, D, G, F, K, J, A, B, I, H"
12,SalesField7,category,0,0.00,7,"K, P, T, Q, V, R, M"
13,PersonalField16,category,0,0.00,50,"ZA, XR, XJ, XM, XD, XH, XX, XO, XB, YH"
14,PersonalField17,category,0,0.00,66,"ZE, XV, XS, YY, ZK, ZH, XE, XG, YV, ZF"
15,PersonalField18,category,0,0.00,61,"XR, YP, ZW, XF, YI, XQ, YF, ZN, YG, XZ"
16,PersonalField19,category,0,0.00,57,"XD, XC, XX, ZQ, YF, ZN, ZT, ZV, YJ, XU"
17,PropertyField5,category,0,0.00,2,"Y, N"
18,PropertyField7,category,0,0.00,19,"O, R, J, D, S, N, I, Q, A, K"
19,PropertyField14,category,0,0.00,4,"C, A, B, D"
20,PropertyField28,category,0,0.00,4,"B, A, D, C"
21,PropertyField30,category,0,0.00,2,"N, Y"
22,PropertyField31,category,0,0.00,4,"O, K, N, M"
23,PropertyField33,category,0,0.00,4,"H, G, E, F"
24,PropertyField37,category,0,0.00,2,"N, Y"
25,GeographicField63,category,0,0.00,3,"N, Y,"
26,GeographicField64,category,0,0.00,4,"CA, NJ, TX, IL"
27,Original_Quote_Date,datetime64[ns],0,0.00,868,"2014-03-03 00:00:00, 2015-03-31 00:00:00, 2014-02-24 00:00:00, 2015-03-23 00:00:00, 2015-03-17 00:00:00, 2014-03-10 00:00:00, 2014-02-26 00:00:00, 2015-03-11 00:00:00, 2014-03-11 00:00:00, 2014-03-04 00:00:00"
28,PropertyField29,float64,200685,76.96,2,"0.0, 1.0"
29,PersonalField84,float64,124208,47.63,7,"2.0, 1.0, 5.0, 3.0, 7.0, 4.0, 8.0"
30,Field8,float64,0,0.00,38,"0.9403, 0.9153, 0.887, 1.0006, 0.9919, 0.8928, 0.8922, 0.9691, 0.9392, 1.0101"
31,Field9,float64,0,0.00,5,"0.0006, 0.0004, 0.0007, 0.004, 0.0038"
32,Field11,float64,0,0.00,11,"1.02, 1.2665, 1.3045, 1.1886, 1.2433, 1.2694, 1.067, 1.1161, 1.2714, 1.2392"
33,PropertyField25,float64,0,0.00,11,"1.0, 2.0, 3.0, 1.5, 2.5, 5.0, 4.0, 3.5, 7.0, 6.0"
34,QuoteNumber,int64,0,0.00,260753,"434588, 1, 2, 4, 6, 8, 12, 13, 14, 18"
35,Field7,int64,0,0.00,28,"23, 25, 11, 7, 26, 24, 21, 22, 19, 14"
36,Field10,int64,0,0.00,8,"935, 1113, 965, 548, 564, 1165, 1487, 1480"
37,CoverageField1A,int64,0,0.00,26,"6, 5, 7, 4, 8, 9, 3, 10, 11, 12"
38,CoverageField1B,int64,0,0.00,26,"9, 6, 12, 3, 20, 15, 19, 14, 11, 25"
39,CoverageField2A,int64,0,0.00,25,"6, 5, 7, 4, 8, 9, 3, 10, 11, 12"
40,CoverageField2B,int64,0,0.00,25,"7, 16, 18, 12, 5, 20, 14, 2, 24, 25"
41,CoverageField3A,int64,0,0.00,25,"5, 6, 7, 4, 8, 9, 3, 10, 11, 12"
42,CoverageField3B,int64,0,0.00,25,"9, 14, 4, 23, 19, 11, 3, 16, 25, 15"
43,CoverageField4A,int64,0,0.00,25,"6, 5, 7, 4, 8, 9, 3, 10, 11, 12"
44,CoverageField4B,int64,0,0.00,25,"4, 9, 15, 11, 8, 2, 7, 19, 18, 13"
45,CoverageField5A,int64,0,0.00,3,"13, 25, 1"
46,CoverageField5B,int64,0,0.00,4,"22, 25, 2, 1"
47,CoverageField6A,int64,0,0.00,3,"13, 1, 25"
48,CoverageField6B,int64,0,0.00,4,"23, 6, 25, 1"
49,CoverageField11A,int64,0,0.00,26,"4, 5, 3, 6, 7, 8, 2, 9, 10, 11"
50,CoverageField11B,int64,0,0.00,26,"15, 22, 24, 20, 10, 13, 1, 12, 6, 18"
51,SalesField1A,int64,0,0.00,25,"3, 2, 4, 5, 6, 7, 8, 9, 10, 1"
52,SalesField1B,int64,0,0.00,25,"5, 14, 8, 11, 20, 21, 7, 16, 12, 25"
53,SalesField2A,int64,0,0.00,26,"3, 2, 4, 5, 6, 7, 8, 9, 1, 25"
54,SalesField2B,int64,0,0.00,26,"1, 19, 8, 14, 23, 17, 7, 21, 20, 10"
55,SalesField3,int64,0,0.00,2,"1, 0"
56,SalesField4,int64,0,0.00,5,"5, 4, 3, 1, 2"
57,SalesField5,int64,0,0.00,5,"5, 3, 4, 2, 1"
58,SalesField6,int64,0,0.00,24,"11, 20, 23, 7, 1, 4, 21, 17, 15, 14"
59,SalesField8,int64,0,0.00,61530,"2879, 36088, 39076, 65661, 64197, 5808, 4327, 64578, 50037, 3879"
60,SalesField9,int64,0,0.00,2,"0, 1"
61,SalesField10,int64,0,0.00,19,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
62,SalesField11,int64,0,0.00,20,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
63,SalesField12,int64,0,0.00,22,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
64,SalesField13,int64,0,0.00,8,"0, 1, 2, 3, 4, 5, 6, 7"
65,SalesField14,int64,0,0.00,12,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
66,SalesField15,int64,0,0.00,12,"0, 1, 2, 3, 4, 5, 6, 7, 9, 8"
67,PersonalField1,int64,0,0.00,2,"1, 0"
68,PersonalField2,int64,0,0.00,2,"1, 0"
69,PersonalField4A,int64,0,0.00,26,"-1, 7, 13, 5, 6, 4, 8, 9, 10, 11"
70,PersonalField4B,int64,0,0.00,26,"-1, 5, 8, 10, 12, 13, 21, 24, 16, 15"
71,PersonalField5,int64,0,0.00,9,"7, 6, 9, 1, 10, 3, 2, 5, 4"
72,PersonalField6,int64,0,0.00,2,"0, 1"
73,PersonalField8,int64,0,0.00,3,"1, 2, 3"
74,PersonalField9,int64,0,0.00,3,"2, 3, 1"
75,PersonalField10A,int64,0,0.00,26,"-1, 5, 6, 7, 4, 8, 9, 25, 1, 10"
76,PersonalField10B,int64,0,0.00,26,"-1, 3, 10, 12, 7, 5, 17, 14, 25, 20"
77,PersonalField11,int64,0,0.00,5,"0, 1, 2, 3, 4"
78,PersonalField12,int64,0,0.00,5,"1, 5, 3, 4, 2"
79,PersonalField13,int64,0,0.00,4,"2, 1, 3, 4"
80,PersonalField14,int64,0,0.00,30,"2, 4, 3, 1, 5, 6, 7, 8, 9, 10"
81,PersonalField15,int64,0,0.00,22,"24, 6, 7, 8, 4, 5, 9, 10, 11, 13"
82,PersonalField22,int64,0,0.00,7,"1, 3, 2, 4, 5, 6, 7"
83,PersonalField23,int64,0,0.00,13,"0, 1, 2, 3, 4, 6, 5, 8, 10, 7"
84,PersonalField24,int64,0,0.00,14,"0, 1, 2, 3, 4, 6, 5, 8, 10, 7"
85,PersonalField25,int64,0,0.00,14,"0, 1, 2, 3, 4, 6, 5, 8, 10, 7"
86,PersonalField26,int64,0,0.00,14,"0, 1, 2, 3, 4, 6, 5, 8, 10, 9"
87,PersonalField27,int64,0,0.00,17,"1, 0, 2, 3, 4, 5, 7, 6, 9, 11"
88,PersonalField28,int64,0,0.00,7,"1, 2, 3, 4, 5, 6, 7"
89,PersonalField29,int64,0,0.00,7,"1, 2, 3, 4, 5, 7, 6"
90,PersonalField30,int64,0,0.00,12,"0, 1, 2, 3, 4, 5, 6, 10, 22, 14"
91,PersonalField31,int64,0,0.00,12,"0, 1, 2, 3, 4, 5, 7, 6, 11, 15"
92,PersonalField32,int64,0,0.00,12,"0, 1, 2, 3, 4, 5, 7, 6, 11, 15"
93,PersonalField33,int64,0,0.00,12,"0, 1, 2, 3, 4, 5, 6, 7, 11, 15"
94,PersonalField34,int64,0,0.00,7,"1, 3, 2, 4, 5, 7, 6"
95,PersonalField35,int64,0,0.00,6,"0, 1, 2, 3, 5, 4"
96,PersonalField36,int64,0,0.00,6,"0, 1, 2, 4, 3, 5"
97,PersonalField37,int64,0,0.00,6,"0, 1, 2, 4, 3, 5"
98,PersonalField38,int64,0,0.00,6,"0, 1, 2, 3, 4, 5"
99,PersonalField39,int64,0,0.00,9,"0, 1, 2, 3, 4, 6, 8, 5, 7"
100,PersonalField40,int64,0,0.00,10,"0, 1, 2, 3, 4, 6, 9, 8, 5, 7"
101,PersonalField41,int64,0,0.00,10,"0, 1, 2, 3, 4, 6, 5, 9, 8, 7"
102,PersonalField42,int64,0,0.00,10,"0, 1, 2, 3, 4, 6, 5, 9, 8, 7"
103,PersonalField43,int64,0,0.00,7,"1, 3, 2, 4, 5, 7, 6"
104,PersonalField44,int64,0,0.00,12,"0, 1, 2, 3, 4, 5, 6, 10, 22, 14"
105,PersonalField45,int64,0,0.00,12,"0, 1, 2, 3, 4, 5, 7, 6, 11, 15"
106,PersonalField46,int64,0,0.00,12,"0, 1, 2, 3, 4, 5, 6, 7, 11, 15"
107,PersonalField47,int64,0,0.00,12,"0, 1, 2, 3, 4, 5, 6, 7, 11, 15"
108,PersonalField48,int64,0,0.00,7,"1, 2, 3, 4, 5, 7, 6"
109,PersonalField49,int64,0,0.00,7,"0, 1, 2, 3, 4, 6, 7"
110,PersonalField50,int64,0,0.00,7,"0, 1, 2, 3, 4, 6, 7"
111,PersonalField51,int64,0,0.00,7,"0, 1, 2, 3, 4, 6, 7"
112,PersonalField52,int64,0,0.00,7,"0, 1, 2, 3, 4, 6, 7"
113,PersonalField53,int64,0,0.00,7,"1, 3, 2, 4, 5, 6, 7"
114,PersonalField54,int64,0,0.00,11,"0, 1, 2, 3, 4, 5, 6, 7, 10, 8"
115,PersonalField55,int64,0,0.00,11,"0, 1, 2, 3, 4, 5, 6, 8, 7, 10"
116,PersonalField56,int64,0,0.00,12,"0, 1, 2, 3, 4, 6, 5, 8, 10, 7"
117,PersonalField57,int64,0,0.00,13,"0, 1, 2, 3, 4, 6, 5, 8, 10, 7"
118,PersonalField58,int64,0,0.00,7,"1, 3, 2, 4, 5, 6, 7"
119,PersonalField59,int64,0,0.00,7,"0, 1, 2, 3, 4, 6, 5"
120,PersonalField60,int64,0,0.00,7,"0, 1, 2, 3, 4, 6, 5"
121,PersonalField61,int64,0,0.00,7,"0, 1, 2, 3, 4, 6, 5"
122,PersonalField62,int64,0,0.00,7,"0, 1, 2, 3, 4, 6, 5"
123,PersonalField63,int64,0,0.00,7,"1, 3, 2, 4, 5, 6, 7"
124,PersonalField64,int64,0,0.00,3,"0, 1, 2"
125,PersonalField65,int64,0,0.00,3,"0, 1, 2"
126,PersonalField66,int64,0,0.00,3,"0, 1, 2"
127,PersonalField67,int64,0,0.00,3,"0, 1, 2"
128,PersonalField68,int64,0,0.00,4,"1, 3, 2, 4"
129,PersonalField69,int64,0,0.00,6,"0, 1, 2, 3, 5, 4"
130,PersonalField70,int64,0,0.00,7,"0, 1, 2, 3, 4, 5, 7"
131,PersonalField71,int64,0,0.00,7,"0, 1, 2, 3, 4, 5, 7"
132,PersonalField72,int64,0,0.00,8,"0, 1, 2, 3, 4, 5, 6, 7"
133,PersonalField73,int64,0,0.00,7,"1, 2, 3, 4, 5, 7, 6"
134,PersonalField74,int64,0,0.00,8,"0, 1, 2, 3, 4, 5, 7, 22"
135,PersonalField75,int64,0,0.00,9,"0, 1, 2, 3, 4, 6, 5, 8, 23"
136,PersonalField76,int64,0,0.00,10,"0, 1, 2, 3, 4, 6, 5, 8, 23, 7"
137,PersonalField77,int64,0,0.00,11,"0, 1, 2, 3, 4, 5, 6, 7, 8, 23"
138,PersonalField78,int64,0,0.00,7,"1, 2, 3, 4, 5, 7, 6"
139,PersonalField79,int64,0,0.00,13,"0, 1, 2, 3, 4, 6, 5, 8, 10, 7"
140,PersonalField80,int64,0,0.00,14,"0, 1, 2, 3, 4, 6, 5, 8, 10, 7"
141,PersonalField81,int64,0,0.00,14,"0, 1, 2, 3, 4, 6, 5, 8, 10, 7"
142,PersonalField82,int64,0,0.00,14,"0, 1, 2, 3, 4, 6, 5, 8, 10, 9"
143,PersonalField83,int64,0,0.00,7,"1, 3, 2, 4, 5, 6, 7"
144,PropertyField1A,int64,0,0.00,26,"4, 3, 5, 10, 8, 7, 6, 15, 16, 14"
145,PropertyField1B,int64,0,0.00,26,"20, 5, 15, 23, 21, 3, 8, 11, 18, 16"
146,PropertyField2A,int64,0,0.00,2,"-1, 25"
147,PropertyField2B,int64,0,0.00,21,"15, 8, 12, 13, 10, 9, 23, 2, 3, 4"
148,PropertyField6,int64,0,0.00,1,0
149,PropertyField8,int64,0,0.00,2,"1, 0"
150,PropertyField9,int64,0,0.00,3,"0, 1, 2"
151,PropertyField10,int64,0,0.00,5,"1, 2, 3, 4, 0"
152,PropertyField11A,int64,0,0.00,2,"-1, 25"
153,PropertyField11B,int64,0,0.00,5,"21, 24, 25, 23, 22"
154,PropertyField12,int64,0,0.00,7,"4, 1, 2, 3, 5, 7, 6"
155,PropertyField13,int64,0,0.00,4,"2, 1, 3, 0"
156,PropertyField15,int64,0,0.00,15,"4, 1, 2, 5, 8, 9, 10, 11, 14, 15"
157,PropertyField16A,int64,0,0.00,26,"3, 4, 5, 6, 7, 2, 8, 9, 10, 11"
158,PropertyField16B,int64,0,0.00,26,"1, 17, 9, 19, 23, 24, 18, 13, 8, 14"
159,PropertyField17,int64,0,0.00,8,"1, 0, 2, 3, 4, 5, 6, 7"
160,PropertyField18,int64,0,0.00,10,"2, 3, 1, 0, 4, 5, 6, 7, 8, 9"
161,PropertyField19,int64,0,0.00,10,"0, 1, 2, 3, 5, 4, 7, 9, 6, 8"
162,PropertyField20,int64,0,0.00,3,"0, 1, 2"
163,PropertyField21A,int64,0,0.00,26,"6, 5, 7, 4, 8, 9, 3, 10, 11, 12"
164,PropertyField21B,int64,0,0.00,26,"3, 2, 17, 25, 15, 1, 24, 19, 10, 7"
165,PropertyField22,int64,0,0.00,5,"2, 3, 4, 5, 1"
166,PropertyField23,int64,0,0.00,13,"1, 4, 2, 9, 13, 3, 10, 11, 8, 5"
167,PropertyField24A,int64,0,0.00,26,"7, 6, 8, 5, 4, 9, 10, 11, 3, 12"
168,PropertyField24B,int64,0,0.00,26,"4, 6, 18, 13, 25, 24, 12, 10, 1, 2"
169,PropertyField26A,int64,0,0.00,26,"9, 8, 6, 7, 10, 5, 11, 12, 4, 13"
170,PropertyField26B,int64,0,0.00,26,"10, 13, 12, 8, 20, 18, 21, 22, 6, 24"
171,PropertyField27,int64,0,0.00,17,"4, 10, 6, 13, 3, 15, 14, 7, 17, 19"
172,PropertyField35,int64,0,0.00,3,"2, 0, 1"
173,PropertyField39A,int64,0,0.00,26,"9, 11, 10, 12, 13, 8, 14, 7, 15, 6"
174,PropertyField39B,int64,0,0.00,26,"20, 14, 18, 6, 16, 21, 23, 12, 9, 3"
175,GeographicField1A,int64,0,0.00,26,"2, 3, 4, 5, 6, 7, 8, 9, 10, 11"
176,GeographicField1B,int64,0,0.00,26,"7, 11, 17, 2, 19, 4, 13, 10, 1, 18"
177,GeographicField2A,int64,0,0.00,26,"14, 13, 12, 11, 16, 17, 18, 15, 10, 9"
178,GeographicField2B,int64,0,0.00,26,"20, 5, 25, 21, 4, 8, 2, 9, 1, 23"
179,GeographicField3A,int64,0,0.00,25,"8, 9, 12, 11, 7, 6, 10, 13, 14, 15"
180,GeographicField3B,int64,0,0.00,25,"23, 17, 15, 8, 4, 18, 7, 19, 2, 1"
181,GeographicField4A,int64,0,0.00,25,"12, 13, 14, 11, 9, 15, 10, 16, 17, 8"
182,GeographicField4B,int64,0,0.00,25,"20, 2, 11, 8, 3, 17, 22, 12, 7, 16"
183,GeographicField5A,int64,0,0.00,2,"-1, 25"
184,GeographicField5B,int64,0,0.00,14,"13, 19, 25, 20, 23, 14, 16, 21, 22, 17"
185,GeographicField6A,int64,0,0.00,26,"2, 4, 5, 13, 9, 12, 10, 1, 24, 25"
186,GeographicField6B,int64,0,0.00,26,"13, 9, 2, 4, 16, 5, 22, 6, 20, 14"
187,GeographicField7A,int64,0,0.00,25,"10, 8, 9, 2, 24, 4, 12, 22, 21, 23"
188,GeographicField7B,int64,0,0.00,24,"13, 25, 22, 14, 16, 9, 6, 10, 3, 2"
189,GeographicField8A,int64,0,0.00,26,"2, 5, 14, 10, 9, 1, 13, 24, 25, 23"
190,GeographicField8B,int64,0,0.00,25,"13, 4, 8, 16, 15, 6, 20, 22, 25, 18"
191,GeographicField9A,int64,0,0.00,26,"2, 6, 5, 18, 20, 1, 14, 19, 7, 15"
192,GeographicField9B,int64,0,0.00,26,"12, 16, 3, 2, 14, 9, 10, 6, 23, 24"
193,GeographicField10A,int64,0,0.00,1,-1
194,GeographicField10B,int64,0,0.00,2,"25, -1"
195,GeographicField11A,int64,0,0.00,26,"2, 4, 9, 14, 24, 1, 25, 11, 13, 15"
196,GeographicField11B,int64,0,0.00,25,"15, 4, 9, 2, 16, 5, 23, 18, 25, 19"
197,GeographicField12A,int64,0,0.00,26,"2, 8, 9, 3, 13, 25, 21, 5, 6, 10"
198,GeographicField12B,int64,0,0.00,24,"13, 25, 22, 16, 4, 14, 8, 10, 23, 5"
199,GeographicField13A,int64,0,0.00,25,"2, 5, 9, 15, 24, 14, 1, 25, 11, 10"
200,GeographicField13B,int64,0,0.00,25,"14, 6, 9, 16, 2, 12, 10, 18, 22, 19"
201,GeographicField14A,int64,0,0.00,2,"-1, 25"
202,GeographicField14B,int64,0,0.00,20,"7, 13, 15, 18, 16, 10, 24, 19, 25, 22"
203,GeographicField15A,int64,0,0.00,26,"9, 10, 23, 11, 24, 3, 1, 6, 4, 2"
204,GeographicField15B,int64,0,0.00,24,"11, 22, 2, 25, 5, 17, 15, 12, 24, 16"
205,GeographicField16A,int64,0,0.00,26,"2, 5, 3, 6, 11, 10, 7, 8, 1, 9"
206,GeographicField16B,int64,0,0.00,26,"12, 2, 9, 16, 15, 5, 10, 21, 25, 24"
207,GeographicField17A,int64,0,0.00,26,"2, 3, 1, 25, 4, 14, 13, 15, 5, 16"
208,GeographicField17B,int64,0,0.00,26,"5, 16, 13, 7, 19, 10, 22, 25, 1, 24"
209,GeographicField18A,int64,0,0.00,2,"-1, 25"
210,GeographicField18B,int64,0,0.00,25,"2, 13, 10, 22, 14, 3, 8, 25, 7, 11"
211,GeographicField19A,int64,0,0.00,26,"2, 3, 22, 23, 20, 11, 4, 19, 10, 9"
212,GeographicField19B,int64,0,0.00,26,"18, 24, 8, 25, 14, 2, 4, 10, 11, 16"
213,GeographicField20A,int64,0,0.00,26,"3, 5, 2, 4, 6, 20, 22, 18, 23, 19"
214,GeographicField20B,int64,0,0.00,26,"24, 21, 8, 10, 14, 25, 18, 11, 22, 9"
215,GeographicField21A,int64,0,0.00,2,"-1, 25"
216,GeographicField21B,int64,0,0.00,23,"4, 22, 6, 24, 9, 11, 20, 7, 25, 16"
217,GeographicField22A,int64,0,0.00,2,"-1, 25"
218,GeographicField22B,int64,0,0.00,12,"15, 19, 20, 22, 25, 23, 16, 18, 21, 24"
219,GeographicField23A,int64,0,0.00,2,"-1, 25"
220,GeographicField23B,int64,0,0.00,26,"11, 18, 5, 20, 15, 25, 14, 2, 8, 7"
221,GeographicField24A,int64,0,0.00,25,"15, 13, 19, 16, 10, 18, 21, 17, 14, 24"
222,GeographicField24B,int64,0,0.00,25,"20, 11, 25, 8, 13, 15, 23, 21, 4, 9"
223,GeographicField25A,int64,0,0.00,25,"19, 16, 10, 13, 14, 17, 12, 11, 23, 24"
224,GeographicField25B,int64,0,0.00,25,"10, 24, 20, 6, 3, 8, 17, 14, 25, 22"
225,GeographicField26A,int64,0,0.00,26,"7, 6, 10, 16, 5, 13, 20, 21, 3, 11"
226,GeographicField26B,int64,0,0.00,25,"10, 21, 17, 5, 22, 13, 6, 14, 25, 24"
227,GeographicField27A,int64,0,0.00,25,"17, 13, 15, 16, 22, 24, 21, 14, 11, 6"
228,GeographicField27B,int64,0,0.00,24,"16, 14, 25, 20, 10, 3, 11, 21, 5, 6"
229,GeographicField28A,int64,0,0.00,26,"6, 7, 5, 8, 9, 4, 10, 11, 3, 12"
230,GeographicField28B,int64,0,0.00,26,"10, 23, 18, 3, 6, 2, 19, 22, 8, 11"
231,GeographicField29A,int64,0,0.00,26,"8, 9, 7, 6, 10, 11, 5, 12, 13, 4"
232,GeographicField29B,int64,0,0.00,26,"20, 5, 13, 10, 3, 12, 6, 11, 4, 21"
233,GeographicField30A,int64,0,0.00,26,"8, 7, 6, 9, 5, 10, 11, 4, 12, 3"
234,GeographicField30B,int64,0,0.00,26,"11, 8, 4, 16, 24, 15, 1, 10, 5, 25"
235,GeographicField31A,int64,0,0.00,26,"8, 7, 9, 6, 10, 5, 11, 12, 4, 13"
236,GeographicField31B,int64,0,0.00,26,"5, 19, 2, 25, 10, 14, 9, 6, 20, 15"
237,GeographicField32A,int64,0,0.00,26,"6, 5, 7, 8, 4, 9, 10, 3, 11, 12"
238,GeographicField32B,int64,0,0.00,26,"3, 15, 6, 2, 16, 25, 18, 8, 1, 12"
239,GeographicField33A,int64,0,0.00,26,"7, 8, 6, 5, 9, 10, 4, 11, 12, 13"
240,GeographicField33B,int64,0,0.00,26,"18, 6, 21, 25, 13, 14, 2, 19, 3, 24"
241,GeographicField34A,int64,0,0.00,26,"9, 11, 12, 10, 8, 13, 14, 7, 6, 15"
242,GeographicField34B,int64,0,0.00,26,"14, 9, 8, 22, 2, 10, 23, 1, 16, 15"
243,GeographicField35A,int64,0,0.00,26,"6, 7, 5, 8, 9, 4, 10, 3, 11, 12"
244,GeographicField35B,int64,0,0.00,26,"8, 12, 9, 3, 18, 16, 22, 17, 2, 14"
245,GeographicField36A,int64,0,0.00,26,"9, 8, 10, 7, 11, 6, 12, 5, 13, 14"
246,GeographicField36B,int64,0,0.00,26,"25, 21, 11, 10, 13, 9, 8, 1, 5, 4"
247,GeographicField37A,int64,0,0.00,26,"3, 4, 5, 2, 6, 7, 8, 9, 10, 11"
248,GeographicField37B,int64,0,0.00,26,"10, 5, 8, 21, 3, 15, 4, 22, 7, 16"
249,GeographicField38A,int64,0,0.00,26,"7, 8, 6, 9, 5, 10, 11, 12, 4, 13"
250,GeographicField38B,int64,0,0.00,26,"16, 1, 22, 14, 18, 6, 10, 23, 3, 9"
251,GeographicField39A,int64,0,0.00,26,"5, 6, 4, 7, 3, 8, 9, 10, 2, 11"
252,GeographicField39B,int64,0,0.00,26,"25, 10, 19, 5, 21, 13, 12, 2, 7, 1"
253,GeographicField40A,int64,0,0.00,26,"3, 2, 11, 10, 12, 8, 9, 7, 1, 25"
254,GeographicField40B,int64,0,0.00,26,"14, 19, 11, 22, 2, 1, 21, 13, 10, 3"
255,GeographicField41A,int64,0,0.00,26,"24, 2, 14, 23, 13, 18, 3, 16, 17, 15"
256,GeographicField41B,int64,0,0.00,26,"11, 22, 4, 25, 6, 17, 14, 23, 9, 8"
257,GeographicField42A,int64,0,0.00,26,"7, 13, 12, 6, 14, 8, 11, 10, 9, 5"
258,GeographicField42B,int64,0,0.00,26,"21, 15, 10, 1, 12, 17, 18, 6, 8, 24"
259,GeographicField43A,int64,0,0.00,26,"11, 10, 9, 12, 3, 2, 8, 13, 6, 7"
260,GeographicField43B,int64,0,0.00,26,"5, 24, 18, 14, 6, 2, 1, 22, 15, 13"
261,GeographicField44A,int64,0,0.00,26,"9, 8, 14, 11, 10, 22, 13, 21, 15, 20"
262,GeographicField44B,int64,0,0.00,26,"15, 22, 9, 2, 20, 10, 16, 21, 7, 11"
263,GeographicField45A,int64,0,0.00,26,"11, 9, 2, 12, 10, 8, 3, 7, 22, 1"
264,GeographicField45B,int64,0,0.00,26,"4, 7, 2, 16, 14, 17, 1, 22, 18, 10"
265,GeographicField46A,int64,0,0.00,26,"10, 9, 21, 11, 20, 19, 12, 14, 13, 18"
266,GeographicField46B,int64,0,0.00,26,"7, 17, 15, 2, 19, 13, 14, 20, 24, 22"
267,GeographicField47A,int64,0,0.00,26,"6, 7, 21, 8, 9, 13, 5, 22, 12, 25"
268,GeographicField47B,int64,0,0.00,25,"5, 23, 18, 10, 24, 25, 14, 3, 16, 11"
269,GeographicField48A,int64,0,0.00,26,"19, 17, 15, 16, 20, 18, 21, 22, 14, 12"
270,GeographicField48B,int64,0,0.00,26,"8, 3, 25, 4, 20, 16, 1, 21, 13, 22"
271,GeographicField49A,int64,0,0.00,26,"18, 17, 19, 20, 16, 15, 21, 14, 13, 22"
272,GeographicField49B,int64,0,0.00,26,"25, 13, 23, 16, 17, 12, 18, 5, 3, 1"
273,GeographicField50A,int64,0,0.00,26,"17, 16, 18, 15, 14, 19, 20, 13, 21, 22"
274,GeographicField50B,int64,0,0.00,26,"23, 11, 20, 1, 10, 2, 14, 24, 19, 18"
275,GeographicField51A,int64,0,0.00,26,"14, 15, 13, 11, 17, 16, 12, 18, 10, 9"
276,GeographicField51B,int64,0,0.00,26,"25, 17, 16, 10, 21, 22, 7, 13, 4, 6"
277,GeographicField52A,int64,0,0.00,26,"14, 15, 13, 16, 11, 17, 12, 9, 19, 18"
278,GeographicField52B,int64,0,0.00,26,"17, 19, 23, 24, 25, 10, 3, 12, 5, 1"
279,GeographicField53A,int64,0,0.00,26,"20, 18, 19, 21, 22, 17, 16, 23, 15, 14"
280,GeographicField53B,int64,0,0.00,26,"25, 16, 15, 1, 17, 23, 13, 4, 5, 19"
281,GeographicField54A,int64,0,0.00,26,"15, 14, 16, 13, 12, 17, 11, 10, 18, 19"
282,GeographicField54B,int64,0,0.00,26,"2, 8, 25, 17, 24, 9, 14, 13, 7, 18"
283,GeographicField55A,int64,0,0.00,26,"4, 3, 5, 6, 7, 2, 8, 9, 10, 11"
284,GeographicField55B,int64,0,0.00,26,"9, 4, 12, 20, 5, 25, 7, 18, 21, 2"
285,GeographicField56A,int64,0,0.00,2,"-1, 25"
286,GeographicField56B,int64,0,0.00,25,"2, 10, 25, 22, 11, 12, 23, 17, 5, 20"
287,GeographicField57A,int64,0,0.00,26,"13, 14, 15, 12, 16, 11, 10, 17, 9, 18"
288,GeographicField57B,int64,0,0.00,26,"19, 12, 24, 7, 1, 10, 8, 16, 3, 9"
289,GeographicField58A,int64,0,0.00,26,"11, 10, 9, 12, 13, 8, 14, 15, 7, 6"
290,GeographicField58B,int64,0,0.00,26,"1, 22, 16, 8, 4, 5, 6, 3, 11, 12"
291,GeographicField59A,int64,0,0.00,26,"11, 10, 12, 14, 8, 9, 13, 15, 6, 7"
292,GeographicField59B,int64,0,0.00,26,"6, 10, 16, 22, 4, 9, 21, 25, 19, 23"
293,GeographicField60A,int64,0,0.00,2,"-1, 25"
294,GeographicField60B,int64,0,0.00,26,"18, 14, 5, 3, 1, 23, 11, 20, 2, 17"
295,GeographicField61A,int64,0,0.00,2,"-1, 25"
296,GeographicField61B,int64,0,0.00,25,"2, 4, 25, 5, 23, 13, 7, 14, 6, 16"
297,GeographicField62A,int64,0,0.00,2,"-1, 25"
298,GeographicField62B,int64,0,0.00,19,"8, 11, 17, 23, 13, 16, 25, 21, 15, 19"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
QuoteNumber,260753.0,217201.246011,125478.522633,1.0000,434588.0000
Field7,260753.0,18.293339,7.382803,1.0000,28.0000
Field8,260753.0,0.938346,0.037086,0.8746,1.0101
Field9,260753.0,0.001451,0.001486,0.0004,0.0040
Field10,260753.0,954.110829,290.571712,548.0000,1487.0000
Field11,260753.0,1.162718,0.116833,1.0000,1.3045
CoverageField1A,260753.0,9.012533,5.576509,-1.0000,25.0000
CoverageField1B,260753.0,13.000403,7.219264,-1.0000,25.0000
CoverageField2A,260753.0,9.054005,5.560521,1.0000,25.0000
CoverageField2B,260753.0,13.015240,7.211717,1.0000,25.0000
CoverageField3A,260753.0,9.053150,5.579687,1.0000,25.0000
CoverageField3B,260753.0,13.007563,7.211417,1.0000,25.0000
CoverageField4A,260753.0,8.967540,5.549876,1.0000,25.0000
CoverageField4B,260753.0,13.013496,7.202253,1.0000,25.0000
CoverageField5A,260753.0,13.818568,5.102779,1.0000,25.0000
CoverageField5B,260753.0,21.206379,4.901781,1.0000,25.0000
CoverageField6A,260753.0,11.488685,6.892669,1.0000,25.0000
CoverageField6B,260753.0,19.202421,7.381384,1.0000,25.0000
CoverageField11A,260753.0,7.809249,5.294721,-1.0000,25.0000
CoverageField11B,260753.0,12.982175,7.249269,-1.0000,25.0000
SalesField1A,260753.0,6.223767,5.201169,1.0000,25.0000
SalesField1B,260753.0,13.000107,7.206967,1.0000,25.0000
SalesField2A,260753.0,5.734247,4.996300,-1.0000,25.0000
SalesField2B,260753.0,12.982704,7.224063,-1.0000,25.0000
SalesField3,260753.0,0.744958,0.435886,0.0000,1.0000
SalesField4,260753.0,4.343486,1.024308,1.0000,5.0000
SalesField5,260753.0,4.224600,0.977157,1.0000,5.0000
SalesField6,260753.0,14.001154,6.297276,1.0000,24.0000
SalesField8,260753.0,33734.858314,19444.146851,1.0000,67164.0000
SalesField9,260753.0,0.147005,0.354112,0.0000,1.0000
SalesField10,260753.0,0.340698,0.773829,0.0000,21.0000
SalesField11,260753.0,0.597911,1.107087,0.0000,32.0000
SalesField12,260753.0,0.623966,1.136513,0.0000,32.0000
SalesField13,260753.0,0.063623,0.288390,0.0000,7.0000
SalesField14,260753.0,0.095527,0.367653,0.0000,14.0000
SalesField15,260753.0,0.098189,0.374738,0.0000,14.0000
PersonalField1,260753.0,0.726515,0.445748,0.0000,1.0000
PersonalField2,260753.0,0.699156,0.458626,0.0000,1.0000
PersonalField4A,260753.0,9.729763,6.821498,-1.0000,25.0000
PersonalField4B,260753.0,11.940726,8.003960,-1.0000,25.0000
PersonalField5,260753.0,6.630781,0.568167,1.0000,10.0000
PersonalField6,260753.0,0.370278,0.482880,0.0000,1.0000
PersonalField8,260753.0,1.000150,0.012539,1.0000,3.0000
PersonalField9,260753.0,2.152236,0.494768,1.0000,3.0000
PersonalField10A,260753.0,6.922586,6.738417,-1.0000,25.0000
PersonalField10B,260753.0,10.138595,8.573812,-1.0000,25.0000
PersonalField11,260753.0,0.023563,0.160741,0.0000,4.0000
PersonalField12,260753.0,2.204285,1.663651,1.0000,5.0000
PersonalField13,260753.0,1.992177,0.090847,1.0000,4.0000
PersonalField14,260753.0,2.954420,1.349083,1.0000,54.0000
PersonalField15,260753.0,16.165919,8.164436,1.0000,24.0000
PersonalField22,260753.0,1.049330,0.345003,1.0000,7.0000
PersonalField23,260753.0,0.025702,0.232619,0.0000,14.0000
PersonalField24,260753.0,0.031747,0.263228,0.0000,14.0000
PersonalField25,260753.0,0.036901,0.286833,0.0000,14.0000
PersonalField26,260753.0,0.044195,0.320752,0.0000,14.0000
PersonalField27,260753.0,0.548941,0.621003,0.0000,23.0000
PersonalField28,260753.0,1.510610,0.567467,1.0000,7.0000
PersonalField29,260753.0,1.522184,0.604798,1.0000,7.0000
PersonalField30,260753.0,0.055965,0.246379,0.0000,22.0000
PersonalField31,260753.0,0.296833,0.469694,0.0000,23.0000
PersonalField32,260753.0,0.470196,0.512921,0.0000,23.0000
PersonalField33,260753.0,0.497674,0.517218,0.0000,23.0000
PersonalField34,260753.0,1.007785,0.121861,1.0000,7.0000
PersonalField35,260753.0,0.003294,0.061809,0.0000,5.0000
PersonalField36,260753.0,0.004011,0.069177,0.0000,5.0000
PersonalField37,260753.0,0.004901,0.076544,0.0000,5.0000
PersonalField38,260753.0,0.005825,0.084734,0.0000,5.0000
PersonalField39,260753.0,0.001154,0.045954,0.0000,8.0000
PersonalField40,260753.0,0.001500,0.055473,0.0000,9.0000
PersonalField41,260753.0,0.001810,0.060142,0.0000,9.0000
PersonalField42,260753.0,0.002343,0.066858,0.0000,9.0000
PersonalField43,260753.0,1.002512,0.073935,1.0000,7.0000
PersonalField44,260753.0,0.059873,0.255855,0.0000,22.0000
PersonalField45,260753.0,0.301596,0.473948,0.0000,23.0000
PersonalField46,260753.0,0.476021,0.515998,0.0000,23.0000
PersonalField47,260753.0,0.504734,0.521330,0.0000,23.0000
PersonalField48,260753.0,1.530728,0.611921,1.0000,7.0000
PersonalField49,260753.0,0.001676,0.053282,0.0000,7.0000
PersonalField50,260753.0,0.002052,0.058024,0.0000,7.0000
PersonalField51,260753.0,0.002332,0.061198,0.0000,7.0000
PersonalField52,260753.0,0.002673,0.065630,0.0000,7.0000
PersonalField53,260753.0,1.003540,0.088877,1.0000,7.0000
PersonalField54,260753.0,0.004882,0.104451,0.0000,12.0000
PersonalField55,260753.0,0.005929,0.114806,0.0000,12.0000
PersonalField56,260753.0,0.007060,0.126733,0.0000,14.0000
PersonalField57,260753.0,0.008548,0.138030,0.0000,14.0000
PersonalField58,260753.0,1.009637,0.153311,1.0000,7.0000
PersonalField59,260753.0,0.004771,0.083501,0.0000,6.0000
PersonalField60,260753.0,0.005791,0.093083,0.0000,6.0000
PersonalField61,260753.0,0.006612,0.100136,0.0000,6.0000
PersonalField62,260753.0,0.007977,0.110005,0.0000,6.0000
PersonalField63,260753.0,1.010186,0.147343,1.0000,7.0000
PersonalField64,260753.0,0.000468,0.021802,0.0000,2.0000
PersonalField65,260753.0,0.000606,0.025072,0.0000,2.0000
PersonalField66,260753.0,0.000771,0.028571,0.0000,2.0000
PersonalField67,260753.0,0.001081,0.034240,0.0000,2.0000
PersonalField68,260753.0,1.001216,0.046451,1.0000,4.0000
PersonalField69,260753.0,0.000376,0.026705,0.0000,5.0000
PersonalField70,260753.0,0.000545,0.034140,0.0000,7.0000
PersonalField71,260753.0,0.000660,0.037151,0.0000,7.0000
PersonalField72,260753.0,0.000886,0.042582,0.0000,7.0000
PersonalField73,260753.0,1.000825,0.043738,1.0000,7.0000
PersonalField74,260753.0,0.058741,0.249449,0.0000,22.0000
PersonalField75,260753.0,0.299897,0.470021,0.0000,23.0000
PersonalField76,260753.0,0.473433,0.511976,0.0000,23.0000
PersonalField77,260753.0,0.500838,0.516131,0.0000,23.0000
PersonalField78,260753.0,1.527879,0.609685,1.0000,7.0000
PersonalField79,260753.0,0.026841,0.240302,0.0000,14.0000
PersonalField80,260753.0,0.033453,0.272012,0.0000,14.0000
PersonalField81,260753.0,0.039501,0.297738,0.0000,14.0000
PersonalField82,260753.0,0.048103,0.336888,0.0000,14.0000
PersonalField83,260753.0,1.052038,0.354014,1.0000,7.0000
PersonalField84,136545.0,1.990142,0.127931,1.0000,8.0000
PropertyField1A,260753.0,10.276913,6.307857,-1.0000,25.0000
PropertyField1B,260753.0,13.147987,7.183770,-1.0000,25.0000
PropertyField2A,260753.0,-0.341707,4.084403,-1.0000,25.0000
PropertyField2B,260753.0,13.519549,7.003219,2.0000,25.0000
PropertyField6,260753.0,0.000000,0.000000,0.0000,0.0000
PropertyField8,260753.0,0.665565,0.471794,0.0000,1.0000
PropertyField9,260753.0,0.000065,0.008974,0.0000,2.0000
PropertyField10,260753.0,1.006278,0.092244,0.0000,4.0000
PropertyField11A,260753.0,-0.353373,4.048981,-1.0000,25.0000
PropertyField11B,260753.0,21.400126,1.020122,21.0000,25.0000
PropertyField12,260753.0,2.958601,1.278441,1.0000,7.0000
PropertyField13,260753.0,1.731317,0.806338,0.0000,3.0000
PropertyField15,260753.0,3.494997,1.780884,1.0000,15.0000
PropertyField16A,260753.0,7.713905,5.453604,-1.0000,25.0000
PropertyField16B,260753.0,13.001588,7.211086,-1.0000,25.0000
PropertyField17,260753.0,0.638313,0.597185,0.0000,7.0000
PropertyField18,260753.0,2.001427,0.838974,0.0000,9.0000
PropertyField19,260753.0,0.419174,0.542287,0.0000,9.0000
PropertyField20,260753.0,0.000069,0.009985,0.0000,2.0000
PropertyField21A,260753.0,9.052233,5.564473,-1.0000,25.0000
PropertyField21B,260753.0,12.993799,7.217917,-1.0000,25.0000
PropertyField22,260753.0,2.004844,0.080002,1.0000,5.0000
PropertyField23,260753.0,1.990328,2.562918,1.0000,14.0000
PropertyField24A,260753.0,9.872646,5.771066,-1.0000,25.0000
PropertyField24B,260753.0,13.004015,7.214597,-1.0000,25.0000
PropertyField25,260753.0,1.632422,0.717064,0.0000,7.0000
PropertyField26A,260753.0,10.198985,5.559468,-1.0000,25.0000
PropertyField26B,260753.0,13.035839,7.204143,-1.0000,25.0000
PropertyField27,260753.0,7.388605,3.527035,1.0000,19.0000
PropertyField29,60068.0,0.000200,0.014133,0.0000,1.0000
PropertyField35,260753.0,1.447972,0.791729,0.0000,2.0000
PropertyField39A,260753.0,11.745276,5.628194,-1.0000,25.0000
PropertyField39B,260753.0,13.006562,7.208360,-1.0000,25.0000
GeographicField1A,260753.0,7.320932,5.255960,-1.0000,25.0000
GeographicField1B,260753.0,12.993258,7.206806,-1.0000,25.0000
GeographicField2A,260753.0,13.628127,6.119374,-1.0000,25.0000
GeographicField2B,260753.0,12.937972,7.264069,-1.0000,25.0000
GeographicField3A,260753.0,11.938263,6.254878,1.0000,25.0000
GeographicField3B,260753.0,12.998259,7.215076,1.0000,25.0000
GeographicField4A,260753.0,12.986190,5.772189,1.0000,25.0000
GeographicField4B,260753.0,12.995049,7.211063,1.0000,25.0000
GeographicField5A,260753.0,-0.347390,4.067188,-1.0000,25.0000
GeographicField5B,260753.0,16.131891,4.041026,-1.0000,25.0000
GeographicField6A,260753.0,7.317573,6.753417,-1.0000,25.0000
GeographicField6B,260753.0,13.119174,7.166691,-1.0000,25.0000
GeographicField7A,260753.0,11.182932,7.419025,-1.0000,25.0000
GeographicField7B,260753.0,13.322896,7.267777,-1.0000,25.0000
GeographicField8A,260753.0,7.698082,6.834840,-1.0000,25.0000
GeographicField8B,260753.0,13.188508,7.137298,-1.0000,25.0000
GeographicField9A,260753.0,8.904197,7.641955,-1.0000,25.0000
GeographicField9B,260753.0,13.158150,7.160769,-1.0000,25.0000
GeographicField10A,260753.0,-1.000000,0.000000,-1.0000,-1.0000
GeographicField10B,260753.0,24.999801,0.072007,-1.0000,25.0000
GeographicField11A,260753.0,7.368360,7.053944,-1.0000,25.0000
GeographicField11B,260753.0,13.170882,7.175042,-1.0000,25.0000
GeographicField12A,260753.0,10.697771,7.685295,-1.0000,25.0000
GeographicField12B,260753.0,13.309247,7.222460,-1.0000,25.0000
GeographicField13A,260753.0,7.776873,7.059001,-1.0000,25.0000
GeographicField13B,260753.0,13.196884,7.141874,-1.0000,25.0000
GeographicField14A,260753.0,-0.308104,4.184573,-1.0000,25.0000
GeographicField14B,260753.0,13.961937,6.089020,-1.0000,25.0000
GeographicField15A,260753.0,11.659456,7.329376,-1.0000,25.0000
GeographicField15B,260753.0,13.290493,7.238379,-1.0000,25.0000
GeographicField16A,260753.0,7.283870,5.996911,-1.0000,25.0000
GeographicField16B,260753.0,13.165636,7.145783,-1.0000,25.0000
GeographicField17A,260753.0,5.017024,5.965579,-1.0000,25.0000
GeographicField17B,260753.0,13.001856,7.208129,-1.0000,25.0000
GeographicField18A,260753.0,-0.340111,4.089220,-1.0000,25.0000
GeographicField18B,260753.0,13.040540,7.148556,-1.0000,25.0000
GeographicField19A,260753.0,11.839929,8.015434,-1.0000,25.0000
GeographicField19B,260753.0,13.028878,7.219295,-1.0000,25.0000
GeographicField20A,260753.0,8.500305,7.610211,-1.0000,25.0000
GeographicField20B,260753.0,13.027141,7.220227,-1.0000,25.0000
GeographicField21A,260753.0,-0.355068,4.043805,-1.0000,25.0000
GeographicField21B,260753.0,13.251771,6.860357,-1.0000,25.0000
GeographicField22A,260753.0,-0.342404,4.082293,-1.0000,25.0000
GeographicField22B,260753.0,17.211714,3.256059,-1.0000,25.0000
GeographicField23A,260753.0,-0.336222,4.100937,-1.0000,25.0000
GeographicField23B,260753.0,13.027187,7.206281,-1.0000,25.0000
GeographicField24A,260753.0,15.535779,5.319601,-1.0000,25.0000
GeographicField24B,260753.0,13.347651,7.302521,-1.0000,25.0000
GeographicField25A,260753.0,14.616284,5.491716,-1.0000,25.0000
GeographicField25B,260753.0,13.223453,7.200182,-1.0000,25.0000
GeographicField26A,260753.0,11.238943,6.372208,-1.0000,25.0000
GeographicField26B,260753.0,13.327582,7.247695,-1.0000,25.0000
GeographicField27A,260753.0,16.131393,5.483249,-1.0000,25.0000
GeographicField27B,260753.0,13.287187,7.252209,-1.0000,25.0000
GeographicField28A,260753.0,9.127696,5.376748,-1.0000,25.0000
GeographicField28B,260753.0,12.989910,7.213153,-1.0000,25.0000
GeographicField29A,260753.0,9.885811,5.166222,-1.0000,25.0000
GeographicField29B,260753.0,12.991862,7.211939,-1.0000,25.0000
GeographicField30A,260753.0,8.543438,4.595461,-1.0000,25.0000
GeographicField30B,260753.0,12.998221,7.212441,-1.0000,25.0000
GeographicField31A,260753.0,9.569666,5.191816,-1.0000,25.0000
GeographicField31B,260753.0,12.987881,7.219891,-1.0000,25.0000
GeographicField32A,260753.0,8.974129,5.412133,-1.0000,25.0000
GeographicField32B,260753.0,12.985101,7.212126,-1.0000,25.0000
GeographicField33A,260753.0,9.570628,5.337012,-1.0000,25.0000
GeographicField33B,260753.0,12.990880,7.217423,-1.0000,25.0000
GeographicField34A,260753.0,11.243579,5.291310,-1.0000,25.0000
GeographicField34B,260753.0,12.993365,7.208759,-1.0000,25.0000
GeographicField35A,260753.0,8.722128,5.101554,-1.0000,25.0000
GeographicField35B,260753.0,12.993036,7.205562,-1.0000,25.0000
GeographicField36A,260753.0,9.837463,4.963367,-1.0000,25.0000
GeographicField36B,260753.0,12.997534,7.215417,-1.0000,25.0000
GeographicField37A,260753.0,6.936584,5.255492,-1.0000,25.0000
GeographicField37B,260753.0,12.824347,7.324679,-1.0000,25.0000
GeographicField38A,260753.0,9.429115,5.135136,-1.0000,25.0000
GeographicField38B,260753.0,12.996687,7.210751,-1.0000,25.0000
GeographicField39A,260753.0,8.027931,5.203351,-1.0000,25.0000
GeographicField39B,260753.0,12.997477,7.220603,-1.0000,25.0000
GeographicField40A,260753.0,8.324219,5.742342,-1.0000,25.0000
GeographicField40B,260753.0,12.994098,7.208082,-1.0000,25.0000
GeographicField41A,260753.0,14.619602,7.593831,-1.0000,25.0000
GeographicField41B,260753.0,13.016069,7.211858,-1.0000,25.0000
GeographicField42A,260753.0,10.983778,5.393446,-1.0000,25.0000
GeographicField42B,260753.0,12.994013,7.204325,-1.0000,25.0000
GeographicField43A,260753.0,10.286693,5.616717,-1.0000,25.0000
GeographicField43B,260753.0,13.000303,7.212508,-1.0000,25.0000
GeographicField44A,260753.0,13.414703,5.733257,-1.0000,25.0000
GeographicField44B,260753.0,12.997787,7.207199,-1.0000,25.0000
GeographicField45A,260753.0,10.041710,6.114244,-1.0000,25.0000
GeographicField45B,260753.0,13.001511,7.211625,-1.0000,25.0000
GeographicField46A,260753.0,13.188968,5.381441,-1.0000,25.0000
GeographicField46B,260753.0,13.003532,7.207169,-1.0000,25.0000
GeographicField47A,260753.0,9.706017,6.109350,-1.0000,25.0000
GeographicField47B,260753.0,13.119113,7.257001,-1.0000,25.0000
GeographicField48A,260753.0,14.375309,6.322120,-1.0000,25.0000
GeographicField48B,260753.0,12.941512,7.262354,-1.0000,25.0000
GeographicField49A,260753.0,15.999091,5.513966,-1.0000,25.0000
GeographicField49B,260753.0,12.937746,7.260546,-1.0000,25.0000
GeographicField50A,260753.0,14.933719,5.957889,-1.0000,25.0000
GeographicField50B,260753.0,12.943433,7.262158,-1.0000,25.0000
GeographicField51A,260753.0,13.130399,6.007871,-1.0000,25.0000
GeographicField51B,260753.0,12.937167,7.260404,-1.0000,25.0000
GeographicField52A,260753.0,13.022370,6.095688,-1.0000,25.0000
GeographicField52B,260753.0,12.937815,7.262391,-1.0000,25.0000
GeographicField53A,260753.0,16.089207,5.840487,-1.0000,25.0000
GeographicField53B,260753.0,12.937911,7.259907,-1.0000,25.0000
GeographicField54A,260753.0,13.500174,5.766017,-1.0000,25.0000
GeographicField54B,260753.0,12.922313,7.270204,-1.0000,25.0000
GeographicField55A,260753.0,8.087980,5.707726,-1.0000,25.0000
GeographicField55B,260753.0,12.908837,7.273700,-1.0000,25.0000
GeographicField56A,260753.0,-0.341906,4.083800,-1.0000,25.0000
GeographicField56B,260753.0,12.965699,7.210315,-1.0000,25.0000
GeographicField57A,260753.0,13.205045,5.310079,-1.0000,25.0000
GeographicField57B,260753.0,13.002857,7.212153,-1.0000,25.0000
GeographicField58A,260753.0,11.567756,5.448425,-1.0000,25.0000
GeographicField58B,260753.0,12.985695,7.216091,-1.0000,25.0000
GeographicField59A,260753.0,11.694903,5.626092,-1.0000,25.0000
GeographicField59B,260753.0,13.049882,7.213636,-1.0000,25.0000
GeographicField60A,260753.0,-0.350481,4.057792,-1.0000,25.0000
GeographicField60B,260753.0,12.994362,7.219943,-1.0000,25.0000
GeographicField61A,260753.0,-0.343601,4.078673,-1.0000,25.0000
GeographicField61B,260753.0,13.042734,7.145248,-1.0000,25.0000
GeographicField62A,260753.0,-0.341009,4.086511,-1.0000,25.0000
GeographicField62B,260753.0,14.122948,5.829091,-1.0000,25.0000

In [7]:
# Categorical Feature Statistics
cat_stats

                                         value   count    pct
column               rank
CoverageField8       1                       Y  143152  54.90
                     2                       T   93778  35.96
                     3                       X   21625   8.29
                     4                       Z     899   0.34
                     5                       U     477   0.18
CoverageField9       1                       E   85017  32.60
                     2                       D   49605  19.02
                     3                       G   32672  12.53
                     4                       F   32520  12.47
                     5                       K   27277  10.46
Field12              1                       N  241867  92.76
                     2                       Y   18886   7.24
Field6               1                       B   94694  36.32
                     2                       F   69053  26.48
                     3                       J   51782  19.86
                     4                       E   26063  10.00
                     5                       K   13226   5.07
GeographicField63    1                       N  254712  97.68
                     2                       Y    6039   2.32
                     3                               2   0.00
GeographicField64    1                      CA   94725  36.33
                     2                      NJ   69293  26.57
                     3                      TX   65011  24.93
                     4                      IL   31724  12.17
Original_Quote_Date  1     2014-03-03 00:00:00     646   0.25
                     2     2015-03-31 00:00:00     608   0.23
                     3     2014-02-24 00:00:00     600   0.23
                     4     2015-03-23 00:00:00     594   0.23
                     5     2015-03-17 00:00:00     586   0.22
PersonalField16      1                      ZA  124015  47.56
                     2                      XR   15051   5.77
                     3                      XJ   10153   3.89
                     4                      XM    9767   3.75
                     5                      XD    8143   3.12
PersonalField17      1                      ZE  124015  47.56
                     2                      XV   20857   8.00
                     3                      XS   15733   6.03
                     4                      YY   12619   4.84
                     5                      ZK   10780   4.13
PersonalField18      1                      XR  124015  47.56
                     2                      YP   31893  12.23
                     3                      ZW   19032   7.30
                     4                      XF   15797   6.06
                     5                      YI    7283   2.79
PersonalField19      1                      XD  124015  47.56
                     2                      XC   70489  27.03
                     3                      XX   13690   5.25
                     4                      ZQ    8282   3.18
                     5                      YF    5487   2.10
PersonalField7       1                       N  259379  99.47
                     2                       Y    1261   0.48
                     3                    <NA>     113   0.04
PropertyField14      1                       C  195586  75.01
                     2                       A   36277  13.91
                     3                       B   28846  11.06
                     4                       D      44   0.02
PropertyField28      1                       B  243374  93.34
                     2                       A    9136   3.50
                     3                       D    6994   2.68
                     4                       C    1249   0.48
PropertyField3       1                       N  226966  87.04
                     2                       Y   33706  12.93
                     3                    <NA>      81   0.03
PropertyField30      1                       N  245807  94.27
                     2                       Y   14946   5.73
PropertyField31      1                       O  156042  59.84
                     2                       K   61146  23.45
                     3                       N   33298  12.77
                     4                       M   10267   3.94
PropertyField32      1                       Y  191627  73.49
                     2                       N   69056  26.48
                     3                    <NA>      70   0.03
PropertyField33      1                       H  123098  47.21
                     2                       G   80649  30.93
                     3                       E   47359  18.16
                     4                       F    9647   3.70
PropertyField34      1                       Y  141185  54.15
                     2                       N  119498  45.83
                     3                    <NA>      70   0.03
PropertyField36      1                       N  248302  95.22
                     2                       Y   12338   4.73
                     3                    <NA>     113   0.04
PropertyField37      1                       N  185976  71.32
                     2                       Y   74777  28.68
PropertyField38      1                       N  254032  97.42
                     2                       Y    5501   2.11
                     3                    <NA>    1220   0.47
PropertyField4       1                       N  226223  86.76
                     2                       Y   34467  13.22
                     3                    <NA>      63   0.02
PropertyField5       1                       Y  260637  99.96
                     2                       N     116   0.04
PropertyField7       1                       O   74326  28.50
                     2                       R   68974  26.45
                     3                       J   35969  13.79
                     4                       D   28142  10.79
                     5                       S   16954   6.50
QuoteConversion_Flag 1                       0  211859  81.25
                     2                       1   48894  18.75
SalesField7          1                       K   50261  19.28
                     2                       P   49251  18.89
                     3                       T   45154  17.32
                     4                       Q   41015  15.73
                     5                       V   38248  14.67

In [8]:
# Target Distribution
target_df

                       count    pct
QuoteConversion_Flag
0                     211859  81.25
1                      48894  18.75

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_iid_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_iid_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=1, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019c1156-f087-7911-bcc4-1f0110b22394
ec278a1c0952360b6ecc8eac69f714c1d2a9da95c72a819798f976b88a4ed775