### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="home_credit_default_risk",
    dataset_year="2018",
    domain_str="finance",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/c/home-credit-default-risk",
    download_description="""
We download the files from the Kaggle data. This dataset starts as a SQL database with multiple tables, so it has multiple files.

kaggle competitions download -c home-credit-default-risk && unzip home-credit-default-risk.zip -d data_files && rm home-credit-default-risk.zip
mkdir -p local-data-warehouse/home_credit_default_risk && mv data_files local-data-warehouse/home_credit_default_risk/
""",
    # References
    academic_reference_bibtex=r"""@misc{Montoya2018HomeCreditDefaultRisk,
  author = {Anna Montoya and inversion and Kirill Odintsov and Martin Kotek},
  title  = {Home Credit Default Risk},
  year   = {2018},
  howpublished = {\url{https://kaggle.com/competitions/home-credit-default-risk}},
  note   = {Kaggle competition}
}
""",
    academic_reference_bibtex_key="Montoya2018HomeCreditDefaultRisk",
    license="Kaggle Competition Rules",
    data_tags=["IID"],
    curation_comments="""
We start with the SQL tables from Kaggle. We then merge these tables into a single file following the top Kaggle solutions.
We start from this file.

- The top solutions start with various features from public notebooks/kernels. When selecting the kernel to use as our starting point, we looked among the most popular and best performance on the leaderboard. We found https://www.kaggle.com/code/jsaguiar/lightgbm-with-simple-features?scriptVersionId=6025993 and its follow-up https://www.kaggle.com/code/ogrellier/lighgbm-with-selected-features. We use the later one, because it performance better and comes with a reduced set of features from the initial raw merges. Note, this may introduce a slight bias, as the feature selection was done for LGBM.
- We do not follow the script exactly. We do not ordinal encode binary features. Moreover, we do not apply one-hot encoding to all categorical columns. Instead, we do it only when need for aggregations and otherwise keep the categorical column with the original semantics. Moreover, we fix some bugs in the original script that cause it to crash when run out of the box.
- We drop a duplicated column after preprocessing.
- We replace values that became inf after aggregation with NaN. This occurred across several aggregated columns.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="TARGET",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="TARGET",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

# Following https://www.kaggle.com/code/ogrellier/lighgbm-with-selected-features/script

# =========== `def application_train_test` refactored ===========
df = pd.read_csv(dataset_mold.path / "data_files" / "application_train.csv")

# Remove 4 applications with XNA CODE_GENDER (train set)
df = df[df['CODE_GENDER'] != 'XNA']
# NaN values for DAYS_EMPLOYED: 365.243 -> nan
df['DAYS_EMPLOYED'] = df['DAYS_EMPLOYED'].replace(365243, np.nan)
# Special features docs and live
docs = [_f for _f in df.columns if 'FLAG_DOC' in _f]
df['NEW_DOC_IND_AVG'] = df[docs].mean(axis=1)
df['NEW_DOC_IND_STD'] = df[docs].std(axis=1)
df['NEW_DOC_IND_KURT'] = df[docs].kurtosis(axis=1)
live = [_f for _f in df.columns if ('FLAG_' in _f) & ('FLAG_DOC' not in _f) & ('_FLAG_' not in _f)]
tmp_live_df = df[live].copy()
for bin_feature in ['FLAG_OWN_CAR', 'FLAG_OWN_REALTY']:
    tmp_live_df[bin_feature], _ = pd.factorize(tmp_live_df[bin_feature])
df['NEW_LIVE_IND_SUM'] = tmp_live_df.sum(axis=1)
df['NEW_LIVE_IND_STD'] = tmp_live_df.std(axis=1)
df['NEW_LIVE_IND_KURT'] = tmp_live_df[live].kurtosis(axis=1)
del tmp_live_df
# Special features
inc_by_org = df[['AMT_INCOME_TOTAL', 'ORGANIZATION_TYPE']].groupby('ORGANIZATION_TYPE').median()['AMT_INCOME_TOTAL']
df['NEW_INC_BY_ORG'] = df['ORGANIZATION_TYPE'].map(inc_by_org)
df['NEW_CREDIT_TO_ANNUITY_RATIO'] = df['AMT_CREDIT'] / df['AMT_ANNUITY']
df['NEW_CREDIT_TO_GOODS_RATIO'] = df['AMT_CREDIT'] / df['AMT_GOODS_PRICE']
df['NEW_INC_PER_CHLD'] = df['AMT_INCOME_TOTAL'] / (1 + df['CNT_CHILDREN'])
df['NEW_EMPLOY_TO_BIRTH_RATIO'] = df['DAYS_EMPLOYED'] / df['DAYS_BIRTH']
df['NEW_ANNUITY_TO_INCOME_RATIO'] = df['AMT_ANNUITY'] / (1 + df['AMT_INCOME_TOTAL'])
df['NEW_SOURCES_PROD'] = df['EXT_SOURCE_1'] * df['EXT_SOURCE_2'] * df['EXT_SOURCE_3']
df['NEW_EXT_SOURCES_MEAN'] = df[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].mean(axis=1)
df['NEW_SCORES_STD'] = df[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].std(axis=1)
df['NEW_SCORES_STD'] = df['NEW_SCORES_STD'].fillna(df['NEW_SCORES_STD'].mean())
df['NEW_CAR_TO_BIRTH_RATIO'] = df['OWN_CAR_AGE'] / df['DAYS_BIRTH']
df['NEW_CAR_TO_EMPLOY_RATIO'] = df['OWN_CAR_AGE'] / df['DAYS_EMPLOYED']
df['NEW_PHONE_TO_BIRTH_RATIO'] = df['DAYS_LAST_PHONE_CHANGE'] / df['DAYS_BIRTH']
df['NEW_PHONE_TO_EMPLOY_RATIO'] = df['DAYS_LAST_PHONE_CHANGE'] / df['DAYS_EMPLOYED']
df['NEW_CREDIT_TO_INCOME_RATIO'] = df['AMT_CREDIT'] / df['AMT_INCOME_TOTAL']
del docs, live, inc_by_org

as_cat_dtype = [
    "TARGET", 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
    'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS',
    'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START',
    'FLAG_OWN_CAR', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL' "REG_REGION_NOT_LIVE_REGION", "REG_REGION_NOT_WORK_REGION", "LIVE_REGION_NOT_WORK_REGION", "REG_CITY_NOT_LIVE_CITY", "REG_CITY_NOT_WORK_CITY", "LIVE_CITY_NOT_WORK_CITY", 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE',
    # Document flags
    'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6',
    'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11',
    'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16',
    'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21'

]
print("Loaded data shape:", df.shape)

Loaded data shape: (307507, 142)

In [3]:
# =========== `def bureau_and_balance` refactored ===========
bureau = pd.read_csv(dataset_mold.path / "data_files" / "bureau.csv")

# Bureau balance: Perform aggregations and merge with bureau.csv
bb = pd.read_csv(dataset_mold.path / "data_files" / "bureau_balance.csv")
bb_w_one_hot = pd.get_dummies(bb, columns=['STATUS'], dummy_na= True)
bb_one_hot_cat_cols = [c for c in bb_w_one_hot.columns if c not in bb.columns]
bb_aggregations = {'MONTHS_BALANCE': ['min', 'max', 'size']}
for col in bb_one_hot_cat_cols:
    bb_aggregations[col] = ['mean']
bb_agg = bb_w_one_hot.groupby('SK_ID_BUREAU').agg(bb_aggregations)
bb_agg.columns = pd.Index([e[0] + "_" + e[1].upper() for e in bb_agg.columns.tolist()])
bureau = bureau.join(bb_agg, how='left', on='SK_ID_BUREAU')
bureau.drop(['SK_ID_BUREAU'], axis=1, inplace= True)
del bb, bb_agg, bb_w_one_hot

# Bureau and bureau_balance numeric features
num_aggregations = {
    'DAYS_CREDIT': ['min', 'max', 'mean', 'var'],
    'DAYS_CREDIT_ENDDATE': ['min', 'max', 'mean'],
    'DAYS_CREDIT_UPDATE': ['mean'],
    'CREDIT_DAY_OVERDUE': ['max', 'mean'],
    'AMT_CREDIT_MAX_OVERDUE': ['mean'],
    'AMT_CREDIT_SUM': ['max', 'mean', 'sum'],
    'AMT_CREDIT_SUM_DEBT': ['max', 'mean', 'sum'],
    'AMT_CREDIT_SUM_OVERDUE': ['mean'],
    'AMT_CREDIT_SUM_LIMIT': ['mean', 'sum'],
    'AMT_ANNUITY': ['max', 'mean'],
    'CNT_CREDIT_PROLONG': ['sum'],
    'MONTHS_BALANCE_MIN': ['min'],
    'MONTHS_BALANCE_MAX': ['max'],
    'MONTHS_BALANCE_SIZE': ['mean', 'sum']
}
# Bureau and bureau_balance categorical features
cat_aggregations = {}
for cat in bb_one_hot_cat_cols:
    cat_aggregations[cat + "_MEAN"] = ['mean']

org_cols = list(bureau.columns)
bureau = pd.get_dummies(bureau, columns=['CREDIT_ACTIVE', 'CREDIT_CURRENCY', 'CREDIT_TYPE'], dummy_na=True)
bureau_one_hot_cat_cols = [c for c in bureau.columns if c not in org_cols]
for cat in bureau_one_hot_cat_cols:
    cat_aggregations[cat] = ['mean']
bureau_agg = bureau.groupby('SK_ID_CURR').agg({**num_aggregations, **cat_aggregations})
bureau_agg.columns = pd.Index(['BURO_' + e[0] + "_" + e[1].upper() for e in bureau_agg.columns.tolist()])

# Bureau: Active credits - using only numerical aggregations
active = bureau[bureau['CREDIT_ACTIVE_Active'] == 1]
active_agg = active.groupby('SK_ID_CURR').agg(num_aggregations)
cols = active_agg.columns.tolist()
active_agg.columns = pd.Index(['ACTIVE_' + e[0] + "_" + e[1].upper() for e in active_agg.columns.tolist()])
bureau_agg = bureau_agg.join(active_agg, how='left', on='SK_ID_CURR')

# Bureau: Closed credits - using only numerical aggregations
closed = bureau[bureau['CREDIT_ACTIVE_Closed'] == 1]
closed_agg = closed.groupby('SK_ID_CURR').agg(num_aggregations)
closed_agg.columns = pd.Index(['CLOSED_' + e[0] + "_" + e[1].upper() for e in closed_agg.columns.tolist()])
bureau_agg = bureau_agg.join(closed_agg, how='left', on='SK_ID_CURR')

for e in cols:
    bureau_agg['NEW_RATIO_BURO_' + e[0] + "_" + e[1].upper()] = bureau_agg['ACTIVE_' + e[0] + "_" + e[1].upper()] / bureau_agg['CLOSED_' + e[0] + "_" + e[1].upper()]
del active, active_agg, bureau

df = df.join(bureau_agg, how='left', on='SK_ID_CURR')
del bureau_agg

In [4]:
# =========== `def previous_applications` refactored ===========
prev = pd.read_csv(dataset_mold.path / "data_files" / "previous_application.csv")

# Cat encode for aggregations
org_cols = list(prev.columns)
prev = pd.get_dummies(prev, columns=list(prev.select_dtypes(include=['object']).columns), dummy_na=True)
prev_cat_cols = [c for c in prev.columns if c not in org_cols]

# Days 365.243 values -> nan
prev['DAYS_FIRST_DRAWING'] = prev['DAYS_FIRST_DRAWING'].replace(365243, np.nan)
prev['DAYS_FIRST_DUE'] = prev['DAYS_FIRST_DUE'].replace(365243, np.nan)
prev['DAYS_LAST_DUE_1ST_VERSION'] = prev['DAYS_LAST_DUE_1ST_VERSION'].replace(365243, np.nan)
prev['DAYS_LAST_DUE'] = prev['DAYS_LAST_DUE'].replace(365243, np.nan)
prev['DAYS_TERMINATION'] = prev['DAYS_TERMINATION'].replace(365243, np.nan)
# Add feature: value ask / value received percentage
prev['APP_CREDIT_PERC'] = prev['AMT_APPLICATION'] / prev['AMT_CREDIT']
# Previous applications numeric features
num_aggregations = {
    'AMT_ANNUITY': ['min', 'max', 'mean'],
    'AMT_APPLICATION': ['min', 'max', 'mean'],
    'AMT_CREDIT': ['min', 'max', 'mean'],
    'APP_CREDIT_PERC': ['min', 'max', 'mean', 'var'],
    'AMT_DOWN_PAYMENT': ['min', 'max', 'mean'],
    'AMT_GOODS_PRICE': ['min', 'max', 'mean'],
    'HOUR_APPR_PROCESS_START': ['min', 'max', 'mean'],
    'RATE_DOWN_PAYMENT': ['min', 'max', 'mean'],
    'DAYS_DECISION': ['min', 'max', 'mean'],
    'CNT_PAYMENT': ['mean', 'sum'],
}
# Previous applications categorical features
cat_aggregations = {}
for cat in prev_cat_cols:
    cat_aggregations[cat] = ['mean']

prev_agg = prev.groupby('SK_ID_CURR').agg({**num_aggregations, **cat_aggregations})
prev_agg.columns = pd.Index(['PREV_' + e[0] + "_" + e[1].upper() for e in prev_agg.columns.tolist()])
# Previous Applications: Approved Applications - only numerical features
approved = prev[prev['NAME_CONTRACT_STATUS_Approved'] == 1]
approved_agg = approved.groupby('SK_ID_CURR').agg(num_aggregations)
cols = approved_agg.columns.tolist()
approved_agg.columns = pd.Index(['APPROVED_' + e[0] + "_" + e[1].upper() for e in approved_agg.columns.tolist()])
prev_agg = prev_agg.join(approved_agg, how='left', on='SK_ID_CURR')
# Previous Applications: Refused Applications - only numerical features
refused = prev[prev['NAME_CONTRACT_STATUS_Refused'] == 1]
refused_agg = refused.groupby('SK_ID_CURR').agg(num_aggregations)
refused_agg.columns = pd.Index(['REFUSED_' + e[0] + "_" + e[1].upper() for e in refused_agg.columns.tolist()])
prev_agg = prev_agg.join(refused_agg, how='left', on='SK_ID_CURR')
del refused, refused_agg, approved, approved_agg, prev, prev_cat_cols

for e in cols:
    prev_agg['NEW_RATIO_PREV_' + e[0] + "_" + e[1].upper()] = prev_agg['APPROVED_' + e[0] + "_" + e[1].upper()] / prev_agg['REFUSED_' + e[0] + "_" + e[1].upper()]

df = df.join(prev_agg, how='left', on='SK_ID_CURR')
del prev_agg

In [5]:
# =========== `def pos_cash` refactored ===========
pos = pd.read_csv(dataset_mold.path / "data_files" / "POS_CASH_balance.csv")

# Cat encode for aggregations
org_cols = list(pos.columns)
pos = pd.get_dummies(pos, columns=list(pos.select_dtypes(include=['object']).columns), dummy_na=True)
pos_cat_cols = [c for c in pos.columns if c not in org_cols]

# Features
aggregations = {
    'MONTHS_BALANCE': ['max', 'mean', 'size'],
    'SK_DPD': ['max', 'mean'],
    'SK_DPD_DEF': ['max', 'mean']
}
for cat in pos_cat_cols:
    aggregations[cat] = ['mean']

pos_agg = pos.groupby('SK_ID_CURR').agg(aggregations)
pos_agg.columns = pd.Index(['POS_' + e[0] + "_" + e[1].upper() for e in pos_agg.columns.tolist()])
# Count pos cash accounts
pos_agg['POS_COUNT'] = pos.groupby('SK_ID_CURR').size()

df = df.join(pos_agg, how='left', on='SK_ID_CURR')
del pos, pos_agg, pos_cat_cols

In [6]:
# =========== `def installments_payments` refactored ===========
ins = pd.read_csv(dataset_mold.path / "data_files" / "installments_payments.csv")

# Cat encode for aggregations
org_cols = list(ins.columns)
ins = pd.get_dummies(ins, columns=list(ins.select_dtypes(include=['object']).columns), dummy_na=True)
ins_cat_cols = [c for c in ins.columns if c not in org_cols]

# Percentage and difference paid in each installment (amount paid and installment value)
ins['PAYMENT_PERC'] = ins['AMT_PAYMENT'] / ins['AMT_INSTALMENT']
ins['PAYMENT_DIFF'] = ins['AMT_INSTALMENT'] - ins['AMT_PAYMENT']
# Days past due and days before due (no negative values)
ins['DPD'] = ins['DAYS_ENTRY_PAYMENT'] - ins['DAYS_INSTALMENT']
ins['DBD'] = ins['DAYS_INSTALMENT'] - ins['DAYS_ENTRY_PAYMENT']
ins['DPD'] = ins['DPD'].apply(lambda x: x if x > 0 else 0)
ins['DBD'] = ins['DBD'].apply(lambda x: x if x > 0 else 0)
# Features: Perform aggregations
aggregations = {
    'NUM_INSTALMENT_VERSION': ['nunique'],
    'DPD': ['max', 'mean', 'sum'],
    'DBD': ['max', 'mean', 'sum'],
    'PAYMENT_PERC': ['max', 'mean', 'sum', 'var'],
    'PAYMENT_DIFF': ['max', 'mean', 'sum', 'var'],
    'AMT_INSTALMENT': ['max', 'mean', 'sum'],
    'AMT_PAYMENT': ['min', 'max', 'mean', 'sum'],
    'DAYS_ENTRY_PAYMENT': ['max', 'mean', 'sum']
}
for cat in ins_cat_cols:
    aggregations[cat] = ['mean']
ins_agg = ins.groupby('SK_ID_CURR').agg(aggregations)
ins_agg.columns = pd.Index(['INSTAL_' + e[0] + "_" + e[1].upper() for e in ins_agg.columns.tolist()])
# Count installments accounts
ins_agg['INSTAL_COUNT'] = ins.groupby('SK_ID_CURR').size()

df = df.join(ins_agg, how='left', on='SK_ID_CURR')
del ins, ins_agg, ins_cat_cols

In [7]:
# =========== `def credit_card_balance` refactored ===========
cc = pd.read_csv(dataset_mold.path / "data_files" / "credit_card_balance.csv")

# Cat encode for aggregations
org_cols = list(cc.columns)
cc = pd.get_dummies(cc, columns=list(cc.select_dtypes(include=['object']).columns), dummy_na=True)
cc_cat_cols = [c for c in cc.columns if c not in org_cols]

# General aggregations
cc.drop(['SK_ID_PREV'], axis= 1, inplace = True)
cc_agg = cc.groupby('SK_ID_CURR').agg(['min', 'max', 'mean', 'sum', 'var'])
cc_agg.columns = pd.Index(['CC_' + e[0] + "_" + e[1].upper() for e in cc_agg.columns.tolist()])
# Count credit card lines
cc_agg['CC_COUNT'] = cc.groupby('SK_ID_CURR').size()

df = df.join(cc_agg, how='left', on='SK_ID_CURR')
del cc, cc_agg, cc_cat_cols

In [8]:
# =========== Feature selection ===========
features_with_no_imp_at_least_twice = [
    'ACTIVE_CNT_CREDIT_PROLONG_SUM', 'ACTIVE_CREDIT_DAY_OVERDUE_MEAN', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_HOUR',
    'AMT_REQ_CREDIT_BUREAU_WEEK', 'BURO_CNT_CREDIT_PROLONG_SUM', 'BURO_CREDIT_ACTIVE_Bad debt_MEAN', 'BURO_CREDIT_ACTIVE_nan_MEAN',
    'BURO_CREDIT_CURRENCY_currency 1_MEAN', 'BURO_CREDIT_CURRENCY_currency 2_MEAN', 'BURO_CREDIT_CURRENCY_currency 3_MEAN',
    'BURO_CREDIT_CURRENCY_currency 4_MEAN', 'BURO_CREDIT_CURRENCY_nan_MEAN', 'BURO_CREDIT_DAY_OVERDUE_MAX', 'BURO_CREDIT_DAY_OVERDUE_MEAN',
    'BURO_CREDIT_TYPE_Cash loan (non-earmarked)_MEAN', 'BURO_CREDIT_TYPE_Interbank credit_MEAN', 'BURO_CREDIT_TYPE_Loan for business development_MEAN',
    'BURO_CREDIT_TYPE_Loan for purchase of shares (margin lending)_MEAN', 'BURO_CREDIT_TYPE_Loan for the purchase of equipment_MEAN',
    'BURO_CREDIT_TYPE_Loan for working capital replenishment_MEAN', 'BURO_CREDIT_TYPE_Mobile operator loan_MEAN',
    'BURO_CREDIT_TYPE_Real estate loan_MEAN', 'BURO_CREDIT_TYPE_Unknown type of loan_MEAN', 'BURO_CREDIT_TYPE_nan_MEAN',
    'BURO_MONTHS_BALANCE_MAX_MAX', 'BURO_STATUS_2_MEAN_MEAN', 'BURO_STATUS_3_MEAN_MEAN', 'BURO_STATUS_4_MEAN_MEAN', 'BURO_STATUS_5_MEAN_MEAN',
    'BURO_STATUS_nan_MEAN_MEAN', 'CC_AMT_DRAWINGS_ATM_CURRENT_MIN', 'CC_AMT_DRAWINGS_CURRENT_MIN', 'CC_AMT_DRAWINGS_OTHER_CURRENT_MAX',
    'CC_AMT_DRAWINGS_OTHER_CURRENT_MEAN', 'CC_AMT_DRAWINGS_OTHER_CURRENT_MIN', 'CC_AMT_DRAWINGS_OTHER_CURRENT_SUM',
    'CC_AMT_DRAWINGS_OTHER_CURRENT_VAR', 'CC_AMT_INST_MIN_REGULARITY_MIN', 'CC_AMT_PAYMENT_TOTAL_CURRENT_MIN', 'CC_AMT_PAYMENT_TOTAL_CURRENT_VAR',
    'CC_AMT_RECIVABLE_SUM', 'CC_AMT_TOTAL_RECEIVABLE_MAX', 'CC_AMT_TOTAL_RECEIVABLE_MIN', 'CC_AMT_TOTAL_RECEIVABLE_SUM', 'CC_AMT_TOTAL_RECEIVABLE_VAR',
    'CC_CNT_DRAWINGS_ATM_CURRENT_MIN', 'CC_CNT_DRAWINGS_CURRENT_MIN', 'CC_CNT_DRAWINGS_OTHER_CURRENT_MAX', 'CC_CNT_DRAWINGS_OTHER_CURRENT_MEAN',
    'CC_CNT_DRAWINGS_OTHER_CURRENT_MIN', 'CC_CNT_DRAWINGS_OTHER_CURRENT_SUM', 'CC_CNT_DRAWINGS_OTHER_CURRENT_VAR', 'CC_CNT_DRAWINGS_POS_CURRENT_SUM',
    'CC_CNT_INSTALMENT_MATURE_CUM_MAX', 'CC_CNT_INSTALMENT_MATURE_CUM_MIN', 'CC_COUNT', 'CC_MONTHS_BALANCE_MAX', 'CC_MONTHS_BALANCE_MEAN',
    'CC_MONTHS_BALANCE_MIN', 'CC_MONTHS_BALANCE_SUM', 'CC_NAME_CONTRACT_STATUS_Active_MAX', 'CC_NAME_CONTRACT_STATUS_Active_MIN',
    'CC_NAME_CONTRACT_STATUS_Approved_MAX', 'CC_NAME_CONTRACT_STATUS_Approved_MEAN', 'CC_NAME_CONTRACT_STATUS_Approved_MIN',
    'CC_NAME_CONTRACT_STATUS_Approved_SUM', 'CC_NAME_CONTRACT_STATUS_Approved_VAR', 'CC_NAME_CONTRACT_STATUS_Completed_MAX',
    'CC_NAME_CONTRACT_STATUS_Completed_MEAN', 'CC_NAME_CONTRACT_STATUS_Completed_MIN', 'CC_NAME_CONTRACT_STATUS_Completed_SUM', 'CC_NAME_CONTRACT_STATUS_Completed_VAR',
    'CC_NAME_CONTRACT_STATUS_Demand_MAX', 'CC_NAME_CONTRACT_STATUS_Demand_MEAN', 'CC_NAME_CONTRACT_STATUS_Demand_MIN', 'CC_NAME_CONTRACT_STATUS_Demand_SUM',
    'CC_NAME_CONTRACT_STATUS_Demand_VAR', 'CC_NAME_CONTRACT_STATUS_Refused_MAX', 'CC_NAME_CONTRACT_STATUS_Refused_MEAN', 'CC_NAME_CONTRACT_STATUS_Refused_MIN',
    'CC_NAME_CONTRACT_STATUS_Refused_SUM', 'CC_NAME_CONTRACT_STATUS_Refused_VAR', 'CC_NAME_CONTRACT_STATUS_Sent proposal_MAX',
    'CC_NAME_CONTRACT_STATUS_Sent proposal_MEAN', 'CC_NAME_CONTRACT_STATUS_Sent proposal_MIN', 'CC_NAME_CONTRACT_STATUS_Sent proposal_SUM',
    'CC_NAME_CONTRACT_STATUS_Sent proposal_VAR', 'CC_NAME_CONTRACT_STATUS_Signed_MAX', 'CC_NAME_CONTRACT_STATUS_Signed_MEAN', 'CC_NAME_CONTRACT_STATUS_Signed_MIN',
    'CC_NAME_CONTRACT_STATUS_Signed_SUM', 'CC_NAME_CONTRACT_STATUS_Signed_VAR', 'CC_NAME_CONTRACT_STATUS_nan_MAX', 'CC_NAME_CONTRACT_STATUS_nan_MEAN',
    'CC_NAME_CONTRACT_STATUS_nan_MIN', 'CC_NAME_CONTRACT_STATUS_nan_SUM', 'CC_NAME_CONTRACT_STATUS_nan_VAR', 'CC_SK_DPD_DEF_MAX',
    'CC_SK_DPD_DEF_MIN', 'CC_SK_DPD_DEF_SUM', 'CC_SK_DPD_DEF_VAR', 'CC_SK_DPD_MAX', 'CC_SK_DPD_MEAN', 'CC_SK_DPD_MIN', 'CC_SK_DPD_SUM',
    'CC_SK_DPD_VAR', 'CLOSED_AMT_CREDIT_SUM_LIMIT_MEAN', 'CLOSED_AMT_CREDIT_SUM_LIMIT_SUM', 'CLOSED_AMT_CREDIT_SUM_OVERDUE_MEAN',
    'CLOSED_CNT_CREDIT_PROLONG_SUM', 'CLOSED_CREDIT_DAY_OVERDUE_MAX', 'CLOSED_CREDIT_DAY_OVERDUE_MEAN', 'CLOSED_MONTHS_BALANCE_MAX_MAX',
    'CNT_CHILDREN', 'ELEVATORS_MEDI', 'ELEVATORS_MODE', 'EMERGENCYSTATE_MODE_No', 'EMERGENCYSTATE_MODE_Yes', 'ENTRANCES_MODE', 'FLAG_CONT_MOBILE',
    'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16',
    'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5',
    'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_9', 'FLAG_EMAIL', 'FLAG_EMP_PHONE', 'FLAG_MOBIL', 'FLAG_OWN_CAR', 'FLOORSMAX_MODE',
    'FONDKAPREMONT_MODE_not specified', 'FONDKAPREMONT_MODE_org spec account', 'FONDKAPREMONT_MODE_reg oper account', 'FONDKAPREMONT_MODE_reg oper spec account',
    'HOUSETYPE_MODE_block of flats', 'HOUSETYPE_MODE_specific housing', 'HOUSETYPE_MODE_terraced house', 'LIVE_REGION_NOT_WORK_REGION',
    'NAME_CONTRACT_TYPE_Revolving loans', 'NAME_EDUCATION_TYPE_Academic degree', 'NAME_FAMILY_STATUS_Civil marriage', 'NAME_FAMILY_STATUS_Single / not married',
    'NAME_FAMILY_STATUS_Unknown', 'NAME_FAMILY_STATUS_Widow', 'NAME_HOUSING_TYPE_Co-op apartment', 'NAME_HOUSING_TYPE_With parents',
    'NAME_INCOME_TYPE_Businessman', 'NAME_INCOME_TYPE_Maternity leave', 'NAME_INCOME_TYPE_Pensioner', 'NAME_INCOME_TYPE_Student',
    'NAME_INCOME_TYPE_Unemployed', 'NAME_TYPE_SUITE_Children', 'NAME_TYPE_SUITE_Family', 'NAME_TYPE_SUITE_Group of people',
    'NAME_TYPE_SUITE_Other_A', 'NAME_TYPE_SUITE_Other_B', 'NAME_TYPE_SUITE_Spouse, partner', 'NAME_TYPE_SUITE_Unaccompanied',
    'NEW_RATIO_BURO_AMT_CREDIT_SUM_DEBT_MEAN', 'NEW_RATIO_BURO_AMT_CREDIT_SUM_LIMIT_SUM', 'NEW_RATIO_BURO_AMT_CREDIT_SUM_OVERDUE_MEAN',
    'NEW_RATIO_BURO_CNT_CREDIT_PROLONG_SUM', 'NEW_RATIO_BURO_CREDIT_DAY_OVERDUE_MAX', 'NEW_RATIO_BURO_CREDIT_DAY_OVERDUE_MEAN', 'NEW_RATIO_BURO_MONTHS_BALANCE_MAX_MAX',
    'NEW_RATIO_PREV_AMT_DOWN_PAYMENT_MIN', 'NEW_RATIO_PREV_RATE_DOWN_PAYMENT_MAX', 'OCCUPATION_TYPE_Cleaning staff', 'OCCUPATION_TYPE_Cooking staff',
    'OCCUPATION_TYPE_HR staff', 'OCCUPATION_TYPE_IT staff', 'OCCUPATION_TYPE_Low-skill Laborers', 'OCCUPATION_TYPE_Managers',
    'OCCUPATION_TYPE_Private service staff', 'OCCUPATION_TYPE_Realty agents', 'OCCUPATION_TYPE_Sales staff', 'OCCUPATION_TYPE_Secretaries',
    'OCCUPATION_TYPE_Security staff', 'OCCUPATION_TYPE_Waiters/barmen staff', 'ORGANIZATION_TYPE_Advertising', 'ORGANIZATION_TYPE_Agriculture',
    'ORGANIZATION_TYPE_Business Entity Type 1', 'ORGANIZATION_TYPE_Business Entity Type 2', 'ORGANIZATION_TYPE_Cleaning', 'ORGANIZATION_TYPE_Culture',
    'ORGANIZATION_TYPE_Electricity', 'ORGANIZATION_TYPE_Emergency', 'ORGANIZATION_TYPE_Government', 'ORGANIZATION_TYPE_Hotel', 'ORGANIZATION_TYPE_Housing',
    'ORGANIZATION_TYPE_Industry: type 1', 'ORGANIZATION_TYPE_Industry: type 10', 'ORGANIZATION_TYPE_Industry: type 11', 'ORGANIZATION_TYPE_Industry: type 12',
    'ORGANIZATION_TYPE_Industry: type 13', 'ORGANIZATION_TYPE_Industry: type 2', 'ORGANIZATION_TYPE_Industry: type 3', 'ORGANIZATION_TYPE_Industry: type 4',
    'ORGANIZATION_TYPE_Industry: type 5', 'ORGANIZATION_TYPE_Industry: type 6', 'ORGANIZATION_TYPE_Industry: type 7', 'ORGANIZATION_TYPE_Industry: type 8',
    'ORGANIZATION_TYPE_Insurance', 'ORGANIZATION_TYPE_Legal Services', 'ORGANIZATION_TYPE_Mobile', 'ORGANIZATION_TYPE_Other', 'ORGANIZATION_TYPE_Postal',
    'ORGANIZATION_TYPE_Realtor', 'ORGANIZATION_TYPE_Religion', 'ORGANIZATION_TYPE_Restaurant', 'ORGANIZATION_TYPE_Security',
    'ORGANIZATION_TYPE_Security Ministries', 'ORGANIZATION_TYPE_Services', 'ORGANIZATION_TYPE_Telecom', 'ORGANIZATION_TYPE_Trade: type 1',
    'ORGANIZATION_TYPE_Trade: type 2', 'ORGANIZATION_TYPE_Trade: type 3', 'ORGANIZATION_TYPE_Trade: type 4', 'ORGANIZATION_TYPE_Trade: type 5',
    'ORGANIZATION_TYPE_Trade: type 6', 'ORGANIZATION_TYPE_Trade: type 7',
    'ORGANIZATION_TYPE_Transport: type 1', 'ORGANIZATION_TYPE_Transport: type 2', 'ORGANIZATION_TYPE_Transport: type 4', 'ORGANIZATION_TYPE_University',
    'ORGANIZATION_TYPE_XNA', 'POS_NAME_CONTRACT_STATUS_Amortized debt_MEAN', 'POS_NAME_CONTRACT_STATUS_Approved_MEAN', 'POS_NAME_CONTRACT_STATUS_Canceled_MEAN',
    'POS_NAME_CONTRACT_STATUS_Demand_MEAN', 'POS_NAME_CONTRACT_STATUS_XNA_MEAN', 'POS_NAME_CONTRACT_STATUS_nan_MEAN', 'PREV_CHANNEL_TYPE_Car dealer_MEAN',
    'PREV_CHANNEL_TYPE_nan_MEAN', 'PREV_CODE_REJECT_REASON_CLIENT_MEAN', 'PREV_CODE_REJECT_REASON_SYSTEM_MEAN', 'PREV_CODE_REJECT_REASON_VERIF_MEAN',
    'PREV_CODE_REJECT_REASON_XNA_MEAN', 'PREV_CODE_REJECT_REASON_nan_MEAN', 'PREV_FLAG_LAST_APPL_PER_CONTRACT_N_MEAN', 'PREV_FLAG_LAST_APPL_PER_CONTRACT_Y_MEAN',
    'PREV_FLAG_LAST_APPL_PER_CONTRACT_nan_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_Building a house or an annex_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_Business development_MEAN',
    'PREV_NAME_CASH_LOAN_PURPOSE_Buying a garage_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a holiday home / land_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a home_MEAN',
    'PREV_NAME_CASH_LOAN_PURPOSE_Buying a new car_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a used car_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_Education_MEAN',
    'PREV_NAME_CASH_LOAN_PURPOSE_Everyday expenses_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_Furniture_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_Gasification / water supply_MEAN',
    'PREV_NAME_CASH_LOAN_PURPOSE_Hobby_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_Journey_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_Money for a third person_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_Other_MEAN',
    'PREV_NAME_CASH_LOAN_PURPOSE_Payments on other loans_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_Purchase of electronic equipment_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_Refusal to name the goal_MEAN',
    'PREV_NAME_CASH_LOAN_PURPOSE_Wedding / gift / holiday_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_XAP_MEAN', 'PREV_NAME_CASH_LOAN_PURPOSE_nan_MEAN', 'PREV_NAME_CLIENT_TYPE_XNA_MEAN',
    'PREV_NAME_CLIENT_TYPE_nan_MEAN', 'PREV_NAME_CONTRACT_STATUS_Unused offer_MEAN', 'PREV_NAME_CONTRACT_STATUS_nan_MEAN', 'PREV_NAME_CONTRACT_TYPE_XNA_MEAN',
    'PREV_NAME_CONTRACT_TYPE_nan_MEAN', 'PREV_NAME_GOODS_CATEGORY_Additional Service_MEAN', 'PREV_NAME_GOODS_CATEGORY_Animals_MEAN',
    'PREV_NAME_GOODS_CATEGORY_Auto Accessories_MEAN', 'PREV_NAME_GOODS_CATEGORY_Clothing and Accessories_MEAN', 'PREV_NAME_GOODS_CATEGORY_Construction Materials_MEAN',
    'PREV_NAME_GOODS_CATEGORY_Direct Sales_MEAN', 'PREV_NAME_GOODS_CATEGORY_Education_MEAN', 'PREV_NAME_GOODS_CATEGORY_Fitness_MEAN',
    'PREV_NAME_GOODS_CATEGORY_Gardening_MEAN', 'PREV_NAME_GOODS_CATEGORY_Homewares_MEAN', 'PREV_NAME_GOODS_CATEGORY_House Construction_MEAN',
    'PREV_NAME_GOODS_CATEGORY_Insurance_MEAN', 'PREV_NAME_GOODS_CATEGORY_Jewelry_MEAN', 'PREV_NAME_GOODS_CATEGORY_Medical Supplies_MEAN',
    'PREV_NAME_GOODS_CATEGORY_Medicine_MEAN', 'PREV_NAME_GOODS_CATEGORY_Office Appliances_MEAN', 'PREV_NAME_GOODS_CATEGORY_Other_MEAN', 'PREV_NAME_GOODS_CATEGORY_Tourism_MEAN',
    'PREV_NAME_GOODS_CATEGORY_Vehicles_MEAN', 'PREV_NAME_GOODS_CATEGORY_Weapon_MEAN', 'PREV_NAME_GOODS_CATEGORY_XNA_MEAN', 'PREV_NAME_GOODS_CATEGORY_nan_MEAN',
    'PREV_NAME_PAYMENT_TYPE_Cashless from the account of the employer_MEAN', 'PREV_NAME_PAYMENT_TYPE_Non-cash from your account_MEAN', 'PREV_NAME_PAYMENT_TYPE_nan_MEAN',
    'PREV_NAME_PORTFOLIO_Cars_MEAN', 'PREV_NAME_PORTFOLIO_nan_MEAN', 'PREV_NAME_PRODUCT_TYPE_nan_MEAN', 'PREV_NAME_SELLER_INDUSTRY_Construction_MEAN',
    'PREV_NAME_SELLER_INDUSTRY_Furniture_MEAN', 'PREV_NAME_SELLER_INDUSTRY_Industry_MEAN', 'PREV_NAME_SELLER_INDUSTRY_Jewelry_MEAN', 'PREV_NAME_SELLER_INDUSTRY_MLM partners_MEAN',
    'PREV_NAME_SELLER_INDUSTRY_Tourism_MEAN', 'PREV_NAME_SELLER_INDUSTRY_nan_MEAN', 'PREV_NAME_TYPE_SUITE_Group of people_MEAN', 'PREV_NAME_YIELD_GROUP_nan_MEAN',
    'PREV_PRODUCT_COMBINATION_POS industry without interest_MEAN', 'PREV_PRODUCT_COMBINATION_POS mobile without interest_MEAN', 'PREV_PRODUCT_COMBINATION_POS others without interest_MEAN',
    'PREV_PRODUCT_COMBINATION_nan_MEAN', 'PREV_WEEKDAY_APPR_PROCESS_START_nan_MEAN', 'REFUSED_AMT_DOWN_PAYMENT_MAX', 'REFUSED_AMT_DOWN_PAYMENT_MEAN',
    'REFUSED_RATE_DOWN_PAYMENT_MIN', 'REG_CITY_NOT_WORK_CITY', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION',
    'WALLSMATERIAL_MODE_Block', 'WALLSMATERIAL_MODE_Mixed', 'WALLSMATERIAL_MODE_Monolithic', 'WALLSMATERIAL_MODE_Others', 'WALLSMATERIAL_MODE_Panel',
    'WALLSMATERIAL_MODE_Wooden', 'WEEKDAY_APPR_PROCESS_START_FRIDAY', 'WEEKDAY_APPR_PROCESS_START_THURSDAY', 'WEEKDAY_APPR_PROCESS_START_TUESDAY'
]

# Filter to cols in our data w/o one hot of categories
features_with_no_imp_at_least_twice = [f for f in features_with_no_imp_at_least_twice if f in df.columns]
df = df.drop(columns=features_with_no_imp_at_least_twice)
as_cat_dtype = [f for f in as_cat_dtype if f in df.columns]
df[as_cat_dtype] = df[as_cat_dtype].astype('category')
df = df.drop(columns=['SK_ID_CURR'])
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [9]:
# Extra Preprocessing and cleaning from us
df = df.drop(columns=["POS_COUNT"]) # Drop duplicated feature

features_win_inf = ['PREV_APP_CREDIT_PERC_MAX', 'PREV_APP_CREDIT_PERC_MEAN', 'REFUSED_APP_CREDIT_PERC_MAX', 'REFUSED_APP_CREDIT_PERC_MEAN', 'NEW_RATIO_PREV_AMT_ANNUITY_MIN', 'NEW_RATIO_PREV_AMT_ANNUITY_MAX', 'NEW_RATIO_PREV_AMT_ANNUITY_MEAN', 'NEW_RATIO_PREV_AMT_APPLICATION_MIN', 'NEW_RATIO_PREV_AMT_APPLICATION_MAX', 'NEW_RATIO_PREV_AMT_APPLICATION_MEAN', 'NEW_RATIO_PREV_AMT_CREDIT_MIN', 'NEW_RATIO_PREV_AMT_CREDIT_MAX', 'NEW_RATIO_PREV_AMT_CREDIT_MEAN', 'NEW_RATIO_PREV_APP_CREDIT_PERC_MIN', 'NEW_RATIO_PREV_APP_CREDIT_PERC_MAX', 'NEW_RATIO_PREV_APP_CREDIT_PERC_MEAN', 'NEW_RATIO_PREV_APP_CREDIT_PERC_VAR', 'NEW_RATIO_PREV_AMT_DOWN_PAYMENT_MAX', 'NEW_RATIO_PREV_AMT_DOWN_PAYMENT_MEAN', 'NEW_RATIO_PREV_AMT_GOODS_PRICE_MIN', 'NEW_RATIO_PREV_AMT_GOODS_PRICE_MAX', 'NEW_RATIO_PREV_AMT_GOODS_PRICE_MEAN', 'NEW_RATIO_PREV_HOUR_APPR_PROCESS_START_MIN', 'NEW_RATIO_PREV_HOUR_APPR_PROCESS_START_MAX', 'NEW_RATIO_PREV_HOUR_APPR_PROCESS_START_MEAN', 'NEW_RATIO_PREV_RATE_DOWN_PAYMENT_MIN', 'NEW_RATIO_PREV_RATE_DOWN_PAYMENT_MEAN', 'NEW_RATIO_PREV_CNT_PAYMENT_MEAN', 'NEW_RATIO_PREV_CNT_PAYMENT_SUM', 'INSTAL_PAYMENT_PERC_MAX', 'INSTAL_PAYMENT_PERC_MEAN', 'INSTAL_PAYMENT_PERC_SUM', 'NEW_RATIO_BURO_DAYS_CREDIT_VAR', 'NEW_RATIO_BURO_DAYS_CREDIT_ENDDATE_MIN', 'NEW_RATIO_BURO_DAYS_CREDIT_ENDDATE_MAX', 'NEW_RATIO_BURO_DAYS_CREDIT_ENDDATE_MEAN', 'NEW_RATIO_BURO_DAYS_CREDIT_UPDATE_MEAN', 'NEW_RATIO_BURO_AMT_CREDIT_MAX_OVERDUE_MEAN', 'NEW_RATIO_BURO_AMT_CREDIT_SUM_MAX', 'NEW_RATIO_BURO_AMT_CREDIT_SUM_MEAN', 'NEW_RATIO_BURO_AMT_CREDIT_SUM_SUM', 'NEW_RATIO_BURO_AMT_CREDIT_SUM_DEBT_MAX', 'NEW_RATIO_BURO_AMT_CREDIT_SUM_DEBT_SUM', 'NEW_RATIO_BURO_AMT_CREDIT_SUM_LIMIT_MEAN', 'NEW_RATIO_BURO_AMT_ANNUITY_MAX', 'NEW_RATIO_BURO_AMT_ANNUITY_MEAN', 'NEW_RATIO_BURO_MONTHS_BALANCE_MIN_MIN', 'NEW_RATIO_BURO_MONTHS_BALANCE_SIZE_SUM',
 'NEW_RATIO_BURO_DAYS_CREDIT_MAX', 'NEW_PHONE_TO_EMPLOY_RATIO']
for c in features_win_inf:
    df[c] = df[c].replace([np.inf, -np.inf], np.nan)

## Data Checks

In [10]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
    duplicate_column_check=False, # Data has no duplicated columns (we checked before)
)

#### Dataset Overview
Rows: 307,507
Columns: 505
Use sampling: False (sample size: 307,507)

Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['NEW_EXT_SOURCES_MEAN', 'INSTAL_AMT_PAYMENT_MEAN', 'INSTAL_AMT_INSTALMENT_MEAN', 'INSTAL_AMT_INSTALMENT_SUM', 'INSTAL_AMT_PAYMENT_SUM', 'NEW_SCORES_STD', 'PREV_AMT_ANNUITY_MEAN', 'NEW_PHONE_TO_BIRTH_RATIO', 'APPROVED_AMT_ANNUITY_MEAN', 'NEW_EMPLOY_TO_BIRTH_RATIO']
Rows remaining as candidates after top-10 filter: 0 (of 307,507)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)

Data quality checks completed.

In [11]:
# Sample Rows
df_head

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_REALTY,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_WORK_PHONE,FLAG_PHONE,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_CITY_NOT_LIVE_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_3,FLAG_DOCUMENT_8,FLAG_DOCUMENT_18,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,NEW_DOC_IND_AVG,NEW_DOC_IND_STD,NEW_DOC_IND_KURT,NEW_LIVE_IND_SUM,NEW_LIVE_IND_STD,NEW_LIVE_IND_KURT,NEW_INC_BY_ORG,NEW_CREDIT_TO_ANNUITY_RATIO,NEW_CREDIT_TO_GOODS_RATIO,NEW_INC_PER_CHLD,NEW_EMPLOY_TO_BIRTH_RATIO,NEW_ANNUITY_TO_INCOME_RATIO,NEW_SOURCES_PROD,NEW_EXT_SOURCES_MEAN,NEW_SCORES_STD,NEW_CAR_TO_BIRTH_RATIO,NEW_CAR_TO_EMPLOY_RATIO,NEW_PHONE_TO_BIRTH_RATIO,NEW_PHONE_TO_EMPLOY_RATIO,NEW_CREDIT_TO_INCOME_RATIO,BURO_DAYS_CREDIT_MIN,BURO_DAYS_CREDIT_MAX,BURO_DAYS_CREDIT_MEAN,BURO_DAYS_CREDIT_VAR,BURO_DAYS_CREDIT_ENDDATE_MIN,BURO_DAYS_CREDIT_ENDDATE_MAX,BURO_DAYS_CREDIT_ENDDATE_MEAN,BURO_DAYS_CREDIT_UPDATE_MEAN,BURO_AMT_CREDIT_MAX_OVERDUE_MEAN,BURO_AMT_CREDIT_SUM_MAX,BURO_AMT_CREDIT_SUM_MEAN,BURO_AMT_CREDIT_SUM_SUM,BURO_AMT_CREDIT_SUM_DEBT_MAX,BURO_AMT_CREDIT_SUM_DEBT_MEAN,BURO_AMT_CREDIT_SUM_DEBT_SUM,BURO_AMT_CREDIT_SUM_OVERDUE_MEAN,BURO_AMT_CREDIT_SUM_LIMIT_MEAN,BURO_AMT_CREDIT_SUM_LIMIT_SUM,BURO_AMT_ANNUITY_MAX,BURO_AMT_ANNUITY_MEAN,BURO_MONTHS_BALANCE_MIN_MIN,BURO_MONTHS_BALANCE_SIZE_MEAN,BURO_MONTHS_BALANCE_SIZE_SUM,BURO_STATUS_0_MEAN_MEAN,BURO_STATUS_1_MEAN_MEAN,BURO_STATUS_C_MEAN_MEAN,BURO_STATUS_X_MEAN_MEAN,BURO_CREDIT_ACTIVE_Active_MEAN,BURO_CREDIT_ACTIVE_Closed_MEAN,BURO_CREDIT_ACTIVE_Sold_MEAN,BURO_CREDIT_TYPE_Another type of loan_MEAN,BURO_CREDIT_TYPE_Car loan_MEAN,BURO_CREDIT_TYPE_Consumer credit_MEAN,BURO_CREDIT_TYPE_Credit card_MEAN,BURO_CREDIT_TYPE_Microloan_MEAN,BURO_CREDIT_TYPE_Mortgage_MEAN,ACTIVE_DAYS_CREDIT_MIN,ACTIVE_DAYS_CREDIT_MAX,ACTIVE_DAYS_CREDIT_MEAN,ACTIVE_DAYS_CREDIT_VAR,ACTIVE_DAYS_CREDIT_ENDDATE_MIN,ACTIVE_DAYS_CREDIT_ENDDATE_MAX,ACTIVE_DAYS_CREDIT_ENDDATE_MEAN,ACTIVE_DAYS_CREDIT_UPDATE_MEAN,ACTIVE_CREDIT_DAY_OVERDUE_MAX,ACTIVE_AMT_CREDIT_MAX_OVERDUE_MEAN,ACTIVE_AMT_CREDIT_SUM_MAX,ACTIVE_AMT_CREDIT_SUM_MEAN,ACTIVE_AMT_CREDIT_SUM_SUM,ACTIVE_AMT_CREDIT_SUM_DEBT_MAX,ACTIVE_AMT_CREDIT_SUM_DEBT_MEAN,ACTIVE_AMT_CREDIT_SUM_DEBT_SUM,ACTIVE_AMT_CREDIT_SUM_OVERDUE_MEAN,ACTIVE_AMT_CREDIT_SUM_LIMIT_MEAN,ACTIVE_AMT_CREDIT_SUM_LIMIT_SUM,ACTIVE_AMT_ANNUITY_MAX,ACTIVE_AMT_ANNUITY_MEAN,ACTIVE_MONTHS_BALANCE_MIN_MIN,ACTIVE_MONTHS_BALANCE_MAX_MAX,ACTIVE_MONTHS_BALANCE_SIZE_MEAN,ACTIVE_MONTHS_BALANCE_SIZE_SUM,CLOSED_DAYS_CREDIT_MIN,CLOSED_DAYS_CREDIT_MAX,CLOSED_DAYS_CREDIT_MEAN,CLOSED_DAYS_CREDIT_VAR,CLOSED_DAYS_CREDIT_ENDDATE_MIN,CLOSED_DAYS_CREDIT_ENDDATE_MAX,CLOSED_DAYS_CREDIT_ENDDATE_MEAN,CLOSED_DAYS_CREDIT_UPDATE_MEAN,CLOSED_AMT_CREDIT_MAX_OVERDUE_MEAN,CLOSED_AMT_CREDIT_SUM_MAX,CLOSED_AMT_CREDIT_SUM_MEAN,CLOSED_AMT_CREDIT_SUM_SUM,CLOSED_AMT_CREDIT_SUM_DEBT_MAX,CLOSED_AMT_CREDIT_SUM_DEBT_MEAN,CLOSED_AMT_CREDIT_SUM_DEBT_SUM,CLOSED_AMT_ANNUITY_MAX,CLOSED_AMT_ANNUITY_MEAN,CLOSED_MONTHS_BALANCE_MIN_MIN,CLOSED_MONTHS_BALANCE_SIZE_MEAN,CLOSED_MONTHS_BALANCE_SIZE_SUM,NEW_RATIO_BURO_DAYS_CREDIT_MIN,NEW_RATIO_BURO_DAYS_CREDIT_MAX,NEW_RATIO_BURO_DAYS_CREDIT_MEAN,NEW_RATIO_BURO_DAYS_CREDIT_VAR,NEW_RATIO_BURO_DAYS_CREDIT_ENDDATE_MIN,NEW_RATIO_BURO_DAYS_CREDIT_ENDDATE_MAX,NEW_RATIO_BURO_DAYS_CREDIT_ENDDATE_MEAN,NEW_RATIO_BURO_DAYS_CREDIT_UPDATE_MEAN,NEW_RATIO_BURO_AMT_CREDIT_MAX_OVERDUE_MEAN,NEW_RATIO_BURO_AMT_CREDIT_SUM_MAX,NEW_RATIO_BURO_AMT_CREDIT_SUM_MEAN,NEW_RATIO_BURO_AMT_CREDIT_SUM_SUM,NEW_RATIO_BURO_AMT_CREDIT_SUM_DEBT_MAX,NEW_RATIO_BURO_AMT_CREDIT_SUM_DEBT_SUM,NEW_RATIO_BURO_AMT_CREDIT_SUM_LIMIT_MEAN,NEW_RATIO_BURO_AMT_ANNUITY_MAX,NEW_RATIO_BURO_AMT_ANNUITY_MEAN,NEW_RATIO_BURO_MONTHS_BALANCE_MIN_MIN,NEW_RATIO_BURO_MONTHS_BALANCE_SIZE_MEAN,NEW_RATIO_BURO_MONTHS_BALANCE_SIZE_SUM,PREV_AMT_ANNUITY_MIN,PREV_AMT_ANNUITY_MAX,PREV_AMT_ANNUITY_MEAN,PREV_AMT_APPLICATION_MIN,PREV_AMT_APPLICATION_MAX,PREV_AMT_APPLICATION_MEAN,PREV_AMT_CREDIT_MIN,PREV_AMT_CREDIT_MAX,PREV_AMT_CREDIT_MEAN,PREV_APP_CREDIT_PERC_MIN,PREV_APP_CREDIT_PERC_MAX,PREV_APP_CREDIT_PERC_MEAN,PREV_APP_CREDIT_PERC_VAR,PREV_AMT_DOWN_PAYMENT_MIN,PREV_AMT_DOWN_PAYMENT_MAX,PREV_AMT_DOWN_PAYMENT_MEAN,PREV_AMT_GOODS_PRICE_MIN,PREV_AMT_GOODS_PRICE_MAX,PREV_AMT_GOODS_PRICE_MEAN,PREV_HOUR_APPR_PROCESS_START_MIN,PREV_HOUR_APPR_PROCESS_START_MAX,PREV_HOUR_APPR_PROCESS_START_MEAN,PREV_RATE_DOWN_PAYMENT_MIN,PREV_RATE_DOWN_PAYMENT_MAX,PREV_RATE_DOWN_PAYMENT_MEAN,PREV_DAYS_DECISION_MIN,PREV_DAYS_DECISION_MAX,PREV_DAYS_DECISION_MEAN,PREV_CNT_PAYMENT_MEAN,PREV_CNT_PAYMENT_SUM,PREV_NAME_CONTRACT_TYPE_Cash loans_MEAN,PREV_NAME_CONTRACT_TYPE_Consumer loans_MEAN,PREV_NAME_CONTRACT_TYPE_Revolving loans_MEAN,PREV_WEEKDAY_APPR_PROCESS_START_FRIDAY_MEAN,PREV_WEEKDAY_APPR_PROCESS_START_MONDAY_MEAN,PREV_WEEKDAY_APPR_PROCESS_START_SATURDAY_MEAN,PREV_WEEKDAY_APPR_PROCESS_START_SUNDAY_MEAN,PREV_WEEKDAY_APPR_PROCESS_START_THURSDAY_MEAN,PREV_WEEKDAY_APPR_PROCESS_START_TUESDAY_MEAN,PREV_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_MEAN,PREV_NAME_CASH_LOAN_PURPOSE_Car repairs_MEAN,PREV_NAME_CASH_LOAN_PURPOSE_Medicine_MEAN,PREV_NAME_CASH_LOAN_PURPOSE_Repairs_MEAN,PREV_NAME_CASH_LOAN_PURPOSE_Urgent needs_MEAN,PREV_NAME_CASH_LOAN_PURPOSE_XNA_MEAN,PREV_NAME_CONTRACT_STATUS_Approved_MEAN,PREV_NAME_CONTRACT_STATUS_Canceled_MEAN,PREV_NAME_CONTRACT_STATUS_Refused_MEAN,PREV_NAME_PAYMENT_TYPE_Cash through the bank_MEAN,PREV_NAME_PAYMENT_TYPE_XNA_MEAN,PREV_CODE_REJECT_REASON_HC_MEAN,PREV_CODE_REJECT_REASON_LIMIT_MEAN,PREV_CODE_REJECT_REASON_SCO_MEAN,PREV_CODE_REJECT_REASON_SCOFR_MEAN,PREV_CODE_REJECT_REASON_XAP_MEAN,PREV_NAME_TYPE_SUITE_Children_MEAN,PREV_NAME_TYPE_SUITE_Family_MEAN,PREV_NAME_TYPE_SUITE_Other_A_MEAN,PREV_NAME_TYPE_SUITE_Other_B_MEAN,"PREV_NAME_TYPE_SUITE_Spouse, partner_MEAN",PREV_NAME_TYPE_SUITE_Unaccompanied_MEAN,PREV_NAME_TYPE_SUITE_nan_MEAN,PREV_NAME_CLIENT_TYPE_New_MEAN,PREV_NAME_CLIENT_TYPE_Refreshed_MEAN,PREV_NAME_CLIENT_TYPE_Repeater_MEAN,PREV_NAME_GOODS_CATEGORY_Audio/Video_MEAN,PREV_NAME_GOODS_CATEGORY_Computers_MEAN,PREV_NAME_GOODS_CATEGORY_Consumer Electronics_MEAN,PREV_NAME_GOODS_CATEGORY_Furniture_MEAN,PREV_NAME_GOODS_CATEGORY_Mobile_MEAN,PREV_NAME_GOODS_CATEGORY_Photo / Cinema Equipment_MEAN,PREV_NAME_GOODS_CATEGORY_Sport and Leisure_MEAN,PREV_NAME_PORTFOLIO_Cards_MEAN,PREV_NAME_PORTFOLIO_Cash_MEAN,PREV_NAME_PORTFOLIO_POS_MEAN,PREV_NAME_PORTFOLIO_XNA_MEAN,PREV_NAME_PRODUCT_TYPE_XNA_MEAN,PREV_NAME_PRODUCT_TYPE_walk-in_MEAN,PREV_NAME_PRODUCT_TYPE_x-sell_MEAN,PREV_CHANNEL_TYPE_AP+ (Cash loan)_MEAN,PREV_CHANNEL_TYPE_Channel of corporate sales_MEAN,PREV_CHANNEL_TYPE_Contact center_MEAN,PREV_CHANNEL_TYPE_Country-wide_MEAN,PREV_CHANNEL_TYPE_Credit and cash offices_MEAN,PREV_CHANNEL_TYPE_Regional / Local_MEAN,PREV_CHANNEL_TYPE_Stone_MEAN,PREV_NAME_SELLER_INDUSTRY_Auto technology_MEAN,PREV_NAME_SELLER_INDUSTRY_Clothing_MEAN,PREV_NAME_SELLER_INDUSTRY_Connectivity_MEAN,PREV_NAME_SELLER_INDUSTRY_Consumer electronics_MEAN,PREV_NAME_SELLER_INDUSTRY_XNA_MEAN,PREV_NAME_YIELD_GROUP_XNA_MEAN,PREV_NAME_YIELD_GROUP_high_MEAN,PREV_NAME_YIELD_GROUP_low_action_MEAN,PREV_NAME_YIELD_GROUP_low_normal_MEAN,PREV_NAME_YIELD_GROUP_middle_MEAN,PREV_PRODUCT_COMBINATION_Card Street_MEAN,PREV_PRODUCT_COMBINATION_Card X-Sell_MEAN,PREV_PRODUCT_COMBINATION_Cash_MEAN,PREV_PRODUCT_COMBINATION_Cash Street: high_MEAN,PREV_PRODUCT_COMBINATION_Cash Street: low_MEAN,PREV_PRODUCT_COMBINATION_Cash Street: middle_MEAN,PREV_PRODUCT_COMBINATION_Cash X-Sell: high_MEAN,PREV_PRODUCT_COMBINATION_Cash X-Sell: low_MEAN,PREV_PRODUCT_COMBINATION_Cash X-Sell: middle_MEAN,PREV_PRODUCT_COMBINATION_POS household with interest_MEAN,PREV_PRODUCT_COMBINATION_POS household without interest_MEAN,PREV_PRODUCT_COMBINATION_POS industry with interest_MEAN,PREV_PRODUCT_COMBINATION_POS mobile with interest_MEAN,PREV_PRODUCT_COMBINATION_POS other with interest_MEAN,APPROVED_AMT_ANNUITY_MIN,APPROVED_AMT_ANNUITY_MAX,APPROVED_AMT_ANNUITY_MEAN,APPROVED_AMT_APPLICATION_MIN,APPROVED_AMT_APPLICATION_MAX,APPROVED_AMT_APPLICATION_MEAN,APPROVED_AMT_CREDIT_MIN,APPROVED_AMT_CREDIT_MAX,APPROVED_AMT_CREDIT_MEAN,APPROVED_APP_CREDIT_PERC_MIN,APPROVED_APP_CREDIT_PERC_MAX,APPROVED_APP_CREDIT_PERC_MEAN,APPROVED_APP_CREDIT_PERC_VAR,APPROVED_AMT_DOWN_PAYMENT_MIN,APPROVED_AMT_DOWN_PAYMENT_MAX,APPROVED_AMT_DOWN_PAYMENT_MEAN,APPROVED_AMT_GOODS_PRICE_MIN,APPROVED_AMT_GOODS_PRICE_MAX,APPROVED_AMT_GOODS_PRICE_MEAN,APPROVED_HOUR_APPR_PROCESS_START_MIN,APPROVED_HOUR_APPR_PROCESS_START_MAX,APPROVED_HOUR_APPR_PROCESS_START_MEAN,APPROVED_RATE_DOWN_PAYMENT_MIN,APPROVED_RATE_DOWN_PAYMENT_MAX,APPROVED_RATE_DOWN_PAYMENT_MEAN,APPROVED_DAYS_DECISION_MIN,APPROVED_DAYS_DECISION_MAX,APPROVED_DAYS_DECISION_MEAN,APPROVED_CNT_PAYMENT_MEAN,APPROVED_CNT_PAYMENT_SUM,REFUSED_AMT_ANNUITY_MIN,REFUSED_AMT_ANNUITY_MAX,REFUSED_AMT_ANNUITY_MEAN,REFUSED_AMT_APPLICATION_MIN,REFUSED_AMT_APPLICATION_MAX,REFUSED_AMT_APPLICATION_MEAN,REFUSED_AMT_CREDIT_MIN,REFUSED_AMT_CREDIT_MAX,REFUSED_AMT_CREDIT_MEAN,REFUSED_APP_CREDIT_PERC_MIN,REFUSED_APP_CREDIT_PERC_MAX,REFUSED_APP_CREDIT_PERC_MEAN,REFUSED_APP_CREDIT_PERC_VAR,REFUSED_AMT_DOWN_PAYMENT_MIN,REFUSED_AMT_GOODS_PRICE_MIN,REFUSED_AMT_GOODS_PRICE_MAX,REFUSED_AMT_GOODS_PRICE_MEAN,REFUSED_HOUR_APPR_PROCESS_START_MIN,REFUSED_HOUR_APPR_PROCESS_START_MAX,REFUSED_HOUR_APPR_PROCESS_START_MEAN,REFUSED_RATE_DOWN_PAYMENT_MAX,REFUSED_RATE_DOWN_PAYMENT_MEAN,REFUSED_DAYS_DECISION_MIN,REFUSED_DAYS_DECISION_MAX,REFUSED_DAYS_DECISION_MEAN,REFUSED_CNT_PAYMENT_MEAN,REFUSED_CNT_PAYMENT_SUM,NEW_RATIO_PREV_AMT_ANNUITY_MIN,NEW_RATIO_PREV_AMT_ANNUITY_MAX,NEW_RATIO_PREV_AMT_ANNUITY_MEAN,NEW_RATIO_PREV_AMT_APPLICATION_MIN,NEW_RATIO_PREV_AMT_APPLICATION_MAX,NEW_RATIO_PREV_AMT_APPLICATION_MEAN,NEW_RATIO_PREV_AMT_CREDIT_MIN,NEW_RATIO_PREV_AMT_CREDIT_MAX,NEW_RATIO_PREV_AMT_CREDIT_MEAN,NEW_RATIO_PREV_APP_CREDIT_PERC_MIN,NEW_RATIO_PREV_APP_CREDIT_PERC_MAX,NEW_RATIO_PREV_APP_CREDIT_PERC_MEAN,NEW_RATIO_PREV_APP_CREDIT_PERC_VAR,NEW_RATIO_PREV_AMT_DOWN_PAYMENT_MAX,NEW_RATIO_PREV_AMT_DOWN_PAYMENT_MEAN,NEW_RATIO_PREV_AMT_GOODS_PRICE_MIN,NEW_RATIO_PREV_AMT_GOODS_PRICE_MAX,NEW_RATIO_PREV_AMT_GOODS_PRICE_MEAN,NEW_RATIO_PREV_HOUR_APPR_PROCESS_START_MIN,NEW_RATIO_PREV_HOUR_APPR_PROCESS_START_MAX,NEW_RATIO_PREV_HOUR_APPR_PROCESS_START_MEAN,NEW_RATIO_PREV_RATE_DOWN_PAYMENT_MIN,NEW_RATIO_PREV_RATE_DOWN_PAYMENT_MEAN,NEW_RATIO_PREV_DAYS_DECISION_MIN,NEW_RATIO_PREV_DAYS_DECISION_MAX,NEW_RATIO_PREV_DAYS_DECISION_MEAN,NEW_RATIO_PREV_CNT_PAYMENT_MEAN,NEW_RATIO_PREV_CNT_PAYMENT_SUM,POS_MONTHS_BALANCE_MAX,POS_MONTHS_BALANCE_MEAN,POS_MONTHS_BALANCE_SIZE,POS_SK_DPD_MAX,POS_SK_DPD_MEAN,POS_SK_DPD_DEF_MAX,POS_SK_DPD_DEF_MEAN,POS_NAME_CONTRACT_STATUS_Active_MEAN,POS_NAME_CONTRACT_STATUS_Completed_MEAN,POS_NAME_CONTRACT_STATUS_Returned to the store_MEAN,POS_NAME_CONTRACT_STATUS_Signed_MEAN,INSTAL_NUM_INSTALMENT_VERSION_NUNIQUE,INSTAL_DPD_MAX,INSTAL_DPD_MEAN,INSTAL_DPD_SUM,INSTAL_DBD_MAX,INSTAL_DBD_MEAN,INSTAL_DBD_SUM,INSTAL_PAYMENT_PERC_MAX,INSTAL_PAYMENT_PERC_MEAN,INSTAL_PAYMENT_PERC_SUM,INSTAL_PAYMENT_PERC_VAR,INSTAL_PAYMENT_DIFF_MAX,INSTAL_PAYMENT_DIFF_MEAN,INSTAL_PAYMENT_DIFF_SUM,INSTAL_PAYMENT_DIFF_VAR,INSTAL_AMT_INSTALMENT_MAX,INSTAL_AMT_INSTALMENT_MEAN,INSTAL_AMT_INSTALMENT_SUM,INSTAL_AMT_PAYMENT_MIN,INSTAL_AMT_PAYMENT_MAX,INSTAL_AMT_PAYMENT_MEAN,INSTAL_AMT_PAYMENT_SUM,INSTAL_DAYS_ENTRY_PAYMENT_MAX,INSTAL_DAYS_ENTRY_PAYMENT_MEAN,INSTAL_DAYS_ENTRY_PAYMENT_SUM,INSTAL_COUNT,CC_MONTHS_BALANCE_VAR,CC_AMT_BALANCE_MIN,CC_AMT_BALANCE_MAX,CC_AMT_BALANCE_MEAN,CC_AMT_BALANCE_SUM,CC_AMT_BALANCE_VAR,CC_AMT_CREDIT_LIMIT_ACTUAL_MIN,CC_AMT_CREDIT_LIMIT_ACTUAL_MAX,CC_AMT_CREDIT_LIMIT_ACTUAL_MEAN,CC_AMT_CREDIT_LIMIT_ACTUAL_SUM,CC_AMT_CREDIT_LIMIT_ACTUAL_VAR,CC_AMT_DRAWINGS_ATM_CURRENT_MAX,CC_AMT_DRAWINGS_ATM_CURRENT_MEAN,CC_AMT_DRAWINGS_ATM_CURRENT_SUM,CC_AMT_DRAWINGS_ATM_CURRENT_VAR,CC_AMT_DRAWINGS_CURRENT_MAX,CC_AMT_DRAWINGS_CURRENT_MEAN,CC_AMT_DRAWINGS_CURRENT_SUM,CC_AMT_DRAWINGS_CURRENT_VAR,CC_AMT_DRAWINGS_POS_CURRENT_MIN,CC_AMT_DRAWINGS_POS_CURRENT_MAX,CC_AMT_DRAWINGS_POS_CURRENT_MEAN,CC_AMT_DRAWINGS_POS_CURRENT_SUM,CC_AMT_DRAWINGS_POS_CURRENT_VAR,CC_AMT_INST_MIN_REGULARITY_MAX,CC_AMT_INST_MIN_REGULARITY_MEAN,CC_AMT_INST_MIN_REGULARITY_SUM,CC_AMT_INST_MIN_REGULARITY_VAR,CC_AMT_PAYMENT_CURRENT_MIN,CC_AMT_PAYMENT_CURRENT_MAX,CC_AMT_PAYMENT_CURRENT_MEAN,CC_AMT_PAYMENT_CURRENT_SUM,CC_AMT_PAYMENT_CURRENT_VAR,CC_AMT_PAYMENT_TOTAL_CURRENT_MAX,CC_AMT_PAYMENT_TOTAL_CURRENT_MEAN,CC_AMT_PAYMENT_TOTAL_CURRENT_SUM,CC_AMT_RECEIVABLE_PRINCIPAL_MIN,CC_AMT_RECEIVABLE_PRINCIPAL_MAX,CC_AMT_RECEIVABLE_PRINCIPAL_MEAN,CC_AMT_RECEIVABLE_PRINCIPAL_SUM,CC_AMT_RECEIVABLE_PRINCIPAL_VAR,CC_AMT_RECIVABLE_MIN,CC_AMT_RECIVABLE_MAX,CC_AMT_RECIVABLE_MEAN,CC_AMT_RECIVABLE_VAR,CC_AMT_TOTAL_RECEIVABLE_MEAN,CC_CNT_DRAWINGS_ATM_CURRENT_MAX,CC_CNT_DRAWINGS_ATM_CURRENT_MEAN,CC_CNT_DRAWINGS_ATM_CURRENT_SUM,CC_CNT_DRAWINGS_ATM_CURRENT_VAR,CC_CNT_DRAWINGS_CURRENT_MAX,CC_CNT_DRAWINGS_CURRENT_MEAN,CC_CNT_DRAWINGS_CURRENT_SUM,CC_CNT_DRAWINGS_CURRENT_VAR,CC_CNT_DRAWINGS_POS_CURRENT_MIN,CC_CNT_DRAWINGS_POS_CURRENT_MAX,CC_CNT_DRAWINGS_POS_CURRENT_MEAN,CC_CNT_DRAWINGS_POS_CURRENT_VAR,CC_CNT_INSTALMENT_MATURE_CUM_MEAN,CC_CNT_INSTALMENT_MATURE_CUM_SUM,CC_CNT_INSTALMENT_MATURE_CUM_VAR,CC_SK_DPD_DEF_MEAN,CC_NAME_CONTRACT_STATUS_Active_MEAN,CC_NAME_CONTRACT_STATUS_Active_SUM,CC_NAME_CONTRACT_STATUS_Active_VAR
0,0,Cash loans,F,Y,72000.0,198666.0,15696.0,175500.0,Unaccompanied,State servant,Secondary / secondary special,Married,House / apartment,0.025164,-9267,-2602.0,-372.0,-785,NaN,0,0,Core staff,4.0,2,2,THURSDAY,15,0,0,Government,0.044202,0.544933,NaN,0.4928,0.2583,0.9866,0.8164,0.1786,0.48,0.4138,0.3750,0.4167,0.2754,0.4009,0.5230,0.0039,0.0012,0.5021,0.2680,0.9866,0.8236,0.1803,0.4167,0.2817,0.4380,0.5449,0.0039,0.0013,0.4976,0.2583,0.9866,0.8189,0.1798,0.4138,0.3750,0.4167,0.2802,0.4079,0.5324,0.0039,0.0013,not specified,block of flats,0.5093,Panel,No,1.0,0.0,1.0,0.0,-1440.0,1,0,0,NaN,NaN,NaN,0.05,0.223607,20.0,3,0.517549,-2.24,135000.0,12.657110,1.132000,24000.0,0.280781,0.217997,NaN,0.294568,0.354070,NaN,NaN,0.155390,0.553420,2.759250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2250.000,16631.010,9472.005,0.0,225000.0,59148.9,0.0,314100.0,73399.95,0.716332,1.011031,0.886557,0.015746,0.0,3424.5,856.125,34231.5,225000.0,98581.5,10.0,18.0,13.300000,0.000000,0.100036,0.025009,-2344.0,-272.0,-850.200000,15.0,90.0,0.4,0.400000,0.200000,0.500000,0.2,0.2,0.0,0.100000,0.000000,0.0,0.0,0.0,0.0,0.0,0.4,0.500000,0.2,0.300000,0.300000,0.700000,0.200000,0.1,0.0,0.0,0.700000,0.0,0.4,0.0,0.0,0.0,0.200000,0.400000,0.100000,0.0,0.900000,0.1,0.1,0.0,0.000000,0.2,0.0,0.0,0.100000,0.1,0.400000,0.4,0.800000,0.1,0.100000,0.0,0.0,0.200000,0.4,0.400000,0.0,0.000000,0.0,0.0,0.2,0.2,0.600000,0.500000,0.3,0.0,0.0,0.200000,0.2,0.000000,0.3,0.0,0.0,0.0,0.0,0.0,0.1,0.2,0.0,0.000000,0.2,0.0,4059.585,16631.010,10916.4060,34231.5,225000.0,109297.8,33858.0,314100.0,137799.9,0.716332,1.011031,0.863868,0.015822,0.0,3424.5,856.125,34231.5,225000.0,109297.8,10.0,18.0,14.4,0.000000,0.100036,0.025009,-2344.0,-272.0,-1382.0,18.0,90.0,2250.000,2250.000,2250.000,0.0,45000.0,15000.0,0.0,45000.0,15000.0,1.000000,1.000000,1.000000,NaN,NaN,45000.0,45000.0,45000.0,11.0,15.0,13.333333,NaN,NaN,-388.0,-272.0,-349.333333,0.0,0.0,1.804260,7.391560,4.851736,NaN,5.000,7.28652,NaN,6.980000,9.186660,0.716332,1.011031,0.863868,NaN,NaN,NaN,0.7607,5.000,2.42884,0.909091,1.200000,1.080000,NaN,NaN,6.041237,1.000000,3.956107,NaN,NaN,-2.0,-43.15,60.0,18.0,0.3,18.0,0.3,0.950000,0.050000,0.0,0.0,4.0,24.0,0.616667,37.0,54.0,10.783333,647.0,9.208146,1.105500,66.329976,1.16438,16460.100,-1155.184500,-69311.070,1.142260e+08,80227.530,11559.575250,693574.515,3.915,90001.665,12714.759750,762885.585,-48.0,-1323.283333,-79397.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,FONDKAPREMONT_MODE,category,210293.0,68.39,4.0,"reg oper account, reg oper spec account, not specified, org spec account"
1,WALLSMATERIAL_MODE,category,156340.0,50.84,7.0,"Panel, Stone, brick, Block, Wooden, Mixed, Monolithic, Others"
2,HOUSETYPE_MODE,category,154296.0,50.18,3.0,"block of flats, specific housing, terraced house"
3,EMERGENCYSTATE_MODE,category,145754.0,47.40,2.0,"No, Yes"
4,OCCUPATION_TYPE,category,96389.0,31.35,18.0,"Laborers, Sales staff, Core staff, Managers, Drivers, High skill tech staff, Accountants, Medicine staff, Security staff, Cooking staff"
5,NAME_TYPE_SUITE,category,1292.0,0.42,7.0,"Unaccompanied, Family, Spouse, partner, Children, Other_B, Other_A, Group of people"
6,TARGET,category,0.0,0.00,2.0,"0, 1"
7,NAME_CONTRACT_TYPE,category,0.0,0.00,2.0,"Cash loans, Revolving loans"
8,CODE_GENDER,category,0.0,0.00,2.0,"F, M"
9,FLAG_OWN_REALTY,category,0.0,0.00,2.0,"Y, N"
10,NAME_INCOME_TYPE,category,0.0,0.00,8.0,"Working, Commercial associate, Pensioner, State servant, Unemployed, Student, Businessman, Maternity leave"
11,NAME_EDUCATION_TYPE,category,0.0,0.00,5.0,"Secondary / secondary special, Higher education, Incomplete higher, Lower secondary, Academic degree"
12,NAME_FAMILY_STATUS,category,0.0,0.00,6.0,"Married, Single / not married, Civil marriage, Separated, Widow, Unknown"
13,NAME_HOUSING_TYPE,category,0.0,0.00,6.0,"House / apartment, With parents, Municipal apartment, Rented apartment, Office apartment, Co-op apartment"
14,FLAG_WORK_PHONE,category,0.0,0.00,2.0,"0, 1"
15,FLAG_PHONE,category,0.0,0.00,2.0,"0, 1"
16,WEEKDAY_APPR_PROCESS_START,category,0.0,0.00,7.0,"TUESDAY, WEDNESDAY, MONDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY"
17,REG_CITY_NOT_LIVE_CITY,category,0.0,0.00,2.0,"0, 1"
18,LIVE_CITY_NOT_WORK_CITY,category,0.0,0.00,2.0,"0, 1"
19,ORGANIZATION_TYPE,category,0.0,0.00,58.0,"Business Entity Type 3, XNA, Self-employed, Other, Medicine, Business Entity Type 2, Government, School, Trade: type 7, Kindergarten"
20,FLAG_DOCUMENT_3,category,0.0,0.00,2.0,"1, 0"
21,FLAG_DOCUMENT_8,category,0.0,0.00,2.0,"0, 1"
22,FLAG_DOCUMENT_18,category,0.0,0.00,2.0,"0, 1"
23,NEW_RATIO_BURO_AMT_CREDIT_SUM_LIMIT_MEAN,float64,303906.0,98.83,1948.0,"0.0, 1.0, 2.0, 0.3, 5.0, 1.875, 0.296, 0.4364, 0.6667, 0.5"
24,NEW_RATIO_BURO_AMT_CREDIT_SUM_DEBT_MAX,float64,303273.0,98.62,3825.0,"0.0, 3.2608, 0.5683, 0.6934, 0.1428, 0.7695, 1.8448, 0.0, 1.004, 4.4003"
25,NEW_RATIO_BURO_AMT_CREDIT_SUM_DEBT_SUM,float64,301411.0,98.02,5072.0,"0.0, 3.2608, 0.1428, 0.5683, -1455.487, 1.6121, 0.9589, -13144.0353, -488.9192, 0.0"
26,NEW_RATIO_PREV_RATE_DOWN_PAYMENT_MIN,float64,291716.0,94.86,6550.0,"0.0, 1.0, 2.0, 0.5, 0.9309, 3.0, 0.3333, 0.4, 0.799, 0.7927"
27,NEW_RATIO_PREV_AMT_DOWN_PAYMENT_MAX,float64,286429.0,93.15,13992.0,"0.0, 1.0, 2.0, 0.5, 1.5, 2.5, 1.3333, 1.6667, 3.0, 5.0"
28,NEW_RATIO_PREV_AMT_DOWN_PAYMENT_MEAN,float64,286429.0,93.15,16387.0,"0.0, 1.0, 0.5, 2.0, 0.3333, 0.6667, 1.5, 0.25, 0.4, 1.3333"
29,NEW_RATIO_PREV_RATE_DOWN_PAYMENT_MEAN,float64,286429.0,93.15,17681.0,"0.0, 1.0, 0.5, 0.3333, 2.0, 0.6667, 0.25, 1.5, 0.3333, 0.4"
30,NEW_RATIO_BURO_AMT_CREDIT_MAX_OVERDUE_MEAN,float64,276818.0,90.02,10756.0,"0.0, 2.9149, 7.6963, 0.0745, 0.5649, 1.2586, 1.8219, 2.9425, 2.2393, 2.9375"
31,NEW_RATIO_BURO_AMT_ANNUITY_MAX,float64,276511.0,89.92,10438.0,"1.0, 0.0, 0.0161, 2.0, 0.5, 0.3333, 0.75, 1.6667, 10.0, 1.5"
32,NEW_RATIO_BURO_AMT_ANNUITY_MEAN,float64,276511.0,89.92,14382.0,"0.0, 1.0, 2.0, 0.5, 1.5, 0.6667, 1.3333, 3.0, 0.75, 1.25"
33,NEW_RATIO_PREV_APP_CREDIT_PERC_VAR,float64,272714.0,88.69,34225.0,"0.0, 1.0, 54.0, 88.6895, 0.1463, 0.0136, 615.5377, 0.0351, 222.308, 4.306"
34,REFUSED_AMT_DOWN_PAYMENT_MIN,float64,262339.0,85.31,5273.0,"0.0, 4500.0, 9000.0, 13500.0, 22500.0, 6750.0, 2250.0, 45000.0, 18000.0, 2700.0"
35,REFUSED_RATE_DOWN_PAYMENT_MAX,float64,262339.0,85.31,15641.0,"0.0, 0.1089, 0.2178, 0.3267, 0.5445, 0.4356, 0.0653, 0.109, 0.1091, 0.1307"
36,REFUSED_RATE_DOWN_PAYMENT_MEAN,float64,262339.0,85.31,17145.0,"0.0, 0.1089, 0.0545, 0.2178, 0.0363, 0.0726, 0.1634, 0.0272, 0.3267, 0.5445"
37,REFUSED_APP_CREDIT_PERC_VAR,float64,258350.0,84.01,31695.0,"0.0, 0.5, 0.0062, 0.0019, 0.0137, 0.3333, 0.008, 0.0091, 0.0041, 0.0068"
38,CC_AMT_PAYMENT_CURRENT_VAR,float64,246888.0,80.29,59041.0,"0.0, 1012500.0, 10125000.0, 40500.0, 2531250.0, 50625.0, 6328125000.0, 4050000.0, 3375000.0, 16200000.0"
39,CC_AMT_DRAWINGS_ATM_CURRENT_VAR,float64,246814.0,80.26,43704.0,"0.0, 337500000.0, 253125000.0, 1012500000.0, 506250000.0, 289285714.2857, 1157142857.1429, 2278125000.0, 2025000000.0, 202500000.0"
40,CC_AMT_DRAWINGS_POS_CURRENT_VAR,float64,246814.0,80.26,33669.0,"0.0, 2109.375, 225000000.0, 25312.5, 337500000.0, 22500.0, 289285714.2857, 40500.0, 289.2857, 405000000.0"
41,CC_CNT_DRAWINGS_ATM_CURRENT_VAR,float64,246814.0,80.26,29341.0,"0.0, 0.1667, 0.1429, 0.5, 0.125, 1.0, 2.0, 0.5714, 0.6667, 0.5536"
42,CC_CNT_DRAWINGS_POS_CURRENT_VAR,float64,246814.0,80.26,21978.0,"0.0, 0.1667, 0.1429, 0.0104, 0.5, 0.125, 0.1111, 0.0909, 0.0104, 0.0104"
43,CC_AMT_PAYMENT_CURRENT_MIN,float64,246447.0,80.14,9923.0,"0.0, 2250.0, 4500.0, 9000.0, 6750.0, 13500.0, 2700.0, 11250.0, 22500.0, 2475.0"
44,CC_AMT_PAYMENT_CURRENT_MAX,float64,246447.0,80.14,25753.0,"22500.0, 13500.0, 45000.0, 9000.0, 18000.0, 27000.0, 90000.0, 67500.0, 11250.0, 31500.0"
45,CC_AMT_PAYMENT_CURRENT_MEAN,float64,246447.0,80.14,56764.0,"0.0, 9000.0, 4500.0, 22500.0, 11250.0, 13500.0, 6750.0, 2250.0, 4950.0, 45000.0"
46,CC_AMT_DRAWINGS_ATM_CURRENT_MAX,float64,246367.0,80.12,1305.0,"0.0, 135000.0, 90000.0, 45000.0, 67500.0, 180000.0, 112500.0, 225000.0, 157500.0, 270000.0"
47,CC_AMT_DRAWINGS_ATM_CURRENT_MEAN,float64,246367.0,80.12,22420.0,"0.0, 22500.0, 4500.0, 11250.0, 9000.0, 45000.0, 2250.0, 7500.0, 13500.0, 15000.0"
48,CC_AMT_DRAWINGS_POS_CURRENT_MIN,float64,246367.0,80.12,2459.0,"0.0, 450.0, 2250.0, 1350.0, 225.0, 900.0, 675.0, 4500.0, 3150.0, 45.0"
49,CC_AMT_DRAWINGS_POS_CURRENT_MAX,float64,246367.0,80.12,28865.0,"0.0, 45000.0, 450.0, 900.0, 90000.0, 225.0, 1350.0, 2250.0, 4500.0, 135000.0"
50,CC_AMT_DRAWINGS_POS_CURRENT_MEAN,float64,246367.0,80.12,33412.0,"0.0, 90.0, 56.25, 5000.0, 4.6875, 225.0, 45.0, 375.0, 14.0625, 9.375"
51,CC_CNT_DRAWINGS_ATM_CURRENT_MAX,float64,246367.0,80.12,44.0,"0.0, 3.0, 4.0, 2.0, 5.0, 1.0, 6.0, 7.0, 8.0, 9.0"
52,CC_CNT_DRAWINGS_ATM_CURRENT_MEAN,float64,246367.0,80.12,3385.0,"0.0, 1.0, 0.5, 0.3333, 0.25, 0.6667, 0.1667, 0.125, 2.0, 0.2"
53,CC_CNT_DRAWINGS_POS_CURRENT_MIN,float64,246367.0,80.12,45.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0"
54,CC_CNT_DRAWINGS_POS_CURRENT_MAX,float64,246367.0,80.12,123.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
55,CC_CNT_DRAWINGS_POS_CURRENT_MEAN,float64,246367.0,80.12,5024.0,"0.0, 1.0, 0.5, 0.3333, 2.0, 0.0104, 0.1667, 0.25, 0.2, 0.1429"
56,ACTIVE_AMT_ANNUITY_MAX,float64,246161.0,80.05,19214.0,"0.0, 4500.0, 13500.0, 22500.0, 45000.0, 18000.0, 27000.0, 9000.0, 11250.0, 2700.0"
57,ACTIVE_AMT_ANNUITY_MEAN,float64,246161.0,80.05,26843.0,"0.0, 4500.0, 13500.0, 22500.0, 9000.0, 18000.0, 2250.0, 45000.0, 27000.0, 6750.0"
58,NEW_RATIO_BURO_MONTHS_BALANCE_MIN_MIN,float64,242444.0,78.84,4501.0,"1.0, 0.5, 0.3333, 0.0, 0.6667, 0.25, 0.4, 0.2, 0.75, 0.6"
59,NEW_RATIO_BURO_MONTHS_BALANCE_SIZE_MEAN,float64,242426.0,78.84,25699.0,"1.0, 0.5, 0.6667, 0.75, 0.8333, 0.3333, 0.8, 0.875, 0.25, 0.4"
60,NEW_RATIO_BURO_MONTHS_BALANCE_SIZE_SUM,float64,242409.0,78.83,20335.0,"1.0, 0.5, 0.3333, 2.0, 0.25, 0.6667, 0.2, 0.4, 1.5, 0.75"
61,CLOSED_AMT_ANNUITY_MAX,float64,241498.0,78.53,17576.0,"0.0, 4500.0, 13500.0, 22500.0, 18000.0, 45000.0, 27000.0, 9000.0, 11250.0, 33750.0"
62,CLOSED_AMT_ANNUITY_MEAN,float64,241498.0,78.53,25564.0,"0.0, 4500.0, 22500.0, 13500.0, 9000.0, 18000.0, 45000.0, 2250.0, 6750.0, 27000.0"
63,ACTIVE_MONTHS_BALANCE_MIN_MIN,float64,230988.0,75.12,97.0,"-11.0, -5.0, -6.0, -7.0, -4.0, -8.0, -9.0, -10.0, -12.0, -16.0"
64,ACTIVE_MONTHS_BALANCE_MAX_MAX,float64,230988.0,75.12,92.0,"0.0, -1.0, -2.0, -5.0, -3.0, -4.0, -6.0, -7.0, -9.0, -8.0"
65,ACTIVE_MONTHS_BALANCE_SIZE_MEAN,float64,230988.0,75.12,1351.0,"5.0, 6.0, 7.0, 8.0, 9.0, 4.0, 12.0, 10.0, 11.0, 13.0"
66,NEW_RATIO_PREV_CNT_PAYMENT_MEAN,float64,230398.0,74.92,8710.0,"1.0, 0.5, 0.6667, 0.75, 0.3333, 2.0, 1.5, 0.8333, 0.25, 1.3333"
67,NEW_RATIO_PREV_CNT_PAYMENT_SUM,float64,230398.0,74.92,5082.0,"1.0, 2.0, 0.5, 3.0, 1.5, 0.6667, 0.3333, 4.0, 1.3333, 2.5"
68,BURO_AMT_ANNUITY_MAX,float64,227498.0,73.98,23582.0,"0.0, 4500.0, 13500.0, 22500.0, 45000.0, 18000.0, 27000.0, 9000.0, 11250.0, 33750.0"
69,BURO_AMT_ANNUITY_MEAN,float64,227498.0,73.98,40578.0,"0.0, 4500.0, 13500.0, 22500.0, 18000.0, 9000.0, 2250.0, 45000.0, 6750.0, 11250.0"
70,NEW_RATIO_PREV_AMT_APPLICATION_MIN,float64,227236.0,73.90,48068.0,"0.0, 1.0, 0.5, 0.2, 0.3333, 0.6667, 0.4, 0.25, 0.1, 2.0"
71,CLOSED_MONTHS_BALANCE_MIN_MIN,float64,226772.0,73.75,97.0,"-95.0, -92.0, -94.0, -88.0, -91.0, -87.0, -93.0, -89.0, -90.0, -86.0"
72,CLOSED_MONTHS_BALANCE_SIZE_MEAN,float64,226772.0,73.75,4049.0,"17.0, 16.0, 13.0, 15.0, 19.0, 14.0, 12.0, 18.0, 20.0, 8.0"
73,CC_MONTHS_BALANCE_VAR,float64,221234.0,71.94,1183.0,"4.6667, 6.0, 3.5, 9.1667, 7.5, 11.0, 2.5, 776.0, 13.0, 1.6667"
74,CC_AMT_BALANCE_VAR,float64,221234.0,71.94,59357.0,"0.0, 616617.5625, 289285714.2857, 13034.4828, 352352.8929, 1644313.5, 1520087808.3848, 2109.375, 4138845883.2335, 8479034925.3785"
75,CC_AMT_CREDIT_LIMIT_ACTUAL_VAR,float64,221234.0,71.94,24877.0,"0.0, 2160000000.0, 2025000000.0, 2314285714.2857, 1350000000.0, 1157142857.1429, 2250000000.0, 1440000000.0, 4050000000.0, 1620000000.0"
76,CC_AMT_DRAWINGS_CURRENT_VAR,float64,221234.0,71.94,56040.0,"0.0, 84375000.0, 1012500000.0, 289285714.2857, 2025000000.0, 253125000.0, 1157142857.1429, 202500000.0, 337500000.0, 21093750.0"
77,CC_AMT_INST_MIN_REGULARITY_VAR,float64,221234.0,71.94,57582.0,"0.0, 1687500.0, 1265625.0, 1012500.0, 1350000.0, 1205357.1429, 1518750.0, 723214.2857, 843750.0, 1356026.7857"
78,CC_AMT_RECEIVABLE_PRINCIPAL_VAR,float64,221234.0,71.94,58564.0,"0.0, 506250000.0, 225000000.0, 337500000.0, 289285714.2857, 675000000.0, 184090909.0909, 202500000.0, 1620000000.0, 405000000.0"
79,CC_AMT_RECIVABLE_VAR,float64,221234.0,71.94,59445.0,"0.0, 65.0893, 62.4144, 65.0893, 63.2812, 58.4135, 64.1725, 61.5709, 60.75, 66.0326"
80,CC_CNT_DRAWINGS_CURRENT_VAR,float64,221234.0,71.94,41524.0,"0.0, 0.5, 0.1667, 0.0104, 2.0, 0.1429, 1.0, 0.125, 0.5714, 0.3333"
81,CC_CNT_INSTALMENT_MATURE_CUM_VAR,float64,221234.0,71.94,25349.0,"0.0, 5.125, 4.6667, 3.5, 3.8095, 6.6111, 8.2667, 6.0, 2.6667, 9.1667"
82,CC_NAME_CONTRACT_STATUS_Active_VAR,float64,221234.0,71.94,3107.0,"0.0, 0.1429, 0.125, 0.1111, 0.2667, 0.1667, 0.2, 0.1, 0.0909, 0.25"
83,NEW_RATIO_PREV_AMT_CREDIT_MIN,float64,220702.0,71.77,75869.0,"1.0, 0.0, 0.5, 0.2, 0.3333, 0.6667, 0.4, 0.75, 1.066, 0.1"
84,CC_AMT_BALANCE_MIN,float64,220602.0,71.74,11608.0,"0.0, 67.5, 46570.5, 130.5, 4945.5, 93141.0, 48141.0, 46607.355, 139711.5, 46345.5"
85,CC_AMT_BALANCE_MAX,float64,220602.0,71.74,56722.0,"0.0, 92043.0, 190386.0, 450.0, 138064.5, 69032.25, 184086.0, 115053.75, 46570.5, 1570.5"
86,CC_AMT_BALANCE_MEAN,float64,220602.0,71.74,59467.0,"0.0, 46570.5, 523.5, 1570.5, 4.6875, 314.1, 30.0, 11250.0, 900.0, 897.4286"
87,CC_AMT_BALANCE_SUM,float64,220602.0,71.74,58811.0,"0.0, 450.0, 900.0, 1570.5, 46570.5, 1345.5, 3141.0, 265.5, 4711.5, 130.5"
88,CC_AMT_CREDIT_LIMIT_ACTUAL_MIN,float64,220602.0,71.74,161.0,"45000.0, 0.0, 180000.0, 135000.0, 450000.0, 225000.0, 90000.0, 270000.0, 765000.0, 67500.0"
89,CC_AMT_CREDIT_LIMIT_ACTUAL_MAX,float64,220602.0,71.74,54.0,"135000.0, 180000.0, 450000.0, 225000.0, 90000.0, 45000.0, 270000.0, 67500.0, 112500.0, 765000.0"
90,CC_AMT_CREDIT_LIMIT_ACTUAL_MEAN,float64,220602.0,71.74,11313.0,"45000.0, 180000.0, 135000.0, 450000.0, 225000.0, 90000.0, 270000.0, 765000.0, 900000.0, 112500.0"
91,CC_AMT_CREDIT_LIMIT_ACTUAL_SUM,float64,220602.0,71.74,2440.0,"1080000.0, 540000.0, 810000.0, 1620000.0, 1350000.0, 720000.0, 0.0, 2700000.0, 900000.0, 675000.0"
92,CC_AMT_DRAWINGS_ATM_CURRENT_SUM,float64,220602.0,71.74,5016.0,"0.0, 135000.0, 90000.0, 45000.0, 180000.0, 67500.0, 225000.0, 112500.0, 157500.0, 270000.0"
93,CC_AMT_DRAWINGS_CURRENT_MAX,float64,220602.0,71.74,24117.0,"0.0, 135000.0, 90000.0, 180000.0, 67500.0, 45000.0, 112500.0, 225000.0, 157500.0, 270000.0"
94,CC_AMT_DRAWINGS_CURRENT_MEAN,float64,220602.0,71.74,49079.0,"0.0, 22500.0, 11250.0, 45000.0, 15000.0, 9000.0, 1406.25, 4500.0, 2250.0, 7500.0"
95,CC_AMT_DRAWINGS_CURRENT_SUM,float64,220602.0,71.74,40377.0,"0.0, 135000.0, 90000.0, 180000.0, 45000.0, 67500.0, 225000.0, 112500.0, 157500.0, 270000.0"
96,CC_AMT_DRAWINGS_POS_CURRENT_SUM,float64,220602.0,71.74,31662.0,"0.0, 450.0, 45000.0, 900.0, 225.0, 1350.0, 4500.0, 1800.0, 2250.0, 45.0"
97,CC_AMT_INST_MIN_REGULARITY_MAX,float64,220602.0,71.74,32000.0,"0.0, 9000.0, 2250.0, 6750.0, 3375.0, 4500.0, 5625.0, 7875.0, 8100.0, 13500.0"
98,CC_AMT_INST_MIN_REGULARITY_MEAN,float64,220602.0,71.74,57389.0,"0.0, 9000.0, 4500.0, 6750.0, 1500.0, 1125.0, 3375.0, 750.0, 5625.0, 1607.1429"
99,CC_AMT_INST_MIN_REGULARITY_SUM,float64,220602.0,71.74,56353.0,"0.0, 2250.0, 11250.0, 4500.0, 9000.0, 6750.0, 13500.0, 450.0, 225.0, 15750.0"
100,CC_AMT_PAYMENT_CURRENT_SUM,float64,220602.0,71.74,54234.0,"0.0, 225000.0, 45000.0, 135000.0, 90000.0, 67500.0, 22500.0, 450.0, 13500.0, 9000.0"
101,CC_AMT_PAYMENT_TOTAL_CURRENT_MAX,float64,220602.0,71.74,30350.0,"0.0, 22500.0, 13500.0, 9000.0, 45000.0, 18000.0, 27000.0, 11250.0, 90000.0, 67500.0"
102,CC_AMT_PAYMENT_TOTAL_CURRENT_MEAN,float64,220602.0,71.74,57833.0,"0.0, 11250.0, 9000.0, 4500.0, 6750.0, 22500.0, 2250.0, 13500.0, 5625.0, 45000.0"
103,CC_AMT_PAYMENT_TOTAL_CURRENT_SUM,float64,220602.0,71.74,52950.0,"0.0, 225000.0, 135000.0, 90000.0, 45000.0, 67500.0, 450.0, 22500.0, 18000.0, 450000.0"
104,CC_AMT_RECEIVABLE_PRINCIPAL_MIN,float64,220602.0,71.74,8523.0,"0.0, 45000.0, 90000.0, 135000.0, 4500.0, 22500.0, 67500.0, 180000.0, 13500.0, 9000.0"
105,CC_AMT_RECEIVABLE_PRINCIPAL_MAX,float64,220602.0,71.74,46271.0,"0.0, 180000.0, 135000.0, 90000.0, 67500.0, 45000.0, 112500.0, 157500.0, 225000.0, 450000.0"
106,CC_AMT_RECEIVABLE_PRINCIPAL_MEAN,float64,220602.0,71.74,58549.0,"0.0, 45000.0, 4500.0, 11250.0, 1500.0, 90000.0, 6428.5714, 22500.0, 5000.0, 4090.9091"
107,CC_AMT_RECEIVABLE_PRINCIPAL_SUM,float64,220602.0,71.74,57769.0,"0.0, 45000.0, 90000.0, 135000.0, 67500.0, 22500.0, 180000.0, 9000.0, 4500.0, 225000.0"
108,CC_AMT_RECIVABLE_MIN,float64,220602.0,71.74,19919.0,"0.0, 45000.0, 90000.0, 4500.0, 135000.0, 45036.855, 67500.0, 22500.0, 45073.71, 13500.0"
109,CC_AMT_RECIVABLE_MAX,float64,220602.0,71.74,56412.0,"0.0, 67.5, 45000.0, 92043.0, 190386.0, 138064.5, 450.0, 184086.0, 69032.25, 90000.0"
110,CC_AMT_RECIVABLE_MEAN,float64,220602.0,71.74,59521.0,"0.0, 0.9643, 45000.0, 0.9247, 0.8654, 0.9122, 0.8766, 0.9783, 0.9507, 0.9375"
111,CC_AMT_TOTAL_RECEIVABLE_MEAN,float64,220602.0,71.74,59521.0,"0.0, 0.9643, 45000.0, 0.9247, 0.8654, 0.9122, 0.8766, 0.9783, 0.9507, 0.9375"
112,CC_CNT_DRAWINGS_ATM_CURRENT_SUM,float64,220602.0,71.74,163.0,"0.0, 3.0, 2.0, 4.0, 1.0, 5.0, 6.0, 7.0, 8.0, 10.0"
113,CC_CNT_DRAWINGS_CURRENT_MAX,float64,220602.0,71.74,119.0,"0.0, 4.0, 3.0, 2.0, 5.0, 6.0, 1.0, 7.0, 8.0, 9.0"
114,CC_CNT_DRAWINGS_CURRENT_MEAN,float64,220602.0,71.74,6584.0,"0.0, 1.0, 0.5, 2.0, 0.3333, 0.25, 1.5, 3.0, 0.1667, 0.125"
115,CC_CNT_DRAWINGS_CURRENT_SUM,float64,220602.0,71.74,548.0,"0.0, 1.0, 4.0, 2.0, 3.0, 5.0, 6.0, 8.0, 7.0, 10.0"
116,CC_CNT_INSTALMENT_MATURE_CUM_MEAN,float64,220602.0,71.74,13923.0,"0.0, 2.1429, 2.625, 3.0, 1.6667, 3.1111, 2.5, 3.5, 3.6, 4.0"
117,CC_CNT_INSTALMENT_MATURE_CUM_SUM,float64,220602.0,71.74,4925.0,"0.0, 15.0, 21.0, 28.0, 36.0, 10.0, 45.0, 55.0, 66.0, 78.0"
118,CC_SK_DPD_DEF_MEAN,float64,220602.0,71.74,1548.0,"0.0, 0.0104, 0.0208, 0.0312, 0.0105, 0.0417, 0.0521, 0.0211, 0.0106, 0.0625"
119,CC_NAME_CONTRACT_STATUS_Active_MEAN,float64,220602.0,71.74,1004.0,"1.0, 0.75, 0.8571, 0.6667, 0.875, 0.8, 0.8333, 0.5, 0.8889, 0.9"
120,CC_NAME_CONTRACT_STATUS_Active_SUM,float64,220602.0,71.74,103.0,"96.0, 8.0, 7.0, 9.0, 6.0, 10.0, 11.0, 12.0, 5.0, 95.0"
121,NEW_RATIO_PREV_APP_CREDIT_PERC_MIN,float64,219945.0,71.53,49967.0,"0.0, 1.0, 0.9381, 0.8834, 0.9099, 0.8347, 1.198, 0.9, 1.1111, 0.8783"
122,NEW_RATIO_PREV_AMT_GOODS_PRICE_MIN,float64,217682.0,70.79,62832.0,"1.0, 0.0, 0.5, 0.2, 0.3333, 0.6667, 0.4, 0.25, 2.0, 0.1"
123,NEW_RATIO_PREV_AMT_ANNUITY_MIN,float64,216542.0,70.42,83470.0,"1.0, 0.0, 0.3333, 0.2, 0.5, 2.0, 0.4, 0.6667, 0.25, 0.6"
124,NEW_RATIO_PREV_AMT_ANNUITY_MAX,float64,216498.0,70.40,87053.0,"1.0, 2.0, 4.0, 3.4, 0.8, 0.6667, 0.6, 0.5, 10.0, 1.5"
125,NEW_RATIO_PREV_AMT_ANNUITY_MEAN,float64,216498.0,70.40,90616.0,"1.0, 0.0, 0.6667, 0.5, 0.6, 0.8, 0.75, 0.9, 0.3333, 0.9683"
126,NEW_RATIO_PREV_AMT_GOODS_PRICE_MAX,float64,216124.0,70.28,47028.0,"1.0, 0.5, 2.0, 0.6667, 0.6, 1.5, 0.8, 0.4, 3.0, 0.75"
127,NEW_RATIO_PREV_AMT_GOODS_PRICE_MEAN,float64,216124.0,70.28,85336.0,"1.0, 0.5, 0.6667, 0.75, 0.8, 1.5, 0.6, 2.0, 0.3333, 0.4"
128,NEW_RATIO_PREV_APP_CREDIT_PERC_MAX,float64,215951.0,70.23,65833.0,"1.0, 1.1111, 0.9381, 1.25, 1.066, 0.9, 0.9681, 1.198, 1.132, 1.1188"
129,NEW_RATIO_PREV_APP_CREDIT_PERC_MEAN,float64,215951.0,70.23,87054.0,"1.0, 0.0, 1.1111, 0.9381, 1.0556, 0.969, 0.5, 1.066, 0.9, 1.198"
130,REFUSED_AMT_ANNUITY_MIN,float64,215941.0,70.22,43719.0,"2250.0, 11250.0, 6750.0, 4500.0, 9000.0, 7875.0, 22500.0, 13500.0, 3375.0, 5625.0"
131,REFUSED_AMT_ANNUITY_MAX,float64,215941.0,70.22,43628.0,"11250.0, 2250.0, 6750.0, 22500.0, 4500.0, 9000.0, 13500.0, 7875.0, 45000.0, 38250.0"
132,REFUSED_AMT_ANNUITY_MEAN,float64,215941.0,70.22,66267.0,"2250.0, 11250.0, 6750.0, 4500.0, 9000.0, 7875.0, 22500.0, 13500.0, 5625.0, 3375.0"
133,REFUSED_CNT_PAYMENT_MEAN,float64,215941.0,70.22,1091.0,"0.0, 12.0, 24.0, 6.0, 60.0, 36.0, 10.0, 18.0, 48.0, 30.0"
134,NEW_RATIO_PREV_AMT_APPLICATION_MAX,float64,215943.0,70.22,47025.0,"1.0, 0.5, 2.0, 0.6667, 0.6, 1.5, 0.8, 0.4, 3.0, 0.75"
135,NEW_RATIO_PREV_AMT_APPLICATION_MEAN,float64,215943.0,70.22,85478.0,"1.0, 0.0, 0.5, 2.0, 0.6667, 1.5, 0.75, 0.8, 0.3333, 0.6"
136,BURO_MONTHS_BALANCE_MIN_MIN,float64,215276.0,70.01,97.0,"-95.0, -92.0, -94.0, -93.0, -91.0, -88.0, -87.0, -89.0, -90.0, -86.0"
137,BURO_MONTHS_BALANCE_SIZE_MEAN,float64,215276.0,70.01,5673.0,"8.0, 9.0, 12.0, 10.0, 11.0, 13.0, 7.0, 6.0, 14.0, 5.0"
138,BURO_STATUS_0_MEAN_MEAN,float64,215276.0,70.01,60712.0,"1.0, 0.0, 0.5, 0.75, 0.6667, 0.3333, 0.8333, 0.8, 0.25, 0.875"
139,BURO_STATUS_1_MEAN_MEAN,float64,215276.0,70.01,13641.0,"0.0, 0.0417, 0.0833, 0.0167, 0.0208, 0.0278, 0.0556, 0.0333, 0.025, 0.05"
140,BURO_STATUS_C_MEAN_MEAN,float64,215276.0,70.01,51205.0,"0.0, 0.3333, 0.25, 0.5, 0.1667, 0.125, 0.2, 0.6667, 0.1429, 0.0833"
141,BURO_STATUS_X_MEAN_MEAN,float64,215276.0,70.01,41962.0,"0.0, 1.0, 0.5, 0.3333, 0.25, 0.1667, 0.125, 0.2, 0.0833, 0.1429"
142,COMMONAREA_AVG,float64,214862.0,69.87,3181.0,"0.0, 0.0079, 0.0078, 0.008, 0.0077, 0.0086, 0.0014, 0.007, 0.0013, 0.0069"
143,COMMONAREA_MODE,float64,214862.0,69.87,3128.0,"0.0, 0.008, 0.0079, 0.0078, 0.0081, 0.0087, 0.0014, 0.007, 0.0071, 0.0012"
144,COMMONAREA_MEDI,float64,214862.0,69.87,3202.0,"0.0, 0.0079, 0.008, 0.0078, 0.0014, 0.0086, 0.0081, 0.0071, 0.0087, 0.0012"
145,REFUSED_AMT_GOODS_PRICE_MIN,float64,214278.0,69.68,18615.0,"45000.0, 225000.0, 135000.0, 450000.0, 90000.0, 180000.0, 0.0, 270000.0, 675000.0, 67500.0"
146,REFUSED_AMT_GOODS_PRICE_MAX,float64,214278.0,69.68,17298.0,"225000.0, 450000.0, 45000.0, 135000.0, 675000.0, 180000.0, 900000.0, 1350000.0, 270000.0, 90000.0"
147,REFUSED_AMT_GOODS_PRICE_MEAN,float64,214278.0,69.68,31593.0,"225000.0, 45000.0, 135000.0, 450000.0, 180000.0, 90000.0, 270000.0, 675000.0, 0.0, 900000.0"
148,NONLIVINGAPARTMENTS_AVG,float64,213512.0,69.43,386.0,"0.0, 0.0039, 0.0077, 0.0116, 0.0154, 0.0193, 0.0019, 0.0232, 0.027, 0.0309"
149,NONLIVINGAPARTMENTS_MODE,float64,213512.0,69.43,167.0,"0.0, 0.0039, 0.0078, 0.0117, 0.0156, 0.0195, 0.0233, 0.0272, 0.0311, 0.035"

In [13]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
AMT_INCOME_TOTAL,307507.0,1.687977e+05,2.371246e+05,2.565000e+04,1.170000e+08
AMT_CREDIT,307507.0,5.990286e+05,4.024926e+05,4.500000e+04,4.050000e+06
AMT_ANNUITY,307495.0,2.710867e+04,1.449380e+04,1.615500e+03,2.580255e+05
AMT_GOODS_PRICE,307229.0,5.383977e+05,3.694472e+05,4.050000e+04,4.050000e+06
REGION_POPULATION_RELATIVE,307507.0,2.086800e-02,1.383131e-02,2.900000e-04,7.250800e-02
DAYS_BIRTH,307507.0,-1.603703e+04,4.363982e+03,-2.522900e+04,-7.489000e+03
DAYS_EMPLOYED,252133.0,-2.384142e+03,2.338328e+03,-1.791200e+04,0.000000e+00
DAYS_REGISTRATION,307507.0,-4.986131e+03,3.522883e+03,-2.467200e+04,0.000000e+00
DAYS_ID_PUBLISH,307507.0,-2.994202e+03,1.509455e+03,-7.197000e+03,0.000000e+00
OWN_CAR_AGE,104580.0,1.206112e+01,1.194492e+01,0.000000e+00,9.100000e+01
CNT_FAM_MEMBERS,307505.0,2.152658e+00,9.106800e-01,1.000000e+00,2.000000e+01
REGION_RATING_CLIENT,307507.0,2.052461e+00,5.090343e-01,1.000000e+00,3.000000e+00
REGION_RATING_CLIENT_W_CITY,307507.0,2.031518e+00,5.027373e-01,1.000000e+00,3.000000e+00
HOUR_APPR_PROCESS_START,307507.0,1.206339e+01,3.265835e+00,0.000000e+00,2.300000e+01
EXT_SOURCE_1,134131.0,5.021294e-01,2.110633e-01,1.456813e-02,9.626928e-01
EXT_SOURCE_2,306847.0,5.143918e-01,1.910603e-01,8.173617e-08,8.549997e-01
EXT_SOURCE_3,246542.0,5.108563e-01,1.948433e-01,5.272652e-04,8.960095e-01
APARTMENTS_AVG,151447.0,1.174420e-01,1.082408e-01,0.000000e+00,1.000000e+00
BASEMENTAREA_AVG,127565.0,8.844251e-02,8.243885e-02,0.000000e+00,1.000000e+00
YEARS_BEGINEXPLUATATION_AVG,157501.0,9.777348e-01,5.922386e-02,0.000000e+00,1.000000e+00
YEARS_BUILD_AVG,103021.0,7.524715e-01,1.132793e-01,0.000000e+00,1.000000e+00
COMMONAREA_AVG,92645.0,4.462114e-02,7.603605e-02,0.000000e+00,1.000000e+00
ELEVATORS_AVG,143617.0,7.894316e-02,1.345769e-01,0.000000e+00,1.000000e+00
ENTRANCES_AVG,152680.0,1.497258e-01,1.000497e-01,0.000000e+00,1.000000e+00
FLOORSMAX_AVG,154488.0,2.262844e-01,1.446408e-01,0.000000e+00,1.000000e+00
FLOORSMIN_AVG,98867.0,2.318965e-01,1.613804e-01,0.000000e+00,1.000000e+00
LANDAREA_AVG,124919.0,6.633385e-02,8.118412e-02,0.000000e+00,1.000000e+00
LIVINGAPARTMENTS_AVG,97310.0,1.007760e-01,9.257666e-02,0.000000e+00,1.000000e+00
LIVINGAREA_AVG,153158.0,1.074005e-01,1.105651e-01,0.000000e+00,1.000000e+00
NONLIVINGAPARTMENTS_AVG,93995.0,8.808819e-03,4.773216e-02,0.000000e+00,1.000000e+00
NONLIVINGAREA_AVG,137827.0,2.835812e-02,6.952362e-02,0.000000e+00,1.000000e+00
APARTMENTS_MODE,151447.0,1.142325e-01,1.079366e-01,0.000000e+00,1.000000e+00
BASEMENTAREA_MODE,127565.0,8.754342e-02,8.430788e-02,0.000000e+00,1.000000e+00
YEARS_BEGINEXPLUATATION_MODE,157501.0,9.770653e-01,6.457604e-02,0.000000e+00,1.000000e+00
YEARS_BUILD_MODE,103021.0,7.596373e-01,1.101104e-01,0.000000e+00,1.000000e+00
COMMONAREA_MODE,92645.0,4.255354e-02,7.444482e-02,0.000000e+00,1.000000e+00
FLOORSMIN_MODE,98867.0,2.280614e-01,1.611600e-01,0.000000e+00,1.000000e+00
LANDAREA_MODE,124919.0,6.495832e-02,8.175078e-02,0.000000e+00,1.000000e+00
LIVINGAPARTMENTS_MODE,97310.0,1.056461e-01,9.788103e-02,0.000000e+00,1.000000e+00
LIVINGAREA_MODE,153158.0,1.059764e-01,1.118459e-01,0.000000e+00,1.000000e+00
NONLIVINGAPARTMENTS_MODE,93995.0,8.076518e-03,4.627675e-02,0.000000e+00,1.000000e+00
NONLIVINGAREA_MODE,137827.0,2.702266e-02,7.025431e-02,0.000000e+00,1.000000e+00
APARTMENTS_MEDI,151447.0,1.178514e-01,1.090764e-01,0.000000e+00,1.000000e+00
BASEMENTAREA_MEDI,127565.0,8.795514e-02,8.217943e-02,0.000000e+00,1.000000e+00
YEARS_BEGINEXPLUATATION_MEDI,157501.0,9.777522e-01,5.989788e-02,0.000000e+00,1.000000e+00
YEARS_BUILD_MEDI,103021.0,7.557463e-01,1.120657e-01,0.000000e+00,1.000000e+00
COMMONAREA_MEDI,92645.0,4.459552e-02,7.614456e-02,0.000000e+00,1.000000e+00
ENTRANCES_MEDI,152680.0,1.492139e-01,1.003690e-01,0.000000e+00,1.000000e+00
FLOORSMAX_MEDI,154488.0,2.258991e-01,1.450671e-01,0.000000e+00,1.000000e+00
FLOORSMIN_MEDI,98867.0,2.316279e-01,1.619337e-01,0.000000e+00,1.000000e+00
LANDAREA_MEDI,124919.0,6.716942e-02,8.216750e-02,0.000000e+00,1.000000e+00
LIVINGAPARTMENTS_MEDI,97310.0,1.019557e-01,9.364287e-02,0.000000e+00,1.000000e+00
LIVINGAREA_MEDI,153158.0,1.086082e-01,1.122608e-01,0.000000e+00,1.000000e+00
NONLIVINGAPARTMENTS_MEDI,93995.0,8.651156e-03,4.741522e-02,0.000000e+00,1.000000e+00
NONLIVINGAREA_MEDI,137827.0,2.823628e-02,7.016693e-02,0.000000e+00,1.000000e+00
TOTALAREA_MODE,159077.0,1.025479e-01,1.074629e-01,0.000000e+00,1.000000e+00
OBS_30_CNT_SOCIAL_CIRCLE,306486.0,1.422209e+00,2.400931e+00,0.000000e+00,3.480000e+02
DEF_30_CNT_SOCIAL_CIRCLE,306486.0,1.434062e-01,4.466442e-01,0.000000e+00,3.400000e+01
OBS_60_CNT_SOCIAL_CIRCLE,306486.0,1.405255e+00,2.379744e+00,0.000000e+00,3.440000e+02
DEF_60_CNT_SOCIAL_CIRCLE,306486.0,1.000339e-01,3.622209e-01,0.000000e+00,2.400000e+01
DAYS_LAST_PHONE_CHANGE,307506.0,-9.628605e+02,8.268115e+02,-4.292000e+03,0.000000e+00
AMT_REQ_CREDIT_BUREAU_MON,265988.0,2.673880e-01,9.159935e-01,0.000000e+00,2.700000e+01
AMT_REQ_CREDIT_BUREAU_QRT,265988.0,2.654744e-01,7.940598e-01,0.000000e+00,2.610000e+02
AMT_REQ_CREDIT_BUREAU_YEAR,265988.0,1.899950e+00,1.869286e+00,0.000000e+00,2.500000e+01
NEW_DOC_IND_AVG,307507.0,4.650837e-02,1.721403e-02,0.000000e+00,2.000000e-01
NEW_DOC_IND_STD,307507.0,2.043187e-01,6.798007e-02,0.000000e+00,4.103913e-01
NEW_DOC_IND_KURT,307507.0,1.774286e+01,6.142166e+00,0.000000e+00,2.000000e+01
NEW_LIVE_IND_SUM,307507.0,4.001590e+00,1.152601e+00,1.000000e+00,8.000000e+00
NEW_LIVE_IND_STD,307507.0,5.106154e-01,3.554191e-02,0.000000e+00,5.345225e-01
NEW_LIVE_IND_KURT,307507.0,-1.863843e+00,1.644965e+00,-2.800000e+00,8.000000e+00
NEW_INC_BY_ORG,307507.0,1.460625e+05,1.901312e+04,1.125000e+05,2.250000e+05
NEW_CREDIT_TO_ANNUITY_RATIO,307495.0,2.161234e+01,7.823872e+00,8.036674e+00,4.530508e+01
NEW_CREDIT_TO_GOODS_RATIO,307229.0,1.122994e+00,1.240361e-01,1.500000e-01,6.000000e+00
NEW_INC_PER_CHLD,307507.0,1.395079e+05,1.458117e+05,3.000000e+03,5.850000e+07
NEW_EMPLOY_TO_BIRTH_RATIO,252133.0,1.568598e-01,1.335478e-01,-0.000000e+00,7.288115e-01
NEW_ANNUITY_TO_INCOME_RATIO,307495.0,1.809294e-01,9.457274e-02,2.238846e-04,1.875892e+00
NEW_SOURCES_PROD,109587.0,1.433162e-01,1.075981e-01,2.430332e-07,6.185571e-01
NEW_EXT_SOURCES_MEAN,307335.0,5.092519e-01,1.498026e-01,5.939651e-06,8.789034e-01
NEW_SCORES_STD,307507.0,1.512447e-01,9.372317e-02,3.538459e-07,6.519439e-01
NEW_CAR_TO_BIRTH_RATIO,104580.0,-8.528626e-04,9.531961e-04,-9.197493e-03,-0.000000e+00
NEW_CAR_TO_EMPLOY_RATIO,94411.0,-1.537780e-02,5.696050e-02,-1.150000e+01,-0.000000e+00
NEW_PHONE_TO_BIRTH_RATIO,307506.0,6.309270e-02,5.588899e-02,-0.000000e+00,3.613653e-01
NEW_PHONE_TO_EMPLOY_RATIO,252130.0,1.099098e+00,4.959104e+00,-0.000000e+00,1.784000e+03
NEW_CREDIT_TO_INCOME_RATIO,307507.0,3.957593e+00,2.689737e+00,4.807615e-03,8.473684e+01
BURO_DAYS_CREDIT_MIN,263487.0,-1.762373e+03,8.638676e+02,-2.922000e+03,0.000000e+00
BURO_DAYS_CREDIT_MAX,263487.0,-4.893032e+02,5.375763e+02,-2.922000e+03,0.000000e+00
BURO_DAYS_CREDIT_MEAN,263487.0,-1.083050e+03,5.633308e+02,-2.922000e+03,0.000000e+00
BURO_DAYS_CREDIT_VAR,227415.0,4.905173e+05,4.672358e+05,0.000000e+00,4.173160e+06
BURO_DAYS_CREDIT_ENDDATE_MIN,261238.0,-1.029577e+03,2.640358e+03,-4.206000e+04,3.119800e+04
BURO_DAYS_CREDIT_ENDDATE_MAX,261238.0,4.433092e+03,9.351005e+03,-4.187500e+04,3.119900e+04
BURO_DAYS_CREDIT_ENDDATE_MEAN,261238.0,6.518175e+02,3.281741e+03,-4.187500e+04,3.119800e+04
BURO_DAYS_CREDIT_UPDATE_MEAN,263487.0,-5.466347e+02,4.537506e+02,-4.189000e+04,1.400000e+01
BURO_AMT_CREDIT_MAX_OVERDUE_MEAN,183882.0,5.242460e+03,3.064116e+05,0.000000e+00,1.159872e+08
BURO_AMT_CREDIT_SUM_MAX,263486.0,9.760076e+05,2.087581e+06,0.000000e+00,3.960000e+08
BURO_AMT_CREDIT_SUM_MEAN,263486.0,3.780815e+05,8.916796e+05,0.000000e+00,1.980723e+08
BURO_AMT_CREDIT_SUM_SUM,263487.0,1.955797e+06,4.101754e+06,0.000000e+00,1.017958e+09
BURO_AMT_CREDIT_SUM_DEBT_MAX,256127.0,5.216271e+05,1.343234e+06,-2.595965e+04,1.701000e+08
BURO_AMT_CREDIT_SUM_DEBT_MEAN,256127.0,1.603902e+05,5.266539e+05,-1.083615e+06,4.365000e+07
BURO_AMT_CREDIT_SUM_DEBT_SUM,263487.0,6.406421e+05,1.633967e+06,-6.981558e+06,3.344983e+08
BURO_AMT_CREDIT_SUM_OVERDUE_MEAN,263487.0,4.954514e+01,5.291774e+03,0.000000e+00,1.617404e+06
BURO_AMT_CREDIT_SUM_LIMIT_MEAN,242438.0,5.901573e+03,3.009190e+04,-9.789166e+04,4.500000e+06
BURO_AMT_CREDIT_SUM_LIMIT_SUM,263487.0,2.356383e+04,1.001343e+05,-5.798541e+05,8.129328e+06
BURO_AMT_ANNUITY_MAX,80009.0,3.483845e+04,5.146613e+05,0.000000e+00,5.958668e+07
BURO_AMT_ANNUITY_MEAN,80009.0,1.605225e+04,1.705016e+05,0.000000e+00,2.728243e+07
BURO_MONTHS_BALANCE_MIN_MIN,92231.0,-5.648895e+01,2.785632e+01,-9.600000e+01,0.000000e+00
BURO_MONTHS_BALANCE_SIZE_MEAN,92231.0,2.747724e+01,1.682767e+01,1.000000e+00,9.700000e+01
BURO_MONTHS_BALANCE_SIZE_SUM,263487.0,5.579635e+01,1.210428e+02,0.000000e+00,2.657000e+03
BURO_STATUS_0_MEAN_MEAN,92231.0,4.571111e-01,2.564784e-01,0.000000e+00,1.000000e+00
BURO_STATUS_1_MEAN_MEAN,92231.0,1.419942e-02,4.168335e-02,0.000000e+00,8.333333e-01
BURO_STATUS_C_MEAN_MEAN,92231.0,3.302495e-01,2.629891e-01,0.000000e+00,1.000000e+00
BURO_STATUS_X_MEAN_MEAN,92231.0,1.945431e-01,2.296837e-01,0.000000e+00,1.000000e+00
BURO_CREDIT_ACTIVE_Active_MEAN,263487.0,4.129719e-01,3.084063e-01,0.000000e+00,1.000000e+00
BURO_CREDIT_ACTIVE_Closed_MEAN,263487.0,5.831126e-01,3.086819e-01,0.000000e+00,1.000000e+00
BURO_CREDIT_ACTIVE_Sold_MEAN,263487.0,3.903492e-03,3.841755e-02,0.000000e+00,1.000000e+00
BURO_CREDIT_TYPE_Another type of loan_MEAN,263487.0,7.302443e-04,1.791163e-02,0.000000e+00,1.000000e+00
BURO_CREDIT_TYPE_Car loan_MEAN,263487.0,1.987320e-02,9.438300e-02,0.000000e+00,1.000000e+00
BURO_CREDIT_TYPE_Consumer credit_MEAN,263487.0,7.195221e-01,2.771656e-01,0.000000e+00,1.000000e+00
BURO_CREDIT_TYPE_Credit card_MEAN,263487.0,2.396509e-01,2.572270e-01,0.000000e+00,1.000000e+00
BURO_CREDIT_TYPE_Microloan_MEAN,263487.0,4.207756e-03,4.623636e-02,0.000000e+00,1.000000e+00
BURO_CREDIT_TYPE_Mortgage_MEAN,263487.0,1.423314e-02,8.097391e-02,0.000000e+00,1.000000e+00
ACTIVE_DAYS_CREDIT_MIN,217146.0,-9.382117e+02,7.225827e+02,-2.922000e+03,0.000000e+00
ACTIVE_DAYS_CREDIT_MAX,217146.0,-4.169374e+02,4.710688e+02,-2.922000e+03,0.000000e+00
ACTIVE_DAYS_CREDIT_MEAN,217146.0,-6.507920e+02,4.957411e+02,-2.922000e+03,0.000000e+00
ACTIVE_DAYS_CREDIT_VAR,143043.0,3.072085e+05,5.100447e+05,0.000000e+00,4.193408e+06
ACTIVE_DAYS_CREDIT_ENDDATE_MIN,208183.0,1.011923e+03,4.687727e+03,-4.205600e+04,3.119800e+04
ACTIVE_DAYS_CREDIT_ENDDATE_MAX,208183.0,4.755245e+03,9.381727e+03,-4.187400e+04,3.119900e+04
ACTIVE_DAYS_CREDIT_ENDDATE_MEAN,208183.0,2.480912e+03,5.509171e+03,-4.187400e+04,3.119800e+04
ACTIVE_DAYS_CREDIT_UPDATE_MEAN,217146.0,-1.321970e+02,2.954517e+02,-4.191900e+04,3.720000e+02
ACTIVE_CREDIT_DAY_OVERDUE_MAX,217146.0,4.710738e+00,8.724848e+01,0.000000e+00,2.770000e+03
ACTIVE_AMT_CREDIT_MAX_OVERDUE_MEAN,116037.0,2.529067e+03,1.303874e+04,0.000000e+00,1.665490e+06
ACTIVE_AMT_CREDIT_SUM_MAX,217145.0,9.418875e+05,1.795551e+06,0.000000e+00,1.701000e+08
ACTIVE_AMT_CREDIT_SUM_MEAN,217145.0,5.640763e+05,1.112517e+06,0.000000e+00,9.003468e+07
ACTIVE_AMT_CREDIT_SUM_SUM,217146.0,1.311226e+06,2.365934e+06,0.000000e+00,3.347397e+08
ACTIVE_AMT_CREDIT_SUM_DEBT_MAX,206510.0,6.398985e+05,1.459973e+06,-6.710518e+05,1.701000e+08
ACTIVE_AMT_CREDIT_SUM_DEBT_MEAN,206510.0,3.771585e+05,9.400713e+05,-1.395766e+06,8.362458e+07
ACTIVE_AMT_CREDIT_SUM_DEBT_SUM,217146.0,7.650889e+05,1.753512e+06,-6.978830e+06,3.344983e+08
ACTIVE_AMT_CREDIT_SUM_OVERDUE_MEAN,217146.0,1.039569e+02,1.101986e+04,0.000000e+00,3.681063e+06
ACTIVE_AMT_CREDIT_SUM_LIMIT_MEAN,188724.0,1.282370e+04,5.287552e+04,-1.449635e+05,4.500000e+06
ACTIVE_AMT_CREDIT_SUM_LIMIT_SUM,217146.0,2.467934e+04,9.919268e+04,-5.798541e+05,8.126600e+06
ACTIVE_AMT_ANNUITY_MAX,61346.0,2.385203e+04,3.044438e+05,0.000000e+00,5.684498e+07
ACTIVE_AMT_ANNUITY_MEAN,61346.0,1.666951e+04,1.439565e+05,0.000000e+00,2.842249e+07
ACTIVE_MONTHS_BALANCE_MIN_MIN,76519.0,-2.945846e+01,2.246049e+01,-9.600000e+01,0.000000e+00
ACTIVE_MONTHS_BALANCE_MAX_MAX,76519.0,-9.438048e-01,5.579674e+00,-9.100000e+01,0.000000e+00
ACTIVE_MONTHS_BALANCE_SIZE_MEAN,76519.0,1.809577e+01,1.347983e+01,1.000000e+00,9.700000e+01
ACTIVE_MONTHS_BALANCE_SIZE_SUM,217146.0,1.617232e+01,3.439711e+01,0.000000e+00,7.700000e+02
CLOSED_DAYS_CREDIT_MIN,230161.0,-1.875810e+03,7.953731e+02,-2.922000e+03,-1.000000e+01
CLOSED_DAYS_CREDIT_MAX,230161.0,-9.074482e+02,6.413247e+02,-2.922000e+03,0.000000e+00
CLOSED_DAYS_CREDIT_MEAN,230161.0,-1.384164e+03,6.002727e+02,-2.922000e+03,-1.000000e+01
CLOSED_DAYS_CREDIT_VAR,176656.0,4.319623e+05,4.357628e+05,0.000000e+00,4.032800e+06
CLOSED_DAYS_CREDIT_ENDDATE_MIN,228639.0,-1.352084e+03,1.606555e+03,-4.206000e+04,3.119500e+04
CLOSED_DAYS_CREDIT_ENDDATE_MAX,228639.0,7.747538e+02,5.053042e+03,-4.187500e+04,3.119800e+04
CLOSED_DAYS_CREDIT_ENDDATE_MEAN,228639.0,-5.669365e+02,1.739057e+03,-4.187500e+04,3.119500e+04
CLOSED_DAYS_CREDIT_UPDATE_MEAN,230161.0,-8.273460e+02,5.340708e+02,-4.189000e+04,0.000000e+00
CLOSED_AMT_CREDIT_MAX_OVERDUE_MEAN,146537.0,6.126265e+03,4.025930e+05,0.000000e+00,1.159872e+08
CLOSED_AMT_CREDIT_SUM_MAX,230161.0,5.187473e+05,1.535172e+06,0.000000e+00,3.960000e+08
CLOSED_AMT_CREDIT_SUM_MEAN,230161.0,2.576510e+05,8.046250e+05,0.000000e+00,1.980723e+08
CLOSED_AMT_CREDIT_SUM_SUM,230161.0,9.757377e+05,3.164450e+06,0.000000e+00,1.017598e+09
CLOSED_AMT_CREDIT_SUM_DEBT_MAX,218329.0,9.313010e+03,1.269166e+05,-5.010390e+03,1.056498e+07
CLOSED_AMT_CREDIT_SUM_DEBT_MEAN,218329.0,2.739603e+03,5.146928e+04,-3.398117e+04,7.279290e+06
CLOSED_AMT_CREDIT_SUM_DEBT_SUM,230161.0,9.328342e+03,1.342253e+05,-4.561205e+05,1.786648e+07
CLOSED_AMT_ANNUITY_MAX,66009.0,2.921818e+04,4.898802e+05,0.000000e+00,5.958668e+07
CLOSED_AMT_ANNUITY_MEAN,66009.0,1.583601e+04,2.686457e+05,0.000000e+00,5.456266e+07
CLOSED_MONTHS_BALANCE_MIN_MIN,80735.0,-5.998370e+01,2.579333e+01,-9.600000e+01,0.000000e+00
CLOSED_MONTHS_BALANCE_SIZE_MEAN,80735.0,3.345759e+01,1.903177e+01,1.000000e+00,9.700000e+01
CLOSED_MONTHS_BALANCE_SIZE_SUM,230161.0,4.828269e+01,1.051034e+02,0.000000e+00,2.363000e+03
NEW_RATIO_BURO_DAYS_CREDIT_MIN,183996.0,6.223427e-01,9.784287e-01,7.044734e-04,1.512667e+02
NEW_RATIO_BURO_DAYS_CREDIT_MAX,183995.0,7.291820e-01,1.883470e+00,-0.000000e+00,2.880000e+02
NEW_RATIO_BURO_DAYS_CREDIT_MEAN,183996.0,5.644426e-01,7.982870e-01,7.044734e-04,1.512667e+02
NEW_RATIO_BURO_DAYS_CREDIT_VAR,107910.0,5.390104e+03,1.172586e+05,0.000000e+00,8.668824e+06
NEW_RATIO_BURO_DAYS_CREDIT_ENDDATE_MIN,175781.0,-1.983147e+00,5.827460e+01,-1.547450e+04,3.868375e+03
NEW_RATIO_BURO_DAYS_CREDIT_ENDDATE_MAX,175681.0,-1.594990e+01,4.808396e+02,-3.115600e+04,3.117800e+04
NEW_RATIO_BURO_DAYS_CREDIT_ENDDATE_MEAN,175779.0,-5.812150e+00,3.111275e+02,-7.863800e+04,4.070667e+04
NEW_RATIO_BURO_DAYS_CREDIT_UPDATE_MEAN,183989.0,2.806914e-01,4.489105e+00,-3.860924e-01,1.588500e+03
NEW_RATIO_BURO_AMT_CREDIT_MAX_OVERDUE_MEAN,30689.0,2.521500e+01,1.350871e+03,0.000000e+00,2.202480e+05
NEW_RATIO_BURO_AMT_CREDIT_SUM_MAX,182663.0,1.087160e+01,1.598332e+03,0.000000e+00,5.899710e+05
NEW_RATIO_BURO_AMT_CREDIT_SUM_MEAN,182663.0,9.906765e+00,1.560217e+03,0.000000e+00,5.899710e+05
NEW_RATIO_BURO_AMT_CREDIT_SUM_SUM,182663.0,1.087969e+01,1.642269e+03,0.000000e+00,5.899710e+05
NEW_RATIO_BURO_AMT_CREDIT_SUM_DEBT_MAX,4234.0,3.646527e+02,4.636535e+04,-1.342967e+06,1.659732e+06
NEW_RATIO_BURO_AMT_CREDIT_SUM_DEBT_SUM,6096.0,-2.986108e+04,7.449081e+05,-3.839460e+07,1.659732e+06
NEW_RATIO_BURO_AMT_CREDIT_SUM_LIMIT_MEAN,3601.0,4.163356e+02,1.018037e+04,-8.362281e+02,3.983456e+05
NEW_RATIO_BURO_AMT_ANNUITY_MAX,30996.0,7.226541e+00,5.072068e+02,0.000000e+00,7.817000e+04
NEW_RATIO_BURO_AMT_ANNUITY_MEAN,30996.0,5.995571e+00,3.278584e+02,0.000000e+00,3.908550e+04
NEW_RATIO_BURO_MONTHS_BALANCE_MIN_MIN,65063.0,6.170108e-01,9.354305e-01,-0.000000e+00,8.100000e+01
NEW_RATIO_BURO_MONTHS_BALANCE_SIZE_MEAN,65081.0,6.906284e-01,6.766183e-01,1.052632e-02,3.333333e+01
NEW_RATIO_BURO_MONTHS_BALANCE_SIZE_SUM,65098.0,7.297180e-01,1.599153e+00,0.000000e+00,1.580000e+02
PREV_AMT_ANNUITY_MIN,290636.0,7.864341e+03,7.488175e+03,0.000000e+00,3.004254e+05
PREV_AMT_ANNUITY_MAX,290636.0,2.372258e+04,1.916947e+04,0.000000e+00,4.180581e+05
PREV_AMT_ANNUITY_MEAN,290636.0,1.453203e+04,1.000754e+04,0.000000e+00,3.004254e+05
PREV_AMT_APPLICATION_MIN,291053.0,4.436149e+04,9.356891e+04,0.000000e+00,4.050000e+06
PREV_AMT_APPLICATION_MAX,291053.0,3.745851e+05,4.219936e+05,0.000000e+00,5.850000e+06
PREV_AMT_APPLICATION_MEAN,291053.0,1.540044e+05,1.532885e+05,0.000000e+00,4.050000e+06
PREV_AMT_CREDIT_MIN,291053.0,4.869127e+04,9.667470e+04,0.000000e+00,4.050000e+06
PREV_AMT_CREDIT_MAX,291053.0,4.138604e+05,4.575378e+05,0.000000e+00,4.509688e+06
PREV_AMT_CREDIT_MEAN,291053.0,1.700689e+05,1.657380e+05,0.000000e+00,4.050000e+06
PREV_APP_CREDIT_PERC_MIN,290826.0,7.916659e-01,3.523523e-01,0.000000e+00,5.000000e+00
PREV_APP_CREDIT_PERC_MAX,290825.0,1.113747e+00,3.076121e-01,0.000000e+00,2.000000e+01
PREV_APP_CREDIT_PERC_MEAN,290825.0,9.687523e-01,1.706354e-01,0.000000e+00,5.467110e+00
PREV_APP_CREDIT_PERC_VAR,229456.0,7.275849e-02,3.469978e-01,0.000000e+00,6.370194e+01
PREV_AMT_DOWN_PAYMENT_MIN,273601.0,3.961792e+03,1.587855e+04,-9.000000e-01,2.025000e+06
PREV_AMT_DOWN_PAYMENT_MAX,273601.0,1.168101e+04,2.860336e+04,0.000000e+00,3.060045e+06
PREV_AMT_DOWN_PAYMENT_MEAN,273601.0,7.080512e+03,1.842193e+04,-2.250000e-01,2.025000e+06
PREV_AMT_GOODS_PRICE_MIN,290078.0,7.941601e+04,1.104161e+05,0.000000e+00,4.050000e+06
PREV_AMT_GOODS_PRICE_MAX,290078.0,3.758743e+05,4.221510e+05,0.000000e+00,5.850000e+06
PREV_AMT_GOODS_PRICE_MEAN,290078.0,1.938949e+05,1.925771e+05,0.000000e+00,4.050000e+06
PREV_HOUR_APPR_PROCESS_START_MIN,291053.0,1.072828e+01,3.093190e+00,0.000000e+00,2.300000e+01
PREV_HOUR_APPR_PROCESS_START_MAX,291053.0,1.476833e+01,3.182885e+00,0.000000e+00,2.300000e+01
PREV_HOUR_APPR_PROCESS_START_MEAN,291053.0,1.266158e+01,2.775583e+00,0.000000e+00,2.300000e+01
PREV_RATE_DOWN_PAYMENT_MIN,273601.0,4.707799e-02,8.494277e-02,-1.497876e-05,9.897399e-01
PREV_RATE_DOWN_PAYMENT_MAX,273601.0,1.280012e-01,1.311089e-01,0.000000e+00,1.000000e+00
PREV_RATE_DOWN_PAYMENT_MEAN,273601.0,8.192414e-02,8.951778e-02,-7.489382e-06,9.897399e-01
PREV_DAYS_DECISION_MIN,291053.0,-1.539814e+03,8.646666e+02,-2.922000e+03,-2.000000e+00
PREV_DAYS_DECISION_MAX,291053.0,-4.808204e+02,5.401889e+02,-2.922000e+03,-1.000000e+00
PREV_DAYS_DECISION_MEAN,291053.0,-9.195762e+02,5.777696e+02,-2.922000e+03,-2.000000e+00
PREV_CNT_PAYMENT_MEAN,290638.0,1.453079e+01,8.419886e+00,0.000000e+00,7.200000e+01
PREV_CNT_PAYMENT_SUM,291053.0,6.102204e+01,7.430595e+01,0.000000e+00,1.788000e+03
PREV_NAME_CONTRACT_TYPE_Cash loans_MEAN,291053.0,3.170690e-01,3.201370e-01,0.000000e+00,1.000000e+00
PREV_NAME_CONTRACT_TYPE_Consumer loans_MEAN,291053.0,5.844888e-01,3.505270e-01,0.000000e+00,1.000000e+00
PREV_NAME_CONTRACT_TYPE_Revolving loans_MEAN,291053.0,9.826384e-02,1.696955e-01,0.000000e+00,1.000000e+00
PREV_WEEKDAY_APPR_PROCESS_START_FRIDAY_MEAN,291053.0,1.472899e-01,2.368835e-01,0.000000e+00,1.000000e+00
PREV_WEEKDAY_APPR_PROCESS_START_MONDAY_MEAN,291053.0,1.455341e-01,2.361257e-01,0.000000e+00,1.000000e+00
PREV_WEEKDAY_APPR_PROCESS_START_SATURDAY_MEAN,291053.0,1.540586e-01,2.507480e-01,0.000000e+00,1.000000e+00
PREV_WEEKDAY_APPR_PROCESS_START_SUNDAY_MEAN,291053.0,1.133483e-01,2.246673e-01,0.000000e+00,1.000000e+00
PREV_WEEKDAY_APPR_PROCESS_START_THURSDAY_MEAN,291053.0,1.451430e-01,2.358778e-01,0.000000e+00,1.000000e+00
PREV_WEEKDAY_APPR_PROCESS_START_TUESDAY_MEAN,291053.0,1.470010e-01,2.362057e-01,0.000000e+00,1.000000e+00
PREV_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_MEAN,291053.0,1.476250e-01,2.371757e-01,0.000000e+00,1.000000e+00
PREV_NAME_CASH_LOAN_PURPOSE_Car repairs_MEAN,291053.0,4.619992e-04,1.473508e-02,0.000000e+00,1.000000e+00
PREV_NAME_CASH_LOAN_PURPOSE_Medicine_MEAN,291053.0,1.129179e-03,2.250990e-02,0.000000e+00,1.000000e+00
PREV_NAME_CASH_LOAN_PURPOSE_Repairs_MEAN,291053.0,1.151860e-02,7.017423e-02,0.000000e+00,1.000000e+00

In [14]:
# Categorical Feature Statistics
cat_stats

                                                         value   count    pct
column                     rank
CODE_GENDER                1                                 F  202448  65.84
                           2                                 M  105059  34.16
EMERGENCYSTATE_MODE        1                                No  159425  51.84
                           2                              <NA>  145754  47.40
                           3                               Yes    2328   0.76
FLAG_DOCUMENT_18           1                                 0  305007  99.19
                           2                                 1    2500   0.81
FLAG_DOCUMENT_3            1                                 1  218340  71.00
                           2                                 0   89167  29.00
FLAG_DOCUMENT_8            1                                 0  282483  91.86
                           2                                 1   25024   8.14
FLAG_OWN_REALTY            1                                 Y  213308  69.37
                           2                                 N   94199  30.63
FLAG_PHONE                 1                                 0  221080  71.89
                           2                                 1   86427  28.11
FLAG_WORK_PHONE            1                                 0  246203  80.06
                           2                                 1   61304  19.94
FONDKAPREMONT_MODE         1                              <NA>  210293  68.39
                           2                  reg oper account   73829  24.01
                           3             reg oper spec account   12079   3.93
                           4                     not specified    5687   1.85
                           5                  org spec account    5619   1.83
HOUSETYPE_MODE             1                              <NA>  154296  50.18
                           2                    block of flats  150500  48.94
                           3                  specific housing    1499   0.49
                           4                    terraced house    1212   0.39
LIVE_CITY_NOT_WORK_CITY    1                                 0  252292  82.04
                           2                                 1   55215  17.96
NAME_CONTRACT_TYPE         1                        Cash loans  278232  90.48
                           2                   Revolving loans   29275   9.52
NAME_EDUCATION_TYPE        1     Secondary / secondary special  218389  71.02
                           2                  Higher education   74862  24.34
                           3                 Incomplete higher   10276   3.34
                           4                   Lower secondary    3816   1.24
                           5                   Academic degree     164   0.05
NAME_FAMILY_STATUS         1                           Married  196429  63.88
                           2              Single / not married   45444  14.78
                           3                    Civil marriage   29774   9.68
                           4                         Separated   19770   6.43
                           5                             Widow   16088   5.23
NAME_HOUSING_TYPE          1                 House / apartment  272865  88.73
                           2                      With parents   14840   4.83
                           3               Municipal apartment   11182   3.64
                           4                  Rented apartment    4881   1.59
                           5                  Office apartment    2617   0.85
NAME_INCOME_TYPE           1                           Working  158771  51.63
                           2              Commercial associate   71616  23.29
                           3                         Pensioner   55362  18.00
                           4                     State servant   21703   7.06
                           5                        Unemployed      22   0.01
NAME_TYPE_SUITE            1                     Unaccompanied  248523  80.82
                           2                            Family   40148  13.06
                           3                   Spouse, partner   11370   3.70
                           4                          Children    3267   1.06
                           5                           Other_B    1770   0.58
OCCUPATION_TYPE            1                              <NA>   96389  31.35
                           2                          Laborers   55186  17.95
                           3                       Sales staff   32102  10.44
                           4                        Core staff   27569   8.97
                           5                          Managers   21371   6.95
ORGANIZATION_TYPE          1            Business Entity Type 3   67992  22.11
                           2                               XNA   55374  18.01
                           3                     Self-employed   38412  12.49
                           4                             Other   16683   5.43
                           5                          Medicine   11192   3.64
REG_CITY_NOT_LIVE_CITY     1                                 0  283468  92.18
                           2                                 1   24039   7.82
TARGET                     1                                 0  282682  91.93
                           2                                 1   24825   8.07
WALLSMATERIAL_MODE         1                              <NA>  156340  50.84
                           2                             Panel   66039  21.48
                           3                      Stone, brick   64813  21.08
                           4                             Block    9253   3.01
                           5                            Wooden    5362   1.74
WEEKDAY_APPR_PROCESS_START 1                           TUESDAY   53900  17.53
                           2                         WEDNESDAY   51934  16.89
                           3                            MONDAY   50714  16.49
                           4                          THURSDAY   50590  16.45
                           5                            FRIDAY   50336  16.37

In [15]:
# Target Distribution
target_df

         count    pct
TARGET
0       282682  91.93
1        24825   8.07

## Task Curation

In [16]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [17]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [18]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...

Saving curated container to home_credit_default_risk/019d736d-6a16-7087-999b-e953d48f7516

019d736d-6a16-7087-999b-e953d48f7516
617c029f4d1c721d1f71666f8cf191ea1cbf13e22f9cf65ae036d5a7d12906f8