### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="clock_protein_period",
    dataset_year="2021",
    domain_str="biology & life sciences",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C5B31D",
    download_description="""
We download the data from the UCI repository and uzip it to a predefined folder. 

mkdir -p local-data-warehouse/clock_protein_period && wget -P local-data-warehouse/clock_protein_period/ https://archive.ics.uci.edu/static/public/729/period+changer-2.zip && unzip local-data-warehouse/clock_protein_period/period+changer-2.zip -d local-data-warehouse/clock_protein_period/ && rm local-data-warehouse/clock_protein_period/period+changer-2.zip
""",
    # References
    academic_reference_bibtex="""@article{Gul2021StructureBasedDC,
  title={Structure-based design and classifications of small molecules regulating the circadian rhythm period},
  author={Sadia Gul and Fatima Rahim and Selen Isin and others},
  journal={Scientific Reports},
  year={2021},
  volume={11},
  pages={18510},
  doi={10.1038/s41598-021-97962-5},
  url={https://doi.org/10.1038/s41598-021-97962-5}
}
""",
    academic_reference_bibtex_key="Gul2021StructureBasedDC",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
    - We remove duplicated columns but keep the first occurrence.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="PeriodChanger",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="PeriodChanger",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(dataset_mold.path / "data.csv")

target_feature = "PeriodChanger"
df = df.rename(columns={"Class": target_feature})
df[target_feature] = df[target_feature].map({"Changer": "Yes", "NoChanger": "No"}).astype("category")

duplicated_mask = df.T.duplicated(keep='first')
df = df.drop(columns = df.columns[duplicated_mask])

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 90
Columns: 1092
Use sampling: False (sample size: 90)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['SpAbs_Dzi', 'MATS8m', 'VR2_Dzm', 'VR2_Dzp', 'ATS5e', 'DELS', 'ETA_Eta_F', 'ATS5m', 'ATS5p', 'ATS5s']
Rows remaining as candidates after top-10 filter: 0 (of 90)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,MATS3v,nHBint10,MATS3s,MATS3p,nHBDon_Lipinski,minHBint8,MATS3e,MATS3c,minHBint2,MATS3m,minHBint6,minHBint7,minHBint4,MATS3i,VR3_Dt,SpMax8_Bhi,SdsN,SpMax8_Bhm,SpMax8_Bhe,ECCEN,MDEC-14,SpMax8_Bhs,SpMax8_Bhp,SpMax8_Bhv,MDEC-11,MDEC-12,MDEC-13,VR2_Dt,BIC5,ATS7s,ATS7p,ATS7v,ATS7i,ATS7m,ATS7e,mintN,nHsNH2,khs.sssCH,minHBint3,maxdssC,nT6Ring,minHBint5,nF8Ring,minssCH2,SpMax_DzZ,ETA_EtaP,nHsOH,SpMin1_Bhe,maxHother,nHBAcc_Lipinski,StN,khs.aaS,khs.aaO,khs.aaN,Sare,SHAvin,SpMax3_Bhv,SpMax3_Bhp,SpMax3_Bhs,SpMax3_Bhe,SpMin6_Bhi,SpMax3_Bhm,SpMax3_Bhi,ETA_EtaP_F_L,AATSC2e,AATSC2c,AATSC2m,AATSC2i,nsBr,AATS5p,AATSC2v,AATSC2p,AATSC2s,VABC,maxdNH,khs.ddsN,RotBtFrac,ATS4e,ATS4m,nFRing,ATS4i,ATS4s,ATS4p,ETA_Alpha,khs.sssN,EE_Dzi,MAXDN,EE_Dzm,EE_Dze,EE_Dzs,EE_Dzp,EE_Dzv,ATS8e,maxsOH,minssssNp,maxsOm,MDEC-23,MDEC-22,MDEC-24,nFG12HeteroRing,ATS8s,ATS8v,SP-6,SP-7,SHsNH2,SP-5,SP-2,SP-3,SP-0,SP-1,minHsOH,ATSC8v,MATS2v,ATSC8s,MATS2p,MATS2s,ATSC8p,MATS2e,ATSC8e,ATSC8c,MATS2c,MATS2m,topoDiameter,ATSC8m,MATS2i,ATSC8i,ntN,khs.ssCH2,SpAD_Dt,ETA_Eta_R_L,SHdsCH,SaasN,SC-4,SaasC,minaaCH,AATSC3c,AATSC3e,AATSC3i,AATSC3m,AATSC3s,AATSC3p,AATSC3v,SpMax2_Bhp,AATS8e,AATS8i,AATS8m,AATS8s,AATS8p,AATS8v,VE3_Dt,XLogP,SpMax2_Bhi,maxssCH2,minaaS,SpMax4_Bhv,SpMax4_Bhs,SpMax4_Bhp,SpMax4_Bhm,minHaaNH,SpMax4_Bhi,minaaN,SpMax4_Bhe,StsC,SssCH2,maxHdNH,MATS1p,R_TpiPCTPC,MATS1s,MATS1v,JGI10,MATS1c,MATS1e,VR2_DzZ,MATS1i,MATS1m,MDEC-34,MDEC-33,VR2_Dze,VR2_Dzm,VR2_Dzs,VR2_Dzp,khs.ssssC,nTG12Ring,khs.ssssN,ATS5e,gmin,VR2_D,ATS5m,ATS5p,ATS5s,ATS5v,AATSC5p,TpiPC,maxsCH3,khs.ssO,ETA_Eta_F_L,khs.ssS,SdO,VE2_Dt,ETA_dEpsilon_B,ETA_dEpsilon_A,ETA_dEpsilon_D,SsNH2,SsCH3,CIC5,CIC4,CIC1,CIC0,CIC3,CIC2,nF10HeteroRing,maxssO,WPOL,n5HeteroRing,maxHAvin,fragC,ETA_Eta_B_RC,AATS7m,SpDiam_Dt,SdssC,ETA_Epsilon_3,AATS7i,AATS7e,nT9Ring,minsCl,AATS7v,AATS7s,AATS7p,ETA_Epsilon_5,ETA_Epsilon_4,SsssCH,maxHsOH,GATS1v,maxaaaC,GATS1s,BIC4,SpMin7_Bhs,SpMin7_Bhp,SpMin7_Bhv,GATS1e,mintsC,GATS1c,SpMin7_Bhm,GATS1m,SpMin7_Bhe,GATS1i,maxtsC,minHAvin,AATS2v,SPC-6,SPC-4,SPC-5,SpAD_D,MATS6c,ETA_BetaP_s,minaasC,minaasN,minssNH,nT7HeteroRing,RotBFrac,nF10Ring,ETA_BetaP_ns,nH,nL,nN,nO,nA,nC,nF,nX,nQ,nS,nV,ATS1m,mindsN,SHCsats,SHCsatu,CrippenMR,GATS1p,SRW10,ETA_dPsi_A,AATS6m,AATS6i,AATS6e,minsBr,nF9HeteroRing,SpMin7_Bhi,AATS6v,AATS6p,AATS6s,naAromAtom,nBase,minHBint10,SpDiam_DzZ,SaaNH,khs.dNH,maxaaN,maxaaO,SpDiam_Dzv,SpDiam_Dzs,SpDiam_Dzp,SpDiam_Dze,SpDiam_Dzm,GATS6i,SpDiam_Dzi,Mi,Mv,Mp,GGI10,bpol,MW,GATS6v,MATS7s,MATS7p,MATS7v,MATS7i,MATS7m,MATS7c,GATS6s,MATS7e,maxtN,SpMin8_Bhe,SpMin8_Bhi,SpMin8_Bhm,SpMin8_Bhp,SpMin8_Bhs,SpMin8_Bhv,maxHCsatu,maxHCsats,ATSC3v,ATSC3s,ATSC3p,ATSC3e,ATSC3c,maxssNH,ATSC3m,ATSC3i,minHCsatu,minHCsats,SpMax7_Bhe,SpMax7_Bhi,SpMax7_Bhm,ETA_BetaP_ns_d,SpMax7_Bhp,SpMax7_Bhs,SpMax7_Bhv,SdsCH,minssO,minssS,SpMin3_Bhe,SpMin3_Bhm,SpMin3_Bhi,SpMin3_Bhv,SpMin3_Bhs,SpMin3_Bhp,TPC,VP-5,VP-4,VP-7,VP-6,VP-1,VP-0,VP-3,VP-2,MIC5,MIC4,MIC3,MIC2,MIC1,MIC0,ATSC5p,piPC10,ATSC5s,minsOm,nHBa,nHBd,SddssS,nCl,minsOH,SHaaCH,nF11HeteroRing,AATS5i,AATS5m,SpMin6_Bhs,SpMin6_Bhp,SpMin6_Bhv,AATS5e,ETA_dBeta,khs.sCH3,ALogP,SpMin6_Bhm,BCUTp-1l,AATS5s,BCUTp-1h,AATS5v,SpMin6_Bhe,ATS8i,ATS8m,BCUTw-1h,BCUTw-1l,nBondsS3,nBondsS2,ATS8p,GATS3p,GATS3s,GATS3v,GATS3c,GATS3e,SC-5,GATS3i,SC-6,GATS3m,SC-3,minsCH3,SssssC,nAtomLC,nT12HeteroRing,minHaaCH,MLFER_BH,MLFER_BO,SaaaC,mindsCH,nddssS,maxaasC,maxsssN,MATS6p,MATS6s,MATS6v,MATS6i,MATS6m,MATS6e,ETA_Beta_ns_d,hmax,ETA_Beta_s,nHaaCH,khs.aaaC,ETA_AlphaP,nAromBond,ATSC2v,ATSC2p,ATSC2s,ATS4v,ATSC2e,ATSC2c,ATSC2m,ATSC2i,AATS4v,AATS4s,AATS4p,AATS4e,ETA_BetaP,AATS4m,AATS4i,SHsOH,SpMax_D,MDEN-13,MDEN-12,MDEN-11,ATS3m,PetitjeanNumber,khs.aasN,khs.aasC,MWC10,MPC7,TWC,topoRadius,WPATH,nG,ndsN,MAXDP,naaaC,SM1_DzZ,SpAbs_DzZ,SpAbs_Dze,khs.aaNH,SpAbs_Dzm,SM1_Dzv,SpAbs_Dzi,SM1_Dzp,SM1_Dzs,SM1_Dzm,SpAbs_Dzv,SM1_Dzi,SpAbs_Dzp,SpAbs_Dzs,SM1_Dze,maxaaCH,maxdO,nF11Ring,GATS2v,GATS2s,ETA_Beta,GATS2m,GATS2i,GATS2e,GATS2c,nHaaNH,ATSC1p,ATSC1s,ATSC1v,ATSC1c,ATSC1e,ATSC1i,ATSC1m,MWC9,MWC8,MWC5,MWC4,MWC7,MWC6,ndssC,MWC2,MAXDN2,MATS5e,SpMin2_Bhe,MATS5c,MATS5m,SpMin2_Bhm,MATS5i,SpMin2_Bhi,SpMin2_Bhv,MATS5v,MATS5p,SpMin2_Bhs,SpMin2_Bhp,VE1_Dzi,Mare,BCUTc-1l,BCUTc-1h,SssNH,MPC9,VE1_Dzp,naaN,SHBd,TSRW,SHBa,khs.ssNH,SpMax6_Bhp,SpMax6_Bhs,SpMAD_Dzv,SpMax6_Bhv,SpMax6_Bhe,SpMAD_Dze,SpMax6_Bhi,SpMAD_Dzi,SpMax6_Bhm,SpMAD_Dzm,SpMAD_DzZ,AATSC8s,AATSC8p,AATSC8v,minHssNH,AATSC8c,AATSC8e,AATSC8i,AATSC8m,AATS3s,AATS3p,AATS3v,SpMin5_Bhv,SpMin5_Bhp,SpMin5_Bhs,SpMin5_Bhm,SpMin5_Bhi,AATS3e,SpMin5_Bhe,AATS3i,SpMAD_Dzs,AATS3m,MLFER_L,GATS5s,GATS5p,GATS5v,MLFER_A,GATS5i,GATS5m,IC3,IC2,IC1,IC0,IC5,IC4,ETA_Eta_R,ETA_Eta_L,ETA_Eta_B,ETA_Eta_F,SaaCH,nAcid,maxsssCH,nF6Ring,maxsF,MATS4c,MATS4e,MATS4i,SP-4,MATS4m,MATS4s,MATS4p,MATS4v,VC-6,SsssN,minaaaC,minwHBa,nT6HeteroRing,khs.dssC,AATSC0m,EE_Dt,ATSC0v,ATSC0s,ATSC0p,ATSC0m,ATSC0i,ATSC0e,ATSC0c,VE2_D,SpMAD_D,nHBint2,nHBint3,ETA_Epsilon_1,nHBint6,nHBint7,nHBint4,nHBint5,nHBint8,nHBint9,nBondsS,AATS2p,AATS2s,AATS2e,nBondsD,AATS2i,AATS2m,nBondsM,nBonds2,MDEN-33,Sp,Sv,Si,FMF,nRotB,SwHBa,Zagreb,SRW6,SRW7,SRW4,SRW5,SRW2,SRW8,SRW9,SCH-5,SCH-6,SCH-7,ATS6p,maxaasN,MAXDP2,VE1_DzZ,VE1_Dze,GATS4p,GATS4s,VE1_Dzm,GATS4v,GATS4i,VE1_Dzs,GATS4m,ndsCH,VE1_Dzv,GATS4c,GATS4e,ETA_Beta_ns,McGowan_Volume,n5Ring,ETA_dAlpha_B,ATSC7s,ATSC7p,ETA_dAlpha_A,ATSC7v,ATSC7i,ATSC7m,ATSC7c,VC-4,VC-5,VC-3,ATSC7e,JGI2,JGI3,JGI1,JGI6,JGI7,JGI4,JGI5,JGI8,JGI9,SpAD_DzZ,SpAD_Dze,SpAD_Dzm,SpAD_Dzi,SpAD_Dzv,SpAD_Dzp,SpAD_Dzs,nBonds,LipinskiFailures,SpDiam_D,minHdsCH,SssO,C2SP3,C2SP2,GATS2p,ETA_Shape_X,ETA_Shape_Y,ETA_Shape_P,AVP-5,AVP-4,AVP-7,AVP-1,AVP-0,AVP-2,AATS1v,AATS1p,AATS1s,AATS1m,MDEN-22,AATS1i,AATS1e,maxaaNH,GATS7c,GATS7m,GATS7v,GATS7p,GATS7s,SsOm,SsOH,AATSC4v,maxHBd,AATSC4s,maxHBa,SHssNH,AATSC4e,AATSC4c,AATSC4m,AATSC4i,SHBint10,ATS2v,ATS2p,ATS2s,CrippenLogP,ATS2i,JGT,MPC10,VAdjMat,ATSC6p,ATSC6s,ATSC6v,ATSC6i,ATSC6m,ATSC6c,ATSC6e,SpMin1_Bhi,SpMin1_Bhm,SpMin1_Bhp,SpMin1_Bhs,SpMin1_Bhv,SHother,AATS0s,SpMin4_Bhv,AATS0p,SpMin4_Bhp,AATS0v,SpMin4_Bhs,SpMin4_Bhm,AATS0i,SpMin4_Bhi,AATS0m,minsssCH,SpMin4_Bhe,nAtomLAC,AATS0e,MWC3,ATSC5v,MLFER_S,ETA_dBetaP,AATSC4p,nRotBt,SHaaNH,AATSC5v,AATSC5s,AATSC5e,naasN,AATSC5c,AATSC5m,SpMax_Dt,AATSC5i,naasC,VR3_D,VR1_D,VR1_Dt,ETA_Epsilon_2,MLogP,nHBAcc2,nHBAcc3,AMR,AMW,GATS6c,sumI,GATS6e,gmax,maxHssNH,MATS5s,GATS6m,maxHBint8,maxHBint9,GATS6p,C1SP2,C1SP3,maxHBint2,maxHBint3,maxHBint4,maxHBint5,maxHBint6,maxHBint7,AVP-6,ATSC5e,C4SP3,AVP-3,ATSC5c,ATSC5m,nHother,ATSC5i,VCH-5,VCH-7,VCH-6,Mse,DELS2,MATS8m,ATS3v,ATS3s,ATS3p,ATS3e,MATS8i,Kier2,Kier3,Kier1,HybRatio,ATS3i,MDEN-23,SHBint9,SHBint8,SHBint3,SHBint2,SHBint7,SHBint6,SHBint5,SHBint4,DELS,nHeteroRing,GATS7e,ETA_Psi_1,mindssC,nwHBa,maxHBint10,GATS7i,nAtom,Spe,khs.dO,maxwHBa,AATSC6p,AATSC6s,AATSC6v,AATSC6c,AATSC6e,AATSC6i,AATSC6m,SssssNp,AATSC7c,ASP-2,ASP-3,ASP-0,ASP-1,ASP-6,ASP-7,ASP-4,ASP-5,ATS0s,MATS8v,ATS0p,MATS8s,ATS0v,MATS8p,MATS8e,MATS8c,ATS0e,ATS0i,ATS0m,GGI9,GGI8,GGI1,GGI3,GGI2,GGI5,GGI4,GGI7,GGI6,nTRing,TIC0,TIC1,TIC2,TIC3,TIC4,TIC5,ZMIC4,ZMIC5,ZMIC0,ZMIC1,ZMIC2,ZMIC3,minHother,ATSC4c,ATSC4e,ATSC4i,ATSC4m,ATSC4s,ATSC4p,ATSC4v,SpMax1_Bhs,SpMax1_Bhp,SpMax1_Bhv,hmin,SpMax1_Bhe,SpMax1_Bhi,SpMax1_Bhm,MPC6,nAtomP,MPC4,MPC5,MPC2,VR3_Dzv,VR3_Dzs,MPC8,VR3_Dzp,VR3_Dzm,SpMAD_Dzp,VR3_Dzi,VR3_Dze,SsF,minaaO,VR3_DzZ,Sse,C3SP2,VR1_DzZ,VR1_Dzp,VR1_Dzs,VR1_Dzi,VR1_Dzm,VR1_Dze,maxdsN,AATSC7v,AATSC7s,AATSC7p,AATSC7m,AATSC7i,AATSC7e,BIC2,BIC3,BIC0,BIC1,SIC5,SIC4,SIC1,SIC0,SIC3,SIC2,minHBd,minHBa,AATSC1p,AATSC0i,ALogp2,AATSC1i,SaaO,SaaN,GATS8m,SpMax2_Bhv,GATS8i,SpMax2_Bhs,GATS8e,GATS8c,SpMax2_Bhe,SpMax2_Bhm,GATS8v,GATS8p,GATS8s,piPC3,piPC2,piPC1,piPC7,piPC6,piPC5,piPC4,piPC9,piPC8,maxHdsCH,ATS1v,ATS1p,ATS1s,ATS1i,SpMAD_Dt,ATS1e,VR2_Dzi,MPC3,ATS2e,VR2_Dzv,minHBint9,VE2_Dzs,VE2_Dzp,VE2_Dzv,ATS2m,VE2_Dzi,VE2_Dzm,VE2_Dze,VE2_DzZ,nHAvin,meanI,nHCsatu,nHCsats,apol,ATS5i,nF12Ring,mindO,maxdsCH,TopoPSA,ETA_EtaP_B_RC,MDEO-11,MDEO-12,AATSC0s,SpMax5_Bhv,AATSC0p,SpMax5_Bhs,AATSC0v,SpMax5_Bhp,SpMax5_Bhm,SpMax5_Bhi,AATSC0c,SpMax5_Bhe,AATSC0e,VE3_DzZ,C3SP3,VE3_Dzv,ATS6s,VE3_Dzs,VE3_Dzp,ATS6v,ATS6i,VE3_Dzm,ATS6m,VE3_Dzi,VE3_Dze,ATS6e,VPC-6,VPC-5,VPC-4,MLFER_E,nBondsD2,Mpe,nHeavyAtom,nRing,GATS5c,GATS5e,VR1_Dzv,minsssN,topoShape,VE1_Dt,maxHaaCH,nHBAcc,VE3_D,VE1_D,AATSC1s,AATSC1v,AATSC1m,AATSC1c,AATSC1e,LipoaffinityIndex,n6Ring,ETA_Eta,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,ETA_EtaP_L,ETA_EtaP_F,ETA_EtaP_B,ETA_dEpsilon_C,MDEO-22,PeriodChanger
0,0.0908,0,0.0075,0.0173,0,0.0,-0.0436,0.0409,0.0,0.1368,0.0,0.0000,0.0,-0.0574,31.8800,3.3540,0.0000,3.2664,3.3158,1422,0.0,3.8373,3.2044,3.2128,0.0000,0.0000,0.0000,22.2380,0.8435,768.4444,275.1928,41003.7141,24110.8860,15270.4651,1277.0737,0.0000,0,0,0.0,0.0000,0,0.0,0,0.0,201.0744,0.8169,0,2.2798,0.0000,8,0.0000,0,0,0,60.832,0.0000,3.9710,3.9582,4.6723,4.0541,1.5761,4.0396,4.0792,0.3114,0.0076,0.0007,0.6986,0.0196,0,1.9081,-0.8911,-0.0033,-0.0255,451.4722,0.0,0,0.0000,1453.5938,19835.8193,0,26862.1417,759.7778,347.5541,21.9333,0,198.0675,0.0000,201.0915,201.1842,213.9751,232.9974,222.2215,1094.3304,0.0000,0.0,0.0,60.1757,13.9880,0.0,0,554.0000,35648.5015,18.2418,16.2633,0.0,20.9413,22.2081,22.3620,30.3248,22.5080,0.0000,237.1491,-0.0231,-0.6667,-0.0166,-0.0129,-0.2969,0.1073,0.0573,0.1053,0.0481,0.0281,17,384.1820,0.0129,-13.8718,0,0,3444.0152,22.5079,0.0000,0.0,0.0,0.0000,0.0000,0.0006,-0.0031,-0.0868,3.4021,0.0149,0.0034,3.5086,4.1095,7.8166,149.5621,92.9158,3.9571,1.7139,254.6322,-167.1241,-0.094,4.2285,0.0,0.0,3.8192,4.6641,3.8195,3.8311,0.0,3.8758,0.0000,3.8599,0.0000,0.0,0.0,0.0049,20.3566,-0.0388,0.0255,0.0063,-0.4760,-0.0226,25.3775,-0.0816,0.0440,0.0,0.0000,25.3702,25.3764,43.3885,24.5288,0,0,0,1408.5019,0.0000,34.7634,18932.5551,339.6464,734.3333,51592.2938,-0.0198,12.0215,0.0000,0,14.3222,0,0.0000,0.0000,0.1391,0.2258,0.0000,0.0,0.0000,0.3333,0.3000,3.0318,4.4787,0.8667,2.0135,0,0.000,116,0,0.0000,1179.08,1.4381,94.8476,1814.8151,0.0000,0.4586,149.7571,7.9321,0,0.0,254.6815,4.7729,1.7093,0.8015,0.5454,0.0,0.0000,0.6341,0.0000,0.4793,0.8486,1.3331,1.4748,1.4774,0.5505,0.0000,1.2841,1.4670,0.5007,1.3636,0.9429,0.0000,0.000,328.8105,39.5531,11.4364,22.4183,581.0425,-0.0902,0.6957,0.0000,0.0,0.0,0,0.0000,0,0.9565,14,0,4,4,0,38,0,0,0,0,0,8823.8932,0.0000,0.0,0.0,0.0000,0.7123,11.4843,0.1194,101.4081,146.8943,7.9652,0.0,0,1.3448,270.7278,1.7912,4.6957,38,-1,0.0,296.0059,0.0,0,0.0000,0.0000,322.7435,319.6259,336.0904,296.1456,296.0272,1.0554,292.0703,7.2942,0.7947,0.8024,0.3406,25.7369,590.1015,1.0713,0.1647,0.0333,-0.0006,-0.0066,0.0473,0.1148,1.3061,0.2220,0.0000,1.3061,1.2720,1.3491,1.4567,1.3022,1.4359,0.0,0.0,575.4060,2.4444,0.5603,-0.5069,0.0919,0.0,557.9458,-14.2345,0.0,0.0,3.4009,3.4171,3.3582,0.0000,3.3048,3.9738,3.3124,0.0000,0.000,0.0,1.8776,1.9542,1.8540,1.9645,1.8650,1.9655,8169,6.8704,8.4524,3.7561,4.9553,14.9333,23.5048,10.2643,12.3024,54.9937,55.3273,51.3250,43.2973,30.8117,13.3151,-3.5162,11.3293,-36.3333,0.0,0,0,0.0,0,0.0000,0.0000,0,145.1083,106.3627,1.5355,1.6851,1.6695,7.9129,12.00,0,0.0000,1.6425,6.0583,4.1255,12.9486,289.8443,1.5809,20938.6998,13008.2055,15.9980,11.8500,8,22,239.9415,0.8415,0.7303,0.7413,0.9107,0.8248,1.5764,0.9982,0.0,0.6471,3.6250,0.0000,0.0,0,0,0.0000,0.000,0.000,0.0000,0.0000,0,0.0000,0.0000,-0.1490,0.0338,-0.1505,-0.1327,-0.0799,0.0522,0.0,0.0000,32.00,0,0,0.4768,45,-108.7165,-0.3998,-3.1111,53189.5532,0.9281,0.0803,85.2306,2.3875,292.2503,4.1746,1.9096,7.9868,1.6522,108.9880,147.5942,0.0000,290.5212,0.0000,0.0000,0.0000,18480.9749,0.4706,0,0,13.6498,863,190.0101,9,6433,0,0,0.0000,0,1.5714,407.0386,407.2647,0,407.0756,-2.8733,401.3850,-6.4019,3.7003,1.5671,453.4003,1.5935,478.6676,436.9364,1.5550,0.0000,0.0000,0,0.7155,0.5235,76.00,0.5750,0.9010,0.5026,0.7545,0,0.0691,-5.4444,70.0473,-0.4627,-0.1138,-8.7604,77.6923,12.6504,11.6523,8.6654,7.6755,10.6549,9.6596,0,5.7137,0.0000,-0.1483,2.0535,-0.0829,-0.1063,2.0784,-0.0509,2.0423,2.1124,-0.0865,-0.0998,2.0764,2.1249,0.0337,1.0139,-0.2886,0.2461,0.0,1857,0.0560,0,0.0000,11.6829,0.0000,0,3.5115,4.1131,9.8375,3.5121,3.5675,8.8774,3.5848,8.7486,3.5302,8.8734,8.8727,-0.0048,-0.0021,1.6939,0.0,0.0008,0.0004,-0.0991,2.7442,3.7710,1.9991,304.0993,1.7577,1.7830,1.6544,1.6838,1.6427,7.8189,1.6609,144.2227,9.5199,112.6889,0.000,1.2088,1.0033,0.9343,0.000,0.9706,0.9430,5.0402,3.8933,2.8751,1.4282,5.5736,5.6069,108.8196,8.1857,0.4061,71.2436,0.0000,-1,0.0,0,0.0,0.0139,-0.1538,0.1338,21.7757,-0.0798,-0.0969,0.0788,0.0508,0.0,0.0000,0.0000,0.0000,0,0,24.8725,709.7827,2318.1149,118.6667,11.8713,1492.3506,90.7490,4.2547,0.8214,0.0000,12.6314,0,0,0.6844,0,0,0,0,0,0,49,2.1667,3.5811,7.8186,22,140.9233,121.1999,49,71,0.0909,48.1456,47.6838,437.6516,0.0000,0,0.0000,302,7.8675,5.5334,6.1964,3.0445,4.7449,9.6454,7.7736,0.1571,0.9203,2.1607,315.2451,0.0,0.0000,0.0363,0.0363,0.8112,1.1874,0.0363,0.7761,0.8813,0.0519,0.9191,0,0.0502,1.1078,1.2503,44.0,0.0000,0,0.0232,52.4444,1.0601,0.0,-3.6343,-1.6116,189.4998,0.2531,0.0,0.4500,1.6157,2.5341,0.0615,0.0427,0.1053,0.0206,0.0144,0.0498,0.0235,0.0121,0.0092,408.1438,408.3601,408.1779,402.4356,452.5259,476.7291,437.9165,57,0,426.7978,0.000,0.000,0,20,0.7623,0.0,0.5836,0.0608,0.0170,0.0333,0.0044,0.2620,0.5110,0.1309,341.3882,2.2428,3.5290,124.2802,0.0909,138.6737,7.7709,0.0,0.9371,1.0249,1.0345,1.0152,1.1557,0.0,0.0000,1.9637,0.0000,-0.1917,0.0000,0.0,-0.0109,0.0002,-1.9843,0.2023,0.0,40114.8749,264.3407,436.8889,0.0000,17192.6451,0.3674,2576,6.5236,-5.1902,11.7778,-1023.5362,-35.3276,-349.9540,-0.2175,0.6513,2.2764,2.2945,2.3139,2.3109,2.3083,0.0000,5.9778,1.9476,1.9936,1.9431,306.1272,1.8476,1.9460,149.8966,1.8440,121.7486,0.0,1.8672,0,7.9135,6.6884,-594.7517,0.000,0.2609,0.0156,0,0.0,-3.3413,-0.2041,-0.0105,0,-0.0011,-2.6427,1722.0076,-0.0771,0,33.9352,1.599117e+03,1.022946e+03,0.8015,4.76,6,6,0.0000,9.8350,1.2051,0.0000,1.1754,0.0000,0.0,-0.1032,1.0236,0.0,0.0000,1.1226,4,0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0085,-1.8717,0,0.0658,-0.2019,-470.4030,0,-13.7157,0.0500,0.5730,0.3002,1.0198,0.0000,0.1103,49872.2846,618.4444,327.8598,1282.2958,-0.0655,9.8597,3.4208,28.6704,0.0000,23652.5257,0.8528,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0000,0,1.0079,0.5949,0.0000,0,0.0,0.9751,60,60.2431,0,0.0000,-0.0295,0.0669,-5.8155,-0.0012,0.0037,-0.2007,-1.9884,0.0,0.0016,0.2363,0.1433,0.6592,0.3949,0.0313,0.0188,0.0857,0.0518,358.6667,0.0438,119.6156,-0.0024,18367.6345,-0.0107,0.0058,0.0549,474.8115,8993.7981,7304.9177,0.5950,0.9458,6.0,4.9583,5.7778,2.7300,6.0711,1.3005,2.1860,0,85.6892,172.5045,233.6007,302.4134,336.4134,334.4134,35.3312,35.9824,117.6403,111.8885,67.0118,44.6829,0.0000,0.0347,-1.9853,36.8197,-361.1360,-34.8889,2.8374,357.4015,4.7297,4.2811,4.2858,0.0000,4.3204,4.3305,4.3132,582,46,254,404,94,32.3486,34.9546,1280,32.3310,32.4873,10.3637,32.5303,32.4862,0.0,0.0000,32.4875,61.1901,14,1.167367e+03,1.128324e+03,1995.8719,1.178276e+03,1.167316e+03,1.167030e+03,0.0000,-0.0226,0.3257,0.0066,1.1770,-0.0100,0.0157,0.5892,0.7628,0.2161,0.4351,0.9436,0.9492,0.4867,0.2418,0.8533,0.6591,0.0000,0.0000,0.0010,1.5125,0.0000,-0.1234,0.0000,0.0000,0.9661,4.1222,1.0458,4.6961,1.0229,0.9193,4.2017,4.1919,1.0201,1.0536,1.0575,6.1361,5.2653,4.4368,9.2281,8.4940,7.7915,6.9825,10.6613,9.9550,0.0000,24238.5612,159.2397,250.5556,9845.8296,74.8699,551.7318,25.6147,156,953.8683,24.6225,0.0000,0.0011,0.0012,0.0011,14786.3920,0.0007,0.0008,0.0008,0.0008,0,0.0000,0,0,83.8231,25829.2720,0,0.0000,0.0000,0.00,0.0313,0.8369,0.0000,1.9778,3.5545,0.1979,4.1297,38.6352,3.5441,3.6046,3.6279,0.0137,3.6275,0.0709,-15.2581,0,-13.7580,826.4444,-13.6053,-13.2579,47648.0932,25853.3904,-15.2568,17847.8323,-15.5940,-15.2483,1401.8756,10.2464,6.9289,4.1692,0.000,4,1.0041,46,0,1.1829,1.1976,1.132637e+03,0.0000,0.8889,0.0000,0.0000,8,-158.6333,0.0000,-0.0767,0.9866,1.0943,-0.0065,-0.0016,0.0000,0,37.5760,0.0000,0.0000,0.0000,0.0000,0.0000,0.1780,1.5488,0.0088,-0.0868,0.00,No

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,PeriodChanger,category,0.0,0.0,2.0,"No, Yes"
1,MATS3v,float64,0.0,0.0,87.0,"-0.0251, -0.0619, -0.0028, 0.0908, 0.1411, 0.072, 0.0995, -0.0254, 0.0081, 0.0135"
2,MATS3s,float64,0.0,0.0,89.0,"-0.0384, 0.0075, 0.0516, 0.0296, 0.1777, 0.135, -0.0164, 0.0424, -0.1548, -0.0077"
3,MATS3p,float64,0.0,0.0,85.0,"-0.0614, -0.0164, -0.0137, -0.0912, -0.1607, -0.0304, 0.0096, 0.055, -0.0399, -0.0353"
4,minHBint8,float64,0.0,0.0,13.0,"0.0, 5.6998, 3.4049, 5.3849, 6.2553, 5.9882, 0.7664, 4.0551, 4.0099, 4.9075"
5,MATS3e,float64,0.0,0.0,89.0,"-0.0356, -0.0436, -0.031, -0.0446, 0.2111, 0.049, -0.0638, -0.1361, -0.0595, -0.056"
6,MATS3c,float64,0.0,0.0,89.0,"-0.045, -0.0191, -0.0214, -0.1156, 0.0575, 0.1199, -0.0159, 0.0307, 0.054, -0.113"
7,minHBint2,float64,0.0,0.0,21.0,"0.0, 4.9247, 6.3505, 0.6939, 5.6769, 0.8764, 7.291, 6.0139, 0.386, 7.1134"
8,MATS3m,float64,0.0,0.0,88.0,"0.0922, -0.0337, 0.1368, 0.1684, 0.1442, 0.1205, 0.0628, 0.0782, 0.0306, -0.2157"
9,minHBint6,float64,0.0,0.0,26.0,"0.0, 0.1731, -0.2817, -0.2562, -0.2795, -0.284, 1.1598, 6.4621, 0.5701, 0.2348"
10,minHBint7,float64,0.0,0.0,12.0,"0.0, 3.3261, 4.9166, 3.3638, 0.3059, 6.1495, 1.2346, 0.886, 5.7176, 8.8221"
11,minHBint4,float64,0.0,0.0,19.0,"0.0, 0.6538, 0.4692, 3.7806, 6.0087, 1.2795, 1.6598, 6.007, -0.8879, 0.1188"
12,MATS3i,float64,0.0,0.0,89.0,"-0.1512, -0.0574, -0.1978, -0.0445, -0.1177, -0.0841, -0.0871, 0.0569, -0.2358, 0.0718"
13,VR3_Dt,float64,0.0,0.0,87.0,"14.6844, 66.8884, 31.88, 28.1692, 18.5967, 24.6228, 25.7867, 15.3933, 24.1184, 23.3828"
14,SpMax8_Bhi,float64,0.0,0.0,87.0,"3.2732, 3.0725, 3.1095, 3.354, 3.0841, 2.9365, 3.056, 3.1868, 3.3059, 2.8381"
15,SdsN,float64,0.0,0.0,24.0,"0.0, 4.5061, 4.4708, 4.6735, 8.3959, 5.1758, 4.9913, 8.835, 5.1754, 13.0551"
16,SpMax8_Bhm,float64,0.0,0.0,87.0,"3.1665, 2.9614, 3.0904, 3.2664, 3.1494, 2.8229, 2.9659, 3.14, 3.2626, 2.6192"
17,SpMax8_Bhe,float64,0.0,0.0,87.0,"3.0841, 2.9908, 3.0885, 2.9882, 3.0915, 2.9778, 3.3079, 2.8817, 3.0249, 3.1743"
18,MDEC-14,float64,0.0,0.0,8.0,"0.0, 1.0931, 0.1111, 0.0526, 1.0, 0.8165, 0.5, 0.2823"
19,SpMax8_Bhs,float64,0.0,0.0,89.0,"3.7357, 3.8373, 3.6147, 3.3403, 2.8918, 3.2175, 3.8393, 3.0051, 3.7216, 2.9792"
20,SpMax8_Bhp,float64,0.0,0.0,84.0,"3.0507, 2.8246, 3.0428, 2.8176, 3.2044, 3.104, 2.7647, 2.9193, 3.0449, 2.9232"
21,SpMax8_Bhv,float64,0.0,0.0,89.0,"3.0653, 3.2128, 3.1279, 2.8649, 3.1169, 2.7634, 2.9183, 3.0525, 2.9736, 2.6458"
22,MDEC-11,float64,0.0,0.0,16.0,"0.0, 0.0833, 0.2, 0.3333, 0.0909, 0.0714, 0.0556, 1.2292, 0.25, 0.6128"
23,MDEC-12,float64,0.0,0.0,44.0,"0.0, 2.1011, 3.162, 4.3786, 5.804, 2.3911, 5.1016, 6.8952, 2.347, 4.778"
24,MDEC-13,float64,0.0,0.0,43.0,"0.0, 0.988, 1.6549, 4.5968, 10.7868, 1.9075, 4.3036, 6.1962, 0.7559, 4.6554"
25,VR2_Dt,float64,0.0,0.0,88.0,"6.7682, 22.238, 16.2772, 20.9868, 90919.394, 7.9759, 8.718, 12.4365, 18.3881, 10.5113"
26,BIC5,float64,0.0,0.0,85.0,"0.8284, 0.895, 0.8262, 0.8948, 0.8435, 0.8479, 0.8455, 0.8389, 0.7539, 0.9054"
27,ATS7s,float64,0.0,0.0,90.0,"768.4444, 425.4444, 637.9722, 302.7778, 381.6389, 584.8889, 618.1667, 409.4815, 489.3333, 409.5679"
28,ATS7p,float64,0.0,0.0,90.0,"275.1928, 181.4037, 308.5308, 177.4491, 219.6084, 223.4303, 274.7079, 178.6939, 176.3196, 256.6466"
29,ATS7v,float64,0.0,0.0,90.0,"41003.7141, 24813.9539, 43978.163, 24070.1176, 29365.513, 31756.7628, 38856.0846, 22460.5131, 26031.1498, 31450.3462"
30,ATS7i,float64,0.0,0.0,90.0,"24110.886, 18065.5308, 32652.6008, 17615.9168, 22274.7466, 21904.7365, 27210.3871, 25240.1576, 16682.6466, 33708.2551"
31,ATS7m,float64,0.0,0.0,90.0,"15270.4651, 7847.5984, 15326.8798, 7171.7894, 8543.078, 10681.9538, 13244.5417, 7467.194, 9865.3887, 9342.8208"
32,ATS7e,float64,0.0,0.0,90.0,"1277.0737, 897.2825, 1600.0765, 850.9717, 1074.2134, 1107.6162, 1361.6859, 1161.4477, 875.3553, 1532.2504"
33,mintN,float64,0.0,0.0,4.0,"0.0, 9.9035, 9.9186, 10.5396"
34,minHBint3,float64,0.0,0.0,11.0,"0.0, 0.4526, 0.5915, 5.1305, 0.3699, 0.6999, 0.3135, 0.3848, 0.3737, 0.2961"
35,maxdssC,float64,0.0,0.0,36.0,"0.0, 0.1123, 0.0391, 0.8559, 0.1313, 1.1118, 0.7553, 0.0665, 0.7177, 0.6828"
36,minHBint5,float64,0.0,0.0,22.0,"0.0, 4.3397, 2.3766, 2.9113, 3.0485, 2.5472, 0.4692, 0.8362, 5.8956, 3.3159"
37,minssCH2,float64,0.0,0.0,53.0,"0.0, 0.4285, -0.32, 0.6117, -0.2881, -0.3139, 0.5468, 0.9788, 0.0338, 0.406"
38,SpMax_DzZ,float64,0.0,0.0,90.0,"201.0744, 170.7489, 224.5021, 135.4904, 182.8209, 275.0884, 232.8161, 119.553, 208.7345, 185.9514"
39,ETA_EtaP,float64,0.0,0.0,90.0,"0.8169, 0.6823, 0.9176, 0.6238, 0.7223, 0.7477, 0.7793, 0.8027, 0.7117, 0.9572"
40,SpMin1_Bhe,float64,0.0,0.0,76.0,"1.9524, 2.1314, 1.9639, 2.0273, 2.0341, 1.9271, 2.0559, 2.0446, 1.9528, 2.0491"
41,maxHother,float64,0.0,0.0,86.0,"0.6492, 0.5668, 0.6079, 0.6549, 0.0, 0.5657, 0.599, 0.5847, 0.6622, 0.6567"
42,StN,float64,0.0,0.0,4.0,"0.0, 19.8069, 19.8385, 21.2941"
43,Sare,float64,0.0,0.0,88.0,"64.456, 58.076, 60.832, 71.168, 72.208, 51.512, 56.964, 64.968, 51.152, 55.284"
44,SHAvin,float64,0.0,0.0,16.0,"0.0, 1.46, 1.4428, 0.523, 0.6047, 0.6139, 0.7208, 0.5092, 0.5089, 0.605"
45,SpMax3_Bhv,float64,0.0,0.0,88.0,"3.8141, 3.7995, 3.6814, 3.8397, 3.7852, 3.8731, 3.8416, 3.8543, 3.6978, 3.8292"
46,SpMax3_Bhp,float64,0.0,0.0,86.0,"3.6685, 3.849, 3.8293, 3.8447, 3.9582, 3.8063, 3.7814, 3.876, 3.84, 3.8521"
47,SpMax3_Bhs,float64,0.0,0.0,88.0,"4.1029, 4.57, 4.6723, 3.8354, 4.1426, 4.1305, 3.8472, 4.0254, 4.6154, 4.6428"
48,SpMax3_Bhe,float64,0.0,0.0,90.0,"4.0541, 3.8496, 3.9253, 3.86, 3.9176, 3.9025, 3.9202, 3.7982, 3.9059, 3.8309"
49,SpMin6_Bhi,float64,0.0,0.0,85.0,"1.3815, 1.4635, 1.4068, 1.368, 1.3727, 1.2898, 1.2944, 1.2506, 1.2577, 1.2255"
50,SpMax3_Bhm,float64,0.0,0.0,86.0,"4.1643, 3.8737, 4.0396, 3.8548, 3.8746, 3.8662, 3.8864, 3.7882, 3.8794, 3.9252"
51,SpMax3_Bhi,float64,0.0,0.0,85.0,"3.9012, 3.9168, 3.909, 3.8689, 3.9097, 4.0792, 3.7821, 3.8554, 3.9382, 3.89"
52,ETA_EtaP_F_L,float64,0.0,0.0,85.0,"0.3093, 0.3071, 0.2722, 0.3092, 0.3114, 0.2507, 0.284, 0.3239, 0.2654, 0.264"
53,AATSC2e,float64,0.0,0.0,72.0,"0.0179, 0.0098, 0.0077, 0.0094, 0.0215, 0.006, 0.0055, 0.0108, 0.0095, 0.011"
54,AATSC2c,float64,0.0,0.0,46.0,"0.0007, 0.0, -0.0001, 0.0003, 0.0002, 0.0018, 0.0004, -0.0014, -0.0007, 0.0006"
55,AATSC2m,float64,0.0,0.0,88.0,"-0.757, 6.0504, 0.6986, 3.6486, 3.8652, -1.5729, -0.5718, 0.3231, -3.5255, 0.7695"
56,AATSC2i,float64,0.0,0.0,88.0,"-0.1221, 0.2696, 0.0196, -0.0837, 0.0094, -0.1081, -0.1955, -0.2296, -0.1424, -0.1041"
57,AATS5p,float64,0.0,0.0,89.0,"1.3466, 1.9081, 1.393, 1.5476, 1.5802, 1.6039, 1.518, 1.5792, 1.3486, 1.5874"
58,AATSC2v,float64,0.0,0.0,88.0,"-4.004, 3.6996, -0.8911, 1.7266, 4.1794, -6.4026, -5.5087, -3.7746, -4.0465, -4.3573"
59,AATSC2p,float64,0.0,0.0,83.0,"-0.0088, 0.0059, -0.0184, -0.0205, -0.001, 0.0358, 0.0304, 0.0173, -0.0315, -0.0329"
60,AATSC2s,float64,0.0,0.0,88.0,"0.003, 0.0379, 0.0342, 0.0308, -0.004, -0.0223, -0.0313, 0.4216, 0.3492, 0.1421"
61,VABC,float64,0.0,0.0,88.0,"509.5859, 437.2103, 451.4722, 486.0112, 491.2352, 372.405, 415.8837, 474.9113, 356.5745, 435.6162"
62,maxdNH,float64,0.0,0.0,2.0,"0.0, 8.7272"
63,RotBtFrac,float64,0.0,0.0,65.0,"0.122, 0.1429, 0.1667, 0.1304, 0.18, 0.0, 0.1463, 0.1373, 0.12, 0.1042"
64,ATS4e,float64,0.0,0.0,90.0,"1453.5938, 1000.3893, 1466.5374, 887.3618, 1166.9825, 1319.7257, 1377.0286, 1014.6269, 1047.0389, 1383.6943"
65,ATS4m,float64,0.0,0.0,90.0,"19835.8193, 10667.8487, 15043.5018, 8482.9597, 11504.6094, 14889.7834, 14817.7007, 8453.7951, 12062.7892, 10938.2733"
66,ATS4i,float64,0.0,0.0,90.0,"26862.1417, 19574.8372, 29205.1582, 18182.8998, 22993.7686, 25065.9509, 26980.2328, 21076.8876, 19874.5666, 29050.5028"
67,ATS4s,float64,0.0,0.0,90.0,"759.7778, 542.6667, 595.0278, 330.8889, 491.5556, 781.6667, 657.0556, 359.0926, 628.1111, 415.8786"
68,ATS4p,float64,0.0,0.0,90.0,"347.5541, 197.8295, 301.1539, 186.7297, 241.402, 255.68, 278.5084, 176.8248, 192.6559, 267.2253"
69,ETA_Alpha,float64,0.0,0.0,76.0,"17.8667, 20.4, 20.8, 13.4667, 17.0333, 18.6333, 18.4, 19.2, 20.9667, 20.6857"
70,EE_Dzi,float64,0.0,0.0,90.0,"198.0675, 166.4848, 217.6419, 132.1021, 183.0626, 268.7435, 226.669, 121.3599, 204.5507, 179.4235"
71,MAXDN,float64,0.0,0.0,89.0,"5.7983, 0.0, 1.7409, 1.8134, 1.0873, 1.9789, 2.2624, 2.4669, 5.4679, 2.2175"
72,EE_Dzm,float64,0.0,0.0,90.0,"201.0915, 170.7734, 224.5435, 135.5053, 182.8549, 275.1219, 232.8506, 119.5754, 208.7745, 185.9514"
73,EE_Dze,float64,0.0,0.0,90.0,"201.1842, 170.9055, 224.7612, 135.5984, 182.9427, 275.3103, 233.0393, 124.6524, 208.9472, 187.2749"
74,EE_Dzs,float64,0.0,0.0,90.0,"213.9751, 178.612, 238.567, 142.1762, 209.0899, 294.8595, 259.3917, 207.103, 214.8005, 216.4419"
75,EE_Dzp,float64,0.0,0.0,90.0,"232.9974, 216.33, 301.6233, 165.5354, 247.1467, 337.2784, 310.3661, 170.1953, 283.6492, 251.2437"
76,EE_Dzv,float64,0.0,0.0,90.0,"222.2215, 200.9012, 275.0579, 155.9596, 217.9909, 316.8587, 280.7815, 156.9648, 254.6812, 231.9667"
77,ATS8e,float64,0.0,0.0,90.0,"1094.3304, 842.6846, 1578.6571, 758.7532, 952.0237, 1074.2945, 1337.0418, 911.5961, 831.992, 1407.5131"
78,maxsOH,float64,0.0,0.0,14.0,"0.0, 11.2259, 11.2531, 10.4481, 10.9319, 11.0704, 9.3005, 10.7499, 9.2266, 11.0968"
79,minssssNp,float64,0.0,0.0,2.0,"0.0, 1.2767"
80,maxsOm,float64,0.0,0.0,8.0,"0.0, 11.5974, 11.5498, 11.7346, 11.0258, 11.2993, 11.5873, 12.0908"
81,MDEC-23,float64,0.0,0.0,87.0,"21.9406, 30.0905, 60.1757, 41.9214, 40.6558, 52.3812, 52.7343, 16.57, 39.8284, 32.8945"
82,MDEC-22,float64,0.0,0.0,69.0,"0.0, 18.522, 21.3119, 19.0452, 30.5976, 21.1857, 24.9656, 24.4932, 15.9913, 20.9494"
83,MDEC-24,float64,0.0,0.0,12.0,"0.0, 6.1751, 2.6445, 4.6102, 2.3094, 5.2861, 5.3684, 2.8887, 5.4718, 2.7589"
84,ATS8s,float64,0.0,0.0,90.0,"554.0, 374.5556, 620.6667, 261.2222, 348.0278, 526.6667, 579.7778, 340.5556, 444.2222, 343.0226"
85,ATS8v,float64,0.0,0.0,90.0,"35648.5015, 20622.7113, 44421.6247, 21187.4335, 25312.8006, 29929.9495, 37507.7567, 19827.4225, 24262.7546, 25405.9472"
86,SP-6,float64,0.0,0.0,84.0,"0.0, 4.8354, 18.2418, 11.1573, 12.1948, 6.6106, 8.3042, 9.4548, 11.3221, 3.3743"
87,SP-7,float64,0.0,0.0,84.0,"0.0, 3.7004, 16.2633, 9.4496, 10.2727, 5.4569, 6.8426, 7.1159, 9.452, 2.5046"
88,SHsNH2,float64,0.0,0.0,2.0,"0.0, 0.4427"
89,SP-5,float64,0.0,0.0,84.0,"0.0, 7.2357, 20.9413, 14.4988, 15.6301, 9.5883, 11.6978, 13.6847, 14.3691, 5.9236"
90,SP-2,float64,0.0,0.0,84.0,"0.0, 12.9139, 22.2081, 19.0158, 20.3002, 14.4199, 16.4529, 19.6379, 20.1943, 12.4857"
91,SP-3,float64,0.0,0.0,84.0,"0.0, 10.0783, 22.362, 17.9001, 19.2709, 12.8878, 15.3748, 18.0321, 18.279, 9.1894"
92,SP-0,float64,0.0,0.0,72.0,"30.5344, 0.0, 24.8108, 19.7254, 28.3713, 30.1118, 24.974, 27.0535, 28.3024, 26.6726"
93,SP-1,float64,0.0,0.0,76.0,"0.0, 13.4317, 21.2789, 21.2086, 19.9019, 17.4744, 19.853, 21.3294, 19.653, 22.508"
94,minHsOH,float64,0.0,0.0,13.0,"0.0, 0.269, 0.3244, 0.3142, 0.4519, 0.3387, 0.309, 0.6246, 0.646, 0.1986"
95,ATSC8v,float64,0.0,0.0,90.0,"237.1491, 209.1564, -303.7545, -283.3104, 47.3189, 365.8774, -310.0301, 393.0578, 185.8929, 2075.2869"
96,MATS2v,float64,0.0,0.0,87.0,"-0.0885, 0.0712, -0.0231, 0.1258, -0.0404, 0.0857, -0.1271, -0.1118, -0.0861, -0.0784"
97,ATSC8s,float64,0.0,0.0,90.0,"-0.6667, 38.8724, -6.2778, -1.4314, 12.4103, -5.4632, -11.8892, 14.5844, 23.9211, 5.4356"
98,MATS2p,float64,0.0,0.0,87.0,"-0.0911, 0.1117, -0.0112, -0.0166, 0.0019, 0.0768, -0.1389, -0.1438, -0.0813, -0.1074"
99,MATS2s,float64,0.0,0.0,89.0,"0.1289, 0.094, 0.0407, -0.013, -0.0275, -0.0116, 0.1808, 0.1949, 0.0625, 0.1631"
100,ATSC8p,float64,0.0,0.0,90.0,"-0.2969, -0.6903, -0.5646, -1.1314, 0.2308, -0.1744, -2.5351, 0.329, -2.0484, 8.6749"
101,MATS2e,float64,0.0,0.0,87.0,"0.0311, 0.0681, 0.2861, 0.1073, 0.1265, 0.2852, 0.1233, 0.1803, 0.1054, 0.2618"
102,ATSC8e,float64,0.0,0.0,89.0,"-0.7819, 0.0573, -1.0147, -0.4422, -0.179, 1.4198, -0.4696, 0.2457, -0.1989, 1.1373"
103,ATSC8c,float64,0.0,0.0,90.0,"0.1053, 0.2512, -0.0962, 0.0321, 0.1691, 0.2246, -0.0081, -0.0116, -0.2409, -0.058"
104,MATS2c,float64,0.0,0.0,90.0,"0.0481, 0.1524, 0.0522, -0.1014, -0.1116, -0.002, -0.0119, 0.0159, 0.1835, -0.1092"
105,MATS2m,float64,0.0,0.0,88.0,"-0.0249, 0.1189, 0.0281, 0.1148, 0.1198, -0.0525, -0.0187, 0.0105, -0.076, 0.0262"
106,ATSC8m,float64,0.0,0.0,90.0,"384.182, 698.9868, -430.0307, -206.059, 199.8748, 427.0017, 43.9934, 346.3785, 711.5082, 1298.9326"
107,MATS2i,float64,0.0,0.0,88.0,"-0.084, 0.166, 0.0129, -0.052, 0.0058, -0.0677, -0.1285, -0.1388, -0.0946, -0.0678"
108,ATSC8i,float64,0.0,0.0,90.0,"-13.8718, -11.2555, 6.2348, -5.477, 0.4626, -8.0251, -5.4787, -3.8913, -26.3567, 27.1437"
109,SpAD_Dt,float64,0.0,0.0,88.0,"635.1516, 3444.0152, 1176.3045, 1108.1734, 1675.4968, 1634.1502, 433.3512, 1205.9262, 1013.3811, 1712.2192"
110,ETA_Eta_R_L,float64,0.0,0.0,79.0,"13.4316, 17.4743, 19.8529, 19.9018, 21.3293, 21.2788, 19.6529, 17.4138, 21.2086, 21.0123"
111,SHdsCH,float64,0.0,0.0,19.0,"0.0, 1.0107, 0.9836, 0.9345, 1.5822, 0.9952, 0.4504, 0.508, 0.605, 1.049"
112,SaasN,float64,0.0,0.0,31.0,"0.0, 1.3532, 2.1215, 2.1188, 1.9613, 2.1054, 2.1071, 1.7679, 1.9565, 4.4231"
113,SC-4,float64,0.0,0.0,9.0,"0.0, 0.2887, 0.0833, 0.1667, 0.0556, 0.25, 0.1179, 0.1443, 0.2041"
114,SaasC,float64,0.0,0.0,89.0,"5.5822, 0.0, 3.2016, 4.2128, 7.947, 4.4531, 2.3406, 4.0133, 2.4316, 3.0686"
115,minaaCH,float64,0.0,0.0,88.0,"1.7414, 1.5871, 0.0, 2.1257, 1.8763, 1.8844, 1.9455, 1.8388, 1.375, 1.4102"
116,AATSC3c,float64,0.0,0.0,42.0,"0.0009, -0.0004, -0.0013, 0.0006, -0.0003, -0.0002, 0.0005, -0.0011, 0.0001, -0.0009"
117,AATSC3e,float64,0.0,0.0,70.0,"-0.0031, -0.0019, -0.0026, -0.0025, -0.0008, -0.0037, -0.0021, -0.0039, -0.001, -0.0043"
118,AATSC3i,float64,0.0,0.0,88.0,"-0.2198, -0.0287, -0.0868, -0.3047, -0.0717, -0.188, -0.128, -0.1442, 0.0855, -0.3622"
119,AATSC3m,float64,0.0,0.0,89.0,"2.8048, 3.4021, 2.4265, 3.8871, 1.8821, 2.3911, 0.9419, -10.0127, 3.5353, -3.9781"
120,AATSC3s,float64,0.0,0.0,88.0,"0.04, -0.0406, 0.0201, 0.0224, 0.0552, 0.1098, -0.0442, 0.0989, -0.2773, -0.0175"
121,AATSC3p,float64,0.0,0.0,82.0,"-0.0053, -0.016, -0.0232, -0.0091, -0.0205, -0.0216, -0.0076, -0.0139, -0.0381, -0.0352"
122,AATSC3v,float64,0.0,0.0,89.0,"-0.1275, 3.5086, -0.8042, 4.8514, -1.279, 0.3983, 0.5941, -4.501, -1.0501, -2.725"
123,SpMax2_Bhp,float64,0.0,0.0,85.0,"3.9515, 4.0711, 3.9043, 4.1095, 4.0229, 4.03, 3.9787, 3.9213, 3.9851, 3.9057"
124,AATS8e,float64,0.0,0.0,90.0,"7.8166, 7.524, 7.7385, 7.3665, 7.38, 7.6735, 7.6841, 7.5339, 7.849, 7.218"
125,AATS8i,float64,0.0,0.0,90.0,"149.5621, 157.1955, 156.1115, 153.0851, 153.7359, 152.8938, 154.3133, 160.186, 152.6438, 166.2994"
126,AATS8m,float64,0.0,0.0,90.0,"92.9158, 60.7826, 74.1633, 59.82, 58.0697, 72.4984, 73.3835, 58.721, 87.1723, 35.9953"
127,AATS8s,float64,0.0,0.0,90.0,"3.9571, 3.3442, 3.0425, 2.5361, 2.6979, 3.7619, 3.3321, 2.8145, 4.1908, 1.7591"
128,AATS8p,float64,0.0,0.0,90.0,"1.7139, 1.3567, 1.5311, 1.5376, 1.4728, 1.4962, 1.5186, 1.2969, 1.5386, 1.0884"
129,AATS8v,float64,0.0,0.0,90.0,"254.6322, 184.1314, 217.7531, 205.7032, 196.2233, 213.7854, 215.5618, 163.863, 228.8939, 130.2869"
130,VE3_Dt,float64,0.0,0.0,88.0,"-1.5291, -167.1241, -15.9048, -5.2389, -150.1094, -2.078, -5.0145, -11.1583, -6.8881, -8.2628"
131,XLogP,float64,0.0,0.0,89.0,"2.933, -0.094, 4.144, 3.338, 5.305, 4.052, 0.991, 2.917, 1.639, 1.099"
132,SpMax2_Bhi,float64,0.0,0.0,86.0,"4.0573, 4.2256, 3.9435, 4.2285, 4.0692, 4.1647, 4.0333, 4.0677, 4.0453, 4.0278"
133,maxssCH2,float64,0.0,0.0,51.0,"0.0, 0.7321, 0.8529, 0.6752, 0.9746, 0.6135, 0.8751, 1.0289, 0.2719, 0.406"
134,minaaS,float64,0.0,0.0,8.0,"0.0, -1.1871, -1.8213, -1.6243, -1.4302, -1.1383, -1.1013, -1.5283"
135,SpMax4_Bhv,float64,0.0,0.0,80.0,"3.5641, 3.6586, 3.6731, 3.7631, 3.7045, 3.6978, 3.7594, 3.6783, 3.7811, 3.6505"
136,SpMax4_Bhs,float64,0.0,0.0,87.0,"3.9659, 4.5009, 3.8676, 4.6641, 3.8608, 3.9788, 3.8046, 3.8793, 4.5857, 4.1103"
137,SpMax4_Bhp,float64,0.0,0.0,81.0,"3.5737, 3.6667, 3.707, 3.6788, 3.7707, 3.5818, 3.6825, 3.7784, 3.6685, 3.7458"
138,SpMax4_Bhm,float64,0.0,0.0,81.0,"3.5513, 3.6477, 3.6856, 3.7368, 3.7114, 3.8024, 3.8165, 3.8057, 3.7551, 3.6874"
139,minHaaNH,float64,0.0,0.0,8.0,"0.0, 0.2689, 0.4006, 0.4591, 0.2929, 0.2919, 0.367, 0.2833"
140,SpMax4_Bhi,float64,0.0,0.0,80.0,"3.6534, 3.756, 3.7349, 3.7821, 3.8519, 3.7684, 3.764, 3.8928, 3.778, 3.8057"
141,minaaN,float64,0.0,0.0,45.0,"0.0, 4.2019, 4.5399, 4.4851, 4.8373, 4.7373, 4.7884, 5.0166, 4.9338, 4.8009"
142,SpMax4_Bhe,float64,0.0,0.0,80.0,"3.623, 3.7536, 3.7088, 3.7044, 3.739, 3.7377, 3.8687, 3.7854, 3.6802, 3.8302"
143,StsC,float64,0.0,0.0,4.0,"0.0, 4.4113, 4.379, 4.795"
144,SssCH2,float64,0.0,0.0,53.0,"0.0, 1.6732, -0.32, 3.1964, 2.435, 1.8041, 2.7966, 5.0091, 0.4545, 0.406"
145,maxHdNH,float64,0.0,0.0,2.0,"0.0, 0.4292"
146,MATS1p,float64,0.0,0.0,86.0,"0.0267, 0.0001, -0.0522, 0.0778, 0.0049, -0.0303, 0.0753, -0.1026, -0.0495, -0.0408"
147,R_TpiPCTPC,float64,0.0,0.0,89.0,"10.4111, 20.3566, 4.7181, 26.2578, 11.3839, 7.5401, 13.9591, 4.2964, 7.9462, 10.6539"
148,MATS1s,float64,0.0,0.0,81.0,"-0.0482, -0.0214, -0.2207, -0.0622, -0.0437, -0.1571, -0.0114, -0.0104, -0.077, 0.0097"
149,MATS1v,float64,0.0,0.0,84.0,"0.0395, 0.0344, 0.0218, -0.0015, 0.0684, 0.0208, 0.0347, 0.0266, -0.0053, -0.0022"
150,JGI10,float64,0.0,0.0,43.0,"0.0065, 0.0066, 0.007, 0.0069, 0.0048, 0.0061, 0.0063, 0.0068, 0.0064, 0.0059"
151,MATS1c,float64,0.0,0.0,88.0,"-0.4421, -0.476, -0.5748, -0.4425, -0.4662, -0.4154, -0.3748, -0.4401, -0.3769, -0.4209"
152,MATS1e,float64,0.0,0.0,86.0,"0.0828, 0.1071, -0.0406, -0.0346, -0.0226, 0.1237, -0.018, 0.1893, 0.1335, 0.2553"
153,VR2_DzZ,float64,0.0,0.0,90.0,"25.3775, 15.7658, 18.1867, 12.6515, 56.5715, 90918.5063, 10.9485, 11.0853, 22.4008, 13.155"
154,MATS1i,float64,0.0,0.0,87.0,"0.0164, -0.1471, 0.0803, -0.1392, -0.0392, -0.2329, -0.015, 0.1202, 0.1025, -0.2292"
155,MATS1m,float64,0.0,0.0,85.0,"0.044, 0.0689, 0.016, 0.1696, 0.0814, 0.0547, 0.085, 0.0713, 0.0699, 0.0709"
156,MDEC-34,float64,0.0,0.0,12.0,"0.0, 4.6696, 2.8426, 6.3119, 1.357, 3.4083, 3.3518, 2.5546, 2.589, 2.9805"
157,MDEC-33,float64,0.0,0.0,84.0,"4.9976, 22.923, 7.3081, 9.3179, 24.0107, 8.1853, 9.4583, 10.9352, 29.9335, 24.5056"
158,VR2_Dze,float64,0.0,0.0,90.0,"25.3702, 15.8313, 18.1764, 12.6341, 59.3956, 90918.5098, 10.9535, 14.9218, 22.0818, 13.4981"
159,VR2_Dzm,float64,0.0,0.0,90.0,"25.3764, 15.7769, 18.1835, 12.649, 51.844, 90918.5067, 10.9493, 11.086, 22.3566, 13.1545"
160,VR2_Dzs,float64,0.0,0.0,89.0,"11.0012, 19.5588, 60.4379, 19.2217, 13.2802, 17.4551, 122.7957, 13.4482, 7.738, 16.5953"
161,VR2_Dzp,float64,0.0,0.0,90.0,"24.5288, 13.9597, 16.3622, 11.5826, 16.5601, 90919.4734, 14.3279, 20.9114, 12.6073, 11.0288"
162,ATS5e,float64,0.0,0.0,90.0,"1408.5019, 945.9353, 1546.6943, 897.5663, 1169.9459, 1277.3226, 1391.8234, 1128.3702, 939.1796, 1502.5156"
163,gmin,float64,0.0,0.0,88.0,"-5.4743, -0.7095, 0.0, 0.8746, -0.0833, -0.1467, 0.5793, -0.7289, -0.5957, -0.4669"
164,VR2_D,float64,0.0,0.0,88.0,"10.1431, 34.7634, 372098.7271, 79.5262, 90918.069, 11.3813, 12.3934, 26.6967, 12.0028, 28.2625"
165,ATS5m,float64,0.0,0.0,90.0,"18932.5551, 9936.3763, 14720.9962, 8785.3315, 10868.6901, 13466.2386, 13925.4556, 9771.3998, 10567.6924, 10887.9018"
166,ATS5p,float64,0.0,0.0,90.0,"339.6464, 194.5498, 312.6218, 186.468, 246.9991, 238.3261, 282.6739, 196.8904, 180.9601, 270.6672"
167,ATS5s,float64,0.0,0.0,90.0,"734.3333, 473.7778, 599.0, 341.5556, 470.7222, 821.7778, 604.5, 526.7407, 522.1111, 449.7984"
168,ATS5v,float64,0.0,0.0,90.0,"51592.2938, 28596.283, 43945.0155, 26294.2191, 34564.225, 35924.3628, 40679.1858, 26372.3508, 27899.5858, 35815.241"
169,AATSC5p,float64,0.0,0.0,81.0,"0.0139, 0.0114, 0.0057, -0.0264, 0.0204, 0.0218, 0.0101, -0.0084, 0.0149, -0.0198"
170,TpiPC,float64,0.0,0.0,89.0,"9.2386, 12.0215, 8.9343, 10.6717, 10.1008, 9.6982, 10.7706, 7.9055, 9.7474, 9.8242"
171,maxsCH3,float64,0.0,0.0,46.0,"0.0, 2.0211, 1.8859, 1.6729, 2.1731, 2.2386, 1.2819, 2.1649, 1.9816, 1.9868"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
MATS3v,90.0,-0.024353,5.617929e-02,-0.1837,1.411000e-01
nHBint10,90.0,0.255556,7.725794e-01,0.0000,4.000000e+00
MATS3s,90.0,-0.003878,7.450182e-02,-0.1736,2.181000e-01
MATS3p,90.0,-0.055896,6.199310e-02,-0.2319,1.028000e-01
nHBDon_Lipinski,90.0,0.722222,1.049642e+00,0.0000,6.000000e+00
minHBint8,90.0,0.563020,1.598142e+00,0.0000,6.255300e+00
MATS3e,90.0,-0.029761,8.213152e-02,-0.2119,2.495000e-01
MATS3c,90.0,-0.043134,1.103378e-01,-0.3563,2.122000e-01
minHBint2,90.0,0.971352,2.177496e+00,0.0000,7.291000e+00
MATS3m,90.0,0.002886,9.174779e-02,-0.2555,1.684000e-01
minHBint6,90.0,0.403329,1.183410e+00,-0.2840,6.462100e+00
minHBint7,90.0,0.481258,1.663235e+00,0.0000,8.822100e+00
minHBint4,90.0,0.474560,1.440056e+00,-1.0388,6.345200e+00
MATS3i,90.0,-0.071478,9.225594e-02,-0.3355,1.780000e-01
VR3_Dt,90.0,28.946937,1.204298e+01,14.6844,6.688840e+01
SpMax8_Bhi,90.0,3.153086,1.219869e-01,2.8381,3.359700e+00
SdsN,90.0,1.709908,3.089544e+00,0.0000,1.305510e+01
SpMax8_Bhm,90.0,3.049026,1.334140e-01,2.6192,3.266400e+00
SpMax8_Bhe,90.0,3.112140,1.228276e-01,2.7718,3.315800e+00
ECCEN,90.0,1189.522222,2.485104e+02,577.0000,1.783000e+03
MDEC-14,90.0,0.042840,1.848525e-01,0.0000,1.093100e+00
SpMax8_Bhs,90.0,3.411270,2.669627e-01,2.8918,4.109300e+00
SpMax8_Bhp,90.0,2.953693,1.106838e-01,2.6659,3.204400e+00
SpMax8_Bhv,90.0,2.957711,1.146551e-01,2.6458,3.212800e+00
MDEC-11,90.0,0.068318,1.864983e-01,0.0000,1.229200e+00
MDEC-12,90.0,1.732594,2.068503e+00,0.0000,7.241800e+00
MDEC-13,90.0,1.810407,2.577237e+00,0.0000,1.155920e+01
VR2_Dt,90.0,10392.880477,3.025573e+04,6.7682,1.219603e+05
BIC5,90.0,0.845021,5.328958e-02,0.6291,9.188000e-01
ATS7s,90.0,523.229390,1.353311e+02,299.0000,9.670000e+02
ATS7p,90.0,232.600436,5.723568e+01,105.9087,4.010535e+02
ATS7v,90.0,31977.133039,7.672444e+03,16575.9453,5.662685e+04
ATS7i,90.0,25657.979072,7.421402e+03,10789.5533,4.438565e+04
ATS7m,90.0,10848.105231,2.573630e+03,6598.4646,1.834878e+04
ATS7e,90.0,1249.025694,3.310252e+02,568.8626,2.069838e+03
mintN,90.0,0.337352,1.827685e+00,0.0000,1.053960e+01
nHsNH2,90.0,0.011111,1.054093e-01,0.0000,1.000000e+00
khs.sssCH,90.0,0.633333,1.021675e+00,0.0000,4.000000e+00
minHBint3,90.0,0.099844,5.530245e-01,0.0000,5.130500e+00
maxdssC,90.0,0.179398,3.313355e-01,0.0000,1.111800e+00
nT6Ring,90.0,5.055556,1.546007e+00,0.0000,8.000000e+00
minHBint5,90.0,0.630458,1.454703e+00,0.0000,5.898600e+00
nF8Ring,90.0,0.066667,2.922212e-01,0.0000,2.000000e+00
minssCH2,90.0,0.238423,3.396551e-01,-0.3200,1.202500e+00
SpMax_DzZ,90.0,202.631162,4.406048e+01,110.6478,2.953160e+02
ETA_EtaP,90.0,0.834087,1.106581e-01,0.6027,1.108100e+00
nHsOH,90.0,0.233333,7.796571e-01,0.0000,6.000000e+00
SpMin1_Bhe,90.0,2.026238,8.460091e-02,1.8863,2.332400e+00
maxHother,90.0,0.610541,1.015770e-01,0.0000,8.422000e-01
nHBAcc_Lipinski,90.0,7.088889,1.940951e+00,2.0000,1.400000e+01
StN,90.0,0.677106,3.668964e+00,0.0000,2.129410e+01
khs.aaS,90.0,0.077778,2.693220e-01,0.0000,1.000000e+00
khs.aaO,90.0,0.133333,4.546884e-01,0.0000,3.000000e+00
khs.aaN,90.0,1.166667,1.493431e+00,0.0000,7.000000e+00
Sare,90.0,62.220356,7.822361e+00,45.3760,7.941600e+01
SHAvin,90.0,0.122233,3.175659e-01,0.0000,1.582200e+00
SpMax3_Bhv,90.0,3.810052,6.588585e-02,3.6507,3.982800e+00
SpMax3_Bhp,90.0,3.817084,6.716087e-02,3.6586,4.002900e+00
SpMax3_Bhs,90.0,4.279149,3.001889e-01,3.7987,4.831400e+00
SpMax3_Bhe,90.0,3.888430,5.384111e-02,3.7651,4.054100e+00
SpMin6_Bhi,90.0,1.340431,1.047627e-01,1.0598,1.669500e+00
SpMax3_Bhm,90.0,3.877746,8.591924e-02,3.7332,4.164300e+00
SpMax3_Bhi,90.0,3.909100,5.600212e-02,3.7497,4.079200e+00
ETA_EtaP_F_L,90.0,0.285881,2.452888e-02,0.2193,3.302000e-01
AATSC2e,90.0,0.009860,6.516561e-03,-0.0060,2.790000e-02
AATSC2c,90.0,0.000631,1.455763e-03,-0.0026,5.300000e-03
AATSC2m,90.0,1.567104,2.925642e+00,-3.5255,1.439990e+01
AATSC2i,90.0,-0.015660,1.547193e-01,-0.3089,5.135000e-01
nsBr,90.0,0.011111,1.054093e-01,0.0000,1.000000e+00
AATS5p,90.0,1.482942,1.234100e-01,1.2049,1.908100e+00
AATSC2v,90.0,-0.464199,4.099161e+00,-7.4048,1.158090e+01
AATSC2p,90.0,-0.002664,2.080605e-02,-0.0418,5.490000e-02
AATSC2s,90.0,0.104543,1.494486e-01,-0.0562,8.305000e-01
VABC,90.0,449.660490,5.110220e+01,330.6816,5.362966e+02
maxdNH,90.0,0.096969,9.199277e-01,0.0000,8.727200e+00
khs.ddsN,90.0,0.088889,3.230627e-01,0.0000,2.000000e+00
RotBtFrac,90.0,0.141814,6.694196e-02,0.0000,3.667000e-01
ATS4e,90.0,1314.596401,2.459005e+02,864.3981,2.149939e+03
ATS4m,90.0,12733.184183,2.172654e+03,8453.7951,1.983582e+04
nFRing,90.0,6.522222,1.530163e+01,0.0000,1.400000e+02
ATS4i,90.0,26360.349706,5.460790e+03,16616.6203,4.698959e+04
ATS4s,90.0,576.261590,1.209352e+02,330.8889,9.120000e+02
ATS4p,90.0,254.895571,4.728278e+01,164.2551,4.039097e+02
ETA_Alpha,90.0,18.666241,2.003837e+00,13.4667,2.193330e+01
khs.sssN,90.0,1.211111,9.656394e-01,0.0000,4.000000e+00
EE_Dzi,90.0,200.279967,4.143251e+01,111.9352,2.818841e+02
MAXDN,90.0,2.599573,1.490901e+00,0.0000,6.359500e+00
EE_Dzm,90.0,202.646563,4.406155e+01,110.6626,2.953742e+02
EE_Dze,90.0,205.314384,4.329640e+01,113.8753,2.957390e+02
EE_Dzs,90.0,245.673624,6.331064e+01,116.5999,4.320511e+02
EE_Dzp,90.0,267.298764,6.387073e+01,133.0035,4.335789e+02
EE_Dzv,90.0,246.236892,5.576528e+01,126.5701,3.708415e+02
ATS8e,90.0,1156.881698,3.225814e+02,548.6191,1.981608e+03
maxsOH,90.0,1.543753,3.786132e+00,0.0000,1.125310e+01
minssssNp,90.0,0.014186,1.345760e-01,0.0000,1.276700e+00
maxsOm,90.0,0.898722,3.113221e+00,0.0000,1.209080e+01
MDEC-23,90.0,40.873938,9.851766e+00,16.5700,6.525600e+01
MDEC-22,90.0,16.554309,1.026812e+01,0.0000,3.623970e+01
MDEC-24,90.0,0.535591,1.520255e+00,0.0000,6.175100e+00
nFG12HeteroRing,90.0,1.522222,3.772246e+00,0.0000,3.200000e+01
ATS8s,90.0,468.523369,1.238812e+02,261.2222,8.251250e+02
ATS8v,90.0,29490.090259,7.510208e+03,15306.0933,5.205846e+04
SP-6,90.0,8.371656,2.887512e+00,0.0000,1.824180e+01
SP-7,90.0,6.656880,2.480243e+00,0.0000,1.626330e+01
SHsNH2,90.0,0.004919,4.666468e-02,0.0000,4.427000e-01
SP-5,90.0,11.383506,3.500864e+00,0.0000,2.094130e+01
SP-2,90.0,16.659950,4.483191e+00,0.0000,2.220810e+01
SP-3,90.0,15.008110,4.244025e+00,0.0000,2.236200e+01
SP-0,90.0,25.258631,6.786915e+00,0.0000,3.140470e+01
SP-1,90.0,17.958469,4.862423e+00,0.0000,2.250800e+01
minHsOH,90.0,0.048978,1.316497e-01,0.0000,6.460000e-01
ATSC8v,90.0,-106.771204,7.238127e+02,-2206.4650,2.310078e+03
MATS2v,90.0,-0.011467,8.548310e-02,-0.1527,2.659000e-01
ATSC8s,90.0,-7.155730,3.050876e+01,-120.8036,9.350820e+01
MATS2p,90.0,-0.014401,8.595539e-02,-0.1821,2.405000e-01
MATS2s,90.0,0.065911,7.917587e-02,-0.0657,3.146000e-01
ATSC8p,90.0,-0.638703,3.300114e+00,-10.0183,8.674900e+00
MATS2e,90.0,0.143713,9.621807e-02,-0.2382,4.330000e-01
ATSC8e,90.0,-0.359683,1.358828e+00,-4.9218,3.178200e+00
ATSC8c,90.0,-0.055602,2.090584e-01,-0.8375,5.650000e-01
MATS2c,90.0,0.036109,1.217638e-01,-0.3124,3.820000e-01
MATS2m,90.0,0.039931,7.022092e-02,-0.0760,2.445000e-01
topoDiameter,90.0,17.144444,2.415126e+00,9.0000,2.400000e+01
ATSC8m,90.0,-101.896882,6.828679e+02,-1835.4984,1.633018e+03
MATS2i,90.0,-0.010116,9.471281e-02,-0.1821,3.318000e-01
ATSC8i,90.0,-3.136652,2.296870e+01,-62.2383,6.130750e+01
ntN,90.0,0.066667,3.610223e-01,0.0000,2.000000e+00
khs.ssCH2,90.0,2.522222,2.919242e+00,0.0000,1.400000e+01
SpAD_Dt,90.0,1255.999971,3.907506e+02,433.3512,3.444015e+03
ETA_Eta_R_L,90.0,18.982224,2.186954e+00,13.4316,2.250790e+01
SHdsCH,90.0,0.200776,4.681070e-01,0.0000,2.631400e+00
SaasN,90.0,0.750404,1.220580e+00,0.0000,4.866500e+00
SC-4,90.0,0.049671,9.469906e-02,0.0000,2.887000e-01
SaasC,90.0,4.463087,2.499526e+00,-1.7229,1.219350e+01
minaaCH,90.0,1.633207,3.130298e-01,0.0000,2.208800e+00
AATSC3c,90.0,-0.000627,1.452298e-03,-0.0059,2.500000e-03
AATSC3e,90.0,-0.002693,5.439200e-03,-0.0221,1.150000e-02
AATSC3i,90.0,-0.114723,1.466477e-01,-0.5670,2.805000e-01
AATSC3m,90.0,-0.428762,4.035210e+00,-16.4786,5.350800e+00
AATSC3s,90.0,-0.028224,1.085843e-01,-0.3614,1.622000e-01
AATSC3p,90.0,-0.013688,1.503269e-02,-0.0529,2.350000e-02
AATSC3v,90.0,-1.230234,2.754607e+00,-9.1294,7.155300e+00
SpMax2_Bhp,90.0,3.955481,8.099817e-02,3.8124,4.115600e+00
AATS8e,90.0,7.651608,2.332951e-01,7.1137,8.312400e+00
AATS8i,90.0,156.685778,4.008131e+00,148.4702,1.662994e+02
AATS8m,90.0,67.371942,1.391533e+01,35.9953,1.104351e+02
AATS8s,90.0,3.188280,7.102660e-01,1.7591,5.259900e+00
AATS8p,90.0,1.438584,1.319617e-01,1.0884,1.713900e+00
AATS8v,90.0,197.758538,2.434511e+01,130.2869,2.546322e+02
VE3_Dt,90.0,-34.760139,5.405522e+01,-167.1241,-1.484600e+00
XLogP,90.0,3.232456,1.565943e+00,-0.0940,7.196000e+00
SpMax2_Bhi,90.0,4.035679,7.450039e-02,3.9153,4.228500e+00
maxssCH2,90.0,0.421030,4.160487e-01,0.0000,1.407300e+00
minaaS,90.0,-0.109231,3.848336e-01,-1.8213,0.000000e+00
SpMax4_Bhv,90.0,3.667180,9.358604e-02,3.4122,3.850200e+00
SpMax4_Bhs,90.0,4.104519,2.890275e-01,3.5684,4.765900e+00
SpMax4_Bhp,90.0,3.669996,9.704276e-02,3.4028,3.844700e+00
SpMax4_Bhm,90.0,3.715369,9.321204e-02,3.4649,4.090500e+00
minHaaNH,90.0,0.026263,9.285882e-02,0.0000,4.591000e-01
SpMax4_Bhi,90.0,3.780117,8.227340e-02,3.5185,3.918300e+00
minaaN,90.0,2.268766,2.344344e+00,0.0000,5.173800e+00
SpMax4_Bhe,90.0,3.752716,8.140270e-02,3.5070,3.907700e+00
StsC,90.0,0.150948,8.181684e-01,0.0000,4.795000e+00
SssCH2,90.0,1.693417,2.787960e+00,-0.5911,1.854950e+01
maxHdNH,90.0,0.004769,4.524165e-02,0.0000,4.292000e-01
MATS1p,90.0,-0.003759,5.605229e-02,-0.1261,3.068000e-01
R_TpiPCTPC,90.0,11.376896,5.723467e+00,3.9240,2.653650e+01
MATS1s,90.0,-0.054072,7.378482e-02,-0.2255,1.818000e-01
MATS1v,90.0,0.025006,2.795138e-02,-0.0147,2.029000e-01
JGI10,90.0,0.006148,1.433016e-03,0.0000,9.200000e-03
MATS1c,90.0,-0.445562,1.055003e-01,-0.6996,-3.650000e-02
MATS1e,90.0,0.035978,8.748211e-02,-0.1714,2.563000e-01
VR2_DzZ,90.0,15585.628300,6.426180e+04,10.2306,4.359020e+05
MATS1i,90.0,-0.065994,1.016005e-01,-0.2366,3.132000e-01
MATS1m,90.0,0.072931,5.133589e-02,-0.0788,2.174000e-01
MDEC-34,90.0,0.409428,1.182504e+00,0.0000,6.311900e+00
MDEC-33,90.0,17.976200,1.050513e+01,0.0000,8.451790e+01
VR2_Dze,90.0,15586.763258,6.426153e+04,10.2238,4.359020e+05
VR2_Dzm,90.0,15585.617917,6.426181e+04,10.2297,4.359020e+05
VR2_Dzs,90.0,5796.289602,4.667994e+04,7.7380,4.359017e+05
VR2_Dzp,90.0,15588.330751,6.426130e+04,9.4318,4.359025e+05
khs.ssssC,90.0,0.122222,3.293773e-01,0.0000,1.000000e+00
nTG12Ring,90.0,3.066667,1.320946e+01,0.0000,1.210000e+02
khs.ssssN,90.0,0.022222,2.108185e-01,0.0000,2.000000e+00
ATS5e,90.0,1317.135620,2.685464e+02,781.1974,1.992878e+03
gmin,90.0,-1.287860,1.912873e+00,-6.0354,1.202500e+00
VR2_D,90.0,19366.897577,6.584795e+04,10.1431,4.359022e+05
ATS5m,90.0,12264.551571,2.285568e+03,7964.7537,1.903461e+04
ATS5p,90.0,251.238744,5.386900e+01,140.1804,3.975281e+02
ATS5s,90.0,572.062968,1.179352e+02,341.5556,9.196111e+02
ATS5v,90.0,35286.615810,7.222650e+03,20907.1585,5.362892e+04
AATSC5p,90.0,0.000367,2.287019e-02,-0.0664,6.610000e-02
TpiPC,90.0,10.001217,6.782435e-01,7.9055,1.202150e+01
maxsCH3,90.0,0.947752,9.723498e-01,0.0000,2.238600e+00
khs.ssO,90.0,0.355556,6.920270e-01,0.0000,3.000000e+00
ETA_Eta_F_L,90.0,11.155668,1.658293e+00,7.2225,1.432220e+01
khs.ssS,90.0,0.055556,2.303447e-01,0.0000,1.000000e+00
SdO,90.0,29.612533,1.954914e+01,0.0000,8.104410e+01
VE2_Dt,90.0,0.004662,5.373355e-03,0.0000,2.070000e-02
ETA_dEpsilon_B,90.0,0.091424,2.036367e-02,0.0495,1.391000e-01
ETA_dEpsilon_A,90.0,0.170706,3.763430e-02,0.0568,2.768000e-01
ETA_dEpsilon_D,90.0,0.009264,1.327140e-02,0.0000,7.660000e-02
SsNH2,90.0,0.075112,7.125771e-01,0.0000,6.760100e+00
SsCH3,90.0,1.618839,2.087836e+00,0.0000,9.014600e+00
CIC5,90.0,0.537911,3.503122e-01,0.0000,1.795500e+00
CIC4,90.0,0.632867,3.649576e-01,0.1250,1.900800e+00
CIC1,90.0,2.765791,3.729971e-01,1.9277,3.651400e+00
CIC0,90.0,4.445366,2.477574e-01,3.8646,5.254200e+00
CIC3,90.0,1.015856,3.853137e-01,0.3607,2.256300e+00
CIC2,90.0,1.882281,4.319164e-01,1.1539,3.072600e+00
nF10HeteroRing,90.0,0.711111,1.083528e+00,0.0000,6.000000e+00
maxssO,90.0,1.490531,2.566869e+00,0.0000,6.808500e+00
WPOL,90.0,72.611111,1.260078e+01,38.0000,1.160000e+02
n5HeteroRing,90.0,1.500000,1.062645e+00,0.0000,5.000000e+00
maxHAvin,90.0,0.097432,2.234516e-01,0.0000,7.942000e-01
fragC,90.0,534.142889,1.521436e+02,144.0700,1.179080e+03
ETA_Eta_B_RC,90.0,1.003562,1.829209e-01,0.5816,1.562700e+00
AATS7m,90.0,68.772381,1.437004e+01,41.1549,1.019437e+02
SpDiam_Dt,90.0,857.139150,2.334071e+02,293.9427,1.814815e+03
SdssC,90.0,-0.404186,1.099242e+00,-5.0633,2.010900e+00
ETA_Epsilon_3,90.0,0.447982,2.686779e-03,0.4400,4.586000e-01
AATS7i,90.0,156.990100,4.272324e+00,149.3181,1.650206e+02
AATS7e,90.0,7.692619,2.198489e-01,7.1782,8.265000e+00
nT9Ring,90.0,1.388889,1.148467e+00,0.0000,5.000000e+00
minsCl,90.0,0.058258,1.979450e-01,0.0000,8.746000e-01
AATS7v,90.0,199.998981,2.766074e+01,145.8475,2.595882e+02
AATS7s,90.0,3.316273,7.574204e-01,1.9212,5.328700e+00
AATS7p,90.0,1.445311,1.437836e-01,1.1590,1.730400e+00
ETA_Epsilon_5,90.0,0.800729,2.809798e-02,0.7191,8.487000e-01
ETA_Epsilon_4,90.0,0.527260,2.416054e-02,0.4600,6.075000e-01
SsssCH,90.0,-0.333514,7.212405e-01,-3.4037,2.566000e-01
maxHsOH,90.0,0.050454,1.350607e-01,0.0000,6.460000e-01
GATS1v,90.0,0.822077,8.763577e-02,0.5592,1.014900e+00
maxaaaC,90.0,0.742676,5.026649e-01,0.0000,1.506600e+00
GATS1s,90.0,0.600351,1.165626e-01,0.4615,8.860000e-01
BIC4,90.0,0.830210,5.695085e-02,0.6127,9.147000e-01
SpMin7_Bhs,90.0,1.260274,1.247381e-01,1.0070,1.524500e+00
SpMin7_Bhp,90.0,1.419132,1.145086e-01,1.1850,1.690200e+00
SpMin7_Bhv,90.0,1.420646,1.119859e-01,1.1455,1.696900e+00
GATS1e,90.0,0.635136,1.312931e-01,0.3330,1.141800e+00
mintsC,90.0,0.074563,4.039389e-01,0.0000,2.321700e+00
GATS1c,90.0,1.394179,1.129451e-01,1.0389,1.663700e+00
SpMin7_Bhm,90.0,1.382929,1.158230e-01,1.0823,1.607700e+00
GATS1m,90.0,0.671779,7.863739e-02,0.5007,8.897000e-01
SpMin7_Bhe,90.0,1.232709,1.193010e-01,0.9805,1.474800e+00
GATS1i,90.0,1.089893,1.624919e-01,0.5876,1.421600e+00
maxtsC,90.0,0.076386,4.143263e-01,0.0000,2.473300e+00
minHAvin,90.0,0.097200,2.227730e-01,0.0000,7.880000e-01
AATS2v,90.0,266.048513,2.293756e+01,222.2152,3.288105e+02
SPC-6,90.0,17.917701,6.680026e+00,0.0000,3.955310e+01
SPC-4,90.0,6.750630,2.105466e+00,0.0000,1.143640e+01
SPC-5,90.0,11.814152,4.024049e+00,0.0000,2.241830e+01
SpAD_D,90.0,541.696976,1.069402e+02,300.2888,7.785257e+02
MATS6c,90.0,0.007606,1.261617e-01,-0.2353,3.955000e-01
ETA_BetaP_s,90.0,0.652356,2.024065e-02,0.6029,7.000000e-01
minaasC,90.0,0.320300,4.615169e-01,-0.6496,1.389100e+00
minaasN,90.0,0.610106,8.860155e-01,0.0000,2.433300e+00
minssNH,90.0,0.618771,1.210280e+00,0.0000,3.676500e+00
nT7HeteroRing,90.0,0.066667,2.922212e-01,0.0000,2.000000e+00
RotBFrac,90.0,0.109133,5.148153e-02,0.0000,3.000000e-01
nF10Ring,90.0,1.655556,2.056293e+00,0.0000,1.300000e+01
ETA_BetaP_ns,90.0,0.807414,1.089213e-01,0.5688,1.024200e+00
nH,90.0,23.855556,5.781725e+00,14.0000,4.200000e+01
nL,90.0,0.133333,7.220445e-01,0.0000,6.000000e+00
nN,90.0,3.977778,1.919608e+00,0.0000,9.000000e+00
nO,90.0,3.111111,1.698938e+00,0.0000,8.000000e+00
nA,90.0,0.122222,4.194104e-01,0.0000,2.000000e+00
nC,90.0,31.355556,4.026070e+00,21.0000,4.000000e+01
nF,90.0,0.144444,4.386166e-01,0.0000,3.000000e+00
nX,90.0,0.244444,5.670961e-01,0.0000,3.000000e+00
nQ,90.0,0.044444,2.072349e-01,0.0000,1.000000e+00
nS,90.0,0.288889,5.852963e-01,0.0000,2.000000e+00
nV,90.0,0.088889,4.144699e-01,0.0000,2.000000e+00
ATS1m,90.0,7452.895689,7.510098e+02,5754.3065,8.910446e+03
mindsN,90.0,1.258126,2.106675e+00,0.0000,5.228700e+00
SHCsats,90.0,1.852778,1.851610e+00,0.0000,6.283500e+00
SHCsatu,90.0,0.578996,1.020352e+00,0.0000,4.493600e+00
CrippenMR,90.0,150.399783,2.413137e+01,0.0000,1.805565e+02
GATS1p,90.0,0.919020,1.308563e-01,0.5705,1.293000e+00
SRW10,90.0,10.815714,2.162106e-01,10.0639,1.148430e+01
ETA_dPsi_A,90.0,0.121474,3.066840e-02,0.0256,1.982000e-01
AATS6m,90.0,72.156057,1.438770e+01,40.0774,1.083080e+02
AATS6i,90.0,156.044158,3.628714e+00,146.8943,1.639337e+02
AATS6e,90.0,7.735657,2.086571e-01,7.2369,8.350900e+00
minsBr,90.0,0.004229,4.011876e-02,0.0000,3.806000e-01
nF9HeteroRing,90.0,1.277778,1.101865e+00,0.0000,5.000000e+00
SpMin7_Bhi,90.0,1.195830,1.167966e-01,0.9236,1.407800e+00
AATS6v,90.0,207.201922,2.695504e+01,144.3076,2.707278e+02
AATS6p,90.0,1.481568,1.386872e-01,1.1420,1.821500e+00
AATS6s,90.0,3.398727,7.825438e-01,2.0177,5.675400e+00
naAromAtom,90.0,26.522222,5.363689e+00,16.0000,4.200000e+01
nBase,90.0,0.222222,7.757241e-01,-1.0000,5.000000e+00
minHBint10,90.0,0.164552,7.198077e-01,0.0000,6.008700e+00
SpDiam_DzZ,90.0,304.017126,6.900181e+01,159.9634,4.801856e+02
SaaNH,90.0,0.379350,1.410359e+00,0.0000,7.006000e+00
khs.dNH,90.0,0.011111,1.054093e-01,0.0000,1.000000e+00
maxaaN,90.0,2.331209,2.409194e+00,0.0000,5.180800e+00
maxaaO,90.0,0.571514,1.727170e+00,0.0000,6.057800e+00
SpDiam_Dzv,90.0,373.143234,9.017607e+01,170.9444,6.128502e+02
SpDiam_Dzs,90.0,374.402091,1.067850e+02,162.2852,7.122228e+02
SpDiam_Dzp,90.0,406.019042,1.035261e+02,183.2520,7.076270e+02
SpDiam_Dze,90.0,308.044658,6.831530e+01,159.9879,4.809287e+02
SpDiam_Dzm,90.0,304.049196,6.900822e+01,159.9753,4.802879e+02
GATS6i,90.0,1.017649,1.146203e-01,0.7344,1.287100e+00
SpDiam_Dzi,90.0,299.677989,6.514801e+01,161.2220,4.565990e+02
Mi,90.0,7.471269,7.223893e-02,7.2942,7.616000e+00
Mv,90.0,0.696364,3.451243e-02,0.6297,7.947000e-01
Mp,90.0,0.728818,2.525799e-02,0.6838,8.024000e-01
GGI10,90.0,0.270558,1.038743e-01,0.0000,6.081000e-01
bpol,90.0,35.753070,7.635828e+00,19.4073,5.136580e+01
MW,90.0,521.737769,5.325645e+01,396.1144,5.991627e+02
GATS6v,90.0,1.007797,1.048780e-01,0.6973,1.283100e+00
MATS7s,90.0,-0.012953,1.198071e-01,-0.2838,3.311000e-01
MATS7p,90.0,-0.013682,8.103905e-02,-0.2293,1.575000e-01
MATS7v,90.0,-0.026024,8.416776e-02,-0.2570,1.689000e-01
MATS7i,90.0,0.003432,8.858239e-02,-0.2157,1.968000e-01
MATS7m,90.0,-0.035138,9.956157e-02,-0.2724,2.906000e-01
MATS7c,90.0,0.008229,1.228634e-01,-0.3590,2.466000e-01
GATS6s,90.0,1.117141,2.883383e-01,0.5066,1.717100e+00
MATS7e,90.0,-0.007313,1.485803e-01,-0.3328,3.680000e-01
maxtN,90.0,0.339754,1.841330e+00,0.0000,1.075450e+01
SpMin8_Bhe,90.0,1.109531,1.227868e-01,0.7986,1.384900e+00
SpMin8_Bhi,90.0,1.071219,1.225193e-01,0.7386,1.330600e+00
SpMin8_Bhm,90.0,1.286573,1.212658e-01,1.0531,1.542600e+00
SpMin8_Bhp,90.0,1.300656,1.364856e-01,0.9828,1.569200e+00
SpMin8_Bhs,90.0,1.142241,1.304595e-01,0.8581,1.457700e+00
SpMin8_Bhv,90.0,1.302286,1.305434e-01,1.0072,1.564300e+00
maxHCsatu,90.0,0.316409,4.264343e-01,0.0000,1.105800e+00
maxHCsats,90.0,0.454376,3.977548e-01,0.0000,1.105800e+00
ATSC3v,90.0,-178.414096,4.399494e+02,-1688.9459,1.280791e+03
ATSC3s,90.0,-3.711674,1.520663e+01,-50.5569,3.389560e+01
ATSC3p,90.0,-2.018352,2.267580e+00,-9.7870,4.210800e+00
ATSC3e,90.0,-0.388349,7.413006e-01,-2.8927,1.557300e+00
ATSC3c,90.0,-0.093832,2.015243e-01,-0.7248,3.029000e-01
maxssNH,90.0,0.634172,1.237416e+00,0.0000,3.676500e+00
ATSC3m,90.0,-52.896679,5.489021e+02,-1977.4375,9.577934e+02
ATSC3i,90.0,-16.816917,2.130231e+01,-69.2272,5.862030e+01
minHCsatu,90.0,0.290286,3.915766e-01,0.0000,1.042800e+00
minHCsats,90.0,0.365431,3.265382e-01,0.0000,9.044000e-01
SpMax7_Bhe,90.0,3.246126,1.372078e-01,2.8993,3.464200e+00
SpMax7_Bhi,90.0,3.286248,1.369785e-01,2.9641,3.520400e+00
SpMax7_Bhm,90.0,3.187316,1.381847e-01,2.7609,3.406100e+00
ETA_BetaP_ns_d,90.0,0.009286,1.377099e-02,0.0000,7.900000e-02
SpMax7_Bhp,90.0,3.104681,1.356874e-01,2.7377,3.384700e+00
SpMax7_Bhs,90.0,3.569914,2.487050e-01,2.9550,4.132400e+00
SpMax7_Bhv,90.0,3.109068,1.391273e-01,2.7250,3.369300e+00
SdsCH,90.0,0.566581,1.241601e+00,0.0000,5.087800e+00
minssO,90.0,1.478181,2.546386e+00,0.0000,6.808500e+00
minssS,90.0,-0.110293,4.613218e-01,-2.3467,0.000000e+00
SpMin3_Bhe,90.0,1.838157,6.117384e-02,1.5761,1.955900e+00
SpMin3_Bhm,90.0,1.918358,6.745947e-02,1.6590,2.013500e+00
SpMin3_Bhi,90.0,1.817206,6.327288e-02,1.5289,1.941100e+00
SpMin3_Bhv,90.0,1.940903,4.070696e-02,1.7898,2.023800e+00
SpMin3_Bhs,90.0,1.857769,6.195644e-02,1.5250,1.979600e+00

In [7]:
# Categorical Feature Statistics
cat_stats

                   value  count   pct
column        rank
PeriodChanger 1       No     63  70.0
              2      Yes     27  30.0

In [8]:
# Target Distribution
target_df

               count   pct
PeriodChanger
No                63  70.0
Yes               27  30.0

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=20, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to clock_protein_period/019d9cd1-aa5a-7b4d-a6a3-75423c198efe
019d9cd1-aa5a-7b4d-a6a3-75423c198efe
0e258f5b706f713fbd82203b346c244425756b2afa99d07382bfcebbcb3173ef