### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="pva_revenue_prediction_kddcup98",
    dataset_year="1997",
    domain_str="business & marketing",
    # Data Source
    dataset_source="Other",
    original_dataset_source_download_link="https://kdd.ics.uci.edu/databases/kddcup98/kddcup98.html", # Rel 10.24432/C5401H
    download_description="""

wget https://kdd.ics.uci.edu/databases/kddcup98/epsilon_mirror/cup98lrn.zip && unzip cup98lrn && rm cup98lrn.zip
wget https://kdd.ics.uci.edu/databases/kddcup98/epsilon_mirror/cup98val.zip && unzip cup98val && rm cup98val.zip && wget https://kdd.ics.uci.edu/databases/kddcup98/epsilon_mirror/valtargt.txt
mkdir -p local-data-warehouse/pva_revenue_prediction_kddcup98 && mv cup98VAL.txt local-data-warehouse/pva_revenue_prediction_kddcup98/ && mv cup98LRN.txt local-data-warehouse/pva_revenue_prediction_kddcup98/ && mv valtargt.txt local-data-warehouse/pva_revenue_prediction_kddcup98/
""",
    # References
    academic_reference_bibtex=r"""@misc{Parsa1998KDDCup1998,
  author = {Ismail Parsa},
  title  = {KDD Cup 1998},
  year   = {1998},
  howpublished = {\url{https://kdd.ics.uci.edu/databases/kddcup98/kddcup98.html}},
  note   = {Dataset, UCI Machine Learning Repository. DOI: 10.24432/C5401H}
}
""",
    academic_reference_bibtex_key="Parsa1998KDDCup1998",
    license=None, # Unclear but has usage instruction that do not count as license (?)
    data_tags=["IID"],
    curation_comments="""
We start with the train and validation data from the KDD Cup 1998 website and combine them.

- The description of the task and data for the KDD Cup (https://kdd.ics.uci.edu/databases/kddcup98/epsilon_mirror/cup98doc.txt) is among the best real-world dataset and task descriptions I have ever seen.
- The task was made IID through feature engineering and would usually used to predict the next year. We only predict from the training data from the current year, other samples from the current year (as to see who else to contact in the same year). Features contain information from the previous year.
- The task is revenue generation and the score function is profit-based with a cost of $0.68 per prediction. The higher the revenue generated, the better. We use the binary classification target (TARGET_B) to predict if a person would donate.
- The TCODE contains titles now in the data dictionary. We map large amount of missing values to placeholder titles and the smaller ones to a new "other" title.
- We treat data as string or category based on the data dictionary suggestions. In cases where the column is from a predefined set of choices, it becomes categorical. We treat various free-text categorical as string columns (they are also high-cardinality otherwise).
- We transform the date columns to pandas datetime.
- The data contains spatial information (ZIP, STATE). We do not resolve them and leave them for the pipeline to handle.
- We remove a faulty postfix ("-") in the ZIP code.
- We drop rows with PVASTATE='E' as this represent a group of donors represent by a different organization chapter. These are 8 rows only.
- The data contains two entries with a faulty day of birth (born in month 00). We drop both rows, as we assume this is indicative of faulty data.
- We noticed that nan values and dtypes mismatch for NOEXCH do correlate with the target. We add these cases as their own categories.
- We resolve the ordinal encoding and nan encoding for all columns.
- Note, that data has a lot of features that contain data from a similar origin that was transformed into individual columns.
- We do not decode the promotion codes across years but keep them as string columns as it would blow up the dimensionality too much otherwise.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="TARGET_B",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="TARGET_B",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(dataset_mold.path / "cup98LRN.txt")
val_df = pd.read_csv(dataset_mold.path / "cup98VAL.txt")
val_targets = pd.read_csv(dataset_mold.path / "valtargt.txt")
df = pd.concat([df, val_df.merge(val_targets, on="CONTROLN")], axis=0).reset_index(drop=True)

/tmp/ipykernel_119432/1021879402.py:4: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dataset_mold.path / "cup98LRN.txt")
/tmp/ipykernel_119432/1021879402.py:5: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  val_df = pd.read_csv(dataset_mold.path / "cup98VAL.txt")

In [3]:
title_code_map = {0: "No Title", 1: "MR.", 1001: "MESSRS.", 1002: "MR. & MRS.", 2: "MRS.", 2002: "MESDAMES", 3: "MISS", 3003: "MISSES", 4: "DR.", 4002: "DR. & MRS.", 4004: "DOCTORS", 5: "MADAME", 6: "SERGEANT", 9: "RABBI", 10: "PROFESSOR", 10002: "PROFESSOR & MRS.", 10010: "PROFESSORS", 11: "ADMIRAL", 11002: "ADMIRAL & MRS.", 12: "GENERAL", 12002: "GENERAL & MRS.", 13: "COLONEL", 13002: "COLONEL & MRS.", 14: "CAPTAIN", 14002: "CAPTAIN & MRS.", 15: "COMMANDER", 15002: "COMMANDER & MRS.", 16: "DEAN", 17: "JUDGE", 17002: "JUDGE & MRS.", 18: "MAJOR", 18002: "MAJOR & MRS.", 19: "SENATOR", 20: "GOVERNOR", 21002: "SERGEANT & MRS.", 22002: "COLNEL & MRS.", 24: "LIEUTENANT", 26: "MONSIGNOR", 27: "REVEREND", 28: "MS.", 28028: "MSS.", 29: "BISHOP", 31: "AMBASSADOR", 31002: "AMBASSADOR & MRS.", 33: "CANTOR", 36: "BROTHER", 37: "SIR", 38: "COMMODORE", 40: "FATHER", 42: "SISTER", 43: "PRESIDENT", 44: "MASTER", 46: "MOTHER", 47: "CHAPLAIN", 48: "CORPORAL", 50: "ELDER", 56: "MAYOR", 59002: "LIEUTENANT & MRS.", 62: "LORD", 63: "CARDINAL", 64: "FRIEND", 65: "FRIENDS", 68: "ARCHDEACON", 69: "CANON", 70: "BISHOP", 72002: "REVEREND & MRS.", 73: "PASTOR", 75: "ARCHBISHOP", 85: "SPECIALIST", 87: "PRIVATE", 89: "SEAMAN", 90: "AIRMAN", 91: "JUSTICE", 92: "MR. JUSTICE", 100: "M.", 103: "MLLE.", 104: "CHANCELLOR", 106: "REPRESENTATIVE", 107: "SECRETARY", 108: "LT. GOVERNOR", 109: "LIC.", 111: "SA.", 114: "DA.", 116: "SR.", 117: "SRA.", 118: "SRTA.", 120: "YOUR MAJESTY", 122: "HIS HIGHNESS", 123: "HER HIGHNESS", 124: "COUNT", 125: "LADY", 126: "PRINCE", 127: "PRINCESS", 128: "CHIEF", 129: "BARON", 130: "SHEIK", 131: "PRINCE AND PRINCESS", 132: "YOUR IMPERIAL MAJEST", 135: "M. ET MME.", 210: "PROF."}
recency_map = {
    "C": "Current Donor",
    "L": "Lapsed Donor",
    "I": "Inactive Donor",
    "D": "Dormant Donor",
}
frequency_map = {
    "1": "One gift in the period of recency",
    "2": "Two-Four gifts in the period of recency",
    "5": "Five+ gifts in the period of recency",
}
amount_map = {
    "L": "Less than $100 (Low Dollar)",
    "C": "$100-499 (Core)",
    "M": "$500-999 (Major)",
    "T": "$1,000+ (Top)",
}
urbanicity_map = {
    "U": "Urban",
    "C": "City",
    "S": "Suburban",
    "T": "Town",
    "R": "Rural",
}
ses_map = {
    "1": "Highest SES",
    "2": "Average SES",
    "3": "Lowest SES",
    "4": "Lower Lowest SES in Urban communities", # weird name to show it is lower as otherwise we would need to rename 2 and 3 only for urban cases, but this should be fine.
}

In [4]:
# Handle DOB
df = df[~df["DOB"].replace(np.nan, 1111).astype(float).astype(int).astype(str).str.zfill(4).str.endswith("00")] # drop 2 rows with month 00
df["DOB"] = df["DOB"].replace(0, np.nan)
dob_nan_mask = df["DOB"].isna()
df.loc[dob_nan_mask, "DOB"] = 0
df["DOB"] = df["DOB"].astype(float).astype(int).astype("string").str.zfill(4)
df.loc[dob_nan_mask, "DOB"] = np.nan
df["DOB"] = pd.to_datetime("19" + df["DOB"], format="%Y%m")

# Make pd Dates (unclear if best preprocessing is not just int as in original data but this way we have the correct metadata of the col)
prom_dates = [
    "ADATE_2","ADATE_3","ADATE_4","ADATE_5","ADATE_6","ADATE_7","ADATE_8",
    "ADATE_9","ADATE_10","ADATE_11","ADATE_12","ADATE_13","ADATE_14",
    "ADATE_15","ADATE_16","ADATE_17","ADATE_18","ADATE_19","ADATE_20",
    "ADATE_21","ADATE_22","ADATE_23","ADATE_24",
    "RDATE_3","RDATE_4","RDATE_5","RDATE_6","RDATE_7","RDATE_8","RDATE_9",
    "RDATE_10","RDATE_11","RDATE_12","RDATE_13","RDATE_14","RDATE_15",
    "RDATE_16","RDATE_17","RDATE_18","RDATE_19","RDATE_20","RDATE_21",
    "RDATE_22","RDATE_23","RDATE_24",
    "MAXADATE", "ODATEDW",
    "MINRDATE", "MAXRDATE", "LASTDATE", "FISTDATE", "NEXTDATE",
]
df["FISTDATE"] = df["FISTDATE"].replace(0, np.nan)
for col in prom_dates:
    nan_mask = df[col].isna()
    df.loc[nan_mask, col] = 1111
    df[col] = pd.to_datetime("19" + df[col].astype(int).astype("string"), format="%Y%m")
    df.loc[nan_mask, col] = np.nan

# Update title map
missing_title_in_data_dic = list(np.unique(df[~df["TCODE"].isin(title_code_map.keys())]["TCODE"]))
for code in missing_title_in_data_dic:
    title_code_map[code] = f"Missing Title {code}"
# Replace Title
assert df["TCODE"].isin(title_code_map.keys()).all(), "Some TCODE values are not in the title_code_map"
df["Title"] = df["TCODE"].map(title_code_map)
df = df.drop(columns=["TCODE"])

# Handle outsource codes
df["OSOURCE"] = df["OSOURCE"].replace(" ", np.nan)
# Remove postfix from ZIP
df["ZIP"] = df["ZIP"].str.replace("-", "")
# Handle mailcode
df["MAILCODE"] = df["MAILCODE"].replace({" ": "Address is OK", "B": "Bad Address"})
# Handle missing values PVASTATE
df["PVASTATE"] = df["PVASTATE"].replace(" ", np.nan)
df = df[df["PVASTATE"] != "E"]
# a scatterplot of these values and the targets shows some superficial correlation
df["NOEXCH"] = df["NOEXCH"].replace({" ": "can be exchanged", "X": "cannot be exchanged", 0: "0-nan-case", "0": "0-nan-case", 1: "1-nan-case", "1": "1-nan-case"})# .value_counts(dropna=False)
# -- Resolve some of the cat variables
df["RECINHSE"] = df["RECINHSE"].replace({
    " ": "Not an In House Record",
    "X": "Donor has given to PVA's In House program"
})
df["RECP3"] = df["RECP3"].replace({
    " ": "Not a P3 Record",
    "X": "Donor has given to PVA's P3 program"
})
df["RECPGVG"] = df["RECPGVG"].replace({
    " ": "Not a Planned Giving Record",
    "X": "Planned Giving Record"
})
df["RECSWEEP"] = df["RECSWEEP"].replace({
    " ": "Not a Sweepstakes Record",
    "X": "Sweepstakes Record"
})
# -- Resolve MDMAUD
# Split into 4 bytes (pad right so short strings don't error)
b = df["MDMAUD"].str.pad(4, side="right").str[:4]
b1, b2, b3 = b.str[0], b.str[1], b.str[2]
# Create categorical columns using the descriptions
df["MDMAUD_recency"]   = b1.map(recency_map)
df["MDMAUD_frequency"] = b2.map(frequency_map)
df["MDMAUD_amount"]    = b3.map(amount_map)
df["MAJOR"] = df["MAJOR"].replace({" ": "Not a Major Donor", "X": "Major Donor"})
assert ((df["MAJOR"] == "Not a Major Donor") == df["MDMAUD"].str.upper().eq("XXXX")).all()
df.loc[df["MAJOR"] == "Not a Major Donor", ["MDMAUD_recency", "MDMAUD_frequency", "MDMAUD_amount"]] = "Not applicable"

df = df.drop(columns=["MDMAUD"]) # can be recovered by pipelines if needed via arithmetic interactions
# Resolve DOMAIN Code
s = df["DOMAIN"].replace(" ", np.nan).astype("string")
b = s.str.pad(2, side="right")
b1 = b.str[0]
b2 = b.str[1]
df["DOMAIN_urbanicity"] = b1.map(urbanicity_map)
df["DOMAIN_ses"] = b2.map(ses_map)
df = df.drop(columns=["DOMAIN"])
# Cluster fix nan
df["CLUSTER"] = df["CLUSTER"].replace(" ", np.nan) # Likely not Ordinal
# Age (has no - values like data dict is saying), so skip but resolve for ageflag
df["AGEFLAG"] = df["AGEFLAG"].replace({0: np.nan, "E": "Exact", "I": "Inferred from Date of Birth Field"})
df["HOMEOWNR"] = df["HOMEOWNR"].replace({" ": np.nan, "H": "Homeowner", "U": "Unknown"})
# Resolve child
child_map = {"B": "Both", "F": "Female", "M": "Male", " ": np.nan}
child_cols = ["CHILD03", "CHILD07", "CHILD12", "CHILD18"]
for col in child_cols:
    df[col] = df[col].replace(child_map)
df["GENDER"] = df["GENDER"].replace({"M": "Male", "F": "Female", "U": "Unknown", " ": np.nan, "J": "Joint Account, unknown gender"})
df["DATASRCE"] = df["DATASRCE"].replace({" ": np.nan, "1": "MetroMail", "2":"Polk", "3":"Both"})
# Not Ordinal/Int as 0 is equal to INF
df["SOLIH"] = df["SOLIH"].replace({" ": "can be mailed (Default)","00":"Do Not Solicit","01":"one solicitation per year","02":"two solicitations per year","03":"three solicitations per year","04":"four solicitations per year","05":"five solicitations per year","06":"six solicitations per year","12":"twelve solicitations per year"})
df["SOLP3"] = df["SOLP3"].replace({" ": "can be mailed (Default)","00":"Do Not Solicit or Mail","01":"one solicitation per year","02":"two solicitations per year","03":"three solicitations per year","04":"four solicitations per year","05":"five solicitations per year","06":"six solicitations per year","12":"twelve solicitations per year"})
df["GEOCODE"] = df["GEOCODE"].replace(" ", "No code has been assigned or did not match at any level")
df["LIFESRC"] = df["LIFESRC"].replace({" ": np.nan, "1": "MATCHED ON METRO MAIL ONLY","2":"MATCHED ON POLK ONLY","3":"MATCHED BOTH MM AND POLK"})
df["PEPSTRFL"] = df["PEPSTRFL"].replace({" ": np.nan, "X": "Has PEP Star RFA Status"})
df["GEOCODE2"] = df["GEOCODE2"].replace(" ", np.nan)
# Resolve interests
y_n_map_list = [
    "COLLECT1","VETERANS","BIBLE","CATLG","HOMEE","PETS","CDPLAY","STEREO",
    "PCOWNERS","PHOTO","CRAFTS","FISHER","GARDENIN","BOATS","WALKER",
    "KIDSTUFF","CARDS","PLATES"
]
for col in y_n_map_list:
    # Data dir says it is yes/no, but data is yes or missing, so I will go for missing as it is more general
    assert np.unique(df[col].dropna()).tolist() == [" ", "Y"]
    df[col] = df[col].replace({"Y": "Yes", " ": np.nan})

df = df.drop(columns=[
    "CONTROLN", # uninformative index column
    "RFA_2R", # constant col
    # Already decoded above and added semantics
    "MDMAUD_R", "MDMAUD_A", "MDMAUD_F",
    # Other target
    "TARGET_D",
])

# -- Dtypes
as_type_str = [
    "OSOURCE", "STATE", "ZIP", "Title",
    # RFA codes (not decoded as too many columns otherwise)
    "RFA_2","RFA_3","RFA_4","RFA_5","RFA_6","RFA_7","RFA_8","RFA_9",
    "RFA_10","RFA_11","RFA_12","RFA_13","RFA_14","RFA_15","RFA_16",
    "RFA_17","RFA_18","RFA_19","RFA_20","RFA_21","RFA_22","RFA_23","RFA_24"
]
as_type_cat = [
    "PVASTATE", "MAILCODE", "NOEXCH", "RECINHSE", "RECP3", "RECPGVG", "RECSWEEP",
    "MDMAUD_recency", "MDMAUD_frequency", "MDMAUD_amount", "MAJOR",
    "DOMAIN_urbanicity", "DOMAIN_ses", "CLUSTER", "CLUSTER2", "AGEFLAG", "HOMEOWNR",
    "CHILD03", "CHILD07", "CHILD12", "CHILD18", "GENDER", "DATASRCE", "SOLIH",
    "SOLP3", "GEOCODE", "GEOCODE2", "LIFESRC", "PEPSTRFL", "HPHONE_D",
    "RFA_2F", "RFA_2A",
    "TARGET_B", # will be dropped later, but making sure it is valid
] + y_n_map_list

for c in as_type_str:
    df[c] = df[c].replace(" ", np.nan)
    nan_mask = df[c].isna()
    df.loc[nan_mask, c] = np.nan
    df[c] = df[c].astype("string")

df[as_type_cat] = df[as_type_cat].astype("category")

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [5]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

Warning: Found 8 constant feature(s) with 1 or fewer unique values (including NaNs): ['RFA_5', 'RFA_15', 'RFA_17', 'RFA_18', 'RFA_19', 'RFA_20', 'RFA_23', 'RFA_24']

#### Dataset Overview
Rows: 144,095
Columns: 478
Use sampling: False (sample size: 144,095)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['IC5', 'ZIP', 'POP901', 'AVGGIFT', 'POP903', 'POP902', 'HV2', 'HV1', 'RAMNTALL', 'IC2']
Rows remaining as candidates after top-10 filter: 792 (of 144,095)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [6]:
# Sample Rows
df_head

,ODATEDW,OSOURCE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,RECP3,RECPGVG,RECSWEEP,CLUSTER,AGE,AGEFLAG,HOMEOWNR,CHILD03,CHILD07,CHILD12,CHILD18,NUMCHLD,INCOME,GENDER,WEALTH1,HIT,MBCRAFT,MBGARDEN,MBBOOKS,MBCOLECT,MAGFAML,MAGFEM,MAGMALE,PUBGARDN,PUBCULIN,PUBHLTH,PUBDOITY,PUBNEWFN,PUBPHOTO,PUBOPP,DATASRCE,MALEMILI,MALEVET,VIETVETS,WWIIVETS,LOCALGOV,STATEGOV,FEDGOV,SOLP3,SOLIH,MAJOR,WEALTH2,GEOCODE,COLLECT1,VETERANS,BIBLE,CATLG,HOMEE,PETS,CDPLAY,STEREO,PCOWNERS,PHOTO,CRAFTS,FISHER,GARDENIN,BOATS,WALKER,KIDSTUFF,CARDS,PLATES,LIFESRC,PEPSTRFL,POP901,POP902,POP903,POP90C1,POP90C2,POP90C3,POP90C4,POP90C5,ETH1,ETH2,ETH3,ETH4,ETH5,ETH6,ETH7,ETH8,ETH9,ETH10,ETH11,ETH12,ETH13,ETH14,ETH15,ETH16,AGE901,AGE902,AGE903,AGE904,AGE905,AGE906,AGE907,CHIL1,CHIL2,CHIL3,AGEC1,AGEC2,AGEC3,AGEC4,AGEC5,AGEC6,AGEC7,CHILC1,CHILC2,CHILC3,CHILC4,CHILC5,HHAGE1,HHAGE2,HHAGE3,HHN1,HHN2,HHN3,HHN4,HHN5,HHN6,MARR1,MARR2,MARR3,MARR4,HHP1,HHP2,DW1,DW2,DW3,DW4,DW5,DW6,DW7,DW8,DW9,HV1,HV2,HV3,HV4,HU1,HU2,HU3,HU4,HU5,HHD1,HHD2,HHD3,HHD4,HHD5,HHD6,HHD7,HHD8,HHD9,HHD10,HHD11,HHD12,ETHC1,ETHC2,ETHC3,ETHC4,ETHC5,ETHC6,HVP1,HVP2,HVP3,HVP4,HVP5,HVP6,HUR1,HUR2,RHP1,RHP2,RHP3,RHP4,HUPA1,HUPA2,HUPA3,HUPA4,HUPA5,HUPA6,HUPA7,RP1,RP2,RP3,RP4,MSA,ADI,DMA,IC1,IC2,IC3,IC4,IC5,IC6,IC7,IC8,IC9,IC10,IC11,IC12,IC13,IC14,IC15,IC16,IC17,IC18,IC19,IC20,IC21,IC22,IC23,HHAS1,HHAS2,HHAS3,HHAS4,MC1,MC2,MC3,TPE1,TPE2,TPE3,TPE4,TPE5,TPE6,TPE7,TPE8,TPE9,PEC1,PEC2,TPE10,TPE11,TPE12,TPE13,LFC1,LFC2,LFC3,LFC4,LFC5,LFC6,LFC7,LFC8,LFC9,LFC10,OCC1,OCC2,OCC3,OCC4,OCC5,OCC6,OCC7,OCC8,OCC9,OCC10,OCC11,OCC12,OCC13,EIC1,EIC2,EIC3,EIC4,EIC5,EIC6,EIC7,EIC8,EIC9,EIC10,EIC11,EIC12,EIC13,EIC14,EIC15,EIC16,OEDC1,OEDC2,OEDC3,OEDC4,OEDC5,OEDC6,OEDC7,EC1,EC2,EC3,EC4,EC5,EC6,EC7,EC8,SEC1,SEC2,SEC3,SEC4,SEC5,AFC1,AFC2,AFC3,AFC4,AFC5,AFC6,VC1,VC2,VC3,VC4,ANC1,ANC2,ANC3,ANC4,ANC5,ANC6,ANC7,ANC8,ANC9,ANC10,ANC11,ANC12,ANC13,ANC14,ANC15,POBC1,POBC2,LSC1,LSC2,LSC3,LSC4,VOC1,VOC2,VOC3,HC1,HC2,HC3,HC4,HC5,HC6,HC7,HC8,HC9,HC10,HC11,HC12,HC13,HC14,HC15,HC16,HC17,HC18,HC19,HC20,HC21,MHUC1,MHUC2,AC1,AC2,ADATE_2,ADATE_3,ADATE_4,ADATE_5,ADATE_6,ADATE_7,ADATE_8,ADATE_9,ADATE_10,ADATE_11,ADATE_12,ADATE_13,ADATE_14,ADATE_15,ADATE_16,ADATE_17,ADATE_18,ADATE_19,ADATE_20,ADATE_21,ADATE_22,ADATE_23,ADATE_24,RFA_2,RFA_3,RFA_4,RFA_5,RFA_6,RFA_7,RFA_8,RFA_9,RFA_10,RFA_11,RFA_12,RFA_13,RFA_14,RFA_15,RFA_16,RFA_17,RFA_18,RFA_19,RFA_20,RFA_21,RFA_22,RFA_23,RFA_24,CARDPROM,MAXADATE,NUMPROM,CARDPM12,NUMPRM12,RDATE_3,RDATE_4,RDATE_5,RDATE_6,RDATE_7,RDATE_8,RDATE_9,RDATE_10,RDATE_11,RDATE_12,RDATE_13,RDATE_14,RDATE_15,RDATE_16,RDATE_17,RDATE_18,RDATE_19,RDATE_20,RDATE_21,RDATE_22,RDATE_23,RDATE_24,RAMNT_3,RAMNT_4,RAMNT_5,RAMNT_6,RAMNT_7,RAMNT_8,RAMNT_9,RAMNT_10,RAMNT_11,RAMNT_12,RAMNT_13,RAMNT_14,RAMNT_15,RAMNT_16,RAMNT_17,RAMNT_18,RAMNT_19,RAMNT_20,RAMNT_21,RAMNT_22,RAMNT_23,RAMNT_24,RAMNTALL,NGIFTALL,CARDGIFT,MINRAMNT,MINRDATE,MAXRAMNT,MAXRDATE,LASTGIFT,LASTDATE,FISTDATE,NEXTDATE,TIMELAG,AVGGIFT,TARGET_B,HPHONE_D,RFA_2F,RFA_2A,CLUSTER2,GEOCODE2,Title,MDMAUD_recency,MDMAUD_frequency,MDMAUD_amount,DOMAIN_urbanicity,DOMAIN_ses
0,1995-01-01,MM1,CA,91702,Address is OK,NaN,1916-01-01,0-nan-case,Not an In House Record,Not a P3 Record,Not a Planned Giving Record,Not a Sweepstakes Record,21,82.0,Exact,Homeowner,NaN,NaN,NaN,NaN,NaN,1.0,Male,1.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Both,0,24,25,30,3,1,1,can be mailed (Default),can be mailed (Default),Not a Major Donor,NaN,No code has been assigned or did not match at any level,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1510,344,464,99,0,0,49,51,59,2,1,2,67,0,0,1,1,0,0,0,60,0,1,5,27,35,40,30,41,45,32,44,38,18,19,30,16,11,11,8,5,19,17,33,18,13,23,9,20,19,27,53,37,24,13,53,12,6,29,220,317,74,67,5,26,20,12,0,0,0,1667,1761,5,5,49,51,95,5,0,44,74,54,33,85,15,11,3,8,14,20,6,15,32,11,1,2,0,23,67,88,97,99,5,16,28,46,44,16,7,17,9,0,26,13,12,0,43,64,89,97,4480.0,13.0,803.0,224,250,295,316,8745,25,27,17,19,5,4,2,0,0,18,32,18,22,2,5,2,0,0,24,14,16,16,44,56,10,67,26,0,0,0,0,0,7,0,2,11,23,27,2,70,63,76,51,69,51,40,35,44,0,13,7,4,1,11,16,0,3,9,2,14,16,7,10,5,0,9,29,3,1,7,18,6,3,0,1,6,6,6,1,3,1,1,5,84,5,1,118,28,23,21,21,4,2,1,3,31,2,24,8,0,0,0,12,24,0,25,16,30,33,0,0,0,2,0,0,0,2,1,0,0,0,0,0,0,33,44,49,47,2,2,92,57,15,7,42,0,0,0,0,13,87,0,0,99,0,1,0,0,0,99,0,99,99,98,11,2,6,6,1997-06-01,1996-06-01,1996-04-01,NaT,1996-03-01,1996-02-01,1996-01-01,1995-11-01,1995-11-01,1995-10-01,1995-09-01,1995-07-01,1995-06-01,NaT,1995-03-01,NaT,NaT,NaT,NaT,1994-09-01,1994-09-01,NaT,NaT,L3E,A2E,A2E,<NA>,A2E,N2E,N2E,N2E,N2E,N2E,N2E,N2E,F1E,<NA>,F1E,<NA>,<NA>,<NA>,<NA>,P1E,P1A,<NA>,<NA>,10,1997-02-01,22,5,11,NaT,NaT,NaT,NaT,1996-03-01,NaT,NaT,NaT,NaT,NaT,1995-11-01,NaT,NaT,1995-04-01,NaT,NaT,NaT,NaT,1994-11-01,NaT,NaT,NaT,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,5.0,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,32.00,4,1,5.00,1995-04-01,10.0,1994-11-01,7.0,1996-03-01,1994-11-01,1995-04-01,5.0,8.000000,0,1,3,E,26.0,A,MR.,Not applicable,Not applicable,Not applicable,Suburban,Lowest SES
1,1990-01-01,MAD,MI,48034,Address is OK,NaN,1902-04-01,0-nan-case,Not an In House Record,Not a P3 Record,Not a Planned Giving Record,Not a Sweepstakes Record,11,96.0,Exact,Homeowner,NaN,NaN,NaN,NaN,NaN,3.0,Male,7.0,9,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Both,0,29,10,62,1,3,1,can be mailed (Default),can be mailed (Default),Not a Major Donor,7.0,No code has been assigned or did not match at any level,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MATCHED ON POLK ONLY,Has PEP Star RFA Status,1892,534,918,99,0,0,45,55,80,16,0,3,1,1,0,1,0,0,0,0,1,0,0,1,41,47,50,43,50,52,16,51,33,16,7,19,19,13,15,17,10,21,19,35,13,12,35,17,33,37,37,25,13,4,1,56,12,11,21,134,206,69,25,0,28,28,27,0,0,0,868,891,5,5,62,38,93,7,3,19,58,48,14,76,24,5,1,4,14,33,4,10,43,28,3,11,1,1,3,18,78,96,0,4,44,52,52,12,4,5,23,0,12,1,24,0,65,70,71,80,2160.0,57.0,505.0,391,488,473,575,22411,21,10,16,15,17,14,4,1,3,8,9,16,17,19,19,7,0,5,32,3,60,8,52,48,3,93,2,0,0,0,0,0,2,4,1,42,23,26,4,71,68,88,54,84,53,57,31,81,0,4,29,16,4,17,15,0,1,4,0,9,3,2,1,0,0,3,14,7,5,7,18,13,10,1,2,9,6,6,1,1,3,1,12,69,14,0,140,4,10,25,18,9,24,12,7,16,2,13,9,0,0,0,12,29,0,10,22,62,0,1,4,1,4,0,1,2,2,0,4,0,4,0,0,0,10,67,90,0,0,10,91,53,15,5,18,2,2,5,60,67,33,32,2,92,0,5,2,0,1,93,6,86,99,99,9,4,6,7,1997-06-01,1996-06-01,1996-04-01,1996-04-01,1996-03-01,1996-02-01,1996-01-01,1995-11-01,NaT,1995-10-01,1995-09-01,1995-07-01,1995-06-01,1995-04-01,1995-03-01,NaT,1994-12-01,1994-11-01,1994-11-01,1994-10-01,1994-09-01,1994-07-01,1994-06-01,L3E,A3E,A3E,A2E,A3E,A3E,A3E,A2E,<NA>,A2E,A2E,A3E,A3E,A3E,A2E,<NA>,A2E,A3E,A2E,A2E,A2E,A2E,A2E,22,1997-02-01,53,6,13,NaT,NaT,NaT,NaT,NaT,1996-02-01,NaT,NaT,NaT,1995-11-01,NaT,NaT,NaT,NaT,NaT,1995-01-01,NaT,1994-11-01,NaT,NaT,NaT,1994-07-01,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,12.0,NaN,9.0,NaN,NaN,NaN,10.0,100.00,11,8,5.00,1993-09-01,13.0,1996-02-01,13.0,1996-02-01,1990-09-01,1990-12-01,3.0,9.090909,0,0,3,E,19.0,A,MR.,Not applicable,Not applicable,Not applicable,Suburban,Highest SES
2,1989-01-01,IMP,TX,78209,Address is OK,NaN,1926-01-01,0-nan-case,Donor has given to PVA's In House program,Not a P3 Record,Not a Planned Giving Record,Not a Sweepstakes Record,15,72.0,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Female,7.0,7,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,MetroMail,3,22,36,63,11,2,0,can be mailed (Default),can be mailed (Default),Not a Major Donor,NaN,No code has been assigned or did not match at any level,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Has PEP Star RFA Status,874,175,565,99,0,0,43,57,92,0,0,0,19,0,0,0,0,0,0,0,17,0,0,2,35,39,41,40,44,47,12,30,41,29,11,29,21,11,10,8,9,15,15,29,19,22,22,17,21,63,25,12,5,1,0,30,22,9,39,79,155,21,15,4,79,75,54,0,0,0,1339,1439,3,4,20,80,89,11,10,13,31,21,7,50,50,6,0,6,30,43,6,8,64,19,0,0,0,14,44,65,82,95,4,11,20,42,44,10,3,47,32,0,7,22,50,0,22,36,67,93,7240.0,271.0,641.0,251,439,307,513,21683,29,20,16,17,12,3,0,2,0,10,17,16,10,30,11,0,7,0,28,6,44,17,63,37,7,82,0,6,6,0,0,0,12,0,0,5,18,22,4,71,61,77,51,66,49,69,17,83,0,14,29,18,4,13,19,2,2,4,0,6,2,2,0,0,0,2,4,2,4,7,19,9,2,7,5,6,15,11,7,11,2,0,12,65,10,0,152,12,6,11,25,1,35,10,7,9,0,5,11,1,3,0,10,22,2,36,43,63,0,0,9,0,4,0,0,10,2,0,0,0,0,1,0,0,6,64,70,30,0,0,77,18,0,3,23,0,0,4,40,65,35,12,0,74,0,26,0,0,0,99,0,99,99,97,12,2,6,11,1997-06-01,1996-06-01,1996-04-01,1996-04-01,NaT,1996-02-01,1996-01-01,1995-11-01,NaT,NaT,NaT,1995-07-01,1995-06-01,1995-04-01,NaT,1995-02-01,1994-12-01,1994-11-01,1994-11-01,1994-10-01,1994-09-01,1994-07-01,1994-06-01,L4D,A4D,A4D,A3D,<NA>,A4D,A4D,A3D,<NA>,<NA>,<NA>,A4D,A4D,A4D,<NA>,A4D,A4D,A4D,A4D,A4D,A4D,A3D,A2D,23,1997-02-01,60,4,9,NaT,NaT,NaT,NaT,NaT,1996-02-01,1995-12-01,NaT,NaT,NaT,1995-07-01,NaT,NaT,NaT,NaT,1995-09-01,1994-12-01,NaT,NaT,1994-11-01,NaT,NaT,NaN,NaN,NaN,NaN,NaN,5.0,7.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,5.0,7.0,NaN,NaN,5.0,NaN,NaN,99.05,18,8,4.05,1988-09-01,9.0,1990-05-01,5.0,1997-02-01,1988-09-01,1989-02-01,5.0,5.502778,0,1,4,D,24.0,B,MRS.,Not applicable,Not applicable,Not applicable,Suburban,Highest SES
3,1989-01-01,IMP,NC,28590,Address is OK,NaN,1932-01-01,0-nan-case,Donor has given to PVA's In House program,Not a P3 Record,Not a Planned Giving Record,Not a Sweepstakes Record,22,66.0,Exact,Unknown,NaN,Male,NaN,NaN,NaN,2.0,Male,9.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,MetroMail,0,26,40,22,6,21,4,can be mailed (Default),can be mailed (Default),Not a Major Donor,NaN,No code has been assigned or did not match at any level,NaN,NaN,NaN,Yes,NaN,Yes,NaN,NaN,Yes,NaN,Yes,NaN,Yes,NaN,NaN,NaN,NaN,NaN,MATCHED BOTH MM AND POLK,Has PEP Star RFA Status,2235,635,911,34,0,66,49,51,87,12,0,0,1,0,0,0,0,0,0,0,1,0,0,0,28,33,35,28,37,39,28,52,33,15,16,37,25,11,6,4,2,23,23,29,17,8,7,2,6,25,35,41,21,6,2,62,12,2,23,173,245,50,43,0,5,5,3,0,0,0,936,983,2,2,84,16,95,5,4,42,70,57,33,85,15,9,1,8,16,19,6,21,61,5,3,8,1,1,7,42,74,95,0,1,41,51,53,14,4,5,0,44,6,1,2,8,8,24,32,60,3150.0,353.0,545.0,256,338,312,356,12274,29,20,12,19,16,4,0,0,0,23,16,12,22,23,4,0,0,0,11,3,32,14,80,20,5,92,6,0,0,0,0,0,1,1,1,11,18,20,3,66,78,80,77,80,75,81,64,99,0,0,13,12,4,16,20,0,2,6,2,12,8,3,1,2,0,6,25,3,1,4,22,6,5,1,0,8,8,5,4,7,8,1,4,75,4,1,133,5,10,28,23,12,17,6,1,31,4,17,12,0,0,0,12,23,1,47,9,15,15,0,8,1,5,0,0,5,0,0,1,0,0,1,0,0,0,75,97,2,0,0,91,62,15,3,6,17,65,81,90,97,3,8,2,2,19,67,11,0,1,84,16,36,99,97,9,2,3,1,1997-06-01,1996-06-01,1996-04-01,1996-04-01,1996-03-01,1996-02-01,1996-01-01,1995-11-01,1995-10-01,1995-10-01,1995-08-01,NaT,1995-06-01,NaT,1995-03-01,1995-02-01,1995-01-01,1994-11-01,NaT,1994-10-01,1994-09-01,NaT,NaT,L2E,S3E,S3E,S3E,S2D,S2D,S2D,S2D,S2D,S2D,S2D,<NA>,A1D,<NA>,I3D,L1D,L1D,L1D,<NA>,L1D,L1D,<NA>,<NA>,25,1997-02-01,68,8,19,NaT,NaT,NaT,NaT,NaT,1996-01-01,NaT,NaT,NaT,NaT,NaT,1995-06-01,NaT,NaT,1995-03-01,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.00,13,8,2.00,1992-01-01,15.0,1996-12-01,15.0,1996-12-01,1989-01-01,1989-09-01,8.0,5.923077,0,1,2,E,52.0,C,MR.,Not applicable,Not applicable,Not applicable,City,Highest SES
4,1995-01-01,ADD,FL,32250,Address is OK,NaN,1960-01-01,0-nan-case,Not an In House Record,Not a P3 Record,Not a Planned Giving Record,Not a Sweepstakes Record,25,38.0,Exact,Unknown,NaN,NaN,NaN,NaN,NaN,3.0,Female,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Polk,3,20,42,19,6,4,1,can be mailed (Default),can be mailed (Default),Not a Major Donor,NaN,No code has been assigned or did not match at any level,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1516,340,712,99,0,0,53,47,82,14,0,3,3,0,0,0,2,0,0,0,0,1,0,1,28,33,38,32,38,43,19,45,33,22,23,30,19,10,8,6,4,20,15,31,17,17,14,6,13,37,34,30,12,5,2,38,20,4,38,140,213,36,29,21,63,42,26,0,0,0,662,687,4,4,38,62,79,21,20,23,48,32,13,63,37,11,2,9,35,23,16,11,63,8,5,8,1,1,3,6,32,77,0,11,15,41,42,12,4,44,19,0,15,35,11,0,17,51,82,92,3600.0,335.0,561.0,235,235,299,278,13338,29,26,17,15,6,5,2,0,0,18,43,19,7,11,2,0,0,0,19,3,19,16,73,27,25,68,19,4,4,0,0,0,7,2,1,6,27,28,4,73,78,83,71,82,69,65,26,95,99,2,7,19,1,9,21,0,0,17,5,8,7,2,5,0,0,6,7,7,5,2,16,13,9,8,11,4,2,6,5,6,4,1,3,81,5,0,120,8,15,32,17,6,14,8,1,21,2,14,6,2,3,0,12,20,0,42,9,19,25,0,9,0,8,0,1,6,6,0,0,0,1,3,0,0,3,31,96,2,0,3,90,39,8,1,11,7,22,45,64,67,33,3,9,0,16,72,8,0,2,99,0,99,98,83,7,2,4,1,1997-06-01,1996-06-01,1996-04-01,NaT,1996-03-01,1996-02-01,1996-01-01,1995-11-01,1995-10-01,1995-10-01,1995-09-01,NaT,1995-06-01,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,L1F,N1F,N1F,<NA>,N1F,F1F,F1F,F1F,F1F,F1F,F1F,<NA>,P1F,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,6,1997-02-01,15,3,7,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,1995-06-01,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.00,1,1,20.00,1995-06-01,20.0,1995-06-01,20.0,1995-06-01,1995-06-01,NaT,NaN,20.000000,0,0,1,F,33.0,B,No Title,Not applicable,Not applicable,Not applicable,City,Average SES

In [7]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,PLATES,category,143127.0,99.33,1.0,Yes
1,HOMEE,category,142525.0,98.91,1.0,Yes
2,CARDS,category,142376.0,98.81,1.0,Yes
3,CHILD03,category,142045.0,98.58,3.0,"Male, Female, Both"
4,PVASTATE,category,142028.0,98.57,1.0,P
5,KIDSTUFF,category,141519.0,98.21,1.0,Yes
6,CHILD07,category,141179.0,97.98,3.0,"Male, Female, Both"
7,CHILD12,category,140711.0,97.65,3.0,"Male, Female, Both"
8,BOATS,category,140572.0,97.56,1.0,Yes
9,CHILD18,category,138863.0,96.37,3.0,"Male, Female, Both"
10,PHOTO,category,135522.0,94.05,1.0,Yes
11,COLLECT1,category,135032.0,93.71,1.0,Yes
12,FISHER,category,131363.0,91.16,1.0,Yes
13,CATLG,category,130031.0,90.24,1.0,Yes
14,CRAFTS,category,129614.0,89.95,1.0,Yes
15,BIBLE,category,128646.0,89.28,1.0,Yes
16,VETERANS,category,125434.0,87.05,1.0,Yes
17,PCOWNERS,category,125427.0,87.04,1.0,Yes
18,WALKER,category,125250.0,86.92,1.0,Yes
19,CDPLAY,category,122224.0,84.82,1.0,Yes
20,STEREO,category,121268.0,84.16,1.0,Yes
21,GARDENIN,category,119897.0,83.21,1.0,Yes
22,PETS,category,118539.0,82.26,1.0,Yes
23,PEPSTRFL,category,73709.0,51.15,1.0,Has PEP Star RFA Status
24,LIFESRC,category,72459.0,50.29,3.0,"MATCHED ON POLK ONLY, MATCHED BOTH MM AND POLK, MATCHED ON METRO MAIL ONLY"
25,HOMEOWNR,category,18107.0,12.57,2.0,"Homeowner, Unknown"
26,DATASRCE,category,16464.0,11.43,3.0,"Both, Polk, MetroMail"
27,CLUSTER,category,2986.0,2.07,53.0,"40, 24, 35, 27, 36, 12, 18, 49, 13, 30"
28,DOMAIN_urbanicity,category,2986.0,2.07,5.0,"Suburban, City, Town, Rural, Urban"
29,DOMAIN_ses,category,2986.0,2.07,4.0,"Average SES, Highest SES, Lowest SES, Lower Lowest SES in Urban communities"
30,GENDER,category,2337.0,1.62,6.0,"Female, Male, Unknown, Joint Account, unknown gender, A, C"
31,GEOCODE2,category,261.0,0.18,4.0,"A, B, C, D"
32,CLUSTER2,category,139.0,0.10,62.0,"13.0, 5.0, 15.0, 59.0, 57.0, 2.0, 11.0, 38.0, 32.0, 12.0"
33,MAILCODE,category,0.0,0.00,2.0,"Address is OK, Bad Address"
34,NOEXCH,category,0.0,0.00,4.0,"0-nan-case, 1-nan-case, cannot be exchanged, can be exchanged"
35,RECINHSE,category,0.0,0.00,2.0,"Not an In House Record, Donor has given to PVA's In House program"
36,RECP3,category,0.0,0.00,2.0,"Not a P3 Record, Donor has given to PVA's P3 program"
37,RECPGVG,category,0.0,0.00,2.0,"Not a Planned Giving Record, Planned Giving Record"
38,RECSWEEP,category,0.0,0.00,2.0,"Not a Sweepstakes Record, Sweepstakes Record"
39,AGEFLAG,category,0.0,0.00,3.0,"Exact, Inferred from Date of Birth Field,"
40,SOLP3,category,0.0,0.00,5.0,"can be mailed (Default), Do Not Solicit or Mail, twelve solicitations per year, one solicitation per year, two solicitations per year"
41,SOLIH,category,0.0,0.00,9.0,"can be mailed (Default), twelve solicitations per year, Do Not Solicit, one solicitation per year, two solicitations per year, three solicitations per year, four solicitations per year, six solicitations per year, five solicitations per year"
42,MAJOR,category,0.0,0.00,2.0,"Not a Major Donor, Major Donor"
43,GEOCODE,category,0.0,0.00,8.0,"No code has been assigned or did not match at any level, 12, 03, 05, 14, 04, 02, 01"
44,TARGET_B,category,0.0,0.00,2.0,"0, 1"
45,HPHONE_D,category,0.0,0.00,2.0,"1, 0"
46,RFA_2F,category,0.0,0.00,4.0,"1, 2, 3, 4"
47,RFA_2A,category,0.0,0.00,4.0,"F, E, G, D"
48,MDMAUD_recency,category,0.0,0.00,5.0,"Not applicable, Current Donor, Lapsed Donor, Dormant Donor, Inactive Donor"
49,MDMAUD_frequency,category,0.0,0.00,4.0,"Not applicable, One gift in the period of recency, Two-Four gifts in the period of recency, Five+ gifts in the period of recency"
50,MDMAUD_amount,category,0.0,0.00,5.0,"Not applicable, $100-499 (Core), Less than $100 (Low Dollar), $500-999 (Major), $1,000+ (Top)"
51,RDATE_5,datetime64[ns],144078.0,99.99,6.0,"1996-04-01 00:00:00, 1998-03-01 00:00:00, 1996-05-01 00:00:00, 1997-03-01 00:00:00, 1998-05-01 00:00:00, 1996-06-01 00:00:00"
52,RDATE_3,datetime64[ns],143770.0,99.77,17.0,"1996-06-01 00:00:00, 1996-07-01 00:00:00, 1997-04-01 00:00:00, 1996-05-01 00:00:00, 1996-08-01 00:00:00, 1996-09-01 00:00:00, 1997-03-01 00:00:00, 1998-02-01 00:00:00, 1996-10-01 00:00:00, 1997-05-01 00:00:00"
53,RDATE_4,datetime64[ns],143659.0,99.70,24.0,"1996-05-01 00:00:00, 1996-04-01 00:00:00, 1996-01-01 00:00:00, 1996-06-01 00:00:00, 1997-04-01 00:00:00, 1996-09-01 00:00:00, 1996-03-01 00:00:00, 1996-02-01 00:00:00, 1996-08-01 00:00:00, 1996-07-01 00:00:00"
54,RDATE_6,datetime64[ns],143042.0,99.27,19.0,"1996-03-01 00:00:00, 1996-04-01 00:00:00, 1996-02-01 00:00:00, 1995-12-01 00:00:00, 1996-05-01 00:00:00, 1995-11-01 00:00:00, 1997-03-01 00:00:00, 1996-07-01 00:00:00, 1996-06-01 00:00:00, 1995-10-01 00:00:00"
55,RDATE_15,datetime64[ns],133136.0,92.39,16.0,"1995-05-01 00:00:00, 1995-06-01 00:00:00, 1995-07-01 00:00:00, 1995-08-01 00:00:00, 1995-09-01 00:00:00, 1995-10-01 00:00:00, 1995-12-01 00:00:00, 1995-11-01 00:00:00, 1996-01-01 00:00:00, 1995-04-01 00:00:00"
56,RDATE_23,datetime64[ns],131794.0,91.46,17.0,"1994-08-01 00:00:00, 1994-07-01 00:00:00, 1994-09-01 00:00:00, 1994-10-01 00:00:00, 1994-11-01 00:00:00, 1994-12-01 00:00:00, 1995-02-01 00:00:00, 1995-03-01 00:00:00, 1995-04-01 00:00:00, 1995-01-01 00:00:00"
57,RDATE_20,datetime64[ns],131617.0,91.34,10.0,"1994-12-01 00:00:00, 1994-11-01 00:00:00, 1995-01-01 00:00:00, 1995-02-01 00:00:00, 1995-03-01 00:00:00, 1995-04-01 00:00:00, 1995-05-01 00:00:00, 1995-06-01 00:00:00, 1995-07-01 00:00:00, 1995-08-01 00:00:00"
58,RDATE_7,datetime64[ns],130791.0,90.77,9.0,"1996-03-01 00:00:00, 1996-02-01 00:00:00, 1996-01-01 00:00:00, 1996-04-01 00:00:00, 1996-05-01 00:00:00, 1996-10-01 00:00:00, 1996-08-01 00:00:00, 1997-01-01 00:00:00, 1995-12-01 00:00:00"
59,RDATE_17,datetime64[ns],130159.0,90.33,11.0,"1995-03-01 00:00:00, 1995-02-01 00:00:00, 1995-04-01 00:00:00, 1995-05-01 00:00:00, 1995-06-01 00:00:00, 1995-07-01 00:00:00, 1995-08-01 00:00:00, 1995-09-01 00:00:00, 1995-12-01 00:00:00, 1995-10-01 00:00:00"
60,RDATE_21,datetime64[ns],129368.0,89.78,12.0,"1994-11-01 00:00:00, 1994-10-01 00:00:00, 1994-12-01 00:00:00, 1995-01-01 00:00:00, 1995-02-01 00:00:00, 1995-03-01 00:00:00, 1995-04-01 00:00:00, 1995-06-01 00:00:00, 1995-05-01 00:00:00, 1995-07-01 00:00:00"
61,RDATE_10,datetime64[ns],128107.0,88.90,9.0,"1995-11-01 00:00:00, 1995-12-01 00:00:00, 1996-01-01 00:00:00, 1996-02-01 00:00:00, 1996-03-01 00:00:00, 1998-05-01 00:00:00, 1998-06-01 00:00:00, 1995-10-01 00:00:00, 1998-04-01 00:00:00"
62,RDATE_13,datetime64[ns],125558.0,87.14,15.0,"1995-08-01 00:00:00, 1995-07-01 00:00:00, 1995-09-01 00:00:00, 1995-10-01 00:00:00, 1995-11-01 00:00:00, 1995-12-01 00:00:00, 1996-01-01 00:00:00, 1996-03-01 00:00:00, 1995-02-01 00:00:00, 1995-03-01 00:00:00"
63,RDATE_11,datetime64[ns],121866.0,84.57,10.0,"1995-11-01 00:00:00, 1995-10-01 00:00:00, 1995-12-01 00:00:00, 1996-01-01 00:00:00, 1996-02-01 00:00:00, 1996-03-01 00:00:00, 1995-09-01 00:00:00, 1996-04-01 00:00:00, 1996-05-01 00:00:00, 1998-05-01 00:00:00"
64,RDATE_19,datetime64[ns],119440.0,82.89,13.0,"1994-12-01 00:00:00, 1995-01-01 00:00:00, 1994-10-01 00:00:00, 1995-02-01 00:00:00, 1994-11-01 00:00:00, 1995-03-01 00:00:00, 1995-04-01 00:00:00, 1995-06-01 00:00:00, 1995-05-01 00:00:00, 1995-07-01 00:00:00"
65,RDATE_9,datetime64[ns],118476.0,82.22,10.0,"1995-12-01 00:00:00, 1996-01-01 00:00:00, 1995-10-01 00:00:00, 1996-02-01 00:00:00, 1995-11-01 00:00:00, 1996-03-01 00:00:00, 1995-09-01 00:00:00, 1996-04-01 00:00:00, 1996-07-01 00:00:00, 1996-09-01 00:00:00"
66,RDATE_24,datetime64[ns],116493.0,80.84,14.0,"1994-07-01 00:00:00, 1994-06-01 00:00:00, 1994-08-01 00:00:00, 1994-09-01 00:00:00, 1994-10-01 00:00:00, 1994-12-01 00:00:00, 1994-11-01 00:00:00, 1995-02-01 00:00:00, 1995-01-01 00:00:00, 1995-04-01 00:00:00"
67,RDATE_18,datetime64[ns],115372.0,80.07,14.0,"1995-01-01 00:00:00, 1995-02-01 00:00:00, 1995-03-01 00:00:00, 1995-04-01 00:00:00, 1995-07-01 00:00:00, 1995-06-01 00:00:00, 1995-05-01 00:00:00, 1995-08-01 00:00:00, 1995-09-01 00:00:00, 1995-12-01 00:00:00"
68,RDATE_22,datetime64[ns],112451.0,78.04,13.0,"1994-09-01 00:00:00, 1994-10-01 00:00:00, 1994-12-01 00:00:00, 1994-11-01 00:00:00, 1995-01-01 00:00:00, 1995-02-01 00:00:00, 1995-04-01 00:00:00, 1995-03-01 00:00:00, 1995-06-01 00:00:00, 1995-05-01 00:00:00"
69,RDATE_8,datetime64[ns],112268.0,77.91,18.0,"1996-01-01 00:00:00, 1996-02-01 00:00:00, 1996-03-01 00:00:00, 1995-12-01 00:00:00, 1996-04-01 00:00:00, 1996-05-01 00:00:00, 1996-06-01 00:00:00, 1998-06-01 00:00:00, 1998-03-01 00:00:00, 1996-07-01 00:00:00"
70,RDATE_14,datetime64[ns],109246.0,75.82,12.0,"1995-06-01 00:00:00, 1995-07-01 00:00:00, 1995-08-01 00:00:00, 1995-09-01 00:00:00, 1995-10-01 00:00:00, 1995-12-01 00:00:00, 1995-11-01 00:00:00, 1996-01-01 00:00:00, 1996-02-01 00:00:00, 1996-03-01 00:00:00"
71,RDATE_12,datetime64[ns],106260.0,73.74,11.0,"1995-09-01 00:00:00, 1995-10-01 00:00:00, 1995-12-01 00:00:00, 1995-11-01 00:00:00, 1996-01-01 00:00:00, 1996-02-01 00:00:00, 1996-03-01 00:00:00, 1996-05-01 00:00:00, 1998-06-01 00:00:00, 1996-04-01 00:00:00"
72,RDATE_16,datetime64[ns],102715.0,71.28,17.0,"1995-04-01 00:00:00, 1995-05-01 00:00:00, 1995-06-01 00:00:00, 1995-03-01 00:00:00, 1995-07-01 00:00:00, 1995-08-01 00:00:00, 1995-09-01 00:00:00, 1995-12-01 00:00:00, 1995-10-01 00:00:00, 1996-01-01 00:00:00"
73,ADATE_15,datetime64[ns],97416.0,67.61,1.0,1995-04-01 00:00:00
74,ADATE_23,datetime64[ns],81245.0,56.38,3.0,"1994-07-01 00:00:00, 1994-06-01 00:00:00, 1993-12-01 00:00:00"
75,ADATE_20,datetime64[ns],72258.0,50.15,2.0,"1994-11-01 00:00:00, 1994-12-01 00:00:00"
76,ADATE_13,datetime64[ns],58488.0,40.59,3.0,"1995-07-01 00:00:00, 1995-02-01 00:00:00, 1995-06-01 00:00:00"
77,ADATE_24,datetime64[ns],51446.0,35.70,2.0,"1994-06-01 00:00:00, 1994-05-01 00:00:00"
78,ADATE_21,datetime64[ns],48782.0,33.85,2.0,"1994-10-01 00:00:00, 1994-09-01 00:00:00"
79,ADATE_5,datetime64[ns],48286.0,33.51,1.0,1996-04-01 00:00:00
80,ADATE_10,datetime64[ns],47015.0,32.63,2.0,"1995-10-01 00:00:00, 1995-11-01 00:00:00"
81,ADATE_17,datetime64[ns],38072.0,26.42,3.0,"1995-02-01 00:00:00, 1995-01-01 00:00:00, 1995-03-01 00:00:00"
82,ADATE_22,datetime64[ns],35016.0,24.30,5.0,"1994-09-01 00:00:00, 1994-08-01 00:00:00, 1995-06-01 00:00:00, 1994-11-01 00:00:00, 1994-10-01 00:00:00"
83,ADATE_19,datetime64[ns],32966.0,22.88,3.0,"1994-11-01 00:00:00, 1994-09-01 00:00:00, 1994-10-01 00:00:00"
84,ADATE_18,datetime64[ns],29751.0,20.65,9.0,"1995-01-01 00:00:00, 1994-12-01 00:00:00, 1994-11-01 00:00:00, 1994-09-01 00:00:00, 1995-05-01 00:00:00, 1995-08-01 00:00:00, 1995-04-01 00:00:00, 1995-02-01 00:00:00, 1995-03-01 00:00:00"
85,ADATE_16,datetime64[ns],27280.0,18.93,3.0,"1995-03-01 00:00:00, 1995-04-01 00:00:00, 1995-02-01 00:00:00"
86,ADATE_14,datetime64[ns],25486.0,17.69,2.0,"1995-06-01 00:00:00, 1995-04-01 00:00:00"
87,ADATE_9,datetime64[ns],15188.0,10.54,3.0,"1995-11-01 00:00:00, 1995-09-01 00:00:00, 1995-10-01 00:00:00"
88,NEXTDATE,datetime64[ns],13094.0,9.09,200.0,"1995-04-01 00:00:00, 1987-03-01 00:00:00, 1994-12-01 00:00:00, 1986-12-01 00:00:00, 1995-12-01 00:00:00, 1992-05-01 00:00:00, 1994-04-01 00:00:00, 1995-06-01 00:00:00, 1993-12-01 00:00:00, 1989-02-01 00:00:00"
89,ADATE_11,datetime64[ns],12971.0,9.00,4.0,"1995-10-01 00:00:00, 1995-09-01 00:00:00, 1995-11-01 00:00:00, 1995-08-01 00:00:00"
90,ADATE_7,datetime64[ns],12231.0,8.49,3.0,"1996-02-01 00:00:00, 1996-01-01 00:00:00, 1995-12-01 00:00:00"
91,ADATE_12,datetime64[ns],12089.0,8.39,4.0,"1995-08-01 00:00:00, 1995-09-01 00:00:00, 1995-10-01 00:00:00, 1995-07-01 00:00:00"
92,ADATE_8,datetime64[ns],5252.0,3.64,5.0,"1996-01-01 00:00:00, 1995-12-01 00:00:00, 1995-11-01 00:00:00, 1996-03-01 00:00:00, 1996-05-01 00:00:00"
93,ADATE_6,datetime64[ns],5204.0,3.61,2.0,"1996-03-01 00:00:00, 1996-01-01 00:00:00"
94,ADATE_4,datetime64[ns],2010.0,1.39,8.0,"1996-04-01 00:00:00, 1996-07-01 00:00:00, 1996-05-01 00:00:00, 1996-09-01 00:00:00, 1996-03-01 00:00:00, 1996-02-01 00:00:00, 1995-12-01 00:00:00, 1995-11-01 00:00:00"
95,ADATE_3,datetime64[ns],1671.0,1.16,2.0,"1996-06-01 00:00:00, 1996-04-01 00:00:00"
96,ODATEDW,datetime64[ns],0.0,0.00,49.0,"1986-01-01 00:00:00, 1995-01-01 00:00:00, 1994-01-01 00:00:00, 1991-01-01 00:00:00, 1996-01-01 00:00:00, 1990-01-01 00:00:00, 1992-01-01 00:00:00, 1988-01-01 00:00:00, 1989-01-01 00:00:00, 1993-01-01 00:00:00"
97,DOB,datetime64[ns],0.0,0.00,991.0,"1948-01-01 00:00:00, 1950-01-01 00:00:00, 1930-01-01 00:00:00, 1928-01-01 00:00:00, 1944-01-01 00:00:00, 1924-01-01 00:00:00, 1926-01-01 00:00:00, 1946-01-01 00:00:00, 1952-01-01 00:00:00, 1922-01-01 00:00:00"
98,ADATE_2,datetime64[ns],0.0,0.00,2.0,"1997-06-01 00:00:00, 1997-04-01 00:00:00"
99,MAXADATE,datetime64[ns],0.0,0.00,5.0,"1997-02-01 00:00:00, 1996-12-01 00:00:00, 1996-11-01 00:00:00, 1997-01-01 00:00:00, 1996-07-01 00:00:00"
100,MINRDATE,datetime64[ns],0.0,0.00,155.0,"1996-01-01 00:00:00, 1996-02-01 00:00:00, 1995-12-01 00:00:00, 1995-06-01 00:00:00, 1994-01-01 00:00:00, 1995-09-01 00:00:00, 1995-10-01 00:00:00, 1995-01-01 00:00:00, 1993-10-01 00:00:00, 1993-01-01 00:00:00"
101,MAXRDATE,datetime64[ns],0.0,0.00,154.0,"1995-12-01 00:00:00, 1996-01-01 00:00:00, 1995-09-01 00:00:00, 1996-02-01 00:00:00, 1995-04-01 00:00:00, 1995-11-01 00:00:00, 1994-12-01 00:00:00, 1995-10-01 00:00:00, 1995-06-01 00:00:00, 1996-03-01 00:00:00"
102,LASTDATE,datetime64[ns],0.0,0.00,24.0,"1995-12-01 00:00:00, 1996-01-01 00:00:00, 1996-02-01 00:00:00, 1996-03-01 00:00:00, 1995-11-01 00:00:00, 1995-09-01 00:00:00, 1995-10-01 00:00:00, 1995-04-01 00:00:00, 1995-06-01 00:00:00, 1995-07-01 00:00:00"
103,FISTDATE,datetime64[ns],2.0,0.00,194.0,"1995-01-01 00:00:00, 1994-01-01 00:00:00, 1993-10-01 00:00:00, 1986-08-01 00:00:00, 1994-10-01 00:00:00, 1986-12-01 00:00:00, 1988-09-01 00:00:00, 1993-01-01 00:00:00, 1996-01-01 00:00:00, 1988-01-01 00:00:00"
104,RAMNT_5,float64,144078.0,99.99,10.0,"5.0, 10.0, 13.0, 20.0, 8.0, 25.0, 11.0, 4.0, 15.0, 30.0"
105,RAMNT_3,float64,143770.0,99.77,35.0,"10.0, 5.0, 20.0, 7.0, 15.0, 3.0, 12.0, 25.0, 8.0, 9.0"
106,RAMNT_4,float64,143659.0,99.70,36.0,"10.0, 5.0, 15.0, 20.0, 25.0, 7.0, 12.0, 9.0, 50.0, 3.0"
107,RAMNT_6,float64,143042.0,99.27,40.0,"10.0, 5.0, 15.0, 20.0, 25.0, 12.0, 11.0, 7.0, 3.0, 16.0"
108,RAMNT_15,float64,133136.0,92.39,79.0,"10.0, 5.0, 15.0, 20.0, 7.0, 25.0, 6.0, 8.0, 12.0, 9.0"
109,RAMNT_23,float64,131794.0,91.46,84.0,"10.0, 5.0, 15.0, 20.0, 6.0, 7.0, 11.0, 25.0, 3.0, 12.0"
110,RAMNT_20,float64,131617.0,91.34,78.0,"10.0, 15.0, 20.0, 5.0, 12.0, 25.0, 7.0, 11.0, 14.0, 9.0"
111,RAMNT_7,float64,130791.0,90.77,89.0,"10.0, 15.0, 20.0, 5.0, 25.0, 11.0, 7.0, 12.0, 16.0, 6.0"
112,RAMNT_17,float64,130159.0,90.33,78.0,"10.0, 5.0, 15.0, 20.0, 25.0, 7.0, 11.0, 12.0, 3.0, 6.0"
113,RAMNT_21,float64,129368.0,89.78,89.0,"10.0, 5.0, 15.0, 20.0, 25.0, 11.0, 7.0, 12.0, 3.0, 6.0"
114,RAMNT_10,float64,128107.0,88.90,96.0,"10.0, 15.0, 20.0, 5.0, 25.0, 12.0, 7.0, 17.0, 11.0, 16.0"
115,RAMNT_13,float64,125558.0,87.14,87.0,"10.0, 5.0, 15.0, 20.0, 25.0, 6.0, 7.0, 11.0, 8.0, 16.0"
116,RAMNT_11,float64,121866.0,84.57,97.0,"10.0, 15.0, 20.0, 5.0, 25.0, 7.0, 11.0, 16.0, 6.0, 12.0"
117,NUMCHLD,float64,121367.0,84.23,7.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0"
118,RAMNT_19,float64,119440.0,82.89,94.0,"10.0, 5.0, 15.0, 20.0, 12.0, 7.0, 25.0, 9.0, 11.0, 14.0"
119,RAMNT_9,float64,118476.0,82.22,106.0,"10.0, 15.0, 20.0, 5.0, 25.0, 12.0, 7.0, 17.0, 16.0, 11.0"
120,RAMNT_24,float64,116493.0,80.84,95.0,"10.0, 5.0, 15.0, 20.0, 7.0, 11.0, 3.0, 25.0, 6.0, 12.0"
121,RAMNT_18,float64,115372.0,80.07,108.0,"10.0, 5.0, 15.0, 20.0, 7.0, 12.0, 25.0, 3.0, 11.0, 8.0"
122,RAMNT_22,float64,112451.0,78.04,108.0,"10.0, 5.0, 15.0, 20.0, 12.0, 7.0, 25.0, 11.0, 3.0, 8.0"
123,RAMNT_8,float64,112268.0,77.91,118.0,"15.0, 10.0, 20.0, 25.0, 5.0, 12.0, 7.0, 11.0, 8.0, 17.0"
124,RAMNT_14,float64,109246.0,75.82,113.0,"10.0, 5.0, 15.0, 20.0, 25.0, 7.0, 11.0, 6.0, 12.0, 16.0"
125,RAMNT_12,float64,106260.0,73.74,129.0,"10.0, 15.0, 20.0, 5.0, 25.0, 12.0, 7.0, 11.0, 8.0, 6.0"
126,RAMNT_16,float64,102715.0,71.28,116.0,"10.0, 15.0, 5.0, 20.0, 12.0, 25.0, 7.0, 11.0, 8.0, 6.0"
127,MBCOLECT,float64,67276.0,46.69,7.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0"
128,MBCRAFT,float64,67177.0,46.62,7.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0"
129,MBGARDEN,float64,67177.0,46.62,5.0,"0.0, 1.0, 2.0, 3.0, 4.0"
130,MBBOOKS,float64,67177.0,46.62,10.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 9.0, 8.0"
131,MAGFAML,float64,67177.0,46.62,10.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 9.0, 8.0"
132,MAGFEM,float64,67177.0,46.62,6.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0"
133,MAGMALE,float64,67177.0,46.62,5.0,"0.0, 1.0, 2.0, 3.0, 4.0"
134,PUBGARDN,float64,67177.0,46.62,7.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0"
135,PUBCULIN,float64,67177.0,46.62,7.0,"0.0, 1.0, 2.0, 3.0, 4.0, 6.0, 5.0"
136,PUBHLTH,float64,67177.0,46.62,10.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
137,PUBDOITY,float64,67177.0,46.62,10.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
138,PUBNEWFN,float64,67177.0,46.62,10.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 9.0, 8.0"
139,PUBPHOTO,float64,67177.0,46.62,3.0,"0.0, 1.0, 2.0"
140,PUBOPP,float64,67177.0,46.62,10.0,"0.0, 1.0, 2.0, 3.0, 4.0, 9.0, 5.0, 6.0, 7.0, 8.0"
141,WEALTH2,float64,59375.0,41.21,10.0,"9.0, 8.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 1.0, 0.0"
142,WEALTH1,float64,55521.0,38.53,10.0,"9.0, 8.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 1.0, 0.0"
143,INCOME,float64,16477.0,11.43,7.0,"5.0, 4.0, 2.0, 3.0, 1.0, 6.0, 7.0"
144,TIMELAG,float64,13094.0,9.09,70.0,"4.0, 5.0, 3.0, 6.0, 2.0, 7.0, 8.0, 9.0, 10.0, 11.0"
145,MSA,float64,139.0,0.10,299.0,"0.0, 4480.0, 1600.0, 2160.0, 520.0, 7040.0, 3360.0, 8280.0, 7600.0, 6200.0"
146,ADI,float64,139.0,0.10,205.0,"13.0, 51.0, 65.0, 57.0, 105.0, 109.0, 131.0, 201.0, 197.0, 107.0"
147,DMA,float64,139.0,0.10,207.0,"803.0, 602.0, 807.0, 505.0, 819.0, 539.0, 623.0, 618.0, 524.0, 862.0"
148,AGE,float64,4.0,0.00,98.0,"50.0, 76.0, 74.0, 68.0, 72.0, 70.0, 48.0, 78.0, 54.0, 66.0"
149,RAMNTALL,float64,0.0,0.00,2647.0,"20.0, 25.0, 15.0, 30.0, 40.0, 50.0, 35.0, 45.0, 55.0, 60.0"
150,MINRAMNT,float64,0.0,0.00,240.0,"5.0, 3.0, 10.0, 15.0, 2.0, 20.0, 25.0, 1.0, 4.0, 6.0"
151,MAXRAMNT,float64,0.0,0.00,347.0,"15.0, 20.0, 25.0, 10.0, 16.0, 12.0, 30.0, 11.0, 17.0, 50.0"
152,LASTGIFT,float64,0.0,0.00,277.0,"15.0, 20.0, 10.0, 25.0, 5.0, 12.0, 16.0, 17.0, 30.0, 11.0"
153,AVGGIFT,float64,0.0,0.00,9597.0,"15.0, 20.0, 25.0, 10.0, 12.5, 13.0, 9.0, 11.0, 12.0, 14.0"
154,HIT,int64,0.0,0.00,83.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
155,MALEMILI,int64,0.0,0.00,97.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
156,MALEVET,int64,0.0,0.00,89.0,"31, 30, 32, 29, 33, 28, 34, 35, 27, 26"
157,VIETVETS,int64,0.0,0.00,96.0,"0, 27, 28, 29, 32, 30, 31, 26, 33, 25"
158,WWIIVETS,int64,0.0,0.00,100.0,"0, 33, 32, 29, 35, 30, 28, 31, 38, 36"
159,LOCALGOV,int64,0.0,0.00,54.0,"5, 6, 7, 4, 8, 9, 3, 0, 10, 2"
160,STATEGOV,int64,0.0,0.00,65.0,"2, 0, 3, 1, 4, 5, 6, 7, 8, 9"
161,FEDGOV,int64,0.0,0.00,56.0,"0, 2, 1, 3, 4, 5, 6, 7, 8, 9"
162,POP901,int64,0.0,0.00,10419.0,"0, 834, 1112, 931, 1086, 1205, 1173, 932, 1092, 1083"
163,POP902,int64,0.0,0.00,5077.0,"0, 281, 268, 255, 261, 237, 278, 228, 296, 265"
164,POP903,int64,0.0,0.00,6049.0,"0, 340, 380, 426, 423, 418, 448, 429, 330, 356"
165,POP90C1,int64,0.0,0.00,100.0,"99, 0, 98, 97, 96, 95, 94, 1, 91, 93"
166,POP90C2,int64,0.0,0.00,100.0,"0, 99, 1, 98, 97, 2, 96, 95, 94, 3"
167,POP90C3,int64,0.0,0.00,100.0,"0, 99, 1, 2, 3, 4, 5, 6, 9, 7"
168,POP90C4,int64,0.0,0.00,83.0,"49, 50, 48, 51, 47, 46, 52, 45, 44, 53"
169,POP90C5,int64,0.0,0.00,83.0,"51, 50, 52, 49, 53, 54, 48, 55, 56, 47"
170,ETH1,int64,0.0,0.00,100.0,"99, 98, 97, 96, 95, 94, 93, 92, 91, 90"
171,ETH2,int64,0.0,0.00,100.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
172,ETH3,int64,0.0,0.00,89.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"
173,ETH4,int64,0.0,0.00,96.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
174,ETH5,int64,0.0,0.00,100.0,"1, 0, 2, 3, 4, 5, 6, 7, 8, 9"
175,ETH6,int64,0.0,0.00,21.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
176,ETH7,int64,0.0,0.00,62.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"
177,ETH8,int64,0.0,0.00,61.0,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"

In [8]:
# Numeric Feature Statistics
numeric_stats

             count          mean          std        min       max
AGE       144091.0     61.628853    16.665193   1.000000      98.0
NUMCHLD    22728.0      1.533879     0.811377   1.000000       7.0
INCOME    127618.0      3.960241     1.843408   1.000000       7.0
WEALTH1    88574.0      5.417143     2.734297   0.000000       9.0
HIT       144095.0      4.070211     9.790032   0.000000     242.0
MBCRAFT    76918.0      0.156348     0.478916   0.000000       6.0
MBGARDEN   76918.0      0.060467     0.264614   0.000000       4.0
MBBOOKS    76918.0      1.155022     1.702199   0.000000       9.0
MBCOLECT   76819.0      0.065635     0.300941   0.000000       6.0
MAGFAML    76918.0      0.461218     0.829841   0.000000       9.0
MAGFEM     76918.0      0.127811     0.382824   0.000000       5.0
MAGMALE    76918.0      0.068255     0.281375   0.000000       4.0
PUBGARDN   76918.0      0.144934     0.495888   0.000000       6.0
PUBCULIN   76918.0      0.151655     0.438562   0.000000       6.0
PUBHLTH    76918.0      0.739541     1.279437   0.000000       9.0
PUBDOITY   76918.0      0.243220     0.740493   0.000000       9.0
PUBNEWFN   76918.0      0.390234     0.970412   0.000000       9.0
PUBPHOTO   76918.0      0.006162     0.080066   0.000000       2.0
PUBOPP     76918.0      0.248914     0.902146   0.000000       9.0
MALEMILI  144095.0      0.967535     4.373705   0.000000      99.0
MALEVET   144095.0     31.045817    11.177744   0.000000      99.0
VIETVETS  144095.0     30.051126    15.084372   0.000000      99.0
WWIIVETS  144095.0     33.050689    17.647931   0.000000      99.0
LOCALGOV  144095.0      6.933946     4.346791   0.000000      76.0
STATEGOV  144095.0      4.574142     5.136715   0.000000      99.0
FEDGOV    144095.0      3.103564     4.058916   0.000000      99.0
WEALTH2    84720.0      5.069511     2.796450   0.000000       9.0
POP901    144095.0   3051.010049  5365.603326   0.000000  100286.0
POP902    144095.0    816.051702  1378.071462   0.000000   23766.0
POP903    144095.0   1148.431694  2000.227704   0.000000   35403.0
POP90C1   144095.0     60.531788    47.040701   0.000000      99.0
POP90C2   144095.0     13.521344    31.302989   0.000000      99.0
POP90C3   144095.0     24.570429    39.248943   0.000000      99.0
POP90C4   144095.0     48.268684     4.892538   0.000000      99.0
POP90C5   144095.0     51.153135     5.060322   0.000000      99.0
ETH1      144095.0     85.233339    20.818861   0.000000      99.0
ETH2      144095.0      7.606052    17.271681   0.000000      99.0
ETH3      144095.0      0.691190     3.029079   0.000000      99.0
ETH4      144095.0      2.826448     6.863058   0.000000      95.0
ETH5      144095.0      7.296464    13.505324   0.000000      99.0
ETH6      144095.0      0.217627     0.680446   0.000000      22.0
ETH7      144095.0      0.381471     2.165360   0.000000      72.0
ETH8      144095.0      0.595211     2.434287   0.000000      87.0
ETH9      144095.0      0.544641     2.293139   0.000000      67.0
ETH10     144095.0      0.238322     0.951146   0.000000      46.0
ETH11     144095.0      0.206933     1.034371   0.000000      47.0
ETH12     144095.0      0.059384     1.015060   0.000000      79.0
ETH13     144095.0      5.025768    11.164831   0.000000      96.0
ETH14     144095.0      0.306312     1.280809   0.000000      57.0
ETH15     144095.0      0.334946     3.260269   0.000000      81.0
ETH16     144095.0      1.452611     3.093013   0.000000      86.0
AGE901    144095.0     34.676318     8.203121   0.000000      84.0
AGE902    144095.0     42.119428     7.971707   0.000000      84.0
AGE903    144095.0     45.288164     7.786199   0.000000      84.0
AGE904    144095.0     36.056976     7.065944   0.000000      81.0
AGE905    144095.0     44.865929     6.568017   0.000000      81.0
AGE906    144095.0     48.041854     6.434050   0.000000      81.0
AGE907    144095.0     24.598668     7.373378   0.000000      71.0
CHIL1     144095.0     39.632048     7.882072   0.000000      99.0
CHIL2     144095.0     38.520532     5.994446   0.000000      99.0
CHIL3     144095.0     21.096589     5.656122   0.000000      99.0
AGEC1     144095.0     12.091953     5.803351   0.000000      99.0
AGEC2     144095.0     22.131892     7.660371   0.000000      99.0
AGEC3     144095.0     20.797925     6.180572   0.000000      99.0
AGEC4     144095.0     14.175218     4.284465   0.000000      99.0
AGEC5     144095.0     11.970637     4.103927   0.000000      99.0
AGEC6     144095.0     10.626823     6.043582   0.000000      61.0
AGEC7     144095.0      7.631292     6.724703   0.000000      90.0
CHILC1    144095.0     16.163142     4.940264   0.000000      99.0
CHILC2    144095.0     16.184753     3.557868   0.000000      99.0
CHILC3    144095.0     31.768208     5.050385   0.000000      99.0
CHILC4    144095.0     19.845088     4.417240   0.000000      99.0
CHILC5    144095.0     15.283681     5.416115   0.000000      99.0
HHAGE1    144095.0     24.685860    13.144965   0.000000      99.0
HHAGE2    144095.0      9.300406     7.420109   0.000000      99.0
HHAGE3    144095.0     22.367986    13.025686   0.000000      99.0
HHN1      144095.0     22.605628    11.539069   0.000000      99.0
HHN2      144095.0     33.814393     8.063448   0.000000      99.0
HHN3      144095.0     42.997106    14.363940   0.000000      99.0
HHN4      144095.0     25.795177    10.966711   0.000000      99.0
HHN5      144095.0     10.501704     6.287936   0.000000      99.0
HHN6      144095.0      3.873403     3.689891   0.000000      99.0
MARR1     144095.0     58.491447    12.475778   0.000000      99.0
MARR2     144095.0     10.653999     4.430951   0.000000      99.0
MARR3     144095.0      7.406600     4.873396   0.000000      73.0
MARR4     144095.0     22.872029     8.555677   0.000000      99.0
HHP1      144095.0    186.477969    48.941557   0.000000     650.0
HHP2      144095.0    260.899629    47.781693   0.000000     700.0
DW1       144095.0     71.321947    24.463471   0.000000      99.0
DW2       144095.0     67.270828    25.954241   0.000000      99.0
DW3       144095.0      2.922336     5.430239   0.000000      88.0
DW4       144095.0     19.008980    23.255769   0.000000      99.0
DW5       144095.0     16.060911    22.022925   0.000000      99.0
DW6       144095.0     12.663063    19.851217   0.000000      99.0
DW7       144095.0      1.636760     5.452951   0.000000      99.0
DW8       144095.0      1.092432     4.083453   0.000000      99.0
DW9       144095.0      0.537048     3.486195   0.000000      99.0
HV1       144095.0   1061.506721   925.978418   0.000000    6000.0
HV2       144095.0   1132.343412   932.462694   0.000000    6000.0
HV3       144095.0      4.283910     2.290794   0.000000      13.0
HV4       144095.0      3.932315     2.211462   0.000000      13.0
HU1       144095.0     70.715570    20.937432   0.000000      99.0
HU2       144095.0     28.695354    20.332015   0.000000      99.0
HU3       144095.0     90.551289    11.903484   0.000000      99.0
HU4       144095.0      8.856768     9.694336   0.000000      99.0
HU5       144095.0     13.491460    20.831221   0.000000      99.0
HHD1      144095.0     35.818391    12.882745   0.000000      99.0
HHD2      144095.0     72.036892    14.458454   0.000000      99.0
HHD3      144095.0     59.249544    15.861261   0.000000      99.0
HHD4      144095.0     27.949832    11.864758   0.000000      99.0
HHD5      144095.0     82.509504    13.088985   0.000000      99.0
HHD6      144095.0     16.911322    11.546143   0.000000      99.0
HHD7      144095.0      7.869489     5.347620   0.000000      99.0
HHD8      144095.0      1.609549     1.094195   0.000000      50.0
HHD9      144095.0      6.258656     4.747849   0.000000      99.0
HHD10     144095.0     13.412582     6.782022   0.000000      99.0
HHD11     144095.0     18.884451     9.281962   0.000000      99.0
HHD12     144095.0      4.773504     3.939673   0.000000      99.0
ETHC1     144095.0     16.843756     6.823701   0.000000      71.0
ETHC2     144095.0     50.972685    14.470286   0.000000      99.0
ETHC3     144095.0     17.458579    12.421198   0.000000      99.0
ETHC4     144095.0      2.002089     4.681660   0.000000      55.0
ETHC5     144095.0      4.653243    10.425282   0.000000      99.0
ETHC6     144095.0      0.854360     2.997134   0.000000      81.0
HVP1      144095.0     13.395607    26.400955   0.000000      99.0
HVP2      144095.0     20.900121    31.727138   0.000000      99.0
HVP3      144095.0     35.165426    36.569608   0.000000      99.0
HVP4      144095.0     51.595586    36.640205   0.000000      99.0
HVP5      144095.0     74.757167    29.135566   0.000000      99.0
HVP6      144095.0      6.273188    17.766224   0.000000      99.0
HUR1      144095.0      4.532038     6.987633   0.000000      99.0
HUR2      144095.0     46.855880    21.394066   0.000000      99.0
RHP1      144095.0     53.498622    10.352542   0.000000      84.0
RHP2      144095.0     54.356987     9.985362   0.000000      88.0
RHP3      144095.0     14.202665     2.444011   0.000000      61.0
RHP4      144095.0      4.386807     1.112982   0.000000      27.0
HUPA1     144095.0     10.043020    12.688166   0.000000      99.0
HUPA2     144095.0      8.952663    16.552448   0.000000      99.0
HUPA3     144095.0      8.073493    14.217981   0.000000      99.0
HUPA4     144095.0     11.034227     7.596363   0.000000      99.0
HUPA5     144095.0      5.168673     7.451643   0.000000      99.0
HUPA6     144095.0     10.558534    17.132295   0.000000      99.0
HUPA7     144095.0      1.501697     2.876774   0.000000      71.0
RP1       144095.0     29.648579    32.146938   0.000000      99.0
RP2       144095.0     43.259711    34.674482   0.000000      99.0
RP3       144095.0     61.054533    32.189996   0.000000      99.0
RP4       144095.0     77.838835    23.188726   0.000000      99.0
MSA       143956.0   3585.900657  2839.288735   0.000000    9360.0
ADI       143956.0    185.682153   135.732024   0.000000     645.0
DMA       143956.0    661.980008   113.629577   0.000000     881.0
IC1       144095.0    346.658434   163.275148   0.000000    1500.0
IC2       144095.0    393.761699   173.674793   0.000000    1500.0
IC3       144095.0    393.860002   161.188678   0.000000    1500.0
IC4       144095.0    437.396516   171.193942   0.000000    1500.0
IC5       144095.0  15948.690697  8575.703302   0.000000  174523.0
IC6       144095.0     20.986932    14.339785   0.000000      99.0
IC7       144095.0     16.737583     7.928680   0.000000      99.0
IC8       144095.0     15.746931     6.260152   0.000000      99.0
IC9       144095.0     18.573046     7.393313   0.000000      99.0
IC10      144095.0     16.356577     9.710942   0.000000      99.0
IC11      144095.0      5.761616     5.916715   0.000000      99.0
IC12      144095.0      2.291467     3.427448   0.000000      57.0
IC13      144095.0      0.961151     1.949365   0.000000      61.0
IC14      144095.0      1.946605     4.740069   0.000000      99.0
IC15      144095.0     14.381873    12.228545   0.000000      99.0
IC16      144095.0     15.683979     9.111506   0.000000      99.0
IC17      144095.0     16.378299     7.623351   0.000000      99.0
IC18      144095.0     20.836275     8.424107   0.000000      99.0
IC19      144095.0     19.110274    10.631544   0.000000      99.0
IC20      144095.0      6.776585     6.749406   0.000000      99.0
IC21      144095.0      2.683459     3.982030   0.000000      99.0
IC22      144095.0      1.152240     2.344288   0.000000      99.0
IC23      144095.0      2.341657     5.628857   0.000000      99.0
HHAS1     144095.0     26.860918    13.905596   0.000000      99.0
HHAS2     144095.0      5.974017     6.161932   0.000000      99.0
HHAS3     144095.0     43.724675    16.993888   0.000000      99.0
HHAS4     144095.0     10.395156     9.830835   0.000000      99.0
MC1       144095.0     48.137160    15.655723   0.000000      99.0
MC2       144095.0     51.254291    15.717266   0.000000      99.0
MC3       144095.0     12.080433    10.030846   0.000000      99.0
TPE1      144095.0     76.771012    12.431746   0.000000      99.0
TPE2      144095.0     12.868587     6.598536   0.000000      99.0
TPE3      144095.0      2.399285     5.535350   0.000000      99.0
TPE4      144095.0      1.819910     4.512176   0.000000      99.0
TPE5      144095.0      0.467539     2.213179   0.000000      71.0
TPE6      144095.0      0.103820     0.756642   0.000000      47.0
TPE7      144095.0      0.239176     0.706587   0.000000      44.0
TPE8      144095.0      3.875825     5.151591   0.000000      99.0
TPE9      144095.0      3.194386     3.566594   0.000000      99.0
PEC1      144095.0      2.237010     6.159862   0.000000      97.0
PEC2      144095.0     18.325223    19.057577   0.000000      99.0
TPE10     144095.0     19.567938     6.544919   0.000000      90.0
TPE11     144095.0     23.802748     6.489405   0.000000      76.0
TPE12     144095.0      5.269086     5.313838   0.000000      85.0
TPE13     144095.0     60.497810    17.017801   0.000000      99.0
LFC1      144095.0     64.845303    13.186098   0.000000      99.0
LFC2      144095.0     74.195392    14.111093   0.000000      99.0
LFC3      144095.0     56.334647    13.449556   0.000000      99.0
LFC4      144095.0     70.153829    14.506413   0.000000      99.0
LFC5      144095.0     53.283112    13.479395   0.000000      99.0
LFC6      144095.0     64.492883    16.009100   0.000000      99.0
LFC7      144095.0     49.173434    17.127985   0.000000      99.0
LFC8      144095.0     70.432971    30.937745   0.000000      99.0
LFC9      144095.0     61.781124    45.192687   0.000000      99.0
LFC10     144095.0      6.540858     9.261405   0.000000      99.0
OCC1      144095.0     14.355460     8.301221   0.000000      99.0
OCC2      144095.0     12.767737     7.098739   0.000000      99.0
OCC3      144095.0      3.587363     2.566524   0.000000      99.0
OCC4      144095.0     12.547389     5.509263   0.000000      99.0
OCC5      144095.0     15.662702     5.691199   0.000000      99.0
OCC6      144095.0      0.415372     0.992308   0.000000      44.0
OCC7      144095.0      1.659745     1.902583   0.000000      50.0
OCC8      144095.0     10.501461     6.032537   0.000000      99.0
OCC9      144095.0      2.659967     4.771712   0.000000      77.0
OCC10     144095.0     11.334661     5.821899   0.000000      99.0
OCC11     144095.0      6.208217     5.759073   0.000000      99.0
OCC12     144095.0      3.959083     3.201752   0.000000      99.0
OCC13     144095.0      3.704785     2.958378   0.000000      79.0
EIC1      144095.0      2.955141     5.221561   0.000000      99.0
EIC2      144095.0      0.697734     2.387249   0.000000      65.0
EIC3      144095.0      6.379638     4.078527   0.000000      99.0
EIC4      144095.0     16.974614     9.980541   0.000000      99.0
EIC5      144095.0      4.299143     3.217959   0.000000      99.0
EIC6      144095.0      2.734161     2.340388   0.000000      64.0
EIC7      144095.0      4.426906     3.078042   0.000000      99.0
EIC8      144095.0     16.970172     6.085940   0.000000      99.0
EIC9      144095.0      6.977071     4.641720   0.000000      99.0
EIC10     144095.0      4.716409     3.009849   0.000000      78.0
EIC11     144095.0      3.253118     3.173710   0.000000      99.0
EIC12     144095.0      1.546008     2.192862   0.000000      61.0
EIC13     144095.0      8.155335     4.486678   0.000000      99.0
EIC14     144095.0      8.104847     5.348496   0.000000      99.0
EIC15     144095.0      6.572712     4.364150   0.000000      99.0
EIC16     144095.0      4.602922     4.093871   0.000000      99.0
OEDC1     144095.0      7.059579     4.257236   0.000000      99.0
OEDC2     144095.0      4.657108     5.082219   0.000000      99.0
OEDC3     144095.0      3.163267     4.087502   0.000000      99.0
OEDC4     144095.0      7.923314     5.345283   0.000000      99.0
OEDC5     144095.0     69.904646    11.637786   0.000000      99.0
OEDC6     144095.0      6.162178     4.303229   0.000000      99.0
OEDC7     144095.0      0.490281     0.997255   0.000000      99.0
EC1       144095.0    128.626816    16.612935   0.000000     170.0
EC2       144095.0      8.485680     8.073384   0.000000      99.0
EC3       144095.0     12.734377     7.605409   0.000000      99.0
EC4       144095.0     28.770804    10.200266   0.000000      99.0
EC5       144095.0     20.967695     6.961746   0.000000      99.0
EC6       144095.0      6.609910     3.404082   0.000000      68.0
EC7       144095.0     14.332864     9.794576   0.000000      99.0
EC8       144095.0      7.497110     7.104021   0.000000      99.0
SEC1      144095.0      3.818661     3.757502   0.000000      93.0
SEC2      144095.0     22.096422     7.644344   0.000000      99.0
SEC3      144095.0      1.921940     1.374476   0.000000      30.0
SEC4      144095.0     17.176800     6.308600   0.000000      72.0
SEC5      144095.0      6.817079     5.414316   0.000000      99.0
AFC1      144095.0      0.546299     2.732346   0.000000      87.0
AFC2      144095.0      0.984080     4.333654   0.000000      98.0
AFC3      144095.0      0.131587     0.882487   0.000000      60.0
AFC4      144095.0     15.744419     5.211783   0.000000      99.0
AFC5      144095.0     31.662070    10.365485   0.000000      99.0
AFC6      144095.0      1.276096     1.639891   0.000000      50.0
VC1       144095.0     30.745328    14.590494   0.000000      99.0
VC2       144095.0     18.017225     9.719513   0.000000      99.0
VC3       144095.0     33.580589    17.103218   0.000000      99.0
VC4       144095.0     11.124078    10.450341   0.000000      99.0
ANC1      144095.0      0.729456     2.304199   0.000000      83.0
ANC2      144095.0      5.447018     4.270019   0.000000      99.0
ANC3      144095.0      0.881620     1.387408   0.000000      41.0
ANC4      144095.0     10.254332     8.190243   0.000000      99.0
ANC5      144095.0      0.202151     0.743316   0.000000      48.0
ANC6      144095.0      0.184052     0.542884   0.000000      14.0
ANC7      144095.0      4.834415     3.291880   0.000000      49.0
ANC8      144095.0      1.866158     2.551425   0.000000      65.0
ANC9      144095.0      0.780527     2.101592   0.000000      57.0
ANC10     144095.0      1.407981     2.949691   0.000000      99.0
ANC11     144095.0      0.166834     0.883781   0.000000      74.0
ANC12     144095.0      0.407724     1.452098   0.000000      38.0
ANC13     144095.0      0.729498     0.976035   0.000000      50.0
ANC14     144095.0      0.740935     1.294506   0.000000      33.0
ANC15     144095.0      0.081988     0.409688   0.000000      47.0
POBC1     144095.0      6.490003     9.293618   0.000000      99.0
POBC2     144095.0     57.342718    21.576839   0.000000      99.0
LSC1      144095.0     88.228065    15.662638   0.000000      99.0
LSC2      144095.0      5.844838    11.806225   0.000000      99.0
LSC3      144095.0      1.823200     4.772910   0.000000      89.0
LSC4      144095.0      3.465367     4.391558   0.000000      99.0
VOC1      144095.0     92.268913    11.318631   0.000000      99.0
VOC2      144095.0     60.908546    18.498007   0.000000      99.0
VOC3      144095.0     20.119081    10.835393   0.000000      99.0
HC1       144095.0      7.005823     4.065608   0.000000      31.0
HC2       144095.0     24.083820    12.538358   0.000000      52.0
HC3       144095.0      2.540921     5.925917   0.000000      99.0
HC4       144095.0     12.285006    17.009865   0.000000      99.0
HC5       144095.0     22.426628    24.046542   0.000000      99.0
HC6       144095.0     45.696575    32.388068   0.000000      99.0
HC7       144095.0     62.385593    31.964772   0.000000      99.0
HC8       144095.0     36.572025    31.639627   0.000000      99.0
HC9       144095.0      2.790229     7.812482   0.000000      90.0

In [9]:
# Categorical Feature Statistics
cat_stats

                                                                          value  \
column            rank
ADATE_10          1                                         1995-10-01 00:00:00
                  2                                                        <NA>
                  3                                         1995-11-01 00:00:00
ADATE_11          1                                         1995-10-01 00:00:00
                  2                                         1995-09-01 00:00:00
                  3                                                        <NA>
                  4                                         1995-11-01 00:00:00
                  5                                         1995-08-01 00:00:00
ADATE_12          1                                         1995-08-01 00:00:00
                  2                                         1995-09-01 00:00:00
                  3                                                        <NA>
                  4                                         1995-10-01 00:00:00
                  5                                         1995-07-01 00:00:00
ADATE_13          1                                         1995-07-01 00:00:00
                  2                                                        <NA>
                  3                                         1995-02-01 00:00:00
                  4                                         1995-06-01 00:00:00
ADATE_14          1                                         1995-06-01 00:00:00
                  2                                                        <NA>
                  3                                         1995-04-01 00:00:00
ADATE_15          1                                                        <NA>
                  2                                         1995-04-01 00:00:00
ADATE_16          1                                         1995-03-01 00:00:00
                  2                                                        <NA>
                  3                                         1995-04-01 00:00:00
                  4                                         1995-02-01 00:00:00
ADATE_17          1                                         1995-02-01 00:00:00
                  2                                                        <NA>
                  3                                         1995-01-01 00:00:00
                  4                                         1995-03-01 00:00:00
ADATE_18          1                                         1995-01-01 00:00:00
                  2                                         1994-12-01 00:00:00
                  3                                                        <NA>
                  4                                         1994-11-01 00:00:00
                  5                                         1994-09-01 00:00:00
ADATE_19          1                                         1994-11-01 00:00:00
                  2                                                        <NA>
                  3                                         1994-09-01 00:00:00
                  4                                         1994-10-01 00:00:00
ADATE_2           1                                         1997-06-01 00:00:00
                  2                                         1997-04-01 00:00:00
ADATE_20          1                                                        <NA>
                  2                                         1994-11-01 00:00:00
                  3                                         1994-12-01 00:00:00
ADATE_21          1                                         1994-10-01 00:00:00
                  2                                                        <NA>
                  3                                         1994-09-01 00:00:00
ADATE_22          1                                         1994-09-01 00:00:00
                  2                                                        <NA>
                  3                                         1994-08-01 00:00:00
                  4                                         1995-06-01 00:00:00
                  5                                         1994-11-01 00:00:00
ADATE_23          1                                                        <NA>
                  2                                         1994-07-01 00:00:00
                  3                                         1994-06-01 00:00:00
                  4                                         1993-12-01 00:00:00
ADATE_24          1                                         1994-06-01 00:00:00
                  2                                                        <NA>
                  3                                         1994-05-01 00:00:00
ADATE_3           1                                         1996-06-01 00:00:00
                  2                                                        <NA>
                  3                                         1996-04-01 00:00:00
ADATE_4           1                                         1996-04-01 00:00:00
                  2                                                        <NA>
                  3                                         1996-07-01 00:00:00
                  4                                         1996-05-01 00:00:00
                  5                                         1996-09-01 00:00:00
ADATE_5           1                                         1996-04-01 00:00:00
                  2                                                        <NA>
ADATE_6           1                                         1996-03-01 00:00:00
                  2                                                        <NA>
                  3                                         1996-01-01 00:00:00
ADATE_7           1                                         1996-02-01 00:00:00
                  2                                                        <NA>
                  3                                         1996-01-01 00:00:00
                  4                                         1995-12-01 00:00:00
ADATE_8           1                                         1996-01-01 00:00:00
                  2                                         1995-12-01 00:00:00
                  3                                                        <NA>
                  4                                         1995-11-01 00:00:00
                  5                                         1996-03-01 00:00:00
ADATE_9           1                                         1995-11-01 00:00:00
                  2                                                        <NA>
                  3                                         1995-09-01 00:00:00
                  4                                         1995-10-01 00:00:00
AGEFLAG           1                                                       Exact
                  2                           Inferred from Date of Birth Field
                  3
BIBLE             1                                                        <NA>
                  2                                                         Yes
BOATS             1                                                        <NA>
                  2                                                         Yes
CARDS             1                                                        <NA>
                  2                                                         Yes
CATLG             1                                                        <NA>
                  2                                                         Yes
CDPLAY            1                                                        <NA>
                  2                                                         Yes
CHILD03           1                                                        <NA>
                  2                                                        Male
                  3                                                      Female
                  4                                                        Both
CHILD07           1                                                        <NA>
                  2                                                        Male
                  3                                                      Female
                  4                                                        Both
CHILD12           1                                                        <NA>
                  2                                                        Male
                  3                                                      Female
                  4                                                        Both
CHILD18           1                                                        <NA>
                  2                                                        Male
                  3                                                      Female
                  4                                                        Both
CLUSTER           1                                                          40
                  2                                                          24
                  3                                                          35
                  4                                                          27
                  5                                                          36
CLUSTER2          1                                                        13.0
                  2                                                         5.0
                  3                                                        15.0
                  4                                                        59.0
                  5                                                        57.0
COLLECT1          1                                                        <NA>
                  2                                                         Yes
CRAFTS            1                                                        <NA>
                  2                                                         Yes
DATASRCE          1                                                        Both
                  2                                                        Polk
                  3                                                        <NA>
                  4                                                   MetroMail
DOB               1                                         1948-01-01 00:00:00
                  2                                         1950-01-01 00:00:00
                  3                                         1930-01-01 00:00:00
                  4                                         1928-01-01 00:00:00
                  5                                         1944-01-01 00:00:00
DOMAIN_ses        1                                                 Average SES
                  2                                                 Highest SES
                  3                                                  Lowest SES
                  4                                                        <NA>
                  5                       Lower Lowest SES in Urban communities
DOMAIN_urbanicity 1                                                    Suburban
                  2                                                        City
                  3                                                        Town
                  4                                                       Rural
                  5                                                       Urban
FISHER            1                                                        <NA>
                  2                                                         Yes
FISTDATE          1                                         1995-01-01 00:00:00
                  2                                         1994-01-01 00:00:00
                  3                                         1993-10-01 00:00:00
                  4                                         1986-08-01 00:00:00
                  5                                         1994-10-01 00:00:00
GARDENIN          1                                                        <NA>
                  2                                                         Yes
GENDER            1                                                      Female
                  2                                                        Male
                  3                                                        <NA>
                  4                                                     Unknown
                  5                               Joint Account, unknown gender
GEOCODE           1     No code has been assigned or did not match at any level
                  2                                                          12
                  3                                                          03
                  4                                                          05
                  5                                                          14
GEOCODE2          1                                                           A
                  2                                                           B
                  3                                                           C
                  4                                                           D
                  5                                                        <NA>
HOMEE             1                                                        <NA>
                  2                                                         Yes
HOMEOWNR          1                                                   Homeowner
                  2                                                     Unknown
                  3                                                        <NA>
HPHONE_D          1                                                           1
                  2                                                           0
KIDSTUFF          1                                                        <NA>
                  2                                                         Yes
LASTDATE          1                                         1995-12-01 00:00:00
                  2                                         1996-01-01 00:00:00
                  3                                         1996-02-01 00:00:00
                  4                                         1996-03-01 00:00:00
                  5                                         1995-11-01 00:00:00
LIFESRC           1                                                        <NA>
                  2                                        MATCHED ON POLK ONLY
                  3                                    MATCHED BOTH MM AND POLK
                  4                                  MATCHED ON METRO MAIL ONLY
MAILCODE          1                                               Address is OK
                  2                                                 Bad Address
MAJOR             1                                           Not a Major Donor
                  2                                                 Major Donor
MAXADATE          1                                         1997-02-01 00:00:00
                  2                                         1996-12-01 00:00:00
                  3                                         1996-11-01 00:00:00
                  4                                         1997-01-01 00:00:00
                  5                                         1996-07-01 00:00:00
MAXRDATE          1                                         1995-12-01 00:00:00
                  2                                         1996-01-01 00:00:00
                  3                                         1995-09-01 00:00:00
                  4                                         1996-02-01 00:00:00
                  5                                         1995-04-01 00:00:00
MDMAUD_amount     1                                              Not applicable
                  2                                             $100-499 (Core)
                  3                                 Less than $100 (Low Dollar)
                  4                                            $500-999 (Major)
                  5                                               $1,000+ (Top)
MDMAUD_frequency  1                                              Not applicable
                  2                           One gift in the period of recency
                  3                     Two-Four gifts in the period of recency
                  4                        Five+ gifts in the period of recency
MDMAUD_recency    1                                              Not applicable
                  2                                               Current Donor
                  3                                                Lapsed Donor
                  4                                               Dormant Donor
                  5                                              Inactive Donor
MINRDATE          1                                         1996-01-01 00:00:00
                  2                                         1996-02-01 00:00:00
                  3                                         1995-12-01 00:00:00
                  4                                         1995-06-01 00:00:00
                  5                                         1994-01-01 00:00:00
NEXTDATE          1                                                        <NA>
                  2                                         1995-04-01 00:00:00
                  3                                         1987-03-01 00:00:00
                  4                                         1994-12-01 00:00:00
                  5                                         1986-12-01 00:00:00
NOEXCH            1                                                  0-nan-case
                  2                                                  1-nan-case
                  3                                         cannot be exchanged
                  4                                            can be exchanged
ODATEDW           1                                         1986-01-01 00:00:00
                  2                                         1995-01-01 00:00:00
                  3                                         1994-01-01 00:00:00
                  4                                         1991-01-01 00:00:00
                  5                                         1996-01-01 00:00:00
OSOURCE           1                                                         MBC
                  2                                                         BHG
                  3                                                         AML
                  4                                                         SYN
                  5                                                         IMP
PCOWNERS          1                                                        <NA>
                  2                                                         Yes
PEPSTRFL          1                                                        <NA>
                  2                                     Has PEP Star RFA Status
PETS              1                                                        <NA>
                  2                                                         Yes
PHOTO             1                                                        <NA>
                  2                                                         Yes

In [10]:
# Target Distribution
target_df

           count    pct
TARGET_B
0         136639  94.83
1           7456   5.17

## Task Curation

In [11]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [12]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [13]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to pva_revenue_prediction_kddcup98/019db49b-9c05-72b8-b4a5-7b967a18225b
019db49b-9c05-72b8-b4a5-7b967a18225b
ac7bab79289e3eb4b1139306571d44ec21ba05681e7582f10c38bf344482816b