### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="ieee_fraud_detection",
    dataset_year="2019",
    domain_str="finance",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/ieee-fraud-detection/overview",
    download_description=r"""
kaggle competitions download -c ieee-fraud-detection -p local-data-warehouse/ieee_fraud_detection \
&& unzip local-data-warehouse/ieee_fraud_detection/ieee-fraud-detection.zip -d local-data-warehouse/ieee_fraud_detection/ \
&& rm local-data-warehouse/ieee_fraud_detection/ieee-fraud-detection.zip
""",
    # References
    academic_reference_bibtex=r"""@misc{ieee-fraud-detection,
    author = {Addison Howard and Bernadette Bouchon-Meunier and IEEE CIS and inversion and John Lei and Lynn@Vesta and Marcus2010 and Prof. Hussein Abbass},
    title = {IEEE-CIS Fraud Detection},
    year = {2019},
    howpublished = {\url{https://kaggle.com/competitions/ieee-fraud-detection}},
    note = {Kaggle}
}
""",
    academic_reference_bibtex_key="ieee-fraud-detection",
    license="non-commercial purposes only, including academic research",
    data_tags=["Non-IID", "Temporal"],
    curation_comments="""
- We use insights of the first place solution on Kaggle for conceptualizing the task: https://www.kaggle.com/competitions/ieee-fraud-detection/discussion/111284
- The data is given as transactions, but the task is to predict fraudulent clients. Once a transaction is detected as fraud, the entire account is considered fraudulent.
- The competition host commented on the labeling logic: "The logic of our labeling is define reported chargeback on the card as fraud transaction (isFraud=1) and transactions posterior to it with either user account, email address or billing address directly linked to these attributes as fraud too" (https://www.kaggle.com/c/ieee-fraud-detection/discussion/101203#589276)
- We load train_transaction.csv and train_identity.csv and merge them on TransactionID.
- We derive Transaction_date from TransactionDT using the competition reference start date 2017-11-30.
- The Kaggle competition also provides test_transaction.csv and test_identity.csv, but they are unlabeled and are therefore excluded from df for curation checks.
- We normalize the D-columns, since they correspond to days since a certain event, we can normalize them by the transaction date to get the actual day of the event. This is also what the first place solution on Kaggle did.
- We add a uid feature used by the first place solution on Kaggle to identify unique users. Note that this feature is not perfect and just an approximation by the Kaggle users. Moreover, due to missing values, for ~15% of the samples no uid could be reconstructed.
- Following the first place Kaggle solution, which used month-based cross-validation, we create splits using forecasting horizons of 1 month.
- The competition test data left a planning window of one month, so do we.
- Anomaly: Missing values.
- Anomaly: Several features might allow to approximate to the uid and can lead to overfitting.
- Anomaly: Grouped data with members of a group often sharing the same label, depending on whether fraud occurred previously or not.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="isFraud",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    # For classification
    stratify_on="isFraud",
    # For time
    time_on="Transaction_date",
)

## Preprocessing

In [2]:
import pandas as pd
import datetime
import numpy as np

# LOAD TRAIN
df = pd.read_csv(dataset_mold.path / 'train_transaction.csv', index_col='TransactionID', engine="pyarrow")
train_id = pd.read_csv(dataset_mold.path / 'train_identity.csv', index_col='TransactionID', engine="pyarrow")
df = df.merge(train_id, how='left', left_index=True, right_index=True)

# LOAD TEST
# X_test = pd.read_csv(dataset_mold.path / 'test_transaction.csv', index_col='TransactionID', engine="pyarrow")
# test_id = pd.read_csv(dataset_mold.path / 'test_identity.csv', index_col='TransactionID', engine="pyarrow")
# fix = {o:n for o, n in zip(test_id.columns, train_id.columns)}
# test_id.rename(columns=fix, inplace=True)
# df_test = X_test.merge(test_id, how='left', left_index=True, right_index=True)

START_DATE = datetime.datetime.strptime('2017-11-30', '%Y-%m-%d')
df['Transaction_date'] = df['TransactionDT'].apply(lambda x: (START_DATE + datetime.timedelta(seconds=x)))
# df['DT_M'] = (df['Transaction_date'].dt.year - 2017) * 12 + df['Transaction_date'].dt.month

df['day'] = df['TransactionDT'] / (24 * 60 * 60)

# NORMALIZE D COLUMNS, since they correspond to days since a certain event, we can normalize them by the transaction date to get the actual day of the event. This is also what the first place solution on Kaggle did.
for i in range(1,16):
    if i in [1,2,3,5,9]: continue
    df['D'+str(i)] =  df['D'+str(i)] - df['TransactionDT']/np.float32(24*60*60)

df = df.drop(columns=['TransactionDT'])

# This is the uid that as used for feature engineering in the first place solution on Kaggle. They also have a better way to find uids 
# df['uid'] = df['card1'].astype(str) + '_' + df['addr1'].astype(str)  + '_' + np.floor(df.day - df.D1).astype(str)
# df.loc[np.logical_or(df['D1'].isna(), df['addr1'].isna()),["uid"]] = np.nan
# Use the uid version that has the best missing values (15%) vs. accuracy for same uid (99.96%)
uids = pd.read_csv('uids_v1_no_multiuid_cleaning.csv',usecols=['TransactionID','uid'],engine="pyarrow")
df = df.merge(uids,on='TransactionID',how='left')

# Obtain correct cat indices
cat_cols = ['ProductCD',"addr1","addr2","P_emaildomain","R_emaildomain","DeviceType","DeviceInfo"]
cat_cols += [f"card{i}" for i in range(1,7)]
cat_cols += [f"M{i}" for i in range(1,10)]
cat_cols += [f"id_{i}" for i in range(12,39)]
cat_cols += ["uid"]

for col in cat_cols:
    df[col] = df[col].astype('category')

df["isFraud"] = df["isFraud"].astype("category")
df = df.sort_values(by=["Transaction_date"]).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 590,540
Columns: 436
Use sampling: False (sample size: 590,540)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['TransactionID', 'day', 'Transaction_date', 'D10', 'D15', 'D4', 'D11', 'uid', 'id_02', 'D8']
Rows remaining as candidates after top-10 filter: 0 (of 590,540)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,TransactionID,isFraud,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,addr2,dist1,dist2,P_emaildomain,R_emaildomain,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14,D15,M1,M2,M3,M4,M5,M6,M7,M8,M9,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,V29,V30,V31,V32,V33,V34,V35,V36,V37,V38,V39,V40,V41,V42,V43,V44,V45,V46,V47,V48,V49,V50,V51,V52,V53,V54,V55,V56,V57,V58,V59,V60,V61,V62,V63,V64,V65,V66,V67,V68,V69,V70,V71,V72,V73,V74,V75,V76,V77,V78,V79,V80,V81,V82,V83,V84,V85,V86,V87,V88,V89,V90,V91,V92,V93,V94,V95,V96,V97,V98,V99,V100,V101,V102,V103,V104,V105,V106,V107,V108,V109,V110,V111,V112,V113,V114,V115,V116,V117,V118,V119,V120,V121,V122,V123,V124,V125,V126,V127,V128,V129,V130,V131,V132,V133,V134,V135,V136,V137,V138,V139,V140,V141,V142,V143,V144,V145,V146,V147,V148,V149,V150,V151,V152,V153,V154,V155,V156,V157,V158,V159,V160,V161,V162,V163,V164,V165,V166,V167,V168,V169,V170,V171,V172,V173,V174,V175,V176,V177,V178,V179,V180,V181,V182,V183,V184,V185,V186,V187,V188,V189,V190,V191,V192,V193,V194,V195,V196,V197,V198,V199,V200,V201,V202,V203,V204,V205,V206,V207,V208,V209,V210,V211,V212,V213,V214,V215,V216,V217,V218,V219,V220,V221,V222,V223,V224,V225,V226,V227,V228,V229,V230,V231,V232,V233,V234,V235,V236,V237,V238,V239,V240,V241,V242,V243,V244,V245,V246,V247,V248,V249,V250,V251,V252,V253,V254,V255,V256,V257,V258,V259,V260,V261,V262,V263,V264,V265,V266,V267,V268,V269,V270,V271,V272,V273,V274,V275,V276,V277,V278,V279,V280,V281,V282,V283,V284,V285,V286,V287,V288,V289,V290,V291,V292,V293,V294,V295,V296,V297,V298,V299,V300,V301,V302,V303,V304,V305,V306,V307,V308,V309,V310,V311,V312,V313,V314,V315,V316,V317,V318,V319,V320,V321,V322,V323,V324,V325,V326,V327,V328,V329,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,id_10,id_11,id_12,id_13,id_14,id_15,id_16,id_17,id_18,id_19,id_20,id_21,id_22,id_23,id_24,id_25,id_26,id_27,id_28,id_29,id_30,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo,Transaction_date,day,uid
0,2987000,0,68.5,W,13926,NaN,150.0,discover,142.0,credit,315.0,87.0,19.0,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,1.0,1.0,14.0,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,12.000000,12.000000,NaN,NaN,NaN,-1.000000,T,T,T,M2,F,T,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,117.0,0.0,0.0,0.0,0.0,0.0,117.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,117.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-01 00:00:00,1.000000,2987000.0
1,2987001,0,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,325.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,-1.000012,NaN,NaN,NaN,NaN,NaN,-1.000012,NaN,NaN,NaN,NaN,-1.000012,NaN,NaN,NaN,M0,T,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-01 00:00:01,1.000012,2987001.0
2,2987002,0,59.0,W,4663,490.0,150.0,visa,166.0,debit,330.0,87.0,287.0,NaN,outlook.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,-1.000799,NaN,NaN,NaN,NaN,NaN,-1.000799,313.999201,NaN,NaN,NaN,313.999201,T,T,T,M0,F,F,F,F,F,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-01 00:01:09,1.000799,2987002.0
3,2987003,0,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,476.0,87.0,NaN,NaN,yahoo.com,NaN,2.0,5.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0,1.0,0.0,25.0,1.0,112.0,112.0,0.0,92.998854,0.0,NaN,NaN,NaN,NaN,82.998854,NaN,NaN,NaN,NaN,109.998854,NaN,NaN,NaN,M0,T,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,48.0,28.0,0.0,10.0,4.0,1.0,38.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.0,1758.0,925.0,0.0,354.0,135.0,50.0,1404.0,790.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,28.0,0.0,0.0,0.0,0.0,10.0,0.0,4.0,0.0,0.0,1.0,1.0,1.0,1.0,38.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,50.0,1758.0,925.0,0.0,354.0,0.0,135.0,0.0,0.0,0.0,50.0,1404.0,790.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-01 00:01:39,1.001146,2987003.0
4,2987004,0,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,420.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,18.0,140.0,0.0,0.0,0.0,0.0,1803.0,49.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0,15557.990234,169690.796875,0.0,0.0,0.0,515.0,5155.0,2840.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NotFound,NaN,-480.0,New,NotFound,166.0,NaN,542.0,144.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NotFound,Android 7.0,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M,2017-12-01 00:01:46,1.001227,2987004.0

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,id_24,category,585793.0,99.20,12.0,"11.0, 15.0, 16.0, 18.0, 21.0, 24.0, 17.0, 26.0, 25.0, 19.0"
1,id_21,category,585381.0,99.13,490.0,"252.0, 228.0, 255.0, 596.0, 576.0, 849.0, 277.0, 755.0, 848.0, 668.0"
2,id_25,category,585408.0,99.13,341.0,"321.0, 205.0, 426.0, 501.0, 371.0, 524.0, 442.0, 509.0, 123.0, 126.0"
3,id_26,category,585377.0,99.13,95.0,"161.0, 184.0, 142.0, 102.0, 100.0, 119.0, 169.0, 147.0, 215.0, 121.0"
4,id_22,category,585371.0,99.12,25.0,"14.0, 41.0, 33.0, 21.0, 17.0, 39.0, 36.0, 22.0, 12.0, 31.0"
5,id_23,category,585371.0,99.12,3.0,"IP_PROXY:TRANSPARENT, IP_PROXY:ANONYMOUS, IP_PROXY:HIDDEN"
6,id_27,category,585371.0,99.12,2.0,"Found, NotFound"
7,id_18,category,545427.0,92.36,18.0,"15.0, 13.0, 12.0, 18.0, 20.0, 17.0, 26.0, 21.0, 24.0, 11.0"
8,id_33,category,517251.0,87.59,260.0,"1920x1080, 1366x768, 1334x750, 2208x1242, 1440x900, 1600x900, 2048x1536, 1280x800, 2560x1600, 2560x1440"
9,id_30,category,512975.0,86.87,75.0,"Windows 10, Windows 7, iOS 11.2.1, iOS 11.1.2, Android 7.0, Mac OS X 10_12_6, Mac OS X 10_11_6, iOS 11.3.0, Windows 8.1, Mac OS X 10_10_5"
10,id_32,category,512954.0,86.86,4.0,"24.0, 32.0, 16.0, 0.0"
11,id_34,category,512735.0,86.82,4.0,"match_status:2, match_status:1, match_status:0, match_status:-1"
12,id_14,category,510496.0,86.45,25.0,"-300.0, -360.0, -480.0, -420.0, -600.0, 60.0, 0.0, -240.0, -180.0, -540.0"
13,DeviceInfo,category,471874.0,79.91,1786.0,"Windows, iOS Device, MacOS, Trident/7.0, rv:11.0, rv:57.0, SM-J700M Build/MMB29K, SM-G610M Build/MMB29K, SM-G531H Build/LMY48B, rv:59.0"
14,id_13,category,463220.0,78.44,54.0,"52.0, 49.0, 64.0, 33.0, 27.0, 20.0, 14.0, 63.0, 19.0, 25.0"
15,id_16,category,461200.0,78.10,2.0,"Found, NotFound"
16,R_emaildomain,category,453249.0,76.75,60.0,"gmail.com, hotmail.com, anonymous.com, yahoo.com, aol.com, outlook.com, comcast.net, yahoo.com.mx, icloud.com, msn.com"
17,id_20,category,451279.0,76.42,394.0,"507.0, 222.0, 325.0, 533.0, 214.0, 549.0, 600.0, 563.0, 333.0, 595.0"
18,id_19,category,451222.0,76.41,522.0,"266.0, 410.0, 427.0, 529.0, 312.0, 100.0, 542.0, 215.0, 153.0, 417.0"
19,id_17,category,451171.0,76.40,104.0,"166.0, 225.0, 102.0, 159.0, 100.0, 121.0, 148.0, 150.0, 191.0, 142.0"
20,id_31,category,450258.0,76.25,130.0,"chrome 63.0, mobile safari 11.0, mobile safari generic, ie 11.0 for desktop, safari generic, chrome 62.0, chrome 65.0, chrome 64.0, chrome 63.0 for android, chrome generic"
21,DeviceType,category,449730.0,76.16,2.0,"desktop, mobile"
22,id_15,category,449555.0,76.13,3.0,"Found, New, Unknown"
23,id_28,category,449562.0,76.13,2.0,"Found, New"
24,id_29,category,449562.0,76.13,2.0,"Found, NotFound"
25,id_35,category,449555.0,76.13,2.0,"T, F"
26,id_36,category,449555.0,76.13,2.0,"F, T"
27,id_37,category,449555.0,76.13,2.0,"T, F"
28,id_38,category,449555.0,76.13,2.0,"F, T"
29,id_12,category,446307.0,75.58,2.0,"NotFound, Found"
30,M5,category,350482.0,59.35,2.0,"F, T"
31,M7,category,346265.0,58.64,2.0,"F, T"
32,M8,category,346252.0,58.63,2.0,"F, T"
33,M9,category,346252.0,58.63,2.0,"T, F"
34,M4,category,281444.0,47.66,3.0,"M0, M2, M1"
35,M1,category,271100.0,45.91,2.0,"T, F"
36,M2,category,271100.0,45.91,2.0,"T, F"
37,M3,category,271100.0,45.91,2.0,"T, F"
38,M6,category,169360.0,28.68,2.0,"F, T"
39,P_emaildomain,category,94456.0,15.99,59.0,"gmail.com, yahoo.com, hotmail.com, anonymous.com, aol.com, comcast.net, icloud.com, outlook.com, msn.com, att.net"
40,uid,category,92436.0,15.65,306173.0,"3428022.0, 2987225.0, 2997296.0, 3006103.0, 3144059.0, 2987765.0, 2989224.0, 3178521.0, 3129364.0, 3005731.0"
41,addr1,category,65706.0,11.13,332.0,"299.0, 325.0, 204.0, 264.0, 330.0, 315.0, 441.0, 272.0, 123.0, 126.0"
42,addr2,category,65706.0,11.13,74.0,"87.0, 60.0, 96.0, 32.0, 65.0, 16.0, 31.0, 19.0, 26.0, 27.0"
43,card2,category,8933.0,1.51,500.0,"321.0, 111.0, 555.0, 490.0, 583.0, 170.0, 194.0, 545.0, 360.0, 514.0"
44,card5,category,4259.0,0.72,119.0,"226.0, 224.0, 166.0, 102.0, 117.0, 138.0, 195.0, 137.0, 126.0, 219.0"
45,card3,category,1565.0,0.27,114.0,"150.0, 185.0, 106.0, 144.0, 146.0, 117.0, 143.0, 119.0, 102.0, 147.0"
46,card4,category,1577.0,0.27,4.0,"visa, mastercard, american express, discover"
47,card6,category,1571.0,0.27,4.0,"debit, credit, debit or credit, charge card"
48,isFraud,category,0.0,0.00,2.0,"0, 1"
49,ProductCD,category,0.0,0.00,5.0,"W, C, R, H, S"
50,card1,category,0.0,0.00,13553.0,"7919, 9500, 15885, 17188, 15066, 12695, 12544, 6019, 2803, 7585"
51,Transaction_date,datetime64[ns],0.0,0.00,573349.0,"2018-03-19 15:53:37, 2018-01-19 21:24:26, 2018-04-12 23:49:11, 2018-02-21 18:09:48, 2017-12-23 23:54:56, 2018-03-05 02:58:27, 2018-03-05 02:58:28, 2017-12-17 21:03:49, 2018-02-22 22:04:14, 2017-12-22 19:43:59"
52,id_07,float64,585385.0,99.13,84.0,"0.0, 16.0, 14.0, 12.0, 15.0, 17.0, 4.0, 13.0, 5.0, 10.0"
53,id_08,float64,585385.0,99.13,94.0,"-100.0, 0.0, -34.0, -33.0, -32.0, -35.0, -25.0, -31.0, -30.0, -24.0"
54,dist2,float64,552913.0,93.63,1751.0,"7.0, 0.0, 1.0, 9.0, 4.0, 2.0, 3.0, 68.0, 6.0, 13.0"
55,D7,float64,551623.0,93.41,38869.0,"-62.0756, -169.0062, -22.7203, -53.7887, -22.7571, -22.9456, -13.8738, -117.2203, -152.7495, -158.0575"
56,D13,float64,528588.0,89.51,61772.0,"-9.9515, -169.0062, -19.1569, -145.642, -29.0092, -55.179, -166.706, -78.9215, -145.6376, -56.9813"
57,D14,float64,528353.0,89.47,62047.0,"-21.8569, 84.3218, -52.641, -67.2717, -9.0177, -170.6809, -6.1058, -22.6582, -138.5945, -109.6381"
58,D12,float64,525823.0,89.04,64551.0,"-159.8919, -62.0756, -154.0968, -23.0734, -21.7893, -22.8682, -85.6475, -74.9819, -28.7997, -64.0161"
59,id_03,float64,524216.0,88.77,24.0,"0.0, 1.0, 3.0, 2.0, 5.0, 4.0, 6.0, -5.0, -6.0, -7.0"
60,id_04,float64,524216.0,88.77,15.0,"0.0, -5.0, -6.0, -8.0, -4.0, -1.0, -11.0, -12.0, -10.0, -9.0"
61,D6,float64,517353.0,87.61,72978.0,"-120.9887, -124.0164, -162.7536, -47.2522, -25.8375, -44.8049, -63.8713, -124.0477, -11.8834, -114.847"
62,D8,float64,515614.0,87.31,74510.0,"1120.9826, -17.0001, 820.9596, -145.0294, -145.0131, -145.0067, 62.9765, -95.0117, -145.0172, -145.027"
63,D9,float64,515614.0,87.31,24.0,"0.7917, 0.8333, 0.75, 0.7083, 0.6667, 0.875, 0.9167, 0.9583, 0.625, 0.0"
64,id_09,float64,515614.0,87.31,46.0,"0.0, 1.0, 3.0, 2.0, 4.0, 5.0, 6.0, -6.0, -5.0, -4.0"
65,id_10,float64,515614.0,87.31,62.0,"0.0, -6.0, -5.0, -1.0, -8.0, -11.0, -9.0, -12.0, -10.0, -7.0"
66,V138,float64,508595.0,86.12,23.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0, 7.0, 15.0"
67,V139,float64,508595.0,86.12,34.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
68,V140,float64,508595.0,86.12,34.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
69,V141,float64,508595.0,86.12,6.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0"
70,V142,float64,508595.0,86.12,10.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 9.0, 7.0, 8.0"
71,V143,float64,508589.0,86.12,870.0,"0.0, 1.0, 2.0, 3.0, 4.0, 28.0, 13.0, 30.0, 24.0, 5.0"
72,V144,float64,508589.0,86.12,63.0,"0.0, 1.0, 2.0, 11.0, 3.0, 4.0, 15.0, 5.0, 40.0, 39.0"
73,V145,float64,508589.0,86.12,260.0,"0.0, 1.0, 2.0, 3.0, 35.0, 4.0, 142.0, 143.0, 39.0, 5.0"
74,V146,float64,508595.0,86.12,25.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 11.0, 8.0"
75,V147,float64,508595.0,86.12,27.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 11.0, 8.0"
76,V148,float64,508595.0,86.12,21.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 20.0"
77,V149,float64,508595.0,86.12,21.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
78,V150,float64,508589.0,86.12,1996.0,"1.0, 2.0, 3.0, 4.0, 5.0, 97.0, 98.0, 100.0, 95.0, 84.0"
79,V151,float64,508589.0,86.12,56.0,"1.0, 52.0, 53.0, 51.0, 54.0, 2.0, 50.0, 55.0, 49.0, 56.0"
80,V152,float64,508589.0,86.12,39.0,"1.0, 68.0, 2.0, 65.0, 64.0, 67.0, 66.0, 53.0, 69.0, 57.0"
81,V153,float64,508595.0,86.12,19.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 16.0, 18.0, 7.0"
82,V154,float64,508595.0,86.12,19.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 16.0"
83,V155,float64,508595.0,86.12,25.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 24.0"
84,V156,float64,508595.0,86.12,25.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
85,V157,float64,508595.0,86.12,25.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 24.0"
86,V158,float64,508595.0,86.12,25.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
87,V159,float64,508589.0,86.12,6663.0,"0.0, 100.0, 50.0, 265.0, 25.0, 106.0, 20.0, 181.0, 10.0, 15.0"
88,V160,float64,508589.0,86.12,9621.0,"0.0, 2401.0, 50.0, 100.0, 1359.0, 25.0, 150.0, 200.0, 20.0, 75.0"
89,V161,float64,508595.0,86.12,79.0,"0.0, 50.0, 100.0, 25.0, 150.0, 200.0, 20.0, 40.0, 30.0, 75.0"
90,V162,float64,508595.0,86.12,185.0,"0.0, 50.0, 100.0, 150.0, 25.0, 200.0, 75.0, 30.0, 20.0, 300.0"
91,V163,float64,508595.0,86.12,106.0,"0.0, 50.0, 100.0, 150.0, 25.0, 200.0, 20.0, 75.0, 30.0, 40.0"
92,V164,float64,508589.0,86.12,1978.0,"0.0, 100.0, 200.0, 150.0, 300.0, 50.0, 400.0, 450.0, 75.0, 600.0"
93,V165,float64,508589.0,86.12,2547.0,"0.0, 100.0, 200.0, 150.0, 300.0, 50.0, 400.0, 600.0, 75.0, 250.0"
94,V166,float64,508589.0,86.12,987.0,"0.0, 100.0, 200.0, 1165.0, 150.0, 300.0, 50.0, 400.0, 500.0, 600.0"
95,V322,float64,508189.0,86.05,881.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
96,V323,float64,508189.0,86.05,1411.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
97,V324,float64,508189.0,86.05,976.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
98,V325,float64,508189.0,86.05,13.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
99,V326,float64,508189.0,86.05,45.0,"0.0, 1.0, 2.0, 27.0, 3.0, 18.0, 4.0, 5.0, 6.0, 7.0"
100,V327,float64,508189.0,86.05,19.0,"0.0, 1.0, 2.0, 10.0, 3.0, 7.0, 9.0, 4.0, 5.0, 8.0"
101,V328,float64,508189.0,86.05,16.0,"0.0, 1.0, 2.0, 11.0, 3.0, 4.0, 15.0, 5.0, 12.0, 6.0"
102,V329,float64,508189.0,86.05,100.0,"0.0, 1.0, 2.0, 77.0, 3.0, 4.0, 38.0, 5.0, 6.0, 7.0"
103,V330,float64,508189.0,86.05,56.0,"0.0, 1.0, 2.0, 3.0, 35.0, 4.0, 39.0, 32.0, 42.0, 43.0"
104,V331,float64,508189.0,86.05,1758.0,"0.0, 100.0, 200.0, 50.0, 150.0, 300.0, 25.0, 400.0, 250.0, 75.0"
105,V332,float64,508189.0,86.05,2453.0,"0.0, 100.0, 50.0, 200.0, 150.0, 300.0, 25.0, 250.0, 75.0, 400.0"
106,V333,float64,508189.0,86.05,1971.0,"0.0, 100.0, 200.0, 50.0, 150.0, 300.0, 25.0, 400.0, 75.0, 250.0"
107,V334,float64,508189.0,86.05,143.0,"0.0, 100.0, 50.0, 25.0, 265.0, 150.0, 20.0, 106.0, 181.0, 10.0"
108,V335,float64,508189.0,86.05,672.0,"0.0, 2301.0, 100.0, 50.0, 150.0, 25.0, 1259.0, 200.0, 30.0, 75.0"
109,V336,float64,508189.0,86.05,356.0,"0.0, 50.0, 1052.0, 100.0, 25.0, 619.0, 150.0, 942.0, 20.0, 30.0"
110,V337,float64,508189.0,86.05,254.0,"0.0, 100.0, 1165.0, 200.0, 150.0, 50.0, 300.0, 250.0, 400.0, 25.0"
111,V338,float64,508189.0,86.05,380.0,"0.0, 100.0, 200.0, 7709.0, 50.0, 150.0, 300.0, 25.0, 250.0, 400.0"
112,V339,float64,508189.0,86.05,334.0,"0.0, 100.0, 200.0, 150.0, 50.0, 300.0, 3657.0, 250.0, 25.0, 400.0"
113,V217,float64,460110.0,77.91,304.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
114,V218,float64,460110.0,77.91,401.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
115,V219,float64,460110.0,77.91,379.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
116,V223,float64,460110.0,77.91,17.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 7.0, 6.0, 8.0, 14.0"
117,V224,float64,460110.0,77.91,79.0,"0.0, 1.0, 2.0, 3.0, 4.0, 18.0, 5.0, 6.0, 7.0, 8.0"
118,V225,float64,460110.0,77.91,35.0,"0.0, 1.0, 2.0, 3.0, 7.0, 4.0, 5.0, 6.0, 8.0, 10.0"
119,V226,float64,460110.0,77.91,81.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
120,V228,float64,460110.0,77.91,55.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
121,V229,float64,460110.0,77.91,91.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
122,V230,float64,460110.0,77.91,66.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
123,V231,float64,460110.0,77.91,294.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
124,V232,float64,460110.0,77.91,338.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
125,V233,float64,460110.0,77.91,333.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
126,V235,float64,460110.0,77.91,24.0,"0.0, 1.0, 2.0, 3.0, 4.0, 15.0, 5.0, 11.0, 6.0, 12.0"
127,V236,float64,460110.0,77.91,46.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 38.0, 6.0, 7.0, 34.0"
128,V237,float64,460110.0,77.91,40.0,"0.0, 1.0, 2.0, 3.0, 4.0, 32.0, 5.0, 6.0, 28.0, 29.0"
129,V240,float64,460110.0,77.91,6.0,"1.0, 2.0, 6.0, 0.0, 5.0, 7.0"
130,V241,float64,460110.0,77.91,5.0,"1.0, 2.0, 0.0, 4.0, 5.0"
131,V242,float64,460110.0,77.91,21.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
132,V243,float64,460110.0,77.91,43.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
133,V244,float64,460110.0,77.91,23.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
134,V246,float64,460110.0,77.91,46.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
135,V247,float64,460110.0,77.91,19.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
136,V248,float64,460110.0,77.91,23.0,"1.0, 2.0, 3.0, 4.0, 5.0, 35.0, 6.0, 7.0, 8.0, 34.0"
137,V249,float64,460110.0,77.91,23.0,"1.0, 2.0, 3.0, 4.0, 5.0, 19.0, 21.0, 6.0, 20.0, 7.0"
138,V252,float64,460110.0,77.91,25.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
139,V253,float64,460110.0,77.91,66.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
140,V254,float64,460110.0,77.91,45.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 9.0, 8.0, 46.0"
141,V257,float64,460110.0,77.91,49.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
142,V258,float64,460110.0,77.91,67.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
143,V260,float64,460110.0,77.91,9.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0"
144,V261,float64,460110.0,77.91,41.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 7.0, 8.0, 6.0, 9.0"
145,V262,float64,460110.0,77.91,21.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 16.0"
146,V263,float64,460110.0,77.91,10422.0,"0.0, 100.0, 200.0, 50.0, 150.0, 300.0, 400.0, 25.0, 75.0, 600.0"
147,V264,float64,460110.0,77.91,13358.0,"0.0, 100.0, 50.0, 200.0, 150.0, 300.0, 25.0, 400.0, 75.0, 250.0"
148,V265,float64,460110.0,77.91,11757.0,"0.0, 100.0, 50.0, 200.0, 150.0, 300.0, 400.0, 25.0, 75.0, 250.0"
149,V266,float64,460110.0,77.91,2178.0,"0.0, 50.0, 100.0, 25.0, 150.0, 106.0, 181.0, 20.0, 200.0, 15.0"
150,V267,float64,460110.0,77.91,3616.0,"0.0, 100.0, 50.0, 25.0, 150.0, 1259.0, 200.0, 20.0, 75.0, 30.0"
151,V268,float64,460110.0,77.91,2756.0,"0.0, 50.0, 100.0, 25.0, 619.0, 150.0, 30.0, 20.0, 15.0, 200.0"
152,V269,float64,460110.0,77.91,151.0,"0.0, 100.0, 106.0, 181.0, 50.0, 150.0, 25.0, 20.0, 1000.0, 10.0"
153,V273,float64,460110.0,77.91,7177.0,"0.0, 100.0, 200.0, 150.0, 50.0, 300.0, 75.0, 400.0, 25.0, 600.0"
154,V274,float64,460110.0,77.91,8315.0,"0.0, 100.0, 200.0, 150.0, 50.0, 300.0, 400.0, 75.0, 600.0, 25.0"
155,V275,float64,460110.0,77.91,7776.0,"0.0, 100.0, 200.0, 150.0, 50.0, 300.0, 400.0, 75.0, 600.0, 25.0"
156,V276,float64,460110.0,77.91,2263.0,"0.0, 100.0, 200.0, 150.0, 50.0, 300.0, 400.0, 250.0, 600.0, 500.0"
157,V277,float64,460110.0,77.91,2540.0,"0.0, 100.0, 200.0, 50.0, 150.0, 300.0, 400.0, 250.0, 600.0, 500.0"
158,V278,float64,460110.0,77.91,2398.0,"0.0, 100.0, 200.0, 150.0, 50.0, 300.0, 400.0, 250.0, 600.0, 500.0"
159,id_05,float64,453675.0,76.82,93.0,"0.0, 1.0, 2.0, 3.0, 4.0, 6.0, 5.0, 7.0, 8.0, 9.0"
160,id_06,float64,453675.0,76.82,101.0,"0.0, -1.0, -5.0, -6.0, -9.0, -100.0, -8.0, -10.0, -11.0, -7.0"
161,V167,float64,450909.0,76.36,873.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
162,V168,float64,450909.0,76.36,965.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
163,V172,float64,450909.0,76.36,32.0,"0.0, 1.0, 2.0, 3.0, 4.0, 7.0, 5.0, 6.0, 11.0, 12.0"
164,V173,float64,450909.0,76.36,8.0,"0.0, 1.0, 2.0, 3.0, 4.0, 6.0, 5.0, 7.0"
165,V176,float64,450909.0,76.36,49.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
166,V177,float64,450909.0,76.36,862.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
167,V178,float64,450909.0,76.36,1236.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
168,V179,float64,450909.0,76.36,921.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
169,V181,float64,450909.0,76.36,25.0,"0.0, 1.0, 2.0, 11.0, 3.0, 4.0, 15.0, 5.0, 6.0, 7.0"
170,V182,float64,450909.0,76.36,84.0,"0.0, 1.0, 2.0, 3.0, 61.0, 4.0, 5.0, 34.0, 6.0, 7.0"
171,V183,float64,450909.0,76.36,42.0,"0.0, 1.0, 2.0, 3.0, 27.0, 4.0, 30.0, 5.0, 6.0, 7.0"
172,V186,float64,450909.0,76.36,39.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
173,V187,float64,450909.0,76.36,215.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 13.0"
174,V190,float64,450909.0,76.36,43.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
175,V191,float64,450909.0,76.36,22.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 12.0, 10.0"
176,V192,float64,450909.0,76.36,45.0,"1.0, 2.0, 3.0, 40.0, 38.0, 4.0, 34.0, 33.0, 41.0, 37.0"
177,V193,float64,450909.0,76.36,38.0,"1.0, 2.0, 3.0, 4.0, 14.0, 7.0, 5.0, 29.0, 12.0, 26.0"
178,V196,float64,450909.0,76.36,39.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0, 9.0, 7.0, 11.0"
179,V199,float64,450909.0,76.36,46.0,"1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0"
180,V202,float64,450909.0,76.36,10970.0,"0.0, 100.0, 200.0, 50.0, 150.0, 300.0, 400.0, 25.0, 250.0, 75.0"
181,V203,float64,450909.0,76.36,14951.0,"0.0, 100.0, 200.0, 50.0, 150.0, 300.0, 400.0, 25.0, 75.0, 250.0"
182,V204,float64,450909.0,76.36,12858.0,"0.0, 100.0, 200.0, 50.0, 150.0, 300.0, 400.0, 25.0, 75.0, 250.0"
183,V205,float64,450909.0,76.36,2240.0,"0.0, 100.0, 50.0, 150.0, 25.0, 265.0, 106.0, 20.0, 200.0, 181.0"
184,V206,float64,450909.0,76.36,1780.0,"0.0, 100.0, 50.0, 150.0, 25.0, 200.0, 300.0, 250.0, 1000.0, 75.0"
185,V207,float64,450909.0,76.36,3246.0,"0.0, 877.0, 50.0, 100.0, 619.0, 25.0, 150.0, 20.0, 30.0, 200.0"
186,V211,float64,450909.0,76.36,7624.0,"0.0, 100.0, 200.0, 150.0, 50.0, 300.0, 75.0, 400.0, 600.0, 25.0"
187,V212,float64,450909.0,76.36,8868.0,"0.0, 100.0, 200.0, 150.0, 50.0, 300.0, 400.0, 75.0, 25.0, 600.0"
188,V213,float64,450909.0,76.36,8317.0,"0.0, 100.0, 200.0, 150.0, 50.0, 300.0, 400.0, 75.0, 600.0, 25.0"
189,V214,float64,450909.0,76.36,2282.0,"0.0, 100.0, 200.0, 1165.0, 150.0, 300.0, 50.0, 400.0, 250.0, 500.0"
190,V215,float64,450909.0,76.36,2747.0,"0.0, 100.0, 200.0, 6428.0, 50.0, 150.0, 300.0, 400.0, 250.0, 500.0"
191,V216,float64,450909.0,76.36,2532.0,"0.0, 100.0, 200.0, 150.0, 50.0, 300.0, 2932.0, 400.0, 250.0, 500.0"
192,V169,float64,450721.0,76.32,20.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
193,V170,float64,450721.0,76.32,49.0,"1.0, 2.0, 0.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
194,V171,float64,450721.0,76.32,62.0,"1.0, 2.0, 0.0, 3.0, 4.0, 5.0, 14.0, 6.0, 7.0, 8.0"
195,V174,float64,450721.0,76.32,9.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0, 7.0"
196,V175,float64,450721.0,76.32,15.0,"0.0, 1.0, 2.0, 7.0, 3.0, 4.0, 5.0, 6.0, 8.0, 9.0"
197,V180,float64,450721.0,76.32,84.0,"0.0, 1.0, 2.0, 3.0, 61.0, 4.0, 5.0, 34.0, 6.0, 30.0"
198,V184,float64,450721.0,76.32,17.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0, 7.0, 11.0"
199,V185,float64,450721.0,76.32,32.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 11.0"
200,V188,float64,450721.0,76.32,31.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 11.0, 9.0"
201,V189,float64,450721.0,76.32,31.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 7.0, 6.0, 8.0, 9.0"
202,V194,float64,450721.0,76.32,8.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0"
203,V195,float64,450721.0,76.32,17.0,"1.0, 0.0, 2.0, 3.0, 8.0, 4.0, 6.0, 5.0, 7.0, 15.0"
204,V197,float64,450721.0,76.32,15.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 11.0"
205,V198,float64,450721.0,76.32,22.0,"1.0, 0.0, 2.0, 3.0, 4.0, 14.0, 5.0, 6.0, 8.0, 11.0"
206,V200,float64,450721.0,76.32,46.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 9.0, 8.0"
207,V201,float64,450721.0,76.32,56.0,"1.0, 0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 9.0, 8.0"
208,V208,float64,450721.0,76.32,2552.0,"0.0, 75.0, 50.0, 100.0, 25.0, 20.0, 150.0, 200.0, 15.0, 30.0"
209,V209,float64,450721.0,76.32,3451.0,"0.0, 1961.0, 50.0, 100.0, 1084.0, 25.0, 150.0, 200.0, 75.0, 20.0"
210,V210,float64,450721.0,76.32,2836.0,"0.0, 465.0, 50.0, 100.0, 25.0, 150.0, 200.0, 20.0, 75.0, 30.0"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
TransactionID,590540.0,3.282270e+06,170474.358321,2.987000e+06,3.577539e+06
TransactionAmt,590540.0,1.350272e+02,239.162522,2.510000e-01,3.193739e+04
dist1,238269.0,1.185022e+02,371.872026,0.000000e+00,1.028600e+04
dist2,37627.0,2.318554e+02,529.053494,0.000000e+00,1.162300e+04
C1,590540.0,1.409246e+01,133.569018,0.000000e+00,4.685000e+03
C2,590540.0,1.526973e+01,154.668899,0.000000e+00,5.691000e+03
C3,590540.0,5.643987e-03,0.150536,0.000000e+00,2.600000e+01
C4,590540.0,4.092185e+00,68.848459,0.000000e+00,2.253000e+03
C5,590540.0,5.571526e+00,25.786976,0.000000e+00,3.490000e+02
C6,590540.0,9.071082e+00,71.508467,0.000000e+00,2.253000e+03
C7,590540.0,2.848478e+00,61.727304,0.000000e+00,2.255000e+03
C8,590540.0,5.144574e+00,95.378574,0.000000e+00,3.331000e+03
C9,590540.0,4.480240e+00,16.674897,0.000000e+00,2.100000e+02
C10,590540.0,5.240343e+00,95.581443,0.000000e+00,3.257000e+03
C11,590540.0,1.024152e+01,94.336292,0.000000e+00,3.188000e+03
C12,590540.0,4.076227e+00,86.666218,0.000000e+00,3.188000e+03
C13,590540.0,3.253992e+01,129.364844,0.000000e+00,2.918000e+03
C14,590540.0,8.295215e+00,49.544262,0.000000e+00,1.429000e+03
D1,589271.0,9.434757e+01,157.660387,0.000000e+00,6.400000e+02
D2,309743.0,1.695632e+02,177.315865,0.000000e+00,6.400000e+02
D3,327662.0,2.834335e+01,62.384721,0.000000e+00,8.190000e+02
D4,421618.0,5.016278e+01,194.923224,-2.156725e+02,6.985086e+02
D5,280699.0,4.233596e+01,89.000144,0.000000e+00,8.190000e+02
D6,73187.0,-1.429075e+01,149.141793,-2.156725e+02,6.968838e+02
D7,38917.0,-4.695873e+01,117.040023,-1.829954e+02,6.968838e+02
D8,74926.0,7.286749e+01,242.180686,-1.820416e+02,1.692974e+03
D9,74926.0,5.610571e-01,0.316880,0.000000e+00,9.583330e-01
D10,514518.0,3.461559e+01,186.964355,-1.829986e+02,6.985086e+02
D11,311253.0,4.513833e+01,187.788387,-1.829992e+02,4.910396e+02
D12,64717.0,-2.963975e+01,132.335186,-2.156725e+02,4.852623e+02
D13,61952.0,-6.924489e+01,85.101168,-1.829980e+02,6.980525e+02
D14,62187.0,-2.627100e+01,141.612618,-1.948765e+02,6.980296e+02
D15,501427.0,7.442936e+01,205.585624,-2.156725e+02,6.985086e+02
V1,311253.0,9.999454e-01,0.007390,0.000000e+00,1.000000e+00
V2,311253.0,1.045204e+00,0.240133,0.000000e+00,8.000000e+00
V3,311253.0,1.078075e+00,0.320890,0.000000e+00,9.000000e+00
V4,311253.0,8.464561e-01,0.440053,0.000000e+00,6.000000e+00
V5,311253.0,8.769907e-01,0.475902,0.000000e+00,6.000000e+00
V6,311253.0,1.045686e+00,0.239385,0.000000e+00,9.000000e+00
V7,311253.0,1.072870e+00,0.304779,0.000000e+00,9.000000e+00
V8,311253.0,1.027704e+00,0.186069,0.000000e+00,8.000000e+00
V9,311253.0,1.041529e+00,0.226339,0.000000e+00,8.000000e+00
V10,311253.0,4.639152e-01,0.521522,0.000000e+00,4.000000e+00
V11,311253.0,4.789865e-01,0.552431,0.000000e+00,5.000000e+00
V12,514467.0,5.597113e-01,0.510533,0.000000e+00,3.000000e+00
V13,514467.0,5.991657e-01,0.532185,0.000000e+00,6.000000e+00
V14,514467.0,9.995005e-01,0.022345,0.000000e+00,1.000000e+00
V15,514467.0,1.223422e-01,0.332422,0.000000e+00,7.000000e+00
V16,514467.0,1.234598e-01,0.342841,0.000000e+00,1.500000e+01
V17,514467.0,1.340397e-01,0.364456,0.000000e+00,1.500000e+01
V18,514467.0,1.353634e-01,0.371763,0.000000e+00,1.500000e+01
V19,514467.0,8.163711e-01,0.425512,0.000000e+00,7.000000e+00
V20,514467.0,8.478425e-01,0.459451,0.000000e+00,1.500000e+01
V21,514467.0,1.296837e-01,0.339060,0.000000e+00,5.000000e+00
V22,514467.0,1.322923e-01,0.359415,0.000000e+00,8.000000e+00
V23,514467.0,1.034791e+00,0.247681,0.000000e+00,1.300000e+01
V24,514467.0,1.058097e+00,0.305485,0.000000e+00,1.300000e+01
V25,514467.0,9.776604e-01,0.185245,0.000000e+00,7.000000e+00
V26,514467.0,9.880400e-01,0.209302,0.000000e+00,1.300000e+01
V27,514467.0,7.755599e-04,0.028596,0.000000e+00,4.000000e+00
V28,514467.0,8.299852e-04,0.031133,0.000000e+00,4.000000e+00
V29,514467.0,3.878402e-01,0.510652,0.000000e+00,5.000000e+00
V30,514467.0,4.064362e-01,0.554311,0.000000e+00,9.000000e+00
V31,514467.0,1.407612e-01,0.355793,0.000000e+00,7.000000e+00
V32,514467.0,1.424173e-01,0.368278,0.000000e+00,1.500000e+01
V33,514467.0,1.306925e-01,0.340900,0.000000e+00,7.000000e+00
V34,514467.0,1.391537e-01,0.357549,0.000000e+00,1.300000e+01
V35,421571.0,5.425942e-01,0.516010,0.000000e+00,3.000000e+00
V36,421571.0,5.791978e-01,0.539039,0.000000e+00,5.000000e+00
V37,421571.0,1.108065e+00,0.690571,0.000000e+00,5.400000e+01
V38,421571.0,1.162400e+00,0.858920,0.000000e+00,5.400000e+01
V39,421571.0,1.660764e-01,0.451956,0.000000e+00,1.500000e+01
V40,421571.0,1.771445e-01,0.505786,0.000000e+00,2.400000e+01
V41,421571.0,9.992694e-01,0.027020,0.000000e+00,1.000000e+00
V42,421571.0,1.561184e-01,0.382896,0.000000e+00,8.000000e+00
V43,421571.0,1.689419e-01,0.433359,0.000000e+00,8.000000e+00
V44,421571.0,1.083891e+00,0.639143,0.000000e+00,4.800000e+01
V45,421571.0,1.120779e+00,0.729774,0.000000e+00,4.800000e+01
V46,421571.0,1.022286e+00,0.166719,0.000000e+00,6.000000e+00
V47,421571.0,1.038515e+00,0.231862,0.000000e+00,1.200000e+01
V48,421571.0,3.831739e-01,0.508189,0.000000e+00,5.000000e+00
V49,421571.0,3.977242e-01,0.542654,0.000000e+00,5.000000e+00
V50,421571.0,1.647457e-01,0.373995,0.000000e+00,5.000000e+00
V51,421571.0,1.705786e-01,0.403899,0.000000e+00,6.000000e+00
V52,421571.0,1.826952e-01,0.439002,0.000000e+00,1.200000e+01
V53,513444.0,5.775859e-01,0.511571,0.000000e+00,5.000000e+00
V54,513444.0,6.199819e-01,0.534635,0.000000e+00,6.000000e+00
V55,513444.0,1.067670e+00,0.391364,0.000000e+00,1.700000e+01
V56,513444.0,1.120979e+00,0.661129,0.000000e+00,5.100000e+01
V57,513444.0,1.283119e-01,0.349094,0.000000e+00,6.000000e+00
V58,513444.0,1.324526e-01,0.372907,0.000000e+00,1.000000e+01
V59,513444.0,1.344334e-01,0.379291,0.000000e+00,1.600000e+01
V60,513444.0,1.425375e-01,0.418230,0.000000e+00,1.600000e+01
V61,513444.0,8.297847e-01,0.436617,0.000000e+00,6.000000e+00
V62,513444.0,8.675630e-01,0.483803,0.000000e+00,1.000000e+01
V63,513444.0,1.307426e-01,0.355262,0.000000e+00,7.000000e+00
V64,513444.0,1.418246e-01,0.406157,0.000000e+00,7.000000e+00
V65,513444.0,9.996631e-01,0.018353,0.000000e+00,1.000000e+00
V66,513444.0,9.810379e-01,0.216235,0.000000e+00,7.000000e+00
V67,513444.0,9.981205e-01,0.245912,0.000000e+00,8.000000e+00
V68,513444.0,5.336512e-04,0.023760,0.000000e+00,2.000000e+00
V69,513444.0,3.902003e-01,0.513696,0.000000e+00,5.000000e+00
V70,513444.0,4.079237e-01,0.554499,0.000000e+00,6.000000e+00
V71,513444.0,1.406385e-01,0.364303,0.000000e+00,6.000000e+00
V72,513444.0,1.451239e-01,0.389212,0.000000e+00,1.000000e+01
V73,513444.0,1.399822e-01,0.367098,0.000000e+00,7.000000e+00
V74,513444.0,1.521471e-01,0.393274,0.000000e+00,8.000000e+00
V75,501376.0,5.442781e-01,0.514318,0.000000e+00,4.000000e+00
V76,501376.0,5.875570e-01,0.538230,0.000000e+00,6.000000e+00
V77,501376.0,1.086893e+00,0.532958,0.000000e+00,3.000000e+01
V78,501376.0,1.144462e+00,0.781474,0.000000e+00,3.100000e+01
V79,501376.0,1.368673e-01,0.379904,0.000000e+00,7.000000e+00
V80,501376.0,1.439538e-01,0.409932,0.000000e+00,1.900000e+01
V81,501376.0,1.526958e-01,0.452298,0.000000e+00,1.900000e+01
V82,501376.0,8.446096e-01,0.422529,0.000000e+00,7.000000e+00
V83,501376.0,8.819648e-01,0.470757,0.000000e+00,7.000000e+00
V84,501376.0,1.371446e-01,0.361875,0.000000e+00,7.000000e+00
V85,501376.0,1.497878e-01,0.419445,0.000000e+00,7.000000e+00
V86,501376.0,1.064885e+00,0.419807,0.000000e+00,3.000000e+01
V87,501376.0,1.099456e+00,0.511281,0.000000e+00,3.000000e+01
V88,501376.0,9.992461e-01,0.027447,0.000000e+00,1.000000e+00
V89,501376.0,9.015190e-04,0.031943,0.000000e+00,2.000000e+00
V90,501376.0,4.018621e-01,0.516153,0.000000e+00,5.000000e+00
V91,501376.0,4.204609e-01,0.561865,0.000000e+00,6.000000e+00
V92,501376.0,1.503223e-01,0.375682,0.000000e+00,7.000000e+00
V93,501376.0,1.548120e-01,0.402314,0.000000e+00,7.000000e+00
V94,501376.0,1.370070e-01,0.343878,0.000000e+00,2.000000e+00
V95,590226.0,1.038019e+00,21.034304,0.000000e+00,8.800000e+02
V96,590226.0,3.005190e+00,40.239490,0.000000e+00,1.410000e+03
V97,590226.0,1.718933e+00,27.700449,0.000000e+00,9.760000e+02
V98,590226.0,6.198473e-02,0.284995,0.000000e+00,1.200000e+01
V99,590226.0,8.949860e-01,2.722552,0.000000e+00,8.800000e+01
V100,590226.0,2.735037e-01,0.947176,0.000000e+00,2.800000e+01
V101,590226.0,8.892492e-01,20.582571,0.000000e+00,8.690000e+02
V102,590226.0,1.827229e+00,35.928456,0.000000e+00,1.285000e+03
V103,590226.0,1.279288e+00,25.685642,0.000000e+00,9.280000e+02
V104,590226.0,8.543338e-02,0.648718,0.000000e+00,1.500000e+01
V105,590226.0,2.811448e-01,3.373948,0.000000e+00,9.900000e+01
V106,590226.0,1.645844e-01,1.825665,0.000000e+00,5.500000e+01
V107,590226.0,9.995798e-01,0.020494,0.000000e+00,1.000000e+00
V108,590226.0,1.004613e+00,0.081146,0.000000e+00,7.000000e+00
V109,590226.0,1.014816e+00,0.127769,0.000000e+00,7.000000e+00
V110,590226.0,1.007739e+00,0.097290,0.000000e+00,7.000000e+00
V111,590226.0,1.002563e+00,0.070830,0.000000e+00,9.000000e+00
V112,590226.0,1.005356e+00,0.084617,0.000000e+00,9.000000e+00
V113,590226.0,1.003383e+00,0.074754,0.000000e+00,9.000000e+00
V114,590226.0,1.009298e+00,0.110179,0.000000e+00,6.000000e+00
V115,590226.0,1.032450e+00,0.190385,0.000000e+00,6.000000e+00
V116,590226.0,1.015738e+00,0.136770,0.000000e+00,6.000000e+00
V117,590226.0,1.000391e+00,0.035238,0.000000e+00,3.000000e+00
V118,590226.0,1.001474e+00,0.041011,0.000000e+00,3.000000e+00
V119,590226.0,1.000729e+00,0.036392,0.000000e+00,3.000000e+00
V120,590226.0,1.000874e+00,0.041684,0.000000e+00,3.000000e+00
V121,590226.0,1.004276e+00,0.067097,0.000000e+00,3.000000e+00
V122,590226.0,1.001759e+00,0.048636,0.000000e+00,3.000000e+00
V123,590226.0,1.031120e+00,0.228134,0.000000e+00,1.300000e+01
V124,590226.0,1.092975e+00,0.374103,0.000000e+00,1.300000e+01
V125,590226.0,1.050415e+00,0.280037,0.000000e+00,1.300000e+01
V126,590226.0,1.299794e+02,2346.951681,0.000000e+00,1.600000e+05
V127,590226.0,3.366116e+02,4238.666949,0.000000e+00,1.600000e+05
V128,590226.0,2.040940e+02,3010.258774,0.000000e+00,1.600000e+05
V129,590226.0,8.768944e+00,113.832828,0.000000e+00,5.512500e+04
V130,590226.0,9.216585e+01,315.960485,0.000000e+00,5.512500e+04
V131,590226.0,3.113330e+01,161.161258,0.000000e+00,5.512500e+04
V132,590226.0,1.035132e+02,2266.106140,0.000000e+00,9.373600e+04
V133,590226.0,2.048892e+02,3796.316755,0.000000e+00,1.339150e+05
V134,590226.0,1.459723e+02,2772.986817,0.000000e+00,9.847600e+04
V135,590226.0,1.725013e+01,293.847563,0.000000e+00,9.075000e+04
V136,590226.0,3.882120e+01,451.808411,0.000000e+00,9.075000e+04
V137,590226.0,2.636509e+01,348.332714,0.000000e+00,9.075000e+04
V138,81945.0,3.643907e-02,0.428490,0.000000e+00,2.200000e+01
V139,81945.0,1.073915e+00,1.333924,0.000000e+00,3.300000e+01
V140,81945.0,1.125267e+00,1.467850,0.000000e+00,3.300000e+01
V141,81945.0,3.769602e-02,0.215133,0.000000e+00,5.000000e+00
V142,81945.0,4.858137e-02,0.313888,0.000000e+00,9.000000e+00
V143,81951.0,8.397006e+00,55.267545,0.000000e+00,8.690000e+02
V144,81951.0,3.708484e+00,10.485633,0.000000e+00,6.200000e+01
V145,81951.0,2.211295e+01,64.371860,0.000000e+00,2.970000e+02
V146,81945.0,1.562756e-01,0.682328,0.000000e+00,2.400000e+01
V147,81945.0,1.686009e-01,0.750497,0.000000e+00,2.600000e+01
V148,81945.0,7.650009e-01,0.581425,0.000000e+00,2.000000e+01
V149,81945.0,7.753127e-01,0.628191,0.000000e+00,2.000000e+01
V150,81951.0,2.775980e+02,829.576922,1.000000e+00,3.389000e+03
V151,81951.0,6.460190e+00,15.232324,1.000000e+00,5.700000e+01
V152,81951.0,9.432710e+00,21.554486,1.000000e+00,6.900000e+01
V153,81945.0,7.532003e-01,0.532649,0.000000e+00,1.800000e+01
V154,81945.0,7.574227e-01,0.546907,0.000000e+00,1.800000e+01
V155,81945.0,7.673806e-01,0.602678,0.000000e+00,2.400000e+01
V156,81945.0,7.774849e-01,0.647209,0.000000e+00,2.400000e+01
V157,81945.0,8.175728e-01,0.682016,0.000000e+00,2.400000e+01
V158,81945.0,8.334615e-01,0.734336,0.000000e+00,2.400000e+01
V159,81951.0,2.719300e+03,8355.445049,0.000000e+00,5.512500e+04
V160,81951.0,4.745318e+04,142076.069162,0.000000e+00,6.415114e+05
V161,81945.0,4.843938e+00,58.929757,0.000000e+00,3.300000e+03
V162,81945.0,6.594661e+00,69.195180,0.000000e+00,3.300000e+03
V163,81945.0,5.505955e+00,63.077887,0.000000e+00,3.300000e+03
V164,81951.0,8.778889e+02,6049.166505,0.000000e+00,9.373600e+04
V165,81951.0,2.239912e+03,8223.258928,0.000000e+00,9.847600e+04
V166,81951.0,3.594694e+02,1244.463270,0.000000e+00,1.040600e+05
V167,139631.0,3.929514e+00,42.200980,0.000000e+00,8.720000e+02
V168,139631.0,5.859501e+00,54.032468,0.000000e+00,9.640000e+02
V169,139819.0,1.680530e-01,0.904944,0.000000e+00,1.900000e+01
V170,139819.0,1.436779e+00,1.751143,0.000000e+00,4.800000e+01
V171,139819.0,1.690908e+00,2.444748,0.000000e+00,6.100000e+01
V172,139631.0,1.320122e-01,0.924894,0.000000e+00,3.100000e+01
V173,139631.0,5.523129e-02,0.264439,0.000000e+00,7.000000e+00
V174,139819.0,1.277938e-01,0.379763,0.000000e+00,8.000000e+00
V175,139819.0,2.126392e-01,0.857133,0.000000e+00,1.400000e+01
V176,139631.0,1.376979e+00,1.829420,0.000000e+00,4.800000e+01
V177,139631.0,3.529245e+00,41.310622,0.000000e+00,8.610000e+02
V178,139631.0,6.649283e+00,69.447364,0.000000e+00,1.235000e+03
V179,139631.0,4.869012e+00,50.489426,0.000000e+00,9.200000e+02
V180,139819.0,9.241233e-01,6.112630,0.000000e+00,8.300000e+01
V181,139631.0,2.533320e-01,1.248974,0.000000e+00,2.400000e+01
V182,139631.0,8.562425e-01,5.792934,0.000000e+00,8.300000e+01
V183,139631.0,4.846918e-01,2.946982,0.000000e+00,4.100000e+01
V184,139819.0,1.323640e-01,0.543699,0.000000e+00,1.600000e+01
V185,139819.0,1.739034e-01,0.699733,0.000000e+00,3.100000e+01
V186,139631.0,1.148799e+00,1.223529,0.000000e+00,3.800000e+01
V187,139631.0,1.843752e+00,9.884390,0.000000e+00,2.180000e+02
V188,139819.0,1.014755e+00,0.671207,0.000000e+00,3.000000e+01
V189,139819.0,1.038314e+00,0.792528,0.000000e+00,3.000000e+01
V190,139631.0,1.213083e+00,1.480318,0.000000e+00,4.200000e+01
V191,139631.0,1.058984e+00,0.677527,0.000000e+00,2.100000e+01
V192,139631.0,1.237361e+00,2.635961,0.000000e+00,4.400000e+01
V193,139631.0,1.149845e+00,1.714792,0.000000e+00,3.700000e+01
V194,139819.0,9.457727e-01,0.304158,0.000000e+00,7.000000e+00
V195,139819.0,9.542265e-01,0.376420,0.000000e+00,1.600000e+01
V196,139631.0,1.084580e+00,1.105834,0.000000e+00,3.800000e+01
V197,139819.0,9.493846e-01,0.336871,0.000000e+00,1.400000e+01
V198,139819.0,9.619508e-01,0.493065,0.000000e+00,2.100000e+01
V199,139631.0,1.270749e+00,1.671863,0.000000e+00,4.500000e+01
V200,139819.0,1.119977e+00,1.253853,0.000000e+00,4.500000e+01
V201,139819.0,1.159106e+00,1.418618,0.000000e+00,5.500000e+01
V202,139631.0,4.441471e+02,4683.828419,0.000000e+00,1.040600e+05
V203,139631.0,1.078328e+03,9105.607991,0.000000e+00,1.397770e+05
V204,139631.0,6.869569e+02,6048.980716,0.000000e+00,1.040600e+05
V205,139631.0,1.806042e+01,266.545451,0.000000e+00,5.512500e+04
V206,139631.0,6.189360e+00,191.474014,0.000000e+00,5.512500e+04
V207,139631.0,7.228410e+01,925.676660,0.000000e+00,5.512500e+04
V208,139819.0,8.888193e+00,59.047125,0.000000e+00,3.300000e+03
V209,139819.0,3.500187e+01,250.800822,0.000000e+00,8.050000e+03
V210,139819.0,1.439183e+01,86.523724,0.000000e+00,3.300000e+03
V211,139631.0,3.851370e+02,4541.837915,0.000000e+00,9.288800e+04
V212,139631.0,7.659883e+02,7496.120737,0.000000e+00,1.290060e+05
V213,139631.0,5.363028e+02,5471.664736,0.000000e+00,9.762800e+04
V214,139631.0,3.843755e+01,571.834283,0.000000e+00,1.040600e+05
V215,139631.0,1.332082e+02,1040.453748,0.000000e+00,1.040600e+05
V216,139631.0,7.110714e+01,680.267625,0.000000e+00,1.040600e+05
V217,130430.0,1.054619e+00,9.547354,0.000000e+00,3.030000e+02
V218,130430.0,1.725784e+00,13.919876,0.000000e+00,4.000000e+02
V219,130430.0,1.367132e+00,12.044032,0.000000e+00,3.780000e+02
V220,141416.0,1.694716e-01,1.002463,0.000000e+00,2.500000e+01
V221,141416.0,1.274912e+00,2.728792,0.000000e+00,3.840000e+02
V222,141416.0,1.359005e+00,2.913772,0.000000e+00,3.840000e+02
V223,130430.0,9.315342e-02,0.402232,0.000000e+00,1.600000e+01
V224,130430.0,3.947481e-01,3.443310,0.000000e+00,1.440000e+02
V225,130430.0,1.917580e-01,1.290820,0.000000e+00,5.100000e+01
V226,130430.0,2.476117e-01,2.756449,0.000000e+00,2.420000e+02
V227,141416.0,1.479748e-01,2.049363,0.000000e+00,3.600000e+02
V228,130430.0,1.351928e+00,1.409722,0.000000e+00,5.400000e+01
V229,130430.0,1.638710e+00,4.316026,0.000000e+00,1.760000e+02
V230,130430.0,1.465476e+00,2.122783,0.000000e+00,6.500000e+01
V231,130430.0,7.655064e-01,8.877119,0.000000e+00,2.930000e+02
V232,130430.0,1.005597e+00,10.460253,0.000000e+00,3.370000e+02
V233,130430.0,9.083876e-01,10.149884,0.000000e+00,3.320000e+02
V234,141416.0,2.092847e+00,11.323036,0.000000e+00,1.210000e+02
V235,130430.0,1.841064e-01,0.902639,0.000000e+00,2.300000e+01
V236,130430.0,3.076669e-01,2.152332,0.000000e+00,4.500000e+01
V237,130430.0,2.535000e-01,1.716634,0.000000e+00,3.900000e+01
V238,141416.0,1.279558e-01,0.574657,0.000000e+00,2.300000e+01
V239,141416.0,1.369647e-01,0.616260,0.000000e+00,2.300000e+01
V240,130430.0,1.000997e+00,0.049522,0.000000e+00,7.000000e+00
V241,130430.0,1.000238e+00,0.022663,0.000000e+00,5.000000e+00
V242,130430.0,1.113463e+00,0.660110,0.000000e+00,2.000000e+01
V243,130430.0,1.178387e+00,1.398953,0.000000e+00,5.700000e+01
V244,130430.0,1.118562e+00,0.698807,0.000000e+00,2.200000e+01
V245,141416.0,8.766193e-01,1.821065,0.000000e+00,2.620000e+02
V246,130430.0,1.183723e+00,1.040363,0.000000e+00,4.500000e+01
V247,130430.0,1.025355e+00,0.281604,0.000000e+00,1.800000e+01
V248,130430.0,1.069493e+00,0.888341,0.000000e+00,3.600000e+01
V249,130430.0,1.042851e+00,0.528812,0.000000e+00,2.200000e+01
V250,141416.0,7.885883e-01,0.488386,0.000000e+00,1.800000e+01
V251,141416.0,7.942312e-01,0.501240,0.000000e+00,1.800000e+01
V252,130430.0,1.032048e+00,0.389546,0.000000e+00,2.400000e+01
V253,130430.0,1.162164e+00,3.612553,0.000000e+00,1.630000e+02
V254,130430.0,1.075113e+00,1.357550,0.000000e+00,6.000000e+01
V255,141416.0,8.066555e-01,0.939124,0.000000e+00,8.700000e+01
V256,141416.0,8.149502e-01,0.969953,0.000000e+00,8.700000e+01
V257,130430.0,1.250993e+00,1.299956,0.000000e+00,4.800000e+01
V258,130430.0,1.343510e+00,2.015811,0.000000e+00,6.600000e+01
V259,141416.0,9.678325e-01,2.113447,0.000000e+00,2.850000e+02
V260,130430.0,9.644254e-01,0.379828,0.000000e+00,8.000000e+00
V261,130430.0,1.107161e+00,1.323230,0.000000e+00,4.900000e+01
V262,130430.0,1.013279e+00,0.625455,0.000000e+00,2.000000e+01
V263,130430.0,1.173907e+02,1294.851543,0.000000e+00,1.536000e+05
V264,130430.0,2.016576e+02,2284.827492,0.000000e+00,1.536000e+05
V265,130430.0,1.535205e+02,1605.512276,0.000000e+00,1.536000e+05
V266,130430.0,9.167839e+00,208.038863,0.000000e+00,5.512500e+04
V267,130430.0,3.652510e+01,644.878586,0.000000e+00,5.512500e+04
V268,130430.0,1.881341e+01,311.280181,0.000000e+00,5.512500e+04
V269,130430.0,5.997508e+00,207.317539,0.000000e+00,5.512500e+04
V270,141416.0,7.712764e+00,65.507232,0.000000e+00,4.000000e+03
V271,141416.0,9.445133e+00,74.147726,0.000000e+00,4.000000e+03
V272,141416.0,8.464571e+00,69.723735,0.000000e+00,4.000000e+03
V273,130430.0,7.382555e+01,935.187927,0.000000e+00,5.120000e+04
V274,130430.0,1.071516e+02,1258.734139,0.000000e+00,6.600000e+04
V275,130430.0,8.889994e+01,1072.883139,0.000000e+00,5.120000e+04
V276,130430.0,3.179728e+01,615.659714,0.000000e+00,1.040600e+05
V277,130430.0,5.195665e+01,732.145368,0.000000e+00,1.040600e+05
V278,130430.0,4.232823e+01,660.611820,0.000000e+00,1.040600e+05
V279,590528.0,1.123061e+00,21.021950,0.000000e+00,8.800000e+02
V280,590528.0,1.967082e+00,27.851780,0.000000e+00,9.750000e+02
V281,589271.0,8.778304e-02,0.512748,0.000000e+00,2.200000e+01
V282,589271.0,8.171707e-01,0.921880,0.000000e+00,3.200000e+01
V283,589271.0,9.911144e-01,1.558731,0.000000e+00,6.800000e+01
V284,590528.0,8.854280e-02,0.338424,0.000000e+00,1.200000e+01
V285,590528.0,1.167660e+00,3.282454,0.000000e+00,9.500000e+01
V286,590528.0,3.149216e-02,0.190939,0.000000e+00,8.000000e+00
V287,590528.0,3.585791e-01,1.078995,0.000000e+00,3.100000e+01
V288,589271.0,1.843498e-01,0.430989,0.000000e+00,1.000000e+01

In [7]:
# Categorical Feature Statistics
cat_stats

                                       value   count    pct
column           rank
DeviceInfo       1                      <NA>  471874  79.91
                 2                   Windows   47722   8.08
                 3                iOS Device   19782   3.35
                 4                     MacOS   12573   2.13
                 5               Trident/7.0    7440   1.26
DeviceType       1                      <NA>  449730  76.16
                 2                   desktop   85165  14.42
                 3                    mobile   55645   9.42
M1               1                         T  319415  54.09
                 2                      <NA>  271100  45.91
                 3                         F      25   0.00
M2               1                         T  285468  48.34
                 2                      <NA>  271100  45.91
                 3                         F   33972   5.75
M3               1                      <NA>  271100  45.91
                 2                         T  251731  42.63
                 3                         F   67709  11.47
M4               1                      <NA>  281444  47.66
                 2                        M0  196405  33.26
                 3                        M2   59865  10.14
                 4                        M1   52826   8.95
M5               1                      <NA>  350482  59.35
                 2                         F  132491  22.44
                 3                         T  107567  18.22
M6               1                         F  227856  38.58
                 2                         T  193324  32.74
                 3                      <NA>  169360  28.68
M7               1                      <NA>  346265  58.64
                 2                         F  211374  35.79
                 3                         T   32901   5.57
M8               1                      <NA>  346252  58.63
                 2                         F  155251  26.29
                 3                         T   89037  15.08
M9               1                      <NA>  346252  58.63
                 2                         T  205656  34.83
                 3                         F   38632   6.54
P_emaildomain    1                 gmail.com  228355  38.67
                 2                 yahoo.com  100934  17.09
                 3                      <NA>   94456  15.99
                 4               hotmail.com   45250   7.66
                 5             anonymous.com   36998   6.27
ProductCD        1                         W  439670  74.45
                 2                         C   68519  11.60
                 3                         R   37699   6.38
                 4                         H   33024   5.59
                 5                         S   11628   1.97
R_emaildomain    1                      <NA>  453249  76.75
                 2                 gmail.com   57147   9.68
                 3               hotmail.com   27509   4.66
                 4             anonymous.com   20529   3.48
                 5                 yahoo.com   11842   2.01
Transaction_date 1       2018-03-19 15:53:37       8   0.00
                 2       2018-01-19 21:24:26       5   0.00
                 3       2018-04-12 23:49:11       5   0.00
                 4       2018-02-21 18:09:48       5   0.00
                 5       2017-12-23 23:54:56       4   0.00
addr1            1                      <NA>   65706  11.13
                 2                     299.0   46335   7.85
                 3                     325.0   42751   7.24
                 4                     204.0   42020   7.12
                 5                     264.0   39870   6.75
addr2            1                      87.0  520481  88.14
                 2                      <NA>   65706  11.13
                 3                      60.0    3084   0.52
                 4                      96.0     638   0.11
                 5                      32.0      91   0.02
card1            1                      7919   14932   2.53
                 2                      9500   14162   2.40
                 3                     15885   10361   1.75
                 4                     17188   10344   1.75
                 5                     15066    7945   1.35
card2            1                     321.0   48935   8.29
                 2                     111.0   45191   7.65
                 3                     555.0   41995   7.11
                 4                     490.0   38145   6.46
                 5                     583.0   21803   3.69
card3            1                     150.0  521287  88.27
                 2                     185.0   56346   9.54
                 3                     106.0    1571   0.27
                 4                      <NA>    1565   0.27
                 5                     146.0    1252   0.21
card4            1                      visa  384767  65.16
                 2                mastercard  189217  32.04
                 3          american express    8328   1.41
                 4                  discover    6651   1.13
                 5                      <NA>    1577   0.27
card5            1                     226.0  296546  50.22
                 2                     224.0   81513  13.80
                 3                     166.0   57140   9.68
                 4                     102.0   29105   4.93
                 5                     117.0   25941   4.39
card6            1                     debit  439938  74.50
                 2                    credit  148986  25.23
                 3                      <NA>    1571   0.27
                 4           debit or credit      30   0.01
                 5               charge card      15   0.00
id_12            1                      <NA>  446307  75.58
                 2                  NotFound  123025  20.83
                 3                     Found   21208   3.59
id_13            1                      <NA>  463220  78.44
                 2                      52.0   58099   9.84
                 3                      49.0   26365   4.46
                 4                      64.0   14429   2.44
                 5                      33.0   10048   1.70
id_14            1                      <NA>  510496  86.45
                 2                    -300.0   44121   7.47
                 3                    -360.0   16661   2.82
                 4                    -480.0   12891   2.18
                 5                    -420.0    4542   0.77
id_15            1                      <NA>  449555  76.13
                 2                     Found   67728  11.47
                 3                       New   61612  10.43
                 4                   Unknown   11645   1.97
id_16            1                      <NA>  461200  78.10
                 2                     Found   66324  11.23
                 3                  NotFound   63016  10.67
id_17            1                      <NA>  451171  76.40
                 2                     166.0   78631  13.32
                 3                     225.0   56968   9.65
                 4                     102.0     689   0.12
                 5                     159.0     352   0.06
id_18            1                      <NA>  545427  92.36
                 2                      15.0   25489   4.32
                 3                      13.0   13439   2.28
                 4                      12.0    4656   0.79
                 5                      18.0     650   0.11
id_19            1                      <NA>  451222  76.41
                 2                     266.0   19849   3.36
                 3                     410.0   11318   1.92
                 4                     427.0    8808   1.49
                 5                     529.0    8122   1.38
id_20            1                      <NA>  451279  76.42
                 2                     507.0   22311   3.78
                 3                     222.0   11065   1.87
                 4                     325.0    8133   1.38
                 5                     533.0    6611   1.12
id_21            1                      <NA>  585381  99.13
                 2                     252.0    2542   0.43
                 3                     228.0     239   0.04
                 4                     255.0     109   0.02
                 5                     596.0     103   0.02
id_22            1                      <NA>  585371  99.12
                 2                      14.0    4736   0.80
                 3                      41.0     321   0.05
                 4                      33.0      38   0.01
                 5                      21.0       7   0.00
id_23            1                      <NA>  585371  99.12
                 2      IP_PROXY:TRANSPARENT    3489   0.59
                 3        IP_PROXY:ANONYMOUS    1071   0.18
                 4           IP_PROXY:HIDDEN     609   0.10
id_24            1                      <NA>  585793  99.20
                 2                      11.0    2817   0.48
                 3                      15.0    1594   0.27
                 4                      16.0     220   0.04
                 5                      18.0      37   0.01
id_25            1                      <NA>  585408  99.13
                 2                     321.0    2494   0.42
                 3                     205.0     301   0.05
                 4                     426.0     236   0.04
                 5                     501.0     103   0.02
id_26            1                      <NA>  585377  99.13
                 2                     161.0     824   0.14
                 3                     184.0     582   0.10
                 4                     142.0     528   0.09
                 5                     102.0     451   0.08
id_27            1                      <NA>  585371  99.12
                 2                     Found    5155   0.87
                 3                  NotFound      14   0.00
id_28            1                      <NA>  449562  76.13
                 2                     Found   76232  12.91
                 3                       New   64746  10.96
id_29            1                      <NA>  449562  76.13
                 2                     Found   74926  12.69
                 3                  NotFound   66052  11.19
id_30            1                      <NA>  512975  86.87
                 2                Windows 10   21155   3.58
                 3                 Windows 7   13110   2.22
                 4                iOS 11.2.1    3722   0.63
                 5                iOS 11.1.2    3699   0.63
id_31            1                      <NA>  450258  76.25
                 2               chrome 63.0   22000   3.73
                 3        mobile safari 11.0   13423   2.27
                 4     mobile safari generic   11474   1.94
                 5       ie 11.0 for desktop    9030   1.53
id_32            1                      <NA>  512954  86.86
                 2                      24.0   53071   8.99
                 3                      32.0   24428   4.14
                 4                      16.0      81   0.01
                 5                       0.0       6   0.00
id_33            1                      <NA>  517251  87.59
                 2                 1920x1080   16874   2.86
                 3                  1366x768    8605   1.46
                 4                  1334x750    6447   1.09
                 5                 2208x1242    4900   0.83
id_34            1                      <NA>  512735  86.82
                 2            match_status:2   60011  10.16
                 3            match_status:1   17376   2.94
                 4            match_status:0     415   0.07
                 5           match_status:-1       3   0.00
id_35            1                      <NA>  449555  76.13
                 2                         T   77814  13.18
                 3                         F   63171  10.70
id_36            1                      <NA>  449555  76.13
                 2                         F  134066  22.70
                 3                         T    6919   1.17
id_37            1                      <NA>  449555  76.13
                 2                         T  110452  18.70
                 3                         F   30533   5.17
id_38            1                      <NA>  449555  76.13
                 2                         F   73922  12.52
                 3                         T   67063  11.36
isFraud          1                         0  569877  96.50
                 2                         1   20663   3.50
uid              1                      <NA>   92436  15.65
                 2                 3428022.0     943   0.16
                 3                 2987225.0     346   0.06
                 4                 2997296.0     232   0.04
                 5                 3006103.0     215   0.04

In [8]:
# Target Distribution
target_df

          count   pct
isFraud
0        569877  96.5
1         20663   3.5

## Task Curation

In [11]:
from data_foundry.schema import PredictiveMLSplitsMetadata

date_col = task_mold.time_on
target_col = task_mold.target_column_name

months = (df['Transaction_date'].dt.year - 2017) * 12 + df['Transaction_date'].dt.month

# -- For Temporal non-IID data -> manual processing required
splits = {
    0: {
        0: ((months[months<=15]).index.to_list(), (months[months==17]).index.to_list()),
    },
    1: {
        0: ((months[months<=14]).index.to_list(), (months[months==16]).index.to_list()),
    },
    2: {
        0: ((months[months<=13]).index.to_list(), (months[months==15]).index.to_list()),
    },
}

used_in_train = set()
used_in_test = set()
used_data = set()
for split in splits:
    train_idx, test_idx = splits[split][0]
    used_in_train.update(train_idx)
    used_in_test.update(test_idx)
    used_data.update(train_idx)
    used_data.update(test_idx)

    print(f"\n=== Step {split} ===")
    print("Train size:", len(train_idx), "| Test size:", len(test_idx))
    print("Train target mean:", df.loc[train_idx, target_col].astype(int).mean())
    print("Test target mean:", df.loc[test_idx, target_col].astype(int).mean())
    print("% test samples with reoccuring, non-missing uids:", df["uid"].dropna().isin(set(df.loc[test_idx, "uid"]).intersection(set(df.loc[train_idx, "uid"]))).mean())
    print("% test samples with missing uids:", df["uid"].isna().mean())

    assert len(set(train_idx).intersection(set(test_idx)))==0, "Train and test indices overlap!"

print(f"{len(used_data)/df.shape[0]:.4f} of the samples are used.")
print(f"{len(used_in_train)/df.shape[0]:.4f} of the samples are used in training")
print(f"{len(used_in_test)/df.shape[0]:.4f} of the samples are used in testing.")

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="To define three train/test splits, we use the last three months as test sets, leave 1 month as the planning gap, and use the remaining training data.",
    splits=splits,
    # For time data
    time_horizon="1",
    time_horizon_unit="months",
)

=== Step 0 ===
Train size: 417559 | Test size: 89326
Train target mean: 0.03525489811020718
Test target mean: 0.03486107068490697
% test samples with reoccuring, non-missing uids: 0.11205089700142942
% test samples with missing uids: 0.15652792359535342

=== Step 1 ===
Train size: 315927 | Test size: 83655
Train target mean: 0.03387491414155802
Test target mean: 0.03380551072858765
% test samples with reoccuring, non-missing uids: 0.11998699066861539
% test samples with missing uids: 0.15652792359535342

=== Step 2 ===
Train size: 229906 | Test size: 101632
Train target mean: 0.03155637521421799
Test target mean: 0.03954463161209068
% test samples with reoccuring, non-missing uids: 0.12339591731847165
% test samples with missing uids: 0.15652792359535342
1.0000 of the samples are used.
0.7071 of the samples are used in training
0.4650 of the samples are used in testing.

## Export

In [12]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to ieee_fraud_detection/019db516-2f8e-7e50-a8c4-f1c57754f52c
019db516-2f8e-7e50-a8c4-f1c57754f52c
2368c2e67810ef4127ceebe3023d115366be24d5f9ceeb87319774a1a4e6c93d