### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="qsar_tid_11",
    dataset_year="2015",
    domain_str="chemistry & material science",
    # Data Source
    dataset_source="OpenML",
    original_dataset_source_download_link="https://www.openml.org/d/3050",
    download_description="""
We download the dataset from OpenML to a predefined folder.

mkdir -p local-data-warehouse/qsar_tid_11/ && wget -P local-data-warehouse/qsar_tid_11/ https://www.openml.org/data/download/1674848/11.arff
""",
    # References
    academic_reference_bibtex="""@article{Olier2018MetaQSAR,
  title={Meta-QSAR: a large-scale application of meta-learning to drug design and discovery},
  author={Ivan Olier and Noureddin Sadawi and G. Richard Bickerton and Josie Vanschoren and Celine Griner and Luca Soldatova and Ross D. King},
  journal={Machine Learning},
  year={2018},
  volume={107},
  pages={285-311},
  doi={10.1007/s10994-017-5685-x},
  url={https://doi.org/10.1007/s10994-017-5685-x}
}
""",
    academic_reference_bibtex_key="Olier2018MetaQSAR",
    license="Public Domain",
    data_tags=["IID"],
    curation_comments="""
        - We drop the "MOLECULE_CHEMBL_ID" column.
        - We shuffle the data as it has an original distribution shift.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="MEDIAN_PXC50",
    problem_type="regression",
    objective_metric_name="rmse",
)

## Preprocessing

In [2]:
import pandas as pd
import arff


with open(dataset_mold.path/"11.arff") as f:
    data = arff.load(f)

df = pd.DataFrame(data["data"], columns=[x[0] for x in data["attributes"]])
df.drop(columns=["MOLECULE_CHEMBL_ID"], inplace=True)

# Data has an original order-based distribution shift, vanishes after random sampling.
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

# convert to binary type
cat_features = [col for col in df.columns if col != "MEDIAN_PXC50"]
df[cat_features] = df[cat_features].astype("category")

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 5,742
Columns: 1025
Use sampling: False (sample size: 5,742)

/Users/schaefer.bastian/miniconda3/envs/jupyter_env-py3-10/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['FCFP6_1024_513', 'FCFP6_1024_675', 'FCFP6_1024_676', 'FCFP6_1024_677', 'FCFP6_1024_678', 'FCFP6_1024_679', 'FCFP6_1024_680', 'FCFP6_1024_681', 'FCFP6_1024_682', 'FCFP6_1024_683']
Rows remaining as candidates after top-10 filter: 5,723 (of 5,742)

#### Duplicate Report
Total duplicate rows: 116 (2.02% of dataset)
Duplicate rows ignoring target: 483 (8.41% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,FCFP6_1024_0,FCFP6_1024_1,FCFP6_1024_2,FCFP6_1024_3,FCFP6_1024_4,FCFP6_1024_5,FCFP6_1024_6,FCFP6_1024_7,FCFP6_1024_8,FCFP6_1024_9,FCFP6_1024_10,FCFP6_1024_11,FCFP6_1024_12,FCFP6_1024_13,FCFP6_1024_14,FCFP6_1024_15,FCFP6_1024_16,FCFP6_1024_17,FCFP6_1024_18,FCFP6_1024_19,FCFP6_1024_20,FCFP6_1024_21,FCFP6_1024_22,FCFP6_1024_23,FCFP6_1024_24,FCFP6_1024_25,FCFP6_1024_26,FCFP6_1024_27,FCFP6_1024_28,FCFP6_1024_29,FCFP6_1024_30,FCFP6_1024_31,FCFP6_1024_32,FCFP6_1024_33,FCFP6_1024_34,FCFP6_1024_35,FCFP6_1024_36,FCFP6_1024_37,FCFP6_1024_38,FCFP6_1024_39,FCFP6_1024_40,FCFP6_1024_41,FCFP6_1024_42,FCFP6_1024_43,FCFP6_1024_44,FCFP6_1024_45,FCFP6_1024_46,FCFP6_1024_47,FCFP6_1024_48,FCFP6_1024_49,FCFP6_1024_50,FCFP6_1024_51,FCFP6_1024_52,FCFP6_1024_53,FCFP6_1024_54,FCFP6_1024_55,FCFP6_1024_56,FCFP6_1024_57,FCFP6_1024_58,FCFP6_1024_59,FCFP6_1024_60,FCFP6_1024_61,FCFP6_1024_62,FCFP6_1024_63,FCFP6_1024_64,FCFP6_1024_65,FCFP6_1024_66,FCFP6_1024_67,FCFP6_1024_68,FCFP6_1024_69,FCFP6_1024_70,FCFP6_1024_71,FCFP6_1024_72,FCFP6_1024_73,FCFP6_1024_74,FCFP6_1024_75,FCFP6_1024_76,FCFP6_1024_77,FCFP6_1024_78,FCFP6_1024_79,FCFP6_1024_80,FCFP6_1024_81,FCFP6_1024_82,FCFP6_1024_83,FCFP6_1024_84,FCFP6_1024_85,FCFP6_1024_86,FCFP6_1024_87,FCFP6_1024_88,FCFP6_1024_89,FCFP6_1024_90,FCFP6_1024_91,FCFP6_1024_92,FCFP6_1024_93,FCFP6_1024_94,FCFP6_1024_95,FCFP6_1024_96,FCFP6_1024_97,FCFP6_1024_98,FCFP6_1024_99,FCFP6_1024_100,FCFP6_1024_101,FCFP6_1024_102,FCFP6_1024_103,FCFP6_1024_104,FCFP6_1024_105,FCFP6_1024_106,FCFP6_1024_107,FCFP6_1024_108,FCFP6_1024_109,FCFP6_1024_110,FCFP6_1024_111,FCFP6_1024_112,FCFP6_1024_113,FCFP6_1024_114,FCFP6_1024_115,FCFP6_1024_116,FCFP6_1024_117,FCFP6_1024_118,FCFP6_1024_119,FCFP6_1024_120,FCFP6_1024_121,FCFP6_1024_122,FCFP6_1024_123,FCFP6_1024_124,FCFP6_1024_125,FCFP6_1024_126,FCFP6_1024_127,FCFP6_1024_128,FCFP6_1024_129,FCFP6_1024_130,FCFP6_1024_131,FCFP6_1024_132,FCFP6_1024_133,FCFP6_1024_134,FCFP6_1024_135,FCFP6_1024_136,FCFP6_1024_137,FCFP6_1024_138,FCFP6_1024_139,FCFP6_1024_140,FCFP6_1024_141,FCFP6_1024_142,FCFP6_1024_143,FCFP6_1024_144,FCFP6_1024_145,FCFP6_1024_146,FCFP6_1024_147,FCFP6_1024_148,FCFP6_1024_149,FCFP6_1024_150,FCFP6_1024_151,FCFP6_1024_152,FCFP6_1024_153,FCFP6_1024_154,FCFP6_1024_155,FCFP6_1024_156,FCFP6_1024_157,FCFP6_1024_158,FCFP6_1024_159,FCFP6_1024_160,FCFP6_1024_161,FCFP6_1024_162,FCFP6_1024_163,FCFP6_1024_164,FCFP6_1024_165,FCFP6_1024_166,FCFP6_1024_167,FCFP6_1024_168,FCFP6_1024_169,FCFP6_1024_170,FCFP6_1024_171,FCFP6_1024_172,FCFP6_1024_173,FCFP6_1024_174,FCFP6_1024_175,FCFP6_1024_176,FCFP6_1024_177,FCFP6_1024_178,FCFP6_1024_179,FCFP6_1024_180,FCFP6_1024_181,FCFP6_1024_182,FCFP6_1024_183,FCFP6_1024_184,FCFP6_1024_185,FCFP6_1024_186,FCFP6_1024_187,FCFP6_1024_188,FCFP6_1024_189,FCFP6_1024_190,FCFP6_1024_191,FCFP6_1024_192,FCFP6_1024_193,FCFP6_1024_194,FCFP6_1024_195,FCFP6_1024_196,FCFP6_1024_197,FCFP6_1024_198,FCFP6_1024_199,FCFP6_1024_200,FCFP6_1024_201,FCFP6_1024_202,FCFP6_1024_203,FCFP6_1024_204,FCFP6_1024_205,FCFP6_1024_206,FCFP6_1024_207,FCFP6_1024_208,FCFP6_1024_209,FCFP6_1024_210,FCFP6_1024_211,FCFP6_1024_212,FCFP6_1024_213,FCFP6_1024_214,FCFP6_1024_215,FCFP6_1024_216,FCFP6_1024_217,FCFP6_1024_218,FCFP6_1024_219,FCFP6_1024_220,FCFP6_1024_221,FCFP6_1024_222,FCFP6_1024_223,FCFP6_1024_224,FCFP6_1024_225,FCFP6_1024_226,FCFP6_1024_227,FCFP6_1024_228,FCFP6_1024_229,FCFP6_1024_230,FCFP6_1024_231,FCFP6_1024_232,FCFP6_1024_233,FCFP6_1024_234,FCFP6_1024_235,FCFP6_1024_236,FCFP6_1024_237,FCFP6_1024_238,FCFP6_1024_239,FCFP6_1024_240,FCFP6_1024_241,FCFP6_1024_242,FCFP6_1024_243,FCFP6_1024_244,FCFP6_1024_245,FCFP6_1024_246,FCFP6_1024_247,FCFP6_1024_248,FCFP6_1024_249,FCFP6_1024_250,FCFP6_1024_251,FCFP6_1024_252,FCFP6_1024_253,FCFP6_1024_254,FCFP6_1024_255,FCFP6_1024_256,FCFP6_1024_257,FCFP6_1024_258,FCFP6_1024_259,FCFP6_1024_260,FCFP6_1024_261,FCFP6_1024_262,FCFP6_1024_263,FCFP6_1024_264,FCFP6_1024_265,FCFP6_1024_266,FCFP6_1024_267,FCFP6_1024_268,FCFP6_1024_269,FCFP6_1024_270,FCFP6_1024_271,FCFP6_1024_272,FCFP6_1024_273,FCFP6_1024_274,FCFP6_1024_275,FCFP6_1024_276,FCFP6_1024_277,FCFP6_1024_278,FCFP6_1024_279,FCFP6_1024_280,FCFP6_1024_281,FCFP6_1024_282,FCFP6_1024_283,FCFP6_1024_284,FCFP6_1024_285,FCFP6_1024_286,FCFP6_1024_287,FCFP6_1024_288,FCFP6_1024_289,FCFP6_1024_290,FCFP6_1024_291,FCFP6_1024_292,FCFP6_1024_293,FCFP6_1024_294,FCFP6_1024_295,FCFP6_1024_296,FCFP6_1024_297,FCFP6_1024_298,FCFP6_1024_299,FCFP6_1024_300,FCFP6_1024_301,FCFP6_1024_302,FCFP6_1024_303,FCFP6_1024_304,FCFP6_1024_305,FCFP6_1024_306,FCFP6_1024_307,FCFP6_1024_308,FCFP6_1024_309,FCFP6_1024_310,FCFP6_1024_311,FCFP6_1024_312,FCFP6_1024_313,FCFP6_1024_314,FCFP6_1024_315,FCFP6_1024_316,FCFP6_1024_317,FCFP6_1024_318,FCFP6_1024_319,FCFP6_1024_320,FCFP6_1024_321,FCFP6_1024_322,FCFP6_1024_323,FCFP6_1024_324,FCFP6_1024_325,FCFP6_1024_326,FCFP6_1024_327,FCFP6_1024_328,FCFP6_1024_329,FCFP6_1024_330,FCFP6_1024_331,FCFP6_1024_332,FCFP6_1024_333,FCFP6_1024_334,FCFP6_1024_335,FCFP6_1024_336,FCFP6_1024_337,FCFP6_1024_338,FCFP6_1024_339,FCFP6_1024_340,FCFP6_1024_341,FCFP6_1024_342,FCFP6_1024_343,FCFP6_1024_344,FCFP6_1024_345,FCFP6_1024_346,FCFP6_1024_347,FCFP6_1024_348,FCFP6_1024_349,FCFP6_1024_350,FCFP6_1024_351,FCFP6_1024_352,FCFP6_1024_353,FCFP6_1024_354,FCFP6_1024_355,FCFP6_1024_356,FCFP6_1024_357,FCFP6_1024_358,FCFP6_1024_359,FCFP6_1024_360,FCFP6_1024_361,FCFP6_1024_362,FCFP6_1024_363,FCFP6_1024_364,FCFP6_1024_365,FCFP6_1024_366,FCFP6_1024_367,FCFP6_1024_368,FCFP6_1024_369,FCFP6_1024_370,FCFP6_1024_371,FCFP6_1024_372,FCFP6_1024_373,FCFP6_1024_374,FCFP6_1024_375,FCFP6_1024_376,FCFP6_1024_377,FCFP6_1024_378,FCFP6_1024_379,FCFP6_1024_380,FCFP6_1024_381,FCFP6_1024_382,FCFP6_1024_383,FCFP6_1024_384,FCFP6_1024_385,FCFP6_1024_386,FCFP6_1024_387,FCFP6_1024_388,FCFP6_1024_389,FCFP6_1024_390,FCFP6_1024_391,FCFP6_1024_392,FCFP6_1024_393,FCFP6_1024_394,FCFP6_1024_395,FCFP6_1024_396,FCFP6_1024_397,FCFP6_1024_398,FCFP6_1024_399,FCFP6_1024_400,FCFP6_1024_401,FCFP6_1024_402,FCFP6_1024_403,FCFP6_1024_404,FCFP6_1024_405,FCFP6_1024_406,FCFP6_1024_407,FCFP6_1024_408,FCFP6_1024_409,FCFP6_1024_410,FCFP6_1024_411,FCFP6_1024_412,FCFP6_1024_413,FCFP6_1024_414,FCFP6_1024_415,FCFP6_1024_416,FCFP6_1024_417,FCFP6_1024_418,FCFP6_1024_419,FCFP6_1024_420,FCFP6_1024_421,FCFP6_1024_422,FCFP6_1024_423,FCFP6_1024_424,FCFP6_1024_425,FCFP6_1024_426,FCFP6_1024_427,FCFP6_1024_428,FCFP6_1024_429,FCFP6_1024_430,FCFP6_1024_431,FCFP6_1024_432,FCFP6_1024_433,FCFP6_1024_434,FCFP6_1024_435,FCFP6_1024_436,FCFP6_1024_437,FCFP6_1024_438,FCFP6_1024_439,FCFP6_1024_440,FCFP6_1024_441,FCFP6_1024_442,FCFP6_1024_443,FCFP6_1024_444,FCFP6_1024_445,FCFP6_1024_446,FCFP6_1024_447,FCFP6_1024_448,FCFP6_1024_449,FCFP6_1024_450,FCFP6_1024_451,FCFP6_1024_452,FCFP6_1024_453,FCFP6_1024_454,FCFP6_1024_455,FCFP6_1024_456,FCFP6_1024_457,FCFP6_1024_458,FCFP6_1024_459,FCFP6_1024_460,FCFP6_1024_461,FCFP6_1024_462,FCFP6_1024_463,FCFP6_1024_464,FCFP6_1024_465,FCFP6_1024_466,FCFP6_1024_467,FCFP6_1024_468,FCFP6_1024_469,FCFP6_1024_470,FCFP6_1024_471,FCFP6_1024_472,FCFP6_1024_473,FCFP6_1024_474,FCFP6_1024_475,FCFP6_1024_476,FCFP6_1024_477,FCFP6_1024_478,FCFP6_1024_479,FCFP6_1024_480,FCFP6_1024_481,FCFP6_1024_482,FCFP6_1024_483,FCFP6_1024_484,FCFP6_1024_485,FCFP6_1024_486,FCFP6_1024_487,FCFP6_1024_488,FCFP6_1024_489,FCFP6_1024_490,FCFP6_1024_491,FCFP6_1024_492,FCFP6_1024_493,FCFP6_1024_494,FCFP6_1024_495,FCFP6_1024_496,FCFP6_1024_497,FCFP6_1024_498,FCFP6_1024_499,FCFP6_1024_500,FCFP6_1024_501,FCFP6_1024_502,FCFP6_1024_503,FCFP6_1024_504,FCFP6_1024_505,FCFP6_1024_506,FCFP6_1024_507,FCFP6_1024_508,FCFP6_1024_509,FCFP6_1024_510,FCFP6_1024_511,FCFP6_1024_512,FCFP6_1024_513,FCFP6_1024_514,FCFP6_1024_515,FCFP6_1024_516,FCFP6_1024_517,FCFP6_1024_518,FCFP6_1024_519,FCFP6_1024_520,FCFP6_1024_521,FCFP6_1024_522,FCFP6_1024_523,FCFP6_1024_524,FCFP6_1024_525,FCFP6_1024_526,FCFP6_1024_527,FCFP6_1024_528,FCFP6_1024_529,FCFP6_1024_530,FCFP6_1024_531,FCFP6_1024_532,FCFP6_1024_533,FCFP6_1024_534,FCFP6_1024_535,FCFP6_1024_536,FCFP6_1024_537,FCFP6_1024_538,FCFP6_1024_539,FCFP6_1024_540,FCFP6_1024_541,FCFP6_1024_542,FCFP6_1024_543,FCFP6_1024_544,FCFP6_1024_545,FCFP6_1024_546,FCFP6_1024_547,FCFP6_1024_548,FCFP6_1024_549,FCFP6_1024_550,FCFP6_1024_551,FCFP6_1024_552,FCFP6_1024_553,FCFP6_1024_554,FCFP6_1024_555,FCFP6_1024_556,FCFP6_1024_557,FCFP6_1024_558,FCFP6_1024_559,FCFP6_1024_560,FCFP6_1024_561,FCFP6_1024_562,FCFP6_1024_563,FCFP6_1024_564,FCFP6_1024_565,FCFP6_1024_566,FCFP6_1024_567,FCFP6_1024_568,FCFP6_1024_569,FCFP6_1024_570,FCFP6_1024_571,FCFP6_1024_572,FCFP6_1024_573,FCFP6_1024_574,FCFP6_1024_575,FCFP6_1024_576,FCFP6_1024_577,FCFP6_1024_578,FCFP6_1024_579,FCFP6_1024_580,FCFP6_1024_581,FCFP6_1024_582,FCFP6_1024_583,FCFP6_1024_584,FCFP6_1024_585,FCFP6_1024_586,FCFP6_1024_587,FCFP6_1024_588,FCFP6_1024_589,FCFP6_1024_590,FCFP6_1024_591,FCFP6_1024_592,FCFP6_1024_593,FCFP6_1024_594,FCFP6_1024_595,FCFP6_1024_596,FCFP6_1024_597,FCFP6_1024_598,FCFP6_1024_599,FCFP6_1024_600,FCFP6_1024_601,FCFP6_1024_602,FCFP6_1024_603,FCFP6_1024_604,FCFP6_1024_605,FCFP6_1024_606,FCFP6_1024_607,FCFP6_1024_608,FCFP6_1024_609,FCFP6_1024_610,FCFP6_1024_611,FCFP6_1024_612,FCFP6_1024_613,FCFP6_1024_614,FCFP6_1024_615,FCFP6_1024_616,FCFP6_1024_617,FCFP6_1024_618,FCFP6_1024_619,FCFP6_1024_620,FCFP6_1024_621,FCFP6_1024_622,FCFP6_1024_623,FCFP6_1024_624,FCFP6_1024_625,FCFP6_1024_626,FCFP6_1024_627,FCFP6_1024_628,FCFP6_1024_629,FCFP6_1024_630,FCFP6_1024_631,FCFP6_1024_632,FCFP6_1024_633,FCFP6_1024_634,FCFP6_1024_635,FCFP6_1024_636,FCFP6_1024_637,FCFP6_1024_638,FCFP6_1024_639,FCFP6_1024_640,FCFP6_1024_641,FCFP6_1024_642,FCFP6_1024_643,FCFP6_1024_644,FCFP6_1024_645,FCFP6_1024_646,FCFP6_1024_647,FCFP6_1024_648,FCFP6_1024_649,FCFP6_1024_650,FCFP6_1024_651,FCFP6_1024_652,FCFP6_1024_653,FCFP6_1024_654,FCFP6_1024_655,FCFP6_1024_656,FCFP6_1024_657,FCFP6_1024_658,FCFP6_1024_659,FCFP6_1024_660,FCFP6_1024_661,FCFP6_1024_662,FCFP6_1024_663,FCFP6_1024_664,FCFP6_1024_665,FCFP6_1024_666,FCFP6_1024_667,FCFP6_1024_668,FCFP6_1024_669,FCFP6_1024_670,FCFP6_1024_671,FCFP6_1024_672,FCFP6_1024_673,FCFP6_1024_674,FCFP6_1024_675,FCFP6_1024_676,FCFP6_1024_677,FCFP6_1024_678,FCFP6_1024_679,FCFP6_1024_680,FCFP6_1024_681,FCFP6_1024_682,FCFP6_1024_683,FCFP6_1024_684,FCFP6_1024_685,FCFP6_1024_686,FCFP6_1024_687,FCFP6_1024_688,FCFP6_1024_689,FCFP6_1024_690,FCFP6_1024_691,FCFP6_1024_692,FCFP6_1024_693,FCFP6_1024_694,FCFP6_1024_695,FCFP6_1024_696,FCFP6_1024_697,FCFP6_1024_698,FCFP6_1024_699,FCFP6_1024_700,FCFP6_1024_701,FCFP6_1024_702,FCFP6_1024_703,FCFP6_1024_704,FCFP6_1024_705,FCFP6_1024_706,FCFP6_1024_707,FCFP6_1024_708,FCFP6_1024_709,FCFP6_1024_710,FCFP6_1024_711,FCFP6_1024_712,FCFP6_1024_713,FCFP6_1024_714,FCFP6_1024_715,FCFP6_1024_716,FCFP6_1024_717,FCFP6_1024_718,FCFP6_1024_719,FCFP6_1024_720,FCFP6_1024_721,FCFP6_1024_722,FCFP6_1024_723,FCFP6_1024_724,FCFP6_1024_725,FCFP6_1024_726,FCFP6_1024_727,FCFP6_1024_728,FCFP6_1024_729,FCFP6_1024_730,FCFP6_1024_731,FCFP6_1024_732,FCFP6_1024_733,FCFP6_1024_734,FCFP6_1024_735,FCFP6_1024_736,FCFP6_1024_737,FCFP6_1024_738,FCFP6_1024_739,FCFP6_1024_740,FCFP6_1024_741,FCFP6_1024_742,FCFP6_1024_743,FCFP6_1024_744,FCFP6_1024_745,FCFP6_1024_746,FCFP6_1024_747,FCFP6_1024_748,FCFP6_1024_749,FCFP6_1024_750,FCFP6_1024_751,FCFP6_1024_752,FCFP6_1024_753,FCFP6_1024_754,FCFP6_1024_755,FCFP6_1024_756,FCFP6_1024_757,FCFP6_1024_758,FCFP6_1024_759,FCFP6_1024_760,FCFP6_1024_761,FCFP6_1024_762,FCFP6_1024_763,FCFP6_1024_764,FCFP6_1024_765,FCFP6_1024_766,FCFP6_1024_767,FCFP6_1024_768,FCFP6_1024_769,FCFP6_1024_770,FCFP6_1024_771,FCFP6_1024_772,FCFP6_1024_773,FCFP6_1024_774,FCFP6_1024_775,FCFP6_1024_776,FCFP6_1024_777,FCFP6_1024_778,FCFP6_1024_779,FCFP6_1024_780,FCFP6_1024_781,FCFP6_1024_782,FCFP6_1024_783,FCFP6_1024_784,FCFP6_1024_785,FCFP6_1024_786,FCFP6_1024_787,FCFP6_1024_788,FCFP6_1024_789,FCFP6_1024_790,FCFP6_1024_791,FCFP6_1024_792,FCFP6_1024_793,FCFP6_1024_794,FCFP6_1024_795,FCFP6_1024_796,FCFP6_1024_797,FCFP6_1024_798,FCFP6_1024_799,FCFP6_1024_800,FCFP6_1024_801,FCFP6_1024_802,FCFP6_1024_803,FCFP6_1024_804,FCFP6_1024_805,FCFP6_1024_806,FCFP6_1024_807,FCFP6_1024_808,FCFP6_1024_809,FCFP6_1024_810,FCFP6_1024_811,FCFP6_1024_812,FCFP6_1024_813,FCFP6_1024_814,FCFP6_1024_815,FCFP6_1024_816,FCFP6_1024_817,FCFP6_1024_818,FCFP6_1024_819,FCFP6_1024_820,FCFP6_1024_821,FCFP6_1024_822,FCFP6_1024_823,FCFP6_1024_824,FCFP6_1024_825,FCFP6_1024_826,FCFP6_1024_827,FCFP6_1024_828,FCFP6_1024_829,FCFP6_1024_830,FCFP6_1024_831,FCFP6_1024_832,FCFP6_1024_833,FCFP6_1024_834,FCFP6_1024_835,FCFP6_1024_836,FCFP6_1024_837,FCFP6_1024_838,FCFP6_1024_839,FCFP6_1024_840,FCFP6_1024_841,FCFP6_1024_842,FCFP6_1024_843,FCFP6_1024_844,FCFP6_1024_845,FCFP6_1024_846,FCFP6_1024_847,FCFP6_1024_848,FCFP6_1024_849,FCFP6_1024_850,FCFP6_1024_851,FCFP6_1024_852,FCFP6_1024_853,FCFP6_1024_854,FCFP6_1024_855,FCFP6_1024_856,FCFP6_1024_857,FCFP6_1024_858,FCFP6_1024_859,FCFP6_1024_860,FCFP6_1024_861,FCFP6_1024_862,FCFP6_1024_863,FCFP6_1024_864,FCFP6_1024_865,FCFP6_1024_866,FCFP6_1024_867,FCFP6_1024_868,FCFP6_1024_869,FCFP6_1024_870,FCFP6_1024_871,FCFP6_1024_872,FCFP6_1024_873,FCFP6_1024_874,FCFP6_1024_875,FCFP6_1024_876,FCFP6_1024_877,FCFP6_1024_878,FCFP6_1024_879,FCFP6_1024_880,FCFP6_1024_881,FCFP6_1024_882,FCFP6_1024_883,FCFP6_1024_884,FCFP6_1024_885,FCFP6_1024_886,FCFP6_1024_887,FCFP6_1024_888,FCFP6_1024_889,FCFP6_1024_890,FCFP6_1024_891,FCFP6_1024_892,FCFP6_1024_893,FCFP6_1024_894,FCFP6_1024_895,FCFP6_1024_896,FCFP6_1024_897,FCFP6_1024_898,FCFP6_1024_899,FCFP6_1024_900,FCFP6_1024_901,FCFP6_1024_902,FCFP6_1024_903,FCFP6_1024_904,FCFP6_1024_905,FCFP6_1024_906,FCFP6_1024_907,FCFP6_1024_908,FCFP6_1024_909,FCFP6_1024_910,FCFP6_1024_911,FCFP6_1024_912,FCFP6_1024_913,FCFP6_1024_914,FCFP6_1024_915,FCFP6_1024_916,FCFP6_1024_917,FCFP6_1024_918,FCFP6_1024_919,FCFP6_1024_920,FCFP6_1024_921,FCFP6_1024_922,FCFP6_1024_923,FCFP6_1024_924,FCFP6_1024_925,FCFP6_1024_926,FCFP6_1024_927,FCFP6_1024_928,FCFP6_1024_929,FCFP6_1024_930,FCFP6_1024_931,FCFP6_1024_932,FCFP6_1024_933,FCFP6_1024_934,FCFP6_1024_935,FCFP6_1024_936,FCFP6_1024_937,FCFP6_1024_938,FCFP6_1024_939,FCFP6_1024_940,FCFP6_1024_941,FCFP6_1024_942,FCFP6_1024_943,FCFP6_1024_944,FCFP6_1024_945,FCFP6_1024_946,FCFP6_1024_947,FCFP6_1024_948,FCFP6_1024_949,FCFP6_1024_950,FCFP6_1024_951,FCFP6_1024_952,FCFP6_1024_953,FCFP6_1024_954,FCFP6_1024_955,FCFP6_1024_956,FCFP6_1024_957,FCFP6_1024_958,FCFP6_1024_959,FCFP6_1024_960,FCFP6_1024_961,FCFP6_1024_962,FCFP6_1024_963,FCFP6_1024_964,FCFP6_1024_965,FCFP6_1024_966,FCFP6_1024_967,FCFP6_1024_968,FCFP6_1024_969,FCFP6_1024_970,FCFP6_1024_971,FCFP6_1024_972,FCFP6_1024_973,FCFP6_1024_974,FCFP6_1024_975,FCFP6_1024_976,FCFP6_1024_977,FCFP6_1024_978,FCFP6_1024_979,FCFP6_1024_980,FCFP6_1024_981,FCFP6_1024_982,FCFP6_1024_983,FCFP6_1024_984,FCFP6_1024_985,FCFP6_1024_986,FCFP6_1024_987,FCFP6_1024_988,FCFP6_1024_989,FCFP6_1024_990,FCFP6_1024_991,FCFP6_1024_992,FCFP6_1024_993,FCFP6_1024_994,FCFP6_1024_995,FCFP6_1024_996,FCFP6_1024_997,FCFP6_1024_998,FCFP6_1024_999,FCFP6_1024_1000,FCFP6_1024_1001,FCFP6_1024_1002,FCFP6_1024_1003,FCFP6_1024_1004,FCFP6_1024_1005,FCFP6_1024_1006,FCFP6_1024_1007,FCFP6_1024_1008,FCFP6_1024_1009,FCFP6_1024_1010,FCFP6_1024_1011,FCFP6_1024_1012,FCFP6_1024_1013,FCFP6_1024_1014,FCFP6_1024_1015,FCFP6_1024_1016,FCFP6_1024_1017,FCFP6_1024_1018,FCFP6_1024_1019,FCFP6_1024_1020,FCFP6_1024_1021,FCFP6_1024_1022,FCFP6_1024_1023,MEDIAN_PXC50
0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.721

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,FCFP6_1024_0,category,0.0,0.0,2.0,"1.0, 0.0"
1,FCFP6_1024_1,category,0.0,0.0,2.0,"1.0, 0.0"
2,FCFP6_1024_2,category,0.0,0.0,2.0,"0.0, 1.0"
3,FCFP6_1024_3,category,0.0,0.0,2.0,"1.0, 0.0"
4,FCFP6_1024_4,category,0.0,0.0,2.0,"0.0, 1.0"
5,FCFP6_1024_5,category,0.0,0.0,2.0,"0.0, 1.0"
6,FCFP6_1024_6,category,0.0,0.0,2.0,"0.0, 1.0"
7,FCFP6_1024_7,category,0.0,0.0,2.0,"0.0, 1.0"
8,FCFP6_1024_8,category,0.0,0.0,2.0,"0.0, 1.0"
9,FCFP6_1024_9,category,0.0,0.0,2.0,"0.0, 1.0"
10,FCFP6_1024_10,category,0.0,0.0,2.0,"0.0, 1.0"
11,FCFP6_1024_11,category,0.0,0.0,2.0,"0.0, 1.0"
12,FCFP6_1024_12,category,0.0,0.0,2.0,"0.0, 1.0"
13,FCFP6_1024_13,category,0.0,0.0,2.0,"0.0, 1.0"
14,FCFP6_1024_14,category,0.0,0.0,2.0,"0.0, 1.0"
15,FCFP6_1024_15,category,0.0,0.0,2.0,"0.0, 1.0"
16,FCFP6_1024_16,category,0.0,0.0,2.0,"1.0, 0.0"
17,FCFP6_1024_17,category,0.0,0.0,2.0,"1.0, 0.0"
18,FCFP6_1024_18,category,0.0,0.0,2.0,"0.0, 1.0"
19,FCFP6_1024_19,category,0.0,0.0,2.0,"0.0, 1.0"
20,FCFP6_1024_20,category,0.0,0.0,2.0,"0.0, 1.0"
21,FCFP6_1024_21,category,0.0,0.0,2.0,"0.0, 1.0"
22,FCFP6_1024_22,category,0.0,0.0,2.0,"0.0, 1.0"
23,FCFP6_1024_23,category,0.0,0.0,2.0,"0.0, 1.0"
24,FCFP6_1024_24,category,0.0,0.0,2.0,"1.0, 0.0"
25,FCFP6_1024_25,category,0.0,0.0,2.0,"0.0, 1.0"
26,FCFP6_1024_26,category,0.0,0.0,2.0,"0.0, 1.0"
27,FCFP6_1024_27,category,0.0,0.0,2.0,"0.0, 1.0"
28,FCFP6_1024_28,category,0.0,0.0,2.0,"0.0, 1.0"
29,FCFP6_1024_29,category,0.0,0.0,2.0,"0.0, 1.0"
30,FCFP6_1024_30,category,0.0,0.0,2.0,"0.0, 1.0"
31,FCFP6_1024_31,category,0.0,0.0,2.0,"0.0, 1.0"
32,FCFP6_1024_32,category,0.0,0.0,2.0,"0.0, 1.0"
33,FCFP6_1024_33,category,0.0,0.0,2.0,"0.0, 1.0"
34,FCFP6_1024_34,category,0.0,0.0,2.0,"0.0, 1.0"
35,FCFP6_1024_35,category,0.0,0.0,2.0,"0.0, 1.0"
36,FCFP6_1024_36,category,0.0,0.0,2.0,"0.0, 1.0"
37,FCFP6_1024_37,category,0.0,0.0,2.0,"0.0, 1.0"
38,FCFP6_1024_38,category,0.0,0.0,2.0,"0.0, 1.0"
39,FCFP6_1024_39,category,0.0,0.0,2.0,"0.0, 1.0"
40,FCFP6_1024_40,category,0.0,0.0,2.0,"0.0, 1.0"
41,FCFP6_1024_41,category,0.0,0.0,2.0,"0.0, 1.0"
42,FCFP6_1024_42,category,0.0,0.0,2.0,"0.0, 1.0"
43,FCFP6_1024_43,category,0.0,0.0,2.0,"0.0, 1.0"
44,FCFP6_1024_44,category,0.0,0.0,2.0,"0.0, 1.0"
45,FCFP6_1024_45,category,0.0,0.0,2.0,"0.0, 1.0"
46,FCFP6_1024_46,category,0.0,0.0,2.0,"0.0, 1.0"
47,FCFP6_1024_47,category,0.0,0.0,2.0,"0.0, 1.0"
48,FCFP6_1024_48,category,0.0,0.0,2.0,"0.0, 1.0"
49,FCFP6_1024_49,category,0.0,0.0,2.0,"0.0, 1.0"
50,FCFP6_1024_50,category,0.0,0.0,2.0,"0.0, 1.0"
51,FCFP6_1024_51,category,0.0,0.0,2.0,"0.0, 1.0"
52,FCFP6_1024_52,category,0.0,0.0,2.0,"0.0, 1.0"
53,FCFP6_1024_53,category,0.0,0.0,2.0,"0.0, 1.0"
54,FCFP6_1024_54,category,0.0,0.0,2.0,"0.0, 1.0"
55,FCFP6_1024_55,category,0.0,0.0,2.0,"0.0, 1.0"
56,FCFP6_1024_56,category,0.0,0.0,2.0,"0.0, 1.0"
57,FCFP6_1024_57,category,0.0,0.0,2.0,"0.0, 1.0"
58,FCFP6_1024_58,category,0.0,0.0,2.0,"0.0, 1.0"
59,FCFP6_1024_59,category,0.0,0.0,2.0,"0.0, 1.0"
60,FCFP6_1024_60,category,0.0,0.0,2.0,"0.0, 1.0"
61,FCFP6_1024_61,category,0.0,0.0,2.0,"0.0, 1.0"
62,FCFP6_1024_62,category,0.0,0.0,2.0,"0.0, 1.0"
63,FCFP6_1024_63,category,0.0,0.0,2.0,"0.0, 1.0"
64,FCFP6_1024_64,category,0.0,0.0,2.0,"0.0, 1.0"
65,FCFP6_1024_65,category,0.0,0.0,2.0,"0.0, 1.0"
66,FCFP6_1024_66,category,0.0,0.0,2.0,"0.0, 1.0"
67,FCFP6_1024_67,category,0.0,0.0,2.0,"0.0, 1.0"
68,FCFP6_1024_68,category,0.0,0.0,2.0,"0.0, 1.0"
69,FCFP6_1024_69,category,0.0,0.0,2.0,"0.0, 1.0"
70,FCFP6_1024_70,category,0.0,0.0,2.0,"0.0, 1.0"
71,FCFP6_1024_71,category,0.0,0.0,2.0,"0.0, 1.0"
72,FCFP6_1024_72,category,0.0,0.0,2.0,"0.0, 1.0"
73,FCFP6_1024_73,category,0.0,0.0,2.0,"0.0, 1.0"
74,FCFP6_1024_74,category,0.0,0.0,2.0,"0.0, 1.0"
75,FCFP6_1024_75,category,0.0,0.0,2.0,"0.0, 1.0"
76,FCFP6_1024_76,category,0.0,0.0,2.0,"0.0, 1.0"
77,FCFP6_1024_77,category,0.0,0.0,2.0,"0.0, 1.0"
78,FCFP6_1024_78,category,0.0,0.0,2.0,"0.0, 1.0"
79,FCFP6_1024_79,category,0.0,0.0,2.0,"0.0, 1.0"
80,FCFP6_1024_80,category,0.0,0.0,2.0,"0.0, 1.0"
81,FCFP6_1024_81,category,0.0,0.0,2.0,"0.0, 1.0"
82,FCFP6_1024_82,category,0.0,0.0,2.0,"0.0, 1.0"
83,FCFP6_1024_83,category,0.0,0.0,2.0,"0.0, 1.0"
84,FCFP6_1024_84,category,0.0,0.0,2.0,"0.0, 1.0"
85,FCFP6_1024_85,category,0.0,0.0,2.0,"0.0, 1.0"
86,FCFP6_1024_86,category,0.0,0.0,2.0,"0.0, 1.0"
87,FCFP6_1024_87,category,0.0,0.0,2.0,"0.0, 1.0"
88,FCFP6_1024_88,category,0.0,0.0,2.0,"0.0, 1.0"
89,FCFP6_1024_89,category,0.0,0.0,2.0,"0.0, 1.0"
90,FCFP6_1024_90,category,0.0,0.0,2.0,"0.0, 1.0"
91,FCFP6_1024_91,category,0.0,0.0,2.0,"0.0, 1.0"
92,FCFP6_1024_92,category,0.0,0.0,2.0,"0.0, 1.0"
93,FCFP6_1024_93,category,0.0,0.0,2.0,"0.0, 1.0"
94,FCFP6_1024_94,category,0.0,0.0,2.0,"0.0, 1.0"
95,FCFP6_1024_95,category,0.0,0.0,2.0,"0.0, 1.0"
96,FCFP6_1024_96,category,0.0,0.0,2.0,"0.0, 1.0"
97,FCFP6_1024_97,category,0.0,0.0,2.0,"0.0, 1.0"
98,FCFP6_1024_98,category,0.0,0.0,2.0,"0.0, 1.0"
99,FCFP6_1024_99,category,0.0,0.0,2.0,"0.0, 1.0"
100,FCFP6_1024_100,category,0.0,0.0,2.0,"0.0, 1.0"
101,FCFP6_1024_101,category,0.0,0.0,2.0,"0.0, 1.0"
102,FCFP6_1024_102,category,0.0,0.0,2.0,"0.0, 1.0"
103,FCFP6_1024_103,category,0.0,0.0,2.0,"0.0, 1.0"
104,FCFP6_1024_104,category,0.0,0.0,2.0,"0.0, 1.0"
105,FCFP6_1024_105,category,0.0,0.0,2.0,"0.0, 1.0"
106,FCFP6_1024_106,category,0.0,0.0,2.0,"0.0, 1.0"
107,FCFP6_1024_107,category,0.0,0.0,2.0,"0.0, 1.0"
108,FCFP6_1024_108,category,0.0,0.0,2.0,"0.0, 1.0"
109,FCFP6_1024_109,category,0.0,0.0,2.0,"0.0, 1.0"
110,FCFP6_1024_110,category,0.0,0.0,2.0,"0.0, 1.0"
111,FCFP6_1024_111,category,0.0,0.0,2.0,"0.0, 1.0"
112,FCFP6_1024_112,category,0.0,0.0,2.0,"0.0, 1.0"
113,FCFP6_1024_113,category,0.0,0.0,2.0,"0.0, 1.0"
114,FCFP6_1024_114,category,0.0,0.0,2.0,"0.0, 1.0"
115,FCFP6_1024_115,category,0.0,0.0,2.0,"0.0, 1.0"
116,FCFP6_1024_116,category,0.0,0.0,2.0,"0.0, 1.0"
117,FCFP6_1024_117,category,0.0,0.0,2.0,"0.0, 1.0"
118,FCFP6_1024_118,category,0.0,0.0,2.0,"0.0, 1.0"
119,FCFP6_1024_119,category,0.0,0.0,2.0,"0.0, 1.0"
120,FCFP6_1024_120,category,0.0,0.0,2.0,"0.0, 1.0"
121,FCFP6_1024_121,category,0.0,0.0,2.0,"0.0, 1.0"
122,FCFP6_1024_122,category,0.0,0.0,2.0,"0.0, 1.0"
123,FCFP6_1024_123,category,0.0,0.0,2.0,"0.0, 1.0"
124,FCFP6_1024_124,category,0.0,0.0,2.0,"0.0, 1.0"
125,FCFP6_1024_125,category,0.0,0.0,2.0,"0.0, 1.0"
126,FCFP6_1024_126,category,0.0,0.0,2.0,"0.0, 1.0"
127,FCFP6_1024_127,category,0.0,0.0,2.0,"0.0, 1.0"
128,FCFP6_1024_128,category,0.0,0.0,2.0,"0.0, 1.0"
129,FCFP6_1024_129,category,0.0,0.0,2.0,"0.0, 1.0"
130,FCFP6_1024_130,category,0.0,0.0,2.0,"0.0, 1.0"
131,FCFP6_1024_131,category,0.0,0.0,2.0,"0.0, 1.0"
132,FCFP6_1024_132,category,0.0,0.0,2.0,"0.0, 1.0"
133,FCFP6_1024_133,category,0.0,0.0,2.0,"0.0, 1.0"
134,FCFP6_1024_134,category,0.0,0.0,2.0,"0.0, 1.0"
135,FCFP6_1024_135,category,0.0,0.0,2.0,"0.0, 1.0"
136,FCFP6_1024_136,category,0.0,0.0,2.0,"0.0, 1.0"
137,FCFP6_1024_137,category,0.0,0.0,2.0,"0.0, 1.0"
138,FCFP6_1024_138,category,0.0,0.0,2.0,"0.0, 1.0"
139,FCFP6_1024_139,category,0.0,0.0,2.0,"0.0, 1.0"
140,FCFP6_1024_140,category,0.0,0.0,2.0,"0.0, 1.0"
141,FCFP6_1024_141,category,0.0,0.0,2.0,"0.0, 1.0"
142,FCFP6_1024_142,category,0.0,0.0,2.0,"0.0, 1.0"
143,FCFP6_1024_143,category,0.0,0.0,2.0,"0.0, 1.0"
144,FCFP6_1024_144,category,0.0,0.0,2.0,"0.0, 1.0"
145,FCFP6_1024_145,category,0.0,0.0,2.0,"0.0, 1.0"
146,FCFP6_1024_146,category,0.0,0.0,2.0,"0.0, 1.0"
147,FCFP6_1024_147,category,0.0,0.0,2.0,"0.0, 1.0"
148,FCFP6_1024_148,category,0.0,0.0,2.0,"0.0, 1.0"
149,FCFP6_1024_149,category,0.0,0.0,2.0,"0.0, 1.0"
150,FCFP6_1024_150,category,0.0,0.0,2.0,"0.0, 1.0"
151,FCFP6_1024_151,category,0.0,0.0,2.0,"1.0, 0.0"
152,FCFP6_1024_152,category,0.0,0.0,2.0,"0.0, 1.0"
153,FCFP6_1024_153,category,0.0,0.0,2.0,"0.0, 1.0"
154,FCFP6_1024_154,category,0.0,0.0,2.0,"0.0, 1.0"
155,FCFP6_1024_155,category,0.0,0.0,2.0,"0.0, 1.0"
156,FCFP6_1024_156,category,0.0,0.0,2.0,"0.0, 1.0"
157,FCFP6_1024_157,category,0.0,0.0,2.0,"0.0, 1.0"
158,FCFP6_1024_158,category,0.0,0.0,2.0,"0.0, 1.0"
159,FCFP6_1024_159,category,0.0,0.0,2.0,"0.0, 1.0"
160,FCFP6_1024_160,category,0.0,0.0,2.0,"0.0, 1.0"
161,FCFP6_1024_161,category,0.0,0.0,2.0,"0.0, 1.0"
162,FCFP6_1024_162,category,0.0,0.0,2.0,"0.0, 1.0"
163,FCFP6_1024_163,category,0.0,0.0,2.0,"0.0, 1.0"
164,FCFP6_1024_164,category,0.0,0.0,2.0,"0.0, 1.0"
165,FCFP6_1024_165,category,0.0,0.0,2.0,"0.0, 1.0"
166,FCFP6_1024_166,category,0.0,0.0,2.0,"0.0, 1.0"
167,FCFP6_1024_167,category,0.0,0.0,2.0,"0.0, 1.0"
168,FCFP6_1024_168,category,0.0,0.0,2.0,"0.0, 1.0"
169,FCFP6_1024_169,category,0.0,0.0,2.0,"1.0, 0.0"
170,FCFP6_1024_170,category,0.0,0.0,2.0,"0.0, 1.0"
171,FCFP6_1024_171,category,0.0,0.0,2.0,"0.0, 1.0"
172,FCFP6_1024_172,category,0.0,0.0,2.0,"0.0, 1.0"
173,FCFP6_1024_173,category,0.0,0.0,2.0,"0.0, 1.0"
174,FCFP6_1024_174,category,0.0,0.0,2.0,"0.0, 1.0"
175,FCFP6_1024_175,category,0.0,0.0,2.0,"0.0, 1.0"
176,FCFP6_1024_176,category,0.0,0.0,2.0,"0.0, 1.0"
177,FCFP6_1024_177,category,0.0,0.0,2.0,"0.0, 1.0"
178,FCFP6_1024_178,category,0.0,0.0,2.0,"0.0, 1.0"
179,FCFP6_1024_179,category,0.0,0.0,2.0,"0.0, 1.0"
180,FCFP6_1024_180,category,0.0,0.0,2.0,"0.0, 1.0"
181,FCFP6_1024_181,category,0.0,0.0,2.0,"0.0, 1.0"
182,FCFP6_1024_182,category,0.0,0.0,2.0,"0.0, 1.0"
183,FCFP6_1024_183,category,0.0,0.0,2.0,"0.0, 1.0"
184,FCFP6_1024_184,category,0.0,0.0,2.0,"0.0, 1.0"
185,FCFP6_1024_185,category,0.0,0.0,2.0,"0.0, 1.0"
186,FCFP6_1024_186,category,0.0,0.0,2.0,"0.0, 1.0"
187,FCFP6_1024_187,category,0.0,0.0,2.0,"0.0, 1.0"
188,FCFP6_1024_188,category,0.0,0.0,2.0,"0.0, 1.0"
189,FCFP6_1024_189,category,0.0,0.0,2.0,"0.0, 1.0"
190,FCFP6_1024_190,category,0.0,0.0,2.0,"0.0, 1.0"
191,FCFP6_1024_191,category,0.0,0.0,2.0,"0.0, 1.0"
192,FCFP6_1024_192,category,0.0,0.0,2.0,"0.0, 1.0"
193,FCFP6_1024_193,category,0.0,0.0,2.0,"0.0, 1.0"
194,FCFP6_1024_194,category,0.0,0.0,2.0,"0.0, 1.0"
195,FCFP6_1024_195,category,0.0,0.0,2.0,"0.0, 1.0"
196,FCFP6_1024_196,category,0.0,0.0,2.0,"0.0, 1.0"
197,FCFP6_1024_197,category,0.0,0.0,2.0,"0.0, 1.0"
198,FCFP6_1024_198,category,0.0,0.0,2.0,"0.0, 1.0"
199,FCFP6_1024_199,category,0.0,0.0,2.0,"0.0, 1.0"
200,FCFP6_1024_200,category,0.0,0.0,2.0,"0.0, 1.0"
201,FCFP6_1024_201,category,0.0,0.0,2.0,"0.0, 1.0"
202,FCFP6_1024_202,category,0.0,0.0,2.0,"0.0, 1.0"
203,FCFP6_1024_203,category,0.0,0.0,2.0,"0.0, 1.0"
204,FCFP6_1024_204,category,0.0,0.0,2.0,"0.0, 1.0"
205,FCFP6_1024_205,category,0.0,0.0,2.0,"0.0, 1.0"
206,FCFP6_1024_206,category,0.0,0.0,2.0,"0.0, 1.0"
207,FCFP6_1024_207,category,0.0,0.0,2.0,"0.0, 1.0"
208,FCFP6_1024_208,category,0.0,0.0,2.0,"0.0, 1.0"
209,FCFP6_1024_209,category,0.0,0.0,2.0,"0.0, 1.0"
210,FCFP6_1024_210,category,0.0,0.0,2.0,"0.0, 1.0"
211,FCFP6_1024_211,category,0.0,0.0,2.0,"0.0, 1.0"
212,FCFP6_1024_212,category,0.0,0.0,2.0,"0.0, 1.0"
213,FCFP6_1024_213,category,0.0,0.0,2.0,"0.0, 1.0"
214,FCFP6_1024_214,category,0.0,0.0,2.0,"0.0, 1.0"
215,FCFP6_1024_215,category,0.0,0.0,2.0,"0.0, 1.0"
216,FCFP6_1024_216,category,0.0,0.0,2.0,"0.0, 1.0"
217,FCFP6_1024_217,category,0.0,0.0,2.0,"0.0, 1.0"
218,FCFP6_1024_218,category,0.0,0.0,2.0,"0.0, 1.0"
219,FCFP6_1024_219,category,0.0,0.0,2.0,"0.0, 1.0"
220,FCFP6_1024_220,category,0.0,0.0,2.0,"0.0, 1.0"
221,FCFP6_1024_221,category,0.0,0.0,2.0,"0.0, 1.0"
222,FCFP6_1024_222,category,0.0,0.0,2.0,"0.0, 1.0"
223,FCFP6_1024_223,category,0.0,0.0,2.0,"0.0, 1.0"
224,FCFP6_1024_224,category,0.0,0.0,2.0,"0.0, 1.0"
225,FCFP6_1024_225,category,0.0,0.0,2.0,"0.0, 1.0"
226,FCFP6_1024_226,category,0.0,0.0,2.0,"0.0, 1.0"
227,FCFP6_1024_227,category,0.0,0.0,2.0,"0.0, 1.0"
228,FCFP6_1024_228,category,0.0,0.0,2.0,"0.0, 1.0"
229,FCFP6_1024_229,category,0.0,0.0,2.0,"0.0, 1.0"
230,FCFP6_1024_230,category,0.0,0.0,2.0,"0.0, 1.0"
231,FCFP6_1024_231,category,0.0,0.0,2.0,"0.0, 1.0"
232,FCFP6_1024_232,category,0.0,0.0,2.0,"0.0, 1.0"
233,FCFP6_1024_233,category,0.0,0.0,2.0,"0.0, 1.0"
234,FCFP6_1024_234,category,0.0,0.0,2.0,"0.0, 1.0"
235,FCFP6_1024_235,category,0.0,0.0,2.0,"0.0, 1.0"
236,FCFP6_1024_236,category,0.0,0.0,2.0,"0.0, 1.0"
237,FCFP6_1024_237,category,0.0,0.0,2.0,"0.0, 1.0"
238,FCFP6_1024_238,category,0.0,0.0,2.0,"0.0, 1.0"
239,FCFP6_1024_239,category,0.0,0.0,2.0,"0.0, 1.0"
240,FCFP6_1024_240,category,0.0,0.0,2.0,"0.0, 1.0"
241,FCFP6_1024_241,category,0.0,0.0,2.0,"0.0, 1.0"
242,FCFP6_1024_242,category,0.0,0.0,2.0,"0.0, 1.0"
243,FCFP6_1024_243,category,0.0,0.0,2.0,"0.0, 1.0"
244,FCFP6_1024_244,category,0.0,0.0,2.0,"0.0, 1.0"
245,FCFP6_1024_245,category,0.0,0.0,2.0,"0.0, 1.0"
246,FCFP6_1024_246,category,0.0,0.0,2.0,"0.0, 1.0"
247,FCFP6_1024_247,category,0.0,0.0,2.0,"0.0, 1.0"
248,FCFP6_1024_248,category,0.0,0.0,2.0,"0.0, 1.0"
249,FCFP6_1024_249,category,0.0,0.0,2.0,"0.0, 1.0"
250,FCFP6_1024_250,category,0.0,0.0,2.0,"0.0, 1.0"
251,FCFP6_1024_251,category,0.0,0.0,2.0,"0.0, 1.0"
252,FCFP6_1024_252,category,0.0,0.0,2.0,"0.0, 1.0"
253,FCFP6_1024_253,category,0.0,0.0,2.0,"0.0, 1.0"
254,FCFP6_1024_254,category,0.0,0.0,2.0,"0.0, 1.0"
255,FCFP6_1024_255,category,0.0,0.0,2.0,"0.0, 1.0"
256,FCFP6_1024_256,category,0.0,0.0,2.0,"0.0, 1.0"
257,FCFP6_1024_257,category,0.0,0.0,2.0,"0.0, 1.0"
258,FCFP6_1024_258,category,0.0,0.0,2.0,"0.0, 1.0"
259,FCFP6_1024_259,category,0.0,0.0,2.0,"0.0, 1.0"
260,FCFP6_1024_260,category,0.0,0.0,2.0,"0.0, 1.0"
261,FCFP6_1024_261,category,0.0,0.0,2.0,"0.0, 1.0"
262,FCFP6_1024_262,category,0.0,0.0,2.0,"0.0, 1.0"
263,FCFP6_1024_263,category,0.0,0.0,2.0,"0.0, 1.0"
264,FCFP6_1024_264,category,0.0,0.0,2.0,"0.0, 1.0"
265,FCFP6_1024_265,category,0.0,0.0,2.0,"0.0, 1.0"
266,FCFP6_1024_266,category,0.0,0.0,2.0,"0.0, 1.0"
267,FCFP6_1024_267,category,0.0,0.0,2.0,"0.0, 1.0"
268,FCFP6_1024_268,category,0.0,0.0,2.0,"0.0, 1.0"
269,FCFP6_1024_269,category,0.0,0.0,2.0,"0.0, 1.0"
270,FCFP6_1024_270,category,0.0,0.0,2.0,"0.0, 1.0"
271,FCFP6_1024_271,category,0.0,0.0,2.0,"0.0, 1.0"
272,FCFP6_1024_272,category,0.0,0.0,2.0,"0.0, 1.0"
273,FCFP6_1024_273,category,0.0,0.0,2.0,"0.0, 1.0"
274,FCFP6_1024_274,category,0.0,0.0,2.0,"0.0, 1.0"
275,FCFP6_1024_275,category,0.0,0.0,2.0,"0.0, 1.0"
276,FCFP6_1024_276,category,0.0,0.0,2.0,"0.0, 1.0"
277,FCFP6_1024_277,category,0.0,0.0,2.0,"0.0, 1.0"
278,FCFP6_1024_278,category,0.0,0.0,2.0,"0.0, 1.0"
279,FCFP6_1024_279,category,0.0,0.0,2.0,"0.0, 1.0"
280,FCFP6_1024_280,category,0.0,0.0,2.0,"0.0, 1.0"
281,FCFP6_1024_281,category,0.0,0.0,2.0,"0.0, 1.0"
282,FCFP6_1024_282,category,0.0,0.0,2.0,"0.0, 1.0"
283,FCFP6_1024_283,category,0.0,0.0,2.0,"0.0, 1.0"
284,FCFP6_1024_284,category,0.0,0.0,2.0,"0.0, 1.0"
285,FCFP6_1024_285,category,0.0,0.0,2.0,"0.0, 1.0"
286,FCFP6_1024_286,category,0.0,0.0,2.0,"0.0, 1.0"
287,FCFP6_1024_287,category,0.0,0.0,2.0,"0.0, 1.0"
288,FCFP6_1024_288,category,0.0,0.0,2.0,"0.0, 1.0"
289,FCFP6_1024_289,category,0.0,0.0,2.0,"0.0, 1.0"
290,FCFP6_1024_290,category,0.0,0.0,2.0,"0.0, 1.0"
291,FCFP6_1024_291,category,0.0,0.0,2.0,"0.0, 1.0"
292,FCFP6_1024_292,category,0.0,0.0,2.0,"0.0, 1.0"
293,FCFP6_1024_293,category,0.0,0.0,2.0,"0.0, 1.0"
294,FCFP6_1024_294,category,0.0,0.0,2.0,"0.0, 1.0"
295,FCFP6_1024_295,category,0.0,0.0,2.0,"0.0, 1.0"
296,FCFP6_1024_296,category,0.0,0.0,2.0,"0.0, 1.0"
297,FCFP6_1024_297,category,0.0,0.0,2.0,"0.0, 1.0"
298,FCFP6_1024_298,category,0.0,0.0,2.0,"0.0, 1.0"
299,FCFP6_1024_299,category,0.0,0.0,2.0,"0.0, 1.0"
300,FCFP6_1024_300,category,0.0,0.0,2.0,"0.0, 1.0"
301,FCFP6_1024_301,category,0.0,0.0,2.0,"0.0, 1.0"
302,FCFP6_1024_302,category,0.0,0.0,2.0,"0.0, 1.0"
303,FCFP6_1024_303,category,0.0,0.0,2.0,"0.0, 1.0"
304,FCFP6_1024_304,category,0.0,0.0,2.0,"0.0, 1.0"
305,FCFP6_1024_305,category,0.0,0.0,2.0,"0.0, 1.0"
306,FCFP6_1024_306,category,0.0,0.0,2.0,"0.0, 1.0"
307,FCFP6_1024_307,category,0.0,0.0,2.0,"0.0, 1.0"
308,FCFP6_1024_308,category,0.0,0.0,2.0,"0.0, 1.0"
309,FCFP6_1024_309,category,0.0,0.0,2.0,"0.0, 1.0"
310,FCFP6_1024_310,category,0.0,0.0,2.0,"0.0, 1.0"
311,FCFP6_1024_311,category,0.0,0.0,2.0,"0.0, 1.0"
312,FCFP6_1024_312,category,0.0,0.0,2.0,"0.0, 1.0"
313,FCFP6_1024_313,category,0.0,0.0,2.0,"0.0, 1.0"
314,FCFP6_1024_314,category,0.0,0.0,2.0,"0.0, 1.0"
315,FCFP6_1024_315,category,0.0,0.0,2.0,"0.0, 1.0"
316,FCFP6_1024_316,category,0.0,0.0,2.0,"0.0, 1.0"
317,FCFP6_1024_317,category,0.0,0.0,2.0,"0.0, 1.0"
318,FCFP6_1024_318,category,0.0,0.0,2.0,"0.0, 1.0"
319,FCFP6_1024_319,category,0.0,0.0,2.0,"0.0, 1.0"
320,FCFP6_1024_320,category,0.0,0.0,2.0,"0.0, 1.0"
321,FCFP6_1024_321,category,0.0,0.0,2.0,"0.0, 1.0"
322,FCFP6_1024_322,category,0.0,0.0,2.0,"0.0, 1.0"
323,FCFP6_1024_323,category,0.0,0.0,2.0,"0.0, 1.0"
324,FCFP6_1024_324,category,0.0,0.0,2.0,"0.0, 1.0"
325,FCFP6_1024_325,category,0.0,0.0,2.0,"0.0, 1.0"
326,FCFP6_1024_326,category,0.0,0.0,2.0,"0.0, 1.0"
327,FCFP6_1024_327,category,0.0,0.0,2.0,"0.0, 1.0"
328,FCFP6_1024_328,category,0.0,0.0,2.0,"0.0, 1.0"
329,FCFP6_1024_329,category,0.0,0.0,2.0,"0.0, 1.0"
330,FCFP6_1024_330,category,0.0,0.0,2.0,"0.0, 1.0"
331,FCFP6_1024_331,category,0.0,0.0,2.0,"0.0, 1.0"
332,FCFP6_1024_332,category,0.0,0.0,2.0,"0.0, 1.0"
333,FCFP6_1024_333,category,0.0,0.0,2.0,"0.0, 1.0"
334,FCFP6_1024_334,category,0.0,0.0,2.0,"0.0, 1.0"
335,FCFP6_1024_335,category,0.0,0.0,2.0,"0.0, 1.0"
336,FCFP6_1024_336,category,0.0,0.0,2.0,"0.0, 1.0"
337,FCFP6_1024_337,category,0.0,0.0,2.0,"0.0, 1.0"
338,FCFP6_1024_338,category,0.0,0.0,2.0,"0.0, 1.0"
339,FCFP6_1024_339,category,0.0,0.0,2.0,"0.0, 1.0"
340,FCFP6_1024_340,category,0.0,0.0,2.0,"0.0, 1.0"
341,FCFP6_1024_341,category,0.0,0.0,2.0,"0.0, 1.0"
342,FCFP6_1024_342,category,0.0,0.0,2.0,"0.0, 1.0"
343,FCFP6_1024_343,category,0.0,0.0,2.0,"0.0, 1.0"
344,FCFP6_1024_344,category,0.0,0.0,2.0,"0.0, 1.0"
345,FCFP6_1024_345,category,0.0,0.0,2.0,"0.0, 1.0"
346,FCFP6_1024_346,category,0.0,0.0,2.0,"0.0, 1.0"
347,FCFP6_1024_347,category,0.0,0.0,2.0,"0.0, 1.0"
348,FCFP6_1024_348,category,0.0,0.0,2.0,"0.0, 1.0"
349,FCFP6_1024_349,category,0.0,0.0,2.0,"0.0, 1.0"
350,FCFP6_1024_350,category,0.0,0.0,2.0,"0.0, 1.0"
351,FCFP6_1024_351,category,0.0,0.0,2.0,"0.0, 1.0"
352,FCFP6_1024_352,category,0.0,0.0,2.0,"0.0, 1.0"
353,FCFP6_1024_353,category,0.0,0.0,2.0,"0.0, 1.0"
354,FCFP6_1024_354,category,0.0,0.0,2.0,"0.0, 1.0"
355,FCFP6_1024_355,category,0.0,0.0,2.0,"0.0, 1.0"
356,FCFP6_1024_356,category,0.0,0.0,2.0,"0.0, 1.0"
357,FCFP6_1024_357,category,0.0,0.0,2.0,"0.0, 1.0"
358,FCFP6_1024_358,category,0.0,0.0,2.0,"0.0, 1.0"
359,FCFP6_1024_359,category,0.0,0.0,2.0,"0.0, 1.0"
360,FCFP6_1024_360,category,0.0,0.0,2.0,"0.0, 1.0"
361,FCFP6_1024_361,category,0.0,0.0,2.0,"0.0, 1.0"
362,FCFP6_1024_362,category,0.0,0.0,2.0,"0.0, 1.0"
363,FCFP6_1024_363,category,0.0,0.0,2.0,"0.0, 1.0"
364,FCFP6_1024_364,category,0.0,0.0,2.0,"0.0, 1.0"
365,FCFP6_1024_365,category,0.0,0.0,2.0,"0.0, 1.0"
366,FCFP6_1024_366,category,0.0,0.0,2.0,"0.0, 1.0"
367,FCFP6_1024_367,category,0.0,0.0,2.0,"0.0, 1.0"
368,FCFP6_1024_368,category,0.0,0.0,2.0,"0.0, 1.0"
369,FCFP6_1024_369,category,0.0,0.0,2.0,"0.0, 1.0"
370,FCFP6_1024_370,category,0.0,0.0,2.0,"0.0, 1.0"
371,FCFP6_1024_371,category,0.0,0.0,2.0,"0.0, 1.0"
372,FCFP6_1024_372,category,0.0,0.0,2.0,"0.0, 1.0"
373,FCFP6_1024_373,category,0.0,0.0,2.0,"0.0, 1.0"
374,FCFP6_1024_374,category,0.0,0.0,2.0,"0.0, 1.0"
375,FCFP6_1024_375,category,0.0,0.0,2.0,"0.0, 1.0"
376,FCFP6_1024_376,category,0.0,0.0,2.0,"0.0, 1.0"
377,FCFP6_1024_377,category,0.0,0.0,2.0,"0.0, 1.0"
378,FCFP6_1024_378,category,0.0,0.0,2.0,"0.0, 1.0"
379,FCFP6_1024_379,category,0.0,0.0,2.0,"0.0, 1.0"
380,FCFP6_1024_380,category,0.0,0.0,2.0,"0.0, 1.0"
381,FCFP6_1024_381,category,0.0,0.0,2.0,"0.0, 1.0"
382,FCFP6_1024_382,category,0.0,0.0,2.0,"0.0, 1.0"
383,FCFP6_1024_383,category,0.0,0.0,2.0,"0.0, 1.0"
384,FCFP6_1024_384,category,0.0,0.0,2.0,"0.0, 1.0"
385,FCFP6_1024_385,category,0.0,0.0,2.0,"0.0, 1.0"
386,FCFP6_1024_386,category,0.0,0.0,2.0,"0.0, 1.0"
387,FCFP6_1024_387,category,0.0,0.0,2.0,"0.0, 1.0"
388,FCFP6_1024_388,category,0.0,0.0,2.0,"0.0, 1.0"
389,FCFP6_1024_389,category,0.0,0.0,2.0,"0.0, 1.0"
390,FCFP6_1024_390,category,0.0,0.0,2.0,"0.0, 1.0"
391,FCFP6_1024_391,category,0.0,0.0,2.0,"0.0, 1.0"
392,FCFP6_1024_392,category,0.0,0.0,2.0,"0.0, 1.0"
393,FCFP6_1024_393,category,0.0,0.0,2.0,"0.0, 1.0"
394,FCFP6_1024_394,category,0.0,0.0,2.0,"0.0, 1.0"

In [6]:
# Numeric Feature Statistics
numeric_stats

               count      mean      std   min   max
MEDIAN_PXC50  5742.0  6.237024  1.54766 -6.24  11.0

In [7]:
# Categorical Feature Statistics
cat_stats

                     value  count    pct
column          rank
FCFP6_1024_0    1      1.0   5738  99.93
                2      0.0      4   0.07
FCFP6_1024_1    1      1.0   5616  97.81
                2      0.0    126   2.19
FCFP6_1024_10   1      0.0   5689  99.08
                2      1.0     53   0.92
FCFP6_1024_100  1      0.0   5694  99.16
                2      1.0     48   0.84
FCFP6_1024_1000 1      0.0   5596  97.46
                2      1.0    146   2.54
FCFP6_1024_1001 1      0.0   5426  94.50
                2      1.0    316   5.50
FCFP6_1024_1002 1      0.0   5407  94.17
                2      1.0    335   5.83
FCFP6_1024_1003 1      0.0   5226  91.01
                2      1.0    516   8.99
FCFP6_1024_1004 1      0.0   5553  96.71
                2      1.0    189   3.29
FCFP6_1024_1005 1      0.0   5383  93.75
                2      1.0    359   6.25
FCFP6_1024_1006 1      0.0   5672  98.78
                2      1.0     70   1.22
FCFP6_1024_1007 1      0.0   4864  84.71
                2      1.0    878  15.29
FCFP6_1024_1008 1      0.0   5672  98.78
                2      1.0     70   1.22
FCFP6_1024_1009 1      0.0   5546  96.59
                2      1.0    196   3.41
FCFP6_1024_101  1      0.0   5528  96.27
                2      1.0    214   3.73
FCFP6_1024_1010 1      0.0   5424  94.46
                2      1.0    318   5.54
FCFP6_1024_1011 1      0.0   5650  98.40
                2      1.0     92   1.60
FCFP6_1024_1012 1      0.0   5531  96.33
                2      1.0    211   3.67
FCFP6_1024_1013 1      0.0   5415  94.31
                2      1.0    327   5.69
FCFP6_1024_1014 1      0.0   4964  86.45
                2      1.0    778  13.55
FCFP6_1024_1015 1      0.0   5614  97.77
                2      1.0    128   2.23
FCFP6_1024_1016 1      0.0   5455  95.00
                2      1.0    287   5.00
FCFP6_1024_1017 1      0.0   5388  93.83
                2      1.0    354   6.17
FCFP6_1024_1018 1      0.0   4751  82.74
                2      1.0    991  17.26
FCFP6_1024_1019 1      0.0   4834  84.19
                2      1.0    908  15.81
FCFP6_1024_102  1      0.0   5514  96.03
                2      1.0    228   3.97
FCFP6_1024_1020 1      0.0   5453  94.97
                2      1.0    289   5.03
FCFP6_1024_1021 1      0.0   5613  97.75
                2      1.0    129   2.25
FCFP6_1024_1022 1      0.0   5654  98.47
                2      1.0     88   1.53
FCFP6_1024_1023 1      0.0   5701  99.29
                2      1.0     41   0.71
FCFP6_1024_103  1      0.0   5578  97.14
                2      1.0    164   2.86
FCFP6_1024_104  1      0.0   5456  95.02
                2      1.0    286   4.98
FCFP6_1024_105  1      0.0   5259  91.59
                2      1.0    483   8.41
FCFP6_1024_106  1      0.0   4104  71.47
                2      1.0   1638  28.53
FCFP6_1024_107  1      0.0   5431  94.58
                2      1.0    311   5.42
FCFP6_1024_108  1      0.0   5694  99.16
                2      1.0     48   0.84
FCFP6_1024_109  1      0.0   5410  94.22
                2      1.0    332   5.78
FCFP6_1024_11   1      0.0   5306  92.41
                2      1.0    436   7.59
FCFP6_1024_110  1      0.0   5689  99.08
                2      1.0     53   0.92
FCFP6_1024_111  1      0.0   5345  93.09
                2      1.0    397   6.91
FCFP6_1024_112  1      0.0   5649  98.38
                2      1.0     93   1.62
FCFP6_1024_113  1      0.0   5557  96.78
                2      1.0    185   3.22
FCFP6_1024_114  1      0.0   5669  98.73
                2      1.0     73   1.27
FCFP6_1024_115  1      0.0   5596  97.46
                2      1.0    146   2.54
FCFP6_1024_116  1      0.0   5355  93.26
                2      1.0    387   6.74
FCFP6_1024_117  1      0.0   5092  88.68
                2      1.0    650  11.32
FCFP6_1024_118  1      0.0   5646  98.33
                2      1.0     96   1.67
FCFP6_1024_119  1      0.0   5621  97.89
                2      1.0    121   2.11
FCFP6_1024_12   1      0.0   5614  97.77
                2      1.0    128   2.23
FCFP6_1024_120  1      0.0   5330  92.82
                2      1.0    412   7.18
FCFP6_1024_121  1      0.0   5231  91.10
                2      1.0    511   8.90
FCFP6_1024_122  1      0.0   5409  94.20
                2      1.0    333   5.80
FCFP6_1024_123  1      0.0   4846  84.40
                2      1.0    896  15.60
FCFP6_1024_124  1      0.0   5669  98.73
                2      1.0     73   1.27
FCFP6_1024_125  1      0.0   5574  97.07
                2      1.0    168   2.93
FCFP6_1024_126  1      0.0   5592  97.39
                2      1.0    150   2.61
FCFP6_1024_127  1      0.0   5114  89.06
                2      1.0    628  10.94
FCFP6_1024_128  1      0.0   3942  68.65
                2      1.0   1800  31.35
FCFP6_1024_129  1      0.0   5515  96.05
                2      1.0    227   3.95
FCFP6_1024_13   1      0.0   5681  98.94
                2      1.0     61   1.06
FCFP6_1024_130  1      0.0   5582  97.21
                2      1.0    160   2.79
FCFP6_1024_131  1      0.0   5493  95.66
                2      1.0    249   4.34
FCFP6_1024_132  1      0.0   4745  82.64
                2      1.0    997  17.36
FCFP6_1024_133  1      0.0   5469  95.25
                2      1.0    273   4.75
FCFP6_1024_134  1      0.0   5604  97.60
                2      1.0    138   2.40
FCFP6_1024_135  1      0.0   5677  98.87
                2      1.0     65   1.13
FCFP6_1024_136  1      0.0   4933  85.91
                2      1.0    809  14.09
FCFP6_1024_137  1      0.0   5524  96.20
                2      1.0    218   3.80
FCFP6_1024_138  1      0.0   4514  78.61
                2      1.0   1228  21.39
FCFP6_1024_139  1      0.0   5698  99.23
                2      1.0     44   0.77
FCFP6_1024_14   1      0.0   5697  99.22
                2      1.0     45   0.78
FCFP6_1024_140  1      0.0   5632  98.08
                2      1.0    110   1.92
FCFP6_1024_141  1      0.0   5450  94.91
                2      1.0    292   5.09
FCFP6_1024_142  1      0.0   5391  93.89
                2      1.0    351   6.11
FCFP6_1024_143  1      0.0   5689  99.08
                2      1.0     53   0.92
FCFP6_1024_144  1      0.0   5658  98.54
                2      1.0     84   1.46
FCFP6_1024_145  1      0.0   5661  98.59
                2      1.0     81   1.41
FCFP6_1024_146  1      0.0   5697  99.22
                2      1.0     45   0.78
FCFP6_1024_147  1      0.0   5631  98.07
                2      1.0    111   1.93
FCFP6_1024_148  1      0.0   5649  98.38
                2      1.0     93   1.62
FCFP6_1024_149  1      0.0   5598  97.49
                2      1.0    144   2.51
FCFP6_1024_15   1      0.0   5713  99.49
                2      1.0     29   0.51
FCFP6_1024_150  1      0.0   5633  98.10
                2      1.0    109   1.90
FCFP6_1024_151  1      1.0   3024  52.66
                2      0.0   2718  47.34
FCFP6_1024_152  1      0.0   5382  93.73
                2      1.0    360   6.27
FCFP6_1024_153  1      0.0   5686  99.02
                2      1.0     56   0.98
FCFP6_1024_154  1      0.0   5632  98.08
                2      1.0    110   1.92
FCFP6_1024_155  1      0.0   5690  99.09
                2      1.0     52   0.91
FCFP6_1024_156  1      0.0   5612  97.74
                2      1.0    130   2.26
FCFP6_1024_157  1      0.0   5658  98.54
                2      1.0     84   1.46
FCFP6_1024_158  1      0.0   5400  94.04
                2      1.0    342   5.96
FCFP6_1024_159  1      0.0   5636  98.15
                2      1.0    106   1.85
FCFP6_1024_16   1      1.0   5617  97.82
                2      0.0    125   2.18
FCFP6_1024_160  1      0.0   5651  98.42
                2      1.0     91   1.58
FCFP6_1024_161  1      0.0   5608  97.67
                2      1.0    134   2.33
FCFP6_1024_162  1      0.0   5665  98.66
                2      1.0     77   1.34
FCFP6_1024_163  1      0.0   5313  92.53
                2      1.0    429   7.47
FCFP6_1024_164  1      0.0   5457  95.04
                2      1.0    285   4.96
FCFP6_1024_165  1      0.0   5430  94.57
                2      1.0    312   5.43
FCFP6_1024_166  1      0.0   5460  95.09
                2      1.0    282   4.91
FCFP6_1024_167  1      0.0   5619  97.86
                2      1.0    123   2.14
FCFP6_1024_168  1      0.0   5098  88.78
                2      1.0    644  11.22
FCFP6_1024_169  1      1.0   5537  96.43
                2      0.0    205   3.57
FCFP6_1024_17   1      1.0   3611  62.89
                2      0.0   2131  37.11
FCFP6_1024_170  1      0.0   3170  55.21
                2      1.0   2572  44.79
FCFP6_1024_171  1      0.0   5644  98.29
                2      1.0     98   1.71
FCFP6_1024_172  1      0.0   5073  88.35
                2      1.0    669  11.65
FCFP6_1024_173  1      0.0   5720  99.62
                2      1.0     22   0.38
FCFP6_1024_174  1      0.0   5703  99.32
                2      1.0     39   0.68
FCFP6_1024_175  1      0.0   5680  98.92
                2      1.0     62   1.08
FCFP6_1024_176  1      0.0   5413  94.27
                2      1.0    329   5.73
FCFP6_1024_177  1      0.0   5124  89.24
                2      1.0    618  10.76
FCFP6_1024_178  1      0.0   5610  97.70
                2      1.0    132   2.30
FCFP6_1024_179  1      0.0   5672  98.78
                2      1.0     70   1.22
FCFP6_1024_18   1      0.0   5691  99.11
                2      1.0     51   0.89
FCFP6_1024_180  1      0.0   5520  96.13
                2      1.0    222   3.87
FCFP6_1024_181  1      0.0   5431  94.58
                2      1.0    311   5.42
FCFP6_1024_182  1      0.0   5585  97.27
                2      1.0    157   2.73
FCFP6_1024_183  1      0.0   5662  98.61
                2      1.0     80   1.39
FCFP6_1024_184  1      0.0   5476  95.37
                2      1.0    266   4.63
FCFP6_1024_185  1      0.0   5559  96.81
                2      1.0    183   3.19
FCFP6_1024_186  1      0.0   5459  95.07
                2      1.0    283   4.93
FCFP6_1024_187  1      0.0   5538  96.45
                2      1.0    204   3.55
FCFP6_1024_188  1      0.0   5691  99.11
                2      1.0     51   0.89
FCFP6_1024_189  1      0.0   5645  98.31
                2      1.0     97   1.69
FCFP6_1024_19   1      0.0   5287  92.08
                2      1.0    455   7.92
FCFP6_1024_190  1      0.0   5044  87.84
                2      1.0    698  12.16
FCFP6_1024_191  1      0.0   5536  96.41
                2      1.0    206   3.59
FCFP6_1024_192  1      0.0   5470  95.26
                2      1.0    272   4.74
FCFP6_1024_193  1      0.0   5496  95.72
                2      1.0    246   4.28
FCFP6_1024_194  1      0.0   4399  76.61
                2      1.0   1343  23.39
FCFP6_1024_195  1      0.0   5572  97.04
                2      1.0    170   2.96
FCFP6_1024_196  1      0.0   5542  96.52
                2      1.0    200   3.48
FCFP6_1024_197  1      0.0   5558  96.80
                2      1.0    184   3.20
FCFP6_1024_198  1      0.0   5303  92.35
                2      1.0    439   7.65
FCFP6_1024_199  1      0.0   5618  97.84
                2      1.0    124   2.16
FCFP6_1024_2    1      0.0   5677  98.87
                2      1.0     65   1.13
FCFP6_1024_20   1      0.0   5694  99.16
                2      1.0     48   0.84
FCFP6_1024_200  1      0.0   5512  95.99
                2      1.0    230   4.01
FCFP6_1024_201  1      0.0   5653  98.45
                2      1.0     89   1.55
FCFP6_1024_202  1      0.0   5569  96.99
                2      1.0    173   3.01
FCFP6_1024_203  1      0.0   5589  97.34
                2      1.0    153   2.66
FCFP6_1024_204  1      0.0   5641  98.24
                2      1.0    101   1.76
FCFP6_1024_205  1      0.0   5581  97.20
                2      1.0    161   2.80
FCFP6_1024_206  1      0.0   5632  98.08
                2      1.0    110   1.92
FCFP6_1024_207  1      0.0   4897  85.28
                2      1.0    845  14.72
FCFP6_1024_208  1      0.0   5531  96.33
                2      1.0    211   3.67
FCFP6_1024_209  1      0.0   5636  98.15
                2      1.0    106   1.85
FCFP6_1024_21   1      0.0   5620  97.88
                2      1.0    122   2.12
FCFP6_1024_210  1      0.0   5642  98.26
                2      1.0    100   1.74
FCFP6_1024_211  1      0.0   5598  97.49
                2      1.0    144   2.51
FCFP6_1024_212  1      0.0   5639  98.21
                2      1.0    103   1.79
FCFP6_1024_213  1      0.0   4993  86.96
                2      1.0    749  13.04
FCFP6_1024_214  1      0.0   5004  87.15
                2      1.0    738  12.85
FCFP6_1024_215  1      0.0   5604  97.60
                2      1.0    138   2.40
FCFP6_1024_216  1      0.0   5701  99.29
                2      1.0     41   0.71
FCFP6_1024_217  1      0.0   5542  96.52
                2      1.0    200   3.48
FCFP6_1024_218  1      0.0   5617  97.82
                2      1.0    125   2.18
FCFP6_1024_219  1      0.0   5609  97.68
                2      1.0    133   2.32
FCFP6_1024_22   1      0.0   5671  98.76
                2      1.0     71   1.24
FCFP6_1024_220  1      0.0   5674  98.82
                2      1.0     68   1.18
FCFP6_1024_221  1      0.0   5230  91.08
                2      1.0    512   8.92
FCFP6_1024_222  1      0.0   5531  96.33
                2      1.0    211   3.67
FCFP6_1024_223  1      0.0   5600  97.53
                2      1.0    142   2.47
FCFP6_1024_224  1      0.0   5633  98.10
                2      1.0    109   1.90
FCFP6_1024_225  1      0.0   5344  93.07
                2      1.0    398   6.93
FCFP6_1024_226  1      0.0   5476  95.37
                2      1.0    266   4.63
FCFP6_1024_227  1      0.0   5558  96.80
                2      1.0    184   3.20
FCFP6_1024_228  1      0.0   5482  95.47
                2      1.0    260   4.53
FCFP6_1024_229  1      0.0   5712  99.48
                2      1.0     30   0.52
FCFP6_1024_23   1      0.0   5667  98.69
                2      1.0     75   1.31
FCFP6_1024_230  1      0.0   5649  98.38
                2      1.0     93   1.62
FCFP6_1024_231  1      0.0   5658  98.54
                2      1.0     84   1.46
FCFP6_1024_232  1      0.0   5603  97.58
                2      1.0    139   2.42
FCFP6_1024_233  1      0.0   5590  97.35
                2      1.0    152   2.65
FCFP6_1024_234  1      0.0   5389  93.85
                2      1.0    353   6.15
FCFP6_1024_235  1      0.0   5571  97.02
                2      1.0    171   2.98
FCFP6_1024_236  1      0.0   5484  95.51
                2      1.0    258   4.49
FCFP6_1024_237  1      0.0   5699  99.25
                2      1.0     43   0.75
FCFP6_1024_238  1      0.0   5507  95.91
                2      1.0    235   4.09
FCFP6_1024_239  1      0.0   4994  86.97
                2      1.0    748  13.03
FCFP6_1024_24   1      1.0   5290  92.13
                2      0.0    452   7.87
FCFP6_1024_240  1      0.0   5399  94.03
                2      1.0    343   5.97
FCFP6_1024_241  1      0.0   5549  96.64
                2      1.0    193   3.36
FCFP6_1024_242  1      0.0   5559  96.81
                2      1.0    183   3.19
FCFP6_1024_243  1      0.0   5602  97.56
                2      1.0    140   2.44
FCFP6_1024_244  1      0.0   5614  97.77
                2      1.0    128   2.23
FCFP6_1024_245  1      0.0   5465  95.18
                2      1.0    277   4.82
FCFP6_1024_246  1      0.0   5603  97.58
                2      1.0    139   2.42
FCFP6_1024_247  1      0.0   5356  93.28
                2      1.0    386   6.72
FCFP6_1024_248  1      0.0   5658  98.54
                2      1.0     84   1.46
FCFP6_1024_249  1      0.0   5121  89.18
                2      1.0    621  10.82
FCFP6_1024_25   1      0.0   5643  98.28
                2      1.0     99   1.72
FCFP6_1024_250  1      0.0   5635  98.14
                2      1.0    107   1.86
FCFP6_1024_251  1      0.0   5368  93.49
                2      1.0    374   6.51
FCFP6_1024_252  1      0.0   5679  98.90
                2      1.0     63   1.10
FCFP6_1024_253  1      0.0   5701  99.29
                2      1.0     41   0.71
FCFP6_1024_254  1      0.0   5599  97.51
                2      1.0    143   2.49
FCFP6_1024_255  1      0.0   5531  96.33
                2      1.0    211   3.67
FCFP6_1024_256  1      0.0   5690  99.09
                2      1.0     52   0.91
FCFP6_1024_257  1      0.0   5428  94.53
                2      1.0    314   5.47
FCFP6_1024_258  1      0.0   5535  96.39
                2      1.0    207   3.61
FCFP6_1024_259  1      0.0   5439  94.72
                2      1.0    303   5.28
FCFP6_1024_26   1      0.0   5325  92.74
                2      1.0    417   7.26
FCFP6_1024_260  1      0.0   5642  98.26
                2      1.0    100   1.74
FCFP6_1024_261  1      0.0   5658  98.54
                2      1.0     84   1.46
FCFP6_1024_262  1      0.0   5501  95.80
                2      1.0    241   4.20
FCFP6_1024_263  1      0.0   4597  80.06
                2      1.0   1145  19.94
FCFP6_1024_264  1      0.0   5485  95.52
                2      1.0    257   4.48
FCFP6_1024_265  1      0.0   5627  98.00
                2      1.0    115   2.00
FCFP6_1024_266  1      0.0   5627  98.00
                2      1.0    115   2.00
FCFP6_1024_267  1      0.0   5612  97.74
                2      1.0    130   2.26
FCFP6_1024_268  1      0.0   5527  96.26
                2      1.0    215   3.74
FCFP6_1024_269  1      0.0   5331  92.84
                2      1.0    411   7.16
FCFP6_1024_27   1      0.0   5425  94.48
                2      1.0    317   5.52
FCFP6_1024_270  1      0.0   4732  82.41
                2      1.0   1010  17.59
FCFP6_1024_271  1      0.0   5668  98.71
                2      1.0     74   1.29
FCFP6_1024_272  1      0.0   5548  96.62
                2      1.0    194   3.38
FCFP6_1024_273  1      0.0   5688  99.06
                2      1.0     54   0.94
FCFP6_1024_274  1      0.0   5527  96.26
                2      1.0    215   3.74
FCFP6_1024_275  1      0.0   5537  96.43
                2      1.0    205   3.57
FCFP6_1024_276  1      0.0   5641  98.24
                2      1.0    101   1.76
FCFP6_1024_277  1      0.0   5473  95.32
                2      1.0    269   4.68
FCFP6_1024_278  1      0.0   5584  97.25
                2      1.0    158   2.75
FCFP6_1024_279  1      0.0   4956  86.31
                2      1.0    786  13.69
FCFP6_1024_28   1      0.0   5677  98.87
                2      1.0     65   1.13
FCFP6_1024_280  1      0.0   5051  87.97
                2      1.0    691  12.03
FCFP6_1024_281  1      0.0   5732  99.83
                2      1.0     10   0.17
FCFP6_1024_282  1      0.0   4560  79.41
                2      1.0   1182  20.59
FCFP6_1024_283  1      0.0   5563  96.88
                2      1.0    179   3.12
FCFP6_1024_284  1      0.0   5694  99.16
                2      1.0     48   0.84
FCFP6_1024_285  1      0.0   5586  97.28
                2      1.0    156   2.72
FCFP6_1024_286  1      0.0   5676  98.85
                2      1.0     66   1.15
FCFP6_1024_287  1      0.0   5453  94.97
                2      1.0    289   5.03
FCFP6_1024_288  1      0.0   5443  94.79
                2      1.0    299   5.21
FCFP6_1024_289  1      0.0   5675  98.83
                2      1.0     67   1.17
FCFP6_1024_29   1      0.0   5498  95.75
                2      1.0    244   4.25
FCFP6_1024_290  1      0.0   5631  98.07
                2      1.0    111   1.93
FCFP6_1024_291  1      0.0   5647  98.35
                2      1.0     95   1.65
FCFP6_1024_292  1      0.0   5687  99.04
                2      1.0     55   0.96
FCFP6_1024_293  1      0.0   5652  98.43
                2      1.0     90   1.57
FCFP6_1024_294  1      0.0   5523  96.19
                2      1.0    219   3.81
FCFP6_1024_295  1      0.0   5557  96.78
                2      1.0    185   3.22

In [8]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.02,0.593,NaN,2.395,0.042,log1p,37698.4,37354.6,lognormal

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to qsar_tid_11/019d4801-f46b-70f0-ac4f-a064e923ac10
019d4801-f46b-70f0-ac4f-a064e923ac10
f124bb2fdab758365a26fd824397ecfd2c95462210710a5dad3f933ba708c69d