### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="naticusdroid_android_permissions_dataset",
    dataset_year="2021",
    domain_str="technology & internet",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://archive.ics.uci.edu/dataset/722/naticusdroid+android+permissions+dataset",
    download_description="""
We download the data from the UCI repository and uzip it to a predefined folder.

mkdir -p local-data-warehouse/naticusdroid_android_permissions_dataset/ && wget -P local-data-warehouse/naticusdroid_android_permissions_dataset/ https://archive.ics.uci.edu/static/public/722/naticusdroid+android+permissions+dataset.zip && unzip local-data-warehouse/naticusdroid_android_permissions_dataset/naticusdroid+android+permissions+dataset.zip -d local-data-warehouse/naticusdroid_android_permissions_dataset/  && rm local-data-warehouse/naticusdroid_android_permissions_dataset/naticusdroid+android+permissions+dataset.zip
""",
    # References
    academic_reference_bibtex="""@article{mathur2021naticusdroid,
  title={NATICUSdroid: A malware detection framework for Android using native and custom permissions},
  author={Mathur, Akshay and Podila, Laxmi Mounika and Kulkarni, Keyur and Niyaz, Quamar and Javaid, Ahmad Y},
  journal={Journal of Information Security and Applications},
  volume={58},
  pages={102696},
  year={2021},
  publisher={Elsevier}
}
""",
    academic_reference_bibtex_key="mathur2021naticusdroid",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
- Originally, the data has 75% duplicates and a perfect class balance. The authors never mention duplicates in their paper. Given this large amount of duplicates, we dropped all row-duplicates, keeping only the first entry.
- We drop one duplicated column.
- Anomaly: all features are binary categorical features.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Malware",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="Malware",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(f"{dataset_mold.path}/data.csv")

df = df.rename(
    columns={
        "Result": "Malware",
    }
)
df["Malware"] = df["Malware"].map({0: "No", 1: "Yes"})

# Drop duplicates
df = df.drop_duplicates(keep="first")

# Map all to cat
df = df.astype("category")

# Drop duplicated col
df = df.drop(columns=["me.everything.badger.permission.BADGE_COUNT_READ"])

# Data is ordered, thus dist shift for original order. Shuffling the data removes this.
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 7,491
Columns: 86
Use sampling: False (sample size: 7,491)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['android.permission.GET_ACCOUNTS', 'com.sonyericsson.home.permission.BROADCAST_BADGE', 'android.permission.READ_PROFILE', 'android.permission.MANAGE_ACCOUNTS', 'android.permission.WRITE_SYNC_SETTINGS', 'android.permission.READ_EXTERNAL_STORAGE', 'android.permission.RECEIVE_SMS', 'com.android.launcher.permission.READ_SETTINGS', 'android.permission.WRITE_SETTINGS', 'com.google.android.providers.gsf.permission.READ_GSERVICES']
Rows remaining as candidates after top-10 filter: 7,422 (of 7,491)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 96 (1.28% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,android.permission.GET_ACCOUNTS,com.sonyericsson.home.permission.BROADCAST_BADGE,android.permission.READ_PROFILE,android.permission.MANAGE_ACCOUNTS,android.permission.WRITE_SYNC_SETTINGS,android.permission.READ_EXTERNAL_STORAGE,android.permission.RECEIVE_SMS,com.android.launcher.permission.READ_SETTINGS,android.permission.WRITE_SETTINGS,com.google.android.providers.gsf.permission.READ_GSERVICES,android.permission.DOWNLOAD_WITHOUT_NOTIFICATION,android.permission.GET_TASKS,android.permission.WRITE_EXTERNAL_STORAGE,android.permission.RECORD_AUDIO,com.huawei.android.launcher.permission.CHANGE_BADGE,com.oppo.launcher.permission.READ_SETTINGS,android.permission.CHANGE_NETWORK_STATE,com.android.launcher.permission.INSTALL_SHORTCUT,android.permission.android.permission.READ_PHONE_STATE,android.permission.CALL_PHONE,android.permission.WRITE_CONTACTS,android.permission.READ_PHONE_STATE,com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY,android.permission.MODIFY_AUDIO_SETTINGS,android.permission.ACCESS_LOCATION_EXTRA_COMMANDS,android.permission.INTERNET,android.permission.MOUNT_UNMOUNT_FILESYSTEMS,com.majeur.launcher.permission.UPDATE_BADGE,android.permission.AUTHENTICATE_ACCOUNTS,com.htc.launcher.permission.READ_SETTINGS,android.permission.ACCESS_WIFI_STATE,android.permission.FLASHLIGHT,android.permission.READ_APP_BADGE,android.permission.USE_CREDENTIALS,android.permission.CHANGE_CONFIGURATION,android.permission.READ_SYNC_SETTINGS,android.permission.BROADCAST_STICKY,com.anddoes.launcher.permission.UPDATE_COUNT,com.android.alarm.permission.SET_ALARM,com.google.android.c2dm.permission.RECEIVE,android.permission.KILL_BACKGROUND_PROCESSES,com.sonymobile.home.permission.PROVIDER_INSERT_BADGE,com.sec.android.provider.badge.permission.READ,android.permission.WRITE_CALENDAR,android.permission.SEND_SMS,com.huawei.android.launcher.permission.WRITE_SETTINGS,android.permission.REQUEST_INSTALL_PACKAGES,android.permission.SET_WALLPAPER_HINTS,android.permission.SET_WALLPAPER,com.oppo.launcher.permission.WRITE_SETTINGS,android.permission.RESTART_PACKAGES,me.everything.badger.permission.BADGE_COUNT_WRITE,android.permission.ACCESS_MOCK_LOCATION,android.permission.ACCESS_COARSE_LOCATION,android.permission.READ_LOGS,com.google.android.gms.permission.ACTIVITY_RECOGNITION,com.amazon.device.messaging.permission.RECEIVE,android.permission.SYSTEM_ALERT_WINDOW,android.permission.DISABLE_KEYGUARD,android.permission.USE_FINGERPRINT,android.permission.CHANGE_WIFI_STATE,android.permission.READ_CONTACTS,com.android.vending.BILLING,android.permission.READ_CALENDAR,android.permission.RECEIVE_BOOT_COMPLETED,android.permission.WAKE_LOCK,android.permission.ACCESS_FINE_LOCATION,android.permission.BLUETOOTH,android.permission.CAMERA,com.android.vending.CHECK_LICENSE,android.permission.FOREGROUND_SERVICE,android.permission.BLUETOOTH_ADMIN,android.permission.VIBRATE,android.permission.NFC,android.permission.RECEIVE_USER_PRESENT,android.permission.CLEAR_APP_CACHE,com.android.launcher.permission.UNINSTALL_SHORTCUT,com.sec.android.iap.permission.BILLING,com.htc.launcher.permission.UPDATE_SHORTCUT,com.sec.android.provider.badge.permission.WRITE,android.permission.ACCESS_NETWORK_STATE,com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE,com.huawei.android.launcher.permission.READ_SETTINGS,android.permission.READ_SMS,android.permission.PROCESS_INCOMING_CALLS,Malware
0,0,1,1,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,0,1,1,1,0,0,1,0,No
1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,No
2,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,No
3,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Yes
4,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,Yes

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,android.permission.GET_ACCOUNTS,category,0.0,0.0,2.0,"0, 1"
1,com.sonyericsson.home.permission.BROADCAST_BADGE,category,0.0,0.0,2.0,"0, 1"
2,android.permission.READ_PROFILE,category,0.0,0.0,2.0,"0, 1"
3,android.permission.MANAGE_ACCOUNTS,category,0.0,0.0,2.0,"0, 1"
4,android.permission.WRITE_SYNC_SETTINGS,category,0.0,0.0,2.0,"0, 1"
5,android.permission.READ_EXTERNAL_STORAGE,category,0.0,0.0,2.0,"0, 1"
6,android.permission.RECEIVE_SMS,category,0.0,0.0,2.0,"0, 1"
7,com.android.launcher.permission.READ_SETTINGS,category,0.0,0.0,2.0,"0, 1"
8,android.permission.WRITE_SETTINGS,category,0.0,0.0,2.0,"0, 1"
9,com.google.android.providers.gsf.permission.READ_GSERVICES,category,0.0,0.0,2.0,"0, 1"
10,android.permission.DOWNLOAD_WITHOUT_NOTIFICATION,category,0.0,0.0,2.0,"0, 1"
11,android.permission.GET_TASKS,category,0.0,0.0,2.0,"0, 1"
12,android.permission.WRITE_EXTERNAL_STORAGE,category,0.0,0.0,2.0,"1, 0"
13,android.permission.RECORD_AUDIO,category,0.0,0.0,2.0,"0, 1"
14,com.huawei.android.launcher.permission.CHANGE_BADGE,category,0.0,0.0,2.0,"0, 1"
15,com.oppo.launcher.permission.READ_SETTINGS,category,0.0,0.0,2.0,"0, 1"
16,android.permission.CHANGE_NETWORK_STATE,category,0.0,0.0,2.0,"0, 1"
17,com.android.launcher.permission.INSTALL_SHORTCUT,category,0.0,0.0,2.0,"0, 1"
18,android.permission.android.permission.READ_PHONE_STATE,category,0.0,0.0,2.0,"0, 1"
19,android.permission.CALL_PHONE,category,0.0,0.0,2.0,"0, 1"
20,android.permission.WRITE_CONTACTS,category,0.0,0.0,2.0,"0, 1"
21,android.permission.READ_PHONE_STATE,category,0.0,0.0,2.0,"1, 0"
22,com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY,category,0.0,0.0,2.0,"0, 1"
23,android.permission.MODIFY_AUDIO_SETTINGS,category,0.0,0.0,2.0,"0, 1"
24,android.permission.ACCESS_LOCATION_EXTRA_COMMANDS,category,0.0,0.0,2.0,"0, 1"
25,android.permission.INTERNET,category,0.0,0.0,2.0,"1, 0"
26,android.permission.MOUNT_UNMOUNT_FILESYSTEMS,category,0.0,0.0,2.0,"0, 1"
27,com.majeur.launcher.permission.UPDATE_BADGE,category,0.0,0.0,2.0,"0, 1"
28,android.permission.AUTHENTICATE_ACCOUNTS,category,0.0,0.0,2.0,"0, 1"
29,com.htc.launcher.permission.READ_SETTINGS,category,0.0,0.0,2.0,"0, 1"
30,android.permission.ACCESS_WIFI_STATE,category,0.0,0.0,2.0,"1, 0"
31,android.permission.FLASHLIGHT,category,0.0,0.0,2.0,"0, 1"
32,android.permission.READ_APP_BADGE,category,0.0,0.0,2.0,"0, 1"
33,android.permission.USE_CREDENTIALS,category,0.0,0.0,2.0,"0, 1"
34,android.permission.CHANGE_CONFIGURATION,category,0.0,0.0,2.0,"0, 1"
35,android.permission.READ_SYNC_SETTINGS,category,0.0,0.0,2.0,"0, 1"
36,android.permission.BROADCAST_STICKY,category,0.0,0.0,2.0,"0, 1"
37,com.anddoes.launcher.permission.UPDATE_COUNT,category,0.0,0.0,2.0,"0, 1"
38,com.android.alarm.permission.SET_ALARM,category,0.0,0.0,2.0,"0, 1"
39,com.google.android.c2dm.permission.RECEIVE,category,0.0,0.0,2.0,"0, 1"
40,android.permission.KILL_BACKGROUND_PROCESSES,category,0.0,0.0,2.0,"0, 1"
41,com.sonymobile.home.permission.PROVIDER_INSERT_BADGE,category,0.0,0.0,2.0,"0, 1"
42,com.sec.android.provider.badge.permission.READ,category,0.0,0.0,2.0,"0, 1"
43,android.permission.WRITE_CALENDAR,category,0.0,0.0,2.0,"0, 1"
44,android.permission.SEND_SMS,category,0.0,0.0,2.0,"0, 1"
45,com.huawei.android.launcher.permission.WRITE_SETTINGS,category,0.0,0.0,2.0,"0, 1"
46,android.permission.REQUEST_INSTALL_PACKAGES,category,0.0,0.0,2.0,"0, 1"
47,android.permission.SET_WALLPAPER_HINTS,category,0.0,0.0,2.0,"0, 1"
48,android.permission.SET_WALLPAPER,category,0.0,0.0,2.0,"0, 1"
49,com.oppo.launcher.permission.WRITE_SETTINGS,category,0.0,0.0,2.0,"0, 1"
50,android.permission.RESTART_PACKAGES,category,0.0,0.0,2.0,"0, 1"
51,me.everything.badger.permission.BADGE_COUNT_WRITE,category,0.0,0.0,2.0,"0, 1"
52,android.permission.ACCESS_MOCK_LOCATION,category,0.0,0.0,2.0,"0, 1"
53,android.permission.ACCESS_COARSE_LOCATION,category,0.0,0.0,2.0,"0, 1"
54,android.permission.READ_LOGS,category,0.0,0.0,2.0,"0, 1"
55,com.google.android.gms.permission.ACTIVITY_RECOGNITION,category,0.0,0.0,2.0,"0, 1"
56,com.amazon.device.messaging.permission.RECEIVE,category,0.0,0.0,2.0,"0, 1"
57,android.permission.SYSTEM_ALERT_WINDOW,category,0.0,0.0,2.0,"0, 1"
58,android.permission.DISABLE_KEYGUARD,category,0.0,0.0,2.0,"0, 1"
59,android.permission.USE_FINGERPRINT,category,0.0,0.0,2.0,"0, 1"
60,android.permission.CHANGE_WIFI_STATE,category,0.0,0.0,2.0,"0, 1"
61,android.permission.READ_CONTACTS,category,0.0,0.0,2.0,"0, 1"
62,com.android.vending.BILLING,category,0.0,0.0,2.0,"0, 1"
63,android.permission.READ_CALENDAR,category,0.0,0.0,2.0,"0, 1"
64,android.permission.RECEIVE_BOOT_COMPLETED,category,0.0,0.0,2.0,"0, 1"
65,android.permission.WAKE_LOCK,category,0.0,0.0,2.0,"1, 0"
66,android.permission.ACCESS_FINE_LOCATION,category,0.0,0.0,2.0,"0, 1"
67,android.permission.BLUETOOTH,category,0.0,0.0,2.0,"0, 1"
68,android.permission.CAMERA,category,0.0,0.0,2.0,"0, 1"
69,com.android.vending.CHECK_LICENSE,category,0.0,0.0,2.0,"0, 1"
70,android.permission.FOREGROUND_SERVICE,category,0.0,0.0,2.0,"0, 1"
71,android.permission.BLUETOOTH_ADMIN,category,0.0,0.0,2.0,"0, 1"
72,android.permission.VIBRATE,category,0.0,0.0,2.0,"1, 0"
73,android.permission.NFC,category,0.0,0.0,2.0,"0, 1"
74,android.permission.RECEIVE_USER_PRESENT,category,0.0,0.0,2.0,"0, 1"
75,android.permission.CLEAR_APP_CACHE,category,0.0,0.0,2.0,"0, 1"
76,com.android.launcher.permission.UNINSTALL_SHORTCUT,category,0.0,0.0,2.0,"0, 1"
77,com.sec.android.iap.permission.BILLING,category,0.0,0.0,2.0,"0, 1"
78,com.htc.launcher.permission.UPDATE_SHORTCUT,category,0.0,0.0,2.0,"0, 1"
79,com.sec.android.provider.badge.permission.WRITE,category,0.0,0.0,2.0,"0, 1"
80,android.permission.ACCESS_NETWORK_STATE,category,0.0,0.0,2.0,"1, 0"
81,com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE,category,0.0,0.0,2.0,"0, 1"
82,com.huawei.android.launcher.permission.READ_SETTINGS,category,0.0,0.0,2.0,"0, 1"
83,android.permission.READ_SMS,category,0.0,0.0,2.0,"0, 1"
84,android.permission.PROCESS_INCOMING_CALLS,category,0.0,0.0,2.0,"0, 1"
85,Malware,category,0.0,0.0,2.0,"No, Yes"

In [6]:
# Numeric Feature Statistics
numeric_stats

'No numeric features to summarize.'

In [7]:
# Categorical Feature Statistics
cat_stats

                                                                                   value  \
column                                                                        rank
Malware                                                                       1       No
                                                                              2      Yes
android.permission.ACCESS_COARSE_LOCATION                                     1        0
                                                                              2        1
android.permission.ACCESS_FINE_LOCATION                                       1        0
                                                                              2        1
android.permission.ACCESS_LOCATION_EXTRA_COMMANDS                             1        0
                                                                              2        1
android.permission.ACCESS_MOCK_LOCATION                                       1        0
                                                                              2        1
android.permission.ACCESS_NETWORK_STATE                                       1        1
                                                                              2        0
android.permission.ACCESS_WIFI_STATE                                          1        1
                                                                              2        0
android.permission.AUTHENTICATE_ACCOUNTS                                      1        0
                                                                              2        1
android.permission.BLUETOOTH                                                  1        0
                                                                              2        1
android.permission.BLUETOOTH_ADMIN                                            1        0
                                                                              2        1
android.permission.BROADCAST_STICKY                                           1        0
                                                                              2        1
android.permission.CALL_PHONE                                                 1        0
                                                                              2        1
android.permission.CAMERA                                                     1        0
                                                                              2        1
android.permission.CHANGE_CONFIGURATION                                       1        0
                                                                              2        1
android.permission.CHANGE_NETWORK_STATE                                       1        0
                                                                              2        1
android.permission.CHANGE_WIFI_STATE                                          1        0
                                                                              2        1
android.permission.CLEAR_APP_CACHE                                            1        0
                                                                              2        1
android.permission.DISABLE_KEYGUARD                                           1        0
                                                                              2        1
android.permission.DOWNLOAD_WITHOUT_NOTIFICATION                              1        0
                                                                              2        1
android.permission.FLASHLIGHT                                                 1        0
                                                                              2        1
android.permission.FOREGROUND_SERVICE                                         1        0
                                                                              2        1
android.permission.GET_ACCOUNTS                                               1        0
                                                                              2        1
android.permission.GET_TASKS                                                  1        0
                                                                              2        1
android.permission.INTERNET                                                   1        1
                                                                              2        0
android.permission.KILL_BACKGROUND_PROCESSES                                  1        0
                                                                              2        1
android.permission.MANAGE_ACCOUNTS                                            1        0
                                                                              2        1
android.permission.MODIFY_AUDIO_SETTINGS                                      1        0
                                                                              2        1
android.permission.MOUNT_UNMOUNT_FILESYSTEMS                                  1        0
                                                                              2        1
android.permission.NFC                                                        1        0
                                                                              2        1
android.permission.PROCESS_INCOMING_CALLS                                     1        0
                                                                              2        1
android.permission.READ_APP_BADGE                                             1        0
                                                                              2        1
android.permission.READ_CALENDAR                                              1        0
                                                                              2        1
android.permission.READ_CONTACTS                                              1        0
                                                                              2        1
android.permission.READ_EXTERNAL_STORAGE                                      1        0
                                                                              2        1
android.permission.READ_LOGS                                                  1        0
                                                                              2        1
android.permission.READ_PHONE_STATE                                           1        1
                                                                              2        0
android.permission.READ_PROFILE                                               1        0
                                                                              2        1
android.permission.READ_SMS                                                   1        0
                                                                              2        1
android.permission.READ_SYNC_SETTINGS                                         1        0
                                                                              2        1
android.permission.RECEIVE_BOOT_COMPLETED                                     1        0
                                                                              2        1
android.permission.RECEIVE_SMS                                                1        0
                                                                              2        1
android.permission.RECEIVE_USER_PRESENT                                       1        0
                                                                              2        1
android.permission.RECORD_AUDIO                                               1        0
                                                                              2        1
android.permission.REQUEST_INSTALL_PACKAGES                                   1        0
                                                                              2        1
android.permission.RESTART_PACKAGES                                           1        0
                                                                              2        1
android.permission.SEND_SMS                                                   1        0
                                                                              2        1
android.permission.SET_WALLPAPER                                              1        0
                                                                              2        1
android.permission.SET_WALLPAPER_HINTS                                        1        0
                                                                              2        1
android.permission.SYSTEM_ALERT_WINDOW                                        1        0
                                                                              2        1
android.permission.USE_CREDENTIALS                                            1        0
                                                                              2        1
android.permission.USE_FINGERPRINT                                            1        0
                                                                              2        1
android.permission.VIBRATE                                                    1        1
                                                                              2        0
android.permission.WAKE_LOCK                                                  1        1
                                                                              2        0
android.permission.WRITE_CALENDAR                                             1        0
                                                                              2        1
android.permission.WRITE_CONTACTS                                             1        0
                                                                              2        1
android.permission.WRITE_EXTERNAL_STORAGE                                     1        1
                                                                              2        0
android.permission.WRITE_SETTINGS                                             1        0
                                                                              2        1
android.permission.WRITE_SYNC_SETTINGS                                        1        0
                                                                              2        1
android.permission.android.permission.READ_PHONE_STATE                        1        0
                                                                              2        1
com.amazon.device.messaging.permission.RECEIVE                                1        0
                                                                              2        1
com.anddoes.launcher.permission.UPDATE_COUNT                                  1        0
                                                                              2        1
com.android.alarm.permission.SET_ALARM                                        1        0
                                                                              2        1
com.android.launcher.permission.INSTALL_SHORTCUT                              1        0
                                                                              2        1
com.android.launcher.permission.READ_SETTINGS                                 1        0
                                                                              2        1
com.android.launcher.permission.UNINSTALL_SHORTCUT                            1        0
                                                                              2        1
com.android.vending.BILLING                                                   1        0
                                                                              2        1
com.android.vending.CHECK_LICENSE                                             1        0
                                                                              2        1
com.google.android.c2dm.permission.RECEIVE                                    1        0
                                                                              2        1
com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE        1        0
                                                                              2        1
com.google.android.gms.permission.ACTIVITY_RECOGNITION                        1        0
                                                                              2        1
com.google.android.providers.gsf.permission.READ_GSERVICES                    1        0
                                                                              2        1
com.htc.launcher.permission.READ_SETTINGS                                     1        0
                                                                              2        1
com.htc.launcher.permission.UPDATE_SHORTCUT                                   1        0
                                                                              2        1
com.huawei.android.launcher.permission.CHANGE_BADGE                           1        0
                                                                              2        1
com.huawei.android.launcher.permission.READ_SETTINGS                          1        0
                                                                              2        1
com.huawei.android.launcher.permission.WRITE_SETTINGS                         1        0
                                                                              2        1
com.majeur.launcher.permission.UPDATE_BADGE                                   1        0
                                                                              2        1
com.oppo.launcher.permission.READ_SETTINGS                                    1        0
                                                                              2        1
com.oppo.launcher.permission.WRITE_SETTINGS                                   1        0
                                                                              2        1
com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY 1        0
                                                                              2        1
com.sec.android.iap.permission.BILLING                                        1        0
                                                                              2        1
com.sec.android.provider.badge.permission.READ                                1        0
                                                                              2        1
com.sec.android.provider.badge.permission.WRITE                               1        0
                                                                              2        1
com.sonyericsson.home.permission.BROADCAST_BADGE                              1        0
                                                                              2        1
com.sonymobile.home.permission.PROVIDER_INSERT_BADGE                          1        0
                                                                              2        1
me.everything.badger.permission.BADGE_COUNT_WRITE                             1        0
                                                                              2        1

                                                                                    count  \
column                                                                        rank
Malware                                                                       1      4867
                                                                              2      2624
android.permission.ACCESS_COARSE_LOCATION                                     1      3894
                                                                              2      3597
android.permission.ACCESS_FINE_LOCATION                                       1      3934
                                                                              2      3557
android.permission.ACCESS_LOCATION_EXTRA_COMMANDS                             1      7003
                                                                              2       488
android.permission.ACCESS_MOCK_LOCATION                                       1      7308
                                                                              2       183
android.permission.ACCESS_NETWORK_STATE                                       1      7219
                                                                              2       272
android.permission.ACCESS_WIFI_STATE                                          1      4770
                                                                              2      2721
android.permission.AUTHENTICATE_ACCOUNTS                                      1      7318
                                                                              2       173
android.permission.BLUETOOTH                                                  1      6746
                                                                              2       745
android.permission.BLUETOOTH_ADMIN                                            1      6961
                                                                              2       530
android.permission.BROADCAST_STICKY                                           1      7286
                                                                              2       205
android.permission.CALL_PHONE                                                 1      6756
                                                                              2       735
android.permission.CAMERA                                                     1      5750
                                                                              2      1741
android.permission.CHANGE_CONFIGURATION                                       1      7349
                                                                              2       142
android.permission.CHANGE_NETWORK_STATE                                       1      6935
                                                                              2       556
android.permission.CHANGE_WIFI_STATE                                          1      6437
                                                                              2      1054
android.permission.CLEAR_APP_CACHE                                            1      7374
                                                                              2       117
android.permission.DISABLE_KEYGUARD                                           1      7067
                                                                              2       424
android.permission.DOWNLOAD_WITHOUT_NOTIFICATION                              1      7288
                                                                              2       203
android.permission.FLASHLIGHT                                                 1      6958
                                                                              2       533
android.permission.FOREGROUND_SERVICE                                         1      7413
                                                                              2        78
android.permission.GET_ACCOUNTS                                               1      5085
                                                                              2      2406
android.permission.GET_TASKS                                                  1      5513
                                                                              2      1978
android.permission.INTERNET                                                   1      7411
                                                                              2        80

In [8]:
# Target Distribution
target_df

         count    pct
Malware
No        4867  64.97
Yes       2624  35.03

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to naticusdroid_android_permissions_dataset/019d7368-f37d-77e2-be2e-0d8d94e9c27d
019d7368-f37d-77e2-be2e-0d8d94e9c27d
216f8eb48ecfb91dcc0e510a0410e7afb4faa4090f54e6c543ffac2283556cc2