### Dataset and Task Metadata

In [15]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="acquire_valued_shoppers_challenge",
    dataset_year="2014",
    domain_str="business & marketing",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/c/acquire-valued-shoppers-challenge",
    download_description="""
We start with the data from Kaggle.

kaggle competitions download -c acquire-valued-shoppers-challenge
mkdir -p local-data-warehouse/acquire_valued_shoppers_challenge && mv acquire-valued-shoppers-challenge.zip local-data-warehouse/acquire_valued_shoppers_challenge/ && cd local-data-warehouse/acquire_valued_shoppers_challenge/ && unzip acquire-valued-shoppers-challenge.zip && rm acquire-valued-shoppers-challenge.zip testHistory.csv.gz sampleSubmission.csv.gz
""",
    # References
    academic_reference_bibtex=r"""@misc{DMDave2014AcquireValuedShoppersChallenge,
  author = {DMDave and Todd B and Will Cukierski},
  title  = {Acquire Valued Shoppers Challenge},
  year   = {2014},
  howpublished = {\url{https://kaggle.com/competitions/acquire-valued-shoppers-challenge}},
  note   = {Kaggle competition}
}
""",
    academic_reference_bibtex_key="DMDave2014AcquireValuedShoppersChallenge",
    licence="Kaggle Competition Rules",
    data_tags=["Non-IID", "Temporal", "Anonymized"],
    curation_comments="""
We follow the preprocessing from TabRed https://github.com/yandex-research/tabred/tree/main/preprocessing#ecom-offers-acquire-valued-shoppers-by-dmdave (which follows a top solution https://github.com/MLWave/kaggle_acquire-valued-shoppers-challenge).

- The preprocessing by TabRed collapses customer groups into single entries per customer. So we go from grouped-temporal data to only temporal data. Future work could look into a version without preprocessing.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="target",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="target",
    time_on="offerdate"
)

## Preprocessing

To start the processing for this dataset, first run the `run_large_data_preprocessing.py` script outside of this notebook to get the initial state of the dataset from which we are starting the curation. This is mostly done to be able to handle the large amount of data.

In [28]:
import pandas as pd
import numpy as np

df = pd.read_parquet(dataset_mold.path / "merged_input_data.parquet")
print(df.shape)

# Add binary columns again
binary_df = (
    df.assign(
        **{f"never_bought_{c}": (df[f"has_bought_{c}"] == 0)
           for c in ["company", "category", "brand"]},

        has_bought_brand_company_category=(
            (df["has_bought_brand"] != 0)
            & (df["has_bought_category"] != 0)
            & (df["has_bought_company"] != 0)
        ),

        has_bought_brand_category=(
            (df["has_bought_brand"] != 0)
            & (df["has_bought_category"] != 0)
        ),

        has_bought_brand_company=(
            (df["has_bought_brand"] != 0)
            & (df["has_bought_company"] != 0)
        ),
    )[
        [
            "never_bought_company",
            "never_bought_category",
            "never_bought_brand",
            "has_bought_brand_company_category",
            "has_bought_brand_category",
            "has_bought_brand_company",
        ]
    ]
    .astype(np.float32)
)
df = pd.concat([df, binary_df], axis=1)
del binary_df

cat_columns = [
    "target",
    "never_bought_company",
    "never_bought_category",
    "never_bought_brand",
    "has_bought_brand_company_category",
    "has_bought_brand_category",
    "has_bought_brand_company",
]
df[cat_columns] = df[cat_columns].astype("category")

df["offerdate"] = pd.to_datetime(df["offerdate"], format="%Y-%m-%d")
df = df.drop(columns=["id"])


df = df.drop(columns=[
    # Duplicated column
    "has_bought_company_q_1",
    "has_bought_company_a_1",
    "has_bought_category_1",
    "has_bought_category_q_1",
    "has_bought_category_a_1",
    "has_bought_brand_1",
    "has_bought_brand_q_1",
    "has_bought_brand_a_1",
    # Constant column
    "has_bought_company_1"
])

df = df.reset_index(drop=True)

(160057, 116)

## Data Checks

In [29]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 160,057
Columns: 112

#### Duplicate Report
Total duplicate rows: 23 (0.01% of dataset)
Duplicate rows ignoring target: 30 (0.02% of dataset)
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [30]:
# Sample Rows
df_head

,total_spend,target,offervalue,offerdate,day_of_week,day_of_month,day_of_year,has_bought_company,has_bought_company_q,has_bought_company_a,has_bought_category,has_bought_category_q,has_bought_category_a,has_bought_brand,has_bought_brand_q,has_bought_brand_a,has_bought_company_3,has_bought_company_q_3,has_bought_company_a_3,has_bought_category_3,has_bought_category_q_3,has_bought_category_a_3,has_bought_brand_3,has_bought_brand_q_3,has_bought_brand_a_3,has_bought_company_7,has_bought_company_q_7,has_bought_company_a_7,has_bought_category_7,has_bought_category_q_7,has_bought_category_a_7,has_bought_brand_7,has_bought_brand_q_7,has_bought_brand_a_7,has_bought_company_14,has_bought_company_q_14,has_bought_company_a_14,has_bought_category_14,has_bought_category_q_14,has_bought_category_a_14,has_bought_brand_14,has_bought_brand_q_14,has_bought_brand_a_14,has_bought_company_21,has_bought_company_q_21,has_bought_company_a_21,has_bought_category_21,has_bought_category_q_21,has_bought_category_a_21,has_bought_brand_21,has_bought_brand_q_21,has_bought_brand_a_21,has_bought_company_28,has_bought_company_q_28,has_bought_company_a_28,has_bought_category_28,has_bought_category_q_28,has_bought_category_a_28,has_bought_brand_28,has_bought_brand_q_28,has_bought_brand_a_28,has_bought_company_60,has_bought_company_q_60,has_bought_company_a_60,has_bought_category_60,has_bought_category_q_60,has_bought_category_a_60,has_bought_brand_60,has_bought_brand_q_60,has_bought_brand_a_60,has_bought_company_90,has_bought_company_q_90,has_bought_company_a_90,has_bought_category_90,has_bought_category_q_90,has_bought_category_a_90,has_bought_brand_90,has_bought_brand_q_90,has_bought_brand_a_90,has_bought_company_120,has_bought_company_q_120,has_bought_company_a_120,has_bought_category_120,has_bought_category_q_120,has_bought_category_a_120,has_bought_brand_120,has_bought_brand_q_120,has_bought_brand_a_120,has_bought_company_150,has_bought_company_q_150,has_bought_company_a_150,has_bought_category_150,has_bought_category_q_150,has_bought_category_a_150,has_bought_brand_150,has_bought_brand_q_150,has_bought_brand_a_150,has_bought_company_180,has_bought_company_q_180,has_bought_company_a_180,has_bought_category_180,has_bought_category_q_180,has_bought_category_a_180,has_bought_brand_180,has_bought_brand_q_180,has_bought_brand_a_180,never_bought_company,never_bought_category,never_bought_brand,has_bought_brand_company_category,has_bought_brand_category,has_bought_brand_company
0,932.85,1,1.0,2013-03-01,5,1,60,0,0.0,0.0,1,1.0,0.99,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1,738.84,0,1.0,2013-03-01,5,1,60,0,0.0,0.0,1,1.0,1.58,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2,3779.94,1,1.0,2013-03-01,5,1,60,0,0.0,0.0,3,3.0,10.19,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,1342.25,1,1.0,2013-03-01,5,1,60,0,0.0,0.0,3,3.0,4.95,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4,1391.65,1,1.0,2013-03-01,5,1,60,0,0.0,0.0,1,1.0,1.57,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0

In [31]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,target,category,0,0.0,2,"0, 1"
1,never_bought_company,category,0,0.0,2,"0.0, 1.0"
2,never_bought_category,category,0,0.0,2,"0.0, 1.0"
3,never_bought_brand,category,0,0.0,2,"1.0, 0.0"
4,has_bought_brand_company_category,category,0,0.0,2,"0.0, 1.0"
5,has_bought_brand_category,category,0,0.0,2,"0.0, 1.0"
6,has_bought_brand_company,category,0,0.0,2,"0.0, 1.0"
7,offerdate,datetime64[ns],0,0.0,56,"2013-03-25 00:00:00, 2013-03-26 00:00:00, 2013-04-24 00:00:00, 2013-03-27 00:00:00, 2013-04-23 00:00:00, 2013-04-25 00:00:00, 2013-04-01 00:00:00, 2013-04-26 00:00:00, 2013-03-30 00:00:00, 2013-04-22 00:00:00"
8,total_spend,float64,0,0.0,147140,"712.46, 5336.51, 1372.02, 2595.74, 2253.76, 1135.9, 783.61, 4347.78, 6058.08, 1817.89"
9,offervalue,float64,0,0.0,6,"1.0, 0.75, 2.0, 1.5, 1.25, 3.0"
10,has_bought_company_q,float64,0,0.0,284,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
11,has_bought_company_a,float64,0,0.0,14128,"0.0, 2.0, 2.99, 1.0, 3.99, 3.0, 4.0, 4.99, 5.0, 1.99"
12,has_bought_category_q,float64,0,0.0,365,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
13,has_bought_category_a,float64,0,0.0,20163,"0.0, 2.99, 3.99, 1.99, 3.49, 4.99, 2.49, 2.79, 5.98, 5.99"
14,has_bought_brand_q,float64,0,0.0,227,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
15,has_bought_brand_a,float64,0,0.0,12964,"0.0, 3.99, 2.99, 3.49, 4.29, 3.0, 4.99, 4.5, 5.99, 5.0"
16,has_bought_company_q_3,float64,0,0.0,25,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 8.0, 6.0, 7.0, 10.0"
17,has_bought_company_a_3,float64,0,0.0,327,"0.0, 3.99, 4.99, 3.0, 2.99, 3.49, 4.0, 1.0, 4.49, 5.99"
18,has_bought_category_q_3,float64,0,0.0,25,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 10.0, 8.0"
19,has_bought_category_a_3,float64,0,0.0,369,"0.0, 2.99, 4.99, 3.99, 2.5, 3.49, 5.99, 5.0, 3.69, 1.99"
20,has_bought_brand_q_3,float64,0,0.0,23,"0.0, 1.0, 2.0, 3.0, 4.0, 6.0, 5.0, 7.0, 8.0, 10.0"
21,has_bought_brand_a_3,float64,0,0.0,279,"0.0, 3.99, 2.99, 3.49, 5.0, 4.99, 3.0, 2.5, 4.29, 4.49"
22,has_bought_company_q_7,float64,0,0.0,39,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0"
23,has_bought_company_a_7,float64,0,0.0,855,"0.0, 3.99, 4.99, 2.99, 3.0, 3.49, 2.0, 4.0, 1.99, 1.0"
24,has_bought_category_q_7,float64,0,0.0,41,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0"
25,has_bought_category_a_7,float64,0,0.0,890,"0.0, 4.99, 2.99, 3.99, 3.69, 3.49, 2.5, 5.99, 2.79, 3.0"
26,has_bought_brand_q_7,float64,0,0.0,37,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
27,has_bought_brand_a_7,float64,0,0.0,682,"0.0, 3.99, 2.99, 3.49, 4.99, 3.0, 5.0, 2.5, 4.29, 3.79"
28,has_bought_company_q_14,float64,0,0.0,55,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0"
29,has_bought_company_a_14,float64,0,0.0,1615,"0.0, 3.99, 2.99, 4.99, 3.0, 2.0, 4.29, 3.49, 4.0, 1.99"
30,has_bought_category_q_14,float64,0,0.0,58,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
31,has_bought_category_a_14,float64,0,0.0,1776,"0.0, 4.99, 2.99, 3.99, 3.69, 3.49, 2.79, 5.99, 1.99, 2.5"
32,has_bought_brand_q_14,float64,0,0.0,53,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
33,has_bought_brand_a_14,float64,0,0.0,1250,"0.0, 3.99, 2.99, 3.49, 4.29, 4.99, 2.5, 3.0, 5.0, 1.99"
34,has_bought_company_q_21,float64,0,0.0,66,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0, 7.0, 10.0"
35,has_bought_company_a_21,float64,0,0.0,2268,"0.0, 3.99, 2.99, 4.29, 2.0, 4.99, 3.0, 3.49, 4.0, 1.99"
36,has_bought_category_q_21,float64,0,0.0,77,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
37,has_bought_category_a_21,float64,0,0.0,2687,"0.0, 4.99, 2.99, 3.99, 3.69, 3.49, 5.99, 1.99, 2.5, 2.79"
38,has_bought_brand_q_21,float64,0,0.0,59,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0, 7.0, 9.0"
39,has_bought_brand_a_21,float64,0,0.0,1726,"0.0, 3.99, 2.99, 4.29, 3.49, 2.5, 4.99, 5.0, 1.99, 3.0"
40,has_bought_company_q_28,float64,0,0.0,75,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0"
41,has_bought_company_a_28,float64,0,0.0,2815,"0.0, 3.99, 2.99, 3.0, 2.0, 4.29, 4.99, 3.49, 1.99, 4.0"
42,has_bought_category_q_28,float64,0,0.0,88,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
43,has_bought_category_a_28,float64,0,0.0,3510,"0.0, 4.99, 2.99, 3.99, 3.69, 3.49, 1.99, 2.5, 5.99, 3.0"
44,has_bought_brand_q_28,float64,0,0.0,65,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
45,has_bought_brand_a_28,float64,0,0.0,2300,"0.0, 3.99, 2.99, 3.49, 4.29, 3.0, 2.5, 4.99, 5.0, 1.99"
46,has_bought_company_q_60,float64,0,0.0,113,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0"
47,has_bought_company_a_60,float64,0,0.0,5026,"0.0, 3.99, 2.99, 2.0, 3.0, 4.99, 4.0, 1.0, 4.29, 1.99"
48,has_bought_category_q_60,float64,0,0.0,126,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
49,has_bought_category_a_60,float64,0,0.0,6322,"0.0, 2.99, 3.99, 4.99, 3.69, 1.99, 3.49, 5.98, 9.98, 7.98"
50,has_bought_brand_q_60,float64,0,0.0,89,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
51,has_bought_brand_a_60,float64,0,0.0,4385,"0.0, 3.99, 2.99, 6.2, 3.49, 4.29, 3.0, 4.99, 2.5, 5.0"
52,has_bought_company_q_90,float64,0,0.0,139,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0"
53,has_bought_company_a_90,float64,0,0.0,6595,"0.0, 2.0, 3.99, 2.99, 3.0, 4.99, 1.0, 4.0, 1.99, 5.0"
54,has_bought_category_q_90,float64,0,0.0,158,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
55,has_bought_category_a_90,float64,0,0.0,8241,"0.0, 2.99, 3.99, 4.99, 1.99, 3.49, 3.69, 5.98, 3.79, 2.79"
56,has_bought_brand_q_90,float64,0,0.0,107,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
57,has_bought_brand_a_90,float64,0,0.0,5792,"0.0, 2.99, 3.99, 3.49, 4.29, 4.99, 3.0, 6.2, 5.0, 5.99"
58,has_bought_company_q_120,float64,0,0.0,157,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
59,has_bought_company_a_120,float64,0,0.0,7997,"0.0, 2.0, 3.99, 2.99, 3.0, 1.0, 4.99, 4.0, 1.99, 5.0"
60,has_bought_category_q_120,float64,0,0.0,185,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
61,has_bought_category_a_120,float64,0,0.0,9922,"0.0, 2.99, 3.99, 4.99, 1.99, 3.49, 3.69, 2.79, 3.79, 2.5"
62,has_bought_brand_q_120,float64,0,0.0,120,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
63,has_bought_brand_a_120,float64,0,0.0,7284,"0.0, 2.99, 3.99, 4.29, 3.49, 4.99, 3.0, 2.5, 5.0, 5.99"
64,has_bought_company_q_150,float64,0,0.0,176,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0"
65,has_bought_company_a_150,float64,0,0.0,9136,"0.0, 2.0, 3.99, 2.99, 3.0, 1.0, 4.99, 4.0, 1.99, 5.0"
66,has_bought_category_q_150,float64,0,0.0,207,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
67,has_bought_category_a_150,float64,0,0.0,11269,"0.0, 2.99, 3.99, 4.99, 1.99, 3.49, 2.79, 3.79, 2.5, 5.98"
68,has_bought_brand_q_150,float64,0,0.0,134,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
69,has_bought_brand_a_150,float64,0,0.0,8211,"0.0, 2.99, 3.99, 4.29, 3.49, 4.99, 3.0, 4.5, 2.5, 5.0"
70,has_bought_company_q_180,float64,0,0.0,195,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
71,has_bought_company_a_180,float64,0,0.0,10049,"0.0, 2.0, 3.99, 2.99, 1.0, 3.0, 4.0, 4.99, 5.0, 1.99"
72,has_bought_category_q_180,float64,0,0.0,229,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
73,has_bought_category_a_180,float64,0,0.0,12406,"0.0, 2.99, 3.99, 4.99, 3.49, 1.99, 2.79, 3.79, 5.98, 2.5"
74,has_bought_brand_q_180,float64,0,0.0,155,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
75,has_bought_brand_a_180,float64,0,0.0,8899,"0.0, 2.99, 3.99, 4.29, 3.49, 3.0, 4.99, 4.5, 5.0, 5.99"
76,day_of_year,int16,0,0.0,56,"84, 85, 114, 86, 113, 115, 91, 116, 89, 112"
77,day_of_week,int8,0,0.0,7,"1, 3, 2, 5, 4, 6, 7"
78,day_of_month,int8,0,0.0,31,"25, 26, 27, 28, 24, 23, 1, 29, 30, 22"
79,has_bought_company,uint32,0,0.0,163,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
80,has_bought_category,uint32,0,0.0,211,"0, 1, 2, 3, 4, 5, 6, 7, 8, 12"
81,has_bought_brand,uint32,0,0.0,153,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
82,has_bought_company_3,uint32,0,0.0,16,"0, 1, 2, 3, 4, 9, 6, 10, 7, 18"
83,has_bought_category_3,uint32,0,0.0,17,"0, 1, 2, 3, 5, 4, 8, 10, 15, 6"
84,has_bought_brand_3,uint32,0,0.0,14,"0, 1, 2, 3, 4, 5, 7, 6, 18, 21"
85,has_bought_company_7,uint32,0,0.0,24,"0, 1, 2, 3, 4, 5, 6, 16, 13, 22"
86,has_bought_category_7,uint32,0,0.0,30,"0, 1, 2, 3, 4, 5, 7, 8, 6, 18"
87,has_bought_brand_7,uint32,0,0.0,27,"0, 1, 2, 3, 4, 5, 9, 6, 12, 10"
88,has_bought_company_14,uint32,0,0.0,35,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
89,has_bought_category_14,uint32,0,0.0,44,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
90,has_bought_brand_14,uint32,0,0.0,39,"0, 1, 2, 3, 4, 5, 6, 7, 9, 10"
91,has_bought_company_21,uint32,0,0.0,39,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
92,has_bought_category_21,uint32,0,0.0,52,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
93,has_bought_brand_21,uint32,0,0.0,42,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
94,has_bought_company_28,uint32,0,0.0,48,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
95,has_bought_category_28,uint32,0,0.0,60,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
96,has_bought_brand_28,uint32,0,0.0,49,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
97,has_bought_company_60,uint32,0,0.0,70,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
98,has_bought_category_60,uint32,0,0.0,86,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
99,has_bought_brand_60,uint32,0,0.0,64,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
100,has_bought_company_90,uint32,0,0.0,80,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
101,has_bought_category_90,uint32,0,0.0,100,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
102,has_bought_brand_90,uint32,0,0.0,76,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
103,has_bought_company_120,uint32,0,0.0,94,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
104,has_bought_category_120,uint32,0,0.0,112,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
105,has_bought_brand_120,uint32,0,0.0,87,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
106,has_bought_company_150,uint32,0,0.0,106,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
107,has_bought_category_150,uint32,0,0.0,122,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
108,has_bought_brand_150,uint32,0,0.0,94,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
109,has_bought_company_180,uint32,0,0.0,114,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
110,has_bought_category_180,uint32,0,0.0,139,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
111,has_bought_brand_180,uint32,0,0.0,103,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"

In [32]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
total_spend,160057.0,5673.646505,172110.106467,-5953.67,48321663.59
offervalue,160057.0,1.255323,0.524645,0.75,3.00
day_of_week,160057.0,3.620541,1.937209,1.00,7.00
day_of_month,160057.0,19.004467,9.632905,1.00,31.00
day_of_year,160057.0,96.164966,15.090164,60.00,120.00
has_bought_company,160057.0,3.500266,31.999006,0.00,9562.00
has_bought_company_q,160057.0,6.204740,108.014206,-3.00,29585.00
has_bought_company_a,160057.0,15.003597,278.383246,-28.47,90477.57
has_bought_category,160057.0,5.715027,33.779835,0.00,6244.00
has_bought_category_q,160057.0,8.628664,106.847771,-1.00,33992.00
has_bought_category_a,160057.0,27.948584,350.241804,-85.14,76002.71
has_bought_brand,160057.0,2.935179,24.747696,0.00,5415.00
has_bought_brand_q,160057.0,4.195687,62.295795,-1.00,14227.00
has_bought_brand_a,160057.0,12.702787,178.250164,-14.85,44534.01
has_bought_company_3,160057.0,0.008078,0.179700,0.00,40.00
has_bought_company_q_3,160057.0,0.013564,0.458747,0.00,116.00
has_bought_company_a_3,160057.0,0.037428,1.213023,-7.55,292.87
has_bought_category_3,160057.0,0.012439,0.249484,0.00,54.00
has_bought_category_q_3,160057.0,0.018356,0.459009,0.00,98.00
has_bought_category_a_3,160057.0,0.060763,1.626372,-12.98,303.94
has_bought_brand_3,160057.0,0.008072,0.161943,0.00,21.00
has_bought_brand_q_3,160057.0,0.012396,0.364623,0.00,66.00
has_bought_brand_a_3,160057.0,0.038501,1.036336,-0.31,175.94
has_bought_company_7,160057.0,0.043859,0.496779,0.00,115.00
has_bought_company_q_7,160057.0,0.071181,1.249946,-1.00,300.00
has_bought_company_a_7,160057.0,0.196626,3.365605,-7.55,894.07
has_bought_category_7,160057.0,0.060241,0.688806,0.00,149.00
has_bought_category_q_7,160057.0,0.087156,1.315882,0.00,284.00
has_bought_category_a_7,160057.0,0.286632,4.830983,-12.98,975.22
has_bought_brand_7,160057.0,0.040542,0.449518,0.00,70.00
has_bought_brand_q_7,160057.0,0.058211,0.988351,-2.00,199.00
has_bought_brand_a_7,160057.0,0.185829,2.791376,-6.39,436.06
has_bought_company_14,160057.0,0.125649,1.020373,0.00,242.00
has_bought_company_q_14,160057.0,0.203265,3.361034,-2.00,1059.00
has_bought_company_a_14,160057.0,0.559968,7.491068,-7.55,1935.27
has_bought_category_14,160057.0,0.168490,1.421959,0.00,311.00
has_bought_category_q_14,160057.0,0.241027,2.747525,-2.00,569.00
has_bought_category_a_14,160057.0,0.792840,10.227166,-11.00,2281.07
has_bought_brand_14,160057.0,0.109980,0.946272,0.00,171.00
has_bought_brand_q_14,160057.0,0.156263,2.338523,-2.00,547.00
has_bought_brand_a_14,160057.0,0.507327,6.443026,-6.39,1294.88
has_bought_company_21,160057.0,0.207901,1.575763,0.00,383.00
has_bought_company_q_21,160057.0,0.337636,5.402459,-2.00,1743.00
has_bought_company_a_21,160057.0,0.934744,11.803479,-14.99,3082.47
has_bought_category_21,160057.0,0.284530,2.236028,0.00,456.00
has_bought_category_q_21,160057.0,0.414059,4.601448,-2.00,913.00
has_bought_category_a_21,160057.0,1.367165,18.034117,-11.00,4758.89
has_bought_brand_21,160057.0,0.182635,1.483307,0.00,290.00
has_bought_brand_q_21,160057.0,0.258327,3.961158,-2.00,1121.00
has_bought_brand_a_21,160057.0,0.848226,10.884678,-6.39,2713.73
has_bought_company_28,160057.0,0.287679,2.136301,0.00,514.00
has_bought_company_q_28,160057.0,0.468158,6.799800,-2.00,2086.00
has_bought_company_a_28,160057.0,1.280007,15.829602,-14.99,4180.51
has_bought_category_28,160057.0,0.396190,3.079745,0.00,641.00
has_bought_category_q_28,160057.0,0.576532,6.630792,-2.00,1509.00
has_bought_category_a_28,160057.0,1.920785,28.351992,-29.27,8746.95
has_bought_brand_28,160057.0,0.259614,2.002861,0.00,405.00
has_bought_brand_q_28,160057.0,0.363714,5.348631,-2.00,1580.00
has_bought_brand_a_28,160057.0,1.192418,14.822008,-6.39,3820.75
has_bought_company_60,160057.0,0.652680,4.774983,0.00,1163.00
has_bought_company_q_60,160057.0,1.115009,15.731677,-9.00,4563.00
has_bought_company_a_60,160057.0,2.877372,36.932754,-28.47,9608.61
has_bought_category_60,160057.0,0.891257,6.976124,0.00,1714.00
has_bought_category_q_60,160057.0,1.308934,18.204877,-4.00,5577.00
has_bought_category_a_60,160057.0,4.372946,82.061166,-29.27,28964.48
has_bought_brand_60,160057.0,0.583717,4.264553,0.00,817.00
has_bought_brand_q_60,160057.0,0.819695,10.802649,-2.00,2940.00
has_bought_brand_a_60,160057.0,2.674713,31.878818,-11.15,7203.61
has_bought_company_90,160057.0,0.983612,7.137048,0.00,1771.00
has_bought_company_q_90,160057.0,1.719462,24.621616,-7.00,7600.00
has_bought_company_a_90,160057.0,4.301937,55.364406,-28.47,14896.51
has_bought_category_90,160057.0,1.328214,10.077632,0.00,2235.00
has_bought_category_q_90,160057.0,1.952011,24.785934,-9.00,6825.00
has_bought_category_a_90,160057.0,6.467004,106.790658,-29.27,35032.89
has_bought_brand_90,160057.0,0.837639,6.218859,0.00,1175.00
has_bought_brand_q_90,160057.0,1.176962,15.496836,-2.00,4106.00
has_bought_brand_a_90,160057.0,3.825299,45.535746,-17.33,9954.76
has_bought_company_120,160057.0,1.297238,9.443237,0.00,2409.00
has_bought_company_q_120,160057.0,2.281337,36.336862,-7.00,11966.00
has_bought_company_a_120,160057.0,5.674570,77.442129,-28.47,20895.36
has_bought_category_120,160057.0,1.746615,12.903398,0.00,2644.00
has_bought_category_q_120,160057.0,2.587397,31.093980,-9.00,7379.00
has_bought_category_a_120,160057.0,8.542833,127.580840,-29.27,37692.72
has_bought_brand_120,160057.0,1.102026,8.027254,0.00,1486.00
has_bought_brand_q_120,160057.0,1.554865,20.398841,-1.00,5113.00
has_bought_brand_a_120,160057.0,5.022015,59.047059,-17.33,12227.70
has_bought_company_150,160057.0,1.612519,11.955859,0.00,3080.00
has_bought_company_q_150,160057.0,2.867753,41.720270,-7.00,13108.00
has_bought_company_a_150,160057.0,6.985396,94.167779,-28.47,26111.66
has_bought_category_150,160057.0,2.132328,15.310032,0.00,2981.00
has_bought_category_q_150,160057.0,3.157925,37.511892,-7.00,8553.00
has_bought_category_a_150,160057.0,10.407661,154.739625,-27.38,42560.69
has_bought_brand_150,160057.0,1.332138,10.008666,0.00,1810.00
has_bought_brand_q_150,160057.0,1.874245,24.953118,-1.00,6186.00
has_bought_brand_a_150,160057.0,6.019827,72.361616,-18.01,14939.98
has_bought_company_180,160057.0,1.898973,14.531342,0.00,3788.00
has_bought_company_q_180,160057.0,3.396890,49.807707,-3.00,15450.00
has_bought_company_a_180,160057.0,8.166978,114.420656,-28.47,31883.18
has_bought_category_180,160057.0,2.510349,17.753833,0.00,3473.00
has_bought_category_q_180,160057.0,3.711353,44.283884,-6.00,10108.00
has_bought_category_a_180,160057.0,12.222047,186.948376,-85.14,51768.61
has_bought_brand_180,160057.0,1.536759,11.968087,0.00,2227.00
has_bought_brand_q_180,160057.0,2.157563,29.430165,-1.00,7033.00
has_bought_brand_a_180,160057.0,6.880611,87.147658,-19.43,18118.13

In [33]:
# Categorical Feature Statistics
cat_stats

                                                      value   count    pct
column                            rank
has_bought_brand_category         1                     0.0  123196  76.97
                                  2                     1.0   36861  23.03
has_bought_brand_company          1                     0.0  102210  63.86
                                  2                     1.0   57847  36.14
has_bought_brand_company_category 1                     0.0  126984  79.34
                                  2                     1.0   33073  20.66
never_bought_brand                1                     1.0   96906  60.54
                                  2                     0.0   63151  39.46
never_bought_category             1                     0.0   87541  54.69
                                  2                     1.0   72516  45.31
never_bought_company              1                     0.0   86741  54.19
                                  2                     1.0   73316  45.81
offerdate                         1     2013-03-25 00:00:00   10922   6.82
                                  2     2013-03-26 00:00:00    9425   5.89
                                  3     2013-04-24 00:00:00    9044   5.65
                                  4     2013-03-27 00:00:00    7896   4.93
                                  5     2013-04-23 00:00:00    7554   4.72
target                            1                       0  116619  72.86
                                  2                       1   43438  27.14

In [34]:
# Target Distribution
target_df

         count    pct
target
0       116619  72.86
1        43438  27.14

## Task Curation

In [43]:
from data_foundry.schema import PredictiveMLSplitsMetadata

splits = {}

test_days = 5 # from TabRed
n_splits = 5 # to keep a reasonable amount of train data still
date_col = task_mold.time_on

df = df.sort_values(date_col).copy()
max_date = df[date_col].max()
print("Newest date:", max_date)

for i in range(n_splits):
    test_start = max_date - pd.Timedelta(days=test_days - 1)

    test_mask = (df[date_col] >= test_start) & (df[date_col] <= max_date)
    train_mask = df[date_col] < test_start

    train_ind = df.loc[train_mask].index.tolist()
    test_ind = df.loc[test_mask].index.tolist()

    # move window backwards
    max_date = test_start - pd.Timedelta(days=1)

    splits[i] = {0: (train_ind, test_ind)}
    print(f"\n---- Split {i}:")
    print(len(train_ind), len(test_ind))
    # last date of train, first date of test
    print(df.loc[train_mask, date_col].max(), df.loc[test_mask, date_col].min())
    # target ratio
    print(
        df.loc[train_mask, task_mold.target_column_name].value_counts(normalize=True),
        df.loc[test_mask, task_mold.target_column_name].value_counts(normalize=True)
    )


splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="We create splits to simulate a model that is deployed for 5 days before being refit. Thus, we use 5 days in the test in a data split. We create 5 splits going back from the newest date and always take all data before the test period as train data.",
    splits=splits,
)

Newest date: 2013-04-30 00:00:00

---- Split 0:
140701 19356
2013-04-25 00:00:00 2013-04-26 00:00:00
target
0    0.740926
1    0.259074
Name: proportion, dtype: float64 target
0    0.639078
1    0.360922
Name: proportion, dtype: float64

---- Split 1:
110396 30305
2013-04-20 00:00:00 2013-04-21 00:00:00
target
0    0.769865
1    0.230135
Name: proportion, dtype: float64 target
0    0.635506
1    0.364494
Name: proportion, dtype: float64

---- Split 2:
105052 5344
2013-04-15 00:00:00 2013-04-16 00:00:00
target
0    0.769105
1    0.230895
Name: proportion, dtype: float64 target
0    0.784805
1    0.215195
Name: proportion, dtype: float64

---- Split 3:
102294 2758
2013-04-10 00:00:00 2013-04-11 00:00:00
target
0    0.770886
1    0.229114
Name: proportion, dtype: float64 target
0    0.703046
1    0.296954
Name: proportion, dtype: float64

---- Split 4:
90387 11907
2013-04-05 00:00:00 2013-04-06 00:00:00
target
0    0.776738
1    0.223262
Name: proportion, dtype: float64 target
0    0.726463
1    0.273537
Name: proportion, dtype: float64

## Export

In [44]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019c6611-15df-7536-8699-e24c3acb32d8
75b422375132dbc45da3521c87598e21d7a02721232a5acb274ecef10d26d180