### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="hiva_agnostic",
    dataset_year="2007",
    domain_str="chemistry & material science",
    # Data Source
    dataset_source="Other",
    # Link to apepr https://doi.org/10.1109/IJCNN.2007.4371065
    original_dataset_source_download_link="https://www.agnostic.inf.ethz.ch",
    download_description="""
We download the dataset from the challenge platform into predefined folder:
    
mkdir -p local-data-warehouse/hiva_agnostic/ && \
wget -P local-data-warehouse/hiva_agnostic/ https://www.agnostic.inf.ethz.ch/datasets/DataAgnos/HIVA.zip && \
wget -P local-data-warehouse/hiva_agnostic/ https://www.agnostic.inf.ethz.ch/datasets/ValidAgnos.zip && \
unzip local-data-warehouse/hiva_agnostic/HIVA.zip -d local-data-warehouse/hiva_agnostic/ && \
unzip local-data-warehouse/hiva_agnostic/ValidAgnos.zip -d local-data-warehouse/hiva_agnostic/ && \
rm local-data-warehouse/hiva_agnostic/HIVA.zip && \
rm local-data-warehouse/hiva_agnostic/ValidAgnos.zip
""",
    # References
    academic_reference_bibtex="""@inproceedings{guyon2007agnostic,
  author={Isabelle Guyon and Amir Saffari and Gideon Dror and Gavin Cawley},
  booktitle={2007 International Joint Conference on Neural Networks}, 
  title={Agnostic Learning vs. Prior Knowledge Challenge}, 
  year={2007},
  pages={829-834},
  doi={10.1109/IJCNN.2007.4371065}
}
""",
    academic_reference_bibtex_key="guyon2007agnostic",
    license="Public Domain",
    data_tags=["IID"],
    curation_comments="""
- We take the original data with the original labels with three classes.
- We only take the training data from the challenge, as the original labels are not available for the validation data.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="CompoundActive",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="CompoundActive",
)

## Preprocessing

In [2]:
import pandas as pd

# train data
df = pd.read_csv(dataset_mold.path / "HIVA/hiva_train.data", header=None, sep=" ")
y = pd.read_csv(dataset_mold.path / "HIVA/hiva_train.labels", header=None)
df.columns = [
    f"molecule_structure_property_{i + 1}" for i in range(len(df.columns))
]

# Remove trailing whitespace column
df = df.drop(columns=["molecule_structure_property_1618"])

target_feature = "CompoundActive"
df[target_feature] = y[0]

df = df.astype("category")

df = df.sample(frac=1, random_state=11).reset_index(drop=True)

# Drop duplicated columns
df = df.drop(columns=[
  "molecule_structure_property_710", "molecule_structure_property_1079", "molecule_structure_property_1398", "molecule_structure_property_1024", "molecule_structure_property_829", "molecule_structure_property_1615", "molecule_structure_property_724", "molecule_structure_property_732", "molecule_structure_property_410", "molecule_structure_property_509", "molecule_structure_property_1035", "molecule_structure_property_811", "molecule_structure_property_686", "molecule_structure_property_1386", "molecule_structure_property_59", "molecule_structure_property_1493", "molecule_structure_property_542", "molecule_structure_property_1500", "molecule_structure_property_376", "molecule_structure_property_765", "molecule_structure_property_970", "molecule_structure_property_1011", "molecule_structure_property_1127", "molecule_structure_property_701", "molecule_structure_property_1114", "molecule_structure_property_1390", "molecule_structure_property_1194", "molecule_structure_property_925", "molecule_structure_property_797", "molecule_structure_property_1373", "molecule_structure_property_1223", "molecule_structure_property_1457", "molecule_structure_property_1342", "molecule_structure_property_1314", "molecule_structure_property_1272", "molecule_structure_property_1322", "molecule_structure_property_1576", "molecule_structure_property_633", "molecule_structure_property_1430", "molecule_structure_property_574", "molecule_structure_property_519", "molecule_structure_property_937", "molecule_structure_property_734", "molecule_structure_property_320", "molecule_structure_property_1344", "molecule_structure_property_175", "molecule_structure_property_544", "molecule_structure_property_533", "molecule_structure_property_746", "molecule_structure_property_1104", "molecule_structure_property_1138", "molecule_structure_property_322", "molecule_structure_property_402", "molecule_structure_property_757", "molecule_structure_property_784", "molecule_structure_property_1472", "molecule_structure_property_1599", "molecule_structure_property_791", "molecule_structure_property_1205", "molecule_structure_property_1031", "molecule_structure_property_1074", "molecule_structure_property_1455", "molecule_structure_property_1475", "molecule_structure_property_287", "molecule_structure_property_748", "molecule_structure_property_1175", "molecule_structure_property_1191", "molecule_structure_property_1582", "molecule_structure_property_264", "molecule_structure_property_1050", "molecule_structure_property_554", "molecule_structure_property_1449", "molecule_structure_property_1140", "molecule_structure_property_407", "molecule_structure_property_1341", "molecule_structure_property_1124", "molecule_structure_property_1049", "molecule_structure_property_1325", "molecule_structure_property_667", "molecule_structure_property_851", "molecule_structure_property_1523", "molecule_structure_property_525", "molecule_structure_property_1208", "molecule_structure_property_1556", "molecule_structure_property_933", "molecule_structure_property_1356", "molecule_structure_property_1209", "molecule_structure_property_964", "molecule_structure_property_989", "molecule_structure_property_1028", "molecule_structure_property_1458", "molecule_structure_property_842", "molecule_structure_property_1468", "molecule_structure_property_1419", "molecule_structure_property_1367", "molecule_structure_property_112", "molecule_structure_property_699", "molecule_structure_property_796", "molecule_structure_property_478",
])

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 3,845
Columns: 1519
Use sampling: False (sample size: 3,845)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['molecule_structure_property_1', 'molecule_structure_property_1064', 'molecule_structure_property_1073', 'molecule_structure_property_1072', 'molecule_structure_property_1071', 'molecule_structure_property_1070', 'molecule_structure_property_1069', 'molecule_structure_property_1068', 'molecule_structure_property_1067', 'molecule_structure_property_1066']
Rows remaining as candidates after top-10 filter: 3,832 (of 3,845)

#### Duplicate Report
Total duplicate rows: 20 (0.52% of dataset)
Duplicate rows ignoring target: 20 (0.52% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,molecule_structure_property_1,molecule_structure_property_2,molecule_structure_property_3,molecule_structure_property_4,molecule_structure_property_5,molecule_structure_property_6,molecule_structure_property_7,molecule_structure_property_8,molecule_structure_property_9,molecule_structure_property_10,molecule_structure_property_11,molecule_structure_property_12,molecule_structure_property_13,molecule_structure_property_14,molecule_structure_property_15,molecule_structure_property_16,molecule_structure_property_17,molecule_structure_property_18,molecule_structure_property_19,molecule_structure_property_20,molecule_structure_property_21,molecule_structure_property_22,molecule_structure_property_23,molecule_structure_property_24,molecule_structure_property_25,molecule_structure_property_26,molecule_structure_property_27,molecule_structure_property_28,molecule_structure_property_29,molecule_structure_property_30,molecule_structure_property_31,molecule_structure_property_32,molecule_structure_property_33,molecule_structure_property_34,molecule_structure_property_35,molecule_structure_property_36,molecule_structure_property_37,molecule_structure_property_38,molecule_structure_property_39,molecule_structure_property_40,molecule_structure_property_41,molecule_structure_property_42,molecule_structure_property_43,molecule_structure_property_44,molecule_structure_property_45,molecule_structure_property_46,molecule_structure_property_47,molecule_structure_property_48,molecule_structure_property_49,molecule_structure_property_50,molecule_structure_property_51,molecule_structure_property_52,molecule_structure_property_53,molecule_structure_property_54,molecule_structure_property_55,molecule_structure_property_56,molecule_structure_property_57,molecule_structure_property_58,molecule_structure_property_60,molecule_structure_property_61,molecule_structure_property_62,molecule_structure_property_63,molecule_structure_property_64,molecule_structure_property_65,molecule_structure_property_66,molecule_structure_property_67,molecule_structure_property_68,molecule_structure_property_69,molecule_structure_property_70,molecule_structure_property_71,molecule_structure_property_72,molecule_structure_property_73,molecule_structure_property_74,molecule_structure_property_75,molecule_structure_property_76,molecule_structure_property_77,molecule_structure_property_78,molecule_structure_property_79,molecule_structure_property_80,molecule_structure_property_81,molecule_structure_property_82,molecule_structure_property_83,molecule_structure_property_84,molecule_structure_property_85,molecule_structure_property_86,molecule_structure_property_87,molecule_structure_property_88,molecule_structure_property_89,molecule_structure_property_90,molecule_structure_property_91,molecule_structure_property_92,molecule_structure_property_93,molecule_structure_property_94,molecule_structure_property_95,molecule_structure_property_96,molecule_structure_property_97,molecule_structure_property_98,molecule_structure_property_99,molecule_structure_property_100,molecule_structure_property_101,molecule_structure_property_102,molecule_structure_property_103,molecule_structure_property_104,molecule_structure_property_105,molecule_structure_property_106,molecule_structure_property_107,molecule_structure_property_108,molecule_structure_property_109,molecule_structure_property_110,molecule_structure_property_111,molecule_structure_property_113,molecule_structure_property_114,molecule_structure_property_115,molecule_structure_property_116,molecule_structure_property_117,molecule_structure_property_118,molecule_structure_property_119,molecule_structure_property_120,molecule_structure_property_121,molecule_structure_property_122,molecule_structure_property_123,molecule_structure_property_124,molecule_structure_property_125,molecule_structure_property_126,molecule_structure_property_127,molecule_structure_property_128,molecule_structure_property_129,molecule_structure_property_130,molecule_structure_property_131,molecule_structure_property_132,molecule_structure_property_133,molecule_structure_property_134,molecule_structure_property_135,molecule_structure_property_136,molecule_structure_property_137,molecule_structure_property_138,molecule_structure_property_139,molecule_structure_property_140,molecule_structure_property_141,molecule_structure_property_142,molecule_structure_property_143,molecule_structure_property_144,molecule_structure_property_145,molecule_structure_property_146,molecule_structure_property_147,molecule_structure_property_148,molecule_structure_property_149,molecule_structure_property_150,molecule_structure_property_151,molecule_structure_property_152,molecule_structure_property_153,molecule_structure_property_154,molecule_structure_property_155,molecule_structure_property_156,molecule_structure_property_157,molecule_structure_property_158,molecule_structure_property_159,molecule_structure_property_160,molecule_structure_property_161,molecule_structure_property_162,molecule_structure_property_163,molecule_structure_property_164,molecule_structure_property_165,molecule_structure_property_166,molecule_structure_property_167,molecule_structure_property_168,molecule_structure_property_169,molecule_structure_property_170,molecule_structure_property_171,molecule_structure_property_172,molecule_structure_property_173,molecule_structure_property_174,molecule_structure_property_176,molecule_structure_property_177,molecule_structure_property_178,molecule_structure_property_179,molecule_structure_property_180,molecule_structure_property_181,molecule_structure_property_182,molecule_structure_property_183,molecule_structure_property_184,molecule_structure_property_185,molecule_structure_property_186,molecule_structure_property_187,molecule_structure_property_188,molecule_structure_property_189,molecule_structure_property_190,molecule_structure_property_191,molecule_structure_property_192,molecule_structure_property_193,molecule_structure_property_194,molecule_structure_property_195,molecule_structure_property_196,molecule_structure_property_197,molecule_structure_property_198,molecule_structure_property_199,molecule_structure_property_200,molecule_structure_property_201,molecule_structure_property_202,molecule_structure_property_203,molecule_structure_property_204,molecule_structure_property_205,molecule_structure_property_206,molecule_structure_property_207,molecule_structure_property_208,molecule_structure_property_209,molecule_structure_property_210,molecule_structure_property_211,molecule_structure_property_212,molecule_structure_property_213,molecule_structure_property_214,molecule_structure_property_215,molecule_structure_property_216,molecule_structure_property_217,molecule_structure_property_218,molecule_structure_property_219,molecule_structure_property_220,molecule_structure_property_221,molecule_structure_property_222,molecule_structure_property_223,molecule_structure_property_224,molecule_structure_property_225,molecule_structure_property_226,molecule_structure_property_227,molecule_structure_property_228,molecule_structure_property_229,molecule_structure_property_230,molecule_structure_property_231,molecule_structure_property_232,molecule_structure_property_233,molecule_structure_property_234,molecule_structure_property_235,molecule_structure_property_236,molecule_structure_property_237,molecule_structure_property_238,molecule_structure_property_239,molecule_structure_property_240,molecule_structure_property_241,molecule_structure_property_242,molecule_structure_property_243,molecule_structure_property_244,molecule_structure_property_245,molecule_structure_property_246,molecule_structure_property_247,molecule_structure_property_248,molecule_structure_property_249,molecule_structure_property_250,molecule_structure_property_251,molecule_structure_property_252,molecule_structure_property_253,molecule_structure_property_254,molecule_structure_property_255,molecule_structure_property_256,molecule_structure_property_257,molecule_structure_property_258,molecule_structure_property_259,molecule_structure_property_260,molecule_structure_property_261,molecule_structure_property_262,molecule_structure_property_263,molecule_structure_property_265,molecule_structure_property_266,molecule_structure_property_267,molecule_structure_property_268,molecule_structure_property_269,molecule_structure_property_270,molecule_structure_property_271,molecule_structure_property_272,molecule_structure_property_273,molecule_structure_property_274,molecule_structure_property_275,molecule_structure_property_276,molecule_structure_property_277,molecule_structure_property_278,molecule_structure_property_279,molecule_structure_property_280,molecule_structure_property_281,molecule_structure_property_282,molecule_structure_property_283,molecule_structure_property_284,molecule_structure_property_285,molecule_structure_property_286,molecule_structure_property_288,molecule_structure_property_289,molecule_structure_property_290,molecule_structure_property_291,molecule_structure_property_292,molecule_structure_property_293,molecule_structure_property_294,molecule_structure_property_295,molecule_structure_property_296,molecule_structure_property_297,molecule_structure_property_298,molecule_structure_property_299,molecule_structure_property_300,molecule_structure_property_301,molecule_structure_property_302,molecule_structure_property_303,molecule_structure_property_304,molecule_structure_property_305,molecule_structure_property_306,molecule_structure_property_307,molecule_structure_property_308,molecule_structure_property_309,molecule_structure_property_310,molecule_structure_property_311,molecule_structure_property_312,molecule_structure_property_313,molecule_structure_property_314,molecule_structure_property_315,molecule_structure_property_316,molecule_structure_property_317,molecule_structure_property_318,molecule_structure_property_319,molecule_structure_property_321,molecule_structure_property_323,molecule_structure_property_324,molecule_structure_property_325,molecule_structure_property_326,molecule_structure_property_327,molecule_structure_property_328,molecule_structure_property_329,molecule_structure_property_330,molecule_structure_property_331,molecule_structure_property_332,molecule_structure_property_333,molecule_structure_property_334,molecule_structure_property_335,molecule_structure_property_336,molecule_structure_property_337,molecule_structure_property_338,molecule_structure_property_339,molecule_structure_property_340,molecule_structure_property_341,molecule_structure_property_342,molecule_structure_property_343,molecule_structure_property_344,molecule_structure_property_345,molecule_structure_property_346,molecule_structure_property_347,molecule_structure_property_348,molecule_structure_property_349,molecule_structure_property_350,molecule_structure_property_351,molecule_structure_property_352,molecule_structure_property_353,molecule_structure_property_354,molecule_structure_property_355,molecule_structure_property_356,molecule_structure_property_357,molecule_structure_property_358,molecule_structure_property_359,molecule_structure_property_360,molecule_structure_property_361,molecule_structure_property_362,molecule_structure_property_363,molecule_structure_property_364,molecule_structure_property_365,molecule_structure_property_366,molecule_structure_property_367,molecule_structure_property_368,molecule_structure_property_369,molecule_structure_property_370,molecule_structure_property_371,molecule_structure_property_372,molecule_structure_property_373,molecule_structure_property_374,molecule_structure_property_375,molecule_structure_property_377,molecule_structure_property_378,molecule_structure_property_379,molecule_structure_property_380,molecule_structure_property_381,molecule_structure_property_382,molecule_structure_property_383,molecule_structure_property_384,molecule_structure_property_385,molecule_structure_property_386,molecule_structure_property_387,molecule_structure_property_388,molecule_structure_property_389,molecule_structure_property_390,molecule_structure_property_391,molecule_structure_property_392,molecule_structure_property_393,molecule_structure_property_394,molecule_structure_property_395,molecule_structure_property_396,molecule_structure_property_397,molecule_structure_property_398,molecule_structure_property_399,molecule_structure_property_400,molecule_structure_property_401,molecule_structure_property_403,molecule_structure_property_404,molecule_structure_property_405,molecule_structure_property_406,molecule_structure_property_408,molecule_structure_property_409,molecule_structure_property_411,molecule_structure_property_412,molecule_structure_property_413,molecule_structure_property_414,molecule_structure_property_415,molecule_structure_property_416,molecule_structure_property_417,molecule_structure_property_418,molecule_structure_property_419,molecule_structure_property_420,molecule_structure_property_421,molecule_structure_property_422,molecule_structure_property_423,molecule_structure_property_424,molecule_structure_property_425,molecule_structure_property_426,molecule_structure_property_427,molecule_structure_property_428,molecule_structure_property_429,molecule_structure_property_430,molecule_structure_property_431,molecule_structure_property_432,molecule_structure_property_433,molecule_structure_property_434,molecule_structure_property_435,molecule_structure_property_436,molecule_structure_property_437,molecule_structure_property_438,molecule_structure_property_439,molecule_structure_property_440,molecule_structure_property_441,molecule_structure_property_442,molecule_structure_property_443,molecule_structure_property_444,molecule_structure_property_445,molecule_structure_property_446,molecule_structure_property_447,molecule_structure_property_448,molecule_structure_property_449,molecule_structure_property_450,molecule_structure_property_451,molecule_structure_property_452,molecule_structure_property_453,molecule_structure_property_454,molecule_structure_property_455,molecule_structure_property_456,molecule_structure_property_457,molecule_structure_property_458,molecule_structure_property_459,molecule_structure_property_460,molecule_structure_property_461,molecule_structure_property_462,molecule_structure_property_463,molecule_structure_property_464,molecule_structure_property_465,molecule_structure_property_466,molecule_structure_property_467,molecule_structure_property_468,molecule_structure_property_469,molecule_structure_property_470,molecule_structure_property_471,molecule_structure_property_472,molecule_structure_property_473,molecule_structure_property_474,molecule_structure_property_475,molecule_structure_property_476,molecule_structure_property_477,molecule_structure_property_479,molecule_structure_property_480,molecule_structure_property_481,molecule_structure_property_482,molecule_structure_property_483,molecule_structure_property_484,molecule_structure_property_485,molecule_structure_property_486,molecule_structure_property_487,molecule_structure_property_488,molecule_structure_property_489,molecule_structure_property_490,molecule_structure_property_491,molecule_structure_property_492,molecule_structure_property_493,molecule_structure_property_494,molecule_structure_property_495,molecule_structure_property_496,molecule_structure_property_497,molecule_structure_property_498,molecule_structure_property_499,molecule_structure_property_500,molecule_structure_property_501,molecule_structure_property_502,molecule_structure_property_503,molecule_structure_property_504,molecule_structure_property_505,molecule_structure_property_506,molecule_structure_property_507,molecule_structure_property_508,molecule_structure_property_510,molecule_structure_property_511,molecule_structure_property_512,molecule_structure_property_513,molecule_structure_property_514,molecule_structure_property_515,molecule_structure_property_516,molecule_structure_property_517,molecule_structure_property_518,molecule_structure_property_520,molecule_structure_property_521,molecule_structure_property_522,molecule_structure_property_523,molecule_structure_property_524,molecule_structure_property_526,molecule_structure_property_527,molecule_structure_property_528,molecule_structure_property_529,molecule_structure_property_530,molecule_structure_property_531,molecule_structure_property_532,molecule_structure_property_534,molecule_structure_property_535,molecule_structure_property_536,molecule_structure_property_537,molecule_structure_property_538,molecule_structure_property_539,molecule_structure_property_540,molecule_structure_property_541,molecule_structure_property_543,molecule_structure_property_545,molecule_structure_property_546,molecule_structure_property_547,molecule_structure_property_548,molecule_structure_property_549,molecule_structure_property_550,molecule_structure_property_551,molecule_structure_property_552,molecule_structure_property_553,molecule_structure_property_555,molecule_structure_property_556,molecule_structure_property_557,molecule_structure_property_558,molecule_structure_property_559,molecule_structure_property_560,molecule_structure_property_561,molecule_structure_property_562,molecule_structure_property_563,molecule_structure_property_564,molecule_structure_property_565,molecule_structure_property_566,molecule_structure_property_567,molecule_structure_property_568,molecule_structure_property_569,molecule_structure_property_570,molecule_structure_property_571,molecule_structure_property_572,molecule_structure_property_573,molecule_structure_property_575,molecule_structure_property_576,molecule_structure_property_577,molecule_structure_property_578,molecule_structure_property_579,molecule_structure_property_580,molecule_structure_property_581,molecule_structure_property_582,molecule_structure_property_583,molecule_structure_property_584,molecule_structure_property_585,molecule_structure_property_586,molecule_structure_property_587,molecule_structure_property_588,molecule_structure_property_589,molecule_structure_property_590,molecule_structure_property_591,molecule_structure_property_592,molecule_structure_property_593,molecule_structure_property_594,molecule_structure_property_595,molecule_structure_property_596,molecule_structure_property_597,molecule_structure_property_598,molecule_structure_property_599,molecule_structure_property_600,molecule_structure_property_601,molecule_structure_property_602,molecule_structure_property_603,molecule_structure_property_604,molecule_structure_property_605,molecule_structure_property_606,molecule_structure_property_607,molecule_structure_property_608,molecule_structure_property_609,molecule_structure_property_610,molecule_structure_property_611,molecule_structure_property_612,molecule_structure_property_613,molecule_structure_property_614,molecule_structure_property_615,molecule_structure_property_616,molecule_structure_property_617,molecule_structure_property_618,molecule_structure_property_619,molecule_structure_property_620,molecule_structure_property_621,molecule_structure_property_622,molecule_structure_property_623,molecule_structure_property_624,molecule_structure_property_625,molecule_structure_property_626,molecule_structure_property_627,molecule_structure_property_628,molecule_structure_property_629,molecule_structure_property_630,molecule_structure_property_631,molecule_structure_property_632,molecule_structure_property_634,molecule_structure_property_635,molecule_structure_property_636,molecule_structure_property_637,molecule_structure_property_638,molecule_structure_property_639,molecule_structure_property_640,molecule_structure_property_641,molecule_structure_property_642,molecule_structure_property_643,molecule_structure_property_644,molecule_structure_property_645,molecule_structure_property_646,molecule_structure_property_647,molecule_structure_property_648,molecule_structure_property_649,molecule_s

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,molecule_structure_property_1,category,0.0,0.0,2.0,"0, 1"
1,molecule_structure_property_2,category,0.0,0.0,2.0,"0, 1"
2,molecule_structure_property_3,category,0.0,0.0,2.0,"0, 1"
3,molecule_structure_property_4,category,0.0,0.0,2.0,"0, 1"
4,molecule_structure_property_5,category,0.0,0.0,2.0,"0, 1"
5,molecule_structure_property_6,category,0.0,0.0,2.0,"0, 1"
6,molecule_structure_property_7,category,0.0,0.0,2.0,"0, 1"
7,molecule_structure_property_8,category,0.0,0.0,2.0,"0, 1"
8,molecule_structure_property_9,category,0.0,0.0,2.0,"0, 1"
9,molecule_structure_property_10,category,0.0,0.0,2.0,"0, 1"
10,molecule_structure_property_11,category,0.0,0.0,2.0,"0, 1"
11,molecule_structure_property_12,category,0.0,0.0,2.0,"0, 1"
12,molecule_structure_property_13,category,0.0,0.0,2.0,"0, 1"
13,molecule_structure_property_14,category,0.0,0.0,2.0,"0, 1"
14,molecule_structure_property_15,category,0.0,0.0,2.0,"0, 1"
15,molecule_structure_property_16,category,0.0,0.0,2.0,"0, 1"
16,molecule_structure_property_17,category,0.0,0.0,2.0,"0, 1"
17,molecule_structure_property_18,category,0.0,0.0,2.0,"0, 1"
18,molecule_structure_property_19,category,0.0,0.0,2.0,"0, 1"
19,molecule_structure_property_20,category,0.0,0.0,2.0,"0, 1"
20,molecule_structure_property_21,category,0.0,0.0,2.0,"0, 1"
21,molecule_structure_property_22,category,0.0,0.0,2.0,"0, 1"
22,molecule_structure_property_23,category,0.0,0.0,2.0,"0, 1"
23,molecule_structure_property_24,category,0.0,0.0,2.0,"0, 1"
24,molecule_structure_property_25,category,0.0,0.0,2.0,"0, 1"
25,molecule_structure_property_26,category,0.0,0.0,2.0,"0, 1"
26,molecule_structure_property_27,category,0.0,0.0,2.0,"0, 1"
27,molecule_structure_property_28,category,0.0,0.0,2.0,"0, 1"
28,molecule_structure_property_29,category,0.0,0.0,2.0,"0, 1"
29,molecule_structure_property_30,category,0.0,0.0,2.0,"0, 1"
30,molecule_structure_property_31,category,0.0,0.0,2.0,"0, 1"
31,molecule_structure_property_32,category,0.0,0.0,2.0,"0, 1"
32,molecule_structure_property_33,category,0.0,0.0,2.0,"0, 1"
33,molecule_structure_property_34,category,0.0,0.0,2.0,"0, 1"
34,molecule_structure_property_35,category,0.0,0.0,2.0,"0, 1"
35,molecule_structure_property_36,category,0.0,0.0,2.0,"0, 1"
36,molecule_structure_property_37,category,0.0,0.0,2.0,"0, 1"
37,molecule_structure_property_38,category,0.0,0.0,2.0,"0, 1"
38,molecule_structure_property_39,category,0.0,0.0,2.0,"0, 1"
39,molecule_structure_property_40,category,0.0,0.0,2.0,"0, 1"
40,molecule_structure_property_41,category,0.0,0.0,2.0,"0, 1"
41,molecule_structure_property_42,category,0.0,0.0,2.0,"0, 1"
42,molecule_structure_property_43,category,0.0,0.0,2.0,"0, 1"
43,molecule_structure_property_44,category,0.0,0.0,2.0,"0, 1"
44,molecule_structure_property_45,category,0.0,0.0,2.0,"0, 1"
45,molecule_structure_property_46,category,0.0,0.0,2.0,"0, 1"
46,molecule_structure_property_47,category,0.0,0.0,2.0,"0, 1"
47,molecule_structure_property_48,category,0.0,0.0,2.0,"0, 1"
48,molecule_structure_property_49,category,0.0,0.0,2.0,"0, 1"
49,molecule_structure_property_50,category,0.0,0.0,2.0,"0, 1"
50,molecule_structure_property_51,category,0.0,0.0,2.0,"0, 1"
51,molecule_structure_property_52,category,0.0,0.0,2.0,"0, 1"
52,molecule_structure_property_53,category,0.0,0.0,2.0,"0, 1"
53,molecule_structure_property_54,category,0.0,0.0,2.0,"0, 1"
54,molecule_structure_property_55,category,0.0,0.0,2.0,"0, 1"
55,molecule_structure_property_56,category,0.0,0.0,2.0,"0, 1"
56,molecule_structure_property_57,category,0.0,0.0,2.0,"0, 1"
57,molecule_structure_property_58,category,0.0,0.0,2.0,"0, 1"
58,molecule_structure_property_60,category,0.0,0.0,2.0,"0, 1"
59,molecule_structure_property_61,category,0.0,0.0,2.0,"0, 1"
60,molecule_structure_property_62,category,0.0,0.0,2.0,"0, 1"
61,molecule_structure_property_63,category,0.0,0.0,2.0,"0, 1"
62,molecule_structure_property_64,category,0.0,0.0,2.0,"0, 1"
63,molecule_structure_property_65,category,0.0,0.0,2.0,"0, 1"
64,molecule_structure_property_66,category,0.0,0.0,2.0,"1, 0"
65,molecule_structure_property_67,category,0.0,0.0,2.0,"0, 1"
66,molecule_structure_property_68,category,0.0,0.0,2.0,"0, 1"
67,molecule_structure_property_69,category,0.0,0.0,2.0,"1, 0"
68,molecule_structure_property_70,category,0.0,0.0,2.0,"0, 1"
69,molecule_structure_property_71,category,0.0,0.0,2.0,"0, 1"
70,molecule_structure_property_72,category,0.0,0.0,2.0,"0, 1"
71,molecule_structure_property_73,category,0.0,0.0,2.0,"0, 1"
72,molecule_structure_property_74,category,0.0,0.0,2.0,"0, 1"
73,molecule_structure_property_75,category,0.0,0.0,2.0,"0, 1"
74,molecule_structure_property_76,category,0.0,0.0,2.0,"0, 1"
75,molecule_structure_property_77,category,0.0,0.0,2.0,"0, 1"
76,molecule_structure_property_78,category,0.0,0.0,2.0,"0, 1"
77,molecule_structure_property_79,category,0.0,0.0,2.0,"0, 1"
78,molecule_structure_property_80,category,0.0,0.0,2.0,"0, 1"
79,molecule_structure_property_81,category,0.0,0.0,2.0,"0, 1"
80,molecule_structure_property_82,category,0.0,0.0,2.0,"0, 1"
81,molecule_structure_property_83,category,0.0,0.0,2.0,"0, 1"
82,molecule_structure_property_84,category,0.0,0.0,2.0,"0, 1"
83,molecule_structure_property_85,category,0.0,0.0,2.0,"0, 1"
84,molecule_structure_property_86,category,0.0,0.0,2.0,"0, 1"
85,molecule_structure_property_87,category,0.0,0.0,2.0,"0, 1"
86,molecule_structure_property_88,category,0.0,0.0,2.0,"0, 1"
87,molecule_structure_property_89,category,0.0,0.0,2.0,"0, 1"
88,molecule_structure_property_90,category,0.0,0.0,2.0,"0, 1"
89,molecule_structure_property_91,category,0.0,0.0,2.0,"0, 1"
90,molecule_structure_property_92,category,0.0,0.0,2.0,"0, 1"
91,molecule_structure_property_93,category,0.0,0.0,2.0,"0, 1"
92,molecule_structure_property_94,category,0.0,0.0,2.0,"0, 1"
93,molecule_structure_property_95,category,0.0,0.0,2.0,"0, 1"
94,molecule_structure_property_96,category,0.0,0.0,2.0,"0, 1"
95,molecule_structure_property_97,category,0.0,0.0,2.0,"0, 1"
96,molecule_structure_property_98,category,0.0,0.0,2.0,"0, 1"
97,molecule_structure_property_99,category,0.0,0.0,2.0,"0, 1"
98,molecule_structure_property_100,category,0.0,0.0,2.0,"0, 1"
99,molecule_structure_property_101,category,0.0,0.0,2.0,"0, 1"
100,molecule_structure_property_102,category,0.0,0.0,2.0,"0, 1"
101,molecule_structure_property_103,category,0.0,0.0,2.0,"0, 1"
102,molecule_structure_property_104,category,0.0,0.0,2.0,"0, 1"
103,molecule_structure_property_105,category,0.0,0.0,2.0,"0, 1"
104,molecule_structure_property_106,category,0.0,0.0,2.0,"0, 1"
105,molecule_structure_property_107,category,0.0,0.0,2.0,"0, 1"
106,molecule_structure_property_108,category,0.0,0.0,2.0,"0, 1"
107,molecule_structure_property_109,category,0.0,0.0,2.0,"0, 1"
108,molecule_structure_property_110,category,0.0,0.0,2.0,"0, 1"
109,molecule_structure_property_111,category,0.0,0.0,2.0,"0, 1"
110,molecule_structure_property_113,category,0.0,0.0,2.0,"0, 1"
111,molecule_structure_property_114,category,0.0,0.0,2.0,"0, 1"
112,molecule_structure_property_115,category,0.0,0.0,2.0,"0, 1"
113,molecule_structure_property_116,category,0.0,0.0,2.0,"0, 1"
114,molecule_structure_property_117,category,0.0,0.0,2.0,"0, 1"
115,molecule_structure_property_118,category,0.0,0.0,2.0,"0, 1"
116,molecule_structure_property_119,category,0.0,0.0,2.0,"0, 1"
117,molecule_structure_property_120,category,0.0,0.0,2.0,"0, 1"
118,molecule_structure_property_121,category,0.0,0.0,2.0,"0, 1"
119,molecule_structure_property_122,category,0.0,0.0,2.0,"0, 1"
120,molecule_structure_property_123,category,0.0,0.0,2.0,"1, 0"
121,molecule_structure_property_124,category,0.0,0.0,2.0,"0, 1"
122,molecule_structure_property_125,category,0.0,0.0,2.0,"1, 0"
123,molecule_structure_property_126,category,0.0,0.0,2.0,"0, 1"
124,molecule_structure_property_127,category,0.0,0.0,2.0,"0, 1"
125,molecule_structure_property_128,category,0.0,0.0,2.0,"0, 1"
126,molecule_structure_property_129,category,0.0,0.0,2.0,"0, 1"
127,molecule_structure_property_130,category,0.0,0.0,2.0,"0, 1"
128,molecule_structure_property_131,category,0.0,0.0,2.0,"0, 1"
129,molecule_structure_property_132,category,0.0,0.0,2.0,"0, 1"
130,molecule_structure_property_133,category,0.0,0.0,2.0,"0, 1"
131,molecule_structure_property_134,category,0.0,0.0,2.0,"0, 1"
132,molecule_structure_property_135,category,0.0,0.0,2.0,"0, 1"
133,molecule_structure_property_136,category,0.0,0.0,2.0,"0, 1"
134,molecule_structure_property_137,category,0.0,0.0,2.0,"0, 1"
135,molecule_structure_property_138,category,0.0,0.0,2.0,"0, 1"
136,molecule_structure_property_139,category,0.0,0.0,2.0,"0, 1"
137,molecule_structure_property_140,category,0.0,0.0,2.0,"0, 1"
138,molecule_structure_property_141,category,0.0,0.0,2.0,"0, 1"
139,molecule_structure_property_142,category,0.0,0.0,2.0,"0, 1"
140,molecule_structure_property_143,category,0.0,0.0,2.0,"0, 1"
141,molecule_structure_property_144,category,0.0,0.0,2.0,"0, 1"
142,molecule_structure_property_145,category,0.0,0.0,2.0,"0, 1"
143,molecule_structure_property_146,category,0.0,0.0,2.0,"0, 1"
144,molecule_structure_property_147,category,0.0,0.0,2.0,"0, 1"
145,molecule_structure_property_148,category,0.0,0.0,2.0,"0, 1"
146,molecule_structure_property_149,category,0.0,0.0,2.0,"0, 1"
147,molecule_structure_property_150,category,0.0,0.0,2.0,"0, 1"
148,molecule_structure_property_151,category,0.0,0.0,2.0,"0, 1"
149,molecule_structure_property_152,category,0.0,0.0,2.0,"0, 1"
150,molecule_structure_property_153,category,0.0,0.0,2.0,"0, 1"
151,molecule_structure_property_154,category,0.0,0.0,2.0,"0, 1"
152,molecule_structure_property_155,category,0.0,0.0,2.0,"0, 1"
153,molecule_structure_property_156,category,0.0,0.0,2.0,"0, 1"
154,molecule_structure_property_157,category,0.0,0.0,2.0,"0, 1"
155,molecule_structure_property_158,category,0.0,0.0,2.0,"0, 1"
156,molecule_structure_property_159,category,0.0,0.0,2.0,"0, 1"
157,molecule_structure_property_160,category,0.0,0.0,2.0,"0, 1"
158,molecule_structure_property_161,category,0.0,0.0,2.0,"0, 1"
159,molecule_structure_property_162,category,0.0,0.0,2.0,"0, 1"
160,molecule_structure_property_163,category,0.0,0.0,2.0,"0, 1"
161,molecule_structure_property_164,category,0.0,0.0,2.0,"0, 1"
162,molecule_structure_property_165,category,0.0,0.0,2.0,"0, 1"
163,molecule_structure_property_166,category,0.0,0.0,2.0,"0, 1"
164,molecule_structure_property_167,category,0.0,0.0,2.0,"0, 1"
165,molecule_structure_property_168,category,0.0,0.0,2.0,"0, 1"
166,molecule_structure_property_169,category,0.0,0.0,2.0,"0, 1"
167,molecule_structure_property_170,category,0.0,0.0,2.0,"0, 1"
168,molecule_structure_property_171,category,0.0,0.0,2.0,"0, 1"
169,molecule_structure_property_172,category,0.0,0.0,2.0,"0, 1"
170,molecule_structure_property_173,category,0.0,0.0,2.0,"0, 1"
171,molecule_structure_property_174,category,0.0,0.0,2.0,"0, 1"
172,molecule_structure_property_176,category,0.0,0.0,2.0,"0, 1"
173,molecule_structure_property_177,category,0.0,0.0,2.0,"0, 1"
174,molecule_structure_property_178,category,0.0,0.0,2.0,"0, 1"
175,molecule_structure_property_179,category,0.0,0.0,2.0,"0, 1"
176,molecule_structure_property_180,category,0.0,0.0,2.0,"0, 1"
177,molecule_structure_property_181,category,0.0,0.0,2.0,"0, 1"
178,molecule_structure_property_182,category,0.0,0.0,2.0,"0, 1"
179,molecule_structure_property_183,category,0.0,0.0,2.0,"0, 1"
180,molecule_structure_property_184,category,0.0,0.0,2.0,"0, 1"
181,molecule_structure_property_185,category,0.0,0.0,2.0,"0, 1"
182,molecule_structure_property_186,category,0.0,0.0,2.0,"0, 1"
183,molecule_structure_property_187,category,0.0,0.0,2.0,"0, 1"
184,molecule_structure_property_188,category,0.0,0.0,2.0,"0, 1"
185,molecule_structure_property_189,category,0.0,0.0,2.0,"0, 1"
186,molecule_structure_property_190,category,0.0,0.0,2.0,"0, 1"
187,molecule_structure_property_191,category,0.0,0.0,2.0,"0, 1"
188,molecule_structure_property_192,category,0.0,0.0,2.0,"0, 1"
189,molecule_structure_property_193,category,0.0,0.0,2.0,"0, 1"
190,molecule_structure_property_194,category,0.0,0.0,2.0,"0, 1"
191,molecule_structure_property_195,category,0.0,0.0,2.0,"0, 1"
192,molecule_structure_property_196,category,0.0,0.0,2.0,"1, 0"
193,molecule_structure_property_197,category,0.0,0.0,2.0,"0, 1"
194,molecule_structure_property_198,category,0.0,0.0,2.0,"0, 1"
195,molecule_structure_property_199,category,0.0,0.0,2.0,"0, 1"
196,molecule_structure_property_200,category,0.0,0.0,2.0,"0, 1"
197,molecule_structure_property_201,category,0.0,0.0,2.0,"0, 1"
198,molecule_structure_property_202,category,0.0,0.0,2.0,"0, 1"
199,molecule_structure_property_203,category,0.0,0.0,2.0,"0, 1"
200,molecule_structure_property_204,category,0.0,0.0,2.0,"0, 1"
201,molecule_structure_property_205,category,0.0,0.0,2.0,"0, 1"
202,molecule_structure_property_206,category,0.0,0.0,2.0,"0, 1"
203,molecule_structure_property_207,category,0.0,0.0,2.0,"0, 1"
204,molecule_structure_property_208,category,0.0,0.0,2.0,"0, 1"
205,molecule_structure_property_209,category,0.0,0.0,2.0,"0, 1"
206,molecule_structure_property_210,category,0.0,0.0,2.0,"0, 1"
207,molecule_structure_property_211,category,0.0,0.0,2.0,"0, 1"
208,molecule_structure_property_212,category,0.0,0.0,2.0,"0, 1"
209,molecule_structure_property_213,category,0.0,0.0,2.0,"0, 1"
210,molecule_structure_property_214,category,0.0,0.0,2.0,"0, 1"
211,molecule_structure_property_215,category,0.0,0.0,2.0,"0, 1"
212,molecule_structure_property_216,category,0.0,0.0,2.0,"1, 0"
213,molecule_structure_property_217,category,0.0,0.0,2.0,"0, 1"
214,molecule_structure_property_218,category,0.0,0.0,2.0,"0, 1"
215,molecule_structure_property_219,category,0.0,0.0,2.0,"0, 1"
216,molecule_structure_property_220,category,0.0,0.0,2.0,"0, 1"
217,molecule_structure_property_221,category,0.0,0.0,2.0,"0, 1"
218,molecule_structure_property_222,category,0.0,0.0,2.0,"0, 1"
219,molecule_structure_property_223,category,0.0,0.0,2.0,"0, 1"
220,molecule_structure_property_224,category,0.0,0.0,2.0,"0, 1"
221,molecule_structure_property_225,category,0.0,0.0,2.0,"0, 1"
222,molecule_structure_property_226,category,0.0,0.0,2.0,"0, 1"
223,molecule_structure_property_227,category,0.0,0.0,2.0,"0, 1"
224,molecule_structure_property_228,category,0.0,0.0,2.0,"0, 1"
225,molecule_structure_property_229,category,0.0,0.0,2.0,"0, 1"
226,molecule_structure_property_230,category,0.0,0.0,2.0,"0, 1"
227,molecule_structure_property_231,category,0.0,0.0,2.0,"1, 0"
228,molecule_structure_property_232,category,0.0,0.0,2.0,"0, 1"
229,molecule_structure_property_233,category,0.0,0.0,2.0,"0, 1"
230,molecule_structure_property_234,category,0.0,0.0,2.0,"0, 1"
231,molecule_structure_property_235,category,0.0,0.0,2.0,"0, 1"
232,molecule_structure_property_236,category,0.0,0.0,2.0,"0, 1"
233,molecule_structure_property_237,category,0.0,0.0,2.0,"0, 1"
234,molecule_structure_property_238,category,0.0,0.0,2.0,"0, 1"
235,molecule_structure_property_239,category,0.0,0.0,2.0,"0, 1"
236,molecule_structure_property_240,category,0.0,0.0,2.0,"0, 1"
237,molecule_structure_property_241,category,0.0,0.0,2.0,"0, 1"
238,molecule_structure_property_242,category,0.0,0.0,2.0,"1, 0"
239,molecule_structure_property_243,category,0.0,0.0,2.0,"0, 1"
240,molecule_structure_property_244,category,0.0,0.0,2.0,"0, 1"
241,molecule_structure_property_245,category,0.0,0.0,2.0,"1, 0"
242,molecule_structure_property_246,category,0.0,0.0,2.0,"0, 1"
243,molecule_structure_property_247,category,0.0,0.0,2.0,"0, 1"
244,molecule_structure_property_248,category,0.0,0.0,2.0,"0, 1"
245,molecule_structure_property_249,category,0.0,0.0,2.0,"0, 1"
246,molecule_structure_property_250,category,0.0,0.0,2.0,"1, 0"
247,molecule_structure_property_251,category,0.0,0.0,2.0,"0, 1"
248,molecule_structure_property_252,category,0.0,0.0,2.0,"0, 1"
249,molecule_structure_property_253,category,0.0,0.0,2.0,"0, 1"
250,molecule_structure_property_254,category,0.0,0.0,2.0,"0, 1"
251,molecule_structure_property_255,category,0.0,0.0,2.0,"0, 1"
252,molecule_structure_property_256,category,0.0,0.0,2.0,"0, 1"
253,molecule_structure_property_257,category,0.0,0.0,2.0,"0, 1"
254,molecule_structure_property_258,category,0.0,0.0,2.0,"0, 1"
255,molecule_structure_property_259,category,0.0,0.0,2.0,"0, 1"
256,molecule_structure_property_260,category,0.0,0.0,2.0,"0, 1"
257,molecule_structure_property_261,category,0.0,0.0,2.0,"0, 1"
258,molecule_structure_property_262,category,0.0,0.0,2.0,"0, 1"
259,molecule_structure_property_263,category,0.0,0.0,2.0,"0, 1"
260,molecule_structure_property_265,category,0.0,0.0,2.0,"0, 1"
261,molecule_structure_property_266,category,0.0,0.0,2.0,"0, 1"
262,molecule_structure_property_267,category,0.0,0.0,2.0,"0, 1"
263,molecule_structure_property_268,category,0.0,0.0,2.0,"0, 1"
264,molecule_structure_property_269,category,0.0,0.0,2.0,"0, 1"
265,molecule_structure_property_270,category,0.0,0.0,2.0,"0, 1"
266,molecule_structure_property_271,category,0.0,0.0,2.0,"0, 1"
267,molecule_structure_property_272,category,0.0,0.0,2.0,"0, 1"
268,molecule_structure_property_273,category,0.0,0.0,2.0,"0, 1"
269,molecule_structure_property_274,category,0.0,0.0,2.0,"0, 1"
270,molecule_structure_property_275,category,0.0,0.0,2.0,"0, 1"
271,molecule_structure_property_276,category,0.0,0.0,2.0,"0, 1"
272,molecule_structure_property_277,category,0.0,0.0,2.0,"0, 1"
273,molecule_structure_property_278,category,0.0,0.0,2.0,"0, 1"
274,molecule_structure_property_279,category,0.0,0.0,2.0,"0, 1"
275,molecule_structure_property_280,category,0.0,0.0,2.0,"0, 1"
276,molecule_structure_property_281,category,0.0,0.0,2.0,"0, 1"
277,molecule_structure_property_282,category,0.0,0.0,2.0,"0, 1"
278,molecule_structure_property_283,category,0.0,0.0,2.0,"0, 1"
279,molecule_structure_property_284,category,0.0,0.0,2.0,"0, 1"
280,molecule_structure_property_285,category,0.0,0.0,2.0,"0, 1"
281,molecule_structure_property_286,category,0.0,0.0,2.0,"0, 1"
282,molecule_structure_property_288,category,0.0,0.0,2.0,"0, 1"
283,molecule_structure_property_289,category,0.0,0.0,2.0,"0, 1"
284,molecule_structure_property_290,category,0.0,0.0,2.0,"0, 1"
285,molecule_structure_property_291,category,0.0,0.0,2.0,"0, 1"
286,molecule_structure_property_292,category,0.0,0.0,2.0,"0, 1"
287,molecule_structure_property_293,category,0.0,0.0,2.0,"0, 1"
288,molecule_structure_property_294,category,0.0,0.0,2.0,"0, 1"
289,molecule_structure_property_295,category,0.0,0.0,2.0,"0, 1"
290,molecule_structure_property_296,category,0.0,0.0,2.0,"1, 0"
291,molecule_structure_property_297,category,0.0,0.0,2.0,"0, 1"
292,molecule_structure_property_298,category,0.0,0.0,2.0,"0, 1"
293,molecule_structure_property_299,category,0.0,0.0,2.0,"0, 1"
294,molecule_structure_property_300,category,0.0,0.0,2.0,"0, 1"
295,molecule_structure_property_301,category,0.0,0.0,2.0,"0, 1"
296,molecule_structure_property_302,category,0.0,0.0,2.0,"0, 1"
297,molecule_structure_property_303,category,0.0,0.0,2.0,"0, 1"
298,molecule_structure_property_304,category,0.0,0.0,2.0,"0, 1"
299,molecule_structure_property_305,category,0.0,0.0,2.0,"0, 1"
300,molecule_structure_property_306,category,0.0,0.0,2.0,"0, 1"
301,molecule_structure_property_307,category,0.0,0.0,2.0,"0, 1"
302,molecule_structure_property_308,category,0.0,0.0,2.0,"0, 1"
303,molecule_structure_property_309,category,0.0,0.0,2.0,"0, 1"
304,molecule_structure_property_310,category,0.0,0.0,2.0,"0, 1"
305,molecule_structure_property_311,category,0.0,0.0,2.0,"0, 1"
306,molecule_structure_property_312,category,0.0,0.0,2.0,"0, 1"
307,molecule_structure_property_313,category,0.0,0.0,2.0,"0, 1"
308,molecule_structure_property_314,category,0.0,0.0,2.0,"0, 1"
309,molecule_structure_property_315,category,0.0,0.0,2.0,"0, 1"
310,molecule_structure_property_316,category,0.0,0.0,2.0,"0, 1"
311,molecule_structure_property_317,category,0.0,0.0,2.0,"0, 1"
312,molecule_structure_property_318,category,0.0,0.0,2.0,"0, 1"
313,molecule_structure_property_319,category,0.0,0.0,2.0,"0, 1"
314,molecule_structure_property_321,category,0.0,0.0,2.0,"0, 1"

In [6]:
# Numeric Feature Statistics
numeric_stats

'No numeric features to summarize.'

In [7]:
# Categorical Feature Statistics
cat_stats

                                      value  count    pct
column                           rank
CompoundActive                   1       -1   3710  96.49
                                 2        1    135   3.51
molecule_structure_property_1    1        0   3808  99.04
                                 2        1     37   0.96
molecule_structure_property_10   1        0   3778  98.26
                                 2        1     67   1.74
molecule_structure_property_100  1        0   3798  98.78
                                 2        1     47   1.22
molecule_structure_property_1000 1        0   3831  99.64
                                 2        1     14   0.36
molecule_structure_property_1001 1        0   2612  67.93
                                 2        1   1233  32.07
molecule_structure_property_1002 1        0   3562  92.64
                                 2        1    283   7.36
molecule_structure_property_1003 1        0   3762  97.84
                                 2        1     83   2.16
molecule_structure_property_1004 1        0   3743  97.35
                                 2        1    102   2.65
molecule_structure_property_1005 1        0   3587  93.29
                                 2        1    258   6.71
molecule_structure_property_1006 1        0   3685  95.84
                                 2        1    160   4.16
molecule_structure_property_1007 1        0   3571  92.87
                                 2        1    274   7.13
molecule_structure_property_1008 1        0   3654  95.03
                                 2        1    191   4.97
molecule_structure_property_1009 1        0   3373  87.72
                                 2        1    472  12.28
molecule_structure_property_101  1        0   3762  97.84
                                 2        1     83   2.16
molecule_structure_property_1010 1        0   3768  98.00
                                 2        1     77   2.00
molecule_structure_property_1012 1        0   3659  95.16
                                 2        1    186   4.84
molecule_structure_property_1013 1        0   3721  96.78
                                 2        1    124   3.22
molecule_structure_property_1014 1        0   3630  94.41
                                 2        1    215   5.59
molecule_structure_property_1015 1        0   3344  86.97
                                 2        1    501  13.03
molecule_structure_property_1016 1        0   3664  95.29
                                 2        1    181   4.71
molecule_structure_property_1017 1        0   3675  95.58
                                 2        1    170   4.42
molecule_structure_property_1018 1        0   2848  74.07
                                 2        1    997  25.93
molecule_structure_property_1019 1        0   3604  93.73
                                 2        1    241   6.27
molecule_structure_property_102  1        0   3752  97.58
                                 2        1     93   2.42
molecule_structure_property_1020 1        0   3615  94.02
                                 2        1    230   5.98
molecule_structure_property_1021 1        0   3717  96.67
                                 2        1    128   3.33
molecule_structure_property_1022 1        0   3636  94.56
                                 2        1    209   5.44
molecule_structure_property_1023 1        0   3788  98.52
                                 2        1     57   1.48
molecule_structure_property_1025 1        0   3750  97.53
                                 2        1     95   2.47
molecule_structure_property_1026 1        0   3597  93.55
                                 2        1    248   6.45
molecule_structure_property_1027 1        0   3751  97.56
                                 2        1     94   2.44
molecule_structure_property_1029 1        0   3032  78.86
                                 2        1    813  21.14
molecule_structure_property_103  1        0   3712  96.54
                                 2        1    133   3.46
molecule_structure_property_1030 1        0   3788  98.52
                                 2        1     57   1.48
molecule_structure_property_1032 1        0   2547  66.24
                                 2        1   1298  33.76
molecule_structure_property_1033 1        0   3665  95.32
                                 2        1    180   4.68
molecule_structure_property_1034 1        0   3382  87.96
                                 2        1    463  12.04
molecule_structure_property_1036 1        0   3305  85.96
                                 2        1    540  14.04
molecule_structure_property_1037 1        0   3481  90.53
                                 2        1    364   9.47
molecule_structure_property_1038 1        0   3624  94.25
                                 2        1    221   5.75
molecule_structure_property_1039 1        0   3344  86.97
                                 2        1    501  13.03
molecule_structure_property_104  1        0   3744  97.37
                                 2        1    101   2.63
molecule_structure_property_1040 1        0   3781  98.34
                                 2        1     64   1.66
molecule_structure_property_1041 1        0   3464  90.09
                                 2        1    381   9.91
molecule_structure_property_1042 1        0   3758  97.74
                                 2        1     87   2.26
molecule_structure_property_1043 1        0   3807  99.01
                                 2        1     38   0.99
molecule_structure_property_1044 1        0   3751  97.56
                                 2        1     94   2.44
molecule_structure_property_1045 1        0   3772  98.10
                                 2        1     73   1.90
molecule_structure_property_1046 1        0   3782  98.36
                                 2        1     63   1.64
molecule_structure_property_1047 1        0   2681  69.73
                                 2        1   1164  30.27
molecule_structure_property_1048 1        0   3686  95.86
                                 2        1    159   4.14
molecule_structure_property_105  1        0   3447  89.65
                                 2        1    398  10.35
molecule_structure_property_1051 1        0   3248  84.47
                                 2        1    597  15.53
molecule_structure_property_1052 1        0   3770  98.05
                                 2        1     75   1.95
molecule_structure_property_1053 1        0   3776  98.21
                                 2        1     69   1.79
molecule_structure_property_1054 1        0   3764  97.89
                                 2        1     81   2.11
molecule_structure_property_1055 1        0   3782  98.36
                                 2        1     63   1.64
molecule_structure_property_1056 1        0   3713  96.57
                                 2        1    132   3.43
molecule_structure_property_1057 1        0   3599  93.60
                                 2        1    246   6.40
molecule_structure_property_1058 1        0   3814  99.19
                                 2        1     31   0.81
molecule_structure_property_1059 1        0   2845  73.99
                                 2        1   1000  26.01
molecule_structure_property_106  1        0   2957  76.91
                                 2        1    888  23.09
molecule_structure_property_1060 1        0   3782  98.36
                                 2        1     63   1.64
molecule_structure_property_1061 1        0   3250  84.53
                                 2        1    595  15.47
molecule_structure_property_1062 1        0   3595  93.50
                                 2        1    250   6.50
molecule_structure_property_1063 1        0   2577  67.02
                                 2        1   1268  32.98
molecule_structure_property_1064 1        0   3597  93.55
                                 2        1    248   6.45
molecule_structure_property_1065 1        0   3637  94.59
                                 2        1    208   5.41
molecule_structure_property_1066 1        0   3727  96.93
                                 2        1    118   3.07
molecule_structure_property_1067 1        0   3815  99.22
                                 2        1     30   0.78
molecule_structure_property_1068 1        0   2661  69.21
                                 2        1   1184  30.79
molecule_structure_property_1069 1        0   3820  99.35
                                 2        1     25   0.65
molecule_structure_property_107  1        0   3403  88.50
                                 2        1    442  11.50
molecule_structure_property_1070 1        0   3723  96.83
                                 2        1    122   3.17
molecule_structure_property_1071 1        0   3501  91.05
                                 2        1    344   8.95
molecule_structure_property_1072 1        0   3653  95.01
                                 2        1    192   4.99
molecule_structure_property_1073 1        0   3757  97.71
                                 2        1     88   2.29
molecule_structure_property_1075 1        0   3709  96.46
                                 2        1    136   3.54
molecule_structure_property_1076 1        0   3745  97.40
                                 2        1    100   2.60
molecule_structure_property_1077 1        0   3191  82.99
                                 2        1    654  17.01
molecule_structure_property_1078 1        0   3734  97.11
                                 2        1    111   2.89
molecule_structure_property_108  1        0   3615  94.02
                                 2        1    230   5.98
molecule_structure_property_1080 1        0   3811  99.12
                                 2        1     34   0.88
molecule_structure_property_1081 1        0   3649  94.90
                                 2        1    196   5.10
molecule_structure_property_1082 1        0   3324  86.45
                                 2        1    521  13.55
molecule_structure_property_1083 1        0   3732  97.06
                                 2        1    113   2.94
molecule_structure_property_1084 1        0   3379  87.88
                                 2        1    466  12.12
molecule_structure_property_1085 1        0   3791  98.60
                                 2        1     54   1.40
molecule_structure_property_1086 1        0   3836  99.77
                                 2        1      9   0.23
molecule_structure_property_1087 1        0   3231  84.03
                                 2        1    614  15.97
molecule_structure_property_1088 1        0   3754  97.63
                                 2        1     91   2.37
molecule_structure_property_1089 1        0   3673  95.53
                                 2        1    172   4.47
molecule_structure_property_109  1        0   3682  95.76
                                 2        1    163   4.24
molecule_structure_property_1090 1        0   3668  95.40
                                 2        1    177   4.60
molecule_structure_property_1091 1        0   3195  83.09
                                 2        1    650  16.91
molecule_structure_property_1092 1        0   2120  55.14
                                 2        1   1725  44.86
molecule_structure_property_1093 1        0   3720  96.75
                                 2        1    125   3.25
molecule_structure_property_1094 1        0   3778  98.26
                                 2        1     67   1.74
molecule_structure_property_1095 1        0   3562  92.64
                                 2        1    283   7.36
molecule_structure_property_1096 1        0   3694  96.07
                                 2        1    151   3.93
molecule_structure_property_1097 1        0   3681  95.73
                                 2        1    164   4.27
molecule_structure_property_1098 1        0   3156  82.08
                                 2        1    689  17.92
molecule_structure_property_1099 1        0   3517  91.47
                                 2        1    328   8.53
molecule_structure_property_11   1        0   3527  91.73
                                 2        1    318   8.27
molecule_structure_property_110  1        0   2494  64.86
                                 2        1   1351  35.14
molecule_structure_property_1100 1        0   3680  95.71
                                 2        1    165   4.29
molecule_structure_property_1101 1        0   3784  98.41
                                 2        1     61   1.59
molecule_structure_property_1102 1        0   3655  95.06
                                 2        1    190   4.94
molecule_structure_property_1103 1        0   3766  97.95
                                 2        1     79   2.05
molecule_structure_property_1105 1        0   3638  94.62
                                 2        1    207   5.38
molecule_structure_property_1106 1        0   3641  94.69
                                 2        1    204   5.31
molecule_structure_property_1107 1        0   3823  99.43
                                 2        1     22   0.57
molecule_structure_property_1108 1        0   3833  99.69
                                 2        1     12   0.31
molecule_structure_property_1109 1        0   3500  91.03
                                 2        1    345   8.97
molecule_structure_property_111  1        0   3655  95.06
                                 2        1    190   4.94
molecule_structure_property_1110 1        0   3572  92.90
                                 2        1    273   7.10
molecule_structure_property_1111 1        0   3402  88.48
                                 2        1    443  11.52
molecule_structure_property_1112 1        0   3757  97.71
                                 2        1     88   2.29
molecule_structure_property_1113 1        0   3758  97.74
                                 2        1     87   2.26
molecule_structure_property_1115 1        0   3657  95.11
                                 2        1    188   4.89
molecule_structure_property_1116 1        0   3761  97.82
                                 2        1     84   2.18
molecule_structure_property_1117 1        1   2810  73.08
                                 2        0   1035  26.92
molecule_structure_property_1118 1        0   2974  77.35
                                 2        1    871  22.65
molecule_structure_property_1119 1        0   2901  75.45
                                 2        1    944  24.55
molecule_structure_property_1120 1        0   3073  79.92
                                 2        1    772  20.08
molecule_structure_property_1121 1        0   3678  95.66
                                 2        1    167   4.34
molecule_structure_property_1122 1        0   3512  91.34
                                 2        1    333   8.66
molecule_structure_property_1123 1        0   3355  87.26
                                 2        1    490  12.74
molecule_structure_property_1125 1        0   3707  96.41
                                 2        1    138   3.59
molecule_structure_property_1126 1        0   3806  98.99
                                 2        1     39   1.01
molecule_structure_property_1128 1        0   3679  95.68
                                 2        1    166   4.32
molecule_structure_property_1129 1        0   3620  94.15
                                 2        1    225   5.85
molecule_structure_property_113  1        0   3600  93.63
                                 2        1    245   6.37
molecule_structure_property_1130 1        0   3328  86.55
                                 2        1    517  13.45
molecule_structure_property_1131 1        0   3766  97.95
                                 2        1     79   2.05
molecule_structure_property_1132 1        0   3099  80.60
                                 2        1    746  19.40
molecule_structure_property_1133 1        0   3641  94.69
                                 2        1    204   5.31
molecule_structure_property_1134 1        0   3534  91.91
                                 2        1    311   8.09
molecule_structure_property_1135 1        0   3694  96.07
                                 2        1    151   3.93
molecule_structure_property_1136 1        0   3430  89.21
                                 2        1    415  10.79
molecule_structure_property_1137 1        0   3765  97.92
                                 2        1     80   2.08
molecule_structure_property_1139 1        0   3594  93.47
                                 2        1    251   6.53
molecule_structure_property_114  1        0   3766  97.95
                                 2        1     79   2.05
molecule_structure_property_1141 1        0   3024  78.65
                                 2        1    821  21.35
molecule_structure_property_1142 1        0   3817  99.27
                                 2        1     28   0.73
molecule_structure_property_1143 1        0   3802  98.88
                                 2        1     43   1.12
molecule_structure_property_1144 1        0   3603  93.71
                                 2        1    242   6.29
molecule_structure_property_1145 1        0   3423  89.02
                                 2        1    422  10.98
molecule_structure_property_1146 1        0   3474  90.35
                                 2        1    371   9.65
molecule_structure_property_1147 1        0   3269  85.02
                                 2        1    576  14.98
molecule_structure_property_1148 1        0   3734  97.11
                                 2        1    111   2.89
molecule_structure_property_1149 1        0   3681  95.73
                                 2        1    164   4.27
molecule_structure_property_115  1        0   3532  91.86
                                 2        1    313   8.14
molecule_structure_property_1150 1        0   2961  77.01
                                 2        1    884  22.99
molecule_structure_property_1151 1        0   3411  88.71
                                 2        1    434  11.29
molecule_structure_property_1152 1        0   3733  97.09
                                 2        1    112   2.91
molecule_structure_property_1153 1        0   3768  98.00
                                 2        1     77   2.00
molecule_structure_property_1154 1        0   3748  97.48
                                 2        1     97   2.52
molecule_structure_property_1155 1        0   3112  80.94
                                 2        1    733  19.06
molecule_structure_property_1156 1        0   3774  98.15
                                 2        1     71   1.85
molecule_structure_property_1157 1        0   3617  94.07
                                 2        1    228   5.93
molecule_structure_property_1158 1        0   3721  96.78
                                 2        1    124   3.22
molecule_structure_property_1159 1        0   3732  97.06
                                 2        1    113   2.94
molecule_structure_property_116  1        0   3776  98.21
                                 2        1     69   1.79
molecule_structure_property_1160 1        0   3821  99.38
                                 2        1     24   0.62
molecule_structure_property_1161 1        0   3679  95.68
                                 2        1    166   4.32
molecule_structure_property_1162 1        0   3771  98.08
                                 2        1     74   1.92
molecule_structure_property_1163 1        0   3694  96.07
                                 2        1    151   3.93
molecule_structure_property_1164 1        0   3042  79.12
                                 2        1    803  20.88
molecule_structure_property_1165 1        0   3614  93.99
                                 2        1    231   6.01
molecule_structure_property_1166 1        0   3760  97.79

In [8]:
# Target Distribution
target_df

                count    pct
CompoundActive
-1               3710  96.49
 1                135   3.51

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to hiva_agnostic/019d9ce5-6be1-7c15-9229-195b5fb16816
019d9ce5-6be1-7c15-9229-195b5fb16816
07e86fa3ee92d132f41128550aa70f2e00d4268379445d08dfc88609657407cd