### Dataset and Task Metadata

In [5]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="qsar_biodeg",
    dataset_year="2013",
    domain_str="biology & life sciences",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C5H60M",
    download_description="""
We download the data from Kaggle and uzip it to a predefined folder.

mkdir -p local-data-warehouse/qsar_biodeg/ && wget -P local-data-warehouse/qsar_biodeg/ https://archive.ics.uci.edu/static/public/254/qsar+biodegradation.zip && unzip local-data-warehouse/qsar_biodeg/qsar+biodegradation.zip -d local-data-warehouse/qsar_biodeg/ && rm local-data-warehouse/qsar_biodeg/qsar+biodegradation.zip
""",
    # References
    academic_reference_bibtex="""@article{mansouri2013qsar,
  title={Quantitative structure--activity relationship models for ready biodegradability of chemicals},
  author={Mansouri, Kamel and Ringsted, Tine and Ballabio, Davide and Todeschini, Roberto and Consonni, Viviana},
  journal={Journal of chemical information and modeling},
  volume={53},
  number={4},
  pages={867--878},
  year={2013},
  publisher={ACS Publications}
}
""",
    academic_reference_bibtex_key="mansouri2013qsar",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
 - We added semantic meaningful feature names.
 - Anomaly: several features are numeric-ordinal in nature but it is unclear if they are categorical features.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Biodegradable",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="Biodegradable",
)

## Preprocessing

In [9]:
import pandas as pd

df = pd.read_csv(f"{dataset_mold.path}/biodeg.csv", header=None, sep=";")

feature_names = [
    "Laplace_Leading_Eigenvalue",
    "Weighted_Balaban_Index_Barysz_Matrix",
    "Num_Heavy_Atoms",
    "Freq_NN_At_Dist1",
    "Freq_CN_At_Dist4",
    "Num_ssssC_Atoms",
    "Num_Substituted_BenzeneC",
    "Percentage_C_Atoms",
    "Num_Terminal_PrimaryC",
    "Num_Oxygen_Atoms",
    "Freq_CN_At_Dist3",
    "Sum_dssC_EStates",
    "Weighted_HyperWiener_Index_Burden_Matrix",
    "Lopping_Centric_Index",
    "Laplace_Spectral_Moment6",
    "Freq_CO_At_Dist3",
    "Mean_Sanderson_Electronegativity",
    "Mean_Ionization_Potential",
    "Num_N_Hydrazine",
    "Num_Aromatic_Nitro_Groups",
    "Num_CRX3",
    "Weighted_Normalized_SpectralPositiveSum_Burden_Matrix",
    "Num_Circuits",
    "Presence_CBr_At_Dist1",
    "Presence_CCl_At_Dist3",
    "N073_chemical_substructure",
    "Adjacency_LeadingEigenvalue",
    "Intrinsic_State_Pseudoconnectivity",
    "Presence_CBr_At_Dist4",
    "Sum_dO_EStates",
    "Laplace_MoharIndex2",
    "Num_RingTertiaryC",
    "C026_chemical_substructure",
    "Freq_CN_At_Dist2",
    "Num_HBond_Donors_Atoms",
    "Weighted_LeadingEigenvalue_Burden_Matrix",
    "Intrinsic_State_Pseudoconnectivity_SAvg",
    "Num_Nitrogen_Atoms",
    "Weighted_SpectralMoment6_Burden_Matrix",
    "Num_Esters",
    "Num_Halogen_Atoms",
    "Biodegradable"
]

cat_features = [
    "Presence_CBr_At_Dist1",
    "Presence_CCl_At_Dist3",
    "N073_chemical_substructure",
    "Presence_CBr_At_Dist4",
    "C026_chemical_substructure",
    "Biodegradable"
]
    
df.columns = feature_names

df["Biodegradable"] = df["Biodegradable"].map({"RB": "Yes", "NRB": "No"})
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

df[cat_features] = df[cat_features].astype("category")

In [10]:
# Use if needed to get see all cols of pandas dataframes
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
df.head()

,Laplace_Leading_Eigenvalue,Weighted_Balaban_Index_Barysz_Matrix,Num_Heavy_Atoms,Freq_NN_At_Dist1,Freq_CN_At_Dist4,Num_ssssC_Atoms,Num_Substituted_BenzeneC,Percentage_C_Atoms,Num_Terminal_PrimaryC,Num_Oxygen_Atoms,Freq_CN_At_Dist3,Sum_dssC_EStates,Weighted_HyperWiener_Index_Burden_Matrix,Lopping_Centric_Index,Laplace_Spectral_Moment6,Freq_CO_At_Dist3,Mean_Sanderson_Electronegativity,Mean_Ionization_Potential,Num_N_Hydrazine,Num_Aromatic_Nitro_Groups,Num_CRX3,Weighted_Normalized_SpectralPositiveSum_Burden_Matrix,Num_Circuits,Presence_CBr_At_Dist1,Presence_CCl_At_Dist3,N073_chemical_substructure,Adjacency_LeadingEigenvalue,Intrinsic_State_Pseudoconnectivity,Presence_CBr_At_Dist4,Sum_dO_EStates,Laplace_MoharIndex2,Num_RingTertiaryC,C026_chemical_substructure,Freq_CN_At_Dist2,Num_HBond_Donors_Atoms,Weighted_LeadingEigenvalue_Burden_Matrix,Intrinsic_State_Pseudoconnectivity_SAvg,Num_Nitrogen_Atoms,Weighted_SpectralMoment6_Burden_Matrix,Num_Esters,Num_Halogen_Atoms,Biodegradable
0,4.414,2.1543,0,0,1,0,0,30.0,0,0,2,0.000,2.736,0.802,9.183,0,0.970,1.149,0,0,0,1.165,1,0,0,0,2.101,-0.064,0,0.000,0.975,0,0,2,2,3.143,1.833,1,7.083,0,0,Yes
1,3.000,1.7389,1,0,0,0,0,25.0,2,0,0,0.000,3.426,0.918,6.594,0,0.985,1.136,0,0,0,1.383,0,1,0,0,1.414,0.691,0,0.000,1.333,0,0,0,0,6.867,2.083,0,11.561,0,1,No
2,4.560,4.4123,0,0,0,0,0,33.3,4,4,0,-0.945,3.979,3.022,10.432,10,0.987,1.139,0,0,0,1.183,0,0,0,0,2.156,0.000,0,23.321,6.935,0,0,0,0,3.542,2.250,0,8.631,0,0,Yes
3,4.973,3.6020,0,0,2,0,3,35.0,0,3,4,0.000,3.450,1.258,10.152,6,1.042,1.144,0,1,0,1.193,1,0,0,0,2.317,0.005,0,20.720,1.706,0,3,4,2,3.883,3.042,2,8.639,0,0,No
4,4.651,2.7156,0,0,0,0,0,31.3,0,1,0,0.292,2.826,0.917,9.502,3,0.998,1.148,0,0,0,1.190,1,0,0,0,2.214,-0.074,0,10.500,0.918,0,0,2,0,3.482,2.452,1,7.624,0,0,Yes

## Data Checks

In [11]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 1,055
Columns: 42
Use sampling: False (sample size: 1,055)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['Weighted_Balaban_Index_Barysz_Matrix', 'Weighted_SpectralMoment6_Burden_Matrix', 'Weighted_HyperWiener_Index_Burden_Matrix', 'Weighted_LeadingEigenvalue_Burden_Matrix', 'Intrinsic_State_Pseudoconnectivity_SAvg', 'Laplace_MoharIndex2', 'Laplace_Spectral_Moment6', 'Sum_dO_EStates', 'Laplace_Leading_Eigenvalue', 'Sum_dssC_EStates']
Rows remaining as candidates after top-10 filter: 6 (of 1,055)

#### Duplicate Report
Total duplicate rows: 3 (0.28% of dataset)
Duplicate rows ignoring target: 3 (0.28% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [12]:
# Sample Rows
df_head

,Laplace_Leading_Eigenvalue,Weighted_Balaban_Index_Barysz_Matrix,Num_Heavy_Atoms,Freq_NN_At_Dist1,Freq_CN_At_Dist4,Num_ssssC_Atoms,Num_Substituted_BenzeneC,Percentage_C_Atoms,Num_Terminal_PrimaryC,Num_Oxygen_Atoms,Freq_CN_At_Dist3,Sum_dssC_EStates,Weighted_HyperWiener_Index_Burden_Matrix,Lopping_Centric_Index,Laplace_Spectral_Moment6,Freq_CO_At_Dist3,Mean_Sanderson_Electronegativity,Mean_Ionization_Potential,Num_N_Hydrazine,Num_Aromatic_Nitro_Groups,Num_CRX3,Weighted_Normalized_SpectralPositiveSum_Burden_Matrix,Num_Circuits,Presence_CBr_At_Dist1,Presence_CCl_At_Dist3,N073_chemical_substructure,Adjacency_LeadingEigenvalue,Intrinsic_State_Pseudoconnectivity,Presence_CBr_At_Dist4,Sum_dO_EStates,Laplace_MoharIndex2,Num_RingTertiaryC,C026_chemical_substructure,Freq_CN_At_Dist2,Num_HBond_Donors_Atoms,Weighted_LeadingEigenvalue_Burden_Matrix,Intrinsic_State_Pseudoconnectivity_SAvg,Num_Nitrogen_Atoms,Weighted_SpectralMoment6_Burden_Matrix,Num_Esters,Num_Halogen_Atoms,Biodegradable
0,4.414,2.1543,0,0,1,0,0,30.0,0,0,2,0.000,2.736,0.802,9.183,0,0.970,1.149,0,0,0,1.165,1,0,0,0,2.101,-0.064,0,0.000,0.975,0,0,2,2,3.143,1.833,1,7.083,0,0,Yes
1,3.000,1.7389,1,0,0,0,0,25.0,2,0,0,0.000,3.426,0.918,6.594,0,0.985,1.136,0,0,0,1.383,0,1,0,0,1.414,0.691,0,0.000,1.333,0,0,0,0,6.867,2.083,0,11.561,0,1,No
2,4.560,4.4123,0,0,0,0,0,33.3,4,4,0,-0.945,3.979,3.022,10.432,10,0.987,1.139,0,0,0,1.183,0,0,0,0,2.156,0.000,0,23.321,6.935,0,0,0,0,3.542,2.250,0,8.631,0,0,Yes
3,4.973,3.6020,0,0,2,0,3,35.0,0,3,4,0.000,3.450,1.258,10.152,6,1.042,1.144,0,1,0,1.193,1,0,0,0,2.317,0.005,0,20.720,1.706,0,3,4,2,3.883,3.042,2,8.639,0,0,No
4,4.651,2.7156,0,0,0,0,0,31.3,0,1,0,0.292,2.826,0.917,9.502,3,0.998,1.148,0,0,0,1.190,1,0,0,0,2.214,-0.074,0,10.500,0.918,0,0,2,0,3.482,2.452,1,7.624,0,0,Yes

In [13]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Presence_CBr_At_Dist1,category,0.0,0.0,2.0,"0, 1"
1,Presence_CCl_At_Dist3,category,0.0,0.0,2.0,"0, 1"
2,N073_chemical_substructure,category,0.0,0.0,4.0,"0, 1, 2, 3"
3,Presence_CBr_At_Dist4,category,0.0,0.0,2.0,"0, 1"
4,C026_chemical_substructure,category,0.0,0.0,11.0,"0, 1, 2, 3, 4, 6, 5, 8, 10, 12"
5,Biodegradable,category,0.0,0.0,2.0,"No, Yes"
6,Laplace_Leading_Eigenvalue,float64,0.0,0.0,440.0,"4.414, 4.732, 4.0, 4.17, 4.562, 4.807, 4.303, 4.77, 4.499, 3.618"
7,Weighted_Balaban_Index_Barysz_Matrix,float64,0.0,0.0,1022.0,"2.7059, 3.1241, 2.4524, 3.2017, 2.0, 2.8789, 3.0152, 3.0864, 3.2243, 3.1334"
8,Percentage_C_Atoms,float64,0.0,0.0,188.0,"33.3, 40.0, 50.0, 25.0, 42.9, 28.6, 30.0, 37.5, 46.2, 41.2"
9,Sum_dssC_EStates,float64,0.0,0.0,384.0,"0.0, -2.514, -0.741, -0.185, -0.995, -0.117, -0.193, -0.671, -1.093, -0.271"
10,Weighted_HyperWiener_Index_Burden_Matrix,float64,0.0,0.0,756.0,"3.647, 3.66, 3.192, 3.462, 3.375, 3.37, 3.233, 3.764, 2.938, 2.997"
11,Lopping_Centric_Index,float64,0.0,0.0,373.0,"0.0, 0.875, 1.185, 0.881, 1.187, 1.16, 0.971, 1.459, 0.918, 0.802"
12,Laplace_Spectral_Moment6,float64,0.0,0.0,510.0,"9.54, 8.597, 9.183, 9.882, 9.833, 9.311, 10.099, 8.755, 7.408, 9.863"
13,Mean_Sanderson_Electronegativity,float64,0.0,0.0,167.0,"0.998, 0.979, 0.993, 0.974, 0.987, 1.014, 0.991, 0.983, 0.98, 0.985"
14,Mean_Ionization_Potential,float64,0.0,0.0,125.0,"1.127, 1.139, 1.14, 1.125, 1.129, 1.121, 1.146, 1.141, 1.132, 1.144"
15,Weighted_Normalized_SpectralPositiveSum_Burden_Matrix,float64,0.0,0.0,352.0,"1.195, 1.254, 1.296, 1.299, 1.28, 1.253, 1.261, 1.202, 1.215, 1.264"
16,Adjacency_LeadingEigenvalue,float64,0.0,0.0,329.0,"2.0, 2.236, 2.194, 1.848, 2.175, 2.303, 2.101, 1.902, 1.732, 2.136"
17,Intrinsic_State_Pseudoconnectivity,float64,0.0,0.0,205.0,"0.0, -0.008, 0.001, 0.004, -0.002, -0.001, 0.014, -0.025, 0.015, -0.007"
18,Sum_dO_EStates,float64,0.0,0.0,470.0,"0.0, 11.013, 9.431, 10.143, 10.87, 22.449, 10.535, 10.696, 10.645, 19.107"
19,Laplace_MoharIndex2,float64,0.0,0.0,553.0,"1.542, 0.975, 1.06, 0.95, 1.74, 1.481, 1.0, 1.14, 2.052, 1.707"
20,Weighted_LeadingEigenvalue_Burden_Matrix,float64,0.0,0.0,705.0,"3.309, 3.423, 4.009, 6.88, 3.497, 3.712, 3.573, 3.755, 3.882, 3.767"
21,Intrinsic_State_Pseudoconnectivity_SAvg,float64,0.0,0.0,624.0,"2.833, 2.167, 2.5, 2.667, 1.833, 2.0, 2.333, 2.25, 2.802, 2.315"
22,Weighted_SpectralMoment6_Burden_Matrix,float64,0.0,0.0,862.0,"9.118, 8.601, 8.128, 8.143, 8.506, 8.704, 8.68, 8.562, 8.015, 8.497"
23,Num_Heavy_Atoms,int64,0.0,0.0,11.0,"0, 1, 2, 3, 4, 6, 5, 7, 10, 8"
24,Freq_NN_At_Dist1,int64,0.0,0.0,4.0,"0, 1, 2, 3"
25,Freq_CN_At_Dist4,int64,0.0,0.0,16.0,"0, 2, 1, 3, 4, 6, 7, 11, 9, 8"
26,Num_ssssC_Atoms,int64,0.0,0.0,13.0,"0, 1, 2, 3, 4, 6, 9, 8, 5, 11"
27,Num_Substituted_BenzeneC,int64,0.0,0.0,15.0,"0, 2, 3, 4, 1, 6, 5, 8, 7, 9"
28,Num_Terminal_PrimaryC,int64,0.0,0.0,15.0,"0, 1, 2, 3, 4, 6, 5, 8, 9, 7"
29,Num_Oxygen_Atoms,int64,0.0,0.0,12.0,"0, 2, 1, 4, 3, 6, 5, 7, 8, 12"
30,Freq_CN_At_Dist3,int64,0.0,0.0,21.0,"0, 2, 4, 3, 1, 6, 8, 5, 12, 10"
31,Freq_CO_At_Dist3,int64,0.0,0.0,24.0,"0, 2, 4, 6, 8, 1, 3, 12, 9, 10"
32,Num_N_Hydrazine,int64,0.0,0.0,3.0,"0, 1, 2"
33,Num_Aromatic_Nitro_Groups,int64,0.0,0.0,4.0,"0, 1, 2, 3"
34,Num_CRX3,int64,0.0,0.0,4.0,"0, 1, 2, 3"
35,Num_Circuits,int64,0.0,0.0,13.0,"1, 0, 2, 3, 6, 4, 7, 5, 15, 10"
36,Num_RingTertiaryC,int64,0.0,0.0,8.0,"0, 1, 2, 4, 6, 3, 8, 5"
37,Freq_CN_At_Dist2,int64,0.0,0.0,16.0,"0, 2, 4, 3, 1, 6, 8, 5, 10, 18"
38,Num_HBond_Donors_Atoms,int64,0.0,0.0,8.0,"0, 1, 2, 3, 4, 6, 5, 7"
39,Num_Nitrogen_Atoms,int64,0.0,0.0,8.0,"0, 1, 2, 3, 4, 5, 6, 8"
40,Num_Esters,int64,0.0,0.0,5.0,"0, 2, 1, 4, 3"
41,Num_Halogen_Atoms,int64,0.0,0.0,17.0,"0, 1, 2, 3, 4, 6, 5, 8, 10, 12"

In [14]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
Laplace_Leading_Eigenvalue,1055.0,4.782644,0.546916,2.0000,6.4960
Weighted_Balaban_Index_Barysz_Matrix,1055.0,3.069508,0.831308,0.8039,9.1775
Num_Heavy_Atoms,1055.0,0.716588,1.462452,0.0000,12.0000
Freq_NN_At_Dist1,1055.0,0.042654,0.256010,0.0000,3.0000
Freq_CN_At_Dist4,1055.0,0.980095,2.332955,0.0000,36.0000
Num_ssssC_Atoms,1055.0,0.290047,1.073771,0.0000,13.0000
Num_Substituted_BenzeneC,1055.0,1.646445,2.224822,0.0000,18.0000
Percentage_C_Atoms,1055.0,37.055640,9.144466,0.0000,60.7000
Num_Terminal_PrimaryC,1055.0,1.376303,1.963521,0.0000,24.0000
Num_Oxygen_Atoms,1055.0,1.803791,1.775435,0.0000,12.0000
Freq_CN_At_Dist3,1055.0,1.436967,3.116577,0.0000,44.0000
Sum_dssC_EStates,1055.0,-0.197129,0.769662,-5.2560,4.7220
Weighted_HyperWiener_Index_Burden_Matrix,1055.0,3.476844,0.584150,1.5440,5.7010
Lopping_Centric_Index,1055.0,1.350716,0.786166,0.0000,4.4910
Laplace_Spectral_Moment6,1055.0,9.937381,0.928678,4.1740,12.6090
Freq_CO_At_Dist3,1055.0,3.630332,4.457243,0.0000,40.0000
Mean_Sanderson_Electronegativity,1055.0,1.013302,0.046494,0.9570,1.3110
Mean_Ionization_Potential,1055.0,1.131106,0.030143,1.0220,1.3770
Num_N_Hydrazine,1055.0,0.008531,0.101802,0.0000,2.0000
Num_Aromatic_Nitro_Groups,1055.0,0.073934,0.317475,0.0000,3.0000
Num_CRX3,1055.0,0.029384,0.217997,0.0000,3.0000
Weighted_Normalized_SpectralPositiveSum_Burden_Matrix,1055.0,1.238727,0.096466,0.8630,1.6410
Num_Circuits,1055.0,1.405687,4.788542,0.0000,147.0000
Adjacency_LeadingEigenvalue,1055.0,2.215641,0.226131,1.0000,2.8590
Intrinsic_State_Pseudoconnectivity,1055.0,-0.001206,0.158928,-1.0990,1.0730
Sum_dO_EStates,1055.0,8.780510,11.895889,0.0000,71.1670
Laplace_MoharIndex2,1055.0,2.668344,2.096607,0.4440,17.5370
Num_RingTertiaryC,1055.0,0.129858,0.644057,0.0000,8.0000
Freq_CN_At_Dist2,1055.0,1.274882,2.273994,0.0000,18.0000
Num_HBond_Donors_Atoms,1055.0,0.961137,1.257013,0.0000,7.0000
Weighted_LeadingEigenvalue_Burden_Matrix,1055.0,3.918240,0.999602,2.2670,10.6950
Intrinsic_State_Pseudoconnectivity_SAvg,1055.0,2.558417,0.642765,1.4670,5.8250
Num_Nitrogen_Atoms,1055.0,0.686256,1.090389,0.0000,8.0000
Weighted_SpectralMoment6_Burden_Matrix,1055.0,8.629492,1.241986,4.9170,14.7000
Num_Esters,1055.0,0.051185,0.318970,0.0000,4.0000
Num_Halogen_Atoms,1055.0,0.723223,2.239286,0.0000,27.0000

In [15]:
# Categorical Feature Statistics
cat_stats

                                value  count    pct
column                     rank
Biodegradable              1       No    699  66.26
                           2      Yes    356  33.74
C026_chemical_substructure 1        0    658  62.37
                           2        1    138  13.08
                           3        2    133  12.61
                           4        3     56   5.31
                           5        4     39   3.70
N073_chemical_substructure 1        0   1026  97.25
                           2        1     26   2.46
                           3        2      2   0.19
                           4        3      1   0.09
Presence_CBr_At_Dist1      1        0   1013  96.02
                           2        1     42   3.98
Presence_CBr_At_Dist4      1        0   1027  97.35
                           2        1     28   2.65
Presence_CCl_At_Dist3      1        0    899  85.21
                           2        1    156  14.79

In [16]:
# Target Distribution
target_df

               count    pct
Biodegradable
No               699  66.26
Yes              356  33.74

## Task Curation

In [17]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=10, n_splits=3, test_size=None

In [18]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [19]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to qsar_biodeg/019d4803-a135-7879-8007-9e3ffc50059b
019d4803-a135-7879-8007-9e3ffc50059b
492616a0e656e3ae61e70f61f026d37d169ef78321d4c05b03077e988b697b25