### Dataset and Task Metadata

In [67]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="polish_companies_bankruptcy",
    dataset_year="2010",
    domain_str="finance",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="http://archive.ics.uci.edu/dataset/365/polish+companies+bankruptcy+data",
    download_description="""
Download from UCI and uzip data to a predefined folder.
mkdir -p local-data-warehouse/polish_companies_bankruptcy/ && wget -P local-data-warehouse/polish_companies_bankruptcy/ https://archive.ics.uci.edu/static/public/365/polish+companies+bankruptcy+data.zip && unzip local-data-warehouse/polish_companies_bankruptcy/polish+companies+bankruptcy+data.zip -d local-data-warehouse/polish_companies_bankruptcy/
""",
    # References
    academic_reference_bibtex="""@article{Ziba2016EnsembleBT,
  title={Ensemble boosted trees with synthetic features generation in application to bankruptcy prediction},
  author={Maciej Ziȩba and Sebastian Klaudiusz Tomczak and Jakub M. Tomczak},
  journal={Expert Syst. Appl.},
  year={2016},
  volume={58},
  pages={93-101},
  url={https://api.semanticscholar.org/CorpusID:40512567}
}

""",
    academic_reference_bibtex_key="Ziba2016EnsembleBT",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
- We include only one of the five original classification datasets (year 5) for a task of bankruptcy prediction.
- We rename the columns.
- We drop duplicate columns.
- We convert target variable to categorical dtype.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="company_bankrupt",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="company_bankrupt",
)

## Preprocessing

In [68]:
import arff
import pandas as pd

with open(dataset_mold.path /"5year.arff") as f:
        data = arff.load(f)

df = pd.DataFrame(data["data"], columns=[x[0] for x in data["attributes"]])

target_feature = "company_bankrupt"
df.columns = feature_names = [
    "net_profit_to_total_assets",
    "total_liabilities_to_total_assets",
    "working_capital_to_total_assets",
    "current_assets_to_short_term_liabilities",
    "liquidity_days_ratio",
    "retained_earnings_to_total_assets",
    "ebit_to_total_assets",
    "book_value_equity_to_total_liabilities",
    "sales_to_total_assets",
    "equity_to_total_assets",
    "extended_profit_to_total_assets",
    "gross_profit_to_short_term_liabilities",
    "gross_profit_plus_depreciation_to_sales",
    "gross_profit_plus_interest_to_total_assets",
    "liabilities_days_ratio",
    "gross_profit_plus_depreciation_to_total_liabilities",
    "total_assets_to_total_liabilities",
    "gross_profit_to_total_assets",
    "gross_profit_to_sales",
    "inventory_days_ratio",
    "sales_growth_ratio",
    "operating_profit_to_total_assets",
    "net_profit_to_sales",
    "three_year_gross_profit_to_total_assets",
    "equity_minus_share_capital_to_total_assets",
    "net_profit_plus_depreciation_to_total_liabilities",
    "operating_profit_to_financial_expenses",
    "working_capital_to_fixed_assets",
    "log_total_assets",
    "net_liabilities_to_sales",
    "gross_profit_plus_interest_to_sales",
    "current_liabilities_days_ratio",
    "operating_expenses_to_short_term_liabilities",
    "operating_expenses_to_total_liabilities",
    "sales_profit_to_total_assets",
    "total_sales_to_total_assets",
    "current_assets_minus_inventories_to_long_term_liabilities",
    "constant_capital_to_total_assets",
    "sales_profit_to_sales",
    "liquid_assets_to_short_term_liabilities",
    "liabilities_to_adjusted_operating_profit",
    "operating_profit_to_sales",
    "receivables_plus_inventory_turnover_days",
    "receivables_days_ratio",
    "net_profit_to_inventory",
    "current_assets_minus_inventory_to_short_term_liabilities",
    "inventory_days_cost_ratio",
    "ebitda_to_total_assets",
    "ebitda_to_sales",
    "current_assets_to_total_liabilities",
    "short_term_liabilities_to_total_assets",
    "short_term_liabilities_days_cost_ratio",
    "equity_to_fixed_assets",
    "constant_capital_to_fixed_assets",
    "working_capital_absolute",
    "gross_margin",
    "adjusted_liquidity_ratio",
    "total_costs_to_total_sales",
    "long_term_liabilities_to_equity",
    "inventory_turnover_ratio",
    "receivables_turnover_ratio",
    "short_term_liabilities_days_ratio",
    "sales_to_short_term_liabilities",
    "sales_to_fixed_assets",
    target_feature,
]

df = df.rename(columns={"target": target_feature})
df[target_feature] = df[target_feature].map({"1": "Yes", "0": "No"}).astype("category")

# conflicting duplicates drop (without target column)
df = df.drop_duplicates(subset=[c for c in df.columns if c != task_mold.target_column_name])
df = df.reset_index(drop=True)

print("Data shape:", df.shape)

Data shape: (5850, 65)

In [69]:
# Use if needed to get see all cols of pandas dataframes
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
df.head()

,net_profit_to_total_assets,total_liabilities_to_total_assets,working_capital_to_total_assets,current_assets_to_short_term_liabilities,liquidity_days_ratio,retained_earnings_to_total_assets,ebit_to_total_assets,book_value_equity_to_total_liabilities,sales_to_total_assets,equity_to_total_assets,extended_profit_to_total_assets,gross_profit_to_short_term_liabilities,gross_profit_plus_depreciation_to_sales,gross_profit_plus_interest_to_total_assets,liabilities_days_ratio,gross_profit_plus_depreciation_to_total_liabilities,total_assets_to_total_liabilities,gross_profit_to_total_assets,gross_profit_to_sales,inventory_days_ratio,sales_growth_ratio,operating_profit_to_total_assets,net_profit_to_sales,three_year_gross_profit_to_total_assets,equity_minus_share_capital_to_total_assets,net_profit_plus_depreciation_to_total_liabilities,operating_profit_to_financial_expenses,working_capital_to_fixed_assets,log_total_assets,net_liabilities_to_sales,gross_profit_plus_interest_to_sales,current_liabilities_days_ratio,operating_expenses_to_short_term_liabilities,operating_expenses_to_total_liabilities,sales_profit_to_total_assets,total_sales_to_total_assets,current_assets_minus_inventories_to_long_term_liabilities,constant_capital_to_total_assets,sales_profit_to_sales,liquid_assets_to_short_term_liabilities,liabilities_to_adjusted_operating_profit,operating_profit_to_sales,receivables_plus_inventory_turnover_days,receivables_days_ratio,net_profit_to_inventory,current_assets_minus_inventory_to_short_term_liabilities,inventory_days_cost_ratio,ebitda_to_total_assets,ebitda_to_sales,current_assets_to_total_liabilities,short_term_liabilities_to_total_assets,short_term_liabilities_days_cost_ratio,equity_to_fixed_assets,constant_capital_to_fixed_assets,working_capital_absolute,gross_margin,adjusted_liquidity_ratio,total_costs_to_total_sales,long_term_liabilities_to_equity,inventory_turnover_ratio,receivables_turnover_ratio,short_term_liabilities_days_ratio,sales_to_short_term_liabilities,sales_to_fixed_assets,company_bankrupt
0,0.088238,0.55472,0.01134,1.0205,-66.5200,0.342040,0.109490,0.57752,1.0881,0.32036,0.109490,0.197600,0.096885,0.109490,1475.20,0.247420,1.8027,0.109490,0.077287,50.199,1.15740,0.135230,0.062287,0.41949,0.320360,0.209120,1.03870,0.026093,6.1267,0.377880,0.077287,155.330,2.3498,0.24377,0.135230,1.4493,571.3700,0.32101,0.095457,0.128790,0.111890,0.095457,127.30,77.096,0.452890,0.66883,54.621,0.107460,0.075859,1.01930,0.55407,0.42557,0.73717,0.73866,15182.0000,0.080955,0.275430,0.91905,0.002024,7.2711,4.7343,142.760,2.5568,3.2597,No
1,-0.006202,0.48465,0.23298,1.5998,6.1825,0.000000,-0.006202,1.06340,1.2757,0.51535,0.001329,-0.015967,0.037544,-0.006202,3693.40,0.098825,2.0634,-0.006202,-0.004862,59.923,1.01580,0.001289,-0.004862,NaN,0.080285,0.098825,0.17118,0.615450,4.0022,0.363810,0.000778,108.050,3.3779,2.70750,-0.036475,1.2757,5.2519,0.59380,-0.028591,0.057810,0.291670,0.001011,171.38,111.450,-0.029614,1.06060,58.258,-0.052809,-0.041395,1.28230,0.38846,0.29604,1.36140,1.56860,2341.8000,-0.028591,-0.012035,1.00470,0.152220,6.0911,3.2749,111.140,3.2841,3.3700,No
2,0.130240,0.22142,0.57751,3.6082,120.0400,0.187640,0.162120,3.05900,1.1415,0.67731,0.162120,0.732180,0.165680,0.162120,431.75,0.845390,4.5164,0.162120,0.143490,41.508,1.23620,0.145860,0.115280,0.23566,0.677310,0.701430,1.47370,2.872100,4.7622,0.050069,0.143490,81.653,4.4701,0.65878,0.145860,1.1698,NaN,0.67731,0.129100,1.319600,0.042587,0.129100,163.71,122.200,1.013700,3.02800,47.382,0.120800,0.106920,3.60820,0.22142,0.22371,3.36840,3.36840,33401.0000,0.123960,0.192290,0.87604,0.000000,8.7934,2.9870,71.531,5.1027,5.6188,No
3,-0.089951,0.88700,0.26927,1.5222,-55.9920,-0.073957,-0.089951,0.12740,1.2754,0.11300,-0.080792,-0.174450,0.084038,-0.089951,3020.50,0.120840,1.1274,-0.089951,-0.070525,47.698,1.09420,0.000000,-0.070525,NaN,0.064737,0.120840,0.00000,1.251900,4.0153,0.657790,-0.138650,253.910,1.4375,0.83567,0.014027,1.2754,1.9005,0.43830,0.010998,0.456220,0.149980,0.000000,157.30,109.600,-0.539690,1.19900,82.073,-0.197140,-0.154560,0.88491,0.51564,0.69565,0.52538,2.03780,2789.6000,0.418840,-0.796020,0.59074,2.878700,7.6524,3.3302,147.560,2.4735,5.9299,No
4,0.048179,0.55041,0.10765,1.2437,-22.9590,0.000000,0.059280,0.81682,1.5150,0.44959,0.091990,0.134190,0.055575,0.059280,2386.10,0.152970,1.8168,0.059280,0.039129,36.074,0.99455,0.067616,0.031802,0.00000,0.429200,0.132800,2.06710,0.238910,5.8823,0.363310,0.039129,140.120,2.6583,2.13360,0.364200,1.5150,6.3783,0.51225,0.240400,0.067283,0.198280,0.044632,125.21,89.134,0.321770,0.90475,46.538,0.042701,0.028186,0.99819,0.44176,0.37618,0.99779,1.13690,1.2437,0.240400,0.107160,0.77048,0.139380,10.1180,4.0950,106.430,3.4294,3.3622,No

## Data Checks

In [70]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 5,850
Columns: 65
Use sampling: False (sample size: 5,850)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['liquidity_days_ratio', 'working_capital_absolute', 'liquid_assets_to_short_term_liabilities', 'gross_profit_plus_depreciation_to_total_liabilities', 'gross_profit_plus_interest_to_sales', 'liabilities_days_ratio', 'operating_expenses_to_total_liabilities', 'gross_profit_to_short_term_liabilities', 'gross_profit_to_sales', 'net_profit_plus_depreciation_to_total_liabilities']
Rows remaining as candidates after top-10 filter: 10 (of 5,850)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [71]:
# Sample Rows
df_head

,net_profit_to_total_assets,total_liabilities_to_total_assets,working_capital_to_total_assets,current_assets_to_short_term_liabilities,liquidity_days_ratio,retained_earnings_to_total_assets,ebit_to_total_assets,book_value_equity_to_total_liabilities,sales_to_total_assets,equity_to_total_assets,extended_profit_to_total_assets,gross_profit_to_short_term_liabilities,gross_profit_plus_depreciation_to_sales,gross_profit_plus_interest_to_total_assets,liabilities_days_ratio,gross_profit_plus_depreciation_to_total_liabilities,total_assets_to_total_liabilities,gross_profit_to_total_assets,gross_profit_to_sales,inventory_days_ratio,sales_growth_ratio,operating_profit_to_total_assets,net_profit_to_sales,three_year_gross_profit_to_total_assets,equity_minus_share_capital_to_total_assets,net_profit_plus_depreciation_to_total_liabilities,operating_profit_to_financial_expenses,working_capital_to_fixed_assets,log_total_assets,net_liabilities_to_sales,gross_profit_plus_interest_to_sales,current_liabilities_days_ratio,operating_expenses_to_short_term_liabilities,operating_expenses_to_total_liabilities,sales_profit_to_total_assets,total_sales_to_total_assets,current_assets_minus_inventories_to_long_term_liabilities,constant_capital_to_total_assets,sales_profit_to_sales,liquid_assets_to_short_term_liabilities,liabilities_to_adjusted_operating_profit,operating_profit_to_sales,receivables_plus_inventory_turnover_days,receivables_days_ratio,net_profit_to_inventory,current_assets_minus_inventory_to_short_term_liabilities,inventory_days_cost_ratio,ebitda_to_total_assets,ebitda_to_sales,current_assets_to_total_liabilities,short_term_liabilities_to_total_assets,short_term_liabilities_days_cost_ratio,equity_to_fixed_assets,constant_capital_to_fixed_assets,working_capital_absolute,gross_margin,adjusted_liquidity_ratio,total_costs_to_total_sales,long_term_liabilities_to_equity,inventory_turnover_ratio,receivables_turnover_ratio,short_term_liabilities_days_ratio,sales_to_short_term_liabilities,sales_to_fixed_assets,company_bankrupt
0,0.088238,0.55472,0.01134,1.0205,-66.5200,0.342040,0.109490,0.57752,1.0881,0.32036,0.109490,0.197600,0.096885,0.109490,1475.20,0.247420,1.8027,0.109490,0.077287,50.199,1.15740,0.135230,0.062287,0.41949,0.320360,0.209120,1.03870,0.026093,6.1267,0.377880,0.077287,155.330,2.3498,0.24377,0.135230,1.4493,571.3700,0.32101,0.095457,0.128790,0.111890,0.095457,127.30,77.096,0.452890,0.66883,54.621,0.107460,0.075859,1.01930,0.55407,0.42557,0.73717,0.73866,15182.0000,0.080955,0.275430,0.91905,0.002024,7.2711,4.7343,142.760,2.5568,3.2597,No
1,-0.006202,0.48465,0.23298,1.5998,6.1825,0.000000,-0.006202,1.06340,1.2757,0.51535,0.001329,-0.015967,0.037544,-0.006202,3693.40,0.098825,2.0634,-0.006202,-0.004862,59.923,1.01580,0.001289,-0.004862,NaN,0.080285,0.098825,0.17118,0.615450,4.0022,0.363810,0.000778,108.050,3.3779,2.70750,-0.036475,1.2757,5.2519,0.59380,-0.028591,0.057810,0.291670,0.001011,171.38,111.450,-0.029614,1.06060,58.258,-0.052809,-0.041395,1.28230,0.38846,0.29604,1.36140,1.56860,2341.8000,-0.028591,-0.012035,1.00470,0.152220,6.0911,3.2749,111.140,3.2841,3.3700,No
2,0.130240,0.22142,0.57751,3.6082,120.0400,0.187640,0.162120,3.05900,1.1415,0.67731,0.162120,0.732180,0.165680,0.162120,431.75,0.845390,4.5164,0.162120,0.143490,41.508,1.23620,0.145860,0.115280,0.23566,0.677310,0.701430,1.47370,2.872100,4.7622,0.050069,0.143490,81.653,4.4701,0.65878,0.145860,1.1698,NaN,0.67731,0.129100,1.319600,0.042587,0.129100,163.71,122.200,1.013700,3.02800,47.382,0.120800,0.106920,3.60820,0.22142,0.22371,3.36840,3.36840,33401.0000,0.123960,0.192290,0.87604,0.000000,8.7934,2.9870,71.531,5.1027,5.6188,No
3,-0.089951,0.88700,0.26927,1.5222,-55.9920,-0.073957,-0.089951,0.12740,1.2754,0.11300,-0.080792,-0.174450,0.084038,-0.089951,3020.50,0.120840,1.1274,-0.089951,-0.070525,47.698,1.09420,0.000000,-0.070525,NaN,0.064737,0.120840,0.00000,1.251900,4.0153,0.657790,-0.138650,253.910,1.4375,0.83567,0.014027,1.2754,1.9005,0.43830,0.010998,0.456220,0.149980,0.000000,157.30,109.600,-0.539690,1.19900,82.073,-0.197140,-0.154560,0.88491,0.51564,0.69565,0.52538,2.03780,2789.6000,0.418840,-0.796020,0.59074,2.878700,7.6524,3.3302,147.560,2.4735,5.9299,No
4,0.048179,0.55041,0.10765,1.2437,-22.9590,0.000000,0.059280,0.81682,1.5150,0.44959,0.091990,0.134190,0.055575,0.059280,2386.10,0.152970,1.8168,0.059280,0.039129,36.074,0.99455,0.067616,0.031802,0.00000,0.429200,0.132800,2.06710,0.238910,5.8823,0.363310,0.039129,140.120,2.6583,2.13360,0.364200,1.5150,6.3783,0.51225,0.240400,0.067283,0.198280,0.044632,125.21,89.134,0.321770,0.90475,46.538,0.042701,0.028186,0.99819,0.44176,0.37618,0.99779,1.13690,1.2437,0.240400,0.107160,0.77048,0.139380,10.1180,4.0950,106.430,3.4294,3.3622,No

In [72]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,company_bankrupt,category,0.0,0.00,2.0,"No, Yes"
1,current_assets_minus_inventories_to_long_term_liabilities,float64,2525.0,43.16,3260.0,"4.1023, 2.7727, 2.4927, 1.7152, 2.7914, 2.9389, 0.4076, 0.4627, 1351.8, 0.9886"
2,operating_profit_to_financial_expenses,float64,390.0,6.67,4985.0,"0.0, 1.397, 2.6295, 1.3454, 14.201, 2.241, 3.0986, 0.7874, 1.502, 1.8854"
3,net_profit_to_inventory,float64,266.0,4.55,5420.0,"0.0, 0.161, 0.132, 1.5193, -0.5143, 0.6531, 2.907, 0.1741, 0.4562, 0.11"
4,inventory_turnover_ratio,float64,266.0,4.55,5369.0,"11.045, 11.257, 5.2512, 10.34, 12.16, 17.114, 12.364, 6.4642, 10.112, 10.667"
5,three_year_gross_profit_to_total_assets,float64,135.0,2.31,5551.0,"0.0, 0.2073, 0.1304, 0.735, 0.1345, 1.4774, 0.3742, 0.1843, 0.2438, 0.5494"
6,working_capital_to_fixed_assets,float64,106.0,1.81,5611.0,"1.2599, 1.0404, 1.1876, 1.4399, 0.1022, 1.3821, 1.5475, 2.4018, 2.5396, -0.2114"
7,equity_to_fixed_assets,float64,106.0,1.81,5462.0,"2.2499, 1.2624, 1.3602, 1.0391, 2.3016, 1.0107, 1.2216, 1.5962, 1.8225, 1.3816"
8,constant_capital_to_fixed_assets,float64,106.0,1.81,5349.0,"2.2499, 1.0371, 1.1296, 1.6298, 1.102, 1.5224, 1.001, 1.1915, 1.7416, 1.3109"
9,sales_to_fixed_assets,float64,106.0,1.81,5548.0,"6.7586, 1.8704, 2.682, 1.6959, 16.589, 1.3938, 1.8705, 2.6989, 0.8741, 1.4893"
10,sales_growth_ratio,float64,103.0,1.76,4420.0,"1.121, 1.0022, 1.1148, 1.1906, 1.3353, 1.2193, 1.2387, 1.0637, 1.0233, 1.0536"
11,liabilities_to_adjusted_operating_profit,float64,84.0,1.44,5593.0,"0.0, 0.1093, 0.2925, 0.2253, 0.1128, 0.2701, 0.1078, 0.1458, 0.1574, 0.0679"
12,current_liabilities_days_ratio,float64,46.0,0.79,5510.0,"0.0, 134.12, 111.64, 57.341, 100.83, 62.32, 48.78, 38.514, 112.12, 109.97"
13,short_term_liabilities_days_cost_ratio,float64,36.0,0.62,5499.0,"0.0, 0.1571, 0.1505, 0.15, 0.3674, 0.3059, 0.2124, 0.1055, 0.1949, 0.3013"
14,inventory_days_cost_ratio,float64,35.0,0.60,5394.0,"0.0, 126.64, 140.3, 33.904, 24.278, 26.403, 39.105, 11.051, 42.212, 15.301"
15,current_assets_to_short_term_liabilities,float64,21.0,0.36,5466.0,"1.0459, 1.6422, 1.0344, 1.1501, 1.1072, 1.3905, 1.7692, 1.029, 1.5094, 1.4348"
16,gross_profit_to_short_term_liabilities,float64,21.0,0.36,5685.0,"0.465, 0.2061, 0.1001, -0.1864, 0.0137, 0.5044, -0.2794, 1.3269, 0.2686, 0.2219"
17,operating_expenses_to_short_term_liabilities,float64,21.0,0.36,5592.0,"0.0, 4.7075, 4.0403, 2.0725, 3.2695, 5.1719, 5.1785, 12.223, 5.3323, 1.9037"
18,liquid_assets_to_short_term_liabilities,float64,21.0,0.36,5699.0,"0.0, 1.2077, 0.3246, 0.6165, 6.8793, 0.0059, 0.2555, 0.1311, 0.1729, 0.0754"
19,current_assets_minus_inventory_to_short_term_liabilities,float64,21.0,0.36,5550.0,"0.3202, 1.6204, 1.1699, 1.3217, 1.0043, 1.2142, 1.0492, 2.0799, 1.0586, 1.6191"
20,sales_to_short_term_liabilities,float64,21.0,0.36,5577.0,"2.3307, 3.6796, 4.2731, 5.6358, 2.1269, 7.2408, 14.691, 2.5748, 3.3463, 4.0783"
21,book_value_equity_to_total_liabilities,float64,18.0,0.31,5635.0,"1.2376, 1.1634, 1.3062, 1.0819, 1.9198, 0.3363, 0.7327, 1.8245, 2.1171, 2.9632"
22,gross_profit_plus_depreciation_to_total_liabilities,float64,18.0,0.31,5699.0,"1.0101, 0.1764, 1.195, 0.2435, 0.9301, 0.3115, 0.3472, 0.1564, -0.06, 2.2454"
23,total_assets_to_total_liabilities,float64,18.0,0.31,5448.0,"1.9046, 1.3363, 1.5194, 1.2871, 1.5152, 1.0192, 1.1631, 1.5508, 1.945, 2.9198"
24,net_profit_plus_depreciation_to_total_liabilities,float64,18.0,0.31,5667.0,"0.0, 0.1932, 0.2482, 0.2509, 0.1939, 0.5512, 1.0898, 0.5328, 1.2018, 0.3048"
25,operating_expenses_to_total_liabilities,float64,18.0,0.31,5688.0,"0.0, 3.5357, 1.1632, 4.3198, 1.6163, 7.0344, 13.644, 2.615, 2.0447, 1.1951"
26,current_assets_to_total_liabilities,float64,18.0,0.31,5506.0,"1.0454, 1.7137, 1.2839, 2.9458, 1.7068, 1.2581, 1.0375, 1.2891, 1.0433, 1.2161"
27,receivables_turnover_ratio,float64,15.0,0.26,5611.0,"10.096, 5.9772, 5.695, 13.983, 11.183, 9.4409, 7.2732, 16.789, 6.7081, 4.3754"
28,liquidity_days_ratio,float64,11.0,0.19,5778.0,"33.352, 0.0, -66.52, -162.35, 42.297, 38.437, -103.49, -21.624, 18.943, 80.303"
29,liabilities_days_ratio,float64,6.0,0.10,5690.0,"0.0, 305.44, 2069.4, 361.35, 1302.2, 1054.0, 337.44, 185.32, 162.55, 1309.1"
30,net_profit_to_total_assets,float64,3.0,0.05,5622.0,"0.0, 0.2229, 0.146, 0.0462, 0.1535, 0.2212, 0.2165, 0.1068, 0.159, 0.2559"
31,total_liabilities_to_total_assets,float64,3.0,0.05,5619.0,"0.0, 0.172, 0.3425, 0.402, 0.6158, 0.66, 0.2523, 0.3853, 1.0208, 0.5772"
32,working_capital_to_total_assets,float64,3.0,0.05,5653.0,"1.0, 0.2003, 0.4365, 0.1972, 0.4504, -0.0741, 0.5175, 0.3445, 0.4734, 0.3064"
33,retained_earnings_to_total_assets,float64,3.0,0.05,3539.0,"0.0, 0.1352, -0.0198, -0.247, 0.2011, 0.3378, 0.1212, 0.334, 0.1881, -0.3596"
34,ebit_to_total_assets,float64,3.0,0.05,5652.0,"0.0, 0.2443, 0.2314, 0.1438, 0.2044, 0.0256, 0.1402, 0.1461, 0.1589, 0.1085"
35,equity_to_total_assets,float64,3.0,0.05,5612.0,"1.0, 0.7477, 0.2406, 0.6575, 0.3497, 0.828, 0.5374, 0.4229, 0.5193, 0.4412"
36,extended_profit_to_total_assets,float64,3.0,0.05,5667.0,"0.0, 0.1482, 0.2571, 0.0931, 0.1426, 0.1647, 0.1341, 0.1668, 0.115, 0.1053"
37,gross_profit_plus_interest_to_total_assets,float64,3.0,0.05,5652.0,"0.0, 0.2443, 0.2314, 0.1438, 0.2044, 0.0256, 0.1402, 0.1461, 0.1589, 0.1085"
38,gross_profit_to_total_assets,float64,3.0,0.05,5652.0,"0.0, 0.2443, 0.2314, 0.1438, 0.2044, 0.0256, 0.1402, 0.1461, 0.1589, 0.1085"
39,operating_profit_to_total_assets,float64,3.0,0.05,5144.0,"0.0, 0.1437, 0.1706, 0.1637, 0.1396, 0.111, 0.0353, 0.1029, 0.062, 0.1608"
40,equity_minus_share_capital_to_total_assets,float64,3.0,0.05,5666.0,"0.5262, 0.3994, 0.6417, 0.0, 0.7256, 0.5013, 0.5942, 0.1512, 0.4501, 1.0"
41,log_total_assets,float64,3.0,0.05,5214.0,"4.1709, 3.4531, 4.1152, 4.1917, 3.5293, 3.8214, 3.6421, 4.225, 4.8609, 4.402"
42,sales_profit_to_total_assets,float64,3.0,0.05,5652.0,"0.0, 0.0126, 0.1018, 0.0, 0.1463, 0.0, 0.1301, -0.0137, 0.1165, 0.1244"
43,total_sales_to_total_assets,float64,3.0,0.05,5420.0,"1.2038, 1.3215, 1.5792, 1.1461, 1.5483, 1.1918, 1.4214, 1.1946, 1.2259, 1.0633"
44,constant_capital_to_total_assets,float64,3.0,0.05,5571.0,"1.0, 0.6142, 0.6994, 0.7477, 0.8079, 0.443, 0.7472, 0.828, 0.3497, 0.832"
45,ebitda_to_total_assets,float64,3.0,0.05,5613.0,"0.0, -0.0038, -0.0071, 0.1361, 0.1018, 0.0059, -0.0153, -0.0708, -0.1204, 0.0"
46,short_term_liabilities_to_total_assets,float64,3.0,0.05,5576.0,"0.0, 0.3019, 0.2665, 0.172, 0.3575, 0.1805, 0.1642, 0.2391, 0.3624, 0.7195"
47,adjusted_liquidity_ratio,float64,3.0,0.05,5572.0,"0.0, 0.1581, 0.1209, 0.1034, 0.1122, 0.1594, 0.1864, 0.3068, 0.3622, 0.2823"
48,long_term_liabilities_to_equity,float64,3.0,0.05,3254.0,"0.0, 0.5694, 0.282, 1.8236, 0.1681, 0.5866, 0.0053, 0.0064, 0.0082, 0.4899"
49,sales_to_total_assets,float64,1.0,0.02,4823.0,"1.0277, 1.0376, 1.0117, 1.0488, 1.0335, 1.0506, 1.0579, 1.081, 1.0482, 1.023"
50,gross_profit_plus_depreciation_to_sales,float64,0.0,0.00,5659.0,"0.0, 0.162, 0.2068, 0.1226, 0.0652, 0.106, 0.1073, 0.106, 0.0271, 0.0605"
51,gross_profit_to_sales,float64,0.0,0.00,5675.0,"0.0, 0.0378, 0.0898, 0.1394, 0.1081, 0.2863, 0.0123, 0.0594, 0.0036, 0.0144"
52,inventory_days_ratio,float64,0.0,0.00,5392.0,"0.0, 100.19, 69.508, 114.58, 35.148, 11.005, 20.857, 8.9365, 35.3, 55.717"
53,net_profit_to_sales,float64,0.0,0.00,5649.0,"0.0, 0.1914, 0.0008, 0.0645, 0.002, 0.0315, 0.1152, 0.0415, 0.0315, 0.0439"
54,net_liabilities_to_sales,float64,0.0,0.00,5622.0,"0.2685, 0.6125, 0.1227, 0.61, 0.2823, 0.2003, 0.2568, -0.0433, 0.0, 0.2012"
55,gross_profit_plus_interest_to_sales,float64,0.0,0.00,5699.0,"0.0, 0.0371, 0.0738, 0.1128, 0.0173, 0.0938, 0.1169, 0.0053, 0.1978, 0.0235"
56,sales_profit_to_sales,float64,0.0,0.00,5655.0,"0.0, 0.002, 0.0, 0.0144, 0.1247, 0.0, 0.1036, 0.1229, 0.0587, 0.0909"
57,operating_profit_to_sales,float64,0.0,0.00,5158.0,"0.0, 0.0, 0.0288, 0.0742, 0.0095, 0.0099, -0.1247, 0.1052, 0.049, 0.0485"
58,receivables_plus_inventory_turnover_days,float64,0.0,0.00,5347.0,"0.0, 117.68, 134.82, 105.27, 111.2, 113.77, 143.53, 126.11, 144.78, 80.253"
59,receivables_days_ratio,float64,0.0,0.00,5614.0,"0.0, 103.3, 109.6, 67.206, 21.74, 41.469, 54.412, 50.184, 77.096, 40.374"
60,ebitda_to_sales,float64,0.0,0.00,5601.0,"0.0, -0.0089, 0.0, 0.0037, 0.1061, 0.0385, -0.3908, 0.0939, 0.1395, -0.0077"
61,working_capital_absolute,float64,0.0,0.00,5718.0,"-11216.0, 2443.9, 1797.0, 13593.0, 10361.0, 853.4, 2284.0, 22830.0, 1538.8, 74884.0"
62,gross_margin,float64,0.0,0.00,5646.0,"1.0, 0.1037, 0.1032, 0.184, 0.1036, 0.1695, 0.1554, 0.1138, 0.1478, 0.1267"
63,total_costs_to_total_sales,float64,0.0,0.00,5115.0,"1.0053, 1.0505, 0.9943, 1.0115, 1.0179, 1.0107, 1.0095, 1.0002, 1.0, 1.0173"
64,short_term_liabilities_days_ratio,float64,0.0,0.00,5559.0,"0.0, 104.08, 102.89, 50.409, 101.31, 141.76, 117.87, 125.27, 132.22, 116.45"

In [73]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
net_profit_to_total_assets,5847.0,-0.023294,6.195176,-4.638900e+02,8.745900e+01
total_liabilities_to_total_assets,5847.0,0.465980,5.780655,-4.308700e+02,7.241600e+01
working_capital_to_total_assets,5847.0,0.188520,1.183425,-7.206700e+01,2.833600e+01
current_assets_to_short_term_liabilities,5829.0,4.900399,91.899109,-4.031100e-01,6.845800e+03
liquidity_days_ratio,5839.0,19.486962,21639.669002,-1.076400e+06,1.250100e+06
retained_earnings_to_total_assets,5847.0,0.022081,10.043177,-4.638900e+02,5.432500e+02
ebit_to_total_assets,5847.0,-0.113911,9.103459,-5.174800e+02,5.530000e+00
book_value_equity_to_total_liabilities,5832.0,5.738594,102.873905,-3.735100e+00,6.868500e+03
sales_to_total_assets,5849.0,1.592324,1.555000,-3.496000e+00,6.560700e+01
equity_to_total_assets,5847.0,0.545096,5.793182,-7.144400e+01,3.398500e+02
extended_profit_to_total_assets,5847.0,-0.011123,6.094070,-4.638900e+02,6.388000e+00
gross_profit_to_short_term_liabilities,5829.0,1.064803,35.454923,-2.318500e+02,2.470300e+03
gross_profit_plus_depreciation_to_sales,5850.0,0.357024,31.076943,-3.103400e+02,2.340200e+03
gross_profit_plus_interest_to_total_assets,5847.0,-0.113885,9.103460,-5.174800e+02,5.530000e+00
liabilities_days_ratio,5844.0,1040.420917,130793.033714,-9.632400e+06,1.341700e+06
gross_profit_plus_depreciation_to_total_liabilities,5832.0,1.176593,37.496171,-2.213300e+02,2.837400e+03
total_assets_to_total_liabilities,5832.0,6.834984,102.879802,-2.321000e-03,6.869500e+03
gross_profit_to_total_assets,5847.0,-0.104484,9.132077,-5.174800e+02,5.512500e+01
gross_profit_to_sales,5850.0,-0.091766,5.472714,-3.108000e+02,7.724400e+01
inventory_days_ratio,5850.0,56.764378,168.929907,-2.934000e+01,9.928500e+03
sales_growth_ratio,5747.0,2.473205,101.076218,-1.351500e+02,7.661500e+03
operating_profit_to_total_assets,5847.0,-0.005326,5.661407,-4.315900e+02,1.554100e+01
net_profit_to_sales,5850.0,-0.098355,5.446075,-3.108900e+02,7.724400e+01
three_year_gross_profit_to_total_assets,5715.0,0.138175,7.402653,-4.638900e+02,2.523400e+02
equity_minus_share_capital_to_total_assets,5847.0,0.373521,4.156411,-7.144400e+01,2.668600e+02
net_profit_plus_depreciation_to_total_liabilities,5832.0,1.081324,35.559992,-2.213300e+02,2.689100e+03
operating_profit_to_financial_expenses,5460.0,468.437395,10275.615673,-1.581300e+05,5.659400e+05
working_capital_to_fixed_assets,5744.0,10.294264,303.824567,-1.089700e+03,2.170100e+04
log_total_assets,5847.0,4.148226,0.834704,6.359000e-03,9.698300e+00
net_liabilities_to_sales,5850.0,0.854007,19.174990,-2.306000e+01,1.236700e+03
gross_profit_plus_interest_to_sales,5850.0,-0.067151,5.285206,-3.108000e+02,7.724400e+01
current_liabilities_days_ratio,5804.0,1395.011211,64161.779236,-2.551000e+02,4.277200e+06
operating_expenses_to_short_term_liabilities,5829.0,8.364612,102.904100,-1.433400e+00,7.590500e+03
operating_expenses_to_total_liabilities,5832.0,5.037562,100.747339,-1.601500e+01,7.590500e+03
sales_profit_to_total_assets,5847.0,-0.008481,5.657374,-4.315900e+02,1.554100e+01
total_sales_to_total_assets,5847.0,2.053971,12.840763,1.910000e-04,9.656600e+02
current_assets_minus_inventories_to_long_term_liabilities,3325.0,115.019877,1605.881714,-4.325800e+00,6.792200e+04
constant_capital_to_total_assets,5847.0,0.652662,7.151424,-7.144400e+01,4.677700e+02
sales_profit_to_sales,5850.0,0.016607,0.713292,-4.704700e+01,2.901100e+00
liquid_assets_to_short_term_liabilities,5829.0,2.208555,58.006557,-9.068600e+00,4.303200e+03
liabilities_to_adjusted_operating_profit,5766.0,2.210857,83.517990,-2.699900e+02,5.043300e+03
operating_profit_to_sales,5850.0,-0.015818,2.449800,-1.435200e+02,4.038600e+01
receivables_plus_inventory_turnover_days,5850.0,155.876781,786.597042,-3.975600e+03,4.051500e+04
receivables_days_ratio,5850.0,99.112522,723.503787,-3.946200e+03,4.051500e+04
net_profit_to_inventory,5584.0,67.320963,4898.643785,-3.037300e+03,3.660300e+05
current_assets_minus_inventory_to_short_term_liabilities,5829.0,4.014603,91.743807,-9.049000e+00,6.845800e+03
inventory_days_cost_ratio,5815.0,137.560898,3293.591127,-1.865800e+01,1.856100e+05
ebitda_to_total_assets,5847.0,-0.090935,7.114895,-5.425600e+02,1.554100e+01
ebitda_to_sales,5850.0,-0.071862,2.468783,-1.448000e+02,1.686600e+01
current_assets_to_total_liabilities,5832.0,4.172246,91.408121,-1.217500e-02,6.845800e+03
short_term_liabilities_to_total_assets,5847.0,0.427224,1.097176,-1.866100e-01,7.241600e+01
short_term_liabilities_days_cost_ratio,5814.0,0.734362,12.923576,-6.976400e-01,6.661100e+02
equity_to_fixed_assets,5744.0,11.259872,316.008018,-1.088700e+03,2.170200e+04
constant_capital_to_fixed_assets,5744.0,12.180452,322.227649,-1.088700e+03,2.170200e+04
working_capital_absolute,5850.0,10736.964744,79757.973637,-1.118500e+06,4.212200e+06
gross_margin,5850.0,0.056400,0.701322,-4.678800e+01,1.651000e+00
adjusted_liquidity_ratio,5847.0,-0.266008,18.519057,-1.236300e+03,8.798100e+01
total_costs_to_total_sales,5850.0,0.957377,0.861435,-1.643900e-01,4.778800e+01
long_term_liabilities_to_equity,5847.0,0.274436,5.862620,-1.849800e+02,3.081500e+02
inventory_turnover_ratio,5584.0,920.319674,64487.007513,-1.244000e+01,4.818700e+06
receivables_turnover_ratio,5835.0,10.965092,41.342725,-9.249300e-02,1.308500e+03
short_term_liabilities_days_ratio,5850.0,243.544388,6252.940749,-2.365300e+02,4.513800e+05
sales_to_short_term_liabilities,5829.0,9.129149,103.587209,-1.543200e+00,7.641300e+03
sales_to_fixed_assets,5744.0,65.846609,2161.654113,-3.726500e+00,1.581800e+05

In [74]:
# Categorical Feature Statistics
cat_stats

                      value  count    pct
column           rank
company_bankrupt 1       No   5442  93.03
                 2      Yes    408   6.97

In [75]:
# Target Distribution
target_df

                  count    pct
company_bankrupt
No                 5442  93.03
Yes                 408   6.97

## Task Curation

In [76]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [79]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [80]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019c94c4-3a12-71a4-946b-ffee38f41bc8
7ddfa229526c5ce105e25c051017c5fd7040747d3caa3ac3239ae4db8bda77e0