### Dataset and Task Metadata

In [93]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="soybean_large",
    dataset_year="1980",
    domain_str="biology & life sciences",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://archive.ics.uci.edu/dataset/90/soybean+large",
    download_description="""

mkdir -p local-data-warehouse/soybean_large/ && wget -P local-data-warehouse/soybean_large/ https://archive.ics.uci.edu/static/public/90/soybean+large.zip && unzip local-data-warehouse/soybean_large/soybean+large.zip -d local-data-warehouse/soybean_large/ && rm local-data-warehouse/soybean_large/soybean+large.zip
""",
    # References
    academic_reference_bibtex="""@article{Michalski1980LearningBB,
  title={Learning by Being Told and Learning from Examples: An Experimental Comparison of the Two Methods of Knowledge Acquisition in the Context of Developing an Expert System for Soybean Disease Diagnosis},
  author={Ryszard S. Michalski and R. L. Chilausky},
  journal={International Journal of Policy Analysis and Information Systems},
  year={1980},
  volume={4},
  number={2}
}
""",
    academic_reference_bibtex_key="Michalski1980LearningBB",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
    - We remove "2-4-d-injury" class as it has only a single sample.
    - We convert all attributes to categorical type.
    - Anomaly: the dataset contains missing values only for four classes ("phytophthora-rot","diaporthe-pod-&-stem-blight", "cyst-nematode", "herbicide-injury").
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="disease",
    problem_type="multiclass_classification",
    objective_metric_name="roc_auc",
    stratify_on="disease",
)

## Preprocessing

In [94]:
import pandas as pd
import numpy as np

column_names = [
"disease",
"date",
"plant-stand",
"precip",
"temp",
"hail",
"crop",
"area",
"severity",
"seed-tmt",
"germination",
"plant-growth",
"leaves",
"leafspots-halo",
"leafspots-marg",
"leafspot-size",
"leaf-shread",
"leaf-malf",
"leaf-mild",
"stem",
"lodging",
"stem-cankers",
"canker-lesion",
"fruiting-bodies",
"external decay",
"mycelium",
"int-discolor",
"sclerotia",
"fruit-pods",
"fruit spots",
"seed",
"mold-growth",
"seed-discolor",
"seed-size",
"shriveling",
"roots",
]

df = pd.read_csv(dataset_mold.path / "soybean-large.data", header=None, index_col=False, names=column_names)
df.replace("?", np.nan, inplace=True)
df = df[df["disease"]!="2-4-d-injury"]
df = df.astype('category')

df = df.sample(frac=1, random_state=99).reset_index(drop=True)

## Data Checks

In [95]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 306
Columns: 36
Use sampling: False (sample size: 306)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['date', 'area', 'canker-lesion', 'stem-cankers', 'severity', 'crop', 'fruit-pods', 'fruit spots', 'leaf-mild', 'fruiting-bodies']
Rows remaining as candidates after top-10 filter: 118 (of 306)

#### Duplicate Report
Total duplicate rows: 4 (1.31% of dataset)
Duplicate rows ignoring target: 4 (1.31% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [96]:
# Sample Rows
df_head

,disease,date,plant-stand,precip,temp,hail,crop,area,severity,seed-tmt,germination,plant-growth,leaves,leafspots-halo,leafspots-marg,leafspot-size,leaf-shread,leaf-malf,leaf-mild,stem,lodging,stem-cankers,canker-lesion,fruiting-bodies,external decay,mycelium,int-discolor,sclerotia,fruit-pods,fruit spots,seed,mold-growth,seed-discolor,seed-size,shriveling,roots
0,alternarialeaf-spot,4,0,2,1,0,2,2,z0,0,1,0,1,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,bacterial-blight,2,0,1,1,0,3,1,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,charcoal-rot,6,0,0,2,0,1,3,1,1,0,1,1,0,2,2,0,0,0,1,0,0,3,0,0,0,2,1,0,4,0,0,0,0,0,0
3,brown-stem-rot,5,0,0,1,0,3,2,1,0,1,0,1,0,2,2,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4,charcoal-rot,5,0,0,2,1,3,3,1,1,2,1,1,0,2,2,0,0,0,1,0,0,3,0,0,0,2,1,0,4,0,0,0,0,0,0

In [97]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,hail,category,40.0,13.07,2.0,"0, 1"
1,severity,category,40.0,13.07,4.0,"1, 0, 2, z0"
2,seed-tmt,category,40.0,13.07,3.0,"0, 1, 2"
3,lodging,category,40.0,13.07,2.0,"0, 1"
4,germination,category,35.0,11.44,3.0,"1, 2, 0"
5,fruiting-bodies,category,34.0,11.11,3.0,"0, 1, 3"
6,fruit spots,category,34.0,11.11,4.0,"0, 4, 1, 2"
7,seed-discolor,category,34.0,11.11,2.0,"0, 1"
8,shriveling,category,34.0,11.11,2.0,"0, 1"
9,leaf-mild,category,29.0,9.48,3.0,"0, 1, 2"
10,seed,category,28.0,9.15,2.0,"0, 1"
11,mold-growth,category,28.0,9.15,2.0,"0, 1"
12,seed-size,category,28.0,9.15,2.0,"0, 1"
13,leafspots-halo,category,25.0,8.17,3.0,"2, 0, 1"
14,leafspots-marg,category,25.0,8.17,3.0,"0, 2, 1"
15,leafspot-size,category,25.0,8.17,3.0,"1, 2, 0"
16,leaf-shread,category,25.0,8.17,2.0,"0, 1"
17,leaf-malf,category,25.0,8.17,2.0,"0, 1"
18,fruit-pods,category,24.0,7.84,4.0,"0, 1, 3, 2"
19,precip,category,10.0,3.27,3.0,"2, 1, 0"
20,stem-cankers,category,10.0,3.27,4.0,"0, 3, 1, 2"
21,canker-lesion,category,10.0,3.27,4.0,"0, 2, 1, 3"
22,external decay,category,10.0,3.27,2.0,"0, 1"
23,mycelium,category,10.0,3.27,2.0,"0, 1"
24,int-discolor,category,10.0,3.27,3.0,"0, 1, 2"
25,sclerotia,category,10.0,3.27,2.0,"0, 1"
26,plant-stand,category,7.0,2.29,2.0,"0, 1"
27,temp,category,6.0,1.96,3.0,"1, 2, 0"
28,roots,category,6.0,1.96,3.0,"0, 1, 2"
29,disease,category,0.0,0.00,18.0,"alternarialeaf-spot, brown-spot, phytophthora-rot, frog-eye-leaf-spot, brown-stem-rot, anthracnose, downy-mildew, purple-seed-stain, powdery-mildew, phyllosticta-leaf-spot"
30,date,category,0.0,0.00,7.0,"5, 4, 3, 2, 6, 1, 0"
31,crop,category,0.0,0.00,4.0,"2, 3, 1, 0"
32,area,category,0.0,0.00,4.0,"1, 3, 2, 0"
33,plant-growth,category,0.0,0.00,2.0,"0, 1"
34,leaves,category,0.0,0.00,2.0,"1, 0"
35,stem,category,0.0,0.00,2.0,"1, 0"

In [98]:
# Numeric Feature Statistics
numeric_stats

'No numeric features to summarize.'

In [99]:
# Categorical Feature Statistics
cat_stats

                                    value  count    pct
column          rank
area            1                       1    101  33.01
                2                       3     91  29.74
                3                       2     63  20.59
                4                       0     51  16.67
canker-lesion   1                       0    151  49.35
                2                       2     75  24.51
                3                       1     38  12.42
                4                       3     32  10.46
                5                    <NA>     10   3.27
crop            1                       2     99  32.35
                2                       3     93  30.39
                3                       1     79  25.82
                4                       0     35  11.44
date            1                       5     65  21.24
                2                       4     58  18.95
                3                       3     53  17.32
                4                       2     41  13.40
                5                       6     41  13.40
disease         1     alternarialeaf-spot     40  13.07
                2              brown-spot     40  13.07
                3        phytophthora-rot     40  13.07
                4      frog-eye-leaf-spot     40  13.07
                5          brown-stem-rot     20   6.54
external decay  1                       0    232  75.82
                2                       1     64  20.92
                3                    <NA>     10   3.27
fruit spots     1                       0    164  53.59
                2                       4     54  17.65
                3                    <NA>     34  11.11
                4                       1     29   9.48
                5                       2     25   8.17
fruit-pods      1                       0    193  63.07
                2                       1     53  17.32
                3                       3     30   9.80
                4                    <NA>     24   7.84
                5                       2      6   1.96
fruiting-bodies 1                       0    226  73.86
                2                       1     45  14.71
                3                    <NA>     34  11.11
                4                       3      1   0.33
germination     1                       1     99  32.35
                2                       2     88  28.76
                3                       0     84  27.45
                4                    <NA>     35  11.44
hail            1                       0    211  68.95
                2                       1     55  17.97
                3                    <NA>     40  13.07
int-discolor    1                       0    266  86.93
                2                       1     20   6.54
                3                       2     10   3.27
                4                    <NA>     10   3.27
leaf-malf       1                       0    268  87.58
                2                    <NA>     25   8.17
                3                       1     13   4.25
leaf-mild       1                       0    257  83.99
                2                    <NA>     29   9.48
                3                       1     10   3.27
                4                       2     10   3.27
leaf-shread     1                       0    233  76.14
                2                       1     48  15.69
                3                    <NA>     25   8.17
leafspot-size   1                       1    147  48.04
                2                       2    109  35.62
                3                       0     25   8.17
                4                    <NA>     25   8.17
leafspots-halo  1                       2    152  49.67
                2                       0    110  35.95
                3                    <NA>     25   8.17
                4                       1     19   6.21
leafspots-marg  1                       0    160  52.29
                2                       2    110  35.95
                3                    <NA>     25   8.17
                4                       1     11   3.59
leaves          1                       1    273  89.22
                2                       0     33  10.78
lodging         1                       0    248  81.05
                2                    <NA>     40  13.07
                3                       1     18   5.88
mold-growth     1                       0    247  80.72
                2                       1     31  10.13
                3                    <NA>     28   9.15
mycelium        1                       0    294  96.08
                2                    <NA>     10   3.27
                3                       1      2   0.65
plant-growth    1                       0    202  66.01
                2                       1    104  33.99
plant-stand     1                       0    160  52.29
                2                       1    139  45.42
                3                    <NA>      7   2.29
precip          1                       2    210  68.63
                2                       1     47  15.36
                3                       0     39  12.75
                4                    <NA>     10   3.27
roots           1                       0    260  84.97
                2                       1     33  10.78
                3                       2      7   2.29
                4                    <NA>      6   1.96
sclerotia       1                       0    286  93.46
                2                       1     10   3.27
                3                    <NA>     10   3.27
seed            1                       0    227  74.18
                2                       1     51  16.67
                3                    <NA>     28   9.15
seed-discolor   1                       0    244  79.74
                2                    <NA>     34  11.11
                3                       1     28   9.15
seed-size       1                       0    251  82.03
                2                    <NA>     28   9.15
                3                       1     27   8.82
seed-tmt        1                       0    140  45.75
                2                       1    106  34.64
                3                    <NA>     40  13.07
                4                       2     20   6.54
severity        1                       1    151  49.35
                2                       0     86  28.10
                3                    <NA>     40  13.07
                4                       2     28   9.15
                5                      z0      1   0.33
shriveling      1                       0    256  83.66
                2                    <NA>     34  11.11
                3                       1     16   5.23
stem            1                       1    166  54.25
                2                       0    140  45.75
stem-cankers    1                       0    179  58.50
                2                       3     72  23.53
                3                       1     24   7.84
                4                       2     21   6.86
                5                    <NA>     10   3.27
temp            1                       1    179  58.50
                2                       2     80  26.14
                3                       0     41  13.40
                4                    <NA>      6   1.96

In [100]:
# Target Distribution
target_df

                             count    pct
disease
alternarialeaf-spot             40  13.07
brown-spot                      40  13.07
phytophthora-rot                40  13.07
frog-eye-leaf-spot              40  13.07
brown-stem-rot                  20   6.54
anthracnose                     20   6.54
downy-mildew                    10   3.27
purple-seed-stain               10   3.27
powdery-mildew                  10   3.27
phyllosticta-leaf-spot          10   3.27
diaporthe-stem-canker           10   3.27
charcoal-rot                    10   3.27
bacterial-pustule               10   3.27
bacterial-blight                10   3.27
rhizoctonia-root-rot            10   3.27
diaporthe-pod-&-stem-blight      6   1.96
cyst-nematode                    6   1.96
herbicide-injury                 4   1.31

## Task Curation

In [101]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=20, n_splits=3, test_size=None

In [102]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)


splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [103]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019d0194-75df-7c19-9375-e31b17feec86
1a7cf6471a4a7c5a71a2631a7d51a96daad1a5946d7928b17286f34c3da661d5