### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="qsar_biodeg",
    dataset_year="2013",
    domain_str="biology & life sciences",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C5H60M",
    download_description="""
mkdir -p local-data-warehouse/qsar_biodeg/ && wget -P local-data-warehouse/qsar_biodeg/ https://archive.ics.uci.edu/static/public/254/qsar+biodegradation.zip && unzip local-data-warehouse/qsar_biodeg/qsar+biodegradation.zip -d local-data-warehouse/qsar_biodeg/ && rm local-data-warehouse/qsar_biodeg/qsar+biodegradation.zip
""",
    # References
    academic_reference_bibtex="""@article{mansouri2013quantitative,
  title={Quantitative structure--activity relationship models for ready biodegradability of chemicals},
  author={Mansouri, Kamel and Ringsted, Tine and Ballabio, Davide and Todeschini, Roberto and Consonni, Viviana},
  journal={Journal of chemical information and modeling},
  volume={53},
  number={4},
  pages={867--878},
  year={2013},
  publisher={ACS Publications}
}
""",
    academic_reference_bibtex_key="mansouri2013quantitative",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
- We added semantic meaningful feature names.
- Anomaly: several features are numeric-ordinal in nature but it is unclear if they are categorical features.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Biodegradable",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="Biodegradable",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(f"{dataset_mold.path}/biodeg.csv", sep=";")
target_feature = "Biodegradable"
df.columns  = [
    "Laplace_Leading_Eigenvalue",
    "Weighted_Balaban_Index_Barysz_Matrix",
    "Num_Heavy_Atoms",
    "Freq_NN_At_Dist1",
    "Freq_CN_At_Dist4",
    "Num_ssssC_Atoms",
    "Num_Substituted_BenzeneC",
    "Percentage_C_Atoms",
    "Num_Terminal_PrimaryC",
    "Num_Oxygen_Atoms",
    "Freq_CN_At_Dist3",
    "Sum_dssC_EStates",
    "Weighted_HyperWiener_Index_Burden_Matrix",
    "Lopping_Centric_Index",
    "Laplace_Spectral_Moment6",
    "Freq_CO_At_Dist3",
    "Mean_Sanderson_Electronegativity",
    "Mean_Ionization_Potential",
    "Num_N_Hydrazine",
    "Num_Aromatic_Nitro_Groups",
    "Num_CRX3",
    "Weighted_Normalized_SpectralPositiveSum_Burden_Matrix",
    "Num_Circuits",
    "Presence_CBr_At_Dist1",
    "Presence_CCl_At_Dist3",
    "N073_chemical_substructure", # no idea what this might be
    "Adjacency_LeadingEigenvalue",
    "Intrinsic_State_Pseudoconnectivity",
    "Presence_CBr_At_Dist4",
    "Sum_dO_EStates",
    "Laplace_MoharIndex2",
    "Num_RingTertiaryC",
    "C026_chemical_substructure",
    "Freq_CN_At_Dist2",
    "Num_HBond_Donors_Atoms",
    "Weighted_LeadingEigenvalue_Burden_Matrix",
    "Intrinsic_State_Pseudoconnectivity_SAvg",
    "Num_Nitrogen_Atoms",
    "Weighted_SpectralMoment6_Burden_Matrix",
    "Num_Esters",
    "Num_Halogen_Atoms",
    target_feature
]
df[target_feature] = df[target_feature].map({"RB": "Yes", "NRB": "No"})

cat_features = [
    target_feature,
    "Presence_CBr_At_Dist1",
    "Presence_CCl_At_Dist3",
    "N073_chemical_substructure",
    "Presence_CBr_At_Dist4",
    "C026_chemical_substructure"  # very likely categorical, but unclear
]
df[cat_features] = df[cat_features].astype("category")

# Shows a distribution shift, that means the original data was sorted
# by an order (by feature "Laplace_LeadingEigenvalue" and target). Vanishes if we
# shuffle here.
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 1,054
Columns: 42
Use sampling: False (sample size: 1,054)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['Weighted_Balaban_Index_Barysz_Matrix', 'Weighted_SpectralMoment6_Burden_Matrix', 'Weighted_HyperWiener_Index_Burden_Matrix', 'Weighted_LeadingEigenvalue_Burden_Matrix', 'Intrinsic_State_Pseudoconnectivity_SAvg', 'Laplace_MoharIndex2', 'Laplace_Spectral_Moment6', 'Sum_dO_EStates', 'Laplace_Leading_Eigenvalue', 'Sum_dssC_EStates']
Rows remaining as candidates after top-10 filter: 6 (of 1,054)

#### Duplicate Report
Total duplicate rows: 3 (0.28% of dataset)
Duplicate rows ignoring target: 3 (0.28% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,Laplace_Leading_Eigenvalue,Weighted_Balaban_Index_Barysz_Matrix,Num_Heavy_Atoms,Freq_NN_At_Dist1,Freq_CN_At_Dist4,Num_ssssC_Atoms,Num_Substituted_BenzeneC,Percentage_C_Atoms,Num_Terminal_PrimaryC,Num_Oxygen_Atoms,Freq_CN_At_Dist3,Sum_dssC_EStates,Weighted_HyperWiener_Index_Burden_Matrix,Lopping_Centric_Index,Laplace_Spectral_Moment6,Freq_CO_At_Dist3,Mean_Sanderson_Electronegativity,Mean_Ionization_Potential,Num_N_Hydrazine,Num_Aromatic_Nitro_Groups,Num_CRX3,Weighted_Normalized_SpectralPositiveSum_Burden_Matrix,Num_Circuits,Presence_CBr_At_Dist1,Presence_CCl_At_Dist3,N073_chemical_substructure,Adjacency_LeadingEigenvalue,Intrinsic_State_Pseudoconnectivity,Presence_CBr_At_Dist4,Sum_dO_EStates,Laplace_MoharIndex2,Num_RingTertiaryC,C026_chemical_substructure,Freq_CN_At_Dist2,Num_HBond_Donors_Atoms,Weighted_LeadingEigenvalue_Burden_Matrix,Intrinsic_State_Pseudoconnectivity_SAvg,Num_Nitrogen_Atoms,Weighted_SpectralMoment6_Burden_Matrix,Num_Esters,Num_Halogen_Atoms,Biodegradable
0,5.099,2.2523,0,0,0,1,0,35.1,2,2,0,1.470,3.533,1.938,10.469,3,0.983,1.135,0,0,0,1.209,1,0,0,0,2.236,-0.001,0,10.550,3.879,1,0,0,1,3.429,2.283,0,8.257,0,0,Yes
1,5.262,4.2718,2,0,0,1,0,25.0,2,0,0,0.000,3.317,0.863,10.026,0,1.230,1.269,0,0,1,1.042,0,0,0,0,2.175,0.172,0,0.000,1.435,0,0,0,0,3.997,4.972,0,8.663,0,5,No
2,4.560,4.4123,0,0,0,0,0,33.3,4,4,0,-0.945,3.979,3.022,10.432,10,0.987,1.139,0,0,0,1.183,0,0,0,0,2.156,0.000,0,23.321,6.935,0,0,0,0,3.542,2.250,0,8.631,0,0,Yes
3,4.973,3.6020,0,0,2,0,3,35.0,0,3,4,0.000,3.450,1.258,10.152,6,1.042,1.144,0,1,0,1.193,1,0,0,0,2.317,0.005,0,20.720,1.706,0,3,4,2,3.883,3.042,2,8.639,0,0,No
4,4.802,3.0226,0,0,1,0,2,50.0,0,0,2,0.000,3.174,0.000,9.805,0,0.985,1.109,0,0,0,1.359,3,0,0,1,2.323,0.013,0,0.000,0.950,0,0,3,1,3.868,1.981,1,8.357,0,0,Yes

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Presence_CBr_At_Dist1,category,0.0,0.0,2.0,"0, 1"
1,Presence_CCl_At_Dist3,category,0.0,0.0,2.0,"0, 1"
2,N073_chemical_substructure,category,0.0,0.0,4.0,"0, 1, 2, 3"
3,Presence_CBr_At_Dist4,category,0.0,0.0,2.0,"0, 1"
4,C026_chemical_substructure,category,0.0,0.0,11.0,"0, 1, 2, 3, 4, 6, 5, 8, 10, 12"
5,Biodegradable,category,0.0,0.0,2.0,"No, Yes"
6,Laplace_Leading_Eigenvalue,float64,0.0,0.0,440.0,"4.414, 4.732, 4.17, 4.0, 4.562, 4.303, 4.807, 4.77, 4.499, 3.618"
7,Weighted_Balaban_Index_Barysz_Matrix,float64,0.0,0.0,1021.0,"3.1356, 3.5332, 2.9372, 3.2017, 3.2896, 4.2631, 2.7059, 3.2439, 3.6943, 3.1387"
8,Percentage_C_Atoms,float64,0.0,0.0,188.0,"33.3, 50.0, 40.0, 25.0, 42.9, 28.6, 30.0, 37.5, 46.2, 41.2"
9,Sum_dssC_EStates,float64,0.0,0.0,384.0,"0.0, -1.093, -0.945, -0.117, -0.741, -0.875, -2.514, -0.888, -0.671, -0.481"
10,Weighted_HyperWiener_Index_Burden_Matrix,float64,0.0,0.0,755.0,"3.647, 3.192, 3.462, 3.375, 3.66, 3.233, 3.37, 3.351, 3.764, 3.678"
11,Lopping_Centric_Index,float64,0.0,0.0,373.0,"0.0, 0.875, 1.185, 0.881, 1.187, 1.16, 0.971, 1.459, 0.918, 0.802"
12,Laplace_Spectral_Moment6,float64,0.0,0.0,510.0,"9.54, 8.597, 9.183, 9.833, 9.882, 10.099, 9.311, 8.755, 8.16, 7.408"
13,Mean_Sanderson_Electronegativity,float64,0.0,0.0,167.0,"0.998, 0.979, 0.993, 0.974, 0.987, 0.991, 1.014, 0.98, 0.983, 1.007"
14,Mean_Ionization_Potential,float64,0.0,0.0,125.0,"1.127, 1.139, 1.14, 1.125, 1.129, 1.146, 1.121, 1.141, 1.144, 1.132"
15,Weighted_Normalized_SpectralPositiveSum_Burden_Matrix,float64,0.0,0.0,352.0,"1.254, 1.296, 1.299, 1.195, 1.253, 1.28, 1.211, 1.202, 1.264, 1.261"
16,Adjacency_LeadingEigenvalue,float64,0.0,0.0,329.0,"2.0, 2.236, 2.194, 1.848, 2.175, 2.101, 2.303, 1.902, 1.732, 2.136"
17,Intrinsic_State_Pseudoconnectivity,float64,0.0,0.0,204.0,"0.0, -0.008, 0.004, 0.001, -0.002, -0.001, 0.014, 0.015, -0.025, -0.007"
18,Sum_dO_EStates,float64,0.0,0.0,470.0,"0.0, 10.143, 9.431, 10.118, 22.449, 20.772, 10.696, 10.249, 20.135, 10.582"
19,Laplace_MoharIndex2,float64,0.0,0.0,553.0,"1.542, 0.975, 1.06, 0.95, 1.74, 1.0, 1.481, 2.052, 1.14, 2.488"
20,Weighted_LeadingEigenvalue_Burden_Matrix,float64,0.0,0.0,704.0,"3.423, 4.009, 6.88, 3.497, 3.309, 3.728, 3.795, 3.834, 3.648, 3.755"
21,Intrinsic_State_Pseudoconnectivity_SAvg,float64,0.0,0.0,623.0,"2.833, 2.167, 2.5, 2.667, 2.0, 1.833, 2.333, 2.25, 2.802, 3.133"
22,Weighted_SpectralMoment6_Burden_Matrix,float64,0.0,0.0,861.0,"8.143, 8.128, 8.562, 8.601, 9.118, 8.015, 8.497, 8.704, 8.68, 8.506"
23,Num_Heavy_Atoms,int64,0.0,0.0,11.0,"0, 1, 2, 3, 4, 6, 5, 7, 8, 10"
24,Freq_NN_At_Dist1,int64,0.0,0.0,4.0,"0, 1, 2, 3"
25,Freq_CN_At_Dist4,int64,0.0,0.0,16.0,"0, 2, 1, 3, 4, 6, 7, 11, 9, 5"
26,Num_ssssC_Atoms,int64,0.0,0.0,13.0,"0, 1, 2, 3, 4, 6, 9, 8, 5, 11"
27,Num_Substituted_BenzeneC,int64,0.0,0.0,15.0,"0, 2, 3, 4, 1, 6, 5, 8, 7, 9"
28,Num_Terminal_PrimaryC,int64,0.0,0.0,15.0,"0, 1, 2, 3, 4, 6, 5, 8, 9, 7"
29,Num_Oxygen_Atoms,int64,0.0,0.0,12.0,"0, 2, 1, 4, 3, 6, 5, 7, 8, 12"
30,Freq_CN_At_Dist3,int64,0.0,0.0,21.0,"0, 2, 4, 3, 1, 6, 8, 5, 12, 10"
31,Freq_CO_At_Dist3,int64,0.0,0.0,24.0,"0, 2, 4, 6, 8, 1, 3, 12, 9, 10"
32,Num_N_Hydrazine,int64,0.0,0.0,3.0,"0, 1, 2"
33,Num_Aromatic_Nitro_Groups,int64,0.0,0.0,4.0,"0, 1, 2, 3"
34,Num_CRX3,int64,0.0,0.0,4.0,"0, 1, 2, 3"
35,Num_Circuits,int64,0.0,0.0,13.0,"1, 0, 2, 3, 6, 4, 7, 5, 15, 10"
36,Num_RingTertiaryC,int64,0.0,0.0,8.0,"0, 1, 2, 4, 6, 3, 5, 8"
37,Freq_CN_At_Dist2,int64,0.0,0.0,16.0,"0, 2, 4, 3, 1, 6, 8, 5, 10, 18"
38,Num_HBond_Donors_Atoms,int64,0.0,0.0,8.0,"0, 1, 2, 3, 4, 6, 5, 7"
39,Num_Nitrogen_Atoms,int64,0.0,0.0,8.0,"0, 1, 2, 3, 4, 6, 5, 8"
40,Num_Esters,int64,0.0,0.0,5.0,"0, 2, 1, 4, 3"
41,Num_Halogen_Atoms,int64,0.0,0.0,17.0,"0, 1, 2, 3, 4, 6, 5, 10, 8, 7"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
Laplace_Leading_Eigenvalue,1054.0,4.783463,0.546527,2.0000,6.4960
Weighted_Balaban_Index_Barysz_Matrix,1054.0,3.069867,0.831621,0.8039,9.1775
Num_Heavy_Atoms,1054.0,0.717268,1.462980,0.0000,12.0000
Freq_NN_At_Dist1,1054.0,0.042694,0.256129,0.0000,3.0000
Freq_CN_At_Dist4,1054.0,0.981025,2.333867,0.0000,36.0000
Num_ssssC_Atoms,1054.0,0.290323,1.074244,0.0000,13.0000
Num_Substituted_BenzeneC,1054.0,1.648008,2.225299,0.0000,18.0000
Percentage_C_Atoms,1054.0,37.061006,9.147145,0.0000,60.7000
Num_Terminal_PrimaryC,1054.0,1.375712,1.964359,0.0000,24.0000
Num_Oxygen_Atoms,1054.0,1.805503,1.775407,0.0000,12.0000
Freq_CN_At_Dist3,1054.0,1.438330,3.117742,0.0000,44.0000
Sum_dssC_EStates,1054.0,-0.197316,0.770004,-5.2560,4.7220
Weighted_HyperWiener_Index_Burden_Matrix,1054.0,3.477195,0.584316,1.5440,5.7010
Lopping_Centric_Index,1054.0,1.349578,0.785670,0.0000,4.4910
Laplace_Spectral_Moment6,1054.0,9.938269,0.928671,4.1740,12.6090
Freq_CO_At_Dist3,1054.0,3.633776,4.457954,0.0000,40.0000
Mean_Sanderson_Electronegativity,1054.0,1.013353,0.046487,0.9570,1.3110
Mean_Ionization_Potential,1054.0,1.131096,0.030155,1.0220,1.3770
Num_N_Hydrazine,1054.0,0.008539,0.101850,0.0000,2.0000
Num_Aromatic_Nitro_Groups,1054.0,0.074004,0.317618,0.0000,3.0000
Num_CRX3,1054.0,0.029412,0.218099,0.0000,3.0000
Weighted_Normalized_SpectralPositiveSum_Burden_Matrix,1054.0,1.238763,0.096504,0.8630,1.6410
Num_Circuits,1054.0,1.407021,4.790620,0.0000,147.0000
Adjacency_LeadingEigenvalue,1054.0,2.215910,0.226070,1.0000,2.8590
Intrinsic_State_Pseudoconnectivity,1054.0,-0.001217,0.159003,-1.0990,1.0730
Sum_dO_EStates,1054.0,8.788841,11.898457,0.0000,71.1670
Laplace_MoharIndex2,1054.0,2.666617,2.096851,0.4440,17.5370
Num_RingTertiaryC,1054.0,0.129981,0.644351,0.0000,8.0000
Freq_CN_At_Dist2,1054.0,1.276091,2.274734,0.0000,18.0000
Num_HBond_Donors_Atoms,1054.0,0.962049,1.257261,0.0000,7.0000
Weighted_LeadingEigenvalue_Burden_Matrix,1054.0,3.919159,0.999630,2.2670,10.6950
Intrinsic_State_Pseudoconnectivity_SAvg,1054.0,2.559335,0.642378,1.4670,5.8250
Num_Nitrogen_Atoms,1054.0,0.686907,1.090701,0.0000,8.0000
Weighted_SpectralMoment6_Burden_Matrix,1054.0,8.630798,1.241851,4.9170,14.7000
Num_Esters,1054.0,0.051233,0.319118,0.0000,4.0000
Num_Halogen_Atoms,1054.0,0.723909,2.240238,0.0000,27.0000

In [7]:
# Categorical Feature Statistics
cat_stats

                                value  count    pct
column                     rank
Biodegradable              1       No    699  66.32
                           2      Yes    355  33.68
C026_chemical_substructure 1        0    657  62.33
                           2        1    138  13.09
                           3        2    133  12.62
                           4        3     56   5.31
                           5        4     39   3.70
N073_chemical_substructure 1        0   1025  97.25
                           2        1     26   2.47
                           3        2      2   0.19
                           4        3      1   0.09
Presence_CBr_At_Dist1      1        0   1012  96.02
                           2        1     42   3.98
Presence_CBr_At_Dist4      1        0   1026  97.34
                           2        1     28   2.66
Presence_CCl_At_Dist3      1        0    898  85.20
                           2        1    156  14.80

In [8]:
# Target Distribution
target_df

               count    pct
Biodegradable
No               699  66.32
Yes              355  33.68

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=10, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to qsar_biodeg/019d5d65-c601-77dd-80e6-8317575698cc
019d5d65-c601-77dd-80e6-8317575698cc
f9ff632037f62fe27a989787363d5760a566ff5f5661a5b39f67d9572a403a42