### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="climate_model_weather_forecasting_1m",
    version_from_unique_name="climate_model_weather_forecasting",
    version_comment="""
We randomly sub-sample the train to 1 million and test data 250k rows. We follow TabReD and use random sub-sampling. The idea behind this instead of a time-based subsampling is to keep data from various time periods and model the distribution shift across the full time horizon.
""",
    # Same as climate_model_weather_forecasting.ipynb
    dataset_year="2024",
    domain_str="environmental science & climate",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/datasets/pcovkrd84mejm/tabred-weather",
    download_description="""
We get the TabRed data from Kaggle.

kaggle datasets download -d pcovkrd84mejm/tabred-weather -f weather.parquet && unzip weather.parquet.zip && rm weather.parquet.zip && mkdir -p local-data-warehouse/climate_model_weather_forecasting && mv weather.parquet local-data-warehouse/climate_model_weather_forecasting/
""",
    # References
    academic_reference_bibtex="""@inproceedings{rubachev2025tabred,
  title={TabReD: Analyzing Pitfalls and Filling the Gaps in Tabular Deep Learning Benchmarks},
  author={Rubachev, Ivan and Kartashev, Nikolay and Gorishniy, Yury and Babenko, Artem},
  booktitle={The Thirteenth International Conference on Learning Representations},
  year={2025},
}
""",
    academic_reference_bibtex_key="rubachev2025tabred",
    license="CC-BY-NC-SA-4.0",
    data_tags=["Non-IID", "Temporal"],
    curation_comments="""
We start with data from TabRed, which already comes preprocessed.

- This data is similar to data from https://arxiv.org/abs/2406.19380. This paper also describes the feature in more detail. The column `apply_time_rl` is new and might relate to a rolling lag/window indicator.
- We drop duplicated columns `cmc_0_1_66_0` , `cmc_0_1_67_0`, `cmc_0_1_68_0`.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="fact_temperature",
    problem_type="regression",
    objective_metric_name="rmse",
    time_on="fact_time",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_parquet(dataset_mold.path / "weather.parquet")
print("Loaded data shape:", df.shape)

Loaded data shape: (16951828, 104)

In [3]:
df["fact_time"] = pd.to_datetime(df['fact_time'] * 10**6, unit='us')

# We take all bin + cat as Category
cat_cols = [
    "fact_station_id",
    "cmc_available",
    "gfs_available",
    "gfs_soil_temperature_available",
]
df[cat_cols] = df[cat_cols].astype("category")

df = df.drop(columns=["cmc_0_1_66_0" , "cmc_0_1_67_0", "cmc_0_1_68_0"])

df = df.sort_values(by="fact_time").reset_index(drop=True)

## Data Checks

In [4]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 16,951,828
Columns: 101
Use sampling: True (sample size: 1,695,183)
Get missing and unique counts per column...

missing/unique per-col:   0%|          | 0/101 [00:00<?, ?it/s]

Get example values per column...

examples per-col:   0%|          | 0/101 [00:00<?, ?it/s]

Get numeric feature statistics...

numeric stats:   0%|          | 0/96 [00:00<?, ?it/s]

Get cat stats...

cat stats:   0%|          | 0/5 [00:00<?, ?it/s]

Get target stats...

/home/lennart_priorlabs_ai/.venvs/tabarena_1503/lib/python3.11/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['gfs_wind_speed', 'gfs_precipitable_water', 'cmc_0_2_2_500', 'cmc_0_2_2_700', 'gfs_u_wind', 'sun_elevation', 'cmc_0_2_2_850', 'cmc_0_2_2_925', 'gfs_v_wind', 'cmc_0_2_2_1000']
Rows remaining as candidates after top-10 filter: 2,222,967 (of 16,951,828)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...

hash cols:   0%|          | 0/101 [00:00<?, ?it/s]

group check:   0%|          | 0/101 [00:00<?, ?it/s]

Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [5]:
# Sample Rows
df_head

,apply_time_rl,climate_pressure,climate_temperature,cmc_0_0_0_1000,cmc_0_0_0_2,cmc_0_0_0_2_grad,cmc_0_0_0_2_interpolated,cmc_0_0_0_2_next,cmc_0_0_0_500,cmc_0_0_0_700,cmc_0_0_0_850,cmc_0_0_0_925,cmc_0_0_6_2,cmc_0_0_7_1000,cmc_0_0_7_2,cmc_0_0_7_500,cmc_0_0_7_700,cmc_0_0_7_850,cmc_0_0_7_925,cmc_0_1_0_0,cmc_0_1_11_0,cmc_0_1_65_0,cmc_0_1_7_0,cmc_0_2_2_10,cmc_0_2_2_1000,cmc_0_2_2_500,cmc_0_2_2_700,cmc_0_2_2_850,cmc_0_2_2_925,cmc_0_2_3_10,cmc_0_2_3_1000,cmc_0_2_3_500,cmc_0_2_3_700,cmc_0_2_3_850,cmc_0_2_3_925,cmc_0_3_0_0,cmc_0_3_0_0_next,cmc_0_3_1_0,cmc_0_3_5_1000,cmc_0_3_5_500,cmc_0_3_5_700,cmc_0_3_5_850,cmc_0_3_5_925,cmc_0_6_1_0,cmc_available,cmc_horizon_h,cmc_precipitations,cmc_timedelta_s,fact_latitude,fact_longitude,fact_station_id,fact_temperature,fact_time,gfs_2m_dewpoint,gfs_a_vorticity,gfs_available,gfs_cloudness,gfs_clouds_sea,gfs_horizon_h,gfs_humidity,gfs_precipitable_water,gfs_precipitations,gfs_pressure,gfs_r_velocity,gfs_soil_temperature,gfs_soil_temperature_available,gfs_temperature_10000,gfs_temperature_15000,gfs_temperature_20000,gfs_temperature_25000,gfs_temperature_30000,gfs_temperature_35000,gfs_temperature_40000,gfs_temperature_45000,gfs_temperature_5000,gfs_temperature_50000,gfs_temperature_55000,gfs_temperature_60000,gfs_temperature_65000,gfs_temperature_7000,gfs_temperature_70000,gfs_temperature_75000,gfs_temperature_80000,gfs_temperature_85000,gfs_temperature_90000,gfs_temperature_92500,gfs_temperature_95000,gfs_temperature_97500,gfs_temperature_sea,gfs_temperature_sea_grad,gfs_temperature_sea_interpolated,gfs_temperature_sea_next,gfs_timedelta_s,gfs_total_clouds_cover_high,gfs_total_clouds_cover_low,gfs_total_clouds_cover_middle,gfs_u_wind,gfs_v_wind,gfs_wind_speed,sun_elevation,topography_bathymetry
0,1656558028,734.744141,23.885000,298.649963,297.296814,1.407745,297.296814,298.704559,267.778595,283.189850,291.702332,293.898102,295.657227,2.625,1.375,2.125535,4.125,4.375,1.000,0.0182,0.0,8.422675,0.00000,0.877924,0.772647,-5.611496,5.720599,2.837402,0.612900,0.296210,0.220421,3.490018,4.065887,-1.089508,1.441672,97478.437500,97565.968750,100995.914062,87.548309,5869.221191,3148.391846,1500.609863,769.788940,56.0,1,36.0,0.011733,0.0,4.320160,118.127998,35268,25.0,2022-07-01,22.911097,0.000161,1,2.595,0.0,30.0,89.099998,58.275848,0.000000,751.914673,0.146159,25.669336,1,-82.938423,-67.529655,-51.575737,-39.137672,-29.290472,-21.140112,-14.710913,-9.310003,-65.094414,-4.954230,-1.558600,2.462945,6.070032,-72.122322,9.213800,12.611872,15.726191,18.676172,21.579950,22.924250,24.248041,25.053217,24.911097,2.334290,24.911097,27.245386,0.0,97.199997,62.700001,99.599998,1.331523,-1.190918,1.786404,27.538477,31.0
1,1656594029,682.137329,20.146429,297.659454,294.297913,2.450745,294.297913,296.748657,268.292236,282.191803,291.044312,294.509247,292.370850,3.875,1.750,2.625003,2.500,1.625,2.000,0.0156,0.0,0.241825,0.00000,-0.263098,-0.262909,-2.932794,6.427920,2.073233,-0.233868,0.026389,0.038190,2.432056,3.227490,0.622314,-0.060648,90688.929688,90709.109375,101027.851562,89.782349,5864.768555,3143.176025,1502.508789,771.345093,64.0,1,24.0,0.000000,0.0,3.733333,115.683334,46359,21.0,2022-07-01,17.850000,0.000008,1,1.820,0.0,18.0,94.699997,39.771606,0.166667,663.337524,0.003005,19.769342,1,-80.992363,-68.254646,-51.409691,-38.887978,-29.477819,-20.929022,-14.847906,-9.100012,-64.959373,-4.854132,-1.389471,2.203210,6.637231,-71.010078,9.605280,12.475275,15.475275,18.363306,19.663355,21.193354,22.683344,24.117121,18.697718,4.441895,18.697718,23.139612,0.0,100.000000,11.600000,70.400002,0.367437,0.011404,0.367613,25.068970,1509.0
2,1656432623,756.472900,23.574999,296.515198,296.540222,0.231506,296.540222,296.771729,267.050110,282.358337,285.808411,290.770325,292.365417,4.375,4.000,29.752676,16.625,4.375,1.625,0.0139,0.0,9.708450,0.00000,0.194861,-0.094766,2.726224,3.046457,-1.268372,-2.827625,5.378507,8.946704,6.409439,2.512552,14.478537,12.460943,101138.687500,101180.195312,101668.359375,145.335785,5864.513672,3154.175293,1538.094849,820.568420,0.0,1,72.0,0.000050,0.0,-4.015000,39.606388,38476,21.0,2022-07-01,18.249994,0.000120,1,0.554,0.0,66.0,88.800003,36.322796,0.145833,751.373535,0.032187,23.469324,1,-75.153572,-66.856361,-54.670006,-43.636055,-31.866888,-23.480093,-16.964148,-12.690008,-63.268013,-6.578436,-2.019721,1.766199,5.802331,-71.943581,7.169641,8.204889,10.652216,13.322229,16.454126,17.985743,19.464136,20.608759,20.113794,0.442932,20.113794,20.556726,0.0,54.200001,1.200000,0.000000,1.278569,2.799758,3.077887,-47.322510,51.0
3,1656452423,755.665466,26.972857,300.841064,300.952606,4.552155,300.952606,305.504761,268.781464,284.036865,292.569824,295.932434,296.928253,3.875,3.875,4.625004,5.125,3.750,2.000,0.0187,0.0,2.502325,0.00000,2.430389,3.308334,2.983395,9.167071,12.292371,8.649988,0.605609,0.958218,-1.569424,-1.406763,0.386383,2.310815,100444.234375,100524.281250,100470.664062,41.993713,5845.444824,3113.958008,1465.367065,730.894470,36.0,1,60.0,0.000000,0.0,13.666389,100.606110,42204,28.0,2022-07-01,21.469324,-0.000030,1,1.880,0.0,60.0,68.300003,58.601189,0.000000,753.251099,0.008995,28.369349,1,-83.168816,-66.639442,-50.777794,-38.289421,-28.130072,-19.790976,-13.497869,-8.443151,-63.084663,-4.333197,-0.913428,3.454248,7.250909,-71.463402,10.153101,13.495874,16.763910,19.328608,21.224634,22.708612,24.296686,25.709345,27.822596,4.488495,27.822596,32.311089,0.0,100.000000,9.300000,78.699997,1.327954,0.859585,1.581881,14.875182,5.0
4,1656607817,754.365845,24.879286,298.859436,298.897888,1.250763,298.897888,300.148651,267.592224,283.641785,291.519318,295.209259,297.120850,1.875,1.625,3.125003,4.250,2.125,0.750,0.0198,0.0,11.951450,0.00039,5.886902,6.462091,-0.082794,15.502920,12.573233,14.141131,-2.861111,-3.061810,-2.617944,-4.022510,-9.302686,-6.110648,100088.929688,100237.109375,100639.851562,56.282349,5846.768555,3117.676025,1474.258789,741.845093,20.0,1,24.0,0.927258,0.0,6.816667,79.883331,42091,28.0,2022-07-01,23.050013,0.000096,1,0.435,0.0,18.0,86.400002,54.814804,0.041667,752.685120,-0.159995,25.469324,1,-79.432365,-67.134651,-51.869682,-40.687965,-30.307806,-21.899023,-15.137915,-9.310003,-62.549370,-5.384131,-0.939459,3.673212,7.037225,-73.320076,10.955286,13.555262,16.635279,17.463312,19.333368,21.023340,23.123346,25.177118,25.597712,2.541901,25.597712,28.139612,0.0,29.500000,10.500000,3.500000,3.747437,-0.978596,3.873104,-6.571712,9.0

In [6]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,cmc_available,category,0.0,0.00,2.0,"1, 0"
1,fact_station_id,category,0.0,0.00,1948.0,"23179, 36164, 26758, 37249, 26525, 23220, 26519, 26778, 26505, 33172"
2,gfs_available,category,0.0,0.00,2.0,"1, 0"
3,gfs_soil_temperature_available,category,0.0,0.00,2.0,"1, 0"
4,fact_time,datetime64[ns],0.0,0.00,234962.0,"2023-06-13 12:00:00, 2023-06-15 12:00:00, 2023-05-21 12:00:00, 2023-07-04 12:00:00, 2023-06-19 12:00:00, 2023-05-16 12:00:00, 2023-06-14 12:00:00, 2023-05-31 12:00:00, 2023-05-25 12:00:00, 2023-06-04 12:00:00"
5,cmc_0_0_0_1000,float32,329334.0,1.94,721463.0,"299.858, 301.0854, 299.2025, 299.3289, 298.8618, 298.621, 299.5639, 300.5511, 299.6708, 299.4365"
6,cmc_0_0_0_2,float32,329334.0,1.94,770746.0,"298.8351, 301.1435, 301.7872, 301.5845, 301.758, 300.3935, 300.7822, 300.5709, 300.1096, 299.0441"
7,cmc_0_0_0_2_interpolated,float32,329334.0,1.94,800715.0,"301.7872, 299.6221, 300.4998, 300.1971, 298.5805, 298.3188, 301.8187, 300.5104, 298.7034, 298.8351"
8,cmc_0_0_0_2_next,float32,329334.0,1.94,760150.0,"300.35, 301.0845, 301.5324, 299.2493, 300.2383, 297.3351, 300.8372, 298.8935, 299.8945, 299.1583"
9,cmc_0_0_0_500,float32,329334.0,1.94,421011.0,"268.3295, 267.7184, 268.2761, 267.887, 268.1498, 268.2513, 268.0501, 268.1144, 267.9138, 268.387"
10,cmc_0_0_0_700,float32,329334.0,1.94,390748.0,"283.5666, 283.5716, 282.8347, 283.2413, 283.335, 282.8469, 283.4164, 283.1341, 283.1564, 283.3995"
11,cmc_0_0_0_850,float32,329334.0,1.94,590716.0,"291.202, 291.7808, 291.7896, 291.8072, 291.1472, 291.1166, 291.4713, 291.327, 291.1829, 291.185"
12,cmc_0_0_0_925,float32,329334.0,1.94,675289.0,"295.3483, 295.4413, 295.4947, 294.9794, 295.6711, 295.2233, 294.5897, 294.9815, 296.0391, 295.1849"
13,cmc_0_0_6_2,float32,329334.0,1.94,609403.0,"296.8761, 296.6405, 296.1066, 297.1405, 296.8333, 297.0221, 296.7601, 297.1066, 296.3905, 297.1899"
14,cmc_0_0_7_1000,float32,329334.0,1.94,241.0,"3.875, 3.625, 3.75, 4.0, 3.375, 3.5, 4.125, 3.25, 3.125, 4.375"
15,cmc_0_0_7_2,float32,329334.0,1.94,1048.0,"0.25, 0.5, 0.75, 3.5, 3.75, 0.375, 3.0, 3.25, 1.0, 2.75"
16,cmc_0_0_7_500,float32,329334.0,1.94,2149769.0,"30.0, 3.875, 4.125, 4.5, 4.0, 3.75, 4.75, 4.25, 4.625, 5.0"
17,cmc_0_0_7_700,float32,329334.0,1.94,241.0,"30.0, 4.25, 4.0, 3.875, 3.75, 3.625, 4.125, 3.5, 3.25, 3.375"
18,cmc_0_0_7_850,float32,329334.0,1.94,241.0,"0.0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1.0, 1.125"
19,cmc_0_0_7_925,float32,329334.0,1.94,241.0,"0.0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 1.0, 1.5, 0.875"
20,cmc_0_1_0_0,float32,329334.0,1.94,88209.0,"0.0192, 0.0186, 0.0183, 0.0197, 0.0194, 0.0187, 0.0189, 0.0198, 0.0181, 0.02"
21,cmc_0_1_11_0,float32,329334.0,1.94,1.0,0.0
22,cmc_0_1_65_0,float32,329334.0,1.94,1600640.0,"0.0, 0.0, 0.0, 0.0001, 0.0002, 0.0003, 0.0001, 0.0002, 0.0003, 0.0003"
23,cmc_0_1_7_0,float32,329334.0,1.94,1824.0,"0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0001, 0.0001, 0.0001, 0.0001"
24,cmc_0_2_2_10,float32,329334.0,1.94,3815570.0,"-0.8, -0.57, -0.27, 0.21, -0.29, 1.0, -0.06, 0.45, -0.62, -0.11"
25,cmc_0_2_2_1000,float32,329334.0,1.94,4086859.0,"-0.71, 0.2646, 0.5878, -0.5104, 0.2286, -1.3526, 0.0614, -0.492, -0.8448, -0.198"
26,cmc_0_2_2_500,float32,329334.0,1.94,4996634.0,"-4.7288, -1.1696, -3.8551, -2.7211, 1.6756, -0.6688, -0.5354, -4.115, -3.2478, -1.7332"
27,cmc_0_2_2_700,float32,329334.0,1.94,4927672.0,"-1.6972, 1.1052, -4.4924, -2.0488, 0.835, -0.3255, -3.3614, -7.7074, -2.783, -2.4855"
28,cmc_0_2_2_850,float32,329334.0,1.94,4485656.0,"1.0225, -3.5367, -4.1713, -1.3077, 1.2807, -1.8634, 0.432, -1.0996, -1.987, -1.7128"
29,cmc_0_2_2_925,float32,329334.0,1.94,4324819.0,"-0.691, 0.532, -2.9248, 0.0054, 0.3328, -0.9504, -3.1818, -8.6724, 0.7819, 0.0472"
30,cmc_0_2_3_10,float32,329334.0,1.94,3585097.0,"0.39, -0.49, -1.25, 0.67, 0.73, -0.44, -0.62, -0.18, -0.41, -0.17"
31,cmc_0_2_3_1000,float32,329334.0,1.94,3799625.0,"-0.507, -0.1185, 2.4162, -0.4145, 0.668, -0.4288, -0.1491, 1.3251, 0.8557, -0.4031"
32,cmc_0_2_3_500,float32,329334.0,1.94,3315851.0,"1.4281, 0.9341, 0.453, 0.0926, 1.6384, 0.4154, 0.9738, -2.4259, -1.0479, 0.5507"
33,cmc_0_2_3_700,float32,329334.0,1.94,3383810.0,"2.7512, 0.7853, -1.1098, 0.1421, -1.0397, -0.7411, 1.4763, -2.0326, 0.8404, -1.818"
34,cmc_0_2_3_850,float32,329334.0,1.94,3432000.0,"-1.3924, -2.6642, 0.0999, -1.752, -0.8232, 1.3544, -2.4718, -0.0668, 1.6634, 1.3107"
35,cmc_0_2_3_925,float32,329334.0,1.94,3534843.0,"-0.409, 2.7375, -1.4969, 1.2255, -0.1689, 0.2925, 2.0055, 0.2787, -0.1569, 1.8977"
36,cmc_0_3_0_0,float32,329334.0,1.94,1415003.0,"100804.7812, 100941.5469, 100791.7656, 100806.125, 100612.4062, 100774.8125, 100740.2656, 100904.0312, 100819.9688, 100740.3125"
37,cmc_0_3_0_0_next,float32,329334.0,1.94,1415321.0,"100944.9062, 100982.4531, 100758.8594, 100965.4844, 100746.9062, 100693.5469, 100809.0312, 100827.9688, 100605.5469, 100834.9062"
38,cmc_0_3_1_0,float32,329334.0,1.94,360046.0,"101082.0234, 101067.5391, 100966.6016, 100925.1406, 101054.8828, 101217.3438, 100978.7578, 101078.2109, 101026.3281, 101003.4609"
39,cmc_0_3_5_1000,float32,329334.0,1.94,3223034.0,"82.4569, 92.6794, 95.0098, 95.9861, 101.6363, 84.1219, 79.4814, 91.5163, 95.3087, 87.2619"
40,cmc_0_3_5_500,float32,329334.0,1.94,362737.0,"5878.439, 5866.6162, 5865.1162, 5873.877, 5876.1733, 5875.2822, 5861.1992, 5870.9336, 5876.939, 5861.6973"
41,cmc_0_3_5_700,float32,329334.0,1.94,590656.0,"3157.7805, 3159.7158, 3160.8677, 3157.0063, 3145.6055, 3140.4419, 3156.2466, 3167.7844, 3151.1963, 3155.5298"
42,cmc_0_3_5_850,float32,329334.0,1.94,1081411.0,"1516.2639, 1510.9912, 1509.356, 1514.5139, 1511.2913, 1512.4436, 1521.5115, 1506.2771, 1508.3508, 1525.8689"
43,cmc_0_3_5_925,float32,329334.0,1.94,2021693.0,"780.5303, 783.9645, 773.4388, 772.9645, 789.4652, 794.989, 774.5453, 774.9454, 783.3755, 776.5177"
44,cmc_0_6_1_0,float32,329334.0,1.94,17.0,"0.0, 92.0, 8.0, 12.0, 20.0, 24.0, 88.0, 32.0, 36.0, 80.0"
45,cmc_precipitations,float32,329334.0,1.94,1233071.0,"0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
46,cmc_timedelta_s,float32,329334.0,1.94,12.0,"0.0, 7200.0, 3600.0, 10800.0, 21600.0, 18000.0, 14400.0, 32400.0, 28800.0, 25200.0"
47,gfs_2m_dewpoint,float32,52571.0,0.31,718262.0,"22.65, 23.15, 22.85, 22.75, 22.15, 23.25, 23.35, 22.35, 23.65, 22.25"
48,gfs_a_vorticity,float32,52571.0,0.31,3070539.0,"0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
49,gfs_cloudness,float32,52571.0,0.31,5603.0,"0.0, 1.0, 0.05, 0.017, 1.05, 0.033, 0.008, 0.001, 3.0, 0.002"
50,gfs_clouds_sea,float32,52571.0,0.31,6227.0,"0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
51,gfs_humidity,float32,52571.0,0.31,965.0,"76.2, 77.2, 77.8, 76.9, 76.7, 77.1, 75.8, 77.0, 75.6, 75.9"
52,gfs_precipitable_water,float32,52571.0,0.31,8123992.0,"49.9506, 45.1149, 58.725, 46.3877, 55.9195, 44.5981, 32.724, 53.4535, 38.9597, 34.6069"
53,gfs_precipitations,float32,52571.0,0.31,6410.0,"0.0, 0.0208, 0.0417, 0.0625, 0.0833, 0.1042, 0.125, 0.1458, 0.1667, 0.1875"
54,gfs_pressure,float32,52571.0,0.31,1643179.0,"756.2822, 755.9577, 755.7684, 756.8693, 755.1268, 755.6774, 756.288, 757.4066, 754.5001, 755.6406"
55,gfs_r_velocity,float32,52571.0,0.31,2674492.0,"0.0024, 0.0017, -0.0001, -0.0106, 0.0023, -0.0002, 0.0004, 0.0008, 0.003, -0.0037"
56,gfs_temperature_10000,float32,52571.0,0.31,1044403.0,"-78.8051, -78.13, -77.52, -80.0108, -80.1489, -78.4791, -79.14, -80.3335, -79.7207, -79.6515"
57,gfs_temperature_15000,float32,52571.0,0.31,641216.0,"-68.3, -68.16, -67.79, -68.03, -67.96, -68.05, -68.18, -68.44, -67.98, -67.2"
58,gfs_temperature_20000,float32,52571.0,0.31,633042.0,"-53.07, -53.23, -53.45, -53.5, -53.03, -53.48, -53.09, -53.2, -53.11, -53.8"
59,gfs_temperature_25000,float32,52571.0,0.31,748220.0,"-40.36, -41.06, -41.41, -40.41, -41.28, -40.69, -40.32, -40.68, -40.05, -39.94"
60,gfs_temperature_30000,float32,52571.0,0.31,797868.0,"-30.3, -30.45, -29.84, -30.26, -30.07, -30.43, -29.86, -29.88, -29.98, -30.19"
61,gfs_temperature_35000,float32,52571.0,0.31,774085.0,"-21.42, -21.67, -21.51, -21.59, -21.4, -21.82, -21.61, -21.88, -21.33, -21.85"
62,gfs_temperature_40000,float32,52571.0,0.31,615161.0,"-14.88, -14.79, -15.03, -15.07, -15.1, -14.97, -14.75, -15.0, -14.57, -15.29"
63,gfs_temperature_45000,float32,52571.0,0.31,472542.0,"-9.41, -9.75, -9.63, -9.72, -9.44, -9.57, -9.5, -9.85, -9.82, -9.66"
64,gfs_temperature_5000,float32,52571.0,0.31,830594.0,"-64.6, -64.11, -64.89, -64.19, -64.59, -65.04, -64.22, -64.23, -64.47, -65.13"
65,gfs_temperature_50000,float32,52571.0,0.31,428135.0,"-5.03, -5.1, -5.35, -4.85, -5.16, -4.88, -5.13, -4.79, -4.78, -4.82"
66,gfs_temperature_55000,float32,52571.0,0.31,414325.0,"-1.25, -1.1, -1.38, -1.0, -1.22, -1.16, -1.26, -1.13, -1.04, -1.29"
67,gfs_temperature_60000,float32,52571.0,0.31,413549.0,"2.12, 2.46, 2.65, 2.53, 2.03, 2.72, 2.24, 2.28, 2.75, 2.47"
68,gfs_temperature_65000,float32,52571.0,0.31,414094.0,"5.77, 6.06, 5.7, 6.36, 6.03, 5.85, 5.64, 6.42, 6.14, 5.98"
69,gfs_temperature_7000,float32,52571.0,0.31,956474.0,"-70.95, -71.48, -71.07, -70.81, -71.29, -71.73, -72.17, -71.18, -70.63, -72.34"
70,gfs_temperature_70000,float32,52571.0,0.31,430406.0,"9.65, 9.75, 9.28, 9.25, 10.15, 8.87, 9.53, 9.46, 9.4494, 9.48"
71,gfs_temperature_75000,float32,52571.0,0.31,489876.0,"13.15, 13.05, 13.25, 12.15, 12.55, 13.35, 12.45, 12.05, 12.85, 12.25"
72,gfs_temperature_80000,float32,52571.0,0.31,575265.0,"15.65, 15.45, 16.15, 15.95, 15.85, 15.05, 15.25, 15.55, 16.05, 15.75"
73,gfs_temperature_85000,float32,52571.0,0.31,669902.0,"17.95, 18.15, 19.05, 18.65, 18.25, 18.05, 18.55, 17.65, 17.55, 18.35"
74,gfs_temperature_90000,float32,52571.0,0.31,737029.0,"20.65, 20.95, 20.55, 21.15, 20.85, 19.95, 20.45, 20.75, 20.15, 20.05"
75,gfs_temperature_92500,float32,52571.0,0.31,759353.0,"21.65, 22.15, 22.05, 21.45, 20.95, 22.55, 22.25, 22.75, 21.55, 21.05"
76,gfs_temperature_95000,float32,52571.0,0.31,774043.0,"22.65, 22.45, 23.45, 22.95, 22.85, 22.55, 22.75, 23.05, 23.65, 23.85"
77,gfs_temperature_97500,float32,52571.0,0.31,785779.0,"24.65, 24.55, 24.95, 25.15, 25.55, 24.75, 25.05, 25.65, 25.45, 24.85"
78,gfs_temperature_sea,float32,52571.0,0.31,809811.0,"27.65, 28.15, 28.05, 27.15, 27.35, 27.55, 27.75, 27.25, 26.65, 27.45"
79,gfs_temperature_sea_interpolated,float32,52571.0,0.31,2068352.0,"27.65, 28.15, 28.05, 27.15, 27.35, 27.55, 27.75, 28.45, 26.65, 28.35"
80,gfs_temperature_sea_next,float32,52571.0,0.31,804562.0,"27.65, 28.15, 27.75, 28.05, 27.15, 27.85, 27.55, 28.35, 28.25, 26.65"
81,gfs_timedelta_s,float32,52571.0,0.31,5.0,"0.0, 7200.0, 3600.0, 10800.0, 14400.0"
82,gfs_total_clouds_cover_high,float32,52571.0,0.31,1001.0,"100.0, 0.0, 5.0, 1.7, 99.9, 3.3, 99.8, 0.8, 99.7, 99.6"
83,gfs_total_clouds_cover_low,float32,52571.0,0.31,1001.0,"0.0, 100.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.8, 0.6, 0.7"
84,gfs_total_clouds_cover_middle,float32,52571.0,0.31,1001.0,"0.0, 100.0, 5.0, 1.7, 3.3, 0.8, 0.1, 0.2, 0.3, 5.1"
85,gfs_u_wind,float32,52571.0,0.31,4893807.0,"-1.2494, 0.6262, 0.0201, 0.0382, -0.1925, 0.1561, -0.4155, -1.4194, -0.4487, -0.5907"
86,gfs_v_wind,float32,52571.0,0.31,4089518.0,"0.6487, 1.2525, 0.4386, 0.5315, 0.9292, -0.4966, 0.122, -1.5228, -0.3267, 0.1281"
87,gfs_wind_speed,float32,52571.0,0.31,10407790.0,"4.9685, 2.3523, 3.0262, 8.332, 2.3277, 2.721, 4.4021, 2.1264, 3.4943, 6.923"
88,climate_pressure,float32,0.0,0.00,683595.0,"755.985, 758.3328, 756.8459, 758.4553, 757.3801, 756.2293, 757.2292, 757.7924, 756.6022, 757.124"
89,climate_temperature,float32,0.0,0.00,63585.0,"28.2571, 28.0643, 27.9857, 28.0214, 26.6786, 28.1214, 27.8357, 28.05, 28.0143, 27.5286"
90,cmc_0_0_0_2_grad,float32,0.0,0.00,583939.0,"-9999.0, -0.0808, -0.1494, 0.094, -0.0554, -0.2837, -0.2306, -0.0472, -0.1422, -0.0887"
91,fact_latitude,float32,0.0,0.00,1789.0,"20.7856, 20.937, -16.8858, 7.3677, -12.2694, 20.8986, 21.0365, 21.1529, 22.9504, 13.584"
92,fact_longitude,float32,0.0,0.00,1885.0,"104.119, 104.7, -89.6577, 145.755, 134.544, 136.818, -156.43, -86.8771, -157.096, 120.206"
93,fact_temperature,float32,0.0,0.00,340.0,"26.0, 27.0, 28.0, 25.0, 29.0, 24.0, 30.0, 31.0, 23.0, 32.0"
94,gfs_soil_temperature,float32,0.0,0.00,204738.0,"-9999.0, 25.65, 26.15, 25.15, 24.65, 26.65, 27.15, 24.15, 25.55, 25.05"
95,gfs_temperature_sea_grad,float32,0.0,0.00,636331.0,"-9999.0, 0.0, -0.1, 0.1, -0.2, -0.5, -0.4, -0.3, -0.2, 0.2"
96,sun_elevation,float32,0.0,0.00,4621318.0,"48.4802, 38.3204, 85.3695, 6.4202, 68.8036, 22.5753, -49.6536, -35.6788, 69.9664, 38.325"
97,topography_bathymetry,float32,0.0,0.00,671.0,"6.0, 5.0, 7.0, 9.0, 10.0, 8.0, 4.0, 13.0, 17.0, 16.0"
98,cmc_horizon_h,float64,329334.0,1.94,37.0,"24.0, 18.0, 27.0, 30.0, 36.0, 21.0, 33.0, 48.0, 15.0, 39.0"
99,gfs_horizon_h,float64,52571.0,0.31,30.0,"30.0, 18.0, 24.0, 12.0, 27.0, 21.0, 33.0, 36.0, 42.0, 15.0"
100,apply_time_rl,int64,0.0,0.00,31635.0,"1680744617, 1690331109, 1688862306, 1672807219, 1688928621, 1685864714, 1688689511, 1689246917, 1687523110, 1686037515"

In [7]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
apply_time_rl,1695183.0,1.674947e+09,9.956256e+06,1.656381e+09,1.690743e+09
climate_pressure,1695183.0,7.437460e+02,2.576016e+01,5.547634e+02,7.752974e+02
climate_temperature,1695183.0,2.584963e+01,3.411622e+00,8.291429e+00,4.287500e+01
cmc_0_0_0_1000,1662082.0,2.996025e+02,3.461965e+00,2.728304e+02,3.171875e+02
cmc_0_0_0_2,1662082.0,2.992672e+02,3.866989e+00,2.720517e+02,3.168543e+02
cmc_0_0_0_2_grad,1695183.0,-1.951475e+02,1.383541e+03,-9.999000e+03,2.040555e+01
cmc_0_0_0_2_interpolated,1662082.0,2.993070e+02,3.773086e+00,2.717597e+02,3.168543e+02
cmc_0_0_0_2_next,1662082.0,2.993672e+02,3.801603e+00,2.710107e+02,3.169143e+02
cmc_0_0_0_500,1662082.0,2.678817e+02,1.804010e+00,2.479178e+02,2.762755e+02
cmc_0_0_0_700,1662082.0,2.830108e+02,1.711854e+00,2.648161e+02,2.914509e+02
cmc_0_0_0_850,1662082.0,2.911002e+02,2.636420e+00,2.686086e+02,3.052584e+02
cmc_0_0_0_925,1662082.0,2.951125e+02,3.134248e+00,2.729278e+02,3.109931e+02
cmc_0_0_6_2,1662082.0,2.943424e+02,3.936371e+00,2.622400e+02,3.019941e+02
cmc_0_0_7_1000,1662082.0,5.379268e+00,4.271395e+00,0.000000e+00,3.000000e+01
cmc_0_0_7_2,1662082.0,4.749505e+00,4.161044e+00,0.000000e+00,3.050000e+01
cmc_0_0_7_500,1662082.0,1.313754e+01,9.552938e+00,0.000000e+00,3.000019e+01
cmc_0_0_7_700,1662082.0,9.952430e+00,8.490211e+00,0.000000e+00,3.000000e+01
cmc_0_0_7_850,1662082.0,4.646937e+00,5.232271e+00,0.000000e+00,3.000000e+01
cmc_0_0_7_925,1662082.0,3.928131e+00,4.536635e+00,0.000000e+00,3.000000e+01
cmc_0_1_0_0,1662082.0,1.870756e-02,4.148796e-03,1.800000e-03,4.210000e-02
cmc_0_1_11_0,1662082.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
cmc_0_1_65_0,1662082.0,9.326291e+00,1.933018e+01,0.000000e+00,7.593793e+02
cmc_0_1_7_0,1662082.0,6.020239e-05,3.235894e-04,0.000000e+00,1.825000e-02
cmc_0_2_2_10,1662082.0,-8.253725e-01,3.038104e+00,-2.522404e+01,2.270840e+01
cmc_0_2_2_1000,1662082.0,-1.024457e+00,3.574151e+00,-2.529331e+01,2.284389e+01
cmc_0_2_2_500,1662082.0,-9.728881e-02,7.545266e+00,-3.542244e+01,6.052837e+01
cmc_0_2_2_700,1662082.0,-7.597052e-01,6.611619e+00,-3.515997e+01,4.005325e+01
cmc_0_2_2_850,1662082.0,-1.102703e+00,5.854738e+00,-3.670473e+01,3.593434e+01
cmc_0_2_2_925,1662082.0,-1.335294e+00,5.355800e+00,-3.441755e+01,3.185211e+01
cmc_0_2_3_10,1662082.0,1.924307e-01,2.405764e+00,-2.170880e+01,2.758275e+01
cmc_0_2_3_1000,1662082.0,2.233931e-01,2.870470e+00,-2.367524e+01,2.763605e+01
cmc_0_2_3_500,1662082.0,-6.252337e-02,3.920332e+00,-4.668539e+01,5.243542e+01
cmc_0_2_3_700,1662082.0,-1.912318e-01,3.647767e+00,-3.158777e+01,3.874612e+01
cmc_0_2_3_850,1662082.0,3.335000e-02,3.795924e+00,-3.257766e+01,3.900675e+01
cmc_0_2_3_925,1662082.0,2.964216e-01,3.910818e+00,-3.252135e+01,3.719289e+01
cmc_0_3_0_0,1662082.0,9.923539e+04,3.282552e+03,7.427557e+04,1.035324e+05
cmc_0_3_0_0_next,1662082.0,9.922751e+04,3.285318e+03,7.429256e+04,1.035042e+05
cmc_0_3_1_0,1662082.0,1.010990e+05,4.099249e+02,9.708810e+04,1.036876e+05
cmc_0_3_5_1000,1662082.0,9.552726e+01,3.573118e+01,-2.656981e+02,3.067552e+02
cmc_0_3_5_500,1662082.0,5.871654e+03,2.509295e+01,5.455264e+03,5.983320e+03
cmc_0_3_5_700,1662082.0,3.151570e+03,2.322692e+01,2.851133e+03,3.283682e+03
cmc_0_3_5_850,1662082.0,1.511331e+03,2.677225e+01,1.177477e+03,1.649269e+03
cmc_0_3_5_925,1662082.0,7.802732e+02,3.086059e+01,4.317573e+02,9.559338e+02
cmc_0_6_1_0,1662082.0,3.565231e+01,3.415084e+01,0.000000e+00,1.000000e+02
cmc_horizon_h,1662082.0,4.401453e+01,2.117208e+01,3.000000e+00,1.200000e+02
cmc_precipitations,1662082.0,2.153730e-01,9.109685e-01,-3.560384e-05,4.654596e+01
cmc_timedelta_s,1662082.0,2.714910e+03,3.821687e+03,0.000000e+00,3.960000e+04
fact_latitude,1695183.0,6.043778e+00,1.343474e+01,-2.761833e+01,3.236694e+01
fact_longitude,1695183.0,2.412601e+01,9.188271e+01,-1.798770e+02,1.793410e+02
fact_temperature,1695183.0,2.688207e+01,3.906368e+00,-2.000000e+00,6.000000e+01
gfs_2m_dewpoint,1689951.0,2.005768e+01,4.374558e+00,-1.707822e+01,2.835000e+01
gfs_a_vorticity,1689951.0,1.838937e-05,9.620053e-05,-1.447546e-03,2.421793e-03
gfs_cloudness,1689951.0,9.647070e-01,7.282160e-01,0.000000e+00,3.000000e+00
gfs_clouds_sea,1689951.0,4.541434e-08,1.455382e-06,0.000000e+00,3.125600e-04
gfs_horizon_h,1689951.0,4.148202e+01,2.093590e+01,3.000000e+00,9.000000e+01
gfs_humidity,1689951.0,7.251299e+01,1.774177e+01,3.900000e+00,1.000000e+02
gfs_precipitable_water,1689951.0,4.412473e+01,1.318945e+01,2.687534e+00,8.766817e+01
gfs_precipitations,1689951.0,2.264950e-01,6.756328e-01,-3.541667e-01,6.331250e+01
gfs_pressure,1689951.0,7.438247e+02,2.532726e+01,5.785797e+02,7.772802e+02
gfs_r_velocity,1689951.0,-1.190505e-02,2.020641e-01,-7.787729e+00,3.116042e+00
gfs_soil_temperature,1695183.0,-3.115541e+03,4.650302e+03,-9.999000e+03,5.125900e+01
gfs_temperature_10000,1689951.0,-7.839029e+01,3.689996e+00,-9.125848e+01,-5.653698e+01
gfs_temperature_15000,1689951.0,-6.701011e+01,2.067263e+00,-7.442915e+01,-5.130425e+01
gfs_temperature_20000,1689951.0,-5.318671e+01,1.802731e+00,-6.562663e+01,-3.877439e+01
gfs_temperature_25000,1689951.0,-4.114605e+01,2.190016e+00,-5.720185e+01,-2.459749e+01
gfs_temperature_30000,1689951.0,-3.101021e+01,2.437973e+00,-5.033759e+01,-1.392835e+01
gfs_temperature_35000,1689951.0,-2.264318e+01,2.432495e+00,-4.389063e+01,-7.098303e+00
gfs_temperature_40000,1689951.0,-1.580538e+01,2.250094e+00,-3.756156e+01,-2.128516e+00
gfs_temperature_45000,1689951.0,-1.017846e+01,2.004363e+00,-3.123867e+01,2.106042e+00
gfs_temperature_5000,1689951.0,-6.535069e+01,2.723717e+00,-8.023774e+01,-5.057804e+01
gfs_temperature_50000,1689951.0,-5.438876e+00,1.790782e+00,-2.503705e+01,5.352655e+00
gfs_temperature_55000,1689951.0,-1.352825e+00,1.689270e+00,-2.163215e+01,8.906122e+00
gfs_temperature_60000,1689951.0,2.409572e+00,1.675897e+00,-1.646409e+01,1.214153e+01
gfs_temperature_65000,1689951.0,5.965957e+00,1.682827e+00,-1.272733e+01,1.581964e+01
gfs_temperature_7000,1689951.0,-7.361217e+01,3.645704e+00,-8.899314e+01,-5.625930e+01
gfs_temperature_70000,1689951.0,9.244061e+00,1.761501e+00,-9.009771e+00,1.836645e+01
gfs_temperature_75000,1689951.0,1.231181e+01,1.957589e+00,-6.756842e+00,2.410360e+01
gfs_temperature_80000,1689951.0,1.519618e+01,2.299031e+00,-6.153510e+00,2.928396e+01
gfs_temperature_85000,1689951.0,1.786538e+01,2.768921e+00,-4.288916e+00,3.451302e+01
gfs_temperature_90000,1689951.0,2.049414e+01,3.202820e+00,-6.444763e-01,3.893029e+01
gfs_temperature_92500,1689951.0,2.186443e+01,3.357753e+00,-6.777405e-01,4.136593e+01
gfs_temperature_95000,1689951.0,2.333967e+01,3.445004e+00,1.499268e-01,4.313653e+01
gfs_temperature_97500,1689951.0,2.487338e+01,3.521018e+00,7.421204e-01,4.519369e+01
gfs_temperature_sea,1689951.0,2.604766e+01,4.069728e+00,3.700342e+00,4.700799e+01
gfs_temperature_sea_grad,1695183.0,-3.080650e+01,5.546493e+02,-9.999000e+03,2.049854e+01
gfs_temperature_sea_interpolated,1689951.0,2.607360e+01,3.961105e+00,3.743829e+00,4.674999e+01
gfs_temperature_sea_next,1689951.0,2.610217e+01,4.028543e+00,4.038019e+00,4.713549e+01
gfs_timedelta_s,1689951.0,2.608547e+03,3.168140e+03,0.000000e+00,1.440000e+04
gfs_total_clouds_cover_high,1689951.0,5.418385e+01,4.018475e+01,0.000000e+00,1.000000e+02
gfs_total_clouds_cover_low,1689951.0,2.000249e+01,2.798261e+01,0.000000e+00,1.000000e+02
gfs_total_clouds_cover_middle,1689951.0,2.228440e+01,3.373132e+01,0.000000e+00,1.000000e+02
gfs_u_wind,1689951.0,-8.692704e-01,3.236269e+00,-3.187201e+01,3.244725e+01
gfs_v_wind,1689951.0,2.369883e-01,2.555220e+00,-3.980941e+01,3.089396e+01
gfs_wind_speed,1689951.0,3.456582e+00,2.422067e+00,1.770425e-03,4.860036e+01
sun_elevation,1695183.0,9.287189e+00,4.459206e+01,-8.986047e+01,8.992464e+01
topography_bathymetry,1695183.0,1.072033e+02,3.341706e+02,-2.415000e+03,1.816000e+03

In [8]:
# Categorical Feature Statistics
cat_stats

                                                   value    count    pct
column                         rank
cmc_available                  1                       1  1662082  98.05
                               2                       0    33101   1.95
fact_station_id                1                   23179     3069   0.18
                               2                   36164     3049   0.18
                               3                   26758     3036   0.18
                               4                   37249     3035   0.18
                               5                   26525     3031   0.18
fact_time                      1     2023-06-13 12:00:00      505   0.03
                               2     2023-06-15 12:00:00      496   0.03
                               3     2023-05-21 12:00:00      494   0.03
                               4     2023-07-04 12:00:00      483   0.03
                               5     2023-06-19 12:00:00      481   0.03
gfs_available                  1                       1  1689951  99.69
                               2                       0     5232   0.31
gfs_soil_temperature_available 1                       1  1163952  68.66
                               2                       0   531231  31.34

In [9]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.0,-0.279,NaN,15.26,0.022,log1p,14551982.1,2.921207e+17,exponential

## Task Curation

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import subsample_temporal

date_col = task_mold.time_on
target_col = task_mold.target_column_name

df = df.sort_values(by=date_col).reset_index(drop=True)

test_time_min = df[date_col].max().normalize() - pd.DateOffset(weeks=1)

# Define indices
test_idx = df.index[df[date_col] >= test_time_min].to_numpy().tolist()
train_idx = df.index[
    df[date_col] < test_time_min
].to_numpy().tolist()

df, train_idx, test_idx = subsample_temporal(
    df=df,
    train_idx=train_idx,
    test_idx=test_idx,
    stratify_on=task_mold.stratify_on,
)

print("Train size:", len(train_idx), "| Test size:", len(test_idx))
print("Train target mean:", df.loc[train_idx, target_col].mean())
print("Test target mean:", df.loc[test_idx, target_col].mean())

splits = {0: {0: (train_idx, test_idx)}}

splits_mold = PredictiveMLSplitsMetadata(
    # We diverge from TabRed here, as TabRed use 1 month. But we think 1 week is more realistic for weather forecasting as there rarely exist long term forecasts longer than 1 week in reality and thus the horizon might be too much.
    splits_comment="We use the last week as test data and all prior data as train data.",
    splits=splits,
    time_horizon=7,
    time_horizon_unit="days",
)

Train size: 1000000 | Test size: 250000
Train target mean: 26.876877
Test target mean: 27.206684

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to climate_model_weather_forecasting/versions/019d307b-f29b-7d7a-ada3-a8786a9bc50b
019d307b-f29b-7d7a-ada3-a8786a9bc50b
51accd3a387e9d01ed23f601f119e6ab2d49ee0826f14e63b4f10d0d0f725932