### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="musk",
    dataset_year="1994",
    domain_str="chemistry & material science",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C51608",
    download_description="""
wget https://archive.ics.uci.edu/static/public/75/musk+version+2.zip && unzip musk+version+2.zip clean2.data.Z && uncompress clean2.data.Z && rm musk+version+2.zip && mkdir -p local-data-warehouse/musk && mv clean2.data local-data-warehouse/musk/
""",
    # References
    academic_reference_bibtex="""@article{dietterich1993comparison,
  title={A comparison of dynamic reposing and tangent distance for drug activity prediction},
  author={Dietterich, Thomas and Jain, Ajay and Lathrop, Richard and Lozano-Perez, Tomas},
  journal={Advances in neural information processing systems},
  volume={6},
  year={1993}
}
""",
    academic_reference_bibtex_key="dietterich1993comparison",
    license="CC BY 4.0",
    data_tags=["Non-IID", "Grouped"],
    curation_comments="""
- We rename the molecule IDs to remove the target leakage from the names.
- We drop the conformation name as it leaks information that the real task should not have (the correlation between specific conformations across samples).
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="class",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="class",
    group_on="molecule_name",
    group_labels="per_group",
)

## Preprocessing

In [2]:
import pandas as pd
import uuid

df = pd.read_csv(dataset_mold.path / "clean2.data", header=None, names=[
    "molecule_name", "conformation_name", *[f"feature_{i}" for i in range(166)], "class",
])
print("Loaded data shape:", df.shape)

df = df.drop(columns=["conformation_name"])

df["class"] = df["class"].map({0: "non-musk", 1: "musk"})

# Create mapping: molecule -> random string id
mapping = {val: uuid.uuid4().hex[:12] for val in df["molecule_name"].unique()}
df["molecule_name"] = df["molecule_name"].map(mapping)

as_cat_type = ["molecule_name", "class"]
df[as_cat_type] = df[as_cat_type].astype("category")


df = df.sample(frac=1, random_state=42).sort_values(by="molecule_name").reset_index(drop=True)

Loaded data shape: (6598, 169)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 6,598
Columns: 168
Use sampling: False (sample size: 6,598)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['feature_126', 'feature_72', 'feature_33', 'feature_20', 'feature_132', 'feature_55', 'feature_128', 'feature_139', 'feature_59', 'feature_47']
Rows remaining as candidates after top-10 filter: 860 (of 6,598)

#### Duplicate Report
Total duplicate rows: 17 (0.26% of dataset)
Duplicate rows ignoring target: 17 (0.26% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,molecule_name,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,feature_80,feature_81,feature_82,feature_83,feature_84,feature_85,feature_86,feature_87,feature_88,feature_89,feature_90,feature_91,feature_92,feature_93,feature_94,feature_95,feature_96,feature_97,feature_98,feature_99,feature_100,feature_101,feature_102,feature_103,feature_104,feature_105,feature_106,feature_107,feature_108,feature_109,feature_110,feature_111,feature_112,feature_113,feature_114,feature_115,feature_116,feature_117,feature_118,feature_119,feature_120,feature_121,feature_122,feature_123,feature_124,feature_125,feature_126,feature_127,feature_128,feature_129,feature_130,feature_131,feature_132,feature_133,feature_134,feature_135,feature_136,feature_137,feature_138,feature_139,feature_140,feature_141,feature_142,feature_143,feature_144,feature_145,feature_146,feature_147,feature_148,feature_149,feature_150,feature_151,feature_152,feature_153,feature_154,feature_155,feature_156,feature_157,feature_158,feature_159,feature_160,feature_161,feature_162,feature_163,feature_164,feature_165,class
0,012a2450ec85,42,-198,-108,-82,-117,-44,37,-83,-13,-29,-186,-166,-141,-202,-195,-302,-49,-75,-144,-69,-35,-16,-49,151,92,29,-47,-109,-100,99,-116,58,-25,39,-132,66,-169,79,-109,50,-184,104,-53,-176,-216,-298,-150,0,-103,-17,-107,-18,1,-130,100,-21,34,-161,-84,18,-101,-154,24,73,-151,57,-166,19,-124,1,-154,-117,-179,-195,-77,-182,-36,-164,-163,-69,5,11,-96,67,-29,41,-165,-50,-79,86,-202,72,-116,-148,29,-39,-129,42,-120,49,-208,135,-158,-178,-200,-186,-169,-30,-147,-203,-138,-32,-4,-16,-44,-9,164,59,51,-78,75,44,47,-107,-106,-9,2,90,-45,-188,18,-138,-47,-139,-160,-2,71,-62,-20,-86,-116,68,61,56,-178,-102,-120,-60,-143,7,-64,-125,-114,-127,99,-116,-237,-75,16,51,127,145,147,-59,-122,55,musk
1,012a2450ec85,42,-197,-148,-92,-117,64,66,-60,-22,5,-183,-101,-52,-194,-201,-302,27,-149,-105,-131,-55,-10,-71,169,96,-28,24,-126,42,73,-116,57,-29,-12,-132,63,-175,-37,-140,30,-179,105,-6,-176,-197,-299,-107,-58,-83,-68,-68,-27,-24,-127,130,-56,87,-153,67,52,-101,-149,24,31,-126,56,-166,-103,-123,-70,-162,-128,-137,-167,-153,-180,4,-161,-103,-54,-55,33,-44,-34,22,34,-121,-172,-9,117,-202,69,-113,-65,28,-41,-115,-1,-155,80,-202,133,-175,-184,-198,-188,-120,-41,-171,-193,-143,-46,-62,-53,-7,35,125,24,76,-9,87,151,149,-108,-105,-9,48,45,12,-187,16,-138,-96,-123,-174,-136,-13,-128,-75,-65,-59,1,58,10,-178,-103,-119,-84,-105,37,-67,-116,-112,-120,99,-73,-240,-165,-191,55,127,143,152,-60,-128,57,musk
2,012a2450ec85,42,-198,-159,-47,-117,-48,43,-81,-29,-65,-210,-123,-130,-201,-174,-302,32,-69,-90,-112,-89,-13,-59,-8,105,10,-23,-84,22,96,-116,57,-29,44,-131,63,-174,1,-140,-40,-184,105,-99,-192,-196,-324,-119,-84,-88,-95,-99,-16,-16,-112,165,-63,51,-151,10,40,-101,-150,24,46,-154,56,-166,-109,-123,-117,-169,-127,-167,-173,-159,-180,4,-180,-101,-68,-83,8,-45,80,4,36,-142,-72,12,69,-202,69,-114,-76,28,-40,-153,40,-155,28,-206,133,-166,-172,-193,-229,-177,-95,-161,-193,-155,-57,-65,-51,25,67,130,59,65,-28,79,146,106,-108,-106,-9,34,90,-1,-187,16,-138,-89,-132,-147,-102,45,-102,-46,-56,-33,-38,17,20,-178,-103,-119,-124,-136,-28,-67,-123,-112,-120,99,-75,-241,-56,-27,55,127,143,152,-60,-128,56,musk
3,012a2450ec85,41,-198,-149,-52,-117,53,66,-71,-26,5,-196,-103,-149,-193,-198,-303,34,-151,-107,-64,-49,-10,-77,157,82,-27,22,-127,-62,103,-116,56,-30,16,-131,64,-159,-35,-140,29,-180,105,-50,-176,-196,-307,-102,-62,-80,-6,-67,-30,-22,-128,137,-56,86,-154,-5,16,-101,-151,24,114,-131,57,-166,-104,-123,-71,-163,-128,-194,-164,-135,-180,4,-168,-113,-53,-58,33,-52,135,35,34,-123,-174,-53,133,-202,69,-116,-230,28,-38,-37,0,-155,79,-204,133,-176,-182,-196,-194,-116,-45,-166,-192,-142,-50,-67,-53,46,12,163,23,75,-11,84,84,109,-109,-107,-10,-28,84,-146,-187,18,-138,-82,-110,-170,-134,-7,-122,-76,-54,-71,0,58,11,-178,-102,-118,-85,-107,35,-67,-125,-113,-122,98,-78,-242,-298,68,55,127,143,152,-60,-127,58,musk
4,012a2450ec85,42,-191,-145,-93,-117,23,53,-106,-32,-62,-209,-131,-59,-182,-188,-300,50,-146,-123,-29,-19,-12,10,195,79,-33,50,-61,-74,112,-116,58,-24,-4,-133,64,-172,30,-122,34,-162,104,-48,-183,-188,-322,-103,-47,-105,-35,-77,-12,0,-116,37,-115,93,-133,-28,-9,-101,-153,25,92,-145,57,-166,-62,-117,-56,-156,-130,-110,-169,-113,-181,-12,-180,-130,-62,3,10,-35,23,-33,22,-78,-156,-94,125,-202,72,-115,-137,29,-42,-107,39,-154,76,-171,135,-161,-181,-184,-261,-181,-136,-151,-201,-155,11,21,18,-40,-9,140,46,87,33,105,62,109,-105,-103,-7,-35,81,-64,-188,16,-138,-67,-135,-167,-58,72,-47,-13,-50,-36,10,44,22,-178,-102,-121,-65,-76,51,-65,-126,-114,-120,99,-91,-236,-307,15,52,127,144,147,-60,-123,53,musk

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,molecule_name,category,0.0,0.0,102.0,"59d697ad6b2c, bc804ca89aca, 761ce578bca0, da38bb0fcd6f, 73f8d56fb62c, 1edbee62d29c, 56838374a453, b93b59f08f95, bf8e770e691e, a479898a1d69"
1,class,category,0.0,0.0,2.0,"non-musk, musk"
2,feature_0,int64,0.0,0.0,202.0,"44, 43, 35, 36, 46, 51, 48, 37, 47, 57"
3,feature_1,int64,0.0,0.0,260.0,"-198, -194, -199, -193, -192, -195, -196, -197, 86, -191"
4,feature_2,int64,0.0,0.0,221.0,"-145, -144, -112, -19, -22, -111, 31, -62, -23, -146"
5,feature_3,int64,0.0,0.0,257.0,"-76, -77, -69, 28, -70, 29, 33, 131, 32, 152"
6,feature_4,int64,0.0,0.0,129.0,"-117, -116, -115, -113, -112, -111, -114, -108, -110, -109"
7,feature_5,int64,0.0,0.0,358.0,"11, 10, 12, 86, 85, 54, 55, -154, 53, 52"
8,feature_6,int64,0.0,0.0,323.0,"56, 26, 57, -163, 27, -160, -162, -161, -164, -159"
9,feature_7,int64,0.0,0.0,389.0,"-95, -96, -103, 57, 64, -3, -171, -102, 67, -5"
10,feature_8,int64,0.0,0.0,347.0,"-40, -21, -22, -31, -231, -32, -233, -230, -232, -234"
11,feature_9,int64,0.0,0.0,399.0,"-22, -23, -24, 7, 8, 6, -25, 9, 5, -21"
12,feature_10,int64,0.0,0.0,387.0,"-242, -321, -50, -49, -53, -40, -54, -51, -48, -47"
13,feature_11,int64,0.0,0.0,384.0,"-113, -112, -214, -24, -23, -25, -212, -114, -22, -215"
14,feature_12,int64,0.0,0.0,397.0,"-68, -67, -69, -56, -66, -55, -62, -64, -53, -61"
15,feature_13,int64,0.0,0.0,329.0,"-283, -287, -83, -72, -286, -74, -71, -100, -285, -76"
16,feature_14,int64,0.0,0.0,319.0,"-283, -284, -282, -285, -281, -76, -75, -74, -73, -94"
17,feature_15,int64,0.0,0.0,327.0,"-302, -301, -303, -300, -298, -299, -304, -297, -295, -288"
18,feature_16,int64,0.0,0.0,350.0,"53, 52, 54, -214, -218, -213, 55, -215, -217, -212"
19,feature_17,int64,0.0,0.0,375.0,"-76, -75, -77, -53, -81, -80, -55, -52, -56, -58"
20,feature_18,int64,0.0,0.0,398.0,"-191, -99, -190, -100, -192, -98, 14, 13, -193, -101"
21,feature_19,int64,0.0,0.0,388.0,"-47, -46, -48, -184, -45, -44, -42, -29, -43, -35"
22,feature_20,int64,0.0,0.0,419.0,"-62, -61, -60, -29, -63, -28, -64, -59, -27, -30"
23,feature_21,int64,0.0,0.0,304.0,"-184, -180, -22, -15, -183, -14, -181, -10, -16, -11"
24,feature_22,int64,0.0,0.0,397.0,"2, -42, 21, -43, 3, 19, 20, 18, 1, 17"
25,feature_23,int64,0.0,0.0,368.0,"-63, -64, -65, -66, -62, -61, -67, 184, -68, 185"
26,feature_24,int64,0.0,0.0,304.0,"-95, -98, 111, 81, -96, 80, -97, -94, 92, -99"
27,feature_25,int64,0.0,0.0,379.0,"-34, 22, 23, -33, 24, -35, -49, 21, -206, -39"
28,feature_26,int64,0.0,0.0,338.0,"-20, -19, 48, 47, 28, 46, 45, 29, -170, 44"
29,feature_27,int64,0.0,0.0,272.0,"-157, -134, -160, -156, -154, -158, -159, -161, -153, -155"
30,feature_28,int64,0.0,0.0,278.0,"25, 9, 11, -66, 8, 10, 26, 5, -65, 14"
31,feature_29,int64,0.0,0.0,341.0,"104, 69, 68, -144, 105, -143, -145, -142, -146, -141"
32,feature_30,int64,0.0,0.0,276.0,"-116, -117, -114, -115, -113, -108, -110, -107, -112, -111"
33,feature_31,int64,0.0,0.0,334.0,"139, 136, 137, 129, 138, -105, -103, -92, -35, -102"
34,feature_32,int64,0.0,0.0,240.0,"-121, -13, -14, -9, -122, -11, -15, -29, -24, -22"
35,feature_33,int64,0.0,0.0,419.0,"5, 4, 6, 12, 7, 13, 15, 14, 16, 11"
36,feature_34,int64,0.0,0.0,243.0,"-122, -156, -155, -14, -157, -23, -129, -137, -128, -133"
37,feature_35,int64,0.0,0.0,261.0,"87, 74, 151, 156, 104, 93, 141, 81, 174, 159"
38,feature_36,int64,0.0,0.0,288.0,"-175, -174, -163, -172, -164, -173, -167, -171, -168, -166"
39,feature_37,int64,0.0,0.0,324.0,"73, 4, -153, -152, 3, 2, 64, 5, -149, -118"
40,feature_38,int64,0.0,0.0,217.0,"-145, -144, -146, -31, -25, -26, -20, -27, -28, -143"
41,feature_39,int64,0.0,0.0,322.0,"70, 39, 69, -128, -131, 38, 95, -109, 36, 71"
42,feature_40,int64,0.0,0.0,231.0,"-172, -178, -48, -176, -179, -184, -43, -177, -44, -49"
43,feature_41,int64,0.0,0.0,329.0,"-10, -21, 26, 27, -137, -11, -138, -9, 88, 101"
44,feature_42,int64,0.0,0.0,407.0,"-29, -27, -28, -30, -52, -26, -53, -25, -31, -51"
45,feature_43,int64,0.0,0.0,328.0,"-289, -56, -55, -54, -57, -59, -58, -60, -61, -62"
46,feature_44,int64,0.0,0.0,340.0,"-280, -279, -82, -79, -81, -84, -80, -91, -78, -83"
47,feature_45,int64,0.0,0.0,392.0,"-331, -329, -328, -330, -327, -332, -326, -105, -107, -108"
48,feature_46,int64,0.0,0.0,265.0,"-152, -151, -153, -150, -137, -97, -96, -154, -138, -98"
49,feature_47,int64,0.0,0.0,411.0,"-7, -6, -72, -63, -71, -70, -67, -62, -74, -61"
50,feature_48,int64,0.0,0.0,381.0,"-139, 31, 28, -140, 29, -141, -23, 26, -109, -142"
51,feature_49,int64,0.0,0.0,374.0,"-2, -103, -19, -102, -18, -20, -101, -22, -21, -3"
52,feature_50,int64,0.0,0.0,390.0,"-73, -72, -71, -74, -141, -142, -70, -139, -144, -143"
53,feature_51,int64,0.0,0.0,329.0,"-26, -27, -199, -200, -197, -198, -196, -18, -201, -17"
54,feature_52,int64,0.0,0.0,333.0,"-1, -12, 0, -11, -200, -197, -195, -198, -199, -196"
55,feature_53,int64,0.0,0.0,389.0,"-136, -135, -138, -134, -131, -137, 58, -132, -133, 67"
56,feature_54,int64,0.0,0.0,313.0,"148, -51, 108, 107, 163, -50, 147, -52, 149, 109"
57,feature_55,int64,0.0,0.0,415.0,"1, 2, 3, -61, -35, -59, -37, -95, -36, -96"
58,feature_56,int64,0.0,0.0,363.0,"93, 40, -160, 41, 92, 94, 99, -159, -161, 100"
59,feature_57,int64,0.0,0.0,271.0,"-177, -171, -170, -139, -140, -172, -141, -138, -150, -143"
60,feature_58,int64,0.0,0.0,302.0,"35, 0, 36, 3, 9, -16, -20, 87, 10, 1"
61,feature_59,int64,0.0,0.0,412.0,"40, 10, 41, 11, 9, 12, 8, 51, -167, 27"
62,feature_60,int64,0.0,0.0,254.0,"-101, -100, -98, -97, -96, -102, -99, -88, 196, -8"
63,feature_61,int64,0.0,0.0,305.0,"-195, 65, 83, 62, -187, 64, -194, 63, 66, 24"
64,feature_62,int64,0.0,0.0,205.0,"28, -35, -37, 23, 24, 31, 16, 27, -34, -38"
65,feature_63,int64,0.0,0.0,388.0,"-188, 110, -186, -187, 111, -185, -189, 109, 108, 112"
66,feature_64,int64,0.0,0.0,251.0,"-134, -145, -146, -12, -11, -144, -133, -13, -10, 97"
67,feature_65,int64,0.0,0.0,206.0,"59, 58, 60, 55, 57, 54, 56, 73, 80, 75"
68,feature_66,int64,0.0,0.0,181.0,"-166, -167, -165, -164, -161, -163, -160, -159, -162, -152"
69,feature_67,int64,0.0,0.0,287.0,"-40, 16, -83, 17, -30, -31, -39, 15, -84, -32"
70,feature_68,int64,0.0,0.0,314.0,"-133, -132, 78, 92, 31, 79, 29, 75, 77, 30"
71,feature_69,int64,0.0,0.0,287.0,"14, 13, -28, -35, -25, -41, -54, -55, 12, -58"
72,feature_70,int64,0.0,0.0,224.0,"-156, -148, -38, -155, -31, -162, -169, -39, -163, -66"
73,feature_71,int64,0.0,0.0,224.0,"-150, -149, -38, -146, -36, -33, -148, -37, -147, -39"
74,feature_72,int64,0.0,0.0,429.0,"-164, -163, -47, -48, -75, -165, -50, -49, -71, -33"
75,feature_73,int64,0.0,0.0,386.0,"-247, -246, -248, -62, -191, -245, -192, -60, -194, -67"
76,feature_74,int64,0.0,0.0,380.0,"-220, -96, -95, -218, -219, -97, -53, -67, -93, -92"
77,feature_75,int64,0.0,0.0,113.0,"-181, -182, -180, -179, -183, -184, -178, -177, -176, -185"
78,feature_76,int64,0.0,0.0,338.0,"0, 1, -32, -31, 8, -242, -243, 4, -30, -244"
79,feature_77,int64,0.0,0.0,392.0,"-218, -26, -28, -24, -25, -29, -23, -33, -22, -27"
80,feature_78,int64,0.0,0.0,347.0,"-105, -215, -216, -9, -10, -106, -8, -11, -13, -79"
81,feature_79,int64,0.0,0.0,338.0,"63, 62, 64, -177, -176, -166, 66, 61, 65, 60"
82,feature_80,int64,0.0,0.0,397.0,"-14, -13, -19, -20, -15, -17, -12, -18, -16, -209"
83,feature_81,int64,0.0,0.0,294.0,"11, -170, 13, 12, 14, -168, -171, -173, -169, -167"
84,feature_82,int64,0.0,0.0,368.0,"-32, -117, -116, -44, -43, -45, -46, -47, -48, -49"
85,feature_83,int64,0.0,0.0,361.0,"194, -40, -41, -39, 110, -81, -42, 111, 109, 121"
86,feature_84,int64,0.0,0.0,368.0,"17, 16, 0, 1, 18, -1, 43, 2, -5, -178"
87,feature_85,int64,0.0,0.0,320.0,"16, 23, 17, -190, -191, 22, -189, 24, -194, -192"
88,feature_86,int64,0.0,0.0,307.0,"-157, 105, -82, -158, 103, -191, -85, -89, 102, -156"
89,feature_87,int64,0.0,0.0,347.0,"-168, -167, -166, -52, -51, -169, -48, -49, -170, -174"
90,feature_88,int64,0.0,0.0,258.0,"-75, -7, -8, 29, 30, -74, -76, 8, -72, 7"
91,feature_89,int64,0.0,0.0,398.0,"134, 133, -146, -147, 83, 82, -145, -148, 81, 135"
92,feature_90,int64,0.0,0.0,331.0,"-202, -201, -196, -200, -195, -199, 32, 167, 33, -194"
93,feature_91,int64,0.0,0.0,247.0,"137, 23, 131, 133, 25, 62, 34, 21, 61, 24"
94,feature_92,int64,0.0,0.0,233.0,"-106, -119, -120, -115, -118, -105, -117, -116, 17, 16"
95,feature_93,int64,0.0,0.0,398.0,"-48, -92, -47, -46, -108, -45, -111, -107, -110, -99"
96,feature_94,int64,0.0,0.0,199.0,"9, -17, 3, 7, -23, -16, -25, -29, 28, -18"
97,feature_95,int64,0.0,0.0,333.0,"234, -50, -53, -55, -52, -54, -51, -49, 235, -56"
98,feature_96,int64,0.0,0.0,340.0,"-167, 126, -166, -183, -168, -182, -43, -188, -189, -184"
99,feature_97,int64,0.0,0.0,354.0,"31, 33, 32, -183, -184, 34, -181, -182, -187, -186"
100,feature_98,int64,0.0,0.0,181.0,"-156, -154, -155, -143, -24, -152, -153, -25, -23, -150"
101,feature_99,int64,0.0,0.0,331.0,"76, 80, 75, 79, -149, -148, -150, -151, -145, 81"
102,feature_100,int64,0.0,0.0,255.0,"-207, -206, -194, -61, -195, 89, -190, -205, 88, -62"
103,feature_101,int64,0.0,0.0,255.0,"130, 135, 134, 133, 131, 144, 136, -5, 143, 141"
104,feature_102,int64,0.0,0.0,396.0,"-259, -258, -39, -260, -257, -40, -38, -37, -61, -53"
105,feature_103,int64,0.0,0.0,337.0,"-53, -54, -52, -55, -293, -50, -284, -49, -51, -56"
106,feature_104,int64,0.0,0.0,277.0,"-302, -109, -110, -92, -89, -91, -301, -90, -88, -87"
107,feature_105,int64,0.0,0.0,382.0,"-264, -265, -262, -195, -54, -53, -266, -49, -56, -61"
108,feature_106,int64,0.0,0.0,319.0,"-167, -166, -169, -168, -175, -165, -181, -174, -171, -173"
109,feature_107,int64,0.0,0.0,388.0,"-120, -14, -119, -15, -16, -13, -78, -118, -17, -121"
110,feature_108,int64,0.0,0.0,328.0,"-245, -246, 2, -244, 1, 0, -186, -1, -63, -65"
111,feature_109,int64,0.0,0.0,268.0,"-282, -281, -249, -101, -233, -91, -100, -105, -99, -90"
112,feature_110,int64,0.0,0.0,292.0,"-243, -242, -55, -56, -57, -54, -53, -241, -52, -49"
113,feature_111,int64,0.0,0.0,406.0,"2, 3, -59, -58, 6, 1, 4, 7, 5, -60"
114,feature_112,int64,0.0,0.0,368.0,"-2, -28, -1, -27, 27, 28, 26, 29, 25, -207"
115,feature_113,int64,0.0,0.0,337.0,"-24, -3, -2, -23, -198, -199, -200, -197, -196, 24"
116,feature_114,int64,0.0,0.0,402.0,"24, -1, 23, 25, 53, 54, 1, 52, 55, 22"
117,feature_115,int64,0.0,0.0,406.0,"60, 61, -18, -15, -19, -9, -12, -11, -16, -7"
118,feature_116,int64,0.0,0.0,351.0,"162, 112, -93, -92, -94, -91, -90, 160, 111, 163"
119,feature_117,int64,0.0,0.0,354.0,"37, 36, 22, 38, 23, -202, -205, -199, -201, -200"
120,feature_118,int64,0.0,0.0,352.0,"84, 85, 86, -179, 7, 6, 83, -180, 8, -178"
121,feature_119,int64,0.0,0.0,347.0,"-189, 24, 26, 25, -188, -190, -123, 23, 22, -187"
122,feature_120,int64,0.0,0.0,299.0,"-114, -115, -113, 81, 82, 90, -112, -116, 89, 91"
123,feature_121,int64,0.0,0.0,314.0,"149, 72, -68, -66, 73, 141, -62, -67, 136, -55"
124,feature_122,int64,0.0,0.0,353.0,"114, 131, 115, 130, -101, -102, 113, 116, -81, -70"
125,feature_123,int64,0.0,0.0,277.0,"54, 50, 51, 53, 48, -108, 49, 29, 52, 30"
126,feature_124,int64,0.0,0.0,327.0,"-132, -127, -133, -129, -130, -131, -134, -126, -135, -136"
127,feature_125,int64,0.0,0.0,246.0,"65, 64, 59, 54, 55, 63, 68, 67, 56, 5"
128,feature_126,int64,0.0,0.0,435.0,"41, -23, -24, -20, -26, -21, -25, -27, -39, -19"
129,feature_127,int64,0.0,0.0,405.0,"81, 58, 80, 57, 56, 91, 90, 88, 92, 59"
130,feature_128,int64,0.0,0.0,415.0,"14, 15, 13, 16, -45, -64, -98, 12, -67, -112"
131,feature_129,int64,0.0,0.0,253.0,"-187, -188, -185, -186, -184, -23, -24, -51, -22, -52"
132,feature_130,int64,0.0,0.0,235.0,"42, 30, 25, 35, 43, 32, 41, 31, -88, 24"
133,feature_131,int64,0.0,0.0,320.0,"-138, -139, -117, -116, 42, -121, -110, 78, -136, -118"
134,feature_132,int64,0.0,0.0,416.0,"-65, -64, -63, -90, -86, -74, -76, -89, -73, -87"
135,feature_133,int64,0.0,0.0,393.0,"-128, -165, -126, -163, -82, -124, -162, -83, -84, -71"
136,feature_134,int64,0.0,0.0,394.0,"-206, -32, -37, -38, -207, -36, -35, -33, -102, -39"
137,feature_135,int64,0.0,0.0,267.0,"-20, -92, -23, -21, -27, -22, -26, -28, -93, -16"
138,feature_136,int64,0.0,0.0,345.0,"46, 45, 53, -174, 54, 47, -175, 38, -173, 51"
139,feature_137,int64,0.0,0.0,301.0,"-116, 127, -48, -33, -118, -44, -49, -23, -32, 126"
140,feature_138,int64,0.0,0.0,396.0,"-3, -4, -18, -19, -2, -21, -17, -16, -20, -207"
141,feature_139,int64,0.0,0.0,414.0,"-33, -34, -35, -32, -55, -37, -53, -54, -56, -36"
142,feature_140,int64,0.0,0.0,386.0,"-27, -37, -28, -26, -36, -94, -64, -95, -93, -63"
143,feature_141,int64,0.0,0.0,303.0,"76, 5, -138, -139, -136, 4, 79, 3, 78, -124"
144,feature_142,int64,0.0,0.0,331.0,"79, 49, -152, -154, -153, 50, 80, -150, -149, 48"
145,feature_143,int64,0.0,0.0,311.0,"61, -168, -169, 16, -166, -170, 17, -167, 24, 25"
146,feature_144,int64,0.0,0.0,150.0,"-178, -177, -175, -176, -140, -163, -139, -174, -141, -165"
147,feature_145,int64,0.0,0.0,247.0,"-103, -102, -104, -101, -105, -100, -99, -97, -95, -96"
148,feature_146,int64,0.0,0.0,144.0,"-120, -119, -121, -122, -118, -123, -117, -124, -116, -115"
149,feature_147,int64,0.0,0.0,294.0,"-35, -32, -21, -36, -34, 99, -33, -63, -42, 100"
150,feature_148,int64,0.0,0.0,295.0,"-35, 65, -107, 94, -51, 108, -66, -36, -34, 109"
151,feature_149,int64,0.0,0.0,329.0,"40, 53, -142, 41, 52, -137, 39, 16, -143, -136"
152,feature_150,int64,0.0,0.0,197.0,"-26, -25, -97, -112, 123, -98, -99, -96, -104, -105"
153,feature_151,int64,0.0,0.0,184.0,"-125, -124, -122, -126, -123, -121, -120, 3, 2, -35"
154,feature_152,int64,0.0,0.0,151.0,"-112, -113, 9, 8, -111, -114, 10, 35, -110, 36"
155,feature_153,int64,0.0,0.0,257.0,"-169, -168, -170, -41, -46, -42, -47, -167, -40, -55"
156,feature_154,int64,0.0,0.0,323.0,"127, 124, 123, 126, 125, 121, 2, 117, -66, 122"
157,feature_155,int64,0.0,0.0,286.0,"-195, -196, -194, 16, 32, -11, 31, -193, -192, -10"
158,feature_156,int64,0.0,0.0,258.0,"-238, -237, -236, -235, -239, -240, -234, -233, -241, -243"
159,feature_157,int64,0.0,0.0,398.0,"-303, -300, -302, -73, -301, -79, -306, -298, -258, -264"
160,feature_158,int64,0.0,0.0,386.0,"-206, -209, -208, -207, -210, -205, -211, 58, 56, -204"
161,feature_159,int64,0.0,0.0,278.0,"-21, -20, -14, -32, -129, -130, -8, -131, 9, -9"
162,feature_160,int64,0.0,0.0,354.0,"154, 150, 153, 155, 147, 149, 30, 151, 127, -41"
163,feature_161,int64,0.0,0.0,281.0,"129, 125, 106, 107, 131, 128, 100, 8, 112, 113"
164,feature_162,int64,0.0,0.0,292.0,"159, 172, 202, 175, 176, 162, 187, 196, 193, 215"
165,feature_163,int64,0.0,0.0,172.0,"-66, -73, -72, -68, -51, -44, -70, -41, -60, -54"
166,feature_164,int64,0.0,0.0,352.0,"-116, -117, -162, -145, -150, -127, -154, -164, -147, -148"
167,feature_165,int64,0.0,0.0,385.0,"-6, -5, 118, 119, -19, -7, 130, -18, 120, -9"

In [6]:
# Numeric Feature Statistics
numeric_stats

              count        mean         std    min    max
feature_0    6598.0   58.945135   53.249007  -31.0  292.0
feature_1    6598.0 -119.128524   90.813375 -199.0   95.0
feature_2    6598.0  -73.146560   67.956235 -167.0   81.0
feature_3    6598.0   -0.628372   80.444617 -114.0  161.0
feature_4    6598.0 -103.533495   64.387559 -118.0  325.0
feature_5    6598.0   18.359806   80.593655 -183.0  200.0
feature_6    6598.0  -14.108821  115.315673 -171.0  220.0
feature_7    6598.0   -1.858290   90.372537 -225.0  320.0
feature_8    6598.0  -86.003031  108.326676 -245.0  147.0
feature_9    6598.0  -44.495756   72.088903 -286.0  231.0
feature_10   6598.0 -119.456502  108.911397 -328.0  176.0
feature_11   6598.0  -84.929221   79.541410 -321.0  184.0
feature_12   6598.0  -61.911185   61.444281 -305.0  195.0
feature_13   6598.0 -127.935283  101.191126 -342.0  158.0
feature_14   6598.0 -123.005153   98.009158 -294.0  172.0
feature_15   6598.0 -265.690967   70.647329 -327.0   80.0
feature_16   6598.0  -53.415732  117.237608 -224.0  138.0
feature_17   6598.0  -67.741285   61.403085 -308.0  189.0
feature_18   6598.0  -52.352531   82.503477 -286.0  225.0
feature_19   6598.0  -44.902698   79.304489 -252.0  227.0
feature_20   6598.0  -75.645953   75.187995 -295.0  194.0
feature_21   6598.0  -55.783419  101.908604 -185.0  190.0
feature_22   6598.0  -61.619127   94.524709 -253.0  213.0
feature_23   6598.0   72.506062  123.334433  -76.0  317.0
feature_24   6598.0   32.285238  108.105908 -100.0  277.0
feature_25   6598.0  -69.659139  101.325550 -242.0  183.0
feature_26   6598.0  -15.361018   91.621335 -205.0  164.0
feature_27   6598.0 -102.665959   73.778232 -166.0  145.0
feature_28   6598.0    8.520764   63.484770 -142.0  174.0
feature_29   6598.0   12.553956  126.086157 -162.0  266.0
feature_30   6598.0  -82.314186   80.225924 -117.0  309.0
feature_31   6598.0   25.436193  106.627993 -143.0  310.0
feature_32   6598.0  -34.503183   57.816952 -139.0  207.0
feature_33   6598.0  -78.915732  118.201270 -279.0  160.0
feature_34   6598.0  -73.199000   75.350809 -160.0  220.0
feature_35   6598.0  115.882995   57.070192   -7.0  324.0
feature_36   6598.0 -115.562746  104.682519 -175.0  147.0
feature_37   6598.0   -7.853289   85.732778 -190.0  187.0
feature_38   6598.0  -75.578509   70.534415 -148.0  107.0
feature_39   6598.0   12.700667   80.750001 -180.0  194.0
feature_40   6598.0  -94.105335   84.554740 -188.0   90.0
feature_41   6598.0   24.210821   91.727678 -150.0  367.0
feature_42   6598.0  -45.615186   60.306330 -295.0  225.0
feature_43   6598.0 -121.602758  111.901894 -343.0  198.0
feature_44   6598.0 -125.547439   89.969244 -310.0  147.0
feature_45   6598.0 -170.321461  100.722635 -340.0  161.0
feature_46   6598.0  -95.759018   66.723054 -159.0  110.0
feature_47   6598.0  -87.315399   82.392698 -290.0  179.0
feature_48   6598.0  -24.237951   81.577192 -265.0  273.0
feature_49   6598.0  -54.001819   68.294161 -279.0  215.0
feature_50   6598.0  -91.248863   66.227603 -326.0  172.0
feature_51   6598.0  -67.800697  103.574857 -206.0  177.0
feature_52   6598.0  -55.654744  104.238710 -206.0  169.0
feature_53   6598.0    7.128221   93.704299 -147.0  335.0
feature_54   6598.0   80.092452   84.223115 -112.0  269.0
feature_55   6598.0  -62.756896   67.330179 -279.0  214.0
feature_56   6598.0    5.114580  112.618475 -170.0  229.0
feature_57   6598.0 -112.445893   79.650938 -178.0  113.0
feature_58   6598.0   26.498030   61.708787 -172.0  200.0
feature_59   6598.0  -36.375417  101.679670 -250.0  200.0
feature_60   6598.0  -23.988027   96.857409 -102.0  254.0
feature_61   6598.0  -54.988481  119.688552 -196.0  180.0
feature_62   6598.0    1.634435   48.537040 -100.0  284.0
feature_63   6598.0  -17.274022  131.326710 -195.0  225.0
feature_64   6598.0  -61.321916   85.130894 -165.0  112.0
feature_65   6598.0   79.316763   55.849966   -9.0  315.0
feature_66   6598.0 -155.735677   48.084476 -167.0  234.0
feature_67   6598.0  -16.943619   59.781700 -195.0  149.0
feature_68   6598.0  -13.007730   99.930285 -134.0  232.0
feature_69   6598.0   -6.271749   59.108877 -191.0  158.0
feature_70   6598.0  -84.647772   76.688701 -174.0   86.0
feature_71   6598.0  -82.482722   68.045335 -152.0   99.0
feature_72   6598.0  -99.559867   92.497523 -324.0  181.0
feature_73   6598.0 -104.820855   86.984078 -333.0  172.0
feature_74   6598.0  -72.398151   82.839247 -274.0  203.0
feature_75   6598.0 -175.827372   13.975250 -195.0   21.0
feature_76   6598.0  -83.528190  120.603288 -259.0  156.0
feature_77   6598.0  -92.815247  104.123379 -313.0  235.0
feature_78   6598.0  -73.518036   82.957802 -306.0  193.0
feature_79   6598.0   -3.541982  107.300603 -202.0  309.0
feature_80   6598.0  -70.569567   93.915668 -255.0  198.0
feature_81   6598.0  -34.470294  107.524802 -175.0  201.0
feature_82   6598.0  -74.743407   71.020966 -299.0  175.0
feature_83   6598.0   67.787208   96.733880  -98.0  273.0
feature_84   6598.0  -44.386935  103.820817 -220.0  193.0
feature_85   6598.0  -41.463474  114.975636 -203.0  194.0
feature_86   6598.0  -62.579418   84.797934 -207.0  109.0
feature_87   6598.0 -100.544559   78.672916 -213.0  172.0
feature_88   6598.0    2.058199   64.616847 -111.0  152.0
feature_89   6598.0   30.591846  123.957652 -157.0  269.0
feature_90   6598.0 -111.898151  111.033244 -202.0  235.0
feature_91   6598.0   85.028342   67.810941  -16.0  306.0
feature_92   6598.0  -39.855865   83.356713 -125.0  223.0
feature_93   6598.0 -118.955744   84.928006 -328.0  184.0
feature_94   6598.0   -6.052440   43.393333 -119.0  238.0
feature_95   6598.0   82.377690  113.737566  -69.0  347.0
feature_96   6598.0  -50.006517   99.398274 -191.0  165.0
feature_97   6598.0  -32.127008  110.107389 -190.0  203.0
feature_98   6598.0  -92.595938   64.245317 -157.0   40.0
feature_99   6598.0   13.029100  106.169467 -156.0  237.0
feature_100  6598.0 -106.344195   91.362072 -209.0   91.0
feature_101  6598.0  110.281600   73.623469  -33.0  348.0
feature_102  6598.0 -102.374204   97.065169 -299.0  173.0
feature_103  6598.0 -120.374659  109.257008 -324.0  191.0
feature_104  6598.0 -135.487572  101.510096 -319.0  154.0
feature_105  6598.0 -103.310700   90.044170 -284.0  212.0
feature_106  6598.0 -133.560473   69.825312 -200.0  159.0
feature_107  6598.0 -108.788724   86.429935 -292.0  167.0
feature_108  6598.0  -78.686875   98.082819 -249.0  200.0
feature_109  6598.0 -130.175053   85.835828 -291.0  141.0
feature_110  6598.0  -84.534101   94.897728 -250.0  209.0
feature_111  6598.0  -60.493786   87.738542 -266.0  214.0
feature_112  6598.0  -61.240376  103.003485 -224.0  194.0
feature_113  6598.0  -56.862989  102.903701 -204.0  180.0
feature_114  6598.0  -40.597908   98.182931 -250.0  216.0
feature_115  6598.0   -9.352380   66.273053 -257.0  253.0
feature_116  6598.0   61.939527  125.069996 -103.0  315.0
feature_117  6598.0  -42.358745  110.701484 -212.0  156.0
feature_118  6598.0  -17.505305  120.421611 -196.0  209.0
feature_119  6598.0  -52.381631   99.621142 -201.0  152.0
feature_120  6598.0   21.712337  114.037722 -121.0  267.0
feature_121  6598.0   63.267505   86.122325 -117.0  258.0
feature_122  6598.0   56.299939  100.990614 -129.0  276.0
feature_123  6598.0   -0.655199   69.524695 -127.0  227.0
feature_124  6598.0   -0.861928  113.150553 -144.0  299.0
feature_125  6598.0   51.431040   47.687834  -69.0  308.0
feature_126  6598.0  -46.587754   86.065208 -286.0  219.0
feature_127  6598.0  -19.476811  130.607205 -221.0  241.0
feature_128  6598.0  -68.070627   70.016546 -307.0  206.0
feature_129  6598.0  -94.963474   98.100733 -189.0  122.0
feature_130  6598.0    2.993786   60.633027 -123.0  281.0
feature_131  6598.0  -36.652774   84.316386 -140.0  255.0
feature_132  6598.0  -79.191422   61.733776 -319.0  176.0
feature_133  6598.0  -90.778266   68.098995 -338.0  169.0
feature_134  6598.0  -95.868142   87.253395 -336.0  219.0
feature_135  6598.0  -28.259473   61.664300 -196.0  125.0
feature_136  6598.0   -8.521067   97.997434 -197.0  186.0
feature_137  6598.0  -37.599121   77.580190 -199.0  130.0
feature_138  6598.0  -67.789330   94.753428 -243.0  202.0
feature_139  6598.0  -51.976508   64.344336 -283.0  203.0
feature_140  6598.0  -65.693089   69.094605 -290.0  188.0
feature_141  6598.0   -0.443165   82.410293 -185.0  184.0
feature_142  6598.0    1.331464  103.746483 -157.0  239.0
feature_143  6598.0  -21.754319  103.113954 -171.0  208.0
feature_144  6598.0 -165.748863   54.087579 -179.0  213.0
feature_145  6598.0  -87.364050   51.177725 -106.0  261.0
feature_146  6598.0 -113.114580   21.463582 -136.0  172.0
feature_147  6598.0  -18.523644   63.048333 -200.0  130.0
feature_148  6598.0  -41.386481   73.864481 -213.0  117.0
feature_149  6598.0    8.755077   83.274158 -190.0  185.0
feature_150  6598.0  -55.026069   60.100098 -140.0  244.0
feature_151  6598.0  -61.105335   70.788743 -128.0  153.0
feature_152  6598.0  -54.810397   67.538140 -114.0  211.0
feature_153  6598.0  -76.831161   76.908685 -173.0  120.0
feature_154  6598.0   33.209912   98.511502 -143.0  379.0
feature_155  6598.0  -61.212337   97.547356 -198.0  153.0
feature_156  6598.0 -210.975447   83.710890 -257.0  145.0
feature_157  6598.0 -184.798272  107.819514 -328.0   94.0
feature_158  6598.0  -75.795696  127.861271 -219.0  179.0
feature_159  6598.0  -26.073204   69.727964 -136.0  192.0
feature_160  6598.0   64.616702  100.861935 -120.0  411.0
feature_161  6598.0  112.037739   72.835040  -69.0  355.0
feature_162  6598.0  201.760230   59.526751   73.0  625.0
feature_163  6598.0  -47.488330   55.069365 -289.0  295.0
feature_164  6598.0 -150.259927   76.019023 -428.0  168.0
feature_165  6598.0   41.770233   94.116085 -471.0  367.0

In [7]:
# Categorical Feature Statistics
cat_stats

                           value  count    pct
column        rank
class         1         non-musk   5581  84.59
              2             musk   1017  15.41
molecule_name 1     59d697ad6b2c   1044  15.82
              2     bc804ca89aca   1010  15.31
              3     761ce578bca0    911  13.81
              4     da38bb0fcd6f    383   5.80
              5     73f8d56fb62c    344   5.21

In [8]:
# Target Distribution
target_df

          count    pct
class
non-musk   5581  84.59
musk       1017  15.41

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
    group_labels=task_mold.group_labels,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Providing recommendations based on number of groups (102).
Recommended splits: n_repeats=20, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_grouped_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    group_on=task_mold.group_on,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
    group_labels=task_mold.group_labels,
    show_splits=True,
    target_on=task_mold.target_column_name,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="We create stratified grouped 20-repeated 3-fold split. This creates ca. 30 group members (500-3000 samples) per test set.",
    splits=splits
)

Using Stratified Grouped splits.
Using label-per-group grouped splits.
Creating index-based splits for 102 groups
Using Stratified IID splits.
Repeat 0, Fold 0:
            Train N: 3560, Test N: 3038
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8328651685393258, 'musk': 0.16713483146067415}
            	Test target distribution: {'non-musk': 0.8610928242264648, 'musk': 0.13890717577353523}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 0, Fold 1:
            Train N: 5571, Test N: 1027
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8571172141446778, 'musk': 0.14288278585532221}
            	Test target distribution: {'non-musk': 0.7848101265822784, 'musk': 0.21518987341772153}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 0, Fold 2:
            Train N: 4065, Test N: 2533
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8418204182041821, 'musk': 0.15817958179581795}
            	Test target distribution: {'non-musk': 0.8523489932885906, 'musk': 0.1476510067114094}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 1, Fold 0:
            Train N: 4598, Test N: 2000
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8555893866898652, 'musk': 0.14441061331013483}
            	Test target distribution: {'non-musk': 0.8235, 'musk': 0.1765}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 1, Fold 1:
            Train N: 5626, Test N: 972
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8787771062922147, 'musk': 0.12122289370778529}
            	Test target distribution: {'non-musk': 0.6553497942386831, 'musk': 0.3446502057613169}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 1, Fold 2:
            Train N: 2972, Test N: 3626
            Target Distribution:
            	Train target distribution: {'non-musk': 0.7685060565275909, 'musk': 0.23149394347240915}
            	Test target distribution: {'non-musk': 0.9092664092664092, 'musk': 0.09073359073359073}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 2, Fold 0:
            Train N: 4941, Test N: 1657
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8915199352357822, 'musk': 0.10848006476421777}
            	Test target distribution: {'non-musk': 0.7097163548581774, 'musk': 0.2902836451418226}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 2, Fold 1:
            Train N: 3924, Test N: 2674
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8047910295616718, 'musk': 0.19520897043832824}
            	Test target distribution: {'non-musk': 0.9061331338818249, 'musk': 0.09386686611817502}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 2, Fold 2:
            Train N: 4331, Test N: 2267
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8309859154929577, 'musk': 0.16901408450704225}
            	Test target distribution: {'non-musk': 0.8742831936479929, 'musk': 0.12571680635200705}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 3, Fold 0:
            Train N: 4638, Test N: 1960
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8266494178525227, 'musk': 0.17335058214747737}
            	Test target distribution: {'non-musk': 0.8913265306122449, 'musk': 0.1086734693877551}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 3, Fold 1:
            Train N: 4350, Test N: 2248
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8832183908045977, 'musk': 0.1167816091954023}
            	Test target distribution: {'non-musk': 0.7735765124555161, 'musk': 0.226423487544484}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 3, Fold 2:
            Train N: 4208, Test N: 2390
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8284220532319392, 'musk': 0.17157794676806085}
            	Test target distribution: {'non-musk': 0.8765690376569037, 'musk': 0.12343096234309624}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 4, Fold 0:
            Train N: 3087, Test N: 3511
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8402980239714933, 'musk': 0.15970197602850664}
            	Test target distribution: {'non-musk': 0.8507547707205925, 'musk': 0.1492452292794076}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 4, Fold 1:
            Train N: 5809, Test N: 789
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8473059046307454, 'musk': 0.1526940953692546}
            	Test target distribution: {'non-musk': 0.835234474017744, 'musk': 0.16476552598225602}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 4, Fold 2:
            Train N: 4300, Test N: 2298
            Target Distribution:
            	Train target distribution: {'non-musk': 0.847906976744186, 'musk': 0.15209302325581395}
            	Test target distribution: {'non-musk': 0.8420365535248042, 'musk': 0.15796344647519583}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 5, Fold 0:
            Train N: 5572, Test N: 1026
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8619885139985642, 'musk': 0.13801148600143576}
            	Test target distribution: {'non-musk': 0.7582846003898636, 'musk': 0.24171539961013644}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 5, Fold 1:
            Train N: 3741, Test N: 2857
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8628708901363272, 'musk': 0.13712910986367283}
            	Test target distribution: {'non-musk': 0.823591179558978, 'musk': 0.17640882044102205}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 5, Fold 2:
            Train N: 3883, Test N: 2715
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8063353077517383, 'musk': 0.19366469224826166}
            	Test target distribution: {'non-musk': 0.9023941068139963, 'musk': 0.09760589318600368}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 6, Fold 0:
            Train N: 5678, Test N: 920
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8569918985558295, 'musk': 0.14300810144417048}
            	Test target distribution: {'non-musk': 0.7771739130434783, 'musk': 0.22282608695652173}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 6, Fold 1:
            Train N: 5520, Test N: 1078
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8793478260869565, 'musk': 0.12065217391304348}
            	Test target distribution: {'non-musk': 0.6743970315398887, 'musk': 0.32560296846011133}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 6, Fold 2:
            Train N: 1998, Test N: 4600
            Target Distribution:
            	Train target distribution: {'non-musk': 0.7217217217217218, 'musk': 0.2782782782782783}
            	Test target distribution: {'non-musk': 0.8997826086956522, 'musk': 0.10021739130434783}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 7, Fold 0:
            Train N: 4835, Test N: 1763
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8665977249224406, 'musk': 0.13340227507755947}
            	Test target distribution: {'non-musk': 0.7889960294951787, 'musk': 0.21100397050482134}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 7, Fold 1:
            Train N: 5161, Test N: 1437
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8343344313117613, 'musk': 0.1656655686882387}
            	Test target distribution: {'non-musk': 0.8872651356993737, 'musk': 0.1127348643006263}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 7, Fold 2:
            Train N: 3200, Test N: 3398
            Target Distribution:
            	Train target distribution: {'non-musk': 0.833125, 'musk': 0.166875}
            	Test target distribution: {'non-musk': 0.8578575632725133, 'musk': 0.14214243672748675}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 8, Fold 0:
            Train N: 4061, Test N: 2537
            Target Distribution:
            	Train target distribution: {'non-musk': 0.7980792908150702, 'musk': 0.20192070918492983}
            	Test target distribution: {'non-musk': 0.9223492313756405, 'musk': 0.07765076862435948}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 8, Fold 1:
            Train N: 3857, Test N: 2741
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8229193673839772, 'musk': 0.1770806326160228}
            	Test target distribution: {'non-musk': 0.878146661802262, 'musk': 0.12185333819773805}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 8, Fold 2:
            Train N: 5278, Test N: 1320
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8993937097385373, 'musk': 0.10060629026146267}
            	Test target distribution: {'non-musk': 0.6318181818181818, 'musk': 0.36818181818181817}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 9, Fold 0:
            Train N: 4664, Test N: 1934
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8666380789022299, 'musk': 0.13336192109777015}
            	Test target distribution: {'non-musk': 0.795760082730093, 'musk': 0.20423991726990692}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 9, Fold 1:
            Train N: 5220, Test N: 1378
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8779693486590038, 'musk': 0.12203065134099617}
            	Test target distribution: {'non-musk': 0.7242380261248186, 'musk': 0.2757619738751814}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 9, Fold 2:
            Train N: 3312, Test N: 3286
            Target Distribution:
            	Train target distribution: {'non-musk': 0.7660024154589372, 'musk': 0.23399758454106281}
            	Test target distribution: {'non-musk': 0.9263542300669507, 'musk': 0.0736457699330493}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 10, Fold 0:
            Train N: 4989, Test N: 1609
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8847464421727801, 'musk': 0.11525355782721988}
            	Test target distribution: {'non-musk': 0.7252952144188938, 'musk': 0.2747047855811063}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 10, Fold 1:
            Train N: 3153, Test N: 3445
            Target Distribution:
            	Train target distribution: {'non-musk': 0.774500475737393, 'musk': 0.22549952426260705}
            	Test target distribution: {'non-musk': 0.9111756168359942, 'musk': 0.0888243831640058}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 10, Fold 2:
            Train N: 5054, Test N: 1544
            Target Distribution:
            	Train target distribution: {'non-musk': 0.85199841709537, 'musk': 0.14800158290463}
            	Test target distribution: {'non-musk': 0.8257772020725389, 'musk': 0.17422279792746115}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 11, Fold 0:
            Train N: 4795, Test N: 1803
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8521376433785193, 'musk': 0.1478623566214807}
            	Test target distribution: {'non-musk': 0.8291735995562951, 'musk': 0.17082640044370492}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 11, Fold 1:
            Train N: 5692, Test N: 906
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8605059732958539, 'musk': 0.13949402670414618}
            	Test target distribution: {'non-musk': 0.7538631346578366, 'musk': 0.24613686534216336}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 11, Fold 2:
            Train N: 2709, Test N: 3889
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8039867109634552, 'musk': 0.19601328903654486}
            	Test target distribution: {'non-musk': 0.8750321419388017, 'musk': 0.12496785806119826}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 12, Fold 0:
            Train N: 2417, Test N: 4181
            Target Distribution:
            	Train target distribution: {'non-musk': 0.7753413322300372, 'musk': 0.22465866776996277}
            	Test target distribution: {'non-musk': 0.8866299928246831, 'musk': 0.11337000717531691}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 12, Fold 1:
            Train N: 5755, Test N: 843
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8665508253692441, 'musk': 0.13344917463075587}
            	Test target distribution: {'non-musk': 0.7046263345195729, 'musk': 0.29537366548042704}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 12, Fold 2:
            Train N: 5024, Test N: 1574
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8560907643312102, 'musk': 0.1439092356687898}
            	Test target distribution: {'non-musk': 0.8132147395171537, 'musk': 0.18678526048284624}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 13, Fold 0:
            Train N: 4469, Test N: 2129
            Target Distribution:
            	Train target distribution: {'non-musk': 0.834414857910047, 'musk': 0.165585142089953}
            	Test target distribution: {'non-musk': 0.8698919680601221, 'musk': 0.13010803193987788}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 13, Fold 1:
            Train N: 2880, Test N: 3718
            Target Distribution:
            	Train target distribution: {'non-musk': 0.81875, 'musk': 0.18125}
            	Test target distribution: {'non-musk': 0.8668639053254438, 'musk': 0.13313609467455623}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 13, Fold 2:
            Train N: 5847, Test N: 751
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8679664785360014, 'musk': 0.13203352146399863}
            	Test target distribution: {'non-musk': 0.6737683089214381, 'musk': 0.3262316910785619}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 14, Fold 0:
            Train N: 4749, Test N: 1849
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8334386186565593, 'musk': 0.16656138134344073}
            	Test target distribution: {'non-musk': 0.8777717685235262, 'musk': 0.12222823147647377}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 14, Fold 1:
            Train N: 4502, Test N: 2096
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8613949355841848, 'musk': 0.1386050644158152}
            	Test target distribution: {'non-musk': 0.8125, 'musk': 0.1875}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 14, Fold 2:
            Train N: 3945, Test N: 2653
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8430925221799747, 'musk': 0.15690747782002534}
            	Test target distribution: {'non-musk': 0.8499811534112326, 'musk': 0.15001884658876743}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 15, Fold 0:
            Train N: 5708, Test N: 890
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8621233356692362, 'musk': 0.13787666433076384}
            	Test target distribution: {'non-musk': 0.7415730337078652, 'musk': 0.25842696629213485}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 15, Fold 1:
            Train N: 2312, Test N: 4286
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8053633217993079, 'musk': 0.19463667820069205}
            	Test target distribution: {'non-musk': 0.8677088194120391, 'musk': 0.1322911805879608}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 15, Fold 2:
            Train N: 5176, Test N: 1422
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8460200927357032, 'musk': 0.15397990726429675}
            	Test target distribution: {'non-musk': 0.8452883263009845, 'musk': 0.15471167369901548}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 16, Fold 0:
            Train N: 3899, Test N: 2699
            Target Distribution:
            	Train target distribution: {'non-musk': 0.794819184406258, 'musk': 0.205180815593742}
            	Test target distribution: {'non-musk': 0.9195998517969618, 'musk': 0.08040014820303816}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 16, Fold 1:
            Train N: 4591, Test N: 2007
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8244391200174254, 'musk': 0.1755608799825746}
            	Test target distribution: {'non-musk': 0.8948679621325362, 'musk': 0.10513203786746388}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 16, Fold 2:
            Train N: 4706, Test N: 1892
            Target Distribution:
            	Train target distribution: {'non-musk': 0.9090522736931577, 'musk': 0.09094772630684234}
            	Test target distribution: {'non-musk': 0.6886892177589852, 'musk': 0.31131078224101477}
            Group Distribution molecule_name:
            	Train: 68
            	Test: 34

Repeat 17, Fold 0:
            Train N: 4288, Test N: 2310
            Target Distribution:
            	Train target distribution: {'non-musk': 0.8222947761194029, 'musk': 0.177705223880597}

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to musk/019d3199-b80d-7a81-913b-6bf76f29a4b8
019d3199-b80d-7a81-913b-6bf76f29a4b8
f4c838aad4e485126298e649a16e1bf7a86d3292376426f363b6c50b3b8e49ec