### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="wids_diabetes_mellitus",
    dataset_year="2021",
    domain_str="medical & healthcare",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/widsdatathon2021",
    download_description="""
We download the data from Kaggle.

kaggle competitions download -c widsdatathon2021 -f TrainingWiDS2021.csv && unzip TrainingWiDS2021.csv.zip &&  rm TrainingWiDS2021.csv.zip
mkdir -p local-data-warehouse/wids_diabetes_mellitus && mv TrainingWiDS2021.csv local-data-warehouse/wids_diabetes_mellitus/
""",
    # References
    academic_reference_bibtex=r"""@misc{Matthys2021WiDSDatathon2021,
  author = {Karen Matthys and Meredith Lee and Neha Goel and Sharada Kalanidhi and Valerie and Vani M.},
  title  = {WiDS Datathon 2021},
  year   = {2021},
  howpublished = {\url{https://kaggle.com/competitions/widsdatathon2021}},
  note   = {Kaggle competition}
}
""",
    academic_reference_bibtex_key="Matthys2021WiDSDatathon2021",
    license="Kaggle Competition Rules",
    data_tags=["IID"],
    curation_comments="""
We start with the Kaggle dataset.

- Data from the prior year's hackathon (2020) also used the very similar data but with older data and different splits. But it seems the feature engineering was transferable across years.
- We drop encounter_id as it is an identifier with no temporal information, and from the competition there seems to be no temporal or index-based leakage.
- We follow the top solutions and use normal random splits, instead of stratifying by hospital_id or ICU ID. Moreover, with the data for which we have labels, we have an even larger overlap for hospital_id and ICU ID even more than the train-test split on Kaggle. Lastly, we do not need to decode the hospital_ID based on the ICU ID.
- A hospital can have multiple ICUs, so there is a strong co-correlation between hospital_id and ICU ID, but it is not identical.
- We drop rows with age=0, as these seems to be 30 faulty entries (patients have a large height at age 0).
- Kaggle experts found that several features were likely clipped to a min/max value based on investigating the histograms of the data. We noticed this too. Following the experts, we add a flag for these features indicating if the value was clipped or not.
- Several Kaggle experts also re-computed the BMI. We also noticed that for 2770 rows, the BMI did not match the real BMI based on the weight and height. We drop all of these cases, as it is unclear to us what the cause of this error is. Given the small fraction, there is either a data entry error, or some values got corrected manually.
- We found and dropped three duplicated columns that provided no new information.
- We keep medical codes as string, as these could be more meaningfully decoded.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="diabetes_mellitus",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="diabetes_mellitus",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(dataset_mold.path / "TrainingWiDS2021.csv")
print("Loaded data shape:", df.shape)

df = df.drop(columns=[
    "Unnamed: 0", # Saving artifact
    "encounter_id", # Identifier, no temporal information
    "readmission_status", # Constant
    # Duplicated columns (no new information)
    "paco2_for_ph_apache",
    "h1_inr_max",
    "h1_inr_min",
])

df = df[df["age"] != 0]  # Drop rows with age=0 (faulty entries)

# Drop cases with faulty BMI calculations
df["bmi_new"] = df["weight"] / ((df["height"] / 100) ** 2)
bmi_wrong_mask = (df["bmi"].round(2) != df["bmi_new"].round(2)) & ~df["bmi"].isna()
df = df[~bmi_wrong_mask]
df = df.drop(columns=["bmi_new"])

# add min/max flags for features that were clipped
clipped_features = [
    "d1_sysbp_min",
    "d1_sysbp_max",
    "d1_heartrate_min",
    "d1_heartrate_max",
    "d1_diasbp_min",
    "d1_diasbp_max",
    "heart_rate_apache",
]
new_clipped_features = []
for f in clipped_features:
    min_val = df[f].min()
    max_val = df[f].max()
    clip_f = f + "_clipped"
    new_clipped_features.append(clip_f)
    df[clip_f] = ((df[f] == min_val) | (df[f] == max_val))

as_cat_type = [
    "hospital_id",
    "icu_id",
    "elective_surgery",
    "ethnicity",
    "gender",
    "hospital_admit_source",
    "icu_admit_source",
    "icu_stay_type",
    "icu_type",
    "apache_post_operative",
    "arf_apache",
    "intubated_apache",
    "gcs_unable_apache",
    # We keep medical scales as int (as they are ordinal in nature)
    "ventilated_apache",
    "aids",
    "cirrhosis",
    "hepatic_failure",
    "immunosuppression",
    "leukemia",
    "lymphoma",
    "solid_tumor_with_metastasis",
    "diabetes_mellitus",
] + new_clipped_features
as_string_type = [
    # Codes for medical terms
    "apache_2_diagnosis",
    "apache_3j_diagnosis",
]
for c in as_string_type:
    nan_mask = df[c].isna()
    df.loc[nan_mask, c] = np.nan
    df[c] = df[c].astype("string")
df[as_cat_type] = df[as_cat_type].astype("category")

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

Loaded data shape: (130157, 181)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 127,358
Columns: 182
Use sampling: False (sample size: 127,358)

Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['bmi', 'urineoutput_apache', 'pre_icu_los_days', 'd1_pao2fio2ratio_max', 'd1_pao2fio2ratio_min', 'weight', 'h1_pao2fio2ratio_max', 'h1_pao2fio2ratio_min', 'd1_wbc_max', 'wbc_apache']
Rows remaining as candidates after top-10 filter: 358 (of 127,358)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,icu_admit_source,icu_id,icu_stay_type,icu_type,pre_icu_los_days,weight,albumin_apache,apache_2_diagnosis,apache_3j_diagnosis,apache_post_operative,arf_apache,bilirubin_apache,bun_apache,creatinine_apache,fio2_apache,gcs_eyes_apache,gcs_motor_apache,gcs_unable_apache,gcs_verbal_apache,glucose_apache,heart_rate_apache,hematocrit_apache,intubated_apache,map_apache,paco2_apache,pao2_apache,ph_apache,resprate_apache,sodium_apache,temp_apache,urineoutput_apache,ventilated_apache,wbc_apache,d1_diasbp_invasive_max,d1_diasbp_invasive_min,d1_diasbp_max,d1_diasbp_min,d1_diasbp_noninvasive_max,d1_diasbp_noninvasive_min,d1_heartrate_max,d1_heartrate_min,d1_mbp_invasive_max,d1_mbp_invasive_min,d1_mbp_max,d1_mbp_min,d1_mbp_noninvasive_max,d1_mbp_noninvasive_min,d1_resprate_max,d1_resprate_min,d1_spo2_max,d1_spo2_min,d1_sysbp_invasive_max,d1_sysbp_invasive_min,d1_sysbp_max,d1_sysbp_min,d1_sysbp_noninvasive_max,d1_sysbp_noninvasive_min,d1_temp_max,d1_temp_min,h1_diasbp_invasive_max,h1_diasbp_invasive_min,h1_diasbp_max,h1_diasbp_min,h1_diasbp_noninvasive_max,h1_diasbp_noninvasive_min,h1_heartrate_max,h1_heartrate_min,h1_mbp_invasive_max,h1_mbp_invasive_min,h1_mbp_max,h1_mbp_min,h1_mbp_noninvasive_max,h1_mbp_noninvasive_min,h1_resprate_max,h1_resprate_min,h1_spo2_max,h1_spo2_min,h1_sysbp_invasive_max,h1_sysbp_invasive_min,h1_sysbp_max,h1_sysbp_min,h1_sysbp_noninvasive_max,h1_sysbp_noninvasive_min,h1_temp_max,h1_temp_min,d1_albumin_max,d1_albumin_min,d1_bilirubin_max,d1_bilirubin_min,d1_bun_max,d1_bun_min,d1_calcium_max,d1_calcium_min,d1_creatinine_max,d1_creatinine_min,d1_glucose_max,d1_glucose_min,d1_hco3_max,d1_hco3_min,d1_hemaglobin_max,d1_hemaglobin_min,d1_hematocrit_max,d1_hematocrit_min,d1_inr_max,d1_inr_min,d1_lactate_max,d1_lactate_min,d1_platelets_max,d1_platelets_min,d1_potassium_max,d1_potassium_min,d1_sodium_max,d1_sodium_min,d1_wbc_max,d1_wbc_min,h1_albumin_max,h1_albumin_min,h1_bilirubin_max,h1_bilirubin_min,h1_bun_max,h1_bun_min,h1_calcium_max,h1_calcium_min,h1_creatinine_max,h1_creatinine_min,h1_glucose_max,h1_glucose_min,h1_hco3_max,h1_hco3_min,h1_hemaglobin_max,h1_hemaglobin_min,h1_hematocrit_max,h1_hematocrit_min,h1_lactate_max,h1_lactate_min,h1_platelets_max,h1_platelets_min,h1_potassium_max,h1_potassium_min,h1_sodium_max,h1_sodium_min,h1_wbc_max,h1_wbc_min,d1_arterial_pco2_max,d1_arterial_pco2_min,d1_arterial_ph_max,d1_arterial_ph_min,d1_arterial_po2_max,d1_arterial_po2_min,d1_pao2fio2ratio_max,d1_pao2fio2ratio_min,h1_arterial_pco2_max,h1_arterial_pco2_min,h1_arterial_ph_max,h1_arterial_ph_min,h1_arterial_po2_max,h1_arterial_po2_min,h1_pao2fio2ratio_max,h1_pao2fio2ratio_min,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus,d1_sysbp_min_clipped,d1_sysbp_max_clipped,d1_heartrate_min_clipped,d1_heartrate_max_clipped,d1_diasbp_min_clipped,d1_diasbp_max_clipped,heart_rate_apache_clipped
0,118,86.0,26.488696,1,Caucasian,M,175.3,Operating Room,Operating Room / Recovery,92,admit,CTICU,0.002778,81.40,NaN,203.0,1206.03,1,0,NaN,28.0,1.00,0.48,4.0,6.0,0.0,5.0,132.0,66.0,34.0,0,112.0,37.0,184.0,7.35,26.0,137.0,36.2,NaN,0,6.80,76.0,50.0,71.0,71.0,71.0,71.0,94.0,66.0,118.0,72.0,118.0,72.0,NaN,NaN,27.0,16.0,100.0,97.0,170.0,126.0,158.0,158.0,158.0,158.0,36.8,36.2,62.0,58.0,62.0,58.0,NaN,NaN,74.0,68.0,90.0,82.0,90.0,82.0,NaN,NaN,19.0,16.0,100.0,99.0,144.0,136.0,144.0,136.0,NaN,NaN,36.2,36.2,NaN,NaN,NaN,NaN,28.0,28.0,7.5,7.5,1.00,1.00,132.0,132.0,22.0,22.0,11.6,11.5,34.1,34.0,NaN,NaN,NaN,NaN,137.0,131.0,4.9,4.7,137.0,137.0,7.50,6.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.6,11.6,34.0,34.0,NaN,NaN,137.0,137.0,NaN,NaN,NaN,NaN,7.5,7.5,37.0,37.0,7.35,7.35,184.0,184.0,383.333333,383.333333,37.0,37.0,7.35,7.35,184.0,184.0,383.333333,383.333333,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False
1,30,30.0,25.850545,0,Caucasian,M,172.7,Emergency Department,Accident & Emergency,921,admit,Med-Surg ICU,0.293750,77.10,NaN,113.0,501.05,0,0,NaN,18.0,0.90,NaN,2.0,6.0,0.0,5.0,99.0,135.0,27.0,0,42.0,NaN,NaN,NaN,41.0,135.0,37.7,NaN,1,3.36,NaN,NaN,68.0,19.0,68.0,19.0,135.0,93.0,NaN,NaN,75.0,24.0,75.0,24.0,41.0,12.0,100.0,76.0,NaN,NaN,114.0,57.0,114.0,57.0,38.5,37.7,NaN,NaN,62.0,22.0,62.0,22.0,119.0,117.0,NaN,NaN,68.0,32.0,68.0,32.0,24.0,22.0,100.0,100.0,NaN,NaN,94.0,57.0,94.0,57.0,38.5,38.5,NaN,NaN,NaN,NaN,18.0,18.0,7.6,7.6,0.90,0.90,104.0,99.0,24.0,24.0,9.8,9.1,27.0,27.0,1.4,1.4,3.4,3.4,141.0,141.0,4.4,4.4,135.0,135.0,3.36,3.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.0,104.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.0,32.0,7.44,7.39,224.0,126.0,385.000000,180.000000,37.0,37.0,7.40,7.40,126.0,126.0,180.000000,180.000000,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False
2,194,63.0,32.255636,0,Caucasian,M,163.0,Emergency Department,Accident & Emergency,601,admit,MICU,0.454167,85.70,3.3,301.0,410.01,0,0,1.6,30.0,1.09,NaN,4.0,6.0,0.0,4.0,93.0,89.0,44.5,0,109.0,NaN,NaN,NaN,11.0,145.0,36.6,1246.7520,0,13.60,NaN,NaN,104.0,60.0,104.0,60.0,85.0,67.0,NaN,NaN,109.0,73.0,109.0,73.0,23.0,11.0,98.0,86.0,NaN,NaN,155.0,111.0,155.0,111.0,37.3,36.6,NaN,NaN,69.0,66.0,69.0,66.0,85.0,77.0,NaN,NaN,86.0,85.0,86.0,85.0,13.0,11.0,97.0,86.0,NaN,NaN,155.0,141.0,155.0,141.0,37.3,37.3,3.3,3.3,1.6,1.6,30.0,30.0,8.9,8.9,1.09,1.09,93.0,93.0,27.0,27.0,15.5,15.5,44.5,44.5,NaN,NaN,NaN,NaN,341.0,341.0,3.1,3.1,145.0,145.0,13.60,13.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False
3,67,86.0,23.819354,0,Caucasian,F,170.2,Emergency Department,Accident & Emergency,1049,admit,Med-Surg ICU,0.177778,69.00,NaN,117.0,106.01,0,0,NaN,17.0,0.90,NaN,4.0,6.0,0.0,5.0,104.0,152.0,38.9,0,46.0,NaN,NaN,NaN,28.0,137.0,36.2,719.1072,0,8.20,NaN,NaN,90.0,59.0,90.0,59.0,152.0,93.0,NaN,NaN,95.0,67.0,95.0,67.0,24.0,17.0,94.0,90.0,NaN,NaN,131.0,84.0,131.0,84.0,36.2,36.2,NaN,NaN,85.0,84.0,85.0,84.0,150.0,144.0,NaN,NaN,92.0,89.0,92.0,89.0,22.0,21.0,94.0,93.0,NaN,NaN,123.0,108.0,123.0,108.0,36.2,36.2,NaN,NaN,NaN,NaN,17.0,17.0,9.1,9.1,0.90,0.90,137.0,100.0,23.0,23.0,12.4,12.4,38.9,38.9,NaN,NaN,NaN,NaN,249.0,249.0,3.9,3.9,137.0,137.0,8.20,8.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False
4,118,61.0,24.822192,0,Caucasian,M,177.8,Floor,Floor,93,admit,Med-Surg ICU,2.188889,78.47,3.1,122.0,703.02,0,0,2.4,8.0,0.77,NaN,4.0,6.0,0.0,4.0,122.0,150.0,36.7,0,135.0,NaN,NaN,NaN,43.0,130.0,36.4,NaN,0,6.00,NaN,NaN,122.0,75.0,122.0,75.0,150.0,94.0,NaN,NaN,135.0,85.0,135.0,85.0,43.0,15.0,98.0,90.0,NaN,NaN,182.0,98.0,182.0,98.0,37.7,36.4,NaN,NaN,110.0,93.0,110.0,93.0,150.0,126.0,NaN,NaN,128.0,114.0,128.0,114.0,43.0,20.0,97.0,92.0,NaN,NaN,182.0,133.0,182.0,133.0,37.7,37.5,3.3,3.2,2.4,2.1,7.0,7.0,9.2,9.0,0.83,0.77,130.0,124.0,24.0,23.0,12.8,12.3,37.2,36.7,NaN,NaN,NaN,NaN,155.0,136.0,4.0,3.2,132.0,130.0,11.30,9.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,hospital_admit_source,category,32415.0,25.45,15.0,"Emergency Department, Operating Room, Floor, Direct Admit, Recovery Room, Other Hospital, Acute Care/Floor, Step-Down Unit (SDU), PACU, Other ICU"
1,ethnicity,category,1533.0,1.20,6.0,"Caucasian, African American, Other/Unknown, Hispanic, Asian, Native American"
2,gcs_unable_apache,category,681.0,0.53,2.0,"0.0, 1.0"
3,icu_admit_source,category,221.0,0.17,5.0,"Accident & Emergency, Operating Room / Recovery, Floor, Other Hospital, Other ICU"
4,gender,category,40.0,0.03,2.0,"M, F"
5,hospital_id,category,0.0,0.00,204.0,"118, 19, 188, 86, 7, 161, 175, 70, 196, 176"
6,elective_surgery,category,0.0,0.00,2.0,"0, 1"
7,icu_id,category,0.0,0.00,328.0,"1019, 646, 876, 653, 413, 998, 236, 337, 1012, 1078"
8,icu_stay_type,category,0.0,0.00,3.0,"admit, transfer, readmit"
9,icu_type,category,0.0,0.00,8.0,"Med-Surg ICU, CCU-CTICU, MICU, Neuro ICU, SICU, Cardiac ICU, CSICU, CTICU"
10,apache_post_operative,category,0.0,0.00,2.0,"0, 1"
11,arf_apache,category,0.0,0.00,2.0,"0, 1"
12,intubated_apache,category,0.0,0.00,2.0,"0, 1"
13,ventilated_apache,category,0.0,0.00,2.0,"0, 1"
14,aids,category,0.0,0.00,2.0,"0, 1"
15,cirrhosis,category,0.0,0.00,2.0,"0, 1"
16,hepatic_failure,category,0.0,0.00,2.0,"0, 1"
17,immunosuppression,category,0.0,0.00,2.0,"0, 1"
18,leukemia,category,0.0,0.00,2.0,"0, 1"
19,lymphoma,category,0.0,0.00,2.0,"0, 1"
20,solid_tumor_with_metastasis,category,0.0,0.00,2.0,"0, 1"
21,diabetes_mellitus,category,0.0,0.00,2.0,"0, 1"
22,d1_sysbp_min_clipped,category,0.0,0.00,2.0,"False, True"
23,d1_sysbp_max_clipped,category,0.0,0.00,2.0,"False, True"
24,d1_heartrate_min_clipped,category,0.0,0.00,2.0,"False, True"
25,d1_heartrate_max_clipped,category,0.0,0.00,2.0,"False, True"
26,d1_diasbp_min_clipped,category,0.0,0.00,2.0,"False, True"
27,d1_diasbp_max_clipped,category,0.0,0.00,2.0,"False, True"
28,heart_rate_apache_clipped,category,0.0,0.00,2.0,"False, True"
29,h1_bilirubin_max,float64,117282.0,92.09,311.0,"0.4, 0.5, 0.3, 0.6, 0.7, 0.8, 0.2, 0.9, 1.0, 1.1"
30,h1_bilirubin_min,float64,117282.0,92.09,311.0,"0.4, 0.5, 0.3, 0.6, 0.7, 0.8, 0.2, 0.9, 1.0, 1.1"
31,h1_albumin_max,float64,116438.0,91.43,38.0,"3.2, 3.3, 3.4, 3.0, 3.1, 3.5, 2.8, 2.9, 2.6, 2.7"
32,h1_albumin_min,float64,116438.0,91.43,37.0,"3.2, 3.3, 3.4, 3.0, 3.1, 3.5, 2.8, 2.9, 2.6, 2.7"
33,h1_lactate_max,float64,115935.0,91.03,593.0,"1.0, 1.2, 1.1, 1.3, 0.9, 1.6, 1.4, 1.5, 1.8, 1.7"
34,h1_lactate_min,float64,115935.0,91.03,583.0,"1.0, 1.2, 1.1, 1.3, 0.9, 1.6, 1.4, 1.5, 1.8, 0.8"
35,h1_pao2fio2ratio_max,float64,110959.0,87.12,3374.0,"200.0, 42.0, 720.0, 160.0, 180.0, 190.0, 210.0, 260.0, 300.0, 140.0"
36,h1_pao2fio2ratio_min,float64,110959.0,87.12,3351.0,"200.0, 38.0, 654.8138, 190.0, 180.0, 150.0, 160.0, 210.0, 260.0, 140.0"
37,h1_arterial_ph_max,float64,105538.0,82.87,577.0,"7.36, 7.38, 7.34, 7.37, 7.35, 7.4, 7.39, 7.32, 7.33, 7.41"
38,h1_arterial_ph_min,float64,105538.0,82.87,598.0,"7.34, 7.32, 7.37, 7.36, 7.35, 7.38, 7.33, 7.39, 7.4, 7.31"
39,h1_arterial_pco2_max,float64,105354.0,82.72,819.0,"41.0, 39.0, 38.0, 40.0, 44.0, 42.0, 43.0, 45.0, 46.0, 37.0"
40,h1_arterial_pco2_min,float64,105354.0,82.72,800.0,"39.0, 38.0, 40.0, 37.0, 41.0, 42.0, 36.0, 43.0, 44.0, 35.0"
41,h1_arterial_po2_max,float64,105145.0,82.56,1823.0,"81.0, 76.0, 71.0, 80.0, 74.0, 82.0, 79.0, 84.0, 67.0, 83.0"
42,h1_arterial_po2_min,float64,105145.0,82.56,1820.0,"81.0, 76.0, 80.0, 82.0, 73.0, 69.0, 71.0, 70.0, 67.0, 74.0"
43,h1_hco3_max,float64,104037.0,81.69,222.0,"23.0, 24.0, 22.0, 25.0, 21.0, 26.0, 20.0, 27.0, 19.0, 28.0"
44,h1_hco3_min,float64,104037.0,81.69,210.0,"23.0, 24.0, 22.0, 25.0, 21.0, 26.0, 20.0, 27.0, 19.0, 28.0"
45,h1_wbc_max,float64,103602.0,81.35,2109.0,"10.6, 10.1, 9.3, 9.6, 13.6, 10.7, 9.2, 9.8, 12.9, 10.8"
46,h1_wbc_min,float64,103602.0,81.35,2105.0,"10.6, 10.1, 9.6, 10.7, 9.8, 9.3, 10.8, 10.0, 12.9, 13.6"
47,h1_calcium_max,float64,103567.0,81.32,59.0,"8.3, 8.4, 8.1, 8.2, 8.6, 8.5, 8.0, 7.9, 8.7, 8.8"
48,h1_calcium_min,float64,103567.0,81.32,62.0,"8.3, 8.4, 8.1, 8.2, 8.6, 8.5, 8.0, 7.9, 8.7, 8.8"
49,h1_platelets_max,float64,103337.0,81.14,554.0,"173.0, 157.0, 178.0, 175.0, 144.0, 133.0, 183.0, 153.0, 158.0, 152.0"
50,h1_platelets_min,float64,103337.0,81.14,554.0,"173.0, 144.0, 157.0, 175.0, 133.0, 178.0, 183.0, 159.0, 153.0, 139.0"
51,h1_bun_max,float64,102663.0,80.61,259.0,"14.0, 13.0, 15.0, 12.0, 11.0, 16.0, 17.0, 10.0, 18.0, 9.0"
52,h1_bun_min,float64,102663.0,80.61,259.0,"14.0, 13.0, 15.0, 12.0, 11.0, 16.0, 17.0, 10.0, 18.0, 9.0"
53,h1_creatinine_max,float64,102456.0,80.45,874.0,"0.9, 0.8, 0.7, 1.0, 1.1, 0.6, 1.2, 1.3, 0.5, 1.4"
54,h1_creatinine_min,float64,102456.0,80.45,871.0,"0.8, 0.9, 0.7, 1.0, 1.1, 0.6, 1.2, 1.3, 0.5, 1.4"
55,h1_diasbp_invasive_max,float64,102393.0,80.40,103.0,"62.0, 60.0, 64.0, 68.0, 66.0, 70.0, 58.0, 63.0, 61.0, 74.0"
56,h1_diasbp_invasive_min,float64,102393.0,80.40,86.0,"50.0, 54.0, 52.0, 56.0, 48.0, 58.0, 46.0, 60.0, 53.0, 55.0"
57,h1_sysbp_invasive_max,float64,102371.0,80.38,182.0,"126.0, 124.0, 132.0, 120.0, 122.0, 128.0, 130.0, 134.0, 140.0, 146.0"
58,h1_sysbp_invasive_min,float64,102371.0,80.38,168.0,"110.0, 98.0, 108.0, 94.0, 102.0, 92.0, 104.0, 100.0, 114.0, 106.0"
59,h1_mbp_invasive_max,float64,102328.0,80.35,255.0,"88.0, 82.0, 94.0, 90.0, 80.0, 86.0, 84.0, 92.0, 83.0, 96.0"
60,h1_mbp_invasive_min,float64,102328.0,80.35,133.0,"66.0, 70.0, 72.0, 64.0, 74.0, 68.0, 78.0, 73.0, 71.0, 62.0"
61,h1_hematocrit_max,float64,100605.0,78.99,358.0,"33.0, 32.0, 31.0, 34.0, 30.0, 35.0, 36.0, 29.0, 38.0, 39.0"
62,h1_hematocrit_min,float64,100605.0,78.99,361.0,"33.0, 26.0, 31.0, 29.0, 28.0, 30.0, 34.0, 32.0, 36.0, 35.0"
63,h1_hemaglobin_max,float64,100449.0,78.87,124.0,"10.9, 11.2, 11.6, 10.5, 10.6, 11.5, 11.4, 11.3, 10.7, 10.2"
64,h1_hemaglobin_min,float64,100449.0,78.87,124.0,"11.2, 10.2, 10.9, 11.6, 9.9, 10.5, 8.8, 11.5, 11.3, 10.6"
65,h1_sodium_max,float64,99519.0,78.14,95.0,"139.0, 140.0, 138.0, 141.0, 137.0, 136.0, 142.0, 135.0, 143.0, 134.0"
66,h1_sodium_min,float64,99519.0,78.14,108.0,"139.0, 138.0, 140.0, 137.0, 141.0, 136.0, 142.0, 135.0, 134.0, 143.0"
67,h1_potassium_max,float64,98566.0,77.39,114.0,"4.1, 4.0, 3.9, 3.8, 4.2, 4.3, 3.7, 4.4, 3.6, 4.5"
68,h1_potassium_min,float64,98566.0,77.39,111.0,"4.1, 4.0, 3.9, 3.8, 4.2, 3.7, 4.3, 3.6, 4.4, 3.5"
69,fio2_apache,float64,97641.0,76.67,87.0,"1.0, 0.4, 0.5, 0.6, 0.3, 0.21, 0.8, 0.7, 0.35, 0.28"
70,paco2_apache,float64,97641.0,76.67,725.0,"38.0, 41.0, 40.0, 39.0, 37.0, 42.0, 43.0, 35.0, 36.0, 44.0"
71,pao2_apache,float64,97641.0,76.67,2026.0,"76.0, 78.0, 75.0, 71.0, 82.0, 69.0, 80.0, 74.0, 72.0, 79.0"
72,ph_apache,float64,97641.0,76.67,575.0,"7.36, 7.38, 7.37, 7.35, 7.34, 7.4, 7.33, 7.39, 7.41, 7.32"
73,d1_lactate_max,float64,93582.0,73.48,775.0,"1.0, 1.2, 1.1, 0.9, 1.3, 1.4, 0.8, 1.5, 1.6, 1.7"
74,d1_lactate_min,float64,93582.0,73.48,538.0,"1.0, 0.9, 1.1, 1.2, 0.8, 1.3, 1.4, 1.5, 0.7, 1.6"
75,d1_diasbp_invasive_max,float64,92869.0,72.92,145.0,"74.0, 76.0, 78.0, 70.0, 68.0, 72.0, 66.0, 80.0, 67.0, 73.0"
76,d1_diasbp_invasive_min,float64,92869.0,72.92,85.0,"44.0, 46.0, 48.0, 42.0, 40.0, 50.0, 43.0, 45.0, 47.0, 38.0"
77,d1_sysbp_invasive_max,float64,92840.0,72.90,225.0,"150.0, 144.0, 148.0, 154.0, 156.0, 152.0, 146.0, 140.0, 158.0, 138.0"
78,d1_sysbp_invasive_min,float64,92840.0,72.90,163.0,"86.0, 92.0, 88.0, 90.0, 84.0, 91.0, 94.0, 89.0, 82.0, 96.0"
79,d1_mbp_invasive_max,float64,92671.0,72.76,285.0,"96.0, 94.0, 92.0, 100.0, 98.0, 102.0, 90.0, 104.0, 93.0, 88.0"
80,d1_mbp_invasive_min,float64,92671.0,72.76,118.0,"60.0, 62.0, 58.0, 64.0, 56.0, 59.0, 61.0, 66.0, 57.0, 63.0"
81,d1_pao2fio2ratio_max,float64,91444.0,71.80,5517.0,"200.0, 300.0, 250.0, 260.0, 834.805, 54.8, 280.0, 240.0, 180.0, 220.0"
82,d1_pao2fio2ratio_min,float64,91444.0,71.80,5238.0,"200.0, 180.0, 160.0, 220.0, 36.0, 250.0, 604.2278, 190.0, 210.0, 300.0"
83,d1_arterial_ph_max,float64,83117.0,65.26,540.0,"7.4, 7.38, 7.39, 7.41, 7.42, 7.37, 7.36, 7.43, 7.44, 7.35"
84,d1_arterial_ph_min,float64,83117.0,65.26,635.0,"7.34, 7.35, 7.36, 7.38, 7.33, 7.37, 7.32, 7.31, 7.39, 7.3"
85,d1_arterial_pco2_max,float64,82771.0,64.99,858.0,"42.0, 40.0, 43.0, 44.0, 41.0, 39.0, 45.0, 38.0, 46.0, 47.0"
86,d1_arterial_pco2_min,float64,82771.0,64.99,691.0,"38.0, 35.0, 37.0, 36.0, 39.0, 34.0, 33.0, 40.0, 41.0, 32.0"
87,d1_arterial_po2_max,float64,82334.0,64.65,2524.0,"82.0, 88.0, 81.0, 91.0, 85.0, 78.0, 77.0, 83.0, 80.0, 84.0"
88,d1_arterial_po2_min,float64,82334.0,64.65,1876.0,"71.0, 69.0, 68.0, 65.0, 70.0, 73.0, 75.0, 77.0, 72.0, 74.0"
89,bilirubin_apache,float64,80846.0,63.48,583.0,"0.4, 0.5, 0.3, 0.6, 0.7, 0.8, 0.9, 0.2, 1.0, 1.1"
90,d1_inr_max,float64,79363.0,62.31,515.0,"1.1, 1.2, 1.0, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 0.9"
91,d1_inr_min,float64,79363.0,62.31,414.0,"1.1, 1.2, 1.0, 1.3, 1.4, 1.5, 1.6, 0.9, 1.7, 1.8"
92,albumin_apache,float64,76555.0,60.11,36.0,"3.1, 3.0, 2.9, 2.8, 3.2, 2.7, 3.3, 2.6, 2.5, 3.4"
93,d1_bilirubin_max,float64,75143.0,59.00,591.0,"0.4, 0.5, 0.3, 0.6, 0.7, 0.8, 0.9, 0.2, 1.0, 1.1"
94,d1_bilirubin_min,float64,75143.0,59.00,557.0,"0.4, 0.5, 0.3, 0.6, 0.7, 0.8, 0.2, 0.9, 1.0, 1.1"
95,h1_glucose_max,float64,73397.0,57.63,611.0,"113.0, 119.0, 127.0, 123.0, 105.0, 120.0, 124.0, 128.0, 108.0, 116.0"
96,h1_glucose_min,float64,73397.0,57.63,601.0,"119.0, 108.0, 105.0, 113.0, 116.0, 110.0, 124.0, 109.0, 118.0, 111.0"
97,d1_albumin_max,float64,69937.0,54.91,40.0,"3.1, 3.0, 3.2, 2.9, 3.3, 2.8, 3.4, 2.7, 3.5, 2.6"
98,d1_albumin_min,float64,69937.0,54.91,38.0,"3.0, 3.1, 2.9, 3.2, 2.8, 3.3, 2.7, 3.4, 2.6, 3.5"
99,urineoutput_apache,float64,61795.0,48.52,32592.0,"0.0, 8716.6696, 1799.9712, 899.9424, 2399.9328, 1439.9424, 1107.648, 2879.9712, 1199.9232, 1714.2624"
100,h1_temp_max,float64,29019.0,22.79,380.0,"36.7, 36.8, 36.6, 36.4, 36.9, 36.5, 37.1, 37.0, 36.3, 37.2"
101,h1_temp_min,float64,29019.0,22.79,391.0,"36.7, 36.6, 36.8, 36.4, 36.9, 36.5, 36.3, 37.1, 37.0, 36.2"
102,wbc_apache,float64,28796.0,22.61,3113.0,"8.4, 8.0, 7.4, 7.8, 7.6, 7.9, 8.8, 8.2, 8.6, 9.2"
103,hematocrit_apache,float64,26131.0,20.52,353.0,"34.0, 36.0, 35.0, 33.0, 32.0, 31.0, 37.0, 29.0, 30.0, 28.0"
104,bun_apache,float64,24847.0,19.51,473.0,"13.0, 12.0, 14.0, 15.0, 11.0, 16.0, 10.0, 17.0, 9.0, 18.0"
105,creatinine_apache,float64,24318.0,19.09,1190.0,"0.8, 0.7, 0.9, 0.6, 1.1, 1.0, 1.2, 0.5, 1.3, 1.4"
106,sodium_apache,float64,23964.0,18.82,116.0,"139.0, 138.0, 140.0, 137.0, 136.0, 141.0, 135.0, 142.0, 134.0, 143.0"
107,d1_hco3_max,float64,19590.0,15.38,241.0,"24.0, 25.0, 23.0, 26.0, 22.0, 27.0, 21.0, 28.0, 20.0, 29.0"
108,d1_hco3_min,float64,19590.0,15.38,272.0,"23.0, 24.0, 25.0, 22.0, 26.0, 21.0, 27.0, 20.0, 28.0, 19.0"
109,d1_platelets_max,float64,18141.0,14.24,559.0,"182.0, 175.0, 173.0, 168.0, 176.0, 196.0, 183.0, 186.0, 179.0, 171.0"
110,d1_platelets_min,float64,18141.0,14.24,541.0,"168.0, 173.0, 170.0, 176.0, 186.0, 157.0, 174.0, 177.0, 163.0, 183.0"
111,d1_wbc_max,float64,17037.0,13.38,3127.0,"9.2, 8.4, 10.2, 9.7, 10.0, 8.0, 8.8, 9.6, 8.9, 9.0"
112,d1_wbc_min,float64,17037.0,13.38,2804.0,"8.4, 8.8, 7.8, 8.0, 9.2, 7.6, 8.6, 7.9, 8.1, 7.2"
113,d1_calcium_max,float64,16295.0,12.79,47.0,"8.4, 8.5, 8.6, 8.3, 8.2, 8.7, 8.8, 8.1, 8.0, 8.9"
114,d1_calcium_min,float64,16295.0,12.79,49.0,"8.3, 8.4, 8.5, 8.2, 8.1, 8.6, 8.0, 8.7, 7.9, 8.8"
115,d1_hemaglobin_max,float64,15862.0,12.45,105.0,"11.6, 10.9, 11.2, 11.3, 11.9, 11.7, 11.5, 11.8, 12.2, 11.1"
116,d1_hemaglobin_min,float64,15862.0,12.45,115.0,"10.9, 11.1, 11.6, 11.2, 11.3, 11.5, 11.7, 11.8, 12.1, 11.9"
117,d1_hematocrit_max,float64,15238.0,11.96,312.0,"35.0, 36.0, 33.0, 38.0, 34.0, 32.0, 37.0, 39.0, 31.0, 30.0"
118,d1_hematocrit_min,float64,15238.0,11.96,340.0,"34.0, 35.0, 36.0, 32.0, 33.0, 31.0, 30.0, 28.0, 29.0, 38.0"
119,glucose_apache,float64,14368.0,11.28,565.0,"92.0, 96.0, 97.0, 95.0, 93.0, 98.0, 94.0, 99.0, 91.0, 100.0"
120,d1_bun_max,float64,13420.0,10.54,490.0,"13.0, 14.0, 12.0, 15.0, 11.0, 16.0, 10.0, 17.0, 9.0, 18.0"
121,d1_bun_min,float64,13420.0,10.54,469.0,"12.0, 13.0, 11.0, 14.0, 10.0, 15.0, 16.0, 9.0, 17.0, 8.0"
122,h1_mbp_noninvasive_max,float64,13024.0,10.23,153.0,"88.0, 86.0, 85.0, 79.0, 90.0, 87.0, 84.0, 83.0, 82.0, 89.0"
123,h1_mbp_noninvasive_min,float64,13024.0,10.23,137.0,"80.0, 74.0, 73.0, 76.0, 79.0, 78.0, 71.0, 75.0, 77.0, 81.0"
124,d1_sodium_max,float64,12959.0,10.18,69.0,"139.0, 140.0, 138.0, 141.0, 137.0, 142.0, 136.0, 143.0, 135.0, 144.0"
125,d1_sodium_min,float64,12959.0,10.18,136.0,"138.0, 139.0, 137.0, 140.0, 136.0, 141.0, 135.0, 142.0, 134.0, 143.0"
126,d1_creatinine_max,float64,12956.0,10.17,1236.0,"0.8, 0.7, 0.9, 1.0, 0.6, 1.1, 1.2, 1.3, 0.5, 1.4"
127,d1_creatinine_min,float64,12956.0,10.17,1141.0,"0.8, 0.7, 0.9, 0.6, 1.0, 1.1, 0.5, 1.2, 1.3, 0.78"
128,d1_potassium_max,float64,12247.0,9.62,100.0,"4.1, 4.0, 4.2, 3.9, 4.3, 3.8, 4.4, 3.7, 4.5, 3.6"
129,d1_potassium_min,float64,12247.0,9.62,116.0,"3.9, 3.8, 4.0, 3.7, 4.1, 3.6, 4.2, 3.5, 4.3, 3.4"
130,h1_diasbp_noninvasive_max,float64,11106.0,8.72,108.0,"68.0, 70.0, 74.0, 72.0, 66.0, 65.0, 77.0, 71.0, 67.0, 69.0"
131,h1_diasbp_noninvasive_min,float64,11106.0,8.72,93.0,"58.0, 60.0, 56.0, 55.0, 59.0, 62.0, 57.0, 63.0, 65.0, 61.0"
132,h1_sysbp_noninvasive_max,float64,11097.0,8.71,149.0,"119.0, 124.0, 118.0, 122.0, 127.0, 132.0, 125.0, 128.0, 117.0, 130.0"
133,h1_sysbp_noninvasive_min,float64,11097.0,8.71,143.0,"110.0, 118.0, 106.0, 114.0, 105.0, 108.0, 119.0, 112.0, 113.0, 111.0"
134,d1_glucose_max,float64,8032.0,6.31,538.0,"113.0, 122.0, 112.0, 114.0, 119.0, 107.0, 125.0, 111.0, 127.0, 108.0"
135,d1_glucose_min,float64,8032.0,6.31,256.0,"97.0, 96.0, 98.0, 92.0, 95.0, 100.0, 104.0, 102.0, 103.0, 101.0"
136,temp_apache,float64,6442.0,5.06,207.0,"36.4, 36.6, 36.7, 36.3, 36.5, 36.8, 36.2, 36.1, 36.9, 36.0"
137,h1_mbp_max,float64,6353.0,4.99,155.0,"88.0, 86.0, 82.0, 90.0, 84.0, 85.0, 83.0, 78.0, 87.0, 80.0"
138,h1_mbp_min,float64,6353.0,4.99,137.0,"74.0, 80.0, 73.0, 76.0, 78.0, 71.0, 79.0, 75.0, 70.0, 72.0"
139,h1_resprate_max,float64,6292.0,4.94,50.0,"20.0, 18.0, 16.0, 22.0, 19.0, 21.0, 24.0, 17.0, 23.0, 25.0"
140,h1_resprate_min,float64,6292.0,4.94,94.0,"16.0, 14.0, 18.0, 12.0, 15.0, 20.0, 17.0, 13.0, 19.0, 11.0"
141,h1_spo2_max,float64,6082.0,4.78,78.0,"100.0, 99.0, 98.0, 97.0, 96.0, 95.0, 94.0, 93.0, 92.0, 91.0"
142,h1_spo2_min,float64,6082.0,4.78,101.0,"100.0, 98.0, 97.0, 96.0, 99.0, 95.0, 94.0, 93.0, 92.0, 91.0"
143,h1_diasbp_max,float64,5376.0,4.22,107.0,"68.0, 70.0, 74.0, 66.0, 72.0, 65.0, 67.0, 71.0, 62.0, 77.0"
144,h1_diasbp_min,float64,5376.0,4.22,92.0,"58.0, 60.0, 56.0, 55.0, 59.0, 62.0, 57.0, 63.0, 61.0, 54.0"
145,h1_sysbp_max,float64,5368.0,4.21,149.0,"124.0, 122.0, 118.0, 119.0, 132.0, 125.0, 127.0, 128.0, 126.0, 130.0"
146,h1_sysbp_min,float64,5368.0,4.21,142.0,"110.0, 106.0, 118.0, 114.0, 108.0, 112.0, 105.0, 104.0, 113.0, 119.0"
147,age,float64,4869.0,3.82,74.0,"67.0, 71.0, 68.0, 72.0, 66.0, 65.0, 63.0, 70.0, 73.0, 62.0"
148,bmi,float64,4472.0,3.51,40222.0,"28.6909, 24.0178, 24.2081, 27.3593, 23.2959, 25.8123, 29.0497, 22.6061, 24.8047, 27.1131"
149,d1_temp_max,float64,4368.0,3.43,258.0,"37.1, 36.9, 37.2, 36.8, 37.0, 37.3, 36.7, 37.4, 37.6, 37.7"
150,d1_temp_min,float64,4368.0,3.43,307.0,"36.4, 36.6, 36.3, 36.7, 36.5, 36.2, 36.1, 36.8, 36.0, 36.9"
151,h1_heartrate_max,float64,3955.0,3.11,119.0,"80.0, 90.0, 86.0, 88.0, 82.0, 84.0, 92.0, 96.0, 78.0, 94.0"
152,h1_heartrate_min,float64,3955.0,3.11,109.0,"80.0, 70.0, 78.0, 74.0, 84.0, 82.0, 76.0, 72.0, 90.0, 60.0"
153,weight,float64,3447.0,2.71,3614.0,"68.0, 81.6, 63.5, 90.7, 77.1, 72.6, 59.0, 70.0, 75.0, 80.0"
154,d1_mbp_noninvasive_max,float64,2174.0,1.71,155.0,"98.0, 100.0, 96.0, 97.0, 104.0, 103.0, 94.0, 102.0, 95.0, 101.0"
155,d1_mbp_noninvasive_min,float64,2174.0,1.71,128.0,"61.0, 60.0, 63.0, 59.0, 65.0, 64.0, 62.0, 67.0, 58.0, 66.0"
156,gcs_eyes_apache,float64,2126.0,1.67,4.0,"4.0, 3.0, 1.0, 2.0"
157,gcs_motor_apache,float64,2126.0,1.67,6.0,"6.0, 5.0, 1.0, 4.0, 3.0, 2.0"
158,gcs_verbal_apache,float64,2126.0,1.67,5.0,"5.0, 1.0, 4.0, 3.0, 2.0"
159,height,float64,2060.0,1.62,441.0,"177.8, 167.6, 160.0, 172.7, 165.1, 170.2, 162.6, 182.9, 175.3, 180.3"
160,d1_diasbp_noninvasive_max,float64,1589.0,1.25,120.0,"84.0, 80.0, 82.0, 83.0, 88.0, 86.0, 85.0, 87.0, 90.0, 79.0"
161,d1_diasbp_noninvasive_min,float64,1589.0,1.25,78.0,"50.0, 51.0, 52.0, 55.0, 53.0, 49.0, 47.0, 46.0, 48.0, 45.0"
162,d1_sysbp_noninvasive_max,float64,1576.0,1.24,143.0,"140.0, 134.0, 137.0, 135.0, 144.0, 138.0, 142.0, 146.0, 145.0, 133.0"
163,d1_sysbp_noninvasive_min,float64,1576.0,1.24,120.0,"90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 100.0"
164,resprate_apache,float64,770.0,0.60,77.0,"10.0, 12.0, 11.0, 9.0, 4.0, 8.0, 28.0, 30.0, 29.0, 31.0"
165,d1_resprate_max,float64,653.0,0.51,79.0,"24.0, 22.0, 25.0, 23.0, 26.0, 20.0, 28.0, 27.0, 21.0, 30.0"
166,d1_resprate_min,float64,653.0,0.51,55.0,"12.0, 14.0, 13.0, 10.0, 11.0, 16.0, 15.0, 9.0, 0.0, 18.0"
167,d1_spo2_max,float64,504.0,0.40,46.0,"100.0, 99.0, 98.0, 97.0, 96.0, 95.0, 94.0, 93.0, 92.0, 91.0"
168,d1_spo2_min,float64,504.0,0.40,101.0,"94.0, 93.0, 92.0, 95.0, 91.0, 96.0, 90.0, 97.0, 89.0, 98.0"
169,map_apache,float64,396.0,0.31,172.0,"56.0, 58.0, 54.0, 55.0, 53.0, 60.0, 40.0, 57.0, 52.0, 59.0"
170,d1_mbp_max,float64,305.0,0.24,158.0,"98.0, 100.0, 96.0, 97.0, 94.0, 104.0, 102.0, 103.0, 95.0, 101.0"
171,d1_mbp_min,float64,305.0,0.24,128.0,"61.0, 60.0, 59.0, 63.0, 64.0, 62.0, 65.0, 58.0, 67.0, 56.0"
172,heart_rate_apache,float64,282.0,0.22,149.0,"100.0, 102.0, 108.0, 104.0, 106.0, 98.0, 110.0, 112.0, 96.0, 60.0"
173,d1_diasbp_max,float64,255.0,0.20,120.0,"84.0, 80.0, 82.0, 86.0, 88.0, 83.0, 85.0, 90.0, 87.0, 79.0"
174,d1_diasbp_min,float64,255.0,0.20,78.0,"50.0, 51.0, 52.0, 55.0, 46.0, 49.0, 53.0, 47.0, 48.0, 54.0"
175,d1_sysbp_max,float64,249.0,0.20,143.0,"140.0, 134.0, 144.0, 135.0, 138.0, 137.0, 142.0, 146.0, 139.0, 145.0"
176,d1_sysbp_min,float64,249.0,0.20,120.0,"90.0, 91.0, 92.0, 93.0, 94.0, 96.0, 95.0, 97.0, 98.0, 100.0"
177,d1_heartrate_max,float64,238.0,0.19,120.0,"100.0, 96.0, 98.0, 92.0, 90.0, 94.0, 102.0, 88.0, 104.0, 106.0"
178,d1_heartrate_min,float64,238.0,0.19,155.0,"60.0, 70.0, 68.0, 62.0, 66.0, 64.0, 72.0, 74.0, 65.0, 58.0"
179,pre_icu_los_days,float64,0.0,0.00,10799.0,"0.0, 0.0007, 0.0014, 0.0021, 0.0028, 0.0035, 0.0049, 0.0042, 0.0063, 0.0056"
180,apache_2_diagnosis,string,1634.0,1.28,44.0,"113.0, 301.0, 302.0, 112.0, 308.0, 124.0, 117.0, 122.0, 303.0, 304.0"
181,apache_3j_diagnosis,string,825.0,0.65,399.0,"501.05, 107.01, 403.01, 106.01, 703.03, 1207.01, 104.01, 502.01, 102.01, 702.01"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
age,122489.0,62.088081,16.772879,16.000000,89.000000
bmi,122886.0,28.904763,7.559969,14.844926,67.812636
height,125298.0,169.695366,10.495597,137.200000,195.590000
pre_icu_los_days,127358.0,0.839402,2.487524,-0.250000,175.627778
weight,123911.0,83.458102,23.525208,38.600000,186.000000
albumin_apache,50803.0,2.888710,0.689554,1.200000,4.600000
bilirubin_apache,46512.0,1.202893,2.357805,0.100000,60.200000
bun_apache,102511.0,25.675660,20.652158,4.000000,127.000000
creatinine_apache,103040.0,1.480846,1.541544,0.300000,11.180000
fio2_apache,29717.0,0.595963,0.262634,0.210000,1.000000
gcs_eyes_apache,125232.0,3.489220,0.939215,1.000000,4.000000
gcs_motor_apache,125232.0,5.486250,1.270545,1.000000,6.000000
gcs_verbal_apache,125232.0,4.033043,1.537076,1.000000,5.000000
glucose_apache,112990.0,160.192088,90.608488,39.000000,598.700000
heart_rate_apache,127076.0,99.756170,30.758234,30.000000,178.000000
hematocrit_apache,101227.0,32.971513,6.832310,16.200000,51.400000
map_apache,126962.0,87.214641,41.883470,40.000000,200.000000
paco2_apache,29717.0,42.020973,12.104591,18.000000,95.000000
pao2_apache,29717.0,132.341441,85.019065,31.000000,498.000000
ph_apache,29717.0,7.352360,0.098284,6.960540,7.590000
resprate_apache,126588.0,25.114760,15.020046,4.000000,60.000000
sodium_apache,103394.0,137.945798,5.291095,117.000000,158.000000
temp_apache,120916.0,36.420263,0.856850,32.100000,39.700000
urineoutput_apache,65563.0,1800.858143,1452.199200,0.000000,8716.669632
wbc_apache,98562.0,12.178893,6.922606,0.900000,45.800000
d1_diasbp_invasive_max,34489.0,79.218041,21.646876,37.000000,181.000000
d1_diasbp_invasive_min,34489.0,46.951144,12.715818,5.000000,89.000000
d1_diasbp_max,127103.0,88.565164,20.145654,46.000000,165.000000
d1_diasbp_min,127103.0,49.880325,13.387074,13.000000,90.000000
d1_diasbp_noninvasive_max,125769.0,88.719223,20.140319,46.000000,165.000000
d1_diasbp_noninvasive_min,125769.0,49.935151,13.417673,13.000000,90.000000
d1_heartrate_max,127120.0,103.233087,21.969496,58.000000,177.000000
d1_heartrate_min,127120.0,70.355955,17.113345,0.000000,175.000000
d1_mbp_invasive_max,34687.0,114.432900,49.166724,38.000000,322.000000
d1_mbp_invasive_min,34687.0,62.218064,17.812383,2.000000,119.000000
d1_mbp_max,127053.0,104.237562,20.898441,60.000000,184.000000
d1_mbp_min,127053.0,64.384950,15.414521,22.000000,112.000000
d1_mbp_noninvasive_max,125184.0,104.189465,20.788948,60.000000,181.000000
d1_mbp_noninvasive_min,125184.0,64.415381,15.439101,22.000000,112.000000
d1_resprate_max,126705.0,28.708875,10.571759,14.000000,92.000000
d1_resprate_min,126705.0,12.683406,5.036875,0.000000,100.000000
d1_spo2_max,126854.0,99.277130,1.721316,0.000000,100.000000
d1_spo2_min,126854.0,90.396338,10.123922,0.000000,100.000000
d1_sysbp_invasive_max,34518.0,153.317776,31.431743,71.000000,295.000000
d1_sysbp_invasive_min,34518.0,93.659772,24.565478,10.000000,172.000000
d1_sysbp_max,127109.0,148.245931,25.876553,90.000000,232.000000
d1_sysbp_min,127109.0,96.708361,20.645544,41.000000,160.000000
d1_sysbp_noninvasive_max,125782.0,148.153472,25.917117,90.000000,232.000000
d1_sysbp_noninvasive_min,125782.0,96.728717,20.664658,41.030000,160.000000
d1_temp_max,122990.0,37.301851,0.699008,35.100000,39.900000
d1_temp_min,122990.0,36.266419,0.768075,31.889000,37.800000
h1_diasbp_invasive_max,24965.0,68.503905,16.241242,33.000000,135.000000
h1_diasbp_invasive_min,24965.0,56.635209,14.223752,19.000000,104.000000
h1_diasbp_max,121982.0,75.431760,18.532261,37.000000,143.000000
h1_diasbp_min,121982.0,62.504140,16.286824,22.000000,113.000000
h1_diasbp_noninvasive_max,116252.0,75.909954,18.634676,37.000000,144.000000
h1_diasbp_noninvasive_min,116252.0,62.911193,16.368420,22.000000,114.000000
h1_heartrate_max,123403.0,92.383889,21.774112,46.000000,164.000000
h1_heartrate_min,123403.0,83.719512,20.207608,36.000000,144.000000
h1_mbp_invasive_max,25030.0,94.665761,30.436537,35.625000,293.375000
h1_mbp_invasive_min,25030.0,75.963084,19.081276,8.000000,140.000000
h1_mbp_max,121005.0,91.309221,20.378725,49.000000,165.000000
h1_mbp_min,121005.0,78.868289,18.825767,32.000000,138.000000
h1_mbp_noninvasive_max,114334.0,91.278302,20.400381,49.000000,163.000000
h1_mbp_noninvasive_min,114334.0,79.114256,18.945911,32.000000,138.000000
h1_resprate_max,121066.0,22.525565,7.435843,10.000000,59.000000
h1_resprate_min,121066.0,17.068987,5.930898,0.000000,189.000000
h1_spo2_max,121276.0,98.103838,3.096671,0.000000,100.000000
h1_spo2_min,121276.0,95.271488,6.450847,0.000000,100.000000
h1_sysbp_invasive_max,24987.0,138.250490,28.890824,65.000000,246.000000
h1_sysbp_invasive_min,24987.0,114.761407,27.716138,31.440000,198.000000
h1_sysbp_max,121990.0,133.304468,27.430705,75.000000,223.000000
h1_sysbp_min,121990.0,115.988056,26.290221,53.000000,194.000000
h1_sysbp_noninvasive_max,116261.0,133.100618,27.553338,75.000000,223.000000
h1_sysbp_noninvasive_min,116261.0,116.123550,26.396953,53.000000,195.000000
h1_temp_max,98339.0,36.721598,0.773049,33.400000,39.500000
h1_temp_min,98339.0,36.612663,0.796253,32.900000,39.300000
d1_albumin_max,57421.0,2.955323,0.675208,1.200000,4.600000
d1_albumin_min,57421.0,2.885600,0.679397,1.100000,4.500000
d1_bilirubin_max,52215.0,1.193300,2.325498,0.200000,60.200000
d1_bilirubin_min,52215.0,1.119197,2.208281,0.200000,58.000000
d1_bun_max,113938.0,25.538931,20.458009,4.000000,126.000000
d1_bun_min,113938.0,23.515965,18.670509,3.000000,113.090000
d1_calcium_max,111063.0,8.379765,0.739158,6.200000,10.800000
d1_calcium_min,111063.0,8.164714,0.792036,5.500000,10.300000
d1_creatinine_max,114402.0,1.492581,1.523853,0.340000,11.110000
d1_creatinine_min,114402.0,1.362979,1.339519,0.300000,9.937900
d1_glucose_max,119326.0,174.185416,86.501979,73.000000,611.000000
d1_glucose_min,119326.0,114.478370,38.160243,33.000000,288.000000
d1_hco3_max,107768.0,24.433636,4.336809,12.000000,40.000000
d1_hco3_min,107768.0,23.173940,4.974797,7.000000,39.000000
d1_hemaglobin_max,111496.0,11.463329,2.148181,6.800000,17.200000
d1_hemaglobin_min,111496.0,10.903426,2.338707,5.300000,16.700000
d1_hematocrit_max,112120.0,34.555830,6.186475,20.400000,51.500000
d1_hematocrit_min,112120.0,32.934172,6.804420,16.100000,50.000000
d1_inr_max,47995.0,1.575564,0.941755,0.900000,7.756000
d1_inr_min,47995.0,1.461532,0.734048,0.900000,6.127000
d1_lactate_max,33776.0,2.929988,3.065595,0.400000,19.800000
d1_lactate_min,33776.0,2.082465,2.069067,0.400000,15.100000
d1_platelets_max,109217.0,205.623557,89.339619,27.000000,585.000000
d1_platelets_min,109217.0,194.614452,87.948397,18.550000,557.450000
d1_potassium_max,115111.0,4.252051,0.665344,2.800000,7.000000
d1_potassium_min,115111.0,3.928735,0.577648,2.400000,5.800000
d1_sodium_max,114399.0,139.150093,4.817925,123.000000,158.000000
d1_sodium_min,114399.0,137.690866,4.915434,117.000000,153.000000
d1_wbc_max,110321.0,12.536290,6.777789,1.200000,46.080000
d1_wbc_min,110321.0,11.290532,5.916332,0.900000,40.898000
h1_albumin_max,10920.0,3.010063,0.736571,1.100000,4.700000
h1_albumin_min,10920.0,3.008773,0.736876,1.100000,4.700000
h1_bilirubin_max,10076.0,1.187665,2.367119,0.200000,58.000000
h1_bilirubin_min,10076.0,1.186891,2.366548,0.200000,58.000000
h1_bun_max,24695.0,25.578040,21.307602,4.000000,135.000000
h1_bun_min,24695.0,25.553084,21.290177,4.000000,135.000000
h1_calcium_max,23791.0,8.272830,0.891293,5.600000,11.400000
h1_calcium_min,23791.0,8.263749,0.904070,5.300000,11.315000
h1_creatinine_max,24902.0,1.525770,1.570332,0.330000,11.604200
h1_creatinine_min,24902.0,1.523502,1.567596,0.330000,11.571000
h1_glucose_max,53961.0,167.761106,93.892287,59.000000,695.045000
h1_glucose_min,53961.0,158.933767,88.124730,42.000000,670.000000
h1_hco3_max,23321.0,22.528048,5.110473,6.000000,39.000000
h1_hco3_min,23321.0,22.470108,5.117367,6.000000,39.000000
h1_hemaglobin_max,26909.0,11.202252,2.347710,5.100000,17.400000
h1_hemaglobin_min,26909.0,11.085176,2.378640,5.000000,17.300000
h1_hematocrit_max,26753.0,33.714757,6.795668,16.000000,51.700000
h1_hematocrit_min,26753.0,33.331025,6.956004,15.500000,51.500000
h1_lactate_max,11423.0,3.032017,2.903156,0.400000,18.100000
h1_lactate_min,11423.0,2.979620,2.857697,0.400000,18.019500
h1_platelets_max,24021.0,193.529162,92.296334,20.000000,585.000000
h1_platelets_min,24021.0,192.708630,92.497946,20.000000,585.000000
h1_potassium_max,28792.0,4.187705,0.756960,2.500000,7.200000
h1_potassium_min,28792.0,4.145751,0.746283,2.500000,7.100000
h1_sodium_max,27839.0,138.167359,5.702829,114.000000,157.000000
h1_sodium_min,27839.0,137.877431,5.648554,114.000000,157.000000
h1_wbc_max,23756.0,13.389163,6.930988,1.100000,44.102000
h1_wbc_min,23756.0,13.337340,6.912877,1.089800,44.102000
d1_arterial_pco2_max,44587.0,45.160611,14.403946,18.400000,111.000000
d1_arterial_pco2_min,44587.0,38.413804,10.855800,14.900000,85.912000
d1_arterial_ph_max,44241.0,7.387886,0.085472,7.054280,7.620000
d1_arterial_ph_min,44241.0,7.323304,0.111337,6.890000,7.557860
d1_arterial_po2_max,45024.0,165.448179,107.241875,39.000000,540.865000
d1_arterial_po2_min,45024.0,103.231143,61.690620,28.000000,448.892000
d1_pao2fio2ratio_max,35914.0,288.028106,130.289151,54.800000,834.805000
d1_pao2fio2ratio_min,35914.0,224.341861,119.092538,36.000000,604.227778
h1_arterial_pco2_max,22004.0,44.363812,14.395265,15.000000,111.505000
h1_arterial_pco2_min,22004.0,43.155479,13.828276,14.997000,107.000000
h1_arterial_ph_max,21820.0,7.337842,0.105604,6.930000,7.570000
h1_arterial_ph_min,21820.0,7.328253,0.108332,6.900000,7.563000
h1_arterial_po2_max,22213.0,163.636351,112.846922,34.000000,534.905000
h1_arterial_po2_min,22213.0,146.329130,100.291004,31.000000,514.905000
h1_pao2fio2ratio_max,16399.0,248.041153,131.506940,42.000000,720.000000
h1_pao2fio2ratio_min,16399.0,240.026774,128.570671,38.000000,654.813793

In [7]:
# Categorical Feature Statistics
cat_stats

                                                      value   count    pct
column                      rank
aids                        1                             0  127228   99.9
                            2                             1     130    0.1
apache_2_diagnosis          1                         113.0   15912  12.49
                            2                         301.0    9676    7.6
                            3                         302.0    8740   6.86
                            4                         112.0    5899   4.63
                            5                         308.0    5773   4.53
apache_3j_diagnosis         1                        501.05    5991    4.7
                            2                        107.01    5899   4.63
                            3                        403.01    5329   4.18
                            4                        106.01    5190   4.08
                            5                        703.03    4129   3.24
apache_post_operative       1                             0  100798  79.15
                            2                             1   26560  20.85
arf_apache                  1                             0  123810  97.21
                            2                             1    3548   2.79
cirrhosis                   1                             0  125294  98.38
                            2                             1    2064   1.62
d1_diasbp_max_clipped       1                         False  125997  98.93
                            2                          True    1361   1.07
d1_diasbp_min_clipped       1                         False  125970  98.91
                            2                          True    1388   1.09
d1_heartrate_max_clipped    1                         False  125944  98.89
                            2                          True    1414   1.11
d1_heartrate_min_clipped    1                         False  126483  99.31
                            2                          True     875   0.69
d1_sysbp_max_clipped        1                         False  126057  98.98
                            2                          True    1301   1.02
d1_sysbp_min_clipped        1                         False  126050  98.97
                            2                          True    1308   1.03
diabetes_mellitus           1                             0   99801  78.36
                            2                             1   27557  21.64
elective_surgery            1                             0  103005  80.88
                            2                             1   24353  19.12
ethnicity                   1                     Caucasian   98171  77.08
                            2              African American   13538  10.63
                            3                 Other/Unknown    6131   4.81
                            4                      Hispanic    4957   3.89
                            5                         Asian    2136   1.68
gcs_unable_apache           1                           0.0  125232  98.33
                            2                           1.0    1445   1.13
                            3                          <NA>     681   0.53
gender                      1                             M   69152   54.3
                            2                             F   58166  45.67
                            3                          <NA>      40   0.03
heart_rate_apache_clipped   1                         False  126025  98.95
                            2                          True    1333   1.05
hepatic_failure             1                             0  125613  98.63
                            2                             1    1745   1.37
hospital_admit_source       1          Emergency Department   50082  39.32
                            2                          <NA>   32415  25.45
                            3                Operating Room   13585  10.67
                            4                         Floor   11062   8.69
                            5                  Direct Admit    8090   6.35
hospital_id                 1                           118    4241   3.33
                            2                            19    3781   2.97
                            3                           188    3022   2.37
                            4                            86    2907   2.28
                            5                             7    2879   2.26
icu_admit_source            1          Accident & Emergency   75076  58.95
                            2     Operating Room / Recovery   27029  21.22
                            3                         Floor   20946  16.45
                            4                Other Hospital    3393   2.66
                            5                     Other ICU     693   0.54
icu_id                      1                          1019    1325   1.04
                            2                           646    1281   1.01
                            3                           876    1257   0.99
                            4                           653    1254   0.98
                            5                           413    1193   0.94
icu_stay_type               1                         admit  122066  95.84
                            2                      transfer    4691   3.68
                            3                       readmit     601   0.47
icu_type                    1                  Med-Surg ICU   69835  54.83
                            2                     CCU-CTICU   11021   8.65
                            3                          MICU   10653   8.36
                            4                     Neuro ICU   10339   8.12
                            5                          SICU    8094   6.36
immunosuppression           1                             0  124075  97.42
                            2                             1    3283   2.58
intubated_apache            1                             0  107408  84.34
                            2                             1   19950  15.66
leukemia                    1                             0  126430  99.27
                            2                             1     928   0.73
lymphoma                    1                             0  126824  99.58
                            2                             1     534   0.42
solid_tumor_with_metastasis 1                             0  124683   97.9
                            2                             1    2675    2.1
ventilated_apache           1                             0   85408  67.06
                            2                             1   41950  32.94

In [8]:
# Target Distribution
target_df

                   count    pct
diabetes_mellitus
0                  99801  78.36
1                  27557  21.64

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...

Saving curated container to wids_diabetes_mellitus/019d5dca-97d8-77e8-9938-c7284735aaed

019d5dca-97d8-77e8-9938-c7284735aaed
04e0480c1b15a6df6539af6260d9fc85e49e03c8d659ec0a16dffe6958df1deb