### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="home_credit_default_stability_1m",
    version_from_unique_name="home_credit_default_stability",
    version_comment="""
We randomly sub-sample the train data to 1 million rows. We follow TabReD and use random sub-sampling. The idea behind this instead of a time-based subsampling is to keep data from various time periods and model the distribution shift across the full time horizon.
""",
    # same as home_credit_default_stability.ipynb
    dataset_year="2024",
    domain_str="finance",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/home-credit-credit-risk-model-stability",
    download_description="""
We get the data from the Kaggle competition.

kaggle competitions download -c home-credit-credit-risk-model-stability
mkdir -p local-data-warehouse/home_credit_default_stability && mv home-credit-credit-risk-model-stability.zip local-data-warehouse/home_credit_default_stability/ && cd local-data-warehouse/home_credit_default_stability/ && unzip home-credit-credit-risk-model-stability.zip && rm home-credit-credit-risk-model-stability.zip && rm -rf csv_files && rm -rf parquet_files/test && rm sample_submission.csv feature_definitions.csv
""",
    # References
    academic_reference_bibtex=r"""@misc{Herman2024HomeCreditCreditRiskModelStability,
  author = {Daniel Herman and Tomas Jelinek and Walter Reade and Maggie Demkin and Addison Howard},
  title  = {Home Credit - Credit Risk Model Stability},
  year   = {2024},
  howpublished = {\url{https://kaggle.com/competitions/home-credit-credit-risk-model-stability}},
  note   = {Kaggle competition}
}
""",
    academic_reference_bibtex_key="Herman2024HomeCreditCreditRiskModelStability",
    license="Kaggle Competition Rules",
    data_tags=["Non-IID", "Temporal"],
    curation_comments="""
We start with the data from Kaggle and follow the preprocessing from TabRed (https://github.com/yandex-research/tabred/tree/main/preprocessing#homecredit-default-stability-homecredit-20), which in turn follows two Kaggle solutions (https://www.kaggle.com/competitions/home-credit-credit-risk-model-stability/discussion/507946, https://www.kaggle.com/code/yuuniekiri/fork-of-home-credit-catboost-inference).

- We follow TabRed and use temporal splits for the task. The Kaggle experts used various strategies and most commonly StratifiedGroupKFold to align offline CV with the temporal-split data on the leaderboard. That is, the split used for training can be StratifiedGroupKFold, but not for testing.
- Note, the original competition was heavily influenced by metric hacking, which is not relevant for our offline benchmark tasks. Thus, results are not directly comparable ot transferable.
- We change the preprocessing from Kaggle and TabRed in specific steps: (A) we depart from the TabRed and Kaggle solutions in that we do not drop high-cardinality string columns, (B) we do not drop month and week, as it was only dropped due to the metric leak in the competition, (C) we only drop constant columns if they are constant w.r.t. NaN and non-NaN values, (D) we do not perform ordinal encoding and drop minor categories, (E) we do not sub-sample the data, (F) we keep the date column without transformations for the pipelines to handle, and (G) the code from TabRed is outdated and does not function the same anymore when it comes to down-casting string and categorical data of the data from Kaggle, we fix this by treating categorical data as categorical following the original Kaggle scripts, moreover, we had to remove getting the std() of a date column, which is not supported anymore.
- We drop case_id as it is already collapsed and thus does not contain extra information.
- We cast all object and string columns to be categorical. Note that they are anonymized and string preprocessing likely does not add a lot of value as a result.
- We drop name-related columns as they do not hold relevant information. These were otherwise dropped as high-cardinality string columns in TabRed or on Kaggle.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="target",
    problem_type="binary_classification",
    # There exists a custom metric see https://www.kaggle.com/competitions/home-credit-credit-risk-model-stability
    # However, we decide to not use it, as it was seen to be not stable and was able to be clearly exploited for modelling in the competition.
    objective_metric_name="roc_auc",
    stratify_on="target",
    time_on="date_decision",
)

## Preprocessing

Start by running `run_large_data_preprocessing.py` outside this notebook to get the merged data in place.

In [2]:
import pandas as pd

df = pd.read_parquet(dataset_mold.path / "merged_input_data.parquet")
print("Loaded data shape:", df.shape)

# Drop constant columns
df = df.drop(columns=[
    # ID column (already collapsed and thus no extra information
    "case_id",
    # Name columns that are missing or have no affect due to case-id related grouping and anonymization
    "last_name_4917606M",
    "first_name_4917606M",
    "last_name_4527232M",
    "first_name_4527232M",
    "last_employername_160M",
    "first_employername_160M",
])
df["date_decision"] = pd.to_datetime(df["date_decision"], format="%Y-%m-%d")
as_cat_type = [
    "target",
    *list(df.columns[
    (df.dtypes == "object") | (df.dtypes == "string")
    ])
]
df[as_cat_type] = df[as_cat_type].astype("category")
df = df.reset_index(drop=True)

Loaded data shape: (1526659, 719)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
    duplicate_column_check=False,
)

#### Dataset Overview
Rows: 1,526,659
Columns: 712
Use sampling: True (sample size: 152,666)
Get missing and unique counts per column...

missing/unique per-col:   0%|          | 0/712 [00:00<?, ?it/s]

Get example values per column...

examples per-col:   0%|          | 0/712 [00:00<?, ?it/s]

Get numeric feature statistics...

numeric stats:   0%|          | 0/598 [00:00<?, ?it/s]

Get cat stats...

cat stats:   0%|          | 0/114 [00:00<?, ?it/s]

Get target stats...
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['mean_totaloutstanddebtvalue_39A', 'max_debtoutstand_525A', 'max_totaloutstanddebtvalue_39A', 'min_totaloutstanddebtvalue_39A', 'std_annuity_853A', 'mean_outstandingamount_362A', 'max_outstandingamount_362A', 'std_credamount_590A', 'min_outstandingamount_362A', 'totalsettled_863A']
Rows remaining as candidates after top-10 filter: 212,416 (of 1,526,659)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,date_decision,MONTH,WEEK_NUM,target,actualdpdtolerance_344P,amtinstpaidbefduel24m_4187115A,annuity_780A,annuitynextmonth_57A,applicationcnt_361L,applications30d_658L,applicationscnt_1086L,applicationscnt_464L,applicationscnt_629L,applicationscnt_867L,avgdbddpdlast24m_3658932P,avgdbddpdlast3m_4187120P,avgdbdtollast24m_4525197P,avgdpdtolclosure24_3658938P,avginstallast24m_3658937A,avglnamtstart24m_4525187A,avgmaxdpdlast9m_3716943P,avgoutstandbalancel6m_4187114A,avgpmtlast12m_4525200A,cardtype_51L,clientscnt12m_3712952L,clientscnt3m_3712950L,clientscnt6m_3712949L,clientscnt_100L,clientscnt_1022L,clientscnt_1071L,clientscnt_1130L,clientscnt_157L,clientscnt_257L,clientscnt_304L,clientscnt_360L,clientscnt_493L,clientscnt_533L,clientscnt_887L,clientscnt_946L,cntincpaycont9m_3716944L,cntpmts24_3658933L,credamount_770A,credtype_322L,currdebt_22A,currdebtcredtyperange_828A,datefirstoffer_1144D,datelastinstal40dpd_247D,datelastunpaid_3546854D,daysoverduetolerancedd_3976961L,disbursedcredamount_1113A,disbursementtype_67L,downpmt_116A,dtlastpmtallstes_4499206D,eir_270L,equalitydataagreement_891L,firstclxcampaign_1125D,firstdatedue_489D,homephncnt_628L,inittransactionamount_650A,inittransactioncode_186L,isbidproduct_1095L,lastactivateddate_801D,lastapplicationdate_877D,lastapprcommoditycat_1041M,lastapprcommoditytypec_5251766M,lastapprcredamount_781A,lastapprdate_640D,lastcancelreason_561M,lastdelinqdate_224D,lastrejectcommoditycat_161M,lastrejectcommodtypec_5251769M,lastrejectcredamount_222A,lastrejectdate_50D,lastrejectreason_759M,lastrejectreasonclient_4145040M,lastst_736L,maininc_215A,maxannuity_159A,maxdbddpdlast1m_3658939P,maxdbddpdtollast12m_3658940P,maxdbddpdtollast6m_4187119P,maxdebt4_972A,maxdpdfrom6mto36m_3546853P,maxdpdinstldate_3546855D,maxdpdinstlnum_3546846P,maxdpdlast12m_727P,maxdpdlast24m_143P,maxdpdlast3m_392P,maxdpdlast6m_474P,maxdpdlast9m_1059P,maxdpdtolerance_374P,maxinstallast24m_3658928A,maxlnamtstart6m_4525199A,maxoutstandbalancel12m_4187113A,maxpmtlast3m_4525190A,mindbddpdlast24m_3658935P,mindbdtollast24m_4525191P,mobilephncnt_593L,monthsannuity_845L,numactivecreds_622L,numactivecredschannel_414L,numactiverelcontr_750L,numcontrs3months_479L,numincomingpmts_3546848L,numinstlallpaidearly3d_817L,numinstls_657L,numinstlsallpaid_934L,numinstlswithdpd10_728L,numinstlswithdpd5_4187116L,numinstlswithoutdpd_562L,numinstmatpaidtearly2d_4499204L,numinstpaid_4499208L,numinstpaidearly3d_3546850L,numinstpaidearly3dest_4493216L,numinstpaidearly5d_1087L,numinstpaidearly5dest_4493211L,numinstpaidearly5dobd_4499205L,numinstpaidearly_338L,numinstpaidearlyest_4493214L,numinstpaidlastcontr_4325080L,numinstpaidlate1d_3546852L,numinstregularpaid_973L,numinstregularpaidest_4493210L,numinsttopaygr_769L,numinsttopaygrest_4493213L,numinstunpaidmax_3546851L,numinstunpaidmaxest_4493212L,numnotactivated_1143L,numpmtchanneldd_318L,numrejects9m_859L,opencred_647L,pctinstlsallpaidearl3d_427L,pctinstlsallpaidlat10d_839L,pctinstlsallpaidlate1d_3546856L,pctinstlsallpaidlate4d_3546849L,pctinstlsallpaidlate6d_3546844L,pmtnum_254L,posfpd10lastmonth_333P,posfpd30lastmonth_3976960P,posfstqpd30lastmonth_3976962P,previouscontdistrict_112M,price_1097A,sellerplacecnt_915L,sellerplacescnt_216L,sumoutstandtotal_3546847A,sumoutstandtotalest_4493215A,totaldebt_9A,totalsettled_863A,totinstallast1m_4525188A,twobodfilling_608L,validfrom_1069D,assignmentdate_238D,assignmentdate_4527235D,birthdate_574D,contractssum_5085716L,dateofbirth_337D,days120_123L,days180_256L,days30_165L,days360_512L,days90_310L,description_5085714M,education_1103M,education_88M,firstquarter_103L,fourthquarter_440L,maritalst_385M,maritalst_893M,pmtaverage_3A,pmtaverage_4527227A,pmtcount_4527229L,pmtcount_693L,pmtscount_423L,pmtssum_45A,requesttype_4525192L,responsedate_1012D,responsedate_4527233D,responsedate_4917613D,secondquarter_766L,thirdquarter_1082L,max_actualdpd_943P,min_actualdpd_943P,mean_actualdpd_943P,std_actualdpd_943P,max_annuity_853A,min_annuity_853A,mean_annuity_853A,std_annuity_853A,max_byoccupationinc_3656910L,min_byoccupationinc_3656910L,mean_byoccupationinc_3656910L,std_byoccupationinc_3656910L,max_childnum_21L,min_childnum_21L,mean_childnum_21L,std_childnum_21L,max_credacc_actualbalance_314A,min_credacc_actualbalance_314A,mean_credacc_actualbalance_314A,max_credacc_credlmt_575A,min_credacc_credlmt_575A,mean_credacc_credlmt_575A,std_credacc_credlmt_575A,max_credacc_maxhisbal_375A,min_credacc_maxhisbal_375A,mean_credacc_maxhisbal_375A,max_credacc_minhisbal_90A,min_credacc_minhisbal_90A,mean_credacc_minhisbal_90A,max_credacc_transactions_402L,min_credacc_transactions_402L,mean_credacc_transactions_402L,max_credamount_590A,min_credamount_590A,mean_credamount_590A,std_credamount_590A,max_currdebt_94A,min_currdebt_94A,mean_currdebt_94A,std_currdebt_94A,max_downpmt_134A,min_downpmt_134A,mean_downpmt_134A,std_downpmt_134A,max_isbidproduct_390L,mean_isbidproduct_390L,std_isbidproduct_390L,max_isdebitcard_527L,min_isdebitcard_527L,mean_isdebitcard_527L,std_isdebitcard_527L,max_mainoccupationinc_437A,min_mainoccupationinc_437A,mean_mainoccupationinc_437A,std_mainoccupationinc_437A,max_maxdpdtolerance_577P,min_maxdpdtolerance_577P,mean_maxdpdtolerance_577P,std_maxdpdtolerance_577P,max_outstandingdebt_522A,min_outstandingdebt_522A,mean_outstandingdebt_522A,std_outstandingdebt_522A,max_pmtnum_8L,min_pmtnum_8L,mean_pmtnum_8L,std_pmtnum_8L,max_revolvingaccount_394A,min_revolvingaccount_394A,mean_revolvingaccount_394A,last_cancelreason_3545846M,n_unique_cancelreason_3545846M,first_cancelreason_3545846M,last_credacc_status_367L,n_unique_credacc_status_367L,last_credtype_587L,n_unique_credtype_587L,first_credtype_587L,last_district_544M,n_unique_district_544M,first_district_544M,last_education_1138M,n_unique_education_1138M,first_education_1138M,last_familystate_726L,n_unique_familystate_726L,first_familystate_726L,last_inittransactioncode_279L,n_unique_inittransactioncode_279L,first_inittransactioncode_279L,last_postype_4733339M,n_unique_postype_4733339M,first_postype_4733339M,last_profession_152M,n_unique_profession_152M,first_profession_152M,last_rejectreason_755M,n_unique_rejectreason_755M,first_rejectreason_755M,last_rejectreasonclient_4145042M,n_unique_rejectreasonclient_4145042M,first_rejectreasonclient_4145042M,last_status_219L,n_unique_status_219L,first_status_219L,max_approvaldate_319D,min_approvaldate_319D,mean_approvaldate_319D,min_creationdate_885D,mean_creationdate_885D,max_dateactivated_425D,min_dateactivated_425D,mean_dateactivated_425D,max_dtlastpmt_581D,min_dtlastpmt_581D,mean_dtlastpmt_581D,max_dtlastpmtallstes_3545839D,min_dtlastpmtallstes_3545839D,mean_dtlastpmtallstes_3545839D,max_employedfrom_700D,min_employedfrom_700D,mean_employedfrom_700D,max_firstnonzeroinstldate_307D,min_firstnonzeroinstldate_307D,mean_firstnonzeroinstldate_307D,max_amount_4527230A,min_amount_4527230A,mean_amount_4527230A,std_amount_4527230A,n_unique_name_4527232M,max_recorddate_4527225D,max_amount_4917619A,min_amount_4917619A,mean_amount_4917619A,std_amount_4917619A,n_unique_name_4917606M,max_deductiondate_4917603D,min_deductiondate_4917603D,mean_deductiondate_4917603D,max_pmtamount_36A,min_pmtamount_36A,mean_pmtamount_36A,std_pmtamount_36A,n_unique_employername_160M,max_processingdate_168D,min_processingdate_168D,mean_processingdate_168D,max_annualeffectiverate_199L,min_annualeffectiverate_199L,mean_annualeffectiverate_199L,std_annualeffectiverate_199L,max_annualeffectiverate_63L,min_annualeffectiverate_63L,mean_annualeffectiverate_63L,max_contractsum_5085717L,min_contractsum_5085717L,mean_contractsum_5085717L,std_contractsum_5085717L,max_credlmt_230A,min_credlmt_230A,mean_credlmt_230A,std_credlmt_230A,max_credlmt_935A,min_credlmt_935A,mean_credlmt_935A,std_credlmt_935A,max_debtoutstand_525A,max_debtoverdue_47A,max_dpdmax_139P,min_dpdmax_139P,mean_dpdmax_139P,std_dpdmax_139P,max_dpdmax_757P,min_dpdmax_757P,mean_dpdmax_757P,std_dpdmax_757P,max_dpdmaxdatemonth_442T,min_dpdmaxdatemonth_442T,mean_dpdmaxdatemonth_442T,std_dpdmaxdatemonth_442T,max_dpdmaxdatemonth_89T,min_dpdmaxdatemonth_89T,mean_dpdmaxdatemonth_89T,std_dpdmaxdatemonth_89T,max_dpdmaxdateyear_596T,min_dpdmaxdateyear_596T,mean_dpdmaxdateyear_596T,std_dpdmaxdateyear_596T,max_dpdmaxdateyear_896T,min_dpdmaxdateyear_896T,mean_dpdmaxdateyear_896T,std_dpdmaxdateyear_896T,max_instlamount_768A,min_instlamount_768A,mean_instlamount_768A,std_instlamount_768A,max_instlamount_852A,min_instlamount_852A,mean_instlamount_852A,std_instlamount_852A,max_monthlyinstlamount_332A,min_monthlyinstlamount_332A,mean_monthlyinstlamount_332A,std_monthlyinstlamount_332A,max_monthlyinstlamount_674A,min_monthlyinstlamount_674A,mean_monthlyinstlamount_674A,std_monthlyinstlamount_674A,max_nominalrate_281L,min_nominalrate_281L,mean_nominalrate_281L,std_nominalrate_281L,max_nominalrate_498L,min_nominalrate_498L,mean_nominalrate_498L,std_nominalrate_498L,max_numberofcontrsvalue_258L,min_numberofcontrsvalue_258L,mean_numberofcontrsvalue_258L,max_numberofcontrsvalue_358L,min_numberofcontrsvalue_358L,mean_numberofcontrsvalue_358L,max_numberofinstls_229L,min_numberofinstls_229L,mean_numberofinstls_229L,std_numberofinstls_229L,max_numberofinstls_320L,min_numberofinstls_320L,mean_numberofinstls_320L,std_numberofinstls_320L,max_numberofoutstandinstls_520L,min_numberofoutstandinstls_520L,mean_numberofoutstandinstls_520L,std_numberofoutstandinstls_520L,max_numberofoutstandinstls_59L,min_numberofoutstandinstls_59L,mean_numberofoutstandinstls_59L,std_numberofoutstandinstls_59L,max_numberofoverdueinstlmax_1039L,min_numberofoverdueinstlmax_1039L,mean_numberofoverdueinstlmax_1039L,std_numberofoverdueinstlmax_1039L,max_numberofoverdueinstlmax_1151L,min_numberofoverdueinstlmax_1151L,mean_numberofoverdueinstlmax_1151L,std_numberofoverdueinstlmax_1151L,max_numberofoverdueinstls_725L,min_numberofoverdueinstls_725L,mean_numberofoverdueinstls_725L,std_numberofoverdueinstls_725L,max_numberofoverdueinstls_834L,min_numberofoverdueinstls_834L,mean_numberofoverdueinstls_834L,std_numberofoverdueinstls_834L,max_outstandingamount_354A,min_outstandingamount_354A,mean_outstandingamount_354A,std_outstandingamount_354A,max_outstandingamount_362A,min_outstandingamount_362A,mean_outstandingamount_362A,std_outstandingamount_362A,max_overdueamount_31A,min_overdueamount_31A,mean_overdueamount_31A,std_overdueamount_31A,max_overdueamount_659A,min_overdueamount_659A,mean_overdueamount_659A,std_overdueamount_659A,max_overdueamountmax2_14A,min_overdueamountmax2_14A,mean_overdueamountmax2_14A,std_overdueamountmax2_14A,max_overdueamountmax2_398A,min_overdueamountmax2_398A,mean_overdueamountmax2_398A,std_overdueamountmax2_398A,max_overdueamountmax_155A,min_overdueamountmax_155A,mean_overdueamountmax_155A,std_overdueamountmax_155A,max_overdueamountmax_35A,min_overdueamountmax_35A,mean_overdueamountmax_35A,std_overdueamountmax_35A,max_overdueamountmaxdatemonth_284T,min_overdueamountmaxdatemonth_284T,mean_overdueamountmaxdatemonth_284T,std_overdueamountmaxdatemonth_284T,max_overdueamountmaxdatemonth_365T,min_overdueamountmaxdatemonth_365T,mean_overdueamountmaxdatemonth_365T,std_overdueamountmaxdatemonth_365T,max_overdueamountmaxdateyear_2T,min_overdueamountmaxdateyear_2T,mean_overdueamountmaxdateyear_2T,std_overdueamountmaxdateyear_2T,max_overdueamountmaxdateyear_994T,min_overdueamountmaxdateyear_994T,mean_overdueamountmaxdateyear_994T,std_overdueamountmaxdateyear_994T,max_periodicityofpmts_1102L,min_periodicityofpmts_1102L,mean_periodicityofpmts_1102L,std_periodicityofpmts_1102L,max_periodicityofpmts_837L,min_periodicityofpmts_837L,mean_periodicityofpmts_837L,std_periodicityofpmts_837L,max_prolongationcount_1120L,min_prolongationcount_1120L,mean_prolongationcount_1120L,max_residualamount_488A,min_residualamount_488A,mean_residualamount_488A,std_residualamount_488A,max_residualamount_856A,min_residualamount_856A,mean_residualamount_856A,std_residualamount_856A,max_totalamount_6A,min_totalamount_6A,mean_totalamount_6A,std_totalamount_6A,max_totalamount_996A,min_totalamount_996A,mean_totalamount_996A,std_totalamount_996A,max_totaldebtoverduevalue_178A,min_totaldebtoverduevalue_178A,mean_totaldebtoverduevalue_178A,max_totaldebtoverduevalue_718A,min_totaldebtoverduevalue_718A,mean_totaldebtoverduevalue_718A,max_totaloutstanddebtvalue_39A,min_totaloutstanddebtvalue_39A,mean_totaloutstanddebtvalue_39A,max_totaloutstanddebtvalue_668A,min_totaloutstanddebtvalue_668A,mean_totaloutstanddebtvalue_668A,last_classificationofcontr_13M,n_unique_classificationofcontr_13M,first_classificationofcontr_13M,last_classificationofcontr_400M,n_unique_classificationofcontr_400M,first_classificationofcontr_400M,last_contractst_545M,n_unique_contractst_545M,first_contractst_545M,last_contractst_964M,n_unique_contractst_964M,first_contractst_964M,last_description_351M,n_unique_description_351M,first_description_351M,last_financialinstitution_382M,n_unique_financialinstitution_382M,first_financialinstitution_382M,last_financialinstitution_591M,n_unique_financialinstitution_591M,first_financialinstitution_591M,last_purposeofcred_426M,n_unique_purposeofcred_426M,first_purposeofcred_426M,last_purposeofcred_874M,n_unique_purposeofcred_874M,first_purposeofcred_874M,n_unique_subjectrole_182M,first_subjectrole_182M,n_unique_subjectrole_93M,first_subjectrole_93M,max_dateofcredend_289D,min_dateofcredend_289D,mean_dateofcredend_289D,max_dateofcredend_353D,min_dateofcredend_353D,mean_dateofcredend_353D,max_dateofcredstart_181D,min_dateofcredstart_181D,mean_dateofcredstart_181D,max_dateofcredstart_739D,min_dateofcredstart_739D,mean_dateofcredstart_739D,max_dateofrealrepmt_138D,min_dateofrealrepmt_138D,mean_dateofrealrepmt_138D,max_lastupdate_1112D,min_lastupdate_1112D,mean_lastupdate_1112D,max_lastupdate_388D,min_lastupdate_388D,mean_lastupdate_388D,max_numberofoverdueinstlmaxdat_148D,min_numberofoverdueinstlmaxdat_148D,mean_numberofoverdueinstlmaxdat_148D,max_numberofoverdueinstlmaxdat_641D,min_numberofoverdueinstlmaxdat_641D,mean_numberofoverdueinstlmaxdat_641D,max_overdueamountmax2date_1002D,min_overdueamountmax2date_1002D,mean_overdueamountmax2date_1002D,max_overdueamountmax2date_1142D,min_overdueamountmax2date_1142D,mean_overdueamountmax2date_1142D,max_refreshdate_3813885D,min_refreshdate_3813885D,mean_refreshdate_3813885D,max_contaddr_smempladdr_334L,mean_contaddr_smempladdr_334L,max_mainoccupationinc_384A,max_personindex_1023L,mean_personindex_1023L,std_personindex_1023L,max_persontype_1072L,mean_persontype_1072L,std_persontype_1072L,mean_persontype_792L,std_persontype_792L,max_safeguarantyflag_411L,mean_safeguarantyflag_411L,last_contaddr_district_15M,n_unique_contaddr_district_15M,first_contaddr_district_15M,last_contaddr_zipcode_807M,n_unique_contaddr_zipcode_807M,first_contaddr_zipcode_807M,last_education_927M,n_unique_education_927M,first_education_927M,n_unique_empl_employedtotal_800L,first_empl_employedtotal_800L,n_unique_empl_industry_691L,first_empl_industry_691L,last_empladdr_district_926M,n_unique_empladdr_district_926M,first_empladdr_district_926M,last_empladdr_zipcode_114M,n_unique_empladdr_zipcode_114M,first_empladdr_zipcode_114M,n_unique_familystate_447L,first_familystate_447L,n_unique_gender_992L,n_unique_housetype_905L,first_housetype_905L,n_unique_housingtype_772L,last_incometype_1044T,n_unique_incometype_1044T,first_incometype_1044T,last_language1_981M,n_unique_language1_981M,first_language1_981M,n_unique_maritalst_703L,last_registaddr_district_1083M,n_unique_registaddr_district_1083M,first_registaddr_district_1083M,last_registaddr_zipcode_184M,n_unique_registaddr_zipcode_184M,first_registaddr_zipcode_184M,last_relationshiptoclient_415T,n_unique_relationshiptoclient_415T,last_relationshiptoclient_642T,last_role_1084L,n_unique_role_1084L,first_role_1084L,n_unique_role_993L,last_sex_738L,first_sex_738L,last_type_25L,n_unique_type_25L,first_type_25L,max_birth_259D,max_empl_employedfrom_271D,max_amount_416A,min_amount_416A,mean_amount_416A,max_openingdate_313D,min_openingdate_313D,mean_openingdate_313D,max_openingdate_857D,min_openingdate_857D,mean_openingdate_857D,max_collater_valueofguarantee_1124L,min_collater_valueofguarantee_1124L,mean_collater_valueofguarantee_1124L,std_collater_valueofguarantee_1124L,max_collater_valueofguarantee_876L,min_collater_valueofguarantee_876L,mean_collater_valueofguarantee_876L,std_collater_valueofguarantee_876L,max_pmts_dpd_1073P,min_pmts_dpd_1073P,mean_pmts_dpd_1073P,std_pmts_dpd_1073P,max_pmts_dpd_303P,min_pmts_dpd_303P,mean_pmts_dpd_303P,std_pmts_dpd_303P,std_pmts_month_158T,std_pmts_month_706T,min_pmts_overdue_1140A,mean_pmts_overdue_1140A,std_pmts_overdue_1140A,min_pmts_overdue_1152A,mean_pmts_overdue_1152A,std_pmts_overdue_1152A,max_pmts_year_1139T,min_pmts_year_1139T,mean_pmts_year_1139T,std_pmts_year_1139T,max_pmts_year_507T,min_pmts_year_507T,mean_pmts_year_507T,std_pmts_year_507T,last_collater_typofvalofguarant_298M,n_unique_collater_typofvalofguarant_298M,first_collater_typofvalofguarant_298M,last_collater_typofvalofguarant_407M,n_unique_collater_typofvalofguarant_407M,first_collater_typofvalofguarant_407M,last_collaterals_typeofguarante_359M,n_unique_collaterals_typeofguarante_359M,first_collaterals_typeofguarante_359M,last_collaterals_typeofguarante_669M,n_unique_collaterals_typeofguarante_669M,first_collaterals_typeofguarante_669M,last_subjectroles_name_541M,n_unique_subjectroles_name_541M,first_subjectroles_name_541M,last_subjectroles_name_838M,n_unique_subjectroles_name_838M,first_subjectroles_name_838M

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,isbidproduct_1095L,bool,0.0,0.00,2.0,"False, True"
1,last_credacc_status_367L,category,1450057.0,94.98,6.0,"AC, CL, CA, PCL, PO, CR"
2,equalitydataagreement_891L,category,1448632.0,94.89,2.0,"True, False"
3,first_housetype_905L,category,1425841.0,93.40,6.0,"OWNED, PARENTAL, FLAT, COMPANY_FLAT, COOP_FLAT, STATE_FLAT"
4,last_relationshiptoclient_415T,category,1362974.0,89.28,10.0,"CHILD, SPOUSE, OTHER_RELATIVE, SIBLING, FRIEND, OTHER, PARENT, COLLEAGUE, NEIGHBOR, GRAND_PARENT"
5,cardtype_51L,category,1334968.0,87.44,2.0,"INSTANT, PERSONALIZED"
6,max_isdebitcard_527L,category,1182972.0,77.49,2.0,"False, True"
7,min_isdebitcard_527L,category,1182972.0,77.49,2.0,"False, True"
8,first_familystate_726L,category,1026869.0,67.26,5.0,"MARRIED, SINGLE, WIDOWED, DIVORCED, LIVING_WITH_PARTNER"
9,first_empl_industry_691L,category,1004423.0,65.79,24.0,"OTHER, GOVERNMENT, EDUCATION, TRADE, HEALTH, MANUFACTURING, AGRICULTURE, TRANSPORTATION, MINING, CATERING"
10,first_empl_employedtotal_800L,category,998344.0,65.39,3.0,"MORE_FIVE, MORE_ONE, LESS_ONE"
11,last_relationshiptoclient_642T,category,935626.0,61.29,10.0,"SIBLING, SPOUSE, CHILD, OTHER_RELATIVE, FRIEND, PARENT, COLLEAGUE, OTHER, NEIGHBOR, GRAND_PARENT"
12,requesttype_4525192L,category,853395.0,55.90,3.0,"DEDUCTION_6, PENSION_6, SOCIAL_6"
13,first_familystate_447L,category,798046.0,52.27,5.0,"MARRIED, SINGLE, WIDOWED, DIVORCED, LIVING_WITH_PARTNER"
14,last_incometype_1044T,category,757320.0,49.61,8.0,"PRIVATE_SECTOR_EMPLOYEE, SALARIED_GOVT, RETIRED_PENSIONER, EMPLOYED, SELFEMPLOYED, OTHER, HANDICAPPED_2, HANDICAPPED_3"
15,last_sex_738L,category,757320.0,49.61,2.0,"F, M"
16,last_familystate_726L,category,408731.0,26.77,5.0,"MARRIED, SINGLE, WIDOWED, DIVORCED, LIVING_WITH_PARTNER"
17,first_credtype_587L,category,333576.0,21.85,3.0,"COL, CAL, REL"
18,first_inittransactioncode_279L,category,333576.0,21.85,3.0,"POS, CASH, NDF"
19,last_credtype_587L,category,311529.0,20.41,3.0,"COL, CAL, REL"
20,last_inittransactioncode_279L,category,311529.0,20.41,3.0,"POS, CASH, NDF"
21,lastst_736L,category,305137.0,19.99,11.0,"D, A, K, T, N, S, Q, L, H, R"
22,opencred_647L,category,305137.0,19.99,2.0,"False, True"
23,max_isbidproduct_390L,category,305137.0,19.99,2.0,"False, True"
24,last_cancelreason_3545846M,category,305137.0,19.99,66.0,"a55475b1, P94_109_143, P73_130_169, P85_114_140, P198_89_166, P180_60_137, P24_27_36, P141_135_146, P11_56_131, P98_38_170"
25,first_cancelreason_3545846M,category,305137.0,19.99,74.0,"a55475b1, P94_109_143, P30_86_84, P85_114_140, P198_89_166, P180_60_137, P24_27_36, P73_130_169, P52_67_90, P11_56_131"
26,last_district_544M,category,305137.0,19.99,404.0,"a55475b1, P131_33_167, P197_47_166, P123_6_84, P98_137_111, P204_99_158, P147_21_170, P159_143_123, P178_112_160, P111_135_181"
27,first_district_544M,category,305137.0,19.99,969.0,"a55475b1, P131_33_167, P197_47_166, P123_6_84, P98_137_111, P204_99_158, P159_143_123, P62_144_102, P147_21_170, P178_112_160"
28,last_education_1138M,category,305137.0,19.99,6.0,"P97_36_170, P33_146_175, a55475b1, P106_81_188, P17_36_170, P157_18_172"
29,first_education_1138M,category,305137.0,19.99,6.0,"a55475b1, P97_36_170, P33_146_175, P106_81_188, P17_36_170, P157_18_172"
30,last_postype_4733339M,category,305137.0,19.99,9.0,"a55475b1, P177_117_192, P60_146_156, P149_40_170, P46_145_78, P217_110_186, P67_102_161, P169_115_83, P140_48_169"
31,first_postype_4733339M,category,305137.0,19.99,9.0,"a55475b1, P177_117_192, P46_145_78, P149_40_170, P67_102_161, P60_146_156, P217_110_186, P169_115_83, P140_48_169"
32,last_profession_152M,category,305137.0,19.99,3575.0,"a55475b1, P46_72_80, P104_137_180, P25_111_112, P62_39_175, P116_87_104, P121_114_58, P95_143_148, P10_42_172, P116_59_165"
33,first_profession_152M,category,305137.0,19.99,1999.0,"a55475b1, P46_72_80, P203_66_70, P10_42_172, P104_137_180, P94_2_52, P139_125_64, P21_76_53, P143_116_69, P167_22_171"
34,last_rejectreason_755M,category,305137.0,19.99,17.0,"a55475b1, P99_56_166, P45_84_106, P198_131_9, P94_109_143, P196_88_176, P121_60_164, P5_143_178, P185_59_178, P53_10_15"
35,first_rejectreason_755M,category,305137.0,19.99,18.0,"a55475b1, P99_56_166, P94_109_143, P45_84_106, P198_131_9, P48_22_32, P30_86_84, P121_60_164, P52_67_90, P196_88_176"
36,last_rejectreasonclient_4145042M,category,305137.0,19.99,11.0,"a55475b1, P94_109_143, P5_143_178, P30_86_84, P84_14_61, P19_25_34, P52_67_90, P53_10_15, P129_162_80, P69_72_116"
37,first_rejectreasonclient_4145042M,category,305137.0,19.99,14.0,"a55475b1, P94_109_143, P30_86_84, P52_67_90, P69_72_116, P129_162_80, P84_14_61, P64_121_167, P19_25_34, P5_143_178"
38,last_status_219L,category,305203.0,19.99,10.0,"K, D, A, T, Q, N, H, L, S, P"
39,first_status_219L,category,305137.0,19.99,11.0,"D, A, K, T, N, S, Q, L, H, R"
40,last_collater_typofvalofguarant_298M,category,141371.0,9.26,3.0,"a55475b1, 8fd95e4b, 9a0c095e"
41,first_collater_typofvalofguarant_298M,category,141371.0,9.26,5.0,"9a0c095e, 8fd95e4b, a55475b1, 06fb9ba8, 26cf31be"
42,last_collater_typofvalofguarant_407M,category,141371.0,9.26,3.0,"a55475b1, 9a0c095e, 8fd95e4b"
43,first_collater_typofvalofguarant_407M,category,141371.0,9.26,7.0,"9a0c095e, a55475b1, 8fd95e4b, 06fb9ba8, 3cbe86ba, 9276e4bb, c7a5ad39"
44,last_collaterals_typeofguarante_359M,category,141371.0,9.26,11.0,"a55475b1, c7a5ad39, 0e63c0f0, 3cbe86ba, 168ad9f3, 2fd21cf1, 5224034a, 7b62420e, 5994c34a, 9276e4bb"
45,first_collaterals_typeofguarante_359M,category,141371.0,9.26,15.0,"c7a5ad39, a55475b1, 3cbe86ba, 9276e4bb, 168ad9f3, 940efad7, 5224034a, 0e63c0f0, 7b62420e, 5994c34a"
46,last_collaterals_typeofguarante_669M,category,141371.0,9.26,8.0,"a55475b1, c7a5ad39, 0e63c0f0, 168ad9f3, 9276e4bb, 3cbe86ba, 46ab00a7, f4d8a027"
47,first_collaterals_typeofguarante_669M,category,141371.0,9.26,15.0,"c7a5ad39, a55475b1, 9276e4bb, 0e63c0f0, 7b62420e, 168ad9f3, 940efad7, 3cbe86ba, 2fd21cf1, 46ab00a7"
48,last_subjectroles_name_541M,category,141371.0,9.26,5.0,"a55475b1, ab3c25cf, 15f04f45, be4fd70b, daf49a8a"
49,first_subjectroles_name_541M,category,141371.0,9.26,9.0,"ab3c25cf, a55475b1, 15f04f45, daf49a8a, be4fd70b, 0c42a10e, 1d94eac1, 71ddaa88, 652d52e3"
50,last_subjectroles_name_838M,category,141371.0,9.26,2.0,"a55475b1, ab3c25cf"
51,first_subjectroles_name_838M,category,141371.0,9.26,9.0,"ab3c25cf, a55475b1, be4fd70b, daf49a8a, 15f04f45, P28_48_88, 0c42a10e, 71ddaa88, 652d52e3"
52,last_classificationofcontr_13M,category,140386.0,9.20,3.0,"a55475b1, 01f63ac8, ea6782cc"
53,first_classificationofcontr_13M,category,140386.0,9.20,11.0,"ea6782cc, a55475b1, 01f63ac8, 00135d9c, 4408ff0f, 1cf4e481, be7b251d, 2c070815, 87bdbcba, 4a5a01e3"
54,last_classificationofcontr_400M,category,140386.0,9.20,25.0,"a55475b1, ea6782cc, 01f63ac8, 00135d9c, 4408ff0f, 1cf4e481, ec922b98, 29e648ae, 130920c8, 42a42e75"
55,first_classificationofcontr_400M,category,140386.0,9.20,301.0,"ea6782cc, a55475b1, 01f63ac8, 42a42e75, 9158339f, e2453741, 00135d9c, d7416962, 62332675, 130920c8"
56,last_contractst_545M,category,140386.0,9.20,3.0,"a55475b1, 7241344e, 8f3a197f"
57,first_contractst_545M,category,140386.0,9.20,47.0,"7241344e, a55475b1, 8f3a197f, 0dc85f9d, b919198c, a52d5641, dd67cff0, 7640edc3, 885ce291, 82a92878"
58,last_contractst_964M,category,140386.0,9.20,60.0,"a55475b1, 7241344e, b2f1bf5c, 41694615, cae5106c, dc23998c, 181f7276, 8ff23ce1, 01f63ac8, 53b31557"
59,first_contractst_964M,category,140386.0,9.20,198.0,"7241344e, a55475b1, 8f3a197f, d7416962, 8260bab9, b83056f9, 4476359f, 89721976, a3386307, fc4d11b5"
60,last_description_351M,category,140386.0,9.20,10.0,"a55475b1, f8e51f8d, 0349102c, 1d89fa48, 6da7c7ed, 53179c19, 8a7423d5, 18e98e64, 95decc86, 0cb4d552"
61,first_description_351M,category,140386.0,9.20,11.0,"a55475b1, 95decc86, 6da7c7ed, 53179c19, f8e51f8d, 1d89fa48, 0cb4d552, 18e98e64, 8a7423d5, 0bfbf8f5"
62,last_financialinstitution_382M,category,140386.0,9.20,139.0,"a55475b1, Home Credit, P133_127_114, P150_136_157, 9a93e20f, d6a7d943, 50babcd4, b619fa46, P204_66_73, 8997b931"
63,first_financialinstitution_382M,category,140386.0,9.20,274.0,"a55475b1, Home Credit, P40_52_135, b619fa46, P150_136_157, P204_66_73, P133_127_114, P40_25_35, a4f0ab55, d6a7d943"
64,last_financialinstitution_591M,category,140386.0,9.20,9.0,"a55475b1, 0d39f5db, 50babcd4, 9325d851, 7fe08d3a, Home Credit, P150_136_157, P204_66_73, b619fa46"
65,first_financialinstitution_591M,category,140386.0,9.20,181.0,"P204_66_73, Home Credit, b619fa46, a55475b1, P150_136_157, P133_127_114, P102_97_118, d6a7d943, 50babcd4, P51_123_23"
66,last_purposeofcred_426M,category,140386.0,9.20,3.0,"a55475b1, 60c73645, 96a8fdfe"
67,first_purposeofcred_426M,category,140386.0,9.20,19.0,"60c73645, 96a8fdfe, a55475b1, 9e302002, e19fdece, 164ee705, 7a7d6960, 6ec903ee, e8f3b178, 44164129"
68,last_purposeofcred_874M,category,140386.0,9.20,19.0,"a55475b1, 60c73645, 96a8fdfe, e19fdece, 5065c2b8, 164ee705, 2162d1a4, 5d1b0cdd, d9ae1a0e, 27b6de28"
69,first_purposeofcred_874M,category,140386.0,9.20,21.0,"5065c2b8, 60c73645, a55475b1, 96a8fdfe, e19fdece, d9ae1a0e, 27b6de28, 5d1b0cdd, d11871e7, ee7d1eb8"
70,first_subjectrole_182M,category,140386.0,9.20,8.0,"ab3c25cf, a55475b1, be4fd70b, daf49a8a, P28_48_88, 15f04f45, 71ddaa88, 652d52e3"
71,first_subjectrole_93M,category,140386.0,9.20,6.0,"ab3c25cf, a55475b1, daf49a8a, be4fd70b, 15f04f45, 71ddaa88"
72,description_5085714M,category,26183.0,1.72,2.0,"a55475b1, 2fc785b2"
73,education_1103M,category,26183.0,1.72,5.0,"a55475b1, 6b2ae0fa, 717ddd49, 39a0853f, c8e1a1d0"
74,education_88M,category,26183.0,1.72,5.0,"a55475b1, 6b2ae0fa, 717ddd49, a34a13c8, c8e1a1d0"
75,maritalst_385M,category,26183.0,1.72,6.0,"a55475b1, 3439d993, a7fcb6e5, b6cabe76, 38c061ee, ecd83604"
76,maritalst_893M,category,26183.0,1.72,6.0,"a55475b1, 46b968c3, 1a19667c, 977b2a70, e18430ff, ecd83604"
77,last_role_1084L,category,6117.0,0.40,3.0,"CL, PE, EM"
78,last_type_25L,category,6117.0,0.40,7.0,"PRIMARY_MOBILE, PHONE, HOME_PHONE, ALTERNATIVE_PHONE, SECONDARY_MOBILE, PRIMARY_EMAIL, TWITTER"
79,disbursementtype_67L,category,866.0,0.06,3.0,"SBA, GBA, DD"
80,max_contaddr_smempladdr_334L,category,441.0,0.03,2.0,"False, True"
81,twobodfilling_608L,category,91.0,0.01,2.0,"FO, BO"
82,target,category,0.0,0.00,2.0,"0, 1"
83,credtype_322L,category,1.0,0.00,3.0,"COL, CAL, REL"
84,inittransactioncode_186L,category,1.0,0.00,3.0,"POS, CASH, NDF"
85,lastapprcommoditycat_1041M,category,0.0,0.00,45.0,"a55475b1, P159_130_59, P12_6_178, P148_110_5, P109_133_183, P53_45_92, P52_56_90, P33_29_177, P100_96_175, P21_79_33"
86,lastapprcommoditytypec_5251766M,category,0.0,0.00,214.0,"a55475b1, P75_90_70, P111_89_135, P172_87_177, P142_50_170, P174_113_42, P79_131_167, P42_60_161, P95_36_171, P200_75_140"
87,lastcancelreason_561M,category,0.0,0.00,74.0,"a55475b1, P94_109_143, P85_114_140, P198_89_166, P30_86_84, P180_60_137, P24_27_36, P73_130_169, P52_67_90, P11_56_131"
88,lastrejectcommoditycat_161M,category,0.0,0.00,45.0,"a55475b1, P159_130_59, P12_6_178, P148_110_5, P109_133_183, P53_45_92, P52_56_90, P33_29_177, P100_96_175, P21_79_33"
89,lastrejectcommodtypec_5251769M,category,0.0,0.00,187.0,"a55475b1, P75_90_70, P111_89_135, P142_50_170, P79_131_167, P95_36_171, P108_95_156, P172_87_177, P200_75_140, P174_113_42"
90,lastrejectreason_759M,category,0.0,0.00,18.0,"a55475b1, P99_56_166, P94_109_143, P45_84_106, P198_131_9, P48_22_32, P30_86_84, P121_60_164, P196_88_176, P52_67_90"
91,lastrejectreasonclient_4145040M,category,0.0,0.00,14.0,"a55475b1, P94_109_143, P30_86_84, P52_67_90, P69_72_116, P129_162_80, P84_14_61, P64_121_167, P19_25_34, P5_143_178"
92,previouscontdistrict_112M,category,0.0,0.00,223.0,"a55475b1, P131_33_167, P197_47_166, P123_6_84, P98_137_111, P204_99_158, P159_143_123, P62_144_102, P147_21_170, P178_112_160"
93,max_safeguarantyflag_411L,category,2.0,0.00,2.0,"True, False"
94,last_contaddr_district_15M,category,0.0,0.00,613.0,"a55475b1, P131_33_167, P123_6_84, P197_47_166, P204_99_158, P98_137_111, P62_144_102, P159_143_123, P178_112_160, P19_11_176"
95,first_contaddr_district_15M,category,0.0,0.00,975.0,"P131_33_167, P197_47_166, P123_6_84, P98_137_111, P159_143_123, P62_144_102, P204_99_158, P19_11_176, P178_112_160, P111_135_181"
96,last_contaddr_zipcode_807M,category,0.0,0.00,3451.0,"a55475b1, P161_14_174, P144_138_111, P46_103_143, P91_47_168, P212_16_169, P157_35_170, P62_116_179, P85_138_173, P11_15_81"
97,first_contaddr_zipcode_807M,category,0.0,0.00,3530.0,"P161_14_174, P144_138_111, P46_103_143, P91_47_168, P62_116_179, P212_16_169, P157_35_170, P11_15_81, P131_154_48, P85_138_173"
98,last_education_927M,category,0.0,0.00,6.0,"a55475b1, P97_36_170, P33_146_175, P106_81_188, P17_36_170, P157_18_172"
99,first_education_927M,category,0.0,0.00,6.0,"a55475b1, P97_36_170, P33_146_175, P106_81_188, P17_36_170, P157_18_172"
100,last_empladdr_district_926M,category,0.0,0.00,22.0,"a55475b1, P123_6_84, P54_133_26, P2_93_127, P197_47_166, P112_89_137, P121_51_168, P120_80_181, P117_30_169, P114_147_118"
101,first_empladdr_district_926M,category,0.0,0.00,223.0,"a55475b1, P197_47_166, P131_33_167, P62_144_102, P98_137_111, P123_6_84, P159_143_123, P19_11_176, P109_162_152, P112_89_137"
102,last_empladdr_zipcode_114M,category,0.0,0.00,24.0,"a55475b1, P144_138_111, P181_124_169, P45_57_146, P46_103_143, P118_161_181, P127_88_150, P11_15_81, P173_3_99, P161_14_174"
103,first_empladdr_zipcode_114M,category,0.0,0.00,3339.0,"a55475b1, P144_138_111, P161_14_174, P91_47_168, P8_88_79, P46_103_143, P62_116_179, P11_15_81, P45_25_38, P118_161_181"
104,first_incometype_1044T,category,0.0,0.00,9.0,"PRIVATE_SECTOR_EMPLOYEE, SALARIED_GOVT, RETIRED_PENSIONER, EMPLOYED, SELFEMPLOYED, OTHER, HANDICAPPED_2, HANDICAPPED_3, HANDICAPPED"
105,last_language1_981M,category,0.0,0.00,3.0,"a55475b1, P10_39_147, P209_127_106"
106,first_language1_981M,category,0.0,0.00,3.0,"P10_39_147, P209_127_106, a55475b1"
107,last_registaddr_district_1083M,category,0.0,0.00,636.0,"a55475b1, P131_33_167, P123_6_84, P197_47_166, P204_99_158, P98_137_111, P62_144_102, P159_143_123, P178_112_160, P19_11_176"
108,first_registaddr_district_1083M,category,0.0,0.00,991.0,"P131_33_167, P197_47_166, P123_6_84, P98_137_111, P159_143_123, P62_144_102, P204_99_158, P19_11_176, P178_112_160, P111_135_181"
109,last_registaddr_zipcode_184M,category,0.0,0.00,3452.0,"a55475b1, P161_14_174, P144_138_111, P46_103_143, P91_47_168, P212_16_169, P62_116_179, P157_35_170, P85_138_173, P11_15_81"
110,first_registaddr_zipcode_184M,category,0.0,0.00,3531.0,"P161_14_174, P144_138_111, a55475b1, P46_103_143, P91_47_168, P62_116_179, P212_16_169, P157_35_170, P11_15_81, P131_154_48"
111,first_role_1084L,category,0.0,0.00,2.0,"CL, EM"
112,first_sex_738L,category,0.0,0.00,2.0,"F, M"
113,first_type_25L,category,0.0,0.00,6.0,"PRIMARY_MOBILE, HOME_PHONE, PHONE, SECONDARY_MOBILE, PRIMARY_EMAIL, WHATSAPP"
114,date_decision,datetime64[ns],0.0,0.00,644.0,"2019-11-29 00:00:00, 2019-11-30 00:00:00, 2019-12-29 00:00:00, 2019-12-28 00:00:00, 2019-11-16 00:00:00, 2019-12-30 00:00:00, 2019-12-14 00:00:00, 2019-11-17 00:00:00, 2019-12-02 00:00:00, 2019-11-15 00:00:00"
115,max_prolongationcount_1120L,float32,1436524.0,94.10,80.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
116,min_prolongationcount_1120L,float32,1436524.0,94.10,44.0,"0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0"
117,mean_prolongationcount_1120L,float32,1436524.0,94.10,1370.0,"0.0, 1.0, 0.5, 2.0, 0.3333, 0.25, 0.2, 1.5, 0.6667, 3.0"
118,std_contractsum_5085717L,float32,1428031.0,93.54,95344.0,"0.0, 164376.875, 25338.3789, 472688.3438, 1034215.8125, 211143.0938, 592921.625, 2544.4104, 697492.1875, 1994339.375"
119,max_openingdate_857D,float32,1421572.0,93.12,2129.0,"-1283.0, -1862.0, -1788.0, -1660.0, -1324.0, -1885.0, -1477.0, -1201.0, -1238.0, -1772.0"
120,min_openingdate_857D,float32,1421572.0,93.12,2158.0,"-1862.0, -1844.0, -2128.0, -1788.0, -2001.0, -1963.0, -1772.0, -1283.0, -1949.0, -1808.0"
121,mean_openingdate_857D,float32,1421572.0,93.12,2136.0,"-1862.0, -1844.0, -1850.0, -1824.0, -1390.0, -1808.0, -1574.0, -1456.0, -1477.0, -1736.0"
122,max_amount_416A,float32,1421548.0,93.11,37816.0,"0.0, 202.008, 204.04, 204.038, 202.006, 202.01, 202.004, 1010.048, 252.744, 202.002"
123,min_amount_416A,float32,1421548.0,93.11,27777.0,"0.0, 204.04, 202.008, 202.006, 204.038, 202.01, 202.004, 252.744, 274.248, 259.182"
124,mean_amount_416A,float32,1421548.0,93.11,40640.0,"0.0, 202.008, 204.04, 204.038, 202.006, 202.01, 202.004, 252.744, 202.002, 259.182"
125,max_openingdate_313D,float32,1421548.0,93.11,2130.0,"-1862.0, -1283.0, -1788.0, -1885.0, -1660.0, -1324.0, -1197.0, -1963.0, -1390.0, -1238.0"
126,min_openingdate_313D,float32,1421548.0,93.11,2159.0,"-1862.0, -2128.0, -1963.0, -2001.0, -1844.0, -1949.0, -1283.0, -1788.0, -1808.0, -2031.0"
127,mean_openingdate_313D,float32,1421548.0,93.11,2136.0,"-1390.0, -1850.0, -1862.0, -1824.0, -1477.0, -1844.0, -1847.0, -1441.0, -1574.0, -1326.0"
128,std_annualeffectiverate_199L,float32,1412468.0,92.52,56881.0,"0.0, 0.0071, 19.799, 21.2132, 2.5809, 68.0944, 29.0057, 1.4142, 16.1658, 0.0849"
129,assignmentdate_4527235D,float32,1411681.0,92.47,8.0,"14.0, 13.0, 12.0, 11.0, 10.0, 8.0, 9.0, 7.0"
130,pmtaverage_4527227A,float32,1411681.0,92.47,30526.0,"7222.2002, 7512.0, 7223.3999, 7553.0, 7222.6001, 7221.6001, 9087.6006, 7221.8003, 7222.0, 7599.6001"
131,pmtcount_4527229L,float32,1411681.0,92.47,15.0,"6.0, 13.0, 11.0, 2.0, 1.0, 3.0, 4.0, 5.0, 7.0, 9.0"
132,std_instlamount_852A,float32,1400301.0,91.72,47885.0,"0.0, 282.8427, 230.9401, 200.0, 707.1068, 1414.2136, 848.5281, 565.6854, 1088.9445, 1598.0613"
133,datelastinstal40dpd_247D,float32,1392841.0,91.23,5124.0,"-55.0, -85.0, -89.0, -62.0, -101.0, -76.0, -92.0, -97.0, -78.0, -75.0"
134,assignmentdate_238D,float32,1389663.0,91.03,9387.0,"14.0, 13.0, 12.0, -817.0, -1121.0, -926.0, -1241.0, -2207.0, -301.0, -574.0"
135,pmtaverage_3A,float32,1383070.0,90.59,40002.0,"0.0, 7512.0, 7222.2002, 7223.3999, 7553.0, 7222.6001, 7221.6001, 9087.6006, 7222.0, 7221.8003"
136,pmtcount_693L,float32,1380253.0,90.41,39.0,"6.0, 5.0, 0.0, 7.0, 12.0, 4.0, 2.0, 3.0, 8.0, 1.0"
137,std_amount_4917619A,float32,1377449.0,90.23,129558.0,"0.0, 2358.8008, 3603.1274, 3120.3999, 4412.9121, 2818.0276, 1653.4055, 1582.1971, 1984.0867, 3231.1985"
138,max_amount_4917619A,float32,1375927.0,90.13,70970.0,"6885.0, 8100.0, 16200.0, 9720.0, 644.2, 1288.4, 7290.0, 24300.0, 11340.0, 4450.2002"
139,min_amount_4917619A,float32,1375927.0,90.13,44238.0,"6885.0, 644.2, 1288.4, 8100.0, 9720.0, 7290.0, 204.2, 16200.0, 179.8, 155.6"
140,mean_amount_4917619A,float32,1375927.0,90.13,128496.0,"6885.0, 8100.0, 644.2, 1288.4, 7290.0, 9720.0, 16200.0, 11340.0, 12960.0, 24300.0"
141,max_deductiondate_4917603D,float32,1375927.0,90.13,181.0,"7.0, 0.0, 6.0, -7.0, 8.0, 10.0, 1.0, 3.0, 9.0, -1.0"
142,min_deductiondate_4917603D,float32,1375927.0,90.13,198.0,"-161.0, -167.0, -165.0, -164.0, -162.0, -166.0, -160.0, -154.0, -158.0, -147.0"
143,mean_deductiondate_4917603D,float32,1375927.0,90.13,181.0,"-77.0, -78.0, -79.0, -76.0, -80.0, -82.0, -81.0, -74.0, -86.0, -73.0"
144,validfrom_1069D,float32,1374886.0,90.06,141.0,"13.0, 12.0, 11.0, 9.0, 7.0, 10.0, 8.0, 6.0, 14.0, 5.0"
145,contractssum_5085716L,float32,1369330.0,89.69,136172.0,"0.0, 300000.0, 1000000.0, 37490.0, 39000.0, 49990.0, 32500.0, 1185843.25, 10000.0, 62490.0"
146,max_contractsum_5085717L,float32,1369330.0,89.69,133025.0,"0.0, 1000000.0, 600000.0, 89990.0, 32500.0, 37490.0, 50000.0, 300000.0, 200000.0, 500000.0"
147,min_contractsum_5085717L,float32,1369330.0,89.69,90318.0,"0.0, 49990.0, 15000.0, 100000.0, 30000.0, 150000.0, 40000.0, 20000.0, 600000.0, 300000.0"
148,mean_contractsum_5085717L,float32,1369330.0,89.69,136633.0,"0.0, 1000000.0, 32500.0, 79980.0, 37490.0, 300000.0, 49990.0, 89990.0, 175500.0, 1776938.25"
149,avglnamtstart24m_4525187A,float32,1364150.0,89.36,57039.0,"100000.0, 20000.0, 40000.0, 60000.0, 150000.0, 23682.8008, 10920.7998, 30000.0, 21841.4004, 200000.0"

In [6]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
MONTH,152666.0,2.019363e+05,4.473666e+01,2.019010e+05,2.020100e+05
WEEK_NUM,152666.0,4.066191e+01,2.380451e+01,0.000000e+00,9.100000e+01
actualdpdtolerance_344P,111005.0,3.872798e-02,5.548453e+00,0.000000e+00,1.816000e+03
amtinstpaidbefduel24m_4187115A,96329.0,5.584494e+04,7.159737e+04,0.000000e+00,1.007363e+06
annuity_780A,152666.0,4.027584e+03,2.998589e+03,1.494000e+02,5.197300e+04
annuitynextmonth_57A,152666.0,1.440332e+03,2.819701e+03,0.000000e+00,7.092420e+04
applicationcnt_361L,152666.0,1.310049e-05,3.619449e-03,0.000000e+00,1.000000e+00
applications30d_658L,152666.0,1.397561e-01,4.885494e-01,0.000000e+00,1.900000e+01
applicationscnt_1086L,152666.0,4.187638e-01,2.732703e+00,0.000000e+00,2.580000e+02
applicationscnt_464L,152666.0,1.098660e+00,9.869553e+00,0.000000e+00,2.370000e+02
applicationscnt_629L,152666.0,2.752283e-01,2.503918e+00,0.000000e+00,7.500000e+01
applicationscnt_867L,152666.0,2.891809e+00,4.354788e+00,0.000000e+00,2.870000e+02
avgdbddpdlast24m_3658932P,91378.0,2.946519e+01,3.165395e+02,-9.230000e+02,4.750000e+03
avgdbddpdlast3m_4187120P,57873.0,2.819145e+01,3.629550e+02,-9.080000e+02,4.750000e+03
avgdbdtollast24m_4525197P,55161.0,3.052214e+01,3.233932e+02,-9.230000e+02,4.750000e+03
avgdpdtolclosure24_3658938P,105980.0,4.584877e+01,3.190652e+02,0.000000e+00,4.750000e+03
avginstallast24m_3658937A,90219.0,5.401423e+03,6.526974e+03,8.000000e-01,2.530110e+05
avglnamtstart24m_4525187A,16328.0,4.489401e+04,4.479809e+04,0.000000e+00,4.000000e+05
avgmaxdpdlast9m_3716943P,76975.0,7.551543e-01,4.905804e+00,0.000000e+00,2.130000e+02
avgoutstandbalancel6m_4187114A,68515.0,4.579339e+04,6.955863e+04,-7.588198e+06,1.128721e+06
avgpmtlast12m_4525200A,49767.0,6.399235e+03,9.326447e+03,0.000000e+00,4.959104e+05
clientscnt12m_3712952L,152666.0,3.602636e-02,7.385402e-01,0.000000e+00,1.980000e+02
clientscnt3m_3712950L,152666.0,1.682759e-02,5.175325e-01,0.000000e+00,1.090000e+02
clientscnt6m_3712949L,152666.0,2.468788e-02,6.490873e-01,0.000000e+00,1.540000e+02
clientscnt_100L,152666.0,4.943471e-02,3.385311e-01,0.000000e+00,6.800000e+01
clientscnt_1022L,152666.0,1.052428e-01,1.172078e+00,0.000000e+00,2.660000e+02
clientscnt_1071L,152666.0,3.405473e-02,1.885594e-01,0.000000e+00,4.000000e+00
clientscnt_1130L,152666.0,3.150014e-02,2.409535e-01,0.000000e+00,3.100000e+01
clientscnt_157L,152666.0,8.008332e-02,1.191788e+00,0.000000e+00,3.900000e+02
clientscnt_257L,152666.0,3.111367e-03,5.878284e-02,0.000000e+00,4.000000e+00
clientscnt_304L,152666.0,7.717501e-02,7.847026e-01,0.000000e+00,2.180000e+02
clientscnt_360L,152666.0,3.019664e-03,5.639923e-02,0.000000e+00,3.000000e+00
clientscnt_493L,152666.0,1.577955e-02,1.614526e+00,0.000000e+00,6.070000e+02
clientscnt_533L,152666.0,7.612697e-02,2.833755e-01,0.000000e+00,4.000000e+00
clientscnt_887L,152666.0,2.368962e+00,3.842991e+01,0.000000e+00,1.239000e+03
clientscnt_946L,152666.0,3.269883e-02,3.082376e-01,0.000000e+00,7.200000e+01
cntincpaycont9m_3716944L,107125.0,6.210268e+00,6.472365e+00,0.000000e+00,5.750000e+02
cntpmts24_3658933L,106597.0,1.061960e+01,7.893691e+00,0.000000e+00,2.500000e+01
credamount_770A,152666.0,4.968111e+04,4.410052e+04,2.000000e+03,9.500000e+05
currdebt_22A,152666.0,1.963641e+04,5.088664e+04,0.000000e+00,1.071761e+06
currdebtcredtyperange_828A,152666.0,1.098399e+04,3.701424e+04,0.000000e+00,8.483403e+05
datefirstoffer_1144D,69418.0,-2.468842e+03,1.618363e+03,-4.902000e+03,1.300000e+01
datelastinstal40dpd_247D,13432.0,-1.967198e+03,1.555641e+03,-5.203000e+03,-2.600000e+01
datelastunpaid_3546854D,63892.0,-9.568522e+02,1.245200e+03,-5.305000e+03,1.300000e+01
daysoverduetolerancedd_3976961L,107408.0,9.514148e+01,4.738825e+02,0.000000e+00,5.337000e+03
disbursedcredamount_1113A,152666.0,4.591377e+04,4.242284e+04,0.000000e+00,9.500000e+05
downpmt_116A,152666.0,5.649736e+02,4.171558e+03,0.000000e+00,3.334424e+05
dtlastpmtallstes_4499206D,54681.0,-4.142051e+02,8.445734e+02,-5.179000e+03,1.300000e+01
eir_270L,133517.0,2.775801e-01,1.975556e-01,0.000000e+00,4.500000e-01
firstclxcampaign_1125D,66824.0,-9.916399e+02,4.637777e+02,-1.709000e+03,1.400000e+01
firstdatedue_489D,104560.0,-1.839024e+03,1.454174e+03,-5.347000e+03,4.600000e+01
homephncnt_628L,152666.0,6.387146e-01,8.469911e-01,0.000000e+00,8.000000e+00
inittransactionamount_650A,19318.0,3.245524e+04,3.332551e+04,0.000000e+00,2.000000e+05
isbidproduct_1095L,152666.0,1.148520e-01,3.188443e-01,0.000000e+00,1.000000e+00
lastactivateddate_801D,107333.0,-6.303986e+02,9.101848e+02,-5.352000e+03,1.400000e+01
lastapplicationdate_877D,122303.0,-4.692690e+02,7.481902e+02,-5.354000e+03,1.400000e+01
lastapprcredamount_781A,108505.0,3.669433e+04,3.678962e+04,0.000000e+00,4.000000e+05
lastapprdate_640D,108505.0,-6.099551e+02,8.930970e+02,-5.354000e+03,1.400000e+01
lastdelinqdate_224D,54936.0,-5.370913e+02,6.481023e+02,-4.863000e+03,1.300000e+01
lastrejectcredamount_222A,75909.0,5.072662e+04,5.289252e+04,0.000000e+00,9.500000e+05
lastrejectdate_50D,75909.0,-8.351287e+02,1.010465e+03,-5.311000e+03,1.400000e+01
maininc_215A,101654.0,4.941495e+04,3.224594e+04,0.000000e+00,2.000000e+05
maxannuity_159A,122112.0,3.460714e+04,9.161409e+04,0.000000e+00,7.988198e+06
maxdbddpdlast1m_3658939P,56589.0,4.142255e+01,4.485033e+02,-1.237000e+03,4.804000e+03
maxdbddpdtollast12m_3658940P,82076.0,5.046243e+01,4.132226e+02,-1.083000e+03,4.804000e+03
maxdbddpdtollast6m_4187119P,64988.0,4.682343e+01,4.251563e+02,-1.225000e+03,4.804000e+03
maxdebt4_972A,122112.0,4.821325e+04,5.327488e+04,0.000000e+00,1.740000e+06
maxdpdfrom6mto36m_3546853P,118357.0,3.215537e+01,2.431571e+02,0.000000e+00,4.453000e+03
maxdpdinstldate_3546855D,70113.0,-1.007250e+03,1.211768e+03,-5.248000e+03,1.300000e+01
maxdpdinstlnum_3546846P,69769.0,8.248277e+00,5.984638e+00,0.000000e+00,9.100000e+01
maxdpdlast12m_727P,122112.0,1.589207e+01,1.845202e+02,0.000000e+00,4.619000e+03
maxdpdlast24m_143P,122112.0,2.589470e+01,2.257195e+02,0.000000e+00,4.619000e+03
maxdpdlast3m_392P,122112.0,5.972198e+00,1.269004e+02,0.000000e+00,4.619000e+03
maxdpdlast6m_474P,122112.0,9.579386e+00,1.512736e+02,0.000000e+00,4.619000e+03
maxdpdlast9m_1059P,122112.0,1.286412e+01,1.691917e+02,0.000000e+00,4.619000e+03
maxdpdtolerance_374P,122112.0,5.339856e+01,2.821099e+02,0.000000e+00,4.619000e+03
maxinstallast24m_3658928A,90219.0,1.527476e+04,2.506935e+04,8.000000e-01,4.959104e+05
maxlnamtstart6m_4525199A,49181.0,4.468932e+04,3.796985e+04,0.000000e+00,5.186296e+05
maxoutstandbalancel12m_4187113A,75734.0,7.122180e+04,8.607161e+04,-7.588198e+06,1.175381e+06
maxpmtlast3m_4525190A,39722.0,9.966470e+03,1.844667e+04,0.000000e+00,3.361747e+05
mindbddpdlast24m_3658935P,91378.0,-4.097485e-01,3.049178e+02,-1.280000e+03,4.696000e+03
mindbdtollast24m_4525191P,55161.0,-7.456536e-01,3.105948e+02,-1.280000e+03,4.696000e+03
mobilephncnt_593L,152666.0,1.776676e+00,1.145705e+00,0.000000e+00,2.300000e+01
monthsannuity_845L,107409.0,2.586500e+01,2.300482e+01,0.000000e+00,1.620000e+02
numactivecreds_622L,152666.0,4.724038e-01,7.103496e-01,0.000000e+00,7.000000e+00
numactivecredschannel_414L,152666.0,1.017908e-01,3.250497e-01,0.000000e+00,3.000000e+00
numactiverelcontr_750L,152666.0,2.443046e-01,4.735923e-01,0.000000e+00,6.000000e+00
numcontrs3months_479L,152666.0,2.740165e-01,7.838396e-01,0.000000e+00,3.100000e+01
numincomingpmts_3546848L,107141.0,3.251329e+01,3.312103e+01,0.000000e+00,6.740000e+02
numinstlallpaidearly3d_817L,108120.0,2.070684e+01,2.583793e+01,0.000000e+00,2.970000e+02
numinstls_657L,152666.0,7.703922e+00,1.548257e+01,0.000000e+00,3.110000e+02
numinstlsallpaid_934L,108120.0,2.738602e+01,2.993947e+01,0.000000e+00,3.130000e+02
numinstlswithdpd10_728L,106995.0,3.594205e+00,1.118401e+01,0.000000e+00,2.790000e+02
numinstlswithdpd5_4187116L,96329.0,2.249904e+00,4.831892e+00,0.000000e+00,7.500000e+01
numinstlswithoutdpd_562L,106995.0,3.176403e+01,3.290203e+01,0.000000e+00,5.570000e+02
numinstmatpaidtearly2d_4499204L,67696.0,2.284743e+01,2.756731e+01,0.000000e+00,3.030000e+02
numinstpaid_4499208L,67696.0,3.363462e+01,3.418906e+01,0.000000e+00,3.280000e+02
numinstpaidearly3d_3546850L,107998.0,1.996141e+01,2.490037e+01,0.000000e+00,2.860000e+02
numinstpaidearly3dest_4493216L,68350.0,2.059147e+01,2.558613e+01,0.000000e+00,2.860000e+02
numinstpaidearly5d_1087L,107409.0,4.605191e+00,8.907061e+00,0.000000e+00,2.150000e+02
numinstpaidearly5dest_4493211L,68350.0,3.253197e+00,4.456628e+00,0.000000e+00,4.800000e+01
numinstpaidearly5dobd_4499205L,67696.0,1.661206e+01,2.264626e+01,0.000000e+00,2.700000e+02
numinstpaidearly_338L,107409.0,1.624874e+01,2.210822e+01,0.000000e+00,2.700000e+02
numinstpaidearlyest_4493214L,68350.0,1.661865e+01,2.264393e+01,0.000000e+00,2.700000e+02
numinstpaidlastcontr_4325080L,85429.0,7.717637e+00,6.116023e+00,0.000000e+00,7.300000e+01
numinstpaidlate1d_3546852L,107409.0,5.493562e+00,8.686556e+00,0.000000e+00,1.110000e+02
numinstregularpaid_973L,107114.0,3.009341e+01,3.243634e+01,0.000000e+00,3.280000e+02
numinstregularpaidest_4493210L,68350.0,3.364492e+01,3.419901e+01,0.000000e+00,3.280000e+02
numinsttopaygr_769L,107408.0,5.952443e+00,1.018693e+01,0.000000e+00,1.170000e+02
numinsttopaygrest_4493213L,68350.0,5.859517e+00,1.024797e+01,0.000000e+00,1.170000e+02
numinstunpaidmax_3546851L,107408.0,5.398983e+00,8.900146e+00,0.000000e+00,6.000000e+01
numinstunpaidmaxest_4493212L,68350.0,5.300102e+00,8.894238e+00,0.000000e+00,6.000000e+01
numnotactivated_1143L,152666.0,2.171407e-02,1.582876e-01,0.000000e+00,4.000000e+00
numpmtchanneldd_318L,152666.0,2.459618e-02,1.621233e-01,0.000000e+00,3.000000e+00
numrejects9m_859L,152666.0,3.741108e-01,1.260951e+00,0.000000e+00,1.030000e+02
pctinstlsallpaidearl3d_427L,106803.0,5.998843e-01,3.499741e-01,0.000000e+00,1.000000e+01
pctinstlsallpaidlat10d_839L,106533.0,8.034264e-02,1.625948e-01,0.000000e+00,1.000000e+00
pctinstlsallpaidlate1d_3546856L,106803.0,1.783906e-01,2.292913e-01,0.000000e+00,1.000000e+00
pctinstlsallpaidlate4d_3546849L,106694.0,1.145834e-01,1.916301e-01,0.000000e+00,2.000000e+00
pctinstlsallpaidlate6d_3546844L,106667.0,9.800258e-02,1.784689e-01,0.000000e+00,1.000000e+00
pmtnum_254L,148176.0,1.704296e+01,9.781550e+00,3.000000e+00,6.000000e+01
posfpd10lastmonth_333P,144844.0,1.603104e-02,1.255952e-01,0.000000e+00,1.000000e+00
posfpd30lastmonth_3976960P,139459.0,7.909135e-03,8.858124e-02,0.000000e+00,1.000000e+00
posfstqpd30lastmonth_3976962P,134533.0,3.028997e-02,1.713847e-01,0.000000e+00,1.000000e+00
price_1097A,130179.0,3.437534e+04,3.442223e+04,0.000000e+00,5.555692e+05
sellerplacecnt_915L,152666.0,1.646994e-01,4.529462e-01,0.000000e+00,6.000000e+00
sellerplacescnt_216L,152666.0,1.618972e+00,2.066379e+00,0.000000e+00,1.020000e+02
sumoutstandtotal_3546847A,108182.0,2.761006e+04,5.848564e+04,0.000000e+00,1.071761e+06
sumoutstandtotalest_4493215A,68350.0,2.833406e+04,6.080223e+04,0.000000e+00,1.071761e+06
totaldebt_9A,152666.0,1.963729e+04,5.088801e+04,0.000000e+00,1.071761e+06
totalsettled_863A,152666.0,9.212859e+04,1.509595e+05,0.000000e+00,1.023130e+07
totinstallast1m_4525188A,35152.0,1.030685e+04,1.557979e+04,3.820000e-01,4.041089e+05
validfrom_1069D,15137.0,-1.777195e+01,2.925252e+01,-1.180000e+02,1.400000e+01
assignmentdate_238D,13592.0,-2.354713e+03,2.305880e+03,-1.257900e+04,1.400000e+01
assignmentdate_4527235D,11490.0,1.394796e+01,3.831780e-01,7.000000e+00,1.400000e+01
birthdate_574D,61175.0,-1.604878e+04,5.097893e+03,-2.774600e+04,-7.657000e+03
contractssum_5085716L,15620.0,6.308546e+05,9.649614e+05,0.000000e+00,1.973140e+07
dateofbirth_337D,138507.0,-1.628049e+04,5.048509e+03,-3.840300e+04,-2.919000e+03
days120_123L,138507.0,1.601414e+00,2.075545e+00,0.000000e+00,3.200000e+01
days180_256L,138507.0,2.379981e+00,2.885569e+00,0.000000e+00,4.800000e+01
days30_165L,138507.0,5.174685e-01,9.011009e-01,0.000000e+00,1.400000e+01
days360_512L,138507.0,4.764070e+00,5.152192e+00,0.000000e+00,7.400000e+01
days90_310L,138507.0,1.205477e+00,1.648151e+00,0.000000e+00,2.500000e+01
firstquarter_103L,138507.0,2.846556e+00,3.577250e+00,0.000000e+00,5.000000e+01
fourthquarter_440L,138507.0,2.843012e+00,3.419011e+00,0.000000e+00,4.500000e+01
pmtaverage_3A,14249.0,9.297528e+03,5.464841e+03,0.000000e+00,7.919753e+04
pmtaverage_4527227A,11490.0,9.954724e+03,5.222983e+03,2.160000e+01,8.745940e+04
pmtcount_4527229L,11490.0,6.606353e+00,2.204264e+00,1.000000e+00,1.300000e+01
pmtcount_693L,14535.0,5.712487e+00,1.743562e+00,0.000000e+00,4.800000e+01
pmtscount_423L,57690.0,5.838187e+00,4.147509e+00,0.000000e+00,6.300000e+01
pmtssum_45A,57690.0,1.317285e+04,1.813980e+04,0.000000e+00,4.010346e+05
responsedate_1012D,72312.0,1.375223e+01,1.414280e+00,-3.000000e+00,1.400000e+01
responsedate_4527233D,65766.0,1.395738e+01,3.697185e-01,7.000000e+00,1.400000e+01
responsedate_4917613D,22392.0,1.356717e+01,1.855614e+00,-5.000000e+00,1.400000e+01
secondquarter_766L,138507.0,2.682110e+00,3.313569e+00,0.000000e+00,4.500000e+01
thirdquarter_1082L,138507.0,2.907016e+00,3.403971e+00,0.000000e+00,4.700000e+01
max_actualdpd_943P,122301.0,3.494656e-02,5.285759e+00,0.000000e+00,1.816000e+03
min_actualdpd_943P,122301.0,1.030245e-03,1.096292e-01,0.000000e+00,1.800000e+01
mean_actualdpd_943P,122301.0,7.666056e-03,1.063225e+00,0.000000e+00,3.632000e+02
std_actualdpd_943P,99146.0,1.782792e-02,2.615697e+00,0.000000e+00,8.121399e+02
max_annuity_853A,121932.0,5.659302e+03,4.122896e+03,0.000000e+00,8.282740e+04
min_annuity_853A,121932.0,1.705011e+03,1.923661e+03,0.000000e+00,6.000360e+04
mean_annuity_853A,121932.0,3.373062e+03,2.094509e+03,0.000000e+00,6.000360e+04
std_annuity_853A,98261.0,2.008167e+03,1.702501e+03,0.000000e+00,4.645494e+04
max_byoccupationinc_3656910L,56575.0,2.706755e+04,3.718959e+04,0.000000e+00,2.000000e+05
min_byoccupationinc_3656910L,56575.0,1.022589e+04,2.201555e+04,0.000000e+00,2.000000e+05
mean_byoccupationinc_3656910L,56575.0,1.756740e+04,2.478389e+04,0.000000e+00,2.000000e+05
std_byoccupationinc_3656910L,33997.0,1.432744e+04,1.983351e+04,0.000000e+00,1.414214e+05
max_childnum_21L,97504.0,1.328438e+00,1.487636e+00,0.000000e+00,1.800000e+01
min_childnum_21L,97504.0,7.105760e-01,1.130567e+00,0.000000e+00,1.800000e+01
mean_childnum_21L,97504.0,9.645142e-01,1.151212e+00,0.000000e+00,1.800000e+01
std_childnum_21L,58992.0,5.180259e-01,7.243134e-01,0.000000e+00,8.049845e+00
max_credacc_actualbalance_314A,25180.0,1.998735e+04,2.715572e+04,-4.917854e+04,4.280262e+05
min_credacc_actualbalance_314A,25180.0,1.687580e+04,2.480199e+04,-4.917854e+04,4.000000e+05
mean_credacc_actualbalance_314A,25180.0,1.837312e+04,2.512239e+04,-4.917854e+04,4.000000e+05
max_credacc_credlmt_575A,122059.0,1.040033e+04,2.604000e+04,0.000000e+00,4.000000e+05
min_credacc_credlmt_575A,122059.0,1.394833e+03,8.998101e+03,0.000000e+00,4.000000e+05
mean_credacc_credlmt_575A,122059.0,4.028003e+03,1.195815e+04,0.000000e+00,4.000000e+05
std_credacc_credlmt_575A,98653.0,5.048568e+03,1.252344e+04,0.000000e+00,2.828427e+05
max_credacc_maxhisbal_375A,25180.0,-2.173690e+03,5.624506e+04,-1.987620e+05,7.988198e+06
min_credacc_maxhisbal_375A,25180.0,-3.720524e+03,5.517273e+04,-1.987620e+05,7.988198e+06
mean_credacc_maxhisbal_375A,25180.0,-2.937897e+03,5.518478e+04,-1.987620e+05,7.988198e+06
max_credacc_minhisbal_90A,25180.0,-5.991106e+03,1.729871e+04,-2.000000e+05,8.681400e+04
min_credacc_minhisbal_90A,25180.0,-7.439331e+03,1.915870e+04,-2.033012e+05,7.585400e+04
mean_credacc_minhisbal_90A,25180.0,-6.670687e+03,1.759503e+04,-2.000000e+05,7.585400e+04
max_credacc_transactions_402L,25180.0,6.087371e-01,3.300541e+00,0.000000e+00,1.260000e+02
min_credacc_transactions_402L,25180.0,4.186259e-01,2.514537e+00,0.000000e+00,1.190000e+02
mean_credacc_transactions_402L,25180.0,5.049679e-01,2.695782e+00,0.000000e+00,1.190000e+02
max_credamount_590A,122059.0,7.150730e+04,5.888276e+04,0.000000e+00,1.000000e+06
min_credamount_590A,122059.0,1.757521e+04,2.106873e+04,0.000000e+00,4.000000e+05
mean_credamount_590A,122059.0,3.798949e+04,2.625681e+04,0.000000e+00,4.000000e+05
std_credamount_590A,98618.0,2.721217e+04,2.346775e+04,0.000000e+00,4.625479e+05
max_currdebt_94A,110916.0,1.855464e+04,3.463950e+04,0.000000e+00,4.907186e+05
min_currdebt_94A,110916.0,2.007202e+03,1.036692e+04,0.000000e+00,3.399964e+05
mean_currdebt_94A,110916.0,6.184009e+03,1.339108e+04,0.000000e+00,3.399964e+05
std_currdebt_94A,82644.0,1.037405e+04,1.766283e+04,0.000000e+00,2.828427e+05
max_downpmt_134A,122059.0,1.694182e+03,5.395922e+03,0.000000e+00,3.052000e+05
min_downpmt_134A,122059.0,1.688192e+02,1.851447e+03,0.000000e+00,1.340000e+05
mean_downpmt_134A,122059.0,5.492044e+02,2.412145e+03,0.000000e+00,1.526000e+05
std_downpmt_134A,98618.0,8.337653e+02,2.656162e+03,0.000000e+00,2.158090e+05
mean_isbidproduct_390L,122303.0,4.004133e-02,9.689596e-02,0.000000e+00,8.333333e-01
std_isbidproduct_390L,99182.0,1.011530e-01,1.852281e-01,0.000000e+00,7.071068e-01
mean_isdebitcard_527L,34224.0,2.202119e-01,3.950256e-01,0.000000e+00,1.000000e+00
std_isdebitcard_527L,8065.0,1.823712e-01,2.932898e-01,0.000000e+00,7.071068e-01
max_mainoccupationinc_437A,122178.0,6.454368e+04,3.999823e+04,0.000000e+00,1.996000e+05
min_mainoccupationinc_437A,122178.0,2.460094e+04,2.230085e+04,0.000000e+00,1.996000e+05
mean_mainoccupationinc_437A,122178.0,4.134520e+04,2.366904e+04,0.000000e+00,1.996000e+05
std_mainoccupationinc_437A,98795.0,2.067228e+04,1.611148e+04,0.000000e+00,1.368959e+05
max_maxdpdtolerance_577P,107577.0,4.268909e+01,2.542034e+02,0.000000e+00,4.079000e+03
min_maxdpdtolerance_577P,107577.0,1.463707e+01,1.684760e+02,0.000000e+00,4.062000e+03
mean_maxdpdtolerance_577P,107577.0,2.525992e+01,1.866066e+02,0.000000e+00,4.062000e+03
std_maxdpdtolerance_577P,76763.0,2.266246e+01,1.403474e+02,0.000000e+00,2.774687e+03
max_outstandingdebt_522A,110791.0,2.494393e+04,5.358007e+04,0.000000e+00,1.071761e+06
min_outstandingdebt_522A,110791.0,2.398840e+03,1.360491e+04,0.000000e+00,5.718206e+05
mean_outstandingdebt_522A,110791.0,7.926258e+03,1.867925e+04,0.000000e+00,5.718206e+05
std_outstandingdebt_522A,82497.0,1.396610e+04,2.710089e+04,0.000000e+00,5.877333e+05
max_pmtnum_8L,120692.0,2.299894e+01,1.284145e+01,3.000000e+00,6.300000e+01
min_pmtnum_8L,120692.0,8.938497e+00,6.441912e+00,3.000000e+00,6.000000e+01
mean_pmtnum_8L,120692.0,1.498036e+01,7.308244e+00,3.000000e+00,6.000000e+01
std_pmtnum_8L,96117.0,7.450348e+00,4.879150e+00,0.000000e+00,4.030509e+01
max_revolvingaccount_394A,25181.0,7.528214e+08,5.145561e+07,5.403425e+08,8.006067e+08
min_revolvingaccount_394A,25181.0,7.464143e+08,5.604708e+07,5.403425e+08,8.006067e+08
mean_revolvingaccount_394A,25181.0,7.496995e+08,5.203558e+07,5.403425e+08,8.006067e+08
n_unique_cancelreason_3545846M,122303.0,1.770104e+00,9.350067e-01,1.000000e+00,8.000000e+00
n_unique_credacc_status_367L,122303.0,1.206618e+00,4.412905e-01,1.000000e+00,4.000000e+00
n_unique_credtype_587L,122303.0,1.814559e+00,8.191936e-01,1.000000e+00,4.000000e+00
n_unique_district_544M,122303.0,1.389851e+00,6.134439e-01,1.000000e+00,7.000000e+00
n_unique_education_1138M,122303.0,1.823684e+00,6.268791e-01,1.000000e+00,5.000000e+00
n_unique_familystate_726L,122303.0,1.826676e+00,7.287621e-01,1.000000e+00,6.000000e+00
n_unique_inittransactioncode_279L,122303.0,1.708862e+00,7.811937e-01,1.000000e+00,4.000000e+00
n_unique_postype_4733339M,122303.0,1.449114e+00,8.841731e-01,1.000000e+00,7.000000e+00
n_unique_profession_152M,122303.0,1.055502e+00,2.497281e-01,1.000000e+00,7.000000e+00
n_unique_rejectreason_755M,122303.0,1.741135e+00,9.403056e-01,1.000000e+00,7.000000e+00
n_unique_rejectreasonclient_4145042M,122303.0,1.471599e+00,6.418384e-01,1.000000e+00,6.000000e+00
n_unique_status_219L,122303.0,2.143750e+00,9.754544e-01,1.000000e+00,5.000000e+00
max_approvaldate_319D,108409.0,-6.096311e+02,8.927628e+02,-5.354000e+03,1.400000e+01
min_approvaldate_319D,108409.0,-1.803857e+03,1.432745e+03,-5.378000e+03,1.400000e+01
mean_approvaldate_319D,108409.0,-1.151894e+03,9.693251e+02,-5.354000e+03,1.400000e+01
min_creationdate_885D,122303.0,-1.916626e+03,1.437387e+03,-5.378000e+03,1.400000e+01
mean_creationdate_885D,122303.0,-1.113940e+03,8.826965e+02,-5.354000e+03,1.400000e+01

In [7]:
# Categorical Feature Statistics
cat_stats

                                                              value   count  \
column                                rank
cardtype_51L                          1                        <NA>  133419
                                      2                     INSTANT   19016
                                      3                PERSONALIZED     231
credtype_322L                         1                         COL   98735
                                      2                         CAL   34612
                                      3                         REL   19318
                                      4                        <NA>       1
date_decision                         1         2019-11-29 00:00:00     838
                                      2         2019-11-30 00:00:00     807
                                      3         2019-12-29 00:00:00     690
                                      4         2019-12-28 00:00:00     679
                                      5         2019-11-16 00:00:00     618
description_5085714M                  1                    a55475b1  131729
                                      2                    2fc785b2   18320
                                      3                        <NA>    2617
disbursementtype_67L                  1                         SBA  113868
                                      2                         GBA   34613
                                      3                          DD    4089
                                      4                        <NA>      96
education_1103M                       1                    a55475b1   85978
                                      2                    6b2ae0fa   45225
                                      3                    717ddd49   13443
                                      4                    39a0853f    4805
                                      5                        <NA>    2617
education_88M                         1                    a55475b1  148471
                                      2                        <NA>    2617
                                      3                    6b2ae0fa    1185
                                      4                    717ddd49     334
                                      5                    a34a13c8      46
equalitydataagreement_891L            1                        <NA>  144743
                                      2                        True    7379
                                      3                       False     544
first_cancelreason_3545846M           1                    a55475b1   76662
                                      2                        <NA>   30363
                                      3                 P94_109_143   30053
                                      4                   P30_86_84    2170
                                      5                 P85_114_140    2136
first_classificationofcontr_13M       1                    ea6782cc  115839
                                      2                        <NA>   14102
                                      3                    a55475b1   12221
                                      4                    01f63ac8    6322
                                      5                    00135d9c    2301
first_classificationofcontr_400M      1                    ea6782cc   51991
                                      2                    a55475b1   37503
                                      3                        <NA>   14102
                                      4                    01f63ac8    6874
                                      5                    42a42e75    5779
first_collater_typofvalofguarant_298M 1                    9a0c095e   98392
                                      2                    8fd95e4b   27848
                                      3                        <NA>   14195
                                      4                    a55475b1   12186
                                      5                    06fb9ba8      45
first_collater_typofvalofguarant_407M 1                    9a0c095e   66836
                                      2                    a55475b1   39197
                                      3                    8fd95e4b   32179
                                      4                        <NA>   14195
                                      5                    06fb9ba8     236
first_collaterals_typeofguarante_359M 1                    c7a5ad39   68770
                                      2                    a55475b1   39197
                                      3                    3cbe86ba   20933
                                      4                        <NA>   14195
                                      5                    9276e4bb    2846
first_collaterals_typeofguarante_669M 1                    c7a5ad39  118694
                                      2                        <NA>   14195
                                      3                    a55475b1   12188
                                      4                    9276e4bb    2670
                                      5                    0e63c0f0    1769
first_contaddr_district_15M           1                 P131_33_167    8161
                                      2                 P197_47_166    7816
                                      3                   P123_6_84    5567
                                      4                 P98_137_111    4293
                                      5                P159_143_123    3591
first_contaddr_zipcode_807M           1                 P161_14_174    9897
                                      2                P144_138_111    9127
                                      3                 P46_103_143    5537
                                      4                  P91_47_168    5361
                                      5                 P62_116_179    3449
first_contractst_545M                 1                    7241344e  122411
                                      2                        <NA>   14102
                                      3                    a55475b1   12311
                                      4                    8f3a197f    1008
                                      5                    0dc85f9d     798
first_contractst_964M                 1                    7241344e   90494
                                      2                    a55475b1   37327
                                      3                        <NA>   14102
                                      4                    8f3a197f    3486
                                      5                    d7416962    1294
first_credtype_587L                   1                         COL   65975
                                      2                         CAL   36937
                                      3                        <NA>   33214
                                      4                         REL   16540
first_description_351M                1                    a55475b1  135246
                                      2                        <NA>   14102
                                      3                    95decc86     826
                                      4                    6da7c7ed     612
                                      5                    53179c19     600
first_district_544M                   1                        <NA>   30363
                                      2                    a55475b1   14264
                                      3                 P131_33_167    6421
                                      4                 P197_47_166    5253
                                      5                   P123_6_84    4317
first_education_1138M                 1                    a55475b1   80142
                                      2                        <NA>   30363
                                      3                  P97_36_170   25350
                                      4                 P33_146_175   15745
                                      5                 P106_81_188     704
first_education_927M                  1                    a55475b1   79870
                                      2                  P97_36_170   41161
                                      3                 P33_146_175   25678
                                      4                 P106_81_188    5341
                                      5                  P17_36_170     555
first_empl_employedtotal_800L         1                        <NA>   99828
                                      2                   MORE_FIVE   37193
                                      3                    MORE_ONE   12651
                                      4                    LESS_ONE    2994
first_empl_industry_691L              1                        <NA>  100453
                                      2                       OTHER   38581
                                      3                  GOVERNMENT    3599
                                      4                   EDUCATION    3059
                                      5                       TRADE    2136
first_empladdr_district_926M          1                    a55475b1  100124
                                      2                 P197_47_166    5713
                                      3                 P131_33_167    4251
                                      4                 P62_144_102    2117
                                      5                 P98_137_111    2033
first_empladdr_zipcode_114M           1                    a55475b1  100118
                                      2                P144_138_111    6104
                                      3                 P161_14_174    4559
                                      4                  P91_47_168    2214
                                      5                    P8_88_79    1934
first_familystate_447L                1                        <NA>   79870
                                      2                     MARRIED   48553
                                      3                      SINGLE   18143
                                      4                     WIDOWED    3436
                                      5                    DIVORCED    1897
first_familystate_726L                1                        <NA>  102447
                                      2                     MARRIED   36630
                                      3                      SINGLE    8868
                                      4                     WIDOWED    2629
                                      5                    DIVORCED    1408
first_financialinstitution_382M       1                    a55475b1   37324
                                      2                 Home Credit   25202
                                      3                  P40_52_135   15115
                                      4                    b619fa46   14961
                                      5                        <NA>   14102
first_financialinstitution_591M       1                  P204_66_73   53945
                                      2                 Home Credit   20958
                                      3                    b619fa46   19364
                                      4                        <NA>   14102
                                      5                    a55475b1   12199
first_housetype_905L                  1                        <NA>  142770
                                      2                       OWNED    9234
                                      3                    PARENTAL     402
                                      4                        FLAT     145
                                      5                COMPANY_FLAT      77
first_incometype_1044T                1     PRIVATE_SECTOR_EMPLOYEE   49148
                                      2               SALARIED_GOVT   37395
                                      3           RETIRED_PENSIONER   31054
                                      4                    EMPLOYED   29829
                                      5                SELFEMPLOYED    2875
first_inittransactioncode_279L        1                         POS   73910
                                      2                        CASH   36944
                                      3                        <NA>   33214
                                      4                         NDF    8598
first_language1_981M                  1                  P10_39_147   84788
                                      2                P209_127_106   62154
                                      3                    a55475b1    5724
first_postype_4733339M                1                    a55475b1   76189
                                      2                        <NA>   30363
                                      3                P177_117_192   22835
                                      4                  P46_145_78   10394
                                      5                 P149_40_170    4920
first_profession_152M                 1                    a55475b1  121756
                                      2                        <NA>   30363
                                      3                   P46_72_80      12
                                      4                  P203_66_70      11
                                      5                  P10_42_172      11
first_purposeofcred_426M              1                    60c73645  103363
                                      2                    96a8fdfe   21844
                                      3                        <NA>   14102
                                      4                    a55475b1   12199
                                      5                    9e302002     374
first_purposeofcred_874M              1                    5065c2b8   45978
                                      2                    60c73645   37535
                                      3                    a55475b1   37337
                                      4                        <NA>   14102
                                      5                    96a8fdfe    9820
first_registaddr_district_1083M       1                 P131_33_167    8126
                                      2                 P197_47_166    7035
                                      3                   P123_6_84    5577
                                      4                 P98_137_111    4307
                                      5                P159_143_123    3628
first_registaddr_zipcode_184M         1                 P161_14_174    9803
                                      2                P144_138_111    8188
                                      3                    a55475b1    6851
                                      4                 P46_103_143    5478
                                      5                  P91_47_168    5377
first_rejectreason_755M               1                    a55475b1   84551
                                      2                        <NA>   30363
                                      3                  P99_56_166   17363
                                      4                 P94_109_143    9905
                                      5                  P45_84_106    4993
first_rejectreasonclient_4145042M     1                    a55475b1   90057
                                      2                        <NA>   30363
                                      3                 P94_109_143   27881
                                      4                   P30_86_84    2053
                                      5                   P52_67_90     769
first_role_1084L                      1                          CL  127951
                                      2                          EM   24715
first_sex_738L                        1                           F   95282
                                      2                           M   57384
first_status_219L                     1                           D   38801
                                      2                           A   37241
                                      3                           K   32292
                                      4                        <NA>   30363
                                      5                           T   11269
first_subjectrole_182M                1                    ab3c25cf  125814
                                      2                        <NA>   14102
                                      3                    a55475b1   12199
                                      4                    be4fd70b     264
                                      5                    daf49a8a     225
first_subjectrole_93M                 1                    ab3c25cf  122742
                                      2                    a55475b1   15614
                                      3                        <NA>   14102
                                      4                    daf49a8a      90
                                      5                    be4fd70b      82
first_subjectroles_name_541M          1                    ab3c25cf   98384
                                      2                    a55475b1   38585
                                      3                        <NA>   14195
                                      4                    15f04f45    1019
                                      5                    daf49a8a     309
first_subjectroles_name_838M          1                    ab3c25cf  122925
                                      2                        <NA>   14195
                                      3                    a55475b1   13574
                                      4                    be4fd70b     644
                                      5                    daf49a8a     576
first_type_25L                        1              PRIMARY_MOBILE  150283
                                      2                  HOME_PHONE    1897
                                      3                       PHONE     293
                                      4            SECONDARY_MOBILE     190
                                      5               PRIMARY_EMAIL       3
inittransactioncode_186L              1                         POS  113910
                                      2                        CASH   34612
                                      3                         NDF    4143
                                      4                        <NA>       1
last_cancelreason_3545846M            1                    a55475b1  103818
                                      2                        <NA>   30363
                                      3                 P94_109_143   13153
                                      4                 P73_130_169     913
                                      5                 P85_114_140     856
last_classificationofcontr_13M        1                    a55475b1  138564
                                      2                        <NA>   14102
                                      3                    01f63ac8       0
                                      4                    ea6782cc       0
last_classificationofcontr_400M       1                    a55475b1  137420
                                      2                        <NA>   14102
                                      3                    ea6782cc     848
                                      4                    01f63ac8     197
                                      5                    00135d9c      83
last_collater_typofvalofguarant_298M  1                    a55475b1  138461
                                      2                        <NA>   14195

In [8]:
# Target Distribution
target_df

          count    pct
target
0       1478665  96.86
1         47994   3.14

## Task Curation

In [9]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import subsample_temporal

split_time = pd.Timestamp("2020-05-01")
# Test: all data from 2020-05-01 onwards
test_idx = df.index[
    df["date_decision"] >= split_time
].to_numpy().tolist()

# Train: all data before that
train_idx = df.index[
    df["date_decision"] < split_time
].to_numpy().tolist()

df, train_idx, test_idx = subsample_temporal(
    df=df,
    train_idx=train_idx,
    test_idx=test_idx,
    stratify_on=task_mold.stratify_on,
)

# Size and class distribution checks
print("Train size:", len(train_idx), " | Test size:", len(test_idx))
print("Train target distribution:\n", df.loc[train_idx, task_mold.target_column_name].value_counts(normalize=True))
print("Test target distribution:\n", df.loc[test_idx, task_mold.target_column_name].value_counts(normalize=True))

splits = {
    0: {
        0: (train_idx, test_idx),
    }
}

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="We follow TabRed and simulate a use case of a model being refit every 4 to 5 months. We create one test split using 4,5 months of data (2020-05-01 to 2020-10-05) for testing and all the previous data for training.",
    splits=splits,
    time_horizon=5, # round up
    time_horizon_unit="months",
)

Train size: 1000000  | Test size: 224927
Train target distribution:
 target
0    0.966924
1    0.033076
Name: proportion, dtype: float64
Test target distribution:
 target
0    0.978046
1    0.021954
Name: proportion, dtype: float64

## Export

In [10]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to home_credit_default_stability/versions/019d308f-f814-7a3e-bf8f-508273a0e8f1
019d308f-f814-7a3e-bf8f-508273a0e8f1
63494a10e58d15d1abea2c64aca6e107f942773f687782051b10185f990ca754