### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="kdd_cup_09_appetency",
    dataset_year="2008",
    domain_str="business & marketing",
    # Data Source
    dataset_source="Other",
    original_dataset_source_download_link="https://kdd.org/kdd-cup/view/kdd-cup-2009/Data",
    download_description="""
We download the data and the labels from the KDD challenge website:

mkdir -p local-data-warehouse/kdd_cup_09_appetency && \
wget -P local-data-warehouse/kdd_cup_09_appetency https://kdd.org/cupfiles/KDDCupData/2009/orange_small_train.data.zip && \
unzip local-data-warehouse/kdd_cup_09_appetency/orange_small_train.data.zip -d local-data-warehouse/kdd_cup_09_appetency/ && \
rm local-data-warehouse/kdd_cup_09_appetency/orange_small_train.data.zip && \
wget -P local-data-warehouse/kdd_cup_09_appetency https://kdd.org/cupfiles/KDDCupData/2009/orange_small_train_appetency.labels
""",
    # References
    academic_reference_bibtex=r"""@inproceedings{guyon2009analysis,
  title={Analysis of the kdd cup 2009: Fast scoring on a large orange customer database},
  author={Guyon, Isabelle and Lemaire, Vincent and Boull{\'e}, Marc and Dror, Gideon and Vogel, David},
  booktitle={KDD-Cup 2009 Competition},
  pages={1--22},
  year={2009},
  organization={PMLR}
}
""",
    academic_reference_bibtex_key="guyon2009analysis",
    license="Public Domain",
    data_tags=["IID"],
    curation_comments="""
- We use the small training data from the original data (230 features).
- We use appetency as label.
- We dropped empty columns: "Var8", "Var15", "Var20", "Var31", "Var32", "Var39", "Var42", "Var48", "Var52", "Var55", "Var79", "Var141", "Var167", "Var169", "Var175", "Var185", "Var209", "Var230".
- Anomaly: the feature names and categorical feature values have no semantic meaning.
- Anomaly: this dataset has many missing values.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Appetency",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="Appetency",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(dataset_mold.path / "orange_small_train.data", sep="\t")
df_y = pd.read_csv(dataset_mold.path / "orange_small_train_appetency.labels", header=None)

target_feature = "Appetency"
df[target_feature] = df_y[0].astype("category")

empty_cols = [
    "Var8","Var15","Var20","Var31","Var32","Var39","Var42","Var48","Var52",
    "Var55","Var79","Var141","Var167","Var169","Var175","Var185","Var209","Var230",
]
df.drop(columns=empty_cols, inplace=True)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

cat_cols = [
    "Var192","Var193","Var194","Var195","Var196","Var197","Var198","Var199","Var200",
    "Var201","Var202","Var203","Var204","Var205","Var206","Var207","Var208","Var210",
    "Var211","Var212","Var214","Var216","Var217","Var218","Var219","Var220","Var222",
    "Var223","Var225","Var226","Var227","Var228","Var229",
    'Var191', 'Var213', 'Var215', 'Var221', 'Var224'
]
df[cat_cols] = df[cat_cols].astype("category")

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 50,000
Columns: 213
Use sampling: False (sample size: 50,000)

Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['Var113', 'Var81', 'Var133', 'Var153', 'Var134', 'Var38', 'Var76', 'Var57', 'Var163', 'Var94']
Rows remaining as candidates after top-10 filter: 4 (of 50,000)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Var215,category,49306.0,98.61,1.0,eGzu
1,Var224,category,49180.0,98.36,1.0,4n2X
2,Var191,category,48917.0,97.83,1.0,r__I
3,Var213,category,48871.0,97.74,1.0,KdSa
4,Var194,category,37216.0,74.43,3.0,"SEuy, lvza, CTUH"
5,Var201,category,37217.0,74.43,2.0,"smXZ, 6dX3"
6,Var229,category,28432.0,56.86,4.0,"am7c, mj86, sk2h, oJmt"
7,Var225,category,26144.0,52.29,3.0,"ELof, kG3k, xG3x"
8,Var200,category,25408.0,50.82,15415.0,"yP09M03, Uw6SDm8, Ipi9M03, EvCZGt8, MF5S0rA, 5YIkUea, b1M9M03, NvI9wLk, gWmZGt8, Uw6kiXL"
9,Var214,category,25408.0,50.82,15415.0,"5zARyjR, PXYoFMh, 5zA8Zov, PXYT2rL, 5zAF4eX, Fhz3CDZ, PXYoYU2, 5zA2v9l, PXYGJt6, PXYwoeV"
10,Var206,category,5529.0,11.06,21.0,"IYzP, zm5i, sYC_, haYg, hAFG, wMei, 43pnToF, kxE9, y6dw, 6JmL"
11,Var219,category,5211.0,10.42,22.0,"FzaX, AU8pNoi, qxDb, OFWH, AU8_WTd, wwPEXoilkr, Lmli, tdJW_Pm, FqMWi1g, ylgWTXl"
12,Var223,category,5211.0,10.42,4.0,"LM8l689qOp, jySVZNlOJy, M_8D, bCPvVye"
13,Var205,category,1934.0,3.87,3.0,"VpdQ, 09_Q, sJzTlal"
14,Var217,category,703.0,1.41,13990.0,"gvA6, 5smi, A1VJ, bru6, s9FI, 4a9J, aINY, g2AX, JEC4, p8c0"
15,Var218,category,703.0,1.41,2.0,"cJvF, UYBR"
16,Var192,category,369.0,0.74,361.0,"qFpmfo8zhV, DHeq9ayfAo, zKnr4RXktW, 8I1r4RXXnK, HYTrjIK12c, 75lr4RXktW, 1GdOj1KXzC, 2jirEyXktW, CxSr4RXktW, vAsgUHXM47"
17,Var197,category,143.0,0.29,225.0,"0Xwj, lK27, TyGl, 487l, JLbT, ssAy, z32l, kNzO, PGNs, 7gSz"
18,Var203,category,143.0,0.29,5.0,"9_Y1, HLqf, F3hy, dgxZ, pybr"
19,Var208,category,143.0,0.29,2.0,"kIsH, sBgB"
20,Var199,category,4.0,0.01,5073.0,"r83_sZi, _jTP8ioIlJ, FoJylxy, 76j2P_OLn0, glRBFJT8NN, msIqHk8toE, k10MzgT, hOpRIhsUSP, Tg7jjBB, _UtlxbJ"
21,Var193,category,0.0,0.00,51.0,"RO12, 2Knk1KF, AERks4l, g62hiBSaKg, e6CkoqApVR, LrdZy8QqgUfkVShG, rEUOq2QD1qfkRr6qpua, eSGpMwS8zSGgq_trOpckZ5, onTuEhrJJQy_H3IHkZku5AFczhYGqxJ890, w9ygS99Qp_"
22,Var195,category,0.0,0.00,23.0,"taul, LfvqpCtLOY, CiJDdr4TQ0rGERIS, ev6I, CuXi4je, b_3Q, I9xt3GDRhUK7p, I9xt3GMcxUnBZ, I9xt3GBDKUbd8, ArtjQZ8ftr3NB"
23,Var196,category,0.0,0.00,4.0,"1K8T, z3mO, JA1C, mKeq"
24,Var198,category,0.0,0.00,4291.0,"fhk21Ss, PHNvXy8, iJzviRg, 9GJGgoz, 6CXYbuk, fqeOwLG, jCepSrJ, _ybO0dd, pro8v8X, 0Vr7wZ4"
25,Var202,category,1.0,0.00,5713.0,"nyZz, VNjO, 85IW, rlx_, gMVu, Mx5G, o5H_, xklU, 8FB6, 0xFv"
26,Var204,category,0.0,0.00,100.0,"RVjC, k13i, m_h1, 7WNq, SkZj, MBhA, rGJy, RcM7, z5Ry, 15m3"
27,Var207,category,0.0,0.00,14.0,"me75fM6ugJ, 7M47J5GA0pTYIFxg5uy, DHn_WUyBhW_whjA88g9bvA64_, Kxdu, NKv3VA1BpP, GjJ35utlTa_GNSvxxpb9ju, 6C53VA1kCv, 5iay, EBKcR3s6B22tD6gC36gm6S, 15TtzZrRt2"
28,Var210,category,0.0,0.00,6.0,"uKAI, g5HH, 7A3j, oT7d, DM_V, 3av_"
29,Var211,category,0.0,0.00,2.0,"L84s, Mtgm"
30,Var212,category,0.0,0.00,81.0,"NhsEn4L, XfqtO3UdzaXh_, CrNX, Ie_5MZs, FMSzZ91zL2, 4kVnq_T26xq1p, h0lfDKh52u4GP, _5OXC8MSLt, 9pUnzWLbztKTo, JBfYVit4g8"
31,Var216,category,0.0,0.00,2016.0,"mAjbk_S, mAja5EA, kZJtVhC, XTbPUYD, beK4AFX, 11p4mKe, NGZxnJM, kZJyVg2, kq0aHkC, kq0n8Bj"
32,Var220,category,0.0,0.00,4291.0,"4UxGlow, UF16siJ, ch2oGfM, Tvpip6Z, ROeipLp, fxJmel6, Oy_RPEi, L91KIiz, meWVy8V, XbZitea"
33,Var221,category,0.0,0.00,7.0,"oslk, zCkv, d0EEeJi, QKW8DRm, Al6ZaUT, z4pH, JIiEFBU"
34,Var222,category,0.0,0.00,4291.0,"catzS2D, APgdzOv, P6pu4Vl, hHJsvbM, K2SqEo9, WfsWw2A, FS4qjNq, CE7uk3u, DQ3u3MC, DHPNgqU"
35,Var226,category,0.0,0.00,23.0,"FSa2, Qu4f, WqMG, szEZ, 7P5s, fKCe, Aoh3, 5Acm, 453m, xb3V"
36,Var227,category,0.0,0.00,7.0,"RAYp, ZI9m, 6fzt, 02N6s8f, nIGXDli, vJ_w8kB, nIGjgSB"
37,Var228,category,0.0,0.00,30.0,"F2FyR07IdsN7I, 55YFVY9, ib5G6X1eUxUn6, R4y5gQQWY8OodqDV, xwM2aC7IdeMC0, TCU50_Yjmm6GIBZ0lL_, iyHGyLCEkQ, Zy3gnGM, F2FcTt7IdMT_v, SbOd7O8ky1wGNxp0Arj0Xs"
38,Appetency,category,0.0,0.00,2.0,"-1, 1"
39,Var92,float64,49829.0,99.66,169.0,"8225.0, 0.0, 50701.0, 513002.0, 39956.0, 55951.0, 33810.0, 194761.0, 145838.0, 23926.0"
40,Var118,float64,49829.0,99.66,1.0,3.0
41,Var64,float64,49762.0,99.52,233.0,"12960.0, 0.0, 25697.07, 77171.4, 1435.5, 11830.5, 8235.72, 604.62, 3435.93, 59624.73"
42,Var190,float64,49667.0,99.33,328.0,"0.0, 12960.0, 25953.57, 28484.01, 52025.85, 25952.94, 86645.08, 15517.53, 5717.88, 61643.61"
43,Var45,float64,49656.0,99.31,343.0,"2985.64, 11994.5, 14412.84, 2664.96, 17507.62, 223.54, 1343.08, 1886.26, 839.84, 5331.66"
44,Var102,float64,49549.0,99.10,445.0,"0.0, 25920.0, 51840.0, 22.5, 407.97, 78417.54, 5163.479, 26266.68, 62699.04, 10510.29"
45,Var12,float64,49442.0,98.88,22.0,"0.0, 8.0, 16.0, 24.0, 32.0, 40.0, 48.0, 56.0, 72.0, 104.0"
46,Var62,float64,49442.0,98.88,12.0,"0.0, 9.0, 18.0, 27.0, 45.0, 72.0, 36.0, 441.0, 288.0, 90.0"
47,Var98,float64,49442.0,98.88,115.0,"0.0, 345600.0, 4580.0, 6868.0, 91624.0, 7164.0, 13524.0, 72108.0, 71604.0, 86284.0"
48,Var56,float64,49354.0,98.71,195.0,"0.0, 432000.0, 864000.0, 7530.0, 3105.0, 3012970.0, 163525.0, 77965.0, 67440.0, 215035.0"
49,Var89,float64,49354.0,98.71,16.0,"0.0, 6.0, 12.0, 24.0, 18.0, 30.0, 42.0, 90.0, 36.0, 72.0"
50,Var178,float64,49354.0,98.71,30.0,"0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 40.0, 35.0, 30.0, 45.0"
51,Var63,float64,49306.0,98.61,48.0,"0.0, 6.0, 12.0, 18.0, 24.0, 36.0, 30.0, 42.0, 48.0, 60.0"
52,Var66,float64,49306.0,98.61,100.0,"0.0, 16.0, 12.0, 20.0, 4.0, 8.0, 24.0, 28.0, 68.0, 44.0"
53,Var136,float64,49306.0,98.61,534.0,"0.0, 172800.0, 1209600.0, 33040.0, 95572.2, 106147.2, 127240.4, 74398.2, 436898.0, 328300.0"
54,Var156,float64,49306.0,98.61,100.0,"0.0, 28.0, 21.0, 35.0, 7.0, 14.0, 42.0, 49.0, 119.0, 77.0"
55,Var1,float64,49298.0,98.60,18.0,"0.0, 8.0, 16.0, 24.0, 32.0, 40.0, 48.0, 56.0, 72.0, 128.0"
56,Var9,float64,49298.0,98.60,100.0,"0.0, 8.0, 6.0, 10.0, 2.0, 4.0, 12.0, 14.0, 34.0, 22.0"
57,Var29,float64,49298.0,98.60,2.0,"0.0, 2.0"
58,Var30,float64,49298.0,98.60,13.0,"5.0, 0.0, 10.0, 15.0, 20.0, 25.0, 30.0, 45.0, 35.0, 60.0"
59,Var41,float64,49298.0,98.60,36.0,"0.0, 7.0, 14.0, 21.0, 28.0, 35.0, 42.0, 56.0, 49.0, 77.0"
60,Var47,float64,49298.0,98.60,11.0,"0.0, 8.0, 16.0, 24.0, 32.0, 64.0, 48.0, 56.0, 80.0, 168.0"
61,Var50,float64,49298.0,98.60,63.0,"0.0, 15.0, 20.0, 5.0, 30.0, 45.0, 40.0, 80.0, 105.0, 50.0"
62,Var53,float64,49298.0,98.60,397.0,"0.0, 777600.0, 3110400.0, 5443200.0, 10886400.0, 712818.0, 3888000.0, 1555200.0, 2332800.0, 6220800.0"
63,Var58,float64,49298.0,98.60,244.0,"0.0, 691200.0, 1382400.0, 4838400.0, 218656.0, 217680.0, 16544.0, 231904.0, 137920.0, 279568.0"
64,Var77,float64,49298.0,98.60,23.0,"0.0, 6.0, 12.0, 18.0, 24.0, 36.0, 30.0, 42.0, 72.0, 48.0"
65,Var86,float64,49298.0,98.60,448.0,"0.0, 172800.0, 1209600.0, 518400.0, 1555200.0, 691200.0, 2073600.0, 51818.0, 541782.0, 785824.0"
66,Var87,float64,49298.0,98.60,5.0,"7.0, 0.0, 14.0, 28.0, 21.0"
67,Var90,float64,49298.0,98.60,2.0,"0.0, 7.0"
68,Var100,float64,49298.0,98.60,5.0,"0.0, 7.0, 14.0, 21.0, 28.0"
69,Var108,float64,49298.0,98.60,341.0,"0.0, 345600.0, 691200.0, 1036800.0, 2419200.0, 2148.0, 1382400.0, 797520.0, 90768.0, 40000.0"
70,Var110,float64,49298.0,98.60,5.0,"6.0, 12.0, 18.0, 30.0, 24.0"
71,Var116,float64,49298.0,98.60,2.0,"0.0, 3.0"
72,Var121,float64,49298.0,98.60,33.0,"0.0, 2.0, 4.0, 6.0, 8.0, 12.0, 10.0, 14.0, 18.0, 16.0"
73,Var129,float64,49298.0,98.60,45.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 16.0, 12.0, 18.0, 14.0"
74,Var131,float64,49298.0,98.60,152.0,"0.0, 6236344.0, 55376.0, 152872.0, 1769296.0, 2091272.0, 25124000.0, 48320880.0, 501344.0, 85880.0"
75,Var137,float64,49298.0,98.60,19.0,"0.0, 4.0, 8.0, 12.0, 16.0, 20.0, 24.0, 28.0, 36.0, 64.0"
76,Var142,float64,49298.0,98.60,4.0,"0.0, 4.0, 8.0, 12.0"
77,Var154,float64,49298.0,98.60,388.0,"0.0, 2073600.0, 4838400.0, 1382400.0, 691200.0, 2764800.0, 9676800.0, 3456000.0, 6220800.0, 8281680.0"
78,Var168,float64,49298.0,98.60,453.0,"247.84, 368.48, 358.16, 283.36, 311.76, 322.72, 290.48, 400.8, 301.52, 313.52"
79,Var180,float64,49298.0,98.60,547.0,"0.0, 2419200.0, 4233600.0, 5435080.0, 7716030.0, 5017544.0, 3343634.0, 8461460.0, 5468267.0, 9174900.0"
80,Var186,float64,49298.0,98.60,13.0,"0.0, 6.0, 12.0, 18.0, 24.0, 36.0, 30.0, 54.0, 42.0, 66.0"
81,Var187,float64,49298.0,98.60,57.0,"0.0, 2.0, 4.0, 10.0, 6.0, 8.0, 14.0, 12.0, 18.0, 16.0"
82,Var59,float64,49180.0,98.36,566.0,"0.0, 777600.0, 5443200.0, 1890.0, 7014.456, 573441.3, 463588.2, 629955.9, 916659.0, 12078.0"
83,Var104,float64,49180.0,98.36,62.0,"0.0, 9.0, 45.0, 54.0, 63.0, 36.0, 27.0, 72.0, 18.0, 90.0"
84,Var105,float64,49180.0,98.36,62.0,"0.0, 6.0, 30.0, 36.0, 42.0, 24.0, 18.0, 48.0, 12.0, 60.0"
85,Var115,float64,49180.0,98.36,35.0,"0.0, 18.0, 9.0, 27.0, 36.0, 45.0, 90.0, 63.0, 81.0, 54.0"
86,Var33,float64,49153.0,98.31,298.0,"0.0, 777600.0, 1512.0, 77211.0, 194868.0, 368037.0, 32796.0, 1849104.0, 165177.0, 62847.0"
87,Var61,float64,49153.0,98.31,39.0,"0.0, 8.0, 16.0, 24.0, 32.0, 40.0, 72.0, 48.0, 56.0, 80.0"
88,Var151,float64,49153.0,98.31,19.0,"0.0, 8.0, 16.0, 24.0, 32.0, 40.0, 56.0, 48.0, 64.0, 80.0"
89,Var101,float64,49127.0,98.25,28.0,"0.0, 9.0, 18.0, 27.0, 36.0, 45.0, 54.0, 81.0, 72.0, 99.0"
90,Var158,float64,49127.0,98.25,18.0,"0.0, 3.0, 6.0, 9.0, 12.0, 18.0, 21.0, 30.0, 48.0, 45.0"
91,Var165,float64,49127.0,98.25,204.0,"0.0, 172800.0, 345600.0, 25600.0, 75858.0, 349186.0, 238324.0, 583940.0, 22494.0, 34158.0"
92,Var88,float64,48917.0,97.83,88.0,"0.0, 10.0, 15.0, 20.0, 25.0, 40.0, 5.0, 30.0, 45.0, 35.0"
93,Var127,float64,48917.0,97.83,39.0,"0.0, 8.0, 16.0, 32.0, 24.0, 40.0, 48.0, 56.0, 64.0, 72.0"
94,Var128,float64,48917.0,97.83,88.0,"0.0, 14.0, 21.0, 28.0, 35.0, 56.0, 7.0, 42.0, 63.0, 49.0"
95,Var171,float64,48917.0,97.83,746.0,"0.0, 777600.0, 712827.0, 712845.0, 712822.5, 777604.5, 712840.5, 712831.5, 712818.0, 712854.0"
96,Var71,float64,48871.0,97.74,119.0,"0.0, 24.0, 12.0, 18.0, 42.0, 30.0, 36.0, 54.0, 48.0, 84.0"
97,Var91,float64,48871.0,97.74,119.0,"0.0, 16.0, 8.0, 12.0, 28.0, 20.0, 24.0, 36.0, 32.0, 56.0"
98,Var111,float64,48871.0,97.74,794.0,"0.0, 518400.0, 3628800.0, 3628806.0, 83633.41, 454718.4, 334765.2, 14261.64, 610560.0, 3348.0"
99,Var157,float64,48871.0,97.74,64.0,"0.0, 4.0, 8.0, 16.0, 12.0, 24.0, 20.0, 28.0, 32.0, 36.0"
100,Var2,float64,48759.0,97.52,2.0,"0.0, 5.0"
101,Var3,float64,48760.0,97.52,146.0,"0.0, 3.0, 144.0, 9.0, 6.0, 18.0, 81.0, 99.0, 60.0, 90.0"
102,Var11,float64,48760.0,97.52,5.0,"8.0, 16.0, 24.0, 32.0, 40.0"
103,Var14,float64,48760.0,97.52,19.0,"0.0, 2.0, 4.0, 8.0, 6.0, 16.0, 18.0, 14.0, 20.0, 12.0"
104,Var34,float64,48759.0,97.52,6.0,"0.0, 8.0, 16.0, 24.0, 32.0, 56.0"
105,Var36,float64,48759.0,97.52,531.0,"0.0, 345600.0, 172800.0, 518400.0, 1036800.0, 224.0, 976874.0, 242774.0, 212566.0, 27124.0"
106,Var40,float64,48759.0,97.52,27.0,"0.0, 8.0, 16.0, 24.0, 32.0, 48.0, 40.0, 80.0, 56.0, 64.0"
107,Var43,float64,48759.0,97.52,20.0,"0.0, 5.0, 10.0, 15.0, 20.0, 30.0, 40.0, 35.0, 25.0, 55.0"
108,Var46,float64,48759.0,97.52,50.0,"0.0, 8.0, 4.0, 12.0, 20.0, 16.0, 24.0, 28.0, 32.0, 44.0"
109,Var49,float64,48759.0,97.52,4.0,"0.0, 6.0, 18.0, 12.0"
110,Var54,float64,48759.0,97.52,5.0,"0.0, 8.0, 16.0, 24.0, 32.0"
111,Var68,float64,48759.0,97.52,84.0,"0.0, 42.0, 7.0, 28.0, 21.0, 35.0, 14.0, 49.0, 56.0, 63.0"
112,Var75,float64,48759.0,97.52,13.0,"0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 40.0, 35.0, 45.0"
113,Var84,float64,48760.0,97.52,96.0,"0.0, 4.0, 8.0, 16.0, 40.0, 20.0, 36.0, 12.0, 64.0, 28.0"
114,Var95,float64,48759.0,97.52,267.0,"0.0, 1036800.0, 518400.0, 1555200.0, 475242.0, 3042.0, 184158.0, 152460.0, 177216.0, 541980.0"
115,Var96,float64,48759.0,97.52,33.0,"0.0, 2.0, 4.0, 6.0, 8.0, 12.0, 10.0, 14.0, 16.0, 20.0"
116,Var114,float64,48759.0,97.52,643.0,"0.0, 1209600.0, 864000.0, 420.0, 224.0, 1035018.0, 2818600.0, 1942368.0, 982448.0, 2281020.0"
117,Var122,float64,48759.0,97.52,3.0,"0.0, 3.0, 6.0"
118,Var130,float64,48760.0,97.52,2.0,"0.0, 3.0"
119,Var159,float64,48759.0,97.52,10.0,"0.0, 9.0, 18.0, 27.0, 36.0, 54.0, 45.0, 63.0, 72.0, 99.0"
120,Var162,float64,48759.0,97.52,471.0,"0.0, 777600.0, 1555200.0, 5443200.0, 2332800.0, 8541.0, 10886400.0, 60642.0, 3888000.0, 387099.0"
121,Var170,float64,48759.0,97.52,18.0,"0.0, 3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 81.0, 51.0"
122,Var176,float64,48760.0,97.52,28.0,"0.0, 4.0, 8.0, 12.0, 16.0, 64.0, 28.0, 52.0, 68.0, 48.0"
123,Var177,float64,48759.0,97.52,443.0,"0.0, 1209600.0, 604800.0, 2419200.0, 4233600.0, 1814400.0, 3024000.0, 2660392.0, 6780956.0, 1591366.0"
124,Var183,float64,48759.0,97.52,374.0,"0.0, 345600.0, 172800.0, 1209600.0, 518400.0, 138488.0, 50006.0, 158410.0, 128280.0, 83122.0"
125,Var184,float64,48759.0,97.52,31.0,"0.0, 4.0, 8.0, 12.0, 16.0, 20.0, 28.0, 32.0, 24.0, 36.0"
126,Var188,float64,48759.0,97.52,535.0,"15.6, 0.0, 16.14, 19.92, 18.3, 16.68, 18.84, 17.76, 19.38, 252.96"
127,Var5,float64,48513.0,97.03,571.0,"0.0, 432000.0, 864000.0, 3024000.0, 1296000.0, 39580.0, 62160.0, 2592000.0, 852375.0, 5530.0"
128,Var10,float64,48513.0,97.03,534.0,"0.0, 777600.0, 1555200.0, 2332800.0, 3110400.0, 5443200.0, 1425618.0, 3888000.0, 2709.0, 265230.0"
129,Var16,float64,48513.0,97.03,597.0,"0.0, 11.0, 11.32, 12.0, 11.64, 10.68, 50.48, 49.08, 47.68, 12.96"
130,Var23,float64,48513.0,97.03,29.0,"0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 35.0, 40.0, 45.0"
131,Var26,float64,48513.0,97.03,4.0,"0.0, 3.0, 6.0, 9.0"
132,Var27,float64,48513.0,97.03,3.0,"0.0, 2.0, 4.0"
133,Var60,float64,48513.0,97.03,47.0,"0.0, 3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 27.0, 24.0"
134,Var67,float64,48513.0,97.03,2.0,"0.0, 5.0"
135,Var69,float64,48513.0,97.03,838.0,"0.0, 10886400.0, 5443200.0, 2332800.0, 777600.0, 8553600.0, 5952294.0, 120888.0, 11452680.0, 5711733.0"
136,Var70,float64,48513.0,97.03,521.0,"0.0, 1814400.0, 259200.0, 1296000.0, 518400.0, 3628800.0, 1555200.0, 2592000.0, 777600.0, 3888000.0"
137,Var80,float64,48513.0,97.03,400.0,"0.0, 259200.0, 518400.0, 777600.0, 237603.0, 475212.0, 95922.0, 98055.0, 62652.0, 164442.0"
138,Var93,float64,48513.0,97.03,4.0,"2.0, 4.0, 6.0, 8.0"
139,Var97,float64,48513.0,97.03,7.0,"0.0, 6.0, 12.0, 18.0, 24.0, 30.0, 36.0"
140,Var103,float64,48513.0,97.03,39.0,"0.0, 7.0, 14.0, 21.0, 35.0, 28.0, 70.0, 49.0, 42.0, 63.0"
141,Var107,float64,48513.0,97.03,24.0,"0.0, 3.0, 6.0, 12.0, 9.0, 18.0, 15.0, 21.0, 27.0, 24.0"
142,Var120,float64,48513.0,97.03,64.0,"0.0, 6.0, 12.0, 18.0, 24.0, 30.0, 48.0, 42.0, 36.0, 54.0"
143,Var139,float64,48513.0,97.03,674.0,"0.0, 1209600.0, 172800.0, 19182.0, 11678.0, 2419200.0, 345600.0, 518400.0, 226698.0, 381882.0"
144,Var146,float64,48513.0,97.03,10.0,"0.0, 8.0, 16.0, 24.0, 32.0, 40.0, 48.0, 80.0, 96.0, 64.0"
145,Var147,float64,48513.0,97.03,5.0,"2.0, 0.0, 4.0, 6.0, 8.0"
146,Var148,float64,48513.0,97.03,119.0,"0.0, 24.0, 16.0, 32.0, 56.0, 48.0, 40.0, 8.0, 72.0, 64.0"
147,Var166,float64,48513.0,97.03,48.0,"0.0, 7.0, 14.0, 21.0, 28.0, 35.0, 42.0, 63.0, 77.0, 49.0"
148,Var172,float64,48513.0,97.03,13.0,"7.0, 0.0, 14.0, 21.0, 28.0, 35.0, 42.0, 49.0, 56.0, 105.0"
149,Var4,float64,48421.0,96.84,4.0,"0.0, 9.0, 18.0, 27.0"
150,Var17,float64,48421.0,96.84,37.0,"0.0, 5.0, 10.0, 15.0, 20.0, 35.0, 25.0, 30.0, 40.0, 45.0"
151,Var18,float64,48421.0,96.84,26.0,"0.0, 6.0, 12.0, 18.0, 24.0, 30.0, 36.0, 48.0, 42.0, 54.0"
152,Var19,float64,48421.0,96.84,4.0,"0.0, 9.0, 27.0, 18.0"
153,Var37,float64,48421.0,96.84,550.0,"0.0, 1555200.0, 712827.0, 712836.0, 712818.0, 5443200.0, 3110400.0, 1425645.0, 777600.0, 1555209.0"
154,Var82,float64,48421.0,96.84,4.0,"3.0, 0.0, 6.0, 9.0"
155,Var99,float64,48421.0,96.84,47.0,"0.0, 8.0, 16.0, 24.0, 40.0, 32.0, 48.0, 56.0, 72.0, 80.0"
156,Var106,float64,48421.0,96.84,261.0,"0.0, 518400.0, 259200.0, 1036800.0, 1814400.0, 9.0, 202431.0, 303024.0, 181476.0, 180570.0"
157,Var117,float64,48421.0,96.84,656.0,"0.0, 345600.0, 172800.0, 1209600.0, 691200.0, 158410.0, 158406.0, 475218.0, 864000.0, 172790.0"
158,Var124,float64,48421.0,96.84,347.0,"0.0, 1382400.0, 691200.0, 2764800.0, 4838400.0, 2073600.0, 41104.0, 1348792.0, 1940720.0, 587104.0"
159,Var135,float64,48421.0,96.84,679.0,"0.0, 18.69, 19.25, 22.12, 18.13, 22.68, 21.0, 21.56, 20.37, 198.24"
160,Var138,float64,48421.0,96.84,2.0,"0.0, 2.0"
161,Var145,float64,48421.0,96.84,88.0,"0.0, 12.0, 18.0, 24.0, 30.0, 6.0, 48.0, 42.0, 54.0, 36.0"
162,Var150,float64,48421.0,96.84,600.0,"0.0, 864000.0, 396020.0, 432000.0, 396015.0, 396010.0, 792030.0, 396025.0, 1296000.0, 396005.0"
163,Var152,float64,48421.0,96.84,12.0,"6.0, 0.0, 12.0, 18.0, 24.0, 30.0, 36.0, 42.0, 48.0, 66.0"
164,Var155,float64,48421.0,96.84,8.0,"0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 35.0, 30.0"
165,Var161,float64,48421.0,96.84,9.0,"0.0, 9.0, 18.0, 27.0, 36.0, 45.0, 54.0, 63.0, 81.0"
166,Var164,float64,48421.0,96.84,19.0,"0.0, 3.0, 6.0, 9.0, 12.0, 21.0, 15.0, 18.0, 27.0, 138.0"
167,Var174,float64,48421.0,96.84,29.0,"0.0, 4.0, 8.0, 12.0, 16.0, 20.0, 24.0, 28.0, 32.0, 36.0"
168,Var179,float64,48421.0,96.84,15.0,"0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 40.0, 50.0, 890.0"
169,Var182,float64,48421.0,96.84,819.0,"0.0, 1036800.0, 950430.0, 950436.0, 950460.0, 1036806.0, 950454.0, 950424.0, 950442.0, 6220800.0"
170,Var51,float64,46253.0,92.51,3561.0,"0.0, 11520.0, 80640.0, 161280.0, 10560.16, 182667.2, 11324.48, 1030.4, 5074.16, 164.4"
171,Var189,float64,28978.0,57.96,97.0,"282.0, 276.0, 270.0, 288.0, 294.0, 252.0, 300.0, 264.0, 240.0, 306.0"
172,Var72,float64,22380.0,44.76,8.0,"3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0"
173,Var94,float64,22380.0,44.76,20002.0,"0.0, 36.0, 72.0, 108.0, 144.0, 216.0, 84.0, 60.0, 24.0, 96.0"
174,Var126,float64,13920.0,27.84,51.0,"4.0, -30.0, -20.0, -18.0, -28.0, -22.0, -26.0, -24.0, 6.0, 8.0"
175,Var24,float64,7230.0,14.46,93.0,"0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
176,Var109,float64,7230.0,14.46,209.0,"32.0, 40.0, 24.0, 48.0, 0.0, 8.0, 16.0, 56.0, 64.0, 72.0"
177,Var149,float64,7230.0,14.46,18652.0,"0.0, 604800.0, 1209600.0, 554414.0, 1814400.0, 554421.0, 554435.0, 2419200.0, 554428.0, 554407.0"
178,Var7,float64,5539.0,11.08,8.0,"7.0, 0.0, 14.0, 21.0, 28.0, 35.0, 140.0, 42.0"
179,Var13,float64,5539.0,11.08,2634.0,"0.0, 4.0, 8.0, 12.0, 16.0, 24.0, 20.0, 28.0, 36.0, 44.0"
180,Var65,float64,5539.0,11.08,15.0,"9.0, 18.0, 27.0, 36.0, 45.0, 54.0, 63.0, 72.0, 81.0, 90.0"
181,Var74,float64,5539.0,11.08,371.0,"0.0, 7.0, 14.0, 21.0, 28.0, 35.0, 42.0, 49.0, 56.0, 63.0"
182,Var125,float64,5539.0,11.08,10505.0,"0.0, 153.0, 171.0, 225.0, 117.0, 198.0, 423.0, 207.0, 333.0, 144.0"
183,Var140,float64,5539.0,11.08,2648.0,"0.0, 5.0, 10.0, 15.0, 20.0, 30.0, 40.0, 25.0, 65.0, 35.0"
184,Var6,float64,5529.0,11.06,1486.0,"0.0, 777.0, 805.0, 798.0, 791.0, 812.0, 833.0, 784.0, 826.0, 840.0"
185,Var21,float64,5529.0,11.06,734.0,"132.0, 136.0, 0.0, 124.0, 128.0, 140.0, 144.0, 148.0, 152.0, 120.0"
186,Var81,float64,5529.0,11.06,43042.0,"0.0, 259200.0, 183267.3, 191281.8, 226340.7, 49480.2, 198568.2, 57073.5, 202639.2, 5489.61"
187,Var119,float64,5529.0,11.06,1487.0,"0.0, 510.0, 520.0, 505.0, 500.0, 515.0, 525.0, 530.0, 495.0, 490.0"
188,Var144,float64,5529.0,11.06,10.0,"9.0, 0.0, 18.0, 27.0, 36.0, 45.0, 54.0, 63.0, 72.0, 81.0"
189,Var22,float64,5009.0,10.02,735.0,"0.0, 165.0, 170.0, 155.0, 160.0, 175.0, 180.0, 185.0, 190.0, 150.0"
190,Var25,float64,5009.0,10.02,271.0,"0.0, 8.0, 16.0, 24.0, 32.0, 40.0, 48.0, 56.0, 64.0, 72.0"
191,Var28,float64,5011.0,10.02,4167.0,"166.56, 220.08, 186.64, 253.52, 200.0, 133.12, 286.96, 233.44, 0.0, 320.4"
192,Var35,float64,5009.0,10.02,13.0,"0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 35.0, 40.0, 45.0"
193,Var38,float64,5009.0,10.02,30832.0,"0.0, 3628800.0, 7257600.0, 11404800.0, 518400.0, 1555200.0, 2073600.0, 10886400.0, 1036800.0, 4665600.0"
194,Var44,float64,5009.0,10.02,8.0,"0.0, 9.0, 18.0, 27.0, 36.0, 63.0, 72.0, 135.0"
195,Var76,float64,5009.0,10.02,29743.0,"0.0, 1382400.0, 2764800.0, 5529600.0, 4838400.0, 4147200.0, 691200.0, 2073600.0, 3456000.0, 6220800.0"
196,Var78,float64,5009.0,10.02,13.0,"0.0, 3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0, 27.0"
197,Var83,float64,5009.0,10.02,195.0,"0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 35.0, 30.0, 45.0, 40.0"
198,Var85,float64,5009.0,10.02,149.0,"0.0, 4.0, 2.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0"
199,Var112,float64,5009.0,10.02,230.0,"0.0, 16.0, 32.0, 24.0, 8.0, 40.0, 48.0, 64.0, 56.0, 72.0"

In [5]:
# Numeric Feature Statistics
numeric_stats

          count          mean           std           min           max
Var1      702.0  1.148718e+01  4.070995e+01  0.000000e+00  6.800000e+02
Var2     1241.0  4.029009e-03  1.419332e-01  0.000000e+00  5.000000e+00
Var3     1240.0  4.252984e+02  4.270194e+03  0.000000e+00  1.306680e+05
Var4     1579.0  1.253958e-01  1.275481e+00  0.000000e+00  2.700000e+01
Var5     1487.0  2.387933e+05  6.441259e+05  0.000000e+00  6.048550e+06
Var6    44471.0  1.326437e+03  2.685694e+03  0.000000e+00  1.317610e+05
Var7    44461.0  6.809496e+00  6.326053e+00  0.000000e+00  1.400000e+02
Var9      702.0  4.814530e+01  1.547779e+02  0.000000e+00  2.300000e+03
Var10    1487.0  3.926057e+05  9.280896e+05  0.000000e+00  1.232559e+07
Var11    1240.0  8.625806e+00  2.869558e+00  8.000000e+00  4.000000e+01
Var12     558.0  1.607168e+01  6.418551e+01  0.000000e+00  1.184000e+03
Var13   44461.0  1.249688e+03  2.794955e+03  0.000000e+00  1.978720e+05
Var14    1240.0  7.419355e-01  3.714316e+00  0.000000e+00  4.800000e+01
Var16    1487.0  1.202393e+02  7.238625e+01  0.000000e+00  4.349200e+02
Var17    1579.0  1.139329e+01  4.949386e+01  0.000000e+00  1.220000e+03
Var18    1579.0  7.215959e+00  3.441543e+01  0.000000e+00  9.480000e+02
Var19    1579.0  2.450918e-01  1.781497e+00  0.000000e+00  2.700000e+01
Var21   44471.0  2.345182e+02  5.655601e+02  0.000000e+00  3.627200e+04
Var22   44991.0  2.902454e+02  7.044900e+02  0.000000e+00  4.534000e+04
Var23    1487.0  7.535306e+00  4.944947e+01  0.000000e+00  1.555000e+03
Var24   42770.0  4.507926e+00  9.928819e+00  0.000000e+00  4.940000e+02
Var25   44991.0  9.682701e+01  2.143183e+02  0.000000e+00  1.316800e+04
Var26    1487.0  7.061197e-02  5.288359e-01  0.000000e+00  9.000000e+00
Var27    1487.0  2.824479e-02  2.472102e-01  0.000000e+00  4.000000e+00
Var28   44989.0  2.245077e+02  9.852024e+01 -6.688000e+01  5.158560e+03
Var29     702.0  2.279202e-02  2.124355e-01  0.000000e+00  2.000000e+00
Var30     702.0  7.435897e+00  8.852461e+00  0.000000e+00  9.500000e+01
Var33     847.0  1.270050e+05  4.957921e+05  0.000000e+00  1.088640e+07
Var34    1241.0  1.173247e+00  4.377707e+00  0.000000e+00  5.600000e+01
Var35   44991.0  7.168100e-01  2.996007e+00  0.000000e+00  1.100000e+02
Var36    1241.0  1.595539e+05  3.277151e+05  0.000000e+00  2.419600e+06
Var37    1579.0  6.485221e+05  1.382225e+06  0.000000e+00  1.163502e+07
Var38   44991.0  2.579107e+06  3.010076e+06  0.000000e+00  1.884690e+07
Var40    1241.0  1.396293e+01  8.141001e+01  0.000000e+00  2.648000e+03
Var41     702.0  2.665385e+01  6.184552e+01  0.000000e+00  7.280000e+02
Var43    1241.0  4.157937e+00  2.057040e+01  0.000000e+00  6.250000e+02
Var44   44991.0  1.668334e-01  1.629344e+00  0.000000e+00  1.350000e+02
Var45     344.0  7.256128e+03  8.798177e+03  0.000000e+00  6.055340e+04
Var46    1241.0  1.679613e+01  7.081733e+01  0.000000e+00  1.668000e+03
Var47     702.0  2.188034e+00  1.019071e+01  0.000000e+00  1.680000e+02
Var49    1241.0  9.186140e-02  8.805826e-01  0.000000e+00  1.800000e+01
Var50     702.0  3.569088e+01  1.270346e+02  0.000000e+00  1.660000e+03
Var51    3747.0  4.365201e+04  7.122949e+04  0.000000e+00  3.478064e+05
Var53     702.0  6.543265e+05  1.379408e+06  0.000000e+00  1.251315e+07
Var54    1241.0  4.789686e+00  5.828331e+00  0.000000e+00  3.200000e+01
Var56     646.0  8.796467e+04  2.738856e+05  0.000000e+00  3.012970e+06
Var57   50000.0  3.512311e+00  2.025882e+00  2.136296e-04  7.000000e+00
Var58     702.0  1.640613e+05  6.457805e+05  0.000000e+00  9.676800e+06
Var59     820.0  4.145965e+05  7.673712e+05  0.000000e+00  5.443200e+06
Var60    1487.0  9.538668e+00  4.917774e+01  0.000000e+00  1.215000e+03
Var61     847.0  4.046281e+01  1.907457e+02  0.000000e+00  4.624000e+03
Var62     558.0  5.096774e+00  2.441498e+01  0.000000e+00  4.410000e+02
Var63     694.0  4.020173e+01  1.557370e+02  0.000000e+00  2.952000e+03
Var64     238.0  2.652647e+04  3.276447e+04  0.000000e+00  2.237283e+05
Var65   44461.0  1.486890e+01  1.013444e+01  9.000000e+00  1.800000e+02
Var66     694.0  9.684150e+01  3.112495e+02  0.000000e+00  4.600000e+03
Var67    1487.0  1.681237e-02  2.895438e-01  0.000000e+00  5.000000e+00
Var68    1241.0  8.559629e+01  3.970628e+02  0.000000e+00  1.192100e+04
Var69    1487.0  3.531945e+06  4.937707e+06  0.000000e+00  1.874187e+07
Var70    1487.0  4.003406e+05  8.096815e+05  0.000000e+00  6.189690e+06
Var71    1129.0  1.370593e+02  5.411525e+02  0.000000e+00  1.410600e+04
Var72   27620.0  4.190659e+00  2.304777e+00  3.000000e+00  2.400000e+01
Var73   50000.0  6.664108e+01  5.285917e+01  4.000000e+00  2.640000e+02
Var74   44461.0  1.036581e+02  7.667120e+02  0.000000e+00  1.421560e+05
Var75    1241.0  6.498791e+00  8.625836e+00  0.000000e+00  7.000000e+01
Var76   44991.0  1.490154e+06  1.853693e+06  0.000000e+00  1.935360e+07
Var77     702.0  1.041026e+01  4.168686e+01  0.000000e+00  6.660000e+02
Var78   44991.0  5.347069e-01  2.135359e+00  0.000000e+00  3.900000e+01
Var80    1487.0  5.442104e+04  1.883292e+05  0.000000e+00  3.637080e+06
Var81   44471.0  1.030841e+05  1.062721e+05  0.000000e+00  1.814403e+06
Var82    1579.0  2.426219e+00  2.298420e+00  0.000000e+00  9.000000e+00
Var83   44991.0  2.002356e+01  8.812946e+01  0.000000e+00  6.335000e+03
Var84    1240.0  4.252742e+01  2.432450e+02  0.000000e+00  4.160000e+03
Var85   44991.0  8.461026e+00  2.062048e+01  0.000000e+00  1.178000e+03
Var86     702.0  2.868930e+05  4.587784e+05  0.000000e+00  2.425840e+06
Var87     702.0  5.424501e+00  5.250840e+00  0.000000e+00  2.800000e+01
Var88    1083.0  6.894737e+01  2.264684e+02  0.000000e+00  5.105000e+03
Var89     646.0  5.517028e+00  1.720867e+01  0.000000e+00  3.000000e+02
Var90     702.0  1.994302e-02  3.733658e-01  0.000000e+00  7.000000e+00
Var91    1129.0  9.137290e+01  3.607684e+02  0.000000e+00  9.404000e+03
Var92     171.0  1.706794e+05  2.228206e+05  0.000000e+00  1.865367e+06
Var93    1487.0  2.127774e+00  6.245984e-01  2.000000e+00  8.000000e+00
Var94   27620.0  9.867107e+04  1.806333e+05  0.000000e+00  5.640330e+06
Var95    1241.0  1.097714e+05  3.600879e+05  0.000000e+00  3.629172e+06
Var96    1241.0  4.646253e+00  2.123201e+01  0.000000e+00  4.980000e+02
Var97    1487.0  9.159381e-01  3.404187e+00  0.000000e+00  3.600000e+01
Var98     558.0  2.129506e+04  8.341316e+04  0.000000e+00  1.245440e+06
Var99    1579.0  2.627992e+01  9.459508e+01  0.000000e+00  2.848000e+03
Var100    702.0  8.874644e-01  3.147381e+00  0.000000e+00  2.800000e+01
Var101    873.0  1.980412e+01  8.398730e+01  0.000000e+00  1.755000e+03
Var102    451.0  2.876580e+04  3.384479e+04  0.000000e+00  2.794581e+05
Var103   1487.0  1.878278e+01  8.556309e+01  0.000000e+00  2.002000e+03
Var104    820.0  1.007890e+02  3.797668e+02  0.000000e+00  1.015200e+04
Var105    820.0  6.719268e+01  2.531778e+02  0.000000e+00  6.768000e+03
Var106   1579.0  3.816413e+04  1.600596e+05  0.000000e+00  2.274345e+06
Var107   1487.0  5.086079e+00  5.212172e+01  0.000000e+00  1.932000e+03
Var108    702.0  1.937795e+05  5.178178e+05  0.000000e+00  7.257600e+06
Var109  42770.0  6.088866e+01  1.412492e+02  0.000000e+00  7.456000e+03
Var110    702.0  6.683761e+00  2.708837e+00  6.000000e+00  3.000000e+01
Var111   1129.0  2.848242e+05  4.972656e+05  0.000000e+00  3.628806e+06
Var112  44991.0  6.622107e+01  1.576377e+02  0.000000e+00  1.035200e+04
Var113  50000.0 -1.532786e+05  7.613730e+05 -9.803600e+06  9.932480e+06
Var114   1241.0  6.081326e+05  9.320570e+05  0.000000e+00  4.493460e+06
Var115    820.0  3.774512e+01  1.947455e+02  0.000000e+00  5.337000e+03
Var116    702.0  6.410256e-02  4.341279e-01  0.000000e+00  3.000000e+00
Var117   1579.0  1.298373e+05  2.887647e+05  0.000000e+00  2.073600e+06
Var118    171.0  3.000000e+00  0.000000e+00  3.000000e+00  3.000000e+00
Var119  44471.0  9.161122e+02  2.165433e+03  0.000000e+00  1.050600e+05
Var120   1487.0  3.164223e+01  1.227964e+02  0.000000e+00  2.502000e+03
Var121    702.0  6.951567e+00  3.076700e+01  0.000000e+00  6.720000e+02
Var122   1241.0  4.351330e-02  3.785054e-01  0.000000e+00  6.000000e+00
Var123  44991.0  6.018804e+01  2.215513e+02  0.000000e+00  1.308600e+04
Var124   1579.0  2.230791e+05  7.444241e+05  0.000000e+00  9.676800e+06
Var125  44461.0  2.788763e+04  9.012838e+04  0.000000e+00  5.436045e+06
Var126  36080.0 -5.538803e-01  2.253210e+01 -3.200000e+01  6.800000e+01
Var127   1083.0  2.809234e+01  1.243525e+02  0.000000e+00  2.480000e+03
Var128   1083.0  9.652632e+01  3.170558e+02  0.000000e+00  7.147000e+03
Var129    702.0  1.069231e+01  3.685209e+01  0.000000e+00  6.360000e+02
Var130   1240.0  4.959677e-01  1.114864e+00  0.000000e+00  3.000000e+00
Var131    702.0  4.064877e+06  2.531187e+07  0.000000e+00  4.422336e+08
Var132  44991.0  3.524616e+00  9.994878e+00  0.000000e+00  1.840000e+02
Var133  44991.0  2.273572e+06  2.438600e+06  0.000000e+00  1.500990e+07
Var134  44991.0  4.373404e+05  6.043415e+05  0.000000e+00  5.735340e+06
Var135   1579.0  1.999204e+02  1.325355e+02  0.000000e+00  7.104300e+02
Var136    694.0  1.106909e+05  1.894939e+05  0.000000e+00  1.209602e+06
Var137    702.0  3.829060e+00  1.243135e+01  0.000000e+00  2.040000e+02
Var138   1579.0  1.266624e-03  5.033139e-02  0.000000e+00  2.000000e+00
Var139   1487.0  1.815414e+05  3.933583e+05  0.000000e+00  2.700560e+06
Var140  44461.0  1.381260e+03  3.990511e+03  0.000000e+00  5.205450e+05
Var142    702.0  1.128205e+00  1.970706e+00  0.000000e+00  1.200000e+01
Var143  44991.0  5.801160e-02  6.430608e-01  0.000000e+00  1.800000e+01
Var144  44471.0  1.172767e+01  1.172029e+01  0.000000e+00  8.100000e+01
Var145   1579.0  5.843825e+01  2.280952e+02  0.000000e+00  6.126000e+03
Var146   1487.0  2.781439e+00  7.884085e+00  0.000000e+00  9.600000e+01
Var147   1487.0  1.701412e+00  1.484652e+00  0.000000e+00  8.000000e+00
Var148   1487.0  1.404869e+02  6.333673e+02  0.000000e+00  1.880800e+04
Var149  42770.0  2.949208e+05  6.568946e+05  0.000000e+00  1.693440e+07
Var150   1579.0  1.576876e+05  4.136112e+05  0.000000e+00  6.048000e+06
Var151    847.0  1.106021e+01  5.304323e+01  0.000000e+00  1.200000e+03
Var152   1579.0  8.314123e+00  9.095334e+00  0.000000e+00  6.600000e+01
Var153  44991.0  6.181967e+06  4.348926e+06  0.000000e+00  1.390780e+07
Var154    702.0  1.538221e+06  2.280224e+06  0.000000e+00  1.504856e+07
Var155   1579.0  8.011400e-01  3.042950e+00  0.000000e+00  3.500000e+01
Var156    694.0  1.694726e+02  5.446865e+02  0.000000e+00  8.050000e+03
Var157   1129.0  3.307352e+01  1.875255e+02  0.000000e+00  5.440000e+03
Var158    873.0  1.896907e+00  6.325709e+00  0.000000e+00  8.700000e+01
Var159   1241.0  4.713940e+00  1.102729e+01  0.000000e+00  9.900000e+01
Var160  44991.0  3.880301e+01  9.949715e+01  0.000000e+00  4.862000e+03
Var161   1579.0  3.374288e+00  8.579672e+00  0.000000e+00  8.100000e+01
Var162   1241.0  3.360168e+05  9.731987e+05  0.000000e+00  1.088640e+07
Var163  44991.0  4.860780e+05  8.488638e+05  0.000000e+00  1.451520e+07
Var164   1579.0  1.753642e+00  8.104872e+00  0.000000e+00  1.380000e+02
Var165    873.0  2.884236e+04  1.157869e+05  0.000000e+00  1.209600e+06
Var166   1487.0  2.255346e+01  9.621126e+01  0.000000e+00  2.261000e+03
Var168    702.0  3.329386e+02  1.028792e+02  0.000000e+00  1.270480e+03
Var170   1241.0  3.041096e+00  2.792174e+01  0.000000e+00  9.570000e+02
Var171   1083.0  3.674517e+05  6.042377e+05  0.000000e+00  5.443200e+06
Var172   1487.0  9.744452e+00  1.039732e+01  0.000000e+00  1.190000e+02
Var173  44991.0  6.845814e-03  1.325030e-01  0.000000e+00  6.000000e+00
Var174   1579.0  7.044965e+00  3.618611e+01  0.000000e+00  1.156000e+03
Var176   1240.0  4.716129e+00  3.100225e+01  0.000000e+00  8.920000e+02
Var177   1241.0  6.188884e+05  1.306030e+06  0.000000e+00  8.554350e+06
Var178    646.0  1.668731e+01  5.901663e+01  0.000000e+00  1.345000e+03
Var179   1579.0  3.138062e+00  2.820604e+01  0.000000e+00  8.900000e+02
Var180    702.0  3.776755e+06  3.785696e+06  0.000000e+00  1.428483e+07
Var181  44991.0  6.114556e-01  2.495681e+00  0.000000e+00  4.900000e+01
Var182   1579.0  1.416638e+06  2.279786e+06  0.000000e+00  1.199478e+07
Var183   1241.0  7.777380e+04  2.016188e+05  0.000000e+00  3.048400e+06
Var184   1241.0  8.460919e+00  4.697378e+01  0.000000e+00  1.200000e+03
Var186    702.0  3.299145e+00  8.781967e+00  0.000000e+00  1.020000e+02
Var187    702.0  1.654416e+01  6.022303e+01  0.000000e+00  9.100000e+02
Var188   1241.0  1.673685e+02  1.139801e+02 -6.420000e+00  6.286200e+02
Var189  21022.0  2.701421e+02  8.670769e+01  6.000000e+00  6.420000e+02
Var190    333.0  2.200705e+04  2.908515e+04  0.000000e+00  2.304270e+05

In [6]:
# Categorical Feature Statistics
cat_stats

                                    value  count    pct
column    rank
Appetency 1                            -1  49110  98.22
          2                             1    890   1.78
Var191    1                          <NA>  48917  97.83
          2                          r__I   1083   2.17
Var192    1                    qFpmfo8zhV    385   0.77
          2                    DHeq9ayfAo    384   0.77
          3                    zKnr4RXktW    380   0.76
          4                    8I1r4RXXnK    379   0.76
          5                    HYTrjIK12c    379   0.76
Var193    1                          RO12  35964  71.93
          2                       2Knk1KF   7271  14.54
          3                       AERks4l   2243   4.49
          4                    g62hiBSaKg    580   1.16
          5                    e6CkoqApVR    524   1.05
Var194    1                          <NA>  37216  74.43
          2                          SEuy  12567  25.13
          3                          lvza    176   0.35
          4                          CTUH     41   0.08
Var195    1                          taul  47958  95.92
          2                    LfvqpCtLOY    866   1.73
          3              CiJDdr4TQ0rGERIS    544   1.09
          4                          ev6I    179   0.36
          5                       CuXi4je    159   0.32
Var196    1                          1K8T  49550  99.10
          2                          z3mO    432   0.86
          3                          JA1C     17   0.03
          4                          mKeq      1   0.00
Var197    1                          0Xwj   4629   9.26
          2                          lK27   4470   8.94
          3                          TyGl   4185   8.37
          4                          487l   3577   7.15
          5                          JLbT   2978   5.96
Var198    1                       fhk21Ss   4441   8.88
          2                       PHNvXy8   1150   2.30
          3                       iJzviRg    776   1.55
          4                       9GJGgoz    748   1.50
          5                       6CXYbuk    573   1.15
Var199    1                       r83_sZi    955   1.91
          2                    _jTP8ioIlJ    920   1.84
          3                       FoJylxy    762   1.52
          4                    76j2P_OLn0    652   1.30
          5                    glRBFJT8NN    597   1.19
Var200    1                          <NA>  25408  50.82
          2                       yP09M03     73   0.15
          3                       Uw6SDm8     48   0.10
          4                       Ipi9M03     45   0.09
          5                       EvCZGt8     34   0.07
Var201    1                          <NA>  37217  74.43
          2                          smXZ  12777  25.55
          3                          6dX3      6   0.01
Var202    1                          nyZz    198   0.40
          2                          VNjO    138   0.28
          3                          85IW    130   0.26
          4                          rlx_    128   0.26
          5                          gMVu    121   0.24
Var203    1                          9_Y1  45233  90.47
          2                          HLqf   3168   6.34
          3                          F3hy   1451   2.90
          4                          <NA>    143   0.29
          5                          dgxZ      4   0.01
Var204    1                          RVjC   1819   3.64
          2                          k13i   1658   3.32
          3                          m_h1   1289   2.58
          4                          7WNq   1096   2.19
          5                          SkZj   1091   2.18
Var205    1                          VpdQ  31962  63.92
          2                          09_Q  11574  23.15
          3                       sJzTlal   4530   9.06
          4                          <NA>   1934   3.87
Var206    1                          IYzP  17274  34.55
          2                          zm5i   6435  12.87
          3                          <NA>   5529  11.06
          4                          sYC_   4003   8.01
          5                          haYg   2901   5.80
Var207    1                    me75fM6ugJ  35079  70.16
          2           7M47J5GA0pTYIFxg5uy   6889  13.78
          3     DHn_WUyBhW_whjA88g9bvA64_   3503   7.01
          4                          Kxdu   1942   3.88
          5                    NKv3VA1BpP   1268   2.54
Var208    1                          kIsH  46022  92.04
          2                          sBgB   3835   7.67
          3                          <NA>    143   0.29
Var210    1                          uKAI  47570  95.14
          2                          g5HH   1527   3.05
          3                          7A3j    510   1.02
          4                          oT7d    174   0.35
          5                          DM_V    151   0.30
Var211    1                          L84s  40299  80.60
          2                          Mtgm   9701  19.40
Var212    1                       NhsEn4L  29303  58.61
          2                 XfqtO3UdzaXh_   6433  12.87
          3                          CrNX   2992   5.98
          4                       Ie_5MZs   1450   2.90
          5                    FMSzZ91zL2   1435   2.87
Var213    1                          <NA>  48871  97.74
          2                          KdSa   1129   2.26
Var214    1                          <NA>  25408  50.82
          2                       5zARyjR     73   0.15
          3                       PXYoFMh     48   0.10
          4                       5zA8Zov     45   0.09
          5                       PXYT2rL     34   0.07
Var215    1                          <NA>  49306  98.61
          2                          eGzu    694   1.39
Var216    1                       mAjbk_S   4937   9.87
          2                       mAja5EA   4160   8.32
          3                       kZJtVhC   3390   6.78
          4                       XTbPUYD   3077   6.15
          5                       beK4AFX   1903   3.81
Var217    1                          <NA>    703   1.41
          2                          gvA6    283   0.57
          3                          5smi    230   0.46
          4                          A1VJ    205   0.41
          5                          bru6    197   0.39
Var218    1                          cJvF  25319  50.64
          2                          UYBR  23978  47.96
          3                          <NA>    703   1.41
Var219    1                          FzaX  40304  80.61
          2                          <NA>   5211  10.42
          3                       AU8pNoi   1109   2.22
          4                          qxDb   1088   2.18
          5                          OFWH    834   1.67
Var220    1                       4UxGlow   4441   8.88
          2                       UF16siJ   1150   2.30
          3                       ch2oGfM    776   1.55
          4                       Tvpip6Z    748   1.50
          5                       ROeipLp    573   1.15
Var221    1                          oslk  37009  74.02
          2                          zCkv   6199  12.40
          3                       d0EEeJi   3060   6.12
          4                       QKW8DRm   1664   3.33
          5                       Al6ZaUT   1662   3.32
Var222    1                       catzS2D   4441   8.88
          2                       APgdzOv   1150   2.30
          3                       P6pu4Vl    776   1.55
          4                       hHJsvbM    748   1.50
          5                       K2SqEo9    573   1.15
Var223    1                    LM8l689qOp  36608  73.22
          2                    jySVZNlOJy   5995  11.99
          3                          <NA>   5211  10.42
          4                          M_8D   2022   4.04
          5                       bCPvVye    164   0.33
Var224    1                          <NA>  49180  98.36
          2                          4n2X    820   1.64
Var225    1                          <NA>  26144  52.29
          2                          ELof  11072  22.14
          3                          kG3k  10429  20.86
          4                          xG3x   2355   4.71
Var226    1                          FSa2   8031  16.06
          2                          Qu4f   4832   9.66
          3                          WqMG   4176   8.35
          4                          szEZ   2956   5.91
          5                          7P5s   2803   5.61
Var227    1                          RAYp  35156  70.31
          2                          ZI9m   6153  12.31
          3                          6fzt   3426   6.85
          4                       02N6s8f   2342   4.68
          5                       nIGXDli   2280   4.56
Var228    1                 F2FyR07IdsN7I  32703  65.41
          2                       55YFVY9   4354   8.71
          3                 ib5G6X1eUxUn6   2672   5.34
          4              R4y5gQQWY8OodqDV   1601   3.20
          5                 xwM2aC7IdeMC0   1477   2.95
Var229    1                          <NA>  28432  56.86
          2                          am7c  11689  23.38
          3                          mj86   9804  19.61
          4                          sk2h     38   0.08
          5                          oJmt     37   0.07

In [7]:
# Target Distribution
target_df

           count    pct
Appetency
-1         49110  98.22
 1           890   1.78

## Task Curation

In [8]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=3, n_splits=3, test_size=None

In [9]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [10]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to kdd_cup_09_appetency/019d7368-96e4-777a-bfbb-4fcb8602465c

019d7368-96e4-777a-bfbb-4fcb8602465c
980a8a08d61d926cb34ecc188f4e5e91e10af16e10dfaf41604a528e03b29b56