### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
        unique_name="delivery_eta_1m",
    version_from_unique_name="delivery_eta",
    version_comment="""
We randomly sub-sample the train to 1 million and test data 250k rows. We follow TabReD and use random sub-sampling. The idea behind this instead of a time-based subsampling is to keep data from various time periods and model the distribution shift across the full time horizon.
""",
    # Same as delivery_eta.ipynb
    dataset_year="2024",
    domain_str="industry & manufacturing",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/datasets/pcovkrd84mejm/delivery-eta",
    download_description="""
We download the data from Kaggle.

kaggle datasets download -d pcovkrd84mejm/delivery-eta -f delivery_eta.parquet && unzip delivery_eta.parquet.zip && rm delivery_eta.parquet.zip && mkdir -p local-data-warehouse/delivery_eta && mv delivery_eta.parquet local-data-warehouse/delivery_eta/
""",
    # References
    academic_reference_bibtex="""@inproceedings{rubachev2025tabred,
  title={TabReD: Analyzing Pitfalls and Filling the Gaps in Tabular Deep Learning Benchmarks},
  author={Rubachev, Ivan and Kartashev, Nikolay and Gorishniy, Yury and Babenko, Artem},
  booktitle={The Thirteenth International Conference on Learning Representations},
  year={2025},
}
""",
    academic_reference_bibtex_key="rubachev2025tabred",
    license="CC-BY-NC-SA-4.0",
    data_tags=["Non-IID", "Temporal", "Anonymized"],
    curation_comments="""
We start with data from TabRed, which already comes preprocessed.

- We drop a duplicated column `cat_2` in the preprocessing.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="delivery_eta_minutes",
    problem_type="regression",
    objective_metric_name="rmse",
    time_on="timestamp",
)

## Preprocessing

In [2]:
import pandas as pd
import numpy as np

df = pd.read_parquet(dataset_mold.path / "delivery_eta.parquet")
print("Loaded data shape:", df.shape)

df["timestamp"] = pd.to_datetime(df["timestamp"])

# Following TabRed
df = df[df["delivery_eta_minutes"] >= 1.0]

# We take all bin + cat as Category
cat_cols = [c for c in df.columns if c.startswith("cat") or c.startswith("bin")]
df[cat_cols] = df[cat_cols].astype("category")

df["delivery_eta_minutes"] = np.log(df["delivery_eta_minutes"])

df = df.drop(columns=["cat_2"])

df = df.sort_values(by="timestamp").reset_index(drop=True)

Loaded data shape: (17044043, 227)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
    # We checked before and neither exists. If these checks are true, this can take ca. 20 minutes.
    duplicate_column_check=False,
    duplicate_row_check=False,
)

#### Dataset Overview
Rows: 16,658,051
Columns: 226
Use sampling: True (sample size: 1,665,805)
Get missing and unique counts per column...

missing/unique per-col:   0%|          | 0/226 [00:00<?, ?it/s]

Get example values per column...

examples per-col:   0%|          | 0/226 [00:00<?, ?it/s]

Get numeric feature statistics...

numeric stats:   0%|          | 0/222 [00:00<?, ?it/s]

Get cat stats...

cat stats:   0%|          | 0/4 [00:00<?, ?it/s]

Get target stats...

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,num_0,num_1,num_2,num_3,num_4,num_5,num_6,num_7,num_8,num_9,num_10,num_11,num_12,num_13,num_14,num_15,num_16,num_17,num_18,num_19,num_20,num_21,num_22,num_23,num_24,num_25,num_26,num_27,num_28,num_29,num_30,num_31,num_32,num_33,num_34,num_35,num_36,num_37,num_38,num_39,num_40,num_41,num_42,num_43,num_44,num_45,num_46,num_47,num_48,num_49,num_50,num_51,num_52,num_53,num_54,num_55,num_56,num_57,num_58,num_59,num_60,num_61,num_62,num_63,num_64,num_65,num_66,num_67,num_68,num_69,num_70,num_71,num_72,num_73,num_74,num_75,num_76,num_77,num_78,num_79,num_80,num_81,num_82,num_83,num_84,num_85,num_86,num_87,num_88,num_89,num_90,num_91,num_92,num_93,num_94,num_95,num_96,num_97,num_98,num_99,num_100,num_101,num_102,num_103,num_104,num_105,num_106,num_107,num_108,num_109,num_110,num_111,num_112,num_113,num_114,num_115,num_116,num_117,num_118,num_119,num_120,num_121,num_122,num_123,num_124,num_125,num_126,num_127,num_128,num_129,num_130,num_131,num_132,num_133,num_134,num_135,num_136,num_137,num_138,num_139,num_140,num_141,num_142,num_143,num_144,num_145,num_146,num_147,num_148,num_149,num_150,num_151,num_152,num_153,num_154,num_155,num_156,num_157,num_158,num_159,num_160,num_161,num_162,num_163,num_164,num_165,num_166,num_167,num_168,num_169,num_170,num_171,num_172,num_173,num_174,num_175,num_176,num_177,num_178,num_179,num_180,num_181,num_182,num_183,num_184,num_185,num_186,num_187,num_188,num_189,num_190,num_191,num_192,num_193,num_194,num_195,num_196,num_197,num_198,num_199,num_200,num_201,num_202,num_203,num_204,num_205,num_206,num_207,num_208,num_209,num_210,num_211,num_212,num_213,num_214,num_215,num_216,num_217,num_218,num_219,num_220,bin_0,cat_0,cat_1,timestamp,delivery_eta_minutes
0,2.877762,4.265921,4.585457,5.199337,2.851106,3.016480,3.093599,3.267431,0.980583,0.578792,1.097845,0.175650,-1.413164,-0.597484,-0.063342,0.459557,1.168894,-3.991260,-1.583624,-0.212510,0.682612,2.183395,-1.104712,-0.448915,0.062745,0.525253,1.804915,2.527374,0.689366,0.001911,2.581163,0.422483,2.629071,-2.395936,2.479963,2.493774,-0.000763,2.575484,0.39656,2.586054,-1.901089,2.905472,1.505632,-0.001903,2.951403,2.935855,2.914115,-2.727752,2.984438,2.363226,2.969794,2.915265,2.767030,2.775644,-2.721100,2.479552,0.974071,0.000016,2.268113,2.184755,2.333133,-2.029513,2.742097,1.931054,-0.002733,2.409729,2.921391,2.422208,-2.125637,2.456904,2.246824,-0.0001,2.511791,0.373591,2.575484,-2.456904,-1.931008,-0.536771,2.173468,0.986974,1.391445,-1.384628,-1.430912,-1.000385,0.418440,-1.169657,-1.54317,-0.277948,2.085325,0.767376,1.704694,-1.931008,1.271819,2.413308,0.982880,2.349671,-1.926403,2.229137,2.600504,0.984562,2.815474,0.003764,0.985383,0.983507,0.981740,0.983960,0.736603,0.132113,0.132113,0.839800,-1.552174,NaN,NaN,NaN,NaN,NaN,-0.687781,NaN,NaN,NaN,NaN,-0.688889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,473,504,2023-10-20 00:10:02,1.766442
1,2.772052,2.747453,2.808219,2.836602,2.756302,2.747421,2.799917,2.850645,0.294473,-0.034024,0.231641,-0.196322,-1.117834,-0.445207,0.070227,0.612805,1.490137,-3.857787,-1.583470,-0.212470,0.682680,2.183839,-1.104674,-0.448893,0.062765,0.525280,1.805020,3.052712,1.146351,0.001911,3.012658,0.422483,3.089988,-2.888382,3.089935,2.651732,-0.000763,3.023233,0.39656,3.089935,-2.575483,3.096727,1.538286,3.089971,3.096185,3.164381,3.180689,-3.127388,3.092278,2.483250,3.092885,3.092528,3.094316,2.728135,-3.114617,3.048729,0.999279,0.000016,2.781789,0.434861,2.813568,-2.461204,2.988676,2.066513,-0.002733,2.805792,2.800105,2.594237,-2.416225,3.058730,2.412569,-0.0001,3.009585,0.373591,3.089935,-2.877846,-1.931008,-2.714187,-2.776463,-1.227636,-2.536456,-1.384628,-1.880656,-1.560835,-0.260205,-1.703172,-1.54317,-2.500358,-2.614430,-1.250491,-2.373946,-1.931008,-2.474909,-1.769461,-1.227569,-1.424958,-1.926403,-1.677404,-1.273537,-1.226657,-0.845930,0.003764,-1.227012,-1.227223,-1.227910,-1.227154,-1.426839,0.132113,0.132113,-1.419050,-1.552174,NaN,NaN,NaN,NaN,NaN,-0.687781,NaN,NaN,NaN,NaN,-0.688889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,349,366,2023-10-20 00:12:25,0.416515
2,2.772052,2.747453,2.808219,2.836602,2.783561,2.755170,2.805196,2.845376,-0.897794,-1.435486,-0.795323,1.011805,-1.140726,-0.458633,0.057901,0.598209,1.454522,-3.867452,-1.583484,-0.212474,0.682674,2.183799,-1.104677,-0.448895,0.062763,0.525278,1.805010,3.052712,1.146351,0.001911,3.012658,0.422483,3.089988,-2.888382,3.089935,2.651732,-0.000763,3.023233,0.39656,3.089935,-2.575483,3.096727,1.538286,3.089971,3.096185,3.164381,3.180689,-3.127388,3.092278,2.483250,3.092885,3.092528,3.094316,2.728135,-3.114617,3.048729,0.999279,0.000016,2.781789,0.434861,2.813568,-2.461204,2.988676,2.066513,-0.002733,2.805792,2.800105,2.594237,-2.416225,3.058730,2.412569,-0.0001,3.009585,0.373591,3.089935,-2.877846,-1.931008,-2.819347,-2.913364,-1.270955,-2.639926,-1.384628,-1.973861,-1.692026,-0.428944,-1.825203,-1.54317,-2.596981,-2.742465,-1.288514,-2.473775,-1.931008,-2.623518,-1.999101,-1.271499,-1.631485,-1.926403,-1.881685,-1.503648,-1.270067,-1.061147,0.003764,-1.269824,-1.270836,-1.270434,-1.270517,-1.592511,0.132113,0.132113,-1.586259,-1.552174,NaN,NaN,NaN,NaN,NaN,-0.687781,NaN,NaN,NaN,NaN,-0.688889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,349,366,2023-10-20 00:13:51,0.209721
3,2.877762,4.265921,4.585457,5.199337,2.845505,3.056999,3.160719,3.481351,0.421408,0.265056,0.667419,0.699760,-0.394040,0.105255,0.652446,1.600640,-1.049555,-3.606255,-1.582850,-0.212306,0.682957,2.185638,-1.104520,-0.448805,0.062846,0.525387,1.805442,2.527374,0.689366,0.001911,2.581163,0.422483,2.629071,-2.395936,2.479963,2.493774,-0.000763,2.575484,0.39656,2.586054,-1.901089,2.905472,1.505632,-0.001903,2.951403,2.935855,2.914115,-2.727752,2.984438,2.363226,2.969794,2.915265,2.767030,2.775644,-2.721100,2.479552,0.974071,0.000016,2.268113,2.184755,2.333133,-2.029513,2.742097,1.931054,-0.002733,2.409729,2.921391,2.422208,-2.125637,2.456904,2.246824,-0.0001,2.511791,0.373591,2.575484,-2.456904,-1.931008,-1.164963,0.767770,1.107316,-0.002127,-1.384628,-1.370932,-0.932914,0.493682,-1.115772,-1.54317,-0.925612,0.717451,0.865454,0.115014,-1.931008,0.526123,1.432410,1.103818,1.361166,-1.926403,1.451195,1.796469,1.105362,1.957481,0.003764,1.108127,1.105137,1.102604,1.105298,0.575808,0.132113,0.132113,0.667235,-1.552174,NaN,NaN,NaN,NaN,NaN,-0.687781,NaN,NaN,NaN,NaN,-0.688889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,473,504,2023-10-20 00:23:37,2.307573
4,3.119203,2.877950,2.877846,2.844991,3.101751,2.974746,2.921604,2.864496,0.625674,-0.537047,1.087211,0.977401,-0.551471,-0.035537,0.486190,1.220101,-1.339029,-3.652850,-1.583012,-0.212349,0.682885,2.185168,-1.104560,-0.448828,0.062825,0.525359,1.805331,2.529002,1.070842,0.001911,2.496661,0.422483,2.513438,-2.355289,2.456904,2.524724,-0.000763,2.524030,0.39656,2.511791,-1.880352,3.091069,1.525641,-0.001903,3.090342,3.099393,3.117773,-2.773598,3.068367,2.416732,2.501164,3.090413,2.659138,2.846465,-2.770001,2.666704,0.983724,0.000016,2.367971,0.434861,2.407584,-2.050133,2.469253,2.013983,-0.002733,2.311332,0.451469,2.413440,-2.013671,2.474382,2.325973,-0.0001,2.575146,0.373591,2.557064,-2.511791,-2.488277,-2.121198,-1.464107,1.511954,-1.925227,NaN,NaN,NaN,NaN,NaN,-2.13828,-1.927581,-1.344621,1.186145,-1.752097,-2.496063,-0.989100,0.087476,1.508482,-0.345593,-2.504506,-0.036258,0.666831,1.510498,0.373619,0.003764,1.511556,1.510090,1.508250,1.507878,NaN,-0.784548,-0.781626,NaN,-1.552174,NaN,NaN,NaN,NaN,NaN,-0.687781,NaN,NaN,NaN,NaN,-0.688889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,402,422,2023-10-20 00:23:41,1.731656

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,bin_0,category,0.0,0.00,2.0,"1.0, 0.0"
1,cat_0,category,0.0,0.00,489.0,"48, 131, 121, 79, 169, 54, 106, 13, 50, 74"
2,cat_1,category,0.0,0.00,524.0,"176, 92, 71, 53, 61, 164, 314, 21, 214, 395"
3,timestamp,datetime64[us],0.0,0.00,4547703.0,"2023-10-25 14:12:46, 2023-11-19 12:19:17, 2023-11-25 15:18:24, 2023-10-30 10:36:43, 2023-12-25 16:11:08, 2023-11-21 13:07:16, 2023-12-27 09:30:16, 2023-12-10 15:15:29, 2023-10-24 16:16:10, 2023-11-18 13:46:18"
4,num_117,float32,12844213.0,77.11,3356449.0,"-4.6937, -0.7208, -1.322, -0.5207, -0.5206, -0.7908, 0.4309, -0.1474, 0.4309, -2.3092"
5,num_118,float32,12844213.0,77.11,3259735.0,"-4.7028, -0.0767, -1.0421, 0.2876, -2.2397, 2.6693, 2.6693, 0.2877, -1.0421, -2.2661"
6,num_119,float32,12844213.0,77.11,3003544.0,"-1.1305, 0.1245, -0.7956, -0.7958, -1.6657, -0.8197, -1.1449, 2.724, 2.724, 1.0314"
7,num_120,float32,12844213.0,77.11,2999082.0,"-1.3401, 0.8403, -4.7333, 0.8404, -0.3472, -0.347, -0.2265, -1.1499, -0.5905, 2.5875"
8,num_159,float32,11316895.0,67.94,309314.0,"-0.6826, -0.7047, -0.7263, -0.7159, -0.6627, -0.7023, -0.701, -0.754, -0.7348, -0.7256"
9,num_201,float32,11318201.0,67.94,1151792.0,"0.7513, 3.0909, 3.09, 3.09, 3.0912, 3.0909, 3.0913, 0.0399, 3.0913, 3.0912"
10,num_207,float32,11317177.0,67.94,1591467.0,"1.5639, 3.0903, -0.8237, 0.7894, 3.0901, 3.0902, -0.4425, 3.0903, -1.4878, 3.09"
11,num_111,float32,10153116.0,60.95,115.0,"-1.3781, -0.6895, -0.2914, 0.0, 0.2342, 0.4321, 0.6029, 0.7513, 0.8846, 1.0104"
12,num_112,float32,10153116.0,60.95,5381760.0,"-5.1993, -0.9609, -0.9609, -0.9609, -0.9609, -0.9609, -0.9609, -0.9609, -0.9609, -0.9609"
13,num_113,float32,10153116.0,60.95,3195787.0,"-5.1993, 3.09, 3.09, 3.09, 3.09, 3.0899, 3.6281, 3.6284, 3.09, 3.1105"
14,num_114,float32,10153116.0,60.95,3004889.0,"-5.1993, 3.1424, 3.1424, 3.1424, 3.1423, 3.1423, 3.1423, 3.1422, 3.1422, 3.1422"
15,num_115,float32,10153116.0,60.95,2914733.0,"-5.1993, 2.5755, 2.4569, 2.4569, 2.4569, 2.5755, 2.4569, 3.0894, 2.4569, 3.0899"
16,num_160,float32,10118039.0,60.74,446030.0,"0.3201, 0.0474, -0.0368, -0.0903, 0.5162, -0.7993, 0.1388, 0.014, 0.5452, -0.1164"
17,num_202,float32,10118469.0,60.74,1989342.0,"0.9147, -0.4959, 0.4217, -0.8165, -0.2719, 0.64, -0.7576, 0.4054, -0.5215, 2.0308"
18,num_208,float32,10118146.0,60.74,2097506.0,"1.2033, -0.1451, -0.1639, 0.0427, 0.2037, 0.305, -0.8672, 0.8616, -0.4405, -2.0442"
19,num_81,float32,9931334.0,59.62,29.0,"-0.6425, -0.1562, -1.3846, 0.2304, 0.5599, 0.8481, 1.1117, 1.3526, 1.58, 1.7987"
20,num_82,float32,9931334.0,59.62,5280155.0,"-2.7578, -1.6615, -2.0157, -1.446, -1.6864, -2.2868, -1.9446, -1.0916, -0.9581, -2.3452"
21,num_83,float32,9931334.0,59.62,5286857.0,"-2.7648, -1.2745, -1.0174, -1.7487, -1.3046, -2.134, -2.2442, -1.3166, -1.1685, -2.2258"
22,num_84,float32,9931334.0,59.62,3589134.0,"-1.7017, -0.7383, -0.3784, -0.7452, -0.8772, -1.0518, 0.078, -0.3737, -0.9678, -1.253"
23,num_85,float32,9931334.0,59.62,4610459.0,"-2.7613, -0.4435, -0.6554, -1.3274, -0.7711, -1.5903, -1.8796, -1.1841, -1.3165, -0.882"
24,num_86,float32,9394655.0,56.40,36.0,"-0.2718, -0.5221, -0.8057, -0.0402, 0.1791, -1.1401, 0.3844, 0.585, -1.5432, 0.7731"
25,num_87,float32,9394655.0,56.40,5823920.0,"-5.1993, -1.9133, -2.9678, -0.7937, -1.9796, 0.9332, 1.9943, -0.3174, 0.1192, -2.9079"
26,num_88,float32,9394655.0,56.40,5727958.0,"-5.1993, -2.1712, -2.8537, 3.0949, -1.4768, -2.7475, 0.1566, -2.0494, 2.4309, -2.0013"
27,num_89,float32,9394655.0,56.40,3728080.0,"-1.6658, -0.5702, -0.5785, -0.9321, -1.1744, -0.7315, -0.1676, 0.355, -0.1647, 0.3071"
28,num_90,float32,9394655.0,56.40,4928627.0,"-5.1993, 1.0187, 0.6785, 0.6739, 1.1002, 1.8475, 1.8808, 2.1384, 0.068, -0.38"
29,num_106,float32,9365037.0,56.22,5002928.0,"2.0233, -5.1993, 1.7056, -1.4862, -1.6635, -0.9649, -2.1221, -2.1176, -0.7353, -1.7726"
30,num_109,float32,9364297.0,56.21,5002378.0,"2.0744, -5.1993, 1.7619, -1.4792, -1.6582, -0.9483, -2.1197, -2.1237, -0.7144, -1.0303"
31,num_76,float32,9333272.0,56.03,37.0,"-0.1397, -0.3709, -0.6196, 0.0816, 0.2887, -0.8883, 0.4865, -1.1844, 0.6816, 0.8717"
32,num_77,float32,9333272.0,56.03,5874637.0,"-5.1993, -2.108, -2.6062, 3.0978, 3.091, -3.1918, 5.1993, 1.274, -2.946, 1.7784"
33,num_78,float32,9333272.0,56.03,5760667.0,"-5.1993, -2.3193, -2.2048, -2.6335, 0.5014, 0.7449, 0.3948, -3.0467, 0.1429, 2.2943"
34,num_79,float32,9333272.0,56.03,3653947.0,"-1.6492, -0.4921, -0.5007, -1.1425, -0.664, -0.8772, -0.0661, 0.5098, -0.0629, 0.3063"
35,num_80,float32,9333272.0,56.03,4958434.0,"-5.1993, 0.8419, 1.6006, 1.5443, 1.7106, 1.5131, 0.5338, 1.4616, 1.4752, -0.0488"
36,num_91,float32,9333272.0,56.03,5.0,"0.1868, -1.1844, -1.5215, -1.931, -2.4961"
37,num_92,float32,9333272.0,56.03,5894192.0,"-5.1993, -0.948, -2.0991, -1.8142, -0.9484, -2.2893, -0.948, -0.8545, -0.948, -3.1066"
38,num_93,float32,9333272.0,56.03,5897750.0,"-5.1993, -2.2347, -1.9076, -0.9801, -0.9797, -0.9797, -0.8006, -1.9551, 0.7199, 1.7119"
39,num_94,float32,9333272.0,56.03,3655498.0,"-1.6528, -0.4921, -0.5006, -1.1434, -0.6643, -0.8774, -0.0644, 0.5092, -0.0615, 0.3072"
40,num_95,float32,9333272.0,56.03,5029330.0,"-5.1993, -0.5751, -1.395, -1.501, -1.4035, -0.9834, -0.8553, -1.722, -0.8858, -1.2611"
41,num_96,float32,9333272.0,56.03,3.0,"0.0489, -1.9264, -2.5045"
42,num_97,float32,9333272.0,56.03,5780634.0,"-3.1036, -1.3866, -1.3849, -0.4752, -1.1708, -0.6576, -0.66, -1.5224, -1.5116, -0.6553"
43,num_98,float32,9333272.0,56.03,5774149.0,"-3.1024, -1.4104, -1.4086, -1.7243, -0.4864, -0.6708, -1.1934, -0.6733, -1.5482, -1.538"
44,num_99,float32,9333272.0,56.03,3655546.0,"-1.6488, -0.495, -0.5035, -1.1437, -0.6673, -0.8788, -0.0677, 0.509, -0.064, 0.3044"
45,num_100,float32,9333272.0,56.03,4578967.0,"-3.1062, -1.1549, -0.4301, -1.7056, -0.8161, 0.1144, -0.2549, -0.1237, -0.0502, -0.3629"
46,num_101,float32,9333272.0,56.03,1.0,0.0038
47,num_102,float32,9333272.0,56.03,3655770.0,"-1.6484, -0.4933, -0.5023, -1.1433, -0.6673, -0.8799, -0.0665, 0.5075, -0.0633, 0.3045"
48,num_103,float32,9333272.0,56.03,3655766.0,"-1.651, -0.4921, -0.5007, -1.1436, -0.6649, -0.8789, -0.0665, 0.508, -0.0638, 0.3036"
49,num_104,float32,9333272.0,56.03,3655776.0,"-1.6502, -0.495, -0.5045, -1.1448, -0.6686, -0.8813, -0.0691, 0.5059, -0.0658, 0.3022"
50,num_105,float32,9333272.0,56.03,3655452.0,"-1.6491, -0.4944, -0.5027, -1.1441, -0.6665, -0.8793, -0.0652, 0.5068, -0.0615, 0.3047"
51,num_107,float32,9237751.0,55.46,1376.0,"0.1321, -0.7845, 0.6549, 1.0146, -0.2471, 0.4225, 1.2896, -0.4052, -0.1094, 0.8502"
52,num_108,float32,9237751.0,55.46,1374.0,"0.1321, -0.7816, 0.6549, 1.0146, -0.2482, 0.4211, 1.2896, -0.4058, -0.1096, 0.8505"
53,num_110,float32,9237751.0,55.46,113.0,"-0.8589, -0.4225, -1.5522, -0.1005, 0.1537, 0.3655, 0.5438, 0.7023, 0.8445, 0.9734"
54,num_116,float32,9237751.0,55.46,53.0,"-0.6878, 0.2809, 0.7988, 1.1644, 1.4497, 1.6879, 1.8878, 2.0653, 2.2199, 2.3652"
55,num_121,float32,9237751.0,55.46,1287.0,"-0.6889, 1.086, 0.6428, 1.9829, 0.4011, 0.2596, 0.171, 1.4615, 0.8254, 0.1127"
56,num_165,float32,4485467.0,26.93,987400.0,"-1.481, -1.4509, -1.4668, -1.4518, -1.4328, -1.4452, -1.4658, -1.4647, -1.4206, -1.4728"
57,num_213,float32,4486023.0,26.93,3418165.0,"0.9877, 3.0907, 3.0907, 3.0906, 3.0907, 3.0906, 3.0907, 3.0906, 3.0906, 3.0904"
58,num_157,float32,3224187.0,19.36,513969.0,"-0.2682, -0.4095, -0.2411, -0.5743, -0.5602, -0.5114, -0.0851, -0.5917, -0.2779, -0.6698"
59,num_199,float32,3224357.0,19.36,4076490.0,"0.5109, -0.7175, 0.4801, 0.1524, 1.1266, -0.0447, 0.2105, -0.9121, 0.2311, 0.5566"
60,num_205,float32,3224248.0,19.36,4266141.0,"0.6585, -0.5568, 0.7138, -0.3815, -0.0482, -0.603, 1.5914, -1.4351, -0.0221, -0.6753"
61,num_214,float32,2834684.0,17.02,3668723.0,"0.5953, 0.8456, 0.293, 0.9425, -0.1116, -0.1686, 0.6866, -0.0967, -1.4465, 1.1075"
62,num_166,float32,2834350.0,17.01,867904.0,"-0.3292, -0.3155, 0.5879, -0.4256, 0.8677, 0.1049, 0.3921, -0.6407, -0.2377, -0.3498"
63,num_155,float32,1857625.0,11.15,374722.0,"-2.094, -2.0817, -2.1358, -2.0311, -2.0745, -2.1138, -2.0866, -2.0915, -2.108, -2.0793"
64,num_197,float32,1857768.0,11.15,4398543.0,"0.4733, 3.0902, 3.0908, 3.0923, 3.0907, 3.0909, 3.0901, 3.0909, 3.0917, 3.0911"
65,num_203,float32,1857686.0,11.15,4557469.0,"0.586, 3.0933, -0.8871, 3.0904, 0.2559, -0.3684, 3.1044, 1.5353, 3.0931, -0.2891"
66,num_156,float32,1705147.0,10.24,371030.0,"-2.5764, -2.6509, -2.696, -2.3866, -2.4742, -2.3655, -2.5122, -2.4558, -2.5428, -2.3454"
67,num_198,float32,1705280.0,10.24,4442859.0,"0.4488, 0.4486, 0.4485, 3.09, 3.09, 3.0899, 3.09, 3.09, 3.09, 3.09"
68,num_204,float32,1705217.0,10.24,4594548.0,"0.551, 0.5509, 0.5509, 0.5509, -0.9731, -0.4558, -0.0025, -0.2994, -0.2737, 0.3295"
69,num_219,float32,1540123.0,9.25,4817374.0,"3.0901, 3.09, 3.09, 3.09, 3.09, 3.0901, 3.09, 3.0902, 3.09, 3.0901"
70,num_177,float32,1526813.0,9.17,4882585.0,"3.09, 3.09, 3.09, 3.09, 3.09, 3.0901, 3.0901, 3.0901, 3.09, 3.0899"
71,num_158,float32,1438498.0,8.64,385838.0,"-0.0394, -0.3606, -0.241, -0.5796, -0.8536, -0.4964, -0.6853, -0.3089, -0.8413, -0.4529"
72,num_200,float32,1438620.0,8.64,4502431.0,"0.3203, 3.0902, 3.09, 3.0906, 3.0913, 3.0913, 3.0904, 3.0902, 3.0907, 3.0905"
73,num_206,float32,1438547.0,8.64,4642108.0,"0.3762, -1.3977, -0.1364, -0.6369, 0.4977, -0.1231, -0.6929, 1.2633, 0.1205, -0.2445"
74,num_132,float32,1430878.0,8.59,1268017.0,"-2.1652, -2.1201, -2.1048, -2.0854, -2.0846, -2.1551, -2.5229, -2.057, -2.0843, -2.1318"
75,num_220,float32,1227248.0,7.37,4947647.0,"1.7913, -0.1046, 3.1122, 1.1205, 0.5915, 1.7517, 0.4217, 1.0438, 1.842, -0.1461"
76,num_178,float32,1206805.0,7.24,4972463.0,"0.9446, 0.4894, 0.216, -0.7547, -0.8455, 0.2382, 3.0938, 0.5781, -1.8353, -0.8144"
77,num_133,float32,1096454.0,6.58,1126201.0,"-0.3647, -0.1021, 0.0507, -0.1875, -0.3164, -0.1885, 0.3497, 0.0069, -0.0704, 0.3106"
78,num_163,float32,887108.0,5.33,793130.0,"-0.1112, -0.7352, -1.0086, -0.8315, -0.2035, -1.0612, -0.7903, -0.853, -1.3196, -0.774"
79,num_211,float32,887177.0,5.33,4172168.0,"0.2539, 0.0267, -0.2283, -0.2917, 0.0446, 0.7927, 0.3861, -0.2628, 0.5807, -0.3182"
80,num_215,float32,829826.0,4.98,4925599.0,"3.09, 3.09, 3.0899, 3.09, 3.09, 3.09, 3.09, 3.0901, 3.0901, 3.0901"
81,num_216,float32,803654.0,4.82,4937120.0,"3.0899, 3.09, 3.09, -5.1993, 3.0902, 3.0905, 3.0901, 3.0904, 3.0904, 3.09"
82,num_173,float32,792685.0,4.76,4819536.0,"0.0237, -0.4813, -0.9254, 0.1855, -0.771, 3.099, 3.0959, 0.2436, -0.514, 3.0902"
83,num_161,float32,774775.0,4.65,433526.0,"-2.8778, -2.8373, -3.0542, -2.8227, -2.8009, -2.7696, -2.8126, -2.8638, -2.8309, -2.7858"
84,num_209,float32,774873.0,4.65,4261093.0,"0.2799, 3.0907, 3.0917, -1.0988, 3.0904, 3.0902, -0.43, 3.0902, 0.7522, 0.4986"
85,num_174,float32,770213.0,4.62,4826848.0,"3.0899, 3.09, 3.09, 3.09, 3.09, 3.0912, -0.6035, 0.0258, 3.091, 3.0922"
86,num_179,float32,753800.0,4.53,4773748.0,"0.0393, -1.1051, 0.4341, 0.7689, 3.1027, 0.424, 0.4277, 1.4307, 0.6699, 0.3752"
87,num_218,float32,748545.0,4.49,4973968.0,"3.09, 3.09, 3.09, 3.09, 3.0899, 3.09, 3.0901, 3.09, 3.0901, 3.0901"
88,num_162,float32,742646.0,4.46,425841.0,"-3.03, -3.1296, -3.1997, -3.1513, -3.0587, -3.0441, -2.9911, -3.1093, -3.0902, -3.0165"
89,num_210,float32,742736.0,4.46,4250902.0,"0.2672, 3.09, 0.2671, 3.0899, 3.09, 3.09, 3.09, 0.2669, 3.09, 3.09"
90,num_180,float32,733518.0,4.40,4780669.0,"3.0899, 3.09, 3.09, 3.09, 0.0432, 3.09, 3.0912, 3.09, 3.0925, 3.0927"
91,num_217,float32,715476.0,4.30,5252436.0,"3.0902, 3.0902, 3.0903, 3.0902, 3.09, 3.09, 3.0901, 3.0901, 3.0909, 3.0903"
92,num_176,float32,711801.0,4.27,4880008.0,"3.09, 3.09, 3.09, 3.09, 3.0902, 3.0901, 3.0901, 3.09, 3.0901, 3.0902"
93,num_134,float32,709800.0,4.26,442144.0,"-0.5911, -0.9754, -0.7368, -0.1532, -0.1785, -0.1977, -0.5682, -0.751, -1.1889, -0.6369"
94,num_167,float32,709800.0,4.26,4935773.0,"3.09, 3.0901, 3.09, 3.09, 3.0901, 3.0902, 3.09, 3.0901, 3.09, 3.0902"
95,num_175,float32,698876.0,4.20,5144736.0,"0.6413, 0.0181, 0.9489, 0.8805, 1.4758, 0.6654, 0.7023, 1.5814, -0.073, -0.8475"
96,num_135,float32,693534.0,4.16,434602.0,"-4.6867, -5.1993, -4.5946, -0.2614, -0.5775, -0.7361, -0.478, -0.9575, -4.7628, -4.6211"
97,num_168,float32,693534.0,4.16,4950603.0,"3.0899, 3.09, 3.09, 3.09, 3.0901, 3.0902, 3.0902, 3.0903, 3.0901, 3.0901"
98,num_182,float32,692213.0,4.16,4861260.0,"3.09, 3.09, 3.0899, 3.09, 3.09, 3.09, 3.09, 3.0901, 3.0901, 3.0901"
99,num_164,float32,670067.0,4.02,421627.0,"-0.4172, -0.5489, -0.5199, -0.7946, -0.5493, -0.2546, -0.6425, -0.1951, -0.6458, -0.3918"
100,num_212,float32,670128.0,4.02,4224825.0,"0.1802, -0.3308, 0.3344, 0.4688, 0.2187, 0.3538, 0.1294, -0.3907, 0.512, 0.4819"
101,num_137,float32,651042.0,3.91,424700.0,"-0.3348, -0.4954, -0.4459, -0.0997, -0.5109, -0.3031, -0.4576, -0.6968, -0.8591, -0.823"
102,num_170,float32,651042.0,3.91,5002688.0,"3.09, 3.0899, 3.09, 3.09, 3.09, 3.09, 3.09, 3.0901, 3.0901, 3.0901"
103,num_184,float32,639050.0,3.84,4766876.0,"3.0923, 0.2135, 0.0952, 0.0563, 0.9885, 0.5293, 3.0949, 0.1622, 0.0925, 0.2659"
104,num_128,float32,628052.0,3.77,447896.0,"-0.5342, -0.6645, -0.5961, -0.149, -0.163, -0.4531, -0.5736, -0.4181, -0.4098, -0.6297"
105,num_140,float32,627267.0,3.77,430567.0,"-0.4738, -0.4558, -0.4952, -1.0023, -0.3449, -0.5264, -0.4214, -0.6635, -0.3955, -0.5961"
106,num_141,float32,616971.0,3.70,421036.0,"-0.4499, -0.6546, -0.421, -0.7285, -0.6243, -0.3718, -4.7727, -0.2502, -4.823, 0.0917"
107,num_139,float32,614827.0,3.69,1955950.0,"3.0904, -0.915, 3.09, 3.0911, -0.6662, 3.0918, -0.3918, 3.0916, -0.6502, 0.307"
108,num_172,float32,614827.0,3.69,5123007.0,"1.4503, 0.3401, 1.3027, 0.6926, -0.0476, -5.1993, -0.2167, -0.205, 0.3679, 0.1314"
109,num_181,float32,615467.0,3.69,4998550.0,"3.09, 3.09, 3.09, 3.0901, 3.0901, 3.09, 3.09, 3.0901, 3.0901, 3.09"
110,num_183,float32,612231.0,3.68,4503148.0,"3.0901, 3.0901, 3.09, 3.0901, 3.09, 3.09, 3.0903, 3.0904, 3.0901, 3.09"
111,num_129,float32,610931.0,3.67,440453.0,"-0.0758, -4.6962, -4.7093, -0.2771, -0.8298, -0.4107, -0.8421, -0.4209, -0.6654, -0.3016"
112,num_143,float32,605936.0,3.64,412077.0,"-0.2468, -0.4018, -0.2499, -0.3871, -0.7436, -0.6173, -0.6241, -0.4179, -0.4267, -0.2758"
113,num_136,float32,597907.0,3.59,1085645.0,"3.0902, -0.4168, -0.4731, -0.4427, 0.0174, -0.6859, -0.5478, -0.3862, -0.7821, -0.6739"
114,num_169,float32,597907.0,3.59,5154356.0,"3.0915, 3.0916, 0.067, -1.7392, 0.5429, 3.0906, 0.2121, -1.0601, 0.1162, 3.0905"
115,num_138,float32,595726.0,3.58,2255511.0,"-0.1612, -0.2085, -0.755, -0.145, -0.0878, -0.9684, -0.3012, -0.0651, 0.4342, 0.3048"
116,num_171,float32,595726.0,3.58,5037774.0,"3.09, 3.09, 3.09, 3.09, 3.09, 3.0901, 3.0899, 3.0901, 3.0901, 3.0901"
117,num_130,float32,585045.0,3.51,910012.0,"-0.7322, -0.654, -0.3702, -0.8169, -0.6585, -0.0571, -0.1768, -0.5862, -0.7939, -1.222"
118,num_145,float32,582110.0,3.49,1976707.0,"-0.8367, -1.4461, 3.0903, -0.3356, -1.2582, -0.3906, -0.5971, -0.2655, 3.0945, 0.1909"
119,num_142,float32,572526.0,3.44,1089897.0,"-0.6357, -0.8493, -0.1517, -0.2088, -0.9791, -0.4616, 3.0909, -0.988, -0.7895, -0.3402"
120,num_144,float32,571077.0,3.43,2268244.0,"3.0911, 3.0903, 3.0903, 3.0904, 3.0902, 3.0913, 3.0901, 3.0912, 0.2435, 3.0902"
121,num_131,float32,563027.0,3.38,433749.0,"-0.4473, -0.6898, -0.6696, -0.4298, -0.5366, -0.6469, -0.5637, -0.8469, -0.1416, -0.6098"
122,num_122,float32,459249.0,2.76,572768.0,"-0.2113, -0.5, -0.6611, -0.5649, -0.9176, -0.6573, -0.429, -0.2106, -0.5777, -0.4535"
123,num_123,float32,459217.0,2.76,561515.0,"-0.6565, -0.2677, -0.1931, -0.3094, -0.5849, -0.3425, 0.1084, -1.1167, -0.1486, -0.2901"
124,num_124,float32,459137.0,2.76,949268.0,"-0.7459, -0.7224, -0.1013, -0.6949, -0.7832, -0.6625, -0.7649, -0.3868, -0.5813, -0.5133"
125,num_125,float32,459146.0,2.76,534486.0,"-0.8602, -0.5526, -0.6213, -0.7373, -0.747, -0.6626, -0.8177, -0.6637, -0.6106, -0.0234"
126,num_126,float32,459179.0,2.76,1587383.0,"-0.2713, -0.6109, -0.501, -0.6542, -0.689, -0.7366, -0.21, 0.2928, -0.3141, -0.0619"
127,num_127,float32,459189.0,2.76,1435910.0,"-0.3955, -0.5677, -0.392, -0.2381, -1.1582, -1.1229, -0.2486, 0.0134, -0.7008, -0.037"
128,num_146,float32,459137.0,2.76,848446.0,"-0.5169, -0.6041, -1.0504, -0.3503, -0.7311, -1.5204, -0.4445, 0.0415, -0.3764, -0.3894"
129,num_147,float32,459179.0,2.76,1162583.0,"-1.0273, -1.008, -1.0242, -1.0164, -0.9879, -0.9909, -1.0531, -1.0032, -1.0463, -1.0752"
130,num_148,float32,459189.0,2.76,1178340.0,"-0.3695, 0.0116, -0.4197, -0.3947, -0.6923, -0.5288, -0.4213, -0.3605, -0.5343, 0.251"
131,num_149,float32,459249.0,2.76,560940.0,"-0.2958, -0.4535, -0.2606, -0.2867, -0.7473, 0.2197, -0.609, 0.1401, -0.0385, -0.0034"
132,num_150,float32,459217.0,2.76,551965.0,"-0.3413, -0.6658, -0.5744, -1.033, -0.1983, -0.2254, -0.9285, -0.7477, -0.3732, -0.0742"
133,num_151,float32,459136.0,2.76,917894.0,"-0.9881, -0.8525, -0.3796, -0.4996, -1.3139, -0.688, -0.8441, -0.7725, -0.8425, -0.9257"
134,num_152,float32,459145.0,2.76,532608.0,"5.1993, -0.3896, -0.45, -0.8072, -0.1704, -0.1481, -1.154, -0.4682, -0.1934, -0.6986"
135,num_153,float32,459179.0,2.76,1600145.0,"-0.0584, -0.5443, -0.4296, -0.0364, 0.1179, -0.8885, -0.272, -0.6121, 0.3405, 0.3562"
136,num_154,float32,459188.0,2.76,1317638.0,"-0.564, -0.0133, -0.5636, -0.5705, 0.0864, 0.1763, -0.1442, -0.8853, -0.3419, -0.4861"
137,num_185,float32,459137.0,2.76,4825822.0,"0.505, 0.6479, 3.0901, -0.0161, 0.196, 1.0508, 0.6891, -0.184, 0.9735, -0.4354"
138,num_186,float32,459179.0,2.76,4638226.0,"0.9389, -0.0922, 0.0413, 0.5792, -0.637, 0.2129, -1.205, 3.092, 1.187, 1.4826"
139,num_187,float32,459189.0,2.76,4188410.0,"0.8042, -0.7239, 0.7509, -1.3295, -0.1557, 1.2616, 0.8732, 0.5266, -0.3331, -0.3526"
140,num_188,float32,459137.0,2.76,4874995.0,"-0.3838, 0.8246, 0.6504, 0.1721, 0.0227, -1.6886, 0.5153, -0.6839, 0.6358, 1.2513"
141,num_189,float32,459179.0,2.76,4858498.0,"1.2434, 0.4999, 3.0937, 0.0158, 3.0917, 0.4528, 0.5506, 1.0405, 0.7954, 0.9164"
142,num_190,float32,459189.0,2.76,4344955.0,"0.2271, 0.9649, 0.8619, 0.8751, 0.2377, 0.8516, 0.2774, 0.9032, 0.0715, -0.2231"
143,num_191,float32,459249.0,2.76,4464228.0,"3.09, 3.09, 3.09, 3.09, 3.0899, 3.09, 3.09, 3.0901, 0.1018, 3.0901"
144,num_192,float32,459217.0,2.76,4524203.0,"3.09, 3.09, 3.09, 3.09, 3.0899, 0.0912, -0.4808, -0.8016, -0.3237, -1.0474"
145,num_193,float32,459137.0,2.76,4309272.0,"0.3538, 3.0928, 0.6017, 0.6375, -0.1905, 0.459, 0.3777, 0.1125, -0.4441, -0.0438"
146,num_194,float32,459146.0,2.76,4715110.0,"3.09, 3.09, 3.09, 3.09, 3.09, 3.0901, 3.0899, 3.09, 3.0901, 3.0901"
147,num_195,float32,459179.0,2.76,4316769.0,"1.0349, -0.0493, 0.4376, 0.5676, -0.328, 0.3109, 0.8444, 0.3785, -1.2481, 1.264"
148,num_196,float32,459189.0,2.76,3780204.0,"0.6387, -0.1995, -0.0571, 0.372, 0.7048, 1.1332, 0.3108, 0.233, 0.2125, -0.9578"
149,num_10,float32,10997.0,0.07,3125.0,"-2.8351, 0.0489, -0.6507, 0.059, -0.1119, -0.5939, -0.0464, -0.3629, -0.1829, -0.3188"
150,num_11,float32,10997.0,0.07,2183718.0,"-2.8488, 3.0899, 1.0981, 0.154, -0.1306, 0.922, 1.1538, 1.1536, 1.0327, 0.345"
151,num_0,float32,0.0,0.00,535.0,"-0.1906, -0.2796, -0.879, 0.2304, 0.0615, 0.1422, 0.0238, -0.2679, 0.525, -0.3309"
152,num_1,float32,0.0,0.00,536.0,"0.1245, 0.0968, -0.3071, 0.612, -0.1804, 0.1791, 0.5984, 0.0339, 0.8864, 0.3575"
153,num_2,float32,0.0,0.00,536.0,"0.0163, 0.1018, -0.1397, 0.464, -0.538, -0.1689, 0.5909, -0.0703, 0.6753, 0.4102"
154,num_3,float32,0.0,0.00,536.0,"-1.1047, -1.5057, -0.6911, -1.023, 0.2149, -0.2034, -1.6395, -1.1473, -0.0326, -2.2731"
155,num_4,float32,0.0,0.00,275928.0,"-0.1689, -0.1649, -0.4863, -0.2493, -0.201, -0.4893, -0.5007, -0.2503, -0.655, -0.2549"
156,num_5,float32,0.0,0.00,279244.0,"0.092, 0.0958, -0.0857, 0.1508, 0.1478, 0.0288, -0.0914, -0.0884, 0.4206, 0.0856"
157,num_6,float32,0.0,0.00,336886.0,"-0.0137, -0.0111, -0.1043, 0.1155, -0.0892, -0.1093, 0.1136, -0.1064, -0.2903, 0.0417"

In [6]:
# Numeric Feature Statistics
numeric_stats

                          count      mean       std       min       max
num_0                 1665805.0  0.002674  1.011505 -4.845584  4.648853
num_1                 1665805.0 -0.000763  1.011753 -5.199337  4.265921
num_2                 1665805.0 -0.001557  1.011515 -5.199337  4.585457
num_3                 1665805.0  0.010094  1.010329 -3.089935  5.199337
num_4                 1665805.0  0.004039  1.006548 -5.199337  4.314810
num_5                 1665805.0 -0.002411  1.008709 -5.199337  5.199337
num_6                 1665805.0  0.000115  1.004738 -5.199337  4.076813
num_7                 1665805.0  0.010312  1.003272 -5.199337  4.432878
num_8                 1665805.0  0.033437  0.970357 -3.212438  5.199337
num_9                 1665805.0  0.003676  0.998669 -3.142850  5.199337
num_10                1664710.0  0.033080  0.968364 -2.835144  5.199337
num_11                1664710.0 -0.003147  0.979588 -2.848784  5.199337
num_12                1665805.0  0.000115  0.999471 -5.199337  4.804715
num_13                1665805.0 -0.001430  0.999975 -5.199337  5.199337
num_14                1665805.0 -0.002372  0.999453 -5.199337  5.199337
num_15                1665805.0  0.000396  1.000539 -4.851826  5.199337
num_16                1665805.0  0.000743  0.999399 -5.199337  5.199337
num_17                1665805.0 -0.005143  0.993204 -4.753427  5.199337
num_18                1665805.0 -0.005222  0.993624 -5.199337  5.199337
num_19                1665805.0  0.009907  0.999796 -5.199337  5.199337
num_20                1665805.0 -0.005345  1.008128 -4.878590  5.199337
num_21                1665805.0 -0.006048  0.994759 -5.109687  5.199337
num_22                1665805.0 -0.000847  1.007858 -5.199337  3.405948
num_23                1665805.0 -0.004846  1.007335 -5.199337  5.199337
num_24                1665805.0 -0.013980  0.992741 -5.199337  4.621231
num_25                1665805.0  0.002828  0.989564 -5.199337  4.698359
num_26                1665805.0  0.011997  1.001999 -5.059146  5.199337
num_27                1665805.0  0.015389  1.007415 -4.130455  5.199337
num_28                1665805.0  0.009595  0.997432 -5.199337  5.199337
num_29                1665805.0  0.001914  0.004027  0.001911  5.199337
num_30                1665805.0  0.015929  1.014854 -5.199337  5.199337
num_31                1665805.0 -0.027088  0.739986 -1.141598  5.199337
num_32                1665805.0  0.016125  1.013747 -5.199337  5.199337
num_33                1665805.0 -0.017820  1.023766 -5.199337  5.199337
num_34                1665805.0  0.015252  1.007395 -3.180618  5.199337
num_35                1665805.0  0.020705  0.995159 -5.199337  5.199337
num_36                1665805.0 -0.000760  0.004029 -0.000763  5.199337
num_37                1665805.0  0.018799  1.007990 -3.089935  5.199337
num_38                1665805.0 -0.033647  0.711795 -1.122976  5.199337
num_39                1665805.0  0.018869  1.008626 -3.089935  5.199337
num_40                1665805.0 -0.006928  1.012914 -5.199337  2.967431
num_41                1665805.0  0.009003  1.001966 -4.214230  5.199337
num_42                1665805.0  0.008616  1.003048 -5.199337  5.199337
num_43                1665805.0 -0.000227  0.072009 -0.001903  5.199337
num_44                1665805.0  0.010625  1.003179 -5.199337  5.199337
num_45                1665805.0 -0.012058  0.808882 -1.201274  5.199337
num_46                1665805.0  0.009981  1.005150 -5.199337  5.199337
num_47                1665805.0 -0.011273  1.013480 -5.199337  5.199337
num_48                1665805.0  0.010114  1.001655 -4.771981  5.199337
num_49                1665805.0  0.014968  1.004389 -5.199337  5.199337
num_50                1665805.0  0.011373  0.234342 -0.008743  5.199337
num_51                1665805.0  0.010386  1.001984 -5.199337  5.199337
num_52                1665805.0 -0.002571  0.854492 -1.265250  5.199337
num_53                1665805.0  0.012032  1.000663 -5.199337  5.199337
num_54                1665805.0 -0.014244  1.009221 -5.199337  5.199337
num_55                1665805.0  0.008278  1.003348 -3.871148  5.199337
num_56                1665805.0  0.004739  0.999857 -5.199337  5.199337
num_57                1665805.0  0.000600  0.042543  0.000016  5.199337
num_58                1665805.0  0.011171  0.998882 -3.155615  5.199337
num_59                1665805.0 -0.016400  0.793998 -1.181191  5.199337
num_60                1665805.0  0.012223  1.000649 -3.208419  5.199337
num_61                1665805.0 -0.010371  1.005975 -5.199337  3.290245
num_62                1665805.0  0.009837  1.001134 -4.360886  5.199337
num_63                1665805.0  0.005901  0.999399 -5.199337  5.199337
num_64                1665805.0  0.004426  0.147278 -0.002733  5.199337
num_65                1665805.0  0.009638  1.000040 -5.199337  5.199337
num_66                1665805.0 -0.007346  0.830601 -1.233761  5.199337
num_67                1665805.0  0.011523  1.002283 -5.199337  5.199337
num_68                1665805.0 -0.013018  1.006652 -4.107245  5.199337
num_69                1665805.0  0.013356  1.004637 -2.919716  5.199337
num_70                1665805.0  0.020140  0.995093 -3.290245  5.199337
num_71                1665805.0 -0.000096  0.004029 -0.000100  5.199337
num_72                1665805.0  0.016274  1.008149 -2.806711  5.199337
num_73                1665805.0 -0.029866  0.684587 -1.044711  5.199337
num_74                1665805.0  0.016232  1.008547 -2.747453  5.199337
num_75                1665805.0 -0.019252  1.018012 -5.199337  2.806712
num_76                 732226.0 -0.001200  0.995933 -2.488277  3.742729
num_77                 732226.0 -0.002279  1.006386 -5.199337  5.199337
num_78                 732226.0  0.000424  1.004335 -5.199337  5.199337
num_79                 732226.0  0.011556  0.973175 -1.649172  3.779919
num_80                 732226.0 -0.000804  1.004239 -5.199337  5.199337
num_81                 672089.0  0.015835  0.946587 -1.384628  3.764484
num_82                 672089.0 -0.003740  1.000682 -2.757802  5.199337
num_83                 672089.0 -0.001760  1.001822 -2.764844  5.199337
num_84                 672089.0  0.008459  0.974830 -1.701663  5.199337
num_85                 672089.0 -0.000976  1.001629 -2.761297  5.199337
num_86                 726119.0 -0.000936  0.989500 -2.138280  5.199337
num_87                 726119.0 -0.003806  1.009545 -5.199337  3.743388
num_88                 726119.0 -0.001242  1.008768 -5.199337  3.676826
num_89                 726119.0  0.010325  0.974557 -1.665823  5.199337
num_90                 726119.0 -0.002024  1.009545 -5.199337  5.199337
num_91                 732226.0 -0.077059  0.641539 -2.496063  0.186756
num_92                 732226.0 -0.003311  1.003945 -5.199337  5.199337
num_93                 732226.0  0.000104  1.003608 -5.199337  4.387918
num_94                 732226.0  0.010825  0.973102 -1.652758  5.199337
num_95                 732226.0 -0.002027  1.002343 -5.199337  3.677084
num_96                 732226.0 -0.042815  0.438200 -2.504506  0.048948
num_97                 732226.0 -0.000640  1.000596 -3.103638  5.199337
num_98                 732226.0 -0.000593  1.001278 -3.102379  4.392496
num_99                 732226.0  0.009962  0.972774 -1.648833  4.406810
num_100                732226.0  0.002231  0.999749 -3.106194  4.900964
num_101                732226.0  0.003764  0.000000  0.003764  0.003764
num_102                732226.0  0.010459  0.973043 -1.648422  5.199337
num_103                732226.0  0.010106  0.973085 -1.650965  5.199337
num_104                732226.0  0.007950  0.972356 -1.650248  5.199337
num_105                732226.0  0.010088  0.972027 -1.649074  4.047100
num_106                728899.0 -0.006528  0.994733 -5.199337  2.023292
num_107                741817.0  0.001281  0.996273 -2.498939  5.199337
num_108                741817.0  0.001329  0.996615 -2.499573  5.199337
num_109                728972.0 -0.005506  0.997981 -5.199337  2.074445
num_110                741817.0  0.008664  0.962892 -1.552174  5.199337
num_111                650120.0  0.017810  0.949634 -1.378114  4.037078
num_112                650120.0 -0.001064  1.007308 -5.199337  5.199337
num_113                650120.0 -0.006386  1.007006 -5.199337  5.199337
num_114                650120.0 -0.003251  1.008295 -5.199337  5.035406
num_115                650120.0 -0.002616  1.007191 -5.199337  5.199337
num_116                741817.0  0.067869  0.847739 -0.687781  3.499786
num_117                381136.0  0.016987  0.988455 -5.018498  5.199337
num_118                381136.0  0.024255  0.985347 -5.199337  5.199337
num_119                381136.0  0.021399  0.983255 -5.199337  5.199337
num_120                381136.0  0.021727  0.985764 -5.199337  5.199337
num_121                741817.0  0.064993  0.841161 -0.688889  1.982881
num_122               1619757.0  0.056422  0.999829 -5.199337  5.199337
num_123               1619761.0  0.056366  1.001169 -5.199337  4.292805
num_124               1619772.0 -0.006379  0.991494 -5.199337  5.199337
num_125               1619772.0  0.054650  0.999914 -5.199337  5.199337
num_126               1619769.0  0.042666  1.006339 -5.199337  5.199337
num_127               1619765.0  0.037474  0.996171 -5.199337  5.199337
num_128               1602742.0  0.061855  0.996483 -3.811609  5.199337
num_129               1604466.0  0.060620  1.000249 -5.199337  4.634600
num_130               1607138.0 -0.012613  0.993244 -5.199337  5.199337
num_131               1609368.0  0.063049  0.997194 -5.199337  5.199337
num_132               1522075.0 -0.013614  1.015701 -3.884199  5.199337
num_133               1555542.0  0.012236  0.992116 -5.199337  5.199337
num_134               1594758.0  0.045440  0.996486 -5.199337  5.199337
num_135               1596404.0  0.041673  1.001586 -5.199337  5.199337
num_136               1605952.0  0.036915  1.002467 -5.199337  5.199337
num_137               1600624.0  0.054494  0.997971 -4.687782  5.199337
num_138               1606155.0  0.172512  1.029047 -5.199337  5.199337
num_139               1604306.0  0.164614  1.047502 -5.199337  5.199337
num_140               1603085.0  0.045345  0.999344 -4.499717  5.199337
num_141               1604081.0  0.040438  1.003214 -5.199337  5.199337
num_142               1608549.0  0.038555  1.003176 -3.969713  5.199337
num_143               1605296.0  0.054949  0.999175 -4.299391  4.621231
num_144               1608679.0  0.175614  1.028079 -5.199337  3.186023
num_145               1607606.0  0.164444  1.048121 -5.199337  5.199337
num_146               1619772.0 -0.007540  0.998781 -5.199337  5.199337
num_147               1619769.0  0.005565  1.015533 -5.199337  5.199337
num_148               1619765.0  0.021406  0.995843 -5.199337  5.199337
num_149               1619757.0  0.041312  1.006864 -3.943557  5.199337
num_150               1619761.0  0.043108  1.006661 -5.199337  5.199337
num_151               1619772.0 -0.007629  0.993591 -3.676793  5.199337
num_152               1619772.0  0.043922  1.000793 -4.311787  5.199337
num_153               1619769.0  0.029277  1.013546 -5.199337  5.199337
num_154               1619765.0  0.031329  0.994705 -5.199337  5.199337
num_155               1479284.0  0.017172  1.013890 -5.199337  5.199337
num_156               1494887.0  0.019433  1.016523 -4.305098  5.199337
num_157               1343390.0 -0.012526  1.002855 -5.199337  5.199337
num_158               1521637.0  0.034823  1.002035 -4.901916  5.199337
num_159                533270.0 -0.020611  0.987967 -3.764607  5.199337
num_160                654687.0  0.007042  0.999392 -3.992487  5.199337
num_161               1588080.0  0.049463  1.004354 -5.199337  4.300427
num_162               1591261.0  0.046001  1.004887 -4.685699  5.199337
num_163               1577081.0 -0.012024  0.997707 -5.199337  5.199337
num_164               1598677.0  0.054735  0.998808 -4.793839  5.199337
num_165               1216854.0 -0.027890  1.007398 -3.701071  5.199337
num_166               1382239.0  0.010478  0.996443 -5.199337  3.987981
num_167               1594758.0  0.025254  1.023222 -5.199337  3.117696
num_168               1596404.0  0.028952  1.022098 -5.199337  5.199337
num_169               1605952.0 -0.043480  1.015559 -5.199337  5.199337
num_170               1600624.0  0.011786  1.029293 -5.199337  3.282765
num_171               1606155.0 -0.122714  1.031942 -5.199337  5.199337
num_172               1604306.0 -0.136858  1.062220 -5.199337  3.549313
num_173               1586378.0  0.019935  1.040060 -4.328884  3.382248
num_174               1588602.0  0.021608  1.042855 -5.059838  5.199337
num_175               1595811.0 -0.050551  1.018134 -5.199337  5.199337
num_176               1594546.0  0.010607  1.044489 -5.199337  5.199337
num_177               1512538.0 -0.118406  0.988839 -4.559781  5.199337
num_178               1544641.0 -0.157799  1.055813 -5.199337  5.199337
num_179               1590388.0 -0.002359  1.023956 -5.199337  5.199337
num_180               1592409.0 -0.001292  1.025705 -5.142963  5.199337
num_181               1604244.0  0.001075  1.008175 -4.150467  3.169421
num_182               1596592.0 -0.002469  1.018368 -5.199337  3.291017
num_183               1604548.0  0.004628  1.009016 -5.199337  5.199337
num_184               1601924.0  0.000759  1.006110 -5.199337  5.199337
num_185               1619772.0 -0.003522  1.007998 -5.199337  3.802626
num_186               1619769.0 -0.008967  1.005000 -5.199337  5.199337
num_187               1619765.0 -0.008301  1.005751 -4.230555  5.199337
num_188               1619772.0 -0.002153  1.007013 -5.199337  5.199337
num_189               1619769.0 -0.011587  1.002613 -5.199337  5.199337
num_190               1619765.0 -0.011870  1.008208 -4.340828  5.199337
num_191               1619757.0 -0.002318  1.000511 -5.199337  5.199337
num_192               1619761.0 -0.001572  1.001536 -4.474846  5.199337
num_193               1619772.0  0.000090  1.006634 -5.199337  3.462106
num_194               1619772.0 -0.001587  0.998223 -5.199337  3.430601
num_195               1619769.0 -0.010472  1.004698 -5.199337  5.199337
num_196               1619765.0 -0.009550  1.009165 -5.199337  5.199337
num_197               1479266.0 -0.018990  1.011433 -4.787002  3.395857
num_198               1494871.0 -0.018254  1.012935 -3.305973  5.199337
num_199               1343366.0 -0.001951  1.004951 -3.769037  5.199337
num_200               1521618.0 -0.013538  1.007519 -4.920598  3.112760
num_201                533153.0  0.014515  0.979187 -5.199337  3.535129
num_202                654644.0 -0.004308  1.001121 -5.199337  5.199337
num_203               1479276.0 -0.024674  1.014150 -4.476667  3.617738
num_204               1494879.0 -0.021540  1.013244 -3.304011  3.333853
num_205               1343384.0 -0.002291  1.003795 -5.199337  5.199337
num_206               1521627.0 -0.016518  1.008988 -5.099174  5.199337
num_207                533238.0  0.001791  0.997028 -5.199337  5.199337
num_208                654675.0 -0.008423  0.997866 -5.199337  5.199337
num_209               1588064.0 -0.012857  1.017215 -5.199337  5.199337
num_210               1591246.0 -0.010767  1.015819 -3.559488  3.409125
num_211               1577077.0  0.003699  1.007213 -5.199337  5.199337
num_212               1598671.0 -0.007751  1.011115 -5.199337  5.199337
num_213               1216787.0 -0.015946  1.006920 -4.205914  5.199337
num_214               1382206.0 -0.003637  1.005617 -5.199337  5.199337
num_215               1582732.0  0.045495  1.008005 -4.922908  3.141333
num_216               1585295.0  0.044843  1.007505 -5.199337  5.199337
num_217               1594193.0 -0.008143  0.997256 -4.092432  3.321267
num_218               1590965.0  0.044664  1.004825 -5.199337  3.162423
num_219               1511254.0 -0.012284  1.012628 -5.199337  5.199337
num_220               1542631.0  0.010258  0.998212 -4.196270  5.199337
delivery_eta_minutes  1665805.0  1.769865  0.731798  0.000000  4.856707

In [7]:
# Categorical Feature Statistics
cat_stats

                              value    count    pct
column    rank
bin_0     1                     1.0  1136424  68.22
          2                     0.0   529381  31.78
cat_0     1                      48    17331   1.04
          2                     131    13095   0.79
          3                     121    12996   0.78
          4                      79    12716   0.76
          5                     169    11548   0.69
cat_1     1                     176     9364   0.56
          2                      92     8497   0.51
          3                      71     7854   0.47
          4                      53     7687   0.46
          5                      61     7627   0.46
timestamp 1     2023-10-25 14:12:46        7   0.00
          2     2023-11-19 12:19:17        6   0.00
          3     2023-11-25 15:18:24        6   0.00
          4     2023-10-30 10:36:43        6   0.00
          5     2023-12-25 16:11:08        6   0.00

In [8]:
# Target Distribution
target_df

,y_missing_count,non_positive_pct,skew_y,skew_log,var_y,var_log,log_used,aic_exponential,aic_lognormal,dist_hint
0,0,0.06,0.151,-0.542,0.536,0.079,log1p,5232702.6,1.083757e+09,exponential

## Task Curation

In [9]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import subsample_temporal

date_col = task_mold.time_on
target_col = task_mold.target_column_name

df = df.sort_values(by=date_col).reset_index(drop=True)

test_time_min = df[date_col].max().normalize() - pd.DateOffset(weeks=1)

# Define indices
test_idx = df.index[df[date_col] >= test_time_min].to_numpy().tolist()
train_idx = df.index[
    df[date_col] < test_time_min
].to_numpy().tolist()

df, train_idx, test_idx = subsample_temporal(
    df=df,
    train_idx=train_idx,
    test_idx=test_idx,
    stratify_on=task_mold.stratify_on,
)

print("Train size:", len(train_idx), "| Test size:", len(test_idx))
print("Train target mean:", df.loc[train_idx, target_col].mean())
print("Test target mean:", df.loc[test_idx, target_col].mean())

splits = {0: {0: (train_idx, test_idx)}}

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="We use the last week as test data and all prior data as train data.",
    splits=splits,
    time_horizon=7,
    time_horizon_unit="days",
)

Train size: 1000000 | Test size: 250000
Train target mean: 1.7691861
Test target mean: 1.7732824

## Export

In [10]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...

Saving curated container to delivery_eta/versions/019d7382-df54-7dd3-8198-0567d7499858

019d7382-df54-7dd3-8198-0567d7499858
f4345dea1c4562aaf6f8bd453e2d97f9a2e84fe7b48c418df9f86acfc454c722