### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="amex_iid",
    dataset_year="2022",
    domain_str="finance",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/amex-default-prediction/",
    download_description="""
We start with the preprocessed version of the dataset in Parquet format provided by
the user 'raddar' on Kaggle. At the root of this project, I ran on linux with
the kaggle CLI installed and authenticated:

kaggle datasets download -d raddar/amex-data-integer-dtypes-parquet-format --unzip -p amex_dataset && rm amex_dataset/test.parquet
kaggle competitions download -c amex-default-prediction -f train_labels.csv -p amex_dataset && cd amex_dataset && unzip train_labels.csv.zip train_labels.csv && rm train_labels.csv.zip && cd ..
mkdir -p local-data-warehouse/amex_iid && mv amex_dataset/* local-data-warehouse/amex_iid/ && rm -rf amex_dataset
""",
    # References
    academic_reference_bibtex="""@misc{howard2022amex,
  author       = {Howard, Addison and AritraAmex and Xu, Di and Vashani, Hossein and inversion and Negin and Dane, Sohier},
  title        = {American Express -- Default Prediction},
  year         = {2022},
  howpublished = {Kaggle Competition},
  url          = {https://kaggle.com/competitions/amex-default-prediction},
  note         = {Accessed via Kaggle}
}
""",
    academic_reference_bibtex_key="howard2022amex",
    licence="Kaggle Competition License",
    data_tags=["IID"],
    curation_comments="""
Our preprocessing followed two Kaggle notebooks (https://www.kaggle.com/code/cdeotte/xgboost-starter-0-793,
https://www.kaggle.com/code/huseyincot/amex-agg-data-how-it-created), which follows
some of the most common steps used by top competitors in this competition. This final
version of the data becomes IID at the customer_ID level and drops temporal information.

- We transformed the "S_2" column to datetime format. It is used to sort the data for
 groupby aggregations based on the last value working correctly. Then it is dropped.
- We filled missing values with -127 (to be able to cast to int types to reduce memory).
- We transformed the list of transactions per customer to a single row per customer by
 aggregating numerical features with mean, std, min, max, and last value using groupby.
 Categorical features were aggregated with count, last value, and nunique.
- We drop the customer index and shuffled the data.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="target",
    problem_type="binary_classification",
    objective_metric_name="amex_metric",
    stratify_on="target",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_parquet(dataset_mold.path / "train.parquet")
print("Loaded data shape:", df.shape)

df.S_2 = pd.to_datetime(df.S_2)
df = df.sort_values(["customer_ID", "S_2"])

df = df.fillna(-127)

# Feature Engineering
all_cols = [c for c in list(df.columns) if c not in ["customer_ID", "S_2"]]
cat_features = [
    "B_30",
    "B_38",
    "D_114",
    "D_116",
    "D_117",
    "D_120",
    "D_126",
    "D_63",
    "D_64",
    "D_66",
    "D_68",
]
num_features = [col for col in all_cols if col not in cat_features]

num_agg = df.groupby("customer_ID")[num_features].agg(
    ["mean", "std", "min", "max", "last"]
)
num_agg.columns = ["_".join(x) for x in num_agg.columns]

cat_agg = df.groupby("customer_ID")[cat_features].agg(["count", "last", "nunique"])
cat_agg.columns = ["_".join(x) for x in cat_agg.columns]

df = pd.concat([num_agg, cat_agg], axis=1)
del num_agg, cat_agg

# Add labels
targets = pd.read_csv(dataset_mold.path / "train_labels.csv")
targets = targets.set_index("customer_ID")
df = df.merge(targets, left_index=True, right_index=True, how="left")
df.target = df.target.astype("int8")
del targets

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

Loaded data shape: (5531451, 190)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False,
)

#### Dataset Overview
Rows: 458,913
Columns: 919

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,P_2_mean,P_2_std,P_2_min,P_2_max,P_2_last,D_39_mean,D_39_std,D_39_min,D_39_max,D_39_last,B_1_mean,B_1_std,B_1_min,B_1_max,B_1_last,B_2_mean,B_2_std,B_2_min,B_2_max,B_2_last,R_1_mean,R_1_std,R_1_min,R_1_max,R_1_last,S_3_mean,S_3_std,S_3_min,S_3_max,S_3_last,D_41_mean,D_41_std,D_41_min,D_41_max,D_41_last,B_3_mean,B_3_std,B_3_min,B_3_max,B_3_last,D_42_mean,D_42_std,D_42_min,D_42_max,D_42_last,D_43_mean,D_43_std,D_43_min,D_43_max,D_43_last,D_44_mean,D_44_std,D_44_min,D_44_max,D_44_last,B_4_mean,B_4_std,B_4_min,B_4_max,B_4_last,D_45_mean,D_45_std,D_45_min,D_45_max,D_45_last,B_5_mean,B_5_std,B_5_min,B_5_max,B_5_last,R_2_mean,R_2_std,R_2_min,R_2_max,R_2_last,D_46_mean,D_46_std,D_46_min,D_46_max,D_46_last,D_47_mean,D_47_std,D_47_min,D_47_max,D_47_last,D_48_mean,D_48_std,D_48_min,D_48_max,D_48_last,D_49_mean,D_49_std,D_49_min,D_49_max,D_49_last,B_6_mean,B_6_std,B_6_min,B_6_max,B_6_last,B_7_mean,B_7_std,B_7_min,B_7_max,B_7_last,B_8_mean,B_8_std,B_8_min,B_8_max,B_8_last,D_50_mean,D_50_std,D_50_min,D_50_max,D_50_last,D_51_mean,D_51_std,D_51_min,D_51_max,D_51_last,B_9_mean,B_9_std,B_9_min,B_9_max,B_9_last,R_3_mean,R_3_std,R_3_min,R_3_max,R_3_last,D_52_mean,D_52_std,D_52_min,D_52_max,D_52_last,P_3_mean,P_3_std,P_3_min,P_3_max,P_3_last,B_10_mean,B_10_std,B_10_min,B_10_max,B_10_last,D_53_mean,D_53_std,D_53_min,D_53_max,D_53_last,S_5_mean,S_5_std,S_5_min,S_5_max,S_5_last,B_11_mean,B_11_std,B_11_min,B_11_max,B_11_last,S_6_mean,S_6_std,S_6_min,S_6_max,S_6_last,D_54_mean,D_54_std,D_54_min,D_54_max,D_54_last,R_4_mean,R_4_std,R_4_min,R_4_max,R_4_last,S_7_mean,S_7_std,S_7_min,S_7_max,S_7_last,B_12_mean,B_12_std,B_12_min,B_12_max,B_12_last,S_8_mean,S_8_std,S_8_min,S_8_max,S_8_last,D_55_mean,D_55_std,D_55_min,D_55_max,D_55_last,D_56_mean,D_56_std,D_56_min,D_56_max,D_56_last,B_13_mean,B_13_std,B_13_min,B_13_max,B_13_last,R_5_mean,R_5_std,R_5_min,R_5_max,R_5_last,D_58_mean,D_58_std,D_58_min,D_58_max,D_58_last,S_9_mean,S_9_std,S_9_min,S_9_max,S_9_last,B_14_mean,B_14_std,B_14_min,B_14_max,B_14_last,D_59_mean,D_59_std,D_59_min,D_59_max,D_59_last,D_60_mean,D_60_std,D_60_min,D_60_max,D_60_last,D_61_mean,D_61_std,D_61_min,D_61_max,D_61_last,B_15_mean,B_15_std,B_15_min,B_15_max,B_15_last,S_11_mean,S_11_std,S_11_min,S_11_max,S_11_last,D_62_mean,D_62_std,D_62_min,D_62_max,D_62_last,D_65_mean,D_65_std,D_65_min,D_65_max,D_65_last,B_16_mean,B_16_std,B_16_min,B_16_max,B_16_last,B_17_mean,B_17_std,B_17_min,B_17_max,B_17_last,B_18_mean,B_18_std,B_18_min,B_18_max,B_18_last,B_19_mean,B_19_std,B_19_min,B_19_max,B_19_last,B_20_mean,B_20_std,B_20_min,B_20_max,B_20_last,S_12_mean,S_12_std,S_12_min,S_12_max,S_12_last,R_6_mean,R_6_std,R_6_min,R_6_max,R_6_last,S_13_mean,S_13_std,S_13_min,S_13_max,S_13_last,B_21_mean,B_21_std,B_21_min,B_21_max,B_21_last,D_69_mean,D_69_std,D_69_min,D_69_max,D_69_last,B_22_mean,B_22_std,B_22_min,B_22_max,B_22_last,D_70_mean,D_70_std,D_70_min,D_70_max,D_70_last,D_71_mean,D_71_std,D_71_min,D_71_max,D_71_last,D_72_mean,D_72_std,D_72_min,D_72_max,D_72_last,S_15_mean,S_15_std,S_15_min,S_15_max,S_15_last,B_23_mean,B_23_std,B_23_min,B_23_max,B_23_last,D_73_mean,D_73_std,D_73_min,D_73_max,D_73_last,P_4_mean,P_4_std,P_4_min,P_4_max,P_4_last,D_74_mean,D_74_std,D_74_min,D_74_max,D_74_last,D_75_mean,D_75_std,D_75_min,D_75_max,D_75_last,D_76_mean,D_76_std,D_76_min,D_76_max,D_76_last,B_24_mean,B_24_std,B_24_min,B_24_max,B_24_last,R_7_mean,R_7_std,R_7_min,R_7_max,R_7_last,D_77_mean,D_77_std,D_77_min,D_77_max,D_77_last,B_25_mean,B_25_std,B_25_min,B_25_max,B_25_last,B_26_mean,B_26_std,B_26_min,B_26_max,B_26_last,D_78_mean,D_78_std,D_78_min,D_78_max,D_78_last,D_79_mean,D_79_std,D_79_min,D_79_max,D_79_last,R_8_mean,R_8_std,R_8_min,R_8_max,R_8_last,R_9_mean,R_9_std,R_9_min,R_9_max,R_9_last,S_16_mean,S_16_std,S_16_min,S_16_max,S_16_last,D_80_mean,D_80_std,D_80_min,D_80_max,D_80_last,R_10_mean,R_10_std,R_10_min,R_10_max,R_10_last,R_11_mean,R_11_std,R_11_min,R_11_max,R_11_last,B_27_mean,B_27_std,B_27_min,B_27_max,B_27_last,D_81_mean,D_81_std,D_81_min,D_81_max,D_81_last,D_82_mean,D_82_std,D_82_min,D_82_max,D_82_last,S_17_mean,S_17_std,S_17_min,S_17_max,S_17_last,R_12_mean,R_12_std,R_12_min,R_12_max,R_12_last,B_28_mean,B_28_std,B_28_min,B_28_max,B_28_last,R_13_mean,R_13_std,R_13_min,R_13_max,R_13_last,D_83_mean,D_83_std,D_83_min,D_83_max,D_83_last,R_14_mean,R_14_std,R_14_min,R_14_max,R_14_last,R_15_mean,R_15_std,R_15_min,R_15_max,R_15_last,D_84_mean,D_84_std,D_84_min,D_84_max,D_84_last,R_16_mean,R_16_std,R_16_min,R_16_max,R_16_last,B_29_mean,B_29_std,B_29_min,B_29_max,B_29_last,S_18_mean,S_18_std,S_18_min,S_18_max,S_18_last,D_86_mean,D_86_std,D_86_min,D_86_max,D_86_last,D_87_mean,D_87_std,D_87_min,D_87_max,D_87_last,R_17_mean,R_17_std,R_17_min,R_17_max,R_17_last,R_18_mean,R_18_std,R_18_min,R_18_max,R_18_last,D_88_mean,D_88_std,D_88_min,D_88_max,D_88_last,B_31_mean,B_31_std,B_31_min,B_31_max,B_31_last,S_19_mean,S_19_std,S_19_min,S_19_max,S_19_last,R_19_mean,R_19_std,R_19_min,R_19_max,R_19_last,B_32_mean,B_32_std,B_32_min,B_32_max,B_32_last,S_20_mean,S_20_std,S_20_min,S_20_max,S_20_last,R_20_mean,R_20_std,R_20_min,R_20_max,R_20_last,R_21_mean,R_21_std,R_21_min,R_21_max,R_21_last,B_33_mean,B_33_std,B_33_min,B_33_max,B_33_last,D_89_mean,D_89_std,D_89_min,D_89_max,D_89_last,R_22_mean,R_22_std,R_22_min,R_22_max,R_22_last,R_23_mean,R_23_std,R_23_min,R_23_max,R_23_last,D_91_mean,D_91_std,D_91_min,D_91_max,D_91_last,D_92_mean,D_92_std,D_92_min,D_92_max,D_92_last,D_93_mean,D_93_std,D_93_min,D_93_max,D_93_last,D_94_mean,D_94_std,D_94_min,D_94_max,D_94_last,R_24_mean,R_24_std,R_24_min,R_24_max,R_24_last,R_25_mean,R_25_std,R_25_min,R_25_max,R_25_last,D_96_mean,D_96_std,D_96_min,D_96_max,D_96_last,S_22_mean,S_22_std,S_22_min,S_22_max,S_22_last,S_23_mean,S_23_std,S_23_min,S_23_max,S_23_last,S_24_mean,S_24_std,S_24_min,S_24_max,S_24_last,S_25_mean,S_25_std,S_25_min,S_25_max,S_25_last,S_26_mean,S_26_std,S_26_min,S_26_max,S_26_last,D_102_mean,D_102_std,D_102_min,D_102_max,D_102_last,D_103_mean,D_103_std,D_103_min,D_103_max,D_103_last,D_104_mean,D_104_std,D_104_min,D_104_max,D_104_last,D_105_mean,D_105_std,D_105_min,D_105_max,D_105_last,D_106_mean,D_106_std,D_106_min,D_106_max,D_106_last,D_107_mean,D_107_std,D_107_min,D_107_max,D_107_last,B_36_mean,B_36_std,B_36_min,B_36_max,B_36_last,B_37_mean,B_37_std,B_37_min,B_37_max,B_37_last,R_26_mean,R_26_std,R_26_min,R_26_max,R_26_last,R_27_mean,R_27_std,R_27_min,R_27_max,R_27_last,D_108_mean,D_108_std,D_108_min,D_108_max,D_108_last,D_109_mean,D_109_std,D_109_min,D_109_max,D_109_last,D_110_mean,D_110_std,D_110_min,D_110_max,D_110_last,D_111_mean,D_111_std,D_111_min,D_111_max,D_111_last,B_39_mean,B_39_std,B_39_min,B_39_max,B_39_last,D_112_mean,D_112_std,D_112_min,D_112_max,D_112_last,B_40_mean,B_40_std,B_40_min,B_40_max,B_40_last,S_27_mean,S_27_std,S_27_min,S_27_max,S_27_last,D_113_mean,D_113_std,D_113_min,D_113_max,D_113_last,D_115_mean,D_115_std,D_115_min,D_115_max,D_115_last,D_118_mean,D_118_std,D_118_min,D_118_max,D_118_last,D_119_mean,D_119_std,D_119_min,D_119_max,D_119_last,D_121_mean,D_121_std,D_121_min,D_121_max,D_121_last,D_122_mean,D_122_std,D_122_min,D_122_max,D_122_last,D_123_mean,D_123_std,D_123_min,D_123_max,D_123_last,D_124_mean,D_124_std,D_124_min,D_124_max,D_124_last,D_125_mean,D_125_std,D_125_min,D_125_max,D_125_last,D_127_mean,D_127_std,D_127_min,D_127_max,D_127_last,D_128_mean,D_128_std,D_128_min,D_128_max,D_128_last,D_129_mean,D_129_std,D_129_min,D_129_max,D_129_last,B_41_mean,B_41_std,B_41_min,B_41_max,B_41_last,B_42_mean,B_42_std,B_42_min,B_42_max,B_42_last,D_130_mean,D_130_std,D_130_min,D_130_max,D_130_last,D_131_mean,D_131_std,D_131_min,D_131_max,D_131_last,D_132_mean,D_132_std,D_132_min,D_132_max,D_132_last,D_133_mean,D_133_std,D_133_min,D_133_max,D_133_last,R_28_mean,R_28_std,R_28_min,R_28_max,R_28_last,D_134_mean,D_134_std,D_134_min,D_134_max,D_134_last,D_135_mean,D_135_std,D_135_min,D_135_max,D_135_last,D_136_mean,D_136_std,D_136_min,D_136_max,D_136_last,D_137_mean,D_137_std,D_137_min,D_137_max,D_137_last,D_138_mean,D_138_std,D_138_min,D_138_max,D_138_last,D_139_mean,D_139_std,D_139_min,D_139_max,D_139_last,D_140_mean,D_140_std,D_140_min,D_140_max,D_140_last,D_141_mean,D_141_std,D_141_min,D_141_max,D_141_last,D_142_mean,D_142_std,D_142_min,D_142_max,D_142_last,D_143_mean,D_143_std,D_143_min,D_143_max,D_143_last,D_144_mean,D_144_std,D_144_min,D_144_max,D_144_last,D_145_mean,D_145_std,D_145_min,D_145_max,D_145_last,B_30_count,B_30_last,B_30_nunique,B_38_count,B_38_last,B_38_nunique,D_114_count,D_114_last,D_114_nunique,D_116_count,D_116_last,D_116_nunique,D_117_count,D_117_last,D_117_nunique,D_120_count,D_120_last,D_120_nunique,D_126_count,D_126_last,D_126_nunique,D_63_count,D_63_last,D_63_nunique,D_64_count,D_64_last,D_64_nunique,D_66_count,D_66_last,D_66_nunique,D_68_count,D_68_last,D_68_nunique,target
0,0.676015,0.029169,0.628534,0.725528,0.654935,1.615385,4.194013,0,14,0,0.101643,0.097616,0.009458,0.354284,0.099197,0.634776,0.350351,0.094994,1.008683,0.094994,0.005882,0.003025,0.000870,0.009774,0.006555,0.164201,0.033795,0.131419,0.265531,0.152290,0.0,0.0,0.0,0.0,0.0,0.039359,0.033349,0.004846,0.117052,0.117052,-19.531637,47.695824,-127.000000,0.012284,-127.000000,-127.000000,0.000000,-127.000000,-127.000000,-127.000000,0.000000,0.000000,0,0,0,8.538462,4.841064,0,16,9,0.018937,0.010593,0.003717,0.036002,0.035624,0.029121,0.020770,0.007892,0.087301,0.051588,0.0,0.0,0,0,0,-28.960875,55.890903,-127.000000,0.488856,0.488856,0.033197,0.007635,0.021799,0.043619,0.043619,0.130950,0.073741,0.023358,0.249552,0.249552,-1.0,0.0,-1,-1,-1,0.153958,0.049798,0.067149,0.248855,0.067149,0.057332,0.033394,0.000741,0.119244,0.096887,1.005507,0.003341,1.000238,1.009094,1.007283,-127.000000,0.000000,-127.000000,-127.000000,-127.000000,0.0,0.00000,0,0,0,0.193532,0.118096,0.000092,0.395648,0.184687,0.461538,0.518875,0,1,0,0.067433,0.011383,0.057911,0.088198,0.087497,-28.796995,55.984356,-127.000000,0.741574,0.652682,0.221454,0.106893,0.030551,0.432499,0.030551,-127.000000,0.000000,-127.0,-127.000000,-127.0,0.185373,0.176150,0.017404,0.609399,0.145832,0.083850,0.088362,0.000438,0.316418,0.079897,0.076923,0.277350,0,1,0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0,0,0,0.225513,0.081875,0.115077,0.370181,0.349526,0.041325,0.013130,0.014523,0.059725,0.054404,1104.076923,369.452627,322,1511,1021,0.073554,0.027401,0.036920,0.121393,0.121393,-127.000000,0.000000,-127.000000,-127.000000,-127.000000,0.102290,0.045739,0.023217,0.144834,0.101063,0.0,0.0,0,0,0,0.005396,0.003334,0.000510,0.009814,0.004987,-19.528288,47.697311,-127.000000,0.026492,0.007840,0.070228,0.040770,0.005051,0.123367,0.108275,24.615385,7.921894,-1,29,29,0.703798,0.236115,0.269621,1.009372,0.990192,0.148562,0.061843,0.026829,0.218550,0.213280,0.004188,0.003344,0.000183,0.009836,0.009836,12.076923,1.656379,9,15,11,-19.424232,47.743492,-127.000000,0.147819,0.115568,0.0,0.0,0,0,0,3.461538,2.787334,0,8,8,-28.581656,56.107174,-127.000000,1.008176,1.003188,0.632881,0.318421,0.310680,1.000000,0.316049,0.000000,0.000000,0,0,0,1.769231,1.786703,0,5,4,0.205688,0.036210,0.150885,0.286770,0.150885,0.004856,0.003163,0.000093,0.009826,0.000745,334.615385,160.863057,0,435,0,0.005341,0.002836,0.000927,0.008579,0.006093,-19.534054,47.694752,-127.000000,0.008946,0.003789,0.000000,0.00000,0,0,0,-0.076923,0.27735,-1,0,0,0.006814,0.003079,0.001910,0.013097,0.005006,0.0,0.0,0,0,0,6.615385,0.767948,6,8,6,0.042594,0.026029,0.004633,0.091201,0.066295,-127.0,0.0,-127.0,-127.0,-127.0,0.811171,0.360096,0.000000,0.974516,0.000000,0.000000,0.00000,0,0,0,0.615385,0.50637,0,1,1,-127.000000,0.000000,-127.000000,-127.000000,-127.000000,0.004845,0.003316,0.000547,0.009999,0.002335,0.0,0.0,0.0,0.0,0.0,-19.430929,47.740520,-127.000000,0.138587,0.107225,0.120627,0.073001,0.002756,0.217863,0.183079,0.005810,0.003316,0.000087,0.009943,0.003104,0.000000,0.000000,0,0,0,-0.076923,0.27735,-1,0,0,0.0,0.0,0,0,0,-1.0,0.0,-1,-1,-1,0.004956,0.003015,0.000528,0.009655,0.008851,0.000000,0.00000,0,0,0,0.0,0.0,0,0,0,0.000000,0.000000,0,0,0,0.005604,0.003139,0.001096,0.009785,0.009477,0.0,0.0,0,0,0,-1.0,0.0,-1,-1,-1,0.006182,0.002239,0.002387,0.008891,0.008137,1.0,0.0,1.0,1.0,1.0,0.047612,0.023679,0.007241,0.081377,0.049360,0.0,0.0,0,0,0,-0.153846,0.375534,-1,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.000000,0.000000,0,0,0,-127.0,0.0,-127.0,-127.0,-127.0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,-1.0,0.0,-1,-1,-1,0.0,0.0,0,0,0,0.0,0.0,0,0,0,-127.0,0.0,-127.0,-127.0,-127.0,1.0,0.0,1,1,1,0.005028,0.002741,0.001581,0.009180,0.003146,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.384615,0.50637,0,1,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,-0.076923,0.27735,-1,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.000000,0.00000,0,0,0,0.971307,0.021373,0.918809,0.989992,0.983430,0.135753,0.002905,0.131413,0.139787,0.132337,0.971780,0.018239,0.933955,0.991822,0.983682,0.973839,0.003106,0.969211,0.978775,0.972185,0.043270,0.055427,0.002203,0.221602,0.221602,-9.763668,35.225136,-127.000000,0.009987,0.008718,-0.076923,0.277350,-1,0,0,-9.769231,35.223461,-127.000000,0.000000,0.000000,-127.000000,0.000000,-127.000000,-127.000000,-127.000000,-1.0,0.0,-1,-1,-1,-0.076923,0.277350,-1,0,0,0.005850,0.003323,0.000588,0.009711,0.000782,0.102106,0.095914,0.005589,0.349078,0.104987,-1.0,0.0,-1,-1,-1,1.004819,0.003421,1.000381,1.010000,1.010000,-1.0,0.0,-1,-1,-1,0.0,0.0,0,0,0,-127.0,0.0,-127.0,-127.0,-127.0,-1.0,0.0,-1,-1,-1,-127.0,0.0,-127.0,-127.0,-127.0,1.0,0.0,1.0,1.0,1.0,0.023193,0.014736,0.002974,0.045518,0.004402,0.432622,0.197061,0.003092,0.611544,0.606189,0.615385,0.767948,-1,1,0,-19.434746,47.738823,-127.000000,0.133215,0.130129,-19.435909,47.738308,-127.000000,0.131581,0.131581,-19.437344,47.737671,-127.000000,0.130007,0.130007,-19.470905,47.722775,-127.000000,0.091423,0.091423,3.230769,1.877669,-1,4,4,-0.153846,0.375534,-1,0,0,0.769231,0.832050,-1,2,1,-0.153846,0.375534,-1,0,0,0.0,0.0,0,0,0,-9.769231,35.223461,-127.000000,0.000000,0.000000,-0.076923,0.27735,-1,0,0,0.0,0.0,0,0,0,-127.0,0.0,-127.0,-127.0,-127.0,-9.769231,35.223461,-127.0,0.0,0.0,-9.769231,35.223461,-127.0,0.0,0.0,-127.0,0.0,-127.0,-127.0,-127.0,-9.763955,35.225048,-127.000000,0.008712,0.000429,0.0,0.0,0,0,0,-127.0,0.0,-127.0,-127.0,-127.0,-1.0,0.0,-1,-1,-1,-1.0,0.0,-1,-1,-1,-1.0,0.0,-1,-1,-1,-1.0,0.0,-1,-1,-1,-0.076923,0.27735,-1,0,0,-0.076923,0.27735,-1,0,0,-9.769231,35.223461,-127.000000,0.000000,0.000000,-127.000000,0.000000,-127.000000,-127.000000,-127.000000,-0.076923,0.27735,-1,0,0,-9.766028,35.224426,-127.000000,0.007874,0.000220,-0.076923,0.277350,-1,0,0,13,0,1,13,5,3,13,0,2,13,0,2,13,5,3,13,0,2,13,2,2,13,3,1,13,0,2,13,-1,1,13,4,3,0

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,D_44_min,int8,0,0.00,27,"0, -1, 1, 2, 3, 4, 5, 6, 7, 8"
1,D_44_max,int8,0,0.00,32,"0, 1, 2, 3, 4, -1, 5, 6, 7, 8"
2,D_44_last,int8,0,0.00,31,"0, 1, 2, 3, -1, 4, 5, 6, 7, 8"
3,R_2_min,int8,0,0.00,2,"0, 1"
4,R_2_max,int8,0,0.00,2,"0, 1"
5,R_2_last,int8,0,0.00,2,"0, 1"
6,D_51_min,int8,0,0.00,8,"0, 1, 2, 3, 4, 5, 6, 7"
7,D_51_max,int8,0,0.00,9,"0, 1, 2, 3, 4, 5, 6, 7, 8"
8,D_51_last,int8,0,0.00,8,"0, 1, 2, 3, 4, 5, 6, 7"
9,R_3_min,int8,0,0.00,42,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
10,R_3_max,int8,0,0.00,73,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
11,R_3_last,int8,0,0.00,57,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
12,S_6_min,int8,0,0.00,2,"0, 1"
13,S_6_max,int8,0,0.00,2,"0, 1"
14,S_6_last,int8,0,0.00,2,"0, 1"
15,R_4_min,int8,0,0.00,2,"0, 1"
16,R_4_max,int8,0,0.00,2,"0, 1"
17,R_4_last,int8,0,0.00,2,"0, 1"
18,R_5_min,int8,0,0.00,23,"0, 1, 2, 3, 5, 4, 6, 9, 7, 8"
19,R_5_max,int8,0,0.00,44,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
20,R_5_last,int8,0,0.00,40,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
21,D_59_min,int8,0,0.00,72,"18, -1, 21, 24, 15, 8, 22, 17, 7, 13"
22,D_59_max,int8,0,0.00,92,"28, 31, 29, 30, 16, 9, 8, 14, 22, 15"
23,D_59_last,int8,0,0.00,85,"28, 31, 29, 30, 15, 14, 8, 9, 22, 21"
24,S_11_min,int8,0,0.00,57,"12, 11, 10, 9, 8, 7, 13, 14, 6, 15"
25,S_11_max,int8,0,0.00,83,"12, 16, 18, 17, 19, 15, 20, 13, 14, 21"
26,S_11_last,int8,0,0.00,73,"12, 13, 16, 15, 14, 17, 18, 11, 19, 10"
27,B_16_min,int8,0,0.00,14,"0, 12, 1, 2, 3, 11, 5, 6, 4, 7"
28,B_16_max,int8,0,0.00,14,"12, 0, 1, 2, 3, 11, 4, 5, 7, 10"
29,B_16_last,int8,0,0.00,14,"0, 12, 1, 2, 11, 3, 10, 9, 7, 4"
30,B_19_min,int8,0,0.00,47,"0, 100, 8, 16, 50, 33, 25, 66, 83, 91"
31,B_19_max,int8,0,0.00,47,"0, 100, 8, 50, 16, 33, 25, 91, 66, 83"
32,B_19_last,int8,0,0.00,47,"0, 100, 8, 50, 16, 33, 25, 66, 91, 83"
33,B_20_min,int8,0,0.00,19,"0, 17, 1, 5, 2, 6, 3, 4, 7, 8"
34,B_20_max,int8,0,0.00,19,"0, 17, 1, 2, 3, 5, 4, 6, 7, 8"
35,B_20_last,int8,0,0.00,19,"0, 17, 1, 2, 3, 5, 6, 4, 7, 8"
36,B_22_min,int8,0,0.00,8,"0, 1, -1, 2, 3, 4, 5, 7"
37,B_22_max,int8,0,0.00,9,"0, 1, 2, 3, 4, 5, -1, 6, 7"
38,B_22_last,int8,0,0.00,9,"0, 1, 2, 3, 4, -1, 5, 6, 7"
39,D_70_min,int8,0,0.00,13,"0, -1, 1, 2, 3, 4, 5, 6, 7, 8"
40,D_70_max,int8,0,0.00,27,"0, 1, 2, 3, 4, 5, -1, 6, 7, 8"
41,D_70_last,int8,0,0.00,23,"0, 1, 2, 3, 4, -1, 5, 6, 7, 8"
42,D_72_min,int8,0,0.00,11,"0, -1, 1, 2, 3, 4, 5, 9, 6, 7"
43,D_72_max,int8,0,0.00,11,"0, 1, 2, 3, 4, 9, 5, -1, 6, 7"
44,D_72_last,int8,0,0.00,11,"0, 1, 2, 3, 4, -1, 9, 5, 6, 7"
45,S_15_min,int8,0,0.00,29,"5, 4, 8, 6, 3, 7, 2, 0, 1, 9"
46,S_15_max,int8,0,0.00,57,"8, 6, 7, 9, 5, 10, 11, 12, 13, 14"
47,S_15_last,int8,0,0.00,47,"8, 5, 6, 7, 4, 9, 3, 10, 11, 12"
48,D_74_min,int8,0,0.00,43,"0, 1, 2, 3, 4, 5, 6, -1, 7, 8"
49,D_74_max,int8,0,0.00,47,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
50,D_74_last,int8,0,0.00,46,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
51,D_75_min,int8,0,0.00,44,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
52,D_75_max,int8,0,0.00,49,"1, 0, 2, 3, 4, 5, 6, 7, 8, 9"
53,D_75_last,int8,0,0.00,47,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
54,D_78_min,int8,0,0.00,14,"0, -1, 1, 2, 3, 4, 6, 5, 7, 8"
55,D_78_max,int8,0,0.00,23,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
56,D_78_last,int8,0,0.00,22,"0, 1, -1, 2, 3, 4, 5, 6, 7, 8"
57,D_79_min,int8,0,0.00,12,"0, -1, 1, 2, 3, 4, 5, 6, 8, 7"
58,D_79_max,int8,0,0.00,24,"0, 1, 2, 3, -1, 4, 5, 6, 7, 8"
59,D_79_last,int8,0,0.00,24,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
60,R_8_min,int8,0,0.00,14,"0, 1, 2, 3, 4, 6, 5, 7, 18, 13"
61,R_8_max,int8,0,0.00,30,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
62,R_8_last,int8,0,0.00,28,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
63,R_9_min,int8,0,0.00,11,"-1, 1, 0, 2, 3, 4, 5, 9, 6, 7"
64,R_9_max,int8,0,0.00,11,"-1, 1, 2, 3, 0, 4, 5, 6, 9, 7"
65,R_9_last,int8,0,0.00,10,"-1, 1, 2, 3, 4, 5, 6, 9, 7, 8"
66,D_80_min,int8,0,0.00,22,"0, 1, 2, -1, 3, 4, 5, 6, 7, 8"
67,D_80_max,int8,0,0.00,33,"0, 1, 2, 3, 4, 5, 6, 7, -1, 8"
68,D_80_last,int8,0,0.00,31,"0, 1, 2, 3, 4, 5, -1, 6, 7, 8"
69,R_10_min,int8,0,0.00,7,"0, 1, 2, 3, 4, 8, 7"
70,R_10_max,int8,0,0.00,16,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
71,R_10_last,int8,0,0.00,14,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
72,R_11_min,int8,0,0.00,9,"0, 1, 2, 3, 4, 6, 7, 8, 11"
73,R_11_max,int8,0,0.00,19,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
74,R_11_last,int8,0,0.00,13,"0, 1, 2, 3, 4, 5, 6, 7, 9, 8"
75,D_81_min,int8,0,0.00,10,"0, -1, 1, 2, 3, 4, 6, 5, 7, 8"
76,D_81_max,int8,0,0.00,10,"0, 1, 2, 3, 4, -1, 5, 6, 7, 8"
77,D_81_last,int8,0,0.00,10,"0, 1, 2, 3, -1, 4, 5, 6, 7, 8"
78,D_82_min,int8,0,0.00,7,"-1, 1, 0, 2, 3, 4, 5"
79,D_82_max,int8,0,0.00,8,"-1, 1, 0, 2, 3, 4, 5, 6"
80,D_82_last,int8,0,0.00,7,"-1, 1, 0, 2, 3, 4, 5"
81,R_13_min,int8,0,0.00,15,"0, 1, 2, 4, 3, 6, 7, 8, 5, 10"
82,R_13_max,int8,0,0.00,28,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
83,R_13_last,int8,0,0.00,25,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
84,D_83_min,int8,0,0.00,17,"0, -1, 1, 2, 3, 4, 5, 6, 7, 8"
85,D_83_max,int8,0,0.00,28,"0, 1, -1, 2, 3, 4, 5, 6, 7, 8"
86,D_83_last,int8,0,0.00,25,"0, 1, -1, 2, 3, 4, 5, 6, 7, 8"
87,R_15_min,int8,0,0.00,2,"0, 1"
88,R_15_max,int8,0,0.00,2,"0, 1"
89,R_15_last,int8,0,0.00,2,"0, 1"
90,D_84_min,int8,0,0.00,19,"0, -1, 1, 2, 3, 4, 5, 6, 7, 8"
91,D_84_max,int8,0,0.00,38,"0, 1, 2, 3, 4, 5, 6, -1, 7, 8"
92,D_84_last,int8,0,0.00,35,"0, 1, 2, 3, 4, -1, 5, 6, 7, 8"
93,R_16_min,int8,0,0.00,11,"0, 1, 2, 3, 4, 5, 6, 8, 7, 14"
94,R_16_max,int8,0,0.00,31,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
95,R_16_last,int8,0,0.00,24,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
96,S_18_min,int8,0,0.00,2,"0, 1"
97,S_18_max,int8,0,0.00,2,"0, 1"
98,S_18_last,int8,0,0.00,2,"0, 1"
99,D_86_min,int8,0,0.00,2,"0, 1"
100,D_86_max,int8,0,0.00,2,"0, 1"
101,D_86_last,int8,0,0.00,2,"0, 1"
102,D_87_min,int8,0,0.00,2,"-1, 1"
103,D_87_max,int8,0,0.00,2,"-1, 1"
104,D_87_last,int8,0,0.00,2,"-1, 1"
105,R_17_min,int8,0,0.00,12,"0, 1, 2, 3, 4, 8, 5, 11, 12, 10"
106,R_17_max,int8,0,0.00,25,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
107,R_17_last,int8,0,0.00,23,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"
108,R_18_min,int8,0,0.00,5,"0, 1, 10, 3, 7"
109,R_18_max,int8,0,0.00,19,"0, 1, 2, 4, 3, 5, 7, 6, 10, 11"
110,R_18_last,int8,0,0.00,17,"0, 1, 2, 5, 3, 7, 4, 9, 11, 6"
111,B_31_min,int8,0,0.00,2,"1, 0"
112,B_31_max,int8,0,0.00,2,"1, 0"
113,B_31_last,int8,0,0.00,2,"1, 0"
114,R_19_min,int8,0,0.00,2,"0, 1"
115,R_19_max,int8,0,0.00,2,"0, 1"
116,R_19_last,int8,0,0.00,2,"0, 1"
117,B_32_min,int8,0,0.00,2,"0, 1"
118,B_32_max,int8,0,0.00,2,"0, 1"
119,B_32_last,int8,0,0.00,2,"0, 1"
120,S_20_min,int8,0,0.00,2,"0, 1"
121,S_20_max,int8,0,0.00,2,"0, 1"
122,S_20_last,int8,0,0.00,2,"0, 1"
123,R_20_min,int8,0,0.00,13,"0, 1, -1, 2, 3, 4, 5, 6, 10, 8"
124,R_20_max,int8,0,0.00,40,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
125,R_20_last,int8,0,0.00,33,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
126,R_21_min,int8,0,0.00,2,"0, 1"
127,R_21_max,int8,0,0.00,2,"0, 1"
128,R_21_last,int8,0,0.00,2,"0, 1"
129,B_33_min,int8,0,0.00,3,"0, 1, -1"
130,B_33_max,int8,0,0.00,3,"1, 0, -1"
131,B_33_last,int8,0,0.00,3,"1, 0, -1"
132,D_89_min,int8,0,0.00,10,"0, -1, 1, 2, 3, 4, 5, 6, 9, 8"
133,D_89_max,int8,0,0.00,11,"0, 1, 2, 3, -1, 4, 5, 6, 9, 7"
134,D_89_last,int8,0,0.00,11,"0, 1, 2, -1, 3, 4, 5, 6, 9, 7"
135,R_22_min,int8,0,0.00,2,"0, 1"
136,R_22_max,int8,0,0.00,2,"0, 1"
137,R_22_last,int8,0,0.00,2,"0, 1"
138,R_23_min,int8,0,0.00,1,0
139,R_23_max,int8,0,0.00,2,"0, 1"
140,R_23_last,int8,0,0.00,2,"0, 1"
141,D_91_min,int8,0,0.00,7,"0, -1, 1, 2, 3, 4, 5"
142,D_91_max,int8,0,0.00,8,"0, 1, -1, 2, 3, 4, 5, 6"
143,D_91_last,int8,0,0.00,7,"0, 1, -1, 2, 3, 4, 5"
144,D_92_min,int8,0,0.00,3,"0, 1, 2"
145,D_92_max,int8,0,0.00,3,"0, 1, 2"
146,D_92_last,int8,0,0.00,3,"0, 1, 2"
147,D_93_min,int8,0,0.00,2,"0, 1"
148,D_93_max,int8,0,0.00,2,"0, 1"
149,D_93_last,int8,0,0.00,2,"0, 1"
150,D_94_min,int8,0,0.00,2,"0, 1"
151,D_94_max,int8,0,0.00,2,"0, 1"
152,D_94_last,int8,0,0.00,2,"0, 1"
153,R_24_min,int8,0,0.00,2,"0, 1"
154,R_24_max,int8,0,0.00,2,"0, 1"
155,R_24_last,int8,0,0.00,2,"0, 1"
156,R_25_min,int8,0,0.00,2,"0, 1"
157,R_25_max,int8,0,0.00,2,"0, 1"
158,R_25_last,int8,0,0.00,2,"0, 1"
159,D_96_min,int8,0,0.00,2,"0, 1"
160,D_96_max,int8,0,0.00,2,"0, 1"
161,D_96_last,int8,0,0.00,2,"0, 1"
162,D_103_min,int8,0,0.00,3,"0, 1, -1"
163,D_103_max,int8,0,0.00,3,"1, 0, -1"
164,D_103_last,int8,0,0.00,3,"0, 1, -1"
165,D_107_min,int8,0,0.00,15,"0, 1, -1, 2, 3, 4, 5, 6, 7, 9"
166,D_107_max,int8,0,0.00,18,"0, 1, 2, 3, 4, -1, 5, 6, 7, 8"
167,D_107_last,int8,0,0.00,15,"0, 1, 2, 3, -1, 4, 5, 6, 7, 8"
168,D_108_min,int8,0,0.00,2,"-1, 0"
169,D_108_max,int8,0,0.00,11,"-1, 0, 1, 2, 3, 4, 5, 6, 8, 7"
170,D_108_last,int8,0,0.00,7,"-1, 0, 1, 2, 3, 4, 7"
171,D_109_min,int8,0,0.00,3,"0, -1, 1"
172,D_109_max,int8,0,0.00,3,"0, 1, -1"
173,D_109_last,int8,0,0.00,3,"0, 1, -1"
174,D_111_min,int8,0,0.00,4,"-1, 2, 1, 0"
175,D_111_max,int8,0,0.00,4,"-1, 2, 1, 0"
176,D_111_last,int8,0,0.00,4,"-1, 2, 1, 0"
177,D_113_min,int8,0,0.00,14,"0, 1, -1, 2, 3, 4, 5, 6, 7, 8"
178,D_113_max,int8,0,0.00,21,"0, 1, 2, 3, 4, 5, -1, 6, 7, 8"
179,D_113_last,int8,0,0.00,18,"0, 1, 2, 3, 4, -1, 5, 6, 7, 8"
180,D_122_min,int8,0,0.00,15,"1, 2, -1, 3, 4, 5, 0, 6, 7, 8"
181,D_122_max,int8,0,0.00,16,"1, 2, 3, 4, 5, 6, 7, -1, 8, 0"
182,D_122_last,int8,0,0.00,16,"1, 2, 3, 4, 5, 6, -1, 7, 0, 8"
183,D_123_min,int8,0,0.00,3,"0, -1, 1"
184,D_123_max,int8,0,0.00,9,"0, 1, -1, 2, 3, 55, 5, 6, 104"
185,D_123_last,int8,0,0.00,7,"0, 1, -1, 2, 3, 37, 6"
186,D_125_min,int8,0,0.00,5,"0, -1, 1, 2, 3"
187,D_125_max,int8,0,0.00,12,"0, 1, 2, -1, 3, 4, 5, 8, 10, 7"
188,D_125_last,int8,0,0.00,7,"0, 1, -1, 2, 3, 4, 6"
189,D_127_min,int8,0,0.00,2,"0, 1"
190,D_127_max,int8,0,0.00,2,"0, 1"
191,D_127_last,int8,0,0.00,2,"0, 1"
192,D_129_min,int8,0,0.00,3,"0, 1, -1"
193,D_129_max,int8,0,0.00,3,"0, 1, -1"
194,D_129_last,int8,0,0.00,3,"0, 1, -1"
195,B_41_min,int8,0,0.00,10,"0, 1, -1, 2, 3, 4, 5, 6, 8, 10"
196,B_41_max,int8,0,0.00,19,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"
197,B_41_last,int8,0,0.00,18,"0, 1, 2, 3, 4, 5, 6, 7, 8, 10"
198,R_28_min,int8,0,0.00,2,"0, 1"
199,R_28_max,int8,0,0.00,2,"0, 1"
200,R_28_last,int8,0,0.00,2,"0, 1"
201,D_135_min,int8,0,0.00,3,"-1, 0, 1"
202,D_135_max,int8,0,0.00,3,"-1, 0, 1"
203,D_135_last,int8,0,0.00,3,"-1, 0, 1"
204,D_136_min,int8,0,0.00,8,"-1, 1, 0, 2, 3, 4, 5, 6"
205,D_136_max,int8,0,0.00,9,"-1, 1, 0, 2, 3, 4, 5, 6, 7"
206,D_136_last,int8,0,0.00,9,"-1, 1, 0, 2, 3, 4, 5, 6, 7"
207,D_137_min,int8,0,0.00,3,"-1, 0, 1"
208,D_137_max,int8,0,0.00,3,"-1, 0, 1"
209,D_137_last,int8,0,0.00,3,"-1, 0, 1"
210,D_138_min,int8,0,0.00,5,"-1, 0, 1, 2, 3"
211,D_138_max,int8,0,0.00,8,"-1, 0, 1, 2, 3, 4, 5, 6"
212,D_138_last,int8,0,0.00,7,"-1, 0, 1, 2, 3, 4, 5"
213,D_139_min,int8,0,0.00,3,"0, -1, 1"
214,D_139_max,int8,0,0.00,3,"0, 1, -1"
215,D_139_last,int8,0,0.00,3,"0, 1, -1"
216,D_140_min,int8,0,0.00,3,"0, -1, 1"
217,D_140_max,int8,0,0.00,2,"0, 1"
218,D_140_last,int8,0,0.00,2,"0, 1"
219,D_143_min,int8,0,0.00,3,"0, -1, 1"
220,D_143_max,int8,0,0.00,3,"0, 1, -1"
221,D_143_last,int8,0,0.00,3,"0, 1, -1"
222,D_145_min,int8,0,0.00,45,"0, -1, 1, 2, 3, 4, 5, 6, 7, 8"
223,D_145_max,int8,0,0.00,46,"0, 1, 2, 3, 4, 5, 6, 7, -1, 8"
224,D_145_last,int8,0,0.00,45,"0, 1, 2, 3, 4, 5, 6, -1, 7, 8"
225,B_30_last,int8,0,0.00,4,"0, 1, 2, -1"
226,B_38_last,int8,0,0.00,8,"2, 3, 1, 5, 7, 4, 6, -1"
227,D_114_last,int8,0,0.00,3,"1, 0, -1"
228,D_116_last,int8,0,0.00,3,"0, -1, 1"
229,D_117_last,int8,0,0.00,8,"0, 4, 5, 3, 6, 7, 2, -1"
230,D_120_last,int8,0,0.00,3,"0, 1, -1"
231,D_126_last,int8,0,0.00,2,"2, 1"
232,D_63_last,int8,0,0.00,6,"3, 0, 4, 1, 2, 5"
233,D_64_last,int8,0,0.00,4,"0, 3, 2, -1"
234,D_66_last,int8,0,0.00,2,"-1, 1"
235,D_68_last,int8,0,0.00,7,"6, 5, 3, 4, 2, 1, -1"
236,target,int8,0,0.00,2,"0, 1"
237,D_39_min,int16,0,0.00,58,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
238,D_39_max,int16,0,0.00,170,"0, 1, 31, 24, 22, 23, 21, 20, 19, 18"
239,D_39_last,int16,0,0.00,126,"0, 1, 3, 8, 4, 2, 6, 31, 7, 5"
240,B_4_min,int16,0,0.00,176,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
241,B_4_max,int16,0,0.00,245,"4, 3, 5, 6, 2, 7, 8, 1, 0, 9"
242,B_4_last,int16,0,0.00,222,"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
243,D_49_min,int16,0,0.00,144,"-1, 3, 2, 4, 1, 5, 6, 7, 8, 9"
244,D_49_max,int16,0,0.00,209,"-1, 5, 1, 2, 3, 10, 4, 6, 8, 7"
245,D_49_last,int16,0,0.00,181,"-1, 1, 2, 3, 4, 5, 6, 7, 8, 9"
246,S_8_min,int16,0,0.00,32,"0, 528, 996, 1021, 1544, 322, 2380, 379, 1511, 1454"
247,S_8_max,int16,0,0.00,32,"0, 2380, 1021, 3166, 2096, 1544, 2218, 1880, 1468, 996"
248,S_8_last,int16,0,0.00,32,"0, 1021, 2380, 528, 996, 1544, 2218, 1511, 2096, 1454"
249,D_65_min,int16,0,0.00,141,"0, 3, 7, 1, 2, 11, 8, 5, 15, 10"
250,D_65_max,int16,0,0.00,750,"0, 1, 7, 2, 3, 4, 5, 6, 8, 10"
251,D_65_last,int16,0,0.00,498,"0, 7, 2, 1, 3, 4, 5, 6, 8, 10"
252,S_13_min,int16,0,0.00,13,"0, 435, 290, 702, 1034, 524, 872, 39, 643, 415"
253,S_13_max,int16,0,0.00,13,"435, 0, 1034, 702, 290, 872, 524, 544, 711, 643"
254,S_13_last,int16,0,0.00,13,"0, 435, 290, 1034, 702, 872, 524, 643, 711, 544"
255,D_106_min,int16,0,0.00,51,"-1, 0, 2, 3, 1, 4, 5, 6, 7, 8"
256,D_106_max,int16,0,0.00,284,"-1, 2, 3, 4, 1, 0, 5, 6, 7, 8"
257,D_106_last,int16,0,0.00,133,"-1, 2, 0, 3, 1, 4, 5, 6, 7, 8"
258,R_26_min,int16,0,0.00,114,"-1, 0, 1, 2, 3, 4, 5, 6, 7, 8"
259,R_26_max,int16,0,0.00,139,"-1, 0, 1, 2, 3, 4, 5, 6, 7, 8"
260,R_26_last,int16,0,0.00,126,"-1, 0, 1, 2, 3, 4, 5, 6, 7, 8"
261,D_124_min,int16,0,0.00,52,"-1, 5, 4, 6, 3, 7, 8, 2, 9, 10"
262,D_124_max,int16,0,0.00,57,"5, 4, 6, 3, 7, 8, 2, 9, 10, 11"
263,D_124_last,int16,0,0.00,54,"5, 4, 3, 6, 7, 8, 2, 9, 10, 1"
264,P_2_std,float32,5120,1.12,448740,"0.0, 36.7975, 0.0409, 0.0377, 0.0345, 35.3233, 0.0725, 0.0501, 0.0485, 0.0289"
265,B_1_std,float32,5120,1.12,451705,"0.0162, 0.0065, 0.0157, 0.0029, 0.0161, 0.1161, 0.007, 0.0359, 0.1389, 0.0555"
266,B_2_std,float32,5120,1.12,450189,"0.0028, 0.3164, 0.0829, 0.266, 0.0714, 0.0026, 0.0025, 0.3763, 0.3168, 0.003"
267,R_1_std,float32,5120,1.12,445872,"0.0028, 0.1391, 0.1384, 0.1396, 0.1382, 0.0027, 0.1865, 0.003, 0.1376, 0.0025"
268,S_3_std,float32,5120,1.12,381245,"0.0, 65.9867, 65.9868, 65.9899, 35.2718, 35.2693, 65.9852, 65.9873, 35.2699, 65.9846"
269,D_41_std,float32,5120,1.12,106834,"0.0, 38.2919, 42.3333, 44.9013, 73.3235, 35.2235, 51.8475, 40.1609, 48.0015, 56.7961"
270,B_3_std,float32,5120,1.12,451018,"0.0027, 0.0033, 0.0034, 0.003, 0.0052, 0.0033, 0.1446, 0.0029, 0.0033, 0.0029"
271,D_42_std,float32,5120,1.12,102424,"0.0, 64.3117, 64.312, 35.2252, 47.6957, 35.225, 64.3122, 64.3127, 64.3147, 64.3155"
272,D_43_std,float32,5120,1.12,322690,"0.0, 65.9145, 65.915, 65.9151, 64.3261, 65.9149, 65.9149, 64.3266, 64.3262, 35.2336"
273,D_45_std,float32,5120,1.12,433553,"35.2283, 35.2284, 0.0103, 0.009, 38.2969, 38.2967, 0.0089, 0.0098, 42.3379, 0.0086"
274,B_5_std,float32,5120,1.12,451794,"0.0033, 0.0028, 0.003, 0.0216, 0.0029, 0.0087, 0.003, 0.0343, 0.0129, 0.0033"
275,D_46_std,float32,5120,1.12,360570,"0.0, 35.3491, 64.5362, 66.1319, 35.3489, 35.3476, 55.8897, 35.3479, 66.1289, 35.3497"
276,D_47_std,float32,5120,1.12,442978,"0.0066, 0.0071, 0.0075, 0.0079, 0.0075, 0.008, 0.0074, 0.007, 0.0069, 0.0079"
277,D_48_std,float32,5120,1.12,406824,"0.0, 35.2286, 35.23, 35.2335, 35.2281, 64.3201, 35.2262, 65.9027, 35.2543, 35.2315"
278,B_6_std,float32,5120,1.12,451777,"0.0028, 0.0034, 0.0637, 0.0682, 0.0086, 0.0033, 0.0191, 0.0041, 0.0053, 0.0152"
279,B_7_std,float32,5120,1.12,451639,"0.0728, 0.1408, 0.0088, 0.0164, 0.087, 0.0069, 0.0091, 0.0112, 0.0228, 0.014"
280,B_8_std,float32,5120,1.12,224382,"0.0, 35.2235, 73.3235, 89.8026, 61.0088, 55.6932, 64.309, 36.6617, 35.5021, 59.3216"
281,D_50_std,float32,5120,1.12,201574,"0.0, 35.236, 35.2411, 35.2457, 35.241, 35.244, 35.2434, 35.2364, 35.2438, 35.2354"
282,B_9_std,float32,5120,1.12,451203,"0.0029, 0.003, 0.003, 0.0029, 0.1066, 0.003, 0.0027, 0.0028, 0.0026, 0.0027"
283,D_52_std,float32,5120,1.12,445278,"0.0, 35.2348, 35.2388, 35.2374, 0.0026, 0.0029, 0.0031, 0.003, 35.235, 0.0028"
284,P_3_std,float32,5120,1.12,431787,"0.0, 66.0594, 66.2139, 35.3766, 68.2005, 68.2146, 35.3998, 35.3994, 68.2023, 35.4053"
285,B_10_std,float32,5120,1.12,451940,"0.0645, 0.0743, 0.0181, 0.0098, 0.0208, 0.0668, 0.0346, 0.045, 0.0087, 0.0278"
286,D_53_std,float32,5120,1.12,124243,"0.0, 65.8997, 64.3112, 64.3114, 64.3116, 64.3115, 65.9, 64.3113, 35.2249, 64.3113"
287,S_5_std,float32,5120,1.12,451514,"0.0031, 0.0026, 0.0029, 0.0029, 0.0217, 0.024, 0.003, 0.0179, 0.0026, 0.0034"
288,B_11_std,float32,5120,1.12,451724,"0.01, 0.003, 0.0098, 0.0175, 0.0324, 0.0026, 0.0161, 0.0035, 0.0225, 0.0327"
289,D_54_std,float32,5120,1.12,24734,"0.0, 38.5935, 42.6667, 45.2548, 35.5008, 40.4772, 52.2558, 48.3795, 36.9504, 73.9008"
290,S_7_std,float32,5120,1.12,382859,"0.0, 65.9556, 35.2543, 35.2519, 65.9527, 35.252, 64.3639, 65.9557, 65.9515, 35.2537"
291,B_12_std,float32,5120,1.12,450410,"0.0026, 0.0032, 0.003, 0.0029, 0.0027, 0.0032, 0.0024, 0.0033, 0.0031, 0.0025"
292,D_55_std,float32,5120,1.12,426350,"0.0, 65.8997, 65.8996, 65.8996, 65.8996, 65.8998, 65.8997, 65.8993, 65.8995, 65.8996"
293,D_56_std,float32,5120,1.12,227969,"0.0, 55.7211, 55.7239, 55.7239, 55.735, 55.7198, 55.7196, 64.4071, 64.3417, 64.374"
294,B_13_std,float32,5120,1.12,446655,"0.0, 35.2281, 35.2281, 40.165, 35.2285, 35.2295, 35.2285, 35.231, 35.2291, 35.2283"
295,D_58_std,float32,5120,1.12,450890,"0.0028, 0.0025, 0.1104, 0.0029, 0.0566, 0.1465, 0.0031, 0.08, 0.0035, 0.0029"
296,S_9_std,float32,5120,1.12,214674,"0.0, 35.2257, 35.226, 35.2253, 35.2257, 35.2258, 35.2255, 35.2258, 35.2256, 35.2257"
297,B_14_std,float32,5120,1.12,451578,"0.003, 0.0043, 0.0055, 0.003, 0.0031, 0.0098, 0.0029, 0.0024, 0.0026, 0.0242"
298,D_60_std,float32,5120,1.12,451789,"0.0313, 0.0638, 0.0029, 0.2771, 0.1691, 0.0031, 0.003, 0.2772, 0.0395, 0.449"
299,D_61_std,float32,5120,1.12,417455,"0.0, 35.2283, 64.3154, 35.2276, 47.6985, 35.2357, 35.2299, 47.6981, 64.3126, 35.2284"
300,B_15_std,float32,5120,1.12,443808,"0.0, 35.2248, 35.2247, 35.2248, 35.2249, 35.2248, 35.225, 35.2249, 35.2247, 35.2252"
301,D_62_std,float32,5120,1.12,407743,"0.0, 35.2353, 35.2275, 35.2269, 35.2276, 35.2275, 47.696, 35.2272, 35.232, 35.2263"
302,B_17_std,float32,5120,1.12,215002,"0.0, 65.9863, 65.9868, 65.9865, 64.3117, 65.9861, 65.987, 65.9867, 65.9865, 65.9867"
303,B_18_std,float32,5120,1.12,367652,"0.0, 0.1318, 0.1316, 0.085, 0.1594, 0.2404, 0.0975, 0.1155, 0.1477, 0.1061"
304,S_12_std,float32,5120,1.12,450591,"0.0028, 0.073, 0.003, 0.0032, 0.0023, 0.0031, 0.0029, 0.0029, 0.0025, 0.0031"
305,R_6_std,float32,5120,1.12,442360,"0.0027, 0.003, 0.0027, 0.0029, 0.003, 0.0025, 0.0027, 0.0031, 0.003, 0.0029"
306,B_21_std,float32,5120,1.12,440167,"0.0027, 0.0032, 0.0028, 0.0028, 0.0028, 0.0027, 0.0029, 0.0029, 0.0027, 0.0029"
307,D_69_std,float32,5120,1.12,379816,"0.0, 47.6947, 47.6946, 47.6947, 47.6947, 47.6948, 47.6947, 47.6947, 47.6948, 47.6945"
308,D_71_std,float32,5120,1.12,447490,"0.0047, 0.0035, 0.0031, 0.0029, 0.0033, 0.003, 0.0027, 0.0028, 0.0029, 0.0026"
309,B_23_std,float32,5120,1.12,451804,"0.0912, 0.0079, 0.0084, 0.0173, 0.0115, 0.0369, 0.0533, 0.0102, 0.0094, 0.0326"
310,D_73_std,float32,5120,1.12,7940,"0.0, 35.2483, 64.3277, 35.2627, 64.3214, 35.2387, 65.9602, 35.2603, 35.2549, 65.9185"
311,P_4_std,float32,5120,1.12,110299,"0.0, 0.2666, 0.2662, 0.3612, 0.4864, 0.3608, 0.2664, 0.2665, 0.2667, 0.2664"
312,D_76_std,float32,5120,1.12,54348,"0.0, 55.6962, 64.3115, 35.2251, 64.3112, 64.3123, 65.8996, 64.3116, 55.6954, 65.9001"
313,B_24_std,float32,5120,1.12,440569,"0.0032, 0.0031, 0.0031, 0.0025, 0.0028, 0.0029, 0.0029, 0.0022, 0.0027, 0.0026"
314,R_7_std,float32,5120,1.12,52507,"0.0, 11.2053, 0.4453, 0.1617, 0.2958, 0.4673, 0.2224, 0.3402, 0.6188, 0.2662"
315,D_77_std,float32,5120,1.12,289615,"0.0, 73.3264, 64.3164, 35.229, 35.229, 35.229, 73.3263, 65.9098, 35.2277, 64.3166"
316,B_25_std,float32,5120,1.12,450311,"0.0, 35.2247, 35.2247, 35.2247, 35.2249, 35.225, 35.2248, 35.2248, 35.2251, 35.225"
317,B_26_std,float32,5120,1.12,444057,"48.0032, 0.0034, 35.2249, 38.2935, 48.0034, 35.2248, 42.3347, 0.0033, 0.0029, 0.0027"
318,S_16_std,float32,5120,1.12,440355,"0.003, 0.0031, 0.0033, 0.0028, 0.0031, 0.0028, 0.003, 0.0023, 0.0029, 0.0032"

In [6]:
# Numeric Feature Statistics
numeric_stats

                  count         mean          std           min           max
P_2_mean       458913.0    -0.929136    11.019608 -1.270000e+02      1.009993
P_2_std        453793.0     1.831865     9.666891  0.000000e+00     90.515991
P_2_min        458913.0    -4.569654    25.097486 -1.270000e+02      1.009993
P_2_max        458913.0     0.039117     9.279095 -1.270000e+02      1.010000
P_2_last       458913.0    -0.190504    10.236442 -1.270000e+02      1.009998
D_39_mean      458913.0     4.987931     5.605566  0.000000e+00    156.000000
D_39_std       453793.0     5.725742     5.302279  0.000000e+00    103.944697
D_39_min       458913.0     0.214001     2.092028  0.000000e+00    151.000000
D_39_max       458913.0    16.754258    16.100298  0.000000e+00    183.000000
D_39_last      458913.0     6.680637    13.672650  0.000000e+00    170.000000
B_1_mean       458913.0     0.126626     0.198291 -1.891373e+00      1.324059
B_1_std        453793.0     0.049245     0.076681  7.810338e-07      3.798284
B_1_min        458913.0     0.067189     0.153841 -7.588799e+00      1.324059
B_1_max        458913.0     0.209491     0.273704 -9.092669e-02      1.324060
B_1_last       458913.0     0.139027     0.231266 -3.571172e+00      1.324059
B_2_mean       458913.0     0.525105     1.933268 -1.270000e+02      1.009981
B_2_std        453793.0     0.351073     3.343542  1.685874e-07     90.515472
B_2_min        458913.0    -0.126860     8.437573 -1.270000e+02      1.009981
B_2_max        458913.0     0.793593     1.099251 -1.270000e+02      1.010000
B_2_last       458913.0     0.582994     1.126714 -1.270000e+02      1.010000
R_1_mean       458913.0     0.080193     0.158306  6.440720e-07      2.006159
R_1_std        453793.0     0.094783     0.145211  1.102733e-06      1.589978
R_1_min        458913.0     0.007817     0.056442  1.534223e-09      2.002352
R_1_max        458913.0     0.274888     0.424056  6.440720e-07      3.256284
R_1_last       458913.0     0.107396     0.278639  5.646122e-08      2.759738
S_3_mean       458913.0   -22.959566    44.513290 -1.270000e+02      3.860899
S_3_std        453793.0     8.706609    20.050467  0.000000e+00     90.314537
S_3_min        458913.0   -36.337399    57.515652 -1.270000e+02      2.812956
S_3_max        458913.0   -15.379480    41.865887 -1.270000e+02      5.482888
S_3_last       458913.0   -23.328024    49.419098 -1.270000e+02      3.993525
D_41_mean      458913.0    -0.041339     1.897190 -1.270000e+02      5.731491
D_41_std       453793.0     0.257508     3.335064  0.000000e+00     90.164764
D_41_min       458913.0    -0.545718     8.400262 -1.270000e+02      4.637304
D_41_max       458913.0     0.136651     1.106529 -1.270000e+02      8.988807
D_41_last      458913.0     0.086727     1.088270 -1.270000e+02      8.988807
B_3_mean       458913.0     0.032307     1.904175 -1.270000e+02      1.500520
B_3_std        453793.0     0.262341     3.334713  2.627593e-07     90.380913
B_3_min        458913.0    -0.494223     8.404611 -1.270000e+02      1.490495
B_3_max        458913.0     0.201178     1.087962 -1.270000e+02      1.625262
B_3_last       458913.0     0.146240     1.075717 -1.270000e+02      1.596532
D_42_mean      458913.0  -103.188484    45.710442 -1.270000e+02      4.185518
D_42_std       453793.0     7.215286    19.090313  0.000000e+00     91.351929
D_42_min       458913.0  -111.893166    41.146713 -1.270000e+02      4.185300
D_42_max       458913.0   -95.534729    54.883717 -1.270000e+02      4.191119
D_42_last      458913.0  -110.397209    42.847038 -1.270000e+02      4.186139
D_43_mean      458913.0   -41.203842    53.342709 -1.270000e+02      6.801702
D_43_std       453793.0    13.772462    24.525764  0.000000e+00     92.760475
D_43_min       458913.0   -59.635078    63.428535 -1.270000e+02      4.920116
D_43_max       458913.0   -28.272682    53.136986 -1.270000e+02     10.111619
D_43_last      458913.0   -37.056561    57.859901 -1.270000e+02      9.185312
D_44_mean      458913.0     0.810165     1.655920 -1.000000e+00     40.769231
D_44_std       453793.0     0.356857     0.557286  0.000000e+00     10.411409
D_44_min       458913.0     0.353601     1.287414 -1.000000e+00     32.000000
D_44_max       458913.0     1.296583     2.176612 -1.000000e+00     45.000000
D_44_last      458913.0     0.968495     1.979220 -1.000000e+00     32.000000
B_4_mean       458913.0    12.859543    16.297495  0.000000e+00    278.461538
B_4_std        453793.0     3.593694     4.169859  0.000000e+00    427.521374
B_4_min        458913.0     8.090782    13.599553  0.000000e+00    272.000000
B_4_max        458913.0    18.612508    20.232756  0.000000e+00   1544.000000
B_4_last       458913.0    14.357717    18.762732  0.000000e+00    345.000000
D_45_mean      458913.0     0.142123     1.915811 -1.270000e+02      1.590517
D_45_std       453793.0     0.227699     3.336508  1.277576e-07     89.918915
D_45_min       458913.0    -0.341153     8.418890 -1.270000e+02      1.580474
D_45_max       458913.0     0.248230     1.073784 -1.270000e+02      1.610002
D_45_last      458913.0     0.232989     1.073233 -1.270000e+02      1.610002
B_5_mean       458913.0     0.080100     0.311481  6.334021e-06     89.471909
B_5_std        453793.0     0.062304     0.233551  1.363187e-07     48.741337
B_5_min        458913.0     0.020527     0.090527  2.804822e-11     28.871983
B_5_max        458913.0     0.215850     0.759157  6.334021e-06    144.207016
B_5_last       458913.0     0.078305     0.339889  1.545439e-07     50.097870
R_2_mean       458913.0     0.042812     0.137046  0.000000e+00      1.000000
R_2_std        453793.0     0.058962     0.145621  0.000000e+00      0.707107
R_2_min        458913.0     0.003319     0.057513  0.000000e+00      1.000000
R_2_max        458913.0     0.150292     0.357358  0.000000e+00      1.000000
R_2_last       458913.0     0.076897     0.266428  0.000000e+00      1.000000
D_46_mean      458913.0   -32.399765    50.101692 -1.270000e+02      4.357760
D_46_std       453793.0    11.400780    23.333248  0.000000e+00     90.734879
D_46_min       458913.0   -46.695381    61.455154 -1.270000e+02      1.744142
D_46_max       458913.0   -21.629745    48.405216 -1.270000e+02     16.319901
D_46_last      458913.0   -25.945578    51.674385 -1.270000e+02     12.529510
D_47_mean      458913.0     0.396872     0.233740 -2.660887e-02      1.372795
D_47_std       453793.0     0.016217     0.033736  3.793216e-07      0.710074
D_47_min       458913.0     0.370751     0.238749 -2.662164e-02      1.362421
D_47_max       458913.0     0.414309     0.236754 -2.660887e-02      1.643096
D_47_last      458913.0     0.398901     0.232237 -2.661557e-02      1.383963
D_48_mean      458913.0   -16.505653    36.477264 -1.270000e+02      8.834923
D_48_std       453793.0    11.194072    21.910690  0.000000e+00     90.799957
D_48_min       458913.0   -34.923344    56.939823 -1.270000e+02      8.055927
D_48_max       458913.0    -7.496152    30.934286 -1.270000e+02      8.971425
D_48_last      458913.0   -15.691833    42.334518 -1.270000e+02      8.964579
D_49_mean      458913.0     0.413220     6.700744 -1.000000e+00   1153.285714
D_49_std       453793.0     0.551988     3.894197  0.000000e+00   1490.580951
D_49_min       458913.0    -0.260291     4.578934 -1.000000e+00    597.000000
D_49_max       458913.0     1.124869    10.955914 -1.000000e+00   3254.000000
D_49_last      458913.0     0.603197     8.018041 -1.000000e+00   1952.000000
B_6_mean       458913.0     0.126920     1.907863 -1.270000e+02    347.662598
B_6_std        453793.0     0.114721     2.037062  1.928218e-06    380.350372
B_6_min        458913.0     0.023142     2.883220 -1.270000e+02    117.375443
B_6_max        458913.0     0.314879     3.757668 -1.270000e+02   1214.516968
B_6_last       458913.0     0.138191     1.422422 -1.270000e+02    194.110001
B_7_mean       458913.0     0.188955     0.216478 -2.227343e-01      1.252738
B_7_std        453793.0     0.060943     0.074211  2.128416e-06      0.884097
B_7_min        458913.0     0.114587     0.172018 -2.652749e+00      1.252738
B_7_max        458913.0     0.293289     0.294457 -9.198263e-02      1.252750
B_7_last       458913.0     0.202722     0.244797 -2.652749e+00      1.252748
B_8_mean       458913.0    -0.737429    10.921172 -1.270000e+02      1.009850
B_8_std        453793.0     0.775273     6.188535  0.000000e+00     90.516068
B_8_min        458913.0    -2.277650    18.412128 -1.270000e+02      1.009850
B_8_max        458913.0    -0.308769    10.253059 -1.270000e+02      1.019079
B_8_last       458913.0    -0.652052    11.993340 -1.270000e+02      1.012483
D_50_mean      458913.0   -73.185791    60.754379 -1.270000e+02     76.278618
D_50_std       453793.0     5.265988    16.102116  0.000000e+00     96.967735
D_50_min       458913.0   -81.604668    60.919670 -3.064871e+02     50.914883
D_50_max       458913.0   -68.814247    63.383450 -1.270000e+02    244.042664
D_50_last      458913.0   -72.495697    62.936913 -1.270000e+02     81.353691
D_51_mean      458913.0     0.402870     0.652089  0.000000e+00      7.615385
D_51_std       453793.0     0.170034     0.254844  0.000000e+00      2.160247
D_51_min       458913.0     0.226272     0.509941  0.000000e+00      7.000000
D_51_max       458913.0     0.657913     0.905609  0.000000e+00      8.000000
D_51_last      458913.0     0.418591     0.725170  0.000000e+00      7.000000
B_9_mean       458913.0     0.191939     0.253260  4.469705e-06     15.465446
B_9_std        453793.0     0.071451     0.117983  1.286137e-06      9.778132
B_9_min        458913.0     0.100500     0.193550  6.726070e-09     14.620032
B_9_max        458913.0     0.307444     0.406829  4.469705e-06     27.424858
B_9_last       458913.0     0.205842     0.300132  3.883418e-08     27.424858
R_3_mean       458913.0     1.257979     1.872069  0.000000e+00     72.875000
R_3_std        453793.0     0.790218     0.970811  0.000000e+00     34.547845
R_3_min        458913.0     0.341986     1.051012  0.000000e+00     52.000000
R_3_max        458913.0     2.475936     3.193805  0.000000e+00    116.000000
R_3_last       458913.0     1.134540     2.122949  0.000000e+00    103.000000
D_52_mean      458913.0    -0.929779     7.884708 -1.270000e+02      1.009779
D_52_std       453793.0     1.897333     9.615582  0.000000e+00     90.516640
D_52_min       458913.0    -5.161878    25.468288 -1.270000e+02      1.009779
D_52_max       458913.0    -0.122387     6.342709 -1.270000e+02      1.010000
D_52_last      458913.0    -0.163903     6.604351 -1.270000e+02      1.009999
P_3_mean       458913.0   -12.389260    32.301785 -1.270000e+02      1.541687
P_3_std        453793.0     8.392491    20.926018  0.000000e+00     90.499916
P_3_min        458913.0   -23.115570    49.442081 -1.270000e+02      1.270046
P_3_max        458913.0    -5.236796    27.012951 -1.270000e+02      2.428051
P_3_last       458913.0    -5.595394    27.386063 -1.270000e+02      1.995108
B_10_mean      458913.0     0.232999     2.156285 -2.956287e-03   1024.816650
B_10_std       453793.0     0.226861     4.909026  2.339150e-06   1896.462402
B_10_min       458913.0     0.095055     0.123792 -2.958481e-03     30.590670
B_10_max       458913.0     0.805826    14.369667 -2.956287e-03   4097.440918
B_10_last      458913.0     0.228289     3.941258 -2.956287e-03   1259.176025
D_53_mean      458913.0   -95.012421    51.828125 -1.270000e+02      5.012737
D_53_std       453793.0     6.910735    18.677967  0.000000e+00     90.240189
D_53_min       458913.0  -102.823303    49.868740 -1.270000e+02      3.493986
D_53_max       458913.0   -87.087746    59.006454 -1.270000e+02      7.901939
D_53_last      458913.0   -90.165451    57.666821 -1.270000e+02      6.969272
S_5_mean       458913.0     0.085818     0.308089  1.366996e-06     64.303169
S_5_std        453793.0     0.059402     0.253509  1.723740e-07     57.375355
S_5_min        458913.0     0.022695     0.121218  8.168135e-09     26.309755
S_5_max        458913.0     0.197881     0.831167  1.366996e-06    206.875275
S_5_last       458913.0     0.084733     0.434215  1.803506e-08    129.275986
B_11_mean      458913.0     0.112921     0.194337  1.283050e-05      1.767753
B_11_std       453793.0     0.046009     0.076916  1.661508e-06      1.003325
B_11_min       458913.0     0.058476     0.147023  2.017814e-08      1.767753
B_11_max       458913.0     0.190893     0.273552  1.283050e-05      1.970375
B_11_last      458913.0     0.125696     0.228291  2.028374e-07      1.767753
S_6_mean       458913.0     0.267788     0.376220  0.000000e+00      1.000000
S_6_std        453793.0     0.134207     0.209527  0.000000e+00      0.707107
S_6_min        458913.0     0.156271     0.363113  0.000000e+00      1.000000
S_6_max        458913.0     0.454498     0.497926  0.000000e+00      1.000000
S_6_last       458913.0     0.237537     0.425575  0.000000e+00      1.000000
D_54_mean      458913.0     0.883786     1.905410 -1.270000e+02      1.000000
D_54_std       453793.0     0.234811     3.361181  0.000000e+00     90.509666
D_54_min       458913.0     0.382982     8.464557 -1.270000e+02      1.000000
D_54_max       458913.0     0.987355     1.053822 -1.270000e+02      1.000000
D_54_last      458913.0     0.949939     1.070262 -1.270000e+02      1.000000
R_4_mean       458913.0     0.026358     0.096439  0.000000e+00      1.000000
R_4_std        453793.0     0.044095     0.127356  0.000000e+00      0.707107
R_4_min        458913.0     0.000867     0.029437  0.000000e+00      1.000000
R_4_max        458913.0     0.112751     0.316289  0.000000e+00      1.000000
R_4_last       458913.0     0.050572     0.219122  0.000000e+00      1.000000
S_7_mean       458913.0   -22.960621    44.515373 -1.270000e+02      2.798808
S_7_std        453793.0     8.711587    20.041975  0.000000e+00     90.263672
S_7_min        458913.0   -36.348259    57.508785 -1.270000e+02      2.420834
S_7_max        458913.0   -15.374142    41.867901 -1.270000e+02      3.948271
S_7_last       458913.0   -23.333609    49.416466 -1.270000e+02      2.902353
B_12_mean      458913.0     0.089979     0.780089  9.087858e-06    405.701660
B_12_std       453793.0     0.018817     0.151498  7.145208e-07     84.190788
B_12_min       458913.0     0.063761     0.663796  3.343624e-08    372.590210
B_12_max       458913.0     0.119150     0.884531  9.087858e-06    420.748993
B_12_last      458913.0     0.092672     0.817097  3.343624e-08    410.792908
S_8_mean       458913.0  1015.922467   821.256595  0.000000e+00   3867.000000
S_8_std        453793.0   423.178267   290.503501  0.000000e+00   2734.381923
S_8_min        458913.0   502.736724   706.689072  0.000000e+00   3867.000000
S_8_max        458913.0  1732.210358  1034.727024  0.000000e+00   3867.000000
S_8_last       458913.0   981.223957   964.216407  0.000000e+00   3867.000000
D_55_mean      458913.0    -4.485120    16.653708 -1.270000e+02      2.698071
D_55_std       453793.0     5.811583    17.716759  0.000000e+00     90.098724
D_55_min       458913.0   -12.963151    38.783695 -1.270000e+02      2.575426
D_55_max       458913.0    -0.334061     9.338118 -1.270000e+02      2.767759
D_55_last      458913.0    -8.097100    31.658474 -1.270000e+02      2.767759
D_56_mean      458913.0   -70.985809    58.243477 -1.270000e+02      8.858459
D_56_std       453793.0    11.485700    23.346504  0.000000e+00     91.520439
D_56_min       458913.0   -84.414200    60.021503 -1.270000e+02      7.219653
D_56_max       458913.0   -59.190140    63.473587 -1.270000e+02     10.956514
D_56_last      458913.0   -67.630493    63.463459 -1.270000e+02     10.873852
B_13_mean      458913.0    -2.323895    10.871063 -1.270000e+02    151.319199
B_13_std       453793.0     4.338285    14.752844  0.000000e+00    115.696754
B_13_min       458913.0   -10.969291    35.765450 -1.270000e+02     50.081223
B_13_max       458913.0    -0.287438     7.447125 -1.270000e+02    276.177826
B_13_last      458913.0    -0.331612     7.433172 -1.270000e+02    243.295837
R_5_mean       458913.0     0.060314     0.322284  0.000000e+00     26.000000
R_5_std        453793.0     0.101514     0.429174  0.000000e+00     23.678942
R_5_min        458913.0     0.002807     0.154923  0.000000e+00     26.000000
R_5_max        458913.0     0.299107     1.275486  0.000000e+00     70.000000
R_5_last       458913.0     0.143343     0.908322  0.000000e+00     70.000000
D_58_mean      458913.0     0.213228     0.244892  1.371051e-06      1.257398
D_58_std       453793.0     0.061338     0.061921  3.513994e-06      0.866555
D_58_min       458913.0     0.131164     0.205969  4.968945e-09      1.253670
D_58_max       458913.0     0.302845     0.284665  1.371051e-06      1.261945
D_58_last      458913.0     0.231353     0.271348  1.433193e-07      1.261935
S_9_mean       458913.0   -68.753792    54.025318 -1.270000e+02      2.832649
S_9_std        453793.0    22.257950    27.348682  0.000000e+00     91.805084
S_9_min        458913.0   -92.865799    56.306461 -1.270000e+02      2.832649
S_9_max        458913.0   -40.087444    59.139614 -1.270000e+02      2.839635
S_9_last       458913.0   -50.854397    62.255463 -1.270000e+02      2.832649
B_14_mean      458913.0     0.098082     0.254706 -2.097979e+00     28.260786
B_14_std       453793.0     0.036427     0.107225  1.538360e-06     18.066635
B_14_min       458913.0     0.050610     0.159530 -8.469853e+00     16.779882
B_14_max       458913.0     0.161963     0.425437 -3.050940e-01     55.011517
B_14_last      458913.0     0.106119     0.287756 -2.978449e+00     40.404064
D_59_mean      458913.0    21.491389     8.769397 -1.000000e+00     92.923077
D_59_std       453793.0     3.831157     4.233867  0.000000e+00     49.497475
D_59_min       458913.0    15.698287    10.222129 -1.000000e+00     85.000000
D_59_max       458913.0    25.581627    10.219478 -1.000000e+00    108.000000
D_59_last      458913.0    24.681855    10.115820 -1.000000e+00     92.000000
D_60_mean      458913.0     0.378060     0.332958  2.877784e-06      1.009961
D_60_std       453793.0     0.119985     0.129919  1.095818e-06      0.712933
D_60_min       458913.0     0.222085     0.308897  5.905030e-09      1.009961
D_60_max       458913.0     0.555417     0.388536  2.877784e-06      1.010000
D_60_last      458913.0     0.364558     0.365668  8.831968e-08      1.010000
D_61_mean      458913.0   -13.195737    33.167576 -1.270000e+02     73.220940
D_61_std       453793.0     9.243720    20.583851  0.000000e+00    250.452820
D_61_min       458913.0   -27.410391    52.551037 -1.270000e+02     15.053741
D_61_max       458913.0    -5.291519    26.740669 -1.270000e+02    868.515442
D_61_last      458913.0   -12.974374    39.130703 -1.270000e+02     46.417835
B_15_mean      458913.0    -0.132668     4.642642 -1.270000e+02     33.409081
B_15_std       453793.0     0.073705     1.387610  0.000000e+00     69.887192
B_15_min       458913.0    -0.327049     6.661623 -1.270000e+02     19.836473
B_15_max       458913.0    -0.077619     4.631502 -1.270000e+02     65.037430
B_15_last      458913.0    -0.116630     4.646430 -1.270000e+02     47.773327
S_11_mean      458913.0    14.213772     3.926450  0.000000e+00     64.076923
S_11_std       453793.0     2.295283     1.846305  0.000000e+00     31.176915
S_11_min       458913.0    11.036641     4.036355  0.000000e+00     64.000000
S_11_max       458913.0    18.350598     6.290206  0.000000e+00    100.000000
S_11_last      458913.0    14.632819     4.870482  0.000000e+00     76.000000
D_62_mean      458913.0   -17.595375    37.402176 -1.270000e+02     10.855783
D_62_std       453793.0    11.032168    22.209229  0.000000e+00     90.656433
D_62_min       458913.0   -34.254086    56.459362 -1.270000e+02     10.852534
D_62_max       458913.0    -8.164697    31.625040 -1.270000e+02     11.100953
D_62_last      458913.0   -16.150633    42.558266 -1.270000e+02     11.099204

In [7]:
# Categorical Feature Statistics
cat_stats

'No categorical/object features to summarize.'

In [8]:
# Target Distribution
target_df

         count    pct
target
0       340085  74.11
1       118828  25.89

## Task Curation

In [9]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from sklearn.model_selection import RepeatedStratifiedKFold

n_repeats, n_splits = 1, 3
sklearn_splits = RepeatedStratifiedKFold(
    n_repeats=n_repeats, n_splits=n_splits, random_state=42
).split(X=df.drop(columns=[task_mold.target_column_name]), y=df[task_mold.target_column_name])

splits = {}
for split_i, (train_idx, test_idx) in enumerate(sklearn_splits):
    repeat_i = split_i // n_splits
    fold_i = split_i % n_splits
    if repeat_i not in splits:
        splits[repeat_i] = {}
    splits[repeat_i][fold_i] = (train_idx.tolist(), test_idx.tolist())

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Stratified 3-fold cross-validation following our default recommendations.",
    splits=splits,
)

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019bc7b9-1e0b-7253-869b-9e4ade870b35
9e84fd9337cc22f61bded997818f2883b6e94681607a275f51b7ef4f66721efc