### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="ancestry_study",
    dataset_year="1990",
    domain_str="biology & life sciences",
    # Data Source
    dataset_source="Other",
    original_dataset_source_download_link="https://github.com/CarolaHeinzel/BGA_Classification/blob/main/data/input_data/full_data.csv",
    download_description="""
We download the data from the GitHub repository and save it to a predefined folder.

mkdir -p local-data-warehouse/ancestry_study/ && curl -L -o local-data-warehouse/ancestry_study/filter_population.xlsx https://raw.githubusercontent.com/CarolaHeinzel/BGA-Classification/main/datat/filtered_population_eur_update.xlsx
""",
    # References
    academic_reference_bibtex="""@article{ruiz2023ancestry,
  title={Development and evaluations of the ancestry informative markers of the VISAGE Enhanced Tool for Appearance and Ancestry},
  author={Ruiz-Ram{\'\i}rez, Jorge and de La Puente, M and Xavier, Catarina and Ambroa-Conde, Adri{\'a}n and {\'A}lvarez-Dios, J and Freire-Aradas, A and Mosquera-Miguel, Ana and Ralf, Arwin and Amory, Christina and Katsara, Maria Alexandra and others},
  journal={Forensic Science International: Genetics},
  volume={64},
  pages={102853},
  year={2023},
  publisher={Elsevier}
}
""",
    academic_reference_bibtex_key="ruiz2023ancestry",
    license="Public",
    data_tags=["IID"],
    curation_comments="""
- 
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Population",
    problem_type="multiclass_classification",
    objective_metric_name="log_loss",
    stratify_on="Population",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_excel(f"{dataset_mold.path}/filter_population.xlsx")
df = df.drop(
    columns=[
        "Unnamed: 1",
        "SNP-Indel with complex genotype listing in VCF (not compiled)",
        "Unnamed: 3",
        "Unnamed: 4",
        "ID",
    ],
)

for col in df.columns:
    df[col] = df[col].astype("category")
    
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [3]:
# Use if needed to get see all cols of pandas dataframes
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
df.head()

,Population,rs1024124,rs1040934,rs1074689,rs10764919,rs10954737,rs10962599,rs1150911,rs11960137,rs1197062,rs12142199,rs1229984,rs12405776,rs12498138,rs12594144,rs12629397,rs12880237,rs12913832,rs1317026,rs13280988,rs1371048,rs1382568,rs1398461,rs1426654,rs1495085,rs1545397,rs1567803,rs1592672,rs166054,rs16891982,rs17086288,rs17130385,rs17287498,rs1757928,rs17625895,rs1796048,rs182857716,rs1871534,rs1924381,rs2024566,rs2026999,rs2156208,rs2196051,rs234623,rs2375771,rs2387842,rs2472304,rs2585339,rs2605361,rs262037,rs2715883,rs2737126,rs2789823,rs2814778,rs2835133,rs310362,rs367953206,rs3737576,rs3751050,rs3827760,rs3844336,rs3852253,rs3857620,rs3862700,rs392461,rs393953,rs408046,rs4308478,rs4465645,rs4471745,rs4540055,rs4657449,rs4737753,rs487750,rs5030240,rs556365,rs6088466,rs6437783,rs6496996,rs6504633,rs6588145,rs6701640,rs6754311,rs6894681,rs6933094,rs7151991,rs7171818,rs7252391,rs7594173,rs776912,rs7816786,rs7975017,rs7989291,rs8072587,rs809540,rs848461,rs881929,rs914468,rs9467370,rs9479657,rs9522149,rs9817359,rs9845503,rs9847307,rs9899480
0,09. Russia - Russian,CT,CT,AA,AA,TT,CC,GT,CC,GT,AA,CC,CC,GG,CC,TT,GG,GG,CC,AG,TT,CG,AG,AA,AA,AA,CT,GT,GG,GG,TT,GG,AC,AA,AA,CC,AA,GG,CC,AA,TT,CC,AG,AG,CG,CG,AG,GT,GT,CC,AA,CT,AA,TT,CC,TT,TT,TT,TT,AA,AA,AA,GG,TT,AG,AG,AG,TT,TT,GG,AC,GG,CC,TT,CC,AT,GG,TT,GG,CT,GG,AC,CC,AA,TT,GG,AA,AG,AG,AC,CT,CC,AG,GG,TT,CT,TT,CG,CC,CC,CC,GG,AG,TT,CC
1,British in England and Scotland,CT,TT,AT,AA,CT,CT,GG,CC,TT,AA,CC,CC,GG,CC,GT,AA,AG,CC,AA,GG,CC,GG,AA,AA,AA,TT,TT,GG,GG,TT,GG,CT,AA,CC,CC,AA,GG,CC,AG,CT,CC,AA,AG,CC,CC,GG,GT,GT,CT,GG,CT,AA,TT,CC,CT,TT,TT,TT,AA,AA,AA,GG,TT,CG,AA,AT,TT,TT,GG,AA,GG,CC,CT,CC,GG,GG,TT,AG,TT,GT,AC,CT,AA,TT,AG,AG,AA,AG,AC,TT,CT,AC,GG,TT,CT,GT,CG,CC,CC,CC,GG,AA,TT,CC
2,Toscani in Italia,CT,CT,AA,AA,TT,TT,GT,CC,TT,AA,CT,CC,GG,AC,CG,GG,AA,CC,AA,GG,CG,GG,AA,AA,AA,CT,TT,GG,GG,TT,GG,CT,AC,CC,CC,AA,GG,CT,GG,TT,CT,AA,AG,CG,CT,AA,TT,GG,CC,AA,CG,AA,TT,CC,TT,TT,TT,TT,AA,AG,AG,GG,TT,CG,AG,GG,CT,TT,GG,AT,GG,CT,CC,CG,GT,AG,TT,AG,TT,TT,CC,CC,AA,CT,AG,TT,AA,AA,AT,CT,CC,CG,CG,GT,CT,TT,CG,CC,CT,CC,GG,AA,TT,CC
3,British in England and Scotland,CT,CT,AA,AA,TT,TT,GT,CC,TT,AA,CC,CC,GG,CC,TT,AG,AG,CC,AA,GG,CC,GG,AA,AA,AA,TT,TT,GG,GG,TT,GG,AC,AA,AA,CC,AA,GG,CC,GG,TT,CT,AA,GG,CC,CT,AG,TT,TT,CC,AA,CC,AA,TT,AC,CT,TT,CT,CT,AA,AA,AA,GG,TT,CC,AG,AA,TT,TT,GG,AA,GG,CC,CT,CC,AT,GG,TT,AG,CT,GT,CC,CT,AA,TT,GG,GG,AG,AA,AA,TT,CC,AG,GG,CT,CC,GG,GG,CC,CC,CC,GG,AA,TT,CT
4,British in England and Scotland,CT,TT,TT,GG,TT,TT,CG,CG,TT,AA,CC,CC,GG,CC,GT,GG,GG,CC,AG,GG,GG,AG,AA,AA,AT,TT,TT,GG,GG,TT,GG,TT,AC,AC,CT,AA,GG,CC,GG,CT,CC,AG,GG,GG,TT,AA,TT,GT,CC,AA,GG,AA,TT,CC,CT,TT,TT,TT,AA,AA,AA,GG,TT,GG,GG,GG,TT,TT,GG,AT,GG,CC,CC,CG,AT,AG,CT,AG,TT,TT,CC,CT,AA,TT,AG,GT,GG,AA,AA,CT,CC,AC,GG,TT,CT,GT,GG,CC,CC,CC,GG,AT,TT,CC

## Data Checks

In [4]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 635
Columns: 105
Use sampling: False (sample size: 635)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['rs12629397', 'rs17287498', 'rs2737126', 'rs392461', 'rs393953', 'rs408046', 'rs1398461', 'rs5030240', 'rs6504633', 'rs1150911']
Rows remaining as candidates after top-10 filter: 0 (of 635)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [5]:
# Sample Rows
df_head

,Population,rs1024124,rs1040934,rs1074689,rs10764919,rs10954737,rs10962599,rs1150911,rs11960137,rs1197062,rs12142199,rs1229984,rs12405776,rs12498138,rs12594144,rs12629397,rs12880237,rs12913832,rs1317026,rs13280988,rs1371048,rs1382568,rs1398461,rs1426654,rs1495085,rs1545397,rs1567803,rs1592672,rs166054,rs16891982,rs17086288,rs17130385,rs17287498,rs1757928,rs17625895,rs1796048,rs182857716,rs1871534,rs1924381,rs2024566,rs2026999,rs2156208,rs2196051,rs234623,rs2375771,rs2387842,rs2472304,rs2585339,rs2605361,rs262037,rs2715883,rs2737126,rs2789823,rs2814778,rs2835133,rs310362,rs367953206,rs3737576,rs3751050,rs3827760,rs3844336,rs3852253,rs3857620,rs3862700,rs392461,rs393953,rs408046,rs4308478,rs4465645,rs4471745,rs4540055,rs4657449,rs4737753,rs487750,rs5030240,rs556365,rs6088466,rs6437783,rs6496996,rs6504633,rs6588145,rs6701640,rs6754311,rs6894681,rs6933094,rs7151991,rs7171818,rs7252391,rs7594173,rs776912,rs7816786,rs7975017,rs7989291,rs8072587,rs809540,rs848461,rs881929,rs914468,rs9467370,rs9479657,rs9522149,rs9817359,rs9845503,rs9847307,rs9899480
0,09. Russia - Russian,CT,CT,AA,AA,TT,CC,GT,CC,GT,AA,CC,CC,GG,CC,TT,GG,GG,CC,AG,TT,CG,AG,AA,AA,AA,CT,GT,GG,GG,TT,GG,AC,AA,AA,CC,AA,GG,CC,AA,TT,CC,AG,AG,CG,CG,AG,GT,GT,CC,AA,CT,AA,TT,CC,TT,TT,TT,TT,AA,AA,AA,GG,TT,AG,AG,AG,TT,TT,GG,AC,GG,CC,TT,CC,AT,GG,TT,GG,CT,GG,AC,CC,AA,TT,GG,AA,AG,AG,AC,CT,CC,AG,GG,TT,CT,TT,CG,CC,CC,CC,GG,AG,TT,CC
1,British in England and Scotland,CT,TT,AT,AA,CT,CT,GG,CC,TT,AA,CC,CC,GG,CC,GT,AA,AG,CC,AA,GG,CC,GG,AA,AA,AA,TT,TT,GG,GG,TT,GG,CT,AA,CC,CC,AA,GG,CC,AG,CT,CC,AA,AG,CC,CC,GG,GT,GT,CT,GG,CT,AA,TT,CC,CT,TT,TT,TT,AA,AA,AA,GG,TT,CG,AA,AT,TT,TT,GG,AA,GG,CC,CT,CC,GG,GG,TT,AG,TT,GT,AC,CT,AA,TT,AG,AG,AA,AG,AC,TT,CT,AC,GG,TT,CT,GT,CG,CC,CC,CC,GG,AA,TT,CC
2,Toscani in Italia,CT,CT,AA,AA,TT,TT,GT,CC,TT,AA,CT,CC,GG,AC,CG,GG,AA,CC,AA,GG,CG,GG,AA,AA,AA,CT,TT,GG,GG,TT,GG,CT,AC,CC,CC,AA,GG,CT,GG,TT,CT,AA,AG,CG,CT,AA,TT,GG,CC,AA,CG,AA,TT,CC,TT,TT,TT,TT,AA,AG,AG,GG,TT,CG,AG,GG,CT,TT,GG,AT,GG,CT,CC,CG,GT,AG,TT,AG,TT,TT,CC,CC,AA,CT,AG,TT,AA,AA,AT,CT,CC,CG,CG,GT,CT,TT,CG,CC,CT,CC,GG,AA,TT,CC
3,British in England and Scotland,CT,CT,AA,AA,TT,TT,GT,CC,TT,AA,CC,CC,GG,CC,TT,AG,AG,CC,AA,GG,CC,GG,AA,AA,AA,TT,TT,GG,GG,TT,GG,AC,AA,AA,CC,AA,GG,CC,GG,TT,CT,AA,GG,CC,CT,AG,TT,TT,CC,AA,CC,AA,TT,AC,CT,TT,CT,CT,AA,AA,AA,GG,TT,CC,AG,AA,TT,TT,GG,AA,GG,CC,CT,CC,AT,GG,TT,AG,CT,GT,CC,CT,AA,TT,GG,GG,AG,AA,AA,TT,CC,AG,GG,CT,CC,GG,GG,CC,CC,CC,GG,AA,TT,CT
4,British in England and Scotland,CT,TT,TT,GG,TT,TT,CG,CG,TT,AA,CC,CC,GG,CC,GT,GG,GG,CC,AG,GG,GG,AG,AA,AA,AT,TT,TT,GG,GG,TT,GG,TT,AC,AC,CT,AA,GG,CC,GG,CT,CC,AG,GG,GG,TT,AA,TT,GT,CC,AA,GG,AA,TT,CC,CT,TT,TT,TT,AA,AA,AA,GG,TT,GG,GG,GG,TT,TT,GG,AT,GG,CC,CC,CG,AT,AG,CT,AG,TT,TT,CC,CT,AA,TT,AG,GT,GG,AA,AA,CT,CC,AC,GG,TT,CT,GT,GG,CC,CC,CC,GG,AT,TT,CC

In [6]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,Population,category,0.0,0.0,10.0,"Iberian population in Spain, Toscani in Italia, Finnish in Finland, Utah Residents (CEPH) with N & W European ancestry, British in England and Scotland, 11. France - French, 13. Italy - Sardinian, Turkey, 09. Russia - Russian, 10. France - French Basque"
1,rs1024124,category,0.0,0.0,3.0,"CT, CC, TT"
2,rs1040934,category,0.0,0.0,3.0,"TT, CT, CC"
3,rs1074689,category,0.0,0.0,6.0,"AA, AT, AC, TT, CT, CC"
4,rs10764919,category,0.0,0.0,3.0,"AG, AA, GG"
5,rs10954737,category,0.0,0.0,3.0,"TT, CT, NN"
6,rs10962599,category,0.0,0.0,3.0,"TT, CT, CC"
7,rs1150911,category,0.0,0.0,6.0,"GT, GG, CG, CT, TT, CC"
8,rs11960137,category,0.0,0.0,3.0,"CC, CG, GG"
9,rs1197062,category,0.0,0.0,3.0,"TT, GT, GG"
10,rs12142199,category,0.0,0.0,4.0,"AA, AG, GG, NN"
11,rs1229984,category,0.0,0.0,3.0,"CC, CT, TT"
12,rs12405776,category,0.0,0.0,2.0,"CC, CT"
13,rs12498138,category,0.0,0.0,2.0,"GG, AG"
14,rs12594144,category,0.0,0.0,3.0,"CC, AC, AA"
15,rs12629397,category,0.0,0.0,7.0,"GT, TT, GG, CG, CT, CC, NN"
16,rs12880237,category,0.0,0.0,3.0,"AG, GG, AA"
17,rs12913832,category,0.0,0.0,4.0,"GG, AG, AA, NN"
18,rs1317026,category,0.0,0.0,3.0,"CC, CT, TT"
19,rs13280988,category,0.0,0.0,3.0,"AG, AA, GG"
20,rs1371048,category,0.0,0.0,3.0,"GT, GG, TT"
21,rs1382568,category,0.0,0.0,6.0,"GG, CG, AG, AC, CC, AA"
22,rs1398461,category,0.0,0.0,7.0,"AG, AC, AA, CG, GG, CC, NN"
23,rs1426654,category,0.0,0.0,2.0,"AA, AG"
24,rs1495085,category,0.0,0.0,3.0,"AA, AG, GG"
25,rs1545397,category,0.0,0.0,3.0,"AA, AT, TT"
26,rs1567803,category,0.0,0.0,3.0,"CT, TT, CC"
27,rs1592672,category,0.0,0.0,3.0,"TT, GT, GG"
28,rs166054,category,0.0,0.0,3.0,"GG, GT, TT"
29,rs16891982,category,0.0,0.0,3.0,"GG, CG, CC"
30,rs17086288,category,0.0,0.0,2.0,"TT, CT"
31,rs17130385,category,0.0,0.0,4.0,"GG, GT, NN, TT"
32,rs17287498,category,0.0,0.0,7.0,"CC, CT, AC, AT, TT, AA, NN"
33,rs1757928,category,0.0,0.0,3.0,"AA, AC, CC"
34,rs17625895,category,0.0,0.0,3.0,"AC, AA, CC"
35,rs1796048,category,0.0,0.0,3.0,"CC, CT, TT"
36,rs182857716,category,0.0,0.0,3.0,"AA, NN, AG"
37,rs1871534,category,0.0,0.0,3.0,"GG, CG, NN"
38,rs1924381,category,0.0,0.0,3.0,"CC, CT, TT"
39,rs2024566,category,0.0,0.0,4.0,"AA, AG, GG, NN"
40,rs2026999,category,0.0,0.0,3.0,"TT, CT, CC"
41,rs2156208,category,0.0,0.0,3.0,"CT, CC, TT"
42,rs2196051,category,0.0,0.0,3.0,"AA, AG, GG"
43,rs234623,category,0.0,0.0,3.0,"AG, GG, AA"
44,rs2375771,category,0.0,0.0,6.0,"CG, GG, CC, GT, CT, TT"
45,rs2387842,category,0.0,0.0,6.0,"CT, TT, CC, GT, CG, GG"
46,rs2472304,category,0.0,0.0,3.0,"AG, AA, GG"
47,rs2585339,category,0.0,0.0,6.0,"TT, GT, GG, CT, CG, NN"
48,rs2605361,category,0.0,0.0,6.0,"GT, GG, TT, AG, AT, NN"
49,rs262037,category,0.0,0.0,3.0,"CC, CT, TT"
50,rs2715883,category,0.0,0.0,3.0,"AA, AG, GG"
51,rs2737126,category,0.0,0.0,7.0,"CT, CC, CG, GT, TT, GG, NN"
52,rs2789823,category,0.0,0.0,3.0,"AA, AG, NN"
53,rs2814778,category,0.0,0.0,3.0,"TT, CT, NN"
54,rs2835133,category,0.0,0.0,3.0,"CC, AC, AA"
55,rs310362,category,0.0,0.0,4.0,"CT, TT, CC, NN"
56,rs367953206,category,0.0,0.0,2.0,"TT, NN"
57,rs3737576,category,0.0,0.0,3.0,"TT, CT, CC"
58,rs3751050,category,0.0,0.0,3.0,"TT, CT, CC"
59,rs3827760,category,0.0,0.0,2.0,"AA, AG"
60,rs3844336,category,0.0,0.0,3.0,"AA, AG, GG"
61,rs3852253,category,0.0,0.0,3.0,"AA, AG, GG"
62,rs3857620,category,0.0,0.0,2.0,"GG, AG"
63,rs3862700,category,0.0,0.0,3.0,"TT, GT, GG"
64,rs392461,category,0.0,0.0,7.0,"CG, GG, CC, AC, AG, AA, NN"
65,rs393953,category,0.0,0.0,7.0,"AG, GG, GT, AA, AT, TT, NN"
66,rs408046,category,0.0,0.0,7.0,"AG, GG, AA, GT, AT, NN, TT"
67,rs4308478,category,0.0,0.0,3.0,"TT, CT, CC"
68,rs4465645,category,0.0,0.0,2.0,"TT, CT"
69,rs4471745,category,0.0,0.0,3.0,"GG, AG, AA"
70,rs4540055,category,0.0,0.0,6.0,"AA, AT, TT, AC, CT, CC"
71,rs4657449,category,0.0,0.0,3.0,"GG, AG, AA"
72,rs4737753,category,0.0,0.0,4.0,"CC, CT, TT, NN"
73,rs487750,category,0.0,0.0,3.0,"CT, CC, TT"
74,rs5030240,category,0.0,0.0,7.0,"CC, CG, AC, GG, AG, AA, NN"
75,rs556365,category,0.0,0.0,6.0,"AT, TT, AA, GT, AG, GG"
76,rs6088466,category,0.0,0.0,4.0,"GG, AG, AA, NN"
77,rs6437783,category,0.0,0.0,3.0,"TT, CT, CC"
78,rs6496996,category,0.0,0.0,3.0,"GG, AG, AA"
79,rs6504633,category,0.0,0.0,7.0,"TT, CT, GT, CG, CC, GG, AG"
80,rs6588145,category,0.0,0.0,6.0,"GT, GG, TT, AG, AT, AA"
81,rs6701640,category,0.0,0.0,3.0,"CC, AC, AA"
82,rs6754311,category,0.0,0.0,3.0,"CT, CC, TT"
83,rs6894681,category,0.0,0.0,3.0,"AA, AG, NN"
84,rs6933094,category,0.0,0.0,5.0,"TT, CT, AT, CC, AC"
85,rs7151991,category,0.0,0.0,3.0,"GG, AG, AA"
86,rs7171818,category,0.0,0.0,6.0,"AG, AA, AT, GT, GG, TT"
87,rs7252391,category,0.0,0.0,3.0,"AA, AG, GG"
88,rs7594173,category,0.0,0.0,4.0,"AA, AG, GG, NN"
89,rs776912,category,0.0,0.0,6.0,"AA, AC, AT, CT, TT, CC"
90,rs7816786,category,0.0,0.0,4.0,"CT, TT, CC, NN"
91,rs7975017,category,0.0,0.0,4.0,"CC, CT, TT, NN"
92,rs7989291,category,0.0,0.0,6.0,"AC, CG, CC, AG, AA, GG"
93,rs8072587,category,0.0,0.0,3.0,"GG, CG, CC"
94,rs809540,category,0.0,0.0,6.0,"TT, CT, GT, CG, CC, GG"
95,rs848461,category,0.0,0.0,3.0,"CT, CC, TT"
96,rs881929,category,0.0,0.0,4.0,"GT, GG, TT, NN"
97,rs914468,category,0.0,0.0,4.0,"CG, GG, CC, GT"
98,rs9467370,category,0.0,0.0,3.0,"CC, AC, NN"
99,rs9479657,category,0.0,0.0,3.0,"CC, CT, TT"
100,rs9522149,category,0.0,0.0,3.0,"CC, CT, TT"
101,rs9817359,category,0.0,0.0,2.0,"GG, AG"
102,rs9845503,category,0.0,0.0,6.0,"AA, AG, AT, GT, GG, TT"
103,rs9847307,category,0.0,0.0,2.0,"TT, AT"
104,rs9899480,category,0.0,0.0,4.0,"CC, CT, TT, NN"

In [7]:
# Numeric Feature Statistics
numeric_stats

'No numeric features to summarize.'

In [8]:
# Categorical Feature Statistics
cat_stats

                                                               value  count  \
column      rank
Population  1                            Iberian population in Spain    107
            2                                      Toscani in Italia    107
            3                                     Finnish in Finland     99
            4     Utah Residents (CEPH) with N & W European ancestry     99
            5                        British in England and Scotland     91
rs1024124   1                                                     CT    321
            2                                                     CC    193
            3                                                     TT    121
rs1040934   1                                                     TT    378
            2                                                     CT    212
            3                                                     CC     45
rs1074689   1                                                     AA    262
            2                                                     AT    232
            3                                                     AC     59
            4                                                     TT     57
            5                                                     CT     23
rs10764919  1                                                     AG    284
            2                                                     AA    234
            3                                                     GG    117
rs10954737  1                                                     TT    578
            2                                                     CT     47
            3                                                     NN     10
rs10962599  1                                                     TT    323
            2                                                     CT    255
            3                                                     CC     57
rs1150911   1                                                     GT    195
            2                                                     GG    149
            3                                                     CG     99
            4                                                     CT     92
            5                                                     TT     74
rs11960137  1                                                     CC    469
            2                                                     CG    149
            3                                                     GG     17
rs1197062   1                                                     TT    579
            2                                                     GT     55
            3                                                     GG      1
rs12142199  1                                                     AA    406
            2                                                     AG    197
            3                                                     GG     31
            4                                                     NN      1
rs1229984   1                                                     CC    584
            2                                                     CT     49
            3                                                     TT      2
rs12405776  1                                                     CC    605
            2                                                     CT     30
rs12498138  1                                                     GG    550
            2                                                     AG     85
rs12594144  1                                                     CC    474
            2                                                     AC    152
            3                                                     AA      9
rs12629397  1                                                     GT    274
            2                                                     TT    187
            3                                                     GG    111
            4                                                     CG     34
            5                                                     CT     26
rs12880237  1                                                     AG    288
            2                                                     GG    271
            3                                                     AA     76
rs12913832  1                                                     GG    263
            2                                                     AG    229
            3                                                     AA    142
            4                                                     NN      1
rs1317026   1                                                     CC    604
            2                                                     CT     30
            3                                                     TT      1
rs13280988  1                                                     AG    289
            2                                                     AA    249
            3                                                     GG     97
rs1371048   1                                                     GT    292
            2                                                     GG    269
            3                                                     TT     74
rs1382568   1                                                     GG    191
            2                                                     CG    163
            3                                                     AG    137
            4                                                     AC     72
            5                                                     CC     42
rs1398461   1                                                     AG    206
            2                                                     AC    128
            3                                                     AA    118
            4                                                     CG     90
            5                                                     GG     72
rs1426654   1                                                     AA    629
            2                                                     AG      6
rs1495085   1                                                     AA    559
            2                                                     AG     75
            3                                                     GG      1
rs1545397   1                                                     AA    537
            2                                                     AT     91
            3                                                     TT      7
rs1567803   1                                                     CT    286
            2                                                     TT    274
            3                                                     CC     75
rs1592672   1                                                     TT    498
            2                                                     GT    128
            3                                                     GG      9
rs166054    1                                                     GG    613
            2                                                     GT     20
            3                                                     TT      2
rs16891982  1                                                     GG    531
            2                                                     CG     90
            3                                                     CC     14
rs17086288  1                                                     TT    631
            2                                                     CT      4
rs17130385  1                                                     GG    553
            2                                                     GT     80
            3                                                     NN      1
            4                                                     TT      1
rs17287498  1                                                     CC    217
            2                                                     CT    161
            3                                                     AC    139
            4                                                     AT     59
            5                                                     TT     28
rs1757928   1                                                     AA    417
            2                                                     AC    195
            3                                                     CC     23
rs17625895  1                                                     AC    287
            2                                                     AA    183
            3                                                     CC    165
rs1796048   1                                                     CC    372
            2                                                     CT    225
            3                                                     TT     38
rs182857716 1                                                     AA    630
            2                                                     NN      3
            3                                                     AG      2
rs1871534   1                                                     GG    627
            2                                                     CG      7
            3                                                     NN      1
rs1924381   1                                                     CC    471
            2                                                     CT    159
            3                                                     TT      5
rs2024566   1                                                     AA    295
            2                                                     AG    269
            3                                                     GG     70
            4                                                     NN      1
rs2026999   1                                                     TT    288
            2                                                     CT    278
            3                                                     CC     69
rs2156208   1                                                     CT    313
            2                                                     CC    186
            3                                                     TT    136
rs2196051   1                                                     AA    312
            2                                                     AG    271
            3                                                     GG     52
rs234623    1                                                     AG    318
            2                                                     GG    159
            3                                                     AA    158
rs2375771   1                                                     CG    255
            2                                                     GG    225
            3                                                     CC     62
            4                                                     GT     54
            5                                                     CT     33
rs2387842   1                                                     CT    234
            2                                                     TT    162
            3                                                     CC    112
            4                                                     GT     68
            5                                                     CG     55
rs2472304   1                                                     AG    278
            2                                                     AA    241
            3                                                     GG    116
rs2585339   1                                                     TT    368
            2                                                     GT    210
            3                                                     GG     35
            4                                                     CT     13
            5                                                     CG      8
rs2605361   1                                                     GT    267
            2                                                     GG    246
            3                                                     TT     84
            4                                                     AG     27
            5                                                     AT     10
rs262037    1                                                     CC    551
            2                                                     CT     81
            3                                                     TT      3
rs2715883   1                                                     AA    313
            2                                                     AG    254
            3                                                     GG     68
rs2737126   1                                                     CT    168
            2                                                     CC    155
            3                                                     CG    123
            4                                                     GT    102
            5                                                     TT     44
rs2789823   1                                                     AA    625
            2                                                     AG      7
            3                                                     NN      3
rs2814778   1                                                     TT    627
            2                                                     CT      7
            3                                                     NN      1
rs2835133   1                                                     CC    571
            2                                                     AC     61
            3                                                     AA      3
rs310362    1                                                     CT    288
            2                                                     TT    252
            3                                                     CC     94
            4                                                     NN      1
rs367953206 1                                                     TT    625
            2                                                     NN     10
rs3737576   1                                                     TT    569
            2                                                     CT     65
            3                                                     CC      1
rs3751050   1                                                     TT    498
            2                                                     CT    134
            3                                                     CC      3
rs3827760   1                                                     AA    621
            2                                                     AG     14
rs3844336   1                                                     AA    480
            2                                                     AG    139
            3                                                     GG     16
rs3852253   1                                                     AA    574
            2                                                     AG     58
            3                                                     GG      3
rs3857620   1                                                     GG    611
            2                                                     AG     24
rs3862700   1                                                     TT    526
            2                                                     GT     99
            3                                                     GG     10
rs392461    1                                                     CG    304
            2                                                     GG    174
            3                                                     CC    142
            4                                                     AC      7
            5                                                     AG      6
rs393953    1                                                     AG    214
            2                                                     GG    209
            3                                                     GT     90
            4                                                     AA     68
            5                                                     AT     40
rs408046    1                                                     AG    275
            2                                                     GG    180
            3                                                     AA    100
            4                                                     GT     45
            5                                                     AT     33
rs4308478   1                                                     TT    524
            2                                                     CT    106
            3                                                     CC      5
rs4465645   1                                                     TT    611
            2                                                     CT     24
rs4471745   1                                                     GG    567
            2                                                     AG     64
            3                                                     AA      4
rs4540055   1                                                     AA    329
            2                                                     AT    200
            3                                                     TT     53
            4                                                     AC     31
            5                                                     CT     20
rs4657449   1                                                     GG    496
            2                                                     AG    134
            3                                                     AA      5
rs4737753   1                                                     CC    550
            2                                                     CT     81
            3                                                     TT      3
            4                                                     NN      1
rs487750    1                                                     CT    285
            2                                                     CC    222
            3                                                     TT    128
rs5030240   1                                                     CC    295
            2                                                     CG    199
            3                                                     AC     74
            4                                                     GG     39
            5                                                     AG     20
rs556365    1                                                     AT    249
            2                                                     TT    158
            3                                                     AA    108
            4                                                     GT     59

In [9]:
# Target Distribution
target_df

                                                    count    pct
Population
Iberian population in Spain                           107  16.85
Toscani in Italia                                     107  16.85
Finnish in Finland                                     99  15.59
Utah Residents (CEPH) with N & W European ancestry     99  15.59
British in England and Scotland                        91  14.33
11. France - French                                    28   4.41
13. Italy - Sardinian                                  28   4.41
Turkey                                                 28   4.41
09. Russia - Russian                                   25   3.94
10. France - French Basque                             23   3.62

## Task Curation

In [10]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=20, n_splits=3, test_size=None

In [11]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [12]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to ancestry_study/019d9cb7-888d-7a7f-9e2b-4b13a0facdcb
019d9cb7-888d-7a7f-9e2b-4b13a0facdcb
987aa69208aadc3b07153284f1bc758ad88553f303bbb67a80c3ba51afedd9bb