### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="lung_cancer",
    dataset_year="2001",
    domain_str="medical & healthcare",
    # Data Source
    dataset_source="Other", # supplementary materials of the paper
    original_dataset_source_download_link="https://www.pnas.org/doi/10.1073/pnas.191502998#supplementary-materials",
    download_description=r"""
Cannot download automatically!

Click and download yourself: "https://www.pnas.org/doi/suppl/10.1073/pnas.191502998/suppl_file/dataseta_12600gene.xls"
mkdir -p local-data-warehouse/lung_cancer/ && mv dataseta_12600gene.xls local-data-warehouse/lung_cancer/
""",
    # References
    academic_reference_bibtex=r"""@article{bhattacharjee2001classification,
  title={Classification of human lung carcinomas by mRNA expression profiling reveals distinct adenocarcinoma subclasses},
  author={Bhattacharjee, Arindam and Richards, William G and Staunton, Jane and Li, Cheng and Monti, Stefano and Vasa, Priya and Ladd, Christine and Beheshti, Javad and Bueno, Raphael and Gillette, Michael and others},
  journal={Proceedings of the National Academy of Sciences},
  volume={98},
  number={24},
  pages={13790--13795},
  year={2001},
  publisher={The National Academy of Sciences}
}
""",
    academic_reference_bibtex_key="bhattacharjee2001classification",
    license="None", # not given as part of data download on the website, likely Copyright for the journal
    data_tags=["IID"],
    curation_comments="""
- The original data comes with lung adenocarcinoma and other adenocarcinomas merged into one class already. We keep the same and were not able to find a way to reverse this from the public data.
- We also drop the class "small-cell lung carcinoma" as it only has 6 samples, which is not a meaningful sample size for benchmarking, or the predictive task.  We could add another version with all classes in the future.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="CancerType",
    problem_type="multiclass_classification",
    objective_metric_name="log_loss",
    stratify_on="CancerType",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_excel(f"{dataset_mold.path}/dataseta_12600gene.xls")

# Translate into tabular format
df = (
    df
    .set_index("probe set")        # use probe set as row index → becomes columns after .T
    .drop(columns=["gene"])        # drop unwanted column
    .T                             # transpose
    .reset_index(names="CancerType")
)
# Extract classes from index
prefix_to_class = {
    "AD": "lung adenocarcinoma",
    "SQ": "squamous cell carcinoma",
    "COID": "pulmonary carcinoid",
    "SMCL": "small-cell lung carcinoma",
    "NL": "normal lung"
}
# extract prefix and map to class
df["CancerType"] = df["CancerType"].str.split("-").str[0].map(prefix_to_class)

df = df[df["CancerType"] != "small-cell lung carcinoma"]
df["CancerType"] = df["CancerType"].astype("category")

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 197
Columns: 12601
Use sampling: False (sample size: 197)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['AFFX-BioB-3_st', 'AFFX-DapX-5_at', 'AFFX-hum_alu_at', 'AFFX-MurIL2_at', 'AFFX-ThrX-5_at', 'AFFX-HUMISGF3A/M97935_3_at', '39733_at', '39721_at', '39722_at', '39750_at']
Rows remaining as candidates after top-10 filter: 0 (of 197)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

probe set           CancerType  AFFX-MurIL2_at  AFFX-MurIL10_at  \
0                  normal lung          -29.40           -27.79
1          lung adenocarcinoma            3.01            14.26
2          lung adenocarcinoma          -44.73           -15.36
3          lung adenocarcinoma          -34.15           -11.46
4                  normal lung          -14.29            -1.17

probe set  AFFX-MurIL4_at  AFFX-MurFAS_at  AFFX-BioB-5_at  AFFX-BioB-M_at  \
0                  -28.60           13.22         -45.500          -55.15
1                   17.71           25.73           5.295            0.47
2                  -21.08           -7.20         -25.160          -39.84
3                   -3.06           16.26         -34.150          -24.91
4                   -0.23            9.15         -20.850          -12.41

probe set  AFFX-BioB-3_at  AFFX-BioC-5_at  AFFX-BioC-3_at  AFFX-BioDn-5_at  \
0                  -31.01           -5.27         -55.960          -75.280
1                   10.06           27.89           1.265          -13.285
2                  -23.52          -13.73         -32.500          -80.570
3                  -22.39           29.69         -26.590          -62.710
4                  -14.29           44.78         -15.230          -52.720

probe set  AFFX-BioDn-3_at  AFFX-CreX-5_at  AFFX-CreX-3_at  AFFX-BioB-5_st  \
0                  -37.450          -36.64          -26.19          35.740
1                   31.435           -1.56           14.30          66.255
2                   65.700          -38.21          -16.99           6.700
3                   43.130          -31.63          -14.82          30.530
4                  -16.160          -16.16           -6.79          82.290

probe set  AFFX-BioB-M_st  AFFX-BioB-3_st  AFFX-BioC-5_st  AFFX-BioC-3_st  \
0                  -34.23         -91.380         -50.320         -31.820
1                    0.27         -53.125         -18.425           7.785
2                  -27.60        -114.730         -34.130         -25.160
3                   -5.58         -74.470         -27.430         -25.750
4                  -17.10         -82.710         -11.480         -26.480

probe set  AFFX-BioDn-5_st  AFFX-BioDn-3_st  AFFX-CreX-5_st  AFFX-CreX-3_st  \
0                  -43.890           -9.290         -28.600         -63.200
1                   29.665           23.865           8.325         -11.005
2                   17.330           -4.740         -24.340         -62.660
3                   17.100            6.180         -19.030         -27.430
4                  -13.350          -11.480          -8.660         -49.910

probe set  AFFX-hum_alu_at  AFFX-DapX-5_at  AFFX-DapX-M_at  AFFX-DapX-3_at  \
0                  6930.40          -25.38           -6.08          -31.01
1                  7286.44           14.18           22.37           11.14
2                  6662.25          -16.18           10.79          -34.94
3                  6921.25           -9.78            4.50          -13.14
4                  6564.45            1.65           11.96           -3.04

probe set  AFFX-LysX-5_at  AFFX-LysX-M_at  AFFX-LysX-3_at  AFFX-PheX-5_at  \
0                  -28.60          -26.19         -14.120         -26.990
1                   11.89           -0.82          28.745           0.605
2                  -21.08          -29.24           9.150         -30.050
3                   -3.90          -28.27           3.660         -26.590
4                   -4.92          -10.54          23.210         -13.350

probe set  AFFX-PheX-M_at  AFFX-PheX-3_at  AFFX-ThrX-5_at  AFFX-ThrX-M_at  \
0                  -26.19         -26.990         -21.360         -31.010
1                    6.66           3.755          15.795          11.765
2                  -22.71         -29.240         -24.340         -13.730
3                  -24.07          -8.940          -8.940         -13.140
4                  -13.35          -3.040          -3.980         -10.540

probe set  AFFX-ThrX-3_at  AFFX-TrpnX-5_at  AFFX-TrpnX-M_at  AFFX-TrpnX-3_at  \
0                  -55.96           -29.40           -48.72          -34.230
1                   -1.88            25.02            -2.89           12.595
2                  -57.77           -14.54           -49.62          -26.790
3                  -36.67           -14.82           -32.47          -15.660
4                  -31.16             1.65           -25.54           -0.230

probe set  AFFX-HUMISGF3A/M97935_5_at  AFFX-HUMISGF3A/M97935_MA_at  \
0                              -36.64                         5.99
1                               43.68                       189.86
2                               21.42                       180.64
3                               50.69                       225.35
4                                0.71                        30.71

probe set  AFFX-HUMISGF3A/M97935_MB_at  AFFX-HUMISGF3A/M97935_3_at  \
0                                 0.36                      184.82
1                               189.99                      570.27
2                               139.10                      568.78
3                               188.41                      690.64
4                                23.21                      198.65

probe set  AFFX-HUMRGE/M10098_5_at  AFFX-HUMRGE/M10098_M_at  \
0                           -47.91                  -74.470
1                            14.26                   -9.405
2                           -20.26                  -50.430
3                           -10.62                   13.740
4                           -10.54                  -53.660

probe set  AFFX-HUMRGE/M10098_3_at  AFFX-HUMGAPDH/M33197_5_at  \
0                           -79.31                   1274.140
1                           -24.30                   2701.245
2                           -83.01                   1806.000
3                           -19.87                   3300.510
4                           -31.16                    836.190

probe set  AFFX-HUMGAPDH/M33197_M_at  AFFX-HUMGAPDH/M33197_3_at  \
0                            1154.50                   2564.640
1                            2713.26                   3439.555
2                            1410.06                   2131.150
3                            3727.55                   4646.990
4                            1111.39                   2050.420

probe set  AFFX-HSAC07/X00351_5_at  AFFX-HSAC07/X00351_M_at  \
0                         3064.230                 4367.250
1                         3083.605                 4082.625
2                         3068.560                 4075.750
3                         3218.700                 3820.970
4                         2258.020                 3779.140

probe set  AFFX-HSAC07/X00351_3_at  AFFX-HUMTFRR/M11507_5_at  \
0                          4613.09                    -13.31
1                          4570.20                     34.18
2                          4033.33                     12.42
3                          4478.74                     10.38
4                          4556.38                     11.96

probe set  AFFX-HUMTFRR/M11507_M_at  AFFX-HUMTFRR/M11507_3_at  \
0                           -27.790                   -10.900
1                            13.385                    46.275
2                           -16.990                    27.970
3                            -3.060                    32.210
4                            -4.920                    24.150

probe set  AFFX-M27830_5_at  AFFX-M27830_M_at  AFFX-M27830_3_at  \
0                    -27.79            55.040            54.240
1                     15.13           102.555           106.705
2                    -19.44           116.770            78.850
3                     34.73           117.040            80.090
4                      4.46            92.610            44.780

probe set  AFFX-HSAC07/X00351_3_st  AFFX-HUMGAPDH/M33197_5_st  \
0                           162.19                     -30.21
1                           193.99                      16.73
2                            69.80                     -34.13
3                           515.66                      23.81
4                           358.37                     -23.66

probe set  AFFX-HUMGAPDH/M33197_M_st  AFFX-HUMGAPDH/M33197_3_st  \
0                            -14.120                      18.05
1                             34.165                      53.73
2                            -17.810                       5.88
3                             54.050                      89.32
4                             25.090                      32.59

probe set  AFFX-HSAC07/X00351_5_st  AFFX-HSAC07/X00351_M_st  \
0                          -32.620                    24.48
1                            8.375                    56.60
2                          -29.240                    13.24
3                           11.220                    51.53
4                            4.460                    54.16

probe set  AFFX-YEL002c/WBP1_at  AFFX-YEL018w/_at  AFFX-YEL024w/RIP1_at  \
0                       -28.600           -34.230                 -9.29
1                         4.875            -0.225                 16.88
2                       -22.710           -25.160                -12.10
3                       -11.460           -16.500                 12.90
4                        -0.230           -15.230                  7.27

probe set  AFFX-YEL021w/URA3_at  31307_at  31308_at  31309_r_at  31310_at  \
0                         18.05   -36.640   -47.910      -24.58   -25.380
1                         51.23     7.865     8.905       16.67    23.195
2                         14.06   -25.160   -36.580      -22.71    -9.650
3                         38.93   -13.140   -13.980       -8.10    -8.940
4                         66.35   -11.480    -6.790       -3.04     9.150

probe set  31311_at  31312_at  31313_at  31314_at  31315_at  31316_at  \
0             0.360   -49.520    -19.75    -31.82    660.05   -31.820
1            38.025    24.065     -5.19     10.52    325.67    10.145
2           -28.420   -33.310    -56.95     -7.20    988.79   -27.600
3            13.740    -1.380    -24.07     -8.94     68.33   -13.140
4            23.210   -35.850    -51.78      1.65    826.75    -1.170

probe set  31317_r_at  31318_at  31319_at  31320_at  31321_at  31322_at  \
0             150.890   -28.600    53.430    -41.47    37.350    -29.40
1             182.075    15.255    19.825    -10.16    50.895     18.58
2             284.820   -18.630   178.980    -45.54    23.880    -16.18
3             115.360    -4.740    41.450     33.05    30.530      0.30
4             179.870    -9.600    74.790     -8.66    60.720     -3.98

probe set  31323_r_at  31324_at  31325_at  31326_at  31327_at  31328_at  \
0              -77.69     1.160   -54.350   -83.330   -31.820   -15.730
1              -51.68    46.545     5.465   -26.725     7.365    25.285
2              -52.06   -11.280   -49.620  -134.240   -22.710    -0.660
3               -3.90    22.130   -21.550   -42.550   -13.140    -4.740
4              -31.16   -16.160   -40.540   -59.280    -0.230    23.210

probe set  31329_at  31330_at  31331_at  31332_at  31333_at  31334_at  \
0           -29.400   1763.65    -31.01    -42.28    -35.04   -27.790
1            14.885   2122.58     13.68     16.75     15.59    13.425
2           -18.630   1569.54    -13.73    -19.44    -16.99   -19.440
3            -8.940   3072.28     -5.58     -8.94     -0.54    -8.940
4            -3.980   2634.28      1.65      2.58      3.52    -1.170

probe set  31335_at  31336_at  31337_at  31338_at  31339_at  31340_at  \
0            -48.72    -23.77  -106.690    -27.79   -43.080   -26.990
1              3.70     13.51   -51.625     15.17    -0.235    15.175
2            -39.84    -19.44  -107.420    -18.63   -32.500   -18.630
3            -24.91    -14.82   -72.790     -6.42   -19.030    -8.100
4             -3.04      2.58  -100.520     -0.23   -11.480    -4.920

probe set  31341_at  31342_at  31343_at  31344_at  31345_at  31346_at  \
0           -50.320    -2.050    -34.23   -35.040   -15.730    -36.64
1            68.215    47.115     12.10    39.625    22.985     -6.74
2          -101.720    14.060    -17.81   -21.890   -18.630    -62.66
3           -44.230    56.570     -8.94    -4.740   -13.980    -16.50
4            -2.100    41.960     -7.73    11.020    -3.980    -41.47

probe set  31347_at  31348_at  31349_at  31350_at  31351_at  31352_at  \
0             7.600   -58.370    -50.32   -11.710   -87.360    -18.95
1           -89.285    -1.975      0.24    21.945   -18.715     25.65
2           378.870   -36.580    -39.84    -8.010   -37.390     -1.48
3             6.180   -17.350    -15.66    -8.940   -44.230      1.14
4            59.780   -27.410    -28.35    -3.040   -21.790      6.33

probe set  31353_f_at  31354_r_at  31355_at  31356_at  31357_at  31358_at  \
0               -6.08    -101.050    -15.73     34.13    -43.08   -33.430
1               62.23     -68.175     -1.01     75.58      1.97    15.875
2               81.32    -109.040     -1.48     35.34    -32.50   -17.810
3               96.88     -82.030    -10.62     28.85    -10.62   -10.620
4               90.73     -84.590     11.02     41.03    -17.10    -3.980

probe set  31359_at  31360_at  31361_at  31362_at  31363_at  31364_i_at  \
0            -35.04    -35.04   -26.190   -18.950    -22.97      -18.14
1              8.15     19.49    -0.125    -7.355     16.71       14.09
2            -24.34    -15.36   -33.310   -46.360    -15.36      -16.99
3            -10.62     -4.74   -19.030   -32.470    -18.19      -16.50
4            -11.48     -7.73   -16.160   -14.290      0.71       -5.85

probe set  31365_f_at  31366_at  31367_at  31368_at  31369_at  31370_at  \
0              -6.880   -43.080   -78.500    -31.01    -32.62   -31.010
1              18.125     6.455   -23.815     16.42     13.97    15.425
2             -13.730   -40.650   -67.540    -13.73    -24.34   -21.080
3               1.980   -22.390   -78.670     -3.06    -11.46    -4.740
4              11.960    -9.600   -62.090     -2.10     -5.85    -4.920

probe set  31371_at  31372_at  31373_at  31374_at  31375_at  31376_at  \
0            -31.01    -22.16   -19.750   -49.520     -5.27   -35.840
1             10.48     26.18     9.895    -2.225     61.04    15.335
2            -22.71    -22.71   -25.970   -35.760     43.54   -25.160
3             -2.22     61.61    -8.100   -27.430     67.49    -8.940
4             -3.04     -4.92    -3.040   -22.730    103.86    -9.600

probe set  31377_r_at  31378_at  31379_at  31380_at  31381_at  31382_f_at  \
0              -0.450     -6.08      7.60    -15.73    -23.77     -36.640
1              19.205     29.53     38.07     33.36      6.32      12.725
2             -12.910     -3.11      7.51     -9.65    -35.76     -28.420
3              -1.380      1.14     20.46    -19.03    -40.03      -9.780
4               7.270     15.71     17.59      9.15    -26.48      -7.730

probe set  31383_at  31384_at  31385_at  31386_at  31387_at  31388_at  \
0            -35.84   -109.91   2998.48     14.83    -25.38   -35.840
1             10.85    -10.07   3370.29     70.00     21.12    13.225
2              0.16   -109.86   2894.11    -15.36    -30.87   -21.080
3             -3.90    -70.27   2974.47     41.45     -5.58    -1.380
4             -2.10   -102.39   3844.74    126.38    -17.10    -3.040

probe set  31389_at  31390_at  31391_at  31392_r_at  31393_r_at  31394_at  \
0             29.31   -28.600   125.080      -17.34     -413.17    -31.01
1             55.28    11.975   127.755       29.68     -441.68     12.93
2             43.54   -21.080   135.790       -6.38     -717.71    -34.13
3            102.76   -12.300    84.290        0.30     -691.30    -11.46
4             14.77   -11.480    94.480       10.09     -539.56    -13.35

probe set  31395_i_at  31396_r_at  31397_at  31398_at  31399_at  31400_at  \
0              -37.45     -91.380    -18.95   -43.890    42.170    -22.16
1                6.95      37.065     15.75     7.945    77.085     13.80
2              -40.65     175.650    -15.36   -25.160    24.690    -21.08
3              -21.55       6.180    -12.30   -10.620    47.330     -8.94
4              -18.04     -27.410      5.40     2.580    97.300     -3.98

probe set  31401_r_at  31402_at  31403_at  31404_at  31405_at  31406_at  \
0              -30.21    -43.89     14.03    33.330   -67.230  -321.180
1               12.93     16.11     44.86    48.125   -34.165  -180.705
2              -20.26    -22.71     22.24   -17.810   -60.210  -295.700
3               -6.42     28.85     28.01   -91.280   -30.790  -321.520
4               -5.85     24.15     38.21     9.150   -30.230  -280.350

probe set  31407_at  31408_at  31409_at  31410_at  31411_at  31412_at  \
0            -28.60     -3.66   -26.190     85.62   -35.040    -36.64
1             12.43     22.99    12.885     63.96    11.185      9.52
2            -25.16     14.06   -21.080     -0.66   -39.020    -15.36
3             -8.94      0.30    -3.900     10.38   -14.820    -11.46
4             -2.10     12.90     6.330     13.84    -5.850      7.27

probe set  31413_at  31414_at  31415_at  31416_at  31417_at  31418_at  \
0            -10.90   -51.930   -21.360    -40.67    -10.10     39.76
1             30.90     1.315    23.275     33.55     53.97     51.57
2             -3.11   -56.140   -16.990      0.98     -1.48     32.88
3             -0.54   -19.030    -8.940      9.54     44.81     15.42
4              8.21     5.400     7.270     13.84     26.96     93.55

probe set  31419_r_at  31420_at  31421_at  31422_at  31423_at  31424_at  \
0             247.260    -26.99   -30.210    -53.54     -1.25    -20.55
1             231.515     14.80    10.645     -4.37     21.45     -0.37
2             450.110    -14.54   -16.180    -38.21     -3.11      5.88
3             309.300    -19.87    -6.420    -30.79     12.06     -8.94
4             424.210      9.15    -7.730    -32.10     30.71    -43.35

probe set  31425_g_at  31426_at  31427_at  31428_at  31429_at  31430_at  \
0             -12.510     23.68    -6.080   -59.180     58.26    -27.79
1              16.255     38.27     9.275   -41.775    110.96     16.42
2              -3.930     18.97   -10.460   -81.380     62.41    -25.16
3              -0.540     20.46   -11.460   -85.400     19.62     -9.78
4              10.090     27.90    23.210   -67.720     11.96     -3.04

probe set  31431_at  31432_g_at  31433_at  31434_at  31435_at  31436_s_at  \
0            457.34      675.70    -22.97     -2.05    -52.74     -24.580
1            239.97      414.46     22.03     43.34     -1.76      21.775
2            208.20      389.23     -9.65     14.06    -31.68      -7.200
3            258.93      330.28    -18.19     35.57    -17.35     -19.870
4            540.97      756.92     -3.04     26.96    -20.85     -35.850

probe set  31437_r_at  31438_s_at  31439_f_at  31440_at  31441_at  31442_at  \
0             -26.190      247.26     -53.540    146.85    -27.79    -43.08
1               6.285      299.06      47.325    135.48      8.87      5.96
2             -34.130       66.52       2.610    164.00    -21.89    -17.81
3             -22.390      228.71      27.170    112.84    -13.14    -16.50
4             -19.910      186.44     -14.290    125.44    -16.16     -3.04

probe set  31443_at  31444_s_at  31445_at  31446_s_at  31447_at  31448_s_at  \
0            34.940     4214.01   -47.110      -31.01    -14.92     -33.430
1            75.365     4267.41    -8.285       19.41     30.68       5.245
2            64.870     3785.72   -21.890      -12.10      5.88     -36.580
3            23.810     2879.60   -18.190        0.30      5.34     -15.660
4            67.280     3852.35   -18.980      -10.54      0.71     -10.540


In [5]:
# Feature Summary
summary.head(100) # limit number of cols we show...

,index,dtype,n_missing,pct_missing,n_unique,examples
0,CancerType,category,0.0,0.0,4.0,"lung adenocarcinoma, squamous cell carcinoma, pulmonary carcinoid, normal lung"
1,AFFX-MurIL2_at,float64,0.0,0.0,197.0,"-29.4, 3.01, -44.73, -34.15, -14.29, -0.81, 27.95, -25.49, -21.165, -15.82"
2,AFFX-MurIL10_at,float64,0.0,0.0,196.0,"11.93, -27.79, -15.36, 14.26, -11.46, -1.17, -12.5, 28.16, -11.535, -7.9"
3,AFFX-MurIL4_at,float64,0.0,0.0,192.0,"14.48, 0.01, 11.06, -13.45, -24.56, -0.23, -3.06, -28.6, -16.415, -12.22"
4,AFFX-MurFAS_at,float64,0.0,0.0,194.0,"7.83, 9.15, 15.68, 13.22, 25.73, 16.26, 38.98, -9.06, 3.99, -7.2"
5,AFFX-BioB-5_at,float64,0.0,0.0,194.0,"-5.54, -25.82, -26.24, -25.16, 5.295, -34.15, 20.6, -24.06, -20.85, -28.17"
6,AFFX-BioB-M_at,float64,0.0,0.0,196.0,"-36.98, -55.15, -39.84, 0.47, -24.91, -12.41, 13.24, -29.78, -28.16, -53.94"
7,AFFX-BioB-3_at,float64,0.0,0.0,194.0,"1.79, -27.9, -14.69, -23.52, 10.06, -22.39, 19.37, -21.2, -14.29, 16.89"
8,AFFX-BioC-5_at,float64,0.0,0.0,196.0,"21.05, -5.27, -13.73, 27.89, 29.69, 44.78, 45.11, 11.26, -3.525, 3.6"
9,AFFX-BioC-3_at,float64,0.0,0.0,196.0,"11.68, -55.96, -32.5, 1.265, -15.23, -40.23, 9.57, -36.2, -28.035, -53.94"
10,AFFX-BioDn-5_at,float64,0.0,0.0,194.0,"-56.38, -63.14, -49.42, -80.57, -13.285, -62.71, -34.56, -69.77, -52.72, -63.56"
11,AFFX-BioDn-3_at,float64,0.0,0.0,197.0,"-37.45, 31.435, 65.7, 43.13, -16.16, 10.45, 83.1, 82.58, 43.84, 41.01"
12,AFFX-CreX-5_at,float64,0.0,0.0,195.0,"-31.2, -19.73, -1.56, -38.21, -31.63, -25.75, -16.16, 8.34, -28.04, -30.2"
13,AFFX-CreX-3_at,float64,0.0,0.0,197.0,"-26.19, 14.3, -16.99, -14.82, -6.79, 13.67, 27.95, -18.34, -15.07, -12.22"
14,AFFX-BioB-5_st,float64,0.0,0.0,195.0,"29.05, 83.54, 66.255, 6.7, 30.53, 50.7, 82.29, 38.14, 55.325, 104.44"
15,AFFX-BioB-M_st,float64,0.0,0.0,196.0,"5.51, -34.23, -27.6, 0.27, -17.1, -4.84, -0.24, -27.63, 14.405, 0.01"
16,AFFX-BioB-3_st,float64,0.0,0.0,197.0,"-91.38, -53.125, -114.73, -74.47, -82.71, -94.92, -19.85, -89.06, -79.135, -94.23"
17,AFFX-BioC-5_st,float64,0.0,0.0,195.0,"-30.56, -36.95, -50.32, -34.13, -18.425, -116.63, -27.43, -34.78, -28.2, -74.08"
18,AFFX-BioC-3_st,float64,0.0,0.0,196.0,"-12.44, -31.82, -25.16, 7.785, -25.75, -26.48, 15.69, -8.06, -19.77, -23.0"
19,AFFX-BioDn-5_st,float64,0.0,0.0,194.0,"2.26, -6.45, 2.87, 17.33, 29.665, 17.1, 23.05, -21.2, -13.35, -17.71"
20,AFFX-BioDn-3_st,float64,0.0,0.0,196.0,"-3.95, -9.29, -4.74, 23.865, 6.18, -11.48, -14.95, 20.91, -21.58, -15.82"
21,AFFX-CreX-5_st,float64,0.0,0.0,195.0,"8.99, -32.6, 8.325, -24.34, -19.03, -2.42, -8.66, -28.35, -19.505, -31.64"
22,AFFX-CreX-3_st,float64,0.0,0.0,195.0,"-8.89, -29.85, -11.005, -62.66, -27.43, -69.99, -49.91, -58.35, -38.38, -57.53"
23,AFFX-hum_alu_at,float64,0.0,0.0,197.0,"6930.4, 7286.44, 6662.25, 6921.25, 6564.45, 8243.93, 5805.55, 7816.38, 6608.24, 5798.36"
24,AFFX-DapX-5_at,float64,0.0,0.0,197.0,"-25.38, 14.18, -16.18, -9.78, 1.65, 20.91, 26.72, -19.06, -11.585, -15.82"
25,AFFX-DapX-M_at,float64,0.0,0.0,195.0,"10.79, 23.565, -6.08, 4.5, 11.96, 28.16, 41.43, -5.48, 2.85, -12.89"
26,AFFX-DapX-3_at,float64,0.0,0.0,196.0,"-7.28, -31.01, -34.94, 11.14, -3.04, -1.62, 20.6, -26.2, -20.395, -17.97"
27,AFFX-LysX-5_at,float64,0.0,0.0,195.0,"5.24, -3.1, -28.6, -21.08, 11.89, 18.5, -3.9, -22.63, -15.11, -14.38"
28,AFFX-LysX-M_at,float64,0.0,0.0,194.0,"-16.99, -1.71, -22.27, -0.82, -10.54, -26.19, 13.24, -41.92, -20.965, -29.24"
29,AFFX-LysX-3_at,float64,0.0,0.0,195.0,"-0.99, 5.77, -14.12, 9.15, 28.745, 3.66, 23.21, -11.91, -4.425, 18.5"
30,AFFX-PheX-5_at,float64,0.0,0.0,195.0,"-1.81, -3.1, 0.605, -30.05, -26.59, -0.01, -13.35, -30.49, -19.825, -30.2"
31,AFFX-PheX-M_at,float64,0.0,0.0,194.0,"-6.23, -16.7, -32.59, 6.66, -13.35, -26.19, 32.85, -27.63, -21.005, -22.71"
32,AFFX-PheX-3_at,float64,0.0,0.0,193.0,"15.33, -9.28, -24.4, -36.13, -26.99, 20.11, 35.3, -8.94, 3.755, -15.82"
33,AFFX-ThrX-5_at,float64,0.0,0.0,197.0,"-21.36, 15.795, -24.34, -8.94, -3.98, 23.33, 25.5, -26.92, -18.365, -8.62"
34,AFFX-ThrX-M_at,float64,0.0,0.0,194.0,"-13.14, -11.82, 11.16, -13.73, 11.765, 20.11, 25.5, -20.49, -10.54, -14.38"
35,AFFX-ThrX-3_at,float64,0.0,0.0,193.0,"-31.16, -24.12, -42.65, -47.24, -55.96, -36.67, -11.27, -46.2, -57.77, -33.08"
36,AFFX-TrpnX-5_at,float64,0.0,0.0,195.0,"-1.88, -0.62, -29.4, -14.82, 1.65, 19.3, 26.72, -16.92, -12.185, -3.59"
37,AFFX-TrpnX-M_at,float64,0.0,0.0,194.0,"-42.39, -42.63, -37.43, -2.89, -49.62, -48.72, 9.57, -41.92, -25.54, -32.47"
38,AFFX-TrpnX-3_at,float64,0.0,0.0,195.0,"2.72, -2.16, 12.595, -26.79, -15.66, 12.06, -0.23, -27.63, -14.79, -12.94"
39,AFFX-HUMISGF3A/M97935_5_at,float64,0.0,0.0,194.0,"0.73, 0.71, 25.47, 43.68, 50.69, -36.64, 12.87, 61.04, 2.38, 21.42"
40,AFFX-HUMISGF3A/M97935_MA_at,float64,0.0,0.0,197.0,"5.99, 189.86, 180.64, 225.35, 30.71, 3.21, 176.2, 114.22, 225.14, 123.23"
41,AFFX-HUMISGF3A/M97935_MB_at,float64,0.0,0.0,197.0,"0.36, 189.99, 139.1, 188.41, 23.21, 21.72, 117.41, 66.08, 185.475, 97.95"
42,AFFX-HUMISGF3A/M97935_3_at,float64,0.0,0.0,197.0,"184.82, 570.27, 568.78, 690.64, 198.65, 82.1, 361.97, 600.53, 579.895, 412.16"
43,AFFX-HUMRGE/M10098_5_at,float64,0.0,0.0,196.0,"-3.99, -47.91, -20.26, 14.26, -10.54, 16.08, 27.95, -28.35, -22.835, -35.23"
44,AFFX-HUMRGE/M10098_M_at,float64,0.0,0.0,195.0,"-20.22, -51.06, -74.47, 13.74, -53.66, -41.04, 19.37, -66.92, -46.465, -64.01"
45,AFFX-HUMRGE/M10098_3_at,float64,0.0,0.0,196.0,"-29.77, -79.31, -83.01, -24.3, -19.87, -31.16, 3.44, -31.39, -38.325, -61.85"
46,AFFX-HUMGAPDH/M33197_5_at,float64,0.0,0.0,197.0,"1274.14, 2701.245, 1806.0, 3300.51, 836.19, 2255.82, 1659.19, 2199.73, 3165.08, 3789.69"
47,AFFX-HUMGAPDH/M33197_M_at,float64,0.0,0.0,197.0,"1154.5, 2713.26, 1410.06, 3727.55, 1111.39, 2468.15, 1814.04, 1871.12, 3335.95, 3699.22"
48,AFFX-HUMGAPDH/M33197_3_at,float64,0.0,0.0,197.0,"2564.64, 3439.555, 2131.15, 4646.99, 2050.42, 3514.3, 2265.29, 3051.06, 3621.16, 3702.13"
49,AFFX-HSAC07/X00351_5_at,float64,0.0,0.0,197.0,"3064.23, 3083.605, 3068.56, 3218.7, 2258.02, 1721.43, 2864.19, 3274.94, 3457.03, 3696.32"
50,AFFX-HSAC07/X00351_M_at,float64,0.0,0.0,197.0,"4367.25, 4082.625, 4075.75, 3820.97, 3779.14, 2788.89, 3450.63, 4378.92, 4694.1, 4375.3"
51,AFFX-HSAC07/X00351_3_at,float64,0.0,0.0,197.0,"4613.09, 4570.2, 4033.33, 4478.74, 4556.38, 3477.96, 3926.08, 4867.92, 3930.28, 4180.7"
52,AFFX-HUMTFRR/M11507_5_at,float64,0.0,0.0,196.0,"49.25, -13.31, 12.42, 34.18, 10.38, 11.96, 34.08, 18.5, 7.24, 18.71"
53,AFFX-HUMTFRR/M11507_M_at,float64,0.0,0.0,193.0,"-13.9, 12.38, -6.12, 5.02, -27.79, 1.6, 13.385, -3.06, -16.99, -5.03"
54,AFFX-HUMTFRR/M11507_3_at,float64,0.0,0.0,196.0,"23.84, -10.9, 27.97, 46.275, 32.21, 24.15, 58.59, 28.96, 34.61, 58.29"
55,AFFX-M27830_5_at,float64,0.0,0.0,192.0,"-17.87, -31.51, 18.63, 53.09, -20.9, 4.46, -19.44, -27.79, -17.31, -6.47"
56,AFFX-M27830_M_at,float64,0.0,0.0,196.0,"113.48, 55.04, 116.77, 102.555, 117.04, 92.61, 144.36, 111.91, 71.56, 77.03"
57,AFFX-M27830_3_at,float64,0.0,0.0,194.0,"54.24, 78.32, 54.21, 106.705, 44.78, 78.85, 37.76, 62.49, 1.78, 80.09"
58,AFFX-HSAC07/X00351_3_st,float64,0.0,0.0,197.0,"162.19, 193.99, 69.8, 515.66, 358.37, 182.84, 233.72, 59.63, 130.145, 71.26"
59,AFFX-HUMGAPDH/M33197_5_st,float64,0.0,0.0,197.0,"-30.21, 16.73, -34.13, 23.81, -23.66, -24.15, 27.95, -35.49, -14.18, -27.32"
60,AFFX-HUMGAPDH/M33197_M_st,float64,0.0,0.0,196.0,"11.06, -14.12, -17.81, 34.165, 54.05, 25.09, 57.36, 24.13, 0.85, -6.47"
61,AFFX-HUMGAPDH/M33197_3_st,float64,0.0,0.0,197.0,"18.05, 53.73, 5.88, 89.32, 32.59, 52.31, 89.23, 0.23, 21.01, -20.13"
62,AFFX-HSAC07/X00351_5_st,float64,0.0,0.0,194.0,"-6.79, -15.82, -2.23, 8.375, 4.46, -32.62, -21.73, 41.43, -51.92, -29.24"
63,AFFX-HSAC07/X00351_M_st,float64,0.0,0.0,196.0,"57.42, 24.48, 13.24, 56.6, 51.53, 54.16, 40.21, 68.41, 10.085, 14.39"
64,AFFX-YEL002c/WBP1_at,float64,0.0,0.0,196.0,"-26.06, -28.6, -22.71, 4.875, -11.46, -0.23, 27.95, 13.67, -21.415, -19.41"
65,AFFX-YEL018w/_at,float64,0.0,0.0,195.0,"-33.75, -3.3, -0.225, -25.16, -16.5, -11.27, -15.23, 27.95, -37.63, -23.81"
66,AFFX-YEL024w/RIP1_at,float64,0.0,0.0,197.0,"-9.29, 16.88, -12.1, 12.9, 7.27, 41.04, 35.3, -13.34, -4.95, -1.43"
67,AFFX-YEL021w/URA3_at,float64,0.0,0.0,196.0,"26.29, 18.05, 14.06, 51.23, 66.35, 52.31, 57.36, 21.68, 14.065, 37.41"
68,31307_at,float64,0.0,0.0,195.0,"-28.56, -8.08, 7.865, -25.16, -13.14, -11.27, -11.48, -33.35, -25.64, -28.76"
69,31308_at,float64,0.0,0.0,195.0,"-0.87, -17.71, 8.905, -36.58, -13.98, -8.06, -6.79, -29.06, -23.69, -30.92"
70,31309_r_at,float64,0.0,0.0,193.0,"-18.71, -15.14, -22.71, -8.1, -24.58, 4.01, 24.27, -20.49, 16.67, -13.66"
71,31310_at,float64,0.0,0.0,195.0,"-9.65, -12.46, -25.38, -8.94, 9.15, 8.04, 23.05, -9.77, -6.78, -9.34"
72,31311_at,float64,0.0,0.0,192.0,"21.66, 49.43, 10.19, 20.88, 49.36, 0.36, -28.42, 38.025, 8.255, 26.62"
73,31312_at,float64,0.0,0.0,194.0,"7.01, -19.06, -37.34, 24.065, -35.85, -49.52, -16.1, 15.69, -18.205, -33.31"
74,31313_at,float64,0.0,0.0,195.0,"-43.24, -21.58, -19.75, -56.95, -5.19, -28.97, -24.07, -30.88, -45.49, -32.195"
75,31314_at,float64,0.0,0.0,196.0,"-7.2, -31.82, 10.52, -8.94, 1.65, 16.89, 42.66, -17.63, -15.76, -22.29"
76,31315_at,float64,0.0,0.0,197.0,"660.05, 325.67, 988.79, 68.33, 826.75, -0.81, 3374.03, 1187.37, 162.64, 556.93"
77,31316_at,float64,0.0,0.0,195.0,"-15.4, -9.28, -31.82, -27.6, 10.145, 4.82, -13.14, -26.2, -18.65, -25.17"
78,31317_r_at,float64,0.0,0.0,197.0,"150.89, 182.075, 284.82, 115.36, 179.87, 328.96, 297.28, 214.26, 131.655, 238.93"
79,31318_at,float64,0.0,0.0,192.0,"-0.81, -3.41, -8.09, 1.79, 5.81, -4.74, -18.63, -9.6, -18.365, -18.69"
80,31319_at,float64,0.0,0.0,196.0,"29.82, 53.43, 178.98, 19.825, 41.45, 74.79, 1268.41, -12.88, 6.47, 61.89"
81,31320_at,float64,0.0,0.0,197.0,"-41.47, -10.16, -45.54, 33.05, -8.66, 23.33, -3.92, -65.49, -11.13, -30.2"
82,31321_at,float64,0.0,0.0,196.0,"41.31, 37.35, 23.88, 50.895, 30.53, 60.72, 48.79, 71.63, 20.39, 35.98"
83,31322_at,float64,0.0,0.0,193.0,"13.64, -12.8, 30.62, -8.45, -29.4, -3.23, 18.58, 0.3, -16.18, -10.78"
84,31323_r_at,float64,0.0,0.0,195.0,"-49.54, -86.09, -77.69, -52.06, -51.68, 8.04, -3.9, -92.63, -39.74, -46.74"
85,31324_at,float64,0.0,0.0,193.0,"26.72, 12.91, -8.03, 12.41, 1.16, -16.16, 72.44, -1.2, 22.13, -2.15"
86,31325_at,float64,0.0,0.0,197.0,"-54.35, 5.465, -49.62, -21.55, -40.54, -25.75, 34.08, -40.49, -47.645, -47.46"
87,31326_at,float64,0.0,0.0,197.0,"-83.33, -26.725, -134.24, -42.55, -59.28, -55.52, -75.0, -34.06, -50.13, -59.69"
88,31327_at,float64,0.0,0.0,193.0,"-7.17, 1.62, -10.75, -12.73, -31.82, -12.88, 7.365, -13.14, -22.71, -18.485"
89,31328_at,float64,0.0,0.0,193.0,"8.95, 21.11, 9.28, 2.32, -15.73, 12.87, 26.72, -4.74, 25.285, -1.705"
90,31329_at,float64,0.0,0.0,197.0,"-29.4, 14.885, -18.63, -8.94, -3.98, 21.72, 23.05, -17.63, -14.79, -12.22"
91,31330_at,float64,0.0,0.0,197.0,"1763.65, 2122.58, 1569.54, 3072.28, 2634.28, 1013.96, 2347.0, 2452.12, 1892.02, 3599.8"
92,31331_at,float64,0.0,0.0,195.0,"-10.92, -11.82, -31.01, -5.58, 1.65, 23.33, 27.95, -17.63, -13.045, -15.82"
93,31332_at,float64,0.0,0.0,193.0,"2.23, 11.06, -0.5, 16.69, -42.28, -2.42, 20.6, -8.94, 16.75, -14.38"
94,31333_at,float64,0.0,0.0,197.0,"-35.04, 15.59, -16.99, -0.54, 3.52, 5.62, 37.76, -19.06, -12.23, -9.34"
95,31334_at,float64,0.0,0.0,194.0,"-18.64, 12.02, 13.425, -27.79, -1.17, -19.44, 12.87, -21.92, -14.665, -8.94"
96,31335_at,float64,0.0,0.0,195.0,"-23.45, -24.63, -48.72, -39.84, 3.7, -16.1, -24.91, -29.78, -27.835, -28.76"
97,31336_at,float64,0.0,0.0,197.0,"-23.77, 13.51, -19.44, -14.82, 2.58, 8.84, 24.27, -22.63, -12.55, -15.82"
98,31337_at,float64,0.0,0.0,196.0,"-55.0, -106.69, -107.42, -51.625, -72.79, -100.52, -51.72, -81.25, -67.085, -28.04"
99,31338_at,float64,0.0,0.0,195.0,"-6.49, -7.48, 15.17, -18.63, -6.42, 9.65, -0.23, -19.77, -14.91, -16.53"

In [6]:
# Numeric Feature Statistics
numeric_stats.head(100) # limit number of cols we show...

,count,mean,std,min,max
AFFX-MurIL2_at,197.0,-8.542568,20.308881,-59.530,92.680
AFFX-MurIL10_at,197.0,4.500651,21.877427,-33.200,106.160
AFFX-MurIL4_at,197.0,0.162090,18.938182,-31.180,70.500
AFFX-MurFAS_at,197.0,19.507065,20.319746,-18.630,91.790
AFFX-BioB-5_at,197.0,-15.592559,19.091591,-67.000,46.340
AFFX-BioB-M_at,197.0,-21.783926,26.261016,-263.470,53.660
AFFX-BioB-3_at,197.0,-4.627035,25.392808,-44.000,210.100
AFFX-BioC-5_at,197.0,22.370042,26.250110,-34.810,114.500
AFFX-BioC-3_at,197.0,-23.943130,16.026964,-57.040,22.295
AFFX-BioDn-5_at,197.0,-53.042064,17.085969,-98.670,16.420
AFFX-BioDn-3_at,197.0,57.874214,43.810145,-96.970,221.450
AFFX-CreX-5_at,197.0,-20.020685,16.464077,-47.350,41.225
AFFX-CreX-3_at,197.0,2.547750,19.656056,-30.045,71.305
AFFX-BioB-5_st,197.0,58.344183,41.959590,-25.660,212.670
AFFX-BioB-M_st,197.0,-3.706874,60.613346,-748.770,88.300
AFFX-BioB-3_st,197.0,-79.787280,24.941532,-135.510,1.070
AFFX-BioC-5_st,197.0,-33.108697,22.140143,-116.630,30.290
AFFX-BioC-3_st,197.0,-14.084518,16.815466,-50.040,54.120
AFFX-BioDn-5_st,197.0,-4.768520,25.321571,-73.360,59.600
AFFX-BioDn-3_st,197.0,4.310588,27.176871,-55.690,125.280
AFFX-CreX-5_st,197.0,-9.062999,17.885533,-54.280,44.845
AFFX-CreX-3_st,197.0,-37.642961,22.340625,-88.840,40.880
AFFX-hum_alu_at,197.0,7144.912995,766.488104,5226.860,9379.100
AFFX-DapX-5_at,197.0,4.371197,18.873071,-28.625,80.250
AFFX-DapX-M_at,197.0,17.989484,20.781227,-70.950,82.450
AFFX-DapX-3_at,197.0,-5.775715,18.917865,-38.690,63.505
AFFX-LysX-5_at,197.0,2.082805,20.423596,-31.180,95.340
AFFX-LysX-M_at,197.0,-11.629437,18.171933,-46.570,65.590
AFFX-LysX-3_at,197.0,12.966489,19.591571,-32.650,69.610
AFFX-PheX-5_at,197.0,-9.494585,18.421615,-43.740,52.050
AFFX-PheX-M_at,197.0,-9.380762,17.119920,-42.430,48.030
AFFX-PheX-3_at,197.0,-3.200765,22.234377,-44.790,87.380
AFFX-ThrX-5_at,197.0,-2.486037,18.582750,-43.330,68.720
AFFX-ThrX-M_at,197.0,-1.900723,17.974724,-36.910,57.700
AFFX-ThrX-3_at,197.0,-32.174979,18.327740,-65.380,44.780
AFFX-TrpnX-5_at,197.0,4.891442,18.895737,-29.400,65.245
AFFX-TrpnX-M_at,197.0,-24.891345,16.681173,-57.430,43.135
AFFX-TrpnX-3_at,197.0,-2.260647,18.998831,-38.370,79.370
AFFX-HUMISGF3A/M97935_5_at,197.0,20.406354,25.378143,-36.640,152.850
AFFX-HUMISGF3A/M97935_MA_at,197.0,95.703291,79.648493,-14.690,485.970
AFFX-HUMISGF3A/M97935_MB_at,197.0,82.358773,60.650521,-7.280,405.860
AFFX-HUMISGF3A/M97935_3_at,197.0,315.285817,176.199890,52.320,993.000
AFFX-HUMRGE/M10098_5_at,197.0,-2.650182,30.595268,-47.910,234.245
AFFX-HUMRGE/M10098_M_at,197.0,-32.281857,31.084562,-93.550,132.725
AFFX-HUMRGE/M10098_3_at,197.0,-37.015694,48.367804,-89.840,522.290
AFFX-HUMGAPDH/M33197_5_at,197.0,2471.632005,944.027114,497.320,5234.210
AFFX-HUMGAPDH/M33197_M_at,197.0,2518.108198,970.351633,774.950,5262.770
AFFX-HUMGAPDH/M33197_3_at,197.0,3343.897411,903.246052,1066.630,5436.390
AFFX-HSAC07/X00351_5_at,197.0,3084.811726,731.691841,963.330,4872.470
AFFX-HSAC07/X00351_M_at,197.0,3939.144746,731.951548,1730.030,5511.780
AFFX-HSAC07/X00351_3_at,197.0,4260.207132,596.687693,2387.640,5520.630
AFFX-HUMTFRR/M11507_5_at,197.0,26.927602,23.903458,-22.660,122.420
AFFX-HUMTFRR/M11507_M_at,197.0,7.168892,24.710986,-30.590,189.450
AFFX-HUMTFRR/M11507_3_at,197.0,51.901796,50.467028,-10.900,539.030
AFFX-M27830_5_at,197.0,11.773469,41.931441,-38.570,392.900
AFFX-M27830_M_at,197.0,110.712750,74.233540,-39.370,497.185
AFFX-M27830_3_at,197.0,67.807561,40.907834,-121.480,216.260
AFFX-HSAC07/X00351_3_st,197.0,186.646939,111.327312,16.940,576.020
AFFX-HUMGAPDH/M33197_5_st,197.0,-7.131142,28.078697,-72.340,84.110
AFFX-HUMGAPDH/M33197_M_st,197.0,19.862390,28.684957,-38.540,98.890
AFFX-HUMGAPDH/M33197_3_st,197.0,30.781053,32.803764,-24.700,144.190
AFFX-HSAC07/X00351_5_st,197.0,-7.782691,24.789268,-68.910,69.160
AFFX-HSAC07/X00351_M_st,197.0,37.739294,30.557510,-17.460,131.470
AFFX-YEL002c/WBP1_at,197.0,0.465935,19.194576,-41.400,76.710
AFFX-YEL018w/_at,197.0,-11.534268,18.861315,-52.040,50.100
AFFX-YEL024w/RIP1_at,197.0,13.848837,19.841084,-26.910,80.825
AFFX-YEL021w/URA3_at,197.0,46.319112,27.824140,-3.110,140.500
31307_at,197.0,-10.368490,18.126556,-41.710,54.025
31308_at,197.0,-8.738642,20.171347,-47.910,122.110
31309_r_at,197.0,-0.753380,18.569777,-33.850,62.520
31310_at,197.0,3.340597,18.092945,-27.630,69.495
31311_at,197.0,30.828832,21.848857,-28.420,116.650
31312_at,197.0,-6.677322,21.598212,-60.000,62.550
31313_at,197.0,-30.985846,23.474041,-92.120,61.630
31314_at,197.0,4.143689,19.994847,-32.360,88.670
31315_at,197.0,676.736046,686.092216,-15.430,3374.030
31316_at,197.0,-4.536337,18.167643,-35.740,62.520
31317_r_at,197.0,233.040477,71.342961,93.370,534.320
31318_at,197.0,-2.236925,17.340220,-33.300,57.120
31319_at,197.0,147.045755,214.948778,-47.560,1268.410
31320_at,197.0,-9.995947,38.981156,-137.840,104.530
31321_at,197.0,44.810791,23.636238,-2.090,148.410
31322_at,197.0,1.886159,19.613068,-32.590,68.720
31323_r_at,197.0,-28.998739,36.146132,-157.970,77.590
31324_at,197.0,24.561599,24.283455,-16.160,129.970
31325_at,197.0,-25.357310,20.649747,-62.430,48.330
31326_at,197.0,-59.980588,37.178299,-188.930,52.420
31327_at,197.0,-3.276341,18.437910,-37.370,69.620
31328_at,197.0,14.716481,22.132686,-28.580,111.320
31329_at,197.0,1.929687,18.741038,-29.680,75.820
31330_at,197.0,2225.836726,639.856295,724.130,4332.580
31331_at,197.0,1.265013,18.938444,-34.550,63.400
31332_at,197.0,0.454784,19.216730,-42.280,77.080
31333_at,197.0,2.119471,19.029664,-35.040,74.050
31334_at,197.0,-2.376675,18.451193,-35.030,61.740
31335_at,197.0,-11.272944,22.553711,-64.960,67.790
31336_at,197.0,-0.666658,18.254747,-35.310,65.770
31337_at,197.0,-62.129886,48.560336,-139.200,243.940
31338_at,197.0,1.356134,18.063055,-31.290,67.840
31339_at,197.0,-15.481633,18.388695,-50.630,50.640

In [7]:
# Categorical Feature Statistics
cat_stats

                                   value  count    pct
column     rank
CancerType 1         lung adenocarcinoma    139  70.56
           2     squamous cell carcinoma     21  10.66
           3         pulmonary carcinoid     20  10.15
           4                 normal lung     17   8.63

In [8]:
# Target Distribution
target_df

                         count    pct
CancerType
lung adenocarcinoma        139  70.56
squamous cell carcinoma     21  10.66
pulmonary carcinoid         20  10.15
normal lung                 17   8.63

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=20, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to lung_cancer/019d6e03-622d-7ca8-b1bf-5ef42a921012
019d6e03-622d-7ca8-b1bf-5ef42a921012
dcbbd1c7784ac8b7eaf9e2b4349ba9d872d2832b46144a77a0768e9d2eea45f9